### PR TITLE
python.pkgs.tensorflow: 1.14.0 -> 1.15.0

### LINKED ISSUE #71578: python3Packages.tensorflow build is broken on master
**Describe the bug**
build fails

```
Analyzing: 2 targets (358 packages loaded, 7386 targets configured)
    currently loading: tensorflow/core/platform/cloud
ERROR: /build/output/external/jpeg/BUILD.bazel:220:15: in nocopts attribute of cc_library rule @jpeg//:simd_x86_64: This attribute was removed. See https://github.com/bazelbuild/bazel/issues/8706 for details.
Analyzing: 2 targets (359 packages loaded, 7419 targets configured)
    currently loading: tensorflow/core/platform/cloud
ERROR: /build/output/external/jpeg/BUILD.bazel:220:15: in nocopts attribute of cc_library rule @jpeg//:simd_x86_64: This attribute was removed. See https://github.com/bazelbuild/bazel/issues/8706 for details.
Analyzing: 2 targets (359 packages loaded, 7419 targets configured)
    currently loading: tensorflow/core/platform/cloud
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis of target '@jpeg//:simd_x86_64' failed; build aborted
Analyzing: 2 targets (360 packages loaded, 7419 targets configured)
INFO: Elapsed time: 7.017s
Analyzing: 2 targets (360 packages loaded, 7419 targets configured)
INFO: 0 processes.
Analyzing: 2 targets (360 packages loaded, 7419 targets configured)
FAILED: Build did NOT complete successfully (360 packages loaded, 7419 targets\
 configured)
FAILED: Build did NOT complete successfully (360 packages loaded, 7419 targets\
 configured)
```

**To Reproduce**
`nix-build -A python3Packages.tensorlfow`

### PR DESCRIPTION
**Pull request by timokau**
###### Motivation for this change

Continuation of  https://github.com/NixOS/nixpkgs/pull/70910.
fixes #71578.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by timokau** [comment]
I have decided to keep the default to no-cuda for now, unless there are any objections.

**Comment by timokau** [comment]
This should also fix the tensorflow build, which was broken by https://github.com/NixOS/nixpkgs/pull/69252.

**Comment by timokau** [comment]
Unfortunately the build still doesn't quite work with bazel 1.0. Upstream is tracking this here: https://github.com/tensorflow/tensorflow/pull/33240

**Comment by flokli** [comment]
Upstream is working on a fix in https://github.com/tensorflow/tensorflow/pull/33415.

**Comment by coreyoconnor** [comment]
Did a quick pass at applying this patch. Unfortunately, I'm unable to build this with upstream's fix applied. Will continue looking into it some later day.

Adding to here FYI:

* https://github.com/coreyoconnor/nixpkgs/commit/8f226c8d13a818ab19f7e5cb364510584c16fa6f

on that nixpkgs fork the build fails with:

~~~
/nix/store/jy6zl5dkw5rcjczm1arjqxz95l9d40i7-binutils-2.31.1/bin/ld: bazel-out/host/bin/tensorflow/core/libop_gen_lib.a(op_gen_lib.o): in function `std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, tensorflow::ApiDef>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, tensorflow::ApiDef> >, std::__deta
il::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail
::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_insert_unique_node(unsigned long, unsigned long, std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<
char>, std::allocator<char> > const, tensorflow::ApiDef>, true>*)':
op_gen_lib.cc:(.text._ZNSt10_HashtableINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_N10tensorflow6ApiDefEESaISA_ENSt8__detail10_Select1stESt8equal_toIS5_ESt4hashIS5_ENSC_18_Mod_range_hashingENSC_20_Default_ranged_hashENSC_20_Prime_reha
sh_policyENSC_17_Hashtable_traitsILb1ELb0ELb1EEEE21_M_insert_unique_nodeEmmPNSC_10_Hash_nodeISA_Lb1EEE[_ZNSt10_HashtableINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_N10tensorflow6ApiDefEESaISA_ENSt8__detail10_Select1stESt8equal_toIS5_
ESt4hashIS5_ENSC_18_Mod_range_hashingENSC_20_Default_ranged_hashENSC_20_Prime_rehash_policyENSC_17_Hashtable_traitsILb1ELb0ELb1EEEE21_M_insert_unique_nodeEmmPNSC_10_Hash_nodeISA_Lb1EEE]+0xe1): undefined reference to `tensorflow::ApiDef::~ApiDef()'
/nix/store/jy6zl5dkw5rcjczm1arjqxz95l9d40i7-binutils-2.31.1/bin/ld: bazel-out/host/bin/tensorflow/core/libop_gen_lib.a(op_gen_lib.o): in function `std::__detail::_Map_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, s
td::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, tensorflow::ApiDef>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, tensorflow::ApiDef> >, st
d::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std:
:__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true>, true>::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
op_gen_lib.cc:(.text._ZNSt8__detail9_Map_baseINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS6_N10tensorflow6ApiDefEESaISB_ENS_10_Select1stESt8equal_toIS6_ESt4hashIS6_ENS_18_Mod_range_hashingENS_20_Default_ranged_hashENS_20_Prime_rehash_po
licyENS_17_Hashtable_traitsILb1ELb0ELb1EEELb1EEixERS8_[_ZNSt8__detail9_Map_baseINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS6_N10tensorflow6ApiDefEESaISB_ENS_10_Select1stESt8equal_toIS6_ESt4hashIS6_ENS_18_Mod_range_hashingENS_20_Default
_ranged_hashENS_20_Prime_rehash_policyENS_17_Hashtable_traitsILb1ELb0ELb1EEELb1EEixERS8_]+0xa8): undefined reference to `tensorflow::ApiDef::ApiDef()'
/nix/store/jy6zl5dkw5rcjczm1arjqxz95l9d40i7-binutils-2.31.1/bin/ld: bazel-out/host/bin/tensorflow/core/libop_gen_lib.a(op_gen_lib.o): in function `std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, tensorflow::ApiDef>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, tensorflow::ApiDef> >, std::__deta
il::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail
::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::~_Hashtable()':
op_gen_lib.cc:(.text._ZNSt10_HashtableINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_N10tensorflow6ApiDefEESaISA_ENSt8__detail10_Select1stESt8equal_toIS5_ESt4hashIS5_ENSC_18_Mod_range_hashingENSC_20_Default_ranged_hashENSC_20_Prime_reha
sh_policyENSC_17_Hashtable_traitsILb1ELb0ELb1EEEED2Ev[_ZNSt10_HashtableINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_N10tensorflow6ApiDefEESaISA_ENSt8__detail10_Select1stESt8equal_toIS5_ESt4hashIS5_ENSC_18_Mod_range_hashingENSC_20_Defa
ult_ranged_hashENSC_20_Prime_rehash_policyENSC_17_Hashtable_traitsILb1ELb0ELb1EEEED5Ev]+0x28): undefined reference to `tensorflow::ApiDef::~ApiDef()'
/nix/store/jy6zl5dkw5rcjczm1arjqxz95l9d40i7-binutils-2.31.1/bin/ld: bazel-out/host/bin/tensorflow/core/libop_gen_lib.a(op_gen_lib.o): in function `tensorflow::ApiDefMap::ApiDefMap(tensorflow::OpList const&)':
op_gen_lib.cc:(.text._ZN10tensorflow9ApiDefMapC2ERKNS_6OpListE+0xcc): undefined reference to `tensorflow::ApiDef::ApiDef()'
....
~~~

**Comment by coreyoconnor** [comment]
Ignore my prior comment. Used an out-of-date version of this pull request. Re-testing.

**Comment by coreyoconnor** [comment]
Re-tested using master + this patch, with adjustments to the deps SHA. On our build farm, both cuda and non-cuda fail to compile with similar link errors:

~~~
bazel-out/host/bin/tensorflow/python/gen_nn_ops_py_wrappers_cc: symbol lookup error: /build/output/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/../../_solib_k8/_U_S_Stensorflow_Spython_Cgen_Unn_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so.1: undefined symbol: _ZN10tensorflow16ProtoDebugStringB5cxx11ERKNS_16DeviceAttributesE
~~~

Unfortunate that the tensorflow build is a monolith. :( Nothing for nixpkgs to resolve afaict. Kinda surprising tho. Pain to test/build.

**Comment by timor** [comment]
@coreyoconnor This seems to stem from `protobuf` being an alias for `protobuf3_7`.  Tensorflow-1.15.0 does seem to require `protobuf3_6` though.

Relevant upstream commit: https://github.com/tensorflow/tensorflow/commit/f92a0e6a9becfb95429bbcc886d5d7dc494fc704

**Comment by timokau** [comment]
Thanks to @scentini in https://github.com/NixOS/nixpkgs/pull/71282, it builds now!

Things left to do:
- some sanity checking
- fill in the cuda hash

If anybody else wants to do some testing, now is the time.

**Comment by coreyoconnor** [comment]
> 
> ```
> bazel-out/host/bin/tensorflow/python/gen_nn_ops_py_wrappers_cc: symbol lookup error: /build/output/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/../../_solib_k8/_U_S_Stensorflow_Spython_Cgen_Unn_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so.1: undefined symbol: _ZN10tensorflow16ProtoDebugStringB5cxx11ERKNS_16DeviceAttributesE
> ```

this issue is resolved with timokau changes. Unfortunately, I missed the latest patch and ran into the gast error. XD

Testing again.

**Comment by timokau** [comment]
Yeah, sorry about that. I made some mistake during fixup before push. Should work now.

**Comment by coreyoconnor** [comment]
@timokau no problem!

Subsequent build failed on this 

~~~
      # for some reason some of the required libs are in the targets/x86_64-linux                                                                                                             
      # directory; not sure why but this works around it                                                                                                                                      
      "${cudatoolkit}/targets/${stdenv.system}"                                                                                                                                               
~~~

I'm building using cudatoolkit 10. Which is not the default in all-packages. I wonder if this workaround is specific to cudatoolkit 9?

**Comment by coreyoconnor** [comment]
Success! Compiled without issue with cudatoolkit_10 (once I removed that workaround). So I presume yes: that is specific to cudatoolkit_9.

**Comment by timokau** [comment]
Thanks for testing! I don't quite understand what you're saying though. So the workaround is not necessary for a newer cudatoolkit? That's good, but why does it fail? If the workaround is not necessary, it still shouldn't do any harm right?

**Comment by timokau** [comment]
Merging now, since this has been broken on master for so long. Any fixups can be made in followup PRs. For example, python2 is still broken. It's probably not too difficult to fix, but I don't plan to invest more time in this for now.

**Comment by coreyoconnor** [comment]
Correct: the work around is not needed for newer cuda. The workaround
actually instructs nix to copy that specific path to the store. Which does
not exist on newer cuda toolkit. Thus it will fail due to not finding the
path.

(On mobile)

**Comment by coreyoconnor** [comment]
Oh: the default cudtoolkit is 9. Which this does compile fine for. Fixing
for cuda 10 can wait :) definitely not a merge blocker

**Comment by timokau** [comment]
Oh, so the path doesn't exist. Its weird that the workaround is necessary at all. The best solution would probably be to fix the cudatoolkit 9 build to make the workaround unnecessary for both versions.

Do feel free to create a PR to fix this either in the tensorflow build or in the cudatoolkit build. If you do, ping me and I'll review (to the best of my ability, since I don't have a nvida card) :)

**Comment by coreyoconnor** [comment]
@timokau
 
will do! Thanks again for figuring this out :)

**Pull request merged**
