### PR TITLE
pythonPackages.jishaku: patch hardcoded /bin/bash default to /bin/sh

### PR DESCRIPTION
**Pull request by itslychee**
## Description of changes

This adds a patch to `jishaku` by changing the default (`/bin/bash`) to `/bin/sh` if `$SHELL` is not present. I didn't have this problem while initially packaging jishaku as my `$SHELL` was set, but inside a systemd service it isn't set and that's where I got the problem.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by itslychee** [comment]
I'll go ahead and update this package to reflect the recent python wrapper changes in a separate commit.

**Comment by a-n-n-a-l-e-e** [comment]
shouldn't the replacement be nix bash?
```nix
  postPatch = ''
    substituteInPlace jishaku/shell.py \
      --replace-fail '"/bin/bash"' '"${lib.getBin bash}/bin/bash"'
  '';
```

**Comment by itslychee** [comment]
good question, I'm using /bin/sh because it points to the current bash derivation but I'm also not opposed to your solution.

**Comment by a-n-n-a-l-e-e** [comment]
> good question, I'm using /bin/sh because it points to the current bash derivation but I'm also not opposed to your solution.

that is only on nixos. on darwin or other linux platforms /bin/sh does not point to nix bash.

**Comment by itslychee** [comment]
> > good question, I'm using /bin/sh because it points to the current bash derivation but I'm also not opposed to your solution.
> 
> that is only on nixos. on darwin or other linux platforms /bin/sh does not point to nix bash or bash at all.

ah okay! In that case I'll use your suggestion, thank u

**Review by ghost — APPROVED** [review]

**Comment by a-n-n-a-l-e-e** [comment]
@ofborg eval

**Pull request merged**
