### PR TITLE
Kernel updates for 2023-06-06

### PR DESCRIPTION
**Pull request by K900**
###### Description of changes

Some interesting amd_pstate fixes.

https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.3.6

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by K900** [comment]
`nixosTests.latestKernel.login` passes on 6.3.6.

**Review by yu-re-ka — APPROVED** [review]

**Comment by lovesegfault** [comment]
Result of `nixpkgs-review pr 236296` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.kernels.linux_4_14_hardened</li>
    <li>linuxKernel.kernels.linux_4_14_hardened.dev</li>
    <li>linuxKernel.kernels.linux_4_19_hardened</li>
    <li>linuxKernel.kernels.linux_4_19_hardened.dev</li>
    <li>linuxKernel.kernels.linux_5_4_hardened</li>
    <li>linuxKernel.kernels.linux_5_4_hardened.dev</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>linuxKernel.kernels.linux_rt_5_10</li>
    <li>linuxKernel.kernels.linux_rt_5_10.dev</li>
  </ul>
</details>
<details>
  <summary>20 packages built:</summary>
  <ul>
    <li>linuxKernel.kernels.linux_5_10</li>
    <li>linuxKernel.kernels.linux_5_10.dev</li>
    <li>linuxKernel.kernels.linux_5_10_hardened</li>
    <li>linuxKernel.kernels.linux_5_10_hardened.dev</li>
    <li>linuxKernel.kernels.linux_5_15</li>
    <li>linuxKernel.kernels.linux_5_15.dev</li>
    <li>linuxKernel.kernels.linux_5_15_hardened</li>
    <li>linuxKernel.kernels.linux_5_15_hardened.dev</li>
    <li>linuxKernel.kernels.linux_5_4</li>
    <li>linuxKernel.kernels.linux_5_4.dev</li>
    <li>linuxKernel.kernels.linux_6_1</li>
    <li>linuxKernel.kernels.linux_6_1.dev</li>
    <li>linuxKernel.kernels.linux_hardened (linuxKernel.kernels.linux_6_1_hardened)</li>
    <li>linuxKernel.kernels.linux_hardened.dev (linuxKernel.kernels.linux_6_1_hardened.dev)</li>
    <li>linuxKernel.kernels.linux_6_3</li>
    <li>linuxKernel.kernels.linux_6_3.dev</li>
    <li>linuxKernel.kernels.linux_latest_libre</li>
    <li>linuxKernel.kernels.linux_latest_libre.dev</li>
    <li>linuxKernel.kernels.linux_libre</li>
    <li>linuxKernel.kernels.linux_libre.dev</li>
  </ul>
</details>

**Comment by Ma27** [comment]
Testing this now...

**Comment by K900** [comment]
Fixed 5.10, 5.4 still needs the patch.

**Comment by lovesegfault** [comment]
Result of `nixpkgs-review pr 236296` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.kernels.linux_4_14_hardened</li>
    <li>linuxKernel.kernels.linux_4_14_hardened.dev</li>
    <li>linuxKernel.kernels.linux_4_19_hardened</li>
    <li>linuxKernel.kernels.linux_4_19_hardened.dev</li>
    <li>linuxKernel.kernels.linux_5_4_hardened</li>
    <li>linuxKernel.kernels.linux_5_4_hardened.dev</li>
  </ul>
</details>
<details>
  <summary>18 packages built:</summary>
  <ul>
    <li>linuxKernel.kernels.linux_5_10</li>
    <li>linuxKernel.kernels.linux_5_10.dev</li>
    <li>linuxKernel.kernels.linux_5_10_hardened</li>
    <li>linuxKernel.kernels.linux_5_10_hardened.dev</li>
    <li>linuxKernel.kernels.linux_5_15</li>
    <li>linuxKernel.kernels.linux_5_15.dev</li>
    <li>linuxKernel.kernels.linux_5_15_hardened</li>
    <li>linuxKernel.kernels.linux_5_15_hardened.dev</li>
    <li>linuxKernel.kernels.linux_5_4</li>
    <li>linuxKernel.kernels.linux_5_4.dev</li>
    <li>linuxKernel.kernels.linux_hardened (linuxKernel.kernels.linux_6_1_hardened)</li>
    <li>linuxKernel.kernels.linux_hardened.dev (linuxKernel.kernels.linux_6_1_hardened.dev)</li>
    <li>linuxKernel.kernels.linux_6_3</li>
    <li>linuxKernel.kernels.linux_6_3.dev</li>
    <li>linuxKernel.kernels.linux_latest_libre</li>
    <li>linuxKernel.kernels.linux_latest_libre.dev</li>
    <li>linuxKernel.kernels.linux_rt_5_10</li>
    <li>linuxKernel.kernels.linux_rt_5_10.dev</li>
  </ul>
</details>

**Review by lovesegfault — APPROVED** [review]

**Review by Ma27 — APPROVED** [review]

**Comment by K900** [comment]
Been running 6.3.6 for a bit, seems good.

**Pull request merged**
