### PR TITLE
vimPlugins.guard-collection: init at 2023-11-13, vimPlugins.guard-nvim: init at 2023.11.27

### PR DESCRIPTION
**Pull request by gepbird**
## Description of changes

Add guard.nvim, an async formatting and linting utility.
Configurations for formatters and linters are in another repo called guard-collection, which is a dependency of guard.nvim.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by gepbird** [comment]
@figsoda @jonringer can you take a look at this PR?

**Comment by mattpolzin** [comment]
Result of `nixpkgs-review pr 270510` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>vimPlugins.guard-collection</li>
    <li>vimPlugins.guard-nvim</li>
  </ul>
</details>

**Review by mattpolzin — APPROVED** [review]
Cool plugin. Was able to poke around on `x86_64-darwin`.

**Comment by mattpolzin** [comment]
@teto how important is it for a `vimPlugins` PR to do the update script thing vs. just adding the new plugins like this PR does?

**Comment by gepbird** [comment]
Thanks for the review!

I can remake the commit with all the updates if you want, I just thought its easier to review an init PR if it only inits and not updates.

**Comment by teto** [comment]
> @teto how important is it for a `vimPlugins` PR to do the update script thing vs. just adding the new plugins like this PR does?

I actually prefer how this PR does. I would prefer that adding a new plugin doesn't automatically update all of them. This would need changes in the script and a broader consensus too.

This passes nixpkgs-review let's merge

**Pull request merged**
