### PR TITLE
antlr: 4.7 -> 4.8

### PR DESCRIPTION
**Pull request by guibou**
###### Motivation for this change

Update to new antlr 4.8

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"` --> yes but I may do it wrongly because it says "no change detected".
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after) (same. `511.2 M`)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

I tested the compilation of `mysql-workbench` which depends on `antlr4_7` and also I tested a few `antlr` binaires as well as the jar on my project.

### CODE REVIEW

**Review by jonringer — COMMENTED** [review]
regression in azure-cli. Do you mind leaving the 4_7 package?

```
builder for '/nix/store/mij0zarqvrqwaa1c61dkq1lsj7cfycva-python3.7-azure-cli-2.14.0.drv' failed with exit code 1; last 10 log lines:
  Processing ./azure_cli-2.14.0-py3-none-any.whl
  Requirement already satisfied: azure-mgmt-reservations==0.6.0 in /nix/store/lrbr2qfvz277xd0y072gzlh9s5d2wcmr-python3.7-azure-mgmt-reservations-0.8.0/lib/python3.7/site-packages (from azure-cli==2.14.0) (0.6.0)
  Requirement already satisfied: websocket-client~=0.56.0 in /nix/store/j22x6k4qha7dyx56k85gpsylkjdf53x5-python3.7-websocket_client-0.56.0/lib/python3.7/site-packages (from azure-cli==2.14.0) (0.56.0)
  Requirement already satisfied: azure-mgmt-compute~=14.0 in /nix/store/6vyyg3y3wh1jfwxnji28w0h4qb3zsa73-python3.7-azure-mgmt-compute-17.0.0/lib/python3.7/site-packages (from azure-cli==2.14.0) (14.0.0)
  Requirement already satisfied: azure-mgmt-synapse~=0.3.0 in /nix/store/myjf2z8nvm6hwfba8knziz44wkm43s0b-python3.7-azure-mgmt-synapse-0.4.0/lib/python3.7/site-packages (from azure-cli==2.14.0) (0.3.0)
  Requirement already satisfied: azure-mgmt-imagebuilder~=0.4.0 in /nix/store/f8nl125m5bfhsffy0lhbhk717dv6d79b-python3.7-azure-mgmt-imagebuilder-0.4.0/lib/python3.7/site-packages (from azure-cli==2.14.0) (0.4.0)
  Requirement already satisfied: azure-mgmt-containerservice~=9.4.0 in /nix/store/1cpd30pvh11h8rgp33pdlaw001ry3j9x-python3.7-azure-mgmt-containerservice-10.0.0/lib/python3.7/site-packages (from azure-cli==2.14.0) (9.4.0)
  Requirement already satisfied: azure-mgmt-botservice~=0.2.0 in /nix/store/29a55fqkw9yv96d2cgyr452ngrwdfm8d-python3.7-azure-mgmt-botservice-0.2.0/lib/python3.7/site-packages (from azure-cli==2.14.0) (0.2.0)
  ERROR: Could not find a version that satisfies the requirement antlr4-python3-runtime~=4.7.2 (from azure-cli==2.14.0) (from versions: none)
  ERROR: No matching distribution found for antlr4-python3-runtime~=4.7.2 (from azure-cli==2.14.0)
```
I'm good with bumping `antlr4` to be `antlr4_8` though

**Comment by jonringer** [comment]
actually, let me try just making them do `antlr-python3-runtime~=4.7`

**Comment by jonringer** [comment]
do you mind applying this diff in a `azure-cli: loosen antlr4 version bounds` commit?

```
$ git diff
diff --git a/pkgs/tools/admin/azure-cli/default.nix b/pkgs/tools/admin/azure-cli/default.nix
index a7dd4a6ae82..5f636dcf747 100644
--- a/pkgs/tools/admin/azure-cli/default.nix
+++ b/pkgs/tools/admin/azure-cli/default.nix
@@ -23,6 +23,7 @@ py.pkgs.toPythonApplication (py.pkgs.buildAzureCliPackage {
     substituteInPlace setup.py \
       --replace "javaproperties==0.5.1" "javaproperties" \
       --replace "pytz==2019.1" "pytz" \
+      --replace "antlr4-python3-runtime~=4.7.2" "antlr4-python3-runtime~=4.7" \
       --replace "mock~=4.0" "mock"
```

**Comment by guibou** [comment]
@jonringer I've added the losen bound for `azure-cli`. I did not detected it because I basically `grep`ed for `antlr4_7` in the repo. Thank you!

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 102820 [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>6 packages built:</summary>  <ul>    <li>antlr4 (antlr4_8)</li>    <li>azure-cli</li>    <li>mysql-workbench</li>    <li>python27Packages.antlr4-python2-runtime</li>    <li>python37Packages.antlr4-python3-runtime</li>    <li>python38Packages.antlr4-python3-runtime</li>  </ul></details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102820` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>antlr4 (antlr4_8)</li>
    <li>azure-cli</li>
    <li>python27Packages.antlr4-python2-runtime</li>
    <li>python37Packages.antlr4-python3-runtime</li>
    <li>python38Packages.antlr4-python3-runtime</li>
  </ul>
</details>

**Pull request merged**
