### PR TITLE
nixos/fontconfig-ultimate: remove

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
See discussion at https://github.com/NixOS/nixpkgs/pull/67529. This was long overdue.

I also removed `fonts.enableCoreFonts` as it also looked due for removal.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Review by jonringer — APPROVED** [review]

**Review by vcunat — APPROVED** [review]
Sounds good.  (I didn't really check for typos, etc.)

**Comment by worldofpeace** [comment]
@GrahamcOfBorg eval

**Comment by grahamc** [comment]
This PR's eval came in at a wonderful time where github had a bug and has since periodically exposed other bugs in github. If you wouldn't mind, would you rebase this PR again, which would work around the bug in ofborg for now?

**Comment by worldofpeace** [comment]
> This PR's eval came in at a wonderful time where github had a bug and has since periodically exposed other bugs in github. If you wouldn't mind, would you rebase this PR again, which would work around the bug in ofborg for now?

Done, I was considering if that was going to be my only option anyways :smile:

**Review by jtojnar — APPROVED** [review]

**Pull request merged**
