### PR TITLE
cataclysm-dda{,-git}: bump version

### PR DESCRIPTION
**Pull request by mnacamura**
###### Motivation for this change

Version 0.D was released a while ago.
The git version in nixpkgs seems too old.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by mnacamura** [comment]
Oops 0.D has an error:
Screen Shot 2019-05-03 at 14 41 40
Trying to fix it.

**Comment by mnacamura** [comment]
Done.

**Comment by mnacamura** [comment]
Done this time for sure.

**Comment by marius851000** [comment]
tested with nix-review, able to play the tutorial.

**Comment by bbigras** [comment]
Is it possible to use custom tilesets? The gfx folder seems to be in the read-only nix store. Is it possible by overriding the package? or can the game load tilesets from ~/.local/share/ or something like that?

**Comment by mnacamura** [comment]
Yes. You can package any tileset and use `buildEnv` or `symlinkJoin` to wrap C:DDA binary with `--datadir` argument. Example: https://github.com/mnacamura/nixpkgs-cdda-mods/blob/572e6555dd14abe8bb3bde54234a4a31652c6a44/wrapper.nix#L29

**Comment by bbigras** [comment]
Thank you very much.

**Pull request merged**
