### PR TITLE
shadowsocks service: support plugins

### PR DESCRIPTION
**Pull request by hmenke**
###### Motivation for this change

Some firewalls performs deep packet inspection to block VPN traffic, such as the Greaf Firewall (GFW) of the Chinese government.  Therefore it is required to obfuscate the traffic which can be done using the v2ray software.  The v2ray-plugin for the shadowsocks VPN was introduced in #95567.  This PR makes the shadowsocks service for NixOS aware of plugins.

Personally, I'm using this in production for myself and for a friend in Beijing for a couple of months without problems.  This is what my configuration roughly looks like:
```nix
{
  networking.firewall = {
    enable = true;
    allowedTCPPorts = [ 8488 ];
    allowedUDPPorts = [ 8488 ];
  };
  services.shadowsocks = {
    enable = true;
    encryptionMethod = "chacha20-ietf-poly1305";
    passwordFile = "/path/to/shadowsocks/key";
    localAddress = [ "0.0.0.0" ];
    port = 8488;
    mode = "tcp_and_udp";
    plugin = "${pkgs.shadowsocks-v2ray-plugin}/bin/v2ray-plugin";
    pluginOpts = "server;host=henrimenke.com";
  };
}
```

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by hmenke** [comment]
@ahrzb @abbradar

**Comment by hmenke** [comment]
Result of `nixpkgs-review pr 96127` [1](https://github.com/Mic92/nixpkgs-review)

**Comment by Lassulus** [comment]
can you add examples to the options also? If you have time, you could maybe add a nixos test for the service.

**Comment by hmenke** [comment]
@Lassulus I have added examples and a test.

**Comment by hmenke** [comment]
@ofborg test shadowsocks

**Comment by hmenke** [comment]
@ofborg test shadowsocks

**Comment by hmenke** [comment]
Test currently fails due to #96197

**Comment by Lassulus** [comment]
perfect, thanks!

**Comment by Mrmaxmeier** [comment]
Heads-Up: It looks like this breaks the default `shadowsocks.enable = true` setup:

```
error: The option value `systemd.services.shadowsocks-libev.path.[definition 1-entry 2]' in `/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/services/networking/shadowsocks.nix' is not of type `package or string'.
```

**Comment by hmenke** [comment]
@Mrmaxmeier Thank you for reporting this.  It should be fixed by #97478, please review.

**Pull request merged**
