### PR TITLE
Linux Hardened Kernel Updates 2024-12-14

### LINKED ISSUE #364251: Update request: linux-hardened 6.12
## Package Information

New tag/patch for Linux 6.12 came out! https://github.com/anthraxx/linux-hardened/releases/tag/v6.12.4-hardened1

- Package name: linuxKernel.kernels.linux_hardened
- Latest released version: 6.12.4
- Current version on the unstable channel: n/a - multiple
- Current version on the stable/release channel: n/a - multiple

## Checklist

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

## Notify maintainers

@fabianhjr

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by fabianhjr**
Closes #364251

NOTE: The following common config options have configuration issues on 6.12 hardened and where lowered to mkDefault on common config + option on hardened config:

- CONFIG_DRM_PANIC_SCREEN_QR_CODE
- CONFIG_RUST
- CONFIG_SCHED_CLASS_EXT

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by surfaceflinger — APPROVED** [review]
6.12 works fine for me!

**Comment by surfaceflinger** [comment]
What is the issue with sched ext?

**Comment by fabianhjr** [comment]
Unsure, haven't been able to look at it in detail

**Comment by jeholliday** [comment]
I also tried running these changes on v6.12, and I haven't had any issues with it running.

I am however confused by all of the changes to the kernel config. I see the comment `Use a lower priority to allow these options to be overridden in hardened/config.nix`, but as far as I can tell you're just setting the same the value in both places. If that is the case, would it not be better to not make unnecessary changes?

It seems like maybe the two Rust related config options might actually cause problems to be configured for the hardened profile unconditionally because they are only conditionally defined in the common config.

**Comment by fabianhjr** [comment]
Those are not the same `option yes` and `yes` are different in one regard: one will fail if it cannot be set during config.

As to not change the semantics of the common config but hardened being unable to config with `yes` hardened ended up with `option yes.`

**Comment by jeholliday** [comment]
I see that now. I was not familiar with that difference in syntax. Thanks for the clarification and figuring this out!

**Comment by fabianhjr** [comment]
Created a followup tracking issue: https://github.com/NixOS/nixpkgs/issues/365700

**Pull request merged**
