### PR TITLE
yadm: add missing dependencies

### PR DESCRIPTION
**Pull request by ilikeavocadoes**
###### Motivation for this change
Yadm was missing a runtime dependency on git.

###### Things done
Added git to `buildInputs`

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by Br1ght0ne — APPROVED** [review]
Seems reasonable.

By the way, what about `yadm encrypt`, that relies on GnuPG? Should it be an optional?

**Comment by ilikeavocadoes** [comment]
> Seems reasonable.
> 
> By the way, what about `yadm encrypt`, that relies on GnuPG? Should it be an optional?

I'm not really sure. Git is really needed for basic functionality but GPG could be considered to be extra? What is the general Nixpkgs policy regarding optional dependencies?

**Comment by ryantm** [comment]
I'm not sure if there is an official policy, but my feeling is that it is nice to get everything to work by default unless there is some good reason not to, like the optional dependency causes a significant performance overhead.

**Comment by ilikeavocadoes** [comment]
I, too, thing that when installing a package, everything should work by default. Thus, I added also gpg to buildInputs

**Review by Br1ght0ne — APPROVED** [review]

**Review by c0bw3b — COMMENTED** [review]
I also notice that this package doesn't produce any log when built and the man page isn't compressed. This is because of the custom `buildCommand`

You could replace the whole buildCommand with:

```nix
  dontConfigure = true;
  dontBuild = true;

  installPhase = ''
    runHook preInstall
    install -Dt $out/bin $src/yadm
    install -Dt $out/share/man/man1 $src/yadm.1
    install -D $src/completion/yadm.zsh_completion $out/share/zsh/site-functions/_yadm
    install -D $src/completion/yadm.bash_completion $out/share/bash-completion/completions/yadm.bash
    runHook postInstall
  '';
```

Then the normal fixup phase would automatically patch any shebang and compress man pages.
Plus the build gets logged which could be useful for checks on Hydra.

**Pull request merged**
