### PR TITLE
ascii: allow build on darwin

### PR DESCRIPTION
**Pull request by sjourdois**

### CODE REVIEW

**Comment by peti** [comment]
Isn't `meta.platforms = all` the default anyway? I don't think it's necessary to specify that attribute explicitly.

**Comment by sjourdois** [comment]
oh so I should delete platforms attribute when unnecessary ?
I'll try that, thx

**Comment by domenkozar** [comment]
No, it's then not built by hydra.

**Comment by peti** [comment]
Ah, okay. So it is necessary.

**Pull request merged**
