### PR TITLE
werf: init at 1.2.55

### PR DESCRIPTION
**Pull request by azahi**
###### Motivation for this change
Desire to use this package in NixOS.

werf is a GitOps delivery tool.
https://werf.io/
https://github.com/werf/werf

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Flakebi — APPROVED** [review]
Builds fine for me.
The maintainer list was probably updated in the meantime and has conflicts.
Also, upstream is now at 1.2.39.

**Comment by azahi** [comment]
@Flakebi I've bumped the version, `nixpkgs-fmt`'d and resolved maintainer conflicts.

**Review by Flakebi — APPROVED** [review]
Result of `nixpkgs-review pr 142597` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>werf</li>
  </ul>
</details>

**Comment by onsails** [comment]
Use werf from @azahi branch, works perfectly

**Comment by azahi** [comment]
Result of `nixpkgs-review pr 142597` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>werf</li>
  </ul>
</details>

**Comment by azahi** [comment]
Updated the version and rebased against master.
Is there any chance this could be merged now? @kalbasit @SuperSandro2000

**Comment by onsails** [comment]
I think commit msg should mention 1.2.55 instead of 1.2.39

**Comment by azahi** [comment]
Whoops... Should be fixed now.

**Pull request merged**
