### PR TITLE
hub: Add test, git reference

### PR DESCRIPTION
**Pull request by NeQuissimus**
###### Motivation for this change
Added test, found an issue with git not being available.
This is due to `hub` assuming git exists in the environment.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [X] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 107887` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gitAndTools.hub</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 107887` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gitAndTools.hub</li>
  </ul>
</details>

**Comment by WolfangAukang** [comment]
Result of `nixpkgs-review pr 107887` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gitAndTools.hub</li>
  </ul>
</details>

**Comment by WolfangAukang** [comment]
Result of `nixpkgs-review pr 107887` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gitAndTools.hub</li>
  </ul>
</details>

**Review by WolfangAukang — APPROVED** [review]

**Comment by zowoq** [comment]
@NeQuissimus Is there a reason you're not using `installCheckPhase` ([example](https://github.com/NixOS/nixpkgs/commit/51031a8d73007115dd5ba9b71449483704699685)) for tests like this? Booting two VMs for a basic test seems kind of heavy and it doesn't cover darwin either.

**Comment by NeQuissimus** [comment]
It's mainly because @ofborg runs these tests for us if they are in `passthru.tests`. And locally I can use `nix-update <PKG> --test` to do the same.

**Comment by zowoq** [comment]
None of that is needed with `installCheckPhase` as it's run as part of the build process.

**Pull request merged**
