### PR TITLE
buildGraalvmNativeImage: allow overriding attributes

### PR DESCRIPTION
**Pull request by thiagokokada**
###### Description of changes

Remove the previous function closure, that would make it difficult to access the inner derivation attributes.

Fix issue #216787.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 216855` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>babashka</li>
    <li>bbin</li>
    <li>clj-kondo</li>
    <li>clojure-lsp</li>
    <li>jet</li>
    <li>neil</li>
    <li>vscode-extensions.betterthantomorrow.calva</li>
    <li>zprint</li>
  </ul>
</details>

**Comment by thiagokokada** [comment]
@ofborg build babashka bbin clj-kondo clojure-lsp jet neil vscode-extension-betterthantomorrow-calva zprint

**Comment by thiagokokada** [comment]
@ofborg eval

**Comment by thiagokokada** [comment]
@ofborg build babashka bbin clj-kondo clojure-lsp jet neil vscode-extension-betterthantomorrow-calva zprint

**Comment by jakubgs** [comment]
Thanks for the fix, but it doesn't seem to work:
```nix
{ pkgs ? import /home/jakubgs/work/nixpkgs { } }:

pkgs.zprint.overrideAttrs (old: rec {
  inherit (old) pname;
  version = "1.2.4";
  src = pkgs.fetchurl {
    url = "https://github.com/kkinnear/${pname}/releases/download/${version}/${pname}-filter-${version}";
    sha256 = "sha256-PWdR5jqyzvTk9HoxqDldwtZNik34dmebBtZZ5vtva4A=";
  };
})
```
```
~/work/nixpkgs PR-216855*
 > nix-build zprint_1.2.4_override.nix
/nix/store/w76qf33scn7yf9dadmp1pck4cj3x8qss-zprint-1.2.4

~/work/nixpkgs PR-216855*
 > /nix/store/w76qf33scn7yf9dadmp1pck4cj3x8qss-zprint-1.2.4/bin/zprint --version
zprint-1.2.5
```
I believe the issue is in the `jar ? args.src` part. Because if I look at the input derivation:
```
 > nix show-derivation /nix/store/gzrpcjkykvp9pdsysflvf55rh9lcrmjg-zprint-1.2.4 | grep 1.2.5
      "/nix/store/8094v9qvrxzhd366li739vi275qs6kqk-zprint-filter-1.2.5.drv": [
      "nativeImageBuildArgs": "-jar /nix/store/b61ykgm8rzz6w47r5h0w9blr6yn11q6d-zprint-filter-1.2.5  -H:Name=zprint --verbose --no-server -H:EnableURLProtocols=https,http -H:+ReportExceptionStackTraces --report-unsupported-elements-at-runtime --initialize-at-build-time --no-fallback -J-Xmx6g",

```
We can see the wrong JAR is still being used.

**Comment by thiagokokada** [comment]
> I believe the issue is in the jar ? args.src part. Because if I look at the input derivation:

I don't know if much can be done about it unless we complicate `buildGraalvmNativeImage` a lot. You are supposed to override `jar` too in those cases.

**Comment by jakubgs** [comment]
Well, what is more valuable, the level of complexity of the builder, or the ease of use of the packages it builds?

I would argue the latter is far more important, but that's just me. I think this could be avoided by doing `jar ? nil` and doing some logic in the `let`/`in` block instead of in the arguments. It might be less pretty, but I do think maintaining the expected functionality of `overrideAttrs` is quite important.

**Comment by thiagokokada** [comment]
> I would argue the latter is far more important, but that's just me. I think this could be avoided by doing jar ? nil and doing some logic in the let/in block instead of in the arguments.

Feel free to open a PR them.

> It might be less pretty, but I do think maintaining the expected functionality of overrideAttrs is quite important.

But `overrideAttrs` is already broken for things like `src` and `version` (if someone sets only `version` and don't override `src`, the same issue you described occurs, and this is valid for any derivation that is not using `mkDerivation` new format that AFAIR were still in probation phase).

**Comment by jakubgs** [comment]
>But `overrideAttrs` is already broken for things like `src` and `version` (if someone sets only `version` and don't override `src`, the same issue you described occurs, and this is valid for any derivation that is not using `mkDerivation` new format that AFAIR were still in probation phase).

How is that an issue in any way, shape, or form? OBVIOUSLY you need to also override the SHA for the `src` and changing just `version` won't work. That is in no way an problem with `overrideAttrs`, it is a completely expected behavior.

**Comment by jakubgs** [comment]
I can try making a PR when I have some time based of of yours possibly, it should not be that difficult.

**Comment by thiagokokada** [comment]
> How is that an issue in any way, shape, or form? OBVIOUSLY you need to also override the SHA for the `src` and changing just `version` won't work. That is in no way an problem with `overrideAttrs`, it is a completely expected behavior.

This is a common newbie trap: it seems easy to just update your version, especially because most derivations does something like this:

```nix
{ stdenv, ... }:

stdenv.mkDerivation rec {
  pname = "foo";
  version = "123";

  src = fetchurl {
    url = "https://foo.com/downloads/v${version}.tar.gz";
    sha256 = "somehash";
  };
}
```

You would expect that at least it would give you a hash conflict or something, but if you `overrideAttrs` the derivation above it will happily build but using the previous version because the `src.url` still points to the previous version. The reason is that the attrset was already evaluated before, because `rec` evals only once when the attrset is defined.

A similar issue is happening here, the attrset was already evaluated when the derivation was defined and `jar = args.src` was the calculated value, and it needs redefined during the `overrideAttrs`.

**Comment by jakubgs** [comment]
Yes, the issue might be caused by a similar reason, and I'd agree it's a common pitfall for new users, but I'd say most docs/tutorials point out the src update requirement. I think the core issue is that you need to come up with special tricks like overriding `buildGraalvmNativeImage` with `override` which is not something a newbie can figure out by themselves for sure, unlike the `src` thing.

I'm busy today but I can try tomorrow.

**Comment by thiagokokada** [comment]
> Yes, the issue might be caused by a similar reason, and I'd agree it's a common pitfall for new users, but I'd say most docs/tutorials point out the src update requirement. I think the core issue is that you need to come up with special tricks like overriding `buildGraalvmNativeImage` with `override` which is not something a newbie can figure out by themselves for sure, unlike the `src` thing.

Ok, there was a dumb issue that needed all the `override`+`overrideAttrs` workaround that is now fixed.

With [94c485b](https://github.com/NixOS/nixpkgs/pull/216855/commits/94c485bcd414f091693f511b46e5f10f68915ef7), no need to `override` the derivations from `buildGraalvmNativeImage`. `overrideAttrs` should be enough:

```nix
pkgs.zprint.overrideAttrs (old: rec {
  inherit (old) pname;
  version = "1.2.4";
  src = pkgs.fetchurl {
    url = "https://github.com/kkinnear/${pname}/releases/download/${version}/${pname}-filter-${version}";
    sha256 = "sha256-PWdR5jqyzvTk9HoxqDldwtZNik34dmebBtZZ5vtva4A=";
  };
  jar = src;
})
```

This works for me and there is no need for weird hacks or complicating this derivation further.

**Review by jakubgs — APPROVED** [review]
Oh, I see, you moved the setting of `-jar` flag into the derivation itself. Yeah, it works for me. Good solution.
```
~/work/nixpkgs PR-216855*
 > nix-build zprint_1.2.4_override.nix                                                      
/nix/store/4x8amznj77dsb3lph73ywsskdj4ax259-zprint-1.2.4

~/work/nixpkgs PR-216855*
 > /nix/store/4x8amznj77dsb3lph73ywsskdj4ax259-zprint-1.2.4/bin/zprint --version            
zprint-1.2.4
```

**Comment by thiagokokada** [comment]
@ofborg build babashka bbin clj-kondo clojure-lsp jet neil vscode-extension-betterthantomorrow-calva zprint

**Comment by thiagokokada** [comment]
@ofborg build babashka bbin clj-kondo clojure-lsp jet neil vscode-extension-betterthantomorrow-calva zprint

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 216855` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>babashka</li>
    <li>bbin</li>
    <li>clj-kondo</li>
    <li>clojure-lsp</li>
    <li>jet</li>
    <li>neil</li>
    <li>vscode-extensions.betterthantomorrow.calva</li>
    <li>zprint</li>
  </ul>
</details>

**Pull request merged**
