### PR TITLE
python2Packages.pyqt4: Fix build

### LINKED ISSUE #56712: Pulseeffects broken
Pulseeffects depends on pyqt4 which does not build. Maybe we could build the plugin without pyqt4.

```
these derivations will be built:
  /nix/store/h6j015zk8h8p9xy2z64qki3r1j1zhpna-python2.7-PyQt-x11-gpl-4.12.drv
  /nix/store/bz3wrlp2wprl5bmm2d92x146i5v1sn1v-ffado-2.4.0.drv
  /nix/store/rsyxgadvf4il4rc86dd12mgf4sfkyl8q-jack2-1.9.12.drv
  /nix/store/nccxmq4nvv3fwcbaq0sjy6s81rxkr209-lsp-plugins-1.1.5.drv
  /nix/store/8g4y8a3xmkd2n0bnr7wc1jsg60gp550s-pulseeffects-4.4.7.drv
building '/nix/store/h6j015zk8h8p9xy2z64qki3r1j1zhpna-python2.7-PyQt-x11-gpl-4.12.drv'...
unpacking sources
unpacking source archive /nix/store/hj68y74aa8ldambjn5kahi4ac0ammrp3-PyQt4_gpl_x11-4.12.tar.gz
source root is PyQt4_gpl_x11-4.12
setting SOURCE_DATE_EPOCH to timestamp 1482760115 of file PyQt4_gpl_x11-4.12/doc/html/threads.html
patching sources
configuring
/nix/store/63karsgdg7fm3q0if4zfd7apbd8ac1ci-stdenv-linux/setup: line 1312: lndir: command not found
builder for '/nix/store/h6j015zk8h8p9xy2z64qki3r1j1zhpna-python2.7-PyQt-x11-gpl-4.12.drv' failed with exit code 127
cannot build derivation '/nix/store/bz3wrlp2wprl5bmm2d92x146i5v1sn1v-ffado-2.4.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/rsyxgadvf4il4rc86dd12mgf4sfkyl8q-jack2-1.9.12.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/nccxmq4nvv3fwcbaq0sjy6s81rxkr209-lsp-plugins-1.1.5.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/8g4y8a3xmkd2n0bnr7wc1jsg60gp550s-pulseeffects-4.4.7.drv': 1 dependencies couldn't be built
error: build of '/nix/store/8g4y8a3xmkd2n0bnr7wc1jsg60gp550s-pulseeffects-4.4.7.drv' failed
```

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
Fixes: https://github.com/NixOS/nixpkgs/issues/56712

cc @hedning 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by hedning — APPROVED** [review]
Looks good to me at least.

**Comment by hedning** [comment]
The python strictDeps change didn't hit 19.03, so not sure if it's necessary to backport.

**Comment by FRidh** [comment]
@hedning I backported the whole of `staging-next`, so including `strictDeps`. Yes, this needs to be backported.

**Comment by FRidh** [comment]
@GrahamcOfBorg python2Packages.pyqt4 python3Packages.pyqt4

**Comment by FRidh** [comment]
You're fast. I was just cherry-picking them.... :)

**Comment by jtojnar** [comment]
Backported:

```
commit 5b38b4572a40af7d396cbd01e66d0d8fec3667b6
Author: Jan Tojnar <jtojnar@gmail.com>
Date:   Sat Mar 2 18:07:19 2019 +0100

    python2Packages.pyqt4: partial clean up
    
    (cherry picked from commit 6471655f76ea8c7c9289704e5a11dfcdd1b139e3)

commit 1861f58d9f7cc6486391bcc66439d1a0c47c7fe6
Author: Jan Tojnar <jtojnar@gmail.com>
Date:   Sat Mar 2 18:03:28 2019 +0100

    python2Packages.pyqt4: Fix build
    
    (cherry picked from commit f14a48f716a7fb29569bc9d6ad4aef8bb71180ae)

```

**Pull request merged**
