### PR TITLE
mutt: 1.6.0 -> 1.6.2

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Motivation for this change

See #16772
###### Things done
- [x] Tested using sandboxing
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

I have taken the patches from the [mutt-sidebar](https://aur.archlinux.org/cgit/aur.git/tree/?h=mutt-sidebar) AUR package. I have tried both sidebar and trash folder: they seem to work however I'm not personally using these features and I have not configured them so I can't be 100% sure.

### CODE REVIEW

**Comment by joachifm** [comment]
LGTM. Thank you

**Comment by joachifm** [comment]
Oh, I can't believe I failed to notice the huge patches ... @rnhmjoj would you mind replacing those with `fetchpatch` or similar? I would do it myself, but I'm not sure exactly where those patches come from.

**Comment by rnhmjoj** [comment]
Sorry, I don't really have time now. The patches are [here](https://aur.archlinux.org/cgit/aur.git/tree/?h=mutt-sidebar) btw.

**Comment by joachifm** [comment]
@rnhmjoj no worries, I'll look into fixing it, thank you for the pointer

**Comment by joachifm** [comment]
Fixed in a317a15b30d6dd2ce25f81474dfba744002ae7a8

**Pull request merged**
