### PR TITLE
akkoma: 3.13.1 -> 3.13.2

### PR DESCRIPTION
**Pull request by tcmal**
## Description of changes

This is a security update. [Changelog](https://akkoma.dev/AkkomaGang/akkoma/src/commit/050bc74437525503595208d820c6918e8cb0be4e/CHANGELOG.md#2024-04-1-security)

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by illdefined** [comment]
Result of `nixpkgs-review pr 313794` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>akkoma</li>
  </ul>
</details>

**Comment by illdefined** [comment]
I confirmed that there is no change in dependencies and successfully ran the unconfined module tests on Linux x86-64.

The confined test fails because `pleroma_ctl` is called with `RUNTIME_DIRECTORY=/run/akkoma:/run/confinement/akkoma`.

**Comment by illdefined** [comment]
I suspect that the problem was introduced by 0a5542c766cc14b3a6c841d0f47ab098605776e2, which is intended to enable the use of `ProtectSystem` with confined units.

I am uncertain why exactly it adds `"confinement/${mkPathSafeName name}"` to the `RuntimeDirectory` list. If I understand correctly, that directory is used as root directory for the confined environment.

The following `InaccesiblePaths` directive then disables access to `/run/confinement/$name/run/confinement/$name`, as the `+` prefix makes the path relative to `RootDirectory`.

**Comment by illdefined** [comment]
> I suspect that the problem was introduced by [0a5542c](https://github.com/NixOS/nixpkgs/commit/0a5542c766cc14b3a6c841d0f47ab098605776e2), which is intended to enable the use of `ProtectSystem` with confined units.
> 
> I am uncertain why exactly it adds `"confinement/${mkPathSafeName name}"` to the `RuntimeDirectory` list. If I understand correctly, that directory is used as root directory for the confined environment.

@ju1m Am I correct in my assumption that the addition of the path to the `RuntimeDirectory` list is only so that the directory is automatically created on unit startup? If so, do you think there is alternative way to create the directory that doesn’t affect the `RUNTIME_DIRECTORY` environment variable?

**Comment by tcmal** [comment]
Since this is a security update, I'd prefer to merge it soon and fix the confinement issue with a seperate PR. Unless there's a readily available fix, I don't really have time to look into it right now.

**Comment by illdefined** [comment]
> Since this is a security update, I'd prefer to merge it soon and fix the confinement issue with a seperate PR. Unless there's a readily available fix, I don't really have time to look into it right now.

I have no objection. It’s broken on master with or without this PR.

**Review by illdefined — APPROVED** [review]

**Comment by ju1m** [comment]
> @ju1m Am I correct in my assumption that the addition of the path to the `RuntimeDirectory` list is only so that the directory is automatically created on unit startup?

@illdefined, yes, that's a fresh empty directory created for `RootDirectory=` instead of using `/var/empty` previously which was not compatible with `ProtectSystem=strict` (also implied by `DynamicUser=true`).

> If so, do you think there is alternative way to create the directory that doesn’t affect the `RUNTIME_DIRECTORY` environment variable?

AFAIK, of [all the directories that systemd can create](https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#%24RUNTIME_DIRECTORY) for a service (`$RUNTIME_DIRECTORY`, `$STATE_DIRECTORY`, `$CACHE_DIRECTORY`, `$LOGS_DIRECTORY`, `$CONFIGURATION_DIRECTORY` and `$CREDENTIALS_DIRECTORY`), `$RUNTIME_DIRECTORY` is the best fit for the purpose of a confinement `RootDirectory=`.

If I may suggest a fix, I think [nixos/modules/services/web-apps/akkoma.nix](https://github.com/NixOS/nixpkgs/blob/bfb7a882678e518398ce9a31a881538679f6f092/nixos/modules/services/web-apps/akkoma.nix#L281) should not assume that `$RUNTIME_DIRECTORY` is a single path and either be replaced by a hardcoded `/run/akkoma` or maybe avoided entirely by defining some envvars like `environment.RELEASE_COOKIE = "/var/lib/akkoma/.cookie";` in the service.

**Comment by illdefined** [comment]
I suggest the following patch to deal with `RUNTIME_DIRECTORY` containing multiple directories:

```
diff --git a/nixos/modules/services/web-apps/akkoma.nix b/nixos/modules/services/web-apps/akkoma.nix
index 7c9bf6c46516..fa6241ba3028 100644
--- a/nixos/modules/services/web-apps/akkoma.nix
+++ b/nixos/modules/services/web-apps/akkoma.nix
@@ -119,7 +119,7 @@ let
         -o ${escapeShellArg cfg.user } \
         -g ${escapeShellArg cfg.group} \
         <(hexdump -n 16 -e '"%02x"' /dev/urandom) \
-        "$RUNTIME_DIRECTORY/cookie"
+        "''${RUNTIME_DIRECTORY%%:*}/cookie"
     '';
   };
 
@@ -131,7 +131,7 @@ let
         -o ${escapeShellArg cfg.user} \
         -g ${escapeShellArg cfg.group} \
         ${escapeShellArg cfg.dist.cookie._secret} \
-        "$RUNTIME_DIRECTORY/cookie"
+        "''${RUNTIME_DIRECTORY%%:*}/cookie"
     '';
   };
 
@@ -181,7 +181,7 @@ let
     name = "akkoma-config";
     runtimeInputs = with pkgs; [ coreutils replace-secret ];
     text = ''
-      cd "$RUNTIME_DIRECTORY"
+      cd "''${RUNTIME_DIRECTORY%%:*}"
       tmp="$(mktemp config.exs.XXXXXXXXXX)"
       trap 'rm -f "$tmp"' EXIT TERM
 
@@ -279,7 +279,7 @@ let
         cd "${cfg.package}"
 
         RUNTIME_DIRECTORY="''${RUNTIME_DIRECTORY:-/run/akkoma}"
-        AKKOMA_CONFIG_PATH="$RUNTIME_DIRECTORY/config.exs" \
+        AKKOMA_CONFIG_PATH="''${RUNTIME_DIRECTORY%%:*}/config.exs" \
         ERL_EPMD_ADDRESS="${cfg.dist.address}" \
         ERL_EPMD_PORT="${toString cfg.dist.epmdPort}" \
         ERL_FLAGS=${lib.escapeShellArg (lib.escapeShellArgs ([
@@ -287,7 +287,7 @@ let
           "-kernel" "inet_dist_listen_min" (toString cfg.dist.portMin)
           "-kernel" "inet_dist_listen_max" (toString cfg.dist.portMax)
         ] ++ cfg.dist.extraFlags))} \
-        RELEASE_COOKIE="$(<"$RUNTIME_DIRECTORY/cookie")" \
+        RELEASE_COOKIE="$(<"''${RUNTIME_DIRECTORY%%:*}/cookie")" \
         RELEASE_NAME="akkoma" \
           exec "${cfg.package}/bin/$(basename "$0")" "$@"
       '';
```

**Comment by illdefined** [comment]
And considering that it is now supported, we no longer need to disable `ProtectSystem` if confinement is enabled:

```
diff --git a/nixos/modules/services/web-apps/akkoma.nix b/nixos/modules/services/web-apps/akkoma.nix
index 7c9bf6c46516..b89c90b4cfd5 100644
--- a/nixos/modules/services/web-apps/akkoma.nix
+++ b/nixos/modules/services/web-apps/akkoma.nix
@@ -1072,7 +1072,7 @@ in {
 
         ProtectProc = "noaccess";
         ProcSubset = "pid";
-        ProtectSystem = mkIf (!isConfined) "strict";
+        ProtectSystem = "strict";
         ProtectHome = true;
         PrivateTmp = true;
         PrivateDevices = true;
```

**Comment by tcmal** [comment]
Have added the patches suggested by @illdefined, everything seems to work locally but not certain which confinement tests need run.

**Comment by ju1m** [comment]
> I suggest the following patch to deal with `RUNTIME_DIRECTORY` containing multiple directories:

Note that this is assuming that `/run/akkoma` comes first in the list, and would fail if it were `/run/confinement/akkoma` which is an inaccessible path.

**Comment by illdefined** [comment]
> Have added the patches suggested by @illdefined, everything seems to work locally but not certain which confinement tests need run.

Just `nixosTests.akkoma-confined`.

> > I suggest the following patch to deal with `RUNTIME_DIRECTORY` containing multiple directories:
> 
> Note that this is assuming that `/run/akkoma` comes first in the list, and would fail if it were `/run/confinement/akkoma` which is an inaccessible path.

I suppose that `lib.mkBefore` should take care of that:

```
diff --git a/nixos/modules/services/web-apps/akkoma.nix b/nixos/modules/services/web-apps/akkoma.nix
index b89c90b4cfd5..1f3653c9bd13 100644
--- a/nixos/modules/services/web-apps/akkoma.nix
+++ b/nixos/modules/services/web-apps/akkoma.nix
@@ -984,7 +984,7 @@ in {
         RemainAfterExit = true;
         UMask = "0077";
 
-        RuntimeDirectory = "akkoma";
+        RuntimeDirectory = mkBefore [ "akkoma" ];
 
         ExecStart = mkMerge [
           (mkIf (cfg.dist.cookie == null) [ genScript ])
```

**Review by illdefined — APPROVED** [review]
Successfully ran all tests locally on Linux x86-64.

**Review by illdefined — APPROVED** [review]

**Review by LeSuisse — APPROVED** [review]
Changes look good and tests are passing, let's merge.

**Pull request merged**
