### PR TITLE
[wip] wxWidgets: move wxGTK-* to one wxWidgets folder

### LINKED ISSUE #16066: wxwidgets fails to build on OSX
## Issue description

Here's the output that I get:

```
In file included from ./include/wx/osx/private.h:4:
./include/wx/osx/core/private.h:55:10: fatal error: 'Carbon/Carbon.h' file not found
#include <Carbon/Carbon.h>
         ^
4 warnings and 1 error generated.
Makefile:28754: recipe for target 'basedll_filefn.o' failed
make: *** [basedll_filefn.o] Error 1
builder for ‘/nix/store/ab4il1siki6x8vbr8lmjr0mp472674bi-wxwidgets-3.0.2.drv’ failed with exit code 2
```
### Steps to reproduce

E.g. `nix-env -i wxmaxima`.
## Technical details
- System: OS X 10.11.6 Beta (15G7b)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: "16.09pre83147.df89584"

### PR DESCRIPTION
**Pull request by matthewbauer**
###### Motivation for this change

wxGTK had a lot of code duplication. This merges wxGTK\* and wxmac into one "wxWidgets/default.nix" file.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [x] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---
- removes wxmac
- removes wxGTK28, wxGTK29, wxGTK30
- adds "compat28" and "compat30" flags
- add aliases for wxmac, wxGTK28, wxGTK29, wxGTK30
- resolves #16066

### CODE REVIEW

**Comment by matthewbauer** [comment]
This is causing a mass rebuild which I think is what is breaking travis.

**Comment by matthewbauer** [comment]
cc @vcunat Could you stage this at some point? I'm not seeing any issues but lots depends on it.

**Comment by vcunat** [comment]
Skimming all this quickly, it looks OK. I dislike a little that libgd should use some "random" master commit; maybe using that PR would be better as that would reportedly add only two commits to the release.

**Comment by vcunat** [comment]
Or we might directly apply https://github.com/libgd/libgd/commit/502e4cd873c3b37b307b9f450ef827d40916c3d6 to the release, perhaps even on darwin only (to avoid depending on the tools elsewhere).

**Comment by matthewbauer** [comment]
Ok, I updated libgd to 2.2.2 and also applied the patch that should fix the issue with building.

**Comment by vcunat** [comment]
Now we should go for gd-2.2.2 at least, due to security: f48d21551.

**Comment by matthewbauer** [comment]
Okay, commit c5ed30f8afb86831066c3cec265873cffd746b4a should be good to go. Everything else should also be good but less urgent.

**Comment by matthewbauer** [comment]
@vcunat I just rebased onto master. This should be ready for another look.

**Comment by FRidh** [comment]
This seems to brea `pythonPackages.wxPython`.

```
In file included from /nix/store/a9whppkflv4f6dq40hdw0lqxvs2srbl8-wxwidgets-3.1.0/include/wx/defs.h:20:0,
                 from /nix/store/a9whppkflv4f6dq40hdw0lqxvs2srbl8-wxwidgets-3.1.0/include/wx/wx.h:14,
                 from include/wx/wxPython/wxPython_int.h:35,
                 from src/helpers.cpp:17:
/nix/store/a9whppkflv4f6dq40hdw0lqxvs2srbl8-wxwidgets-3.1.0/include/wx/platform.h:136:22: fatal error: wx/setup.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1
builder for ‘/nix/store/53qfpc47b787wnfm2q0l4qgx44gnad1c-python2.7-wxPython-3.0.2.0.drv’ failed with exit code 1
error: build of ‘/nix/store/53qfpc47b787wnfm2q0l4qgx44gnad1c-python2.7-wxPython-3.0.2.0.drv’ failed
```

**Pull request closed without merging**
