### PR TITLE
brgenml1cupswrapper: init at 3.1.0-1 + fix regression and improvements

### PR DESCRIPTION
**Pull request by jraygauthier**
backport of https://github.com/NixOS/nixpkgs/pull/14758.

Tests performed explained there.

### CODE REVIEW

**Comment by joachifm** [comment]
Looks like you need to include the commit that adds you to the maintainers list
> error: undefined variable ‘jraygauthier’ at /home/travis/build/NixOS/nixpkgs/pkgs/misc/cups/drivers/brgenml1cupswrapper/default.nix:123:50

**Comment by jraygauthier** [comment]
Odd, it built fine locally. Added myself as a maintainer.

**Comment by joachifm** [comment]
Probably due to Nix being non-strict, errors in the meta attribute won't reveal themselves before it is actually evaluated (which I guess it won't be if you're just building the package).

**Comment by jraygauthier** [comment]
Thanks again for the quick merge :+1:

**Pull request merged**
