### PR TITLE
chromium: add enable_hangout_services_extension=true

### PR DESCRIPTION
**Pull request by obadz**
… to fix screensharing bug

as suggested in: https://code.google.com/p/chromium/issues/detail?id=416856#c53

### CODE REVIEW

**Comment by jagajaga** [comment]
What if I don't use hangouts? I don't need this option then.

**Comment by obadz** [comment]
Actually, Hangouts is turned on by default.

This option seems to bring back that bit of code which is needed for the screensharing feature to work like it does in Chrome.

**Comment by domenkozar** [comment]
`In common.gypi, the top definition of 'enable_hangout_services_extension%' can be ignored because at line 2448 has a check for whether you are building Chrome or Chromium. I suspect this has license implications so bare in mind you probably should not distribute your build of Chromium with Hangouts force-enabled.`

**Comment by obadz** [comment]
I'm not sure what that licensing comment is based on. I'm no lawyer, but looking at https://chromium.googlesource.com/chromium/src.git/+/47.0.2526.12/LICENSE I see no restriction on the combination of flags that can be used to compile chromium and distribute binaries..

**Comment by obadz** [comment]
Just to motivate that this isn't a trivial issue that only affects me:
62 people have stared this issue here: https://code.google.com/p/chromium/issues/detail?id=416856
And another 59 in the duplicate here: https://code.google.com/p/chromium/issues/detail?id=413942
One guy even took the time to make a Youtube video to demonstrate the problem: https://www.youtube.com/watch?v=vWVTBJIk__M

**Comment by obadz** [comment]
cc @aszlig (based on git log)

**Comment by obadz** [comment]
Looks like this gyp variable was created specifically to be able to include these features in Chromium builds: https://code.google.com/p/chromium/issues/detail?id=343567

**Comment by domenkozar** [comment]
I'm OK with this, but I'll let @aszlig merge

**Comment by aszlig** [comment]
Hm, I'd prefer if we'd have a way to enable/disable these at runtime or at least without the need to recompile Chromium.

**Comment by aszlig** [comment]
@domenkozar: Well, I'm currently not able to test this right away, so feel free to merge. Otherwise I'll assign myself once I'm able to test it.

**Comment by obadz** [comment]
Agreed it would be nice if we could toggle at runtime but since that's not a possibility, I think it's better on than off as screenshare works when on and there are no downside that I could see after 2 weeks of use.

Also it's on in Chrome branded builds so this must be a relatively well tested code path.

**Comment by domenkozar** [comment]
@obadz you tested this and it works? If so, I'll just merge for now (and revert if problems come up)

**Comment by obadz** [comment]
@domenkozar, yes it works for me.

**Pull request merged**
