### PR TITLE
androidenv: add emulator v29.3.6

### PR DESCRIPTION
**Pull request by fmnxl**
###### Motivation for this change
Android SDK packages are getting out of date. The bash script to automatically generate the packages derivation seems to be broken, and I will attempt to fix it in the near future.

###### Things done

- Adds an updated version of the android emulator (v29.3.6)

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] ~Ensured that relevant documentation is up to date~ N/A
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lucafavatella** [comment]
This PR seems still current - as I do not see reference to emulator 29 in master.

(I am having a quick look at the androidenv-related PRs - hence this comment.)

----

I understand this PR is meant to be a short term solution for getting emulator 29 until the script for automatic generation of the related config is fixed and re-run.

> The bash script to automatically generate the packages derivation seems to be broken ...

I understand the script in question is `generate.sh`, whose usage is [documented](https://github.com/NixOS/nixpkgs/blob/4120419e10d1edcf9f3835b6e1e3ffe8f285b56d/doc/languages-frameworks/android.section.md#updating-the-generated-expressions).

I wonder if the project has a way (CI cron weekly job?) for periodically checking for these kinds of semi-automatically generated configurations:
- Whether the invocation of `generate.sh` still succeeds.
- Whether the invocation of `generate.sh` still generates the same output - so if some body has to call it manually it still works predictably.
- Whether new version are available (and ideally automatically prepare a PR).

**Comment by fmnxl** [comment]
@lucafavatella Thanks for your comment. Yes, this was a quick fix to get emulator v29.

Like you said the long term solution should be to get generate.sh t run and run regularly and auto updates the `generated` files.

I'm not a Nix expert, but I'm not sure why the `generated` files are part of this package. If it can be built by the user, then we won't need to maintain this package for every version upgrade.. I guess it's something to do with determinism.

**Comment by lucafavatella** [comment]
@fmnxl Thanks for coming back to me! Your changes saved me a lot of time while trying to get a recent emulator to run. I am trying to propose this in (still draft) PR #82118 so you are welcome to have a look to that so we get your changes (hopefully) merged soon.

**Comment by numinit** [comment]
Possibly superseded by #89775

**Pull request closed without merging**
