### PR TITLE
Firejail module: exposed wrappedBins

### PR DESCRIPTION
**Pull request by hqurve**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ryneeverett** [comment]
Motivation?

**Comment by SuperSandro2000** [comment]
> Motivation?

Let me guess: somewhere the variable is needed. Doesn't matter to much to be honest.

----

Do nixos modules support passthru? If so that should be used.

**Comment by hqurve** [comment]
Yeah, the motivation was to be able to use the wrapped binary elsewhere (mainly in `makeDesktopItem` or to edit an existing deskop item). 

However, I think a better solution would be to expose this as function in all-packages. Though something feels a bit wrong with this approach as it would require that [the firejail wrapper](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/firejail.nix#L84) be enabled in order for this function to work.

**Comment by ryneeverett** [comment]
> Side note: Is there any reason in particular why the firejail package is both added to systemPackages and the security wrapper?

#79104: "this way the man page etc. becomes available"

**Comment by hqurve** [comment]
Thanks

**Comment by hqurve** [comment]
Also, I'm closing since, I no longer have the motivation to fix this into a format for the repo. But is the code I'm using to wrap packages

```
{ lib
, firejail
, runtimeShell
}:

{ package
, paths
, args ? ""
, name ? lib.getName package
, profile ? "${firejail}/etc/firejail/${name}.profile"
}:
let
  wrapFileMapper = p: ''wrapProgram "$out/${p}"'';
in
package.overrideAttrs (old: {
  postFixup = /* bash */ ''
    ${old.postFixup or ""}

    # ensure profile exists
    if [[ ! -e ${profile} ]]; then
      echo '"${profile}"' does not exist
      exit 1
    fi

    wrapProgram() {
      local prog="$1"
      local hidden

      hidden="$(dirname "$prog")/.$(basename "$prog")"-wrapped
      while [ -e "$hidden" ]; do
        hidden="''${hidden}_"
      done

      hidden2="''${hidden}_"
      while [ -e "$hidden2" ]; do
        hidden2="''${hidden2}_"
      done

      echo $prog $hidden $hidden2

      # prog - firejail
      # hidden - change name of exec
      # hidden2 - original

      mv "$prog" "$hidden2"

      echo "#!${runtimeShell} -e" > "$hidden"
      echo "exec -a \"$(basename "$prog")\" \"$hidden2\" \"\$@\"" >> "$hidden"
      chmod +x "$hidden"


      echo "#!${runtimeShell} -e" > "$prog"
      echo "exec /run/wrappers/bin/firejail --profile=\"${profile}\" ${args} -- \"$hidden\" \"\$@\"" >> "$prog"
      chmod +x "$prog"

    }

    ${lib.concatMapStringsSep "\n" wrapFileMapper paths}
  '';
})
```

Its kind of dirty since it overrides the original package, but I think I did it that way to be able to easily keep desktop files. Also, for some reason zoom's desktop file has a hardcoded full path, so I just took the easy route.

**Pull request closed without merging**
