### PR TITLE
dotnet-sdk_5: 5.0.403 -> 5.0.408

### PR DESCRIPTION
**Pull request by mdarocha**
###### Description of changes

Updated to the latest available version. Looks like we won't be getting rid of it for a while, due to dependant packages.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by IvarWithoutBones** [comment]
Looks like `roslyn` breaks with this PR, while it did build on [hydra](https://hydra.nixos.org/build/190855481) a few days ago.
 ```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/8i235sfsbxkc18x4c52ksddsm882q0cw-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
/build/source/src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/CSharpSyntaxGenerator.csproj : error NU1100: Unable to resolve 'Microsoft.NETCore.App.>
/build/source/src/Interactive/csi/csi.csproj : error NU1100: Unable to resolve 'Microsoft.NETCore.App.Host.linux-x64 (= 3.1.25)' for '.NETCoreApp,Version=v3.1'. [/build/>
  Restored /build/source/src/Compilers/VisualBasic/Portable/Microsoft.CodeAnalysis.VisualBasic.vbproj (in 351 ms).
  Failed to restore /build/source/src/Interactive/csi/csi.csproj (in 350 ms).
  Restored /build/source/src/Compilers/Core/MSBuildTask/Microsoft.Build.Tasks.CodeAnalysis.csproj (in 363 ms).
  Restored /build/source/src/Compilers/VisualBasic/vbc/vbc.csproj (in 350 ms).
  Failed to restore /build/source/src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/CSharpSyntaxGenerator.csproj (in 350 ms).
  Restored /build/source/src/Compilers/Server/VBCSCompiler/VBCSCompiler.csproj (in 350 ms).
  Restored /build/source/src/Compilers/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.csproj (in 350 ms).
  Restored /build/source/src/Scripting/Core/Microsoft.CodeAnalysis.Scripting.csproj (in 350 ms).
  Restored /build/source/src/Scripting/CSharp/Microsoft.CodeAnalysis.CSharp.Scripting.csproj (in 364 ms).
  Restored /build/source/src/Compilers/CSharp/csc/csc.csproj (in 351 ms).
  Restored /build/source/src/Compilers/Core/Portable/Microsoft.CodeAnalysis.csproj (in 351 ms).
  Restored /build/source/src/NuGet/Microsoft.Net.Compilers.Toolset/Microsoft.Net.Compilers.Toolset.Package.csproj (in 350 ms).
```
`msbuild` depends on that package so it doesn't build either.

**Comment by mdarocha** [comment]
> Looks like `roslyn` breaks with this PR, while it did build on [hydra](https://hydra.nixos.org/build/190855481) a few days ago.
> 
> ```
> @nix { "action": "setPhase", "phase": "unpackPhase" }
> unpacking sources
> unpacking source archive /nix/store/8i235sfsbxkc18x4c52ksddsm882q0cw-source
> source root is source
> @nix { "action": "setPhase", "phase": "patchPhase" }
> patching sources
> @nix { "action": "setPhase", "phase": "configurePhase" }
> configuring
> no configure script, doing nothing
> @nix { "action": "setPhase", "phase": "buildPhase" }
> building
> Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
>  Determining projects to restore...
> /build/source/src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/CSharpSyntaxGenerator.csproj : error NU1100: Unable to resolve 'Microsoft.NETCore.App.>
> /build/source/src/Interactive/csi/csi.csproj : error NU1100: Unable to resolve 'Microsoft.NETCore.App.Host.linux-x64 (= 3.1.25)' for '.NETCoreApp,Version=v3.1'. [/build/>
>  Restored /build/source/src/Compilers/VisualBasic/Portable/Microsoft.CodeAnalysis.VisualBasic.vbproj (in 351 ms).
>  Failed to restore /build/source/src/Interactive/csi/csi.csproj (in 350 ms).
>  Restored /build/source/src/Compilers/Core/MSBuildTask/Microsoft.Build.Tasks.CodeAnalysis.csproj (in 363 ms).
>  Restored /build/source/src/Compilers/VisualBasic/vbc/vbc.csproj (in 350 ms).
>  Failed to restore /build/source/src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/CSharpSyntaxGenerator.csproj (in 350 ms).
>  Restored /build/source/src/Compilers/Server/VBCSCompiler/VBCSCompiler.csproj (in 350 ms).
>  Restored /build/source/src/Compilers/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.csproj (in 350 ms).
>  Restored /build/source/src/Scripting/Core/Microsoft.CodeAnalysis.Scripting.csproj (in 350 ms).
>  Restored /build/source/src/Scripting/CSharp/Microsoft.CodeAnalysis.CSharp.Scripting.csproj (in 364 ms).
>  Restored /build/source/src/Compilers/CSharp/csc/csc.csproj (in 351 ms).
>  Restored /build/source/src/Compilers/Core/Portable/Microsoft.CodeAnalysis.csproj (in 351 ms).
>  Restored /build/source/src/NuGet/Microsoft.Net.Compilers.Toolset/Microsoft.Net.Compilers.Toolset.Package.csproj (in 350 ms).
> ```
> 
> `msbuild` depends on that package so it doesn't build either.

Should be fixed now

**Comment by prusnak** [comment]
From https://logs.nix.ci/?key=nixos/nixpkgs.192258&attempt_id=9d61e7eb-ee28-4827-a3d4-581dc9abb18a:

```
/build/source/src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/CSharpSyntaxGenerator.csproj : error NU1100: Unable to resolve 'Microsoft.NETCore.App.Host.linux-arm64 (= 3.1.25)' for '.NETCoreApp,Version=v3.1'. [/build/source/src/NuGet/Microsoft.Net.Compilers.Toolset/Microsoft.Net.Compilers.Toolset.Package.csproj]
/build/source/src/Interactive/csi/csi.csproj : error NU1100: Unable to resolve 'Microsoft.NETCore.App.Host.linux-arm64 (= 3.1.25)' for '.NETCoreApp,Version=v3.1'. [/build/source/src/NuGet/Microsoft.Net.Compilers.Toolset/Microsoft.Net.Compilers.Toolset.Package.csproj]
  Restored /build/source/src/Compilers/VisualBasic/Portable/Microsoft.CodeAnalysis.VisualBasic.vbproj (in 567 ms).
```

not sure why it tries to find aarch64-linux runtime for dotnet 3.1

**Comment by mdarocha** [comment]
> From https://logs.nix.ci/?key=nixos/nixpkgs.192258&attempt_id=9d61e7eb-ee28-4827-a3d4-581dc9abb18a:
> 
> ```
> /build/source/src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/CSharpSyntaxGenerator.csproj : error NU1100: Unable to resolve 'Microsoft.NETCore.App.Host.linux-arm64 (= 3.1.25)' for '.NETCoreApp,Version=v3.1'. [/build/source/src/NuGet/Microsoft.Net.Compilers.Toolset/Microsoft.Net.Compilers.Toolset.Package.csproj]
> /build/source/src/Interactive/csi/csi.csproj : error NU1100: Unable to resolve 'Microsoft.NETCore.App.Host.linux-arm64 (= 3.1.25)' for '.NETCoreApp,Version=v3.1'. [/build/source/src/NuGet/Microsoft.Net.Compilers.Toolset/Microsoft.Net.Compilers.Toolset.Package.csproj]
>   Restored /build/source/src/Compilers/VisualBasic/Portable/Microsoft.CodeAnalysis.VisualBasic.vbproj (in 567 ms).
> ```
> 
> not sure why it tries to find aarch64-linux runtime for dotnet 3.1

Yeah, there was a problem when regenerating dependencies. Let's hope someone ports roslyn soon to `buildDotnetModule` (https://github.com/NixOS/nixpkgs/issues/146257), which has a lot better dependency generation script.

**Pull request merged**
