### PR TITLE
Improve Unicode coverage

### PR DESCRIPTION
**Pull request by Mathnerd314**
This gives NixOS mostly-complete Unicode 8.0 coverage, together with Noto and Unifont.

George Douros - Egyptian cuneiform, other ancient symbols that aren't in Noto
Hanazono - CJK A-E coverage
Lohit - Updated for Unicode 8.0
OldSindhi, Sampradaya, Maratha Cursive, Tai Ahom, Mro - other obscure Indian fonts
Unifont_upper - Old Permic, a few others
SignWriting - exactly that

The remaining 0.55% of glyphs (673 total):
Multani (38) - no googleable font exists
Warang Citi (84) - no googleable font exists
Pau Cin Hau (57) - no googleable font exists
Tirhuta (82) - [most](http://www.tirhutalipi.4t.com/index.htm) [fonts](http://www.bhashasanchar.org/fontsdev.php) seem to be [clip fonts](https://en.wikipedia.org/wiki/Clip_font), [this](http://www.maithilifonts.in/) has clip fonts and a Bengali overwrite, http://forum.high-logic.com/viewtopic.php?f=16&t=5806 is a placeholder font
Bassa Vah (36) - http://glavyfonts.com/african.html (non-free, clip font), http://web.archive.org/web/20070210143146/http://www.ie-inc.com/vkarmo/bfont.htm (free clip font)
Mende Kikakui (213) - http://glavyfonts.com/african.html (non-free, private use area)
Duployan (143) - http://www.unicode.org/notes/tn37/DuployanProp.ttf, non-free, private use area
Grantha (20) - Sampradaya's coverage is incomplete and layout only works on OSX

cc @ttuegel

### CODE REVIEW

**Comment by ttuegel** [comment]
Thanks!

**Comment by Mathnerd314** [comment]
Full list of fonts:
```
hanazono noto-fonts noto-fonts-cjk noto-fonts-emoji aegean textfonts symbola 
aegyptus akkadian anatolian maya unidings musica analecta unifont_upper 
lohit-fonts.assamese lohit-fonts.bengali lohit-fonts.devanagari 
lohit-fonts.gujarati lohit-fonts.gurmukhi lohit-fonts.kannada 
lohit-fonts.malayalam lohit-fonts.marathi lohit-fonts.nepali lohit-fonts.odia 
lohit-fonts.tamil-classical lohit-fonts.tamil lohit-fonts.telugu 
lohit-fonts.kashmiri lohit-fonts.konkani lohit-fonts.maithili lohit-fonts.sindhi 
oldsindhi sampradaya marathi-cursive tai-ahom mro-unicode signwriting
```

**Comment by shlevy** [comment]
What do I have to do on NixOS to get these installed?

**Comment by Mathnerd314** [comment]
Copy the list of fonts into a config entry:
```
  fonts.fonts = with pkgs; [ ... ];
```
I've been thinking about a ``fonts.enableUnicodeCoverage = true`` switch, which would be more maintainable.

**Comment by pSub** [comment]
:+1:  for such a switch

**Comment by shlevy** [comment]
Agreed.

**Pull request merged**
