### PR TITLE
vimPlugins: add ChatGPT.nvim

### PR DESCRIPTION
**Pull request by PrimaMateria**
###### Description of changes

Added https://github.com/jackMort/ChatGPT.nvim

ChatGPT is a Neovim plugin that allows you to interact with OpenAI's GPT-3 language model. With ChatGPT, you can ask questions and get answers from GPT-3 in real-time.

###### First time contribution!

Hi, this is my first time contribution, so better I will describe what I did.

1. Run `GITHUB_API_TOKEN=<secret> ./update.py --add "jackMort/ChatGPT.nvim"` (resulted in the commits in this PR)
1. Run `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"` (resulted in no code changes / no commits required)
1. Tested manually with the following config:

```nix
{
  inputs = {
    nixpkgs-local.url = "/home/primamateria/dev/nixpkgs";
    flake-utils.url = "github:numtide/flake-utils";

    neovim = {
      url = "github:neovim/neovim?dir=contrib";
      inputs.nixpkgs.follows = "nixpkgs-local";
    };
  };

  outputs = inputs@{ self, flake-utils, nixpkgs-local, neovim, ... }:
    let
      overlay = prev: final: rec {      
        neovimPrimaMateria = prev.wrapNeovim neovim.packages.x86_64-linux.neovim {
          withNodeJs = true;
          configure = {
            customRC = ''
              lua << EOF
              require("chatgpt").setup({ })
              EOF
              '';
            packages.myVimPackage.start = [
              final.pkgs.vimPlugins.plenary-nvim
              final.pkgs.vimPlugins.telescope-nvim
              final.pkgs.vimPlugins.nui-nvim
              final.pkgs.vimPlugins.ChatGPT-nvim
            ];
          };
        };
      };

    in flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs-local {
          inherit system;
          overlays = [ overlay ];
        };
      in {
        packages = rec {
          inherit (pkgs) neovimPrimaMateria;
          default = neovimPrimaMateria;
        };

        apps = rec {
          neovimPrimaMateria= {
            type = "app";
            program = "${pkgs.neovimPrimaMateria}/bin/nvim";
          };
          default = neovimPrimaMateria;
        };
      });
}
```

You can see that this plugin depends on other 3 plugins. I was thinking if something needs to be done in the `overrides.nix`, but as far as I understand, this would not help. These plugins must be listed in the array of plugins explicitly by the user to be available in the nvim runtime.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by figsoda** [comment]
> I was thinking if something needs to be done in the overrides.nix

I think this might be what you wanted

```nix
{
  # ...
  ChatGPT-nvim = super.ChatGPT-nvim.overrideAttrs (old: {
    dependencies = with self; [ nui-nvim plenary-nvim telescope-nvim ];
  });
  # ...
}
```

**Comment by PrimaMateria** [comment]
I have added the dependencies to the `overrides.nix`. But this will only install them to the store, and it will not automatically include them to the list of plugins used in neovim. So, the user will still need to explicitly list them in their configuration. At least, it didn't work with my flake I have used for testing.

**Comment by figsoda** [comment]
I was able to start neovim with this with no issues
```nix
{
  inputs = {
    nixpkgs.url = "github:PrimaMateria/nixpkgs/vimPlugins-add-chatgptnvim";
  };

  outputs = { self, nixpkgs }:
    let
      inherit (nixpkgs.lib) genAttrs systems;
    in
    {
      packages = genAttrs systems.flakeExposed (system: {
        default = with nixpkgs.legacyPackages.${system}; neovim.override {
          configure = {
            customRC = ''
              lua require("chatgpt").setup({ })
            '';
            packages.all.start = with vimPlugins; [ ChatGPT-nvim ];
          };
        };
      });
    };
}
```

**Comment by PrimaMateria** [comment]
Oh yes, it works. Also, my config works. I had to be doing something wrong. Probably, I didn't run `nix flake update` after updating the overrides locally, so I have built it with previously cached nixpkgs.

**Review by figsoda — APPROVED** [review]

**Pull request merged**
