### PR TITLE
Add package: swiften-3.0beta2 (C++ XMPP library)

### PR DESCRIPTION
**Pull request by Twey**

### CODE REVIEW

**Comment by jagajaga** [comment]
Please rename commit's name following our guide in `CONTRIBUTING.md`.

**Comment by Twey** [comment]
Like this?  (following https://hydra.nixos.org/build/26681095/download/1/nixpkgs/manual.html#idm140737319133600 )

**Comment by jagajaga** [comment]
Like this https://hydra.nixos.org/build/26681095/download/1/nixpkgs/manual.html#idm140737319165840
> Format the commit in a following way 

So your comment should be `swiften: init at 3.0beta2`

**Comment by vbgl** [comment]
There should be a link to this file in `all-packages.nix`, isn’t it?

**Comment by jagajaga** [comment]
@vbgl you are right :) 
@Twey please fix

**Comment by Twey** [comment]
Fixed (?)

**Pull request merged**
