### PR TITLE
mingw: Disalbe FORTIFY_SOURCE by default.

### PR DESCRIPTION
**Pull request by shlevy**
In newer versions of mingw, programs compiled with FORTIFY_SOURCE need
to link to libssp or they will have link-time errors.

gmp has been broken since @pstn updated mingw-64 in c60a0b044747037b87e7ec24b60d221e261b8a6b

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
> In newer versions of mingw, programs compiled with FORTIFY_SOURCE need
to link to libssp or they will have link-time errors.

Would an alternative be to just add libssp or am I missing something?

**Comment by shlevy** [comment]
@SuperSandro2000 We'd have to add it to all links with fortify enabled, but just adding -lssp when fortify is given results in failed autoconf checks. Would need to track down the proper fix.

**Comment by Ericson2314** [comment]
@alexfmpe and I were looking into this (see #132199). I think this is a good temp fix. I hope to fix it more properly with https://github.com/NixOS/nixpkgs/pull/132343 (which has been a long time coming!).

**Comment by alexfmpe** [comment]
> @SuperSandro2000 We'd have to add it to all links with fortify enabled, but just adding -lssp when fortify is given results in failed autoconf checks. Would need to track down the proper fix.

That's more or less the conclusion I reached in https://github.com/NixOS/nixpkgs/pull/132188#issuecomment-890566691

**Comment by pstn** [comment]
Just for the record: I did *not* break `pkgs.gmp` as would be discoverable by `nixpkgs-review`, as @shlevy seems to feel the need to imply constantly. I assume some cross package he uses broke.

**Comment by shlevy** [comment]
@pstn Apologies for the lack of clarity, I did mean gmp cross-compiled to mingw in that commit.

I don't know what you mean by "feel the need to imply constantly." I just put that in one commit message to explain why this was needed now and not before.

**Pull request merged**
