### PR TITLE
smlnjBootstrap: 110.84 -> 110.91

### PR DESCRIPTION
**Pull request by vaibhavsagar**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vaibhavsagar** [comment]
@jwiegley does this look good?

**Comment by xeji** [comment]
@GrahamcOfBorg build smlnjBootstrap

**Review by xeji — COMMENTED** [review]
doesn't build

**Comment by aanderse** [comment]
@vaibhavsagar are you able to address the build failure?

> /nix/store/4ixxl0jdcq0zz7xbzmrqg2cpg1wpsi63-stdenv-darwin/setup: line 1317: /usr/bin/xar: Operation not permitted

**Comment by vaibhavsagar** [comment]
Unfortunately I don't have access to a Mac.

**Comment by aanderse** [comment]
@vaibhavsagar alright thanks.

**Comment by lilyball** [comment]
I have to assume the build failure is due to sandboxing preventing access to `/usr/bin/xar`.

**Comment by lilyball** [comment]
The following appears to fix this for me:

```diff
diff --git a/pkgs/development/compilers/smlnj/bootstrap.nix b/pkgs/development/compilers/smlnj/bootstrap.nix
index 2315ae28431..28f65d3ad9d 100644
--- a/pkgs/development/compilers/smlnj/bootstrap.nix
+++ b/pkgs/development/compilers/smlnj/bootstrap.nix
@@ -1,4 +1,4 @@
-{ stdenv, fetchurl, cpio, rsync, makeWrapper }:
+{ stdenv, fetchurl, cpio, rsync, xar, makeWrapper }:
 
 stdenv.mkDerivation rec {
   name = "smlnj-bootstrap-${version}";
@@ -13,7 +13,7 @@ stdenv.mkDerivation rec {
   buildInputs = [ cpio rsync makeWrapper ];
 
   unpackPhase = ''
-    /usr/bin/xar -xf $src
+    ${xar}/bin/xar -xf $src
     cd smlnj.pkg
   '';
 
```

**Comment by vaibhavsagar** [comment]
Thanks @lilyball!

**Comment by lilyball** [comment]
@vaibhavsagar I believe nixpkgs guidelines says you should squash the two commits together.

**Comment by vaibhavsagar** [comment]
I went ahead and did this, but I don't see it in the guidelines as it's not a typo or whitespace-only change: https://nixos.org/nixpkgs/manual/#chap-submitting-changes.

**Comment by aanderse** [comment]
@GrahamcOfBorg build smlnjBootstrap

Thanks for your never ending awesomeness @lilyball!

**Comment by aanderse** [comment]
@vaibhavsagar Oops... it appears this has sat long enough it is out of date. Maybe you should rename this PR and rewrite thebump commit to the newest version.

**Comment by vaibhavsagar** [comment]
@aanderse updated.

**Comment by aanderse** [comment]
@GrahamcOfBorg build smlnjBootstrap

**Review by aanderse — APPROVED** [review]
LGTM :+1:

**Pull request merged**
