### PR TITLE
nixos/lxd: add preseed option

### LINKED ISSUE #66502: LXD preseed option would be useful
As far as I can tell LXD isn't very useful until initializing it. This can be done non-interactively using `lxd init --preseed` and passing the "preseed configuration" on standard input. An option to specify this as a multi-line configuration string would be useful.

### PR DESCRIPTION
**Pull request by adamcstephens**
- nixos/lxd: remove with lib
- nixos/lxd: add preseed option

closes #66502

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by adamcstephens** [comment]
@ofborg test lxd

**Comment by adamcstephens** [comment]
@ofborg test lxd

**Comment by adamcstephens** [comment]
> nixosTests.lxd on aarch64-linux — Unexpected error: command failed with exit code 1

This is the VM test failing from my previous work. I think we’ll need to disable this test on aarch64 for now. Any tips on best way to disable just the VM test only on aarch64?

**Review by AndersonTorres — APPROVED** [review]

**Comment by adamcstephens** [comment]
@ofborg test lxd

**Comment by AndersonTorres** [comment]
> nixosTests.lxd on x86_64-linux — Unexpected error: command failed with exit code 1

I desist.

**Comment by adamcstephens** [comment]
Sigh. This is yet another test, the container test, which I’m able to run locally. 

> Test "Container is mounted with lxcfs inside" failed with error: "command `lxc restart container` failed (exit code 1)"

Let’s try again and see if that was a spurious failure. 

@ofborg test lxd

**Comment by adamcstephens** [comment]
And now the tests pass.

**Pull request merged**
