### PR TITLE
buildLayeredImage: Allow empty store, no paths to add

### PR DESCRIPTION
**Pull request by roberth**
This is useful when buildLayeredImage is called in a generic way
that should allow simple (base) images to be built, which may not
reference any store paths.

For example arion uses it to build a very bare base image for use with the host's Nix store.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nlewo** [comment]
It would be nice to add a test case (building and loading such image) because I'm pretty sure nobody will test this behavior in case of refactoring ;)
What do you think?

**Comment by roberth** [comment]
I agree it would be nice to have a test. I did look for existing tests to add to, but I didn't find any. Or are these supposed to be used as tests? https://github.com/NixOS/nixpkgs/blob/f9388a76344479c3a1855f45a69fc3676905a4e7/pkgs/build-support/docker/examples.nix

**Comment by nlewo** [comment]
@roberth that's not ideally at all, but currently, we add an example image in `pkgs/build-support/docker/examples.nix` and we use this image in the NixOS test `nixos/tests/docker-tools.nix`.
Basically, you'd have to add an example image without any path and `docker load` this image in the test to ensure the image can be loaded by Docker.
The commit baa78de59403a69936bd9fc4709707d600926308 can be used as example.

**Comment by roberth** [comment]
@nlewo I've added a test case.

**Comment by nlewo** [comment]
@roberth Arf, we just merged to Python migration of the test:/ Could you rebase your test?

**Comment by roberth** [comment]
@nlewo rebased.

**Comment by roberth** [comment]
This also solves https://github.com/hercules-ci/arion/issues/91 according to manveru.

**Comment by nlewo** [comment]
@GrahamcOfBorg test docker-tools

**Review by nlewo — APPROVED** [review]
Thanks for the test!
I'm just waiting for the bot feedback;)

**Comment by roberth** [comment]
@GrahamcOfBorg test docker-tools

I'm surprised by the timeout. Output seems to have stopped around here https://github.com/NixOS/nixpkgs/pull/80921/files#diff-1635c3330be60719346294be6c07f88fR153

The preceding test produced output and it should return immediately. 
I've tested this locally. `(exec -a custom-true busybox) |& grep custom-true` and `docker run --rm no-store-paths:latest custom-true |& grep custom-true` return immediately. Local testing was on 19.09 though.

**Comment by domenkozar** [comment]
@GrahamcOfBorg test docker-tools

**Comment by domenkozar** [comment]
Seems to pass on rerun.

**Comment by domenkozar** [comment]
Backported to 20.03

**Pull request merged**
