### PR TITLE
nextcloud25: 25.0.3 -> 25.0.4, nextcloud24: 24.0.9 -> 24.0.10

### PR DESCRIPTION
**Pull request by dotlambda**
###### Description of changes
https://help.nextcloud.com/t/minor-releases-25-0-4-and-24-0-10-changelogs/156522/1

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bachp** [comment]
@dotlambda There seems to be no changelog for 25.0.4. Are we to early or was it yanked for some reason?

**Comment by dotlambda** [comment]
> @dotlambda There seems to be no changelog for 25.0.4. Are we to early or was it yanked for some reason?

I think we're just too early. The GitHub releases do exist:
https://github.com/nextcloud/server/releases/tag/v25.0.4
https://github.com/nextcloud/server/releases/tag/v24.0.10

**Comment by dotlambda** [comment]
I can confirm that PDF previews with imaginary are working in 25.0.4.

**Comment by dotlambda** [comment]
I get
```
$ nix-build -A nextcloud24Packages.apps.notes
these 2 derivations will be built:
  /nix/store/7wj0pdv1hnzfgbm1n2ylw4jns7zzzr4k-source.drv
  /nix/store/493g43rx71cdhrkkg5gqcx5ggghd6mk9-source-patched.drv
building '/nix/store/7wj0pdv1hnzfgbm1n2ylw4jns7zzzr4k-source.drv'...

trying https://github.com/nextcloud/notes/releases/download/v4.5.1/notes.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 5201k  100 5201k    0     0  4586k      0  0:00:01  0:00:01 --:--:-- 10.6M
unpacking source archive /build/notes.tar.gz
error: hash mismatch in fixed-output derivation '/nix/store/7wj0pdv1hnzfgbm1n2ylw4jns7zzzr4k-source.drv':
         specified: sha256-rd3uVkVtARX4enRAWm1ivV468lboYZnYe7/zsqaHYpk=
            got:    sha256-WdteA8pDSZ7ba+kngmveHC2KgzyLSB+PomFEZ7/uCC0=
error: 1 dependencies of derivation '/nix/store/493g43rx71cdhrkkg5gqcx5ggghd6mk9-source-patched.drv' failed to build
```
and the same on master. Any idea why?

**Review by urandom2 — APPROVED** [review]

**Comment by dotlambda** [comment]
https://nextcloud.com/blog/updates-25-0-4-and-24-0-10-are-out-get-it/

**Review by Ma27 — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
> @dotlambda There seems to be no changelog for 25.0.4. Are we to early or was it yanked for some reason?

nextcloud does not publish changelogs. There is the marketing material about new features and the git log both on the forums and the release notes.

**Pull request merged**
