### PR TITLE
clojure: 1.10.3.855 -> 1.10.3.933

### LINKED ISSUE #131959: clojure out-of-date (1.10.3.855 -> 1.10.3.933)
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: clojure

current version: 1.10.3.855
desired version: 1.10.3.933

###### Notify maintainers

maintainers: @jlesquembre @thiagokokada

###### Note for maintainers

Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by thiagokokada**
###### Motivation for this change

Closes https://github.com/NixOS/nixpkgs/issues/131959

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by pb-** [comment]
@jlesquembre any chance to get this reviewed soonish? It would help unbreaking the `clj` binary in NixOS 21.05 I think.

**Comment by thiagokokada** [comment]
@SuperSandro2000 it is a simple bump, can we have a review/merge :thinking: ?

**Comment by jlesquembre** [comment]
@onetom see https://github.com/NixOS/nixpkgs/pull/132922
@thiagokokada I appreciate how responsive you are and how fast you are with the updates, but I think it would be better to take more time to check them

**Comment by thiagokokada** [comment]
> @thiagokokada I appreciate how responsive you are and how fast you are with the updates, but I think it would be better to take more time to check them

One question, did this actually broke something or it is only this new `-T` flag that isn't working :thinking: ?

Because if it is the second case, I don't think what I did was wrong.

But if it is the first case, I think we need more testing for this package. Because this would be the same if the auto-update bot updated this package (it doesn't work in this case because the package is not hosted in GitHub, but the point still is valid).

**Comment by jlesquembre** [comment]
As far as I know, it's only the `-T` flag

> Because if it is the second case, I don't think what I did was wrong.

Not at all! Apologies if my comment sounds negative, not my intention. I really appreciate your work on nix. As a personal preference, I prefer to have older versions, but more tested. But you can, of course, disagree with me, and that's fine

**Comment by thiagokokada** [comment]
> As a personal preference, I prefer to have older versions, but more tested. But you can, of course, disagree with me, and that's fine

I think that `unstable` should have the most up-to-date packages, while stable should have stable, tested versions. Maybe my early attempt to backport this change to 21.05 was a mistake, but the act of bumping itself should be fine.

And it is important to bump early so we get those bugs faster too. At least, those are my 2c.

**Pull request merged**
