### PR TITLE
python311Packages.extruct: 0.16.0 -> 0.17.0

### LINKED ISSUE #329027: Build failure: python311Packages.recipe-scrapers
### Steps To Reproduce

1. build *python311Packages.recipe-scrapers* on `master` (e5bc1cb431307c0a3943615151aeff0b9cc246c3)

### Build log

```
Executing pythonImportsCheckPhase
Check whether the following modules can be imported: extruct
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "/nix/store/hyppxdhgqx7nbg394j97yhmi6vizl074-python3-3.11.9/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nix/store/ahx97198xk2wjd4dbxax1l6yb22iiv3p-python3.11-extruct-0.16.0/lib/python3.11/site-packages/extruct/__init__.py", line 1, in <module>
    from ._extruct import SYNTAXES, extract
  File "/nix/store/ahx97198xk2wjd4dbxax1l6yb22iiv3p-python3.11-extruct-0.16.0/lib/python3.11/site-packages/extruct/_extruct.py", line 9, in <module>
    from extruct.dublincore import DublinCoreExtractor
  File "/nix/store/ahx97198xk2wjd4dbxax1l6yb22iiv3p-python3.11-extruct-0.16.0/lib/python3.11/site-packages/extruct/dublincore.py", line 6, in <module>
    from extruct.utils import parse_html
  File "/nix/store/ahx97198xk2wjd4dbxax1l6yb22iiv3p-python3.11-extruct-0.16.0/lib/python3.11/site-packages/extruct/utils.py", line 5, in <module>
    from extruct.xmldom import XmlDomHTMLParser
  File "/nix/store/ahx97198xk2wjd4dbxax1l6yb22iiv3p-python3.11-extruct-0.16.0/lib/python3.11/site-packages/extruct/xmldom.py", line 9, in <module>
    from lxml.etree import (
ImportError: cannot import name '_ElementStringResult' from 'lxml.etree' (/nix/store/0i7w9qrw41ih3sa45kpaihldn1d6fj9n-python3.11-lxml-5.2.2/lib/python3.11/site-packages/lxml/etree.cpython-311-x86_64-linux-gnu.so)
```

### Notify maintainers
@ambroisie

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by litchipi**
## Description of changes

Required change for https://github.com/NixOS/nixpkgs/issues/325120#issuecomment-2227850878

fixes https://github.com/NixOS/nixpkgs/issues/329027

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by ambroisie — APPROVED** [review]
LGTM, will wait on ofborg result and merge if it doesn't break anything.

@litchipi you can ping me if I forget :-)

**Comment by eclairevoyant** [comment]
Seems like the `tandoor-recipes` module is currently broken (not due to this PR)

**Comment by ambroisie** [comment]
Urgh I wasn't even pinged on that `tandoor-recipes` PR...

**Comment by litchipi** [comment]
> And the `mealie` tests would not work due to #326296
`mealie` breaks on `python312` because of the issue with `python-ldap`
and `mealie` breaks on `python311` because of the issue with `python-extruct`

So depending on what version of python is the best for serving mealie on, it may or may not help

**Comment by ambroisie** [comment]
@litchipi does your update to `python-extruct` fix `mealie` on 3.11? If so, we can pin it to use `python311{,Packages}` ([like it was done for `tandoor-recipes`](https://github.com/NixOS/nixpkgs/pull/327142)) for now until upstream updates it to be compatible.

**Comment by litchipi** [comment]
@ambroisie Yes it does, and I can pin the version no worries.

However I wonder why cannot we simply merge this PR ? (I don't understand what is the problem here :sweat_smile: )
Does this version upgrade break `tandoor-recipes` ?

**Comment by ambroisie** [comment]
@litchipi I think we can merge the PR, I assume @eclairevoyant was just pointing out that running NixOS tests for `mealie` and `tandoor-recipes` wouldn't actually show whether bump `python-extruct` broke anything, as they were already broken for different reasons.

**Comment by ambroisie** [comment]
@GrahamcOfBorg test tandoor-recipes

This test should have been fixed now.

**Comment by eclairevoyant** [comment]
I ran both mealie and tandoor-recipes nixos tests after pinning python and rebasing, no errors locally (x86_64-linux), so this PR should be fine.

**Comment by litchipi** [comment]
> EDIT: as for pinning to `python311` in `mealie`, you can open a new PR (and assign me as a reviewer) for that if you want.

@ambroisie  I meant that as mealie is broken because of `python-extruct` being outdated, after this PR is merged, there is no need anymore to pin the version

Idk who has merge rights tho, so could you ping someone in charge ? :sweat_smile:

**Comment by eclairevoyant** [comment]
> meant that as mealie is broken because of `python-extruct` being outdated

No, mealie is broken due to `python312Packages.ldap` being in the dependency tree. Pinning to 3.11 is still necessary.

**Comment by eclairevoyant** [comment]
Can you update the commit message to follow [guidelines](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions) (i.e. match the PR title)? I'll merge after.

**Review by ambroisie — APPROVED** [review]

**Review by kloenk — APPROVED** [review]

**Pull request merged**
