### PR TITLE
perlPackages.DBDSQLite: 1.55_07 -> 1.58

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

minor update

### CODE REVIEW

**Comment by volth** [comment]
@GrahamcOfBorg build perlPackages.DBDSQLite

**Comment by xeji** [comment]
@GrahamcOfBorg  build hydra nix1 nix-serve

**Comment by xeji** [comment]
@volth do you think the `nix1` test failure on aarch64 is caused by this PR?

**Comment by volth** [comment]
```
hash mismatch in downloaded path ‘/build/nix-1.11.16/tests/test-tmp/store/c19w5zyv083igcqc319l1px9qvgn6xwk-dependencies’: expected 7fb5baba31471847815159ed05523d86e59fc641dddd3ba3a3b109e6403a3e82, got a50a5ab6d992f5598edd92105059fae9acfc192981e08bd88534c2167e92526a
error: build of ‘/build/nix-1.11.16/tests/test-tmp/store/q16p7lgfpgyvksjgk0a0asfladg73z2c-dependencies.drv’ failed
```

**Comment by volth** [comment]
I guess no.
Let's see, I started the same ```@GrahamcOfBorg build hydra nix1 nix-serve``` here https://github.com/NixOS/nixpkgs/pull/41679#issuecomment-395838968

**Comment by volth** [comment]
Hm, succeeded there.
Then yes

**Comment by volth** [comment]
although I do not know where "the expected hash ```7fb5baba31471847815159ed05523d86e59fc641dddd3ba3a3b109e6403a3e82``` (AKA ```10iy790fc2dilfikppfx8739zrc67m90bvara60lf62766xbmdbz```) come from.

it is not in the PR and Github search nor Google can help :(

**Comment by xeji** [comment]
I think the hash mismatch is part of the test and meant to occur, see `All tests successful` a few lines below it. 

The test that actually fails is `FAIL: tests/gc-concurrent.sh`

**Comment by volth** [comment]
@GrahamcOfBorg build hydra nix1 nix-serve

well, lets try to bisect

**Comment by volth** [comment]
@GrahamcOfBorg build hydra nix1 nix-serve

**Comment by volth** [comment]
Hm, there is **no** difference in code between ```1.57_01``` and ```1.58``` (besides the version number in string constants)

But ```1.58``` failed and ```1.57_01``` succeeded.

I rerun the build with ```1.58``` here: https://github.com/NixOS/nixpkgs/pull/41725

**Pull request closed without merging**
