### PR TITLE
nix-daemon: strip /nixpkgs from nixpkgs channel

### PR DESCRIPTION
**Pull request by lukateras**
Alternative to #39682.

### CODE REVIEW

**Review by matthewbauer — APPROVED** [review]
This is much better to me at least! Should verify it still works okay with https://nixos.org/channels/ though.

**Comment by yegortimoshenko** [comment]
Works for me.

**Comment by edolstra** [comment]
I'm very hesitant about this. I'm pretty sure there was a reason for using the `nixpkgs` symlink but I don't remember what it was.

**Comment by matthewbauer** [comment]
@edolstra Maybe you would prefer the original, #39682? I didn't like having it in the top tree, but that was before I realized that the channels already have the nixpkgs symlink.

**Comment by dezgeg** [comment]
Maybe this commit which actually creates the symlink in question has an explanation?
````
commit 2cd7c1f19888ae73bf7ef0f41a45680cfb86334a
Author: Eelco Dolstra <eelco.dolstra@logicblox.com>
Date:   Wed Aug 5 17:29:08 2015 +0200

    Unify NixOS and Nixpkgs channel structure
    
    This is primarily to ensure that
    
      -I nixpkgs=https://nixos.org/channels/nixos-unstable/nixexprs.tar.xz
    
    and
    
      -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz
    
    and
    
      -I nixpkgs=https://nixos.org/channels/nixpkgs-unstable/nixexprs.tar.xz
    
    behave consistently.
    
    It also allows installing packages via "nix-env -iA nixos.<pkg>"
    rather than "nixos.pkgs.<pkg>". It would be even better to allow
    "nixpkgs.<pkg>", but that requires a change to nix-channel.
````

**Comment by yegortimoshenko** [comment]
Locations that do have `nixpkgs -> .` symlink:

* https://nixos.org/channels/nixos-unstable/nixexprs.tar.xz

Locations that don't (currently broken, fixed by this patch):

* https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz
* https://nixos.org/channels/nixpkgs-unstable/nixexprs.tar.xz
* https://github.com/NixOS/nixpkgs/archive/master.tar.gz

This seems to be a safe change to me, because it only normalizes the first case. For this change to cause breakage, there should be a nixpkgs channel that a) has `nixpkgs/` directory, b) it is something other than `nixpkgs -> .` symlink. It seems that there are no such channels.

**Comment by dezgeg** [comment]
I agree with that analysis, this change seems safe. I'm guessing it used to be needed for pre-15.09 channels but those seem to be garbage-collected already so I can't check.

**Comment by yegortimoshenko** [comment]
Superseded by #40892.

**Comment by copumpkin** [comment]
Sorry I missed this, but thanks for all the discussion!

**Pull request closed without merging**
