### PR TITLE
cc-wrapper: deunify clang/gcc treatment of -isystem

### PR DESCRIPTION
**Pull request by ghost**
#### Problem

[Failures](https://hydra.nixos.org/build/215195834) [reported](https://github.com/NixOS/nixpkgs/pull/209870#issuecomment-1500028913) among packages which use gfortran:

#### Methodology

1. Add `-v` to `NIX_CFLAGS_COMPILE`
2. Run builds of `python3Packages.scipy` with and without [#209870](https://github.com/NixOS/nixpkgs/pull/209870) reverted
3. Run `nuke-refs` on the resulting logs
4. Run `wdiff -n | colordiff` on the nuked logs
 
#### Diagnosis

you-can-run-but-you-cant-hide

#### The fix

```
commit 77239eb5b09e5f0c507887524557b987a5508e50
Author: Adam Joseph <adam@westernsemico.com>
Date:   Fri Apr 7 21:44:28 2023 -0700

    In https://github.com/NixOS/nixpkgs/pull/209870 I tried to unify the
    treatment of clang and gcc in cc-wrapper as much as possible.
    However it appears that I went too far.

    Clang requires -isystem flags in order to be able to find gcc's
    libstdc++.  Gcc does not need these flags.  If they are added,
    gfortran will get confused:

      https://github.com/NixOS/nixpkgs/pull/209870#issuecomment-1500550903

    This commit deunifies the chunk of code that adds the -isystem
    flags, and explains why this chunk applies only to clang.
```

#### Validation

I hacked in this PR's fix to `scipy` (only) using `wrapCCWith` and `scipy` built correctly.  Currently verifying a global rebuild with this PR, but it won't finish until after I go to sleep.

@vcunat, if the situation is urgent we can send the `wrapCCWith`-hacked version to `staging-next`.  Otherwise the fix has to wait for this PR's global rebuild :frowning_face:

### CODE REVIEW

**Comment by amjoseph-nixpkgs** [comment]
Verifying that this fixes scikit-learn...

**Comment by amjoseph-nixpkgs** [comment]
Hrm, it got farther but failed (differently).  Investigating.

```
python3.10-scipy>   [202/1619] Compiling C++ object scipy/_lib/_uarray/_uarray.cpython-310-x86_64-linux-gnu.so.p/_uarray_dispatch.cxx.o
python3.10-scipy>   [203/1619] Compiling C++ object scipy/special/_ufuncs_cxx.cpython-310-x86_64-linux-gnu.so.p/ellint_carlson_wrap.cxx.o
python3.10-scipy>   [204/1619] Generating 'scipy/special/_test_internal.cpython-310-x86_64-linux-gnu.so.p/_test_internal.c'.
python3.10-scipy>   /nix/store/4i6p479ffikrcg11s28lb5dajjy7n5sa-python3.10-pythran-0.11.0/lib/python3.10/site-packages/pythran/tables.py:4530: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
python3.10-scipy>     if not hasattr(numpy, method):
python3.10-scipy>   /nix/store/4i6p479ffikrcg11s28lb5dajjy7n5sa-python3.10-pythran-0.11.0/lib/python3.10/site-packages/pythran/tables.py:4563: FutureWarning: In the future `np.bytes` will be defined as the corresponding NumPy scalar.
python3.10-scipy>     obj = getattr(themodule, elem)
python3.10-scipy>   ninja: build stopped: subcommand failed.
python3.10-scipy>   INFO: autodetecting backend as ninja
python3.10-scipy>   INFO: calculating backend command to run: /nix/store/f26yn4dnlq3wiw72pw01r3ywi52cfn89-ninja-1.11.1/bin/ninja
python3.10-scipy>   + meson setup --prefix=/nix/store/45v06dfypiw75jn6dwffyv4y10d3pdhy-python3-3.10.10 /build/scipy-1.10.1 /build/scipy-1.10.1/.mesonpy-f17ks_i7/build --native-file=/build/scipy-1.10.1/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2
python3.10-scipy>   + meson compile
python3.10-scipy>   error: subprocess-exited-with-error
python3.10-scipy>   × Preparing metadata (pyproject.toml) did not run successfully.
python3.10-scipy>   │ exit code: 1
python3.10-scipy>   ╰─> See above for output.
python3.10-scipy>   note: This error originates from a subprocess, and is likely not a problem with pip.
python3.10-scipy>   full command: /nix/store/45v06dfypiw75jn6dwffyv4y10d3pdhy-python3-3.10.10/bin/python3.10 /nix/store/8ncihaxa3fr5iybjv7h2k7ybfaksgy33-python3.10-pip-23.0.1/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_wheel /build/tmpgbr5fyny
python3.10-scipy>   cwd: /build/scipy-1.10.1
python3.10-scipy>   Preparing metadata (pyproject.toml) ... error
python3.10-scipy> error: metadata-generation-failed
python3.10-scipy> × Encountered error while generating package metadata.
python3.10-scipy> ╰─> See above for output.
python3.10-scipy> note: This is an issue with the package mentioned above, not pip.
python3.10-scipy> hint: See above for details.
error: build of '/nix/store/dxm3i9w4zf5sxpsrl44km56w6rdszs8r-python3.10-scipy-1.10.1.drv' on 'ssh://root@192.168.22.104' failed: builder for '/nix/store/dxm3i9w4zf5sxpsrl44km56w6rdszs8r-python3.10-scipy-1.10.1.drv' failed with exit code 1
error: builder for '/nix/store/dxm3i9w4zf5sxpsrl44km56w6rdszs8r-python3.10-scipy-1.10.1.drv' failed with exit code 1;
       last 10 log lines:
       >   full command: /nix/store/45v06dfypiw75jn6dwffyv4y10d3pdhy-python3-3.10.10/bin/python3.10 /nix/store/8ncihaxa3fr5iybjv7h2k7ybfaksgy33-python3.10-pip-23.0.1/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_wheel /build/tmpgbr5fyny
       >   cwd: /build/scipy-1.10.1
       >   Preparing metadata (pyproject.toml) ... error
       > error: metadata-generation-failed
       >
       > × Encountered error while generating package metadata.
       > ╰─> See above for output.
       >
       > note: This is an issue with the package mentioned above, not pip.
       > hint: See above for details.
       For full logs, run 'nix log /nix/store/dxm3i9w4zf5sxpsrl44km56w6rdszs8r-python3.10-scipy-1.10.1.drv'.
error: 1 dependencies of derivation '/nix/store/dbz2xia96mvmz6zs7s00dn2dgcg12i1i-python3.10-scikit-learn-1.2.1.drv' failed to build

```

**Comment by amjoseph-nixpkgs** [comment]
Reminds me of:
- https://github.com/NixOS/nixpkgs/pull/225117#issue-1658479017

**Comment by amjoseph-nixpkgs** [comment]
Alright there does not seem to be any quick fix here.

I'm running builds of `staging` with and without the Nix-driven bootstrap reverted, and `-v` added to `NIX_CFLAGS_COMPILE`.  I'll `nuke-refs` the resulting logs and look at the diffs to see what went wrong.

**Comment by amjoseph-nixpkgs** [comment]
you-can-run-but-you-cant-hide

**Review by trofi — APPROVED** [review]

**Comment by lovesegfault** [comment]
@amjoseph-nixpkgs i think you want to target staging-next?

**Comment by vcunat** [comment]
I think I'll go for a workaround using this just for the specific breakage(s) in the current staging-next, as rebuilding linux stdenvs is quite costly.

**Comment by amjoseph-nixpkgs** [comment]
> @amjoseph-nixpkgs i think you want to target staging-next?

This causes a global rebuild; is that okay?  I thought `staging-next` was sort of like `master` -- no mass-rebuilds allowed.  Did I misunderstand?

Anyways it doesn't matter to me.

Also, my rebuild went way faster than I thought; I should have a rebuilt-from-scratch `scipy` in the next few minutes.

**Comment by amjoseph-nixpkgs** [comment]
> I think I'll go for a workaround using this just for the specific breakage(s) in the current staging-next, as rebuilding linux stdenvs is quite costly.

I'll submit that as a separate PR.

It may not fix all the breakage, but it will fix `scipy`.

**Comment by amjoseph-nixpkgs** [comment]
> I think I'll go for a workaround using this just for the specific breakage(s) in the current staging-next

- https://github.com/NixOS/nixpkgs/pull/225273

**Comment by vcunat** [comment]
I'm a bit confused that you mention `scipy` all the time, as that package worked: https://hydra.nixos.org/job/nixpkgs/staging-next/python310Packages.scipy.x86_64-linux

**Comment by vcunat** [comment]
(it was `python3.pkgs.scikit-learn` that I knew to be broken)

**Comment by amjoseph-nixpkgs** [comment]
> I'm a bit confused that you mention `scipy` all the time, as that package ~worked~ built successfully: https://hydra.nixos.org/job/nixpkgs/staging-next/python310Packages.scipy.x86_64-linux

You are right, I was very confused.  I diffed the wrong build!  But I think it doesn't matter.  Checking now, should take another 5-10 minutes.

**Comment by vcunat** [comment]
I was doing my own hack in parallel and it did not fix the build.  But mine was lighter on rebuilds and maybe I've made some mistake.

**Comment by amjoseph-nixpkgs** [comment]
My first draft of this PR included 4bdc817f052c1140897f20736735f183622d1563 which causes `scipy` (which is a prerequisite of `scikit-learn`) to fail for the same reason that `scikit-learn` fails.  So I wrote a fix for the failure under those circumstances.

I'm currently verifying that the fix in this PR also fixes `scikit-learn`.  I'm pretty sure it does.  Should be another 5-10 minutes.

**Comment by amjoseph-nixpkgs** [comment]
WTF.

Okay, I have embarrassed myself enough and made enough mistakes for one day.

This will resume after I have slept.

**Comment by vcunat** [comment]
No problem :-)  Fortunately it still seems like simple hacks will suffice for now, so a proper solution isn't urgent and could be a mass rebuild.

**Comment by amjoseph-nixpkgs** [comment]
:heavy_check_mark: This PR is ready.  @vcunat @trofi please consider merging this.

It contains two commits, and **both** are needed.  If you omit either one of them, `scikit-learn` will fail to build (although the failure might be different, or one of its dependencies might fail before it even starts building).

-----

Got it!  To fix `scikit-learn` you need *both* [trofi's suggestion](https://github.com/NixOS/nixpkgs/commit/4bdc817f052c1140897f20736735f183622d1563) *and also* the change to `-isystem`.

Proof:

```
nix@moore:/git/work/fix/scikit/with-trofi-idea$ git rev-parse HEAD
de7cbf714b8562d4dddbe284a205e5d92f7b7bf7
nix@moore:/git/work/fix/scikit/with-trofi-idea$ nix-instantiate . -A python3Packages.scikit-learn
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
/nix/store/j9jd3mad0624pfhn9vlmc17rvk9017a2-python3.10-scikit-learn-1.2.1.drv
nix@moore:/git/work/fix/scikit/with-trofi-idea$ nix-build . -A python3Packages.scikit-learn
/nix/store/z3fxmiam657acwl10jwkhygvvgda44ll-python3.10-scikit-learn-1.2.1
```

The [failure I ran into with `scipy`](https://github.com/NixOS/nixpkgs/pull/225220#issuecomment-1500696592) only seems to arise if you have `buildPlatform.config==hostPlatform.config && buildPlatform!=hostPlatform`.  My local tree (which is based on `staging`) works like this (due to `gcc.arch` customization).  But the root cause of that failure and the root cause of `scikit-learn` on plain-vanilla `staging` are definitely related, and this PR now fixes them both.

**Comment by amjoseph-nixpkgs** [comment]
@ofborg build python3Packages.scikit-learn

**Review by trofi — APPROVED** [review]
LGTM, to state the obvious it's a full linux rebuild:

```
$ ./maintainers/scripts/rebuild-amount.sh HEAD^
Estimating rebuild amount by counting changed Hydra jobs (parallel=unset).
      1 pkgs-lib-tests
      2 x86_64-darwin
  57773 x86_64-linux
```

**Comment by amjoseph-nixpkgs** [comment]
> LGTM, to state the obvious it's a full linux rebuild:

Yes indeed.

The low-rebuilds version in https://github.com/NixOS/nixpkgs/pull/225273 has been updated; I'm just waiting to make sure it works before undraftifying it.  If it works, I think the best plan is to merge that one to `staging-next`, and then in the next full-rebuild cycle revert #225273 and merge this.

**Comment by amjoseph-nixpkgs** [comment]
I have cherry-picked 4b9280f8fd008b7bd22aeff50ede5195dcf355fb and then reverted it.  Once `staging-next` merges to `staging` github will drop the cherry-picked commit, and then when this merges it will revert 4b9280f8fd008b7bd22aeff50ede5195dcf355fb.

This way we won't forget to revert 4b9280f8fd008b7bd22aeff50ede5195dcf355fb.

**Comment by Artturin** [comment]
Needs rebase

**Comment by vcunat** [comment]
Well yes, it needs a revert of e2691227cdc4.

**Comment by Artturin** [comment]
> Well yes, it needs a revert of [e269122](https://github.com/NixOS/nixpkgs/commit/e2691227cdc424c643511d40fd6234acdf77372e).

i did
```
git rebase --onto staging HEAD~4 --interactive
```
then added `exec git revert e269122` at the top, exited, then got the following
```
$ git rebase --onto staging HEAD~4 --interactive
Executing: git revert e269122
Auto-merging pkgs/top-level/all-packages.nix
[detached HEAD a8c95cf146b] Revert "julia{18,19,}: fix build by a temporary hack"
 3 files changed, 4 insertions(+), 22 deletions(-)
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git rebase --skip'
interactive rebase in progress; onto da9d5848454
Last commands done (2 commands done):
   exec git revert e269122
   pick e64a751c475 python3Packages.scikit-learn: hack-fix missing libstdc++
Next commands to do (3 remaining commands):
   pick 3d904285202 Revert "python3Packages.scikit-learn: hack-fix missing libstdc++"
   pick 68ed28c77d6 gcc: never disableBootstrap for gfortran
  (use "git rebase --edit-todo" to view and edit)
You are currently rebasing branch 'pr/gfortran/do-not-disable-bootstrap' on 'da9d5848454'.
  (all conflicts fixed: run "git rebase --continue")
```
then ran `git rebase --continue`

and i think it worked

**Comment by amjoseph-nixpkgs** [comment]
> `git rebase --onto staging HEAD~4 --interactive`

BTW thanks for telling me about this trick earlier.  I figured out how to do it without manually counting commits (I often rebase 100+-long branches):

```
git-rebase-from-to() {
  echo "rebasing from $1 to $2"
  git rebase --onto $2 $(git merge-base $1 HEAD) HEAD
}
```

and then you can do things like

```
$ git-rebase-from-to origin/master origin/staging
rebasing from origin/master to origin/staging
...
```

**Pull request merged**
