### PR TITLE
python310Packages.cryptography: 40.0.1 -> 41.0.1

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by exarkun** [comment]
Can I help move this along somehow?

**Comment by SuperSandro2000** [comment]
@ofborg build python310Packages.cryptography python311Packages.cryptography

**Comment by exarkun** [comment]
I have now used this to build/test/package a recent version of Tahoe-LAFS against pyOpenSSL 23.2.0 (which requires cryptography >=41, <42).  I encountered one new test failure in Twisted (https://github.com/twisted/twisted/issues/11892) which I ended up patching in a skip for (it looks like a test bug to me, but it's also not entirely trivial to make sense of) and I had to upgrade service-identity to 23.1.0 to address an x509 parsing test failure that _looks_ related to cryptography to me.  With Twisted and service-identity thus adjusted, I had success with the cryptography in this PR on Python 3.8, Python 3.9, and Python 3.10.

**Comment by exarkun** [comment]
> I encountered one new test failure in Twisted ([twisted/twisted#11892](https://github.com/twisted/twisted/issues/11892)) which I ended up patching in a skip for (it looks like a test bug to me, but it's also not entirely trivial to make sense of)

Upstream confirms this is a bug in Twisted's test suite which has already been fixed (but not released) - https://github.com/twisted/twisted/pull/11878

**Comment by SuperSandro2000** [comment]
depends on #238006

**Comment by SuperSandro2000** [comment]
Included in #244135

**Pull request closed without merging**
