### PR TITLE
dbeaver-bin: 24.1.1 -> 24.1.2

### LINKED ISSUE #325705: Update request: `dbeaver-bin` 24.1.1 → 24.1.2
- Package name: dbeaver-bin
- Latest released version: 24.1.2

- Current version on the unstable channel: 24.1.1
- Current version on the stable/release channel: 24.0.5

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@gepbird @mkg20001 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by 21CSM**
## Description of changes
Closes: #325705

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [X] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by gepbird — CHANGES_REQUESTED** [review]
Thanks for your contribution! Please update the hashes too, currently this package doesn't build due to a hash mismatch. You can do this by using the update script, run this from the root of your nixpkgs: `nix-shell maintainers/scripts/update.nix --argstr package dbeaver-bin`. (you need to change the version back to an older one, otherwise the update script thinks its up-to-date and won't update the hashes)

**Comment by 21CSM** [comment]
@gepbird  Thank you so much for this helpful feedback on my first contribution! I've applied the changes you suggested.

**Review by gepbird — CHANGES_REQUESTED** [review]
Awesome, tested on x86_64-linux, works as expected.

Just a minor nit with git: please squash your commit so there's a single commit that updates the version and the hashes with the first commit message (*dbeaver-bin: 24.1.1 -> 24.1.2*).
You can do this by changing the last 2 commits with rebase: `git rebase --interactive HEAD~2`. It will open a file where you can modify commits, change `pick 1a5f4ebd65eb dbeaver-bin: 24.1.1 -> 24.1.2` to `squash 1a5f4ebd65eb dbeaver-bin: 24.1.1 -> 24.1.2` then save and exit the file. A new file will open, change the commit message accordingly, save and exit. Now you can check if you did it right with `git log`, you should see only 1 commit related to dbeaver. You can `git push --force` to upload the commits.

**Comment by 21CSM** [comment]
@gepbird updated based on feedback. Again, thanks so much, it has been extremely helpful for me!

**Review by gepbird — APPROVED** [review]
LGTM, I'm glad I could help you!

**Review by yzx9 — APPROVED** [review]
1 package built:
dbeaver-bin

Result of `nixpkgs-review pr 325718` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>dbeaver-bin</li>
  </ul>
</details>

**Pull request merged**
