### PR TITLE
Update vllm to v0.3.2

### PR DESCRIPTION
**Pull request by ghpu**
## Description of changes
vllm updated to 0.3.2.

## Things done
vllm version and commit changed to match v0.3.2
bump torch version from 2.2.0 to 2.2.1

- Built on platform(s)
  - [x ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ghpu** [comment]
for @CertainLach , @happysalada :-)

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 292084` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.vllm</li>
    <li>python311Packages.vllm.dist</li>
  </ul>
</details>

**Comment by happysalada** [comment]
This looks good to me, but I don't have a system with cuda enabled to test now.
@ghpu can you run a nixpkgs-review on this PR to just show it works ?

**Comment by ghpu** [comment]
Trying, but nixpkgs-review is not working on my computer :-S
What I tried :
```
git clone https://github.com/NixOS/nixpkgs.git
cd nixpkgs
nix run 'nixpkgs#nixpkgs-review' pr 292084
git worktree remove -f /home/redacted/.cache/nixpkgs-review/pr-292084-2/nixpkgs
fatal: '/home/redacted/.cache/nixpkgs-review/pr-292084-2/nixpkgs' is not a working tree
Traceback (most recent call last):
  File "/nix/store/i47y1c2dcsr877irqrc81qgrlcmhzgip-nixpkgs-review-2.10.3/bin/.nixpkgs-review-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/i47y1c2dcsr877irqrc81qgrlcmhzgip-nixpkgs-review-2.10.3/lib/python3.11/site-packages/nixpkgs_review/__init__.py", line 10, in main
    cli.main(command, args)
  File "/nix/store/i47y1c2dcsr877irqrc81qgrlcmhzgip-nixpkgs-review-2.10.3/lib/python3.11/site-packages/nixpkgs_review/cli/__init__.py", line 334, in main
    return cast(str, args.func(args))
                     ^^^^^^^^^^^^^^^
  File "/nix/store/i47y1c2dcsr877irqrc81qgrlcmhzgip-nixpkgs-review-2.10.3/lib/python3.11/site-packages/nixpkgs_review/cli/pr.py", line 76, in pr_command
    contexts.append((pr, builddir.path, review.build_pr(pr)))
                                        ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/i47y1c2dcsr877irqrc81qgrlcmhzgip-nixpkgs-review-2.10.3/lib/python3.11/site-packages/nixpkgs_review/review.py", line 221, in build_pr
    pr = self.github_client.pull_request(pr_number)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/i47y1c2dcsr877irqrc81qgrlcmhzgip-nixpkgs-review-2.10.3/lib/python3.11/site-packages/nixpkgs_review/github.py", line 70, in pull_request
    return self.get(f"repos/NixOS/nixpkgs/pulls/{number}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/i47y1c2dcsr877irqrc81qgrlcmhzgip-nixpkgs-review-2.10.3/lib/python3.11/site-packages/nixpkgs_review/github.py", line 33, in get
    return self._request(path, "GET")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/i47y1c2dcsr877irqrc81qgrlcmhzgip-nixpkgs-review-2.10.3/lib/python3.11/site-packages/nixpkgs_review/github.py", line 29, in _request
    with urllib.request.urlopen(req) as resp:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/sxr2igfkwhxbagri49b8krmcqz168sim-python3-3.11.8/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/sxr2igfkwhxbagri49b8krmcqz168sim-python3-3.11.8/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/sxr2igfkwhxbagri49b8krmcqz168sim-python3-3.11.8/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/nix/store/sxr2igfkwhxbagri49b8krmcqz168sim-python3-3.11.8/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/sxr2igfkwhxbagri49b8krmcqz168sim-python3-3.11.8/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/nix/store/sxr2igfkwhxbagri49b8krmcqz168sim-python3-3.11.8/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
```

**Comment by CertainLach** [comment]
Works for me on ROCm with https://github.com/NixOS/nixpkgs/pull/292097

**Review by CertainLach — APPROVED** [review]

**Pull request merged**
