### PR TITLE
Add trytond module dependencies

### PR DESCRIPTION
**Pull request by johbo**
###### Motivation for this change

I am working on adding support for the modules of trytond. This PR contains a first chunk of dependencies needed to install them.

Details about the modules which are available in the project: http://doc.tryton.org/4.2/modules/index.html

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by johbo** [comment]
On my NixOS box things did build cleanly after disabling tests for zope_configuration on python 3.

On darwin I was not able to build all packages via nox, mainly due to issues around the cffi package on python35, it has failing tests.

**Comment by FRidh** [comment]
Failing tests with cffi? That is not good. Could you turn on the sandbox?

**Comment by johbo** [comment]
Hmm, not sure how the sandbox on darwin works, need to set up a few bits most probably. 

I've tried to build things on master via `nix-build python35Packages.cffi`, it's failing in a similar way there:

```
====== 197 failed, 1588 passed, 122 skipped, 4 xfailed in 396.50 seconds =======
builder for ‘/nix/store/894al50a57swq9dyzl2h6r87jqrnar05-python3.5-cffi-1.9.1.drv’ failed with exit code 1
error: build of ‘/nix/store/894al50a57swq9dyzl2h6r87jqrnar05-python3.5-cffi-1.9.1.drv’ failed
```

Running the same on top of this change gave me this result:

```
====== 197 failed, 1588 passed, 122 skipped, 4 xfailed in 367.21 seconds =======
builder for ‘/nix/store/894al50a57swq9dyzl2h6r87jqrnar05-python3.5-cffi-1.9.1.drv’ failed with exit code 1
error: build of ‘/nix/store/894al50a57swq9dyzl2h6r87jqrnar05-python3.5-cffi-1.9.1.drv’ failed
```

My assumption is that the change in this PR did not really affect it. The build with python 2.7 just went fine on darwin.

**Comment by johbo** [comment]
Is there any check left which I could do for this PR?

**Comment by FRidh** [comment]
thanks for the reminder

**Pull request merged**
