### PR TITLE
Dead packages (Round 1)

### PR DESCRIPTION
**Pull request by NeQuissimus**
###### Motivation for this change

I was wondering about files that had not been touched for a long time and I came across a bunch of packages that are entirely broken.
Most of them cannot even be updated because their sources no longer exist.
Some of these packages I have been able to update.

If you object to the removal of any of these packages, let me know.

Edit: For those wondering, this is how I am finding old files (Is there a better way?)

```bash
git ls-tree -r --name-only HEAD | while read filename; do  
  echo "$(git log -1 --format="%at | %h | %an | %ad |" -- $filename) $filename" >> files.txt
done
```

### CODE REVIEW

**Comment by aneeshusa** [comment]
I have an affection for `cowsay` and would hate to see it go :(
It's fun, I like showing it to people new to the command line, and it makes for a great example in a variety of arenas (talking about scripting, packaging, etc.)

**Comment by NeQuissimus** [comment]
@aneeshusa I tried finding the sources for cowsay but was unable to find anything maintained. If you could provide a link to the official sources, I will add it back.

**Comment by NeQuissimus** [comment]
This will do for round 1. I am waiting for feedback on `cowsay`, then I will merge this in

**Comment by nbp** [comment]
@NeQuissimus 
https://packages.debian.org/source/sid/cowsay

**Comment by NeQuissimus** [comment]
I put `cowsay` back with the latest Debian-maintained version

**Comment by vcunat** [comment]
- All code.google.com stuff was migrated to github so isn't really dead: https://opensource.googleblog.com/2015/03/farewell-to-google-code.html
- It would be nice to notify `meta.maintainers` explicitly (and give them a couple days).
- The tarball job got broken because of this; fixed in c6fcd28e.

**Pull request merged**
