### PR TITLE
element-*: 1.9.6 -> 1.9.7

### PR DESCRIPTION
**Pull request by pstn**
###### Motivation for this change
https://matrix.org/blog/2021/12/13/disclosure-buffer-overflow-in-libolm-and-matrix-js-sdk

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sumnerevans** [comment]
Closes https://github.com/NixOS/nixpkgs/issues/150552

**Comment by sumnerevans** [comment]
The commit message is wrong. Should be `1.9.6 -> 1.9.7`

**Comment by sumnerevans** [comment]
Result of `nixpkgs-review pr 150558` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>element-desktop</li>
    <li>element-desktop-wayland</li>
  </ul>
</details>

```
 nix --experimental-features nix-command build --no-link --keep-going --option build-use-sandbox relaxed -f /home/sumner/.cache/nixpkgs-review/pr-150558/build.nix
error: hash mismatch in fixed-output derivation '/nix/store/cj06wjiha7ab79iiqcppqpz3k3l6rqrd-source.drv':
         specified: sha256-EUH7Pm2e/5+m/MLxg04Kup2+mpFx4mbht2mpQ6rd2LU=
            got:    sha256-bUzIIPNVgK2whQJoEZOaoa+jsJx4No+xji6hXK6wxFY=
error: 1 dependencies of derivation '/nix/store/1b1dwz9k1zmh59zx3kqcjpm95cb2b2i7-offline.drv' failed to build
error: 2 dependencies of derivation '/nix/store/pwkzn0cmrfib9s13gnalq2mp8x77cwm6-element-desktop-modules-1.9.7.drv' failed to build
error: 3 dependencies of derivation '/nix/store/7jf9cyqv74p912saakr838g5rknhyvl7-element-desktop-1.9.7.drv' failed to build
error: 3 dependencies of derivation '/nix/store/drvf7xwz4667lh6lhszzyvd4s22fy2i5-element-desktop-1.9.7.drv' failed to build
error: 2 dependencies of derivation '/nix/store/fbww6ilcvgqvdck0i6il49rbdam3dj85-review-shell.drv' failed to build

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/150558

2 packages failed to build:
element-desktop element-desktop-wayland
```

**Comment by pstn** [comment]
Result of `nixpkgs-review pr 150558` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>                                                                                            
  <summary>3 packages built:</summary>                                                               
  <ul>                                                                                               
    <li>element-desktop</li>                                                                         
    <li>element-desktop-wayland</li>                                                                 
    <li>element-web</li>                                                                             
  </ul>                                                                                              
</details>

Previous error was caused by old nixpkgs checkout.

**Comment by lourkeur** [comment]
691111d99ff resolves the stale hash

`element-desktop` tested, looks up to date and safe to me

Result of `nixpkgs-review pr 150558` run on x86_64-linux [1](https://github.com/Mic92/>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>element-desktop</li>
    <li>element-desktop-wayland</li>
    <li>element-web</li>
  </ul>
</details>

**Review by bbjubjub2494 — APPROVED** [review]

**Review by sumnerevans — APPROVED** [review]
Result of `nixpkgs-review pr 150558` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>element-desktop</li>
    <li>element-desktop-wayland</li>
    <li>element-web</li>
  </ul>
</details>

**Review by fpletz — APPROVED** [review]

**Comment by 0x4A6F** [comment]
Should `version` and `sha256` be also bumped in `pkgs/applications/networking/instant-messengers/element/element-{desktop,web}.nix`?

Element (Desktop) version is still reported with `1.9.2`, olm with `3.2.3`.

Was the `update.sh` script used in this update?

**Comment by Ma27** [comment]
> Element (Desktop) version is still reported with 1.9.2, olm with 3.2.3.

Where?

> Should version and sha256 be also bumped in pkgs/applications/networking/instant-messengers/element/element-{desktop,web}.nix?

On which branch are you?

**Comment by 0x4A6F** [comment]
Sorry, was on the wrong PR. Comment was intended for https://github.com/NixOS/nixpkgs/pull/150589#issuecomment-992832683, which is 21.05 and does not yet inherit version and rev from pinData.

**Pull request merged**
