### PR TITLE
ghc*: Increase build timeout to 1 day

### PR DESCRIPTION
**Pull request by roberth**
###### Motivation for this change

The default of 10 hours is insufficient for some of the slower platforms like macOS and aarch64.
The timeout failures have been causing delays _and_ waste of build agent time on staging-20.09, quite opposite of the intent of the timeout feature.

I've decided not to tune the timeout per system type, because I don't expect GHC to have this kind of problem, and if it does, it would normally be caught by the lack of build log output after two hours. The `timeout` is a last resort for builds/tests that loop while printing to the log. So decreasing the timeout for `x86_64-linux` would be over-engineered.

###### Things done

Applied this to staging-20.09 #103007 which _should_ soon merge into release-20.09.

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by cdepillabout — APPROVED** [review]
I didn't realize this feature was available, but it sounds like this is a good idea for `ghc`.

**Comment by jonringer** [comment]
should we run through a smaller subset of tests for those platforms?

**Comment by roberth** [comment]
> should we run through a smaller subset of tests for those platforms?

I don't think the time spent in tests is significant inside a ghc build.

**Comment by jonringer** [comment]
Probably true

**Pull request merged**
