### PR TITLE
quagga: remove

### PR DESCRIPTION
**Pull request by Mic92**
Upstream repositories do no longer exists. There has been no release in
a while. - Not a good combination for a network daemon running as root
in C that parses network packets...

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nixinator** [comment]
Looks like https://github.com/FRRouting/frr forked from quagga and seems to be it's direct replacement.

i don't think it in nixpkgs. may have a look at packaging it up.

**Comment by Mic92** [comment]
Feel free to add it afterwards. I would still suggest to name the module after the fork in that case.

**Comment by primeos** [comment]
LGTM (cc @fpletz - FYI, based on https://github.com/NixOS/nixpkgs/commits/3e01d420248ff13630a2c0a7cfd95ce56e9fd846/pkgs/servers/quagga/default.nix)

**Comment by woffs** [comment]
I'll try to build FRR.

**Pull request merged**
