### PR TITLE
nixos/nixos-option: fix evaluator to render a full submodule entry

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

When running e.g. `nixos-option users.users.ma27`, the evaluation breaks
since `ma27` is the attribute name in `attrsOf (submodule {})`, but not
a part of the option tree and therefore breaks with the following
errors:

```
error: At 'ma27' in path 'users.users.ma27': Attribute not found
An error occurred while looking for attribute names. Are you sure that 'users.users.ma27' exists?
```

This happens since the option evaluator expects that either the option
exists or the option is a submodule and the "next" token in the
attribute path points to an option (e.g. `users.users.ma27.createHome`).

This patch checks in the `Attribute not found` condition if the attribute-path
actually exists in the config tree. If that's true, a dummy-attrset is created
which contains `{_type = "__nixos-option-submodule-attr";}`, in that case, the
entire entry of the submodule will be displayed.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @chkno

### CODE REVIEW

**Comment by chkno** [comment]
This patch doesn't fix this problem for me.  I still get the same  "Attribute not found" error message when I run `nixos-option users.users.root` with and without this change.

I agree that this should be fixed.  I propose a slightly different way to fix it: https://github.com/chkno/nixpkgs/commit/35ac88deb15c17a9495f7607dd22bc5d4b122a84

(I'm not sure how the PR mechanics work from here.  Do I start a separate pull request?  Do you switch the source branch of this pull request from Ma27:submodule-fixes-for-nixos-option to chkno:submodule-fix-for-nixos-option?  Do you copy that commit to this PR branch?)

**Comment by Ma27** [comment]
Oof.... you're right, that was an avoidable mistake (it worked in my case due to a coincidence :/). Updated the code now. (I'd prefer to have the attribute printed when running `nixos-option users.users.ma27` tbh).

Regarding contributions from your side: feel free to open a PR against this branch on my fork :)

**Comment by chkno** [comment]
I created https://github.com/Ma27/nixpkgs/pull/2 to pull that change into this PR.

**Review by chkno — APPROVED** [review]

**Review by lheckemann — APPROVED** [review]
I've tested this and it works nicely, but I haven't reviewed the code changes.

**Pull request merged**
