### PR TITLE
ocamlPackages.*: huge update because everything is linked, send help

### PR DESCRIPTION
**Pull request by StridBot**
Update a bunch of packages in `ocamlPackages`.

### CODE REVIEW

**Comment by ulrikstrid** [comment]
If we merge https://github.com/NixOS/nixpkgs/pull/162383 we can probably drop a bunch of tezos packages and then we can merge this.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 165661` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>ligo: log was empty</li>
  </ul>
</details>

**Comment by ulrikstrid** [comment]
This PR got a bit out of hand, I started updating ringo and then had to fix more packages which lead me to have to fix more packages.

I'm not sure how to handle such a large PR as this honestly and I'm not sure each commit builds on it's own or if that is even possible.

We *might* be able to slice it for updates related to `cstruct` and updates related to `cmdliner` but some of the packages most likely needs both changes.

cc @vbgl and @sternenseemann since you're the maintainers of most of the updated packages.

**Comment by wegank** [comment]
Closing as (most) packages are up-to-date now.

**Pull request closed without merging**
