### PR TITLE
way-cooler: 0.8.0 -> 0.8.1

### PR DESCRIPTION
**Pull request by ghost**
###### Motivation for this change

Closes https://github.com/NixOS/nixpkgs/issues/50847

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by gnidorah** [comment]
@P-E-Meunier I've regenerated only way-cooler derivation using recent carnix, components (wc-bg, wc-lock, wc-grab) are left untouched, because I don't know how to merge crates-io.nix files altogether https://nest.pijul.org/pmeunier/carnix/discussions/23 And using an own crates-io.nix file for each component is not good for me.

**Comment by gnidorah** [comment]
@dywedir Done.

**Comment by dywedir** [comment]
@GrahamcOfBorg build way-cooler

**Comment by gnidorah** [comment]
@dywedir Thanks!

**Comment by dywedir** [comment]
@gnidorah thank you!

**Pull request merged**
