### PR TITLE
mastodon: 3.4.6 -> 3.5.0

### PR DESCRIPTION
**Pull request by erictapen**
###### Description of changes

[Release notes](https://github.com/mastodon/mastodon/releases/tag/v3.5.0)

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by erictapen** [comment]
Blocking: https://github.com/mastodon/mastodon/issues/17831

**Comment by Izorkin** [comment]
You can add instructions on how to use `./update.sh`?
I manually added the required packages, and only after that it started working for me.

**Comment by Izorkin** [comment]
I have a build error:
```
yarn install v1.22.18
warning You don't appear to have an internet connection. Try the --offline flag to use the cache for registry queries.
info There appears to be trouble with your network connection. Retrying...
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
[4/6] Linking dependencies...
warning " > react-redux-loading-bar@4.0.8" has incorrect peer dependency "react-redux@^3.0.0 || ^4.0.0 || ^5.0.0".
warning Workspaces can only be enabled in private projects.
info There appears to be trouble with your network connection. Retrying...
[5/6] Building fresh packages...
warning Error running install script for optional dependency: "/build/mastodon-patched/node_modules/bufferutil: Command failed.
Exit code: 127
Command: node-gyp-build
Arguments:
Directory: /build/mastodon-patched/node_modules/bufferutil
Output:
/bin/sh: node-gyp-build: not found"
info This module is OPTIONAL, you can safely ignore this error
warning Error running install script for optional dependency: "/build/mastodon-patched/node_modules/utf-8-validate: Command failed.
Exit code: 127
Command: node-gyp-build
Arguments:
Directory: /build/mastodon-patched/node_modules/utf-8-validate
Output:
/bin/sh: node-gyp-build: not found"
info This module is OPTIONAL, you can safely ignore this error
[6/6] Cleaning modules...
info There appears to be trouble with your network connection. Retrying...
Done in 6.98s.
info There appears to be trouble with your network connection. Retrying...

```

**Comment by Izorkin** [comment]
Working patch:
```diff
diff --git a/pkgs/servers/mastodon/default.nix b/pkgs/servers/mastodon/default.nix
index d84377f0945..afb952a5c84 100644
--- a/pkgs/servers/mastodon/default.nix
+++ b/pkgs/servers/mastodon/default.nix
@@ -1,6 +1,7 @@
 { lib, stdenv, nodejs-slim, mkYarnPackage, fetchFromGitHub, bundlerEnv, nixosTests
 , yarn, callPackage, imagemagick, ffmpeg, file, ruby_3_0, writeShellScript
 , fetchYarnDeps, fixup_yarn_lock
+, fetchpatch

   # Allow building a fork or custom version of Mastodon:
 , pname ? "mastodon"
@@ -16,6 +17,13 @@ stdenv.mkDerivation rec {
   # Putting the callPackage up in the arguments list also does not work.
   src = if srcOverride != null then srcOverride else callPackage ./source.nix {};

+  patches = [
+    (fetchpatch {
+      url = "https://github.com/mastodon/mastodon/commit/b8e4b02894c65adce9100e11ae0fcd5b9cc236ce.patch";
+      sha256 = "sha256-FPbi1HP4IhAxvgGwaonK7w0ayL9avMvwR1P5aRYpRBE=";
+    })
+  ];
+
   yarnOfflineCache = fetchYarnDeps {
     yarnLock = "${src}/yarn.lock";
     sha256 = "sha256:0kjrzjcr5p5lx2bn6jh105ma57302yxafxc6yyw3rgy9k118n93k";
@@ -57,6 +65,8 @@ stdenv.mkDerivation rec {
       yarn install --offline --frozen-lockfile --ignore-engines --ignore-scripts --no-progress
       patchShebangs ~/node_modules

+      # skip running yarn install
+      rm -rf ~/bin/yarn
       OTP_SECRET=precompile_placeholder SECRET_KEY_BASE=precompile_placeholder \
         rails assets:precompile
       yarn cache clean --offline

```

**Comment by Izorkin** [comment]
Update patch:
```
diff --git a/pkgs/servers/mastodon/default.nix b/pkgs/servers/mastodon/default.nix
index d84377f0945..8e85e4424b6 100644
--- a/pkgs/servers/mastodon/default.nix
+++ b/pkgs/servers/mastodon/default.nix
@@ -1,6 +1,7 @@
 { lib, stdenv, nodejs-slim, mkYarnPackage, fetchFromGitHub, bundlerEnv, nixosTests
 , yarn, callPackage, imagemagick, ffmpeg, file, ruby_3_0, writeShellScript
 , fetchYarnDeps, fixup_yarn_lock
+, fetchpatch

   # Allow building a fork or custom version of Mastodon:
 , pname ? "mastodon"
@@ -16,6 +17,13 @@ stdenv.mkDerivation rec {
   # Putting the callPackage up in the arguments list also does not work.
   src = if srcOverride != null then srcOverride else callPackage ./source.nix {};

+  patches = [
+    (fetchpatch {
+      url = "https://github.com/mastodon/mastodon/commit/b8e4b02894c65adce9100e11ae0fcd5b9cc236ce.patch";
+      sha256 = "sha256-FPbi1HP4IhAxvgGwaonK7w0ayL9avMvwR1P5aRYpRBE=";
+    })
+  ];
+
   yarnOfflineCache = fetchYarnDeps {
     yarnLock = "${src}/yarn.lock";
     sha256 = "sha256:0kjrzjcr5p5lx2bn6jh105ma57302yxafxc6yyw3rgy9k118n93k";
@@ -45,7 +53,7 @@ stdenv.mkDerivation rec {
     pname = "${pname}-modules";
     inherit src version;

-    nativeBuildInputs = [ fixup_yarn_lock mastodon-gems nodejs-slim yarn ];
+    nativeBuildInputs = [ fixup_yarn_lock nodejs-slim yarn mastodon-gems mastodon-gems.wrappedRuby ];

     RAILS_ENV = "production";
     NODE_ENV = "production";
@@ -55,8 +63,13 @@ stdenv.mkDerivation rec {
       fixup_yarn_lock ~/yarn.lock
       yarn config --offline set yarn-offline-mirror ${yarnOfflineCache}
       yarn install --offline --frozen-lockfile --ignore-engines --ignore-scripts --no-progress
+
+      patchShebangs ~/bin
       patchShebangs ~/node_modules

+      # skip running yarn install
+      rm -rf ~/bin/yarn
+
       OTP_SECRET=precompile_placeholder SECRET_KEY_BASE=precompile_placeholder \
         rails assets:precompile
       yarn cache clean --offline

```

**Comment by Izorkin** [comment]
```diff
diff --git a/nixos/modules/services/web-apps/mastodon.nix b/nixos/modules/services/web-apps/mastodon.nix
index dbcac234cc2..362268e38e5 100644
--- a/nixos/modules/services/web-apps/mastodon.nix
+++ b/nixos/modules/services/web-apps/mastodon.nix
@@ -12,6 +12,8 @@ let
     RAILS_ENV = "production";
     NODE_ENV = "production";

+    LD_PRELOAD = "${pkgs.jemalloc}/lib/libjemalloc.so";
+
     # mastodon-web concurrency.
     WEB_CONCURRENCY = toString cfg.webProcesses;
     MAX_THREADS = toString cfg.webThreads;

```

**Comment by Izorkin** [comment]
Patch `caniuse.patch` merged to upstream - https://github.com/mastodon/mastodon/pull/17902.

**Comment by erictapen** [comment]
@Izorkin Woah, nice!

**Review by Izorkin — APPROVED** [review]

**Comment by Izorkin** [comment]
I tested it on my instance - it works.
Can you check my PR-s for the Mastodon module?

**Review by Izorkin — APPROVED** [review]

**Comment by Izorkin** [comment]
Fix error:
```
Error importing StatusesIndex: undefined method `extract_status_plain_text' for StatusesIndex:Class
```

```diff
diff --git a/pkgs/servers/mastodon/default.nix b/pkgs/servers/mastodon/default.nix
index ef4c22b1c2c..b199f008daa 100644
--- a/pkgs/servers/mastodon/default.nix
+++ b/pkgs/servers/mastodon/default.nix
@@ -1,4 +1,4 @@
-{ lib, stdenv, nodejs-slim, mkYarnPackage, fetchFromGitHub, bundlerEnv, nixosTests
+{ lib, stdenv, nodejs-slim, mkYarnPackage, fetchFromGitHub, fetchpatch, bundlerEnv, nixosTests
 , yarn, callPackage, imagemagick, ffmpeg, file, ruby_3_0, writeShellScript
 , fetchYarnDeps, fixup_yarn_lock

@@ -21,6 +21,13 @@ stdenv.mkDerivation rec {
     sha256 = "sha256-Ngfs15YKLfSBOKju3BzpZFnenB370jId2G1g9Qy1y5w=";
   };

+  patches = [
+    (fetchpatch {
+      url = "https://github.com/mastodon/mastodon/commit/2ad5928574624c7fb650024969d646b85e6f7e88.patch";
+      sha256 = "sha256-uw8m6j4BzMQtev0LNLeIHW0xOJEmj3JikT/6gVfmvzs=";
+    })
+  ];
+
   mastodon-gems = bundlerEnv {
     name = "${pname}-gems-${version}";
     inherit version;
```

**Comment by erictapen** [comment]
> Fix error:

Could you open a separate PR for this? I wanted to get this merged, before waiting for the tests again. Also could you use the commit that was merged into `main`? https://github.com/mastodon/mastodon/commit/ef196c913c77338be5ebb1e02af2f6225f857080

**Pull request merged**
