### PR TITLE
thelounge: Set THELOUNGE_HOME environment variable

### PR DESCRIPTION
**Pull request by nuxeh**
Setting this environment variable allows the CLI to correctly locate the
state directory, allowing users to be added, etc. from the command line,
without additionally having to set this variable.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @Mrmaxmeier

### CODE REVIEW

**Comment by flokli** [comment]
Hmm, I wouldn't suggest to set this environment variable globally.

Instead, we might want to patch the CLI to use the used state directory location as a default. Reading its [function definition](https://github.com/thelounge/thelounge/blob/9ef5c6c67e463c1f401e33b21dfb5641636e5ed1/src/command-line/utils.js#L56), this could be accomplished by adding a
```
echo /var/lib/thelounge > $out/lib/node_modules/thelounge/.thelounge_home
```

to the `thelounge` `postInstall` in `pkgs/development/node-packages/default-v10.nix`.

**Comment by Ekleog** [comment]
@nuxeh Are you still interested in moving this forward, with @flokli's comments? :)

**Comment by nuxeh** [comment]
At the time I was somewhat doubtful of my own aptitude for implementing or testing it, I personally haven't written a line of Javascript in a long time.

Also it's my instinct that this solution is slightly more error-prone (especially going forwards, it may need to be maintained) than simply setting an environment variable, which doesn't seem to be too much of an issue? It'll only be present when the lounge is installed after all, and is fairly well namespaced as `THELOUNGE_HOME`. I don't really know the conventions of Nix for this sort of thing, however.

It is something that would be nice to have a fix for, certainly. I could look at it at some point.

**Comment by nuxeh** [comment]
Haha, oh wait, I wasn't paying enough attention... the suggestion isn't to patch the Javascript at all.

**Comment by nuxeh** [comment]
@Ekleog just done this, seems to work nicely!

**Comment by Ekleog** [comment]
Great! That said, I've just looked at the current state of this PR, and it looks to me like you could revert the changes in nixos/modules/services/networking/thelounge.nix now that the correct path is being set right into the CLI tools :)

**Comment by nuxeh** [comment]
Oh, right, yes, I totally forgot!

**Pull request merged**
