### PR TITLE
criterion: 2.3.3 -> 2.4.1, used prebuilt packge

### PR DESCRIPTION
**Pull request by SDAChess**
The criterion package was suffering of bad includes but that is
now fixed using the tarball that is build on the Release page on
Github. This commit also bumps the version from 2.3.3 to 2.4.1.

###### Description of changes

Changed the version and the package is now not built from the sources anymore.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin 
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by viraptor — CHANGES_REQUESTED** [review]
> was suffering of bad includes

What does it mean and why not fix that instead?

Also, this breaks non-Linux systems which were supported before. (but doesn't change the supported list)

Other packages which have subtle dependency issues have a package-bin version alternative instead of changing the main one. (see wkhtmltopdf-bin)

**Comment by SDAChess** [comment]
> What does it mean and why not fix that instead?
The include directory of the library could not be found by a C compiler. Using prebuilt library and headers fixes that issue and updates the software.
> Also, this breaks non-Linux systems which were supported before. (but doesn't change the supported list) 
My mistake here, there is no reason that it would break non Linux systems.

**Comment by Thesola10** [comment]
> > What does it mean and why not fix that instead?
> 
> The include directory of the library could not be found by a C compiler. Using prebuilt library and headers fixes that issue and updates the software.
> 
> > Also, this breaks non-Linux systems which were supported before. (but doesn't change the supported list) 
> 
> My mistake here, there is no reason that it would break non Linux systems.

That's a pretty poor fix. Have you considered adding a patch to the build files instead? Binary releases can lead to many more issues than they fix.

**Comment by SDAChess** [comment]
> That's a pretty poor fix. Have you considered adding a patch to the build files instead? Binary releases can lead to many more issues than they fix.

I've looked into a fix already but the new build system that they are using (meson) makes building from the source really hard without having to download external dependencies during the build process, which is explicitly disabled in the packaging code for Meson. I couldn't fix it myself but maybe you could give it a try?

**Comment by Thesola10** [comment]
All of the Meson dependencies mentioned are available in Nixpkgs. I'm almost building from source. If it's okay with you, I'll close this PR once I submit the source-based update.

**Review by Thesola10 — CHANGES_REQUESTED** [review]
Using a binary package reduces package compatibility, as well as runs the risk of unmet dynamic dependencies due to the way Nix works.

**Comment by Thesola10** [comment]
Superseded by #181821

**Comment by Thesola10** [comment]
Re-reading a bit, you mentioned "bad includes", could you clarify?

The headers are **not** in the default output (`out`), but in `dev`. Make sure to have both in your dev environment

**Pull request closed without merging**
