### PR TITLE
solc: 0.4.23 -> 0.4.24

### PR DESCRIPTION
**Pull request by sifmelcara**
###### Motivation for this change
Update the package. Enable the test.

###### Things done

1. `boost-shared-libs.patch` removed. (because it have been fixed by upstream)
2.  The `CMAKE_INSTALL_LIBDIR` fix is needed because it will cause build failure.
3. I removed `substituteInPlace cmake/EthCompilerSettings.cmake --replace "add_compile_options(-Werror)" ""` (I guess this is ok because it still builds)

cc maintainers @dbrock @akru 

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@grahamcofborg build solc

**Comment by xeji** [comment]
Please fix or disable the tests on darwin to avoid a regression.

**Comment by sifmelcara** [comment]
Tests disabled if on darwin or cross compiling.

**Comment by xeji** [comment]
@GrahamcOfBorg build solc

**Pull request merged**
