### PR TITLE
rust: 1.52.1 -> 1.53.0

### PR DESCRIPTION
**Pull request by kellerkindt**
###### Motivation for this change
rustc released on june 17th... that's already two days ago! 😉

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 127473` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>rustc</li>
  </ul>
</details>

**Comment by kellerkindt** [comment]
> /rebase staging

Excuse me, what do you mean by that?

**Comment by petabyteboy** [comment]
@GrahamcOfBorg build fd

**Comment by petabyteboy** [comment]
:heavy_check_mark:  Built fd, spidermonkey, firefox-esr, firefox on x86_64-linux.

Please rebase/cherry-pick this on top of staging, and then force-push to get rid of the merge commit.

**Comment by zowoq** [comment]
Duplicate of #127354

**Comment by siraben** [comment]
> > /rebase staging
> 
> Excuse me, what do you mean by that?

It's supposed to automatically migrate to PR to target staging (e.g. https://github.com/NixOS/nixpkgs/pull/110306#issuecomment-764559977) but failed here somehow

**Comment by zowoq** [comment]
The rebase action has been removed: 1ea409a4f01b4adf115fd798afe369a760240256.

**Pull request closed without merging**
