### PR TITLE
floorp: 11.6.1 -> 11.7.1

### PR DESCRIPTION
**Pull request by dr460nf1r3**
## Description of changes

Updated the package to the latest version.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by christoph-heiss — APPROVED** [review]
3 packages built:
floorp floorp-unwrapped floorp-unwrapped.debug

Result of `nixpkgs-review pr 275386` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>floorp</li>
    <li>floorp-unwrapped</li>
    <li>floorp-unwrapped.debug</li>
  </ul>
</details>

Changes LGTM. (Smoke-)tested the usual things as well.

**Review by PedroHLC — APPROVED** [review]
Diff LGTM

**Comment by christoph-heiss** [comment]
[v11.7.1](https://github.com/Floorp-Projects/Floorp/releases/tag/v11.7.1) has been released, please just bump it directly to this and just skip `.0`.
I'll do another build + test after this.

**Comment by dr460nf1r3** [comment]
Already noticed, I will be doing this in a few hours!

**Review by christoph-heiss — APPROVED** [review]
2 packages built:                                                          
floorp-unwrapped floorp-unwrapped.debug         

Result of `nixpkgs-review pr 275386` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>                                       
  <summary>2 packages built:</summary>
  <ul>                                                                      
    <li>floorp-unwrapped</li>
    <li>floorp-unwrapped.debug</li>
  </ul>                                                                         
</details>   

Everything looks good. :+1: 
I've also added the `backport release-23.11` label, since browser updates should generally be backported to stable.

**Review by PedroHLC — APPROVED** [review]

**Comment by emilylange** [comment]
Backport to `release-23.11` failes because #270455 (11.6.0 -> 11.6.1) is missing in `release-23.11`.
Meaning `release-23.11` is still on `11.6.0`.

**Pull request merged**
