### PR TITLE
plantuml: 8012 -> 8037

### PR DESCRIPTION
**Pull request by jraygauthier**
###### Things done:
- [ ] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- [x] Built on platform(s):  Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
###### More

Updated to latest stable version.

### CODE REVIEW

**Comment by joachifm** [comment]
Travis error looks legit

**Comment by jraygauthier** [comment]
Odd, it seem to have to do with this `sphinxcontrib-plantuml` python 3.5 package which has trouble with executing its `setup.py` script. Here is the important part:

~~~
writing manifest file '/tmp/nix-build-python3.5-sphinxcontrib-plantuml-0.5.drv-0/sphinxcontrib-plantuml-0.5/build/lib/sphinxcontrib_plantuml.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "nix_run_setup.py", line 6, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 36, in <module>
    use_2to3=True,
  File "/nix/store/ln2cn6g6rf116vaq1fgngaqzpzfq495x-python3-3.5.1/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/nix/store/ln2cn6g6rf116vaq1fgngaqzpzfq495x-python3-3.5.1/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/nix/store/ln2cn6g6rf116vaq1fgngaqzpzfq495x-python3-3.5.1/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/nix/store/8qi91pnjxk49s3nzgs2y4xqnrwpraxsl-python3.5m-setuptools-19.4/lib/python3.5/site-packages/setuptools-19.4-py3.5.egg/setuptools/command/test.py", line 159, in run
  File "/nix/store/8qi91pnjxk49s3nzgs2y4xqnrwpraxsl-python3.5m-setuptools-19.4/lib/python3.5/site-packages/setuptools-19.4-py3.5.egg/setuptools/command/test.py", line 140, in with_project_on_sys_path
  File "/nix/store/8qi91pnjxk49s3nzgs2y4xqnrwpraxsl-python3.5m-setuptools-19.4/lib/python3.5/site-packages/setuptools-19.4-py3.5.egg/setuptools/command/test.py", line 166, in run_tests
AttributeError: 'NoneType' object has no attribute 'split'
builder for â€˜/nix/store/z98239d322d06q8xm77a44v67yac74jh-python3.5-sphinxcontrib-plantuml-0.5.drvâ€™ failed with exit code 1
[31;1merror:[0m build of â€˜/nix/store/z98239d322d06q8xm77a44v67yac74jh-python3.5-sphinxcontrib-plantuml-0.5.drvâ€™ failed
[31mThe invocation of "nix-build -A python27Packages.sphinxcontrib_plantuml -A python35Packages.sphinxcontrib_plantuml -A python35Packages.plantuml -A plantuml -A python27Packages.plantuml /home/travis/.nox/nixpkgs" failed[0m
~~~

I'm not used to python packaging. It however does not seem related to its `plantuml` dependency tough and look like some `setuptool` issue.

**Comment by joachifm** [comment]
@FRidh @domenkozar might know

**Comment by FRidh** [comment]
`sphinxcontrib-plantuml` was already broken, so ignore it. I've seen this type of error before, likely it is incompatible with the setuptools version we use.

**Comment by FRidh** [comment]
Fixed `sphinxcontrib_plantuml` in c7e448818f01f733ac8cd6c49532002035c0c93c

**Comment by jraygauthier** [comment]
Thank you both :)

**Pull request merged**
