### PR TITLE
php.extensions.sqlsrv: 5.8.0 -> 5.8.1

### PR DESCRIPTION
**Pull request by aanderse**
###### Motivation for this change
https://github.com/microsoft/msphpsql/releases/tag/v5.8.1

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aanderse** [comment]
@etu @talyz I'm having a little issue with this one... any ideas?
```
~/nixpkgs> nix-build -E 'with import ~/nixpkgs {}; php.withExtensions (e: [ e.pdo_sqlsrv ])'                                                                                                        
error: attribute 'pdo' missing, at /home/aaron/nixpkgs/lib/strings-with-deps.nix:67:71
(use '--show-trace' to show detailed location information)
```

**Comment by etu** [comment]
`pdo_sqlsrv` needs the `pdo` extension, so php refuse to build it without it :slightly_smiling_face: 

Try:
```
nix-build -E 'with import ~/nixpkgs {}; php.withExtensions (e: [ e.pdo e.pdo_sqlsrv ])'
```

**Comment by aanderse** [comment]
Verified `pdo_sqlsrv` works with `php72`, `php73`, and `php74` by executing a simple `php` script to hit a database.

**Comment by aanderse** [comment]
@GrahamcOfBorg build php72.extensions.pdo_sqlsrv php73.extensions.pdo_sqlsrv php74.extensions.pdo_sqlsrv
@GrahamcOfBorg build php72.extensions.sqlsrv php73.extensions.sqlsrv php74.extensions.sqlsrv

**Comment by talyz** [comment]
Yeah, the error message is sadly pretty cryptic, since it originates in `strings-with-deps.nix`. We should try to catch it earlier and say something a bit more informational than `attribute xxx missing`..

**Comment by aanderse** [comment]
@GrahamcOfBorg build php72.extensions.pdo_sqlsrv php73.extensions.pdo_sqlsrv php74.extensions.pdo_sqlsrv
@GrahamcOfBorg build php72.extensions.sqlsrv php73.extensions.sqlsrv php74.extensions.sqlsrv

**Comment by aanderse** [comment]
I don't have a mac so can't effectively troubleshoot the issue... :man_shrugging:

Look good @etu and @talyz?

**Comment by talyz** [comment]
@aanderse It builds just fine in my mac, so whatever the build error was, it was probably just a CI glitch - they seem rather frequent on darwin..

**Comment by aanderse** [comment]
In that case I'm merging based on your feedback :+1:
Thank you @talyz :tada:

**Pull request merged**
