### PR TITLE
vmtouch: 1.0.2 -> 1.1.0

### PR DESCRIPTION
**Pull request by garrison**
###### Motivation for this change

Upstream release
###### Things done
- [x] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by garrison** [comment]
I am confused by the rather cryptic "Things done" checklist above.  Are these items my responsibility as submitter of this pull request?  I looked in CONTRIBUTING.md and "Chapter 11. Submitting changes" of the manual, and I am still unsure how to move forward.

**Comment by joachifm** [comment]
@garrison those are mainly suggestions for things you should/could do to reduce the risk of breaking stuff and to eliminate some sources of impurities (aka packaging problems). Not all steps apply to all PRs. In the present case, you have indicated that this is a blind update.

**Comment by garrison** [comment]
Thanks @joachifm. I think I have checked the appropriate checkboxes now.  As a meta issue, it would be really helpful for occasional contributors if this checklist were described in more detail.  I am still unsure from where I would run this `nix-shell -p nox --run "nox-review wip"` command.

**Comment by joachifm** [comment]
@garrison Thank you. LGTM. 

`nox` is typically run within your checkout. I don't think it's described very well anywhere, unfortunately. These days, travis is able to run `nox` fairly reliably and provides at least some protection against broken revdeps. I guess you'll have to use your own judgement as to the amount of breakage that may result from your update and whether running `nox review` locally is worth the cycles (it's incredibly slow, in my experience).

**Comment by garrison** [comment]
Thanks!

**Pull request merged**
