### PR TITLE
meson: 0.63.1 -> 0.64.1

### PR DESCRIPTION
**Pull request by raboof**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by doronbehar** [comment]
1. Why is this marked as a draft?
2. This should target staging
3. Any idea why does the `ofborg-eval-lib-tests` CI check fails?

**Comment by raboof** [comment]
> 1. Why is this marked as a draft?

Sorry, should've made a note: I didn't manage to properly test this, so I figured I'd at least open the draft PR as a conversation starter :)

> 2. This should target staging

Yes, sorry, I suspected as much but lost track of this PR before ofborg reported on the number of rebuilds. Is there a way to count rebuilds without waiting for ofborg?

> 3. Any idea why does the ` ofborg-eval-lib-tests`  CI check fails?

No - hmm, seems OK now that you retargeted to ` staging` ?

**Comment by doronbehar** [comment]
> > 2. This should target staging
> 
> Yes, sorry, I suspected as much but lost track of this PR before ofborg reported on the number of rebuilds. Is there a way to count rebuilds without waiting for ofborg?

I think it's the command listed [here](https://github.com/NixOS/ofborg#running-meta-checks-locally) but you should expect it uses a lot of RAM and time so IMO it's not worth it.
 
> > 3. Any idea why does the ` ofborg-eval-lib-tests`  CI check fails?
> 
> No - hmm, seems OK now that you retargeted to ` staging` ?

Yes it does :), only the `x86_64-darwin` build is failing, not due to the `meson` update I think.

**Comment by jtojnar** [comment]
Systemd will require a patch (or update to 252): https://github.com/systemd/systemd/issues/24323

**Comment by doronbehar** [comment]
So we'll wait for https://github.com/NixOS/nixpkgs/pull/201558 .

**Comment by doronbehar** [comment]
Rebased and force pushed with https://github.com/NixOS/nixpkgs/pull/201558 merged now.

**Comment by jtojnar** [comment]
BTW, there is [0.64.1](https://github.com/mesonbuild/meson/releases/tag/0.64.1) now.

**Comment by doronbehar** [comment]
> BTW, there is [0.64.1](https://github.com/mesonbuild/meson/releases/tag/0.64.1) now.

Thanks! Pushed.

**Comment by doronbehar** [comment]
Is it possible to test this update without building the world? `systemd-minimal` builds fine with this update.

**Comment by NickCao** [comment]
We may drop a few line from the cross-files too: https://github.com/mesonbuild/meson/commit/8a8ab9a8e0c2cefb6faa0734e52803c74790576c

**Comment by doronbehar** [comment]
> We may drop a few line from the cross-files too: [mesonbuild/meson@8a8ab9a](https://github.com/mesonbuild/meson/commit/8a8ab9a8e0c2cefb6faa0734e52803c74790576c)

Our cross-file doesn't seem to include references to these binaries:

https://github.com/NixOS/nixpkgs/blob/4b6303bf3d6f3ee2d2a20a8ba69678e3fc5e0f6f/pkgs/stdenv/generic/make-derivation.nix#L385-L399

**Pull request merged**
