### PR TITLE
sbcl: 2.4.10 -> 2.4.11

### PR DESCRIPTION
**Pull request by hraban**
~Get ahead of upcoming SBCL 2.4.11 release and support those overriding ‘src’.~

2.4.11 is now released might as well reuse this PR

Introduced in
https://sourceforge.net/p/sbcl/sbcl/ci/6c784b333ad2206be13c5588af6cf1e56d4ab3f8

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by hraban** [comment]
Good timing lol 😂 they just released 2.4.11

**Comment by hraban** [comment]
@ofborg build stumpwm sbcl.iolib

**Comment by 7c6f434c** [comment]
Should we start using `staging`, especially when we are just before NixOS 24.11 release? (Lisp packages are super quick to rebuild, but Hydra seems to have some per-derivation slowness)

**Comment by hraban** [comment]
Just re 24.11: I thought it branched off a while back and was in a dedicated pre-release, backports-only branch, but you may know more about this of course.

But in general I think staging is probably a fine choice. If nothing else, it raises fewer questions with the people managing the build infra. And where's the rush? :)

@ofborg build sbcl.packages.iolib

**Comment by 7c6f434c** [comment]
The only drawback is that CI builds on staging are not always informative. You are probably right about branch-off, I don't keep track of that (staging has lower Hydra priority though, so in terms of contention it's still nicer).

But yeah, I guess hitting a 1000 rebuilds and keeping the `master` habits would not be nice, so let's switch now.

**Comment by 7c6f434c** [comment]
StumpWM looks like it dislikes that update, though — although maybe a fresher version would be happier

**Comment by hraban** [comment]
@ofborg build sbclPackages.iolib

**Comment by 7c6f434c** [comment]
@ofborg eval

**Comment by Uthar** [comment]
Regarding StumpWM, It's an opportunity to move it out to a separate package. This way we could re-use upstream's Makefile build system and make a step in the direction of only keeping CL libraries in `${lisp}.pkgs` sets. What do you think of such a change? [[patch]](https://github.com/uthar/nixpkgs/commit/8e0db3b847a685b6b331f5003a43a9710f6e76c3)

`nix-build https://github.com/uthar/nixpkgs/archive/8e0db3b847a685b6b331f5003a43a9710f6e76c3.tar.gz -A stumpwm`

**Comment by 7c6f434c** [comment]
Well, I am interested in StumpWM as library possibly more than in the version with the executable (but moving the executable version outside the set and to Makefile-based build sounds reasonable)

**Comment by hraban** [comment]
I'm running into a problem overriding sbcl locally and I have a feeling it might come from the way we do management of lisp packages:

```
$ nix-build --expr 'let p = import ./. { overlays = [ overlay ]; } ; overlay = self: super: { sbcl = super.sbcl.overrideAttrs { doCheck = false; }; } ; in p.stumpwm'
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
error:
       … while evaluating the attribute 'stumpwm'
         at /Users/user/nobackup/nixpkgs/pkgs/top-level/all-packages.nix:15653:3:
        15652|
        15653|   stumpwm = sbclPackages.stumpwm;
             |   ^
        15654|

       … in the left operand of the update (//) operator
         at /Users/user/nobackup/nixpkgs/lib/attrsets.nix:2075:11:
         2074|     attrs:
         2075|     attrs // { recurseForDerivations = true; };
             |           ^
         2076|

       error: attribute 'pkgs' missing
       at /Users/user/nobackup/nixpkgs/pkgs/top-level/all-packages.nix:11385:35:
        11384|
        11385|   sbclPackages = recurseIntoAttrs sbcl.pkgs;
             |                                   ^
        11386|
       Did you mean args?
```

I don't know about the `sbcl.pkgs` stuff but it looks like it doesn't survive an `.overrideAttrs`? This feels like a pretty standard use case we would want to support, right? @Uthar do you know more about this?

**Comment by Uthar** [comment]
Unfortunately I was not aware or this problem during the lisp modules refactor. It is probably caused by the fact that `wrapLisp` is the one adding `pkgs` - overrideAttrs is a lower level call - because of which, currently it's needed to call `wrapLisp` again when overriding. Nowadays, with `finalAttrs.finalPackage`, maybe we should move that `pkgs` attribute into `sbcl.passthru`? Then `overrideAttrs` would do the right thing. I had some initial patch for that somewhere...

**Comment by Uthar** [comment]
Found the patch... it's for abcl - surely doesn't apply anymore, but at least to communicate the gist of it.

```patch
diff --git a/pkgs/development/compilers/abcl/default.nix b/pkgs/development/compilers/abcl/default.nix
index c681ff47cc8f..ac17149895f5 100644
--- a/pkgs/development/compilers/abcl/default.nix
+++ b/pkgs/development/compilers/abcl/default.nix
@@ -6,6 +6,9 @@
 , jdk
 , makeWrapper
 , stripJavaArchivesHook
+# Lisp-specific options:
+, asdf
+, packageOverrides ? (self: super: {})
 }:
 
 let
@@ -53,7 +56,15 @@ stdenv.mkDerivation (finalAttrs: {
     runHook postInstall
   '';
 
-  passthru.updateScript = ./update.sh;
+  passthru = {
+    updateScript = ./update.sh;
+    pkgs = (commonLispPackagesFor {
+      inherit asdf;
+      pkg = finalAttrs.finalPackage;
+      faslExt = "abcl";
+    }).overrideScope packageOverrides;
+    withPackages = lispWithPackages finalAttrs.finalPackage.pkgs;
+  };
 
   meta = {
     description = "A JVM-based Common Lisp implementation";
diff --git a/pkgs/development/lisp-modules/nix-cl.nix b/pkgs/development/lisp-modules/nix-cl.nix
index 6bec2c3513db..acb405f49a58 100644
--- a/pkgs/development/lisp-modules/nix-cl.nix
+++ b/pkgs/development/lisp-modules/nix-cl.nix
@@ -319,4 +319,7 @@ let
       inherit pkgs withPackages withOverrides buildASDFSystem;
     };
 
-in wrapLisp
+in {
+  inherit wrapLisp commonLispPackagesFor lispWithPackages;
+}
+  
diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
index 9a23cccbcd12..5d6627db05ba 100644
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -25240,9 +25240,10 @@ with pkgs;
   wrapLisp = callPackage ../development/lisp-modules/nix-cl.nix {};
 
   # Armed Bear Common Lisp
-  abcl = wrapLisp {
-    pkg = callPackage ../development/compilers/abcl { };
-    faslExt = "abcl";
+  abcl = callPackage ../development/compilers/abcl {
+    inherit (callPackage ../development/lisp-modules/nix-cl.nix {})
+      commonLispPackagesFor
+      lispWithPackages;
   };
 
   # Clozure Common Lisp

```

**Comment by hraban** [comment]
I've pushed a commit to pin stumpwm to SBCL 2.4.10. Obviously a very temporary a suboptimal solution but I don't know how else to resolve this issue I'm afraid.

**Comment by hraban** [comment]
For the record the build error I'm getting for stumpwm using sbcl 2.4.11:

```
$ nix build -L github:nixos/nixpkgs/42ea6796bf05358aaab4c47444fc1eca758cd504#sbcl_2_4_11.pkgs.stumpwm
...
; wrote /private/tmp/nix-build-sbcl-stumpwm-22.11.drv-0/source/module-tmpYEMMM7SE.fasl
; compilation finished in 0:00:00.005
; compiling file "/nix/store/3cari6d2j9zbmx52p8vg7ay0k2yz86yj-source/ioloop.lisp" (written 01 JAN 1970 12:00:01 AM):

; file: /nix/store/3cari6d2j9zbmx52p8vg7ay0k2yz86yj-source/ioloop.lisp
; in: DEFMETHOD IO-LOOP (SBCL-IO-LOOP)
;     (MULTIPLE-VALUE-CALL #'SB-UNIX:UNIX-FAST-SELECT
;       (1+ STUMPWM::MAXFD)
;       (ADDR STUMPWM::RFDS)
;       (ADDR STUMPWM::WFDS)
;       (ADDR STUMPWM::EFDS)
;       (STUMPWM::COMPUTE-TIMEOUT))
;
; caught WARNING:
;   Derived type of
;   (SB-ALIEN-INTERNALS:%SAP-ALIEN SB-C::VAR
;                                  (QUOTE
;                                   #<ALIEN-TYPE (* (:STRUCT SB-UNIX:FD-SET))>))
;   is
;     SB-SYS:SYSTEM-AREA-POINTER,
;   conflicting with its asserted type
;     (OR
;      (SB-ALIEN:ALIEN
;       (*
;        (SB-ALIEN:STRUCT SB-UNIX:FD-SET
;         (SB-UNIX::FDS-BITS (ARRAY (SB-ALIEN:UNSIGNED 64) 16) :OFFSET 0))))
;      NULL).
;   See also:
;     The SBCL Manual, Node "Handling of Types"
;
; caught WARNING:
;   Derived type of
;   (SB-ALIEN-INTERNALS:%SAP-ALIEN SB-C::VAR
;                                  (QUOTE
;                                   #<ALIEN-TYPE (* (:STRUCT SB-UNIX:FD-SET))>))
;   is
;     SB-SYS:SYSTEM-AREA-POINTER,
;   conflicting with its asserted type
;     (OR
;      (SB-ALIEN:ALIEN
;       (*
;        (SB-ALIEN:STRUCT SB-UNIX:FD-SET
;         (SB-UNIX::FDS-BITS (ARRAY (SB-ALIEN:UNSIGNED 64) 16) :OFFSET 0))))
;      NULL).
;   See also:
;     The SBCL Manual, Node "Handling of Types"
;
; caught WARNING:
;   Derived type of
;   (SB-ALIEN-INTERNALS:%SAP-ALIEN SB-C::VAR
;                                  (QUOTE
;                                   #<ALIEN-TYPE (* (:STRUCT SB-UNIX:FD-SET))>))
;   is
;     SB-SYS:SYSTEM-AREA-POINTER,
;   conflicting with its asserted type
;     (OR
;      (SB-ALIEN:ALIEN
;       (*
;        (SB-ALIEN:STRUCT SB-UNIX:FD-SET
;         (SB-UNIX::FDS-BITS (ARRAY (SB-ALIEN:UNSIGNED 64) 16) :OFFSET 0))))
;      NULL).
;   See also:
;     The SBCL Manual, Node "Handling of Types"


; wrote /private/tmp/nix-build-sbcl-stumpwm-22.11.drv-0/source/ioloop-tmp73HU0RPK.fasl
; compilation finished in 0:00:00.067

debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD tid=259 "main thread" RUNNING {70033E0143}>:
  COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "stumpwm" "ioloop">

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<CL-SOURCE-FILE "stumpwm" "ioloop">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<CL-SOURCE-FILE "stumpwm" "ioloop">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4: [ABORT                        ] Exit debugger, returning to top level.

(UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "stumpwm" "ioloop">)))
   error finding frame source: Bogus form-number: the source file has probably
                               changed too much to cope with.
   source: NIL
0]
;
; compilation unit aborted
;   caught 1 fatal ERROR condition
;   caught 3 WARNING conditions
;   caught 1 STYLE-WARNING condition
;   printed 1 note
* Running phase: installPhase
@nix { "action": "setPhase", "phase": "installPhase" }
cp: cannot stat 'stumpwm': No such file or directory
```

This is on darwin. Obviously counterintuitive to build stumpwm on darwin but I don't have a linux machine on which to try this atm and sbcl 2.4.10 stumpwm does work here so that says at least something, I guess.

**Comment by federkamm** [comment]
Is this still current? stumpwm builds fine with current sbcl on x86_64:

````nix
with import <nixpkgs> {};
stumpwm.override { 
  sbcl = sbcl_2_5_7.withPackages (ps: with ps; [
    alexandria cl-ppcre clx fiasco
  ]);
}
````

should it be unpinned?

**Pull request merged**
