### PR TITLE
gnupg20: drop

### PR DESCRIPTION
**Pull request by ajs124**
###### Motivation for this change
Upstream hasn't been maintaining this version for years. https://gnupg.org/download/index.html

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by danieldk — CHANGES_REQUESTED** [review]
Could you add an entry to `pkgs/top-level/aliases.nix` so that if anyone still has this in their configuration gets a nice error?

**Comment by danieldk** [comment]
The build fails now because the patch is missing.

I can't see the patch to compare. But does https://gitlab.gnome.org/GNOME/libcryptui/-/commit/b05e301d1b264a5d8f07cb96e5edc243d99bff79.patch apply cleanly? If so, you could also `fetchPatch` that patch.

**Comment by ajs124** [comment]
Oops. I should pay more attention when using git.

The patch does not apply cleanly, because the release `configure.ac` only has gnupg 2.0, whereas the patch is against one that also has 2.1. We could also patch the patch or try finding the patch that adds that and apply both, but this option seemed the most straightforward.

**Comment by danieldk** [comment]
Thanks, looks good! One thing I forgot to mention: it would probably add the removal to the list of *Backward Incompatibilities* in the release notes ( `nixos/doc/manual/release-notes/rl-2009.xml` ). Sorry for missing that in the first review!

**Comment by ajs124** [comment]
I would argue that this is not a relevant enough change to warrant documentation in the release notes. This version was only used in one package, because it specifically checked for a version, but supporting anything newer didn't require any actual code changes in that package's source code.

It's also been unsupported upstream for years and the only reason that it wasn't dropped is probably that everyone collectively forgot it existed. IMHO the alias is enough. 

(And yes, I admit it, I also really don't want to write XML.)

**Review by danieldk — APPROVED** [review]
Fair enough! Looks good to me otherwise.

Result of `nixpkgs-review pr 93545` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
<br>- almanah
<br>- libcryptui
</details>

**Pull request merged**
