### PR TITLE
w3m patches

### PR DESCRIPTION
**Pull request by cstrahan**
Fix the built-in help (perl.patch)
  https://bugs.archlinux.org/task/45608

Properly link w3mimgdisplay to x11
  https://bbs.archlinux.org/viewtopic.php?id=196093

Fix rendering bug in w3mimgdisplay (w3m_rgba.patch)
  https://github.com/hut/ranger/issues/86

Don't ignores input tags with invalid types (form_unkown.patch)
  http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=615843

Fix a segfault when using https (https.patch)
  https://bugzilla.redhat.com/show_bug.cgi?id=707994

---

One question remains: should I merge the `NIX_LDFLAGS` into `LIBS`?

### CODE REVIEW

**Comment by cstrahan** [comment]
I removed the `newgc.patch`, as we only have a more recent version of boehm-gc, so I don't think we need that patch any more.

**Comment by vcunat** [comment]
Note: this PR seems to overlap with  #11222.

**Comment by jagajaga** [comment]
cc @oxij

**Comment by oxij** [comment]
I'd like to have at least some of those patches. Will you merge them
with the current w3m expression, or should I?

I think we can actually avoid mass rebuild now by not using those
patches for `w3m-batch`, if we wanted to.

**Comment by vcunat** [comment]
@oxij: I suggest you port and test the patches atop a current state. You seem to use w3m a lot.

**Comment by cstrahan** [comment]
I rebased the changes; merging.

**Pull request merged**
