### PR TITLE
cargo-deny: 0.7.0 -> 0.8.5

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Does not build for me though, tests fail.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
Will take a look at the failing test.

**Comment by Ma27** [comment]
@matthiasbeyer the issue is reproducible with 0.7.1 and 0.7.2 when building the sources in a git checkout where all dependencies are fetched using `cargo vendor`, so the vendoring seems to be the culprit.

For me it'd be fine to skip the test for now as it's an upstream bug, however we should report this problem to the developers.

**Comment by matthiasbeyer** [comment]
Ping. What is needed from me?

**Comment by Ma27** [comment]
Eval error looks unrelated (https://github.com/NixOS/nixpkgs/pull/100071).

@GrahamcOfBorg build cargo-deny

**Comment by matthiasbeyer** [comment]
Another update,... will this land before cargo-deny hits version 1.0?

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 94367` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>cargo-deny</li>
  </ul>
</details>

```
failures:                                                                                                                                                                                                                                                                                                                                                                               ---- cyclic_dependencies_do_not_cause_infinite_loop stdout ----                                                                                                                             thread 'cyclic_dependencies_do_not_cause_infinite_loop' panicked at 'called `Result::unwrap()` on an `Err` value: failed to build crate graph

Caused by:
    0: Error during execution of `cargo metadata`: error: failed to select a version for the requirement `winapi = "=0.3.8"`
       candidate versions found which didn't match: 0.3.9
       location searched: directory source `/private/tmp/nix-build-cargo-deny-0.8.2.drv-0/cargo-deny-0.8.2-vendor.tar.gz` (which is replacing registry `https://github.com/rust-lang/crates.io-index`)
       required by package `ansi_term v0.11.0`
           ... which is depended on by `root v0.1.0 (/private/tmp/nix-build-cargo-deny-0.8.2.drv-0/source/tests/test_data/cyclic_dependencies/root)`
       perhaps a crate was updated and forgotten to be re-vendored?

    1: Error during execution of `cargo metadata`: error: failed to select a version for the requirement `winapi = "=0.3.8"`
       candidate versions found which didn't match: 0.3.9
       location searched: directory source `/private/tmp/nix-build-cargo-deny-0.8.2.drv-0/cargo-deny-0.8.2-vendor.tar.gz` (which is replacing registry `https://github.com/rust-lang/crates.io-index`)
       required by package `ansi_term v0.11.0`
           ... which is depended on by `root v0.1.0 (/private/tmp/nix-build-cargo-deny-0.8.2.drv-0/source/tests/test_data/cyclic_dependencies/root)`
       perhaps a crate was updated and forgotten to be re-vendored?
       ', tests/bans.rs:10:60
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    cyclic_dependencies_do_not_cause_infinite_loop

test result: FAILED. 3 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test bans'
```

**Comment by matthiasbeyer** [comment]
Seems like `cargo metadata` is missing in the environment during the tests...

**Comment by SuperSandro2000** [comment]
> Seems like `cargo metadata` is missing in the environment during the tests...

Can you please add it or disable the test?

**Comment by matthiasbeyer** [comment]
If you tell me how to or even provide me with a patch, that'd be awesome!

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 94367` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>cargo-deny</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 94367` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>cargo-deny</li>
</ul>
</details>

**Pull request merged**
