### PR TITLE
keycloak: 21.1.1 -> 21.1.2

### PR DESCRIPTION
**Pull request by NickCao**
Diff: https://github.com/keycloak/keycloak/compare/None...21.1.2

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by drupol — APPROVED** [review]

**Comment by drupol** [comment]
@NickCao It's not building on Linux, I just noticed.

**Comment by NickCao** [comment]
It builds but is failing test.

**Comment by drupol** [comment]
I guess we don't merge it now then?

**Comment by NickCao** [comment]
I'm unable to reproduce the failure locally, let's try again.
@ofborg test keycloak.mariadb keycloak.mysql keycloak.postgres

**Comment by NickCao** [comment]
It passes, so another flaky test....

**Comment by drupol** [comment]
> It passes, so another flaky test....

Linux tests are still broken here.

**Comment by NickCao** [comment]
> > It passes, so another flaky test....
> 
> Linux tests are still broken here.

Which one? Both [x86_64-linux](https://github.com/NixOS/nixpkgs/pull/240297/checks?check_run_id=14622855164) and  [aarch64-linux](https://github.com/NixOS/nixpkgs/pull/240297/checks?check_run_id=14622821843) looks fine to me.

**Comment by drupol** [comment]
Here https://github.com/NixOS/nixpkgs/pull/240297/checks?check_run_id=14617001272

**Comment by NickCao** [comment]
It's from the previous run.

**Comment by NickCao** [comment]
@ofborg eval

**Comment by NickCao** [comment]
ofborg seems to refuse doing another eval, let me reopen another pr.

**Pull request closed without merging**
