### PR TITLE
libtorrentRasterbar: 1.1.5 -> 1.1.6, switch deluge to libtorrentRasterbar & removed libtorrentRasterbar_1_0

### PR DESCRIPTION
**Pull request by andir**
###### Motivation for this change

The recent `boost` bump started causing issues with `libtorrentRasterbar`. The update to 1.1.6 fixes the issue since upstream now includes support for a more recent `boost` version. 

We can also remove `libtorrentRasterbar_1_0` after switching deluge to `libtorrentRasterbar`.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
  - [X] test using with deluge(d)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by adisbladis** [comment]
qbittorrent was still using `libtorrentRasterbar_1_0`. 
I bumped the version number and changed the libtorrent version.

**Comment by andir** [comment]
Thanks, must have overlooked that and should finally add the pre-commit eval check :/

**Comment by andir** [comment]
I just re-compiled qbittorrent as proposed here. Successfully downloaded an Debian ISO. 👍

**Comment by adisbladis** [comment]
Thanks :) 👍

**Comment by Infinisil** [comment]
Version 1.1.6 makes global bandwidth limits in Deluge not work anymore, see https://forum.deluge-torrent.org/viewtopic.php?p=227823

I'm therefore using an older version of nixpkgs before the boost upgrade to have a deluge with bandwidth limits. I'm hoping upstream fixes this asap, master doesn't currently run either (gives a runtime error). See https://github.com/Infinisil/system/commit/d6a1af07131a9dd5fe3252f5b67f0ced18ba509c

**Comment by andir** [comment]
@infinisil thanks for reporting that. Can you check the upstream project for the correct bug report/fix? We might want to apply a patch until there is a new release.

**Comment by Infinisil** [comment]
@andir There is no bug report for libtorrent, only the one for deluge linked in my commit (https://dev.deluge-torrent.org/ticket/3153), but there's no patch.. :(

**Comment by andir** [comment]
Can you open one? :)

**Comment by Infinisil** [comment]
https://github.com/arvidn/libtorrent/issues/2857

**Pull request merged**
