### PR TITLE
ue4: init at 4.10.2

### PR DESCRIPTION
**Pull request by puffnfresh**
This builds Unreal Engine 4 and has a wrapper to start the editor.

Sadly the application requires write access to a lot of paths. I have a
hack to do a symlink tree under $HOME and it works well, the UE4Editor
binary just needs to be not a symlink.

### CODE REVIEW

**Comment by jb55** [comment]
nice! going to test this now.

**Comment by puffnfresh** [comment]
Realised that I should have probably uploaded a screenshot!

2016-02-19-145440_1010x884_scrot

@jb55 thank you!

**Comment by jb55** [comment]
nice, works :+1:

**Comment by jagajaga** [comment]
wow!

**Comment by globin** [comment]
Wow :speak_no_evil:

**Pull request merged**
