### PR TITLE
texstudio: add qtwayland as dependency

### PR DESCRIPTION
**Pull request by mohe2015**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ajs124** [comment]
why is this needed?

**Comment by mohe2015** [comment]
> why is this needed?

Oh sorry for not explaining.
When setting
```nix
home.sessionVariables = {
      QT_QPA_PLATFORM = "wayland";
};
```
to get native wayland support it otherwise crashes with
```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: offscreen, minimalegl, vkkhrdisplay, linuxfb, vnc, minimal, eglfs, xcb.
Aborted (core dumped)
```
I also verified using xeyes that the env variable is needed to get native wayland support. There also seems to be a bit of previous art in nixpkgs https://github.com/search?q=repo%3ANixOS%2Fnixpkgs%20qtwayland&type=code

**Comment by ajs124** [comment]
Does that mean that every qt app that doesn't explicitly add `qtwayland` as a dependency runs through xwayland?

**Comment by mohe2015** [comment]
> Does that mean that every qt app that doesn't explicitly add `qtwayland` as a dependency runs through xwayland?

From https://wiki.archlinux.org/title/wayland#Qt and https://wiki.qt.io/QtWayland I would conclude that. I assume you want to say we should add it to qt5 itself.

**Comment by ne9z** [comment]
From @ajs124:
> Does that mean that every qt app that doesn't explicitly add qtwayland as a dependency runs through xwayland?

Yes, for QT6 programs. They will not run on Wayland, unless `qtwayland` is explicitly added as `buildInput`.  See https://github.com/NixOS/nixpkgs/issues/219724#issuecomment-1455518086. QT5 programs in Nix have qtwayland bundled due to historical reasons.

Based on this PR, I opened a similar PR at #267427 for adding wayland support to TeXworks.

**Comment by ajs124** [comment]
> QT5 programs in Nix have qtwayland bundled due to historical reasons.

oh. but why not do the same for qt6? where/why was that decision made? so programs without wayland support don't have it unnecessarily?

sounds like someone should go through the qt6 apps in nixpkgs and check if they're actually running with wayland natively then.

**Comment by ne9z** [comment]
I'm an outsider therefore may be misinformed, but it seems that this is
done for QT6 in an attempt to reduce closure size.  (But then the
maintainers have to add them back in package definitions... I'm confused)

**Comment by ajs124** [comment]
There's a typo in the commit message and PR title. texsudio vs texstudio.

**Comment by mohe2015** [comment]
> There's a typo in the commit message and PR title. texsudio vs texstudio.

Fixed.

**Pull request merged**
