### PR TITLE
brotli: 1.0.9 -> 1.1.0

### PR DESCRIPTION
**Pull request by trofi**
Changes: https://github.com/google/brotli/releases/tag/v1.1.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by marsam** [comment]
@GrahamcOfBorg eval

**Review by marsam — APPROVED** [review]

**Comment by mweinelt** [comment]
This update broke `curl` and `python3.pkgs.brotlicffi` on darwin. See https://github.com/NixOS/nixpkgs/pull/254963#issuecomment-1722317697.


Curl builds fine on f4f431907f93528c6010b7269007504d39afa15a, fails on eb1c63ee5e5b535c1e4e08c007be2f818c4122a7.

```
curl-aarch64-darwin> checking run-time libs availability... failed
curl-aarch64-darwin> configure: error: one or more libs available at link-time are not available run-time. Libs used at link-time: -lnghttp2 -lidn2 -lssh2 -lssh2 -lssl -lcrypto -lssl -lcrypto -lgssapi_krb5 -lresolv -lzstd -lzstd -lbrotlidec -lbrotlidec -lz 
```

**Comment by trofi** [comment]
There were two changes in this update:
1. static libraries stopped being installed by default
2. f842c1bcf9264431cd3b15429a72b7dafbe80509 added an rpath on darwin

Worth a try the revert of Darwin first.

**Comment by trofi** [comment]
> f842c1bcf9264431cd3b15429a72b7dafbe80509 added an rpath on darwin

That did it., Proposed the workaround as https://github.com/NixOS/nixpkgs/pull/255630

**Comment by trofi** [comment]
Proposed proper upstream fix in https://github.com/google/brotli/pull/1084 to use correct library path.

**Pull request merged**
