### PR TITLE
neatvnc: 0.6.0 -> 0.7.0, wayvnc: 0.6.2 -> 0.7.1

### PR DESCRIPTION
**Pull request by NickCao**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by PedroHLC** [comment]
Result of `nixpkgs-review pr 259104` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>weston</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>neatvnc</li>
    <li>wayvnc</li>
  </ul>
</details>

**Comment by PedroHLC** [comment]
Weston didn't seem to find neatvnc now, but I checked and wayvnc can read the new config with RSA and relative paths:

```
╰─λ ./results/wayvnc/bin/wayvnc -vL trace --config ~/.secrets/wayvnc.config -o DP-2
Info: Capturing output DP-2
Info: >> Samsung Electric Company LU28R55 HX5R701479 (DP-2) 3840x2160+0x0 Power:ON
DEBUG: ../src/server.c: 1805: Trying address: 10.100.0.2
DEBUG: ../src/server.c: 1825: Successfully bound to address
Info: Listening for connections on 10.100.0.2:5900
DEBUG: ../src/ctl-server.c: 751: Initializing wayvncctl socket: /run/user/1001/wayvncctl
```

**Comment by NickCao** [comment]
Lets

**Comment by NickCao** [comment]
Let's wait for a new weston release.

**Comment by NickCao** [comment]
Result of `nixpkgs-review pr 259104` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>neatvnc</li>
    <li>wayvnc</li>
    <li>weston</li>
    <li>westonLite</li>
  </ul>
</details>

**Review by PedroHLC — APPROVED** [review]

**Comment by wineee** [comment]
@ofborg build westonLite

**Comment by NickCao** [comment]
Tested weston vnc backend with tigervnc.

**Pull request merged**
