### PR TITLE
Add current alpha of protobuf 3

### PR DESCRIPTION
**Pull request by eduarrrd**

### CODE REVIEW

**Comment by edolstra** [comment]
I'm generally not in favor of adding alpha versions of software. Do we need this somewhere?

**Comment by wkennington** [comment]
I believe if you want to use grpc you need protobuf3. This would be a fantastic addition as I've been wanting to write some tools which leverage grpc for rpc.

**Comment by wkennington** [comment]
I should also mention that it turns out bazel needs this version of protobuf if we want to keep that up to date. #9008

**Comment by eduarrrd** [comment]
I'm doing grpc stuff with proto3 which is why I would like to use it.
(Also, arguable Google's "alpha" might be a bit more stable than alpha
might suggest.)

**Comment by edolstra** [comment]
Okay. Can you mark it as `lowPrio` in all-packages.nix?

**Comment by eduarrrd** [comment]
Done.

**Pull request merged**
