### PR TITLE
lua51Packages.rest-nvim: 0.2-1 -> 2.0.1-1

### PR DESCRIPTION
**Pull request by teto**
big update plus changed license to GPL \o/

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by uttarayan21** [comment]
Using this as well as the current nixpkgs-unstable versions of rest-nvim doesn't add the ftdetect and ftplugin it seems.
So even if I open a .http file it doensn't get syntax highlighted unless I manually `set ft=http`  
I was previously using an old commit of rest.nvim with `vimUtils.buildVimPlugin` but that doesn't work anymore.

**Comment by teto** [comment]
the vimPlugins.rest-nvim does a "flat" install of the lua package with some additionnal steps like generating the doc. The nix package doesn't contain the ftdetect directory because it is missing from the release rockspec (but exists in the scm one): https://luarocks.org/modules/NTBBloodbath/rest.nvim/2.0.1-1
I will warn the maintainer

**Comment by wegank** [comment]
Already on master.

**Comment by teto** [comment]
dont you confond with the vim plugin ? I can't find the lua package, which will have the property of propagating its lua dependencies after my next patch

**Comment by wegank** [comment]
I don't think so. That's the current expression of `lua51Packages.rest-nvim` on master:

https://github.com/NixOS/nixpkgs/blob/33ae86a95140f3fdc877b4507955343debe32014/pkgs/development/lua-modules/generated-packages.nix#L3151-L3173

**Comment by uttarayan21** [comment]
The plugin still doesn't work on the master / unstable with the following nvim 
```nix
{
  description = "A very basic flake";
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    nixvim = {
      url = "github:nix-community/nixvim";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    systems.url = "github:nix-systems/x86_64-linux";
    flake-utils.url = "github:numtide/flake-utils";
    flake-utils.inputs.systems.follows = "systems";
  };

  outputs = {
    flake-utils,
    nixpkgs,
    nixvim,
    ...
  }:
    flake-utils.lib.eachDefaultSystem (system: let
      pkgs = import nixpkgs {
        inherit system;
        overlays = [nixvim.overlays.default];
      };
    in {
      packages = rec {
        nvim = pkgs.nixvim.makeNixvim {
          plugins.rest.enable = true;
          # extraPlugins = with pkgs.vimPlugins; [
          #   rest-nvim
          # ];
        };
        default = nvim;
      };
    });
}
```

which gives the following output on `:checkhealth rest-nvim`
```

==============================================================================
rest-nvim: require("rest-nvim.health").check()

- ERROR Failed to run healthcheck for "rest-nvim" plugin. Exception:
  function health#check, line 25
  Vim(eval):E5108: Error executing lua ...yNeovimPackages/start/rest.nvim/lua/rest-nvim/health.lua:37: bad argument #1 to 'pairs' (table expected, got nil)
  stack traceback:
  [C]: in function 'pairs'
  ...yNeovimPackages/start/rest.nvim/lua/rest-nvim/health.lua:37: in function 'install_health'
  ...yNeovimPackages/start/rest.nvim/lua/rest-nvim/health.lua:125: in function 'check'
  [string "luaeval()"]:1: in main chunk

```

**Comment by teto** [comment]
known issue, I will have it fixed (fixed locally) but I am waiting for the next round of staging to make it to master. I'll let you know

**Pull request closed without merging**
