### PR TITLE
nixos/docker: Add module for network

### PR DESCRIPTION
**Pull request by agentx3**
###### Description of changes
This module supports declaratively creating docker networks and supports
all the standard arguments that the CLI tool accepts. It uses systemd to
do this. Networks are also removed upon systemd service stop.

For the test I just ran the docker test.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by geri1701** [comment]
Result of `nixpkgs-review pr 231776` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>

**Comment by agentx3** [comment]
Realized there's some error handling cases I can improve, will update soon

**Comment by agentx3** [comment]
> Result of `nixpkgs-review pr 231776` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
> 2 packages blacklisted:
> 
>     * nixos-install-tools
> 
>     * tests.nixos-functions.nixos-test

@geri1701 Sorry, I'm rather new to all of this. What do these results mean and is there any action needed on my part?

**Comment by tomodachi94** [comment]
> @geri1701 Sorry, I'm rather new to all of this. What do these results mean and is there any action needed on my part?

I'm not the person you pinged, but there is no action needed on your part.

**Pull request closed without merging**
