### PR TITLE
fastfetch: 2.2.0 -> 2.2.1

### PR DESCRIPTION
**Pull request by khaneliman**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by giomf** [comment]
Result of `nixpkgs-review pr 265033` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>fastfetch</li>
  </ul>
</details>


```
error: builder for '/nix/store/zj6xy82c2wh641yrsr2jhn23b6gj6fk6-fastfetch-2.2.1.drv' failed with exit code 2;
       last 10 log lines:
       > make[1]: *** Waiting for unfinished jobs....
       > lto1: some warnings being treated as errors
       > make[3]: *** [/build/ccShElcS.mk:11: /build/cc6X8c9m.ltrans3.ltrans.o] Error 1
       > lto-wrapper: fatal error: make returned 2 exit status
       > compilation terminated.
       > /nix/store/p58l5qmzifl20qmjs3xfpl01f0mqlza2-binutils-2.40/bin/ld: error: lto-wrapper failed
       > collect2: error: ld returned 1 exit status
       > make[2]: *** [CMakeFiles/flashfetch.dir/build.make:425: flashfetch] Error 1
       > make[1]: *** [CMakeFiles/Makefile2:139: CMakeFiles/flashfetch.dir/all] Error 2
       > make: *** [Makefile:156: all] Error 2
       For full logs, run 'nix log /nix/store/zj6xy82c2wh641yrsr2jhn23b6gj6fk6-fastfetch-2.2.1.drv'.
error: 1 dependencies of derivation '/nix/store/ffi4bpc36n9ki3d0sdc6m1skxw6rl75n-review-shell.drv' failed to build
```

**Comment by khaneliman** [comment]
> Result of `nixpkgs-review pr 265033` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
> 1 package failed to build:
> 
>     * fastfetch
> 
> 
> ```
> error: builder for '/nix/store/zj6xy82c2wh641yrsr2jhn23b6gj6fk6-fastfetch-2.2.1.drv' failed with exit code 2;
>        last 10 log lines:
>        > make[1]: *** Waiting for unfinished jobs....
>        > lto1: some warnings being treated as errors
>        > make[3]: *** [/build/ccShElcS.mk:11: /build/cc6X8c9m.ltrans3.ltrans.o] Error 1
>        > lto-wrapper: fatal error: make returned 2 exit status
>        > compilation terminated.
>        > /nix/store/p58l5qmzifl20qmjs3xfpl01f0mqlza2-binutils-2.40/bin/ld: error: lto-wrapper failed
>        > collect2: error: ld returned 1 exit status
>        > make[2]: *** [CMakeFiles/flashfetch.dir/build.make:425: flashfetch] Error 1
>        > make[1]: *** [CMakeFiles/Makefile2:139: CMakeFiles/flashfetch.dir/all] Error 2
>        > make: *** [Makefile:156: all] Error 2
>        For full logs, run 'nix log /nix/store/zj6xy82c2wh641yrsr2jhn23b6gj6fk6-fastfetch-2.2.1.drv'.
> error: 1 dependencies of derivation '/nix/store/ffi4bpc36n9ki3d0sdc6m1skxw6rl75n-review-shell.drv' failed to build
> ```

Welp... so much for just a patch version bump.. lol

**Comment by giomf** [comment]
Do you need the full logs or maybe the concrete error messages?

**Comment by khaneliman** [comment]
> Do you need the full logs or maybe the concrete error messages?

Nah I see the logs now. Just trying to decipher and figure out what needs to change.

**Comment by khaneliman** [comment]
Looks like I get the same build error on the current 2.2.0 version in master...

**Comment by khaneliman** [comment]
Looks like last upgrade also broke darwin. Gonna try fixing that, too...

**Comment by khaneliman** [comment]
image

**Comment by khaneliman** [comment]
Result of `nixpkgs-review pr 265033` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>fastfetch</li>
  </ul>
</details>

**Comment by khaneliman** [comment]
Result of `nixpkgs-review pr 265033` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>fastfetch</li>
  </ul>
</details>

**Review by Gerg-L — APPROVED** [review]
looks good for a squash merge

**Review by dr460nf1r3 — APPROVED** [review]

**Review by giomf — APPROVED** [review]

**Pull request merged**
