### PR TITLE
[Backports] netdata: from 1.36.1 to 1.37.1

### PR DESCRIPTION
**Pull request by HLudmann**
###### Description of changes

Update of Netdata agent from 1.36.1 to 1.37.1 because of security and crash patches:

- 2 security patches in 1.37.0: https://github.com/netdata/netdata/releases/tag/v1.37.0
- crash patches in 1.37.1: https://github.com/netdata/netdata/releases/tag/v1.37.1

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by winterqt** [comment]
Please see the discussion in #207270, this PR is not acceptable as-is.

(cc @RaitoBezarius, looks like nobody ended up backporting the patch to 22.11 😕)

**Comment by RaitoBezarius** [comment]
Yes, actually, this PR was sparked by me saying we really need to backport it now.

**Comment by RaitoBezarius** [comment]
But we still need to isolate the *patches*.

**Comment by winterqt** [comment]
Yes, that's what I meant by "backporting the patch" :)

**Comment by RaitoBezarius** [comment]
> Yes, that's what I meant by "backporting the patch" :)

Yes, this was for OP :).

**Comment by HLudmann** [comment]
with only the security patches: https://github.com/NixOS/nixpkgs/pull/230758

**Pull request closed without merging**
