### PR TITLE
wlroots: 0.13.0 -> 0.14.0

### PR DESCRIPTION
**Pull request by primeos**
###### Motivation for this change

https://github.com/swaywm/wlroots/releases/tag/0.14.0

###### Current status:

<details>
<summary>nixpkgs-review output</summary>

```
1 package added:
wlroots_0_13 (init at 0.13.0)

17 packages updated:
cage cagebreak dwl fuzzel labwc-unstable qt-video-wlr river-unstable waybar waybox-unstable wayfireApplications-unwrapped.wayfire (0.7.1 → 0.7.2) wayfire (0.7.1-wrapped → 0.7.2-wrapped) wbg-unstable wcm wcm wf-sh
ell wio wlroots (0.13.0 → 0.14.0)

$ nix --experimental-features nix-command build --no-link --keep-going --option build-use-sandbox relaxed -f /home/michael/.cache/nixpkgs-review/rev-258dafee0ce2912f5c0351fae5f24feb2fdbfc58/build.nix
18 packages built:
cage cagebreak dwl fuzzel labwc qt-video-wlr river waybar waybox wayfire wayfireApplications-unwrapped.wayfire wayfireApplications-unwrapped.wayfirePlugins.wf-shell wayfireApplications-unwrapped.wcm wbg wcm wio wlroots wlroots_0_13
```
</details>

Builds:
- [x] dwl
- [x] fuzzel
- [x] qt-video-wlr river
- [x] waybox
- [x] wbg
- [x] wlroots
- [x] cage (`https://github.com/Hjdskes/cage/pull/191`)
  - [-] wio (unmaintained, we'll have to switch to a fork)
- [x] cagebreak (https://github.com/project-repo/cagebreak/commit/d57869d43add58331386fc8e89c14bb2b74afe17)
- [-] hikari (nothing yet)
- [x] labwc (`https://github.com/johanmalm/labwc/pull/35`)
- [-] sway-unwrapped sway sway-contrib.grimshot (progress: `https://github.com/swaywm/sway/pull/6339` and `https://github.com/swaywm/sway/pull/6340`)
  - [x] waybar
- [x] wayfire wayfireApplications-unwrapped.wayfire wayfireApplications-unwrapped.wayfirePlugins.wf-shell wayfireApplications-unwrapped.wcm wcm (at least https://github.com/WayfireWM/wayfire/commit/1a65ae3115f3f8fb715a6b25ea96a5be155c4ab6, https://github.com/WayfireWM/wayfire/commit/48275e46b4705a1f9b827d94d7a61921ada2ea51, and https://github.com/WayfireWM/wayfire/commit/1f56528484350dc15196e7bde10266a1a97d4c4a should be required)

Tested:
- nixosTests.cage
- nixosTests.cagebreak
- nixosTests.sway
- Manual tests

###### TODOs

- [x] Wait for updates of reverse-dependencies (to make them build with wlroots 0.14)
  - [x] But we'll likely have to introduce `wlroots_0_13`
  - [ ] ~~Ask upstream if wlroots 0.13.1 is still planned: https://github.com/swaywm/wlroots/milestone/7~~
- [x] nixpkgs-review
- [x] Squash the commits

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Synthetica9** [comment]
Beat me to it!

Tested the following:

- [ ] nixosTests.sway
- [ ] nixosTests.cage
- [ ] nixosTests.cagebreak

**Comment by primeos** [comment]
@Synthetica9 oops :o :D Usually I'm not that fast but this time the timing of the release was very convenient and I noticed the notification within a few minutes.

Anyway, regarding your testing, are you sure you're testing with wlroots 0.14.0? Sway shouldn't build with it without additional modifications (should be part of Sway 1.6.1, which should be released soon).

**Comment by Synthetica9** [comment]
> Anyway, regarding your testing, are you sure you're testing with wlroots 0.14.0? Sway shouldn't build with it without additional modifications (should be part of Sway 1.6.1, which should be released soon).

Yeah, just noticed I hadn't checked out the branch, only fetched it 🤦🏻‍♀

**Comment by primeos** [comment]
@Synthetica9 happens :) I've started tracking the current status in the PR description. I'd aim to merge this once Sway 1.6.1 is out (or maybe a bit later if other releases/merges are imminent) and we might have to introduce `wlroots/0.13.nix` for some time.

@AndersonTorres I've just tested the `wio` build and it currently fails with:
```
[10/15] Compiling C object wio.p/main.c.otable-v1-protocol.h'.ated_wlr-layer-shell-unstable-v1-protocol.c.o
FAILED: wio.p/main.c.o
gcc -Iwio.p -I. -I.. -I../include -I/nix/store/60ncgyr2anh1r1h7c7i7p1hz3p56sg0w-cairo-1.16.0-dev/include/cairo -I/nix/store/fqfp27bm34jsis1bbdxfcl2ca9k7crwi-freetype-2.10.4-dev/include/freetype2 -I/nix/store/fqfp27bm34jsis1bbdxfcl2ca9k7crwi-freetype-2.10.4-dev/include -I/nix/store/36csrjsw98msm2av0za03gnf768hyng4-libdrm-2.4.106-dev/include -I/nix/store/36csrjsw98msm2av0za03gnf768hyng4-libdrm-2.4.106-dev/include/libdrm -I/nix/store/fmqjy32hds1gkanz9ljdybl9wkh9h3l6-wayland-1.19.0-dev/include -I/nix/store/dz6xfswjlybx9n7780zl7slgk7847m8l-wlroots-0.14.0/include -I/nix/store/d8p788lxsqp3kl10d86i9yhrcirk03dy-libxkbcommon-1.3.0-dev/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c11 -DWL_HIDE_DEPRECATED -DWLR_USE_UNSTABLE -Wno-unused-parameter -Wno-unused-result -Wundef -MD -MQ wio.p/main.c.o -MF wio.p/main.c.o.d -o wio.p/main.c.o -c ../main.c
../main.c:18:10: fatal error: wlr/types/wlr_gtk_primary_selection.h: No such file or directory
   18 | #include <wlr/types/wlr_gtk_primary_selection.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Could you handle that and switch the package source over to your fork?

**Comment by alyssais** [comment]
Taken care of Wayfire. :)

**Comment by primeos** [comment]
I've extracted the Sway update into a dedicated PR as that caused issues with the test (WIP): #128036 

The rest should be good to go now.
I'll run a few manual tests and merge it then.

**Pull request merged**
