### PR TITLE
collision: 3.6.0 -> 3.8.0

### PR DESCRIPTION
**Pull request by sund3RRR**
## Description of changes
Update version and install `nautilus-python` extension.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by viraptor — APPROVED** [review]

**Review by viraptor — CHANGES_REQUESTED** [review]
See the failures on aarch64: https://github.com/NixOS/nixpkgs/pull/282286/checks?check_run_id=20684676737
The blake lib seems to be missing.
(Previous approval accidental :( )

**Comment by sund3RRR** [comment]
> See the failures on aarch64: https://github.com/NixOS/nixpkgs/pull/282286/checks?check_run_id=20684676737 The blake lib seems to be missing. (Previous approval accidental :( )

This is a really strange issue, I don't know how this successfully builds and works on `x86_64` and fails on `aarch64`.
I can't compile it on my aarch64 machine because there doesn't seem to be a `libblake3` in nixpkgs.

**Comment by sund3RRR** [comment]
Ok, I figured out why it doesn't work on aarch64. Crystal's `blake3` dependency builds a static library `libblake3.a`, but default `Makefile` target builds libarary for `x86_64` regardless of the machine architecture. So, `libblake3.a` on my `aarch64` machine contains these files:
```bash
ar -t /nix/store/kh4kh9qczdw0lpmrm9pjg499bqh6iq5p-blake3.cr/blake3c/libblake3.a
blake3.o
blake3_dispatch.o
blake3_portable.o
blake3_sse2.o
blake3_sse41.o
blake3_avx2.o
blake3_avx512.o
blake3_sse2_x86-64_unix.S
blake3_sse41_x86-64_unix.S
blake3_avx2_x86-64_unix.S
blake3_avx512_x86-64_unix.S
```
There is a `Makefile` target for `aarch64`:
```Makefile
blake3_neon.o: blake3_neon.c
	$(CC) $(CFLAGS) $(EXTRAFLAGS) -c $^ -o $@
```
But I don't know, how to redefine this target. I can manually replace `blake3.cr` dependency for `aarch64` with the correct build in the `collision` derivation.

**Comment by GeopJr** [comment]
FWIW, the flatpak solution was to just pass env vars so it builds the neon target only on aarch64 https://github.com/flathub/dev.geopjr.Collision/blob/master/dev.geopjr.Collision.yaml#L43-L47

**Comment by sund3RRR** [comment]
> FWIW, the flatpak solution was to just pass env vars so it builds the neon target only on aarch64 https://github.com/flathub/dev.geopjr.Collision/blob/master/dev.geopjr.Collision.yaml#L43-L47

Hi, GeopJr. Thank you for your help. Unfortunately, `crystal2nix`, which is used for collecting `collision` dependencies doesn't run post_install targets in `shard.yaml` from `blake3.cr`. This is because in nix all packages are isolated from each other and in order to execute custom package build scripts, you will have to create an additional build environment in which `gcc` would be.
In other words, whatever I write in the blake3.cr's `Makefile`, it won't run. It works on `x86_64` because your repository contains prebuild [libblake3.a](https://github.com/GeopJr/blake3.cr/blob/main/blake3c/libblake3.a).
The only solution I found is to write a custom build script and package `blake3.cr` together with `collision`.
Something like this:
```bash
    if [ "$ARCH" == "x86_64" ]; then
        make -f ../build/Makefile
    elif [ "$ARCH" == "aarch64" ]; then
        BLAKE3_USE_NEON=1 make -f ../build/Makefile blake3_neon.o
    else
        echo "Unsupported architecture: $ARCH"
        cd ..
        exit 1
    fi
```

**Comment by sund3RRR** [comment]
It works now, thanks to @GeopJr for advice with the environment variables.

**Comment by sund3RRR** [comment]
@ofborg eval

**Comment by GeopJr** [comment]
> Unfortunately, crystal2nix, which is used for collecting collision dependencies doesn't run post_install targets in shard.yaml from blake3.cr.

> In other words, whatever I write in the blake3.cr's Makefile, it won't run. It works on x86_64 because your repository contains prebuild [libblake3.a](https://github.com/GeopJr/blake3.cr/blob/main/blake3c/libblake3.a).

Nice catch thanks!

I don't like that it relies on a postinstall script either :/
I do have an idea, maybe I could check with crystal macros if blake3c is available and only compile it if it isn't without relying on postinstall. I'll need some time to test it properly (if it's can be done at all), if possible please postpone this update until 3.7.1! Sorry for the inconvenience :bow:

**Comment by GeopJr** [comment]
Released 3.7.1, it should now have fixed the issues! Please make blake.cr a regular shard again. At compile time it only requires a C compiler to be available for blake3c. It should also build the correct target for aarch64

**Comment by sund3RRR** [comment]
I spent so much time building, but nothing worked. `blake3-cr` cannot run on `nix` as a `shard` due to the read-only filesystem, so `blake3c` will not compile due to a write permission error. I placed this package as a regular dependency without a symlink, but for some reason Crystal on Nix can't build the original C library, I spent two days trying to figure out why, but to no avail. So I still build `blake3-cr` in another derivation, I don't see any other way out

**Comment by GeopJr** [comment]
I can't setup a nix environment at the moment so I'll try to describe the build steps if it helps at all, otherwise do what you believe it's best!

When the crystal compiler builds collision, in the preprocessing phase, it will check if `lib/blake3/blake3c/libblake3.a` exists. If it doesn't it will run the `compile_blake3.cr` script that will prepare the right commands to build blake3c for the current arch and execute them.

From my understanding based on your last comment, the problem is here, `lib/blake3/` is read-only. Not sure why that is as I'm sure other shards in other crystal problems *might* also need to modify their files with macros but :shrug: 

Some other stuff might worth looking into:
- `crystal/build-package.nix` includes some additional options, not sure if it's possible to make it run `crystal run blake3/src/compile_blake3.cr` (or whatever its path is there) so it builds blake3c in advance
- If in the future you find a better way to provide libblake3.a you can skip blake3.cr building it by setting `BLAKE3_CR_DO_NOT_BUILD=1`

No idea if anything else can be done from my side and don't really want to waste more of your time with more patch releases so I'd say go ahead and package it however you see fit and when I setup nix again I'll revisit it! Thanks again!

**Comment by sund3RRR** [comment]
> I can't setup a nix environment at the moment so I'll try to describe the build steps if it helps at all, otherwise do what you believe it's best!
>
Thank you for your help, GeopJr! It's 100% a nix problem. This is not feedback about your update, but simply a report on the work done.

>From my understanding based on your last comment, the problem is here, lib/blake3/ is read-only. Not sure why that is as I'm sure other shards in other crystal programs might also need to modify their files with macros but 🤷
>
I think it's all `crystal2nix` fault. It installs collision dependencies in /nix/store and creates symlinks to these folders. This means that during the build phase we do not have permissions to change dependencies folders. Macros and `post_build` in `shards` will not work.

>Some other stuff might worth looking into:
crystal/build-package.nix includes some additional options, not sure if it's possible to make it run crystal run blake3/src/compile_blake3.cr (or whatever its path is there) so it builds blake3c in advance
If in the future you find a better way to provide libblake3.a you can skip blake3.cr building it by setting BLAKE3_CR_DO_NOT_BUILD=1
>
The main problem is that I can build `blake3-cr` in other derivation, but when I run the `collision` build, it can’t build `blake3c`. I think that nix set some cflags/ldflags/etc, which prevent successful compilation and `libblake3.a` does not appear.
I set up a test environment on ubuntu and it worked, you did a good job, the problem is not related to the package itself.

**Comment by GeopJr** [comment]
> I think that nix set some cflags/ldflags/etc, which prevent successful compilation and libblake3.a does not appear.

The script does respect them https://github.com/GeopJr/blake3.cr/blob/main/src/compile_blake3.cr#L22-L23 maybe it shouldn't? if nix allows you to, you could try to unset them or set them to the ones from the script

**Comment by sund3RRR** [comment]
In general, I figured it out. All the problems were due to symlinks. For some reason, crystal did not run the `libblake3.a` build at all. When I manually copied the entire shard, the library still did not build, it turned out that all file permissions also applied when copying and crystal simply did not have the rights to write at least something to the `lib/blake3.cr` folder, since all files remained `read-only`. I did a [PR](https://github.com/NixOS/nixpkgs/pull/289266) with changes to `buildCrystalPackage`, so now adding just one `copyShardsDeps` flag solves all problems with both `gi-crystal` and `blake3.cr` since the building environment  in `nix` will now be practically the same as ubuntu's env. Thanks to `GeopJr` for the advice and for the help with the packaging!

I will make changes to the current PR as soon as crystal's PR is merged.

**Comment by will** [comment]
Result of `nixpkgs-review pr 282286` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>collision</li>
  </ul>
</details>

**Comment by sund3RRR** [comment]
Damn, I broke the branch I think. How to fix it?

**Comment by sund3RRR** [comment]
Okay, that's fixed now.
Collision updated to 3.7.1. Unfortunately, I can't upgrade to 3.8.0 version. due to `Adw::AboutDialog`, which was added in libadwaita 1.5, but the current version in nixpkgs is 1.4.4.
Added nautilus extension so you can install `gnome.nautilus-python` system-wide and `Check hashes` will appear automatically.

**Comment by sund3RRR** [comment]
@viraptor

**Review by viraptor — APPROVED** [review]
I'm not near a machine that can test it, but it looks good 👍

**Comment by sund3RRR** [comment]
@viraptor could you please review the changes related to the new collision version? Collision still broken in nixpkgs, so we want to fix it before 24.05 released.

**Pull request closed without merging**
