### PR TITLE
ctranslate2: add withOneDNN, withOpenblas, withRuy

### PR DESCRIPTION
**Pull request by misuzu**
###### Description of changes
Update oneDNN to 3.1.1 and add oneDNN_2 package for compatibility with migraphx and onnxruntime.

Disable withOneDNN by default until the https://github.com/OpenNMT/CTranslate2/issues/1294 is fixed.

Required for https://github.com/NixOS/nixpkgs/pull/228563

Closes: https://github.com/NixOS/nixpkgs/pull/201938

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Thanks, I hope I didn't step on your toes. Feel free to co-maintain ctranslate2 if you want to.

Build tested on aarch64-linux, aarch64-darwin, x86_64-linux.

**Comment by misuzu** [comment]
Result of `nixpkgs-review pr 237788` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>23 packages built:</summary>
  <ul>
    <li>ctranslate2</li>
    <li>oneDNN</li>
    <li>oneDNN.dev</li>
    <li>oneDNN.doc</li>
    <li>oneDNN_2</li>
    <li>oneDNN_2.dev</li>
    <li>oneDNN_2.doc</li>
    <li>piper-train (python310Packages.piper-train)</li>
    <li>piper-train.dist (python310Packages.piper-train.dist)</li>
    <li>python310Packages.ctranslate2</li>
    <li>python310Packages.ctranslate2.dist</li>
    <li>python310Packages.faster-whisper</li>
    <li>python310Packages.faster-whisper.dist</li>
    <li>python310Packages.invisible-watermark</li>
    <li>python310Packages.invisible-watermark.dist</li>
    <li>python310Packages.mmcv</li>
    <li>python310Packages.mmcv.dist</li>
    <li>python310Packages.onnxruntime</li>
    <li>python310Packages.onnxruntime.dist</li>
    <li>python311Packages.onnxruntime</li>
    <li>python311Packages.onnxruntime.dist</li>
    <li>wyoming-faster-whisper</li>
    <li>wyoming-faster-whisper.dist</li>
  </ul>
</details>

Result of `nixpkgs-review pr 237788` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>ctranslate2</li>
    <li>oneDNN</li>
    <li>oneDNN.dev</li>
    <li>oneDNN.doc</li>
    <li>oneDNN_2</li>
    <li>oneDNN_2.dev</li>
    <li>oneDNN_2.doc</li>
    <li>python310Packages.ctranslate2</li>
    <li>python310Packages.ctranslate2.dist</li>
    <li>wyoming-faster-whisper</li>
    <li>wyoming-faster-whisper.dist</li>
  </ul>
</details>

**Comment by misuzu** [comment]
Had to disable openblas support to fix segfaults in libretranslate...

**Comment by mweinelt** [comment]
Ideally, you'd create an `withOpenblas` argument on ctranslate2 instead of ripping it out like that. It works great with faster-whisper fwiw.

**Comment by misuzu** [comment]
Added `withOpenblas`

**Comment by mweinelt** [comment]
How does ctranslate2 choose the preferred backend? At the moment I think enabling all free ones is the best approach for the default package. If libretranslate breaks, then it should disable the backend that breaks it, no?

**Comment by misuzu** [comment]
> If libretranslate breaks, then it should disable the backend that breaks it, no?

Works for me

**Comment by mweinelt** [comment]
Seems to break wyoming-faster-whisper.

```pytb
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-8' coro=<AsyncEventHandler.run() done, defined at /nix/store/w2zfwrs2b7yam7v33w35dw5nq69qj1rw-python3.10-wyoming-0.0.1/lib/python3.10/site-packages/wyoming/server.py:26> exception=RuntimeError('could not create a primitive')>
Traceback (most recent call last):
  File "/nix/store/w2zfwrs2b7yam7v33w35dw5nq69qj1rw-python3.10-wyoming-0.0.1/lib/python3.10/site-packages/wyoming/server.py", line 32, in run
    if not (await self.handle_event(event)):
  File "/nix/store/rhnfi362r2rib18mhh8czmwryzn2b611-wyoming-faster-whisper-0.0.3/lib/python3.10/site-packages/wyoming_faster_whisper/handler.py", line 67, in handle_event
    text = " ".join(segment.text for segment in segments)
  File "/nix/store/rhnfi362r2rib18mhh8czmwryzn2b611-wyoming-faster-whisper-0.0.3/lib/python3.10/site-packages/wyoming_faster_whisper/handler.py", line 67, in <genexpr>
    text = " ".join(segment.text for segment in segments)
  File "/nix/store/rhnfi362r2rib18mhh8czmwryzn2b611-wyoming-faster-whisper-0.0.3/lib/python3.10/site-packages/wyoming_faster_whisper/faster_whisper/transcribe.py", line 162, in generate_segments

    for start, end, tokens in tokenized_segments:
  File "/nix/store/rhnfi362r2rib18mhh8czmwryzn2b611-wyoming-faster-whisper-0.0.3/lib/python3.10/site-packages/wyoming_faster_whisper/faster_whisper/transcribe.py", line 186, in generate_tokenized_segments
    result, temperature = self.generate_with_fallback(segment, prompt, options)
  File "/nix/store/rhnfi362r2rib18mhh8czmwryzn2b611-wyoming-faster-whisper-0.0.3/lib/python3.10/site-packages/wyoming_faster_whisper/faster_whisper/transcribe.py", line 279, in generate_with_fallback
    result = self.model.generate(
RuntimeError: could not create a primitive

**Comment by misuzu** [comment]
> Seems to break wyoming-faster-whisper. Maybe we need `withOneDNN` now as well.

Added `withOneDNN`, disabled by default

**Comment by misuzu** [comment]
@mweinelt please check if it works for you now

**Comment by mweinelt** [comment]
No, still the same error. Seems like faster-whisper wants openblas.

Also, not sure why you moved openmp to darwin only, and exposed `withRuy`, when we don't even have ruy packaged up.

**Comment by mweinelt** [comment]
> Is there an easy way to test it?

I'm testing it from within home-assistant's voice assistant pipeline, so probably, but I don't know how.

**Comment by misuzu** [comment]
I guess we will have to have two versions of ctranslate2, one with oneDNN and one with OpenBLAS

**Comment by misuzu** [comment]
Thanks, @mweinelt!

**Pull request merged**
