### PR TITLE
Update VapourSynth

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Motivation for this change
Usual version bump

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change
- [x] Tested execution of all binary files
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by nlewo** [comment]
@GrahamcOfBorg build vapoursynth

**Comment by nlewo** [comment]
Could you please set the platform attribute to `platforms = [ "x86_64-linux" ];`?

**Comment by rnhmjoj** [comment]
darwin and windows should also be supported, so maybe `platforms.x86_64`.

**Comment by nlewo** [comment]
@rnhmjoj yes, we can try this!

@GrahamcOfBorg build vapoursynth

**Comment by rnhmjoj** [comment]
@LnL7 fixed the package some time ago to build on darwin. I suppose it still works.

**Comment by nlewo** [comment]
Ok. Thanks.

**Pull request merged**
