### PR TITLE
source-serif-pro: 1.017 -> 2.010, sync w/source-sans-pro expression

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

Now installs font in various formats, not only OTF,
since that's what we do with source-sans-pro.

If this needs to be changed, we should fix that as well.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by worldofpeace** [comment]
> Now installs font in various formats, not only OTF,
since that's what we do with source-sans-pro.

> If this needs to be changed, we should fix that as well.

I think this is fine :+1:

**Comment by worldofpeace** [comment]
I think we should also change the homepage for these expression to like https://adobe-fonts.github.io/source-serif-pro/

**Review by worldofpeace — APPROVED** [review]
Should be good :+1: 

As long as this isn't already out of date that is :smile:

**Comment by dtzWill** [comment]
Doesn't seem to be! Quick, better merge before it becomes outdated! :P

**Pull request merged**
