### PR TITLE
kubeval: 0.7.3 -> 0.14.0

### PR DESCRIPTION
**Pull request by groodt**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @nicknovitski

### CODE REVIEW

**Comment by filalex77** [comment]
Testing build on darwin
@GrahamcOfBorg build kubeval

**Comment by groodt** [comment]
@filalex77 I don't suppose you're able to look into this one too? https://github.com/NixOS/nixpkgs/pull/73093

It's been sitting for a while...

**Comment by filalex77** [comment]
Sorry @groodt, but I also don't have merge rights yet :(

I'll ping some maintainers I know to see if we can resolve this and #73093 faster. To said maintainers: sorry if that's not the way to do it.

cc @jonringer @worldofpeace @marsam @Ma27

**Review by Br1ght0ne — APPROVED** [review]
Works for me on NixOS unstable. (checked with `nix-review`)

**Comment by marsam** [comment]
Thank you @groodt, please feel free to ping me if a PR gets stuck

**Pull request merged**
