### PR TITLE
musl: 1.2.2 -> 1.2.3

### PR DESCRIPTION
**Pull request by dtzWill**
###### Description of changes

https://www.openwall.com/lists/musl/2022/04/07/1

cc @NixOS/static

Previous upgrade: #117375

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dtzWill** [comment]
cc @TredwellGit @thoughtpolice from mentions on previous updates, in case interested.

**Comment by dtzWill** [comment]
https://git.musl-libc.org/cgit/musl/tree/WHATSNEW?h=v1.2.3#n2293 for changes.

Notably adds some functions that are sometimes needed to be patched around previously: qsort_r, and to a lesser extent, pthread_getname_np.

On phone so not sure trust the results, but searching tree for mentions/patches for these only turns up some Darwin issues?

Anyway not sure the testing plan?
I know folks care about static builds in general and specifically Haskell.  I used to throw this at my hydra+builders for these upgrades but don't have that infra presently and not sure warrants such a use of our NixOS builders re:hydra job there.  Is very useful to see fallout before/after building all the things, and testing pkgsMusl as well as pkgsStatic.

@ofborg build pkgsMusl.gdb pkgsMusl.valgrind

**Review by alyssais — APPROVED** [review]
I've tested a full rebuild of [Spectrum](https://spectrum-os.org) (where we use pkgsMusl and pkgsStatic extensively), and everything looks fine.  I'll merge soon unless anybody finds some objections/issues.

**Comment by Artturin** [comment]
aarch64-linux build failed on ofborg https://logs.nix.ci/?key=nixos/nixpkgs.168207&attempt_id=6e85695e-ba6d-452f-b741-5947598267a1

**Comment by sternenseemann** [comment]
Haskell in `pkgsMusl` and `pkgsStatic` seems to work as expected on x86_64-linux at least.

**Comment by rnhmjoj** [comment]
> Haskell in pkgsMusl and pkgsStatic seems to work as expected on x86_64-linux at least.

Can confirm: I built a bunch of complex Haskell programs using `pkgsStatic`.

**Comment by alyssais** [comment]
> aarch64-linux build failed on ofborg https://logs.nix.ci/?key=nixos/nixpkgs.168207&attempt_id=6e85695e-ba6d-452f-b741-5947598267a1

This seems to be unrelated to this patch — I can reproduce it on the parent commit.

**Comment by alyssais** [comment]
That particular failure was introduced in https://github.com/NixOS/nixpkgs/pull/149482.  But pkgsMusl.stdenv hasn't worked at all on aarch64-linux since https://github.com/NixOS/nixpkgs/pull/57339.

**Comment by dtzWill** [comment]
Thanks all! :+1:

**Pull request merged**
