### PR TITLE
wlroots_0_16: 0.16.1 -> 0.16.2

### PR DESCRIPTION
**Pull request by alyssais**
###### Description of changes

Tested that sway builds and runs.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by hesiod** [comment]
Result of `nixpkgs-review pr 215745` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>river</li>
    <li>rivercarro</li>
  </ul>
</details>
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>dwl</li>
    <li>labwc</li>
    <li>nwg-panel</li>
    <li>sway</li>
    <li>sway-contrib.grimshot</li>
    <li>sway-unwrapped</li>
    <li>waybar</li>
    <li>wlprop</li>
    <li>wlroots_0_16</li>
  </ul>
</details>

**Comment by hesiod** [comment]
Note: There are parallel PRs for river (#215709) and rivercarro (#215719).

The build failures of river and rivercarro seem to be new compared to #212110. They are due to river crashing with SIGLL (same error as in https://github.com/NixOS/nixpkgs/pull/215709#issuecomment-1426242222:
```
river> unpacking sources
river> unpacking source archive /nix/store/5qlxxp9vmfi64bwc3xbk57mzg90yzwy2-source
river> source root is source
river> patching sources
river> building
river> no Makefile or custom buildPhase, doing nothing
river> installing
river> /nix/store/3yfs41f4b60jya2gk6xikx4s97zsxjr0-stdenv-linux/setup: line 1574:    20 Illegal instruction     (core dumped) zig build -Drelease-safe -Dcpu=baseline -Dxwayland -Dman-pages --prefix $out install
```
But overall the failure seems to be unrelated to the wlroots bump, but more of a host CPU issue in the zig compiler.

**Review by hesiod — APPROVED** [review]

**Comment by alyssais** [comment]
@OfBorg build river

**Comment by trofi** [comment]
Result of `nixpkgs-review pr 215745` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>dwl</li>
    <li>labwc</li>
    <li>nwg-panel</li>
    <li>river</li>
    <li>rivercarro</li>
    <li>sway</li>
    <li>sway-contrib.grimshot</li>
    <li>sway-unwrapped</li>
    <li>waybar</li>
    <li>wlprop</li>
    <li>wlroots_0_16</li>
  </ul>
</details>

**Review by trofi — APPROVED** [review]

**Review by ocfox — APPROVED** [review]

**Pull request merged**
