### PR TITLE
signal-desktop: remove stdenv.cc.cc from runtimeDeps

### PR DESCRIPTION
**Pull request by Atemu**
The signal desktop app does not require a C compiler to function.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by drupol — APPROVED** [review]

**Comment by emilazy** [comment]
This is probably working as `lib.getLib stdenv.cc.cc`, which does contain libraries that many binary packages need at runtime? (Just a guess.)

**Comment by Atemu** [comment]
Not sure but it works without this just fine.

**Comment by teutat3s** [comment]
We need to make sure that this change does not break screensharing or audio / video on wayland. I remember issues regarding those the last time this was touched.

**Comment by Atemu** [comment]
Screen share works for me on Hyprland.

I really can't see how that could ever depend on a C compiler. Remember, we're talking about the compiler here, not its lib. The compiler lib is still in the RUNPATH beofre and after if you take a look at `objdump -x`.

**Comment by teutat3s** [comment]
Thank you for checking. As long as the gcc lib is in `rpath`, `signal-desktop` should be happy.

**Review by teutat3s — APPROVED** [review]

**Comment by Atemu** [comment]
Thanks!

Though I don't think we should backport, it's just a super minor fix. People will get this in <1 month when they update to 24.11. I don't see how but if this does *somehow* break, we wouldn't want that to happen on stable ;)

**Pull request merged**
