### PR TITLE
perlPackages.JSON: 2.90 -> 2.97001

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

update to match ```JSON::PP``` version

### CODE REVIEW

**Comment by volth** [comment]
@GrahamcOfBorg build perlPackages.JSON

**Comment by ElvishJerricco** [comment]
This version fails to cross compile due to some compile time eval, it seems. I don't think we should hold back on old versions of packages just because of cross compilation, especially not with perl, but this does mean NixOS can't be cross compiled.

**Comment by volth** [comment]
@ElvishJerricco Any little testcase to reproduce? (I suspect it might just fail the tests and ```doCheck = some-condition``` would help)

**Comment by ElvishJerricco** [comment]
The issue is that `eval` requires some kind of dynamic linking, which the cross compiling perl doesn't support.

```nix
let
  src = builtins.fetchTarball https://github.com/NixOS/nixpkgs/archive/master.tar.gz;
  pkgs = import src {
    crossSystem = (import ("${src}/lib")).systems.examples.aarch64-multiplatform;
  };
in pkgs.perlPackages.JSON
```

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/hylqw5v5fy5l5avhhaxf806mmm4nmajg-JSON-2.97001.tar.gz-aarch64-unknown-linux-gnu
source root is JSON-2.97001
setting SOURCE_DATE_EPOCH to timestamp 1513854859 of file JSON-2.97001/MANIFEST
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
Loading lib/JSON.pm failed. No B module?
perl says : Can't load module B, dynamic loading not available in this perl.
  (You may need to build a new perl executable which either supports
  dynamic loading or has the B module statically linked into it.)
 at /nix/store/2kbg8imhilg82zd4ybk2x67zc55fpr2z-perl-5.24.3-aarch64-unknown-linux-gnu/lib/perl5/5.24.3/aarch64-linux/B.pm line 28.
BEGIN failed--compilation aborted at /nix/store/2kbg8imhilg82zd4ybk2x67zc55fpr2z-perl-5.24.3-aarch64-unknown-linux-gnu/lib/perl5/5.24.3/aarch64-linux/B.pm line 28.
Compilation failed in require at lib/JSON/backportPP.pm line 1364.
BEGIN failed--compilation aborted at lib/JSON/backportPP.pm line 1404.
Compilation failed in require at (eval 8) line 1.
BEGIN failed--compilation aborted at (eval 8) line 1.
 at (eval 7) line 2.
Compilation failed in require at (eval 7) line 2.
Setting environmental variable 'PERL_DL_NONLAZY' to 0 may help.
No Makefile created.
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
no Makefile, doing nothing
@nix { "action": "setPhase", "phase": "installPhase" }
installing
install flags: pkgconfigdir=/nix/store/0fcp287zh4sy1vs62gza7g3qlm65kfhp-perl-JSON-2.97001-aarch64-unknown-linux-gnu/lib/pkgconfig m4datadir=/nix/store/0fcp287zh4sy1vs62gza7g3qlm65kfhp-perl-JSON-2.97001-aarch64-unknown-linux-gnu/share/aclocal aclocaldir=/nix/store/0fcp287zh4sy1vs62gza7g3qlm65kfhp-perl-JSON-2.97001-aarch64-unknown-linux-gnu/share/aclocal pure_install
make: *** No rule to make target 'pure_install'.  Stop.
```

The `preConfigure` and `postConfigure` options you removed in this PR fixes this particular package.

**Comment by volth** [comment]
> The ```preConfigure``` and ```postConfigure``` options you removed in this PR fixes this particular package.

Reverting them breaks build on ```x86_64-linux```.
I will try to debug up to the root cause, otherwise we will have to revert the whole PR

**Comment by volth** [comment]
It seems that better to undo.
the newer ```JSON``` breaks ```CPAN::Meta``` (by not providing ```JSON->new``` when ```JSON::PP``` backend is using, while the older ```JSON-2.90``` forces to use ```JSON::XS``` backend if ```JSON->new```  is called)

**Comment by volth** [comment]
```Loading lib/JSON.pm failed``` is not needed, they just do it for testing.

The problem with cross-compilation is: all the backends (JSON::PP or JSON::XS) end up in loading native modules, ```aarch64``` modules into ```x86_64``` perl

**Pull request merged**
