### PR TITLE
Change self to finalAttrs

### PR DESCRIPTION
**Pull request by AndersonTorres**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by teto** [comment]
why ? is there some spec somewhere ?

**Comment by AndersonTorres** [comment]
No.

But to avoid questions like "I have seen someone using it" or "there is a spec somewhere", I am anticipating.

**Comment by teto** [comment]
Was there any discussion of this anywhere ? If there is a consensus I dont mind but one could see "self" in overlays, and I prefer it because it's shorter to type.  The fact there are already so many self may hint at this. It's tough to search for "self" though as it may refer to something else:
 ```
 ➜ rg -l finalAttrs | wc -l
269
➜ rg -l self | wc -l      
1420
```

**Comment by AndersonTorres** [comment]
The times I came across this particular issue were here:

- https://github.com/NixOS/nixpkgs/pull/212600#discussion_r1086946120
- https://github.com/NixOS/nixpkgs/pull/215860#discussion_r1103897193

There are others but I don't remember perfectly.

**Pull request merged**
