### PR TITLE
gcompris: 0.91 -> 0.95

### PR DESCRIPTION
**Pull request by guibou**
###### Motivation for this change

Bump version to 0.95.

Previous version (0.91) was not properly working with qt > 5.9, it seems fixed now, so I removed the custom pinning to qt 5.9.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peterhoeg** [comment]
Do you want to bumb qmlbox2d as well?

**Comment by guibou** [comment]
@peterhoeg Well, there is nothing really new in `qmlbox2d` since last commit, however I'll bump it and setup it for qt > 5.9.

Actually I'm surprised that it even works, `gcompris` with qt 5.11 and qmlbox2d with qt 5.9.

**Comment by guibou** [comment]
@peterhoeg done.

**Comment by Ma27** [comment]
When I build and start `gcompris`, I get a screen with the following message:

Error for gcompris

**Comment by guibou** [comment]
@Ma27 Have you `nix-env -i ./result` to install `gcompris` into your env? For some reasons, qt packages *must* be installed in an environment to work.

**Comment by Ma27** [comment]
@Mic92 was faster, but I can confirm that it works fine when testing this with `nix run` :)

**Pull request merged**
