### PR TITLE
[20.09] macvim: 8.2.539 -> 8.2.1719

### PR DESCRIPTION
**Pull request by lilyball**
###### Motivation for this change
backport of #99045

Without this version bump the package is broken due to a recent perl update. However it doesn't build on Hydra so it's not showing up as a Hydra failure.

ZHF: #97479

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lilyball** [comment]
ping @NixOS/nixos-release-managers

**Comment by jonringer** [comment]
ofborg doesn't seem to build darwin anymore. Do you mind posting a nixpkgs-review done a darwin machine?

**Review by jonringer — APPROVED** [review]
diff and commits LGTM

**Comment by lilyball** [comment]
I think ofborg is just really slow right now for darwin, the original PR took a while for its checks to populate too.

Anyway `nix-review` builds it just fine

```
https://github.com/NixOS/nixpkgs/pull/99117
2 packages built:
macvim vimacs
```

I didn't even know about `vimacs` 😅 I also tested the scripting language integration and it works (e.g. `:perl print "hi"` works correctly). And `vimacs` runs, though I don't know how to use emacs.

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 99117 [1](https://github.com/Mic92/nixpkgs-review)

**Pull request merged**
