### PR TITLE
graalvm: Use lib.getVersion for stdenv.cc

### LINKED ISSUE #71471: graalvm: build error
**Describe the bug**
```
installing 'graal-19.1.1'
error: while evaluating the attribute 'postPatch' of the derivation 'graal-19.1.1' at /nix/store/9lsn5ss30fq5nhk
3n4zacyqh3izgxg0l-nixpkgs-20.03pre197053.d08a7431561/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:191:11:
while evaluating the attribute 'cc.cc.version' at /nix/store/9lsn5ss30fq5nhk3n4zacyqh3izgxg0l-nixpkgs-20.03pre19
7053.d08a7431561/nixpkgs/pkgs/build-support/cc-wrapper/default.nix:102:10:
attribute 'version' missing, at /nix/store/9lsn5ss30fq5nhk3n4zacyqh3izgxg0l-nixpkgs-20.03pre197053.d08a7431561/n
ixpkgs/pkgs/development/compilers/graalvm/default.nix:321:83
```

**To Reproduce**
`nix-env -iA nixpkgs.graalvm8 --show-trace`

**Metadata**

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.0.0, macOS 10.15`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.1`
 - channels(regadas): `"home-manager, nixpkgs-20.03pre197053.d08a7431561"`
```

@volth @hlolli

### PR DESCRIPTION
**Pull request by regadas**
Attempting to address fix #71471;

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by conferno** [comment]
I am non sure that `native-image` will work smoothly with `clang`
Perhaps `stdenv.cc.cc.version` -> `gcc.cc.version` (and `stdenv.cc` -> `gcc` in other places) would be more honest

**Comment by conferno** [comment]
It is easier to port `graalv8-ee` to Darwin, there is just download and unpack instead of long and tricky build process.
It is unfree though, but who will care on an unfree platform?

**Comment by hlolli** [comment]
It would of course be great if this could work for darwin. I have a darwin myself which I use for ios dev. I'm going to bump this derivation this week, and in the process test darwin. I may want to add, that building graalvm from sources is super memory consuming and slow process. So all help appreciated.

**Comment by volth** [comment]
@hlolli you can try to use https://github.com/NixOS/nix/pull/3036 to avoid restarting the long build process from the beginning on each change (I am using it to work on `chromium` forks)

**Comment by hlolli** [comment]
Very nice, I'll try this, thanks!

**Comment by volth** [comment]
Why?
It is still actively WIP in https://github.com/NixOS/nixpkgs/pull/72331

**Comment by matthewbauer** [comment]
lib.getVersion should be preferred over  `.version` regardless

**Pull request merged**
