### PR TITLE
vivaldi: 2.1.1337.51-1 -> 2.2.1388.37-1; vivaldi-ffmpeg-codecs: 70.0.3538.77 -> 71.0.3578.98

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

Update vivaldi.

- vivaldi: 2.1.1337.51-1 -> 2.2.1388.37-1
- vivaldi-ffmpeg-codecs: 70.0.3538.77 -> 71.0.3578.98

[Minor update for Vivaldi 2.2](https://vivaldi.com/blog/minor-update-for-vivaldi-2-2/)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by worldofpeace** [comment]
@romildo  Mind preparing a backport pr after this is merged? 
Figured that this was something we should do in #51711.

**Comment by romildo** [comment]
>@romildo Mind preparing a backport pr after this is merged?

@worldofpeace It should be easy, but I have not done a backport before. Would someone tell me how it is done?

**Comment by worldofpeace** [comment]
Should just be https://nixos.org/nixpkgs/manual/#submitting-changes-stable-release-branches.
Just those exact commits from master to `release-18.09`.

**Comment by romildo** [comment]
@worldofpeace I hope I have done it right.

**Pull request merged**
