### PR TITLE
temporal: enable tests

### PR DESCRIPTION
**Pull request by superherointj**
temporal: enable tests

### CODE REVIEW

**Comment by zowoq** [comment]
I think if it takes that much to get the tests to pass it is better to keep them disabled.

**Comment by superherointj** [comment]
> I think if it takes that much to get the tests to pass it is better to keep them disabled.

Integration tests and databases are disabled. But A LOT of tests are running. It is not skipping that much as you might think.

**Comment by zowoq** [comment]
I'm referring to the size of `postPatch`. Anything more than a couple of lines (either substituteInPlace or rm) doesn't seem like a good idea, more of a maintainability burden. Are you going to add yourself as a maintainer for this package to ensure that `doCheck`/`postPatch` continue to work with new versions?

**Comment by titanous** [comment]
I also don't think this is worth it, better to upstream a patch that skips all of these if the `-short` flag is used.

**Comment by superherointj** [comment]
> I also don't think this is worth it, better to upstream a patch that skips all of these if the `-short` flag is used.

Are you going to do it then? And make tests work?
Realize the solution I'm offering here is working *now*. We are going from 0 tests to lots of tests.
It can be improved later.

**Comment by titanous** [comment]
>Realize the solution I'm offering here is working now. We are going from 0 tests to lots of tests.

Tests aren't useful if they break with every new release, which is what will happen with this approach. In order for this to be maintainable, the constraints need to be enforced upstream, by creating a limited test set run with `-short` that is checked in their CI.

**Pull request closed without merging**
