### PR TITLE
[20.03] go_1_14: init at 1.14 and switch to it (backport)

### PR DESCRIPTION
**Pull request by Frostman**
###### Motivation for this change

https://golang.org/doc/go1.14

There are Go releases every half a year and we had 1.13 in 19.09, so, it’ll be great to have 1.14 in 20.03

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---
This change is [Reviewable](https://reviewable.io/reviews/nixos/nixpkgs/81266)

### CODE REVIEW

**Comment by Frostman** [comment]
cc @NixOS/nixos-release-managers

**Review by worldofpeace — APPROVED** [review]
Seems sane to me.

**Comment by adisbladis** [comment]
I'm gonna go ahead and try to build all packages and we'll see which ones fail.

**Comment by worldofpeace** [comment]
> I'm gonna go ahead and try to build all packages and we'll see which ones fail.

That's good, but it is going into staging-20.03 so we could use hydra for this https://hydra.nixos.org/jobset/nixpkgs/staging-20.03. But I guess it's also better for something to be adequately tested before merging in the first place.

**Comment by Frostman** [comment]
just in case I've re-tested it with nixpkgs-review:

2 package failed to build:  act python38Packages.aria2p                                                                                                                                                                                                                                         730 package built

**Comment by adisbladis** [comment]
Fixed aria2p by backporting 76079f270c81fb608c9c3ba71b81115e091e8fab

**Comment by adisbladis** [comment]
Fixed `act` by backporting 5e75ba3f420d511db23b8fbf2f54dc92db60ff59 & 5e75ba3f420d511db23b8fbf2f54dc92db60ff59.

**Pull request merged**
