### PR TITLE
googleplaydownloader: init at 1.8

### PR DESCRIPTION
**Pull request by DamienCassou**

### CODE REVIEW

**Comment by DamienCassou** [comment]
Github says that the branch can be merged automatically, but Travis says the opposite.

**Comment by vcunat** [comment]
I suppose the bad authentication I'm getting is due to not filling my credentials.

**Comment by DamienCassou** [comment]
I'm facing several bugs that also prevents me from using this tool:

- https://codingteam.net/project/googleplaydownloader/bugs/show/3051
- https://codingteam.net/project/googleplaydownloader/bugs/show/3047
- https://codingteam.net/project/googleplaydownloader/bugs/show/3052

**Comment by DamienCassou** [comment]
@vcunat normally, the default credentials should just work. But several users seem to face problems. And it's not only related to googleplaydownloader, the problems are the same with gplaycli (e.g., https://github.com/matlink/gplaycli/issues/15 and https://github.com/matlink/gplaycli/issues/16)

**Pull request closed without merging**
