### PR TITLE
Add an escape hatch for the shell check.

### PR DESCRIPTION
**Pull request by farcaller**
###### Description of changes

This adds an escape hatch for an assertion introduced in #211603.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by marcusramberg — APPROVED** [review]
👌

**Review by RaitoBezarius — APPROVED** [review]

**Comment by RaitoBezarius** [comment]
Hey @farcaller ; as always, thank you for the contribution! Can I get you to fix the conflicts for the release notes and I will merge it. Thanks!

**Comment by RaitoBezarius** [comment]
> @RaitoBezarius done.

Could you remove the merge commit and use a rebase instead? Also the commit is not formatted according to the CONTRIBUTING guide (`nixos/blablabla: escape hatch for enabling a shell system-wide`) or something like this?

**Comment by farcaller** [comment]
Whoops. Somehow I thought this was long merged 😨

**Comment by RaitoBezarius** [comment]
Some conflict in the RL, if you fix them, good to go :)

**Comment by RaitoBezarius** [comment]
We usually rebase and do not use merge commits for fixing conflicts

**Comment by farcaller** [comment]
@RaitoBezarius I know! I thought the UI would do the right job and then it didn't and then git cli decided to rebase 10K commits because I fat-fingered a sha. All good now.

**Comment by RaitoBezarius** [comment]
Thanks @farcaller we made it!

**Comment by SuperSandro2000** [comment]
Please do not merge pull requests with merge commits. If there is a merge conflict on that commit, it is an absolute nightmare to resolve because you have a gigantic working tree to work with.

**Comment by RaitoBezarius** [comment]
Apologies I thought I removed the merge commit and the best rebase didn't
introduce it but GitHub UI took the best of me again, given the situation,
I didn't feel comfortable making the merge go longer.

**Comment by farcaller** [comment]
I’m sorry, it's on me! I did the conflict resolution with github once again thinking it will do the reasonable thing by default.

**Pull request merged**
