### PR TITLE
remove vala namespace

### PR DESCRIPTION
**Pull request by RamKromberg**
###### Motivation for this change

https://github.com/NixOS/nixpkgs/issues/17869

This is a zero-sum namespace-only change that removes the default vala package name in favor of vala_0_23. It shouldn't lead to any recompilation.

What prompted this was some runtime errors followed by realization vala major versions track glib and break both backwards and forwards.

With this change, maintainers will no longer just put vala, not realizing the runtime issues an incorrect version triggers.

Note: Done manually.

### CODE REVIEW

**Comment by RamKromberg** [comment]
cc @lethalman for input

**Comment by lethalman** [comment]
Indeed nothing was built by travis. Thanks, looks good.

**Comment by domenkozar** [comment]
So why do we then still have `vala`?

**Comment by lethalman** [comment]
@domenkozar where?

**Comment by domenkozar** [comment]
@lethalman my bad, commit message mislead me :)

**Comment by RamKromberg** [comment]
Thanks!

**Pull request merged**
