### PR TITLE
mdadm: allow sending mail when using opensmtpd

### PR DESCRIPTION
**Pull request by Ekleog**
`opensmtpd` does not require the setuid bit for its `sendmail`. This works around it by wrapping the called `sendmail` so that the wrapper falls back on either the setuid `sendmail` or the non-setuid `sendmail` depending on what's available.

I don't know whether that's something that happens often, but maybe it'd make sense to generate a linkfarm to both `current-system/sw/bin` and `wrappers/bin`, for when an absolute path is requested?

Tested on 18.03.

### CODE REVIEW

**Comment by Ekleog** [comment]
Just added information to the commit message. Also copying it here as it'll be easier to access:
```
The solution of relying on `$PATH` to be set is unfortunately unreliable, as `mdadm --monitor` will likely be executed from a `systemd` unit, that runs with a clean `$PATH`.
```
So I thought it'd be better to just follow what the previous `mdadm` did, and depend on the current environment.

**Comment by bjornfor** [comment]
Both approaches have their benefits.

I personally prefer to not leak NixOS specific paths into nixpkgs (the packages). Sometimes it doesn't really matter, other times it makes packages break on non-NixOS. By the way, [here](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/network-filesystems/kbfs.nix#L50) you can see the $PATH approach implemented in the kbfs NixOS module. Does mdadm work with sendmail PATH lookup and something like ```path = [ "/run/wrappers" "/run/current-system/sw/bin" ];``` in the systemd service definition?

**Comment by Ekleog** [comment]
I can confirm it does work with PATH, actually that's the way I initially chose to develop. The issue I came upon with that is that there are likely people with services such as:
```nix
systemd.services.mdadm-monitor = {
  description = "Monitor RAID disks";
  wantedBy = [ "multi-user.target" ];
  script = "${pkgs.mdadm}/bin/mdadm --scan --monitor -m root";
};
```
And such a script would be silently broken by such an update: it would no longer send any email were one of the disks to fail. This sounds like an easy way to have someone hate nixpkgs, unfortunately.

And I don't really know of any way to handle the switch cleanly. Using `lib.warn` to warn on all installs of `mdadm` until 18.09 seems… a bit overkill. And I'd rather not just break everything silently until then.

Do you have any idea how to handle this better?

**Comment by bjornfor** [comment]
Good point. (I have a hand-written service like that myself.) The problem is that we don't have a NixOS module for mdadm, https://github.com/NixOS/nixpkgs/issues/31840. Let's merge.

**Review by bjornfor — APPROVED** [review]

**Comment by bjornfor** [comment]
Applied to master (ec9a51d0cc6fab730bfe10d354b47c98ddb37460).

**Comment by Ekleog** [comment]
Thanks!

**Pull request closed without merging**
