### PR TITLE
mindustry,mindustry-server: 104.6 -> 120

### PR DESCRIPTION
**Pull request by fgaz**
###### Motivation for this change

After a ton of betas, the "codename 6.0" release is finally stable: https://github.com/Anuken/Mindustry/releases/tag/v120

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by petabyteboy** [comment]
Builds and starts on NixOS x86_64-linux. The audio sounds a bit crackly to me, not sure if it's part of the soundtrack though.

**Comment by fgaz** [comment]
@petabyteboy it's just how it is I think

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105590` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>mindustry</li>
    <li>mindustry-server</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105590` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>mindustry</li>
    <li>mindustry-server</li>
  </ul>
</details>

```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1m 15s
10 actionable tasks: 7 executed, 3 up-to-date
installing
post-installation fixup
strip is /nix/store/pd852x17wab1glhw1ahqacsnlvcidr7a-cctools-binutils-darwin-949.0.1/bin/strip
patching script interpreter paths in /nix/store/hfmns925g1qlbcflhmjp7sbrlz0ry49g-mindustry-deps-120
hash mismatch in fixed-output derivation '/nix/store/mm5dpz4q45mm45xrcmsgc00x9x1vg54d-mindustry-deps-120':
  wanted: sha256:1yv9l8zdml6drmvlgv45w3qas9qmb654x4kja3an4d16k020khr7
  got:    sha256:0w63syrqvq2g7ra99xr18mhinrkhckvvhy6c4psfivgk71080jj3
cannot build derivation '/nix/store/4l0kws7c7nln04m7b7ciamk2x69vl51d-mindustry-120.drv': 1 dependencies couldn't be built
error: build of '/nix/store/4l0kws7c7nln04m7b7ciamk2x69vl51d-mindustry-120.drv' failed
```

**Comment by fgaz** [comment]
A hash mismatch? I don't think I can fix that for every new release, especially with the broken ofborg darwin builder (I don't have a darwin machine). So I think I'll just mark the package as broken for darwin, unless someone volunteers to generate the hash at each new release.

**Comment by petabyteboy** [comment]
Maybe this can be fixed by changing to [gradle2nix](https://github.com/tadfisher/gradle2nix/) at some point.

**Comment by fgaz** [comment]
Indeed, I hope it gets integrated into nixpkgs soon

**Comment by SuperSandro2000** [comment]
> A hash mismatch? I don't think I can fix that for every new release, especially with the broken ofborg darwin builder (I don't have a darwin machine). So I think I'll just mark the package as broken for darwin, unless someone volunteers to generate the hash at each new release.

I could generate it but with some delay.

**Comment by petabyteboy** [comment]
The deps directory contains com/github/Anuken as well as com/github/anuken. @SuperSandro2000 can you post a directory listing of the -deps derivation? I would like to see if these lowercase/uppercase names differ.

**Comment by SuperSandro2000** [comment]
@petabyteboy
```
anuken~nix~case~hack~1
```
https://termbin.com/bv8w
😂 

```
these derivations will be built:
  /nix/store/7pzl8gisaly7r7xrd4aihgy47f4713wc-mindustry-120.2.drv
[2F[0Jbuilding '/nix/store/7pzl8gisaly7r7xrd4aihgy47f4713wc-mindustry-120.2.drv'...
[4F[0Junpacking sources
[4F[0Junpacking source archive /nix/store/jdxyya7q9gicm4rdnkwjxlzv1g2zs0xd-source
[4F[0Jsource root is source
[4F[0Jpatching sources
[4F[0Jconfiguring
[4F[0Jno configure script, doing nothing
building
[4F[0J
Welcome to Gradle 6.7!

Here are the highlights of this release:
 - File system watching is ready for production use
 - Declare the version of Java your build requires
 - Java 15 support

[4F[0JFor more details see https://docs.gradle.org/6.7/release-notes.html

[4F[0JTo honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.7/userguide/gradle_daemon.html.
[4F[0J
FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/6.7/userguide/gradle_daemon.html
Process command line: /nix/store/54l615jr0sdlzs91vxwncs9a3kab90bm-zulu14.28.21-ca-jdk14.0.1/zulu-14.jdk/Contents/Home/bin/java --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED -Xms256m -Xmx1024m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /nix/store/rhmg9cp3pzw81ly0m8aq9k3d3lfknlsc-gradle-6.7/lib/gradle/lib/gradle-launcher-6.7.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 6.7
Please read the following process output to find out more:
-----------------------

FAILURE: Build failed with an exception.

* What went wrong:
java.net.SocketException: Operation not permitted

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.UncheckedIOException: java.net.SocketException: Operation not permitted
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:61)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
        at org.gradle.internal.remote.internal.inet.TcpIncomingConnector.accept(TcpIncomingConnector.java:62)
        at org.gradle.launcher.daemon.server.DaemonTcpServerConnector.start(DaemonTcpServerConnector.java:86)
        at org.gradle.launcher.daemon.server.Daemon.start(Daemon.java:169)
[4F[0J        at org.gradle.launcher.daemon.bootstrap.DaemonMain.doAction(DaemonMain.java:125)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:50)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
        at org.gradle.launcher.daemon.bootstrap.GradleDaemon.main(GradleDaemon.java:22)
Caused by: java.net.SocketException: Operation not permitted
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:479)
        at java.base/sun.nio.ch.Net.bind(Net.java:468)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:220)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:88)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
        at org.gradle.internal.remote.internal.inet.TcpIncomingConnector.accept(TcpIncomingConnector.java:59)
        ... 11 more


* Get more help at https://help.gradle.org


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
[4F[0Jbuilder for '/nix/store/7pzl8gisaly7r7xrd4aihgy47f4713wc-mindustry-120.2.drv' failed with exit code 1
[4F[0J[31;1merror:[0m build of '/nix/store/7pzl8gisaly7r7xrd4aihgy47f4713wc-mindustry-120.2.drv' failed
```

**Pull request merged**
