### PR TITLE
aperture: 0.2-beta -> 0.3-beta

### PR DESCRIPTION
**Pull request by HannahMR**
## Description of changes

Package updated from Aperture version 0.2-beta to Aperture version 0.3-beta. Hashes updated and HannahMR added as a maintainer. 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by amaxine** [comment]
Thank you for your contribution! There are a few things you'll need to fix in your PR - primarily, you need to first add yourself to the maintainers list [here](https://github.com/NixOS/nixpkgs/blob/master/maintainers/maintainer-list.nix) to be able to become a package maintainer - you can do that in this PR, no need to open a new one.

Please also make sure your commit message adheres to nixpkgs' [commit conventions](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions) - for the update, `aperture: 0.2-beta -> 0.3-beta` would be the right format.

**Comment by HannahMR** [comment]
Okay how we looking now? 

Please let me know if there is anything else I should update here. 

Cheers

**Comment by amaxine** [comment]
That's fixed one part of CI - but you need to fix the commit message in which you're performing the update, not just the PR title. You can rewrite the history and force push this PR to get this fixed.

The commit message is important for triggering the right builds with ofborg.

**Comment by HannahMR** [comment]
Okay, third time's the charm? How's this?

**Review by amaxine — APPROVED** [review]
Looks good, thanks!

**Comment by HannahMR** [comment]
Thanks for walking me through the process!

**Pull request merged**
