### PR TITLE
kubeless: init at 1.0.4

### PR DESCRIPTION
**Pull request by 00-matt**
###### Motivation for this change

Adds the `kubeless` command for interacting with functions running on top of Kubernetes.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by srhb — CHANGES_REQUESTED** [review]
Thanks for the contribution!

If you add something like:

```
  buildFlagsArray = ''
    -ldflags=
      -X github.com/kubeless/kubeless/pkg/version.Version=${version}
  '';
```

`kubeless version` will display the correct version instead of an empty string. :)

**Review by srhb — APPROVED** [review]

**Comment by 00-matt** [comment]
Thanks for the version tip. Updated that and fixed the entry in the maintainers list :)

**Comment by srhb** [comment]
Great! I'll merge as soon as OfBorg gives the A-OK. Thanks again! :smile_cat:

**Comment by mmahut** [comment]
@GrahamcOfBorg build kubeless

**Pull request merged**
