### PR TITLE
linuxPackages.nvidia_x11_beta: 470.42.01 -> 495.29.05

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
Add new nvidia beta driver

Fixes for 5.10-hardened are here: https://github.com/NixOS/nixpkgs/pull/141681

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by colemickens** [comment]
LGTM and works for me.

**Comment by colemickens** [comment]
While this initially works, I think there's additional work for us to do, from the release notes:

> Added support for the GBM API. This adds the new symlink nvidia-drm_gbm.so pointing to the file libnvidia-allocator.so.VERSION to implement a GBM backend driver usable with the GBM loader from the Mesa project version 21.2 and above, as well as the files libnvidia-egl-gbm.so.1.1.0 and 15_nvidia_gbm.json, which implement EGL support for the GBM platform (EGL_KHR_platform_gbm).

I think this the so and json both probably require fixing-up so they actually install.

**Comment by jonringer** [comment]
> I think basically we're going to have to rebuild mesa and have it learn about some new GBM search dirs under /run/opengl

Sounds good to me.

But modifying mesa is kind of out-of-scope for this PR, and it will probably need to target staging. If this PR looks good, let's merge it, then do mesa changes in another.

**Comment by colemickens** [comment]
Aggh, Sorry, I forget GitHub doesn't post email replies as comments anymore.

I totally agree, I didn't mean to hold up merging this. I'd love to see this merged, and then my other nvidia PR, and then it looks like you already tackled mesa, I'll grab that and try it soon too. 

Again to be clear, very in favor of merging this. Thanks!

**Comment by jonringer** [comment]
> Again to be clear, very in favor of merging this. Thanks!

Everything builds, and going to view that as approval :)

**Comment by jonringer** [comment]
backport: #141920

**Pull request merged**
