### PR TITLE
yosys: 0.12+54 -> 0.15

### PR DESCRIPTION
**Pull request by Luflosi**
###### Motivation for this change
https://github.com/YosysHQ/yosys/releases/tag/yosys-0.15
Also fix the link to the homepage as the old link was now pointing at a casino website.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Luflosi** [comment]
Updated to 0.15.

**Review by c0bw3b — COMMENTED** [review]
The `abc` update should be a separate commit.

**Comment by mweinelt** [comment]
Yes, it should be, since they are different attributes. We don't guarantee that intermediate commits aren't breaking, but as long as the whole PR isn't that is totally fine.

**Comment by Luflosi** [comment]
Ok, done.

**Review by c0bw3b — COMMENTED** [review]
Result of `nixpkgs-review pr 160342` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>acl2</li>
  </ul>
</details>
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>abc-verifier</li>
    <li>echidna</li>
    <li>glasgow (python39Packages.glasgow)</li>
    <li>mcy</li>
    <li>openroad</li>
    <li>python310Packages.amaranth</li>
    <li>python310Packages.amaranth-boards</li>
    <li>python310Packages.amaranth-soc</li>
    <li>python310Packages.glasgow</li>
    <li>python39Packages.amaranth</li>
    <li>python39Packages.amaranth-boards</li>
    <li>python39Packages.amaranth-soc</li>
    <li>symbiyosys</li>
    <li>yosys</li>
    <li>yosys-bluespec</li>
    <li>yosys-ghdl</li>
  </ul>
</details>

---

`abc` can run.

Not sure if `acl2` failure was here before this PR. It fails with:

```session
builder for '/nix/store/867ldvc7p8v0lq6qm6qqr6mxf714046y-acl2-8.4.drv' failed with exit code 2; last 10 log lines:
  
  **CERTIFICATION FAILED** for /nix/store/189i2nyjy2w63jcnkal21paqr18v7sx2-acl2-8.4/share/acl2/books/models/y86/y86-basic/common/x86-state.lisp
  
  make: *** [/nix/store/189i2nyjy2w63jcnkal21paqr18v7sx2-acl2-8.4/share/acl2/books/build/make_cert:116: models/y86/y86-basic/common/x86-state.cert] Error 1
  make: *** Waiting for unfinished jobs....
  Built /nix/store/189i2nyjy2w63jcnkal21paqr18v7sx2-acl2-8.4/share/acl2/books/rtl/rel9/support/support/oddr-proofs.cert (2.546s)
  Built /nix/store/189i2nyjy2w63jcnkal21paqr18v7sx2-acl2-8.4/share/acl2/books/projects/filesystems/absfat/abs-find-file.cert (879.519s)
  Built /nix/store/189i2nyjy2w63jcnkal21paqr18v7sx2-acl2-8.4/share/acl2/books/rtl/rel9/support/support/setbits-proofs.cert (26.784s)
  Built /nix/store/189i2nyjy2w63jcnkal21paqr18v7sx2-acl2-8.4/share/acl2/books/workshops/2011/krug-et-al/support/MinVisor/setup-nested-page-tables.cert (3730.064s)
  Built /nix/store/189i2nyjy2w63jcnkal21paqr18v7sx2-acl2-8.4/share/acl2/books/projects/filesystems/eqfat.cert (1128.408s)
```

**Comment by Luflosi** [comment]
Hmm, acl2 builds fine for me. `nixpkgs-review pr 160342` also shows no failure for me. Maybe it's a flaky test or something?

**Review by c0bw3b — APPROVED** [review]
I reproduced my failure again but it's probably because I ran the build in a VM _or_ because there's unfree components.

**Pull request merged**
