### PR TITLE
youtube-dl: 2020.12.31 -> 2021.01.03

### PR DESCRIPTION
**Pull request by zowoq**
https://github.com/ytdl-org/youtube-dl/releases/tag/2021.01.03

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by fabaff — APPROVED** [review]

**Review by prusnak — APPROVED** [review]

**Comment by zowoq** [comment]
`20.09`: 78a5623173ceef6df94f6c33d0260680c0059743

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108281` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
5 packages marked as broken and skipped:
</summary>
<ul>
<li>haskellPackages.cut-the-crap</li>
<li>jellyfin-mpv-shim</li>
<li>kodi-cli</li>
<li>persepolis</li>
<li>sublime-music</li>
</ul>
</details>
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>mpc-qt: log https://hastebin.com/raw/xoqodegaxe</li>
  </ul>
</details>
<details>
<summary>
21 packages built:
</summary>
<ul>
<li>catt</li>
<li>curseradio</li>
<li>mkchromecast</li>
<li>mopidy-youtube</li>
<li>mps-youtube</li>
<li>plex-mpv-shim</li>
<li>python37Packages.mpv</li>
<li>python37Packages.pafy</li>
<li>python37Packages.youtube-dl</li>
<li>python37Packages.youtube-dl-light</li>
<li>python38Packages.mpv</li>
<li>python38Packages.pafy</li>
<li>youtube-dl (python38Packages.youtube-dl)</li>
<li>youtube-dl-light (python38Packages.youtube-dl-light)</li>
<li>python39Packages.mpv</li>
<li>python39Packages.pafy</li>
<li>python39Packages.youtube-dl</li>
<li>python39Packages.youtube-dl-light</li>
<li>somafm-cli</li>
<li>tuijam</li>
<li>ytcc</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

plex-mpv-shim:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108281` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>plex-media-player: log was empty</li>
  </ul>
</details>
<details>
<summary>
34 packages built:
</summary>
<ul>
<li>catt</li>
<li>celluloid</li>
<li>curseradio</li>
<li>haskellPackages.cut-the-crap</li>
<li>jellyfin-mpv-shim</li>
<li>jftui</li>
<li>kodi-cli</li>
<li>lollypop</li>
<li>minitube</li>
<li>mkchromecast</li>
<li>mopidy-youtube</li>
<li>mpc-qt</li>
<li>mps-youtube</li>
<li>mpv</li>
<li>persepolis</li>
<li>plex-mpv-shim</li>
<li>python37Packages.mpv</li>
<li>python37Packages.pafy</li>
<li>python37Packages.youtube-dl</li>
<li>python37Packages.youtube-dl-light</li>
<li>python38Packages.mpv</li>
<li>python38Packages.pafy</li>
<li>youtube-dl (python38Packages.youtube-dl)</li>
<li>youtube-dl-light (python38Packages.youtube-dl-light)</li>
<li>python39Packages.mpv</li>
<li>python39Packages.pafy</li>
<li>python39Packages.youtube-dl</li>
<li>python39Packages.youtube-dl-light</li>
<li>qimgv</li>
<li>somafm-cli</li>
<li>sublime-music</li>
<li>tartube</li>
<li>tuijam</li>
<li>ytcc</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

jellyfin-mpv-shim:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>
plex-mpv-shim:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>
sublime-music:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>

**Comment by SuperSandro2000** [comment]
Fixed all those issues and going to do a PR with them tomorrow.

**Pull request merged**
