### PR TITLE
libtool: 2.4.7 -> 2.5.4

### PR DESCRIPTION
**Pull request by s1syph0s**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by getchoo — CHANGES_REQUESTED** [review]
It seems this update will cause a lot of rebuilds, meaning it should be targeting our `staging` branch rather than `master`. Our Contributing guide describes how to rebase pull requests onto `staging` [here](https://github.com/NixOS/nixpkgs/blob/6e984ab74f3a519a4e8b88a82d30678ffdff2f8a/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging)

Let me know if you need any help, any welcome to Nixpkgs!

**Review by getchoo — APPROVED** [review]
> Would this be right?

Yep, that seems to have worked just as well

I'll try to build this tomorrow if CI doesn't. Diff LGTM, and welcome again to Nixpkgs :)

**Comment by s1syph0s** [comment]
thank you :)

**Comment by s1syph0s** [comment]
@getchoo Is there an update regarding this PR? The CI failed for several reasons. The `nixpkgs-lib-tests` failed because it could find the `release.nix`, and the other jobs failed because the operation was cancelled (in nixpkgs-manual-build I found the cancelled entry in the log, and I couldn't download the log from nixos-manual-build).

**Comment by getchoo** [comment]
> The CI failed for several reasons. The nixpkgs-lib-tests failed because it could find the release.nix, and the other jobs failed because the operation was cancelled (in nixpkgs-manual-build I found the cancelled entry in the log, and I couldn't download the log from nixos-manual-build).

This was just bad luck with the commit on staging that was rebased onto, and not related to this PR

> Is there an update regarding this PR?

I was waiting for other reviews to come around, but as those haven't come and builds finished on Linux (and Darwin failures appear to be unrelated), I'll merge now. Thanks again!

**Comment by mweinelt** [comment]
I'm seeing a hash mismatch on staging for libtool right now.

```
error: hash mismatch in fixed-output derivation '/nix/store/izbfj3rckm6lyip0y99dw9hyyap52kg6-libtool-2.5.4.tar.gz.drv':
        likely URL: https://ftpmirror.gnu.org/libtool/libtool-2.5.4.tar.gz
         specified: sha256-2o67LOTc9GuQCY2vliz/po9LT2LqYPeY0O8Skp7eat8=
            got:    sha256-DFroQ6osZmBT/jtl6vdid+Pae3Fz3zCouS8N8e239DY=

**Comment by paparodeo** [comment]
I get the same one as the PR
```
$ nix-build -E '(import <nixpkgs>{}).fetchurl { url = "mirror://gnu/libtool/libtool-2.5.4.tar.gz"; }'
warning: found empty hash, assuming 'sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='
this derivation will be built:
  /nix/store/ycz5g17wc5v5zzldb1vwnl8vn0avdkwj-libtool-2.5.4.tar.gz.drv
building '/nix/store/ycz5g17wc5v5zzldb1vwnl8vn0avdkwj-libtool-2.5.4.tar.gz.drv'...

trying https://ftpmirror.gnu.org/libtool/libtool-2.5.4.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1969k  100 1969k    0     0  3136k      0 --:--:-- --:--:-- --:--:-- 15.1M
error: hash mismatch in fixed-output derivation '/nix/store/ycz5g17wc5v5zzldb1vwnl8vn0avdkwj-libtool-2.5.4.tar.gz.drv':
         specified: sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
            got:    sha256-2o67LOTc9GuQCY2vliz/po9LT2LqYPeY0O8Skp7eat8=
```

**Comment by mweinelt** [comment]
Indeed, cannot reproduce the hash mismatch anymore, so nvm.

**Comment by mweinelt** [comment]
If you have both sources, can you do a recursive diff?

**Pull request merged**
