### PR TITLE
neko: 2.1.0 -> 2.2.0

### PR DESCRIPTION
**Pull request by volth**
new version.
all patches included.

@andyli  @aszlig

### CODE REVIEW

**Comment by orivej** [comment]
I can not make `haxe` build with it…

**Comment by volth** [comment]
@orivej it should work now

**Comment by orivej** [comment]
Wow, was that a lucky guess or did you have a theory?

Your commit's author has become `John Doe <John Doe john@example.com>`, is this by mistake?

**Comment by volth** [comment]
@orivej this [sed-patch](https://github.com/NixOS/nixpkgs/pull/32907/files#diff-f7304197ba63821ecc7b8c8e4e0356a2L45) is needless after https://github.com/HaxeFoundation/neko/commit/4ee7192c9a23b4b95681d4adc3a84f07730135dd

**Comment by orivej** [comment]
Thank you!

**Comment by volth** [comment]
maybe ```rm -rf $out/lib/cmake``` at the end
some cmake files leaked to the output

**Pull request merged**
