### PR TITLE
clj-kondo: 2020.04.05 -> 2020.06.12

### PR DESCRIPTION
**Pull request by bennyandresen**
###### Motivation for this change
version bump

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ x Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jlesquembre — APPROVED** [review]
Tested it with graalvm11-ee and looks fine. Good catch with the buildInputs

**Comment by hlolli** [comment]
I could make a PR on this branch for a small graalvm8ce fix actually. I've been last 4 weeks working on graalvm20, it's gonna take few more weeks, and I think the problem preventing a build is very easy problem to solve.

**Comment by jlesquembre** [comment]
@hlolli If you have time for that, it would be great. I'm thinking about creating new graalvm packages based on the binaries from https://github.com/graalvm/graalvm-ce-builds, if I find time for it. Of course, your version is preferred, but I'd like to have an alternative version for cases like this, where the build from source is broken for a long period

**Comment by hlolli** [comment]
@jlesquembre that's exactly what I also have in mind, I want to be able to create an environment where I can develop new graalvm packages using nix. If you're interested, I could take you trough the build process on high level and also get your opinion and suggestions on how to best port graalvm ecosystem over to nix. I feel bit alone with this massive ecosystem. You can check out my open PR https://github.com/NixOS/nixpkgs/pull/86244 where I've thus far been able to seperate graalpython from the core graalvm. I'm still left with graaljs and fastR. In best case scenario, we'd define a graalvm environment the same way we do in python (using pythonPackages.withPackages [ foo bar];) and develop by converting suite.py to a nix expression, tough that could be a seperate project unrelated to nixpkgs.

**Comment by hlolli** [comment]
Btw, porting simplelanguage to nixpkgs could be a good "hello world" nixos packaging of graalvm suites. So the question, how would a compilation of somthing like simplelanguage using nix, be best configured.

**Comment by jlesquembre** [comment]
@hlolli I took a look to #86244 , but it is massive and I'm lost, I'll need some help to understand what is going on. If I'm not mistaken, what you you want to do is something like 
```nix
graalvm.withLanguages [ llvm python]
``` 
then you have access to python and llvm to build your graalvm application, is that right?

I'm also a bit confused about what you mean by separating graaljs/fastr... from core graalvm, I thought that they were already separated, or at least looks like graalvm project offers different download per component.

This conversation is off-topic for this PR, I think we should continue on other place.

**Comment by bennyandresen** [comment]
New version was released. Bumped PR.

**Comment by bennyandresen** [comment]
I will close this. We've updated to graalvm-ce and it doesn't work right now with the latest 2010.10.10 version. I'm upstreaming a change in how the standalone.jar is built that we consume.

I will update after the next release.

**Pull request closed without merging**
