### PR TITLE
openroad: unstable-2022-07-19 -> unstable-2023-03-31

### PR DESCRIPTION
**Pull request by panicgh**
###### Description of changes

Update to the latest upstream commit.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by risicle — APPROVED** [review]
LGTM, builds for me, nixos x86_64

**Comment by trepetti** [comment]
Beat me to it, thank you!

**Comment by hzeller** [comment]
I notices that, this seemed to stop compiling for some reason in the last month.
On a current nixos unstable, attempting to use `openroad` results in a compile issue.

I can confirm that nixpkgs at the time of this commit (8ece93e12ef5cbe59050f41c31bc8f70038e51af) this compiles on nixos x86_64.

However, at current head of nixpkgs building with `nix-build -A openroad` results in a cmake configure error, and the compilation stops.

```
...
CMake Error in src/mpl2/CMakeLists.txt:
  Imported target "ortools::ortools" includes non-existent path

    "/nix/store/9shzdd9ymr3lqfi9jmx21s038bwqwgbw-or-tools-9.4/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in src/par/CMakeLists.txt:
  Imported target "ortools::ortools" includes non-existent path

    "/nix/store/9shzdd9ymr3lqfi9jmx21s038bwqwgbw-or-tools-9.4/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

So I suspect that something changed/broken in the meantime. I don't have enough NixOS-FU yet to fully debug. It does seem that the or-tools package used to contain everything (bin, lib, include, e.g. /nix/store/73klpwa320ccy5x5mn14m00v5w03x51x-or-tools-9.4), but these days the are separated; there is
a `/nix/store/9shzdd9ymr3lqfi9jmx21s038bwqwgbw-or-tools-9.4` which contains the binaries and libraries, and there is 
`/nix/store/zv86mnips2bjyhllxy7gz4mqvidx29vl-or-tools-9.4-dev`, which contains the includes and the cmake configuration.

Maybe the package has to be configured to pick up the `or-tools.dev` ?

**Comment by hzeller** [comment]
Bisecting it, the  https://github.com/NixOS/nixpkgs/commit/1d5e5ca56d1f6019b8a7dcc5b66a78e767e5276 commit in `or-tools` by @lopsided98 seemed to have triggered the situation that  `openroad` can't compile anymore.

The `or-tools` patch does add the `"dev"` output, so now library and includes are separated and possibly confuses CMake file searching for the components.

Maybe with this info you're able get openroad to compile again ?

**Comment by lopsided98** [comment]
#229148

**Pull request merged**
