### PR TITLE
xdg-app: init at git 2015/08/16

### PR DESCRIPTION
**Pull request by ts468**

### CODE REVIEW

**Comment by nbp** [comment]
```
Xdg-App is a tool that uses OSTree to install and update runtimes and applications.

It also allows the user to start these applications in a container-like environment where they are isolated (to various degrees) from the host operating system. In particular, each application depends on a particular runtime which supplies /usr for the application.
```

Would be nice to have a similar mechanism on top of nix.

**Comment by ts468** [comment]
@nbp How would you design such a mechanism for nixos? For now I'm mainly interested into xdg-app-helper, which seems to be the part that does all the namespacing magic and which works without all the ostree overhead. I'm thinking of using it for the local nixup environment (nixup shell) and for having wine applications that can be installed into the nix store.

**Comment by nbp** [comment]
@ts468 I think we can get inspiration from `buildFHSUserEnv` [1] and `buildFHSChrootEnv` [2].  Then instead of making an FHS compliant environment, we can only mount the necessary resources.

But maybe this would be easier with `xdg-app-helper`, I have no idea.

[1] https://github.com/NixOS/nixpkgs/tree/master/pkgs/build-support/build-fhs-userenv
[2] https://github.com/NixOS/nixpkgs/tree/master/pkgs/build-support/build-fhs-chrootenv

**Comment by joachifm** [comment]
Ping?

**Comment by matthewbauer** [comment]
This looks like it's been renamed to "flatpak". But I'm not sure how useful it is because everything this offers can be done via Nix and some "nix-user-chroot" bootstrapping.

**Comment by garbas** [comment]
@ts468 is this still work in progress?

**Comment by baracoder** [comment]
It could be useful because of the sandboxing features like for file access and so on, I think nix does not have any sandboxing features

I would be interested to use flatpak.

**Comment by garbas** [comment]
closing this PR since it looks like it is outdated. it would be nice to have flatpack in nix, but this should be done in a separate PR.

**Pull request closed without merging**
