### PR TITLE
libvirt: Update from 1.2.19 to 1.3.0

### PR DESCRIPTION
**Pull request by wido**
This is my first PR for NixOS and I don't know if I need to perform any more testing.

Followed this guide: https://nixos.org/wiki/Create_and_debug_nix_packages

This is to update libvirt to 1.3.0 in NixOS.

### CODE REVIEW

**Comment by copumpkin** [comment]
Looks fine to me, but I don't know if downstream tools will break with the new version.

**Comment by wido** [comment]
@copumpkin Thanks! I tested libvirt 1.3.0 and it works just fine with all the things I do with it.

The libvirt API is also very stable, they only add functions, nothing is ever removed or changed.

**Comment by bjornfor** [comment]
Where is the changelog for >=1.3.0? I only see <= 1.2.18 at http://wiki.libvirt.org/page/Maintenance_Releases. (1.2.18.2 was released late in december 2015.)

**Comment by bjornfor** [comment]
Oh, and <=1.2.21 is found at http://libvirt.org/news.html (latest update from november 2015).

**Comment by nckx** [comment]
> @bjornfor: Where is the changelog for >=1.3.0? I only see <= 1.2.18 at http://wiki.libvirt.org/page/Maintenance_Releases.

That is already the most stupidly confusing page I have seen this year.

The ChangeLog in the tarball is basically just a commit-by-commit git dump. So, [this](http://libvirt.org/git/?p=libvirt.git;a=log;h=refs/tags/v1.3.0). Judging by that, I doubt there's anything better on the web site.

**Comment by wido** [comment]
I appreciate the level of testing and checking that is done on this PR, but I don't want to be blund, but isn't this a bit to much?

libvirt is one of the most stable software projects I know. Very stable API and codebase.

**Comment by nckx** [comment]
Less testing, more no-one feeling like being the one responsible for breaking something.

I do agree that if something breaks, it's not likely to be because of this. Merged. Thanks!

**Comment by copumpkin** [comment]
For what it's worth, this broke the build (link) on Darwin :smile: (which I just got working last week! :expressionless:)

Here's an excerpt from the failed build:
```
...
  CC       vbox/libvirt_driver_vbox_impl_la-vbox_V4_0.lo
  CC       vbox/libvirt_driver_vbox_impl_la-vbox_V4_1.lo
  CC       vbox/libvirt_driver_vbox_impl_la-vbox_V4_2.lo
  CC       vbox/libvirt_driver_vbox_impl_la-vbox_V3_1.lo
  CC       vbox/libvirt_driver_vbox_impl_la-vbox_V4_2_20.lo
  CC       remote/libvirt_driver_remote_la-remote_protocol.lo
  CC       vbox/libvirt_driver_vbox_impl_la-vbox_V4_3.lo
  CC       vbox/libvirt_driver_vbox_impl_la-vbox_V4_3_4.lo
  CC       vbox/libvirt_driver_vbox_impl_la-vbox_common.lo
  CC       vbox/libvirt_driver_vbox_impl_la-vbox_network.lo
  CC       qemu/libvirt_driver_qemu_impl_la-qemu_blockjob.lo
  CC       qemu/libvirt_driver_qemu_impl_la-qemu_capabilities.lo
  CC       qemu/libvirt_driver_qemu_impl_la-qemu_command.lo
  CC       qemu/libvirt_driver_qemu_impl_la-qemu_domain.lo
  CC       qemu/libvirt_driver_qemu_impl_la-qemu_agent.lo
  CC       qemu/libvirt_driver_qemu_impl_la-qemu_cgroup.lo
  CC       vbox/libvirt_driver_vbox_impl_la-vbox_storage.lo
  CC       qemu/libvirt_driver_qemu_impl_la-qemu_hostdev.lo
  CC       qemu/libvirt_driver_qemu_impl_la-qemu_hotplug.lo
  CC       qemu/libvirt_driver_qemu_impl_la-qemu_conf.lo
  CC       qemu/libvirt_driver_qemu_impl_la-qemu_process.lo
  CC       qemu/libvirt_driver_qemu_impl_la-qemu_migration.lo
  CC       qemu/libvirt_driver_qemu_impl_la-qemu_monitor_json.lo
  CC       qemu/libvirt_driver_qemu_impl_la-qemu_driver.lo
  CC       qemu/libvirt_driver_qemu_impl_la-qemu_interface.lo
  CC       secret/libvirt_driver_secret_la-secret_driver.lo
  CC       qemu/libvirt_driver_qemu_impl_la-qemu_monitor_text.lo
  CC       storage/libvirt_driver_storage_impl_la-storage_driver.lo
  CC       qemu/libvirt_driver_qemu_impl_la-qemu_monitor.lo
  CC       storage/libvirt_driver_storage_impl_la-storage_backend.lo
  CC       storage/libvirt_driver_storage_impl_la-storage_backend_fs.lo
  CC       storage/libvirt_driver_storage_impl_la-storage_backend_scsi.lo
  CCLD     libvirt_util.la
  CCLD     libvirt_conf.la
  CCLD     libvirt_cpu.la
/nix/store/7fi5j0hhb60arwrjk3cvl3ai6g7kydza-cctools-port-862/bin/ranlib: file: .libs/libvirt_util.a(libvirt_util_la-viratomic.o) has no symbols
ranlib: file: .libs/libvirt_util.a(libvirt_util_la-viratomic.o) has no symbols
  CCLD     libvirt_driver_test.la
  CCLD     libvirt-net-rpc-client.la
  CCLD     libvirt-net-rpc-server.la
  CCLD     libvirt-net-rpc.la
  CCLD     libvirt_driver_phyp.la
  CCLD     libvirt_driver_vmware.la
  CCLD     libvirt_driver_esx.la
  CCLD     libvirt_security_manager.la
  CCLD     libvirt_driver_access.la
  CCLD     lockd.la
  CCLD     libvirt_driver_vbox_impl.la
  CCLD     libvirt_driver.la
  CCLD     libvirt_driver_qemu_impl.la
  CCLD     libvirt_driver_secret.la
  CCLD     libvirt_driver_storage_impl.la
  CCLD     libvirt_iohelper
  CCLD     virtlockd
  CCLD     virtlogd
  CCLD     libvirt_driver_remote.la
  CCLD     libvirt_vmx.la
Undefined symbols for architecture x86_64:
  "_xdr_uint64_t", referenced from:
      _xdr_virLogManagerProtocolLogFilePosition in virtlogd-log_protocol.o
      _xdr_virLogManagerProtocolDomainOpenLogFileRet in virtlogd-log_protocol.o
      _xdr_virLogManagerProtocolDomainGetLogFilePositionRet in virtlogd-log_protocol.o
      _xdr_virLogManagerProtocolDomainReadLogFileArgs in virtlogd-log_protocol.o
ld: symbol(s) not found for architecture x86_64
clang-3.7: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by nckx** [comment]
Oh for the... OK, I lol'd.

Still, sorry 'bout that. I'd gladly try to fix it if I knew anything about Darwin. Is that something that can be fixed or is it reversion time?

**Comment by copumpkin** [comment]
I wouldn't revert it since I doubt anyone uses it on darwin today. If you have any obvious solutions to my problem, I'd appreciate hints, but otherwise I'll dig in and fix it when I have some time.

**Comment by nckx** [comment]
@wido: just for the record: `libvirt` and `pythonPackages.libvirt` versions should always match. Fixed in https://github.com/NixOS/nixpkgs/commit/b4c0495435564d2958de874fa0479e3edbf4015b.

**Comment by copumpkin** [comment]
Thanks!

**Pull request merged**
