### PR TITLE
Slither analyzer

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Motivation for this change

https://github.com/NixOS/nixpkgs/pull/101873#issuecomment-722622599

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102966` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python37Packages.crytic-compile</li>
    <li>python37Packages.slither-analyzer</li>
    <li>python38Packages.crytic-compile</li>
    <li>slither-analyzer (python38Packages.slither-analyzer)</li>
  </ul>
</details>

**Comment by fare** [comment]
LGTM

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102966` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python37Packages.slither-analyzer</li>
    <li>slither-analyzer (python38Packages.slither-analyzer)</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python37Packages.crytic-compile</li>
    <li>python38Packages.crytic-compile</li>
  </ul>
</details>

**Review by jonringer — APPROVED** [review]
LGTM

failures are broken on target branch
```
https://github.com/NixOS/nixpkgs/pull/102966
2 packages failed to build:
python37Packages.slither-analyzer slither-analyzer

2 packages built:
python37Packages.crytic-compile python38Packages.crytic-compile
```

**Pull request merged**
