### PR TITLE
factorio: 0.12.29 -> 0.12.33

### PR DESCRIPTION
**Pull request by elitak**
No functional changes; just tried to make the derivation-split more readable.

Then I bumped the hashes and version to actual release's.

### CODE REVIEW

**Comment by zimbatm** [comment]
Looking good.

Can you rename the `factorio: bump to 0.12.33` commit to follow our naming conventions. The commit should be `factorio: 0.12.29 -> 0.12.23`. Otherwise it's all legit.

**Comment by joachifm** [comment]
@elitak note that changing the PR title does not affect the commit subject.

**Comment by elitak** [comment]
Haha, looks like i just replaced the first thing i saw and called it a day. I'll resubmit this later, because I discovered that this version is actually an intermediate weekly one, and this package should probably track only the major releases.

Sorry for the trouble.

**Comment by joachifm** [comment]
@elitak oh, I've already pushed this, with a fixed commit subject

**Comment by elitak** [comment]
Okay, that should be no problem really. I don't think this has too many users and those users are probably experienced enough to override the version to their needs.

**Comment by joachifm** [comment]
What I mean is, this PR has been integrated, I only fixed the commit subject.

**Comment by elitak** [comment]
Yeah, everything's good. I'm pretty sure these minor releases are compatible across the network anyway. Thanks.

**Pull request closed without merging**
