### PR TITLE
nextcloud: 16.0.5 -> 17.0.0

### PR DESCRIPTION
**Pull request by cw789**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @schneefux @bachp @globin @fpletz

### CODE REVIEW

**Comment by cw789** [comment]
It currently breaks my installation as the apps won't work anymore.
Of every app `.../appinfo/info.xml` `min-version` needs to be at lest 16 - doesn't work it if it 17.

**Comment by globin** [comment]
This PR is conflicting, could you please rebase?

**Comment by cw789** [comment]
> 
> 
> This PR is conflicting, could you please rebase?

Should be ok now.

PS: The thing with the non working apps I think was to due having maintenance mode set during my update.

**Comment by globin** [comment]
Nope seems something went wrong

**Comment by cw789** [comment]
Sorry, my fault.

**Comment by dtzWill** [comment]
Please always look at the deployment notes, they change in minor ways across major updates.  Here's what I ended up with for updating the NixOS module: f422c754042fde9f55c6c19be278605b8cd708bc .

**Pull request merged**
