### PR TITLE
Revert "nodejs-16_x: 16.5.0 -> 16.6.0"

### LINKED ISSUE #132533: nodejs 16.6 fails to build on darwin
trying to build nodejs 16.6 on darwin I get the following error

```
In file included from ../deps/v8/src/libplatform/tracing/trace-writer.cc:14:
../deps/v8/src/libplatform/tracing/recorder.h:17:10: fatal error: 'os/signpost.h' file not found
#include <os/signpost.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [tools/v8_gypfiles/v8_libplatform.target.mk:159: /private/tmp/nix-build-nodejs-16.6.0.drv-0/n
rm 2e0eb71b1e97d7e96d4a06b54146ae6d4d2eb9d0.intermediate
make: *** [Makefile:110: node] Error 2
```

This error seems to be fixed by adding `darwin.Libsystem` as a buildinput.

however trying to build after that I get another error

```
In file included from /nix/store/znv06z6pld0ivwddj52rishggwc2m94c-libcxx-7.1.0-dev/include/c++/v1/__hash_table:19:
/nix/store/znv06z6pld0ivwddj52rishggwc2m94c-libcxx-7.1.0-dev/include/c++/v1/cmath:321:9: error: no member named 'isless' in the global namespace
using ::isless;
      ~~^
/nix/store/znv06z6pld0ivwddj52rishggwc2m94c-libcxx-7.1.0-dev/include/c++/v1/cmath:322:9: error: no member named 'islessequal' in the global namespace
using ::islessequal;
      ~~^
/nix/store/znv06z6pld0ivwddj52rishggwc2m94c-libcxx-7.1.0-dev/include/c++/v1/cmath:323:9: error: no member named 'islessgreater' in the global namespace
using ::islessgreater;
      ~~^
/nix/store/znv06z6pld0ivwddj52rishggwc2m94c-libcxx-7.1.0-dev/include/c++/v1/cmath:324:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
/nix/store/znv06z6pld0ivwddj52rishggwc2m94c-libcxx-7.1.0-dev/include/c++/v1/cmath:325:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
13 errors generated.
```

which I think is coming from the warning
`WARNING: C++ compiler (CXX=clang++, 7.1.0) too old, need g++ 8.3.0 or clang++ 8.0.0`

darwin is still on llvm 7. There is an effort at the moment to update it to llvm 11, but it might take some more time.

I don't understand how to fix the c++ compiler version. Should it not be fixed to something higher than 7 rather than relying on the default stdenv one?

@gilligan @cko @marsam 

I'm happy to test whatever ideas you have

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by marsam**
Node.js 16.6.0 fails to build on Darwin

Fixes https://github.com/NixOS/nixpkgs/issues/132533

This reverts commit f5de4158dd462c51741ec48be2e47a3f8015930d.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
Thank you for this!

I'm tempted to just merge this, I don't know if you want to get the feedback of more people.

**Comment by mohe2015** [comment]
I don't like this as this is a critical security release.

**Comment by SuperSandro2000** [comment]
Could we use the older version only on darwin?

**Comment by mohe2015** [comment]
https://nodejs.org/en/blog/vulnerability/july-2021-security-releases-2/

Unfortunately it doesn't seem like patches are available and no minor release either

**Comment by mohe2015** [comment]
I would be fine with adding that patch.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 132656` at c73d1006 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages skipped due to time constraints:</summary>
  <ul>
    <li>lumo</li>
    <li>nodejs-16_x (nodejs_latest)</li>
  </ul>
</details>
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>nodejs-slim-16_x (nodejs-slim_latest)</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/name-and-version.md">name-and-version</a>

Did you mean to pass `pname` instead of `name` to `mkDerivation`?

Near pkgs/development/web/nodejs/nodejs.nix:48:5:
```
   |
48 |     name = "${baseName}-${version}";
   |     ^
```

Near pkgs/development/web/nodejs/nodejs.nix:46:12:
```
   |
46 |     inherit version;
   |            ^
```
</li>
  </ul>
</details>

**Pull request merged**
