### PR TITLE
spotifyd: 0.3.4 -> 0.3.5

### PR DESCRIPTION
**Pull request by marsam**
###### Description of changes
https://github.com/Spotifyd/spotifyd/releases/tag/v0.3.5

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by georgefst** [comment]
Slightly off-topic, but is there a reason we don't enable `withMpris` by default? It's a very useful feature.

(Embarrassingly, [I don't even know how to override it](https://discourse.nixos.org/t/passing-flake-arguments-to-nixpkgs-package/27496).)

**Review by anderslundstedt — COMMENTED** [review]
Currently have no NixOS machine with sound, neither a Linux one with nixpkgs installed. Builds on Mac OS, but I get the following error:

```
error sending packet Os { code: 65, kind: HostUnreachable, message: "No route to host" }
```

I get the same error with 0.3.4 (from unstable) and with 0.3.3 (from stable) so I guess this is due to some config problem for me. Perhaps relevant:

https://github.com/Spotifyd/spotifyd/issues/1026

The official builds all crashes for me so I cannot compare with them.

Sorry, that I cannot provide a more informed review.

**Comment by marsam** [comment]
Sorry for the delay, I totally forgot about this PR
>but is there a reason we don't enable withMpris by default? 

I think there is none. I've enabled mpris by default.

>Builds on Mac OS, but I get the following error:

I tested it on Darwin. I think you forgot to start spotifyd with your credentials.

**Comment by georgefst** [comment]
> I think there is none. I've enabled mpris by default.

Thanks!

**Comment by anderslundstedt** [comment]
> > Builds on Mac OS, but I get the following error:
> 
> I tested it on Darwin. I think you forgot to start spotifyd with your credentials.

Indeed, with credentials supplied it works. But since it works also without credentials for me running the official builds on non-nix machines¹ I would consider this a bug if not:
- for some reason it is always necessary to supply credentials on Mac OS, even with official builds of spotifyd (as mentioned and explained in my previous post on this, I cannot test this); and
- nixpkgs-supplied spotifyd works without credentials on Linux.

(Since I no longer use nixpkgs-supplied spotifyd I will not investigate this further, nor open an issue—it is a non-issue for me—but perhaps this information will be of help to someone sometime.)

¹ Currently I use the official spotifyd builds on two Raspberry Pis: the armv6 build on a Pi 1 Model B Rev 2 and the armhf build on a Pi 3 Model B+ Rev 1.3. On both of these spotifyd does not need credentials but runs in “discovery mode” (which is convenient if you want guests to be able to connect). Relevant log from the systemd service startup:

```
May 11 16:56:19 rpi1b-rev2 spotifyd[462]: No config file specified. Running with default values
May 11 16:56:19 rpi1b-rev2 spotifyd[462]: No username specified. Checking username_cmd
May 11 16:56:19 rpi1b-rev2 spotifyd[462]: No username_cmd specified
May 11 16:56:19 rpi1b-rev2 spotifyd[462]: No password specified. Checking password_cmd
May 11 16:56:19 rpi1b-rev2 spotifyd[462]: No password_cmd specified
May 11 16:56:19 rpi1b-rev2 spotifyd[462]: No proxy specified
May 11 16:56:19 rpi1b-rev2 spotifyd[462]: Using software volume controller.
May 11 16:56:19 rpi1b-rev2 spotifyd[462]: no usable credentials found, enabling discovery
```

**Pull request merged**
