### PR TITLE
cargo,rustc: 1.75.0 -> 1.76.0

### PR DESCRIPTION
**Pull request by alyssais**
## Description of changes

Built:

- [x] fd aarch64-linux
- [x] fd x86_64-linux
- [x] fd x86_64-darwin (help wanted!)
- [x] thunderbird x86_64-linux
- [x] firefox x86_64-linux
- [x] rust-out-of-tree-module (both 6.7 and 6.8-rc4; cross aarch64-linux → x86_64-linux) 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Ma27 — APPROVED** [review]
LGTM.

Even managed to get the VM tests for kernel with Rust building by cherry-picking ruff 0.2.2 and disabling all tests in python3.pkgs.eventlet.

**Review by drupol — COMMENTED** [review]
PR LGTM, but the CI is broken, are we supposed to merge it as-is?

**Comment by alyssais** [comment]
> PR LGTM, but the CI is broken, are we supposed to merge it as-is?

There's nothing we can do about OfBorg timing out a build halfway through (which is what's gone wrong with 3/4 of the OfBorg builds).  For the x86_64-linux failure, I've tested it locally.

Usually we test fd on x86_64-darwin before merging a Rust update, but nobody has done that yet.  (And we can't do it on OfBorg because OfBorg is not capable of building LLVM for Darwin before timing out, at all, so OfBorg isn't generally usable for Darwin on staging.)

**Comment by Ma27** [comment]
> Usually we test fd on x86_64-darwin before merging a Rust update

I'm wondering, is there any trivial way to do that from an aarch64-linux mac? I have a mac from my new workplace, but I'm not very much into the ecosystem, so if that's reasonable somehow, pointers would be appreciated.

**Comment by zowoq** [comment]
Build fd on x86_64-darwin.

**Comment by vcunat** [comment]
I see relatively lots of packages failing to build with
> the parameter type `T` may not live long enough

For example, `hmm`: https://hydra.nixos.org/build/251973802

**Comment by vcunat** [comment]
Uh, why the hell are things like ["unused import"](https://hydra.nixos.org/build/251985373/nixlog/30/tail) a hard error in nixpkgs?  That might be for some strict upstream CI but not here/default.

**Comment by winterqt** [comment]
It's not.

This happened because [`Result::inspect_err` became stable in this release](https://doc.rust-lang.org/stable/std/result/enum.Result.html#method.inspect_err), which [`dim` defines their own version of](https://github.com/Dusk-Labs/dim/blob/3ccb4ab05fc1d7dbd4ebbba9ff2de0ecc9139b27/dim-core/src/inspect.rs#L2), despite [being warned against it](https://github.com/Dusk-Labs/dim/blob/3ccb4ab05fc1d7dbd4ebbba9ff2de0ecc9139b27/dim-core/src/scanner/movie.rs#L1).

The new version of rustc is saying "oh, you're using the new standard `Result::inspect_err`, so your custom version of it is unused, thus it warns against that. But because the project is set to [fail to compile on warnings](https://github.com/Dusk-Labs/dim/blob/3ccb4ab05fc1d7dbd4ebbba9ff2de0ecc9139b27/dim-core/src/lib.rs#L22), it blows up when using any rustc version past 1.76.0.

**Pull request merged**
