### PR TITLE
pjsip: 2.10 -> 2.11.1

### PR DESCRIPTION
**Pull request by linsui**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 140436` at 562f4383 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>ring-daemon</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/151fb47562dfc852fdcf2ec915242a8c">mumsi</a></li>
    <li><a href="https://gist.github.com/79e424f4f7be549d0b1c66f5f69ce5fe">pjsip</a></li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by hax404** [comment]
This merge broke mumsi.
@SuperSandro2000 @dasJ

**Comment by dasJ** [comment]
I think you pinged the wrong person ;)

**Comment by dasJ** [comment]
Oh wait I'm the mumsi maintainer, am I not?

**Comment by dasJ** [comment]
Well looks like that Mumsi is unmaintained anyway: https://github.com/slomkowski/mumsi/commit/961b75792f8da22fb5502e39edb286e32172d0b0

**Comment by SuperSandro2000** [comment]
> Oh wait I'm the mumsi maintainer, right?

😂 yeah you are.

Can we remove it?

**Pull request merged**
