### PR TITLE
evil-winrm: fix build, updated all dependencies, fixes StringIO issue

### PR DESCRIPTION
**Pull request by SanderShark**
## Things done

Just changed out the version of StringIO in the gemset as it was not building correct without.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by D3vil0p3r — APPROVED** [review]

**Comment by kirillrdy** [comment]
@SanderShark greetings, can you please update commit message to match contribution guidelines.

https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions

**Comment by SanderShark** [comment]
@kirillrdy should be all set now. Will make sure i use the formatting moving forwards

**Comment by kirillrdy** [comment]
hi @SanderShark , there is a spelling mistake in commit message.

may I suggest to change commit to something like `evil-winrm: fix build, updated stringio dependency` ( or something similar )

**Review by SanderShark — COMMENTED** [review]
Don't know how I missed the spelling mistake... Thank you for helping me, been a long day hah.

**Comment by kirillrdy** [comment]
commit message also needs to be updated

**Comment by SanderShark** [comment]
Some how missed the most important part that time in a sense. Welp here's hoping i didn't biff anything else this time

**Comment by kirillrdy** [comment]
@SanderShark darwin build fails due to ffi compilation issue ( as per https://github.com/NixOS/nixpkgs/pull/345974/checks?check_run_id=31112179751 )

updating ffi fixes the issue,

using something like this https://github.com/NixOS/nixpkgs/commit/345f39cf2bba61369ee43480f169a4e4dc77758c

```
 uname -a
Darwin admins-iMac-Pro.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul 31 21:42:48 PDT 2024; root:xnu-8796.141.3.707.4~1/RELEASE_X86_64 x86_64
admin@admins-iMac-Pro nixpkgs % ./result/bin/evil-winrm 
                                        
Evil-WinRM shell v3.5
                                        
Error: missing argument: ip, user

Usage: evil-winrm -i IP -u USER [-s SCRIPTS_PATH] [-e EXES_PATH] [-P PORT] [-p PASS] [-H HASH] [-U URL] [-S] [-c PUBLIC_KEY_PATH ] [-k PRIVATE_KEY_PATH ] [-r REALM] [--spn SPN_PREFIX] 
```

**Comment by D3vil0p3r** [comment]
@SanderShark can you fix please:
```
pkgs/tools/security/evil-winrm/Gemfile.lock:
	Wrong line endings or new final newline
pkgs/tools/security/evil-winrm/gemset.nix:
	Wrong line endings or new final newline
```

**Comment by SanderShark** [comment]
@D3vil0p3r All set on that, pushed that and walked away earlier today, hoped that closing my laptop would make it work and turns out it did. 

@kirillrdy I just added all those dep version updates to this as well, I had originally done that but when I went to do the test build locally I ended up just changing the one in error. Hopefully this was the better way to go

**Comment by SanderShark** [comment]
Just pushed it again to update the message and title

**Review by kirillrdy — APPROVED** [review]
thank you for the fix

**Pull request merged**
