### PR TITLE
nixos/wireless: make wireless.interfaces mandatory

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Motivation for this change

This is the only way to solve issue #101963, for now.

###### Things done

- [x] Tested in 21.05
- [x] Built manual 
- [x] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rnhmjoj** [comment]
@jonringer Is updating the release notes after the release acceptable?

**Comment by jonringer** [comment]
I would say it's okay.

I guess it's better to fail fast, so I'm okay backporting these changes as well

**Comment by rnhmjoj** [comment]
Ok, thank you. I'm merging now.

**Comment by Izorkin** [comment]
There are no wireless interfaces on the server. An error occurs while the system is rebuilding:
```
Failed assertions:
- No network interfaces for wpa_supplicant have been configured.
Please, specify at least one using networking.wireless.interfaces.

```

**Comment by rnhmjoj** [comment]
@Izorkin This assertion is behind a gate `networking.wireless.enable`. Are you sure it's not enabled somewhere in your configuration?

**Comment by Izorkin** [comment]
Checked, there is no parameter  `networking.wireless.enable`

**Comment by rnhmjoj** [comment]
Maybe you have imported a file that enables it, like `nixos/modules/profiles/installation-device.nix`. Also try setting `networking.wireless.enable = lib.mkForce default;`.

**Comment by Izorkin** [comment]
Thanks, found here:
```
{ pkgs, ... }:
let
  netboot = import (pkgs.path + "/nixos/lib/eval-config.nix") {
      modules = [
        (pkgs.path + "/nixos/modules/installer/netboot/netboot-minimal.nix")
        module
      ];
    };
...
```

**Pull request merged**
