### PR TITLE
haskell.packages.ghcjs: fix entropy

### PR DESCRIPTION
**Pull request by Profpatsch**

### CODE REVIEW

**Comment by rvl** [comment]
How does entropy work on ghcjs? Wouldn't it need to `foreign import javascript` something?

**Comment by Profpatsch** [comment]
No idea, really. It was broken and that made it compile, I haven’t used it for anything.

**Comment by rvl** [comment]
OK fair enough :thumbsup:. I guess it will fail trying to open `/dev/urandom`. I also had this package dragged in as a dependency, so this build fix will be helpful.

**Comment by Profpatsch** [comment]
Oh, all the nice surprises we are going to have with ghcjs. <3 ;)

**Pull request merged**
