### PR TITLE
iosevka: use buildNpmPackage

### PR DESCRIPTION
**Pull request by lunik1**
###### Description of changes

Following from #213243, this PR aims to use `buildNpmPackage` for `iosevka`. ~~In the process, it updates `iosevka` from 15.6.3 to 17.1.0.~~

Hopefully this should make keeping Iosevka up-to-date a little less ardous and we won't have to regenerate `node-packages.nix`.

@cstrahan @jfrankenau @ttuegel @babariviere @rileyinman @AluisioASG @mweinelt @winterqt 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lunik1** [comment]
I have split the commit. To avoid the version change being introduced here, #213243 can be merged first and then I'll rebase.

I have removed `iosevka` from `node-packages.json`, but not regenerated. Would that be necessary?

**Comment by DamienCassou** [comment]
@lunik1 Thanks a lot for taking the time to split your commit. This is so much easier to review now. Everything looks good to me.

I don't feel confident enough on the buildNpmPackage changes to merge the PR myself.

**Comment by mweinelt** [comment]
There is not much to it. Read through https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/javascript.section.md#buildnpmpackage-javascript-buildnpmpackage, compare the before/after output, check for functionality, that we don't ship the whole build tooling.

**Review by ttuegel — APPROVED** [review]
Thanks so much for taking care of this! :smiley:

**Comment by veehaitch** [comment]
Thanks for the effort! Please also make sure that `iosevka` continues to build on Darwin (see log [here](https://github.com/NixOS/nixpkgs/pull/213481/checks?check_run_id=11017580080)).

**Comment by winterqt** [comment]
@ttuegel *Please* check OfBorg statuses before merging, it shows that the [Darwin build failed](https://github.com/NixOS/nixpkgs/pull/213481/checks?check_run_id=11017580080).

Additionally, you merged a merge commit into master... please don't do this, [prefer rebases](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#writing-good-commit-messages).

**Comment by ttuegel** [comment]
I'm sorry. I'll be more attentive in the future.

**Pull request merged**
