### PR TITLE
erlang R18-20: updates

### PR DESCRIPTION
**Pull request by dtzWill**
Noticed various updates available, thought I'd submit bumps :).

Also forces rebuild which may be significant re:testing
and hopefully fixing #https://github.com/NixOS/nixpkgs/issues/36853.

Not sure how folks generally test erlang, I defer to your wisdom!

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
cc code owner @gleber (no rush!).

**Comment by gleber** [comment]
I'm on vacations, will try to look. Latest on Sunday

**Review by gleber — APPROVED** [review]

**Comment by gleber** [comment]
@grahamc  Graham, any ideas why ofborg did not mention me on this PR automatically?

**Comment by LnL7** [comment]
@GrahamcOfBorg build erlangR18 erlangR19 erlangR20

**Comment by gleber** [comment]
@LnL7 Both failures seem to be timeouts. Nothing else suspicious happening there as far as I can see

**Comment by LnL7** [comment]
Indeed, tested everything locally.

**Review by LnL7 — APPROVED** [review]

**Comment by LnL7** [comment]
Are these ok to backport?

**Comment by gleber** [comment]
@LnL7 These are minor version bumps only and Erlang is really good with backward-compatibility, I am no aware of any reasons not to backport.

**Comment by LnL7** [comment]
I thought so, just wanted to make sure. f9245e3e8021

**Pull request merged**
