### PR TITLE
pythonPackages.fontmath: 0.7.0 -> 0.8.0

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Motivation for this change

Tested on `x86_64-linux`:

```
/nix/store/bcgvapk6hyiiakjzfk5pcn9ggvjiwssd-liberation-fonts-2.1.0
/nix/store/k4wir8q8v5pnjcsxrqjbxviv1n5dimn9-liberation-fonts-1.07.5
/nix/store/vpxxkph3999n79n2wgm1r308cv22p4yl-noto-fonts-emoji-2020-09-16-unicode13.1
/nix/store/0jj8ipa3knks45qsw3difpf34am94dg2-scfbuild-1.0.3
/nix/store/c2i6a9aqxkcmbnwgfl5l75qbzyy552v7-twitter-color-emoji-13.0.2
/nix/store/w08sgvf77fhirc2vf9afdsn013y7a97n-rictydiminished-with-firacode-1.2.2
/nix/store/gwirzkqdwms39ga1rqk09fjjj8fi4lyr-liberation-sans-narrow-1.07.6
/nix/store/7m8yv390xzya1x487cz5aivn0pg8y5j4-visidata-2.4
```

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
@ofborg build python3Packages.fontmath

**Comment by jonringer** [comment]
do you mind rebasing on top of `python-unstable`?
```
builder for '/nix/store/y4asdnw62vvxcfsxfgrnynhdyf1hxmci-python3.9-Faker-6.6.3.drv' failed with exit code 1; last 10 log lines:
    File "/nix/store/37mfsqv7yqdikbkhy76iczlxp7nkpfqs-python3.9-Faker-6.6.3/lib/python3.9/site-packages/faker/utils/loading.py", line 35, in <listcomp>
      return [name for _, name, is_pkg in pkgutil.iter_modules([path]) if is_pkg]
    File "/nix/store/9qcqx6s645q8hri8i4ygj2s429w3nqw8-python3-3.9.5/lib/python3.9/pkgutil.py", line 130, in iter_modules
      for i in importers:
    File "/nix/store/9qcqx6s645q8hri8i4ygj2s429w3nqw8-python3-3.9.5/lib/python3.9/pkgutil.py", line 420, in get_importer
      importer = path_hook(path_item)
    File "<frozen importlib._bootstrap_external>", line 1601, in path_hook_for_FileFinder
    File "<frozen importlib._bootstrap_external>", line 1476, in __init__
    File "<frozen importlib._bootstrap_external>", line 177, in _path_isabs
  AttributeError: 'PosixPath' object has no attribute 'startswith'
```

should be fixed.

**Comment by sternenseemann** [comment]
Done!

**Comment by sternenseemann** [comment]
@ofborg build python3Packages.fontmath python3Packages.afdko

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 128763 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>14 packages built:</summary>  <ul>    <li>noto-fonts-emoji</li>    <li>python38Packages.afdko</li>    <li>python38Packages.fontmath</li>    <li>python38Packages.fontparts</li>    <li>python38Packages.mutatormath</li>    <li>python38Packages.nototools</li>    <li>python38Packages.ufoprocessor</li>    <li>python39Packages.afdko</li>    <li>python39Packages.fontmath</li>    <li>python39Packages.fontparts</li>    <li>python39Packages.mutatormath</li>    <li>python39Packages.nototools</li>    <li>python39Packages.ufoprocessor</li>    <li>twitter-color-emoji</li>  </ul></details>

**Pull request merged**
