### PR TITLE
nvidia_x11: 460.73.01 -> 470.57.02

### LINKED ISSUE #129233: Latest nvidia driver doesn't compile
**Describe the bug**
With the latest kernel and the latest non-beta nvidia driver, the drivers don't compile:
```
error: builder for '/nix/store/wv00lqc6ynx5bhhv31vaixaz867a9vfb-nvidia-x11-460.73.01-5.13.drv' failed with exit code 2;
       last 10 log lines:
       > make[3]: *** Waiting for unfinished jobs....
       > /build/kernel/nvidia-drm/nvidia-drm-modeset.c: In function '__will_generate_flip_event':
       > /build/kernel/nvidia-drm/nvidia-drm-modeset.c:96:23: warning: unused variable 'primary_plane' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wunused-variable-Wunused-variable8;;]
       >    96 |     struct drm_plane *primary_plane = crtc->primary;
       >       |                       ^~~~~~~~~~~~~
       > make[2]: *** [/nix/store/0l90igcsgvmq2z69ia6n4dalvln2h81w-linux-5.13-dev/lib/modules/5.13.0/source/Makefile:1847: /build/kernel] Error 2
       > make[2]: Leaving directory '/nix/store/0l90igcsgvmq2z69ia6n4dalvln2h81w-linux-5.13-dev/lib/modules/5.13.0/build'
       > make[1]: *** [Makefile:215: __sub-make] Error 2
       > make[1]: Leaving directory '/nix/store/0l90igcsgvmq2z69ia6n4dalvln2h81w-linux-5.13-dev/lib/modules/5.13.0/source'
       > make: *** [Makefile:80: modules] Error 2
       For full logs, run 'nix log /nix/store/wv00lqc6ynx5bhhv31vaixaz867a9vfb-nvidia-x11-460.73.01-5.13.drv'.
error: 1 dependencies of derivation '/nix/store/gld36fh5sc69s3lw8rnpm701pbsxx67g-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/5qnd3i9k96nkxljjs6hpiq100k9ss1m6-linux-5.13-modules.drv' failed to build
error: 1 dependencies of derivation '/nix/store/11y6fqa7ygg9bbr9mf2rq61ciq6dyzk1-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/l29n869335p9xfyvcaqbjgqwc8pkcwl5-nixos-system-dracula-21.11.20210703.09c38c2.drv' failed to build
error: getting status of '/tmp/nixos-rebuild.v0uAIA/result': No such file or directory
```

**To Reproduce**
1. use unstable
2. use the latest linux kernel
3. add nvidia as a drivers

**Expected behavior**
It should compile.

**Notify maintainers**
Latest person who touched it: @ronthecookie 

**Metadata**
```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.12, NixOS, 21.11.20210703.09c38c2 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `no` # also happens with it on, it has to be off for other reasons
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - channels(root): `""`
 - channels(nix): `""`
 - nixpkgs: `/nix/store/zy56rp0mfp7lx2xqcfzqcf9z82vph9pd-wsfwxm10shvi4yr0ll8p4v1dp7l7wqfl-source`
```

### PR DESCRIPTION
**Pull request by baracoder**
closes #129233

###### Motivation for this change

Stable driver release
https://www.nvidia.com/download/driverResults.aspx/177145/en-us
I did not test DLSS yet. There might be some additional handling of files required
http://us.download.nvidia.com/XFree86/Linux-x86_64/470.57.02/README/installedcomponents.html
eg `ibnvidia-ngx.so.470.57.02` or proton/wine specific dlls `nvngx.dll`

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Kranzes — APPROVED** [review]
Diff LGTM :+1:

**Comment by arcnmx** [comment]
:+1: I've been using this for a few days

**Comment by Technical27** [comment]
`nvngx.dll` and `_nvngx.dll` aren't installed, because the builder only installs libs ending in `.so`.
Those dlls should probably be installed to `$out/lib/wine` according to the nvidia documentation.

steam/lutris may need some additional changes to get features like DLSS working.

**Comment by andrevmatos** [comment]
Does suspend/resume work with this? It seems some `nvidia-sleep.sh` script is missing from recent driver releases?

**Review by fufexan — APPROVED** [review]

**Comment by bendlas** [comment]
this fixes https://github.com/NixOS/nixpkgs/issues/129233 for me

**Review by jakobrs — APPROVED** [review]
This fixes building nvidia_x11 on Linux 5.13 for me.

**Comment by andrevmatos** [comment]
This just broke suspend on systems with `hardware.nvidia.powerManagement.enable = true`
```
...
Jul 28 10:59:56 systemd[1]: Starting NVIDIA system suspend actions...
Jul 28 10:59:56 systemd[3431]: nvidia-suspend.service: Failed to locate executable /nix/store/mxpkr3i8nxhh6vjmlr29hlnmlkda30y4-nvidia-x11-470.57.02-5.13.5/bin/nvidia-sleep.sh: No such file or direct>
Jul 28 10:59:56 systemd[3431]: nvidia-suspend.service: Failed at step EXEC spawning /nix/store/mxpkr3i8nxhh6vjmlr29hlnmlkda30y4-nvidia-x11-470.57.02-5.13.5/bin/nvidia-sleep.sh: No such file or direc>
Jul 28 10:59:56 systemd[1]: Starting Pre-Sleep Actions...
Jul 28 10:59:56 systemd[1]: Starting TLP suspend/resume...
Jul 28 10:59:56 systemd[1]: nvidia-suspend.service: Main process exited, code=exited, status=203/EXEC
Jul 28 10:59:56 systemd[1]: nvidia-suspend.service: Failed with result 'exit-code'.
Jul 28 10:59:56 systemd[1]: Failed to start NVIDIA system suspend actions.
Jul 28 10:59:56 systemd[1]: Dependency failed for Suspend.
Jul 28 10:59:56 systemd[1]: Dependency failed for Suspend.
Jul 28 10:59:56 systemd[1]: suspend.target: Job suspend.target/start failed with result 'dependency'.
```

**Comment by dtzWill** [comment]
> `nvngx.dll` and `_nvngx.dll` aren't installed, because the builder only installs libs ending in `.so`.
> Those dlls should probably be installed to `$out/lib/wine` according to the nvidia documentation.
> 
> steam/lutris may need some additional changes to get features like DLSS working.

Thanks for catching this, came here for this.  Perhaps we should create an issue for this? I'm worried unless someone sees this (or happens to read the driver changelogs as I did) this will slip through the cracks indefinitely.   I don't know anything about what changes may or may not be needed in wine/steam/etc (as mentioned in the notes).

Also perhaps some brave soul might investigate this :grin:.

FWIW from the link above:

> NGX for Proton and Wine (/usr/lib/nvidia/wine/nvngx.dll); (/usr/lib/nvidia/wine/_nvngx.dll);
> 
> NGX for Proton and Wine is a Microsoft Windows dynamic-link library used by Microsoft Windows applications which support NVIDIA DLSS.
> 
> In addition to driver-side support, changes to third-party software are required in order to support DLSS within Proton and Wine.
> 

---

Anything else that we know is missing ?

**Pull request merged**
