### PR TITLE
Remove redundant -DCMAKE_BUILD_TYPE=Release flags

### PR DESCRIPTION
**Pull request by aneeshusa**
###### Motivation for this change

Cleanup I noticed while working on #17886.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Haven't built or tested yet.

### CODE REVIEW

**Comment by andrewrk** [comment]
Why is this flag redundant? AFAIK, the default cmake build is not `Release`.

**Comment by aneeshusa** [comment]
@andrewrk In `pkgs/development/tools/build-managers/cmake/setup-hook.sh`, `-DCMAKE_BUILD_TYPE=Release` is prepended to `cmakeFlags`, since a commit in 2012. AFAIK, this sets the default to `Release` (for derivations with `cmake` as a build input).

**Comment by andrewrk** [comment]
OK this sounds reasonable to me then.

**Comment by aneeshusa** [comment]
@andrewrk I updated the commit message with that info, thanks for pointing that out.

**Comment by Mic92** [comment]
Merged thanks!

**Pull request closed without merging**
