### PR TITLE
python3: improve cross-compilation of extension modules, fixes #91171

### LINKED ISSUE #91171: Python (distutils): Set LDSHARED for cross compilation
## Issue description

This would be a generic solution to fix cases like #91161.

Some information about this is e.g. [here](https://stackoverflow.com/questions/5986256/python-distutils-gcc-path) and there are possibly other relevant environment variables that we should set (e.g. the ones mentioned [here](https://github.com/easybuilders/easybuild-easyblocks/issues/1136)).

It also seems like we currently leak some invalid Nix store references into `LDSHARED`:
```console
michael@jarvis> python                                                                                                                                                                                            ~
Python 3.8.3 (default, May 13 2020, 19:59:26)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from distutils import sysconfig
>>> sysconfig.get_config_var('LDSHARED')
'gcc -pthread -shared -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-zlib-1.2.11/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-bzip2-1.0.6.0.1/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-expat-2.2.8/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-xz-5.2.5/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-libffi-3.3/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-gdbm-1.18.1/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-sqlite-3.32.2/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-readline-6.3p08/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ncurses-6.2/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-openssl-1.1.1g/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-zlib-1.2.11/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-bzip2-1.0.6.0.1/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-expat-2.2.8/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-xz-5.2.5/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-libffi-3.3/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-gdbm-1.18.1/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-sqlite-3.32.2/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-readline-6.3p08/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ncurses-6.2/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-openssl-1.1.1g/lib'
>>> sysconfig.get_config_var('CC')
'gcc -pthread'
```

Not sure if this is really intended.

### Steps to reproduce

E.g. cross compiling `python3Packages.pycryptodome` currently fails with:
```
aarch64-unknown-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DHAVE_STDINT_H -DPYCRYPTO_LITTLE_ENDIAN -DSYS_BITS=64 -DLTC_NO_ASM -DHAVE_UINT128 -DHAVE_POSIX_MEMALIGN -Isrc/ -I/nix/store/nnfpapxzrhib9gxpj26f0i5h0ww9rfwc-python3-3.7.7/include/python3.7m -c src/MD2.c -o build/temp.linux-x86_64-3.7/src/MD2.o
gcc -pthread -shared -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-zlib-1.2.11/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-bzip2-1.0.6.0.1/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-expat-2.2.8/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-xz-5.2.5/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-libffi-3.3/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-gdbm-1.18.1/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-sqlite-3.31.1/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-readline-6.3p08/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ncurses-6.2/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-openssl-1.1.1g/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-zlib-1.2.11/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-bzip2-1.0.6.0.1/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-expat-2.2.8/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-xz-5.2.5/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-libffi-3.3/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-gdbm-1.18.1/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-sqlite-3.31.1/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-readline-6.3p08/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ncurses-6.2/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-openssl-1.1.1g/lib build/temp.linux-x86_64-3.7/src/MD2.o -L/nix/store/nnfpapxzrhib9gxpj26f0i5h0ww9rfwc-python3-3.7.7/lib -o build/lib.linux-x86_64-3.7/Crypto/Hash/_MD2.cpython-37m-x86_64-linux-gnu.so
unable to execute 'gcc': No such file or directory
error: command 'gcc' failed with exit status 1
```

With #91161 it succeeds:
```
aarch64-unknown-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DHAVE_STDINT_H -DPYCRYPTO_LITTLE_ENDIAN -DSYS_BITS=64 -DLTC_NO_ASM -DHAVE_UINT128 -DHAVE_POSIX_MEMALIGN -Isrc/ -I/nix/store/nnfpapxzrhib9gxpj26f0i5h0ww9rfwc-python3-3.7.7/include/python3.7m -c src/MD2.c -o build/temp.linux-x86_64-3.7/src/MD2.o
aarch64-unknown-linux-gnu-gcc -shared build/temp.linux-x86_64-3.7/src/MD2.o -L/nix/store/nnfpapxzrhib9gxpj26f0i5h0ww9rfwc-python3-3.7.7/lib -o build/lib.linux-x86_64-3.7/Crypto/Hash/_MD2.cpython-37m-x86_64-linux-gnu.so
```

### PR DESCRIPTION
**Pull request by FRidh**
Fixes #91171.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
Should not do this for Darwin because I am pretty sure it will break then given the `python-3.x-distutils-C++.patch` and `pkgs/development/python-modules/pysqlite/default.nix`.

**Comment by FRidh** [comment]
Downside of this approach is that it only works in a `nix-build` or `nix-shell`.

**Comment by FRidh** [comment]
Upstream PR!
https://github.com/python/cpython/pull/7914

**Comment by Mic92** [comment]
> Downside of this approach is that it only works in a `nix-build` or `nix-shell`.

This is not really a regression compilers don't work outside the `nix-shell` anyway.

**Comment by FRidh** [comment]
Doesn't mean we need to enforce that shortcoming when we can avoid it.

**Comment by Mic92** [comment]
> Doesn't mean we need to enforce that shortcoming when we can avoid it.

It should be easy enough to whatever one wants to use instead of `nix-shell` to also just export LDSHARED, CC, and CXX accordingly.

**Comment by FRidh** [comment]
Exactly.

So, as it is now cross-compiling pycryptodome succeeds. I also tried btrfs-progs because it exports LDSHARED, but unfortunately that package fails to build with and without the patch in this PR.

**Comment by Mic92** [comment]
There is a report that btrfs-progs cross-compiles now as of https://github.com/NixOS/nixpkgs/issues/50925#issuecomment-647021226

**Comment by kvtb** [comment]
@GrahamcOfBorg build pkgsCross.aarch64-multiplatform.python3Packages.pycryptodome

**Pull request merged**
