### PR TITLE
jetbrains batch update

### PR DESCRIPTION
**Pull request by sonercirit**
Updated with update.pl, have not tested the packages.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Infinisil** [comment]
@GrahamcOfBorg build jetbrains.clion
@GrahamcOfBorg build jetbrains.datagrip
@GrahamcOfBorg build jetbrains.goland
@GrahamcOfBorg build jetbrains.idea-community
@GrahamcOfBorg build jetbrains.idea-ultimate
@GrahamcOfBorg build jetbrains.phpstorm
@GrahamcOfBorg build jetbrains.pycharm-community
@GrahamcOfBorg build jetbrains.pycharm-professional
@GrahamcOfBorg build jetbrains.ruby-mine
@GrahamcOfBorg build jetbrains.webstorm

**Comment by sonercirit** [comment]
@Infinisil seems like these tests won't run because of allowUnfree option.
```
a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnfree = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnfree = true; }
to ~/.config/nixpkgs/config.nix.
```

**Comment by Infinisil** [comment]
Yeah, but at least it did the builds for a couple of them (if you scroll down in the checks list at the bottom)

**Comment by sonercirit** [comment]
@Infinisil , @edwtjo  any updates on this?

**Comment by sonercirit** [comment]
also @c0bw3b since he merged the last one :)

**Review by c0bw3b — APPROVED** [review]
Result of `nix-review pr 61920` [1](https://github.com/Mic92/nix-review)
<details>
  <summary>10 package were build:</summary>

  - jetbrains.clion
  - jetbrains.datagrip
  - jetbrains.goland
  - jetbrains.idea-community
  - jetbrains.idea-ultimate
  - jetbrains.phpstorm
  - jetbrains.pycharm-community
  - jetbrains.pycharm-professional
  - jetbrains.ruby-mine
  - jetbrains.webstorm
</details>

**Pull request merged**
