### PR TITLE
nixos/gnome3: fix default background setting

### PR DESCRIPTION
**Pull request by jtojnar**
Fix the following error when opening Background panel in GNOME Settings:

    URI '/nix/store/…-simple-dark-gray-2016-02-19/share/artwork/gnome/nix-wallpaper-simple-dark-gray.png' is invalid

### CODE REVIEW

**Comment by worldofpeace** [comment]
Hmm, I see errors trying to load the grilo plugindir. Does gnome-control-center depend on grilo (not optionally)?

**Review by worldofpeace — APPROVED** [review]
Tested in a VM that the correct background appears and I don't see the error in mention appear in when launching `gnome-control-center`.

**Comment by jtojnar** [comment]
Hmm, apparently grilo miners are used for finding some backgrounds. I will take a look.

**Comment by jtojnar** [comment]
Apparently, there are no plugins in `grilo` package – everything is in `grilo-plugins`, so we need to add `grilo-plugins` to inputs.

**Comment by jtojnar** [comment]
Confirmed that it is possible to set wallpaper from Flickr account’s gallery when signed in Online Accounts.

**Review by worldofpeace — APPROVED** [review]
LGTM, don't see that warning for grilo anymore.

**Pull request merged**
