### PR TITLE
Add autochanger support to bacula-sd

### PR DESCRIPTION
**Pull request by wucke13**
+ Fixing interrupted descriptions
+ Added more verbose descriptions
+ Addded <literal> to the descriptions
+ uniformly reformated descriptions to break at 80 chars

(cherry picked from commit c7945c8a97df52a468cf32155154cdec021561bc)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @Lassulus

### CODE REVIEW

**Comment by Lassulus** [comment]
ah, the commit message needs to change, sadly I missed that on the other PR

**Comment by wucke13** [comment]
Updated this PR. Sorry.

**Review by Lassulus — APPROVED** [review]
LGTM
Edit: can we change the commit message to `nixos/bacula-sd: add autochange support`

**Review by Lassulus — CHANGES_REQUESTED** [review]
can we change the commit message to `nixos/bacula-sd: add autochange support`

**Comment by wucke13** [comment]
Sure, done.

**Pull request merged**
