### PR TITLE
vimPlugins.darkearth-nvim: init at 2024-07-19

### PR DESCRIPTION
**Pull request by ptdewey**
## Description of changes

Adds the [`darkearth`](https://github.com/ptdewey/darkearth-nvim) colorcheme for `vim`.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by PerchunPak** [comment]
Could you please add an entry to `generated.nix`? Just run `nix-build -A vimPluginUpdater && vim-plugins-updater -n
` and make sure to include only the changes related to this plugin. Also please remove unrelated changes.

Thanks!

**Comment by ptdewey** [comment]
@PerchunPak I will get the `generated.nix` added. In terms of the other changes that were made in the commit, I didn't remove or update anything manually, but I believe the `nix-shell -p vimPluginsUpdater --run vim-plugins-updater` command just sorted a couple of out-of-place plugins in the `vim-plugin-names` file. I can revert them to their previous places if necessary, but wouldn't it be better for them to be in the correct place to avoid dealing with this in the future? Thanks!

**Comment by ptdewey** [comment]
When running the updater `nix-shell -p vimPluginsUpdater --run vim-plugins-updater`, I am now also getting a 404 error resulting from the `andsild/peskcolor.vim` plugin, which appears to no longer exist on GitHub. 
```
HTTP Error 404: Not Found, Retrying in 3 seconds...
HTTP Error 404: Not Found, Retrying in 6 seconds...
HTTP Error 404: Not Found, Retrying in 12 seconds...
1475 plugins were checked, 1 plugin(s) could not be downloaded:

PluginDesc(repo=Repo(peskcolor.vim, https://github.com/andsild/peskcolor.vim/), branch='', alias=''): HTTP Error 404: Not Found
```

I'm going to open an issue about this error since the package may need to be removed.

**Comment by PerchunPak** [comment]
This is already being resolved in #336589, so just remove `peskcolor` from `vim-plugin-names` before running `vim-plugins-updater` and return it back before committing (to avoid conflicts).

> just sorted a couple of out-of-place plugins in the `vim-plugin-names` file

I am unsure what happened, maybe you have an older version of `vim-plugins-updater`, but running it using master gave me a different diff:

<details>
  <summary>diff</summary>
  
```diff
diff --git a/pkgs/applications/editors/vim/plugins/vim-plugin-names b/pkgs/applications/editors/vim/plugins/vim-plugin-names
index 64b5a4776d05..1a981283ba0a 100644
--- a/pkgs/applications/editors/vim/plugins/vim-plugin-names
+++ b/pkgs/applications/editors/vim/plugins/vim-plugin-names
@@ -200,8 +200,8 @@ https://github.com/tjdevries/colorbuddy.nvim/,,
 https://github.com/lilydjwg/colorizer/,,
 https://github.com/Domeee/com.cloudedmountain.ide.neovim/,HEAD,
 https://github.com/wincent/command-t/,,
-https://github.com/numtostr/comment.nvim/,,
 https://github.com/LudoPinelli/comment-box.nvim/,HEAD,
+https://github.com/numtostr/comment.nvim/,,
 https://github.com/rhysd/committia.vim/,,
 https://github.com/hrsh7th/compe-conjure/,,
 https://github.com/GoldsteinE/compe-latex-symbols/,,
@@ -239,6 +239,7 @@ https://github.com/FelikZ/ctrlp-py-matcher/,,
 https://github.com/amiorin/ctrlp-z/,,
 https://github.com/ctrlpvim/ctrlp.vim/,,
 https://github.com/scottmckendry/cyberdream.nvim/,,
+https://github.com/ptdewey/darkearth-nvim/,HEAD,
 https://github.com/dart-lang/dart-vim-plugin/,,
 https://github.com/rizzatti/dash.vim/,HEAD,
 https://github.com/glepnir/dashboard-nvim/,,
@@ -940,6 +941,7 @@ https://github.com/natecraddock/telescope-zf-native.nvim/,HEAD,
 https://github.com/jvgrootveld/telescope-zoxide/,,
 https://github.com/nvim-telescope/telescope.nvim/,,
 https://github.com/luc-tielen/telescope_hoogle/,HEAD,
+https://github.com/joerdav/templ.vim/,HEAD,
 https://github.com/axelvc/template-string.nvim/,HEAD,
 https://github.com/jacoborus/tender.vim/,,
 https://github.com/chomosuke/term-edit.nvim/,HEAD,
@@ -1480,4 +1482,3 @@ https://github.com/ziglang/zig.vim/,,
 https://github.com/mickael-menu/zk-nvim/,HEAD,
 https://github.com/troydm/zoomwintab.vim/,,
 https://github.com/nanotee/zoxide.vim/,,
-https://github.com/joerdav/templ.vim,HEAD,
```
</details>

If you really want to sort plugins, I think it is better to use my diff, as running `vim-plugins-updater add ...` on your PR resorts everything to above.

@ptdewey

**Comment by PerchunPak** [comment]
Looks like you accidentally pushed updates for all plugins. Also syntax check for some reason fails
@ptdewey

**Comment by ptdewey** [comment]
Yeah sorry about that, I'll work on resolving it.

**Comment by ptdewey** [comment]
I think I got everything squared away now, sorry for the issues and thanks for your help.

**Review by PerchunPak — APPROVED** [review]
> sorry for the issues and thanks for your help.

It's totally fine, don't worry

---

LGTM

CC @teto

**Pull request merged**
