### PR TITLE
Unity3D package

### PR DESCRIPTION
**Pull request by abbradar**
###### Motivation for this change

Another attempt at https://github.com/NixOS/nixpkgs/issues/10452. Now Unity fully works, but requires SUID binary and also a small C `LD_PRELOAD`ed library which hack-forces Unity to believe some things about `chrome-sandbox`. To use, enable it with `programs.unity3d.enable = true` and run `unity-editor`. Compiled games can be run with `steam-run`.

Further work would be to build `libcef` by ourselves to enable userns -- then Unity wouldn't require a SUID binary (and hence NixOS module).
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by abbradar** [comment]
After some testing (thanks @lolwat97) and fixing emerging issues it appears to be ready (at least basic scene, compilation and Asset Store are reported to work). Notice that MonoDevelop is split into a separate `unity3d.monodevelop` output which can be installed ordinarily (via `environmentPackages`, for example). Given that there were several persons interested in #10452 I suggest we move on and merge this. I'll do it in several days unless someone objects.

Current problems with building our own libcef: https://github.com/NixOS/nixpkgs/pull/15648#issuecomment-222320370. When it's resolved we can drop the NixOS service.

**Comment by jb55** [comment]
awesome! going to test this soon.

**Comment by AshSlave** [comment]
For me it works fine until I try to open a project. No matter what project I try, it loads for about half a minute, shows the editor window for a moment, then aborts.
[Editor.log.txt](https://github.com/NixOS/nixpkgs/files/295783/Editor.log.txt)

**Comment by abbradar** [comment]
Interesting. From the log it throws some exception and actually fails on trying to run a bug reporter tool. I'll try to fix it, but I don't know the cause of the actual NULL pointer exception -- looks like something inside of Unity...

**Comment by abbradar** [comment]
Sadly I had no luck fixing bug reporter for now -- I keep getting this after fixing Qt plugin path:
```
xkbcommon: ERROR: failed to add default include path auto
Qt: Failed to create XKB context!
Use QT_XKB_CONFIG_ROOT environmental variable to provide an additional search 
path, add ':' as separator to provide several search paths and/or make sure 
that XKB configuration data directory contains recent enough contents, to 
update please see http://cgit.freedesktop.org/xkeyboard-config/ .
```
No idea how to fix that!

**Comment by the-kenny** [comment]
I see similar behavior to @AshSlave - I can register and create a project just fine, but it crashes a minute or two after opening (after showing the unity ui for a split second). 

Anyone got an idea?

**Comment by AshSlave** [comment]
I figured that it happens with Nvidia proprietary drivers, but not with Nouveau. Though with Nouveau it doesn't that work well either. Didn't have time to investigate it further.

**Comment by the-kenny** [comment]
I'm actually on a Lenovo Thinkpad x260 with intel graphics. WIth `-force-opengl` it reports the following:

```
OpenGL:
    Version:  OpenGL 3.0 [3.0 Mesa 13.0.2]
    Renderer: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2)
    Vendor:   Intel Open Source Technology Center
    VRAM:     3072 MB
```

**Comment by tdroxler** [comment]
Hi, everything went fine with the rebuild and `programs.unity3d.enable = true` in my config file, but then I've got a `unity-editor: command not found` when trying to run it, did I miss something? thx

**Comment by AshSlave** [comment]
I think you also need to install unity3d package.

**Comment by tdroxler** [comment]
ahah seems you right :-) it works, thanks a lot

**Pull request merged**
