### PR TITLE
qtcreator-qt6: 9.0.2 -> 10.0.0

### PR DESCRIPTION
**Pull request by wineee**
###### Description of changes

https://www.qt.io/blog/qt-creator-10-released

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wineee** [comment]
wait qt 6.5.0

**Comment by wegank** [comment]
@ofborg build qtcreator-qt6 qtcreator-qt6.passthru.tests

**Comment by wineee** [comment]
QML language server plugin crashes frequently，Maybe https://github.com/NixOS/nixpkgs/pull/202223 can fix

**Comment by wineee** [comment]
How can I fetch qtcreator-qt6 build by ofborg ? I don't want to compile qtwebengine

**Comment by wegank** [comment]
You can't: NixOS/ofborg#68

Anyway, I think you can just revert the last commit on `qt6.qtwebengine` to get a functioning build from Hydra.

**Comment by wegank** [comment]
Any update on this PR?

**Comment by wineee** [comment]
Still haven't tested the situation under qt 6.5,  qtwebengine inevitably needs to be recompiled，qt6 packaging has changed a lot


Refer to the experience of Arch, there should be no need to adjust： https://github.com/archlinux/svntogit-packages/commit/6058cf5d5f09b6f0bc821d53c944ad8478475313

**Comment by wegank** [comment]
> Still haven't tested the situation under qt 6.5, qtwebengine inevitably needs to be recompiled，qt6 packaging has changed a lot

I believe `qt6.qtwebengine` has been built and cached on `cache.nixos.org`, and `nixpkgs-review` should work without rebuilding Qt. Maybe you just need to rebase locally?

**Comment by wineee** [comment]
image

Basically, LGTM

**Review by wegank — APPROVED** [review]

**Pull request merged**
