### PR TITLE
python3Packages.bitstring: 3.1.7 -> 3.1.9

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 3.1.9

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
This causes `chia` to fail on nixos x86_64:

```
ERROR: Could not find a version that satisfies the requirement bitstring==3.1.7 (from chia-blockchain)
ERROR: No matching distribution found for bitstring==3.1.7
```

**Comment by risicle** [comment]
...but doesn't produce any new failures on macos 10.15.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 130863` at 67402af7 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/de9f03275462d4d4dbc5343d5c8a3cb3">chia</a></li>
    <li><a href="https://gist.github.com/2f3883627a9cadcef2c6b61c38d7a935">python38Packages.ailment</a></li>
    <li><a href="https://gist.github.com/632c8fbd4b39cf9dd96933eea0d118ce">python38Packages.angr</a></li>
    <li><a href="https://gist.github.com/717b92cac8ca3fd86d585a7744d0e510">python38Packages.angrop</a></li>
    <li><a href="https://gist.github.com/a8ce3a2b9a80bc7db1e9d75de2190dd1">python38Packages.cle</a></li>
    <li><a href="https://gist.github.com/4953e38a93ec8ad7093bd157230dd6cd">python38Packages.pyvex</a></li>
    <li><a href="https://gist.github.com/874183a5b66acaf78f3eedeafb8c6dd2">python39Packages.ailment</a></li>
    <li><a href="https://gist.github.com/6bbc17e5a33c168c92c64d4a623159ac">python39Packages.angr</a></li>
    <li><a href="https://gist.github.com/4ba644d2ae05c708660578ddf2f6a0cb">python39Packages.angrop</a></li>
    <li><a href="https://gist.github.com/3602c6b16effe526b4688bb30bef6c9b">python39Packages.cle</a></li>
    <li><a href="https://gist.github.com/2fafbd94f3e9b277441ec8dafe38fd24">python39Packages.pyvex</a></li>
  </ul>
</details>
<details>
  <summary>1 package skipped due to time constraints:</summary>
  <ul>
    <li>electrum</li>
  </ul>
</details>
<details>
  <summary>11 packages built successfully:</summary>
  <ul>
    <li>cantoolz</li>
    <li>esptool</li>
    <li>opsdroid</li>
    <li>python38Packages.aiolifx</li>
    <li>python38Packages.aiolifx-effects</li>
    <li>python38Packages.bitstring</li>
    <li>python38Packages.pysml</li>
    <li>python39Packages.aiolifx</li>
    <li>python39Packages.aiolifx-effects</li>
    <li>python39Packages.bitstring</li>
    <li>python39Packages.pysml</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/no-python-tests.md">no-python-tests</a>

Test runner could not discover any test cases: ‘Ran 0 tests in 0.000s’
Near pkgs/development/python-modules/bitstring/default.nix:13:0:
```
   |
13 |     description = "Module for binary data manipulation";
   | ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by fabaff** [comment]
`angr` stack update: https://github.com/NixOS/nixpkgs/pull/131139

**Comment by Artturin** [comment]
> This causes `chia` to fail on nixos x86_64:
> 
> ```
> ERROR: Could not find a version that satisfies the requirement bitstring==3.1.7 (from chia-blockchain)
> ERROR: No matching distribution found for bitstring==3.1.7
> ```

https://github.com/Chia-Network/chia-blockchain/pull/7676

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 130863` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages failed to build:</summary>
  <ul>
    <li>chia</li>
    <li>python38Packages.ailment</li>
    <li>python38Packages.angr</li>
    <li>python38Packages.angrop</li>
    <li>python38Packages.cle</li>
    <li>python38Packages.pyvex</li>
    <li>python39Packages.ailment</li>
    <li>python39Packages.angr</li>
    <li>python39Packages.angrop</li>
    <li>python39Packages.cle</li>
    <li>python39Packages.pyvex</li>
  </ul>
</details>
<details>
  <summary>13 packages built:</summary>
  <ul>
    <li>cantoolz</li>
    <li>electrum</li>
    <li>esphome</li>
    <li>esptool</li>
    <li>opsdroid</li>
    <li>python38Packages.aiolifx</li>
    <li>python38Packages.aiolifx-effects</li>
    <li>python38Packages.bitstring</li>
    <li>python38Packages.pysml</li>
    <li>python39Packages.aiolifx</li>
    <li>python39Packages.aiolifx-effects</li>
    <li>python39Packages.bitstring</li>
    <li>python39Packages.pysml</li>
  </ul>
</details>

**Pull request merged**
