### PR TITLE
qt515: Update KDE Qt 5.15 patches

### PR DESCRIPTION
**Pull request by LunNova**
###### Motivation for this change
I'm most interested in this change https://invent.kde.org/qt/qt/qtwayland/-/commit/4644d51f4b52e83fc1b4d02b380d80d9d57e76fa which makes performance on nvidia wayland usable, but there are many other changes.

We're expected to keep these up to date as we update plasma5, but that was updated [a few weeks ago](https://github.com/NixOS/nixpkgs/pull/153663) and our patches are from October.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by LunNova** [comment]
```
21 packages marked as broken and skipped:
aqemu authenticator cq-editor ideamaker libsForQt5.openbr libsForQt512.fcitx-qt5 libsForQt512.fcitx5-qt libsForQt512.plasma-phone-components libsForQt514.fcitx-qt5 libsForQt514.fcitx5-qt libsForQt514.plasma-phone-components multibootusb nagstamon python310Packages.skein python39Packages.skein screencloud timedoctor ultrastar-creator ultrastar-manager vogl webbrowser

34 packages failed to build:
anki ankisyncd cudatext faustStk goverlay hqplayer-desktop koboredux magnetophonDSP.ConstantDetuneChorus mlterm mnemosyne obs-studio-plugins.obs-ndi openmw-tes3mp perl532Packages.BarcodeZBar perl534Packages.BarcodeZBar pfstools pivx pokerth pokerth-server python310Packages.ansible-kernel python310Packages.einops python310Packages.elegy python310Packages.jupyter python310Packages.lightparam python310Packages.magicgui python310Packages.napari python310Packages.pyside2 python310Packages.pyside2-tools python310Packages.shiboken2 python310Packages.treex python310Packages.tumpa python310Packages.vega python310Packages.weboob python310Packages.woob xflr5



$ nix --experimental-features nix-command build --no-link --keep-going --option build-use-sandbox relaxed -f /home/lun/.cache/nixpkgs-review/rev-d7e59539429e7921496705785ac34be9fc5aefbd-5/build.nix
1281 packages built:
AusweisApp2 CuboCore.coreaction CuboCore.corearchiver CuboCore.corefm CuboCore.coregarage CuboCore.corehunt CuboCore.coreimage CuboCore.coreinfo CuboCore.corekeyboard CuboCore.corepad CuboCore.corepaint CuboCore.corepdf CuboCore.corepins CuboCore.corerenamer CuboCore.coreshot CuboCore.corestats CuboCore.corestuff CuboCore.coreterminal CuboCore.coretime CuboCore.coretoppings CuboCore.coreuniverse CuboCore.libcprime CuboCore.libcsys OSCAR PageEdit adwaita-qt aj-snapshot ajour albert amarok ams android-file-transfer antimicrox ao appcsxcad aqbanking arx-libertatis asymptote audacious audiality2 avidemux avogadro2 avogadrolibs awesomebump backintime bambootracker barrier bcompare beamerpresenter beauty-line-icon-theme bibletime bino3d birdtray bitcoin bitcoin-abc blackbox cadence calamares calaos_installer calibre calligra calyx-vpn candle caneda cantata carla cemu chatterino2 chessx chewing-editor chiaki chrome-token-signing citra ckb-next clementine clementineUnfree clipgrab cloudcompare cmakeWithGui cmst cockatrice code-browser-qt colord-kde communi contour convertall cool-retro-term coolreader copyq coqPackages.interval corectrl corrscope cpeditor crow-translate csound-qt cubiomes-viewer cura cutecom cutelyst cutemaze cutter datovka ddcui dfasma dfilemanager dialogbox diffpdf digikam djview dolphin-emu-beta dolphin-emu-primehack doomseeker dosbox-staging doxygen_gui drawpile drawpile-server-headless drumkv1 dsview duckstation dupeguru dwarf-fortress-packages.dwarf-fortress-full dwarf-fortress-packages.dwarf-therapist dwarf-fortress-packages.dwarf-therapist-original eagle easyeffects edb eddy eiskaltdcpp electron-cash electrum electrum-ltc elements elf-dissector engauge-digitizer enyo-doom espanso evilpixie evtest-qt extra-cmake-modules faust2jack faust2jaqt faustPhysicalModeling faustlive fceux fcitx fcitx-configtool fcitx-engines.anthy fcitx-engines.chewing fcitx-engines.cloudpinyin fcitx-engines.hangul fcitx-engines.libpinyin fcitx-engines.m17n fcitx-engines.mozc fcitx-engines.rime fcitx-engines.skk fcitx-engines.table-extra fcitx-engines.table-other fcitx-engines.unikey fcitx5 fcitx5-chinese-addons fcitx5-configtool fcitx5-gtk fcitx5-lua fcitx5-m17n fcitx5-mozc fcitx5-rime fcitx5-table-extra fcitx5-table-other fcitx5-with-addons fdr featherpad ffado firebird-emu flacon flameshot flat-remix-icon-theme flent flightgear flirc flowblade fmit focuswriter foxdot freecad frescobaldi friture fritzing fstl fsuae-launcher fwbuilder g2o gammy gcompris gecode gede ghostwriter giada gimp-with-plugins gimpPlugins.gmic git-annex-metadata-gui git-cola gjay glfw-wayland glimpse-with-plugins globalprotect-openconnect glogg gmic-qt gmic-qt-krita gnome-keysign gns3-gui gnss-sdr gnucash gnuplot_qt gnuradio gnuradio3_8 gnuradio3_8Packages.ais gnuradio3_8Packages.gnuradio gnuradio3_8Packages.grnet gnuradio3_8Packages.limesdr gnuradio3_8Packages.osmosdr gnuradio3_8Packages.rds gnuradio3_9 gnuradioMinimal gnuradio3_9Packages.gnuradio goldendict gplates gpsbabel gpsbabel-gui gpxlab gpxsee gqrx gqrx-gr-audio gqrx-portaudio graphia gruvbox-dark-icons-gtk gsettings-qt guglielmo gwenhywfar haka hal-hardware-analyzer haruna heaptrack heimdall heimdall-gui heimer herqq hime hobbits hopper hotspot hplip hplipWithPlugin hpmyroom httraqt hydrogen hydrus iannix ibus-engines.mozc icemon ihaskell imgbrd-grabber in-formant index-fm inkcut inkscape-extensions.inkcut inspectrum insync-v3 ioquake3 jack1 jack2 jackmix jackmix_jack1 jami-client-gnome jami-client-qt jami-libclient jamulus jellyfin-media-player jellyfin-mpv-shim k4dirstat kaffeine kaidan kalendar kapow kbibtex kcc kcollectd kdbg kddockwidgets kdeltachat kdev-php kdev-python kdevelop kdevelop-pg-qt kdevelop-unwrapped kdiff3 keepassxc kernelshark kgraphviewer kid3 kile kime kio-fuse kitsas kiwix klayout klog kmetronome kmplayer kmymoney knockpy koboredux-free konversation kora-icon-theme kotatogram-desktop krename kristall krita kronometer krop krunner-pass krusader ksmoothdock ksnip kstars ktimetracker ktorrent kup kwalletcli la-capitaine-icon-theme labelImg latte-dock lazarus-qt leela-zero leo-editor leocad libarchive-qt libchipcard libime libosmscout libqt5pas libquotient libreoffice-qt librepcb libsForQt5.accounts-qt libsForQt5.akonadi libsForQt5.akonadi-calendar libsForQt5.akonadi-calendar-tools libsForQt5.akonadi-contacts libsForQt5.akonadi-import-wizard libsForQt5.akonadi-mime libsForQt5.akonadi-notes libsForQt5.akonadi-search libsForQt5.akonadiconsole libsForQt5.akregator libsForQt5.alkimia libsForQt5.alligator libsForQt5.angelfish libsForQt5.applet-window-buttons libsForQt5.appstream-qt libsForQt5.ark libsForQt5.attica libsForQt5.audiotube libsForQt5.baloo libsForQt5.baloo-widgets libsForQt5.bismuth libsForQt5.bluedevil libsForQt5.bluez-qt libsForQt5.bomber libsForQt5.bovo libsForQt5.breeze-grub libsForQt5.breeze-gtk libsForQt5.breeze-icons libsForQt5.breeze-plymouth libsForQt5.breeze-qt5 libsForQt5.calendarsupport libsForQt5.calindori libsForQt5.discover libsForQt5.dolphin libsForQt5.dolphin-plugins libsForQt5.dragon libsForQt5.drumstick libsForQt5.dxflib libsForQt5.elisa libsForQt5.eventviews libsForQt5.fcitx-qt5 libsForQt5.fcitx5-qt libsForQt5.ffmpegthumbs libsForQt5.filelight libsForQt5.frameworkintegration libsForQt5.full libsForQt5.granatier libsForQt5.grantlee libsForQt5.grantleetheme libsForQt5.gwenview libsForQt5.incidenceeditor libsForQt5.k3b libsForQt5.kaccounts-integration libsForQt5.kaccounts-providers libsForQt5.kactivities libsForQt5.kactivities-stats libsForQt5.kactivitymanagerd libsForQt5.kaddressbook libsForQt5.kalarm libsForQt5.kalarmcal libsForQt5.kalk libsForQt5.kalzium libsForQt5.kamoso libsForQt5.kapidox libsForQt5.kapman libsForQt5.kapptemplate libsForQt5.karchive libsForQt5.kasts libsForQt5.kate libsForQt5.katomic libsForQt5.kauth libsForQt5.kblackbox libsForQt5.kblocks libsForQt5.kbookmarks libsForQt5.kbounce libsForQt5.kbreakout libsForQt5.kcachegrind libsForQt5.kcalc libsForQt5.kcalendarcore libsForQt5.kcalutils libsForQt5.kcharselect libsForQt5.kclock libsForQt5.kcmutils libsForQt5.kcodecs libsForQt5.kcolorchooser libsForQt5.kcolorpicker libsForQt5.kcompletion libsForQt5.kconfig libsForQt5.kconfigwidgets libsForQt5.kcontacts libsForQt5.kcoreaddons libsForQt5.kcrash libsForQt5.kdav libsForQt5.kdb libsForQt5.kdbusaddons libsForQt5.kde-cli-tools libsForQt5.kde-gtk-config libsForQt5.kde2-decoration libsForQt5.kdebugsettings libsForQt5.kdeclarative libsForQt5.kdeconnect-kde libsForQt5.kdecoration libsForQt5.kded libsForQt5.kdegraphics-mobipocket libsForQt5.kdegraphics-thumbnailers libsForQt5.kdelibs4support libsForQt5.kdenetwork-filesharing libsForQt5.kdenlive libsForQt5.kdepim-addons libsForQt5.kdepim-runtime libsForQt5.kdeplasma-addons libsForQt5.kdesignerplugin libsForQt5.kdesu libsForQt5.kdewebkit libsForQt5.kdf libsForQt5.kdiagram libsForQt5.kdialog libsForQt5.kdiamond libsForQt5.kdnssd libsForQt5.kdoctools libsForQt5.kdsoap libsForQt5.keditbookmarks libsForQt5.kemoticons libsForQt5.keysmith libsForQt5.kf5gpgmepp libsForQt5.kfilemetadata libsForQt5.kfind libsForQt5.kfloppy libsForQt5.kgamma5 libsForQt5.kgeography libsForQt5.kget libsForQt5.kglobalaccel libsForQt5.kgpg libsForQt5.kguiaddons libsForQt5.khelpcenter libsForQt5.kholidays libsForQt5.khotkeys libsForQt5.khtml libsForQt5.ki18n libsForQt5.kiconthemes libsForQt5.kidentitymanagement libsForQt5.kidletime libsForQt5.kig libsForQt5.kigo libsForQt5.killbots libsForQt5.kimageannotator libsForQt5.kimageformats libsForQt5.kimap libsForQt5.kinfocenter libsForQt5.kinit libsForQt5.kio libsForQt5.kio-extras libsForQt5.kio-gdrive libsForQt5.kipi-plugins libsForQt5.kirigami-addons libsForQt5.kirigami2 libsForQt5.kitemmodels libsForQt5.kitemviews libsForQt5.kitinerary libsForQt5.kjobwidgets libsForQt5.kjs libsForQt5.kjsembed libsForQt5.kldap libsForQt5.kleopatra libsForQt5.klettres libsForQt5.klines libsForQt5.kmag libsForQt5.kmahjongg libsForQt5.kmail libsForQt5.kmail-account-wizard libsForQt5.kmailtransport libsForQt5.kmbox libsForQt5.kmediaplayer libsForQt5.kmenuedit libsForQt5.kmime libsForQt5.kmines libsForQt5.kmix libsForQt5.kmplot libsForQt5.knavalbattle libsForQt5.knetwalk libsForQt5.knewstuff libsForQt5.knights libsForQt5.knotes libsForQt5.knotifications libsForQt5.knotifyconfig libsForQt5.koko libsForQt5.kolf libsForQt5.kollision libsForQt5.kolourpaint libsForQt5.kompare libsForQt5.konqueror libsForQt5.konquest libsForQt5.konsole libsForQt5.kontact libsForQt5.kontactinterface libsForQt5.korganizer libsForQt5.kpackage libsForQt5.kparts libsForQt5.kpat libsForQt5.kpeople libsForQt5.kpeoplevcard libsForQt5.kpimtextedit libsForQt5.kpkpass libsForQt5.kplotting libsForQt5.kpmcore libsForQt5.kproperty libsForQt5.kpty libsForQt5.kpublictransport libsForQt5.kpurpose libsForQt5.kqtquickcharts libsForQt5.kquickcharts libsForQt5.kquickimageedit libsForQt5.krdc libsForQt5.krecorder libsForQt5.kreport libsForQt5.kreversi libsForQt5.krfb libsForQt5.krohnkite libsForQt5.kross libsForQt5.kruler libsForQt5.krunner libsForQt5.krunner-symbols libsForQt5.kscreen libsForQt5.kscreenlocker libsForQt5.kservice libsForQt5.kshisen libsForQt5.ksmtp libsForQt5.kspaceduel libsForQt5.ksquares libsForQt5.ksshaskpass libsForQt5.ksudoku libsForQt5.ksystemlog libsForQt5.ksystemstats libsForQt5.kteatime libsForQt5.ktexteditor libsForQt5.ktextwidgets libsForQt5.ktimer libsForQt5.ktnef libsForQt5.ktouch libsForQt5.ktrip libsForQt5.kturtle libsForQt5.kunitconversion libsForQt5.kwallet libsForQt5.kwallet-pam libsForQt5.kwalletmanager libsForQt5.kwave libsForQt5.kwayland libsForQt5.kwayland-integration libsForQt5.kwayland-server libsForQt5.kweather libsForQt5.kweathercore libsForQt5.kwidgetsaddons libsForQt5.kwin libsForQt5.kwin-dynamic-workspaces libsForQt5.kwin-tiling libsForQt5.kwindowsystem libsForQt5.kwrited libsForQt5.kxmlgui libsForQt5.kxmlrpcclient libsForQt5.layer-shell-qt libsForQt5.ldutils libsForQt5.libcommuni libsForQt5.libdbusmenu libsForQt5.libgravatar libsForQt5.libkcddb libsForQt5.libkdcraw libsForQt5.libkdegames 
libsForQt5.libkdepim libsForQt5.libkexiv2 libsForQt5.libkgapi libsForQt5.libkipi libsForQt5.libkleo libsForQt5.libkmahjongg libsForQt5.libkomparediff2 libsForQt5.libksane libsForQt5.libkscreen libsForQt5.libksieve libsForQt5.libksysguard libsForQt5.libktorrent libsForQt5.liblastfm libsForQt5.libopenshot libsForQt5.libqaccessibilityclient libsForQt5.libqglviewer libsForQt5.libqofono libsForQt5.libqtav libsForQt5.lightly libsForQt5.mailcommon libsForQt5.mailimporter libsForQt5.mapbox-gl-native libsForQt5.mapbox-gl-qml libsForQt5.marble libsForQt5.mauikit libsForQt5.mauikit-filebrowsing libsForQt5.mbox-importer libsForQt5.messagelib libsForQt5.milou libsForQt5.minuet libsForQt5.mlt libsForQt5.modemmanager-qt libsForQt5.networkmanager-qt libsForQt5.okular libsForQt5.oxygen libsForQt5.oxygen-icons5 libsForQt5.packagekit-qt libsForQt5.parachute libsForQt5.phonon libsForQt5.phonon-backend-gstreamer libsForQt5.phonon-backend-vlc libsForQt5.picmi libsForQt5.pim-data-exporter libsForQt5.pim-sieve-editor libsForQt5.pimcommon libsForQt5.plasma-applet-caffeine-plus libsForQt5.plasma-applet-virtual-desktop-bar libsForQt5.plasma-browser-integration libsForQt5.plasma-desktop libsForQt5.plasma-dialer libsForQt5.plasma-disks libsForQt5.plasma-framework libsForQt5.plasma-integration libsForQt5.plasma-nano libsForQt5.plasma-nm libsForQt5.plasma-pa libsForQt5.plasma-phone-components libsForQt5.plasma-phonebook libsForQt5.plasma-sdk libsForQt5.plasma-settings libsForQt5.plasma-systemmonitor libsForQt5.plasma-thunderbolt libsForQt5.plasma-vault libsForQt5.plasma-wayland-protocols libsForQt5.plasma-workspace libsForQt5.plasma-workspace-wallpapers libsForQt5.polkit-kde-agent libsForQt5.polkit-qt libsForQt5.poppler libsForQt5.poppler_0_61 libsForQt5.powerdevil libsForQt5.print-manager libsForQt5.prison libsForQt5.pulseaudio-qt libsForQt5.qca-qt5 libsForQt5.qcoro libsForQt5.qcsxcad libsForQt5.qgpgme libsForQt5.qmake libsForQt5.qmlbox2d libsForQt5.qmltermwidget libsForQt5.qoauth libsForQt5.qqc2-breeze-style libsForQt5.qqc2-desktop-style qscintilla libsForQt5.qt3d libsForQt5.qt5.qtbase libsForQt5.qt5.qtcharts libsForQt5.qt5.qtconnectivity libsForQt5.qt5.qtdeclarative libsForQt5.qt5.qtdoc libsForQt5.qt5.qtgamepad libsForQt5.qt5.qtgraphicaleffects libsForQt5.qt5.qtimageformats libsForQt5.qt5.qtlocation libsForQt5.qt5.qtmultimedia libsForQt5.qt5.qtnetworkauth libsForQt5.qt5.qtquickcontrols libsForQt5.qt5.qtquickcontrols2 libsForQt5.qt5.qtscript libsForQt5.qt5.qtscxml libsForQt5.qt5.qtsensors libsForQt5.qt5.qtserialbus libsForQt5.qt5.qtserialport libsForQt5.qt5.qtspeech libsForQt5.qt5.qtsvg libsForQt5.qt5.qttools libsForQt5.qt5.qttranslations libsForQt5.qt5.qtvirtualkeyboard libsForQt5.qt5.qtwayland libsForQt5.qt5.qtwebchannel libsForQt5.qt5.qtwebengine libsForQt5.qt5.qtwebglplugin libsForQt5.qt5.qtwebkit libsForQt5.qt5.qtwebsockets libsForQt5.qt5.qtwebview libsForQt5.qt5.qtx11extras libsForQt5.qt5.qtxmlpatterns libsForQt5.qt5.wrapQtAppsHook libsForQt5.qt5ct libsForQt5.qtcurve libsForQt5.qtfeedback libsForQt5.qtinstaller libsForQt5.qtkeychain libsForQt5.qtpbfimageplugin libsForQt5.qtstyleplugin-kvantum libsForQt5.qtstyleplugins libsForQt5.qtutilities libsForQt5.qtwebkit-plugins libsForQt5.quazip libsForQt5.qwt libsForQt5.rocs libsForQt5.sddm libsForQt5.sddm-kcm libsForQt5.signond libsForQt5.solid libsForQt5.sonnet libsForQt5.soqt libsForQt5.soundkonverter libsForQt5.spacebar libsForQt5.spectacle libsForQt5.syndication libsForQt5.syntax-highlighting libsForQt5.systemsettings libsForQt5.telepathy libsForQt5.threadweaver libsForQt5.xdg-desktop-portal-kde libsForQt5.yakuake libsForQt512.qcsxcad libsForQt514.qcsxcad lightburn lightdm_qt lightly-qt linphone linssid linuxstopmotion littlegptracker lmms lsd2dsl lsp-plugins ltc-tools luckybackup lumina.lumina lumina.lumina-calculator lumina.lumina-pdf luminanceHDR luna-icons luppp lutris lutris-free lxqt.compton-conf lxqt.libfm-qt lxqt.liblxqt lxqt.libqtxdg lxqt.libsysstat lxqt.lximage-qt lxqt.lxqt-about lxqt.lxqt-admin lxqt.lxqt-archiver lxqt.lxqt-build-tools lxqt.lxqt-config lxqt.lxqt-globalkeys lxqt.lxqt-notificationd lxqt.lxqt-openssh-askpass lxqt.lxqt-panel lxqt.lxqt-policykit lxqt.lxqt-powermanagement lxqt.lxqt-qtplugin lxqt.lxqt-runner lxqt.lxqt-session lxqt.lxqt-sudo lxqt.lxqt-themes lxqt.obconf-qt lxqt.pavucontrol-qt lxqt.pcmanfm-qt lxqt.qlipper lxqt.qps lxqt.qterminal lxqt.qtermwidget lxqt.screengrab lyx maestral-gui magnetophonDSP.CharacterCompressor magnetophonDSP.CompBus magnetophonDSP.LazyLimiter magnetophonDSP.MBdistortion magnetophonDSP.RhythmDelay magnetophonDSP.VoiceOfFaust magnetophonDSP.faustCompressors magnetophonDSP.pluginUtils magnetophonDSP.shelfMultiBand maia-icon-theme makemkv maliit-framework maliit-keyboard mandelbulber manuskript mapmap massif-visualizer masterpdfeditor masterpdfeditor4 material-kwin-decoration mcrl2 mediaelch megapixels megasync mellowplayer melonDS merkaartor meshlab mgba michabo mindforger minitube mirage-im mirakurun mixxx mkchromecast mkvtoolnix mkvtoolnix-cli mlt mlv-app molequeue monero-gui mooSpace moolticute moonlight-qt mpc-qt mpvScripts.convert mrtrix mudlet mumble mumble_overlay munt murmur muse musescore mytetra nano-wallet nanovna-saver napari nemo-qml-plugin-dbus neochat neovim-qt neovim-qt-unwrapped nethack-qt nextcloud-client nextpnrWithGui nheko nifskope nitrokey-app nm-tray nomacs nootka nootka-unstable obs-studio obs-studio-plugins.looking-glass-obs obs-studio-plugins.obs-gstreamer obs-studio-plugins.obs-move-transition obs-studio-plugins.obs-multi-rtmp obs-studio-plugins.obs-nvfbc obs-studio-plugins.obs-websocket obs-studio-plugins.wlrobs ocenaudio octaveFull octavePackages.audio odafileconverter ofono-phonesim okteta onionshare-gui onlyoffice-bin openambit openboard openbrf opencsg openems openhantek6022 openlp openlpFull openmodelica.combined openmodelica.omedit openmodelica.omplot openmodelica.omshell openmw openorienteering-mapper openrgb openroad openscad openshot-qt opensnitch-ui opentrack opentx opl3bankeditor opn2bankeditor oranchelo-icon-theme osmscout-server ostinato otpclient ovito owncloud-client padthv1 panopticon papirus-icon-theme papirus-maia-icon-theme paraview partition-manager passExtensions.pass-tomb patray pcl pdfmixtool pentablet-driver pentobi persepolis peruse pgmodeler photoflare photoqt phototonic pianobooster picard pinentry pinentry-curses pinentry-emacs pinentry-gnome pinentry-gtk2 pinentry-qt plasma-applet-volumewin7mixer plasma-pass plater playbar2 plover.dev polymc portmod pothos ppsspp pragha pro-office-calculator projectm proxmark3 proxmark3-rrg proxmark3-unstable psi psi-plus ptcollab puddletag pulseeffects-legacy punes pure-maps pyotherside pyspread python310Packages.binwalk-full python310Packages.enamlx python310Packages.foxdot python310Packages.mayavi python310Packages.mlt python310Packages.napari-console python310Packages.pivy python310Packages.poppler-qt5 python310Packages.pyls-flake8 python310Packages.pyls-isort python310Packages.pyls-spyder python310Packages.pylsp-mypy python310Packages.pyqt5 python310Packages.pyqt5_with_qtmultimedia python310Packages.pyqt5_with_qtwebkit python310Packages.pyqtgraph python310Packages.pyqtwebengine python310Packages.python-csxcad python310Packages.python-lsp-black python310Packages.python-lsp-server python310Packages.python-openems python310Packages.pywebview python310Packages.qimage2ndarray python310Packages.qreactor python310Packages.qscintilla python310Packages.qtconsole python310Packages.quamash python310Packages.recoll python310Packages.superqt python310Packages.trezor_agent python310Packages.uranium python39Packages.ansible-kernel python39Packages.binwalk-full python39Packages.einops python39Packages.elegy python39Packages.enamlx python39Packages.jupyter python39Packages.lightparam python39Packages.magicgui python39Packages.mayavi python39Packages.mlt python39Packages.napari-console python39Packages.pivy python39Packages.poppler-qt5 python39Packages.pyls-flake8 python39Packages.pyls-isort python39Packages.pyls-spyder python39Packages.pylsp-mypy python39Packages.pyqt5 python39Packages.pyqt5_with_qtmultimedia python39Packages.pyqt5_with_qtwebkit python39Packages.pyqtgraph python39Packages.pyqtwebengine python39Packages.pyside2 python39Packages.pyside2-tools python39Packages.python-csxcad python39Packages.python-lsp-black python39Packages.python-lsp-server python39Packages.python-openems python39Packages.pywebview python39Packages.qimage2ndarray python39Packages.qreactor python39Packages.qscintilla python39Packages.qtconsole python39Packages.quamash recoll python39Packages.shiboken2 python39Packages.stytra python39Packages.superqt python39Packages.treex trezor_agent python39Packages.tumpa python39Packages.uranium python39Packages.vega python39Packages.weboob python39Packages.woob pytrainer q4wine qMasterPassword qarte qastools qbittorrent qbittorrent-nox qbs qcachegrind qcad qcomicbook qdigidoc qdirstat qgis qgis-unwrapped qgit qgnomeplatform qgo qgroundcontrol qimgv qjackctl qjournalctl qlcplus qmapshack qmediathekview qmidiarp qmidinet qmmp qmplay2 qnotero qolibri qosmic qpaeq qpdfview qpwgraph qradiolink qsampler qsstv qstopmotion qsudo qsyncthingtray qsynth qt-box-editor qt-video-wlr qtads qtbitcointrader qtchan qtcreator qtemu qtikz qtox qtpass qtractor qtspim quake3demo quassel quasselClient quasselDaemon quaternion quicksynergy qutebrowser qv2ray qvge qview qxmledit qxmpp radeon-profile rapid-photo-downloader razergenie rclone-browser reaper redis-desktop-manager redshift-plasma-applet renderdoc rescuetime restique retext retroshare rgp ricochet ripcord riseup-vpn rmview rockbox_utility rocket rpcs3 rpi-imager rsibreak rssguard rstudio rstudioWrapper saga samplv1 scribusUnstable scudcloud sdrangel seafile-client semantik seq66 sfxr-qt shotcut sierra-breeze-enhanced sigil simplescreenrecorder skanlite skrooge sl1-to-photon smplayer snowman solarus solarus-quest-editor sonic-lineup sonic-pi sonic-visualiser soulseekqt soundtracker soundwireserver 
sourcetrail spectmorph speedcrunch spoofer-gui spotify-qt sqlitebrowser stellarium stellarsolver strawberry stremio suil-qt5 sumorobot-manager supercollider supercollider_scel svn-all-fast-export svxlink syncplay syncthingtray syncthingtray-minimal synergy synergyWithoutGUI synology-drive-client synthv1 systemdgenie tageditor tambura tbe tdesktop teamspeak_client teamviewer tellico tensor testdisk-qt tetraproc texmacs texmaker texstudio texworks tikzit tiled tipp10 tiscamera tomb tora tortoisehg transmission-qt traverso trenchbroom tribler trojita ttfautohint tuxguitar tvheadend twmn tytools uefitool uefitoolPackages.old-engine unetbootin unixcw urh v4l-utils vapoursynth-editor veikk-linux-driver-gui veusz viking vimiv-qt virt-manager-qt virtlyst virtscreen vlc vmpk vnote vokoscreen vokoscreen-ng vorta vtkWithQt5 vtk_9_withQt5 vym wacomtablet webcamoid webmacs welle-io wireshark wluma wpa_supplicant_gui write_stylus wsjtx x2goclient xautoclick xca xcb-imdkit xxdiff yabause yacas-gui yacreader yubikey-manager-qt yubikey-personalization-gui yubioath-desktop yuzu-ea yuzu-mainline zafiro-icons zanshin zbar zeal zegrapher zombietrackergps zrythm
```

Some odd failures here which seem not to happen if I build without nixpkgs-review, I tried with `nix build .#anki -L --no-link` (and `xflr5`) and it built fine. The rest of the failures seem to also be broken in master due to python 3.10 issues.

**Comment by LunNova** [comment]
Have been running these with plasma 5.23 and not noticed any problems.

**Comment by LunNova** [comment]
Changed this to target staging due to big rebuild, hope that was correct.

**Comment by LunNova** [comment]
One more fix landed in qtwayland for a bug which causes the plasma panel to stop updating. https://bugs.kde.org/show_bug.cgi?id=449163

**Comment by timokau** [comment]
Thanks! I'm not very well qualified to review this. Maybe one of the maintainers could have a look? I have requested reviews from the qt and plasma maintainers.

**Review by ttuegel — APPROVED** [review]

**Comment by ttuegel** [comment]
Thanks!

**Pull request merged**
