### PR TITLE
dolphinEmuMaster: 2018-06-22 -> 2018-06-27

### PR DESCRIPTION
**Pull request by ghost**
###### Motivation for this change
Version bump.
Change default GUI from wxWidgets to Qt.
screenshot_20180627_182246

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Chiiruno** [comment]
cc @MP2E

**Comment by Chiiruno** [comment]
As a side note, I ran `nix path-info -S`, but I didn't really get any useful info.
Exactly when am I supposed to run this?

**Comment by Chiiruno** [comment]
wxWidgets was removed in [dolphin-emu/dolphin#6819](https://github.com/dolphin-emu/dolphin/pull/6819)

**Comment by Chiiruno** [comment]
I also did some restructuring because wxWidgets was removed, as well as checking the dependencies upstream.

**Comment by MP2E** [comment]
Looks great, as usual! Good to see that they moved quickly in making the qt frontend the default, that cleans up the expression quite a bit.

Squashed the changes into 1 commit and merged as of 8b312db421ca99797e60d76201f607f75c80af48

**Pull request closed without merging**
