### PR TITLE
nixos: switch the package installation prefix from `nixos.` to `nixpkgs.`

### PR DESCRIPTION
**Pull request by zimbatm**
###### Motivation for this change

This is a proposal to change NixOS so that packages can also be installed with the same prefix as non-NixOS machines:

Before:

    $ nix-env -iA nixos.hello

After:

    $ nix-env -iA nixpkgs.hello

The goal is to reduce the complexity in installation instructions so we can tell all our users to use the same command to install packages. It also fixes issues where `nix search` will return one prefix and then `nix-env` will need the other-one. Or the user having to remember on which machine they are installing a package.

This change is backward-compatible. The main downside is that `nix-env -qaP` takes twice as long to execute.

EDIT: updated the proposal, it was initially about switching channels

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by zimbatm** [comment]
One open question is how the upgrade path for existing NixOS would look like. The change should be backward-compatible except for manual instructions. It would be nice if old users could use both the old and new notations.

**Review by srhb — APPROVED** [review]
I think this is an excellent simplification. I don't really have a firm understanding of where exactly we might still have references to `nixos` so consider this an approval in principle, not in implementation.

**Comment by zimbatm** [comment]
thanks @srhb!

thanks @samueldr for reading between the lines, your feedback is awesome. I agree that there are still unknowns to be uncovered and this is exactly the type of feedback I was looking for.

**Comment by Infinisil** [comment]
Can we somehow make installations with `nix-env -iA nixos.hello` throw an error like "error: nixos. has been changed to nixpkgs."? Because if not, we'd break a lot of installation instructions out there.

**Comment by davidak** [comment]
I think it's a good idea to make this more consistent.

`nixos` is also used on https://nixos.org/nixos/packages.html for example.

**Comment by edolstra** [comment]
I think we should not change this at this time, because 1) it's an incompatible change; and 2) all of this will change anyway once we have flakes and a nix-channel replacement.

**Comment by Mic92** [comment]
Closing then?

**Comment by davidak** [comment]
>this will change anyway once we have flakes and a nix-channel replacement.

@edolstra can you say something about the status of that? Is there a chance it will be ready for the next release? When not we could still use this workaround in the next NixOS release until we have a clean solution. It might be a huge help for (new) Nix(OS) users.

**Comment by vcunat** [comment]
What about aliasing those two in some way?

**Comment by zimbatm** [comment]
I think I found a backward-compatible way of tweaking the layout of `~/.nix-defexpr` (which is the legacy folder `nix-env` uses instead of `NIX_PATH`). With that change in mind we would:
* Keep the `nixos` root channel
* But allow to use the `nixpkgs.` prefix in `nix-env`
* And change all the doc to point to the `nixpkgs.` prefix

TBC

**Comment by zimbatm** [comment]
```
$ nix-channel --list

$ sudo nix-channel --list
nixos https://nixos.org/channels/nixos-unstable

$ tree ~/.nix-defexpr/
/home/zimbatm/.nix-defexpr/
├── channels_root -> /nix/var/nix/profiles/per-user/root/channels
└── nixpkgs-compat
    └── nixpkgs -> /nix/var/nix/profiles/per-user/root/channels/nixos

$ nix search hello
warning: using cached results; pass '-u' to update the cache
* nixpkgs.gnome3.iagno (iagno-3.28.0)
  Computer version of the game Reversi, more popularly called Othello

* nixpkgs.hello (hello)
  A program that produces a familiar, friendly greeting
[...]
$ nix-env -iA nixpkgs.hello
installing 'hello-2.10'
```

The only issue is `nix-env -qaP` which lists both prefixes:
```
$ nix-env -qaP | head -n 6
nixpkgs._1password                                                       1password-0.5.4
nixos._1password                                                         1password-0.5.4
nixpkgs._2048-in-terminal                                                2048-in-terminal-2017-11-29
nixos._2048-in-terminal                                                  2048-in-terminal-2017-11-29
nixpkgs._20kly                                                           20kly-1.4
nixos._20kly                                                             20kly-1.4
```

**Comment by lheckemann** [comment]
>The only issue is nix-env -qaP which lists both prefixes

Does that mean it also evaluates nixpkgs twice, or is that memoised? If it has to evaluate twice that's quite a pain…

**Comment by zimbatm** [comment]
It's evaluated twice when using `nix-env -qaP`. It went from 7s to 12s on my system. Since it will be replaced I think it's alright. For example `nix search` is not affected by that change either.

**Comment by zimbatm** [comment]
This PR has changed from switching the channel name to tweaking `~/.nix-defexpr` to allow the unification of prefixes during `nix-env -iA` installs. I updated the PR description to reflect the new approach. This makes the PR backward-compatible and allows us to update and simplify the documentation.

**Comment by zimbatm** [comment]
As long as the command uses NIX_PATH instead of the old `~/.nix-defexprs` it won't be impacted. I think that if the command uses `~/.nix-defexprs` but specifies the prefix it won't be impacted either.

Not impacted by this PR:
* any of the new `nix` commands
* nixos-rebuild
* nix-build
* explicit `<nixpkgs>` imports
Impacted:
* `nix-env -qaP`

TODO: test the following commands:
* [ ] `nix-env -iA nixos.hello` (how to test this?)
* [ ] `nix-shell -p hello` (how to test this?)

Did I miss anything?

**Comment by edolstra** [comment]
Modifying `~/.nix-defexpr` from the login script is the kind of stateful, untracked configuration change that doesn't fit very well in NixOS.

Also given that many systems are already barely able to evaluate Nixpkgs, evaluating it twice isn't really an option.

**Comment by zimbatm** [comment]
I am currently blocked on resolving all the constraints:

1. Keep backward-compatible
2. Not rename the nixos channel
3. Not touch ~/.nix-defexpr
4. Avoid double nixpkgs evaluation on a subset of the old commands

Potential routes I can see:
a. Patch nix-env to alias `nixpkgs` to `nixos` if no `nixpkgs` prefix exists.
b. Help with the channel replacement (I don't know where that is?)

**Comment by Mic92** [comment]
`a)` in short-term and having the channel replacement long-term, does not sound too bad to me.

**Pull request closed without merging**
