### PR TITLE
fasttext: 0.2.0 -> 0.9.1

### PR DESCRIPTION
**Pull request by danieldk**
###### Motivation for this change

Changes:

- Refactoring of internal classes.
- Better unicode handling.

https://github.com/facebookresearch/fastText/releases/tag/v0.9.1

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by danieldk** [comment]
@GrahamcOfBorg build fasttext

**Review by jonringer — COMMENTED** [review]
since this looks like a repeat of your library, I think you could use `toPythonApplication` from the other derivation.

in pkgs/top-level/all-packages.nix
```
fasttext = callPackage ../applications/science/machine-learning/fasttext { };
```
to
```
fasttext = python3.pkgs.toPythonApplication python3.pkgs.fasttext;
```
or something similar, i might be off by a little in terms of syntax.

EDIT:
nevermind, looked at the file. They are in the same repo, but they are completely different builds.

**Review by jonringer — APPROVED** [review]
`nix-review pr 64639` passes on NixOS
diff LGTM
binary works

```
$ nix path-info -Sh ./results/fasttext
/nix/store/a3n85z82jl2mxskd73gv6ky9w7s5qxgr-fasttext-0.9.1        34.1M
```

**Comment by teto** [comment]
Thanks for the package and to @jonringer for his reviews <3

**Pull request merged**
