### PR TITLE
nixos/nixpkgs: fix determination for cross-compiled nixos system

### LINKED ISSUE #278001: Comparison of nixpkgs.hostPlatform to nixpkgs.buildPlatform is flawed
### Describe the bug

When a nixos configuration has `nixpkgs.hostPlatform` and `nixpkgs.buildPlatform` both set to the same string, the module defined [here](https://github.com/nixos/nixpkgs/blob/2b8295bf1e4be78b062e558bcf3b6abcb928466c/nixos/modules/misc/nixpkgs.nix#L75) always determines that the system is cross-compiled, even when it should not be.

### Steps To Reproduce
1. Make a nixos config with the example configuration:
```nix
{ nixpkgs.hostPlatform = "x86_64-linux"; nixpkgs.buildPlatform = "x86_64-linux"; }
```
3. Try building and notice that the entire world gets rebuilt since it tries to build cross-compilation toolchains

### Expected behavior

I would expect that the module would determine I am not cross-compiling the nixos system and build accordingly.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.8, NixOS, 24.05 (Uakari), 24.05.20231231.48d59d0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/4pxqlm2rwq6j6di78q178602jfnx2mys-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by jmbaur**
## Description of changes

Since the output of `lib.systems.elaborate` contains functions, an equality check with `==` does not suffice, `lib.systems.equals` should be used instead.

Fixes #278001

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by roberth** [comment]
We have three solutions to this problem

1. Canonicalize all pairs so that if they match, we use only one of the values in both places. Works well for Nixpkgs and its implementation.
2. Remove the functions.
3. Don't use `==`.


2 is in progress IIRC, but is a slow deprecation. You're doing 3.

1 is a bit more effective though, because it fixes all comparisons of `nixpkgs.*Platform`.
Could you try add something like this to line 211?

```diff
- apply = lib.systems.elaborate;
+ apply = inputBuildPlatform:
+   let elaborated = lib.systems.elaborate inputBuildPlatform;
+   in if lib.systems.equals elaborated cfg.hostPlatform
+     then cfg.hostPlatform  # make identical, so that `==` equality works; see https://github.com/NixOS/nixpkgs/issues/278001
+     else elaborated;
```


(Perhaps relevant are also https://github.com/NixOS/nixpkgs/pull/237512, https://github.com/NixOS/nixpkgs/pull/254763 and related PRs/issues, if you haven't seen them)

That all said, all other modules shouldn't read from anything other than the `pkgs` module argument, which is the single most reliable source of truth. Unfortunately we can't enforce that; would be simpler.

**Comment by roberth** [comment]
@Mindavi

> Where did this isCross come from? 😅. It's way too vague like this...

From me. I don't think it is vague.

> What about other cross types, like Canadian cross?

Nixpkgs is not a compiler, so Canadian cross does not apply to it. Its configuration only has two platforms: build and host; no target.
Individual packages may well support a Canadian cross, but this isn't about individual packages.

**Comment by jmbaur** [comment]
@roberth that makes sense, and is also more forgiving to potential usage of `==` for comparing these platforms, applied your recommendation

**Review by roberth — APPROVED** [review]
Looks good and thank you for adding a test case :+1:

**Pull request merged**
