### PR TITLE
Add taskwarrior3 and taskchampion-sync-server

### LINKED ISSUE #300679: Update request: taskwarrior 2.6.2 → 3.0.0
- Package name: taskwarrior
- Latest released version: 3.0.0
- Current version on the unstable channel: 2.6.2
- Current version on the stable/release channel: 2.6.2
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@marcweber @oxalica

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by mlaradji**
## Description of changes

No existing packages were modified. I added myself (@mlaradji) to the maintainers list. I added new package definitions for `taskwarrior3` and its associated sync server `taskchampion-sync-server`. This PR resolves #300679.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by YarekTyshchenko** [comment]
Nice work! Both client and server work. Ship it!

**Comment by mlaradji** [comment]
> Nice work! Both client and server work. Ship it!
> 
> PS: Just curious how to deal with clash of binary names. I have already have a utility called `task` (taskfile.dev). Do you have any suggestion how to rename it on my system so they don't interfere?

You could rename it to `tw`, which I think is a common alias people use. `taskw` would also work. Unfortunately, there are applications which depend on taskwarrior that expect to find the executable named as `task`.

**Review by matthiasbeyer — CHANGES_REQUESTED** [review]
Please change your commit message(s) to match the [commit message conventions of nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions)!

**Comment by matthiasbeyer** [comment]
For other reviewers: This is a new package instead of an update to the existing `taskwarrior` package because of https://github.com/NixOS/nixpkgs/issues/300679#issuecomment-2041559223

**Review by matthiasbeyer — APPROVED** [review]
Diff itself looks good, commit messages as well, so I unblock this :wink:

**Comment by YarekTyshchenko** [comment]
/me patiently waits for someone to hit the Merge button...

**Comment by matthiasbeyer** [comment]
Result of `nixpkgs-review pr 303632` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>taskchampion-sync-server</li>
    <li>taskwarrior3</li>
  </ul>
</details>

**Comment by matthiasbeyer** [comment]
Okay, lets do this :laughing:

**Comment by doronbehar** [comment]
A NixOS module, and a test is added at:

https://github.com/NixOS/nixpkgs/pull/318892

**Pull request merged**
