### PR TITLE
hyprland: 44.0 -> 44.1

### PR DESCRIPTION
**Pull request by Atemu**
This also fixes the info.json which was missed in the previous update.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Atemu** [comment]
Appears to be running fine on my laptop.

**Comment by JohnRTitor** [comment]
Result of `nixpkgs-review pr 347624` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>hyprlandPlugins.hycov</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>hyprlandPlugins.hypr-dynamic-cursors</li>
    <li>hyprlandPlugins.hyprtrails</li>
  </ul>
</details>
<details>
  <summary>23 packages built:</summary>
  <ul>
    <li>grimblast</li>
    <li>hdrop</li>
    <li>hyprland</li>
    <li>hyprland.dev</li>
    <li>hyprland.man</li>
    <li>hyprlandPlugins.borders-plus-plus</li>
    <li>hyprlandPlugins.csgo-vulkan-fix</li>
    <li>hyprlandPlugins.hy3</li>
    <li>hyprlandPlugins.hyprbars</li>
    <li>hyprlandPlugins.hyprexpo</li>
    <li>hyprlandPlugins.hyprfocus</li>
    <li>hyprlandPlugins.hyprgrass</li>
    <li>hyprlandPlugins.hyprscroller</li>
    <li>hyprlandPlugins.hyprspace</li>
    <li>hyprlandPlugins.hyprsplit</li>
    <li>hyprlandPlugins.hyprwinwrap</li>
    <li>hyprshade</li>
    <li>hyprshade.dist</li>
    <li>hyprshot</li>
    <li>nwg-panel</li>
    <li>nwg-panel.dist</li>
    <li>waybar</li>
    <li>xdg-desktop-portal-hyprland</li>
  </ul>
</details>

**Comment by JohnRTitor** [comment]
Plugins can be updated later.

**Comment by Atemu** [comment]
I'm unfamiliar with Hyprland packaging, what plugins?

**Comment by JohnRTitor** [comment]
There are plugins that can make Hyprland experience easier/enable some features and functionalities, such as hy3, which makes Hyprland have manual tiling like Sway/i3.

Generally these plugins are not backwards compatible with older Hyprland versions, so each time Hyprland is updated, plugins are expected to be updated as well, else they'll cause build failure.

As you can see `hyprtrails` and `hypr-dynamic-cursors` can not be built anymore due to this PR, so they needs to be updated, if available.

**Comment by Atemu** [comment]
Why did you merge this PR then? 

As a distro, we can't just go around breaking packages if we can avoid it. Looking at the plugins mentioned, it appears all we would have had to do to avoid all such breakaged was wait a short while (~days) for compat to be restored.

I'm going to revert this.

***

Unstable does not mean we should just break things willy-nilly, it only means that *necessary* breaking changes aren't coordinated to happen at the same time and can happen at any time.

While there certainly can be the expectation of temporary breakages when avoiding them is unreasonable effort (i.e. core package updates where it is not reasonable for the PR author to find and fix all breakages), this does not extend to cases where it's trivial to avoid the breakage.

Unless something is explicitly time-critical such as i.e. security, getting stuff updated is by no means time-critical; we can always wait a few days or even weeks if we have to. (Though that would be rather extreme.)  
As a distro it's even well "within our rights" to hold back a package update if we think the upstream release needs to be cooked a little longer (i.e. mesa where we never ship .0).

**Comment by JohnRTitor** [comment]
> Why did you merge this PR then?

https://github.com/NixOS/nixpkgs/pull/333074#issuecomment-2278991192

**Comment by Atemu** [comment]
I see.

**Pull request merged**
