### PR TITLE
unbound: 1.17.1 -> 1.18.0

### PR DESCRIPTION
**Pull request by ajs124**
## Description of changes
https://nlnetlabs.nl/news/2023/Aug/30/unbound-1.18.0-released/

## Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Can we add the exporter test into `passhtru.tests`?

**Review by mweinelt — APPROVED** [review]

**Review by fpletz — APPROVED** [review]

**Comment by alyssais** [comment]
This seems to have broken packages that use libunbound. Upstream bug report here: https://github.com/NLnetLabs/unbound/issues/942

**Comment by ajs124** [comment]
Do we have examples of this in nixpkgs? Maybe we should add them to passthru.tests, so we can avoid this in the future.

**Comment by alyssais** [comment]
I don't know.  The prosody test didn't — that was the first thing I checked, because it would have made bisecting this way easier.

**Comment by alyssais** [comment]
Fix: #256682

**Comment by toastal** [comment]
Prosody test didn’t fail, but I’ve been seeing errors in the logs. The project’s maintainers tried to help me debug me the situation, with

```
Sep 23 01:15:55 unbound.queryNY6vePUev1l5	error	Resolver error: out of memory
Sep 23 01:15:55 unbound.queryitu_09eU9gCv	error	Resolver error: out of memory
Sep 23 01:15:55 unbound.queryvYQZshVpQokz	error	Resolver error: out of memory
Sep 23 01:16:13 unbound.query2ePAsnBddWWK	error	Resolver error: out of memory
Sep 23 01:38:46 unbound.queryqqdDNPSCgSja	error	Resolver error: out of memory
Sep 23 01:38:46 unbound.queryMd2zpyd_2sbl	error	Resolver error: out of memory
Sep 23 01:38:46 unbound.queryQ5d5WPNEVyac	error	Resolver error: out of memory
Sep 23 01:41:14 unbound.queryhxUp9aEitTB6	error	Resolver error: out of memory
Sep 23 02:22:55 unbound.querywavOBOtGqrll	error	Resolver error: out of memory
```

**Pull request merged**
