### PR TITLE
magma: 2.7.1 -> 2.7.2

### PR DESCRIPTION
**Pull request by ConnorBaker**
## Description of changes

Version bump.

@NixOS/cuda-maintainers 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ConnorBaker** [comment]
Passed `nix-cuda-test` at https://github.com/connorbaker/nix-cuda-test.

<details>

```console
$ nix run .#nix-cuda-test --override-input nixpkgs github:nixos/nixpkgs/d9faf957f472d8f40818ca16f6826cb3783e22f7 -L
warning: not writing modified lock file of flake 'git+file:///home/connorbaker/nix-cuda-test':
• Updated input 'nixpkgs':
    'github:NixOS/nixpkgs/cf795c35039b544a66a29a9ad3cd4d37bd1d6cb3' (2023-08-21)
  → 'github:nixos/nixpkgs/d9faf957f472d8f40818ca16f6826cb3783e22f7' (2023-08-28)
Global seed set to 42
Using bfloat16 Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Files already downloaded and verified
Files already downloaded and verified
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name      | Type             | Params
-----------------------------------------------
0 | criterion | CrossEntropyLoss | 0     
1 | model     | ViT              | 86.3 M
-----------------------------------------------
86.3 M    Trainable params
0         Non-trainable params
86.3 M    Total params
345.317   Total estimated model params size (MB)
Epoch 9: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 781/781 [01:17<00:00, 10.04it/s, v_num=4, train_loss=2.310, val_loss=2.310]`Trainer.fit` stopped: `max_epochs=10` reached.                                                                                                                                                                                                      
Epoch 9: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 781/781 [01:20<00:00,  9.69it/s, v_num=4, train_loss=2.310, val_loss=2.310]
```

</details>

**Comment by ConnorBaker** [comment]
Result of `nixpkgs-review pr 251872 --extra-nixpkgs-config '{ allowUnfree = true; cudaSupport = true; cudaCapabilities = [ "8.9" ]; }'` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>magma (magma-cuda ,magma_2_7_2)</li>
    <li>magma-cuda-static</li>
    <li>python310Packages.torchWithCuda</li>
    <li>python310Packages.torchWithCuda.dev</li>
    <li>python310Packages.torchWithCuda.dist</li>
    <li>python310Packages.torchWithCuda.lib</li>
    <li>python311Packages.torchWithCuda</li>
    <li>python311Packages.torchWithCuda.dev</li>
    <li>python311Packages.torchWithCuda.dist</li>
    <li>python311Packages.torchWithCuda.lib</li>
  </ul>
</details>

**Comment by ConnorBaker** [comment]
@samuela @SomeoneSerge just looking for a second pair of eyes on this to merge. (I'm the only maintainer.)

**Comment by ConnorBaker** [comment]
@NixOS/rocm-maintainers I was unable to build 2.7.2 for ROCm with just the `rocmSupport = true` flag in `nixpkgs.config`. (So no change from 2.7.1, which also did not build.)

Is it possible the generated binary is large enough that it's failing to link? Is there a flag I can set in `nixpkgs.config` to reduce the number of GPU targets to build for? For example, with CUDA we use `nixpkgs.config.cudaCapabilities` as a list of targets to build for.

**Comment by Flakebi** [comment]
> Is it possible the generated binary is large enough that it's failing to link?

It’s easily possible to run out of ram, but if there’s enough ram, linking shouldn’t fail.
A problem that we have been seeing is that derivations become too big to be stored on cache.nixos.org, but that doesn’t hinder local build.

> Is there a flag I can set in nixpkgs.config to reduce the number of GPU targets to build for?

There are flags for individual packages, but I’m not aware of a global flag.

I’m not that familiar with all the ROCm libraries, so take my answers with a grain of salt.

**Review by samuela — APPROVED** [review]
diff LGTM

**Pull request merged**
