### PR TITLE
nix: 2.13.3 -> 2.15.1

### PR DESCRIPTION
**Pull request by infinisil**
###### Description of changes

Updates the stable Nix version from 2.13.3 to 2.15.1.

There's some information floating around that the 2.14 update is currently blocked, but nobody really explained why that would be the case:

> @SuperSandro2000: This PR blocks bumping nixVersions.stable to 2.14.
> — https://github.com/NixOS/nixpkgs/pull/146515#issuecomment-1475463482

> @Artturin: Will need https://github.com/NixOS/nixpkgs/pull/146515 before a stable bump
> — https://github.com/NixOS/nixpkgs/pull/218889#issuecomment-1451041087

> @balsoft: 2.14.0 is still broken (although now for different reasons).
> — https://github.com/NixOS/nix/pull/5588#issuecomment-1472228955

> @Ma27: Can we also backport the `nix_2_15` attribute to stable, please? The default nix version not, of course %)
> — https://github.com/NixOS/nixpkgs/pull/225800#issuecomment-1506793029

Although these issues have been popping up:
- This Nix PR by @balsoft as the potential root cause: https://github.com/NixOS/nix/pull/5588
- This Nix issue: https://github.com/NixOS/nix/issues/7937

Note that the [release branch-off will be today](https://github.com/NixOS/nixpkgs/issues/223562), so assuming that we're not merging this today this will not make it to NixOS 23.05.

Ping @Mic92 @zowoq @NixOS/nix-team

This work is sponsored by [Antithesis](https://antithesis.com/) :sparkles: 

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kranzes** [comment]
> The other interesting question is... will Nix 2.13 receive backports for bugfixes (and patch-level releases) since it'll be used in NixOS for _at least_ another 6 months?

Do we not backport nix releases?

**Comment by thufschmitt** [comment]
2.14 badly broke some stuff on the profile handling. 2.15 has fixes for most of these, so we should be good with bumping in in nixpkgs

**Comment by thufschmitt** [comment]
> The other interesting question is... will Nix 2.13 receive backports for bugfixes (and patch-level releases) since it'll be used in NixOS for at least another 6 months?

We (the Nix team) never formally committed to anything, but it seems quite obvious that the version in Nixpkgs should get some form of LTS support (at least security issues, and bugfixes as much as reasonable)

**Comment by RaitoBezarius** [comment]
Given we are hours away from the branch-off, it would be nice to ping also *in priority* the release managers on that.

**Comment by RaitoBezarius** [comment]
Given https://github.com/NixOS/nixpkgs/pull/146515 is unmerged and references changes to the NixOS module logic for some paths, this can have consequences we would need to stabilize during the beta.

I am not in favor of this change, stabilization cost is too high in my opinion.

I am available in https://matrix.to/#/#nixos-release-management:nixos.org to discuss this further.

**Comment by RaitoBezarius** [comment]
Also, I was made aware of https://github.com/NixOS/nix/issues/8294 which is not fixed in 2.15.0 AFAIK.

**Comment by thufschmitt** [comment]
> Given https://github.com/NixOS/nixpkgs/pull/146515 is unmerged and references changes to the NixOS module logic for some paths, this can have consequences we would need to stabilize during the beta.

That one isn't needed at all for anything. It merely allows taking advantage of a new optional Nix feature (which overall isn't worth its cost if you ask me).

> Also, I was made aware of https://github.com/NixOS/nix/issues/8294 which is not fixed in 2.15.0 AFAIK.

Uh indeed, there should be a point release for that one

**Comment by RaitoBezarius** [comment]
> > Given #146515 is unmerged and references changes to the NixOS module logic for some paths, this can have consequences we would need to stabilize during the beta.
> 
> That one isn't needed at all for anything. It merely allows taking advantage of a new optional Nix feature (which overall isn't worth its cost if you ask me).

But what happens if someone uses this optional Nix feature? Will it fail in some unknown ways? What are the expectations of our users in that regards?

> > Also, I was made aware of [NixOS/nix#8294](https://github.com/NixOS/nix/issues/8294) which is not fixed in 2.15.0 AFAIK.
> 
> Uh indeed, there should be a point release for that one

Awesome. :)

**Comment by thufschmitt** [comment]
> But what happens if someone uses this optional Nix feature? Will it fail in some unknown ways? What are the expectations of our users in that regards?

There's an explicit warning in the docs saying that it might break whatever. So people shouldn't enable it by accident without knowing what they are doing

**Comment by RaitoBezarius** [comment]
We branched off! Please proceed accordingly :).

**Comment by roberth** [comment]
> Uh indeed, there should be a point release for that one

Seems quite serious. I suppose this is blocked on 2.15.1 release?

**Comment by balsoft** [comment]
I think all the (blocking) issues with https://github.com/NixOS/nix/pull/5588 have been resolved with https://github.com/NixOS/nix/pull/7925 . There's still https://github.com/NixOS/nix/pull/7929 which is a less hacky fix, but it's not required.

**Comment by Kranzes** [comment]
Please add this patch to a commit named  `nixos/nix-fallback-paths: 2.13.3 -> 2.15.1`.
```diff
--- a/nixos/modules/installer/tools/nix-fallback-paths.nix
+++ b/nixos/modules/installer/tools/nix-fallback-paths.nix
@@ -1,7 +1,7 @@
 {
-  x86_64-linux = "/nix/store/mc43d38fibi94pp5crfwacl5gbslccd0-nix-2.13.3";
-  i686-linux = "/nix/store/09m966pj26cgd4ihlg8ihl1106j3vih8-nix-2.13.3";
-  aarch64-linux = "/nix/store/7f191d125akld27gc6jl0r13l8pl7x0h-nix-2.13.3";
-  x86_64-darwin = "/nix/store/1wn9jkvi2zqfjnjgg7lnp30r2q2y8whd-nix-2.13.3";
-  aarch64-darwin = "/nix/store/8w0v2mffa10chrf1h66cbvbpw86qmh85-nix-2.13.3";
+  x86_64-linux = "/nix/store/ny9r65799s7xhp605bc2753sjvzkxrrs-nix-2.15.1";
+  i686-linux = "/nix/store/ck55dz5klc7szi8rx9ghhm8gi2b5q5bw-nix-2.15.1";
+  aarch64-linux = "/nix/store/cl0a02vr28913dgw98hrm45a4baqr3z1-nix-2.15.1";
+  x86_64-darwin = "/nix/store/wq228jdbz16pp2lnxf32n8dv27pw53p8-nix-2.15.1";
+  aarch64-darwin = "/nix/store/x11cpsjg4q236msfz5scc325pfp9xy64-nix-2.15.1";
 }
 ```

**Comment by Mic92** [comment]
Works fine with nix-direnv. nix-eval-jobs on linux works but I have issues with nix headers on darwin.

**Comment by Ericson2314** [comment]
2.15.1+ I do feel like would make for a good 6 month LTS.

**Comment by infinisil** [comment]
Result of `nixpkgs-review pr 233439` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>11 packages failed to build:</summary>
  <ul>
    <li>emscriptenPackages.libxml2</li>
    <li>emscriptenPackages.libxml2.bin</li>
    <li>emscriptenPackages.libxml2.dev</li>
    <li>emscriptenPackages.libxml2.doc</li>
    <li>emscriptenPackages.xmlmirror</li>
    <li>emscriptenPackages.xmlmirror.doc</li>
    <li>faustStk</li>
    <li>python310Packages.django-hijack-admin</li>
    <li>python310Packages.django-hijack-admin.dist</li>
    <li>python311Packages.django-hijack-admin</li>
    <li>python311Packages.django-hijack-admin.dist</li>
  </ul>
</details>
<details>
  <summary>205 packages built:</summary>
  <ul>
    <li>activitywatch</li>
    <li>ansible-language-server</li>
    <li>antora</li>
    <li>appvm</li>
    <li>ariang</li>
    <li>audiobookshelf</li>
    <li>authelia</li>
    <li>aw-server-rust</li>
    <li>bitwarden</li>
    <li>botamusique</li>
    <li>bundix</li>
    <li>cabal2nix</li>
    <li>cached-nix-shell</li>
    <li>cdxgen</li>
    <li>common-updater-scripts</li>
    <li>crate2nix</li>
    <li>crystal2nix</li>
    <li>cz-cli</li>
    <li>deltachat-desktop</li>
    <li>dep2nix</li>
    <li>docker-compose-language-service</li>
    <li>dot-language-server</li>
    <li>dydisnix</li>
    <li>element-desktop</li>
    <li>element-desktop-wayland</li>
    <li>emscripten</li>
    <li>emscriptenPackages.json_c</li>
    <li>emscriptenPackages.json_c.dev</li>
    <li>emscriptenPackages.zlib</li>
    <li>epgstation</li>
    <li>evcc</li>
    <li>faust</li>
    <li>faust2alqt</li>
    <li>faust2alsa</li>
    <li>faust2csound</li>
    <li>faust2firefox</li>
    <li>faust2jack</li>
    <li>faust2jackrust</li>
    <li>faust2jaqt</li>
    <li>faust2ladspa</li>
    <li>faust2lv2</li>
    <li>faust2sc</li>
    <li>faustPhysicalModeling</li>
    <li>faustlive</li>
    <li>forgejo</li>
    <li>forgejo.data</li>
    <li>fusionInventory</li>
    <li>github-copilot-cli</li>
    <li>go2nix</li>
    <li>go2nix.man</li>
    <li>google-clasp</li>
    <li>guitarix</li>
    <li>harmonia</li>
    <li>hred</li>
    <li>iosevka</li>
    <li>iosevka-comfy.comfy</li>
    <li>iosevka-comfy.comfy-duo</li>
    <li>iosevka-comfy.comfy-fixed</li>
    <li>iosevka-comfy.comfy-motion</li>
    <li>iosevka-comfy.comfy-motion-duo</li>
    <li>iosevka-comfy.comfy-motion-fixed</li>
    <li>iosevka-comfy.comfy-wide</li>
    <li>iosevka-comfy.comfy-wide-duo</li>
    <li>iosevka-comfy.comfy-wide-fixed</li>
    <li>iosevka-comfy.comfy-wide-motion</li>
    <li>iosevka-comfy.comfy-wide-motion-duo</li>
    <li>iosevka-comfy.comfy-wide-motion-fixed</li>
    <li>isso</li>
    <li>isso.dist</li>
    <li>isso.doc</li>
    <li>jellyfin</li>
    <li>jellyfin-media-player</li>
    <li>jellyfin-web</li>
    <li>kapitonov-plugins-pack</li>
    <li>kaufkauflist</li>
    <li>kavita</li>
    <li>libnixxml</li>
    <li>lua51Packages.luarocks-nix</li>
    <li>lua52Packages.luarocks-nix</li>
    <li>lua53Packages.luarocks-nix</li>
    <li>lua54Packages.luarocks-nix</li>
    <li>luajitPackages.luarocks-nix</li>
    <li>lv_img_conv</li>
    <li>magnetophonDSP.CharacterCompressor</li>
    <li>magnetophonDSP.CompBus</li>
    <li>magnetophonDSP.ConstantDetuneChorus</li>
    <li>magnetophonDSP.LazyLimiter</li>
    <li>magnetophonDSP.MBdistortion</li>
    <li>magnetophonDSP.RhythmDelay</li>
    <li>magnetophonDSP.VoiceOfFaust</li>
    <li>magnetophonDSP.faustCompressors</li>
    <li>magnetophonDSP.pluginUtils</li>
    <li>magnetophonDSP.shelfMultiBand</li>
    <li>matrix-appservice-irc</li>
    <li>memos</li>
    <li>mongosh</li>
    <li>mooSpace</li>
    <li>mpvScripts.webtorrent-mpv-hook</li>
    <li>navidrome</li>
    <li>nc4nix</li>
    <li>nest-cli</li>
    <li>newman</li>
    <li>nil</li>
    <li>nix</li>
    <li>nix-binary-cache</li>
    <li>nix-bundle</li>
    <li>nix-direnv</li>
    <li>nix-doc</li>
    <li>nix-du</li>
    <li>nix-index</li>
    <li>nix-init</li>
    <li>nix-pin</li>
    <li>nix-plugins</li>
    <li>nix-prefetch</li>
    <li>nix-prefetch-bzr</li>
    <li>nix-prefetch-cvs</li>
    <li>nix-prefetch-docker</li>
    <li>nix-prefetch-git</li>
    <li>nix-prefetch-hg</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-prefetch-svn</li>
    <li>nix-serve</li>
    <li>nix-serve-ng</li>
    <li>nix-simple-deploy</li>
    <li>nix-template</li>
    <li>nix-update</li>
    <li>nix-update-source</li>
    <li>nix-update-source.dist</li>
    <li>nix-update.dist</li>
    <li>nix.debug</li>
    <li>nix.dev</li>
    <li>nix.doc</li>
    <li>nix.man</li>
    <li>nixStatic</li>
    <li>nixStatic.dev</li>
    <li>nixVersions.nix_2_13</li>
    <li>nixVersions.nix_2_13.debug</li>
    <li>nixVersions.nix_2_13.dev</li>
    <li>nixVersions.nix_2_13.doc</li>
    <li>nixVersions.nix_2_13.man</li>
    <li>nixos-generators</li>
    <li>nixos-rebuild</li>
    <li>nixos-shell</li>
    <li>nixpkgs-hammering</li>
    <li>nixpkgs-review</li>
    <li>nixpkgs-review.dist</li>
    <li>node-manta</li>
    <li>node2nix</li>
    <li>npins</li>
    <li>nuget-to-nix</li>
    <li>nurl</li>
    <li>nvfetcher</li>
    <li>open-music-kontrollers.mephisto</li>
    <li>open-stage-control</li>
    <li>osmtogeojson</li>
    <li>paperless-ngx</li>
    <li>photoprism</li>
    <li>pnpm-lock-export</li>
    <li>prefetch-npm-deps</li>
    <li>prefetch-yarn-deps</li>
    <li>pyCA</li>
    <li>pyCA.dist</li>
    <li>python310Packages.django-hijack</li>
    <li>python310Packages.django-hijack.dist</li>
    <li>python310Packages.nix-kernel</li>
    <li>python310Packages.nix-kernel.dist</li>
    <li>python311Packages.django-hijack</li>
    <li>python311Packages.django-hijack.dist</li>
    <li>python311Packages.nix-kernel</li>
    <li>python311Packages.nix-kernel.dist</li>
    <li>resumed</li>
    <li>rnix-lsp</li>
    <li>sbomnix</li>
    <li>sbomnix.dist</li>
    <li>schildichat-desktop</li>
    <li>schildichat-desktop-wayland</li>
    <li>sharing</li>
    <li>slskd</li>
    <li>sunshine</li>
    <li>swiftpm2nix</li>
    <li>tambura</li>
    <li>terminal-stocks</li>
    <li>terranix</li>
    <li>torq</li>
    <li>triton</li>
    <li>twspace-crawler</li>
    <li>update-nix-fetchgit</li>
    <li>update-python-libraries</li>
    <li>uptime-kuma</li>
    <li>vieb</li>
    <li>vsce</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
    <li>vulnix</li>
    <li>vulnix.dist</li>
    <li>vulnix.doc</li>
    <li>vulnix.man</li>
    <li>webcord</li>
    <li>webcord-vencord</li>
    <li>webtorrent_desktop</li>
    <li>wp4nix</li>
    <li>yarn-lock-converter</li>
    <li>yarn2nix</li>
    <li>zigbee2mqtt</li>
    <li>zinc</li>
    <li>zrythm</li>
  </ul>
</details>

**Comment by infinisil** [comment]
The above PR is now merged, so this will fix CI. Additionally [Nix 2.16 was just released](https://discourse.nixos.org/t/nix-2-16-released/28597) and [already assigned as the unstable default in Nixpkgs](https://github.com/NixOS/nixpkgs/pull/235221).

I rebased this PR on top of master with these two changes now.

**Comment by RaitoBezarius** [comment]
> The above PR is now merged, so this will fix CI. Additionally [Nix 2.16 was just released](https://discourse.nixos.org/t/nix-2-16-released/28597) and [already assigned as the unstable default in Nixpkgs](https://github.com/NixOS/nixpkgs/pull/235221).
> 
> I rebased this PR on top of master with these two changes now.

But the stable is now also unstable? But has this new version of Nix been tested :) ?

**Comment by infinisil** [comment]
Good point, I don't think there's any policy for that but I guess something like this would make sense:

> Upon new minor Nix releases, `nixVersions.unstable` should be updated to the new release. If no major breaking changes were reported with the previous `nixVersions.unstable` release, `nixVersions.stable` may be set to the previous `nixVersions.unstable`.

Therefore `stable` is always lagging behind `unstable` by at least one minor release.

Normally we shouldn't require this for packages, but Nix's poor track-record of making breaking changes and its importance should make us consider this.

Since we already got confirmation by the Nix team that 2.15 is looking good, I'll make `stable` point to `2.15` here.

**Comment by infinisil** [comment]
I now also updated the `nix-fallback-paths.nix` file. That file is seemingly entirely undocumented, but because I was annoyed with having to update it manually, I created https://github.com/NixOS/nixpkgs/pull/235463 to automate this a bit better.

**Comment by infinisil** [comment]
Result of `nixpkgs-review pr 233439` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.django-hijack-admin</li>
    <li>python310Packages.django-hijack-admin.dist</li>
    <li>python311Packages.django-hijack-admin</li>
    <li>python311Packages.django-hijack-admin.dist</li>
  </ul>
</details>
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>7 packages failed to build:</summary>
  <ul>
    <li>emscriptenPackages.libxml2</li>
    <li>emscriptenPackages.libxml2.bin</li>
    <li>emscriptenPackages.libxml2.dev</li>
    <li>emscriptenPackages.libxml2.doc</li>
    <li>emscriptenPackages.xmlmirror</li>
    <li>emscriptenPackages.xmlmirror.doc</li>
    <li>faustStk</li>
  </ul>
</details>
<details>
  <summary>208 packages built:</summary>
  <ul>
    <li>activitywatch</li>
    <li>ansible-language-server</li>
    <li>antora</li>
    <li>appvm</li>
    <li>ariang</li>
    <li>audiobookshelf</li>
    <li>authelia</li>
    <li>aw-server-rust</li>
    <li>bitwarden</li>
    <li>botamusique</li>
    <li>bundix</li>
    <li>cabal2nix</li>
    <li>cached-nix-shell</li>
    <li>cdxgen</li>
    <li>common-updater-scripts</li>
    <li>crate2nix</li>
    <li>crystal2nix</li>
    <li>cz-cli</li>
    <li>deltachat-desktop</li>
    <li>dep2nix</li>
    <li>docker-compose-language-service</li>
    <li>dot-language-server</li>
    <li>dydisnix</li>
    <li>element-desktop</li>
    <li>element-desktop-wayland</li>
    <li>emscripten</li>
    <li>emscriptenPackages.json_c</li>
    <li>emscriptenPackages.json_c.dev</li>
    <li>emscriptenPackages.zlib</li>
    <li>epgstation</li>
    <li>eslint_d</li>
    <li>evcc</li>
    <li>faust</li>
    <li>faust2alqt</li>
    <li>faust2alsa</li>
    <li>faust2csound</li>
    <li>faust2firefox</li>
    <li>faust2jack</li>
    <li>faust2jackrust</li>
    <li>faust2jaqt</li>
    <li>faust2ladspa</li>
    <li>faust2lv2</li>
    <li>faust2sc</li>
    <li>faustPhysicalModeling</li>
    <li>faustlive</li>
    <li>forgejo</li>
    <li>forgejo.data</li>
    <li>fusionInventory</li>
    <li>github-copilot-cli</li>
    <li>go2nix</li>
    <li>go2nix.man</li>
    <li>google-clasp</li>
    <li>guitarix</li>
    <li>harmonia</li>
    <li>hred</li>
    <li>iosevka</li>
    <li>iosevka-comfy.comfy</li>
    <li>iosevka-comfy.comfy-duo</li>
    <li>iosevka-comfy.comfy-fixed</li>
    <li>iosevka-comfy.comfy-motion</li>
    <li>iosevka-comfy.comfy-motion-duo</li>
    <li>iosevka-comfy.comfy-motion-fixed</li>
    <li>iosevka-comfy.comfy-wide</li>
    <li>iosevka-comfy.comfy-wide-duo</li>
    <li>iosevka-comfy.comfy-wide-fixed</li>
    <li>iosevka-comfy.comfy-wide-motion</li>
    <li>iosevka-comfy.comfy-wide-motion-duo</li>
    <li>iosevka-comfy.comfy-wide-motion-fixed</li>
    <li>isso</li>
    <li>isso.dist</li>
    <li>isso.doc</li>
    <li>jellyfin</li>
    <li>jellyfin-media-player</li>
    <li>jellyfin-web</li>
    <li>kapitonov-plugins-pack</li>
    <li>kaufkauflist</li>
    <li>kavita</li>
    <li>libnixxml</li>
    <li>lua51Packages.luarocks-nix</li>
    <li>lua52Packages.luarocks-nix</li>
    <li>lua53Packages.luarocks-nix</li>
    <li>lua54Packages.luarocks-nix</li>
    <li>luajitPackages.luarocks-nix</li>
    <li>lv_img_conv</li>
    <li>magnetophonDSP.CharacterCompressor</li>
    <li>magnetophonDSP.CompBus</li>
    <li>magnetophonDSP.ConstantDetuneChorus</li>
    <li>magnetophonDSP.LazyLimiter</li>
    <li>magnetophonDSP.MBdistortion</li>
    <li>magnetophonDSP.RhythmDelay</li>
    <li>magnetophonDSP.VoiceOfFaust</li>
    <li>magnetophonDSP.faustCompressors</li>
    <li>magnetophonDSP.pluginUtils</li>
    <li>magnetophonDSP.shelfMultiBand</li>
    <li>matrix-appservice-irc</li>
    <li>memos</li>
    <li>mirakurun</li>
    <li>mongosh</li>
    <li>mooSpace</li>
    <li>mpvScripts.webtorrent-mpv-hook</li>
    <li>navidrome</li>
    <li>nc4nix</li>
    <li>nest-cli</li>
    <li>newman</li>
    <li>nil</li>
    <li>nix</li>
    <li>nix-binary-cache</li>
    <li>nix-bundle</li>
    <li>nix-direnv</li>
    <li>nix-doc</li>
    <li>nix-du</li>
    <li>nix-index</li>
    <li>nix-init</li>
    <li>nix-pin</li>
    <li>nix-plugins</li>
    <li>nix-prefetch</li>
    <li>nix-prefetch-bzr</li>
    <li>nix-prefetch-cvs</li>
    <li>nix-prefetch-docker</li>
    <li>nix-prefetch-git</li>
    <li>nix-prefetch-hg</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-prefetch-svn</li>
    <li>nix-serve</li>
    <li>nix-serve-ng</li>
    <li>nix-simple-deploy</li>
    <li>nix-template</li>
    <li>nix-update</li>
    <li>nix-update-source</li>
    <li>nix-update-source.dist</li>
    <li>nix-update.dist</li>
    <li>nix.debug</li>
    <li>nix.dev</li>
    <li>nix.doc</li>
    <li>nix.man</li>
    <li>nixStatic</li>
    <li>nixStatic.dev</li>
    <li>nixVersions.nix_2_13</li>
    <li>nixVersions.nix_2_13.debug</li>
    <li>nixVersions.nix_2_13.dev</li>
    <li>nixVersions.nix_2_13.doc</li>
    <li>nixVersions.nix_2_13.man</li>
    <li>nixos-generators</li>
    <li>nixos-rebuild</li>
    <li>nixos-shell</li>
    <li>nixpkgs-hammering</li>
    <li>nixpkgs-review</li>
    <li>nixpkgs-review.dist</li>
    <li>node-manta</li>
    <li>node2nix</li>
    <li>npins</li>
    <li>nuget-to-nix</li>
    <li>nvfetcher</li>
    <li>open-music-kontrollers.mephisto</li>
    <li>open-stage-control</li>
    <li>osmtogeojson</li>
    <li>paperless-ngx</li>
    <li>photoprism</li>
    <li>pnpm-lock-export</li>
    <li>prefetch-npm-deps</li>
    <li>prefetch-yarn-deps</li>
    <li>pyCA</li>
    <li>pyCA.dist</li>
    <li>python310Packages.django-hijack</li>
    <li>python310Packages.django-hijack.dist</li>
    <li>python310Packages.nix-kernel</li>
    <li>python310Packages.nix-kernel.dist</li>
    <li>python311Packages.django-hijack</li>
    <li>python311Packages.django-hijack.dist</li>
    <li>python311Packages.nix-kernel</li>
    <li>python311Packages.nix-kernel.dist</li>
    <li>resumed</li>
    <li>rnix-lsp</li>
    <li>sbomnix</li>
    <li>sbomnix.dist</li>
    <li>schildichat-desktop</li>
    <li>schildichat-desktop-wayland</li>
    <li>sharing</li>
    <li>slskd</li>
    <li>sunshine</li>
    <li>swiftpm2nix</li>
    <li>tambura</li>
    <li>terminal-stocks</li>
    <li>terranix</li>
    <li>torq</li>
    <li>triton</li>
    <li>twspace-crawler</li>
    <li>update-nix-fetchgit</li>
    <li>update-python-libraries</li>
    <li>uptime-kuma</li>
    <li>vencord</li>
    <li>vencord-web-extension</li>
    <li>vieb</li>
    <li>vsce</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
    <li>vulnix</li>
    <li>vulnix.dist</li>
    <li>vulnix.doc</li>
    <li>vulnix.man</li>
    <li>webcord</li>
    <li>webcord-vencord</li>
    <li>webtorrent_desktop</li>
    <li>wp4nix</li>
    <li>yarn-lock-converter</li>
    <li>yarn2nix</li>
    <li>zigbee2mqtt</li>
    <li>zinc</li>
    <li>zrythm</li>
  </ul>
</details>

I can confirm that the failing packages also failed before this PR.

Additionally I ran some seemingly relevant NixOS tests, all successful:
```
❯ nix-build nix-serve-ssh.nix hydra nix-serve.nix nix-ld.nix
/nix/store/idw8lr8g11lm5r4l6bgra1f7mzpm2i1c-vm-test-run-nix-ssh-serve
/nix/store/4b5x6jd7w1phm04d5la502l7mx36vnww-vm-test-run-hydra-hydra_unstable
/nix/store/d2hd0l3gnf5l7ikv9zidzaxz84fnx3cq-vm-test-run-nix-serve
/nix/store/y8ig4zsh9a4a3r28wvnwl7dyji52a0xb-vm-test-run-nix-ld
```

Addionally I switched my system to 2.15.1 and didn't notice anything breaking.

**Comment by infinisil** [comment]
I guess it's good that we don't update to 2.16 yet: https://github.com/NixOS/nix/issues/8437

**Comment by RaitoBezarius** [comment]
Given the new occurrence,

> Good point, I don't think there's any policy for that but I guess something like this would make sense:

I think we should make a policy for that, or, at least, in nixpkgs. It does not cost us too much.

**Comment by infinisil** [comment]
Can we merge this?

**Comment by RaitoBezarius** [comment]
It would be nice to have https://github.com/NixOS/nix/commit/61ddfa154bcfa522819781d23e40e984f38dfdeb in 2.15.

**Comment by happysalada** [comment]
nix 2.15.1 has https://github.com/NixOS/nix/issues/8480 (which effectively breaks nix copy if ssh has controlmaster).
It seems that 2.17 is a week away so might not be worth doing the upgrade to 2.16 before then. But for future reference, I wonder if that problem would have warranted an early update of nix or if it would be in the category of "just don't use controlmaster" consideration.

**Comment by RaitoBezarius** [comment]
2.15 is the Nix version for the 23.05 release, so we need a backport too for that.

**Comment by roberth** [comment]
> 2.15 is the Nix version for the 23.05 release, so we need a backport too for that.

Is it? The release branch has 2.13.3.

**Comment by RaitoBezarius** [comment]
> > 2.15 is the Nix version for the 23.05 release, so we need a backport too for that.
> 
> Is it? The release branch has 2.13.3.

Please ignore me, I got things confused :see_no_evil:…

**Pull request merged**
