### PR TITLE
libcli: 1.9.7 -> 1.10.7 (wait for upstream fix)

### PR DESCRIPTION
**Pull request by trofi**

### CODE REVIEW

**Comment by illdefined** [comment]
Result of `nixpkgs-review pr 147749` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>libcli</li>
    <li>netsniff-ng</li>
  </ul>
</details>

**Comment by bobby285271** [comment]
It will be nice to remove the unused `fetchurl` from args.

**Comment by trofi** [comment]
Good point! Removed unused `fetchurl`.

**Comment by bobby285271** [comment]
https://logs.nix.ci/?key=nixos/nixpkgs.147749&attempt_id=54ba70b3-6044-4233-ab14-a2ecea5c68e8
https://hydra.nixos.org/job/nixpkgs/trunk/libcli.x86_64-darwin

Failed to build on x86_64-darwin and seem to be a regression?

**Comment by trofi** [comment]
Ah, good point. Looks like it now uses `glibc`-specific API:
```
libcli.c:2521:41: error: implicit declaration of function 'strchrnul' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  if (help && !(c->help = strndup(help, strchrnul(help, '\v') - help))) {
                                        ^
```

**Comment by trofi** [comment]
Filed https://github.com/dparrish/libcli/issues/78 upstream issue.

**Comment by trofi** [comment]
Does not seem to happen.

**Pull request closed without merging**
