### PR TITLE
mastodon: build nodejs modules with fetchYarnDeps

### PR DESCRIPTION
**Pull request by Izorkin**
###### Description of changes
Build nodejs modules with fetchYarnDeps

cc @erictapen
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by erictapen — APPROVED** [review]
This makes a ton of sense. Looks and builds great. Thanks a lot!

Could you squash the two commits into one, or is there a reason for the separation?

**Comment by Izorkin** [comment]
> Could you squash the two commits into one, or is there a reason for the separation?

Separated commits to make it easier to view changes.

**Comment by Izorkin** [comment]
Warning messages appear during the build process:
```
[3/5] Linking dependencies...
warning " > react-redux-loading-bar@4.0.8" has incorrect peer dependency "react-redux@^3.0.0 || ^4.0.0 || ^5.0.0".
...
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
sh: /build/mastodon-patched/bin/yarn: not found
sh: /build/mastodon-patched/bin/yarn: not found
...
Compiled all packs in /build/mastodon-patched/public/packs
warning You don't appear to have an internet connection. Try the --offline flag to use the cache for registry queries.
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
```
Any idea how to fix these warnings?

If remove `bin/ruby` `yarn` error disappears:
```
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
sh: /build/mastodon-patched/bin/yarn: not found
sh: /build/mastodon-patched/bin/yarn: not found
```
Did not include this change in this PR.

**Comment by erictapen** [comment]
> Separated commits to make it easier to view changes.

Mh, that logic wasn't obvious for me from first glance. Having the commits named more descriptively than part1/part2 would've made it easier to understand for me probably. Thanks for squashing anyway.

> Warning messages appear during the build process

We're speaking about the mastodon-modules derivation, right? In https://github.com/NixOS/nixpkgs/pull/165036 I can only find the 

```
warning " > react-redux-loading-bar@4.0.8" has incorrect peer dependency "react-redux@^3.0.0 || ^4.0.0 || ^5.0.0".
```

warning, so I guess most of the problems solved themself? Also doesn't sound too dramatic. Weird though that they won't throw an error on incorrect version bounds.

**Comment by Izorkin** [comment]
> We're speaking about the mastodon-modules derivation, right? In #165036 I can only find the

Yes, about the warning messages in the mastodon module block.

Is PR ready to merge?

**Pull request merged**
