### PR TITLE
atuin: 13.0.1 -> 14.0.0

### PR DESCRIPTION
**Pull request by 0x4A6F**
###### Description of changes

Upgrade to [14.0.0](https://github.com/ellie/atuin/releases/tag/v14.0.0) including these [changes](https://github.com/ellie/atuin/compare/v13.0.1...v14.0.0).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by figsoda** [comment]
In case you didn't see this, do you have any idea about https://github.com/NixOS/nixpkgs/pull/219412#issuecomment-1492341820? The package seems to be building fine on hydra and I don't know how to reproduce this

**Comment by SuperSandro2000** [comment]
Shouldn't ``xvfb-run.meta.available`` be ``lib.meta.availableOn stdenv.hostPlatform xvfb-run``?

**Review by SuperSandro2000 — APPROVED** [review]
diff by itself is LGTM

**Comment by 0x4A6F** [comment]
I think this update is predestined for an entry in `release-notes.md`, at least for people out there running their own `atuin server`.

**Comment by happysalada** [comment]
The ci is failing the darwin build on some hash mismatch https://github.com/NixOS/nixpkgs/pull/224264/checks?check_run_id=12451154469 . The different hash is the cargoHash, could it be that the dependencies are different on darwin and on linux ?

@figsoda I'm not sure what he is talking about, I'm running atuin on darwin and don't have a problem. I'm on x86_64.

this release adds support for nushell, should we add it to the `gen-completions` script ?

**Comment by figsoda** [comment]
> The different hash is the cargoHash, could it be that the dependencies are different on darwin and on linux ?

Cargo should always vendor all dependencies on all platforms, so I don't think that would be causing the issue. I looked through the changes to `Cargo.lock` on diff.rs and couldn't find any suspicious changes. Might be useful to do a diffoscope of the unpacked `cargoDeps` on different platforms.

> @figsoda I'm not sure what he is talking about, I'm running atuin on darwin and don't have a problem. I'm on x86_64.

I think we have to ignore it for now until we get a response to https://github.com/NixOS/nixpkgs/pull/219412#issuecomment-1493290938, since none of us can reproduce it.

> this release adds support for nushell, should we add it to the gen-completions script ?

Adding it to `installShellCompletion` would cause a mass rebuild. It would be nice to if anyone knows how/where to install nushell completions, but I'm fine either way.

**Comment by happysalada** [comment]
let's leave the shellCompletions like this for now, I'll do another pass at this once I find out exactly where to add them.

**Comment by figsoda** [comment]
Isn't this going to break darwin?

**Comment by 0x4A6F** [comment]
I was able to build this commit on remote builders for `aarch64-darwin` and `x86_64-darwin`.

**Comment by happysalada** [comment]
I've just tested on darwin and indeed the cargohash is different
https://github.com/NixOS/nixpkgs/pull/224411
looking at the cargo lock there is a linux-raw crate that looks like it wouldn't be included on darwin.

**Pull request merged**
