### PR TITLE
haskellPackages.hercules-ci-cnix-store: nix_2_16 -> nix_2_18

### PR DESCRIPTION
**Pull request by wegank**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by wegank** [comment]
@ofborg build cachix cachix.passthru.tests

**Comment by maralorn** [comment]
Sorry, I don’t know how you are related to cachix/hercules-ci. Why bump this now?
Is this coordinated with @roberth and @domenkozar ?

**Comment by wegank** [comment]
> Why bump this now?

Cachix no longer builds on master and release-23.11, due to Nix 2.16 being marked as insecure (https://github.com/NixOS/nix/security/advisories/GHSA-2ffj-w4mj-pg37).

If this PR is not viable, I'll create a PR to remove Cachix from the release-critical jobs.

**Comment by maralorn** [comment]
Ah, that is very relevant context. Thank you! Maybe we can give @domenkozar a few hours to react?

**Comment by roberth** [comment]
I'm working on a branch that bumps that cluster of packages separately from `haskell-updates`, which would have fixed this if it were merged in a timely manner. I will use `non-hackage-packages.nix`, as I expect that that won't interfere with `haskell-updates`.

**Comment by roberth** [comment]
@maralorn I'll clean it up.

- https://github.com/NixOS/nixpkgs/pull/294055

**Pull request closed without merging**
