### PR TITLE
vscode{,ium}: 1.35.1 

### PR DESCRIPTION
**Pull request by eadwu**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by worldofpeace** [comment]
`vscodium` renamed its `executableName` to `codium`. Pushed the change to reflect that.

**Review by worldofpeace — APPROVED** [review]
Executed both packages successfully on NixOS x86_64-linux.

Also verified all hashes.

**Comment by worldofpeace** [comment]
backported in
* 0ff6b8863a8916766616845cc9f723edd6ce3558
* 1601f559e89ba71091faa26888711d4dd24c2d4d

**Comment by Synthetica9** [comment]
This update isn't fully backwards compatible, the `vscodium` binary was renamed to `codium`. (See https://github.com/VSCodium/vscodium/pull/176). Do we want to symlink this?

**Comment by worldofpeace** [comment]
For NixOS I'd think most people wouldn't notice because of the desktop file.
But yes I did overlook that, a symlink wouldn't hurt for people who launch it through a shell.

**Comment by worldofpeace** [comment]
Also note that vscodium was just recently added to stable (last backports for vscode).

**Comment by Synthetica9** [comment]
@worldofpeace: #63522

**Pull request merged**
