### PR TITLE
enlightenment.enlightenment: 0.23.1 -> 0.24.0, cleanup and fixes

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

~~**Needs testing.**~~

- enlightenment.enlightenment: format
- enlightenment.enlightenment: 0.23.1 -> [0.24.0](https://www.enlightenment.org/news/e24.0)
- enlightenment.enlightenment: update dependence list
- enlightenment.enlightenment: no need to fix edje_cc path
- enlightenment.enlightenment: provides display manager session
- nixos/enlightenment: use display manager session packages
- nixos/enlightenment: no need to explicitly set XDG_MENU_PREFIX
- nixos/enlightenment: remove some themes and xauth
- nixos/enlightenment: add ephoto and rage
- enlightenment.enlightenment: do not explicitly enable parallel building
- enlightenment.enlightenment: fix setuid wrappers (see also https://github.com/NixOS/nixpkgs/issues
- nixos/tests/enlightenment: fix some steps in the first time wizard

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by emilazy** [comment]
Now that there's only one setuid executable, I suggest fixing #87678 by removing removing `enlightenment.suid-exes.patch` and manually setting `security.wrappers` in the module rather than using the [existing import-from-derivation](https://github.com/NixOS/nixpkgs/blob/3676aedae0b3312d9db1132bc619e786e8bd7849/nixos/modules/services/x11/desktop-managers/enlightenment.nix#L66). Although the the test doesn't block the channel, there's no reason to unnecessarily prevent it from being able to run on Hydra, and building packages during NixOS system configuration evaluation should generally be avoided where possible.

**Comment by romildo** [comment]
> Now that there's only one setuid executable, I suggest fixing #87678 by removing `enlightenment.suid-exes.patch` and manually setting `security.wrappers` in the module rather than using the [existing import-from-derivation](https://github.com/NixOS/nixpkgs/blob/3676aedae0b3312d9db1132bc619e786e8bd7849/nixos/modules/services/x11/desktop-managers/enlightenment.nix#L66).

@emilazy Is it ok now?

**Comment by emilazy** [comment]
Looks like the import-from-derivation should be gone now, yep. Let's see what ofborg thinks of it; not sure if ofborg has IFD disabled but it's worth running the test anyway.

@ofborg test enlightenment

**Comment by romildo** [comment]
@ofborg test enlightenment

**Comment by romildo** [comment]
@emilazy  It seems that ofborg test has passed well.

**Pull request merged**
