### PR TITLE
codeowners: add jonringer as python packages codeowner

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change

@FRidh has a lot on his plate, I would like to help him out. For most python packages, my knowledge should suffice, and should enable him to focus on other things.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Review by c0bw3b — APPROVED** [review]

**Review by worldofpeace — APPROVED** [review]
Yay! :confetti_ball: Always nice to see this happening, python ecosystem needs maintainers.
Guess this makes @jonringer official collaborator @FRidh?

@jonringer Also be prepared for pings when people change their PR bases.

**Comment by jonringer** [comment]
That's fine, i usually check github like 10x a day now... so the spam shouldn't be too overwhelming

**Comment by jonringer** [comment]
I'll take that as everyone is okay with me getting spammed :)

**Comment by FRidh** [comment]
Thanks! Be prepared for the notifications avalanche ;-)

**Pull request merged**
