### PR TITLE
Update Gitlab to 12.1

### PR DESCRIPTION
**Pull request by bgamari**
##### Motivation for this change

Update GitLab to 12.1.2. Also fix an issue where the nixos module failed to start as it tried to delete the `hooks` directories with non-recursive `rm`.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @fpletz @globin  @roblabla

### CODE REVIEW

**Review by srhb — COMMENTED** [review]
Looks like this or some earlier change broke the test. It's hard to tell, because apparently there's some other, earlier breakage currently in master as well. Investigating..

**Comment by srhb** [comment]
Looks like the tests were broken in #64550 already.

**Comment by srhb** [comment]
I've opened #65681 for the tests instead.

**Comment by flokli** [comment]
This should be covered by #66621, I cherry-picked 
0e6b805 into it aswell. Thanks!

**Pull request closed without merging**
