### PR TITLE
syslinux: fix missing mtools dependency

### LINKED ISSUE #11472: syslinux: missing mtools dependency
It calls mcopy, which is in `mtools`:
```
syslinux /dev/sdc
sh: mcopy: command not found
```

### PR DESCRIPTION
**Pull request by jgillich**
closes #11472

### CODE REVIEW

**Comment by dezgeg** [comment]
This doesn't seem to actually make `mtools` a runtime dependency: `nix-store -q --tree /nix/store/k31kkci0f5w9kxa4pr7q97zd6c6zdz11-syslinux-2015-11-09 | grep mtools` returns no hits.

The references to mcopy are:
{code}
$ strings /nix/store/k31kkci0f5w9kxa4pr7q97zd6c6zdz11-syslinux-2015-11-09/bin/syslinux | grep mcopy                                                                                                                                                           21:52:22
mcopy -D o -D O -o - s:/ldlinux.sys
mcopy -D o -D O -o - s:/ldlinux.c32
{code}

So you'd have to either patch the absolute path to `mcopy` there, or use `wrapProgram`.

**Comment by jgillich** [comment]
@dezgeg Ok I'm still rebuilding because of bash and don't know how long it will take, can you check if this one works? Thanks!

**Comment by jgillich** [comment]
```
$ nix-store -q --tree /nix/store/k4zh2spsaax99y9zjv3smdkwvnr00pbk-syslinux-2015-11-09/ | grep mtools
+---/nix/store/7d5cxpcvkygsfmvrys7sz3ywj8bj6b9r-mtools-4.0.18
|   +---/nix/store/7d5cxpcvkygsfmvrys7sz3ywj8bj6b9r-mtools-4.0.18 [...]
```

Should be all good now.

**Comment by jgillich** [comment]
@jagajaga Mind taking a look? Thanks!

**Comment by jagajaga** [comment]
I'm not a syslinux guy :(
Cc @Phreedom @wkennington

**Comment by wkennington** [comment]
Lgtm

**Comment by jgillich** [comment]
Somebody still has to hit merge. :)

**Pull request merged**
