### PR TITLE
ghostwriter: init at 1.5.0

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dotlambda** [comment]
@GrahamcOfBorg build ghostwriter

**Comment by dotlambda** [comment]
Why did it work now when it didn't work before? I only changed `meta`.

**Comment by grahamc** [comment]
The aarch64 builder was updated between those to builds to fix a problem with `/bin/sh`, which was fixed in https://github.com/NixOS/nixpkgs/pull/34628.

**Comment by dotlambda** [comment]
Okay, thanks! Then I'll have to revisit an older PR to enable aarch64.

**Pull request merged**
