### PR TITLE
openimageio: 2.4.6.1 -> 2.4.10.0

### PR DESCRIPTION
**Pull request by panicgh**
###### Description of changes

Update to the most recent release and unpin from fmt_8.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>blender</li>
    <li>blender-hip</li>
    <li>embree</li>
    <li>embree2</li>
    <li>olive-editor</li>
    <li>openimageio</li>
    <li>openimageio.bin</li>
    <li>openimageio.dev</li>
    <li>openimageio.doc</li>
    <li>osl</li>
    <li>python310Packages.bpycv</li>
    <li>python310Packages.bpycv.dist</li>
  </ul>
</details>

### CODE REVIEW

**Comment by risicle** [comment]
Dude #227632, but let's go with this one instead as it has the fmt changes.

**Comment by risicle** [comment]
In fact could you cherry-pick my https://github.com/NixOS/nixpkgs/pull/227632/commits/990a9d2e71e6b40f75bbee667aebbebe37a20a27 into this to kill two birds with one stone?

**Comment by panicgh** [comment]
Sorry, I didn't search for already opened PRs. I prepared my branch two weeks ago but had to wait until #225645 was merged (old version would have failed to compile under fmt 9).

**Review by risicle — APPROVED** [review]
`nixpkgs-review` reveals no new failures on macos 10.15 & nixos x86_64

**Review by LeSuisse — APPROVED** [review]
LGTM too, no new failures, seems to work as expected.


Result of `nixpkgs-review pr 227986` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>luxcorerender</li>
  </ul>
</details>
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>blender</li>
    <li>blender-hip</li>
    <li>embree</li>
    <li>embree2</li>
    <li>olive-editor</li>
    <li>openimageio</li>
    <li>openimageio.bin</li>
    <li>openimageio.dev</li>
    <li>openimageio.doc</li>
    <li>osl</li>
    <li>python310Packages.bpycv</li>
    <li>python310Packages.bpycv.dist</li>
  </ul>
</details>

**Pull request merged**
