### PR TITLE
gnomeExtensions: Update for GNOME 45

### LINKED ISSUE #259035: Update request: gnomeExtensions.ddterm 43 → 45
- Package name: `gnomeExtensions.ddterm`
- Latest released version: `45`

- Current version on the unstable channel: `43`
- Current version on the stable/release channel: `43`

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@piegamesde 

-----

Note for maintainers: Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by piegamesde**
## Description of changes

Closes #259035

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by surfaceflinger** [comment]
btw it looks like extensions don't work on gnome 44 after this got merged, i guess many of them are now ported to ESM while #247766 is still wip

image

**Comment by piegamesde** [comment]
Oh I'm sorry, I hadn't thought of that, and it probably should not have been merged. Depending on how long #247766 still needs, we can fix this by reverting one line back to `gnomeExtensions = lib.trivial.pipe (gnome42Extensions // gnome43Extensions // gnome44Extensions) [`, or revert the entire thing (but which would also lose the updates which resolved e.g. #259035).

**Comment by surfaceflinger** [comment]
just wait until someone else notices and makes an issue 😎 personally i'll just wait for gnome 45 merge, but you'll definitely make some people mad once this lands in unstable

**Comment by jtojnar** [comment]
I think reverting just `gnomeExtensions` change makes most sense for now. We can then revert the revert in gnome branch.

**Comment by piegamesde** [comment]
Revert in #261196. I just noticed that after the update some extensions fail to build, which is a bit weird because I really thought we had CI to do some basic building of changed packages. So @jtojnar please don't re-add the commit to the gnome branch yet, as it requires more work. Also I'm currently writing a test suite to make sure this hopefully doesn't ever happen again.

**Comment by piegamesde** [comment]
Follow-up in #261831

**Pull request merged**
