### PR TITLE
Optionalize more kernel features

### PR DESCRIPTION
**Pull request by aneeshusa**
###### Motivation for this change

Make it possible to disable some kernel features which are not required for NixOS.
Hopefully by having smaller commits it is more clear that these features can be disabled safely (compare with #18058). I have been running this configuration without any issues.

If this is accepted, expect more in the same vein.
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @spacekitteh, who is likely interested in this

### CODE REVIEW

**Comment by copumpkin** [comment]
Your message doesn't address the concerns people raised on the original. Putting question marks doesn't make it easier for a user to disable certain features, right?

**Comment by aneeshusa** [comment]
Currently, we don't have a structured kernel config so `extraConfig` must be used to disable features. However, when I add `SOUND n` for example to `extraConfig`, it will error out at build time, because the config options without questions marks (e.g. `SND_DYNAMIC_MINORS`) unconditionally select `SOUND`. Adding question marks turns them into recommendations, so that if `SOUND` is enabled they will also be set, but preventing an error if the user tries to disable `SOUND`.

I've scoped this PR to features which are clearly not required to run NixOS, so making them recommendations instead of required lets me disable them in my kernel, making it more customizable. A structured config would be better, but this is still useful in the short term.

**Comment by copumpkin** [comment]
Oh, I see. I'd personally rather someone keep pushing https://github.com/NixOS/nixpkgs/pull/12158 than do it this way, but I'm obviously biased. I've had very little time for Nix stuff recently, but putting effort into that space feels more useful long-term than adding question marks (not to demean your particular question marks, but text munging is always going to be painful)

**Comment by aneeshusa** [comment]
I definitely want to see #12158 as well, but it doesn't seem like it's going to be in a mergeable place soon, and I'd rather not let the perfect be the enemy of the good here.
Text munging is never fun, but it's working today.

**Comment by copumpkin** [comment]
Sure, I agree with that in principle, but I'll let others who actually deal with the kernel expression weigh in on whether this is a good maintainability trade-off. Maybe one day I'll finish that PR 😄

**Comment by edolstra** [comment]
If we're going to add `?` to (nearly) every kernel option, we may as well either a) disable the check that options are used, and remove all the `?`; or b) add an option to disable that check for people who want to override the default config.

**Comment by aneeshusa** [comment]
For a), I think it is still a good idea to make it impossible to disable any options that are required for NixOS (there's way too many kernel options for me at least to know what they all do or if they're required). It does seem like many options are recommendations instead of requirements though, so maybe default to being optional, and have something to mark (maybe the suffix `!`) required options (which are the only ones checked)?

I don't know which options are actually required though, so I couldn't implement that.

For b), I think it's already possible to use  the `configfile` option with `buildLinux` directly if you want full control of the generated config, so I don't think another option to disable checks is useful.

Alternately I saw @cstrahan assigned himself to #12158, so maybe that will happen sooner rather than later.

**Comment by cstrahan** [comment]
> Alternately I saw @cstrahan assigned himself to #12158, so maybe that will happen sooner rather than later.

Dunno when I might get to it, though...

**Comment by spacekitteh** [comment]
@grahamc please tag as security, enhancement

**Comment by bobvanderlinden** [comment]
This is quite an old PR and a lot has changed. Is this PR still relevant?

**Comment by teto** [comment]
Might be related https://github.com/NixOS/nixpkgs/pull/55755

**Comment by teto** [comment]
with the structured config, it's possible to disable specific items or make them optional. Closing.

**Pull request closed without merging**
