### PR TITLE
webfs: init at 1.21

### PR DESCRIPTION
**Pull request by zimbatm**
A small web server to serve local static file. Useful when toying with single-page apps (or testing the nixos-homepage rendering)

### CODE REVIEW

**Comment by cillianderoiste** [comment]
@zimbatm Travis complains "install: cannot create regular file '/usr/local/bin/webfsd': Permission denied", have you tried building with chroot enabled for nix? Maybe that helps to reproduce the issue.

**Comment by zimbatm** [comment]
@cillianderoiste oops, chroot doesn't work for me on OSX right now. This should be fixed now.

**Comment by lethalman** [comment]
`error: cannot download webfs-1.21.tar.gz from any mirror`

**Comment by zimbatm** [comment]
I think that it was only a transient failure. It's the same source in homebrew.

**Pull request merged**
