### PR TITLE
virtualbox: 5.0.26 -> 5.1.6

### PR DESCRIPTION
**Pull request by calbrecht**
###### Motivation for this change

Virtualbox got a lot improvements and bug fixes with newer version.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ x ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ x ] Tested execution of all binary files (usually in `./result/bin/`)
- [ x ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by aszlig** [comment]
Okay, I'll rebase my refactor work on top of this, thanks.

**Comment by aszlig** [comment]
Btw. having a Qt 5 env will increase the closure size a lot, but I'm going to rip that apart as well.

**Comment by calbrecht** [comment]
Okay -- you're welcome.

**Comment by aszlig** [comment]
@calbrecht: So far looking good except that the `systemd-detect-virt` subtest is failing. Haven't figured out the exact reason for the failure yet and will do that after a few hours of sleep

@calbrecht, @dguibert, @DamienCassou, @globin: Can you test these changes on a real system?

**Comment by DamienCassou** [comment]
Does is make sense to make pulse audio support depend on `hardware.pulseaudio` on NixOS?

**Comment by aszlig** [comment]
Okay, `net-hostonlyif` fails as well with the same issue, here is the build log:

https://headcounter.org/hydra/log/8qqzihwzig8rq2vj32w8hd457zpdp352-vm-test-run-virtualbox-net-hostonlyif.drv

And the build log from `systemd-detect-virt`:

https://headcounter.org/hydra/log/kqm2q44mp3za2j55ylrbbwhbibxma2g6-vm-test-run-virtualbox-systemd-detect-virt.drv

So the machine state is `PoweredOff` but the `VirtualBox --startvm` process is still running, so killing the process before the `unregistervm` let's the tests pass.

If you can reproduce this issue on a real machine, that would be quite helpful, possibly by running the VM debugger (`VirtualBox --startvm $name --debug`). Interestingly when running the tests with a debug build the issue doesn't happen and the tests run well :unamused:

Okay, but now :zzz:, c'ya later.

**Comment by aszlig** [comment]
@DamienCassou: Hm, it might even make sense to enable it by default, because it falls back to using ALSA if PulseAudio is unavailable at runtime. If people want to get rid of PulseAudio they can still use `nixpkgs.config.pulseaudio = false` or even override `pulseaudio` with `null`.

**Comment by DamienCassou** [comment]
@aszlig the new VirtualBox seems to work. The audio problem (#15005) is still there though (with pulseAudio enabled but if you know how to double check the binaries have indeed pulse audio enabled that would be great).

Also, please note that [5.1.6 is now out](https://www.virtualbox.org/wiki/Changelog#v6).

**Comment by calbrecht** [comment]
Works for me with a vagrant project, so far. :-)

**Comment by aszlig** [comment]
@DamienCassou: Thanks for the notice, will retry the tests with 5.1.6 and hope it's an upstream bug :-D

**Comment by DamienCassou** [comment]
@aszlig I'm more worried about the sound problem. If it doesn't get fixed really soon, I will have to change my distro :-(

**Comment by aszlig** [comment]
@DamienCassou: You can double-check by looking at the settings UI whether there is PulseAudio listed as an audio output option.

**Comment by domenkozar** [comment]
@aszlig so only one test needs to be fixed before this is ready?

**Comment by aszlig** [comment]
@domenkozar: Two tests actually, currently debugging them.

**Comment by aszlig** [comment]
@DamienCassou: So does the audio problem persist?

**Comment by DamienCassou** [comment]
@aszlig yes, see #15005

**Comment by domenkozar** [comment]
Awesome work :)

There is one test failing with kernel panics however: http://hydra.nixos.org/build/40690563/nixlog/3/raw

**Pull request merged**
