### PR TITLE
gamescope: 3.11.33-jupiter-3.3-2 -> 3.11.39

### PR DESCRIPTION
**Pull request by nrdxp**
Updated to latest release version.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nrdxp** [comment]
Result of `nixpkgs-review pr 187478` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>gamescope</li>
    <li>libliftoff</li>
  </ul>
</details>

**Review by zhaofengli — APPROVED** [review]
This update works fine on my Steam Deck, but we should bump to [3.11.39](https://github.com/Plagman/gamescope/releases/tag/3.11.39) before merging.

**Comment by nrdxp** [comment]
done

**Review by zhaofengli — APPROVED** [review]
Tested 3.11.39 on my Steam Deck. However, when testing the trivial bump to [3.11.40](https://github.com/Plagman/gamescope/compare/3.11.39...3.11.40), the Steam Deck UI failed to launch due to some XWayland issue:

```
Aug 22 21:10:03 steamdeck gamescope-switcher-start[252338]: [2022-08-22 21:10:03] Opted in to client beta 'steamdeck_publicbeta' via beta file
Aug 22 21:10:03 steamdeck gamescope-switcher-start[252338]: You are in the 'steamdeck_publicbeta' client beta.
Aug 22 21:10:03 steamdeck gamescope-switcher-start[252338]: SteamUpdateUI: An X Error occurred
Aug 22 21:10:03 steamdeck gamescope-switcher-start[252338]: X Error of failed request:  BadValue (integer parameter out of range for operation)
Aug 22 21:10:03 steamdeck gamescope-switcher-start[252338]: Major opcode of failed request:  1 (X_CreateWindow)
```

Let merge 3.11.39 in for now.

**Comment by zhaofengli** [comment]
It was [a regression](https://github.com/Plagman/gamescope/issues/593) that was reverted in 3.11.42.

**Pull request merged**
