### PR TITLE
kdeApplications: Use latest qt515 by default

### LINKED ISSUE #98268: Qt applications use Windows style regardless of style selected in KDE settings
**Describe the bug**
Various Qt applications (smplayer, qjackctl etc) use Windows style regardless of what style is selected in KDE System Settings.
When I try to pass style via command line it doesn't work either.
```
qjackctl -style Breeze
QApplication: invalid style override 'Breeze' passed, ignoring it.
        Available styles: Breeze, Windows, Fusion
```

**To Reproduce**
1. Select any style (Breeze, Fusion) in KDE System Settings
2. Launch Qt application (smplayer for example)
3. Application uses Windows style

**Expected behavior**
Qt applications should use style selected in KDE System Settings

**Screenshots**
Screenshot_20200919_124746

**Metadata**
```
- system: `"x86_64-linux"`
 - host os: `Linux 5.7.19, NixOS, 21.03pre243690.441a7da8080 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-21.03pre243690.441a7da8080"`
 - channels(alapshin): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### LINKED ISSUE #100707: kdeApplications uses qt514 by default while all-packages.nix uses qt515, causing incompatibilites
**Describe the bug**

Consider this:

https://github.com/NixOS/nixpkgs/blob/0826f2efaed5c64d3c574f87dd4dcf978207f576/pkgs/top-level/all-packages.nix#L21555-L21562

Where all other `libsForQt5.callPackage` usages in `all-packages.nix` use `libsForQt515`. This causes incompatibilities if derivations available in `kdeApplications` are used in conjunction with expressions called with `libsForQt5.callPackage` used in `all-packages.nix`.

**To Reproduce**

For example, `kile` has:

https://github.com/NixOS/nixpkgs/blob/0826f2efaed5c64d3c574f87dd4dcf978207f576/pkgs/applications/editors/kile/default.nix#L51-L52

Which causes it to have the environment of `kdeApplications.konsole` in it's wrapper. The environment of `kdeApplications.konsole` has qt514 vars but `kile` is built with `qt515` causing it not to start.

**Additional context**

A fix for this should be similar to the sprint in #99956 . FYI @piegamesde .

**Notify maintainers**

@ttuegel

### LINKED ISSUE #100854: Figuring out *where* a package is marked as broken is difficult
**Describe the bug**
In 0b8799ecaaf0dc6b4c11583a3c96ca5b40fcfdfb I was faced with the following error when trying to build `elisa`:
```
$ nix run -f . elisa
error: Package ‘breeze-qt5-5.18.5’ in /opt/exp/nixpkgs/pkgs/desktops/plasma-5/default.nix:96 is marked as broken, refusing to evaluate.
```

However, nothing in `pkgs/desktops/plasma-5/breeze-qt5.nix` suggests that `breeze-qt5` is marked as broken. I looked in the "obvious" places, (e.g. `all-packages.nix`, `pkgs/desktops/plasma-5/default.nix`) yet have been utterly unable to locate the `broken` declaration in question. Presumably there is something somewhere which *does* mark it as broken. However, I haven't the slightest idea how one would find it.

**To Reproduce**
1. Try building a broken derivation
2. Encounter error
3. Try in vain to find the `broken` attribute

**Expected behavior**

The error should tell you the source location of the `broken` attribute.

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.14, NixOS, 20.09beta1057.0b8799ecaaf (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09beta1057.0b8799ecaaf, nixpkgs-20.09beta1057.0b8799ecaaf"`
 - channels(ben): `"nixpkgs-20.09beta1083.51aaa3fa1b6, nixpkgs-20_03-20.03.3122.ff6fda61600, nixpkgs-unstable-21.03pre246624.cfed29bfcb2, nixos-18.09-18.09.2574.a7e559a5504"`
 - nixpkgs: `/home/ben/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### LINKED ISSUE #102167: kmail is broken on master
**Describe the bug**
Run-time fatal error.

**To Reproduce**
```
$ kmail
```
starts the program but results in a dialog that says
```
The Email program encountered a fatal error and will terminate now.
The error was:
Unable to obtain agent type ''.
```

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Nixpkgs at d420c85a5593866939e5fe72ee9396bbf271bc92

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: `kmail`
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by doronbehar**
###### Motivation for this change

Fix https://github.com/NixOS/nixpkgs/issues/100707 , Fix #102167 , Fix #100854 , Fix #98268. (cc @ttuegel ).

###### Things done

- [ ] Iterate all qt applications affected and make sure they work.

In order to do that, before building, one can verify whether incompatible versions are used using the following steps:

1. Download this script: https://paste.sr.ht/~jorsn/307bd7a99855c7d6f34923ebe2f41a9f2d0f6f8a and save it as `dep-ver-consistent.nix`.
2. Run the following to test for incompatible versions with `$pkg` substituted for the attribute path you want to test:

```sh
$(nix-build --no-out-link -A nixUnstable)/bin/nix eval --impure  --expr \
  'with import ./. {}; import ./dep-ver-consistent.nix lib false 4 "qtbase" '$pkg
```

You can use `1` or `2` or any other number instead of `4` in the command above to adjust the depth for which inputs of inputs will be checked. The command will print `true` if no issues are found, and `false` + a trace, if there _are _ incompatible qt versions used.

Given a list of attributes in a file you can iterate them all with:

```sh
cat broken-for-sure | while read pkg; do
 $(nix-build --no-out-link -A nixUnstable)/bin/nix eval --impure --expr 'with import ./. {}; import ./dep-ver-consistent.nix lib false 4 "qtbase" '$pkg
done
```

I think all of affected packages now have no mismatched versions used together, up to depth 4. Upcoming ofborg evals may tell differently.

Here's the current list of affected packages, `kdeFrameworks.` and `kdeApplications.` prefixes were cut in favor of maintaining uniqueness.

   - [ ] akonadi
   - [ ] akonadi-calendar
   - [ ] akonadiconsole
   - [ ] akonadi-contacts
   - [ ] akonadi-import-wizard
   - [ ] akonadi-mime
   - [ ] akonadi-notes
   - [ ] akonadi-search
   - [ ] akregator
   - [ ] alkimia
   - [ ] amarok
   - [ ] amarok-kf5
   - [ ] antimicroX
   - [ ] ark
   - [ ] attica
   - [ ] baloo
   - [ ] baloo-widgets
   - [ ] bcompare
   - [ ] bluedevil
   - [ ] bluez-qt
   - [ ] bomber
   - [ ] bovo
   - [ ] breeze-gtk
   - [ ] breeze-icons
   - [ ] breeze-plymouth
   - [ ] breeze-qt5
   - [ ] calamares
   - [ ] calendarsupport
   - [ ] calligra
   - [ ] colord-kde
   - [ ] digikam
   - [ ] discover
   - [ ] dolphin
   - [ ] dolphin-plugins
   - [ ] dragon
   - [ ] drawpile
   - [ ] drawpile-server-headless
   - [ ] elisa
   - [ ] espanso
   - [ ] eventviews
   - [ ] extra-cmake-modules
   - [ ] falkon
   - [ ] fcitx
   - [ ] fcitx-configtool
   - [ ] fcitx-engines.anthy
   - [ ] fcitx-engines.chewing
   - [ ] fcitx-engines.cloudpinyin
   - [ ] fcitx-engines.hangul
   - [ ] fcitx-engines.libpinyin
   - [ ] fcitx-engines.m17n
   - [ ] fcitx-engines.mozc
   - [ ] fcitx-engines.rime
   - [ ] fcitx-engines.skk
   - [ ] fcitx-engines.table-extra
   - [ ] fcitx-engines.table-other
   - [ ] fcitx-engines.unikey
   - [ ] fcitx-qt5
   - [ ] ffmpegthumbs
   - [ ] filelight
   - [ ] flat-remix-icon-theme
   - [ ] frameworkintegration
   - [ ] gmic-qt-krita
   - [ ] granatier
   - [ ] grantleetheme
   - [ ] gwenview
   - [ ] heaptrack
   - [ ] hotspot
   - [ ] incidenceeditor
   - [ ] k3b
   - [x] k4dirstat
   - [ ] k9copy
   - [ ] kactivities
   - [ ] kactivities-stats
   - [ ] kactivitymanagerd
   - [ ] kaddressbook
   - [ ] kalarm
   - [ ] kalarmcal
   - [ ] kalzium
   - [ ] kapidox
   - [ ] kapman
   - [ ] kapptemplate
   - [ ] karchive
   - [ ] kate
   - [ ] katomic
   - [ ] kauth
   - [ ] kblackbox
   - [ ] kblocks
   - [ ] kbookmarks
   - [ ] kbounce
   - [ ] kbreakout
   - [x] kcachegrind
   - [ ] kcalc
   - [ ] kcalendarcore
   - [ ] kcalutils
   - [ ] kcharselect
   - [ ] kcmutils
   - [ ] kcodecs
   - [ ] kcolorchooser
   - [ ] kcompletion
   - [ ] kconfig
   - [ ] kconfigwidgets
   - [ ] kcontacts
   - [ ] kcoreaddons
   - [ ] kcrash
   - [ ] kdav
   - [ ] kdb
   - [ ] kdbg
   - [ ] kdbusaddons
   - [ ] kde2-decoration
   - [ ] kdebugsettings
   - [ ] kdeclarative
   - [ ] kde-cli-tools
   - [ ] kdeconnect
   - [ ] kdecoration
   - [ ] kded
   - [ ] kdegraphics-mobipocket
   - [ ] kdegraphics-thumbnailers
   - [ ] kde-gtk-config
   - [ ] kdelibs4support
   - [ ] kdenetwork-filesharing
   - [ ] kdenlive
   - [ ] kdepim-addons
   - [ ] kdepim-apps-libs
   - [ ] kdepim-runtime
   - [ ] kdeplasma-addons
   - [ ] kdesignerplugin
   - [ ] kdesu
   - [ ] kdevelop
   - [ ] kdevelop-pg-qt
   - [ ] kdevelop-unwrapped
   - [ ] kdev-php
   - [ ] kdev-python
   - [ ] kdewebkit
   - [ ] kdf
   - [ ] kdiagram
   - [ ] kdialog
   - [ ] kdiamond
   - [ ] kdiff3
   - [ ] kdnssd
   - [ ] kdoctools
   - [ ] keditbookmarks
   - [ ] kemoticons
   - [ ] kexi
   - [ ] keysmith
   - [ ] kf5gpgmepp
   - [ ] kfilemetadata
   - [ ] kfind
   - [ ] kfloppy
   - [ ] kgamma5
   - [ ] kgeography
   - [ ] kget
   - [ ] kglobalaccel
   - [ ] kgpg
   - [ ] kgraphviewer
   - [ ] kguiaddons
   - [ ] khelpcenter
   - [ ] kholidays
   - [ ] khotkeys
   - [ ] khtml
   - [ ] ki18n
   - [ ] kiconthemes
   - [ ] kid3
   - [ ] kidentitymanagement
   - [ ] kidletime
   - [ ] kig
   - [ ] kigo
   - [x] kile
   - [ ] killbots
   - [ ] kimageformats
   - [ ] kimap
   - [ ] kinfocenter
   - [ ] kinit
   - [ ] kio
   - [ ] kio-extras
   - [ ] kipi-plugins
   - [ ] kirigami2
   - [ ] kitemmodels
   - [ ] kitemviews
   - [ ] kitinerary
   - [ ] kjobwidgets
   - [ ] kjs
   - [ ] kjsembed
   - [ ] kldap
   - [ ] kleopatra
   - [ ] klettres
   - [ ] klines
   - [ ] kmag
   - [ ] kmahjongg
   - [ ] kmail
   - [ ] kmail-account-wizard
   - [ ] kmailtransport
   - [ ] kmbox
   - [ ] kmediaplayer
   - [ ] kmenuedit
   - [ ] kmime
   - [ ] kmines
   - [ ] kmix
   - [ ] kmplayer
   - [ ] kmplot
   - [ ] kmymoney
   - [ ] knavalbattle
   - [ ] knetwalk
   - [ ] knewstuff
   - [ ] knights
   - [ ] knotes
   - [ ] knotifications
   - [ ] knotifyconfig
   - [ ] kolf
   - [ ] kollision
   - [ ] kolourpaint
   - [ ] kompare
   - [ ] konqueror
   - [ ] konquest
   - [ ] konsole
   - [ ] kontact
   - [ ] kontactinterface
   - [ ] konversation
   - [ ] korganizer
   - [ ] kpackage
   - [ ] kparts
   - [ ] kpat
   - [ ] kpeople
   - [ ] kpeoplevcard
   - [ ] kpimtextedit
   - [ ] kpkpass
   - [ ] kplotting
   - [ ] kpmcore
   - [ ] kproperty
   - [ ] kpty
   - [ ] kpurpose
   - [ ] kqtquickcharts
   - [ ] kquickcharts
   - [ ] krdc
   - [ ] krename
   - [ ] kreport
   - [ ] kreversi
   - [ ] krfb
   - [ ] krita
   - [ ] krohnkite
   - [ ] kronometer
   - [ ] kross
   - [ ] kruler
   - [ ] krunner
   - [ ] krunner-pass
   - [ ] krusader
   - [ ] kscreen
   - [ ] kscreenlocker
   - [ ] kservice
   - [ ] kshisen
   - [ ] ksmoothdock
   - [ ] ksmtp
   - [ ] kspaceduel
   - [ ] ksquares
   - [ ] ksshaskpass
   - [ ] kstars
   - [ ] ksudoku
   - [ ] ksysguard
   - [ ] ksystemlog
   - [ ] kteatime
   - [ ] ktexteditor
   - [ ] ktextwidgets
   - [ ] ktimer
   - [ ] ktimetracker
   - [ ] ktnef
   - [ ] ktorrent
   - [ ] ktouch
   - [ ] kturtle
   - [ ] kunitconversion
   - [ ] kwallet
   - [ ] kwalletcli
   - [ ] kwalletmanager
   - [ ] kwallet-pam
   - [ ] kwave
   - [ ] kwayland
   - [ ] kwayland-integration
   - [ ] kwidgetsaddons
   - [ ] kwin
   - [ ] kwindowsystem
   - [ ] kwin-dynamic-workspaces
   - [ ] kwin-tiling
   - [ ] kwrited
   - [ ] kxmlgui
   - [ ] kxmlrpcclient
   - [ ] latte-dock
   - [ ] libgravatar
   - [ ] libkcddb
   - [ ] libkdcraw
   - [ ] libkdegames
   - [ ] libkdepim
   - [ ] libkexiv2
   - [ ] libkgapi
   - [ ] libkipi
   - [ ] libkleo
   - [ ] libkmahjongg
   - [ ] libkomparediff2
   - [ ] libksane
   - [ ] libkscreen
   - [ ] libksieve
   - [ ] libksysguard
   - [ ] libktorrent
   - [ ] libqtav
   - [ ] libreoffice-qt
   - [ ] luna-icons
   - [ ] lxqt.lxqt-config
   - [ ] maia-icon-theme
   - [ ] mailcommon
   - [ ] mailimporter
   - [ ] marble
   - [ ] massif-visualizer
   - [ ] mbox-importer
   - [ ] messagelib
   - [ ] milou
   - [ ] minitube
   - [ ] minuet
   - [ ] mlterm
   - [ ] modemmanager-qt
   - [ ] networkmanager-qt
   - [x] okteta
   - [x] okular
   - [ ] oxygen
   - [ ] oxygen-icons5
   - [ ] papirus-icon-theme
   - [ ] papirus-maia-icon-theme
   - [ ] partition-manager
   - [ ] peruse
   - [ ] phonon
   - [ ] phonon-backend-gstreamer
   - [ ] phonon-backend-vlc
   - [ ] photoqt
   - [ ] picmi
   - [ ] pimcommon
   - [ ] pim-data-exporter
   - [ ] pim-sieve-editor
   - [ ] plasma-applet-caffeine-plus
   - [ ] plasma-applet-volumewin7mixer
   - [ ] plasma-browser-integration
   - [ ] plasma-desktop
   - [ ] plasma-framework
   - [ ] plasma-integration
   - [ ] plasma-nm
   - [ ] plasma-pa
   - [ ] plasma-vault
   - [ ] plasma-wayland-protocols
   - [ ] plasma-workspace
   - [ ] plasma-workspace-wallpapers
   - [ ] playbar2
   - [ ] polkit-kde-agent
   - [ ] pop-icon-theme
   - [ ] powerdevil
   - [ ] print-manager
   - [ ] prison
   - [ ] pulseaudio-qt
   - [ ] qqc2-desktop-style
   - [ ] qstopmotion
   - [ ] qtcurve
   - [ ] quassel
   - [ ] quasselClient
   - [ ] redshift-plasma-applet
   - [ ] rocs
   - [ ] rsibreak
   - [ ] sddm
   - [ ] sddm-kcm
   - [ ] skanlite
   - [ ] skrooge
   - [ ] solid
   - [ ] sonnet
   - [ ] soundkonverter
   - [ ] spectacle
   - [ ] syncthingtray
   - [ ] syndication
   - [ ] syntax-highlighting
   - [ ] systemsettings
   - [ ] tellico
   - [ ] threadweaver
   - [ ] tora
   - [ ] trojita
   - [ ] user-manager
   - [ ] virt-manager-qt
   - [ ] wacomtablet
   - [ ] x2goclient
   - [ ] xdg-desktop-portal-kde
   - [ ] yakuake
   - [ ] zafiro-icons
   - [ ] zanshin
   - [ ] zeal
   - [ ] zombietrackergps

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by doronbehar** [comment]
Damn that list is so long. It was filtered from [the original ofborg eval gist](https://gist.githubusercontent.com/GrahamcOfBorg/851d243bb3123e5c5985f1ffcbf2c64c/raw/2977e56f16ed4da57f125099736af2198bcccfaa/Changed%2520Paths) with:

```
curl -Ls 'https://gist.githubusercontent.com/GrahamcOfBorg/851d243bb3123e5c5985f1ffcbf2c64c/raw/2977e56f16ed4da57f125099736af2198bcccfaa/Changed%2520Paths' | awk '{sub(/kdeApplications\./, "", $2); sub(/libsForQt5.?.?\./, "", $2); print "   - [ ] "$2}' | sort -u
```

**Comment by doronbehar** [comment]
Thanks to [`@jorsn`s script](https://github.com/NixOS/ofborg/issues/533), I was able to run:

```
rm -f broken-for-sure
curl -Ls 'https://gist.githubusercontent.com/GrahamcOfBorg/851d243bb3123e5c5985f1ffcbf2c64c/raw/2977e56f16ed4da57f125099736af2198bcccfaa/Changed%2520Paths' | awk '{print $2}' | sort -u | while read pkg; do
 result=$(nix eval --impure --expr 'with import ./. {}; import ./.m/dep-ver-consistent.nix lib false 1 "qtbase" '$pkg)
 if [[ $result == false ]]; then 
 echo $pkg >> broken-for-sure
 fi
done
```

To tell myself what packages are probably broken due to the incompatible qt versions. The current result is not too long:

```
bluedevil
k9copy
kde-cli-tools
libsForQt514.kpmcore
plasma5.bluedevil
plasma5.kde-cli-tools
plasma5.plasma-desktop
plasma5.plasma-workspace
plasma-desktop
plasma-workspace
tellico
trojita
zanshin
```

**Comment by doronbehar** [comment]
All of the above now don't use mixed qt versions.

**Comment by doronbehar** [comment]
From **kile**, I get:

ZENIX-selection-2020-10-23T10:34:35+03:00

I wonder if it means it's broken or it's just because I don't use kde. cc @piegamesde .

**Comment by doronbehar** [comment]
lxqt had 1 package with mismatched qt5 versions. @ttuegel , not totally related to this PR, but I'd appreciate if you'd elaborate on https://github.com/NixOS/doronbehar/nixpkgs/commit/4fd58aa4e18c06ead397ad45d68b76d0930c6cbb - explaining why did you pin lxqt to 5.14.

**Comment by doronbehar** [comment]
Current incompatible packages:

```
calligra
digikam
kdevelop-unwrapped
kexi
kile
libsForQt512.kreport
libsForQt514.kreport
virt-manager-qt
wacomtablet
zombietrackergps
```

**Review by solson — APPROVED** [review]
I think the bot requested my review due to changes to `drumstick`, which look fine to me. I'm not qualified to comment on the overall changes, but cleaning up Qt version mismatches seems like something we should do.

I'm curious, would this PR fix the problems I was investigating over at https://github.com/NixOS/nixpkgs/issues/98268#issuecomment-706855440?

**Comment by alapshin** [comment]
I'm trying to test this PR to check if it fixes https://github.com/NixOS/nixpkgs/issues/98268 or not however I can't build system using
```
nixos-rebuild -I nixpkgs=$NIXPKGS switch
```

Build fails with
```
building Nix...
building the system configuration...
error: attribute 'kinit' missing, at /home/alapshin/workspace/nixpkgs/nixos/modules/services/x11/desktop-managers/plasma5.nix:195:46
(use '--show-trace' to show detailed location information)
```

**Comment by doronbehar** [comment]
> Build fails with

Thanks for the report. It was indeed inevitable. and is now fixed.

**Comment by raboof** [comment]
k4dirstat works

**Comment by erosennin** [comment]
Plasma packages won't build with this patch:

```
$ nix-build --show-trace -A plasma5.plasma-desktop
error: while evaluating the attribute 'handled' at /home/erosennin/src/sbox/nixpkgs/pkgs/stdenv/generic/check-meta.nix:256:7:
while evaluating 'handleEvalIssue' at /home/erosennin/src/sbox/nixpkgs/pkgs/stdenv/generic/check-meta.nix:152:38, called from /home/erosennin/src/sbox/nixpkgs/pkgs/stdenv/generic/check-meta.nix:257:14:
Package ‘plasma-desktop-5.18.5’ in /home/erosennin/src/sbox/nixpkgs/pkgs/desktops/plasma-5/default.nix:96 is marked as broken, refusing to evaluate.
```

**Comment by FRidh** [comment]
Given the similarity between Qt and Python, I think we should take the approach as with Python: put all Qt libraries (KDE frameworks, plasma, ...) in `libsForQt5`. That means e.g. Plasma gets build for all Qt versions. We will have to disable some builds because they will fail, but at least this way you have consistency.

**Comment by alapshin** [comment]
I was able to rebuild my system using this PR.
One problem is that after reboot sddm starts with errors
1. First virtual keyboard is shown (instead of normal login screen)
2. If press enter on virtual keyboard then login screen is shown but it uses default theme and there is error message
```
Login failed
The current theme cannot be loaded due to the errors below, please select another theme.
file:///run/current-system/sw/share/sddm/themes/breeze/Main.qml:24:1: plugin cannot be loaded for module "QtGraphicalEffects": The plugin '/nix/store/cxrlnws0arc6sgw08lz9ryyiknqcyvr3-qtgraphicaleffects-5.15.0/lib/qt-5.15.0/qml/QtGraphicalEffects/libqtgraphicaleffectsplugin.so' uses incompatible Qt library. (5.15.0) [release]'
```
3. Entering password on this login screen works.
4. Everything else after login seems to work fine (plasma/KDE apps)
5. Issue https://github.com/NixOS/nixpkgs/issues/98268 is also solved. Qt apps (smplayer, qjackctl) use breeze theme selected in system settings.

**Comment by FRidh** [comment]
Moved Qt and other Qt libraries into a single `qt-packages.nix` https://github.com/NixOS/nixpkgs/commit/165b07749dc59227b0c4b90dcf3cabd7fcc83b92.

**Comment by doronbehar** [comment]
> Moved Qt and other Qt libraries into a single `qt-packages.nix` [165b077](https://github.com/NixOS/nixpkgs/commit/165b07749dc59227b0c4b90dcf3cabd7fcc83b92).

@FRidh this is not pushed to this PR right?

**Comment by doronbehar** [comment]
> Plasma packages won't build with this patch:
> 
> ```
> $ nix-build --show-trace -A plasma5.plasma-desktop
> error: while evaluating the attribute 'handled' at /home/erosennin/src/sbox/nixpkgs/pkgs/stdenv/generic/check-meta.nix:256:7:
> while evaluating 'handleEvalIssue' at /home/erosennin/src/sbox/nixpkgs/pkgs/stdenv/generic/check-meta.nix:152:38, called from /home/erosennin/src/sbox/nixpkgs/pkgs/stdenv/generic/check-meta.nix:257:14:
> Package ‘plasma-desktop-5.18.5’ in /home/erosennin/src/sbox/nixpkgs/pkgs/desktops/plasma-5/default.nix:96 is marked as broken, refusing to evaluate.
> ```

I don't know why @ttuegel did this:

```patch
tree c1e91aef7166c593eb8bd0e1017e0c6c531d6676
parent 65b0805f8f38b3d2a6585f4217f026c011cd2cbf
author Thomas Tuegel <thomas.tuegel@runtimeverification.com> Sun Sep 6 13:50:50 2020 -0500
committer Thomas Tuegel <thomas.tuegel@runtimeverification.com> Mon Sep 7 08:06:42 2020 -0500

plasma5: mark broken with Qt >= 5.15


diff --git a/pkgs/desktops/plasma-5/default.nix b/pkgs/desktops/plasma-5/default.nix
index 265c22b5565..8ab4b60156c 100644
--- a/pkgs/desktops/plasma-5/default.nix
+++ b/pkgs/desktops/plasma-5/default.nix
@@ -36,6 +36,7 @@ let
   };
 
   mkDerivation = libsForQt5.callPackage ({ mkDerivation }: mkDerivation) {};
+  qtbase = libsForQt5.callPackage ({ qtbase }: qtbase) {};
 
   packages = self: with self;
     let
@@ -82,6 +83,7 @@ let
             setupHook = args.setupHook or defaultSetupHook;
 
             meta = {
+              broken = lib.versionAtLeast qtbase.version "5.15";
               license = with lib.licenses; [
                 lgpl21Plus lgpl3Plus bsd2 mit gpl2Plus gpl3Plus fdl12
               ];
```

I think it'd be best to revert it in the meantime, and see if users encounter issues. I suspect that due to mixed qt5 versoins used together many applications were broken and as such the false conclusion was reached that the whole set is broken.

**Comment by doronbehar** [comment]
>     2\. If I press enter on virtual keyboard then login screen is shown but it uses default theme and there is error message
> 
> 
> ```
> Login failed
> The current theme cannot be loaded due to the errors below, please select another theme.
> file:///run/current-system/sw/share/sddm/themes/breeze/Main.qml:24:1: plugin cannot be loaded for module "QtGraphicalEffects": The plugin '/nix/store/cxrlnws0arc6sgw08lz9ryyiknqcyvr3-qtgraphicaleffects-5.15.0/lib/qt-5.15.0/qml/QtGraphicalEffects/libqtgraphicaleffectsplugin.so' uses incompatible Qt library. (5.15.0) [release]'
> ```
> 

I can't trace this issue. It seems fine according to:

https://github.com/doronbehar/nixpkgs/blob/e6a26e35c886ecbbb8821679d2212fad6ef04391/pkgs/desktops/plasma-5/plasma-workspace/default.nix#L37-L39

And according to the dep-ver-consistent.nix script there are no incompatible versions used there, up to at least level 6.

**Comment by FRidh** [comment]
> @FRidh this is not pushed to this PR right?

It is not strictly needed.

**Comment by alapshin** [comment]
@doronbehar 

Regarding sddm issue.

It is decalred in `all-packages.nix` as
```
sddm = libsForQt514.callPackage ../applications/display-managers/sddm { };
```
If I change it declaration to 
```
sddm = libsForQt5.callPackage ../applications/display-managers/sddm { };
```
and rebuild then issue is not present and sddm starts without errors. But I'm not sure if this is correct solution or not.

**Comment by FRidh** [comment]
> and rebuild then issue is not present and sddm starts without errors. But I'm not sure if this is correct solution or not.

As a standalone application I do not see an issue with that.

**Comment by doronbehar** [comment]
Thanks for the report @alapshin . I think this is now fixed, and hopefully lxqt (still held back with qt514) + sddm users should now get the correct sddm build now.

**Comment by doronbehar** [comment]
@FRidh Besides perhaps running some NixOS tests, I don't see anymore blockers - All possible mixed versions of Qt should be eliminated. There are not much  :heavy_check_mark: marked on the changed packages since d0609043c32 has removed the problematic inheritance I expect most of the breakage came from.

Definitely there could be more packages broken, but they should be broken only if:

1. They link to a dependency that's defined in the widest scope of `all-packages.nix` using a certain `libsForQt5*` and not in all of `libsForQt5*` scopes, i.e not here:

https://github.com/NixOS/nixpkgs/blob/630f19b3ef9cebef1b85bc5c8c6e1fe2a3c6aa01/pkgs/top-level/all-packages.nix#L15102-L15104

2. Either of:
   - They are called using a different `libsForQt5` then the dependency.
   - The dependency imports `qt5` directly, which will then default to 515, while the package might be defined also in the widest scope, using e.g `libsForQt514`.

----

**Comment by worldofpeace** [comment]
Hi, please merge this **with** @ttuegel approval when the time comes. It is also up to him how much or what gets backported because he's the codeowner.

**Comment by schmittlauch** [comment]
While this PR is against master, do you plan to backport this to 20.09?
I'm asking because I don't know how much master and release-20.09 differ in their Qt version usage due to things like #98657. 

I currently have to postpone my upgrade to 20.09 because of running into the marked-broken `breeze` as described in #100854, so I need to know whether this PR will tackle that or whether that needs to be reported separately.

**Comment by FRidh** [comment]
This looks good to me. Now building my system against this change.

**Comment by FRidh** [comment]
This looks good to me. My system is now running with these changes, although I had to rebase it onto master at d420c85a5593866939e5fe72ee9396bbf271bc92. 

I also made some changes, Kile now uses latest Qt f9852ef7343fba0fa67a8cf997d5bc86bb2e019b and so does kdeconnect f8e99501c91e46688b475e33aa3587d6111dc426. Please cherry-pick those from my repo.

**Comment by tobiasBora** [comment]
I can confirm that I've the same issue as the one presented [here](https://discourse.nixos.org/t/package-breeze-qt-broken-when-upgrading-to-20-09/9736/4), so it means that I cannot upgrade to 20.09. So a backport would be much appreciated, thanks a lot!

**Comment by FRidh** [comment]
Just a note for myself.

The following is the KDE Plasma release schedule https://community.kde.org/Schedules/Plasma_5#Support_status_by_Release_Series.

We currently have:
- Qt 5.15.0 (and 5.15.1 with https://github.com/NixOS/nixpkgs/pull/102216)
- Frameworks 5.73.0
- Plasma 5.18.5
- Applications 20.08.2

**Comment by FRidh** [comment]
@doronbehar the kdeconnect revert got removed

**Comment by FRidh** [comment]
My system is running on this PR now without issues.

**Comment by FRidh** [comment]
Backport PR https://github.com/NixOS/nixpkgs/pull/101369

**Comment by FRidh** [comment]
Looking at it again, I think we may have gone too far regarding using aliases here. The applications should still be available from `all-packages.nix`, as long as the dependencies of each application are consistent.

**Comment by doronbehar** [comment]
> Looking at it again, I think we may have gone too far regarding using aliases here. The applications should still be available from `all-packages.nix`, as long as the dependencies of each application are consistent.

I disagree. The issue is also explained in the commit message of b5c6505e63d - many attributes in `kdeApplications` are also used as inputs to other applications that use `libsForQt5.callPackage`, and are not part of that set. If we (at least in the meantime) don't use a `qt-applications.nix`, we can never be sure that inheriting them in `all-packages.nix` will not cause trouble to packages using these "applications" as inputs.

I guess we (I) could have filtered out what was aliased and what was inherited by inspecting each attribute in `kdeApplications` and check whether it is used as an input or not in any packages, but I concluded it'd be best to alias all of them, to put us as far as possible from this potential issue.

**Comment by ajs124** [comment]
Hm, this breaks building systems with `services.xserver.desktopManager.plasma5.enable = true;` and `nixpkgs.config.allowAliases = true;`.

**Comment by FRidh** [comment]
Nice those undocumented options to Nixpkgs.

Aside from documenting this option, we should also pass it as false in `make-test-python.nix`. Basically, everywhere we import Nixpkgs from with Nixpkgs it should be false.

**Comment by erictapen** [comment]
At first glance this looks to me as backported successfully in https://github.com/NixOS/nixpkgs/pull/102347.
Will remove the `needs: port to stable` then. Feel free to readd it if there is something missing.

**Pull request merged**
