### PR TITLE
rspamd: 1.6.6 -> 1.7.3

### PR DESCRIPTION
**Pull request by oxij**
Update.

### CODE REVIEW

**Comment by xeji** [comment]
Have you tested that the rspamd module works with this?
cc @fpletz

**Comment by xeji** [comment]
Thanks. Can you please have a look at #40434 (opened after this), which bumps to 1.7.4, drops rmilter and updates the module.

**Comment by oxij** [comment]
Ok. Done.

**Comment by xeji** [comment]
Thanks!

**Pull request closed without merging**
