### PR TITLE
firefox: 89.0.2 -> 90.0

### PR DESCRIPTION
**Pull request by ajs124**
###### Motivation for this change
make gtk3Support non-optional, because it hasn't been for a long time
also make gtk2 conditional on firefox older than 90, because we can get
rid of it with firefox 90, but it's still needed by the current ESR
release

###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by drupol** [comment]
We should add the tag to automatically backport this to `release-21.05`.

**Comment by mweinelt** [comment]
> We should add the tag to automatically backport this to `release-21.05`.

That has to be evaluated on a case-by-case basis. Might require a certain nss or rust-cbindgen backport as well.

**Review by lovesegfault — APPROVED** [review]
Changes LGTM

**Comment by lovesegfault** [comment]
Result of `nixpkgs-review pr 130019` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>adoptopenjdk-icedtea-web</li>
    <li>dropbox</li>
    <li>dropbox-cli</li>
    <li>firefox-esr-78-unwrapped (firefoxPackages.firefox-esr-78)</li>
    <li>xulrunner (firefox-unwrapped)</li>
    <li>mate.caja-dropbox</li>
    <li>slimerjs</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
- Built `firefox-unwrapped` on aarch64-linux
  ```
  /nix/store/nwv6ggpyzrdhpdb7bz8rf2apbqpqnyrs-firefox-unwrapped-90.0
  ```
- Tested `firefox-wayland` on x86_64-linux (sway, pipewire)
  ```
  /nix/store/j1vganal6v3hppprza5jcny7qhynjr3q-firefox-90.0
  ```
  - [x] YouTube Video Playback
  - [x] Webcam
  - [x] Microphone
  - [x] Screen Sharing

**Pull request merged**
