### PR TITLE
vimPlugins: Add meta.homepage

### PR DESCRIPTION
**Pull request by lugray**
###### Motivation for this change
Allow determining the source from a nix-env query to disambiguate which
plugin you're using/about to use.

###### Things done
- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by blitz — APPROVED** [review]
Looks very straight-forward.

**Review by jonringer — APPROVED** [review]

**Comment by jonringer** [comment]
Thanks @lugray for opening your first PR with nixpkgs :)

**Review by timokau — APPROVED** [review]
Looks good to me, thank you :)

I'll give @evanjs a chance to review. Feel free to ping me if nobody has merged this by the end of the week.

**Review by evanjs — APPROVED** [review]
This is awesome!
I remember wondering why we didn't have this information since initially dealing with vim plugins on nixpkgs.

Thank you for this PR!!

**Comment by jonringer** [comment]
I think this is ready to merge, :)

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 85702 [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>60 packages built:</summary>  - vimPlugins.NrrwRgn  - vimPlugins.Recover-vim  - vimPlugins.YouCompleteMe  - vimPlugins.ale  - vimPlugins.ayu-vim  - vimPlugins.caw-vim  - vimPlugins.coc-denite  - vimPlugins.coc-fzf  - vimPlugins.coc-nvim  - vimPlugins.csv-vim  - vimPlugins.defx-nvim  - vimPlugins.denite-nvim  - vimPlugins.deol-nvim  - vimPlugins.deoplete-fish  - vimPlugins.deoplete-jedi  - vimPlugins.deoplete-khard  - vimPlugins.deoplete-nvim  - vimPlugins.falcon  - vimPlugins.float-preview-nvim  - vimPlugins.ghcid  - vimPlugins.julia-vim  - vimPlugins.lf-vim  - vimPlugins.neoterm  - vimPlugins.nerdtree  - vimPlugins.nvim-lsp  - vimPlugins.rust-vim  - vimPlugins.splitjoin-vim  - vimPlugins.syntastic  - vimPlugins.tcomment_vim  - vimPlugins.unicode-vim  - vimPlugins.vim  - vimPlugins.vim-airline  - vimPlugins.vim-android  - vimPlugins.vim-bazel  - vimPlugins.vim-codefmt  - vimPlugins.vim-cool  - vimPlugins.vim-css-color  - vimPlugins.vim-dispatch  - vimPlugins.vim-elixir  - vimPlugins.vim-endwise  - vimPlugins.vim-fireplace  - vimPlugins.vim-gitgutter  - vimPlugins.vim-glsl  - vimPlugins.vim-go  - vimPlugins.vim-javascript  - vimPlugins.vim-lsc  - vimPlugins.vim-maktaba  - vimPlugins.vim-pandoc  - vimPlugins.vim-polyglot  - vimPlugins.vim-prosession  - vimPlugins.vim-rooter  - vimPlugins.vim-ruby  - vimPlugins.vim-snippets  - vimPlugins.vim-startify  - vimPlugins.vim-table-mode  - vimPlugins.vim-test  - vimPlugins.vim-visual-multi  - vimPlugins.vimtex  - vimPlugins.vista-vim  - vimPlugins.yats-vim</details>

**Pull request merged**
