### PR TITLE
notable: 1.4.0 -> 1.7.3

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

Not sure why we (I?) missed updating 1.5.1,
but 1.6.0 looks good here :).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by mmahut** [comment]
Getting this error while testing the binary.

```
/nix/store/1rdxmqd6pq5vnqxwvy8zv94qj5c039ak-notable-1.6.0-extracted/notable: error while loading shared libraries: libatspi.so.0: cannot open shared object file: No such file or directory
```

**Comment by mmahut** [comment]
``1.7.2`` is out too.

**Comment by dtzWill** [comment]
Updated to 1.7.3 and added missing dep, thanks! Mind taking a look again?

**Comment by mmahut** [comment]
Thank you, looks good.

**Pull request merged**
