### PR TITLE
dokuwiki: 2020-07-29 -> 2022-07-31

### PR DESCRIPTION
**Pull request by onny**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by onny** [comment]
Tests fail with
```
dokuwiki_nginx: output: 
cleanup
kill machine (pid 8)
dokuwiki_caddy # qemu-kvm: terminating on signal 15 from pid 6 (/nix/store/9wa02q541sxq7372f8zv27rl57aribxj-python3-3.10.5/bin/python3.10)
kill machine (pid 19)
dokuwiki_nginx # qemu-kvm: terminating on signal 15 from pid 6 (/nix/store/9wa02q541sxq7372f8zv27rl57aribxj-python3-3.10.5/bin/python3.10)
(finished: cleanup, in 0.17 seconds)
Traceback (most recent call last):
  File "/nix/store/h2y28wijraw8hhmfzipkdvd6rj8mgiki-nixos-test-driver-1.1/bin/.nixos-test-driver-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/h2y28wijraw8hhmfzipkdvd6rj8mgiki-nixos-test-driver-1.1/lib/python3.10/site-packages/test_driver/__init__.py", line 114, in main
    driver.run_tests()
  File "/nix/store/h2y28wijraw8hhmfzipkdvd6rj8mgiki-nixos-test-driver-1.1/lib/python3.10/site-packages/test_driver/driver.py", line 146, in run_tests
    self.test_script()
  File "/nix/store/h2y28wijraw8hhmfzipkdvd6rj8mgiki-nixos-test-driver-1.1/lib/python3.10/site-packages/test_driver/driver.py", line 142, in test_scri>
    exec(self.tests, symbols, None)
  File "<string>", line 17, in <module>
  File "/nix/store/h2y28wijraw8hhmfzipkdvd6rj8mgiki-nixos-test-driver-1.1/lib/python3.10/site-packages/test_driver/machine.py", line 598, in succeed
    raise Exception(
Exception: command `curl -sSfL 'http://site2.local/doku.php?do=login' | grep 'Login'` failed (exit code 1)
```
@_1000101 I might look into it later

**Comment by RaitoBezarius** [comment]
cc @1000101 (because @onny did not ping correctly)

**Comment by sinavir** [comment]
I think the test is falling because the module doesn't create the right filetree (here : https://github.com/NixOS/nixpkgs/blob/3b6f1cfcf9a7fdac1dc78de2edb10031574c2ebb/nixos/modules/services/web-apps/dokuwiki.nix#L316)

Can I help you to finish this PR ?

**Comment by sinavir** [comment]
This modification to dokuwiki module makes the test passing:

```
--- a/nixos/modules/services/web-apps/dokuwiki.nix
+++ b/nixos/modules/services/web-apps/dokuwiki.nix
@@ -318,6 +318,7 @@ in
       "d ${stateDir hostName}/cache 0750 ${user} ${webserver.group} - -"
       "d ${stateDir hostName}/index 0750 ${user} ${webserver.group} - -"
       "d ${stateDir hostName}/locks 0750 ${user} ${webserver.group} - -"
+      "d ${stateDir hostName}/log 0750 ${user} ${webserver.group} - -"
       "d ${stateDir hostName}/media 0750 ${user} ${webserver.group} - -"
       "d ${stateDir hostName}/media_attic 0750 ${user} ${webserver.group} - -"
       "d ${stateDir hostName}/media_meta 0750 ${user} ${webserver.group} - -"
```

**Comment by sinavir** [comment]
May I create a second PR for the above change or it can be integrated to this one ?

**Comment by onny** [comment]
> May I create a second PR for the above change or it can be integrated to this one ?

I can integrate it here :)

**Comment by SuperSandro2000** [comment]
Is this ready to merge?

**Comment by RaitoBezarius** [comment]
> Is this ready to merge?

I think it is, the test is now passing.

**Review by RaitoBezarius — APPROVED** [review]

**Comment by onny** [comment]
Result of `nixpkgs-review pr 184827` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>dokuwiki</li>
  </ul>
</details>

**Comment by onny** [comment]
Result of `nixpkgs-review pr 184827` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 test built:</summary>
  <ul>
    <li>nixosTests.dokuwiki</li>
  </ul>
</details>

**Comment by onny** [comment]
@sinavir thank you for helping out :)

**Pull request merged**
