### PR TITLE
Prometheus service

### PR DESCRIPTION
**Pull request by teh**
###### Motivation for this change

Replaces: https://github.com/NixOS/nixpkgs/pull/8216/files
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

https://github.com/NixOS/nixpkgs/pull/8216/files

### CODE REVIEW

**Comment by fpletz** [comment]
Thanks for opening this PR! As we're already using this module I'd like to review and compare with our code that we're already using in production, probably this evening.

**Comment by teh** [comment]
@fpletz happy to review your company's module as well if you open a PR.

**Comment by fpletz** [comment]
Sorry, forgot about this, will take a look later this evening.

**Comment by fpletz** [comment]
Thanks for your changes, you have fixed 1.0 compatibility more thoroughly than we did. :+1: Other than that, we just moved the nix file to a new folder and added some exporters. This shouldn't be controversial and I'll push those later. 

Regarding 16.09, we have the consensus that adding new modules doesn't hurt, so we'll backport eventually. You already opened another PR for the node exporter #18515 which we also did. We also have a module for the nginx exporter and one for the alertmanager is coming up. I'd like to wait with backporting until we have all the components we want to support in place and in a sensible structure.

**Pull request merged**
