### PR TITLE
doc: update python manual to reference python 3.8 instead of 3.5

### PR DESCRIPTION
**Pull request by bhipple**
Improvement suggested in #87094

CC @fridh @jonringer

### CODE REVIEW

**Review by FRidh — APPROVED** [review]
Looks good. Will also need to get rid of blaze as example because that package is no longer maintained and entirely functioning.

**Comment by doronbehar** [comment]
Question: Why not use `python3` so it will point to whatever's considered as Python3 ?

**Comment by FRidh** [comment]
Depends on the exact use whether that is possible. Sometimes it's used to indicate specifically there are other versions available.

**Review by prusnak — APPROVED** [review]

**Comment by bhipple** [comment]
> Looks good. Will also need to get rid of blaze as example because that package is no longer maintained and entirely functioning.

Sounds good; I see a couple other things that are not idiomatic and could use touchups, but I'll send those in a follow-up and keep this PR just on the 3.5 -> 3.8 rename for easy reviewability.

**Pull request merged**
