### PR TITLE
pythonPackages.pytest: Revert "4.6.5 -> 5.1.0 in case of Python 3"

### PR DESCRIPTION
**Pull request by peti**
This reverts commit b3ddab852a5229331553e07be6055fb015966b42. The update broke
a number of other packages, like python-blessed and python-django-extentsions,
which are dependencies of GNU Mailman.

Ping @FRidh.

### CODE REVIEW

**Comment by jonringer** [comment]
The better solution be to just disable the tests that aren't compatible.

This will likely break packages that are using pytest5 features.

**Comment by jonringer** [comment]
Also, python doesn't handle mutliple versions well, since they have to coexist in the same environment. There should only ever be a single version of a package for an interpreter version.

**Comment by peti** [comment]
> The better solution be to just disable the tests that aren't compatible.

Well, after we've reverted the update, then we can disable the test suite that turn out to depend on pytest-5.x features.

**Comment by FRidh** [comment]
This is a mass rebuild. The far majority of packages are already compatible or have been adjusted. Those that need fixing can be done now and backported to 19.09. Also, reverting will break other packages.

**Comment by FRidh** [comment]
I've fixed the two mentioned packages on master and 19.09.

**Comment by FRidh** [comment]
4dd38c42894c61358b9b0f56fe7838b045a157eb
aa6c38d9c162ecfc9c9f330ca65eb53de6d844c3

**Comment by peti** [comment]
OK, thank you for the fix for `django-extensions`. I'll check how far I get now compiling Mailman.

**Pull request closed without merging**
