### PR TITLE
nixos/tests: add step-ca test

### PR DESCRIPTION
**Pull request by mohe2015**
###### Motivation for this change
This is more or less what I check on updates.

###### Things done
Probably IFD is not allowed but we will see. If its not allowed the only way is to put the files in-repo I suppose.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mohe2015** [comment]
@ofborg build step-ca.passthru.tests

**Comment by mohe2015** [comment]
@ofborg build step-ca.passthru.tests

**Comment by mohe2015** [comment]
Would it be possible to get this merged before branchoff so it's in the next release?

**Comment by mohe2015** [comment]
Any chance to get this merged? Should be fairly uncontroversial.

**Review by m1cr0man — APPROVED** [review]
The test looks good to me. I'm not all too familiar with step-ca but this seems fine. Nice to have the tests in case I break something in acme that affects it ;)

**Comment by ju1m** [comment]
Looks like this is the only use of `passthru.tests` in `nixos/modules/`, is it a deliberate choice or a mistake? Isn't the `passthru.tests` in `pkgs/tools/security/step-ca/default.nix` [enough](https://github.com/NixOS/nixpkgs/pull/159187#issuecomment-1037224924)? Thanks in advance for your time.

**Pull request merged**
