### PR TITLE
coqPackages.CoLoR: 1.4.0 -> 1.7.0

### PR DESCRIPTION
**Pull request by jpas**
###### Motivation for this change

I'm working on a project that requires this package and it is about a year years out of date and the old version no longer states support for Coq 8.6 and 8.7 which are at least 2 minor versions out of date.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vbgl** [comment]
The updated version won’t build with Coq < 8.8. Please either fix the `compatibleCoqVersions` attribute or keep older versions of CoLoR for older versions of Coq.

**Comment by jpas** [comment]
With this re-factor it should be pretty straight forward to add in CoLoR 1.7.0 for Coq 8.10.

Would a new PR make sense for adding that or should I rename this one and add that version as well?

**Comment by vbgl** [comment]
If you don’t mind, please add version 1.7.0 for Coq 8.10 in this very PR. Thanks.

**Comment by vbgl** [comment]
@GrahamcOfBorg build coqPackages.CoLoR

**Pull request merged**
