### PR TITLE
binutils: try to fix plv8 build

### PR DESCRIPTION
**Pull request by jtojnar**
Backport patch from 2.36 so that gold can succeed in linking programs without complaining
unknown program property type 0xc0008002 in .note.gnu.property section

Should fix: https://github.com/NixOS/nixpkgs/issues/134190

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Verified it fixes plv8 using https://github.com/jtojnar/nixpkgs/commit/94446ca4058a6fcdefa89c2d3b1b7352377368a0
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
Verified it works with https://github.com/jtojnar/nixpkgs/commit/94446ca4058a6fcdefa89c2d3b1b7352377368a0

**Comment by vcunat** [comment]
I _think_ I've seen these errors also when building some other packages.

**Comment by sternenseemann** [comment]
This affects all of `haskellPackages` which haven't failed so far since they don't usually use `-Werror` for linking, but it'd be nice to solve this just to be safe.

**Review by lovesegfault — APPROVED** [review]
This looks good, I'll look into bumping binutils in the next couple days.

**Pull request merged**
