### PR TITLE
pythonPackages.drf-jwt: init at 1.19.0

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
closes https://github.com/NixOS/nixpkgs/pull/120957

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @critbase @ivegotasthma

### CODE REVIEW

**Comment by dotlambda** [comment]
Should we send @ivegotasthma an email before removing him?

**Comment by grahamc** [comment]
> Should we send @ivegotasthma an email before removing him?

Please do.

**Comment by dotlambda** [comment]
I sent an email. Ofborg will fail cause I forgot to remove him from other packages.

**Comment by grahamc** [comment]
Note that we can have maintainers who do not have a GitHub account, so it is possible the only change is removing their github handle.

**Pull request merged**
