### PR TITLE
owncloud: 7.0.5 -> 8.1.0

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This updates owncloud.

Applied to my channel-unstable branch and test-building worked. I do not have a local owncloud installation though, so one of you might test this with a real installation?

### CODE REVIEW

**Comment by domenkozar** [comment]
cc @offlinehacker @matejc

**Comment by matejc** [comment]
@matthiasbeyer can you confirm that it is working with the nixos module, with clean install, I packaged owncloud 8 locally a few days back.. but I was not able make it work yet as a service, I will continue my work this weekend (If I find time), and my version(s) of owncloud(s) is using my-not-yet-pushed nginx abstraction layer... I can speed things up a bit, but before this weekend there will be little or no progress.
Also, I would suggest to make a seperate package for owncloud 7.* and owncloud 8.*

**Comment by geerds** [comment]
@matejc a nginx abstractin layer? That would be awesome! :smile:

**Comment by matthiasbeyer** [comment]
Sorry for the delay. I did not confirm it works. I just test built it.

**Comment by matthiasbeyer** [comment]
Will close now. Others are better in doing these kind of updates.

**Pull request closed without merging**
