### PR TITLE
jpegexiforient: init at 2002-02-17

### PR DESCRIPTION
**Pull request by infinisil**
###### Motivation for this change
This allows `feh --edit` to work properly, whereas previously it would give
```
feh WARNING: lossless rotate: Failed to exec jpegexiforient: No such file or directory
feh WARNING: lossless rotate: Failed to update EXIF orientation tag: jpegexiforient returned 1
```

###### Things done

- [x] Built and tested on linux

### CODE REVIEW

**Review by jonringer — COMMENTED** [review]
I would break this out into two commits:

```
jpegexiforient: init at unstable-2002-02-17
feh: add jpegexiforient to wrapped path
```

I could see an instance where someone may want to revert the wrapping, and currently they would also have to remove the jpegexiforient package as well

**Comment by Infinisil** [comment]
Yeah, done that

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS
diff LGTM
commits LGTM
executables seem to work
didn't do a proper test

```
https://github.com/NixOS/nixpkgs/pull/73361
7 package were build:
betterlockscreen deco feh jpegexiforient pywal python38Packages.pywal wpgtk
```

**Comment by Infinisil** [comment]
`feh`'s build failure on darwin isn't related: https://hydra.nixos.org/job/nixpkgs/trunk/feh.x86_64-darwin

**Pull request merged**
