### PR TITLE
tinc-haskell: Rename package name to avoid conflict

### PR DESCRIPTION
**Pull request by robbinch**
###### Things done
- [ ] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
You need to update the path in `all-packages.nix` as well

**Comment by robbinch** [comment]
You're right, just fixed that :)

**Comment by fpletz** [comment]
Thanks for the quick fix! :beers:

**Comment by peti** [comment]
IMHO, the package belongs into `configuration-common.nix` rather than `all-packages.nix`.

**Comment by peti** [comment]
Done in cf4a69e2ec73c5abf5812e20a558bf45b9646e56.

**Pull request merged**
