### PR TITLE
ruby: Revert rubygems to 3.0.6 for ruby 2.6 and earlier

### LINKED ISSUE #76629: Vagrant broken by rubygems 3.1.2 upgrade: uninitialized constant I18n::Config (NameError)
**Describe the bug**
Vagrant no longer works; every operation fails with an error `uninitialized constant I18n::Config (NameError)`. I bisected this regression to commit 298010982b8986f6669e2b762634dac48253d7ba “ruby: rubygems 3.0.6 -> 3.1.2” (#76495).

**To Reproduce**
```console
$ nix-shell -p vagrant --run 'vagrant version'
/nix/store/x2xagsdlb556kg1jzx0qrbc1wyjf8092-ruby2.6.5-json-2.1.0/lib/ruby/gems/2.6.0/gems/json-2.1.0/lib/json/common.rb:100: warning: already initialized constant JSON::NaN
/nix/store/p4hrycs0zaa9x0gsqylbk577ppnryixr-vagrant-2.2.6/lib/ruby/gems/2.6.0/gems/json-2.1.0/lib/json/common.rb:100: warning: previous definition of NaN was here
/nix/store/x2xagsdlb556kg1jzx0qrbc1wyjf8092-ruby2.6.5-json-2.1.0/lib/ruby/gems/2.6.0/gems/json-2.1.0/lib/json/common.rb:102: warning: already initialized constant JSON::Infinity
/nix/store/p4hrycs0zaa9x0gsqylbk577ppnryixr-vagrant-2.2.6/lib/ruby/gems/2.6.0/gems/json-2.1.0/lib/json/common.rb:102: warning: previous definition of Infinity was here
/nix/store/x2xagsdlb556kg1jzx0qrbc1wyjf8092-ruby2.6.5-json-2.1.0/lib/ruby/gems/2.6.0/gems/json-2.1.0/lib/json/common.rb:104: warning: already initialized constant JSON::MinusInfinity
/nix/store/p4hrycs0zaa9x0gsqylbk577ppnryixr-vagrant-2.2.6/lib/ruby/gems/2.6.0/gems/json-2.1.0/lib/json/common.rb:104: warning: previous definition of MinusInfinity was here
/nix/store/x2xagsdlb556kg1jzx0qrbc1wyjf8092-ruby2.6.5-json-2.1.0/lib/ruby/gems/2.6.0/gems/json-2.1.0/lib/json/common.rb:129: warning: already initialized constant JSON::UnparserError
/nix/store/p4hrycs0zaa9x0gsqylbk577ppnryixr-vagrant-2.2.6/lib/ruby/gems/2.6.0/gems/json-2.1.0/lib/json/common.rb:129: warning: previous definition of UnparserError was here
Traceback (most recent call last):
	11: from /nix/store/5y31ch80fwnvbz2lpc7shn0jgnf2mql1-vagrant-2.2.6/bin/.vagrant-wrapped:18:in `<main>'
	10: from /nix/store/5y31ch80fwnvbz2lpc7shn0jgnf2mql1-vagrant-2.2.6/bin/.vagrant-wrapped:18:in `load'
	 9: from /nix/store/5y31ch80fwnvbz2lpc7shn0jgnf2mql1-vagrant-2.2.6/lib/ruby/gems/2.6.0/gems/vagrant-2.2.6/bin/vagrant:88:in `<top (required)>'
	 8: from /nix/store/7l24siwk9yw0znjpcapq0rvpdghxmwsc-ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 7: from /nix/store/7l24siwk9yw0znjpcapq0rvpdghxmwsc-ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 6: from /nix/store/5y31ch80fwnvbz2lpc7shn0jgnf2mql1-vagrant-2.2.6/lib/ruby/gems/2.6.0/gems/vagrant-2.2.6/lib/vagrant.rb:278:in `<top (required)>'
	 5: from /nix/store/p4hrycs0zaa9x0gsqylbk577ppnryixr-vagrant-2.2.6/lib/ruby/gems/2.6.0/gems/i18n-1.1.1/lib/i18n.rb:55:in `load_path'
	 4: from /nix/store/p4hrycs0zaa9x0gsqylbk577ppnryixr-vagrant-2.2.6/lib/ruby/gems/2.6.0/gems/i18n-1.1.1/lib/i18n.rb:42:in `config'
	 3: from /nix/store/7l24siwk9yw0znjpcapq0rvpdghxmwsc-ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 2: from /nix/store/7l24siwk9yw0znjpcapq0rvpdghxmwsc-ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 1: from /nix/store/p4hrycs0zaa9x0gsqylbk577ppnryixr-vagrant-2.2.6/lib/ruby/gems/2.6.0/gems/i18n-1.1.1/lib/i18n/config.rb:5:in `<top (required)>'
/nix/store/p4hrycs0zaa9x0gsqylbk577ppnryixr-vagrant-2.2.6/lib/ruby/gems/2.6.0/gems/i18n-1.1.1/lib/i18n/config.rb:6:in `<module:I18n>': uninitialized constant I18n::Config (NameError)
```

**Expected behavior**
```console
$ nix-shell -I nixpkgs=channel:nixos-19.09 -p vagrant --run 'vagrant version'
Installed Version: 2.2.6
Latest Version: 2.2.6
 
You're running an up-to-date version of Vagrant!
```

**Metadata**
```console
$ nix run nixpkgs.nix-info -c nix-info -m
nix: src/libexpr/attr-set.hh:54: void nix::Bindings::push_back(const nix::Attr&): Assertion `size_ < capacity_' failed.
Aborted (core dumped)

$ what
what: command not found

$ nix-shell -p nix-info --run 'nix-info -m'
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.6, NixOS, 20.03pre206632.b0bbacb5213 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre206632.b0bbacb5213, nixos-19.09-19.09.1687.c5d5561f772"`
 - channels(anders): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [vagrant]
# a list of nixos modules affected by the problem
module:
```

cc @aneeshusa

### PR DESCRIPTION
**Pull request by andersk**
###### Motivation for this change

The rubygems upgrade from 3.0.6 to 3.1.2 (#76495) broke vagrant at runtime. Specifically, it

* works with ruby 2.6 and rubygems 3.0.6,
* fails with ruby 2.6 and rubygems 3.1.2,
* works with ruby 2.7 and rubygems 3.1.2,

perhaps because bundler 2.1 vendored by rubygems 3.1 conflicts with bundler 1.17 vendored by ruby 2.6.

Fixes #76629.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @vrthra @manveru @alyssais @zimbatm @aneeshusa

### CODE REVIEW

**Comment by alyssais** [comment]
I’m strongly opposed to reverting because one package is incompatible.

**Comment by andersk** [comment]
I’m open to any suggestions—what should we do?

Note that I’m not reverting anything for ruby 2.7, with which the new rubygems works fine.

**Comment by alyssais** [comment]
Does Vagrant work with Ruby 2.7?  That would be a fix I'd be much
happier merging now, even before we fix the underlying issue here.

**Comment by andersk** [comment]
Hmm. I thought it did, but my test must have been wrong. I tested `vagrant.override { ruby = ruby_2_7; }` on top of this patch, which works, but without this patch, it still fails in the same way. So Ruby 2.6 must have been leaking in to my test somewhere.

**Comment by andersk** [comment]
I discovered an alternative fix on the Vagrant side only: #76765. I have no idea why it works, though.

**Pull request closed without merging**
