### PR TITLE
[Backport release-23.11] mastodon: 4.2.8 -> 4.2.9

### PR DESCRIPTION
**Pull request by erictapen**
(cherry picked from commit b5fe3210557b634a521e81357ae2af9637b09c46)

Backport of https://github.com/NixOS/nixpkgs/pull/315915#issuecomment-2140315991

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Ma27** [comment]
@erictapen I think this broke my setup. After deploying this I get an error 500 with the following error:

```
May 30 20:38:17 mastodon puma[725]: [cb8b41ce-2a37-4528-ab68-877baac50c9c] ActionDispatch::RemoteIp::IpSpoofAttackError (IP spoofing attack?! client 127.0.0.1 is not a trusted proxy HTTP_CLIENT_IP=nil HTTP_X_FORWARDED_FOR="<IPv6 of my laptop>, <IPv6 of the reverse proxy>"):
```

Please note that my mastodon runs in an nspawn container and the reverse-proxy on the host.

After `switch-to-configuration test`ing my previous generation with mastodon 4.2.8 it worked fine again.

**Comment by erictapen** [comment]
@Ma27 Damn, I'm sorry. We could revert the change and add release notes for 24.05? On the other hand your setup isn't explicitly supported by the module, so some breakage might be expected, even on stable. What do you think would be best way forward?

**Comment by Ma27** [comment]
> Damn, I'm sorry

No worries, it happens!

---

A few thoughts (though I'm on the consuming side on pkgs.mastodon, so not sure if that makes sense):

For 24.05: as you said, it's not the "official" way to use the module and the release itself is in beta. IMHO it's sufficient to add a note to the release notes.

For 23.11 I see a few options:
* apply the security patches by hand (we surely have people upgraded to 4.2.9 now, though).
* try to find a condition where to warn/assert, maybe?

**Comment by erictapen** [comment]
> apply the security patches by hand (we surely have people upgraded to 4.2.9 now, though).

Sounds tedious, not sure it would be worth the effort, considering that the issues mentioned are all marked as moderate or low severity.

> try to find a condition where to warn/assert, maybe?

I don't really see how we could check for the condition from inside the module.

**Pull request merged**
