### PR TITLE
python312Packages.certomancer 0.11.0 -> 0.12.0

### PR DESCRIPTION
**Pull request by djacu**
## Description of changes

Bumped version to 0.12.0 and disabled 1 broken test.

Several tests are broken on Python 3.12 and there is an open issue to fix it.
https://github.com/MatthiasValvekens/certomancer/issues/12

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 304985` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages failed to build:</summary>
  <ul>
    <li>maigret</li>
    <li>maigret.dist</li>
    <li>python311Packages.pyhanko</li>
    <li>python311Packages.pyhanko.dist</li>
    <li>python311Packages.xhtml2pdf</li>
    <li>python311Packages.xhtml2pdf.dist</li>
    <li>python312Packages.pyhanko</li>
    <li>python312Packages.pyhanko.dist</li>
    <li>python312Packages.xhtml2pdf</li>
    <li>python312Packages.xhtml2pdf.dist</li>
    <li>sasview</li>
    <li>sasview.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.certomancer</li>
    <li>python311Packages.certomancer.dist</li>
    <li>python312Packages.certomancer</li>
    <li>python312Packages.certomancer.dist</li>
  </ul>
</details>

**Review by samrose — APPROVED** [review]

**Comment by Moraxyc** [comment]
Result of `nixpkgs-review pr 304985` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages failed to build:</summary>
  <ul>
    <li>maigret</li>
    <li>maigret.dist</li>
    <li>python311Packages.pyhanko</li>
    <li>python311Packages.pyhanko.dist</li>
    <li>python311Packages.xhtml2pdf</li>
    <li>python311Packages.xhtml2pdf.dist</li>
    <li>python312Packages.pyhanko</li>
    <li>python312Packages.pyhanko.dist</li>
    <li>python312Packages.xhtml2pdf</li>
    <li>python312Packages.xhtml2pdf.dist</li>
    <li>sasview</li>
    <li>sasview.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.certomancer</li>
    <li>python311Packages.certomancer.dist</li>
    <li>python312Packages.certomancer</li>
    <li>python312Packages.certomancer.dist</li>
  </ul>
</details>

**Review by Moraxyc — APPROVED** [review]

**Comment by Moraxyc** [comment]
fix build (https://hydra.nixos.org/build/260937779)

ZHF: https://github.com/NixOS/nixpkgs/issues/309482

**Comment by risicle** [comment]
Hold on, what makes us think this is just "broken tests" on 3.12 and not breakage of the features behind them?

**Comment by Moraxyc** [comment]
After reviewing the changes upstream and related resources, we cannot take this issue lightly.
 - https://github.com/MatthiasValvekens/certomancer/issues/12
 - https://github.com/wbond/asn1crypto/pull/230
 - https://github.com/wbond/asn1crypto/pull/265
 - https://github.com/NixOS/nixpkgs/commit/418b5d9e5c316c15f7390cdbacaddd6df4e12c81

`asn1crypto` removed `.hash_algo` for safety reasons, but there hasn’t been a release since that change. Consequently, the package in Nixpkgs has two versions of it. When we use Python 3.12, it includes an unstable version with the patch.

I believe a better approach is to disable the `certomancer` build on Python 3.12 until `asn1crypto` releases a new version and certomancer catches up.

Sorry for linking it to ZHF without sufficient consideration.

**Comment by GaetanLepage** [comment]
I opened #315532 and then discovered this PR.
It looks like it addresses most of the concerns raised above.
Feel free to either pick changes from it (and close it) or merge it directly.

**Review by SuperSandro2000 — APPROVED** [review]

**Pull request closed without merging**
