### PR TITLE
libvirt: 9.10.0 -> 10.0.0

### PR DESCRIPTION
**Pull request by matdibu**
## Description of changes

As per the comment in `pkgs/development/libraries/libvirt/default.nix`, the following version bumps were applied:
- `libvirt`: `9.10.0` to `10.0.0`
- `python<version>Packages.libvirt`: `9.10.0` to `10.0.0`
- `perl<version>Packages.SysVirt`: `9.8.0` to `10.0.0`

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by matdibu** [comment]
output of `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`:

```
warning: Ignoring setting 'auto-allocate-uids' because experimental feature 'auto-allocate-uids' is not enabled
warning: Ignoring setting 'impure-env' because experimental feature 'configurable-impure-env' is not enabled
error: builder for '/nix/store/bwjxdac7qyqbjwx6msc9j082llgxwx26-nixops-unstable-2023-12-17.drv' failed with exit code 1;
       last 10 log lines:
       > Creating a wheel...
       > * Getting build dependencies for wheel...
       > * Building wheel...
       > Successfully built nixops-2.0.0-py3-none-any.whl
       > Finished creating a wheel...
       > Finished executing pypaBuildPhase
       > Running phase: pythonRuntimeDepsCheckHook
       > Executing pythonRuntimeDepsCheck
       > Checking runtime dependencies for nixops-2.0.0-py3-none-any.whl
       >   - prettytable<0.8.0,>=0.7.2 not satisfied by version 3.9.0
       For full logs, run 'nix log /nix/store/bwjxdac7qyqbjwx6msc9j082llgxwx26-nixops-unstable-2023-12-17.drv'.
error: 1 dependencies of derivation '/nix/store/pq3nmvhba55gz3hyj1gvyqbkkrii762y-python3.11-nixops-digitalocean-unstable-2022-08-14.drv' failed to build
error: 1 dependencies of derivation '/nix/store/mrzing4vsz5dgxk65b7akqnjc6nkaf02-python3.11-nixops-encrypted-links-unstable-2021-02-16.drv' failed to build
error: 1 dependencies of derivation '/nix/store/sxj52v49m8xamjczz8az799jm8gs787m-python3.11-nixops-hercules-ci-unstable-2021-10-06.drv' failed to build
error: 1 dependencies of derivation '/nix/store/m0q7vas726dz5jr8gcn2s0jxwkw15psw-python3.11-nixops-hetznercloud-unstable-2023-02-19.drv' failed to build
error: 1 dependencies of derivation '/nix/store/y1ar5lc5v6k3rgbj0aq1546k2w0gy6mc-python3.11-nixops-libvirtd-unstable-2023-09-01.drv' failed to build
error: 1 dependencies of derivation '/nix/store/9z4p9sbhhm50bgbrarwhc1zzqr522bc9-python3.11-nixops-vbox-unstable-2023-08-10.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rmdvl4ba8xalzzyvwsmikwxzwqd8kin5-python3.11-nixos-modules-contrib-unstable-2021-01-20.drv' failed to build
error: 2 dependencies of derivation '/nix/store/3bdpidsclfsck62ahvbpq65v0d351xpa-python3.11-nixops-aws-unstable-2023-08-09.drv' failed to build
error: 2 dependencies of derivation '/nix/store/kfkz0als2x4q6ya8bsm7i3484wivhi93-python3.11-nixops-gce-unstable-2023-05-26.drv' failed to build
error: 2 dependencies of derivation '/nix/store/sa9ss5dzmwgcvgm05kx8k9xpcnhwnrpr-python3.11-nixops-hetzner-unstable-2022-04-23.drv' failed to build
error: 9 dependencies of derivation '/nix/store/k5b8mx91zdvix846l2qg86ax9hsccvyv-nixops-unstable-2023-12-17.drv' failed to build
[1/17/35 built (1 failed), 1193 copied (12276.5/12281.2 MiB), 3107.1 MiB DL] building multipass-1.13.0 (buildPhase): [ 87%]herror: builder for '/nix/store/b1gpsbby32zki9w0ic224qpwswd5gg0r-virt-manager-4.1.0.drv' failed with exit code 1;
       last 10 log lines:
       >     raise libvirtError('virDomainAttachDeviceFlags() failed')
       > libvirt.libvirtError: unsupported configuration: hotplug is not supported for hostdev subsys type 'default'
       >
       >
       > TESTSUITE: Didn't find grep=not supported by the connection driver: virDomainAttachDevice
       >
       > =========================== short test summary info ============================
       > FAILED tests/test_cli.py::testCLI0261virt_xml - AssertionError: Command was: ./virt-xml  test-for-virtxml --add-device --ho...
       > =========== 1 failed, 521 passed, 17 skipped, 4 deselected in 13.67s ===========
       > /nix/store/v5irq7wvkr7kih0hhnch5nnv2dcq8c4f-stdenv-linux/setup: line 1557: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/b1gpsbby32zki9w0ic224qpwswd5gg0r-virt-manager-4.1.0.drv'.
error: builder for '/nix/store/75wjh45q9hg7inmn2dy8lmzc7f9fidii-vagrant-2.3.7.drv' failed with exit code 1;
       last 10 log lines:
       > /nix/store/51frfqmz7i30x0h1p8vdsmb40wdv2987-vagrant-2.3.7/lib/ruby/gems/3.1.0/gems/vagrant-2.3.7/.runner.sh: interpreter directive changed from "#!/usr/bin/env bash" to "/nix/store/9vafkkic27k7m4934fpawl6yip3a6k4h-bash-5.2-p21/bin/bash"
       > /nix/store/51frfqmz7i30x0h1p8vdsmb40wdv2987-vagrant-2.3.7/lib/ruby/gems/3.1.0/gems/vagrant-2.3.7/bin/vagrant: interpreter directive changed from "#!/usr/bin/env ruby" to "/nix/store/mqvgyyxws079dwijpslhgmm5ylmx880a-ruby-3.1.4/bin/ruby"
       > stripping (with command strip and flags -S -p) in  /nix/store/51frfqmz7i30x0h1p8vdsmb40wdv2987-vagrant-2.3.7/lib /nix/store/51frfqmz7i30x0h1p8vdsmb40wdv2987-vagrant-2.3.7/bin
       > rewriting symlink /nix/store/51frfqmz7i30x0h1p8vdsmb40wdv2987-vagrant-2.3.7/nix-support/gem-meta/spec to be relative to /nix/store/51frfqmz7i30x0h1p8vdsmb40wdv2987-vagrant-2.3.7
       > Running phase: installCheckPhase
       > Vagrant failed to initialize at a very early stage:
       >
       > The executable 'cmd.exe' Vagrant is trying to run was not
       > found in the PATH variable. This is an error. Please verify
       > this software is installed and on the path.
       For full logs, run 'nix log /nix/store/75wjh45q9hg7inmn2dy8lmzc7f9fidii-vagrant-2.3.7.drv'.
error: 3 dependencies of derivation '/nix/store/9vrz2ldzf9mgwrssmnvngfsshcml21zd-review-shell.drv' failed to build
5 packages failed to build:
nixops_unstable nixops_unstable.dist vagrant virt-manager virt-manager.dist

36 packages built:
appvm collectd diffoscope diffoscope.dist diffoscope.man docker-machine-kvm docker-machine-kvm2 gnome.gnome-boxes guestfs-tools libguestfs libguestfs-with-appliance librenms libvirt libvirt-glib libvirt-glib.dev libvirt-glib.devdoc mgmt minikube multipass ocamlPackages.ocaml_libvirt perl536Packages.SysVirt perl536Packages.SysVirt.devdoc perl538Packages.SysVirt perl538Packages.SysVirt.devdoc python311Packages.guestfs python311Packages.guestfs.dist python311Packages.libvirt python311Packages.libvirt.dist python312Packages.guestfs python312Packages.guestfs.dist rubyPackages.ruby-libvirt rubyPackages_3_2.ruby-libvirt rubyPackages_3_3.ruby-libvirt virt-manager-qt virt-top virt-viewer

error: build log of '/nix/store/k5b8mx91zdvix846l2qg86ax9hsccvyv-nixops-unstable-2023-12-17.drv^*' is not available
error: build log of '/nix/store/qfgyg93db06w43lvnxmzs7g6v0rzqqrq-nixops-unstable-2023-12-17' is not available
error: build log of '/nix/store/k5b8mx91zdvix846l2qg86ax9hsccvyv-nixops-unstable-2023-12-17.drv^*' is not available
error: build log of '/nix/store/ji4kq064zsz3pcwyq540ax3pb8hvw2g3-nixops-unstable-2023-12-17-dist' is not available
$ /nix/store/p1l4j192w1abk7mmkg60qmvc18svhky4-nix-2.18.1/bin/nix-shell /home/mateidibu/.cache/nixpkgs-review/rev-72cdb495faa2c5597dadf02e3c1f68e67c584328/shell.nix --nix-path nixpkgs=/home/mateidibu/.cache/nixpkgs-review/rev-72cdb495faa2c5597dadf02e3c1f68e67c584328/nixpkgs nixpkgs-overlays=/run/user/1000/tmpqelztmoi
```

**Comment by matdibu** [comment]
Is this error unrelated to the changes to libvirt?
```
Checking runtime dependencies for nixops-2.0.0-py3-none-any.whl
  - prettytable<0.8.0,>=0.7.2 not satisfied by version 3.9.0
```

**Comment by matdibu** [comment]
As far as I understand, these are the packages that fail to build:

### `nixops_unstable`
```
Checking runtime dependencies for nixops-2.0.0-py3-none-any.whl
  - prettytable<0.8.0,>=0.7.2 not satisfied by version 3.9.0
```
- is there an issue with nixops 2?

### `vagrant`
```
       > Running phase: installCheckPhase
       > Vagrant failed to initialize at a very early stage:
       >
       > The executable 'cmd.exe' Vagrant is trying to run was not
       > found in the PATH variable. This is an error. Please verify
       > this software is installed and on the path.
```

### `virt-manager`
```
libvirt.libvirtError: unsupported configuration: hotplug is not supported for hostdev subsys type 'default'


TESTSUITE: Didn't find grep=not supported by the connection driver: virDomainAttachDevice
```
- is it looking for the string `not supported by the connection driver` but finding `unsupported configuration: hotplug is not supported for hostdev subsys type 'default'` ?

**Comment by matdibu** [comment]
@fpletz I saw you self requested a review two weeks ago, could you give your two cents on the issue(s) ?

**Comment by fpletz** [comment]
nixops-unstable is also broken on master with the same issue. vagrant now builds on master.

virt-manager needed a patch from master. Pushed.

Also rebased this PR and fixed the commit message since there was a staging merge on master. NixOS tests are green.

**Review by fpletz — APPROVED** [review]

**Pull request merged**
