### PR TITLE
Fix the upstream project URL

### PR DESCRIPTION
**Pull request by mquinson**
As a upstream developer, I just wanted to tell you that our URL changed recently.
This change seems trivial enough to not mandate the full check-list of your usual contributing guidelines. 

Kudos for this process, and for the rest.
Mt

### CODE REVIEW

**Comment by veprbl** [comment]
Commit message needs to have a "simgrid: " prefix as required by the contribution guidelines https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md

**Comment by mquinson** [comment]
Have fun doing so ;)

**Comment by veprbl** [comment]
Thank you!

**Comment by mquinson** [comment]
thank YOU ;)

**Pull request closed without merging**
