### PR TITLE
libqalculate, qalculate-gtk: 4.1.1 -> 4.2.0

### PR DESCRIPTION
**Pull request by cyclic-pentane**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by doronbehar** [comment]
Thanks!

**Comment by vcunat** [comment]
This PR broke the build on aarch64-linux, transitively breaking plasma.  The issue was shown even before merging in the OfBorg CI.

**Comment by gebner** [comment]
> The issue was shown even before merging in the OfBorg CI.

It is very confusing that a build failure is listed as "28 checks passed".

**Comment by vcunat** [comment]
I think OfBorg never makes CI red, maybe because for many packages it runs into timeouts or something. I'm not even sure if I've ever seen nixpkgs CI red.

Anyway, the interesting part of config.log is probably
```
configure:6828: checking whether the C compiler works
configure:6850: aarch64-unknown-linux-gnu-gcc -g -O2   conftest.c  >&5
/nix/store/mskx817hz1irhv9q0b6lvdaqbwimv4fp-binutils-2.38/bin/ld: cannot find crt1.o: No such file or directory
/nix/store/mskx817hz1irhv9q0b6lvdaqbwimv4fp-binutils-2.38/bin/ld: cannot find crti.o: No such file or directory
collect2: error: ld returned 1 exit status
configure:6854: $? = 1
configure:6894: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "libqalculate"
| #define PACKAGE_TARNAME "libqalculate"
| #define PACKAGE_VERSION "4.2.0"
| #define PACKAGE_STRING "libqalculate 4.2.0"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define PACKAGE "libqalculate"
| #define VERSION "4.2.0"
| /* end confdefs.h.  */
| 
| int
| main (void)
| {
| 
|   ;
|   return 0;
| }
configure:6899: error: in `/build/source':
configure:6901: error: C compiler cannot create executables
See `config.log' for more details
```

**Pull request merged**
