### PR TITLE
Fix `NIXOS_OZONE_WL` not working with 1Password

### PR DESCRIPTION
**Pull request by Enzime**
###### Description of changes

`makeWrapper` is creating a binary wrapper instead of a shell wrapper so we need to directly use `makeShellWrapper` instead as the logic for `NIXOS_OZONE_WL` relies on shell variable expansion.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SebTM** [comment]
Can you explain me the difference / the issue you occur with as I'm using it daily and trying to understand? :)

**Comment by Enzime** [comment]
The Ozone flags don’t get added when `NIXOS_OZONE_WL` is set, so 1Password is rendering through XWayland instead of Wayland directly. This is because the flag we add relies on being executed in a shell wrapper (shell variable expansion) but 1Password GUI uses a binary wrapper.

**Review by SebTM — APPROVED** [review]
Thanks for the explanation 👍🏻

**Comment by Enzime** [comment]
Haven’t run into that issue, the only thought that comes to mind would be are you using `programs._1password-gui.enable`?

**Comment by SebTM** [comment]
> Haven’t run into that issue, the only thought that comes to mind would be are you using `programs._1password-gui.enable`?

That wasn't the issue but by accident I figured it out - this will happen if you have / or set the environment-variable `GTK_USE_PORTAL=1` like I had in my login-script as global-env.

**Review by Ma27 — APPROVED** [review]

**Pull request merged**
