### PR TITLE
mailspring: 1.12.0 -> 1.13.1

### PR DESCRIPTION
**Pull request by Arjun31415**
## Description of changes
https://github.com/Foundry376/Mailspring/releases

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Arjun31415** [comment]
@GrahamcOfBorg eval

**Comment by LudovicoPiero** [comment]
v1.13.2 just got released. 
https://github.com/Foundry376/Mailspring/releases/tag/1.13.2

**Comment by Arjun31415** [comment]
Don't we need 1.13.1 in the commit history of nixpkgs ? and then 1.13.2

**Comment by LudovicoPiero** [comment]
> Don't we need 1.13.1 in the commit history of nixpkgs ? and then 1.13.2

Here's an example https://github.com/NixOS/nixpkgs/pull/272289

**Comment by Arjun31415** [comment]
> > Don't we need 1.13.1 in the commit history of nixpkgs ? and then 1.13.2
> 
> Here's an example #272289

Oh ok. Got it

**Comment by Arjun31415** [comment]
> > Don't we need 1.13.1 in the commit history of nixpkgs ? and then 1.13.2
> 
> Here's an example #272289

done

**Comment by LudovicoPiero** [comment]
Maybe it's also safe to remove the knownVulnerabilities(?)

cc @delroth ,I don't know how to check if it still has the [vulnerabilitie](https://github.com/NixOS/nixpkgs/issues/254798) or not.

**Comment by delroth** [comment]
It's using electron 22 which is EOL and not receiving security updates: https://endoflife.date/electron

So the `knownVulnerabilities` should stay, feel free to update it to say "Vendors Electron 22.x (EOL)" or something like that instead of pointing to a particular vulnerability.

**Comment by LudovicoPiero** [comment]
> It's using electron 22 which is EOL and not receiving security updates: [endoflife.date/electron](https://endoflife.date/electron)

Oops, I forgot that they revert the [Electron 27 update](https://github.com/Foundry376/Mailspring/commit/d69e49a4ffe51dbc46ded0fc42d9f901ef31d652).
> 
> So the `knownVulnerabilities` should stay, feel free to update it to say "Vendors Electron 22.x (EOL)" or something like that instead of pointing to a particular vulnerability.

Yeah, Let's just keep it there.

**Review by LudovicoPiero — APPROVED** [review]

**Comment by Janik-Haag** [comment]
We should backport this since it is a email client update for a client capable of rendering html malis and thus it has similar attack surfaces to a web browsers, also it is somewhat less likely to be attacked.

**Comment by Arjun31415** [comment]
I think some other PR was merged regarding mailspring. I will close this

**Pull request closed without merging**
