### PR TITLE
nixos/kea: return to merged runtime directory; preserve runtime directories

### PR DESCRIPTION
**Pull request by mweinelt**
## Description of changes

Separate runtime directories cause different problems, as seen in #265826 and an alternate solution was proposed.

@chayleaf WDYT?

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by chayleaf — APPROVED** [review]
LGTM. Not sure about the backport though, as this is (a revert of) a breaking change.

**Comment by mweinelt** [comment]
I think backporting it is fair, if it resolves the regression presumably without causing another.

**Comment by mweinelt** [comment]
The prometheus exporter test consistently fails for me.

**Comment by chayleaf** [comment]
probably since the path is `/run/kea/kea-dhcp4.socket`, not `/run/kea/dhcp4.sock`?

**Comment by mweinelt** [comment]
```
diff --git a/nixos/modules/services/monitoring/prometheus/exporters/kea.nix b/nixos/modules/services/monitoring/prometheus/exporters/kea.nix
index ed33c72f644f..d6d811e11bff 100644
--- a/nixos/modules/services/monitoring/prometheus/exporters/kea.nix
+++ b/nixos/modules/services/monitoring/prometheus/exporters/kea.nix
@@ -42,6 +42,15 @@ in {
         # Need AF_UNIX to collect data
         "AF_UNIX"
       ];
+      ReadWritePaths = [
+        "/run/kea"
+      ];
+      AmbientCapabilities = [
+        "CAP_DAC_READ_SEARCH"
+      ];
+      CapabilityBoundingSet = [
+        "CAP_DAC_READ_SEARCH"
+      ];
     };
   };
 }
```

Even when bypassing filesystem permissions the exporter gets `FileNotFoundError`.

Even though the test right before it claimed that the file now exists.

```
vm-test-run-prometheus-kea-exporter> kea: waiting for file '/run/kea/dhcp4.sock'
vm-test-run-prometheus-kea-exporter> (finished: waiting for file '/run/kea/dhcp4.sock', in 0.01 seconds)
```

And even though kea claims to listen on just that path.

```
vm-test-run-prometheus-kea-exporter> kea # [    5.980950] kea-dhcp4[930]: 2023-12-15 15:24:34.850 INFO  [kea-dhcp4.commands/930.140490168950848] COMMAND_ACCEPTOR_START Starting to accept connections via unix domain socket bound to /run/kea/dhcp4.sock
```

I'm clueless.

**Comment by DeeUnderscore** [comment]
systemd will put the runtime dir under `/run/private` and hide that behind a symlink if `RuntimeDirectoryPreserve` is anything other than `no`. I'm not sure why, but [they have a check for this](https://github.com/systemd/systemd-stable/blob/2c9e1ae02a74bd5383065885941aa272bbe0d1f8/src/core/execute.c#L283-L284). See also systemd/systemd#7260. 


Anyway, a suboptimal but working way to fix this is something like this:

```patch
diff --git a/nixos/modules/services/monitoring/prometheus/exporters/kea.nix b/nixos/modules/services/monitoring/prometheus/exporters/kea.nix
index ed33c72f644f..3abb6ff6bdf8 100644
--- a/nixos/modules/services/monitoring/prometheus/exporters/kea.nix
+++ b/nixos/modules/services/monitoring/prometheus/exporters/kea.nix
@@ -31,13 +31,15 @@ in {
     ];
     serviceConfig = {
       User = "kea";
+      DynamicUser = true;
       ExecStart = ''
         ${pkgs.prometheus-kea-exporter}/bin/kea-exporter \
           --address ${cfg.listenAddress} \
           --port ${toString cfg.port} \
           ${concatStringsSep " " cfg.controlSocketPaths}
       '';
-      SupplementaryGroups = [ "kea" ];
+      RuntimeDirectory = "kea";
+      RuntimeDirectoryPreserve = true;
       RestrictAddressFamilies = [
         # Need AF_UNIX to collect data
         "AF_UNIX"

```

This sets up all the bind mount magic to give the exporter service access to the runtime dir, but we do end up running the exporter under the same user/group.

**Comment by mweinelt** [comment]
@ofborg build kea.tests

**Pull request merged**
