### PR TITLE
Cross bootstrapping logic fixes benefitting llvmPackages

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Motivation for this change

cc @trofi

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Ericson2314 — APPROVED** [review]

**Review by trofi — COMMENTED** [review]
Fixes CXX header discovery https://github.com/NixOS/nixpkgs/issues/153759 for me, but does not fix library discovery. If I extend original example to linking it still fails. Expected?

```
$ nix build --impure --expr 'with import ./. {}; pkgsLLVM.llvmPackages.stdenv.mkDerivation { name = "d"; unpackPhase = "srcs=foo.cc; echo \"#include <cstdio>\" > $srcs"; buildPhase = "$CXX -c $srcs -o $out"; installPhase= " "; }' -L
d-x86_64-unknown-linux-gnu> unpacking sources
d-x86_64-unknown-linux-gnu> patching sources
d-x86_64-unknown-linux-gnu> configuring
d-x86_64-unknown-linux-gnu> no configure script, doing nothing
d-x86_64-unknown-linux-gnu> building
d-x86_64-unknown-linux-gnu> installing
d-x86_64-unknown-linux-gnu> post-installation fixup
d-x86_64-unknown-linux-gnu> shrinking RPATHs of ELF executables and libraries in /nix/store/ihrim8idfjyj310kkiz818nlnvqpg7gk-d-x86_64-unknown-linux-gnu
d-x86_64-unknown-linux-gnu> shrinking /nix/store/ihrim8idfjyj310kkiz818nlnvqpg7gk-d-x86_64-unknown-linux-gnu
d-x86_64-unknown-linux-gnu> patchelf: wrong ELF type
d-x86_64-unknown-linux-gnu> x86_64-unknown-linux-gnu-strip is /nix/store/ap467qy2w3hafl74z87php1ccd55ff2h-llvm-binutils-13.0.0/bin/x86_64-unknown-linux-gnu-strip
d-x86_64-unknown-linux-gnu> patching script interpreter paths in /nix/store/ihrim8idfjyj310kkiz818nlnvqpg7gk-d-x86_64-unknown-linux-gnu
d-x86_64-unknown-linux-gnu> checking for references to /build/ in /nix/store/ihrim8idfjyj310kkiz818nlnvqpg7gk-d-x86_64-unknown-linux-gnu...
d-x86_64-unknown-linux-gnu> patchelf: wrong ELF type
[nz] ~/n:nix build --impure --expr 'with import ./. {}; pkgsLLVM.llvmPackages.stdenv.mkDerivation { name = "d"; unpackPhase = "srcs=foo.cc; echo \"#include <cstdio>\nint main(){}\" > $srcs"; buildPhase = "$CXX $srcs -o $out"; installPhase= " "; }' -L
d-x86_64-unknown-linux-gnu> unpacking sources
d-x86_64-unknown-linux-gnu> patching sources
d-x86_64-unknown-linux-gnu> configuring
d-x86_64-unknown-linux-gnu> no configure script, doing nothing
d-x86_64-unknown-linux-gnu> building
d-x86_64-unknown-linux-gnu> x86_64-unknown-linux-gnu-ld: error: cannot open crtbegin.o: No such file or directory
d-x86_64-unknown-linux-gnu> x86_64-unknown-linux-gnu-ld: error: unable to find library -lgcc_s
d-x86_64-unknown-linux-gnu> x86_64-unknown-linux-gnu-ld: error: unable to find library -lgcc
d-x86_64-unknown-linux-gnu> x86_64-unknown-linux-gnu-ld: error: unable to find library -lgcc_s
d-x86_64-unknown-linux-gnu> x86_64-unknown-linux-gnu-ld: error: unable to find library -lgcc
d-x86_64-unknown-linux-gnu> x86_64-unknown-linux-gnu-ld: error: cannot open crtend.o: No such file or directory
d-x86_64-unknown-linux-gnu> clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by sternenseemann** [comment]
> but does not fix library discovery

Library discovery is not broken because `libgcc` is indeed not available :) We can switch to `clangUseLLVM` though which uses compiler-rt in this case (see  f16cfa1).

**Review by trofi — APPROVED** [review]
Current state allows me to build both small example and `pkgsLLVM.mold`. Thank you!

**Review by Ericson2314 — APPROVED** [review]

**Comment by alyssais** [comment]
Since this PR, `pkgsLLVM.llvmPackages_5` and `pkgsLLVM.llvmPackages_6` don't eval, because they don't have `clangUseLLVM`.

**Pull request merged**
