### PR TITLE
Somewhat saner cross-compiling through bootstrapping 

### PR DESCRIPTION
**Pull request by Ericson2314**
#21915 got closed by mistake due to a force push. @shlevy I wrote docs so this should be ready to go unless we want someone to review the docs.

The docs have some explicit "to be written" sections. I consider that fine, and the docs rightfully WIP, because some stuff will change with future PRs and there is little point writing it just to rewrite it.

### CODE REVIEW

**Comment by shlevy** [comment]
@Ericson2314 Besides docs has anything changed since my last review?

**Comment by Ericson2314** [comment]
@shlevy just docs and a tiny bit of comment formatting.

**Comment by Ericson2314** [comment]
Travis is backlogged, but I ran (the normal) tests locally and they pass.

**Comment by shlevy** [comment]
:LGTM:

**Pull request merged**
