### PR TITLE
wxmaxima: 21.05.2 -> 21.11.0, and more

### PR DESCRIPTION
**Pull request by doronbehar**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 7c6f434c** [comment]
This is not a no-op for Sage because of Maxima bump, right?

**Comment by doronbehar** [comment]
> This is not a no-op for Sage because of Maxima bump, right?

Correct. I finally finished compiling it, and it seems functional.

**Comment by 7c6f434c** [comment]
@timokau @collares @omasanori 

(I think this should have happened automatically…)

**Comment by doronbehar** [comment]
> @timokau @collares @omasanori
> 
> (I think this should have happened automatically…)

I think ofborg didn't requested their review because nothing has changed in the expressions really (besides the update to maxima of course), only the names of the attributes passed from one to another. You @7c6f434c were requested for a review due to the change in `ecl`.

**Comment by 7c6f434c** [comment]
Ah right

**Comment by collares** [comment]
The Sage testsuite ran successfully on x86_64-linux according to ofBorg, which should be enough testing. I wish `python3.9-debugpy-1.5.1` were not broken on aarch64-linux so we could run the testsuite there too, but this is a preexisting problem and I won't have time to look at it until next week, so I am happy with testing only on x86_64-linux.

**Review by 7c6f434c — APPROVED** [review]

**Comment by doronbehar** [comment]
Although the end result of this change doesn't mean anything, changing names of variables is still significant for maintaining the `sage` expressions. Let's wait a few more days for a reply by @timokau and/or @omasanori .

**Comment by 7c6f434c** [comment]
I do have an impression that @collares currently does the most of the work on Sage, by the way, which doesn't mean an extra glance at the changes is useless of course.

**Pull request merged**
