### PR TITLE
duktape: force link shared library against libm

### LINKED ISSUE #182427: qt6.qtdeclatative failing due to problematic linkage with duktape
### Steps To Reproduce
1. see https://hydra.nixos.org/build/184735263

### Build log
```
/build/qtdeclarative-everywhere-src-6.3.1/build/libexec/qmlcachegen: Relink `/nix/store/qlzy6szczc4glp0p18vafppsnzssz5ph-duktape-2.7.0/lib/libduktape.so.207' with `/nix/store/mhhlymrg2m70r8h94cwhv2d7a0c8l7g6-glibc-2.34-210/lib/libm.so.6' for IFUNC symbol `ceil'
```

### Additional context
The regression is directly caused by https://github.com/NixOS/nixpkgs/pull/181917, and the root cause is `duktape` the library is not properly linked, upstream issue: https://github.com/svaarala/duktape/issues/2464

### Notify maintainers

@fgaz
@ajs124
### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

### PR DESCRIPTION
**Pull request by NickCao**
###### Description of changes
fixes https://github.com/NixOS/nixpkgs/issues/182427

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fgaz** [comment]
Couldn't -lm go in LDFLAGS?

**Comment by ajs124** [comment]
We could also fetch the patch and filter out the other files. `fetchpatch` supports that, but I always forget how exactly to do that.

Either way, sorry for breaking this and thanks for fixing it.

**Review by K900 — APPROVED** [review]
Can confirm this fixes things.

**Comment by K900** [comment]
Let's get this in.

**Pull request merged**
