### PR TITLE
nautilus-open-any-terminal: fix build

### LINKED ISSUE #186167: nautilus-open-any-terminal failing to build (ValueError: Namespace Gtk not available)
### Describe the bug
The `nautilus-open-any-terminal` is failing to build

### Steps To Reproduce
```console
$ nix build github:NixOS/nixpkgs/master#nautilus-open-any-terminal
$ nix log /nix/store/x429mh7zpns5i408xfckzqqzddrhb6ci-python3.10-nautilus-open-any-terminal-0.3.0.drv
...
Traceback (most recent call last):
  File "/build/source/nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 81, in <module>
    setup(
  File "/nix/store/zfski6pdfdz1wj2xjiqrkp1m3jdyi3ly-python3.10-setuptools-63.2.0/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/nix/store/zfski6pdfdz1wj2xjiqrkp1m3jdyi3ly-python3.10-setuptools-63.2.0/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 177, in setup
    return run_commands(dist)
  File "/nix/store/zfski6pdfdz1wj2xjiqrkp1m3jdyi3ly-python3.10-setuptools-63.2.0/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
    dist.run_commands()
  File "/nix/store/zfski6pdfdz1wj2xjiqrkp1m3jdyi3ly-python3.10-setuptools-63.2.0/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/nix/store/zfski6pdfdz1wj2xjiqrkp1m3jdyi3ly-python3.10-setuptools-63.2.0/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/nix/store/zfski6pdfdz1wj2xjiqrkp1m3jdyi3ly-python3.10-setuptools-63.2.0/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/nix/store/zfski6pdfdz1wj2xjiqrkp1m3jdyi3ly-python3.10-setuptools-63.2.0/lib/python3.10/site-packages/setuptools/command/test.py", line 224, in run
    self.run_tests()
  File "/nix/store/zfski6pdfdz1wj2xjiqrkp1m3jdyi3ly-python3.10-setuptools-63.2.0/lib/python3.10/site-packages/setuptools/command/test.py", line 227, in run_tests
    test = unittest.main(
  File "/nix/store/rc9cz7z4qlgmsbwvpw2acig5g2rdws46-python3-3.10.5/lib/python3.10/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/nix/store/rc9cz7z4qlgmsbwvpw2acig5g2rdws46-python3-3.10.5/lib/python3.10/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/nix/store/rc9cz7z4qlgmsbwvpw2acig5g2rdws46-python3-3.10.5/lib/python3.10/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/nix/store/rc9cz7z4qlgmsbwvpw2acig5g2rdws46-python3-3.10.5/lib/python3.10/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/nix/store/rc9cz7z4qlgmsbwvpw2acig5g2rdws46-python3-3.10.5/lib/python3.10/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/nix/store/rc9cz7z4qlgmsbwvpw2acig5g2rdws46-python3-3.10.5/lib/python3.10/unittest/loader.py", line 405, in _find_tests
    tests, should_recurse = self._find_test_path(
  File "/nix/store/rc9cz7z4qlgmsbwvpw2acig5g2rdws46-python3-3.10.5/lib/python3.10/unittest/loader.py", line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/nix/store/zfski6pdfdz1wj2xjiqrkp1m3jdyi3ly-python3.10-setuptools-63.2.0/lib/python3.10/site-packages/setuptools/command/test.py", line 57, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/nix/store/rc9cz7z4qlgmsbwvpw2acig5g2rdws46-python3-3.10.5/lib/python3.10/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/build/source/nautilus_open_any_terminal/open_any_terminal_extension.py", line 16, in <module>
    require_version("Gtk", "3.0")
  File "/nix/store/gipin543iy3insvp27jp1f4cycjcsm1h-python3.10-pygobject-3.42.2/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```

### Expected behavior
Package should build

### Notify maintainers
@Stunkymonkey

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.10, NixOS, 22.11 (Raccoon), 22.11.20220727.2b0dd45`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.0pre20220620_16c6c6c`
 - nixpkgs: `/nix/store/p67y7q6kpk53zycri0v0qm7wvjv46mfc-source`
```

### PR DESCRIPTION
**Pull request by superherointj**
nautilus-open-any-terminal: fix build

Error logs: https://termbin.com/h436

Fixes #186167

### CODE REVIEW

**Comment by bobby285271** [comment]
See https://github.com/NixOS/nixpkgs/issues/186167#issuecomment-1221616955 Try adding gobject-introspection to nativeBuildInputs?

**Review by blitz — APPROVED** [review]
Looks like gobject-introspection is a compile-time tool. So adding it to nativeBuildInputs makes sense.

**Comment by superherointj** [comment]
@Stunkymonkey @Artturin @jtojnar

Do you approve this PR?

**Comment by Stunkymonkey** [comment]
sorry I was on vacation.

**Pull request merged**
