### PR TITLE
python310Packages.ansible-doctor: 1.4.1 -> 1.4.4

### PR DESCRIPTION
**Pull request by tjni**
###### Description of changes

I need to do this in order to update pathspec in https://github.com/NixOS/nixpkgs/pull/190845.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by tboerger — APPROVED** [review]

**Comment by onny** [comment]
Could you update ansible-doctor to 1.4.4 and maybe remove some of these patches?

**Comment by tboerger** [comment]
ansible-doctor gets dependency updates automatically via Renovate, so it's hard to always match the exact version constraints. They are changing with every release.

**Comment by onny** [comment]
Do you mind updating the package anyway? We could also consider using a general relaxPythonHook dependency to ignore all version pinnings?

**Comment by tboerger** [comment]
This is not my pr, but I could create a new one including the version update. Where can I find information about relaxPythonHook?

**Comment by tjni** [comment]
I'll try to update this at the same time. Thank you for your review.

**Comment by tjni** [comment]
@onny I updated the package and cleaned up the replacements where possible.

**Comment by onny** [comment]
Result of `nixpkgs-review pr 191581` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>ansible-doctor (python310Packages.ansible-doctor)</li>
    <li>python39Packages.ansible-doctor</li>
  </ul>
</details>

**Comment by onny** [comment]
That's great, thank you!

**Comment by tboerger** [comment]
Great, thanks for the effort :)

**Pull request merged**
