### PR TITLE
nixos/documentation: expose manualPages as a hidden option

### PR DESCRIPTION
**Pull request by ncfavier**
Allows advanced users to select what packages they want to generate the man cache for, and even more advanced users to make `manualPages` content-addressed to avoid needless rebuilds.

@rnhmjoj

### CODE REVIEW

**Comment by rnhmjoj** [comment]
How do you plan on saving rebuilds? AFAIK, the only way to avoid building the whole cache everytime `environment.systemPackages` changes would be generating per-derivation caches and combining them somehow (similarly to how it's done for fish tab completions). I don't think it's possible to combine these caches, though.

**Comment by ncfavier** [comment]
I'm only talking about avoiding rebuilds when `/share/man` hasn't changed, say when you've modified the contents of a shell script in `environment.systemPackages`.

**Comment by rnhmjoj** [comment]
> I'm only talking about avoiding rebuilds when /share/man hasn't changed, say when you've modified the contents of a shell script in environment.systemPackages.

Ok, it's not super useful, but making this configurable doesn't cost us anything.

I have mixed feelings about adding invisible options: no one will probably ever use it without documentation. Why not make it a normal option and mention your motivations in the description?

**Comment by ncfavier** [comment]
> no one will probably ever use it without documentation.

I don't know, I kind of expect users past a certain level of familiarity with the project to just check the source as a reflex. That's the target audience I had in mind, at least.

But we can make it visible. Would this do?

**Comment by rnhmjoj** [comment]
Yes, thanks. Can you squash the commits?

**Comment by rnhmjoj** [comment]
Ah, you need to update the commit message: it's not hidden anymore ;)

**Comment by ncfavier** [comment]
Good catch

**Pull request merged**
