### PR TITLE
ell: 0.38 -> 0.40, iwd: 1.12 -> 1.14, ofono: 1.31 -> 1.32

### PR DESCRIPTION
**Pull request by amaxine**
###### Motivation for this change
ell, https://git.kernel.org/pub/scm/libs/ell/ell.git/tree/ChangeLog?h=0.40
```
ver 0.40:
	Fix issue with handling failure from missing CA certificates.
	Fix issue with handling DBus.Introspectable queries.

ver 0.39:
	Add support for serialized test execution framework.
```

iwd, https://git.kernel.org/pub/scm/network/wireless/iwd.git/tree/ChangeLog?h=1.14
```
ver 1.14:
	Fix issue with scanning property and quick scan cancellation.
	Fix issue with handling authentication timeouts from SAE.
	Fix issue with handling association timeouts and retries.
	Fix issue with handling roaming frequencies after roaming.
	Fix issue with requesting neighbor report after roaming.
	Add support for handling PSK offload connections.

ver 1.13:
	Fix issue with EAPoL protocol version 2010 handling.
	Fix issue with authenticator method logic handling.
	Fix issue with getting scan results from firmware.
	Add support for handling SAE offload connections.
	Add support for roaming with FullMAC devices.
```

iwd needs to have `ell/useful.h` to build now. I've opted for symlinking it in (not sure if that's the best/most nix way to do it?), the alternative is just using release tarballs - but they do not contain the `doc` directory. I went for the option that changed the fewest things, though it feels more correct to use the release tarballs for both ell/iwd to me.

EDIT: Added a bump for ofono as it failed to build otherwise.

ofono, https://git.kernel.org/pub/scm/network/ofono/ofono.git/tree/ChangeLog?h=1.32
```
ver 1.32:
	Fix issue with handling of IMS private identity validation.
	Fix issue with handling of SIM EF structure bit processing.
	Fix issue with handling removal of Huawai modems.
	Add support for USSD indication with QMI modems.
```

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 122881` at c018ef9f run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/ca93d4c4ac642664b8e3eccd07308e0e">modem-manager-gui</a></li>
    <li><a href="https://gist.github.com/4cfc642356c1056eb008f822c0733426">ofono</a></li>
  </ul>
</details>
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>ell</li>
    <li>iwd</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by maxeaubrey** [comment]
Result of `nixpkgs-review pr 122881` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>modem-manager-gui</li>
    <li>ofono</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>ell</li>
    <li>iwd</li>
  </ul>
</details>

**Comment by maxeaubrey** [comment]
`ofono` needs a bump to 1.32 as well.

**Comment by maxeaubrey** [comment]
Result of `nixpkgs-review pr 122881` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>ell</li>
    <li>iwd</li>
    <li>modem-manager-gui</li>
    <li>ofono</li>
  </ul>
</details>

**Comment by jtojnar** [comment]
That sounds like a bug in iwd to me – according to readme:

> When using --enable-external-ell build option, it is not required that the
> Embedded Linux library source code is available in the top level directory.

I would probably go with linking the header too.

**Comment by maxeaubrey** [comment]
@jtojnar As currently done in upstream, even with `--enable-external-ell` it expects to build `ell/useful.h` (at least as far as I understand the makefile). I'll keep an eye on it when bumping in the future to see if it's fixed.

**Pull request merged**
