### PR TITLE
treewide: remove kampka as maintainer

### PR DESCRIPTION
**Pull request by kampka**
###### Motivation for this change

In my observation, it has become increasingly difficult to become meaningful code review in a timely fashion.
This leads to packages not receiving even simple version updates for month, even half a year, after a PR is filed.
To me, it feels increasingly frustrating to see my name next to a package that in all practical sense not maintained at all.

In addition, I often test packages against non-x86 architectures with non-GCC, non-glibc stdenvs, which often take a long time to build from scratch since hydra does not populate a cache for these. That makes re-testing a PR, if only for a rebase, a time consuming task. The fact committers may choose to reject your PR months later for something as mediocre as a (subjectively) misplaced whitespace just adds insult to injury.
Hence, I decided to step down as a maintainer and remove myself from the list. I'd advice to remove the packages I maintained as they will likely end up abandoned, but I leave that decision up to the remaining maintainer team.

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
> In my observation, it has become increasingly difficult to become meaningful code review in a timely fashion.

You can write me a private message on IRC if you need a review/merge.

> if only for a rebase

Rebasing a PR is not required ever except for fixing merge conflicts which is unavoidable.

**Comment by kampka** [comment]
> > In my observation, it has become increasingly difficult to become meaningful code review in a timely fashion.
> 
> You can write me a private message on IRC if you need a review/merge.

I appreciate the offer, but fishing / begging for review has been my default since I started contributing to NixOS and I honestly don't feel like ti anymore.
I know you mean well, but I think we both know that that offer will not scale or really solve anything except _maybe_ short term.

**Comment by Ekleog** [comment]
@kampka As a random question, have you tried using [the marvin bot](https://github.com/timokau/marvin-mk2), which is intended to automate the process of fishing for review? Usage can be found [here](https://github.com/timokau/marvin-mk2/blob/master/USAGE.md), for now it is still opt-in due to being still alpha software but I personally have great hopes that it can make all this less painful for the contributor, though it is still to be determined how well it works in practice.

**Comment by kampka** [comment]
@Ekleog I know about the marvin bot, but I disagree with the concept, as it is does not address any problems, it will only amplify the symptoms. There are already not enough maintainers on nixpkgs, I don't see how hogging more attention of those remaining by auto-nagging them will result in more and higher quality review. But hey, if it works, great.

**Comment by Ekleog** [comment]
Well, one of the main ideas of marvin is, that not only committers can do reviews, but really anyone who gets registered for it. Meaning that there could be review exchanges between non-committers, and then committers just have to do a quick sanity-check before landing already-reviewed PRs, which would naturally increase the number of people who do reviews, and hopefully reduce the average time to land :)

(Also, marvin also has the advantage of allowing one to easily know whether a PR is waiting for changes from the author or not — I know I personally literally never go to see old PRs, because there is a way too high rate of “PR that was already reviewed and is pending changes from the author who never answered again” — there is value in keeping those for a while, if only so that other people could pick them up, but it also means that unfortunately actually-reviewable PRs sometimes get lost there :/)

**Comment by Mic92** [comment]
@kampka can you also remove the packages that are left without maintainer?

**Pull request merged**
