### PR TITLE
zrepl: init at 0.3.1.

### PR DESCRIPTION
**Pull request by danderson**
###### Motivation for this change

I want to use zrepl :)

cc @grahamc 

/marvin opt-in
/status needs_reviewer

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by grahamc** [comment]
cc @cole-h

**Comment by cole-h** [comment]
Great minds think alike: https://github.com/NixOS/nixpkgs/pull/113090.

**Comment by danderson** [comment]
Hah! Well. @cole-h maybe let's submit this to get the package in, that way I can use it the manual way until the other PR has the nixos module figured out? I can put you in maintainers for this change also.

**Comment by cole-h** [comment]
Sounds good to me. I'll drop the package init from my PR.

**Review by cole-h — APPROVED** [review]
Diff LGTM. Thanks :)

**Comment by grahamc** [comment]
:partying_face:

**Comment by cole-h** [comment]
FYI: the module was merged and is now available in nixos-unstable-small (and soon in nixos-unstable; after it's next successful evaluation + build)!

**Pull request merged**
