### PR TITLE
python310Packages.backports_*: remove

### PR DESCRIPTION
**Pull request by natsukium**
## Description of changes

remove the following python310Packages
- backports_csv
- backports_functools_lru_cache
- backports_tempfile
- backports_unittest-mock
- backports_weakref

relates to #245383

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 245894` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>python310Packages.ritassist</li>
    <li>python310Packages.ritassist.dist</li>
    <li>python310Packages.sseclient</li>
    <li>python310Packages.sseclient.dist</li>
    <li>python311Packages.ritassist</li>
    <li>python311Packages.ritassist.dist</li>
    <li>python311Packages.sseclient</li>
    <li>python311Packages.sseclient.dist</li>
  </ul>
</details>

**Review by mweinelt — APPROVED** [review]

**Comment by bryango** [comment]
This PR breaks all python2 build. See e.g. https://github.com/NixOS/nixpkgs/issues/246631.

**Comment by zimbatm** [comment]
I think it's a sign that python2 should be removed from nixpkgs

**Comment by mweinelt** [comment]
Given that we don't build it in review, it feels like it's game over.

**Comment by bryango** [comment]
Maybe for now we should mark python2 as broken? Also, there is a new PR #246976 to re-introduce the missing dep for python2.

My build of python2 is only for the [gimp plugin ecosystem](https://github.com/NixOS/nixpkgs/tree/master/pkgs/applications/graphics/gimp/plugins), which still heavily relies on it. I am okay with dropping python2 support, but then I will have to switch to flatpak or appimage for gimp :scream:

**Comment by natsukium** [comment]
I will try not to break as much as I can notice, but I don't have the time to maintain python2.
I think you need to pin the revision of nixpkgs for gimp or make an effort to keep python2 with current users.

**Pull request merged**
