### PR TITLE
ocamlPackages.utop: fix environment variables

### PR DESCRIPTION
**Pull request by pmahoney**
###### Motivation for this change

Given a `nix-shell` with `ocamlPackages.core` on `OCAMLPATH`, `utop` is unable to load Core.Std. The error was:

    findlib: [WARNING] cannot read directory $OCAMLPATH: No such file or directory

This is because the wrapper script inserts a literal `$OCAMLPATH` into the `$OCAMLPATH` environment variable, rather than expanding the existing value.

This has not received extensive testing, but does solve my immediate problem. I'd like to get feedback from @vbgl or @FlorentBecker. Would also like to test on Linux at least, possibly NixOS.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] (utop and utop-full only) Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vbgl** [comment]
This reintroduces #24496.

**Comment by pmahoney** [comment]
@vbgl I've updated with a fix for #24496 

Tested on NixOS with OCaml 4.02 and 4.04.

**Comment by pmahoney** [comment]
@vbgl ping.  utop is completely broken for me without this patch (at least when using Core).

**Comment by 7c6f434c** [comment]
Merged, hopefully correctly…

**Pull request merged**
