### PR TITLE
Update 0ad 0.0.16 -> 0.0.17

### PR DESCRIPTION
**Pull request by waylon531**

### CODE REVIEW

**Comment by robberer** [comment]
Does not build on my machine. `make[1]: ../../../libraries/source/cxxtest-4.4/bin/cxxtestgen: Command not found` On which platform did you test this ?

**Comment by robberer** [comment]
Weird, nix-build fails while building 0AD whereas nix-shell does not. Do you use nix.useChroot = true; ?

**Comment by robberer** [comment]
OK, i got it working with `nix.useChroot = true;`

@waylon531 

could you please add `--without-tests` as a premake4 option ? I guess this also makes the `broken = true;` obsolete for this derivation.

**Comment by waylon531** [comment]
It's all working now, I was successfully able to build and run it.

**Comment by robberer** [comment]
Thanks.

**Pull request merged**
