### PR TITLE
git-credential-keepassxc: fix build on darwin

### PR DESCRIPTION
**Pull request by eliandoran**
## Things done

Changed SDK version as per #215782 .

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by RaghavSood** [comment]
Result of `nixpkgs-review pr 312508` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by RaghavSood** [comment]
Result of `nixpkgs-review pr 312508` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Comment by RaghavSood** [comment]
@GrahamcOfBorg build git-credential-keepassxc

**Review by ghost — COMMENTED** [review]
i believe that using overrideSDK is the preferred method rather than trying to pin to some version.

eg:

<details><summary>ovrdsdk.diff</summary>

```diff
diff --git a/pkgs/applications/version-management/git-credential-keepassxc/default.nix b/pkgs/applications/version-management/git-credential-keepassxc/default.nix
index 2d3e511fcbfd..b75f025d6141 100644
--- a/pkgs/applications/version-management/git-credential-keepassxc/default.nix
+++ b/pkgs/applications/version-management/git-credential-keepassxc/default.nix
@@ -10,7 +10,11 @@
 , withAll ? false
 }:

-rustPlatform.buildRustPackage rec {
+let
+  # apply the possibly modified stdenv from all-packages.nix
+  buildRustPackage = rustPlatform.buildRustPackage.override { inherit stdenv; };
+in
+buildRustPackage rec {
   pname = "git-credential-keepassxc";
   version = "0.14.0";

diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
index 1f6c9407956f..8bf0e4ee4e7e 100644
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -2335,6 +2335,10 @@ with pkgs;
   git-credential-1password = callPackage ../applications/version-management/git-credential-1password { };

   git-credential-keepassxc = callPackage ../applications/version-management/git-credential-keepassxc {
+    stdenv =
+      if stdenv.isDarwin && lib.versionOlder stdenv.hostPlatform.darwinSdkVersion "11"
+      then overrideSDK stdenv "11.0"
+      else stdenv;
     inherit (darwin.apple_sdk.frameworks) DiskArbitration Foundation;
   };

```
</details>


or

<details><summary>ovrdsdk-alt.diff</summary>

```diff
diff --git a/pkgs/applications/version-management/git-credential-keepassxc/default.nix b/pkgs/applications/version-management/git-credential-keepassxc/default.nix
index 2d3e511fcbfd..1c75d64d39a2 100644
--- a/pkgs/applications/version-management/git-credential-keepassxc/default.nix
+++ b/pkgs/applications/version-management/git-credential-keepassxc/default.nix
@@ -1,5 +1,6 @@
 { lib
 , stdenv
+, overrideSDK
 , rustPlatform
 , fetchFromGitHub
 , DiskArbitration
@@ -10,7 +11,14 @@
 , withAll ? false
 }:
 
-rustPlatform.buildRustPackage rec {
+let
+  stdenv' =
+    if stdenv.isDarwin && lib.versionOlder stdenv.hostPlatform.darwinSdkVersion "11"
+    then overrideSDK stdenv "11.0"
+    else stdenv;
+  buildRustPackage = rustPlatform.buildRustPackage.override { stdenv = stdenv'; };
+in
+buildRustPackage rec {
   pname = "git-credential-keepassxc";
   version = "0.14.0";
 
@@ -23,7 +31,7 @@ rustPlatform.buildRustPackage rec {
 
   cargoHash = "sha256-c2YucWs0UzyWDKWS5KebT3ps+XvWzlI0+ziJ8JX6oiQ=";
 
-  buildInputs = lib.optionals stdenv.isDarwin [ DiskArbitration Foundation ];
+  buildInputs = lib.optionals stdenv'.isDarwin [ DiskArbitration Foundation ];
 
   buildFeatures = []
     ++ lib.optional withNotification "notification"
```
</details>

**Comment by eliandoran** [comment]
@annaleeleaves , thank you for the feedback, I'l look into it.
@wegank , what is your opinion?

**Comment by wegank** [comment]
I still prefer `darwin.apple_sdk_11_0.callPackage` to `overrideSDK`, if possible, when it comes to Rust packages, as there's a systematic override of `rustPlatform`, but my preference will probably change one day.

https://github.com/NixOS/nixpkgs/blob/27851edc9dde0393e2275068365e6d0f5655bde4/pkgs/os-specific/darwin/apple-sdk-11.0/default.nix#L119-L128

**Comment by eliandoran** [comment]
Closing in favor of https://github.com/NixOS/nixpkgs/pull/312711.

**Comment by annaleeleaves** [comment]
hmm, i thought that the overrideSDK rewrite https://github.com/NixOS/nixpkgs/pull/287609 fixed it but from looking at the PR comment it states that rustPlatform still needs some attention.

**Pull request closed without merging**
