### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
@worldofpeace glib seems to fail

**Comment by volth** [comment]
@GrahamcOfBorg build biber

**Comment by volth** [comment]
@GrahamcOfBorg build texlive.combined.scheme-full

**Comment by worldofpeace** [comment]
> @worldofpeace glib seems to fail https://hydra.nixos.org/build/93629754

Fix for that will be moved here shortly https://github.com/NixOS/nixpkgs/pull/61598

**Comment by worldofpeace** [comment]
@FRidh For the failing things for the docs in `libpsl`; it appears that they never were installed  even before this so I guess nobody will miss disabling them :smile:

**Comment by FRidh** [comment]
@worldofpeace libicalc also fails to build now
https://hydra.nixos.org/build/93852324
We should check what is causing it because this is blocking `staging-next`.

**Comment by worldofpeace** [comment]
At a glance it failed like
```
cd /build/source/build/doc/reference/libical-glib && /nix/store/4falj4r8a92r54im5kp6zj86lwm4qxg2-gtk-doc-1.30/bin/gtkdoc-fixxref --module=libical-glib --module-dir=. --extra-dir=.. --html-dir=share/gtk-doc/html/libical-glib
Traceback (most recent call last):
  File "/nix/store/4falj4r8a92r54im5kp6zj86lwm4qxg2-gtk-doc-1.30/bin/gtkdoc-fixxref", line 57, in <module>
    fixxref.Run(options)
  File "/nix/store/4falj4r8a92r54im5kp6zj86lwm4qxg2-gtk-doc-1.30/share/gtk-doc/python/gtkdoc/fixxref.py", line 54, in Run
    highlight.append_style_defs(os.path.join(options.module_dir, 'style.css'))
  File "/nix/store/4falj4r8a92r54im5kp6zj86lwm4qxg2-gtk-doc-1.30/share/gtk-doc/python/gtkdoc/highlight.py", line 50, in append_style_defs
    os.chmod(css_file_name, 0o664)
FileNotFoundError: [Errno 2] No such file or directory: './style.css'
```

Idk looks like the stuff with the css file which should have been fixed in https://github.com/NixOS/nixpkgs/pull/61598/commits/0e2768050a7fee157556679b31773b75a935d01d. 
See https://gitlab.gnome.org/GNOME/gtk-doc/issues/84

Looks like they might have reverted what was breaking stuff on master https://gitlab.gnome.org/GNOME/gtk-doc/issues/84#note_516043

**Comment by vcunat** [comment]
Anything against reverting the gtk-doc update for now?  So far I can only see problems from it and no expected benefits.

**Comment by FRidh** [comment]
I recall just reverting the gtk-doc related changes wasn't sufficient, otherwise, definitely.

**Comment by vcunat** [comment]
Hydra:
- `x86_64-linux` seems just fine;
- `aarch64-linux` would need a couple more restarts for timed out stuff, but it does seem fine now already;
- `x86_64-darwin` &ndash; [probably too early to tell](https://hydra.nixos.org/eval/1521962?filter=x86_64-darwin&compare=1519954&full=#tabs-now-fail).  Periodically restarting aborted jobs is easy and cheap, but there are some bigger time outs (e.g. whole haskell), and also some other failures (e.g. `p11-kit` not passing some security-related checks).

**Comment by FRidh** [comment]
I intend to merge this later tonight. Darwin on Hydra is quite unreliable.

**Comment by vcunat** [comment]
@grahamc any idea why there are so many aborted jobs for darwin on Hydra? (or whom to ask)  Most of these print a message like:
> Aborted: cannot  connect to ‘root@c6279b03.packethost.net’: Warning: Permanently added  the ED25519 host key for IP address '147.75.70.201' to the list of known  hosts. root@c6279b03.packethost.net: Permission denied (publickey).

**Pull request merged**
