### PR TITLE
nixos/test-driver: add wait_before_entry

### PR DESCRIPTION
**Pull request by Synthetica9**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tfc** [comment]
Hi, do i understand correctly that this PR adds the new feature that the `with some_condition:` bracket feature now also waits *until* this condition is true for the first time and *then* watches its truth state (like before)?

**Comment by Synthetica9** [comment]
Exactly!

**Comment by tfc** [comment]
Hm... i am stumbling on this a bit:


- from just looking at the interface without the implementation, it's not really obvious (which could be fixed with enhanced documentation)
 - it's much more code and added complexity on the driver side (so more work for us to maintain) than it relieves on the user side
 - the wait and timeout semantics are harder to tune for the user than when the user uses `wait_until succeeds/fails` to explicitly wait until the wanted conditions are met.

**Comment by Synthetica9** [comment]
Maybe the same functionality but with a different, more explicit interface would be better and simpler:

```py

@polling_condition
def foo():
	...

foo.wait()
with foo:
	...
```

**Comment by tfc** [comment]
> Maybe the same functionality but with a different, more explicit interface would be better and simpler:

That looks very nice. On the implementation side: "your" polling condition *is* the old polling condition with an additional piece of functionality, so i suggest implementing this with a decorating subclass of polling_condition. i think this has great potential of not making the existing code more complicated, what do you think?

**Review by RaitoBezarius — APPROVED** [review]
LGTM, @tfc could you give it another review please?

**Comment by tfc** [comment]
@ofborg test vscodium.xorg vscodium.wayland

**Pull request merged**
