### PR TITLE
IPMIView: update src hash

### PR DESCRIPTION
**Pull request by iamdenchik**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Please format the title and commit message like ``IPMIView:: update src hash``.

**Comment by iamdenchik** [comment]
> Please format the title and commit message like `IPMIView:: update src hash`.

done

**Comment by vlaci** [comment]
Hmm, that has does not work for me either:
```
trying https://www.supermicro.com/wftp/utility/IPMIView/Linux/IPMIView_2.17.0_build.200505_bundleJRE_Linux_x64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   152  100   152    0     0    234      0 --:--:-- --:--:-- --:--:--   234
100  189k    0  189k    0     0   237k      0 --:--:-- --:--:-- --:--:--  237k
hash mismatch in fixed-output derivation '/nix/store/dcibg5lhw552197ckzh3iky61fkjxv9z-IPMIView_2.17.0_build.200505_bundleJRE_Linux_x64.tar.gz':
  wanted: sha256:1k2cjpq73j2d4vnjj7q9b38pbccjmls1qp1zy2vb1iv2yh2d76z6
  got:    sha256:1r0zmk9navx6sivgpxslghq75qpsav9llqc5ckhbrc10n5zakcph
cannot build derivation '/nix/store/q7hqvl4rczwip4f0z8chyc7gqjh7xfkv-IPMIView-2.17.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/q7hqvl4rczwip4f0z8chyc7gqjh7xfkv-IPMIView-2.17.0.drv' failed
```

**Comment by vlaci** [comment]
Looks like we need to update to 2.18 which can be downloaded from https://www.supermicro.com/wftp/utility/IPMIView/Linux/IPMIView_2.18.0_build.201007_bundleJRE_Linux_x64.tar.gz

**Comment by vlaci** [comment]
Unfortunately patchelf fails on `libiKVM_v11_64.so`:
```
patchelf --set-rpath /nix/store/7in2alrzhkpcax5fk4823ismvsmdk1aj-gcc-9.3.0-lib/lib ./libiKVM_v11_64.so
patchelf: no section headers. The input file is probably a statically linked, self-decompressing binary
```

patching is still neceserry:
```
ldd libiKVM_v11_64.so
	linux-vdso.so.1 (0x00007ffc3bdfb000)
	libstdc++.so.6 => not found
	libm.so.6 => /nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib/libm.so.6 (0x00007f243859e000)
	libgcc_s.so.1 => /nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib/libgcc_s.so.1 (0x00007f2438584000)
	libc.so.6 => /nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib/libc.so.6 (0x00007f24383c5000)
	/nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib64/ld-linux-x86-64.so.2 (0x00007f243d004000)
```

**Review by vlaci — CHANGES_REQUESTED** [review]
```diff --git a/pkgs/applications/misc/ipmiview/default.nix b/pkgs/applications/misc/ipmiview/default.nix
index 4b740a943c0..370b58709b0 100644
--- a/pkgs/applications/misc/ipmiview/default.nix
+++ b/pkgs/applications/misc/ipmiview/default.nix
@@ -13,12 +13,12 @@
 
 stdenv.mkDerivation rec {
   pname = "IPMIView";
-  version = "2.17.0";
-  buildVersion = "200505";
+  version = "2.18.0";
+  buildVersion = "201007";
 
   src = fetchurl {
     url = "https://www.supermicro.com/wftp/utility/IPMIView/Linux/IPMIView_${version}_build.${buildVersion}_bundleJRE_Linux_x64.tar.gz";
-    sha256 = "1k2cjpq73j2d4vnjj7q9b38pbccjmls1qp1zy2vb1iv2yh2d76z6";
+    sha256 = "10cv63yhh81gjxahsg4y3zp4mjivc217m4z1vcpwvvnds46c65h8";
   };
 ```

The above diff fixes the download issue for me. Unfortunately patchelf failse. May need another approach like presetting `LD_LIBRARY_PATH`

**Comment by iamdenchik** [comment]
> ```diff
> index 4b740a943c0..370b58709b0 100644
> --- a/pkgs/applications/misc/ipmiview/default.nix
> +++ b/pkgs/applications/misc/ipmiview/default.nix
> @@ -13,12 +13,12 @@
>  
>  stdenv.mkDerivation rec {
>    pname = "IPMIView";
> -  version = "2.17.0";
> -  buildVersion = "200505";
> +  version = "2.18.0";
> +  buildVersion = "201007";
>  
>    src = fetchurl {
>      url = "https://www.supermicro.com/wftp/utility/IPMIView/Linux/IPMIView_${version}_build.${buildVersion}_bundleJRE_Linux_x64.tar.gz";
> -    sha256 = "1k2cjpq73j2d4vnjj7q9b38pbccjmls1qp1zy2vb1iv2yh2d76z6";
> +    sha256 = "10cv63yhh81gjxahsg4y3zp4mjivc217m4z1vcpwvvnds46c65h8";
>    };
> ```
> 
> The above diff fixes the download issue for me. Unfortunately patchelf failse. May need another approach like presetting `LD_LIBRARY_PATH`

me close this task and open for update to the version 2.18.0 ?

**Comment by vlaci** [comment]
I am fine with either adjusting this PR or opening up a new one.

**Comment by iamdenchik** [comment]
> I am fine with either adjusting this PR or opening up a new one.

https://github.com/NixOS/nixpkgs/pull/106428

**Comment by vlaci** [comment]
Superseeded by #106428

**Pull request closed without merging**
