### PR TITLE
meson: 0.46.1 → 0.48.2

### PR DESCRIPTION
**Pull request by jtojnar**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
We patch(ed?) meson to change how it writes RPATH, which caused particularly painful (and not immediately obvious) results since apparently it works like this:

* build using dummy rpath that's "surely" long enough
* afterwards "blindly" replace dummy path with actual path, which is "known to be safe" since dummy was long enough.

It's a hack in the first place but we managed to very much break things by replacing paths of length ~30 ("dummy") with ones very much longer (> 200) which of course often resulted in invalid rpath searching but especially bad since those extra 170 chars or whatever overwrote whatever followed, which uhh hopefully wasn't important or something ;).

Bit more details here, although I was a bit battle-weary so didn't explain it very well:
https://github.com/NixOS/nixpkgs/pull/44040

As I recall, all the relevant parts of meson are the ones we already touch with our patches.  I think. :).

**Comment by dtzWill** [comment]
In particular, everything was broken: https://github.com/NixOS/nixpkgs/pull/44040#issuecomment-412645128

But it'd be good to ensure we're not generating corrupt binaries or at least be somewhat confident that's unlikely to happen....

**Comment by hedning** [comment]
We have a testing ground for meson now https://github.com/NixOS/nixpkgs/pull/45950, https://hydra.nixos.org/jobset/nixpkgs/gnome

Seems like things are working better than last time at least, I'm eg. able to run `nixos.tests.login` sucessfully. `nixos.tests.systemd` fails one of two tests, not sure if it's related though.

Doing this produces identical results, where nixpkgs.systemd is from master and ~/nixpkgs is the gnome branch with the meson update:
```
diff <(readelf -d $(nix eval nixpkgs.systemd --raw)/lib/libnss_resolve.so.2) \
     <(readelf -d $(nix eval -f ~/nixpkgs systemd --raw)/lib/libnss_resolve.so.2)
```

@dtzWill any tips on how to check if the rpath is wrong?

**Comment by jtojnar** [comment]
It looks like `./gir-fallback-path.patch` is no longer needed?

**Comment by jtojnar** [comment]
@dtzWill at https://github.com/NixOS/nixpkgs/pull/45950#issuecomment-428405545 wrote:

> NixOS's extraUtils fails with this due to reference that's not allowed-- at first I feared this was the same problem as before (since the symptom is the same as when we were corrupting things re:meson), but I think it's unrelated :). Regardless I suspect you're running into this and if you haven't you probably will (or have fixed it and I'm on wrong branch :D).
> 
> In short the fix is adding `-Dlink-udev-shared=false` to systemd's mesonFlags. I didn't chase down why it suddenly started happening, but I can say I noticed in past few months various other distributions making changes regarding this so perhaps it's due to a meson upgrade they did before us :).
> 
> The harder fix, and untested, is that the extraUtils find-libs-and-copy-and-patchelf stuff is both too complicated and in particular fails to account for transitive dependencies (libraries that need other libraries). Well "fails" may be incorrect, this is possibly a feature and some would argue a case of underlinking but all I mean is this wouldn't happen if the xz dep was pulled in and patched to be used.
> 
> I think the solution proposed (meson flags) is the best as it prevents general systemd deps (== take over the world) from being pulled into our early boot process. We may want to do the same for systemctl (similar option) but that's not necessary so I'll leave that for another time.
> 
> Anyway thanks for your work, hope this helps, LMK if you have any questions or whatnot :).

I still cannot reproduce this failure when trying to build the following expression:

```nix
{pkgs ? import <nixpkgs> {} }:
let
  config.boot.loader.supportsInitrdSecrets = false;
  config.boot.isContainer = false;
  config.boot.initrd.secrets = {};
  config.boot.initrd.extraUtilsCommands = "";
  config.boot.initrd.extraUtilsCommandsTest = "";
  config.system.build.fileSystems = [];
  config.systemd.package = pkgs.systemd;
  inherit (pkgs) lib;

  utils = import <nixpkgs/nixos/lib/utils.nix> pkgs;
  stage-1 = import <nixpkgs/nixos/modules/system/boot/stage-1.nix> { inherit pkgs lib utils config; };

in stage-1.config.content.system.build.extraUtils
```

**Comment by dtzWill** [comment]
> I still cannot reproduce this failure when trying to build the following expression:

Using that expression fails for me building against the gnome PR (where I commented) and when setting NIX_PATH appropriately, I'll try it against this PR shortly.

**Comment by worldofpeace** [comment]
Works for me.

**Comment by asymmetric** [comment]
FYI, meson is now at 0.48.1.

**Comment by lifranc** [comment]
I pulled this on recent master, and hit the extraUtils error:
```
output '/nix/store/9h118rrgi24q9206jzd42g1nblq28541-extra-utils' is not allowed to refer to the following paths:
       /nix/store/drm0a6hdflrmd3c71ams843z6hd9hs5n-xz-5.2.4
cannot build derivation '/nix/store/va7bgqr5ky0gybwngv3mf0hxcbp61awr-udev-rules.drv': 1 dependencies couldn't be built

```

**Comment by dtzWill** [comment]
On Fri, 19 Oct 2018 17:04:28 -0700, Li <notifications@github.com> wrote:
> I pulled this on recent master, and hit the extraUtils error:
> ```
> output '/nix/store/9h118rrgi24q9206jzd42g1nblq28541-extra-utils' is not allowed to refer to the following paths:
>        /nix/store/drm0a6hdflrmd3c71ams843z6hd9hs5n-xz-5.2.4
> cannot build derivation '/nix/store/va7bgqr5ky0gybwngv3mf0hxcbp61awr-udev-rules.drv': 1 dependencies couldn't be built
> 
> ```

Hmm, I wonder what causes this error for some but not others?
Maybe some configuration option? :/

Anyway, can you try to see if fixing things with the mesonFlags tweak I
suggested fixes the issue for you? It does for me O:)

**Comment by jtojnar** [comment]
The RPATH length should definitely cause no issues silently, since we [check](https://github.com/NixOS/nixpkgs/blob/80906eb858eaf6aa6ba2ea981cb30a9fa06f6bc3/pkgs/development/tools/build-managers/meson/fix-rpath.patch#L30) if the newly created RPATH is no longer than the old one.

One thing I noticed with my [debug patch](https://github.com/NixOS/nixpkgs/files/2498327/meson-debug.patch.txt) is that the old rpaths contain things like `$ORIGIN/../../../../nix/store/qf5z8hvvapnmj1i2pcl2zp0plq3c2cdh-libcap-2.25-lib/lib`. It does not affect anything, though, since nixpkgs will add the linked libraries to rpath anyway. Coincidentally, upstream has just merged a [fix](https://github.com/mesonbuild/meson/pull/4381), so I have partially backported it.

I still cannot reproduce the issue with extra-utils, but I noticed one curious thing: 

```ShellSession
$ patchelf --print-rpath $(nix-build -I nixpkgs=$PWD extrautils.nix)/lib/libacl.so.1
/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-attr-2.4.47/lib:/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-glibc-2.27/lib
```

**Comment by jtojnar** [comment]
I started consistently getting the error:

```
output '/nix/store/79kvzi8yjlryyawk8pv6snw3frndf5p2-extra-utils' is not allowed to refer to the following paths:
       /nix/store/3v5r7fkrbkw2qajadvjbf6p6qriz9p1i-gcc-7.3.0-lib
error: build of '/nix/store/yfm71c4m2b52cckw7b52g05jcp8dxdg2-extra-utils.drv' failed
```

Adding `-Dlink-udev-shared=false` to `systemd`’s `mesonFlags` does not fix this.

**Comment by jtojnar** [comment]
The solution was actually quite simple: just clear the whole old rpath before fixing it. I am still not certain why did the package get into the rpath in the first place, though.

**Comment by hedning** [comment]
I think that might cause trouble for some esoteric reason: https://github.com/mesonbuild/meson/pull/1620

Apparently Xorg in particular actually looks at stuff after `\0` or and loads it through dlopen or something like that. We're obviously not building Xorg with meson so it might be fine?

**Comment by jtojnar** [comment]
Right, I forgot about that. I would expect `rodata` sharing to be used more widely than in Xorg; will need to do more research about when it is triggered.

Weirdly, now the rest of the `old_rpath` seems to be filled with `X`s even when I just replace it as before (no clearing). [Debug print](https://github.com/NixOS/nixpkgs/files/2498327/meson-debug.patch.txt) confirms that there is not that many `X`s in either `old_path` or `new_rpath`.

**Comment by zimbatm** [comment]
coming here from trying to update waycooler, which depends on wlroots 0.1 which depends on a newer version of meson.

by the way, meson 0.48.1 has been released 5 days ago

**Comment by zimbatm** [comment]
coming here from trying to update waycooler, which depends on wlroots 0.1 which depends on a newer version of meson.

by the way, meson 0.48.1 has been released 5 days ago

**Comment by jtojnar** [comment]
@zimbatm We have already updated to meson 0.48.1.

**Comment by hedning** [comment]
I'm getting the `gcc` issue on this branch consistently now. I'm quite certain I found the reference in `bin/systemd-udevd` once (which weirdly enough didn't seem to be part of the RPATH, but rather following, according to `readelf --string-dump=.dynstr` output). I'm also pretty certain that the reference in `systemd-udevd` isn't in the systemd derivation, but rather appears after being copied and processed to `extra-utils`.

I'm now seeing the reference in `libudev.so.1`, which is there in the `systemd` derivation too, so the above might be irrelevant.

Anyway, I can't quite understand how the padding works, as the `old_rpath` tend to look like this:
>'$ORIGIN/:$ORIGIN/../shared:/nix/store/qf5z8hvvapnmj1i2pcl2zp0plq3c2cdh-libcap-2.25-lib/lib:...:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:/nix/store/73s0qx4fjf3bxns6byappvvyr7s9q8a2-systemd-239-lib/lib64:/nix/store/3v5r7fkrbkw2qajadvjbf6p6qriz9p1i-gcc-7.3.0-lib/lib'

Why is the padding sandwiched between actual paths? [`build_unix_rpath_args`](https://github.com/mesonbuild/meson/blob/0.48.1/mesonbuild/compilers/compilers.py#L1105) puts the padding on the end. So something else adds a bunch of extra stuff to the RPATH?

For reference, a typical case with meson-0.46 is something like this, so very little at the start of the RPATH (both cases come from building `systemd`). Not sure what's changed here, but it looks like systemd on unstable gets a lot fewer RPATH entries at the start, so the new_rpath was probably long enough to kill any full hashes avoiding the issue. 

> b'$ORIGIN/src/shared
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
/nix/store/zb6fdd56ljzv8c6jdsbs79iwvxpslw70-systemd-239-lib/lib64
/nix/store/zb6fdd56ljzv8c6jdsbs79iwvxpslw70-systemd-239-lib/lib
/nix/store/hhsyfa5l26ys7m5c1j4fjsr3l323g83w-glibc-2.27/lib
/nix/store/ba45raq8b5yki9jghdlrmizhnvxgwc44-gcc-7.3.0-lib/lib'

**Comment by zimbatm** [comment]
coming here from trying to update waycooler, which depends on wlroots 0.1 which depends on a newer version of meson.

by the way, meson 0.48.1 has been released 5 days ago

**Comment by jtojnar** [comment]
I think the paths after placeholder come from nixpkgs, ld-wrapper in particular, IIRC

**Comment by hedning** [comment]
Okay, so it's the interaction between `ld-wrapper` and meson that's the main problem? (and for some reason strip doesn't fix it up).

The stuff that's added by `ld-wrapper` will never be used as meson writes `new_rpath`  and terminates it with `\0` making anything beyond irrelevant apart from things like nixpkgs reference «counting» or `rodata`.

As such would it make sense to make `ld-wrapper` not add those extras when using meson? I might misunderstand something here, but it seems like it simply adds something that never will be used, but can cause effectively random references to the nix store.

**Comment by jtojnar** [comment]
The stuff added by `ld-wrapper` is part of `old_rpath`, therefore it will remain in the `new_rpath`:

https://github.com/NixOS/nixpkgs/blob/01fcaf8d29b74fe163d34328b15edbbb828577d6/pkgs/development/tools/build-managers/meson/fix-rpath.patch#L28

The issue occurs even when we remove `fix-rpath.patch` – vanilla meson uses `install_rpath` kwarg as the value of `new_rpath`, which will often be short or empty string, preserving the references to paths added to `ld-wrapper`.

> As such would it make sense to make `ld-wrapper` not add those extras when using meson?

Yes, that sounds sensible to me. Though adding `NIX_DONT_SET_RPATH = true;` only breaks the build.

> I might misunderstand something here, but it seems like it simply adds something that never will be used, but can cause effectively random references to the nix store.

Yes, I do not understand this either. I thought the builder knows not to include gcc into the closure. Though I am not sure how it discerns it, will need to re-read the relevant section of nix-pills.

**Comment by dtzWill** [comment]
On Mon, 22 Oct 2018 09:53:33 -0700, Jan Tojnar <notifications@github.com> wrote:
> The stuff added by `ld-wrapper` is part of `old_rpath`, therefore it will remain in the `new_rpath`:
> 
> https://github.com/NixOS/nixpkgs/blob/01fcaf8d29b74fe163d34328b15edbbb828577d6/pkgs/development/tools/build-managers/meson/fix-rpath.patch#L28
> 
> The issue occurs even when we remove `fix-rpath.patch` – vanilla meson uses `install_rpath` kwarg as the value of `new_rpath`, which will often be short or empty string, preserving the references to paths added to `ld-wrapper`.
> 
> > As such would it make sense to make `ld-wrapper` not add those extras when using meson?
> 
> Yes, that sounds sensible to me. Though adding `NIX_DONT_SET_RPATH = true;` only breaks the build.
> 
> > I might misunderstand something here, but it seems like it simply adds something that never will be used, but can cause effectively random references to the nix store.
> 
> Yes, I do not understand this either. I thought the builder knows not to include gcc into the closure. Though I am not sure how it discerns it, will need to re-read the relevant section of nix-pills.

Oh no, not rpath troubles again! :3

FWIW found this from upstream that looks relevant:

https://github.com/mesonbuild/meson/commit/4d7de6c1225ff7645be845c293769e3cf361b513

(upstream PR4381).

Which seems to address the portion of the rpath handling that appeared
problematic to me last time I looked into this, I think O:).

**Comment by jtojnar** [comment]
> Oh no, not rpath troubles again! :3

I would say that in this case the issues do not originate from meson but our own `ld-wrapper` – for some reason, nixpkgs push gcc into rpath.

> FWIW found this from upstream that looks relevant: [mesonbuild/meson@4d7de6c](https://github.com/mesonbuild/meson/commit/4d7de6c1225ff7645be845c293769e3cf361b513) (upstream PR4381). Which seems to address the portion of the rpath handling that appeared problematic to me last time I looked into this, I think O:).

Yes, it is equivalent to this portion of https://github.com/NixOS/nixpkgs/blob/ef356158e070139602922b5a8ebd5ac1420db50e/pkgs/development/tools/build-managers/meson/fix-rpath.patch#L7-L8, that I introduced as a fix for the store-path relativization as mentioned in https://github.com/NixOS/nixpkgs/pull/46020#issuecomment-431617225

**Comment by dtzWill** [comment]
On Mon, 22 Oct 2018 19:08:28 +0000 (UTC), Jan Tojnar <notifications@github.com> wrote:
> > Oh no, not rpath troubles again! :3
> 
> I would say that in this case the issues do not originate from meson but our own `ld-wrapper` – for some reason, nixpkgs push gcc into rpath.

Well regardless thanks for tackling this!

> 
> > FWIW found this from upstream that looks relevant: [mesonbuild/meson@4d7de6c](https://github.com/mesonbuild/meson/commit/4d7de6c1225ff7645be845c293769e3cf361b513) (upstream PR4381). Which seems to address the portion of the rpath handling that appeared problematic to me last time I looked into this, I think O:).
> 
> Yes, it is equivalent to this portion of https://github.com/NixOS/nixpkgs/blob/ef356158e070139602922b5a8ebd5ac1420db50e/pkgs/development/tools/build-managers/meson/fix-rpath.patch#L7-L8, that I introduced as a fix for the store-path relativization as mentioned in https://github.com/NixOS/nixpkgs/pull/46020#issuecomment-431617225

Ha! Well, my apologies for not noticing.  I'm laughing though because I
*did* make sure that you weren't the PR author before linking it :D.

Sorry for the noise, carry on :3.

**Comment by hedning** [comment]
So I'm seeing two ways to deal with this (as not adding stuff with `ld-wrapper` doesn't work, I missed the `split` -> `join` logic there):

1. Fixing the strip logic so that any reference to eg. `gcc` gets cleaned out properly. For instance are we only getting the problem when we have something like this `ix/store/hash-gcc-*`, while `/nix/store/hash-gcc-*` gets taken care of correctly? If so that might be fixable.

2. Null out the end of the RPATH that `ld-wrapper` adds, after meson copies it to the start. In that case we would need to somehow know the length of the stuff `ld-wrapper` adds.

**Comment by jtojnar** [comment]
This might help with the rpath issue: https://github.com/NixOS/nixpkgs/pull/49417

**Comment by timokau** [comment]
I wish I would've spent some time searching the open PR's *before* trying to do the update myself.

Anyways the python3.6 -> python3.7 upgrade causes some problems with meson 0.46.1 that seem to be fixed with 0.48.1 (see https://github.com/NixOS/nixpkgs/pull/49446#issuecomment-434269967).

**Comment by hedning** [comment]
Nice, that looks promising and should hopefully get us out of the immediate problem. Would it be worth it to spin up the gnome job with #49417 ?

Now for the remaining issue (lingering references to things actually in `buildInputs`). Here's an idea: Only  overwrite the paths starting with `/nix/store` that we copy to `new_rpath`. Eg. something like this:
```diff python
modified   mesonbuild/scripts/depfixer.py
@@ -303,6 +303,16 @@ class Elf(DataSizes):
             return
         self.bf.seek(rp_off)
         old_rpath = self.read_str()
+
+        if new_rpath:
+            new_rpath += b':'
+        else:
+            new_rpath = b''
+
+        paths = old_rpath.split(b':')
+        new_rpath += b':'.join(filter(lambda path: path.startswith(b'@storeDir@'), paths))
+        clean_old_rpath = b':'.join(map(lambda path: b'X'*len(path) if path.startswith(b'@storeDir@') else path, paths))
+
         if len(old_rpath) < len(new_rpath):
             sys.exit("New rpath must not be longer than the old one.")
         # The linker does read-only string deduplication. If there is a
@@ -316,6 +326,9 @@ class Elf(DataSizes):
         if not new_rpath:
             self.remove_rpath_entry(entrynum)
         else:
+            self.bf.seek(rp_off)
+            self.bf.write(clean_old_rpath)
+
             self.bf.seek(rp_off)
             self.bf.write(new_rpath)
             self.bf.write(b'\0')
```

Not entirely sure if that would be 100% safe, though if not I'm a bit perplexed about what a general solution would look like. To be on the safe side I guess we could check that the path also ends with `/lib` or something.

**Comment by jtojnar** [comment]
#49417 would not be enough by itself, I think; we would also need to set `strictDeps = true` everywhere.

The patch should help if the hypothesis that trimmed store paths are not cleared is correct. I am not sure that is the case, since the problematic path is in the output in full in https://github.com/NixOS/nixpkgs/pull/46020#issuecomment-431619314.

**Comment by pbogdan** [comment]
From when I was looking at the `extraUtils` issue when I was trying to build it on the gnome3 update branch:

```
output '/nix/store/kdvj619qkggcs7wsxk1rxc5xwpaiarpg-extra-utils' is not allowed to refer to the following paths:                                                                                                    
       /nix/store/drm0a6hdflrmd3c71ams843z6hd9hs5n-xz-5.2.4
$ grep -Ri /nix/store/drm0a6hdflrmd3c71ams843z6hd9hs5n-xz-5.2.4 /nix/store/kdvj619qkggcs7wsxk1rxc5xwpaiarpg-extra-utils/
# no matches, what gives?
$ grep -Ri drm0a6hdflrmd3c71ams843z6hd9hs5n-xz-5.2.4 /nix/store/kdvj619qkggcs7wsxk1rxc5xwpaiarpg-extra-utils/
Binary file /nix/store/kdvj619qkggcs7wsxk1rxc5xwpaiarpg-extra-utils/bin/scsi_id matches
Binary file /nix/store/kdvj619qkggcs7wsxk1rxc5xwpaiarpg-extra-utils/bin/cdrom_id matches
Binary file /nix/store/kdvj619qkggcs7wsxk1rxc5xwpaiarpg-extra-utils/bin/v4l_id matches
Binary file /nix/store/kdvj619qkggcs7wsxk1rxc5xwpaiarpg-extra-utils/bin/ata_id matches
Binary file /nix/store/kdvj619qkggcs7wsxk1rxc5xwpaiarpg-extra-utils/sbin/scsi_id matches
Binary file /nix/store/kdvj619qkggcs7wsxk1rxc5xwpaiarpg-extra-utils/sbin/cdrom_id matches
Binary file /nix/store/kdvj619qkggcs7wsxk1rxc5xwpaiarpg-extra-utils/sbin/v4l_id matches
Binary file /nix/store/kdvj619qkggcs7wsxk1rxc5xwpaiarpg-extra-utils/sbin/ata_id matches
$ readelf --string-dump .dynstr /nix/store/kdvj619qkggcs7wsxk1rxc5xwpaiarpg-extra-utils/sbin/scsi_id | grep drm0a6hdflrmd3c71ams843z6hd9hs5n-xz-5.2.4
  [   4a8]  e/drm0a6hdflrmd3c71ams843z6hd9hs5n-xz-5.2.4/lib:$ORIGIN/../../../../../nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-lz4-1.8.3/lib:$ORIGIN/../../../../../nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-util-linux-2.32.1/lib:/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-systemd-239-lib/lib64:/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-systemd-239-lib/lib:/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-glibc-2.27/lib:/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-gcc-7.3.0-lib/lib
```

So apparently a binary containing a reference to  `e/drm0a6hdflrmd3c71ams843z6hd9hs5n-xz-5.2.4/lib` is considered as referring to, presumably `/nix/store/drm0a6hdflrmd3c71ams843z6hd9hs5n-xz-5.2.4`? Why? `e/drm0a6hdflrmd3c71ams843z6hd9hs5n-xz-5.2.4/lib` is clearly not a valid store path...

It seems `nuke-refs` - which is used in `extraUtils` - scans for `store-dir/hash-regex` and replaces it with `store-dir/dummy-hash` which seems reasonable (scanning for just hash-regex in binaries and replacing that.. could be problematic? haha). So it can't catch the truncated hash as shown above.

On the Nix side - which as far as I can tell is what scans for the references - the scanner only looks for the hash part of the paths of the derivation's inputs. I don't really grok C++ but as far as I can tell it does something like this?:

```
for input in inputs:
   hash = store_path_hash_of_input(hash)
   if grep_output hash then
     echo "found reference"
     die
  fi
```

dtzWill might perhaps know better how the reference scanning works in Nix?

Leaving that aside... I'm not too familiar with how this works but could the depfixer.py a) first grab the old rpath b) do what `nuke-refs` does` c) rewrite the rpath with the one from b) and finally d) write the new one?

**Comment by timokau** [comment]
If I remember correctly from the original nix paper, it only checks for the hash part because the path may be stored in some unpredictable way (e.g. an array with path components `["nix", "store", "hash"]`) and the store hashes should be unique enough.

**Comment by hedning** [comment]
The minimal fix for the `nuke-refs` issue could be to simply preemptively nuke any nix store reference that would be cut in half by meson's RPATH rewrite. I would think it's safe to assume that cutting a RPATH entry in half will make it unusable for any purpose, so nuking it fully shouldn't break anything that's not already broken, making it possible to get this out of the door?

So something like this in `fix_rpathtype_entry`:

```python
        cut = len(new_rpath)
        if cut < len(old_rpath) and old_rpath[cut] != b':':
            start = old_rpath.rfind(b':', 0, cut) + 1
            to = old_rpath.find(b':', start)
            to = len(old_rpath) if to == -1 else to
            cut_ref = old_rpath[start:to]
            if cut_ref.startswith(b'@storeDir@'):
                old_rpath = old_rpath[0:start] + b'X'*len(cut_ref) + old_rpath[to:]
```

Building systemd using this meson patch seems to fix the current issue at least (test branch with some print debugging: https://github.com/hedning/nixpkgs/commits/meson-rpath)

**Comment by hedning** [comment]
Yeah, you're probably right. We're most likely already violating the assumptions made by meson when we're moving the stuff added by `ld-wrapper` to the start. So I don't really have any problems with going with the current solution. Just saw that you've already pushed the fix to the the gnome branch :+1:

**Comment by jtojnar** [comment]
I cannot reproduce the issue at the moment.

**Comment by jtojnar** [comment]
Based on https://github.com/NixOS/nixpkgs/pull/45950#issuecomment-437651775, our `gir-fallback-path.patch` is apparently still needed. The old patch is not really trivially portable, since our [`--fallback-library-path` hack](https://github.com/NixOS/nixpkgs/blob/e2bae133a70fe5a8978a71016c2118a49c9f540d/pkgs/development/libraries/gobject-introspection/absolute_shlib_path.patch) does not expect multiple libraries that are [now supported](https://github.com/mesonbuild/meson/pull/4000).

**Comment by jtojnar** [comment]
Re-added the patch.

**Comment by coreyoconnor** [comment]
FYI: I also ran into the `is not allowed to refer to` error previously. I'm unable to reproduce the issue with the latest commits.

**Comment by hedning** [comment]
(answer from irc) @jtojnar ah, sorry for the confusion, I should've made it clear that I was talking about the branch without the clear old_rpath fix. I was working under the assumption that the fix wasn't safe, but when reading https://github.com/NixOS/nixpkgs/pull/46020#issuecomment-431837249 again I can see I didn't make specify that at all :(

**Comment by jtojnar** [comment]
Let's merge this and see what happens.

**Pull request merged**
