### PR TITLE
lib/types: addCheckDesc: init

### PR DESCRIPTION
**Pull request by cole-h**
It's used in only a couple places, but being able to communicate what
check was violated will help with cryptic error messages like:

    error: A definition for option `programs._1password-gui.gid' is not of type `signed integer'. Definition values:
           - In `/home/vin/workspace/vcs/nixpkgs/master/test.nix': 998

Instead, add the ability to append a nice description of the check:

    error: A definition for option `programs._1password-gui.gid' is not of type `signed integer (with check: greater than or equal to 1000)'. Definition values:
           - In `/home/vin/workspace/vcs/nixpkgs/master/test.nix': 998

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by infinisil — COMMENTED** [review]
Looking good to me! Could use some docs though. Could probably replace the one use of `addCheck` in the docs with `addCheckDesc`

**Comment by cole-h** [comment]
I added a comment above the declaration and replaced the manual's usage of `addCheck` with `addCheckDesc`. Is there anywhere else I should put some docs?

**Review by infinisil — APPROVED** [review]

**Comment by cole-h** [comment]
Ha ha :P

I'd prefer to keep the canonical type description but have an addendum so that it's easier to search for in e.g. the generated `configuration.nix.5` manpage. Not a terribly strong reason, but...

I wouldn't be opposed to also adding an `addCheckWith` as you've described and implementing `addCheckDesc` (would `addCheckDescription` make you happier?) in terms of that, but it's difficult to communicate that the description is that of the attached check, and not of the type itself, otherwise -- i.e., I'd expect `addCheckWith { description = "lol"; }` to _set_ the `description`, but I want `addCheckDesc "lol"` to _augment_ the `description`.

**Comment by RaitoBezarius** [comment]
Is there something I can do to help this getting merged?

**Comment by cole-h** [comment]
I think I was waiting on a response from roberth on the approach, since they had some reservations, but there's nothing _wrong_ with this as-is, IMHO.

**Comment by roberth** [comment]
The example is still an awful error message. Why would you want this?

    signed integer (with check: greater than or equal to 1000)

... if you could have

    integer of at least 1000

This way, you avoid
1. any references to the bit-wise representation of integers
2. the implementation detail that an extra check is performed
3. a conjunction (or)

I guess (1) and (3) could be fixed elsewhere, but (2) is introduced by this PR.

If the goal was to make type descriptions nicer, this is not the right solution.

**Pull request closed without merging**
