### PR TITLE
nixos: move matrix services into their category

### PR DESCRIPTION
**Pull request by McSinyx**
###### Description of changes

This better organize Matrix-related services.  IMHO the matrix- prefix should be drop from the names, but I'm not sure if the backward incompatibility is worth it.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by piegamesde** [comment]
How would removing the matrix- prefix additionally break things? If somebody relies on the module path, this is already a breaking change.

**Comment by McSinyx** [comment]
It would be a breaking change if the option name is to be shortened,
which should be desired since e.g. services.matrix-synapse is redundant
as there is only one synapse service; the same for conduit.

**Comment by piegamesde** [comment]
No. Those names should not be touched, and are not redundant. Conduit for example explicitly requested to be packaged as matrix-conduit, and the module name should match the pname if possible.

What is redundant though is the new module file path: `./services/matrix/matrix-conduit.nix`. I think this could safely be shortened to `./services/matrix/conduit.nix` (same for the others)

**Comment by ajs124** [comment]
You could do something like `services.matrix.(synapse|conduit)`, but we don't really do that for anything else, like http, smtp, sql, etc. And that could be done in a backwards-compatible manner with `mkRenamedOptionModule`.

**Comment by piegamesde** [comment]
Based on the experience with `services.xserver`, I don't think that would be a good idea either.

**Comment by McSinyx** [comment]
> What is redundant though is the new module file path: `./services/matrix/matrix-conduit.nix`. I think this could safely be shortened to `./services/matrix/conduit.nix` (same for the others)

That sounds good, I've updated the patch.

**Review by sumnerevans — APPROVED** [review]

**Comment by McSinyx** [comment]
Gentle ping!

**Review by piegamesde — APPROVED** [review]

**Comment by McSinyx** [comment]
Gentle ping!

**Pull request merged**
