### PR TITLE
nixos/firewall: handle conntrack helper autodetection being removed in 6.0

### PR DESCRIPTION
**Pull request by K900**
###### Description of changes

Upstream change: https://lore.kernel.org/all/20220830153319.71890-1-pablo@netfilter.org/

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
I'd say the assertion is worth backporting to 22.11, too.

**Comment by vcunat** [comment]
Also https://github.com/NixOS/nixpkgs/pull/219457

**Comment by SuperSandro2000** [comment]
How do I migrate away from this setting? Need to have access to the sysctl setting ``net.netfilter.nf_conntrack_max`` at boot to increase it. When not auto loading the conntrack helpers, the setting does not exist.

**Comment by vcunat** [comment]
I don't know this stuff, but I still have `/proc/sys/net/netfilter/nf_conntrack_max` on default-ish 6.1 kernel.

**Comment by SuperSandro2000** [comment]
That path was in the past not available on boot when the sysctl settings are applied and I needed to load the conntrack module early on.

**Pull request merged**
