### PR TITLE
nvidia-vaapi-driver: 0.0.8 -> 0.0.9

### PR DESCRIPTION
**Pull request by NickCao**
Changes: https://github.com/elFarto/nvidia-vaapi-driver/compare/v0.0.8...v0.0.9

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabianhjr** [comment]
On `staging-next` + `gnome`:

```
[15/16] Compiling C object nvidia_drv_video.so.p/src_vabackend.c.o
FAILED: nvidia_drv_video.so.p/src_vabackend.c.o 
gcc -Invidia_drv_video.so.p -I. -I.. -I../nvidia-include -I/nix/store/jva80ywpsdi9377n4gg0w1z1i9j7f78p-nv-codec-headers-11.1.5.2/include -I/nix/store/5n1hx0bc7djfvgbri3igrw2cgfxvp8zc-libva-2.17.0-dev/include -I/nix/store/97w0qch13m2zg5hivqrjjj3lcfpcngx1-libdrm-2.4.115-dev/include -I/nix/store/97w0qch13m2zg5hivqrjjj3lcfpcngx1-libdrm-2.4.115-dev/include/libdrm -I/nix/store/0pkm5f5cx59v1y9fgkjgqyk112niz3yk-gstreamer-1.20.3-dev/include/gstreamer-1.0 -I/nix/store/7d1jqhvwpnr13fv8364l2b8cgrxcsn6f-glib-2.76.1-dev/include -I/nix/store/7d1jqhvwpnr13fv8364l2b8cgrxcsn6f-glib-2.76.1-dev/include/glib-2.0 -I/nix/store/3ddnxizrk3j7m6l64bwiw0hgl4n5iq96-glib-2.76.1/lib/glib-2.0/include -I/nix/store/ajyck9f1a2624sc17w77hilabnwga15b-gst-plugins-bad-1.20.3-dev/include/gstreamer-1.0 -fvisibility=hidden -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c11 -Wno-missing-field-initializers -Wno-unused-parameter -Werror=format -Werror=format-security -Werror=incompatible-pointer-types -Werror=init-self -Werror=int-conversion -Werror=missing-declarations -Werror=missing-prototypes -Werror=pointer-arith -Werror=undef -Werror=vla -Wsuggest-attribute=format -Wwrite-strings -fPIC -pthread -MD -MQ nvidia_drv_video.so.p/src_vabackend.c.o -MF nvidia_drv_video.so.p/src_vabackend.c.o.d -o nvidia_drv_video.so.p/src_vabackend.c.o -c ../src/vabackend.c
In file included from ../src/vabackend.c:3:
../src/vabackend.c: In function 'resolveSurfaces':
../src/vabackend.c:418:13: error: format '%llX' expects argument of type 'long long unsigned int', but argument 6 has type 'CUdeviceptr' {aka 'unsigned int'} [-Werror=format=]
  418 |         LOG("Mapped surface %d to %llX (%d)", surface->pictureIdx, deviceMemory, pitch);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                       ~~~~~~~~~~~~
      |                                                                    |
      |                                                                    CUdeviceptr {aka unsigned int}
../src/vabackend.h:242:55: note: in definition of macro 'LOG'
  242 | #define LOG(...) logger(__FILE__, __func__, __LINE__, __VA_ARGS__);
      |                                                       ^~~~~~~~~~~
../src/vabackend.c:418:38: note: format string is defined here
  418 |         LOG("Mapped surface %d to %llX (%d)", surface->pictureIdx, deviceMemory, pitch);
      |                                   ~~~^
      |                                      |
      |                                      long long unsigned int
      |                                   %X
../src/vabackend.c: In function 'nvExportSurfaceHandle':
../src/vabackend.c:2065:9: error: format '%lx' expects argument of type 'long unsigned int', but argument 9 has type 'uint64_t' {aka 'long long unsigned int'} [-Werror=format=]
 2065 |     LOG("Exporting with %d %d %d %d %lx %d %d %lx", ptr->width, ptr->height, ptr->layers[0].offset[0], ptr->layers[0].pitch[0], ptr->objects[0].drm_format_modifier, ptr->layers[1].offset[0], ptr->layers[1].pitch[0], ptr->objects[1].drm_format_modifier);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                                |
      |                                                                                                                                                uint64_t {aka long long unsigned int}
../src/vabackend.h:242:55: note: in definition of macro 'LOG'
  242 | #define LOG(...) logger(__FILE__, __func__, __LINE__, __VA_ARGS__);
      |                                                       ^~~~~~~~~~~
../src/vabackend.c:2065:39: note: format string is defined here
 2065 |     LOG("Exporting with %d %d %d %d %lx %d %d %lx", ptr->width, ptr->height, ptr->layers[0].offset[0], ptr->layers[0].pitch[0], ptr->objects[0].drm_format_modifier, ptr->layers[1].offset[0], ptr->layers[1].pitch[0], ptr->objects[1].drm_format_modifier);
      |                                     ~~^
      |                                       |
      |                                       long unsigned int
      |                                     %llx
../src/vabackend.c:2065:9: error: format '%lx' expects argument of type 'long unsigned int', but argument 12 has type 'uint64_t' {aka 'long long unsigned int'} [-Werror=format=]
 2065 |     LOG("Exporting with %d %d %d %d %lx %d %d %lx", ptr->width, ptr->height, ptr->layers[0].offset[0], ptr->layers[0].pitch[0], ptr->objects[0].drm_format_modifier, ptr->layers[1].offset[0], ptr->layers[1].pitch[0], ptr->objects[1].drm_format_modifier);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                                                                                                                        |
      |                                                                                                                                                                                                                                        uint64_t {aka long long unsigned int}
../src/vabackend.h:242:55: note: in definition of macro 'LOG'
  242 | #define LOG(...) logger(__FILE__, __func__, __LINE__, __VA_ARGS__);
      |                                                       ^~~~~~~~~~~
../src/vabackend.c:2065:49: note: format string is defined here
 2065 |     LOG("Exporting with %d %d %d %d %lx %d %d %lx", ptr->width, ptr->height, ptr->layers[0].offset[0], ptr->layers[0].pitch[0], ptr->objects[0].drm_format_modifier, ptr->layers[1].offset[0], ptr->layers[1].pitch[0], ptr->objects[1].drm_format_modifier);
      |                                               ~~^
      |                                                 |
      |                                                 long unsigned int
      |                                               %llx
cc1: some warnings being treated as errors
ninja: build stopped: subcommand failed.
```

Workaround on my local checkout: Reverting fixes the build, probably adding a `-Wno-error` would too.

**Comment by NickCao** [comment]
Looks like https://github.com/elFarto/nvidia-vaapi-driver/issues/188, lets see if the upstream patch fixes it.

**Comment by SharzyL** [comment]
Any fix planed? Using latest nvidia-vaapi-driver source seems to work.

**Comment by fabianhjr** [comment]
Already on the main branch upstream so probably on next release.

Another workaround is adding `-Wno-error`

```
diff --git a/pkgs/development/libraries/nvidia-vaapi-driver/default.nix b/pkgs/development/libraries/nvidia-vaapi-driver/default.nix
index 752c19fb2cf..60951a723f4 100644
--- a/pkgs/development/libraries/nvidia-vaapi-driver/default.nix
+++ b/pkgs/development/libraries/nvidia-vaapi-driver/default.nix
@@ -39,6 +39,11 @@ stdenv.mkDerivation rec {
     libva
   ];
 
+  NIX_CFLAGS_COMPILE = [
+    "-Wno-error=format="
+    "-Wno-error=int-conversion"
+  ];
+
   postFixup = ''
     addOpenGLRunpath "$out/lib/dri/nvidia_drv_video.so"
   '';
```

Will open a merge request.

**Pull request merged**
