### PR TITLE
arora: Remove

### PR DESCRIPTION
**Pull request by doronbehar**
It's last release was 10 years ago, and it won't build since a long time now, due to webkit unfound for qt4.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by doronbehar** [comment]
cc @NixOS/nixos-release-managers

**Comment by doronbehar** [comment]
A 2nd commit fixes editor-config trailing space ci error.

**Comment by zowoq** [comment]
@doronbehar I cherrypicked the second commit to master: https://github.com/NixOS/nixpkgs/commit/09d00b5b98be0ffaf53d887ed44ee7414be70839

**Review by jonringer — APPROVED** [review]
diff LGTM

cc @Phreedom

**Comment by doronbehar** [comment]
Pushed a `arora: Remove` only commit.

**Pull request merged**
