### PR TITLE
regreet - use lib.mkDefault for GTK theme options

### PR DESCRIPTION
**Pull request by hyperparabolic**
These were added in ab65220a1af24cc46a67021e624fce3f4c87ebfa and 5ee778d42408dac493338b2e5e761443c88d5ae7. Nice to have an explicit config, but it breaks configs that already set a TOML config via programs.regreet.settings.GTK directly due to new defaults without setting a priority.

## Description of changes

No functional changes, just adding `lib.mkDefault` so that this new config doesn't conflict with configs that already set `programs.regreet.settings.GTK` directly, avoiding a breaking change.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by hyperparabolic** [comment]
@Enzime Hi, this is adding on to your last commits, and it looks like you're a member of the nixpkgs org, is there any chance you could review this? If not, do you know who should?

**Review by Enzime — COMMENTED** [review]
I think users should switch to using the new `programs.regreet.{cursorTheme,font,iconTheme,theme}.*` options instead of adding `mkDefault` here.

I think that we shouldn't add `mkDefault` on these options as users should be explicit that they don't want to use these options.

**Comment by hyperparabolic** [comment]
I think that what you did is a great improvement. It avoids having to check the regreet documentation, and I really appreciate that.

It's also a breaking change to at least  [~100 pre-existing public nix configs](https://github.com/search?q=regreet+%22GTK+%3D+%7B%22&type=code&p=5) when backwards compatibility can be easily offered.

**Comment by SuperSandro2000** [comment]
> I think users should switch to using the new `programs.regreet.{cursorTheme,font,iconTheme,theme}.*` options instead of adding `mkDefault` here.

Why do we have explicit options for freeform modules? Those should be moved into the settings type.

**Comment by hyperparabolic** [comment]
> > I think users should switch to using the new `programs.regreet.{cursorTheme,font,iconTheme,theme}.*` options instead of adding `mkDefault` here.
> 
> Why do we have explicit options for freeform modules? Those should be moved into the settings type.

Yeah, I think I'd probably prefer just documenting the `programs.regreet.GTK.*` options over this, but I didn't want to stomp all over somebody's effort, and I'm honestly not sure what's most idiomatic. I'd defer to you on that.

I don't really mind however this is done. I just don't think a module should conflict with itself and its own existing use.

**Comment by SuperSandro2000** [comment]
The options are still documented when inside the freeform setting and then rendered into the doc. That's the correct approach here and what should be done.

**Comment by hyperparabolic** [comment]
> The options are still documented when inside the freeform setting and then rendered into the doc. That's the correct approach here and what should be done.

I looked at this again for a second with intent to document `programs.regreet.GTK` and this is in an awkward spot now. The `(pkgs.formats.toml {}).type` doesn't seem to offer any built in way to document its args. I think it might still be possible with something like:

```
settings = lib.mkOption {
  type = types.submodule {
    freeformType = settingsFormat.type;
    options = {
      // document GTK.* here
    };
  };
  description = ''
    ReGreet·configuration·file.·Refer⤶                                                                                                                                         
    <https://github.com/rharish101/ReGreet/blob/main/regreet.sample.toml>⤶                                                                                                     
    for·options
  '';
};
```

but I'm not sure how to handle defaults. Ideally I'd set `programs.regreet.settings.GTK.*` properties only if they have non-default values, but I'm not sure how to do that. Any hard coded defaults here would override changes to regreet package defaults, or make it so they couldn't implement theme discovery or similar in the future.

Thoughts? Is there something I'm missing here?

**Comment by hyperparabolic** [comment]
This has gone pretty far off the original topic. I haven't been able to find any examples for the suggestion of how to fix this. This isn't the first commit I thought it might be, and I can't do this without more feedback. Closing.

**Comment by SuperSandro2000** [comment]
> The `(pkgs.formats.toml {}).type` doesn't seem to offer any built in way to document its args.

It is an helper function to turn an attrset into toml. You want to define options in the module system which is a different layer.



> I think it might still be possible with something like:

Yep, this is what I was talking about the whole time.

> Ideally I'd set `programs.regreet.settings.GTK.*` properties only if they have non-default values, but I'm not sure how to do that.

You mean like:

```nix
a = lib.mkOption {
  type = lib.types.str;
  default = "default";
  description = "some description";
};
```

if a is now set, the default is overwritten.

**Comment by hyperparabolic** [comment]
Not quite what I was asking. Creating any default seems to preempt the ability to inherit the default from the package. That also can be behavior somebody else is relying on.

**Pull request closed without merging**
