### PR TITLE
chromium: 78.0.3904.108 -> 79.0.3945.79

### PR DESCRIPTION
**Pull request by ivan**
###### Motivation for this change

https://chromereleases.googleblog.com/2019/12/stable-channel-update-for-desktop.html

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Tested `chromium` on x86_64 NixOS master:
w/ NVIDIA: WebGL, YouTube, audio output, Twitter, Octane 2.0, wasm Google Earth, Widevine OK
w/ radeon: WebGL, YouTube, audio output, Widevine OK

Tested `chromiumDev` on x86_64 NixOS master:
w/ radeon: WebGL, YouTube, audio output OK

###### Notify maintainers

cc @bendlas

### CODE REVIEW

**Comment by ivan** [comment]
Don't merge, GPU acceleration appears to be broken, at least on NVIDIA and radeon, not sure why.

**Comment by ivan** [comment]
I have figured out that copying `/nix/store/cjvg10incaf6sag8z8v0sganlss4mf8q-libGL-1.2.0/lib/*` into `libexec/chromium/` makes Chromium's GL support work, now I just need to do something useful instead of that.

**Comment by ivan** [comment]
I see that chromium 79 can use GL on NVIDIA and radeon if it is started with `--use-gl=egl`. I am looking into what changed between 78 -> 79 w.r.t. GLX and EGL.

**Comment by ivan** [comment]
Still testing, please test if you wish but don't merge until I verify GL and Widevine are working.

**Comment by ivan** [comment]
My patch appears to have fixed the GL issue.

Tested on NVIDIA: WebGL, YouTube, audio output, Twitter, Octane 2.0, wasm Google Earth, Widevine OK
Tested on radeon: WebGL, YouTube, audio output, Widevine OK

Please review/merge.

**Comment by thefloweringash** [comment]
I've verified that this builds and runs on aarch64.

**Pull request merged**
