### PR TITLE
nixos/ipfs: remove separate ipfs-init systemd unit

### PR DESCRIPTION
**Pull request by Luflosi**
###### Motivation for this change
There is no need for a separate unit as far as I can tell. Simplify the NixOS module by adding the shell code to preStart of the main unit, where the other initialization code already is.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg test ipfs

**Comment by Mic92** [comment]
On my server where I had ipfs installed before I got:

```
Apr 23 07:58:14 eve systemd[1]: Starting InterPlanetary File System (IPFS) daemon...
Apr 23 07:58:15 eve ipfs-pre-start[722431]: Error: ipfs repo needs migration
Apr 23 07:58:15 eve systemd[1]: ipfs.service: Control process exited, code=exited, status=1/FAILURE
Apr 23 07:58:15 eve systemd[1]: ipfs.service: Failed with result 'exit-code'.
Apr 23 07:58:15 eve systemd[1]: Failed to start InterPlanetary File System (IPFS) daemon.
Apr 23 07:58:15 eve systemd[1]: ipfs.service: Scheduled restart job, restart counter is at 1.
Apr 23 07:58:15 eve systemd[1]: Stopped InterPlanetary File System (IPFS) daemon.
Apr 23 07:58:15 eve systemd[1]: Starting InterPlanetary File System (IPFS) daemon...
```

Is there a way to make this repo migration in the systemd unit itself?

**Comment by Luflosi** [comment]
I don't know. There used to be some code for auto migration but it was removed, perhaps because it wasn't working. See 74ff433320a6363a3a7e1fff5ac38a13fc737d94 for example.
I always did the migration manually with a command like `nix shell nixpkgs#ipfs-migrator --command sudo -u ipfs IPFS_PATH=/path/to/ipfs/repo fs-repo-migrations`

**Comment by Mic92** [comment]
I guess that does it for now.

**Pull request merged**
