### PR TITLE
nixos/test: some test fixes in succession of #125992

### PR DESCRIPTION
**Pull request by blaggacao**
/cc @vcunat

subset of fixes for https://github.com/NixOS/nixpkgs/pull/125992#issuecomment-902820537

### CODE REVIEW

**Comment by blaggacao** [comment]
```
@GrahamcOfBorg test firefox
@GrahamcOfBorg test printing
```

taking `retry; back into context should solve a whole class of errors

**Comment by blaggacao** [comment]
@vcunat can you eventually get me a new like of this sort to continue short-listing? https://hydra.nixos.org/eval/1697684?compare=1697395&full=1#tabs-now-fail

(need some help)

**Comment by blaggacao** [comment]
this should be merged. both (exemplary) tests are green again.

**Comment by blaggacao** [comment]
```
@GrahamcOfBorg test nsd
```

**Comment by blaggacao** [comment]
@tfc  we should probably expose the `Machine` class instead to allow writing typed test scripts.

**Comment by blaggacao** [comment]
```
@GrahamcOfBorg test firefox
@GrahamcOfBorg test printing
@GrahamcOfBorg test nsd
```

**Review by vcunat — APPROVED** [review]
I don't really know nixos/test stuff, but these are very simple and unblock the `nixos-unstable` channel.

**Comment by vcunat** [comment]
> can you eventually get me a new like of this sort to continue short-listing?

I'm not aware of a way.  There's lots of noise on Hydra (e.g. those hardened regressions).  It's easy to e.g. compare the next evaluation to the one just before this breakage was introduced, but you've probably guessed that already.

**Pull request merged**
