### PR TITLE
home-assistant: remove dotlambda from maintainers

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
I'm currently not using it.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
@mweinelt @fabaff you want to jump in maybe?

**Comment by mweinelt** [comment]
@Mic92 @globin What is your stake in home-assistant and its maintenance these days?

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by mweinelt** [comment]
> @ofborg eval

What kind of result are you expecting given the diff?

**Comment by mweinelt** [comment]
Maybe a home-assistant team would be appropriate here.

**Comment by SuperSandro2000** [comment]
> What kind of result are you expecting given the diff?

ofborg tends to not start on some PRs the last days. I expected it to pass and just gave it the hit it needed.

**Pull request merged**
