### PR TITLE
pipenv: add virualenv to propagatedBuildInputs.

### PR DESCRIPTION
**Pull request by dgarzon**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dgarzon** [comment]
Even though `pew` has `virtualenv` as a `propagatedBuildInputs`, `virtualenv` is not being propagated to `pipenv`. This leads to: `No module named virtualenv` when running the following commands on `nixos-19.03 (sha256:164g1qg2yp9w5a8klfxpw29xjslbxxz6q4v5d0zsxx6rsf04dzgy):

```
pipenv --python 3.7.3
pipenv lock
pypenv sync
```

**Comment by dgarzon** [comment]
Furthermore, after testing this against a real project, I found that the `PYTHONPATH` being set is not correct, as it does not take into consideration the current working directory for a given project. I added a new commit to this PR to reflect the needed changes to make it work. Can we get this merged soon? @zimbatm @flokli . Thanks!

**Comment by zimbatm** [comment]
/cc @berdario as the pipenv maintainer and @FRidh as he is maintaining python in general.

@dgarzon the commit should be formatter like: `pipenv: <reason>`. Other than that it looks ok to me.

**Review by flokli — APPROVED** [review]
LGTM in general too (apart from the commit message) - but we should await some feedback from @berdario or @FRidh.

**Comment by berdario** [comment]
I suspect that part of the issue is that pipenv doesn't depend on pew anymore 

https://github.com/pypa/pipenv/commit/a5a9583c2df93165a3b2ca5a416ddff5c573800a#diff-2eeaed663bd0d25b7e608891384b7298

pipenv usage of pew was also one of the reasons that I cared about it working properly and why I packaged it in the first place. As you can see, I haven't touched it since and in fact I'm not even using it personally anymore.

Sorry for being an absent maintainer.

After unbreaking the tool, we might want to address the above?

**Comment by flokli** [comment]
Thanks @berdario for the heads-up!

I guess in that case, we should drop `pew` from `propagatedBuildInputs` entirely. I grepped through `pipenv`s source code (master), and it doesn't seem to be used.

**Comment by dgarzon** [comment]
Thank you @berdario @zimbatm @flokli I have addressed the commit message structure, and also removed `pew` from the `propagatedBuildInputs` 👍

**Comment by flokli** [comment]
@dgarzon could you update the PR?

**Review by flokli — APPROVED** [review]
LGTM.

**Pull request merged**
