### PR TITLE
lesspipe: add missing dependency on 'file'

### PR DESCRIPTION
**Pull request by snaar**
###### Motivation for this change
lesspipe uses 'file' internally and doesn't work if your system does not have 'file' pulled in by some other means

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by volth** [comment]
but this fixes nothing, just an unreferenced variable added

**Comment by Mic92** [comment]
`makeWrapper` is required to extend the PATH of lesspipe to have file available at runtime:

https://github.com/NixOS/nixpkgs/blob/3fdde25b4c3c7c7962c6e92109d5f4d62f134fc8/pkgs/development/tools/ronn/default.nix#L18

`file` is mentioned as required program in lesspipe, so this should be fine: https://github.com/wofr06/lesspipe

**Comment by snaar** [comment]
Thank you for help. Using "--pure" with nix-shell also uncovered dependency on tput from ncurses, which I added.

I still need help though: while it works now, lesspipe.sh tries to print helpful error message referencing to itself and ends up printing something like:
```
$ ./result/bin/lesspipe.sh 
LESSOPEN="|/nix/store/b910wzmz5xqfv0i9xapwls8ira5vi0kh-lesspipe-1.82/bin/.lesspipe.sh-wrapped %s"
export LESSOPEN
```
It should instead refer to the unwrapped version of itself. What is the typical way to handle it? One way I can see right now is to do patching of the lesspipe.sh itself to replace references to 'file' with references to '${file}/bin/file' instead of the wrapProgram step. That seems somewhat fragile. Is there any other canonical way?

**Comment by Mic92** [comment]
Since it seems to be only used there https://github.com/wofr06/lesspipe/blob/lesspipe/lesspipe.sh#L50,
you could create a simple patch that replaces `file` and `tput` there with the help of `substituteAll`: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/flatpak-builder/default.nix#L78 https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/flatpak-builder/fix-paths.patch

This is more robust on updates then just using sed.

**Comment by snaar** [comment]
I'm happy with the result now, thank you.

**Review by matthewbauer — DISMISSED** [review]
Because this is a shell script, I think it will be much easier to maintain if you just do ```wrapProgram``` in postInstall with those paths.

**Comment by snaar** [comment]
What are the procedures for getting a change into current release branch by the way? I'd like to try it for this change just to see how that works.

**Comment by Mic92** [comment]
```console
# branch of from the release branch
$ git checkout release-18.03
# create a new local branch based on that
$ git checkout -b less-pipe-backport
# cherry pick the commits that were merged to nixpkgs master
$ git cherry-pick -x <commits-from-master...>
# upload to your own nixpkgs fork
$ git push origin less-pipe-backport
```

and then open a pull request for your `less-pipe-backport` branch.

**Comment by snaar** [comment]
Ah ok, no special procedures then. Thanks again.

**Pull request merged**
