### PR TITLE
tremc: init at 0.9.1

### PR DESCRIPTION
**Pull request by snglth**
###### Motivation for this change

#84238 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Emantor** [comment]
- [x] checked license
The derivation says `gpl3Plus`, the project has GPL3 in `COPYING`, however the tremc file specifies ` version 3 of the License, or (at your option) any later version.`
- [x] build derivation on NixOS unstable:
```
$ nix build --no-link --keep-going --option build-use-sandbox relaxed -f /home/phoenix/.cache/nixpkgs-review/pr-84718/build.nix
[3 built, 0.0 MiB DL]
https://github.com/NixOS/nixpkgs/pull/84718
1 package built:
tremc
```
- [x] ran the binary, I get:
```
Traceback (most recent call last):
  File "/nix/store/7s3dakw4mxb96q2zfhvflnai92d9axz5-tremc-0.9.1/bin/.tremc-wrapped", line 3712, in <module>
    Interface()
  File "/nix/store/7s3dakw4mxb96q2zfhvflnai92d9axz5-tremc-0.9.1/bin/.tremc-wrapped", line 986, in __init__
    self.run()
  File "/nix/store/7s3dakw4mxb96q2zfhvflnai92d9axz5-tremc-0.9.1/bin/.tremc-wrapped", line 1080, in run
    self.draw_stats()
  File "/nix/store/7s3dakw4mxb96q2zfhvflnai92d9axz5-tremc-0.9.1/bin/.tremc-wrapped", line 2616, in draw_stats
    self.draw_global_rates()
  File "/nix/store/7s3dakw4mxb96q2zfhvflnai92d9axz5-tremc-0.9.1/bin/.tremc-wrapped", line 2695, in draw_global_rates
    self.screen.addch(curses.ACS_UARROW, curses.A_REVERSE)
_curses.error: addch() returned ERR
```
when trying to run against a locally started transmission daemon

**Comment by snglth** [comment]
>     * [x]  checked license
>       The derivation says `gpl3Plus`, the project has GPL3 in `COPYING`, however the tremc file specifies ` version 3 of the License, or (at your option) any later version.`
So, what license should we specify?
>     * [x]  ran the binary, I get:
> 
> 
> ```
> Traceback (most recent call last):
>   File "/nix/store/7s3dakw4mxb96q2zfhvflnai92d9axz5-tremc-0.9.1/bin/.tremc-wrapped", line 3712, in <module>
>     Interface()
>   File "/nix/store/7s3dakw4mxb96q2zfhvflnai92d9axz5-tremc-0.9.1/bin/.tremc-wrapped", line 986, in __init__
>     self.run()
>   File "/nix/store/7s3dakw4mxb96q2zfhvflnai92d9axz5-tremc-0.9.1/bin/.tremc-wrapped", line 1080, in run
>     self.draw_stats()
>   File "/nix/store/7s3dakw4mxb96q2zfhvflnai92d9axz5-tremc-0.9.1/bin/.tremc-wrapped", line 2616, in draw_stats
>     self.draw_global_rates()
>   File "/nix/store/7s3dakw4mxb96q2zfhvflnai92d9axz5-tremc-0.9.1/bin/.tremc-wrapped", line 2695, in draw_global_rates
>     self.screen.addch(curses.ACS_UARROW, curses.A_REVERSE)
> _curses.error: addch() returned ERR
> ```
> 
> when trying to run against a locally started transmission daemon

Hmm, it looks like an issue with ncurses struggling with your terminal emulator. I've tested it  in Alacritty and a bare linux tty.

**Comment by Emantor** [comment]
> > ```
> > * [x]  checked license
> >   The derivation says `gpl3Plus`, the project has GPL3 in `COPYING`, however the tremc file specifies ` version 3 of the License, or (at your option) any later version.`
> > ```
> 
> So, what license should we specify?

IANAL, but IMO gpl3Plus is fine.

> > ```
> > * [x]  ran the binary, I get:
> > ```
> > 
> > 
> > ```
> > Traceback (most recent call last):
> >   File "/nix/store/7s3dakw4mxb96q2zfhvflnai92d9axz5-tremc-0.9.1/bin/.tremc-wrapped", line 3712, in <module>
> >     Interface()
> >   File "/nix/store/7s3dakw4mxb96q2zfhvflnai92d9axz5-tremc-0.9.1/bin/.tremc-wrapped", line 986, in __init__
> >     self.run()
> >   File "/nix/store/7s3dakw4mxb96q2zfhvflnai92d9axz5-tremc-0.9.1/bin/.tremc-wrapped", line 1080, in run
> >     self.draw_stats()
> >   File "/nix/store/7s3dakw4mxb96q2zfhvflnai92d9axz5-tremc-0.9.1/bin/.tremc-wrapped", line 2616, in draw_stats
> >     self.draw_global_rates()
> >   File "/nix/store/7s3dakw4mxb96q2zfhvflnai92d9axz5-tremc-0.9.1/bin/.tremc-wrapped", line 2695, in draw_global_rates
> >     self.screen.addch(curses.ACS_UARROW, curses.A_REVERSE)
> > _curses.error: addch() returned ERR
> > ```
> > 
> > 
> > when trying to run against a locally started transmission daemon
> 
> Hmm, it looks like an issue with ncurses struggling with your terminal emulator. I've tested it in Alacritty and a bare linux tty.

I use alacritty too, are you running stable or unstable?

**Comment by snglth** [comment]
I'm running unstable.

**Comment by snglth** [comment]
Closing in favor of #85323

**Pull request closed without merging**
