### PR TITLE
snapraid: fix split parity files

### LINKED ISSUE #269248: SnapRAID package doesn't support split parity files
### Describe the bug
When specifying multiple paths in a single parityFile entry (SnapRAID [split-parity feature](https://www.snapraid.it/manual#7.1)), the `snapraid-sync.service` systemd service failes with the following error:
```Failed to set up mount namespacing: /run/systemd/unit-root/mnt/parity1/snapraid1.parity,/mnt/parity1/snapraid2.parity: No such file or directory```

### Steps To Reproduce
1. Create a SnapRAID config and specify a `snapraid.parityFiles` entry like so:  `"/mnt/parity1/snapraid1.parity,/mnt/parity1/snapraid2.parity"`
2. Manually run the snapraid sync: ```sudo systemctl start snapraid-sync.service```
3. Observe the error: `sudo journalctl -u snapraid-sync.service`

### Expected behavior
The `snapraid-sync.service` runs without error.

### Additional context
SnapRAID has a [feature](https://www.snapraid.it/manual#7.1) where you can specify "split" parity files.  This is useful when you're using 16tb or bigger ext4-formatted disks for parity.  ext4 doesn't support files bigger than 16tb so this "split parity file" can be used to specify two parity files on a single raid disk and SnapRAID will automatically use the second file when the first cannot grow anymore (hits 16TB).  You specify these multiple files by putting multiple comma-separated paths in the [parity" option](https://www.snapraid.it/manual#7.1).  This mostly already works except when it comes to the scheduled systemd sync job where it specifies [`ReadWritePaths`](https://github.com/NixOS/nixpkgs/blob/bef55841a27cd41710bf52e6d6de41bd8733a1fc/nixos/modules/tasks/snapraid.nix#L215-L223).  If you specify a parity with multiple files you'll get an error when the systemd job runs:
```Failed to set up mount namespacing: /run/systemd/unit-root/mnt/parity1/snapraid1.parity,/mnt/parity1/snapraid2.parity: No such file or directory```
It seems like since SnapRAID essentially does not allow commas in the parity file paths it would be OK to split on comma here?

### Notify maintainers
@makefu @r-ryantm 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.62, NixOS, 23.05 (Stoat), 23.05.20231121.767986a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.6`
 - channels(root): `"nixos"`
 - channels(khendricks): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by kylehendricks**
## Description of changes
Fixes https://github.com/NixOS/nixpkgs/issues/269248

SnapRAID has a feature where you can specify "split" parity files. This is useful when you're using 16tb or bigger ext4-formatted disks for parity. ext4 doesn't support files bigger than 16tb so this "split parity file" can be used to specify two parity files on a single parity disk and SnapRAID will automatically use the subsequent file when the current cannot grow anymore (hits 16TB). You specify these split parity files by separating them with commas in the "parity" config option. This mostly already works except when it comes to the scheduled systemd sync job where it specifies ReadWritePaths. If you specify a parity with multiple files you'll get an error when the systemd job runs: `Failed to set up mount namespacing:
/run/systemd/unit-root/mnt/parity1/snapraid1.parity,/mnt/parity1/snapraid2.parity: No such file or directory` Essentially, when the parity file paths are passed into ReadWritePaths, they're always treated as a single path.  This change makes sure to split the paths if they contain a comma.

The big concern for this change is if it would break users who have commas in their actual parity file paths.  This won't be an issue because SnapRAID itself blindly splits on commas for parity files, so legitimate commas in a parity file path wouldn't work in SnapRAID anyway. See here: https://github.com/amadvance/snapraid/blob/978d812153736c06763192f0f1d4b34e54ad633f/cmdline/state.c#L692

SnapRAID doc for split parity files: https://www.snapraid.it/manual#7.1

## Things done

- Used this package locally with my broken configuration and verified working by running `sudo systemctl show snapraid-sync.service` and verifying `ReadWritePaths` had the paths split properly.  Also ran the systemd service and verified it ran successfully.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by lunik1 — APPROVED** [review]

**Comment by lunik1** [comment]
LGTM, thanks for the PR

**Comment by emilytrau** [comment]
Would you please add a short note to the changelog?

**Comment by kylehendricks** [comment]
> Would you please add a short note to the changelog?

Sorry, I looked around for the changelog you're referring to and couldn't find anything.  Could you point me in the right direction?

**Comment by emilytrau** [comment]
Thanks for your contribution!

**Pull request merged**
