### PR TITLE
zabbix: Support for 6.0

### PR DESCRIPTION
**Pull request by andreaswolf**
###### Description of changes

This is a followup to https://github.com/NixOS/nixpkgs/pull/145502. I took this PR and replaced Zabbix 5.4 by 6.0. I could build it locally, but did not test it yet.

Please be gentle, this is my second week of working with Nix and NixOS… :sweat_smile: 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aanderse** [comment]
Hello :wave: 

Sorry I took so long to get around this. It sort of dropped off my radar and I noticed it today when reviewing my backlog.

Thanks for picking this up! Can you please review the list of commits. The first one isn't needed, for example.

**Comment by andreaswolf** [comment]
No worries :)

I left the base branch intact to not just hijack someone elses work w/o proper attribution. If that's better I could also squash commits together and attribute the original authors in the commit message.

**Comment by aanderse** [comment]
That sounds good to me. Thanks.

**Comment by andreaswolf** [comment]
I just rebased my MR onto master and squashed the two version update commits into one.

**Comment by aanderse** [comment]
Taking a look over everything I don't see any problems, everything looks in order. Did you do any testing? Run the update script, etc...? Am I good to click merge? Thanks!

**Comment by andreaswolf** [comment]
Well, I'm pretty new to Nix, so I can't judge this 100%. I took the existing MR, left most untouched and just swapped 5.4 for 6.0.

What I can say: I have this running in production on one machine (slowly migrating my stuff over to NixOS). So it works at least for me…

**Comment by aanderse** [comment]
Packages all build fine, I'm happy to merge all that. Unfortunately update script has a couple issues. It might be a good idea to drop the update script from this PR so we can merge it right away and then a second PR to work through the update script issues.

---

```
$ nix-shell maintainers/scripts/update.nix
...
           % nix-shell maintainers/scripts/update.nix --argstr package gnome.nautilus

       to run update script for specific package, or
```

so...

```
$ nix-shell maintainers/scripts/update.nix --argstr package zabbix60.agent2                                                                                                                           
this derivation will be built:
  /nix/store/4yhcb6mlrkgxw4lf6xclc415bdbyai2f-packages.json.drv
building '/nix/store/4yhcb6mlrkgxw4lf6xclc415bdbyai2f-packages.json.drv'...

Going to be running update for following packages:
 - zabbix-agent2-6.0.9

Press Enter key to continue...

Running update for:
 - zabbix-agent2-6.0.9: UPDATING ...
 - zabbix-agent2-6.0.9: ERROR

--- SHOWING ERROR LOG FOR zabbix-agent2-6.0.9 ----------------------

these 8 paths will be fetched (9.08 MiB download, 59.91 MiB unpacked):
  /nix/store/7rhf667rkqhcljcyz9b9mrzjw1sh3qji-gettext-0.21
  /nix/store/klar7c8pcc6a35jyw8wwjjq6dfipz2pb-perl5.34.0-HTML-TagCloud-0.38
  /nix/store/l5wrs6xl99pjrrr94jwiz5a2py7b7j35-perl5.34.0-FCGI-ProcManager-0.28
  /nix/store/q5v46mf2gppaw15fz30kf7dj9swmbya1-git-2.33.1-doc
  /nix/store/qc34acwphyjjr2y5vxyz1q9vz8hrk1ik-git-2.33.1
  /nix/store/rqy6r093k446b0l45dn0pa244lap3dfm-perl5.34.0-CGI-Fast-2.15
  /nix/store/xmsxysya1dvc6xsgg3hv1sv0fz7qw81n-perl5.34.0-FCGI-0.79
  /nix/store/zl3nikgcdx0z76aq2sf0v9kc337990nx-perl5.34.0-CGI-4.51
copying path '/nix/store/q5v46mf2gppaw15fz30kf7dj9swmbya1-git-2.33.1-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/l5wrs6xl99pjrrr94jwiz5a2py7b7j35-perl5.34.0-FCGI-ProcManager-0.28' from 'https://cache.nixos.org'...
copying path '/nix/store/klar7c8pcc6a35jyw8wwjjq6dfipz2pb-perl5.34.0-HTML-TagCloud-0.38' from 'https://cache.nixos.org'...
copying path '/nix/store/zl3nikgcdx0z76aq2sf0v9kc337990nx-perl5.34.0-CGI-4.51' from 'https://cache.nixos.org'...
copying path '/nix/store/xmsxysya1dvc6xsgg3hv1sv0fz7qw81n-perl5.34.0-FCGI-0.79' from 'https://cache.nixos.org'...
copying path '/nix/store/7rhf667rkqhcljcyz9b9mrzjw1sh3qji-gettext-0.21' from 'https://cache.nixos.org'...
copying path '/nix/store/rqy6r093k446b0l45dn0pa244lap3dfm-perl5.34.0-CGI-Fast-2.15' from 'https://cache.nixos.org'...
copying path '/nix/store/qc34acwphyjjr2y5vxyz1q9vz8hrk1ik-git-2.33.1' from 'https://cache.nixos.org'...
$ nix-instantiate --expr --strict --json --eval '
with builtins;
mapAttrs (_: attrs:
  mapAttrs (k: v:
    {
      value = v;
      pos = unsafeGetAttrPos k attrs;
    }
  ) attrs
) (
  import ./versions.nix (x: x)
)
'
warning: unknown setting 'access-tokens'
warning: unknown setting 'experimental-features'
warning: unknown setting 'warn-dirty'
error: getting status of '/home/aaron/nixpkgs/versions.nix': No such file or directory
Traceback (most recent call last):
  File "/home/aaron/nixpkgs/pkgs/servers/monitoring/zabbix/update.py", line 56, in <module>
    info = json.loads(run('nix-instantiate', '--expr', '--strict', '--json', '--eval', '''
  File "/home/aaron/nixpkgs/pkgs/servers/monitoring/zabbix/update.py", line 17, in run
    return subprocess.run(args, **kwargs)
  File "/nix/store/2c9w4p2x6x0l64fdvcmc11app7x4xran-python3-3.9.6/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('nix-instantiate', '--expr', '--strict', '--json', '--eval', '\nwith builtins;\nmapAttrs (_: attrs:\n  mapAttrs (k: v:\n    {\n      value = v;\n      pos = unsafeGetAttrPos k attrs;\n    }\n  ) attrs\n) (\n  import ./versions.nix (x: x)\n)\n')' returned non-zero exit status 1.


--- SHOWING ERROR LOG FOR zabbix-agent2-6.0.9 ----------------------
The update script for zabbix-agent2-6.0.9 failed with exit code 1
```

1. The script is interactive which probably means our bot can't run it and automatically update `zabbix` for us.
2. The script doesn't work with the instructions provided by [our manual](https://nixos.org/manual/nixpkgs/stable/#special-variables).

**Comment by aanderse** [comment]
@seberm oh... this is very unfortunate. Several members of the @NixOS/php maintain older `php` versions [here](https://github.com/fossar/nix-phps/) that you could use, but you're right we should really get `zabbix` moved to `6.x`.

**Pull request closed without merging**
