### PR TITLE
[23.11] gnutls: 3.8.3 -> 3.8.4

### PR DESCRIPTION
**Pull request by LeSuisse**
## Description of changes

#297657

https://lists.gnupg.org/pipermail/gnutls-help/2024-March/004845.html

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by alyssais** [comment]
This is a build regression for musl.  For stable I guess that should be weighed against the security impact.  (I haven't looked into what the issue is beyond that it's "medium", so I'm not qualified to have an opinion on that.)  (I'll try to fix it but no promises.)

**Comment by LeSuisse** [comment]
I have been able to build `pkgsMusl.gnutls` on top of this branch. Does the issue only affect unstable?

**Comment by alyssais** [comment]
Oh, it looks like it does! Sorry for the noise.

**Comment by alyssais** [comment]
Right, there were two things going on here, so I got confused — there's a transient build failure that I thought was pkgsMusl regressing, but there's _also_ a real, persistent regression of pkgsStatic.gnutls.

**Comment by LeSuisse** [comment]
Closing this in favor of #298806 for 23.11.

There is something going on with the version of Nettle they vendor that is not happy with `pkgsStatic`. We fallback to the vendored version because they need it to support the RSA OAEP primitives they added and it's not present in a released version of Nettle.

**Pull request closed without merging**
