### PR TITLE
vscode

### PR DESCRIPTION
**Pull request by jgillich**
Note that vscode is broken and this doesn't fix that (#14890).
###### Things done
- [X] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- Built on platform(s)
  - [X] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jgillich** [comment]
I don't have a darwin machine, can someone tell me the correct hash?

**Comment by abbradar** [comment]
Given that `fetchurl` is used here you can just run `nix-prefetch-url` and copy the hash.

**Comment by jgillich** [comment]
Oh I had no idea, done.

**Comment by abbradar** [comment]
In the long term we should perhaps build those from sources, but the process of doing this is definitely non-trivial (we need to build `libcef` first and then somehow all those, too).

**Comment by jgillich** [comment]
I don't know of a single distribution that has packaged libcef, heck even Chromium is not accepted into many repos because of its excessive bundling/forking of other libraries. Having maintained a partially source-based Brackets rpm over the last few years, I don't think its worth the effort, at least not until upstream makes some changes to help packaging.

**Comment by abbradar** [comment]
Fair enough -- FWIW I have tried to build `libcef` in the past and while I succeeded, the amount of effort needed burned all my motivation to actually use it somewhere...

**Comment by jgillich** [comment]
Maybe I would still be using Brackets instead of VS Code if it weren't for its awful build process (want a release build? We'll simply force you to run tests first, which of course require half of npmjs.org as dependencies, plus webkit because why not. Oh, and here's a 4 years old libcef we link against that works on no modern distro :scream:).

**Comment by abbradar** [comment]
*sigh* I still have to be shown at least _one_ `libcef`-based package which can be sanely built... See also https://github.com/NixOS/nixpkgs/issues/10452 for more libcef insanity (though arguably that's more a Unity problem for not updating their library to namespaces-supporting version).

**Comment by mucaho** [comment]
Just tried to install it from nixkpkgs-channel and it works, good job everybody!
This PR fixed part of #14850.

**Pull request merged**
