### PR TITLE
go_1_20: 1.20.8 -> 1.20.9

### PR DESCRIPTION
**Pull request by mfrw**
## Description of changes
Changelog: https://go.dev/doc/devel/release#go1.20

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by kalbasit — APPROVED** [review]

**Review by qbit — APPROVED** [review]

**Comment by fabianhjr** [comment]
Rebuilds seem low, could this go to the main branch directly?

**Comment by mfrw** [comment]
> Rebuilds seem low, could this go to the main branch directly?

I can retarget this to `master`. I was not aware of how many rebuilds would happen at the time I made the PR so thought better to target `staging`.

Should I go ahead and retarget this ? @fabianhjr

**Comment by fabianhjr** [comment]
Sure, though note that you may need to rebase your branch to the merge-base before changing the target branch in github to avoid a mass ping. (More info at https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging )

**Comment by mfrw** [comment]
> Sure, though note that you may need to rebase your branch to the merge-base before changing the target branch in github to avoid a mass ping. (More info at https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging )

Even though you gave such a nice pointer, I still managed to mess it up :(
Sincere apologies @fabianhjr

**Comment by fabianhjr** [comment]
Happens from time to time. :sweat_smile:

Will diverge from the procedure merge when ofborg succeeds since notifications are low enuough and change is small enough.

**Comment by fabianhjr** [comment]
Oh no, I messed up to I apologize as well, lost track of where the default go version change was so far.

https://github.com/NixOS/nixpkgs/pull/254878

Could you create a new pull request targeting staging-next?

Reference

```
go, buildGoModule, buildGoPackage: default to 1.21

    [python-updates](https://github.com/NixOS/nixpkgs/compare/python-updates) ([#254878](https://github.com/NixOS/nixpkgs/pull/254878)) [staging](https://github.com/NixOS/nixpkgs/compare/staging) ([hllizi/nixpkgs#1](https://github.com/hllizi/nixpkgs/pull/1), [#254878](https://github.com/NixOS/nixpkgs/pull/254878)) [staging-next](https://github.com/NixOS/nixpkgs/compare/staging-next) ([#257792](https://github.com/NixOS/nixpkgs/pull/257792), [#254878](https://github.com/NixOS/nixpkgs/pull/254878))
```

**Pull request closed without merging**
