### PR TITLE
treewide: remove wkennington as maintainer

### PR DESCRIPTION
**Pull request by Mic92**
He prefers to contribute to his own nixpkgs fork triton.
Since he is still marked as maintainer in many packages
this leaves the wrong impression he still maintains those.

### CODE REVIEW

**Comment by domenkozar** [comment]
No need to remove him from the org I think. Maintainership makes sense though.

**Review by grahamc — APPROVED** [review]
A shame to see many packages without maintainers.

**Comment by Infinisil** [comment]
Ping @wkennington

**Comment by wkennington** [comment]
Looks good to me

**Pull request merged**
