### PR TITLE
glab: 1.23.0 -> 1.24.1

### PR DESCRIPTION
**Pull request by garymh**
Updating glab version to v1.24.1 https://gitlab.com/gitlab-org/cli/-/releases/v1.24.1

###### Description of changes

Hi all - bumped the `glab` version up to v1.24.1. The release page is here with a changelog: https://gitlab.com/gitlab-org/cli/-/releases/v1.24.1/

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by freezeboy** [comment]
Don't have the permission to approve and run the tests, will review after tests

**Comment by bobby285271** [comment]
The "1 workflow awaiting approval" only appears when you target wrong branch before, it is a "no channel PR" action that will simply fail. It is fine to simply ignore it as long as you are targeting the correct branch now. 

Can you change the commit message to `glab: 1.23.0 -> 1.24.1`? Also ofborg says there is hash mismatch, how did you get those hashes?

```
trying https://gitlab.com/api/v4/projects/gitlab-org%2Fcli/repository/archive.tar.gz?sha=v1.24.1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15.7M    0 15.7M    0     0  11.2M      0 --:--:--  0:00:01 --:--:-- 11.2M
unpacking source archive /build/archive.tar.gz?sha=v1.24.1
error: hash mismatch in fixed-output derivation '/nix/store/wgmf1mfhj46mf5r1clyvn3f01d383jkd-source.drv':
         specified: sha256-3JQveAaqQXcUSDvVMjv83p7OrdftMxVPencDi0Fr3ZU=
            got:    sha256-CUchYPMBTINkMJg8TC8rKMVkrcj/Gy+ZxV7jbtMFvpg=
```

**Comment by garymh** [comment]
Thanks @bobby285271 ! It should be updated now 😄

**Comment by freezeboy** [comment]
Oh didn't know that trick and I didn't really watch the branch either

**Pull request merged**
