### PR TITLE
bazel: 0.29.0 -> 1.0.0

### PR DESCRIPTION
**Pull request by guibou**
###### Motivation for this change

Update bazel to upstream version.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @Profpatsch

### CODE REVIEW

**Comment by guibou** [comment]
Sorry, I should have created a "draft" PR. This should not be merged until bazel 1.0 is official.

**Comment by guibou** [comment]
@GrahamcOfBorg build bazel.tests

**Comment by Mic92** [comment]
@guibou marking it as draft is a good idea.

**Comment by guibou** [comment]
Bazel 1.0 was released: https://blog.bazel.build/2019/10/10/bazel-1.0.html

I no longer consider this PR as work in progress.

**Comment by Profpatsch** [comment]
@GrahamcOfBorg build bazel.tests

**Comment by Profpatsch** [comment]
We’ll have to fix the darwin build now:

```
Building Bazel from scratch....../usr/bin/xcrun --sdk macosx clang -fobjc-arc -framework CoreServices -framework Foundation -o /private/tmp/nix-build-bazel-1.0.0.drv-0/bazel_s6Mj2C4u/archive/_embedded_binaries/xcode-locator tools/osx/xcode_locator.m
xcode-select: error: no developer tools were found at '/Applications/Xcode.app', and no install could be requested (perhaps no UI is present), please install manually from 'developer.apple.com'.
./bazel_src/scripts/generate_bash_completion.sh: line 71: ./bazel_src/output/bazel: No such file or directory
builder for '/nix/store/lfpcg31ckz5xf8bdygimz41ngc2dfh0h-bazel-1.0.0.drv' failed with exit code 127
```

@kalbasit, @uri-canva  any input?

**Comment by kalbasit** [comment]
> We’ll have to fix the darwin build now:
> 
> ```
> Building Bazel from scratch....../usr/bin/xcrun --sdk macosx clang -fobjc-arc -framework CoreServices -framework Foundation -o /private/tmp/nix-build-bazel-1.0.0.drv-0/bazel_s6Mj2C4u/archive/_embedded_binaries/xcode-locator tools/osx/xcode_locator.m
> xcode-select: error: no developer tools were found at '/Applications/Xcode.app', and no install could be requested (perhaps no UI is present), please install manually from 'developer.apple.com'.
> ./bazel_src/scripts/generate_bash_completion.sh: line 71: ./bazel_src/output/bazel: No such file or directory
> builder for '/nix/store/lfpcg31ckz5xf8bdygimz41ngc2dfh0h-bazel-1.0.0.drv' failed with exit code 127
> ```
> 
> @kalbasit, @uri-canva any input?

Maybe we should fix/expand this :point_down:?

https://github.com/NixOS/nixpkgs/blob/73eb01bde000c34b54764f6f2b9fd1d89a54ccfa/pkgs/development/tools/build-managers/bazel/default.nix#L309-L313

**Comment by flokli** [comment]
@GrahamcOfBorg build bazel

**Comment by flokli** [comment]
https://github.com/bazelbuild/bazel/commit/ada2c55dcc106cd55bafbbe5d9a966e21e4770e0 introduced explicit `--sdk macosx` parameters, and our `sed` to patch this to `${stdenv.cc}/bin/clang` didn't apply anymore.

I pushed a commit on top of it which should fix the two currently not matching occurences in `src/tools/xcode/realpath/BUILD` and `tools/osx/BUILD`, but I'm not sure if more work is needed.

I'm not sure why we need this in first place - passing another compiler to use instead of xcrun should be something supported upstreamed somehow by `BAZEL_USE_CPP_ONLY_TOOLCHAIN`, so this might be an upstream bug while building bazel itself.

**Comment by Profpatsch** [comment]
@GrahamcOfBorg build bazel.tests

**Comment by flokli** [comment]
I opened https://github.com/bazelbuild/bazel/issues/9993 about using `BAZEL_USE_CPP_ONLY_TOOLCHAIN` to build bazel itself, so we might get rid of patching these `xcrun` paths in the future.

**Comment by Profpatsch** [comment]
```
ERROR: /private/var/tmp/_bazel_nixbld1/56203a21b662facfb0adf82c2b07e3a9/external/com_google_protobuf/BUILD:388:1: C++ compilation of rule '@com_google_protobuf//:protoc' failed (Exit 1) cc_wrapper.sh failed: error executing command
  (cd /private/var/tmp/_bazel_nixbld1/56203a21b662facfb0adf82c2b07e3a9/sandbox/processwrapper-sandbox/2/execroot/our_workspace && \
  exec env - \
    PATH=/nix/store/z298gvhxk2z8l0asyn1dxhbfgkyqbdzw-clang-wrapper-7.1.0/bin:/nix/store/2vz5l1vh943013fi6y4c8vrnls30s5gb-clang-7.1.0/bin:/nix/store/ywh9sd47gs8m6r2gdlrg3240zc8lzqlz-coreutils-8.31/bin:/nix/store/fppvpyp7f1018ca9bsxanmxlm0jha3z3-cctools-binutils-darwin-wrapper/bin:/nix/store/8wja3apgzfxb6sq9zlgcwbayzqbv81rg-cctools-binutils-darwin/bin:/nix/store/ywh9sd47gs8m6r2gdlrg3240zc8lzqlz-coreutils-8.31/bin:/nix/store/611gq7s9s11w5ri95fbq2adi9ifrhkmn-python3-3.7.4/bin:/nix/store/z0ql8nlhvxsw4lwlhrinbg1vf8p064w7-zulu1.8.0_121-8.20.0.5/bin:/nix/store/ywh9sd47gs8m6r2gdlrg3240zc8lzqlz-coreutils-8.31/bin:/nix/store/2vi5scm77xixrgp6jp5j2xyg02zqhr1h-findutils-4.7.0/bin:/nix/store/5hzif2m3rjyhpbnrk3g63hr1h3s73q6p-diffutils-3.7/bin:/nix/store/46j1f9xrkxb4z7bjcqgs6aq073rc3jdl-gnused-4.7/bin:/nix/store/zl63kky2pi5vd4x53g2r0nqgirs43msk-gnugrep-3.3/bin:/nix/store/2v37kq4hkyl8bvl9gvrl3ag3d22dzwfc-gawk-5.0.1/bin:/nix/store/nd7wmp6bw5w3pc5p1yfrf9g2m6bwajia-gnutar-1.32/bin:/nix/store/cy599ifm4dwdxfm1kjghd16ni4nmy81c-gzip-1.10/bin:/nix/store/riygq975bghqqlhpqp4hihlvxrbqfzqk-bzip2-1.0.6.0.1-bin/bin:/nix/store/givd6m0izs21yc8drxsy9ps7qyivjsqg-gnumake-4.2.1/bin:/nix/store/v1sp0shp912cwz3h92rmpvpbsyshiq48-bash-4.4-p23/bin:/nix/store/3v46lnv5h6ah03i0mzqhqna5d550w6ic-patch-2.7.6/bin:/nix/store/czgx3s4y2ivcf5mc3iz8jmh9p2fql9vh-xz-5.2.4-bin/bin:/nix/store/v1sp0shp912cwz3h92rmpvpbsyshiq48-bash-4.4-p23/bin:/nix/store/ywh9sd47gs8m6r2gdlrg3240zc8lzqlz-coreutils-8.31/bin:/nix/store/2vi5scm77xixrgp6jp5j2xyg02zqhr1h-findutils-4.7.0/bin:/nix/store/2v37kq4hkyl8bvl9gvrl3ag3d22dzwfc-gawk-5.0.1/bin:/nix/store/zl63kky2pi5vd4x53g2r0nqgirs43msk-gnugrep-3.3/bin:/nix/store/1dxzl7kfpr1xpiislljmxypcl7il89rf-gnutar-1.32/bin:/nix/store/46j1f9xrkxb4z7bjcqgs6aq073rc3jdl-gnused-4.7/bin:/nix/store/cy599ifm4dwdxfm1kjghd16ni4nmy81c-gzip-1.10/bin:/nix/store/9safg84mmd3cd6i0lamd7dppvxrmz3i5-which-2.21/bin:/nix/store/h9dqx3wyaicslf9cdycya16dgmrgqn96-unzip-6.0/bin \
    PWD=/proc/self/cwd \
  external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/host/bin/external/com_google_protobuf/_objs/protoc/main.d '-frandom-seed=bazel-out/host/bin/external/com_google_protobuf/_objs/protoc/main.o' -iquote external/com_google_protobuf -iquote bazel-out/host/bin/external/com_google_protobuf -iquote external/net_zlib -iquote bazel-out/host/bin/external/net_zlib -iquote external/bazel_tools -iquote bazel-out/host/bin/external/bazel_tools -isystem external/com_google_protobuf/src -isystem bazel-out/host/bin/external/com_google_protobuf/src -isystem external/net_zlib/zlib/include -isystem bazel-out/host/bin/external/net_zlib/zlib/include -g0 -g0 -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_google_protobuf/src/google/protobuf/compiler/main.cc -o bazel-out/host/bin/external/com_google_protobuf/_objs/protoc/main.o)
Execution platform: @local_config_platform//:host
Use --sandbox_debug to see verbose messages from the sandbox
src/main/tools/process-wrapper-legacy.cc:58: "execvp(external/local_config_cc/cc_wrapper.sh, ...)": No such file or directory
INFO: Elapsed time: 5,092s, Critical Path: 0,14s
INFO: 1 process: 1 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

**Comment by flokli** [comment]
This smells like the same error as in https://github.com/NixOS/nixpkgs/pull/66723#issuecomment-529590629, so pinging @aherrmann here - this might already be halfway broken in master on Darwin, the version bump now just exercises more  code paths.

What do you think about merging this PR into master as-is, rebasing #66723 on top of it, and fix the darwin problems in there too?

**Comment by Profpatsch** [comment]
> This smells like the same error as in [#66723 (comment)](https://github.com/NixOS/nixpkgs/pull/66723#issuecomment-529590629), so

Oh wow, you are right!

**Comment by Profpatsch** [comment]
In accordance with @flokli I’ll merge and we are going to open an issue about the MacOS thing.

**Comment by flokli** [comment]
I opened a follow-up issue for the broken MacOS tests in https://github.com/NixOS/nixpkgs/issues/70994.

**Pull request merged**
