### PR TITLE
lxqt.libqtxdg: 3.3.1 -> 3.4.0

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

Update to version [3.4.0](https://forum.lxqt.org/t/release-libqtxdg-3-4-0/981)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by worldofpeace** [comment]
This fails to build on darwin. Should any of these packages really have `platforms.unix`?

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS (1 broken on master)
diff LGTM
executables appear to work (not much testing)

```
[24 built (1 failed), 119 copied (568.8 MiB), 157.7 MiB DL]
error: build of '/nix/store/9q23f2pq6brgbpl041463kz1c940nmh1-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/72182
1 package are marked as broken and were skipped:
deepin.deepin-wm

2 package failed to build:
deepin.dde-file-manager deepin.deepin-terminal

22 package were build:
deepin.dde-control-center deepin.deepin-image-viewer deepin.deepin-menu deepin.deepin-screenshot deepin.deepin-shortcut-viewer deepin.qt5integration lxqt.liblxqt lxqt.libqtxdg lxqt.lxqt-about lxqt.lxqt-admin lxqt.lxqt-config lxqt.lxqt-globalkeys lxqt.lxqt-notificationd lxqt.lxqt-openssh-askpass lxqt.lxqt-panel lxqt.lxqt-policykit lxqt.lxqt-powermanagement lxqt.lxqt-qtplugin lxqt.lxqt-runner lxqt.lxqt-session lxqt.lxqt-sudo lxqt.screengrab
```

I would switch the platform to linux though, it makes no mention of it supporting darwin.

**Comment by romildo** [comment]
> This fails to build on darwin. Should any of these packages really have `platforms.unix`?

It seems that `mariadb-connector-c` is what fails on darwin, and as a consequence `qtbase` also fails, making this package also to fail. Is that enough to justify restricting it to the linux platform?

That would prevent having some applications (like `screengrab`) that depend on `libqtxdg` to be available in other platforms.

**Comment by romildo** [comment]
> Should any of these packages really have `platforms.unix`?

That would imply changing most of the LXQt packages to `platforms.unix`, right?

**Comment by worldofpeace** [comment]
@romildo No, that would be `platforms.linux`. Are these supported on darwin? I find it unlikely, it's a DE for linux so I assume linux is only supported.

**Comment by jonringer** [comment]
@GrahamcOfBorg build lxqt.libqtxdg

**Comment by romildo** [comment]
Resticting the platform to linux, as it fails to build on darwin.

Doing the same for other components of LXQt that depends on `libqtxdg`.

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS (failures are broken on master)
diff LGTM
commits LGTM

```
[24 built (1 failed), 91 copied (551.4 MiB), 162.4 MiB DL]
error: build of '/nix/store/966qihw11zj9kpwng4z4cifcfrjv8lpd-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/72182
2 package failed to build:
deepin.dde-file-manager deepin.deepin-terminal

23 package were build:
deepin.dde-control-center deepin.dde-kwin deepin.deepin-image-viewer deepin.deepin-menu deepin.deepin-screenshot deepin.deepin-shortcut-viewer deepin.qt5integration lxqt.liblxqt lxqt.libqtxdg lxqt.lxqt-about lxqt.lxqt-admin lxqt.lxqt-config lxqt.lxqt-globalkeys lxqt.lxqt-notificationd lxqt.lxqt-openssh-askpass lxqt.lxqt-panel lxqt.lxqt-policykit lxqt.lxqt-powermanagement lxqt.lxqt-qtplugin lxqt.lxqt-runner lxqt.lxqt-session lxqt.lxqt-sudo lxqt.screengrab
```

**Comment by worldofpeace** [comment]
> Resticting the platform to linux, as it fails to build on darwin.
> 
> Doing the same for other components of LXQt that depends on `libqtxdg`.

Thanks for fixing this :+1:

**Pull request merged**
