### PR TITLE
ssh-mitm: 2.1.0 -> 3.0.1

### PR DESCRIPTION
**Pull request by manfred-kaiser**
Update nix module to the latest version. At the moment, the hash value for the githup repo is wrong and must be changed

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by manfred-kaiser** [comment]
@fabaff can you help me to update the nix package to the latest version of SSH-MITM, pleas

**Comment by bobby285271** [comment]
> I don't know how to generate the hash value

This package has an update script, it will update the hash for you. To use it:

```sh
# ... assume you have nix installed (nix can be installed on non-nixos) and nixpkgs cloned
cd /path/to/nixpkgs
nix-shell maintainers/scripts/update.nix --argstr package python310Packages.ssh-mitm
# ... both the version and the hash should be updated now, if the update contains build changes, address them
vi pkgs/development/python-modules/ssh-mitm/default.nix
# ... now build and test the package
nix-build -A ssh-mitm
# ... check the build result
./result/bin/ssh-mitm --version
# ... commit the changes and force push the branch
```

Or if the update script doen't work for some reason, you can just manually change the `version` then change the `hash` to a wrong one like `sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=` (you cannot skip this step) and try to build it `nix-build -A ssh-mitm`. You should be able to get the correct hash in the error logs.

The commit message should be `ssh-mitm: 2.1.0 -> 3.0.1` or `python310Packages.ssh-mitm: 2.1.0 -> 3.0.1`, please take a look at [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md) for more info :bow:

> Is it the hash value (SHA-256) from the source archive?

The hash is calculated **after** unpacking the source.

**Comment by fabaff** [comment]
> @fabaff can you help me to update the nix package to the latest version of SSH-MITM, please

`nix-update` should work here.

**Comment by SuperSandro2000** [comment]
linked PR merged instead

**Pull request closed without merging**
