### PR TITLE
fwupd: 1.0.5 update & cleanups

### LINKED ISSUE #32142: nixos/fwupd: prevent build during evaluation
## Issue description
The fwupd module is trying to obtain list of files inside the package causing build during evaluation. See: https://github.com/NixOS/nixpkgs/pull/30252#discussion_r153038794

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
Update fwupd, fwupdate, libsmbios and umockdev; clean up #35011, fix #32142, https://github.com/NixOS/nixpkgs/issues/35072, re-enable test.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jtojnar** [comment]
@GrahamcOfBorg test fwupd

**Comment by jtojnar** [comment]
@GrahamcOfBorg test fwupd

**Comment by jtojnar** [comment]
@GrahamcOfBorg test fwupd

**Comment by dtzWill** [comment]
This fixes two problems for me:
* thunderbolt timeout in test (as you mention)
* doesn't just hang when I request it perform an update! :+1: 

First update attempt it refused because I wasn't on A/C, great,
this time around it fails due to an attempt to write to the nix store (instead of system equivalent?):

```
UEFI firmware update failed: {error #0} libfwup.c:1513 get_fd_and_media_path(): mkostemps(/nix/store/hkw69gi94wq50adlpdyqi63iiy5wyk9q-fwupdate-10/boot/EFI/nixos/fw/fwupdate-5KbgKy.cap) failed: Read-only file system
```

Which would appear to be the result of setting `ESPMOUNTPOINT` to` $out/boot`:
https://github.com/NixOS/nixpkgs/pull/35065/commits/bba87ad763a74ac2217d0290c6860798ade5e8f5#diff-529194568589c1038f6ec87fc87f2397R27

Dropping this variable causes the fwupdate installation to fail, as it attempts to copy "fw-update" onto /boot"... which is of course no good either.

I'm not sure of a good solution, and since previous versions of fwupd didn't work I'm not sure if this is a regression in terms of functionality on NixOS or not.  If it's not or it's too difficult to fix I understand, but thought I'd report anyway :+1:.

**Comment by jtojnar** [comment]
@GrahamcOfBorg test fwupd

**Comment by jtojnar** [comment]
@GrahamcOfBorg eval

**Comment by dtzWill** [comment]
re: [comments made earlier](https://github.com/NixOS/nixpkgs/pull/35065#issuecomment-366556815), this issue seems rather relevant:

https://github.com/rhboot/fwupdate/issues/97

**Comment by jtojnar** [comment]
@GrahamcOfBorg test fwupd

**Comment by dtzWill** [comment]
Thanks for working on this!

**Comment by jtojnar** [comment]
The EFI issue existed previously as well and yes, rhboot/fwupdate#97 might fix it.

The borg anomaly we will ignore for now https://github.com/NixOS/ofborg/issues/84

**Comment by Moredread** [comment]
It looks like the esp path can be set by a config file as well, so that might be a fix for the time till the upstream issue is fixed.

See i.e. https://wiki.archlinux.org/index.php/Fwupd#Running_fwupd

**Comment by Moredread** [comment]
With the changes in https://github.com/Moredread/nixpkgs/commit/67250f386d73e4a71b30271a6e1b09f7566442d1 it fails now with

```
> fwupdmgr update 
Downloading 0.1.2.1 for XPS 13 9370 System Firmware...
Updating 0.1.2.1 on XPS 13 9370 System Firmware...
Decompressing…         [***************************************]
Authenticating…        [***************************************]
Scheduling…            [***************************************]
UEFI firmware update failed: {error #0} libfwup.c:1513 get_fd_and_media_path(): mkostemps(/boot/EFI/nixos/fw/fwupdate-2BaElw.cap) failed: Read-only file system
```

**Comment by Moredread** [comment]
When mounting the boot partition with full permissions (i.e. mount flags 'fmask=0000,dmask=0000') it works. :)

I overlooked that before, as I only tried chmod-ing the EFI directories. I guess that doesn't work correctly with a vfat filesystem?

Does someone know under which user the fwupd process is run?

**Comment by jtojnar** [comment]
It runs as root on my system.

**Comment by abrooks** [comment]
Is this issue sufficiently fixed? Is it ready to be merged in to master? Is there anything I can do to help move it along?

**Comment by jtojnar** [comment]
https://github.com/NixOS/nixpkgs/pull/39792@abrooks follow https://github.com/NixOS/nixpkgs/issues/39386 and

**Comment by abrooks** [comment]
@jtojnar I was following #39386 but missed #39792. Thanks for pointing me to that PR.

**Pull request merged**
