### PR TITLE
tree-sitter: update grammars

### PR DESCRIPTION
**Pull request by siraben**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 165178` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>20 packages built:</summary>
  <ul>
    <li>tree-sitter-grammars.tree-sitter-clojure</li>
    <li>tree-sitter-grammars.tree-sitter-cpp</li>
    <li>tree-sitter-grammars.tree-sitter-cuda</li>
    <li>tree-sitter-grammars.tree-sitter-dockerfile</li>
    <li>tree-sitter-grammars.tree-sitter-dot</li>
    <li>tree-sitter-grammars.tree-sitter-elixir</li>
    <li>tree-sitter-grammars.tree-sitter-erlang</li>
    <li>tree-sitter-grammars.tree-sitter-fennel</li>
    <li>tree-sitter-grammars.tree-sitter-fish</li>
    <li>tree-sitter-grammars.tree-sitter-haskell</li>
    <li>tree-sitter-grammars.tree-sitter-java</li>
    <li>tree-sitter-grammars.tree-sitter-latex</li>
    <li>tree-sitter-grammars.tree-sitter-markdown</li>
    <li>tree-sitter-grammars.tree-sitter-nix</li>
    <li>tree-sitter-grammars.tree-sitter-norg</li>
    <li>tree-sitter-grammars.tree-sitter-perl</li>
    <li>tree-sitter-grammars.tree-sitter-prisma</li>
    <li>tree-sitter-grammars.tree-sitter-rust</li>
    <li>tree-sitter-grammars.tree-sitter-vim</li>
    <li>tree-sitter-grammars.tree-sitter-zig</li>
  </ul>
</details>

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 165178` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>20 packages built:</summary>
  <ul>
    <li>tree-sitter-grammars.tree-sitter-clojure</li>
    <li>tree-sitter-grammars.tree-sitter-cpp</li>
    <li>tree-sitter-grammars.tree-sitter-cuda</li>
    <li>tree-sitter-grammars.tree-sitter-dockerfile</li>
    <li>tree-sitter-grammars.tree-sitter-dot</li>
    <li>tree-sitter-grammars.tree-sitter-elixir</li>
    <li>tree-sitter-grammars.tree-sitter-erlang</li>
    <li>tree-sitter-grammars.tree-sitter-fennel</li>
    <li>tree-sitter-grammars.tree-sitter-fish</li>
    <li>tree-sitter-grammars.tree-sitter-haskell</li>
    <li>tree-sitter-grammars.tree-sitter-java</li>
    <li>tree-sitter-grammars.tree-sitter-latex</li>
    <li>tree-sitter-grammars.tree-sitter-markdown</li>
    <li>tree-sitter-grammars.tree-sitter-nix</li>
    <li>tree-sitter-grammars.tree-sitter-norg</li>
    <li>tree-sitter-grammars.tree-sitter-perl</li>
    <li>tree-sitter-grammars.tree-sitter-prisma</li>
    <li>tree-sitter-grammars.tree-sitter-rust</li>
    <li>tree-sitter-grammars.tree-sitter-vim</li>
    <li>tree-sitter-grammars.tree-sitter-zig</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
This update broke tree-sitter in nix files for me.

20220325_01h24m02s_grim

**Comment by siraben** [comment]
Likely due to https://github.com/cstrahan/tree-sitter-nix/commit/14af97221e59b355e421f71f94bf302f860267a8

**Comment by siraben** [comment]
Looks like dramatic changes to the nodes, I can rollback the update for the Nix grammar for now.

**Comment by siraben** [comment]
@mweinelt I cannot reproduce this in Emacs. The queries for the grammar also seem to have been updated to reflect the node changes.

**Comment by mweinelt** [comment]
I reverted the update and everything was fine again, so I don't know how I could help debug this further.

**Pull request merged**
