### PR TITLE
bear: fix

### PR DESCRIPTION
**Pull request by DieracDelta**
## Description of changes

A continuation of #238531. Fixes bear such that that it runs on aarch64-darwin.

## Things done
I cherry picked the commits from #238531, then added another commit to remove the broken marker for bear on darwin. I can squash the commits together if that's better.

I tested on aarch64-darwin by running bear when building `nix`. `compile_commands.json` was generated and was non-empty.

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Atemu** [comment]
I no longer have a setup to use Bear in any meaningful way but the diff LGTM and it runs successfully on aarch64-darwin.

**Review by babariviere — APPROVED** [review]

**Review by thiagokokada — APPROVED** [review]

**Review by thiagokokada — COMMENTED** [review]
It seems the tests are failing in CI, maybe because of timeout issues?

**Comment by DieracDelta** [comment]
I think some of the tests are broken. Maybe we could disable the tests for now and fix them later. This would let us get a working bear merged. WDYT?

**Comment by thiagokokada** [comment]
> I think some of the tests are broken. Maybe we could disable the tests for now and fix them later. This would let us get a working bear merged. WDYT?

Fine for me.

**Comment by Atemu** [comment]
Are you still going to do that in this PR or in a follow-up?

**Comment by DieracDelta** [comment]
I believe I've disabled the tests by added `doCheck = false`. I'm not super familiar with how Cmake works, though. Will wait to see what CI says.

**Comment by DieracDelta** [comment]
Hmm that doesn't seem to have worked. Does anyone know how to disable those tests? If not, I'll revert the docheck change and let's merge it?

**Comment by DieracDelta** [comment]
It looks like those cmake flags helped, except on x86_64-darwin. Not sure how to fix that. In any case, this is probably fine to merge.

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 279035` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>bear</li>
  </ul>
</details>

**Pull request merged**
