### PR TITLE
oil: 0.17.0 -> 0.18.0

### PR DESCRIPTION
**Pull request by a12l**
## Description of changes

Oil is a new Unix shell that's under heavy development.

https://www.oilshell.org/release/0.18.0/changelog.html

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Melkor333** [comment]
It would probably make sense to rename the package to `oils` (and maybe keep `oil` with a deprecationwarning if that's possible).

**Review by nagy — APPROVED** [review]

**Comment by nagy** [comment]
> It would probably make sense to rename the package to `oils`

I dont understand. Why ?

**Comment by nagy** [comment]
@a12l Could you maybe also add `mainProgram = "oil";` in the meta section ?

**Comment by sullyj3** [comment]
> I dont understand. Why ?

The project has been [renamed](https://www.oilshell.org/blog/2023/03/release-0.14.2.html).

> Could you maybe also add mainProgram = "oil"; in the meta section ?

 `oil` the program has also been renamed to `ysh`. `oil` still works for now, but will be deprecated.
Separately, the project includes both `ysh` (compatibility breaking, cool new features) and `osh` (posix compliant, more limited). I'm not sure if it really makes sense to call either one the main program, from my perspective they have approximately equal status.

**Comment by nagy** [comment]
Good to know, thanks. Then maybe `mainProgram = "ysh";` would be more appropriate.

**Comment by Melkor333** [comment]
> Good to know, thanks. Then maybe `mainProgram = "ysh";` would be more appropriate.

I'd argue `osh` is the main peogram, as `ysh` is "osh with `shopt --set ysh:all`. But I asked the main dev on [zulip](https://oilshell.zulipchat.com/#narrow/stream/325160-oil-discuss-public/topic/Main.20Program.20for.20nix)

**Comment by andychu** [comment]
Oils author here -- since this is still the Python tarball, I think it's OK to keep things the same

Not here:

https://www.oilshell.org/release/0.18.0/

- the Python tarball is called `oil-$VERSION`, and in the long term it will go away
- the C++ tarball is called `oils-for-unix-$VERSION` should be packaged separately

What is the idea behind `mainProgram` ?

The best analogy is busybox -- there is no main program really.  Or the main program is not the useful one.

There are multiple main programs, the two primary ones being:

- osh
- ysh

**Comment by andychu** [comment]
Basically for the Python tarball, it's OK to keep everything the same, but `oil` -> `ysh` is fine to reduce confusion

The real changes will come with a **separate** package for the C++ tarball

**Comment by sullyj3** [comment]
Afaict `mainProgram` determines which executable `nix run nixpkgs#oil` runs. I was going to mention earlier that neither ysh nor osh really have higher status, but imo you might as well pick one arbitrarily to get some of that benefit.

**Comment by sullyj3** [comment]
It seems like `mainProgram` [determines which executable `nix run nixpkgs#oil` runs](https://nixos.org/manual/nixpkgs/stable/#var-meta-mainProgram). I was going to mention earlier that neither `ysh` nor `osh` really have higher status, but imo picking one arbitrarily to get that benefit is better than picking neither.

**Comment by andychu** [comment]
Hm well there is currently no mainProgram there now?  It seems OK to leave it out

The only thing that has changed about the Python tarball recently is that it has a `ysh` symlink instead of `oil`, to reflect the new renaming

So I guess  I would test if `ysh -c 'echo hi'` works with this package, as a sanity check

and `osh -c 'echo hi'`

---

I think it's confusing that it's called `oil` -- is Oil  osh or ysh?    So I think picking a default just adds to confusion

It makes sense for people to just pick osh or ysh explicitly, based on what they want

**Comment by sullyj3** [comment]
It seems strange that `nix run` doesn't include a mechanism for easily running a specific binary from a package of multiple binaries. At least you can do `nix shell nixpkgs#oil -c ysh`

**Comment by a12l** [comment]
@nagy What's your current opinion of this?

**Comment by nagy** [comment]
It's fine like it is, we can change things later.

**Comment by happysalada** [comment]
Hey ive merged to not delay the update to the new version. I think we can make subsequent PRs if anyones feels we should add more to this.

**Pull request merged**
