### PR TITLE
[staging] diffutils: 3.9 -> 3.10

### PR DESCRIPTION
**Pull request by dasJ**
Fixes the issue introduced in 3.9 and makes cmp and diff work past Y2K39.

Release announcement: https://savannah.gnu.org/news/?id=10368

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by trofi — APPROVED** [review]

**Comment by reckenrode** [comment]
diffutils 3.10 appears to hang on Rosetta 2 during the `test-c-stack` test like gnugrep 3.11 does. I expect this is going to be an issue with anything using gnulib and the `test-c-stack` test under Rosetta 2.

**Comment by vcunat** [comment]
Do you know if someone's reached out to upstream (gnulib) about this?  (so that we could at least hope for improvement in further future)

**Comment by reckenrode** [comment]
> Do you know if someone's reached out to upstream (gnulib) about this? (so that we could at least hope for improvement in further future)

Not as far as I’m aware. I don’t see anything on the bug-gnulib mailing list. There doesn’t appear to be an official issue tracker. I’d say I’m surprised this didn’t affect the coreutils update, but it appears its tests are disabled on Darwin.

**Comment by vcunat** [comment]
For this staging-next iteration [we got lucky](https://hydra.nixos.org/build/223928772#tabs-buildsteps) to build rosetta-free, but I expect we'll need a workaround soon.

**Comment by vcunat** [comment]
It also fails with musl:
https://hydra.nixos.org/build/223912323/nixlog/69/tail

**Comment by alyssais** [comment]
Only on aarch64.  Probably because aarch64-musl is still using an ancient bootstrap, but I haven't investigated yet.

**Pull request merged**
