### PR TITLE
rink: 0.4.5 -> 0.5.0

### PR DESCRIPTION
**Pull request by dywedir**
###### Motivation for this change

https://github.com/tiffany352/rink-rs/releases/tag/v0.5.0

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by typetetris** [comment]
Result of `nixpkgs-review pr 93404` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
<br>- rink
</details>

**Comment by typetetris** [comment]
[x] version fits guideline
[x] commit text fits guidelines
[x] package maintainers are notified
[x] meta field information is correct
[x] code contains no typos
[x] package built / executable was run

**Comment by typetetris** [comment]
Cool stuff, didn't know about rink. Every physics student should know about that!

**Review by typetetris — APPROVED** [review]
Looks good to me

**Review by Br1ght0ne — APPROVED** [review]
LGTM.

Thanks @dywedir for the PR and @typetetris for the detailed review!

**Comment by sbourdeauducq** [comment]
> Every physics student should know about that!

More experienced physicists also use it :)

**Pull request merged**
