### PR TITLE
starboard: 0.9.1 -> 0.9.2

### PR DESCRIPTION
**Pull request by 06kellyjac**
###### Motivation for this change

Bump starboard to `0.9.2`

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 06kellyjac** [comment]
Result of `nixpkgs-review pr 113182` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>starboard</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 113182` at 280af4d8 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li><a href="https://gist.github.com/4ec25018e77468c7e3017052c24a26cf">starboard</a></li></li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>error: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/no-flags-array.md">no-flags-array</a>

`buildFlagsArray` is only intended to be used in Bash, not as a Nix attribute.

Near pkgs/applications/networking/cluster/starboard/default.nix:20:3:
```
   |
20 |   buildFlagsArray = [
   |   ^
```
</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 113182` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>starboard</li>
  </ul>
</details>

**Review by fabaff — APPROVED** [review]
Change log: https://github.com/aquasecurity/starboard/releases/tag/v0.9.2

- [x] package build (see https://github.com/NixOS/nixpkgs/pull/113182#issuecomment-779150124)
- [ ] all depending packages build
- [x] tested on x86_64

```bash
...ew/pr-113182]$ ./results/starboard/bin/starboard version
Starboard Version: {Version:v0.9.2 Commit:none Date:unknown}
...ew/pr-113182]$ ./results/starboard/bin/starboard
Kubernetes-native security toolkit

Usage:
  starboard [command]

Available Commands:
  cleanup     Delete Kubernetes resources created by Starboard
[...]
```

Looks good to me.

**Pull request merged**
