### PR TITLE
python3Packages.pymc: 5.10.4 -> 5.13.0

### PR DESCRIPTION
**Pull request by ferrine**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ferrine** [comment]
@nidabdella anything else to change in the PR?

**Comment by ferrine** [comment]
@nidabdella meanwhile pymc and it's dependency have updated already, attaching the commits here

**Comment by ferrine** [comment]
going to bump pymc to the latest 5.13, this will require a release for https://github.com/NixOS/nixpkgs/blob/b987e0c6ad592b74332c4e3c25874a17bcfdc451/pkgs/development/python-modules/bambi/default.nix#L18
CC @tomicapretto

**Comment by ferrine** [comment]
so far there are the following issues with upgrade 

```
warning: Git tree '/home/ferres/nixpkgs' is dirty
error: builder for '/nix/store/c26dzd7y9xd687s7q12zfkrin387lyj9-python3.11-pymc-5.13.1.drv' failed with exit code 1;
       last 10 log lines:
       >   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
       >   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
       >   File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
       >   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
       >   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
       >   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
       >   File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
       > ModuleNotFoundError: No module named 'setuptools'
       >
       > ERROR Backend 'setuptools.build_meta:__legacy__' is not available.
       For full logs, run 'nix log /nix/store/c26dzd7y9xd687s7q12zfkrin387lyj9-python3.11-pymc-5.13.1.drv'.
```

**Comment by pbsds** [comment]
Result of `nixpkgs-review pr 296665` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
    <li>python312Packages.pytensor</li>
    <li>python312Packages.pytensor.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymc.dist</li>
    <li>python311Packages.pytensor</li>
    <li>python311Packages.pytensor.dist</li>
  </ul>
</details>

python311Packages.bambi fails in checkPhase which is an improvement over the [current transitive failure](https://hydra.nixos.org/build/257771465), python312Packages.pytensor is [expected to fail](https://hydra.nixos.org/build/257774221) due to tensorflow

LGTM, but still want to see the results from ofborg

@ofborg build python311Packages.pymc python311Packages.pymc.passhtru.tests

**Comment by pbsds** [comment]
wow unlucky, merge conflict with https://github.com/NixOS/nixpkgs/pull/307492

**Comment by GaetanLepage** [comment]
I had this in the loop already: https://github.com/NixOS/nixpkgs/pull/294574

**Comment by pbsds** [comment]
> I see, we'll need to wait for bambi, they are planing to cut a release quite soon to fully support pymc 5.13

Already broken on master https://hydra.nixos.org/build/257771465, hence not a blocker here. Looking forward to the update

**Comment by ferrine** [comment]
thanks! As for bambi, it takes too long indeed

**Comment by GaetanLepage** [comment]
> thanks! As for bambi, it takes too long indeed

Would you mind if we mark bambi as broken ?
Tracking issue: https://github.com/NixOS/nixpkgs/issues/310940

**Pull request closed without merging**
