### PR TITLE
apt: init at 1.8.4

### PR DESCRIPTION
**Pull request by JordiPlayGames**
###### Motivation for this change

Add apt to all-packages.nix.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by JordiPlayGames** [comment]
#110346

**Comment by OPNA2608** [comment]
Hi, thanks for fixing this! Could you squash the commits down into one and rename it `apt: init at 1.8.4` please?

Result of `nixpkgs-review pr 120044` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>apt</li>
  </ul>
</details>

**Comment by JordiPlayGames** [comment]
I cannot squash the commits, but i need to add apt to all-packages.nix.

**Comment by SuperSandro2000** [comment]
The resulting binary does not work so it should probably be removed all together.

**Comment by AndersonTorres** [comment]
Already done!

**Pull request closed without merging**
