### PR TITLE
[21.11] Twisted backport

### PR DESCRIPTION
**Pull request by lheckemann**
###### Description of changes

Closes #165706

###### Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
    - [x] matrix-synapse.nix
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
On nixos x86_64 & macos 10.15:

```
builder for '/nix/store/8hlilp0pfm8zrfid4vllifndyg8glbc8-python3.9-txtorcon-21.1.0.drv' failed with exit code 1; last 10 log lines:
      return self.suiteFactory([self.findByName(name, recurse=recurse)])
    File "/nix/store/w6jnkqzq2z7q1l3hwi1dfq45dh31wnn5-python3.9-Twisted-22.4.0/lib/python3.9/site-packages/twisted/trial/runner.py", line 492, in findByName
      raise AttributeError(f"{name} does not exist.")
  builtins.AttributeError: test.test_web.WebAgentTests.test_socks_agent_unix does not exist.
  
  test.test_web.WebAgentTests.test_socks_agent_unix
  -------------------------------------------------------------------------------
  Ran 680 tests in 1.588s
  
  FAILED (errors=680)
```

**Comment by lheckemann** [comment]
Cherry-picked a bump and fix from master for txtorcon.

**Comment by lheckemann** [comment]
@ofborg test matrix-synapse

**Comment by mweinelt** [comment]
Tested magic-wormhole as another consumer of the twisted/txtorcon triangle.

**Pull request merged**
