### PR TITLE
postgresql_15: init at 15.0

### PR DESCRIPTION
**Pull request by ankhers**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ankhers** [comment]
There is a checkbox for testing all binaries. I have not done this. But I have enabled pg15 as the database on my local machine and basic functionality seems to work.

**Comment by bachp** [comment]
This seems to be a duplicate of https://github.com/NixOS/nixpkgs/pull/195852 which also changes the default postgres.

**Comment by techknowlogick** [comment]
@bachp mine was in fact the dupe, and so I've closed it.

**Comment by bachp** [comment]
@techknowlogick In your PR you also changed the default postgresql derivation. This is missing here.

**Comment by ankhers** [comment]
I made the decision to not change the default postgres version here as I am not one of the maintainers and do not know what the release process should be. For reference, in Elixir and Erlang, we chose to not make the latest version the default immediately on release. At least that is what it used to be when I was a bit more active.

If the maintainers would like for me to bump the default postgres version, I would be more than happy to make that modification.

**Review by marsam — APPROVED** [review]

**Pull request merged**
