### PR TITLE
NixOS/evalModules legacy cleanup

### PR DESCRIPTION
**Pull request by roberth**
###### Motivation for this change

The supposedly legacy `args` flags was still used and was not passed along correctly. This PR fixes this at the module system level, at the NixOS level and in the documentation module. While only one of these would be sufficient to solve the issue, it is clear that we should get rid of the redundant code.

 - First and foremost, address the issue raised in https://github.com/NixOS/nixpkgs/pull/144094#issuecomment-984623393.

 - Deprecate the legacy parameters that, combined with #144094, created the problem.
 
 - Simplify the documentation module and make it more complete and accurate.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - **The fix is to simplify, so that a new test case is not necessary**
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FlorianFranzen** [comment]
This seems to fix #148343 for me.

**Review by infinisil — APPROVED** [review]
Nice cleanup! I can confirm that this fixes specialisations

**Comment by nh2** [comment]
@roberth @infinisil There is one location remaining in nixpkgs that sets these deprecated `args` and `check`:

https://github.com/NixOS/nixpkgs/blob/0ed41137b76534003507b55dfe214ae56c30e021/lib/modules.nix#L1073-L1074

Could/should this be rewritten?

**Comment by infinisil** [comment]
@nh2 `fixMergeModules` should really be fully deprecated, could you try that? It looks like Nixops [still uses it](https://github.com/NixOS/nixops/blob/fc9b55c55da62f949028143b974f67fdc7f40c8b/flake.nix#L82) even though it should've been removed [some time ago](https://github.com/NixOS/nixops/pull/1506), so a Nixops PR to remove that would be good. Nixpkgs would have to wait a bit with deprecation then though

**Pull request merged**
