### PR TITLE
Update to newer libtoxcore and uTox

### PR DESCRIPTION
**Pull request by DamienCassou**

### CODE REVIEW

**Comment by geerds** [comment]
Did you check all other packages that depend on libtoxcore? It's sometime a bit fragile because they only provide nightly versions

**Comment by jagajaga** [comment]
What about travis errors? :(

**Comment by domenkozar** [comment]
`ratox` doesn't compile

**Comment by domenkozar** [comment]
@DamienCassou are you going to open another PR?

**Comment by DamienCassou** [comment]
@domenkozar only if others really want me to. I don't care so much about this patch as I don't use these tools. It would be better if someone who uses them to the work and check.

**Comment by domenkozar** [comment]
I might come back to it.

**Comment by geerds** [comment]
I think we should wait until this bug is fixed: https://github.com/jin-eld/tox-prpl/issues/54

Otherwise we would have to maintain two libtoxcore versions because tox-prpl doesn't work with latest master.

**Comment by geerds** [comment]
On the other side: Does anyone use tox-prpl? This derivation has no maintainer

**Comment by akaWolf** [comment]
Anyway, there is one more package, which using old api: ratox.
#8563 -- added 2 versions of libtoxcore.

**Comment by DamienCassou** [comment]
Can I close this PR? I have the impression nobody cares (and I certainly don't anymore).

**Comment by akaWolf** [comment]
@DamienCassou,
as you can see here, https://github.com/NixOS/nixpkgs/pull/13019
we are still maintaining two versions of libtoxcore.
http://git.2f30.org/ratox/log.html have no new commits.
https://github.com/jin-eld/tox-prpl/issues/54 isn't done yet.
so...

**Comment by zimbatm** [comment]
Closing for now. Please re-open if there is any interest.

**Pull request closed without merging**
