### PR TITLE
update URL of apple-sdk-11

### PR DESCRIPTION
**Pull request by xofyarg**
The previous one is outdated, this updates it to 11.1.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by domenkozar** [comment]
@thefloweringash

**Comment by thefloweringash** [comment]
Change LGTM, commit message needs to follow [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes)

**Comment by xofyarg** [comment]
Commit message updated.

**Comment by rb2k** [comment]
Since the URL is dead, it's probably reasonable to backport this to 21.05, right?
Otherwise 21.05 will fail for people trying to compile things from scratch

Attempt: #132608

**Pull request merged**
