### PR TITLE
renderdoc: 1.18 -> 1.19 + 

### PR DESCRIPTION
**Pull request by jansol**
###### Description of changes

https://github.com/baldurk/renderdoc/releases/tag/v1.19

Finally figured out where to place the PySide stuff so CMake finds it at build time so plugins should now work fully.

Unfortunately Wayland is not really supported nor are some Vulkan extensions that have been critical for me for a long time now, and upstream has explicitly said they aren't planning to work on either so for the time being renderdoc is unusable for me and this'll be the last update I do for it.

@Ralith wanna take over the package? AFAIK you have more use for this than I do these days and lately the updates have been pretty trivial so r-ryantm *should* get them anyway.

###### Things done

Tried tried capturing vkcube (X11-only application) via CLI and running the GUI with `QT_QPA_PLATFORM=xcb` to inspect the capture, both worked without a hitch. Tried out the "where is my draw" example plugin to verify that python stuff works. No problems with that either.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ralith** [comment]
> @Ralith wanna take over the package? AFAIK you have more use for this than I do these days and lately the updates have been pretty trivial so r-ryantm should get them anyway.

Sure, I won't be closely tracking releases but I am indeed a regular user still.

**Comment by onny** [comment]
Please rebase

**Comment by jansol** [comment]
Closing as obsolete - nixpkgs already has version 1.21

**Comment by Ralith** [comment]
The version in master still doesn't seem to have pyside to wired up. Would be nice to get that in; I don't have any idea how it works myself.

**Comment by jansol** [comment]
I'm not sure if I ever figured out how to actually verify that it works at run time, but IIRC the change here made CMake pick up the fact that pyside is available.

**Comment by Ralith** [comment]
So, should this be reopened (and rebased) to get that in?

**Comment by jansol** [comment]
Looks like github does not allow reopening PRs if there have been changes to the branch in between. Rebased & reopened as #191978

**Comment by Ralith** [comment]
Thanks!

**Pull request closed without merging**
