### PR TITLE
wayland: 1.20.0 -> 1.21.0

### PR DESCRIPTION
**Pull request by primeos**
Release announcements:
- Alpha: https://lists.freedesktop.org/archives/wayland-devel/2022-May/042194.html
- Beta: https://lists.freedesktop.org/archives/wayland-devel/2022-June/042228.html
- RC1: https://lists.freedesktop.org/archives/wayland-devel/2022-June/042261.html
- 1.21: https://lists.freedesktop.org/archives/wayland-devel/2022-June/042268.html

The URLs of the release tarballs did change as can be seen on the
website [0] (the old URL scheme doesn't work anymore).

[0]: https://wayland.freedesktop.org/releases.html

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
@ofborg eval

**Comment by fabianhjr** [comment]
Small nitpick: use `git mv` to keep the patch history trough the file rename instead of `git rm` and `git add`?

**Review by fabianhjr — APPROVED** [review]
Been using it for a day, haven't noticed any issues.

**Comment by alyssais** [comment]
> Small nitpick: use `git mv` to keep the patch history trough the file rename instead of `git rm` and `git add`?

That's not how git works.  Git stores directory structure at each commit, and detects renames dynamically by looking for similar files.  There's no actual rename tracking, and there's no difference between `mv` and `rm`/`add`.

**Review by alyssais — APPROVED** [review]

**Comment by primeos** [comment]
Thanks for the reviews :)

I was a bit surprised about all of the build warnings - I don't remember them from previous PRs but I get the same warnings with 1.20.0 so it should be "fine" (no new regressions). Examples:
```
[14/107] Generating doc/doxygen/xml/wayland-architecture.png with a custom command
Fontconfig error: Cannot load default config file: No such file: (null)
Fontconfig error: No writable cache directories
[...]
Writing apa.html for appendix(appe-Wayland-Protocol)
Error: no ID for constraint linkend: "Client-structwl__interface_1a3ee0780631cad42bcc90a8deb76caec8".
Error: no ID for constraint linkend: "Client-structwl__interface_1ac7b9bc6c0352b4100213109094ca55fa".
[...]
[20/107] Generating doc/doxygen/man-pages-3 with a custom command
/build/wayland-1.20.0/cursor/wayland-cursor.c:504: warning: argument 'cursor' of command @param is not found in the argument list of wl_cursor_frame(struct wl_cursor *_cursor, uint32_t time)
[...]
 [28/107] Generating doc/publican/sources/Architecture.xml with a custom command
warning: failed to load external entity "../doc/publican/images/x-architecture.map"
warning: failed to load external entity "../doc/publican/images/wayland-architecture.map"
```

They all seem to affect just the documentation. I'll try to take a closer look at this later (feel free to help out if you're interested). We can probably only do something about the Fontconfig error (and "failed to load external entity" - I haven't looked a the code yet but I guess those files should already exist).

My other checks were fine. I also run the following tests:
```console
$ nix-build -A pkgsCross.aarch64-multiplatform.wayland
/nix/store/k4j0irzfkd3f2d12kyfv0ijb7vkr09va-wayland-aarch64-unknown-linux-gnu-1.21.0
$ nix-build -A nixosTests.tinywl
/nix/store/w5dm8lxhkhvgwqrfcxyk37i41nc85d1r-vm-test-run-tinywl
# Sway but without the Pinentry part for now to avoid Qt rebuilds:
$ nix-build -A nixosTests.sway
/nix/store/gq6bax38wf867w7f7znz7l3scpd0rm8s-vm-test-run-sway
```

So this should be good to go :)

**Pull request merged**
