### PR TITLE
Update postgresql

### PR DESCRIPTION
**Pull request by matthiasbeyer**
###### Motivation for this change

As discussed in https://github.com/NixOS/nixpkgs/pull/15856#issuecomment-222691021

### CODE REVIEW

**Comment by groxxda** [comment]
CC: @ocharles

**Comment by ocharles** [comment]
I would be happy with all these changes.

**Comment by alanorth** [comment]
[PostgreSQL 9.3.13 has been out](https://www.postgresql.org/docs/9.3/static/release-9-3-13.html) for a few weeks. I came to submit a pull request but saw this one. This is what I have built locally (on Mac OS X):

```
diff --git a/pkgs/servers/sql/postgresql/default.nix b/pkgs/servers/sql/postgresql/default.nix
index bd7b8fd..df44d78 100644
--- a/pkgs/servers/sql/postgresql/default.nix
+++ b/pkgs/servers/sql/postgresql/default.nix
@@ -86,9 +86,9 @@ in {
   };

   postgresql93 = common {
-    version = "9.3.11";
+    version = "9.3.13";
     psqlSchema = "9.3";
-    sha256 = "08ba951nfiy516flaw352shj1zslxg4ryx3w5k0adls1r682l8ix";
+    sha256 = "0ax7cb1lknzz4105spi8k71n71rb4jp00d2kscasifgxkg9f2i2m";
   };

   postgresql94 = common {
```

I don't use any other PostgreSQL versions so I haven't tested anything other than 9.3.x.

**Comment by paraseba** [comment]
This looks good to me.

I want to use the opportunity to ask a question, anybody here has opinions on the best way to fix #15512 

Postgis extension is broken after the multiple outputs patch. Regrouping everything under a single output would fix it, but it's probably not something we want to do? Should we create a new package that contains both postgres and any extensions (the way the NixOs module does)?

**Pull request merged**
