### PR TITLE
agdaPackages.standard-library: 1.7.3 -> 2.0

### PR DESCRIPTION
**Pull request by ncfavier**
https://github.com/agda/agda-stdlib/blob/v2.0/CHANGELOG.md

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by turion** [comment]
@ofborg build agdaPackages.standard-library.passthru.tests

**Review by alexarice — CHANGES_REQUESTED** [review]
We should add the `--include-deprecated` flag on the call to `GenerateEverything.hs`. This means that if you use a deprecated module the warnings actually show up instead of giving an error about things not being built

**Review by alexarice — APPROVED** [review]

**Comment by turion** [comment]
It seems that this would break `agda-categories`. Can we give them some time & warning to update their library before merging?

**Comment by turion** [comment]
Upstream issue is https://github.com/agda/agda-categories/issues/405, if there is no progress in, say, a week or so, I'm happy to merge. But if there is some promising progress, I think we should bump both libraries jointly.

**Comment by alexarice** [comment]
It's worth noting that this version is a large non backwards compatible change

**Comment by ncfavier** [comment]
Sure, I wasn't planning to merge this right away. `agdarsec` and `functional-linear-algebra` are also failing; opened https://github.com/gallais/agdarsec/issues/33 and https://github.com/ryanorendorff/functional-linear-algebra/issues/50.

**Comment by ryanorendorff** [comment]
Updated the functional-linear-algebra package to work with the 2.0 version of the library. Thanks for the heads up.

**Comment by ncfavier** [comment]
Can confirm HEAD builds. Are you planning to make a new release or should we bump to HEAD?

**Comment by ryanorendorff** [comment]
Just pushed tag `v0.5.0` works (which is `HEAD`), so if that could be used that would be great. Thanks!

**Comment by alexarice** [comment]
agda-categories has a new release, so we can probably go ahead with this update now

**Comment by ncfavier** [comment]
Bumped agda-categories. No response from agdarsec, so we might as well mark it broken.

-----------

I had to increase the maximum heap for building agda-categories after the update. Weirdly enough, this is the *third* Agda project that has recently started exceeding the maximum heap size, but this doesn't seem to be correlated to the Agda 2.6.4.1 bump... Does anyone have an explanation, or is this just a funny coincidence?

**Review by turion — APPROVED** [review]

**Comment by turion** [comment]
> Does anyone have an explanation, or is this just a funny coincidence?

It might be worth checking whether this is due to the recent agda version bump, the agda-stdlib version bump, or the agda-categories version bump. I have no explanation, though.

**Comment by alexarice** [comment]
Could it also be a ghc change? I always remember agda being happy to consume way more than 4gb ram

**Pull request merged**
