### PR TITLE
go, buildGoModule, buildGoPackage: default to 1.20

### PR DESCRIPTION
**Pull request by zowoq**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

https://go.dev/doc/go1.20

### CODE REVIEW

**Comment by Kranzes** [comment]
This should go to staging.

**Comment by zowoq** [comment]
> This should go to staging.

When it is ready to be merged it will go to staging.
____

cc @NixOS/golang

Seems vendor hashes are stable this time which makes for a nice change, only need to deal with broken builds and nixosTests.

Like usual will probably end up waiting for 1.20.1 before moving forward with this to try and avoid any potential problems but we'll see what 1.20 is like.

**Review by saschagrunert — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
> Seems vendor hashes are stable this time which makes for a nice change, only need to deal with broken builds and nixosTests.

What about my recent changes to add more pre and post phases? Maybe a good opportunity to check for outfalls.

**Comment by zowoq** [comment]
> What about my recent changes to add more pre and post phases?

Here's what I found that has a broken vendor hash after that change.

```
cue
docker-compose
gocryptfs
goofys
ijq
pistol
shfmt
```

**Comment by qbit** [comment]
Not bad! Do they just need an updated hash?

**Comment by zowoq** [comment]
>  Do they just need an updated hash?

Probably not, the build needs to be adjusted and then the vendor hash doesn't change. e.g.

```diff
diff --git a/pkgs/tools/text/shfmt/default.nix b/pkgs/tools/text/shfmt/default.nix
index a4cdcaa6121..54e39c3be63 100644
--- a/pkgs/tools/text/shfmt/default.nix
+++ b/pkgs/tools/text/shfmt/default.nix
@@ -19,7 +19,7 @@ buildGoModule rec {
 
   nativeBuildInputs = [ installShellFiles scdoc ];
 
-  postBuild = ''
+  preInstall = ''
     scdoc < cmd/shfmt/shfmt.1.scd > shfmt.1
     installManPage shfmt.1
   '';

```

**Comment by zowoq** [comment]
1.20.1 is in master so I'll follow up on this in the next couple of weeks.

**Comment by zowoq** [comment]
@vcunat Would it be possible to get a jobset to check x86_64-linux nixosTests?

**Comment by vcunat** [comment]
There are many go-related ``nixosTests.*` ?  If there aren't too many, I think it's better to run just those.

**Comment by zowoq** [comment]
> I think it's better to run just those.

I don't understand?

**Comment by zowoq** [comment]
@vcunat If you're telling me to go through them manually there are enough tests that it's a hassle, that's why I'm asking for a jobset.

**Comment by vcunat** [comment]
I thought of running them myself, but anyway - hard to discuss, let me make Hydra build the 2k tests: https://hydra.nixos.org/jobset/nixos/pr-208706-go-1.20

**Comment by zowoq** [comment]
@vcunat Thank you, the jobset can be disabled now.

**Comment by zowoq** [comment]
Not much breakage, I'll merge this PR to staging now and do a follow up PRs on master to pin these:

```
boulder
browserpass
cloudflared
dnsproxy
ent-go
enumer
erigon
eris-go
gomplate
gost
grafana-agent
grafana-loki
gsctl
hyperledger-fabric
ipfs-cluster
kube-router
kubo
ligolo-ng
mgmt
mimir
miniflux
o
ooniprobe-cli
open-policy-agent
pcp
prometheus
protonmail-bridge
syncthing
tinygo
toxiproxy
unifiedpush-common-proxies
unparam
victoriametrics
```

**Comment by zowoq** [comment]
@ofborg eval

**Pull request merged**
