### PR TITLE
nixos/neovim: fix remote plugin manifest generation

### PR DESCRIPTION
**Pull request by liketechnik**
###### Description of changes

Stops using ex mode when running neovim for remote plugin manifest generation, since that leads to errors in more recent neovim versions with various plugins.

Relevant discussion in and fix for #189804 

###### Things done

Fix personally tested for `vim-polyglot` and with 
<details>
<summary>currently used in my configuration</summary>

- nvim-lspconfig
- vim-automkdir
- vim-vsnip
- vim-vsnip-integ
- nvim-cmp
- cmp-nvim-lsp
- cmp-buffer
- cmp-path
- cmp-calc
- cmp-spell
- cmp-emoji
- cmp-treesitter
- cmp-latex-symbols
- cmp-omni
- cmp-vsnip
- vim-grammarous
- vim-matchup
- NeoSolarized
- nerdtree
- nerdtree-git-plugin
- vim-commentary
- camelcasemotion
- vim-closetag
- vim-polyglot
- vim-surround
- vim-indent-guides
- gruvbox
- vim-repeat
- vim-airline
- rainbow
- vim-devicons
- nvim-web-devicons
- vim-shellcheck
- editorconfig-vim
- plantuml-syntax
- nvim-treesitter
- vim-gnupg
- base16-vim
- base16-vim-airline-themes
- vim-ledger
- plenary-nvim 
- telescope-nvim
- telescope-fzf-native-nvim
- gitsigns-nvim
- neorg
- trouble-nvim
- friendly-snippets

</details>

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by polarmutex** [comment]
Fix works in my neovim-flake

**Comment by teto** [comment]
Have you a better explanation/the commit responsible for that ? `-E` doesnt look needed here but still it would be nice to understand. Isn't that a vim-polyglot change ?

> Fix works in my neovim-flake

What does that mean ? nightly neovim ? neovim ?

**Comment by polarmutex** [comment]
AutoCommands that have the vim special variable "afile" are the ones that are broken like vim-polyglot and neogit when generating the rplugin.vim

Afile is replace with the file name of the current buffer when running the autocommand so running it in ex mode there is nothing to replace it with. 

The neovim commit that broke this (references in the issue) was a refactor in this area. I am not fully confident in my understanding of why this is happening now, but the commit looks right so I believe this needs fixed in nixpkgs. 

So if the -E command option is not needed I think that is the best solution. This is not just a problem in one plugin but any plugin using afile in autocommands and the neovim conmit that broke it looks correct for neovim

**Comment by MonAaraj** [comment]
what's blocking this merge? @teto @jonringer

**Review by subterfugue — APPROVED** [review]
Looks good from a bird's eye view.

**Comment by teto** [comment]
could you try a rebase to fix the ofborg-eval job ?

**Comment by liketechnik** [comment]
Done and seems like it did fix the eval job :)

**Pull request merged**
