### PR TITLE
awscli: backport 1.10.1 -> 1.10.46 to 16.03

### PR DESCRIPTION
**Pull request by grahamc**
###### Motivation for this change

awscli on 16.03 is quite old, and doesn't support several new features from AWS.
###### Things done
- [X] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [X] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

---

This change is [Reviewable](https://reviewable.io/reviews/nixos/nixpkgs/16924)

### CODE REVIEW

**Comment by grahamc** [comment]
FWIW, on 16.03 and master, the following derivations don't build with or without this change:

```
  /nix/store/vpnlj2p512lxwqdrgmrpr2xhd6p8pn5z-python2.7-boto3-1.2.2.drv
  /nix/store/ir563abgahncw9zqz9gl4z4dpsw5f80f-python2.7-aws-shell-0.1.0.drv
  /nix/store/j30snqmk0ya21yzl5pjkqzlr544895rf-python3.5-boto3-1.2.2.drv
```

but is triggering the travis failure. Because the problems exist in master, I definitely don't want to be fixing it in this PR.

**Comment by FRidh** [comment]
@grahamc I was able to build those packages with
```
nix-shell -p pythonPackages.aws_shell python35Packages.boto3 -I nixpkgs=. --pure
```
on 19a4935c5513575b8f1368f897f8721cbf2ddb4f.

**Comment by FRidh** [comment]
Adding 750db7ba9744ba24057da3f83ce2db50eb46d0b4 gets it to build at least.

**Comment by grahamc** [comment]
Updated to include @FRidh's changes.

**Comment by FRidh** [comment]
I've pushed it to 16.03.

**Pull request closed without merging**
