### PR TITLE
gitit: Remove staticDir and templatesDir

### LINKED ISSUE #9863: [gitit]: Cannot override staticDir or templatesDir
It tells me that these variables already exist in the configuration.

In fact, these variables are set [here](https://github.com/NixOS/nixpkgs/blob/d5505ae75732b3313015804b915aca30746767cd/nixos/modules/services/misc/gitit.nix#L646). I don't know why this needs to be done the way it is done, but I'd really like to be able to move my `staticDir` and `templatesDir` to other places.

### PR DESCRIPTION
**Pull request by matthiasbeyer**
as these cannot be overridden if specified here.

---

My attempt to fix #9863. I don't know whether this is a step in the right direction or not.

Ping to all haskellers I can find, because I have no clue who is responsible for the service file
**CC**: @gebner @gridaphobe @jb55 @khumba @psibi @ttuegel

### CODE REVIEW

**Comment by khumba** [comment]
(Disclaimer, I don't know about gitit.)  I see that there are config
options defined for those, and that the options are used in the
generated config file and the systemd service, but strangely, they're
hard-coded.  It conflicts if you try to set it without your patch,
right?  If so, looks fine to me, but I'd recommend setting `default`
attributes for `staticDir` and `templatesDir` to what they were
previously fixed to.

**Comment by matthiasbeyer** [comment]
@khumba Good idea!

**Comment by edwtjo** [comment]
As the author of the module I would like to have these options available, which I'm using in a private module. For nixpkgs, it was commit https://github.com/NixOS/nixpkgs/commit/99750d89dd962cc7011b02e487ed1a38c7842524 that essentially made them useless.

@khumba that would require evaluation of the haskellPackages set.

I would recommend setting them null by default and changing the type to nullOr. Also checking for null in the config inclusion.

**Comment by matthiasbeyer** [comment]
@edwtjo Sorry I do not understand your comment. Shall I set these options to `null` by default?

What's funny: As far as I can see, the path for the static and template dir is hard coded to the store itself in the service definition. And there is no way to override a service, is there? So this package is rather useless as-is.

**Comment by edwtjo** [comment]
@matthiasbeyer yes that is what I meant, but also modify configFile. Anyway these alterations will just be ugly hacks, let's avoid those on second thought.

> And there is no way to override a service, is there? So this package is rather useless as-is.

I'm not exactly sure what you mean but no 99750d89dd962cc7011b02e487ed1a38c7842524 was not a very good idea. So since @edolstra don't want the computational and storage overhead with the module; The only correct way to move forward is to remove gitit.nix from the module list, reverting 99750d89dd962cc7011b02e487ed1a38c7842524 and instead requiring it to be manually added into your configuration.nix. Which was done in 122d5e497e6df55f4b2e5c353bb2224b79cfd7b0 and aeba3eabcdbfa6308d9af27b2a70e7864ec4d3e3

**Pull request closed without merging**
