### PR TITLE
Darwin GSettings support

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
See https://github.com/NixOS/nixpkgs/issues/53307

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jtojnar** [comment]
For some reason, meson does not detect Darwin and passes `-Wl,-O1` to the compiler:

https://github.com/mesonbuild/meson/blob/bbcf80d7348135e0590622a7b85c30429f005c07/mesonbuild/compilers/compilers.py#L1479

**Comment by 7c6f434c** [comment]
@jtojnar it looks like ofborg Darwin build of `glib` has actualy failed?

**Comment by jtojnar** [comment]
Sorry, forgot to push this fix.

**Comment by matthewbauer** [comment]
Are there any other dconf uses we need to get rid of? We can also make dconf an optional propagated input of glib to reduce duplication.

**Comment by jtojnar** [comment]
In general, packages should not depend on dconf (unless they explicitly need libdconf for low-level access). Instead, they should pick up the dconf-based GSettings backend module from the environment (passed by `wrapGAppsHook`). We should probably add the `!isDarwin` condition to all manual `wrapProgram` invocations (or change them to `wrapGAppsHook`).

I am not sure what duplication do you mean but dconf depends on glib so we definitely cannot propagate it from there.

**Comment by hedning** [comment]
I think this broke glibmm on darwin: https://hydra.nixos.org/build/87684380

Complains about not finding a header file:
> desktopappinfo.cc:27:10: fatal error: 'gio/gdesktopappinfo.h' file not found
#include <gio/gdesktopappinfo.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

There's similar failures in other darwin derivations.

Needed by inkscape: https://hydra.nixos.org/job/nixpkgs/trunk/unstable#tabs-constituents

**Comment by jtojnar** [comment]
Yeah, glib does not build them on Darwin: https://gitlab.gnome.org/GNOME/glib/blob/be10f19752223f2607ba1fe00408c75920792aba/gio/meson.build#L412-429

It previously did build them because it detects Mac by the presence of Cocoa. Maybe we need to convince glibmm glibmm it is on Darwin in a same way? Or report a bug?

**Comment by jtojnar** [comment]
Yeah, there are the same checks, we need cocoa in glibmm:

https://gitlab.gnome.org/GNOME/glibmm/blob/96a997b1f4cf902a7690de8a27e1173f1d217042/configure.ac#L58-76

https://gitlab.gnome.org/GNOME/glibmm/blob/96a997b1f4cf902a7690de8a27e1173f1d217042/gio/src/desktopappinfo.hg#L26

**Pull request merged**
