### PR TITLE
vencord: 1.9.5 -> 1.10.1

### PR DESCRIPTION
**Pull request by Scrumplex**
## Description of changes

https://github.com/Vendicated/Vencord/compare/v1.9.5...v1.10.1

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by mattpolzin** [comment]
I got a hash mismatch building this on `x86_64-linux`.

```
error: hash mismatch in fixed-output derivation '/nix/store/n06k5gfwlkxfgwg2zal0xqlibgax94js-source.drv':
         specified: sha256-Xu93mSMF+DVAc90ma4cOM7bJSb2wOpRfm6w5pCGl+oQ=
            got:    sha256-RhczE44qTWpB1rzAKk5m/rEfhFNu7aXIzfKXpTxzO+o=
```

**Comment by Scrumplex** [comment]
> I got a hash mismatch building this on `x86_64-linux`.
> 
> ```
> error: hash mismatch in fixed-output derivation '/nix/store/n06k5gfwlkxfgwg2zal0xqlibgax94js-source.drv':
>          specified: sha256-Xu93mSMF+DVAc90ma4cOM7bJSb2wOpRfm6w5pCGl+oQ=
>             got:    sha256-RhczE44qTWpB1rzAKk5m/rEfhFNu7aXIzfKXpTxzO+o=
> ```

That's interesting. I just tried to build it again and it worked? In my case the derivation is also different though: `/nix/store/s9lpvblksfqs3q6dbfrm8brjjddwv0h9-source.drv`

Build log:

```
source> sourcing setup hook '/nix/store/dv5vgsw8naxnkcc88x78vprbnn1pp44y-patchelf-0.15.0/nix-support/setup-hook'
source> sourcing setup hook '/nix/store/i4iynx9axbq23sd0gyrc5wdb46zz6z8l-update-autotools-gnu-config-scripts-hook/nix-support/setup-hook'
source> sourcing setup hook '/nix/store/h9lc1dpi14z7is86ffhl3ld569138595-audit-tmpdir.sh'
source> sourcing setup hook '/nix/store/m54bmrhj6fqz8nds5zcj97w9s9bckc9v-compress-man-pages.sh'
source> sourcing setup hook '/nix/store/wgrbkkaldkrlrni33ccvm3b6vbxzb656-make-symlinks-relative.sh'
source> sourcing setup hook '/nix/store/5yzw0vhkyszf2d179m0qfkgxmp5wjjx4-move-docs.sh'
source> sourcing setup hook '/nix/store/fyaryjvghbkpfnsyw97hb3lyb37s1pd6-move-lib64.sh'
source> sourcing setup hook '/nix/store/kd4xwxjpjxi71jkm6ka0np72if9rm3y0-move-sbin.sh'
source> sourcing setup hook '/nix/store/pag6l61paj1dc9sv15l7bm5c17xn5kyk-move-systemd-user-units.sh'
source> sourcing setup hook '/nix/store/jivxp510zxakaaic7qkrb7v1dd2rdbw9-multiple-outputs.sh'
source> sourcing setup hook '/nix/store/ilaf1w22bxi6jsi45alhmvvdgy4ly3zs-patch-shebangs.sh'
source> sourcing setup hook '/nix/store/cickvswrvann041nqxb0rxilc46svw1n-prune-libtool-files.sh'
source> sourcing setup hook '/nix/store/xyff06pkhki3qy1ls77w10s0v79c9il0-reproducible-builds.sh'
source> sourcing setup hook '/nix/store/aazf105snicrlvyzzbdj85sx4179rpfp-set-source-date-epoch-to-latest.sh'
source> sourcing setup hook '/nix/store/gps9qrh99j7g02840wv5x78ykmz30byp-strip.sh'
source> exporting https://github.com/Vendicated/Vencord.git (rev v1.9.7) into /nix/store/967mcz7dgqmmgdds8n5kwblj8fkgbrkm-source
source> Initialized empty Git repository in /nix/store/967mcz7dgqmmgdds8n5kwblj8fkgbrkm-source/.git/
copying path '/nix/store/63g12hfzq40msw1vfdzpfcg9bp42gwir-pnpm-config-hook' from 'https://cache.nixos.org'...
source> remote: Enumerating objects: 824, done.
source> remote: Counting objects: 100% (824/824), done.
source> remote: Compressing objects: 100% (709/709), done.
source> remote: Total 824 (delta 117), reused 371 (delta 14), pack-reused 0 (from 0)
source> Receiving objects: 100% (824/824), 776.67 KiB | 6.64 MiB/s, done.
source> Resolving deltas: 100% (117/117), done.
source> From https://github.com/Vendicated/Vencord
source>  * tag               v1.9.7     -> FETCH_HEAD
source> Switched to a new branch 'fetchgit'
source> Enumerating objects: 824, done.
source> Counting objects: 100% (824/824), done.
source> Compressing objects: 100% (723/723), done.
source> Writing objects: 100% (824/824), done.
source> Total 824 (delta 118), reused 703 (delta 0), pack-reused 0 (from 0)
source> Enumerating objects: 824, done.
source> Nothing new to pack.
```

**Comment by Scrumplex** [comment]
@FlafyDev @NotAShelf could one of you please take a look and review this PR?

**Comment by NotAShelf** [comment]
will do as soon as I get home

**Comment by NotAShelf** [comment]
Seems to be causing a hash mismatch:

```
error: hash mismatch in fixed-output derivation '/nix/store/s0vf0d8wbvqm1ck06qdf0k8bycsfzajq-source.drv':
        likely URL: https://github.com/Vendicated/Vencord.git
         specified: sha256-krNo5CMQ70xEAdsK8Ix/7L8wOJq8yyRbGj9o5NzRYfk=
            got:    sha256-PPzFCMifAeg9TosUwP/asvmSFIDDvdN7MHLeNNV2VH8=
```

**Comment by Scrumplex** [comment]
This is odd. I wonder if `leaveDotGit` makes the source drv hash unstable? Because it definitely built fine for me before, but now it fails (after I gced the source)

**Comment by sersorrel** [comment]
likewise:

```
error: hash mismatch in fixed-output derivation '/nix/store/yxzvm6r8afjgdibjz0v4azybgbbl9s38-source.drv':
        likely URL: https://github.com/Vendicated/Vencord.git
         specified: sha256-PPzFCMifAeg9TosUwP/asvmSFIDDvdN7MHLeNNV2VH8=
            got:    sha256-5AYIlmlmEpoDvFHbXH8W8JbDRw2Wbs0aSqt8GmQyCRs=
```

**Comment by Scrumplex** [comment]
I think this is #8567

**Comment by Scrumplex** [comment]
I have compromised on setting a hardcoded `VENCORD_HASH` that shouldn't be relevant for anything besides the updated (that is disabled in our build).

**Comment by Scrumplex** [comment]
Please try again @sersorrel @NotAShelf :pray:

**Comment by Scrumplex** [comment]
> "interesting" log message on build:
> 
> "WARN using --force I sure hope you know what you are doing"

That's from `pnpm.fetchDeps`. `--force` just makes it download all node deps no matter the platform, processor and libc implementation.

**Comment by Infinidoge** [comment]
There's a new release, ([v1.10.1](https://github.com/Vendicated/Vencord/releases/tag/v1.10.1), which fixes broken BetterFolders and the like.

**Comment by Scrumplex** [comment]
Result of `nixpkgs-review pr 332423` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>vencord</li>
    <li>vencord-web-extension</li>
    <li>webcord-vencord</li>
  </ul>
</details>

**Review by Infinidoge — APPROVED** [review]
Tested on my machine, works great :)

Also the package looks to be significantly more maintainable now, which is good.

**Review by NotAShelf — APPROVED** [review]

**Comment by NotAShelf** [comment]
Seems to be running fine, LGTM.

**Pull request merged**
