### PR TITLE
chia: drop

### PR DESCRIPTION
**Pull request by bbjubjub2494**
## Description of changes

Remove the `chia` derivation and its exclusive references, and disband the chia team.

For the record, these packages always required a ton of hacks and tricks to maintain in-tree because of very specific dependencies and other idiosyncrasies and I don't have the resources to do that anymore. It may work better out-of-tree in something like [chia.nix](https://github.com/lourkeur/chia.nix). 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by lourkeur** [comment]
weird I thought I forked the latest master

**Comment by delroth** [comment]
Could you add tombstones to `pkgs/top-level/aliases.nix` for the removed packages (as well as `pkgs/top-level/python-aliases.nix` for the Python packages).

**Comment by delroth** [comment]
Thank you very much for the clean-up! Hopefully at some point in the future upstream will fix things to be more distro-friendly and we can maybe get those packages back in nixpkgs without them being a maintenance nightmare :-)

**Comment by meebey** [comment]
Today I wanted to bump my chia node and noticed the package was removed. @delroth @lourkeur any specific packaging pain that led to the removal? The feedback might help upstream to be less painful in the future (I will pass the message on).

**Comment by lourkeur** [comment]
Hi @meebey, nice to know someone else is using this. So in short, what happens with chia is a mix of different things. Most often, it depends on newer package versions that the ones in `master`, so I would forward-port them, but that risks breaking something else. There's also always something unexpected that I have to go and debug. I don't think upstream can do much about it because their development style of bumping dependencies very often and having a lot of them is justified, and Nixpkgs's approach of manually and slowly bumping python modules is also justified, they are just incompatible.

I have been working on [`chia.nix`](https://github.com/lourkeur/chia.nix) as I said, and if the trust assumption is ok with you, you can get 1.8.2 or 1.8.3-rc1 right now, and more recent versions soon (tm)

**Pull request merged**
