### PR TITLE
ruby: --disable-rubygems for baseruby

### PR DESCRIPTION
**Pull request by alyssais**
###### Motivation for this change

This works just fine, and means we don't run into an issue with RubyGems trying to install into a different Ruby's prefix when cross-compiling. See https://github.com/NixOS/nixpkgs/pull/51842#issuecomment-478392799.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.

---

Cc: @immae @samueldr @Mic92

### CODE REVIEW

**Comment by immae** [comment]
@alyssais Thanks for your fix. Just so that I can test properly, can you please confirm that your fix is another solution to what I suggested (i.e. removing the `--destdir`) as a temporary workaround?

**Comment by alyssais** [comment]
> @alyssais Thanks for your fix. Just so that I can test properly, can you please confirm that your fix is another solution to what I suggested (i.e. removing the `--destdir`) as a temporary workaround?

Yes, I believe so. Except this keeps the cross-build working as well,
and so I intend this change to be permanent.

**Comment by samueldr** [comment]
At a glance, this looks safe for backporting to 19.03, since its rubies are exhibiting this issue. Do you think this is wrong?

**Comment by alyssais** [comment]
> At a glance, this looks safe for backporting to 19.03, since its rubies are exhibiting this issue. Do you think this is wrong?

I think this should be safe to backport, providing it does actually fix
the issue.

**Comment by samueldr** [comment]
Hmm, having an issue. Ruby 2.6's native `bundler` apparently doesn't play well with that change.

[Repro](https://gist.github.com/samueldr/e9a12642e240726621a3a006c0bde324)

```
~/tmp/tmp/repro $ nix-build --keep-going -I nixpkgs=/Users/samuel/tmp/nixpkgs/nixpkgs-PR61684
these derivations will be built:
  /nix/store/qkn0f4hiqkii9j11xnk4kjrw5mgjc4x9-test-with-ruby_2_6.drv
building '/nix/store/qkn0f4hiqkii9j11xnk4kjrw5mgjc4x9-test-with-ruby_2_6.drv' on 'ssh://samuel@duffman'...
ruby 2.6.3p62 (2019-04-16) [x86_64-linux]
`/homeless-shelter` is not a directory.
Bundler will use `/build/bundler/home/unknown' as your home directory temporarily.
Bundler version 1.17.2
/nix/store/s7x3gaf88bbi7p647jpbrbc29249f65m-ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundler (Gem::GemNotFoundException)
        from /nix/store/s7x3gaf88bbi7p647jpbrbc29249f65m-ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
        from /nix/store/s7x3gaf88bbi7p647jpbrbc29249f65m-ruby-2.6.3/bin/bundler:23:in `<main>'
builder for '/nix/store/qkn0f4hiqkii9j11xnk4kjrw5mgjc4x9-test-with-ruby_2_6.drv' failed with exit code 1
error: build of '/nix/store/qkn0f4hiqkii9j11xnk4kjrw5mgjc4x9-test-with-ruby_2_6.drv' on 'ssh://samuel@duffman' failed: builder for '/nix/store/qkn0f4hiqkii9j11xnk4kjrw5mgjc4x9-test-with-ruby_2_6.drv' failed with exit code 1
builder for '/nix/store/qkn0f4hiqkii9j11xnk4kjrw5mgjc4x9-test-with-ruby_2_6.drv' failed with exit code 1
error: build of '/nix/store/qkn0f4hiqkii9j11xnk4kjrw5mgjc4x9-test-with-ruby_2_6.drv' failed
```

The PATH order here matters. The other way around `bundler` comes from `ruby_2_6`. This means that if an end-user with `ruby_2_6` could have a different bundler than expected. Additionally, I think the bundler shipped with ruby should work, otherwise it seems weird to me.

**Comment by immae** [comment]
@samueldr : this is actually the error that I got with the destdir (bundler cannot find himself), but only with versions different from the latest one (see comment given in the description of the PR for details)

Does it work with other versions for you?

**Comment by samueldr** [comment]
Yes, the default.nix when built only fails for 2.6 with the change; calling `nix-build` builds for `2_4`, `2_5` and `2_6`.

**Comment by immae** [comment]
Ok, so it’s the exact reverse of the current state then

**Comment by alyssais** [comment]
On Sat, May 18, 2019 at 03:53:41PM -0700, Samuel Dionne-Riel wrote:
> Hmm, having an issue. Ruby 2.6's native `bundler` apparently doesn't play well with that change.
>
> [Repro](https://gist.github.com/samueldr/e9a12642e240726621a3a006c0bde324)
>
> ```
> ~/tmp/tmp/repro $ nix-build --keep-going -I nixpkgs=/Users/samuel/tmp/nixpkgs/nixpkgs-PR61684
> these derivations will be built:
>   /nix/store/qkn0f4hiqkii9j11xnk4kjrw5mgjc4x9-test-with-ruby_2_6.drv
> building '/nix/store/qkn0f4hiqkii9j11xnk4kjrw5mgjc4x9-test-with-ruby_2_6.drv' on 'ssh://samuel@duffman'...
> ruby 2.6.3p62 (2019-04-16) [x86_64-linux]
> `/homeless-shelter` is not a directory.
> Bundler will use `/build/bundler/home/unknown' as your home directory temporarily.
> Bundler version 1.17.2
> /nix/store/s7x3gaf88bbi7p647jpbrbc29249f65m-ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundler (Gem::GemNotFoundException)
>         from /nix/store/s7x3gaf88bbi7p647jpbrbc29249f65m-ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
>         from /nix/store/s7x3gaf88bbi7p647jpbrbc29249f65m-ruby-2.6.3/bin/bundler:23:in `<main>'
> builder for '/nix/store/qkn0f4hiqkii9j11xnk4kjrw5mgjc4x9-test-with-ruby_2_6.drv' failed with exit code 1
> error: build of '/nix/store/qkn0f4hiqkii9j11xnk4kjrw5mgjc4x9-test-with-ruby_2_6.drv' on 'ssh://samuel@duffman' failed: builder for '/nix/store/qkn0f4hiqkii9j11xnk4kjrw5mgjc4x9-test-with-ruby_2_6.drv' failed with exit code 1
> builder for '/nix/store/qkn0f4hiqkii9j11xnk4kjrw5mgjc4x9-test-with-ruby_2_6.drv' failed with exit code 1
> error: build of '/nix/store/qkn0f4hiqkii9j11xnk4kjrw5mgjc4x9-test-with-ruby_2_6.drv' failed
> ```
>
> The PATH order here matters. The other way around `bundler` comes from `ruby_2_6`. This means that if an end-user with `ruby_2_6` could have a different bundler than expected. Additionally, I think the bundler shipped with ruby should work, otherwise it seems weird to me.

As far as I can tell, this is only an issue with the `bundler'
executable, which is designed to just be a convenience alias for
`bundle', which is the command referred to in the documentation, etc.

I don't know how much of an issue it is that this doesn't work? I
wouldn't even have thought to test it. But maybe other people have come
to rely on it?

**Comment by alyssais** [comment]
I've added a new commit. Please try again.

It feels very strange that we now include a seperately-versioned
RubyGems with Ruby, but with Bundler, you get the default version, and
can use the bundler package to get the "latest" version.

I'm inclined to say that we should distribute a rubygems package for the
latest version of RubyGems, and distribute stock RubyGems (with our
patches) with Ruby. I haven't thought much about the implications of
this, but it instintively feels right to me... Thoughts?
(cc @zimbatm @manveru)

**Comment by samueldr** [comment]
Oh, you're right it only fails with `bundler`. (Seems I never internalised there was `bundle` and `bundler` and that they could differ in behaviour?)

I'm have prepared a couple tests to see how the behaviour compares, it is descriptive of the situation, and not necessarily prescriptive; meaning that you do what you feel is right with the data.

Though, I am not confident that the test tests @immae's case.

* * *

The stuff required to run it:

 * https://gist.github.com/samueldr/597a0a44671e0b4150c332b37b485d88

Results:

 * https://gist.github.com/samueldr/005d9f3c25590b7a74a5501a82c07a64

* * *

My take on the results:

 * Between 18.09 and 19.03 there was a change that made `bundle` not work with the non-default ruby. (Excluding 2.6.)
 * The PR currently doesn't seem to cause regressions.

**Comment by alyssais** [comment]
To clarify: there /shouldn't/ be a difference between `bundle' and
`bundler'. But when RubyGems is installed, it (deliberately) only
installs `bundle'. I don't know why.

**Comment by alyssais** [comment]
> I'm have prepared a couple tests to see how the behaviour compares, it is descriptive of the situation, and not necessarily prescriptive; meaning that you do what you feel is right with the data.

Thanks very much for these. They've been very helpful.

An observation: Ruby 2.3 in 18.09 includes a `bundler' executable. In
19.03 it does not.

**Comment by alyssais** [comment]
The current behaviour (as of the tip of this branch), which is that a Ruby elsewhere in the environment does not affect an application just because it happens to be written in Ruby, is desirable in almost all cases. The problem is just that, with Bundler, we actually want the exact opposite behaviour — it should use whatever Ruby is in the environment.

In the cases @samueldr has found where this works, it works because of a Bundler executable bundled with Ruby that finds and executes Bundler from Ruby’s LOAD_PATH. In these cases, Ruby and Bundler both have `bundle` executables, and the Ruby one wins purely by having a Nix store path that beats Bundler’s alphabetically. When run, assuming Bundler is loaded after Ruby (in arguments to `nix-shell`, for example), Ruby’s Bundler executable will load Bundler from the Bundler derivation, not from the Ruby one. This produces the desirable behaviour.

To have this work perfectly, we would need a way to ensure that `nix-shell -p ruby_2_3 bundler` put Ruby’s Bundler executable first in PATH, but set RUBYLIB with the Bundler derivation’s lib directory.

**Comment by zimbatm** [comment]
nice detective work yall :)

I think I'm the one that installed rubygems directly into the ruby installation. The reason was that rubygems had a security vulnerability and I wanted to make sure that all the ruby users would have the latest version available.

Regarding the priority, how about marking `bundler` with `lib.hiPrio`? `bundlerEnv` should respect that and prioritize it.

**Comment by alyssais** [comment]
> I think I'm the one that installed rubygems directly into the ruby installation. The reason was that rubygems had a security vulnerability and I wanted to make sure that all the ruby users would have the latest version available.

Nowadays Ruby upstream issues version bumps for Rubygems vulns (e.g. 2.6.2), so I think I'd like to go back to shipping the default version of RubyGems with Ruby, and making a seperate RubyGems package that could be used to get latest. Out of scope of this PR though.

> Regarding the priority, how about marking `bundler` with `lib.hiPrio`? `bundlerEnv` should respect that and prioritize it.

In `bundlerEnv`, I don't think this is an issue, because it only exposes the gem executables (no Ruby anything). `bundlerEnv`'s `.env` can be fixed by swapping the order of `nativeBuildInputs`.

But the case I'm really thinking of is this:

    nix-shell -p ruby -p bundler

If you can get one where Ruby beats Bundler because it's hash is sorted after Bundler's, it doesn't make a difference if you do

    nix-shell -p ruby -p 'hiPrio bundler'

You still get Ruby's Bundler.

Any ideas?

**Comment by samueldr** [comment]
This makes me think, my initial testing (never shared here) with nix-shell failed because I had a `bundler` from a `bundlerApp`, *hue-cli*. This is not limited to that app, see `nix-locate -1 --at-root --regex '/bin/bundler?'`.

Just saying in case it is related or relevant to the current issue with the bundler executable being overriden.

**Comment by FRidh** [comment]
What's the status of this PR?

**Comment by alyssais** [comment]
> What's the status of this PR?

Looks like it’s been incorporated into #61114. I still want to get the ruby and bundler derivations playing nice together. It looks from that PR that @manveru might have found a way to do it…

**Comment by alyssais** [comment]
To summarise how PATH order is determined in temporary environments:

In nix-shell, order matters:

    ~ $ nix-shell -p ruby_2_6 -p bundler --run 'which bundle'
    /nix/store/0cqkbznpnvjw1lwkq05dh0psyykzqw3z-ruby-2.6.3/bin/bundle
    ~ $ nix-shell -p bundler -p ruby_2_6 --run 'which bundle'
    /nix/store/zqbn9k0rk06bllxk1k2wk5xs1q1j6m5z-bundler-1.17.2/bin/bundle

So, users need to always put Bundler first.

In nix run, order doesn't matter and paths are always sorted
reverse-lexicographically:

    ~ $ nix run -f '<nixpkgs>' bundler ruby_2_6 -c which bundle
    /nix/store/zqbn9k0rk06bllxk1k2wk5xs1q1j6m5z-bundler-1.17.2/bin/bundle
    ~ $ nix run -f '<nixpkgs>' ruby_2_6 bundler -c which bundle
    /nix/store/zqbn9k0rk06bllxk1k2wk5xs1q1j6m5z-bundler-1.17.2/bin/bundle

    ~ $ env -i nix run -f /home/src/nixlib bash hello coreutils ruby_2_6 bundler -c sh -c 'echo $PATH' | tr : '\n'
    /nix/store/zqbn9k0rk06bllxk1k2wk5xs1q1j6m5z-bundler-1.17.2/bin
    /nix/store/xfghy8ixrhz3kyy6p724iv3cxji088dx-bash-4.4-p23/bin
    /nix/store/k8lhqzpaaymshchz8ky3z4653h4kln9d-coreutils-8.31/bin
    /nix/store/d31xwav4imnlpw7zk2ipsc6szbi8dp4k-hello-2.10/bin
    /nix/store/0cqkbznpnvjw1lwkq05dh0psyykzqw3z-ruby-2.6.3/bin

It does not appear that there is anything we can do in Nixpkgs
(e.g. setting meta.priority) to alter this order. So, while this isn't
ideal, improving it is out of scope for this PR (and Nixpkgs in
general), and needs to be a change in Nix.

**Pull request merged**
