### PR TITLE
crosvm: 119.0 -> unstable-2024-01-02

### PR DESCRIPTION
**Pull request by philiptaron**
## Description of changes

As of 18 months ago, this project [switched to another repository](https://chromium.googlesource.com/chromiumos/platform/crosvm/+/ed7d455a4364671d8dfaf2d3e65d25128861f650).

I turned on all the features that were listed in [Cargo.toml](https://chromium.googlesource.com/crosvm/crosvm/+/refs/heads/main/Cargo.toml) as working on both aarch64 and x86_64.

This is perhaps too much. No package at the current moment depends on `crosvm`, so maybe it's OK.

I also deleted the updater, as the project no longer appears to have releases, and just deploys out of main. The most recent commit as of 2024/01/02 seemed as good as any.

I think commit [c7dddbcc44833f89b3b2e98630baea5e84be1b9c](https://chromium.googlesource.com/crosvm/crosvm/+/c7dddbcc44833f89b3b2e98630baea5e84be1b9c) from crosvm corresponds with the old repo's [b9977397be2ffc8154bf55983eb21495016d48b5](https://chromium.googlesource.com/chromiumos/platform/crosvm/+/b9977397be2ffc8154bf55983eb21495016d48b5), based on that commit's message.

Therefore, here's the diffs: https://chromium.googlesource.com/crosvm/crosvm/+/c7dddbcc44833f89b3b2e98630baea5e84be1b9c..dbdd15966d6bb8239f33d31a658221cac47e3666

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alyssais** [comment]
> As of 18 months ago, this project [switched to another repository](https://chromium.googlesource.com/chromiumos/platform/crosvm/+/ed7d455a4364671d8dfaf2d3e65d25128861f650).

They switched the development repo.  We package the Chrome OS release versions, since they presumably get QAd and stuff. These branches are still created in the old repository, presumably due to some automation having not been updated.  If you look, you'll see that the release we have is far more recent than 18 months old, and lives in that repository.

> I turned on all the features that were listed in [Cargo.toml](https://chromium.googlesource.com/crosvm/crosvm/+/refs/heads/main/Cargo.toml) as working on both aarch64 and x86_64.

crosvm features are in varying states of working, sometimes require hacks to even build (although it seems like that's not so much the case at the moment), and sometimes are Chrome OS or Android-specific.  I don't think it makes sense to turn them all on by default, but I'm happy for any particular one to be turned on if somebody has a use case for it.

**Comment by philiptaron** [comment]
Got it. I'm inclined just to close this PR then, since it's not the direction you'd like to maintain the package, and all I'm trying to do is get [QEMU + virtio-gpu](https://linaro.atlassian.net/wiki/spaces/ORKO/pages/28985622530/Building+QEMU+with+virtio-gpu+and+rutabaga+gfx) going.

**Comment by alyssais** [comment]
Then you probably want #275820 :)

**Comment by philiptaron** [comment]
I'm keeping this in the freezer.

**Pull request closed without merging**
