### PR TITLE
New packages for luabind, stxxl and osrm-backend

### PR DESCRIPTION
**Pull request by risicle**
This is almost a strawman pull request, as I am still _very_ new to nix. Either way, I thought these packages could be useful to someone and if I'm going horribly wrong someone could point me in the right direction.

### CODE REVIEW

**Comment by lethalman** [comment]
Any reason why luabind is not in luaPackages ?

**Comment by risicle** [comment]
Mmm probably because luabind isn't really a lua *package* as such. It's a c++ library for embedding lua. But if it's generally considered that it should live there anyway, I'm not against moving it.

**Comment by lethalman** [comment]
@risicle inside luaPackages it will be compiled for more than one lua versions. If that's not compatible with luabind then it's ok.

**Comment by risicle** [comment]
Ah yes, that's an interesting point - I'll consider...

**Comment by risicle** [comment]
@lethalman Looking deeper, the only reason I can see against moving luabind into luaPackages is it has a host of patches, and I'm not sure where they'd live if it went into lua-packages.nix. top-level/ seems to be devoid of patches, so I assumed they are not welcome there.

**Comment by lethalman** [comment]
Ok it's fine as is for now.

**Comment by lethalman** [comment]
Built locally, thanks.

**Comment by risicle** [comment]
That was almost too easy.

**Pull request merged**
