### PR TITLE
karabiner-elements: 14.13.0 -> 15.0.0, refactor and cleanup

### PR DESCRIPTION
**Pull request by 4evy**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by DontEatOreo** [comment]
Result of `nixpkgs-review pr 335700` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>karabiner-elements</li>
    <li>karabiner-elements.driver</li>
  </ul>
</details>

**Comment by DontEatOreo** [comment]
Result of `nixpkgs-review pr 335700` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>karabiner-elements</li>
    <li>karabiner-elements.driver</li>
  </ul>
</details>

**Comment by Atemu** [comment]
Given that this release contains breaking changes and there's a refactor, this should certainly not be backported. Please read the backport criteria again.

**Comment by JohnRTitor** [comment]
Agree with Atemu on this one. The formatting part is pretty harmless (just some nixfmt and minor changes), but the update itself has breaking changes (big ones at that) making it not eligible for backport. 

https://github.com/pqrs-org/Karabiner-Elements/releases/tag/v15.0.0

**Review by JohnRTitor — COMMENTED** [review]
Formatting commits can be squashed, so there's three commits. 

1. Formatting
2. updateScript change
3. Package update

**Comment by Atemu** [comment]
There's only one formatting commit? The refactors being separate commits isn't strictly necessary but welcome. No need to change anything w.r.t. commit hygiene.

**Comment by JohnRTitor** [comment]
I only suggested to merge the insignificant commits to one to keep the commit history clean, but I have no problem merging this as it is.

**Review by JohnRTitor — APPROVED** [review]

**Comment by Atemu** [comment]
I do not see how commits split into atomic units in any way constitute an "unclean" history; quite the opposite.

**Pull request merged**
