### PR TITLE
nodePackages.redoc-cli: init at 0.9.8

### PR DESCRIPTION
**Pull request by veehaitch**
###### Motivation for this change

`redoc-cli` is [ReDoc](https://github.com/Redocly/redoc)'s command line interface

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by prusnak** [comment]
Please rework your PR. It now has a merge conflict after merging https://github.com/NixOS/nixpkgs/pull/89184

**Comment by veehaitch** [comment]
> Please rework your PR. It now has a merge conflict after merging #89184

Done!

**Review by prusnak — APPROVED** [review]

**Comment by veehaitch** [comment]
@prusnak is there anything I can do to help getting this PR merged? Just let me know :)

**Comment by prusnak** [comment]
@veehaitch I don't have merge permissions, so this needs to be merged by someone who has them.

**Comment by veehaitch** [comment]
Maybe @calbrecht wants to take a look? :)

**Comment by veehaitch** [comment]
Still looking forward to getting this merged :)

**Comment by calbrecht** [comment]
No merge permissions either, here :)

**Comment by veehaitch** [comment]
Maybe @Infinisil? :)

**Pull request merged**
