### PR TITLE
python310Packages.websockets: 10.3 -> 10.4 

### PR DESCRIPTION
**Pull request by fabaff**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 206834` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>22 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.hug</li>
    <li>python310Packages.pytest-sanic</li>
    <li>python310Packages.qiskit</li>
    <li>python310Packages.qiskit-aer</li>
    <li>python310Packages.qiskit-finance</li>
    <li>python310Packages.qiskit-ibmq-provider</li>
    <li>python310Packages.qiskit-ignis</li>
    <li>python310Packages.qiskit-machine-learning</li>
    <li>python310Packages.qiskit-nature</li>
    <li>python310Packages.qiskit-optimization</li>
    <li>python310Packages.qiskit-terra</li>
    <li>python39Packages.hug</li>
    <li>python39Packages.pytest-sanic</li>
    <li>python39Packages.qiskit</li>
    <li>python39Packages.qiskit-aer</li>
    <li>python39Packages.qiskit-finance</li>
    <li>python39Packages.qiskit-ibmq-provider</li>
    <li>python39Packages.qiskit-ignis</li>
    <li>python39Packages.qiskit-machine-learning</li>
    <li>python39Packages.qiskit-nature</li>
    <li>python39Packages.qiskit-optimization</li>
    <li>python39Packages.qiskit-terra</li>
  </ul>
</details>
<details>
  <summary>16 packages failed to build:</summary>
  <ul>
    <li>dyndnsc</li>
    <li>python310Packages.dalle-mini</li>
    <li>python310Packages.elastic-apm</li>
    <li>python310Packages.elegy</li>
    <li>python310Packages.entrance</li>
    <li>python310Packages.entrance-with-router-features</li>
    <li>python310Packages.json-logging</li>
    <li>python310Packages.sanic</li>
    <li>python310Packages.sanic-auth</li>
    <li>python310Packages.sanic-testing</li>
    <li>python310Packages.strawberry-graphql</li>
    <li>python39Packages.dalle-mini</li>
    <li>python39Packages.elegy</li>
    <li>python39Packages.modeled</li>
    <li>python39Packages.robotframework-tools</li>
    <li>wolfram-notebook</li>
  </ul>
</details>
<details>
  <summary>255 packages built:</summary>
  <ul>
    <li>adl</li>
    <li>ani-cli</li>
    <li>anime-downloader</li>
    <li>baserow</li>
    <li>botamusique</li>
    <li>celluloid</li>
    <li>chia</li>
    <li>clipgrab</li>
    <li>cplay-ng</li>
    <li>curseradio</li>
    <li>dmarc-metrics-exporter</li>
    <li>dmlive</li>
    <li>faraday-agent-dispatcher</li>
    <li>ff2mpv</li>
    <li>gallery-dl</li>
    <li>grab-site</li>
    <li>gtk-pipe-viewer</li>
    <li>haruna</li>
    <li>home-assistant-component-tests.ambient_station</li>
    <li>home-assistant-component-tests.emulated_kasa</li>
    <li>home-assistant-component-tests.homematicip_cloud</li>
    <li>home-assistant-component-tests.livisi</li>
    <li>home-assistant-component-tests.roomba</li>
    <li>home-assistant-component-tests.samsungtv</li>
    <li>home-assistant-component-tests.sense</li>
    <li>home-assistant-component-tests.simplisafe</li>
    <li>home-assistant-component-tests.tibber</li>
    <li>home-assistant-component-tests.twitch</li>
    <li>home-assistant-component-tests.vallox</li>
    <li>home-assistant-component-tests.volvooncall</li>
    <li>home-assistant-component-tests.webostv</li>
    <li>home-assistant-component-tests.whirlpool</li>
    <li>hydrus</li>
    <li>hypnotix</li>
    <li>ihaskell</li>
    <li>jellyfin-media-player</li>
    <li>jellyfin-mpv-shim</li>
    <li>jftui</li>
    <li>jupyter</li>
    <li>kismet</li>
    <li>libsForQt5.audiotube (plasma5Packages.audiotube)</li>
    <li>mailman</li>
    <li>mailman-hyperkitty</li>
    <li>manim</li>
    <li>media-downloader</li>
    <li>minitube</li>
    <li>mpc-qt</li>
    <li>mpv</li>
    <li>mpvScripts.mpv-playlistmanager</li>
    <li>mpvpaper</li>
    <li>ntfy</li>
    <li>opsdroid</li>
    <li>paperless-ngx</li>
    <li>pipe-viewer</li>
    <li>plex-media-player</li>
    <li>plex-mpv-shim</li>
    <li>pylode</li>
    <li>python310Packages.Nikola</li>
    <li>python310Packages.Pweave</li>
    <li>python310Packages.aioambient</li>
    <li>python310Packages.aiohttp-apispec</li>
    <li>python310Packages.aiolivisi</li>
    <li>python310Packages.aiopylgtv</li>
    <li>python310Packages.aiowebostv</li>
    <li>python310Packages.amqtt</li>
    <li>python310Packages.ansible-kernel</li>
    <li>python310Packages.aqualogic</li>
    <li>python310Packages.arviz</li>
    <li>python310Packages.augmax</li>
    <li>python310Packages.batchspawner</li>
    <li>python310Packages.cairo-lang</li>
    <li>python310Packages.datashader</li>
    <li>python310Packages.dockerspawner</li>
    <li>python310Packages.einops</li>
    <li>python310Packages.falcon</li>
    <li>python310Packages.folium</li>
    <li>python310Packages.gehomesdk</li>
    <li>python310Packages.gekitchen</li>
    <li>python310Packages.gql</li>
    <li>python310Packages.gradient</li>
    <li>python310Packages.graphql-subscription-manager</li>
    <li>python310Packages.homematicip</li>
    <li>python310Packages.jupyter</li>
    <li>python310Packages.jupyter-lsp</li>
    <li>python310Packages.jupyter-server-mathjax</li>
    <li>python310Packages.jupyter-sphinx</li>
    <li>python310Packages.jupyter_server</li>
    <li>python310Packages.jupyterhub</li>
    <li>python310Packages.jupyterhub-ldapauthenticator</li>
    <li>python310Packages.jupyterhub-systemdspawner</li>
    <li>python310Packages.jupyterhub-tmpauthenticator</li>
    <li>python310Packages.jupyterlab</li>
    <li>python310Packages.jupyterlab-git</li>
    <li>python310Packages.jupyterlab-lsp</li>
    <li>python310Packages.jupyterlab_launcher</li>
    <li>python310Packages.jupyterlab_server</li>
    <li>python310Packages.jupytext</li>
    <li>python310Packages.livelossplot</li>
    <li>python310Packages.mattermostdriver</li>
    <li>python310Packages.mkdocs-jupyter</li>
    <li>python310Packages.mpv</li>
    <li>python310Packages.nbclassic</li>
    <li>python310Packages.nbconflux</li>
    <li>python310Packages.nbconvert</li>
    <li>python310Packages.nbdime</li>
    <li>python310Packages.nbsmoke</li>
    <li>python310Packages.nbsphinx</li>
    <li>python310Packages.nix-kernel</li>
    <li>python310Packages.notebook</li>
    <li>python310Packages.notebook-shim</li>
    <li>python310Packages.notedown</li>
    <li>python310Packages.oauthenticator</li>
    <li>python310Packages.openapi-core</li>
    <li>python310Packages.osmnx</li>
    <li>python310Packages.phik</li>
    <li>python310Packages.pymc</li>
    <li>python310Packages.pymoo</li>
    <li>python310Packages.pyppeteer</li>
    <li>python310Packages.python-binance</li>
    <li>python310Packages.pytibber</li>
    <li>python310Packages.roombapy</li>
    <li>python310Packages.samsungtvws</li>
    <li>python310Packages.sense-energy</li>
    <li>python310Packages.simplisafe-python</li>
    <li>python310Packages.slack-sdk</li>
    <li>spyder (python310Packages.spyder)</li>
    <li>python310Packages.systembridge</li>
    <li>python310Packages.tago</li>
    <li>python310Packages.treex</li>
    <li>python310Packages.tubeup</li>
    <li>python310Packages.twitchapi</li>
    <li>python310Packages.vallox-websocket-api</li>
    <li>python310Packages.vega</li>
    <li>python310Packages.volvooncall</li>
    <li>python310Packages.web3</li>
    <li>python310Packages.webargs</li>
    <li>python310Packages.websockets</li>
    <li>python310Packages.whirlpool-sixth-sense</li>
    <li>python310Packages.xarray-einstats</li>
    <li>yt-dlp (python310Packages.yt-dlp)</li>
    <li>yt-dlp-light (python310Packages.yt-dlp-light)</li>
    <li>python39Packages.Nikola</li>
    <li>python39Packages.Pweave</li>
    <li>python39Packages.aioambient</li>
    <li>python39Packages.aiohttp-apispec</li>
    <li>python39Packages.aiolivisi</li>
    <li>python39Packages.aiopylgtv</li>
    <li>python39Packages.aiowebostv</li>
    <li>python39Packages.amqtt</li>
    <li>python39Packages.ansible-kernel</li>
    <li>python39Packages.aqualogic</li>
    <li>python39Packages.arviz</li>
    <li>python39Packages.augmax</li>
    <li>python39Packages.batchspawner</li>
    <li>python39Packages.cairo-lang</li>
    <li>python39Packages.datashader</li>
    <li>python39Packages.dockerspawner</li>
    <li>python39Packages.einops</li>
    <li>python39Packages.elastic-apm</li>
    <li>python39Packages.entrance</li>
    <li>python39Packages.entrance-with-router-features</li>
    <li>python39Packages.falcon</li>
    <li>python39Packages.folium</li>
    <li>python39Packages.gehomesdk</li>
    <li>python39Packages.gekitchen</li>
    <li>python39Packages.gql</li>
    <li>python39Packages.gradient</li>
    <li>python39Packages.graphql-subscription-manager</li>
    <li>python39Packages.homematicip</li>
    <li>python39Packages.json-logging</li>
    <li>python39Packages.jupyter</li>
    <li>python39Packages.jupyter-lsp</li>
    <li>python39Packages.jupyter-server-mathjax</li>
    <li>python39Packages.jupyter-sphinx</li>
    <li>python39Packages.jupyter_server</li>
    <li>python39Packages.jupyterhub</li>
    <li>python39Packages.jupyterhub-ldapauthenticator</li>
    <li>python39Packages.jupyterhub-systemdspawner</li>
    <li>python39Packages.jupyterhub-tmpauthenticator</li>
    <li>python39Packages.jupyterlab</li>
    <li>python39Packages.jupyterlab-git</li>
    <li>python39Packages.jupyterlab-lsp</li>
    <li>python39Packages.jupyterlab_launcher</li>
    <li>python39Packages.jupyterlab_server</li>
    <li>python39Packages.jupytext</li>
    <li>python39Packages.livelossplot</li>
    <li>python39Packages.mattermostdriver</li>
    <li>python39Packages.mkdocs-jupyter</li>
    <li>python39Packages.moretools</li>
    <li>python39Packages.mpv</li>
    <li>python39Packages.nbclassic</li>
    <li>python39Packages.nbconflux</li>
    <li>python39Packages.nbconvert</li>
    <li>python39Packages.nbdime</li>
    <li>python39Packages.nbsmoke</li>
    <li>python39Packages.nbsphinx</li>
    <li>python39Packages.nix-kernel</li>
    <li>python39Packages.notebook</li>
    <li>python39Packages.notebook-shim</li>
    <li>python39Packages.notedown</li>
    <li>python39Packages.oauthenticator</li>
    <li>python39Packages.openapi-core</li>
    <li>python39Packages.osmnx</li>
    <li>python39Packages.phik</li>
    <li>python39Packages.pymc</li>
    <li>python39Packages.pymoo</li>
    <li>python39Packages.pyppeteer</li>
    <li>python39Packages.python-binance</li>
    <li>python39Packages.pytibber</li>
    <li>python39Packages.roombapy</li>
    <li>python39Packages.samsungtvws</li>
    <li>python39Packages.sanic</li>
    <li>python39Packages.sanic-auth</li>
    <li>python39Packages.sanic-testing</li>
    <li>python39Packages.sense-energy</li>
    <li>python39Packages.simplisafe-python</li>
    <li>python39Packages.slack-sdk</li>
    <li>python39Packages.spyder</li>
    <li>python39Packages.strawberry-graphql</li>
    <li>python39Packages.systembridge</li>
    <li>python39Packages.tago</li>
    <li>python39Packages.treex</li>
    <li>python39Packages.tubeup</li>
    <li>python39Packages.twitchapi</li>
    <li>python39Packages.vallox-websocket-api</li>
    <li>python39Packages.vega</li>
    <li>python39Packages.volvooncall</li>
    <li>python39Packages.web3</li>
    <li>python39Packages.webargs</li>
    <li>python39Packages.websockets</li>
    <li>python39Packages.whirlpool-sixth-sense</li>
    <li>python39Packages.xarray-einstats</li>
    <li>python39Packages.yt-dlp</li>
    <li>python39Packages.yt-dlp-light</li>
    <li>python39Packages.zetup</li>
    <li>qimgv</li>
    <li>quarto</li>
    <li>radioboat</li>
    <li>sage</li>
    <li>sageWithDoc</li>
    <li>sharedown</li>
    <li>somafm-cli</li>
    <li>soundux</li>
    <li>spotdl</li>
    <li>stremio</li>
    <li>sublime-music</li>
    <li>tandoor-recipes</li>
    <li>tartube-yt-dlp</li>
    <li>theharvester</li>
    <li>tribler</li>
    <li>urlwatch</li>
    <li>wtwitch</li>
    <li>ytcc</li>
    <li>ytfzf</li>
    <li>ytmdl</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
Why staging? We can just make sure this breaks nothing before merging into master.

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 206834` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>22 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.hug</li>
    <li>python310Packages.pytest-sanic</li>
    <li>python310Packages.qiskit</li>
    <li>python310Packages.qiskit-aer</li>
    <li>python310Packages.qiskit-finance</li>
    <li>python310Packages.qiskit-ibmq-provider</li>
    <li>python310Packages.qiskit-ignis</li>
    <li>python310Packages.qiskit-machine-learning</li>
    <li>python310Packages.qiskit-nature</li>
    <li>python310Packages.qiskit-optimization</li>
    <li>python310Packages.qiskit-terra</li>
    <li>python39Packages.hug</li>
    <li>python39Packages.pytest-sanic</li>
    <li>python39Packages.qiskit</li>
    <li>python39Packages.qiskit-aer</li>
    <li>python39Packages.qiskit-finance</li>
    <li>python39Packages.qiskit-ibmq-provider</li>
    <li>python39Packages.qiskit-ignis</li>
    <li>python39Packages.qiskit-machine-learning</li>
    <li>python39Packages.qiskit-nature</li>
    <li>python39Packages.qiskit-optimization</li>
    <li>python39Packages.qiskit-terra</li>
  </ul>
</details>
<details>
  <summary>18 packages failed to build:</summary>
  <ul>
    <li>python310Packages.dalle-mini</li>
    <li>python310Packages.elegy</li>
    <li>python310Packages.treex</li>
    <li>python39Packages.batchspawner</li>
    <li>python39Packages.dalle-mini</li>
    <li>python39Packages.dockerspawner</li>
    <li>python39Packages.elegy</li>
    <li>python39Packages.jupyterhub</li>
    <li>python39Packages.jupyterhub-ldapauthenticator</li>
    <li>python39Packages.jupyterhub-systemdspawner</li>
    <li>python39Packages.jupyterhub-tmpauthenticator</li>
    <li>python39Packages.modeled</li>
    <li>python39Packages.oauthenticator</li>
    <li>python39Packages.robotframework-tools</li>
    <li>python39Packages.treex</li>
    <li>sage</li>
    <li>sageWithDoc</li>
    <li>wolfram-notebook</li>
  </ul>
</details>
<details>
  <summary>253 packages built:</summary>
  <ul>
    <li>adl</li>
    <li>ani-cli</li>
    <li>anime-downloader</li>
    <li>baserow</li>
    <li>botamusique</li>
    <li>celluloid</li>
    <li>chia</li>
    <li>clipgrab</li>
    <li>cplay-ng</li>
    <li>curseradio</li>
    <li>dmarc-metrics-exporter</li>
    <li>dmlive</li>
    <li>dyndnsc</li>
    <li>faraday-agent-dispatcher</li>
    <li>ff2mpv</li>
    <li>gallery-dl</li>
    <li>grab-site</li>
    <li>gtk-pipe-viewer</li>
    <li>haruna</li>
    <li>home-assistant-component-tests.ambient_station</li>
    <li>home-assistant-component-tests.emulated_kasa</li>
    <li>home-assistant-component-tests.homematicip_cloud</li>
    <li>home-assistant-component-tests.livisi</li>
    <li>home-assistant-component-tests.roomba</li>
    <li>home-assistant-component-tests.samsungtv</li>
    <li>home-assistant-component-tests.sense</li>
    <li>home-assistant-component-tests.simplisafe</li>
    <li>home-assistant-component-tests.tibber</li>
    <li>home-assistant-component-tests.twitch</li>
    <li>home-assistant-component-tests.vallox</li>
    <li>home-assistant-component-tests.volvooncall</li>
    <li>home-assistant-component-tests.webostv</li>
    <li>home-assistant-component-tests.whirlpool</li>
    <li>hydrus</li>
    <li>hypnotix</li>
    <li>ihaskell</li>
    <li>jellyfin-media-player</li>
    <li>jellyfin-mpv-shim</li>
    <li>jftui</li>
    <li>jupyter</li>
    <li>kismet</li>
    <li>libsForQt5.audiotube (plasma5Packages.audiotube)</li>
    <li>mailman</li>
    <li>mailman-hyperkitty</li>
    <li>manim</li>
    <li>media-downloader</li>
    <li>minitube</li>
    <li>mpc-qt</li>
    <li>mpv</li>
    <li>mpvScripts.mpv-playlistmanager</li>
    <li>mpvpaper</li>
    <li>ntfy</li>
    <li>opsdroid</li>
    <li>paperless-ngx</li>
    <li>pipe-viewer</li>
    <li>plex-media-player</li>
    <li>plex-mpv-shim</li>
    <li>pylode</li>
    <li>python310Packages.Nikola</li>
    <li>python310Packages.Pweave</li>
    <li>python310Packages.aioambient</li>
    <li>python310Packages.aiohttp-apispec</li>
    <li>python310Packages.aiolivisi</li>
    <li>python310Packages.aiopylgtv</li>
    <li>python310Packages.aiowebostv</li>
    <li>python310Packages.amqtt</li>
    <li>python310Packages.ansible-kernel</li>
    <li>python310Packages.aqualogic</li>
    <li>python310Packages.arviz</li>
    <li>python310Packages.augmax</li>
    <li>python310Packages.batchspawner</li>
    <li>python310Packages.cairo-lang</li>
    <li>python310Packages.datashader</li>
    <li>python310Packages.dockerspawner</li>
    <li>python310Packages.einops</li>
    <li>python310Packages.elastic-apm</li>
    <li>python310Packages.entrance</li>
    <li>python310Packages.entrance-with-router-features</li>
    <li>python310Packages.falcon</li>
    <li>python310Packages.folium</li>
    <li>python310Packages.gehomesdk</li>
    <li>python310Packages.gekitchen</li>
    <li>python310Packages.gql</li>
    <li>python310Packages.gradient</li>
    <li>python310Packages.graphql-subscription-manager</li>
    <li>python310Packages.homematicip</li>
    <li>python310Packages.json-logging</li>
    <li>python310Packages.jupyter</li>
    <li>python310Packages.jupyter-lsp</li>
    <li>python310Packages.jupyter-server-mathjax</li>
    <li>python310Packages.jupyter-sphinx</li>
    <li>python310Packages.jupyter_server</li>
    <li>python310Packages.jupyterhub</li>
    <li>python310Packages.jupyterhub-ldapauthenticator</li>
    <li>python310Packages.jupyterhub-systemdspawner</li>
    <li>python310Packages.jupyterhub-tmpauthenticator</li>
    <li>python310Packages.jupyterlab</li>
    <li>python310Packages.jupyterlab-git</li>
    <li>python310Packages.jupyterlab-lsp</li>
    <li>python310Packages.jupyterlab_launcher</li>
    <li>python310Packages.jupyterlab_server</li>
    <li>python310Packages.jupytext</li>
    <li>python310Packages.livelossplot</li>
    <li>python310Packages.mattermostdriver</li>
    <li>python310Packages.mkdocs-jupyter</li>
    <li>python310Packages.mpv</li>
    <li>python310Packages.nbclassic</li>
    <li>python310Packages.nbconflux</li>
    <li>python310Packages.nbconvert</li>
    <li>python310Packages.nbdime</li>
    <li>python310Packages.nbsmoke</li>
    <li>python310Packages.nbsphinx</li>
    <li>python310Packages.nix-kernel</li>
    <li>python310Packages.notebook</li>
    <li>python310Packages.notebook-shim</li>
    <li>python310Packages.notedown</li>
    <li>python310Packages.oauthenticator</li>
    <li>python310Packages.openapi-core</li>
    <li>python310Packages.osmnx</li>
    <li>python310Packages.phik</li>
    <li>python310Packages.pymc</li>
    <li>python310Packages.pymoo</li>
    <li>python310Packages.pyppeteer</li>
    <li>python310Packages.python-binance</li>
    <li>python310Packages.pytibber</li>
    <li>python310Packages.roombapy</li>
    <li>python310Packages.samsungtvws</li>
    <li>python310Packages.sanic</li>
    <li>python310Packages.sanic-auth</li>
    <li>python310Packages.sanic-testing</li>
    <li>python310Packages.sense-energy</li>
    <li>python310Packages.simplisafe-python</li>
    <li>python310Packages.slack-sdk</li>
    <li>spyder (python310Packages.spyder)</li>
    <li>python310Packages.strawberry-graphql</li>
    <li>python310Packages.systembridge</li>
    <li>python310Packages.tago</li>
    <li>python310Packages.tubeup</li>
    <li>python310Packages.twitchapi</li>
    <li>python310Packages.vallox-websocket-api</li>
    <li>python310Packages.vega</li>
    <li>python310Packages.volvooncall</li>
    <li>python310Packages.web3</li>
    <li>python310Packages.webargs</li>
    <li>python310Packages.websockets</li>
    <li>python310Packages.whirlpool-sixth-sense</li>
    <li>python310Packages.xarray-einstats</li>
    <li>yt-dlp (python310Packages.yt-dlp)</li>
    <li>yt-dlp-light (python310Packages.yt-dlp-light)</li>
    <li>python39Packages.Nikola</li>
    <li>python39Packages.Pweave</li>
    <li>python39Packages.aioambient</li>
    <li>python39Packages.aiohttp-apispec</li>
    <li>python39Packages.aiolivisi</li>
    <li>python39Packages.aiopylgtv</li>
    <li>python39Packages.aiowebostv</li>
    <li>python39Packages.amqtt</li>
    <li>python39Packages.ansible-kernel</li>
    <li>python39Packages.aqualogic</li>
    <li>python39Packages.arviz</li>
    <li>python39Packages.augmax</li>
    <li>python39Packages.cairo-lang</li>
    <li>python39Packages.datashader</li>
    <li>python39Packages.einops</li>
    <li>python39Packages.elastic-apm</li>
    <li>python39Packages.entrance</li>
    <li>python39Packages.entrance-with-router-features</li>
    <li>python39Packages.falcon</li>
    <li>python39Packages.folium</li>
    <li>python39Packages.gehomesdk</li>
    <li>python39Packages.gekitchen</li>
    <li>python39Packages.gql</li>
    <li>python39Packages.gradient</li>
    <li>python39Packages.graphql-subscription-manager</li>
    <li>python39Packages.homematicip</li>
    <li>python39Packages.json-logging</li>
    <li>python39Packages.jupyter</li>
    <li>python39Packages.jupyter-lsp</li>
    <li>python39Packages.jupyter-server-mathjax</li>
    <li>python39Packages.jupyter-sphinx</li>
    <li>python39Packages.jupyter_server</li>
    <li>python39Packages.jupyterlab</li>
    <li>python39Packages.jupyterlab-git</li>
    <li>python39Packages.jupyterlab-lsp</li>
    <li>python39Packages.jupyterlab_launcher</li>
    <li>python39Packages.jupyterlab_server</li>
    <li>python39Packages.jupytext</li>
    <li>python39Packages.livelossplot</li>
    <li>python39Packages.mattermostdriver</li>
    <li>python39Packages.mkdocs-jupyter</li>
    <li>python39Packages.moretools</li>
    <li>python39Packages.mpv</li>
    <li>python39Packages.nbclassic</li>
    <li>python39Packages.nbconflux</li>
    <li>python39Packages.nbconvert</li>
    <li>python39Packages.nbdime</li>
    <li>python39Packages.nbsmoke</li>
    <li>python39Packages.nbsphinx</li>
    <li>python39Packages.nix-kernel</li>
    <li>python39Packages.notebook</li>
    <li>python39Packages.notebook-shim</li>
    <li>python39Packages.notedown</li>
    <li>python39Packages.openapi-core</li>
    <li>python39Packages.osmnx</li>
    <li>python39Packages.phik</li>
    <li>python39Packages.pymc</li>
    <li>python39Packages.pymoo</li>
    <li>python39Packages.pyppeteer</li>
    <li>python39Packages.python-binance</li>
    <li>python39Packages.pytibber</li>
    <li>python39Packages.roombapy</li>
    <li>python39Packages.samsungtvws</li>
    <li>python39Packages.sanic</li>
    <li>python39Packages.sanic-auth</li>
    <li>python39Packages.sanic-testing</li>
    <li>python39Packages.sense-energy</li>
    <li>python39Packages.simplisafe-python</li>
    <li>python39Packages.slack-sdk</li>
    <li>python39Packages.spyder</li>
    <li>python39Packages.strawberry-graphql</li>
    <li>python39Packages.systembridge</li>
    <li>python39Packages.tago</li>
    <li>python39Packages.tubeup</li>
    <li>python39Packages.twitchapi</li>
    <li>python39Packages.vallox-websocket-api</li>
    <li>python39Packages.vega</li>
    <li>python39Packages.volvooncall</li>
    <li>python39Packages.web3</li>
    <li>python39Packages.webargs</li>
    <li>python39Packages.websockets</li>
    <li>python39Packages.whirlpool-sixth-sense</li>
    <li>python39Packages.xarray-einstats</li>
    <li>python39Packages.yt-dlp</li>
    <li>python39Packages.yt-dlp-light</li>
    <li>python39Packages.zetup</li>
    <li>qimgv</li>
    <li>quarto</li>
    <li>radioboat</li>
    <li>sharedown</li>
    <li>somafm-cli</li>
    <li>soundux</li>
    <li>spotdl</li>
    <li>stremio</li>
    <li>sublime-music</li>
    <li>tandoor-recipes</li>
    <li>tartube-yt-dlp</li>
    <li>theharvester</li>
    <li>tribler</li>
    <li>urlwatch</li>
    <li>wtwitch</li>
    <li>ytcc</li>
    <li>ytfzf</li>
    <li>ytmdl</li>
  </ul>
</details>

**Review by dotlambda — APPROVED** [review]
The failures are unrelated.

**Pull request merged**
