### PR TITLE
maintainers: add jgarcia

### PR DESCRIPTION
**Pull request by chewblacka**
## Description of changes

Added jgarcia to list of maintainers

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
I don't want to be a pain in the butt here or be offensive, but the commit and PR title do not match the contributing guidelines at all here, so I doubt that we should merge this.

Sorry OP, maybe you want to re-read [the contributing guidelines](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md) and update this PR accordingly?

**Comment by chewblacka** [comment]
> I don't want to be a pain in the butt here or be offensive, but the commit and PR title do not match the contributing guidelines at all here, so I doubt that we should merge this.
> 
> Sorry OP, maybe you want to re-read [the contributing guidelines](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md) and update this PR accordingly?

Hi many thanks for the reply. If you could give me some guidance on what PR title and commit would be appropriate I'd be very grateful. As far as I can work out the CONTRIBUTING.md only mentions package changes, not adding to the maintainer list. Apologies if I've missed something obvious!

**Comment by matthiasbeyer** [comment]
If you have a look at the log of the file (`git log --oneline -- maintainers/maintainer-list.nix`), you'll see that commonly the commit message is `maintainers: add <username>`. That'd be a perfect PR title in this case as well.

**Comment by chewblacka** [comment]
> If you have a look at the log of the file (`git log --oneline -- maintainers/maintainer-list.nix`), you'll see that commonly the commit message is `maintainers: add <username>`. That'd be a perfect PR title in this case as well.

Much obliged! I have amended the title. Thanks again.

**Comment by matthiasbeyer** [comment]
Yes, please also fix the commit title, that'd be much appreciated!

**Comment by ius** [comment]
> As far as I can work out the CONTRIBUTING.md only mentions package changes, not adding to the maintainer list. Apologies if I've missed something obvious!

You didn't miss anything. I don't think it's mentioned in there. It's in [the manual](https://nixos.org/manual/nixpkgs/stable/#var-meta-maintainers) though.

**Comment by chewblacka** [comment]
> Yes, please also fix the commit title, that'd be much appreciated!

I'm just going to close this and submit a new request as it's way easier.

**Comment by matthiasbeyer** [comment]
That's not necessary, just `git commit --amend` the commit you pushed here and `git push` this with a little bit of `--force`.

**Comment by chewblacka** [comment]
> That's not necessary, just `git commit --amend` the commit you pushed here and `git push` this with a little bit of `--force`.

Thanks, next time I'll use the above method. In the mean time I've created a new pull request here: https://github.com/NixOS/nixpkgs/pull/248028

**Pull request closed without merging**
