### PR TITLE
gtetrinet: init at 0.7.11

### PR DESCRIPTION
**Pull request by chris-martin**
###### Motivation for this change

This was a great old game

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by disassembler** [comment]
builds fine and runs! merging! thanks for the contribution!

**Comment by orivej** [comment]
This needs `export GCONF_DISABLE_MAKEFILE_SCHEMA_INSTALL=1` to prevent a wall of warnings during install. I've commited that and various style fixes in https://github.com/NixOS/nixpkgs/commit/3dded417f6510641fb0c0011cc1243608a9f0e9f.

I expect the authors of pull requests to explain why git revision is not the tag with the version, especially when it differs from the tag with the version; but in this case it seems somewhat acceptable.

**Comment by chris-martin** [comment]
> I expect the authors of pull requests to explain why git revision is not the tag with the version, especially when it differs from the tag with the version; but in this case it seems somewhat acceptable.

For posterity: The reason is because this package hasn't been actively maintained since about a decade ago, and some fixes we need (like https://github.com/GNOME/gtetrinet/commit/717dc612a884011ec1c0e838db1c9c51b9e533c6) happened in the last few years but never made it into a new release version.

**Comment by chris-martin** [comment]
@orivej I put a line break in the argument list because the [manual](https://nixos.org/nixpkgs/manual/#sec-syntax) says

> Function formal arguments are written as:

>     { arg1, arg2, arg3 }:

> but if they don't fit on one line they're written as:

>     { arg1, arg2, arg3
>     , arg4, ...
>     , # Some comment...
>       argN
>     }:

It doesn't say how many characters consistutes "one line," so I guessed 80. Is that wrong? I'll PR to update the docs if I can find out what the correct style is.

**Comment by orivej** [comment]
Your indentation was fine, but I removed some dependencies and the list got shorter. (Some dependencies are subsumed by autoreconfHook, perl is an internal dependency of intltool and is not directly used by gtetrinet.)

**Comment by chris-martin** [comment]
Ah yes, sorry I misread.

Regarding the warning output, would you mind explaining why it matters (and should we mention that in the manual, perhaps in the [*Contributing*](https://nixos.org/nixpkgs/manual/#contributing) guide?), and how did you know to set the `GCONF_DISABLE_MAKEFILE_SCHEMA_INSTALL` variable to fix it?

**Comment by orivej** [comment]
The warnings are just inconvenient: for example, if someone changes a dependency of gtetrinet and tests all affected packages with nox-review, they may waste some time to check if the warnings are relevant or not, because they are very prominent; and they make any previous output hard to read, because they quickly scroll it away.

I've looked for how other packages deal with grome2.GConf (maybe there is way to actually install the schemas to avoid the warnings?) and found this variable used in https://github.com/NixOS/nixpkgs/blob/ef0486b1f91fc9df5a0d92a32765f3aa18be6345/pkgs/applications/misc/guake/default.nix#L50-52.

**Pull request merged**
