### PR TITLE
bazarr: 0.9.0.8 -> 0.9.2

### PR DESCRIPTION
**Pull request by andreisergiu98**
Bazarr now needs `unrar` and `ffmpeg` at runtime, if missing it will try to download them and crash. So I added them to path, tho I'm not sure if it's the correct way to do it.
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 115949` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>bazarr</li>
</ul>
</details>

**Review by drewrisinger — CHANGES_REQUESTED** [review]
* [x] Diff LGTM
* [ ] Commits could be squashed together
* [x] Builds for me via ``nix-review`` on x86-64-linux
* [ ] Doesn't start when launched from command-line, see below

```
1 package built:
bazarr

warning: ignoring the user-specified setting 'experimental-features', because it is a restricted setting and you are not a trusted user
$ nix-shell ~/.cache/nixpkgs-review/pr-115949/shell.nix

[nix-shell:~/.cache/nixpkgs-review/pr-115949]$ bazarr 
Bazarr starting...
BAZARR The configuration directory doesn't exist and Bazarr cannot create it (permission issue?).
Bazarr exited.

[nix-shell:~/.cache/nixpkgs-review/pr-115949]$ bazarr --help
usage: bazarr.py [-h] [-c DIR] [-p PORT] [--no-update [BOOL]] [--debug [BOOL]] [--release-update [BOOL]] [--dev [BOOL]]
                 [--no-tasks [BOOL]]

optional arguments:
  -h, --help            show this help message and exit
  -c DIR, --config DIR  Directory containing the configuration (default: /nix/store/70j8vq1fy711idmvc6d0cccm7zysd2zs-
                        bazarr-0.9.2/src/data)
  -p PORT, --port PORT  Port number (default: 6767)
  --no-update [BOOL]    Disable update functionality (default: False)
  --debug [BOOL]        Enable console debugging (default: False)
  --release-update [BOOL]
                        Enable file based updater (default: False)
  --dev [BOOL]          Enable developer mode (default: False)
  --no-tasks [BOOL]     Disable all tasks (default: False)
```

**Comment by andreisergiu98** [comment]
> Doesn't start when launched from command-line, see below

It's not starting because it's trying to create configuration files inside the store by default `Directory containing the configuration (default: /nix/store/70j8vq1fy711idmvc6d0cccm7zysd2zs-bazarr-0.9.2/src/data` which is read-only. It should work with the right directory.

**Comment by andreisergiu98** [comment]
@drewrisinger what must be further done to get this merged, should I squash commits together?

**Comment by andreisergiu98** [comment]
@SuperSandro2000 Now that this PR got merged you can close https://github.com/NixOS/nixpkgs/pull/113252

**Pull request merged**
