### PR TITLE
binutils: 2.31.1 -> 2.34

### PR DESCRIPTION
**Pull request by lovesegfault**
###### Motivation for this change
Trying #85951 again as it had to be reverted.

cc. @flokli @pbogdan @thefloweringash

Closes #78204

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lovesegfault** [comment]
Please see https://github.com/NixOS/nixpkgs/pull/85951#issuecomment-619601978 and https://github.com/NixOS/nixpkgs/pull/85951#issuecomment-624025143.

Still unclear on how to solve the (apparent) bootstrapping issue.

**Comment by pbogdan** [comment]
I don't feel confident enough to say if it's a good / bad idea but this patch:

```diff
diff --git a/pkgs/development/libraries/glibc/common.nix b/pkgs/development/libraries/glibc/common.nix
index 0429c7295fb..52fa7191cb7 100644
--- a/pkgs/development/libraries/glibc/common.nix
+++ b/pkgs/development/libraries/glibc/common.nix
@@ -203,7 +203,7 @@ stdenv.mkDerivation ({
     configureScript="`pwd`/../$sourceRoot/configure"
 
     ${lib.optionalString (stdenv.cc.libc != null)
-      ''makeFlags="$makeFlags BUILD_LDFLAGS=-Wl,-rpath,${stdenv.cc.libc}/lib"''
+      ''makeFlags="$makeFlags BUILD_LDFLAGS=-Wl,-rpath,${stdenv.cc.libc}/lib OBJDUMP=${stdenv.cc.bintools.bintools}/bin/objdump"''
     }
```
does fix the issue with the generation of the stub functions and at least confirms what @thefloweringash found. I don't know if there's a better way to somehow line up the binutils tools that are included in the stdenv with other tools like `objdump` which at that stage get pulled from the bootstrap tools as I understand it.

**Comment by lovesegfault** [comment]
Alright, @pbogdan's patch solved the issue and the full bootstrap seems to work now. Managed to build `opencv`, `linux_latest`, and `twelf`, all of which failed previously.

**Comment by flokli** [comment]
@lovesegfault just to confirm - with "bootstrap", you meant building `opencv`, `linux_latest` and `twelf`, not creating new bootstrap binaries, right?

**Comment by lovesegfault** [comment]
@flokli That's correct.

**Comment by flokli** [comment]
I'd say let's cook this in staging :-)

**Comment by FRidh** [comment]
Fix for a missing change c10f0a32d26832a419e294765244eb05fda650a9

Note Python's cffi's tests fail with this bump.

**Comment by flokli** [comment]
@FRidh I'm not sure I really understand some of these test failures:
```
______________________________ test_load_library _______________________________

    def test_load_library():
>       x = find_and_load_library('c')

c/test_c.py:73: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'c', flags = 2

    def find_and_load_library(name, flags=RTLD_NOW):
        import ctypes.util
        if name is None:
            path = None
        else:
            path = ctypes.util.find_library(name)
            if path is None and name == 'c':
>               assert sys.platform == 'win32'
E               AssertionError: assert 'linux' == 'win32'
E                 - win32
E                 + linux

```
Why does this code think the platform should be win32? :confused:

**Comment by FRidh** [comment]
Most because `find_library` returned `None`, and that is something that absolutely should not happen.

```
$ nix-shell -p python3 --pure --run "python3 -c 'import ctypes.util; print(ctypes.util.find_library(\"c\"))'"
```
functions fine though.

**Comment by flokli** [comment]
@lovesegfault any idea what's going on here?

**Comment by lovesegfault** [comment]
I do not, maybe @pbogdan or @thefloweringash do.

We may need to revert this _again_ :(

**Comment by pbogdan** [comment]
I don't know either, sorry :-(. Agreed it might need another revert to not block other important changes in staging.

**Comment by thefloweringash** [comment]
`find_library("c")` is calling `ld -t -o /dev/null -lc` in [`_findLib_ld`][]. In current master, this returns only shared objects while on staging this is returning scripts and archives too. Python takes the first result that matches a simple filter and tries to use it as a shared object. The first returned item is now `libc.so`, instead of `libc.so.6`. `libc.so` is a plain-text script, so this fails and ultimately returns `None`. There was a change in binutils ([727a29b][]) that looks suspicious:

[`_findLib_ld`]: https://github.com/python/cpython/blob/af23f0d3cf19343512e6ca1fe1d46a5dbe425719/Lib/ctypes/util.py#L287-L307
[simple filter]: https://github.com/python/cpython/blob/af23f0d3cf19343512e6ca1fe1d46a5dbe425719/Lib/ctypes/util.py#L289
[727a29b]: https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=727a29badd95a68d08b86fec0b98702ce756c660
[`find_library`]: https://github.com/python/cpython/blob/af23f0d3cf19343512e6ca1fe1d46a5dbe425719/Lib/ctypes/util.py#L309-L312

> Report scripts and libraries searched for ld --trace

It seems like python's `_findLib_ld` doesn't handle this use change. This probably isn't a widespread problem since it's a fallback method for [`find_library`][].

---

```
# recent unstable
$ nix-shell --pure -p hello --run 'ld -t -o /dev/null -lc'
/nix/store/a57856fs4m8ir6vlv14h3gq3sv9aq2lb-binutils-2.31.1/bin/ld: mode elf_x86_64
/nix/store/nwsn18fysga1n5s0bj4jp4wfwvlbx8b1-glibc-2.30/lib/libc.so.6
/nix/store/nwsn18fysga1n5s0bj4jp4wfwvlbx8b1-glibc-2.30/lib/ld-linux-x86-64.so.2
/nix/store/nwsn18fysga1n5s0bj4jp4wfwvlbx8b1-glibc-2.30/lib/ld-linux-x86-64.so.2
/nix/store/a57856fs4m8ir6vlv14h3gq3sv9aq2lb-binutils-2.31.1/bin/ld: warning: cannot find entry symbol _start; not setting start address
```

```
# current staging
$ nix-shell --pure -p hello --run 'ld -t -o /dev/null -lc'
/nix/store/j1l6ds4mhm97nqw965w9sg07i9fric4d-glibc-2.30/lib/libc.so
/nix/store/j1l6ds4mhm97nqw965w9sg07i9fric4d-glibc-2.30/lib/libc.so.6
/nix/store/j1l6ds4mhm97nqw965w9sg07i9fric4d-glibc-2.30/lib/libc_nonshared.a
/nix/store/j1l6ds4mhm97nqw965w9sg07i9fric4d-glibc-2.30/lib/ld-linux-x86-64.so.2
/nix/store/j1l6ds4mhm97nqw965w9sg07i9fric4d-glibc-2.30/lib/libc_nonshared.a
/nix/store/j1l6ds4mhm97nqw965w9sg07i9fric4d-glibc-2.30/lib/ld-linux-x86-64.so.2
/nix/store/j284mk8hdv9ccxfdlhcdk1lg2jml4fhk-binutils-2.34/bin/ld: warning: cannot find entry symbol _start; not setting start address
```

**Comment by FRidh** [comment]
Thanks for investigating @thefloweringash . I did not realize `libc.so` was a text file. So, in my test I forgot to set `nixpkgs=.`, sigh. Indeed, it will return `None` as expected to be the problem.

Using `_findLib_ld` is actually the only method we use for finding libraries, considering the other methods (ldconfig, gcc) have been patched out.

To me this seems now like an upstream Python issue. Either we can try and fix the regex ourselves, or we need to revert the binutils update and try yet again later.

**Comment by thefloweringash** [comment]
> Either we can try and fix the regex ourselves

I don't think this can be fixed by filtering the list by filename. A `*.so` file is an input for GNU ld which might be a shared library, symlink to a shared library, or a linker script as seen here. `ld` is now reporting all files and revealing the presence of the linker script. It's likely sufficient to return the first thing that's actually a shared library, but I don't see a way to do that without opening each file and inspecting the contents. An easy way would be to go through the list and return the first one that returns a value from `_get_soname`.

**Comment by FRidh** [comment]
Actually, we may not *have* to fix this. In principle we do not support `find_library`. Packages are required to include hardcoded paths to libraries, thereby circumventing `load_library`.

**Comment by FRidh** [comment]
numpy also fails, but with "ELF load command address/offset not properly aligned". Too much stripped? https://hydra.nixos.org/build/118901023
```
$ ldd /nix/store/riqyzfjpskh0qf46f5fjc8ldqbp8aj85-python3.7-numpy-1.18.4/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so 
/nix/store/riqyzfjpskh0qf46f5fjc8ldqbp8aj85-python3.7-numpy-1.18.4/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so: error while loading shared libraries: liblapack.so.3: ELF load command address/offset not properly aligned
```

**Comment by vcunat** [comment]
So... we revert for a while again?  So far I haven't noticed anything that needs the new version.  I'd hope that upstream helps to resolve this within a couple weeks.

**Comment by FRidh** [comment]
Yep, already doing the revert.

**Comment by vcunat** [comment]
Hmm, CVEs are reported for 2.31.1: https://github.com/NixOS/nixpkgs/issues/63061  so I wonder if there's a version in-between that fixes them but doesn't break python yet.

**Comment by lovesegfault** [comment]
The battle to bump binutils rages on! See you guys in the next episode of the binutils Iliad

**Pull request merged**
