### PR TITLE
[22.11] nixos/headscale: Update openidconnect options to be in sync with package

### PR DESCRIPTION
**Pull request by D4ndellion**
###### Description of changes

Updated openIdConnect options to match the config options available in the version actually used on 22.11

I've also hidden the option that isn't applicable anymore so people won't be confused when looking at the available options in the man page

This is only a problem for 22.11 as on master #203938 was merged

On a related note:

I think it headscale might fit the bill for something that can be backported even with breaking changes - since it relies heavily on external infrastructure and client applications, but maintaining two separate modules like this would be a pain.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kradalby** [comment]
Hi, great to add the ones I've missed earlier.

The module went through a large rewrite in https://github.com/NixOS/nixpkgs/commit/571780384a4327b5af15c411b23e318be5cfc9f0 which makes the config format conform with RFC0042, These options are still missing on master, so would be great to get them in there: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/headscale.nix#L276-L313.

As for 22.11, I am not actually sure what the process is to get it backported, maybe we should start with getting these into master, then look at the backporting?

**Comment by dali99** [comment]
I'd say we should merge this first, so that it's at all possible to configure oidc on 22.11, then we can open a discussion about backporting the module from master later.

As for adding these options to the module on master, I'll file a PR for it, but it's orthogonal to this PR, and is not a pressing concern since it's a freeform module

**Comment by kradalby** [comment]
> so that it's at all possible to configure oidc on 22.11

It is _possible_, but its a bit opaque by passing it to the [`services.headscale.settings`](https://search.nixos.org/options?channel=22.11&show=services.headscale.settings&from=0&size=50&sort=relevance&type=packages&query=headscale.settings).

Otherwise I am happy with getting them in as long as we also get it in `master`.

**Review by kradalby — APPROVED** [review]

**Comment by dali99** [comment]
oh, you're right of course, I read "Overrides to config.yaml" as "Overrides config.yaml", coupled with the PR on master that changed settings into a freeform module, and didn't look into it any further. My bad!

**Pull request closed without merging**
