### PR TITLE
Backport KDE 5.8.2 upgrades to release-16.09

### PR DESCRIPTION
**Pull request by grahamc**
###### Motivation for this change

https://github.com/NixOS/nixpkgs/issues/19678

@ttuegel asked me to see if these applied cleanly. They seem to, I'm building the changes to see how it goes.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
Newly broken:

 - powerdevil
 - plasma-workspace
 - startkde (?)
 - kdeplasma-addons
 - plasma-desktop
 - kwin
 - khotkeys

build log:

```
# nix-build --keep-going -A kde5.kinfocenter -A kde5.kwin -A kdevelop -A kde5.kmenuedit -A kde5.plasma-integration -A kde5.milou -A kde5.kwrited -A kde5.kwallet-pam -A kde5.breeze-qt5 -A kde5.kactivitymanagerd -A kde5.plasma-pa -A kde5.ksysguard -A kde5.kdeplasma-addons -A kde5.bluedevil -A kde5.plasma-workspace -A kde5.startkde -A kde5.breeze-grub -A kde5.polkit-kde-agent -A kde5.spectacle -A kde5.breeze-qt4 -A kde5.kdecoration -A kde5.breeze -A kde5.oxygen -A kde5.kgamma5 -A kde5.plasma-desktop -A kde5.kwayland-integration -A kde5.plasma-workspace-wallpapers -A kde5.kde-gtk-config -A kde5.powerdevil -A kde5.kscreen -A kde5.libksysguard -A kde5.khotkeys -A kde5.kde-cli-tools -A kde5.systemsettings -A kde5.ksshaskpass -A kde5.breeze-plymouth -A kde5.breeze-gtk -A kde5.libkscreen -A kde5.plasma-nm -A kde5.kscreenlocker /root/nixpkgs
these derivations will be built:
  /nix/store/vzbnpy5m59h8nfga1amq27gkbb1dkjw7-kwin-5.8.2.drv
  /nix/store/7ggp0j8vmk38j22mhz5imrnwvna8d74f-plasma-workspace-5.8.2.drv
  /nix/store/3vz7xk99lcz2b9l3iw6xirvz3l2i14r6-powerdevil-5.8.2.drv
  /nix/store/afl3fh1wq5pfnhm5iq372ym37z9src8j-startkde.drv
  /nix/store/fzm3ywdzc6la94xk1l6929lyfcz5lzxz-kdeplasma-addons-5.8.2.drv
  /nix/store/gi6jd9ya3ayx78jm11i0h6rix82d78q1-plasma-desktop-5.8.2.drv
  /nix/store/y8p48xkxrfdnxzjas1bqqf37zcin5kjd-khotkeys-5.8.2.drv
building path(s) ‘/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2’, ‘/nix/store/v4pk5yknkb4vp12db2l9xgf2w36zabbg-kwin-5.8.2-dev’
unpacking sources
unpacking source archive /nix/store/cjz0i27g6b6jx0in0cp2za8jgpc7f14b-kwin-5.8.2.tar.xz
source root is kwin-5.8.2
setting SOURCE_DATE_EPOCH to timestamp 1476790710 of file kwin-5.8.2/doc/CMakeLists.txt
patching sources
applying patch /nix/store/kna6r22hmsp5kfwwwyqprfk6pbknf139-follow-symlinks.patch
patching file plugins/kdecorations/aurorae/src/aurorae.cpp
applying patch /nix/store/zmlg29nz4sidwpv039n7596pdy44b30k-xwayland.patch
patching file main_wayland.cpp
Hunk #1 succeeded at 317 (offset 2 lines).
configuring
qmake: File exists
fixing cmake files...
cmake flags: -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_BUILD_RPATH=ON -DCMAKE_INSTALL_INCLUDEDIR=/nix/store/v4pk5yknkb4vp12db2l9xgf2w36zabbg-kwin-5.8.2-dev/include -DCMAKE_INSTALL_LIBDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/lib -DCMAKE_INSTALL_NAME_DIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/lib -DCMAKE_INSTALL_PREFIX=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2 -DCMAKE_SKIP_BUILD_RPATH=OFF -DBUILD_TESTING=OFF -DKDE_INSTALL_EXECROOTDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2 -DKDE_INSTALL_BINDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/bin -DKDE_INSTALL_SBINDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/sbin -DKDE_INSTALL_LIBDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/lib -DKDE_INSTALL_LIBEXECDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/lib/libexec -DKDE_INSTALL_CMAKEPACKAGEDIR=/nix/store/v4pk5yknkb4vp12db2l9xgf2w36zabbg-kwin-5.8.2-dev/lib/cmake -DKDE_INSTALL_QTPLUGINDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/lib/qt5/plugins -DKDE_INSTALL_PLUGINDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/lib/qt5/plugins -DKDE_INSTALL_QTQUICKIMPORTSDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/lib/qt5/imports -DKDE_INSTALL_QMLDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/lib/qt5/qml -DKDE_INSTALL_INCLUDEDIR=/nix/store/v4pk5yknkb4vp12db2l9xgf2w36zabbg-kwin-5.8.2-dev/include -DKDE_INSTALL_LOCALSTATEDIR=/var -DKDE_INSTALL_DATAROOTDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/share -DKDE_INSTALL_DATADIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/share -DKDE_INSTALL_DOCBUNDLEDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/share/doc/HTML -DKDE_INSTALL_KCFGDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/share/config.kcfg -DKDE_INSTALL_KCONFUPDATEDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/share/kconf_update -DKDE_INSTALL_KSERVICES5DIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/share/kservices5 -DKDE_INSTALL_KSERVICETYPES5DIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/share/kservicetypes5 -DKDE_INSTALL_KXMLGUI5DIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/share/kxmlgui5 -DKDE_INSTALL_KNOTIFY5RCDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/share/knotifications5 -DKDE_INSTALL_ICONDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/share/icons -DKDE_INSTALL_LOCALEDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/share/locale -DKDE_INSTALL_SOUNDDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/share/sounds -DKDE_INSTALL_TEMPLATEDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/share/templates -DKDE_INSTALL_WALLPAPERDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/share/wallpapers -DKDE_INSTALL_APPDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/share/applications -DKDE_INSTALL_DESKTOPDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/share/desktop-directories -DKDE_INSTALL_MIMEDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/share/mime/packages -DKDE_INSTALL_METAINFODIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/share/appdata -DKDE_INSTALL_MANDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/share/man -DKDE_INSTALL_INFODIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/share/info -DKDE_INSTALL_DBUSDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/share/dbus-1 -DKDE_INSTALL_DBUSINTERFACEDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/share/dbus-1/interfaces -DKDE_INSTALL_DBUSSERVICEDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/share/dbus-1/services -DKDE_INSTALL_DBUSSYSTEMSERVICEDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/share/dbus-1/system-services -DKDE_INSTALL_SYSCONFDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/etc -DKDE_INSTALL_CONFDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/etc/xdg -DKDE_INSTALL_AUTOSTARTDIR=/nix/store/i5hib0jaqmjkm7x0vmjwiyfp16ly8acd-kwin-5.8.2/etc/xdg/autostart 
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /nix/store/dp2nf60lqzy1kbhd78ndf5nm3fb3qicd-gcc-wrapper-5.4.0/bin/gcc
-- Check for working C compiler: /nix/store/dp2nf60lqzy1kbhd78ndf5nm3fb3qicd-gcc-wrapper-5.4.0/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /nix/store/dp2nf60lqzy1kbhd78ndf5nm3fb3qicd-gcc-wrapper-5.4.0/bin/g++
-- Check for working CXX compiler: /nix/store/dp2nf60lqzy1kbhd78ndf5nm3fb3qicd-gcc-wrapper-5.4.0/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
CMake Warning at /nix/store/16ihm9cqj2vipf0syr81xxl091xz5mvy-extra-cmake-modules-5.24.0/share/ECM/find-modules/FindKF5.cmake:74 (find_package):
  Could not find a configuration file for package "KF5Config" that is
  compatible with requested version "5.26.0".

  The following configuration files were considered but not accepted:

    /nix/store/9csfqd71mzxiih6i10knxrgpfqqqz15n-kconfig-5.24.0-dev/lib/cmake/KF5Config/KF5ConfigConfig.cmake, version: 5.24.0

Call Stack (most recent call first):
  CMakeLists.txt:66 (find_package)


-- Could NOT find KF5Config , checked the following files:
    /nix/store/9csfqd71mzxiih6i10knxrgpfqqqz15n-kconfig-5.24.0-dev/lib/cmake/KF5Config/KF5ConfigConfig.cmake (version 5.24.0)

CMake Warning at /nix/store/16ihm9cqj2vipf0syr81xxl091xz5mvy-extra-cmake-modules-5.24.0/share/ECM/find-modules/FindKF5.cmake:74 (find_package):
  Could not find a configuration file for package "KF5ConfigWidgets" that is
  compatible with requested version "5.26.0".

  The following configuration files were considered but not accepted:

    /nix/store/vcy1s9sch2215w3zx7nxr7xk3pcbsqz6-kconfigwidgets-5.24.0-dev/lib/cmake/KF5ConfigWidgets/KF5ConfigWidgetsConfig.cmake, version: 5.24.0

Call Stack (most recent call first):
  CMakeLists.txt:66 (find_package)


-- Could NOT find KF5ConfigWidgets , checked the following files:
    /nix/store/vcy1s9sch2215w3zx7nxr7xk3pcbsqz6-kconfigwidgets-5.24.0-dev/lib/cmake/KF5ConfigWidgets/KF5ConfigWidgetsConfig.cmake (version 5.24.0)

CMake Warning at /nix/store/16ihm9cqj2vipf0syr81xxl091xz5mvy-extra-cmake-modules-5.24.0/share/ECM/find-modules/FindKF5.cmake:74 (find_package):
  Could not find a configuration file for package "KF5CoreAddons" that is
  compatible with requested version "5.26.0".

  The following configuration files were considered but not accepted:

    /nix/store/hblrl3xxw2j2m791lrh76w774b37y4q2-kcoreaddons-5.24.0-dev/lib/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake, version: 5.24.0

Call Stack (most recent call first):
  CMakeLists.txt:66 (find_package)


-- Could NOT find KF5CoreAddons , checked the following files:
    /nix/store/hblrl3xxw2j2m791lrh76w774b37y4q2-kcoreaddons-5.24.0-dev/lib/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake (version 5.24.0)

CMake Warning at /nix/store/16ihm9cqj2vipf0syr81xxl091xz5mvy-extra-cmake-modules-5.24.0/share/ECM/find-modules/FindKF5.cmake:74 (find_package):
  Could not find a configuration file for package "KF5Crash" that is
  compatible with requested version "5.26.0".

  The following configuration files were considered but not accepted:

    /nix/store/7mykm2jnwn1h7c79322asvs369j0kf3f-kcrash-5.24.0-dev/lib/cmake/KF5Crash/KF5CrashConfig.cmake, version: 5.24.0

Call Stack (most recent call first):
  CMakeLists.txt:66 (find_package)


-- Could NOT find KF5Crash , checked the following files:
    /nix/store/7mykm2jnwn1h7c79322asvs369j0kf3f-kcrash-5.24.0-dev/lib/cmake/KF5Crash/KF5CrashConfig.cmake (version 5.24.0)

CMake Warning at /nix/store/16ihm9cqj2vipf0syr81xxl091xz5mvy-extra-cmake-modules-5.24.0/share/ECM/find-modules/FindKF5.cmake:74 (find_package):
  Could not find a configuration file for package "KF5GlobalAccel" that is
  compatible with requested version "5.26.0".

  The following configuration files were considered but not accepted:

    /nix/store/s51yrsp6zh8xir93lvblq86alg7v9iiy-kglobalaccel-5.24.0-dev/lib/cmake/KF5GlobalAccel/KF5GlobalAccelConfig.cmake, version: 5.24.0

Call Stack (most recent call first):
  CMakeLists.txt:66 (find_package)


-- Could NOT find KF5GlobalAccel , checked the following files:
    /nix/store/s51yrsp6zh8xir93lvblq86alg7v9iiy-kglobalaccel-5.24.0-dev/lib/cmake/KF5GlobalAccel/KF5GlobalAccelConfig.cmake (version 5.24.0)

CMake Warning at /nix/store/16ihm9cqj2vipf0syr81xxl091xz5mvy-extra-cmake-modules-5.24.0/share/ECM/find-modules/FindKF5.cmake:74 (find_package):
  Could not find a configuration file for package "KF5I18n" that is
  compatible with requested version "5.26.0".

  The following configuration files were considered but not accepted:

    /nix/store/mmkqjrimkkjfbjf0c3dy0l9w850q11xa-ki18n-5.24.0-dev/lib/cmake/KF5I18n/KF5I18nConfig.cmake, version: 5.24.0

Call Stack (most recent call first):
  CMakeLists.txt:66 (find_package)


-- Could NOT find KF5I18n , checked the following files:
    /nix/store/mmkqjrimkkjfbjf0c3dy0l9w850q11xa-ki18n-5.24.0-dev/lib/cmake/KF5I18n/KF5I18nConfig.cmake (version 5.24.0)

CMake Warning at /nix/store/16ihm9cqj2vipf0syr81xxl091xz5mvy-extra-cmake-modules-5.24.0/share/ECM/find-modules/FindKF5.cmake:74 (find_package):
  Could not find a configuration file for package "KF5Init" that is
  compatible with requested version "5.26.0".

  The following configuration files were considered but not accepted:

    /nix/store/8xsjn5ywwl1xvn2bn24h0nbh8a6gyxvn-kinit-5.24.0-dev/lib/cmake/KF5Init/KF5InitConfig.cmake, version: 5.24.0

Call Stack (most recent call first):
  CMakeLists.txt:66 (find_package)


-- Could NOT find KF5Init , checked the following files:
    /nix/store/8xsjn5ywwl1xvn2bn24h0nbh8a6gyxvn-kinit-5.24.0-dev/lib/cmake/KF5Init/KF5InitConfig.cmake (version 5.24.0)

CMake Warning at /nix/store/16ihm9cqj2vipf0syr81xxl091xz5mvy-extra-cmake-modules-5.24.0/share/ECM/find-modules/FindKF5.cmake:74 (find_package):
  Could not find a configuration file for package "KF5Notifications" that is
  compatible with requested version "5.26.0".

  The following configuration files were considered but not accepted:

    /nix/store/hw9hyxiz9l9pl8i1qa3mn1prn852lrca-knotifications-5.24.0-dev/lib/cmake/KF5Notifications/KF5NotificationsConfig.cmake, version: 5.24.0

Call Stack (most recent call first):
  CMakeLists.txt:66 (find_package)


-- Could NOT find KF5Notifications , checked the following files:
    /nix/store/hw9hyxiz9l9pl8i1qa3mn1prn852lrca-knotifications-5.24.0-dev/lib/cmake/KF5Notifications/KF5NotificationsConfig.cmake (version 5.24.0)

CMake Warning at /nix/store/16ihm9cqj2vipf0syr81xxl091xz5mvy-extra-cmake-modules-5.24.0/share/ECM/find-modules/FindKF5.cmake:74 (find_package):
  Could not find a configuration file for package "KF5Package" that is
  compatible with requested version "5.26.0".

  The following configuration files were considered but not accepted:

    /nix/store/g6z45zhmyyirqc7n9vr6vmihq288sxp9-kpackage-5.24.0-dev/lib/cmake/KF5Package/KF5PackageConfig.cmake, version: 5.24.0

Call Stack (most recent call first):
  CMakeLists.txt:66 (find_package)


-- Could NOT find KF5Package , checked the following files:
    /nix/store/g6z45zhmyyirqc7n9vr6vmihq288sxp9-kpackage-5.24.0-dev/lib/cmake/KF5Package/KF5PackageConfig.cmake (version 5.24.0)

CMake Warning at /nix/store/16ihm9cqj2vipf0syr81xxl091xz5mvy-extra-cmake-modules-5.24.0/share/ECM/find-modules/FindKF5.cmake:74 (find_package):
  Could not find a configuration file for package "KF5Plasma" that is
  compatible with requested version "5.26.0".

  The following configuration files were considered but not accepted:

    /nix/store/3pgxcarbldf6431gfhads2sgxpmil02k-plasma-framework-5.24.0-dev/lib/cmake/KF5Plasma/KF5PlasmaConfig.cmake, version: 5.24.0

Call Stack (most recent call first):
  CMakeLists.txt:66 (find_package)


-- Could NOT find KF5Plasma , checked the following files:
    /nix/store/3pgxcarbldf6431gfhads2sgxpmil02k-plasma-framework-5.24.0-dev/lib/cmake/KF5Plasma/KF5PlasmaConfig.cmake (version 5.24.0)

CMake Warning at /nix/store/16ihm9cqj2vipf0syr81xxl091xz5mvy-extra-cmake-modules-5.24.0/share/ECM/find-modules/FindKF5.cmake:74 (find_package):
  Could not find a configuration file for package "KF5WidgetsAddons" that is
  compatible with requested version "5.26.0".

  The following configuration files were considered but not accepted:

    /nix/store/mgds9yxk26p5a0lx31s9fprd1iv1x5bn-kwidgetsaddons-5.24.0-dev/lib/cmake/KF5WidgetsAddons/KF5WidgetsAddonsConfig.cmake, version: 5.24.0

Call Stack (most recent call first):
  CMakeLists.txt:66 (find_package)


-- Could NOT find KF5WidgetsAddons , checked the following files:
    /nix/store/mgds9yxk26p5a0lx31s9fprd1iv1x5bn-kwidgetsaddons-5.24.0-dev/lib/cmake/KF5WidgetsAddons/KF5WidgetsAddonsConfig.cmake (version 5.24.0)

CMake Warning at /nix/store/16ihm9cqj2vipf0syr81xxl091xz5mvy-extra-cmake-modules-5.24.0/share/ECM/find-modules/FindKF5.cmake:74 (find_package):
  Could not find a configuration file for package "KF5WindowSystem" that is
  compatible with requested version "5.26.0".

  The following configuration files were considered but not accepted:

    /nix/store/m52agimi3x5yc4qip4p21245g4hq8afw-kwindowsystem-5.24.0-dev/lib/cmake/KF5WindowSystem/KF5WindowSystemConfig.cmake, version: 5.24.0

Call Stack (most recent call first):
  CMakeLists.txt:66 (find_package)


-- Could NOT find KF5WindowSystem , checked the following files:
    /nix/store/m52agimi3x5yc4qip4p21245g4hq8afw-kwindowsystem-5.24.0-dev/lib/cmake/KF5WindowSystem/KF5WindowSystemConfig.cmake (version 5.24.0)

CMake Warning at /nix/store/16ihm9cqj2vipf0syr81xxl091xz5mvy-extra-cmake-modules-5.24.0/share/ECM/find-modules/FindKF5.cmake:74 (find_package):
  Could not find a configuration file for package "KF5IconThemes" that is
  compatible with requested version "5.26.0".

  The following configuration files were considered but not accepted:

    /nix/store/gpm2s6d62y1x38a8a9j7yk54yz62qscm-kiconthemes-5.24.0-dev/lib/cmake/KF5IconThemes/KF5IconThemesConfig.cmake, version: 5.24.0

Call Stack (most recent call first):
  CMakeLists.txt:66 (find_package)


-- Could NOT find KF5IconThemes , checked the following files:
    /nix/store/gpm2s6d62y1x38a8a9j7yk54yz62qscm-kiconthemes-5.24.0-dev/lib/cmake/KF5IconThemes/KF5IconThemesConfig.cmake (version 5.24.0)

CMake Warning at /nix/store/16ihm9cqj2vipf0syr81xxl091xz5mvy-extra-cmake-modules-5.24.0/share/ECM/find-modules/FindKF5.cmake:74 (find_package):
  Could not find a configuration file for package "KF5IdleTime" that is
  compatible with requested version "5.26.0".

  The following configuration files were considered but not accepted:

    /nix/store/v7w6b1f5kabsqzma0p642w3pmpqdx079-kidletime-5.24.0-dev/lib/cmake/KF5IdleTime/KF5IdleTimeConfig.cmake, version: 5.24.0

Call Stack (most recent call first):
  CMakeLists.txt:66 (find_package)


-- Could NOT find KF5IdleTime , checked the following files:
    /nix/store/v7w6b1f5kabsqzma0p642w3pmpqdx079-kidletime-5.24.0-dev/lib/cmake/KF5IdleTime/KF5IdleTimeConfig.cmake (version 5.24.0)

CMake Warning at /nix/store/16ihm9cqj2vipf0syr81xxl091xz5mvy-extra-cmake-modules-5.24.0/share/ECM/find-modules/FindKF5.cmake:74 (find_package):
  Could not find a configuration file for package "KF5Wayland" that is
  compatible with requested version "5.26.0".

  The following configuration files were considered but not accepted:

    /nix/store/apd51jxy3r9740rhgw0a1653v1r45hgv-kwayland-5.24.0-dev/lib/cmake/KF5Wayland/KF5WaylandConfig.cmake, version: 5.24.0

Call Stack (most recent call first):
  CMakeLists.txt:66 (find_package)


-- Could NOT find KF5Wayland , checked the following files:
    /nix/store/apd51jxy3r9740rhgw0a1653v1r45hgv-kwayland-5.24.0-dev/lib/cmake/KF5Wayland/KF5WaylandConfig.cmake (version 5.24.0)

CMake Error at /nix/store/9cpbpp4qy9blfippj8g9k5parrm46llh-cmake-3.6.0/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find KF5 (missing: Config ConfigWidgets CoreAddons Crash
  GlobalAccel I18n Init Notifications Package Plasma WidgetsAddons
  WindowSystem IconThemes IdleTime Wayland) (Required is at least version
  "5.26.0")
Call Stack (most recent call first):
  /nix/store/9cpbpp4qy9blfippj8g9k5parrm46llh-cmake-3.6.0/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /nix/store/16ihm9cqj2vipf0syr81xxl091xz5mvy-extra-cmake-modules-5.24.0/share/ECM/find-modules/FindKF5.cmake:110 (find_package_handle_standard_args)
  CMakeLists.txt:66 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/nix-build-kwin-5.8.2.drv-0/kwin-5.8.2/build/CMakeFiles/CMakeOutput.log".
builder for ‘/nix/store/vzbnpy5m59h8nfga1amq27gkbb1dkjw7-kwin-5.8.2.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/7ggp0j8vmk38j22mhz5imrnwvna8d74f-plasma-workspace-5.8.2.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/fzm3ywdzc6la94xk1l6929lyfcz5lzxz-kdeplasma-addons-5.8.2.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/y8p48xkxrfdnxzjas1bqqf37zcin5kjd-khotkeys-5.8.2.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/gi6jd9ya3ayx78jm11i0h6rix82d78q1-plasma-desktop-5.8.2.drv’: 2 dependencies couldn't be built
cannot build derivation ‘/nix/store/3vz7xk99lcz2b9l3iw6xirvz3l2i14r6-powerdevil-5.8.2.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/afl3fh1wq5pfnhm5iq372ym37z9src8j-startkde.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/3vz7xk99lcz2b9l3iw6xirvz3l2i14r6-powerdevil-5.8.2.drv’, ‘/nix/store/7ggp0j8vmk38j22mhz5imrnwvna8d74f-plasma-workspace-5.8.2.drv’, ‘/nix/store/afl3fh1wq5pfnhm5iq372ym37z9src8j-startkde.drv’, ‘/nix/store/fzm3ywdzc6la94xk1l6929lyfcz5lzxz-kdeplasma-addons-5.8.2.drv’, ‘/nix/store/gi6jd9ya3ayx78jm11i0h6rix82d78q1-plasma-desktop-5.8.2.drv’, ‘/nix/store/vzbnpy5m59h8nfga1amq27gkbb1dkjw7-kwin-5.8.2.drv’, ‘/nix/store/y8p48xkxrfdnxzjas1bqqf37zcin5kjd-khotkeys-5.8.2.drv’ failed
```

any thoughts @ttuegel?

**Comment by ttuegel** [comment]
> any thoughts @ttuegel?

It looks like it needs the KDE Frameworks 5.26 update to be backported, too.

**Comment by grahamc** [comment]
@ttuegel I'm still having build failures:

```
‘/nix/store/cksi5ab452igjpknbv9flaq3fgm0ljb3-kwooty-1.1.0.drv’,
‘/nix/store/drqc51sk2qkiay4fazm6d8f7drh2i0s2-kmplayer-0.11.3d.drv’,
‘/nix/store/mv5g9ad20p8l8l6smyb90hnzhx44j5fd-plasma-framework-5.26.0.drv’,
‘/nix/store/w4068aaiqvkad06iyswj6qh2648lll8x-krunner-5.26.0.drv’
```

did I miss other commits too?

**Comment by ttuegel** [comment]
I think you're missing 16dafb018e09363bfae3949a8261c18ee7880781.

**Comment by ttuegel** [comment]
We are also going to need these patches:
https://cgit.kde.org/ktexteditor.git/commit/?id=2c4feeb0c9107732399f8ae3dacea3124572f345
https://cgit.kde.org/ktexteditor.git/commit/?id=09a1e864d54735ebcab6bf31198fdef969b92a67
https://cgit.kde.org/ktexteditor.git/commit/?id=86f1dde943389bbf211ec1cde3f27c9681351d3f

**Comment by grahamc** [comment]
Closed by https://github.com/NixOS/nixpkgs/pull/20197, thank you!

**Pull request closed without merging**
