### PR TITLE
sequoia: 0.19.0 -> 0.20.0

### PR DESCRIPTION
**Pull request by doronbehar**
###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This patch fixes building on darwin for me:

```
diff --git a/pkgs/tools/security/sequoia/default.nix b/pkgs/tools/security/sequoia/default.nix
index a54433b92c93..42edff5ca49e 100644
--- a/pkgs/tools/security/sequoia/default.nix
+++ b/pkgs/tools/security/sequoia/default.nix
@@ -62,6 +62,7 @@ rustPlatform.buildRustPackage rec {

   makeFlags = [
     "PREFIX=${placeholder "out"}"
+    "INSTALL=install"
   ];

   buildFlags = [
@@ -100,6 +101,5 @@ rustPlatform.buildRustPackage rec {
     homepage = "https://sequoia-pgp.org/";
     license = licenses.gpl3;
     maintainers = with maintainers; [ minijackson doronbehar ];
-    broken = stdenv.targetPlatform.isDarwin;
   };
 }
```

**Comment by doronbehar** [comment]
> This diff fixes building on darwin for me:

Awesome! Thanks :).

**Comment by marsam** [comment]
Would you mind checking whether we can drop `llvmPackages_10` from buildInputs along with `LIBCLANG_PATH`?

**Comment by doronbehar** [comment]
> Would you mind checking whether we can drop `llvmPackages_10` from buildInputs along with `LIBCLANG_PATH`?

No, fails the same way it used to fail before. FWIW, `clang` is listed officially as a dependency, so for sure it can't be dropped completely: https://gitlab.com/sequoia-pgp/sequoia/-/tree/v0.20.0#arch-linux . I tried more things - using `llvmPackages_10.llvm` and `llvmPackages_10.llvm.out` in inputs...

**Comment by doronbehar** [comment]
```
sequoia>    Compiling nettle-sys v2.0.4
sequoia> error: failed to run custom build command for `nettle-sys v2.0.4`
sequoia> Caused by:
sequoia> process didn't exit successfully: `/build/source/target/release/build/nettle-sys-1fcae42ffc344f15/build-script-build` (exit code: 101)
sequoia> --- stdout
sequoia> cargo:rerun-if-env-changed=NETTLE_STATIC
sequoia> cargo:rerun-if-env-changed=NETTLE_PREGENERATED_BINDINGS
sequoia> cargo:rerun-if-env-changed=NETTLE HOGWEED_NO_PKG_CONFIG
sequoia> cargo:rerun-if-env-changed=PKG_CONFIG
sequoia> cargo:rerun-if-env-changed=NETTLE HOGWEED_STATIC
sequoia> cargo:rerun-if-env-changed=NETTLE HOGWEED_DYNAMIC
sequoia> cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
sequoia> cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
sequoia> cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
sequoia> cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
sequoia> cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
sequoia> cargo:rerun-if-env-changed=PKG_CONFIG_PATH
sequoia> cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
sequoia> cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
sequoia> cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
sequoia> cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
sequoia> cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
sequoia> cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
sequoia> cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
sequoia> cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
sequoia> cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
sequoia> cargo:rerun-if-env-changed=SYSROOT
sequoia> cargo:rerun-if-env-changed=NETTLE HOGWEED_STATIC
sequoia> cargo:rerun-if-env-changed=NETTLE HOGWEED_DYNAMIC
sequoia> cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
sequoia> cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
sequoia> cargo:rustc-link-search=native=/nix/store/6qp2gdi9jc3hcjpa4bqmxalzxwvgb7sa-nettle-3.6/lib
sequoia> cargo:rustc-link-lib=nettle
sequoia> cargo:rustc-link-lib=hogweed
sequoia> cargo:rerun-if-env-changed=PKG_CONFIG
sequoia> cargo:rerun-if-env-changed=NETTLE HOGWEED_STATIC
sequoia> cargo:rerun-if-env-changed=NETTLE HOGWEED_DYNAMIC
sequoia> cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
sequoia> cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
sequoia> cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
sequoia> cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
sequoia> cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
sequoia> cargo:rerun-if-env-changed=PKG_CONFIG_PATH
sequoia> cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
sequoia> cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
sequoia> cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
sequoia> cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
sequoia> cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
sequoia> cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
sequoia> cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
sequoia> cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
sequoia> cargo:include=/nix/store/bfsnmn88nf3b54fh1n884lq6wp99j3ba-nettle-3.6-dev/include
sequoia> cargo:rustc-link-lib=dylib=nettle
sequoia> cargo:rustc-link-lib=dylib=hogweed
sequoia> cargo:rustc-link-search=native=/nix/store/6qp2gdi9jc3hcjpa4bqmxalzxwvgb7sa-nettle-3.6/lib
sequoia> cargo:rustc-link-lib=dylib=gmp
sequoia> --- stderr
sequoia> thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclng-*.so\', \'libclang.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"'
 /build/sequoia-0.20.0-vendor.tar.gz/bindgen/src/lib.rs:1731:31
sequoia> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
sequoia> warning: build failed, waiting for other jobs to finish...
sequoia> error: build failed
sequoia> make[1]: *** [Makefile:74: build-release] Error 101
sequoia> make[1]: Leaving directory '/build/source/openpgp-ffi'
sequoia> make: *** [Makefile:100: build-release] Error 2
```

**Pull request merged**
