### PR TITLE
kernel: 4.5.2 -> 4.5.3

### PR DESCRIPTION
**Pull request by NeQuissimus**
###### Things done
- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [X] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
Built this locally, albeit with grsecurity applied ontop, but that shouldn't matter. Thank you.

**Comment by NeQuissimus** [comment]
@joachifm Speaking of grsecurity, I installed it last weekend. Is it normal that I cannot `nixos-rebuild switch` running grsecurity? :D What am I missing?
It tells me about not being allowed to unmount my root filesystem, causing nixos-rebuild to fail.

**Comment by joachifm** [comment]
@NeQuissimus problem is I have not yet leapt into changing the grsecurity builder, so it relies almost completely on the auto configuration, with a few overrides, which needs to change for the distro kernel.

If the mounting occurs in the sandbox, it's quite likely it's blocked by the chroot protections (`GRKERNSEC_CHROOT_MOUNT` specifically). Otherwise, there's only the read-only mount protection that *could* interfere, afaik, but I wouldn't think it'd be enabled by the autoconfig.

`nixos-rebuild switch` on NixOS should work out of the box, so I consider this a bug.

I don't actually run NixOS directly, but I will see about debugging this in a vm.

**Comment by joachifm** [comment]
@NeQuissimus what I should say is: please open an issue about this

**Comment by NeQuissimus** [comment]
I can give this another try this weekend and open an issue if it occurs again.
I had actually installed on a clean laptop and could not get off grsecurity :D Had to boot the live-CD again.

**Comment by joachifm** [comment]
@NeQuissimus hah, that falls somewhat short of what the out-of-the-box experience should be ... If you enable `security.grsecurity.sysctl`, you will at least be able to affect much of the grsec configuration, notably chroot restrictions, without rebuilding the kernel.

**Comment by joachifm** [comment]
@NeQuissimus I'm quite keen on making the grsecurity smoother, so any feedback is much appreciated!

**Pull request merged**
