### PR TITLE
nginx: add listenAddresses

### PR DESCRIPTION
**Pull request by mkg20001**
###### Motivation for this change

This allows the user to manually specify the addresses nginx shoud 
listen on, while still having the convinience to use the *SSL options 
and have the ports automatically applied

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
@ajs ping

**Comment by aanderse** [comment]
Can I see an example of config before and after this change? As I'm reading it, this seems a bit superfluous... adding more complication than clarity, perhaps?

**Comment by mkg20001** [comment]
before:

```
{
  services.nginx.virtualHosts."example.com" = {
    forceSSL = true;
    listen = [
      { addr = "1.2.3.4"; port = 80; ssl = false; }
      { addr = "1.2.3.4"; port = 443; ssl = true; }
      { addr = "[[1:2:3::4]"; port = 80; ssl = false; }
      { addr = "[[1:2:3::4]"; port = 443; ssl = true; }
    ];
  };
}
```

after:

```
{
  services.nginx.virtualHosts."example.com" = {
    forceSSL = true;
    listenAddresses = [ "1.2.3.4" "[1:2:3::4]" ];
  };
}
```

Setting values in "listen" currently requires knowing if SSL is enabled and if onlySSL is set. This makes it simpler as the module is already able to figure out the ports it needs, this allows setting just the addresses and have the module add the right ports per address.

**Review by aanderse — APPROVED** [review]
Yeah I guess that is a good tradeoff. Thanks.

Any chance you want l want to add this to the `httpd` module as well? I like to try and keep it roughly the same as `nginx` when it makes sense to.

**Comment by mkg20001** [comment]
The httpd module looks very different from the nginx module, I don't have the knowledge to implement that properly there.

**Pull request merged**
