### PR TITLE
root5: Fix build

### PR DESCRIPTION
**Pull request by infinisil**
## Description of changes

Fixes root5, fixing the builds for applgrid, apfelgrid and xfitter

Done during [Nix Hour 51](https://www.youtube.com/watch?v=90BEKi4Iz8U&list=PLyzwHTVJlRc8yjlx4VR4LU5A5O44og9in&index=1&pp=iAQB), for ZHF https://github.com/NixOS/nixpkgs/issues/265948

See also https://github.com/NixOS/nixpkgs/pull/266538 for dropping root5

## Things done

- [x] Built successfully for all commits on x86_64-linux:
  - [x] root5
  - [x] applgrid
  - [x] apfelgrid
  - [x] xfitter

### CODE REVIEW

**Comment by infinisil** [comment]
@ofborg build xfitter

(this packages depends on all others)

**Comment by veprbl** [comment]
Not really sure if applgrid will work well with ROOT6 at runtime. I recall, it used to break things significantly, I would need to test. Let's not rush into merging this.

**Comment by infinisil** [comment]
@veprbl Ah I see. How about only having the first commit in this PR then and opening another for the rest?

**Comment by veprbl** [comment]
First commit is a no-brainer – yes.

**Comment by infinisil** [comment]
Oh, I meant the first two commits, so including the root 5 fix. Now done that

**Pull request merged**
