### PR TITLE
qemu: 2.6.1 -> 2.7.0 for CVEs

### PR DESCRIPTION
**Pull request by grahamc**
###### Motivation for this change

https://github.com/NixOS/nixpkgs/issues/18856
### qemu-kvm (4 issues)
- [x] [`#686857`](https://lwn.net/Vulnerabilities/686857/) ([search](http://search.nix.gsc.io/?q=qemu-kvm&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=qemu-kvm+in%3Apath&type=Code))  qemu-kvm: code execution
- [x] [`#687235`](https://lwn.net/Vulnerabilities/687235/) ([search](http://search.nix.gsc.io/?q=qemu-kvm&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=qemu-kvm+in%3Apath&type=Code))  qemu: information leak
- [x] [`#666755`](https://lwn.net/Vulnerabilities/666755/) ([search](http://search.nix.gsc.io/?q=qemu-kvm&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=qemu-kvm+in%3Apath&type=Code))  qemu: three vulnerabilities
- [x] [`#674496`](https://lwn.net/Vulnerabilities/674496/) ([search](http://search.nix.gsc.io/?q=qemu-kvm&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=qemu-kvm+in%3Apath&type=Code))  qemu: multiple vulnerabilities
### qemu (12 issues)
- [x] [`#700388`](https://lwn.net/Vulnerabilities/700388/) ([search](http://search.nix.gsc.io/?q=qemu&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=qemu+in%3Apath&type=Code))  qemu: directory/path traversal
- [x] [`#692861`](https://lwn.net/Vulnerabilities/692861/) ([search](http://search.nix.gsc.io/?q=qemu&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=qemu+in%3Apath&type=Code))  qemu: multiple vulnerabilities
- [x] [`#695959`](https://lwn.net/Vulnerabilities/695959/) ([search](http://search.nix.gsc.io/?q=qemu&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=qemu+in%3Apath&type=Code))  qemu: two vulnerabilities
- [x] [`#691104`](https://lwn.net/Vulnerabilities/691104/) ([search](http://search.nix.gsc.io/?q=qemu&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=qemu+in%3Apath&type=Code))  qemu: denial of service
- [x] [`#690402`](https://lwn.net/Vulnerabilities/690402/) ([search](http://search.nix.gsc.io/?q=qemu&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=qemu+in%3Apath&type=Code))  qemu: denial of service
- [x] [`#689261`](https://lwn.net/Vulnerabilities/689261/) ([search](http://search.nix.gsc.io/?q=qemu&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=qemu+in%3Apath&type=Code))  qemu: two vulnerabilities
- [x] [`#687235`](https://lwn.net/Vulnerabilities/687235/) ([search](http://search.nix.gsc.io/?q=qemu&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=qemu+in%3Apath&type=Code))  qemu: information leak
- [x] [`#686861`](https://lwn.net/Vulnerabilities/686861/) ([search](http://search.nix.gsc.io/?q=qemu&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=qemu+in%3Apath&type=Code))  qemu: denial of service
- [x] [`#680800`](https://lwn.net/Vulnerabilities/680800/) ([search](http://search.nix.gsc.io/?q=qemu&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=qemu+in%3Apath&type=Code))  xen: multiple denial of service vulnerabilities
- [x] [`#666755`](https://lwn.net/Vulnerabilities/666755/) ([search](http://search.nix.gsc.io/?q=qemu&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=qemu+in%3Apath&type=Code))  qemu: three vulnerabilities
- [x] [`#674609`](https://lwn.net/Vulnerabilities/674609/) ([search](http://search.nix.gsc.io/?q=qemu&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=qemu+in%3Apath&type=Code))  qemu: privilege escalation
- [x] [`#674496`](https://lwn.net/Vulnerabilities/674496/) ([search](http://search.nix.gsc.io/?q=qemu&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=qemu+in%3Apath&type=Code))  qemu: multiple vulnerabilities
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Thanks to @NeQuissimus and @joachifm on this.

### CODE REVIEW

**Comment by NeQuissimus** [comment]
Awesome, thanks. I didn't get around to trying this today...

**Comment by aneeshusa** [comment]
Also fixes #18954.

**Comment by grahamc** [comment]
@fpletz do you have opinions on what happens before this merge? I built locally and it seems okay. I didn't give it too much of a test though.

**Comment by grahamc** [comment]
I ran the boot tests and they appear to have passed.

**Pull request merged**
