### PR TITLE
neuronpy python: init at 0.1.6

### PR DESCRIPTION
**Pull request by nico202**
###### Things done:
- [ ] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
###### More

It's my first python module, no idea if it's done the right way

### CODE REVIEW

**Comment by FRidh** [comment]
Hi @nico202 ,

Thanks for contributing. First though, I recommend you turn on the sandboxing/chroot since it helps identify packaging issues.

I checked the `setup.py` of the archive. It doesn't mention any dependencies, however, when I check some of the modules that are included in the archive, then it's clear it does depend on `numpy`, `matplotlib`, and possibly other packages.

This package will not function properly without adding those dependencies to `propagatedBuildInputs`. Therefore, please add all dependencies. Furthermore, because no tests are included in the archive, add
`doCheck = false;` along with a note why the tests were disabled (in this case, because no tests are included).

**Comment by FRidh** [comment]
ping

**Comment by nico202** [comment]
Sorry, made some change right now (looked for all imports) but I cannot test with --option build-use-chroot true because of: error: assertion failed at path/nixpkgs/pkgs/top-level/all-packages.nix:5657:19

**Comment by FRidh** [comment]
Try setting `nix.useChroot` to `true` in `configuration.nix`

**Comment by FRidh** [comment]
pushed in https://github.com/NixOS/nixpkgs/commit/78901322d8002cb2645be2060ec544fd2f9c9e2a

**Pull request closed without merging**
