### PR TITLE
sponsorblock-mpv-script: init at 2020-06-21

### PR DESCRIPTION
**Pull request by samuelgrf**
###### Motivation for this change
mpv_sponsorblock is an (or a?) mpv script that automatically skips sponsors on YouTube videos.

###### Things done
Successfully tested that mpv skips sponsors with the script installed.
Rewrote the NixOS wiki entry to use overlays, since packageOverrides are deprecated.

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by samuelgrf** [comment]
Converting this to a draft until a license is added to the project, see https://github.com/po5/mpv_sponsorblock/issues/15

**Comment by samuelgrf** [comment]
The GPLv3 license was added. I'll undraft the pr when I've found a good way to handle configuring the script.

**Comment by mweinelt** [comment]
Looks like #92507 is obsoleting this PR. Can you take a look?

**Comment by samuelgrf** [comment]
That implementation looks a lot nicer than mine, I've still got lots to learn. Closing this in favor of #92507 then.

**Pull request closed without merging**
