### PR TITLE
fira-code: don't use variable font

### LINKED ISSUE #118891: lualatex cannot find Fira Code
**Describe the bug**
```
luaotfload | db : Reload initiated (formats: otf,ttf,ttc); reason: Font "FiraCode" not found.
luaotfload | resolve : sequence of 3 lookups yielded nothing appropriate.

! Package fontspec Error: The font "FiraCode" cannot be found.
```

```
$ fc-list | rg -i "fira code"
/home/rschuetz/.nix-profile/share/fonts/truetype/FiraCode-VF.ttf: Fira Code,Fira Code Light:style=Light,Regular
/home/rschuetz/.nix-profile/share/fonts/truetype/FiraCode-VF.ttf: Fira Code
/home/rschuetz/.nix-profile/share/fonts/truetype/FiraCode-VF.ttf: Fira Code:style=Bold
/home/rschuetz/.nix-profile/share/fonts/truetype/FiraCode-VF.ttf: Fira Code:style=SemiBold
/home/rschuetz/.nix-profile/share/fonts/truetype/FiraCode-VF.ttf: Fira Code Light:style=Retina
/home/rschuetz/.nix-profile/share/fonts/truetype/FiraCode-VF.ttf: Fira Code:style=Medium
/home/rschuetz/.nix-profile/share/fonts/truetype/FiraCode-VF.ttf: Fira Code,Fira Code Light:style=Regular
```

**To Reproduce**
Install the font with `nix-env -iA nixos.fira-code` and use it with `\setmonofont{Fira Code}`.

**Expected behavior**

**Notify maintainers**
@eyJhb @veprbl @rycee 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.11, NixOS, 21.05pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre281538.9e377a6ce42"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
fixes https://github.com/NixOS/nixpkgs/issues/118891
Also, Arch Linux's ttf package installs the same files.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 123220` at 856969f1 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>fira-code</li>
    <li>fira-mono</li>
  </ul>
</details>

**Comment by midchildan** [comment]
It looks to me the real issue lies in luaotfload. luaotfload isn't properly matching the font family name, so it is falling back to finding the font by filename instead.

```console
❯ luaotfload-tool --find 'Fira Code' --fuzzy
luaotfload | db : Reload initiated (formats: otf,ttf,ttc); reason: Font "Fira Code" not found.
luaotfload | resolve : sequence of 3 lookups yielded nothing appropriate.
luaotfload | resolve : Cannot find "Fira Code" in index.
luaotfload | resolve : Looking for close matches, this may take a while ...
luaotfload | query : Distance from "firacode": 5
    Fira Code Light
    file-icons
```

luaotfload is mistakenly thinking that "Fira Code Light" is the family name, so the following works:

```tex
\usepackage{fontspec}
\setmainfont{Fira Code Light}
```

**Comment by midchildan** [comment]
I'd prefer keeping the variable font unless it causes more problems because it's more customizable while being smaller in size. The non-variable ttfs are 1.8 MB combined while the variable one is only 260 KB.

**Comment by dotlambda** [comment]
> The non-variable ttfs are 1.8 MB combined while the variable one is only 260 KB.

That's a stark difference indeed.



> It looks to me the real issue lies in luaotfload. luaotfload isn't properly matching the font family name, so it is falling back to finding the font by filename instead.

Do you have an idea how to fix that? As a workaround, can we maybe change the filename from `FiraCode-VF.ttf` to `FiraCode.ttf`?

**Comment by midchildan** [comment]
For a complete fix, I believe this would have to be reported upstream at [latex3/luaotfload](https://github.com/latex3/luaotfload). We could rename the file for Fira Code, but fixing it upstream would solve the problem for other fonts that may suffer from the same issue.

I'm not familiar with Lua but from a cursory look, it seems that luaotfload rolls its own parser for fonts files[1] so any fixes would probably have to be made there.

[1]: https://github.com/latex3/luaotfload/blob/d3b03695412a7a8ff0c58fd630527370a47ae5c6/src/fontloader/misc/fontloader-font-otr.lua#L1904

**Comment by rycee** [comment]
I think installing `FiraCode-VF.ttf` as `FiraCode.ttf` sounds like a good idea.

**Comment by minijackson** [comment]
What about the solution proposed by #196087, keeping them both? The fira-code variable font also makes `xdvipdfmx` fail when I use `xelatex`

**Comment by drupol** [comment]
Dear @dotlambda,

The original issue this PR has been created for is fixed. Is this PR still relevant?

If not, can you please close it?

Thanks!

**Comment by minijackson** [comment]
I can confirm that the issue that I had is fixed on nixpkgs master.

**Review by drupol — APPROVED** [review]

**Comment by drupol** [comment]
Could you please fix the merge conflict ?

**Comment by minijackson** [comment]
Note: I'm confirming that for my usecase, this PR was *not* needed.

**Comment by minijackson** [comment]
Sorry for necrobumping the pull request, but I can reproduce the issue on master again.

```latex
\documentclass{article}
\usepackage{fontspec}\setmonofont{Fira Code}
\begin{document}
Let's test the “programming ligatres” \verb|hello <> === ok nein|.
\end{document}
```

``` bash
nix shell 'nixpkgs/master#texlive.combined.scheme-full'
latexmk -pdf -xelatex test.tex
```

Fails with:

```
------------
Running 'xdvipdfmx -E -o "test.pdf"  "test.xdv"'
------------
test.xdv -> test.pdf
[1
xdvipdfmx:warning: Invalid TTC index (not TTC font): /nix/store/3nvjhw65a3vqf411g0w3nyyjmmwlxc75-fira-code-6.2/share/fonts/truetype/FiraCode-VF.ttf
xdvipdfmx:fatal: Invalid font: -1 (1)

No output PDF file written.
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  xdvipdfmx: Command for 'xdvipdfmx' gave return code 256
```

**Pull request closed without merging**
