### PR TITLE
ruby: 2.7.6 -> 2.7.7, 3.0.4 -> 3.0.5, 3.1.2 -> 3.1.3 

### PR DESCRIPTION
**Pull request by marsam**
###### Description of changes

https://www.ruby-lang.org/en/news/2022/11/24/ruby-2-7-7-released/
https://www.ruby-lang.org/en/news/2022/11/24/ruby-3-0-5-released/
https://www.ruby-lang.org/en/news/2022/11/24/ruby-3-1-3-released/
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Princemachiavelli** [comment]
The openssl-dir patch's are broken and seem to not be needed anymore required (upstream patchsets reflect this). The larger issue is that 3.1.3 builds with some references to `/build/source` remaining (seems to be libraries in `./lib/ruby/3.1.0/x86_64-linux`). I've identified the breaking upstream commit to be `8e74bfb641096f39f8eb22961f7aadf89ab741cf`. This commit changes from building under miniruby to bootstrapruby if possible.

I'm still working through how to fix it; it may be a patch or change to the derivation.  It might also be better to just correct the issue in the fixupPhase... or it could be a bug in the patchelf/shrink process.

For reference, here's the first broken binary Nix sees and exits at:

```
$ patchelf --print-rpath /nix/store/pr2f6735y5zv8d0kxrakzp8969zayz5r-ruby-3.1.3/lib/ruby/3.1.0/x86_64-linux/enc/windows_1257.so
/build/source:/nix/store/4nlgxhb09sdr51nc9hdm8az5b08vzkgx-glibc-2.35-163/lib
```

**Comment by will** [comment]
If the openssl patches are an issue, would it be possible to do a PR with only the 3.1.2 -> 3.1.3 which doesn't appear to have that problematic patch?

**Comment by Princemachiavelli** [comment]
> If the openssl patches are an issue, would it be possible to do a PR with only the 3.1.2 -> 3.1.3 which doesn't appear to have that problematic patch?

It's the opposite, the 2.7.x and 3.0.x updates can be merged by just removing the unnecessary OpenSSL patch (might as well update the patchset source revision). The 3.1.3 version is the problematic broken package.

**Comment by njaremko** [comment]
These are the `railsExpress` patches? It's never made any sense to me that we enable those by default. Our default ruby build shouldn't have patches that change fundamental things about how Ruby works (there are patches that mess with GC stuff). It also prevents manually specifying versions of ruby that aren't in that `railsExpress` patch file.

I have to maintain my own branch to be able to use Ruby 3.0.5 with `useRailsExpress = false` as the (correct) default and 
```nix
if useRailsExpress then (import ./patchsets.nix {
  inherit patchSet useRailsExpress ops fetchpatch;
  patchLevel = ver.patchLevel;
}).${ver.majMinTiny} else []
```

**Pull request closed without merging**
