### PR TITLE
python3Packages.pytorch: 1.9.0 -> 1.10.2; python3Packages.torchvision: 0.11.2 -> 0.11.3

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change
Noticed these were out of date.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
Only new failure `nixpkgs-review` gave me on nixos x86_64:

```
builder for '/nix/store/mk59iysx4vikawl4jw1nk268jw0rl27v-python3.9-boxx-0.9.9.drv' failed with exit code 1; last 10 log lines:
      switch_backend(rcParams["backend"])
    File "/nix/store/rr9mlvqwjzfd88xfrpcwfvc3y8wqmzln-python3.9-matplotlib-3.5.1/lib/python3.9/site-packages/matplotlib/pyplot.py", line 275, in switch_backend
      raise ImportError(
  ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running


  ----------------------------------------------------------------------
  Ran 1 test in 0.000s

  FAILED (errors=1)
```

**Comment by risicle** [comment]
Though I note that prior to this, `boxx` is just failing to find any tests

```
----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

**Comment by mweinelt** [comment]
On x86_64-linux I see:

```
running install tests
Matplotlib created a temporary config/cache directory at /build/matplotlib-sntfeqm6 because the default path (/homeless-shelter/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

**Comment by risicle** [comment]
Yes ditto, I just didn't include the that message in my paste

**Comment by mweinelt** [comment]
I was surprised because you said in https://github.com/NixOS/nixpkgs/pull/158185#issuecomment-1030894467 that with this update you see the tests erroring out. But I see tests are still not found even after this update.

**Review by jonringer — APPROVED** [review]
failures look unrelated

```
https://github.com/NixOS/nixpkgs/pull/158185

3 packages marked as broken and skipped:
python39Packages.pywick python39Packages.shap python39Packages.skorch

5 packages failed to build:
python39Packages.bpycv python39Packages.pytorch-metric-learning python39Packages.qiskit python39Packages.spacy-transformers python39Packages.zcs

19 packages built:
python39Packages.boxx python39Packages.einops python39Packages.elegy python39Packages.ignite python39Packages.pyro-ppl python39Packages.pytorch python39Packages.pytorch-lightning python39Packages.pytorchWithCuda python39Packages.qiskit-machine-learning python39Packages.rising python39Packages.slicer python39Packages.stanza python39Packages.tensorboardx python39Packages.test-tube python39Packages.torchgpipe python39Packages.torchinfo python39Packages.torchvision python39Packages.treex tts
```

**Comment by veprbl** [comment]
Result of `nixpkgs-review pr 158185` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>27 packages marked as broken and skipped:</summary>
  <ul>
    <li>python39Packages.boxx</li>
    <li>python39Packages.bpycv</li>
    <li>python39Packages.einops</li>
    <li>python39Packages.elegy</li>
    <li>python39Packages.ignite</li>
    <li>python39Packages.pyro-ppl</li>
    <li>python39Packages.pytorch</li>
    <li>python39Packages.pytorch-lightning</li>
    <li>python39Packages.pytorch-metric-learning</li>
    <li>python39Packages.pytorchWithoutCuda</li>
    <li>python39Packages.pywick</li>
    <li>python39Packages.qiskit</li>
    <li>python39Packages.qiskit-machine-learning</li>
    <li>python39Packages.rising</li>
    <li>python39Packages.shap</li>
    <li>python39Packages.skorch</li>
    <li>python39Packages.slicer</li>
    <li>python39Packages.spacy-transformers</li>
    <li>python39Packages.stanza</li>
    <li>python39Packages.tensorboardx</li>
    <li>python39Packages.test-tube</li>
    <li>python39Packages.torchgpipe</li>
    <li>python39Packages.torchinfo</li>
    <li>python39Packages.torchvision</li>
    <li>python39Packages.treex</li>
    <li>python39Packages.zcs</li>
    <li>tts</li>
  </ul>
</details>

**Pull request merged**
