### PR TITLE
ghc821: init at 8.2.1-rc2 (a.k.a., 8.2.0.20170507)

### PR DESCRIPTION
**Pull request by k0001**
The approach taken to add this package was to port over the definitions
currently existing for 8.2.0, and making the necessesary changes to get
this building.

The Haskell package set associated with this compiler doesn't yet
guarantee that all or most of the packages successfully build with this
new compiler, but that will improve over time after this GHC 8.2.1
is officially released and the ecosystem catches up.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by shlevy** [comment]
@k0001 Can you port over the cross-compilation stuff from `HEAD.nix` as well? cc @Ericson2314

**Comment by k0001** [comment]
@shlevy sure, I'll add that as well. Thanks for the quick feedback.

**Comment by Ericson2314** [comment]
Err the cross compilation stuff in head needs a lot of revamp too. I have a yet-to-be-made PR for that, but it relies on other PRs that still need to be fixed.

So yeah, while it's fine to mimick some stuff from ghcHEAD, I'll end up rewriting it all anyways.

**Comment by shlevy** [comment]
@Ericson2314 As long as you update it both here and in HEAD, no need to copy it over for now

**Comment by k0001** [comment]
@shlevy updated. I based my work off `head.nix` instead.

**Pull request merged**
