### PR TITLE
gpt4all-cuda: fix CUDA initialization

### LINKED ISSUE #321928: gpt4all-cuda: No cuda acceleration
### Describe the bug
Greetings.
I'm trying to run gpt4all in cuda acceleration, but there is no option for CUDA acceleration in app. 
Launching from terminal give me this error:failed to initialize CUDA: CUDA driver is a stub library

### Steps To Reproduce
1. install gpt4all-cuda
2. Settings -> Applictiation->Device 
3. In device section, there is only CPU and Auto

### Expected behavior
Cuda device should be detectable.

### Additional context
Exporting `LD_LIBRARY_PATH="/run/opengl-driver/lib"` resolve this issue and gpt4all detect cuda device.

### Notify maintainers
@drupol
@Polygon

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.5-xanmod1, NixOS, 24.11 (Vicuna), 24.11.20240620.d603719`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix Super) 2.22.0pre20240422_5ecd820`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/xfpiyfgf6y30fxk5ngv0cjn474qfr3sj-source
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by haras-unicorn**
## Description of changes

Fixes #321928.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Titaniumtown** [comment]
I do not have an nvidia gpu to test with. So I do not have any way of testing this.

**Comment by Titaniumtown** [comment]
@VeilSilence Since you reported the original issue. Do you have a sec to test this? Lmk if you need an explanation on how to :)

**Comment by VeilSilence** [comment]
> @VeilSilence Since you reported the original issue. Do you have a sec to test this? Lmk if you need an explanation on how to :)

```nix
{
  pkgs ?
    import (fetchTarball {
      url = "https://github.com/haras-unicorn/nixpkgs/archive/06c5b53ca56092bc65c2f6f30e31c8eeb87cbb7e.tar.gz";
    }) {
      config = {
        allowUnfree = true;
      };
    },
}:
pkgs.mkShell {
  buildInputs = [pkgs.gpt4all-cuda];
}
```
I made this shell, and build/launched gpt4all inside shell. gpt4all see cuda device, so if my test is correct, this merge request indeed fix this issue.

**Comment by Titaniumtown** [comment]
Ok given the feedback I'll approve it. I have no qualms about the changes :)

**Review by Titaniumtown — APPROVED** [review]
LGTM. others said it fixed their issues.

**Pull request merged**
