### PR TITLE
Binutils-wrapper: Init by refactoring out of cc-wrapper

### PR DESCRIPTION
**Pull request by Ericson2314**
###### Motivation for this change

I need this so packages that just use binutils (e.g. gcc building its standard library until https://github.com/NixOS/nixpkgs/issues/26004) get the same setup-hook support. More broadly, having two wrappers will help enforce proper layering between binutils and the C compiler.

This depends on https://github.com/NixOS/nixpkgs/pull/28556

###### Things done

Right now cc-wrapper just calls binutils wrapper, but I should add another commit exposing wrapped binutils on it's own and changing the stdenv bootstrapping.

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Ericson2314** [comment]
Something really weird is going on where binutils' configure tests for various headers fail despite the underlying `gcc -E conftest.c` succeeding.

**Comment by Ericson2314** [comment]
Ok the Darwin `allowedRequsites problem is from a self rpath, it seems:
```diff
    time stamp 2 Wed Dec 31 19:00:02 1969
       current version 1226.10.1
 compatibility version 1.0.0
 Load command 11
+          cmd LC_RPATH
+      cmdsize 88
+         path /nix/store/n3s943551i12fvklcxxs023bfy2izk8g-libresolv-osx-10.11.6/lib (offset 12)
+Load command 12
       cmd LC_FUNCTION_STARTS
   cmdsize 16
   dataoff 162176
```

**Comment by Ericson2314** [comment]
Everything should be fixed now. https://hydra.mayflower.de/jobset/mayflower/hydra-jobs-cross-rewrite#tabs-evaluations failures are spurious due to outage yesterday.

**Comment by globin** [comment]
Please ping me in IRC when you have time later today :)

**Comment by edolstra** [comment]
I reverted this in ec8d41f08c95cff79ccb28132146226f4f75c6fe because I really don't want yet another mass rename like `NIX_GCC` -> `NIX_CC`, especially when the motivation isn't particular clear to me ("enforce proper layering between binutils and the C compiler" is a bit vague to me).

**Comment by Ericson2314** [comment]
https://github.com/NixOS/nixpkgs/pull/29396 new version

**Pull request merged**
