### PR TITLE
discourseAllPlugins: init discourse-ldap-auth

### PR DESCRIPTION
**Pull request by ryantm**
###### Motivation for this change

discourse-ldap-auth enables LDAP authentication.

Note, it looks like our plugin architecture does not support the "register_css" hook because you end up with errors like this:

```
Errno::EACCES: Permission denied @ rb_sysopen - /build/source/plugins/discourse-ldap-auth/auto_generated/plugin_34a2724ed7ad43636a4417a37d190b96c4d34ef6.css
/build/source/lib/plugin/instance.rb:976:in `initialize'
/build/source/lib/plugin/instance.rb:976:in `open'
/build/source/lib/plugin/instance.rb:976:in `write_asset'
/build/source/lib/plugin/instance.rb:372:in `block in generate_automatic_assets!'
/build/source/lib/plugin/instance.rb:371:in `each'
/build/source/lib/plugin/instance.rb:371:in `generate_automatic_assets!'
/build/source/lib/plugin/instance.rb:629:in `activate!'
lib/discourse.rb:246:in `block in activate_plugins!'
lib/discourse.rb:243:in `each'
lib/discourse.rb:243:in `activate_plugins!'
/build/source/config/application.rb:312:in `block in <class:Application>'
/build/source/lib/plugin_initialization_guard.rb:5:in `plugin_initialization_guard'
/build/source/config/application.rb:311:in `<class:Application>'
/build/source/config/application.rb:73:in `<module:Discourse>'
/build/source/config/application.rb:72:in `<top (required)>'
/build/source/Rakefile:7:in `require'
/build/source/Rakefile:7:in `<top (required)>'
/nix/store/c4g15ybzpvh3ynb6d1489l98az063j25-discourse-ruby-env-2.7.5/lib/ruby/gems/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/nix/store/3h9n2k5gfm84gk74s77vb23d274c7g83-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/cli/exec.rb:63:in `load'
/nix/store/3h9n2k5gfm84gk74s77vb23d274c7g83-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/cli/exec.rb:63:in `kernel_load'
/nix/store/3h9n2k5gfm84gk74s77vb23d274c7g83-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/cli/exec.rb:28:in `run'
/nix/store/3h9n2k5gfm84gk74s77vb23d274c7g83-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/cli.rb:474:in `exec'
/nix/store/3h9n2k5gfm84gk74s77vb23d274c7g83-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/nix/store/3h9n2k5gfm84gk74s77vb23d274c7g83-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/nix/store/3h9n2k5gfm84gk74s77vb23d274c7g83-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/nix/store/3h9n2k5gfm84gk74s77vb23d274c7g83-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/cli.rb:30:in `dispatch'
/nix/store/3h9n2k5gfm84gk74s77vb23d274c7g83-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/nix/store/3h9n2k5gfm84gk74s77vb23d274c7g83-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/cli.rb:24:in `start'
/nix/store/c4g15ybzpvh3ynb6d1489l98az063j25-discourse-ruby-env-2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/exe/bundle:49:in `block in <top (required)>'
/nix/store/3h9n2k5gfm84gk74s77vb23d274c7g83-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
/nix/store/c4g15ybzpvh3ynb6d1489l98az063j25-discourse-ruby-env-2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/exe/bundle:37:in `<top (required)>'
/nix/store/2r14xjbp68pvsw44hj9xjy39vmid6vq4-ruby-2.7.4/bin/bundle:23:in `load'
/nix/store/2r14xjbp68pvsw44hj9xjy39vmid6vq4-ruby-2.7.4/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
error: builder for '/nix/store/0j853bqz510bhs11rkf0c777wb5hni6b-discourse-assets-2.7.5.drv' failed with exit code 1;
       last 10 log lines:
       > /nix/store/3h9n2k5gfm84gk74s77vb23d274c7g83-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
       > /nix/store/3h9n2k5gfm84gk74s77vb23d274c7g83-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/cli.rb:30:in `dispatch'
       > /nix/store/3h9n2k5gfm84gk74s77vb23d274c7g83-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
       > /nix/store/3h9n2k5gfm84gk74s77vb23d274c7g83-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/cli.rb:24:in `start'
       > /nix/store/c4g15ybzpvh3ynb6d1489l98az063j25-discourse-ruby-env-2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/exe/bundle:49:in `block in <top (required)>'
       > /nix/store/3h9n2k5gfm84gk74s77vb23d274c7g83-bundler-2.2.20/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
       > /nix/store/c4g15ybzpvh3ynb6d1489l98az063j25-discourse-ruby-env-2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.2.20/exe/bundle:37:in `<top (required)>'
       > /nix/store/2r14xjbp68pvsw44hj9xjy39vmid6vq4-ruby-2.7.4/bin/bundle:23:in `load'
       > /nix/store/2r14xjbp68pvsw44hj9xjy39vmid6vq4-ruby-2.7.4/bin/bundle:23:in `<main>'
       > (See full trace by running task with --trace)
       For full logs, run 'nix log /nix/store/0j853bqz510bhs11rkf0c777wb5hni6b-discourse-assets-2.7.5.drv'.
error: 1 dependencies of derivation '/nix/store/6vw3vkf8d1lis6zyv1icwf6bsaphcv6y-discourse-2.7.5.drv' failed to build
```

But this CSS here is just cosmetically changing the color of a button, so it isn't critical to the function of the plugin, so I patched it out.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ryantm** [comment]
@dpausp I think this is ready to go now that I've updated it to also include the changes to update.py.

**Review by dpausp — APPROVED** [review]
LGTM, thanks! Installed the plugin with Discourse 2.8.0.beta4 on unstable. Didn't test logging in via LDAP but the plugins loads correctly, settings are present and the login form works.

Couldn't get it to build on my 21.05 branch though. Produces the error caused by the custom CSS. Looks like the patch isn't applied correctly there but I haven't looked further yet.

**Comment by talyz** [comment]
Oh, the `register_css` error is interesting. I'll have to look into what's causing it and if there's any way to solve it.

**Comment by talyz** [comment]
Okay, I have a fix for the `register_css` issue now. It's in #133611 and I've tested it against this PR and it builds fine and makes the CSS available as expected. The button CSS provided by this package is however overridden by other higher prioritized styles, so it doesn't really make any difference. However, if we can merge #133611 first, that would let us get rid of the patch, which I think would be preferable.

**Comment by talyz** [comment]
#133611 is merged now, so if you rebase on master, you can get rid of the patch.

**Comment by ryantm** [comment]
@talyz Thank you! I rebased and it does indeed work without the patch. I also was able to run `nix-build -A discourseAllPlugings.tests` and they passed.

**Pull request merged**
