### PR TITLE
treewide: remove `refs/tags/` from github release `meta.changelog`

### PR DESCRIPTION
**Pull request by pbsds**
I saw https://github.com/NixOS/nixpkgs/pull/346488 was a thing, so i figured a redo of https://github.com/NixOS/nixpkgs/pull/338301 was warranted. Part of https://github.com/NixOS/nixpkgs/issues/346453

diff of `jq <packages.json 'to_entries[]|"\(.key) \(.value.meta.changelog)"' -r`:

https://gist.github.com/pbsds/02ee3d771ab31e15c3c67db9c79c4e57

Made using the script in https://github.com/NixOS/nixpkgs/pull/338301 without modifications

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by HeitorAugustoLN — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
This change is kinda backwards. We should take version and optionally add the v prefix.

**Review by adamcstephens — DISMISSED** [review]
I agree with Sandro that we should use version if these links are broken.

**Comment by pbsds** [comment]
semantically the github release urls are derived from the git tag, which don't necessarily map cleanly from the version. In https://github.com/NixOS/nixpkgs/pull/338301 the idea of a `tag` input and output for `fetchFromGitHub` was brought up which I fully support, but in the meanwhile I believe this is the easiest treewide to consistently enforce.

**Comment by adamcstephens** [comment]
I don't really understand. How is what you propose any simpler, clearer, or more reliable than using the version like so:

```
changelog = "https://codeberg.org/forgejo/forgejo/releases/tag/v${version}";
```

In my opinion your version is more complex, and needlessly spends compute cycles modifying strings for what? So you don't have to put the `v` in front of version?

**Comment by pbsds** [comment]
Okay, have it your way. Note now that the review requires you to view the whole file.

I left forgejo with `lib.removePrefix` since `rev` is provided as an input to `callPackage`

**Comment by emilylange** [comment]
> I left forgejo with `lib.removePrefix` since `rev` is provided as an input to `callPackage`

`version` is used and required in multiple places in this internal abstraction (`generic.nix`) of Forgejo.
Please change it to `v${version}`, just like you did with all the other packages.

Thanks :)

**Comment by pbsds** [comment]
Thanks for pointing that out :+1:

**Review by philiptaron — APPROVED** [review]

**Pull request merged**
