### PR TITLE
vimPlugins.vim-kitty-navigator: init at 2019-11-04

### PR DESCRIPTION
**Pull request by equirosa**
###### Motivation for this change

Add vim plugin: vim-kitty-navigator
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by timokau — APPROVED** [review]
This looks good to me, but due to the high potential for conflicts in vim plugin changes this will have to wait until https://github.com/NixOS/nixpkgs/pull/83119 and https://github.com/nixos/nixpkgs/pull/69130 are resolved. If I forget, please remind me to merge this.

**Comment by timokau** [comment]
Those PRs have been merged, so this should be good to go after a rebase.

**Comment by equirosa** [comment]
> Those PRs have been merged, so this should be good to go after a rebase.

Done! :smile:

**Review by timokau — APPROVED** [review]
Thanks!

**Pull request merged**
