### PR TITLE
pythonPackage.pyown: fix builds

### PR DESCRIPTION
**Pull request by lsix**
###### Motivation for this change

- Version 2.10 relaxed the requirement for geojson from `geojson>=2.3.0,<2.4` to `geojson>=2.3.0,<3`. Remove the postPatch hook that adjusted this requirement when it broke in nixpkgs.
- Python2 support has been deprecated in 2.9 (https://github.com/csparpa/pyowm/releases/tag/2.9.0)
- Python-3.3 support dropped in 2.10 (https://github.com/csparpa/pyowm/releases/tag/2.10)

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS
diff LGTM
leaf package

```
[2 built, 2 copied (3.6 MiB), 3.5 MiB DL]
https://github.com/NixOS/nixpkgs/pull/67249
1 package were build:
python37Packages.pyowm
```

**Comment by risicle** [comment]
`nix-review` happy on macos 10.13, package imports ok.

**Comment by mmahut** [comment]
@GrahamcOfBorg build pythonPackage.pyown python3Package.pyown

**Comment by mmahut** [comment]
@GrahamcOfBorg build python37Package.pyown

**Comment by mmahut** [comment]
@GrahamcOfBorg build python37Packages.pyowm

**Pull request merged**
