### PR TITLE
jdt-language-server: 1.20.0 -> 1.21.0

### PR DESCRIPTION
**Pull request by fabianpage**
also remove the option noverify as it was depricated in JDK 13 (https://github.com/eclipse/eclipse.jdt.ls/blob/master/CHANGELOG.md#1160-september-29th-2022)

### CODE REVIEW

**Review by matt-snider — APPROVED** [review]
Nice catch! I see you also provided eclipse/eclipse.jdt.ls#2566, because what I was about to comment is that the upstream still documents it in the README :wink: 

Looks good to me

**Comment by fabianpage** [comment]
Do i need to do something to merge this PR?

**Comment by matt-snider** [comment]
@fabianpage No sorry I should have clarified. I introduced the derivation so I'm listed as the maintainer but I don't have any special permissions in this repository.

I will tag @wegank because they merged the last one

**Review by wegank — APPROVED** [review]

**Comment by wegank** [comment]
`jdt-language-server 1.20.0 -> 1.21.0` -> `jdt-language-server: 1.20.0 -> 1.21.0`

**Comment by wegank** [comment]
> `jdt-language-server 1.20.0 -> 1.21.0` -> `jdt-language-server: 1.20.0 -> 1.21.0`

The same goes for the commit message.

**Review by matt-snider — APPROVED** [review]

**Comment by wegank** [comment]
`jdt-language-server 1.20.0: -> 1.21.0` -> `jdt-language-server: 1.20.0 -> 1.21.0`  🤦‍♂️

**Review by matt-snider — APPROVED** [review]

**Pull request merged**
