### PR TITLE
chromium: 79.0.3945.88 -> 79.0.3945.117

### PR DESCRIPTION
**Pull request by ivan**
###### Motivation for this change

https://chromereleases.googleblog.com/2020/01/stable-channel-update-for-desktop.html

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

`chromium` works fine on x86_64 but I haven't tested the other 5 things, please test.

###### Notify maintainers

cc @bendlas @thefloweringash

### CODE REVIEW

**Comment by thefloweringash** [comment]
I've successfully tested `chromium` on aarch64

**Comment by thefloweringash** [comment]
`chromiumDev` is also fine on aarch64. `chromiumBeta` builds but I have yet to make it start. I don't think it's necessary to fix `chromiumBeta` before merging, so LGTM.

**Comment by flokli** [comment]
@thefloweringash what do you mean by "I have yet to make it start"?

It built, but fails to start? You didn't try starting it so far?

How's the situation currently on master?

**Comment by thefloweringash** [comment]
> @thefloweringash what do you mean by "I have yet to make it start"?
> 
> It built, but fails to start? You didn't try starting it so far?

It builds, it prints [an error][] on startup relating to having no crashpad_handler, and then it hangs. I also just realized I made a critical typo in the above (now edited): `chromiumDev` is the affected version.

[an error]: https://gist.github.com/thefloweringash/4266d9ee1f8c24089c0a5b77660343bf

> How's the situation currently on master?

It's apparently uncached. I've started a build but they take a few hours each. I'll report back when I have tested.

**Comment by thefloweringash** [comment]
> How's the situation currently on master?

`chromium` and `chromiumBeta` both refer to version 79. `chromiumDev` refers to version 80. Testing on aarch64: all of them work (briefly tested by loading a few pages).

I don't think we should delay the upgrade to `chromium` for the sole case of aarch64+chromiumDev.

@ivan 

> `chromium` works fine on x86_64 but I haven't tested the other 5 things, please test.

Just to eliminate ambiguity, what are the 5 other things that need testing here?

From reading this thread, I think the status of this PR is:

| platform | attribute | status | tester |
| --- | --- | --- | --- |
| x86_64 | chromium | ✅ | @ivan |
| x86_64 | chromiumBeta | ? | ? |
| x86_64 | chromiumDev | ? | ? |
| aarch64 | chromium | ✅ | @thefloweringash |
| aarch64 | chromiumBeta | ✅ | @thefloweringash |
| aarch64 | chromiumDev | ❌ | @thefloweringash |

**Comment by ivan** [comment]
Oh, the six things I was thinking of were 
```
chromium
chromiumBeta
chromiumDev
google-chrome
google-chrome-beta
google-chrome-dev
```

but I guess we have 9 things with the inclusion of the aarch64 chromium builds.

Please take over this PR (i.e. make a new one) if changes are needed, I removed myself from maintainers.

One thing I have sometimes done is hold back a `chromiumDev` upgrade by removing the version bump for just that channel in `upstream-info.nix`, but I do not know if that is appropriate here.

**Review by primeos — APPROVED** [review]
Atm I don't have the resources to test this, but since it's already tested twice I'm +1 for merging this ASAP (and the diff obviously looks fine as well).

> Please take over this PR (i.e. make a new one) if changes are needed, I removed myself from maintainers.

@ivan just to be sure: That means you won't maintain Chromium anymore (which is of course totally fine) and we need a new maintainer (which is the important part)?

In any case: Thank you for maintaining Chromium up util now :heart:.
I often saw your PRs and appreciate your work - thank you :)

**Comment by ivan** [comment]
@primeos right, I do not plan to make chromium PRs, as I removed my desktop Linuxes for now. Yes, I believe chromium could use another maintainer/tester on x86_64.

If you would like to track upstream's releases, I recommend following the feed on https://chromereleases.googleblog.com/ and filtering for "Stable Channel Update for Desktop". Typically, within a few hours of an upstream release being available, a source tarball is also available and `pkgs/applications/networking/browsers/chromium/update.sh` can be used to update `upstream-info.nix`. Note that when upstream does not have a tarball yet, `update.sh` may silently fail to update a hash in `upstream-info.nix`, making it look like the version was updated while retaining the old hash.

In upcoming releases, I expect WebGL to break again because of a libGLESv2.so loading issue that [this patch](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/browsers/chromium/patches/dont-use-ANGLE-by-default.patch) is working around, watch out for that.

**Comment by primeos** [comment]
Gave Google Chrome a quick test in a VM and updated https://github.com/NixOS/nixpkgs/pull/77299#issuecomment-576996824.

LGTM, IMO `google-chrome-dev` and `chromiumDev` shall not delay these updates so I'm going to merge this PR. If this bugs anyone: Please complain, additional testers for future updates are welcome ;) :P

@ivan: Thank you very much for your response and additional details :heart:.

**Comment by primeos** [comment]
Just to note it here as well: I've opened https://github.com/NixOS/nixpkgs/issues/78450 in an attempt to find new maintainers.

**Pull request merged**
