### PR TITLE
windows improvements, mainly cross: linux -> mingw

### PR DESCRIPTION
**Pull request by vcunat**
The main point point of this is to make some particular packages cross-compile to mingw. I'll merge in a few days if there's noone interested.

A specific change that may be of interest is a kindof-replacement for RPATH on Windows: https://github.com/NixOS/nixpkgs/commit/6e7787e666c50558b5aa10ffcca8e6c0c9bc1ba3. It allows me to just `wine ./result-bin/bin/foo` on dynamically linked binaries. I activated that hook for cygwin as well, although I have only tested it on cross: linux -> mingw.

The linux non-cross stdenv is unchanged, but this PR is probably still a non-cross mass rebuild.

---
###### Things done
- [x] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of **most** binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md), hopefully.

### CODE REVIEW

**Comment by vcunat** [comment]
By analyzing mingw-related PRs, I identified @mcmtroffaes as potentially interested.

@aszlig: I used some of your unmerged commits, but I suppose you're no longer interested in mingw...

**Comment by vcunat** [comment]
And perhaps /cc @chaoflow due to https://ternaris.com/lab/nix-on-windows.html.

**Comment by vcunat** [comment]
Hmm, this PR may worsen some stuff due to https://github.com/NixOS/nixpkgs/issues/14965, although probably not significantly except for mingw.

**Comment by mcmtroffaes** [comment]
Thanks for all your work on this!

I quite like the idea to autolink dll files.

I've only inspected the bzip2 cross build patch in detail so far (as I worked on it previously). Instead of making the nix expression more complicated to handle all the oddities caused by the makefile which ships with bzip2, can't we use the upstream autoconf build system for all builds (cross and native)? In fact, once we had this in the repository:

https://github.com/mcmtroffaes/nixpkgs/blob/094c374941e68bf667719da15c655f148840ebab/pkgs/tools/compression/bzip2/default.nix

but this had to be reverted due to lack of https during bootstrap, and bzip2 is required during bootstrap. Here are the relevant pull requests:

https://github.com/NixOS/nixpkgs/pull/11127
https://github.com/NixOS/nixpkgs/pull/11221

IIUC https support during bootstrap was added to nix a while ago (I failed right now to track down the relevant commit, so it would be good if someone else could confirm). If that's correct, then perhaps maybe now is a good time to revert back to the simpler nix expression for bzip2?

**Comment by mcmtroffaes** [comment]
Found the relevant commit that enables https during bootstrap: https://github.com/NixOS/nixpkgs/commit/e6f61b4cf33887a9231a12e8c766404139a277d8

**Comment by vcunat** [comment]
I can see little advantage in applying a mingw-specific patch on other platforms. In particular, the added dependency on autotools would probably lengthen stdenv bootstrapping.

**Comment by mcmtroffaes** [comment]
The autotools patch isn't mingw specific; it originates from SUSE: http://ftp.suse.com/pub/people/sbrabec/bzip2/ and it just happens to fix most of the cross build issues too.

I assumed that the current bootstrap process depended on autotools already, I apologize if that's not the case and of course I agree that it is better to keep the bootstrap dependencies as minimal as possible.

**Comment by vcunat** [comment]
Oh, I see, it might allow us to delete half of all those hacks. It is possible we have the autotools dependency in there already, I don't know, but it's probably worth it anyway.

**Comment by mcmtroffaes** [comment]
Exactly, the autotools patch allows us to remove almost all the ugly hacks. I'm not sure how to check whether we have autotools or not in the bootstrap. There is probably a very simple command that gives us the immediate answer to that question... I'll try to figure it out.

In any case I certainly don't mean to hold up the whole effort, which I like very much.

**Comment by vcunat** [comment]
It's just an improvement atop, no hold-up really.

**Pull request merged**
