### PR TITLE
Revert "netpbm: 11.8.1 -> 11.8.2"

### PR DESCRIPTION
**Pull request by mweinelt**
Reverts NixOS/nixpkgs#359504

Rebuild of al nixos tests. Let's bundle that with staging changes instead.

### CODE REVIEW

**Comment by philiptaron** [comment]
cc @trofi -- I'm game to do the commit to staging once I understand how the periodic merge works with reverts.

**Comment by trofi** [comment]
I think you can click run job at https://github.com/NixOS/nixpkgs/actions/workflows/periodic-merge-6h.yml to get merge now, but looks like merges are already failing.

**Comment by philiptaron** [comment]
Thank you @mweinelt for doing the manual merge. 🙇🏻

**Comment by vcunat** [comment]
I believe it could be applied to `staging-next` already if need be, as there are no tests built.  (well, staging-next-small will be at some point, but that's not many anyway)

**Comment by trofi** [comment]
How do I find out next time if my next `master` PR rebuilds too many tests? Would `maintainers/scripts/rebuild-amount.sh`? Or it's as problematic as `rebuild-linux` label?

**Comment by mweinelt** [comment]
The problem with ofborg, the current actions and rebuild-amount.sh is that none of them eval nixos tests. Basically, if it is referenced in nixos/lib/test-driver, then it is expensive.

**Comment by trofi** [comment]
Aha, makes sense. Thank you!

**Comment by vcunat** [comment]
Evaluating all tests would be quite expensive, but maybe if we checked only a few random tests or the test driver...

**Pull request merged**
