### PR TITLE
apparmor: 3.0.3 -> 3.0.4

### PR DESCRIPTION
**Pull request by ajs124**
###### Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by ju1m — APPROVED** [review]
LGTM.

`nixpkgs-review pr 160070` was a monster: 
```
[0/48356 built, 2/526/38534 copied (6057.9/349053.0 MiB), 4777.7/135609.0 MiB DL]
```
So I've had to use:
```shell
$ curl -Ls https://github.com/NixOS/nixpkgs/pull/160070.diff | git apply -
$ nix -L build -f . apparmor-bin-utils apparmor-kernel-patches apparmor-pam apparmor-parser apparmor-profiles apparmor-utils
```

**Comment by ju1m** [comment]
Oh, I can `nixpkgs-review pr 160070 --package apparmor-utils`, though it stills take time (and a 5GB+ of RES memory) to list the packages before and after the PR, which is useless in this case AFAIU.

**Review by ju1m — APPROVED** [review]

**Comment by ajs124** [comment]
@GrahamcOfBorg eval

**Comment by zowoq** [comment]
Shouldn't have gone to master.

Reverted in https://github.com/NixOS/nixpkgs/commit/da1a40da75d5203ed158d0ec1dd4bb95ac32d132.

**Comment by zowoq** [comment]
cc @jonringer @vcunat Not sure if this got picked up in a staging-next eval?

**Comment by ajs124** [comment]
ouch, my mistake… I thought I changed the base to staging, sorry.

**Comment by jonringer** [comment]
> cc @jonringer @vcunat Not sure if this got picked up in a staging-next eval?

I dont see it in any of the jobsets following master:
https://hydra.nixos.org/jobset/nixpkgs/trunk
https://hydra.nixos.org/jobset/nixos/trunk-combined

**Comment by jonringer** [comment]
AFAICT, 3.0.4 is just a maintenance release: https://apparmor.net/news/release-3.0.4/

Unless someone is likely to be severely affected, this should probably go in staging, or staging-next if people are affected.

**Comment by zowoq** [comment]
I reverted this just before I had to go AFK for a bit.

I know master is fine as I checked the same jobs you listed. But I can see that it got merged into staging-next by the action.

I don't know if it is going to be evaled and start building on staging-next before the next merge by the action?

May need to do a merge manually to avoid the new rebuilds on staging-next?

**Comment by jonringer** [comment]
> I know master is fine as I checked the same jobs you listed. But I can see that it got merged into staging-next by the action.

Fair enough, but it looks good https://hydra.nixos.org/jobset/nixpkgs/staging-next

**Comment by zowoq** [comment]
Seems `staging-next` `check_interval` was changed a few days ago from 12hrs to 120hr, so didn't need to be concerned about this being evaled and causing new rebuilds on that branch before the revert landed there.

**Comment by ajs124** [comment]
re-opened as #161746

sorry again for the trouble

**Pull request merged**
