### PR TITLE
tuxedo-keyboard: 3.0.7 -> 3.0.8

### PR DESCRIPTION
**Pull request by blitz**
###### Motivation for this change

This PR bumps the tuxedo-keyboard module to its latest version and exposes all kernel modules from it. `tuxedo_io` is required to run the [Tuxedo Control Center](https://www.tuxedocomputers.com/en/TUXEDO-Control-Center.tuxedo).

Relates to #135841 and #132206.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by blitz** [comment]
@Mic92 I've split out the kernel module update from #135841 to avoid blocking this on the TCC packaging issues.

**Comment by Mic92** [comment]
Should we backport this?

**Comment by blitz** [comment]
> Should we backport this?

Yes.

**Comment by blitz** [comment]
@Mic92 There is one commit missing to auto-backport. I'll manually open a PR.

**Pull request merged**
