### PR TITLE
Firefox bin 69.0.1

### PR DESCRIPTION
**Pull request by taku0**
###### Motivation for this change

- Moderate security fix
- Other bug fixes

https://www.mozilla.org/en-US/firefox/69.0.1/releasenotes/
https://www.mozilla.org/en-US/security/advisories/mfsa2019-31/

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Only tested `firefox-bin`. `firefox` is being built.

###### Notify maintainers

cc @edolstra @andir

### CODE REVIEW

**Review by jonringer — COMMENTED** [review]
I seem to get a regression, these build on master:

```
builder for '/nix/store/lcyyfnzyna7xgi341pj7pamw5z6m952p-firefox-unwrapped-69.0.1.drv' failed with exit code 2; last 10 log lines:
                   from /build/firefox-69.0.1/obj-x86_64-pc-linux-gnu/dom/bindings/HeapSnapshotBinding.cpp:8,
                   from /build/firefox-69.0.1/obj-x86_64-pc-linux-gnu/dom/bindings/UnifiedBindings9.cpp:2:
  /nix/store/pcs8pq4a5rkym1hzibqz7da45fxkmig7-gcc-8.3.0/include/c++/8.3.0/bits/stl_map.h:100:11: note: 'class std::map<long unsigned int, mozilla::layers::ScrollUpdateInfo>' declared here
       class map
             ^~~
  make[3]: Leaving directory '/build/firefox-69.0.1/obj-x86_64-pc-linux-gnu/dom/bindings'
  make[2]: Leaving directory '/build/firefox-69.0.1/obj-x86_64-pc-linux-gnu'
  make[1]: *** [/build/firefox-69.0.1/config/recurse.mk:34: compile] Error 2
  make[1]: Leaving directory '/build/firefox-69.0.1/obj-x86_64-pc-linux-gnu'
  make: *** [/build/firefox-69.0.1/config/rules.mk:391: default] Error 2
cannot build derivation '/nix/store/nmcd8q1ijb5zd20320hfj9jzdb5i27jz-adoptopenjdk-icedtea-web-1.8.3.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/y6nb8c2q9riw6cicjj3kqwrn1bip5hvs-firefox-69.0.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/nqacg53lxhdhh4drnzak7a23zilrdjws-mozplugger-2.1.6.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/qqv34zgiw15ln1fnwqqvzzbg7xz01bgd-slimerjs-1.0.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/d4jp12sp76vwrbri98nq6zqy6fc8hl39-env.drv': 4 dependencies couldn't be built
[21 built (1 failed), 12 copied (100.9 MiB), 19.1 MiB DL]
error: build of '/nix/store/d4jp12sp76vwrbri98nq6zqy6fc8hl39-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/69099
4 package failed to build:
adoptopenjdk-icedtea-web xulrunner mozplugger slimerjs
```

**Comment by taku0** [comment]
The packages are successfully built with this PR rebased on master (d8adf06d355e9f49c86089c7231202094f4ede05).

```
$ nix-build -I nixpkgs=. --keep-failed --keep-going -A pkgs.adoptopenjdk-icedtea-web -A pkgs.xulrunner -A pkgs.mozplugger -A pkgs.slimerjs
/nix/store/ra3r99yc84k430viqxcvcz6ygbdkjfaz-adoptopenjdk-icedtea-web-1.8.3
/nix/store/k9akv5bbqnjy7plq8pja0kxp76sfz7x7-firefox-unwrapped-69.0.1
/nix/store/fpr7lj7wyqf3grww4ms5klq90c33pqyk-mozplugger-2.1.6
/nix/store/nnnzqhsm7jj7m1cdzj68igdq84limbyc-slimerjs-1.0.0
```

**Review by vcunat — APPROVED** [review]
Both work fine for me atop master.

**Comment by vcunat** [comment]
Hmm, I verified even exact `/nix/store/lcyyfnzyna7xgi341pj7pamw5z6m952p-firefox-unwrapped-69.0.1.drv` builds &ndash; I hope it was just some rare glitch.

**Comment by Mic92** [comment]
Also built for me.

**Comment by Mic92** [comment]
[detached HEAD 61201f89da9] firefox-bin: 69.0 -> 69.0.1
 Author: taku0 <mxxouy6x3m_github@tatapa.org>
 Date: Thu Sep 19 21:43:32 2019 +0900
 1 file changed, 935 insertions(+), 935 deletions(-)
 rewrite pkgs/applications/networking/browsers/firefox-bin/release_sources.nix (60%)
Press Enter to continue
[detached HEAD 1bf3db545cb] firefox: 69.0 -> 69.0.1
 Author: taku0 <mxxouy6x3m_github@tatapa.org>
 Date: Thu Sep 19 21:50:43 2019 +0900
 1 file changed, 2 insertions(+), 2 deletions(-)

**Comment by Mic92** [comment]
[detached HEAD 75fdf70a92d] firefox-bin: 69.0 -> 69.0.1
 Author: taku0 <mxxouy6x3m_github@tatapa.org>
 Date: Thu Sep 19 21:43:32 2019 +0900
 1 file changed, 935 insertions(+), 935 deletions(-)
 rewrite pkgs/applications/networking/browsers/firefox-bin/release_sources.nix (60%)
Press Enter to continue
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your merge.renamelimit variable to at least 2080 and retry the command.
[detached HEAD d91b06e4362] firefox: 69.0 -> 69.0.1
 Author: taku0 <mxxouy6x3m_github@tatapa.org>
 Date: Thu Sep 19 21:50:43 2019 +0900
 1 file changed, 2 insertions(+), 2 deletions(-)

**Pull request merged**
