### PR TITLE
qtchan: init at v0.100

### PR DESCRIPTION
**Pull request by ghost**
###### Motivation for this change
A fun /g/ project that I think deserves a package.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthewbauer** [comment]
@grahamcofborg build qtchan

**Comment by matthewbauer** [comment]
Can you see if qmake install works for the install phase.

**Comment by Chiiruno** [comment]
It doesn't, that's why I manually specified the `installPhase`.
As for Darwin not building, I'll just set the platform to linux.

**Comment by matthewbauer** [comment]
Applied in 8419c347ca303839ff97ea2750276da0b9977e0b.

**Pull request closed without merging**
