### PR TITLE
nixos/podman: allow changing the default network

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Description of changes

You might want a different network if you happen to be using the 10.88.x.x network for something else.

Been running with this for a very long time.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by zowoq — CHANGES_REQUESTED** [review]
Please undo the formatting changes or move them to a separate commit.

**Comment by zowoq** [comment]
TBH I'd really prefer not to add more networking options until after we've switched to `netavark` .

**Comment by peterhoeg** [comment]
The formatting is just `nixpkgs-fmt` doing its thing on save, but I absolutely understand where you're coming from.

I've carried this PR locally for over a year I think, so if you want to hold off on changes, that's not a problem. Your call.

**Comment by zowoq** [comment]
Thanks, give me a few weeks and I should get around to the `netavark` changes. I'll switch this to a draft for now.

**Comment by bachp** [comment]
> Thanks, give me a few weeks and I should get around to the `netavark` changes. I'll switch this to a draft for now.

@zowoq I'm also interested in switching to `netavark`, let me know if you have something to test

**Comment by peterhoeg** [comment]
now that nixpkgs-fmt changes have been merged, the changes are significant smaller. If you would still prefer to wait, that is of course your call @zowoq

**Comment by zowoq** [comment]
Yes, I'd rather wait.

**Comment by zowoq** [comment]
`netavark` PR: https://github.com/NixOS/nixpkgs/pull/199965

Closing this as it's not needed with `defaultNetwork` changing to `settings` style config.

**Pull request closed without merging**
