### PR TITLE
minder: init at 1.5.0

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

Mind-mapping application for Elementary OS!

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by alexarice — APPROVED** [review]
Have tested with nix-review and I can't see anything obviously wrong with the code. My only concern is that the executable file is called `com.github.phase1geo.minder`. I found this a bit confusing so it could be worth patching this to just be `minder`

**Review by mmahut — CHANGES_REQUESTED** [review]
The output binary has a wrong name probably ``com.github.phase1geo.minder`` however it works fine.

**Comment by dtzWill** [comment]
@mmahut: should be good now, look good to you? :)

**Comment by mmahut** [comment]
Looks good!

**Pull request merged**
