### PR TITLE
regenerate `nodePackages`

### PR DESCRIPTION
**Pull request by matthew-piziak**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthew-piziak** [comment]
@ryantm If you could let me know what I should do at this point, that would be great. My first `textlint` PR just got merged with no ceremony, so I don't know if there's more I should be doing.

**Comment by ryantm** [comment]
@GrahamcOfBorg build nodePackages.vscode-css-languageserver-bin 
@GrahamcOfBorg build nodePackages.vscode-html-languageserver-bin 
@GrahamcOfBorg build nodePackages.vue-language-server
@GrahamcOfBorg build nodePackages.bash-language-server
@GrahamcOfBorg build nodePackages.speed-test
@GrahamcOfBorg build nodePackages.typescript-language-server
@GrahamcOfBorg build nodePackages.textlint-plugin-latex
@GrahamcOfBorg build nodePackages.textlint-rule-abbr-within-parentheses
@GrahamcOfBorg build nodePackages.textlint-rule-alex
@GrahamcOfBorg build nodePackages.textlint-rule-common-misspellings
@GrahamcOfBorg build nodePackages.textlint-rule-diacritics
@GrahamcOfBorg build nodePackages.textlint-rule-en-max-word-count
@GrahamcOfBorg build nodePackages.textlint-rule-max-comma
@GrahamcOfBorg build nodePackages.textlint-rule-no-start-duplicated-conjunction
@GrahamcOfBorg build nodePackages.textlint-rule-period-in-list-item
@GrahamcOfBorg build nodePackages.textlint-rule-stop-words
@GrahamcOfBorg build nodePackages.textlint-rule-terminology
@GrahamcOfBorg build nodePackages.textlint-rule-unexpanded-acronym
@GrahamcOfBorg build nodePackages.textlint-rule-write-good
@GrahamcOfBorg build nodePackages.write-good

**Comment by ryantm** [comment]
@GrahamcOfBorg build nodePackages.vue-language-server

**Comment by matthew-piziak** [comment]
Thank you!! :)

**Pull request merged**
