### PR TITLE
mutter, gnome-shell: 44.1 → 44.2

### LINKED ISSUE #230097: GNOME 44 problems with Qt-applications
### Describe the bug
Since the Gnome 44 (under wayland) update, on multiple devices reproducible errors with Qt based applications.

### Steps To Reproduce
- nextcloud-client: The application does not show itself after first start, it is only visible in Activities as an empty frame. You have to restart the application and it works.
- keepassxc: The Drag-and-Drop functionality does not work.

This are only two errors that I found, but I think many Qt-applications are affected. The solution is to set `QT_QPA_PLATFORM=wayland` inside a shell and start the application. The errors vanish. Currently, my workaround is setting it global with
```
  environment.variables = {
    QT_QPA_PLATFORM = "wayland";
  };
```

Perhaps, can you add the variable as a default setting for each gnome under wayland session? 
Thank you

### Notify maintainers
@bobby285271
@hedning
@jtojnar
@dasj19
@maxeaubrey

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.01 MiB download, 0.05 MiB unpacked):
  /nix/store/pgf87rgkzdbqhhsddpligy8xiwar63w8-stdenv-linux
copying path '/nix/store/pgf87rgkzdbqhhsddpligy8xiwar63w8-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.0, NixOS, 23.05 (Stoat), 23.05pre480050.1a411f23ba2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - channels(goetz): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### LINKED ISSUE #236765: Update request: gnome-shell 44.1 → 44.2
- Package name: gnome-shell
- Latest released version: 44.2

- Current version on the unstable channel: 44.1
- Current version on the stable/release channel: 44.1

- [x ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@bobby285271 @hedning @jtojnar @dasj19 @maxeaubrey 

-----

Note for maintainers: Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by bobby285271**
###### Description of changes

Closes #236765, Closes #230097

###### Things done

- [x] Tested DnD with strawberry
- [x] Briefly tested builtin screenshot, screen recording, did not test [EasyScreenCast](https://github.com/EasyScreenCast/EasyScreenCast) extension
  - By 'briefly', I am aware of [gnome-shell#6747](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6747) but did not investigate/manage to reproduce
- [x] Confirmed [focus issue is not fixed](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/3041#note_1760064)
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
@ofborg test gnome

**Review by jtojnar — APPROVED** [review]
Changes look okay.

**Comment by daemonspudguy** [comment]
How long does it take for this to effect Unstable?

**Comment by bobby285271** [comment]
1-7 days

- https://nixos.wiki/wiki/Nix_channels#Channel_update_process
- https://nixpk.gs/pr-tracker.html?pr=237042

**Pull request merged**
