### PR TITLE
elixir: 1.0.5 -> 1.1.0

### PR DESCRIPTION
**Pull request by Havvy**
Tested and working locally.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
There is already 1.1.1 available! Can you [update to 1.1.1](http://monitor.nixos.org/patch?p=elixir&v=1.1.1)?

**Comment by Havvy** [comment]
Sure.

**Comment by Havvy** [comment]
Umm, I'm having issues with `mix` on v1.1.1....

```
[havvy@nixos:~]$ mix --help
/nix/store/8xfxnm4a7jvyh0i1sd967z6rws8lh21a-coreutils-8.24/bin/env: /nix/store/6c4s7sp11vp2vjapf4y1r94zcajg5m2h-elixir-1.1.1/b: No such file or directory
```

**Comment by Havvy** [comment]
Solved that issue.

**Pull request merged**
