### PR TITLE
dtools: 2.075.1 -> 2.078.0

### PR DESCRIPTION
**Pull request by ThomasMader**
###### Motivation for this change

dtools: 2.075.1 -> 2.078.0

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
Is the `rdmd_test` executable usable in its current form?

```console
$ /nix/store/z28shj7a8g2n4phsavkfis3rihlws80x-dtools-2.078.0/bin/rdmd_test
object.Exception@rdmd_test.d(63): Path to rdmd does not exist: rdmd.d
----------------
??:? pure @safe void std.exception.bailOut!(Exception).bailOut(immutable(char)[], ulong, const(char[])) [0x48fbde]
??:? pure @safe bool std.exception.enforce!(Exception, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x4943c8]
??:? _Dmain [0x489377]
```

**Comment by ThomasMader** [comment]
> Is it reasonable to keep rdmd_test installed? (Is there any use case beyond our checkPhase?)

No, removed it.

**Comment by Mic92** [comment]
@GrahamcOfBorg build dtools

**Comment by ThomasMader** [comment]
And again the bot build isn't working on Mac OSX. See also https://github.com/NixOS/nixpkgs/pull/33532#issuecomment-355838143

**Comment by Mic92** [comment]
@GrahamcOfBorg build dtools

**Pull request merged**
