### PR TITLE
plasma5: 5.13.0 -> 5.13.2

### PR DESCRIPTION
**Pull request by bkchr**
###### Motivation for this change

@peterhoeg @adisbladis 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
@GrahamcOfBorg build plasma-desktop sddm-kcm 
@GrahamcOfBorg test plasma5
@GrahamcOfBorg test sddm

**Comment by peterhoeg** [comment]
@GrahamcOfBorg test plasma5

Tests didn't run due to download errors so try again.

**Comment by bkchr** [comment]
@peterhoeg the failed again, but before the succeeded on x86_64.

**Comment by peterhoeg** [comment]
You ran the tests locally?

**Comment by bkchr** [comment]
Yep.

**Comment by peterhoeg** [comment]
Excellent!

**Pull request merged**
