### PR TITLE
linuxPackages.rtl8821au: 2021-11-05 -> 2022-03-08

### PR DESCRIPTION
**Pull request by alyssais**
###### Description of changes

Fixes the build with Linux 5.17.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]
Can you please update the homepage to https://github.com/morrownr/8821au-20210708?

**Comment by alyssais** [comment]
No, I think the current value makes more sense.  morrownr/8821au is the homepage of the 8821au driver as a whole, and morrownr/8821au-20210708 is the location of the current implementation.  Using the 8821au repo as the homepage means it'll always link to the current version, which I think is desirable for a homepage and inline with how normal homepages work.  I think using multiple GitHub repositories like this is a very strange way of working, but it is what it is.

**Comment by SuperSandro2000** [comment]
But the current commit is not contained in the homepage which is unexpected when homepage points to a github repo.

**Comment by alyssais** [comment]
I agree that's unexpected, because upstream is doing something strange.  But they're basically using the 8821au repo as a web page with information, i.e. a homepage.  It's strange that they're using a GitHub repo instead of GitHub Pages or something, but just because it _happens_ to be a GitHub repo rather than some other way of hosting/presenting the information doesn't mean that it isn't the homepage.

**Pull request merged**
