### PR TITLE
halide: 15.0.1 -> 16.0.0

### PR DESCRIPTION
**Pull request by twesterhout**
This PR supersedes  #241047.

## Description of changes

Link to the upstream release: https://github.com/halide/Halide/releases/tag/v16.0.0

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by OPNA2608** [comment]
Testing on x86_64-darwin, fails to compile fuzz tests.

```
[ 86%] Building CXX object test/fuzz/CMakeFiles/fuzz_bounds.dir/bounds.cpp.o
[ 86%] Linking CXX executable runtime_internal_memory_arena
error: current translation unit is compiled with the target feature '-fsanitize=fuzzer-no-link' but the AST file was not
1 error generated.
make[2]: *** [test/fuzz/CMakeFiles/fuzz_bounds.dir/build.make:78: test/fuzz/CMakeFiles/fuzz_bounds.dir/bounds.cpp.o] Error 1
```

Post-release, upstream committed https://github.com/halide/Halide/commit/09c5d1d19ec8e6280ccbc01a8a12decfb27226ba to disable these tests unless specifically requested. Prolly either `fetchpatch` to change the default ahead of the next release or set `WITH_TEST_FUZZ` to off.

**Comment by twesterhout** [comment]
@OPNA2608 thanks, fixed!

**Review by OPNA2608 — COMMENTED** [review]
Result of `nixpkgs-review pr 250545` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>halide</li>
  </ul>
</details>

---

One question/suggestion, otherwise LGTM.

**Review by OPNA2608 — APPROVED** [review]
Result of `nixpkgs-review pr 250545` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>halide</li>
  </ul>
</details>

LGTM.

**Pull request merged**
