### PR TITLE
ycmd: 2016-01-12 -> 2017-02-03

### LINKED ISSUE #14349: ycmd fails to work with Atom you-complete-me plugin due to wrapper script
## Basic info

To make sure that we are on the same page:
- Kernel: `Linux szamito 3.18.24 #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970 x86_64 GNU/Linux`
- System: `15.09.git.45128deM (Dingo)`
- Nix version: `nix-env (Nix) 1.10`
- Nixpkgs version: `"15.09.1177.f8a795e"`
## Describe your issue here

I installed atom and ycmd, and the you-complete-me plugin for Atom, but none of the YCM functionality in Atom seems to work.
### Expected result

It works.
### Actual result

It doesn't.
### Steps to reproduce

`nix-env -i ycmd atom`
Install you-complete-me from Atom's package manager.
Set the ycmd path in the plugin's settings appropriately (`/home/glaebhoerl/.nix-profile/lib/ycmd` in my case)
Open a C/C++ source file, right click on something, try (e.g.) "GoToDeclaration" from the "YouCompleteMe" submenu
(nothing happens)

---

Boilerplate out of the way!

The above commands all say 15.09, but I installed ycmd and atom from the 16.03 beta channel. `atom-1.5.3`, `ycmd-2016-01-12`, you-complete-me plugin is 0.7.4.

Running Atom in Dev Mode, if we try anything from the YouCompleteMe submenu, we see this in the debug console:

you-complete-me-python

Looking at that `__main__.py` file, we see that it contains:

``` bash
#! /nix/store/w6rc026a5kw9zyvvapqq6li157ckvwq7-bash-4.3-p42/bin/bash -e
export PYTHONPATH=/nix/store/9jlki3pyyxxlldsdj2zr2d5y637lfr8r-python2.7-waitress-0.8.9/lib/python2.7/site-packages:/nix/store/jzq8nbp1z182kxz3vyj51p2qki2s1vdq-python2.7-frozendict-0.5/lib/python2.7/site-packages:/nix/store/7h43ls1ixp0s1vhbdjjm44dvdkaggmlk-python2.7-bottle-0.12.8/lib/python2.7/site-packages${PYTHONPATH:+:}$PYTHONPATH
exec -a "$0" /nix/store/f91xrlqmby1sb0c3jsqbycmf19sk4nja-ycmd-2016-01-12/lib/ycmd/ycmd/.__main__.py-wrapped "${extraFlagsArray[@]}" "$@"
```

It's actually a bash script! Which Nix created to setup `PYTHONPATH` before invoking the _real_ `__main__.py` from `ycmd`. And the syntax error is presumably because Atom/YCM are trying to execute it as a python script.

We can verify this by looking at the [source for the you-complete-me plugin](https://github.com/Qusic/atom-youcompleteme/blob/9c856557ff7acc16777bdf782f547777cf7d6b4d/lib/handler.coffee#L60-L64):

``` coffee
  startServer = (optionsFile) -> new Promise (fulfill, reject) ->
    ycmdProcess = new BufferedProcess
      command: atom.config.get 'you-complete-me.pythonExecutable'
      args: [
        path.resolve atom.config.get('you-complete-me.ycmdPath'), 'ycmd'
```

But I'm not sure where or how this should be fixed.

### PR DESCRIPTION
**Pull request by cstrahan**
Also, remove wrapper bash script and symlink completion backends to ycmd can find them.

This builds on #22463 and should fix #14349.

### CODE REVIEW

**Comment by cstrahan** [comment]
With the code as it is right now, I inject the following into `__main__.py`:

```python
import os; os.environ['PATH'] = ('{0}:{1}' if os.getenv('PATH', '') != '' else '{1}').format('$program_PATH', os.getenv('PATH', ''))
```

... where `$program_PATH` is substituted with the environment variable that the `wrapPython` hook sets up.

That preserves the behavior of the wrapper script, but I don't know if it's really necessary. In fact, that puts the build-time `python` on `PATH` (as should be expected), which could can then cause problems for some people's use of ycmd -- ycmd will by default attempt to start the JediHTTP with the pthon on `PATH` which will end up being python 2, but that'll cause problems if someone want's to, say in a `shell.nix`, put python 3 on their `PATH` so they can have JediHTTP parse their python 3 project. They can always specify a specific python in their config... but IMO the `PATH` based approach should continue to work.

So, I think I'm not going to try to preserve the `PATH` manipulation -- I don't think it'll cause any problems to do so in this package.

**Comment by cstrahan** [comment]
Also TODO in a separate PR: have the vim plugin use this package, instead of it also compiling ycmd.

**Comment by cstrahan** [comment]
In the latest commit I've switched to using the vendored python libs - YouCompleteMe expects that it can source those libs, and things get very tricky when trying to use our packaged libraries while trying not to break YCM's assumptions. We could probably patch YCM's source, but by using the vendored python libs, we make our packaged YouCompleteMe and ycmd work seamlessly together (see https://github.com/NixOS/nixpkgs/issues/22614 for the changes to the vim plugin).

**Comment by rasendubi** [comment]
This does seem to break darwin build: https://hydra.nixos.org/build/48027016

**Pull request merged**
