### PR TITLE
Draft: gitlab: 13.10.2 -> 13.11.2

### PR DESCRIPTION
**Pull request by ghost**
It builds, starts, but pushing doesn't work:

```
[pbb@mozarella:~/proj/irdest-nixfiles]$ git push origin main
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 12 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 1.14 KiB | 1.14 MiB/s, done.
Total 4 (delta 2), reused 0 (delta 0), pack-reused 0
remote: GitLab: 500 Internal Server Error
To ssh://git.irde.st:22/we/infra/nixfiles.git
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'ssh://git.irde.st:22/we/infra/nixfiles.git'

[pbb@mozarella:~/proj/irdest-nixfiles]$
```

```
Apr 27 22:57:05 irdest-services puma[2662]: I, [2021-04-27T22:57:05.925059 #2662]  INFO -- : Started POST "/api/v4/internal/allowed" for 127.0.0.1 at 2021-04-27 22:57:05 +0000
Apr 27 22:57:05 irdest-services puma[2662]: I, [2021-04-27T22:57:05.993642 #2662]  INFO -- : Started POST "/api/v4/internal/allowed" for 127.0.0.1 at 2021-04-27 22:57:05 +0000
Apr 27 22:57:06 irdest-services gitaly[1593]: time="2021-04-27T22:57:06Z" level=info msg="finished unary call with code OK" correlation_id=01F4ARSSC3ZJATRN1AGGE3SEJP grpc.code=OK grpc.meta.auth_version=v2 grpc.meta.client_name=gitlab-web grpc.meta.deadline_type=regular grpc.method=RepositoryExists grpc.request.deadline="2021-04-27T22:57:16.009Z" grpc.request.fullMethod=/gitaly.RepositoryService/RepositoryExists grpc.request.glProjectPath=we/infra/nixfiles grpc.request.glRepository=project-2 grpc.request.repoPath=@hashed/d4/73/d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35.git grpc.request.repoStorage=default grpc.request.topLevelGroup=@hashed grpc.service=gitaly.RepositoryService grpc.start_time="2021-04-27T22:57:06.019Z" grpc.time_ms=0.062 peer.address=@ pid=1593 remote_ip=127.0.0.1 span.kind=server system=grpc username=milan
Apr 27 22:57:06 irdest-services gitaly[1593]: time="2021-04-27T22:57:06Z" level=info msg="diskcache state change" correlation_id=01F4ARSSC3ZJATRN1AGGE3SEJP diskcache=7f7d8f8e-ec00-4bc7-b934-632b3ea0e0f8 grpc.meta.auth_version=v2 grpc.meta.client_name=gitlab-web grpc.meta.deadline_type=regular grpc.method=Cleanup grpc.request.deadline="2021-04-27T22:57:16.001Z" grpc.request.fullMethod=/gitaly.RepositoryService/Cleanup grpc.request.glProjectPath=we/infra/nixfiles grpc.request.glRepository=project-2 grpc.request.repoPath=@hashed/d4/73/d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35.git grpc.request.repoStorage=default grpc.request.topLevelGroup=@hashed grpc.service=gitaly.RepositoryService grpc.start_time="2021-04-27T22:57:06.021Z" peer.address=@ pid=1593 remote_ip=127.0.0.1 span.kind=server system=grpc username=milan
Apr 27 22:57:06 irdest-services gitaly[1593]: time="2021-04-27T22:57:06Z" level=info msg="finished unary call with code OK" correlation_id=01F4ARSSC3ZJATRN1AGGE3SEJP grpc.code=OK grpc.meta.auth_version=v2 grpc.meta.client_name=gitlab-web grpc.meta.deadline_type=regular grpc.method=Cleanup grpc.request.deadline="2021-04-27T22:57:16.001Z" grpc.request.fullMethod=/gitaly.RepositoryService/Cleanup grpc.request.glProjectPath=we/infra/nixfiles grpc.request.glRepository=project-2 grpc.request.repoPath=@hashed/d4/73/d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35.git grpc.request.repoStorage=default grpc.request.topLevelGroup=@hashed grpc.service=gitaly.RepositoryService grpc.start_time="2021-04-27T22:57:06.021Z" grpc.time_ms=15.587 peer.address=@ pid=1593 remote_ip=127.0.0.1 span.kind=server system=grpc username=milan
Apr 27 22:57:06 irdest-services gitaly[1593]: time="2021-04-27T22:57:06Z" level=info msg="finished unary call with code OK" correlation_id=01F4ARSSC3ZJATRN1AGGE3SEJP grpc.code=OK grpc.meta.auth_version=v2 grpc.meta.client_name=gitlab-web grpc.meta.deadline_type=regular grpc.method=CommitIsAncestor grpc.request.deadline="2021-04-27T22:57:16.002Z" grpc.request.fullMethod=/gitaly.CommitService/CommitIsAncestor grpc.request.glProjectPath=we/infra/nixfiles grpc.request.glRepository=project-2 grpc.request.repoPath=@hashed/d4/73/d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35.git grpc.request.repoStorage=default grpc.request.topLevelGroup=@hashed grpc.service=gitaly.CommitService grpc.start_time="2021-04-27T22:57:06.062Z" grpc.time_ms=1.95 peer.address=@ pid=1593 remote_ip=127.0.0.1 span.kind=server system=grpc username=milan
Apr 27 22:57:06 irdest-services puma[2662]: I, [2021-04-27T22:57:06.097571 #2662]  INFO -- : Processing by Gitlab::RequestForgeryProtection::Controller#index as HTML
Apr 27 22:57:06 irdest-services puma[2662]: W, [2021-04-27T22:57:06.097778 #2662]  WARN -- : Can't verify CSRF token authenticity.
Apr 27 22:57:06 irdest-services puma[2662]: I, [2021-04-27T22:57:06.098164 #2662]  INFO -- : Completed 422 Unprocessable Entity in 0ms (ActiveRecord: 0.0ms | Elasticsearch: 0.0ms | Allocations: 259)
Apr 27 22:57:06 irdest-services puma[2662]: F, [2021-04-27T22:57:06.099042 #2662] FATAL -- :
Apr 27 22:57:06 irdest-services puma[2662]: GRPC::Unimplemented (12:unknown method ListLFSPointers for service gitaly.BlobService. debug_error_string:{"created":"@1619564226.096490999","description":"Error received from peer unix:/var/gitlab/state/tmp/sockets/gitaly.socket","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"unknown method ListLFSPointers for service gitaly.BlobService","grpc_status":12}):
Apr 27 22:57:06 irdest-services puma[2662]:   /nix/store/vklvn52nqj9yp45s5nn40c8w94ix6pm8-ruby2.7.3-grpc-1.30.2/lib/ruby/gems/2.7.0/gems/grpc-1.30.2/src/ruby/lib/grpc/generic/active_call.rb:29:in `check_status'
Apr 27 22:57:06 irdest-services puma[2662]:   /nix/store/vklvn52nqj9yp45s5nn40c8w94ix6pm8-ruby2.7.3-grpc-1.30.2/lib/ruby/gems/2.7.0/gems/grpc-1.30.2/src/ruby/lib/grpc/generic/active_call.rb:180:in `attach_status_results_and_complete_call'
Apr 27 22:57:06 irdest-services puma[2662]:   /nix/store/vklvn52nqj9yp45s5nn40c8w94ix6pm8-ruby2.7.3-grpc-1.30.2/lib/ruby/gems/2.7.0/gems/grpc-1.30.2/src/ruby/lib/grpc/generic/active_call.rb:169:in `receive_and_check_status'
Apr 27 22:57:06 irdest-services puma[2662]:   /nix/store/vklvn52nqj9yp45s5nn40c8w94ix6pm8-ruby2.7.3-grpc-1.30.2/lib/ruby/gems/2.7.0/gems/grpc-1.30.2/src/ruby/lib/grpc/generic/active_call.rb:337:in `each_remote_read_then_finish'
Apr 27 22:57:06 irdest-services puma[2662]:   puma: cluster worker 1: 2581 [gitlab-puma-worker]:in `each'
Apr 27 22:57:06 irdest-services gitaly[1593]: time="2021-04-27T22:57:06Z" level=error msg="Internal API error" correlation_id=01F4ARSSC3ZJATRN1AGGE3SEJP duration_ms=107ns error="500 Internal Server Error" method=POST status=500 url="http://unix/api/v4/internal/allowed"
Apr 27 22:57:06 irdest-services gitaly[1593]: time="2021-04-27T22:57:06Z" level=warning msg="stopping transaction because pre-receive hook failed" correlation_id=01F4ARSSC3ZJATRN1AGGE3SEJP error="GitLab: 500 Internal Server Error" grpc.meta.deadline_type=none grpc.method=PreReceiveHook grpc.request.fullMethod=/gitaly.HookService/PreReceiveHook grpc.request.glProjectPath=we/infra/nixfiles grpc.request.glRepository=project-2 grpc.request.repoPath=@hashed/d4/73/d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35.git grpc.request.repoStorage=default grpc.request.topLevelGroup=@hashed grpc.service=gitaly.HookService grpc.start_time="2021-04-27T22:57:05.992Z" peer.address=@ pid=1593 span.kind=server system=grpc
Apr 27 22:57:06 irdest-services gitaly[1593]: time="2021-04-27T22:57:06Z" level=info msg="finished streaming call with code OK" correlation_id=01F4ARSSC3ZJATRN1AGGE3SEJP grpc.code=OK grpc.meta.deadline_type=none grpc.method=PreReceiveHook grpc.request.fullMethod=/gitaly.HookService/PreReceiveHook grpc.request.glProjectPath=we/infra/nixfiles grpc.request.glRepository=project-2 grpc.request.repoPath=@hashed/d4/73/d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35.git grpc.request.repoStorage=default grpc.request.topLevelGroup=@hashed grpc.service=gitaly.HookService grpc.start_time="2021-04-27T22:57:05.992Z" grpc.time_ms=108.224 peer.address=@ pid=1593 span.kind=server system=grpc
Apr 27 22:57:06 irdest-services gitaly[1593]: time="2021-04-27T22:57:06Z" level=warning msg="transport: http2Server.HandleStreams failed to read frame: read unix /tmp/gitaly-internal400417450/internal.sock->@: read: connection reset by peer" pid=1593 system=system
Apr 27 22:57:06 irdest-services gitaly[1593]: time="2021-04-27T22:57:06Z" level=info msg="diskcache state change" correlation_id=01F4ARSSC3ZJATRN1AGGE3SEJP diskcache=894ed7f4-d99c-4f23-ae69-982c1ade5437 grpc.meta.client_name=gitlab-shell grpc.meta.deadline_type=none grpc.method=SSHReceivePack grpc.request.fullMethod=/gitaly.SSHService/SSHReceivePack grpc.request.glProjectPath=we/infra/nixfiles grpc.request.glRepository=project-2 grpc.request.repoPath=@hashed/d4/73/d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35.git grpc.request.repoStorage=default grpc.request.topLevelGroup=@hashed grpc.service=gitaly.SSHService grpc.start_time="2021-04-27T22:57:05.952Z" peer.address=@ pid=1593 remote_ip="2a0f:4ac0:0:1::19d" span.kind=server system=grpc user_id=user-2 username=milan
Apr 27 22:57:06 irdest-services gitaly[1593]: time="2021-04-27T22:57:06Z" level=info msg="finished streaming call with code OK" correlation_id=01F4ARSSC3ZJATRN1AGGE3SEJP grpc.code=OK grpc.meta.client_name=gitlab-shell grpc.meta.deadline_type=none grpc.method=SSHReceivePack grpc.request.fullMethod=/gitaly.SSHService/SSHReceivePack grpc.request.glProjectPath=we/infra/nixfiles grpc.request.glRepository=project-2 grpc.request.repoPath=@hashed/d4/73/d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35.git grpc.request.repoStorage=default grpc.request.topLevelGroup=@hashed grpc.service=gitaly.SSHService grpc.start_time="2021-04-27T22:57:05.952Z" grpc.time_ms=156.856 peer.address=@ pid=1593 remote_ip="2a0f:4ac0:0:1::19d" span.kind=server system=grpc user_id=user-2 username=milan
Apr 27 22:57:06 irdest-services sshd[2562]: Close session: user gitlab from 2a0f:4ac0:0:1::19d port 36128 id 0
```

Also note that I had to manually edit the Gemfile to remove the "mail-smtp_pool" line.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by talyz** [comment]
Looks like the gitaly package wasn't updated, so it's probably still using the old one which doesn't have the `ListLFSPointers` method.

**Comment by petabyteboy** [comment]
Ah yes, I didn't run the thingies it in the right order. Have to test later if it's fixed.

**Review by talyz — APPROVED** [review]
Works well in my manual testing:
- Using the UI
- Cloning and pushing commits to a repo
- Adding an SSH key

**Comment by petabyteboy** [comment]
Oops, I had partially updated to 13.11.2 while fixing gitaly. But now all components are at 13.11.2 and there are only minor changes compared to what you tested.

**Pull request merged**
