### PR TITLE
powerdevil: build with ddcutil support

### PR DESCRIPTION
**Pull request by HurricanePootis**
## Description of changes

Powerdevil supports changing external monitor brightness via ddcutil, which sends DDC protocol messages over an I2C bus to the external monitor. However, powerdevil needs to be built with ddcutil and needs user access for the i2c bus. Therefore, I added ddcutil to the powerdevil package and enabled i2c along with powerdevil in the plasma module.

Shoutout @getchoo for the help!

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by K900** [comment]
This has been brought up before. DDC/CI is very unreliable, and using it incorrectly can lead to permanently messing up your hardware. It should not be enabled by default.

**Comment by HurricanePootis** [comment]
If you're talking about previous KDE versions, at least starting with version 6.0, KDE has refined their approach to using libddcutil as explained in [this blog](Starting with Plasma 6.0.4, our DDC/CI code was restructured so that a monitor is only hogged for the short time it takes to change the brightness. ddcutil works again as intended in a Plasma session.) here. Furthermore, distros like Arch have enabled ddcutil as of recent, and everything seems to be fine now.

**Comment by K900** [comment]
No, that's not the issue. The issue is that ddcutil, and DDC/CI in general, provides no way to enumerate devices, and has to blindly poke I2C buses and hope the right thing is on the other end, which can severely confuse other I2C hardware.

**Comment by HurricanePootis** [comment]
Alright, I appreciate the information. Thanks for taking the time for a response 👍

**Pull request closed without merging**
