### PR TITLE
tor-browser-bundle-bin: 10.0.5 -> 10.0.7

### PR DESCRIPTION
**Pull request by samb96**
###### Motivation for this change

Update to the latest version of tor-browser-bundle-bin. The URL for the old version 10.0.5 is returning 404.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

maintainers: @joachifm @hax404 @KarlJoad @matejc @offlinehacker @scaredmushroom @thoughtpolice

### CODE REVIEW

**Comment by samb96** [comment]
Result of `nixpkgs-review pr 106930` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>torbrowser (tor-browser-bundle-bin)</li>
  </ul>
</details>

**Comment by samb96** [comment]
@GrahamcOfBorg eval

**Comment by samb96** [comment]
I updated the version to 10.0.7, which includes [fixes for important security vulnerabilities](https://www.mozilla.org/en-US/security/advisories/mfsa2020-55/). See the [release notes](https://blog.torproject.org/new-release-tor-browser-1007) for more details.

**Comment by prusnak** [comment]
Backport to stable 20.09 in https://github.com/NixOS/nixpkgs/pull/107179

**Pull request merged**
