### PR TITLE
azure-functions-core-tools: patch /bin/bash

### PR DESCRIPTION
**Pull request by Detegr**
This is not pretty and I'm not sure what's the policy for such hacks, but I thought it's worth putting this out anyway as the whole tool isn't very usable on NixOS without something like this. Should they decide to include another string of "/bin/bash" this may not work correctly anymore, but I would be willing to take the risk, as the tool is currently broken anyway.

Of course building from source and patching the source would be the more correct way to achieve this (upstream [does not seem interested](https://github.com/Azure/azure-functions-core-tools/pull/3255) in fixing the issue), but it seemed that building the project isn't that trivial and I don't have the time to invest learning it.

My reasoning for doing this for `stdenv.isLinux` only is that MacOS most likely has `/bin/bash` installed anyway so the tool just works there already.

If someone knows how to do this elegantly without having python as dependency, I'm all ears :)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mdarocha** [comment]
This seems really hacky. I'd prefer switching to building from source, which should be hard to do using `buildDotnetModule`

**Comment by Detegr** [comment]
> This seems really hacky.

100% agreed :D

> I'd prefer switching to building from source, which should be hard to do using `buildDotnetModule`

I was having difficulty building it with normal dotnet toolchain. I'll give `buildDotnetModule` a shot tomorrow, maybe it has sane defaults that will just work.

**Comment by mdarocha** [comment]
I'd prefer not to merge it like that. Try doing the source build, if you encounter problems I can try helping

**Comment by Detegr** [comment]
I think I got the build working properly. I'll close this and open another PR.

**Pull request closed without merging**
