### PR TITLE
kubernetes: add kubectl zsh completion

### PR DESCRIPTION
**Pull request by mbode**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build kubernetes

**Comment by Mic92** [comment]
I can reproduce borg's failure.

**Comment by mbode** [comment]
@Mic92 sorry about that, should work now.

**Comment by Mic92** [comment]
@GrahamcOfBorg build kubernetes

**Comment by Mic92** [comment]
18.03:

[detached HEAD 386e8324d31] kubernetes: add kubectl zsh completion
 Author: Maximilian Bode <maximilian.bode@tngtech.com>
 Date: Sat Mar 31 16:37:32 2018 +0200
 1 file changed, 2 insertions(+), 1 deletion(-)

**Pull request merged**
