### PR TITLE
python3Packages.python-slugify: 4.0.1 -> 5.0.2

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 5.0.2

Change log: https://github.com/un33k/python-slugify/blob/master/CHANGELOG.md#502

Support for Python 2 was dropped by upstream.

This will most likely break Home Assistant.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 126255` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>home-assistant</li>
  </ul>
</details>
<details>
  <summary>29 packages built:</summary>
  <ul>
    <li>aws-sam-cli</li>
    <li>cookiecutter (python38Packages.cookiecutter)</li>
    <li>csvkit</li>
    <li>kaggle (python38Packages.kaggle)</li>
    <li>kcc</li>
    <li>papis (python38Packages.papis)</li>
    <li>python38Packages.agate</li>
    <li>python38Packages.agate-dbf</li>
    <li>python38Packages.agate-excel</li>
    <li>python38Packages.agate-sql</li>
    <li>python38Packages.mesa</li>
    <li>python38Packages.pyruckus</li>
    <li>python38Packages.python-slugify</li>
    <li>python38Packages.spacy-transformers</li>
    <li>python38Packages.sphinx-material</li>
    <li>python38Packages.transformers</li>
    <li>python39Packages.agate</li>
    <li>python39Packages.agate-dbf</li>
    <li>python39Packages.agate-excel</li>
    <li>python39Packages.agate-sql</li>
    <li>python39Packages.cookiecutter</li>
    <li>python39Packages.kaggle</li>
    <li>python39Packages.mesa</li>
    <li>python39Packages.papis</li>
    <li>python39Packages.pyruckus</li>
    <li>python39Packages.python-slugify</li>
    <li>python39Packages.sphinx-material</li>
    <li>python39Packages.transformers</li>
    <li>transifex-client</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 126255` at 255e90f7 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>python38Packages.spacy-transformers</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>home-assistant</li>
  </ul>
</details>
<details>
  <summary>28 packages built successfully:</summary>
  <ul>
    <li>aws-sam-cli</li>
    <li>cookiecutter (python38Packages.cookiecutter)</li>
    <li>csvkit</li>
    <li>kaggle (python38Packages.kaggle)</li>
    <li>kcc</li>
    <li>papis (python38Packages.papis)</li>
    <li>python38Packages.agate</li>
    <li>python38Packages.agate-dbf</li>
    <li>python38Packages.agate-excel</li>
    <li>python38Packages.agate-sql</li>
    <li>python38Packages.mesa</li>
    <li>python38Packages.pyruckus</li>
    <li>python38Packages.python-slugify</li>
    <li>python38Packages.sphinx-material</li>
    <li>python38Packages.transformers</li>
    <li>python39Packages.agate</li>
    <li>python39Packages.agate-dbf</li>
    <li>python39Packages.agate-excel</li>
    <li>python39Packages.agate-sql</li>
    <li>python39Packages.cookiecutter</li>
    <li>python39Packages.kaggle</li>
    <li>python39Packages.mesa</li>
    <li>python39Packages.papis</li>
    <li>python39Packages.pyruckus</li>
    <li>python39Packages.python-slugify</li>
    <li>python39Packages.sphinx-material</li>
    <li>python39Packages.transformers</li>
    <li>transifex-client</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: unused-argument

Unused argument: `python`.
Near pkgs/development/python-modules/python-slugify/default.nix:5:3:
```
  |
5 | , python
  |   ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by ethancedwards8** [comment]
esult of `nixpkgs-review pr 126255` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>aws-sam-cli</li>
    <li>python38Packages.spacy-transformers</li>
  </ul>
</details>
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>csvkit</li>
    <li>python38Packages.agate-sql</li>
    <li>python38Packages.transformers</li>
    <li>python39Packages.agate-sql</li>
    <li>python39Packages.transformers</li>
  </ul>
</details>
<details>
  <summary>22 packages built:</summary>
  <ul>
    <li>cookiecutter (python38Packages.cookiecutter)</li>
    <li>kaggle (python38Packages.kaggle)</li>
    <li>kcc</li>
    <li>papis (python38Packages.papis)</li>
    <li>python38Packages.agate</li>
    <li>python38Packages.agate-dbf</li>
    <li>python38Packages.agate-excel</li>
    <li>python38Packages.mesa</li>
    <li>python38Packages.pyruckus</li>
    <li>python38Packages.python-slugify</li>
    <li>python38Packages.sphinx-material</li>
    <li>python39Packages.agate</li>
    <li>python39Packages.agate-dbf</li>
    <li>python39Packages.agate-excel</li>
    <li>python39Packages.cookiecutter</li>
    <li>python39Packages.kaggle</li>
    <li>python39Packages.mesa</li>
    <li>python39Packages.papis</li>
    <li>python39Packages.pyruckus</li>
    <li>python39Packages.python-slugify</li>
    <li>python39Packages.sphinx-material</li>
    <li>transifex-client</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
I have cherry-picked this change into my staging tree, thank you!

Also pinned to 4.0.1 in home-assistant v2021.7.0.

**Pull request closed without merging**
