### PR TITLE
lightdm: 1.26.0 -> 1.28.0

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
The same as #45817 but adds the missing description and adds a 'dev' output.
Closes #45817

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
87151912
87029760
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by worldofpeace** [comment]
cc @xeji

**Comment by jtojnar** [comment]
@GrahamcOfBorg test lightdm

**Comment by xeji** [comment]
LGTM.

**Comment by xeji** [comment]
The test isn't part of release.nix. I'm just running it locally right now.

**Comment by xeji** [comment]
Test looks fine. For the record:
@GrahamcOfBorg build lightdm

**Comment by worldofpeace** [comment]
:fireworks: :clap:

**Comment by xeji** [comment]
Thank you! Let's hope #30890 gets into 18.09...

**Pull request merged**
