### PR TITLE
vimPlugins.futhark-vim: init at 2021-08-24

### PR DESCRIPTION
**Pull request by Alexnortung**
###### Motivation for this change

futhark syntax highligting for vim https://github.com/BeneCollyridam/futhark-vim

I am not sure how to test vim plugins from nixpkgs, if anyone can test it or tell me how it can be tested it would be nice.

I added my package by using the update.py script.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by figsoda** [comment]
`vimPlugins.vim-clap` failed to build, can you update its `cargoSha256` in `overrides.nix`?
https://github.com/NixOS/nixpkgs/blob/2f73bd77ed034e1a565920a1d52fb585a6ec7aa2/pkgs/misc/vim-plugins/overrides.nix#L680

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 138265` at 1df22181 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/f599bb9e5b9d16014d243dd88d585f96">vimPlugins.vim-clap</a></li>
  </ul>
</details>
<details>
  <summary>4 packages built successfully:</summary>
  <ul>
    <li>spacevim</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`configurePhase` should probably contain `runHook preConfigure` and `runHook postConfigure`.

Near pkgs/misc/vim-plugins/build-vim-plugin.nix:30:14:
```
   |
30 |       inherit unpackPhase configurePhase buildPhase addonInfo preInstall postInstall;
   |              ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/misc/vim-plugins/build-vim-plugin.nix:30:14:
```
   |
30 |       inherit unpackPhase configurePhase buildPhase addonInfo preInstall postInstall;
   |              ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by teto** [comment]
you can check https://github.com/NixOS/nixpkgs/commit/22caffad3a2b32a0be38cd2a3a1e1953f3d153f0 or neovim/tests.nix to see some tests.

**Comment by figsoda** [comment]
Result of `nixpkgs-review pr 138265` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>86 packages built:</summary>
  <ul>
    <li>spacevim</li>
    <li>vimPlugins.Recover-vim</li>
    <li>vimPlugins.nerdtree (vimPlugins.The_NERD_tree)</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.aurora</li>
    <li>vimPlugins.bufferline-nvim</li>
    <li>vimPlugins.calendar (vimPlugins.calendar-vim)</li>
    <li>vimPlugins.caw (vimPlugins.caw-vim)</li>
    <li>vimPlugins.chadtree</li>
    <li>vimPlugins.cmp-conjure</li>
    <li>vimPlugins.cmp-nvim-lsp</li>
    <li>vimPlugins.cmp_luasnip</li>
    <li>vimPlugins.commentary (vimPlugins.vim-commentary)</li>
    <li>vimPlugins.compe-tabnine</li>
    <li>vimPlugins.crates-nvim</li>
    <li>vimPlugins.defx-nvim</li>
    <li>vimPlugins.deol-nvim</li>
    <li>vimPlugins.echodoc (vimPlugins.echodoc-vim)</li>
    <li>vimPlugins.editorconfig-nvim</li>
    <li>vimPlugins.feline-nvim</li>
    <li>vimPlugins.formatter-nvim</li>
    <li>vimPlugins.friendly-snippets</li>
    <li>vimPlugins.fugitive (vimPlugins.vim-fugitive)</li>
    <li>vimPlugins.fugitive-gitlab-vim</li>
    <li>vimPlugins.futhark-vim</li>
    <li>vimPlugins.fzf-lsp-nvim</li>
    <li>vimPlugins.fzf-vim</li>
    <li>vimPlugins.gitsigns-nvim</li>
    <li>vimPlugins.goto-preview</li>
    <li>vimPlugins.increment-activator</li>
    <li>vimPlugins.indent-blankline-nvim (vimPlugins.indent-blankline-nvim-lua)</li>
    <li>vimPlugins.lightline-bufferline</li>
    <li>vimPlugins.lightspeed-nvim</li>
    <li>vimPlugins.lir-nvim</li>
    <li>vimPlugins.lsp-status-nvim</li>
    <li>vimPlugins.lsp_signature-nvim</li>
    <li>vimPlugins.luasnip</li>
    <li>vimPlugins.ncm2-neosnippet</li>
    <li>vimPlugins.neoformat</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neomake</li>
    <li>vimPlugins.neosnippet (vimPlugins.neosnippet-vim)</li>
    <li>vimPlugins.neovim-ayu</li>
    <li>vimPlugins.nnn-vim</li>
    <li>vimPlugins.null-ls-nvim</li>
    <li>vimPlugins.nvim-autopairs</li>
    <li>vimPlugins.nvim-cmp</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-highlite</li>
    <li>vimPlugins.nvim-hlslens</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-nonicons</li>
    <li>vimPlugins.nvim-spectre</li>
    <li>vimPlugins.onedark-nvim</li>
    <li>vimPlugins.orgmode-nvim</li>
    <li>vimPlugins.packer-nvim</li>
    <li>vimPlugins.papercolor-theme</li>
    <li>vimPlugins.playground</li>
    <li>vimPlugins.plenary-nvim</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.rust-tools-nvim</li>
    <li>vimPlugins.symbols-outline-nvim</li>
    <li>vimPlugins.tabnine-vim</li>
    <li>vimPlugins.telescope-coc-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.toggleterm-nvim</li>
    <li>vimPlugins.vim-autoformat</li>
    <li>vimPlugins.vim-better-whitespace</li>
    <li>vimPlugins.vim-clap</li>
    <li>vimPlugins.vim-snippets</li>
    <li>vimPlugins.vim-test</li>
    <li>vimPlugins.vim-twiggy</li>
    <li>vimPlugins.vim-unimpaired</li>
    <li>vimPlugins.vim-vsnip</li>
    <li>vimPlugins.vim-vsnip-integ</li>
    <li>vimPlugins.vimspector</li>
    <li>vimPlugins.vimtex</li>
    <li>vimPlugins.wilder-nvim</li>
    <li>vimPlugins.zenburn</li>
  </ul>
</details>

**Review by figsoda — APPROVED** [review]

**Pull request merged**
