### PR TITLE
nextcloud27: 27.1.1 -> 27.1.2

### PR DESCRIPTION
**Pull request by f2k1de**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cafkafk** [comment]
Result of `nixpkgs-review pr 259348` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>nextcloud27</li>
  </ul>
</details>

**Review by cafkafk — APPROVED** [review]

**Comment by bachp** [comment]
Sucessfully deployed and it's working. But I get the following warning in the admin overview page:


> Your web server is not properly set up to resolve "/ocm-provider/". This is most likely related to a web server configuration that was not updated to deliver this folder directly. Please compare your configuration against the shipped rewrite rules in ".htaccess" for Apache or the provided one in the documentation for Nginx at it's [documentation page ↗](https://docs.nextcloud.com/server/27/go.php?to=admin-nginx). On Nginx those are typically the lines starting with "location ~" that need an update.

Maybe a change to the nginx config is necessary in the module

**Comment by SuperSandro2000** [comment]
could be this commit https://github.com/nextcloud/server/commit/6200c914a304be2ed91a9242112956b5c5724c2d

**Comment by bachp** [comment]
Looks like others are having the same issue https://github.com/nextcloud/server/issues/40803

**Comment by SuperSandro2000** [comment]
I think this doc change is relevant for us https://github.com/nextcloud/documentation/pull/11179/files

In fact removing the redirect fixed the admin message for me

**Comment by SuperSandro2000** [comment]
Please pick to fix the warning https://github.com/SuperSandro2000/nixpkgs/commit/a5624e484d61008ecdf75c0b7ce32037294b9641

**Comment by Ma27** [comment]
fwiw this patch can't be applied as-is since it'd break nextcloud26 (also 25, but that's almost EOL, so it doesn't count). I started fixing that, but it may take me a day until I can submit the patches :)

**Comment by wegank** [comment]
Superseded by #259967.

**Pull request closed without merging**
