### PR TITLE
pico-8: init at 0.1.12c

### PR DESCRIPTION
**Pull request by amaxine**
###### Motivation for this change
I wanted to get pico-8 running properly without needing e.g. steamrun.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by maxeaubrey** [comment]
Sorry, took me a while to figure out how to fix the `libudev` problems as they were unobvious... should be ok now!

**Review by endocrimes — APPROVED** [review]
Excited to not have to `steam-run` this any more :D

```
[nixpkgs(master)] $ cd ~/Downloads                                                                                                                                                                                                      
[Downloads] $ nix-prefetch-url file://$PWD/pico-8_0.1.12c_amd64.zip                                                                                                                                                                     
[8.1 MiB DL]                                                                                                                                                                                                                            
path is '/nix/store/v4f4f6fz30czl1p83gjbs2b5j96sq0jg-pico-8_0.1.12c_amd64.zip'                                                                                                                                                          
```

Result of `nixpkgs-review pr 84999` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>

  - pico-8
</details>

Screenshot of game running in a `nix-shell`:

![image](https://user-images.githubusercontent.com/1330683/79073116-04511880-7ce5-11ea-8b6f-61b249baf347.png)

**Comment by maxeaubrey** [comment]
Rebased and bumped version.

**Comment by rileyinman** [comment]
Is there a reason this was closed beyond the lack of response? I'm a fan of the idea.

**Comment by maxeaubrey** [comment]
@rileyinman Sorry, but yeah, that's pretty much it.

**Comment by rileyinman** [comment]
Unfortunately new package requests can take a bit to get merged, if you don't want to go through the trouble of keeping it up to date I'd be happy to do so based on the derivation you already created!

**Comment by maxeaubrey** [comment]
I'd be happy to remain maintainer and continue updating the package if it were merged.

The seeming impossibility of that (at least compared to getting open source packages or version bumps merged) has instead made me decide to only do so in my own repository for now. The alternative of leaving a PR open forever seemed undesirable to me, as I don't know what more can be done to get it merged at this point.

**Comment by rileyinman** [comment]
I believe that you can get help in the unofficial NixOS Discord server, they have a channel for reviewing pull requests to get them merged: https://discord.com/invite/RbvHtGa

**Pull request closed without merging**
