### PR TITLE
mercury: build on Darwin

### PR DESCRIPTION
**Pull request by jacereda**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vcunat** [comment]
@GrahamcOfBorg build mercury

**Comment by xeji** [comment]
timed out on darwin, let's try one more
@GrahamcOfBorg build mercury

**Comment by jacereda** [comment]
Mercury is quite big and the build takes a while. I'd say it took something like half an hour on my laptop.

**Comment by xeji** [comment]
Timed out again, so let's merge this and see if it builds on Hydra.

**Pull request merged**
