### PR TITLE
dockerTools.pullImage: use imageDigest

### PR DESCRIPTION
**Pull request by nlewo**
Docker provides the "image digest" which is an immutable image
identifier (unlike image name and tag).
It now has to be specified to pull an image.

Note Docker supports URI such as imageName:imageTag@imageDigest however
this is not yet supported by Skopeo:
"Docker references with both a tag and digest are currently not supported"

###### Motivation for this change
This improve reproducibility of docker pullling operations since it now use a immutable Docker image identifier. 

###### Things done
`nix-build ./ -A dockerTools.examples.nix && docker load -i result`

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by purefn** [comment]
This looks fantastic, thanks!

**Review by puffnfresh — APPROVED** [review]
Awesome! :fireworks:

**Review by fpletz — APPROVED** [review]

**Comment by aneeshusa** [comment]
Big fan of digests, so +1 from me. Can you also add a commit to remove the `pull.sh` script that got orphaned in #29302?

**Comment by globin** [comment]
+1 also cc @offlinehacker and @matejc

**Comment by nlewo** [comment]
@aneeshusa oups... commit pushed. Thanks!

**Comment by aneeshusa** [comment]
Thanks @nlweo! I just noticed that `pullImage` is also described in the docs (`docs/functions.xml`) - can you update it to mention that the digest is now required? Might also be a good idea to update the release notes with the same info.

**Comment by nlewo** [comment]
@aneeshusa done.

**Review by aneeshusa — APPROVED** [review]
Looking forward to using this, thanks!

**Review by domenkozar — APPROVED** [review]

**Comment by offlinehacker** [comment]
Nice, looks good, thanks :)

**Comment by nlewo** [comment]
Since dockerTools.pull implementation with Skopeo has been reverted from master, this PR is deprecated.
I have to rework on all of these PRs before resubmitting them. So,for now, I close this PR.

**Pull request closed without merging**
