### PR TITLE
rustc: 1.37.0 -> 1.38.0

### PR DESCRIPTION
**Pull request by edolstra**
###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by Mic92** [comment]
The `postPatch` phase needs an update on macOS: https://logs.nix.ci/?key=nixos/nixpkgs.69534&attempt_id=c1862a45-c16f-48d0-91e3-7b97d04d13b9

Since it does not look like we would get the test suite running again, how about removing all test-related patch commands in `postPatch`?

**Comment by LnL7** [comment]
It's been a few versions since I've tried to enable the tests again, but yeah we should remove the patches otherwise.

**Comment by basvandijk** [comment]
Removing the [offending line](https://github.com/NixOS/nixpkgs/blob/9c0968fd8103a32b05c72d8137e6d9e388a86a7e/pkgs/development/compilers/rust/rustc.nix#L147:L148) fixes the build for me on MacOS.

**Comment by Mic92** [comment]
I think this might have broke thunderbird: https://hydra.nixos.org/build/102506852/nixlog/1

**Comment by Mic92** [comment]
We should add rustc updates to staging in future again.

**Comment by Mic92** [comment]
fixed in https://github.com/NixOS/nixpkgs/pull/70229

**Pull request merged**
