### PR TITLE
notmuch: 0.28.4 -> 0.29

### PR DESCRIPTION
**Pull request by bsima**
###### Motivation for this change

I wanted to use notmuch 0.29

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @flokli @the-kenny

### CODE REVIEW

**Comment by FRidh** [comment]
Base version is approx. 0.28.4, not 0.28.2 as mentioned in the commit msg and PR msg.

**Comment by disassembler** [comment]
@GrahamcOfBorg build notmuch

**Comment by teto** [comment]
a link towards the changelog in commit message is appreciated: https://notmuchmail.org/news/release-0.29/

**Comment by bsima** [comment]
Fixed the commit message and added the changelog with a force push.

**Comment by flokli** [comment]
@bsima this does not seem to apply cleanly. Can you rebase on master?

**Comment by edef1c** [comment]
…well, that was a `git rebase --continue` forgotten after I fixed the conflict, and since the PR is closed that yields a permission denied now. Thanks, GitHub.

**Comment by bsima** [comment]
Looks like commit 21fac085c7f20eabaa5676a6b472cef14af9b436 beat me too
the version bump. So this can stay closed.

**Pull request closed without merging**
