### PR TITLE
freetds: 1.00.70 -> 1.00.80

### PR DESCRIPTION
**Pull request by ryantm**
Semi-automatic update. These checks were performed:

- built on NixOS
- found 1.00.80 with grep in /nix/store/ss0qlmmr3wx5xbwq3rzzydc0qh3swazw-freetds-1.00.80

cc "@peterhoeg"

### CODE REVIEW

**Comment by ryantm** [comment]
@GrahamcOfBorg build freetds

**Comment by grahamc** [comment]
@GrahamcOfBorg eval

I brought up too small of a machine

**Comment by adisbladis** [comment]
@grahamcofborg build php56Packages.apcu40 php56Packages.yaml13 php56Packages.pcs php56Packages.redis php56Packages.phpcs php56Packages.memcache php56Packages.yaml php56Packages.geoip php56Packages.phpcbf php56 php56Packages.redis22 php56Packages.imagick php56Packages.composer lispPackages.pgloader php56Packages.xdebug php56Packages.box php56Packages.igbinary sqsh freetds php56Packages.couchbase php56Packages.apcu lispPackages.mssql php56Packages.memcached php56Packages.xcache php56Packages.spidermonkey php56Packages.php-parallel-lint php56Packages.zmq php56Packages.memcached22 php56Packages.xdebug23 python27Packages.python-sybase php56Packages.php-cs-fixer

**Comment by xeji** [comment]
already bumped on master

**Pull request closed without merging**
