### PR TITLE
home-assistant-custom-components.awtrix: init at unstable-2024-05-26

### PR DESCRIPTION
**Pull request by pinpox**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by mweinelt** [comment]
How did you build test this package?

**Comment by pinpox** [comment]
> How did you build test this package?

I tested the build with:
```
nix-build -A home-assistant-custom-components.awtrix   
```

And tested the functionality by  adding this to my own home-assistant config:
```nix
    services.home-assistant = {
      enable = true;

      customComponents =
        let
          awtrix = pkgs.buildHomeAssistantComponent
            rec {
              owner = "10der";
              domain = "awtrix";
              version = "unstable-2024-05-26";

              src = pkgs.fetchFromGitHub {
                inherit owner;
                repo = "homeassistant-custom_components-awtrix";
                rev = "329d8eec28478574b9f34778f96b5768f30be2ab";
                hash = "sha256-ucSaQWMS6ZwXHnw5Ct/STxpl1JjBRua3edrLvBAsdyw=";
              };

              propagatedBuildInputs = [
                pkgs.home-assistant.python.pkgs.requests
              ];

              meta = with lib; {
                description = "Home-assistant integration for awtrix";
                homepage = "https://github.com/10der/homeassistant-custom_components-awtrix";
                maintainers = with maintainers; [ pinpox ];
                license = licenses.mit;
              };
            };

        in

        with pkgs.home-assistant-custom-components;
        [
          awtrix
        ];
        #...
 }

```

**Comment by pinpox** [comment]
> Then `home-assistant-custom-components.awtrix` should be attribute mentioned in the commit message.

fixed.

**Comment by mweinelt** [comment]
@ofborg build home-assistant-custom-components.awtrix

**Pull request merged**
