### PR TITLE
Shared libuv in io.js and Node.js

### PR DESCRIPTION
**Pull request by valeriangalliat**
**Fair warning:** I have currently very little experience with Nix. I have ngo idea what I'm doing.

---

Following #6234, I'm trying to build Node.js and io.js with a shared libuv instead of the one statically included in the source.

I could build both `iojs` and `nodejs` on NixOS with these updated expressions. I also successfully built `iojsPackages.npm` and `nodePackages.npm` and they seem to work properly.

I currently have a `nox-review wip` build running, however I believe it will fail like #6234 since (at least) the `stream-splitter-transform` package is currently broken.

### CODE REVIEW

**Comment by valeriangalliat** [comment]
Travis build was apparently killed; on my side, `nox-review wip` failed because the disk is full (I'm building inside a 8 GiB VM)… it was trying to build Haskell packages, which I don't really understand (maybe because of the new libuv version?).

**Comment by valeriangalliat** [comment]
I removed the `[WIP]` flag from the title, it's not exactly WIP, it's more "need review, opinions / help wanted".

**Comment by Havvy** [comment]
It looks to me like the build was killed (and thus failed) because the output went over 10,000 lines.

**Comment by lethalman** [comment]
Ok let's merge this, thanks. Will revert in case there's any regression with node.

Please note that iojs packages are prefixed with `node-` instead of `iojs-`. That should be changed.

**Comment by valeriangalliat** [comment]
> Please note that iojs packages are prefixed with node- instead of iojs-. That should be changed.

Indeed, I'll take care of this.

**Comment by valeriangalliat** [comment]
@lethalman any idea what to do with `bin-` prefix for Node packages that also have binaries? Node packages and io.js packages will still conflict for this… maybe `bin-node-*` and `bin-iojs-*` (or even drop the `bin-` in the case we always prefix with `node` or `iojs`)?

**Comment by lethalman** [comment]
Yes bin-iojs is fine. Don't drop the bin prefix.

**Pull request merged**
