### PR TITLE
vector: disable flaky test

### PR DESCRIPTION
**Pull request by happysalada**
###### Motivation for this change

just had this test fail upon upgrading today, not really sure why.
The failure is not super clear, here is the error message
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: ErrorCode(1), cause:
 Some(Ssl(ErrorStack([Error { code: 337047686, library: "SSL routines", function: "tls_process_server_cert
ificate", reason: "certificate verify failed", file: "ssl/statem/statem_clnt.c", line: 1914 }]))) }', src/
test_util/mod.rs:165:43
```

maybe it's related to the openssl upgrade that we did ? (not sure I have to say).
I'm guessing the failure is on hydra as well, otherwise my machine wouldn't have tried to rebuild it. There might be a chance that the binary cache isn't caught up with the recent changes yet.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
Since vector is broken on master without this, I'm going to go ahead and merge this.
I'm happy to revisit this decision later at any time.

**Comment by ius** [comment]
The build on 21.05 is [failing](https://hydra.nixos.org/job/nixos/release-21.05/nixpkgs.vector.x86_64-linux/all) as well. Might want to backport this?

**Comment by happysalada** [comment]
I'm happy to, however, will you be able to test?

**Comment by ius** [comment]
Afraid not - it failed to build on my own machine due to insufficient memory, as I just wanted to evaluate *vector* I decided to move on for now instead.

That said, some more Googling reveals the root cause - it's an expired self-signed certificate in their test suite which expired on september 3rd: https://github.com/vectordotdev/vector/pull/9053.

**Comment by happysalada** [comment]
Thank you for finding the that. I can just remove the skip on this test in the next release.
I'll try to backport if I can find somebody running on 21.05.

**Pull request merged**
