### PR TITLE
pipelight: Add support for 32 bit linux via #9000

### PR DESCRIPTION
**Pull request by cillianderoiste**
This is an update to #9000 (sorry for the extra PR, I don't know if there's a cleaner way to suggest changes via github). I've removed some inputs which don't seem to be used, passed in stdenv_32bit via all-packages.nix and tried to test it a bit. It seems to do something (a window pops up when I start firefox after enabling e.g. widevine). But examples I found didn't seem to work:
- http://www.iis.net/media/experiencesmoothstreaming1080p
- http://pipelight.net/cms/plugin-widevine.html

The patch also seems to be outdated e.g. 

```
$ pipelight-plugin --system-check
/home/goibhniu/.nix-profile/bin/pipelight-plugin: line 424: /usr/bin/id: No such file or directory
```

any ideas @jraygauthier, @nathanielbaxter?

### CODE REVIEW

**Comment by jraygauthier** [comment]
@cillianderoiste: Hi again. I'm not sure it can help, but here are the notes I took for myself that
allowed use of pipelight on my side:

-  Install the "User Agent Overrider" firefox extension.
-  From a user shell: `pipelight-plugin --enable silverlight5.1`.
-  So that the plugin is recognized, you need to flush the firefox
  plugin cache.
-  Type `about:support` in the browser url bar.
-  Open the *profile directory* by clicking on the *Open Directory*
  button.
-  Close the browser.
-  Manually delete the `pluginreg.dat` file you will find there.
-  Restart the browser.
-  When the time comes to use Silverlight (e.g.: watching a netflix movie),
  select the `Windows / Firefox 29` agent.

**Comment by cillianderoiste** [comment]
Thanks @jraygauthier for the instructions. I'm afraid I still don't see any new plugins in about:plugins (should I?). I've tried manually setting my MOZ_PLUGIN_PATH to point to ~/.mozilla/plugins (I can see libpipelight-silverlight5.1.so there). Also the two demo pages don't work. Can you think of anything else I can try, or could you test this out yourself and let me know if it works for you?

**Comment by jraygauthier** [comment]
If you followed the instructions about deleting the plugin registration cache your should see your
plugin in the `about:plugins` listing. Mine is:

*Silverlight Plug-In* and refers to: `Path: /nix/store/jpqpwc7nnwpwbsa3w6wpiazwdlzrnz4y-pipelight-0.2.8/lib/pipelight/libpipelight-silverlight5.1.so`.

I'm a bit outdated on my 32 bit computer. I should upgrade soon. I will definitely try this out after
the upgrade.

**Comment by cillianderoiste** [comment]
FWIW I can't get this to work with the current pipelight in nixpkgs either. It would be great if you can test it, if it works for you I'm happy to merge. You could use a patch on the revision of nixpkgs that your current system uses, if you don't want to upgrade.

**Comment by jraygauthier** [comment]
I built it on my 64 bits machine. Still work well here.

Maybe you need to start anew?:

In order to start anew (remove all pipelight plugins and pipelight data):
 -  Open the *profile directory* by clicking on the *Open Directory*
    button.
 -  Close the browser.
 -  Manually delete the `pluginreg.dat` file you will find there.
 -  `rm ~/.mozilla/plugins/libpipelight-*`
 -  `rm -r ~/.cache/pipelight`
 -  `rm -r ~/.wine-pipelight`

After these steps, my previous version of the silverlight plugin was no longer detected.

Afterward I perform the steps I previously listed.

I however noticed that the `~/.wine-pipelight` gets created on first firefox lauch and that the
silverlight plugin is not detected at this point. In order to make it work, I restart firefox
a second time and now see the plugin.

**Comment by cillianderoiste** [comment]
Thanks @jraygauthier, it still doesn't work for me. Actually, Firefox crashes after following these steps, but if it works for you that's fine.

**Comment by jraygauthier** [comment]
My pleasure and thank you as well for the merge. Sorry to hear that it breaks on your side.

**Pull request merged**
