### PR TITLE
rtv: remove

### PR DESCRIPTION
**Pull request by Br1ght0ne**
###### Motivation for this change
See #75817.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @matthiasbeyer

---
This change is [Reviewable](https://reviewable.io/reviews/nixos/nixpkgs/75821)

### CODE REVIEW

**Review by matthiasbeyer — CHANGES_REQUESTED** [review]
I do not approve.

rtv is still working. We should not remove it. IMO, we should just mark it as deprecated somehow (again: Is there a process for deprecating a package?).

**Comment by filalex77** [comment]
> is there a process for deprecating a package?

Not that I know of, sadly.

**Comment by matthiasbeyer** [comment]
Well, yeah, seems like there is no way. It seems that adding "(deprecated)" to the description of the package would be the first step.

We should definitively not just remove the package, as this might break nixos updates for people. I'd rather set the description to "(deprecated)" and, in the next release (nixos-20.03) remove rtv, but not like in the middle of the nixos year.

Maybe I would even schedule the removal for 20.09 rather than 20.03, because rtv still works afaik.

**Comment by wedens** [comment]
I agree with @matthiasbeyer that we should keep rtv while it works.

**Comment by Ma27** [comment]
> Not that I know of, sadly.

IIRC we basically throw an error (as you did) and add a note in the release-notes for the upcoming release.

**Comment by aanderse** [comment]
@filalex77 now that https://github.com/NixOS/nixpkgs/pull/75817 is merged can you please update this PR to mention `tuir` and then we can merge? @Ma27 - sound good to you?

**Comment by matthiasbeyer** [comment]
Should still be removed

**Comment by bobby285271** [comment]
#133085 already removed.

**Pull request closed without merging**
