### PR TITLE
firefox, firefox-bin: 72.0.2 -> 73.0 [WIP]

### PR DESCRIPTION
**Pull request by tokudan**
###### Motivation for this change

Backport to stable due to security fixes.
Security advisory: https://www.mozilla.org/en-US/security/advisories/mfsa2020-05/

Included commits:
1c0b278 a085e9c 6da3b5e 48603cd 9f07ede 82d9ce4 187d691 8019df9 1192073 f43fdd1 d6b7a99 7a625e7

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tokudan** [comment]
@GrahamcOfBorg test firefox
@GrahamcOfBorg build firefox firefox-bin

**Comment by tokudan** [comment]
@GrahamcOfBorg test firefox
@GrahamcOfBorg build firefox firefox-bin

**Comment by andir** [comment]
I've been avoiding to do the global NSS (sqlite, nspr, …) bumps on stable branches. I am not sure we want to start with this so late in the release cycle.

**Comment by andir** [comment]
Also while trying to build nss on this branch I get:
```
ix_pl_nss/module/Linux5.4_x86_64_gcc_glibc_PTH_64_OPT.OBJ/pkix_pl_nsscontext.o ../libpkix/pkix_pl_nss/module/Linux5.4_x86_64_gcc_glibc_PTH_64_OPT.OBJ/pkix_pl_pk11certstore.o ../libpkix/pkix_pl_nss/module/Linux5.4_x86_64_gcc_glibc_PTH_64_OPT.OBJ/pkix_pl_socket.o   -L/nix/store/hl2hlln6k9gh24kxp9a4kvvx635gfkcj-nss-3.49.2/Linux5.4_x86_64_gcc_glibc_PTH_64_OPT.OBJ/lib -L/nix/store/hl2hlln6k9gh24kxp9a4kvvx635gfkcj-nss-3.49.2/Linux5.4_x86_64_gcc_glibc_PTH_64_OPT.OBJ/lib -lnssutil3 -L/nix/store/3i0v28jxrzwh5h5zndf6ginvsscj4m07-nspr-4.21/lib -lplc4 -lplds4 -lnspr4  -lpthread  -ldl -lc
/nix/store/ajrrkivdfvp8dp4vdg5hp1h5hblmanc9-binutils-2.31.1/bin/ld: ../certdb/Linux5.4_x86_64_gcc_glibc_PTH_64_OPT.OBJ/certdb.o: in function `CERT_UnlockCertTrust':
certdb.c:(.text.CERT_UnlockCertTrust+0x1f): undefined reference to `PR_ASSERT_ARG'
/nix/store/ajrrkivdfvp8dp4vdg5hp1h5hblmanc9-binutils-2.31.1/bin/ld: ../certdb/Linux5.4_x86_64_gcc_glibc_PTH_64_OPT.OBJ/certdb.o: in function `CERT_UnlockCertTempPerm':
certdb.c:(.text.CERT_UnlockCertTempPerm+0x1f): undefined reference to `PR_ASSERT_ARG'
collect2: error: ld returned 1 exit status
make[2]: *** [../../coreconf/rules.mk:291: Linux5.4_x86_64_gcc_glibc_PTH_64_OPT.OBJ/libnss3.so] Error 1
```

@GrahamcOfBorg build nss

**Comment by andir** [comment]
@tokudan thanks for the effort. I went with the other PR instead as that had less impact and did not show the compiler error seen here.

**Pull request closed without merging**
