### PR TITLE
goredo: 1.31.0 -> 2.4.0

### PR DESCRIPTION
**Pull request by spacefrogg**
### Major changes

- Improve speed of dependency calculation by orders of magnitude
- New format of dependency records from GNU recfile (text) to binary
- When called in a .do file, redo-if* commands treat all arguments as targets.

[Changelog](http://www.goredo.cypherpunks.ru/News.html#Release-2_005f0_005f0)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by spacefrogg** [comment]
Updated to 2.1.0

**Comment by spacefrogg** [comment]
Updated to 2.2.0

**Comment by spacefrogg** [comment]
Update to 2.3.0

**Comment by spacefrogg** [comment]
Updated to 2.4.0.

**Comment by fabianhjr** [comment]
Hi, will gladly help with review.

I would also suggest posting the PR to https://discourse.nixos.org/t/prs-ready-for-review/3032/ and to https://app.element.io/#/room/#dev:nixos.org

**Comment by fabianhjr** [comment]
Result of `nixpkgs-review pr 259824` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>goredo</li>
    <li>goredo.info</li>
  </ul>
</details>

**Review by fabianhjr — APPROVED** [review]
diff lgtm

**Comment by fabianhjr** [comment]
Removing backport due to 2 reasons:

- Major updates shouldn't be backported
- 23.05 is about to reach EOL and 23.11 has just been cut.

**Pull request merged**
