### PR TITLE
abseil-cpp: 202301 -> 202401

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Change the default version of `abseil-cpp` to the latest one (202401).

Changelog: https://github.com/abseil/abseil-cpp/releases/tag/20240116.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
rebased to try to fix the github actions

**Comment by SuperSandro2000** [comment]
Successfull build ``nix build .#telegram-desktop .#libreoffice .#grpc .#protobuf .#bloaty``

**Comment by GaetanLepage** [comment]
Anymore builds to test before merging ?
I can run some on my hardware if needed.

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by vcunat** [comment]
So, I believe this PR caused this regression:
https://hydra.nixos.org/build/248411515/nixlog/1/tail

Currently in PR #285983

**Comment by GaetanLepage** [comment]
> So, I believe this PR caused this regression: https://hydra.nixos.org/build/248411515/nixlog/1/tail
> 
> Currently in PR #285983

Would bumping `grpc` help ?

**Comment by vcunat** [comment]
(I don't know.)

**Comment by vcunat** [comment]
Apparently updating does not help:
https://github.com/NixOS/nixpkgs/pull/285921/checks?check_run_id=21288775543

**Comment by GaetanLepage** [comment]
> Apparently updating does not help:

Ok, thank you for trying.
I wonder why this break specifically on darwin and not on linux...
Hint: https://github.com/grpc/grpc/pull/34663

**Comment by vcunat** [comment]
GitHub says that the linked change was included in the current grpc version already (1.60.0).

**Comment by vcunat** [comment]
Resolved by PR https://github.com/NixOS/nixpkgs/pull/287548

**Pull request merged**
