### PR TITLE
alacritty: 0.13.0 -> 0.13.1

### PR DESCRIPTION
**Pull request by ncfavier**
https://github.com/alacritty/alacritty/releases/tag/v0.13.1

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by r-vdp — APPROVED** [review]
LGTM!

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 279625` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>wio</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>alacritty</li>
    <li>alacritty.terminfo</li>
  </ul>
</details>

**Comment by happysalada** [comment]
the error is 

```
= note: Undefined symbols for architecture x86_64:
alacritty>             "_NSPasteboardTypeFileURL", referenced from:
alacritty>                 objc::rc::autorelease::autoreleasepool::ha8ebbee24d12f407 in alacritty-b347e2f7b8586748.copypasta-391a6e9e8e7011eb.copypasta.13839ede92835bb1-cgu.0.rcgu.o.rcgu.o
alacritty>           ld: symbol(s) not found for architecture x86_64
alacritty>           clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
alacritty>
alacritty>
```
this is rather unexpected on a minor version upgrade. It might be just a matter of updating an sdk version or something. I'll make more tests, but just wanted to post this here first in case someone else already has seen this.

**Comment by happysalada** [comment]
tagging @NixOS/darwin-maintainers just in case they know a trick here (let me know if this is too much noise, I'm happy to not use that tag again for a problem, I just thought the fix might be obvious to someone in the darwin maintainers).

**Comment by amaxine** [comment]
@happysalada I'd assume the failure predates this bump as #279778 describes the same issue on 0.13

**Comment by happysalada** [comment]
@amaxine thank you for the clarification!

the fix should be in https://github.com/NixOS/nixpkgs/pull/279907

**Pull request merged**
