### PR TITLE
pkgsStatic fix for macOS

### PR DESCRIPTION
**Pull request by matthewbauer**
###### Motivation for this change

Two things done:

- don't let cctools use clang backend for as (builtin one works here)
- use buildPackages for bootstrap_cmds in all-packages.nix

### CODE REVIEW

**Review by Ericson2314 — APPROVED** [review]
Does the internal assembler change work for ARM/`iOS`?

**Comment by matthewbauer** [comment]
Maybe not. The cctools as may only support arm32:

https://github.com/tpoechtrager/cctools-port/blob/f53c6186393915ba9bff287f18769f9e14ec02e6/cctools/as/driver.c#L257-L283

We can make this flag conditional on !stdenv.targetPlatform.isAarch64.

**Comment by matthewbauer** [comment]
@GrahamcOfBorg build pkgsStatic.hello pkgsStatic.file

**Comment by matthewbauer** [comment]
But we use prebuilt iOS for that right now correct?

**Comment by Ericson2314** [comment]
No we build cctools for iOS. It's already broken because you removed the old cctools though. (We'll have to upstream the TAPI stuff or just swap LLVM sources for Apple's LLVM fork for that.)

**Comment by Ericson2314** [comment]
Also from those comments, it seems that the internal assembler still requires llvm the library, even if it doesn't require clang? I'm not sure removing that dependency is correct.

**Pull request merged**
