### PR TITLE
Expose minimum required Nix version (2)

### PR DESCRIPTION
**Pull request by ebzzry**

### CODE REVIEW

**Comment by spwhitt** [comment]
In the future you can modify a pull request in place with `git rebase -i` and `git push -f`

**Comment by ebzzry** [comment]
@spwhitt Yes. My reason however was to leave the other one for examination. If rebasing is indeed a better option, then I'll do that in the future.

**Comment by domenkozar** [comment]
Let's move it to `lib/minver.nix` and add a comment why this file exists.

**Comment by ebzzry** [comment]
Ok. I just pushed the updates.

**Comment by domenkozar** [comment]
cc @edolstra this looks better right?

**Pull request merged**
