### PR TITLE
perlXMLParser -> perlPackages.XMLParser

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

Remove top-level ```perlXMLParser``` as a rudiment from the epoch of a single Perl version across nixpkgs

```perlXMLParser = perlPackages.XMLParser``` moved from ```all-packages.nix``` to ```aliases.nix```

### CODE REVIEW

**Comment by volth** [comment]
it seems that mass-rebuild is causes only by removal of trailing space inside string literals

**Comment by xeji** [comment]
> it seems that mass-rebuild is causes only by removal of trailing space inside string literals

I looked through the changes and still don't understand the mass rebuild. You only change string literals in `wxcam` and `gnumeric`, and neither should cause a mass rebuild. So I wonder if we're overlooking a bug here...

**Comment by xeji** [comment]
Let's ask ofborg again
@GrahamcOfBorg eval

**Comment by xeji** [comment]
I did a little experiment with `intltool`. Actually the derivation hash changes although the resulting `propagatedBuildInputs` are exactly as before. Probably because the arguments to the derivation are different. So the mass rebuild seems to be a caused by the way nix computes derivation hashes.

**Comment by xeji** [comment]
let's build some of these to check
@GrahamcOfBorg build intltool rarian avahi libgksu

**Pull request merged**
