### PR TITLE
Update Haskell package set to Stackage Nightly (plus other fixes)

### PR DESCRIPTION
**Pull request by peti**
This PR is test-built by Hydra at https://hydra.nixos.org/jobset/nixpkgs/haskell-updates. I'll fix up the remaining errors and merge it on Friday, 2020-11-20 20:00 +01:00. You can watch this live on Twitch at https://www.twitch.tv/peti343. In addition to the chat features offered by Twitch, there is also a voice conference at https://discord.gg/YTEa3XR that viewers can use to chat with me and with each other.

### CODE REVIEW

**Comment by cdepillabout** [comment]
@peti Why did you decide to update the package set to Nightly (instead of an LTS)?

Also, when LTS-17 comes out, are you planning on switching back to track it?

**Comment by peti** [comment]
The discussion took place at http://www.twitch.tv/peti343/v/801715350?sr=a&t=3625s.

We felt that Nightly is better for us in general. Release branches could follow some LTS set, of course, but we actually don't update the package set in release branches, so I guess it doesn't make any practical difference.

**Comment by cdepillabout** [comment]
@peti Thanks for the link to the conversation.

I think agree with most of the points brought up.  It sounds like Nightly might actually be a better fit for nixpkgs, since we also provide many packages on Hackage but not in Stackage.  Packages from Hackage are sometimes hard to get working with the slightly older stuff from Stackage.

One concern I have is how often Nightly drops "important" packages.  I remember from about a year or so ago I was quite surprised when Nightly dropped Servant, which has quite a few dependencies in Stackage.  However, I don't actually have any idea how frequent or widespread this kind of breakage is.  Servant is somewhat of a fringe package (even though it has a lot of dependencies), but I wonder what the story is for the more "core" packages, like `lens`, `aeson`, `conduit`, etc.

**Comment by maralorn** [comment]
Okay, I got this down to zero eval errors.

We are now at 5933 building packages, down from 6044 before the switch to stackage nightly. This is not so bad.

Sadly right now some of the most important packages are still broken. e.g. cabal-install, stack, hls, git-annex, neuron …

So, still a lot to do.

**Comment by maralorn** [comment]
I will just very informally document here, what packages are still on my list to be fixed:

- [ ] cabal-install
- [ ] hls
- [ ] stack
- [ ] neuron
- [ ] stan
- [ ] git-annex

Of course, I don‘t know if I can fix them all.

**Comment by cdepillabout** [comment]
@srid 

neuron isn't building because the following packages are broken on this branch:

- `reflex`
- `aeson-gadt-th`
- `rib-core`
- `dependent-sum-aeson-orphans`

**Comment by cdepillabout** [comment]
I've fixed Spago in https://github.com/NixOS/nixpkgs/pull/104164.

**Comment by maralorn** [comment]
> @srid
> 
> neuron isn't building because the following packages are broken on this branch:
> 
>     * `reflex`
> 
>     * `aeson-gadt-th`
> 
>     * `rib-core`
> 
>     * `dependent-sum-aeson-orphans`

I have fixed all of them locally. But most of them with simple dontCheck and doJailbreak, so I want to clean that up and make a pretty PR with patches or at least issues out of it.

**Comment by maralorn** [comment]
I have fixed all neuron deps other than neuron itself. It fails with this error message: https://github.com/srid/neuron/issues/475

**Comment by cdepillabout** [comment]
@maralorn The fix in 80d6b9af0fab1c for `pcg-random` was all that was needed to get `password` building.  I'll check it off on your list above.

**Comment by expipiplus1** [comment]
`streamly-0.7.2` doesn't compile with `primitive-0.7.1` (even after jailbreak) (hence `pkgs.nix-linter` is broken)

**Comment by maralorn** [comment]
As soon as we merge master into haskell-updates (or the other way around). hls will break. :-( 

https://github.com/NixOS/nixpkgs/issues/104275

**Comment by maralorn** [comment]
That has been fixed. \o/

I think it's a bit late now to merge master in, if we did that now, we won‘t have reasonable hydra infos tomorrow.

I wish we had a way for hydra to tell us which jobs fail now which built successfully last week. So we could have a look at which of them should also be fixed …

**Comment by maralorn** [comment]
@peti You obviously didn‘t read what I said or decided to disagree. :laughing:

**Comment by peti** [comment]
I don't see an alternative. We have to merge `master` in, no? What else could we do?

**Comment by domenkozar** [comment]
I've only gotten the notification that decision was made to switch to nightly. Can I get like a week before this is merged? Otherwise cachix will be broken and I literally had no time to prepare without knowing about the decision.

**Comment by turboMaCk** [comment]
how about this quickfix:

```
# in all-packages.nix
  cachix = haskell.lib.justStaticExecutables haskell.packages.ghc883.cachix;
```

this builds for me and might be good enough perhaps?

**Comment by peti** [comment]
@domenkozar, there are plenty of ways to fix `cachix` quickly. One has been pointed out by @turboMaCk. Another option might be to use `overrideScope` to re-create the environment (set of versions of its dependencies) in which it builds successfully. I don't know. It doesn't feel like a big deal if `cachix` is broken for a few hours or even days on the unstable development branch. I'd rather not abort all our efforts here to avoid a problem that doesn't feel particularly major to be honest.

**Comment by domenkozar** [comment]
@peti you're a true gentlement :D

**Comment by maralorn** [comment]
For what it's worth. It is really annoying that we don‘t have notifications for failed hydra builds. We should have an automated way to notify devs about pending broken merges as early as possible.

**Comment by peti** [comment]
We'll merge https://github.com/NixOS/nixpkgs/pull/104424 next week.

**Comment by domenkozar** [comment]
@maralorn we have release blockers, but it doesn't help if someone removes your package from it 20min before merging the PR...

**Comment by domenkozar** [comment]
And disabling servant means disabling A LOT of packages.

**Comment by expipiplus1** [comment]
> For what it's worth. It is really annoying that we don‘t have notifications for failed hydra builds. We should have an automated way to notify devs about pending broken merges as early as possible.
> 
> Our current workflow is lacking in that regard and we will need to improve on that.

Can you open an issue for this? (It's also been discussed elsewhere, for instance the static pkgs maintainer issue)

**Pull request merged**
