### PR TITLE
Various VSCode / VSCodium extension additions

### PR DESCRIPTION
**Pull request by yoav-lavi**
## Description of changes

- vscode-extensions.emroussel.atomize-atom-one-dark-theme: init at 2.0.2
- vscode-extensions.wmaurer.change-case: init at 1.0.0
- vscode-extensions.bierner.docs-view: init at 0.0.11
- vscode-extensions.unifiedjs.vscode-mdx: init at 1.4.0
- vscode-extensions.enkia.tokyo-night: init at 1.0.0
- vscode-extensions.dotenv.dotenv-vscode: init at 0.28.0

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Janik-Haag** [comment]
Result of `nixpkgs-review pr 246196` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>vscode-extensions.bierner.docs-view</li>
    <li>vscode-extensions.dotenv.dotenv-vscode</li>
    <li>vscode-extensions.emroussel.atomize-atom-one-dark-theme</li>
    <li>vscode-extensions.enkia.tokyo-night</li>
    <li>vscode-extensions.unifiedjs.vscode-mdx</li>
    <li>vscode-extensions.wmaurer.change-case</li>
  </ul>
</details>

**Review by Janik-Haag — COMMENTED** [review]
The commits should all be named `vscode-extensions.$extension: init at $version` other wise this looks good to me but I don't use vscode so I'm probably not the correct person to review this :see_no_evil:

**Review by drupol — CHANGES_REQUESTED** [review]
Hi!

Thanks for your contribution.

Please add a `meta.description` to each extension, take some inspiration from existing extension.

Thanks!

**Comment by yoav-lavi** [comment]
@Janik-Haag fixed, thanks!

**Comment by yoav-lavi** [comment]
@drupol done, added changelings and homepages etc. as well

**Review by drupol — APPROVED** [review]
I definitely agree now, thanks for implementing the requested changes!

**Review by drupol — APPROVED** [review]

**Comment by drupol** [comment]
Let me know when you're ready to merge.

**Comment by yoav-lavi** [comment]
@drupol I am now, sorry, had to fix that one uppercase T in "Theme" haha

**Comment by drupol** [comment]
Right, I'm waiting for the ci to pass and merging this. Thanks!

**Comment by yoav-lavi** [comment]
@drupol @Janik-Haag Thanks for the review!

**Pull request merged**
