### PR TITLE
lilv: add meson options to include Nix and NixOS specific paths for the default lv2 plugin search

### PR DESCRIPTION
**Pull request by datMaffin**
Currently applications that use lilv will miss LV2 plugins installed in Nix and NixOS.

The lilv meson build already exposes options that can be filled.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by jopejoe1 — CHANGES_REQUESTED** [review]
This needs to go through staging, but otherwise this looks good to me.

**Comment by datMaffin** [comment]
> This needs to go through staging, but otherwise this looks good to me.

Thanks for looking into this PR!

Do I need to do anything?

running `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"` is not practical on a private machine, its way too much that wants to be build.

I also tested this with ardour 8.8 (which is now already merged), and it did work as expected.

**Comment by jopejoe1** [comment]
> Ok, I think with staging you mean the staging-next branch

I mean the https://github.com/NixOS/nixpkgs/tree/staging not the https://github.com/NixOS/nixpkgs/tree/staging-next branch, you can follow the guide at https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging to rebase the pr.

> running nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD" is not practical on a private machine, its way too much that wants to be build.

Just testing some important reverse decencies should be enough.

**Review by jopejoe1 — APPROVED** [review]

**Comment by datMaffin** [comment]
@jopejoe1 thanks!

**Pull request merged**
