### PR TITLE
tinc: enable chroot

### PR DESCRIPTION
**Pull request by tg-x**

### CODE REVIEW

**Comment by wkennington** [comment]
Lgtm

**Comment by tg-x** [comment]
Only problem this could cause is with running scripts. From the [documentation](http://tinc-vpn.org/documentation/Runtime-options.html):
> Note that tinc can’t run scripts anymore (such as tinc-down or host-up), unless it’s setup to be runnable inside chroot environment.

It would be possibly better to add an option to disable chroot, if any scripts require it (which can be added through environment.etc)

**Comment by fadenb** [comment]
> It would be possibly better to add an option to disable chroot, if any scripts require it (which can be added through environment.etc)

+1. I would very much like an option to disable the chroot to ensure compatibility with existing setups (so setting chroot to false is enough to keep an existing setup working)

**Comment by tg-x** [comment]
OK, added the option

**Comment by fadenb** [comment]
lgtm :)

**Pull request merged**
