### PR TITLE
some `recurseIntoAttrs` hackery

### PR DESCRIPTION
**Pull request by oxij**
###### What?

Apply this, put `{ recurseIntoAttrs = [ "all" ]; }` into your `config.nix`, do `nix-env -qa`/`nix search`, see _all_ the packages (or, alternatively, consume all the memory and crash).

###### Motivation for this change

1) I wanted to have a nice way to force `nix-env -qa` to list _all_ the packages for measurements and to toggle that feature on and off for package subsets.
2) I wanted metrics.nix to count packages.

I started making it specifically for https://github.com/NixOS/nixpkgs/issues/38635#issuecomment-414062763, but, I think, it turned out to be generally useful by itself.

I made `dontRecurseIntoAttrs` as a joke to guide myself via search, but now kinda like it too.

###### Things done

- [X] It's a noop.

### CODE REVIEW

**Comment by vcunat** [comment]
This can be also approached as a wrapper without touching nixpkgs, though perhaps with a little worse performance &ndash; a function that imports nixpkgs and recursively adds the attribute everywhere (all is lazy, of course).  Something similar is done in `./maintainers/scripts/rebuild-amount.sh` but the aim is different there.

**Comment by edolstra** [comment]
Also `recurseIntoAttrs` is an ugly name. Something like `enableAllPackages` would be more descriptive.

**Comment by oxij** [comment]
@vcunat @edolstra regardless of the `recurseIntoAttrs` hackery, what about the new metric? Would you merge that if I split in into a separate PR?

The problem with https://github.com/NixOS/nixpkgs/issues/38635#issuecomment-414062763 is that hydra metrics graphs like memory consumption and etc don't make too much sense without knowing the number of packages it tried to evaluate.

**Comment by oxij** [comment]
ping. The metric thing was merged in #49863. What can be done to have the rest merged? Is the config option name the only problem here?

This is pretty useful for measuring massive changes like #50643.

**Comment by oxij** [comment]
The last commit was merged as #49863. The first commit now has a separate PR #56105.

**Comment by danbst** [comment]
should this be rebased or closed now?

**Comment by oxij** [comment]
Most of this was merged via other PRs but the main thing was not and I kinda hope to hear some input on option names, semantics and such.

**Comment by danbst** [comment]
My opinion on naming:
- `recurseIntoAttrs` should be called `hydraPackageSet :: Attrset -> Attrset`
- `dontRecurseIntoAttrs` should be called `packageSet :: String -> Attrset -> Attrset`
- `recurseIntoAttrsMaybe` should be called `packageSet`. Can you provide an insight on why some are "dont", and others are "maybe"? Is "all" your personal choice of "interesting" attrsets?

Also, a minor nitpick, I can suggest the following refactor to propagate package set name automatically:
```
inherit (lib.mapAttrs packageSet {
  nodePackages_10_x = callPackage ../development/node-packages/default-v10.nix { };
  nodePackages_8_x = callPackage ../development/node-packages/default-v8.nix { };
  nodePackages = nodePackages_8_x;
})
  nodePackages_10_x
  nodePackages_8_x
  nodePackages
;
```

**Comment by oxij** [comment]
> - `recurseIntoAttrs` should be called `hydraPackageSet :: Attrset -> Attrset`
> - `dontRecurseIntoAttrs` should be called `packageSet :: String -> Attrset -> Attrset`
> - `recurseIntoAttrsMaybe` should be called `packageSet`.

I would rather have a single `packageSet` configurable via a `config` option instead of having `hydraPackageSet`. I think having an option to disable stuff hydra builds by default is useful.

> Can you provide an insight on why some are "dont", and others are "maybe"?

Non-default sets are "dont", default ones are "maybe".

> Is "all" your personal choice of "interesting" attrsets?

Yes, the "dont/maybe" part was made so that "all" would be "all default sets". But now thinking about it, it does make sense to have two "all"s...

> Also, a minor nitpick, I can suggest the following refactor to propagate package set name automatically:

That's cute, will do.

**Pull request closed without merging**
