### PR TITLE
[Backport release 23.11]: atuin 17.0.1 -> 18.0.1

### PR DESCRIPTION
**Pull request by matthiasbeyer**
## Description of changes

Backport of

* https://github.com/NixOS/nixpkgs/pull/273427
* https://github.com/NixOS/nixpkgs/pull/278496
* https://github.com/NixOS/nixpkgs/pull/287492
* https://github.com/NixOS/nixpkgs/pull/288377

to release-23.11

CC @happysalada

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
We should probably also wait for review from @0x4A6F as one of the maintainers here? :thinking:

**Comment by happysalada** [comment]
I'm happy to wait 24h, even though I don't think it's really worth bothering him for a backport.

**Comment by matthiasbeyer** [comment]
I'll meet him in person in a few hours probably. Gonna ask him to ACK this, but yes, 24 hours is absolutely fine for me, or even less. I have merge rights and if he approves I'll click the button myself tonight. If I didn't until tomorrow morning, feel free to assume that I simply forgot :laughing:

**Comment by 0x4A6F** [comment]
I would wait till someone on 23.11 can confirm, that the server is working properly. I can't test it as I don't run a stable release.

**Comment by matthiasbeyer** [comment]
I am running the 17.0.1 version of the atuin server on a nixos stable installation. Syncing does currently not work that reliably, but I did not yet figure out why... on one device it works, on my other device it doesn't.

That's why I wanted to update the atuin version on stable nixos, to maybe "get it back to work" :smile: 

So from me: :+1:

**Comment by matthiasbeyer** [comment]
After discussion with @0x4A6F we decided that we wait for #289741 to be solved and then I'll try to update my atuin server installation carefully step by step, to see what happens.

Merging this should be postponed until then.

**Comment by matthiasbeyer** [comment]
This is waiting for https://github.com/NixOS/nixpkgs/pull/290195

**Pull request merged**
