### PR TITLE
clamav: 1.1.0 -> 1.2.0

### PR DESCRIPTION
**Pull request by Steinhagen**
## Description of changes

Updates clamav to the latest version.
Homepage: https://www.clamav.net/

## Things done

Version update

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by matthiasbeyer — APPROVED** [review]

**Comment by ajs124** [comment]
Release notes: https://blog.clamav.net/2023/08/clamav-120-feature-version-and-111-102.html

Should probably also update to 1.1.2 on release-23.05

**Comment by risicle** [comment]
Build failing for me on macos 10.15:

```
In file included from /tmp/nix-build-clamav-1.2.0.drv-0/clamav-1.2.0/libclamav/cache.c:34:
/nix/store/sq9w5y029sl08x2v7f42qldz5yvjarap-Libsystem-1238.60.2/include/math.h:163:58: error: expected ')'
        static __inline__  int __inline_isfinitef       (float      ) __MATH_H_ALWAYS_INLINE__;
                                                                      ^
/nix/store/sq9w5y029sl08x2v7f42qldz5yvjarap-Libsystem-1238.60.2/include/math.h:67:55: note: expanded from macro '__MATH_H_ALWAYS_INLINE__'
    #define __MATH_H_ALWAYS_INLINE__            __attribute__ ((always_inline))
                                                                ^
/tmp/nix-build-clamav-1.2.0.drv-0/clamav-1.2.0/libclamav/others.h:876:30: note: expanded from macro 'always_inline'
#define always_inline inline __attribute__((always_inline))
                             ^

```

**Review by fabianhjr — APPROVED** [review]
1 package built:
clamav

with nixpkgs-review

**Comment by risicle** [comment]
Holup. Have we just knowingly broken this for macos x86_64?

**Comment by fabianhjr** [comment]
I thought this was going stale and x86_64-linux with gcc+glibc is a tier 1 platform. Missed the platform notification to the @NixOS/darwin-maintainers before proceeding. UnU

https://github.com/NixOS/rfcs/blob/master/rfcs/0046-platform-support-tiers.md

**Comment by marsam** [comment]
Fix for the Darwin build https://github.com/NixOS/nixpkgs/pull/254843

**Comment by mweinelt** [comment]
> Release notes: [blog.clamav.net/2023/08/clamav-120-feature-version-and-111-102.html](https://blog.clamav.net/2023/08/clamav-120-feature-version-and-111-102.html)
> 
> Should probably also update to 1.1.2 on release-23.05

Can someone look into this? Apparently there is also a 1.0.3 release that might be more suitable.

**Pull request merged**
