### PR TITLE
trivy: 0.18.3 -> 0.19.0 -> 0.19.1

### PR DESCRIPTION
**Pull request by 06kellyjac**
###### Motivation for this change

Bump trivy to ~`0.19.0`~ `0.19.1`

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 06kellyjac** [comment]
Result of `nixpkgs-review pr 130026` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>trivy</li>
  </ul>
</details>

**Comment by 06kellyjac** [comment]
New `nixpkgs-review` result failed for what appears to be an unrelated issue

```
λ nixpkgs-review pr --no-shell --post-result 130026
$ git -c fetch.prune=false fetch --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/130026/head:refs/nixpkgs-review/1
remote: Enumerating objects: 185, done.
remote: Counting objects: 100% (142/142), done.
remote: Compressing objects: 100% (71/71), done.
remote: Total 185 (delta 94), reused 92 (delta 70), pack-reused 43
Receiving objects: 100% (185/185), 433.28 KiB | 3.67 MiB/s, done.
Resolving deltas: 100% (106/106), completed with 47 local objects.
From https://github.com/NixOS/nixpkgs
   6db0e92064c..085d6f71b94  master                -> refs/nixpkgs-review/0
   88cf2e54db0..e66e0d6ed39  refs/pull/130026/head -> refs/nixpkgs-review/1
$ git worktree add /home/jk/.cache/nixpkgs-review/pr-130026-1/nixpkgs 085d6f71b94887b7b91509ea23e4b5a48044ccaa
Preparing worktree (detached HEAD 085d6f71b94)
Updating files: 100% (26976/26976), done.
HEAD is now at 085d6f71b94 Merge pull request #130002 from fabaff/bump-geopy
$ nix-env --option system x86_64-linux -f /home/jk/.cache/nixpkgs-review/pr-130026-1/nixpkgs -qaP --xml --out-path --show-trace
error: attribute 'gtk3' missing

       at /home/jk/.cache/nixpkgs-review/pr-130026-1/nixpkgs/pkgs/applications/networking/browsers/firefox/wrapper.nix:184:23:

          183|       nativeBuildInputs = [ makeWrapper lndir ];
          184|       buildInputs = [ browser.gtk3 ];
             |                       ^
          185|

       … while evaluating anonymous lambda

       at /home/jk/.cache/nixpkgs-review/pr-130026-1/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:154:17:

          153|           (map (drv: drv.__spliced.hostHost or drv) depsHostHost)
          154|           (map (drv: drv.crossDrv or drv) buildInputs)
             |                 ^
          155|         ]

       … from call site

       … while evaluating 'getOutput'

       at /home/jk/.cache/nixpkgs-review/pr-130026-1/nixpkgs/lib/attrsets.nix:486:23:

          485|   */
          486|   getOutput = output: pkg:
             |                       ^
          487|     if pkg.outputUnspecified or false

       … from call site

       … while evaluating the attribute 'buildInputs' of the derivation 'midori-9.0'

       at /home/jk/.cache/nixpkgs-review/pr-130026-1/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:203:11:

          202|         // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          203|           name =
             |           ^
          204|             let

       … while querying the derivation named 'midori-9.0'
https://github.com/NixOS/nixpkgs/pull/130026 failed to build
$ git worktree prune
```

**Comment by jonringer** [comment]
is there much value in have two commits? Personally I would squash

**Comment by 06kellyjac** [comment]
If I've already verified a commit works I tend to keep it so people can (try) grab older versions (e.g. https://4shells.com/nixdb/search), I guess that's less important for a tool like trivy

**Pull request merged**
