### PR TITLE
garage_0_7: drop, garage_0_9: init at 0.9.0

### PR DESCRIPTION
**Pull request by RaitoBezarius**
## Description of changes

- 0.7 is dropped (EOL)
- 0.9 is introduced: https://git.deuxfleurs.fr/Deuxfleurs/garage/releases/tag/v0.9.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by adamcstephens** [comment]
Result of `nixpkgs-review pr 260255` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>garage_0_9 (garage_0_9_0)</li>
  </ul>
</details>

-----

Result of `nixpkgs-review pr 260255` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>garage_0_9 (garage_0_9_0)</li>
  </ul>
</details>

-----

Both Darwin systems are failing on 0.9 with a bunch of integer type mismatches.

<details>

```
error[E0308]: mismatched types
   --> src/rpc/system.rs:902:40
    |
902 |                 let avail = x.blocks_available() * x.fragment_size() as u64;
    |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `u64`

error[E0277]: cannot multiply `u32` by `u64`
   --> src/rpc/system.rs:902:38
    |
902 |                 let avail = x.blocks_available() * x.fragment_size() as u64;
    |                                                  ^ no implementation for `u32 * u64`
    |
    = help: the trait `Mul<u64>` is not implemented for `u32`
    = help: the following other types implement trait `Mul<Rhs>`:
              <u32 as Mul>
              <u32 as Mul<ByteSize>>
              <u32 as Mul<std::time::Duration>>
              <u32 as Mul<&u32>>
              <&'a u32 as Mul<u32>>
              <&u32 as Mul<&u32>>

error[E0308]: mismatched types
   --> src/rpc/system.rs:903:30
    |
903 |                 let total = x.blocks() * x.fragment_size() as u64;
    |                                          ^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `u64`

error[E0277]: cannot multiply `u32` by `u64`
   --> src/rpc/system.rs:903:28
    |
903 |                 let total = x.blocks() * x.fragment_size() as u64;
    |                                        ^ no implementation for `u32 * u64`
    |
    = help: the trait `Mul<u64>` is not implemented for `u32`
    = help: the following other types implement trait `Mul<Rhs>`:
              <u32 as Mul>
              <u32 as Mul<ByteSize>>
              <u32 as Mul<std::time::Duration>>
              <u32 as Mul<&u32>>
              <&'a u32 as Mul<u32>>
              <&u32 as Mul<&u32>>

error[E0308]: mismatched types
   --> src/rpc/system.rs:909:26
    |
909 |         self.meta_disk_avail = mount_avail(meta_dir).map(|(_, a, t)| (a, t));
    |         --------------------   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Option<(u64, u64)>`, found `Option<(u32, u32)>`
    |         |
    |         expected due to the type of this binding
    |
    = note: expected enum `std::option::Option<(u64, u64)>`
               found enum `std::option::Option<(u32, u32)>`

error[E0308]: mismatched types
   --> src/rpc/system.rs:911:32
    |
911 |             DataDirEnum::Single(dir) => mount_avail(dir).map(|(_, a, t)| (a, t)),
    |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Option<(u64, u64)>`, found `Option<(u32, u32)>`
    |
    = note: expected enum `std::option::Option<(u64, u64)>`
               found enum `std::option::Option<(u32, u32)>`
```

</details>

**Comment by adamcstephens** [comment]
`single_node # Error: Internal error: The storage capacity of he cluster is to small. It is impossible to store partitions of size 1.`

This is likely due to

> Capacity values are now in actual byte units. The translation from the old layout will assign 1 capacity = 1Gb by default

**Review by yu-re-ka — APPROVED** [review]

**Comment by flokli** [comment]
@RaitoBezarius the macos build got upstreamed and merged at https://git.deuxfleurs.fr/Deuxfleurs/garage/pulls/654

**Comment by flokli** [comment]
The aarch64-darwin build successfully finished:

image

**Comment by emilylange** [comment]
Still missing @adamcstephens' patch from https://github.com/NixOS/nixpkgs/pull/260255#issuecomment-1757820404 for the tests^

**Comment by flokli** [comment]
> Still missing @adamcstephens' patch from [#260255 (comment)](https://github.com/NixOS/nixpkgs/pull/260255#issuecomment-1757820404) for the tests^

Done!

**Review by emilylange — APPROVED** [review]

**Comment by yu-re-ka** [comment]
In my opionion changing the default package used by the module is dangerous. This needs an improvement in the module to choose the default version based on stateVersion, or even require the user to set the version manually.
That's why I'm sceptical about changing the default.

17 Oct 2023 00:05:43 Emily ***@***.***>:

**Comment by RaitoBezarius** [comment]
Hmm, retrospectively, I agree

**Comment by flokli** [comment]
Having the unversioned attribute name always point to the latest version is somewhat a nixpkgs convention.

I think it's a good idea to always have the user explicitly set the package (version) they want to run though, so I'd prefer dropping the default in the module system, and documenting it in the release notes.

Users then always consciously choose the version they run, which seems less brittle than state version comparisons, which might not capture the full picture either.

**Comment by yu-re-ka** [comment]
I disagree that this is a convention. The unversioned attribute points to a reasonable default. Not necessarily the latest version, see postgres or LLVM.

> I think it's a good idea to always have the user explicitly set the package (version) they want to run though, so I'd prefer dropping the default in the module system, and documenting it in the release notes.

Can we drop the default from the module in this PR, or postpone the "point garage to garage_0_9" to after that has been done?

**Comment by flokli** [comment]
> I disagree that this is a convention. The unversioned attribute points to a reasonable default.

But using garage 0.9 is a reasonable default for someone starting new. I'll update this PR to remove the default, and add some release notes to document this now needs to be set explicitly.

**Comment by flokli** [comment]
> I'll update this PR to remove the default, and add some release notes to document this now needs to be set explicitly.

Done!

**Review by adamcstephens — APPROVED** [review]
I successfully upgraded my cluster to 0.9 last night using this branch.

Result of `nixpkgs-review pr 260255` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>garage (garage_0_9 ,garage_0_9_0)</li>
  </ul>
</details>

-----

Result of `nixpkgs-review pr 260255` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>garage (garage_0_9 ,garage_0_9_0)</li>
  </ul>
</details>

-----

Result of `nixpkgs-review pr 260255` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>garage (garage_0_9 ,garage_0_9_0)</li>
  </ul>
</details>

-----

Result of `nixpkgs-review pr 260255` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>garage (garage_0_9 ,garage_0_9_0)</li>
  </ul>
</details>

**Pull request merged**
