### PR TITLE
curl: 7.65.0 -> 7.65.1

### PR DESCRIPTION
**Pull request by dtzWill**
https://curl.haxx.se/changes.html#7_65_1

###### Motivation for this change

Rebuilding all the things is my favorite! O:)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
Eval failure looks rather unrelated:

```
...
duplicate formal function argument 'fetchpatch' at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-2-shlevy.ewr1.nix.ci/pkgs/servers/pulseaudio/default.nix:1:26
...
```

So perhaps try again?

**Comment by dtzWill** [comment]
@GrahamcOfBorg round2fight

**Comment by dtzWill** [comment]
@GrahamcOfBorg go go gadget rebuild
@GrahamcOfBorg if at first you don't succeed, try try again
@GrahamcOfBorg get knocked down, you get up again, never gonna keep borg down
@GrahamcOfBorg build curl

**Comment by FRidh** [comment]
newer curl is in

**Pull request closed without merging**
