### PR TITLE
discourse: 2.9.0.beta4 -> 2.9.0.beta9

### PR DESCRIPTION
**Pull request by talyz**
###### Description of changes
Update Discourse to the latest beta and update all plugins.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ryantm** [comment]
I tried upgrading one of my servers to this and the page shows a constant loading animation with these errors in the browser console:
image

**Comment by ryantm** [comment]
Here's a probably relevant post: https://meta.discourse.org/t/regression-on-could-not-find-module-handlebars-imported-from-discourse-common-lib-raw-handlebars/225572

**Comment by dpausp** [comment]
Looks like we were working on the update simultaneosly. Your PR is cleaner but I found the reason for the handlebars error Ryan mentioned :) The problem is indeed the missing `dist` directory which is used by Discourse code to find the dependency "chunks" that have to be included in the page. Unfortunately, the "file not found" exception gets ignored and nothing is rendered, which leads to the missing handlebars module.

**Comment by dpausp** [comment]
Here's the fix: https://github.com/dpausp/nixpkgs/commit/7cf064e1ef594d5c016c73c0801d7439b2de9f91 @ryantm @talyz

**Comment by ryantm** [comment]
Seems to be working well for me with @dpausp's patch on top.

**Comment by talyz** [comment]
Oh, great! Maybe we should just include the whole `javascripts` folder to be on the safe side? That way we catch any future generated artifacts as well. I'll push a fix-up that does this, which seems to work just fine to me.

**Comment by ryantm** [comment]
Your updates work for me @talyz. Meanwhile they're now on 2.9.0.beta9.

**Comment by talyz** [comment]
Okay, I've updated to **2.9.0.beta9** and squashed the change now.

**Comment by ryantm** [comment]
The latest thing still works for me!

**Review by ryantm — APPROVED** [review]

**Pull request merged**
