### PR TITLE
gradle: 8.10 -> 8.10.2

### PR DESCRIPTION
**Pull request by britter**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by skowalak — APPROVED** [review]
lgtm!

**Comment by katexochen** [comment]
@ofborg eval

**Comment by katexochen** [comment]
Result of `nixpkgs-review pr 351437` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>jabref</li>
    <li>keyguard</li>
  </ul>
</details>
<details>
  <summary>51 packages built:</summary>
  <ul>
    <li>apkleaks</li>
    <li>apkleaks.dist</li>
    <li>apksigcopier</li>
    <li>apksigcopier.dist</li>
    <li>apksigner</li>
    <li>atlauncher</li>
    <li>cie-middleware-linux</li>
    <li>cryptomator</li>
    <li>diffoscope</li>
    <li>diffoscope.dist</li>
    <li>diffoscope.man</li>
    <li>experienced-pixel-dungeon</li>
    <li>fdroidserver</li>
    <li>fdroidserver.dist</li>
    <li>ghidra</li>
    <li>ghidra-extensions.findcrypt</li>
    <li>ghidra-extensions.ghidra-delinker-extension</li>
    <li>ghidra-extensions.ghidra-golanganalyzerextension</li>
    <li>ghidra-extensions.gnudisassembler</li>
    <li>ghidra-extensions.lightkeeper</li>
    <li>ghidra-extensions.machinelearning</li>
    <li>ghidra-extensions.ret-sync</li>
    <li>ghidra-extensions.sleighdevtools</li>
    <li>gotenberg</li>
    <li>gradle (gradle_8)</li>
    <li>gradle-unwrapped (gradle_8-unwrapped)</li>
    <li>gscan2pdf</li>
    <li>gscan2pdf.man</li>
    <li>jadx</li>
    <li>openjfx22 (javaPackages.openjfx22)</li>
    <li>jextract</li>
    <li>jextract-21</li>
    <li>kotlin-language-server</li>
    <li>libeufin</li>
    <li>mindustry</li>
    <li>mindustry-server</li>
    <li>mindustry-wayland</li>
    <li>moneydance</li>
    <li>nextflow</li>
    <li>nf-test</li>
    <li>pdfchain</li>
    <li>pdftk</li>
    <li>pidginPackages.purple-signald</li>
    <li>rat-king-adventure</li>
    <li>rkpd2</li>
    <li>shattered-pixel-dungeon</li>
    <li>shorter-pixel-dungeon</li>
    <li>signald</li>
    <li>signaturepdf</li>
    <li>sparrow</li>
    <li>sparrow-unwrapped</li>
  </ul>
</details>

**Comment by katexochen** [comment]
Never mind, some hiccup in my remote builder setup:

Result of `nixpkgs-review pr 351437` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>53 packages built:</summary>
  <ul>
    <li>apkleaks</li>
    <li>apkleaks.dist</li>
    <li>apksigcopier</li>
    <li>apksigcopier.dist</li>
    <li>apksigner</li>
    <li>atlauncher</li>
    <li>cie-middleware-linux</li>
    <li>cryptomator</li>
    <li>diffoscope</li>
    <li>diffoscope.dist</li>
    <li>diffoscope.man</li>
    <li>experienced-pixel-dungeon</li>
    <li>fdroidserver</li>
    <li>fdroidserver.dist</li>
    <li>ghidra</li>
    <li>ghidra-extensions.findcrypt</li>
    <li>ghidra-extensions.ghidra-delinker-extension</li>
    <li>ghidra-extensions.ghidra-golanganalyzerextension</li>
    <li>ghidra-extensions.gnudisassembler</li>
    <li>ghidra-extensions.lightkeeper</li>
    <li>ghidra-extensions.machinelearning</li>
    <li>ghidra-extensions.ret-sync</li>
    <li>ghidra-extensions.sleighdevtools</li>
    <li>gotenberg</li>
    <li>gradle (gradle_8)</li>
    <li>gradle-unwrapped (gradle_8-unwrapped)</li>
    <li>gscan2pdf</li>
    <li>gscan2pdf.man</li>
    <li>jabref</li>
    <li>jadx</li>
    <li>openjfx22 (javaPackages.openjfx22)</li>
    <li>jextract</li>
    <li>jextract-21</li>
    <li>keyguard</li>
    <li>kotlin-language-server</li>
    <li>libeufin</li>
    <li>mindustry</li>
    <li>mindustry-server</li>
    <li>mindustry-wayland</li>
    <li>moneydance</li>
    <li>nextflow</li>
    <li>nf-test</li>
    <li>pdfchain</li>
    <li>pdftk</li>
    <li>pidginPackages.purple-signald</li>
    <li>rat-king-adventure</li>
    <li>rkpd2</li>
    <li>shattered-pixel-dungeon</li>
    <li>shorter-pixel-dungeon</li>
    <li>signald</li>
    <li>signaturepdf</li>
    <li>sparrow</li>
    <li>sparrow-unwrapped</li>
  </ul>
</details>

**Review by katexochen — APPROVED** [review]

**Comment by britter** [comment]
I've looked into the conflict. 24.05 is still on Gradle 8.7 and updating it to 8.10.2 requires more changes than just updating the version. I think we should leave it like it is and wait for 24.11.

**Pull request merged**
