### PR TITLE
kde_frameworks: 5.44 -> 5.45

### PR DESCRIPTION
**Pull request by bkchr**
###### Motivation for this change

It's still compiling, so I can't say for 100% that everything is working.

@adisbladis @ttuegel @peterhoeg 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peterhoeg** [comment]
How is it working so far?

**Comment by bkchr** [comment]
I'm still on it. :)

**Comment by bkchr** [comment]
I have some problems with `msgfmt` from gettext I think. It seems to be hanging somewhere, but I don't where exactly.

**Comment by bkchr** [comment]
Okay, I found a bug report and a fix that could solve the problem I have: https://phabricator.kde.org/D12216
I will add the patch and test it tomorrow.

**Comment by bkchr** [comment]
After adding the patch, compilation finally worked as expected :)

**Pull request merged**
