### PR TITLE
libtracefs: 1.5.0 -> 1.6.4, trace-cmd: 3.1.2 -> 3.1.6

### PR DESCRIPTION
**Pull request by wentasah**
###### Description of changes

trace-cmd fails to build with make-4.4, which was updated recently. The build does not fail with an error, but [times out](https://hydra.nixos.org/build/202269459).

While it would be possible to fix the build with the older version we have in nixpkgs, I decided to update trace-cmd to the latest version, which fixes few bugs. See the changlogs: [3.1.3](https://git.kernel.org/pub/scm/utils/trace-cmd/trace-cmd.git/tag/?h=trace-cmd-v3.1.3), [3.1.4](https://git.kernel.org/pub/scm/utils/trace-cmd/trace-cmd.git/tag/?h=trace-cmd-v3.1.4), [3.1.5](https://git.kernel.org/pub/scm/utils/trace-cmd/trace-cmd.git/tag/?h=trace-cmd-v3.1.5).

The update requires newer libtracefs, which was also updated. Changelogs contains a few new features and bugfixes: [1.6.0](https://git.kernel.org/pub/scm/libs/libtrace/libtracefs.git/tag/?h=libtracefs-1.6.0), [1.6.1](https://git.kernel.org/pub/scm/libs/libtrace/libtracefs.git/tag/?h=libtracefs-1.6.1), [1.6.2](https://git.kernel.org/pub/scm/libs/libtrace/libtracefs.git/tag/?h=libtracefs-1.6.2), [1.6.3](https://git.kernel.org/pub/scm/libs/libtrace/libtracefs.git/tag/?h=libtracefs-1.6.3).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aaronjheng** [comment]
libtracefs 1.6.4 and trace-cmd 3.1.6 are out.
I think, your PR title should be something like `libtracefs: 1.5.0 -> 1.6.4, trace-cmd: 3.1.2 -> 3.1.6`.

**Comment by wentasah** [comment]
> libtracefs 1.6.4 and trace-cmd 3.1.6 are out.

Thanks for notifying me. The new versions contain only bugfixes, so it's safe to update them. I've updated the PR content as well as the title.

**Comment by ethorsoe** [comment]
I have tested our main test case of record/report, seems to work fine including stack traces. I had to rebase on nixos-unstable to avoid other unrelated issues for the test (no manual changes in the rebase).

**Comment by ethorsoe** [comment]
built and tested (superficially on aarch64 too)

**Pull request merged**
