### PR TITLE
psst: Fix autoupdate script

### PR DESCRIPTION
**Pull request by vbrandl**
## Description of changes

The current update script that is used by @r-ryantm sets the package version to `unstable-$(date +%F)`. When I initially added psst, I [was told to](https://github.com/NixOS/nixpkgs/pull/151479#discussion_r817549368) set the package name to the date of the last commit:

> `unstable-XXXX-XX-XX` and replace XXXX-XX-XX with the date of the commit.

The current state of the update script will create update PRs that only update the package version even if nothing actually changed, such as https://github.com/NixOS/nixpkgs/pull/295215.

## Things done

`update.sh` now extracts the date from the GitHub API response and uses this value for the nixpkgs version.

One thing that remains unclear to me, is how we should handle the current diverging state. At the time of writing this PR, the [latest commit in jpochyla/psst](https://github.com/jpochyla/psst/commits/master/) is jpochyla/psst@0cb4f6964b5ba771182ccfe005260a86a494ef92 from 2024-02-11. So when running the script now, it would generate the nixkpgs version `unstable-2024-02-11` which is behind the (false) current nixpkgs version of `unstable-2024-03-04`. I'm not sure what will happen if @r-ryantm runs the script again. Would it generate a new PR for psst with an older version? Should we also include a check in `update.sh` to abort early, if the latest rev in the remote repo is the same as the one in nixpkgs?

Pinging relevant users: @peterhoeg, @ambroisie and @ryantm (especialy for my last question since I'm not sure how nixpkgs-update works in detail)

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by ambroisie — APPROVED** [review]
Script looks fine. I'd do a separate call to fetch `rev` and use the same code path to fetch the date, but that's not a necessary change.

As for the course of action with the current, erroneous, version in the package I think you should update it to the correct one in this PR.

@r-ryantm should only open a PR if there's an actual change after running the update script.

**Comment by vbrandl** [comment]
The problem is, that the version on master is unstable-2024-03-04, which is higher than the actual version of 2024-02-11, so fixing that would imply a downgrade. Im not sure if this works or is allowed.

As for using the same logic to retrieve the date in both cases: I decided not to do that because it would require two network calls instead of one. But I can change this.

**Comment by vbrandl** [comment]
@ambroisie any idea, who I should ping to get this merged?

**Comment by ambroisie** [comment]
@vbrandl pinging me works :-).

**Pull request merged**
