### PR TITLE
keepassx2: 2.0alpha6 -> 2.0beta1

### PR DESCRIPTION
**Pull request by jraygauthier**

### CODE REVIEW

**Comment by nckx** [comment]
CC @qknight.

**Comment by polyzen** [comment]
[2.0beta2](https://www.keepassx.org/news/2015/09/514)

**Comment by nckx** [comment]
Is there a stable release expected soon? If not, I'll merge an (updated) PR since the maintainer seems to be AWOL.

**Comment by polyzen** [comment]
Can't say

**Comment by nckx** [comment]
@polyzen: I just noticed the above commit, so never mind :-)

**Pull request closed without merging**
