### PR TITLE
[staging] set-source-date-epoch-to-latest.sh: ignore generated files

### PR DESCRIPTION
**Pull request by volth**
set-source-date-epoch-to-latest.sh to ignore files newer than ```$NIX_BUILD_TOP/..``` (unlike ```$NIX_BUILD_TOP``` it is root-owned and cannot be touched by ```nixbld1```).

Fixes https://github.com/NixOS/nixpkgs/issues/28218

mass-rebuild

### CODE REVIEW

**Comment by volth** [comment]
```..``` here is not the parent (/tmp) directory but the ```..``` entry in the NIX_BUILD_TOP.

there are a couple of other options discussed in #28218

**Comment by vcunat** [comment]
Well, on my NixOS, `ls -ld somedir/foo/..` shows the timestamp of `somedir/`, if I read my experiments right.

**Comment by volth** [comment]
If so, then the PR may not work as planned

**Comment by vcunat** [comment]
On my NixOS with sandboxing and `/tmp` on tmpfs, this does make `libertine` binary-deterministic.  Let me stage now &ndash; there's a security rebuild of stdenv anyway (coreutils); we can improve later.

**Pull request merged**
