### PR TITLE
ipe: 7.2.9 -> 7.2.10

### PR DESCRIPTION
**Pull request by dtzWill**
https://mailman.science.uu.nl/pipermail/ipe-announce/2019-February/000077.html

Cleanup a bit while visiting :).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vcunat** [comment]
@dtzWill: the hash doesn't match and [apparently never did](https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.ipe.x86_64-linux/all).  Any idea why?  Needs backport to 19.03, too (#56826).

**Comment by dtzWill** [comment]
On Mon, 04 Mar 2019 22:27:10 -0800, Vladimír Čunát <notifications@github.com> wrote:
> @dtzWill: the hash doesn't match and [apparently never did](https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.ipe.x86_64-linux/all).  Any idea why?  Needs backport to 19.03, too (#56826).

Looks like the release was changed shortly after initial posting? :(

https://mailman.science.uu.nl/pipermail/ipe-announce/2019-February/000080.html

**Comment by vcunat** [comment]
OK, pushed 3adbe4f7374 etc.

**Comment by dtzWill** [comment]
Thank you!

**Pull request merged**
