### PR TITLE
android-tools: add patch to fix build against 6.0 kernel headers

### PR DESCRIPTION
**Pull request by yu-re-ka**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by trofi** [comment]
Result of `nixpkgs-review pr 196146` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>agi</li>
    <li>android-tools</li>
  </ul>
</details>

**Review by trofi — APPROVED** [review]
Is it an upstream patch? If not should it be forwarded there as well?

**Comment by primeos** [comment]
> Is it an upstream patch? If not should it be forwarded there as well?

Agreed. If it's an upstream patch then `fetchpatch` is much preferred (AFAIK; and the source should definitely be documented in Nixpkgs). If this patch is from you then it should be sent upstream as well (and ideally it would even get merged so that we can use `fetchpatch`).

**Comment by vcunat** [comment]
Upstream merged a similar patch in the meantime: https://github.com/nmeum/android-tools/pull/85

They're exactly the same, except they have additional diffs in `usb_close()` and `register_device()`.  I'd expect their patch is more correct, but I haven't _really_ reviewed either.

**Comment by yu-re-ka** [comment]
I wrote this patch with the help of a friend. I did not get around to submitting it upstream, but if they already have an equivalent patch submitted there that's great too.

> They're exactly the same, except they have additional diffs in usb_close() and register_device().

You overlooked that my patch adds the allocation/free of heap-allocated child structs to the constructor/destructor of usb_handle. This is cleaner than what they are doing because it makes it impossible to accidentally delete the usb_handle without freeing the child structs too. But well, theirs will probably work too (except for leaking memory in some failure cases).

**Comment by vcunat** [comment]
Oh right, I did overlook that when diffing.

**Comment by yu-re-ka** [comment]
Please someone else update or create a new PR for importing the upstream patch. I can't focus on this currently.
Feel free to request review from me then.

**Comment by vcunat** [comment]
The upstream patch wouldn't apply as-is.  Maybe it will after the update.  Anyway, your patch should be OK and at least it fixes the build **now**.  Apparently, many nixpkgs users were affected.

**Pull request merged**
