### PR TITLE
freerdp: 20160909 -> 20170201 and rename freerdpStable to freerdp_legacy

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

*NOTE*: ```weston``` still requires the old freerdp version, so until weston 2.0 is released, we cannot merge this.

The former "stable" version of FreeRDP was actually not stable - it just happened to have a released version while being both buggy and insecure.

The "unstable" branch hasn't seen a release in years, but everybody should be using this instead and I have been using it as a daily driver for ages.

This new version works beautifully here.

If/when at some point upstream does a normal release, we can bring back stable/unstable if needed.

As I am quite dependent on FreeRDP working properly, I will be commit to keeping this updated.

The commit used for this release follows the Arch Linux release.

###### Things done

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
What about weston?

**Comment by joachifm** [comment]
For example,
```
libweston/compositor-rdp.c: In function 'rdp_peer_context_new':
libweston/compositor-rdp.c:621:53: error: 'RDP_PIXEL_FORMAT_B8G8R8A8' undeclared (first use in this function)
```

**Comment by peterhoeg** [comment]
I should have tagged this differently admittedly. 

We need weston 2.0 (currently only an alpha release) for support with this version. I will continue to carry this version as I don't need weston and we then can look at actually merging this when it is available.

Alternatively, we remove ```freerdpStable``` from the global namespace and make it local to weston. Nobody should really be using it directly.

Any thoughts?

**Comment by joachifm** [comment]
What about just keeping `freerdpStable` around, while making `freerdp = freerdpUnstable`, with a TODO to expunge the "stable" version asap? Seems unfortunate to hold off on this just on account of `weston`. Keeping both is the path of least resistance, I think.

**Comment by peterhoeg** [comment]
Having some around called "xxxStable" when it very much isn't so just irks me.

Another option is to simply build weston 1.12 without the rdp compositor. Shipping software with CVEs is not exactly great. http://www.cvedetails.com/vulnerability-list/vendor_id-13032/product_id-26789/Freerdp-Project-Freerdp.html

**Comment by joachifm** [comment]
Name it `legacy` or `_1` or something, if `stable` is a problem. All of the issues in the cve list are denial of service, so it's not *that* awful and presumably it'll be removed in the medium-long term. In any event, by simply having both versions, this would've been integrated already :) (hence the proliferation of `_suffix` packages, it's just easier to get on with things that way).

**Comment by peterhoeg** [comment]
Just realized when trying to build ```freerdpStable``` that it was marked as broken back in September: https://github.com/NixOS/nixpkgs/commit/4c0b07ce1eb680f67cb28cf952ef14657779cf6a

If I remove ```broken = true;``` I can actually build it. Should we unmark it and then patch the 2 derivations that depend on it to use ```freerdp_legacy``` instead?

**Comment by peterhoeg** [comment]
@joachifm - and now everything works.

**Comment by joachifm** [comment]
@peterhoeg great, thank you

**Pull request merged**
