### PR TITLE
saml2aws: 2.10.0 -> 2.13.0, add darwin to platforms

### PR DESCRIPTION
**Pull request by swdunlop**
###### Motivation for this change

update to 2.13.0, fixing support for PingID and adding Darwin platform support.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build saml2aws

**Comment by Infinisil** [comment]
Please remove any merge commits from this PR. This looks good to merge after that

**Comment by mmahut** [comment]
Are there any updates on this pull request, please?

**Comment by Infinisil** [comment]
Closing due to inactivity for 1.5 years

**Pull request closed without merging**
