### PR TITLE
python310Packages.wandb: disable more tests

### PR DESCRIPTION
**Pull request by wegank**
###### Description of changes

https://malob.github.io/nix-review-tools-reports/nixpkgs:trunk/nixpkgs_trunk_1794289.html

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by samuela** [comment]
It builds fine for me on x86_64-linux:
```
sam.ainsworth in 🌐 cs-tze7x4cv-extreme-homedir-725883 in nixpkgs on  master [$?] on ☁️  sam.ainsworth@getcruise.com took 25m8s
❯ git log -1
commit 770f6182ac3084eb9ed836e1f34fce0595c905db (HEAD -> master, upstream/master, upstream/HEAD)
Merge: d3ccbe1e550 e24518ef591
Author: Weijia Wang <9713184+wegank@users.noreply.github.com>
Date:   Sat Apr 29 02:38:44 2023 +0300

    Merge pull request #228796 from dritter/update-jetbrains2

    jetbrains: 2023.1 -> 2023.1.2

sam.ainsworth in 🌐 cs-tze7x4cv-extreme-homedir-725883 in nixpkgs on  master [$?] on ☁️  sam.ainsworth@getcruise.com
❯ nix-build -A python3Packages.wandb
/nix/store/0liblfis25kgzf0dabmi8a6ddz7v26m1-python3.10-wandb-0.15.0
```
Perhaps i'm missing something?

**Comment by wegank** [comment]
It seems that there are some flaky tests. I have the first test failing on aarch64-darwin, but not on Hydra, for example.

**Comment by samuela** [comment]
Hmm it's building fine for me on aarch64-darwin:
```
nixpkgs on  master on ☁️  (us-west-2)
❯ git log -1 --format="%H"
9a382aa6ca1ebd1342e0a2f233a6fdd1a35d57fa

nixpkgs on  master on ☁️  (us-west-2)
❯ nix-build -A python3Packages.wandb
/nix/store/4bk0gff715jf9jlf9wknaxbhqni94svp-python3.10-wandb-0.15.0
```

However, I can see from https://hydra.nixos.org/build/217805920/nixlog/1 that the `test_artifacts_cache_cleanup` test in `tests/pytest_tests/unit_tests/test_artifacts/test_storage.py` is failing on x86_64-linux.

Is there a log for the aarch64-darwin failures you've seen? The link only says that the build timed out.

Whatever the case may be we should raise these issues upstream and add comments pointing to those issues. If the issues are platform-specific we should add them conditionally.

**Comment by wegank** [comment]
@ofborg build python310Packages.wandb python310Packages.wandb.passthru.tests

**Comment by natsukium** [comment]
On my `x86_64-linux` machine, `tests/pytest_tests/unit_tests/test_artifacts/test_storage.py` is not reproducible, sometimes passing and sometimes failing.

**Comment by wegank** [comment]
@ofborg build openai-full openai-full.passthru.tests

**Comment by samuela** [comment]
Ok let's report these failures upstream, add code comment(s) looking to the report and get this merged

**Comment by wegank** [comment]
Reported in wandb/wandb#5423.

**Comment by wegank** [comment]
I have no interest in the flaky `aws-sdk-cpp` failures on darwin, so merging.

**Pull request merged**
