### PR TITLE
diffoscope: 271 -> 273

### PR DESCRIPTION
**Pull request by trofi**
Changes:
- https://diffoscope.org/news/diffoscope-272-released/
- https://diffoscope.org/news/diffoscope-273-released/

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by philiptaron** [comment]
Fails to build due to a test failure, likely not this PR's fault:

```
=================================== FAILURES ===================================
_______________________________ test_has_visuals _______________________________

monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7ffee7fc3bc0>
image1 = <<class 'abc.JPEGImageFile'> /build/diffoscope-272/tests/data/test1.jpg>
image2 = <<class 'abc.JPEGImageFile'> /build/diffoscope-272/tests/data/test2.jpg>

    @skip_unless_tools_exist("img2txt", "convert", "identify")
    def test_has_visuals(monkeypatch, image1, image2):
        monkeypatch.setattr(Config(), "compute_visual_diffs", True)
        jpg_diff = image1.compare(image2)
>       assert len(jpg_diff.details) == 2
E       assert 1 == 2
E        +  where 1 = len([<Difference Image content -- Image content []>])
E        +    where [<Difference Image content -- Image content []>] = <Difference /build/diffoscope-272/tests/data/test1.jpg -- /build/diffoscope-272/tests/data/test2.jpg [<Difference Image content -- Image content []>]>.details

tests/comparators/test_jpeg_image.py:87: AssertionError
----------------------------- Captured stderr call -----------------------------
WARNING: The convert command is deprecated in IMv7, use "magick" instead of "convert" or "magick convert"
```

**Comment by raboof** [comment]
the build failure is tracked in #328350 - you could add https://salsa.debian.org/reproducible-builds/diffoscope/-/commit/bbcf367cca97eac25129ad861c628a3203a3500e as a patch for now (until 273 is released)

**Comment by trofi** [comment]
Let's wait for 273. Converting to draft.

**Comment by raboof** [comment]
273 is now out :tada:

**Comment by trofi** [comment]
Updated to `273`, applied `nixfmt` and undrafted.

**Comment by trofi** [comment]
Result of `nixpkgs-review pr 324888` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>diffoscope</li>
    <li>diffoscope.dist</li>
    <li>diffoscope.man</li>
    <li>diffoscopeMinimal</li>
    <li>diffoscopeMinimal.dist</li>
    <li>diffoscopeMinimal.man</li>
  </ul>
</details>

**Review by SuperSandro2000 — APPROVED** [review]

**Review by raboof — APPROVED** [review]

**Pull request merged**
