### PR TITLE
[19.03] backport wasmtime

### PR DESCRIPTION
**Pull request by asymmetric**
###### Motivation for this change

This is a backport of 2 of @matthewbauer's [wasm](https://github.com/NixOS/nixpkgs/commit/dbb94b984f8282d1d9eada83634fc6777d19bdac) [commits](https://github.com/NixOS/nixpkgs/commit/bfaebc3647bc80137c51185e2a5a332d3420831d), stripped to the bare minimum so that they only just init the package.

I added myself as a "co-author" as I modified the commit slightly (removed the changes to `lib/systems/default.nix` for example), but credit is all his.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthewbauer** [comment]
@grahamcofborg build wasmtime

**Comment by matthewbauer** [comment]
Can you make it x86_64-linux only for now?

**Comment by asymmetric** [comment]
@matthewbauer how did you produce the Cargo.lock patch?

**Comment by matthewbauer** [comment]
I think it just came from a successful `cargo build` run.

**Pull request merged**
