### PR TITLE
util-linux: fix unshare -r on linux >=3.19

### PR DESCRIPTION
**Pull request by abbradar**
https://github.com/karelzak/util-linux/commit/0bf159413bdb9e324864a422b7aecb081e739119

### CODE REVIEW

**Comment by abbradar** [comment]
I've tested locally that `unshare` works for me (this should have no other effects). Also, should I PR against `staging` instead?

**Comment by shlevy** [comment]
Hm is this really mass-rebuild? What depends on utillinux?

**Comment by abbradar** [comment]
I can't quite get what, but it causes rebuild of nearly everything for me (I've tried with and without the patch on a clear tree to make sure).

**Comment by abbradar** [comment]
(And yes, it's really strange -- maybe something has an optional dependency?)

**Comment by edolstra** [comment]
Maybe we should update to 2.26 while we're at it?

**Comment by abbradar** [comment]
2.26 actually has this fix (according to a Git tag), but is it out yet?

**Comment by abbradar** [comment]
According to https://git.kernel.org/cgit/utils/util-linux/util-linux.git/ , it's not yet. From looking at timestamps there, it is usually several months from the first rc till the release.

**Comment by edolstra** [comment]
Oh, I was confused by the existence of https://www.kernel.org/pub/linux/utils/util-linux/v2.26/.

**Comment by vcunat** [comment]
@shlevy: systemd depends on util-linux (refers the binaries), so that's probably why it's mass-rebuild.

Builds and looks safe, so pushed to staging.

**Comment by abbradar** [comment]
Thanks!

**Pull request closed without merging**
