### PR TITLE
Revert "python3Packages.localzone: Use dnspython_1"

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Can you pick https://github.com/NixOS/nixpkgs/pull/99568/commits/198f2da81aae1b4ed2dff30af6d9aaadfcf1413f?

**Comment by FRidh** [comment]
https://github.com/NixOS/nixpkgs/pull/99568

**Comment by jonringer** [comment]
I already made an issue upstream https://github.com/ags-slc/localzone/issues/1

**Comment by ags-slc** [comment]
Thanks again for reporting this issue @jonringer. The latest release should now support dnspython >= 2.

**Pull request closed without merging**
