### PR TITLE
[20.09] vscodium: 1.51.1 -> 1.54.3

### PR DESCRIPTION
**Pull request by JesusMtnez**
###### Motivation for this change

Upgrade vscodium to latest stable release 1.54.3

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 117442` at dec2f560 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>vscodium</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: EvalError

Cannot evaluate attribute ‘vscodium’ in ‘/nix/store/dmgdmivd0f2s4m18qgivm49fhqk7ixhg-nixpkgs’.</li>
  </ul>
</details>

**Comment by turion** [comment]
What is the evaluation error?

**Comment by risicle** [comment]
What's the thinking behind upgrading stable?

**Comment by Synthetica9** [comment]
> What's the thinking behind upgrading stable?

I believe extensions don't work great on older versions

**Comment by JesusMtnez** [comment]
> What's the thinking behind upgrading stable?

I think upgrading `vscodium` is stable enough to be back-ported, so all the extensions and the editor are up-to-date but we could still continue using 20.09 stable release.

**Pull request closed without merging**
