### PR TITLE
llvmPackages_13: Forward port the patches from llvmPackages_12

### PR DESCRIPTION
**Pull request by primeos**
###### Motivation for this change

#133148 and #132643.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by primeos** [comment]
@ofborg build llvmPackages_13

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 133168` at c8db49f0 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>13 packages skipped due to time constraints:</summary>
  <ul>
    <li>lldb_13 (llvmPackages_13.lldb)</li>
    <li>llvmPackages_13.clang (llvmPackages_13.libstdcxxClang)</li>
    <li>llvmPackages_13.libclang (llvmPackages_13.clang-unwrapped)</li>
    <li>llvmPackages_13.clangNoCompilerRt</li>
    <li>llvmPackages_13.clangNoCompilerRtWithLibc</li>
    <li>llvmPackages_13.clangNoLibc</li>
    <li>llvmPackages_13.clangNoLibcxx</li>
    <li>llvmPackages_13.clangUseLLVM</li>
    <li>llvmPackages_13.libcxxClang</li>
    <li>llvmPackages_13.libcxxStdenv</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>llvmPackages_13.clang-manpages</li>
    <li>llvmPackages_13.compiler-rt (llvmPackages_13.compiler-rt-libc ,llvmPackages_13.compiler-rt-no-libc)</li>
  </ul>
</details>
<details>
  <summary>6 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/development/compilers/llvm/13/lldb/default.nix:40:5:
```
   |
40 |     ./gnu-install-dirs.patch
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/development/compilers/llvm/13/clang/default.nix:37:7:
```
   |
37 |       ./purity.patch
   |       ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/development/compilers/llvm/13/clang/default.nix:108:5:
```
    |
108 |     installPhase = ''
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/development/compilers/llvm/13/lldb/default.nix:35:5:
```
   |
35 |     (runCommand "resource-dir.patch" {
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/development/compilers/llvm/13/clang/default.nix:104:5:
```
    |
104 |     buildPhase = ''
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/development/compilers/llvm/13/lldb/default.nix:34:5:
```
   |
34 |     ./procfs.patch
   |     ^
```
</li>
  </ul>
</details>

**Comment by risicle** [comment]
Darwin still seems pretty broken (tested macos 10.15), but `nixpkgs-review` was happy for me on nixos x86_64.

**Comment by primeos** [comment]
Yeah, we lack Darwin maintainers.

**Pull request merged**
