### PR TITLE
pythonPackages.pytest: 5.3.5 -> 5.4.1

### PR DESCRIPTION
**Pull request by sugar700**
###### Motivation for this change

Making pytest work in Python 3.9

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by xfix** [comment]
@GrahamcOfBorg build python27Packages.pytest python37Packages.pytest python38Packages.pytest python39Packages.pytest

**Comment by FRidh** [comment]
The Python packages set needs to be tested with this change.

**Comment by xfix** [comment]
Probably should be staging.

**Comment by FRidh** [comment]
Included in https://github.com/NixOS/nixpkgs/pull/83676

**Comment by FRidh** [comment]
Removed from #83676 due to too much breakage (sqlalchemy).

**Comment by grahamc** [comment]
@GrahamcOfBorg eval

**Comment by xfix** [comment]
This doesn't work, I'm experimenting currently.

**Comment by xfix** [comment]
@GrahamcOfBorg build python3Packages.sqlalchemy

**Comment by xfix** [comment]
Closing until it will become usable enough.

**Comment by jonringer** [comment]
> Closing until it will become usable enough (unfortunately GitHub doesn't allow marking a pull request as a draft).

It does, but only when you first create it. The convention currently is to change the title of the PR to: `[WIP] ...`

**Comment by drewrisinger** [comment]
> Closing until it will become usable enough (unfortunately GitHub doesn't allow marking a pull request as a draft).

It actually does, it just is kinda hidden. On the right sidebar, there's a "Convert to draft" or similar button, in small print.

**Comment by xfix** [comment]
@drewrisinger This functionality did not exist back when I closed this pull request, I believe it was added a few days afterwards.

**Comment by jonringer** [comment]
Thats correct, being able to convert to draft was a semi-recent addition

**Comment by drewrisinger** [comment]
Thanks, I stand corrected.

**Pull request closed without merging**
