### PR TITLE
light-locker (lockscreen for lightdm)

### PR DESCRIPTION
**Pull request by obadz**
cc @wkennington
cc @lethalman (I suspect something like that might also fixed the "Switch user" button in gnome-screensaver)

### CODE REVIEW

**Comment by obadz** [comment]
https://github.com/the-cavalry/light-locker/issues/66#issuecomment-133435272 explains a bit how light-locker works and why it's essential that we're able to run multiple X servers simultaneously.

**Comment by obadz** [comment]
Tip for those who want system-wide default to `xscreensaver` with ability to "switch user" without logging off:

```nix
      displayManager = {
        lightdm.enable = true;
        sessionCommands = ''
          ${pkgs.xorg.xrdb}/bin/xrdb -merge <(echo xscreensaver\*newLoginCommand: ${pkgs.lightdm}/bin/dm-tool switch-to-greeter)
          ${pkgs.xscreensaver}/bin/xscreensaver -no-splash &
          ${pkgs.xss-lock}/bin/xss-lock -- ${pkgs.xscreensaver}/bin/xscreensaver-command -lock &
        '';
      };
```

**Comment by ocharles** [comment]
It all looks good to me, I can't see anything that would break existing set ups. :+1:

**Comment by obadz** [comment]
Rebased to fix merge conflicts

**Comment by obadz** [comment]
cc @TimoMeijer @spacefrogg @wkennington

**Comment by obadz** [comment]
@ocharles has reviewed this change (thanks @ocharles).
Unless there are any further concerns, could we merge this change?

**Comment by spacefrogg** [comment]
Looks good to me.

Could you please reformat the commit subject lines properly (see [Nixpkgs manual](https://nixos.org/nixpkgs/manual))? Especially the latter is without much information.

**Comment by obadz** [comment]
@spacefrogg: is that better?

**Comment by spacefrogg** [comment]
Fine! Now you just have to catch the attention of somebody who has commit rights.

**Comment by ocharles** [comment]
Thanks!

**Comment by obadz** [comment]
Thanks Ollie!

**Pull request merged**
