### PR TITLE
nix_2_4: 2.4pre-rc1 -> 2.4

### PR DESCRIPTION
**Pull request by lovesegfault**
###### Motivation for this change
This is an offshoot of #144197 containing everything _except_ changing the
default Nix to 2.4, since that turned out to be quite tricky and there are
unresolved issues.

This does all the groundwork, without doing the actual switch.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by flokli** [comment]
I'd prefer if the regression of https://github.com/NixOS/nix/issues/5495 could be fixed in a 2.4.x point release, and we wait upgrading nixpkgs till that's ruled out, instead of having yet another `nix*` attribute that isn't compatible with all in nixpkgs.

**Comment by xaverdh** [comment]
Well `nix_2_4` is already in nixpkgs, this pr only bumps it, or do you mean introducing `nix_2_3`?

**Comment by thiagokokada** [comment]
> Well `nix_2_4` is already in nixpkgs, this pr only bumps it, or do you mean introducing `nix_2_3`?

BTW, #144197 also introduces it for those who need it. https://github.com/NixOS/nix/issues/5495 is not related to `nix_2_3` overrides AFAIK, it is related to specific to the basic eval errors test.

**Review by thiagokokada — COMMENTED** [review]
Result of `nixpkgs-review pr 144831` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>ovftool</li>
  </ul>
</details>
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>tests.nixos-functions.nixos-test</li>
    <li>tests.nixos-functions.nixosTest-test</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>66 packages built:</summary>
  <ul>
    <li>bundix</li>
    <li>cabal2nix</li>
    <li>cachix</li>
    <li>common-updater-scripts</li>
    <li>crate2nix</li>
    <li>crystal2nix</li>
    <li>dep2nix</li>
    <li>dydisnix</li>
    <li>fusionInventory</li>
    <li>go2nix</li>
    <li>haskellPackages.cabal2nix-unstable</li>
    <li>haskellPackages.cachix</li>
    <li>haskellPackages.hercules-ci-agent</li>
    <li>haskellPackages.hercules-ci-cli</li>
    <li>haskellPackages.hercules-ci-cnix-expr</li>
    <li>haskellPackages.hercules-ci-cnix-store</li>
    <li>haskellPackages.nix-paths</li>
    <li>haskellPackages.nvfetcher</li>
    <li>haskellPackages.update-nix-fetchgit</li>
    <li>hci</li>
    <li>hercules-ci-agent</li>
    <li>hubstaff</li>
    <li>libnixxml</li>
    <li>lispPackages.quicklisp-to-nix</li>
    <li>lispPackages.quicklisp-to-nix-system-info</li>
    <li>nix (nixStable ,nix_2_3)</li>
    <li>nix-bundle</li>
    <li>nix-direnv</li>
    <li>nix-doc</li>
    <li>nix-du</li>
    <li>nix-index</li>
    <li>nix-pin</li>
    <li>nix-plugins</li>
    <li>nix-prefetch</li>
    <li>nix-prefetch-bzr</li>
    <li>nix-prefetch-cvs</li>
    <li>nix-prefetch-docker</li>
    <li>nix-prefetch-git</li>
    <li>nix-prefetch-hg</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-prefetch-svn</li>
    <li>nix-serve</li>
    <li>nix-simple-deploy</li>
    <li>nix-template</li>
    <li>nix-update</li>
    <li>nix-update-source</li>
    <li>nixStatic</li>
    <li>nix_2_4</li>
    <li>nixos-generators</li>
    <li>nixos-option</li>
    <li>nixos-rebuild</li>
    <li>nixos-shell</li>
    <li>nixui</li>
    <li>nvfetcher</li>
    <li>prefetch-yarn-deps</li>
    <li>python38Packages.nix-kernel</li>
    <li>python38Packages.nixpkgs</li>
    <li>python38Packages.pythonix</li>
    <li>python39Packages.nix-kernel</li>
    <li>python39Packages.nixpkgs</li>
    <li>python39Packages.pythonix</li>
    <li>tests.trivial-builders.references</li>
    <li>update-nix-fetchgit</li>
    <li>vgo2nix</li>
    <li>vulnix</li>
    <li>yarn2nix</li>
  </ul>
</details>

Really strange this failure on`nixos-install-tools` :thinking: .

**Comment by thiagokokada** [comment]
Just saw this commit: https://github.com/Mic92/nixpkgs-review/commit/65107fd4548914ef77618e29e4517d88ce8ce721

So the `nixos-install-tools` failure should be fine.

**Comment by thiagokokada** [comment]
@lovesegfault Maybe we could have a PR with just the nix 2.4 bump and no introduction of `nix_2_3`. This would probably be faster to merge, and leave the #144197 introducing both `nix = nix_2_4` and the introduction of `nix_2_3`.

WDYT?

**Comment by lovesegfault** [comment]
> @lovesegfault Maybe we could have a PR with just the nix 2.4 bump and no introduction of `nix_2_3`. This would probably be faster to merge, and leave the #144197 introducing both `nix = nix_2_4` and the introduction of `nix_2_3`.
> 
> WDYT?

I'm going to keep the introduction of `nix_2_3` in this one, but remove all of the commits pinning pkgs to it.

So all this will do is:
1. Update `nix_2_4` with some fixes for static
2. Create `nix_2_3`

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 144831` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>57 packages built:</summary>
  <ul>
    <li>bundix</li>
    <li>cabal2nix</li>
    <li>cachix</li>
    <li>common-updater-scripts</li>
    <li>crate2nix</li>
    <li>crystal2nix</li>
    <li>dep2nix</li>
    <li>dydisnix</li>
    <li>fusionInventory</li>
    <li>go2nix</li>
    <li>hci</li>
    <li>hercules-ci-agent</li>
    <li>hubstaff</li>
    <li>libnixxml</li>
    <li>lispPackages.quicklisp-to-nix</li>
    <li>lispPackages.quicklisp-to-nix-system-info</li>
    <li>nix (nixStable ,nix_2_3)</li>
    <li>nix-binary-cache</li>
    <li>nix-bundle</li>
    <li>nix-direnv</li>
    <li>nix-doc</li>
    <li>nix-du</li>
    <li>nix-index</li>
    <li>nix-pin</li>
    <li>nix-plugins</li>
    <li>nix-prefetch</li>
    <li>nix-prefetch-bzr</li>
    <li>nix-prefetch-cvs</li>
    <li>nix-prefetch-docker</li>
    <li>nix-prefetch-git</li>
    <li>nix-prefetch-hg</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-prefetch-svn</li>
    <li>nix-serve</li>
    <li>nix-simple-deploy</li>
    <li>nix-template</li>
    <li>nix-update</li>
    <li>nix-update-source</li>
    <li>nix_2_4 (nixFlakes)</li>
    <li>nixStatic</li>
    <li>nixos-generators</li>
    <li>nixos-option</li>
    <li>nixos-rebuild</li>
    <li>nixos-shell</li>
    <li>nixui</li>
    <li>nvfetcher</li>
    <li>prefetch-yarn-deps</li>
    <li>python38Packages.nix-kernel</li>
    <li>python38Packages.nixpkgs</li>
    <li>python38Packages.pythonix</li>
    <li>python39Packages.nix-kernel</li>
    <li>python39Packages.nixpkgs</li>
    <li>python39Packages.pythonix</li>
    <li>update-nix-fetchgit</li>
    <li>vgo2nix</li>
    <li>vulnix</li>
    <li>yarn2nix</li>
  </ul>
</details>

**Review by thiagokokada — APPROVED** [review]

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 144831` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>fusionInventory</li>
    <li>nixui</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>nix_2_4</li>
  </ul>
</details>
<details>
  <summary>55 packages built:</summary>
  <ul>
    <li>bundix</li>
    <li>cabal2nix</li>
    <li>cachix</li>
    <li>crate2nix</li>
    <li>crystal2nix</li>
    <li>dep2nix</li>
    <li>dydisnix</li>
    <li>go2nix</li>
    <li>haskellPackages.cabal2nix-unstable</li>
    <li>haskellPackages.cachix</li>
    <li>haskellPackages.hercules-ci-agent</li>
    <li>haskellPackages.hercules-ci-cli</li>
    <li>haskellPackages.hercules-ci-cnix-expr</li>
    <li>haskellPackages.hercules-ci-cnix-store</li>
    <li>haskellPackages.nix-paths</li>
    <li>haskellPackages.nvfetcher</li>
    <li>haskellPackages.update-nix-fetchgit</li>
    <li>hci</li>
    <li>hercules-ci-agent</li>
    <li>libnixxml</li>
    <li>nix (nixStable ,nixStatic ,nix_2_3)</li>
    <li>nix-bundle</li>
    <li>nix-direnv</li>
    <li>nix-doc</li>
    <li>nix-du</li>
    <li>nix-index</li>
    <li>nix-pin</li>
    <li>nix-plugins</li>
    <li>nix-prefetch</li>
    <li>nix-prefetch-bzr</li>
    <li>nix-prefetch-cvs</li>
    <li>nix-prefetch-docker</li>
    <li>nix-prefetch-git</li>
    <li>nix-prefetch-hg</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-prefetch-svn</li>
    <li>nix-serve</li>
    <li>nix-simple-deploy</li>
    <li>nix-template</li>
    <li>nix-update</li>
    <li>nix-update-source</li>
    <li>nixos-generators</li>
    <li>nixos-option</li>
    <li>nixos-shell</li>
    <li>nvfetcher</li>
    <li>python38Packages.nix-kernel</li>
    <li>python38Packages.nixpkgs</li>
    <li>python38Packages.pythonix</li>
    <li>python39Packages.nix-kernel</li>
    <li>python39Packages.nixpkgs</li>
    <li>python39Packages.pythonix</li>
    <li>update-nix-fetchgit</li>
    <li>vgo2nix</li>
    <li>vulnix</li>
    <li>yarn2nix</li>
  </ul>
</details>

**Comment by thiagokokada** [comment]
```console
$ nix-build -A pkgsStatic.nix_2_4
/nix/store/66j6dzyw8ldm7c39fnizj0gmh7m8vvg4-nix-static-x86_64-unknown-linux-musl-2.4
```

:+1:

**Comment by lovesegfault** [comment]
I'm going to land this since it's now a very inoffensive patch

**Pull request merged**
