### PR TITLE
pythonPackages.ndjson: init at 0.3.1

### PR DESCRIPTION
**Pull request by nbke**
###### Motivation for this change
labelbox 2.4.6 depends on ndjson

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Why is there a 0.3.1 on pypi when there is only 0.3.0 on GitHub?

**Comment by nbke** [comment]
Version 0.3.1 includes a typo fix (PR https://github.com/rhgrant10/ndjson/pull/3). No code was changed between v0.3.0 and v0.3.1.
I can switch to v0.3.0 if preferred.

**Comment by SuperSandro2000** [comment]
> I can switch to v0.3.0 if preferred.

I am not sure where I read it but I think fetching from GitHub is preferred if available. If you would switch to GitHub tags it would be clearer and we would update when 0.3.1 is tagged.

Right now it kinda looks fishy if 0.3.1 is on pypi but not GitHub but I am not sure how this is handled. Just my opinion.

**Comment by nbke** [comment]
The tests are included in the package from PyPi.
@FRidh @jonringer Do you prefer `fetchPypi` or `fetchFromGitHub`?

**Comment by SuperSandro2000** [comment]
> The tests are included in the package from PyPi.
> Do you prefer `fetchPypi` or `fetchFromGitHub`?

Then you can use fetchPypi.

**Comment by SuperSandro2000** [comment]
This package is already in master. If you want to add changes please modify this PR or open a new one.

**Pull request closed without merging**
