### PR TITLE
libarchive: fix build

### PR DESCRIPTION
**Pull request by marsam**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by emilazy** [comment]
cc @jtojnar @Ericson2314 were talking about this on `#nixos-dev`

Do you know have any idea what a fix would be to make this work with `autoreconfHook`? Presumably some packages might need patching due to the unavailability of a binary `configure` generated with an older version of autoconf.

**Comment by Ericson2314** [comment]
Yeah I am curious what the underlying issue is, and would rather fix that if possible, as I saw it crop up with other packages.

**Comment by jtojnar** [comment]
I agree but libarchive is currently blocking staging CI so I would merge this as is for now.

**Comment by jtojnar** [comment]
Bisection leads me to

```commit c71ab32a678a98ce1ec069956bc55d6ea606f55c
Author: John Ericson <John.Ericson@Obsidian.Systems>
Date:   Mon Apr 27 22:39:58 2020 -0400

    pkg-config-wrapper: Init
    
    This fixes longstanding build issues

 pkgs/build-support/pkg-config-wrapper/add-flags.sh |  12 +++
 pkgs/build-support/pkg-config-wrapper/default.nix  | 117 +++++++++++++++++++++
 .../pkg-config-wrapper/pkg-config-wrapper.sh       |  21 ++++
 .../build-support/pkg-config-wrapper/setup-hook.sh |  29 +++++
 .../python-modules/pkgconfig/default.nix           |   2 +-
 pkgs/development/tools/misc/pkg-config/default.nix |   2 -
 .../tools/misc/pkg-config/setup-hook.sh            |   6 --
 pkgs/test/cross/default.nix                        |  14 +++
 pkgs/top-level/all-packages.nix                    |  17 ++-
 9 files changed, 208 insertions(+), 12 deletions(-)
 create mode 100644 pkgs/build-support/pkg-config-wrapper/add-flags.sh
 create mode 100644 pkgs/build-support/pkg-config-wrapper/default.nix
 create mode 100644 pkgs/build-support/pkg-config-wrapper/pkg-config-wrapper.sh
 create mode 100644 pkgs/build-support/pkg-config-wrapper/setup-hook.sh
 delete mode 100644 pkgs/development/tools/misc/pkg-config/setup-hook.sh
```

**Comment by Ericson2314** [comment]
Ah! Well, then it's on me to fix :)

**Comment by Ericson2314** [comment]
Found the issue: my wrapper left the pkg-config `share/` behind. Fixing now.

**Comment by Ericson2314** [comment]
Got it, see https://github.com/NixOS/nixpkgs/pull/88518

**Pull request closed without merging**
