### PR TITLE
ocamlPackages: fix cross compilation for some packages

### PR DESCRIPTION
**Pull request by anmonteiro**
###### Motivation for this change
follow up to #145033 

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alyssais** [comment]
How are you testing this?  If I try to build e.g. `pkgsCross.aarch64-multiplatform.ocamlPackages.astring`, it doesn't work because OCaml fails to build.

**Comment by anmonteiro** [comment]
I have an OCaml cross compiler in my overlays. I didn’t upstreamed it because it’s experimental and not officially supported.

**Comment by alyssais** [comment]
I encourage you to try upstreaming it — an experimental cross compiler is better than no cross compiler.  Otherwise, nobody apart from you actually benefits from these fixes.

**Comment by symphorien** [comment]
Hum pkgsStatic.ocamlPackages.ocamlgraph works for example, but I fail to test this PR with pkgStatic because of opaline.
I went a bit further but it's not enough:
```diff
diff --git a/pkgs/development/ocaml-modules/topkg/default.nix b/pkgs/development/ocaml-modules/topkg/default.nix
index 97052115da6..3f477e085bd 100644
--- a/pkgs/development/ocaml-modules/topkg/default.nix
+++ b/pkgs/development/ocaml-modules/topkg/default.nix
@@ -35,12 +35,12 @@ stdenv.mkDerivation rec {
     inherit (param) sha256;
   };
 
-  nativeBuildInputs = [ ocaml findlib ocamlbuild ];
+  nativeBuildInputs = [ ocaml findlib ocamlbuild opaline ];
   propagatedBuildInputs = param.propagatedBuildInputs or [];
 
   buildPhase = "${run} build";
   createFindlibDestdir = true;
-  installPhase = "${opaline}/bin/opaline -prefix $out -libdir $OCAMLFIND_DESTDIR";
+  installPhase = "opaline -prefix $out -libdir $OCAMLFIND_DESTDIR";
 
   passthru = { inherit run; };
 

```

**Comment by superherointj** [comment]
Most changes in this PR have already been integrated. So I'm closing this as it is very outdated by now.

**Pull request closed without merging**
