### PR TITLE
keybase{,-gui}: 3.0.0 -> 4.1.0

### LINKED ISSUE #64248: Keybase out of date, KBFS severely out of date
## Issue description
Hi, I'm a Keybase developer and some of our users reported that the Nix packages were out of date.

Keybase 4.1.0 was released a while ago, so I believe these need to be updated: https://github.com/NixOS/nixpkgs/tree/master/pkgs/tools/security/keybase.

Additionally, the KBFS nix should point to the new remote, `github.com/keybase/client` with `subPackages = [ "go/kbfs/kbfsfuse" "go/kbfs/kbfsgit/git-remote-keybase" ]`, and be on the same version as the other packages (4.1.0).

Please let me know if you have any questions, happy to answer! Thanks.

### Steps to reproduce
N/A

## Technical details
N/A

### PR DESCRIPTION
**Pull request by das-g**
###### Motivation for this change

Fix #64248 for stable branch by back-porting #60872, #62220 & #64275

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by worldofpeace** [comment]
KBFS still isn't up to date (https://github.com/NixOS/nixpkgs/issues/64248)  so I don't think a backport would appropriate yet.

**Comment by das-g** [comment]
> KBFS still isn't up to date (#64248) so I don't think a backport would appropriate yet.

Is it up-to-date on master?

**Comment by worldofpeace** [comment]
No it isn't, see this comment at https://github.com/NixOS/nixpkgs/issues/50999#issuecomment-461852250 and it was also mentioned in https://github.com/NixOS/nixpkgs/issues/64248#issue-463753717

> Additionally, the KBFS nix should point to the new remote, github.com/keybase/client with subPackages = [ "go/kbfs/kbfsfuse" "go/kbfs/kbfsgit/git-remote-keybase" ], and be on the same version as the other packages (4.1.0).

**Comment by das-g** [comment]
Does that mean that #64275 was merged prematurely?

**Comment by worldofpeace** [comment]
> Does that mean that #64275 was merged prematurely?

Perhaps, I've opened  #64377

**Comment by jonringer** [comment]
I apologize, wasn't aware of this package. 

Future facing, #64377 imports the keybase package as part of kbfs, which should fix the issue of nix-review not picking it up. Thank you @worldofpeace for your attention to detail :)

**Comment by worldofpeace** [comment]
> I apologize, wasn't aware of this package.
> 
> Future facing, #64377 imports the keybase package as part of kbfs, which should fix the issue of nix-review not picking it up. Thank you @worldofpeace for your attention to detail :)

You're welcome. And I think because `kbfs` uses `keybase` `src` it should cause a rebuild so maybe `nix-review` will pick it up.

**Comment by worldofpeace** [comment]
Ok this should be ready for someone to test it on stable.

**Comment by kalbasit** [comment]
@worldofpeace I'm actually running unstable, I won't be able to test beyond simply building it. @Ma27 maybe?

**Comment by das-g** [comment]
I'm on stable (NixOS 19.03).

Can you give instructions on how to go about to test this? As a service is involved, I guess I'd have to install the to-be-tested version system-wide rather than simply run it with `nix-shell` or `nix run`.

**Comment by kalbasit** [comment]
> I'm on stable (NixOS 19.03).
> 
> Can you give instructions on how to go about to test this? As a service is involved, I guess I'd have to install the to-be-tested version system-wide rather than simply run it with `nix-shell` or `nix run`.

Precisely! I would point my nixpkgs to this specific PR and rebuild your system with Keybase and kbfs enabled.

**Comment by das-g** [comment]
I've tested as follows:

### preparation

- Verify I'm on the right commit (d365f15ed644f5dfe8dd5098eed6fe87f0338fa1):
  ```
  $ (cd ~/dev/nixos/nixpkgs/ ; git rev-parse HEAD)
  d365f15ed644f5dfe8dd5098eed6fe87f0338fa1
  ```
- Modify `/etc/nixos/configuration.nix` to have
  ```
  services.keybase.enable = true;
  services.kbfs.enable = true;
  # ...
  environment.systemPackages = with pkgs; [
    # ...
    keybase
  ];
  ```
- try to switch with
  ```bash
  sudo nixos-rebuild test -I nixpkgs=~/dev/nixos/nixpkgs/ --upgrade
  ```

That didn't succeed.

<details><summary>output (click to expand)</summary>

```
unpacking channels...
building Nix...
building the system configuration...
stopping the following units: accounts-daemon.service, alsa-store.service, audit.service, bluetooth.service, bolt.service, colord.service, cpufreq.service, cups.service, docker.service, docker.socket, kmod-static-nodes.service, network-link-vboxnet0.service, network-local-commands.service, network-manager.service, network-setup.service, nix-daemon.service, nix-daemon.socket, nscd.service, postgresql.service, rngd.service, rtkit-daemon.service, sshd.service, systemd-machined.service, systemd-modules-load.service, systemd-sysctl.service, systemd-timesyncd.service, systemd-tmpfiles-clean.timer, systemd-tmpfiles-setup-dev.service, systemd-udev-trigger.service, systemd-udevd-control.socket, systemd-udevd-kernel.socket, systemd-udevd.service, udisks2.service, upower.service, vboxnet0.service, wpa_supplicant.service
NOT restarting the following changed units: display-manager.service, getty@tty1.service, systemd-backlight@backlight:intel_backlight.service, systemd-backlight@leds:tpacpi::kbd_backlight.service, systemd-fsck@dev-disk-by\x2duuid-37BB\x2d937E.service, systemd-journal-flush.service, systemd-logind.service, systemd-random-seed.service, systemd-remount-fs.service, systemd-tmpfiles-setup.service, systemd-udev-settle.service, systemd-update-utmp.service, systemd-user-sessions.service, user-runtime-dir@1000.service, user@1000.service
activating the configuration...
removing user ‘sshd’
setting up /etc...
removing obsolete symlink ‘/etc/ssh/moduli’...
removing obsolete symlink ‘/etc/ssh/sshd_config’...
removing obsolete symlink ‘/etc/pam.d/sshd’...
restarting systemd...
reloading user units for das-g...
setting up tmpfiles
reloading the following units: dbus.service, dev-hugepages.mount, dev-mqueue.mount, firewall.service, sys-fs-fuse-connections.mount, sys-kernel-debug.mount
restarting the following units: network-addresses-vboxnet0.service, polkit.service, systemd-journald.service
Job for network-addresses-vboxnet0.service failed because the control process exited with error code.
See "systemctl status network-addresses-vboxnet0.service" and "journalctl -xe" for details.
starting the following units: accounts-daemon.service, alsa-store.service, audit.service, bluetooth.service, bolt.service, colord.service, cpufreq.service, cups.service, docker.socket, kmod-static-nodes.service, network-link-vboxnet0.service, network-local-commands.service, network-manager.service, network-setup.service, nix-daemon.socket, nscd.service, postgresql.service, rngd.service, rtkit-daemon.service, systemd-machined.service, systemd-modules-load.service, systemd-sysctl.service, systemd-timesyncd.service, systemd-tmpfiles-clean.timer, systemd-tmpfiles-setup-dev.service, systemd-udev-trigger.service, systemd-udevd-control.socket, systemd-udevd-kernel.socket, udisks2.service, upower.service, vboxnet0.service, wpa_supplicant.service
Job for network-link-vboxnet0.service failed because the control process exited with error code.
See "systemctl status network-link-vboxnet0.service" and "journalctl -xe" for details.
the following new units were started: NetworkManager-dispatcher.service, systemd-hostnamed.service
warning: the following units failed: network-addresses-vboxnet0.service, network-link-vboxnet0.service

● network-addresses-vboxnet0.service - Address configuration of vboxnet0
   Loaded: loaded (/nix/store/fdy5ga790g4ridaf7dpm9za3l6ypbvaa-unit-network-addresses-vboxnet0.service/network-addresses-vboxnet0.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2019-07-14 15:10:57 CEST; 1s ago
  Process: 4408 ExecStop=/nix/store/agfhqiv3vniy8bqlpxvfy3gzlsc41inh-unit-script-network-addresses-vboxnet0-pre-stop (code=exited, status=0/SUCCESS)
  Process: 4476 ExecStart=/nix/store/9m4zjwp20vgfjhs0jm1qs0lqr0mmlx8a-unit-script-network-addresses-vboxnet0-start (code=exited, status=1/FAILURE)
 Main PID: 4476 (code=exited, status=1/FAILURE)

Jul 14 15:10:57 nixos systemd[1]: Starting Address configuration of vboxnet0...
Jul 14 15:10:57 nixos 9m4zjwp20vgfjhs0jm1qs0lqr0mmlx8a-unit-script-network-addresses-vboxnet0-start[4476]: adding address 192.168.56.1/24... 'ip addr add 192.168.56.1/24 dev vboxnet0' failed: Cannot find device "vboxnet0"
Jul 14 15:10:57 nixos systemd[1]: network-addresses-vboxnet0.service: Main process exited, code=exited, status=1/FAILURE
Jul 14 15:10:57 nixos systemd[1]: network-addresses-vboxnet0.service: Failed with result 'exit-code'.
Jul 14 15:10:57 nixos systemd[1]: Failed to start Address configuration of vboxnet0.

● network-link-vboxnet0.service - Link configuration of vboxnet0
   Loaded: loaded (/nix/store/px0cd8sni5ppcdmrcnk6yiqghndfyv2r-unit-network-link-vboxnet0.service/network-link-vboxnet0.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2019-07-14 15:10:57 CEST; 1s ago
  Process: 4489 ExecStart=/nix/store/605c5v3wfrh93nw003irxl3hxpz0yc09-unit-script-network-link-vboxnet0-start (code=exited, status=1/FAILURE)
 Main PID: 4489 (code=exited, status=1/FAILURE)

Jul 14 15:10:57 nixos systemd[1]: Starting Link configuration of vboxnet0...
Jul 14 15:10:57 nixos 605c5v3wfrh93nw003irxl3hxpz0yc09-unit-script-network-link-vboxnet0-start[4489]: Configuring link...
Jul 14 15:10:57 nixos 605c5v3wfrh93nw003irxl3hxpz0yc09-unit-script-network-link-vboxnet0-start[4489]: bringing up interface... Cannot find device "vboxnet0"
Jul 14 15:10:57 nixos 605c5v3wfrh93nw003irxl3hxpz0yc09-unit-script-network-link-vboxnet0-start[4489]: failed
Jul 14 15:10:57 nixos systemd[1]: network-link-vboxnet0.service: Main process exited, code=exited, status=1/FAILURE
Jul 14 15:10:57 nixos systemd[1]: network-link-vboxnet0.service: Failed with result 'exit-code'.
Jul 14 15:10:57 nixos systemd[1]: Failed to start Link configuration of vboxnet0.
warning: error(s) occurred while switching to the new configuration
```

</details>

So I did
```bash
sudo nixos-rebuild boot -p test -I nixpkgs=~/dev/nixos/nixpkgs/
```
and then rebooted into the resulting profile.

### tests done
(after rebooting into the `test` profile)

- [x] check that `keybase --version` reports 4.1.0
- [x] check that `keybase` without arguments lists usage info
- [x] started keybase-gui (as I had forgotten to add it to the `configuration.nix`, through `nix run -f ~/dev/nixos/nixpkgs/ keybase-gui -c keybase-gui`)
- [x] check that keybase-gui reports version 4.1.0-something
- [x] clicked around in GUI so see whether things seem to work
- [x] check whether the content I had stored in by keybase account is available at `~/keybase`

:+1:

**Comment by worldofpeace** [comment]
Sounds sufficiently tested, merging.

**Pull request merged**
