### PR TITLE
intltool: refactor

### PR DESCRIPTION
**Pull request by codyopel**

### CODE REVIEW

**Comment by vcunat** [comment]
I guess you know that most of the changed parts were generated from ``default.upstream``? @7c6f434c should know more about it.

**Comment by wkennington** [comment]
Yeah, I'm aware but not really sure how I feel about it :/. We probably need to discuss that style of automatic updating and packaging.

**Comment by codyopel** [comment]
I suppose, but I can't haven't been able to completely figure out how `update-walker.sh` is supposed to be called and not many build make use of it.
https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/upstream-updater/update-walker.sh

**Comment by vcunat** [comment]
I've never used it myself; I just know it exists. A few other people also have their own generic updater scripts, and there's also nixpkgs monitor.

Perhaps one day we might agree on a common metadata format for these to unify what's committed into nixpkgs, i.e. standardize format that specifies how to determine whether an update is available, e.g. skipping unstable/testing updates and verifying crypto-signatures. Then we could have reliable automatic update detection for important packages.

**Pull request merged**
