### PR TITLE
outguess: init at 0.2.2

### PR DESCRIPTION
**Pull request by siraben**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 101824` [1](https://github.com/Mic92/nixpkgs-review)

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 101824` [1](https://github.com/Mic92/nixpkgs-review)

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 101824` [1](https://github.com/Mic92/nixpkgs-review)

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 101824` [1](https://github.com/Mic92/nixpkgs-review)

**Comment by doronbehar** [comment]
Result of `nixpkgs-review pr 101824` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>outguess</li>
  </ul>
</details>

**Comment by doronbehar** [comment]
```
  make -C ./jpeg-6b-steg -f makefile.ansi 'CC=gcc -pipe -Wall -funroll-all-loops' CFLAGS=-DHAVE_STDC_HEADERS libjpeg.a
  make[1]: Entering directory '/build/source/jpeg-6b-steg'
  echo You must prepare a system-dependent jconfig.h file.
  You must prepare a system-dependent jconfig.h file.
  echo Please read the installation directions in install.doc.
  Please read the installation directions in install.doc.
  exit 1
  make[1]: *** [makefile.ansi:124: jconfig.h] Error 1
  make[1]: Leaving directory '/build/source/jpeg-6b-steg'
  make: *** [Makefile:50: jpeg-6b-steg/libjpeg.a] Error 2
```

**Pull request closed without merging**
