### PR TITLE
python3Packages.plexwebsocket: 0.0.12 -> 0.0.13, python3Packages.plexapi: 4.5.0 -> 4.5.1

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 0.0.13

Change log: https://github.com/jjlawren/python-plexwebsocket/releases/tag/v0.0.13

Update to latest upstream release 4.5.1 

Change log:https://github.com/pkkid/python-plexapi/releases/tag/4.5.1

Home Assistant's tests are not enabled as they don't pass.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Failures:

```bash
warning: ignoring the user-specified setting 'sandbox', because it is a restricted setting and you are not a trusted user
builder for '/nix/store/r0rwax3ag7n93vml5zqpv9xk9rvnprsi-homeassistant-2021.3.4.drv' failed with exit code 1; last 10 log lines:
  tests/components/shell_command/test_init.py::test_do_no_run_forever[pyloop]
    /nix/store/5470xw15wnn972ap0c4f7q642z4nvh6f-python3-3.8.8/lib/python3.8/asyncio/unix_events.py:917: RuntimeWarning: A loop is being detached from a child watcher with pending handlers
      warnings.warn(
  
  -- Docs: https://docs.pytest.org/en/stable/warnings.html
  =========================== short test summary info ============================
  FAILED tests/components/sonos/test_init.py::test_creating_entry_sets_up_media_player[pyloop]
  ERROR tests/components/sonos/test_media_player.py
  ERROR tests/components/sonos/test_plex_playback.py
```

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 118436` at 9bfee1f9 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>home-assistant</li>
  </ul>
</details>
<details>
  <summary>4 packages built successfully:</summary>
  <ul>
    <li>python38Packages.plexapi</li>
    <li>python38Packages.plexwebsocket</li>
    <li>python39Packages.plexapi</li>
    <li>python39Packages.plexwebsocket</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement.

**Comment by mweinelt** [comment]
> Failures:
> 
> ```shell
> warning: ignoring the user-specified setting 'sandbox', because it is a restricted setting and you are not a trusted user
> builder for '/nix/store/r0rwax3ag7n93vml5zqpv9xk9rvnprsi-homeassistant-2021.3.4.drv' failed with exit code 1; last 10 log lines:
>   tests/components/shell_command/test_init.py::test_do_no_run_forever[pyloop]
>     /nix/store/5470xw15wnn972ap0c4f7q642z4nvh6f-python3-3.8.8/lib/python3.8/asyncio/unix_events.py:917: RuntimeWarning: A loop is being detached from a child watcher with pending handlers
>       warnings.warn(
>   
>   -- Docs: https://docs.pytest.org/en/stable/warnings.html
>   =========================== short test summary info ============================
>   FAILED tests/components/sonos/test_init.py::test_creating_entry_sets_up_media_player[pyloop]
>   ERROR tests/components/sonos/test_media_player.py
>   ERROR tests/components/sonos/test_plex_playback.py
> ```

Scroll way up, this only a very slim summary of what is actually going wrong. The actual test failure is far more interesting.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 118436` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>home-assistant</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python38Packages.plexapi</li>
    <li>python38Packages.plexwebsocket</li>
    <li>python39Packages.plexapi</li>
    <li>python39Packages.plexwebsocket</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
Is this ready for review?

**Comment by fabaff** [comment]
With `home-assistant-2021.3.4` I get:

```bash
warning: ignoring the user-specified setting 'sandbox', because it is a restricted setting and you are not a trusted user
builder for '/nix/store/nh0xq1n9drsgvzasrdhnxll8py9lp2r6-homeassistant-2021.3.4.drv' failed with exit code 1; last 10 log lines:
  
  -- Docs: https://docs.pytest.org/en/stable/warnings.html
  =========================== short test summary info ============================
  FAILED tests/components/cast/test_home_assistant_cast.py::test_remove_entry[pyloop]
  FAILED tests/components/cast/test_init.py::test_creating_entry_sets_up_media_player[pyloop]
  FAILED tests/components/sonos/test_init.py::test_creating_entry_sets_up_media_player[pyloop]
  ERROR tests/components/cast/test_media_player.py
  ERROR tests/components/sonos/test_media_player.py
  ERROR tests/components/sonos/test_plex_playback.py
  = 3 failed, 7435 passed, 5 skipped, 425 warnings, 3 errors in 1221.69s (0:20:21) =
```

The updates are part of `2021.4.0`,  thus perhaps this version is needed for the tests to pass.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 118436` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>home-assistant</li>
    <li>python38Packages.plexapi</li>
    <li>python38Packages.plexwebsocket</li>
    <li>python39Packages.plexapi</li>
    <li>python39Packages.plexwebsocket</li>
  </ul>
</details>

**Pull request merged**
