### PR TITLE
cri-o: 1.17.3 -> 1.18.0

### PR DESCRIPTION
**Pull request by saschagrunert**
###### Motivation for this change

Update CRI-O to the latest version.

This won't build because I need at least go 1.13 for this. @zowoq @marsam @vdemeester do you know if I can enforce a specific go version for `buildGoPackage`?

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by saschagrunert** [comment]
@GrahamcOfBorg build cri-o

**Comment by vdemeester** [comment]
@saschagrunert Also I can see that `cri-o` switch to using go modules, so we should be able to use `buildGoModule` in this derivation, shouldn't we ? :angel:

**Comment by marsam** [comment]
you may need to remove this line: https://github.com/NixOS/nixpkgs/blob/f02a1293138a01fb5cda53336389aa79f1268c19/pkgs/top-level/all-packages.nix#L23310

**Comment by Mic92** [comment]
@GrahamcOfBorg eval

**Comment by jonringer** [comment]
@GrahamcOfBorg eval

**Comment by zowoq** [comment]
@saschagrunert Do you want to add the commit from #85682 to this PR?

**Comment by srhb** [comment]
> do you know if I can enforce a specific go version for buildGoPackage?
Easiest is probably `buildGo113Package` (or `buildGo113Module` if you go down that route)

**Comment by saschagrunert** [comment]
Thank you for all of your hints! I picked in the changes of  #85682, using now `buildGoModule` and switched to the standard go version as well.

@GrahamcOfBorg eval

**Comment by zowoq** [comment]
I don't think `buildGoModule` is needed as the deps are already vendored?

**Comment by vdemeester** [comment]
> I don't think `buildGoModule` is needed as the go deps are already vendored?

Right, I *thought* of that too *after* commenting :sweat_smile:. With go 1.14, `go build` will use the `vendor` folder if it's present (à-la `go build -mod=vendor`). I wonder if long-term we should have only one `buildGo…` function that would support *all the thing* :angel:.

**Comment by saschagrunert** [comment]
> I don't think `buildGoModule` is needed as the go deps are already vendored?

Yeah but since `buildGoPackage` is explicitly mentioned as "legacy" I still would like to stick to the new way. WDYT?

**Comment by vdemeester** [comment]
> > I don't think `buildGoModule` is needed as the go deps are already vendored?
> 
> Yeah but since `buildGoPackage` is explicitly mentioned as "legacy" I still would like to stick to the new way. WDYT?

Maybe but I don't think we should hold merge this bump for that :angel: (it could be done as a follow-up)

**Comment by saschagrunert** [comment]
Okay cool I reverted some of my changes and sticked to `buildGoPackage`

**Review by zowoq — APPROVED** [review]

**Comment by zowoq** [comment]
Could a committer merge this please? cc @marsam @Mic92

**Pull request merged**
