### PR TITLE
R: 3.2.4 -> 3.3.2

### PR DESCRIPTION
**Pull request by jbedo**
###### Motivation for this change

R 3.2 is quite old and a lot of commonly used packages are not available or obsolete. This updates R to the latest minor version and updates the CRAN and bioconductor packages.

###### Things done

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
Is it okay to update these and not the other package sets? Hopefully! :)

Unfortunately this fails the ['test-evaluation.nix' check](https://nixos.org/nixpkgs/manual/#testing-if-the-nix-expression-could-be-evaluated), looks like default.nix needs to be updated as well.  Not sure if that just means removing references to no-longer-existing packages or if there's more to it?

**Comment by yamad** [comment]
+1. Resolves issues with this older pull request https://github.com/NixOS/nixpkgs/pull/20704 .

The "--with-system*" configure flags are deprecated in 3.3.2, so it makes sense to remove them from the `default.nix`.

This builds a functioning R on my macOS 10.11.6 machine, although this update does not solve what seems to be a longer standing issue that no interactive graphical device (x11, quartz,...) is available in the macOS build.

**Comment by jbedo** [comment]
Thanks guys for the feedback. I've removed the --with-system flags and fixed the errors found by test-evaluation.nix, including a naming clash between the R package "import" and the import keyword in nix (fixed in the generation script).

**Comment by domenkozar** [comment]
Note that we branch-off 17.03 today, so let's test and merge this. @lukego can you test this work for you?

**Comment by lukego** [comment]
@domenkozar Trying to test now. Just at the moment running `pkgs/developer/r-modules$ nix-build test-evaluation.nix` is hanging with hundreds/thousands of messages like:

```
...
download-from-binary-cache.pl: still waiting for ‘https://cache.nixos.org/w7vrygwn1z466bgrafsjvprkxbalg4bz.narinfo’ after 5 seconds...
download-from-binary-cache.pl: still waiting for ‘https://cache.nixos.org/yh6hz97k25cjcbks0g2yvx49ay6z23r8.narinfo’ after 5 seconds...
download-from-binary-cache.pl: still waiting for ‘https://cache.nixos.org/l760g144v984jbm3kinxhl44693x3rm6.narinfo’ after 5 seconds...
download-from-binary-cache.pl: still waiting for ‘https://cache.nixos.org/rrdzdk8ch21jvpfdxjngc9n49wgmxi4r.narinfo’ after 5 seconds...
download-from-binary-cache.pl: still waiting for ‘https://cache.nixos.org/s8yvbk11xg0mrj8k6gw8k8ig5q6ag1b7.narinfo’ after 5 seconds...
...
```

**Comment by domenkozar** [comment]
@lukego Nix should get 404 for most of those links and fallback to source building after some seconds. Does it not?

**Comment by lukego** [comment]
@domenkozar No, on my NixOS machine (`lugano-3.snabb.co`) it seems to be hanging for minutes at least after printing those messages. I am trying on my OSX machine now instead.

**Comment by domenkozar** [comment]
Try adding `--option connect-timeout 5` to the cli args

**Comment by lukego** [comment]
@domenkozar No difference. Can Hydra test this instead somehow instead of depending on my private tests?

**Comment by domenkozar** [comment]
Will do that after lunch

**Comment by vcunat** [comment]
R builds OK for me, but I haven't tested it except for starting up the interpreter.

**Comment by lukego** [comment]
I am a relative R newbie. I have some software I have developed with Rstudio that I want to deploy with nix, but I don't know exactly what versions I depend on, and I am happy if nixpkgs just picks up the latest versions and then I make that work for me.

**Comment by domenkozar** [comment]
http://hydra.nixos.org/jobset/nixpkgs/r-updates#tabs-evaluations is evaluating /cc @peti

**Comment by domenkozar** [comment]
It's almost half way through and most of packages compile. We can fix those that don't in the next month :) Thanks!

**Pull request merged**
