### PR TITLE
ladybird: 0-unstable-2024-07-11 -> 0-unstable-2024-08-12

### PR DESCRIPTION
**Pull request by fgaz**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by qbit** [comment]
Builds fine but doesn't seem to load any pages:

```
VERIFICATION FAILED: m_default_font at /build/source/Ladybird/FontPlugin.cpp:45
/nix/store/yk44cnbs3gpa5hpaxml3gbw2jjr04knh-ladybird-0-unstable-2024-08-12/libexec/../lib/liblagom-ak.so.0(ak_verification_failed+0x83) [0x7fd510845633]
/nix/store/yk44cnbs3gpa5hpaxml3gbw2jjr04knh-ladybird-0-unstable-2024-08-12/libexec/WebContent() [0x50a0b8]
/nix/store/yk44cnbs3gpa5hpaxml3gbw2jjr04knh-ladybird-0-unstable-2024-08-12/libexec/WebContent() [0x43c96c]
/nix/store/yk44cnbs3gpa5hpaxml3gbw2jjr04knh-ladybird-0-unstable-2024-08-12/libexec/WebContent(main+0xf2) [0x42bc32]
/nix/store/0wydilnf1c9vznywsvxqnaing4wraaxp-glibc-2.39-52/lib/libc.so.6(+0x2a14e) [0x7fd51023314e]
/nix/store/0wydilnf1c9vznywsvxqnaing4wraaxp-glibc-2.39-52/lib/libc.so.6(__libc_start_main+0x89) [0x7fd510233209]
/nix/store/yk44cnbs3gpa5hpaxml3gbw2jjr04knh-ladybird-0-unstable-2024-08-12/libexec/WebContent() [0x42bd65]

```

**Comment by qbit** [comment]
Result of `nixpkgs-review pr 334149` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>ladybird</li>
    <li>skia</li>
  </ul>
</details>

**Comment by fgaz** [comment]
> Builds fine but doesn't seem to load any pages:

It works for me. Are you on NixOS, and if so did you enable the ladybird option?

**Review by qbit — APPROVED** [review]

**Comment by fgaz** [comment]
> It's pretty frustrating that you need to enable the option to make it work.

It's a common complaint... a lot of packages are like that but there is no way to inform the user about it

**Comment by YoshiRulz** [comment]
A comment in the expression would be a good start...
For future humans, the option in question is [`fonts.fontDir.enable`](https://search.nixos.org/options?channel=24.05&show=fonts.fontDir.enable).

**Pull request merged**
