### PR TITLE
notmuch: 0.32.1 -> 0.32.2; clarify license

### PR DESCRIPTION
**Pull request by alyssais**
Also fix an incorrect (but apparently harmless) use of lib.optional.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 132201` at 15eec211 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/9095585018c07e9b285bfcb248617cb6">afew</a></li>
    <li><a href="https://gist.github.com/cb1c3f38bfcdcb7a2d842c44d1c5f8d4">alot</a> (python39Packages.alot)</li>
    <li><a href="https://gist.github.com/2356f45e6322dc086ba76f2cf8645795">lieer</a></li>
    <li><a href="https://gist.github.com/f2364b7a1ae19cb29b9021ccfbbbf68e">meli</a></li>
    <li><a href="https://gist.github.com/eebabf7b5ea3a059989833e2656a4e54">python38Packages.alot</a></li>
    <li><a href="https://gist.github.com/19ddf7e0872f466c8b98f411a6366715">python38Packages.notmuch</a></li>
    <li><a href="https://gist.github.com/b60b69e0ffd23f7fc464846c5fc884c4">python38Packages.notmuch2</a></li>
    <li><a href="https://gist.github.com/760f768adbd76a708306934f9da62be2">python39Packages.notmuch</a></li>
    <li><a href="https://gist.github.com/3e16cfe9bce89f8a67ad4b3a5970e646">python39Packages.notmuch2</a></li>
  </ul>
</details>
<details>
  <summary>9 packages built successfully:</summary>
  <ul>
    <li>aerc</li>
    <li>astroid</li>
    <li>haskellPackages.notmuch</li>
    <li>i3status-rust</li>
    <li>muchsync</li>
    <li>neomutt</li>
    <li>notmuch</li>
    <li>notmuch-addrlookup</li>
    <li>notmuch-mutt</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 132201` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>17 packages failed to build:</summary>
  <ul>
    <li>aerc</li>
    <li>afew</li>
    <li>alot (python39Packages.alot)</li>
    <li>astroid</li>
    <li>haskellPackages.notmuch</li>
    <li>i3status-rust</li>
    <li>lieer</li>
    <li>meli</li>
    <li>muchsync</li>
    <li>neomutt</li>
    <li>notmuch</li>
    <li>notmuch-addrlookup</li>
    <li>python38Packages.alot</li>
    <li>python38Packages.notmuch</li>
    <li>python38Packages.notmuch2</li>
    <li>python39Packages.notmuch</li>
    <li>python39Packages.notmuch2</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>notmuch-mutt</li>
  </ul>
</details>

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 132201` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>17 packages failed to build:</summary>
  <ul>
    <li>aerc</li>
    <li>afew</li>
    <li>alot (python39Packages.alot)</li>
    <li>astroid</li>
    <li>haskellPackages.notmuch</li>
    <li>i3status-rust</li>
    <li>lieer</li>
    <li>meli</li>
    <li>muchsync</li>
    <li>neomutt</li>
    <li>notmuch</li>
    <li>notmuch-addrlookup</li>
    <li>python38Packages.alot</li>
    <li>python38Packages.notmuch</li>
    <li>python38Packages.notmuch2</li>
    <li>python39Packages.notmuch</li>
    <li>python39Packages.notmuch2</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>notmuch-mutt</li>
  </ul>
</details>

**Comment by yorickvP** [comment]
@GrahamcOfBorg build python3packages.notmuch

**Comment by yorickvP** [comment]
@GrahamcOfBorg build python3Packages.notmuch

(sorry for the noise)

**Pull request merged**
