### PR TITLE
Update to Mariadb 10.2

### PR DESCRIPTION
**Pull request by globin**
###### Motivation for this change
This is split out of #22357, as this causes quite some changes in the whole code base and might cause breakage. 

Pending jobset and possibly needing fixes: https://hydra.nixos.org/jobset/nixos/mariadb-10.2

### CODE REVIEW

**Review by peti — APPROVED** [review]
The bit of the PR that affects Haskell looks good to me.

**Comment by vcunat** [comment]
Possibly better base this on staging.  If so, rather sooner than later to save some rebuild in the testing jobset as well.
```
Estimating rebuild amount by counting changed Hydra jobs.
   1955 x86_64-darwin
   3549 x86_64-linux
```

**Comment by globin** [comment]
@nixborg build

**Comment by nixborg** [comment]
@globin is not a committer

**Comment by globin** [comment]
@nixborg build

**Comment by nixborg** [comment]
Jobset created at https://hydra.mayflower.de/jobset/nixos/pr-30546

**Comment by globin** [comment]
@nixborg build

**Comment by nixborg** [comment]
Jobset created at https://hydra.mayflower.de/jobset/nixos/pr-30546

**Comment by globin** [comment]
@nixborg build

**Comment by globin** [comment]
@nixborg build

**Comment by globin** [comment]
@nixborg build

**Comment by globin** [comment]
@nixborg build

**Comment by nixborg** [comment]
Jobset created at https://hydra.mayflower.de/jobset/nixos/pr-30546

**Comment by globin** [comment]
@GrahamcOfBorg eval

**Review by ttuegel — APPROVED** [review]
This looks OK on the Qt 5 front.

**Comment by globin** [comment]
@vcunat I've just rebased this and will trigger another eval after a currently running one has finished.

This could either be merged into master and back into staging or go through staging, which would you prefer? The builds are cached due to it having its own jobset.

**Comment by vcunat** [comment]
These months the rebuilding bottleneck is clearly in Darwin.  The jobset for this branch has no Darwin binaries now, so I'd prefer to merge to staging, in order to reduce Darwin rebuild amounts (by doing multiple Darwin rebuilds together).

**Comment by globin** [comment]
Ok fine, I'll rebase without triggering a new eval :)

**Pull request merged**
