### PR TITLE
[staging-next] vim: 9.0.1403 -> 9.0.1441

### PR DESCRIPTION
**Pull request by dasJ**
###### Description of changes

This is going to staging-next because it contains a security fix: https://github.com/vim/vim/commit/23a971da506249fc8388f06cd5c011b83406ac5c

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
OK.  Around 12k rebuilds per `*-linux`.  Ofborg failed on aarch64-linux but I can't see relevant error message and can't reproduce the failure on the community box.

**Comment by vcunat** [comment]
Also @mweinelt got a build error.  Probably some race in the build system.

**Comment by mweinelt** [comment]
The aarch64-linux did indeed fail for the same reason.

```
/nix/store/gzqz4gzky8hw74257w1csci5jh1dngx8-binutils-2.40/bin/strip: unable to copy file '/nix/store/bwvvnhlsjkb77p7rjk5z46nr1jvwj8pp-vim-9.0.1441/bin/vim'; reason: Text file busy
installing /nix/store/bwvvnhlsjkb77p7rjk5z46nr1jvwj8pp-vim-9.0.1441/share/man/da.UTF-8/man1/vimtutor.1
make[1]: *** [Makefile:2314: installvimbin] Error 1
make[1]: *** Waiting for unfinished jobs....

**Comment by vcunat** [comment]
The ofBorg log indicates that the error is in install phase.  Was it also in your case?

That would point to doing `enableParallelInstalling = false;`
We might squeeze it into current `staging-next` or not, e.g. based on how much it fails on Hydra or preemptively now.

**Pull request merged**
