### PR TITLE
prefetch-npm-deps: read url bodies within the retry loop

### LINKED ISSUE #256873: buildNpmPackage / fetch-npm-deps runs into rate limiting
AIUI, requests are being sent out over and over again, and I do not understand why.
For a single build, that already runs into rate limits when buildings apps.

Native npm would use its cacache to avoid unnecessary requests.
Is there a chance to only request files that are not yet downloaded?

For implementation, I can help witht the Rust part, but Nix is too complicated for me at this point.

### LINKED ISSUE #257805: Occasionally, buildNpmPackage fails to download node_modules
### Describe the bug

Sometimes, I get network related errors when I try to produce a `buildNpmPackage`. Here's an example:

```
node_modules/@jridgewell/gen-mapping
node_modules/@xtuc/long
node_modules/@xtuc/ieee754
node_modules/accepts
node_modules/astral-regex
node_modules/basic-auth
node_modules/bl
node_modules/brace-expansion
node_modules/decompress-tar/node_modules/bl
Error: unknown error
Caused by:
    [55] Failed sending data to the peer
```

From this ofborg attempt: https://logs.ofborg.org/?key=nixos/nixpkgs.257662&attempt_id=77d3e9d9-ef98-4308-b021-afff5f6c0015

I cannot reproduce this easily, and sometimes after a retry it works, so that's all the information I have to give.

https://github.com/NixOS/nixpkgs/pull/238452 and https://github.com/NixOS/nixpkgs/issues/225586 might be related?

### PR DESCRIPTION
**Pull request by lilyinstarlight**
## Description of changes

Fixes issues with prefetch-npm-deps not properly retrying on network errors by reading the full body within the retry loop (rather than processing the request in the retry loop but then reading the body after)

Closes #257805
Closes #256873
Closes #258428

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Gerg-L** [comment]
works for me
```console
$ nix build github:nixos/nixpkgs#bitwarden --option substituters ''
error: builder for '/nix/store/a49pbxzg99z3j8yi8n27ibb1r0w73r90-bitwarden-2023.9.0-npm-deps.drv' failed with exit code 1;
       last 10 log lines:
       > node_modules/dir-compare/node_modules/minimatch
       > node_modules/through2-filter
       > node_modules/static-module/node_modules/magic-string
       > node_modules/@babel/plugin-transform-unicode-sets-regex
       > node_modules/@babel/plugin-syntax-export-namespace-from
       > node_modules/stat-mode
       > Error: unknown error
       >
       > Caused by:
       >     [55] Failed sending data to the peer
       For full logs, run 'nix log /nix/store/a49pbxzg99z3j8yi8n27ibb1r0w73r90-bitwarden-2023.9.0-npm-deps.drv'.
error (ignored): error: cannot unlink '/tmp/nix-build-openssh-9.5p1.drv-0': Directory not empty
error: 1 dependencies of derivation '/nix/store/531n38krd1jxbycp954sg5cm1fp2p6w4-bitwarden-2023.9.0.drv' failed to build
```
vs
```
nix build github:lilyinstarlight/nixpkgs/fix/prefetch-npm-deps-network-error-recovery#bitwarden --option substituters ''
```

**Review by amarshall — APPROVED** [review]
Ran `nix-build -A bitwarden.npmDeps --check` 20 times on 48 cores with no failures! Thanks!

**Review by Gerg-L — APPROVED** [review]
LGTM

**Comment by lilyinstarlight** [comment]
That last push was to change the method name a bit to clarify its change in behavior. It should just be a cosmetic/semantic change rather than a functional one

**Review by Gerg-L — APPROVED** [review]

**Review by wegank — APPROVED** [review]

**Comment by lilyinstarlight** [comment]
Manual backport is in #260742 (backport failure was due to #255168 not having been merged, but #260742 supersedes that one now)

**Pull request merged**
