### PR TITLE
nixos-rebuild: use `nix build` and `nix copy`

### LINKED ISSUE #45595: Use nix 2.0 commands in nixos-rebuild
## Issue description
It would be great to replace the massive wall of output with the Nix 2.0 progress indicator.

It *looks* relatively straightforward, but does require https://github.com/NixOS/nixpkgs/pull/37693.

### PR DESCRIPTION
**Pull request by michaelpj**
###### Motivation for this change
Get the nice progress indicators when running `nixos-rebuild`. Mostly fixes https://github.com/NixOS/nixpkgs/issues/45595.

###### Things done

- Replace `nix-copy-closure` with `nix copy`.
    - As I understand it, this is a straight replacement, provided we have the commit for [supporting copying drvs](https://github.com/NixOS/nix/commit/85530bcc0b4c61499f90fa6125c19beeb0f4485e). However, I think that might not be in our current version?
- Replace `nix-build` with `nix build`.
    - Due to https://github.com/NixOS/nix/issues/1930 we put the output in a temporary directory.
    - We also switch to running the function in our process instead of a subshell, so Nix thinks it's in a TTY and gives us the progress output.

I haven't attempted to touch any of the uses of `nix-instantiate`, since as I understand it there isn't a good Nix 2.0 replacement for the stuff that's being done there.

This is obviously going to need pretty careful testing, but I'm putting this up to get things going. I've tested it on my own machine and it seems to work nicely!

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - x ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
While I agree we should eventually do this, I don't think we should do it just yet.

- `nix build/copy --help` warns: `Note: this program is EXPERIMENTAL and subject to change.`
- the output is quite useless for debugging

**Comment by Mic92** [comment]
In `nix-review` I also switched back to `nix-build` because I needed the output. So the new nix 2.0 tools are more useful if one only downloads stuff.

**Comment by michaelpj** [comment]
What about gating it behind a flag or an env var? That way it's opt in, but people can start experimenting with it bug upstream if it's not usable enough.

**Comment by xeji** [comment]
Yes, the different options are a pain. I recommend we heed the "EXPERIMENTAL" warning and keep things as they are for now.

Eventually, `nix-build` and `nix build` should converge. I don't know what the plan or timeline is, but that's a discussion for the `nix` repo, not `nixpkgs`...

**Comment by yegortimoshenko** [comment]
I agree with @xeji, it seems to be too early to make that switch.

**Comment by ElvishJerricco** [comment]
Any chance this could be packaged as an optional replacement? Either a separate package with a different command name, or a NixOS module option?

**Comment by michaelpj** [comment]
Yes, that's a nice idea, I hadn't thought of that. I'll look into it. I think a separate package makes sense - then you just install `nixos-rebuild2` or something.

**Comment by michaelpj** [comment]
This won't work well as a separately packaged script, since it builds `nixos-rebuild` from the new nixpkgs and then re-execs it, so you'll just immediately delegate to the "real" `nixos-rebuild`.

I guess there's nothing really that can be done here unless there are some changes to the nix UI.

**Pull request closed without merging**
