### PR TITLE
nginx: Verify that configuration is syntactically correct

### PR DESCRIPTION
**Pull request by roblabla**
###### Motivation for this change

Making mistakes on a daily basis to the nginx config, I've made my website fall way too often due to a missing semicolon. With this change, the configFile writeText will fail if nginx -t doesn't report "syntax is ok". Note that `nginx -t` also checks if the files referenced in the config exists. However, I had to disable those checks since the user running the build (nixbld) doesn't necessarely have access to the files used by nginx (root for the master process).

If there is a way to run the checks under the correct user, that'd be even better. I haven't found a way to do that though.
###### Things done
- [x] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bobvanderlinden** [comment]
This is very much appreciated. However, it needs to be an option as it will fail for a lot of people. `nginx -t` doesn't just check for syntax errors, it also checks whether referred files and directories actually exist.

For instance my nginx configuration depends on certificates that are generated by ACME before Nginx starts. Running this on a NixOS machine will not work when ACME (or its dummy) has not ran before. Nginx and ACME can only run after the configuration has been built.

In addition, tools like nixops and building VMs on a machine that isn't the target will also fail when Nginx is referring to files outside of `/nix/store`. This happens when I run automated tests in a VM, but build the VM using Nix. `nginx -t` will be ran on the machine that is building, not the target machine.

#15906 covers some of the problems around avoiding stopping/starting Nginx with an invalid configuration.

**Comment by domenkozar** [comment]
But if you look at the implementation it ignores exit code but just checks
for syntax check

**Comment by roblabla** [comment]
The implementation just verifies nginx sends a "syntax is ok" message. I *think*, based purely on what I've seen on my machine, that that message is always sent (assuming syntax is OK), even if nginx fails to load other files. I do not know what happens in case of missing `includes` though.

**Comment by bobvanderlinden** [comment]
Aah, it took me a while to see what you meant. But after running `nginx -t` it makes sense. Somehow I thought `syntax is ok` was only outputted when everything in the file was ok.

Sorry for the confusion. This look good. :+1:

**Comment by regnat** [comment]
It seems that `nginx -t` doesn't output the `syntax is ok` line if it fails to load the SSL files.

On my computer, running `nginx -t -c /tmp/nginx.conf` says `syntax is ok` on the following file, but if I uncomment the ssl-related lines, I don't get the line anymore (and hence the builder fails). 
```
user nginx nginx;
daemon off;

events {}

http {
  server {
    server_name test
    listen 443;
    # ssl on;
    # ssl_certificate /nonexistent-cert.pem;
    # ssl_certificate_key /nonexistent-key.pem;
  }
}
```

**Comment by globin** [comment]
This breaks on nixops deployments:
```
2016/07/28 11:49:46 [emerg] 13847#0: open() "/srv/www/nixos.mayflower.de/channels/.redirects.conf" failed (2: No such file or directory) in /nix/store/p5iz8y608jp78r00fbq03c42mxpbjigc-nginx.conf:1266
nginx: configuration file /nix/store/p5iz8y608jp78r00fbq03c42mxpbjigc-nginx.conf test failed
```

The path `/srv/www/nixos.mayflower.de/` obviously does not exist on the machine I deploy from. I'd strongly prefer reverting this.

**Comment by garbas** [comment]
@globin i'll revert it and lets get your PR in first. we can then make this check optional (disabled by default ofcourse)

**Comment by edolstra** [comment]
No, don't make it optional. This sort of check fundamentally does not work, as we discovered years ago with the equivalent for Apache.

**Comment by roblabla** [comment]
Well, I personally need this kind of check. Being able to optionally enable it with something like `services.nginx.testConfig = true` would be great.

**Comment by edolstra** [comment]
The only viable way is to do the check *outside* of the build, but before switching to the new configuration. Having a pre-switch hook to prevent switching to a new configuration has been discussed, but I don't think we have it yet...

**Comment by roblabla** [comment]
What I have done works (if only for the fact that the test isn't perfect). By making the derivation that puts the config in the store fail, we make the whole build fail, which prevents switching.

**Comment by globin** [comment]
It doesn't work at all as long as you don't build on the same machine you're running nginx on, which we for example never do, either the machine config is build on hydra or the machine is deployed via nixops.

**Comment by roblabla** [comment]
Which is why having it opt-in (requiring users to do `services.nginx.testConfig = true`) would fix the issue...

**Comment by ibrahimsag** [comment]
can someone sketch the implementation of a pre-switch hook?
can we at least run a command like the following, between `nixos-rebuild build` and `nixos-rebuild switch` manually?
`{$new_nginx_store_dir}/bin/nginx -t -c {$new_nginx_config_store_dir} -p /var/spool/nginx` ?

**Pull request merged**
