### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
gettext is failing on darwin due to a patch that does not apply, cc @NixOS/darwin-maintainers

**Comment by flokli** [comment]
This currently break assembling the initrd:

```
output '/nix/store/1jrw092qwwgw5wkf4sqf3qmn9f2y7jbl-extra-utils' is not allowed to refer to the following paths:
  /nix/store/v589pqjhvxrj73g3r0xb41yr84z5pwb7-gcc-9.3.0-lib
```

(reproducible by running any nixos test)

`libudev.so` (coming from `${systemd.lib}`) seems to have gotten a reference to gcc-9.3.0-lib - I don't know yet what introduced it.

**Comment by flokli** [comment]
Bisecting revels this might be due to a meson bump:

```
❯ git bisect log
git bisect start
# good: [8a78890a08dfa697be21891619f799738b956aa5] Merge pull request #94296 from NixOS/staging-next
git bisect good 8a78890a08dfa697be21891619f799738b956aa5
# bad: [a93340d651aac4512efa395a3925c08372a709ee] Merge pull request #94933 from danieldk/amdvlk-2020.Q3.3
git bisect bad a93340d651aac4512efa395a3925c08372a709ee
# good: [e449d07a26787e3b373815e412981e107bd0d31c] pythonPackages.hdlparse: init at 1.0.4
git bisect good e449d07a26787e3b373815e412981e107bd0d31c
# good: [eac5ef8aa9c0ddd948b20e83d9d7b37cd0132a81] Merge pull request #95145 from samuelgrf/update/pcsx2-1.6.0
git bisect good eac5ef8aa9c0ddd948b20e83d9d7b37cd0132a81
# bad: [d94f97ae98180c483dd39b62aeace7ec5be845de] python: loguru: 0.5.0 -> 0.5.1
git bisect bad d94f97ae98180c483dd39b62aeace7ec5be845de
# bad: [53c6004d661d0fc897ff840e911cdaa944543285] python: base58: 2.0.0 -> 2.0.1
git bisect bad 53c6004d661d0fc897ff840e911cdaa944543285
# bad: [ccedb29f4b0b3a02f28be0a06cae480da2be432b] Define a i686-genode system double
git bisect bad ccedb29f4b0b3a02f28be0a06cae480da2be432b
# skip: [b1d838e20efe3ec594b76f0d33b9b318fb5fa74b] golden-cheetah: use libsForQt512
git bisect skip b1d838e20efe3ec594b76f0d33b9b318fb5fa74b
# bad: [5b543ef2148eb704beeb1db1d103add89eb29c90] Merge pull request #93011 from jtojnar/meson-0.55.0
git bisect bad 5b543ef2148eb704beeb1db1d103add89eb29c90
# skip: [ae661388c6fdbdaa206fab8684f6a603201cf78f] pyqtwebengine: add patch to fix build with Qt 5.14
git bisect skip ae661388c6fdbdaa206fab8684f6a603201cf78f
# bad: [d8ac41f86394365f8319d8b37fd25e6a7ba7d904] meson: 0.54.2 → 0.55.0
git bisect bad d8ac41f86394365f8319d8b37fd25e6a7ba7d904
# good: [c19222143e79bf8e58e1791ac1125cba34069c3c] meson: clean up
git bisect good c19222143e79bf8e58e1791ac1125cba34069c3c
# first bad commit: [d8ac41f86394365f8319d8b37fd25e6a7ba7d904] meson: 0.54.2 → 0.55.0
```

```
d8ac41f86394365f8319d8b37fd25e6a7ba7d904 is the first bad commit
commit d8ac41f86394365f8319d8b37fd25e6a7ba7d904
Author: Jan Tojnar <jtojnar@gmail.com>
Date:   Sun Jul 12 18:19:10 2020 +0200

    meson: 0.54.2 → 0.55.0
    
    https://mesonbuild.com/Release-notes-for-0-55-0.html
    https://github.com/mesonbuild/meson/releases/tag/0.55.0
    https://github.com/mesonbuild/meson/compare/0.54.2...0.55.0

 .../tools/build-managers/meson/default.nix         |  8 ++-
 .../tools/build-managers/meson/fix-rpath.patch     | 76 +++++++---------------
 2 files changed, 28 insertions(+), 56 deletions(-)
```

@jtojnar, any ideas?

**Comment by FRidh** [comment]
and @Ericson2314

**Comment by flokli** [comment]
Spun off into https://github.com/NixOS/nixpkgs/issues/95163.

**Pull request merged**
