### PR TITLE
pythonPackages.tlslite-ng: init at 0.7.5, migrate tlslite references to it, delete tlslite

### PR DESCRIPTION
**Pull request by erictapen**
###### Motivation for this change

`pythonPackages.tlslite` has a [test failure](https://github.com/trevp/tlslite/issues/121) on Python 3.7. @tomato42, a commiter of tlslite and author of [tlslite-ng](https://github.com/tomato42/tlslite-ng) said, that tlslite is abandoned (last commit 2015) and tlslite-ng should be used as a drop in replacement.

As it doesn't seem to be adopted widely, I believe that it is suitable to mark `tlslite` as broken. `tlslite-ng` can be dropped-in without much of a hassle.

###### Things done

- Init `pythonPackages.tlslite-ng`
- Mark `tlslite` as broken
- Migrate all occurences of `tlslite` to `tlslite-ng`.

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by tomato42** [comment]
I'm not familiar with development on macOS so I would appreciate any help in making sure that tlslite-ng continues to work there: https://github.com/tomato42/tlslite-ng/issues/73 (in general, it should work as I try to use portable code, but it will be easier for you if the issues are caught early, not after release)

**Comment by edef1c** [comment]
I don't think it's wise to leave a security-relevant package in that it is expected to remain unmaintained..
We should at least have a comment explaining *why* the package is broken (and should not be used), or perhaps alias the old package name over.

**Comment by alyssais** [comment]
If the package is unmaintained and not used by anything, I don't think it should be in Nixpkgs at all. I'd prefer the derivation be deleted. It's never going to be fixed, (and in fact, since it's security-relevant, never _should_ be fixed since it's unmaintained), so there's no benefit for us to continue to carry the code.

**Comment by alyssais** [comment]
I think the normal way to do this is to delete the package and then add an alias to `throw “foo has been removed because bar. use baz instead”`.

I’d prefer that we don’t just alias this to the ng version, because then it’s not clear what libraries a derivation is actually using.

**Comment by edef1c** [comment]
I'll take the argument against aliasing, though if we end up having to backport for a security issue, it should get aliased over in the backport.
I can find some precedent (8 instances) in nixpkgs for `throw "deprecated 2018-12-10: use tlslite-ng instead";`

**Comment by alyssais** [comment]
@grahamcofborg build pythonPackages.tlslite-ng python3Packages.tlslite-ng

**Pull request merged**
