### PR TITLE
R: 3.6.1 -> 3.6.2

### PR DESCRIPTION
**Pull request by jabranham**
###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by timokau** [comment]
Please look into the aarch64 ofBorg failure.

**Comment by peti** [comment]
Cherry-picked into r-updates as df07230. Test builds are running at https://hydra.nixos.org/jobset/nixpkgs/r-updates.

**Comment by jabranham** [comment]
This is the error on the aarch build: `running code in 'reg-tests-1d.R' ...make[3]: *** [Makefile.common:106: reg-tests-1d.Rout] Error 1`, which isn't especially useful without access to the reg-tests-1d.Rout file. I don't have an aarch64 machine to test this on. Does ofborg store that file somewhere I'm missing?

**Comment by timokau** [comment]
Not currently. That is why I opened https://github.com/NixOS/nixpkgs/pull/49378 some while ago. Unfortunately that wasn't accepted. Maybe you can cherry-pick it into this PR and look at the error ofBorg generates.

**Pull request closed without merging**
