### PR TITLE
vlc: fix GLib-GIO-ERROR rg.gtk.Settings.FileChooser

### PR DESCRIPTION
**Pull request by ghost**
###### Motivation for this change

When clicking on the "Media -> Open File ..." item in the GUI VLC player, the player crashes with the following error.

```
(vlc:22800): GLib-GIO-ERROR **: 10:08:13.004: Settings schema 'org.gtk.Settings.FileChooser' does not contain a key named 'show-type-column'
Trace/breakpoint trap (core dumped)
```

Adding `wrapGAppsHook` to the `nativeBuildInputs` resolves the issue and allows users to select a file.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests)) (no tests exist)
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`

  The following derivation could not be built.

  ```
  builder for '/nix/store/13qb5yp1v9r4cpabhxipqqxfkl51bqsj-InstallNDISDK_v4_Linux.tar.gz.drv' failed with exit code 1; last 10 log lines:
  
    https://ndi.tv/sdk/
  
    Once you have downloaded the file, please use the following command and
    re-run the installation:
  
    nix-prefetch-url file://$PWD/InstallNDISDK_v4_Linux.tar.gz
  
    ***
  cannot build derivation '/nix/store/0b072a09k16rgz7kaipppp626dvh1r3k-ndi-4.drv': 1 dependencies couldn't be built
  cannot build derivation '/nix/store/xzg1xvx23zfai55rm596p4y842s50rvm-obs-ndi-4.7.1.drv': 1 dependencies couldn't be built
  cannot build derivation '/nix/store/2jpgmzlvjpwazj7mf3l4zi6psln7jjxd-env.drv': 1 dependencies couldn't be built
  ```

  The `nix-review` command generated the following report.

  ```
  Result of `nix-review` [1](https://github.com/Mic92/nix-review)
  <details>
    <summary>1 package failed to build:</summary>
  
    - obs-ndi
  </details>
  <details>
    <summary>16 package were built:</summary>
  
    - cantata
    - elisa
    - libsForQt5.phonon-backend-vlc
    - libsForQt5.vlc
    - megaglest
    - minitube
    - netease-cloud-music
    - obs-linuxbrowser
    - obs-studio
    - obs-wlrobs
    - pympress
    - python27Packages.python-vlc
    - python37Packages.python-vlc
    - python38Packages.python-vlc
    - strawberry
    - tribler
  </details>
  ```

- [x] Tested execution of all binary files (usually in `./result/bin/`)
  
  All run except the wrapper, which seems to attempt to call the wrong subwrapper. Potentially it should be calling `.vlc-wrapped` instead of `.vlc-wrapper`

  ```
  $ ./vlc-wrapper
  /nix/store/d57y6sgrxyl3zviyhvg30p7v4rc0dc1k-vlc-3.0.8/bin/.vlc-wrapper: No such file or directory
  ```

- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date (does not seem to have any documentation)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

No maintainers specified in the .nix file, but the following contributor approved the last VLC PR.

cc @aanderse

### CODE REVIEW

**Comment by teto** [comment]
cc @jtojnar

**Comment by jtojnar** [comment]
We would need to prevent double-wrapping, see https://nixos.org/nixpkgs/manual/#ssec-gnome-common-issues-double-wrapped.

**Comment by orendorff-mi** [comment]
I got a bit stuck trying to prevent the double wrapping. I tried the method mentioned in the manual for Qt apps but this did not seem to apply any of prefixes specified in `gappsWrapperArgs`. I then tried this

```
  preFixup = ''
    qtWrapperArgs+=(
      ''${gappsWrapperArgs[@]}
    )
  '';
```

which did add the correct arguments to two of the binaries (`vlc` and `vlc-wrapper`), with the other binary wrappers seem to reference these two. However, when the `vlc` program is run and one tries to open a file, the `Settings schema 'org.gtk.Settings.FileChooser' does not contain a key named 'show-type-column'` error happens. This is the original error that prompted the PR.

When using the double wrapped setup, the `gappsWrapperArgs` are wrapped on every binary (`vlc`, `rvlc`, etc), and this seems to solve the original schema issue.

I'm not quite sure where to go from here. I checked through the repository for similar cases and it seems that these two solutions are commonly used, but neither worked out.

- Add the arguments in a `preFixup` using something similar to what is above (remmina has this type of modification). As mentioned this added the prefix arguments to the wrapper scripts but the main open file issue remained.
- Add `gappsWrapperArgs` when manually calling `wrapProgram` (telegram has this approach). This option could be done but would remove the nice machinery already existing for wrapping the Qt arguments.

I also tried the following

- Adding the values to `makeWrapperArgs` directly but this did not seem to do anything.
- Adding the prefix values of `gappsWrapperArgs` explicitly to `qtWrapperArgs`, but this had the same result as the main attempt above.

**Comment by jtojnar** [comment]
Sorry, there might be more issues: https://github.com/NixOS/nixpkgs/pull/76283#issuecomment-568801591 I guess double wrapping will have to do for now.

**Comment by orendorff-mi** [comment]
I added a note about the double wrapping to remember in the future.

**Comment by SuperSandro2000** [comment]
Closing due to ghost user.

**Pull request closed without merging**
