### PR TITLE
Revert "noto-fonts-cjk: switch back to variable font"

### PR DESCRIPTION
**Pull request by midchildan**
###### Description of changes

Apply #174753 on 22.11 because the Discord app still can't render variable Noto CJK correctly.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [X] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Mathnerd314 — APPROVED** [review]
Sigh, I guess this is necessary. Although, based on the Electron version numbers, the Discord public testing build should work. So maybe the alternative is to recommending installing the PTB build.

Of course then there are still [the people](https://discourse.nixos.org/t/noto-fonts-cjk-font-look-too-thin-on-nixos-22-05-and-kde-plasma/19528) complaining that the OTF is too thin. I think the only solution is to switch the main Noto font and the CJK at the same time so that the font is uniformly thin, or to always provide the TTF. Or maybe it is a KDE bug and there is some weight setting that is not getting applied.

**Comment by oxalica** [comment]
> Of course then there are still [the people](https://discourse.nixos.org/t/noto-fonts-cjk-font-look-too-thin-on-nixos-22-05-and-kde-plasma/19528) complaining that the OTF is too thin.

I'm on nixos-unstable and the weight of Chinese characters in Qt applications *change* frequently whenever a Qt-related update lands. Both Qt5 (KDE) and Qt6 (tdesktop) are affected. Sometimes it gets too thin, sometime too thick, sometime just right. It seems hard to find exactly what causes the change in font weights. But the weight of ASCII characters is always fine.

**Comment by Mathnerd314** [comment]
I googled and found a suggestion that maybe the language is not being set right, so maybe it is showing JP-style glyphs instead of Chinese style. Or it could be the font weight switching. Regardless, I don't think much progress can be made without a reproducible testcase showing the different weights. Then we can report an upstream bug in Qt/KDE and hopefully get it fixed eventually. 

But if it's really random and VF vs no VF has no effect then it would make sense to use the VF - there's no point in using a workaround that doesn't work.

**Comment by oxalica** [comment]
> maybe it is showing JP-style glyphs instead of Chinese style

I can read and distinguish between Japanese and Chinese characters. That's unrelated. I'm talking about font weights.

> But if it's really random and VF vs no VF has no effect 

No. Maybe my wording is somehow confusing. But to be simple,
1. I don't have any explicit "weight" setting in my (font)config.
2. noto-fonts-cjk non-VF fonts work fine always.
3. noto-fonts-cjk VF fonts use `Regular` weight for some nixpkgs revision, use `Light`/`Bold` weight for some other ones, despite that nothing font-specific configs or packages except the KDE/Qt itself are changed.
4. I guess the issue is about "what's the default weight chosen". Or maybe it only recognized `Light` variant preset sometimes.

There are definitely some bugs in Qt, but I don't know how to reliably test/reproduce it.

**Comment by oxalica** [comment]
I made a nixos test for the CJK font weight issue. But currently it can only by checked using eyes. Not sure if there's an automatic way to assert the rendered weight.
https://gist.github.com/oxalica/8136992ba1fd5a08b6e417d653046d78

This PR does fix my issue. And maybe it's good to also include the test here.

**Comment by oxalica** [comment]
My issue about variable font is fixed in the Qt side in #222311 and I don't need this PR anymore. Not sure if the Discord issue is related to that too.

**Comment by midchildan** [comment]
@drupol I think this PR is still relevant because packages in 22.11 probably don't include fixes to render variable Noto CJK correctly.

**Comment by drupol** [comment]
Then we should move it forward. Maybe @SuperSandro2000 can help?

**Comment by SuperSandro2000** [comment]
No idea but since the next stable is almost around the corner I would just sit this one out.

**Comment by midchildan** [comment]
I guess it wouldn't be too big of a deal if enough people upgrade. I'll close this PR for now.

**Comment by lboklin** [comment]
Steam is still affected by this issue.

**Pull request closed without merging**
