### PR TITLE
services.xserver.extraLayouts fixes

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions 
- [x] Tested in a NixOS VM
- [x] Tested compilation of all pkgs that depend on this change (nixos manual)
- [x] Tested execution of all binary files (none)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @dasj19 @infinisil

### CODE REVIEW

**Comment by lheckemann** [comment]
@grahamcofborg test keymap

**Comment by dasj19** [comment]
This PR makes my PR obsolete: https://github.com/NixOS/nixpkgs/pull/67181

So when this gets merged the one I referenced must be rejected

**Comment by lheckemann** [comment]
Hm, is grahamcofborg on holiday as well?

**Comment by lheckemann** [comment]
Tested myself, keymap tests work.

**Comment by FRidh** [comment]
Looks like only one x86_64-linux worker is available?
https://monitoring.nix.ci/d/000000002/ofborg?orgId=1&from=1568013635984&to=1568017235984&panelId=8&fullscreen

**Comment by rnhmjoj** [comment]
Thank you all!

**Pull request merged**
