### PR TITLE
nixos/caddy: Add rfc42 settings option

### PR DESCRIPTION
**Pull request by Sohalt**
###### Description of changes

Add [rfc42](https://github.com/NixOS/rfcs/blob/master/rfcs/0042-config-option.md) `settings` option to Caddy.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by dasj19 — APPROVED** [review]
I built this on my machine and used the provided test config, the caddy.json gets generated and the server works as expected.

**Comment by emilylange** [comment]
I am not in favor of this.

Most end-users should mainly interact with Caddy via Caddyfile.
I'd argue, this change suggests, that the json config is preferred.
Which it isn't :(

**Comment by Sohalt** [comment]
Would you be ok with the change if the docstring were more explicit that usually using the other options (which assemble a Caddyfile) is preferred?

I think we should provide a rfc42 style settings option for the json config, because it means that we can utilize the module system to merge json configs. If you need features from the json config, you currently have to do something like
```nix
configFile = pkgs.writeText "caddy.json" (builtins.toJSON {
  …
});
```
which then can't be merged or overridden anymore.

**Comment by Sohalt** [comment]
Is the change fine for you, @emilylange? Anything left to do?

**Comment by Sohalt** [comment]
Push. CC @emilylange

**Comment by emilylange** [comment]
Whoops, sorry, will try to look into this soon.

**Review by emilylange — CHANGES_REQUESTED** [review]

**Comment by emilylange** [comment]
@ofborg test caddy

**Review by emilylange — APPROVED** [review]
Thanks!

**Pull request merged**
