### PR TITLE
exiftool: 12.39 -> 12.49

### PR DESCRIPTION
**Pull request by anthonyroussel**
###### Description of changes

* exiftool: 12.39 -> 12.49
  * See https://exiftool.org/history.html

* Add myself to maintainers
* Fix mat2 tests with exiftool upgrade
  * See https://0xacab.org/jvoisin/mat2/-/issues/178

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
@ofborg build mat2

Fails for me, macos 10.15 & nixos x86_64

**Comment by anthonyroussel** [comment]
> @ofborg build mat2
> 
> Fails for me, macos 10.15 & nixos x86_64

Indeed, looks like it is related to https://0xacab.org/jvoisin/mat2/-/issues/178

**Comment by anthonyroussel** [comment]
> > @ofborg build mat2
> > Fails for me, macos 10.15 & nixos x86_64
> 
> Indeed, looks like it is related to https://0xacab.org/jvoisin/mat2/-/issues/178

Fixed with https://0xacab.org/jvoisin/mat2/-/commit/618e0a8e3984fd534b95ef3dbdcb8a76502c90b5 on master

**Review by ivan — APPROVED** [review]
I did not see issues on x86_64 NixOS master. I tested `exiftool` and `exiftool -gps:all= -xmp:geotag=` on a JPEG.

**Pull request merged**
