### PR TITLE
curl: backport netrc regression fix

### PR DESCRIPTION
**Pull request by Scrumplex**
Closes https://github.com/NixOS/nixpkgs/issues/356114

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by vcunat** [comment]
24.05 has curl-8.7.1

**Comment by Scrumplex** [comment]
I am currently building this on x86_64-linux to test if it fixes the issue

**Comment by Scrumplex** [comment]
Git on master (`/nix/store/pxpns5vm111i6j3r3wbygaj99wbrm6h1-git-2.47.0/bin/git`) fails as expected. Git when built with this branch (`/nix/store/sdibgacy5r5lyhv80hga6d1xd61p5g08-git-2.47.0/bin/git`) works

**Review by JohnRTitor — COMMENTED** [review]
Do we have to vendor the patch? Can we not use `fetchpatch2`?

**Comment by Scrumplex** [comment]
> Do we have to vendor the patch? Can we not use `fetchpatch2`?

There is a comment in the derivation about this:

> ```
> # Note: this package is used for bootstrapping fetchurl, and thus
> # cannot use fetchpatch! All mutable patches (generated by GitHub or
> # cgit) that are needed here should be included directly in Nixpkgs as
> # files.
> ```

**Review by JohnRTitor — COMMENTED** [review]
I'd target staging-next for this PR. 

curl and git are critical packages that we don't want broken in master.

**Comment by JohnRTitor** [comment]
CC @NixOS/nixos-release-managers, as curl 8.11 have already reached master and release-24.11.

I'd prefer we'd not ship a broken curl and git, so accept this huge rebuild and get it within this cycle before release.

**Comment by vcunat** [comment]
We rebuild stuff either way all the time.  So I see it more as a question of accepting the delay.

**Comment by RossComputerGuy** [comment]
> I'd prefer we'd not ship a broken curl and git

I agree

> accept this huge rebuild and get it within this cycle before release.

How much of a delay do you think this could have?

**Comment by vcunat** [comment]
This is a huge rebuild.  (I see I've only posted about it in the chat.)  It's roughly 200/250 k jobs.

I believe that `staging-next-24.11` will now be the next mass rebuild to run either way.  So the infra will work on that, and you'll see how fast it goes and decide the moment for announcing the release 🤷🏽   I feel confident that it will be finished this month, but the 24.11 schedule plans the release at Nov 22 already.

**Comment by vcunat** [comment]
This weekend might be realistic, but such predictions are rather uncertain.

**Comment by jzbor** [comment]
I only see comments on the impact on the stable release. Any estimation when this fix expected to land in unstable?

**Comment by jzbor** [comment]
> Probably a few days after it lands on 24.11. I hope; I haven't estimated the divergence yet.

Is there any PR that one can track regarding this? (Or will there/what do I have to look out for?)

**Comment by adrian-gierakowski** [comment]
https://nixpkgs-tracker.ocfox.me/?pr=356133

**Comment by matthiasdotsh** [comment]
> https://nixpkgs-tracker.ocfox.me/?pr=356133

It looks like it's still in `staging-next`. Is there a reason why it's taking so long?

**Comment by jzbor** [comment]
https://nixpkgs-tracker.ocfox.me/?pr=360437

This would be the corresponding PR I think

**Pull request merged**
