### PR TITLE
vscode-extensions.mgt19937.typst-preview: 0.6.0 -> 0.6.1

### PR DESCRIPTION
**Pull request by drupol**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 2xsaiko** [comment]
Result of `nixpkgs-review pr 243232` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>typst-ws</li>
  </ul>
</details>

`typst-ws --help` works, `typst-ws fonts` gives:

```
% typst-ws fonts
[2023-07-13T20:29:03Z INFO  typst_ws] Arguments: CliArguments {
        font_paths: [],
        root: None,
        data_plane_host: None,
        control_plane_host: None,
        static_file_host: None,
        static_file_path: None,
        command: Fonts(
            FontsCommand {
                variants: false,
            },
        ),
    }
thread 'main' panicked at 'internal error: entered unreachable code', src/main.rs:81:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by drupol** [comment]
Dear @Enter-tainer,

I'm trying to package `typst-ws` in Nix in this PR and I'm wondering if `typst-ws` can potentially be used without VSCode or not.

Can you help us ?

**Comment by Enter-tainer** [comment]
cool! 

I've heard of that typst-ws binary shipped within the vsix bundle would not working on nixos for some reason(dyn lib path, etc). I guess that your X problem is to make typst-ws working on nixos. I once took a look at the code in rust-analyzer and I found that when it detects nixos, elfpatch would be called to patch the binary to make it work on nixos.

For another perspective, typst-ws itself does't do anything meanful if used without the extension. And it is designed for internal use.(or, it isn't carefully designed for external use). It mainly starts several http/ws server and waits for vscode connects to it. Then it watches on the typst source file and sends relevant data to through the ws connection. So if no one connects to it, it will not do anything.

I'd prefer implementing rust-analyzer-like elfpatch logic in the extension itself if the intention is to make it work on nixos. And I will do that. I will also take a look at this pr. Many thanks for your work!

**Comment by Enter-tainer** [comment]
For some background info: typst-ws's code was initially copied for typst cli. So there are some subcommand like `typst-ws fonts`. It isn't useful and should get removed. See https://github.com/Enter-tainer/typst-preview-vscode/blob/main/src/main.rs#L81 . All commands other than `watch` would panic. The only valid use of `typst-ws` is to launch it from the vscode extension like `typst-ws watch [path here]`. See https://github.com/Enter-tainer/typst-preview-vscode/blob/main/addons/vscode/src/extension.ts#L338 for details.

**Comment by drupol** [comment]
I understand better, thanks for the explanation. This PR makes no sense then if `typst-ws` cannot be used without the extension.

This morning, I tried to fix the broken library linkage and I though that I succeeded at first, but nope.

Here's the log:

```
❯ ldd ~/.vscode/extensions/mgt19937.typst-preview/out/typst-ws
        linux-vdso.so.1 (0x00007fff77ec1000)
        libgcc_s.so.1 => /nix/store/4l1wp6kyi2yz7krzq8lmz8fb9i18yplf-gcc-12.3.0-libgcc/lib/libgcc_s.so.1 (0x00007f7ad6682000)
        libc.musl-x86_64.so.1 => /nix/store/1gcgfv9gx4f1hvqz4yc6krwpha3c40id-musl-1.2.3/lib/libc.musl-x86_64.so.1 (0x00007f7ad65cd000)
        libc.so.6 => /nix/store/3n58xw4373jp0ljirf06d8077j15pc4j-glibc-2.37-8/lib/libc.so.6 (0x00007f7ad381a000)
        /nix/store/3n58xw4373jp0ljirf06d8077j15pc4j-glibc-2.37-8/lib/ld-linux-x86-64.so.2 => /nix/store/3n58xw4373jp0ljirf06d8077j15pc4j-glibc-2.37-8/lib64/ld-linux-x86-64.so.2 (0x00007f7ad66a5000)
❯ ~/.vscode/extensions/mgt19937.typst-preview/out/typst-ws
fish: Job 1, '~/.vscode/extensions/mgt19937.t…' terminated by signal SIGSEGV (Address boundary error)
❯ ~/.vscode/extensions/mgt19937.typst-preview/out/typst-ws --help
fish: Job 1, '~/.vscode/extensions/mgt19937.t…' terminated by signal SIGSEGV (Address boundary error)
~/C/d/nixos-x260 > master +268 -1 [x!+] ✘ 
```

Do you have any idea why it's failing?

**Comment by Enter-tainer** [comment]
Let's track this issue here https://github.com/Enter-tainer/typst-preview-vscode/issues/62

**Comment by drupol** [comment]
@Enter-tainer I just updated this PR and it's now working on Linux.

**Comment by Enter-tainer** [comment]
Nix can even patch binary shipped with vscode extension..! That is very, very interesting. Thank you for your work!

**Pull request merged**
