### PR TITLE
whitebox-tools: init at 0.9.0

### PR DESCRIPTION
**Pull request by mpickering**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Infinisil** [comment]
@GrahamcOfBorg build whitebox-tools

**Comment by mpickering** [comment]
Looks like `rustc-1.27.0` is broken.

**Comment by mpickering** [comment]
I'll fix this on darwin.

**Comment by nlewo** [comment]
@GrahamcOfBorg build whitebox-tools

**Comment by xeji** [comment]
to check darwin build:
@GrahamcOfBorg build whitebox-tools

**Pull request merged**
