### PR TITLE
grafana: fix frontend build on aarch64

### PR DESCRIPTION
**Pull request by K900**
I think it works on x86_64 because it fallback to the prebuilt version and they only added prebuilt ARM binaries in 2.2.0 https://github.com/parcel-bundler/watcher/commit/062bca4887f17a2f448c11a99bfc2f826eb98c3e
- @tgerbet

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by alyssais** [comment]
Would it be worth getting rid of the prebuilt version so it can't accidentally fall back?

**Comment by K900** [comment]
My node-fu is not nearly strong enough to know how to do that, never mind how to make sure it doesn't come back.

**Comment by LeSuisse** [comment]
That would be nice but I'm not sure if we have a nice way to handle that. Using precompiled or built from source binaries often relies on a build script specific to each package. `parcel/watcher` is unlikely to be the only one, I see some @swc-project tools in the Grafana dev/build tools.

The VSCode/OpenVSCode servers seem to do something specific for parcel/watcher because they use a more recent version: 
https://github.com/NixOS/nixpkgs/blob/f58fe0f36dbbef39b3f5ec8542a02dece7c9559b/pkgs/servers/openvscode-server/default.nix#L182-L200

Anyway overall we are probably still in a better place with #283330 and this PR fixing the aarch64 build issue. At least we can know patch the frontend code if we need to and we have a better visibility on how the build process works (even if they are some things we would have preferred not seeing :sweat_smile: )

**Comment by Ma27** [comment]
> At least we can know patch the frontend code if we need to and we have a better visibility on how the build process works

I fully agree with that and I'd like to apologize for not having caught the aarch64-linxu regression!
Will review & merge later to get that fixed.

But @alyssais has a point though and unless someone else wants to, I'll probably try to take a look soonish.

**Comment by K900** [comment]
So fun thing, it builds on ofborg, but on my Orange Pi it OOMs. Trying now with `export NODE_OPTIONS=--max_old_space_size=4096`, supposedly it should help?

**Comment by K900** [comment]
It helped.

**Pull request merged**
