### PR TITLE
epson-escpr2: 1.0.29 -> 1.1.1 

### PR DESCRIPTION
**Pull request by d-goldin**
###### Motivation for this change

The build was failing because the source rpm does not exist
on epsons servers anymore.

Thus bumping it to an existing version
https://hydra.nixos.org/build/101990975/nixlog/5

Related: https://github.com/NixOS/nixpkgs/issues/68361

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @ma9e

### CODE REVIEW

**Comment by d-goldin** [comment]
@furrycatherder and @joachifm because of the last PR https://github.com/NixOS/nixpkgs/pull/54906

**Review by sphaugh — APPROVED** [review]
afaict Epson is evil and only keeps the latest version of the rpm on their site. So this is going to keep happening and might be worth hosting a mirror or something. Otherwise lgtm.

**Comment by d-goldin** [comment]
@furrycatherder: Yeah, I assume so as well. Right now I'm not sure about the repercussions of mirroring it somewhere, but I'll give it a thought. I'm also not aware whether we have any sort of precedent for hosting 3rd party artifacts yet. Main prio was to provide some fix for the 19.09 release.

**Comment by d-goldin** [comment]
@furrycatherder: Btw, are you by any chance able to try this driver out, if you still happen to have such a device?

**Review by jonringer — COMMENTED** [review]
I'm unable to download that as well
```
trying https://download3.ebz.epson.net/dsc/f/03/00/09/02/31/a332507b6398c6e2e007c05477dd6c3d5a8e50eb/epson-inkjet-printer-escpr2-1.1.1-1lsb3.2.src.rpm
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
    0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  curl: (22) The requested URL returned error: 404 Not Found
  error: cannot download epson-inkjet-printer-escpr2-1.1.1-1lsb3.2.src.rpm from any mirror
```

**Comment by d-goldin** [comment]
@jonringer: thanks. forgot to update the other parts of the URL. must have tested sth else while in a hurry. should be fine now.

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS
diff LGTM
leaf package

**Comment by d-goldin** [comment]
Ok, now I had a little time to look into the rpm itself. It seems like the thing is under LGPL 2.1, so at least from that angle archiving the rpm somewhere should be fine. What do we think of trust in the case of hosting it in some arbitrary github repo? The rpm is unfortunately not signed, nor are there any checksums published as far as I can see, so it would be hard to establish trust.

AUR does epsons site. Debian seems to have an own repo where they manually merge in changes from upstream, but debian also has a different contribution model. I'd think with nixos we should prefer the original source, but here of course the trade-off would be maintenance effort.

@furrycatherder; As the maintainer, what do you think (I just now realized you are ma9e)?

**Comment by d-goldin** [comment]
Just FYI - the binary RPM is signed with keys available on SKS, the source archive is unfortunately not;

```
$  rpm -K -v epson-inkjet-printer-escpr2-1.1.1-1lsb3.2.src.rpm
epson-inkjet-printer-escpr2-1.1.1-1lsb3.2.src.rpm:
    Header SHA1 digest: OK
    MD5 digest: OK

$ rpm -K -v epson-inkjet-printer-escpr2-1.1.1-1lsb3.2.x86_64.rpm
epson-inkjet-printer-escpr2-1.1.1-1lsb3.2.x86_64.rpm:
    Header V4 DSA/SHA1 Signature, key ID 8aa65d56: OK
    Header SHA1 digest: OK
    V4 DSA/SHA1 Signature, key ID 8aa65d56: OK
    MD5 digest: OK
```

**Comment by d-goldin** [comment]
I sent epson (there is a linux-printing@ address provided in the README or so) a mail asking them if they could also sign the source archive, to make it easier for us wrt trust. But I dont have too high hopes. I'd suggest that if the PR is otherwise OK, we should probably merge it, including backport for 19.09, and open a follow-up issue to figure out the mirror part.

**Comment by furrycatherder** [comment]
lgtm 👍

**Review by sphaugh — APPROVED** [review]

**Comment by worldofpeace** [comment]
backported in 8ef6192d2af7a4db575133f2e8f80c74b65b3294

**Pull request merged**
