### PR TITLE
vimPlugins: update; add seoul256-vim, vim-cpp-enhanced-highlight, delimitMate

### PR DESCRIPTION
**Pull request by tmplt**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by jonringer — APPROVED** [review]
Diff LGTM

`nix-review` passes on NixOS

**Review by timokau — APPROVED** [review]
LGTM too, just needs a rebase and then it should be good to go. Unfortunately vim plugin PRs tend to bitrot fast.

**Comment by Tmplt** [comment]
@timokau, done.

**Comment by timokau** [comment]
Thanks!

**Pull request merged**
