### PR TITLE
[staging] openssh: 8.6p1 -> 8.7p1

### PR DESCRIPTION
**Pull request by dasJ**
###### Motivation for this change

https://lwn.net/Articles/866926/

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests)) `openssh.nix`
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kloenk** [comment]
tested `ssh` and `ssh-add` on `aarch64-darwin`

**Review by ajs124 — APPROVED** [review]
openssh test still passes

**Comment by lionello** [comment]
Can we backport this to 21.05? My server is suffering from https://bugzilla.mindrot.org/show_bug.cgi?id=3286

**Comment by dasJ** [comment]
You could check if `8c396f42c19` applies on 21.05

**Pull request merged**
