### PR TITLE
chefdk: enhancement

### PR DESCRIPTION
**Pull request by rvlander**
Berkshelf is included by default in chefdk offcial release but was not included in the packet.
Knife tools are also very useful in the chefdk environment, so they were embedded in the package.

Related to #11439

### CODE REVIEW

**Comment by joachifm** [comment]
Will you please change the commit subject to `pkgname: enhancement`? Besides that, I don't see any reason not to merge this.

**Comment by joachifm** [comment]
@rvlander sorry, I was unclear, I meant to change the actual commit subject (via `git commit --amend` and force pushing it). Also note that participants in the thread are not notified of such changes. Feel free to ping me.

**Comment by whiteley** [comment]
I'm confused by a couple of things here, sorry if I'm missing something

* `chef` is included but is a runtime dependency of `chef-dk` and would be included automatically
* `chef-dk` is removed entirely which is the entire purpose of this package
* `knife-solo` and `knife-solo_data_bag` are not an official part of the [Chef DK](https://github.com/chef/chef-dk/blob/master/omnibus/config/projects/chefdk.rb)

I'm excited to see some movement on this package after I was unable to get any feedback on my concerns earlier but I think this is headed in a direction that creates yet more confusion. I think that a NixOS package called "chefdk" should be as close as possible to the upstream packages offered for other distributions. Additional tools regardless of popularity should be punted to a "chefdk-extras" or similar.

**Comment by rvlander** [comment]
@whiteley, I agree with all.

**Comment by joachifm** [comment]
@rvlander could this PR be closed or do you intend to address the concerns that have been raised?

**Comment by rvlander** [comment]
@joachifm I will eventually address the concerns unless @whiteley is more motivated.

**Pull request closed without merging**
