### PR TITLE
atom: 0.187.0 -> 0.199.0

### PR DESCRIPTION
**Pull request by codyopel**

### CODE REVIEW

**Comment by geerds** [comment]
Couldn't start atom:

```
$ /nix/store/27q4ih58kwc88wsxnqzzhl7q3ljmkjng-atom-0.199.0/bin/.atom-wrapped: line 98:  5227 Aborted                 nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
[5227:0518/001622:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[5227:0518/001622:FATAL:udev_loader.cc(36)] Check failed: false. 
^C
```

Does it work on your machine?

**Comment by codyopel** [comment]
I'll look into it.  It worked when I tested it, but I could have something weird causing it to work.

**Comment by pSub** [comment]
I can reproduce the error too. Any updates?

**Comment by codyopel** [comment]
I haven't looked into it, I instead started working on packaging atom from source, although I have been busy the last couple of weeks.  However because the main atom developer can't write a build system to save his life, this is proving more difficult than I anticipated.  The build system vendors dependencies through nested git submodules and there is no way to override this behavior.  With this, not only do you have to patch atom, but all of it's vendored dependencies too where necessary.  Most of the problems are with building electron(previously atom-shell), but the nodejs/npm crap for atom itself wants to write files all over the filesystem so I still have to figure that out, I'll have to look at npm2nix and other hacks.
Related: https://github.com/NixOS/nixpkgs/issues/6689

In the meantime, atom is probably just missing udev and a few other dependencies. I don't have a definitive list to compare against, but I am working on one though.  I'll see if I can take care of this tonight as a hack in the mean time and bump it to 207.

**Comment by pSub** [comment]
Closing in favor of #8421.

**Pull request closed without merging**
