### PR TITLE
[staging-20.09] Add ghc8102BinaryMinimal to stay within hydra limits on aarch64

### PR DESCRIPTION
**Pull request by roberth**
###### Motivation for this change

Make ghc buildable on hydra for `aarch64`.

It's currently failing with `Output limit exceeded` https://hydra.nixos.org/build/129487354#tabs-summary
Hydra only allows outputs up to 2<sup>31</sup> NAR bytes.
The new `ghc8102BinaryMinimal` is 2136668000 out of 2147483648 bytes; ~10M under the limit.
This is achieved by removing the documentation and the profiling objects, neither of which are used for bootstrapping.

I have a build of GHC 8.8.4 in that's in progress. 

TODO
 - [x] finish compilation of ghc884
 - [x] inline docs

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
I wanted to build this locally but it does not eval. Tried it on x86_64-linux

**Comment by roberth** [comment]
@SuperSandro2000 fixed in `haskell.compiler.integer-simple: Exclude ghc8102Binary*`

**Comment by cole-h** [comment]
In order to fix `release-20.09` evals, I opened a separate PR with https://github.com/NixOS/nixpkgs/commit/95b230c9109cf30e7d60bcfd83f0af39d8c45792 in https://github.com/NixOS/nixpkgs/pull/102539; you might want to rebase to drop that commit ;)

(Thanks for the fix!)

**Comment by roberth** [comment]
I've
  - tested this PR locally and it can still bootstrap ghc despite removing the files that take it below the limit :tada: 
  - rebased it, cleaned up and has inline docs
  - `hydraPlatforms = []` when the docs are stripped, for legal reasons

Presumably hydra will still allow it to be built for use as a dependency.

Thanks @cole-h. I suppose ofborg was failing in the comparison step because the old version was bad, so it seems like ofborg should work now :tada:

**Comment by vcunat** [comment]
I suspect it will get into `cache.nixos.org` anyway but we'll see.

**Comment by roberth** [comment]
> I suspect it will get into `cache.nixos.org` anyway but we'll see.

If hydra only pushes closures of attributes with non-nil `hydraPlatforms`, it should work out, because it's not a runtime dependency.
We should enforce that with `disallowedRequisites`. I'll check if that can work.

**Comment by roberth** [comment]
That's a mass rebuild, so I'll skip it for 20.09, but it should be added to the forward port, to master. 20.09 should only receive backports from master anyway, catching any problems.

**Comment by vcunat** [comment]
We could switch to fixing `staging-next` before 20.09, as it apparently got unblocked.

**Comment by roberth** [comment]
I'm happy to add the forward port there, but I don't think we should delay this PR for it.

**Comment by vcunat** [comment]
```
$ nix build -f https://github.com/hercules-ci/nixpkgs/archive/minimal-ghc-to-please-hydra-limits.tar.gz ghc
error: --- ThrownError ------------------------------------------------------------------------------------ nix
Package ‘ghc-8.8.4’ in /nix/store/70bs1f100yldwvihsp03lpgsfsklps2b-source/pkgs/development/compilers/ghc/8.8.4.nix:251 is not supported on ‘aarch64-linux’, refusing to evaluate.
```

**Comment by vcunat** [comment]
Why did you touch `platforms` instead of `hydraPlatforms`?

**Comment by roberth** [comment]
> Why did you touch platforms instead of hydraPlatforms?

A mistake I didn't catch because I evaluated on `x86_64-linux`. Fixed.

**Comment by roberth** [comment]
@vcunat I'm building this locally and I've created #102614 for staging-next.

**Comment by vcunat** [comment]
Uh, I got some glitch
```
builder for '/nix/store/yzzbli3jy90w2gfiskpqwl34v79dxy18-jailbreak-cabal-1.3.5.drv' failed
  [1 of 1] Compiling Main             ( Setup.hs, /build/Main.o )
  Linking Setup ...
  
  out of memory allocating 1605596214263808 bytes after a total of 18446462599109164456 bytes
  collect2: error: ld returned 1 exit status
```
but it disappeared on retrying, so I expect I'll ignore it.

**Comment by roberth** [comment]
@ofborg eval

**Comment by roberth** [comment]
It built successfully!

**Comment by roberth** [comment]
@GrahamcOfBorg eval

**Comment by roberth** [comment]
I'll open a PR for staging-20.09 because it rebuilds haskell on other systems since the `disallowedRequisites`

**Comment by roberth** [comment]
Hydra: https://hydra.nixos.org/eval/1624086#tabs-new

**Comment by vcunat** [comment]
> I suspect it will get into `cache.nixos.org` anyway but we'll see.

```
$ nix build /nix/store/5c5bfc6n1ynr2anajix18l6brdv6dqhq-ghc-8.10.2-binary
[... fetched from cache.nixos.org]
```
(this one was used for current nixpkgs master)

**Comment by vcunat** [comment]
I think the problem here is that we utilize `cache.nixos.org` to distribute all build dependencies to the builders, so we do need to upload all the build products.

**Comment by roberth** [comment]
Some good news. I had overlooked a class of profiling files, so I've added the docs back in and we're at only 74% of the limit now.
My GHC build has been going for a while now. So far so good.

**Comment by roberth** [comment]
:heavy_check_mark: tested

**Pull request merged**
