### PR TITLE
nixos/stage-1: fix predictable interface names in initrd

### LINKED ISSUE #74328: Initrd vs predictable interface names
**Describe the bug**
Initrd networking does not use predictable interface names, but does enable DHCP on the interfaces that are specified by the normal (networking.) configuration. 

**To Reproduce**
1. Enable boot.initrd.network
2. Enable predictable interface names (default)
3. Enable useDHCP on one interface
4. Boot to initrd

**Expected behavior**
DHCP should be used on all interfaces that have DHCP enabled.

**Screenshots**
photo_2019-11-27_13-30-49

**Additional context**

**Metadata**
Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
I can't because I can not unlock the root drive without networking ;)
But here's the info from another computer running the same channel and kernel:

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0, NixOS, 20.03.20191125.89b2c0b (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20191022_9cac895`
 - channels(root): `"nixos-20.03pre202991.57cf4eb83bc"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
- boot.initrd.network
```

CC @edolstra

### PR DESCRIPTION
**Pull request by fpletz**
###### Motivation for this change
This makes predictable interfaces names available as soon as possible with udev by adding the default network link units to initrd which are read by udev. Also adds some udev rules that are needed but which would normally loaded from the udev store path which is not included in the initrd.

Also ensures that the interfaces are unconfigured before switching to stage 2, switches to klibc's ipconfig due to more features and make `boot.initrd.network.postCommands` run regardless if network setup has succeeded.

Fixes #74328 #75314 #71447.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fpletz** [comment]
@GrahamcOfBorg test predictable-interface-names initrdNetwork initrd-network-ssh

**Comment by flokli** [comment]
From a quick glace, this looks like the right way to do (at least until we have systemd in initrd).

Can somebody with a "push luks keys over ssh in initrd" setup test this? I don't currently have such a setup around, but we should make sure it now works as intended.

Also, we should add something to the release notes, so people who are using such a setup and implemented their workarounds are aware names have changed and don't lock themselves out.

**Review by Ma27 — APPROVED** [review]
I have a setup which is fairly similar to `nixos/tests/initrd-network-ssh` and tested the first commit on multiple servers, didn't find any regressions :)

**Comment by flokli** [comment]
@petabyteboy @schmittlauch @erikarvstedt @emilazy could you also give this a very firm look?

**Comment by fpletz** [comment]
cc @mweinelt for #71447

**Comment by emilazy** [comment]
I'll try and take a look at this soon -- for what it's worth, I personally successfully use [this module](https://github.com/NixOS/nixpkgs/pull/68953#issuecomment-573394801) and it's the closest thing I've seen to a Correct™ solution for this issue.

**Comment by fpletz** [comment]
@emilazy Those changes are actually included here but with some more fixes for stuff I encountered while reviewing the code. Just didn't notice @arianvp's PR earlier unfortunately.

**Comment by emilazy** [comment]
I'm referring to @ju1m's module here, not @arianvp's PR, which IIRC didn't quite work for me.

**Comment by flokli** [comment]
Marked this as a blocker, we should really try to get this fixed for 20.03.

**Comment by fpletz** [comment]
> I'm referring to @ju1m's module here, not @arianvp's PR, which IIRC didn't quite work for me.

Just for clarification: This PR should also (at least semantically) include the same changes as @ju1m's module does. Taking the rules from udev itself is better IMHO. Thanks!

**Comment by fpletz** [comment]
From the Discourse thread if anybody wants to test these changes on an existing machine with 19.09:

> I’ve cherry-picked the commits on top of the current release-19.09 branch and checked that the relevant tests still pass. Pushed to https://github.com/NixOS/nixpkgs/tree/fix-predictable-ifnames-in-initrd-19.09 so you could test with `nixpkgs=https://github.com/NixOS/nixpkgs/archive/fix-predictable-ifnames-in-initrd-19.09.tar.gz` in your NIX_PATH.

**Comment by schmittlauch** [comment]
Just tested the backport to 19.09, everything worked like a charm after removing the workaround from my config.
My setup is a classic one where I log in to an interactive `cryptsetup-askpass` running in dropbear.

I can confirm that static IP configuration via cmdline arguments also still works.

**Comment by emilazy** [comment]
This works perfectly for me on nixos-unstable-small with an sshd-based ZFS key loading setup, yay!

I'm not sure whether flushing the configuration and bringing down the interface before stage2 is the correct default, but I don't feel qualified to judge one way or the other.

**Comment by mweinelt** [comment]
> I'm not sure whether flushing the configuration and bringing down the interface before stage2 is the correct default, but I don't feel qualified to judge one way or the other.

At least without predictive naming in the initrd when you didn't flush and down the interface the unpredictive name would persist into the running system, because you can't rename interfaces while they're up.

The only issue I can imagine right now is that flushing the interfaces too early will leave clients connected via SSH stuck because their session wasn't terminated before the network went down. So maybe stop dropbear first if its up?

I'm currently unable to give this a spin, so this is the only feedback I can give right now.

**Comment by emilazy** [comment]
Yeah, I have `pkill -x dropbear` in my `boot.initrd.postMountCommands`; it'd be nice if that happened automatically.

I suppose it's also possible that the DHCP client in the initrd might be less powerful and you'd want it to run again post-stage2 (e.g. v4 vs. v6?).

**Comment by petabyteboy** [comment]
This works exactly as expected and solves many issues, thanks!

**Comment by flokli** [comment]
It should be possible to run dhcp clients at later stages, even when interfaces are not put down.
@fpletz can you elaborate on "ensures that the interfaces are unconfigured before switching to stage 2"?

I propose introduce killing dropbear in a separate PR (as it's unrelated), and probably useful even when not downing interfaces.

**Comment by fpletz** [comment]
@flokli @worldofpeace I can also split out the change that cleans up the interfaces if that helps to get the rest merged for 20.03. I consider the rest as a bugfix.

The reason to do this is the following: I encountered multiple default routes with different options when the system is fully up, at least with networkd. Therefore I think it would be wise to clean up the networking configuration in stage 1 for stage 2 to ensure no temporary configuration remains.

**Comment by flokli** [comment]
I personally think it'd be a huge improvement over the status quo, and people already work around things similar to how the PR does it to fix it.

Downing interfaces probably isn't a problem for netboot scenarios, as it's all still in the initrd, right?

**Comment by flokli** [comment]
As the branchoff already happened, this won't happen for 20.03 anymore, still: can we add it to the 20.09 changelog?

The multiple default routes are a good point - I assume it's fine to merge a version downing the interfaces, give it some time in master, and see if this causes any other problems (if we add a comment in the release notes why this was done)

**Comment by Ma27** [comment]
@fpletz may I ask if there's anything that keeps us from merging this one? :)

And I'd still like to see at least the first commit in 20.03 as it's rather non-controversial and fixes an annoying bug.

**Comment by emilazy** [comment]
Sorry to bump this again, but I'd really love to see this merged...

**Comment by flokli** [comment]
I'd be fine with that, if we add to 20.03 release notes in the first one and to 20.09 ones in the last one ;-)

**Comment by Ma27** [comment]
@fpletz any reasons against merging this (and backporting at least 44e289f93bcf6d04c3eab231bac57dade06fc0c6 to 20.03)?

If not, I'll merge this later today and backport 44e289f93bcf6d04c3eab231bac57dade06fc0c6.

**Comment by worldofpeace** [comment]
@Ma27 I believe we established in https://github.com/NixOS/nixpkgs/pull/79532#issuecomment-584089532 that the part that was strictly a bug fix could go to 20.03.

**Comment by Ma27** [comment]
Currently preparing the backport :)

**Comment by flokli** [comment]
Please don't forget the release notes (both 20.03 and master) so people know they can remove their hacks, and don't stumble into other things now working ;-)

**Comment by Ma27** [comment]
Backported the following patches:

* 332d731a7a48e79acda2e4ce79f1245999a5a2e4 (nixos/stage-1: fix predictable interfaces names)
* 3206aa985af95d48fde39c3613461882106cc7d4 (klibc: 2.0.4 -> 2.0.7)
* 173c7715dedc9c88f54e970d70464319fe93c04d (nixos/initrd-network: use ipconfig from klibc)
* 0bdf352a0589252cf63ebbf50944d213f4cd6447 (nixos/release-notes: mention fix for predictable network-interfaces in initrd)

After re-reading @fpletz previous comment, I figured that the `ipconfig`-related fix is also part of the bugfixes and the main breaking change that should not be backported is the flush of the interfaces after stage-1.

**Comment by mweinelt** [comment]
Is https://github.com/NixOS/nixpkgs/pull/79532/commits/589789997fe882668eae25f1f0578230d8576506 out of scope for a backport? It has the fix for #71447.

**Comment by flokli** [comment]
I'd personally say that's fine to backport as well, if it comes with release notes (and I'd also have preferred if those were part of the initial PR ;-), but now it is how it is)

**Comment by Ma27** [comment]
> and I'd also have preferred if those were part of the initial PR

Sorry for that, hit the PR-button too early :/

> I'd personally say that's fine to backport as well

You're right, just missed it!

**Comment by worldofpeace** [comment]
> Backported the following patches:
> 
>     * [332d731](https://github.com/NixOS/nixpkgs/commit/332d731a7a48e79acda2e4ce79f1245999a5a2e4) (nixos/stage-1: fix predictable interfaces names)
> 
>     * [3206aa9](https://github.com/NixOS/nixpkgs/commit/3206aa985af95d48fde39c3613461882106cc7d4) (klibc: 2.0.4 -> 2.0.7)
> 
>     * [173c771](https://github.com/NixOS/nixpkgs/commit/173c7715dedc9c88f54e970d70464319fe93c04d) (nixos/initrd-network: use ipconfig from klibc)
> 
>     * [0bdf352](https://github.com/NixOS/nixpkgs/commit/0bdf352a0589252cf63ebbf50944d213f4cd6447) (nixos/release-notes: mention fix for predictable network-interfaces in initrd)
> 
> 
> After re-reading @fpletz previous comment, I figured that the `ipconfig`-related fix is also part of the bugfixes and the main breaking change that should not be backported is the flush of the interfaces after stage-1.

Btw, please PR larger backports.

**Comment by Ma27** [comment]
Sorry for the delay, currently preparing a PR to backport 589789997fe882668eae25f1f0578230d8576506.

**Comment by Frostman** [comment]
@fpletz does it move building bridges to stage-1 as well? I have .useDHCP=true only for br0 and trying to understand if it'll continue working after switching to 20.03. Thanks.

**Comment by Nadrieril** [comment]
Hum, this seems to impose predictable interface names in stage-1 even if the main OS has `predictableInterfaceNames = false`. This has just cause my server to fail to get the interface up in initrd because I expected `eth0` to exist. This should at least be mentioned in the release notes I think, it's really breaking

**Comment by flokli** [comment]
@Nadrieril can you show us a minimal NixOS configuration reproducing this?

There's `nixos/tests/predictable-interface-names.nix` which should discover exactly this, and it's not failing…

**Comment by Nadrieril** [comment]
Hmm, this happened on two of my servers so it's not just a fluke and probably not hardware-related either. But it's difficult to minimize, I can't just break my servers.
The one thing that's weird is that I did not have `usePredictableInterfaceNames = false`, yet the servers used to use `eth0`-like interfaces in normal use. So it could also be that I was relying on an old bug that has been fixed in the past year. If no one else has that problem then I won't bother trying to understand this mess.

**Comment by Ma27** [comment]
That's most likely the case: without this PR, NixOS had `eth0`-like interfaces when configuring a network in the `initrd`.

**Comment by Nadrieril** [comment]
Ohh, you mean the interface set up in initrd would carry on to the booted system? That explains a lot!

**Comment by ju1m** [comment]
@Nadrieril yes the interface names are kept from stage-1 to stage-2, AFAIU there's no more than a `pivot_root` between the two, no `rmmod` and `modprobe` that would reset the interface names. I've explained this in detail in this proposal https://github.com/NixOS/nixpkgs/pull/68953#issuecomment-573394801 ; note that I'm still using this code and it still work for me.

**Comment by flokli** [comment]
So this PR actually fixed a bug we didn't know about - even with `networking.usePredictableInterfaceNames` set to `true` (the default), doing things with them in initrd caused them to stick with their non-predictable name.

I don't think that's a bug we should consider a feature and apply workarounds for ;-)

We should however update the release note entry explaining the possibly changed behaviour, so people reading those are made aware.

**Comment by flokli** [comment]
Ah, nvm - we already refer to this PR in the release notes, and as this landed in 20.03 already, the amount of people still running into it while upgrading should be somewhat small.

**Comment by Ma27** [comment]
> So this PR actually fixed a bug we didn't know about - even with networking.usePredictableInterfaceNames set to true (the default), doing things with them in initrd caused them to stick with their non-predictable name.

Well, actually this was one of the main issues before this PR (and one of the biggest challenges I had while trying to upgrade to 19.09).

The problem was that `[they] did not have usePredictableInterfaceNames = false`, so AFAICS everything works as expected now, right?

**Pull request merged**
