### PR TITLE
Many updates

### PR DESCRIPTION
**Pull request by AndersonTorres**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by thiagokokada — COMMENTED** [review]
I don't know what other maintainers would prefer, but I would prefer this to be split in multiple commits. At least, one for the bump and other for the refactors (migrating to cmake, moving to libraries).

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 108801` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>libjson-rpc-cpp</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>argtable</li>
    <li>clustal-omega</li>
  </ul>
</details>

**Comment by AndersonTorres** [comment]
> I don't know what other maintainers would prefer, but I would prefer this to be split in multiple commits. At least, one for the bump and other for the refactors (migrating to cmake, moving to libraries).

Moving files to more meaningful locations doesn't change the outputs. After all, if someone was crazy enough, all the packages could be put in a same directory...

**Comment by thiagokokada** [comment]
> Moving files to more meaningful locations doesn't change the outputs. After all, if someone was crazy enough, all the packages could be put in a same directory...

Yeah, I know, but the reason I am saying this is because this makes the review easier.

For now, it is very difficult to understand what is changing because I can't really diff your changes thanks to the file you moved. If this was a separate commit I could look commit by commit to understand whats happening.

**Comment by AndersonTorres** [comment]
Unbfortunately git is very dumb on this aspect. Even if you use git commands to highlight a change, it treats it as a delete-plus-create.

On the case at point, libjson-rpc-cpp fails with this message:

> 
> libjson-rpc-cpp> build flags: SHELL=/nix/store/zcl19h06322c3kss6bvf05w2pxg4kfll-bash-4.4-p23/bin/bash
> libjson-rpc-cpp> Scanning dependencies of target jsonrpccommon
> libjson-rpc-cpp> [  1%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpccommon.dir/common/errors.cpp.o
> libjson-rpc-cpp> [  2%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpccommon.dir/common/exception.cpp.o
> libjson-rpc-cpp> [  4%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpccommon.dir/common/procedure.cpp.o
> libjson-rpc-cpp> [  5%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpccommon.dir/common/specificationparser.cpp.o
> libjson-rpc-cpp> /build/source/src/jsonrpccpp/common/specificationparser.cpp: In static member function 'static std::vector<jsonrpc::Procedure> jsonrpc::SpecificationParser::GetProceduresFromString(const string&)':
> libjson-rpc-cpp> /build/source/src/jsonrpccpp/common/specificationparser.cpp:27:16: warning: 'Reader' is deprecated: Use CharReader and CharReaderBuilder instead. [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations8;;]
> libjson-rpc-cpp>    27 |   Json::Reader reader;
> libjson-rpc-cpp>       |                ^~~~~~
> libjson-rpc-cpp> In file included from /nix/store/flfgmrd00q5dh6mr4dfd7yhfmw48284f-jsoncpp-1.9.4-dev/include/json/json.h:11,
> libjson-rpc-cpp>                  from /build/source/Build/gen/jsonrpccpp/common/jsonparser.h:13,
> libjson-rpc-cpp>                  from /build/source/src/jsonrpccpp/common/procedure.h:16,
> libjson-rpc-cpp>                  from /build/source/src/jsonrpccpp/common/specificationparser.h:13,
> libjson-rpc-cpp>                  from /build/source/src/jsonrpccpp/common/specificationparser.cpp:10:
> libjson-rpc-cpp> /nix/store/flfgmrd00q5dh6mr4dfd7yhfmw48284f-jsoncpp-1.9.4-dev/include/json/reader.h:37:63: note: declared here
> libjson-rpc-cpp>    37 |     "Use CharReader and CharReaderBuilder instead.") JSON_API Reader {
> libjson-rpc-cpp>       |                                                               ^~~~~~
> libjson-rpc-cpp> /build/source/src/jsonrpccpp/common/specificationparser.cpp:27:16: warning: 'Json::Reader::Reader()' is deprecated: Use CharReader and CharReaderBuilder instead [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations8;;]
> libjson-rpc-cpp>    27 |   Json::Reader reader;
> libjson-rpc-cpp>       |                ^~~~~~
> libjson-rpc-cpp> In file included from /nix/store/flfgmrd00q5dh6mr4dfd7yhfmw48284f-jsoncpp-1.9.4-dev/include/json/json.h:11,
> libjson-rpc-cpp>                  from /build/source/Build/gen/jsonrpccpp/common/jsonparser.h:13,
> libjson-rpc-cpp>                  from /build/source/src/jsonrpccpp/common/procedure.h:16,
> libjson-rpc-cpp>                  from /build/source/src/jsonrpccpp/common/specificationparser.h:13,
> libjson-rpc-cpp>                  from /build/source/src/jsonrpccpp/common/specificationparser.cpp:10:
> libjson-rpc-cpp> /nix/store/flfgmrd00q5dh6mr4dfd7yhfmw48284f-jsoncpp-1.9.4-dev/include/json/reader.h:56:3: note: declared here
> libjson-rpc-cpp>    56 |   Reader();
> libjson-rpc-cpp>       |   ^~~~~~
> libjson-rpc-cpp> [  6%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpccommon.dir/common/specificationwriter.cpp.o
> libjson-rpc-cpp> [  8%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpccommon.dir/common/streamreader.cpp.o
> libjson-rpc-cpp> [  9%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpccommon.dir/common/streamwriter.cpp.o
> libjson-rpc-cpp> [ 10%] Linking CXX shared library ../../lib/libjsonrpccpp-common.so
> libjson-rpc-cpp> [ 10%] Built target jsonrpccommon
> libjson-rpc-cpp> Scanning dependencies of target jsonrpcserver
> libjson-rpc-cpp> [ 12%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/server/abstractprotocolhandler.cpp.o
> libjson-rpc-cpp> /build/source/src/jsonrpccpp/server/abstractprotocolhandler.cpp: In member function 'virtual void jsonrpc::AbstractProtocolHandler::HandleRequest(const string&, std::string&)':
> libjson-rpc-cpp> /build/source/src/jsonrpccpp/server/abstractprotocolhandler.cpp:31:16: warning: 'Reader' is deprecated: Use CharReader and CharReaderBuilder instead. [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations8;;]
> libjson-rpc-cpp>    31 |   Json::Reader reader;
> libjson-rpc-cpp>       |                ^~~~~~
> libjson-rpc-cpp> In file included from /nix/store/flfgmrd00q5dh6mr4dfd7yhfmw48284f-jsoncpp-1.9.4-dev/include/json/json.h:11,
> libjson-rpc-cpp>                  from /build/source/Build/gen/jsonrpccpp/common/jsonparser.h:13,
> libjson-rpc-cpp>                  from /build/source/src/jsonrpccpp/../jsonrpccpp/common/procedure.h:16,
> libjson-rpc-cpp>                  from /build/source/src/jsonrpccpp/server/abstractprotocolhandler.h:17,
> libjson-rpc-cpp>                  from /build/source/src/jsonrpccpp/server/abstractprotocolhandler.cpp:10:
> libjson-rpc-cpp> /nix/store/flfgmrd00q5dh6mr4dfd7yhfmw48284f-jsoncpp-1.9.4-dev/include/json/reader.h:37:63: note: declared here
> libjson-rpc-cpp>    37 |     "Use CharReader and CharReaderBuilder instead.") JSON_API Reader {
> libjson-rpc-cpp>       |                                                               ^~~~~~
> libjson-rpc-cpp> /build/source/src/jsonrpccpp/server/abstractprotocolhandler.cpp:31:16: warning: 'Json::Reader::Reader()' is deprecated: Use CharReader and CharReaderBuilder instead [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations8;;]
> libjson-rpc-cpp>    31 |   Json::Reader reader;
> libjson-rpc-cpp>       |                ^~~~~~
> libjson-rpc-cpp> In file included from /nix/store/flfgmrd00q5dh6mr4dfd7yhfmw48284f-jsoncpp-1.9.4-dev/include/json/json.h:11,
> libjson-rpc-cpp>                  from /build/source/Build/gen/jsonrpccpp/common/jsonparser.h:13,
> libjson-rpc-cpp>                  from /build/source/src/jsonrpccpp/../jsonrpccpp/common/procedure.h:16,
> libjson-rpc-cpp>                  from /build/source/src/jsonrpccpp/server/abstractprotocolhandler.h:17,
> libjson-rpc-cpp>                  from /build/source/src/jsonrpccpp/server/abstractprotocolhandler.cpp:10:
> libjson-rpc-cpp> /nix/store/flfgmrd00q5dh6mr4dfd7yhfmw48284f-jsoncpp-1.9.4-dev/include/json/reader.h:56:3: note: declared here
> libjson-rpc-cpp>    56 |   Reader();
> libjson-rpc-cpp>       |   ^~~~~~
> libjson-rpc-cpp> [ 13%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/server/abstractserverconnector.cpp.o
> libjson-rpc-cpp> [ 15%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/server/abstractthreadedserver.cpp.o
> libjson-rpc-cpp> [ 16%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/server/requesthandlerfactory.cpp.o
> libjson-rpc-cpp> [ 17%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/server/rpcprotocolserver12.cpp.o
> libjson-rpc-cpp> /build/source/src/jsonrpccpp/server/rpcprotocolserver12.cpp: In member function 'virtual void jsonrpc::RpcProtocolServer12::HandleRequest(const string&, std::string&)':
> libjson-rpc-cpp> /build/source/src/jsonrpccpp/server/rpcprotocolserver12.cpp:25:16: warning: 'Reader' is deprecated: Use CharReader and CharReaderBuilder instead. [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations8;;]
> libjson-rpc-cpp>    25 |   Json::Reader reader;
> libjson-rpc-cpp>       |                ^~~~~~
> libjson-rpc-cpp> In file included from /nix/store/flfgmrd00q5dh6mr4dfd7yhfmw48284f-jsoncpp-1.9.4-dev/include/json/json.h:11,
> libjson-rpc-cpp>                  from /build/source/Build/gen/jsonrpccpp/common/jsonparser.h:13,
> libjson-rpc-cpp>                  from /build/source/src/jsonrpccpp/../jsonrpccpp/common/procedure.h:16,
> libjson-rpc-cpp>                  from /build/source/src/jsonrpccpp/server/abstractprotocolhandler.h:17,
> libjson-rpc-cpp>                  from /build/source/src/jsonrpccpp/server/rpcprotocolserver12.h:13,
> libjson-rpc-cpp>                  from /build/source/src/jsonrpccpp/server/rpcprotocolserver12.cpp:10:
> libjson-rpc-cpp> /nix/store/flfgmrd00q5dh6mr4dfd7yhfmw48284f-jsoncpp-1.9.4-dev/include/json/reader.h:37:63: note: declared here
> libjson-rpc-cpp>    37 |     "Use CharReader and CharReaderBuilder instead.") JSON_API Reader {
> libjson-rpc-cpp>       |                                                               ^~~~~~
> libjson-rpc-cpp> /build/source/src/jsonrpccpp/server/rpcprotocolserver12.cpp:25:16: warning: 'Json::Reader::Reader()' is deprecated: Use CharReader and CharReaderBuilder instead [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations8;;]
> libjson-rpc-cpp>    25 |   Json::Reader reader;
> libjson-rpc-cpp>       |                ^~~~~~
> libjson-rpc-cpp> In file included from /nix/store/flfgmrd00q5dh6mr4dfd7yhfmw48284f-jsoncpp-1.9.4-dev/include/json/json.h:11,
> libjson-rpc-cpp>                  from /build/source/Build/gen/jsonrpccpp/common/jsonparser.h:13,
> libjson-rpc-cpp>                  from /build/source/src/jsonrpccpp/../jsonrpccpp/common/procedure.h:16,
> libjson-rpc-cpp>                  from /build/source/src/jsonrpccpp/server/abstractprotocolhandler.h:17,
> libjson-rpc-cpp>                  from /build/source/src/jsonrpccpp/server/rpcprotocolserver12.h:13,
> libjson-rpc-cpp>                  from /build/source/src/jsonrpccpp/server/rpcprotocolserver12.cpp:10:
> libjson-rpc-cpp> /nix/store/flfgmrd00q5dh6mr4dfd7yhfmw48284f-jsoncpp-1.9.4-dev/include/json/reader.h:56:3: note: declared here
> libjson-rpc-cpp>    56 |   Reader();
> libjson-rpc-cpp>       |   ^~~~~~
> libjson-rpc-cpp> [ 19%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/server/rpcprotocolserverv1.cpp.o
> libjson-rpc-cpp> [ 20%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/server/rpcprotocolserverv2.cpp.o
> libjson-rpc-cpp> [ 21%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/server/connectors/httpserver.cpp.o
> libjson-rpc-cpp> /build/source/src/jsonrpccpp/server/connectors/httpserver.cpp: In member function 'virtual bool jsonrpc::HttpServer::StartListening()':
> libjson-rpc-cpp> /build/source/src/jsonrpccpp/server/connectors/httpserver.cpp:79:60: error: invalid conversion from 'int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, size_t*, void**)' {aka 'int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, long unsigned int*, void**)'} to 'MHD_AccessHandlerCallback' {aka 'MHD_Result (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, long unsigned int*, void**)'} [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-fpermissive-fpermissive8;;]
> libjson-rpc-cpp>    79 |             mhd_flags, this->port, NULL, NULL, HttpServer::callback, this,
> libjson-rpc-cpp>       |                                                ~~~~~~~~~~~~^~~~~~~~
> libjson-rpc-cpp>       |                                                            |
> glibjson-rpc-cpp>       |                                                            int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, size_t*, void**) {aka int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, long unsigned int*, void**)}
> libjson-rpc-cpp> In file included from /build/source/src/jsonrpccpp/server/connectors/httpserver.h:33,
> libjson-rpc-cpp>                  from /build/source/src/jsonrpccpp/server/connectors/httpserver.cpp:10:
> libjson-rpc-cpp> /nix/store/qfyczzgvf9ykamaaj78i8m6ca0vvxr42-libmicrohttpd-0.9.72-dev/include/microhttpd.h:2443:45: note:   initializing argument 5 of 'MHD_Daemon* MHD_start_daemon(unsigned int, uint16_t, MHD_AcceptPolicyCallback, void*, MHD_AccessHandlerCallback, void*, ...)'
> libjson-rpc-cpp>  2443 |                   MHD_AccessHandlerCallback dh, void *dh_cls,
> libjson-rpc-cpp>       |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
> libjson-rpc-cpp> /build/source/src/jsonrpccpp/server/connectors/httpserver.cpp:89:25: error: invalid conversion from 'int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, size_t*, void**)' {aka 'int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, long unsigned int*, void**)'} to 'MHD_AccessHandlerCallback' {aka 'MHD_Result (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, long unsigned int*, void**)'} [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-fpermissive-fpermissive8;;]
> libjson-rpc-cpp>    89 |             HttpServer::callback, this, MHD_OPTION_HTTPS_MEM_KEY,
> libjson-rpc-cpp>       |             ~~~~~~~~~~~~^~~~~~~~
> libjson-rpc-cpp>       |                         |
> libjson-rpc-cpp>       |                         int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, size_t*, void**) {aka int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, long unsigned int*, void**)}
> libjson-rpc-cpp> In file included from /build/source/src/jsonrpccpp/server/connectors/httpserver.h:33,
> libjson-rpc-cpp>                  from /build/source/src/jsonrpccpp/server/connectors/httpserver.cpp:10:
> libjson-rpc-cpp> /nix/store/qfyczzgvf9ykamaaj78i8m6ca0vvxr42-libmicrohttpd-0.9.72-dev/include/microhttpd.h:2443:45: note:   initializing argument 5 of 'MHD_Daemon* MHD_start_daemon(unsigned int, uint16_t, MHD_AcceptPolicyCallback, void*, MHD_AccessHandlerCallback, void*, ...)'
> libjson-rpc-cpp>  2443 |                   MHD_AccessHandlerCallback dh, void *dh_cls,
> libjson-rpc-cpp>       |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
> libjson-rpc-cpp> /build/source/src/jsonrpccpp/server/connectors/httpserver.cpp:98:58: error: invalid conversion from 'int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, size_t*, void**)' {aka 'int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, long unsigned int*, void**)'} to 'MHD_AccessHandlerCallback' {aka 'MHD_Result (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, long unsigned int*, void**)'} [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-fpermissive-fpermissive8;;]
> libjson-rpc-cpp>    98 |           mhd_flags, this->port, NULL, NULL, HttpServer::callback, this,
> libjson-rpc-cpp>       |                                              ~~~~~~~~~~~~^~~~~~~~
> libjson-rpc-cpp>       |                                                          |
> libjson-rpc-cpp>       |                                                          int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, size_t*, void**) {aka int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, long unsigned int*, void**)}
> libjson-rpc-cpp> In file included from /build/source/src/jsonrpccpp/server/connectors/httpserver.h:33,
> libjson-rpc-cpp>                  from /build/source/src/jsonrpccpp/server/connectors/httpserver.cpp:10:
> libjson-rpc-cpp> /nix/store/qfyczzgvf9ykamaaj78i8m6ca0vvxr42-libmicrohttpd-0.9.72-dev/include/microhttpd.h:2443:45: note:   initializing argument 5 of 'MHD_Daemon* MHD_start_daemon(unsigned int, uint16_t, MHD_AcceptPolicyCallback, void*, MHD_AccessHandlerCallback, void*, ...)'
> libjson-rpc-cpp>  2443 |                   MHD_AccessHandlerCallback dh, void *dh_cls,
> libjson-rpc-cpp>       |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
> libjson-rpc-cpp> make[2]: *** [src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/build.make:173: src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/server/connectors/httpserver.cpp.o] Error 1
> libjson-rpc-cpp> make[1]: *** [CMakeFiles/Makefile2:253: src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/all] Error 2
> libjson-rpc-cpp> make: *** [Makefile:182: all] Error 2
> error: --- Error ----------------------------------------------------------------------------------------------------------------- nix
> error: --- Error --- nix-daemon
> builder for '/nix/store/fljvpghjijn9x3lmyxix1r3d4l8w4qqh-libjson-rpc-cpp-1.3.0.drv' failed with exit code 2; last 10 log lines:
>         |                                                          |
>         |                                                          int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, size_t*, void**) {aka int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, long unsigned int*, void**)}
>   In file included from /build/source/src/jsonrpccpp/server/connectors/httpserver.h:33,
>                    from /build/source/src/jsonrpccpp/server/connectors/httpserver.cpp:10:
>   /nix/store/qfyczzgvf9ykamaaj78i8m6ca0vvxr42-libmicrohttpd-0.9.72-dev/include/microhttpd.h:2443:45: note:   initializing argument 5 of 'MHD_Daemon* MHD_start_daemon(unsigned int, uint16_t, MHD_AcceptPolicyCallback, void*, MHD_AccessHandlerCallback, void*, ...)'
>    2443 |                   MHD_AccessHandlerCallback dh, void *dh_cls,
>         |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
>   make[2]: *** [src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/build.make:173: src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/server/connectors/httpserver.cpp.o] Error 1
>   make[1]: *** [CMakeFiles/Makefile2:253: src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/all] Error 2
>   make: *** [Makefile:182: all] Error 2

**Comment by AndersonTorres** [comment]
Error reported here too:

https://github.com/cinemast/libjson-rpc-cpp/pull/299

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108801` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>libjson-rpc-cpp: log <a href="https://termbin.com/ku8l">https://termbin.com/ku8l</a></li>
  </ul>
</details>
<details>
<summary>
2 packages built:
</summary>
<ul>
<li>argtable</li>
<li>clustal-omega</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108801` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>argtable</li>
<li>clustal-omega</li>
<li>libmicrohttpd_0_9_72</li>
</ul>
</details>

**Comment by AndersonTorres** [comment]
I will erase the latest upload. It causes a massive rebuild.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108801` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>libjson-rpc-cpp: log <a href="https://termbin.com/6wdn">https://termbin.com/6wdn</a></li>
  </ul>
</details>
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>argtable</li>
<li>clustal-omega</li>
<li>libmicrohttpd_0_9_72</li>
</ul>
</details>

**Comment by AndersonTorres** [comment]
I am also fixing libjson-rpc-cpp in this commit.

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 108801` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>argtable</li>
    <li>clustal-omega</li>
    <li>libjson-rpc-cpp (libjson_rpc_cpp)</li>
    <li>libmicrohttpd_0_9_72</li>
  </ul>
</details>

**Review by thiagokokada — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108801` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>argtable</li>
<li>clustal-omega</li>
<li>libmicrohttpd_0_9_72</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108801` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
4 packages built:
</summary>
<ul>
<li>argtable</li>
<li>clustal-omega</li>
<li>libjson-rpc-cpp</li>
<li>libmicrohttpd_0_9_72</li>
</ul>
</details>

**Pull request merged**
