### PR TITLE
haskell.compiler.ghcHEAD: disable DWARF on non x86

### PR DESCRIPTION
**Pull request by sternenseemann**
The broken build of ghcHEAD on aarch64-linux results from rts/Libdw.c
not supporting that platform. Seemingly this particular file is only
relevant for DWARF support in GHC, so we disable that on unsupported
platforms.

(untested)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
@ofborg build haskell.compiler.ghcHEAD

**Comment by sternenseemann** [comment]
@ofborg build haskell.compiler.ghcHEAD

**Comment by sternenseemann** [comment]
Gonna merge this tomorrow if no one objects, hydra should tell us if it indeed fixes the build.

**Comment by cdepillabout** [comment]
It looks like ofborg successfully built this on x86-64 linux, so I'll merge in and see what hydra thinks about this on aarch64.

Thanks for looking into this!

**Pull request merged**
