### PR TITLE
[staging] perlPackages: bulk update

### PR DESCRIPTION
**Pull request by stigtsp**
###### Motivation for this change

This is the first semi-automatic bulk update of `perlPackages` using [nix-update-cpan](https://github.com/stigtsp/nix-update-cpan), when stable the plan is to add this tool to `maintainers/scripts/`

Changes to dependencies have been added manually. 

Cc: @aanderse @zakame @SuperSandro2000 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by adisbladis** [comment]
@GrahamcOfBorg build hydra-unstable

**Comment by aanderse** [comment]
Thanks for doing this @stigtsp :heart: The diffs look fine...

**Comment by stigtsp** [comment]
@GrahamcOfBorg build perlPackages.YAMLPP perlPackages.YAMLSyck perlPackages.XMLWriter perlPackages.XMLRSS perlPackages.XMLLibXML perlPackages.WWWMechanize perlPackages.Version perlPackages.UserIdentity perlPackages.URI perlPackages.TypesSerialiser perlPackages.TypeTiny perlPackages.TieRefHash perlPackages.TieHashIndexed perlPackages.TextSprintfNamed perlPackages.TextBalanced perlPackages.TestWWWMechanize perlPackages.TestSimple13 perlPackages.TestRunValgrind perlPackages.TestRunPluginTrimDisplayedFilenames perlPackages.TestRunPluginColorSummary perlPackages.TestRunPluginColorFileVerdicts perlPackages.TestRunPluginBreakOnFailure perlPackages.TestRunPluginAlternateInterpreters perlPackages.TestRunCmdLine perlPackages.TestRun perlPackages.TestMockModule perlPackages.TestEOL perlPackages.TestDataSplit perlPackages.Test2Suite perlPackages.TermShell perlPackages.TaskTestRunAllPlugins perlPackages.TaskFreecellSolverTesting perlPackages.SubHandlesVia perlPackages.StringRandom perlPackages.StringCRC32 perlPackages.StatisticsDescriptive perlPackages.SQLTranslator perlPackages.SQLStatement perlPackages.SQLAbstractLimit perlPackages.SearchXapian perlPackages.PodSimple perlPackages.PodMarkdown perlPackages.podlators perlPackages.PodChecker perlPackages.PadWalker perlPackages.PPIxRegexp perlPackages.PPIxQuoteLike perlPackages.Plack perlPackages.PkgConfig perlPackages.PerlTidy perlPackages.PerlIOutf8_strict perlPackages.PDL perlPackages.ParsePMFile perlPackages.PARDist perlPackages.ParamsValidate perlPackages.ParamsUtil perlPackages.PackageStash perlPackages.NetOpenSSH perlPackages.OggVorbisHeaderPurePerl perlPackages.NumberFraction perlPackages.NetPing perlPackages.NetLDAPSID perlPackages.NetDNS perlPackages.NetAmazonS3 perlPackages.MusicBrainzDiscID perlPackages.MooXHandlesVia perlPackages.Moo perlPackages.MojoPg perlPackages.MojoJWT perlPackages.MojoRedis perlPackages.MojoliciousPluginOpenAPI perlPackages.MojoliciousPluginAssetPack perlPackages.Minion perlPackages.MIMETypes perlPackages.MailMessage perlPackages.MacPasteboard perlPackages.LWP perlPackages.LogLog4perl perlPackages.LocaleCodes perlPackages.ListMoreUtilsXS perlPackages.ListMoreUtils perlPackages.LinkEmbedder perlPackages.LinguaStem perlPackages.LinguaENInflect perlPackages.libnet perlPackages.libintl_perl perlPackages.JSONXS perlPackages.JSONValidator perlPackages.JSONMaybeXS perlPackages.IPCSysV perlPackages.IOTty perlPackages.IOPager perlPackages.IOHTML perlPackages.IOAIO perlPackages.HTTPMessage perlPackages.HTTPEntityParser perlPackages.HTTPDaemon perlPackages.HTTPCookies perlPackages.HTTPCookieJar perlPackages.HTMLTableExtract perlPackages.Graph perlPackages.Gnome2Canvas perlPackages.GlibObjectIntrospection perlPackages.GitAutofixup perlPackages.GD perlPackages.FileShareDir perlPackages.FileRemove perlPackages.FilePath perlPackages.FileMimeInfo perlPackages.FileLoadLines perlPackages.FileListing perlPackages.FileHomeDir perlPackages.ExtUtilsMakeMaker perlPackages.ExtUtilsInstall perlPackages.Encode perlPackages.EmailSender perlPackages.EmailOutlookMessage perlPackages.DistZilla perlPackages.DBIxClass perlPackages.DBFile perlPackages.DBDMock perlPackages.DBDCSV perlPackages.DevelPPPort perlPackages.DevelPatchPerl perlPackages.DevelCheckOS perlPackages.DateTimeTimeZone perlPackages.DateTimeFormatNatural perlPackages.DateTimeFormatISO8601 perlPackages.DateTime perlPackages.DateManip perlPackages.Curses perlPackages.CryptTwofish perlPackages.CryptRijndael perlPackages.CryptRIPEMD160 perlPackages.CPANPerlReleases perlPackages.CpanelJSONXS perlPackages.Connector perlPackages.ConfigAutoConf perlPackages.ClonePP perlPackages.ClassSingleton perlPackages.ClassC3 perlPackages.CGI perlPackages.CDB_File perlPackages.CatalystRuntime perlPackages.CatalystDevel perlPackages.CarpAssertMore perlPackages.Cairo perlPackages.CacheFastMmap perlPackages.BerkeleyDB perlPackages.AuthenRadius perlPackages.ArchiveTarWrapper perlPackages.ArrayCompare perlPackages.Appperlbrew perlPackages.Applify perlPackages.ApacheSession perlPackages.AlienLibxml2 perlPackages.AlienBuild perlPackages.AlgorithmC3

**Comment by stigtsp** [comment]
# perlPackages.MacPasteboard excluded
@GrahamcOfBorg build perlPackages.YAMLPP perlPackages.YAMLSyck perlPackages.XMLWriter perlPackages.XMLRSS perlPackages.XMLLibXML perlPackages.WWWMechanize perlPackages.Version perlPackages.UserIdentity perlPackages.URI perlPackages.TypesSerialiser perlPackages.TypeTiny perlPackages.TieRefHash perlPackages.TieHashIndexed perlPackages.TextSprintfNamed perlPackages.TextBalanced perlPackages.TestWWWMechanize perlPackages.TestSimple13 perlPackages.TestRunValgrind perlPackages.TestRunPluginTrimDisplayedFilenames perlPackages.TestRunPluginColorSummary perlPackages.TestRunPluginColorFileVerdicts perlPackages.TestRunPluginBreakOnFailure perlPackages.TestRunPluginAlternateInterpreters perlPackages.TestRunCmdLine perlPackages.TestRun perlPackages.TestMockModule perlPackages.TestEOL perlPackages.TestDataSplit perlPackages.Test2Suite perlPackages.TermShell perlPackages.TaskTestRunAllPlugins perlPackages.TaskFreecellSolverTesting perlPackages.SubHandlesVia perlPackages.StringRandom perlPackages.StringCRC32 perlPackages.StatisticsDescriptive perlPackages.SQLTranslator perlPackages.SQLStatement perlPackages.SQLAbstractLimit perlPackages.SearchXapian perlPackages.PodSimple perlPackages.PodMarkdown perlPackages.podlators perlPackages.PodChecker perlPackages.PadWalker perlPackages.PPIxRegexp perlPackages.PPIxQuoteLike perlPackages.Plack perlPackages.PkgConfig perlPackages.PerlTidy perlPackages.PerlIOutf8_strict perlPackages.PDL perlPackages.ParsePMFile perlPackages.PARDist perlPackages.ParamsValidate perlPackages.ParamsUtil perlPackages.PackageStash perlPackages.NetOpenSSH perlPackages.OggVorbisHeaderPurePerl perlPackages.NumberFraction perlPackages.NetPing perlPackages.NetLDAPSID perlPackages.NetDNS perlPackages.NetAmazonS3 perlPackages.MusicBrainzDiscID perlPackages.MooXHandlesVia perlPackages.Moo perlPackages.MojoPg perlPackages.MojoJWT perlPackages.MojoRedis perlPackages.MojoliciousPluginOpenAPI perlPackages.MojoliciousPluginAssetPack perlPackages.Minion perlPackages.MIMETypes perlPackages.MailMessage perlPackages.LWP perlPackages.LogLog4perl perlPackages.LocaleCodes perlPackages.ListMoreUtilsXS perlPackages.ListMoreUtils perlPackages.LinkEmbedder perlPackages.LinguaStem perlPackages.LinguaENInflect perlPackages.libnet perlPackages.libintl_perl perlPackages.JSONXS perlPackages.JSONValidator perlPackages.JSONMaybeXS perlPackages.IPCSysV perlPackages.IOTty perlPackages.IOPager perlPackages.IOHTML perlPackages.IOAIO perlPackages.HTTPMessage perlPackages.HTTPEntityParser perlPackages.HTTPDaemon perlPackages.HTTPCookies perlPackages.HTTPCookieJar perlPackages.HTMLTableExtract perlPackages.Graph perlPackages.Gnome2Canvas perlPackages.GlibObjectIntrospection perlPackages.GitAutofixup perlPackages.GD perlPackages.FileShareDir perlPackages.FileRemove perlPackages.FilePath perlPackages.FileMimeInfo perlPackages.FileLoadLines perlPackages.FileListing perlPackages.FileHomeDir perlPackages.ExtUtilsMakeMaker perlPackages.ExtUtilsInstall perlPackages.Encode perlPackages.EmailSender perlPackages.EmailOutlookMessage perlPackages.DistZilla perlPackages.DBIxClass perlPackages.DBFile perlPackages.DBDMock perlPackages.DBDCSV perlPackages.DevelPPPort perlPackages.DevelPatchPerl perlPackages.DevelCheckOS perlPackages.DateTimeTimeZone perlPackages.DateTimeFormatNatural perlPackages.DateTimeFormatISO8601 perlPackages.DateTime perlPackages.DateManip perlPackages.Curses perlPackages.CryptTwofish perlPackages.CryptRijndael perlPackages.CryptRIPEMD160 perlPackages.CPANPerlReleases perlPackages.CpanelJSONXS perlPackages.Connector perlPackages.ConfigAutoConf perlPackages.ClonePP perlPackages.ClassSingleton perlPackages.ClassC3 perlPackages.CGI perlPackages.CDB_File perlPackages.CatalystRuntime perlPackages.CatalystDevel perlPackages.CarpAssertMore perlPackages.Cairo perlPackages.CacheFastMmap perlPackages.BerkeleyDB perlPackages.AuthenRadius perlPackages.ArchiveTarWrapper perlPackages.ArrayCompare perlPackages.Appperlbrew perlPackages.Applify perlPackages.ApacheSession perlPackages.AlienLibxml2 perlPackages.AlienBuild perlPackages.AlgorithmC3

**Comment by stigtsp** [comment]
Ready to merge, IMHO. All packages bumped build OK on linux x64 (except MacPasteboard)

**Review by aanderse — APPROVED** [review]
Thanks again @stigtsp! I'll look to @adisbladis to click merge, please.

**Comment by Mic92** [comment]
Thanks!

**Pull request merged**
