### PR TITLE
vulkan: 1.2.141 -> 1.2.162

### PR DESCRIPTION
**Pull request by expipiplus1**
Also improve metadata for vulkan-validation-layers

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by Ralith — APPROVED** [review]

**Comment by expipiplus1** [comment]
Thanks for the approval, @Ralith. Is it possible to merge this now that the checks have also passed?

**Comment by expipiplus1** [comment]
Have tested this now with a raytracing example and the validation layer works very well!

**Comment by expipiplus1** [comment]
Is it possible to get this merged, please?

**Comment by spacekitteh** [comment]
@Ralith

**Comment by spacekitteh** [comment]
> Have tested this now with a raytracing example and the validation layer works very well!

I'm waiting on this to test your Haskell RT example, lol

**Comment by Ralith** [comment]
@spacekitteh hi

**Comment by expipiplus1** [comment]
> I'm waiting on this to test your Haskell RT example, lol

It runs with the older SDK still, but not with the validation layer (for the best though as otherwise my invalid Vulkan usage would be visible!)

**Comment by expipiplus1** [comment]
Thanks!

**Pull request merged**
