### PR TITLE
scala-cli: add aarch64-darwin to sources

### PR DESCRIPTION
**Pull request by regadas**
###### Description of changes

Temporarily use x86 binaries via rosetta.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kubukoz** [comment]
I'm not sure this should've been merged - the x86 binary can be used via an overlay and we don't currently have similar workarounds for packages like `bloop` (similar situation, native image).

(also not sure why GH didn't notify me as a maintainer)

**Comment by uri-canva** [comment]
@kubukoz I think we shouldn't do this, if someone wants to use nix packages through rosetta they can always explicitly set `system` to `x86_64-darwin`, but if the package set is a mix of `x86_64-darwin` and `aarch64-darwin` someone who wants to avoid rosetta doesn't have a good way of doing so.

I can revert it if you agree.

**Comment by regadas** [comment]
Hi, y'all. Looking back and knowing more about Nix now, I also feel this should not be the way to go. All pkgs should follow the same strategy otherwise, it's the source of confusion.

I went ahead and created https://github.com/NixOS/nixpkgs/pull/183601 please take a look.

@kubukoz sorry I missed your reply 🙏

**Comment by kubukoz** [comment]
to be fair, since I wrote the comment I changed my mind - using this PR, I didn't have to fetch/build any x86-specific derivations (except for scala-cli itself), so I didn't need x86's coreutils or anything like that - it was working pretty well, too. Happy either way :)

**Pull request merged**
