### PR TITLE
mirrors: add cran mirrors

### PR DESCRIPTION
**Pull request by nviets**
###### Description of changes

Added CRAN to mirrors.nix and updated reference in r-modules.

###### Things done

Generated R packages set for CRAN successfully.

@jbedo @alexvorobiev

### CODE REVIEW

**Comment by nviets** [comment]
Would you rather there be a posit entry in mirrors.nix instead? Posit releases it's own packages directly to CRAN, so there isn't really a separate posit-only mirror. Posit is just archiving those snapshots of CRAN, and, if MRAN was still active or another mirror appeared, we could add it to the same section. My understanding (which could be wrong), is fetchurl will simply traverse the list of mirrors until it finds the desired package.

Btw, posit also does bioconductor snapshots

**Comment by jbedo** [comment]
The naming is misleading as it's not an official CRAN mirror (see
https://cran.r-project.org/mirrors.html) and as it's not official it has
a different directory layout and so is not interchangeable.

There seems little advantage to refactoring posit out into a list of
mirrors at this point, as I am not aware of any posit snapshot mirrors
(hence my question).

**Comment by nviets** [comment]
Sure, I'll change it to posit then

**Comment by nviets** [comment]
How about this?

On a related note, I generally build R in an air gapped environment and need to overlay all of this with my own artifactory mirrors. I also add my own private mirrors for internal packages.

The situation is pretty standard for enterprise, and I wonder if we could make mirrors.nix in fetchurl and default.nix more extensible.

Are you open to doing something like that with r-modules?

**Comment by jbedo** [comment]
I don't know anything about artifactory so I don't have any good
suggestions. Note though that as hydra builds (almost) the rPackages
tree the source tarballs are available on the cache, e.g.,:

    ❯ nix path-info -sh --store https://cache.nixos.org /nix/store/xnigj5gi6vnn7ywc7df3m4lvhyq7vmly-ggplot2_3.4.1.tar.gz
    /nix/store/xnigj5gi6vnn7ywc7df3m4lvhyq7vmly-ggplot2_3.4.1.tar.gz           3.0M

So maybe if you can proxy the cache with artifactory you don't need to
make any explicit changes?

The exception is the Bioconductor datasets which aren't built by hydra.

**Comment by nviets** [comment]
Interesting that nix caches tarballs. I hadn't thought about getting them from there. Thanks for mentioning that. Posit uses packrat to containerize shiny apps (in Connect), and it gets redirected to an internal CRAN mirror. I wonder if could be made to read them from the nix store. I'll have to give it some thought separately.

Let me know if you'd like anything else tidied up in the current PR.

**Review by jbedo — CHANGES_REQUESTED** [review]
Needs trailing /:

```
error: builder for '/nix/store/0l3y03vn7hzwbv3a79zyv0r5j0n8hs64-gtable_0.3.1.tar.gz.drv' failed with exit code 1;
       last 10 log lines:
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: packagemanager.rstudio.comcran
       > Warning: Problem : timeout. Will retry in 1 seconds. 3 retries left.
       >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: packagemanager.rstudio.comcran
       > Warning: Problem : timeout. Will retry in 2 seconds. 2 retries left.
       >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: packagemanager.rstudio.comcran
       > Warning: Problem : timeout. Will retry in 4 seconds. 1 retries left.
       >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: packagemanager.rstudio.comcran
       > error: cannot download gtable_0.3.1.tar.gz from any mirror
       For full logs, run 'nix log /nix/store/0l3y03vn7hzwbv3a79zyv0r5j0n8hs64-gtable_0.3.1.tar.gz.drv'.

**Comment by nviets** [comment]
Sorry about that. Here you go

**Comment by jbedo** [comment]
Sorry for the delay, there's some other issue as the hashes seem to have changed:

```
error: hash mismatch in fixed-output derivation '/nix/store/kz9nbn09d3l9cmrnpwmv5x9ajvi6g5wb-gtable_0.3.1.tar.gz.drv':
         specified: sha256-i9YsVyLVGIkU1mfKurEpkcVV9lf09c57VHVxrjrsfLU=
            got:    sha256-p/i84nvUawlJkae3ux5K0kGxzM8UBu8/g0d2KhfUjEs=
```

Rebasing against current master doesn't help, and it doesn't seem possible to be this patch, so posit switch might be the cause? I'd like to figure this out before merging this.

**Comment by nviets** [comment]
Just to confirm my understanding, are you saying that this PR to add posit to mirrors.nix causes all the hashes to changes?

**Comment by jbedo** [comment]
No, I'm saying testing this PR has revealed the hashes aren't constant.

**Comment by jbedo** [comment]
Worked it out, posit doesn't just mirror CRAN binaries it modifies the `DESCRIPTION` file. Our R update script only updates hashes for packages that have been updated, so after switching to posit we now have incorrect hashes for a lot of our tree. Not sure what the best way to deal with this is, but it's not related to this PR.

**Comment by nviets** [comment]
Let's continue the discussion on #219275 as you have started.

**Comment by jbedo** [comment]
This functionality was part of #224451.

**Pull request closed without merging**
