### PR TITLE
grocy: 3.3.0 -> 4.0.0

### PR DESCRIPTION
**Pull request by n0emis**
## Description of changes
https://github.com/grocy/grocy/releases/tag/v4.0.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by hexchen — APPROVED** [review]
Looks good to me.

**Comment by timhae** [comment]
Running just fine for me as well, thanks for the PR!

**Comment by timhae** [comment]
4.0.1 with PHP 8.2 support released yesterday

**Comment by Ma27** [comment]
Removing my review request. Sorry, I should've probaly done this earlier, but I wasn't sure if I'd change my mind. Anyways: I stopped using Grocy a while ago and I don't plan to go back. While you're touching this, feel free to remove my maintainership, otherwise I'll do it soonish(tm).

The changes are looking good btw, but I haven't close testing.

**Comment by AkechiShiro** [comment]
@SuperSandro2000 could you please review this PR, I'm not sure if you're the right one to tag but the actual maintainer that was needed to make the review, has resigned. also, a previous review has already been made, but I'm not sure if this PR can thus be merged or not.

**Comment by n0emis** [comment]
> Removing my review request. Sorry, I should've probaly done this earlier, but I wasn't sure if I'd change my mind. Anyways: I stopped using Grocy a while ago and I don't plan to go back. While you're touching this, feel free to remove my maintainership, otherwise I'll do it soonish(tm).
> 
> The changes are looking good btw, but I haven't close testing.

I can offer to overtake maintainership of this package and module

**Pull request merged**
