### PR TITLE
blaze: init at 0.8.2

### PR DESCRIPTION
**Pull request by FRidh**
Requires #8765, #8763 and #8737.

Maybe next time when I have a case with dependencies like here I should put the commits in a single PR?

Cherry-picked the other commits and tested with nox-review.

### CODE REVIEW

**Comment by FRidh** [comment]
There are some optional dependencies as well that I did not include here yet. However, I think it is best if by default those are installed as well. It's not really clear how each optional dependency is used.
Add a flag `optional=true` in this case?

**Comment by lethalman** [comment]
Well, you choose. If you need those optional dependencies, just include them.

**Comment by FRidh** [comment]
Alright, I'll add them then. Thanks.

**Comment by FRidh** [comment]
@lethalman  @pSub can this be merged?

**Pull request merged**
