### PR TITLE
velero: 1.6.0 -> 1.6.2

### PR DESCRIPTION
**Pull request by starcraft66**
###### Motivation for this change
Update velero

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by bryanasdev000 — CHANGES_REQUESTED** [review]
Did some tests and LGTM. Could you please add this changes too?

Line 27 - excludedPackages change to:

```
excludedPackages = [ "issue-template-gen" "crd-gen" "release-tools" "velero-restic-restore-helper" ];
``` 

Line 29 - doCheck change to:

```
doCheck = false; # Tests expect a running cluster see https://github.com/vmware-tanzu/velero/tree/main/test/e2e
```

After doCheck add: 

```
doInstallCheck = true;
installCheckPhase = ''
    $out/bin/velero version --client-only | grep ${version} > /dev/null
'';
``` 

Remove `platforms = platforms.linux ++ platforms.darwin;`.

Sorry for the delay, busy with RL.

```
diff --git a/pkgs/applications/networking/cluster/velero/default.nix b/pkgs/applications/networking/cluster/velero/default.nix
index b38787e2968..a83a9277854 100644
--- a/pkgs/applications/networking/cluster/velero/default.nix
+++ b/pkgs/applications/networking/cluster/velero/default.nix
@@ -3,15 +3,15 @@
 buildGoModule rec {
   pname = "velero";
   # When updating, change the commit underneath
-  version = "1.6.0";
-  commit = "5bd70fd8eef316d220317245e46dc6016c348dce";
+  version = "1.6.2";
+  commit = "8c9cdb9603446760452979dc77f93b17054ea1cc";
 
 
   src = fetchFromGitHub {
     rev = "v${version}";
     owner = "vmware-tanzu";
     repo = "velero";
-    sha256 = "sha256-2d4xsffh5DpxGahmzXpgUBRFAt5CsDnHCm8xU1ksqyQ=";
+    sha256 = "sha256-JYa+5lP9uo/6/5wTxNz8xa2usHo6WfXSndbwrMpHhcg=";
   };
 
   buildFlagsArray = ''
@@ -22,11 +22,16 @@ buildGoModule rec {
       -X github.com/vmware-tanzu/velero/pkg/buildinfo.GitTreeState=clean
   '';
 
-  vendorSha256 = "sha256-aQjtebIyV69nRwc/zvK/9v0mX3pAPKfOunSL/FpFZJU=";
+  vendorSha256 = "sha256-Rmj2qGY2w1gsnKAuRQ8cQyqfoM556t4/MookkuPmbDM=";
 
-  excludedPackages = [ "issue-template-gen" ];
+  excludedPackages = [ "issue-template-gen" "crd-gen" "release-tools" "velero-restic-restore-helper" ];
 
-  doCheck = false;
+  doCheck = false; # Tests expect a running cluster see https://github.com/vmware-tanzu/velero/tree/main/test/e2e
+
+  doInstallCheck = true;
+  installCheckPhase = ''
+    $out/bin/velero version --client-only | grep ${version} > /dev/null
+  '';
 
   nativeBuildInputs = [ installShellFiles ];
   postInstall = ''
@@ -43,6 +48,5 @@ buildGoModule rec {
       "https://github.com/vmware-tanzu/velero/releases/tag/v${version}";
     license = licenses.asl20;
     maintainers = [ maintainers.mbode maintainers.bryanasdev000 ];
-    platforms = platforms.linux ++ platforms.darwin;
   };
 }
```

**Review by bryanasdev000 — APPROVED** [review]
LGTM. Thanks!

**Review by bryanasdev000 — APPROVED** [review]
4Borg!

**Review by risicle — APPROVED** [review]
Builds & runs, macos 10.15 & nixos x86_64

**Pull request merged**
