### PR TITLE
[Backport release-23.11] nextcloud, nextcloud-notify_push: set platforms to linux

### PR DESCRIPTION
**Pull request by teutat3s**
## Description of changes
Backport of #283970

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by dotlambda** [comment]
Why is the first commit not a `cherry-pick -x`?

**Comment by teutat3s** [comment]
> Why is the first commit not a `cherry-pick -x`?

Thanks, fixed.

**Comment by emilylange** [comment]
Why exactly do we need to backport `maintainers/teams: init and add helsinki-systems` (#268109, 7b6580dba42d2ec15e8b2b90fb2f1da93bd0d398)?

Also, wrong cherry-pick commit rev in that commit btw.
`(cherry picked from commit 9871162bc36198d4ab996b6fe4db726c1559adf7)` should be
`(cherry picked from commit 7b6580dba42d2ec15e8b2b90fb2f1da93bd0d398)`.

9871162bc36198d4ab996b6fe4db726c1559adf7 was your initial commit for which you didn't use `cherry-pick -x` and then force-pushed over.

**Comment by teutat3s** [comment]
Good catch, thanks!

My intention with cherry-picking the maintainers commit is to avoid future merge conflicts when backporting via labels (maintainers of notify_push changed). Would you prefer something else?

**Comment by teutat3s** [comment]
@emilylange Reconsidered and fixed, thanks for the review.

**Review by emilylange — APPROVED** [review]
Thanks :)

The `rev`s in `(cherry picked from commit <rev>)` are still wrong, but I guess it's fine /shrug

(waiting for someone else to approve/merge)

**Comment by teutat3s** [comment]
@emilylange That might be an issue with GitHub, I literally copy pasted those commit revs from the GitHub bot message linked above. The revs are present in this repo as well, somehow it's linking to my fork.

20240131_16h46m07s_grim

**Comment by emilylange** [comment]
Hmm... yeah, you are right the thing I saw is gone now.
Not sure how that happened.

Could have been GitHub being eventually consistent or just my brain bit flipping or whatever.

sorry^^

**Pull request merged**
