### PR TITLE
pivx: 3.2.0 -> 3.4.0

### PR DESCRIPTION
**Pull request by wucke13**
* pivx: 3.2.0 -> 3.2.2

* altcoins.pivx: 3.2.2 -> 3.3.0

Furthermore, this fixes 2542928

* pivx: 3.3.0 -> 3.4.0

Added `test_pivx` as test ran by nixpkgs

* Update pkgs/applications/blockchains/pivx.nix

Thanks to @lassulus for fixing this typo!

Co-Authored-By: Lassulus <github@lassul.us>

Backport of https://github.com/NixOS/nixpkgs/pull/67412
@Lassulus maybe you can `nix-review` this shortly? I'm currently on a weak laptop and don't have the time to compile.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @Lassulus

### CODE REVIEW

**Comment by Lassulus** [comment]
did you use `git cherry-pick -x` ?

**Comment by wucke13** [comment]
without `-x`, namely `git cherry-pick e9cd8a2d60f0fb1a55b997a3f10aefdd1f1b1e52`

**Comment by Lassulus** [comment]
ah, normally we use -x to show the original commit which is cherry picked. There is a section in the manual about this: https://nixos.org/nixpkgs/manual/#submitting-changes-stable-release-branches

**Comment by wucke13** [comment]
Ah ok. DIdn't knew that. I adjusted accordingly and force-pushed :smile:

**Comment by wucke13** [comment]
@GrahamcOfBorg build pivx

**Review by Lassulus — APPROVED** [review]
tested with nix-review, on top of 19.09

**Pull request merged**
