### PR TITLE
sudo and sssd: Enable sssd support in sudo and building of sudo library in sssd

### PR DESCRIPTION
**Pull request by lejonet**
###### Motivation for this change
Sudo has support to poll SSSD for its sudoers rules, but it has to be compiled into sudo and it requires a sudo plugin, libsss_sudo.so, from SSSD to function.

Added optional arguments to sudo and sssd to enable this functionality and have tested it, via packageOverrides, on a baremetal nixos machine. Both sssd and sudo was built with nix.useSandbox = true and I tried the functionality it brings and it works, I have sudoers rules in an openldap directory which I could apply after appending sudoers: files sss to nsswitch.conf.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bjornfor** [comment]
Hi, could you move this PR to a separate feature branch? It seems you are using your master branch, and now you have added some non-relevant commits to this PR. (All the "sheepdog" stuff.)

**Comment by lejonet** [comment]
Definitively, was a while since I did the PR workflow, so completely missed that

**Comment by lejonet** [comment]
Seems like I can't change from what branch I want to merge, but I can change to which branch I want to merge, so I'll close this PR and open up a new with the correct branch.

**Comment by bjornfor** [comment]
Thanks!

**Pull request closed without merging**
