### PR TITLE
Updates to awscli, botocore, boto3

### PR DESCRIPTION
**Pull request by NeQuissimus**
###### Motivation for this change
Necessary updates for Python 3.7 support

Previously, the following errors would occur:

```
$ aws eks update-kubeconfig --region eu-west-1 --name myeks
Error in sitecustomize; set PYTHONVERBOSE for traceback:
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
Traceback (most recent call last):
  File "/nix/store/3ghbq3qk5l2bwm0cb67b4cygvwrq2c8y-awscli-1.16.266/bin/.aws-wrapped", line 14, in <module>
    import sys;import site;import functools;sys.argv[0] = '/nix/store/3ghbq3qk5l2bwm0cb67b4cygvwrq2c8y-awscli-1.16.266/bin/aws';functools.reduce(lambda k, p: site.addsitedir(p, k), ['/nix/store/3ghbq3qk5l2bwm0cb67b4cygvwrq2c8y-awscli-1.16.266/lib/python3.7/site-packages','/nix/store/xg8pj5pg4s16kgicfrgxm8fgm628xg5n-python3.7-python-dateutil-2.8.0/lib/python3.7/site-packages','/nix/store/1i37v0b8a6f0pd641piilncn62b5hr3p-python3.7-six-1.12.0/lib/python3.7/site-packages','/nix/store/8cq0n5r6d7rkidifbsxqkap9imnn44rf-python3.7-setuptools_scm-3.3.3/lib/python3.7/site-packages','/nix/store/g1ys9jixq2c7c6pyxyiyj80473b9nd08-python3.7-jmespath-0.9.4/lib/python3.7/site-packages','/nix/store/ilyfy7vlz59nkidykfcbldicx01qqqlm-python3.7-ply-3.11/lib/python3.7/site-packages','/nix/store/05wprk4fbwya0n4gyzkrdy025qshqafn-python3.7-docutils-0.15.2/lib/python3.7/site-packages','/nix/store/vqcrkscy19pjnksjwghwv6fl780l3g7n-python3.7-ordereddict-1.1/lib/python3.7/site-packages','/nix/store/yz636bbhkfgb1rxa409gi9ycz8cf5r64-python3.7-simplejson-3.16.1/lib/python3.7/site-packages','/nix/store/yrjsqxgkdlhx29add6gda94wqsiwxjx3-python3.7-packaging-19.2/lib/python3.7/site-packages','/nix/store/9zy703cqhlyrc5y37i8jlb4346amqwm8-python3.7-pyparsing-2.4.2/lib/python3.7/site-packages','/nix/store/nhmpshasnqqll40qxbggm5pvgngqb8lv-python3.7-pycparser-2.19/lib/python3.7/site-packages','/nix/store/snz1pawsryw17p6cxay3wc51asb5g5f6-python3.7-cffi-1.13.1/lib/python3.7/site-packages','/nix/store/i9fm8y7ndbz0z1n3y303ycmmdmmnf0r1-python3.7-cryptography-2.8/lib/python3.7/site-packages','/nix/store/9fwq2sg80c66ijnk66xjkhyp82riq64k-python3.7-pyasn1-0.4.7/lib/python3.7/site-packages','/nix/store/sg4ygzhfc031fzd8h75jii3mwl1ic591-python3.7-idna-2.8/lib/python3.7/site-packages','/nix/store/dwxqmi066sm6yb5zssm04vj3zqkj08aa-python3.7-pyOpenSSL-19.0.0/lib/python3.7/site-packages','/nix/store/70ryp2dkr8xmcmwl3w4xnfxrqxc9kngf-python3.7-certifi-2019.9.11/lib/python3.7/site-packages','/nix/store/iadmc74iddhvvhkgqanxh2q7pcr07nbm-python3.7-pysocks-1.7.0/lib/python3.7/site-packages','/nix/store/7pwryyy1m8pkvd2y1936m1pzl4frs3sm-python3.7-urllib3-1.25.6/lib/python3.7/site-packages','/nix/store/rn2fknpwcs7dsac20bziyjgs7rnxz2d0-python3.7-botocore-1.13.2/lib/python3.7/site-packages','/nix/store/7c15acqm9ifp6bgx375xpclgs243kxfb-python3.7-bcdoc-0.16.0/lib/python3.7/site-packages','/nix/store/6dg4v631him6nr0cnqagbmj9vrgjp1nb-python3.7-s3transfer-0.2.1/lib/python3.7/site-packages','/nix/store/xj394bh0x3g2szlapc8dyf3wi5za6ql5-python3.7-colorama-0.4.1/lib/python3.7/site-packages','/nix/store/zjwcyd346zbma44mna5s7g1nw8bm640x-python3.7-rsa-3.4.2/lib/python3.7/site-packages','/nix/store/2493yirzz17js8l4byiijqkspshp2s5b-python3.7-PyYAML-5.1.2/lib/python3.7/site-packages'], site._init_pathinfo());
  File "/nix/store/zdh16dcvjw99ybam59zd2ijb6bx138j0-python3-3.7.5/lib/python3.7/functools.py", line 21, in <module>
    from collections import namedtuple
  File "/nix/store/zdh16dcvjw99ybam59zd2ijb6bx138j0-python3-3.7.5/lib/python3.7/collections/__init__.py", line 27, in <module>
    from reprlib import recursive_repr as _recursive_repr
  File "/nix/store/wsp0hvpba4bbk0vwirgibdrs82mfnyvc-python2.7-future-0.18.2/lib/python2.7/site-packages/reprlib/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
```

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
real issue is that the python2 interpreter is getting called:
```
  File "/nix/store/wsp0hvpba4bbk0vwirgibdrs82mfnyvc-python2.7-future-0.18.2/lib/python2.7/site-packages/reprlib/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
```

**Comment by jonringer** [comment]
also, i think this break moto, which in turn breaks quite a bit of stuff

**Comment by jonringer** [comment]
Yea, i was right, it breaks moto, which does break a lot:
```
ilder for '/nix/store/zrjw3pympfp5qgnjcji3ksjjhbh1bdcb-python3.7-moto-1.3.14.drv' failed with exit code 1; last 10 log lines:
  moto/xray/mock_client.py                                  39      3    92%
  moto/xray/models.py                                      146     18    88%
  moto/xray/responses.py                                    99     40    60%
  moto/xray/urls.py                                          4      0   100%
  --------------------------------------------------------------------------
  TOTAL                                                  35325   2996    92%
  ----------------------------------------------------------------------
  Ran 2663 tests in 678.139s

  FAILED (SKIP=4, errors=20)
cannot build derivation '/nix/store/2y0ci3db88slhh5vfc1j8yzkbqhp4y7n-python3.7-buildbot-2.5.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/rkdhamyczx9s46iskhiz78bm5hjplm8j-python3.7-celery-4.4.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/kgh1ra61s78zn7bq2yrgq3cxv85rbdb9-python3.7-pandas-0.25.3.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/shk8iq6kz59rncib0ylpngkyna3nkqa4-paperwork-1.2.4.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/2sp4cn1rpazfa8s26ynkzvdc462sfwil-python3.7-CNVkit-0.9.6.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/hznxaifna1a5yhp4l5akikhdddg222js-python3.7-acoustics-0.2.3.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/z4lfg7xcnjfggv2izbw9r84n5828bdzl-python3.7-apache-airflow-1.10.5.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/sxihwq5j46yw3z36wrr90knbmcamm1zz-python3.7-atomman-1.3.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/0j5wrf1ki9lhzbv14g3sm606q416xq4l-python3.7-bkcharts-0.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/3zvng4ynv76vza8mw8xdwzmv6a2ginza-python3.7-csvs-to-sqlite-1.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/fqvnk0qm7aqf7vbi37g8hl06gnh5w604-python3.7-djmail-1.1.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/gvi03c1b4l5aqcawg201g7vk0h2djn82-python3.7-drms-0.5.7.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/b942lb8gdwalmypxkdlysvnl276nd6bl-python3.7-fastparquet-0.3.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/67qlq3p9bw1cssfi6v9h9847qk79ncb2-python3.7-flammkuchen-0.9.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/y98l64qzyr4nv4jdmc7kqvs3cyxvgwr9-python3.7-geopandas-0.6.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/pvkbicf2n5b054x8xi58cr3drk8vca1n-python3.7-google-cloud-monitoring-0.34.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/prqlrf6arnpgzvcljn3g77g190ikgi8h-python3.7-holoviews-1.12.7.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/h35bghypardd7b9zmk3flcxs17cfmfml-python3.7-imbalanced-learn-0.6.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/1inkdsvg42qqh9d1gpddfvm84d33nwis-python3.7-mesa-unstable-2019-12-09.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/k68f7byjnjjs404sh1zbign9367l4xjl-python3.7-partd-1.1.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/h3g430yx8vfc71jnz1j3djsiws2ygdar-python3.7-phik-0.9.8.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/51mvy5vxlfjmc7grvv0l8zapg4i6jsq9-python3.7-pvlib-0.7.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/nxny1lm0hrc9fr7n5bas10pxshk6xw1p-python3.7-pyarrow-0.15.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/lkycc3s4dxnpnym192qanmbk6460g2xh-python3.7-pybids-0.10.0.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/3q6pfz13rbwakdpn8va2wz7gycp0nnjx-python3.7-pymatgen-2019.12.22.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/mcspxn5cx4ah9j82s99ci4xc86lklj7g-python3.7-pymc3-3.8.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/0snvfywi6jwpsrgfgvsqgizs46z6a7z2-python3.7-python3.7-buildbot-2.5.1-with-plugins.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/ha8dawb09kdq0p2hgl4qv7i5ssj9fj2d-python3.7-python3.7-buildbot-2.5.1-with-plugins.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/lzh2pv2jdmcz28rdhs1613y1vmi16whp-python3.7-pytrends-4.7.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/aqjbgki7ky4s5xqp1hiqd0jlmfi46abf-python3.7-quandl-3.4.6.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/hm7j60bndwqb3j1y52myk3xhm3a4yf9z-python3.7-scikit-bio-0.5.5.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/sya90ipm255spfi99if507fb3vjx88m9-python3.7-seaborn-0.9.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/r2011ryhykfh4hb9a882kvd2s6fhkli7-python3.7-sentry-sdk-0.13.5.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/mm2msfyggi9scgjpm6wmlk7wk2g83rjw-python3.7-srht-0.54.4.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/3bzjxyxpsr1fwr4c1zqr28zxyh19q8s9-python3.7-statsmodels-0.10.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/3mx1yj076lg97i8lnhxah1ydh3lmkrmv-python3.7-tablib-0.12.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/0ai3y1vpyrnwpa27fb079j9sf1vazp3g-python3.7-trackpy-0.4.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/spin9qgnzk7cxig3g14l2pi3v47scc5r-python3.7-vega-2.6.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/iln4z7rfb11lqy8lqwx3lyfpfjf85r0g-python3.7-vega_datasets-0.8.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/ibxlr7srknb8by7j6hmgj4ly1sshr1la-python3.7-vidstab-1.7.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/ywxhh81ikm29nf39k7v8llj383a48y1c-python3.7-xarray-0.14.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/h6rskr2kd3rb4aa2b988nn1m2saqa4rl-python3.7-xgboost-0.90.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/wwlqb92x1arr9n8gqhzdazp4k2vjgky2-visidata-1.5.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/h8gv9q8iwxbrxnqy3xplk943wsm4gwsb-python3.7-altair-4.0.0.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/z61k94skmvzx1s4yaazqr9li20k5hzs5-python3.7-awkward-0.12.18.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/cvm7pzj7rgvdnp5g1z96208mha5iibxk-python3.7-buildsrht-0.48.0.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/jfgicfsihm4nxbyvwbm0h1waawhyl3n5-python3.7-cufflinks-0.16.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/0ja7hy3fby7153ba6zzgaawf3v93mc1c-python3.7-dask-2.9.1.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/89xpkss5d4iwl66y9q0mnywlwz7wd75h-python3.7-google-cloud-bigquery-1.23.1.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/cqqvzv3qv84fswxnkxqj3xw9gm6h1rgj-python3.7-ibis-framework-1.2.0.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/b9pj7nlql266xhkfwq51fnwg22vq5cr3-python3.7-lammps-cython-0.5.7.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/x2y1w8rq4fis6975kjjl32zxxwzivxa1-python3.7-listssrht-0.38.3.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/dcslm86sx8h6b8y014x9z8ansia21mra-python3.7-mansrht-0.13.5.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/9ywhgk6a6n14h5yn2kl5n963gkswz7h7-python3.7-metasrht-0.37.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/1m1x3bs5v4n6kvv2cc63a0jm7fakiydw-python3.7-nbsmoke-0.3.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/s8476lflwdxn211y5yam71kly5h657x1-python3.7-nipype-1.3.1.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/xz9p9h5dbm6c25mfk2c3fzmycjn705lh-python3.7-osmnx-0.9.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/1h6m2gg5qsy1h1pskk8y7z033yzjl3y7-python3.7-pastesrht-0.7.3.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/yidz6p97bp566a09r4k4cbq6xdmib1a1-python3.7-pymatgen-lammps-0.4.5.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/rva3q5lyz7y1g5d7nh73rx7ql0n059ry-python3.7-sumo-1.0.9.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/3p0wzqdjg6ykv0s9wjli3nwd0vfv30mi-python3.7-todosrht-0.51.13.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/b7zifs27llx6r1y8h7n6x3243dq3w7ch-python3.7-wrf-python-1.3.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/pzq54p6vyzp5x2j5axpii2lh0n5frqn3-tebreak-1.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/hzi1yirpiwgw9c60m9rc179cixyla40w-python3.7-colorcet-2.0.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/bzgfnqi38sihlnfkdixkfy4as53p946i-python3.7-dask-glm-0.2.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/2b6rc2waxvl23z5k155w77bhlijfrf00-python3.7-dftfit-0.5.1.drv': 4 dependencies couldn't be built
cannot build derivation '/nix/store/y3wjp5qf9rrf9f7x4xj7pvbcmq4rcsmf-python3.7-distributed-2.9.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/pdgj9j0irz36hw07pix5s78h04shjzzj-python3.7-pyFFTW-0.11.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/dqf801mwhl3g3pak655sppnbmin00ib5-python3.7-scikit-image-0.16.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/7g33bhs1q109c5cr5wsi94p1cllwcq10-python3.7-scmsrht-0.16.0.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/1k8hn7b7sjhdvpx58nl3n50fcdfdn1d4-python3.7-uproot-methods-0.7.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/kcnq67wgj1bz0dhnmvp9pw0w7z4h1ix3-streamlit-0.50.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/s5ming805ks0c82sarfx97kgclmw4bwg-caffe-1.0.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/slwf2p3jwz1bndfllvf2985cxqys6c1m-python3.7-PIMS-0.4.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/hkb4g86ry0jwx6vjjhjw4mxcpvs1f0gq-python3.7-aplpy-2.0.3.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/3qjn3wn9nr03ggky5qxx0mgcnffsi1mn-python3.7-dask-jobqueue-0.7.0.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/1s4w0ys1pc6pb6lql4vzdp2wkjyl14r0-python3.7-dask-ml-1.1.1.drv': 4 dependencies couldn't be built
cannot build derivation '/nix/store/kdsbpmkx52pjisjkkzn1na50fl54pkdn-python3.7-dask-mpi-2.0.0.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/ngkkzgiq1nvjwrjaz1pk80iy6dc6bb6b-python3.7-dask-xgboost-0.1.9.drv': 3 dependencies couldn't be built
cannot build derivation '/nix/store/w0x93hqi3q0bs7bjq4sp4wda1rj8sqb2-python3.7-datashader-0.9.0.drv': 8 dependencies couldn't be built
cannot build derivation '/nix/store/sg2ykr3bq53awycm9x02azl2jkz4635r-python3.7-gitsrht-0.35.6.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/1yqnz5z46xc29laclx3y3n977h1xlvlv-python3.7-glymur-0.8.18.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/d4f41gi7k1fw7kcnq62y3b7vv9nvqy1r-python3.7-hvplot-0.5.2.drv': 3 dependencies couldn't be built
cannot build derivation '/nix/store/ci4snl0fwmlh2b4plm8sbzddhpkkvwkp-python3.7-image-match-1.1.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/b9lgbjk8hll84a0rmji14b9rl09j5dzn-python3.7-imgaug-0.3.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/hrsagnlmfr6gp0vpqfyl57hfvych0qxn-python3.7-runway-python-0.5.7.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/xc46pdm9y81bwhpnanc4s5mhm6ysq7li-python3.7-slicedimage-4.1.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/vzfn6jc1pasca2mn1vgyvmiwk3mh16fi-python3.7-streamz-0.5.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/xwa7bxc0xazadyidgiil1ijbcpayi49f-python3.7-stumpy-1.0.drv': 3 dependencies couldn't be built
cannot build derivation '/nix/store/mq9s2d4bqc1wgbzsdqywzr2bm89ix7ln-python3.7-uproot-3.11.0.drv': 3 dependencies couldn't be built
cannot build derivation '/nix/store/avqscpsi5ipzn08al2c9660n3ib6qp28-python3.7-dask-image-0.2.0.drv': 3 dependencies couldn't be built
cannot build derivation '/nix/store/nrhlj4xdqmp9fg74ra4ilwg02gs1rrfg-python3.7-intake-0.5.4.drv': 4 dependencies couldn't be built
cannot build derivation '/nix/store/kskvk1jdhn8yl19m4k31xj7gn9rmv9mw-python3.7-stytra-0.8.26.drv': 4 dependencies couldn't be built
cannot build derivation '/nix/store/zsbrsp10nf8arj6hhmrpakwy059sxcnd-python3.7-sunpy-1.0.6.drv': 4 dependencies couldn't be built
cannot build derivation '/nix/store/w8cmzmfqhcinn29wvmb41ggcxlrxccny-python3.8-hass-nabucasa-0.29.drv': 3 dependencies couldn't be built
cannot build derivation '/nix/store/wazgds037fpmpix4cl3hm72r95hmnllk-python3.7-dispatchsrht-0.12.3.drv': 1 dependencies couldn't be built
```

**Comment by NeQuissimus** [comment]
Oh wow oO
And there is no moto update.
Not sure what to do about this, so I am going to leave this PR here for now :)

FWIW, this was my environment: 
```
λ nix-shell -p cookiecutter -p terraform_0_12 -p kubectl -p kubernetes-helm -p aws-iam-authenticator
```

I terraformed something which worked until `aws eks update-kubeconfig` was called.

**Comment by FRidh** [comment]
Avoid using `nix-shell`, it runs the setup hooks, sets up `PYTHONPATH`, and if you happen to have multiple Python applications, the paths will mingle. `nix run` should solve your issue then.

**Comment by jonringer** [comment]
#77332 should allow you to do your previous workflow again

**Comment by Infinisil** [comment]
This seems resolved with above PRs, correct?

**Comment by jonringer** [comment]
looks like underlying files have been updated as well. Closing

**Pull request closed without merging**
