### PR TITLE
python311Packages.numba: enable

### PR DESCRIPTION
**Pull request by bcdarwin**
python310Packages.numba: unstable-2023-08-11 -> 0.58.0
python310Packages.numba: remove unused local patch

Python 3.11 support was merged in https://github.com/numba/numba/pull/8822

## Description of changes

Bump maximum supported Python version from 3.10 to 3.11.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by natsukium** [comment]
Can we update to [0.58](https://github.com/numba/numba/releases/tag/0.58.0)?

**Comment by bcdarwin** [comment]
> Can we update to [0.58](https://github.com/numba/numba/releases/tag/0.58.0)?

Sure, pushed.

**Comment by natsukium** [comment]
Thanks, I think we need to remove `postPatch`.

**Comment by bcdarwin** [comment]
`postPatch` and related comments removed.

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 260478` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>22 packages marked as broken and skipped:</summary>
  <ul>
    <li>piper-train</li>
    <li>piper-train.dist</li>
    <li>python310Packages.graspologic</li>
    <li>python310Packages.graspologic.dist</li>
    <li>python310Packages.qiskit</li>
    <li>python310Packages.qiskit-machine-learning</li>
    <li>python310Packages.qiskit-machine-learning.dist</li>
    <li>python310Packages.qiskit.dist</li>
    <li>python310Packages.scikit-tda</li>
    <li>python310Packages.scikit-tda.dist</li>
    <li>python310Packages.umap-learn</li>
    <li>python310Packages.umap-learn.dist</li>
    <li>python311Packages.graspologic</li>
    <li>python311Packages.graspologic.dist</li>
    <li>python311Packages.qiskit</li>
    <li>python311Packages.qiskit-machine-learning</li>
    <li>python311Packages.qiskit-machine-learning.dist</li>
    <li>python311Packages.qiskit.dist</li>
    <li>python311Packages.scikit-tda</li>
    <li>python311Packages.scikit-tda.dist</li>
    <li>python311Packages.umap-learn</li>
    <li>python311Packages.umap-learn.dist</li>
  </ul>
</details>
<details>
  <summary>40 packages failed to build:</summary>
  <ul>
    <li>python310Packages.awkward</li>
    <li>python310Packages.awkward.dist</li>
    <li>python310Packages.coffea</li>
    <li>python310Packages.coffea.dist</li>
    <li>python310Packages.dask-awkward</li>
    <li>python310Packages.dask-awkward.dist</li>
    <li>python310Packages.mplhep</li>
    <li>python310Packages.mplhep.dist</li>
    <li>python310Packages.pynndescent</li>
    <li>python310Packages.pynndescent.dist</li>
    <li>python310Packages.shap</li>
    <li>python310Packages.shap.dist</li>
    <li>python310Packages.trackpy</li>
    <li>python310Packages.trackpy.dist</li>
    <li>python310Packages.uproot</li>
    <li>python310Packages.uproot.dist</li>
    <li>python310Packages.vector</li>
    <li>python310Packages.vector.dist</li>
    <li>python311Packages.awkward</li>
    <li>python311Packages.awkward.dist</li>
    <li>python311Packages.coffea</li>
    <li>python311Packages.coffea.dist</li>
    <li>python311Packages.dask-awkward</li>
    <li>python311Packages.dask-awkward.dist</li>
    <li>python311Packages.gumath</li>
    <li>python311Packages.gumath.dist</li>
    <li>python311Packages.mplhep</li>
    <li>python311Packages.mplhep.dist</li>
    <li>python311Packages.pynndescent</li>
    <li>python311Packages.pynndescent.dist</li>
    <li>python311Packages.pyscf</li>
    <li>python311Packages.pyscf.dist</li>
    <li>python311Packages.shap</li>
    <li>python311Packages.shap.dist</li>
    <li>python311Packages.trackpy</li>
    <li>python311Packages.trackpy.dist</li>
    <li>python311Packages.uproot</li>
    <li>python311Packages.uproot.dist</li>
    <li>python311Packages.vector</li>
    <li>python311Packages.vector.dist</li>
  </ul>
</details>
<details>
  <summary>145 packages built:</summary>
  <ul>
    <li>openai-whisper (python310Packages.openai-whisper)</li>
    <li>openai-whisper.dist (python310Packages.openai-whisper.dist)</li>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>pianotrans</li>
    <li>pianotrans.dist</li>
    <li>pitivi</li>
    <li>python310Packages.aeppl</li>
    <li>python310Packages.aeppl.dist</li>
    <li>python310Packages.aesara</li>
    <li>python310Packages.aesara.dist</li>
    <li>python310Packages.arviz</li>
    <li>python310Packages.arviz.dist</li>
    <li>python310Packages.bambi</li>
    <li>python310Packages.bambi.dist</li>
    <li>python310Packages.clifford</li>
    <li>python310Packages.clifford.dist</li>
    <li>python310Packages.cppe</li>
    <li>python310Packages.cppe.dist</li>
    <li>python310Packages.dask-glm</li>
    <li>python310Packages.dask-glm.dist</li>
    <li>python310Packages.dask-ml</li>
    <li>python310Packages.dask-ml.dist</li>
    <li>python310Packages.datashader</li>
    <li>python310Packages.datashader.dist</li>
    <li>python310Packages.ffcv</li>
    <li>python310Packages.ffcv.dist</li>
    <li>python310Packages.galois</li>
    <li>python310Packages.galois.dist</li>
    <li>python310Packages.gumath</li>
    <li>python310Packages.gumath.dist</li>
    <li>python310Packages.hyppo</li>
    <li>python310Packages.hyppo.dist</li>
    <li>python310Packages.langchain</li>
    <li>python310Packages.langchain.dist</li>
    <li>python310Packages.librosa</li>
    <li>python310Packages.librosa.dist</li>
    <li>python310Packages.numba</li>
    <li>python310Packages.numba-scipy</li>
    <li>python310Packages.numba-scipy.dist</li>
    <li>python310Packages.numba.dist</li>
    <li>python310Packages.numbaWithCuda</li>
    <li>python310Packages.numbaWithCuda.dist</li>
    <li>python310Packages.phik</li>
    <li>python310Packages.phik.dist</li>
    <li>python310Packages.piano-transcription-inference</li>
    <li>python310Packages.piano-transcription-inference.dist</li>
    <li>python310Packages.pygmo</li>
    <li>python310Packages.pymatting</li>
    <li>python310Packages.pymatting.dist</li>
    <li>python310Packages.pymc</li>
    <li>python310Packages.pymc.dist</li>
    <li>python310Packages.pymoo</li>
    <li>python310Packages.pymoo.dist</li>
    <li>python310Packages.pyscf</li>
    <li>python310Packages.pyscf.dist</li>
    <li>python310Packages.pytensor</li>
    <li>python310Packages.pytensor.dist</li>
    <li>python310Packages.quaternion</li>
    <li>python310Packages.quaternion.dist</li>
    <li>python310Packages.resampy</li>
    <li>python310Packages.resampy.dist</li>
    <li>python310Packages.sparse</li>
    <li>python310Packages.sparse.dist</li>
    <li>python310Packages.stumpy</li>
    <li>python310Packages.stumpy.dist</li>
    <li>python310Packages.stytra</li>
    <li>python310Packages.stytra.dist</li>
    <li>python310Packages.timezonefinder</li>
    <li>python310Packages.timezonefinder.dist</li>
    <li>python310Packages.torchlibrosa</li>
    <li>python310Packages.torchlibrosa.dist</li>
    <li>python310Packages.tsfresh</li>
    <li>python310Packages.tsfresh.dist</li>
    <li>python310Packages.xarray-einstats</li>
    <li>python310Packages.xarray-einstats.dist</li>
    <li>python311Packages.aeppl</li>
    <li>python311Packages.aeppl.dist</li>
    <li>python311Packages.aesara</li>
    <li>python311Packages.aesara.dist</li>
    <li>python311Packages.arviz</li>
    <li>python311Packages.arviz.dist</li>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
    <li>python311Packages.clifford</li>
    <li>python311Packages.clifford.dist</li>
    <li>python311Packages.cppe</li>
    <li>python311Packages.cppe.dist</li>
    <li>python311Packages.dask-glm</li>
    <li>python311Packages.dask-glm.dist</li>
    <li>python311Packages.dask-ml</li>
    <li>python311Packages.dask-ml.dist</li>
    <li>python311Packages.datashader</li>
    <li>python311Packages.datashader.dist</li>
    <li>python311Packages.ffcv</li>
    <li>python311Packages.ffcv.dist</li>
    <li>python311Packages.galois</li>
    <li>python311Packages.galois.dist</li>
    <li>python311Packages.hyppo</li>
    <li>python311Packages.hyppo.dist</li>
    <li>python311Packages.langchain</li>
    <li>python311Packages.langchain.dist</li>
    <li>python311Packages.librosa</li>
    <li>python311Packages.librosa.dist</li>
    <li>python311Packages.numba</li>
    <li>python311Packages.numba-scipy</li>
    <li>python311Packages.numba-scipy.dist</li>
    <li>python311Packages.numba.dist</li>
    <li>python311Packages.numbaWithCuda</li>
    <li>python311Packages.numbaWithCuda.dist</li>
    <li>python311Packages.openai-whisper</li>
    <li>python311Packages.openai-whisper.dist</li>
    <li>python311Packages.phik</li>
    <li>python311Packages.phik.dist</li>
    <li>python311Packages.piano-transcription-inference</li>
    <li>python311Packages.piano-transcription-inference.dist</li>
    <li>python311Packages.pygmo</li>
    <li>python311Packages.pymatting</li>
    <li>python311Packages.pymatting.dist</li>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymc.dist</li>
    <li>python311Packages.pymoo</li>
    <li>python311Packages.pymoo.dist</li>
    <li>python311Packages.pytensor</li>
    <li>python311Packages.pytensor.dist</li>
    <li>python311Packages.quaternion</li>
    <li>python311Packages.quaternion.dist</li>
    <li>python311Packages.resampy</li>
    <li>python311Packages.resampy.dist</li>
    <li>python311Packages.sparse</li>
    <li>python311Packages.sparse.dist</li>
    <li>python311Packages.stumpy</li>
    <li>python311Packages.stumpy.dist</li>
    <li>python311Packages.stytra</li>
    <li>python311Packages.stytra.dist</li>
    <li>python311Packages.timezonefinder</li>
    <li>python311Packages.timezonefinder.dist</li>
    <li>python311Packages.torchlibrosa</li>
    <li>python311Packages.torchlibrosa.dist</li>
    <li>python311Packages.tsfresh</li>
    <li>python311Packages.tsfresh.dist</li>
    <li>python311Packages.xarray-einstats</li>
    <li>python311Packages.xarray-einstats.dist</li>
    <li>tts</li>
    <li>tts.dist</li>
  </ul>
</details>

**Comment by bcdarwin** [comment]
Looks like we need #256140 to update `awkward` since it doesn't want to build against the new numba.

**Comment by bcdarwin** [comment]
There are other problems as well, so I've simply dropped the 0.58 update for now.

**Comment by natsukium** [comment]
Thanks for trying the update.
I agree that we should postpone it.

**Review by natsukium — APPROVED** [review]

**Pull request merged**
