### PR TITLE
PyPy: Update interpreter, unbreak many packages

### PR DESCRIPTION
**Pull request by MostAwesomeDude**
###### Motivation for this change

I like PyPy.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

This PR updates the PyPy interpreter versions and unbreaks many packages, including the ubiquitous Numpy.

### CODE REVIEW

**Comment by MostAwesomeDude** [comment]
@GrahamcOfBorg build pypyPackages.mock

**Comment by Ekleog** [comment]
@GrahamcOfBorg build pypyPackages.mock

**Comment by Mic92** [comment]
```
@GrahamcOfBorg build magic-wormhole python27Packages.magic-wormhole python27Packages.magic-wormhole-transit-relay python37Packages.magic-wormhole-transit-relay transporter
```

**Comment by FRidh** [comment]
pushed to staging

**Comment by andersk** [comment]
Hydra has been failing to build pypy-7.0.0 and pypy3-7.0.0, and so has my system. Was this ever tested using sandboxing?

**Comment by andersk** [comment]
And…now pypy is marked as broken (8760c695d4e1e98d53cdf410f0f509fa62f4fd41).

**Pull request closed without merging**
