### PR TITLE
{febio, febio-studio}: darwin sdk refactor; fix qt 6.8 build

### PR DESCRIPTION
**Pull request by khaneliman**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 352943`

---
### `x86_64-linux`

---
### `aarch64-linux`

---
### `x86_64-darwin`
<details>
  <summary>:x: 2 packages failed to build:</summary>
  <ul>
    <li>febio</li>
    <li>febio-studio</li>
  </ul>
</details>

---
### `aarch64-darwin`

**Comment by khaneliman** [comment]
Interesting... looking upstream they had available checks for 10.13 so I assumed it wouldn't need to do anything.

**Comment by emilazy** [comment]
That’s backwards: the 10.12 SDK cannot compile code with availability checks for 10.13+ APIs, because it doesn’t have the 10.13+ APIs. Availability checks are a runtime thing: you need an SDK that is at least the maximum of all availability checks. Rarely, things will use the preprocessor `MAC_OS_X_VERSION_MAX_ALLOWED` definition to gate their availability checks, but in that case you’re still missing out on functionality for no gain in compatibility by using an old SDK.

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 352943`

---
### `x86_64-linux`

---
### `aarch64-linux`

---
### `x86_64-darwin`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>febio-studio</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>febio</li>
  </ul>
</details>

---
### `aarch64-darwin`

**Comment by khaneliman** [comment]
Interesting...
```bash
FAILED: CMakeFiles/FEBioStudio.dir/FEBioStudio/FileViewer.cpp.o
/nix/store/d2jm2gdf5qmyfbqk579f7h65sbi497sr-clang-wrapper-16.0.6/bin/clang++ -DFFMPEG -DHAS_SSH -DHAVE_ZLIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_OPENGLWIDGETS_LIB -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DTETLIBRARY -D__APPLE__
-I/tmp/nix-build-febio-studio-2.7.drv-0/source/build/CMakeFiles/AutoGen/FEBioStudio_autogen/include -I/tmp/nix-build-febio-studio-2.7.drv-0/source/.
-F/nix/store/nzfcir6lrdq1dx2vkwl5xv996p60zhnq-apple-sdk-12.3/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks -isystem /nix/store/24n4sn70knrm4ma6g8j3dv4xfbq2axvj-qtbase-6.8.0/lib/QtCore.framework/Headers -iframework
/nix/store/24n4sn70knrm4ma6g8j3dv4xfbq2axvj-qtbase-6.8.0/lib -isystem /nix/store/24n4sn70knrm4ma6g8j3dv4xfbq2axvj-qtbase-6.8.0/mkspecs/macx-clang -isystem /nix/store/24n4sn70knrm4ma6g8j3dv4xfbq2axvj-qtbase-6.8.0/lib/QtWidgets.framework/Headers -isystem
/nix/store/24n4sn70knrm4ma6g8j3dv4xfbq2axvj-qtbase-6.8.0/lib/QtGui.framework/Headers -isystem /nix/store/24n4sn70knrm4ma6g8j3dv4xfbq2axvj-qtbase-6.8.0/lib/QtNetwork.framework/Headers -isystem /nix/store/24n4sn70knrm4ma6g8j3dv4xfbq2axvj-qtbase-6.8.0/lib/QtOpenGL.framework/Headers -isystem /nix/store/24n4sn70knrm4ma6g8j3dv4xfbq2axvj-qtbase-6.8.0/lib/QtOpenGLWidgets.framework/Headers -O3 -DNDEBUG -std=gnu++17 -isysroot /nix/store/nzfcir6lrdq1dx2vkwl5xv996p60zhnq-apple-sdk-12.3/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -mmacosx-version-min=10.15
-F/nix/store/6sqx120cqlp20k69fp5al6aji6rri5k0-apple-sdk-10.12.2/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks  -w -fPIC -MD -MT CMakeFiles/FEBioStudio.dir/FEBioStudio/FileViewer.cpp.o -MF CMakeFiles/FEBioStudio.dir/FEBioStudio/FileViewer.cpp.o.d -oCMakeFiles/FEBioStudio.dir/FEBioStudio/FileViewer.cpp.o -c /tmp/nix-build-febio-studio-2.7.drv-0/source/FEBioStudio/FileViewer.cpp
/tmp/nix-build-febio-studio-2.7.drv-0/source/FEBioStudio/FileViewer.cpp:651:17: error: variable has incomplete type 'QDirIterator'
                        QDirIterator it(path, { "*.fs2", "*.fsm", "*.feb", "*.xplt" }, QDir::AllEntries | QDir::NoSymLinks | QDir::NoDotAndDotDot);
                                     ^
/nix/store/24n4sn70knrm4ma6g8j3dv4xfbq2axvj-qtbase-6.8.0/lib/QtCore.framework/Headers/qdir.h:17:7: note: forward declaration of 'QDirIterator'
class QDirIterator;
      ^
1 error generated.

**Comment by emilazy** [comment]
Qt 6.8 issue?

**Comment by khaneliman** [comment]
> Qt 6.8 issue?

Just came back to this, tried building it on master and see the same error.

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 352943`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>febio-studio</li>
  </ul>
</details>

---
### `aarch64-linux`

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>febio</li>
    <li>febio-studio</li>
  </ul>
</details>

---
### `aarch64-darwin`

**Pull request merged**
