### PR TITLE
exim: add SPF support (+ init libspf2 at 1.2.10)

### PR DESCRIPTION
**Pull request by pacien**
###### Motivation for this change

This PR adds SPF support to the exim package and inits libspf2 at 1.2.10.

I'm not sure whether we should enable SPF by default, as it's quite common.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @4z3 (exim package maintainer)

@ofborg build libspf2
@ofborg build exim

### CODE REVIEW

**Comment by dasJ** [comment]
I think it's a good idea to enable it by default as it's (as you said) really common and exim options which aren't enabled by default tend to break over updates as they are not automatically tested.

**Comment by 4z3** [comment]
+1 for enabling it by default

**Review by 4z3 — APPROVED** [review]

**Comment by pacien** [comment]
Amended to enable SPF support by default.

**Comment by risicle** [comment]
`libspf2` builds successfully macos 10.13.

**Comment by disassembler** [comment]
@GrahamcOfBorg build libspf2 exim

**Pull request merged**
