### PR TITLE
xmonad: put the correct xmonad binary in PATH

### PR DESCRIPTION
**Pull request by xaverdh**
###### Motivation for this change
If `services.xserver.windowManager.xmonad.config` is used, until this pr the module would put the official `xmonad` package in `systemPackages` which is almost certainly not what you want. After this pr, if you e.g. rebuild your config and then restart `xmonad` with `xmonad --restart`, it will take the binary from `PATH` which will be the one you specified in your config.
I also took the liberty to rename some things to hopefully make their purpose more obvious.

Personally I would simply consider the old behavior a bug, but not sure if somebody relies on it for some strange reason?
 
By the way don't get confused by the diff; the relevant line [here](https://github.com/xaverdh/nixpkgs/blob/67eb45ddce9d390e1c9f7f8c709d98ad68cb0bfd/nixos/modules/services/x11/window-managers/xmonad.nix#L114) is unchanged, but `xmonad` is bound to a different value.
 
###### Things done

* Tested this with my own `xmonad` config (which uses `services.xserver.windowManager.xmonad.config`). Should be no-op if not using the `config` option.

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by xaverdh** [comment]
cc @Profpatsch (might be of interest to you?)

**Comment by Lassulus** [comment]
seems like a good idea. This sadly has broken the xmonad test in nixos/tests because it depended on this "broken" behavior. Would be nice of you if you could fix it also :)

**Comment by xaverdh** [comment]
Hmm the test is actually tricky. It uses `launch` which does not support the `xmonad` command line options..
There probably was a reason why `launch` was used instead of the standard `xmonad` entry point, but lets see.

(I can't run the tests locally atm because `qemu` is broken on my hardware – gives me a kernel panic)

**Comment by xaverdh** [comment]
Ok, I finally found machine with working `qemu`. The test won't work as is, essentially because it tests precisely the old behavior (which makes me think that somebody wanted it?). Using the standard `xmonad` entry point fails because that makes wrong assumptions about the binary name, using `launch` would require reimplementing some logic from the `xmonad` module, which I would rather not do for a simple test.

Actually my favorite solution for this problem would be to just drop that part of the test. Maybe have a second test that actually tests the code path without custom `config`.

**Comment by xaverdh** [comment]
I finally found a way to make the test work while staying close to the original version. It does test restarting as the original test did (at least I think that was the intention). Just have to be careful to avoid shelling out to `xmonad --restart` which will not work with `launch`..

**Comment by xaverdh** [comment]
(fixed a type in the commit message)

**Comment by xaverdh** [comment]
Ok, so I now understand why people might want the vanilla `xmonad` in their `PATH`:

The standard keybinding for restarting `xmonad` actually goes through a somewhat convoluted process (detailed in [this discussion](https://github.com/xmonad/xmonad/pull/240)), which involves executing the xmonad from `PATH` and makes assumptions about it, namely that it uses the `xmonad` entry point.

But if people use `launch` as entry point (the example actually advertises this), putting the configured binary in path will break that key binding.
I think its still more consistent to have the configured `xmonad` in `PATH`, as this
* avoids accidentally dropping you into an vanilla `xmonad` (without any config) by not overwriting and pressing the standard `mod+q` key binding
* allows you to `restart` into the new `xmonad` after rebuilding your system by adding a key binding that calls `restart "xmonad" True`

But the module description / docs could be improved somewhat in this regard ;-) will look into that..

The one thing I am still worried about a bit is that some people may rely on the following workflow atm:
configure `xmonad` with `nixos + config` but have a copy of that `xmonad.hs` in `.xmonad`
-> change that local copy, use `mod+q` to recompile and exec into it
-> when you are satisfied with the result, copy+paste that into your `nixos` config
That workflow can be saved by making your own binary do the recompilation / exec on startup, but requires significantly more insight than previously.

Apart from what this pr does there are two other other sensible approaches I can think of in the case of xmonad configured through the `config` module option:
* put nothing into `PATH`, but put both `xmonad` versions in a read only variable of the module: This will avoid accidentally dropping ppl into unconfigured `xmonad`, if they want either the old behavior or the one from this pr, they can explicitly put either one or the other in `PATH`
* put both in `PATH` but under different names (say `xmonad` and `xmonad-configured`). Can still accidentally dropping ppl into unconfigured `xmonad`, but also allows users to restart into `xmonad-configured` if they want.

**Comment by xaverdh** [comment]
@Lassulus  ah I looked through the history of this module, and you actually submitted the original pr for the config option (thanks by the way!);  after reading that, I think it wasn't intentional to put the plain `xmonad` in `PATH`, right?


> The one thing I am still worried about a bit is that some people may rely on the following workflow atm

^ It occurs to me now, that you can also always just temporarily disable the `config` option, use plain `xmonad` with recompilation semantics, and re-enable it afterwards...

**Comment by xaverdh** [comment]
Pushed some docs. Is there a known way to show inline code, in such a way that there is a visible difference to ordinary text in `man configuration.nix`? I tried `<code></code>` and it failed me :-/

Apart from that I think I am now happy with the state of this pr.

**Comment by xaverdh** [comment]
(fixed up a remnant from some early experimentation in the `nixos` test)

**Comment by Lassulus** [comment]
no, putting the original xmonad was indeed not intentional, but never bothered me enough to actually change it. While you are on it. Maybe you can add some maintainers to the service while you are on it? (like you and me for example)
And thanks for your contribution :)

**Comment by xaverdh** [comment]
before merging this @nequissimus might want to have a look, because he is listed as maintainer of the `xmonad` test (just noticed)

**Review by NeQuissimus — APPROVED** [review]

**Comment by NeQuissimus** [comment]
I think I adopted the test at one point when it was broken. I don't really remember though :D I do use XMonad, so I appreciate this!

**Comment by copyread** [comment]
This fixes configuration not updating after recompiling & restarting? Appreciate it.

**Comment by Profpatsch** [comment]
I don’t change my config often enough to particularly care, but great to see it works now!

**Comment by ivanbrennan** [comment]
> The one thing I am still worried about a bit is that some people may rely on the following workflow atm:
> configure `xmonad` with `nixos + config` but have a copy of that `xmonad.hs` in `.xmonad`
> -> change that local copy, use `mod+q` to recompile and exec into it
> -> when you are satisfied with the result, copy+paste that into your `nixos` config

@xaverdh That's precisely the workflow I was using. It's not ideal, but when I'm making frequent changes to my config it's a quick way to try things out.

Thanks for providing the example `compileRestart` function. I found that in order to get it working, I had to add the following to my `environment.systemPackages`:
```nix
(haskellPackages.ghcWithPackages (ps: with ps; [xmonad xmonad-contrib]))
```
Is that expected? I ask because I didn't need to do this previously, and while I don't mind adding it, I'd like to better understand what changed.

**Comment by xaverdh** [comment]
> 
> Thanks for providing the example `compileRestart` function. I found that in order to get it working, I had to add the following to my `environment.systemPackages`:
> 
> ```nix
> (haskellPackages.ghcWithPackages (ps: with ps; [xmonad xmonad-contrib]))
> ```
> 
> Is that expected? I ask because I didn't need to do this previously, and while I don't mind adding it, I'd like to better understand what changed.

Yes that's actually expected (probably should've added that to the docs as well).

The `vanilla xmonad` has a [wrapper](https://github.com/NixOS/nixpkgs/tree/master/pkgs/applications/window-managers/xmonad/wrapper.nix), that puts `ghc` in place. Now prior to this pr, the running `xmonad with config` used to exec the `xmonad` from `PATH` (i.e. the vanilla one), which then in turn did the recompilation and executed the newly compiled binary. So the compiling was done by the vanilla version, which had knowledge of `ghc` and friends due to the wrapper.

Now in your setup the `xmonad with config` does not do the double exec but rather does the recompilation step directly, so it will not know about `ghc`, unless you put it in `PATH`.

**Pull request merged**
