### PR TITLE
python doc: update virtualenv section

### PR DESCRIPTION
**Pull request by danbst**
- make it easy to switch python 2/3
- add glibcLocales dep (not sure it is still required after https://github.com/NixOS/nixpkgs/pull/54485
  but manual is also used by users of Nixpkgs versions <19.03)
- use `mkShell`
- use `libffi`, as it is required for Python3 `cryptography` (in my setup it worked with Python2 without this dep)
- set PYTHONPATH. Either this or `source venv/bin/activate` was missing.

Closes https://github.com/NixOS/nixpkgs/pull/46909

cc @FRidh @MelleB

### CODE REVIEW

**Comment by FRidh** [comment]
Considering this example is not a supported workflow it should never have been part of the manual.

**Comment by danbst** [comment]
@FRidh mmm, what are the problems here? I do advocate exactly this (wiki section https://nixos.wiki/wiki/Python#Emulating_virtualenv_with_nix-shell), and do use exactly this at company (I'm forced to, because I use NixOS).

But in case this isn't supported by you, then it's fine. I'll merge it before branchoff if there are no other objections.

**Comment by danbst** [comment]
@FRidh I've found  your concerns at https://github.com/NixOS/nixpkgs/pull/21837#pullrequestreview-16391708

Now I understand that even if this example can work for some (me included), it is not easy to make it work in general case.

**Comment by Mic92** [comment]
It wouldn't be necessary after https://github.com/NixOS/nixpkgs/pull/54485
however for nixpkgs we also need support on macOS, which is also possible to add, 
but I currently have not the OS to implement it and test it.

**Comment by Mic92** [comment]
I think it is OK to have it in the manual, if we mention the limitations of it,
i.e. mention the problems with GC. It is also possible to use some packages from the nix store (numpy, pyqt) if one using `--system-site-packages`. The GC problem can be also worked around by using a persistent GC root https://github.com/direnv/direnv/wiki/Nix#persistent-shell

I even think we still need this option because using nixpkgs python package sets limits one to the versions given by nixpkgs. These are likely to be not compatible with whatever a different project is working on. Also we https://github.com/garbas/pypi2nix it forces one to create your own list of overrides for every package
that needs manual intervention, which can become painful for more complex projects (also it would try to rebuild it everytime from the start after an error).
Also the nix workflow does not allow you to have editable dependencies, which are sometimes necessary if you want to fix stuff in other packages or just add a breakpoint to the source code.

**Comment by danbst** [comment]
Closing this, as `virtualenv` isn't officially supported for Nixpkgs. But still referenced this PR from https://nixos.wiki/wiki/Python#Emulating_virtualenv_with_nix-shell

**Comment by pmyjavec** [comment]
@danbst ,

Sorry to resurrect  an old PR, but I love this! Thank you.

**Comment by Pablo1107** [comment]
Another sorry for resurrecting this PR, but the [example](https://nixos.wiki/wiki/Python#Emulating_virtualenv_with_nix-shell) giving in the wiki is (maybe?) wrong?

Shouldn't `in pkgs.stdenv.mkShell {` be `in pkgs.mkShell {`?

**Comment by Mic92** [comment]
> Another sorry for resurrecting this PR, but the [example](https://nixos.wiki/wiki/Python#Emulating_virtualenv_with_nix-shell) giving in the wiki is (maybe?) wrong?
> 
> Shouldn't `in pkgs.stdenv.mkShell {` be `in pkgs.mkShell {`?

yes.

**Pull request closed without merging**
