### PR TITLE
Linux 5.15

### PR DESCRIPTION
**Pull request by xaverdh**
###### Motivation for this change
New stable kernel.

###### Things done

Still building locally

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alyssais** [comment]
@OfBorg test simple

**Comment by alyssais** [comment]
@ofborg test latestKernel.login

**Comment by Ma27** [comment]
Please update nixos/tests/kernel-generic.nix.

**Comment by Ma27** [comment]
This doesn't seem to evaluate - locally at least:

```
λ ma27 [~/Projects/nixpkgs] at  linux-5.15 ✔
→ lbmf nixos/tests/kernel-generic.nix -A linuxPackages_5_15                                                                                                                                            [a0e10eb992d]
error: attribute 'linuxPackages_5_15' missing

       at /home/ma27/Projects/nixpkgs/nixos/tests/kernel-generic.nix:26:14:

           25|   }) args);
           26|   kernels = {
             |              ^
           27|     inherit (pkgs)
(use '--show-trace' to show detailed location information)
```

**Comment by xaverdh** [comment]
> This doesn't seem to evaluate - locally at least:
> 
> ```
> λ ma27 [~/Projects/nixpkgs] at  linux-5.15 ✔
> → lbmf nixos/tests/kernel-generic.nix -A linuxPackages_5_15                                                                                                                                            [a0e10eb992d]
> error: attribute 'linuxPackages_5_15' missing
> 
>        at /home/ma27/Projects/nixpkgs/nixos/tests/kernel-generic.nix:26:14:
> 
>            25|   }) args);
>            26|   kernels = {
>              |              ^
>            27|     inherit (pkgs)
> (use '--show-trace' to show detailed location information)
> ```

I changed the tests to reference attributes from `linuxKernel` directly. It also tests all "vanilla" kernels now, so we don't need to manually track them there.

**Review by Ma27 — APPROVED** [review]

**Comment by xaverdh** [comment]
While looking at the tests, is it deliberate that we don't test the `5.14` version of the hardened packages?

**Comment by fabianhjr** [comment]
```
diff --git a/pkgs/top-level/aliases.nix b/pkgs/top-level/aliases.nix
index fc822f809e5a..2f269abb55c2 100644
--- a/pkgs/top-level/aliases.nix
+++ b/pkgs/top-level/aliases.nix
@@ -467,6 +467,7 @@ mapAliases ({
   linuxPackages_5_4 = linuxKernel.packages.linux_5_4;
   linuxPackages_5_10 = linuxKernel.packages.linux_5_10;
   linuxPackages_5_14 = linuxKernel.packages.linux_5_14;
+  linuxPackages_5_15 = linuxKernel.packages.linux_5_15;
 
   linux_mptcp_95 = linuxKernel.kernels.linux_mptcp_95;
   linux_rpi1 = linuxKernel.kernels.linux_rpi1;
@@ -483,6 +484,7 @@ mapAliases ({
   linux-rt_5_10 = linuxKernel.kernels.linux_rt_5_10;
   linux-rt_5_11 = linuxKernel.kernels.linux_rt_5_11;
   linux_5_14 = linuxKernel.kernels.linux_5_14;
+  linux_5_15 = linuxKernel.kernels.linux_5_15;
 
   # added 2020-04-04
   linuxPackages_testing_hardened = throw "linuxPackages_testing_hardened has been removed, please use linuxPackages_latest_hardened";
   ```
   
   Missing some convenience aliases.

**Comment by Princemachiavelli** [comment]
Looks like Linux 5.15 starting using the `-Wfatal-errors` flag which causes the ENA (used on Amazon AWS images) module to fail building.
    
    ❯ nix log /nix/store/2dijr7vb3qlmjx42y8xadhhdcsa5q1py-ena-2.5.0-5.15.drv
    @nix { "action": "setPhase", "phase": "unpackPhase" }
    unpacking sources
    unpacking source archive /nix/store/hr7q45xf00xd50209lv1m4van6d8kn1d-source
    source root is source
    @nix { "action": "setPhase", "phase": "patchPhase" }
    patching sources
    @nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
    updateAutotoolsGnuConfigScriptsPhase
    @nix { "action": "setPhase", "phase": "configurePhase" }
    configuring
    @nix { "action": "setPhase", "phase": "buildPhase" }
    building
    build flags: SHELL=/nix/store/b9kazb4rcz4mm7am51c8zbzqxl4dycr1-bash-5.1-p8/bin/bash
    make -C /nix/store/dqrxrsf208j3f63xrz3wlvv1dsd3bqx2-linux-5.15-dev/lib/modules/5.15.0/build M=/build/source/kernel/linux/ena modules
    make[1]: Entering directory '/nix/store/dqrxrsf208j3f63xrz3wlvv1dsd3bqx2-linux-5.15-dev/lib/modules/5.15.0/build'
      CC [M]  /build/source/kernel/linux/ena/ena_netdev.o
      CC [M]  /build/source/kernel/linux/ena/ena_ethtool.o
    /build/source/kernel/linux/ena/ena_ethtool.c:1072:19: error: initialization of 'int (*)(struct net_device *, struct ethtool_coalesce *, struct kernel_ethtool_co>
     1072 |  .get_coalesce  = ena_get_coalesce,
          |                   ^~~~~~~~~~~~~~~~
    compilation terminated due to -Wfatal-errors.
    cc1: some warnings being treated as errors
    make[2]: *** [/nix/store/dqrxrsf208j3f63xrz3wlvv1dsd3bqx2-linux-5.15-dev/lib/modules/5.15.0/source/scripts/Makefile.build:277: /build/source/kernel/linux/ena/en>
    make[1]: *** [/nix/store/dqrxrsf208j3f63xrz3wlvv1dsd3bqx2-linux-5.15-dev/lib/modules/5.15.0/source/Makefile:1868: /build/source/kernel/linux/ena] Error 2
    make[1]: Leaving directory '/nix/store/dqrxrsf208j3f63xrz3wlvv1dsd3bqx2-linux-5.15-dev/lib/modules/5.15.0/build'
    make: *** [Makefile:40: all] Error 2
    lines 1-26/26 (END)...skipping...
    @nix { "action": "setPhase", "phase": "unpackPhase" }
    unpacking sources
    unpacking source archive /nix/store/hr7q45xf00xd50209lv1m4van6d8kn1d-source
    source root is source
    @nix { "action": "setPhase", "phase": "patchPhase" }
    patching sources
    @nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
    updateAutotoolsGnuConfigScriptsPhase
    @nix { "action": "setPhase", "phase": "configurePhase" }
    configuring
    @nix { "action": "setPhase", "phase": "buildPhase" }
    building
    build flags: SHELL=/nix/store/b9kazb4rcz4mm7am51c8zbzqxl4dycr1-bash-5.1-p8/bin/bash
    make -C /nix/store/dqrxrsf208j3f63xrz3wlvv1dsd3bqx2-linux-5.15-dev/lib/modules/5.15.0/build M=/build/source/kernel/linux/ena modules
    make[1]: Entering directory '/nix/store/dqrxrsf208j3f63xrz3wlvv1dsd3bqx2-linux-5.15-dev/lib/modules/5.15.0/build'
      CC [M]  /build/source/kernel/linux/ena/ena_netdev.o
      CC [M]  /build/source/kernel/linux/ena/ena_ethtool.o
    /build/source/kernel/linux/ena/ena_ethtool.c:1072:19: error: initialization of 'int (*)(struct net_device *, struct ethtool_coalesce *, struct kernel_ethtool_co>
     1072 |  .get_coalesce  = ena_get_coalesce,
          |                   ^~~~~~~~~~~~~~~~
    compilation terminated due to -Wfatal-errors.
    cc1: some warnings being treated as errors
    make[2]: *** [/nix/store/dqrxrsf208j3f63xrz3wlvv1dsd3bqx2-linux-5.15-dev/lib/modules/5.15.0/source/scripts/Makefile.build:277: /build/source/kernel/linux/ena/en>
    make[1]: *** [/nix/store/dqrxrsf208j3f63xrz3wlvv1dsd3bqx2-linux-5.15-dev/lib/modules/5.15.0/source/Makefile:1868: /build/source/kernel/linux/ena] Error 2
    make[1]: Leaving directory '/nix/store/dqrxrsf208j3f63xrz3wlvv1dsd3bqx2-linux-5.15-dev/lib/modules/5.15.0/build'
    make: *** [Makefile:40: all] Error 2

**Comment by fabianhjr** [comment]
@Princemachiavelli:

 - https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.15-Werror
 - https://www.phoronix.com/scan.php?page=news_item&px=GNU-Linux-Libre-5.15
 
 AFAIK
 
 > Then brought up in this heated conversation by Marco Elver was the idea of just enabling "-Werror" when doing a "COMPILE_TEST" kernel build for wanting to push the warning-as-error reporting to those compile testing the kernels. That path seems to be gaining ground and Linus calling it as "reasonable" change. That COMPILE_TEST approach for -Werror seems to be gaining ground as other upstream developers voice their opinion how they've also had to resort to disabling the new behavior to provide successful kernel builds. 
 
 This became the case and 5.15 has `-Werror` only on `COMPILE_TEST`.

**Pull request merged**
