### PR TITLE
libkrunfw: 4.0.0-unstable-2024-06-10 -> 4.2.0, libkrun: 1.9.3 -> 1.9.4

### PR DESCRIPTION
**Pull request by NickCao**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by NickCao** [comment]
Tested krunvm but couldn't get krun to work:
```
Error: Failed to set up user, bailing out

Caused by:
    0: Failed to read directory `/dev/dri`
    1: No such file or directory (os error 2)
```
cc @RossComputerGuy

**Comment by RossComputerGuy** [comment]
It's working for me

**Comment by NickCao** [comment]
> It's working for me

Does it require specific setups other than the `NIXOS_CURRENT_SYSTEM` env var?

**Comment by RossComputerGuy** [comment]
No but I forgot to specify it, I got this error after adding it:
```
No IPv4 nameserver available for DHCP
No IPv6 nameserver available for NDP/DHCPv6
DRI driver not from this Mesa build ('24.2.0-devel' vs '24.1.2')
failed to bind extensions
DRI driver not from this Mesa build ('24.2.0-devel' vs '24.1.2')
failed to bind extensions
DRI driver not from this Mesa build ('24.2.0-devel' vs '24.1.2')
failed to bind extensions
thread '<unnamed>' panicked at src/devices/src/virtio/gpu/virtio_gpu.rs:220:14:
Rutabaga initialization failed!: ComponentError(-1)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: could not initialize wayland channel: Operation not supported
sommelier_scope_timer: init wayland channel: 0.000235 seconds
```

**Comment by NickCao** [comment]
Result of `nixpkgs-review pr 330054` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>krun</li>
    <li>krunvm</li>
    <li>libkrun</li>
    <li>libkrun-sev</li>
    <li>libkrun-sev.dev</li>
    <li>libkrun.dev</li>
    <li>libkrunfw</li>
  </ul>
</details>

**Comment by NickCao** [comment]
The mesa version mismatch should be unrelated.

**Comment by RossComputerGuy** [comment]
> The mesa version mismatch should be unrelated.

It is, I just get it because I have the Asahi driver.

**Pull request merged**
