### PR TITLE
acl2: 6.5 -> 7.4; sbcl: remove 1.2.0 and 1.3.12

### PR DESCRIPTION
**Pull request by kini**
###### Motivation for this change

Short summary: ACL2 is out of date so I figured I should update it. Also removed some obsolete SBCL versions. See below for the long version.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Note: execution of all binary files works equally well as the previous version did, though it could be improved -- the libraries are not installed, for example.

---

### acl2: 6.5 -> 7.4, refactor

The `make regression` line was failing because the expression was
downloading a core-system-only, no-libraries source tarball.  I
switched to using fetchFromGitHub, which downloads the full source
code -- the core system as well as the "community books",
i.e. libraries -- but the libraries unfortunately do not build yet
because they have more dependencies than the core system, and they
also run into some impurity problems during the build process.

This commit changes the ACL2 package so that at least the user will
obtain the latest version of the core system, even though they won't
get the community books.  In a later commit I hope to fix this; it
will require either changes to ACL2 itself, or a patch to be applied
to ACL2 in nixpkgs.

ACL2 7.4 has no trouble building on the current version of SBCL in
nixpkgs, so I let it do so instead of using the ancient SBCL version
1.2.0 from 2014.

I also added myself as a maintainer to this package, since I'm an
active contributor to the ACL2 project and am interested in seeing it
working on Nix.

### sbcl: remove old versions 1.2.0, 1.3.12

SBCL 1.2.0 was being retained for the acl2 package, which no longer
needs it.  SBCL 1.3.12 was being retained for the maxima package,
which appears to no longer need it.

### CODE REVIEW

**Comment by kini** [comment]
I'd also like to ping @7c6f434c, who maintains ACL2 and SBCL, and @tohl, who maintains SBCL, as well as @peti, who maintains Maxima, since all three packages are affected. (Not sure how to request "reviewers" to this pull request, so I'm just pinging you in this comment.)

**Comment by kini** [comment]
Oh, I see @7c6f434c already closed it. Never mind then, I guess... :)

**Comment by 7c6f434c** [comment]
Technically speaking, Maxima is not even affected.

**Comment by kini** [comment]
True - at least it seems that way. I thought maybe I was overlooking
something, since the comment does say that sbcl 1.3.12 is needed for
maxima. This is my first real pull request to nixpkgs so I thought I should
be careful.

2017/11/04 午後4:27 "Michael Raskin" <notifications@github.com>:

**Comment by 7c6f434c** [comment]
Your description for the pull request is definitely among the best-written ones… Thanks.

**Pull request merged**
