### PR TITLE
init: signal-desktop on darwin

### PR DESCRIPTION
**Pull request by hlolli**
###### Motivation for this change

There's not darwin support currently.

###### Things done

copy/pasta from how slack is built on darwin, minus autoupdate patches, I guess we'll see after some time if that will cause issues.

Notabene, I have very bad taste in my mouth from not building from sources here :(

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by rmcgibbo — APPROVED** [review]
Result of `nixpkgs-review pr 122256` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>signal-desktop</li>
  </ul>
</details>

(I didn't actually try launching the binary though)

**Review by aaronjanse — CHANGES_REQUESTED** [review]
Exciting! Maybe it would make sense to write the `src` and `version` inside of each derivation instead of inheriting something that changes based on the platform?

It also might make sense to remove `platforms` from the common `meta` then write `meta = meta // { platforms = [ "the-platform-name" ]; }` inside each derivation

**Comment by aaronjanse** [comment]
Oh huh, you're right, this PR does match how the `slack` derivation does things

**Comment by hlolli** [comment]
My first instinct was to start a new file alongside linux. I wonder if this effects how the documentation is generated, generating two entities with different platform, or single entity with single platform (missing out the other?).

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 122256` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>signal-desktop</li>
  </ul>
</details>

**Review by siraben — APPROVED** [review]
LGTM, runs.

**Comment by primeos** [comment]
Sorry for my late reply to this.

> My first instinct was to start a new file alongside linux.

Personally I'd prefer that (putting it into a new file) as this currently seems to only reuse `meta` (and `pname` :D). That way it should be much easier to understand / look at the code and the diff would be smaller. It could also make sense to have a `generic.nix` with `version`, `sha256{Linux,Darwin}`, and `meta` and the rest in `linux.nix` and `darwin.nix`.

Not sure though if there are any existing patterns for this in Nixpkgs and how other contributors feel about this.

**Comment by hlolli** [comment]
going to abstract this cleaner in a later PR now that aarch64 supports seems to be around the corner according to the PR.
The auto-update is also terribly annoying.

**Pull request closed without merging**
