### PR TITLE
jetbrainsjdk: 1036.1 ~> 1136.20 (based on build #181.4203)

### PR DESCRIPTION
**Pull request by concatime**
Updating jetbrainsjdk to latest available version.

###### Motivation for this change
Living #YOLO, aka bleeding edge ;)

### CODE REVIEW

**Comment by adisbladis** [comment]
cc @edwtjo

**Comment by concatime** [comment]
Sorry for the title.

**Comment by adisbladis** [comment]
Please fix commit message to include package name

**Comment by matklad** [comment]
I no longer work at JetBrains, but here's the useful bit of information:

The version of jdk actually used by IDEs is specified in here: https://github.com/JetBrains/intellij-community/blob/b98a9ccc6b9e5ae05b71ed855a5c91dd9f6c6587/build/dependencies/gradle.properties#L4. In general, development builds of JDK are also published to bintray, so just blindly picking the latest version from bin tray is risky. Accidentally, this is exactly what I've done initially, so, for a while, NixOS users used JDK which was more bleeding edge than anything bundled with IDEs :)

So, I think the better approach to updating here is to go to the https://www.jetbrains.com/idea/download/#section=linux, note the build number (`173.4127` currently), find the corresponding branch: https://github.com/JetBrains/intellij-community/blob/173.4127/build/dependencies/gradle.properties and use the version from there `jdkBuild=u152b1024.8`.

**Comment by matklad** [comment]
cc @forantar who I believe is on the JBSDK team :)

**Comment by Mic92** [comment]
What @matklad said, sounds reasonable. So at the moment nixos is still ahead of jetbrains own versions?

**Comment by concatime** [comment]
I followed the instructions provided @matklad, and fixed the message.

**Pull request merged**
