### PR TITLE
cd-discid: 0.9 -> 1.4

### PR DESCRIPTION
**Pull request by rycee**
Also did some package cleanups and added myself as maintainer.

### CODE REVIEW

**Comment by aristidb** [comment]
This does not build here.

**Comment by aristidb** [comment]
How did this work on your machine, @rycee ? And why does the travis-ci let this pass?

**Comment by jagajaga** [comment]
That worked on my machine..

**Comment by aristidb** [comment]
@jagajaga Do you have a /usr/bin/install ?

**Comment by aristidb** [comment]
Fixed by ed1355e0f1ad961139263485f72e9b0c6d9a8d3c

**Comment by rycee** [comment]
Sorry! I usually verify builds in a clean NixOS virtual machine before opening pull requests but must have skipped that crucial step this time.

**Pull request merged**
