### PR TITLE
standardnotes: 3.181.23 -> 3.191.4

### PR DESCRIPTION
**Pull request by baalajimaestro**
## Description of changes
https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fdesktop%403.191.4
Upgraded standardnotes

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).
---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by baalajimaestro** [comment]
Closes #293270

**Comment by JohnRTitor** [comment]
Since v3.194.0 is available now, can you update the PR accordingly?

**Comment by baalajimaestro** [comment]
> Since v3.194.0 is available now, can you update the PR accordingly?

The problem is, i am not sure how to cleanly build it, it fails at the configuring auto tools phase, which i was able to override and no-op, but im sure thats not the right way, and there is something else thats triggering the autotools phase.

**Comment by baalajimaestro** [comment]
```
  standardnotes_overlay = self: super: {
    standardnotes = super.standardnotes.overrideAttrs (oldAttrs: rec {
      version = "3.194.0";
      src = super.fetchurl {
        url = "https://github.com/standardnotes/app/releases/download/%40standardnotes%2Fdesktop%403.194.0/standard-notes-3.194.0-linux-amd64.deb";
        sha512 = "sha512-RLeDqkeHtSW6Tk9P8qZvXtB92joxo6caOUVx1bPjKn+b8Wvnfs4lE0jjldQlOaHXVs20luI+dMu1xRyQCZU6gA==";
      };
      updateAutotoolsGnuConfigScriptsPhase = ":";
      installPhase = ''
        runHook preInstall

        mkdir -p $out/bin $out/share/standardnotes
        cp -R usr/share/{applications,icons} $out/share
        cp -R opt/Standard\ Notes/resources/app.asar $out/share/standardnotes/

        makeWrapper ${pkgs.electron_27}/bin/electron $out/bin/standardnotes \
          --add-flags $out/share/standardnotes/app.asar \
          --prefix LD_LIBRARY_PATH : ${lib.makeLibraryPath [ pkgs.libsecret pkgs.stdenv.cc.cc.lib ]}

        ${pkgs.desktop-file-utils}/bin/desktop-file-install --dir $out/share/applications \
          --set-key Exec --set-value standardnotes usr/share/applications/standard-notes.desktop

        runHook postInstall
      '';

    });
  };
  ```
  Overlay for anyone who wishes to update theirs, until this is sorted out properly

**Comment by wegank** [comment]
Superseded by #365265.

**Pull request closed without merging**
