### PR TITLE
mysql57: drop

### PR DESCRIPTION
**Pull request by yorickvP**
###### Description of changes

This PR moves everything that was using mysql57 to mariadb or mysql80.
mysql57 is technically still supported, but there is not really a good reason to use it over mariadb or mysql80 and even debian has dropped it now. [It also creates a security burden.](https://repology.org/project/mysql/cves?version=5.7.40)

- rework mariadb to preserve .override attribute on versions (similar to postgres)
- add mariadb-embedded override that also builds libmysqld and keeps the `mysql_config` output (which we normally delete to avoid people from linking with mariadb to get libmysqlclient)
- switch amorok to mariadb-embedded
- switch cqrlog to mariadb.server
- switch dspam to mariadb-connector
- switch mysql-workbench to mysql80 (doesn't presently build, see #191174, but I tested with that)
- drop mysql 5.7
- add release note

#93991, #90914

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [x] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by yorickvP** [comment]
@ofborg build cqrlog dspam amarok mariadb-embedded mariadb

**Review by AndersonTorres — APPROVED** [review]
One week, and I merge this if no one complains

**Comment by ajs124** [comment]
What exactly does 8b30afdd78c761bfeb92a6509b4fad2ad1461f75 do? What does this preserve .override?

Can you give an example of what doesn't work before this but works after?

**Comment by yorickvP** [comment]
> What exactly does [8b30afd](https://github.com/NixOS/nixpkgs/commit/8b30afdd78c761bfeb92a6509b4fad2ad1461f75) do? How does this preserve .override?
> 
> Can you give an example of what doesn't work before this but works after?

Before: `mariadb_106.override` -> `error: attribute 'override' missing`
After: `mariadb-embedded = mariadb_106.override { withEmbedded = true; }`

**Review by SuperSandro2000 — APPROVED** [review]
took a brief look and didn't find anything obvious

**Pull request merged**
