### PR TITLE
jellyfin-web: switch to apple-sdk_11

### PR DESCRIPTION
**Pull request by khaneliman**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 352923`

---
### `x86_64-linux`

---
### `aarch64-linux`

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>jellyfin</li>
    <li>jellyfin-web</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>jellyfin</li>
    <li>jellyfin-web</li>
  </ul>
</details>

**Comment by minijackson** [comment]
I'm not familiar with Darwin, so if someone more knowledgeable could help review, it'd be great!

**Comment by purcell** [comment]
@minijackson Same here — looks reasonable but I can't meaningfully review it :)

**Comment by khaneliman** [comment]
Basically, the apple sdk frameworks used to need to be declared individually but are all now provided by `apple-sdk`. The `stdenv` automatically gets `apple-sdk` for the SDK we build with and a deployment target SDK, referred to as `minSDKVersion`. This just changes to new the new format of declaring apple-sdk overrides when you need to change it. Having said that, I'm not so sure we really need the 11 build version explicitly declared here, but I didn't want to change your package to behave any differently than it did before since I don't use/maintain it.

**Review by GaetanLepage — APPROVED** [review]

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 352923`

---
### `x86_64-darwin`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>jellyfin</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>jellyfin-web</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>jellyfin</li>
    <li>jellyfin-web</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
`jellyfin-ffmpeg` fails on `x86_64-darwin with errors of the following kind:
```
libavdevice/avfoundation.m:765:41: error: must use 'enum' tag to refer to type 'AVMediaType'
static NSArray* getDevicesWithMediaType(AVMediaType mediaType) {
                                        ^
                                        enum
```

This could be related to https://github.com/NixOS/nixpkgs/pull/353338.

**Comment by khaneliman** [comment]
> `jellyfin-ffmpeg` fails on `x86_64-darwin with errors of the following kind:
> 
> ```
> libavdevice/avfoundation.m:765:41: error: must use 'enum' tag to refer to type 'AVMediaType'
> static NSArray* getDevicesWithMediaType(AVMediaType mediaType) {
>                                         ^
>                                         enum
> ```
> 
> This could be related to #353338.

Yeah, looks like something changed from the time I opened PR to master, now. I can build it on branch and nixpkgs-review fails with that. Saw they just had some releases, gonna try bumping it real quick.

**Comment by khaneliman** [comment]
@GaetanLepage looks like a recent bump in master has conversation also about staging maybe just breaking it https://github.com/NixOS/nixpkgs/pull/351966

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 352923`

---
### `x86_64-darwin`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>jellyfin</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>jellyfin-web</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>jellyfin</li>
    <li>jellyfin-web</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
> @GaetanLepage looks like a recent bump in master has conversation also about staging maybe just breaking it #351966 See also #353600

Indeed, but people seem to say that it is now fixed. It actually builds fine on `master`. However, it seems to be failing on this branch...

**Review by GaetanLepage — APPROVED** [review]

**Pull request merged**
