### PR TITLE
gnome.mutter42: 42.7 → 42.9

### PR DESCRIPTION
**Pull request by bobby285271**
https://gitlab.gnome.org/GNOME/mutter/-/compare/42.7...42.9

###### Description of changes

This is the last mutter42 release, this is now EOL.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
TODO:

- [ ] I assume 42.9 should contain all the focus fixes which are regressed in 42.8?
- [ ] Pantheon (x11 only right now) is not likely relevant with the `gst-play-1.0 test.mp4 test.mp4 --videosink="gtkwaylandsink"` crash?
- [ ] Do we backport https://github.com/GNOME/mutter/commit/e0a9bab97037ec547aa6a53c846c45cd4f83d4c7 for log spam introduced by GLib 2.76?

**Comment by bobby285271** [comment]
@ofborg test pantheon

**Comment by bobby285271** [comment]
I want a backport for https://gitlab.gnome.org/GNOME/mutter/-/issues/2566 as well, I managed to reproduce the log spam when testing GNOME 44 PR :sweat:

(For cinnamon there is a new muffin release to address that)

**Comment by bobby285271** [comment]
@ofborg test pantheon

**Comment by bobby285271** [comment]
[GNOME 44 PR] Crash when dragging window to another workspace in multitasking view :sweat_drops: 

```
#0  clutter_actor_run_actions (self=0x143c960, phase=CLUTTER_PHASE_BUBBLE, event=0x2e26390) at ../clutter/clutter/clutter-actor.c:12318
#1  clutter_actor_event (actor=actor@entry=0x143c960, event=event@entry=0x2e26390, capture=capture@entry=0) at ../clutter/clutter/clutter-actor.c:12365
#2  0x00007f4fb6b3fc06 in _clutter_actor_handle_event (self=self@entry=0x97b5c0, root=0x143c960, event=event@entry=0x2e26390) at ../clutter/clutter/clutter-actor.c:19172
#3  0x00007f4fb6b73f69 in emit_event_chain (event=0x2e26390, target=0x97b5c0) at ../clutter/clutter/clutter-main.c:681
#4  emit_event (event=<optimized out>, target=<optimized out>) at ../clutter/clutter/clutter-main.c:699
#5  _clutter_process_event_details (context=0x7b2500, event=0x2e26390, stage=0x9a81b0) at ../clutter/clutter/clutter-main.c:899
#6  _clutter_process_event (event=event@entry=0x2e26390) at ../clutter/clutter/clutter-main.c:989
#7  0x00007f4fb6b8e910 in _clutter_stage_queue_event (stage=0x9a81b0, event=0x2e26390, copy_event=1) at ../clutter/clutter/clutter-stage.c:623
#8  0x00007f4fb6b73d8e in clutter_do_event (event=<optimized out>) at ../clutter/clutter/clutter-main.c:829
#9  0x00007f4fb6ca0ac8 in meta_x11_handle_event (backend=backend@entry=0x693760, xevent=xevent@entry=0x7fff75a301a0) at ../src/backends/x11/meta-event-x11.c:106
#10 0x00007f4fb6c9f015 in handle_host_xevent (event=0x7fff75a301a0, backend=0x693760) at ../src/backends/x11/meta-backend-x11.c:405
#11 x_event_source_dispatch (source=<optimized out>, callback=<optimized out>, user_data=<optimized out>) at ../src/backends/x11/meta-backend-x11.c:458
#12 0x00007f4fb7cc4dad in g_main_dispatch (context=0x692040) at ../glib/gmain.c:3460
#13 g_main_context_dispatch (context=context@entry=0x692040) at ../glib/gmain.c:4200
#14 0x00007f4fb7cc5058 in g_main_context_iterate (context=0x692040, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4276
#15 0x00007f4fb7cc530f in g_main_loop_run (loop=0x14ea7d0) at ../glib/gmain.c:4479
#16 0x00007f4fb6cde875 in meta_context_run_main_loop (context=<optimized out>, error=error@entry=0x7fff75a303e8) at ../src/core/meta-context.c:437
#17 0x000000000042d7f4 in gala_main (args=<optimized out>, args_length1=<optimized out>) at ../src/Main.vala:85
#18 0x00007f4fb662924e in __libc_start_call_main (main=main@entry=0x4219f0 <main>, argc=argc@entry=1, argv=argv@entry=0x7fff75a30828) at ../sysdeps/nptl/libc_start_call_main.h:58
#19 0x00007f4fb6629309 in __libc_start_main_impl (main=0x4219f0 <main>, argc=1, argv=0x7fff75a30828, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fff75a30818) at ../csu/libc-start.c:389
#20 0x0000000000421a25 in _start ()
```

**Comment by bobby285271** [comment]
Found the backtrace in https://gitlab.gnome.org/GNOME/mutter/-/issues/2495, no fix?

**Comment by bobby285271** [comment]
Forwarded to https://github.com/elementary/gala/issues/1580 for now :upside_down_face:

**Comment by jtojnar** [comment]
That does not sound like it should fix anything. `g_list_copy` just makes a shallow copy of the (linked) list so if it crashes in https://gitlab.gnome.org/GNOME/mutter/-/blob/42.9/clutter/clutter/clutter-actor.c#L12318, it should crash when copying the list. The dereferencing would need to occur for shallow copy as well.

**Comment by bobby285271** [comment]
:upside_down_face: Ugh, I actually started trying this since the backtrace also reminds me of [the openbox crash](https://bugs.archlinux.org/task/77853) ([patch](https://github.com/Mikachu/openbox/commit/d41128e5a1002af41c976c8860f8299cfcd3cd72)) ~~Trying to learn how to use valgrind right now (sorry)~~

**Comment by jtojnar** [comment]
Oh, reading the Xfce commit explains it. Presumably some of the functions in the loop modify the actions list: https://gitlab.xfce.org/xfce/xfce4-session/-/commit/321ca64377eb8ddf5572f260e78f119c9e87dd8b

**Comment by bobby285271** [comment]
Replaced by #222752 (which is manually pushed to gnome branch)

**Comment by bobby285271** [comment]
Gala has some very early WIP support for mutter 44 now. From my testing so far I cannot reproduce the crash with mutter 44.

**Pull request closed without merging**
