### PR TITLE
vimPlugins: update

### PR DESCRIPTION
**Pull request by lovesegfault**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
Result of `nixpkgs-review pr 148265` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>vimPlugins.vim-clap</li>
  </ul>
</details>
<details>
  <summary>80 packages built:</summary>
  <ul>
    <li>spacevim</li>
    <li>tests.vim.test_vim_with_vim_nix</li>
    <li>vimPlugins.NrrwRgn</li>
    <li>vimPlugins.Recover-vim</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.aurora</li>
    <li>vimPlugins.chadtree</li>
    <li>vimPlugins.cmp-cmdline</li>
    <li>vimPlugins.cmp-omni</li>
    <li>vimPlugins.cmp-path</li>
    <li>vimPlugins.cmp-tabnine</li>
    <li>vimPlugins.cmp-tmux</li>
    <li>vimPlugins.cmp-treesitter</li>
    <li>vimPlugins.colorbuddy-nvim</li>
    <li>vimPlugins.crates-nvim</li>
    <li>vimPlugins.deol-nvim</li>
    <li>vimPlugins.diffview-nvim</li>
    <li>vimPlugins.edge</li>
    <li>vimPlugins.friendly-snippets</li>
    <li>vimPlugins.git-worktree-nvim</li>
    <li>vimPlugins.gitlinker-nvim</li>
    <li>vimPlugins.gitsigns-nvim</li>
    <li>vimPlugins.goto-preview</li>
    <li>vimPlugins.gruvbox-material</li>
    <li>vimPlugins.gruvbox-nvim</li>
    <li>vimPlugins.harpoon</li>
    <li>vimPlugins.indent-blankline-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.lir-nvim</li>
    <li>vimPlugins.lsp_signature-nvim</li>
    <li>vimPlugins.luasnip</li>
    <li>vimPlugins.neovim-ayu</li>
    <li>vimPlugins.nightfox-nvim</li>
    <li>vimPlugins.nord-nvim</li>
    <li>vimPlugins.null-ls-nvim</li>
    <li>vimPlugins.nvim-autopairs</li>
    <li>vimPlugins.nvim-bqf</li>
    <li>vimPlugins.nvim-cmp</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-dap-ui</li>
    <li>vimPlugins.nvim-highlite</li>
    <li>vimPlugins.nvim-hlslens</li>
    <li>vimPlugins.nvim-jdtls</li>
    <li>vimPlugins.nvim-lint</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-notify</li>
    <li>vimPlugins.nvim-scrollview</li>
    <li>vimPlugins.nvim-solarized-lua</li>
    <li>vimPlugins.onedarkpro-nvim</li>
    <li>vimPlugins.packer-nvim</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.sonokai</li>
    <li>vimPlugins.srcery-vim</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.tokyonight-nvim</li>
    <li>vimPlugins.vifm-vim</li>
    <li>vimPlugins.vim-buffergator</li>
    <li>vimPlugins.vim-dispatch</li>
    <li>vimPlugins.vim-fugitive</li>
    <li>vimPlugins.vim-git</li>
    <li>vimPlugins.vim-liquid</li>
    <li>vimPlugins.vim-lsp</li>
    <li>vimPlugins.vim-matchup</li>
    <li>vimPlugins.vim-prosession</li>
    <li>vimPlugins.vim-sandwich</li>
    <li>vimPlugins.vim-table-mode</li>
    <li>vimPlugins.vim-tpipeline</li>
    <li>vimPlugins.vim-ultest</li>
    <li>vimPlugins.vim-wakatime</li>
    <li>vimPlugins.vimade</li>
    <li>vimPlugins.vimspector</li>
    <li>vimPlugins.vimtex</li>
  </ul>
</details>

**Comment by Mic92** [comment]
The rust package checksums in the `vimPlugins.vim-clap` override needs an update from the looks of it.

**Comment by jonringer** [comment]
merge conflict :(

**Comment by oxalica** [comment]
Waiting for this. `vim-sandwich`'s surround-keymap is broken in `nixos-unstable` and this would fix it.

**Comment by lovesegfault** [comment]
I'm traveling, someone should take this on

**Comment by oxalica** [comment]
See #149330

**Pull request closed without merging**
