### PR TITLE
system76-dkms: 1.0.13 -> 1.0.16

### PR DESCRIPTION
**Pull request by khumba**
The latest release adds a small compatibility fix needed for building against Linux 6.11 (which I've confirmed builds okay now).

Requested by: https://github.com/NixOS/nixpkgs/issues/348615

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by khumba** [comment]
Hi @Mic92, you reviewed this before so I hope you don't mind me pinging you again.  I'm not sure what's up with the Codeowners check failure, but it looks transient or unrelated.

**Comment by sjmonson** [comment]
@ahoneybun

**Comment by ahoneybun** [comment]
> @ahoneybun

if you have testing method I'd be happy to test this once I get my system76-power build issue fixed.

**Comment by khumba** [comment]
Hi @ahoneybun, great to see you here.  The way I would test this is:

1) Clone nixpkgs.git locally, and either check out the exact commit my system is already at, or just the `nixos-YY.MM` or `nixos-unstable` channel branch[1] matching my system.
2) Cherry pick this commit.
3) Run `nixos-rebuild boot -Q -I nixpkgs=/path/to/local/nixpkgs.git`, confirm that the updated module is built in the output, then reboot into the new system.

Thanks in advance for testing this.  The nixpkgs-review run confirmed that it builds against the latest 6.11 kernel as well as older ones, but I haven't booted into it yet on NixOS ($otherDistros went fine).

On that note: would you be interested in taking over for me maintaining these three kernel modules in Nixpkgs?  Once this is merged, I am planning to orphan of all of my packages in Nixpkgs except for nvd, as my involvement with Nix has been basically limited to just nvd for quite a while.  Well, that plus a legacy Nix system at work :).

[1] https://wiki.nixos.org/wiki/Channel_branches

**Comment by khumba** [comment]
(That's assuming you're not using flakes, if you are then you might need a different approach.)

**Comment by ahoneybun** [comment]
> (That's assuming you're not using flakes, if you are then you might need a different approach.)

From my understanding I am using Flakes:

https://gitlab.com/ahoneybun/nix-configs/-/blob/main/flake.nix?ref_type=heads

but I have a general configuration.nix file:

https://gitlab.com/ahoneybun/nix-configs/-/blob/main/configuration.nix?ref_type=heads

**Comment by ahoneybun** [comment]
> Hi @ahoneybun, great to see you here. The way I would test this is:
> 
>     1. Clone nixpkgs.git locally, and either check out the exact commit my system is already at, or just the `nixos-YY.MM` or `nixos-unstable` channel branch[1] matching my system.
> 
>     2. Cherry pick this commit.
> 
>     3. Run `nixos-rebuild boot -Q -I nixpkgs=/path/to/local/nixpkgs.git`, confirm that the updated module is built in the output, then reboot into the new system.
> 
> 
> Thanks in advance for testing this. The nixpkgs-review run confirmed that it builds against the latest 6.11 kernel as well as older ones, but I haven't booted into it yet on NixOS ($otherDistros went fine).
> 
> On that note: would you be interested in taking over for me maintaining these three kernel modules in Nixpkgs? Once this is merged, I am planning to orphan of all of my packages in Nixpkgs except for nvd, as my involvement with Nix has been basically limited to just nvd for quite a while. Well, that plus a legacy Nix system at work :).
> 
> [1] https://wiki.nixos.org/wiki/Channel_branches

I may be willing to if you stay around for some questions as I have just been maintaining a few COSMIC packages but no modules.

**Comment by khumba** [comment]
> I may be willing to if you stay around for some questions as I have just been maintaining a few COSMIC packages but no modules.

I'm happy to share any knowledge I have.

> From my understanding I am using Flakes:

I think you could set flake.nix's `inputs.nixpkgs.url` to your local nixpkgs path then, either as a literal path or a `"path:..."` string, if I'm reading the manual correctly:

https://nix.dev/manual/nix/2.18/command-ref/new-cli/nix3-flake.html#path-like-syntax

**Comment by ahoneybun** [comment]
> > I may be willing to if you stay around for some questions as I have just been maintaining a few COSMIC packages but no modules.
> 
> I'm happy to share any knowledge I have.
> 
> > From my understanding I am using Flakes:
> 
> I think you could set flake.nix's `inputs.nixpkgs.url` to your local nixpkgs path then, either as a literal path or a `"path:..."` string, if I'm reading the manual correctly:
> 
> https://nix.dev/manual/nix/2.18/command-ref/new-cli/nix3-flake.html#path-like-syntax

Thank you very much and I look forward to getting system76-io-dkms updated as well:

https://github.com/NixOS/nixpkgs/pull/349436

I think that's similar to how I tested my nixos-hardware PR for the system76 galp5-1650.

**Comment by ahoneybun** [comment]
> > I think it may be fairly important to have that enabled since the whole point of this is for a system76 Thelio desktop.
> 
> I need it for my laptop as well, my machine configuration hasn't been building until this change due to that being enabled. Unfortunately rebooting right now to fully test, probably not for a few hours, but I wanted to share the tip about `--override-input` so I posted prematurely sorry

Ah sorry this is for the dkms not the io-dkms which is Thelio only.

**Comment by ahoneybun** [comment]
It would be really nice to get this in soon as folks are stuck on the 6.10 or below kernel until this is merged.

**Comment by ahoneybun** [comment]
It looks like the 6.10 is now EOL so I had to drop down to the 6.6 kernel.

**Review by ahoneybun — APPROVED** [review]

**Review by nickgerace — APPROVED** [review]

**Comment by nyabinary** [comment]
Can you copy the suggestions I gave here https://github.com/NixOS/nixpkgs/pull/349436#pullrequestreview-2382378140 to this PR as well?

**Comment by khumba** [comment]
Thanks for the reviews everyone.

> Can you copy the suggestions I gave here [#349436 (review)](https://github.com/NixOS/nixpkgs/pull/349436#pullrequestreview-2382378140) to this PR as well?

Sure, done.

**Review by nyabinary — APPROVED** [review]

**Pull request merged**
