### PR TITLE
mypy: 0.941 → 0.961

### PR DESCRIPTION
**Pull request by fabianhjr**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 179842` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages marked as broken and skipped:</summary>
  <ul>
    <li>apache-airflow</li>
    <li>home-assistant-component-tests.bsblan</li>
    <li>python310Packages.apache-airflow</li>
    <li>python310Packages.tvdb_api</li>
    <li>python39Packages.apache-airflow</li>
    <li>python39Packages.tvdb_api</li>
    <li>truvari</li>
    <li>tvnamer</li>
  </ul>
</details>
<details>
  <summary>30 packages failed to build:</summary>
  <ul>
    <li>barman</li>
    <li>cura</li>
    <li>portmod</li>
    <li>prospector</li>
    <li>python310Packages.angr</li>
    <li>python310Packages.angrcli</li>
    <li>python310Packages.angrop</li>
    <li>python310Packages.baselines</li>
    <li>python310Packages.gradient</li>
    <li>python310Packages.ibis-framework</li>
    <li>python310Packages.jupytext</li>
    <li>python310Packages.numpy-stl</li>
    <li>python310Packages.progressbar2</li>
    <li>python310Packages.pylint-django</li>
    <li>python310Packages.python-utils</li>
    <li>python310Packages.scancode-toolkit</li>
    <li>python39Packages.angr</li>
    <li>python39Packages.angrcli</li>
    <li>python39Packages.angrop</li>
    <li>python39Packages.baselines</li>
    <li>python39Packages.gradient</li>
    <li>python39Packages.ibis-framework</li>
    <li>python39Packages.jupytext</li>
    <li>python39Packages.numpy-stl</li>
    <li>python39Packages.progressbar2</li>
    <li>python39Packages.pylint-django</li>
    <li>python39Packages.pysychonaut</li>
    <li>python39Packages.python-utils</li>
    <li>python39Packages.requests-cache</li>
    <li>python39Packages.scancode-toolkit</li>
  </ul>
</details>
<details>
  <summary>138 packages built:</summary>
  <ul>
    <li>anime-downloader</li>
    <li>autosuspend</li>
    <li>azure-cli</li>
    <li>chia</li>
    <li>cmake-format</li>
    <li>coconut (python310Packages.coconut)</li>
    <li>conan</li>
    <li>cryptop</li>
    <li>cve-bin-tool</li>
    <li>flitter</li>
    <li>home-assistant-component-tests.plugwise</li>
    <li>home-assistant-component-tests.sia</li>
    <li>json-schema-for-humans (python310Packages.json-schema-for-humans)</li>
    <li>mnamer</li>
    <li>mypy (python310Packages.mypy)</li>
    <li>nix-pin</li>
    <li>openai (python310Packages.openai)</li>
    <li>paperless-ngx</li>
    <li>pokete</li>
    <li>pwndbg</li>
    <li>pylint (python310Packages.pylint)</li>
    <li>python310Packages.aiokef</li>
    <li>python310Packages.algebraic-data-types</li>
    <li>python310Packages.applicationinsights</li>
    <li>python310Packages.avro-python3</li>
    <li>python310Packages.azure-identity</li>
    <li>python310Packages.bsblan</li>
    <li>python310Packages.cattrs</li>
    <li>python310Packages.concurrent-log-handler</li>
    <li>python310Packages.dataclasses-json</li>
    <li>python310Packages.diff-cover</li>
    <li>python310Packages.diofant</li>
    <li>python310Packages.dragonfly</li>
    <li>python310Packages.duckdb</li>
    <li>python310Packages.duckdb-engine</li>
    <li>python310Packages.fingerprints</li>
    <li>python310Packages.flake8-import-order</li>
    <li>python310Packages.globus-sdk</li>
    <li>python310Packages.ics</li>
    <li>python310Packages.immutables</li>
    <li>python310Packages.isort</li>
    <li>python310Packages.msal-extensions</li>
    <li>python310Packages.mypy-boto3-builder</li>
    <li>python310Packages.pandas-stubs</li>
    <li>python310Packages.parsedmarc</li>
    <li>python310Packages.pixelmatch</li>
    <li>python310Packages.plugwise</li>
    <li>python310Packages.portalocker</li>
    <li>python310Packages.pylama</li>
    <li>python310Packages.pylint-celery</li>
    <li>python310Packages.pylint-flask</li>
    <li>python310Packages.pylint-plugin-utils</li>
    <li>python310Packages.pyls-flake8</li>
    <li>python310Packages.pyls-isort</li>
    <li>python310Packages.pyls-spyder</li>
    <li>python310Packages.pylsp-mypy</li>
    <li>python310Packages.pynamodb</li>
    <li>python310Packages.pynput</li>
    <li>python310Packages.pysiaalarm</li>
    <li>python310Packages.pysychonaut</li>
    <li>python310Packages.pytest-isort</li>
    <li>python310Packages.pytest-mypy</li>
    <li>python310Packages.pytest-mypy-plugins</li>
    <li>python310Packages.pytest-pylint</li>
    <li>python310Packages.python-lsp-black</li>
    <li>python310Packages.python-lsp-server</li>
    <li>python310Packages.requests-cache</li>
    <li>python310Packages.setuptools-lint</li>
    <li>spyder (python310Packages.spyder)</li>
    <li>python310Packages.spyse-python</li>
    <li>python310Packages.statmake</li>
    <li>python310Packages.tatsu</li>
    <li>python310Packages.typed-settings</li>
    <li>python310Packages.typical</li>
    <li>python310Packages.zimports</li>
    <li>python39Packages.aiokef</li>
    <li>python39Packages.algebraic-data-types</li>
    <li>python39Packages.applicationinsights</li>
    <li>python39Packages.avro-python3</li>
    <li>python39Packages.azure-identity</li>
    <li>python39Packages.bsblan</li>
    <li>python39Packages.cattrs</li>
    <li>python39Packages.coconut</li>
    <li>python39Packages.concurrent-log-handler</li>
    <li>python39Packages.dataclasses-json</li>
    <li>python39Packages.diff-cover</li>
    <li>python39Packages.diofant</li>
    <li>python39Packages.dragonfly</li>
    <li>python39Packages.duckdb</li>
    <li>python39Packages.duckdb-engine</li>
    <li>python39Packages.fingerprints</li>
    <li>python39Packages.flake8-import-order</li>
    <li>python39Packages.globus-sdk</li>
    <li>python39Packages.immutables</li>
    <li>python39Packages.isort</li>
    <li>python39Packages.json-schema-for-humans</li>
    <li>python39Packages.msal-extensions</li>
    <li>python39Packages.mypy</li>
    <li>python39Packages.openai</li>
    <li>python39Packages.pandas-stubs</li>
    <li>python39Packages.parsedmarc</li>
    <li>python39Packages.pixelmatch</li>
    <li>python39Packages.plugwise</li>
    <li>python39Packages.portalocker</li>
    <li>python39Packages.pylama</li>
    <li>python39Packages.pylint</li>
    <li>python39Packages.pylint-celery</li>
    <li>python39Packages.pylint-flask</li>
    <li>python39Packages.pylint-plugin-utils</li>
    <li>python39Packages.pyls-flake8</li>
    <li>python39Packages.pyls-isort</li>
    <li>python39Packages.pyls-spyder</li>
    <li>python39Packages.pylsp-mypy</li>
    <li>python39Packages.pynamodb</li>
    <li>python39Packages.pynput</li>
    <li>python39Packages.pysiaalarm</li>
    <li>python39Packages.pytest-isort</li>
    <li>python39Packages.pytest-mypy</li>
    <li>python39Packages.pytest-mypy-plugins</li>
    <li>python39Packages.pytest-pylint</li>
    <li>python39Packages.python-lsp-black</li>
    <li>python39Packages.python-lsp-server</li>
    <li>python39Packages.setuptools-lint</li>
    <li>python39Packages.spyder</li>
    <li>python39Packages.statmake</li>
    <li>python39Packages.typed-settings</li>
    <li>python39Packages.zimports</li>
    <li>qtile</li>
    <li>remarkable-mouse</li>
    <li>sqlfluff</li>
    <li>sublime-music</li>
    <li>tests.testers.nixosTest-example</li>
    <li>tests.trivial-builders.references</li>
    <li>thonny</li>
    <li>todoman</li>
    <li>topydo</li>
    <li>ulauncher</li>
    <li>zfs-replicate</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
Breaks at least `progressbar2` and `python-utils`, possibly a few others. Can you go through the list and check for fixes?

**Comment by fabianhjr** [comment]
Will work through those, thanks for the review.

**Comment by fabianhjr** [comment]
progressbar2 and python-utils fixed, going through the rest of build failures.

**Comment by fabianhjr** [comment]
python3Packages.gradient breakage seems unrelated to this merge request:

```
/build/gradient_statsd-1.0.1/dist /build/gradient_statsd-1.0.1
Processing ./gradient_statsd-1.0.1-py3-none-any.whl
Requirement already satisfied: idna>=2.8 in /nix/store/w32q8s0x2sbgxysk7bapla9a77n58l04-python3.10-idna-3.3/lib/python3.10/site-packages (from gradient-statsd==1.0.1) (3.3)
Requirement already satisfied: requests>=2.21.0 in /nix/store/szq65wdj43f5iql69kk15h6makj3g3yn-python3.10-requests-2.28.1/lib/python3.10/site-packages (from gradient-statsd==1.0.1) (2.28.1)
Requirement already satisfied: urllib3>=1.24.1 in /nix/store/x14lgddv4n4r81i1dj4y9a6ijv2kw39d-python3.10-urllib3-1.26.9/lib/python3.10/site-packages (from gradient-statsd==1.0.1) (1.26.9)
Requirement already satisfied: decorator>=4.3.2 in /nix/store/zzcbs7xgkf7nrfvpj02983g4193d69z6-python3.10-decorator-5.1.1/lib/python3.10/site-packages (from gradient-statsd==1.0.1) (5.1.1)
Requirement already satisfied: certifi>=2018.11.29 in /nix/store/i6airf1pvrqip3jg3wsg1ddfx24gg9aw-python3.10-certifi-2022.06.15/lib/python3.10/site-packages (from gradient-statsd==1.0.1) (2022.6.15)
Requirement already satisfied: datadog>=0.26.0 in /nix/store/9hzqss4gyqw7hxrd23iplcl0pgfh37fg-python3.10-datadog-0.44.0/lib/python3.10/site-packages (from gradient-statsd==1.0.1) (0.44.0)
ERROR: Could not find a version that satisfies the requirement chardet>=3.0.4 (from gradient-statsd) (from versions: none)
ERROR: No matching distribution found for chardet>=3.0.4

error: builder for '/nix/store/83c3klfp6s5s4z9m7f1v6j1yacwi6n60-python3.10-gradient_statsd-1.0.1.drv' failed with exit code 1;
```

**Comment by fabianhjr** [comment]
python3Packages.baselines breakage seems unrelated to this merge request:

```
==================================== ERRORS ====================================
____________ ERROR collecting tests/crypt/test__cryptography_rsa.py ____________
ImportError while importing test module '/build/google-auth-2.6.6/tests/crypt/test__cryptography_rsa.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/nix/store/hjwdfamsr1i4hgw41ldbj062icdyshvw-python3-3.10.5/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/crypt/test__cryptography_rsa.py:18: in <module>
    from cryptography.hazmat.primitives.asymmetric import rsa
E   ModuleNotFoundError: No module named 'cryptography'
__________________ ERROR collecting tests/crypt/test_es256.py __________________
ImportError while importing test module '/build/google-auth-2.6.6/tests/crypt/test_es256.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/nix/store/hjwdfamsr1i4hgw41ldbj062icdyshvw-python3-3.10.5/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/crypt/test_es256.py:19: in <module>
    from cryptography.hazmat.primitives.asymmetric import ec
E   ModuleNotFoundError: No module named 'cryptography'
____________ ERROR collecting tests/transport/test__mtls_helper.py _____________
ImportError while importing test module '/build/google-auth-2.6.6/tests/transport/test__mtls_helper.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/nix/store/hjwdfamsr1i4hgw41ldbj062icdyshvw-python3-3.10.5/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/transport/test__mtls_helper.py:19: in <module>
    from OpenSSL import crypto
E   ModuleNotFoundError: No module named 'OpenSSL'
______________ ERROR collecting tests/transport/test_requests.py _______________
ImportError while importing test module '/build/google-auth-2.6.6/tests/transport/test_requests.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/nix/store/hjwdfamsr1i4hgw41ldbj062icdyshvw-python3-3.10.5/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/transport/test_requests.py:22: in <module>
    import OpenSSL
E   ModuleNotFoundError: No module named 'OpenSSL'
_______________ ERROR collecting tests/transport/test_urllib3.py _______________
ImportError while importing test module '/build/google-auth-2.6.6/tests/transport/test_urllib3.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/nix/store/hjwdfamsr1i4hgw41ldbj062icdyshvw-python3-3.10.5/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/transport/test_urllib3.py:19: in <module>
    import OpenSSL
E   ModuleNotFoundError: No module named 'OpenSSL'
=========================== short test summary info ============================
ERROR tests/crypt/test__cryptography_rsa.py
ERROR tests/crypt/test_es256.py
ERROR tests/transport/test__mtls_helper.py
ERROR tests/transport/test_requests.py
ERROR tests/transport/test_urllib3.py
!!!!!!!!!!!!!!!!!!! Interrupted: 5 errors during collection !!!!!!!!!!!!!!!!!!!!
============================== 5 errors in 1.63s ===============================
error: builder for '/nix/store/5xk1r9g9b3zgrxazmkz1c3nrfn7yn6ik-python3.10-google-auth-2.6.6.drv' failed with exit code 2;
```

**Pull request merged**
