### PR TITLE
mutt: 1.14.7 -> 2.0.0

### PR DESCRIPTION
**Pull request by matthiasbeyer**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Does this update require a changelog entry?

**Comment by matthiasbeyer** [comment]
I would say so, as mutt had some breaking changes (thus the major version update).

**Comment by danieldk** [comment]
Yes, I think adding this to the release notes would be a good idea, with a link to

http://www.mutt.org/relnotes/2.0/

Could you add a separate commit to this PR that adds an item to the release notes?

**Comment by matthiasbeyer** [comment]
I could, but the release notes are still ugly XML. I can apply a patch if you have one, though.

**Comment by danieldk** [comment]
> I could, but the release notes are still ugly XML. I can apply a patch if you have one, though.

I added a commit that adds an item to the release notes. Does that look ok to you?

**Comment by matthiasbeyer** [comment]
Nice, thanks.

**Review by danieldk — APPROVED** [review]
Result of `nixpkgs-review pr 103101` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>grepm</li>
    <li>mutt (mutt-with-sidebar)</li>
  </ul>
</details>

Looks good to go then! Will merge when ofborg is also happy.

**Pull request merged**
