### PR TITLE
cmus: fix darwin

### PR DESCRIPTION
**Pull request by LnL7**
###### Motivation for this change

Fixes cmus for darwin based on the changes from #14204

###### Things done

- [x] Tested using sandboxing / without xcode
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] macOS
   - [x] No Changes
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by globin** [comment]
The travis failure looks relevant. (disclaimer I have no idea of darwin stuff)

**Comment by LnL7** [comment]
Indeed, that package didn't work before because `libcdio` was linux only.

**Comment by LnL7** [comment]
I also fixed the build to use clang, perhaps there should be a top level package with the clang based gcc binaries?

**Comment by joachifm** [comment]
@LnL7 is this ready for integration?

**Comment by LnL7** [comment]
Should be fine, unless we want a top level drv for the clang gcc wrapper.

**Pull request merged**
