### PR TITLE
svt-av1: 0.8.6 -> 0.8.7

### PR DESCRIPTION
**Pull request by arcnmx**
###### Motivation for this change

Updated and upstream moved from github to gitlab

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 128528` at aeb634d5 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/07465a0849bb1db774ca00c7685acc6b">python38Packages.rl-coach</a></li>
    <li><a href="https://gist.github.com/426efe9a5b9011771ec05daac390f1d8">python39Packages.rl-coach</a></li>
  </ul>
</details>
<details>
  <summary>4 packages skipped due to time constraints:</summary>
  <ul>
    <li>libsForQt512.kdenlive</li>
    <li>libsForQt512.soundkonverter</li>
    <li>libsForQt514.kdenlive</li>
    <li>libsForQt514.soundkonverter</li>
  </ul>
</details>
<details>
  <summary>27 packages built successfully:</summary>
  <ul>
    <li>MIDIVisualizer</li>
    <li>ffmpeg-full</li>
    <li>handbrake</li>
    <li>imagination</li>
    <li>libsForQt5.kdenlive (libsForQt515.kdenlive ,plasma5Packages.kdenlive)</li>
    <li>soundkonverter (libsForQt5.soundkonverter)</li>
    <li>liquidsoap</li>
    <li>manim</li>
    <li>olive-editor</li>
    <li>printrun</li>
    <li>python38Packages.baselines</li>
    <li>python38Packages.gym</li>
    <li>python38Packages.moderngl-window</li>
    <li>python38Packages.pydub</li>
    <li>python38Packages.pyglet</li>
    <li>python38Packages.pytmx</li>
    <li>python38Packages.roboschool</li>
    <li>python39Packages.baselines</li>
    <li>python39Packages.gym</li>
    <li>python39Packages.moderngl-window</li>
    <li>python39Packages.pydub</li>
    <li>python39Packages.pyglet</li>
    <li>python39Packages.pytmx</li>
    <li>python39Packages.roboschool</li>
    <li>restream</li>
    <li>svt-av1</li>
    <li>webcamoid</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Review by risicle — APPROVED** [review]
`nixpkgs-review` happy, macos 10.15, nixos x86_64

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]
please update the meta section.

**Comment by arcnmx** [comment]
So I think the homepage should still work, but changelog link updated, nice catch!

**Pull request merged**
