### PR TITLE
git-branchless: 0.9.0 -> 0.10.0 & fix build

### LINKED ISSUE #338971: Build failure: git-branchless
### Steps To Reproduce

1. build *git-branchless*

### Build log

https://hydra.nixos.org/search?query=git-branchless

### Additional context

No longer builds with latest Nixpkgs

### Notify maintainers

@arxanas

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix run nixpkgs#nix-info -- "-m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.6, NixOS, 24.11 (Vicuna), 24.11.20240828.71e91c4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.92.0-dev-pre20240813-f9a3bf6
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/toastal/.config/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/toastal/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/toastal/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/toastal/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/3g35mlki1l0p3xx68q6gpwpi5xavgrky-lix-2.92.0-dev-pre20240813-f9a3bf6/share`
 - nixpkgs: `/nix/store/887hpp8a2i99n9jjwcvz6qkhhhqsvzkg-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

[^1]

[^1]: Please consider [giving up MS GitHub](https://sfconservancy.org/GiveUpGitHub/) or offering a non-proprietary, non-US-corporate-controlled mirror for this free software project. I wish to delete this Microsoft account in the future, but I need more projects like this to support alternative methods to send patches & contribute.

### PR DESCRIPTION
**Pull request by bryango**
## Description of changes

- Bump 0.9.0 -> 0.10.0: https://github.com/arxanas/git-branchless/releases/tag/v0.10.0
- Fix build:
	- fix #338971
	- rework #339023 (was reverted in #340854).

- In a previous commit d5a849c (by me), the `postInstall` hook invokes the host binary `git-branchless`, which would probably fail when cross compiling. In this commit, we simply disable the hook in these cases.

- Add myself to `meta.maintainers`.

**P.S.** a log cache of the current upstream CI test failures can be found here: [git-branchless-job-logs.txt](https://github.com/user-attachments/files/17016948/git-branchless-job-logs.txt)

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by hmenke — APPROVED** [review]

**Comment by bryango** [comment]
It seems that most of the test skips in #339023 are actually necessary as they are also failing on the upstream master; see e.g. a log cache of the current upstream CI test failures: [git-branchless-job-logs.txt](https://github.com/user-attachments/files/17016948/git-branchless-job-logs.txt)

I have added some comments in `checkFlags` to explain the nature of these failures.

**Comment by bryango** [comment]
Friendly ping @nh2 @hmenke for comments and review :wave: I have been running on this for a few weeks now, nothing out of the ordinary for me (I am a lightweight user though).

**Comment by xanderio** [comment]
Result of `nixpkgs-review pr 342278` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>git-branchless</li>
  </ul>
</details>

**Review by xanderio — APPROVED** [review]

**Comment by niklaskorz** [comment]
0.10.0 was just released, so we don't need to cherry-pick fixes anymore: https://github.com/arxanas/git-branchless/releases/tag/v0.10.0

**Comment by bryango** [comment]
Bump for `0.10.0`, waiting for ofborg...

**Review by hmenke — APPROVED** [review]
It's really unfortunate that so many tests fail. Maybe it might even be better to just `doCheck = false;`

**Review by bb010g — APPROVED** [review]

**Comment by bryango** [comment]
Friendly ping @Artturin and @eclairevoyant for merging :eyes: Approved by @hmenke among others.

**Comment by eclairevoyant** [comment]
FYI I don't participate in nixpkgs PRs anymore nor am I currently a committer.

**Comment by bryango** [comment]
> FYI I don't participate in nixpkgs PRs anymore nor am I currently a committer.

I see, sorry for the noise, and thank you so much for your contributions for all these years!

**Comment by Scrumplex** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 342278`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>git-branchless</li>
  </ul>
</details>

**Review by Scrumplex — APPROVED** [review]

**Pull request merged**
