### PR TITLE
ffms: 2.23 -> 2.40

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
https://github.com/FFMS/ffms2/releases/tag/2.40

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

I did not test whether this actually works.

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 120846` at e670d0d3 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>avxsynth</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/d1be3a69666d19a241d9e9045e6f4f1f">aegisub</a></li>
  </ul>
</details>
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>ffms</li>
    <li>siril</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/libraries/ffms/default.nix:50:5:
```
   |
50 |     maintainers = with maintainers; [ ];
   |     ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement.

**Review by tadeokondrak — APPROVED** [review]
I've tested the VapourSynth plugin, it still works.

**Comment by dotlambda** [comment]
@tadeokondrak Would you like to become a maintainer of ffms?

**Comment by tadeokondrak** [comment]
> Would you like to become a maintainer of ffms?

Sure, since it has no maintainers. Feel free to add me in this PR.

**Comment by dotlambda** [comment]
> Sure, since it has no maintainers. Feel free to add me in this PR.

That's what I did. Thanks a lot!

**Pull request merged**
