### PR TITLE
 lxd: 3.13 -> 3.18

### LINKED ISSUE #69818: Every LXD container fails to start
**Describe the bug**
I'm not able to start any (freshly created) container in lxd.

**To Reproduce**
1. `virtualisation.lxd.enable = true`
2. `sudo lxd --init`
3. `lxc launch images:alpine/3.10`

**Expected behavior**
Container starts without issues.

**Additional context**
Log gathered via `lxc info --show-log enabled-sponge`
```
lxc enabled-sponge 20190928102355.329 WARN     initutils - initutils.c:setproctitle:341 - Invalid argument - Failed to set cmdline
lxc enabled-sponge 20190928102355.370 ERROR    cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1279 - File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.monitor/enabled-sponge"
lxc enabled-sponge 20190928102355.370 ERROR    cgfsng - cgroups/cgfsng.c:monitor_create_path_for_hierarchy:1300 - Failed to create cgroup "/sys/fs/cgroup/cpuset//lxc.monitor/enabled-sponge"
lxc enabled-sponge 20190928102355.370 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_monitor_create:1390 - Failed to create cgroup "/sys/fs/cgroup/cpuset//lxc.monitor/enabled-sponge"
lxc enabled-sponge 20190928102355.370 ERROR    cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1279 - File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.monitor/enabled-sponge-1"
lxc enabled-sponge 20190928102355.370 ERROR    cgfsng - cgroups/cgfsng.c:monitor_create_path_for_hierarchy:1300 - Failed to create cgroup "/sys/fs/cgroup/cpuset//lxc.monitor/enabled-sponge-1"
lxc enabled-sponge 20190928102355.370 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_monitor_create:1390 - Failed to create cgroup "/sys/fs/cgroup/cpuset//lxc.monitor/enabled-sponge-1"
lxc enabled-sponge 20190928102355.371 ERROR    cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1279 - File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.monitor/enabled-sponge-2"
lxc enabled-sponge 20190928102355.371 ERROR    cgfsng - cgroups/cgfsng.c:monitor_create_path_for_hierarchy:1300 - Failed to create cgroup "/sys/fs/cgroup/cpuset//lxc.monitor/enabled-sponge-2"
lxc enabled-sponge 20190928102355.371 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_monitor_create:1390 - Failed to create cgroup "/sys/fs/cgroup/cpuset//lxc.monitor/enabled-sponge-2"
lxc enabled-sponge 20190928102355.372 ERROR    cgfsng - cgroups/cgfsng.c:__do_cgroup_enter:1500 - No space left on device - Failed to enter cgroup "/sys/fs/cgroup/cpuset//lxc.monitor/enabled-sponge-3/cgroup.procs"
lxc enabled-sponge 20190928102355.372 ERROR    start - start.c:__lxc_start:2009 - Failed to enter monitor cgroup
lxc enabled-sponge 20190928102355.372 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:873 - Received container state "STOPPING" instead of "RUNNING"
lxc enabled-sponge 20190928102355.374 WARN     cgfsng - cgroups/cgfsng.c:cgfsng_monitor_destroy:1180 - No space left on device - Failed to move monitor 20481 to "/sys/fs/cgroup/cpuset//lxc.pivot/cgroup.procs"

lxc 20190928102355.374 WARN     commands - commands.c:lxc_cmd_rsp_recv:135 - Connection reset by peer - Failed to receive response for command "get_state"
```
Regarding the not enough space, I'm quiet sure that the report is wrong:
```
$ df -x tmpfs -x devtmpfs -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2       466G  367G   97G  80% /
/dev/sda2       466G  367G   97G  80% /nix
/dev/sda2       466G  367G   97G  80% /var
/dev/sda1       500M   31M  470M   7% /boot
/dev/sda2       466G  367G   97G  80% /home
```

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.0, NixOS, 19.09beta439.b30f86ffc6a (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09beta439.b30f86ffc6a"`
 - channels(wucke13): `"nixos-unstable-19.09pre192418.e19054ab3cd"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  lxd
```

### PR DESCRIPTION
**Pull request by wucke13**
###### Motivation for this change

Hopefully this resolves #69818
Edit:
~Which is not the case.~ But the binaries run fine :laughing: 
Edit 2: 
Running this in a nixos-vm, lxd __is__ working!

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @fpletz

### CODE REVIEW

**Review by jonringer — COMMENTED** [review]
noticed the shared libraries in libco-canonical don't have execute permissions

```
[nix-shell:/home/jon/.cache/nix-review/pr-70209/results]$ ls -lg libco-canonical/lib/
.r--r--r-- 7.9k root root 31 Dec  1969 libco.a
lrwxrwxrwx   14 root root 31 Dec  1969 libco.so -> libco.so.0.1.0
lrwxrwxrwx   14 root root 31 Dec  1969 libco.so.0 -> libco.so.0.1.0
.r--r--r--  20k root root 31 Dec  1969 libco.so.0.1.0
dr-xr-xr-x    - root root 31 Dec  1969 pkgconfig

[nix-shell:/home/jon/.cache/nix-review/pr-70209/results]$ ls -lg raft-canonical/lib/
.r-xr-xr-x  969 root root 31 Dec  1969 libraft.la
lrwxrwxrwx   16 root root 31 Dec  1969 libraft.so -> libraft.so.0.0.7
lrwxrwxrwx   16 root root 31 Dec  1969 libraft.so.0 -> libraft.so.0.0.7
.r-xr-xr-x 197k root root 31 Dec  1969 libraft.so.0.0.7
dr-xr-xr-x    - root root 31 Dec  1969 pkgconfig
```

for some closure improvements, i would add `outputs = [ "out" "dev" ];` so that the pkgconfig and headers are only used during builds. But the libraries are so small in size it probably won't make too much of a difference.

**Comment by wucke13** [comment]
@jonringer Again, excellent review! I'm baffled about the amount detail caught by your eye. I will adjust according to both of your comments in next hours.

**Comment by wucke13** [comment]
@jonringer I included your feedback regarding the `out` thing. Didn't knew that before, thanks for educating me! Regarding the (missing?) `x` of the `.so` files, I'm conflicted. A quick research left me here:
+ `.so` do not have to be executable to be used by linker/`ldd`
+ some are executable
+ `glibc`s `libc.so.6` for example is executable, for the purpose of outputting some information about itself
+ `libco.so.0.1.0` segfaults if ran on its own
+ Funnily, the `libraft.so` which is executable segfaults when ran __too__
So my conclusion here is that it would be the best to let the executability flag just as it came from the 3rd party in this case. It probably doesn't brake something and keeping close to upstream feels best.

**Comment by jonringer** [comment]
Yea, i guess I stumbled upon it becuase i was getting a warning with ldd saying that `foo.so is not executable`. But if it works in a normal use-case, then I'm 'okay with it being how it is :).

**Comment by jonringer** [comment]
Unfortunately, I don't have any prior experience with lxd, so I can't really test it well :(

**Comment by wucke13** [comment]
Well, you could do me big favor for #69818:
Spin up nixos-vm build from my fork of the nixpkgs with lxd enabled, and run these:

+ initialize lxd: ``lxd init --auto`
+ launch a container: `lxc launch images:alpine/10`

And report the result of your effort in launching the container to the issue #69818:

**Comment by wucke13** [comment]
In the meantime a new version of lxd was release, updated accordingly.

**Review by Lassulus — APPROVED** [review]
tested with  `nixos-generators` and this PR checked out as nixpkgs, created an alpine container and looked around it with `lxc exec` everything looked fine

**Comment by Lassulus** [comment]
Do you also want to maintain LXD?

**Comment by wucke13** [comment]
> Do you also want to maintain LXD?

Ok

**Pull request merged**
