### PR TITLE
steamPackages.steam-runtime: 20210527.0 -> 20210630.0

### PR DESCRIPTION
**Pull request by baracoder**
###### Motivation for this change

* "Updated scout LD_* runtime to 0.20210630.0" in [latest steam update](https://steamcommunity.com/games/593110/announcements/detail/2958285593310513192)
*  Without this, big-picture mode won't work
* Backport might be required

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 130195` at 7cae0551 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built successfully:</summary>
  <ul>
    <li>kodiPackages.steam-launcher</li>
    <li>lutris</li>
    <li>protontricks</li>
    <li>steam</li>
    <li>steam-run</li>
    <li>steam-tui</li>
    <li>steamcmd</li>
  </ul>
</details>

**Comment by ashkitten** [comment]
this fixes big picture mode for me

**Comment by uvNikita** [comment]
We should backport this to 21.05.

**Comment by baracoder** [comment]
I noticed there is a label "9. needs: port to stable" Should I add it next time?

**Comment by uvNikita** [comment]
@baracoder yeah, I guess adding it would create backport pull request automatically, but I'm not 100% sure.

**Comment by lovesegfault** [comment]
That's correct, if you add the label the bot automatically creates the backport PR

**Pull request merged**
