### PR TITLE
qt5{12,14,15}: use default stdenv on darwin

### PR DESCRIPTION
**Pull request by prusnak**
###### Motivation for this change

- as pointed out in https://github.com/NixOS/nixpkgs/issues/151874 - depending on llvmPackages_5 is probably not what we want/need and this blocks further works on bringing Qt5 to aarch64-darwin
- also mark Qt5 broken on aarch64-darwin for the time being until we address the underlying build issue

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by veprbl — APPROVED** [review]
Diff LGTM

**Comment by prusnak** [comment]
I was able to build `qt512.full` and `qt515.full` (modulo `qt515.webengine` which is broken) without any issues.

I also built gmic-qt against libsForQt512, libsForQt514 and libsForQt515 and it worked nicely.

**Comment by prusnak** [comment]
cc @NixOS/darwin-maintainers

**Comment by uri-canva** [comment]
Diff looks good to me too, but the `x86_64-darwin` build timed out, let me test it locally.

**Review by uri-canva — APPROVED** [review]
Seems good, will merge in a couple of days if no one else does, to give people a chance to look it over.

**Comment by prusnak** [comment]
Rebased on top of current master after staging-next merge.

**Comment by SuperSamus** [comment]
Is it intended for #151874 to still be open?

**Pull request merged**
