### PR TITLE
cudaPackages_12_2.cudatoolkit: 12.2.0 -> 12.2.2

### PR DESCRIPTION
**Pull request by timothyklim**
## Description of changes

https://docs.nvidia.com/cuda/archive/12.2.2/cuda-toolkit-release-notes/index.html

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Kiskae — CHANGES_REQUESTED** [review]
I believe you also need to update the redistributable manifests, but @NixOS/cuda-maintainers would know more.

**Comment by timothyklim** [comment]
> I believe you also need to update the redistributable manifests, but @NixOS/cuda-maintainers would know more.

It's already in the master branch: https://github.com/NixOS/nixpkgs/pull/275313#pullrequestreview-1788191391 https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/cuda-modules/cuda/manifests/redistrib_12.2.2.json

**Comment by SomeoneSerge** [comment]
Hi! Thanks! Just one remark about the commit message: this PR makes `cudaPackages_12_2.cudatoolkit` catch up with the rest of `cudaPackages_12_2`, which are already at 12.2.2:

```
❯ nix eval nixpkgs#cudaPackages_12_2.cudaVersion
"12.2"
❯ nix eval nixpkgs#cudaPackages_12_2.libnvjpeg.version
"12.2.2.4"
❯ nix eval nixpkgs#cudaPackages_12_2.cudatoolkit.version
"12.2.0"
```

I think it's a bit confusing, but we keep `cudaPackages.cudatoolkit` for compatibility. @timothyklim could you update the commit message to reflect the full attribute path?

**Review by Kiskae — COMMENTED** [review]
Deferring to the cuda maintainers for a review

**Comment by timothyklim** [comment]
> Hi! Thanks! Just one remark about the commit message: this PR makes `cudaPackages_12_2.cudatoolkit` catch up with the rest of `cudaPackages_12_2`, which are already at 12.2.2:
> 
> ```
> ❯ nix eval nixpkgs#cudaPackages_12_2.cudaVersion
> "12.2"
> ❯ nix eval nixpkgs#cudaPackages_12_2.libnvjpeg.version
> "12.2.2.4"
> ❯ nix eval nixpkgs#cudaPackages_12_2.cudatoolkit.version
> "12.2.0"
> ```
> 
> I think it's a bit confusing, but we keep `cudaPackages.cudatoolkit` for compatibility. @timothyklim could you update the commit message to reflect the full attribute path?

done

**Review by SomeoneSerge — APPROVED** [review]

**Comment by SomeoneSerge** [comment]
```
❯ nix build -I nixpkgs=flake:github:timothyklim/nixpkgs/master -f '<nixpkgs>' --arg config '{ allowUnfree = true; cudaSupport = true; cudaCapabilities = [ "8.6" ]; cudaEnableForwardCompat = false; }' cudaPackages_12_2.cudatoolkit --print-out-paths 
/nix/store/mnr04163r454zh0rpbpgqilcy8yngir1-cudatoolkit-12.2.2
```

Waiting just for Ofborg

**Comment by timothyklim** [comment]
Gentle ping @Kiskae

**Comment by Kiskae** [comment]
I don't have permission to merge, that's why I pinged the cuda maintainers

**Comment by SomeoneSerge** [comment]
Thank you @timothyklim!

**Pull request merged**
