### PR TITLE
nixos/udev: include upstream udev rules

### PR DESCRIPTION
**Pull request by oxalica**
This fixes triggers of some systemd upstream services, like to run systemd-vconsole-setup when the GPU driver is loaded.

It's kind of surprising that we don't include upstream udev rules by default. Some of them look pretty essential like `60-serial.rules` and `64-btrfs.rules`, which may be better included in initrd?

`99-systemd.rules` restores backlight. May be related to #178345. cc @ncfavier

Ping @dasJ who defined [the subset of rules](https://github.com/NixOS/nixpkgs/pull/171021/files#diff-a2c1abd42b837d24d5075f83285c05636ddfa42dd8312119f9c5978055d31fdfR13) included in systemd based initrd. Not sure if we should extend that list also.

All upstream rules:
```
50-udev-default.rules
60-autosuspend.rules
60-block.rules
60-cdrom_id.rules
60-drm.rules
60-evdev.rules
60-fido-id.rules
60-input-id.rules
60-persistent-alsa.rules
60-persistent-input.rules
60-persistent-storage-tape.rules
60-persistent-storage.rules
60-persistent-v4l.rules
60-sensor.rules
60-serial.rules
64-btrfs.rules
70-camera.rules
70-joystick.rules
70-memory.rules
70-mouse.rules
70-power-switch.rules
70-touchpad.rules
70-uaccess.rules
71-seat.rules
73-seat-late.rules
75-net-description.rules
75-probe_mtd.rules
78-sound-card.rules
80-drivers.rules
80-net-setup-link.rules
81-net-dhcp.rules
90-vconsole.rules
99-systemd.rules
```

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by oxalica** [comment]
:thinking: Weird.
Without this PR, `systemd-analyze cat-config udev/rules.d` still contains `90-vconsole.rules`, but my TTY font is changing back to the default after GPU driver loaded (somewhere after staging 2 with one second of black screen), and are keeping this state.
With this PR, my TTY font correctly respects `console.font` both before and after the GPU driver loading (the black screen).

**Comment by LunNova** [comment]
The seat rules (71, 73) are definitely already getting loaded by something without this PR.

Does udev search its own rules by default without needing them in extraRules?

**Comment by oxalica** [comment]
> The seat rules (71, 73) are definitely already getting loaded by something without this PR.
> 
> Does udev search its own rules by default without needing them in udevPackages?

Is there a difference between explicit and implicit including those rules? Otherwise, this PR would not fix the vconsole-setup triggering issue for me. But it does.

**Comment by LunNova** [comment]
Maybe it's impacting the ordering?

**Comment by ncfavier** [comment]
This PR does not affect https://github.com/NixOS/nixpkgs/issues/178345 in any way for me.

**Comment by oxalica** [comment]
Close now because more investigation is required.

**Comment by ncfavier** [comment]
@oxalica out of curiosity, what GPU driver are you using? I'm using `amdgpu`, and the console font is **not** preserved after the driver is loaded, with or without the upstream udev rules.

**Comment by oxalica** [comment]
> what GPU driver are you using? I'm using `amdgpu`, and the console font is **not** preserved after the driver is loaded, with or without the upstream udev rules.

I'm also using `amdgpu` for my Ryzen 7 5700G's integrated GPU. I'm not sure what's going on here.

**Comment by ncfavier** [comment]
Note that the `reload-systemd-vconsole-setup` service might be interfering with the tests since it is pulled by `multi-user.target`.

**Pull request closed without merging**
