### PR TITLE
nixos/networking-scripted: restore bridge slaves dynamically added by…

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

Another attempt to do something with disappearing slaves
History is here https://github.com/NixOS/nixpkgs/pull/26765 and https://github.com/NixOS/nixpkgs/issues/26342

The use case is not to destroy VM's network on ```nixos-rebuild switch``` on the host, when ```network-setup.service``` stops then starts, not just reloads.

```
['ssh',
 '-oControlPath=/run/user/1000/nixops-ssh-tmpqgre9163/master-socket',
 '-oLogLevel=quiet',
 '-oUserKnownHostsFile=/dev/null',
 '-oGlobalKnownHostsFile=/dev/null',
 '-oStrictHostKeyChecking=no',
 '-oCheckHostIP=no',
 '-X',
 '-t', 'root@10.8.0.1',
 '--',
 '/nix/store/dz2yl580fbs7h1qq0m1z9fpm28c5472x-nixos-system-x1-17.09.git.d9ad651/bin/switch-to-configuration switch']
updating GRUB 2 menu...
stopping the following units: network-setup.service                                                                                                                                                                                                                               
activating the configuration...
setting up /etc...                                                                                                                                                                                                                                                                
setting up tmpfiles
starting the following units: network-setup.service
```

This fix is for ```libvirt``` only, ```nixos-container``` is not covered (here is a [similar fix for containers](https://github.com/NixOS/nixpkgs/pull/22547/files#diff-0346c64733c3dc6b8b853e265bb1e4f1R229)). 

There is also https://github.com/NixOS/nixpkgs/pull/26765 which helps for both ```libvirt``` and ```nixos-container``` (and any not yet known software which enslaves interfaces dynamically), which might be a better option. I stuck to this ```libvirt```-bound solution because of ease of existing installations upgrade: it works right from the first ```nixos-rebuild switch```, while upgrading networking scripts to ones with saving-support requires an extra restart on which the slaves will be lost.

cc @globin @fpletz @kampfschlaefer @mxxz

### CODE REVIEW

**Comment by volth** [comment]
I deployed it into production few days ago.
But.
There is also concept of ```network``` in ```libvirt``` which I never used.
It might have references to the bridges and this is not covered by this code.

**Comment by fpletz** [comment]
@volth This should work just fine. Networks are basically bridges that are fully managed by libvirt. libvirt takes care of setting up the interface, starting a dnsmasq for DHCPv4, setting up NAT etc. These networks/bridges can't be the same as those managed by the NixOS configuration. I suspect things will break on system activation anyway.

**Comment by volth** [comment]
I meant those bridges might be mentioned in other places of xml

**Comment by sargon** [comment]
Hey, same problem here. 
Patchset works for me, please merge.

**Comment by volth** [comment]
up

**Pull request merged**
