### PR TITLE
nixos/containers: use machinectl poweroff

### PR DESCRIPTION
**Pull request by flokli**
Previously, we were storing the leader pid in a runtime file and
signalled SIGRTMIN+4 manually.

In systemd 219, the `machinectl poweroff` command was introduced, which
does that for us.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @arianvp

### CODE REVIEW

**Comment by flokli** [comment]
@GrahamcOfBorg build nixosTests.containers-bridge nixosTests.containers-ephemeral nixosTests.containers-extra_veth nixosTests.containers-hosts nixosTests.containers-imperative nixosTests.containers-ip nixosTests.containers-macvlans nixosTests.containers-physical_interfaces nixosTests.containers-physical_interfaces nixosTests.containers-portforward nixosTests.containers-restart_networking nixosTests.containers-tmpfs

**Comment by jonringer** [comment]
@GrahamcOfBorg test containers-bridge containers-ephemeral containers-extra_veth containers-hosts containers-ip containers-macvlans containers-physical_interfaces containers-portforward containers-restart_networking containers-tmpfs

**Review by jonringer — APPROVED** [review]
LGTM

locally passes:
```
[nix-shell:~/.cache/nix-review/pr-76719]$ nix build -f ./nixpkgs/ nixosTests.containers-bridge nixosTests.containers-ephemeral nixosTests.containers-extra_veth nixosTests.containers-hosts nixosTests.containers-imperative nixosTests.containers-ip nixosTests.containers-macvlans nixosTests.containers-physical_interfaces nixosTests.containers-physical_interfaces nixosTests.containers-portforward nixosTests.containers-restart_networking nixosTests.containers-tmpfs
[754 built, 423 copied (1181.7 MiB), 237.6 MiB DL]
```

**Comment by jonringer** [comment]
these passed locally, but failed on ofborg:
```
error: build of '/nix/store/81s1hqa1i3l53fq9ls2b1izrc699538w-vm-test-run-containers-hosts.drv', '/nix/store/hnlggxfn5v1h49p9z0i3qbry4mwmxfhd-vm-test-run-containers-macvlans.drv' failed
```

**Comment by flokli** [comment]
@GrahamcOfBorg test containers-hosts containers-macvlans

**Comment by flokli** [comment]
@GrahamcOfBorg test containers-hosts containers-macvlans

**Comment by flokli** [comment]
It now succeeded on ofborg aswell, merging.

**Comment by uvNikita** [comment]
I'm probably missing something, but why we wouldn't use the same configuration as in the [upstream service file](https://github.com/systemd/systemd/blob/b6cea5496a20773cfccb06642fd146f184b5c0d8/units/systemd-nspawn%40.service.in#L22-L23)?

```
KillMode=mixed
Type=notify
```

From my basic tests, the shutdown process seems the same.

**Comment by flokli** [comment]
TBH, I'd like to see us moving to a state where we basically just use the upstream unit, and all the setup hackery became superfluous...

**Pull request merged**
