### PR TITLE
pass-import: fix environment bugs

### LINKED ISSUE #41323: pass: extensions have wrong $PASSWORD_STORE_DIR
## Issue description

`pass` extensions like `pass-import` and `pass-audit` give the error `Error: password store not initialized` because wrapping the program causes the environment variable `PREFIX` set by the main pass script to be lost when calling the extension script.

### Steps to reproduce

```
$ pass import -p Import keepass pass.xml
 [x] Error: password store not initialized
```

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.5.0, macOS 10.13.4`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.1`
 - channels(jake): `""`
 - channels(root): `"nixpkgs-18.09pre140731.c29d2fde74d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

### PR DESCRIPTION
**Pull request by jbaum98**
###### Motivation for this change

Fixes #41323.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by orivej** [comment]
> Haven't been able to build because of the many rebuilds triggered by #41369, but working on it.

You can test your changes with `--run "export PREFIX"` instead of `--export PREFIX`. I suspect that this will not help, but even if it does #41369 should not yet be merged because it does not seem useful for other packages.

**Comment by xeji** [comment]
Rebase gone wrong, the extra commits don't belong here.

**Comment by jbaum98** [comment]
Sorry I'll fix it. I built with `--run "export PREFIX"` and it worked! I didn't know about the `--run` flag. So rebase this right without relying on that other pull request.

**Comment by jbaum98** [comment]
This only fixes one of the issues, now there is a different problem related to `PASSWORD_STORE_BIN` being set to `$0`, because it assumes that it is being invoked as `/path/to/pass import`.

**Comment by jbaum98** [comment]
Using `--argv0` doesn't help either, because `exec -a` doesn't seem to have an effect on shell scripts with a shebang.

**Comment by jbaum98** [comment]
Since I can't figure out how to set `$0` through the shebang, I'm going to use `sed` to replace it with a path to the `pass` binary. Doesn't seem like the best way but I can't figure out a better one.

**Comment by xeji** [comment]
@GrahamcOfBorg  build passExtensions.pass-import

**Pull request merged**
