### PR TITLE
sysdig: 0.31.5 -> 0.32.0

### PR DESCRIPTION
**Pull request by Mic92**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by trofi — APPROVED** [review]

**Comment by trofi** [comment]
Something pulls in very old gcc and fails the linkage against libraries that use newer gcc:

```
-- The C compiler identification is GNU 10.4.0
-- The CXX compiler identification is GNU 10.4.0
...
       > make[2]: *** [userspace/sysdig/CMakeFiles/sysdig.dir/build.make:257: userspace/sysdig/sysdig] Error 1
       > make[1]: *** [CMakeFiles/Makefile2:1235: userspace/sysdig/CMakeFiles/sysdig.dir/all] Error 2
       > /nix/store/zsvpmlddl2i5mpzm031a99xfpn410m5b-binutils-2.40/bin/ld: /nix/store/qbiz0jggsvniaznpc4yxdzi12hw9jl3a-re2-2023-03-01/lib/libre2.so.10.0.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve()@GLIBCXX_3.4.29'
       > /nix/store/zsvpmlddl2i5mpzm031a99xfpn410m5b-binutils-2.40/bin/ld: /nix/store/w1vn9rc7pd7d1dv44c31lxkxdxy3n5mx-yaml-cpp-0.7.0/lib/libyaml-cpp.so: undefined reference to `std::__throw_bad_array_new_length()@GLIBCXX_3.4.29'
       > /nix/store/zsvpmlddl2i5mpzm031a99xfpn410m5b-binutils-2.40/bin/ld: /nix/store/rvrr9wnb1s32qpqvdr7qbmg9swf79s13-tbb-2020.3/lib/libtbb.so.2: undefined reference to `std::__exception_ptr::exception_ptr::_M_release()@CXXABI_1.3.13'
       > /nix/store/zsvpmlddl2i5mpzm031a99xfpn410m5b-binutils-2.40/bin/ld: /nix/store/rvrr9wnb1s32qpqvdr7qbmg9swf79s13-tbb-2020.3/lib/libtbb.so.2: undefined reference to `std::__exception_ptr::exception_ptr::_M_addref()@CXXABI_1.3.13'
       > collect2: error: ld returned 1 exit status
       > make[2]: *** [userspace/sysdig/CMakeFiles/csysdig.dir/build.make:339: userspace/sysdig/csysdig] Error 1
       > make[1]: *** [CMakeFiles/Makefile2:1274: userspace/sysdig/CMakeFiles/csysdig.dir/all] Error 2
       > make: *** [Makefile:156: all] Error 2
       For full logs, run 'nix log /nix/store/3bz522f9pcdxz044ifzb6ffbfm8hlpc4-sysdig-0.32.0.drv'.
```

**Comment by trofi** [comment]
Result of `nixpkgs-review pr 241349` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.hardkernel_4_14.sysdig</li>
    <li>linuxPackages_hardkernel_latest.sysdig</li>
  </ul>
</details>
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>linuxPackages_4_14_hardened.sysdig (linuxKernel.packages.linux_4_14_hardened.sysdig)</li>
    <li>linuxPackages_4_19_hardened.sysdig (linuxKernel.packages.linux_4_19_hardened.sysdig)</li>
    <li>linuxPackages_5_4_hardened.sysdig (linuxKernel.packages.linux_5_4_hardened.sysdig)</li>
  </ul>
</details>
<details>
  <summary>20 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_4_14.sysdig</li>
    <li>linuxKernel.packages.linux_4_19.sysdig</li>
    <li>linuxKernel.packages.linux_5_10.sysdig</li>
    <li>linuxPackages_5_10_hardened.sysdig (linuxKernel.packages.linux_5_10_hardened.sysdig)</li>
    <li>linuxKernel.packages.linux_5_15.sysdig</li>
    <li>linuxPackages_5_15_hardened.sysdig (linuxKernel.packages.linux_5_15_hardened.sysdig)</li>
    <li>linuxKernel.packages.linux_5_4.sysdig</li>
    <li>linuxPackages.sysdig (linuxKernel.packages.linux_6_1.sysdig)</li>
    <li>linuxPackages_hardened.sysdig (linuxPackages_6_1_hardened.sysdig)</li>
    <li>linuxKernel.packages.linux_6_3.sysdig</li>
    <li>linuxPackages_6_3_hardened.sysdig (linuxKernel.packages.linux_6_3_hardened.sysdig)</li>
    <li>linuxPackages_latest.sysdig (linuxKernel.packages.linux_6_4.sysdig)</li>
    <li>linuxPackages_latest-libre.sysdig (linuxKernel.packages.linux_latest_libre.sysdig)</li>
    <li>linuxPackages-libre.sysdig (linuxKernel.packages.linux_libre.sysdig)</li>
    <li>linuxPackages_lqx.sysdig (linuxKernel.packages.linux_lqx.sysdig)</li>
    <li>linuxPackages_testing_bcachefs.sysdig (linuxKernel.packages.linux_testing_bcachefs.sysdig)</li>
    <li>linuxPackages_xanmod.sysdig (linuxKernel.packages.linux_xanmod.sysdig)</li>
    <li>linuxPackages_xanmod_latest.sysdig (linuxKernel.packages.linux_xanmod_latest.sysdig ,linuxPackages_xanmod_stable.sysdig)</li>
    <li>linuxPackages_zen.sysdig (linuxKernel.packages.linux_zen.sysdig)</li>
    <li>sysdig</li>
  </ul>
</details>

**Comment by Mic92** [comment]
> Something pulls in very old gcc and fails the linkage against libraries that use newer gcc:
> 
> ```
> -- The C compiler identification is GNU 10.4.0
> -- The CXX compiler identification is GNU 10.4.0
> ...
>        > make[2]: *** [userspace/sysdig/CMakeFiles/sysdig.dir/build.make:257: userspace/sysdig/sysdig] Error 1
>        > make[1]: *** [CMakeFiles/Makefile2:1235: userspace/sysdig/CMakeFiles/sysdig.dir/all] Error 2
>        > /nix/store/zsvpmlddl2i5mpzm031a99xfpn410m5b-binutils-2.40/bin/ld: /nix/store/qbiz0jggsvniaznpc4yxdzi12hw9jl3a-re2-2023-03-01/lib/libre2.so.10.0.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve()@GLIBCXX_3.4.29'
>        > /nix/store/zsvpmlddl2i5mpzm031a99xfpn410m5b-binutils-2.40/bin/ld: /nix/store/w1vn9rc7pd7d1dv44c31lxkxdxy3n5mx-yaml-cpp-0.7.0/lib/libyaml-cpp.so: undefined reference to `std::__throw_bad_array_new_length()@GLIBCXX_3.4.29'
>        > /nix/store/zsvpmlddl2i5mpzm031a99xfpn410m5b-binutils-2.40/bin/ld: /nix/store/rvrr9wnb1s32qpqvdr7qbmg9swf79s13-tbb-2020.3/lib/libtbb.so.2: undefined reference to `std::__exception_ptr::exception_ptr::_M_release()@CXXABI_1.3.13'
>        > /nix/store/zsvpmlddl2i5mpzm031a99xfpn410m5b-binutils-2.40/bin/ld: /nix/store/rvrr9wnb1s32qpqvdr7qbmg9swf79s13-tbb-2020.3/lib/libtbb.so.2: undefined reference to `std::__exception_ptr::exception_ptr::_M_addref()@CXXABI_1.3.13'
>        > collect2: error: ld returned 1 exit status
>        > make[2]: *** [userspace/sysdig/CMakeFiles/csysdig.dir/build.make:339: userspace/sysdig/csysdig] Error 1
>        > make[1]: *** [CMakeFiles/Makefile2:1274: userspace/sysdig/CMakeFiles/csysdig.dir/all] Error 2
>        > make: *** [Makefile:156: all] Error 2
>        For full logs, run 'nix log /nix/store/3bz522f9pcdxz044ifzb6ffbfm8hlpc4-sysdig-0.32.0.drv'.
> ```

for you interested, there seems to be something broken with the hardened kernel cc @K900 @fabianhjr

**Comment by fabianhjr** [comment]
oh no Dx

**Comment by fabianhjr** [comment]
Those kernels have been overriden to gcc10:

```
255-    linux_4_14_hardened = hardenedKernelFor kernels.linux_4_14 {
256:      stdenv = gcc10Stdenv;
257:      buildPackages = buildPackages // { stdenv = buildPackages.gcc10Stdenv; };
258-    };
259-    linux_4_19_hardened = hardenedKernelFor kernels.linux_4_19 {
260:      stdenv = gcc10Stdenv;
261:      buildPackages = buildPackages // { stdenv = buildPackages.gcc10Stdenv; };
262-    };
263-    linux_5_4_hardened = hardenedKernelFor kernels.linux_5_4 {
264:      stdenv = gcc10Stdenv;
265:      buildPackages = buildPackages // { stdenv = buildPackages.gcc10Stdenv; };
266-    };
```

**Comment by fabianhjr** [comment]
Related to ddf613299d6ddde7ec41415919f378df330e0639, 90c22150c05dfdadebb89aaafcac656cd44dee9b, and c381ab775ad99dd3b7b673961c8cdc26bcc85727

**Comment by fabianhjr** [comment]
Comment was:

> The older hardened kernels didn't compile because this doesn't seem to work with gcc11.

Will attempt to remove the override

**Pull request merged**
