### PR TITLE
workflows/check-by-name: print failed command output

### PR DESCRIPTION
**Pull request by Artturin**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by infinisil** [comment]
Oh I was surprised to not get requested as a reviewer automatically, but I figured it out :sweat_smile: https://github.com/NixOS/nixpkgs/pull/261698

**Review by infinisil — APPROVED** [review]
Looking good. Can't test this easily so let's just merge and watch it for a minute, should be fine.

**Comment by infinisil** [comment]
Although, I think if it printed anything we should've seen it already..

**Comment by infinisil** [comment]
This should be fully fixed with https://github.com/NixOS/nixpkgs/pull/261741

**Comment by infinisil** [comment]
Btw here's a workflow run where we can see the effect of this PR, but as I suspected no extra information is printed by the `git ls-remote`: https://github.com/NixOS/nixpkgs/actions/runs/6558134544/job/17811091261#step:2:17

Anyways, I merged https://github.com/NixOS/nixpkgs/pull/261741, so this should be fixed now.

**Comment by amjoseph-nixpkgs** [comment]
@Artturin where is the "escape hatch" from these tests, like you asked for in https://github.com/NixOS/nixpkgs/pull/263082#issuecomment-1776685453 ?

I'm very disturbed by the fact that, contrary to discussion, these checks have been designed so that if there is a bug in the tests you can't fix the test within the same PR that it's obstructing.  You have to file a separate PR to fix the test and **then wait for Hydra to advance the channel** before you can resume work on the obstructed PR.  The by-name checks are even foolishly using `include_str!("eval.nix")` to further ossify the whole mess.

This is absurd.

This is precisely the problem with ofborg being out-of-tree, and we're making it worse.

This is not what was agreed to.

Right now the only way to fix broken tests is to simply disable the github action.  As it stands that is precisely what I will do if I have a PR that gets blocked by malfunctioning tests.

**Comment by Artturin** [comment]
> @Artturin where is the "escape hatch" from these tests, like you asked for in [#263082 (comment)](https://github.com/NixOS/nixpkgs/pull/263082#issuecomment-1776685453) (and I added in [bde78f5](https://github.com/NixOS/nixpkgs/commit/bde78f5990697c766847c0d117b397f436ebb0e8))

The currently unfixable (or very difficult to fix) splicing issues are not the same as a fixable test 


> I'm very disturbed by the fact that, contrary to discussion, these checks have been designed so that if there is a bug in the tests you can't fix the test within the same PR that it's obstructing. You have to file a separate PR to fix the test and **then wait for Hydra to advance the channel** before you can resume work on the obstructed PR. The by-name checks are even foolishly using `include_str!("eval.nix")` to further ossify the whole mess.

Relevant issue https://github.com/NixOS/nixpkgs/issues/256788

Architecture team is available at the [architecture team room](https://matrix.to/#/#nixpkgs-architecture:nixos.org)

**Comment by Artturin** [comment]
> @Artturin where is the "escape hatch" from these tests, like you asked for in [#263082 (comment)](https://github.com/NixOS/nixpkgs/pull/263082#issuecomment-1776685453) (and I added in [bde78f5](https://github.com/NixOS/nixpkgs/commit/bde78f5990697c766847c0d117b397f436ebb0e8))

The currently unfixable (or very difficult to fix) splicing issues are not the same as a fixable test 


> I'm very disturbed by the fact that, contrary to discussion, these checks have been designed so that if there is a bug in the tests you can't fix the test within the same PR that it's obstructing. You have to file a separate PR to fix the test and **then wait for Hydra to advance the channel** before you can resume work on the obstructed PR. The by-name checks are even foolishly using `include_str!("eval.nix")` to further ossify the whole mess.

Relevant issue https://github.com/NixOS/nixpkgs/issues/256788

Architecture team is available at the [architecture team room](https://matrix.to/#/#nixpkgs-architecture:nixos.org)

**Comment by infinisil** [comment]
@amjoseph-nixpkgs I have no idea how the splicing relates to this PR here, they seem totally unrelated.

And the supposed issue with the by-name check I'm already discussing with you in https://github.com/NixOS/nixpkgs/pull/252057 (which would probably better in a separate issue), it's totally unrelated to this PR here too. And the `include_str!` problem is also unrelated, and it's already tracked in https://github.com/NixOS/nixpkgs/issues/257748.

And if you think the above issues aren't tracked appropriately, please open a new one and ping me.

**Comment by amjoseph-nixpkgs** [comment]
> I have no idea how the splicing relates to this PR here

Nor do I.  My comment was about the need for an escape hatch from malfunctioning checks.

**Comment by Artturin** [comment]
> > I have no idea how the splicing relates to this PR here
> 
> Nor do I. My comment was about the need for an escape hatch from malfunctioning checks.

The splicing check test isn't malfunctioning.

**Comment by amjoseph-nixpkgs** [comment]
> > > I have no idea how the splicing relates to this PR here
> > 
> > 
> > Nor do I. My comment was about the need for an escape hatch from malfunctioning checks.
> 
> The splicing check test isn't malfunctioning.

Alright, *malfunctioning or counterproductive* checks then.

**Pull request merged**
