### PR TITLE
fastfetch: 2.3.4 -> 2.4.0

### LINKED ISSUE #273947: Build failure: fastfetch on x86_64-darwin
### Steps To Reproduce

1. build fastfetch

### Build log

log: https://fars.ee/qvz7

```
error: builder for '/nix/store/5vanxp0vklzkq6lh1949h8d0jxz3ild4-fastfetch-2.3.4.drv' failed with exit code 2;
       last 10 log lines:
       > fatal error: too many errors emitted, stopping now [-ferror-limit=]
       > 8 errors generated.
       > make[2]: *** [CMakeFiles/libfastfetch.dir/build.make:1700: CMakeFiles/libfastfetch.dir/src/detection/brightness/brightness_apple.c.o] Error 1
       > make[2]: *** Waiting for unfinished jobs....
       > 20 errors generated.
       > make[2]: *** [CMakeFiles/libfastfetch.dir/build.make:1756: CMakeFiles/libfastfetch.dir/src/detection/cursor/cursor_apple.m.o] Error 1
       > 20 errors generated.
       > make[2]: *** [CMakeFiles/libfastfetch.dir/build.make:1672: CMakeFiles/libfastfetch.dir/src/detection/bluetooth/bluetooth_apple.m.o] Error 1
       > make[1]: *** [CMakeFiles/Makefile2:87: CMakeFiles/libfastfetch.dir/all] Error 2
       > make: *** [Makefile:156: all] Error 2
       For full logs, run 'nix log /nix/store/5vanxp0vklzkq6lh1949h8d0jxz3ild4-fastfetch-2.3.4.drv'.
```

### Additional context

related: https://github.com/NixOS/nixpkgs/pull/272289#issuecomment-1847007239

### Notify maintainers

@gerg-l @khaneliman @federicoschonborn

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
guanranwang@Plato ~> nix-shell -p nix-info --run "nix-info -m"
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
 - system: `"x86_64-darwin"`
 - host os: `Darwin 22.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/Users/guanranwang/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by khaneliman**
## Description of changes

https://github.com/fastfetch-cli/fastfetch/releases/tag/2.4.0

Also resolve https://github.com/NixOS/nixpkgs/issues/273947

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by khaneliman** [comment]
@Guanran928 this should resolve the build for you, if you want to try this PR.

**Comment by khaneliman** [comment]
Result of `nixpkgs-review pr 275938` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>fastfetch</li>
  </ul>
</details>

**Comment by khaneliman** [comment]
Result of `nixpkgs-review pr 275938` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>fastfetch</li>
  </ul>
</details>

**Comment by Guanran928** [comment]
> @Guanran928 this should resolve the build for you, if you want to try this PR.

Works for me :-)
~~not sure why its still not detecting my macOS version correctly lol~~

```
~ took 2m16s > nix build github:khaneliman/nixpkgs/fastfetch#fastfetch && ./result/bin/fastfetch --version
fastfetch 2.4.0 (x86_64)
```

**Review by Gerg-L — APPROVED** [review]
LGTM

**Pull request merged**
