### PR TITLE
grpc: 1.35.0 -> 1.36.1

### PR DESCRIPTION
**Pull request by marsam**
###### Motivation for this change

https://github.com/grpc/grpc/releases/tag/v1.36.0
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by marsam** [comment]
@GrahamcOfBorg build or-tools

**Comment by andersk** [comment]
Last I checked, OR-Tools requires Abseil built with `CMAKE_CXX_STANDARD=17`, so we may need to provide both variants.

**Comment by andersk** [comment]
Yeah, this makes `or-tools` fail with ``/nix/store/cp1sa3xxvl71cypiinw2c62i5s33chlr-binutils-2.35.1/bin/ld: /nix/store/wv2mvvxpi6ic18j93vhbqgglffw0raqh-abseil-cpp-20200923.3/lib/libabsl_status.a(status.cc.o):(.rodata+0xc0): multiple definition of `absl::lts_2020_09_23::Status::kMovedFromString'; objs/lp_data/mps_reader.o:(.rodata._ZN4absl14lts_2020_09_236Status16kMovedFromStringE[_ZN4absl14lts_2020_09_236Status16kMovedFromStringE]+0x0): first defined here``.

**Comment by marsam** [comment]
Thanks for reviewing! yes we probably need to provide two variants

@GrahamcOfBorg build or-tools

**Comment by marsam** [comment]
@andersk I dropped the changes to abseil.

IIUC we should build abseil with 

    [ "-DCMAKE_CXX_STANDARD=17" "-DBUILD_SHARED_LIBS=ON" ]

and offer an static variant for or-tools

**Pull request merged**
