### PR TITLE
otter-browser: remove

### PR DESCRIPTION
**Pull request by lheckemann**
###### Motivation for this change
I have no interest in maintaining this anymore and it has no other maintainers.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aanderse** [comment]
While I understand how in the long term distro unmaintained software is a big problem I think this might be a bit hasty. Several other people have been updating or fixing this package and we don't know that someone else wouldn't step up to maintain it if they knew you didn't want to. If the package is currently working and supported upstream can we just remove your name and look for a new maintainer?

**Comment by flokli** [comment]
Previous contributors: @aanderse, @dtzWill - would you be interested in taking over maintainership?

**Comment by lheckemann** [comment]
@aanderse sure, I didn't make this pull request with the absolute intention of removing otter from nixpkgs—more to signal that I no longer plan to maintain it, and call for anyone who might be using it to take up maintainership :) and if nobody steps up, we can remove it and then if someone misses it they can make a new PR reverting it and adding themselves as a maintainer.

**Comment by aanderse** [comment]
@lheckemann I think raising an issue + discourse thread + possibly mentioning on IRC is going to have much better chances of finding a new maintainer than creating a PR to remove the software with no mention of looking for a maintainer.

That being said... unmaintained software is bad so definitely better you create this PR than quietly ignore the package.

I'll post a thread on discourse to see if there are any takers.

**Comment by flokli** [comment]
I didn't really see somebody stepping up to maintain it. Unmaintained packages in nixpkgs are a problem, browsers even more given their exposure, which is why I'm inclined merging this.

**Comment by aanderse** [comment]
Unfortunate, but given the circumstances I agree.

**Comment by flokli** [comment]
@lheckemann added the alias.

**Pull request merged**
