### PR TITLE
rocm{5,6}: use elfutils instead of abandoned libelf

### PR DESCRIPTION
**Pull request by philiptaron**
## Description of changes

Switch from using unmaintained libelf to elfutils for the `rocmPackages_5.rocm-runtime` and `rocmPackages_6.rocm-runtime` packages.

- https://github.com/NixOS/nixpkgs/issues/271473

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mschwaig** [comment]
Result of `nixpkgs-review pr 311442` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>26 packages marked as broken and skipped:</summary>
  <ul>
    <li>rocmPackages.llvm.flang</li>
    <li>rocmPackages.llvm.flang.doc</li>
    <li>rocmPackages.llvm.flang.info</li>
    <li>rocmPackages.llvm.flang.man</li>
    <li>rocmPackages.migraphx</li>
    <li>rocmPackages.mivisionx</li>
    <li>rocmPackages.mivisionx-cpu</li>
    <li>rocmPackages.mivisionx-hip</li>
    <li>rocmPackages.rdc</li>
    <li>rocmPackages.rdc.doc</li>
    <li>rocmPackages_5.llvm.flang</li>
    <li>rocmPackages_5.llvm.flang.doc</li>
    <li>rocmPackages_5.llvm.flang.info</li>
    <li>rocmPackages_5.llvm.flang.man</li>
    <li>rocmPackages_5.rdc</li>
    <li>rocmPackages_5.rdc.doc</li>
    <li>rocmPackages_6.llvm.flang</li>
    <li>rocmPackages_6.llvm.flang.doc</li>
    <li>rocmPackages_6.llvm.flang.info</li>
    <li>rocmPackages_6.llvm.flang.man</li>
    <li>rocmPackages_6.migraphx</li>
    <li>rocmPackages_6.mivisionx</li>
    <li>rocmPackages_6.mivisionx-cpu</li>
    <li>rocmPackages_6.mivisionx-hip</li>
    <li>rocmPackages_6.rdc</li>
    <li>rocmPackages_6.rdc.doc</li>
  </ul>
</details>
<details>
  <summary>14 packages failed to build:</summary>
  <ul>
    <li>python311Packages.torchWithRocm</li>
    <li>python311Packages.torchWithRocm.cxxdev</li>
    <li>python311Packages.torchWithRocm.dev</li>
    <li>python311Packages.torchWithRocm.dist</li>
    <li>python311Packages.torchWithRocm.lib</li>
    <li>python312Packages.torchWithRocm</li>
    <li>python312Packages.torchWithRocm.cxxdev</li>
    <li>python312Packages.torchWithRocm.dev</li>
    <li>python312Packages.torchWithRocm.dist</li>
    <li>python312Packages.torchWithRocm.lib</li>
    <li>rocmPackages_5.mivisionx (rocmPackages_5.mivisionx-hip)</li>
    <li>rocmPackages_5.mivisionx-cpu</li>
    <li>rocmPackages_5.mivisionx-opencl</li>
    <li>rocmPackages_5.rocprofiler</li>
  </ul>
</details>
<details>
  <summary>89 packages built:</summary>
  <ul>
    <li>blender-hip</li>
    <li>magma (magma-hip ,magma_2_7_2)</li>
    <li>magma.test (magma-hip.test ,magma_2_7_2.test)</li>
    <li>magma_2_6_2</li>
    <li>magma_2_6_2.test</li>
    <li>opensyclWithRocm</li>
    <li>rocmPackages.clr (rocmPackages_6.clr)</li>
    <li>rocmPackages.clr.icd (rocmPackages_6.clr.icd)</li>
    <li>rocmPackages.composable_kernel (rocmPackages_6.composable_kernel)</li>
    <li>rocmPackages.hipblas (rocmPackages_6.hipblas)</li>
    <li>rocmPackages.hipcub (rocmPackages_6.hipcub)</li>
    <li>rocmPackages.hipfft (rocmPackages_6.hipfft)</li>
    <li>rocmPackages.hiprand (rocmPackages_6.hiprand)</li>
    <li>rocmPackages.hipsolver (rocmPackages_6.hipsolver)</li>
    <li>rocmPackages.hipsparse (rocmPackages_6.hipsparse)</li>
    <li>rocmPackages.llvm.mlir (rocmPackages_6.llvm.mlir)</li>
    <li>rocmPackages.llvm.openmp (rocmPackages_6.llvm.openmp)</li>
    <li>rocmPackages.llvm.openmp.doc (rocmPackages_6.llvm.openmp.doc)</li>
    <li>rocmPackages.llvm.openmp.info (rocmPackages_6.llvm.openmp.info)</li>
    <li>rocmPackages.llvm.openmp.man (rocmPackages_6.llvm.openmp.man)</li>
    <li>rocmPackages.miopen (rocmPackages.miopen-hip ,rocmPackages_6.miopen ,rocmPackages_6.miopen-hip)</li>
    <li>rocmPackages.rccl (rocmPackages_6.rccl)</li>
    <li>rocmPackages.rocalution (rocmPackages_6.rocalution)</li>
    <li>rocmPackages.rocblas (rocmPackages_6.rocblas)</li>
    <li>rocmPackages.rocdbgapi (rocmPackages_6.rocdbgapi)</li>
    <li>rocmPackages.rocdbgapi.doc (rocmPackages_6.rocdbgapi.doc)</li>
    <li>rocmPackages.rocfft (rocmPackages_6.rocfft)</li>
    <li>rocmPackages.rocm-runtime (rocmPackages_6.rocm-runtime)</li>
    <li>rocmPackages.rocminfo (rocmPackages_6.rocminfo)</li>
    <li>rocmPackages.rocmlir (rocmPackages_6.rocmlir)</li>
    <li>rocmPackages.rocmlir-rock (rocmPackages_6.rocmlir-rock)</li>
    <li>rocmPackages.rocmlir.external (rocmPackages_6.rocmlir.external)</li>
    <li>rocmPackages.rocprim (rocmPackages_6.rocprim)</li>
    <li>rocmPackages.rocprofiler (rocmPackages_6.rocprofiler)</li>
    <li>rocmPackages.rocr-debug-agent (rocmPackages_6.rocr-debug-agent)</li>
    <li>rocmPackages.rocrand (rocmPackages_6.rocrand)</li>
    <li>rocmPackages.rocsolver (rocmPackages_6.rocsolver)</li>
    <li>rocmPackages.rocsparse (rocmPackages_6.rocsparse)</li>
    <li>rocmPackages.rocthrust (rocmPackages_6.rocthrust)</li>
    <li>rocmPackages.roctracer (rocmPackages_6.roctracer)</li>
    <li>rocmPackages.rocwmma (rocmPackages_6.rocwmma)</li>
    <li>rocmPackages.rpp (rocmPackages.rpp-hip ,rocmPackages_6.rpp ,rocmPackages_6.rpp-hip)</li>
    <li>rocmPackages.rpp-cpu (rocmPackages_6.rpp-cpu)</li>
    <li>rocmPackages.rpp-opencl (rocmPackages_6.rpp-opencl)</li>
    <li>rocmPackages.tensile (rocmPackages_6.tensile)</li>
    <li>rocmPackages.tensile.dist (rocmPackages_6.tensile.dist)</li>
    <li>rocmPackages_5.clr</li>
    <li>rocmPackages_5.clr.icd</li>
    <li>rocmPackages_5.composable_kernel</li>
    <li>rocmPackages_5.hipblas</li>
    <li>rocmPackages_5.hipcub</li>
    <li>rocmPackages_5.hipfft</li>
    <li>rocmPackages_5.hiprand (rocmPackages_5.rocrand)</li>
    <li>rocmPackages_5.hipsolver</li>
    <li>rocmPackages_5.hipsparse</li>
    <li>rocmPackages_5.llvm.mlir</li>
    <li>rocmPackages_5.llvm.openmp</li>
    <li>rocmPackages_5.llvm.openmp.doc</li>
    <li>rocmPackages_5.llvm.openmp.info</li>
    <li>rocmPackages_5.llvm.openmp.man</li>
    <li>rocmPackages_5.migraphx</li>
    <li>rocmPackages_5.miopen (rocmPackages_5.miopen-hip)</li>
    <li>rocmPackages_5.miopen-opencl</li>
    <li>rocmPackages_5.miopengemm</li>
    <li>rocmPackages_5.miopengemm.doc</li>
    <li>rocmPackages_5.rccl</li>
    <li>rocmPackages_5.rocalution</li>
    <li>rocmPackages_5.rocblas</li>
    <li>rocmPackages_5.rocdbgapi</li>
    <li>rocmPackages_5.rocdbgapi.doc</li>
    <li>rocmPackages_5.rocfft</li>
    <li>rocmPackages_5.rocm-runtime</li>
    <li>rocmPackages_5.rocminfo</li>
    <li>rocmPackages_5.rocmlir</li>
    <li>rocmPackages_5.rocmlir-rock</li>
    <li>rocmPackages_5.rocmlir.external</li>
    <li>rocmPackages_5.rocprim</li>
    <li>rocmPackages_5.rocr-debug-agent</li>
    <li>rocmPackages_5.rocsolver</li>
    <li>rocmPackages_5.rocsparse</li>
    <li>rocmPackages_5.rocthrust</li>
    <li>rocmPackages_5.roctracer</li>
    <li>rocmPackages_5.rocwmma</li>
    <li>rocmPackages_5.rpp (rocmPackages_5.rpp-hip)</li>
    <li>rocmPackages_5.rpp-cpu</li>
    <li>rocmPackages_5.rpp-opencl</li>
    <li>rocmPackages_5.tensile</li>
    <li>rocmPackages_5.tensile.dist</li>
    <li>zluda</li>
  </ul>
</details>

Those failures seem to be unrelated, since hydra also fails to build those same packages right now.

**Comment by lovesegfault** [comment]
cc. @Flakebi @Madouura

**Review by Flakebi — APPROVED** [review]
Sounds good to me (I didn’t test it myself).

**Comment by lovesegfault** [comment]
@philiptaron did you test this?

**Comment by philiptaron** [comment]
@lovesegfault other than build and the check phases of the artifacts, no, as I do not have a Radeon card.

I haven't found a regression in these transformations to date -- see the linked issue for all the previous PRs in the same vein -- giving me a lot of faith that this too will work. But testing the actual product is worth it, and I'm fine delaying until such a test is done.

**Comment by lovesegfault** [comment]
I don't currently have the hardware to test it, perhaps @Madouura can help here?

**Pull request merged**
