### PR TITLE
home-assistant: 2021.1.4 -> 2021.1.5 (and more)

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

https://github.com/home-assistant/core/releases/tag/2021.1.5

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
fastapi fails thoroughly, because it relies on a feature removed from starlette in 0.14.1.

>     UJSONResponse was removed (this change was intended to be included in 0.14.0). Please see the documentation for how to implement responses using custom JSON serialization - #1074.


https://github.com/encode/starlette/releases/tag/0.14.1

**Comment by mweinelt** [comment]
I'll look into this mess tomorrow.

**Comment by delroth** [comment]
LGTM for pyatmo bump.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110653` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
3 packages marked as broken and skipped:
</summary>
<ul>
<li>python39Packages.pyatmo</li>
<li>python39Packages.pybotvac</li>
<li>python39Packages.starlette</li>
</ul>
</details>
<details>

  <summary>2 packages failed to build and are new build failures:</summary>
  <ul>
<li>python37Packages.fastapi: log <a href="https://termbin.com/svje">https://termbin.com/svje</a></li>
<li>python38Packages.fastapi: log <a href="https://termbin.com/lgxx">https://termbin.com/lgxx</a></li>
  </ul>
</details>
<details>
<summary>
12 packages built:
</summary>
<ul>
<li>datasette (python38Packages.datasette)</li>
<li>home-assistant</li>
<li>python37Packages.asgi-csrf</li>
<li>python37Packages.datasette</li>
<li>python37Packages.pyatmo</li>
<li>python37Packages.pybotvac</li>
<li>python37Packages.starlette</li>
<li>python38Packages.asgi-csrf</li>
<li>python38Packages.pyatmo</li>
<li>python38Packages.pybotvac</li>
<li>python38Packages.starlette</li>
<li>python39Packages.asgi-csrf</li>
</ul>
</details>

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 110653` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python39Packages.pyatmo</li>
    <li>python39Packages.pybotvac</li>
  </ul>
</details>
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>datasette (python38Packages.datasette)</li>
    <li>home-assistant</li>
    <li>python37Packages.asgi-csrf</li>
    <li>python37Packages.datasette</li>
    <li>python37Packages.pyatmo</li>
    <li>python37Packages.pybotvac</li>
    <li>python38Packages.asgi-csrf</li>
    <li>python38Packages.pyatmo</li>
    <li>python38Packages.pybotvac</li>
    <li>python39Packages.asgi-csrf</li>
  </ul>
</details>

**Pull request merged**
