### PR TITLE
polaris: 0.13.5 -> 0.14.0

### PR DESCRIPTION
**Pull request by pbsds**
###### Description of changes

Updates `polaris` to `0.14.0`, and `polaris-web` to `build-66`.
`polaris-web` is also migrated to use the newly introduces `buildNpmPackage`, and both have their update scripts replaced with `nix-update`. ~4k deletions is a _good day_.

~~May rely on #200475, hence draft status. It is also a bit difficult to properly test before buildNpmPackage reaches stable.~~

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by winterqt** [comment]
I'm admittedly a bit confused as to if you've tested this or not. Your PR description says that you haven't since it might depend on the fixes branch, but is there a reason that you haven't tested that to see?

Either way, the fixes branch (#200470) has been merged, this should be okay to test properly now -- I'm only aware of one issue, and if you run into it, it'll be fixed sometime in the next day or two.

> It is also a bit difficult to properly test before buildNpmPackage reaches stable.

Similarly, what did you mean by this?

**Comment by pbsds** [comment]
It is not a critique of your builder in anyway, I simply want to test it in my existing setup, i.e. not in fresh VM but on my NAS. This i usually do with an overlay, but that would not work as my NAS runs on 22.05, which is missing the npm builder. Once i upgrade to 22.11 i'll be able to test it.

**Comment by pbsds** [comment]
This force-push makes the following change:

* `polaris-web: build-65 -> build-66`

Tested on nixos 22.11 on existing setup

**Comment by pbsds** [comment]
Huh, there is a `npmDepsHash` mismatch between my local checkout and master, but master and 22.11 produces the same hash. Seems like I got bit by the cached fixed-derivation npm deps output produced by my pre-stable buildNpmPackage checkout. I updated the deps hash with a force push.

@ofborg build polaris

**Comment by pbsds** [comment]
I'm unable to reproduce the current `cargoHash` error :S

**Comment by pbsds** [comment]
Interestingly, the different deps hash was due to different vendoring on darwin. 
Sadly still fails to build on Darwin after getting a correct hash, and as i don't have a mac to test with, I'm marking this broken.

**Comment by dotlambda** [comment]
I fixed the problem with the git dependency and the build failure on Darwin for you.

**Comment by pbsds** [comment]
Thanks! I've pushed a fix for the git dep upstream, but it has yet to get tagged. If this gets merged in its current state then I'll remove the vendored lockfile come next release

**Pull request merged**
