### PR TITLE
buildDunePackage: fix doc installation

### PR DESCRIPTION
**Pull request by anmonteiro**
The default directory where dune expects docs is in `$out/doc`, but Nix installs it in `$out/share/doc`

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by anmonteiro** [comment]
- This makes it possible to depend on `(package PKG-NAME)` for packages with a `doc` section
- As a result, it allows running dune's own tests (which depend on `(package cinaps)`) inside a nix shell

**Comment by anmonteiro** [comment]
Ran `nixpkgs-review`:

```
2 packages marked as broken and skipped:
ocamlPackages.extlib-1-7-7 ocamlPackages.reason-native.qcheck-rely

905 packages built:

```

**Comment by vbgl** [comment]
@GrahamcOfBorg build ocaml-ng.ocamlPackages_4_07.result

**Review by vbgl — CHANGES_REQUESTED** [review]
This does not work for all versions of dune:

> dune: unknown option `--docdir'.

> Usage: dune install [OPTION]... [PACKAGE]...

> Try `dune install --help' or `dune --help' for more information.

**Comment by Alizter** [comment]
Changlog says `--docdir` was introduced in Dune 2.9.

**Comment by anmonteiro** [comment]
@vbgl good catch, thanks. Is a good alternative to check for `duneVersion` being 2 or 3?

**Comment by ulrikstrid** [comment]
> @vbgl good catch, thanks. Is a good alternative to check for `duneVersion` being 2 or 3?

`>= 2` should be fine right? Then we don't have to add another case for dune 4.

**Comment by anmonteiro** [comment]
Added a check for the dune version

**Review by Alizter — APPROVED** [review]

**Review by vbgl — APPROVED** [review]
Thanks.

**Pull request merged**
