### PR TITLE
Carnix: 0.8 -> 0.9

### PR DESCRIPTION
**Pull request by P-E-Meunier**
###### Motivation for this change

Carnix 0.9 gives a way to merge the `crates-io.nix` from different packages into a single package, in two different ways:

- By producing a list of packages, and a way to recover `crates-io.nix` from that list, using `carnix generate-crates-io crates-io.list`.
- By introducing a new command, `carnix merge`, to merge the contents of multiple files (given on the standard input) into a single file.

It would be very cool to have just a crates-io.list, and generate `crates-io.nix` as a derivation. However:
- Carnix (required to produce `crates-io.nix`) still needs a `crates-io.nix` to be compiled.
- `carnix generate-crates-io` needs to download all the packages in the list. Can we let Hydra do that?

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dywedir** [comment]
@GrahamcOfBorg build carnix cargo-vendor

**Comment by Mic92** [comment]
This addition sounds great!
it seems like the old cache format is no longer valid:

```console
$ carnix generate-crates-io crates-io.list
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Io(Custom { kind: InvalidData, error: StringError("stream did not contain valid UTF-8") }), State { next_error: N
one, backtrace: InternalBacktrace { backtrace: None } })', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
$ rm /home/joerg/.cargo/nix-cache
$ carnix generate-crates-io crates-io.list
Prefetching aho-corasick-0.6.8
Prefetching ansi_term-0.11.0
Prefetching argon2rs-0.2.5
Prefetching arrayvec-0.4.7
```

I have not understood yet how the merge command is supposed to work.
What is in the first argument that the program takes?
Also how would the workflow for contributors look like?
Is the the idea that contributors first generate their crates-io.nix file as usual
and then in a later commit we merge the content into the the single crates-io.nix file and recreate the now smaller per-package crrates-io.nix files?
Finally it would be nice to also have the steps documented in our rust nixpkgs documentation.

cc @andir @Ekleog

**Comment by P-E-Meunier** [comment]
The cache has changed, it no longer needs sqlite and uses plain text instead. Carnix 0.9.1 has a bug in that part actually, which was fixed by Carnix 0.9.2. I'd prefer to keep working on compiling Rust to WASM using this before submitting a new PR.

`carnix merge` takes several versions of `crates-io.nix` as input, and outputs a merger of them. These files need to have been produced with carnix >= 0.9, as the parsing is extremely basic and relies on markers placed in the file.

The idea is that contributors submit the larger single `crates-io.nix` in their PRs. When Carnix reaches 1.0, we will need to check that these commits only add to that file. There is not "per crate" `crates-io.nix`, only a `Cargo.nix`.

I wonder what the Hydra will think of that. Will it speed up release mode deployments by pre-compiling common libraries? That would be very cool and would make Nix the most convenient platform for writing web services in Rust.

**Comment by Mic92** [comment]
Could you maybe add an better error message if somebody is using the sqlite file or change the name of the cache file? I had to use strace to find out why carnix failed to update for me, other people might not find out the reason for that.

Can you make an concrete example how I have to run `carnix merge`? It does not accept multiple arguments:

```
[nix-shell:~/git/nixpkgs/pkgs/build-support/rust]$ cp crates-io.nix crates-io2.nix
[nix-shell:~/git/nixpkgs/pkgs/build-support/rust]$ carnix merge crates-io.nix crates-io2.nix
error: Found argument 'crates-io2.nix' which wasn't expected, or isn't valid in this context

USAGE:
    carnix merge [file]

For more information try --help
$ cat crates-io.nix | carnix merge
{ lib, buildRustCrate, buildRustCrateHelpers }:
with buildRustCrateHelpers;
let inherit (lib.lists) fold;
    inherit (lib.attrsets) recursiveUpdate;
in
rec {
}
```

**Review by ryantm — CHANGES_REQUESTED** [review]
Please resolve merge conflicts and address mic92s questions

**Comment by P-E-Meunier** [comment]
I just pushed #56314, which addresses @Mic92 's questions in the documentation. The error messages are not much better now, but at least the documentation is clear about them.

**Comment by ln-nl** [comment]
Hi @P-E-Meunier
I didn't see any docs addition in https://github.com/NixOS/nixpkgs/pull/56314

**Comment by P-E-Meunier** [comment]
Sorry, I probably forgot to git add it. I have updates to `buildRustCrate` to push anyway, let me open a new PR.

**Comment by ryantm** [comment]
Oops, sorry. I thought "documentation" was just referring to the command line error messages.

**Comment by P-E-Meunier** [comment]
Oops, I had completely rewritten the section about Carnix, but it seems I forgot to commit and it got wiped by a rebase. I will probably write it again one of these days, because the documentation is severely outdated, but I right now I just feel "git'ed".

**Comment by ln-nl** [comment]
:cry: 

Could you please also explain: what should the `default.nix` file look like to work with Cargo.nix _and_ contain some `meta`?

Something like this?

```nix
{ stdenv, defaultCrateOverrides, fetchFromGitHub }:

((import ./Cargo.nix).cargo_outdated {}).override {
  crateOverrides = defaultCrateOverrides // {
    cargo-outdated = attrs: rec {
      name = "pijul-${version}";
      version = "0.11.0";

      meta = with stdenv.lib; {
        description = "A distributed version control system";
        homepage = https://pijul.org;
        license = with licenses; [ gpl2Plus ];
        maintainers = [ maintainers.gal_bolle ];
        platforms = platforms.all;
      };
    };
  };
```

Thank you for your work!

**Pull request closed without merging**
