### PR TITLE
rustPlatform.bindgenHook: use the same clang/libclang as rustc

### PR DESCRIPTION
**Pull request by NickCao**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NickCao** [comment]
Result of `nixpkgs-review pr 207352` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>48 packages built:</summary>
  <ul>
    <li>adoptopenjdk-icedtea-web</li>
    <li>ashpd-demo</li>
    <li>authenticator</li>
    <li>blightmud</li>
    <li>blightmud-tts</li>
    <li>clipcat</li>
    <li>darwin.builder</li>
    <li>dmenu-rs</li>
    <li>electrs</li>
    <li>emacsPackages.evil-textobj-tree-sitter</li>
    <li>emacsPackages.evil-tree-edit</li>
    <li>emacsPackages.helm-tree-sitter</li>
    <li>emacsPackages.pygn-mode</li>
    <li>emacsPackages.tree-edit</li>
    <li>emacsPackages.tree-sitter</li>
    <li>emacsPackages.tree-sitter-ess-r</li>
    <li>emacsPackages.tree-sitter-indent</li>
    <li>emacsPackages.tree-sitter-ispell</li>
    <li>emacsPackages.tree-sitter-langs</li>
    <li>emacsPackages.tsc</li>
    <li>firefox-esr-unwrapped (firefox-esr-102-unwrapped ,firefoxPackages.firefox-esr-102)</li>
    <li>xulrunner (firefox-unwrapped)</li>
    <li>fractal-next</li>
    <li>helvum</li>
    <li>imag</li>
    <li>indradb-client</li>
    <li>indradb-server</li>
    <li>librewolf-unwrapped</li>
    <li>lighthouse</li>
    <li>matrix-conduit</li>
    <li>nearcore</li>
    <li>neovide</li>
    <li>nix-du</li>
    <li>openpgp-card-tools</li>
    <li>polkadot</li>
    <li>proxmox-backup-client</li>
    <li>pw-viz</li>
    <li>qdrant</li>
    <li>slimerjs</li>
    <li>snarkos</li>
    <li>solana-validator</li>
    <li>stratisd</li>
    <li>teos</li>
    <li>teos-watchtower-plugin</li>
    <li>thunderbird-unwrapped (thunderbirdPackages.thunderbird ,thunderbirdPackages.thunderbird-102)</li>
    <li>wasmer</li>
    <li>wluma</li>
    <li>zpool-auto-expand-partitions</li>
  </ul>
</details>

**Comment by symphorien** [comment]
what does this fix?

**Comment by NickCao** [comment]
This reduces the build time closure of rust packages using bindgenHook from two llvms to a single llvm.

**Review by symphorien — APPROVED** [review]

**Comment by zowoq** [comment]
@ofborg eval

**Comment by winterqt** [comment]
> This reduces the build time closure of rust packages using bindgenHook from two llvms to a single llvm.

(In the future, it'd probably be a good idea to mention this in at least the commit message/PR description, to improve understanding for both reviewers and people looking at the change even after it's merged :)

**Comment by zhaofengli** [comment]
This broke [nix-du](https://hydra.nixos.org/build/204554312) and [Attic](https://github.com/zhaofengli/attic) on Darwin because it introduces mismatched libcxx versions, though the blame lies elsewhere in the chain.

With the PR, here is the generated `bindgenHook` on `aarch64-darwin`:

```bash
populateBindgenEnv () {
    export LIBCLANG_PATH=/nix/store/g3gmlnvvmrqiir447i5qjpvcdx5gqy5z-clang-14.0.6-lib/lib
    BINDGEN_EXTRA_CLANG_ARGS="$(< /nix/store/3gqvvrx5plnb3cd9wf587s2za85yggv1-clang-wrapper-14.0.6/nix-support/cc-cflags) $(< /nix/store/3gqvvrx5plnb3cd9wf587s2za85yggv1-clang-wrapper-14.0.6/nix-support/libc-cflags) $(< /nix/store/3gqvvrx5plnb3cd9wf587s2za85yggv1-clang-wrapper-14.0.6/nix-support/libcxx-cxxflags) $NIX_CFLAGS_COMPILE"
    export BINDGEN_EXTRA_CLANG_ARGS
}
```

Let's take a look at `libcxx-cxxflags` first:

```
-isystem /nix/store/5qwz665n6dgr0id7lgrmyqmqkkm6yg1l-libcxx-14.0.6-dev/include/c++/v1
```

Nothing out of the ordinary here, with `libcxx-14.0.6` selected as intended.

However, overriding `libcxx` isn't that easy. Using the default `stdenv` with Clang 11, `-isystem /nix/store/5sby1xhsk6dzi83lsfrxp3w2hz32r3j7-libcxx-11.1.0-dev/include/c++/v1` is forcibly injected in `cc-wrapper`. Other `-isystem` flags against `libcxx-11.1.0` are added straight into `NIX_CFLAGS_COMPILE` [here](https://github.com/NixOS/nixpkgs/blob/d3794666319080b160c3909892774423316ea98c/pkgs/build-support/cc-wrapper/setup-hook.sh#L63-L78) in the setup hook :cursing_face: 

As you would expect, things won't work that well when the headers are mixed. Even for a trivial program, everything breaks apart:

```cpp
# sadness.cpp
#include <cstdlib>
int main() {}
```

```console
[nix-shell:~/Git/attic]$ which clang++
/nix/store/bwscr98440mhhlg556fqhp5ll2fxnfic-clang-wrapper-11.1.0/bin/clang++

[nix-shell:~/Git/attic]$ clang++ --version
clang version 11.1.0
Target: aarch64-apple-darwin
Thread model: posix
InstalledDir: /nix/store/ssfpjhrysqf6ywz5sqi8gpz28zc23kiy-clang-11.1.0/bin

[nix-shell:~/Git/attic]$ clang++ $BINDGEN_EXTRA_CLANG_ARGS sadness.cpp 
In file included from sadness.cpp:2:
In file included from /nix/store/5qwz665n6dgr0id7lgrmyqmqkkm6yg1l-libcxx-14.0.6-dev/include/c++/v1/cstdlib:85:
/nix/store/5qwz665n6dgr0id7lgrmyqmqkkm6yg1l-libcxx-14.0.6-dev/include/c++/v1/stdlib.h:148:34: error: unknown type name 'ldiv_t'
inline _LIBCPP_INLINE_VISIBILITY ldiv_t div(long __x, long __y) _NOEXCEPT {
                                 ^
/nix/store/5qwz665n6dgr0id7lgrmyqmqkkm6yg1l-libcxx-14.0.6-dev/include/c++/v1/stdlib.h:149:12: error: no member named 'ldiv' in the global namespace
  return ::ldiv(__x, __y);
         ~~^
/nix/store/5qwz665n6dgr0id7lgrmyqmqkkm6yg1l-libcxx-14.0.6-dev/include/c++/v1/stdlib.h:152:34: error: unknown type name 'lldiv_t'
inline _LIBCPP_INLINE_VISIBILITY lldiv_t div(long long __x,
                                 ^
/nix/store/5qwz665n6dgr0id7lgrmyqmqkkm6yg1l-libcxx-14.0.6-dev/include/c++/v1/stdlib.h:154:12: error: no member named 'lldiv' in the global namespace
  return ::lldiv(__x, __y);
         ~~^
[snip]
```

I'm not sure how to best address this, and the whole thing looks like a house of cards. We _could_ make `rustPlatform.buildRustPackage` use the rustc stdenv by default, but still dev shells on the default stdenv remain broken without manual overrides. From a practical standpoint, I think we should revert this PR while we look for a better approach.

**Comment by winterqt** [comment]
I agree that reverting it is likely the best route for now, at least to avoid breakage until the next staging cycle.

cc @NixOS/rust

**Comment by lopsided98** [comment]
This also causes build failures when cross-compiling to armv6l (and probably others):
```
Running rustc --crate-name build_script_build build.rs --crate-type bin -C opt-level=3 -C codegen-units=1 --edition 2021 --cfg feature="default" --out-dir target/build/r2r_rcl --emit=dep-info,link -L dependency=target/buildDeps --extern bindgen=/nix/store/iq3q6cgzx4blrd7icjl1smhhybv5gjw7-rust_bindgen-0.63.0-lib/lib/libbindgen-e82a3757df.rlib --extern r2r_common=/nix/store/mq61wjl2ckmikc21s5mxyycvn6bgqnwl-rust_r2r_common-0.3.4-lib/lib/libr2r_common-51083e258c.rlib --cap-lints allow --color always
Generate bindings file '/build/r2r_rcl-0.3.4/target/build/r2r_rcl.out/287eb9d48069f6c0c366f5ed178c6dab3fd779e321319a3c1c1b1173cb01720f/rcl_bindings.rs'
/nix/store/nasgvbblxi25r6y1s82il4m0m4ghib68-glibc-2.35-224-dev/include/gnu/stubs.h:7:11: fatal error: 'gnu/stubs-32.h' file not found
thread 'main' panicked at 'Unable to generate bindings: ClangDiagnostic("/nix/store/nasgvbblxi25r6y1s82il4m0m4ghib68-glibc-2.35-224-dev/include/gnu/stubs.h:7:11: fatal error: 'gnu/stubs-32.h' file not found\n")', build.rs:101:10
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: build_script_build::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

This is a splicing problem and can be fixed by adding `rustc` to the `bindgenHook` `callPackage` arguments rather than the top-level arguments.

**Pull request merged**
