### PR TITLE
[20.03] steam: fix more of generated runtime dependencies

### PR DESCRIPTION
**Pull request by prusnak**
###### Motivation for this change

PR #86619 did not contain all the necessary changes

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by prusnak** [comment]
Fixes https://github.com/NixOS/nixpkgs/issues/86749

**Comment by flokli** [comment]
Was this something missing from the cherry-pick in https://github.com/NixOS/nixpkgs/pull/86619, or is this something that should target master first?

**Comment by prusnak** [comment]
@flokli I backported only a single-commit, later I noticed the change needed was included in other commits too. This chang is already in master. I just backported more stuff from master.

**Comment by flokli** [comment]
Okay, then please cherry-pick again with `-x` so people can find the corresponding commit in master. Also see https://nixos.org/nixpkgs/manual/#submitting-changes-stable-release-branches.

**Comment by prusnak** [comment]
@flokli I reworked the PR to include only cherry-picked commits from the master. Thanks!

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 86636` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
<br>- kodiPlugins.steam-launcher
<br>- linux-steam-integration
<br>- lutris
<br>- steam
<br>- steam-run
<br>- steam-run-native
<br>- steamcmd
</details>

**Review by mweinelt — APPROVED** [review]

**Pull request merged**
