### PR TITLE
meilisearch: 0.9.0 -> 0.21.1

### PR DESCRIPTION
**Pull request by happysalada**
###### Motivation for this change

This wasn't a "simple" update.
see https://github.com/meilisearch/MeiliSearch/issues/1273 for more context
@michcioperz you might be interested in this.

upon building I had this weird warning 
```
warning: vergen: could not find repository from '/private/tmp/nix-build-meilisearch-0.21.1.drv-0/source/meilisearch-http'; class=Repository (6); code=NotFound (-3)
```
My internet connection is not great at the moment, so I'm wondering if there wasn't a connection failure during the vendoring of dependencies.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [X] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by michcioperz** [comment]
This patch seems to be larger than what I've originally done. Did you run `cargo update`? Is it the packaging policy to do this? It bumps a number of packages.

**Comment by happysalada** [comment]
yes I did run `cargo update` I wasn't sure how to exactly generate the lockfile.
Happy to do it a different way.

**Comment by michcioperz** [comment]
It seems that any command that needs the dependencies to be fetched is enough to apply the lockfile change, for example `cargo check` or `cargo build`. I just tried with `cargo check` and the lockfile was rewritten

**Comment by happysalada** [comment]
I just pushed a different patch that does not update the dependencies.
That patch contains a change to the cargo resolver, since one of the workspace dependency (meilisearch-http) contains a default feature (mini-dashboard) that tries to make a request at compile time.
Here are the reference for the change https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
https://doc.rust-lang.org/cargo/reference/features.html#resolver-version-2-command-line-flags

**Comment by happysalada** [comment]
After reverting the update to the dependencies, this is the error on the ci
```
error: the lock file /build/source/Cargo.lock needs to be updated but --frozen was passed to prevent this
If you want to try to generate the lock file without accessing the network, use the --offline flag.
```

I'm not sure what this is due to.
I'm going to try to update the dependencies and see if that fixes the failure.

**Comment by happysalada** [comment]
Even after the update, the error persists. It must not be due to dependencies.

**Comment by happysalada** [comment]
I think I realise the mistake. The cargo lock was generated with rust 1.54, but nixpkgs is still on 1.53

**Comment by happysalada** [comment]
Targeting staging with 1.54 doesn't change anything.

**Comment by happysalada** [comment]
@kolloch thank you for crate2nix ! It worked wonders !
I couldn't find how to override the name so that it doesn't say `rust_meilisearch-http`. What if I want it to say just `meilisearch`. Not a big deal, feel free to ignore if you are busy.

**Comment by kolloch** [comment]
@happysalada: Heyo! Thanks for the nice words!

I think that the iconv issue is probably something very general, e.g. every build step would need this dependency and `buildRustCrate` should be changed accordingly.

With the naming issue: A quick workaround would be to wrap the derivation. I don't think that the underlying `buildRustCrate` supports renaming but I don't remember without digging into the code.

**Comment by happysalada** [comment]
@kolloch changing the buildRustCrate itself is a good idea, I was on the fence, since it's not all the crates that need this, but a lot of them.

Regarding the naming, you're right, wrapping it in another derivation should be an easy solution.

Thanks a lot for having taken a look at this!

**Comment by happysalada** [comment]
I've added a global buildInputs into buildRustCrate for libiconv
I've also added a small dummy mkDerivation to change the meilisearch name.

**Comment by humancalico** [comment]
Result of `nixpkgs-review pr 136353` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>meilisearch</li>
  </ul>
</details>

**Comment by Br1ght0ne** [comment]
Thank you everyone involved with this PR (and of course, @happysalada)! I sadly don't have much time for Nixpkgs maintenance these days, but seeing packages I added back in the day still being updated pleases me to no end. Please excuse my ramblings 😅

**Comment by happysalada** [comment]
@Br1ght0ne thanks for adding them in the first place! I also saw the PR you have around adding a module, that will come in very useful later when I add the module for it. Your work is very appreciated!

**Comment by happysalada** [comment]
Without this fix (adding the libiconv to the global overrides, crate2nix is really hard to use on darwin.
I'm going to go ahead and merge this, however I am available to do address any criticism in follow up PRs.
Feel free to comment here if you don't think anything is satisfactory.

**Pull request merged**
