### PR TITLE
Add lib.kernel

### PR DESCRIPTION
**Pull request by teto**
###### Motivation for this change
I would like to improve the kernel configuration system, https://github.com/NixOS/nixpkgs/pull/69013 looks blocked so I extracted what I believed is less controversial here.
I would like afterwards to get rid  of the string format
```
extraConfig=''
OPENVSWITCH ?y
''
```
in favor of the more powerful `structuredExtraConfig` that is not documented (and thus not used) because it is presently too hard to use:
- you either have to import lib/kernel.nix yourself
- or understand or how the `kernelItem` submodule

Merging this will help move forward with https://github.com/NixOS/nixpkgs/issues/69014

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by edolstra** [comment]
I don't think package-specific functions should be in `lib`. `lib` should be generic.

**Comment by teto** [comment]
IMO, the kernel configuration is not a package-specific operation (rather platform/linux specific). There is already a library to configure the kernel that is used across nixpkgs:
`system.requiredKernelConfig = with config.lib.kernelConfig; [`
except it doesn't do anything sensible (the checks are just for show since we don't check the resultiung kenel config anyway).
My approach just moves the library from `config.lib` to `lib` with the goal of being more powerful:
- really check the kernel requirements
- allow packages to specify dependencies withotu the need to configure modules (some packages simply can't run without some kernel configuration, no need to add a module for that).

I deal with many types of kernels: out-of-tree kernels, computer-specific configurations, different versions as well as different testing setups (openvswitch/mininet/nixops-libvirtd with virtio  reuquirements), builtin modules in order not to have to build an initramfs.

This is my single biggest complaint about nixos, it's all about reproducibility/dependency management, yet when it comes to the kernel we are not allowed to specify/check dependencies. It doesn't have to be like that. It's reasonibly easy to implement and can be opt-in if there are concerns.

**Comment by teto** [comment]
for instance one can try to build a kernel with a configuration supposed to be checked by nixpkgs (module support is mandatory):
```
  kernel0 = (pkgs.linux_latest.override {
    structuredExtraConfig = { MODULES.tristate = "n"; };
  });

  kernel1 = (pkgs.linux_latest.override {
    extraConfig = ''
      MODULES n
    '';
  });
```
yet none of it is checked by nixpkgs, it just fails building. But for an option that doesn't break the build, it could easily go unnoticed. 

There are multiple issues that show that kernel configuration checks could be useful
- https://github.com/NixOS/nixpkgs/pull/6296
- https://github.com/NixOS/nixpkgs/issues/56102
- https://github.com/NixOS/nixpkgs/issues/3982
- and several others for containers/virtualization etc.

**Comment by teto** [comment]
cc @dtzWill @Ericson2314 @worldofpeace

**Comment by Infinisil** [comment]
Looking good! Since this has been unnoticed for a while, is this still fresh or does it need adjustments before merging?

**Comment by teto** [comment]
it's up to date ty !

**Pull request merged**
