### PR TITLE
bazel: 0.11.1 -> 0.12.0

### PR DESCRIPTION
**Pull request by benbarclay**
###### Motivation for this change
Need an updated version for a project that I'm contributing to.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

I've tested this locally in the build process for a project I'm working on, and it seems to work okay.

### CODE REVIEW

**Comment by Mic92** [comment]
cc @rbvermaa

**Comment by zimbatm** [comment]
@GrahamcOfBorg build bazel

**Comment by zimbatm** [comment]
ping @philandstuff

**Comment by philandstuff** [comment]
I don't think I'm really qualified to maintain this package any more. It's
undergone significant changes since I put myself forward, and I haven't
kept up with it. If anyone else wants to take it over, I'd welcome that.

**Comment by zimbatm** [comment]
cc @mboes ?

**Comment by mboes** [comment]
Would be happy to do so. Could we merge the current patch as-is and I'll add myself as maintainer in a separate PR?

**Comment by philandstuff** [comment]
@mboes not sure what you mean, as this PR is already merged. But I'm happy for you to raise a PR replacing me as maintainer.  Thank you!

**Comment by mboes** [comment]
@philandstuff oh hadn't noticed that @zimbatm merged right before pinging you. Will submit new PR shortly (taking the opportunity to switch to 0.13, which has since come out).

**Comment by philandstuff** [comment]
@mboes there's already a PR for that upgrade: #40205

**Pull request merged**
