### PR TITLE
incus: 6.4.0 -> 6.5.0

### PR DESCRIPTION
**Pull request by bbigras**
## Description of changes

https://github.com/lxc/incus/releases/tag/v6.5.0

## Things done

`nix-build -A incus.passthru.tests` seems to fail on my side. I'll test with 6.4.0.

```
machine # Error: Failed setting up device via monitor: Failed adding block device for disk device "root": Failed adding block device: Failed to find file descriptor with matching flags=0x4002
machine # Try `incus info --show-log instance1` for more info
```

EDIT: it also fails with 6.4.0 on my side.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by adamcstephens** [comment]
6.5 appears to be broken with qemu 9.1. There are a couple merged fixes, which I've applied locally to test, but now it's failing on kvm detection. stgraber rolled the zabbly packages back to qemu 9.0.x, which isn't a good sign.

**Comment by adamcstephens** [comment]
tests ran on x86_64

/nix/store/vsd0wj2sx856s901byls458nxyb82rws-vm-test-run-container-legacy-init
/nix/store/bsbnphsq4gf82fd8ka1zky7q0a3mj6y4-vm-test-run-container-systemd-init
/nix/store/f4j3f27yzwh9mbxfhh9s1iyvy1p8ngar-vm-test-run-incusd-options
/nix/store/8lh93r7rjb5nv90jy66g37p47a0nbkzs-vm-test-run-lxd-to-incus
/nix/store/x3flppy8qwjplx0jdjqwimzwznc99w19-vm-test-run-incus-openvswitch
/nix/store/mhd1g73h4nkqqq93pg7ana5q336vap0v-vm-test-run-incus-socket-activated
/nix/store/vgzxll2kfq9i7jvrjhpka015aivvpi2s-vm-test-run-incus-storage
/nix/store/pnp2y4ci7r0iylrdvnqyg9yxhpv57vlg-vm-test-run-incus-ui
/nix/store/lsynqk6fs1366s877hiv83iy3700d906-vm-test-run-incus-virtual-machine

**Comment by bbigras** [comment]
Thanks! 

Nice catch. How did you know about the problem with qemu?

**Comment by adamcstephens** [comment]
Found the error here https://discuss.linuxcontainers.org/t/incus-6-5-incus-vm-not-starting-in-cluster/21538/8

Then I reviewed the more recent PRs and found a couple more relevant commits.

**Pull request merged**
