### PR TITLE
mumble: 1.4.287 -> 1.5.517

### PR DESCRIPTION
**Pull request by K900**
This is technically an RC release, but it contains all the fixes we've been vendoring and then some. Also, 1.4 doesn't build on staging-next anymore. This removes gRPC support, because upstream also removed it.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cafkafk** [comment]
Result of `nixpkgs-review pr 249762` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>ioquake3</li>
    <li>mumble</li>
    <li>murmur</li>
    <li>quake3demo</li>
  </ul>
</details>

**Review by felixsinger — CHANGES_REQUESTED** [review]
A release candidate is not a release. It's a... candidate. 1.5.517 has many issues and shouldn't be used.

Why does the current version not build on staging-next anymore?

**Comment by K900** [comment]
There seem to be multiple issues with latest Protobuf and gRPC versions at the very least. I guess we can try disabling gRPC and keeping the old version...

**Comment by K900** [comment]
So yeah, disabling gRPC _and_ downgrading Protobuf works. I guess we can try doing that, unless someone is willing to patch the current version of Mumble to build with the new gRPC...

**Comment by felixsinger** [comment]
> There seem to be multiple issues with latest Protobuf and gRPC versions at the very least. I guess we can try disabling gRPC and keeping the old version...

Since Mumble does not support gRPC anymore, let's just disable it.

**Pull request closed without merging**
