### PR TITLE
doc: doCheck: add the special case of 'buildPython*'

### PR DESCRIPTION
**Pull request by Anton-Latukha**
###### Motivation for this change

By default `doCheck = false`, `buildPython*` has `doCheck = true` - it is a special case that should be mentioned in `doCheck` section.

Forming paragraph for special cases. Rephrased cross compile case.

This build is fresh after the fixes to the changes of the NixPkgs Manual build:
1. Changes to the NixPkgs Manual build process: https://github.com/NixOS/nixpkgs/pull/53055
2. Issue about Manual build being broken: https://github.com/NixOS/nixpkgs/issues/55014
3. Recently merged fix: https://github.com/NixOS/nixpkgs/pull/55040

###### Things done

- Built on platform(s)
   - [x] NixOS
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by FRidh — CHANGES_REQUESTED** [review]
I don't think it should be mentioned in the `stdenv` part. `buildPython*` is just a function that calls `stdenv` but with potentially different attribute values. We do that in many places. I'm of the opinion that `Take a note for special cases` is sufficient. Details regarding `buildPython*` can be found in its own section.

**Comment by Anton-Latukha** [comment]
@FRidh For deep understanding this is the right harder approach, but this 'look yourself for special cases' approach makes documentation way harder and sometimes not useful for users and casual contributor.

AFAIK this `doCheck` Python special case and cross-compilation special case are the only two major special cases. Maybe then since cross-compilation has its own `Chapter 5. Cross-compilation`, it should be removed from `stdenv`? As additional point - anyway, as I look - cross-comp text touched in this PR is not true (https://nixos.org/nixpkgs/manual/#sec-cross-cookbook) cross-comp can run rests if configured right.

I can send PR with this discussed changes.

**Comment by mmahut** [comment]
Are there any updates on this pull request, please?

**Comment by Anton-Latukha** [comment]
The PR resulted in a dead tie.

My point was that when you troubleshoot and refer to documentation - there is nothing mentioned in there `doCheck`, but there is a special case for `doCheck` that is hidden in `buildPython*` documentation. So I wanted to cross-mention the special case.

The maintainer point is that it is a `buildPython*` question, so documentation stayed in place.

**Pull request closed without merging**
