### PR TITLE
attempt to fix redpanda-server (WIP)

### PR DESCRIPTION
**Pull request by Radvendii**
## Description of changes

`redpanda-server` has been broken for a while (see #253529 #253549 https://github.com/NixOS/nixpkgs/pull/248256#issuecomment-1672480109)

I'm attempting to fix all the linker errors. This is WIP.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by happysalada** [comment]
The creator of redpanda once commented on a nixpkgs PR, is there no way we can propose some of these patches upstream ?

**Comment by layus** [comment]
@happysalada Yes, we have opened a nix channel on redpanda slack, so they seem to care about nix. See also https://github.com/fornybar/redpanda.nix for the open source work funded by Eviny Fornybar.

**Comment by happysalada** [comment]
Thank you for the PR!
so far this looks good, feel free to ping me when you're done with it.

**Comment by domenkozar** [comment]
Any progress on this?

**Comment by layus** [comment]
Everything is in [fornybar/redpanda.nix](https://github.com/fornybar/redpanda.nix). AutoPatchelf-ing the binary release seems the more robust way forward. Building from sources is a bit tricky. You either need a lot of patches to build with libstdc++ or a lot of overrides to get the dependencies to build with libc++. A complete libc++ package set is not an option. It breaks the build way before you get to redpanda.

As for progress here, I cannot replay in stead of @Radvendii, but our funding for working on redpanda has ended, so getting this difficult PR finished (knowing that the next release will break it) is not a big priority.

**Comment by SuperSandro2000** [comment]
I think this PR is pretty stale and I am going to close it.

**Pull request closed without merging**
