### PR TITLE
sumneko-lua-language-server: 2.3.6 -> 2.4.1

### PR DESCRIPTION
**Pull request by michaeladler**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by michaeladler** [comment]
Yeah, I saw that, too. However, looking at the changelog (and considering previous major releases of this project) I'm a bit hesitant to upgrade to 2.4 yet. 2.3.6 was acting weird (CPU usage) and when I saw that this issue could be fixed in 2.3.7, I was happy to upgrade (and the issue seems to be fixed).

**Comment by figsoda** [comment]
I tried out 2.4.1 with neovim on nixos, works fine so far

**Comment by figsoda** [comment]
I tried out 2.4.1 with neovim on nixos, worked fine so far

**Comment by michaeladler** [comment]
Ok, I'll give it a try and update this MR then

**Review by figsoda — APPROVED** [review]

**Pull request merged**
