### PR TITLE
Python: introduce NIX_PYTHONEXECUTABLE in order to set sys.executable

### PR DESCRIPTION
**Pull request by FRidh**
This is needed in case of `python.buildEnv` to make sure sys.executable
does not point to the unwrapped executable.

###### Motivation for this change

Fixes issues mentioned in https://github.com/NixOS/nixpkgs/commit/ec7f569211091282410050e89e68832d4fe60528

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
Actually thinking of sending this straight to `staging-next`.

**Comment by vcunat** [comment]
Probably, as nixos-unstable is blocked on this.  I know basically nothing around python paths, so I can't well review.

**Comment by timokau** [comment]
Seems to fix the sage test issues, at least when running the previously failing tests in isolation.

**Comment by vcunat** [comment]
Sage succeeded on Hydra.

**Pull request merged**
