### PR TITLE
cc-wrapper: Fix for cross-compiling

### LINKED ISSUE #5949: Cross compilation regression due to CC and CXX being set
It seems that commit 28b6fb61e651a3e2cca57d087781e7ba6ab45e7c broke cross compilation for the majority of packages, by setting CC and CXX to native compilers. In particular I'm getting an error in bash. It doesn't matter what the error is but it is clear that it's not using the right compiler from the configure output:

```
configure flags: --disable-static --prefix=/nix/store/jqpxcv13araqrsv54rwsq2qxg763qlfy-bash-4.3-p30-armv6l-unknown-linux-gnueabi --disable-readline bash_cv_job_control_missing=nomissing bash_cv_sys_named_pipes=nomissing --build=x86_64-linux --host=armv6l-unknown-linux-gnueabi 
configure: WARNING: unrecognized options: --disable-static
checking build system type... x86_64-pc-linux-gnu
checking host system type... armv6l-unknown-linux-gnueabi

Beginning configuration for bash-4.3-release for armv6l-unknown-linux-gnueabi

checking for armv6l-unknown-linux-gnueabi-gcc... cc
checking whether the C compiler works... yes
```

The problematic change is in `pkgs/build-support/gcc-wrapper/setup-hook.sh` where CC and CXX environment variables are assigned.

Note: there are other issues currently in nixpgks that are preventing actually testing this one.

### PR DESCRIPTION
**Pull request by shlevy**
Fixes #5949

Suggested by @ambrop72

### CODE REVIEW

**Comment by wmertens** [comment]
Isn't it weird to have these two scripts depend on each other? Wouldn't it be better to make sure the cross script runs later and moves CC to BUILD_CC etc? Or would that be more error people?

**Comment by shlevy** [comment]
How do they depend on each other?

**Comment by ambrop72** [comment]
I think it's fine to do the conditional setting as is. They don't depend on each other (note that crossConfig is set by the derivation wrapper). If we did the set-and-override, *then* there would be a dependency and assumption of order :)

**Comment by wmertens** [comment]
Ok then... The dependency is that each implements a part of cross compile
setup but indeed changing it would be moving the dependency elsewhere. +1

**Pull request merged**
