### PR TITLE
genact: 1.0.2 -> 1.1.1

### PR DESCRIPTION
**Pull request by figsoda**
###### Description of changes

https://github.com/svenstaro/genact/compare/v1.0.2...v1.1.1
[changelog](https://github.com/svenstaro/genact/blob/v1.1.1/CHANGELOG.md)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by figsoda** [comment]
@ofborg eval

Not sure if ofborg will meet the same problem but I got a hash mismatch on darwin: https://github.com/figsoda/nixpkgs-test/actions/runs/3046177342/jobs/4908660871

**Comment by toonn** [comment]
I think I've found the cause of the hash mismatch:

```diff
toonn@yorp ~> diff -u (tar -tf /nix/store/kfzjagwpr7rw683jlci8fxnmjyjlrj55-genact-1.1.1-vendor.tar.gz | psub) (tar -tf genact-mac.tar.gz | psub)
--- /tmp/.psub.XwdV5ghdbN       2022-09-13 19:32:08.082117411 +0200
+++ /tmp/.psub.1sQMK2s5qB       2022-09-13 19:32:10.867121863 +0200
@@ -1553,19 +1553,6 @@
 genact-1.1.1-vendor.tar.gz/humansize/examples/
 genact-1.1.1-vendor.tar.gz/humansize/examples/custom_options.rs
 genact-1.1.1-vendor.tar.gz/humansize/examples/sizes.rs
-genact-1.1.1-vendor.tar.gz/humansize/feature-tests/
-genact-1.1.1-vendor.tar.gz/humansize/feature-tests/impl-style/
-genact-1.1.1-vendor.tar.gz/humansize/feature-tests/impl-style/cargo.toml
-genact-1.1.1-vendor.tar.gz/humansize/feature-tests/impl-style/src/
-genact-1.1.1-vendor.tar.gz/humansize/feature-tests/impl-style/src/lib.rs
-genact-1.1.1-vendor.tar.gz/humansize/feature-tests/impl-style/tests/
-genact-1.1.1-vendor.tar.gz/humansize/feature-tests/impl-style/tests/impl_style.rs
-genact-1.1.1-vendor.tar.gz/humansize/feature-tests/no-alloc/
-genact-1.1.1-vendor.tar.gz/humansize/feature-tests/no-alloc/cargo.toml
-genact-1.1.1-vendor.tar.gz/humansize/feature-tests/no-alloc/src/
-genact-1.1.1-vendor.tar.gz/humansize/feature-tests/no-alloc/src/lib.rs
-genact-1.1.1-vendor.tar.gz/humansize/feature-tests/no-alloc/tests/
-genact-1.1.1-vendor.tar.gz/humansize/feature-tests/no-alloc/tests/no_alloc.rs
 genact-1.1.1-vendor.tar.gz/humansize/src/
 genact-1.1.1-vendor.tar.gz/humansize/src/allocating.rs
 genact-1.1.1-vendor.tar.gz/humansize/src/formatters.rs
```

Looks like Cargo is somehow dropping these "feature-tests" on Darwin? As for a solution, I'm not sure. Normally you would add a `postFetch` to whatever fetch is giving differing results but maybe that fetch is generated by something like cargo2nix here?

**Comment by figsoda** [comment]
A possible solution would be to use `fetchCargoTarball` with `postFetch`

**Comment by figsoda** [comment]
maybe this is because the `cargo.toml` are lower case? I'm trying to understand what cargo-vendor-normalise does

**Comment by figsoda** [comment]
oh, there is depsExtraArgs

**Comment by figsoda** [comment]
@toonn I removed the `feature-tests` directory but there still seems to be a hash mismatch, perhaps now `.cargo-checksum.json` is different?

**Comment by figsoda** [comment]
jq puts a new line at the end 🤦, this should fix it now

**Pull request merged**
