### PR TITLE
vimPlugins: multiple vim and neovim themes

### PR DESCRIPTION
**Pull request by uchars**
## Description of changes

Added the following themes

- https://github.com/kartikp10/noctis.nvim
- https://github.com/folke/styler.nvim
- https://github.com/uloco/bluloco.nvim
- https://github.com/ribru17/bamboo.nvim
- https://github.com/aktersnurra/no-clown-fiesta.nvim
- https://github.com/NTBBloodbath/doom-one.nvim
- https://github.com/oxfist/night-owl.nvim
- https://github.com/rockerBOO/boo-colorscheme-nvim
- https://github.com/JoosepAlviste/palenightfall.nvim
- https://github.com/dasupradyumna/midnight.nvim
- https://github.com/gbprod/nord.nvim
- https://github.com/xero/miasma.nvim
- https://github.com/AhmedAbdulrahman/aylin.vim
- https://github.com/hachy/eva01.vim
- https://github.com/scottmckendry/cyberdream.nvim
- https://github.com/LunarVim/onedarker.nvim
- https://github.com/humanoid-colors/vim-humanoid-colorscheme
- https://github.com/lalitmee/cobalt2.nvim
- https://github.com/zootedb0t/citruszest.nvim
- https://github.com/phha/zenburn.nvim
    - renamed to `phha-zenburn` 
- https://github.com/yonlu/omni.vim
- https://github.com/AstroNvim/astrotheme
- https://github.com/Alexis12119/nightly.nvim
- https://github.com/blazkowolf/gruber-darker.nvim
- https://github.com/Verf/deepwhite.nvim
- https://github.com/felipeagc/fleet-theme-nvim

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by teto** [comment]
cc @GaetanLepage for review. (you might need to rebase too)

**Comment by GaetanLepage** [comment]
Diff LGTM. It surely has been generated by our beloved `vim-plugins-updater` script.
@teto do you wish to merge this before #289040 or the other way around ?

**Comment by GaetanLepage** [comment]
@uchars can you rebase on `master` please ?

**Comment by uchars** [comment]
should be rebased now

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 285361` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>26 packages built:</summary>
  <ul>
    <li>vimPlugins.astrotheme</li>
    <li>vimPlugins.aylin-vim</li>
    <li>vimPlugins.bamboo-nvim</li>
    <li>vimPlugins.bluloco-nvim</li>
    <li>vimPlugins.boo-colorscheme-nvim</li>
    <li>vimPlugins.citruszest-nvim</li>
    <li>vimPlugins.cobalt2-nvim</li>
    <li>vimPlugins.cyberdream-nvim</li>
    <li>vimPlugins.deepwhite-nvim</li>
    <li>vimPlugins.doom-one-nvim</li>
    <li>vimPlugins.eva01-vim</li>
    <li>vimPlugins.fleet-theme-nvim</li>
    <li>vimPlugins.gbprod-nord</li>
    <li>vimPlugins.gruber-darker-nvim</li>
    <li>vimPlugins.miasma-nvim</li>
    <li>vimPlugins.midnight-nvim</li>
    <li>vimPlugins.night-owl-nvim</li>
    <li>vimPlugins.nightly-nvim</li>
    <li>vimPlugins.no-clown-fiesta-nvim</li>
    <li>vimPlugins.noctis-nvim</li>
    <li>vimPlugins.omni-vim</li>
    <li>vimPlugins.onedarker-nvim</li>
    <li>vimPlugins.palenightfall-nvim</li>
    <li>vimPlugins.phha-zenburn</li>
    <li>vimPlugins.styler-nvim</li>
    <li>vimPlugins.vim-humanoid-colorscheme</li>
  </ul>
</details>

**Review by GaetanLepage — CHANGES_REQUESTED** [review]
Please rename commit to `vimPlugins: multiple vim and neovim themes`.

**Comment by uchars** [comment]
should be renamed now

**Review by GaetanLepage — APPROVED** [review]
LGTM ! Up to you @teto

**Pull request merged**
