### PR TITLE
flent: 1.2.2 -> 1.3.0

### PR DESCRIPTION
**Pull request by mmlb**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by markus1189** [comment]
Note: never used `flent` before.

I played around with it locally using the gui.  Seems to work fine, although for e.g. the `bursts1 test I get 

```
19:54:27 ERROR: Runner Ping (ms) UDP EF failed check: No netperf binary found in PATH.
```

But I guess it's better to rely on `netperf` on the path instead of adding all tools for all tests (don't know how many there are) as a dependency

**Comment by mmlb** [comment]
Yep, I had not added the dependencies when I created the package as I was only looking for the gui aspect of it, but that should probably be changed. @teto took a stab at wrapping flent, though https://github.com/NixOS/nixpkgs/issues/41521 I'm not quite sure what the ultimate goal was though.

**Comment by teto** [comment]
let's provide a full version by default then. Pass an `extraPrograms ? [ ]` parameter and from all-packages.nix pass the required 3rd party programs: iperf/netperf etc. 
It's not like these are huge programs anyway. Would be good to see the change in closure size though.

**Comment by mmlb** [comment]
@teto sgtm, but in a follow up PR?

**Comment by teto** [comment]
waiting for the follow up commit then, let's build with everything but let the possibility for someone to srip it down, sthg like extraDeps ? [ netperf iperf ... ]

**Comment by mmlb** [comment]
sgtm, will do so in next few days.

**Pull request merged**
