### PR TITLE
autojump: include a way to find the share dir

### LINKED ISSUE #3239: support autojump in zsh
https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/misc/autojump/default.nix#L28 notes that this is a fixme.

### PR DESCRIPTION
**Pull request by zimbatm**
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [x] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

autojump-share is a new script that gives you the path to autojump's
shared directory. It can then be used in the various shell's rc files to
find and source the autojump integration. Eg:

```
source "$(autojump-share)/autojump.bash"
```

Fixes #3239

### CODE REVIEW

**Comment by phunehehe** [comment]
this is cool!

**Comment by domenkozar** [comment]
well now we just need to document it :)

**Comment by zimbatm** [comment]
damn :) where should the documentation for packages go ?

**Comment by wjlroe** [comment]
LGTM

**Comment by jagajaga** [comment]
:+1:

**Comment by zimbatm** [comment]
Does it make sense to add the doc as a package note like that ? ^

**Pull request merged**
