### PR TITLE
zsh-history: Update gomod hashsum

### PR DESCRIPTION
**Pull request by kampka**
##### Motivation for this change

SHA256 checksum of gomod dependencies does not match on master

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @worldofpeace @teto

### CODE REVIEW

**Comment by teto** [comment]
@GrahamcOfBorg build zsh-history

**Comment by teto** [comment]
seems to fail on my nixos-unstable fork. Let's see how ofbord does

**Comment by kampka** [comment]
Well, I have no idea whats going on here. I had to generate the hashsum three times over for it converge in `nix-review` after using the one ofBorg originally wanted.
Fingers crossed it's good now.

**Comment by teto** [comment]
@GrahamcOfBorg build zsh-history

**Comment by teto** [comment]
what sometimes happen to me is that I first develop a package in an overlay and then move it to my nixpkgs but it still builds the version from the overlay xD. 
Looks like it is stiff failing

**Comment by kampka** [comment]
@GrahamcOfBorg build zsh-history

**Comment by teto** [comment]
@GrahamcOfBorg build zsh-history

**Comment by teto** [comment]
strange, the build succeeds once, the same hash is wrong for the 2 other tests, but wrong against 2 different values xD I don't know enough about the go ecosystem so let's wait for a more adept reviewer :(

**Comment by kampka** [comment]
@GrahamcOfBorg build zsh-history

**Comment by kampka** [comment]
@GrahamcOfBorg build zsh-history

**Comment by teto** [comment]
@GrahamcOfBorg build zsh-history

**Comment by kampka** [comment]
@teto I believe this might have been fixed with golang 1.13 but now the checksum turns back to the value we had before which means there is no change here. That's why GH closed this issue automatically and ofBorg does not longer build it.
Hydra however seems to build it just fine: https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.zsh-history.x86_64-linux#tabs-status

**Pull request closed without merging**
