### PR TITLE
lnav: 0.11.2 -> 0.12.1

### PR DESCRIPTION
**Pull request by cor**
## Description of changes

Changelog: https://github.com/tstack/lnav/releases/tag/v0.12.1

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by msanft — APPROVED** [review]

**Review by sikmir — CHANGES_REQUESTED** [review]
Result of `nixpkgs-review pr 304752` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>lnav</li>
  </ul>
</details>

```
lnav> readline_curses.cc:839:9: error: use of undeclared identifier 'ptsname_r'; did you mean 'ttyname_r'?
lnav>     if (ptsname_r(
lnav>         ^~~~~~~~~
lnav>         ttyname_r
```

**Comment by tstack** [comment]
Can you add a dependency on rust/cargo.  The 0.12.1 version adds support for [PRQL](https://prql-lang.org), which is implemented in rust.

It seems like the darwin version is pretty recent, so I don't know why `ptsname_r` is not found.  I think `_GNU_SOURCE` might be needed for it to be available and that is done in the configure script:

https://github.com/tstack/lnav/blob/4c3c958ab136136c5a1b626410486bc9dd1c29be/configure.ac#L33

Is it possible to run the `make` with `V=1`, so that the build commands are written out fully instead of the abbreviated `CXX <filename>`.

**Comment by tstack** [comment]
It looks like a dependency on `libarchive` is also missing.  That allows lnav to open up archive files and read the files within.

**Comment by tstack** [comment]
Another issue is that a dependency on tzdata needs to be added and a patch done to make the date library in lnav look in the right place.  Someone has done that part here:

https://github.com/soenkeliebau/nixpkgs/blob/lnav_0.12.2/pkgs/tools/misc/lnav/default.nix

**Comment by soenkeliebau** [comment]
Full disclosure: that patch should be taken woth a fair amount of salt!
That was just the first simple thing that I could come up with to make this work. Not sure if for example there is a chance to hit that other codepath with a hardcoded default value.

Also, embedding the patch in the .nix file is kinda ugly, but can't be helped because otherwise `${tzdata}` wouldn't be interpolated.. 

It would be nicer to come up with a generic patch that checks the TZDIR (which is set by tzdata automatically) env var and uses that instead of hardcoding a default.

https://github.com/samuel-emrys/date/commit/97551678c4f238d7b6f7bdba2a5abbf505c06259 has some code to that effect I believe. But my C skills are quite frankly not up to fully understanding what is happening and adapting it.

**Comment by tstack** [comment]
> Full disclosure: that patch should be taken with a fair amount of salt!

You say that, but it's not too different from what was done in the official nix package for the date library:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/howard-hinnant-date/default.nix

**Comment by wegank** [comment]
Done in #323321.

**Pull request closed without merging**
