### PR TITLE
topgrade: 4.7.0 -> 4.8.0

### PR DESCRIPTION
**Pull request by Br1ght0ne**
###### Motivation for this change
https://github.com/r-darwish/topgrade/releases/tag/v4.8.0

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by danieldk** [comment]
There is this comment in the derivation ;):

```
# TODO: add manpage (topgrade.8) to postInstall on next update
```

**Review by danieldk — APPROVED** [review]
LGTM

Result of `nixpkgs-review pr 91274` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
<br>- topgrade
</details>

ofborg is still stuck on Darwin and you may want to add a change to install the man page as suggested ;).

**Review by HugoReeves — APPROVED** [review]
Built and executed successfully on NixOS.
LGTM

**Comment by filalex77** [comment]
@danieldk Thanks for pointing out, I forgot about it! Will address in the next update :)

**Pull request merged**
