### PR TITLE
waybar: optionally wrap mediaplayer.py

### PR DESCRIPTION
**Pull request by bbigras**
This is a continuation of #85507 that I brok with a force push.

###### Motivation for this change
waybar has a `mediaplayer.py` script that uses mpris to show the current song.

###### Things done

Quite a package closure size increase.

No idea if I should use `preFixup` or another phase.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

/nix/store/igjl73fjbg42hdk4di4bpjb6gypjx3cl-waybar-0.9.2	 202.7M
/nix/store/fg8j6fq4pqziscjnvy1lry96hb2k6pxa-waybar-0.9.2	 **847.6M**

### CODE REVIEW

**Comment by bbigras** [comment]
I added `playerctl` back because we get:

```
[nix-shell:~/.cache/nixpkgs-review/pr-85507-1]$ result/bin/waybar-mediaplayer.py
Traceback (most recent call last):
  File "/nix/store/dygl1b2k1rdxylnzq5w0m8sgc0bm89c3-waybar-0.9.2/bin/..waybar-mediaplayer.py-wrapped-wrapped", line 8, in <module>
    gi.require_version('Playerctl', '2.0')
  File "/nix/store/w4mr1ykma079sgdw4bj9x9y3f6ax86mw-python3.8-pygobject-3.36.0/lib/python3.8/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Playerctl not available
 ```

Thanks for the help cole-h.

**Review by cole-h — APPROVED** [review]
LGTM. `waybar-mediaplayer.py` prints out some `playerctl`-related warnings, but this doesn't to appear impact functionality, so it should be fine.

```
https://github.com/NixOS/nixpkgs/pull/88080
1 package built:
waybar
```

**Review by FlorianFranzen — APPROVED** [review]
Thank you. Looks good to me.

**Comment by bbigras** [comment]
Thank you very much.

**Pull request merged**
