### PR TITLE
init meshio at 4.0.12 and init pygmsh at 6.1.1

### PR DESCRIPTION
**Pull request by Wulfsta**
###### Motivation for this change
Add packages.

Thanks to `energizer` on IRC for the help with `meshio`.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Wulfsta** [comment]
Oops, wrong git operations.

**Comment by Wulfsta** [comment]
There we go.

**Comment by Wulfsta** [comment]
`gmsh` should be a runtime dependency of this package, but regardless of which of [these](https://nixos.org/nixpkgs/manual/#ssec-stdenv-dependencies) I add it to, `nix-shell -I nixpkgs=./ -p 'python3.withPackages(ps: with ps; [ pygmsh pytest ])' --run pytest` seems to fail whereas `nix-shell -I nixpkgs=./ -p 'python3.withPackages(ps: with ps; [ pygmsh pytest ])' gmsh --run pytest` passes all tests.

**Comment by prusnak** [comment]
Please put URL in the `homepage` field into quotes (RFC45).

**Comment by Wulfsta** [comment]
@prusnak Done, but how do I get `gmsh` as a runtime dependency of `pygmsh`?

**Comment by doronbehar** [comment]
> passes all tests. How do I include this as a runtime dependency?

@prusnak I didn't manage to figure out what did you try to accomplish with that `nix-shell` command. The question I think you _should_ ask yourself is whether the python module you are packaging is usable to other python modules. Are trying to enable tests to the `pygmsh` module while `gmsh` is a runtime dependency of it? I think this should work when `gmsh` is in the `propagatedBuildInputs`.

**Comment by Wulfsta** [comment]
I cloned the pygmsh repository in a directory next to `nixpkgs`, and ran that `nix-shell` command from there. From my understanding that first command should make available a python environment with `pygmsh` and `pytest`, whereas the second also includes `gmsh` alongside python. `gmsh` is a runtime dependency of `pygmsh`, and needs to exist on the system for `pygmsh` to work. As I understand it, the first command failed to satisfy the runtime dependency, which implies that `propagatedBuildInputs` isn't enough. I could be misunderstanding the `nix-shell` though.

**Comment by doronbehar** [comment]
I _think_ that the non python deps of the packages you put in `propagatedBuildInputs` don't make their way to the `$PATH` of your nix-shell, if that's what you mean by "runtime dependency" - I noticed you didn't add `gmsh` to that nix-shell's `propagatedBuildInputs`.

**Comment by Wulfsta** [comment]
Aha, I think I understand the problem. I assume this derivation is actually correct then?

**Comment by doronbehar** [comment]
> Aha, I think I understand the problem. I assume this derivation is actually correct then?

Yes I think so too, just fix the merge conflicts, I'll verify everything builds and you'll get an approval from me.

**Comment by Wulfsta** [comment]
Oops, something went wrong with that push, sorry if you got pinged.

**Pull request closed without merging**
