### PR TITLE
Add various lsp and formatter packages in Node.js

### PR DESCRIPTION
**Pull request by winston0410**
###### Motivation for this change

To include more development tools like formatter and language server from NPM.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
You didn't properly regenerate the lock file.

**Comment by winston0410** [comment]
@SuperSandro2000 Is it step 2 that I have made error? I have run the following command and I got this error:

```
~/Desktop/nixpkgs/pkgs/development/node-packages master
❯ sh generate.sh
error: getting status of '/Users/hugosum/Desktop/nixpkgs/pkgs/development/node-packages/node-env.nix': No such file or directory
(use '--show-trace' to show detailed location information)
```

https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/node.section.md

**Comment by SuperSandro2000** [comment]
> @SuperSandro2000 Is it step 2 that I have made error? I have run the following command and I got this error:
> 
> ```
> ~/Desktop/nixpkgs/pkgs/development/node-packages master
> ❯ sh generate.sh
> error: getting status of '/Users/hugosum/Desktop/nixpkgs/pkgs/development/node-packages/node-env.nix': No such file or directory
> (use '--show-trace' to show detailed location information)
> ```
> 
> [https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/node.section.md](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/node.section.md?rgh-link-date=2021-07-13T15%3A15%3A51Z)

You want to run ``(cd pkgs/development/node-packages && ./generate.sh)``.

**Comment by winston0410** [comment]
I guess I should be running that from the root directory? But I still got the same error. Is `node-env.nix` generated?

```
~/Desktop/nixpkgs master
❯ (cd pkgs/development/node-packages && ./generate.sh)
error: getting status of '/Users/hugosum/Desktop/nixpkgs/pkgs/development/node-packages/node-env.nix': No such file or directory
(use '--show-trace' to show detailed location information)
```

**Comment by SuperSandro2000** [comment]
> I guess I should be running that from the root directory? But I still got the same error. Is `node-env.nix` generated?
> 
> ```
> ~/Desktop/nixpkgs master
> ❯ (cd pkgs/development/node-packages && ./generate.sh)
> error: getting status of '/Users/hugosum/Desktop/nixpkgs/pkgs/development/node-packages/node-env.nix': No such file or directory
> (use '--show-trace' to show detailed location information)
> ```

I think that file is missing but I am not sure why and why it fails.

**Pull request closed without merging**
