### PR TITLE
nixVersion.nix_2_3: Remove

### PR DESCRIPTION
**Pull request by mweinelt**
Nix 2.3 is the last version not using libarchive for decompression and
therefore prevents us from migrating the compression algorithm used for
the binary cache.

This resulted from interest in using zstd compression on hydra.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
@chkno Can you port `nixos-option` to a more recent nix version, please?

**Comment by Artturin** [comment]
Sounds good to me, let's also bump minver (i will handle it in #203361 which we can merge when most people have migrated to 22.11)

**Comment by mweinelt** [comment]
The minver bump is already in there.

**Comment by Artturin** [comment]
> What about the remaining packages in `nixVersions` (2.6 to 2.10)?

let's think about that in #203361 

this pr can be merged with the minver bump and the release notes and i'll remove them in my pr

**Comment by Artturin** [comment]
@andir why the :confused: ?

**Review by SuperSandro2000 — APPROVED** [review]
Can someone please be so kind and update nixos-option? We should also move it into its own repository and out of nixpkgs.

**Comment by vcunat** [comment]
> What about the remaining packages in `nixVersions` (2.6 to 2.10)?

2.6 is there quite newly: PR https://github.com/NixOS/nixpkgs/pull/200357

**Comment by vcunat** [comment]
I'd personally _not_ bump minver at this point.  Maybe throw a warning, but not hard error.  I mean, everything will still work fine with 2.3, except perhaps downloading from cache.nixos.org &ndash; and only for binaries created *in future* (and it's not like switch's been decided yet).  So at this point, bumping minver feels like introducing breakage without utilizing any benefit in exchange (in nixpkgs).

**Comment by Mic92** [comment]
Ok with dropping pythonix

**Comment by mweinelt** [comment]
Drpüed the minver bump.

**Comment by andir** [comment]
> @andir why the confused ?

Because I am still using 2.3 daily. I've had it as a default until last week. Newer Nix versions simply break too much for me to be happy with them. Reporting issues to the Nix project usually doesn't result in any constructive conversation on how to fix issues. PRs are left hanging etc. If you asked me, all versions after 2.3 are at best beta quality.

**Comment by Artturin** [comment]
> > What about the remaining packages in `nixVersions` (2.6 to 2.10)?
> 
> 2.6 is there quite newly: PR #200357

removals of 2.6-2.9 in https://github.com/NixOS/nixpkgs/pull/204481 
they should be uncontroversial

**Comment by SuperSandro2000** [comment]
The default nix version is newer than 2.3 for quite a while and no one I know in person has problems they complain about it that weren't also in 2.3 like to much RAM usage, downloading could be faster or taking a bit to evaluate.

I'd rather fancy zstd compressed packages to slightly speed up downloads and improve extraction performance than keeping nix 2.3.

**Comment by Profpatsch** [comment]
I know at least a dozen people who have nix pinned to 2.3.

Nix 2.3 was the last “stable” release (the release window between 2.3 and 2.4 was over 2 years), before promises like “the new CLI is gonna be stabilized any week now” were traded in for “flakes is gonna be stabilized any bi-monthly release now”.

What we effectively got since 2.3 was constant beta-quality changes to experimental features, which is the reason so many people stayed on 2.3 from what I know.

**Comment by RaitoBezarius** [comment]
I switched to later versions of Nix, but to be honest, I still run into Nix 2.3 regressions in the latest versions. I completely understand why some people want to keep running it, so I am too keen on seeing this PR being merged until a clear plan of addressing Nix 2.3 regressions is there and executed (easier to say than to do, of course).

**Review by Mic92 — APPROVED** [review]
fine with dropping pythonix

**Comment by edef1c** [comment]
zstd decompression support for Nix 2.3 isn't a lot of work; I'm not sure why that option wasn't considered previously.
I've implemented it in https://github.com/NixOS/nix/pull/9221, aiming for simplicity over performance.
If there is interest, I'm happy to optimise it for speed.

**Comment by SuperSandro2000** [comment]
Because it is already implemented via libarchive and we don't need to redevelop it for a 15 (!) minor version old release.

**Comment by RaitoBezarius** [comment]
Yes but it's used by other people and any further version still possess
unsolved bug unfortunately.

**Comment by RaitoBezarius** [comment]
> Because it is already implemented via libarchive and we don't need to redevelop it for a 15 (!) minor version old release.
> 
> Can we work together to get this PR finished instead of walking in circles?
> 
> I am personally like many others using a version which is a lot newer and it's useable. Maybe things are broken but I don't have the comparison, I don't know but I want to get this somewhere because German Internet is slow and downloading less for every nixos-unstable bump would be a pretty great benefit.
> 
> 

You'd download more with zstd, this was explained in the Discourse post. So it would worsen the situation.

It'd only benefit people like me with fast French Internet.

Under the presence of zstd in 2.3, removing it is NACK from me.
And anyway even pushing for zstd is its own question.

**Comment by roberth** [comment]
> Reporting issues to the Nix project usually doesn't result in any constructive conversation on how to fix issues. PRs are left hanging etc.

I'm sorry to hear that. We've been putting in a lot of effort over the past year (the Nix team). In particular we've succeeded at keeping PR backlog stable near 300 until approximately NixCon. In other words, new PRs had a good chance, and those that didn't were compensated by old PRs.
We have also triaged many issues, made relevant decisions, tried help move them forward, but those were mostly newer issues.

**Comment by edef1c** [comment]
> Because it is already implemented via libarchive and we don't need to redevelop it for a 15 (!) minor version old release.

Newer Nix versions are full of regressions, so I'm still running 2.3 and expect to continue doing so until Tvix is production-ready. No work on your part is necessary to port it to 2.3, the code is already written, so I'm not sure what else would satisfy you.

**Comment by edef1c** [comment]
More generally, is there a tracking issue for moving Hydra to zstd? I'm actively working fulltime on cache _storage_ size reduction strategies, and _serving_ the cache as zstd would definitely help enable the techniques we're working on gathering data for.

**Comment by vcunat** [comment]
I don't think there is.  The place would most likely be https://github.com/NixOS/nixos-org-configurations/issues but I believe that right now the more pressing matters are like reducing storage size, which goes against this.  Though perhaps we could afford worse compression ratio once we start expiring some older paths: https://github.com/NixOS/nixos-org-configurations/issues/282

**Comment by SuperSandro2000** [comment]
> Newer Nix versions are full of regressions

You are just saying that without any context or referencing any issue(s) or problems. We have nothing concrete here, just some vague statement that newer versions are supposedly unusable despite many many people using them daily and it seems to somehow work for them.
Could someone at least link one issue or problem that is so pressing that it must be fixed before dropping 2.3? Otherwise I don't think we can get here anywhere.

**Comment by RaitoBezarius** [comment]
> > Newer Nix versions are full of regressions
> 
> You are just saying that without any context or referencing any issue(s) or problems. We have nothing concrete here, just some vague statement that newer versions are supposedly unusable despite many many people using them daily and it seems to somehow work for them. Could someone at least link one issue or problem that is so pressing that it must be fixed before dropping 2.3? Otherwise I don't think we can get here anywhere.

Honestly, it's quite tiring because you can figure this out on your own by just going into https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc and type "Nix 2.3", obvious results will appear.

We spent the last years explaining and answering to this over and over, this is disrespectful of the time of others.

What has been said for the last years was: "If you don't want Nix 2.3 to be removed, get zstd support", this is now done.

If you have objective and valid reasons to remove Nix 2.3, I am interested, for the time being, I do not see them, therefore, there's no reason to drop support for Nix 2.3 at the moment.

The project is frustrating enough for a lot of folks which were disrespected and burned out in the past, let's not make them ragequit just for the sake of increasing a version number with no benefits.
Please be kind and take into account the history of other people involved in this project.

If you want Nix 2.3 to move, please, let's collect all reasonable Nix 2.3 regressions, show they are fixed in a Nix release that is supported by nixpkgs and we can potentially move the needle **there**. In the meantime, thanks to @edef1c efforts, Nix 2.3 community did the work to unblock people wanting zstd support. This cannot work only in one way.

**Comment by mweinelt** [comment]
With nix 2.3 having gained zstd support this PR has been made obsolete for my cause.

Please make sure these patches make it into nixpkgs.

**Comment by RaitoBezarius** [comment]
Tracked in https://github.com/NixOS/nix/issues/9244.

**Pull request closed without merging**
