### PR TITLE
nixos/sshd: disable openFirewall by default

### PR DESCRIPTION
**Pull request by bb2020**
Opening SSH port on firewall is a security risk and it should be blocked by default.

I thought this was an urgent issue so I didn't use proper branching and had to create a new PR.
Sorry for the duplicate.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by aanderse — APPROVED** [review]
By forcing the user to choose a value this satisfies the argument against unknowingly locking people out of their systems, as well as the argument for a more secure default :+1:

If there were to be any change to this PR I might suggest that since this will impact a large number of users we might add an assertion which explains the situation nicer than the existing `openFirewall` referenced but not declared error, which isn't overly nice or clear.

**Comment by aanderse** [comment]
We should see if @edolstra finds this to be an acceptable compromise. This satisfies issues he has raised in the past, so I think there is a chance he would be accepting of this.

**Comment by edolstra** [comment]
This would be okay, though I still think that the case where you want sshd enabled but you don't want it exposed in the firewall is a pretty rare one. So the current situation has my preference.

**Comment by bb2020** [comment]
One possible scenario would be having two interfaces and assigning one of them as trusted interface with `networking.firewall.trustedInterfaces`. As you can access to trusted interface freely,  one may think that the other interface is safe while it is not.

**Comment by aanderse** [comment]
> One possible scenario would be having two interfaces

This is my scenario. I set `openFirewall` to `false` and then explicitly open port `22` for a given interface.

**Comment by bb2020** [comment]
Of course you are right. This is a rare situation. However SSH is a dangerous thing when it is unchecked by firewall. I think we should maximize security whenever possible.

**Comment by Frostman** [comment]
if I'm not mistaken, it'll add an extra not that obvious step to the installation process - not only enable sshd but open port for it.

**Comment by aanderse** [comment]
@Frostman posting a clear message to the screen in an assertion if the user hasn't explicitly opened the firewall will clarify any confusion. All services **except** `openssh` require the user to explicitly open a port in the firewall.

Personally I'm somewhat indifferent to this PR, but the change has been requested a number of times and it seems like a reasonable solution to me. Since @edolstra seems to find this solution acceptable enough maybe we just wait and see more opinions :man_shrugging:

**Comment by bb2020** [comment]
Hi everyone. It has been a year since I opened this PR (time passes :confused:). Should we merge this for `21.05`?

I've changed the default setting to `false` and utilized `stateVersion`. Is this okay or the explicit assertion should be there indefinitely? With this change, NixOS will have `openFirewall = false` policy for all packages, no exceptions. Best wishes!

**Comment by jonringer** [comment]
I would agree with eelco. If i were to do `sevices.sshd.enable = true;` I would expect to be able to ssh to the machine. The use cases where you would want the firewall to close the port, but have sshd active seems much less likely than the normal use case.

**Comment by Melkor333** [comment]
I'm in favor of this change! IMO it doesn't make sense to be inconsistent and have only `openFirewall` set to true by default for this service.
SSH is usually the only protocol used to connect to servers on a daily basis so I get why people like to have it enabled per default. But IMHO I would never want a server with a public IP to expose port 22 globally anyway just because of the log noise that would be generated. Especially since `passwordAuthentication` is also true per default.
Closing the SSH port is also often wanted as soon as a device has more than one interface. This includes virtual interfaces like VPN.

I also consider it a good thing when newcomers learn how ports can be opened in the firewall by having to do it. I think the assert statement would do a good job for that purpose. Therefore I personally would like to have the default set to `NULL` as a "compromise" (and not default to `false` for `>=21.05`).

**Comment by Ma27** [comment]
I'm not entirely sure yet if I'm in favor of this, but if it gets merged, we'll also need

* a note in the release-notes.
* IMHO having this flag set (commented out though) in `nixos-generate-config.pl`

**Comment by nixinator** [comment]
I would certainly go for this change if after a successful nixos-rebuild switch, nixos gave feedback to the user on what ports are currently enabled.

nix-repl> config.networking.firewall.allowedTCPPorts
[ 3000 ]

that way, your reminded what nix expressions are opening what and you audit your machine every time you rebuild ... neat huh?

;-)

**Comment by nixinator** [comment]
> This should be doable with `nixos-option networking.firewall.allowedTCPPorts` or `nixops show-option (forgot which arguments come here though)`. Or do you want to have this in an automated way?

[vulnix](https://github.com/flyingcircusio/vulnix)

**Comment by bb2020** [comment]
> I would certainly go for this change if after a successful nixos-rebuild switch, nixos gave feedback to the user on what ports are currently enabled.
> 
> nix-repl> config.networking.firewall.allowedTCPPorts
> [ 3000 ]
> 
> that way, your reminded what nix expressions are opening what and you audit your machine every time you rebuild ... neat huh?
> 
> ;-)

This makes you to overlook per-interface open ports though.

**Comment by nixinator** [comment]
> This makes you to overlook per-interface open ports though.

ah! good point. 

networking.firewall.interfaces.wg0.allowedTCPPorts

so it would need to evaluate all interfaces on the machine..  it might be a nice feedback feature! :-)

**Comment by bb2020** [comment]
> > This makes you to overlook per-interface open ports though.
> 
> ah! good point.
> 
> networking.firewall.interfaces.wg0.allowedTCPPorts
> 
> so it would need to evaluate all interfaces on the machine.. it might be a nice feedback feature! :-)

This is a great idea, if it is not happening in my PR :smile:

**Comment by MatthewCroughan** [comment]
This is dependent on use-case. If this change is made, then I will be unable to contact my machines magically when I upgrade my NixOS channels. It's pretty radical. People will have to learn about this implicit default, it will have to be included in the output of `nixos-generate-config` explicitly. The installer image ought to have `openFirewall = true;` on by default, for sure. Else, I'd have to do a `nixos-rebuild-switch` just to remotely install NixOS via `ssh`.

Currently, my procedure for installation from installer images on a Hetzner VPS or local physical server for me is:

1. Boot installer ISO
2. Change `nixos` user `passwd`
3. `ssh` into the machine remotely
4. `nixos-generate-config --root /mnt`
  (or whatever else I need to do in order to provision the machine)
5. `nixos-install`

After step 3, you could do anything with nixops, deploy-rs, etc. It's quite handy.

The proposed change would make me unable to do this, correct? Disabling `ssh` by default just messes with provisioning.

**Comment by Ma27** [comment]
AFAIU you won't if you didn't set `sshd.openFirewall`. If it's `null`, an eval error will be thrown and thus no bogus config will be deployed.

**Comment by aanderse** [comment]
You are correct @Ma27 - this PR forces the user to explicitly set a value... so no risk of breakage.

**Comment by MatthewCroughan** [comment]
> AFAIU you won't if you didn't set `sshd.openFirewall`. If it's `null`, an eval error will be thrown and thus no bogus config will be deployed.

So does this mean that the default configuration as it is today, made by `nixos-generate-config` will fail to rebuild?

**Comment by MatthewCroughan** [comment]
However, what about the installer image? SSH is enabled on that out-of-the-box. This is nice behavior in my view, because it allows easy provisioning, so even if this is merged, `openFirewall` should still be set to `true` on the installer image.

**Comment by bb2020** [comment]
> However, what about the installer image? SSH is enabled on that out-of-the-box. This is nice behavior in my view, because it allows easy provisioning, so even if this is merged, `openFirewall` should still be set to `true` on the installer image.

I tried to achieve that [here](https://github.com/NixOS/nixpkgs/blob/fa834fdf4a7544bbc69b38b2692d75d76df15ea2/nixos/modules/profiles/installation-device.nix#L70). I am not sure if it is enough.

**Comment by bb2020** [comment]
By the way I still think this should be merged :smiley:

**Comment by aanderse** [comment]
unfortunately we not only failed to reach consensus on this, and there are some strong opinions both ways, but support for the change wasn't overwhelming enough that we can accept this

i would say that this PR should be closed at this point

**Comment by bjornfor** [comment]
> unfortunately we not only failed to reach consensus on this, and there are some strong opinions both ways, but support for the change wasn't overwhelming enough that we can accept this

I just read the thread and disagree with this summary. IMO, the posts that were strongly negative misunderstood the PR and changed their opinion afterwards (maybe not to "positive" but at least not "negative"). Some were indifferent. Some were positive.

I suggest we use this post with thumbs up/down for whether to re-open this PR.

**Comment by aanderse** [comment]
is there enough visibility in this thread? maybe elsewhere is better?

to be clear i think that this is a good idea... but i think a strong consensus needs to be reached here if we were to proceed

**Comment by Ma27** [comment]
> IMO, the posts that were strongly negative misunderstood the PR

To be fair, the author didn't bother to update the summary and if the summary says "__sshd__: disable openFirewall __by default__", it's fine to already say "no" if you feel that way.

That being said, to me the current approach seems like yet another annoyance pushed to the end user of this NixOS module which is why I prefer the current default. If people strongly feel they don't want to expose their sshd onto the Internet, they may still disable it.

> Opening SSH port on firewall is a security risk and it should be blocked by default.

Is it though? I mean, I'm probably a little biased, but I've seen numerous SSH installations being exposed to the internet and that's the way how these were deployed.

**Pull request closed without merging**
