### PR TITLE
yate: patch shebangs in configure

### PR DESCRIPTION
**Pull request by pbogdan**
###### Motivation for this change

Avoid dependency on `/bin/sh`, otherwise the build may fail like so https://hydra.nixos.org/build/70734780/nixlog/2

/cc ZHF #36453

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build pbogdan

**Comment by Mic92** [comment]
gosh...
@GrahamcOfBorg build yate

**Comment by Mic92** [comment]
@pbogdan can you add yourself to borg? https://github.com/NixOS/ofborg/pull/100

**Comment by Mic92** [comment]
@pbogdan can you also disable aarch64?

**Comment by pbogdan** [comment]
Done, kept `i686-linux` as it looks to build and run fine (tested locally).

**Comment by Mic92** [comment]
also backported in d2bf584a7588e1e2dc72d37b42b4f27f14ad6af2 7b72d7f713ffae1e9a1def3b324e9085cf4203b2

**Comment by pbogdan** [comment]
Thank you!

**Pull request merged**
