### PR TITLE
python310Packages.moderngl-window: 2.4.4 -> 2.4.5, manim: 0.16.0.post0 -> 0.17.3

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Update and fix `moderngl-window` and `manim`.
Changelog `moderngl-window`: https://github.com/moderngl/moderngl-window/releases/tag/2.4.5
Changelog `manim`: https://github.com/ManimCommunity/manim/releases/tag/v0.17.3

cc @c0deaddict @friedelino 

TODO: Is it still broken on darwin ?

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by GaetanLepage** [comment]
@ofborg build python310Packages.moderngl-window python311Packages.moderngl-window

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 261666` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>manim</li>
    <li>manim.dist</li>
    <li>python310Packages.moderngl-window</li>
    <li>python310Packages.moderngl-window.dist</li>
    <li>python311Packages.moderngl-window</li>
    <li>python311Packages.moderngl-window.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
@ofborg build python310Packages.moderngl-window python311Packages.moderngl-window manim

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 261666` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>manim</li>
    <li>manim.dist</li>
    <li>python310Packages.moderngl-window</li>
    <li>python310Packages.moderngl-window.dist</li>
    <li>python311Packages.moderngl-window</li>
    <li>python311Packages.moderngl-window.dist</li>
  </ul>
</details>

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 261666` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>manim</li>
    <li>manim.dist</li>
    <li>python310Packages.moderngl-window</li>
    <li>python310Packages.moderngl-window.dist</li>
    <li>python311Packages.moderngl-window</li>
    <li>python311Packages.moderngl-window.dist</li>
  </ul>
</details>

**Review by natsukium — APPROVED** [review]
LGTM

It seems that the broken mark is propagated by the dependencies.
It is currently impossible to build with darwin.

**Pull request merged**
