### PR TITLE
darwin: miscellaneous fixes

### PR DESCRIPTION
**Pull request by matthewbauer**
###### Motivation for this change

This is a bunch of miscellaneous fixes to Darwin. I can split them up into multiple prs if necessary, but hopefully it won't be necessary.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by LnL7** [comment]
I get this when building cwebbin, do you get the same with `nix-build -A cwebbin.src --check`?

```
unpacking source archive /private/var/folders/qv/5k4lhv3n1hg2jk29cj3smtp00000gn/T/nix-build-cwebbin-cwebbin-22p-src.drv-0/cwebbin-22p.tar.gz
output path ‘/nix/store/pb6ag3d3cznzklaqfbamfs4kk4q13mm1-cwebbin-cwebbin-22p-src’ has r:sha256 hash ‘180i5af07zhjv7cdi1wggs9b03iwj07ay7dkvfdwi1ljm6rqm4dj’ when ‘0zf93016hm9i74i2v384rwzcw16y3hg5vc2mibzkx1rzvqa50yfr’ was expected
```

**Comment by matthewbauer** [comment]
I uploaded a fix.

**Comment by LnL7** [comment]
Oh it's actually `nix-build -A cwebbin.cweb --check` not the src, that has a different hash for me.

**Comment by matthewbauer** [comment]
@LnL7 Ok got it now, I think. How do you feel about these kind of "miscellaneous" pull requests? I can definitely open separate PRs for each commit but these are mostly unused, tiny packages that I think can be grouped together.

**Review by LnL7 — APPROVED** [review]

**Comment by LnL7** [comment]
I don't have a problem with it for trivial changes like this. It's just generally preferred to keep unrelated changes separate to reduce the chance of good changes getting blocked by another issue or unrelated merge conflicts.

**Pull request merged**
