### PR TITLE
wivrn: 0.19 -> 0.20

### PR DESCRIPTION
**Pull request by Titaniumtown**
https://github.com/WiVRn/WiVRn/releases/tag/v0.20

## Things done

Ported to: https://github.com/WiVRn/WiVRn/releases/tag/v0.20

added glib as a dependency

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

@PassiveLemon 

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Titaniumtown** [comment]
I've done some testing and maybe avahi-daemon.service is not being properly started?

**Review by tomodachi94 — CHANGES_REQUESTED** [review]
Diff looks good, but can you change a2922fae7ea92ee5c3ddb5999ee1997c699d87f8 to be prefixed with `nixos/wivrn` instead?

**Comment by Titaniumtown** [comment]
@tomodachi94 your wish is my command!

**Review by tomodachi94 — APPROVED** [review]
Lgtm, thank you!

As mentioned in Matrix, I'd like to wait until @PassiveLemon reviews this PR before merging it.

**Comment by PassiveLemon** [comment]
Will fully review in a moment, currently running some tests on my machine

**Comment by PassiveLemon** [comment]
I've been keeping up to date in my flake repository: https://github.com/PassiveLemon/lemonake/tree/master/pkgs/wivrn
Would you mind updating the PR with these? Ignore the missing sources/versions, that's just how the repository is designed.

Also here's a message from Xytovl:
When you plan to update to 0.20, there's quite a few changes related to build:
* the default IPC socket path has been changed to `$XDG_RUNTIME_DIR/wivrn/comp_ipc`, note the change from `_` to `/`, this can be overriden at compile time by setting `XRT_IPC_MSG_SOCK_FILENAME` but I do not recommend it as it may cause issues with inconsistent docs.
* There is now a GUI with `WIVRN_BUILD_DASHBOARD`, which adds an additional dependency on qt, has a `.desktop` file. `WIVRN_CHECK_CAPSYSNICE` compile option adds check in gui for cap_sys_nice, you can safely set it to off if nix takes care of it
* Configuration is now smarter: it is possible to omit encoder, codec or group in the encoders array and it will have a sensible value (hardware encoder, best quality codec supported by headset + encoder, grouping encoders of the same type together)
* monado patches have changed (make sure your list is up to date), `WIVRN_USE_SYSTEMD` is no longer necessary for reliable application autostart feature.

The link I provided above covers the dashboard and the monado patches, but the smarter configuration and IPC socket path are not relevant to the package/module so those can be disregarded.

**Comment by Titaniumtown** [comment]
Thanks for the feedback @PassiveLemon I'll work on adjusting the package.

**Comment by Titaniumtown** [comment]
How do I make it a Qt package? I need to call it like described in: https://nixos.wiki/wiki/Qt or else I don't get all the qt dependencies I need.

**Comment by PassiveLemon** [comment]
It should be called with `pkgs.qt6Packages.callPackage` since the dashboard uses Qt 6

**Comment by PassiveLemon** [comment]
If you would like, I could PR 0.19 -> 0.20 since I pretty much have it all done anways

**Comment by Titaniumtown** [comment]
> If you would like, I could PR 0.19 -> 0.20 since I pretty much have it all done anways

Ok I can close this PR then. Thank you!

**Comment by Titaniumtown** [comment]
also, if you don't mind @ me on that new PR please :) @PassiveLemon

**Comment by PassiveLemon** [comment]
Submitted a PR ^^

**Pull request closed without merging**
