### PR TITLE
libvirt: 4.5.0 -> 4.6.0

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

new version

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg build python36Packages.libvirt python27Packages.libvirt

**Comment by xeji** [comment]
@GrahamcOfBorg build virtmanager virt-viewer

**Comment by xeji** [comment]
Timeouts as usual recently.  LGTM.

**Comment by Izorkin** [comment]
With this version libvirt error work virt-manager/ Not connected to qemu:///system:
```
Unable to connect to libvirt qemu:///system.

нет драйвера подключения для qemu:///system

Libvirt URI is: qemu:///system

Traceback (most recent call last):
  File "/nix/store/k97sj445pjgj53ibj3737hfixkv3xr95-virt-manager-1.5.1/share/virt-manager/virtManager/connection.py", line 1036, in _do_open
    self._backend.open(self._do_creds_password)
  File "/nix/store/k97sj445pjgj53ibj3737hfixkv3xr95-virt-manager-1.5.1/share/virt-manager/virtinst/connection.py", line 144, in open
    open_flags)
  File "/nix/store/bkfwx4sjdr2jk3nmk6fh3mbzsplbknk1-python2.7-libvirt-4.6.0/lib/python2.7/site-packages/libvirt.py", line 104, in openAuth
    if ret is None:raise libvirtError('virConnectOpenAuth() failed')
libvirtError: нет драйвера подключения для qemu:///system
```
Journalctl:
```
авг 11 01:26:35 NixOS-Local libvirtd[4240]: 2018-08-10 22:26:35.934+0000: 4263: error : virConnectOpenInternal:1072 : нет драйвера подключения для qemu:///system
авг 11 01:26:35 NixOS-Local libvirtd[4240]: 2018-08-10 22:26:35.954+0000: 4240: error : virNetSocketReadWire:1805 : Достигнут конец файла при чтении данных: Input/output error

```

**Comment by Izorkin** [comment]
@volth new error:

```
авг 11 14:25:33 NixOS-Local libvirtd[19902]: 2018-08-11 11:25:33.840+0000: 19902: info : libvirt version: 4.6.0
авг 11 14:25:33 NixOS-Local libvirtd[19902]: 2018-08-11 11:25:33.840+0000: 19902: info : hostname: NixOS-Local
авг 11 14:25:33 NixOS-Local libvirtd[19902]: 2018-08-11 11:25:33.840+0000: 19902: error : virJSONJanssonOnceInit:66 : функция не поддерживается драйвером соединения: libjansson.so.4 JSON library not available: libjansson.so.4: cannot open shared object file: No such file or directory
```

**Comment by volth** [comment]
@Izorkin: https://github.com/volth/nixpkgs/commit/d46cfd2ff087816697f46d69f9f795ff878301c5 (I will make a PR after the testing)

**Pull request merged**
