### PR TITLE
{wlcs,mir}: Bump to newer versions

### PR DESCRIPTION
**Pull request by OPNA2608**
###### Description of changes

- wlcs: 1.5.0 -> 1.6.0
- mir: 2.13.0 -> 2.14.1

Updating these together because updating  either of them individually makes the Mir tests segfault.

~~Would run Miriway VM test as a check, but it's broken on master. :slightly_frowning_face: 
Fix for that: #245880~~

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by OPNA2608** [comment]
Miriway tests should be fixed again.

@ofborg build miriway.passthru.tests

**Comment by OPNA2608** [comment]
[2.15.0](https://github.com/MirServer/mir/releases/tag/v2.15.0) is now out, but:

- bumping to it would break `miriway` until we're on at least https://github.com/Miriway/Miriway/commit/e3a2d6f9ffb97929485971458323be0357c748cd, and bumping `miriway` up to that without at least the versions in this PR doesn't compile because it needs things from 2.14.0 <sub>and the preprocessor version check in Miriway doesn't seem to properly catch this?</sub>
- https://github.com/MirServer/mir/pull/3008 wants to setup a Python venv environment & use `pip` at build time, which won't work in our build sandbox

@onny, could you find the time to review this so I can continue with further bumps without making this PR explode in scope?

**Comment by Janik-Haag** [comment]
Result of `nixpkgs-review pr 245854` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>mir</li>
    <li>mir.dev</li>
    <li>mir.doc</li>
    <li>miriway</li>
    <li>wlcs</li>
  </ul>
</details>

**Review by Janik-Haag — APPROVED** [review]
LGTM

**Comment by Artturin** [comment]
builds

**Pull request merged**
