### PR TITLE
minetime: 1.7.3 -> 1.8.10

### PR DESCRIPTION
**Pull request by cheriimoya**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

@ajs124

### CODE REVIEW

**Comment by ajs124** [comment]
This only gives me a blank screen? Does it work for you?

**Comment by cheriimoya** [comment]
true, i accidentally ran the wrong version of minetime. from my nixpkgs, not the branch

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 101797` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>minetime</li>
  </ul>
</details>

**Comment by ajs124** [comment]
??? does this work now?

**Comment by ajs124** [comment]
@SuperSandro2000 are you sure this doesn't just show a white screen?

**Pull request merged**
