### PR TITLE
reiserfsprogs: fix cross compilation

### PR DESCRIPTION
**Pull request by eburimu**
###### Motivation for this change

Fixes https://github.com/NixOS/nixpkgs/issues/51132

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build reiserfsprogs

**Review by Mic92 — APPROVED** [review]

**Review by Ericson2314 — APPROVED** [review]
Nice!

**Comment by eburimu** [comment]
@Ericson2314 OK, fix the patch, now you can merge.

**Comment by Ericson2314** [comment]
Failure looks unrelated, but want to rebase/remerged with master if it's fixed just in case? Sorry about that.

**Comment by Mic92** [comment]
merged in cfb184f2cb8

**Pull request closed without merging**
