### PR TITLE
[20.03] build-bazel-package: switch hash mode to “flat”

### PR DESCRIPTION
**Pull request by matthewbauer**
flat hashes can be substituted through hashed-mirrors, while recursive
hashes can’t. This is especially important for Bazel since the bazel
fetch dependencies can come from multiple different methods (git,
http, ftp, etc.). To do this, we create tar archives from the
output/external directory, which is then extracted to build. All of
the Bazel hashes are all updated.

Cherry-picked from 9b8ed3bd998301ecc1e8ce3ed7c54c741f4ae315

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kalbasit** [comment]
This will break packages outside of nixpkgs. I am not sure it is worth backporting?

**Comment by FRidh** [comment]
This is a change in interface on a stable branch. I don't think that is acceptable.

**Comment by matthewbauer** [comment]
Yes will wait on this and see if there's a way to not make it breaking.

**Comment by bhipple** [comment]
That's fine; I can cherry-pick it onto our 20.03 fork where it's needed and it'll drop off when we upgrade to 20.09 later this year.  Since the diff is so small I don't anticipate issues.

**Pull request closed without merging**
