### PR TITLE
build-support/rust: Add target option

### PR DESCRIPTION
**Pull request by exFalso**
###### Motivation for this change

This PR adds a flag to `buildRustPackage` that can override the `--target` flag to cargo.

###### Things done

Added the flag, adjusted corresponding paths in the code.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions (Arch Linux)
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @andir @Mic92

### CODE REVIEW

**Comment by Mic92** [comment]
How do you use this flag, given that our rustc expression does not allow set a target different from `stdenv.targetPlatform.config`?

**Comment by exFalso** [comment]
We use an overridden nightly rust, i.e.
```nix
  mozillaOverlay = nixpkgs.fetchFromGitHub {
    owner = "mozilla";
    repo = "nixpkgs-mozilla";
    rev = "b52a8b7de89b1fac49302cbaffd4caed4551515f";
    sha256 = "1np4fmcrg6kwlmairyacvhprqixrk7x9h89k813safnlgbgqwrqb";
  };
  rustOverlay = import "${mozillaOverlay.out}/rust-overlay.nix" nixpkgs.pkgs nixpkgs.pkgs;
  rustNightly = rustOverlay.rustChannelOf {
      sha256 = "1siwx5k3jk637zf16ygmx2wxkm26wdkgl6bqh35f7j0cnfhlpz58";
      date = "2019-09-27";
      channel = "nightly";
  };
  rustSgx = rustNightly.rust.override {
    targets = [ "x86_64-fortanix-unknown-sgx" ];
  };
```

then 

```nix
pkgs.rustPlatform.buildRustPackage {
  .. bla bla ..
  target = "x86_64-fortanix-unknown-sgx";
}
```

**Comment by Mic92** [comment]
Can you add an example to our some documentation as well? (`doc/languages-frameworks/rust.section.md`)

**Comment by exFalso** [comment]
> Can you add an example to our some documentation as well? (`doc/languages-frameworks/rust.section.md`)

Added a small paragraph

**Pull request merged**
