### PR TITLE
urbit: 0.6.0 -> 0.7.1

### PR DESCRIPTION
**Pull request by bsima**
###### Motivation for this change

Minor version update

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by etu** [comment]
@GrahamcOfBorg build urbit

**Comment by etu** [comment]
The build failure seems to be new on aarch64: https://hydra.nixos.org/job/nixpkgs/staging/urbit.aarch64-linux

**Comment by bsima** [comment]
Looks like this is a known issue https://github.com/urbit/urbit/issues/970

**Comment by bsima** [comment]
@etu: Is there a way to say something like `platforms = [ linuxExceptAarch64 ]`?

**Comment by etu** [comment]
@bsima Usually we don't want to go break on one platform where it currently works. And usually we don't want to diverge the versions per platform.

But we usually try to see if upstream may have a patch or something that can be applied in the version in question so we can update the package and get on with it.

But from looking at the issue linked above it doesn't seem like upstream have made any statements other than putting labels on it...

**Comment by bsima** [comment]
Okay, let's put this on the shelf for now and I'll come back to it in a
few weeks to see if they've made progress. In the meantime, maybe I'll
take a crack at fixing it myself and upstream the patch if I have
time...

**Comment by ryantm** [comment]
Closing in favor of https://github.com/NixOS/nixpkgs/pull/55743

**Pull request closed without merging**
