### PR TITLE
pkgsMusl.ocamlPackages.ocaml: Disable pie hardening on musl

### LINKED ISSUE #124476: pkgsMusl.ocamlPackages.ocaml: -r and -pie may not be used together
It used to be possible to build `ocaml` (it is possible on 20.09), but these days it fails with:
```
$ nix-build -A pkgsMusl.ocamlPackages.ocaml
…
../../ocamlopt.opt -nostdlib -I ../../stdlib -c -for-pack Dynlink_compilerlibs -strict-sequence -principal -absname -w +a-4-9-40-41-42-44-45-48-66 -warn-error A -bin-annot -safe-string -strict-formats -I byte \
          -function-sections -I native -I dynlink_compilerlibs -o dynlink_compilerlibs/cmxs_format.cmx dynlink_compilerlibs/cmxs_format.ml
../../ocamlopt.opt -nostdlib -I ../../stdlib -strict-sequence -principal -absname -w +a-4-9-40-41-42-44-45-48-66 -warn-error A -bin-annot -safe-string -strict-formats -I byte -function-sections -I native -pack -o native/dynlink_compilerlibs.cmx dynlink_compilerlibs/config.cmx dynlink_compilerlibs/build_path_prefix_map.cmx dynlink_compilerlibs/misc.cmx dynlink_compilerlibs/identifiable.cmx dynlink_compilerlibs/numbers.cmx dynlink_compilerlibs/arg_helper.cmx dynlink_compilerlibs/clflags.cmx dynlink_compilerlibs/profile.cmx dynlink_compilerlibs/consistbl.cmx dynlink_compilerlibs/terminfo.cmx dynlink_compilerlibs/warnings.cmx dynlink_compilerlibs/load_path.cmx dynlink_compilerlibs/location.cmx dynlink_compilerlibs/longident.cmx dynlink_compilerlibs/docstrings.cmx dynlink_compilerlibs/syntaxerr.cmx dynlink_compilerlibs/ast_helper.cmx dynlink_compilerlibs/ast_mapper.cmx dynlink_compilerlibs/attr_helper.cmx dynlink_compilerlibs/builtin_attributes.cmx dynlink_compilerlibs/ident.cmx dynlink_compilerlibs/path.cmx dynlink_compilerlibs/primitive.cmx dynlink_compilerlibs/type_immediacy.cmx dynlink_compilerlibs/types.cmx dynlink_compilerlibs/btype.cmx dynlink_compilerlibs/subst.cmx dynlink_compilerlibs/predef.cmx dynlink_compilerlibs/datarepr.cmx dynlink_compilerlibs/cmi_format.cmx dynlink_compilerlibs/persistent_env.cmx dynlink_compilerlibs/env.cmx dynlink_compilerlibs/lambda.cmx dynlink_compilerlibs/runtimedef.cmx dynlink_compilerlibs/instruct.cmx dynlink_compilerlibs/opcodes.cmx dynlink_compilerlibs/bytesections.cmx dynlink_compilerlibs/dll.cmx dynlink_compilerlibs/meta.cmx dynlink_compilerlibs/symtable.cmx dynlink_compilerlibs/asttypes.cmx dynlink_compilerlibs/parsetree.cmx dynlink_compilerlibs/outcometree.cmx dynlink_compilerlibs/cmo_format.cmx dynlink_compilerlibs/cmxs_format.cmx
/nix/store/30kg865p8ixsvblqypmfwzvqx72fglws-binutils-2.35.1/bin/ld: -r and -pie may not be used together
File "/build/ocaml-4.10.2/otherlibs/dynlink/native/dynlink_compilerlibs.cmx", line 1:
Error: Error during partial linking
make[4]: *** [Makefile:193: native/dynlink_compilerlibs.cmx] Error 2
make[4]: Leaving directory '/build/ocaml-4.10.2/otherlibs/dynlink'
make[3]: *** [Makefile:33: allopt] Error 2
make[3]: Leaving directory '/build/ocaml-4.10.2/otherlibs'
make[2]: *** [Makefile:1138: otherlibrariesopt] Error 2
make[2]: Leaving directory '/build/ocaml-4.10.2'
make[1]: *** [Makefile:418: opt.opt] Error 2
make[1]: Leaving directory '/build/ocaml-4.10.2'
make: *** [Makefile:472: world.opt] Error 2
builder for '/nix/store/ksxkzyib6nh9zfhvw8dkr11bn31ywplr-ocaml-4.10.2.drv' failed with exit code 2
```

I’ll try to bisect it…

### PR DESCRIPTION
**Pull request by nomeata**
This was broken since 4e9dc46d, and fixes #124476

### CODE REVIEW

**Comment by nomeata** [comment]
Hmm, this might not be good enough; it seems that now other ocaml packages fails to build. Maybe this needs to be disabled for ocaml on musl in more central way.

**Comment by nomeata** [comment]
Indeed, it seems that this affects all executables that are ocaml build. I fixed a few manually, but is there a way to fix this more widely?

**Comment by veprbl** [comment]
FYI We don't enable pie on non-musl
https://github.com/NixOS/nixpkgs/blob/2ba3a65a7d54264bf387460e6a2cc0f4a9ea70a7/pkgs/stdenv/generic/make-derivation.nix#L112-L120

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]
stdenv.lib is deprecated. Please replace it with lib.

**Comment by nomeata** [comment]
> FYI We don't enable pie on non-musl

So you are saying `pie` is enabled only on musl, and then disabled again in GHC and glibc:
```
~/build/nixpkgs/pkgs $ git grep 'isMusl "pie"'
development/compilers/ghc/8.10.4.nix:  hardeningDisable = [ "format" ] ++ lib.optional stdenv.targetPlatform.isMusl "pie";
development/compilers/ghc/8.8.4.nix:  hardeningDisable = [ "format" ] ++ lib.optional stdenv.targetPlatform.isMusl "pie";
development/compilers/ghc/9.0.1.nix:  hardeningDisable = [ "format" ] ++ lib.optional stdenv.targetPlatform.isMusl "pie";
development/compilers/ghc/head.nix:  hardeningDisable = [ "format" ] ++ lib.optional stdenv.targetPlatform.isMusl "pie";
development/libraries/glibc/default.nix:      ++ lib.optional stdenv.hostPlatform.isMusl "pie";
```

> stdenv.lib is deprecated. Please replace it with lib.

Sorry, of course. I cargo-culted from elsewhere. Fixed.

**Comment by SuperSandro2000** [comment]
Because @vbgl blocked me he got removed while requesting a review from other people. Sorry, not sorry.

**Comment by Mic92** [comment]
I have not understand the issue yet. Is the issue that ocaml build static libraries, which do not work with pie?

**Comment by nomeata** [comment]
The linked issue has the error messages: it seems that without this (or something like this), ocaml programs won't build in pkgsMusl.

**Comment by r-burns** [comment]
Closing as the PIE fixes have hit master and seem to be working well. Feel free to reopen and/or ping me if not

**Pull request closed without merging**
