### PR TITLE
goose: 3.15.0 -> 3.19.2

### PR DESCRIPTION
**Pull request by RaghavSood**
## Description of changes

Bumps goose to the latest version

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by geekodour** [comment]
```
error: builder for '/nix/store/yb727vzx80sc457b4h016d0ww53kkspb-goose-3.19.2.drv' failed with exit code 1;
       last 10 log lines:
       > 2024/04/15 05:32:58 OK   00003_comments_table.sql (10.65ms)
       > 2024/04/15 05:32:58 OK   00002_posts_table.sql (52.94ms)
       > 2024/04/15 05:32:58 OK   00001_users_table.sql (11.82ms)
       > 2024/04/15 05:32:58 Created new file: /build/TestEmbeddedMigrationscreate_uses_os_fs517639883/001/20240415053258_test.sql
       > 2024/04/15 05:32:58 RENAMED 20240415053258_test.sql => 00001_test.sql
       > --- FAIL: TestLockModeAdvisorySession (0.00s)
       >     provider_run_test.go:941: unexpected error: failed to create docker container: dial unix /var/run/docker.sock: connect: no such file or directory
       > FAIL
       > FAIL       github.com/pressly/goose/v3     32.478s
       > FAIL
       For full logs, run 'nix log /nix/store/yb727vzx80sc457b4h016d0ww53kkspb-goose-3.19.2.drv'.
```

Getting this error when trying to build. why is it trying to create a docker container?

**Comment by RaghavSood** [comment]
> ```
> error: builder for '/nix/store/yb727vzx80sc457b4h016d0ww53kkspb-goose-3.19.2.drv' failed with exit code 1;
>        last 10 log lines:
>        > 2024/04/15 05:32:58 OK   00003_comments_table.sql (10.65ms)
>        > 2024/04/15 05:32:58 OK   00002_posts_table.sql (52.94ms)
>        > 2024/04/15 05:32:58 OK   00001_users_table.sql (11.82ms)
>        > 2024/04/15 05:32:58 Created new file: /build/TestEmbeddedMigrationscreate_uses_os_fs517639883/001/20240415053258_test.sql
>        > 2024/04/15 05:32:58 RENAMED 20240415053258_test.sql => 00001_test.sql
>        > --- FAIL: TestLockModeAdvisorySession (0.00s)
>        >     provider_run_test.go:941: unexpected error: failed to create docker container: dial unix /var/run/docker.sock: connect: no such file or directory
>        > FAIL
>        > FAIL       github.com/pressly/goose/v3     32.478s
>        > FAIL
>        For full logs, run 'nix log /nix/store/yb727vzx80sc457b4h016d0ww53kkspb-goose-3.19.2.drv'.
> ```
> 
> Getting this error when trying to build. why is it trying to create a docker container?

I suspect it's trying to run tests that run a DB inside docker - what OS are you on?

Maybe we should disable the tests or patch out the ones that require docker, I'll take a look

**Comment by geekodour** [comment]
```
Linux hq 6.1.72 #1-NixOS SMP PREEMPT_DYNAMIC Wed Jan 10 16:10:37 UTC 2024 x86_64 GNU/Linux
OS: NixOS 23.11.2936.428544ae95ee (Tapir) x86_64
```

> Maybe we should disable the tests or patch out the ones that require docker, I'll take a look

Yes, think we don't need to run the tests when all we want to do is to build the package and run it on our systems

**Comment by geekodour** [comment]
Seems like this docker based test was intentionally added in https://github.com/NixOS/nixpkgs/pull/232485, wonder why

**Pull request merged**
