### PR TITLE
llvmPackages: 5 -> 7 on Linux, keep Darwin at 5 until fixed

### PR DESCRIPTION
**Pull request by dtzWill**
Replaces #39986.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

I've been using 7 as my default for over a month (ea00916ba11510fdf21c116d5204440c80391deb)
and so far so good -- although my usage certainly doesn't cover all packages impacted by this.

### CODE REVIEW

**Comment by dtzWill** [comment]
A miscompilation bug was mentioned on the other PR, it may be wise to check if LLVM 7 contains the fix (although this would mostly impact Darwin).

**Comment by dtzWill** [comment]
Anyone have thoughts -- particularly "please wait"-- on this?

**Comment by LnL7** [comment]
I don't really see a reason to diverge. I would propose to drop libxml2 by default and switch everything or nothing. The darwin builds will also give us a better overview of the impact.

**Comment by LnL7** [comment]
We have to disable (libxml?) on darwin, or just by default to avoid bootstrapping problems.

**Comment by dtzWill** [comment]
Beep boop, ping! O:)

**Review by lheckemann — APPROVED** [review]

**Comment by vcunat** [comment]
I can hardly guess the amount of breakage, but I'd hope almost all will be built-time.  It might be worth creating a separate x86_64-linux -only jobset on Hydra just for this, so that these regressions get separated from others.

**Comment by madjam002** [comment]
Just as an FYI, I tried LLVM 7 with Mesa on NixOS Unstable and I get the following errors when trying games from Steam Proton (might be unrelated):

```
[  551.019500] amdgpu 0000:01:00.0: GPU fault detected: 147 0x09d84401 for process Overcooked.exe pid 5241 thread Overcooked.exe pid 5241
[  551.019504] amdgpu 0000:01:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x0D70013B
[  551.019505] amdgpu 0000:01:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x08044001
[  551.019507] amdgpu 0000:01:00.0: VM fault (0x01, vmid 4, pasid 32774) at page 225444155, read from 'TC5' (0x54433500) (68)
[  562.390204] [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring gfx timeout, signaled seq=55183, emitted seq=55186
```

I'm trying LLVM 7 by using the following (this also could be completely wrong, I'm new to NixOS!):
```
packageOverrides = pkgs: with pkgs.stdenv.lib;
      let
        mesa = ((pkgs.mesa_noglu.override {
          llvmPackages = pkgs.llvmPackages_7;
        }));
      in {
        mesa_drivers = mesa.drivers;
      };
```

```
$ DISPLAY=:0 glxinfo | grep "OpenGL"
OpenGL vendor string: X.Org
OpenGL renderer string: AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.27.0, 4.20.3, LLVM 7.0.1)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.3.1
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.5 (Compatibility Profile) Mesa 18.3.1
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 18.3.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

LLVM 6 works fine.

**Comment by matthewbauer** [comment]
Let's aim for this right after the 19.03 branch off. We still have quite a few things in staging that I am wanting to prioritize.

**Comment by dtzWill** [comment]
Sounds good for me! Thanks for making these calls! o7 (salute)

**Pull request merged**
