### PR TITLE
schildichat: 1.9.0-sc.1 -> 1.9.7-sc.1

### PR DESCRIPTION
**Pull request by yu-re-ka**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by pstn** [comment]
Result of `nixpkgs-review pr 150562` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>                                                                                            
  <summary>3 packages built:</summary>                                                               
  <ul>                                                                                               
    <li>schildichat-desktop</li>                                                                     
    <li>schildichat-desktop-wayland</li>                                                             
    <li>schildichat-web</li>                                                                         
  </ul>                                                                                              
</details>

**Comment by sumnerevans** [comment]
Hmm... failing for me...

Result of `nixpkgs-review pr 150562` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>schildichat-desktop</li>
    <li>schildichat-desktop-wayland</li>
    <li>schildichat-web</li>
  </ul>
</details>

**Comment by yu-re-ka** [comment]
I think it might be a flaky download. It worked for me on the second try. Do you have logs?

**Comment by sumnerevans** [comment]
```
$ nix-shell -p nixpkgs-review --run "nixpkgs-review pr 150562"
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/150562/head:refs/nixpkgs-review/1
$ git worktree add /home/sumner/.cache/nixpkgs-review/pr-150562-1/nixpkgs c152cb71e182068a83b22a7bbea5bf19bfae6eb6
Preparing worktree (detached HEAD c152cb71e18)
Updating files: 100% (29240/29240), done.
HEAD is now at c152cb71e18 Merge pull request #150266 from r-ryantm/auto-update/cargo-feature
$ git merge --no-commit --no-ff 127a5753d338663f25ec04de7b84fe066d80f57e
Automatic merge went well; stopped before committing as requested
$ nix --experimental-features nix-command build --no-link --keep-going --option build-use-sandbox relaxed -f /home/sumner/.cache/nixpkgs-review/pr-150562-1/build.nix
error: builder for '/nix/store/n29sfb6iqia2ks0vbk6zxz1sll2lk948-schildichat-desktop.drv' failed with exit code 1;
       last 10 log lines:
       > Switched to a new branch 'fetchgit'
       > Submodule 'element-desktop' (https://github.com/SchildiChat/element-desktop.git) registered for path 'element-desktop'
       > Submodule 'element-web' (https://github.com/SchildiChat/element-web.git) registered for path 'element-web'
       > Submodule 'matrix-js-sdk' (https://github.com/SchildiChat/matrix-js-sdk.git) registered for path 'matrix-js-sdk'
       > Submodule 'matrix-react-sdk' (https://github.com/SchildiChat/matrix-react-sdk.git) registered for path 'matrix-react-sdk'
       > Initialized empty Git repository in /nix/store/nwiwb17ls090syjn3h9pgjd0m7kx2bcv-schildichat-desktop/element-desktop/.git/
       > fatal: unable to access 'https://github.com/SchildiChat/element-desktop.git/': Could not resolve host: github.com
       > fatal: unable to access 'https://github.com/SchildiChat/element-desktop.git/': Could not resolve host: github.com
       > fatal: unable to access 'https://github.com/SchildiChat/element-desktop.git/': Could not resolve host: github.com
       > Unable to checkout a074ede0c13c09dca96a9be2c60d3c4e5c03a234 from https://github.com/SchildiChat/element-desktop.git.
       For full logs, run 'nix log /nix/store/n29sfb6iqia2ks0vbk6zxz1sll2lk948-schildichat-desktop.drv'.
error: 1 dependencies of derivation '/nix/store/pcd4d7icxk1js30zyahhjrg9mqv5m4vm-offline.drv' failed to build
error: 1 dependencies of derivation '/nix/store/xllqzy5r1xp56vva8kmmpmbgid7wf5qy-offline.drv' failed to build
error: 2 dependencies of derivation '/nix/store/vzpi3b4racmz6c9yrivljbrxnb9dsd4w-schildichat-web-1.9.7-sc.1.drv' failed to build
error: 3 dependencies of derivation '/nix/store/15alr3h97vy436gy21lsdckrjj33av6q-schildichat-desktop-1.9.7-sc.1.drv' failed to build
error: 3 dependencies of derivation '/nix/store/cxvk06ssq6s1nya5ks0jq56d66mwfz6l-schildichat-desktop-1.9.7-sc.1.drv' failed to build
error: 3 dependencies of derivation '/nix/store/gcpjp79x33r537v5bgnq8fn0djzzri1s-review-shell.drv' failed to build

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/150562

3 packages failed to build:
schildichat-desktop schildichat-desktop-wayland schildichat-web

error: build log of '/nix/store/15alr3h97vy436gy21lsdckrjj33av6q-schildichat-desktop-1.9.7-sc.1.drv' is not available
error: build log of '/nix/store/5kxjvlq368w39m6v6xqpvc5yqkmpzi5j-schildichat-desktop-1.9.7-sc.1' is not available
error: build log of '/nix/store/cxvk06ssq6s1nya5ks0jq56d66mwfz6l-schildichat-desktop-1.9.7-sc.1.drv' is not available
error: build log of '/nix/store/4cb9is4cs5q58nwpdlm5zrlfvfbwvwhi-schildichat-desktop-1.9.7-sc.1' is not available
error: build log of '/nix/store/vzpi3b4racmz6c9yrivljbrxnb9dsd4w-schildichat-web-1.9.7-sc.1.drv' is not available
error: build log of '/nix/store/741ca794896kk8nf8cwzq4fyzd3lvv0x-schildichat-web-1.9.7-sc.1' is not available
```

**Review by fpletz — APPROVED** [review]

**Comment by 0x4A6F** [comment]
`Could not resolve host: github.com` -> transient problem for @sumnerevans 

Diff looks good, schildichat-desktop works.
LGTM.

**Comment by yu-re-ka** [comment]
SchildiChat is not packaged in 21.05

**Pull request merged**
