### PR TITLE
wio: Build with wlroots 0.13

### PR DESCRIPTION
**Pull request by primeos**
###### Motivation for this change

I thought I'd give this a try and it was easier than expected but I only performed the necessary changes to fix the build and one segfault so it could still be missing something. Anyway, according to my basic testing it's fine. It doesn't work when running it from a virtual console but that also didn't work before this change. https://lists.sr.ht/~sircmpwn/wio/patches/15055 might fix that.

I've explained my changes in more details here: https://git.sr.ht/~primeos/wio/commit/f90a473d8dc4fc3d714810eb5a66b8557e9b9ee2

I was about to send this to the ML for review/feedback but I realized that the relevant changes where already submitted (with minor differences):
- https://lists.sr.ht/~sircmpwn/wio/patches/22364
- https://lists.sr.ht/~sircmpwn/wio/patches/22363

Not sure how to proceed here (the patch is unfortunately quite large due to the `wlr-layer-shell-unstable-v1.xml` change (which we could fetch from wlroots) so we could also fetch the existing patches from the ML, my commit from the link above - and it might be a good idea to mention on the ML that the build is currently broken with wlroots 0.13).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AndersonTorres** [comment]
Do you plan to upstream this patch?

**Comment by primeos** [comment]
@AndersonTorres see above (PR description) ;)

**Comment by AndersonTorres** [comment]
I need to read more before asking :)

LGTM

**Comment by primeos** [comment]
@AndersonTorres FYI: I eventually posted to the ML and Drew replied that the status of wio is: "Abandoned, you should fork it." ([source](https://lists.sr.ht/~sircmpwn/wio/%3CYLEcGabBxsoopxgY%40jarvis.primeos.dev%3E#%3CCBP0Z8B62KV8.2MPY6PPGZTG9M@taiga%3E=)).

wio will likely require changes again once wlroots 0.14 gets released so we might want to eventually drop this Nixpkgs package, at least if no one wants to actively maintain a proper fork.

**Comment by AndersonTorres** [comment]
Maybe **I** should fork it, even if the only purpose is maintain it for posterity...

**Comment by primeos** [comment]
Yes, there's a mailing list (https://lists.sr.ht/~sircmpwn/wio) but it looks like you already found it :)
https://lists.sr.ht/~sircmpwn/wio/patches/15055 is likely also interesting but I didn't test it.
I would also recommend subscribing to the mailing list and announcing your fork there.

**Pull request merged**
