### PR TITLE
nodePackages.node2nix: backport patch to reduce derivation sizes

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change
Backport https://github.com/svanderburg/node2nix/pull/255 to reduce derivation sizes and regenerate nodePackages to benefit from that change.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
```
❯ nix-build pkgs/top-level/release.nix -A tarball.nixpkgs-basic-release-checks --arg supportedSystems '[ "aarch64-darwin" "aarch64-linux" "x86_64-linux" "x86_64-darwin"  ]'
this derivation will be built:
  /nix/store/56znv078bh2zl4rsn2nzh94kmxkmnccl-nixpkgs-release-checks.drv
building '/nix/store/56znv078bh2zl4rsn2nzh94kmxkmnccl-nixpkgs-release-checks.drv' on 'ssh://hexa@phoibe.cysec.de'...
copying 0 paths...
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
checking Nixpkgs on aarch64-darwin
checking Nixpkgs on aarch64-linux
checking Nixpkgs on x86_64-linux
checking Nixpkgs on x86_64-darwin
copying 1 paths...
copying path '/nix/store/hhidjacyjh6lq9f58wqqkb91qgj4rya8-nixpkgs-release-checks' from 'ssh://hexa@phoibe.cysec.de'...
/nix/store/hhidjacyjh6lq9f58wqqkb91qgj4rya8-nixpkgs-release-checks
```

Basic release checks WFM.

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 142319` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages marked as broken and skipped:</summary>
  <ul>
    <li>hyperspace-cli</li>
    <li>remarkjs</li>
    <li>teleprompter</li>
    <li>timedoctor</li>
    <li>vimPlugins.coc-imselect</li>
  </ul>
</details>
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>tests.writers</li>
  </ul>
</details>
<details>
  <summary>13 packages failed to build:</summary>
  <ul>
    <li>fast-cli</li>
    <li>lumo</li>
    <li>python39Packages.batchspawner</li>
    <li>python39Packages.dockerspawner</li>
    <li>python39Packages.jupyterhub</li>
    <li>python39Packages.jupyterhub-ldapauthenticator</li>
    <li>python39Packages.jupyterhub-systemdspawner</li>
    <li>python39Packages.jupyterhub-tmpauthenticator</li>
    <li>python39Packages.oauthenticator</li>
    <li>reveal-md</li>
    <li>sage</li>
    <li>sageWithDoc</li>
    <li>teck-programmer</li>
  </ul>
</details>
<details>
  <summary>146 packages built:</summary>
  <ul>
    <li>airfield</li>
    <li>antora</li>
    <li>balanceofsatoshis</li>
    <li>base16-builder</li>
    <li>bat-extras.prettybat</li>
    <li>bitwarden-cli</li>
    <li>botamusique</li>
    <li>castnow</li>
    <li>commitizen</li>
    <li>commitlint</li>
    <li>concurrently</li>
    <li>create-cycle-app</li>
    <li>cryptpad</li>
    <li>deltachat-desktop</li>
    <li>discourse</li>
    <li>discourseAllPlugins</li>
    <li>elmPackages.create-elm-app</li>
    <li>elmPackages.elm-analyse</li>
    <li>elmPackages.elm-coverage</li>
    <li>elmPackages.elm-doc-preview</li>
    <li>elmPackages.elm-language-server</li>
    <li>elmPackages.elm-live</li>
    <li>elmPackages.elm-optimize-level-2</li>
    <li>elmPackages.elm-review</li>
    <li>elmPackages.elm-test</li>
    <li>elmPackages.elm-upgrade</li>
    <li>elmPackages.elm-verify-examples</li>
    <li>elmPackages.elm-xref</li>
    <li>emojione</li>
    <li>epgstation</li>
    <li>flexoptix-app</li>
    <li>flood</li>
    <li>fx</li>
    <li>google-clasp</li>
    <li>gtop</li>
    <li>hueadm</li>
    <li>image_optim</li>
    <li>imapnotify</li>
    <li>imgbrd-grabber</li>
    <li>iosevka</li>
    <li>isso</li>
    <li>jellyfin</li>
    <li>jellyfin-web</li>
    <li>joplin</li>
    <li>ldgallery</li>
    <li>lessc</li>
    <li>mastodon-bot</li>
    <li>matrix-appservice-irc</li>
    <li>matrix-appservice-slack</li>
    <li>mx-puppet-discord</li>
    <li>n8n</li>
    <li>nixui</li>
    <li>odoo</li>
    <li>oni2</li>
    <li>onlykey</li>
    <li>openmoji-black</li>
    <li>openmoji-color</li>
    <li>parity-ui</li>
    <li>peertube</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>prometheus</li>
    <li>pscid</li>
    <li>pulp</li>
    <li>purescript-psa</li>
    <li>pyright</li>
    <li>python38Packages.batchspawner</li>
    <li>python38Packages.dockerspawner</li>
    <li>python38Packages.jupyterhub</li>
    <li>python38Packages.jupyterhub-ldapauthenticator</li>
    <li>python38Packages.jupyterhub-systemdspawner</li>
    <li>python38Packages.jupyterhub-tmpauthenticator</li>
    <li>python38Packages.oauthenticator</li>
    <li>redoc-cli</li>
    <li>shepherd</li>
    <li>shout</li>
    <li>slack</li>
    <li>sloc</li>
    <li>spacegun</li>
    <li>styx</li>
    <li>teams</li>
    <li>thelounge</li>
    <li>triton</li>
    <li>uchiwa</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vimPlugins.coc-clangd</li>
    <li>vimPlugins.coc-cmake</li>
    <li>vimPlugins.coc-css</li>
    <li>vimPlugins.coc-diagnostic</li>
    <li>vimPlugins.coc-emmet</li>
    <li>vimPlugins.coc-eslint</li>
    <li>vimPlugins.coc-explorer</li>
    <li>vimPlugins.coc-git</li>
    <li>vimPlugins.coc-go</li>
    <li>vimPlugins.coc-highlight</li>
    <li>vimPlugins.coc-html</li>
    <li>vimPlugins.coc-java</li>
    <li>vimPlugins.coc-jest</li>
    <li>vimPlugins.coc-json</li>
    <li>vimPlugins.coc-lists</li>
    <li>vimPlugins.coc-markdownlint</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-pairs</li>
    <li>vimPlugins.coc-prettier</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-python</li>
    <li>vimPlugins.coc-r-lsp</li>
    <li>vimPlugins.coc-rls</li>
    <li>vimPlugins.coc-rust-analyzer</li>
    <li>vimPlugins.coc-smartf</li>
    <li>vimPlugins.coc-snippets</li>
    <li>vimPlugins.coc-solargraph</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-tabnine</li>
    <li>vimPlugins.coc-texlab</li>
    <li>vimPlugins.coc-tslint</li>
    <li>vimPlugins.coc-tslint-plugin</li>
    <li>vimPlugins.coc-tsserver</li>
    <li>vimPlugins.coc-ultisnips</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vimPlugins.coc-vimlsp</li>
    <li>vimPlugins.coc-vimtex</li>
    <li>vimPlugins.coc-wxml</li>
    <li>vimPlugins.coc-yaml</li>
    <li>vimPlugins.coc-yank</li>
    <li>vimPlugins.markdown-preview-nvim</li>
    <li>vscode</li>
    <li>vscode-extensions.matklad.rust-analyzer</li>
    <li>vscode-extensions.ms-python.vscode-pylance</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
    <li>vscode-fhs</li>
    <li>vscode-with-extensions</li>
    <li>vscodium</li>
    <li>vscodium-fhs</li>
    <li>wasm-strip</li>
    <li>wasm-text-gen</li>
    <li>wast-refmt</li>
    <li>webassemblyjs-cli</li>
    <li>webassemblyjs-repl</li>
    <li>whalebird</li>
    <li>whitebophir</li>
    <li>wring</li>
    <li>yaml-language-server</li>
    <li>ycmd</li>
    <li>zerobin</li>
    <li>zx</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
Tested the following builds manually:

- [x] sage
- [x] reavel-md
- [x] lumo
- [x] fast-cli
- [x] python3Packages.jupyterhub :x: 
  - [x] python3Packages.batchspawner
  - [x] python3Packages.dockerspawner
  - [x] python39Packages.jupyterhub-ldapauthenticator
  - [x] python39Packages.jupyterhub-systemdspawner
  - [x] python39Packages.jupyterhub-tmpauthenticator
- [x] python3Packages.oauthenticator

So … flaky nixpkgs-review. This PR is ready IMO.

**Review by Artturin — APPROVED** [review]
code-wise lgtm

**Comment by happysalada** [comment]
It looks good to me too. I'm running a nixpkgs-review on darwin just in case. Feel free to merge anytime if you fear conflicts with the main branch though.

**Comment by thefloweringash** [comment]
Thanks for integrating this!

Not necessarily a problem, but I'm looking at the remaining instances of `node-env.nix` (excluding the common instance at `pkgs/development/node-packages/node-env.nix`).

In this PR, there are places where the `writeShellScript` has been added to a local copy of `node-env.nix` and its caller, but without the changes to `node-env.nix` that require it, for example, `zigbee2mqtt` and `isso`. And the looking through the nixpkgs, a case of a local `node-env.nix` without this change in `mjolnir`.

I hope all of the `node-env.nix` consumers in nixpkgs can use the single shared instance, but there might be some traps so I'm happy to consider that out of scope for now. However, some the changes in "treewide: pass and inherit writeShellScript in node2nix packages" that add an unused argument seem unnecessary. Is there a reason to add it here?

As a sanity check, looking at the instances of `writeShellScript` in the various `node-env.nix` files shows that only `node-packages` and `commitizen` make use of it.
```
$ find . -name node-env.nix | xargs grep -e writeShellScript
```

**Comment by thefloweringash** [comment]
I mean to remove it from the node-env.nix and the node.nix

```
❯ git diff | cat
diff --git a/pkgs/servers/zigbee2mqtt/node-env.nix b/pkgs/servers/zigbee2mqtt/node-env.nix
index 1d21b22f873..9af216ad1df 100644
--- a/pkgs/servers/zigbee2mqtt/node-env.nix
+++ b/pkgs/servers/zigbee2mqtt/node-env.nix
@@ -1,6 +1,6 @@
 # This file originates from node2nix

-{lib, stdenv, nodejs, python2, util-linux, libtool, runCommand, writeTextFile, writeShellScript}:
+{lib, stdenv, nodejs, python2, util-linux, libtool, runCommand, writeTextFile}:

 let
   python = if nodejs ? python then nodejs.python else python2;
diff --git a/pkgs/servers/zigbee2mqtt/node.nix b/pkgs/servers/zigbee2mqtt/node.nix
index 7cef1ef8cfe..0769168a78f 100644
--- a/pkgs/servers/zigbee2mqtt/node.nix
+++ b/pkgs/servers/zigbee2mqtt/node.nix
@@ -6,7 +6,7 @@

 let
   nodeEnv = import ./node-env.nix {
-    inherit (pkgs) lib stdenv python2 util-linux runCommand writeTextFile writeShellScript;
+    inherit (pkgs) lib stdenv python2 util-linux runCommand writeTextFile;
     inherit nodejs;
     libtool = if pkgs.stdenv.isDarwin then pkgs.darwin.cctools else null;
   };
❯ nix-instantiate --argstr system x86_64-linux -A zigbee2mqtt
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
/nix/store/cq5w0nbpivwmhy4fgf562w4276ghpvlg-node_zigbee2mqtt-1.16.2.drv
```

**Comment by mweinelt** [comment]
Oh, yeah. That makes total sense. Let me try and remedy that.

**Review by SuperSandro2000 — APPROVED** [review]
Thanks hexa! ❤️

**Comment by mweinelt** [comment]
Resolved.

**Review by thefloweringash — APPROVED** [review]
LGTM

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by mweinelt** [comment]
*(nixpkgs-review is building chrome right now...)*

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 142319` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages marked as broken and skipped:</summary>
  <ul>
    <li>hyperspace-cli</li>
    <li>remarkjs</li>
    <li>teleprompter</li>
    <li>timedoctor</li>
    <li>vimPlugins.coc-imselect</li>
  </ul>
</details>
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>tests.writers</li>
  </ul>
</details>
<details>
  <summary>1 packages failed to build:</summary>
  <ul>
    <li>teck-programmer</li>
  </ul>
</details>
<details>
  <summary>157 packages built:</summary>
  <ul>
    <li>airfield</li>
    <li>antora</li>
    <li>balanceofsatoshis</li>
    <li>base16-builder</li>
    <li>bat-extras.prettybat</li>
    <li>bitwarden-cli</li>
    <li>botamusique</li>
    <li>castnow</li>
    <li>commitizen</li>
    <li>commitlint</li>
    <li>concurrently</li>
    <li>create-cycle-app</li>
    <li>cryptpad</li>
    <li>deltachat-desktop</li>
    <li>discourse</li>
    <li>discourseAllPlugins</li>
    <li>elmPackages.create-elm-app</li>
    <li>elmPackages.elm-analyse</li>
    <li>elmPackages.elm-coverage</li>
    <li>elmPackages.elm-doc-preview</li>
    <li>elmPackages.elm-language-server</li>
    <li>elmPackages.elm-live</li>
    <li>elmPackages.elm-optimize-level-2</li>
    <li>elmPackages.elm-review</li>
    <li>elmPackages.elm-test</li>
    <li>elmPackages.elm-upgrade</li>
    <li>elmPackages.elm-verify-examples</li>
    <li>elmPackages.elm-xref</li>
    <li>emojione</li>
    <li>epgstation</li>
    <li>fast-cli</li>
    <li>flexoptix-app</li>
    <li>flood</li>
    <li>fx</li>
    <li>google-clasp</li>
    <li>gtop</li>
    <li>hueadm</li>
    <li>image_optim</li>
    <li>imapnotify</li>
    <li>imgbrd-grabber</li>
    <li>iosevka</li>
    <li>jellyfin</li>
    <li>jellyfin-web</li>
    <li>joplin</li>
    <li>ldgallery</li>
    <li>lessc</li>
    <li>lumo</li>
    <li>mastodon-bot</li>
    <li>matrix-appservice-irc</li>
    <li>matrix-appservice-slack</li>
    <li>mx-puppet-discord</li>
    <li>n8n</li>
    <li>nixui</li>
    <li>odoo</li>
    <li>oni2</li>
    <li>onlykey</li>
    <li>openmoji-black</li>
    <li>openmoji-color</li>
    <li>parity-ui</li>
    <li>peertube</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>prometheus</li>
    <li>pscid</li>
    <li>pulp</li>
    <li>purescript-psa</li>
    <li>pyright</li>
    <li>python38Packages.batchspawner</li>
    <li>python38Packages.dockerspawner</li>
    <li>python38Packages.jupyterhub</li>
    <li>python38Packages.jupyterhub-ldapauthenticator</li>
    <li>python38Packages.jupyterhub-systemdspawner</li>
    <li>python38Packages.jupyterhub-tmpauthenticator</li>
    <li>python38Packages.oauthenticator</li>
    <li>python39Packages.batchspawner</li>
    <li>python39Packages.dockerspawner</li>
    <li>python39Packages.jupyterhub</li>
    <li>python39Packages.jupyterhub-ldapauthenticator</li>
    <li>python39Packages.jupyterhub-systemdspawner</li>
    <li>python39Packages.jupyterhub-tmpauthenticator</li>
    <li>python39Packages.oauthenticator</li>
    <li>redoc-cli</li>
    <li>reveal-md</li>
    <li>sage</li>
    <li>sageWithDoc</li>
    <li>shepherd</li>
    <li>shout</li>
    <li>slack</li>
    <li>sloc</li>
    <li>spacegun</li>
    <li>styx</li>
    <li>teams</li>
    <li>thelounge</li>
    <li>triton</li>
    <li>uchiwa</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vimPlugins.coc-clangd</li>
    <li>vimPlugins.coc-cmake</li>
    <li>vimPlugins.coc-css</li>
    <li>vimPlugins.coc-diagnostic</li>
    <li>vimPlugins.coc-emmet</li>
    <li>vimPlugins.coc-eslint</li>
    <li>vimPlugins.coc-explorer</li>
    <li>vimPlugins.coc-git</li>
    <li>vimPlugins.coc-go</li>
    <li>vimPlugins.coc-highlight</li>
    <li>vimPlugins.coc-html</li>
    <li>vimPlugins.coc-java</li>
    <li>vimPlugins.coc-jest</li>
    <li>vimPlugins.coc-json</li>
    <li>vimPlugins.coc-lists</li>
    <li>vimPlugins.coc-markdownlint</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-pairs</li>
    <li>vimPlugins.coc-prettier</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-python</li>
    <li>vimPlugins.coc-r-lsp</li>
    <li>vimPlugins.coc-rls</li>
    <li>vimPlugins.coc-rust-analyzer</li>
    <li>vimPlugins.coc-smartf</li>
    <li>vimPlugins.coc-snippets</li>
    <li>vimPlugins.coc-solargraph</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-tabnine</li>
    <li>vimPlugins.coc-texlab</li>
    <li>vimPlugins.coc-tslint</li>
    <li>vimPlugins.coc-tslint-plugin</li>
    <li>vimPlugins.coc-tsserver</li>
    <li>vimPlugins.coc-ultisnips</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vimPlugins.coc-vimlsp</li>
    <li>vimPlugins.coc-vimtex</li>
    <li>vimPlugins.coc-wxml</li>
    <li>vimPlugins.coc-yaml</li>
    <li>vimPlugins.coc-yank</li>
    <li>vimPlugins.markdown-preview-nvim</li>
    <li>vscode</li>
    <li>vscode-extensions.matklad.rust-analyzer</li>
    <li>vscode-extensions.ms-python.vscode-pylance</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
    <li>vscode-fhs</li>
    <li>vscode-with-extensions</li>
    <li>vscodium</li>
    <li>vscodium-fhs</li>
    <li>wasm-strip</li>
    <li>wasm-text-gen</li>
    <li>wast-refmt</li>
    <li>webassemblyjs-cli</li>
    <li>webassemblyjs-repl</li>
    <li>whalebird</li>
    <li>whitebophir</li>
    <li>wring</li>
    <li>yaml-language-server</li>
    <li>ycmd</li>
    <li>zerobin</li>
    <li>zx</li>
  </ul>
</details>

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 142319` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>21 packages marked as broken and skipped:</summary>
  <ul>
    <li>bat-extras.prettybat</li>
    <li>fast-cli</li>
    <li>hyperspace-cli</li>
    <li>nixui</li>
    <li>odoo</li>
    <li>oni2</li>
    <li>python38Packages.batchspawner</li>
    <li>python38Packages.dockerspawner</li>
    <li>python38Packages.jupyterhub</li>
    <li>python38Packages.jupyterhub-ldapauthenticator</li>
    <li>python38Packages.jupyterhub-systemdspawner</li>
    <li>python38Packages.jupyterhub-tmpauthenticator</li>
    <li>python38Packages.oauthenticator</li>
    <li>python39Packages.batchspawner</li>
    <li>python39Packages.dockerspawner</li>
    <li>python39Packages.jupyterhub</li>
    <li>python39Packages.jupyterhub-ldapauthenticator</li>
    <li>python39Packages.jupyterhub-systemdspawner</li>
    <li>python39Packages.jupyterhub-tmpauthenticator</li>
    <li>python39Packages.oauthenticator</li>
    <li>vimPlugins.coc-imselect</li>
  </ul>
</details>
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>tests.writers</li>
  </ul>
</details>
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>lumo</li>
    <li>spacegun</li>
    <li>teck-programmer</li>
  </ul>
</details>
<details>
  <summary>106 packages built:</summary>
  <ul>
    <li>antora</li>
    <li>balanceofsatoshis</li>
    <li>base16-builder</li>
    <li>bitwarden-cli</li>
    <li>botamusique</li>
    <li>castnow</li>
    <li>commitizen</li>
    <li>commitlint</li>
    <li>concurrently</li>
    <li>create-cycle-app</li>
    <li>cryptpad</li>
    <li>deltachat-desktop</li>
    <li>elmPackages.elm-analyse</li>
    <li>elmPackages.elm-coverage</li>
    <li>elmPackages.elm-doc-preview</li>
    <li>elmPackages.elm-live</li>
    <li>elmPackages.elm-upgrade</li>
    <li>elmPackages.elm-xref</li>
    <li>epgstation</li>
    <li>flood</li>
    <li>fx</li>
    <li>google-clasp</li>
    <li>gtop</li>
    <li>hueadm</li>
    <li>image_optim</li>
    <li>imapnotify</li>
    <li>iosevka</li>
    <li>joplin</li>
    <li>ldgallery</li>
    <li>lessc</li>
    <li>mastodon-bot</li>
    <li>matrix-appservice-irc</li>
    <li>matrix-appservice-slack</li>
    <li>mx-puppet-discord</li>
    <li>openmoji-black</li>
    <li>openmoji-color</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>prometheus</li>
    <li>pscid</li>
    <li>pulp</li>
    <li>purescript-psa</li>
    <li>pyright</li>
    <li>redoc-cli</li>
    <li>reveal-md</li>
    <li>shepherd</li>
    <li>shout</li>
    <li>sloc</li>
    <li>styx</li>
    <li>thelounge</li>
    <li>triton</li>
    <li>uchiwa</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vimPlugins.coc-clangd</li>
    <li>vimPlugins.coc-cmake</li>
    <li>vimPlugins.coc-css</li>
    <li>vimPlugins.coc-diagnostic</li>
    <li>vimPlugins.coc-emmet</li>
    <li>vimPlugins.coc-eslint</li>
    <li>vimPlugins.coc-explorer</li>
    <li>vimPlugins.coc-git</li>
    <li>vimPlugins.coc-go</li>
    <li>vimPlugins.coc-highlight</li>
    <li>vimPlugins.coc-html</li>
    <li>vimPlugins.coc-java</li>
    <li>vimPlugins.coc-jest</li>
    <li>vimPlugins.coc-json</li>
    <li>vimPlugins.coc-lists</li>
    <li>vimPlugins.coc-markdownlint</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-pairs</li>
    <li>vimPlugins.coc-prettier</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-python</li>
    <li>vimPlugins.coc-r-lsp</li>
    <li>vimPlugins.coc-rls</li>
    <li>vimPlugins.coc-rust-analyzer</li>
    <li>vimPlugins.coc-smartf</li>
    <li>vimPlugins.coc-snippets</li>
    <li>vimPlugins.coc-solargraph</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-tabnine</li>
    <li>vimPlugins.coc-texlab</li>
    <li>vimPlugins.coc-tslint</li>
    <li>vimPlugins.coc-tslint-plugin</li>
    <li>vimPlugins.coc-tsserver</li>
    <li>vimPlugins.coc-ultisnips</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vimPlugins.coc-vimlsp</li>
    <li>vimPlugins.coc-vimtex</li>
    <li>vimPlugins.coc-wxml</li>
    <li>vimPlugins.coc-yaml</li>
    <li>vimPlugins.coc-yank</li>
    <li>vscode-extensions.matklad.rust-analyzer</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
    <li>wasm-strip</li>
    <li>wasm-text-gen</li>
    <li>wast-refmt</li>
    <li>webassemblyjs-cli</li>
    <li>webassemblyjs-repl</li>
    <li>whitebophir</li>
    <li>wring</li>
    <li>yaml-language-server</li>
    <li>ycmd</li>
    <li>zerobin</li>
    <li>zx</li>
  </ul>
</details>

**Pull request merged**
