### PR TITLE
cloud-utils: 0.27 -> 0.29

### LINKED ISSUE #15736: cloud-utils: depends on sed being available as gnused
## Issue description

[cloud-utils](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/misc/cloud-utils/default.nix) depends on the `gnused` binary being in `$PATH`, but stdenv has sed as just `sed`.
### Steps to reproduce

```
$ nix-shell -p cloud-utils
$ growpart /dev/sda 1
# I assume this fails, reported by jeaye on IRC
```

Or just:

```
$ nix-shell -p cloud-utils --run 'gnused --version'
/run/user/1000/nix-shell.x2PKAC/rc: line 1: gnused: command not found
```
## Technical details
- System: (NixOS: 16.03)
- Nix version: 1.11.2
- Nixpkgs version: unstable and master
## Cause and proposed solution

In `buildPhase`, use of `sed` is replaced by `gnused` [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/misc/cloud-utils/default.nix#L14). I traced that code back to [this commit](https://github.com/NixOS/nixpkgs/commit/044a24e58bcf4cf48df02df936c542839fb08d90) which also includes [this line](https://github.com/NixOS/nixpkgs/commit/044a24e58bcf4cf48df02df936c542839fb08d90#diff-657f0a66367fa9a3b575d28f508a3e62R26) making sed available as `gnused`, but these are now separated in the codebase.

In [amazon-grow-partition](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/amazon-grow-partition.nix), cloud-utils is used in the original context (in initrd) where `gnused` is still explicitely made available, but of course this doesn't hold when using cloud-utils elsewhere.

It was mentioned on IRC by clever that using absolute paths instead of relying on PATH here would perhaps mess with the closure size of the initrd.

### PR DESCRIPTION
**Pull request by jokogr**
###### Motivation for this change

Package update.

Fixes #15736
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
Looks like the `sed` replacement got too much:

```
debug 1 "WARN: disk is larger than 2TB. additional space will go unu/nix/store/r3m6xxf11rr65pyvfjslvj8lawpxjwi0-gnused-4.2.2/bin/sed."
```

Otherwise seems to work.

Unrelated to this PR: A bit weird we only expose growpart I think, when the upstream package provides several more.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nixos/nixpkgs/17015#-:-KMpKhV5vGxVZDH_tcfs:1466609322)*

**Comment by domenkozar** [comment]
I wonder if these references work in initrd, we still have to test an actual ami file to be sure this works.

**Comment by jokogr** [comment]
@domenkozar I do not have AWS access, so I can not test this. AFAIK, initrd takes place before mounting the root partition, so my impression is that it would not work like that.

As I mentioned (previously)[https://github.com/NixOS/nixpkgs/pull/15737], I have verified the execution of `growpart` at ~okeanos, a cloud service for the Greek Research and Academic Community, by explicitly installing the cloud-utils package. I had a 2 GB image of NixOS and extended it manually to 40 GB there.

**Comment by obadz** [comment]
I think @grahamc's comment regarding overly aggressive string substitutions needs to be addressed before merging.

**Comment by garbas** [comment]
@jokogr ping

**Comment by jokogr** [comment]
@grahamc could you mention how you got this message? As I said, I have tried this over a 2 **G**B (not TB) image of nixos-unstable installation and it worked as intended, the image expanded to 40 GB.

@domenkozar let me know how you embed cloud-utils in initrd, so that I could try it on my cloud infrastructure.

**Comment by Mic92** [comment]
any updates?

**Comment by grahamc** [comment]
Hi @jokogr, sorry for dropping the ball on this. The issue I was identifying is it incorrectly replaced:

```
debug 1 "WARN: disk is larger than 2TB. additional space will go unused."
```

with:

```
debug 1 "WARN: disk is larger than 2TB. additional space will go unu/nix/store/r3m6xxf11rr65pyvfjslvj8lawpxjwi0-gnused-4.2.2/bin/sed."
``

**Comment by grahamc** [comment]
After this patch:

```
# nix-shell -I nixpkgs=$(pwd) -p cloud-utils --pure

[nix-shell:~/nixpkgs]$ growpart /dev/xvda 1
FAILED: sfdisk not found
```

Looks like more to fix. Note: sfdisk is in util-linux.

**Comment by grahamc** [comment]
A bit more effort got me to this diff:

```diff
diff --git a/pkgs/tools/misc/cloud-utils/default.nix b/pkgs/tools/misc/cloud-utils/default.nix
index 8bba00b..1200196 100644
--- a/pkgs/tools/misc/cloud-utils/default.nix
+++ b/pkgs/tools/misc/cloud-utils/default.nix
@@ -1,4 +1,4 @@
-{ stdenv, fetchurl }:
+{ stdenv, fetchurl, utillinux, substituteAll, gawk, gnused }:
 
 stdenv.mkDerivation {
   name = "cloud-utils-0.27";
@@ -10,9 +10,11 @@ stdenv.mkDerivation {
   buildPhase = ''
     mkdir -p $out/bin
     cp bin/growpart $out/bin/growpart
-    sed -i 's|awk|gawk|' $out/bin/growpart
-    sed -i 's|sed|gnused|' $out/bin/growpart
-  '';
+    substituteInPlace $out/bin/growpart --replace "awk " "${gawk}/bin/gawk "
+    substituteInPlace $out/bin/growpart --replace "sed " "${gnused}/bin/sed "
+    substituteInPlace $out/bin/growpart --replace "sfdisk " "${utillinux}/bin/sfdisk "
+  ' ';
   dontInstall = true;
   dontPatchShebangs = true;
```

but I think a better solution here is to make a wrapper to put these utilities in the PATH.

Still getting problems like this:

```diff
< 				[ -z "${PART}" ] || fail "confused by arg ${cur}"
---
> 				[ -z "${PART}" ] || fail "confu/nix/store/n62975gpkckivvxvlhg9hjfknspxnkkm-gnused-4.2.2/bin/sed by arg ${cur}"
```

**Comment by grahamc** [comment]
Also, my attempts were not successful:

```
[root@ip-172-30-0-51:~/nixpkgs]# ./result//bin/growpart /dev/xvda 1
attempt to resize /dev/xvda failed. /nix/store/1sf1hnv3kw5jrjp0v8i9bdzrfw8rqbnl-util-linux-2.28.1-bin/bin/sfdisk output below:
| Backup files:
|          MBR (offset     0, size   512): /tmp/growpart.TqYf6I/backup-xvda-0x00000000.bak
| 
| Disk /dev/xvda: 7 GiB, 7516192768 bytes, 14680064 sectors
| Units: sectors of 1 * 512 = 512 bytes
| Sector size (logical/physical): 512 bytes / 512 bytes
| I/O size (minimum/optimal): 512 bytes / 512 bytes
| Disklabel type: dos
| Disk identifier: 0x1d80d496
| 
| Old situation:
| 
| Device     Boot Start     End Sectors Size Id Type
| /dev/xvda1       2048 4194303 4192256   2G 83 Linux
| 
| >>> Script header accepted.
| >>> Script header accepted.
| >>> Script header accepted.
| >>> Script header accepted.
| >>> Created a new DOS disklabel with disk identifier 0x1d80d496.
| Created a new partition 1 of type 'Linux' and of size 7 GiB.
| /dev/xvda2: 
| New situation:
| 
| Device     Boot Start      End  Sectors Size Id Type
| /dev/xvda1       2048 14680063 14678016   7G 83 Linux
| 
| The partition table has been altered.
| Calling ioctl() to re-read partition table.
| Re-reading the partition table failed.: Device or resource busy
| The kernel still uses the old table. The new table will be used at the next reboot or after you run partprobe(8) or kpartx(8).
FAILED: failed to resize
***** WARNING: Resize failed, attempting to revert ******
512+0 records in
512+0 records out
512 bytes copied, 0.000410368 s, 1.2 MB/s
***** Appears to have gone OK ****

[root@ip-172-30-0-51:~/nixpkgs]# mount
devtmpfs on /dev type devtmpfs (rw,nosuid,size=51044k,nr_inodes=126446,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=3,mode=620,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /run type tmpfs (rw,nodev,size=255216k,mode=755)
ramfs on /run/keys type ramfs (rw,nosuid,nodev,relatime,mode=750,gid=96)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
/dev/xvda1 on / type ext4 (rw,relatime,data=ordered)
/dev/xvda1 on /nix/store type ext4 (ro,relatime,data=ordered)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/run/current-system/systemd/lib/systemd/systemd-cgroups-agent,name=systemd)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=28,pgrp=1,timeout=0,minproto=5,maxproto=5,direct)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
mqueue on /dev/mqueue type mqueue (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
tmpfs on /run/user/0 type tmpfs (rw,nosuid,nodev,relatime,size=102084k,mode=700)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)

[root@ip-172-30-0-51:~/nixpkgs]# df -ha
Filesystem                Size  Used Avail Use% Mounted on
devtmpfs                   50M     0   50M   0% /dev
devpts                       0     0     0    - /dev/pts
tmpfs                     499M     0  499M   0% /dev/shm
proc                         0     0     0    - /proc
tmpfs                     250M  4.3M  246M   2% /run
ramfs                        0     0     0    - /run/keys
sysfs                        0     0     0    - /sys
/dev/disk/by-label/nixos  2.0G  1.7G  196M  90% /
/dev/disk/by-label/nixos  2.0G  1.7G  196M  90% /nix/store
securityfs                   0     0     0    - /sys/kernel/security
tmpfs                     499M     0  499M   0% /sys/fs/cgroup
cgroup                       0     0     0    - /sys/fs/cgroup/systemd
cgroup                       0     0     0    - /sys/fs/cgroup/pids
cgroup                       0     0     0    - /sys/fs/cgroup/cpuset
cgroup                       0     0     0    - /sys/fs/cgroup/net_cls
cgroup                       0     0     0    - /sys/fs/cgroup/cpu,cpuacct
cgroup                       0     0     0    - /sys/fs/cgroup/blkio
cgroup                       0     0     0    - /sys/fs/cgroup/freezer
cgroup                       0     0     0    - /sys/fs/cgroup/memory
cgroup                       0     0     0    - /sys/fs/cgroup/devices
systemd-1                    -     -     -    - /proc/sys/fs/binfmt_misc
hugetlbfs                    0     0     0    - /dev/hugepages
debugfs                      0     0     0    - /sys/kernel/debug
mqueue                       0     0     0    - /dev/mqueue
fusectl                      0     0     0    - /sys/fs/fuse/connections
tmpfs                     100M  8.0K  100M   1% /run/user/0
binfmt_misc                  0     0     0    - /proc/sys/fs/binfmt_misc

[root@ip-172-30-0-51:~/nixpkgs]# ./result//bin/growpart /dev/xvda 1 --help
growpart disk partition
   rewrite partition table so that partition takes up all the space it can
   options:
    -h | --help       print Usage and exit
         --fudge F    if part could be resized, but change would be
                      less than 'F', do not resize (default: 20480)
    -N | --dry-run    only report what would be done, show new '/nix/store/1sf1hnv3kw5jrjp0v8i9bdzrfw8rqbnl-util-linux-2.28.1-bin/bin/sfdisk -d'
    -v | --verbose    increase verbosity / debug
    -u | --update  R  update the the kernel partition table info after growing
                      this requires kernel support and 'partx --update'
                      R is one of:
                       - 'auto'  : [default] update partition if possible
                       - 'force' : try despite sanity checks (fail on failure)
                       - 'off'   : do not attempt
                       - 'on'    : fail if sanity checks indicate no support

   Example:
    - growpart /dev/sda 1
      Resize partition 1 on /dev/sda

```

Happy to try again if you can help me out.

**Comment by jokogr** [comment]
@grahamc many thanks for the output! I am fairly busy this week presenting my Ph.D. thesis, but I promise to have a look on it by the end of the week.

When I originally tried this, it worked for a btrfs partition on a GPT disk via `nix-shell`. It has been a while since then and this PR needs more work, for sure. Others are using it in a different way, e.g., embedded in initrd (https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/grow-partition.nix), so sfdisk is copied there. Perhaps I need to revert back to `sed` from `substituteInPlace`, so that it works again like that.

**Comment by domenkozar** [comment]
Now I need this too, looking into it.

**Comment by domenkozar** [comment]
I've pushed a fix in 2326c8de4dd53a2829d40a7dbdf16f4dc0ebf6b6 that works for EC2, can you also check that it works now with plan package?

**Comment by domenkozar** [comment]
Just open a new issue if it's still broken.

**Comment by grahamc** [comment]
Domen Kožar <notifications@github.com> writes:

> Closed #17015.
>
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/NixOS/nixpkgs/pull/17015#event-862855299


:thumbsup: thank you, domen, for getting this fixed up!

**Pull request closed without merging**
