### PR TITLE
skypeforlinux: 8.51.0.72 -> 8.54.0.85

### PR DESCRIPTION
**Pull request by fishi0x01**
###### Motivation for this change
Source package got removed https://repo.skype.com/deb/pool/main/s/skypeforlinux/skypeforlinux_8.51.0.72_amd64.deb

Updated to latest `x.y.0.z` release, i.e., `8.54.0.85`.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @PanAeon @jraygauthier

### CODE REVIEW

**Comment by c0bw3b** [comment]
Hello @fishi0x01 and welcome around here since it seems to be your first contribution to nixpkgs :)

As per [our contribution guidelines](https://nixos.org/nixpkgs/manual/#submitting-changes-making-patches), your commit message should be written like this:
`skypeforlinux: 8.51.0.72 -> 8.54.0.85`

**Comment by fishi0x01** [comment]
Thanks for pointing this out @c0bw3b :bowing_man:  
I will read the guideline more thoroughly :+1: 

I adjusted the commit message as you suggested :)

**Review by c0bw3b — APPROVED** [review]
I've tested it locally on x64 NixOS and it runs as expected.

**Comment by c0bw3b** [comment]
Thank you @fishi0x01 for this update. 🚀

**Comment by d-goldin** [comment]
I think this could be a candidate for backporting to 19.09, as currently this seems broken. I think in such a case a version upgrade of such a leaf package is probably legitimate for the stable release.

**Comment by c0bw3b** [comment]
It was updated in #72822 for r19.09
Is v8.51.0.86 not working ?

**Comment by d-goldin** [comment]
@c0bw3b: It does not exist anymore: https://repo.skype.com/deb/pool/main/s/skypeforlinux/

```
> git rev-parse HEAD                                                                                  
c0c062da7b3e20ec3b6c9416bc03cb3fc61df4b8

> nix-build -I nixpkgs=$(pwd) '<nixpkgs>' -A pkgs.skypeforlinux                                             release-19.09 [c0c062da7b3] untracked

these derivations will be built:
  /nix/store/f8gyiby845s8wxlwy37dfbyiyz622gv9-skypeforlinux_8.51.0.86_amd64.deb.drv
  /nix/store/c1yan6hs2clfhrcg6w7vkjqhikg91mgl-skypeforlinux-8.51.0.86.drv
building '/nix/store/f8gyiby845s8wxlwy37dfbyiyz622gv9-skypeforlinux_8.51.0.86_amd64.deb.drv'...

trying https://repo.skype.com/deb/pool/main/s/skypeforlinux/skypeforlinux_8.51.0.86_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
error: cannot download skypeforlinux_8.51.0.86_amd64.deb from any mirror
builder for '/nix/store/f8gyiby845s8wxlwy37dfbyiyz622gv9-skypeforlinux_8.51.0.86_amd64.deb.drv' failed with exit code 1
cannot build derivation '/nix/store/c1yan6hs2clfhrcg6w7vkjqhikg91mgl-skypeforlinux-8.51.0.86.drv': 1 dependencies couldn't be built
error: build of '/nix/store/c1yan6hs2clfhrcg6w7vkjqhikg91mgl-skypeforlinux-8.51.0.86.drv' failed
```

**Comment by c0bw3b** [comment]
Quick fix in e6d584f6dd22b587d5cdf5019f5e7dd2be370f61

Wish upstream repo would be more stable.

**Pull request merged**
