### PR TITLE
gitlab: 7.4.2 -> 8.0.5

### LINKED ISSUE #10476: Can't enable gitlab module
Hello, 

Whenever I try to enable the gitlab module, it fails to install with the error : `The unique option `services.postgresql.package' is defined multiple times, in `/nix/store/igd20r92j317ks59qqfr69bkb5sbralf-nixos-16.03pre70421.e57024f/nixos/nixpkgs/nixos/modules/services/misc/gitlab.nix' and `/nix/store/igd20r92j317ks59qqfr69bkb5sbralf-nixos-16.03pre70421.e57024f/nixos/nixpkgs/nixos/modules/services/databases/postgresql.nix'.`

The configuration.nix and full trace can be found at https://gist.github.com/roblabla/0acfd800aa1114a784e0 .

### PR DESCRIPTION
**Pull request by roblabla**
Fixes #10476 .

### CODE REVIEW

**Comment by domenkozar** [comment]
Right, the biggest hurdle here is how to apply migrations for users on 7.4.2?

**Comment by roblabla** [comment]
Hmm, yeah. @domenkozar should the migrations be applied by the service ? Or should the users apply it themselves. If applied by the service, I guess I could run the migration command `bundle exec rake db:migrate RAILS_ENV=production` in the preStart of the service. Would that work ?

Otherwise, I _think_ users can use `gitlab-runner rake db:migrate RAILS_ENV=production`.

Another problem for current 7.4.2 users is that the secret file is now required to be entirely made of UTF8 characters (no random binary, hence https://github.com/NixOS/nixpkgs/pull/10535/files#diff-a8187202c46aeec728e5b8818fdce3c8L250). If we want to fix this, we'll probably want to check if the secret contains only ASCII (for convenience) and if not, regenerate it. I'll need to check what the consequences of changing the secret is first though...

**Comment by jagajaga** [comment]
I think we **must** provide migration automatically.

**Comment by roblabla** [comment]
This commit should run the database migrations automatically upon starting gitlab now. I suppose that's enough (seems to be, looking at the update guides), but since I don't have a gitlab to migrate, I'm not sure, and since I can't easily install an older version, it ain't really possible for me to test it.

I found out the gitlab_shell_secret file is recreated each time the gitlab service is started, so that's not an issue, the binary secret will be changed to an ascii one automatically upon upgrading.

**Comment by roblabla** [comment]
Bump. This is ready on my end, just waiting for a merger.

**Comment by domenkozar** [comment]
@offlinehacker @fmap @cstrahan @abbradar @teh anyone of you using gitlab 7.4.x and would like to try out these migrations?

**Comment by fmap** [comment]
nope

**Comment by cstrahan** [comment]
I don't have a GitLab instance at the moment, but I can try to spin one up tonight and see if the migrations work.

**Comment by roblabla** [comment]
Bump ?

**Comment by devhell** [comment]
Bump

**Comment by devhell** [comment]
bump 2

**Comment by roblabla** [comment]
Bump. Squashed the commits into one and gave it the proper commit message as per `CONTRIBUTING.md`.

**Comment by jagajaga** [comment]
Tested?
Sorry, I can't test myself :(

**Comment by roblabla** [comment]
The old version (7.4.2) fails to install, one of the dependency is broken (therubyracer). I don't even know if anyone currently runs the gitlab server currently in the repo, given it's uninstallable right now...

The current version, freshly installed, works perfectly well on my end.

**Comment by jagajaga** [comment]
Found old nixos server with gitlab there. Tested. It works and it migrates.

**Comment by jgillich** [comment]
Could this be backported to 15.09?

**Pull request merged**
