### PR TITLE
facette: 0.4.0 -> 0.4.1

### PR DESCRIPTION
**Pull request by fgaz**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by fgaz** [comment]
@GrahamcOfBorg build facette

**Comment by fgaz** [comment]
Right... this requires an itnernet connection to build, which is why we don't have facette cached in nixpkgs :-/

**Comment by Mic92** [comment]
Can you get the compiled assets from the release tarball? https://github.com/facette/facette/releases

**Comment by fgaz** [comment]
I just marked it as broken for now

**Comment by fgaz** [comment]
I'll open an issue about the assets and fix it later

**Pull request merged**
