### PR TITLE
element-{web,desktop}: 1.8.5 -> 1.9.0

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

ChangeLog: https://github.com/vector-im/element-web/releases/tag/v1.9.0
ChangeLog: https://github.com/vector-im/element-desktop/releases/tag/v1.9.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by hmenke** [comment]
Result of `nixpkgs-review pr 139743` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>element-desktop</li>
    <li>element-desktop-wayland</li>
    <li>element-web</li>
  </ul>
</details>

**Comment by hmenke** [comment]
Doesn't work on Ubuntu but that's a generic problem that affects all Chromium/Electron applications (cf. https://discourse.nixos.org/t/cannot-launch-chromium-electron-based-programs-on-ubuntu/15221) and also does not seem to be specific to Nix-built Chromium/Electron applications (cf. https://bugs.launchpad.net/ubuntu/+source/slack/+bug/1943568/comments/6)
```console
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
$ /nix/store/dqk63iaymn1nkrlg7a4i3nkgbr54i5m2-element-desktop-1.9.0/bin/element-desktop 
Trace/breakpoint trap
```

**Comment by Kranzes** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/pull/139647

**Comment by Ma27** [comment]
Oh... interesting... Normally ofborg pings me for element-web bumps and since I didn't see such a notification I assumed there's no bump :)

**Pull request closed without merging**
