### PR TITLE
ocamlPackages.{benchmark,obuild,ptmap,rope}: init at 1.4, 0.1.8, 2.0.…

### PR DESCRIPTION
**Pull request by volth**
…1, 0.5

###### Motivation for this change

Dependencies for coming Haxe 4.0 (current git master).

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vbgl** [comment]
`obuild` is not an OCaml library. Can you move the file e.g. in `pkgs/development/tools/ocaml/obuild` and the attribute outside of `ocamlPackages`.  Thanks.

**Comment by volth** [comment]
Indeed, it is not an ocaml library, but it is a program written in ocaml and thus bound to a particular ocamlPackages.ocaml and ocamlPackages.findlib.
Haxe is also in ocamlPackages not being an ocaml library, as well as many others.

**Comment by vbgl** [comment]
Merged in 18e3799cd1fcce8a1b37e182e65e3edc4c0f0a0e. Thanks.

I’ve moved `obuild`, removed some spurious dependencies to `camlp4` and added “OCaml” to the names of the OCaml libraries.

The `obuild` tool is indeed written in OCaml. But it does not matter much which version of the OCaml compiler is used to compile it: it will provide the same functionality; only the size of the binaries, the execution times, etc. might slightly vary. If someone really needs to set a particular version of the compiler to compile this tool, this is possible, e.g., by overriding the derivation. But it does not seem particularly useful to provide by default in `nixpkgs` four or five variants of the same tool.

**Comment by volth** [comment]
Thank you!

**Comment by volth** [comment]
As for ```camlp4``` - there were warnings like "camlp4 not found" in the build log.

**Comment by vbgl** [comment]
Yes, this is `ocamlbuild` which looks for `camlp4` before it actually needs it.

**Pull request closed without merging**
