### PR TITLE
phpfpm: add options

### PR DESCRIPTION
**Pull request by Izorkin**
###### Motivation for this change
Add options globalPhpOptions to configure php.ini for all PHP-FPM pools.
Add option listenTCP to enable work PHP-FPM with network address.

cc @etu

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by aanderse** [comment]
I want to highlight that there was an option to add configuration globally across all `php.ini` files that you removed in #63156:
```
(mkRemovedOptionModule [ "services" "phpfpm" "phpOptions" ] "Use services.phpfpm.pools.<name>.phpOptions instead.")
```
I'll state that this PR should not be merged, in my opinion, because it is based on a PR I'm planning to revert with 63931. Note that #63931 will reintroduce the ability to set `phpOptions` globally which is half of what this PR does.

As an aside @Izorkin what is your use case for using a tcp connection instead of a unix socket? I'm curious because one has much better performance than the other.

**Comment by Izorkin** [comment]
@aanderse globalPhpOptions allows you to set global parameters.
Example config with tcp connection:
```
  services.phpfpm = {
    globalExtraConfig = ''
      rlimit_files = 131072
      rlimit_core = unlimited
    '';
    globalPhpOptions = ''
      display_errors = off
      display_startup_errors = off
      open_basedir = /dev/urandom:/proc/cpuinfo:/proc/meminfo:/etc/ssl/certs:/var/www
      disable_functions = exec,passthru,shell_exec,system
      date.timezone = "Europe/Moscow"
    '';
    pools = {
      "example-php72" = {
        listenTCP = "127.0.0.1:9002";
        phpPackage = pkgs.php72;
        user = "nginx";
        group = "nginx";
        phpOptions = ''
          ; Extensions
          extension = ${pkgs.php72Packages.apcu}/lib/php/extensions/apcu.so
          extension = ${pkgs.php72Packages.imagick}/lib/php/extensions/imagick.so
          extension = ${pkgs.php72Packages.memcached}/lib/php/extensions/memcached.so
          extension = ${pkgs.php72Packages.event}/lib/php/extensions/event.so
          zend_extension = ${pkgs.php72}/lib/php/extensions/opcache.so
        '';
        extraConfig = ''
          pm = dynamic
          pm.max_children = 40
          pm.start_servers = 4
          pm.min_spare_servers = 4
          pm.max_spare_servers = 12
          pm.max_requests = 500
          listen.backlog = 65536
          security.limit_extensions = .php
        '';
      };
    };
  };

```

**Comment by aanderse** [comment]
@Izorkin Setting global php options is what you removed from your last PR. Now you are adding it back.

I understand how to use tcp connection I'm just curious why you would do that when socket is faster. What benefit do you get from using tcp instead of socket in this example?

**Comment by Izorkin** [comment]
Yes, I missed the moment with the global php.ini configuration.
It is possible that someone else is using tcp connection with option c `listen = "127.0.0.1:9000";` In this case, it remains possible to use tcp connection.

**Comment by aanderse** [comment]
Closing in favor of https://github.com/NixOS/nixpkgs/pull/63931

**Pull request closed without merging**
