### PR TITLE
sourcehut: bump all versions

### PR DESCRIPTION
**Pull request by tomberek**
###### Motivation for this change
Extract out the version bumps for https://github.com/NixOS/nixpkgs/pull/113244

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 119517` at 02b2e2c2 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages built successfully:</summary>
  <ul>
    <li>sourcehut.buildsrht</li>
    <li>sourcehut.dispatchsrht</li>
    <li>sourcehut.gitsrht</li>
    <li>sourcehut.hgsrht</li>
    <li>sourcehut.hubsrht</li>
    <li>sourcehut.listssrht</li>
    <li>sourcehut.mansrht</li>
    <li>sourcehut.metasrht</li>
    <li>sourcehut.pastesrht</li>
    <li>sourcehut.todosrht</li>
  </ul>
</details>
<details>
  <summary>8 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/no-python-tests.md">no-python-tests</a>

Test runner could not discover any test cases: ‘Ran 0 tests in 0.000s’
Near pkgs/applications/version-management/sourcehut/git.nix:76:0:
```
   |
76 |     description = "Git repository hosting service for the sr.ht network";
   | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/no-python-tests.md">no-python-tests</a>

Test runner could not discover any test cases: ‘Ran 0 tests in 0.000s’
Near pkgs/applications/version-management/sourcehut/paste.nix:33:0:
```
   |
33 |     description = "Ad-hoc text file hosting service for the sr.ht network";
   | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/no-python-tests.md">no-python-tests</a>

Test runner could not discover any test cases: ‘Ran 0 tests in 0.000s’
Near pkgs/applications/version-management/sourcehut/man.nix:33:0:
```
   |
33 |     description = "Wiki service for the sr.ht network";
   | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/no-python-tests.md">no-python-tests</a>

Test runner could not discover any test cases: ‘Ran 0 tests in 0.000s’
Near pkgs/applications/version-management/sourcehut/dispatch.nix:35:0:
```
   |
35 |     description = "Task dispatcher and service integration tool for the sr.ht network";
   | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/no-python-tests.md">no-python-tests</a>

Test runner could not discover any test cases: ‘Ran 0 tests in 0.000s’
Near pkgs/applications/version-management/sourcehut/builds.nix:60:0:
```
   |
60 |     description = "Continuous integration service for the sr.ht network";
   | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/no-python-tests.md">no-python-tests</a>

Test runner could not discover any test cases: ‘Ran 0 tests in 0.000s’
Near pkgs/applications/version-management/sourcehut/hg.nix:37:0:
```
   |
37 |     description = "Mercurial repository hosting service for the sr.ht network";
   | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/no-python-tests.md">no-python-tests</a>

Test runner could not discover any test cases: ‘Ran 0 tests in 0.000s’
Near pkgs/applications/version-management/sourcehut/meta.nix:70:0:
```
   |
70 |     description = "Account management service for the sr.ht network";
   | ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/no-python-tests.md">no-python-tests</a>

Test runner could not discover any test cases: ‘Ran 0 tests in 0.000s’
Near pkgs/applications/version-management/sourcehut/lists.nix:41:0:
```
   |
41 |     description = "Mailing list service for the sr.ht network";
   | ^
```
</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 119517` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
10 packages built:
</summary>
<ul>
<li>sourcehut.buildsrht</li>
<li>sourcehut.dispatchsrht</li>
<li>sourcehut.gitsrht</li>
<li>sourcehut.hgsrht</li>
<li>sourcehut.hubsrht</li>
<li>sourcehut.listssrht</li>
<li>sourcehut.mansrht</li>
<li>sourcehut.metasrht</li>
<li>sourcehut.pastesrht</li>
<li>sourcehut.todosrht</li>
</ul>
</details>

**Review by eadwu — APPROVED** [review]
Builds fine locally, has trouble with go.pkg.dev probably due to rate limiting.

**Review by dotlambda — CHANGES_REQUESTED** [review]
Please rebase on master. `python3Packages.minio` fails on your branch.

**Review by dotlambda — CHANGES_REQUESTED** [review]
There should be one commit per package.

**Review by dotlambda — CHANGES_REQUESTED** [review]
Please use `fetchFromSourcehut`.

**Comment by SuperSandro2000** [comment]
> Please rebase on master. `python3Packages.minio` fails on your branch.

ofborg and nixpkgs-reviews by default merge the PR into master and generally it is not required to rebase because it just makes it hard to know what changed between force pushes.

**Comment by dotlambda** [comment]
> ofborg and nixpkgs-reviews by default merge the PR into master

I know that, but as a thorough reviewer, I e.g. try whether we can enable more tests etc., which requires checking out the pull request's head.

**Comment by tomberek** [comment]
rebased onto master and split commits per package

**Comment by tomberek** [comment]
> Please use `fetchFromSourcehut`.

Used fetchFromSourcehut in most cases (some requires submodules).

**Review by dotlambda — APPROVED** [review]
LGTM, but I haven't tested it.

**Comment by tomberek** [comment]
Possibly a side-discussion: generally I try not to merge my own PRs. But in some cases where my knowledge of a PR is high it would be more efficient to iterate to go ahead. It’s helpful to have approvals from others to double-check things. Often (eg. for this and the parent service module PR) a PR can stall waiting for another less involved committer to build up enough knowledge to merge. 

In such cases what do people think is the appropriate amount of review?

**Comment by dotlambda** [comment]
> In such cases what do people think is the appropriate amount of review?

I would suggest you wait a day or two and then merge this. The Python *looks* good and builds and usually not much is required to have a PR merged. For NixOS modules, I would be a little more careful.

**Pull request merged**
