### PR TITLE
inkcut: 2.1.2 -> 2.1.3

### PR DESCRIPTION
**Pull request by raboof**
###### Motivation for this change

We had a patch to make using inkcut as an inkscape plugin more reliable.
This has been accepted upstream so no longer needs to be in nixpkgs.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Also tested that inkcut also still works correctly when invoked as an inkscape plugin.

### CODE REVIEW

**Review by charles-dyfis-net — APPROVED** [review]
Builds; runs; reviewing the upstream repo confirms that https://github.com/inkcut/inkcut/pull/292 has been merged.

**Comment by SuperSandro2000** [comment]
Fails to build on darwin:

```
FAILED: src/CMakeFiles/SMESH.dir/SMESH/SMESH_MeshEditor.cpp.o
/nix/store/m50xmigjz3j30msh214vs9b7yf8sl9d4-clang-wrapper-7.1.0/bin/clang++ -DCSFDB -DHAVE_CONFIG_H -DLIN -DOCC_CONVERT_SIGNALS -DSMESH_EXPORTS -D_OCC64 -I../ -I../inc -I/nix/store/bic2aq7gqfns55674fksrb21vhzdi5x8-opencascade-oce-0.18.3/OCE.framework/Versions/0.18/Resources/../../../../include/oce -I../boost-1.52.0 -O3 -DNDEBUG -arch x86_64 -fPIC -F/nix/store/m35jpggl5f18yw7a5h3hbaqnw9hl4ya0-apple-framework-OpenGL/Library/Frameworks -MD -MT src/CMakeFiles/SMESH.dir/SMESH/SMESH_MeshEditor.cpp.o -MF src/CMakeFiles/SMESH.dir/SMESH/SMESH_MeshEditor.cpp.o.d -o src/CMakeFiles/SMESH.dir/SMESH/SMESH_MeshEditor.cpp.o -c ../src/SMESH/SMESH_MeshEditor.cpp
../src/SMESH/SMESH_MeshEditor.cpp:6968:22: error: non-constant-expression cannot be narrowed from type 'std::__1::list<const SMDS_MeshNode *, std::__1::allocator<const SMDS_MeshNode *> >::size_type' (aka 'unsigned long') to 'int' in initializer list [-Wc++11-narrowing]
  int nbNodes[]  = { nSide[0].size(), nSide[1].size() };
                     ^~~~~~~~~~~~~~~
../src/SMESH/SMESH_MeshEditor.cpp:6968:22: note: insert an explicit cast to silence this issue
  int nbNodes[]  = { nSide[0].size(), nSide[1].size() };
                     ^~~~~~~~~~~~~~~
                     static_cast<int>( )
../src/SMESH/SMESH_MeshEditor.cpp:6968:39: error: non-constant-expression cannot be narrowed from type 'std::__1::list<const SMDS_MeshNode *, std::__1::allocator<const SMDS_MeshNode *> >::size_type' (aka 'unsigned long') to 'int' in initializer list [-Wc++11-narrowing]
  int nbNodes[]  = { nSide[0].size(), nSide[1].size() };
                                      ^~~~~~~~~~~~~~~
../src/SMESH/SMESH_MeshEditor.cpp:6968:39: note: insert an explicit cast to silence this issue
  int nbNodes[]  = { nSide[0].size(), nSide[1].size() };
                                      ^~~~~~~~~~~~~~~
                                      static_cast<int>( )
2 errors generated.
[65/157] Building CXX object src/CMakeFiles/SMESH.dir/SMESH/SMESH_MesherHelper.cpp.o
ninja: build stopped: subcommand failed.
builder for '/nix/store/gf8zlz8whvc4jlvrjcs1bylmkl3kshf1-smesh-6.7.6.drv' failed with exit code 1
cannot build derivation '/nix/store/mshms86si8b8vwawivga0lw1lvhkk4bw-pythonocc-core-0.18.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/64v56fc0z0jnmbv57hwps8dzfh8pdnrj-python3.8-enamlx-0.4.3.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/m4bnq34jlbg03qp9mqfqq5p7v7ijirb8-inkcut-2.1.3.drv': 1 dependencies couldn't be built
error: build of '/nix/store/m4bnq34jlbg03qp9mqfqq5p7v7ijirb8-inkcut-2.1.3.drv' failed
```

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 106433` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>inkcut</li>
    <li>inkscape-extensions.inkcut</li>
  </ul>
</details>

**Comment by raboof** [comment]
> Fails to build on darwin:
> 
> ```
> FAILED: src/CMakeFiles/SMESH.dir/SMESH/SMESH_MeshEditor.cpp.o
> ...
> builder for '/nix/store/gf8zlz8whvc4jlvrjcs1bylmkl3kshf1-smesh-6.7.6.drv' failed with exit code 1
> cannot build derivation '/nix/store/mshms86si8b8vwawivga0lw1lvhkk4bw-pythonocc-core-0.18.1.drv': 1 dependencies couldn't be built
> cannot build derivation '/nix/store/64v56fc0z0jnmbv57hwps8dzfh8pdnrj-python3.8-enamlx-0.4.3.drv': 1 dependencies couldn't be built
> cannot build derivation '/nix/store/m4bnq34jlbg03qp9mqfqq5p7v7ijirb8-inkcut-2.1.3.drv': 1 dependencies couldn't be built
> error: build of '/nix/store/m4bnq34jlbg03qp9mqfqq5p7v7ijirb8-inkcut-2.1.3.drv' failed
> ```

That's a failure with an upstream dependency (smesh) unrelated to this PR AFAICS.

**Comment by SuperSandro2000** [comment]
> That's a failure with an upstream dependency (smesh) unrelated to this PR AFAICS.

Can you mark it broken on darwin?

**Comment by raboof** [comment]
> > That's a failure with an upstream dependency (smesh) unrelated to this PR AFAICS.
> 
> Can you mark it broken on darwin?

I'm pretty sure this problem already exists on master, right? Since it is unrelated to this PR I'd prefer not to mark it broken on this PR. That said, perhaps we can do even better: #106641 (tested compiling with clang on linux, I don't have a darwin machine)

**Comment by raboof** [comment]
> Fails to build on darwin:
> 
> ```
> FAILED: src/CMakeFiles/SMESH.dir/SMESH/SMESH_MeshEditor.cpp.o
> /nix/store/m50xmigjz3j30msh214vs9b7yf8sl9d4-clang-wrapper-7.1.0/bin/clang++ -DCSFDB -DHAVE_CONFIG_H -DLIN -DOCC_CONVERT_SIGNALS -DSMESH_EXPORTS -D_OCC64 -I../ -I../inc -I/nix/store/bic2aq7gqfns55674fksrb21vhzdi5x8-opencascade-oce-0.18.3/OCE.framework/Versions/0.18/Resources/../../../../include/oce -I../boost-1.52.0 -O3 -DNDEBUG -arch x86_64 -fPIC -F/nix/store/m35jpggl5f18yw7a5h3hbaqnw9hl4ya0-apple-framework-OpenGL/Library/Frameworks -MD -MT src/CMakeFiles/SMESH.dir/SMESH/SMESH_MeshEditor.cpp.o -MF src/CMakeFiles/SMESH.dir/SMESH/SMESH_MeshEditor.cpp.o.d -o src/CMakeFiles/SMESH.dir/SMESH/SMESH_MeshEditor.cpp.o -c ../src/SMESH/SMESH_MeshEditor.cpp
> ../src/SMESH/SMESH_MeshEditor.cpp:6968:22: error: non-constant-expression cannot be narrowed from type 'std::__1::list<const SMDS_MeshNode *, std::__1::allocator<const SMDS_MeshNode *> >::size_type' (aka 'unsigned long') to 'int' in initializer list [-Wc++11-narrowing]
>   int nbNodes[]  = { nSide[0].size(), nSide[1].size() };
>                      ^~~~~~~~~~~~~~~
> ../src/SMESH/SMESH_MeshEditor.cpp:6968:22: note: insert an explicit cast to silence this issue
>   int nbNodes[]  = { nSide[0].size(), nSide[1].size() };
>                      ^~~~~~~~~~~~~~~
>                      static_cast<int>( )
> ../src/SMESH/SMESH_MeshEditor.cpp:6968:39: error: non-constant-expression cannot be narrowed from type 'std::__1::list<const SMDS_MeshNode *, std::__1::allocator<const SMDS_MeshNode *> >::size_type' (aka 'unsigned long') to 'int' in initializer list [-Wc++11-narrowing]
>   int nbNodes[]  = { nSide[0].size(), nSide[1].size() };
>                                       ^~~~~~~~~~~~~~~
> ../src/SMESH/SMESH_MeshEditor.cpp:6968:39: note: insert an explicit cast to silence this issue
>   int nbNodes[]  = { nSide[0].size(), nSide[1].size() };
>                                       ^~~~~~~~~~~~~~~
>                                       static_cast<int>( )
> 2 errors generated.
> [65/157] Building CXX object src/CMakeFiles/SMESH.dir/SMESH/SMESH_MesherHelper.cpp.o
> ninja: build stopped: subcommand failed.
> builder for '/nix/store/gf8zlz8whvc4jlvrjcs1bylmkl3kshf1-smesh-6.7.6.drv' failed with exit code 1
> cannot build derivation '/nix/store/mshms86si8b8vwawivga0lw1lvhkk4bw-pythonocc-core-0.18.1.drv': 1 dependencies couldn't be built
> cannot build derivation '/nix/store/64v56fc0z0jnmbv57hwps8dzfh8pdnrj-python3.8-enamlx-0.4.3.drv': 1 dependencies couldn't be built
> cannot build derivation '/nix/store/m4bnq34jlbg03qp9mqfqq5p7v7ijirb8-inkcut-2.1.3.drv': 1 dependencies couldn't be built
> error: build of '/nix/store/m4bnq34jlbg03qp9mqfqq5p7v7ijirb8-inkcut-2.1.3.drv' failed
> ```

Could you test this again, since #106641 has been merged and this PR rebased on that?

**Comment by SuperSandro2000** [comment]
> @SuperSandro2000
> 
> > Fails to build on darwin:
> > ```
> > ../src/SMESH/SMESH_MeshEditor.cpp:6968:22: error: non-constant-expression cannot be narrowed from type 'std::__1::list<const SMDS_MeshNode *, std::__1::allocator<const SMDS_MeshNode *> >::size_type' (aka 'unsigned long') to 'int' in initializer list [-Wc++11-narrowing]
> > builder for '/nix/store/gf8zlz8whvc4jlvrjcs1bylmkl3kshf1-smesh-6.7.6.drv' failed with exit code 1
> > error: build of '/nix/store/m4bnq34jlbg03qp9mqfqq5p7v7ijirb8-inkcut-2.1.3.drv' failed
> > ```
> 
> Could you test this again, since #106641 has been merged and this PR rebased on that?

PRs do not need to be rebased. nixpkgs-review always fetches the latest master beforehand.

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 106433` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>inkcut</li>
    <li>inkscape-extensions.inkcut</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
There are still some build failures with darwin. I'll try to fix the obvious parts.

**Comment by SuperSandro2000** [comment]
I did #107806 which should fix building on darwin for inkcut.

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 106433` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>inkcut</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review. If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 106433` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages built:
</summary>
<ul>
<li>inkcut</li>
<li>inkscape-extensions.inkcut</li>
</ul>
</details>

**Comment by raboof** [comment]
> I did #107806 which should fix building on darwin for inkcut.

Thanks a lot!

**Pull request merged**
