### PR TITLE
azure-cli: Add extension azure-devops

### PR DESCRIPTION
**Pull request by obreitwi**
## Description of changes

Add [devops extension](https://github.com/Azure/azure-devops-cli-extension) for `azure-cli`.

Extension code was simply generated via
```sh
./query-extension-index.sh --cli-version=2.58.0 --extension=azure-devops --download --nix
```
where `2.58.0` is the version reported by `az version` on `nixpkgs-unstable`.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by katexochen** [comment]
@obreitwi Thanks for your PR, missed that when opening https://github.com/NixOS/nixpkgs/pull/306986. Would love to get your review on that PR.

**Comment by obreitwi** [comment]
> The `azure-devops` extension has external dependencies and thus can't be placed in the file with generated extensions. The infrastructure to package such extension is part of #306986.

Ah thank you for pointing that out. I assumed because its dependency was already [specified in the "parent derivation"](https://github.com/NixOS/nixpkgs/blob/f104d62b274da7e5f9296b439fa50a012ecfc3f2/pkgs/tools/admin/azure-cli/default.nix#L188) (without which azure-devops is not usable), it would not count as "actual" external dependency and thus not have to be specified again.

But I assume removing `distro` form `azurecli` dependencies would unexpectedly break `azure-devops` then, correct?
Only started getting into `nix` last month, so I'm still a bit fuzzy about best practices…

**Comment by katexochen** [comment]
> Ah thank you for pointing that out. I assumed because its dependency was already [specified in the "parent derivation"](https://github.com/NixOS/nixpkgs/blob/f104d62b274da7e5f9296b439fa50a012ecfc3f2/pkgs/tools/admin/azure-cli/default.nix#L188) (without which azure-devops is not usable), it would not count as "actual" external dependency and thus not have to be specified again.

Well, technically you are right, I guess it would just work with the parent having the dependency. The problem is rather about the semi-automated way of updating that file, which consists of deleting all extensions from the set and inserting the new output from the query-extensions-index.sh mentioned in the header. `azure-devops` isn't contained in that output so it would get lost during extension update.

> But I assume removing `distro` form `azurecli` dependencies would unexpectedly break `azure-devops` then, correct?

Yes, that another good reason to add it there.

> Only started getting into `nix` last month, so I'm still a bit fuzzy about best practices…

Happy to have you on board. :)

**Comment by katexochen** [comment]
Superseded by https://github.com/NixOS/nixpkgs/pull/306986

**Pull request closed without merging**
