### PR TITLE
Add Subdownloader

### PR DESCRIPTION
**Pull request by DamienCassou**

### CODE REVIEW

**Comment by vcunat** [comment]
- It might be better to use something else than md5 hashes, as they're deprecated #4491.
- It looks like some packages would like to use a variant of ``buildPythonPackage`` (without ``--old-and-unmanageable``). If that's likely to occur again (or does already), wouldn't it be better to make ``buildPythonPackage`` parametrizable in some way to allow it? I know very little about python; CC @iElectric or other pythons?

**Comment by DamienCassou** [comment]
@vcunat new version uses sha256 everywhere. For the other problem, I'm willing create a new pull request once `buildPythonPackage` is parametrizable. Please merge

**Comment by iElectric** [comment]
`--old-and-unmanageable` should never be used, will go away with wheels.

**Comment by vcunat** [comment]
I don't understand what that implies to this PR.

I would merge it, but I just noticed that the subdownloader package provides ``$out/bin/run.py`` as the main executable. That's really ugly!

**Comment by iElectric** [comment]
It means that it's the problem of python infrastructure and not this PR

**Comment by vcunat** [comment]
OK, so that confirms we'll leave these work-arounds for now; they can be removed after the general python changes.

**Pull request merged**
