### PR TITLE
zoom-us: 2.2.123200.0405 -> 2.2.128100.0627

### PR DESCRIPTION
**Pull request by tadfisher**
###### Motivation for this change

Rewrite `zoom-us` using `autoPatchelfHook` and use the system qt5 libraries.

Add an update script so this can be kept up-to-date more easily.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by tadfisher** [comment]
cc maintainers: @danbst

**Comment by peterhoeg** [comment]
This is much cleaner - nice!

**Comment by xeji** [comment]
When I build this locally and try to start it, I get this error:
```
result/bin/zoom-us 
sh: /nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libc.so.6: version `GLIBC_2.27' not found (required by /nix/store/nlq683r0lsrqgkg0pnmcr5x2fi64b3yq-v4l-utils-1.14.2/lib/libv4l2.so.0)
zoom started.
Could not initialize GLX
Aborted
```
Might be some kind of version clash between the bundled libraries and the nixpkgs ones, or an impurity in the build.

**Comment by tadfisher** [comment]
@xeji It would have to be the latter, as this change removes all bundled libraries from the package.

**Comment by xeji** [comment]
Turns out it doesn't launch from `nix-shell` but works when installed via `nix-env`. That happens with some packages.

**Comment by srhb** [comment]
@tadfisher Does your webcam work in zoom after this change? Mine doesn't, but reverting 81c2f27 fixes it. With this PR I only see a black screen, even though my webcam is on (there's an LED indicator on my laptop)

**Comment by tadfisher** [comment]
@srhb see https://github.com/NixOS/nixpkgs/issues/41203

**Comment by srhb** [comment]
@tadfisher Seems unlikely since that error existed for some people before this PR. I guess I'll open a new issue to discuss what was broken in this one specifically.

**Comment by danbst** [comment]
@tadfisher sorry, was on vacation, so missed this.

Thanks for your help and investigations! Though there are several drawbacks for this approach:
1. Closure size is now twice as large (667 Mb vs 342 Mb). Largest space-takers now:
```
danbst@station ~> du -s $(nix-store -qR ~/zoom-us-nix-profile-1-link/bin/zoom-us) | sort -k1nr                                                                                                                      
145360  /nix/store/hin017hi1y5fdqvwayzicpdrjikcwv87-qtwebengine-5.11.1
64980   /nix/store/pz8nl4cnppd3p1cykshcb40mqxjd5yvy-python3-3.6.5
50520   /nix/store/vawc9a89l53mf05yq0k1910q7dakd99w-perl-5.24.3
36636   /nix/store/frdhjbv90y5ihwzkm35x70m9r6wgsfc3-gtk+3-3.22.30
32228   /nix/store/34n5v385sghsv3zkrbzzw7y7zsq01z17-zoom-us-2.2.128200.0702
31360   /nix/store/yqbvbbi4ha1y79ljkcczw26irxd0ah0n-icu4c-59.1
30756   /nix/store/6swx68jxqvzziml0kk0wnb99hk39hdv5-qtbase-5.11.1
26668   /nix/store/83lrbvbmxrgv7iz49mgd42yvhi473xp6-glibc-2.27
22320   /nix/store/2q9i4vjql277npk1ni0yfj8xc348w1pi-systemd-238
12948   /nix/store/dkq5gx9xpc7sx1k29kxjhwjk9dq4lkz8-glib-2.56.0
11692   /nix/store/bfsbwfhqiyi9lmq4kyymbnryg5vfjsfq-qtdeclarative-5.11.1
11312   /nix/store/n7qp8pffvcb5ff52l2nrc3g2wvxfrk75-coreutils-8.29
```
Previously:
```
danbst@station ~> du -s $(nix-store -qR ~/.nix-profile/bin/zoom-us) | sort -k1nr                                                                                                                                    
242100  /nix/store/m5fiqmg3243i784p1b9xkhqld875fzc3-zoom-us-2.1.103753.0521                                                                                                                                        
26668   /nix/store/bgl62l4ly7xfsdwqp93cqw3kqbwchdrd-glibc-2.27                                                                                                                                                     
12948   /nix/store/dz0p1m05d956swc5h255ghnpl5cf312f-glib-2.56.0                                                                                                                                                    
```
2. The approach to use nixpkgs Qt had problems in past: see @ttuegel comment https://github.com/NixOS/nixpkgs/commit/bb99babc5a1c62edd012da5a1ad14cd3fe1abf0a . Please, add yourself as maintainer if you'd like to support nixpkgs Qt bundle for Zoom.

**Comment by peterhoeg** [comment]
> Closure size is now twice as large (667 Mb vs 342 Mb). Largest space-takers now:

While that is technically true, Qt and its dependencies are very likely to already exist on a machine on which somebody wants to use zoom-us so the effective change in closure size is actually a net decrease in closure size.

As ttuegel pointed out in the referenced commit, we definitely want to use our version of Qt rather than a vendored version.

**Pull request merged**
