### PR TITLE
polonium: 0.6.0 -> 1.0b1

### LINKED ISSUE #293409: Polonium not installing in Plasma 6
### Describe the bug
I added the libsForQt5.polonium nixpkg to my plasma 6 configuration but it does not appear despite being present in the kwin folder in /run/current-system/sw. Perhaps a package titled kdePackages.polonium needs to be added for Plasma 6.

### Steps To Reproduce
1. Add libForQt5.polonium to configuration.nix
2. sudo nixos-rebuild switch
3. reboot
4. polonium missing in kwin scripts control panel.

### Expected behavior
After adding polonium to configuration.nix, rebuilding, and rebooting, polonium should appear in the kwin scripts control panel.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by lomenzel**
## Description of changes

[Github release](https://github.com/zeroxoneafour/polonium/releases/tag/v1.0b1)

## Things done

i built it on my mashine (x86_64-linux with plasma6) and it builds successfully and works as intended 
fixes #293409

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by peterhoeg** [comment]
this still builds it against plasma5 and building against plasma6 will fail as we need to invoke kpackagetool.

I have been using a local package here (just for reference):

```nix
{ lib
, fetchFromGitHub
, buildNpmPackage
, qtbase
, plasma5Packages ? null
, kdePackages ? null
}:

# how to update:
# 1. check out the tag for the version in question
# 2. run `prefetch-npm-deps package-lock.json`
# 3. update npmDepsHash with the output of the previous step

let
  isQt5 = (lib.versions.major qtbase.version) == "5";

in
buildNpmPackage {
  pname = "polonium-git";
  version = "1.0.0.beta1";

  src = fetchFromGitHub {
    owner = "zeroxoneafour";
    repo = "polonium";
    rev =
      if isQt5
      then "dbb86e5e829d8ae57caf78cd3ef0606fdc1fbca5"
      else "32b8af8a65242e2f213c268ac4be9101321b0130";
    hash =
      if isQt5
      then "sha256-MKG255AtybzXLHaxaBjk6HhcMbgGUMPiNn5tjQDaLMQ="
      else "sha256-2uthjNhQm+hkRCPXGQm2LZunTj+J0SUuUfZL0PeRd4s=";
  };

  npmDepsHash =
    if isQt5
    then "sha256-NBEkn4wNV34YWyADtjWdhnUXEfe/xomeCoiWAmin4+M="
    else "sha256-kaT3Uyq+/JkmebakG9xQuR4Kjo7vk6BzI1/LffOj/eo=";

  # the installer does a bunch of stuff that fails in our sandbox, so just build here and then we
  # manually do the install
  postPatch = ''
    substituteInPlace Makefile \
      --replace-fail "build install cleanall" "res src"
  '';

  nativeBuildInputs = [ (if isQt5 then plasma5Packages else kdePackages).kpackage ];

  dontNpmBuild = true;

  dontWrapQtApps = true;

  installPhase = ''
    runHook preInstall

    kpackagetool${if isQt5 then "5" else "6"} --install pkg --packageroot $out/share/kwin/scripts

    runHook postInstall
  '';

  env.LANG = "C.UTF-8";

  meta = with lib; {
    description = "Auto-tiler that uses KWin ${if isQt5 then "5.27" else "6"}+ tiling functionality";
    license = licenses.mit;
    maintainers = with maintainers; [ peterhoeg ];
    inherit (kdePackages.kpackage.meta) platforms;
  };
}
```

**Comment by peterhoeg** [comment]
Pardon my poor choice of words - it's not that it's built against plasma6 as such (there are no direct dependencies other than the packaging tool) but the build will fail when the plasma5 build-infra is ripped out.

**Review by drupol — APPROVED** [review]

**Review by cab404 — APPROVED** [review]

**Comment by cab404** [comment]
@peterhoeg Should this be merged, or you want your version of bump instead?

**Review by drupol — APPROVED** [review]

**Comment by atagen** [comment]
This version of polonium deprecates Plasma 5 support (and does nothing there) - is there a compromise? Could libsForQt5 be held back on 0.6.0 while kdePackages gets >1.0?

**Comment by cab404** [comment]
> This version of polonium deprecates Plasma 5 support (and does nothing there) - is there a compromise? Could libsForQt5/plasma5Packages be held back on 0.6.0 while kdePackages gets >1.0?

I thought that release notes stated it is the last version to support plasma5

> Update to Plasma 6. Plasma 5 is still available with this release, but the code quality is worse, it may have more (or fewer) bugs, and it is lacking shortcuts.

**Comment by cab404** [comment]
However, yeah, I do think that plasma5 package should also be present for backward compatibility

**Comment by atagen** [comment]
> I thought that release notes stated it is the last version to support plasma5
> 
> > Update to Plasma 6. Plasma 5 is still available with this release, but the code quality is worse, it may have more (or fewer) bugs, and it is lacking shortcuts.

"Support" in this case appears to mean "registers itself as a kwin script at all", but practically tiling functionality is lost - unsurprising as the internals were reworked for Plasma 6 in this release. Loss of shortcuts is pretty big for a tiling plugin too.

> I do think that plasma5 package should also be present for backward compatibility
It appears v1.0 proper will deprecate Plasma 5 and push support for it off to a special branch, so preemptively splitting it into its own package seems worthwhile and congruent with the developer's intent: https://github.com/zeroxoneafour/polonium/issues/106

I would hope to see Plasma 5 support in general kept around for a while yet. Plasma 6 feels amazing but it seems even window management can cause fatal crashes at present - I get one with splitting out documents from OnlyOffice, and Polonium itself has some [window dragging related crashes](https://github.com/zeroxoneafour/polonium/issues/107). It's a pretty far cry from P5 in terms of everyday stability.

**Comment by cab404** [comment]
> I would hope to see Plasma 5 support in general kept around for a while yet. Plasma 6 feels amazing but it seems even window management can cause fatal crashes at present - I get one with splitting out documents from OnlyOffice, and Polonium itself has some [window dragging related crashes](https://github.com/zeroxoneafour/polonium/issues/107). It's a pretty far cry from P5 in terms of everyday stability.

I did experience a lot of crashes with polonium beta on 6, yes

Can you please PR it? I can do that in the next 30-40 hours if you can't.

**Comment by atagen** [comment]
> Can you please PR it? I can do that in the next 30-40 hours if you can't.

any ideas on how to structure it? it looks like it should go under `pkgs/kde` somewhere, but there's no 3rd party dir there, and the `3rdparty/addons` dir in `desktops/plasma-5` seems wrong as it's explicitly splitting away from p5.

**Comment by cab404** [comment]
I guess we need @NixOS/qt-kde for that)

**Pull request merged**
