### PR TITLE
nix: revert default to 2.18 for now

### PR DESCRIPTION
**Pull request by K900**
## Description of changes

The segfault bug (see #335342) keeps hitting Hydra on unstable-small, so it's likely going to hit a lot of people once it rolls out widely. Let's revert for now, and investigate without time pressure.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by winterqt — APPROVED** [review]

**Review by RaitoBezarius — APPROVED** [review]

**Comment by K900** [comment]
Running nixpkgs-review to see if there's anything else that needs reverting.

**Comment by emilazy** [comment]
Seems like the `simpleUefiSystemdBoot` test is another thing that should go in the Nix `passthru` pile (though given that it’s flaky it might not help that much).

**Comment by K900** [comment]
Yeah, maybe if someone finds an expression that reproduces this consistently, we can add it to the upstream test suite, but this feels way too flaky.

**Comment by alyssais** [comment]
Please include reasons for reverts in commit messages.

**Comment by K900** [comment]
Updated commit messages, added nix-plugins revert.

**Comment by emilazy** [comment]
6c0fc2b45e0e3ed4bcaebe22b0b7ecb7e8303da8 isn’t right. (Or rather it’s insufficient.)

**Review by Mic92 — COMMENTED** [review]
I think the nix maintainer team should have consulted for that. Also there is no nix issue for this bug.

**Comment by K900** [comment]
Result of `nixpkgs-review pr 343032` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>94 packages built:</summary>
  <ul>
    <li>appvm</li>
    <li>attic-client</li>
    <li>attic-server</li>
    <li>bundix</li>
    <li>cabal2nix</li>
    <li>cached-nix-shell</li>
    <li>common-updater-scripts</li>
    <li>crate2nix</li>
    <li>crystal2nix</li>
    <li>disko</li>
    <li>dub-to-nix</li>
    <li>dydisnix</li>
    <li>fusionInventory</li>
    <li>libnixxml</li>
    <li>lua51Packages.luarocks-nix</li>
    <li>lua52Packages.luarocks-nix</li>
    <li>lua53Packages.luarocks-nix</li>
    <li>lua54Packages.luarocks-nix</li>
    <li>luajitPackages.luarocks-nix</li>
    <li>luarocks-packages-updater</li>
    <li>nim_lk</li>
    <li>niv (niv.bin ,niv.data)</li>
    <li>nix</li>
    <li>nix-binary-cache</li>
    <li>nix-bundle</li>
    <li>nix-direnv</li>
    <li>nix-du</li>
    <li>nix-index</li>
    <li>nix-init</li>
    <li>nix-pin</li>
    <li>nix-plugin-pijul</li>
    <li>nix-plugins</li>
    <li>nix-prefetch</li>
    <li>nix-prefetch-bzr</li>
    <li>nix-prefetch-cvs</li>
    <li>nix-prefetch-docker</li>
    <li>nix-prefetch-git</li>
    <li>nix-prefetch-hg</li>
    <li>nix-prefetch-scripts</li>
    <li>nix-prefetch-svn</li>
    <li>nix-required-mounts</li>
    <li>nix-required-mounts.dist</li>
    <li>nix-template</li>
    <li>nix-update</li>
    <li>nix-update-source</li>
    <li>nix-update-source.dist</li>
    <li>nix-update.dist</li>
    <li>nix-visualize</li>
    <li>nix-visualize.dist</li>
    <li>nix.debug</li>
    <li>nix.dev</li>
    <li>nix.doc</li>
    <li>nix.man</li>
    <li>nixStatic</li>
    <li>nixStatic.dev</li>
    <li>nixStatic.doc</li>
    <li>nixStatic.man</li>
    <li>nixci</li>
    <li>nixos-anywhere</li>
    <li>nixos-generators</li>
    <li>nixos-rebuild</li>
    <li>nixos-shell</li>
    <li>nixpkgs-hammering</li>
    <li>nixpkgs-manual</li>
    <li>nixpkgs-review</li>
    <li>nixpkgs-review.dist</li>
    <li>nixtract</li>
    <li>node2nix</li>
    <li>npins</li>
    <li>nuget-to-nix</li>
    <li>nurl</li>
    <li>nvfetcher</li>
    <li>outline</li>
    <li>prefetch-yarn-deps</li>
    <li>python311Packages.nix-kernel</li>
    <li>python311Packages.nix-kernel.dist</li>
    <li>python312Packages.nix-kernel</li>
    <li>python312Packages.nix-kernel.dist</li>
    <li>sbomnix</li>
    <li>sbomnix.dist</li>
    <li>sonarr</li>
    <li>swiftPackages.swiftpm2nix</li>
    <li>terranix</li>
    <li>typescript-language-server</li>
    <li>update-nix-fetchgit</li>
    <li>update-python-libraries</li>
    <li>vimPluginsUpdater</li>
    <li>vulnix</li>
    <li>vulnix.dist</li>
    <li>vulnix.doc</li>
    <li>vulnix.man</li>
    <li>wp4nix</li>
    <li>yarn2nix</li>
    <li>zon2nix</li>
  </ul>
</details>

**Comment by emilazy** [comment]
I think we arrived at the consensus to merge the bump as long as we’re willing to revert if problems crop up again, given the reaction to https://github.com/NixOS/nixpkgs/pull/335342#pullrequestreview-2302978504 and discussion with @fabianhjr on Matrix when they were making the decision to merge. If there are channel‐blocking eval crash issues cropping up even on the small channel I don’t think we should let a delay risk this shipping to the channels before further assessment.

**Comment by K900** [comment]
Filed a proper bug to contain discussion: https://github.com/NixOS/nix/issues/11547

**Comment by nyabinary** [comment]
How much times has the nix version been reverted to 2.18 atp lol

**Pull request merged**
