### PR TITLE
pythonPackages.serverlessrepo: fix pyyaml override

### PR DESCRIPTION
**Pull request by dhl**
###### Motivation for this change
The previous PR https://github.com/NixOS/nixpkgs/pull/62011 botched `pythonPackages.serverlessrepo` by overriding PyYAML, even though `serverlessrepo` is a python module.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Ma27** [comment]
Built and tested locally :+1:

**Comment by Ma27** [comment]
@dhl thanks!

**Comment by dhl** [comment]
Thanks again @Ma27. Very sorry about the previous PR.

**Comment by FRidh** [comment]
@dhl thanks and no problem; it's impossible to know every detail in Nixpkgs :)

**Pull request merged**
