### PR TITLE
sparrow: 1.9.1 -> 2.0.0

### PR DESCRIPTION
**Pull request by emmanuelrosa**
## Description of changes

This change updates Sparrow wallet from 1.9.1 to 2.0.0. See https://github.com/sparrowwallet/sparrow/releases/tag/2.0.0

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by RaghavSood — APPROVED** [review]

**Review by hatch01 — APPROVED** [review]
Build and tested it works great

**Comment by emilazy** [comment]
This broke `staging-next` because OpenJDK 22 is  being removed as it is end-of-life. The 21 pin should remain if possible, or otherwise be replaced with a 23 pin on `staging-next`.

**Comment by hatch01** [comment]
openjdk 21 is too old for sparrow, it does not compile with it.
I can't find openjdk 23 in `pkgs/top-level/all-packages.nix` to try if it is compatible with sparrow.
Is it normal?

**Comment by emilazy** [comment]
Sorry for being unclear; the OpenJDK changes are batched up waiting for the next `staging` cycle, as they cause a large number of rebuilds. I’ll handle rebasing the OpenJDK changes on `master` and ensuring this package continues to build on OpenJDK 23, but I don’t know how to test Sparrow. Is it reasonable to assume that it will work if it builds correctly?

**Comment by emmanuelrosa** [comment]
The Sparrow Nix package doesn't build Sparrow from source. Instead, it removes the bundled JDK and replaces it with an equivalent JDK from Nixpkgs; The Sparrow binary distrubution is built with Eclipse Temurin 22.

Because of this, a successful build of the Sparrow Nix package is no indication that the application itself will work.

**Comment by emilazy** [comment]
Alright. Hopefully they can put out a build that uses a version of OpenJDK that gets security updates soon, but I’ve pushed the OpenJDK 23 changes and a pin of `sparrow` to JDK 23 to my fork for testing. I’m checking the build now, but can you try `nix build github:emilazy/nixpkgs/push-uwxvkporsurk#sparrow` and see if it works at runtime?

**Comment by emilazy** [comment]
The build was successful. I have temporarily published the binaries to `sparrow-openjdk-23.cachix.org-1:ccHH2L2ovMLhAVlxn8s50BcdVAZcYOWx7iK19yYHdn8=` (`cachix use sparrow-openjdk-23`) if you want to avoid building OpenJDK and trust me, the nix-community builder, and Cachix enough to test it in a VM or something.

**Comment by emmanuelrosa** [comment]
It tested it. It's working just fine.

Thank you.

**Pull request merged**
