### PR TITLE
OVMF: remove invalid `assert` on SMM

### PR DESCRIPTION
**Pull request by RaitoBezarius**
## Description of changes

Original author of the patch seems to believe that SMM implies x86, this is wrong. aarch64 supports SMM too, see upstream QEMU code.

The proper way to do this is to signal support via QEMU itself, this is something we cannot do because we have no way to communicate QEMU support itself (yet?).

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by nikstur — APPROVED** [review]

**Review by adamcstephens — APPROVED** [review]

**Comment by adamcstephens** [comment]
@nikstur does this resolve your problems as mentioned in #284874 ?

**Comment by adamcstephens** [comment]
Is failing on aarch64

```
machine: must succeed: sbctl sign /boot/EFI/systemd/systemd-bootx64.efi
machine # /boot/EFI/systemd/systemd-bootx64.efi does not exist
```

**Comment by RaitoBezarius** [comment]
Well yes, the test is wrong. :).

Le ven. 1 mars 2024, 22:13, Adam C. Stephens ***@***.***> a
écrit :

**Comment by nikstur** [comment]
@ofborg test systemd-boot.secureBoot

**Comment by nikstur** [comment]
@ofborg test systemd-boot.secureBoot

**Comment by nikstur** [comment]
@ofborg test systemd-boot.secureBoot

**Comment by adamcstephens** [comment]
FYI @nikstur if you edit your message ofborg will rerun the tests.

**Comment by nikstur** [comment]
It finally seems to work.

**Review by adamcstephens — APPROVED** [review]

**Comment by adamcstephens** [comment]
aarch64:
/nix/store/83liz22468yppp9bn2ihfh6kqx2zhbzi-vm-test-run-systemd-boot-secure-boot

x86:
/nix/store/qfgmrni62sqnaj35r52hvqyf1lb2y2sk-vm-test-run-systemd-boot-secure-boot

**Pull request merged**
