### PR TITLE
zncModules.clientbuffer: 2015-08-27 -> 2020-04-24

### PR DESCRIPTION
**Pull request by szlend**
###### Motivation for this change

The original clientbuffer ZNC module has been abandoned since 2015. It has been picked up and maintained as a fork by another maintainer (https://github.com/CyberShadow/znc-clientbuffer).

This is now the recommended repo by the ZNC wiki page (https://wiki.znc.in/Clientbuffer)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by hrdinka** [comment]
@ofborg eval

**Comment by hrdinka** [comment]
@szlend I just noticed that you are a first time contributor. Thanks for the update, your work and welcome on board!

In case you plan to stick around longer and make more contributions in the future, you can think about adding yourself as a maintainer for this derivation. More about this here https://nixos.wiki/wiki/Nixpkgs#Becoming_a_Nixpkgs_maintainer

Have a nice day, Christoph

**Comment by szlend** [comment]
@hrdinka Thank you, I would gladly help maintain this derivation. I'll go ahead and add myself to the maintainers. I already tried doing so but I reverted it after a failed build. Reading through it now, it looks as I forgot to add myself to the `maintainers-list.nix`.

**Comment by hrdinka** [comment]
Yes, that was definitely the problem. Just add another commit to this pull request and make sure to name both correct regarding https://nixos.org/manual/nixpkgs/stable/#chap-submitting-changes

The actual commit containing the update should be name `zncModules.clientbuffer: 2015-08-27 -> 2020-04-24`
and the first commit `maintainers: add szlend`. This way we keep our commit history nice and tidy :) Gits interactive rebase `git rebase -i …` comes in handy for such jobs.

**Comment by hrdinka** [comment]
Great :+1: welcome on board!

Now lets wait for OfBorg to finish.

**Comment by szlend** [comment]
Thanks for the help @hrdinka. Should be good to go now :)

**Comment by hrdinka** [comment]
Thanks for the changes and congrats to your first NixOS contribution 👍

**Pull request merged**
