### PR TITLE
haskellPackages.qtah*: Fix build and mark as unbroken

### PR DESCRIPTION
**Pull request by turboMaCk**
Fixes qtah* packages

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by turboMaCk** [comment]
cc @khumba

**Comment by cdepillabout** [comment]
It looks like `qtah-generator` depends on `haskell-src`, `hoppy-std`, and `hoppy-generator`, which are all marked broken.  Could you mark these unbroken as well?

**Comment by khumba** [comment]
Hey @turboMaCk, thanks kindly for fixing this.  I'm fine with this as is, but there are some things I don't understand:

Is it proper to add `wrapQtAppsHook` or use `dontWrapQtApps` for Qt libraries?  The manual doesn't say, and `qtah-cpp-qt5` and `qtah-qt5` only have Qt libraries, not executables.  `qtah-examples` has an executable.  (And yes, it doesn't look simple to add `dontWrapQtApps` to the derivation...)

How much does it matter whether `wrapQtAppsHook` is in `nativeBuildInputs` in particular?  Here and also in my repo's qtah-examples derivation, `buildDepends` seems to work but that makes it end up in `propagatedBuildInputs` instead.  It doesn't seem like there's a perfect fit for `nativeBuildInputs` though (`buildTools` perhaps).

Just points of curiousity though :).

> haskell-src, hoppy-std, and hoppy-generator

Would you mind unmarking hoppy-runtime and hoppy-docs too please?  The former at least is required for Qtah.

**Comment by turboMaCk** [comment]
I also find hoppy-runtime, and hoppy-docs which also can be made "unbroken". Gosh searching in the huge yaml list is the new hardest problem in CS.

> Is it proper to add wrapQtAppsHook or use dontWrapQtApps for Qt libraries? The manual doesn't say, and qtah-cpp-qt5 and qtah-qt5 only have Qt libraries, not executables. qtah-examples has an executable. (And yes, it doesn't look simple to add dontWrapQtApps to the derivation...)

> How much does it matter whether wrapQtAppsHook is in nativeBuildInputs in particular? Here and also in my repo's qtah-examples derivation, buildDepends seems to work but that makes it end up in propagatedBuildInputs instead. It doesn't seem like there's a perfect fit for nativeBuildInputs though (buildTools perhaps).

I have no idea what I'm, doing to be honest :D I just chose path of the least resistance to kick start it. Anyone any suggestions? If not I will later look around qt things in nixpkgs to see if there is anything better we can do. Anyway I think `nativeBuildInputs` should work. Let me try that.

**Comment by khumba** [comment]
It's not possible to pass `nativeBuildInputs` to the Haskell `mkDerivation` directly unfortunately, that's why I suggested `buildTools` as it seems like the most general parameter to the [builder](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/generic-builder.nix) that ends up in nativeBuildInputs.

I'm fine with either though and am good with this once the merge conflicts are resolved.

**Comment by turboMaCk** [comment]
I tried using `buildTools` in place of `nativeBuildDepends` and build faild for me with the same error as it does now in master:

```
Error: wrapQtAppsHook is not used, and dontWrapQtApps is not set.
```

It seems `buildtools` not a way to satisfy the assertion.

I'm going to keep this as is and rebase it so it can be merged as it seems there is no better approach.

**Comment by turboMaCk** [comment]
@cdepillabout this is ready now. It would be great if it can get in https://github.com/NixOS/nixpkgs/pull/116096

**Review by cdepillabout — APPROVED** [review]

**Comment by cdepillabout** [comment]
This LGTM.  Everything builds.

Thanks!

**Pull request merged**
