### PR TITLE
Support SOCKS5 proxy for the Syncthing service

### PR DESCRIPTION
**Pull request by sergei-mironov**
Github says it cannot merge automatically. Probably, it is confused by a fact that my branch point is below the '0.11 -> 0.12' commit (that's why I cherry-picked it here). Could you please try to do this manually, I think that a1395ee would be resolved to a trivial merge

### CODE REVIEW

**Comment by jgillich** [comment]
Cherry picking creates a new commit, that is why there are conflicts. Just rebase your commit on top of master and they should go away (and drop the upgrade commit, obviously).

Also, why not call the option simply `proxy`?

**Comment by grwlf** [comment]
I've updated my system, so there should be no more conflicts.

@jgillich, I'd prefer to name this variable `all_proxy` because upstream has tricky policy regarding the environment. They use http_proxy for http- parts of system and all_proxy for binary parts. IMHO, for now, it is better to know exactly what variable we are changing.

**Comment by grwlf** [comment]
Hi! Travis check have failed due to some network problems (there are messages about git clone errors). Could you please restart it?

**Comment by joachifm** [comment]
I have restarted travis. Re: all_proxy vs proxy, as a user of the module, do I really care what environment variable is being set to achieve the desired end result? I would think most people care more about the feature than how it is implemented. Thus, proxy is a better name and I'd also suggest removing the detailed comments from the documentation, unless you're sure  it is necessary for the user to make effective use of the module.

**Comment by ierton** [comment]
Thanks. Regarding all_proxy, I already wrote about the fact that syncthing uses different *_proxy variables for different purposes. What I didn't mention is the fact that for typical setups those variable should have _different_ values. In my situation (which I would call typical) syncthing requires two _different_ proxy servers to operate beyond the firewall: http-proxy for HTTP protocol used and SOCKS5 for binaries.

Thats why I think that proxy support in syncthing is too young to be called stable. Inexperienced users probably shouldn't use this feature, and experienced ones usually prefer to know what exactly they are doing.

**Comment by joachifm** [comment]
Fair enough

**Pull request merged**
