### PR TITLE
go-task: rename executable to `task`

### PR DESCRIPTION
**Pull request by endorama**
###### Motivation for this change

As discussed in #116555 the `postInstall` hook renaming the executable to `go-task` is not needed anymore and can be safely removed.

After this commit the `go-task` executable will be available as `task`.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

I tried following the [reviewer docs](https://nixos.org/manual/nixpkgs/unstable/#chap-reviewing-contributions) but noticed that a PR is needed. I'm not really sure how to perform most of the actions stated above (given that I'm not using NixOS but `home-manager` on elementary).

### CODE REVIEW

**Review by dotlambda — COMMENTED** [review]
Maybe we could add a symlink to be backwards-compatible?

**Comment by lourkeur** [comment]
Result of `nixpkgs-review pr 117455` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>go-task</li>
  </ul>
</details>

---

> I tried following the [reviewer docs](https://nixos.org/manual/nixpkgs/unstable/#chap-reviewing-contributions) but noticed that a PR is needed. I'm not really sure how to perform most of the actions stated above (given that I'm not using NixOS but `home-manager` on elementary).

Welcome! fyi that's not necessarily a problem if you work on packages rather than NixOS modules, you can easily build and review packages if you have Nix installed. `nixpkgs-review` should work too.

**Review by Parasrah — CHANGES_REQUESTED** [review]
I'm basing this on my own experience with things that have been brought up on my own PR's, but I think it's preferred to combine your commits into a single commit as opposed to having new commits to address comments on the PR or build failures

**Comment by SuperSandro2000** [comment]
> I'm basing this on my own experience with things that have been brought up on my own PR's, but I think it's preferred to combine your commits into a single commit as opposed to having new commits to address comments on the PR or build failures

If it is just one change we can safely squash it but if there are 5 commits which should become 2 it is no as easy.

It is always nice to squash it because the merger can't forget it.

**Comment by endorama** [comment]
Thanks everyone!

**Pull request merged**
