### PR TITLE
rambox: build from sources

### PR DESCRIPTION
**Pull request by ghost**
Superseeded by https://github.com/NixOS/nixpkgs/pull/31137

### CODE REVIEW

**Comment by Mic92** [comment]
looks like electron, wants to download something from github after building.
This breaks the build in sandbox mode:

https://gist.github.com/Mic92/70a6da1f44a590fb4c2b86e61bd40237

**Comment by Mic92** [comment]
The offending file looks like it could be rebuild in nix: https://github.com/electron-userland/electron-prebuilt/blob/master/install.js

**Comment by gnidorah** [comment]
@Mic92 
I've fixed that by just telling nix to download and extract electron and put contents where needed (node_modules/electron/dist), but next culprit appeared - camelcase npm package needs Internet too.

Then I've tried to build another package using node2nix in sandbox - nixui (exactly its node part) and it failed too at underscore npm package.

Shouldn't it be fixed at another level?

**Comment by Mic92** [comment]
I do not know how this can be fixed. That's why I accepted the precompiled application in the first place.

**Pull request closed without merging**
