### PR TITLE
nexusmods-app: 0.7.0 -> 0.7.1

### PR DESCRIPTION
**Pull request by MattSturgeon**
- Bump version: 0.7.0 -> 0.7.1
- [Upstream's changelog](https://github.com/Nexus-Mods/NexusMods.App/releases/tag/v0.7.1)
- [Previous update PR](https://github.com/NixOS/nixpkgs/pull/360174)

Also:
- Still need .NET 8 runtime available while building, for the StrawberryShake dependency 😦 

## Notes for end-users

> [!NOTE]
> When upgrading from version 0.7.0, it _should_ be safe to upgrade **without** resetting/uninstalling:
> > We've made it possible to update the app without completely removing all your mods and games. You can update from 0.7.0 to 0.7.1 and keep your mods, games and other settings. This means that if you want to be an early adopter, you can keep your mod list intact as we release new versions!

> [!CAUTION]
> When upgrading from a **version older than 0.7.0**, you will need a fresh start.
> If you have configuration leftover from an old version, the updated app will crash.
> 
> See upstream's guide on [how to uninstall the app](https://nexus-mods.github.io/NexusMods.App/users/Uninstall/).

<details><summary>Resetting tips</summary>
<p>

> [!TIP]
> You can reset all modded games and wipe your nexusmods-app config using:
> ```
> NexusMods.App uninstall-app
> ```
> - This should be done **before** updating the app.
> - **Be careful**: There's no way to recover a wiped config!

> [!TIP]
> If you've run the appimage version from upstream, or a pre-0.6 nixpkgs version, you may also need to remove old desktop entries to avoid other issues:
> ```
> rm ~/.local/share/applications/com.nexusmods.app.desktop
> ```

</p>
</details> 

> [!CAUTION]
> Known issues are listed on the [changelog](https://github.com/Nexus-Mods/NexusMods.App/releases/tag/v0.7.1), but include:
> - Stardew Valley (Native Linux version) is not detected when installed via Heroic Launcher on Linux. The Windows version of the game can be used instead until this issue is fixed.
> - When installing Collections that include bundled mods, it is not possible to fully download the collection due to a counting error. A fix for this is planned for the next release.
> - Bundled mods included with collections do not appear in the UI but are still applied to your game.
> - The success rating for collections is not showing the correct value.
> - The game version is not checked when adding a collection meaning you can install outdated mods without being warned.
> - The Library and Collections (WIP) pages are not filtered by game.
> - The "Switch View" option does not persist in the Library/Installed Mods view.
> - The "Load Order" heading toggle does not persist in the Load Order view.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by l0b0** [comment]
This is a much better PR than #365943, thank you!

**Comment by MattSturgeon** [comment]
@ofborg build nexusmods-app.tests

**Comment by l0b0** [comment]
> > This is a much better PR
> 
> The diff is identical 😛 but thanks

I mean your PR description :grin:

**Comment by MattSturgeon** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 365942`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>nexusmods-app</li>
    <li>nexusmods-app-unfree</li>
  </ul>
</details>

**Review by corngood — APPROVED** [review]

**Comment by corngood** [comment]
Looks like one of the tests failed on ofborg.  Presumably it's still just flakey like you mentioned.

**Review by corngood — APPROVED** [review]

**Comment by MattSturgeon** [comment]
> Backport failed for `release-24.11`, because it was unable to cherry-pick the commit(s).

We decided not to backpack 0.7.0, Hence why the cherry-pick fails for 0.7.1.

Currently 24.11 still has 0.6.x, so those users would still need to manually reset the game/app state before updating.

**Pull request merged**
