### PR TITLE
jellyfin-ffmpeg: 5.0.1-5 -> 5.0.1-6, bump nv-codec-headers to v11

### PR DESCRIPTION
**Pull request by justinas**
###### Description of changes

[Per upstream request](https://github.com/jellyfin/jellyfin/issues/7944#issuecomment-1159060073), this bumps the version of `nv-codec-headers` that `jellyfin-ffmpeg` uses from the default of v9, to v11.

This fixes basic NVENC encoding in Jellyfin 10.8.0 (the core issue described by https://github.com/jellyfin/jellyfin/issues/7944).

Manual testing: Jellyfin (`nixpkgs-unstable`), GTX 1060, Nvidia 515.48.07).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by justinas** [comment]
Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>jellyfin</li>
    <li>jellyfin-ffmpeg</li>
  </ul>
</details>

**Comment by Kranzes** [comment]
Could you also update jellyfin-ffmpeg?

**Comment by justinas** [comment]
> Could you also update jellyfin-ffmpeg?

Will do. Please advise whether that is better done as a separate PR.

**Comment by Kranzes** [comment]
A separate commit would be fine.

**Comment by symphorien** [comment]
any reason to not bump nv-codec-headers globally ?

**Comment by Kranzes** [comment]
https://github.com/jellyfin/jellyfin-ffmpeg/releases/tag/v5.0.1-7

**Comment by justinas** [comment]
> any reason to not bump nv-codec-headers globally ?

I am simply not familiar enough with nv-codec-headers, and assumed that if there are separate packages (with the "old" 9 version being the default) there must be a reason for it. So for now, I did the conservative thing - if jellyfin-ffmpeg maintainers say that they expect v11, that's good enough for this change.

Grepping through nixpkgs, it looks like Xpra uses 10, a couple packages use 11, and a few others use the unversioned attr. We could probably bump the default, but I'll defer this decision to the maintainers (and that should probably be its own PR). /cc @MP2E @zhaofengli .

**Comment by symphorien** [comment]
I had not seen that there were already several versions of nv-codec-headers in nixpkgs. In this case it's ok.

**Pull request merged**
