### PR TITLE
nali: fix cross compilaton and shell completion generation

### PR DESCRIPTION
**Pull request by NickCao**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by XYenon** [comment]
Result of `nixpkgs-review pr 325406` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>nali</li>
  </ul>
</details>

**Comment by XYenon** [comment]
```
evaling implicit 'postInstall' string hook
panic: open /private/tmp/nix-build-nali-0.8.1.drv-0/Library/Application Support/nali/config.yaml: file exists

goroutine 1 [running]:
github.com/zu1k/nali/internal/config.ReadConfig({0xc00015e050, 0x48})
        github.com/zu1k/nali/internal/config/config.go:24 +0x6ed
main.main()
        github.com/zu1k/nali/main.go:13 +0x25
panic: open /private/tmp/nix-build-nali-0.8.1.drv-0/Library/Application Support/nali/config.yaml: file exists

goroutine 1 [running]:
github.com/zu1k/nali/internal/config.ReadConfig({0xc000028320, 0x48})
        github.com/zu1k/nali/internal/config/config.go:24 +0x6ed
main.main()
        github.com/zu1k/nali/main.go:13 +0x25
installShellCompletion: error: installed shell completion file `/nix/store/lqbknqwai5blmi8ywfqdcl1mgw4fka84-nali-0.8.1/share/bash-completion/completions/nali.bash' does not exist or has zero size
/nix/store/z6xrig32y1m1i3j7in3shya78y9agcp5-stdenv-darwin/setup: line 202: pop_var_context: head of shell_variables not a function context
```

**Review by XYenon — CHANGES_REQUESTED** [review]
Also failed on NixOS

```
evaling implicit 'postInstall' string hook
panic: open /build/.config/nali/config.yaml: file exists

goroutine 1 [running]:
github.com/zu1k/nali/internal/config.ReadConfig({0xc00015a0a8, 0x13})
        github.com/zu1k/nali/internal/config/config.go:24 +0x6ed
main.main()
        github.com/zu1k/nali/main.go:13 +0x25
panic: Config File "/build/.config/nali/config.yaml" Already Exists

goroutine 1 [running]:
github.com/zu1k/nali/internal/config.ReadConfig({0xc00002a270, 0x13})
        github.com/zu1k/nali/internal/config/config.go:24 +0x6ed
main.main()
        github.com/zu1k/nali/main.go:13 +0x25
installShellCompletion: error: installed shell completion file `/nix/store/0pm9rilzp4m88nqswxp7i3ckiksysirz-nali-0.8.1/share/bash-completion/completions/nali.bash' does not exist or has zero size
/nix/store/5r0df66ikad3xw06azlqvswcvncll8wa-stdenv-linux/setup: line 193: pop_var_context: head of shell_variables not a function context
```

**Comment by NickCao** [comment]
There are some race conditions in config loading/saving.

**Review by Aleksanaa — APPROVED** [review]

**Review by XYenon — APPROVED** [review]

**Comment by XYenon** [comment]
Result of `nixpkgs-review pr 325406` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>nali</li>
  </ul>
</details>

**Pull request merged**
