### PR TITLE
bambu-studio: remove openvdb override

### LINKED ISSUE #353863: Build failure: openvdb (dependency of bambu-studio, incompatible boost versions)
### Steps To Reproduce

1. build openvdb

### Build log

I think that the following lines is representative enough.

```
       last 25 log lines:
       > -- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
       > -- Configuring for OpenVDB Version 12.0.0
       > -- Configuring for OpenVDB ABI Version 12
       > -- ----------------------------------------------------
       > -- ------------- Configuring OpenVDBCore --------------
       > -- ----------------------------------------------------
       > CMake Warning (dev) at openvdb/openvdb/CMakeLists.txt:112 (find_package):
       >   Policy CMP0167 is not set: The FindBoost module is removed.  Run "cmake
       >   --help-policy CMP0167" for policy details.  Use the cmake_policy command to
       >   set the policy and suppress this warning.
       >
       > This warning is for project developers.  Use -Wno-dev to suppress it.
       > 
       > CMake Error at /nix/store/irwcgpm8csj7br49jih6kdpqkaqya3vf-cmake-3.30.4/share/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
       >   Could NOT find Boost: Found unsuitable version "1.79.0", but required is at
       >   least "1.80" (found
       >   /nix/store/p0a0h9zwmgqxn1vhl7ang0zxrrl1x60j-boost-1.79.0-dev/include, found
       >   components: iostreams regex)
       > Call Stack (most recent call first):
       >   /nix/store/irwcgpm8csj7br49jih6kdpqkaqya3vf-cmake-3.30.4/share/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:601 (_FPHSA_FAILURE_MESSAGE)
       >   /nix/store/irwcgpm8csj7br49jih6kdpqkaqya3vf-cmake-3.30.4/share/cmake-3.30/Modules/FindBoost.cmake:2409 (find_package_handle_standard_args)
       >   openvdb/openvdb/CMakeLists.txt:112 (find_package)
       >
       > 
       > -- Configuring incomplete, errors occurred!
       For full logs, run 'nix log /nix/store/fvig2bd6hfrh8njaplb84ia2f18h7mf7-openvdb-12.0.0.drv'.
```

### Notify maintainers

@guibou

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.58, NixOS, 24.11 (Vicuna), 24.11.20241030.d565bce`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/9aq8y2y2v47626vy3nm5wmy5x2a39bdp-source`

---

### PR DESCRIPTION
**Pull request by Scrumplex**
ZHF: #352882

Closes #353863

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by 06kellyjac** [comment]
I had a nixpkgs-review going but it got oom-kill-ed even though I have a significant amount of RAM :cry:
Running again with a slight limit on the nix-daemon :slightly_smiling_face:

**Comment by Scrumplex** [comment]
I also have a fairly powerful system, but it took a really long time to compile orca-slicer for me. Not quite sure what's up with the codebase

**Comment by 06kellyjac** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 354038`

---
### `x86_64-linux`
<details>
  <summary>:x: 4 packages failed to build:</summary>
  <ul>
    <li>bambu-studio</li>
    <li>bambu-studio.debug</li>
    <li>orca-slicer</li>
    <li>orca-slicer.debug</li>
  </ul>
</details>

**Comment by 06kellyjac** [comment]
Well a 48G limit on the daemon didn't help, it's still ramping up to 51G

I'm now running with 20/32 cores which should help

**Comment by Scrumplex** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 354038`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>bambu-studio</li>
    <li>bambu-studio.debug</li>
    <li>orca-slicer</li>
    <li>orca-slicer.debug</li>
  </ul>
</details>

**Comment by 06kellyjac** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 354038`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>bambu-studio</li>
    <li>bambu-studio.debug</li>
    <li>orca-slicer</li>
    <li>orca-slicer.debug</li>
  </ul>
</details>

**Review by 06kellyjac — APPROVED** [review]
less overlays = more happy

**Review by jnsgruk — APPROVED** [review]
LGTM assuming the eval jobs pass! Thanks!

**Pull request merged**
