### PR TITLE
Import cargo lock updates

### PR DESCRIPTION
**Pull request by happysalada**
###### Motivation for this change

cargoLock can now process urls like
git+https://github.com/qdequele/assert-json-diff?branch=master#9012a0c8866d0f2db0ef9a6242e4a19d1e8c67e4
or
git+https://github.com/Kerollmops/heed?tag=v0.12.1#fc017cf3394af737f92fd71e16f0499a78b79d65

those urls are coming from meilisearch https://github.com/meilisearch/MeiliSearch/blob/main/Cargo.lock

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [X] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by danieldk — CHANGES_REQUESTED** [review]
Cool, looks good! Could you perhaps add a unit test that covers the new cases?

**Comment by happysalada** [comment]
Sure, let me try to do this.
The actual repo doesn't build with buildRustPackage. I'll try to create two dummy repos with those dependencies.

**Comment by yu-re-ka** [comment]
I didn't see this one. https://github.com/NixOS/nixpkgs/pull/137303 tries to achieve the same thing.

This PR doesn't work for me:

```
    Updating git repository `https://github.com/KWARC/rust-libxml`
error: failed to get `libxml` as a dependency of package `testcrate v0.1.0 (/build/source)`

Caused by:
  failed to load source for dependency `libxml`

Caused by:
  Unable to update https://github.com/KWARC/rust-libxml?branch=master#14913eb0

Caused by:
  failed to clone into: /build/git/db/rust-libxml-d81a08cb24c2f4e4

Caused by:
  attempting to update a git repository, but --frozen was specified
builder for '/nix/store/yrbdgnfk2qwdsin1bc8gks7m3sypikqk-testcrate-0.1.0.drv' failed with exit code 101
```

Cargo.toml:
```
libxml = { git = "https://github.com/KWARC/rust-libxml", branch = "master" }
```

Cargo.lock:
```
source = "git+https://github.com/KWARC/rust-libxml?branch=master#14913eb077ad6d79a051b7f6b1f13e567588e998"
```

**Comment by happysalada** [comment]
happy to close this in favor of yours.

**Pull request closed without merging**
