### PR TITLE
graalvmCEPackages.nodejs-installable-svm: init at 22.3.1

### PR DESCRIPTION
**Pull request by thiagokokada**
###### Description of changes

Continuation of #216228.

Add `graalvmCEPackages.nodejs-installable-svm`. I think this is the last product that I am going to add, but it was a good addition since it helped find some bugs in the previous implementation.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by thiagokokada** [comment]
@ofborg build babashka bbin clj-kondo clojure-lsp jet neil zprint dbqn-native dapl-native graalvmCEPackages.graalvm11-ce-full graalvmCEPackages.graalvm17-ce-full

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 216532` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>30 packages built:</summary>
  <ul>
    <li>babashka</li>
    <li>bbin</li>
    <li>clj-kondo</li>
    <li>clojure-lsp</li>
    <li>dapl-native</li>
    <li>dbqn-native</li>
    <li>graalvm-ce (graalvm11-ce ,graalvmCEPackages.graalvm11-ce)</li>
    <li>graalvm17-ce (graalvmCEPackages.graalvm17-ce)</li>
    <li>graalvmCEPackages.graalvm11-ce-bare</li>
    <li>graalvmCEPackages.graalvm11-ce-full</li>
    <li>graalvmCEPackages.graalvm17-ce-bare</li>
    <li>graalvmCEPackages.graalvm17-ce-full</li>
    <li>graalvmCEPackages.js-installable-svm-java11</li>
    <li>graalvmCEPackages.js-installable-svm-java17</li>
    <li>graalvmCEPackages.llvm-installable-svm-java11</li>
    <li>graalvmCEPackages.llvm-installable-svm-java17</li>
    <li>graalvmCEPackages.native-image-installable-svm-java11</li>
    <li>graalvmCEPackages.native-image-installable-svm-java17</li>
    <li>graalvmCEPackages.nodejs-installable-svm-java11</li>
    <li>graalvmCEPackages.nodejs-installable-svm-java17</li>
    <li>graalvmCEPackages.python-installable-svm-java11</li>
    <li>graalvmCEPackages.python-installable-svm-java17</li>
    <li>graalvmCEPackages.ruby-installable-svm-java11</li>
    <li>graalvmCEPackages.ruby-installable-svm-java17</li>
    <li>graalvmCEPackages.wasm-installable-svm-java11</li>
    <li>graalvmCEPackages.wasm-installable-svm-java17</li>
    <li>jet</li>
    <li>neil</li>
    <li>vscode-extensions.betterthantomorrow.calva</li>
    <li>zprint</li>
  </ul>
</details>

**Comment by thiagokokada** [comment]
@ofborg build babashka bbin clj-kondo clojure-lsp jet neil zprint dbqn-native dapl-native graalvmCEPackages.graalvm11-ce-full graalvmCEPackages.graalvm17-ce-full

**Comment by thiagokokada** [comment]
@ofborg build babashka bbin clj-kondo clojure-lsp jet neil zprint dbqn-native dapl-native graalvmCEPackages.graalvm11-ce-full graalvmCEPackages.graalvm17-ce-full

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 216532` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>30 packages built:</summary>
  <ul>
    <li>babashka</li>
    <li>bbin</li>
    <li>clj-kondo</li>
    <li>clojure-lsp</li>
    <li>dapl-native</li>
    <li>dbqn-native</li>
    <li>graalvm-ce</li>
    <li>graalvm17-ce</li>
    <li>graalvmCEPackages.graalvm11-ce-bare</li>
    <li>graalvmCEPackages.graalvm11-ce-full</li>
    <li>graalvmCEPackages.graalvm17-ce-bare</li>
    <li>graalvmCEPackages.graalvm17-ce-full</li>
    <li>graalvmCEPackages.js-installable-svm-java11</li>
    <li>graalvmCEPackages.js-installable-svm-java17</li>
    <li>graalvmCEPackages.llvm-installable-svm-java11</li>
    <li>graalvmCEPackages.llvm-installable-svm-java17</li>
    <li>graalvmCEPackages.native-image-installable-svm-java11</li>
    <li>graalvmCEPackages.native-image-installable-svm-java17</li>
    <li>graalvmCEPackages.nodejs-installable-svm-java11</li>
    <li>graalvmCEPackages.nodejs-installable-svm-java17</li>
    <li>graalvmCEPackages.python-installable-svm-java11</li>
    <li>graalvmCEPackages.python-installable-svm-java17</li>
    <li>graalvmCEPackages.ruby-installable-svm-java11</li>
    <li>graalvmCEPackages.ruby-installable-svm-java17</li>
    <li>graalvmCEPackages.wasm-installable-svm-java11</li>
    <li>graalvmCEPackages.wasm-installable-svm-java17</li>
    <li>jet</li>
    <li>neil</li>
    <li>vscode-extensions.betterthantomorrow.calva</li>
    <li>zprint</li>
  </ul>
</details>

**Review by superherointj — APPROVED** [review]

**Review by AndersonTorres — APPROVED** [review]
Way better!

**Pull request merged**
