### PR TITLE
nixos/wordpress: caddy support

### PR DESCRIPTION
**Pull request by onny**
###### Motivation for this change
Adds caddy web server support to wordpress module which already supports httpd and nginx. Since most of the restructuring was already done by adding nginx support [here](https://github.com/NixOS/nixpkgs/pull/84446), this PR is quite reasonable. 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by onny** [comment]
Don't know how to fix the NixOS manual checks :(

**Comment by mohe2015** [comment]
> Don't know how to fix the NixOS manual checks :(

Just run nixos/doc/manual/md-to-db.sh

**Comment by happysalada** [comment]
One small thing, I'm trying to add the ability for caddy to merge multiple configs.
The idea being that if you enable caddy, it wouldn't override your config and you could just merge everything.
You might be interested by the PR https://github.com/NixOS/nixpkgs/pull/134384
It might affect slightly your PR.

**Comment by happysalada** [comment]
That PR has just been merged. There is now a virtualHosts option in caddy that works in the following way
```
caddy.virtualHosts."http://hostname" = {
   serverAliases = [ "www.hostname" ]; (optional)
   extraConfig = ''
          root    * /${pkg hostName cfg}/share/wordpress
          file_server
          php_fastcgi unix/${config.services.phpfpm.pools."wordpress-${hostName}".socket}
          @uploads {
            path_regexp path /uploads\/(.*)\.php
          }
          rewrite @uploads /
          @wp-admin {
            path  not ^\/wp-admin/*
          }
          rewrite @wp-admin {path}/index.php?{query}
   ''
};
```

basically at the moment everything is dumped into extraConfig. I'm open to feedback on what to options to extract from caddy users.
If you don't mind rebasing, I can help you get this merged.
(the one advantage of having the virtualhosts is that now caddy config is merged and not overridden, so caddy users can use caddy to expose other things).

**Comment by onny** [comment]
> That PR has just been merged. There is now a virtualHosts option in caddy that works in the following way
> 
> ```
> caddy.virtualHosts."http://hostname" = {
>    serverAliases = [ "www.hostname" ]; (optional)
>    extraConfig = ''
>           root    * /${pkg hostName cfg}/share/wordpress
>           file_server
>           php_fastcgi unix/${config.services.phpfpm.pools."wordpress-${hostName}".socket}
>           @uploads {
>             path_regexp path /uploads\/(.*)\.php
>           }
>           rewrite @uploads /
>           @wp-admin {
>             path  not ^\/wp-admin/*
>           }
>           rewrite @wp-admin {path}/index.php?{query}
>    ''
> };
> ```
> 
> basically at the moment everything is dumped into extraConfig. I'm open to feedback on what to options to extract from caddy users.
> If you don't mind rebasing, I can help you get this merged.
> (the one advantage of having the virtualhosts is that now caddy config is merged and not overridden, so caddy users can use caddy to expose other things).

Thank you for the info and for your work! I rebased this PR and it should work now :+1:

**Comment by happysalada** [comment]
Thank you!

**Pull request merged**
