### PR TITLE
ruby: remove unsupported versions

### PR DESCRIPTION
**Pull request by zimbatm**
###### Motivation for this change

Help with https://github.com/NixOS/nixpkgs/pull/22357 a bit.

Remove EOL ruby versions for security and maintenance reasons.

Only expose ruby_MAJOR_MINOR to the top-level. we don't provide
guarantees for the TINY version.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vcunat** [comment]
Sounds good.  I would also remove 2.2 before nixpkgs 18.03, as its maintenance is scheduled to [end in March](https://www.ruby-lang.org/en/news/2017/12/14/ruby-2-2-9-released/).

**Comment by zimbatm** [comment]
There is still work needed on that PR. Make sure the evaluation works and all packages depending on older ruby versions are marked as broken.

One thing that might also be considered is to switch the default ruby version to 2.4 or 2.5. I'm expecting that this will bring a lot of regressions.

**Comment by vcunat** [comment]
@globin switched the default to 2.4 in #22357.

**Comment by zimbatm** [comment]
@globin ok I switched the default ruby as well. looks like it's ready!

**Pull request merged**
