### PR TITLE
spidermonkey: 78.1.0 -> 78.4.0

### PR DESCRIPTION
**Pull request by lostnet**
###### Motivation for this change

This is a minor update, but has some security fixes https://www.mozilla.org/en-US/firefox/78.4.0/releasenotes/

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lostnet** [comment]
Aside from the direct update, I made the following changes:
1. The previous patches were promised to be integrated in 78.2 and seem to be (I verifiied that they all get rejected when applied to 78.4). So I removed them.

2. Spidermonkey commands have a version specific name that was copied without change since _60, I fixed that and verified it doesn't break dependent builds.

**Comment by lostnet** [comment]
@doronbehar  @mkg20001 I'm happy if @abbradar is interested in this, but looking at the history, I think spidermonkey_78 was primarily of interest to one of you as a dependency of cjs.

**Comment by doronbehar** [comment]
> @doronbehar @mkg20001 I'm happy if @abbradar is interested in this, but looking at the history, I think spidermonkey_78 was primarily of interest to one of you as a dependency of cjs.

Once the gnome 3.38 update will land in the unstable channels, I'd be able to test this PR and give it a :+1: . But maybe it'd be wise to merge it beforehand, since it's security related, :man_shrugging: .

**Comment by jtojnar** [comment]
Thanks.

**Pull request merged**
