### PR TITLE
nixos: fix minimal-kernel override mechanism

### PR DESCRIPTION
**Pull request by ghost**
###### Motivation for this change

After [patch](https://github.com/NixOS/nixpkgs/commit/da36847d925058fd86f027b64cc712c57be11ad8) for pull request #15095 was applied, [this](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/testing/minimal-kernel.nix#L16) code should be fixed. This PR is a first try to fix the issue.

Also this PR fixes kernel configuration parameter duplication issue in `configfile`.
###### Things done
- Built on platform(s)
  - [x] Linux
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by joachifm** [comment]
Could you add an explanation to the commit message, re what is wrong with the original and how the patch fixes the issue?

**Comment by joachifm** [comment]
cc @cstrahan

**Comment by tk-ecotelecom** [comment]
@cstrahan, please, review this.

**Comment by joachifm** [comment]
Sorry, I still fail to understand what the issue is exactly? Would you mind expanding on what about the kernel override mechanism is broken? Preferably with an example that illustrates the broken behavior vs desired result. That way we can perhaps get this integrated without needing feedback from the original implementor.

**Pull request closed without merging**
