### PR TITLE
Enable tests for Halide; replace llvmPackages.stdenv with stdenv

### PR DESCRIPTION
**Pull request by twesterhout**
###### Description of changes

Fixes errors in Nix-built Halide (see https://github.com/halide/Halide/issues/7442 for more info about the failures) by replacing `llvmPackages.stdenv` with `stdenv`.

Enables tests for the package (these were failing before this PR and pass now).

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [X] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by twesterhout** [comment]
@AtilaSaraiva @ck3d could you let me know if there's something I need to do before we can merge this?

**Comment by ck3d** [comment]
Result of `nixpkgs-review pr 224473` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>halide</li>
  </ul>
</details>

**Comment by twesterhout** [comment]
Thanks for checking!

> On my system the test 520 performance_memcpy failed.

Is this something that you can reproduce from run to run? And is that under a heavy system load?

As far as I know, Halide compares their simple memory copy implementation to the system one and asserts that it takes no longer than `3 * time(memcpy)`.

**Comment by ck3d** [comment]
I stopped using the web browser and re-started the build of Halide. And yes it finished without errors.
I think we should skip the test 520 to avoid randomly breaking builds.

**Comment by twesterhout** [comment]
> I think we should skip the test 520 to avoid randomly breaking builds.

Done in the latest commit.

**Comment by twesterhout** [comment]
On second thought, it might be better to disable all performance tests, since one other already failed here in CI. I think there are enough correctness tests in halide to ensure that the installation is successful.

**Review by ck3d — APPROVED** [review]
Thanks, LGTM

**Comment by twesterhout** [comment]
Sorry, clicked accidentally

**Review by ck3d — APPROVED** [review]

**Pull request merged**
