### PR TITLE
 thunderbird,  thunderbird-bin: 78.3.1 -> 78.3.2 

### PR DESCRIPTION
**Pull request by taku0**
###### Motivation for this change

- Bug fixes and updates.

https://www.thunderbird.net/en-US/thunderbird/78.3.2/releasenotes/

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by doronbehar** [comment]
@GrahamcOfBorg eval

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 100079` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>thunderbird</li>
    <li>thunderbird-bin</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
Thunderbird has been crashing on me every once in a while on startup or later during usage, but that isn't directly related to this specific version. Anyway, it happend to me twice while starting the binary from the `thunderbird` package.

```
[nix-shell:~/.cache/nixpkgs-review/pr-100079]$ ./results/thunderbird/bin/thunderbird 
[calBackendLoader] Using Thunderbird's libical backend
console.debug: "Successfully loaded OpenPGP library librnp.so from /nix/store/jnhnfnzszj1ygnaa8k030hfl41f95r1h-thunderbird-78.3.2/lib/thunderbird/librnp.so"
console.debug: "public keys: 29, secret keys: 2"
console.debug: "2 protected and 0 unprotected keys"
console.log: (new Error("Cannot load required OTR library", "resource:///modules/OTRLib.jsm", 75))
Gdk-Message: 01:00:44.429: Error 32 (Broken pipe) dispatching to Wayland display.

[nix-shell:~/.cache/nixpkgs-review/pr-100079]$ ./results/thunderbird/bin/thunderbird 
[calBackendLoader] Using Thunderbird's libical backend
console.debug: "Successfully loaded OpenPGP library librnp.so from /nix/store/jnhnfnzszj1ygnaa8k030hfl41f95r1h-thunderbird-78.3.2/lib/thunderbird/librnp.so"
console.debug: "public keys: 29, secret keys: 2"
console.debug: "2 protected and 0 unprotected keys"
console.log: (new Error("Cannot load required OTR library", "resource:///modules/OTRLib.jsm", 75))
console.error: Lightning: 
  [calCachedCalendar] replay action failed: <unknown>, uri=https://davical.darmstadt.ccc.de/public.php/foo/bar/, result=2147500037, operation=[xpconnect wrapped calIOperation]

(thunderbird:604): GLib-GIO-WARNING **: 01:01:02.956: Failed to execute child process “update-desktop-database” (No such file or directory)
Gdk-Message: 01:01:18.131: Error reading events from display: Broken pipe
```

I wonder if thunderbird should depend on `desktop-file-utils`. And then there is this odd error about being unable to load an OTR library. 

The latter error does not appear on the `thunderbird-bin` package.

Once up both versions do work.

**Comment by taku0** [comment]
I also get `Cannot load required OTR library` but it works fine with X.Org Server.

**Comment by vcunat** [comment]
I've never seen anyone using Thunderbird [for chat](https://wiki.mozilla.org/Thunderbird:OTR), so perhaps OTR in there has been broken 🤷🏽

**Review by vcunat — APPROVED** [review]
I used -bin for several minutes and the compiled one for about half a day.

**Comment by mweinelt** [comment]
FWIW: Please don't mistake my comment as a blocker. TB generally works
for me.

**Comment by vcunat** [comment]
👍🏽 I understood that *this* update doesn't seem to change those problems anyway.

**Comment by vcunat** [comment]
Oops, I unintentionally merged the previous version with incorrect commit message.

**Pull request closed without merging**
