### PR TITLE
apptainer: 1.3.1 -> 1.3.2

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Changelog: https://github.com/apptainer/apptainer/releases/tag/v1.3.2

cc @ShamrockLee 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 315423` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>apptainer</li>
    <li>apptainer-overriden-nixos</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 315423` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>apptainer</li>
    <li>apptainer-overriden-nixos</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
`apptainer.tests` builds fine on both `x86_64-linux` and `aarch64-linux`.

**Review by NickCao — APPROVED** [review]

**Comment by ShamrockLee** [comment]
CVE -2024-3727 affects `apptainer` on Nixpkgs 23.11 (Apptainer 1.2.5), as the latter [uses](https://github.com/apptainer/apptainer/blob/v1.2.5/go.mod#L20) an affected version (5.25.0) of go module `github.com/containers/image/v5 `.

> Backport failed for release-23.11, because it was unable to cherry-pick the commit(s).

Quite a few non-trivial changes are applied to `apptainer` and `singularity` packages between Nixpkgs 23.11 and 24.05. Automatic backport by cherry-picking is expected to fail.

> Please cherry-pick the changes locally and resolve any conflicts.

Instead of cherry-picking, it makes more sense to do a version bump manually based on `release-23.11` and pick changes necessary for the update from the `master` branch.

**Comment by risicle** [comment]
Is it nontrivial to bump the dependency in Apptainer 1.2.5?

**Comment by ShamrockLee** [comment]
> Is it nontrivial to bump the dependency in Apptainer 1.2.5?

That depends on the test result after bumping. Everything will be alright if 'apptainer` and `apptainer.tests` builds, and `nix run .#apptainer exec "$(nix build --no-link --print-out-paths .#apptainer.tests.image-hello-cowsay)" hello` runs.

**Comment by ShamrockLee** [comment]
> > Is it nontrivial to bump the dependency in Apptainer 1.2.5?
> 
> It'll be trivial, as most updates I could recall were simple version bumps. The actual case depends on the test result after bumping.

The only nontrivial` apptainer`-specific change between Nixpkgs 23.11 and Nixpkgs 24.05 is #280076. Let's just bump Apptainer to 1.2.5 on Nixpkgs 23.11.

**Comment by ShamrockLee** [comment]
> Is it nontrivial to bump the dependency in Apptainer 1.2.5?

Oops! I misunderstood what you were saying and thought you would like to bump Apptainer.

I haven't tried manually " bumping" the dependency version before, but it sounds hacky. Maybe it would be easier to bump the Apptainer version.

**Comment by ShamrockLee** [comment]
I made a backport PR targeting Nixpkgs 23.11 (#319649). Please take a look.

**Pull request merged**
