### PR TITLE
rPackages: overall update

### PR DESCRIPTION
**Pull request by michelk**
Updates created with

```
    Rscript generate-cran-packages.R > cran-packages.nix
```

### CODE REVIEW

**Comment by peti** [comment]
Test builds will run at http://hydra.cryp.to/jobset/nixpkgs/r-packages.

**Comment by peti** [comment]
This patch does not evaluate properly. The `default.nix` file configures extra properties for may builds that after this update no longer exist in `cran-packages.nix`. As it is, we cannot merge this.

**Comment by michelk** [comment]
Do we have a policy how to update r-packages? How is your workflow of doing so?
1. Run `Rscript generate-cran-packages.R > cran-packages.nix` 
2. Test build on  http://hydra.cryp.to/jobset/nixpkgs/r-packages
3. Adjust `default.nix` and patches according to `cran-packages.nix`. Have you any tools for this?

So what should I do, if I want to update r-packages. (2.) is currently not available to me. Should I make a pull request to https://github.com/peti/nixpkgs/tree/r-updates?

**Comment by peti** [comment]
As a rule, we cannot merge anything that breaks Nixpkgs evaluation. You can test whether your patch evaluates by running `nix-env -f /path/to/your/nixpkgs -qaP -A rPackages | tail -1`. If that succeeds, then it can be merged. The build tests are supposed to determine how many packages were fixed/broken, but this is something I do mostly for my own pleasure.

**Comment by iElectric** [comment]
This doesn't need much more work, just cleaning up default.nix

**Comment by michelk** [comment]
I updated the packages again and commented out all failures of `nix-env -f /path/to/your/nixpkgs -qaP -A rPackages | tail -1` in `default.nix`; now my personal package-set installs fine on my machine.

**Comment by peti** [comment]
When a package is removed from the set, it's fine to just erase the corresponding entries from `default.nix`; we don't need to keep them around for the future; the git history still has those entries for those who care.

Anyway, I'll start a new round of test builds at http://hydra.cryp.to/jobset/nixpkgs/r-packages to see what the current state of affairs is.

Thank you for your efforts.

**Pull request merged**
