### PR TITLE
gitu: init at 0.5.4

### PR DESCRIPTION
**Pull request by evanrichter**
## Things done

added [gitu](https://github.com/altsem/gitu), a standalone magit-like git client

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Aleksanaa — APPROVED** [review]
Please reword the commit message as `gitu: init at 0.5.2`

**Comment by evanrichter** [comment]
> Please reword the commit message as `gitu: init at 0.5.2`

done! I must be really tired :sweat_smile:

**Comment by sikmir** [comment]
[0.5.3](https://github.com/altsem/gitu/releases/tag/v0.5.3) is out

**Comment by sikmir** [comment]
Result of `nixpkgs-review pr 294443` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gitu</li>
  </ul>
</details>

**Comment by sikmir** [comment]
Some icons required?

Näyttökuva 2024-3-10 kello 21 01 27

**Comment by evanrichter** [comment]
> Some icons required?
> 
> 
> 
> Näyttökuva 2024-3-10 kello 21 01 27
> 
> 

Oh yes I guess so. It worked out of the box on wezterm on Linux, but I see the same thing on wezterm on macOS.

Not sure what the nixpkgs policy is on things like that, icons and fonts are a personal preference.  But it would be nice to show something besides `?`

**Review by Vonfry — APPROVED** [review]
LGTM. And there is no icon or front issues as well. 

I use alaccrity and some fonts with symbols in fontconfig. I think that issue cannot be packaged in this repo, which is depended on other parts.

**Review by patka-123 — APPROVED** [review]
I was packaging this myself, and before creating the PR I found this one haha. I had almost exactly the same.

LGTM!

**Review by adamcstephens — APPROVED** [review]

**Pull request merged**
