### PR TITLE
updating bitcoin to 0.11.0

### PR DESCRIPTION
**Pull request by sfultong**
bitcoin: 0.10.2 -> 0.11.0

### CODE REVIEW

**Comment by jagajaga** [comment]
Rename commit's name as it said in `CONTRIBUTNG.md`.

**Comment by sfultong** [comment]
@jagajaga does this look ok?

**Comment by sfultong** [comment]
Huh, Travis ran out of memory.

**Comment by jagajaga** [comment]
But you've tested it by yourself? :)

**Comment by sfultong** [comment]
I've been running it on my computer since this weekend.

**Pull request merged**
