### PR TITLE
tensorflow: 1.5.0 -> 1.8.0

### PR DESCRIPTION
**Pull request by mboes**
###### Motivation for this change

Upgrade to latest Tensorflow. Required by #40525.

cc @zimbatm @xeji 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg  build tensorflow

**Comment by xeji** [comment]
@GrahamcOfBorg  build python36Packages.tensorflow python36Packages.tensorflowWithCuda python27Packages.tensorflow python27Packages.tensorflowWithCuda

**Comment by xeji** [comment]
(deleted ofborg results were caused by my incorrect build command, sorry for the noise)

@mboes please fix the build for x86_64-linux (or does this require bazel 0.13 now?)

**Comment by mboes** [comment]
@xeji fixed. I used the sha256 corresponding to the output of building with Bazel v0.13 previously. I set it to that of building with Bazel 0.12 now. IIUC we'll have to update this again when Bazel v0.13 gets merged.

Incidentally, even when building with `--option build-use-sandbox true` I'm getting reproducibility issues where supplying the wrong output hash sometimes still works locally.

**Comment by xeji** [comment]
@GrahamcOfBorg build python36Packages.tensorflow python27Packages.tensorflow

**Comment by zimbatm** [comment]
> ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': Error downloading [https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/08039ba8ca59f64248bb3b6ae016460fe9c9914f.tar.gz, https://github.com/bazelbuild/rules_closure/archive/08039ba8ca59f64248bb3b6ae016460fe9c9914f.tar.gz] to /build/output/external/io_bazel_rules_closure/08039ba8ca59f64248bb3b6ae016460fe9c9914f.tar.gz: All mirrors are down: [Unknown host: github.com, Unknown host: mirror.bazel.build]

What is the best way to pre-populate these external fetches done by Bazel? Nix doesn't allow the downloading because of the sandbox.

**Comment by globin** [comment]
cc @abbradar

**Comment by mboes** [comment]
Shelving this for now.

**Comment by grwlf** [comment]
Just a note: I've independently attempted to build tensorflow 1.8 from source. Used older bazel 0.10 for this. Faced issue related to hardening:

NixOS appends -D_FORTIFY_SOURCE macro to any gcc arguments unless `hardeningDIsable=all` is present in the environment. Our build expression sets this variable, but, unfortunately, tf1.8 prepends `env -` before every bazel action, so this hardening is re-enabled. This eventually leads to "macro redefied" warning, and finally, -Werror does its job to stop the show. Ridiculous.

**Comment by grwlf** [comment]
I turned nixHacks off, but I think caching or sandboxing is not the cause of my errors. Bazel seems to react on setting `CC` and `CXX` correctly. Regarding your options:
 * `--action_env` doesn't seem to work in tensorflow's case because TF prepends `exec env - PATH=... PWD=... ` to every action, so the environment is almost empty at the time of GCC execution. This is not a bazel problem.
 * `--copt` and `--linkoopt` seem to ignore extra 'U_FORTIFY_SOURCE`
I'll continue trying to wrap GCC in a way that disable hardening. Passing unwrapped CC cause some problems with `execve` which I don't understand yet.

**Comment by uri-canva** [comment]
By TF do you mean the normal bazel build process or does TF do something special? `exec env - PATH=... PWD=...` is what Bazel always does, but you can pass envs through using `--action_env`, except for cc actions, see bazelbuild/bazel#3642 for example.

You can unwrap the various layer and test things by using `nix-shell` and bazel's `-s`, `--verbose_failures` and `--sandbox_debug` flags.

**Comment by grwlf** [comment]
I was able to overcome the `_FORTIFY_SOURCE` problem with the following hand-made GCC wrapper
```
    gccnh = stdenv.mkDerivation {
      name = "gccnh";
      buildCommand = ''
        . $stdenv/setup
        mkdir -p $out/bin

        for prog in as  c++  cc  cpp  g++  ld  ld.bfd  ld.gold ; do
          ln -s ${stdenv.cc}/bin/$prog $out/bin/$prog
        done

        cat >$out/bin/gcc <<"EOF"
        #!/bin/sh
        export hardeningDisable=all
        exec "${stdenv.cc}/bin/gcc" "''${extraFlagsArray[@]}" "$@"
        EOF
        chmod +x $out/bin/gcc
        '';
    };
```

I used this wrapper manually, inside nix-shell, as following:

```
$ CC="$gccnh/bin/gcc" bazel build $bazelTarget
```

Not sure if hardening was the only problem or not (bazel still works)

**Comment by globin** [comment]
@grwlf you can use `(python3.withPackages (ps: with ps; [ numpy ]))`

**Comment by uri-canva** [comment]
For the gcc flags see #42832 for an example of configuring a bazel toolchain. That makes the whole nix hacks and wrappers redundant at least as far as bazel goes.

**Comment by grwlf** [comment]
For the reference, I keep my work files here https://github.com/grwlf/nixpkgs/tree/tf18/pkgs/development/python-modules/tensorflow

**Pull request closed without merging**
