### PR TITLE
vimPlugins.cmp-*: Init

### PR DESCRIPTION
**Pull request by pyrox0**
###### Description of changes
Adds a bunch of sources for cmp, a neovim completion framework.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by teto** [comment]
are the fuzzy-nvim/nvim-snippy necessary for the other plugins ?

**Comment by ModdedGamers** [comment]
> are the fuzzy-nvim/nvim-snippy necessary for the other plugins ?

Yes. There is an fuzzy-nvim integration plugin as well as an nvim-snippy integration plugin for cmp.

**Comment by teto** [comment]
what is missing to leave the "draft" status (apart from a rebase) ?

**Comment by theHedgehog0** [comment]
> what is missing to leave the "draft" status (apart from a rebase) ?

I'll rebase, then it should be good to go. I added draft status while I was adding dependencies. I'll make a second pass to confirm that I've added all needed dependencies.

**Comment by theHedgehog0** [comment]
Should be ready for merging!

**Comment by teto** [comment]
I ran `nixpkgs-review pr 172862` and hit:
```
error: undefined variable 'neosnippet'

       at /home/teto/.cache/nixpkgs-review/pr-172862/nixpkgs/pkgs/applications/editors/vim/plugins/overrides.nix:187:42:

          186|   cmp-neosnippet = super.cmp-neosnippet.overrideAttrs (old: {
          187|     dependencies = with self; [ nvim-cmp neosnippet ];
             |                                          ^
          188|   });
(use '--show-trace' to show detailed location information)
```

**Comment by theHedgehog0** [comment]
Should be fixed now.

**Comment by teto** [comment]
Result of `nixpkgs-review pr 172862` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>28 packages built:</summary>
  <ul>
    <li>spacevim</li>
    <li>tests.vim.test_vim_with_vim_nix</li>
    <li>vimPlugins.cmp-clippy</li>
    <li>vimPlugins.cmp-cmdline-history</li>
    <li>vimPlugins.cmp-conventionalcommits</li>
    <li>vimPlugins.cmp-copilot</li>
    <li>vimPlugins.cmp-dap</li>
    <li>vimPlugins.cmp-dictionary</li>
    <li>vimPlugins.cmp-digraphs</li>
    <li>vimPlugins.cmp-fish</li>
    <li>vimPlugins.cmp-fuzzy-buffer</li>
    <li>vimPlugins.cmp-fuzzy-path</li>
    <li>vimPlugins.cmp-git</li>
    <li>vimPlugins.cmp-greek</li>
    <li>vimPlugins.cmp-look</li>
    <li>vimPlugins.cmp-neosnippet</li>
    <li>vimPlugins.cmp-npm</li>
    <li>vimPlugins.cmp-nvim-lsp-signature-help</li>
    <li>vimPlugins.cmp-nvim-tags</li>
    <li>vimPlugins.cmp-pandoc-nvim</li>
    <li>vimPlugins.cmp-rg</li>
    <li>vimPlugins.cmp-snippy</li>
    <li>vimPlugins.cmp-tmux</li>
    <li>vimPlugins.cmp-vim-lsp</li>
    <li>vimPlugins.cmp-vimwiki-tags</li>
    <li>vimPlugins.cmp-zsh</li>
    <li>vimPlugins.fuzzy-nvim</li>
    <li>vimPlugins.nvim-snippy</li>
  </ul>
</details>

**Comment by teto** [comment]
I haven't tried installing those plugins yet but will do as I already use cmp-nvim interactively. I'll ping youif I find any (nix) issue then :p

**Comment by theHedgehog0** [comment]
Sounds great!

**Pull request merged**
