### PR TITLE
just: 1.11.0 -> 1.12.0

### PR DESCRIPTION
**Pull request by adamcstephens**
- just: 1.11.0 -> 1.13.0
- just: add adamcstephens as maintainer

https://github.com/casey/just/blob/1.13.0/CHANGELOG.md

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by adamcstephens** [comment]
Result of `nixpkgs-review pr 210527` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>dogdns</li>
    <li>just</li>
    <li>kabeljau</li>
  </ul>
</details>

**Comment by adamcstephens** [comment]
Result of `nixpkgs-review pr 210527` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>dogdns</li>
    <li>just</li>
    <li>kabeljau</li>
  </ul>
</details>

**Comment by adamcstephens** [comment]
I'm going to convert this to a draft. This tag hasn't been converted to a release yet, and the upstream aarch64 build failed for a different reason.

https://github.com/casey/just/actions/runs/3908675689/jobs/6679021229

I'll keep an eye on what happens with this release/tag.

**Comment by adamcstephens** [comment]
Upstream CI has now passed and the release has been cut: https://github.com/casey/just/releases/tag/1.11.0

My rebuild on actual aarch64-linux passed, so I'm considering this ready again.

**Comment by Mic92** [comment]
Result of `nixpkgs-review pr 210527` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>dogdns</li>
    <li>just</li>
    <li>kabeljau</li>
  </ul>
</details>

**Comment by adamcstephens** [comment]
Upstream appears to be having some CI issues, so not sure what's going on here.

**Comment by adamcstephens** [comment]
Sorry everyone if you see this, I apparently completely messed up this rebase and missed it until after push.

**Pull request closed without merging**
