### PR TITLE
rmapi: 0.0.13 -> 0.0.15

### PR DESCRIPTION
**Pull request by benneti**
###### Motivation for this change
upstream update

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TaiBa131** [comment]
This should solves https://github.com/NixOS/nixpkgs/issues/123665

How did you end up with those SHA256sums though ?
Doing the same thing, I ended up with:
`sha256 = "0ccbn2399jbv9a1vfvvlv0w7g3w5li1kr2w1wng2qrvp4wjpivlf";`
and
`vendorSha256 = "05bhkljg581wpb4spp8bwaw9fmy7k2d8j4h93flca9hlqimz8ks8";`

**Comment by benneti** [comment]
I just removed them and tried to compile, and then used the ones nix told me to.
And yes it made connecting to the cloud possible for me.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 123672` at f2923147 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>rmapi</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`agpl3` is a deprecated license, please check if project uses `agpl3Plus` or `agpl3Only` and change `meta.license` accordingly.

Near pkgs/applications/misc/remarkable/rmapi/default.nix:22:5:
```
   |
22 |     license = licenses.agpl3;
   |     ^
```
</li>
  </ul>
</details>

**Comment by wamserma** [comment]
>       ```
>          |
>       22 |     license = licenses.agpl3;
>          |     ^
>       ```

This can be changed to `agpl3Only`.

**Comment by benneti** [comment]
done and squashed

**Review by wamserma — APPROVED** [review]
Built and tested.

@jonringer This should be merged before 21.05 is forked.

**Comment by NickHu** [comment]
> This should solves #123665
> 
> How did you end up with those SHA256sums though ?
> Doing the same thing, I ended up with:
> `sha256 = "0ccbn2399jbv9a1vfvvlv0w7g3w5li1kr2w1wng2qrvp4wjpivlf";`
> and
> `vendorSha256 = "05bhkljg581wpb4spp8bwaw9fmy7k2d8j4h93flca9hlqimz8ks8";`

They are the same hash, but you have put it in base32 format, whereas this commit has them in SRI (base64 + header) format (You can convert with the `nix hash to-sri` and `nix hash to-base32` commands). I suppose the reason you're seeing differences is because the PR author is potentially using the experimental version of `nix` - you need to do this to use flakes for instance. I think we're at the point now where we can use SRI hashes without worrying about backwards compatibility.

**Comment by benneti** [comment]
Indeed my system uses flakes!

**Comment by NickHu** [comment]
I cherry-picked this into stable also, seeing as the previous versions no longer work.

**Pull request merged**
