### PR TITLE
Mumps: add variant mumps_par with mpi support

### PR DESCRIPTION
**Pull request by qbisi**
## Change log
mumps: keep mumps mostly unchanged except the optimized build flag "-O3".
mumps_par: add new varient mumps with mpiSupport, with optional parmetis(unfree) and ptscotch support.
Testing build of mumps_par with parmetis and ptscotch are passed on x86_64-linux and aarch64-linux.
Build of mumps_par failed on darwin platform due to broken dependency of scalapack.

Many downstream scientific packages need mumps_par, for exemple: mfem(to be contributed), pastix(to be contributed), petsc.

This pull request will be ready to be reviewed until the pr https://github.com/NixOS/nixpkgs/pull/350824 is merged.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [x] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by nim65s** [comment]
Result of `nixpkgs-review pr 351476` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>50 packages built:</summary>
  <ul>
    <li>aligator</li>
    <li>aligator.doc</li>
    <li>bonmin</li>
    <li>casadi</li>
    <li>crocoddyl</li>
    <li>crocoddyl.doc</li>
    <li>ipopt</li>
    <li>openturns</li>
    <li>pinocchio</li>
    <li>pinocchio.doc</li>
    <li>proxsuite-nlp</li>
    <li>proxsuite-nlp.doc</li>
    <li>python311Packages.aerosandbox</li>
    <li>python311Packages.aerosandbox.dist</li>
    <li>python311Packages.aligator</li>
    <li>python311Packages.aligator.doc</li>
    <li>python311Packages.casadi</li>
    <li>python311Packages.crocoddyl</li>
    <li>python311Packages.crocoddyl.doc</li>
    <li>python311Packages.example-robot-data</li>
    <li>python311Packages.example-robot-data.doc</li>
    <li>python311Packages.neuralfoil</li>
    <li>python311Packages.neuralfoil.dist</li>
    <li>python311Packages.openturns</li>
    <li>python311Packages.pinocchio</li>
    <li>python311Packages.pinocchio.doc</li>
    <li>python311Packages.proxsuite-nlp</li>
    <li>python311Packages.proxsuite-nlp.doc</li>
    <li>python311Packages.tsid</li>
    <li>python311Packages.tsid.doc</li>
    <li>python312Packages.aerosandbox</li>
    <li>python312Packages.aerosandbox.dist</li>
    <li>python312Packages.aligator</li>
    <li>python312Packages.aligator.doc</li>
    <li>python312Packages.casadi</li>
    <li>python312Packages.crocoddyl</li>
    <li>python312Packages.crocoddyl.doc</li>
    <li>python312Packages.example-robot-data</li>
    <li>python312Packages.example-robot-data.doc</li>
    <li>python312Packages.neuralfoil</li>
    <li>python312Packages.neuralfoil.dist</li>
    <li>python312Packages.openturns</li>
    <li>python312Packages.pinocchio</li>
    <li>python312Packages.pinocchio.doc</li>
    <li>python312Packages.proxsuite-nlp</li>
    <li>python312Packages.proxsuite-nlp.doc</li>
    <li>python312Packages.tsid</li>
    <li>python312Packages.tsid.doc</li>
    <li>tsid</li>
    <li>tsid.doc</li>
  </ul>
</details>

**Comment by nim65s** [comment]
Result of `nixpkgs-review pr 351476` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>55 packages built:</summary>
  <ul>
    <li>aligator</li>
    <li>aligator.doc</li>
    <li>bonmin</li>
    <li>casadi</li>
    <li>crocoddyl</li>
    <li>crocoddyl.doc</li>
    <li>ipopt</li>
    <li>mumps</li>
    <li>mumps_par</li>
    <li>openturns</li>
    <li>pagmo2</li>
    <li>pinocchio</li>
    <li>pinocchio.doc</li>
    <li>proxsuite-nlp</li>
    <li>proxsuite-nlp.doc</li>
    <li>python311Packages.aerosandbox</li>
    <li>python311Packages.aerosandbox.dist</li>
    <li>python311Packages.aligator</li>
    <li>python311Packages.aligator.doc</li>
    <li>python311Packages.casadi</li>
    <li>python311Packages.crocoddyl</li>
    <li>python311Packages.crocoddyl.doc</li>
    <li>python311Packages.example-robot-data</li>
    <li>python311Packages.example-robot-data.doc</li>
    <li>python311Packages.neuralfoil</li>
    <li>python311Packages.neuralfoil.dist</li>
    <li>python311Packages.openturns</li>
    <li>python311Packages.pinocchio</li>
    <li>python311Packages.pinocchio.doc</li>
    <li>python311Packages.proxsuite-nlp</li>
    <li>python311Packages.proxsuite-nlp.doc</li>
    <li>python311Packages.pygmo</li>
    <li>python311Packages.tsid</li>
    <li>python311Packages.tsid.doc</li>
    <li>python312Packages.aerosandbox</li>
    <li>python312Packages.aerosandbox.dist</li>
    <li>python312Packages.aligator</li>
    <li>python312Packages.aligator.doc</li>
    <li>python312Packages.casadi</li>
    <li>python312Packages.crocoddyl</li>
    <li>python312Packages.crocoddyl.doc</li>
    <li>python312Packages.example-robot-data</li>
    <li>python312Packages.example-robot-data.doc</li>
    <li>python312Packages.neuralfoil</li>
    <li>python312Packages.neuralfoil.dist</li>
    <li>python312Packages.openturns</li>
    <li>python312Packages.pinocchio</li>
    <li>python312Packages.pinocchio.doc</li>
    <li>python312Packages.proxsuite-nlp</li>
    <li>python312Packages.proxsuite-nlp.doc</li>
    <li>python312Packages.pygmo</li>
    <li>python312Packages.tsid</li>
    <li>python312Packages.tsid.doc</li>
    <li>tsid</li>
    <li>tsid.doc</li>
  </ul>
</details>

**Review by nim65s — COMMENTED** [review]
Maybe you can add a comment next to `withParmetis ? false` saying it is unfree

**Review by nim65s — APPROVED** [review]
Thanks !

**Comment by MatthewCroughan** [comment]
This is amazing. Thanks for the hard work, will merge this as soon as you fix the conflict, as it is tested working with https://github.com/MatthewCroughan/codedisaster/pull/1

**Review by nim65s — APPROVED** [review]

**Review by MatthewCroughan — APPROVED** [review]

**Pull request merged**
