### PR TITLE
rustc: 1.6.0 -> 1.7.0. Enable Darwin platform.

### PR DESCRIPTION
**Pull request by retrry**
###### Things done:
- [x] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- Built on platform(s)
  - [x] NixOS
  - [x] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Updated to Rust 1.7.0. Now rust network tests pass and do not fail on Darwin.

@copumpkin @pikajude nix-build option with sandbox enabled fails for me. Could you help debug me those as I don't have enough expertise in Darwin things.

```
$ nix-build --option build-use-chroot relaxed -A rustc
these derivations will be built:
  /nix/store/pids5n5s8hvixms06fcsj4sfz1rrhazg-rustc-1.7.0.drv
building path(s) ‘/nix/store/hp4v5c5xlkb4gvpnrd5dcpanixsgf4mz-rustc-1.7.0-doc’, ‘/nix/store/nq046bklqhgjm7zp01smbdxvcb2kzzbz-rustc-1.7.0’
killing process 7334
killing process 7334: Operation not permitted
error: while setting up the build environment: changing into ‘/private/var/folders/j7/4_0kh_7n6574vdxv_q0b4_1h0000gn/T/nix-build-rustc-1.7.0.drv-0’: No such file or directory
```

---

_Please note, that points are not mandatory, but rather desired._

### CODE REVIEW

**Comment by copumpkin** [comment]
@retrry I don't generally expect the sandbox stuff to work on OSX right now. We'll fix it eventually, but for now I'd just disregard.

**Comment by retrry** [comment]
@copumpkin ok, I will ignore it for now.

Just built it on NixOS. All tests pass.

**Comment by zimbatm** [comment]
I'm getting the following error when running `nox-review`
```
output path ‘/nix/store/ydslfpzcy6whfrhpgghb0ysyz9yglirz-exa-2016-03-22-fetch’ has r:sha256 hash ‘1rg4gxx8m2q47m3mzlw3g4a6351dj513k9m740r0qh63p4v8yncc’ when ‘18anwh235kzziq6z7md8f3rl2xl4l9d4ivsqw9grkb7yivd5j0jk’ was expected
cannot build derivation ‘/nix/store/zn53c436bk3wssh26m7424g42gjyar83-exa-2016-03-22.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/zn53c436bk3wssh26m7424g42gjyar83-exa-2016-03-22.drv’ failed
The invocation of "nix-build -A rustPlatform.rustc -A rustfmt -A heatseeker -A racerRust -A cargo -A cfdyndns -A exa /home/zimbatm/.nox/nixpkgs" failed
```

**Comment by retrry** [comment]
Thanks I'll look into those errors.

**Comment by retrry** [comment]
@zimbatm fixed exa error and rebased branch. Now nox-review passes for me.

**Comment by flosse** [comment]
FYI: [Version 1.8 released](http://blog.rust-lang.org/2016/04/14/Rust-1.8.html)

**Comment by retrry** [comment]
I'm waiting for this to be merged so I could move to cargo compatibility with Darwin and Rust 1.8.0 version.

**Comment by retrry** [comment]
Ping to maintainers for review/feedback: @madjar @cstrahan @wizeman @globin @havvy @wkennington.
I would like to get this merged and I would like to know, what can I improve in these commits to get them to mergable state.

**Comment by zimbatm** [comment]
sorry for the wait !

**Comment by retrry** [comment]
No problem, thanks! :)

**Pull request merged**
