### PR TITLE
virtualbox: 6.1.4 -> 6.1.6

### LINKED ISSUE #84586: virtualbox kernel drivers broken on latest master with latest kernel
**Describe the bug**
Virtualbox kernel drivers don't build with latest kernel.

**To Reproduce**

**on latest master, channel hasn't updated yet**

1. `d=(import /home/maciej/Projekte/nix { configuration = {pkgs, ...}: { boot.kernelPackages = pkgs.linuxPackages_latest; virtualisation.virtualbox.host.enable = true; }; }).vm   
`
2. `:b d`

**Expected behavior**
Builds

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.13, NixOS, 20.09pre-git (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-20.09pre218613.ae6bdcc5358"`
 - channels(maciej): `"nixpkgs-20.09pre218717.05f0934825c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by B4dM4n**
###### Motivation for this change

Fix kernel module build with linux 5.6.

Fixes: #84586

###### Things done

The tests are currently broken and I don't have the time to fix them. 
It looks like the Virtualbox VM's in the tests start booting, but the kernel never reaches the `init` script.

Booting a VM (Windows and Linux) under NixOS with Linux 5.6 worked for me.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by flokli** [comment]
@B4dM4n were the tests already broken before? In any case, could you mark them as broken?

**Comment by flokli** [comment]
It'd be really nice if you or some of the other regular contributors could find some time to port the tests to python and fix them. It's a pity they don't work currently - they automated a lot of testing and very often uncovered some (even upstream) bugs.

cc @wkral @ambrop72 @knedlsepp @grahamc

**Comment by Lucus16** [comment]
I'm trying to debug the tests, findings so far:
`/tmp/.vbox-*-ipc/` does not exist due to `/tmp` does not have sticky bit set

**Comment by Lucus16** [comment]
In retrospect, that may be some unrelated bug that only occurs on my system, although that's still weird.

**Comment by flokli** [comment]
Let's merge this in, the tests were already broken before.

**Comment by jcumming** [comment]
```
kBuild: Linking SSMStandalone                                                                      
Error! Cannot find file '/build/VirtualBox-6.1.6/out/linux.amd64/release/obj/VBoxPcBios32/pci32.obj'                                                
```

**Comment by jcumming** [comment]
Fails with hardening enabled, too. :(

I'll try and figure out what I broke...

**Comment by flokli** [comment]
@jcumming  I can build `virtualbox`, `virtualboxWithExtpack` and `virtualboxHardened` from latest master :shrug:

**Pull request merged**
