### PR TITLE
gitlab: 13.6.1 -> 13.7.1

### PR DESCRIPTION
**Pull request by jslight90**
###### Motivation for this change

Update to the latest release of GitLab.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — COMMENTED** [review]
I think you where using an older version of vgo2nix. Could you regenerate the files with the newest version?

**Comment by jslight90** [comment]
> I think you where using an older version of vgo2nix. Could you regenerate the files with the newest version?

You want me to use the new version from c60ef6a249b952ed975c51a8701d1bd22a6185d1?

**Comment by petabyteboy** [comment]
Tested: Upgrade from 13.6.1, created a repository, cloned a repository, pushed to a repository, edited a file in the web editor, created a MR and merged it.

**Comment by jslight90** [comment]
After upgrading one of our gitlab servers, I had to flush the feature_flag configuration files before the gitlab service would start:
`rm -rf /var/gitlab/state/config/feature_flags/*`

**Pull request merged**
