### PR TITLE
sketchybar: 2.15.2 -> 2.16.1

### PR DESCRIPTION
**Pull request by khaneliman**
## Description of changes

https://github.com/FelixKratz/SketchyBar/releases/tag/v2.16.1

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by khaneliman** [comment]
Currently getting this error:

```bash
nix-build --attr pkgs.sketchybar
this derivation will be built:
  /nix/store/4pas9210ydg0nw2mij5mclx90p73x412-sketchybar-2.16.0.drv
building '/nix/store/4pas9210ydg0nw2mij5mclx90p73x412-sketchybar-2.16.0.drv'...
unpacking sources
unpacking source archive /nix/store/rd5lvshk0rfzdg6qi46kzk34lp7bgbww-source
source root is source
patching sources
updateAutotoolsGnuConfigScriptsPhase
configuring
no configure script, doing nothing
building
build flags: SHELL=/nix/store/wbpbgy7a09bicknf1yl397mqyyfs0kv7-bash-5.2-p15/bin/bash arm64
mkdir bin
clang -c -o bin/alias.o src/alias.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target arm64-apple-macos11
clang -c -o bin/background.o src/background.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target arm64-apple-macos11
clang -c -o bin/bar_item.o src/bar_item.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target arm64-apple-macos11
clang -c -o bin/custom_events.o src/custom_events.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target arm64-apple-macos11
clang -c -o bin/event.o src/event.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target arm64-apple-macos11
clang -c -o bin/graph.o src/graph.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target arm64-apple-macos11
clang -c -o bin/image.o src/image.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target arm64-apple-macos11
clang -c -o bin/mouse.o src/mouse.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target arm64-apple-macos11
clang -c -o bin/shadow.o src/shadow.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target arm64-apple-macos11
clang -c -o bin/font.o src/font.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target arm64-apple-macos11
clang -c -o bin/text.o src/text.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target arm64-apple-macos11
clang -c -o bin/message.o src/message.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target arm64-apple-macos11
clang -c -o bin/bar.o src/bar.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target arm64-apple-macos11
clang -c -o bin/color.o src/color.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target arm64-apple-macos11
clang -c -o bin/window.o src/window.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target arm64-apple-macos11
clang -c -o bin/bar_manager.o src/bar_manager.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target arm64-apple-macos11
clang -c -o bin/display.o src/display.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target arm64-apple-macos11
clang -c -o bin/group.o src/group.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target arm64-apple-macos11
clang -c -o bin/mach.o src/mach.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target arm64-apple-macos11
clang -c -o bin/popup.o src/popup.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target arm64-apple-macos11
clang -c -o bin/animation.o src/animation.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target arm64-apple-macos11
clang -c -o bin/workspace.om src/workspace.m -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target arm64-apple-macos11
clang -c -o bin/volume.o src/volume.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target arm64-apple-macos11
clang -c -o bin/slider.o src/slider.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target arm64-apple-macos11
clang -c -o bin/power.o src/power.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target arm64-apple-macos11
clang -c -o bin/wifi.om src/wifi.m -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target arm64-apple-macos11
clang -c -o bin/media.om src/media.m -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target arm64-apple-macos11
src/media.m:87:25: error: expected a type
- (void)playing_change:(NSNotification *)notification {
                        ^
src/media.m:95:23: error: expected a type
- (void)media_change:(NSNotification *)notification {
                      ^
src/media.m:28:8: error: use of undeclared identifier 'NSNotificationCenter'
      [NSNotificationCenter.defaultCenter addObserver:self
       ^
src/media.m:33:8: error: use of undeclared identifier 'NSNotificationCenter'
      [NSNotificationCenter.defaultCenter addObserver:self
       ^
src/media.m:38:8: error: use of undeclared identifier 'NSNotificationCenter'
      [NSNotificationCenter.defaultCenter addObserver:self
       ^
src/media.m:51:40: warning: instance method '-UTF8String' not found (return type defaults to 'id') [-Wobjc-method-access]
      const char* app_cstr = [self.app UTF8String];
                                       ^~~~~~~~~~
/nix/store/km68nqhsk0h20ajnlqys3cnlqshs7cgv-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:238:8: note: receiver is instance of class declared here
@class NSString;
       ^
src/media.m:51:19: warning: incompatible pointer types initializing 'const char *' with an expression of type 'id' [-Wincompatible-pointer-types]
      const char* app_cstr = [self.app UTF8String];
                  ^          ~~~~~~~~~~~~~~~~~~~~~
src/media.m:52:46: warning: instance method '-UTF8String' not found (return type defaults to 'id') [-Wobjc-method-access]
      const char* artist_cstr = [self.artist UTF8String];
                                             ^~~~~~~~~~
/nix/store/km68nqhsk0h20ajnlqys3cnlqshs7cgv-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:238:8: note: receiver is instance of class declared here
@class NSString;
       ^
src/media.m:52:19: warning: incompatible pointer types initializing 'const char *' with an expression of type 'id' [-Wincompatible-pointer-types]
      const char* artist_cstr = [self.artist UTF8String];
                  ^             ~~~~~~~~~~~~~~~~~~~~~~~~
src/media.m:53:44: warning: instance method '-UTF8String' not found (return type defaults to 'id') [-Wobjc-method-access]
      const char* title_cstr = [self.title UTF8String];
                                           ^~~~~~~~~~
/nix/store/km68nqhsk0h20ajnlqys3cnlqshs7cgv-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:238:8: note: receiver is instance of class declared here
@class NSString;
       ^
src/media.m:53:19: warning: incompatible pointer types initializing 'const char *' with an expression of type 'id' [-Wincompatible-pointer-types]
      const char* title_cstr = [self.title UTF8String];
                  ^            ~~~~~~~~~~~~~~~~~~~~~~~
src/media.m:54:44: warning: instance method '-UTF8String' not found (return type defaults to 'id') [-Wobjc-method-access]
      const char* album_cstr = [self.album UTF8String];
                                           ^~~~~~~~~~
/nix/store/km68nqhsk0h20ajnlqys3cnlqshs7cgv-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:238:8: note: receiver is instance of class declared here
@class NSString;
       ^
src/media.m:54:19: warning: incompatible pointer types initializing 'const char *' with an expression of type 'id' [-Wincompatible-pointer-types]
      const char* album_cstr = [self.album UTF8String];
                  ^            ~~~~~~~~~~~~~~~~~~~~~~~
src/media.m:99:32: error: property 'userInfo' not found on object of type 'const id'
      self.app = [notification.userInfo valueForKey:kMRMediaRemoteNowPlayingApplicationDisplayNameUserInfoKey];
                               ^
src/media.m:100:27: warning: instance method '-valueForKey:' not found (return type defaults to 'id') [-Wobjc-method-access]
      self.artist = [dict valueForKey:kMRMediaRemoteNowPlayingInfoArtist];
                          ^~~~~~~~~~~
/nix/store/km68nqhsk0h20ajnlqys3cnlqshs7cgv-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:244:8: note: receiver is instance of class declared here
@class NSDictionary;
       ^
src/media.m:101:26: warning: instance method '-valueForKey:' not found (return type defaults to 'id') [-Wobjc-method-access]
      self.title = [dict valueForKey:kMRMediaRemoteNowPlayingInfoTitle];
                         ^~~~~~~~~~~
/nix/store/km68nqhsk0h20ajnlqys3cnlqshs7cgv-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:244:8: note: receiver is instance of class declared here
@class NSDictionary;
       ^
src/media.m:102:26: warning: instance method '-valueForKey:' not found (return type defaults to 'id') [-Wobjc-method-access]
      self.album = [dict valueForKey:kMRMediaRemoteNowPlayingInfoAlbum];
                         ^~~~~~~~~~~
/nix/store/km68nqhsk0h20ajnlqys3cnlqshs7cgv-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:244:8: note: receiver is instance of class declared here
@class NSDictionary;
       ^
11 warnings and 6 errors generated.
make: *** [makefile:61: bin/media.om] Error 1
error: builder for '/nix/store/4pas9210ydg0nw2mij5mclx90p73x412-sketchybar-2.16.0.drv' failed with exit code 2;
       last 50 log lines:
       > src/media.m:52:46: warning: instance method '-UTF8String' not found (return type defaults to 'id') [-Wobjc-method-access]
       >       const char* artist_cstr = [self.artist UTF8String];
       >                                              ^~~~~~~~~~
       > /nix/store/km68nqhsk0h20ajnlqys3cnlqshs7cgv-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:238:8: note: receiver is instance of class declared here
       > @class NSString;
       >        ^
       > src/media.m:52:19: warning: incompatible pointer types initializing 'const char *' with an expression of type 'id' [-Wincompatible-pointer-types]
       >       const char* artist_cstr = [self.artist UTF8String];
       >                   ^             ~~~~~~~~~~~~~~~~~~~~~~~~
       > src/media.m:53:44: warning: instance method '-UTF8String' not found (return type defaults to 'id') [-Wobjc-method-access]
       >       const char* title_cstr = [self.title UTF8String];
       >                                            ^~~~~~~~~~
       > /nix/store/km68nqhsk0h20ajnlqys3cnlqshs7cgv-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:238:8: note: receiver is instance of class declared here
       > @class NSString;
       >        ^
       > src/media.m:53:19: warning: incompatible pointer types initializing 'const char *' with an expression of type 'id' [-Wincompatible-pointer-types]
       >       const char* title_cstr = [self.title UTF8String];
       >                   ^            ~~~~~~~~~~~~~~~~~~~~~~~
       > src/media.m:54:44: warning: instance method '-UTF8String' not found (return type defaults to 'id') [-Wobjc-method-access]
       >       const char* album_cstr = [self.album UTF8String];
       >                                            ^~~~~~~~~~
       > /nix/store/km68nqhsk0h20ajnlqys3cnlqshs7cgv-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:238:8: note: receiver is instance of class declared here
       > @class NSString;
       >        ^
       > src/media.m:54:19: warning: incompatible pointer types initializing 'const char *' with an expression of type 'id' [-Wincompatible-pointer-types]
       >       const char* album_cstr = [self.album UTF8String];
       >                   ^            ~~~~~~~~~~~~~~~~~~~~~~~
       > src/media.m:99:32: error: property 'userInfo' not found on object of type 'const id'
       >       self.app = [notification.userInfo valueForKey:kMRMediaRemoteNowPlayingApplicationDisplayNameUserInfoKey];
       >                                ^
       > src/media.m:100:27: warning: instance method '-valueForKey:' not found (return type defaults to 'id') [-Wobjc-method-access]
       >       self.artist = [dict valueForKey:kMRMediaRemoteNowPlayingInfoArtist];
       >                           ^~~~~~~~~~~
       > /nix/store/km68nqhsk0h20ajnlqys3cnlqshs7cgv-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:244:8: note: receiver is instance of class declared here
       > @class NSDictionary;
       >        ^
       > src/media.m:101:26: warning: instance method '-valueForKey:' not found (return type defaults to 'id') [-Wobjc-method-access]
       >       self.title = [dict valueForKey:kMRMediaRemoteNowPlayingInfoTitle];
       >                          ^~~~~~~~~~~
       > /nix/store/km68nqhsk0h20ajnlqys3cnlqshs7cgv-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:244:8: note: receiver is instance of class declared here
       > @class NSDictionary;
       >        ^
       > src/media.m:102:26: warning: instance method '-valueForKey:' not found (return type defaults to 'id') [-Wobjc-method-access]
       >       self.album = [dict valueForKey:kMRMediaRemoteNowPlayingInfoAlbum];
       >                          ^~~~~~~~~~~
       > /nix/store/km68nqhsk0h20ajnlqys3cnlqshs7cgv-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:244:8: note: receiver is instance of class declared here
       > @class NSDictionary;
       >        ^
       > 11 warnings and 6 errors generated.
       > make: *** [makefile:61: bin/media.om] Error 1
       For full logs, run 'nix log /nix/store/4pas9210ydg0nw2mij5mclx90p73x412-sketchybar-2.16.0.drv'.

```

**Comment by khaneliman** [comment]
Never mind, looks like an upstream issue.. he released a 2.16.1 that fixes compile.

**Comment by khaneliman** [comment]
Result of `nixpkgs-review pr 251366` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>sketchybar</li>
  </ul>
</details>

**Review by AndersonTorres — COMMENTED** [review]
I can't possibly test Darwin things.

**Comment by khaneliman** [comment]
> I can't possibly test Darwin things.

Just trying to get a version bumped. It's built and runs fine

**Comment by AndersonTorres** [comment]
I will believe in you, then.

**Comment by khaneliman** [comment]
> I will believe in you, then.

Appreciate it, thanks.

**Pull request merged**
