### PR TITLE
riak-cs: delete

### PR DESCRIPTION
**Pull request by DianaOlympos**
###### Motivation for this change
Now that Riak can run on modern version of OTP, it is time to drop what stopped being supported when Basho died. Riak-CS has had no new commit in 5 years. Time to drop it.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by DianaOlympos** [comment]
Moved the throw to `pkgs/top-level/aliases.nix`

**Comment by DianaOlympos** [comment]
@berbiche I rebased on master, could you re-review now with the changes so we can get that to master, so i can move to getting rid of riak and otp r16 ?

**Review by berbiche — APPROVED** [review]
Removing the module options would need an entry in `nixos/doc/manual/release-notes/rl-2103.xml` under "Backward incompatibilities" in the form of 
``` xml
<listitem>
    <para>
    <package>riak-cs</package> package removed along with <varname>services.riak-cs</varname> module.
    </para>
</listitem>
<listitem>
    <para>
    <package>stanchion</package> package removed along with <varname>services.stanchion</varname> module.
    </para>
</listitem>
```

**Comment by DianaOlympos** [comment]
Well i did add it and deleted it today welp :D ok done

**Comment by berbiche** [comment]
I am not part of the org, so someone else will have to merge this.

/marvin opt-in
/status needs_merger

**Pull request merged**
