### PR TITLE
rustup: 1.18.1 -> 1.18.2

### PR DESCRIPTION
**Pull request by xrelkd**
###### Motivation for this change

Update `rustup` to the latest release.
https://github.com/rust-lang/rustup.rs/releases/tag/1.18.2
Changes: https://github.com/rust-lang/rustup.rs/blob/1.18.2/CHANGELOG.md

cc maintainer @Mic92 
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by marsam** [comment]
@GrahamcOfBorg build rustup

**Comment by marsam** [comment]
@GrahamcOfBorg build rustup

**Comment by marsam** [comment]
I've added a fix for the darwin build, I hope you don't mind. 
Built and tested locally on NixOS and darwin.
@xrelkd thanks!

**Comment by xrelkd** [comment]
@marsam Thanks for adding the fix for darwin build and merging this PR.

**Pull request merged**
