### PR TITLE
sequoia: 0.16.0 -> 0.17.0

### PR DESCRIPTION
**Pull request by puzzlewolf**
###### Motivation for this change
`sequoia` version 0.17.0 has been released

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Ping maintainers: @minijackson, @doronbehar

### CODE REVIEW

**Comment by doronbehar** [comment]
Tests fail in CI.

**Comment by puzzlewolf** [comment]
Hm, builds fine on my machine. I'll take a look at those tests.

**Comment by puzzlewolf** [comment]
It runs out of file handles, so it's #70646 again. What does that mean? I can't find a solution in that issue, but somehow the build succeeded later. In #80209 @bhipple says 
> I'm guessing it'll build eventually?

So, just wait and rebuild?

**Comment by minijackson** [comment]
Yeah, it's unfortunate :-/

One thing we can try though, is to reduce the number of tests run in parallel by overriding the check phase, and setting the `--jobs` option in `cargo test`.

**Comment by puzzlewolf** [comment]
Let's see if deactivating the 'sequoia-store' tests does the trick :D

**Comment by puzzlewolf** [comment]
So, I noticed (in the log posted in #70646 and the failed build here) that the failing tests are all for the `sequoia-store` package. I guess it's better to deactivate those specific tests than to slow them all down by limiting the number of jobs. 
All tests are run by upstream CI anyway, I guess we can live without a couple ones that prove problematic for our environment. What do you think?

**Comment by doronbehar** [comment]
@GrahamcOfBorg's environment is not exactly as hydra, but still, the idea sounds good to me.

**Comment by puzzlewolf** [comment]
We won't know if it works on Hydra until it has been built there :laughing:. I'm not too familiar with how Hydra works, but I guess we'll have to merge this, right?

**Comment by erictapen** [comment]
I agree, let's merge this.

**Pull request merged**
