### PR TITLE
Systemd v243.4

### PR DESCRIPTION
**Pull request by lheckemann**
closes #74207 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- [x] Built on NixOS
- [x] Tested via `nixos/tests/timezone.nix`

cc @flokli

### CODE REVIEW

**Comment by lheckemann** [comment]
Accompanying systemd PR: https://github.com/NixOS/systemd/pull/34

**Comment by nh2** [comment]
You want `master` or should it be `staging`?

**Comment by lheckemann** [comment]
Good catch, thanks.

**Comment by doronbehar** [comment]
What was wrong with https://github.com/NixOS/nixpkgs/pull/74207 in the first place?

**Comment by flokli** [comment]
#74207 broke the timezones-imperative test.

**Review by flokli — APPROVED** [review]
Ran the timezone tests, switched my system to this systemd flavour, and toyed around with setting timezone via NixOS config and imperatively.

**Pull request merged**
