### PR TITLE
pump.io 2.1.1

### PR DESCRIPTION
**Pull request by rvl**
###### Motivation for this change

Package was broken and new stable releases have been made.

Could this also be cherry-picked onto `release-17.03` please?

Relevant to #23253.

###### Things done

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [X] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
Yes can be cherry-picked to 17.03. There is also 3.0 already released: https://github.com/pump-io/pump.io/releases

How do I use pumpio? If I start it from commandline:

```
$ pump
{"name":"pump.io","hostname":"eve","pid":18432,"level":30,"msg":"Listening on 31337 for host 127.0.0.1","time":"2017-03-06T22:06:37.455Z","v":0}
```

However it does not open a socket on localhost:31337.

**Comment by rvl** [comment]
Thanks @Mic92 I will add the 3.0 release to this PR. There are some config file changes for this version which I will need to test. To use pump.io, you need to run a database and configure `services.pumpio` in NixOS.

**Comment by Mic92** [comment]
I applied your fixes with some minor style changes and made "localhost" the default value of `address` again.

**Comment by rvl** [comment]
Most excellent, thanks @Mic92

**Pull request closed without merging**
