### PR TITLE
scryer-prolog: 0.9.2 -> 0.9.3

### PR DESCRIPTION
**Pull request by wkral**
## Description of changes
Bump to release 0.9.3 of scryer-prolog.

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>scryer-prolog</li>
  </ul>
</details>

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wkral** [comment]
Also adding myself as a maintainer if that's alright, I've been following and minorly participating in the development of scryer for a while now.

**Review by malbarbo — APPROVED** [review]
LGTM, thanks @wkral.

**Comment by onemoresuza** [comment]
There's a merge conflict on `maintainers/maintainer-list.nix`:

```patch
diff --cc maintainers/maintainer-list.nix
index da13f66838ce,266eea1b7429..000000000000
--- a/maintainers/maintainer-list.nix
+++ b/maintainers/maintainer-list.nix
@@@ -19307,6 -19179,18 +19307,21 @@@
      githubId = 168610;
      name = "Ricardo M. Correia";
    };
++<<<<<<< HEAD
++=======
+   wjlroe = {
+     email = "willroe@gmail.com";
+     github = "wjlroe";
+     githubId = 43315;
+     name = "William Roe";
+   };
+   wkral = {
+     email = "william.kral@gmail.com";
+     github = "wkral";
+     githubId = 105114;
+     name = "William Kral";
+   };
++>>>>>>> ff26471679a0 (scryer-prolog: add wkral as a maintainer)
    wladmis = {
      email = "dev@wladmis.org";
      github = "wladmis";

```

Could you rebase `master` against your branch, solve the conflict, then force-push the changes, @wkral?

**Comment by wkral** [comment]
Thanks @onemoresuza, didn't notice that had arrisen while I was waiting on this PR.
I've addressed the conflict and force pushed the change.

**Review by malbarbo — APPROVED** [review]

**Pull request merged**
