### PR TITLE
pr-template: Clarify `sandbox` checkbox

### PR DESCRIPTION
**Pull request by l0b0**
###### Description of changes

This setting can be enabled or disabled on all platforms, so asking
specifically for "non-Linux" is not sufficient.

Also links directly to the setting in the manual, for faster lookup.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by l0b0** [comment]
> `zsh: command not found: nix-info` on Arch Linux with single-user Nix install

Fixed, thanks!

**Comment by piegamesde** [comment]
Nope ^^
`/tmp/nix-shell-47282-0/rc: line 3: nix-info: command not found`

But honestly, before wasting your time some more, I'm not sure about how much benefit this checkbox brings in the first place. I mean we can all agree that it is currently completely dysfunctional and I see how your change attempts to improve it. But I think we've done pretty much fine without so far, so maybe simply remove that line in order to keep the list smaller?

**Comment by l0b0** [comment]
> Nope ^^ `/tmp/nix-shell-47282-0/rc: line 3: nix-info: command not found`
> 
> But honestly, before wasting your time some more, I'm not sure about how much benefit this checkbox brings in the first place. I mean we can all agree that it is currently completely dysfunctional and I see how your change attempts to improve it. But I think we've done pretty much fine without so far, so maybe simply remove that line in order to keep the list smaller?

Sorry, for some reason I thought `nix-info` was part of the `nix` package. People have so far complained that the current template has too many checkboxes, too few checkboxes, and the wrong checkboxes, so I'm just trying to make as neutral changes as possible.

**Comment by piegamesde** [comment]
I'd like to hear from @NixOS/darwin-maintainers on this. I've heard rumors that Darwin nowadays has a sandbox and enabled by default, making this checkbox obsolete?

**Comment by emilazy** [comment]
I don't think it's enabled by default, sadly. Though it's been a while since I did a fresh install.

**Comment by mikroskeem** [comment]
Sandbox is not enabled by default on Darwin currently

**Comment by toonn** [comment]
If the checkbox remains, I'm in favor of it at least being clear and correct. I opened #238575 about a similar issue with it.

**Comment by Artturin** [comment]
toonn's pr merged

**Pull request closed without merging**
