### PR TITLE
nixos/xl2tpd: add the xl2tpOptions

### PR DESCRIPTION
**Pull request by jpotier**
This option allows the user to give a full configuration file, and
bypass the — sometimes problematic — default configuration.

###### Motivation for this change
The module is not usable as-is with my company's setup. I suspect this will be the case for other people, so the simplest option is to give users the choice to provide a full config file.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jpotier** [comment]
@obadz you are the original writter of the module, any thoughts?

**Comment by jpotier** [comment]
@abbradar you are the maintainer of the underlying `xl2tpd` package, I wish to bring this to your attention, if you are interested.

**Comment by obadz** [comment]
@jpotier, is there really no way for you to add the options you care about to the module rather than provide a string-based fallback?

**Comment by jpotier** [comment]
Hmm, sure, there should be a way. This will require much more work though. I'll try and come up with something more detailed, and keeping your options.

I proposed this, because I've seen it implemented in other modules this way.

In any case, I'll have to eliminate some of the defaults.

**Comment by obadz** [comment]
Is this related to your E-mail where you try to set this up as a client rather than server?

**Comment by jpotier** [comment]
yep, it is.

**Comment by obadz** [comment]
Do you want to try the networkmanager module for client side instead?

**Comment by jpotier** [comment]
Well, I don't use networkmanager and installing it will just change too
much of my usual settings (I mean, how much of networkmanager's config
can be declared in a .nix file?)

Le 23/10/17 à 11:43, obadz a écrit:

**Comment by obadz** [comment]
Yes networkmanager lives outside of nix. If you want to avoid that you'll need to do this from a module indeed.

This module was meant to configure the server side. Not sure whether client version should be another module or same module with different options. My first guess would be separate module but feel free to propose what you feel is best.

**Comment by jpotier** [comment]
So either it's a client module that lives in
  services.xl2tpd-client

Or the current module is split (like openvpn) between
  services.xl2tpd.client and
  services.xl2tpd.server

I think there are reusable config options between the server and the client,
so it may seem to be a better idea to have that under a single module.

Le 23/10/17 à 12:06, obadz a écrit:

**Comment by jpotier** [comment]
Well, now that I thought about it a little bit more, I don't get why we should separate client and server. I'll just enable more options, but people can choose by setting the options.

A good next point on the roadmap would be to start several instances of the service.

**Comment by matthewbauer** [comment]
Status of this?

**Comment by jpotier** [comment]
Let's close this one. I'll PR something else when I get the time.

**Pull request closed without merging**
