### PR TITLE
memos: 0.13.2 -> 0.21.0

### LINKED ISSUE #257131: Update request: memos 0.13.2 → 0.22.5
- Package name: memos
- Latest released version: [0.22.5](https://github.com/usememos/memos/releases/tag/v0.22.5)

- Current version on the unstable channel: 0.13.2
- Current version on the stable/release channel: 0.13.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@indexyz

-----

Note for maintainers: Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by JohnRTitor**
## Description of changes
Update memos: 0.13.2 -> 0.21.0
Changelog: https://github.com/usememos/memos/compare/v0.13.2...v0.21.0
Still WIP

Closes https://github.com/NixOS/nixpkgs/issues/257131

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by JohnRTitor** [comment]
Pinging maintainers: @5aaee9 who added the package. Whenever I try to build the package it seems to fail with dependency error.

**Comment by JohnRTitor** [comment]
Fixed the issue, but now buf is not working
```
       > npm ERR! command sh -c cd ../proto && buf generate
       > npm ERR! Failure: the server hosted at that remote is unavailable.
```
could it be because buf can't access network in the environment?

**Comment by 5aaee9** [comment]
> Fixed the issue, but now buf is not working
> 
> ```
>        > npm ERR! command sh -c cd ../proto && buf generate
>        > npm ERR! Failure: the server hosted at that remote is unavailable.
> ```
> 
> could it be because buf can't access network in the environment?

buf generate cant access the net in sandbox, you can try to use FOD to get the output

Ref: https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/zi/zitadel/package.nix#L53-L82

**Comment by JohnRTitor** [comment]
Closing because I don't have the time and skills to put into this. If anyone wanna reuse this PR as a reference, they are welcome.

**Pull request closed without merging**
