### PR TITLE
igraph: 0.9.4 -> 0.9.5 

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dotlambda** [comment]
This breaks `python3Packages.cozy` (which I'm not fixing cause it's not https://pypi.org/project/Cozy/ and shouldn't be in `pythonPackages` anyway).
cc @MostAwesomeDude

**Comment by MostAwesomeDude** [comment]
How is Cozy broken by this change? This should be fine, although I haven't tested it. As a practical matter, I don't have dependencies on Cozy, so don't let me block this upgrade; you can mark Cozy as broken if necessary.

**Comment by dotlambda** [comment]
> How is Cozy broken by this change?

It's broken by the renaming from python-igraph to igraph.

**Review by sugar700 — COMMENTED** [review]
SkyTemple works fine after this change (tested script debugger which I know uses igraph).

Packages other than Cozy build. For Cozy I have the following issue.

    ERROR: Could not find a version that satisfies the requirement python-igraph<1.0,>=0.7.1 (from cozy) (from versions: none)
    ERROR: No matching distribution found for python-igraph<1.0,>=0.7.1

**Comment by dotlambda** [comment]
@MostAwesomeDude Please make a PR moving Cozy into `all-packages.nix`. In that PR, you can also fix the failure created by renaming `python-igraph`.

**Comment by MostAwesomeDude** [comment]
Hi, I don't understand what you've attempted to obligate me to do. If you broke Cozy, please mark it broken. If you want it removed from the tree, please remove it. Thanks!

**Pull request merged**
