### PR TITLE
vimPlugins.gina-vim: rename plugin to fix alias

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

The `gina-vim` plugin was marked as deprecated (rightfully so) but was not removed from `vim-plugin-names`.
This lead to an eval failure reported in #337444.

This PR properly ~~removes~~ renames the plugin.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 341309` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Review by PerchunPak — APPROVED** [review]
Will take into consideration in #336137. Could you check also other deprecated plugins?

**Comment by teto** [comment]
gina recommends https://github.com/lambdalisue/vim-gin as an alternative. I dont think we package it and it is using deno, I am not sure how easy it's to add. Till then maybe we can keep gina. It might be deprecated but doesn't mean it's broken yet.

**Comment by GaetanLepage** [comment]
I think that the update script automatically added it to `deprecated.json` as the GH repo is marked as active.
It will behave the same the next times we will run it.

As the package has already been unavailable in nixpkgs for the past few months, I would argue that we properly deprecate it and eventually add `gin`.

**Comment by PerchunPak** [comment]
Oh, update script doesn't remove packages. It also doesn't check if repository archived. All it does is resolves redirects, and adds a notice about rename to `deprecated.json`

The reported error must come from another source (e.g. there is also an alias in `aliases.nix`

**Comment by PerchunPak** [comment]
Also, there are already multiple plugins that use denops.vim packaged (`vim-pluto` & `ddc-vim`). Packaging gin.nvim won't be any problem

**Comment by GaetanLepage** [comment]
> Oh, update script doesn't remove packages. It also doesn't check if repository archived. All it does is resolves redirects, and adds a notice about rename to `deprecated.json`
> 
> The reported error must come from another source (e.g. there is also an alias in `aliases.nix`

The plugin that was in the package set was `gina-vim`, but the alias was saying that this was the old name was `vim-gina` (which didn't exist).

I have simply ran the update script and propose that we merge this.

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 341309` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>lua52Packages.neotest</li>
    <li>lua53Packages.neotest</li>
    <li>lua54Packages.neotest</li>
    <li>lua54Packages.sqlite</li>
    <li>luajitPackages.neotest</li>
    <li>vimPlugins.sg-nvim</li>
  </ul>
</details>
<details>
  <summary>120 packages built:</summary>
  <ul>
    <li>lua51Packages.neotest</li>
    <li>lua51Packages.sqlite</li>
    <li>lua52Packages.sqlite</li>
    <li>lua53Packages.sqlite</li>
    <li>luajitPackages.sqlite</li>
    <li>vimPlugins.ChatGPT-nvim</li>
    <li>vimPlugins.CopilotChat-nvim</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vimPlugins.advanced-git-search-nvim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.auto-session</li>
    <li>vimPlugins.autosave-nvim</li>
    <li>vimPlugins.barbecue-nvim</li>
    <li>vimPlugins.cmake-tools-nvim</li>
    <li>vimPlugins.cmp-ai</li>
    <li>vimPlugins.cmp-clippy</li>
    <li>vimPlugins.cmp-fuzzy-buffer</li>
    <li>vimPlugins.cmp-fuzzy-path</li>
    <li>vimPlugins.cmp-git</li>
    <li>vimPlugins.cmp-npm</li>
    <li>vimPlugins.cmp-pandoc-nvim</li>
    <li>vimPlugins.cmp-tabnine</li>
    <li>vimPlugins.codeium-nvim</li>
    <li>vimPlugins.compiler-explorer-nvim</li>
    <li>vimPlugins.compiler-nvim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.conform-nvim</li>
    <li>vimPlugins.copilot-lua</li>
    <li>vimPlugins.crates-nvim</li>
    <li>vimPlugins.csharpls-extended-lsp-nvim</li>
    <li>vimPlugins.cyberdream-nvim</li>
    <li>vimPlugins.ddc-source-lsp</li>
    <li>vimPlugins.diagram-nvim</li>
    <li>vimPlugins.diffview-nvim</li>
    <li>vimPlugins.fuzzy-nvim</li>
    <li>vimPlugins.gitlinker-nvim</li>
    <li>vimPlugins.gitsigns-nvim</li>
    <li>vimPlugins.go-nvim</li>
    <li>vimPlugins.hardhat-nvim</li>
    <li>vimPlugins.harpoon</li>
    <li>vimPlugins.harpoon2</li>
    <li>vimPlugins.haskell-scope-highlighting-nvim</li>
    <li>vimPlugins.himalaya-vim</li>
    <li>vimPlugins.idris2-nvim</li>
    <li>vimPlugins.image-nvim</li>
    <li>vimPlugins.lazy-lsp-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.leap-ast-nvim</li>
    <li>vimPlugins.limelight-vim</li>
    <li>vimPlugins.lir-nvim</li>
    <li>vimPlugins.lspkind-nvim</li>
    <li>vimPlugins.mason-lspconfig-nvim</li>
    <li>vimPlugins.multicursors-nvim</li>
    <li>vimPlugins.neo-tree-nvim</li>
    <li>vimPlugins.neoconf-nvim</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neorg</li>
    <li>vimPlugins.neotest</li>
    <li>vimPlugins.neotest-gradle</li>
    <li>vimPlugins.neotest-gtest</li>
    <li>vimPlugins.neotest-playwright</li>
    <li>vimPlugins.night-owl-nvim</li>
    <li>vimPlugins.nlsp-settings-nvim</li>
    <li>vimPlugins.none-ls-nvim</li>
    <li>vimPlugins.null-ls-nvim</li>
    <li>vimPlugins.nvim-coverage</li>
    <li>vimPlugins.nvim-lint</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-navbuddy</li>
    <li>vimPlugins.nvim-navic</li>
    <li>vimPlugins.nvim-spectre</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-parsers.gomod</li>
    <li>vimPlugins.nvim-treesitter-parsers.latex</li>
    <li>vimPlugins.nvim-treesitter-parsers.markdown</li>
    <li>vimPlugins.nvim-treesitter-parsers.markdown_inline</li>
    <li>vimPlugins.nvim-treesitter-parsers.perl</li>
    <li>vimPlugins.nvim-treesitter-parsers.scala</li>
    <li>vimPlugins.nvim-treesitter-parsers.sql</li>
    <li>vimPlugins.obsidian-nvim</li>
    <li>vimPlugins.octo-nvim</li>
    <li>vimPlugins.oil-nvim</li>
    <li>vimPlugins.ollama-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.otter-nvim</li>
    <li>vimPlugins.overseer-nvim</li>
    <li>vimPlugins.persisted-nvim</li>
    <li>vimPlugins.playground</li>
    <li>vimPlugins.plenary-nvim</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.render-markdown</li>
    <li>vimPlugins.rest-nvim</li>
    <li>vimPlugins.roslyn-nvim</li>
    <li>vimPlugins.smart-open-nvim</li>
    <li>vimPlugins.smart-splits-nvim</li>
    <li>vimPlugins.ssr</li>
    <li>vimPlugins.startup-nvim</li>
    <li>vimPlugins.supermaven-nvim</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-media-files-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-undo-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.telescope-zoxide</li>
    <li>vimPlugins.todo-comments-nvim</li>
    <li>vimPlugins.typescript-tools-nvim</li>
    <li>vimPlugins.unison</li>
    <li>vimPlugins.vifm-vim</li>
    <li>vimPlugins.vim-gina</li>
    <li>vimPlugins.vim-tpipeline</li>
    <li>vimPlugins.vimtex</li>
    <li>vimPlugins.yazi-nvim</li>
    <li>vimPlugins.zarchive-vim-fsharp</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Comment by PerchunPak** [comment]
> I have simply ran the update script and propose that we merge this.

Current update script is broken and doesn't do what I described, it is fixed in https://github.com/NixOS/nixpkgs/pull/336137. Though, for some reason, it correctly renamed the plugin

Also, let's not pollute commit history and change only parts that are related to this PR. And return deprecation please, it should work now

**Comment by GaetanLepage** [comment]
> Current update script is broken and doesn't do what I described, it is fixed in #336137. Though, for some reason, it correctly renamed the plugin
> 
> Also, let's not pollute commit history and change only parts that are related to this PR. And return deprecation please, it should work now

You are right, let's do things properly.

Is there any remaining blocker on your PR ?

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 341309` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>vimPlugins.vim-gina</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Review by PerchunPak — APPROVED** [review]

**Comment by PerchunPak** [comment]
> Is there any remaining blocker on your PR ?

No, only review. I will also fix merge conflicts in a moment

**Pull request merged**
