### PR TITLE
cargo-mommy: 0.2.0 -> 0.3.1

### PR DESCRIPTION
**Pull request by 999eagle**
## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by GoldsteinE** [comment]
Yeah, can we wait a bit with this? I think 0.3 is coming, and I’d like to merge these updates to reduce amount of PRs needed.

**Comment by 999eagle** [comment]
Well, this PR is already open now but sure :)

**Comment by GoldsteinE** [comment]
Also 0.2.1 is not in the repo for some reason?

**Comment by 999eagle** [comment]
The [upstream repo](https://github.com/Gankra/cargo-mommy) has no version tags or branches at all, but according to [crates.io](https://crates.io/crates/cargo-mommy/versions) 0.2.1 is the current version.

**Comment by GoldsteinE** [comment]
Yeah, but the upstream repo has [Cargo.toml](https://github.com/Gankra/cargo-mommy/blob/6feb98f10ede68c82d99f70aa79cb3a53530dc88/Cargo.toml#L6) which declares version as 0.2.0 in the main branch.

**Comment by 999eagle** [comment]
Here is the upstream commit for 0.2.1, it's on the `modular-mommy` branch: https://github.com/Gankra/cargo-mommy/commit/ee444e290bbf856d9a0155837e4ef394a1097dd4

**Comment by GoldsteinE** [comment]
@999eagle Hi! 0.3 is out now (and also in the main branch). Do you want to update the PR?

**Comment by 999eagle** [comment]
Updated to 0.3.0 now, thanks for the ping!

**Review by GoldsteinE — APPROVED** [review]
Checked with nixpkgs-review.

**Review by GoldsteinE — APPROVED** [review]

**Comment by GoldsteinE** [comment]
And now it's 0.3.1

**Comment by 999eagle** [comment]
Updated to 0.3.1.

**Review by GoldsteinE — APPROVED** [review]
Still works, still approved.

**Pull request merged**
