### PR TITLE
nixos/xserver: fix a display-manager race condition

### LINKED ISSUE #97795: SDDM Crashes when displayManager.autoLogin is set
**Describe the bug**
On a cold boot, `sddm-helper` exits uncleanly, leaving a black screen.

This issue seems to have appeared on 20.03 (stable) up to the (at the time of this report) latest `nixos-unstable-small` channel. 

Running `sudo systemctl restart display-manager.service` from a different TTY will immediately load Plasma with the expected automatic login.

**To Reproduce**
1. Include `nixpkgs/nixos/modules/profiles/graphical.nix` as an import at the top of the system configuration
2. Enable `services.xserver.displayManager.autoLogin` and set `services.xserver.displayManager.autoLogin.user`

**Expected behavior**
Automatic login to Plasma after the Plymouth screen.

**Screenshots**
No screenshots, but here's an excerpt of the output of `systemctl -b -u display-manager.service`:

```
...
Sep 11 19:08:24 nixos sddm-helper[842]: [PAM] Starting...
Sep 11 19:08:24 nixos sddm-helper[842]: [PAM] Authenticating...
Sep 11 19:08:24 nixos sddm-helper[842]: [PAM] Preparing to converse...
Sep 11 19:08:24 nixos sddm-helper[842]: [PAM] Conversation with 1 messages
Sep 11 19:08:24 nixos sddm[812]: Authentication error: "\"System is booting up. Unprivileged users are not permitted to log in yet. Please come back later. For technical details, see pam_nologin(8).\""
Sep 11 19:08:24 nixos sddm-helper[842]: [PAM] authenticate: Authentication failure
Sep 11 19:08:24 nixos sddm-helper[842]: [PAM] returning.
Sep 11 19:08:24 nixos sddm[812]: Authentication error: "Authentication failure"
Sep 11 19:08:24 nixos sddm-helper[842]: [PAM] Ended.
Sep 11 19:08:24 nixos sddm[812]: Auth: sddm-helper exited with 1
Sep 11 19:09:24 nixos xserver-wrapper[826]: (EE) event12 - Telink Wireless Receiver: client bug: event processing lagging behind by 17ms, your system is too slow
Sep 11 19:09:24 nixos xserver-wrapper[826]: (II) event2  - Power Button: device removed
Sep 11 19:09:24 nixos xserver-wrapper[826]: (II) event13 - Video Bus: device removed
Sep 11 19:09:24 nixos xserver-wrapper[826]: (II) event0  - Power Button: device removed
Sep 11 19:09:24 nixos xserver-wrapper[826]: (II) event1  - Sleep Button: device removed
Sep 11 19:09:24 nixos xserver-wrapper[826]: (II) event9  - Telink Wireless Receiver Mouse: device removed
Sep 11 19:09:24 nixos xserver-wrapper[826]: (II) event11 - Telink Wireless Receiver System Control: device removed
Sep 11 19:09:24 nixos xserver-wrapper[826]: (II) event12 - Telink Wireless Receiver: device removed
Sep 11 19:09:24 nixos xserver-wrapper[826]: (II) event7  - HP WMI hotkeys: device removed
Sep 11 19:09:24 nixos xserver-wrapper[826]: (II) event10 - Telink Wireless Receiver Consumer Control: device removed
Sep 11 19:09:24 nixos xserver-wrapper[826]: (II) AIGLX: Suspending AIGLX clients for VT switch
Sep 11 19:11:05 nixos sddm[812]: Signal received: SIGTERM
Sep 11 19:11:05 nixos sddm[812]: Display server stopping...
Sep 11 19:11:05 nixos systemd[1]: Stopping X11 Server...
...
```

**Additional context**
Using the same configuration this issue appears on only 2 of my 3 machines. The affected ones are using Intel integrated graphics with SSDs, while the other one has an older AMD GPU and HDD. I'm unsure if this could be an issue relating to drivers (with autologin off, SDDM and X work OOTB) or the significant difference in boot times.

**Notify maintainers**
@abbradar @ttuegel 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.8, NixOS, 21.03pre243391.b38c90caa22 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(johannes): `""`
 - channels(root): `"nixos-21.03pre243391.b38c90caa22"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by j0hax**
###### Motivation for this change
Resolves https://github.com/NixOS/nixpkgs/issues/97795.

Tested with SDDM, GDM, and LightDM (Autologin after boot, along with manual login/logout)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Artturin** [comment]
these should probably be here 
https://github.com/NixOS/nixpkgs/blob/0dde103318090f77ac95ef7fc26fe0cdd00fa0b3/nixos/modules/services/x11/xserver.nix#L684

**Comment by Artturin** [comment]
checked a couple of display manager packages on arch and they have

sddm
```
Conflicts=getty@tty1.service
After=systemd-user-sessions.service getty@tty1.service plymouth-quit.service systemd-logind.service
```

lightdm
```
Conflicts=getty@tty1.service
After=getty@tty1.service systemd-user-sessions.service plymouth-quit.service acpid.service
```

**Comment by j0hax** [comment]
> could you try just adding `systemd-user-sessions.service`?

`systemd-user-sessions.service` definitely seems like a good idea, if I remember correctly `/run/nologin` was also part of the problem in the SDDM logs. Because this issue only popped up sporadically for me, I'll rebuild some of the affected boxes with that suggestion and see what happens over a couple reboots.

**Comment by j0hax** [comment]
SDDM and LightDM work OOTB with these changes, however I have the following issue with GDM:

```console
> systemctl status gdm.service 
● gdm.service - GNOME Display Manager
     Loaded: error (Reason: Unit gdm.service failed to load properly: File exists.)
     Active: inactive (dead)

Aug 09 23:31:08 kirby systemd[1]: gdm.service: Two services allocated for the same bus name org.gnome.DisplayManager, refusing operation.
```

Could be related to https://github.com/NixOS/nixpkgs/issues/108672.

**Comment by Artturin** [comment]
was it happening before this change?

**Comment by Artturin** [comment]
> SDDM and LightDM work OOTB with these changes, however I have the following issue with GDM:
> 
> ```
> > systemctl status gdm.service 
> ● gdm.service - GNOME Display Manager
>      Loaded: error (Reason: Unit gdm.service failed to load properly: File exists.)
>      Active: inactive (dead)
> 
> Aug 09 23:31:08 kirby systemd[1]: gdm.service: Two services allocated for the same bus name org.gnome.DisplayManager, refusing operation.
> ```
> 
> Could be related to #108672.

made a pr which fixes that #133304

**Review by Artturin — APPROVED** [review]
i think this pr is ready to be merged
i tested it in a vm
i'll merge tomorrow if there's no objections

**Pull request merged**
