### PR TITLE
nixos/ntfy.sh: use dynamic user + add defaults

### PR DESCRIPTION
**Pull request by happysalada**
###### Description of changes

Second try at updating this service with additional commands for smooth migration.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
Note that I'm not sure the chown is going to work, the dynamic user might lack permissions.

**Comment by JulienMalka** [comment]
@Tom-Hubrecht could you try this and tell us if the migration went correctly ?

**Review by JulienMalka — COMMENTED** [review]
We lost the test change in the operation

**Comment by Tom-Hubrecht** [comment]
The migration is still unsuccessful:

```
May 29 16:04:24 sd-02 systemd[1]: Starting Push notifications server...
May 29 16:04:24 sd-02 (touch)[164053]: Found pre-existing public StateDirectory= directory /var/lib/ntfy-sh, migrating to /var/lib/private/ntfy-sh.
May 29 16:04:24 sd-02 (touch)[164053]: Apparently, service previously had DynamicUser= turned off, and has now turned it on.
May 29 16:04:24 sd-02 touch[164053]: /nix/store/l6jgwxkc3jhr029vfzfwzcy28iyckwsj-coreutils-9.1/bin/touch: cannot touch '/var/lib/ntfy/user.db': Permission denied
May 29 16:04:24 sd-02 systemd[1]: ntfy-sh.service: Control process exited, code=exited, status=1/FAILURE
May 29 16:04:24 sd-02 systemd[1]: ntfy-sh.service: Failed with result 'exit-code'.
May 29 16:04:24 sd-02 systemd[1]: Failed to start Push notifications server.
```

It is possible to use `DynamicUser` while providing a specific user to sytemd's service. Thus, the creation of the required files can be done with `systemd.tmpfiles.rules` instead of `touch` and `mkdir` while setting the correct permissions

**Comment by Tom-Hubrecht** [comment]
The module file at https://git.hubrecht.ovh/hubrecht/nixos/src/branch/master/modules/_ntfy-sh.nix does this

**Comment by happysalada** [comment]
What do you need to pass to the tmp file rules for it to be the dynamic user ?
I tried with just a - in place of the user and the files where owned by root which made the deployment fail.
I couldnt find any docs on using tmp file rules and dynamic user . (thats why in the end i leaned on an execprestart hook since my attempt at tmpfile rules failed )
Happy to change if you know what should be out in place of the user and group of the rule.

**Comment by happysalada** [comment]
I see , thanks for providing an example, ill have a look at changing and testing this on my machine.

**Comment by JulienMalka** [comment]
@ofborg test ntfy-sh

**Comment by happysalada** [comment]
Alright, I would have liked to not have to define the user at all, but I don't think there is a way to not define the user and provide a smooth migration process.

I've hardcoded the user and group since I can't think of a use case for running this service as another user. What do you both think ? 
It's less flexible, but it reduces cognitive load since you have less options to choose from. I'm not married to this decision, but I thought I would propose it.

**Comment by Tom-Hubrecht** [comment]
> Alright, I would have liked to not have to define the user at all, but I don't think there is a way to not define the user and provide a smooth migration process.
> 
> I've hardcoded the user and group since I can't think of a use case for running this service as another user. What do you both think ? It's less flexible, but it reduces cognitive load since you have less options to choose from. I'm not married to this decision, but I thought I would propose it.

As specifying a user is necessary, I don't really see a point in hardcoding it now when it was configurable before, I don't think that it increases that much the cognitive load for users of this module, the options are few and a default is provided.

**Comment by happysalada** [comment]
@Tom-Hubrecht fair enough.
I've left it configurable. When you have a moment if you can have another look, I think this is ready to merge now.

**Review by Tom-Hubrecht — APPROVED** [review]

**Comment by happysalada** [comment]
@Tom-Hubrecht @JulienMalka thanks to both of you for taking the time to review and test this!
Im going to wait 24h more (just in case ) before i merge

**Review by JulienMalka — APPROVED** [review]
LGTM :)

**Comment by JulienMalka** [comment]
@ofborg test ntfy-sh

**Review by JulienMalka — CHANGES_REQUESTED** [review]
Ah actually no, doesn't evaluate

**Review by JulienMalka — CHANGES_REQUESTED** [review]

**Comment by JulienMalka** [comment]
@ofborg test ntfy-sh

**Comment by happysalada** [comment]
@JulienMalka the test is failing on
```
ile "/nix/store/pvlfvg0zm1v19qgjvadvzm7h9hm3jzs5-nixos-test-driver-1.1/lib/python3.10/site-packages/test_driver/machine.py", line 706, in wait_for_open_port
```
I don't think there is anything wrong with this PR though. I've just deployed it to make sure it worked well.
Are you comfortable if we merge or do you want to try something ?

**Comment by happysalada** [comment]
trying a rebase on master just to see if it changes anything.

**Comment by JulienMalka** [comment]
> I don't think there is anything wrong with this PR though. I've just deployed it to make sure it worked well.
> Are you comfortable if we merge or do you want to try something ?

Might actually be broken, test output is:
`ntfy: if attachment-cache-dir is set, base-url must also be set`

**Comment by JulienMalka** [comment]
Also:
```
(ntfy) Found pre-existing public StateDirectory= directory /var/lib/ntfy-sh, migrating to /var/lib/private/ntfy-sh.
(ntfy)[916]: Apparently, service previously had DynamicUser= turned off, and has now turned it on.
```

**Comment by happysalada** [comment]
The warning about DynamicUser being off is fine to ignore IMO, as it's just a warning.

The base-url thing is real. You do have to set it when starting an instance, but I don't think having a default there makes any sense. I'm going to remove the default for attachment cache dir then.

**Comment by happysalada** [comment]
> > Im going to wait 24h more (just in case ) before i merge
> 
> Please do not do this in nixpkgs, wait for someone else to merge it ideally, the previous attempts already broke something, please be mindful of the maintainers of this package and give them enough time to test things if possible.

Hey thanks for chiming in !
I understand that there was breakage on the previous PR, it was fixed in a timely manner though. 
This PR wont get merged before everyone has approved it.

**Comment by happysalada** [comment]
@JulienMalka I've changed the test and added back the attachment default (I actually think it's a great feature to have out of the box).
Let me know what you think when you have a moment.

**Comment by JulienMalka** [comment]
Here we go again

**Comment by JulienMalka** [comment]
@ofborg test ntfy-sh

**Review by JulienMalka — APPROVED** [review]
Ok lgtm, let's see what @Tom-Hubrecht says :)

**Comment by Tom-Hubrecht** [comment]
> Ok lgtm, let's see what @Tom-Hubrecht says :)

LGTM !

**Comment by happysalada** [comment]
@RaitoBezarius @mweinelt the tests, are passing and both of the maintainers have approved, would you be okay to merge ?

**Comment by happysalada** [comment]
@JulienMalka @Tom-Hubrecht sorry again for the misunderstanding and thanks again for your patience through this!

**Pull request merged**
