### PR TITLE
libbpf: 0.6.1 -> 0.7.0, bcc 0.23.0 -> 0.24.0

### PR DESCRIPTION
**Pull request by martinetd**
###### Motivation for this change

New releases of bcc and libbpf.
This replaces #155080 which was waiting for new libbpf version, as bcc 0.24.0 is not compatible with the previous release. (added @Mic92 as 'co-authored-by' for the bcc commit)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by vcunat — APPROVED** [review]
The `libbpf` update looks good to me.

**Comment by vcunat** [comment]
But OfBorg says that the test is syntactically broken:
```
/nix/store/q2qfw74idwq6vv1qnsfnwksm2bp7f13v-nixos-test-driver-bpf/test-script:15:54: EOL while scanning string literal
print(machine.succeed("bpftrace -e 'kprobe:schedule {
                                                     ^
builder for '/nix/store/1sgzb74q90347vgnkb2h8bg68iymlgfj-nixos-test-driver-bpf.drv' failed with exit code 1
```

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by B4dM4n** [comment]
It looks like the libbpf 0.7.0 release tag has been changed on `11. Feb. 2022, 22:01 MEZ` (libbpf/libbpf@2cd2d03f63242c048a896179398c68d2dbefe3d6), after this PR has been opened/tested :facepalm:

```log
error: hash mismatch in fixed-output derivation '/nix/store/4n582hdmix1rlndn0pxa9ryvd85308zq-source.drv':
         specified: sha256-ieJ19igGCoPKGX6J0mQG+QD7QcXHX2SVzZUjMwxum/M=
            got:    sha256-NFVJ8JquWVzu+QoaaOMzhnu6/IqdP1FPhtJFidXA4L4=
error: 1 dependencies of derivation '/nix/store/iaf2mkwg5qj7qd7saymvndmlhghws9fi-libbpf-0.7.0.drv' failed to build
```

**Pull request merged**
