### PR TITLE
clickhouse: 19.17.9.60 -> 20.5.2.7

### PR DESCRIPTION
**Pull request by RaghavSood**
###### Motivation for this change

Implements #90354

~~I tried the nixpkgs-review command, but I'm not sure if it worked - I got `No diff detected, stopping review...` which seems wrong~~
nixpkgs-review builds only clickhouse and gives it a clean chit

llvm was bumped from 7 to 9 to match what Clickhouse recommends
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
> I tried the nixpkgs-review command, but I'm not sure if it worked - I got No diff detected, stopping review... which seems wrong

Which command did you run?

**Comment by RaghavSood** [comment]
@Ma27 It's the command given in the PR template

```
[raghav@ch-misc:~/nixpkgs/nixpkgs]$ git status
On branch clickhouse/20.5.2.7
Your branch is up to date with 'origin/clickhouse/20.5.2.7'.

nothing to commit, working tree clean

[raghav@ch-misc:~/nixpkgs/nixpkgs]$ nix-shell -p nixpkgs-review --run "nixpkgs-review wip"
$ git -c fetch.prune=false fetch --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0
remote: Enumerating objects: 70, done.
remote: Counting objects: 100% (70/70), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 87 (delta 53), reused 59 (delta 49), pack-reused 17
Unpacking objects: 100% (87/87), 331.57 KiB | 1.05 MiB/s, done.
From https://github.com/NixOS/nixpkgs
   cefa2ad525a..143398d7da2  master     -> refs/nixpkgs-review/0
$ git worktree add /home/raghav/.cache/nixpkgs-review/rev-2761377682bdd30de0ceb94407b62e51f1368a4d-dirty-1/nixpkgs 143398d7da2af8c8c1db948e6211e1e1dec3d800
Preparing worktree (detached HEAD 143398d7da2)
Updating files: 100% (22075/22075), done.
HEAD is now at 143398d7da2 Merge pull request #92390 from fionera/add-fuzzel
$ nix-env -f /home/raghav/.cache/nixpkgs-review/rev-2761377682bdd30de0ceb94407b62e51f1368a4d-dirty-1/nixpkgs -qaP --xml --out-path --show-trace
No diff detected, stopping review...
$ git worktree prune
```

**Comment by Ma27** [comment]
Well, the `wip`-command tests your local, uncommitted changes. In your case you probably want to run `nix-review rev <rev of your commit>`.

**Comment by RaghavSood** [comment]
Ah, right, that makes sense - running that now.

Seems a bit odd to have a WIP command in the pull request template, since by the time you're making a pull request you would have committed your changes.

**Comment by RaghavSood** [comment]
`nixpkgs-review` builds only clickhouse, no errors

**Pull request merged**
