### PR TITLE
mesa: 21.2.5 -> 21.2.6

### PR DESCRIPTION
**Pull request by primeos**
###### Motivation for this change

https://docs.mesa3d.org/relnotes/21.2.6.html

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by primeos** [comment]
@ofborg test sway

**Comment by vcunat** [comment]
A few thousand darwin rebuilds?  Maybe `staging` instead this time?  (It's rather overloaded on Hydra this week.)

**Comment by vcunat** [comment]
Oh, scratch that... there's only like 100 builds finished there for now https://hydra.nixos.org/eval/1725525?filter=x86_64-darwin

**Comment by primeos** [comment]
Ok, I hope it's fine for `staging-next` then.

I'm pretty confused why there are more rebuilds on Darwin than on Linux (not sure if we discussed that before but that could be something for @NixOS/darwin-maintainers to investigate). I'm not familiar with Darwin but IIRC/AFAIK the OpenGL libraries from Apple are used there, so I'm not sure why so many Darwin packages even depend on Mesa (since the GL headers should be used from libglvnd now).

Maybe we lack the changes from https://github.com/NixOS/nixpkgs/pull/118479 for Darwin?

**Comment by vcunat** [comment]
IIRC mesa doesn't use glvnd at all on darwin, but overall I'm leaving the platform to others.

**Pull request merged**
