### PR TITLE
go-symbols: init at 2017-02-06

### PR DESCRIPTION
**Pull request by vdemeester**
Signed-off-by: Vincent Demeester <vincent@sbr.pm>

###### Motivation for this change

`go-symbols` is an utility for extracting a JSON representation of the package symbols from a go source tree. It's used in `vscode` and other editors 👼

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by nlewo** [comment]
It seems to me the nixpkgs convention for the name of a package that doesn't have any version is `package-name-YY-MM-DD`. But I cannot find any spec about this convention:/
Some information on this?

**Comment by nlewo** [comment]
In fact, it is mentionnend here: https://nixos.org/nixpkgs/manual/#sec-package-naming

And the format is `YYYY-MM-DD`

**Comment by vdemeester** [comment]
@nlewo hum.. there is a few package that uses `YYYMMDD-{commitid}` though.. Happy to change this new one for sure 👼

**Comment by vdemeester** [comment]
@nlewo updated 👼

**Review by nlewo — APPROVED** [review]

**Comment by nlewo** [comment]
@Mic92 LGTM. Could you have a lool?

**Pull request merged**
