### PR TITLE
Gnome 3.36.1

### PR DESCRIPTION
**Pull request by hedning**
###### Motivation for this change

Things from the 3.36.1 bump that can go straight to master (~250 rebuilds).

This excludes gnome-shell and mutter, as there's some complications with a new internal library with incorrect shared-library path in the typelib, causing the extension app to crash. 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
Apparently g-c-m removed calibration but g-c-c still depends on it https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/951. Perhaps we should ice g-c-m bump for now?

**Comment by hedning** [comment]
> Perhaps we should ice g-c-m bump for now?

Yeah, that works.

**Comment by jtojnar** [comment]
Opened https://github.com/NixOS/nixpkgs/pull/84734

**Comment by jtojnar** [comment]
Rebased dropping the g-c-m update.

**Review by jtojnar — APPROVED** [review]
Have been running this without problems, LGTM.

**Pull request merged**
