### PR TITLE
nixosTests/prosody: fix test

### LINKED ISSUE #202458: Prosody NixOS tests time out
### Describe the bug
The NixOS tests for prosody and prosody-mysql time out on hydra, unnecessarily delaying the channel by about 9 hours.

### Steps To Reproduce
e.g.
https://hydra.nixos.org/build/199758102
https://hydra.nixos.org/build/199758852

### Expected behavior
Tests should finish promptly or fail, not stall the channel.

### Notify maintainers
@Izorkin @NinjaTrappeur 

### Metadata
Happens on both nixos-22.11 and nixos-unstable.

### PR DESCRIPTION
**Pull request by picnoir**
###### Description of changes

```
commit 501d684de8fb70cac2e72eaaff0dcc94aa2af459
Date:   Wed Nov 23 11:01:04 2022 +0100

    nixosTests/prosody: add timeout
    
    The xmpp-sendmessage the slixmpp-powered python script tend to timeout
    and block the nixos channels.
    
    Adding a signal-based timeout making sure that whatever happens, the
    script won't run for more than 2 minutes. That should be pleinty
    enough time to finish regardless of the runner specs. As a data point,
    it runs in about 10 secs on my desktop machine.
```
^ I manually tested this timeout setup before moving on with fixing the test. It does work as expected.

```
commit 8040c468ed9188c33fb851921327d9d9d6850f2c (HEAD -> nin/fix-prosody-test, fork/nin/fix-prosody-test)
Date:   Wed Nov 23 11:05:12 2022 +0100

    nixosTests/prosody[-mysql]: fix tests TLS setup
    
    The tests TLS setup was bogus: the xmpp-send-message script was trying
    to connect to the server through a bogus domain name. Injecting the
    right one.
    
    I'm a bit confused about that one. I know for sure this NixOS test
    succeeded last time I checked it, but the TLS conf is bogus for sure.
    I assume the slixmpp SNI validation was a bit too loose and was
    tightened at some point.
```

Fixes #202458 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

-----------------------------------

@GrahamcOfBorg test prosody prosody-mysql

### CODE REVIEW

**Comment by NinjaTrappeur** [comment]
@GrahamcOfBorg test prosody prosody-mysql

**Comment by NinjaTrappeur** [comment]
I'm sadly the sole maintainer of this package to my knowledge. I'll merge this in 24h if nobody shows up: it's delaying the NixOS channels as it is.

**Review by Izorkin — APPROVED** [review]

**Comment by Izorkin** [comment]
Test working, thanks!

**Comment by NinjaTrappeur** [comment]
> I'm sadly the sole maintainer of this package to my knowledge.

Ah! My bad!

Thanks @Izorkin ! :slightly_smiling_face:

**Comment by mweinelt** [comment]
FYI: slixmpp did not do any certificate validation up until a recent security update that may well have broken the test.

#201252

**Comment by NinjaTrappeur** [comment]
Ah! Thanks for the information.

Make sense. Mystery solved.

**Pull request merged**
