### PR TITLE
mark long-failing packages broken for 18.09

### PR DESCRIPTION
**Pull request by xeji**
###### Motivation for this change

While looking at Hydra failures for ZHF #45960, I found some packages that have been failing for a long time. Great opportunity to start a little clean-up for 18.09.

I propose a simple rule:
A package that has not had a successful Hydra build since 2018-03-01 (before 18.03 was branched off) deserves neither immediate investigation nor more Hydra resources, and will be marked broken right away. It would have been fixed by now if there was demand for it.

Of course, whoever is interested can fix and resurrect them later... If that doesn't happen, these packages should be removed for 19.03.

I'll keep adding more packages to this list as I find them, and merge when the list is long enough :smile:

###### How you can help

- Drop a comment if you find more packages that should be on this list
- Also tell me if I'm wrong and a package should NOT be marked broken
- Committers, feel free to add commits to this PR

---

cc @samueldr @vcunat

### CODE REVIEW

**Comment by xeji** [comment]
`kippo`: cc maintainer @tomberek

**Comment by xeji** [comment]
(`leksah`: no maintainer, actually no `meta` at all)

**Comment by xeji** [comment]
(`btanks`: no maintainer)

**Comment by xeji** [comment]
`qt56.qtwebengine`: not worth fixing as it is not used anywhere in nixpkgs (the last package depending on it was `leo-editor`, updated to qt511 in #46589). cc maintainer @matthewbauer 

btw I think we should get rid of qt56 altogether...

**Comment by ttuegel** [comment]
> I think we should get rid of qt56 altogether...

I agree, now that it is no longer used. We kept it for legacy reasons because it was a long-term support release and some packages could not be upgraded.

**Comment by xeji** [comment]
I'll merge these now so we can get the numbers down :smile:.  Stay tuned for the next round...

**Comment by xeji** [comment]
backported: 0da7a40fcac..47d922fc54b

**Pull request merged**
