### PR TITLE
vimPlugins: revert bad update

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/pull/145640#issuecomment-971126083

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

cc @bandithedoge

### CODE REVIEW

**Comment by lovesegfault** [comment]
Weird, why revert it instead of fixing the hash?

**Comment by dotlambda** [comment]
> Weird, why revert it instead of fixing the hash?

Cause this makes me distrust the auto-generated update commit. Maybe it was altered by hand?

**Comment by chuahou** [comment]
Can confirm that there is a hash mismatch—

```
$ git checkout 1a270c8
$ nix build .\#vimPlugins.vim-colorschemes
error: hash mismatch in fixed-output derivation '/nix/store/59s75xa7338nwfrrn30nz6cp1qwjn995-source.drv':
         specified: sha256-5Y29LUC1cddrX/mwLQoMTWxRcvXHYrgRo+s5IKRx+k4=
            got:    sha256-JhBnyvuKqP0ddKTUi+oVrfBd4Af/pxW4Goe+DfjB6LE=
error: 1 dependencies of derivation '/nix/store/847xbd3pcnch8hnr8rjwnhmlan978k6d-vimplugin-vim-colorschemes-2020-05-15.drv' failed to build
```

(Running `nix-hash to-base32 --type sha256 [hash]` shows these are the same hashes as mentioned in the original linked comment https://github.com/NixOS/nixpkgs/pull/145640#issuecomment-971126083.

---

> > Weird, why revert it instead of fixing the hash?
> 
> Cause this makes me distrust the auto-generated update commit. Maybe it was altered by hand?

Perhaps it'll be better to run `update.py` again?

**Comment by dotlambda** [comment]
> Perhaps it'll be better to run `update.py` again?

Does `update.py` redownload everything to compute the hash or only the plugins that were actually updated?

**Comment by chuahou** [comment]
> Does `update.py` redownload everything to compute the hash or only the plugins that were actually updated?

If I'm not wrong [the script](https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/vim-plugins/update.py) just iterates over [vim-plugin-names](https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/vim-plugins/vim-plugin-names) and generates nix expressions for each, so it likely checks everything in order to know what to update. The details are in [`pluginupdate.py`](https://github.com/NixOS/nixpkgs/blob/master/maintainers/scripts/pluginupdate.py).

**Comment by lovesegfault** [comment]
There could've been a race condition at play here, maybe? Where between fetching the latest rev and computing the sha a new commit was made upstream.

If you change the rev to one before/after the stated one, does the hash match again?

**Comment by chuahou** [comment]
Interestingly, the last commit in [upstream](https://github.com/flazz/vim-colorschemes) was https://github.com/flazz/vim-colorschemes/commit/fd8f122cef604330c96a6a6e434682dbdfb878c9, which is the rev that is left unchanged by the commit, from **15 May 2020**—can't imagine how such a race condition would happen.

**Comment by lovesegfault** [comment]
Ah, indeed. I have no idea what happened then.

**Comment by dotlambda** [comment]
I want to mention that https://github.com/NixOS/nixpkgs/commit/af115051b8cb3fed175bdfefca0e95efe76966d2 was @bandithedoge's first commit in Nixpkgs.

**Comment by lovesegfault** [comment]
I'm merging this, if someone could make a PR re-running the update script and tagging me that'd be swell.

**Comment by chuahou** [comment]
> I'm merging this, if someone could make a PR re-running the update script and tagging me that'd be swell.

I'll do that now and tag you when it's ready.

**Comment by dotlambda** [comment]
I just tried to run the update script but got
```
930 plugins were checked, 3 plugin(s) could not be downloaded:

vim-lsc: The read operation timed out
Traceback (most recent call last):
  File "/home/rschuetz/devel/nixpkgs/maintainers/scripts/pluginupdate.py", line 471, in prefetch
    plugin, redirect = prefetch_plugin(pluginDesc, cache)
  File "/home/rschuetz/devel/nixpkgs/maintainers/scripts/pluginupdate.py", line 326, in prefetch_plugin
    commit, date = repo.latest_commit()
  File "/home/rschuetz/devel/nixpkgs/maintainers/scripts/pluginupdate.py", line 64, in f_retry
    return f(*args, **kwargs)
  File "/home/rschuetz/devel/nixpkgs/maintainers/scripts/pluginupdate.py", line 126, in latest_commit
    xml = req.read()
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/http/client.py", line 466, in read
    return self._readall_chunked()
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/http/client.py", line 576, in _readall_chunked
    value.append(self._safe_read(chunk_left))
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/http/client.py", line 613, in _safe_read
    data = self.fp.read(amt)
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
neosnippet-snippets: The read operation timed out
Traceback (most recent call last):
  File "/home/rschuetz/devel/nixpkgs/maintainers/scripts/pluginupdate.py", line 471, in prefetch
    plugin, redirect = prefetch_plugin(pluginDesc, cache)
  File "/home/rschuetz/devel/nixpkgs/maintainers/scripts/pluginupdate.py", line 326, in prefetch_plugin
    commit, date = repo.latest_commit()
  File "/home/rschuetz/devel/nixpkgs/maintainers/scripts/pluginupdate.py", line 64, in f_retry
    return f(*args, **kwargs)
  File "/home/rschuetz/devel/nixpkgs/maintainers/scripts/pluginupdate.py", line 124, in latest_commit
    with urllib.request.urlopen(commit_req, timeout=10) as req:
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/urllib/request.py", line 1350, in do_open
    r = h.getresponse()
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
targets.vim: The read operation timed out
Traceback (most recent call last):
  File "/home/rschuetz/devel/nixpkgs/maintainers/scripts/pluginupdate.py", line 471, in prefetch
    plugin, redirect = prefetch_plugin(pluginDesc, cache)
  File "/home/rschuetz/devel/nixpkgs/maintainers/scripts/pluginupdate.py", line 326, in prefetch_plugin
    commit, date = repo.latest_commit()
  File "/home/rschuetz/devel/nixpkgs/maintainers/scripts/pluginupdate.py", line 64, in f_retry
    return f(*args, **kwargs)
  File "/home/rschuetz/devel/nixpkgs/maintainers/scripts/pluginupdate.py", line 124, in latest_commit
    with urllib.request.urlopen(commit_req, timeout=10) as req:
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/urllib/request.py", line 1350, in do_open
    r = h.getresponse()
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
```

**Comment by chuahou** [comment]
I just ran update.py without the error you encountered, I'm not sure why. The result is in https://github.com/ch-fork/nixpkgs/commit/98426ba308658f6ea8f9208694ab3ca11cd16da6, will open a PR after doing some checks.

**Pull request merged**
