### PR TITLE
element-{web,desktop}: 1.8.5 -> 1.9.0

### PR DESCRIPTION
**Pull request by sumnerevans**
###### Motivation for this change

https://github.com/vector-im/element-web/releases/tag/v1.9.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kranzes** [comment]
Result of `nixpkgs-review pr 139647` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>element-desktop</li>
    <li>element-desktop-wayland</li>
    <li>element-web</li>
  </ul>
</details>

**Review by Kranzes — APPROVED** [review]

**Comment by lovesegfault** [comment]
@GrahamcOfBorg eval

**Comment by lovesegfault** [comment]
Ah, @sumnerevans please split into a commit for `-web` and a commit for `-desktop` please.

**Comment by lovesegfault** [comment]
@GrahamcOfBorg eval element-web, element-desktop

**Comment by sumnerevans** [comment]
@lovesegfault in the past, it has worked without splitting it into multiple commits: https://github.com/NixOS/nixpkgs/pull/137869

**Comment by lovesegfault** [comment]
Result of `nixpkgs-review pr 139647` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>element-desktop</li>
    <li>element-desktop-wayland</li>
  </ul>
</details>

**Comment by lovesegfault** [comment]
Result of `nixpkgs-review pr 139647` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>element-desktop</li>
    <li>element-desktop-wayland</li>
  </ul>
</details>

**Pull request merged**
