### PR TITLE
tree-sitter: 0.20.7 -> 0.20.8

### PR DESCRIPTION
**Pull request by teto**
0.20.8 will be required by neovim 0.9 so this is a preliminary bump

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by teto** [comment]
seems to pass nixpkgs-review

**Comment by teto** [comment]
@DieracDelta could you push the fix you proposed https://github.com/NixOS/nixpkgs/pull/225152#issuecomment-1500264419 here ?

**Comment by DieracDelta** [comment]
err do I have push perms? The fix is the change [here](https://github.com/NixOS/nixpkgs/blob/09f49769746a9ba87ea3985402615e0f90dc7ffb/pkgs/development/tools/parsing/tree-sitter/default.nix#L115)

**Comment by teto** [comment]
I think so, I've allowed edit by maintainers and you are part of the nixpkgs org . I would rather have you push because you can test, if it doesn't work, I can do it.

**Comment by DieracDelta** [comment]
I don't have push perms, but here's the diff:
```
diff --git a/pkgs/development/tools/parsing/tree-sitter/default.nix b/pkgs/development/tools/parsing/tree-sitter/default.nix
index 3cb407fa0ab..9da09a10e7e 100644
--- a/pkgs/development/tools/parsing/tree-sitter/default.nix
+++ b/pkgs/development/tools/parsing/tree-sitter/default.nix
@@ -16,7 +16,7 @@
 , Security
 , callPackage
 , linkFarm
-
+, CoreServices
 , enableShared ? !stdenv.hostPlatform.isStatic
 , enableStatic ? stdenv.hostPlatform.isStatic
 , webUISupport ? false
@@ -111,7 +111,7 @@ rustPlatform.buildRustPackage {
   inherit src version cargoSha256;

   buildInputs =
-    lib.optionals stdenv.isDarwin [ Security ];
+    lib.optionals stdenv.isDarwin [ Security CoreServices];
   nativeBuildInputs =
     [ which ]
     ++ lib.optionals webUISupport [ emscripten ];
diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
index 781d5efafc7..28320db77cc 100644
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -19013,7 +19013,7 @@ with pkgs;
   travis = callPackage ../development/tools/misc/travis { };

   tree-sitter = makeOverridable (callPackage ../development/tools/parsing/tree-sitter) {
-    inherit (darwin.apple_sdk.frameworks) Security;
+    inherit (darwin.apple_sdk.frameworks) Security CoreServices;
   };

   tree-sitter-grammars = recurseIntoAttrs tree-sitter.builtGrammars;
   ```

**Comment by teto** [comment]
@Profpatsch looks good to go ?

**Review by luxus — APPROVED** [review]

**Comment by luxus** [comment]
lgtm

**Comment by teto** [comment]
nxipkgs-review looks broken for me, it builds 1300 packages (mostly vim plugins) than shows up with an internal error. Plugins  build fine, neovim and emacs too so merging this since it's a neovim 0.9 blocker.

**Pull request merged**
