### PR TITLE
fastfetch: switch to apple-sdk_15

### PR DESCRIPTION
**Pull request by khaneliman**
## Things done
Upstream uses `@available` and `#ifdef` checks for SDK features. Bumping to latest SDK and patching so that we don't need to bump minimum.

https://github.com/fastfetch-cli/fastfetch/blob/e0acce9646d7cd0b45506cf618d0401974b57875/src/detection/camera/camera_apple.m#L17-L25
> `if (@available(macOS 14.0, *))`

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 352623`

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>fastfetch</li>
    <li>fastfetch.man</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>fastfetch</li>
    <li>fastfetch.man</li>
  </ul>
</details>

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 352623`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>fastfetch</li>
    <li>fastfetch.man</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>fastfetch</li>
    <li>fastfetch.man</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>fastfetch</li>
    <li>fastfetch.man</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>fastfetch</li>
    <li>fastfetch.man</li>
  </ul>
</details>

**Comment by khaneliman** [comment]
@emilazy so this one should be fine because they use   #ifdef MAC_OS_VERSION_14_0 ?

**Comment by emilazy** [comment]
Yeah I think that’s a janky check for SDK version. Theoretically it would build on an older SDK version, but given that they’ve added functionality for newer ones, there’s no reason to.

**Comment by khaneliman** [comment]
Alright, bumped min to match availability checks

**Comment by khaneliman** [comment]
```bash
fastfetch> /tmp/nix-build-fastfetch-2.28.0.drv-0/source/src/detection/gpu/gpu_apple.m:59:40: warning: 'MTLGPUFamilyMetal3' is only available on macOS 13.0 or newer [-Wunguarded-availability-new]
fastfetch>             if ([device supportsFamily:MTLGPUFamilyMetal3])
fastfetch>                                        ^~~~~~~~~~~~~~~~~~
fastfetch> /nix/store/p3hq1kd6lw5zwqznwzsh4gy72mmhriwp-apple-sdk-15.0/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLDevice.h:222:5: note: 'MTLGPUFamilyMetal3' has been marked as being introduced in macOS 13.0 here, but the deployment target is macOS 11.0.0
fastfetch>     MTLGPUFamilyMetal3 API_AVAILABLE(macos(13.0), ios(16.0)) = 5001,
fastfetch>     ^
fastfetch> /tmp/nix-build-fastfetch-2.28.0.drv-0/source/src/detection/gpu/gpu_apple.m:59:40: note: enclose 'MTLGPUFamilyMetal3' in an @available check to silence this warning
fastfetch>             if ([device supportsFamily:MTLGPUFamilyMetal3])
fastfetch>                                        ^~~~~~~~~~~~~~~~~~
fastfetch> 1 warning generated.
```
Just double checking this real quick.

**Comment by khaneliman** [comment]
Created a patch, for now. Upstream PR created https://github.com/fastfetch-cli/fastfetch/pull/1371

**Comment by khaneliman** [comment]
Removing patch since it should be fine, but upstream PR still open to resolve warnings and fix some of the availability checks.

**Review by GaetanLepage — APPROVED** [review]
LGTM

**Pull request merged**
