### PR TITLE
vscode-extensions.hashicorp.terraform: Init at 2.3.0

### PR DESCRIPTION
**Pull request by andyrichardson**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Please fix the typo in your commit.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110505` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>vscode-extensions.hashicorp.terraform</li>
</ul>
</details>

**Comment by rhoriguchi** [comment]
I tried this as well but the extension won't really run correctly. What you are missing is the [Terraform Language Server](https://github.com/hashicorp/terraform-ls) Nix has a [package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/misc/terraform-ls/default.nix) for it. The syntax highlighting does work but the language features do not and you get an error every time you open VS Code.

image

**Comment by rhoriguchi** [comment]
This is what I've tried till now, but still getting an error:
```nix
hashicorp.terraform = (vscode-utils.extensionFromVscodeMarketplace {
  name = "terraform";
  publisher = "hashicorp";
  version = "2.3.0";
  sha256 = "0696q8nr6kb5q08295zvbqwj7lr98z18gz1chf0adgrh476zm6qq";
}).overrideAttrs (oldAttrs: {
  buildInputs = oldAttrs.buildInputs ++ [ pkgs.terraform-ls ];

  meta = with lib; {
    license = licenses.mit;
  };
});
```

After going through the source of the extension, I think building from source and replacing these [lines](https://github.com/hashicorp/vscode-terraform/blob/ac6849c4e48c11f851782f4817b312194a571af1/src/extension.ts#L228-L238) with `command = "[TERRAFORM-LS PATH]"` should do the trick.

**Comment by rhoriguchi** [comment]
@andyrichardson So had some time today and I figured it out. This is how I got it to work:

```nix
{lib, vscode-utils, fetchurl, terraform-ls}:

vscode-utils.buildVscodeMarketplaceExtension rec {
  mktplcRef = {
    name = "terraform";
    publisher = "hashicorp";
    version = "2.4.0";
  };

  vsix = fetchurl {
    name = "${mktplcRef.publisher}-${mktplcRef.name}.zip";
    url = "https://github.com/hashicorp/vscode-terraform/releases/download/v${mktplcRef.version}/terraform-${mktplcRef.version}.vsix";
    sha256 = "14waz0yv25f4l46y84px2g58qnawbzp1p24zrfjqlxmp99kx009n";
  };

  patches = [ ./fix-terraform-ls.patch ];

  postPatch = ''
    substituteInPlace out/extension.js --replace TERRAFORM-LS-PATH ${terraform-ls}/bin/terraform-ls
  '';

  meta = with lib; { 
    license = licenses.mit; 
  };
}
```

---

**fix-terraform-ls.patch**
```patch
diff --git a/out/extension.js b/out/extension.js
index 1de8aab..e2b3a3e 100644
--- a/out/extension.js
+++ b/out/extension.js
@@ -204,19 +204,7 @@ function pathToBinary() {
         if (!_pathToBinaryPromise) {
             let command = vscodeUtils_1.config('terraform').get('languageServer.pathToBinary');
             if (!command) { // Skip install/upgrade if user has set custom binary path
-                const installDir = `${extensionPath}/lsp`;
-                const installer = new languageServerInstaller_1.LanguageServerInstaller();
-                try {
-                    yield installer.install(installDir);
-                }
-                catch (err) {
-                    vscode.window.showErrorMessage(err);
-                    throw err;
-                }
-                finally {
-                    yield installer.cleanupZips(installDir);
-                }
-                command = `${installDir}/terraform-ls`;
+                command = 'TERRAFORM-LS-PATH';
             }
             _pathToBinaryPromise = Promise.resolve(command);
         }
```

**Comment by andyrichardson** [comment]
@rhoriguchi thanks for helping out on this!

> What you are missing is the Terraform Language Server

When users typically install the package to VSCode (without nix) it also doesn't install the language server, no?

While the plugin can optionally integrate with a system-level language server, I'm unsure why it would be required as a build dependency?

**Comment by SuperSandro2000** [comment]
> When users typically install the package to VSCode (without nix) it also doesn't install the language server, no?

Because if it should work on multiple linux versions you can't easily install it for the package manager. One way around this is to vendor it which has its own problems.

> While the plugin can optionally integrate with a system-level language server, I'm unsure why it would be required as a build dependency?

This is a common thing to do in nixpkgs so that we have everything for it to run and you do not need to install something in your user environment.

**Comment by rhoriguchi** [comment]
> When users typically install the package to VSCode (without nix) it also doesn't install the language server, no?

When you install the extension for the first time it will try to download the language server. The only way to not make it auto-download, is to manually set the option: `terraform.languageServer.pathToBinary`. Otherwise, it will always check the installation and will download or update it. The issue with nix is, that the store is read-only so it has no way to install it, which causes that error.

---

Here are some other extensions that also have the language server bundled:
- [ms-python.python](https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/vscode-extensions/python/default.nix)
- [ms-vscode.cpptools](https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/vscode-extensions/cpptools/default.nix)
- [PR ms-dotnettools.csharp](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp)

**Comment by andyrichardson** [comment]
> When you install the extension and you open a `.tf` file it will try to download the language server

Ahh thanks for explaining - so the issue is that it tries to write to our immutable extension dir. That makes sense 👍

**Pull request closed without merging**
