### PR TITLE
cc-wrapper: gross hack for staging-next to fix scipy **revert this when merging staging-next to staging**

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/NixOS/nixpkgs/pull/225220 plus an ugly hack to avoid a mass-rebuild on staging-next

### CODE REVIEW

**Comment by amjoseph-nixpkgs** [comment]
@ofborg build python3Packages.scipy

Should build correctly.

**Comment by amjoseph-nixpkgs** [comment]
@ofborg build python3Packages.scikit-learn

**Review by vcunat — CHANGES_REQUESTED** [review]
This does **not** fix the `.scikit-learn` build for me.

**Comment by vcunat** [comment]
Speaking of temporary hacks this one worked for me:
```diff
--- a/pkgs/development/python-modules/scikit-learn/default.nix
+++ b/pkgs/development/python-modules/scikit-learn/default.nix
@@ -56,4 +56,6 @@ buildPythonPackage rec {
   '';
 
+  NIX_LDFLAGS = "-L${stdenv.cc.cc.lib}/lib";
+
   doCheck = !stdenv.isAarch64;
 
```
(It would probably need adding a condition on `stdenv.cc.isGNU`.)

**Comment by vcunat** [comment]
Pushed as 46f29d4bd63 as momentary unblocker.

**Comment by amjoseph-nixpkgs** [comment]
Yeah I guess we can't fix this without a mass-rebuild.

**Comment by vcunat** [comment]
Maybe we won't need this more complex temporary hack (i.e. do this smaller amount of rebuilds).  So far I'm not aware of any package needing it.

**Comment by amjoseph-nixpkgs** [comment]
> Maybe we won't need this more complex temporary hack (i.e. do this smaller amount of rebuilds).

Meaning that you intend to merge https://github.com/NixOS/nixpkgs/pull/225220 and revert 46f29d4bd6305a9f7c743d3f9022a8d5f6d3cb12?

**Comment by vcunat** [comment]
That's what I assumed so far.

**Comment by vcunat** [comment]
It's certainly simpler and hopefully it will suffice.

**Comment by amjoseph-nixpkgs** [comment]
> That's what I assumed so far.

Sounds good.

**Pull request closed without merging**
