### PR TITLE
rambox: fix incorrect sha256

### PR DESCRIPTION
**Pull request by anpryl**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by lheckemann** [comment]
It seems some other commits sneaked their way in here. Also, do you know why the sha256 changed? Perhaps we also need to fix the download URL or something to avoid this happening again.

**Comment by Mic92** [comment]
This is bad it could mean that the npm fixed input derivation is not reproducible, cc @yegortimoshenko

**Comment by Mic92** [comment]
Cherry-picked here: 4051fc901b52c233b7fa3f4ee2ac390ed3406583

**Comment by Mic92** [comment]
backport: ff7413b1603

**Pull request closed without merging**
