### PR TITLE
Update/jetbrains

### PR DESCRIPTION
**Pull request by kolaente**
###### Motivation for this change

Updates various jetbrains IDEs by running the `update.pl` script.

I tested the execution of `idea-community`, `goland` and `phpstorm`. Each of these failed with a segfault but I'm pretty sure this is not a fault of nix or this update since I had this occasionally with the current versions and execution worked in #96449
To make sure they work though it would be a good idea if someone reviewing this could also try to build + run them.
I also contacted jetbrains about the segfaults because again, I suspect my particular setup at fault here.

This PR is partially identical with  #96449 but contains a few more updates (like phpstorm) which were probably not available at the time of the other PR. Both should be mergable without conflicting each other.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by raboof — APPROVED** [review]
I can confirm intellij-idea works for me and can import, build and run a Scala (sbt) project for me.

**Review by Ma27 — APPROVED** [review]
Tested `idea.phpstorm` and `idea.idea-community` (using both actively) and everything seems fine.
@kolaente would you mind preparing a backport PR for 20.09? I guess that it's fine to backport patch-level releases to stable :)

**Comment by kolaente** [comment]
@Ma27 Sure, will do.

**Comment by kolaente** [comment]
Backport is up: #97474

**Comment by kolaente** [comment]
The "working" backport: #97477 (It was easier to create a new branch from 20.09 and cherry-pick everything into that again than rebasing the branch I had onto 20.09)

**Comment by Ma27** [comment]
@kolaente didn't `git rebase --onto`[1] work? :) 

[1] https://git-scm.com/docs/git-rebase#Documentation/git-rebase.txt---ontoltnewbasegt

**Comment by kolaente** [comment]
@Ma27 I completely forgot that's a thing tbh

**Comment by Gerschtli** [comment]
Hey, I didn't find a better place to ask but I tried running `update.pl` to update the jetbrains packages but I got following error:

```
$ cd pkgs/applications/editors/jetbrains
$ ./update.pl 
updating CLion RELEASE: 2020.2.1 -> 2020.2.2
Jetbrains published SHA256: b638369135a418855f07350b4d07658cd1e98dff2b80f6fa2fd11e5aaad3f3cd
Conversion into base32 yields: 1kgksfm5l7ni5zxgd01bzy6yklcccl3ls2rm0xgqa6546n8kcf5n
DataGrip RELEASE is up to date at 2020.2.2
GoLand RELEASE is up to date at 2020.2.2
updating IntelliJ IDEA RELEASE: 2020.2.1 -> 2020.2.2
Jetbrains published SHA256: e6c9e868da73a3e9936cd19d2bc99119a3cec8b622226a78583fc3ed0e4e764d
Conversion into base32 yields: 0kbn9q7fvhrzb1w6l8i2nv4cx8qrj74jp7fidj9yk8vkv9lfijg6
updating IntelliJ IDEA RELEASE: 2020.2.1 -> 2020.2.2
Jetbrains published SHA256: 269ba62b3ec9214864244ab490273cad6fb87f15ed6739c31129e7b758fe2685
Conversion into base32 yields: 1196zrcbgrr9271kjrzd2mzvhvxd7hkr1d2a4ij4h8f97qmsd6r6
updating MPS RELEASE: 2020.1.4 -> 2020.2
invalid sha256 in https://download.jetbrains.com/mps/2020.1/MPS-2020.2-202.6397.948.tar.gz.sha256 at ./update.pl line 75.
```

Does anyone know what I need to do to fix this? My knowledge in perl is like non existent, but I would be glad to help :)

**Comment by LeUlukai** [comment]
Jetbrains does not use uniform URLs for their products. The problem in this case is MPS. There, the version is not only used in the file to be downloaded, but also **partly** (major.minor) in the path. Have a look at `default.nix`:
```nix
      url = "https://download.jetbrains.com/mps/2020.1/MPS-${version}.tar.gz";
```
The update script only changes the `version` and `sha256` variables and not the `url`. MPS has been updated from `2020.1` to `2020.2` and thus, the `url` has to be updated manually:
```nix
      url = "https://download.jetbrains.com/mps/2020.2/MPS-${version}.tar.gz";
```
Maybe there is a way to do this in the script as well? Unfortunately, I don't know perl good enough.

**Comment by Gerschtli** [comment]
That is good to know. I will create a PR with jetbrains updates and afterwards have a look at the update script :)

**Pull request merged**
