### PR TITLE
mesa: 21.0.1 -> 21.0.2

### PR DESCRIPTION
**Pull request by primeos**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by vcunat — APPROVED** [review]
Seems OK, but I haven't tried running against the drivers.

**Comment by vcunat** [comment]
https://lists.freedesktop.org/archives/mesa-announce/2021-April/000625.html

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 118753` at e3bc983d run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>699 packages marked as broken and skipped:</summary>
  <ul>
    <li>adobe-reader</li>
    <li>adoptopenjdk-hotspot-bin-13</li>
    <li>adoptopenjdk-hotspot-bin-14</li>
    <li>adoptopenjdk-jre-hotspot-bin-13</li>
    <li>adoptopenjdk-jre-hotspot-bin-14</li>
    <li>adoptopenjdk-jre-openj9-bin-13</li>
    <li>adoptopenjdk-jre-openj9-bin-14</li>
    <li>adoptopenjdk-openj9-bin-13</li>
    <li>adoptopenjdk-openj9-bin-14</li>
    <li>agdaPackages.iowa-stdlib</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/cbcdeef902a030edfb8fd1d9d152375f">ocz-ssd-guru</a></li>
  </ul>
</details>
<details>
  <summary>8284 packages skipped due to time constraints:</summary>
  <ul>
    <li>AusweisApp2</li>
    <li>DisnixWebService</li>
    <li>EmptyEpsilon</li>
    <li>Fabric (python38Packages.Fabric)</li>
    <li>MIDIVisualizer</li>
    <li>OSCAR</li>
    <li>R</li>
    <li>SDL</li>
    <li>SDL2_gfx</li>
    <li>SDL2_image</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>38 packages built successfully:</summary>
  <ul>
    <li>SDL2</li>
    <li>asciidoctor</li>
    <li>at-spi2-atk</li>
    <li>at-spi2-core</li>
    <li>atk (gnome2.atk ,gnome3.atk)</li>
    <li>cairo (gnome2.cairo)</li>
    <li>egl-wayland</li>
    <li>epoxy</li>
    <li>freeglut</li>
    <li>gdk-pixbuf</li>
    <li>gl2ps</li>
    <li>libsoup (gnome2.libsoup)</li>
    <li>pango (gnome2.pango)</li>
    <li>gobject-introspection (gnome3.gobject-introspection)</li>
    <li>gsettings-desktop-schemas (gnome3.gsettings-desktop-schemas)</li>
    <li>libgudev (gnome3.libgudev)</li>
    <li>tracker (gnome3.tracker)</li>
    <li>harfbuzz</li>
    <li>icesl</li>
    <li>json-glib</li>
    <li>lasem</li>
    <li>libGL</li>
    <li>libGLU (mesa_glu)</li>
    <li>libass</li>
    <li>libdevil</li>
    <li>libinput</li>
    <li>libmanette</li>
    <li>libmbim</li>
    <li>libnotify</li>
    <li>libqrtr-glib</li>
    <li>libva</li>
    <li>libwacom</li>
    <li>mesa</li>
    <li>python38Packages.dbus-python</li>
    <li>python38Packages.pycairo</li>
    <li>python38Packages.pygobject3</li>
    <li>softmaker-office</li>
    <li>tesseract4</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: unused-argument

Unused argument: `enableRadv`.
Near pkgs/development/libraries/mesa/default.nix:8:3:
```
  |
8 | , enableRadv ? true
  |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unnecessary-parallel-building.md">unnecessary-parallel-building</a>

Meson, CMake and qmake already set `enableParallelBuilding = true` by default so it is not necessary.

Near pkgs/development/libraries/mesa/default.nix:147:3:
```
    |
147 |   enableParallelBuilding = true;
    |   ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement.

**Comment by primeos** [comment]
My initial testing was fine and I can successfully launch applications and X11 but I just noticed that I cannot launch `sway` and `cage` anymore (Cage seems to fail due to XWayland segfaulting but for Sway I've disabled XWayland) - both of them will segfault but run fine if I revert this update. This might only affect the `iris` driver though. I haven't seen any bug reports about this yet so it could also be Nixpkgs related. Not sure if I'll have time to investigate or if it's even worth it (vs. waiting for the next release).

Here's the output for starting Signal-Desktop via Cage:
```
sway[874]: glamor: No eglstream capable devices found
sway[874]: (EE)
sway[874]: (EE) Backtrace:
sway[874]: (EE) 0: Xwayland (OsSigHandler+0x25) [0x5a2925]
sway[874]: (EE) 1: /nix/store/1jn6apz0fa9h9x7rl3v6vwiymwnjznwv-glibc-2.32-40/lib/libpthread.so.0 (funlockfile+0x50) [0x7f4f4f14e700]
sway[874]: (EE) 2: /run/opengl-driver/lib/dri/iris_dri.so (driCreateContextAttribs+0x56) [0x7f4f4d774386]
sway[874]: (EE) 3: /run/opengl-driver/lib/dri/iris_dri.so (driCreateNewContext+0x2e) [0x7f4f4d77482e]
sway[874]: (EE) 4: /nix/store/mijk8fqjp82xnh8w8b0s5jsxn10386qq-mesa-21.0.2-drivers/lib/libEGL_mesa.so.0 (dri2_setup_extensions+0x16) [0x7f4f4e8ce0c6]
sway[874]: (EE) 5: /nix/store/mijk8fqjp82xnh8w8b0s5jsxn10386qq-mesa-21.0.2-drivers/lib/libEGL_mesa.so.0 (dri2_initialize_drm+0x236) [0x7f4f4e8d3ca6]
sway[874]: (EE) 6: /nix/store/mijk8fqjp82xnh8w8b0s5jsxn10386qq-mesa-21.0.2-drivers/lib/libEGL_mesa.so.0 (dri2_initialize+0x88) [0x7f4f4e8cc258]
sway[874]: (EE) 7: /nix/store/mijk8fqjp82xnh8w8b0s5jsxn10386qq-mesa-21.0.2-drivers/lib/libEGL_mesa.so.0 (eglInitialize+0x1dc) [0x7f4f4e8c4b0c]
sway[874]: (EE) 8: Xwayland (xwl_glamor_gbm_init_egl+0xb9) [0x44c439]
sway[874]: (EE) 9: Xwayland (xwl_glamor_init+0x32) [0x44bc72]
sway[874]: (EE) 10: Xwayland (xwl_screen_init+0x6b9) [0x444799]
sway[874]: (EE) 11: Xwayland (AddScreen+0xd7) [0x56cef7]
sway[874]: (EE) 12: Xwayland (InitOutput+0xf5) [0x444965]
sway[874]: (EE) 13: Xwayland (dix_main+0x18c) [0x570aac]
sway[874]: (EE) 14: /nix/store/1jn6apz0fa9h9x7rl3v6vwiymwnjznwv-glibc-2.32-40/lib/libc.so.6 (__libc_start_main+0xed) [0x7f4f4efa1ded]
sway[874]: (EE) 15: Xwayland (_start+0x2a) [0x44239a]
sway[874]: (EE)
sway[874]: (EE) Segmentation fault at address 0xa0
sway[874]: (EE)
sway[874]: Fatal server error:
sway[874]: (EE) Caught signal 11 (Segmentation fault). Server aborting
sway[874]: (EE)
systemd-coredump[885]: Process 874 (Xwayland) of user 1001 dumped core.
sway[839]: 00:00:01.905 [ERROR] [xwayland/server.c:234] Xwayland startup failed, not setting up xwm
systemd-coredump[910]: Process 848 (signal-desktop) of user 1001 dumped core.
systemd-coredump[917]: Process 839 (.cage-wrapped) of user 1001 dumped core.
```

@vcunat do you mind if I just revert this commit for now or should we wait and see if we find a solution before this lands in `staging-next`/`master`?

**Comment by vcunat** [comment]
OK, it sounds best to revert until we know more.

**Comment by vcunat** [comment]
BTW, as of current `staging`, mesa updates aren't large rebuilds anymore...

**Comment by primeos** [comment]
Thanks for your fast reply, I've just reverted it in 25ae1fd29f81fd4a50d4cdf42292ae58d91336ac.

> BTW, as of current staging, mesa updates aren't large rebuilds anymore...

Wow, nice :) I didn't expect that the amount of rebuilds would drop that significantly, that's awesome!

**Comment by vcunat** [comment]
```
$ ./maintainers/scripts/rebuild-amount.sh HEAD^ HEAD
Estimating rebuild amount by counting changed Hydra jobs.
   1469 x86_64-darwin
    868 x86_64-linux
```

**Pull request merged**
