### PR TITLE
metals: 0.10.7 → 0.10.8

### PR DESCRIPTION
**Pull request by fabianhjr**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Tomahna — APPROVED** [review]
Tested the new derivation on nixos, works well. LGTM.
Thank you !

**Review by timokau — APPROVED** [review]

**Comment by fabianhjr** [comment]
Seems like macOS - x86_64 has a different hash?

`sha256-K/Pjo5VD9w4knelK0YwXFoZOzJDzjzlMjHF6fJZo524=`

Got a report from a macOS user.

**Comment by SuperSandro2000** [comment]
Probably because of the case insensitive filesystem. Maybe we can rename the effecting file?

Can you tell the person to compare both versions with diffoscope?

**Comment by fabianhjr** [comment]
Will do, thanks for the pointer. :3

**Comment by contrun** [comment]
Also failed on github actions runner (https://github.com/contrun/infra/runs/4076462708?check_suite_focus=true). Maybe it's not mac os specific.

**Comment by fabianhjr** [comment]
Thanks for the pointer @contrun, can reproduce locally. The hash changed and what I hadn't noticed is tat it is specifically about the `metals-deps` rather than `metals` itself. Will open a new PR.

```
error: hash mismatch in fixed-output derivation '/nix/store/c2vpmdah2na6xx5i8413f10mp6gqy7p2-metals-deps-0.10.8.drv':
         specified: sha256-xTJ+N/aYMEzAQnu1wwWQ/nGRMYiEMfNPiuUFHcFbU4c=
            got:    sha256-K/Pjo5VD9w4knelK0YwXFoZOzJDzjzlMjHF6fJZo524=
error: 1 dependencies of derivation '/nix/store/iblqkf6v0yr78kpc7p792lycfdw9xaj0-metals-0.10.8.drv' failed to build
```

**Pull request merged**
