### PR TITLE
crashdump module: fix evaluation.

### PR DESCRIPTION
**Pull request by symphorien**
###### Motivation for this change

the module was broken. It wouldn't even evaluate.
To work properly, this PR depends on #30413

The increase in memory size is motivated by my own needs and https://bugs.launchpad.net/ubuntu/+source/kexec-tools/+bug/785394

Is using kernelPatches to change kernel configuration options the canonical way to do so ? Should the documentation mention that ?

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bjornfor** [comment]
CC @viric.

**Comment by viric** [comment]
All fixes welcome! I can't easily evaluate it other than to repeat the claimed tests.

**Comment by bjornfor** [comment]
I've got no experience with the crashdump module, but IMHO it'd be nice to have more info in the commit message than "fix evaluation", to help users/reviewers.

**Comment by symphorien** [comment]
I added a description in the commit message.

**Review by bjornfor — APPROVED** [review]
Looks good. Not tested.

**Pull request merged**
