### PR TITLE
Elm: automate packaging with elm2nix

### PR DESCRIPTION
**Pull request by domenkozar**
- rewrite documentation
- automate the whole process into update.sh
- remove all legacy snippets
- build Elm on GHC 8.6.3

### CODE REVIEW

**Comment by domenkozar** [comment]
cc @jerith666 who did a bunch of cool work recently.

**Comment by jerith666** [comment]
I am super curious to try this out!  However, multiple dependencies of `pkgs.elmPackages.elm` fail to build at this commit -- have you looked into that yet?

**Comment by domenkozar** [comment]
Yeah it's due to LTS-13 bump. I'll see what I can do.

**Comment by domenkozar** [comment]
@GrahamcOfBorg build elmPackages.elm elmPackages.elm-format

**Comment by domenkozar** [comment]
@jerith666 compiles now :)

**Pull request merged**
