### PR TITLE
qemu: 2.8.0 -> 2.8.1

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

minor release.
some bugfixes and security patches are applied, but not all.
it also includes @dezgeg's patch mentioned in https://github.com/NixOS/nixpkgs/issues/23957#issuecomment-288117708

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by volth** [comment]
rebased for 17.03: https://github.com/NixOS/nixpkgs/compare/release-17.03...volth:qemu-2.8.1-nixos-17.03

**Comment by 7c6f434c** [comment]
Let's hope it doesn't break too many tests…

**Comment by 7c6f434c** [comment]
Cherry-picked your port to `release-17.03`

**Comment by volth** [comment]
It could be too late to merge it.
qemu-2.9 was released 3 days ago.
It has all the security and bug fixes included

**Comment by 7c6f434c** [comment]
I gave up and did a search of PRs by words «security/vulnerability/critical/CVE»

Turns out not to be good enough, yes

**Comment by volth** [comment]
I mean all the ```upstreamPatch```es in https://github.com/NixOS/nixpkgs/pull/24549/files could be removed, they are in 2.9

**Comment by 7c6f434c** [comment]
Yes, I understood that. I just didn't notice 2.9.0 is something that is ready to package in the first place

**Comment by 7c6f434c** [comment]
There is also 2.8.1.1 which may be a better choice for stable

**Comment by volth** [comment]
https://github.com/NixOS/nixpkgs/compare/master...volth:qemu-2.9.0
https://github.com/NixOS/nixpkgs/compare/release-17.03...volth:qemu-2.8.1.1

**Comment by 7c6f434c** [comment]
Thanks, pushed.

**Comment by 7c6f434c** [comment]
Ouch, 2.8.1.1 does not include new bugfix patches.

**Pull request merged**
