### PR TITLE
[21.05] linux_xanmod: 5.12.13 -> 5.13.0

### PR DESCRIPTION
**Pull request by moni-dz**
(cherry picked from commit 741f6efc6bac0c79f5f280bf0e1e8fa82c9020af)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 129315` at e483e83c run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>73 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/57c34bc2fbf447fb5005a4a54629ae9d">linuxPackages_xanmod.acpi_call</a></li>
    <li><a href="https://gist.github.com/f3f0394c2f22bbf2ab131e1fc30aa017">linuxPackages_xanmod.akvcam</a></li>
    <li><a href="https://gist.github.com/b210a3f0119bba3050c3d8657306b3f9">linuxPackages_xanmod.amdgpu-pro</a></li>
    <li><a href="https://gist.github.com/894d482c8054a0af3368345505b9b28e">linuxPackages_xanmod.anbox</a></li>
    <li><a href="https://gist.github.com/94c57cb8872c13bfb3a26398bd1997b8">linuxPackages_xanmod.asus-wmi-sensors</a></li>
    <li><a href="https://gist.github.com/999af3a720aad4a235b7b3c5ee0f80aa">linuxPackages_xanmod.batman_adv</a></li>
    <li><a href="https://gist.github.com/238b04c89045fc9fa378ca336c89cc00">linuxPackages_xanmod.bbswitch</a></li>
    <li><a href="https://gist.github.com/daafdc1a39e38eb33eb53a4267d263df">linuxPackages_xanmod.bcc</a></li>
    <li><a href="https://gist.github.com/1204024a0c706890f108af71585b6395">linuxPackages_xanmod.bpftrace</a></li>
    <li><a href="https://gist.github.com/04e9ec9e519329585fc026e67b13279b">linuxPackages_xanmod.broadcom_sta</a></li>
    <li><a href="https://gist.github.com/a1fb060778a349ddb4a5a2fb0b4ffecb">linuxPackages_xanmod.can-isotp</a></li>
    <li><a href="https://gist.github.com/dc977d6c35ddc9ca21ac45c6a413879d">linuxPackages_xanmod.chipsec</a></li>
    <li><a href="https://gist.github.com/a85c6ced2ec7d10fd11242e8bdabc722">linuxPackages_xanmod.cryptodev</a></li>
    <li><a href="https://gist.github.com/38aefed9fcccf5c70e1070b269ecc522">linuxPackages_xanmod.ddcci-driver</a></li>
    <li><a href="https://gist.github.com/cb7ae285ea5870e59c0f479a3819f78a">linuxPackages_xanmod.digimend</a></li>
    <li><a href="https://gist.github.com/8dc5f7880f36b1a61f80e7871510c556">linuxPackages_xanmod.ena</a></li>
    <li><a href="https://gist.github.com/c785ff1085fd8f884273919a58dfc382">linuxPackages_xanmod.evdi</a></li>
    <li><a href="https://gist.github.com/5a256925cded93a6a8186562ba6d46c2">linuxPackages_xanmod.facetimehd</a></li>
    <li><a href="https://gist.github.com/c1030c23293fa432e979ec92f7a96986">linuxPackages_xanmod.fwts-efi-runtime</a></li>
    <li><a href="https://gist.github.com/68bac0396fc316c8b7bc4b7310c48dac">linuxPackages_xanmod.gcadapter-oc-kmod</a></li>
    <li><a href="https://gist.github.com/300b7aa9616f75ea6b56807c4ed88dc8">linuxPackages_xanmod.hid-nintendo</a></li>
    <li><a href="https://gist.github.com/965c0872bb5b808ada6d0dcd5c79af33">linuxPackages_xanmod.isgx</a></li>
    <li><a href="https://gist.github.com/92f48b4ff531e02050baea8e5b9d780f">linuxPackages_xanmod.it87</a></li>
    <li><a href="https://gist.github.com/dbaa6e27d1774bbd4a9dd1cc1b45fd10">linuxPackages_xanmod.ixgbevf</a></li>
    <li><a href="https://gist.github.com/d9f35d6a41e39e703146177cbf4f863d">linuxPackages_xanmod.jool</a></li>
    <li><a href="https://gist.github.com/36ce565d2b9f8618b304aa4bd10de149">linux_xanmod</a> (linuxPackages_xanmod.kernel)</li>
    <li><a href="https://gist.github.com/f8a4bd44f7db68bb679198db71114ac2">linuxPackages_xanmod.lttng-modules</a></li>
    <li><a href="https://gist.github.com/2609d7639f90a3abec85d51cf0ca8bfb">linuxPackages_xanmod.mba6x_bl</a></li>
    <li><a href="https://gist.github.com/4665191e20004fd7b73b828f6db1b1c7">linuxPackages_xanmod.mbp2018-bridge-drv</a></li>
    <li><a href="https://gist.github.com/6d2e56bcfee2704a30987dd5240225bc">linuxPackages_xanmod.mwprocapture</a></li>
    <li><a href="https://gist.github.com/2cc7482acb65464ca05499e6ff1411d0">linuxPackages_xanmod.mxu11x0</a></li>
    <li><a href="https://gist.github.com/52a08433f51c149e318f4e1ade8d743c">linuxPackages_xanmod.ndiswrapper</a></li>
    <li><a href="https://gist.github.com/3cf84fc83697db3b11ae2746617916ef">linuxPackages_xanmod.netatop</a></li>
    <li><a href="https://gist.github.com/1db5d61f893a783c801eef0170643d2b">linuxPackages_xanmod.nvidia_x11</a></li>
    <li><a href="https://gist.github.com/42ad8e0bd4e96c404aa53d3feb3709a1">linuxPackages_xanmod.nvidia_x11_beta</a></li>
    <li><a href="https://gist.github.com/d32232e26846268252278ec9ef1a4418">linuxPackages_xanmod.nvidia_x11_legacy340</a></li>
    <li><a href="https://gist.github.com/070814a8649344bcb4dcb395730056ad">linuxPackages_xanmod.nvidia_x11_legacy390</a></li>
    <li><a href="https://gist.github.com/fe2f0640342b3fe00ee93a77774f32c7">linuxPackages_xanmod.nvidia_x11_vulkan_beta</a></li>
    <li><a href="https://gist.github.com/7be01ea707f15230b366ecc93022c6aa">linuxPackages_xanmod.nvidiabl</a></li>
    <li><a href="https://gist.github.com/79c6207af626e781cb7e97b35536a652">linuxPackages_xanmod.oci-seccomp-bpf-hook</a></li>
    <li><a href="https://gist.github.com/71a6eb3c4e9f14b150a9f893ad26e131">linuxPackages_xanmod.openrazer</a></li>
    <li><a href="https://gist.github.com/7cadc6b3a9a6d0510e4111549c9e854d">linuxPackages_xanmod.perf</a></li>
    <li><a href="https://gist.github.com/735a82673913e24fa2c3910467f94556">linuxPackages_xanmod.phc-intel</a></li>
    <li><a href="https://gist.github.com/e9e9cbe4b9babb594a84ac35cd061e57">linuxPackages_xanmod.r8125</a></li>
    <li><a href="https://gist.github.com/f1c7acf86e952272e53c08f4363dd7d0">linuxPackages_xanmod.r8168</a></li>
    <li><a href="https://gist.github.com/2f593f318d97383b641aab60bc27442e">linuxPackages_xanmod.rtl8192eu</a></li>
    <li><a href="https://gist.github.com/bef155c2f95a8399642f0e7a68132401">linuxPackages_xanmod.rtl8723bs</a></li>
    <li><a href="https://gist.github.com/67c34076abcc40d766da5db48a875469">linuxPackages_xanmod.rtl8812au</a></li>
    <li><a href="https://gist.github.com/4bb55bab92c7c9dd0ad2518beda19097">linuxPackages_xanmod.rtl8814au</a></li>
    <li><a href="https://gist.github.com/dc3a34ca7df15f867e0db34e070e1c14">linuxPackages_xanmod.rtl8821au</a></li>
    <li><a href="https://gist.github.com/0556dab07167039079666dfd910fc336">linuxPackages_xanmod.rtl8821ce</a></li>
    <li><a href="https://gist.github.com/75c1ea6ff03b9de745ed890a725f692a">linuxPackages_xanmod.rtl8821cu</a></li>
    <li><a href="https://gist.github.com/7c1cafc6dc36295a258ce9bb5c7ab64f">linuxPackages_xanmod.rtl88x2bu</a></li>
    <li><a href="https://gist.github.com/5e30e3ad4827ac9d40513ad5f36a805b">linuxPackages_xanmod.rtl88xxau-aircrack</a></li>
    <li><a href="https://gist.github.com/237a7981352ba205adabed3d9740c49b">linuxPackages_xanmod.rtw88</a> (linuxPackages_xanmod.rtlwifi_new)</li>
    <li><a href="https://gist.github.com/08cb55fa539192864daad9ac88d14568">linuxPackages_xanmod.sch_cake</a></li>
    <li><a href="https://gist.github.com/d4641ec10809b80c58a86b9903d68b87">linuxPackages_xanmod.sysdig</a></li>
    <li><a href="https://gist.github.com/d5a0ad12450297bf6e2b9da57718dde6">linuxPackages_xanmod.system76</a></li>
    <li><a href="https://gist.github.com/3a96ffadccc87d1505a6465cc4c689db">linuxPackages_xanmod.system76-acpi</a></li>
    <li><a href="https://gist.github.com/02104443adcbcc90564948b66755a59b">linuxPackages_xanmod.system76-io</a></li>
    <li><a href="https://gist.github.com/a9cf83dfe93710360b4d230812d74309">linuxPackages_xanmod.systemtap</a></li>
    <li><a href="https://gist.github.com/ea6c9f6ff19b76b6ebde7c924db3afe9">linuxPackages_xanmod.tbs</a></li>
    <li><a href="https://gist.github.com/1a4b5aedf61eab0b3b1f59acb31687d9">linuxPackages_xanmod.tp_smapi</a></li>
    <li><a href="https://gist.github.com/88e8f0c563cff8afb21ff10632bb7c89">linuxPackages_xanmod.tuxedo-keyboard</a></li>
    <li><a href="https://gist.github.com/95232432938ca12e1ffa2d440a7cb862">linuxPackages_xanmod.v4l2loopback</a></li>
    <li><a href="https://gist.github.com/72a7b2cce7e590a409b322d204d87b93">linuxPackages_xanmod.v86d</a></li>
    <li><a href="https://gist.github.com/9690fd81efdc96992bb94c2e8f1525e1">linuxPackages_xanmod.vendor-reset</a></li>
    <li><a href="https://gist.github.com/fa390e552afde5f9854d88f2f11902e6">linuxPackages_xanmod.vhba</a></li>
    <li><a href="https://gist.github.com/6eae1a4e79dafa5630a349a08d1244fb">linuxPackages_xanmod.virtualboxGuestAdditions</a></li>
    <li><a href="https://gist.github.com/d60fffb9b6570f7de958427386e25628">linuxPackages_xanmod.xpadneo</a></li>
    <li><a href="https://gist.github.com/cab9e0fe398094f0a1e66e584d65f82f">linuxPackages_xanmod.zenpower</a></li>
    <li><a href="https://gist.github.com/71e6b00557ec4c80bb94e66fcf58d2f5">linuxPackages_xanmod.zfs</a> (linuxPackages_xanmod.zfsStable)</li>
    <li><a href="https://gist.github.com/45add14c9e1989d983a24456995039df">linuxPackages_xanmod.zfsUnstable</a></li>
  </ul>
</details>
<details>
  <summary>4 packages skipped due to time constraints:</summary>
  <ul>
    <li>linuxPackages_xanmod.dpdk-kmods</li>
    <li>linuxPackages_xanmod.openafs (linuxPackages_xanmod.openafs_1_8)</li>
    <li>linuxPackages_xanmod.openafs_1_9</li>
    <li>linuxPackages_xanmod.virtualbox</li>
  </ul>
</details>
<details>
  <summary>8 packages built successfully:</summary>
  <ul>
    <li>linuxPackages_xanmod.cpupower</li>
    <li>linuxPackages_xanmod.hyperv-daemons</li>
    <li>linuxPackages_xanmod.intel-speed-select</li>
    <li>linuxPackages_xanmod.ply</li>
    <li>linuxPackages_xanmod.tmon</li>
    <li>linuxPackages_xanmod.turbostat</li>
    <li>linuxPackages_xanmod.usbip</li>
    <li>linuxPackages_xanmod.x86_energy_perf_policy</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by fortuneteller2k** [comment]
merge after backport of #128538

**Comment by ckauhaus** [comment]
Could someone who has any clue what xanmod is all about please review this PR?

**Comment by Artturin** [comment]
linux_latest is at `5.14.12` in 21.05 so this should be safe to merge

**Comment by Artturin** [comment]
@ofborg eval

**Comment by Artturin** [comment]
Result of `nixpkgs-review pr 129315` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxPackages_xanmod.anbox</li>
    <li>linuxPackages_xanmod.ixgbevf</li>
    <li>linuxPackages_xanmod.lttng-modules</li>
    <li>linuxPackages_xanmod.ndiswrapper</li>
    <li>linuxPackages_xanmod.phc-intel</li>
    <li>linuxPackages_xanmod.r8125</li>
    <li>linuxPackages_xanmod.rtl8723bs</li>
    <li>linuxPackages_xanmod.sch_cake</li>
    <li>linuxPackages_xanmod.tbs</li>
  </ul>
</details>
<details>
  <summary>8 packages failed to build:</summary>
  <ul>
    <li>linuxPackages_xanmod.amdgpu-pro</li>
    <li>linuxPackages_xanmod.mxu11x0</li>
    <li>linuxPackages_xanmod.nvidia_x11_legacy340</li>
    <li>linuxPackages_xanmod.nvidia_x11_legacy390</li>
    <li>linuxPackages_xanmod.nvidia_x11_vulkan_beta</li>
    <li>linuxPackages_xanmod.openafs (linuxPackages_xanmod.openafs_1_8)</li>
    <li>linuxPackages_xanmod.perf</li>
    <li>linuxPackages_xanmod.virtualboxGuestAdditions</li>
  </ul>
</details>
<details>
  <summary>69 packages built:</summary>
  <ul>
    <li>linuxPackages_xanmod.acpi_call</li>
    <li>linuxPackages_xanmod.akvcam</li>
    <li>linuxPackages_xanmod.asus-wmi-sensors</li>
    <li>linuxPackages_xanmod.batman_adv</li>
    <li>linuxPackages_xanmod.bbswitch</li>
    <li>linuxPackages_xanmod.bcc</li>
    <li>linuxPackages_xanmod.bpftrace</li>
    <li>linuxPackages_xanmod.broadcom_sta</li>
    <li>linuxPackages_xanmod.can-isotp</li>
    <li>linuxPackages_xanmod.chipsec</li>
    <li>linuxPackages_xanmod.cpupower</li>
    <li>linuxPackages_xanmod.cryptodev</li>
    <li>linuxPackages_xanmod.ddcci-driver</li>
    <li>linuxPackages_xanmod.digimend</li>
    <li>linuxPackages_xanmod.dpdk-kmods</li>
    <li>linuxPackages_xanmod.ena</li>
    <li>linuxPackages_xanmod.evdi</li>
    <li>linuxPackages_xanmod.facetimehd</li>
    <li>linuxPackages_xanmod.fwts-efi-runtime</li>
    <li>linuxPackages_xanmod.gcadapter-oc-kmod</li>
    <li>linuxPackages_xanmod.hid-nintendo</li>
    <li>linuxPackages_xanmod.hyperv-daemons</li>
    <li>linuxPackages_xanmod.intel-speed-select</li>
    <li>linuxPackages_xanmod.isgx</li>
    <li>linuxPackages_xanmod.it87</li>
    <li>linuxPackages_xanmod.jool</li>
    <li>linux_xanmod (linuxPackages_xanmod.kernel)</li>
    <li>linuxPackages_xanmod.mba6x_bl</li>
    <li>linuxPackages_xanmod.mbp2018-bridge-drv</li>
    <li>linuxPackages_xanmod.mwprocapture</li>
    <li>linuxPackages_xanmod.netatop</li>
    <li>linuxPackages_xanmod.nvidia_x11</li>
    <li>linuxPackages_xanmod.nvidia_x11_beta</li>
    <li>linuxPackages_xanmod.nvidiabl</li>
    <li>linuxPackages_xanmod.oci-seccomp-bpf-hook</li>
    <li>linuxPackages_xanmod.openafs_1_9</li>
    <li>linuxPackages_xanmod.openrazer</li>
    <li>linuxPackages_xanmod.ply</li>
    <li>linuxPackages_xanmod.r8168</li>
    <li>linuxPackages_xanmod.rtl8192eu</li>
    <li>linuxPackages_xanmod.rtl8812au</li>
    <li>linuxPackages_xanmod.rtl8814au</li>
    <li>linuxPackages_xanmod.rtl8821au</li>
    <li>linuxPackages_xanmod.rtl8821ce</li>
    <li>linuxPackages_xanmod.rtl8821cu</li>
    <li>linuxPackages_xanmod.rtl88x2bu</li>
    <li>linuxPackages_xanmod.rtl88xxau-aircrack</li>
    <li>linuxPackages_xanmod.rtw88 (linuxPackages_xanmod.rtlwifi_new)</li>
    <li>linuxPackages_xanmod.rtw89</li>
    <li>linuxPackages_xanmod.sysdig</li>
    <li>linuxPackages_xanmod.system76</li>
    <li>linuxPackages_xanmod.system76-acpi</li>
    <li>linuxPackages_xanmod.system76-io</li>
    <li>linuxPackages_xanmod.systemtap</li>
    <li>linuxPackages_xanmod.tmon</li>
    <li>linuxPackages_xanmod.tp_smapi</li>
    <li>linuxPackages_xanmod.turbostat</li>
    <li>linuxPackages_xanmod.tuxedo-keyboard</li>
    <li>linuxPackages_xanmod.usbip</li>
    <li>linuxPackages_xanmod.v4l2loopback</li>
    <li>linuxPackages_xanmod.v86d</li>
    <li>linuxPackages_xanmod.vendor-reset</li>
    <li>linuxPackages_xanmod.vhba</li>
    <li>linuxPackages_xanmod.virtualbox</li>
    <li>linuxPackages_xanmod.x86_energy_perf_policy</li>
    <li>linuxPackages_xanmod.xpadneo</li>
    <li>linuxPackages_xanmod.zenpower</li>
    <li>linuxPackages_xanmod.zfs (linuxPackages_xanmod.zfsStable)</li>
    <li>linuxPackages_xanmod.zfsUnstable</li>
  </ul>
</details>

**Pull request merged**
