### PR TITLE
bridge-utils: 1.5 -> 1.7.1

### PR DESCRIPTION
**Pull request by trofi**
While at it:
- updated package description (and mention DEPRECATED upstream status)
- switched to .xz tarball
- dropped upstreamed patch
- dropped explicit checks for build result as upstream fixed it.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 137670` at 05a63390 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>libvirt_5_9_0</li>
  </ul>
</details>
<details>
  <summary>1 package skipped due to time constraints:</summary>
  <ul>
    <li>virt-manager-qt</li>
  </ul>
</details>
<details>
  <summary>39 packages built successfully:</summary>
  <ul>
    <li>bridge-utils</li>
    <li>collectd</li>
    <li>collectd-data</li>
    <li>diffoscope</li>
    <li>docker-machine-kvm</li>
    <li>docker-machine-kvm2</li>
    <li>gnome.gnome-boxes</li>
    <li>haskellPackages.libvirt-hs</li>
    <li>k3s</li>
    <li>libguestfs</li>
    <li>libvirt</li>
    <li>libvirt-glib</li>
    <li>libvmi</li>
    <li>minikube</li>
    <li>minishift</li>
    <li>nixopsUnstable</li>
    <li>perl532Packages.SysVirt</li>
    <li>perl534Packages.SysVirt</li>
    <li>pipework</li>
    <li>python38Packages.guestfs</li>
    <li>python38Packages.libvirt</li>
    <li>python39Packages.guestfs</li>
    <li>python39Packages.libvirt</li>
    <li>qemu_xen (qemu_xen_4_10)</li>
    <li>qemu_xen-light (qemu_xen_4_10-light)</li>
    <li>qubes-core-vchan-xen</li>
    <li>rubyPackages.ruby-libvirt (rubyPackages_2_7.ruby-libvirt)</li>
    <li>rubyPackages_2_6.ruby-libvirt</li>
    <li>rubyPackages_3_0.ruby-libvirt</li>
    <li>terraform-full</li>
    <li>terraform-providers.libvirt</li>
    <li>vagrant</li>
    <li>virt-manager</li>
    <li>virt-top</li>
    <li>virt-viewer</li>
    <li>virtlyst</li>
    <li>xen (xenPackages.xen-vanilla ,xenPackages.xen_4_10-vanilla ,xen_4_10)</li>
    <li>xen-light (xenPackages.xen-light ,xenPackages.xen_4_10-light ,xen_4_10-light)</li>
    <li>xen-slim (xenPackages.xen-slim ,xenPackages.xen_4_10-slim ,xen_4_10-slim)</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/os-specific/linux/bridge-utils/default.nix:16:3:
```
   |
16 |   meta = {
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/os-specific/linux/bridge-utils/default.nix:12:15:
```
   |
12 |   patches = [ ./autoconf-ar.patch ];
   |               ^
```
</li>
  </ul>
</details>

**Comment by r-burns** [comment]
Changes LGTM, please resolve the merge conflict

**Comment by trofi** [comment]
Fixed merge conflict.

**Comment by r-burns** [comment]
Hmm, wonder why ofborg thinks there are darwin rebuilds - the nixpkgs-review was a no-op.

I trust the bot for linux so this looks good to go.

**Comment by SuperSandro2000** [comment]
> Hmm, wonder why ofborg thinks there are darwin rebuilds - the nixpkgs-review was a no-op.
> 
> I trust the bot for linux so this looks good to go.

I think there are some qemu variants which are maybe marked broken on darwin but they still have the platform.

**Pull request merged**
