### PR TITLE
nixos/spacenavd: run as user service

### PR DESCRIPTION
**Pull request by Sohalt**
###### Motivation for this change
This fixes the patches to run spacenavd as a user service.
However, it does not adjust the location of the default config (`/etc/spnavrc`) and the pid file (`/var/run/spnavd.pid`).
The user service obviously cannot write to these locations, so it is a bit of a problem. For example spnavcfg (as introduced in https://github.com/NixOS/nixpkgs/pull/118327) requires these files in their default location. I could of course also patch spnavcfg accordingly. What do you think? @gebner @flokli

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by flokli** [comment]
> The binary is installed setuid root in order to be able to modify /etc/spnavrc and send signals to the daemon. However, it was designed from start to be as secure as possible.

Huuh, yeah, this won't work editing files in the nix store, and running as setuid root isn't even required on user services.

**Comment by flokli** [comment]
@gebner can you give FreeCAD a try with this?

**Comment by Sohalt** [comment]
> Huuh, yeah, this won't work editing files in the nix store, and running as setuid root isn't even required on user services.

The module does not generate any config in the nix store currently (it just uses the defaults).
When running a user service, you obviously wouldn't need setuid root, but then you would need a user writable location for the config file (e.g. `~/.config/spnavrc`) and both spacenavd and spnavcfg would need to be patched accordingly.

**Comment by gebner** [comment]
I've just tried running freecad and it works fine with the system-wide daemon.

> Huuh, yeah, this won't work editing files in the nix store, and running as setuid root isn't even required on user services.

@flokli The `/etc/spnavrc` file is not in the nix store, it's a regular file in `/etc` and can be modified by root.  Configuring the daemon "works" at the moment, but you need to run `sudo spnavcfg`.

>  I could of course also patch spnavcfg accordingly. What do you think?

If we're already patching spacenavd and co., then I think we should really do this.  I don't have a strong opinion about whether the daemon should be a user service or not, but I'd really like to run spnavcfg without sudo.

**Comment by flokli** [comment]
>> I could of course also patch spnavcfg accordingly. What do you think?

> If we're already patching spacenavd and co., then I think we should really do this. I don't have a strong opinion about whether the daemon should be a user service or not, but I'd really like to run spnavcfg without sudo.

Yeah, then let's also add the same config file location logic to spnavcfg, so it can read and edit user config. We certainly don't want to setuid spnavcfg and have it poke around in `/etc`.

**Comment by Sohalt** [comment]
I'll try to get around patching everything by the end of the week.

**Comment by Sohalt** [comment]
It took me a little longer, but I've patched everything. I haven't tested everything in combination yet however. If someone finds the time, feel free to give it a go.

**Comment by gebner** [comment]
Built and tested.  FreeCAD with patched libspnav works with the upstream daemon.  After switching to the patched spacenavd, FreeCAD works and spnavcfg no longer requires sudo.

**Pull request merged**
