### PR TITLE
protoc-gen-es: init at 1.10.0, protoc-gen-connect-es: init at 1.4.0

### PR DESCRIPTION
**Pull request by felschr**
###### Description of changes
Add 2 protoc plugins for the ECMAScript ecosystem developed by Buf for use with Protobuf & Connect:
[protoc-gen-es](https://github.com/bufbuild/protobuf-es/tree/main/packages/protoc-gen-es)
[protoc-gen-connect-es](https://github.com/connectrpc/connect-es/tree/main/packages/protoc-gen-connect-es)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by felschr** [comment]
For some reason the npm deps for `protoc-gen-es` fail to build:
```console
unpacking sources
unpacking source archive /nix/store/12md47d55g0an07msckkazlynw6y1fz4-source
source root is source
patching sources
updateAutotoolsGnuConfigScriptsPhase
configuring
no configure script, doing nothing
building
DEBUG 1, out: "/nix/store/k7pzr462jply2x2mrjs9gg9ad1jpy8z1-protoc-gen-es-1.2.1-npm-deps"
Error: No such file or directory (os error 2)
```

I've added some logging to `prefetch-npm-deps` which can be seen in the output above:

https://github.com/NixOS/nixpkgs/blob/a226f103d3ed01e04c68d1a5f0aaf424722fcfcd/pkgs/build-support/node/fetch-npm-deps/src/main.rs#L259-L265

I've tried creating the `$out` directory before invoking `prefetch-npm-deps` or within `prefetch-npm-deps`, but then it'll get a different os error 2 during the consistency validation instead:
```console
Validating consistency between /build/source/package-lock.json and /nix/store/k75l3phibjdsqgnbwfgz7mfwrn6r8rhn-protoc-gen-es-1.2.1-npm-deps/package-lock.json
Error: IO error for operation on /nix/store/k75l3phibjdsqgnbwfgz7mfwrn6r8rhn-protoc-gen-es-1.2.1-npm-deps/_cacache/index-v5: No such file or directory (os error 2)

Caused by:
    No such file or directory (os error 2)
```

The build for `protoc-gen-connect-es` works fine, though, and I can't figure out why it fails for `protoc-gen-es`, especially since the setup is basically identical.

**Comment by felschr** [comment]
@winterqt, @lilyinstarlight, do you have any idea what might cause this?

**Comment by felschr** [comment]
I just noticed, I've used the wrong `npmDepsHash` for a while. After fixing it I now always get the os error 2 for missing `[...]/_cacache/index-v5` after the "Validating consistency" step, even without adding `mkdir -p $out` before invoking `prefetch-npm-deps`.

The exact place where it fails is in `prefetch-npm-deps` invoked by `@prefetchNpmDeps@ --map-cache` in this line:
https://github.com/NixOS/nixpkgs/blob/e4db1840dcf3c73085ad72a4ef13fbbe788f5a20/pkgs/build-support/node/fetch-npm-deps/src/main.rs#L162

**Comment by felschr** [comment]
@ofborg build protoc-gen-es

**Comment by lilyinstarlight** [comment]
@felschr, these upstream lockfiles are busted and need to be deleted/regenerated. They contain hardly any `resolved` URLs or `integrity` hashes which are required to be able to cache them

The connect-es repo only works now because the package-lock.json in the latest release had that info, but it has since disappeared in the main branch since https://github.com/bufbuild/connect-es/commit/411bba56a53310dd510c1a0bbd65629b7141b4f5

You'll probably either need to vendor a working package-lock.json or bug upstream to fix their package-lock.json files (are they using some old npm version or something? why would that information disappear?)

We definitely need to have a better error message for this case in prefetch-npm-deps though, so I'll open a PR in a bit to detect and error out in this scenario

**Comment by felschr** [comment]
@lilyinstarlight, ah, thank you. It's indeed been quite painful to debug this.

**Comment by lilyinstarlight** [comment]
> @lilyinstarlight, ah, thank you. It's indeed been quite painful to debug this.

Yeah, sorry about that 😅

I've opened #243458 with a better error message and an escape hatch if someone really was trying to generate an empty cache for some reason

**Comment by felschr** [comment]
I've updated the PR to fix the `package-lock.json`, but I get an error now, that is similar to #223964, but I actually have the same package in different versions:

```console
Installing dependencies
npm WARN deprecated @types/lz-string@1.5.0: This is a stub types definition. lz-string provides its own type definitions, so you do not need this installed.
npm ERR! code ENOTCACHED
npm ERR! request to https://registry.npmjs.org/typescript failed: cache mode is 'only-if-cached' but no cached response is available.

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/cache/_logs/2023-07-14T15_29_02_932Z-debug-0.log

ERROR: npm failed to install dependencies

Here are a few things you can try, depending on the error:
1. Set `makeCacheWritable = true`
  Note that this won't help if npm is complaining about not being able to write to the logs directory -- look above that for the actual error.
2. Set `npmFlags = [ "--legacy-peer-deps" ]`
```

The `typescript` package is specified multiple times with different versions:
https://github.com/NixOS/nixpkgs/blob/4743531e505c34c29267d17460c7d9f04c61f63d/pkgs/development/tools/protoc-gen-es/package-lock.json#L5847-L5972

**Comment by felschr** [comment]
Same problem when I completely regenerate the `package-lock.json` instead of using `npm-lockfile-fix`.

**Comment by lilyinstarlight** [comment]
> Same problem when I completely regenerate the `package-lock.json` instead of using `npm-lockfile-fix`.

Did you update the `npmDepsHash`? I just downloaded the diff from this PR and the hash was wrong on my system

After fixing the hash, the build still fails but that's due to missing type stubs for typescript

**Comment by felschr** [comment]
> Did you update the `npmDepsHash`? I just downloaded the diff from this PR and the hash was wrong on my system

Might be, but I still get the cache error even with the correct hash.
I've now updated this PR to `protoc-gen-es` 1.3.0 which includes the fixed `package-lock.json` and it's the same error there:
```console
Installing dependencies
npm WARN deprecated @types/lz-string@1.5.0: This is a stub types definition. lz-string provides its own type definitions, so you do not need this installed.
npm ERR! code ENOTCACHED
npm ERR! request to https://registry.npmjs.org/typescript failed: cache mode is 'only-if-cached' but no cached response is available.
```

**Comment by felschr** [comment]
@ofborg build protoc-gen-es protoc-gen-connect-es

**Comment by felschr** [comment]
@lilyinstarlight could you take a look at this again? The `npmDepsHash` should be correct now, and ofborg shows the same error I get locally: https://github.com/NixOS/nixpkgs/pull/243432/checks?check_run_id=15618332384

**Comment by lilyinstarlight** [comment]
Apologies for taking so long to get back to this. The ofborg log is still gone, but it looks like `packages/protoplugin/node_modules/typescript` still doesn't have `integrity`/`resolved` info?

I'm wondering if this is some sort of npm bug since i've seen a number of workspace packages without actual lock info like this...

**Comment by felschr** [comment]
@lilyinstarlight oh, I completely overlooked that.
Those packages also weren't updated by `npm-lockfile-fix`, which I fixed in https://github.com/jeslie0/npm-lockfile-fix/pull/3

Now building the npm dependencies finally works, but the build currently fails for some other reason:

<details>

<summary>Build Log</summary>

```console
rebuilt dependencies successfully
patching script interpreter paths in node_modules
Finished npmConfigHook
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
Executing npmBuildHook

> @bufbuild/protoc-gen-es@1.3.0 build
> ../../node_modules/typescript/bin/tsc --project tsconfig.json --module commonjs --outDir ./dist/cjs

src/declaration.ts:20:8 - error TS2307: Cannot find module '@bufbuild/protobuf' or its corresponding type declarations.

20 } from "@bufbuild/protobuf";
          ~~~~~~~~~~~~~~~~~~~~

src/declaration.ts:25:8 - error TS2307: Cannot find module '@bufbuild/protoplugin/ecmascript' or its corresponding type declarations.

25 } from "@bufbuild/protoplugin/ecmascript";
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/declaration.ts:32:8 - error TS2307: Cannot find module '@bufbuild/protoplugin/ecmascript' or its corresponding type declarations.

32 } from "@bufbuild/protoplugin/ecmascript";
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/javascript.ts:15:55 - error TS2307: Cannot find module '@bufbuild/protobuf' or its corresponding type declarations.

15 import type { DescEnum, DescField, DescMessage } from "@bufbuild/protobuf";
                                                         ~~~~~~~~~~~~~~~~~~~~

src/javascript.ts:16:44 - error TS2307: Cannot find module '@bufbuild/protobuf' or its corresponding type declarations.

16 import { proto2, proto3, ScalarType } from "@bufbuild/protobuf";
                                              ~~~~~~~~~~~~~~~~~~~~

src/javascript.ts:21:8 - error TS2307: Cannot find module '@bufbuild/protoplugin/ecmascript' or its corresponding type declarations.

21 } from "@bufbuild/protoplugin/ecmascript";
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/javascript.ts:28:8 - error TS2307: Cannot find module '@bufbuild/protoplugin/ecmascript' or its corresponding type declarations.

28 } from "@bufbuild/protoplugin/ecmascript";
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/protoc-gen-es-plugin.ts:15:40 - error TS2307: Cannot find module '@bufbuild/protoplugin' or its corresponding type declarations.

15 import { createEcmaScriptPlugin } from "@bufbuild/protoplugin";
                                          ~~~~~~~~~~~~~~~~~~~~~~~

src/typescript.ts:20:8 - error TS2307: Cannot find module '@bufbuild/protobuf' or its corresponding type declarations.

20 } from "@bufbuild/protobuf";
          ~~~~~~~~~~~~~~~~~~~~

src/typescript.ts:21:28 - error TS2307: Cannot find module '@bufbuild/protobuf' or its corresponding type declarations.

21 import { ScalarType } from "@bufbuild/protobuf";
                              ~~~~~~~~~~~~~~~~~~~~

src/typescript.ts:26:8 - error TS2307: Cannot find module '@bufbuild/protoplugin/ecmascript' or its corresponding type declarations.

26 } from "@bufbuild/protoplugin/ecmascript";
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/typescript.ts:33:8 - error TS2307: Cannot find module '@bufbuild/protoplugin/ecmascript' or its corresponding type declarations.

33 } from "@bufbuild/protoplugin/ecmascript";
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/typescript.ts:35:31 - error TS2307: Cannot find module '@bufbuild/protoplugin/ecmascript' or its corresponding type declarations.

35 import { literalString } from "@bufbuild/protoplugin/ecmascript";
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 13 errors in 4 files.

Errors  Files
     3  src/declaration.ts:20
     4  src/javascript.ts:15
     1  src/protoc-gen-es-plugin.ts:15
     5  src/typescript.ts:20
npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @bufbuild/protoc-gen-es@1.3.0 
npm ERR!   at location: /build/source/packages/protoc-gen-es 

ERROR: `npm build` failed

Here are a few things you can try, depending on the error:
1. Make sure your build script (build) exists
  If there is none, set `dontNpmBuild = true`.
2. If the error being thrown is something similar to "error:0308010C:digital envelope routines::unsupported", add `NODE_OPTIONS = "--ope>
  See https://github.com/webpack/webpack/issues/14532 for more information.
```

</details>

I haven't looked much into it, but it seems like some issue with the resolution of npm workspace packages.

**Comment by lilyinstarlight** [comment]
Yay typescript resolution errors... I'll, uh, look into it when i get a chance unless you figure something out before then

I don't actually use typescript, so i'm not sure how it's module resolution works. But if it's in `node_modules` correctly, I would imagine it can find it?

**Comment by felschr** [comment]
In this particular project it seems that each package is built with tsc, so the imports are essentially just a normal dependency (with type declaration files).
It does require that the `build` script is run for all the workspace packages, not just for `protoc-gen-es`.

**Comment by lilyinstarlight** [comment]
The `@bufbuild/*` packages come pre-built from the npm registry. Looking in to the tgz it does already come with cjs builds, esm builds, and type stubs. As for why typescript isn't finding those though... I'm not sure

> It does require that the build script is run for all the workspace packages, not just for protoc-gen-es.

Ah, we don't have a way currently to run multiple build scripts if multiple are needed. I'd need to dive in to be sure, but shouldn't it be running those during `npm rebuild` if they are deps of the workspace package?

**Comment by felschr** [comment]
I kinda assumed upstream would handle that in their npm scripts, but they seem to use a Makefile where they ensure stuff is built in order.
So, if I build those other workspaces in a `preBuild` everything is fine.

**Comment by lilyinstarlight** [comment]
> So, if I build those other workspaces in a preBuild everything is fine.

Wait does that really work? That's cursed 💀

Sounds fine enough as a workaround here for me, though

**Comment by felschr** [comment]
I think npm itself actually doesn't have any logic for also building workspace dependencies as required.

**Comment by felschr** [comment]
Related npm issue, but it's mostly regarding building the entire workspaces: https://github.com/npm/cli/issues/4139

**Comment by felschr** [comment]
So, the build succeeds now, now the only remaining issue is that the packages are out of date and upstream introduced [some other issues](https://github.com/bufbuild/protobuf-es/issues/526#issuecomment-1763470000) to the `package-lock.json` 😅.

**Comment by felschr** [comment]
Result of `nixpkgs-review pr 243432` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>npm-lockfile-fix</li>
    <li>npm-lockfile-fix.dist</li>
    <li>protoc-gen-connect-es</li>
    <li>protoc-gen-es</li>
  </ul>
</details>

**Comment by felschr** [comment]
Updated all packages & fixed `protoc-gen-es`'s remaining `package-lock.json` issues manually.
Everything builds now.

Is it still alright if I add `npm-lockfile-fix` together with this PR?

**Comment by felschr** [comment]
Moved the packages to `pkgs/by-name` now.

**Comment by jtszalay** [comment]
👋 Hi! I'm looking to use the same npm packages via nix. Is there anything that can be done to move this PR along?

**Comment by felschr** [comment]
@jtszalay I'm actually resuming work on the project where I need these dependencies.
I'll update this PR and then I just need someone to review it.

**Comment by felschr** [comment]
I've updated the packages to the latest versions and automated the `npm-lockfile-fix` including the update scripts.

@jtszalay would you be interested in maintaining these packages with me?

**Comment by felschr** [comment]
Result of `nixpkgs-review pr 243432` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>protoc-gen-connect-es</li>
    <li>protoc-gen-es</li>
  </ul>
</details>

**Comment by jtszalay** [comment]
@felschr We'll be using them at my work so, yes, I can do that. 👍

**Comment by felschr** [comment]
@jtszalay Awesome. You'll need to add yourself to the [maintainer list](https://github.com/NixOS/nixpkgs/blob/master/maintainers/maintainer-list.nix) first.

**Comment by jtszalay** [comment]
@felschr I've submitted a PR for that now
https://github.com/NixOS/nixpkgs/pull/321883

**Comment by jtszalay** [comment]
@felschr I started pulling this into my repo but I see the following:

```
> error: collision between `/nix/store/ds3v28pivv80lvwr4xfa39g9hjrar015-protoc-gen-connect-es-1.4.0/lib/node_modules/null/dist/cjs/src/typescript.js' and `/nix/store/yrh9ikqfchzg00dv8j7i2gxirdvylh6x-protoc-gen-es-1.10.0/lib/node_modules/null/dist/cjs/src/typescript.js'
```

**Comment by felschr** [comment]
@jtszalay I can't reproduce that issue. I was able to add both dependencies to a dev shell without issues. If you referenced the packages from this PR before, you might have to garbage collect your nix store.

However, I do get a runtime error when trying to run `protoc-gen-es` (`protoc-gen-connect-es` works):

```console
❯ protoc-gen-es
node:internal/modules/cjs/loader:1146
  throw err;
  ^
                                                                                                                                            
Error: Cannot find module '@bufbuild/protoplugin'
Require stack:
- /nix/store/yrh9ikqfchzg00dv8j7i2gxirdvylh6x-protoc-gen-es-1.10.0/lib/node_modules/null/bin/protoc-gen-es
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/nix/store/yrh9ikqfchzg00dv8j7i2gxirdvylh6x-protoc-gen-es-1.10.0/lib/node_modules/null/bin/protoc-gen-es:3:21)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/nix/store/yrh9ikqfchzg00dv8j7i2gxirdvylh6x-protoc-gen-es-1.10.0/lib/node_modules/null/bin/protoc-gen-es'
  ]
}
```

I'm looking into this.

**Pull request merged**
