### PR TITLE
poppler: 0.64.0 -> 0.65.0

### PR DESCRIPTION
**Pull request by bhipple**
###### Motivation for this change
Upgrading to the latest released version

###### Things done
```
nix build nixpkgs.poppler nixpkgs.cups-filters
```

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bhipple** [comment]
@GrahamcOfBorg build poppler cups-filters

**Comment by bhipple** [comment]
@GrahamcOfBorg build poppler_data

**Comment by matthewbauer** [comment]
Can you rebase off of staging? 0.64.0 is already included.

**Comment by bhipple** [comment]
Sorry for the spam; I messed up my rebase and pulled in a bunch of other commits.  

Thanks for the heads up on the `staging` branch; I have to remember to check that in addition to master before doing upgrades!

**Pull request merged**
