### PR TITLE
vanilla-dmz: init at 0.4.4

### PR DESCRIPTION
**Pull request by cstrahan**
Vanilla DMZ cursor theme

/cc @devhell

### CODE REVIEW

**Comment by devhell** [comment]
Sweeeeeeeeet! :+1:

**Comment by devhell** [comment]
Not sure though if you'd not better split out the commit for the license additions. Just a suggestion.

**Comment by cstrahan** [comment]
> Not sure though if you'd not better split out the commit for the license additions. Just a suggestion.

Done :)

**Comment by devhell** [comment]
Neat. Hope it'll be merged soon. ;-) Thank you!

**Comment by pSub** [comment]
Could you add `meta.description`? Maybe something like "A style neutral scalable cursor theme".

**Comment by devhell** [comment]
@cstrahan ping? :)

**Comment by devhell** [comment]
@cstrahan ping ping? :)

**Comment by garbas** [comment]
@pSub added description before merging
@cstrahan @devhell merged!

**Comment by cstrahan** [comment]
Thanks @pSub  / @garbas!

**Comment by devhell** [comment]
Thanks @cstrahan @pSub @garbas!

**Pull request closed without merging**
