### PR TITLE
pythonPackages.django: 1.9.5 -> 1.9.9 and 1.8.12 -> 1.8.14

### PR DESCRIPTION
**Pull request by kevinmarsh**
###### Motivation for this change

Keeping up to date with latest bug fixes and security patches.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
cc @lancelotsix

**Comment by FRidh** [comment]
I suppose these also need to be backported to stable?

**Comment by lancelotsix** [comment]
I am building and testing them locally.

Could the 2 updates (`django_1_8` and `django_1_9`) be separated into 2 different commits?

**Comment by kevinmarsh** [comment]
@lancelotsix no problem, I split them into separate commits

**Comment by lancelotsix** [comment]
@kevinmarsh Could the commit messages be ` pythonPackages.django_1_8: 1.8.12 -> 1.8.14` and ``pythonPackages.django_1_9: 1.9.5 -> 1.9.9`? `pythonPackages.django` is an alias to django_1_10.

**Comment by lancelotsix** [comment]
tested, merged and back ported to release-16.03.

Thanks for the PR

**Pull request merged**
