### PR TITLE
bind: 9.18.16 -> 9.18.17

### PR DESCRIPTION
**Pull request by trofi**
Changes: https://downloads.isc.org/isc/bind9/9.18.17/doc/arm/html/notes.html#notes-for-bind-9-18-17

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Built on:
- [x] `x86_64-linux`
- [x] `powerpc64le-linux`
- [x] `aarch64-linux` (cross from `x86_64-linux`)
- [x] `mips64el-linux` mixed `n32`/`64` (cross from `x86_64-linux`)

**Comment by amjoseph-nixpkgs** [comment]
@trofi, I think this could go to `master`; do you want to change the branch or should I merge it to `staging`?  Either is okay with me.

**Comment by trofi** [comment]
Good point. Switched to `master`.

**Review by ghost — APPROVED** [review]

**Comment by trofi** [comment]
Result of `nixpkgs-review pr 245921` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>49 packages failed to build:</summary>
  <ul>
    <li>acme-sh</li>
    <li>asn</li>
    <li>autofs5</li>
    <li>bashSnippets</li>
    <li>blueberry</li>
    <li>check-wmiplus</li>
    <li>checkSSLCert</li>
    <li>cinnamon.cinnamon-common</li>
    <li>cinnamon.cinnamon-gsettings-overrides</li>
    <li>cinnamon.cinnamon-screensaver</li>
    <li>cinnamon.cinnamon-session</li>
    <li>cinnamon.nemo</li>
    <li>cinnamon.nemo-fileroller</li>
    <li>cinnamon.nemo-python</li>
    <li>cinnamon.nemo-with-extensions</li>
    <li>cinnamon.nemo.dev</li>
    <li>cinnamon.pix</li>
    <li>cinnamon.warpinator</li>
    <li>cinnamon.xapp</li>
    <li>cinnamon.xapp.dev</li>
    <li>cinnamon.xreader</li>
    <li>cinnamon.xviewer</li>
    <li>dwm-status</li>
    <li>freeipa</li>
    <li>hw-probe</li>
    <li>hypnotix</li>
    <li>inxi</li>
    <li>lightdm-slick-greeter</li>
    <li>monitoring-plugins</li>
    <li>nmapsi4</li>
    <li>python310Packages.django-scim2</li>
    <li>python310Packages.django-scim2.dist</li>
    <li>python310Packages.xapp</li>
    <li>python311Packages.django-scim2</li>
    <li>python311Packages.django-scim2.dist</li>
    <li>python311Packages.xapp</li>
    <li>sssd</li>
    <li>sticky</li>
    <li>tests.testers.nixosTest-example</li>
    <li>tests.testers.runNixOSTest-example</li>
    <li>tests.trivial-builders.references</li>
    <li>testssl</li>
    <li>timeshift</li>
    <li>timeshift-minimal</li>
    <li>timeshift-unwrapped</li>
    <li>twa</li>
    <li>wsl-vpnkit</li>
    <li>xed-editor</li>
    <li>xplayer</li>
  </ul>
</details>
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>bind</li>
    <li>bind.dev</li>
    <li>dig (bind.dnsutils ,dig.dev ,dig.dnsutils ,dig.host ,dig.lib ,dig.man ,dnsutils ,dnsutils.dev ,dnsutils.dnsutils ,dnsutils.host ,dnsutils.lib ,dnsutils.man)</li>
    <li>host (bind.host ,host.dev ,host.dnsutils ,host.host ,host.lib ,host.man)</li>
    <li>bind.lib</li>
    <li>bind.man</li>
    <li>gnome.gnome-nettool</li>
  </ul>
</details>

**Comment by trofi** [comment]
Removed `nix-review` failures, failed for `-ENOSPC`: `filesystem error: cannot rename: No space left on device [/nix/store/.tmp-link-1257869-2021760633] [/nix/store/h2xqpjphk3z3mqyvh4g0j5q0b1zlj2fy-tmpfiles.d/var.conf]`

**Comment by amjoseph-nixpkgs** [comment]
Can you post some of those failures?  I had no trouble building: `acme-sh,hw-probe,inxi,testssl,twa`.

**Comment by trofi** [comment]
Result of `nixpkgs-review pr 245921` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>56 packages built:</summary>
  <ul>
    <li>acme-sh</li>
    <li>asn</li>
    <li>autofs5</li>
    <li>bashSnippets</li>
    <li>bind</li>
    <li>bind.dev</li>
    <li>dig (bind.dnsutils ,dig.dev ,dig.dnsutils ,dig.host ,dig.lib ,dig.man ,dnsutils ,dnsutils.dev ,dnsutils.dnsutils ,dnsutils.host ,dnsutils.lib ,dnsutils.man)</li>
    <li>host (bind.host ,host.dev ,host.dnsutils ,host.host ,host.lib ,host.man)</li>
    <li>bind.lib</li>
    <li>bind.man</li>
    <li>blueberry</li>
    <li>check-wmiplus</li>
    <li>checkSSLCert</li>
    <li>cinnamon.cinnamon-common</li>
    <li>cinnamon.cinnamon-gsettings-overrides</li>
    <li>cinnamon.cinnamon-screensaver</li>
    <li>cinnamon.cinnamon-session</li>
    <li>cinnamon.nemo</li>
    <li>cinnamon.nemo-fileroller</li>
    <li>cinnamon.nemo-python</li>
    <li>cinnamon.nemo-with-extensions</li>
    <li>cinnamon.nemo.dev</li>
    <li>cinnamon.pix</li>
    <li>cinnamon.warpinator</li>
    <li>cinnamon.xapp</li>
    <li>cinnamon.xapp.dev</li>
    <li>cinnamon.xreader</li>
    <li>cinnamon.xviewer</li>
    <li>dwm-status</li>
    <li>freeipa</li>
    <li>gnome.gnome-nettool</li>
    <li>hw-probe</li>
    <li>hypnotix</li>
    <li>inxi</li>
    <li>lightdm-slick-greeter</li>
    <li>monitoring-plugins</li>
    <li>nmapsi4</li>
    <li>python310Packages.django-scim2</li>
    <li>python310Packages.django-scim2.dist</li>
    <li>python310Packages.xapp</li>
    <li>python311Packages.django-scim2</li>
    <li>python311Packages.django-scim2.dist</li>
    <li>python311Packages.xapp</li>
    <li>sssd</li>
    <li>sticky</li>
    <li>tests.testers.nixosTest-example</li>
    <li>tests.testers.runNixOSTest-example</li>
    <li>tests.trivial-builders.references</li>
    <li>testssl</li>
    <li>timeshift</li>
    <li>timeshift-minimal</li>
    <li>timeshift-unwrapped</li>
    <li>twa</li>
    <li>wsl-vpnkit</li>
    <li>xed-editor</li>
    <li>xplayer</li>
  </ul>
</details>

**Pull request merged**
