### PR TITLE
nixos/incus: add support for soft daemon restarts

### PR DESCRIPTION
**Pull request by adamcstephens**
## Description of changes

This is a feature supported out of the box by upstream and allows the
incusd service to be restarted without impacting running
instances. While this does give up a bit of reproducibility, qemu and
lxc for example, there are clear benefits in allowing the host to
apply updates without impacting instances.

Modeled after the zabbly implementation: https://github.com/zabbly/incus/blob/2a67c3e260de5a5d1259ce598d7b4423c49403be/systemd/incus-startup.service

This will now be the default.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by adamcstephens** [comment]
@ofborg test incus

**Comment by adamcstephens** [comment]
I'm unable to reproduce the test failures locally, which is :/ . The below skips the openvswitch test since I didn't want to rebase again and it should be unaffected as it was not touched here.

x86_64
```
/nix/store/qg0hwpwi3iy6q74r4l1h1qh81dhnlrg6-vm-test-run-container-legacy-init
/nix/store/4l3756karl67qr8g7qb5gw7xljgl087q-vm-test-run-container-systemd-init
/nix/store/avcq0cbvcpfy7n51zp6hxd9qrlby16mg-vm-test-run-incusd-options
/nix/store/yjb2a7fifjzhzijb2qlgr8d5nkl86bmp-vm-test-run-lxd-to-incus
/nix/store/xg0apq93sffb9b46is46830yhwcrlmxa-vm-test-run-incus-socket-activated
/nix/store/b3qjrkk2xslnblf6a71shxw8mzkmqc2p-vm-test-run-incus-storage
/nix/store/bgjy7bpf11z97wyb51g5rxrnbhhbq13w-vm-test-run-incus-ui
/nix/store/aaizw0abaw466mmh57r5js0z2g5l57ml-vm-test-run-incus-virtual-machine
```

aarch64
```
/nix/store/9ybf6aa79xwfqma8kn9m6yasgshkdxqa-vm-test-run-container-legacy-init
/nix/store/la495jvcswa9ckzg54k2z8zi7lfshbil-vm-test-run-container-systemd-init
/nix/store/8q21g6mzsrq84zmb0mss93jyy70azb30-vm-test-run-incusd-options
/nix/store/v1vxapxnxp81c8gxhbirz7r5fksxgpfg-vm-test-run-lxd-to-incus
/nix/store/9fagj0c0kysk0q1sw3h5gambk0g0iyzs-vm-test-run-incus-socket-activated
/nix/store/ypjjbcx43f2ccr0if4qysnpbi24rn93g-vm-test-run-incus-storage
/nix/store/11lmaw0zl1xq0w79d1myadcb2qj72kcc-vm-test-run-incus-ui
```

**Comment by Aleksanaa** [comment]
What about `softRestart` or `softReload`?

**Comment by adamcstephens** [comment]
> What about `softRestart` or `softReload`?

Thanks for the suggestion. I've updated it to softDaemonRestart and made it the default.

**Pull request merged**
