### PR TITLE
Added some vim plugins

### PR DESCRIPTION
**Pull request by thufschmitt**
This PR adds some vim plugins.

If necessary, it can be splitted in one commit per plugin, although it would be a bit painful.

### CODE REVIEW

**Comment by jagajaga** [comment]
You did everything by hand?
Also please rename commits' names following our `CONTRIBUTING.md`.

**Comment by regnat** [comment]
> You did everything by hand?

No, of course, I used the vim-addon-vim2nix script.

> Also please rename commits' names following our `CONTRIBUTING.md`.

It this enough, or do I need to split the big commit into one per plugin added ?

**Comment by jagajaga** [comment]
But why indentation in `pkgs/misc/vim-plugins/default.nix` was lost? :(
I mean that:
Was
```nix
  CSApprox = buildVimPluginFrom2Nix { # created by nix#NixDerivation
    name = "CSApprox-2013-07-26";
    src = fetchgit {
      url = "git://github.com/godlygeek/csapprox";
.....
```
Become
```nix
  CSApprox = buildVimPluginFrom2Nix { # created by nix#NixDerivation
  name = "CSApprox-2013-07-26";
  src = fetchgit {
    url = "git://github.com/godlygeek/csapprox";
.....
```

**Comment by regnat** [comment]
I must have let my editor indent it, I'll fix it in a minute.
Btw, I got a problem with vim2nix, the vimshell plugin gets two "dependencies" fields, which need to be removed by hand.

**Comment by jagajaga** [comment]
@regnat I know that problem. No time to fix :(

**Comment by jagajaga** [comment]
Thank you!

**Pull request merged**
