### PR TITLE
ultrastar-manager: deprecate phases

### PR DESCRIPTION
**Pull request by Stunkymonkey**
###### Motivation for this change
#28910

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Profpatsch** [comment]
@SuperSandro2000 was this tested?

**Comment by SuperSandro2000** [comment]
It built and there are files installed in the output.

**Comment by Profpatsch** [comment]
I’m a bit worried that if we introduce the `checkupPhase` and never run the binary, that we miss if the binary is stripped the wrong way. e.g. this is a Turbopascal binary, I don’t know if our default `checkupPhase` works for those.

**Comment by Profpatsch** [comment]
*`fixupPhase`

**Comment by Profpatsch** [comment]
I ran it, looks like it still works.

**Comment by Stunkymonkey** [comment]
i only tested the compilation. thanks for testing

**Pull request merged**
