### PR TITLE
update NixOS fdisk instructions based on my flow (18.03)

### PR DESCRIPTION
**Pull request by KiaraGrouwstra**
The existing installation instructions did not quite match what I ran into on a clean install (NixOS 18.03) -- this PR alters the instructions to reflect my experience.

### CODE REVIEW

**Comment by grahamc** [comment]
I'm not sure why these are an improvement. My understanding is your clean install was overtop an existing set of partitions, and not actually to a clean disk. Am I misunderstanding?

**Comment by tycho01** [comment]
Hi, thanks for asking.

It's not that I wanted to preserve partitions -- I was wiping/repartitioning my SSD as part of this install.
I can't tell what was the reason the original instructions gave me issues -- they somehow did, then I documented my steps for myself / others with similar issues (?).
I can't tell which of these only occurred for me and which could be more general. If not useful, feel free to close.

Changes included:
- partition table type MBR -> GPT: helped me solve an error `File system "/boot" is not on a GPT partition table`.
- `fdisk` -> `gdisk` -- iirc this was needed for the partition table difference below.
- add button presses for some missing prompts, though potentially tweaked toward `gdisk`.
- boot partition size: helped me solve error #34508.
- vfat signature warnings: ignore if applicable.

**Comment by afrepues** [comment]
Upon start, `gdisk` will attempt to convert any existing from MBR or BSD disklabels into a GPT. Then using the `o` function you can clean out that GPT to start anew.

**Comment by tycho01** [comment]
I'll close as it doesn't appear clear whether this would be of use.

**Pull request closed without merging**
