### PR TITLE
nixos/gnome3: add sound-theme-freedesktop

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
I've noticed a similar issue in Pantheon, without this
sound theme installed there's no system sounds.
I believe it's because the gnome theme and the pantheon
theme inherit this one.

###### Things done

Running on my machine currently. Its effects may not be seen right away. i.e, on this particular machine
I had flip a few dconf switches. I'd want to check if the sound theme is working in a VM, but I'm not sure
how to get sounds from a NixOS qemu machine.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
How do you test this? GNOME does not seem to have any sound theme. In g-c-c there is a Alert sound choice but it does not seem to make any sound when changed. And it only seems to make a symlink from `~/.local/share/sounds/__custom/bell-window-system.ogg` to a file in g-c-c package.

**Comment by worldofpeace** [comment]
> How do you test this? GNOME does not seem to have any sound theme. In g-c-c there is a Alert sound choice but it does not seem to make any sound when changed. And it only seems to make a symlink from `~/.local/share/sounds/__custom/bell-window-system.ogg` to a file in g-c-c package.

It was pretty weird, I actually checked and the gnome theme doesn't inherit from the freedesktop one. I'll test it again somehow, but for sure before I did this there wasn't any sound theme activated, and trying to activate it in g-c-c wouldn't work.

**Comment by worldofpeace** [comment]
Hmm, I don't know how to have sound in qemu...

**Comment by jtojnar** [comment]
Hmm, I had system sounds muted so that alert sound was not being played when I changed it. Now I also hear a sound when changing volume level.

**Comment by jtojnar** [comment]
Yup, seems to be the case:

```ShellSession
$ cat ~/.local/share/sounds/__custom/index.theme
[Sound Theme]
Name=Custom
Inherits=freedesktop
Directories=.
```

That should be enough justification to install it from the gnome module.

In the past, I just added it locally (https://github.com/NixOS/nixpkgs/commit/2be9f022012a499c941e3a044a70f90388cd946d) but it might make sense to handle sound themes just like icon themes. On the other hand, the freedesktop theme is probably the only one anyone will ever use, so the replaceability argument is not so strong.

In either case, GNOME Shell also [relies on some sound theme being present](https://gitlab.gnome.org/GNOME/gnome-shell/blob/8cb819926ad587b7643876a8fbdd30bb3d9fba61/js/ui/status/volume.js#L128).

I would go with installing it in gnome module with a comment about the custom alert theme. Adding it to `xdg.sounds` module on top of that probably would not do any harm.

**Comment by worldofpeace** [comment]
> Yup, seems to be the case:
> 
> ```
> $ cat ~/.local/share/sounds/__custom/index.theme
> [Sound Theme]
> Name=Custom
> Inherits=freedesktop
> Directories=.
> ```
> 
> That should be enough justification to install it from the gnome module.
> 
> In the past, I just added it locally ([2be9f02](https://github.com/NixOS/nixpkgs/commit/2be9f022012a499c941e3a044a70f90388cd946d)) but it might make sense to handle sound themes just like icon themes. On the other hand, the freedesktop theme is probably the only one anyone will ever use, so the replaceability argument is not so strong.
> 
> In either case, GNOME Shell also [relies on some sound theme being present](https://gitlab.gnome.org/GNOME/gnome-shell/blob/8cb819926ad587b7643876a8fbdd30bb3d9fba61/js/ui/status/volume.js#L128).
> 
> I would go with installing it in gnome module with a comment about the custom alert theme. Adding it to `xdg.sounds` module on top of that probably would not do any harm.

I believe I've supplied these changes. Though I would still like a way to test it in qemu for a backport.

**Comment by jtojnar** [comment]
Adding the following seems to be sufficient to make the sound work.

```nix
virtualisation.qemu.options = [ "-soundhw hda" ];
```

Though for some reason, when QEMU is run, it starts acting as a monitor and it is mixed with the output. But Spotify triggers that too, so maybe it is irrelevant.

**Comment by jtojnar** [comment]
You can also abuse `QEMU_NET_OPTS` environment variable:

```ShellSession
$ env QEMU_NET_OPTS="hostfwd=tcp::2222-:22,hostfwd=tcp::8888-:80 -soundhw help" ./result/bin/run-*-vm
Valid sound card names (comma separated):
sb16        Creative Sound Blaster 16
es1370      ENSONIQ AudioPCI ES1370
ac97        Intel 82801AA AC97 Audio
adlib       Yamaha YM3812 (OPL2)
gus         Gravis Ultrasound GF1
cs4231a     CS4231A
hda         Intel HD Audio
pcspk       PC speaker

-soundhw all will enable all of the above
```

**Comment by worldofpeace** [comment]
> Adding the following seems to be sufficient to make the sound work.
> 
> ```nix
> virtualisation.qemu.options = [ "-soundhw hda" ];
> ```
> 
> Though for some reason, when QEMU is run, it starts acting as a monitor and it is mixed with the output. But Spotify triggers that too, so maybe it is irrelevant.

Ok, it does seem to have system sounds now from themes. However it's pretty strange that system sounds start off as muted, I believe you noticed this also.

What I did to test was:
1. build vm with gnome3 config
2. opened sound pane in g-c-c
3. made sure system sounds were all the way up
4. played with volume slider in the shell

Without this change, even if you set a sound theme you won't get the alert sound (drip).

@jtojnar Similar findings?

**Comment by worldofpeace** [comment]
> You can also abuse `QEMU_NET_OPTS` environment variable:
> 
> ```
> $ env QEMU_NET_OPTS="hostfwd=tcp::2222-:22,hostfwd=tcp::8888-:80 -soundhw help" ./result/bin/run-*-vm
> Valid sound card names (comma separated):
> sb16        Creative Sound Blaster 16
> es1370      ENSONIQ AudioPCI ES1370
> ac97        Intel 82801AA AC97 Audio
> adlib       Yamaha YM3812 (OPL2)
> gus         Gravis Ultrasound GF1
> cs4231a     CS4231A
> hda         Intel HD Audio
> pcspk       PC speaker
> 
> -soundhw all will enable all of the above
> ```

Thanks, I was able to test with nixos option :+1: 
(happened to also have intel audio)

**Comment by worldofpeace** [comment]
backported a22b01890024decaa76a918846dc4f173f6d9660

**Comment by timokau** [comment]
My terminal bell suddenly made a sound due to this change, which was a bit annoying to track down (I don't even directly use gnome). Not saying that there's anything wrong with it, since I've apparently been relying on a bug (https://xkcd.com/1172/). Now I just need to figure out how to disable the sounds properly.

I'm not sure the backport is a good idea though. Its a functional change, and maybe not just strictly a fix.

**Comment by worldofpeace** [comment]
@timokau I only backported the fix to GNOME https://github.com/NixOS/nixpkgs/commit/a22b01890024decaa76a918846dc4f173f6d9660. The OS wide change to include the freedesktop sound theme, where on conventional systems would have always been there (and I think libcanberra even needs it), wasn't backported for the reason you mentioned. Simply put, I fixed being able to set an alert sound in GNOME, and with gnome-control-center.

**Comment by timokau** [comment]
Ah okay, that's good then. Discovery is still not optimal (I had to bisect it, which is even harder since my system configuration didn't build on some of the relevant revs), but I'm not sure how to improve that.

**Pull request merged**
