### PR TITLE
tor-browser: 13.0.8 -> 13.0.9, mullvad-browser: 13.0.7 -> 13.0.9

### PR DESCRIPTION
**Pull request by felschr**
## Description of changes

Updates Tor Browser & Mullvad Browser and also fixes the desktop file for Mullvad Browser.

https://blog.torproject.org/new-release-tor-browser-1309/
https://github.com/mullvad/mullvad-browser/releases/tag/13.0.9

> This version includes important [security updates](https://www.mozilla.org/en-US/security/advisories/) to Firefox.
>
> This release updates Firefox to 115.7.0esr and Snowflake to 2.8.1. It also includes various bug fixes (see changelog for details).

Supersedes #282586

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by felschr** [comment]
Result of `nixpkgs-review pr 283289` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>mullvad-browser</li>
    <li>tor-browser</li>
  </ul>
</details>

**Comment by felschr** [comment]
I've still got the same issue that I've mentioned in #282586.
Running the browsers from my local branch fails with a segfault. This PR doesn't introduce the error, it was already broken before. Nonetheless I'm looking into it.

**Review by panicgh — APPROVED** [review]
Web browsing, audio, and video work in both applications.

Result of `nixpkgs-review pr 283289` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>mullvad-browser</li>
    <li>tor-browser</li>
  </ul>
</details>

**Comment by felschr** [comment]
> Web browsing, audio, and video work in both applications.

Good to know that it works for you. Then the segfault is just some issue specific to my setup.
I'm currently running a bisect to investigate further, but I'd say this PR can already be merged.

**Review by SuperSandro2000 — APPROVED** [review]

**Pull request merged**
