### PR TITLE
factorio-demo: init at 0.14.23

### PR DESCRIPTION
**Pull request by layus**

### CODE REVIEW

**Review by fpletz — APPROVED** [review]

**Comment by elitak** [comment]
For me, the demo tarball downloaded is gzip compressed, so renaming it to .xz causes the unpack phase to fail. You'll need to provide a modified `name` attr to the fetch instead of inheriting the common one.

Also maybe fix the inconsistent spacing around the `fetchurl`/`authenticatedFetch` (right-justify the verbs) and maybe rename `versions` to `releases`.

**Comment by layus** [comment]
@elitak How can it fail for you and not for me ? This is scarier than the issue itself.

**Comment by elitak** [comment]
@layus Run `file /nix/store/*factorio-demo*tar.[gx]z` and see if the contents match the extensions. I can't really offer an explanation for this behavior on the master branch unless you rebased from an older one, since I think the `tar xaf` behavior in stdenv changed to `xz -d | tar x` at some point in recent history. Regardless, the extensions should match the contents of any files written to the store, especially when used as `src` attributes.

**Comment by layus** [comment]
@elitak It wan indeed the rebase. Factorio uses xz for 0.15.x apparently, and the demo is still stuck at 0.14.x. Also fixed the other nitpicks.

**Pull request merged**
