### PR TITLE
xorg.libX11: 1.7.0 -> 1.7.1

### PR DESCRIPTION
**Pull request by TredwellGit**
###### Motivation for this change
https://lists.x.org/archives/xorg-announce/2021-May/003089.html
https://lists.x.org/archives/xorg-announce/2021-May/003088.html

###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TredwellGit** [comment]
@ofborg test sway i3wm

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 123622` at fa8d1b33 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>868 packages marked as broken and skipped:</summary>
  <ul>
    <li>OVMF-CSM</li>
    <li>adoptopenjdk-hotspot-bin-13</li>
    <li>adoptopenjdk-hotspot-bin-14</li>
    <li>adoptopenjdk-jre-hotspot-bin-13</li>
    <li>adoptopenjdk-jre-hotspot-bin-14</li>
    <li>agdaPackages.iowa-stdlib</li>
    <li>aldor</li>
    <li>alliance</li>
    <li>ams-lv2</li>
    <li>amuleDaemon</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>14971 packages skipped due to time constraints:</summary>
  <ul>
    <li>AusweisApp2</li>
    <li>CHOWTapeModel</li>
    <li>DisnixWebService</li>
    <li>EBTKS</li>
    <li>EmptyEpsilon</li>
    <li>Fabric (python38Packages.Fabric)</li>
    <li>MIDIVisualizer</li>
    <li>MMA</li>
    <li>OVMF</li>
    <li>OVMF-secureBoot</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>54 packages built successfully:</summary>
  <ul>
    <li>asciidoctor</li>
    <li>at-spi2-atk</li>
    <li>at-spi2-core</li>
    <li>atk (gnome.atk ,gnome2.atk)</li>
    <li>avahi</li>
    <li>cairo (gnome2.cairo)</li>
    <li>cups</li>
    <li>dbus</li>
    <li>dconf (gnome.dconf ,xfce.dconf)</li>
    <li>epoxy</li>
    <li>gdk-pixbuf</li>
    <li>gobject-introspection (gnome.gobject-introspection)</li>
    <li>libgudev (gnome.libgudev)</li>
    <li>libsoup (gnome.libsoup)</li>
    <li>tracker (gnome.tracker)</li>
    <li>pango (gnome2.pango)</li>
    <li>harfbuzz</li>
    <li>json-glib</li>
    <li>lasem</li>
    <li>libglvnd</li>
    <li>libinput</li>
    <li>libqrtr-glib</li>
    <li>libva</li>
    <li>libvdpau</li>
    <li>libwacom</li>
    <li>libxkbcommon (libxkbcommon_8)</li>
    <li>maiko</li>
    <li>python38Packages.pycairo</li>
    <li>python38Packages.pygobject3</li>
    <li>runningx</li>
    <li>xkeyboard_config (xorg.xkeyboardconfig)</li>
    <li>xlibsWrapper (xorg.xlibsWrapper)</li>
    <li>xorg.libX11</li>
    <li>xorg.libXScrnSaver</li>
    <li>xorg.libXcomposite</li>
    <li>xorg.libXcursor</li>
    <li>xorg.libXdamage</li>
    <li>xorg.libXext</li>
    <li>xorg.libXfixes</li>
    <li>xorg.libXft</li>
    <li>xorg.libXi</li>
    <li>xorg.libXinerama</li>
    <li>xorg.libXmu</li>
    <li>xorg.libXpm</li>
    <li>xorg.libXrandr</li>
    <li>xorg.libXrender</li>
    <li>xorg.libXres</li>
    <li>xorg.libXt</li>
    <li>xorg.libXtst</li>
    <li>xorg.libXv</li>
    <li>xorg.libXvMC</li>
    <li>xorg.libXxf86vm</li>
    <li>xorg.xauth</li>
    <li>yabasic</li>
  </ul>
</details>

**Comment by risicle** [comment]
`xorg.libX11` and `xorg.twm` build happily, macos 10.15

**Comment by vcunat** [comment]
Hehe, tricked OfBorg by merging too fast.

I'm keeping the backporting label, as 21.05 currently has no branch.  @jonringer: perhaps we'd better create `staging-21.05` branch already? I could even add a jobset, but I mainly wanted to just use git instead of using labels to defer the work for later.

**Comment by jonringer** [comment]
> Hehe, tricked OfBorg by merging too fast.
> 
> I'm keeping the backporting label, as 21.05 currently has no branch. @jonringer: perhaps we'd better create `staging-21.05` branch already? I could even add a jobset, but I mainly wanted to just use git instead of using labels to defer the work for later.

yea, we can create another staging-21.05. I wanted to have hydra in a better state than the 200k builds queued  that we had around a week ago.

**Pull request merged**
