### PR TITLE
doc: Make callout marks & prompts unselectable

### PR DESCRIPTION
**Pull request by jtojnar**
As [noticed](https://github.com/NixOS/rfcs/pull/64#issuecomment-574168483) by @davidak, this was actually broken.

This will make copying examples easier.

### CODE REVIEW

**Review by davidak — APPROVED** [review]
Thanks for the fast fix! :sparkles: 

It works and code looks sane. (but i'm no CSS expert)

Screenshot from 2020-01-14 16-43-42

**Comment by jtojnar** [comment]
Also noticed that there are spaces before callouts but the default stylesheet does not mark the `<span>`s produced by `<co>` so I did not figure out a nice way of doing that. [Asked](https://github.com/docbook/xslt10-stylesheets/issues/184) upstream.

**Review by samueldr — APPROVED** [review]

**Comment by grahamc** [comment]
@jtojnar can you backport?

**Comment by jtojnar** [comment]
Cherry-picked in 273f15c08e524dd96f2907a4b40bfb5c1eae8798 and d1265562b4c3cca8922f680ee504fa6bd875cae6.

**Pull request merged**
