### PR TITLE
solo5: install ocaml bindings for all targets that are enabled 

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Motivation for this change

Reuse the configuration generated by configure.sh to dynamically install
the bindings for all enabled targets. A bit of a hack grepping for the
respective lines in the Makeconf which incidentally also parse as shell.

Alternative would be to check for the target libs.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
@ofborg build solo5

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 116685` at 1512d267 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li><a href="https://gist.github.com/4e3c3cddb10800ac937f164db22e6e13">solo5</a></li></li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`checkPhase` should probably contain `runHook preCheck` and `runHook postCheck`.

Near pkgs/os-specific/solo5/default.nix:56:3:
```
   |
56 |   checkPhase = ''
   |   ^
```
</li>
  </ul>
</details>

**Review by ghost — APPROVED** [review]

**Comment by ehmry** [comment]
@sternenseemann If you didn't know already, there are planned changes to Solo5 build system: https://github.com/Solo5/solo5/pull/494

**Comment by sternenseemann** [comment]
Thanks for the link :) I sort of figured already as `ocaml-freestanding` is also about to redo their build system with cross-compilation support (they currently have a set of shell scripts eerily similar to `solo5`'s), going to be interesting.

**Pull request merged**
