### PR TITLE
Generate new R packages [help needed]

### PR DESCRIPTION
**Pull request by langston-barrett**
###### Motivation for this change

Updates are good!

I'm having some trouble:

```
development/r-modules > nix-build test-evaluation.nix --dry-run --show-trace
error: while evaluating the attribute ‘nativeBuildInputs’ of the derivation ‘R-3.2.3-wrapper’ at /archroot/home/siddharthist/code/nixpkgs/pkgs/development/r-modules/wrapper.nix:4:3:
while evaluating ‘optionals’ at /archroot/home/siddharthist/code/nixpkgs/lib/lists.nix:185:21, called from /archroot/home/siddharthist/code/nixpkgs/pkgs/stdenv/generic/default.nix:212:16:
while evaluating ‘chooseDevOutputs’ at /archroot/home/siddharthist/code/nixpkgs/lib/attrsets.nix:463:22, called from /archroot/home/siddharthist/code/nixpkgs/pkgs/stdenv/generic/default.nix:169:22:
while evaluating ‘isDerivation’ at /archroot/home/siddharthist/code/nixpkgs/lib/attrsets.nix:295:18, called from undefined position:
attribute ‘TextoMineR’ missing, at /archroot/home/siddharthist/code/nixpkgs/pkgs/development/r-modules/default.nix:200:18
```

However, if I don't make those changes to `pkgs/development/r-modules/default.nix`, then I get this error:

```
development/r-modules > nix-build test-evaluation.nix --dry-run --show-trace
error: while evaluating the attribute ‘nativeBuildInputs’ of the derivation ‘R-3.2.3-wrapper’ at /archroot/home/siddharthist/code/nixpkgs/pkgs/development/r-modules/wrapper.nix:4:3:
while evaluating ‘optionals’ at /archroot/home/siddharthist/code/nixpkgs/lib/lists.nix:185:21, called from /archroot/home/siddharthist/code/nixpkgs/pkgs/stdenv/generic/default.nix:212:16:
while evaluating ‘chooseDevOutputs’ at /archroot/home/siddharthist/code/nixpkgs/lib/attrsets.nix:463:22, called from /archroot/home/siddharthist/code/nixpkgs/pkgs/stdenv/generic/default.nix:169:22:
while evaluating ‘isDerivation’ at /archroot/home/siddharthist/code/nixpkgs/lib/attrsets.nix:295:18, called from undefined position:
attribute ‘Goslate’ missing, at /archroot/home/siddharthist/code/nixpkgs/pkgs/development/r-modules/default.nix:200:18
```

Any ideas what's going on? 

For context, both of those packages are now missing from CRAN
- https://cran.r-project.org/web/packages/Goslate/
- https://cran.r-project.org/web/packages/TextoMineR/
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by domenkozar** [comment]
cc @peti

**Comment by peti** [comment]
@siddharthist, the file `pkgs/development/r-modules/default.nix` lists `TextoMineR` as a broken package and tries to mark it so in the package set -- which results in an evaluation error because that package no longer existst. If you remove the build from the list of "broken" overrides, then the error will go away.

Also, I've started a build of the new package set at http://hydra.cryp.to/jobset/nixpkgs/r-updates and this is bound to uncover many other evaluation errors (and build errors) that may need addressing.

**Comment by siddharthist** [comment]
@peti If you're on top of that, should I just close this PR?

**Comment by peti** [comment]
I'm not on top of that. I'll be able to help you fix those issues, but I can't do it all by myself.

**Comment by jefdaj** [comment]
I got partway through developing a script that automatically updates the
nix expressions. It works, but requires 1) a lot of time to compile
everything locally, 2) manual checking afterward, and 3) probably some
fixes to jive with the current generate-r-packages.R since I haven't merged
it in a few months. It's here though if you want to work on it:

https://gist.github.com/anonymous/a2987f3a0bc10d8f07425fce50f6ef03

I don't have time to maintain it right now but could troubleshoot a bit.
Jeff

**Comment by jefdaj** [comment]
Oh, if you comment out main and source it you can update just the packages
you care about plus their dependencies. That should save a lot of time.
Jeff

**Comment by siddharthist** [comment]
@peti How can I help?

**Comment by peti** [comment]
@siddharthist, you seem to be confused about the responsibilities here. This is *your* PR, and I may be able to help *you* getting it into a state where we can merge it. I'll be happy to review your changes and provide guidance, if necessary. Right now, the most pressing issue is the bunch of evaluation errors that occur after your update. Are you willing to look into that?

**Comment by siddharthist** [comment]
@peti Yes, sorry for the lack of clarity, I'm asking how to do that.

**Comment by peti** [comment]
My explanation at https://github.com/NixOS/nixpkgs/pull/19532#issuecomment-253827977 did not help at all convey an idea how to fix those evaluation errors?

**Comment by siddharthist** [comment]
@peti Yes, I understood that one. I was asking more about when you said "this is bound to uncover many other evaluation errors (and build errors) that may need addressing." Sorry about my lack of knowledge, I'm just beginning to understand our R infrastructure.

**Comment by peti** [comment]
Have you looked at the link I posted?

**Comment by siddharthist** [comment]
@peti I did, yes! Are the things under "Evaluation Errors" the stuff that needs to be fixed? Is there a way to filter out packages that are marked as broken (as that seems to be most of them)?

**Pull request closed without merging**
