### PR TITLE
staging-18.03 merge

### PR DESCRIPTION
**Pull request by domenkozar**
https://hydra.nixos.org/jobset/nixpkgs/staging-18.03#

- e2fsprogs bump
- btrfs-progs bump

### CODE REVIEW

**Comment by shlevy** [comment]
https://hydra.nixos.org/eval/1444573

**Comment by shlevy** [comment]
@domenkozar This causes a bunch of breakage, including btrfsprogs.

**Comment by vcunat** [comment]
We should probably wait also for https://github.com/NixOS/systemd/pull/18 (or similar fix)

**Comment by domenkozar** [comment]
@vcunat makes sense - I think there are no regressions otherwise in staging.

**Pull request merged**
