### PR TITLE
julia_19: 1.9.0-beta2 -> 1.9.0-beta4

### PR DESCRIPTION
**Pull request by joshniemela**
###### Description of changes

Bumped `julia_19` from 1.9.0-beta2 to 1.9.0-beta4 and added "joshniemela" to maintainers. Continuation of #215818.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NickCao** [comment]
diff LGTM. But you should further split `julia_19: add joshniemela to maintainers` into `maintainers: add joshniemela` and `julia_19: add joshniemela to maintainers`.

**Comment by joshniemela** [comment]
> 

How do i split it?

**Comment by NickCao** [comment]
There are some excellent tutorials out there: https://stackoverflow.com/a/6217314

**Comment by joshniemela** [comment]
Done

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by NickCao** [comment]
Result of `nixpkgs-review pr 216803` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>julia_19</li>
  </ul>
</details>

And the binary runs.

**Pull request merged**
