### PR TITLE
rhash: 1.4.1 -> 1.4.2

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 1.4.2

Change log: https://github.com/rhash/RHash/releases/tag/v1.4.2

- Ran `nixpkgs-fmt`

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Hmmm...

```bash
16468 packages updated:
````

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 136282` at 7b9291a4 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>276 packages marked as broken and skipped:</summary>
  <ul>
    <li>Literate</li>
    <li>OVMF-CSM</li>
    <li>acl2</li>
    <li>adoptopenjdk-hotspot-bin-13</li>
    <li>adoptopenjdk-hotspot-bin-14</li>
    <li>adoptopenjdk-jre-hotspot-bin-13</li>
    <li>adoptopenjdk-jre-hotspot-bin-14</li>
    <li>airtame</li>
    <li>ams-lv2</li>
    <li>apfelgrid</li>
    <li>applgrid</li>
    <li>artyFX</li>
    <li>asymptote</li>
    <li>autotrace</li>
    <li>avy</li>
    <li>beignet</li>
    <li>betaflight-configurator</li>
    <li>blastem</li>
    <li>bless</li>
    <li>bootiso</li>
    <li>bud</li>
    <li>cargo-rr</li>
    <li>cassandra_2_1</li>
    <li>cassandra_2_2</li>
    <li>clang-sierraHack</li>
    <li>clang-sierraHack-stdenv</li>
    <li>clickhouse</li>
    <li>clmagma</li>
    <li>collectd</li>
    <li>collectd-data</li>
    <li>colmapWithCuda</li>
    <li>cura_stable</li>
    <li>dcraw</li>
    <li>deeptools</li>
    <li>devede</li>
    <li>displaycal</li>
    <li>dtools</li>
    <li>dvd-slideshow</li>
    <li>easyeffects</li>
    <li>echidna</li>
    <li>electron_3</li>
    <li>electron_4</li>
    <li>electron_5</li>
    <li>embree</li>
    <li>embree2</li>
    <li>emuflight-configurator</li>
    <li>eterm</li>
    <li>evilvte</li>
    <li>exodus</li>
    <li>facter</li>
    <li>ffmpeg_2</li>
    <li>ffmpeg_2_8</li>
    <li>ffmpeg_3</li>
    <li>ffmpeg_3_4</li>
    <li>forge</li>
    <li>gb-backup</li>
    <li>git-dit</li>
    <li>gitin</li>
    <li>globalplatform</li>
    <li>globulation2</li>
    <li>gmtk</li>
    <li>gnome_mplayer</li>
    <li>gnuradio3_7</li>
    <li>gnuradio3_7Packages.ais</li>
    <li>gnuradio3_7Packages.gnuradio</li>
    <li>gnuradio3_7Packages.gsm</li>
    <li>gnuradio3_7Packages.limesdr</li>
    <li>gnuradio3_7Packages.nacl</li>
    <li>gnuradio3_7Packages.osmosdr</li>
    <li>gnuradio3_7Packages.rds</li>
    <li>gogoclient</li>
    <li>gopro</li>
    <li>gppcscconnectionplugin</li>
    <li>gpshell</li>
    <li>gpu-burn</li>
    <li>grass</li>
    <li>green-pdfviewer</li>
    <li>gtkd</li>
    <li>gtmess</li>
    <li>hplipWithPlugin_3_16_11</li>
    <li>hplip_3_16_11</li>
    <li>idris2</li>
    <li>impressive</li>
    <li>intecture-cli</li>
    <li>intel-compute-runtime</li>
    <li>intel-media-driver</li>
    <li>invoice2data</li>
    <li>isabelle</li>
    <li>jboss</li>
    <li>jfbpdf</li>
    <li>jfbview</li>
    <li>julia</li>
    <li>julia-lts</li>
    <li>julia_10</li>
    <li>k2pdfopt</li>
    <li>k3d</li>
    <li>keyfinder</li>
    <li>libav</li>
    <li>libav_0_8</li>
    <li>libav_11</li>
    <li>libav_12</li>
    <li>libgroove</li>
    <li>libnats-c</li>
    <li>librealsenseWithCuda</li>
    <li>libvirt_5_9_0</li>
    <li>libvmi</li>
    <li>linuxPackages_hardkernel_4_14.bcc</li>
    <li>linuxPackages_hardkernel_4_14.openrazer</li>
    <li>linuxPackages_hardkernel_4_14.xpadneo</li>
    <li>linuxPackages_hardkernel_4_14.zfs</li>
    <li>linuxPackages_hardkernel_4_14.zfsStable</li>
    <li>linuxPackages_hardkernel_4_14.zfsUnstable</li>
    <li>linuxPackages_hardkernel_latest.bcc</li>
    <li>linuxPackages_hardkernel_latest.openrazer</li>
    <li>linuxPackages_hardkernel_latest.xpadneo</li>
    <li>linuxPackages_hardkernel_latest.zfs</li>
    <li>linuxPackages_hardkernel_latest.zfsStable</li>
    <li>linuxPackages_hardkernel_latest.zfsUnstable</li>
    <li>linuxPackages_testing_bcachefs.bcc</li>
    <li>linuxPackages_testing_bcachefs.oci-seccomp-bpf-hook</li>
    <li>linuxPackages_testing_bcachefs.openrazer</li>
    <li>linuxPackages_testing_bcachefs.xpadneo</li>
    <li>linuxPackages_testing_bcachefs.zfs</li>
    <li>linuxPackages_testing_bcachefs.zfsStable</li>
    <li>linuxPackages_testing_bcachefs.zfsUnstable</li>
    <li>loxodo</li>
    <li>lucenepp</li>
    <li>luxcorerender</li>
    <li>magma</li>
    <li>mame</li>
    <li>meo</li>
    <li>metamorphose2</li>
    <li>mpich</li>
    <li>mrxvt</li>
    <li>mupdf_1_17</li>
    <li>mvapich</li>
    <li>natron</li>
    <li>nixui</li>
    <li>nrpl</li>
    <li>nvtop</li>
    <li>obs-studio-plugins.obs-ndi</li>
    <li>ocropus</li>
    <li>odpdown</li>
    <li>onedrive</li>
    <li>openems</li>
    <li>openimagedenoise</li>
    <li>openimagedenoise_1_2_x</li>
    <li>openrw</li>
    <li>openssh_gssapi</li>
    <li>openssh_hpn</li>
    <li>opentsdb</li>
    <li>ovftool</li>
    <li>pcsxr</li>
    <li>pdfdiff</li>
    <li>pgadmin</li>
    <li>photoflow</li>
    <li>pig</li>
    <li>plover.stable</li>
    <li>poedit</li>
    <li>polymake</li>
    <li>pony-stable</li>
    <li>processing</li>
    <li>pulp</li>
    <li>pulseeffects-legacy</li>
    <li>python38Packages.HTSeq</li>
    <li>python38Packages.caffe</li>
    <li>python38Packages.cnvkit</li>
    <li>python38Packages.dask-gateway</li>
    <li>python38Packages.dask-jobqueue</li>
    <li>python38Packages.dask-ml</li>
    <li>python38Packages.dask-mpi</li>
    <li>python38Packages.dask-xgboost</li>
    <li>python38Packages.datashader</li>
    <li>python38Packages.fipy</li>
    <li>python38Packages.foundationdb51</li>
    <li>python38Packages.foundationdb52</li>
    <li>python38Packages.foundationdb60</li>
    <li>python38Packages.foundationdb61</li>
    <li>python38Packages.foxdot</li>
    <li>python38Packages.ignite</li>
    <li>python38Packages.pycuda</li>
    <li>python38Packages.pygmt</li>
    <li>python38Packages.pynvml</li>
    <li>python38Packages.pyrealsense2WithCuda</li>
    <li>python38Packages.pyscf</li>
    <li>python38Packages.python-csxcad</li>
    <li>python38Packages.python-openems</li>
    <li>python38Packages.pythonnet</li>
    <li>python38Packages.pytorchWithCuda</li>
    <li>python38Packages.spacy</li>
    <li>python38Packages.spacy-transformers</li>
    <li>python38Packages.streamz</li>
    <li>python38Packages.stumpy</li>
    <li>python38Packages.tensorflowWithCuda</li>
    <li>python38Packages.textacy</li>
    <li>python38Packages.thinc</li>
    <li>python39Packages.HTSeq</li>
    <li>python39Packages.caffe</li>
    <li>python39Packages.cnvkit</li>
    <li>python39Packages.dask-gateway</li>
    <li>python39Packages.dask-jobqueue</li>
    <li>python39Packages.dask-ml</li>
    <li>python39Packages.dask-mpi</li>
    <li>python39Packages.dask-xgboost</li>
    <li>python39Packages.datashader</li>
    <li>python39Packages.fipy</li>
    <li>python39Packages.foundationdb51</li>
    <li>python39Packages.foundationdb52</li>
    <li>python39Packages.foundationdb60</li>
    <li>python39Packages.foundationdb61</li>
    <li>python39Packages.foxdot</li>
    <li>python39Packages.ignite</li>
    <li>python39Packages.pycuda</li>
    <li>python39Packages.pygmt</li>
    <li>python39Packages.pynvml</li>
    <li>python39Packages.pyrealsense2WithCuda</li>
    <li>python39Packages.pyscf</li>
    <li>python39Packages.python-csxcad</li>
    <li>python39Packages.python-openems</li>
    <li>python39Packages.pythonnet</li>
    <li>python39Packages.pytorchWithCuda</li>
    <li>python39Packages.spacy</li>
    <li>python39Packages.spacy-transformers</li>
    <li>python39Packages.streamz</li>
    <li>python39Packages.stumpy</li>
    <li>python39Packages.tensorflowWithCuda</li>
    <li>python39Packages.textacy</li>
    <li>python39Packages.thinc</li>
    <li>qemu_xen</li>
    <li>qemu_xen-light</li>
    <li>qemu_xen_4_10</li>
    <li>qemu_xen_4_10-light</li>
    <li>qlandkartegt</li>
    <li>qubes-core-vchan-xen</li>
    <li>rainbowstream</li>
    <li>ring-daemon</li>
    <li>rocm-opencl-icd</li>
    <li>rocm-opencl-runtime</li>
    <li>root5</li>
    <li>rund</li>
    <li>scribus</li>
    <li>secretscanner</li>
    <li>shellinabox</li>
    <li>shotgun</li>
    <li>siril</li>
    <li>sonic-pi</li>
    <li>spark</li>
    <li>split2flac</li>
    <li>spotifywm</li>
    <li>spring</li>
    <li>springLobby</li>
    <li>stepmania</li>
    <li>swftools</li>
    <li>termplay</li>
    <li>tilix</li>
    <li>tlaps</li>
    <li>torchat</li>
    <li>truecrack-cuda</li>
    <li>truvari</li>
    <li>twinkle</li>
    <li>unetbootin</li>
    <li>unicap</li>
    <li>vbam</li>
    <li>vcs</li>
    <li>volatility</li>
    <li>vp</li>
    <li>wimlib</li>
    <li>winpdb</li>
    <li>woeusb</li>
    <li>xfitter</li>
    <li>xorg.libAppleWM</li>
    <li>xpdf</li>
    <li>xsw</li>
    <li>yosys-bluespec</li>
    <li>zandronum</li>
    <li>zgv</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/c12b592230e6cabd839179cbdf24a844">lean2</a></li>
  </ul>
</details>
<details>
  <summary>20298 packages skipped due to time constraints:</summary>
  <ul>
    <li>AusweisApp2</li>
    <li>CHOWTapeModel</li>
    <li>DisnixWebService</li>
    <li>EBTKS</li>
    <li>EmptyEpsilon</li>
    <li>Fabric (python39Packages.Fabric)</li>
    <li>LAStools</li>
    <li>LASzip</li>
    <li>LASzip2</li>
    <li>MACS2</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>52 packages built successfully:</summary>
  <ul>
    <li>atk (gnome.atk ,gnome2.atk)</li>
    <li>brotli</li>
    <li>cairo (gnome2.cairo)</li>
    <li>cglm</li>
    <li>cmake</li>
    <li>cryptsetup</li>
    <li>curl</li>
    <li>dkh</li>
    <li>eigen</li>
    <li>fontconfig</li>
    <li>fontforge (fontforge-fonttools ,python39Packages.fontforge)</li>
    <li>gd</li>
    <li>gdk-pixbuf (gnome.gdk-pixbuf)</li>
    <li>gobject-introspection (gnome.gobject-introspection)</li>
    <li>pango (gnome2.pango)</li>
    <li>graphite2</li>
    <li>harfbuzz</li>
    <li>ilmbase</li>
    <li>imath</li>
    <li>json-glib</li>
    <li>json_c</li>
    <li>lcms2</li>
    <li>libccd</li>
    <li>libdevil-nox</li>
    <li>libfido2</li>
    <li>libipt</li>
    <li>libjpeg (libjpeg_turbo)</li>
    <li>libmicrohttpd (libmicrohttpd_0_9_71)</li>
    <li>libmng</li>
    <li>libmysqlclient (libmysqlclient_3_1 ,mariadb-connector-c ,mariadb-connector-c_3_1)</li>
    <li>libstemmer</li>
    <li>libtiff</li>
    <li>libvori</li>
    <li>libwebp</li>
    <li>libzip</li>
    <li>luarocks (luaPackages.luarocks)</li>
    <li>luajitPackages.luarocks</li>
    <li>metis</li>
    <li>octomap</li>
    <li>openexr (openexr_2)</li>
    <li>openssh</li>
    <li>pcmsolver</li>
    <li>poppler_data</li>
    <li>python39Packages.pycairo</li>
    <li>rhash</li>
    <li>soxr</li>
    <li>usrsctp</li>
    <li>vulkan-headers</li>
    <li>woff2</li>
    <li>xlibsWrapper (xorg.xlibsWrapper)</li>
    <li>xorg.libXft</li>
    <li>zeromq (zeromq4)</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by risicle** [comment]
@ofborg eval

**Comment by fabaff** [comment]
Superseding #134526

**Comment by SuperSandro2000** [comment]
http://rhash.sourceforge.net/changelog.php
```
RHash v1.4.2 Wed Jul 14 2021
print 'Nothing to verify' when verifying a hash file without a message digest
significantly improve file reading performance on Linux/Unix
Bugfix: fix verification of some hash files containing spaces in file paths
count unparsed lines of a hash file as errors
print line numbers of unparsed lines of a hash file
```

**Comment by vcunat** [comment]
This doesn't build on x86_64-darwin, breaking veery many packages transitively.  Log: https://hydra.nixos.org/log/kwqzl1axr1f08v91ld9344xa3jbdpbx3-rhash-1.4.2.drv
It's in `staging-next` branch now #146259, potentially delaying the 21.11 stabilization.

**Comment by vcunat** [comment]
Upstream has a patch: https://github.com/rhash/RHash/issues/169#issuecomment-881918809

Either way, I think we'd best get at least some verification from someone with an x86_64-darwin machine.

**Comment by r-burns** [comment]
Patch works for me! Opened PR here: https://github.com/NixOS/nixpkgs/pull/146572

**Pull request merged**
