### PR TITLE
remove networkmanager098

### PR DESCRIPTION
**Pull request by Atemu**
It causes Steam to not find its local installation on my machine somehow and we
don't need it AFAICT

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Still used in `pkgs/build-support/appimage/default.nix`, so I have to wonder if we can get rid of this 7y old version altgoether now.

**Comment by Atemu** [comment]
If you tested a good amount of AppImages (I don't use those), that's fine with me.

**Comment by mweinelt** [comment]
https://github.com/AppImage/pkg2appimage/blob/master/excludelist doesn't mention network manager anymore, so I think dropping it should be fine.

**Comment by mweinelt** [comment]
I'm using none of those apps either.

Result of `nixpkgs-review pr 162904` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>appimage-run-tests</li>
  </ul>
</details>
<details>
  <summary>69 packages built:</summary>
  <ul>
    <li>Sylk</li>
    <li>altair</li>
    <li>anki-bin</li>
    <li>anytype</li>
    <li>appimage-run</li>
    <li>apple-music-electron</li>
    <li>beekeeper-studio</li>
    <li>betterdiscord-installer</li>
    <li>bloomrpc</li>
    <li>bottles</li>
    <li>buttercup-desktop</li>
    <li>chrysalis</li>
    <li>cozy-drive</li>
    <li>crypto-org-wallet</li>
    <li>devdocs-desktop</li>
    <li>electron-mail</li>
    <li>electronplayer</li>
    <li>firefly-desktop</li>
    <li>flexoptix-app</li>
    <li>fspy</li>
    <li>heroic</li>
    <li>irccloud</li>
    <li>itch</li>
    <li>itch-setup</li>
    <li>joplin-desktop</li>
    <li>keeweb</li>
    <li>kodiPackages.steam-launcher</li>
    <li>lbry</li>
    <li>ledger-live-desktop</li>
    <li>lens</li>
    <li>losslesscut-bin</li>
    <li>lunar-client</li>
    <li>lutris</li>
    <li>marktext</li>
    <li>mathpix-snipping-tool</li>
    <li>minigalaxy</li>
    <li>mobilecoin-wallet</li>
    <li>molotov</li>
    <li>mycrypto</li>
    <li>neo4j-desktop</li>
    <li>notable</li>
    <li>notion-app-enhanced</li>
    <li>nuclear</li>
    <li>octant-desktop</li>
    <li>p3x-onenote</li>
    <li>playonlinux</li>
    <li>plexamp</li>
    <li>protontricks</li>
    <li>radicle-upstream</li>
    <li>rambox-pro</li>
    <li>saleae-logic-2</li>
    <li>session-desktop-appimage</li>
    <li>ssb-patchwork</li>
    <li>standardnotes</li>
    <li>station</li>
    <li>steam</li>
    <li>steam-run</li>
    <li>steam-tui</li>
    <li>steamcmd</li>
    <li>timeular</li>
    <li>trezor-suite</li>
    <li>tusk</li>
    <li>unityhub</li>
    <li>via</li>
    <li>vial</li>
    <li>wootility</li>
    <li>ytmdesktop</li>
    <li>zettlr</li>
    <li>zulip</li>
  </ul>
</details>

**Pull request merged**
