### PR TITLE
yash: 2.53 -> 2.54

### PR DESCRIPTION
**Pull request by qbit**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kranzes** [comment]
Result of `nixpkgs-review pr 218264` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>getoptions</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>yash</li>
  </ul>
</details>

**Comment by qbit** [comment]
No clue why `getoptions` failed. Yash builds fine for me with `nix-build -A yash`.

**Review by matrss — COMMENTED** [review]
##### Reviewed points

- [x] package name fits guidelines
- [x] package version fits guidelines
- [x] package build on x86_64-linux
- [x] executables tested on x86_64-linux
- [ ] all depending packages build

##### Possible improvements

##### Comments
I have to retract my previous comment, it looks like this yash version indeed introduces a change that breaks getoptions test suite. I previously assumed that the issue was the failing shellcheck addressed in #230869.

Specifically it looks like this change is the issue here (from yash's changelog):
```
  =  The shell now requires a corresponding external executable to
     exist in $PATH when running a built-in that works like a standard
     external utility even when the POSIXly-correct mode is inactive.
     Such built-ins are now categorized as "substitutive" built-ins.
```

shellspec in getoptions' test suite complains about missing `[` and `echo` commands in yash.
The weird thing is that `[` and `echo` are actually available in the PATH of the check phase and should therefore be available as built-ins from yash. I am not sure how to fix this issue.

Edit: filed an issue with shellspec, since I think the problem lies there: https://github.com/shellspec/shellspec/issues/299

**Review by drupol — APPROVED** [review]
LGTM

**Pull request merged**
