### PR TITLE
git-quick-stats: init at 2.0.8

### PR DESCRIPTION
**Pull request by kmein**
###### Motivation for this change
This package was missing from nixpkgs while for example homebrew has it.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by davidak** [comment]
@kmein looks like a useful tool. thanks for the PR!

It seems the lyricwikia commit slipped in. Can you remove it from the branch?

**Comment by vcunat** [comment]
Hmm, do the colors look OK for you?  When I run just `git-quick-stats`, in my konsole the menu items aren't visible at all, in xterm they're barely visible but without their numbers so not really usable either.

**Comment by vcunat** [comment]
Oh, let's try darwin build, BTW.
@GrahamcOfBorg build git-quick-stats

**Comment by kmein** [comment]
For me (urxvt, dark scheme) the colours work perfectly. Maybe the author just assumed that people use a dark colorscheme?

**Comment by vcunat** [comment]
Right, it seems so.  I posted upstream: https://github.com/arzzen/git-quick-stats/pull/65#issuecomment-500208725

**Review by vcunat — APPROVED** [review]

**Pull request merged**
