### PR TITLE
Jetbrains Idea-Ultimate 2016.3.4 -> 2017.1

### PR DESCRIPTION
**Pull request by rydnr**
###### Motivation for this change

Support for latest Idea-Ultimate (2017.1).

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
What is our policy for backports of IDEs major revisions?

**Comment by rydnr** [comment]
I should've requested the pull against master, not the release-17.03 tag.

**Comment by NeQuissimus** [comment]
@Mic92 We generally bring those into stable when an old version stops working properly (to some degree). With Atom, for example, you can't install certain plugins anymore if you are too far behind...

**Comment by Mic92** [comment]
@rydnr we already have it in master. But it is probably also ok to push it to master.

**Comment by NeQuissimus** [comment]
@Mic92 You mean 17.03? We can just cherry-pick the commit rather than using this PR. Probably easier if we ever need to merge larger chunks from one branch to the other...

**Comment by Mic92** [comment]
@NeQuissimus this is probably not possible, because we have recently moved `idea` to `jetbrains`.

**Comment by NeQuissimus** [comment]
@Mic92 Oh okay... Did not know that... The merge is probably fine then

**Pull request merged**
