### PR TITLE
rustc: 1.4.0 -> 1.5.0

### PR DESCRIPTION
**Pull request by globin**

### CODE REVIEW

**Comment by globin** [comment]
This is failing on our hydra, please let me investigate.

**Comment by globin** [comment]
1.5.0 needs to use the bundled LVM for now until llvm 3.7.1 is released see rust-lang/rust#30304, llvm 3.7.1 is already tagged but not announced and no tarball releases available.

**Comment by globin** [comment]
Seems to be building correctly (https://hydra.mayflower.de/build/2292)

**Comment by the-kenny** [comment]
There is a backported patch available for LLVM somewhere. I mentioned this in IRC and people suggested we should patch our mainline 3.7.0 LLVM until 3.7.1 is released (as long as the patch is official, of course)

**Comment by globin** [comment]
If someone wants to patch llvm and is faster than me: http://llvm.org/viewvc/llvm-project?view=revision&revision=247191

**Comment by the-kenny** [comment]
I'm working on all the Rust PRs right now. Will try this :)

**Comment by globin** [comment]
Cheers :+1:

**Comment by the-kenny** [comment]
Compiling our mainline LLVM with the patch now. If this fails I'll merge this PR as is, using the bundled LLVM.

**Comment by the-kenny** [comment]
Sorry, I got sidetracked by some people believing an ancient story about a girl who got pregnant while being a virgin. Can you believe that?

Other than that: Works fine, merged as c11f6c9

**Pull request closed without merging**
