### PR TITLE
Vector: 0.12.1 -> 0.12.2

### PR DESCRIPTION
**Pull request by happysalada**
###### Motivation for this change

just a version update.

I'm pleased to say that It built on my darwin hardware with no errors!

I ran the nixpkgs-fmt on the first commit, I hope that's not a problem

@thoughtpolice in case you have time

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Please name the format commit ``vector: nixpkgs-fmt``

**Review by SuperSandro2000 — APPROVED** [review]
diff LGTM

**Comment by happysalada** [comment]
@SuperSandro2000 done. Let me know if it works for you!

**Pull request merged**
