### PR TITLE
Chromium: Update and build fixes.

### PR DESCRIPTION
**Pull request by ambrop72**
I have tested the stable version (43), it builds and runs, but not others.

Changes included:
- Update versions.
- Use gyp package not gyp_svn1977.
- Remove icu from buildInputs, since this causes a build error due to inferference with use_system_icu=false.
- Remove the hack that inserts the absolute path into gyp files, and pass `--depth .` to gyp. This resolves the `third_party/angle` gyp error.
- Do a normal copy of the source code not a symlink copy. This resolves some link error where the symlinks interfere with relative paths (seems like because gyp resolves symlinks first). Note, this used to be worked around with the absolute path insertion hack.
- Change the bucketURL in update.nix to https (for more secure updates).

### CODE REVIEW

**Comment by aszlig** [comment]
Building all channels and VM test at https://headcounter.org/hydra/jobset/aszlig/chromium-pending, thanks a bunch!

**Comment by aszlig** [comment]
Fixed the `nix_plugin_paths` patch in my [pu-chromium branch](https://github.com/ambrop72/nixpkgs/compare/chromium-update...aszlig:pu-chromium).

**Comment by aszlig** [comment]
Okay, `stable` and `beta` are building now, only `dev` bails out with [an error](https://headcounter.org/hydra/build/702174/nixlog/2).

**Comment by eduarrrd** [comment]
Sorry, but why do we prefer bundled icu over system icu?

**Comment by aszlig** [comment]
@eduarrrd: Thanks for pointing that out, it should be possible to build with system ICU now, so I'm switching to it after the [current evaluation](https://headcounter.org/hydra/eval/169134) has finished building.

**Comment by aszlig** [comment]
@eduarrrd: Trying with system ICU: https://headcounter.org/hydra/eval/169215

**Comment by aszlig** [comment]
@eduarrrd: Okay, `beta` and `dev` channels still fail, so going with bundled again, also so far it has been breaking the build on every ICU update.

**Pull request merged**
