### PR TITLE
teams-for-linux: 1.0.45 -> 1.0.53

### LINKED ISSUE #215593: teams-for-linux: JavaScript TypeError "properties of undefined (reading 'play')"
### Describe the bug
Audio notifications in `teams-for-linux` do not play and a pop-up appears with a JavaScript error. The error raised is quoted below:
```
Uncaught Exception:
TypeError: Cannot read properties of undefined (reading 'play')
```
A screenshot of the error is also provided which references the `nix` store path pointing to `index.js`.

### Steps To Reproduce
1. Start `teams-for-linux`.
2. Get a notification from either a direct message, or the start of a meeting.
3. Popup with error appears.

### Expected behavior
Notifications play an audio tone and do not create a Javascript error.

### Screenshots
image

### Additional context
- NixOS configuration using flakes.
- `teams-for-linux` version is 1.0.45.
- Other notifications in my system work fine such as Slack and Firefox.
- Running Hyprland, Gnome is also installed. Issue is not dependent on desktop environment as it occurs in both Gnome and Hyprland.
- Using `pipewire` for audio. Config below:
```
  hardware.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    config.pipewire = {
      "context.properties" = {
      "link.max-buffers" = 16; # version < 3 clients can't handle more than this
      "log.level" = 2; # https://docs.pipewire.org/page_daemon.html
      };
    };
  };
```

### Notify maintainers
@muscaln 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.9, NixOS, 23.05 (Stoat), 23.05.20230202.a100acd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/n14283gcxp1l2qj0h53lngw4rl4y9xkd-source`
```

### PR DESCRIPTION
**Pull request by lilyinstarlight**
###### Description of changes

The biggest changes are having macOS support and having a multi-account command-line flag. Other release notes at https://github.com/ismaelmartinez/teams-for-linux/releases

I added myself as maintainer and am letting OfBorg test to see if it builds on macOS or not (and I'll mark it broken if not)

Versions in-between these were waiting on #214062 but this version works without it again (so some of the drive-by changes were originally related to getting it to work with that)

I also tossed in a fix for notification sounds

Fixes #215593

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lilyinstarlight** [comment]
I'm just marking darwin broken for now unless someone else figures something out or I get access to the Darwin community builder (winterqt/darwin-build-box#12) and can debug

**Review by adamcstephens — APPROVED** [review]
Result of `nixpkgs-review pr 219393` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>teams-for-linux</li>
  </ul>
</details>

---

Result of `nixpkgs-review pr 219393` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>teams-for-linux</li>
  </ul>
</details>

**Review by adamcstephens — APPROVED** [review]
Tested on x86_64-linux and was able to log in and use Teams.

---

Result of `nixpkgs-review pr 219393` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>teams-for-linux</li>
  </ul>
</details>


---

Result of `nixpkgs-review pr 219393` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>teams-for-linux</li>
  </ul>
</details>

**Comment by lilyinstarlight** [comment]
Fixes a known bug (two people verified on the issue thread) and has an approval already, merging

**Pull request merged**
