### PR TITLE
python312Packages.llama-cpp-python: init at 0.3.1

### PR DESCRIPTION
**Pull request by kirillrdy**
unlike previous attempt https://github.com/NixOS/nixpkgs/pull/268712

this uses bundled version of llama-cpp, also tested CUDA support

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by hoh** [comment]
Thanks for the work !

Can you explain the motivations behind switching to the bundled version of llama-cpp ? 

The package looks much simpler than the previous version that used patches on llama-cpp, but lacks support for other back-ends (OpenCL, ROCm).

**Comment by alexvorobiev** [comment]
Trying to build with Cuda results in the version error:
```
llama-cpp-python>   /nix/store/slx40i35cmd7kb3wvdqzckfww8smcy6s-cuda_nvcc-12.2.140/include/crt/host_config.h:143:2:
llama-cpp-python>   error: #error -- unsupported GNU version! gcc versions later than 12 are
llama-cpp-python>   not supported! The nvcc flag '-allow-unsupported-compiler' can be used to
llama-cpp-python>   override this version check; however, using an unsupported host compiler
llama-cpp-python>   may cause compilation failure or incorrect run time execution.  Use at your
llama-cpp-python>   own risk.
```

**Comment by alexvorobiev** [comment]
> Thanks for the work !
> 
> Can you explain the motivations behind switching to the bundled version of llama-cpp ?
> 
> The package looks much simpler than the previous version that used patches on llama-cpp, but lacks support for other back-ends (OpenCL, ROCm).

I am not the author but the code refers to the llama.cpp's examples subdirectory which is not included in nixpkg.llama-cpp. For instance https://github.com/abetlen/llama-cpp-python/blob/7403e002b8e033c0a34e93fba2b311e2118487fe/CMakeLists.txt#L110.

**Comment by kirillrdy** [comment]
@hoh 

> Can you explain the motivations behind switching to the bundled version of llama-cpp ?

llama-cpp and llama-cpp-python often get out of sync, so using llama-cpp from nixpkgs requires either breaking lama-cpp-python or not updating llama-cpp

@alexvorobiev CUDA support builds without any overrides, do you change default cuda in your overlays ?

**Comment by kirillrdy** [comment]
> > @alexvorobiev CUDA support builds without any overrides, do you change default cuda in your overlays ?
> 
> I have to use CUDA 12.2 for now, could that be the issue?

yes, it seems to only build with 12.4  ( which is default in nixpkgs )

**Comment by kirillrdy** [comment]
@alexvorobiev I've fixed cuda build, tested with 12_3, 12_2, 12_1, 12_0, 11_8 ( stopped here )

**Comment by alexvorobiev** [comment]
> @alexvorobiev I've fixed cuda build, tested with 12_3, 12_2, 12_1, 12_0, 11_8 ( stopped here )

Thank you!

**Comment by MatthewCroughan** [comment]
Unsure if there are any outstanding issues, but best to merge instead of leaving the PR for a long time, so have merged and will try to use it and identify any outstanding issues.

**Pull request merged**
