### PR TITLE
gnome3.gjs: 1.52.3 -> 1.53.3

### PR DESCRIPTION
**Pull request by dpc**
###### Motivation for this change

I was told that the infamous gnome memory leak was finally fixed upstream:
    
https://bugs.launchpad.net/gnome-shell/+bug/1672297/comments/93

I am running this version on my work Ubuntu and it is a great improvement.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jtojnar** [comment]
Please note that this is an unstable version.

Also 1.53.4 has been released:

https://gitlab.gnome.org/GNOME/gjs/blob/1.53.4/NEWS

**Comment by xeji** [comment]
@jtojnar so should we wait for a stable version?

**Comment by jtojnar** [comment]
I would just wait, gjs 1.53.4 is outdated already and the version after that is not backwards compatible. With GNOME 3.30 releasing in September, it is not a very long wait.

**Comment by xeji** [comment]
ok, marking this as WIP for now.

**Comment by jtojnar** [comment]
Closing in favor of https://github.com/NixOS/nixpkgs/pull/45950

**Pull request closed without merging**
