### PR TITLE
pixie: refactor to allow macOS build

### PR DESCRIPTION
**Pull request by alekcz**
###### Motivation for this change
- Adding macOS support for pixie (pixie has been support on macOS for quite a while already)
- Updating the name as discussed on issue 445 (https://github.com/pixie-lang/pixie/issues/455)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
@GrahamcOfBorg build pixie

**Comment by alekcz** [comment]
@joachifm any chance I could ask Graham for a new build?

**Comment by joachifm** [comment]
@GrahamcOfBorg build pixie

**Comment by alekcz** [comment]
@joachifm aarch64-linux is not on platforms list but Graham keeps trying to build on it. I'm not sure how to fix the build error. Any ideas?

**Comment by joachifm** [comment]
@alekcz I'd ignore it for now

**Comment by bendlas** [comment]
Great! Thanks for taking that on. I don't have a mac, so I'll have to go with your assessment, but one question: Why did you remove `i686-linux` as a platform? Isn't it supported by pixie?

**Comment by alekcz** [comment]
@bendlas on pixie 0.1 yes. But with support i686 is being phased out in general, we'd be digging a hole. Also things like libuv and pypy will get harder and harder to support on i686.

https://www.archlinux.org/news/the-end-of-i686-support/

**Comment by bendlas** [comment]
@alekcz have you had any actual breakage due to i686 being supported? If it's not related to OSX support, I'd ask you to submit a separate PR for that.

**Comment by alekcz** [comment]
@bendlas done

**Comment by bendlas** [comment]
OK.

Strictly speaking, the executable name change is out of scope for an OSX PR, as well,
but I'll accept it as part of this, because it is based on upstream consensus (and because pixie is not exactly a high-stakes package, right now).
However, please keep this idea of separating concerns in mind, when filing further pull requests, as it makes reviewer's lifes a lot easier.

Thanks and welcome to NixOS!

**Comment by anka-213** [comment]
This change made [`dust`](https://github.com/NixOS/nixpkgs/blob/92a047a6c4d46a222e9c323ea85882d0a7a13af8/pkgs/development/interpreters/pixie/dust.nix) stop working, since that has a reference to the path `bin/pixie-vm`. It should be a simple 1-line fix here: https://github.com/NixOS/nixpkgs/blob/92a047a6c4d46a222e9c323ea85882d0a7a13af8/pkgs/development/interpreters/pixie/dust.nix#L14

----

I'm not really interested in this package, I just noticed it when accidentally installing this while trying to install [the other package named "dust"](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/misc/dust/default.nix).

**Pull request closed without merging**
