### PR TITLE
treewide: src cleanup

### PR DESCRIPTION
**Pull request by prusnak**
###### Motivation for this change

* replaced `repo = "${pname}";` with `repo = pname;`
* replaced `rev = "${version}";` with `rev = version;`
* used `fetchFromGitHub` where possible

I tested that none of the changes causes rebuilds meaning my changes were pure refactors.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
doing something like:
```
rev = "refs/tags/v${version}"; into rev = "v${version}";
```
is tricky, as a repository could both have a branch, and a tag with the same name. I would move those changes to a different commit.

The other changes (e.g. `repo = "${pname}"; with repo = pname;`) are not very controversial

**Comment by omasanori** [comment]
> doing something like:
> ```
> rev = "refs/tags/v${version}"; into rev = "v${version}";
> ```
> is tricky, as a repository could both have a branch and a tag with the same name. I would move those changes to a different PR.

How about adding `tag` to fetchers, migrating to it where appropriate, and revising `rev` to accept revision-like strings after a sufficient migration period? It would be better if we could save Nix writers from such situations IMHO. It will be larger and longer-term task which seems a drawback though.

**Comment by prusnak** [comment]
Removed controversial changes in  041bc79

**Review by jonringer — APPROVED** [review]
LGTM

```
https://github.com/NixOS/nixpkgs/pull/102396
48 packages built:
crackxls ddate eolie gx gx-go libmkv lumo matrix-synapse mirage-im mopidy-iris mopidy-local mopidy-mopify mopidy-mpd mopidy-mpris mopidy-musicbox-webclient mopidy-somafm mopidy-soundcloud mopidy-spotify-tunigo mopidy-tunein mopidy-youtube orion pantalaimon python27Packages.hawkauthlib python27Packages.pyfxa python27Packages.pykka python27Packages.tokenlib python27Packages.unpaddedbase64 python37Packages.hawkauthlib python37Packages.matrix-nio python37Packages.pyfxa python37Packages.pykka python37Packages.pyramid_hawkauth python37Packages.signedjson python37Packages.tokenlib python37Packages.unpaddedbase64 python38Packages.hawkauthlib python38Packages.matrix-nio python38Packages.pyfxa python38Packages.pykka python38Packages.pyramid_hawkauth python38Packages.signedjson python38Packages.tokenlib python38Packages.unpaddedbase64 retdec retdec-full tbe weechatScripts.weechat-matrix xwinmosaic
```

**Pull request merged**
