### PR TITLE
 syncthing 0.11.25 -> 0.12.2 

### PR DESCRIPTION
**Pull request by jgillich**
Please review aka I have no idea what I'm doing but it works for me.

The Go bug is only fixed in master, 1.5.2 should happen soon. I'm not 100% sure if that should be included already.

### CODE REVIEW

**Comment by jgillich** [comment]
@the-kenny I'm super confused, at first it thought `licenses.gplv2` was a typo, now it says `‘gplv2’ missing`...

**Comment by pSub** [comment]
@jgillich `licenses.gplv2` was a typo but it is already fixed in master.

I am not using syncthing, but there was some discussion on the mailing list that version 0.12 has some incompatible changes and that we want to keep 0.11 and 0.12 for some time to allow a smooth transition/migration. for the users.

**Comment by jgillich** [comment]
@psub Yeah 0.12 isn't backwards compatible, having both would be good. But how is that usually done, do I just copy the package definition under a different name?

**Comment by domenkozar** [comment]
cc @ctheune

**Comment by devhell** [comment]
Might be good to come to a conclusion rather soon on this. Syncthing discovery has been failing on and off since 0.12 has been released. Also, currently NixOS stable is still running a rather old version of the 0.11 series.

**Comment by jgillich** [comment]
The syncthing android app is already on 0.12 with no real way to downgrade, I feel like we should just upgrade to 0.12.

**Comment by devhell** [comment]
Agreed. Considering that on "normal" systems, it would move automatically to 0.12 anyway, I fail to see any benefit in keeping a 0.11 branch around.

**Comment by ctheune** [comment]
Absolutely +1 from me. Keeping a 0.11 around would be helpful for people who do not need Android or such and are stuck with 0.11 within their team for some reason. But having the default 0.12 around is more important.

**Comment by ctheune** [comment]
Oh and: did someone check that stuff like the syncthing-protocol do not have to be updated?

**Comment by lfam** [comment]
You should keep both sides of an incompatible  update in the repos
because people run Syncthing on a variety of platforms that are updated
independently, at different times. Each user can only update their
cluster to the new version once all their platforms have support.

On Wed, Nov 18, 2015, at 16:40, devhell wrote:
> Considering that syncthing normally auto-updates, I'd like to see an
> actual example of people needing 0.11. Also, discovery service seems
> to be getting flaky lately.


> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/NixOS/nixpkgs/pull/10952#issuecomment-157873555

**Comment by devhell** [comment]
@lfam I agree in principle. Personally I'm still not convinced, but that's a different story. I'm sure the maintainers will decide wisely on what we should do, however, I think it would be good if we'd come to a conclusion soon.

**Comment by ctheune** [comment]
The best example of syncthing _not_ updating automatically is this discussion. :) If your team runs on Nix then, well, there you go. I do that on my Mac and I love that this doesn't auto-update. This means our team coordinates those updates. Voila.

**Comment by ctheune** [comment]
Lets keep both, please.

**Comment by ctheune** [comment]
Aaactually. I just noticed #10431 - if discovery is really broken for 0.11 and 0.11 really is completely useless by now. However, this would be weird. I thought if you run something like an introducer then you're independent of _their_ upstream infrastructure. I'm trying to verify that.

**Comment by jgillich** [comment]
If anyone wants to make a new PR with both, go ahead. I am really just getting started with Nix so I don't know how to do that properly. I'm also not sure if `syncthing-protocol` needs to be updated, there are no tags in their repo.

**Comment by lfam** [comment]
As I said upthread, it makes sense to keep both versions because some platforms (such as NixOS) are slow to support the new incompatible releases. But a week ago, it was not only NixOS.

Of course, one of the strengths of Nix is the ease with which you can have multiple versions of the software in the package tree and move between them without breaking the whole system. So some people will not have any trouble maintaining a private branch of nixpkgs, but some will.

Regarding 0.11 and discovery, it is NOT broken. You can run your own discovery server and it works quite well. That's kinda the point ;) Also, you can use Syncthing without any discovery servers if you configure your nodes with static addresses or DNS.

**Comment by lfam** [comment]
I think the best thing to do would be to contribute a Nix package expression upstream with instructions for installing from it "out of tree". I'm not sure how to do that on Nix but on Guix, it's just an environment variable:
```
$ GUIX_PACKAGE_PATH=~/my/private/pkgs guix install syncthing
```
That would make it super easy for Nix users to run whichever version they need.

**Comment by ctheune** [comment]
Ok, so as long 0.11 is working (I wasn't sure about the own discovery servers) I stick with the plan to keep both. I'll try to amend the pull request later today.

**Comment by devhell** [comment]
Ah, I wasn't aware of own discovery servers. In which case, sure let's keep both versions.

**Comment by ctheune** [comment]
Interesting. I'm trying to figure out the dependency to those factored-out go packages. Interestingly in the syncthing repository there is lib/protocol in addition to the separate protocol repository. I might be oblivous to some detail about go, but it looks like syncthing packages its own version and the protocol dependency here is superfluous ... 

I'm currently waiting for the OS X userland to rebuilt (no binary packages yet) so I can try out my changes. I added v11 and v12 packages and made the service configurable. I guess this will take a while.

**Comment by ctheune** [comment]
Here is another bit:
https://github.com/syncthing/relaysrv/tree/master/Godeps

Even the relaysrv explicitly states go dependencies based on the original repository.

**Comment by ctheune** [comment]
Aha! They're using git subtree. It looks like this way they keep the versioning in sync. I guess we should be careful to not accidentally use incorrect versions here. Interestingly the relayserver also accesses the go dependency through the subtree. I think we should do the same.

**Comment by ctheune** [comment]
Sorry for the noise - and then we also find that 0.11 uses the external repository whereas 0.12 uses the subtree. This is getting a bit hairy. I'll try to clean this up.

**Comment by AudriusButkevicius** [comment]
We've moved protocol into the syncthing repo as it was painful to maintain. Regardless, dependencies were always vendored, regardless which version you are looking at, so no dependency on other repos. The only thing that has changed was wether the protocol dependency vendored from external repo (and then lives locally), or if it just lives locally.

**Comment by ctheune** [comment]
Oh, thanks @AudriusButkevicius for letting us know. 

This isn't true for the dependencies mentioned in the Godeps file, or is it?

**Comment by AudriusButkevicius** [comment]
All dependencies are vendored using godeps, other dependencies are no longer dependencies as they live in the same repo.

**Comment by wkennington** [comment]
We dont use build.sh and are not using the syncthing vendored deps.

**Comment by AudriusButkevicius** [comment]
Are you pointing GOPATH at Godeps?
If not, why? I wouldn't be surprised if it will fail to build at some point someone changes some API we are using.

If you are pointing it at godeps, you shouldn't have any issues regardless of the version

**Comment by wkennington** [comment]
We are not, but we are testing to make sure that doesnt happen.

**Comment by AudriusButkevicius** [comment]
The fact that it builds, runs and passes the tests doesn't mean its tested. There are many platform specific hacks all over the place, potentially ones which were removed in later versions of the package we are depending on, so I'd still like to know why. By the end of the day, users of your package end up on our forums/issue tracker looking for support when it breaks, so using unsupported deps just increases the support workload we have, and increases the complexity of actually building it.

**Comment by ctheune** [comment]
The point is that we can build using identical deps, but we need to provide them through the nix mechanism for stuff to work reliably. 

The current way this is done is a maintenance issue as many go utilities may depend on various versions. We need to fix that.

**Comment by calmh** [comment]
Hello. The stuff under Godeps is indeed vendored deps; build against those if you like, or some other source or version of them as you like. :) We obviously test with what we bundle, hence the bundling.

The stuff in lib, including lib/protocol, is not vendored but part of the repo. So this is the "primary" source for anything in there. There is an external repo for the protocol for historical reasons, which I was reminded to update now, but it's a mirror of syncthing/lib/protocol, not the other way around.

**Comment by ctheune** [comment]
I spend some time going through this.

I thought extracting the application packages back into the pkgs/applications tree would be reasonable. But then I stumbled over the recursive inheritance of the syncthing-lib package for the relay server. 

I'm not out of time for this today. Stuff has been more fun in the past for me. Spending this time for restructuring for a "simple" version update, well ...

**Comment by AudriusButkevicius** [comment]
Whats the cycle you found?

**Comment by ctheune** [comment]
@AudriusButkevicius not a cycle in syncthing's dependencies but the way that the sub-packages are referenced within the Nix code ... -_-

**Comment by ctheune** [comment]
I made a new PR #11329 with 0.11 and 0.12 in parallel and updated dependencies. I'd suggest to use that.

**Pull request closed without merging**
