### PR TITLE
wine: stable, unstable; upgrade to 1.8

### PR DESCRIPTION
**Pull request by bendlas**
cc @abbradar 
- [x] update wine stable to 1.8
- [x] wait for wine-staging to release a 1.8 version

### CODE REVIEW

**Comment by bendlas** [comment]
hold off a bit on this, wine 1.8 has just been released

**Comment by bendlas** [comment]
Good to merge now

**Comment by abbradar** [comment]
Sorry for the delay and thanks for your work!

**Comment by abbradar** [comment]
Sorry for the delay and thanks for your work!

**Pull request merged**
