### PR TITLE
mosquito: add support for websockets

### PR DESCRIPTION
**Pull request by mogorman**
###### Motivation for this change

Mosquitto has supported websockets for 2 years now.  It would be nice to have this feature in nixos especially before 16.09
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x ] NixOS
  - [ ] OS X
  - [ x Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by mogorman** [comment]
Not sure about the mac error.  it looks to me like it broke because of some other build issue. but I don't have a way to test it.

**Comment by mogorman** [comment]
rebased to fix conflict/

**Comment by the-kenny** [comment]
@mogorman Can you please change the wording of the commit to match our [Guidelines](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes)?

Other than that it's ready to merge.

**Comment by mogorman** [comment]
i think that is correct per guide lines now.

**Comment by the-kenny** [comment]
Thanks! Merged as 6a01fc2

**Comment by mogorman** [comment]
@the-kenny i would like to backport this change for 16.09 could you point me in right direction to do that?

**Comment by the-kenny** [comment]
Sorry, missed your comment. I just cherry-picked your commit into the `release-16.09` branch.

**Pull request closed without merging**
