### PR TITLE
Bullet: upgrade and fix on aarch64

### PR DESCRIPTION
**Pull request by lheckemann**
###### Motivation for this change
New upstream version, aarch64 build was broken

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lheckemann** [comment]
@GrahamcOfBorg build bullet

**Comment by lheckemann** [comment]
The darwin failure is not introduced by this change: https://hydra.nixos.org/build/66960784

**Comment by lheckemann** [comment]
@aforemny any feedback?

**Comment by aforemny** [comment]
@lheckemann Looks good to me!

**Pull request merged**
