### PR TITLE
invidious: 2.20240825.2 -> 2.20241110.0

### PR DESCRIPTION
**Pull request by Kupac**
Due to some changes on Youtube, channels and subscriptions were no longer displayed in invidious. This update solves the problem.
https://github.com/iv-org/invidious/issues/5021
https://github.com/iv-org/invidious/pull/5059 

## Things done

Updated using the included update.sh script. 

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

  @_999eagle, @GaetanLepage, @sbruder, @pbsds

### CODE REVIEW

**Comment by hughobrien** [comment]
They [mention](https://github.com/iv-org/invidious/releases/tag/v2.20241110.0) a new dependency on `tzdata`, was that something we needed to include?

**Comment by hughobrien** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 355279`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>invidious</li>
  </ul>
</details>

**Comment by pbsds** [comment]
VM seems to run fine
image
(i assume my ip is blacklisted, since my instance in known by some)



> They [mention](https://github.com/iv-org/invidious/releases/tag/v2.20241110.0) a new dependency on `tzdata`, was that something we needed to include?

Judging by this line

https://github.com/iv-org/invidious/blob/98926047586154269bb269d01e3e52e60e044035/docker/Dockerfile#L36

it seems it is needed at runtime, not build time. In my minimal VM i find

image

But it would be nice to encode this explicitly in the nixos module if possible

**Review by pbsds — APPROVED** [review]

**Comment by Kupac** [comment]
Should I simply add it to buildInputs? I guess it worked on my system because tzdata must be installed already (which should be the case for most systems). But apparently alpine based docker is not one of them.

**Comment by hughobrien** [comment]
I honestly don't know, many `tzdata` usages in nixpkgs seem to also involve patching in zoneinfo paths.

According to the [bug report](https://github.com/iv-org/invidious/issues/5067) it should be obvious enough in the logs if it turns out to be necessary.

**Review by fpletz — APPROVED** [review]

**Comment by fpletz** [comment]
Deployed on aarch64 and fixes the issues mentioned.

**Pull request merged**
