### PR TITLE
jetbrains: build from source code with jbr-no-jcef-17

### LINKED ISSUE #320782: Build failure: jetbrains.idea-community
### Steps To Reproduce

1. build `jetbrains.idea-community`

### Build log

```
building '/nix/store/6iadizj083lq495fiyx1d1frbghlhsxn-idea-community-233.13135.103.tar.gz.drv'...
Running phase: unpackPhase
unpacking source archive /nix/store/n5p308f6szc1by0sdi7rddyxgacd13hk-source
source root is source
Running phase: patchPhase
applying patch /nix/store/4x8g999cjwfkb24bzw3f6yivm5vfvbdc-no-download.patch
patching file build/deps/src/org/jetbrains/intellij/build/impl/BundledMavenDownloader.kt
patching file platform/build-scripts/downloader/src/org/jetbrains/intellij/build/dependencies/BuildDependenciesDownloader.kt
patching file platform/build-scripts/downloader/src/org/jetbrains/intellij/build/dependencies/JdkDownloader.kt
patching file platform/build-scripts/src/org/jetbrains/intellij/build/LinuxDistributionCustomizer.kt
patching file platform/build-scripts/src/org/jetbrains/intellij/build/impl/LinuxDistributionBuilder.kt
Hunk #1 succeeded at 47 (offset 2 lines).
Hunk #2 succeeded at 92 (offset 7 lines).
patching file platform/build-scripts/src/org/jetbrains/intellij/build/impl/brokenPlugins.kt
patching file platform/build-scripts/src/org/jetbrains/intellij/build/kotlin/KotlinCompilerDependencyDownloader.kt
applying patch /nix/store/yk9mmd3x9v7jsw5bjrv5l4z5r3a2z69m-disable-sbom-generation.patch
patching file platform/build-scripts/src/org/jetbrains/intellij/build/impl/sbom/SoftwareBillOfMaterialsImpl.kt
Running phase: updateAutotoolsGnuConfigScriptsPhase
Running phase: configurePhase
Working directory: /build/source/build/jps-bootstrap-work
Loaded project /build/source: 1146 modules, 268 libraries in 1024 ms
Adding SDK 'jdk-home' at /nix/store/v62ppqgky69v4m6rb37dzymai6jphhcf-jetbrains-jdk-21.0.3-b465.3/lib/openjdk
Compilation log directory: /build/source/build/jps-bootstrap-work/log
Resolving project dependencies...
* DotNet packages credentials not loaded
Space credentials are not provided via -Djps.auth.spaceUsername and -Djps.auth.spacePassword. Private Space Maven dependencies, if not available locally, will fail to be resolved.
Be careful, logger will be shut down earlier than application: Unable to make field private static java.util.IdentityHashMap java.lang.ApplicationShutdownHooks.hooks accessible: module java.base does not "opens java.lang" to unnamed module @950161a
Running 'before' tasks
Checking sources
Started building Project Dependencies Resolving
Resolving repository libraries in the project?
Finished building Project Dependencies Resolving
Running 'after' tasks
Build duration: Builder 'Project dependencies resolver' took 4 s 692 ms; 0 sources processed
Finished, saving caches?
Finished resolving project dependencies in 6154 ms
:JPS_INFO:Errors occurred while compiling module 'intellij.platform.util.trove'
:JPS_INFO:Errors occurred while compiling module 'intellij.java.guiForms.rt'
:JPS_INFO:Errors occurred while compiling module 'intellij.platform.util.rt'
Kotlin:INFO:kotlinc-jvm 2.0.0 (JRE 21.0.3+35-nixos)
Kotlin:INFO:kotlinc-jvm 2.0.0 (JRE 21.0.3+35-nixos)
Kotlin:INFO:kotlinc-jvm 2.0.0 (JRE 21.0.3+35-nixos)
Kotlin:INFO:kotlinc-jvm 2.0.0 (JRE 21.0.3+35-nixos)
Kotlin:INFO:kotlinc-jvm 2.0.0 (JRE 21.0.3+35-nixos)
:JPS_INFO:javac 21.0.3 was used to compile java sources
:INFO:Modules 'intellij.platform.statistics.config', 'intellij.platform.util.rt', 'intellij.platform.util.nanoxml', 'intellij.java.guiForms.rt', 'intellij.platform.diagnostic' and 5 others were fully rebuilt due to project configuration/dependencies changes
Finished building 'intellij.devkit.jps intellij.platform.diagnostic.telemetry intellij.java.compiler.instrumentationUtil.java8 intellij.platform.util.jdom intellij.platform.buildScripts intellij.tools.testsBootstrap intellij.platform.testFramework.core intellij.platform.statistics.config intellij.platform.util.base intellij.platform.util.rt intellij.platform.jps.build intellij.platform.runtime.repository intellij.platform.util.rt.java8 intellij.platform.util.nanoxml intellij.platform.util.zip intellij.tools.jps.build.standalone intellij.platform.buildScripts.downloader intellij.groovy.jps intellij.platform.jps.model.serialization intellij.platform.diagnostic.telemetry.exporters intellij.platform.jps.build.javac.rt intellij.idea.community.build.dependencies intellij.platform.util.trove intellij.platform.util intellij.platform.util.xmlDom intellij.platform.jps.model intellij.idea.community.build intellij.platform.jps.model.impl intellij.platform.boot intellij.java.aetherDependencyResolver intellij.tools.jps.antTasks intellij.java.guiForms.compiler intellij.idea.community.build.tasks intellij.platform.diagnostic intellij.platform.util.classLoader intellij.platform.util.http intellij.groovy.constants.rt intellij.groovy.rt intellij.java.guiForms.rt intellij.java.guiForms.jps intellij.platform.util.immutableKeyValueStore intellij.devkit.runtimeModuleRepository.jps intellij.java.rt intellij.platform.tracing.rt intellij.java.compiler.instrumentationUtil' in 6616 ms
        Incremental build finished with errors. Forcing rebuild. Compilation errors:
        java:ERROR:error: release version 7 not supported
java:ERROR:error: release version 7 not supported
java:ERROR:error: release version 7 not supported
:JPS_INFO:Errors occurred while compiling module 'intellij.platform.util.trove'
:JPS_INFO:Errors occurred while compiling module 'intellij.java.guiForms.rt'
:JPS_INFO:Errors occurred while compiling module 'intellij.platform.util.rt'
Kotlin:INFO:kotlinc-jvm 2.0.0 (JRE 21.0.3+35-nixos)
Kotlin:INFO:kotlinc-jvm 2.0.0 (JRE 21.0.3+35-nixos)
Kotlin:INFO:kotlinc-jvm 2.0.0 (JRE 21.0.3+35-nixos)
Kotlin:INFO:kotlinc-jvm 2.0.0 (JRE 21.0.3+35-nixos)
:JPS_INFO:javac 21.0.3 was used to compile java sources
Finished building 'intellij.devkit.jps intellij.platform.diagnostic.telemetry intellij.java.compiler.instrumentationUtil.java8 intellij.platform.util.jdom intellij.platform.buildScripts intellij.tools.testsBootstrap intellij.platform.testFramework.core intellij.platform.statistics.config intellij.platform.util.base intellij.platform.util.rt intellij.platform.jps.build intellij.platform.runtime.repository intellij.platform.util.rt.java8 intellij.platform.util.nanoxml intellij.platform.util.zip intellij.tools.jps.build.standalone intellij.platform.buildScripts.downloader intellij.groovy.jps intellij.platform.jps.model.serialization intellij.platform.diagnostic.telemetry.exporters intellij.platform.jps.build.javac.rt intellij.idea.community.build.dependencies intellij.platform.util.trove intellij.platform.util intellij.platform.util.xmlDom intellij.platform.jps.model intellij.idea.community.build intellij.platform.jps.model.impl intellij.platform.boot intellij.java.aetherDependencyResolver intellij.tools.jps.antTasks intellij.java.guiForms.compiler intellij.idea.community.build.tasks intellij.platform.diagnostic intellij.platform.util.classLoader intellij.platform.util.http intellij.groovy.constants.rt intellij.groovy.rt intellij.java.guiForms.rt intellij.java.guiForms.jps intellij.platform.util.immutableKeyValueStore intellij.devkit.runtimeModuleRepository.jps intellij.java.rt intellij.platform.tracing.rt intellij.java.compiler.instrumentationUtil' in 2937 ms
##teamcity[publishArtifacts '/build/source/build/jps-bootstrap-work/log=>jps-bootstrap-jps-logs.zip']
ERROR: java:ERROR:error: release version 7 not supported
ERROR: java:ERROR:error: release version 7 not supported
ERROR: java:ERROR:error: release version 7 not supported

FATAL: java.lang.IllegalStateException: Build finished with errors. See TC artifacts for build log. First error:
java:ERROR:error: release version 7 not supported
        at org.jetbrains.jpsBootstrap.JpsBuild$JpsMessageHandler.assertNoErrors(JpsBuild.kt:189)
        at org.jetbrains.jpsBootstrap.JpsBuild.runBuild(JpsBuild.kt:134)
        at org.jetbrains.jpsBootstrap.JpsBuild.runBuild(JpsBuild.kt:131)
        at org.jetbrains.jpsBootstrap.JpsBuild.buildModules(JpsBuild.kt:69)
        at org.jetbrains.jpsBootstrap.JpsBootstrapMain.downloadOrBuildClasses(JpsBootstrapMain.kt:317)
        at org.jetbrains.jpsBootstrap.JpsBootstrapMain.main(JpsBootstrapMain.kt:158)
        at org.jetbrains.jpsBootstrap.JpsBootstrapMain.access$main(JpsBootstrapMain.kt:47)
        at org.jetbrains.jpsBootstrap.JpsBootstrapMain$Companion.main(JpsBootstrapMain.kt:358)
        at org.jetbrains.jpsBootstrap.JpsBootstrapMain.main(JpsBootstrapMain.kt)


          ###### ERROR EXIT due to FATAL error: Build finished with errors. See TC artifacts for build log. First error:
java:ERROR:error: release version 7 not supported
```

### Notify maintainers

@edwtjo  @gytis-ivaskevicius @steinybot @AnatolyPopov @tymscar 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by herberteuler**
## Description of changes

Add JBR-17 and use it to build community versions of JetBrains IDEs.
Fixes issues introduced in #318036.

Update: I have checked this on #316185; both the two IDEs were successfully built and able to run.

Fixes https://github.com/NixOS/nixpkgs/issues/320782

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by herberteuler** [comment]
@leona-ya I am considering reopening #320161 and adding this commit if everything works. Is it okay?

**Review by raboof — APPROVED** [review]
A bit icky to have so much duplication between `17.nix` and `default.nix`, but I can see how removing the duplication would make things more complex, so the trade-off seems fair.

Can confirm `jetbrains.idea-community` now starts again and opens nontrivial projects fine.

Fixes #320782

**Review by leona-ya — APPROVED** [review]
Also works for me. Thank you.

**Comment by leona-ya** [comment]
> I can see how removing the duplication would make things more complex, so the trade-off seems fair.

I also think we can (and maybe should?) remove jdk 17 in unstable when 2024.2 is releases as – to my understanding – it's fully based on jdk 21.

> @leona-ya I am considering reopening https://github.com/NixOS/nixpkgs/pull/320161 and adding this commit if everything works. Is it okay?

I think yes. I would wait for a few days tho to see if other regressions occur.

**Comment by herberteuler** [comment]
> I think yes. I would wait for a few days tho to see if other regressions occur.

For sure. I will wait a few days or weeks to reopen it.

**Pull request merged**
