### PR TITLE
woodpecker: 1.0.3 -> 1.0.5

### PR DESCRIPTION
**Pull request by adamcstephens**
## Description of changes

https://github.com/woodpecker-ci/woodpecker/blob/v1.0.5/CHANGELOG.md

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by ambroisie — APPROVED** [review]

**Comment by ambroisie** [comment]
The 2.0.0 update should be coming soon BTW.

**Comment by mweinelt** [comment]
> The 2.0.0 update should be coming soon BTW.

That sounds like breaking changes. Too late for NixOS 23.11.

**Comment by mweinelt** [comment]
Please add `meta.changelog` and reference the changelog URL in the commit message.

```
https://github.com/woodpecker-ci/woodpecker/blob/v${version}/CHANGELOG.md

**Comment by ambroisie** [comment]
> That sounds like breaking changes. Too late for NixOS 23.11.

It is semver breaking, but only in the most minor ways (they're removing things that have been deprecated since 1.0.0).

Also, unless I'm mistaken targeting `master` for breaking changes is fine.

**Comment by mweinelt** [comment]
> Also, unless I'm mistaken targeting master for breaking changes is fine.

We're in breaking changes freeze since 2023-10-30 until after the branch-off around 2023-11-20.

**Comment by ambroisie** [comment]
Ah, I'd missed that it was already started, thank you 👍.

**Comment by adamcstephens** [comment]
> Please add `meta.changelog`

`meta.changelog` is already defined in `common.nix`...

**Comment by MayNiklas** [comment]
> The 2.0.0 update should be coming soon BTW.

There is already a release candidate for 2.0.0 I wanted to play around with.
Unfortunately, I wasn't able to 'just update' the woodpecker package to 2.0.0 - it will require some small changes!

**Pull request merged**
