### PR TITLE
zigbee2mqtt: 1.16.2 -> 1.22.1

### PR DESCRIPTION
**Pull request by ck3d**
###### Motivation for this change

- Update versions
- switch from npm to yarn for hopefully cleaner derivation (see also https://github.com/NixOS/nixpkgs/pull/147792 and https://github.com/NixOS/nixpkgs/pull/131623)
- disable application self update which is not possible with nix
- web interface is now working
- remove unused argument dataDir

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ck3d** [comment]
I have to check why ofborg can not execute the test.

**Comment by ck3d** [comment]
On my machine I can execute the test.

**Comment by NULLx76** [comment]
I get the same error as ofborg when I try to build/test this PR using `nixpkgs-review` but when I do it manually no errors occur.

**Comment by ck3d** [comment]
I could fix the check by providing a package.json and yarn.nix. From my side, the package is ready to review.

**Comment by sweber83** [comment]
@ck3d 
When I originally implemented the zigbee2mqtt package, I too thought about using yarn and yarn2nix instead of npm and node2nix.
I ended up using npm because yarn is not able to replicate the dependencies from `npm-shrinkwrap.json`.

The way you implemented it with yarn, every time the update script is run, one can end up with different dependencies in `yarn.lock`.
If you run the update script now, then wait a few days and run it again, the resulting `yarn.lock` can look different, because a new version of a dependency was released.
This way, we can't really use the update script for automated updates, because it will result in a new derivation although no new version of zigbee2mqtt was released.

I just noticed, the update script fetches `package.json` from master, so even without the yarn / shrinkwrap problem, it will create a new derivation as soon as there are new commits on master.
The way it should work is that it only produces a new derivation, when there's a new release version.

**Comment by ck3d** [comment]
I also do not like to have a different lock file than what the upstream package use. But packaging this package in Nix is not easy. We had no updates for more than year in nixpkgs, so I looked for a simpler approach which ended in this PR.
But I am happy if you or somebody else can maintain this package with node2nix.

**Comment by sweber83** [comment]
Since the derivation size issue with node2nix seems to be [solved](https://github.com/NixOS/nixpkgs/pull/142319), I'll see if I can get the node2nix based package to the current version.

**Pull request closed without merging**
