### PR TITLE
Numerical computing overhaul

### PR DESCRIPTION
**Pull request by ttuegel**
This is a big overhaul of our numerical computing packages. The biggest change is replacing ATLAS with OpenBLAS in the following packages:
- suitesparse
- arpack
- julia
- hmatrix
- R
- numpy and scipy

This will decrease build times. Dynamic architecture detection improves performance on all platforms.

Some of these packages previously experienced segfaults when built with OpenBLAS due to its use of 64-bit integers in the BLAS and LAPACK interfaces. (Standard BLAS and LAPACK use 32-bit integers, even on 64-bit platforms.) We now build two versions of OpenBLAS; `openblas` uses platform-native integers, while `openblasCompat` uses 32-bit integers to be compatible with standard BLAS and LAPACK. Packages that depend on OpenBLAS natively (suitesparse, arpack, and julia) now use platform-native integers. Packages that depend on BLAS and LAPACK generically (hmatrix, R, numpy, and scipy) use 32-bit integers still.

@peti I use hmatrix myself extensively; I have tested these changes on my code without incident. I do not use R myself, but its tests continue to pass with these changes. For numpy and scipy, I have checked the short tests in #6772, but done no extensive testing.

I have improved the suitesparse package so that now it also builds shared libraries.

@7c6f434c I think you are listed as the maintainer of Julia. This PR includes a significant refactoring of the expression for `julia03`. There were several unused dependencies, which I removed. I also removed almost all of the private libraries in favor of the system versions. I updated to julia-0.3.9, released recently. Because suitesparse now provides shared libraries, I removed that step from the Julia build. I also changed the expression style in places to match the rest of Nixpkgs better. If any of these changes are a problem for you, I am happy to revert them, please just let me know. Also, can we drop `julia02`? That would also allow us to drop the old version of suitesparse.

I don't want to drop any huge changes on the other maintainers, so I will wait 48 hours before merging this, to see if there are any complaints.

### CODE REVIEW

**Comment by ttuegel** [comment]
I forgot to mention, regarding Julia:
I also generalized the architecture settings. The `i686-linux` build now works, and `x86_64-darwin` should also work (but I can't test it). I also generalized the JIT target because the `x86_64-linux` build wouldn't work on pre-Bulldozer AMD CPUs. I think the Hydra builds should be more compatible than that.

**Comment by ttuegel** [comment]
I just added two commits to switch Octave and its dependencies to OpenBLAS.

A quick `grep` reveals that only a few packages still require ATLAS, so I'll go for broke and switch them all.

**Comment by peti** [comment]
This is gonna be interesting. :+1:

**Comment by garbas** [comment]
i've tested this on darwin. looks like clang (from xcode) does not support ``USE_OPENMP=1`` option for openblas. i get 

```
building path(s) ‘/nix/store/w3jgr6926p0hn0b8shj96hkh1y5v7wqj-openblas-0.2.14’
unpacking sources
unpacking source archive /nix/store/arpi0lqjwfaj4xg4yfri16w0s3jvp53q-openblas-0.2.14.tar.gz
source root is xianyi-OpenBLAS-2b0d8a8
patching sources
configuring
no configure script, doing nothing
building
make flags: SHELL=/nix/store/sl3scf6za8b9bpr4ynfkfh6sqn3rcdvl-bash-4.3-p33/bin/bash DYNAMIC_ARCH=1 NUM_THREADS=64 MACOSX_DEPLOYMENT_TARGET=10.9 FC=gfortran CC=clang PREFIX="$(out)" BINARY=64 USE_OPENMP=1 INTERFACE64=0   
Makefile.system:379: *** OpenBLAS: Clang didn't support OpenMP yet..  Stop.
```

without ``USE_OPENMP=1`` option openblas builds fine on darwin.
i've only tested ``nix-build -A pythonPackages.scipy``.

**Comment by vcunat** [comment]
Another option might be to use newer clang from nixpkgs on darwin, but disabling openmp should be easier for now.

**Comment by ttuegel** [comment]
@garbas Thanks for the report! I have disabled OpenMP on Darwin now. It is still enabled by default on other platforms because if another package links to OpenBLAS and uses OpenMP, it will segfault otherwise. That shouldn't be an issue on Darwin, though, because nothing can use OpenMP.

**Comment by vcunat** [comment]
Tarball works now.

**Pull request merged**
