### PR TITLE
[staging] x11 updates

### PR DESCRIPTION
**Pull request by ikervagyok**
###### Motivation for this change
another round of x11 updates from the x11-announce ml

###### Things done
just rebuilt my laptop, didnt test any apps (yet) will do that tomorrow.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ikervagyok** [comment]
@lheckemann am i too late for 19.03 yet? i forgot about these

**Comment by dtzWill** [comment]
cc #56252 , I don't care which but let's just be sure to get updates from both? :)

**Comment by xeji** [comment]
I just merged #56252 . That leaves the two new packages `xfsinfo` and `xstdcmap` from this. Let's just cherry-pick these.

**Comment by xeji** [comment]
cherry-picked `xfsinfo` and `xstdcmap` to staging in dffba878e135960d14f12392a52eb24194539dd7 and ed508238beb1ce451cc02d9322dad6cdaf65f848 .  Now everything from this PR should be covered.

**Pull request closed without merging**
