### PR TITLE
diffoscope: 261 -> 263

### PR DESCRIPTION
**Pull request by trofi**
Changes: https://diffoscope.org/news/diffoscope-262-released/

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by trofi** [comment]
Result of `nixpkgs-review pr 300021` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>diffoscope</li>
    <li>diffoscope.dist</li>
    <li>diffoscope.man</li>
    <li>diffoscopeMinimal</li>
    <li>diffoscopeMinimal.dist</li>
    <li>diffoscopeMinimal.man</li>
  </ul>
</details>

**Review by philiptaron — APPROVED** [review]

**Review by philiptaron — COMMENTED** [review]
I clicked too fast.

I get a build failure:

```
=================================== FAILURES ===================================
__________________________________ test_diff ___________________________________

differences = []

    @skip_unless_tool_is_at_least("ssh-keygen", openssh_version, "6.9")
    def test_diff(differences):
        expected_diff = get_data("openssh_pub_key_expected_diff")
>       assert differences[0].unified_diff == expected_diff
E       IndexError: list index out of range

tests/comparators/test_openssh_pub_key.py:60: IndexError
__________________________ test_compare_non_existing ___________________________

monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7ffee6065010>
opensshpubkey1 = <<class 'abc.PublicKeyFile'> /build/diffoscope-262/tests/data/test_openssh_pub_key1.pub>

    @skip_unless_tools_exist("ssh-keygen")
    def test_compare_non_existing(monkeypatch, opensshpubkey1):
        monkeypatch.setattr(Config(), "new_file", True)
        difference = opensshpubkey1.compare(
            MissingFile("/nonexisting", opensshpubkey1)
        )
        assert difference.source2 == "/nonexisting"
>       assert len(difference.details) > 0
E       assert 0 > 0
E        +  where 0 = len([])
E        +    where [] = <Difference /build/diffoscope-262/tests/data/test_openssh_pub_key1.pub -- /nonexisting []>.details

tests/comparators/test_openssh_pub_key.py:70: AssertionError
=============================== warnings summary ===============================
../../nix/store/4vdc8i6i2yrs7nvqfa4fcypksaqabrcr-python3.11-pypdf2-3.0.1/lib/python3.11/site-packages/PyPDF2/__init__.py:21
  /nix/store/4vdc8i6i2yrs7nvqfa4fcypksaqabrcr-python3.11-pypdf2-3.0.1/lib/python3.11/site-packages/PyPDF2/__init__.py:21: DeprecationWarning: PyPDF2 is deprecated. Please move to the pypdf library instead.
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/comparators/test_openssh_pub_key.py::test_diff - IndexError: list index out of range
FAILED tests/comparators/test_openssh_pub_key.py::test_compare_non_existing - assert 0 > 0
= 2 failed, 671 passed, 37 skipped, 5 deselected, 1 xfailed, 1 xpassed, 1 warning in 33.67s =
```

**Comment by trofi** [comment]
Seeing it as well now. Probably a dependency update. Marking as `draft` for now.

**Comment by philiptaron** [comment]
Thanks for root-causing the issue, @amarshall.

**Comment by philiptaron** [comment]
@drupol, mind merging this one now that #302348 is in?

**Pull request merged**
