### PR TITLE
redmine: 4.2.5 -> 4.2.7

### PR DESCRIPTION
**Pull request by delroth**
###### Description of changes

Bump to the latest 4.x version. This includes security fixes for 4 vulnerabilities per https://www.redmine.org/projects/redmine/wiki/Security_Advisories, so tagging appropriately for security and backports.

The existing update script did not properly work because it was picking up an arch-dependent gem variant for nokogiri. I added some `bundle lock --add-platform` / `bundle lock --remove-platform` invocations to fix this, inspired by how the `discourse` update script currently works.

Also added `nixosTests.redmine` to `passthru.tests` since it wasn't there yet, as a quick cleanup along the way.

Tested with NixOS tests + a barebones deployment on one of my servers, could't notice any obvious issue.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by delroth** [comment]
@ofborg eval (hoping to not land on the evaluator with a full disk again...)

**Review by felixsinger — CHANGES_REQUESTED** [review]
Looks good to me, but please split up the patch into multiple ones. So the patch regarding the tests and the other one fixing the update script should go into separate patches. Also, add proper commit messages.

**Comment by delroth** [comment]
> Looks good to me, but please split up the patch into multiple ones. So the patch regarding the tests and the other one fixing the update script should go into separate patches. Also, add proper commit messages.

Split into 3 commits as per your preference, PTAL. Hopefully CI will decide to work instead of running out of inodes this time...

**Review by felixsinger — CHANGES_REQUESTED** [review]
> Method inspired by the update script for `discourse` in nixpkgs.

What does that mean? Do you refer to a thread somewhere on https://discourse.nixos.org? If so, you should add a link to it or just leave it out. This way it's too confusing.

**Comment by SuperSandro2000** [comment]
> What does that mean? Do you refer to a thread somewhere on [discourse.nixos.org](https://discourse.nixos.org)? If so, you should add a link to it or just leave it out. This way it's too confusing.

It refers to the discourse package in nixpkgs. https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/web-apps/discourse/update.py#L179
https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/web-apps/discourse/update.py#L245

Fine as it is.

**Review by SuperSandro2000 — APPROVED** [review]

**Review by felixsinger — APPROVED** [review]
Looks good to me.

**Pull request merged**
