### PR TITLE
[23.05] Backport fixes for davinci-resolve

### PR DESCRIPTION
**Pull request by davidak**
## Description of changes

Backports all commits from master. They are needed for a working program.

9bca13980fae davinci-resolve: remove host header restrictions for blob download (https://github.com/NixOS/nixpkgs/pull/246647)
384a9eeee4dd davinci-resolve: update payload request and URL of download (https://github.com/NixOS/nixpkgs/pull/246074)
e0d25a052885 davinci-resolve: add missing dependencies to 18.1.4 (part of https://github.com/NixOS/nixpkgs/pull/240549)
c4319ac59e90 davinci-resolve: 17.4.3 -> 18.1.4 (https://github.com/NixOS/nixpkgs/pull/240549)

Related issues:

- https://github.com/NixOS/nixpkgs/issues/210098
- https://github.com/NixOS/nixpkgs/issues/242091

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by eclairevoyant** [comment]
going from 17 to 18 seems like a breaking change to me, any reason for this?

**Comment by davidak** [comment]
@eclairevoyant it uses Python 2.7 (EOL and insecure). See linked issue.

**Comment by eclairevoyant** [comment]
Python2 has been dead for 3 years, bit late to the game now...

Anyway, I disagree that this qualifies for the security exemption in the backport process. It really depends on the threat model, but in general, I do not believe the mere existence of python2 in the store is substantial enough to outweigh the breakage involved when DVR changes major versions (which is substantial and much more realistic).

**Comment by davidak** [comment]
@eclairevoyant i see. thanks

then i only backport the curl fix

**Comment by wegank** [comment]
Closing since NixOS 23.05 is EOL.

**Pull request closed without merging**
