### PR TITLE
clojure-lsp: 2022.02.23-12.12.12 -> 2022.03.26-18.47.08

### PR DESCRIPTION
**Pull request by ericdallo**
###### Description of changes

- Bump to latest
- Fix update script

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by EllipticCrab** [comment]
Result of `nixpkgs-review pr 166149` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>clojure-lsp</li>
  </ul>
</details>

**Comment by EllipticCrab** [comment]
fail log:

```
$ nix --experimental-features nix-command build --no-link --keep-going -f /Users/gordias/.cache/nixpkgs-review/pr-166149/build.nix
error: builder for '/nix/store/rim289srkx6476saxl295r4hk9953zyw-graalvm11-ce.drv' failed with exit code 1;
       last 10 log lines:
       >     yield ELFFile(stream)
       >   File "/nix/store/0qmwd1hj38nj7dsnyhn5pxbwqv6f52m1-python3-3.9.10-env/lib/python3.9/site-packages/elftools/elf/elffile.py", line 73, in __init__
       >     self._identify_file()
       >   File "/nix/store/0qmwd1hj38nj7dsnyhn5pxbwqv6f52m1-python3-3.9.10-env/lib/python3.9/site-packages/elftools/elf/elffile.py", line 482, in _identify_file
       >     elf_assert(magic == b'\x7fELF', 'Magic number does not match')
       >   File "/nix/store/0qmwd1hj38nj7dsnyhn5pxbwqv6f52m1-python3-3.9.10-env/lib/python3.9/site-packages/elftools/common/utils.py", line 77, in elf_assert
       >     _assert_with_exception(cond, msg, ELFError)
       >   File "/nix/store/0qmwd1hj38nj7dsnyhn5pxbwqv6f52m1-python3-3.9.10-env/lib/python3.9/site-packages/elftools/common/utils.py", line 114, in _assert_with_exception
       >     raise exception_type(msg)
       > elftools.common.exceptions.ELFError: Magic number does not match
       For full logs, run 'nix log /nix/store/rim289srkx6476saxl295r4hk9953zyw-graalvm11-ce.drv'.
error: 1 dependencies of derivation '/nix/store/mm8fsnmbsv9jsj1hkzqnvb06wbpwxcrg-clojure-lsp-2022.03.26-18.47.08.drv' failed to build
error: 1 dependencies of derivation '/nix/store/c0jmpmimnq8ymk5p8y337sgfx9vhdhwr-review-shell.drv' failed to build
```

**Comment by ericdallo** [comment]
@EllipticCrab not sure if there is anything wrong, maybe something with darwin only? I tested the binary on NixOS and it worked properly

**Review by thiagokokada — APPROVED** [review]
The darwin issue is related to https://github.com/NixOS/nixpkgs/issues/165670, fixed on https://github.com/NixOS/nixpkgs/pull/163924.

Otherwise LGTM. Going to merge this.

**Pull request merged**
