### PR TITLE
agda: 2.6.2 -> 2.6.2.1

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Motivation for this change

cc @turion @alexarice @iblech

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by turion** [comment]
@ofborg build agda.passthru.tests.allPackages

I'm not familiar with the current haskell packages setup, so I can't comment on the advantages & disadvantages of pinning this extra version.

**Comment by turion** [comment]
(See https://nixos.org/manual/nixpkgs/unstable/#maintaining-the-agda-package-set-on-nixpkgs for the test)

**Comment by srid** [comment]
For the record, Agda fails with segfault during linking on m1 Mac. I suppose it always failed this way, and this PR wasn't intended to change that.

```
       > Linking dist/build/agda/agda ...
       > /nix/store/bp55vzlmcyqcx9n08pkzslvks10zybwc-clang-wrapper-11.1.0/bin/ld: line 256: 58415 Segmentation fault: 11  /nix/store/3fl5z9yfnz08kjb4cnhw2w8a2zsm5qim-cctools-binutils-darwin-949.0.1/bin/ld ${extraBefore+"${extraBefore[@]}"} ${params+"${params[@]}"} ${extraAfter+"${extraAfter[@]}"}
```

image

**Comment by turion** [comment]
> For the record, Agda fails with segfault during linking on m1 Mac. I suppose it always failed this way, and this PR wasn't intended to change that.
> 
> ```
>        > Linking dist/build/agda/agda ...
>        > /nix/store/bp55vzlmcyqcx9n08pkzslvks10zybwc-clang-wrapper-11.1.0/bin/ld: line 256: 58415 Segmentation fault: 11  /nix/store/3fl5z9yfnz08kjb4cnhw2w8a2zsm5qim-cctools-binutils-darwin-949.0.1/bin/ld ${extraBefore+"${extraBefore[@]}"} ${params+"${params[@]}"} ${extraAfter+"${extraAfter[@]}"}
> ```

That sounds bad :( do we know this already? I can't find an issue related to this.

**Comment by sternenseemann** [comment]
Unchanged: <https://hydra.nixos.org/build/160900296>

**Comment by sternenseemann** [comment]
@ofborg test agda

**Comment by sternenseemann** [comment]
Seems like this is good to go, `aarch64-linux` issue is a timeout. Any concerns?

**Comment by sternenseemann** [comment]
Follow #149730 for further stabilization.

**Pull request merged**
