### PR TITLE
staging-next 2022-11-12

### PR DESCRIPTION
**Pull request by vcunat**
This is planned as the last iteration for 22.11 and it should contain no breaking changes.
https://github.com/NixOS/nixpkgs/issues/193585
- - -
- workflow docs: https://nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy
- important jobs:
  https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
  https://hydra.nixos.org/job/nixos/staging-next-small/tested
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next
  https://hydra.nixos.org/jobset/nixos/staging-next-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/199725

### CODE REVIEW

**Comment by lorenz** [comment]
Any chance https://github.com/NixOS/nixpkgs/pull/200872 could be pulled in as it missed the (early) staging->staging-next transfer and thus would miss 22.11?

**Comment by vcunat** [comment]
@lorenz: OK, merged.  Fortunately the rebuilds are not so high, especially for our bottle-neck `*-darwin`.

**Comment by delroth** [comment]
Could #200760 be added as well? It's low risk and a major fix for cross-compilation since glib is a very common dependency.

**Comment by vcunat** [comment]
Not in this iteration.  Sounds OK for `staging-22.11` later, at a quick glance.

**Comment by vcunat** [comment]
There are quite a few python* issues again, as usual:
https://hydra.nixos.org/eval/1785779?compare=1785775#tabs-now-fail

**Comment by SuperSandro2000** [comment]
fix intel-media-driver build in #202115

**Pull request merged**
