### PR TITLE
autoPatchelfHook: allow building on all platforms 

### PR DESCRIPTION
**Pull request by tie**
## Description of changes

This change allows using autoPatchelfHook in nativeBuildInputs when cross-compiling from non-Linux platform. Technically, the hook is platform-independent and only limited by the dependencies, namely patchelf (`platforms = all`) and pyelftools (inherits from python, that is, `platforms = linux ++ darwin ++ windows`).

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by layus** [comment]
LGTM. Thanks! Will merge on Monday if not merged before.

Le 4 mai 2024 08:37:17 GMT+02:00, Ivan Trubach ***@***.***> a écrit :

**Comment by NickCao** [comment]
While the hook should be available on all `hostPlatform`, it should be nop for non-elf `targetPlatform`.

**Comment by layus** [comment]
Is that true though ? I would prefer to have it fail the build, or mark it as failed automatically.

If your package depends on autopatchelf, you probably do not want it to silently turn into a noop. And you probably do not want to use it for these platforms anyway.

Le 4 mai 2024 16:16:28 GMT+02:00, Nick Cao ***@***.***> a écrit :

**Comment by NickCao** [comment]
> Is that true though ? I would prefer to have it fail the build, or mark it as failed automatically.

Maybe, but the current situation is somewhat bad, like in https://github.com/NixOS/nixpkgs/pull/304336#discussion_r1575252767 where it spams the log.

**Comment by NickCao** [comment]
> > Is that true though ? I would prefer to have it fail the build, or mark it as failed automatically.
> 
> Maybe, but the current situation is somewhat bad, like in [#304336 (comment)](https://github.com/NixOS/nixpkgs/pull/304336#discussion_r1575252767) where it spams the log.

Edit: ignore me, that was `auditTmpdir` hook, but the same applies.

**Comment by tie** [comment]
Disabling autoPatchelfHook for non-ELF target platforms is trivial but I don’t think it makes much sense to do that. Unlike auditTmpdir, autoPatchelfHook is explicitly added to nativeBuildInputs, _conditionally_ in most cases, and otherwise the package is already limited to ELF platforms anyway. And technically it _can_ run for non-ELF target platforms, although I can’t think of any practical use case (but that doesn’t mean there isn’t one).

```diff
diff --git a/pkgs/build-support/setup-hooks/auto-patchelf.sh b/pkgs/build-support/setup-hooks/auto-patchelf.sh
index 783ea45f8eeb..8a9c8b18df25 100644
--- a/pkgs/build-support/setup-hooks/auto-patchelf.sh
+++ b/pkgs/build-support/setup-hooks/auto-patchelf.sh
@@ -97,7 +97,7 @@ autoPatchelfPostFixup() {
     # So what we do here is basically run in postFixup and emulate the same
     # behaviour as fixupOutputHooks because the setup hook for patchelf is run in
     # fixupOutput and the postFixup hook runs later.
-    if [[ -z "${dontAutoPatchelf-}" ]]; then
+    if [[ -z "${dontAutoPatchelf-@dontAutoPatchelfByDefault@}" ]]; then
         autoPatchelf -- $(for output in $(getAllOutputNames); do
             [ -e "${!output}" ] || continue
             echo "${!output}"
diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
index cefad4d25783..71dc7998dd48 100644
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -192,6 +192,9 @@ with pkgs;
     substitutions = {
       pythonInterpreter = "${python3.withPackages (ps: [ ps.pyelftools ])}/bin/python";
       autoPatchelfScript = ../build-support/setup-hooks/auto-patchelf.py;
+      # Do not run autoPatchelfHook by default if the target platform executable
+      # format is not ELF.
+      dontAutoPatchelfByDefault = lib.optionalString (!stdenv.targetPlatform.isElf) "true";
     };
   } ../build-support/setup-hooks/auto-patchelf.sh;
```

**Review by layus — APPROVED** [review]
Okay, all good to me. Thanks for addressing my concerns.

**Pull request merged**
