### PR TITLE
solc: 0.6.8 -> 0.7.1

### PR DESCRIPTION
**Pull request by RaghavSood**
###### Motivation for this change

Tests for 0.6.8 fail, and upstream has a new version anyways

This will be backported to 20.09 as part of ZHF.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
Fails to build for me on macos 10.14:

```
/tmp/nix-build-solc-0.7.1.drv-0/source/libsmtutil/CVC4Interface.cpp:231:24: error: call to constructor of 'CVC4::BitVector' is ambiguous
                                        m_context.mkConst(CVC4::BitVector(1, size_t(0)))
                                                          ^               ~~~~~~~~~~~~
/nix/store/4j8gspc6s2vlrdghbw8mn36aan8r6z3l-cvc4-1.8/include/cvc4/util/bitvector.h:47:3: note: candidate constructor
  BitVector(unsigned size, uint32_t z) : d_size(size), d_value(z)
  ^
/nix/store/4j8gspc6s2vlrdghbw8mn36aan8r6z3l-cvc4-1.8/include/cvc4/util/bitvector.h:59:3: note: candidate constructor
  BitVector(unsigned size, uint64_t z) : d_size(size), d_value(z)
  ^
/nix/store/4j8gspc6s2vlrdghbw8mn36aan8r6z3l-cvc4-1.8/include/cvc4/util/bitvector.h:33:3: note: candidate constructor
  BitVector(unsigned size, const Integer& val)
  ^
/nix/store/4j8gspc6s2vlrdghbw8mn36aan8r6z3l-cvc4-1.8/include/cvc4/util/bitvector.h:64:3: note: candidate constructor
  BitVector(unsigned size, const BitVector& q)
  ^
1 error generated.
make[2]: *** [libsmtutil/CMakeFiles/smtutil.dir/build.make:160: libsmtutil/CMakeFiles/smtutil.dir/CVC4Interface.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:518: libsmtutil/CMakeFiles/smtutil.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

**Comment by risicle** [comment]
The tests fail for me on linux x86_64:

```
solidity/test/boostTest.cpp(115): error: in "smtCheckerTests/modifiers/modifier_code_after_placeholder": Test expectation mismatch.
Expected result:
  Warning 4984: (203-208): Overflow (resulting value larger than 2**256 - 1) happens here.
  Warning 6328: (136-149): Assertion violation happens here
Obtained result:
  Warning 4984: (203-208): Overflow (resulting value larger than 2**256 - 1) happens here
  Warning 6328: (136-149): Assertion violation happens here
solidity/test/boostTest.cpp(115): error: in "smtCheckerTests/types/tuple_assignment_array_empty": Test expectation mismatch.
Expected result:
  Warning 6328: (136-153): Assertion violation happens here
Obtained result:
  Warning 6328: (136-153): Assertion violation happens here.
solidity/test/boostTest.cpp(115): error: in "smtCheckerTests/functions/functions_external_2": Test expectation mismatch.
Expected result:
  Warning 4661: (297-321): Assertion violation happens here
Obtained result:
  Warning 1218: (297-321): Error trying to invoke SMT solver.
  Warning 4661: (297-321): Assertion violation happens here
```

**Review by jonringer — COMMENTED** [review]
still getting failures:
```
builder for '/nix/store/1bwdqa1k0ykk2qc3x4x7wacx7c6c5g3s-solc-0.7.1.drv' failed with exit code 1; last 10 log lines:
  Expected result:
    Warning 4661: (297-321): Assertion violation happens here
  Obtained result:
    Warning 1218: (297-321): Error trying to invoke SMT solver.
    Warning 4661: (297-321): Assertion violation happens here

  ***

  *** 3 failures are detected in the test module "SolidityTests"
```

**Comment by RaghavSood** [comment]
Closing in favor of #101873

**Pull request closed without merging**
