### PR TITLE
all-packages: Use callPackage where possible

### PR DESCRIPTION
**Pull request by Mathnerd314**
This creates no new derivations, although it does add (identical) copies of pixman and squid-3.5.1 due to the use of callPackages.

I also have to add explicit arguments to builderDefs packages; this is apparently a good thing.

### CODE REVIEW

**Comment by vcunat** [comment]
Identical copies? I can't see anything like that in the diff (looked at occurrences of `pixman` and `squid`).

In `xorg`, why did you use `callPackagesWith pkgs` instead of `callPackages`?

**Comment by vcunat** [comment]
> In xorg, why did you use callPackagesWith pkgs instead of callPackages?

Oh, there's infinite recursion otherwise. I wonder why...

**Comment by Mathnerd314** [comment]
@vcunat pkgs.xorg is in the default scope, so callPackages would have to access the contents of pkgs.xorg before it is even imported.

@nckx I forgot to re-check the earlier ones, looks like that's the only one I missed.

**Comment by Mathnerd314** [comment]
@vcunat The identical copies appear in the Travis build, also in nix-env / nix-instantiate. It seems ``import ( xorg { inherit pixman; } )`` did not produce a new attribute while ``callPackages ( xorg { inherit pixman; } )`` did. (Similarly squid has ``squid35 = ...`` and ``latest = squid35``).

**Comment by vcunat** [comment]
Hmm, the duplicates are only when querying and the derivations are identical. There seems to be some heuristics that removes the duplicates, but it doesn't work when there are multiple attributes outside the top-level attrmap. Maybe the usage of `makeOverridable` makes it think they're different even though they evaluate to the same derivation path (they likely contain different added fields).

**Comment by Mathnerd314** [comment]
The heuristic is pointer equality: https://github.com/NixOS/nix/blob/master/src/libexpr/get-drvs.cc#L193
It should probably use drvPath too.

**Pull request merged**
