### PR TITLE
[21.11] Fix some places where python2 packages fail to evaluate.

### PR DESCRIPTION
**Pull request by tomprince**
I unfortunately still depend on some python2 packages. It appears
that these two packages fail to evaluate, in a way that `tryEval`
doesn't catch. This changes them to be explicitly disabled there.

Backport of #148328.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by FRidh — CHANGES_REQUESTED** [review]
disabling for Python 2 should be done in `python2-packages.nix`

**Comment by tomprince** [comment]
> disabling for Python 2 should be done in `python2-packages.nix`

Hmm. I was matching some existing examples in the `python-packages.nix` file. In any case, I've switched to doing in `python2-packages.nix`, and as a separate commit, changed the existing examples as well (both here and in #148328).

**Comment by jonringer** [comment]
When backporting changes, please follow https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#backporting-changes.

Namely, you should be doing `git cherry-pick -x <rev>` from a commit that has already landed in master. If the branches have diverged, you may alter the commit or add another commit to ensure that the package is able to still evaluate and build

**Comment by jonringer** [comment]
please make commits against master

**Comment by tomprince** [comment]
On Thu., Dec. 2, 2021, 20:09 Jonathan Ringer, ***@***.***>
wrote:

> please make commits against master
>
> If you look at the PR message, you will see that I also made a PR against
master.

**Comment by tomprince** [comment]
I've updated this to use the cherry-picked 427912ea93fc9f4025b2565171389b89588a0c1e.

**Comment by tomprince** [comment]
> I've updated this to use the cherry-picked [427912e](https://github.com/NixOS/nixpkgs/commit/427912ea93fc9f4025b2565171389b89588a0c1e).

(Now with all the commits, and the fixes necessary for 21.11 as opposed to master)

**Comment by tomprince** [comment]
Ping @jonringer

**Review by jonringer — APPROVED** [review]
LGTM

**Pull request merged**
