### PR TITLE
podman: add darwin wrapper and wrap gvproxy

### PR DESCRIPTION
**Pull request by zowoq**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Waiting for the coreos vm image to update as it needs to be compatible.

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by willcohen** [comment]
Note: https://github.com/NixOS/nixpkgs/pull/162243 will fix qemu on darwin, which I assume is one missing piece toward getting this working.

**Comment by zowoq** [comment]
> Note: https://github.com/NixOS/nixpkgs/pull/162243 will fix qemu on darwin, which I assume is one missing piece toward getting this working.

No, not related.

**Comment by willcohen** [comment]
Really? I've tested this PR on top of #162243 and can confirm that with these changes podman machine can now mount a volume on macOS, which requires 9p on mac + a working gvproxy. 

```
$ podman machine init --volume /Users/yourusername:/mnt/yourusername
$ podman machine start
$ podman machine ssh
$ cd /mnt/yourusername
$ ls
```

**Comment by zowoq** [comment]
> Really?

Yes. From the top post:

> Waiting for the coreos vm image to update as it needs to be compatible.

(which apparently it has sometime in the last couple of days as you have a working vm)

9p is nice to have but it doesn't have any relevance to this PR.

**Comment by willcohen** [comment]
Got it, sorry. Well, let me know if there's anything else this draft PR needs testing/help with!

**Review by willcohen — APPROVED** [review]

**Comment by willcohen** [comment]
As a quick note, the CoreOS version I've got running on my `podman machine` built today is `Fedora CoreOS 35.20220225.dev.0`

**Comment by willcohen** [comment]
Result of `nixpkgs-review pr 161130` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>podman</li>
  </ul>
</details>

**Comment by zowoq** [comment]
@ofborg eval

**Comment by willcohen** [comment]
Many thanks!

**Comment by Necoro** [comment]
@zowoq Sorry to resurrect such an old (and closed) PR: Do you recall whether it was deliberate to include `pkgs.gvproxy` unconditionally? The original patch (#157134) put it behind a `lib.optionals stdenv.isDarwin`

**Comment by zowoq** [comment]
Yes, it was deliberate. It may not be a common use case but podman machine can still be used on linux.

**Pull request merged**
