### PR TITLE
llvmPackages.libcxx: unset _LIBCPP_USE_AVAILABILITY_APPLE

### PR DESCRIPTION
**Pull request by veprbl**
Should fix a common regression from #126411
Can go to staging or staging-next depending on how fast this can be reviewed, or whether we have time for a quick darwin stdenv rebuild.
cc #148396

### CODE REVIEW

**Comment by vcunat** [comment]
(I generally know almost nothing about Apple-specific stuff.)

**Comment by veprbl** [comment]
> (I generally know almost nothing about Apple-specific stuff.)

I don't think many of us feel like they do :) In this instance I was pinging you because: you are watching over the staging-next regressions. Also I need help deciding where this change should go this or next staging iteration, and you probably have a better idea about timeline and amount of acceptable breakages for this.

**Comment by vcunat** [comment]
I'm not sure how bad these issues are.  Hydra isn't very busy now, but the current `staging-next` has been running for relatively long time (over two weeks) and full `x86_64-darwin` rebuild would surely add at least several days.

**Comment by risicle** [comment]
(am attempting to build the packages which have had their tweaks removed...)

**Comment by veprbl** [comment]
Result of `nixpkgs-review pr 151151` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>nix</li>
  </ul>
</details>

**Comment by risicle** [comment]
Not entirely sure how it's related but I get:

```
builder for '/nix/store/sfjsywkwvyfhc4dbvmm3fwllajl1l7c3-automake-1.16.5.drv' failed with exit code 2; last 10 log lines:
    GEN      doc/aclocal.1
    GEN      lib/Automake/Config.pm
    GEN      runtest
    GEN      t/ax/cc-no-c-o
    GEN      t/ax/shell-no-trail-bslash
    GEN      t/ax/test-defs.sh
    GEN      doc/automake-1.16.1
  help2man: can't get `--help' info from automake-1.16
  Try `--no-discard-stderr' if option outputs to stderr
  make: *** [Makefile:3743: doc/automake-1.16.1] Error 127
```

on macos 10.15

**Comment by veprbl** [comment]
@risicle I think saw this error on x86_64-linux recently. Although I don't remember what that was about, could be that I just worked it around by enabling sandboxing.

**Comment by veprbl** [comment]
Let's pull the trigger on this. The issue affects compilation with never standards, so users will definitely be affected if we don't fix it now.

**Pull request merged**
