### PR TITLE
[20.09] pidgin-skypeweb: 1.6 -> 1.7

### PR DESCRIPTION
**Pull request by lzmartinico**
###### Motivation for this change
backport of #97232 
(cherry picked from commit 3aafbb6498badc83efd26b4864d86c74aed1f9a5)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
fixes connection with skype.

**Comment by Mic92** [comment]
@dasJ for nix-review

**Comment by dasJ** [comment]
Result of `nixpkgs-review pr 99720` [1](https://github.com/Mic92/nixpkgs-review)

**Comment by mweinelt** [comment]
Unfortunately NixOS 20.09 has reached its end-of-life status on 2021-07-01, one
month after the release of NixOS 21.05.

Since we do not accept any changes to its branches anymore, I'm closing this pull
request.

**Pull request closed without merging**
