### PR TITLE
python3Packages.azure*: bump

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
closes: #109467
closes: #109468

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
```
https://github.com/NixOS/nixpkgs/pull/109473

20 packages built:
appdaemon azure-cli dvc-with-remotes python37Packages.azure-mgmt-loganalytics python37Packages.azure-mgmt-monitor python37Packages.azure-servicebus python37Packages.azure-storage-blob python37Packages.azure-storage-file-share python37Packages.snowflake-connector-python python37Packages.snowflake-sqlalchemy python37Packages.uamqp python38Packages.azure-mgmt-loganalytics python38Packages.azure-mgmt-monitor python38Packages.azure-servicebus python38Packages.azure-storage-blob python38Packages.azure-storage-file-share python38Packages.snowflake-connector-python python38Packages.snowflake-sqlalchemy python38Packages.uamqp python39Packages.uamqp
```

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109473` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
20 packages built:
</summary>
<ul>
<li>appdaemon</li>
<li>azure-cli</li>
<li>dvc-with-remotes</li>
<li>python37Packages.azure-mgmt-loganalytics</li>
<li>python37Packages.azure-mgmt-monitor</li>
<li>python37Packages.azure-servicebus</li>
<li>python37Packages.azure-storage-blob</li>
<li>python37Packages.azure-storage-file-share</li>
<li>python37Packages.snowflake-connector-python</li>
<li>python37Packages.snowflake-sqlalchemy</li>
<li>python37Packages.uamqp</li>
<li>python38Packages.azure-mgmt-loganalytics</li>
<li>python38Packages.azure-mgmt-monitor</li>
<li>python38Packages.azure-servicebus</li>
<li>python38Packages.azure-storage-blob</li>
<li>python38Packages.azure-storage-file-share</li>
<li>python38Packages.snowflake-connector-python</li>
<li>python38Packages.snowflake-sqlalchemy</li>
<li>python38Packages.uamqp</li>
<li>python39Packages.uamqp</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109473` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
7 packages marked as broken and skipped:
</summary>
<ul>
<li>python39Packages.azure-mgmt-loganalytics</li>
<li>python39Packages.azure-mgmt-monitor</li>
<li>python39Packages.azure-servicebus</li>
<li>python39Packages.azure-storage-blob</li>
<li>python39Packages.azure-storage-file-share</li>
<li>python39Packages.snowflake-connector-python</li>
<li>python39Packages.snowflake-sqlalchemy</li>
</ul>
</details>
<details>

  <summary>5 packages failed to build and are new build failures:</summary>
  <ul>
<li>python37Packages.azure-servicebus: log was empty</li>
<li>python37Packages.uamqp: log <a href="https://termbin.com/o7e2">https://termbin.com/o7e2</a></li>
<li>python38Packages.azure-servicebus: log was empty</li>
<li>python38Packages.uamqp: log <a href="https://termbin.com/r2i5">https://termbin.com/r2i5</a></li>
<li>python39Packages.uamqp: log <a href="https://termbin.com/fm1h">https://termbin.com/fm1h</a></li>
  </ul>
</details>
<details>
<summary>
15 packages built:
</summary>
<ul>
<li>appdaemon</li>
<li>azure-cli</li>
<li>dvc-with-remotes</li>
<li>python37Packages.azure-mgmt-loganalytics</li>
<li>python37Packages.azure-mgmt-monitor</li>
<li>python37Packages.azure-storage-blob</li>
<li>python37Packages.azure-storage-file-share</li>
<li>python37Packages.snowflake-connector-python</li>
<li>python37Packages.snowflake-sqlalchemy</li>
<li>python38Packages.azure-mgmt-loganalytics</li>
<li>python38Packages.azure-mgmt-monitor</li>
<li>python38Packages.azure-storage-blob</li>
<li>python38Packages.azure-storage-file-share</li>
<li>python38Packages.snowflake-connector-python</li>
<li>python38Packages.snowflake-sqlalchemy</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
@jonringer Should I fix the darwin issues in a separate PR?

**Comment by jonringer** [comment]
yes please :)

**Comment by jonringer** [comment]
looks like darwin just need `darwin.CF`?

**Comment by jonringer** [comment]
actually, it might need other fixes, if you could please do the fixes in another PR, that would be great :)

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109473` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
7 packages marked as broken and skipped:
</summary>
<ul>
<li>python39Packages.azure-mgmt-loganalytics</li>
<li>python39Packages.azure-mgmt-monitor</li>
<li>python39Packages.azure-servicebus</li>
<li>python39Packages.azure-storage-blob</li>
<li>python39Packages.azure-storage-file-share</li>
<li>python39Packages.snowflake-connector-python</li>
<li>python39Packages.snowflake-sqlalchemy</li>
</ul>
</details>
<details>

  <summary>5 packages failed to build and are new build failures:</summary>
  <ul>
<li>python37Packages.azure-servicebus: log was empty</li>
<li>python37Packages.uamqp: log <a href="https://termbin.com/bwiu">https://termbin.com/bwiu</a></li>
<li>python38Packages.azure-servicebus: log was empty</li>
<li>python38Packages.uamqp: log <a href="https://termbin.com/xexa">https://termbin.com/xexa</a></li>
<li>python39Packages.uamqp: log <a href="https://termbin.com/4dgu">https://termbin.com/4dgu</a></li>
  </ul>
</details>
<details>
<summary>
15 packages built:
</summary>
<ul>
<li>appdaemon</li>
<li>azure-cli</li>
<li>dvc-with-remotes</li>
<li>python37Packages.azure-mgmt-loganalytics</li>
<li>python37Packages.azure-mgmt-monitor</li>
<li>python37Packages.azure-storage-blob</li>
<li>python37Packages.azure-storage-file-share</li>
<li>python37Packages.snowflake-connector-python</li>
<li>python37Packages.snowflake-sqlalchemy</li>
<li>python38Packages.azure-mgmt-loganalytics</li>
<li>python38Packages.azure-mgmt-monitor</li>
<li>python38Packages.azure-storage-blob</li>
<li>python38Packages.azure-storage-file-share</li>
<li>python38Packages.snowflake-connector-python</li>
<li>python38Packages.snowflake-sqlalchemy</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
> actually, it might need other fixes, if you could please do the fixes in another PR, that would be great :)

It does and it wasn't as easy as I first thought.

**Comment by SuperSandro2000** [comment]
@jonringer You owe me something. It took me way to long to fix it.

**Comment by jonringer** [comment]
looks like it,wasn't expecting a patch to be needed.

I already owe for all the reviews you've been doing :)

**Pull request merged**
