### PR TITLE
xen: add v 4.10

### PR DESCRIPTION
**Pull request by xeji**
###### Motivation for this change

Would like to experiment with latest xen version (in particular, try to enable xen-uefi boot in NixOS - which appears to require xen >= 4.9).
This change only adds xen 4.10. It does not modify the other versions (4.5 and 4.8) and leaves the default at 4.5 to prevent breaking existing installations.

###### Current Status

- xen_4_10-vanilla, -light and -slim build
- hypervisor and dom0 boot in a vm
- oxenstored fails to start (caused by missing config file)

###### Things done

- [x] fix broken version check in generic.nix (previous string comparison broke with 4.10)
- [x] bump versions
- [x] add relevant xsa patches for 4.10
- [x] fix broken build of xen_4_10-vanilla

###### Things to do

- [ ] test, test, test

---

/CC xen maintainers: @edolstra  @oxij  @tstrobel

### CODE REVIEW

**Comment by oxij** [comment]
Thanks! Will test.

I also think we should switch the default from 4.5 to 4.8 as soon as I fix 4.8 build, gcc update broke it again :(

**Comment by xeji** [comment]
I agree that 4.5 should be deprecated since security support ended in January.

**Comment by xeji** [comment]
now all 3 versions (-vanilla, -slim, -light) build. Still needs testing.

**Comment by xeji** [comment]
@oxij regarding xen 4.8, I believe this will fix the gcc7 build error: https://xenbits.xen.org/gitweb/?p=xen.git;a=commit;h=f49fa658b53580cf2ad354d2bf1796766cc11222

**Comment by oxij** [comment]
May I kindly ask you to fetchpatch it into the 4.8 expression and to check it compiles? My computational resources are busy with libpulseaudio/pressureaudio/cardiacarrest mass-rebuild ATM.

**Comment by xeji** [comment]
sure, will do and let you know/

**Comment by xeji** [comment]
4.8: we're on the right track. Patch fixed previous error but no a similar error occurs in another place. I'll keep picking patches and open a separate PR when it works

**Comment by xeji** [comment]
rebased on master

**Comment by xeji** [comment]
4.10 works now. Tested in a VM with no obvious problems. Could use some more testing (maybe on real hardware) to make sure it's ready to merge.

**Comment by 7c6f434c** [comment]
From a glance, it looks like it doesn't change 4.8. If it is a pure addition, maybe it should be just merged? Or maybe @oxij wants to test it on real hardware…

**Comment by oxij** [comment]
I'm rebuilding everything the 6th time with libcardiacarrest... So not yet.
I will test it eventually, but if it boots I say it should be merged now.

I would squash (and remove [WIP]) 7a3b1949fdc, bf9426cb6e2, and c4dd6904cee into a single commit, though.
And then maybe I'd repeat that for 387ef24572f and f1541f1475a too.

**Comment by xeji** [comment]
Sounds good. I'll clean up the commits first, then we can merge.

**Comment by xeji** [comment]
Ready to merge.

**Comment by oxij** [comment]
LGTM. Thanks!

**Pull request merged**
