### PR TITLE
Fix emacs-24.5 build on OS X

### LINKED ISSUE #12863: emacs-24.5 macport build fails on OS X
Here is the failure:

```shell
Finding pointers to doc strings...
Finding pointers to doc strings...done
Dumping under the name emacs
unexec: not enough room for load commands for new __DATA segments (increase headerpad_extra in configure.in to at least 11B8)
--- List of All Regions ---
   address     size prot maxp
--- List of Regions to be Dumped ---
   address     size prot maxp
--- Header Information ---
Magic = 0xfeedfacf
CPUType = 16777223
CPUSubType = -2147483645
...
Writing unknown           command
Writing LC_FUNCTION_STARTS command
Writing LC_DATA_IN_CODE   command
Makefile:826: recipe for target 'bootstrap-emacs' failed
make[1]: *** [bootstrap-emacs] Error 1
make[1]: Leaving directory '/private/var/folders/h_/2t30cxtx7pg0b_nrzk0zdx9w0000gn/T/nix-build-emacs-24.5-mac-5.15.drv-0/emacs-24.5/src'
Makefile:393: recipe for target 'src' failed
make: *** [src] Error 2
builder for ‘/nix/store/7kn1xip1qq97s94r24lm7a1qn0gjpjv1-emacs-24.5-mac-5.15.drv’ failed with exit code 2
cannot build derivation ‘/nix/store/k7lrxvip7nvrnqa9zxpzcnjdxwiwicfn-emacs-env.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/d40v8qjs87chpsbq61pjlc8hwnb3rsdl-exceptions-0.8.2.1.tar.gz’
cannot build derivation ‘/nix/store/8rjws9lnsnvsi5ajg3317jhll51dr4qi-hindent-4.6.1.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/vzmbd4xli7n09g8p4r3g8idgdp76g6qd-structured-haskell-mode-1.0.20.drv’: 1 dependencies couldn't be built
killing process 84549
cannot build derivation ‘/nix/store/dng0sh0514gbnwg9703y4lkngyjfzn7y-meta-env.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/dng0sh0514gbnwg9703y4lkngyjfzn7y-meta-env.drv’ failed
```

This is a common problem with Emacs on the Mac and can be fixed by adding `"-headerpad_max_install_names"` to NIX_CLFAGS_LINK. I'll submit a PR.

### PR DESCRIPTION
**Pull request by dhess**
Fixes #12863.

(This might strictly only be necessary for the macports build as that's the one I use.)

### CODE REVIEW

**Comment by copumpkin** [comment]
cc @jwiegley @gridaphobe

**Comment by gridaphobe** [comment]
Both `emacs24` and `emacs24Macport` build (and run!) for me. :+1:

**Comment by dhess** [comment]
@gridaphobe Do you mean it builds for you without the patch?

**Comment by gridaphobe** [comment]
I didn't test without the patch, but `emacs24Macport` hasn't worked in ages. (IIRC it used to compile but then fail to start)

**Comment by dhess** [comment]
Ahh, ok, thanks for the clarification!

**Comment by copumpkin** [comment]
Basically, you might be the savior of many a Darwin nix user!

**Comment by copumpkin** [comment]
Can one of you emacs experts examine the failure in Travis and tell me if it's real or not? If not, I'll just press merge and @jwiegley can later bask in the glory of a working darwin emacs in the public binary cache.

**Comment by copumpkin** [comment]
@dhess also, looking at your fix, I'm curious how it works and/or how you figured it out. Care to outline your discovery process while you're at it, and perhaps put a little comment next to it explaining why it's there? I'm fearful that 2 years from now, someone will see no point for it and take it out.

**Comment by jwiegley** [comment]
I don't see how this will fix the problem I've been having of emacs24Macport exiting within a minute after startup.  Does it continue working for you, @dhess?

**Comment by gridaphobe** [comment]
I don't see why it would fix the problem either, but i've been running `emacs24Macport` with this patch since yesterday morning and haven't had any problems :/

**Comment by dhess** [comment]
Hold on, people are reading too much into this pull request.

If you refer back to the bug I filed (#12863), you'll see that I only reported a build failure for emacs24Macport. The problem is this:

`unexec: not enough room for load commands for new __DATA segments (increase headerpad_extra in configure.in to at least 11B8)`

A [quick Google search](https://www.google.com/#q=unexec+not+enough+room+for+load+commands+os+x) shows that this is a common problem building Emacs on OS X (irrespective of the Macport patches) and is easily fixed by increasing headerpad_extra at link time.

All this pull request claims to do is fix that build problem. I didn't claim that it makes emacs24Macport work for those for whom it didn't previously work, so if you're wondering how I did that or what my process was for debugging that -- I didn't and there was none!

---

As for actually running emacs24Macport, I've been using it successfully (more or less) since I started using Nixpkgs on my Mac. Sometime in the last 2 or 3 months, it started crashing occasionally (but not always) immediately after launch. If I recall correctly, this was sometime around the time when I started using `build-use-chroot`, on 2015-10-30, according to my git logs.

I stopped using `build-use-chroot` on 2015-12-26 and have not re-enabled it since. I was having lots of problems building things, and I seem to recall vaguely that emacs24Macport started crashing more frequently after launch, but I can't be sure about that.

Meanwhile, emacs24Macport works well enough for me in practice to continue using it daily. It's my main Nix/Haskell development environment and it runs for days on end with no issues. The only time it crashes is when I launch it and then shortly thereafter I switch to another Space for a bit. Sometimes when I come back to the Emacs Space, it's gone.

My work-around is just to start using it immediately, say by loading up a Haskell source file and launching the Haskell Mode REPL. Then it runs like a champ, even after I switch Spaces, until I quit it manually.

But this pull request has nothing to do with emacs24Macport's run-time issues, and if the fix here actually makes emacs24Macport work for @gridaphobe, I have no idea why that would be the case.

**Comment by dhess** [comment]
@copumpkin I added a comment explaining the reason for the change, as requested.

**Comment by gridaphobe** [comment]
Oh I see, I haven't been using `build-use-chroot` lately either. Sorry for the confusion!

**Comment by joachifm** [comment]
Is this patch still relevant/good to integrate? I would propose maybe squashing the commits first, however.

**Comment by joachifm** [comment]
As far as I can tell, emacs is building on darwin per Hydra.

**Comment by dhess** [comment]
Just a few days ago I had `macport-24.5` from master fail with this exact same issue. It appears to be somewhat random as `macport-24.5` was building fine without it before that and I don't think that the base Emacs or the macport patches changed in the interim.

I understand that, in general, maintainers want to understand an issue before they apply a fix for it. However, in this case, I don't think that concern applies. If you Google the error message in the problem report, you'll see that it affects people all the time with Emacs on OS X; not just on Nix and not just with the macport patches, either. I don't know why it happens sometimes and others not. I don't think anyone from the Emacs team has ever gotten to the bottom of it, either, so I doubt any of us will -- the Emacs build process has its own strange and horrible way of creating an executable, a legacy from its Lisp heritage. 

There is even a precedent here for Nixpkgs: if you grep the Nixpkgs source tree, you'll see this link flag littered throughout as other OS X packages have had a similar issue. In fact, it's used by default for linking all Haskell-based shared executables on OS X.

It doesn't hurt to add the flag, in any case -- it doesn't affect code generation or other behavior. It adds maybe a few extra Kbytes in the executable header. 

So if I were you, I'd just apply the patch and be done with it. But I got tired of waiting for the Nixpkgs team to integrate this and am maintaining my own `nixpkgs` fork with this fix now, so you can do whatever you think is best.

p.s. When I submitted this patch, I thought that patching `emacs-24/default.nix` was sufficient, but in fact, you also need to apply it to `macport-24.5.nix`.

**Comment by the-kenny** [comment]
What's the current status of this PR? In the meantime `emacs-25.1` was released.

**Comment by dhess** [comment]
This PR is now irrelevant.

**Pull request closed without merging**
