### PR TITLE
texinfo: fix for the new perl

### PR DESCRIPTION
**Pull request by oxij**
###### Motivation for this change

Two `perl` versions are a bit too much.

###### Things done

- [X] It builds and passes its own tests.
- [X] Saves a bunch of space.

<strike>I think this should be stable enough for staging-next.</strike> Added a hack to prevent mass-rebuild, rebased onto master.

/cc @vcunat

### CODE REVIEW

**Comment by oxij** [comment]
Added a hack to prevent mass-rebuild, rebased onto master.

Why OfBorg thinks I added a new package I have no idea.

**Comment by xeji** [comment]
Cool hack :+1:   Let's try the darwin build as well:
@GrahamcOfBorg build texinfo texinfoInteractive

**Review by vcunat — APPROVED** [review]
Patches taken from upstream, low impact if this package breaks for some reason.

**Comment by vcunat** [comment]
I didn't know _this_ hack.  Usually I use `null` attribute _values_ (instead of `null` attribute names).

**Pull request merged**
