### PR TITLE
python311Packages.textual: refactor

### PR DESCRIPTION
**Pull request by fabaff**
Changelog: https://github.com/tree-sitter/py-tree-sitter/releases/tag/v0.21.0

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 296248` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>textual-paint</li>
    <li>textual-paint.dist</li>
    <li>tftui</li>
    <li>tftui.dist</li>
    <li>upiano</li>
    <li>upiano.dist</li>
  </ul>
</details>
<details>
  <summary>74 packages built:</summary>
  <ul>
    <li>browsr</li>
    <li>browsr.dist</li>
    <li>dooit</li>
    <li>dooit.dist</li>
    <li>frogmouth</li>
    <li>frogmouth.dist</li>
    <li>oterm</li>
    <li>oterm.dist</li>
    <li>python311Packages.clarifai</li>
    <li>python311Packages.clarifai.dist</li>
    <li>python311Packages.llama-index</li>
    <li>python311Packages.llama-index-agent-openai</li>
    <li>python311Packages.llama-index-agent-openai.dist</li>
    <li>python311Packages.llama-index-cli</li>
    <li>python311Packages.llama-index-cli.dist</li>
    <li>python311Packages.llama-index-core</li>
    <li>python311Packages.llama-index-core.dist</li>
    <li>python311Packages.llama-index-embeddings-gemini</li>
    <li>python311Packages.llama-index-embeddings-gemini.dist</li>
    <li>python311Packages.llama-index-embeddings-google</li>
    <li>python311Packages.llama-index-embeddings-google.dist</li>
    <li>python311Packages.llama-index-embeddings-openai</li>
    <li>python311Packages.llama-index-embeddings-openai.dist</li>
    <li>python311Packages.llama-index-indices-managed-llama-cloud</li>
    <li>python311Packages.llama-index-indices-managed-llama-cloud.dist</li>
    <li>python311Packages.llama-index-legacy</li>
    <li>python311Packages.llama-index-legacy.dist</li>
    <li>python311Packages.llama-index-llms-openai</li>
    <li>python311Packages.llama-index-llms-openai.dist</li>
    <li>python311Packages.llama-index-multi-modal-llms-openai</li>
    <li>python311Packages.llama-index-multi-modal-llms-openai.dist</li>
    <li>python311Packages.llama-index-program-openai</li>
    <li>python311Packages.llama-index-program-openai.dist</li>
    <li>python311Packages.llama-index-question-gen-openai</li>
    <li>python311Packages.llama-index-question-gen-openai.dist</li>
    <li>python311Packages.llama-index-readers-file</li>
    <li>python311Packages.llama-index-readers-file.dist</li>
    <li>python311Packages.llama-index-readers-json</li>
    <li>python311Packages.llama-index-readers-json.dist</li>
    <li>python311Packages.llama-index-readers-llama-parse</li>
    <li>python311Packages.llama-index-readers-llama-parse.dist</li>
    <li>python311Packages.llama-index-readers-weather</li>
    <li>python311Packages.llama-index-readers-weather.dist</li>
    <li>python311Packages.llama-index-vector-stores-chroma</li>
    <li>python311Packages.llama-index-vector-stores-chroma.dist</li>
    <li>python311Packages.llama-index.dist</li>
    <li>python311Packages.llama-parse</li>
    <li>python311Packages.llama-parse.dist</li>
    <li>python311Packages.manifestoo</li>
    <li>python311Packages.manifestoo.dist</li>
    <li>python311Packages.pytest-textual-snapshot</li>
    <li>python311Packages.pytest-textual-snapshot.dist</li>
    <li>python311Packages.textual</li>
    <li>python311Packages.textual-dev</li>
    <li>python311Packages.textual-dev.dist</li>
    <li>python311Packages.textual-universal-directorytree</li>
    <li>python311Packages.textual-universal-directorytree.dist</li>
    <li>python311Packages.textual.dist</li>
    <li>python311Packages.tree-sitter</li>
    <li>python311Packages.tree-sitter.dist</li>
    <li>python312Packages.manifestoo</li>
    <li>python312Packages.manifestoo.dist</li>
    <li>python312Packages.pytest-textual-snapshot</li>
    <li>python312Packages.pytest-textual-snapshot.dist</li>
    <li>python312Packages.textual</li>
    <li>python312Packages.textual-dev</li>
    <li>python312Packages.textual-dev.dist</li>
    <li>python312Packages.textual-universal-directorytree</li>
    <li>python312Packages.textual-universal-directorytree.dist</li>
    <li>python312Packages.textual.dist</li>
    <li>python312Packages.tree-sitter</li>
    <li>python312Packages.tree-sitter.dist</li>
    <li>zeekscript</li>
    <li>zeekscript.dist</li>
  </ul>
</details>

**Comment by fabaff** [comment]
@ofborg eval

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 296248` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>textual-paint</li>
    <li>textual-paint.dist</li>
    <li>tftui</li>
    <li>tftui.dist</li>
    <li>upiano</li>
    <li>upiano.dist</li>
  </ul>
</details>
<details>
  <summary>78 packages built:</summary>
  <ul>
    <li>browsr</li>
    <li>browsr.dist</li>
    <li>dooit</li>
    <li>dooit.dist</li>
    <li>frogmouth</li>
    <li>frogmouth.dist</li>
    <li>oterm</li>
    <li>oterm.dist</li>
    <li>python311Packages.clarifai</li>
    <li>python311Packages.clarifai.dist</li>
    <li>python311Packages.llama-index</li>
    <li>python311Packages.llama-index-agent-openai</li>
    <li>python311Packages.llama-index-agent-openai.dist</li>
    <li>python311Packages.llama-index-cli</li>
    <li>python311Packages.llama-index-cli.dist</li>
    <li>python311Packages.llama-index-core</li>
    <li>python311Packages.llama-index-core.dist</li>
    <li>python311Packages.llama-index-embeddings-gemini</li>
    <li>python311Packages.llama-index-embeddings-gemini.dist</li>
    <li>python311Packages.llama-index-embeddings-google</li>
    <li>python311Packages.llama-index-embeddings-google.dist</li>
    <li>python311Packages.llama-index-embeddings-openai</li>
    <li>python311Packages.llama-index-embeddings-openai.dist</li>
    <li>python311Packages.llama-index-indices-managed-llama-cloud</li>
    <li>python311Packages.llama-index-indices-managed-llama-cloud.dist</li>
    <li>python311Packages.llama-index-legacy</li>
    <li>python311Packages.llama-index-legacy.dist</li>
    <li>python311Packages.llama-index-llms-openai</li>
    <li>python311Packages.llama-index-llms-openai.dist</li>
    <li>python311Packages.llama-index-multi-modal-llms-openai</li>
    <li>python311Packages.llama-index-multi-modal-llms-openai.dist</li>
    <li>python311Packages.llama-index-program-openai</li>
    <li>python311Packages.llama-index-program-openai.dist</li>
    <li>python311Packages.llama-index-question-gen-openai</li>
    <li>python311Packages.llama-index-question-gen-openai.dist</li>
    <li>python311Packages.llama-index-readers-file</li>
    <li>python311Packages.llama-index-readers-file.dist</li>
    <li>python311Packages.llama-index-readers-json</li>
    <li>python311Packages.llama-index-readers-json.dist</li>
    <li>python311Packages.llama-index-readers-llama-parse</li>
    <li>python311Packages.llama-index-readers-llama-parse.dist</li>
    <li>python311Packages.llama-index-readers-weather</li>
    <li>python311Packages.llama-index-readers-weather.dist</li>
    <li>python311Packages.llama-index-vector-stores-chroma</li>
    <li>python311Packages.llama-index-vector-stores-chroma.dist</li>
    <li>python311Packages.llama-index.dist</li>
    <li>python311Packages.llama-parse</li>
    <li>python311Packages.llama-parse.dist</li>
    <li>python311Packages.manifestoo</li>
    <li>python311Packages.manifestoo.dist</li>
    <li>python311Packages.pytest-textual-snapshot</li>
    <li>python311Packages.pytest-textual-snapshot.dist</li>
    <li>python311Packages.textual</li>
    <li>python311Packages.textual-dev</li>
    <li>python311Packages.textual-dev.dist</li>
    <li>python311Packages.textual-universal-directorytree</li>
    <li>python311Packages.textual-universal-directorytree.dist</li>
    <li>python311Packages.textual.dist</li>
    <li>python311Packages.tree-sitter</li>
    <li>python311Packages.tree-sitter-languages</li>
    <li>python311Packages.tree-sitter-languages.dist</li>
    <li>python311Packages.tree-sitter.dist</li>
    <li>python312Packages.manifestoo</li>
    <li>python312Packages.manifestoo.dist</li>
    <li>python312Packages.pytest-textual-snapshot</li>
    <li>python312Packages.pytest-textual-snapshot.dist</li>
    <li>python312Packages.textual</li>
    <li>python312Packages.textual-dev</li>
    <li>python312Packages.textual-dev.dist</li>
    <li>python312Packages.textual-universal-directorytree</li>
    <li>python312Packages.textual-universal-directorytree.dist</li>
    <li>python312Packages.textual.dist</li>
    <li>python312Packages.tree-sitter</li>
    <li>python312Packages.tree-sitter-languages</li>
    <li>python312Packages.tree-sitter-languages.dist</li>
    <li>python312Packages.tree-sitter.dist</li>
    <li>zeekscript</li>
    <li>zeekscript.dist</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 296248` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>dooit</li>
    <li>dooit.dist</li>
    <li>oterm</li>
    <li>oterm.dist</li>
    <li>textual-paint</li>
    <li>textual-paint.dist</li>
  </ul>
</details>
<details>
  <summary>80 packages built:</summary>
  <ul>
    <li>browsr</li>
    <li>browsr.dist</li>
    <li>frogmouth</li>
    <li>frogmouth.dist</li>
    <li>python311Packages.clarifai</li>
    <li>python311Packages.clarifai.dist</li>
    <li>python311Packages.llama-index</li>
    <li>python311Packages.llama-index-agent-openai</li>
    <li>python311Packages.llama-index-agent-openai.dist</li>
    <li>python311Packages.llama-index-cli</li>
    <li>python311Packages.llama-index-cli.dist</li>
    <li>python311Packages.llama-index-core</li>
    <li>python311Packages.llama-index-core.dist</li>
    <li>python311Packages.llama-index-embeddings-gemini</li>
    <li>python311Packages.llama-index-embeddings-gemini.dist</li>
    <li>python311Packages.llama-index-embeddings-google</li>
    <li>python311Packages.llama-index-embeddings-google.dist</li>
    <li>python311Packages.llama-index-embeddings-openai</li>
    <li>python311Packages.llama-index-embeddings-openai.dist</li>
    <li>python311Packages.llama-index-indices-managed-llama-cloud</li>
    <li>python311Packages.llama-index-indices-managed-llama-cloud.dist</li>
    <li>python311Packages.llama-index-legacy</li>
    <li>python311Packages.llama-index-legacy.dist</li>
    <li>python311Packages.llama-index-llms-openai</li>
    <li>python311Packages.llama-index-llms-openai.dist</li>
    <li>python311Packages.llama-index-multi-modal-llms-openai</li>
    <li>python311Packages.llama-index-multi-modal-llms-openai.dist</li>
    <li>python311Packages.llama-index-program-openai</li>
    <li>python311Packages.llama-index-program-openai.dist</li>
    <li>python311Packages.llama-index-question-gen-openai</li>
    <li>python311Packages.llama-index-question-gen-openai.dist</li>
    <li>python311Packages.llama-index-readers-file</li>
    <li>python311Packages.llama-index-readers-file.dist</li>
    <li>python311Packages.llama-index-readers-json</li>
    <li>python311Packages.llama-index-readers-json.dist</li>
    <li>python311Packages.llama-index-readers-llama-parse</li>
    <li>python311Packages.llama-index-readers-llama-parse.dist</li>
    <li>python311Packages.llama-index-readers-weather</li>
    <li>python311Packages.llama-index-readers-weather.dist</li>
    <li>python311Packages.llama-index-vector-stores-chroma</li>
    <li>python311Packages.llama-index-vector-stores-chroma.dist</li>
    <li>python311Packages.llama-index.dist</li>
    <li>python311Packages.llama-parse</li>
    <li>python311Packages.llama-parse.dist</li>
    <li>python311Packages.manifestoo</li>
    <li>python311Packages.manifestoo.dist</li>
    <li>python311Packages.pytest-textual-snapshot</li>
    <li>python311Packages.pytest-textual-snapshot.dist</li>
    <li>python311Packages.textual</li>
    <li>python311Packages.textual-dev</li>
    <li>python311Packages.textual-dev.dist</li>
    <li>python311Packages.textual-universal-directorytree</li>
    <li>python311Packages.textual-universal-directorytree.dist</li>
    <li>python311Packages.textual.dist</li>
    <li>python311Packages.tree-sitter</li>
    <li>python311Packages.tree-sitter-languages</li>
    <li>python311Packages.tree-sitter-languages.dist</li>
    <li>python311Packages.tree-sitter.dist</li>
    <li>python312Packages.manifestoo</li>
    <li>python312Packages.manifestoo.dist</li>
    <li>python312Packages.pytest-textual-snapshot</li>
    <li>python312Packages.pytest-textual-snapshot.dist</li>
    <li>python312Packages.textual</li>
    <li>python312Packages.textual-dev</li>
    <li>python312Packages.textual-dev.dist</li>
    <li>python312Packages.textual-universal-directorytree</li>
    <li>python312Packages.textual-universal-directorytree.dist</li>
    <li>python312Packages.textual.dist</li>
    <li>python312Packages.tree-sitter</li>
    <li>python312Packages.tree-sitter-languages</li>
    <li>python312Packages.tree-sitter-languages.dist</li>
    <li>python312Packages.tree-sitter.dist</li>
    <li>rich-cli</li>
    <li>rich-cli.dist</li>
    <li>tftui</li>
    <li>tftui.dist</li>
    <li>upiano</li>
    <li>upiano.dist</li>
    <li>zeekscript</li>
    <li>zeekscript.dist</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 296248` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>textual-paint</li>
    <li>textual-paint.dist</li>
  </ul>
</details>
<details>
  <summary>88 packages built:</summary>
  <ul>
    <li>browsr</li>
    <li>browsr.dist</li>
    <li>dooit</li>
    <li>dooit.dist</li>
    <li>frogmouth</li>
    <li>frogmouth.dist</li>
    <li>oterm</li>
    <li>oterm.dist</li>
    <li>python311Packages.clarifai</li>
    <li>python311Packages.clarifai.dist</li>
    <li>python311Packages.llama-index</li>
    <li>python311Packages.llama-index-agent-openai</li>
    <li>python311Packages.llama-index-agent-openai.dist</li>
    <li>python311Packages.llama-index-cli</li>
    <li>python311Packages.llama-index-cli.dist</li>
    <li>python311Packages.llama-index-core</li>
    <li>python311Packages.llama-index-core.dist</li>
    <li>python311Packages.llama-index-embeddings-gemini</li>
    <li>python311Packages.llama-index-embeddings-gemini.dist</li>
    <li>python311Packages.llama-index-embeddings-google</li>
    <li>python311Packages.llama-index-embeddings-google.dist</li>
    <li>python311Packages.llama-index-embeddings-openai</li>
    <li>python311Packages.llama-index-embeddings-openai.dist</li>
    <li>python311Packages.llama-index-indices-managed-llama-cloud</li>
    <li>python311Packages.llama-index-indices-managed-llama-cloud.dist</li>
    <li>python311Packages.llama-index-legacy</li>
    <li>python311Packages.llama-index-legacy.dist</li>
    <li>python311Packages.llama-index-llms-openai</li>
    <li>python311Packages.llama-index-llms-openai.dist</li>
    <li>python311Packages.llama-index-multi-modal-llms-openai</li>
    <li>python311Packages.llama-index-multi-modal-llms-openai.dist</li>
    <li>python311Packages.llama-index-program-openai</li>
    <li>python311Packages.llama-index-program-openai.dist</li>
    <li>python311Packages.llama-index-question-gen-openai</li>
    <li>python311Packages.llama-index-question-gen-openai.dist</li>
    <li>python311Packages.llama-index-readers-file</li>
    <li>python311Packages.llama-index-readers-file.dist</li>
    <li>python311Packages.llama-index-readers-json</li>
    <li>python311Packages.llama-index-readers-json.dist</li>
    <li>python311Packages.llama-index-readers-llama-parse</li>
    <li>python311Packages.llama-index-readers-llama-parse.dist</li>
    <li>python311Packages.llama-index-readers-weather</li>
    <li>python311Packages.llama-index-readers-weather.dist</li>
    <li>python311Packages.llama-index-vector-stores-chroma</li>
    <li>python311Packages.llama-index-vector-stores-chroma.dist</li>
    <li>python311Packages.llama-index.dist</li>
    <li>python311Packages.llama-parse</li>
    <li>python311Packages.llama-parse.dist</li>
    <li>python311Packages.manifestoo</li>
    <li>python311Packages.manifestoo.dist</li>
    <li>python311Packages.ollama</li>
    <li>python311Packages.ollama.dist</li>
    <li>python311Packages.pytest-textual-snapshot</li>
    <li>python311Packages.pytest-textual-snapshot.dist</li>
    <li>python311Packages.textual</li>
    <li>python311Packages.textual-dev</li>
    <li>python311Packages.textual-dev.dist</li>
    <li>python311Packages.textual-universal-directorytree</li>
    <li>python311Packages.textual-universal-directorytree.dist</li>
    <li>python311Packages.textual.dist</li>
    <li>python311Packages.tree-sitter</li>
    <li>python311Packages.tree-sitter-languages</li>
    <li>python311Packages.tree-sitter-languages.dist</li>
    <li>python311Packages.tree-sitter.dist</li>
    <li>python312Packages.manifestoo</li>
    <li>python312Packages.manifestoo.dist</li>
    <li>python312Packages.ollama</li>
    <li>python312Packages.ollama.dist</li>
    <li>python312Packages.pytest-textual-snapshot</li>
    <li>python312Packages.pytest-textual-snapshot.dist</li>
    <li>python312Packages.textual</li>
    <li>python312Packages.textual-dev</li>
    <li>python312Packages.textual-dev.dist</li>
    <li>python312Packages.textual-universal-directorytree</li>
    <li>python312Packages.textual-universal-directorytree.dist</li>
    <li>python312Packages.textual.dist</li>
    <li>python312Packages.tree-sitter</li>
    <li>python312Packages.tree-sitter-languages</li>
    <li>python312Packages.tree-sitter-languages.dist</li>
    <li>python312Packages.tree-sitter.dist</li>
    <li>rich-cli</li>
    <li>rich-cli.dist</li>
    <li>tftui</li>
    <li>tftui.dist</li>
    <li>upiano</li>
    <li>upiano.dist</li>
    <li>zeekscript</li>
    <li>zeekscript.dist</li>
  </ul>
</details>

**Comment by fabaff** [comment]
`textual-paint` is already broken.

**Comment by khaneliman** [comment]
Result of `nixpkgs-review pr 296248` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>browsr</li>
    <li>browsr.dist</li>
    <li>python311Packages.clarifai</li>
    <li>python311Packages.clarifai.dist</li>
  </ul>
</details>
<details>
  <summary>50 packages failed to build:</summary>
  <ul>
    <li>python311Packages.llama-index</li>
    <li>python311Packages.llama-index-agent-openai</li>
    <li>python311Packages.llama-index-agent-openai.dist</li>
    <li>python311Packages.llama-index-cli</li>
    <li>python311Packages.llama-index-cli.dist</li>
    <li>python311Packages.llama-index-embeddings-gemini</li>
    <li>python311Packages.llama-index-embeddings-gemini.dist</li>
    <li>python311Packages.llama-index-embeddings-google</li>
    <li>python311Packages.llama-index-embeddings-google.dist</li>
    <li>python311Packages.llama-index-embeddings-openai</li>
    <li>python311Packages.llama-index-embeddings-openai.dist</li>
    <li>python311Packages.llama-index-indices-managed-llama-cloud</li>
    <li>python311Packages.llama-index-indices-managed-llama-cloud.dist</li>
    <li>python311Packages.llama-index-llms-openai</li>
    <li>python311Packages.llama-index-llms-openai.dist</li>
    <li>python311Packages.llama-index-multi-modal-llms-openai</li>
    <li>python311Packages.llama-index-multi-modal-llms-openai.dist</li>
    <li>python311Packages.llama-index-program-openai</li>
    <li>python311Packages.llama-index-program-openai.dist</li>
    <li>python311Packages.llama-index-question-gen-openai</li>
    <li>python311Packages.llama-index-question-gen-openai.dist</li>
    <li>python311Packages.llama-index-readers-file</li>
    <li>python311Packages.llama-index-readers-file.dist</li>
    <li>python311Packages.llama-index-readers-json</li>
    <li>python311Packages.llama-index-readers-json.dist</li>
    <li>python311Packages.llama-index-readers-llama-parse</li>
    <li>python311Packages.llama-index-readers-llama-parse.dist</li>
    <li>python311Packages.llama-index-readers-weather</li>
    <li>python311Packages.llama-index-readers-weather.dist</li>
    <li>python311Packages.llama-index-vector-stores-chroma</li>
    <li>python311Packages.llama-index-vector-stores-chroma.dist</li>
    <li>python311Packages.llama-index.dist</li>
    <li>python311Packages.llama-parse</li>
    <li>python311Packages.llama-parse.dist</li>
    <li>python312Packages.manifestoo</li>
    <li>python312Packages.manifestoo.dist</li>
    <li>python312Packages.pytest-textual-snapshot</li>
    <li>python312Packages.pytest-textual-snapshot.dist</li>
    <li>python312Packages.textual</li>
    <li>python312Packages.textual-dev</li>
    <li>python312Packages.textual-dev.dist</li>
    <li>python312Packages.textual-universal-directorytree</li>
    <li>python312Packages.textual-universal-directorytree.dist</li>
    <li>python312Packages.textual.dist</li>
    <li>python312Packages.tree-sitter</li>
    <li>python312Packages.tree-sitter-languages</li>
    <li>python312Packages.tree-sitter-languages.dist</li>
    <li>python312Packages.tree-sitter.dist</li>
    <li>textual-paint</li>
    <li>textual-paint.dist</li>
  </ul>
</details>
<details>
  <summary>36 packages built:</summary>
  <ul>
    <li>dooit</li>
    <li>dooit.dist</li>
    <li>frogmouth</li>
    <li>frogmouth.dist</li>
    <li>oterm</li>
    <li>oterm.dist</li>
    <li>python311Packages.llama-index-core</li>
    <li>python311Packages.llama-index-core.dist</li>
    <li>python311Packages.llama-index-legacy</li>
    <li>python311Packages.llama-index-legacy.dist</li>
    <li>python311Packages.manifestoo</li>
    <li>python311Packages.manifestoo.dist</li>
    <li>python311Packages.ollama</li>
    <li>python311Packages.ollama.dist</li>
    <li>python311Packages.pytest-textual-snapshot</li>
    <li>python311Packages.pytest-textual-snapshot.dist</li>
    <li>python311Packages.textual</li>
    <li>python311Packages.textual-dev</li>
    <li>python311Packages.textual-dev.dist</li>
    <li>python311Packages.textual-universal-directorytree</li>
    <li>python311Packages.textual-universal-directorytree.dist</li>
    <li>python311Packages.textual.dist</li>
    <li>python311Packages.tree-sitter</li>
    <li>python311Packages.tree-sitter-languages</li>
    <li>python311Packages.tree-sitter-languages.dist</li>
    <li>python311Packages.tree-sitter.dist</li>
    <li>python312Packages.ollama</li>
    <li>python312Packages.ollama.dist</li>
    <li>rich-cli</li>
    <li>rich-cli.dist</li>
    <li>tftui</li>
    <li>tftui.dist</li>
    <li>upiano</li>
    <li>upiano.dist</li>
    <li>zeekscript</li>
    <li>zeekscript.dist</li>
  </ul>
</details>

**Comment by khaneliman** [comment]
Result of `nixpkgs-review pr 296248` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>browsr</li>
    <li>browsr.dist</li>
    <li>python311Packages.clarifai</li>
    <li>python311Packages.clarifai.dist</li>
  </ul>
</details>
<details>
  <summary>36 packages failed to build:</summary>
  <ul>
    <li>python311Packages.llama-index</li>
    <li>python311Packages.llama-index-agent-openai</li>
    <li>python311Packages.llama-index-agent-openai.dist</li>
    <li>python311Packages.llama-index-cli</li>
    <li>python311Packages.llama-index-cli.dist</li>
    <li>python311Packages.llama-index-embeddings-gemini</li>
    <li>python311Packages.llama-index-embeddings-gemini.dist</li>
    <li>python311Packages.llama-index-embeddings-google</li>
    <li>python311Packages.llama-index-embeddings-google.dist</li>
    <li>python311Packages.llama-index-embeddings-openai</li>
    <li>python311Packages.llama-index-embeddings-openai.dist</li>
    <li>python311Packages.llama-index-indices-managed-llama-cloud</li>
    <li>python311Packages.llama-index-indices-managed-llama-cloud.dist</li>
    <li>python311Packages.llama-index-llms-openai</li>
    <li>python311Packages.llama-index-llms-openai.dist</li>
    <li>python311Packages.llama-index-multi-modal-llms-openai</li>
    <li>python311Packages.llama-index-multi-modal-llms-openai.dist</li>
    <li>python311Packages.llama-index-program-openai</li>
    <li>python311Packages.llama-index-program-openai.dist</li>
    <li>python311Packages.llama-index-question-gen-openai</li>
    <li>python311Packages.llama-index-question-gen-openai.dist</li>
    <li>python311Packages.llama-index-readers-file</li>
    <li>python311Packages.llama-index-readers-file.dist</li>
    <li>python311Packages.llama-index-readers-json</li>
    <li>python311Packages.llama-index-readers-json.dist</li>
    <li>python311Packages.llama-index-readers-llama-parse</li>
    <li>python311Packages.llama-index-readers-llama-parse.dist</li>
    <li>python311Packages.llama-index-readers-weather</li>
    <li>python311Packages.llama-index-readers-weather.dist</li>
    <li>python311Packages.llama-index-vector-stores-chroma</li>
    <li>python311Packages.llama-index-vector-stores-chroma.dist</li>
    <li>python311Packages.llama-index.dist</li>
    <li>python311Packages.llama-parse</li>
    <li>python311Packages.llama-parse.dist</li>
    <li>textual-paint</li>
    <li>textual-paint.dist</li>
  </ul>
</details>
<details>
  <summary>50 packages built:</summary>
  <ul>
    <li>dooit</li>
    <li>dooit.dist</li>
    <li>frogmouth</li>
    <li>frogmouth.dist</li>
    <li>oterm</li>
    <li>oterm.dist</li>
    <li>python311Packages.llama-index-core</li>
    <li>python311Packages.llama-index-core.dist</li>
    <li>python311Packages.llama-index-legacy</li>
    <li>python311Packages.llama-index-legacy.dist</li>
    <li>python311Packages.manifestoo</li>
    <li>python311Packages.manifestoo.dist</li>
    <li>python311Packages.ollama</li>
    <li>python311Packages.ollama.dist</li>
    <li>python311Packages.pytest-textual-snapshot</li>
    <li>python311Packages.pytest-textual-snapshot.dist</li>
    <li>python311Packages.textual</li>
    <li>python311Packages.textual-dev</li>
    <li>python311Packages.textual-dev.dist</li>
    <li>python311Packages.textual-universal-directorytree</li>
    <li>python311Packages.textual-universal-directorytree.dist</li>
    <li>python311Packages.textual.dist</li>
    <li>python311Packages.tree-sitter</li>
    <li>python311Packages.tree-sitter-languages</li>
    <li>python311Packages.tree-sitter-languages.dist</li>
    <li>python311Packages.tree-sitter.dist</li>
    <li>python312Packages.manifestoo</li>
    <li>python312Packages.manifestoo.dist</li>
    <li>python312Packages.ollama</li>
    <li>python312Packages.ollama.dist</li>
    <li>python312Packages.pytest-textual-snapshot</li>
    <li>python312Packages.pytest-textual-snapshot.dist</li>
    <li>python312Packages.textual</li>
    <li>python312Packages.textual-dev</li>
    <li>python312Packages.textual-dev.dist</li>
    <li>python312Packages.textual-universal-directorytree</li>
    <li>python312Packages.textual-universal-directorytree.dist</li>
    <li>python312Packages.textual.dist</li>
    <li>python312Packages.tree-sitter</li>
    <li>python312Packages.tree-sitter-languages</li>
    <li>python312Packages.tree-sitter-languages.dist</li>
    <li>python312Packages.tree-sitter.dist</li>
    <li>rich-cli</li>
    <li>rich-cli.dist</li>
    <li>tftui</li>
    <li>tftui.dist</li>
    <li>upiano</li>
    <li>upiano.dist</li>
    <li>zeekscript</li>
    <li>zeekscript.dist</li>
  </ul>
</details>

**Review by khaneliman — APPROVED** [review]
Dooit works for me, still. Llama packages and textual-paint both appear broken on darwin on master so can ignore those failures. Should probably just mark them broken if darwin. 

```bash
Traceback (most recent call last):
  File "/nix/store/vlyfykywav0mbfm20ra960a5ja1pf56i-python3.11-llama-index-core-0.10.18/lib/python3.11/site-packages/llama_index/core/utils.py", line 60, in __init__
    nltk.data.find("corpora/stopwords", paths=[self._nltk_data_dir])
  File "/nix/store/vr3slm4y75802y93mgxixs7v0yawk6yq-python3.11-nltk-3.8.1/lib/python3.11/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')

  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - '/nix/store/vlyfykywav0mbfm20ra960a5ja1pf56i-python3.11-llama-index-core-0.10.18/lib/python3.11/site-packages/llama_index/core/_static/nltk_cache'
**********************************************************************
```

**Comment by fabaff** [comment]
`tree-sitter-languages` doesn't contains the languages yet.

**Comment by wegank** [comment]
Partially done in #297420.

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by khaneliman** [comment]
This looks like it broke a dependency chain with treesitter-languages being limited to python 3.11 because of using `tree-sitter0_21`.

**Pull request merged**
