### PR TITLE
obsidian: add commandLineArgs

### PR DESCRIPTION
**Pull request by CrackTC**
## Description of changes
add `commandLineArgs` so that we can override some electron flags more easily 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by w-lfchen — APPROVED** [review]
other applications [seem to be doing this as well](https://github.com/search?q=repo%3ANixOS%2Fnixpkgs%20commandLineArgs&type=code), therefore i don't see any issues with adding this.
i'm unsure how useful this will be but i might be missing something here; i'd love to hear somebody else's opinion on it

**Review by kashw2 — APPROVED** [review]

**Comment by zaninime** [comment]
If the flags are electron-related, why not adding them to electron directly? An overlay that adds them once to electron would then solve the problem for all apps using it. @CrackTC can you provide an example of what you're trying to achieve?

**Comment by CrackTC** [comment]
> If the flags are electron-related, why not adding them to electron directly?

Mainly because the flags passed to electron might vary from application to application. In my use case, some apps work on wayland by passing flags like `--enable-features=UseOzonePlatform` and `--ozone-platform=wayland`. Some apps may need `--disable-gpu` to work properly, while some apps won't work on wayland at all. I'm not sure if this is the best way to do it, but imo adding an argument to specific apps is more straightforward.

**Comment by zaninime** [comment]
I'm not following too much how electron is behaving on different platforms nowadays. I find it strange that the same electron binary needs different GPU-configurations based on the (JS) app it is running. Also while this is a straightforward change to make, reverting it in the future will be a breaking one for whoever relies on it.

With that aside, did you realize the line above your change already sets `--ozone-platform=wayland` under some conditions? I would find it confusing if I'd be making an override such as:

```nix
electron.override {
  commandLineArgs = ["a" "b" "c"];
}
```

and suddently my `ps aux | grep electron` shows that also `--ozone-platform=wayland` is set. For Nix beginners this might be quite unexpected behaviour.

**Comment by CrackTC** [comment]
> I find it odd that the same electron binary needs different GPU configurations depending on the (JS) application it is running.

I noticed that some of them have a bundled electron binary, some of them use the one in nixpkgs. And you're right, obsidian is the latter, for which we can simply add flags to the shared electron binary. But wayland support is just one of the things I'm trying to achieve. There are other things I have come across that vary between application, such as scale factor and proxy related flags.

> while this is an easy change to make, undoing it in the future will be a break for anyone relying on it.

Sorry I hadn't thought of this. I'm not quite sure in which case we will undo it in the future, if electron changes certain flags we can just update the value of `commandLineArgs`. And there are applications that already use this argument, so I think it's safe to assume that they will continue to use it.

> For Nix newbies, this may be quite unexpected behaviour.

The nixos wiki mentions that we can add ozone flags to electron apps globally via `environment.sessionVariables.NIXOS_OZONE_WL = "1";`, so if someone has added this variable, they should know what they're doing. Also, in the case some apps are broken because of the presence of `NIXOS_OZONE_WL` (probably those bundled with outdated electron), we can easily opt out with the help of `commandLineArgs`.

**Review by JohnRTitor — APPROVED** [review]
LGTM, runs fine

**Comment by JohnRTitor** [comment]
Result of `nixpkgs-review pr 319539` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>obsidian</li>
  </ul>
</details>

**Pull request merged**
