### PR TITLE
nixos/acme: default to lets encrypt production URL instead of null, mention lets encrypt staging URI

### PR DESCRIPTION
**Pull request by SuperSandro2000**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by emilylange — COMMENTED** [review]
Hi, sorry for the late response.

Could you add a link to https://letsencrypt.org/docs/staging-environment/ as well, similar to
https://github.com/NixOS/nixpkgs/blob/c1f0be03736e6d5ab4d19e867e6684686203eee8/nixos/modules/services/web-servers/caddy/default.nix#L265-L268
please?

But ultimately, this isn't "my" module, so uhh

Pinging @yu-re-ka who was the last one to add a feature to this module :)

**Comment by SuperSandro2000** [comment]
> Could you add a link to letsencrypt.org/docs/staging-environment please?

Done

> But ultimately, this isn't "my" module, so uhh

I doubt that anyone has a strong ownership over such widely used and shared modules.

**Comment by yu-re-ka** [comment]
I'd prefer using the "default" and "example" documentation fields for prod and staging lets encrypt directory urls. Then just mention the existence in the description, but without writing out the urls again.

**Comment by yu-re-ka** [comment]
I don't particularly care if we or lego pick the default.
Also, it would be more accurate to set the default explicitly, since we promise the user that the Let's Encrypt production directory is the default (in the description text). Or adjust the text to say that the default of null means that the lego default is used.

**Comment by SuperSandro2000** [comment]
friendly ping

**Review by emilylange — APPROVED** [review]
Might need a release note entry since the option no longer accepts `null` as value.
But fine with me without I guess.

**Comment by yu-re-ka** [comment]
@ofborg test acme

**Comment by SuperSandro2000** [comment]
Can we merge this?

**Review by yu-re-ka — APPROVED** [review]
Yeah, sorry for blocking this so long

**Comment by Izorkin** [comment]
This PR changes `accountHash`?
If yes, then it may mess up certificate renewals if CAA records in DNS are used.

**Comment by emilylange** [comment]
@Izorkin If by `CAA` records you mean specifically `CAA` records with `accounturi`, then yes, those are broken now.

Very good catch!

Also only just noticing now, because it changes the `accountHash`, we essentially mass-renew any certificates on `nixos-rebuild switch` once while migrating to the new account directories.

Anyone against reverting this for now and maybe giving it another go in the future?

**Comment by Izorkin** [comment]
Сan add information to release notes.

**Comment by SuperSandro2000** [comment]
> Also only just noticing now, because it changes the accountHash, we essentially mass-renew any certificates on nixos-rebuild switch once while migrating to the new account directories.

Do we only renew it or request a new one? If we only renew them, I don't think that is a big issue.

> Anyone against reverting this for now and maybe giving it another go in the future?

It is already in [nixos-unstable-small](https://nixpk.gs/pr-tracker.html?pr=270221), so if we revert it now, anyone updating between now and when it lands in nixos-unstable gets this twice.

Also please if you want to do it, only revert the default value. I don't want to chase after the description change to get back in.

**Comment by emilylange** [comment]
> Do we only renew it or request a new one? If we only renew them, I don't think that is a big issue.

We create a new account in a new directory, don't renew (because that account does not have the previous certificate) and create a new certificate from scratch.

> It is already in [nixos-unstable-small](https://nixpk.gs/pr-tracker.html?pr=270221), so if we revert it now, anyone updating between now and when it lands in nixos-unstable gets this twice.

Yes, I know. Reasoning behind a potential revert was, that many users don't immediately update to the newest channel and as such, haven't encountered the new behavior yet /shrug

If no one else wants to do it, I can look into adding a release note for this and post about it in https://discourse.nixos.org/t/breaking-changes-announcement-for-unstable/17574

**Comment by SuperSandro2000** [comment]
> We create a new account in a new directory, don't renew (because that account does not have the previous certificate) and create a new certificate from scratch.

okay, thanks for the clarification

If changes of the account hash are of concern, we should probably assert it in tests/acme.nix, right?

Quickly did that in #286999 so that we notice this the next time :)

**Comment by arianvp** [comment]
> I doubt that anyone has a strong ownership over such widely used and shared modules.

Actually there is a team for this; as marked by the `meta.maintainers` field:

https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/security/acme/default.nix#L1034

There is also @NixOS/acme  team in GitHub. I'm wondering if we need more automation to make these kind of things more clear?

Does the assigning review automatically automation not work for NixOS code but only for nixpkgs code?

**Comment by mweinelt** [comment]
If you want to get review requests for non-pkgs you need to set up code ownership.

**Pull request merged**
