### PR TITLE
gtk2,gtk3: rename derivation name

### PR DESCRIPTION
**Pull request by Stunkymonkey**
## Description of changes

fixes: #57887

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by 7c6f434c — APPROVED** [review]

**Review by jtojnar — APPROVED** [review]
Including major version is redundant with the `version` attribute as well as just plain ugly. But I guess it is needed until Nix stops considering all derivations with the same `pname` portion of the `name` to be the same package.

**Comment by emilazy** [comment]
Does that `nix-env` silliness matter here? Hopefully nobody is trying to install GTK libraries globally, since it wouldn't do anything useful.

**Comment by 7c6f434c** [comment]
There are some executables in the gtk3 package, though

**Comment by emilazy** [comment]
So the issue is someone with `gtk3` installed globally with `nix-env` for `gtk-launch` or similar might get upgraded to `gtk4`? Seems marginal to me (and I believe wouldn't happen to people who already have it installed), but I suppose there is probably someone out here it'd affect.

**Comment by Stunkymonkey** [comment]
how do we continue here?

**Comment by Artturin** [comment]
Of course there are people using `gtk3.name` to get this path `/nix/store/jf8y3nz89k3hxj3r4mvlp6mccsj8hdc2-gtk+3-3.24.38/share/gsettings-schemas/gtk+3-3.24.38`

**Comment by Artturin** [comment]
Nvm `glib.getSchemaDataDirPath gtk3` won't work, it uses the name.

```
nix-repl> glib.getSchemaDataDirPath gtk3
"/nix/store/0a4brh0c0ms6mg5q9ymshc43iblkcsfb-gtk3-3.24.38/share/gsettings-schemas/gtk3-3.24.38"
```

**Comment by Artturin** [comment]
```diff
diff --git a/pkgs/development/libraries/glib/default.nix b/pkgs/development/libraries/glib/default.nix
index 8a1ba46f50eb..79d0e4d0cde2 100644
--- a/pkgs/development/libraries/glib/default.nix
+++ b/pkgs/development/libraries/glib/default.nix
@@ -249,8 +249,8 @@ stdenv.mkDerivation (finalAttrs: {
 
     makeSchemaDataDirPath = dir: name: "${dir}/share/gsettings-schemas/${name}";
     makeSchemaPath = dir: name: "${makeSchemaDataDirPath dir name}/glib-2.0/schemas";
-    getSchemaPath = pkg: makeSchemaPath pkg pkg.name;
-    getSchemaDataDirPath = pkg: makeSchemaDataDirPath pkg pkg.name;
+    getSchemaPath = pkg: makeSchemaPath pkg (pkg.schemaDirName or pkg.name);
+    getSchemaDataDirPath = pkg: makeSchemaDataDirPath pkg (pkg.schemaDirName or pkg.name);
 
     tests = {
       withChecks = finalAttrs.finalPackage.overrideAttrs (_: { doCheck = true; });
diff --git a/pkgs/development/libraries/gtk/3.x.nix b/pkgs/development/libraries/gtk/3.x.nix
index a527faf5a8be..6c0da799815c 100644
--- a/pkgs/development/libraries/gtk/3.x.nix
+++ b/pkgs/development/libraries/gtk/3.x.nix
@@ -228,6 +228,7 @@ stdenv.mkDerivation (finalAttrs: {
   '';
 
   passthru = {
+    schemaDirName = "gtk+3-${finalAttrs.version}";
     updateScript = gnome.updateScript {
       packageName = "gtk+";
       attrPath = "gtk3";
```

this would be a fix but `gtk3.name` in `--prefix XDG_DATA_DIRS : "${gtk3}/share/gsettings-schemas/${gtk3.name}/"` still remains broken and it's used out of tree a lot

**Comment by jtojnar** [comment]
The schemadirname is Nixpkgs-specific thing so it should be fine to change it.

**Pull request merged**
