### PR TITLE
python311Packages.colorlog: 6.8.0 -> 6.8.2

### PR DESCRIPTION
**Pull request by dotlambda**
## Description of changes
Changelog: https://github.com/borntyping/python-colorlog/releases/tag/v6.8.2

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by NickCao** [comment]
Result of `nixpkgs-review pr 284695` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>23 packages marked as broken and skipped:</summary>
  <ul>
    <li>home-assistant-component-tests.abode</li>
    <li>home-assistant-component-tests.comelit</li>
    <li>home-assistant-component-tests.isy994</li>
    <li>python312Packages.chat-downloader</li>
    <li>python312Packages.chat-downloader.dist</li>
    <li>python312Packages.cot</li>
    <li>python312Packages.cot.dist</li>
    <li>python312Packages.jaraco-abode</li>
    <li>python312Packages.jaraco-abode.dist</li>
    <li>python312Packages.jedi-language-server</li>
    <li>python312Packages.jedi-language-server.dist</li>
    <li>python312Packages.lsprotocol</li>
    <li>python312Packages.lsprotocol.dist</li>
    <li>python312Packages.nox</li>
    <li>python312Packages.nox.dist</li>
    <li>python312Packages.online-judge-api-client</li>
    <li>python312Packages.online-judge-api-client.dist</li>
    <li>python312Packages.online-judge-tools</li>
    <li>python312Packages.online-judge-tools.dist</li>
    <li>python312Packages.pygls</li>
    <li>python312Packages.pygls.dist</li>
    <li>python312Packages.skybellpy</li>
    <li>python312Packages.skybellpy.dist</li>
  </ul>
</details>
<details>
  <summary>8 packages failed to build:</summary>
  <ul>
    <li>apache-airflow</li>
    <li>apache-airflow.dist</li>
    <li>python311Packages.optuna</li>
    <li>python311Packages.optuna.dist</li>
    <li>python312Packages.clldutils</li>
    <li>python312Packages.clldutils.dist</li>
    <li>python312Packages.segments</li>
    <li>python312Packages.segments.dist</li>
  </ul>
</details>
<details>
  <summary>109 packages built:</summary>
  <ul>
    <li>bitbake-language-server</li>
    <li>bitbake-language-server.dist</li>
    <li>cmake-language-server</li>
    <li>cmake-language-server.dist</li>
    <li>cot (python311Packages.cot)</li>
    <li>cot.dist (python311Packages.cot.dist)</li>
    <li>errbot</li>
    <li>errbot.dist</li>
    <li>gkraken</li>
    <li>gnomeExtensions.freon</li>
    <li>liquidctl (python311Packages.liquidctl)</li>
    <li>liquidctl.dist (python311Packages.liquidctl.dist)</li>
    <li>liquidctl.man (python311Packages.liquidctl.man)</li>
    <li>octoprint</li>
    <li>octoprint.dist</li>
    <li>online-judge-template-generator</li>
    <li>online-judge-template-generator.dist</li>
    <li>online-judge-tools (python311Packages.online-judge-tools)</li>
    <li>online-judge-tools.dist (python311Packages.online-judge-tools.dist)</li>
    <li>phonemizer (python311Packages.phonemizer)</li>
    <li>phonemizer.dist (python311Packages.phonemizer.dist)</li>
    <li>python311Packages.aio-pika</li>
    <li>python311Packages.aio-pika.dist</li>
    <li>python311Packages.aiocomelit</li>
    <li>python311Packages.aiocomelit.dist</li>
    <li>python311Packages.aiofile</li>
    <li>python311Packages.aiofile.dist</li>
    <li>python311Packages.aiomisc</li>
    <li>python311Packages.aiomisc-pytest</li>
    <li>python311Packages.aiomisc-pytest.dist</li>
    <li>python311Packages.aiomisc.dist</li>
    <li>python311Packages.aiormq</li>
    <li>python311Packages.aiormq.dist</li>
    <li>python311Packages.caio</li>
    <li>python311Packages.caio.dist</li>
    <li>python311Packages.chat-downloader</li>
    <li>python311Packages.chat-downloader.dist</li>
    <li>python311Packages.clldutils</li>
    <li>python311Packages.clldutils.dist</li>
    <li>python311Packages.colorlog</li>
    <li>python311Packages.colorlog.dist</li>
    <li>python311Packages.dask-gateway-server</li>
    <li>python311Packages.dask-gateway-server.dist</li>
    <li>python311Packages.dataprep-ml</li>
    <li>python311Packages.dataprep-ml.dist</li>
    <li>python311Packages.jaraco-abode</li>
    <li>python311Packages.jaraco-abode.dist</li>
    <li>python311Packages.jedi-language-server</li>
    <li>python311Packages.jedi-language-server.dist</li>
    <li>python311Packages.lsprotocol</li>
    <li>python311Packages.lsprotocol.dist</li>
    <li>python311Packages.lupupy</li>
    <li>python311Packages.lupupy.dist</li>
    <li>python311Packages.mindsdb-evaluator</li>
    <li>python311Packages.mindsdb-evaluator.dist</li>
    <li>python311Packages.nox</li>
    <li>python311Packages.nox.dist</li>
    <li>python311Packages.online-judge-api-client</li>
    <li>python311Packages.online-judge-api-client.dist</li>
    <li>python311Packages.pyenvisalink</li>
    <li>python311Packages.pyenvisalink.dist</li>
    <li>python311Packages.pygls</li>
    <li>python311Packages.pygls.dist</li>
    <li>python311Packages.pyisy</li>
    <li>python311Packages.pyisy.dist</li>
    <li>python311Packages.pypca</li>
    <li>python311Packages.pypca.dist</li>
    <li>python311Packages.pysim</li>
    <li>python311Packages.pysim.dist</li>
    <li>python311Packages.python-lsp-ruff</li>
    <li>python311Packages.python-lsp-ruff.dist</li>
    <li>python311Packages.riscof</li>
    <li>python311Packages.riscof.dist</li>
    <li>python311Packages.riscv-isac</li>
    <li>python311Packages.riscv-isac.dist</li>
    <li>python311Packages.segments</li>
    <li>python311Packages.segments.dist</li>
    <li>python311Packages.skybellpy</li>
    <li>python311Packages.skybellpy.dist</li>
    <li>python311Packages.type-infer</li>
    <li>python311Packages.type-infer.dist</li>
    <li>python312Packages.aio-pika</li>
    <li>python312Packages.aio-pika.dist</li>
    <li>python312Packages.aiomisc</li>
    <li>python312Packages.aiomisc-pytest</li>
    <li>python312Packages.aiomisc-pytest.dist</li>
    <li>python312Packages.aiomisc.dist</li>
    <li>python312Packages.aiormq</li>
    <li>python312Packages.aiormq.dist</li>
    <li>python312Packages.colorlog</li>
    <li>python312Packages.colorlog.dist</li>
    <li>python312Packages.liquidctl</li>
    <li>python312Packages.liquidctl.dist</li>
    <li>python312Packages.liquidctl.man</li>
    <li>python312Packages.lupupy</li>
    <li>python312Packages.lupupy.dist</li>
    <li>python312Packages.pyenvisalink</li>
    <li>python312Packages.pyenvisalink.dist</li>
    <li>python312Packages.pypca</li>
    <li>python312Packages.pypca.dist</li>
    <li>rapid-photo-downloader</li>
    <li>rapid-photo-downloader.dist</li>
    <li>ruff-lsp</li>
    <li>ruff-lsp.dist</li>
    <li>sbomnix</li>
    <li>sbomnix.dist</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vscode-extensions.ms-python.python</li>
    <li>ycmd</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 284695` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>20 packages marked as broken and skipped:</summary>
  <ul>
    <li>python312Packages.chat-downloader</li>
    <li>python312Packages.chat-downloader.dist</li>
    <li>python312Packages.cot</li>
    <li>python312Packages.cot.dist</li>
    <li>python312Packages.jaraco-abode</li>
    <li>python312Packages.jaraco-abode.dist</li>
    <li>python312Packages.jedi-language-server</li>
    <li>python312Packages.jedi-language-server.dist</li>
    <li>python312Packages.lsprotocol</li>
    <li>python312Packages.lsprotocol.dist</li>
    <li>python312Packages.nox</li>
    <li>python312Packages.nox.dist</li>
    <li>python312Packages.online-judge-api-client</li>
    <li>python312Packages.online-judge-api-client.dist</li>
    <li>python312Packages.online-judge-tools</li>
    <li>python312Packages.online-judge-tools.dist</li>
    <li>python312Packages.pygls</li>
    <li>python312Packages.pygls.dist</li>
    <li>python312Packages.skybellpy</li>
    <li>python312Packages.skybellpy.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>apache-airflow</li>
    <li>apache-airflow.dist</li>
    <li>python312Packages.segments</li>
    <li>python312Packages.segments.dist</li>
  </ul>
</details>
<details>
  <summary>116 packages built:</summary>
  <ul>
    <li>bitbake-language-server</li>
    <li>bitbake-language-server.dist</li>
    <li>cmake-language-server</li>
    <li>cmake-language-server.dist</li>
    <li>cot (python311Packages.cot)</li>
    <li>cot.dist (python311Packages.cot.dist)</li>
    <li>errbot</li>
    <li>errbot.dist</li>
    <li>gkraken</li>
    <li>gnomeExtensions.freon</li>
    <li>home-assistant-component-tests.abode</li>
    <li>home-assistant-component-tests.comelit</li>
    <li>home-assistant-component-tests.isy994</li>
    <li>liquidctl (python311Packages.liquidctl)</li>
    <li>liquidctl.dist (python311Packages.liquidctl.dist)</li>
    <li>liquidctl.man (python311Packages.liquidctl.man)</li>
    <li>octoprint</li>
    <li>octoprint.dist</li>
    <li>online-judge-template-generator</li>
    <li>online-judge-template-generator.dist</li>
    <li>online-judge-tools (python311Packages.online-judge-tools)</li>
    <li>online-judge-tools.dist (python311Packages.online-judge-tools.dist)</li>
    <li>phonemizer (python311Packages.phonemizer)</li>
    <li>phonemizer.dist (python311Packages.phonemizer.dist)</li>
    <li>python311Packages.aio-pika</li>
    <li>python311Packages.aio-pika.dist</li>
    <li>python311Packages.aiocomelit</li>
    <li>python311Packages.aiocomelit.dist</li>
    <li>python311Packages.aiofile</li>
    <li>python311Packages.aiofile.dist</li>
    <li>python311Packages.aiomisc</li>
    <li>python311Packages.aiomisc-pytest</li>
    <li>python311Packages.aiomisc-pytest.dist</li>
    <li>python311Packages.aiomisc.dist</li>
    <li>python311Packages.aiormq</li>
    <li>python311Packages.aiormq.dist</li>
    <li>python311Packages.caio</li>
    <li>python311Packages.caio.dist</li>
    <li>python311Packages.chat-downloader</li>
    <li>python311Packages.chat-downloader.dist</li>
    <li>python311Packages.clldutils</li>
    <li>python311Packages.clldutils.dist</li>
    <li>python311Packages.colorlog</li>
    <li>python311Packages.colorlog.dist</li>
    <li>python311Packages.dask-gateway-server</li>
    <li>python311Packages.dask-gateway-server.dist</li>
    <li>python311Packages.dataprep-ml</li>
    <li>python311Packages.dataprep-ml.dist</li>
    <li>python311Packages.jaraco-abode</li>
    <li>python311Packages.jaraco-abode.dist</li>
    <li>python311Packages.jedi-language-server</li>
    <li>python311Packages.jedi-language-server.dist</li>
    <li>python311Packages.lsprotocol</li>
    <li>python311Packages.lsprotocol.dist</li>
    <li>python311Packages.lupupy</li>
    <li>python311Packages.lupupy.dist</li>
    <li>python311Packages.mindsdb-evaluator</li>
    <li>python311Packages.mindsdb-evaluator.dist</li>
    <li>python311Packages.nox</li>
    <li>python311Packages.nox.dist</li>
    <li>python311Packages.online-judge-api-client</li>
    <li>python311Packages.online-judge-api-client.dist</li>
    <li>python311Packages.optuna</li>
    <li>python311Packages.optuna.dist</li>
    <li>python311Packages.pyenvisalink</li>
    <li>python311Packages.pyenvisalink.dist</li>
    <li>python311Packages.pygls</li>
    <li>python311Packages.pygls.dist</li>
    <li>python311Packages.pyisy</li>
    <li>python311Packages.pyisy.dist</li>
    <li>python311Packages.pypca</li>
    <li>python311Packages.pypca.dist</li>
    <li>python311Packages.pysim</li>
    <li>python311Packages.pysim.dist</li>
    <li>python311Packages.python-lsp-ruff</li>
    <li>python311Packages.python-lsp-ruff.dist</li>
    <li>python311Packages.riscof</li>
    <li>python311Packages.riscof.dist</li>
    <li>python311Packages.riscv-isac</li>
    <li>python311Packages.riscv-isac.dist</li>
    <li>python311Packages.segments</li>
    <li>python311Packages.segments.dist</li>
    <li>python311Packages.skybellpy</li>
    <li>python311Packages.skybellpy.dist</li>
    <li>python311Packages.type-infer</li>
    <li>python311Packages.type-infer.dist</li>
    <li>python312Packages.aio-pika</li>
    <li>python312Packages.aio-pika.dist</li>
    <li>python312Packages.aiomisc</li>
    <li>python312Packages.aiomisc-pytest</li>
    <li>python312Packages.aiomisc-pytest.dist</li>
    <li>python312Packages.aiomisc.dist</li>
    <li>python312Packages.aiormq</li>
    <li>python312Packages.aiormq.dist</li>
    <li>python312Packages.clldutils</li>
    <li>python312Packages.clldutils.dist</li>
    <li>python312Packages.colorlog</li>
    <li>python312Packages.colorlog.dist</li>
    <li>python312Packages.liquidctl</li>
    <li>python312Packages.liquidctl.dist</li>
    <li>python312Packages.liquidctl.man</li>
    <li>python312Packages.lupupy</li>
    <li>python312Packages.lupupy.dist</li>
    <li>python312Packages.pyenvisalink</li>
    <li>python312Packages.pyenvisalink.dist</li>
    <li>python312Packages.pypca</li>
    <li>python312Packages.pypca.dist</li>
    <li>rapid-photo-downloader</li>
    <li>rapid-photo-downloader.dist</li>
    <li>ruff-lsp</li>
    <li>ruff-lsp.dist</li>
    <li>sbomnix</li>
    <li>sbomnix.dist</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vscode-extensions.ms-python.python</li>
    <li>ycmd</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
> 4 packages failed to build:
> * apache-airflow
> * apache-airflow.dist
> * python312Packages.segments
> * python312Packages.segments.dist

apache-airflow will be fixed by #286828 and segments is just as broken on master

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 284695` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>25 packages marked as broken and skipped:</summary>
  <ul>
    <li>apache-airflow</li>
    <li>apache-airflow.dist</li>
    <li>home-assistant-component-tests.abode</li>
    <li>home-assistant-component-tests.comelit</li>
    <li>home-assistant-component-tests.isy994</li>
    <li>python312Packages.chat-downloader</li>
    <li>python312Packages.chat-downloader.dist</li>
    <li>python312Packages.cot</li>
    <li>python312Packages.cot.dist</li>
    <li>python312Packages.jaraco-abode</li>
    <li>python312Packages.jaraco-abode.dist</li>
    <li>python312Packages.jedi-language-server</li>
    <li>python312Packages.jedi-language-server.dist</li>
    <li>python312Packages.lsprotocol</li>
    <li>python312Packages.lsprotocol.dist</li>
    <li>python312Packages.nox</li>
    <li>python312Packages.nox.dist</li>
    <li>python312Packages.online-judge-api-client</li>
    <li>python312Packages.online-judge-api-client.dist</li>
    <li>python312Packages.online-judge-tools</li>
    <li>python312Packages.online-judge-tools.dist</li>
    <li>python312Packages.pygls</li>
    <li>python312Packages.pygls.dist</li>
    <li>python312Packages.skybellpy</li>
    <li>python312Packages.skybellpy.dist</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python312Packages.segments</li>
    <li>python312Packages.segments.dist</li>
  </ul>
</details>
<details>
  <summary>113 packages built:</summary>
  <ul>
    <li>bitbake-language-server</li>
    <li>bitbake-language-server.dist</li>
    <li>cmake-language-server</li>
    <li>cmake-language-server.dist</li>
    <li>cot (python311Packages.cot)</li>
    <li>cot.dist (python311Packages.cot.dist)</li>
    <li>errbot</li>
    <li>errbot.dist</li>
    <li>gkraken</li>
    <li>gnomeExtensions.freon</li>
    <li>liquidctl (python311Packages.liquidctl)</li>
    <li>liquidctl.dist (python311Packages.liquidctl.dist)</li>
    <li>liquidctl.man (python311Packages.liquidctl.man)</li>
    <li>octoprint</li>
    <li>octoprint.dist</li>
    <li>online-judge-template-generator</li>
    <li>online-judge-template-generator.dist</li>
    <li>online-judge-tools (python311Packages.online-judge-tools)</li>
    <li>online-judge-tools.dist (python311Packages.online-judge-tools.dist)</li>
    <li>phonemizer (python311Packages.phonemizer)</li>
    <li>phonemizer.dist (python311Packages.phonemizer.dist)</li>
    <li>python311Packages.aio-pika</li>
    <li>python311Packages.aio-pika.dist</li>
    <li>python311Packages.aiocomelit</li>
    <li>python311Packages.aiocomelit.dist</li>
    <li>python311Packages.aiofile</li>
    <li>python311Packages.aiofile.dist</li>
    <li>python311Packages.aiomisc</li>
    <li>python311Packages.aiomisc-pytest</li>
    <li>python311Packages.aiomisc-pytest.dist</li>
    <li>python311Packages.aiomisc.dist</li>
    <li>python311Packages.aiormq</li>
    <li>python311Packages.aiormq.dist</li>
    <li>python311Packages.caio</li>
    <li>python311Packages.caio.dist</li>
    <li>python311Packages.chat-downloader</li>
    <li>python311Packages.chat-downloader.dist</li>
    <li>python311Packages.clldutils</li>
    <li>python311Packages.clldutils.dist</li>
    <li>python311Packages.colorlog</li>
    <li>python311Packages.colorlog.dist</li>
    <li>python311Packages.dask-gateway-server</li>
    <li>python311Packages.dask-gateway-server.dist</li>
    <li>python311Packages.dataprep-ml</li>
    <li>python311Packages.dataprep-ml.dist</li>
    <li>python311Packages.jaraco-abode</li>
    <li>python311Packages.jaraco-abode.dist</li>
    <li>python311Packages.jedi-language-server</li>
    <li>python311Packages.jedi-language-server.dist</li>
    <li>python311Packages.lsprotocol</li>
    <li>python311Packages.lsprotocol.dist</li>
    <li>python311Packages.lupupy</li>
    <li>python311Packages.lupupy.dist</li>
    <li>python311Packages.mindsdb-evaluator</li>
    <li>python311Packages.mindsdb-evaluator.dist</li>
    <li>python311Packages.nox</li>
    <li>python311Packages.nox.dist</li>
    <li>python311Packages.online-judge-api-client</li>
    <li>python311Packages.online-judge-api-client.dist</li>
    <li>python311Packages.optuna</li>
    <li>python311Packages.optuna.dist</li>
    <li>python311Packages.pyenvisalink</li>
    <li>python311Packages.pyenvisalink.dist</li>
    <li>python311Packages.pygls</li>
    <li>python311Packages.pygls.dist</li>
    <li>python311Packages.pyisy</li>
    <li>python311Packages.pyisy.dist</li>
    <li>python311Packages.pypca</li>
    <li>python311Packages.pypca.dist</li>
    <li>python311Packages.pysim</li>
    <li>python311Packages.pysim.dist</li>
    <li>python311Packages.python-lsp-ruff</li>
    <li>python311Packages.python-lsp-ruff.dist</li>
    <li>python311Packages.riscof</li>
    <li>python311Packages.riscof.dist</li>
    <li>python311Packages.riscv-isac</li>
    <li>python311Packages.riscv-isac.dist</li>
    <li>python311Packages.segments</li>
    <li>python311Packages.segments.dist</li>
    <li>python311Packages.skybellpy</li>
    <li>python311Packages.skybellpy.dist</li>
    <li>python311Packages.type-infer</li>
    <li>python311Packages.type-infer.dist</li>
    <li>python312Packages.aio-pika</li>
    <li>python312Packages.aio-pika.dist</li>
    <li>python312Packages.aiomisc</li>
    <li>python312Packages.aiomisc-pytest</li>
    <li>python312Packages.aiomisc-pytest.dist</li>
    <li>python312Packages.aiomisc.dist</li>
    <li>python312Packages.aiormq</li>
    <li>python312Packages.aiormq.dist</li>
    <li>python312Packages.clldutils</li>
    <li>python312Packages.clldutils.dist</li>
    <li>python312Packages.colorlog</li>
    <li>python312Packages.colorlog.dist</li>
    <li>python312Packages.liquidctl</li>
    <li>python312Packages.liquidctl.dist</li>
    <li>python312Packages.liquidctl.man</li>
    <li>python312Packages.lupupy</li>
    <li>python312Packages.lupupy.dist</li>
    <li>python312Packages.pyenvisalink</li>
    <li>python312Packages.pyenvisalink.dist</li>
    <li>python312Packages.pypca</li>
    <li>python312Packages.pypca.dist</li>
    <li>rapid-photo-downloader</li>
    <li>rapid-photo-downloader.dist</li>
    <li>ruff-lsp</li>
    <li>ruff-lsp.dist</li>
    <li>sbomnix</li>
    <li>sbomnix.dist</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vscode-extensions.ms-python.python</li>
    <li>ycmd</li>
  </ul>
</details>

**Pull request merged**
