### PR TITLE
frankenphp: 1.1.0 -> 1.1.2

### PR DESCRIPTION
**Pull request by gaelreyrol**
## Description of changes

This PR updates FrankenPHP to its latest version: https://github.com/dunglas/frankenphp/releases/tag/v1.1.1

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by shyim — APPROVED** [review]

**Comment by NickCao** [comment]
There is a hash mismatch:
```
error: hash mismatch in fixed-output derivation '/nix/store/rjj0l8ngklgvnvz7isnrrmwq56bd23r3-frankenphp-1.1.1-go-modules.drv':
         specified: sha256-pYjn3JwnzJBS2zCxKFux1zYOQoiZePKvie859awQeUk=
            got:    sha256-gxBD2KPkWtAM0MsaQ9Ed4QDjJCg1uJQpXvnCOnAsZTw=
```

**Comment by shyim** [comment]
1.1.2 is out. maybe let's do that instead

**Review by shyim — APPROVED** [review]

**Comment by drupol** [comment]
WTH ? Checksum mismatch ?!

**Comment by drupol** [comment]
Rebased against `master` and now I get the same hash as in the CI.

Weird... but OK. I hope that all the Go module doesn't need an update, or else it's going to be painful.

**Comment by shyim** [comment]
yup build for me also on darwin/arm64
```
shyim in ~
❯ nix build github:gaelreyrol/nixpkgs/a943160442362e63602d2053a901aedc15eb6b49#frankenphp

shyim in ~ took 1m7s
❯ ./result/bin/frankenphp -v
FrankenPHP 1.1.2 PHP 8.2.17 Caddy v2.7.6 h1:w0NymbG2m9PcvKWsrXO6EEkY9Ru4FJK8uQbYcev1p3A=
```

**Review by shyim — APPROVED** [review]

**Review by shyim — APPROVED** [review]

**Pull request merged**
