### PR TITLE
Fix mk flutter app

### PR DESCRIPTION
**Pull request by Qubasa**
###### Description of changes

After upgrading flutter to version 3 in https://github.com/NixOS/nixpkgs/pull/173200 I found a bug in the mkFlutterApp
which only successfully build the app if it used flutter plugins. I removed that necessity and cleaned up the code a bit.
Alongside these changes I had to recalculate the vendorHash of the packages: fluffychat and firmware-updater while also simultaneously upgrading fluffychat to the newest version and fix the build issues.  

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NetaliDev** [comment]
This will also fix #163515

**Comment by DarkKirb** [comment]
the vendorHash in the fluffychat patch isn’t reproducible, i got `sha256-PvUx4Z1owC99P3d1eMM5UPhUMpv0K1roGBSLQlo7lSI=`

**Comment by Luis-Hebendanz** [comment]
> the vendorHash in the fluffychat patch isn’t reproducible, i got `sha256-PvUx4Z1owC99P3d1eMM5UPhUMpv0K1roGBSLQlo7lSI=`

Hmm that's weird, ofborg seems to successfully build

**Comment by Luis-Hebendanz** [comment]
Maybe it's because of a new version of flutter being merged?

**Comment by Luis-Hebendanz** [comment]
No you are right seems to be unreproducible

**Pull request closed without merging**
