### PR TITLE
Steam: remove flashplayer

### PR DESCRIPTION
**Pull request by yochai**

### CODE REVIEW

**Comment by cpages** [comment]
I had to look at the diff to understand steam is the package not needing flash. Would you care to amend the commit message to mention it? Also, just for my information, where did you see it's not needed anymore? Thanks.

**Comment by yochai** [comment]
Sorry, my first pull request, I think that fixed it.
They are serving webm files for videos for a long time now.
Using Steam without flash and everything seems to work.

**Comment by linquize** [comment]
You don't need flash player to watch youtube either

**Comment by cpages** [comment]
I'm all for it. @jagajaga any objection?

**Comment by jagajaga** [comment]
Make one commit and rename it as it said in `CONTRIBUTING.md`. 
Don't create new PR, force push to this one.

**Comment by jagajaga** [comment]
You have to do
```
git rebase -i HEAD~5
# Then squash commits
git push --force # to your repo and this branch
```

**Pull request merged**
