### PR TITLE
nixos/wireguard-networkd: use systemd credentials for privateKeyFile and presharedKeyFile

### PR DESCRIPTION
**Pull request by Majiir**
Use systemd credentials to configure `privateKeyFile` and `presharedKeyFile` in the networkd backend for `networking.wireguard`.

## Testing

- [x] Ran NixOS tests
  - [x] `wireguard-networkd`
  - [x] `wireguard-dynamic-refresh-networkd`
- [x] Manually tested with config using `privateKeyFile`
  - [x] Verified private key is loaded correctly
  - [x] Verified `privateKeyFile` no longer needs to be readable by the `systemd-network` user`
  - [x] Verified everything works with `presharedKeyFile` being null/unconfigured (although a warning is logged)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by eliasp — APPROVED** [review]

**Review by misuzu — APPROVED** [review]

**Comment by pwaller** [comment]
This PR / the release note makes it sound like the presharedKeyFile should 'just work' if I set a path `presharedKeyFile = "/etc/path/to/cred`, but that leads to:

```
/etc/systemd/network/40-wg2.netdev:13: Failed to read credential for wireguard key (PresharedKey=), ignoring assignment: No such file or directory
```

And then in the netdev config:

```
PresharedKey=@wireguard-wg2-<hash>-preshared-key
```

So question: Is this meant to work out of the box, or are there additional steps, and are those steps documented somewhere?

**Comment by Majiir** [comment]
> So question: Is this meant to work out of the box, or are there additional steps, and are those steps documented somewhere?

That should just work out of the box. There is probably a bug here. I'm working on some other things right now, but this could probably use a NixOS test using `presharedKeyFile`.

Stab in the dark, but: What happens if you set the `name` of the peer manually to something simple (instead of letting it use the public key automatically)?

**Comment by pwaller** [comment]
> Stab in the dark, but: What happens if you set the name of the peer manually to something simple (instead of letting it use the public key automatically)?

Sadly did not help. I checked the contents of 40-wg2.netdev and it looks like `PresharedKey=@wireguard-wg2-customname-preshared-key` it still says:

```
/etc/systemd/network/40-wg2.netdev:13: Failed to read credential for wireguard key (PresharedKey=), ignoring assignment: No such file or directory
```

Interestingly, it looks like the root is not mounted before this error message. I see for example `wg2: netdev ready` before `Reached target Local File Systems`, separated by a timestamp of one second. Could that be relevant? Some things have (/sysroot) been mounted by that point but not /home, and not `/mnt/myroot` (which is a secondary mount for my root filesystem, I actually don't see the primary root mount listed in the systemd log output).

**Comment by pwaller** [comment]
It's not obvious to me how the credential mechanism is meant to work; which thing reads which files at what point? Is systemd aware of the mapping somehow?

**Comment by networkException** [comment]
Yes, systemd is supposed to be reading the credential files on your behalf. The way its implemented here all credentials are listed in `systemd.services.systemd-networkd.serviceConfig.LoadCredential` (visible on the running system with `systemctl cat systemd-networkd.service | grep LoadCredential`) all credentials are referenced by `@name` (where `name` is the string before the `:` in the `LoadCredential`s) in the respective netdevs.

See https://www.freedesktop.org/software/systemd/man/latest/systemd.netdev.html#PresharedKey= and https://www.freedesktop.org/software/systemd/man/latest/systemd.netdev.html#PrivateKey= for how networkd can use credentials, see https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#LoadCredential=ID:PATH and https://systemd.io/CREDENTIALS/ for credentials in general

**Comment by networkException** [comment]
I can't test this properly currently but from a quick look at the code paths that could've printed the error you posted

> /etc/systemd/network/40-wg2.netdev:13: Failed to read credential for wireguard key (PresharedKey=), ignoring assignment: No such file or directory

I would assume the `No such file or directory` refers to reading the already loaded credential from `/run/credentials/systemd-networkd.service`. Can you check in there?

**Comment by networkException** [comment]
I've addressed some issues regarding pre shared keys in #368684.

@pwaller your issue will probably not be fixed by those changes just yet although you can try anyways with something like

```nix
imports = [
  ./path/to/updated-module.nix
];

disabledModules = [
  "services/networking/wireguard-networkd.nix"
];
```

**Pull request merged**
