### PR TITLE
bundix: 2.5.1 -> 2.5.2

### PR DESCRIPTION
**Pull request by kirillrdy**
###### Description of changes

fixes downloading of bundled gems eg rexml

this is also compatible with ruby_2_7

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by marsam** [comment]
Thanks a lot for looking into these issues.  
Would you mind updating the PR with the patch from https://github.com/nix-community/bundix/pull/101? It also seems to address the rexml issue among other fixes

**Comment by kirillrdy** [comment]
@marsam done ...
haha 3 MRs to address the same issue  ( i mean on bundix side )

Lets hope https://github.com/nix-community/bundix/pull/101 gets merged at some point

i've tested latest patch, still works with ruby_2_7 and ruby_3_0

**Comment by zowoq** [comment]
@marsam Do you want commit access to https://github.com/nix-community/bundix?

**Comment by marsam** [comment]
@zowoq yes please, I can help maintaining it

**Comment by zowoq** [comment]
I've sent you an invite to nix-community org and the nix-community bundix team.

**Comment by marsam** [comment]
@zowoq thanks a lot!

@kirillrdy I cut a release including both patches. Would you mind bumping bundix to [2.5.2](https://github.com/nix-community/bundix/releases/tag/2.5.2)?

**Comment by kirillrdy** [comment]
> @zowoq thanks a lot!
> 
> @kirillrdy I cut a release including both patches. Would you mind bumping bundix to [2.5.2](https://github.com/nix-community/bundix/releases/tag/2.5.2)?

done, i guess just wait for of ofborg to finish checks

**Review by marsam — APPROVED** [review]

**Pull request merged**
