### PR TITLE
statsd: repackage with node2nix

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

In #31032 it's attempted to get entirely rid of npm2nix.
One our packages which still used npm2nix is statsd.

Due to the fact that it's part of the NPM registry, it could be added to the `nodePackages` set.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Ma27** [comment]
(/cc @svanderburg )

**Comment by Ma27** [comment]
currently running `nox-review`.

**Comment by Ma27** [comment]
`fast-cli` breaks, however it breaks as well when running `nix-build -A fast-cli` on master without my change, so this seems unrelated.

**Comment by svanderburg** [comment]
@Ma27 The `fast-cli` breakage is indeed unrelated. I fixed this package some time ago, but it appears to be broken again.

Have you also tested the NixOS module that runs it as a service? I think you also to update the package reference there and check whether it still works.

**Comment by Ma27** [comment]
@svanderburg ah, didn't know about the module, will test it tonight :-)
The package reference doesn't need to be updated, I aliased `nodePackages.statsd` to `statsd` in `all-packages.nix` for compliancy reasons.

**Comment by Ma27** [comment]
@svanderburg the `services.statsd` module still works for me.

I checked it using the following VM configuration from my branch:

``` nix
{
  statsd = {
    users.extraUsers.vm = {
      isNormalUser = true;
      password = "vm";
    };

    services.statsd.enable = true;
  };
}
```

The executable exists, the systemd services running on the default port (8125 in that case), the config defaults will be generated by the nixos module, it seems as nothing needs to be changed.

**Comment by svanderburg** [comment]
@Ma27 Cool! I guess this issue is resolved then!

**Comment by svanderburg** [comment]
@Ma27 I also just fixed the `fast-cli` package, so this should no longer be an issue

**Comment by garbas** [comment]
@Ma27 @svanderburg Is there a reason statsd backends were not included?

```
-, "statsd-librato-backend"
-, "stackdriver-statsd-backend"
-, "statsd-influxdb-backend"
```

**Comment by garbas** [comment]
Could we add this packages to the list?

**Comment by Ma27** [comment]
@garbas sure, will do this on the weekend :)

**Comment by garbas** [comment]
thank you, thank you, thank you! :)

**Comment by Ma27** [comment]
@garbas see #32051 (still WIP, but already testable)

**Pull request merged**
