### PR TITLE
[20.03] buildRustCrate fixes backports

### PR DESCRIPTION
**Pull request by andir**
###### Motivation for this change

This PR backports a bunch of changes that have been done to buildRustCrate since the branch-off. They are (mostly) just fixing bugs. Some of which are more annoying then others.

Since none of these break compatibility with older packages or users I do think they are still good to be included.

The PRs that are included in this:
- #79299: buildRustCrate: remap the current build dir to / for (more) reproducible builds (bugfix)
- #79816: buildRustCrate: remove superfluous dependency overrides (~10x eval speedup in some cases; bugfix)
- #82155: buildRustCrate: Search for matching Cargo.toml in sub directories (feature/bugfix) 
- #82404: buildRustCrate: only link build deps into build script (bugfix)
- #83481: buildRustCrate: fewer backslashes (syntax only change) 
- #83379: buildRustCrate: don't sort link flags  (bugfix for an issue introduced in #82404)
- #83616: buildRustCrateTests: Fix link order test on darwin  (bugfix)
- #83488:  buildRustCrate: Add "-r" to cp to make it work under Mac OS (bugfix)

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS

### CODE REVIEW

**Comment by andir** [comment]
@GrahamcOfBorg build buildRustCrateTests

**Comment by andir** [comment]
Dear @NixOS/nixos-release-managers,

Please consider this for inclusion into 20.03. This carries a bunch of bug fixes and other QoL improvements. Since we have a very low amount of actual `buildRustCrate` users in nixpkgs the impact is very minimal. There are a few rebuilds but no new failures.

It would be great to have this in 20.03 since it also improves the compatibility with Darwin.

**Comment by flokli** [comment]
20.03 hasn't been released, should be fine IMHO to merge if it doesn't cause immediate breakages.

**Comment by worldofpeace** [comment]
> Dear @NixOS/nixos-release-managers,
> 
> Please consider this for inclusion into 20.03. This carries a bunch of bug fixes and other QoL improvements. Since we have a very low amount of actual `buildRustCrate` users in nixpkgs the impact is very minimal. There are a few rebuilds but no new failures.
> 
> It would be great to have this in 20.03 since it also improves the compatibility with Darwin.

Soo polite :smile: It sounds good to me.

**Review by worldofpeace — APPROVED** [review]
I approve of these bugfixes being backported.

**Pull request merged**
