### PR TITLE
refind: fix runtime errors

### PR DESCRIPTION
**Pull request by erikarvstedt**
In newer versions, instead of using `$PWD` to locate its ressource files,
Refind now refers to the dir containing `$0`.
This causes runtime errors due to missing ressources.

In lieu of a wrapper binary, we now simply patch the variable `RefindDir`
which stores the path to the ressource dir.

Here's a short script (run as root) to help testing this PR.
To see the runtime error that was fixed, replace the call to `refind-install` with the current Nixpkgs version of refind.
```
## Summary: Create temp device, install refind, delete device

# Create temporary loop device
truncate -s 10M /tmp/buf
tmpdev=$(losetup --find --show /tmp/buf)
mkfs.fat $tmpdev

# Run refind 
$(nix-build --no-out-link '<nixpkgs-dev>' -A refind)/bin/refind-install --usedefault $tmpdev --alldrivers
# Show contents of installation
$(nix-build --no-out-link '<nixpkgs>' -A tree)/bin/tree /tmp/refind_install

# Remove device
umount $tmpdev
losetup --detach $tmpdev
rm /tmp/buf
```

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by xeji** [comment]
cc @AndersonTorres

**Comment by AndersonTorres** [comment]
It was "readmitted" into Nixpkgs?

**Comment by xeji** [comment]
It was last updated and marked no longer broken in 2d66f39b15c65dd810925d15c83c54d123b77073.

**Comment by AndersonTorres** [comment]
So, it has my bless! Thanks, @xeji and @joachifm !

**Pull request merged**
