### PR TITLE
nixos/miniflux: add database.* options

### PR DESCRIPTION
**Pull request by aanderse**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/issues/108386

From here someone (@bricewge? @nornagon? :heart:) should make a PR to:
- replace the `database.password` option with a `database.passwordFile` option
- add a `database.socket` option and start using socket authentication by default to avoid passwords entirely

Note that while this PR does add a `password` option, storing a plain-text password in the nix store, the value was already being placed in the nix store - I'm just making it explicit so no one is mistaken in what they are doing when they use this module. We really need an additional PR to replace `database.password` with `database.passwordFile` as mentioned above.

If anyone is interested in writing such a PR but needs some advice I'd be more than willing to share my thoughts.

ping @Criena for testing.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aanderse** [comment]
@GrahamcOfBorg test miniflux

**Review by iblech — CHANGES_REQUESTED** [review]
This looks very good, thank you for your efforts!

I spotted one issue: Special characters in the password are not escaped properly. Once it has to be quoted for the purposes of protecting it from shell expansion (and to be SQL-safe), the second time so that DATABASE_URL is always a valid url.

Unfortunately, I don't know the recommend nixpkgs way of quoting. Perhaps others can weigh in on this question?

In any case, this problem existed also before this pull request.

**Comment by cript0nauta** [comment]
> In any case, this problem existed also before this pull request.

Before this change the database password was hardcoded to "miniflux", so there was no need for performing special quoting.

> Unfortunately, I don't know the recommend nixpkgs way of quoting. Perhaps others can weigh in on this question?

I'm not sure how would we url-encode the characters of a string using just Nix. An alternative that comes to my mind is to add an assertion checking that the password matches a regular expression (such as `[a-zA-Z0-9%]). If the assertion fails, building the configuration should abort and indicate the user to URL-encode the password to prevent problems.

**Comment by cript0nauta** [comment]
Besides the issue of character escaping, the changes look good to me. They will conflict with my PR #111030 but I can easily fix it if this PR gets merged first.

**Comment by aanderse** [comment]
@iblech @cript0nauta rebased and added some database escaping. Can you please take another look? Thanks!

**Review by nornagon — APPROVED** [review]
looks fine to me :)

**Review by cript0nauta — COMMENTED** [review]
Anyway, I don't see an attack surface useful to a malicious user. And in the case a password just has special characters, the worst case will be miniflux failing to start. Because the default password doesn't have special characters, it is unlikely that this change will cause a regression. In my opinion, it is good enough for merging.

**Comment by symphorien** [comment]
@aanderse oh I was going to test fully removing passwords: https://github.com/symphorien/nixpkgs/commit/861ca32393a1682a1ac40c4f4fe34abde204ccd8

Honestly the miniflux service is sooo simple that if you don't want a local database you are better off rewriting everything from scratch, so I'd favor simplicity with no options.

I think I'll still open a PR when I test it for real (the nixos tests works) to drive discussion.

**Comment by aanderse** [comment]
@symphorien ok cool. I don't use the service so have no real interest. Can you please close https://github.com/NixOS/nixpkgs/issues/108386 with a resolution and we'll call it a day? Thanks!

**Pull request closed without merging**
