### PR TITLE
wasmtime: 21.0.0 -> 21.0.1

### PR DESCRIPTION
**Pull request by ereslibre**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by basvandijk** [comment]
FYI: https://github.com/NixOS/nixpkgs/pull/314409 fixes the build on aarch64 by disabling the checks on those platforms.

**Comment by ereslibre** [comment]
I could cherry pick that commit but let's see if https://github.com/NixOS/nixpkgs/pull/314409 gets merged first and I can rebase this PR on top of that.

**Comment by ereslibre** [comment]
@basvandijk: rebased on top of https://github.com/NixOS/nixpkgs/pull/314409. I could also reproduce the issue about rust-lld in x86_64, so I have relaxed the `doCheck` condition.

Besides this -- added a note about it, -- the SIMD requirements for x86_64 were relaxed on https://github.com/bytecodealliance/wasmtime/commit/0c980788ae77d2fe5198352673370168675da749, so that SSE3 and SSSE3 were no longer necessary for lowering.

**Comment by SuperSandro2000** [comment]
Is the 2nd commit related to #312641 ? If so, we should drop the workaround and send the update to staging.

**Comment by ereslibre** [comment]
> Is the 2nd commit related to https://github.com/NixOS/nixpkgs/pull/312641 ? If so, we should drop the workaround and send the update to staging-next. https://nixpk.gs/pr-tracker.html?pr=312641

Exactly, that did the trick. Thank you @SuperSandro2000! Rebased on top of staging-next and updated the target branch in this PR.

**Comment by ereslibre** [comment]
Unsure how this PR targeting staging-branch will play out with the backport to release-24.05 though.

**Comment by K900** [comment]
Next time, please set your PR to draft before rebasing, otherwise you cause a mass ping.

**Comment by ereslibre** [comment]
> Next time, please set your PR to draft before rebasing, otherwise you cause a mass ping.

Wow, had no idea about it. Sorry.

**Pull request closed without merging**
