### PR TITLE
hareThirdParty.hare-json: init at unstable-2023-09-21

### PR DESCRIPTION
**Pull request by starzation**
## Description of changes

hare-json packages provides JSON support for Hare ([Homepage](https://git.sr.ht/~sircmpwn/hare-json))

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by starzation** [comment]
This require hare build from `master` branch or from this pr #266456 .
Maybe mark this pr as draft until #266456 is merged.

**Comment by starzation** [comment]
I will add all offcial hare apckgaes  should i do in this pr or separate?

**Comment by onemoresuza** [comment]
> I will add all official hare packages should i do in this pr or separate?

What exactly do you mean by **all official hare packages**? If you mean something like the other extended support libraries, they should go into their own PRs.

**Comment by onemoresuza** [comment]
> ~This require hare build from `master` branch or from this pr #266456 . Maybe i should mark this pr as draft until #266456 is merged.~
> 
> Btw. If hare still said there is no module `encoding::json`, you need to set `third-party` folder to `HAREPATH` env
> 
> ```shell
> export HAREPATH=$HOME/.nix-profile/src/hare/stdlib:$HOME/.nix-profile/src/hare/third-party
> ```

This is already handled by `hare`'s [`setupHook`](https://github.com/NixOS/nixpkgs/blob/67273d0def72ec49e6d4c7225e032a87bbdaaca7/pkgs/development/compilers/hare/setup-hook.sh)

**Comment by pbsds** [comment]
Please rebase

**Comment by starzation** [comment]
@pbsds Updated!

**Review by pbsds — APPROVED** [review]
Result of `nixpkgs-review pr 268982` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>hareThirdParty.hare-json</li>
  </ul>
</details>

Seems like no compilation takes place, it only puts the hare-json sources in a directory structure for downstream use.

Just a quick nit and it should be ready for merge

**Pull request merged**
