### PR TITLE
mailman: drop

### LINKED ISSUE #158424: python3.pkgs.mailman is not a Python module
`python3.pkgs.mailman` is not a Python module and `python310.pkgs.mailman` actually uses Python 3.9!???
It can also not be added to `python3Packages` with the correct Python version cause it overrides sqlalchemy.
Thus mailman and the packages depending on it need to be removed from `python-packages.nix`.
cc @mweinelt @jonringer

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
closes https://github.com/NixOS/nixpkgs/issues/158424

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
cc maintainers @globin @alyssais

**Comment by veprbl** [comment]
Do I understand correctly that this is deleting a package just because it has an issue?

**Comment by dotlambda** [comment]
> Do I understand correctly that this is deleting a package just because it has an issue?

An issue and inactive maintainers.

**Comment by lheckemann** [comment]
We are not inactive. You're welcome to cc maintainers on issues like this.

**Comment by lheckemann** [comment]
(sorry, I missed the issue assignment and that I'm not actually listed as a maintainer. Will fix.)

**Comment by dotlambda** [comment]
> Will fix.

You didn't. Now it's time for removal: https://github.com/NixOS/nixpkgs/pull/170035

**Pull request closed without merging**
