### PR TITLE
pythonPackages.dateparser: switch to parameterized and thereby fix Hydra test

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
nose-parameterized is deprecated and yields a warning.
This fixes a failing Hydra test: https://hydra.nixos.org/build/68773666

The relevant upstream PR (https://github.com/scrapinghub/dateparser/pull/381) can't be used for `fetchpatch`. The codebase seems to have changed too much in the meantime.

See also https://github.com/NixOS/nixpkgs/pull/34589.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

/cc @Ma27

### CODE REVIEW

**Comment by FRidh** [comment]
Seems like a good solution to me. While you're at it, could you also remove `Warning: ` after the `warn`
https://github.com/NixOS/nixpkgs/pull/34589/files#diff-2afbba83e1b14f9e0c304c769831a0e2R3842

**Comment by dotlambda** [comment]
In the same commit?

**Comment by dotlambda** [comment]
Removed `Warning:`

**Comment by Ma27** [comment]
@FRidh see my comment in the other PR, shouldn't we rather drop the `warn` expression for now and try to get rid of all usages or shall we make python builds pass if a warning is rendered?

**Comment by dotlambda** [comment]
I grepped through `python-packages.nix` and `development/python-modules/` and this was the only occurence of `nose-parameterized`.

**Comment by FRidh** [comment]
Let's just get rid of this deprecated package as it simplifies things.

**Comment by Ma27** [comment]
> I grepped through python-packages.nix and development/python-modules/ and this was the only occurence of nose-parameterized.

Thanks for your clarification, then you're right :)

> Let's just get rid of this deprecated package as it simplifies things.

I wasn't sure at first if we should really drop this package, however I think that you might be right. Currently preparing a PR for `dateparser` to get rid of the old dependency :-)

**Comment by dotlambda** [comment]
I already made a PR: https://github.com/scrapinghub/dateparser/pull/381

**Comment by dotlambda** [comment]
I ran `nix-build nixos/release-combined.nix -A nixpkgs.tarball` again. No errors as expected.

**Comment by Ma27** [comment]
awesome! Thanks for caring about this <3

**Comment by dotlambda** [comment]
@FRidh Please merge.

**Pull request merged**
