### PR TITLE
update-users-groups: update hashedPassword in /etc/shadow

### PR DESCRIPTION
**Pull request by dasj19**
###### Description of changes
As it is right now if a user has a password hash in /etc/shadow and then a changes it via configuration. However the hash does not get updated in /etc/shadow.

This PR makes possible to update the password hash in /etc/shadow declaratively using the options `hashedPassword`, `password` and `passwordFile`. So whenever one of the value of these options gets updated /etc/shadow will be updated accordingly.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
Isn't this going to break the mutable users option?

**Comment by dasj19** [comment]
hmm. yes this contradicts with the mutabe users statement `The initial password for a user will be set according to users.users, but existing passwords will not be changed.`
But wait a minute do you think I would achieve the same by using `users.mutableUsers = false;`?

**Comment by winterqt** [comment]
You should, yes, as that just replaces the shadow file each time. Not sure of the specifics of the (intended) mutable users logic off the top is my head (specifically with regards to how state tracking and the existing shadow file interact), but making your users immutable would definitely fix this.

**Comment by dasj19** [comment]
okay thanks for input. do we know why `users.mutableUsers = true;` is the default? Is it just to allow user manipulation via useradd and groupadd ?

**Comment by RaitoBezarius** [comment]
> okay thanks for input. do we know why `users.mutableUsers = true;` is the default? Is it just to allow user manipulation via useradd and groupadd ?

My understanding is that declarative users are nice but should be a conscious decision because of how they can break a lot of stuff and `nixos-rebuild switch` is not necessarily going to work under broken users / groups.

**Comment by RaitoBezarius** [comment]
Feel free to reopen if you think this should be a change, but I think `users.mutableUsers = false;` achieves what is desired here.

**Pull request closed without merging**
