### PR TITLE
pulsar: patch additionals git binary

### PR DESCRIPTION
**Pull request by COLAMAroro**
## Description of changes
This is a direct fix for #303142.

Pulsar comes with a npm dependency called "dugite", which comes with it's own git binaries.
The actual "git" binary itself was patched, but not other dependency binaries such as "git-fetch-http". This commit just blanket fixes every other secondary binary.
Additionally, this patches are now also included on aarch64

Also, considering this package has now another maintainer, I wish to withdraw myself as a maintainer.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Sigmanificient** [comment]
Result of `nixpkgs-review pr 305825` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>pulsar</li>
  </ul>
</details>

**Review by bryango — APPROVED** [review]

**Comment by bryango** [comment]
This looks great to me! Although I haven't run the build yet, I will try to do that as soon as possible.

On the other hand, would you consider staying as a maintainer? You understand the packaging much better than me and we would be very grateful for your help (don't be pressured to answer for the issues though, I will try to respond as a maintainer when pinged).

**Comment by COLAMAroro** [comment]
The main issue is that, I packaged this when I was still a student, and I could regularly check out GitHub (or their emails). You even saw that I kind of stopped updating the package since 1.109

Since then, I've graduated, got employed, and now my free time is limited to mostly week-ends. It took me two weeks to even see in my inbox that I was pinged on the related issue. I'm not sure this availability is compatible to remain registered as a maintainer.

I can still take a look from time to time if pinged, but I'm not sure if having my name in there is still the best idea.

**Comment by bryango** [comment]
I don't believe there is any hard requirement for maintainers' availability, especially when there are multiple maintainers. But the decision is yours eventually. Thank you very much for packaging pulsar in the first place!

**Review by Aleksanaa — APPROVED** [review]
Please reword to `pulsar: patch additionals git binary`

**Pull request merged**
