### PR TITLE
feat: Add catchuptvandmore and dependencies

### PR DESCRIPTION
**Pull request by M-Gregoire**
## Description of changes

Hello :wave: ,

I've been working on packaging [Catchup TV And More](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore) for Kodi and all it's dependencies. I've made some progress but I'm looking for some help/guidance.

1. First of all, I've seen some Kodi packages having:
```
  passthru = {
    pythonPath = "lib";
    updateScript = addonUpdateScript {
      attrPath = "kodi.packages.arrow";
    };
  };
```

but not all of them. I couldn't find any documentation (In both Nixpkgs or Kodi wiki): when is `passthru` needs to be used (for either `pythonPath` or `updateScript`?

2. Catchup TV And More gets installed on Kodi but fails on launch, I couldn't find anything in `~/.kodi/temp/kodi.log`, is there a good way to debug this?

3. So far, the only meaningful information I found was looking at the `dependencies` list in Kodi, where some of the dependencies I packaged are correctly picked-up, while some others are considered not available.

Thank you for any help you might provide,

## Notifications

Kodi maintainers (let me know if it's not the right way to ask for review :pray: ):
@aanderse
@cpages
@edwtjo
@minijackson
@peterhoeg
@sephalon

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aanderse** [comment]
i'll address your questions a bit later, just heading out now... almost got it to work, remaining issue is `error <general>: Add-on 'script.module.pytz' is not compatible with Kodi`

take a look at my [fixups](https://github.com/NixOS/nixpkgs/compare/master...aanderse:nixpkgs:kodi.packages.catchuptvandmore?expand=1) if you want to keep hacking on this in the meantime

**Comment by aanderse** [comment]
i pushed a couple more fixes so the addon will actually run now

i had success playing some videos, but failures trying to play many more
some failures were errors in the streams, some failures seemed to be out of date code, and others i didn't understand what was wrong

example: `AttributeError: module 'kodi_six.xbmc' has no attribute 'translatePath'`

i suggest you pull my commit into your branch and try the application... see how it goes

let me know if you need any more help

**Comment by aanderse** [comment]
- `passthru.updateScript` is documented [here](https://nixos.org/manual/nixpkgs/unstable/)
- `passthru.pythonPath` is a specific to `kodi.packages` packages and "documented" [here](https://github.com/NixOS/nixpkgs/blob/5550a85a087c04ddcace7f892b0bdc9d8bb080c8/pkgs/applications/video/kodi/wrapper.nix#L12)... better documentation wasn't much of a priority for me because not many people were contributing to `kodi` up until recently

if you take a look at:
- the "documentation" i linked above
- the source code of the dependencies you packaged
- the `pythonPath` that i set for the dependencies you packaged

i think you will understand very clearly what `pythonPath` is for... though if you don't please let me know and i can try to improve upon the explanation

**Comment by M-Gregoire** [comment]
Thanks a lot for both your fixups and your explanations/documentation! This helped a lot. I was able to fix a few things I just pushed.

I'm still encountering an issue with some videos: the addon downloads the `ChromeOS` image to extract WidevineCDM  to read some contents, which fails:
```
2023-10-24 10:43:34.367 T:7322  warning <general>: [script.module.inputstreamhelper] Recursively create directory '/home/kodi/.kodi/userdata/addon_data/script.module.inputstreamhelper/backup/'.
2023-10-24 10:43:37.517 T:7322  warning <general>: [script.module.inputstreamhelper] Downloading ChromeOS image for Widevine: trogdor (15572.63.0)
2023-10-24 10:43:37.918 T:1833     info <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2023-10-24 10:48:18.273 T:7322  warning <general>: [script.module.inputstreamhelper] Recursively create directory '/home/kodi/.kodi/userdata/addon_data/script.module.inputstreamhelper/backup/15572.63.0/'.
2023-10-24 10:48:18.356 T:7322  warning <general>: [script.module.inputstreamhelper] Recursively create directory '/home/kodi/.kodi/cdm/'.
2023-10-24 10:48:18.357 T:7322  warning <general>: [script.module.inputstreamhelper] Hardlink file '/home/kodi/.kodi/userdata/addon_data/script.module.inputstreamhelper/backup/15572.63.0/config.json' to '/home/kodi/.kodi/cdm/config.json'.
2023-10-24 10:48:18.360 T:7322  warning <general>: [script.module.inputstreamhelper] Hardlink file '/home/kodi/.kodi/userdata/addon_data/script.module.inputstreamhelper/backup/15572.63.0/libwidevinecdm.so' to '/home/kodi/.kodi/cdm/libwidevinecdm.so'.
2023-10-24 10:48:18.363 T:7322  warning <general>: [script.module.inputstreamhelper] Hardlink file '/home/kodi/.kodi/userdata/addon_data/script.module.inputstreamhelper/backup/15572.63.0/recovery.json' to '/home/kodi/.kodi/cdm/recovery.json'.
2023-10-24 10:48:18.430 T:7322  critical <general>: [script.module.inputstreamhelper] ['ldd', '/home/kodi/.kodi/cdm/libwidevinecdm.so'] cmd failed.
2023-10-24 10:48:18.431 T:7322  critical <general>: [script.module.inputstreamhelper] Failed to check for missing Widevine libraries.
2023-10-24 10:48:18.901 T:1997     info <general>: CActiveAESink::OpenSink - initialize sink
```

So I've tried manually running the command that fails:
```
$ ldd /home/kodi/.kodi/cdm/libwidevinecdm.so
/home/kodi/.kodi/cdm/libwidevinecdm.so: error while loading shared libraries: /home/kodi/.kodi/cdm/libwidevinecdm.so: DT_RELR without GLIBC_ABI_DT_RELR dependency
```

I'm not quite sure how to fix this issue unfortunately. I'll try to take some time to look into it but any idea is welcome.

**Comment by aanderse** [comment]
i think i used widevine a number of times in the past without issue
a few years ago i was using the netflix addon which i am sure uses it and that was fine

i also got prompted to install widevine and i don't recall seeing those errors
 i'll take another look

**Comment by M-Gregoire** [comment]
Thanks a lot, I tried investigating the issue but apart from the error mentionned above, I was not able to find the culprit.

**Comment by aanderse** [comment]
errors encountered:
- `Error Contents: module 'kodi_six.xbmc' has no attribute 'translatePath'` - looks like the addon needs updating perhaps?
- `2023-10-29 11:05:39.290 T:1259724   error <general>: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/resources/lib/channels/ch/srgssr/list_sub_categories/?_pickle_=8004956f000000000000007d94288c075f7469746c655f948c06436f6d656479948c076974656d5f6964948c03737266948c0c63617465676f72795f75726e948c3575726e3a7372663a746f7069633a74763a65353230383066632d663336622d343831652d393535662d30373162366338643664633394752e` looks to me like the menu structure doesn't match the website... so again an issue with the addon
- `2023-10-29 11:09:58.479 T:1265861   error <general>: [Catch-up-TV-&-More.support] list indices must be integers or slices, not str` - definitely an issue with the addon
- `2023-10-29 11:11:07.540 T:1266868   error <general>: [Catch-up-TV-&-More.support] 'in <string>' requires string as left operand, not NoneType` - addon
- `2023-10-29 11:11:47.471 T:1267475   error <general>: [Catch-up-TV-&-More.support] 'url'` - addon
- `2023-10-29 11:13:10.962 T:1270956   error <general>: [Catch-up-TV-&-More.support] ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))` - looks to be that the video might not be available, or just a connection issue with the provider

---

i was able to start a bunch of videos from a number of countries, though i ran into a ton of issues... all of which seemed to be from the addon itself
i did not run into any widevine issue at all :man_shrugging:

have you ever used this addon before? it doesn't seem well maintained...

**Comment by aanderse** [comment]
@M-Gregoire are you still working on this?

**Comment by M-Gregoire** [comment]
Hey @aanderse ,

I'm sorry for the slow reply, I haven't had much time to look into it and decided to move my Kodi host to Raspbian as I use my plugins and won't have time to migrate all of them to NixOS.

My PR was mostly working but some channels were not working.

**Comment by aanderse** [comment]
no problem

i am sorry what we have in nixpkgs didn't suit your needs 😞 unfortunately packaging nontrivial addons can be a task sometimes

i will close this PR and in the future if anyone wants to take it over they can open a new one

best wishes

**Pull request closed without merging**
