### PR TITLE
paperwm: 2022-12-14 -> 2023-04-20

### PR DESCRIPTION
**Pull request by cab404**
###### Description of changes

Well, with gnome 44 this also needs a bump

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cab404** [comment]
Checked it, works just fine. They've sorted out 4-finger swipes :з

**Comment by cab404** [comment]
@AndersonTorres >.>

**Comment by cab404** [comment]
@piegamesde it looks like gesture code haven't been touched it a really long time in PaperWM, and that it is as best as we can get rn on 44 :(

**Comment by cab404** [comment]
Also, if anyone needs a working paperwm — use `477e87a4f04a01ad05245852c0cf645fd19bec0c` until https://github.com/paperwm/PaperWM/pull/515 is merged

**Comment by jtaala** [comment]
Just a note that we've now merged in Gnome 44 support into [develop](https://github.com/paperwm/PaperWM/tree/develop) branch.  We've also done a beta release for Gnome 44 https://github.com/paperwm/PaperWM/releases/tag/v44.0.0-beta.1.

**Pull request merged**
