### PR TITLE
ollama: 0.1.42 -> 0.1.43

### PR DESCRIPTION
**Pull request by abysssol**
## Description of changes

changelog: [release 0.1.43](https://github.com/ollama/ollama/releases/tag/v0.1.43)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [x] hydra `nix build -f pkgs/top-level/release.nix release-checks`
  - [x] nixos service + rocm + cuda `nix build -f default.nix ollama.tests`
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix run nixpkgs#nixpkgs-review -- rev HEAD`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
  - tested that rocm uses gpu
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by kirillrdy** [comment]
@abysssol please consider adding link to release log / diff 

as per https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions

something like a45d61da22a36e22b1d43f369cd3ed462cc677a8

**Comment by abysssol** [comment]
is the link I added, [release 0.1.43](https://github.com/ollama/ollama/releases/tag/v0.1.43), not good enough?

**Comment by kirillrdy** [comment]
> is the link I added, [release 0.1.43](https://github.com/ollama/ollama/releases/tag/v0.1.43), not good enough?

the link you added is adequate but as per
 https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions

it should be added to commit message as well as  PR description

**Comment by kirillrdy** [comment]
i just saw your edit

if upstream doesn't keep change log  ( pretty common ) then diff link is added

**Comment by abysssol** [comment]
I misunderstood, I didn't realize that I should be adding the link directly to the commit message. Thank you for bringing this to my attention.

**Pull request merged**
