### PR TITLE
python35: remove

### LINKED ISSUE #95272: Python 3.5 removal
According to the 3.5 life-cycle (https://www.python.org/dev/peps/pep-0478/) , the final release has already occurred and is now considered EOL. 

The jump from 3.5 to 3.6 has already happened in the majority of python packages and should not be a similar situation in which we had to extend python2's life long after its official EOL date.

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
It's EOL soon, and should be removed before 20.09

closes: #95272

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

```
$ nix-env -f /home/jon/.cache/nixpkgs-review/pr-95305/nixpkgs -qaP --xml --out-path --show-trace --meta
2 packages removed:
python3 (†3.5.9) python3 (†3.5.9)

Nothing changed
https://github.com/NixOS/nixpkgs/pull/95305
$ nix-shell /home/jon/.cache/nixpkgs-review/pr-95305/shell.nix
```

### CODE REVIEW

**Review by FRidh — APPROVED** [review]
I was hoping to get the final patch release in before removing it, so anyone that would be interested in it could easily cherry-pick it or refer to a Nixpkgs release with it. But, the release is delayed and I don't consider it that important either.

**Comment by jonringer** [comment]
I'll leave this open for a while longer so other can comment, but those are my feelings as well

**Review by prusnak — APPROVED** [review]

**Review by bhipple — APPROVED** [review]
If I were you I'd just nuke it now @FRidh.  Anyone maintaining a fork w/ a long-lived py 3.5 should be sophisticated enough to bump it to the last 3.5.X patch themselves if they're really keen on it.

Though the commitment to top it off and see it through to the end is admirable.

**Comment by jonringer** [comment]
according to the original PEP, https://www.python.org/dev/peps/pep-0478/ , the final release was meant to be out almost a month ago, I don't think we should hold our breath.

Also a lot of "core" packages, that you want to bring in through nixpkgs (E.g. pandas), no longer build.

Not to mention that 0 caching makes it very painful to use this package set.

**Comment by jonringer** [comment]
I could add it to my NUR, and we can have a foot note in the docs . But I would like to discourage people from using it in general

**Pull request merged**
