### PR TITLE
R: Adding MKL support

### PR DESCRIPTION
**Pull request by nviets**
###### Description of changes

Adds option to build R to use oneMKL's BLAS and LAPACK. See:
- [Using oneMKL with R](https://www.intel.com/content/www/us/en/developer/articles/technical/using-onemkl-with-r.html)
- [Extending R with Intel MKL](https://www.intel.com/content/www/us/en/developer/articles/technical/extending-r-with-intel-mkl.html)
- [R Admin's Intel MKL Section](https://cran.r-project.org/doc/manuals/r-release/R-admin.html#MKL)

After building, you can verify oneMKL is active with ldd:
```
➜ ldd /nix/store/57hxm6piknq4b1rxxg1hka92a7ylxp3p-R-4.2.2/lib/R/lib/libR.so
	linux-vdso.so.1 (0x00007fffb17a8000)
	libmkl_gf_lp64.so.1 => /nix/store/77z026cccvjwgmm2ns06045grfijczp6-mkl-2021.1.1.52/lib/libmkl_gf_lp64.so.1 (0x00007f5d72a00000)
	libmkl_gnu_thread.so.1 => /nix/store/77z026cccvjwgmm2ns06045grfijczp6-mkl-2021.1.1.52/lib/libmkl_gnu_thread.so.1 (0x00007f5d70c00000)
	libmkl_core.so.1 => /nix/store/77z026cccvjwgmm2ns06045grfijczp6-mkl-2021.1.1.52/lib/libmkl_core.so.1 (0x00007f5d68c00000)
...
```
@alexvorobiev @jbedo @bhipple

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jbedo** [comment]
Blas/lapack are already abstracted to allow swapping between implementations, you can override and specify what provider you need, e.g.,:

```
with import <nixpkgs> {
  overlays = [
    (_: super:
      with super; {
        blas = blas.override {blasProvider = mkl;};
        lapack = lapack.override {lapackProvider = mkl;};
      })
  ];
}; R

**Comment by nviets** [comment]
I tried a shell with the overlay, but R doesn't pick up MKL's BLAS:
```
[nix-shell:~/rMklTest]$ ldd /nix/store/qspqpf4d41dcbgdqdcqqpljgpa50i355-R-4.2.2/lib/R/lib/libR.so
        linux-vdso.so.1 (0x00007fffbfcf4000)
        libblas.so.3 => /nix/store/f7bj3ac2bysmkgd7amnczz8gnpjavigz-blas-3/lib/libblas.so.3 (0x00007f82462f0000)
        libgfortran.so.5 => /nix/store/hnq2yysb10ds0hl9mnndq9clc9qrga83-gfortran-11.3.0-lib/lib/libgfortran.so.5 (0x00007f8246000000)
        libm.so.6 => /nix/store/ayfr5l52xkqqjn3n4h9jfacgnchz1z7s-glibc-2.35-224/lib/libm.so.6 (0x00007f8245f20000)
```
I think the overlay misses the extra options required to activate BLAS. From [R Admin](https://cran.r-project.org/doc/manuals/r-release/R-admin.html#MKL):

```
MKL_LIB_PATH=/path/to/intel_mkl/mkl/lib/intel64
export LD_LIBRARY_PATH=$MKL_LIB_PATH
MKL="-L${MKL_LIB_PATH} -lmkl_gf_lp64 -lmkl_core -lmkl_gnu_thread -dl -fopenmp"
./configure --with-blas="$MKL" --with-lapack
```
MKL BLAS is a popular in R, so I thought an option made sense.

**Comment by jbedo** [comment]
The BLAS abstraction builds a shared object by copying symbols from one of the providers, see https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/alternatives/blas/default.nix. If you check your libblas above (with e.g., `nix show-derivation /nix/store/f7bj3ac2bysmkgd7amnczz8gnpjavigz-blas-3/lib/libblas.so.3`) you should find it is build by taking symbols from MKL.

**Comment by nviets** [comment]
Looks like R builds, but fails on the tests:
```
...
Matrix products: default
BLAS/LAPACK: /nix/store/bwvl225306vbcds1j2lmjb36fbygvf1i-blas-3/lib/libblas.so.3

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.2.1
check flags: -j4 SHELL=/nix/store/dsd5gz46hdbdk2rfdimqddhq6m8m8fqs-bash-5.1-p16/bin/bash VERBOSE=y check
make[1]: Entering directory '/build/R-4.2.1/tests'
make[2]: Entering directory '/build/R-4.2.1/tests'
make[3]: Entering directory '/build/R-4.2.1/tests/Examples'
Testing examples for package 'base'
Testing examples for package 'tools'
  comparing 'tools-Ex.Rout' to 'tools-Ex.Rout.save' ... OK
Testing examples for package 'utils'
Testing examples for package 'grDevices'
  comparing 'grDevices-Ex.Rout' to 'grDevices-Ex.Rout.save' ... OK
Testing examples for package 'graphics'
  comparing 'graphics-Ex.Rout' to 'graphics-Ex.Rout.save' ... OK
Testing examples for package 'stats'
Error: testing 'stats' failed
```
MKL's libblas.sp.3 does appear in the derivation of the blas that appears in the log:
```
{
  "/nix/store/gxscbxb61j649pwi4pb8r9kdmcb3jz9b-blas-3.drv": {
    "args": [
      "-e",
      "/nix/store/9krlzvny65gdc8s7kpb6lkx8cd02c25b-default-builder.sh"
    ],
    "builder": "/nix/store/dsd5gz46hdbdk2rfdimqddhq6m8m8fqs-bash-5.1-p16/bin/bash",
    "env": {
...
      "installPhase": "mkdir -p $out/lib $dev/include $dev/lib/pkgconfig\n\nlibblas=\"/nix/store/b7qsdza368vg0crll0r9fhb3dx2x7g7f-mkl-2021.1.1.52/lib/libblas.so.3\"\n\nif ! [ -e \"$libblas\" ]; then\n  echo \"$libblas does not exist, mkl-2021.1.1.52 does not provide libblas.\"\n  exit 1\nfi\n\n$NM -an \"$libblas\" | cut -f3 -d' ' > symbols\nfor symbol in caxpy ccopy cdotc cdotu cgbmv cgemm cgemv cgerc cgeru chbmv chemm chemv cher cher2 cher2k cherk chpmv chpr chpr2 crotg cscal csrot csscal cswap csymm csyr2k csyrk ctbmv ctbsv ctpmv ctpsv ctrmm ctrmv ctrsm ctrsv dasum daxpy dcabs1 dcopy ddot dgbmv dgemm dgemv dger dnrm2 drot drotg drotm drotmg dsbmv dscal dsdot dspmv dspr dspr2 dswap dsymm dsymv dsyr dsyr2 dsyr2k dsyrk dtbmv dtbsv dtpmv dtpsv dtrmm dtrmv dtrsm dtrsv dzasum dznrm2 icamax idamax isamax izamax lsame sasum saxpy scabs1 scasum scnrm2 scopy sdot sdsdot sgbmv sgemm sgemv sger snrm2 srot srotg srotm srotmg ssbmv sscal sspmv sspr sspr2 sswap ssymm ssymv ssyr ssyr2 ssyr2k ssyrk stbmv stbsv stpmv stpsv strmm strmv strsm strsv xerbla xerbla_array zaxpy zcopy zdotc zdotu zdrot zdscal zgbmv zgemm zgemv zgerc zgeru zhbmv zhemm zhemv zher zher2 zher2k zherk zhpmv zhpr zhpr2 zrotg zscal zswap zsymm zsyr2k zsyrk ztbmv ztbsv ztpmv ztpsv ztrmm ztrmv ztrsm ztrsv; do\n  grep -q \"^$symbol_$\" symbols || { echo \"$symbol\" was not found in \"$libblas\"; exit 1; }\ndone\n\ncp -L \"$libblas\" $out/lib/libblas.so.3\nchmod +w $out/lib/libblas.so.3\n\npatchelf --set-soname libblas.so.3 $out/lib/libblas.so.3\npatchelf --set-rpath \"$(patchelf --print-rpath $out/lib/libblas.so.3):/nix/store/b7qsdza368vg0crll0r9fhb3dx2x7g7f-mkl-2021.1.1.52/lib\" $out/lib/libblas.so.3\n\n  if [ \"$out/lib/libblas.so.3\" != \"$out/lib/libblas.so\" ]; then\n    ln -s $out/lib/libblas.so.3 \"$out/lib/libblas.so\"\n  fi\n\n  cat <<EOF > $dev/lib/pkgconfig/blas.pc\nName: blas\nVersion: 3\nDescription: BLAS FORTRAN implementation\nLibs: -L$out/lib -lblas\nCflags: -I$dev/include\nEOF\n\n  libcblas=\"/nix/store/b7qsdza368vg0crll0r9fhb3dx2x7g7f-mkl-2021.1.1.52/lib/libcblas.so.3\"\n\n  if ! [ -e \"$libcblas\" ]; then\n    echo \"$libcblas does not exist, mkl-2021.1.1.52 does not provide libcblas.\"\n    exit 1\n  fi\n\n  cp -L \"$libcblas\" $out/lib/libcblas.so.3\n  chmod +w $out/lib/libcblas.so.3\n\npatchelf --set-soname libcblas.so.3 $out/lib/libcblas.so.3\npatchelf --set-rpath \"$(patchelf --print-rpath $out/lib/libcblas.so.3):/nix/store/b7qsdza368vg0crll0r9fhb3dx2x7g7f-mkl-2021.1.1.52/lib\" $out/lib/libcblas.so.3\n  if [ \"$out/lib/libcblas.so.3\" != \"$out/lib/libcblas.so\" ]; then\n    ln -s $out/lib/libcblas.so.3 \"$out/lib/libcblas.so\"\n  fi\n\n  cp /nix/store/g9zbdx8kw97j4rgacc1jqxk05nfmddn4-liblapack-3.10.1/include/cblas{,_mangling}.h $dev/include\n\n  cat <<EOF > $dev/lib/pkgconfig/cblas.pc\nName: cblas\nVersion: 3\nDescription: BLAS C implementation\nCflags: -I$dev/include\nLibs: -L$out/lib -lcblas\nEOF\nmkdir -p $out/nix-support\necho 'export MKL_INTERFACE_LAYER=LP64,GNU' > $out/nix-support/setup-hook\nln -s $out/lib/libblas.so.3 $out/lib/libmkl_rt.so\nln -sf /nix/store/b7qsdza368vg0crll0r9fhb3dx2x7g7f-mkl-2021.1.1.52/include/* $dev/include\n",
...
```
Am I doing something silly?
```
➜ cat default.nix
with import <nixpkgs> {
  overlays = [
    (_: super:
      with super; {
        blas = blas.override {blasProvider = mkl;};
        lapack = lapack.override {lapackProvider = mkl;};
      })
  ];
}; R
```

**Comment by jbedo** [comment]
I believe your running into this situation: https://www.jyotirmoy.net/posts/2021-10-03-r-mkl-openmp.html. An additional override `R = R.overrideAttrs (_: {MKL_THREADING_LAYER="GNU";});` will get it through the tests if it is. Some care will be needed to do this when you use the binary later too.

**Comment by nviets** [comment]
Thanks for tip. The override worked for me:
```
with import <nixpkgs> {
  overlays = [
    (_: super:
      with super; {
        blas = blas.override {blasProvider = mkl;};
        lapack = lapack.override {lapackProvider = mkl;};
      })
  ];
}; R.overrideAttrs (_: {MKL_THREADING_LAYER="GNU";})
```

**Comment by alexvorobiev** [comment]
@jbedo Wouldn't this issue affect everybody who wants to use MKL-enabled R? So R is not fully compatible with the configurable blas/lapack approach used in nixpkgs?

**Comment by jbedo** [comment]
No, the issue is MKL has threading that's not compatible with GNU threads. If R is compiled with GNU threading then MKL has to be configured into a compatible mode with the above environment variable. As this is specifically GNU threads it doesn't happen when R is compiled with other compilers like clang, and it's hard to resolve it globally as there's no way to tell when GNU threads are being used. For R specifically we could try and handle MKL with gcc, but there are several options (propagate the threading config, or disable openmp). Open an issue and we can discuss this further if you feel we should do something. At least as we run tests by default and will pick up this issue.

**Pull request closed without merging**
