### PR TITLE
displaylink: 5.8.0-63.33 -> 6.0.0-24

### PR DESCRIPTION
**Pull request by drupol**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 324121` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 324121` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Review by GaetanLepage — APPROVED** [review]
Diff LGTM.

Were you able to test ?

**Comment by drupol** [comment]
I have no clue on how I could test this yet :S

**Comment by drupol** [comment]
I have issues with this version of the driver.

<details>

<summary>Kernel logs</summary>

```
❯  sudo journalctl -f -t kernel
jui 15 10:02:52 x280 kernel: hub 4-1.2:1.0: 4 ports detected
jui 15 10:02:52 x280 kernel: cdc_ncm 4-1.1:1.5 enp58s0u1u1i5: renamed from eth0
jui 15 10:02:52 x280 kernel: usb 3-1.4: new high-speed USB device number 16 using xhci_hcd
jui 15 10:02:53 x280 kernel: usb 3-1.4: New USB device found, idVendor=046d, idProduct=0836, bcdDevice= 0.10
jui 15 10:02:53 x280 kernel: usb 3-1.4: New USB device strings: Mfr=0, Product=2, SerialNumber=1
jui 15 10:02:53 x280 kernel: usb 3-1.4: Product: B525 HD Webcam
jui 15 10:02:53 x280 kernel: usb 3-1.4: SerialNumber: C95FC680
jui 15 10:02:53 x280 kernel: usb 3-1.4: Warning! Unlikely big volume range (=6144), cval->res is probably wrong.
jui 15 10:02:53 x280 kernel: usb 3-1.4: [5] FU [Mic Capture Volume] ch = 1, val = 1536/7680/1
jui 15 10:02:53 x280 kernel: usb 3-1.4: Found UVC 1.00 device B525 HD Webcam (046d:0836)
jui 15 10:03:38 x280 kernel: usb 3-1: USB disconnect, device number 13
jui 15 10:03:38 x280 kernel: usb 3-1.2: USB disconnect, device number 15
jui 15 10:03:38 x280 kernel: usb 3-1.4: USB disconnect, device number 16
jui 15 10:03:38 x280 kernel: uvcvideo 3-1.4:1.3: Failed to resubmit video URB (-19).
jui 15 10:03:39 x280 kernel: usb 4-1: USB disconnect, device number 11
jui 15 10:03:39 x280 kernel: usb 4-1.1: USB disconnect, device number 12
jui 15 10:03:39 x280 kernel: cdc_ncm 4-1.1:1.5 enp58s0u1u1i5: unregister 'cdc_ncm' usb-0000:3a:00.0-1.1, CDC NCM (SEND ZLP)
jui 15 10:03:39 x280 kernel: ------------[ cut here ]------------
jui 15 10:03:39 x280 kernel: WARNING: CPU: 6 PID: 144653 at kernel/module/main.c:851 module_put+0x82/0xa0
jui 15 10:03:39 x280 kernel: Modules linked in: cdc_mbim cdc_wdm snd_usb_audio cdc_ncm cdc_ether snd_usbmidi_lib usbnet snd_ump mii snd_rawmidi typec_displayport uinput xt_mark hid_logitech_hidpp usbhid hid_generic uhid hid ccm qrtr rfcomm snd_seq_dummy snd_hrtimer snd_seq snd_seq_device nft_chain_nat xt_MASQUERADE nf_conntrack_netlink xfrm_user xfrm_algo xt_addrtype overlay af_packet cmac algif_hash algif_skcipher af_alg bnep snd_sof_pci_intel_skl snd_sof_intel_hda_common snd_soc_hdac_hda soundwire_intel snd_sof_intel_hda_mlink soundwire_cadence snd_sof_intel_hda snd_sof_pci snd_sof_xtensa_dsp snd_sof snd_sof_utils soundwire_generic_allocation soundwire_bus snd_soc_avs iwlmvm snd_soc_hda_codec snd_hda_codec_hdmi snd_soc_skl snd_soc_sst_ipc snd_soc_sst_dsp snd_hda_ext_core joydev snd_soc_acpi_intel_match mousedev snd_ctl_led snd_hda_codec_realtek snd_soc_acpi intel_uncore_frequency intel_uncore_frequency_common snd_hda_codec_generic snd_soc_core mac80211 intel_tcc_cooling snd_hda_scodec_component x86_pkg_temp_thermal intel_powerclamp
jui 15 10:03:39 x280 kernel:  coretemp xt_conntrack snd_compress crc32_pclmul ac97_bus polyval_clmulni snd_pcm_dmaengine polyval_generic btusb rmi_smbus uvcvideo gf128mul rmi_core ghash_clmulni_intel btrtl sha512_ssse3 nls_iso8859_1 sha256_ssse3 btintel nls_cp437 sha1_ssse3 snd_hda_intel iTCO_wdt aesni_intel btbcm vfat snd_intel_dspcfg btmtk intel_pmc_bxt fat crypto_simd libarc4 ip6t_rpfilter cryptd videobuf2_vmalloc snd_intel_sdw_acpi watchdog rapl intel_rapl_msr mei_pxp mei_hdcp sd_mod uvc ipt_rpfilter videobuf2_memops bluetooth iwlwifi videobuf2_v4l2 snd_hda_codec ledtrig_audio videodev intel_cstate videobuf2_common ecdh_generic mc uas ecc intel_uncore snd_hda_core xt_pkttype thunderbolt intel_wmi_thunderbolt wmi_bmof psmouse processor_thermal_device_pci_legacy think_lmi cfg80211 e1000e xt_LOG snd_hwdep firmware_attributes_class processor_thermal_device thinkpad_acpi snd_pcm tpm_crb processor_thermal_wt_hint processor_thermal_rfim nf_log_syslog i2c_i801 ucsi_acpi processor_thermal_rapl ptp intel_rapl_common typec_ucsi snd_timer
jui 15 10:03:39 x280 kernel:  nvram platform_profile pps_core i2c_smbus processor_thermal_wt_req typec intel_xhci_usb_role_switch xt_tcpudp snd processor_thermal_power_floor processor_thermal_mbox mei_me tpm_tis rfkill intel_soc_dts_iosf intel_pch_thermal tpm_tis_core thermal roles mei soundcore nft_compat tiny_power_button battery ac int3403_thermal int340x_thermal_zone intel_pmc_core int3400_thermal intel_vsec pmt_telemetry acpi_thermal_rel button pmt_class acpi_pad input_leds led_class evdev mac_hid nf_tables serio_raw sch_fq_codel msr loop cpufreq_powersave xt_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 libcrc32c br_netfilter veth tun tap macvlan bridge stp llc kvm_intel kvm fuse configfs efi_pstore nfnetlink efivarfs tpm rng_core dmi_sysfs ip_tables x_tables autofs4 usb_storage scsi_mod scsi_common ext4 crc32c_generic crc16 mbcache jbd2 nvme atkbd xhci_pci xhci_pci_renesas libps2 vivaldi_fmap nvme_core xhci_hcd nvme_auth t10_pi crc32c_intel crc64_rocksoft crc64 crc_t10dif crct10dif_generic crct10dif_pclmul
jui 15 10:03:39 x280 kernel:  crct10dif_common i8042 rtc_cmos serio dm_mod dax i915 i2c_algo_bit drm_buddy video wmi backlight ttm intel_gtt drm_display_helper firmware_class cec
jui 15 10:03:39 x280 kernel: CPU: 6 PID: 144653 Comm: kworker/6:1 Tainted: G S      W          6.9.8 #1-NixOS
jui 15 10:03:39 x280 kernel: Hardware name: LENOVO 20KES4MW00/20KES4MW00, BIOS N20ET61W (1.46 ) 05/11/2022
jui 15 10:03:39 x280 kernel: Workqueue: events ucsi_handle_connector_change [typec_ucsi]
jui 15 10:03:39 x280 kernel: RIP: 0010:module_put+0x82/0xa0
jui 15 10:03:39 x280 kernel: Code: 85 c0 74 0f 48 8b 40 08 48 89 fe 48 89 c7 e8 65 fd ff ff 65 ff 0d e6 56 29 60 74 13 31 c0 31 d2 31 f6 31 ff c3 cc cc cc cc 90 <0f> 0b 90 eb 9e 0f 1f 44 00 00 31 c0 31 d2 31 f6 31 ff c3 cc cc cc
jui 15 10:03:39 x280 kernel: RSP: 0018:ffff9ad6e19ebd10 EFLAGS: 00010297
jui 15 10:03:39 x280 kernel: RAX: 0000000000000000 RBX: ffff935b98062c08 RCX: 0000000000000000
jui 15 10:03:39 x280 kernel: RDX: 00000000ffffffff RSI: 0000000000000000 RDI: ffffffffc231d240
jui 15 10:03:39 x280 kernel: RBP: 0000000000000000 R08: 0000000000000000 R09: 0000000000000000
jui 15 10:03:39 x280 kernel: R10: 0000000000000000 R11: 0000000000000000 R12: ffffffffc231d0b8
jui 15 10:03:39 x280 kernel: R13: ffff935b98062c88 R14: 0000000000000080 R15: ffff935c41e22800
jui 15 10:03:39 x280 kernel: FS:  0000000000000000(0000) GS:ffff935da7500000(0000) knlGS:0000000000000000
jui 15 10:03:39 x280 kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
jui 15 10:03:39 x280 kernel: CR2: 00007fe89a6c2a90 CR3: 00000001657ec002 CR4: 00000000003706f0
jui 15 10:03:39 x280 kernel: Call Trace:
jui 15 10:03:39 x280 kernel:  <TASK>
jui 15 10:03:39 x280 kernel:  ? __warn+0x80/0x120
jui 15 10:03:39 x280 kernel:  ? module_put+0x82/0xa0
jui 15 10:03:39 x280 kernel:  ? report_bug+0x172/0x1a0
jui 15 10:03:39 x280 kernel:  ? handle_bug+0x43/0x90
jui 15 10:03:39 x280 kernel:  ? exc_invalid_op+0x17/0x80
jui 15 10:03:39 x280 kernel:  ? asm_exc_invalid_op+0x1a/0x20
jui 15 10:03:39 x280 kernel:  ? module_put+0x82/0xa0
jui 15 10:03:39 x280 kernel:  typec_altmode_update_active+0x6f/0x120 [typec]
jui 15 10:03:39 x280 kernel:  typec_remove+0x8b/0xa0 [typec]
jui 15 10:03:39 x280 kernel:  device_release_driver_internal+0x1a7/0x210
jui 15 10:03:39 x280 kernel:  bus_remove_device+0xc6/0x140
jui 15 10:03:39 x280 kernel:  device_del+0x163/0x400
jui 15 10:03:39 x280 kernel:  ? kfree+0x2bf/0x310
jui 15 10:03:39 x280 kernel:  device_unregister+0x17/0x70
jui 15 10:03:39 x280 kernel:  ucsi_unregister_altmodes+0x4c/0xb0 [typec_ucsi]
jui 15 10:03:39 x280 kernel:  ucsi_unregister_partner+0x85/0x150 [typec_ucsi]
jui 15 10:03:39 x280 kernel:  ucsi_handle_connector_change+0x285/0x300 [typec_ucsi]
jui 15 10:03:39 x280 kernel:  process_one_work+0x180/0x3a0
jui 15 10:03:39 x280 kernel:  worker_thread+0x256/0x370
jui 15 10:03:39 x280 kernel:  ? __pfx_worker_thread+0x10/0x10
jui 15 10:03:39 x280 kernel:  ? __pfx_worker_thread+0x10/0x10
jui 15 10:03:39 x280 kernel:  kthread+0xcd/0x100
jui 15 10:03:39 x280 kernel:  ? __pfx_kthread+0x10/0x10
jui 15 10:03:39 x280 kernel:  ret_from_fork+0x31/0x50
jui 15 10:03:39 x280 kernel:  ? __pfx_kthread+0x10/0x10
jui 15 10:03:39 x280 kernel:  ret_from_fork_asm+0x1a/0x30
jui 15 10:03:39 x280 kernel:  </TASK>
jui 15 10:03:39 x280 kernel: ---[ end trace 0000000000000000 ]---
jui 15 10:03:39 x280 kernel: usb 4-1.2: USB disconnect, device number 13
jui 15 10:03:45 x280 kernel: usb 1-4: new high-speed USB device number 11 using xhci_hcd
jui 15 10:03:45 x280 kernel: i915 0000:00:02.0: [drm] *ERROR* Atomic update failure on pipe A (start=2206 end=2207) time 1905 us, min 1073, max 1079, scanline start 991, end 6
jui 15 10:03:45 x280 kernel: usb 1-4: New USB device found, idVendor=1d5c, idProduct=5012, bcdDevice= 1.00
jui 15 10:03:45 x280 kernel: usb 1-4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
jui 15 10:03:45 x280 kernel: usb 1-4: Product: USB2.0 Hub
jui 15 10:03:45 x280 kernel: usb 1-4: Manufacturer: Fresco Logic, Inc.
jui 15 10:03:45 x280 kernel: hub 1-4:1.0: USB hub found
jui 15 10:03:45 x280 kernel: hub 1-4:1.0: 4 ports detected
jui 15 10:03:45 x280 kernel: usb 2-4: new SuperSpeed USB device number 9 using xhci_hcd
jui 15 10:03:45 x280 kernel: usb 2-4: New USB device found, idVendor=1d5c, idProduct=5002, bcdDevice= 1.00
jui 15 10:03:45 x280 kernel: usb 2-4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
jui 15 10:03:45 x280 kernel: usb 2-4: Product: USB3.0 Hub
jui 15 10:03:45 x280 kernel: usb 2-4: Manufacturer: Fresco Logic, Inc.
jui 15 10:03:45 x280 kernel: hub 2-4:1.0: USB hub found
jui 15 10:03:45 x280 kernel: hub 2-4:1.0: 4 ports detected
jui 15 10:03:45 x280 kernel: ------------[ cut here ]------------
jui 15 10:03:45 x280 kernel: WARNING: CPU: 5 PID: 304962 at drivers/usb/typec/class.c:303 typec_altmode_update_active+0x105/0x120 [typec]
jui 15 10:03:45 x280 kernel: Modules linked in: cdc_mbim cdc_wdm snd_usb_audio cdc_ncm cdc_ether snd_usbmidi_lib usbnet snd_ump mii snd_rawmidi typec_displayport uinput xt_mark hid_logitech_hidpp usbhid hid_generic uhid hid ccm qrtr rfcomm snd_seq_dummy snd_hrtimer snd_seq snd_seq_device nft_chain_nat xt_MASQUERADE nf_conntrack_netlink xfrm_user xfrm_algo xt_addrtype overlay af_packet cmac algif_hash algif_skcipher af_alg bnep snd_sof_pci_intel_skl snd_sof_intel_hda_common snd_soc_hdac_hda soundwire_intel snd_sof_intel_hda_mlink soundwire_cadence snd_sof_intel_hda snd_sof_pci snd_sof_xtensa_dsp snd_sof snd_sof_utils soundwire_generic_allocation soundwire_bus snd_soc_avs iwlmvm snd_soc_hda_codec snd_hda_codec_hdmi snd_soc_skl snd_soc_sst_ipc snd_soc_sst_dsp snd_hda_ext_core joydev snd_soc_acpi_intel_match mousedev snd_ctl_led snd_hda_codec_realtek snd_soc_acpi intel_uncore_frequency intel_uncore_frequency_common snd_hda_codec_generic snd_soc_core mac80211 intel_tcc_cooling snd_hda_scodec_component x86_pkg_temp_thermal intel_powerclamp
jui 15 10:03:45 x280 kernel:  coretemp xt_conntrack snd_compress crc32_pclmul ac97_bus polyval_clmulni snd_pcm_dmaengine polyval_generic btusb rmi_smbus uvcvideo gf128mul rmi_core ghash_clmulni_intel btrtl sha512_ssse3 nls_iso8859_1 sha256_ssse3 btintel nls_cp437 sha1_ssse3 snd_hda_intel iTCO_wdt aesni_intel btbcm vfat snd_intel_dspcfg btmtk intel_pmc_bxt fat crypto_simd libarc4 ip6t_rpfilter cryptd videobuf2_vmalloc snd_intel_sdw_acpi watchdog rapl intel_rapl_msr mei_pxp mei_hdcp sd_mod uvc ipt_rpfilter videobuf2_memops bluetooth iwlwifi videobuf2_v4l2 snd_hda_codec ledtrig_audio videodev intel_cstate videobuf2_common ecdh_generic mc uas ecc intel_uncore snd_hda_core xt_pkttype thunderbolt intel_wmi_thunderbolt wmi_bmof psmouse processor_thermal_device_pci_legacy think_lmi cfg80211 e1000e xt_LOG snd_hwdep firmware_attributes_class processor_thermal_device thinkpad_acpi snd_pcm tpm_crb processor_thermal_wt_hint processor_thermal_rfim nf_log_syslog i2c_i801 ucsi_acpi processor_thermal_rapl ptp intel_rapl_common typec_ucsi snd_timer
jui 15 10:03:45 x280 kernel:  nvram platform_profile pps_core i2c_smbus processor_thermal_wt_req typec intel_xhci_usb_role_switch xt_tcpudp snd processor_thermal_power_floor processor_thermal_mbox mei_me tpm_tis rfkill intel_soc_dts_iosf intel_pch_thermal tpm_tis_core thermal roles mei soundcore nft_compat tiny_power_button battery ac int3403_thermal int340x_thermal_zone intel_pmc_core int3400_thermal intel_vsec pmt_telemetry acpi_thermal_rel button pmt_class acpi_pad input_leds led_class evdev mac_hid nf_tables serio_raw sch_fq_codel msr loop cpufreq_powersave xt_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 libcrc32c br_netfilter veth tun tap macvlan bridge stp llc kvm_intel kvm fuse configfs efi_pstore nfnetlink efivarfs tpm rng_core dmi_sysfs ip_tables x_tables autofs4 usb_storage scsi_mod scsi_common ext4 crc32c_generic crc16 mbcache jbd2 nvme atkbd xhci_pci xhci_pci_renesas libps2 vivaldi_fmap nvme_core xhci_hcd nvme_auth t10_pi crc32c_intel crc64_rocksoft crc64 crc_t10dif crct10dif_generic crct10dif_pclmul
jui 15 10:03:45 x280 kernel:  crct10dif_common i8042 rtc_cmos serio dm_mod dax i915 i2c_algo_bit drm_buddy video wmi backlight ttm intel_gtt drm_display_helper firmware_class cec
jui 15 10:03:45 x280 kernel: CPU: 5 PID: 304962 Comm: kworker/u32:1 Tainted: G S      W          6.9.8 #1-NixOS
jui 15 10:03:45 x280 kernel: Hardware name: LENOVO 20KES4MW00/20KES4MW00, BIOS N20ET61W (1.46 ) 05/11/2022
jui 15 10:03:45 x280 kernel: Workqueue: USBC000:00-con2 ucsi_poll_worker [typec_ucsi]
jui 15 10:03:45 x280 kernel: RIP: 0010:typec_altmode_update_active+0x105/0x120 [typec]
jui 15 10:03:45 x280 kernel: Code: 25 28 00 00 00 75 2b 48 83 c4 10 5b 5d 31 c0 31 d2 31 c9 31 f6 31 ff c3 cc cc cc cc e8 44 76 a9 de 84 c0 0f 85 6b ff ff ff 90 <0f> 0b 90 e9 62 ff ff ff e8 0e 07 59 df 66 66 2e 0f 1f 84 00 00 00
jui 15 10:03:45 x280 kernel: RSP: 0018:ffff9ad6cf24bdf8 EFLAGS: 00010246
jui 15 10:03:45 x280 kernel: RAX: 0000000000000000 RBX: ffff935c4c1ed808 RCX: 0000000000000000
jui 15 10:03:45 x280 kernel: RDX: 0000000000000000 RSI: 0000000000000000 RDI: 0000000000000000
jui 15 10:03:45 x280 kernel: RBP: 0000000000000001 R08: 0000000000000000 R09: 0000000000000000
jui 15 10:03:45 x280 kernel: R10: 0000000000000000 R11: 0000000000000000 R12: ffff935c4438a4e8
jui 15 10:03:45 x280 kernel: R13: ffff935b47a1a480 R14: ffff935b4181ac00 R15: 0000000000000000
jui 15 10:03:45 x280 kernel: FS:  0000000000000000(0000) GS:ffff935da7480000(0000) knlGS:0000000000000000
jui 15 10:03:45 x280 kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
jui 15 10:03:45 x280 kernel: CR2: 00007f773a6452b0 CR3: 000000023e020002 CR4: 00000000003706f0
jui 15 10:03:45 x280 kernel: Call Trace:
jui 15 10:03:45 x280 kernel:  <TASK>
jui 15 10:03:45 x280 kernel:  ? __warn+0x80/0x120
jui 15 10:03:45 x280 kernel:  ? typec_altmode_update_active+0x105/0x120 [typec]
jui 15 10:03:45 x280 kernel:  ? report_bug+0x172/0x1a0
jui 15 10:03:45 x280 kernel:  ? handle_bug+0x43/0x90
jui 15 10:03:45 x280 kernel:  ? exc_invalid_op+0x17/0x80
jui 15 10:03:45 x280 kernel:  ? asm_exc_invalid_op+0x1a/0x20
jui 15 10:03:45 x280 kernel:  ? typec_altmode_update_active+0x105/0x120 [typec]
jui 15 10:03:45 x280 kernel:  ? typec_altmode_update_active+0xfc/0x120 [typec]
jui 15 10:03:45 x280 kernel:  ucsi_altmode_update_active+0x8a/0xf0 [typec_ucsi]
jui 15 10:03:45 x280 kernel:  ucsi_check_altmodes+0x55/0xa0 [typec_ucsi]
jui 15 10:03:45 x280 kernel:  ? mutex_lock+0x12/0x40
jui 15 10:03:45 x280 kernel:  ucsi_poll_worker+0x3a/0x110 [typec_ucsi]
jui 15 10:03:45 x280 kernel:  process_one_work+0x180/0x3a0
jui 15 10:03:45 x280 kernel:  worker_thread+0x256/0x370
jui 15 10:03:45 x280 kernel:  ? __pfx_worker_thread+0x10/0x10
jui 15 10:03:45 x280 kernel:  kthread+0xcd/0x100
jui 15 10:03:45 x280 kernel:  ? __pfx_kthread+0x10/0x10
jui 15 10:03:45 x280 kernel:  ret_from_fork+0x31/0x50
jui 15 10:03:45 x280 kernel:  ? __pfx_kthread+0x10/0x10
jui 15 10:03:45 x280 kernel:  ret_from_fork_asm+0x1a/0x30
jui 15 10:03:45 x280 kernel:  </TASK>
jui 15 10:03:45 x280 kernel: ---[ end trace 0000000000000000 ]---
jui 15 10:03:46 x280 kernel: usb 1-4.2: new high-speed USB device number 12 using xhci_hcd
jui 15 10:03:46 x280 kernel: usb 1-4.2: New USB device found, idVendor=05e3, idProduct=0610, bcdDevice=93.06
jui 15 10:03:46 x280 kernel: usb 1-4.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
jui 15 10:03:46 x280 kernel: usb 1-4.2: Product: USB2.1 Hub
jui 15 10:03:46 x280 kernel: usb 1-4.2: Manufacturer: GenesysLogic
jui 15 10:03:46 x280 kernel: hub 1-4.2:1.0: USB hub found
jui 15 10:03:46 x280 kernel: hub 1-4.2:1.0: 4 ports detected
jui 15 10:03:46 x280 kernel: usb 2-4.1: Device not responding to setup address.
jui 15 10:03:46 x280 kernel: usb 2-4.1: Device not responding to setup address.
jui 15 10:03:46 x280 kernel: usb 2-4.1: device not accepting address 10, error -71
jui 15 10:03:46 x280 kernel: usb 2-4.1: new SuperSpeed USB device number 11 using xhci_hcd
jui 15 10:03:46 x280 kernel: usb 2-4.1: New USB device found, idVendor=17e9, idProduct=6000, bcdDevice=31.97
jui 15 10:03:46 x280 kernel: usb 2-4.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
jui 15 10:03:46 x280 kernel: usb 2-4.1: Product: USB3.0 5K Graphic Docking
jui 15 10:03:46 x280 kernel: usb 2-4.1: Manufacturer: DisplayLink
jui 15 10:03:46 x280 kernel: usb 2-4.1: SerialNumber: 4310338341262
jui 15 10:03:46 x280 kernel: usb 2-4.1: Warning! Unlikely big volume range (=767), cval->res is probably wrong.
jui 15 10:03:46 x280 kernel: usb 2-4.1: [4] FU [Mic Capture Volume] ch = 2, val = -4592/7680/16
jui 15 10:03:46 x280 kernel: usb 2-4.1: Warning! Unlikely big volume range (=672), cval->res is probably wrong.
jui 15 10:03:46 x280 kernel: usb 2-4.1: [7] FU [USB Audio Playback Volume] ch = 6, val = -10752/0/16
jui 15 10:03:46 x280 kernel: cdc_ncm 2-4.1:1.5: MAC-Address: 80:3f:5d:09:3e:1a
jui 15 10:03:46 x280 kernel: cdc_ncm 2-4.1:1.5: setting rx_max = 16384
jui 15 10:03:46 x280 kernel: cdc_ncm 2-4.1:1.5: setting tx_max = 16384
jui 15 10:03:46 x280 kernel: cdc_ncm 2-4.1:1.5 eth0: register 'cdc_ncm' at usb-0000:00:14.0-4.1, CDC NCM (SEND ZLP), 80:3f:5d:09:3e:1a
jui 15 10:03:46 x280 kernel: usb 1-4.4: new high-speed USB device number 13 using xhci_hcd
jui 15 10:03:47 x280 kernel: usb 2-4.2: new SuperSpeed USB device number 12 using xhci_hcd
jui 15 10:03:47 x280 kernel: usb 2-4.2: New USB device found, idVendor=05e3, idProduct=0620, bcdDevice=93.06
jui 15 10:03:47 x280 kernel: usb 2-4.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
jui 15 10:03:47 x280 kernel: usb 2-4.2: Product: USB3.1 Hub
jui 15 10:03:47 x280 kernel: usb 2-4.2: Manufacturer: GenesysLogic
jui 15 10:03:47 x280 kernel: hub 2-4.2:1.0: USB hub found
jui 15 10:03:47 x280 kernel: hub 2-4.2:1.0: 4 ports detected
jui 15 10:03:47 x280 kernel: cdc_ncm 2-4.1:1.5 enp0s20f0u4u1i5: renamed from eth0
jui 15 10:03:47 x280 kernel: usb 1-4.4: New USB device found, idVendor=046d, idProduct=0836, bcdDevice= 0.10
jui 15 10:03:47 x280 kernel: usb 1-4.4: New USB device strings: Mfr=0, Product=2, SerialNumber=1
jui 15 10:03:47 x280 kernel: usb 1-4.4: Product: B525 HD Webcam
jui 15 10:03:47 x280 kernel: usb 1-4.4: SerialNumber: C95FC680
jui 15 10:03:47 x280 kernel: usb 1-4.4: Warning! Unlikely big volume range (=6144), cval->res is probably wrong.
jui 15 10:03:47 x280 kernel: usb 1-4.4: [5] FU [Mic Capture Volume] ch = 1, val = 1536/7680/1
jui 15 10:03:47 x280 kernel: usb 1-4.4: Found UVC 1.00 device B525 HD Webcam (046d:0836)
```

</details>

**Pull request merged**
