### PR TITLE
atlas: 0.14.1 -> 0.15.0

### LINKED ISSUE #267136: Update request: Atlas  0.14.1→ 0.15.0
- Package name: atlas
- Latest released version: 0.15.0

- Current version on the unstable channel: 0.14.1
- Current version on the stable/release channel: Not packaged

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@marsam 

-----

Note for maintainers: Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by aaronjheng**
## Description of changes

Fixes #267136

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by W1M0R** [comment]
This worked for me, thanks.

**Review by marsam — APPROVED** [review]
Thanks a lot!

**Comment by W1M0R** [comment]
Is it normal for the `atlas login` command to be missing from this build?

image

**Comment by aaronjheng** [comment]
My guess is that this command is not included in the community edition.

**Comment by W1M0R** [comment]
Thanks, it looks like you are right:

1. https://atlasgo.io/cli-reference#distributed-binaries

image

For those who need the cloud features, this derivation does the trick:

```nix
{ stdenv, fetchurl, lib, autoPatchelfHook }:


stdenv.mkDerivation rec {
    owner = "ariga";
    pname = "atlas";
    version = "0.15.0";

    src = fetchurl {
        url = "https://release.ariga.io/atlas/atlas-linux-amd64-v${version}";
        sha256 = "sha256-lLRLdtExG8Xklo+PTBjHGqJOIHhW18RX3gTqchEVQ5Q=";
    };

    dontUnpack = true;

    nativeBuildInputs = [
        autoPatchelfHook
    ];

    installPhase = ''
    runHook preInstall
    install -m755 -D $src $out/bin/atlas
    runHook postInstall
    '';

    meta = with lib; {
        # license = licenses.asl20;
        # homepage = "https://github.com/ariga/atlas";
        homepage = "https://atlasgo.io/";
        changelog = "https://github.com/ariga/atlas/releases/tag/v${version}";
        description = "A modern tool for managing database schemas";
        # maintainers = with maintainers; [ w1m0r ];
        mainProgram = "atlas";
    };
}
```

**Pull request merged**
