### PR TITLE
freeplane: 1.9.14 -> 1.10.5; refactor

### PR DESCRIPTION
**Pull request by yuuyins**
###### Description of changes

#177199

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by yuuyins** [comment]
@GrahamcOfBorg build test

**Comment by yuuyins** [comment]
@GrahamcOfBorg build all

**Comment by charles-dyfis-net** [comment]
Most immediate problem wrt not trying to build is that `platforms.linux` is not a specific platform, it's a _list_ of platforms, so right now we're making the metadata a list of lists.

Also, `mimetype` needs to be `mimeTypes`, and if using `hash = ` rather than `sha256 =`, one should use `lib.fakeHash` rather than `lib.fakeSha256`.

There are some other build problems I haven't run down yet.

**Comment by charles-dyfis-net** [comment]
Well, this is not pretty: the build target is now Java SE 15, so JDK 11 is too old; but the set of JDKs shipped jumps from 11 to 17, and 17 isn't supported without a newer version of Gradle, which the build scripts for freeplane 1.10.5 don't support.

**Comment by yuuyins** [comment]
@GrahamcOfBorg build

**Comment by yuuyins** [comment]
@charles-dyfis-net so this commit in 1.10.5 doesn't help for supporting java 1.8 on Linux https://github.com/freeplane/freeplane/commit/3b4e83d9e4a8e8484f920367e86f1ccaafa984a3 ? well we could try overrideAttrs the jdk to 15.

this might require some effort. so i will leave it for now; i may only have time to deal with it 1 to 2 months from now

**Comment by yuuyins** [comment]
@GrahamcOfBorg build

**Comment by charles-dyfis-net** [comment]
> @charles-dyfis-net so this commit in 1.10.5 doesn't help for supporting java 1.8 on Linux [freeplane/freeplane@3b4e83d](https://github.com/freeplane/freeplane/commit/3b4e83d9e4a8e8484f920367e86f1ccaafa984a3) ? well we could try overrideAttrs the jdk to 15.

Interesting. Indeed, that _did_ make the release, so I don't know why it didn't work. I might take a closer look over the weekend.

**Comment by yuuyins** [comment]
https://github.com/NixOS/nixpkgs/pull/244937

**Pull request closed without merging**
