### PR TITLE
rhash: fix static build

### PR DESCRIPTION
**Pull request by alyssais**
###### Motivation for this change

This is an alternative implementation of #121483, which is able to be much simpler since it incorporates #126620.

Draft until #126620 is merged.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alyssais** [comment]
Remember to only look at the second commit :)

**Review by Ericson2314 — APPROVED** [review]

**Comment by jonringer** [comment]
I believe this still requires my patch:
```
configure flags: --prefix=/nix/store/x90cld543w4jsm1p7q2y8dws420nh168-rhash-static-x86_64-unknown-linux-musl-1.4.1 --disable-shared --enable-static --disable-shared
configure flags: --prefix=/nix/store/x90cld543w4jsm1p7q2y8dws420nh168-rhash-static-x86_64-unknown-linux-musl-1.4.1 --disable-shared --enable-static --disable-shared
which: no jot in (/nix/store/zwq4fbn3dcjpr0d1zs4h85ap8613ca2r-which-2.21/bin:/nix/store/qwzy0lxzszaldlmnn793isndbgxq6s48-patchelf-0.12/bin:/nix/store/yyvzyqzdbrpg2b9h2gf7f5381b0x6pni-x86_64-unknown-linux-musl-stage-final-gcc-wrapper-10.3.0/bin:/nix/store/yq9pnnndns29041pb2apr37c6zv9ay07-x86_64-unknown-linux-musl-stage-final-gcc-10.3.0/bin:/nix/store/jw646r0pmdj81mgx6114kxrjzma8jnbb-musl-static-x86_64-unknown-linux-musl-1.2.2/bin:/nix/store/ymd5zsm7alarzzcq3fm7ds0d9q34b2ah-coreutils-8.32/bin:/nix/store/pacdklpqwlrqdxy105gr059nank6qji6-x86_64-unknown-linux-musl-binutils-wrapper-2.35.1/bin:/nix/store/riwh877kwq68vnvicm65akj70wby9h72-x86_64-unknown-linux-musl-binutils-2.35.1/bin:/nix/store/ymd5zsm7alarzzcq3fm7ds0d9q34b2ah-coreutils-8.32/bin:/nix/store/5gapd51wqnlm3m8dl931a1hz6859b6sz-findutils-4.7.0/bin:/nix/store/d3jd07315h1ddsvk0r6y3ab9gz7sbisa-diffutils-3.7/bin:/nix/store/wc4rb6qlg1lgaq5xmnmib3pa5v0444jc-gnused-4.8/bin:/nix/store/zjm9vvi8a4id3jkaq5jl6w50sgh1k50m-gnugrep-3.6/bin:/nix/store/2sf4bx7003q1h4g009ja3mgzkfyc7xxb-gawk-5.1.0/bin:/nix/store/ii4g46lr5pji9iymk929sqc8g9jyzdif-gnutar-1.34/bin:/nix/store/axqclwm1lf0x0i5y5vgx3k16qrzs6lck-gzip-1.10/bin:/nix/store/d143hdlqp5alcsmkxb0ybvaqp0hxki6a-bzip2-1.0.6.0.2-bin/bin:/nix/store/lymrb7r79x2qragq3wb30x9ng8mikaf2-gnumake-4.3/bin:/nix/store/7gcsgf1km51nxh7ryaz8v6424v2vih47-bash-4.4-p23/bin:/nix/store/0y77m432pmcgqm5kd0g6jrcp64xivs8k-patch-2.7.6/bin:/nix/store/c303y1gwdfz06g0in6fgk31qc0frg1j0-xz-5.2.5-bin/bin)
which: no jot in (/nix/store/zwq4fbn3dcjpr0d1zs4h85ap8613ca2r-which-2.21/bin:/nix/store/qwzy0lxzszaldlmnn793isndbgxq6s48-patchelf-0.12/bin:/nix/store/yyvzyqzdbrpg2b9h2gf7f5381b0x6pni-x86_64-unknown-linux-musl-stage-final-gcc-wrapper-10.3.0/bin:/nix/store/yq9pnnndns29041pb2apr37c6zv9ay07-x86_64-unknown-linux-musl-stage-final-gcc-10.3.0/bin:/nix/store/jw646r0pmdj81mgx6114kxrjzma8jnbb-musl-static-x86_64-unknown-linux-musl-1.2.2/bin:/nix/store/ymd5zsm7alarzzcq3fm7ds0d9q34b2ah-coreutils-8.32/bin:/nix/store/pacdklpqwlrqdxy105gr059nank6qji6-x86_64-unknown-linux-musl-binutils-wrapper-2.35.1/bin:/nix/store/riwh877kwq68vnvicm65akj70wby9h72-x86_64-unknown-linux-musl-binutils-2.35.1/bin:/nix/store/ymd5zsm7alarzzcq3fm7ds0d9q34b2ah-coreutils-8.32/bin:/nix/store/5gapd51wqnlm3m8dl931a1hz6859b6sz-findutils-4.7.0/bin:/nix/store/d3jd07315h1ddsvk0r6y3ab9gz7sbisa-diffutils-3.7/bin:/nix/store/wc4rb6qlg1lgaq5xmnmib3pa5v0444jc-gnused-4.8/bin:/nix/store/zjm9vvi8a4id3jkaq5jl6w50sgh1k50m-gnugrep-3.6/bin:/nix/store/2sf4bx7003q1h4g009ja3mgzkfyc7xxb-gawk-5.1.0/bin:/nix/store/ii4g46lr5pji9iymk929sqc8g9jyzdif-gnutar-1.34/bin:/nix/store/axqclwm1lf0x0i5y5vgx3k16qrzs6lck-gzip-1.10/bin:/nix/store/d143hdlqp5alcsmkxb0ybvaqp0hxki6a-bzip2-1.0.6.0.2-bin/bin:/nix/store/lymrb7r79x2qragq3wb30x9ng8mikaf2-gnumake-4.3/bin:/nix/store/7gcsgf1km51nxh7ryaz8v6424v2vih47-bash-4.4-p23/bin:/nix/store/0y77m432pmcgqm5kd0g6jrcp64xivs8k-patch-2.7.6/bin:/nix/store/c303y1gwdfz06g0in6fgk31qc0frg1j0-xz-5.2.5-bin/bin)
unknown option --disable-shared
unknown option --disable-shared
```

**Comment by jonringer** [comment]
should be able to rebase on latest staging now

**Review by jonringer — APPROVED** [review]
LGTM

```
$ nix-build ./nixpkgs/ -A pkgsStatic.rhash
/nix/store/pp0sfkhwxbb6qyl01lypj81yv0078n75-rhash-static-x86_64-unknown-linux-musl-1.4.1
```

**Pull request merged**
