### PR TITLE
simutrans: 120.2.2 -> 120.4.1

### PR DESCRIPTION
**Pull request by phile314**
###### Motivation for this change

Fix broken build.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by pschuprikov** [comment]
Build works, but I get the following error when I try to run `simutrans`:

```
Error: Cannot open 'font/prop.fnt'
Error: Cannot open 'font/prop.fnt'
No fonts found!Error: No fonts found!
```

**Comment by phile314** [comment]
Strange. For me,it does start, even if I use a pure nix-shell. Can you start it with `simutrans -debug 3` and post the entire output? Do you have Nix or NixOS? Which version?

**Comment by pschuprikov** [comment]
__nix-info -m:__
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.25, NixOS, 20.03beta687.16dd1df0817 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(pschuprikov): `""`
 - channels(root): `"nixos-20.03beta687.16dd1df0817, nixos-stable-19.09.2284.bf7c0f0461e, nixos-unstable-20.09pre217537.d96bd3394b7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

__simutrans -debug 5__ doesn't get much more talkative:

```
Use work dir /nix/store/1vic2mmap93ahpmq5h957ddi3abwjmi1-simutrans-120.4.1/bin/
Reading low level config data ...
Simutrans version 120.4.1 from Sep 23 2018
SDL_driver=x11, hw_available=0, video_mem=0, blit_sw=0, bpp=32, bytes=4
Screen Flags: requested=10, actual=10
dr_os_open(SDL): SDL realized screen size width=704, height=560 (requested w=704, h=560)
Error: Cannot open 'font/prop.fnt'
Error: Cannot open 'font/prop.fnt'
No fonts found!Error: No fonts found!
```

Running __simutrans__ from `/nix/store/1vic2mmap93ahpmq5h957ddi3abwjmi1-simutrans-120.4.1/share/simutrans` with the `-use_workdir` does _not_ give that error.

**Comment by phile314** [comment]
This is getting confusing. I removed my `~/.simutrans` directory, but running `result/bin/simutrans` still works for me.

The startup script always sets `use_workdir`, so I do not understand why the work directory is `/nix/store/1vic2mmap93ahpmq5h957ddi3abwjmi1-simutrans-120.4.1/bin/` in your log.

Can you post the content of `/nix/store/rhfdrmv5z8w1gy7dzwbpmqwx14yg6p74-simutrans-120.4.1/bin/simutrans`? What hapens if you run that? How are you building simutrans? `nix-build . -A simutrans` ?

**Comment by pschuprikov** [comment]
> The startup script always sets `use_workdir`

Thanks! It made me check what `nixpkgs-review` did. Turns out it has't included `simultrans` into the `nix-shell`. Everything works runs just fine now, thanks for the build fix!

**Review by vcunat — APPROVED** [review]
Thanks!  I also updated the graphics packages in 16a3feb65 (minor).

**Pull request merged**
