### PR TITLE
audacity: fix library path

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

audacity cannot find the ```lame``` and ```ffmpeg``` libraries, so we wrap the binary.

###### Things done

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by abbradar** [comment]
It may be better to do `NIX_LDFLAGS = [ "-lflac" ... ];` instead -- this way it won't leak to subprocesses and doesn't require a wrapper.

**Comment by LnL7** [comment]
@abbradar interesting, that fixes the binary at runtime?

**Comment by abbradar** [comment]
@LnL7 Should be -- it would link the library to all the produced binaries, so `dlopen` finds them without any other measures.

**Comment by LnL7** [comment]
@abbradar any idea where that happens?

**Comment by abbradar** [comment]
@LnL7 You mean where `NIX_LDFLAGS` is used? Look at our compiler wrappers, specifically `pkgs/build-support/cc-wrapper/ld-wrapper.sh`.

**Comment by peterhoeg** [comment]
Thanks for the pointer @abbradar. Much more elegant!

**Comment by abbradar** [comment]
As a side note, I don't think we should fix `file` warnings case by case (it should be either fixed everywhere which is not happening or left as is since it's harmless), but that's just my IMHO. Let's merge, thanks!

**Pull request merged**
