### PR TITLE
redpanda: mark broken

### PR DESCRIPTION
**Pull request by happysalada**
## Description of changes

redpanda has been broken for a while now, it's time to mark it officially broken until someone has time to fix the build.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
coming after https://github.com/NixOS/nixpkgs/issues/253529 was reported.

**Comment by OPNA2608** [comment]
Did you intend to mark `redpanda` (`pkgs/servers/redpanda/default.nix`) instead of `redpanda-server` (`pkgs/servers/redpanda/server.nix`)? The linked issue is about `redpanda-server`. On master, `redpanda` builds fine if unmarked, while `redpanda-server` isn't marked and still fails.

**Comment by happysalada** [comment]
redpanda server should also be marked as broken.
redpanda contains just a simple client to interact with a redpanda server, the package should probably be renamed. I'm going to rename this package and remove the broken label and mark the server as broken.
Thank you for reporting!

**Comment by happysalada** [comment]
@OPNA2608 let me know if you have time to check https://github.com/NixOS/nixpkgs/pull/260872

**Pull request merged**
