### PR TITLE
llvmPackages_12: Finalize reorganizing the files

### PR DESCRIPTION
**Pull request by primeos**
###### Motivation for this change

Now it is more consistent.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by primeos** [comment]
@GrahamcOfBorg build llvmPackages_12

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 120506` at e4f8498c run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built successfully:</summary>
  <ul>
    <li>llvmPackages_12.libcxx</li>
    <li>llvmPackages_12.libcxxClang</li>
    <li>llvmPackages_12.libcxxStdenv</li>
    <li>llvmPackages_12.libcxxabi</li>
    <li>llvmPackages_12.lldClang</li>
  </ul>
</details>

**Comment by Ericson2314** [comment]
I would much prefer if changes like this were to all the LLVMs. Maybe it's more consistent within LLVM 12, but it's less consistent across versions, and that makes maintenance harder.

(We should try to dedup some things too, which also would prevent drift.)

**Comment by primeos** [comment]
Applying it to all LLVM versions might help for some changes (and should at least be easy to do, if necessary) but our LLVM expressions are already pretty unmaintained (I don't think there's even one active maintainer) and seem to need some serious cleanup.
Anyway, agreed that it would be helpful but IMO LLVM is already more (or less) bit rotting and I'm currently attempting to make more aggressive changes to recent versions in the hopes of preventing it from becoming a lost cause. However, what we'd really need is a proper team of active maintainers for LLVM.

**Comment by Ericson2314** [comment]
@primeos I have a rather large cleanup I'm doing in https://github.com/NixOS/nixpkgs/pull/111487. I have normalized many things already. I just would rather this be normalized separately than make that one even bigger.

**Comment by primeos** [comment]
> I would much prefer if changes like this were to all the LLVMs.

I agree with that now. I wasn't aware of PRs like #111487 (the ones I've seen usually only touched a single LLVM version to fix something the author cared about) and I'll keep it in mind for the next time. And thanks for looking after our LLVM packaging! :)

**Comment by Ericson2314** [comment]
@primeos yeah it's fight I've taken to various compilers with lots of copy-paste from time to time. Did GCC and GHC in the paste.

**Pull request merged**
