### PR TITLE
Fix cargo sha

### LINKED ISSUE #8566: Cargo build yields a sha256 mismatch
Using:

```
$ nix-shell -p cargo
```

I get the following:

```
output path ‘/nix/store/qmp7gabngcaqvndl5andafpvispi90mb-cargo-d814fcb’ should have r:sha256 hash ‘0sppd3x2cacmbnypcjip44amnh66lrrbwwzsbz8rqf3nq2ah496x’, instead has ‘1c9h5qiwfq0f7z9rpfkl23il4qlfm6bk97c78gk7ish6gsy9c1d7’
cannot build derivation ‘/nix/store/bcin2sfxmgjm3f8j9jxkcpykihcclj18-cargo-2015-05-13.drv’: 1 dependencies couldn't be built
```

Nix 1.9 on Ubuntu.

CC maintainer @wizeman

### PR DESCRIPTION
**Pull request by globin**
fixes #8566

[Review on Reviewable](https://reviewable.io/reviews/nixos/nixpkgs/8862)

### CODE REVIEW

**Comment by globin** [comment]
cc @wizeman

**Comment by vcunat** [comment]
My fetch is getting yet another hash ``16f371jj89xplfc1fygvvhyhrq634v0w9674gz6j06m7blxqylpx``. Do you know if ``leaveDotGit`` is needed? #8567.

**Comment by wizeman** [comment]
@vcunat I just tried to build without `leaveDotGit` and it seems to build and work fine, apart from some error messages during the build due to the lack of a `.git` directory, and the lack of the git commit in the output of `cargo --version`.

Since the `leaveDotGit` is causing more problems than it solves, I think I will remove it instead of merging this PR to update the hash once again. I will close this PR later when I push the fix.

BTW, the `leaveDotGit` was introduced by @madjar, so maybe he can clarify if anything else could be broken.

**Comment by madjar** [comment]
It was package a long time ago, before cargo even had a its 0.1.0 release, so git was pretty much the only way to have a version. Since it now has stable releases, that's not needed anymore. We could even use the github tarball with the same effect.

**Pull request closed without merging**
