### PR TITLE
babashka: sync native-image arguments with upstream

### PR DESCRIPTION
**Pull request by thiagokokada**
###### Motivation for this change

This commit syncs the arguments passed to the babashka with upstream: https://github.com/babashka/babashka/blob/77daea7362d8e2562c89c315b1fbcefde6fa56a5/script/compile#L41-L74

The idea here is to enable more features and reduce the number of issues compared to upstream.

Also add some tests to ensure everything is working.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by thiagokokada** [comment]
CC @bennyandresen @bhougland18 @DerGuteMoritz @jlesquembre.

**Comment by jlesquembre** [comment]
thanks @thiagokokada 
I didn't test the binary, but the changes look good to me. Just a small suggestion, could you add a comment with a link to 
https://github.com/babashka/babashka/blob/master/script/compile ?
Just to make easier to remember from where the options are coming

**Comment by thiagokokada** [comment]
> thanks @thiagokokada
> I didn't test the binary, but the changes look good to me. Just a small suggestion, could you add a comment with a link to
> https://github.com/babashka/babashka/blob/master/script/compile ?
> Just to make easier to remember from where the options are coming

Makes sense, I will just use the specific commit to avoid breakage in the future (in case this script move places, for example).

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 114467` at a639b424 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/befecca980ab16e72544fdbc323139e0">babashka</a></li></li>
    <li><a href="https://gist.github.com/28d98d3a46daca991e02dc39e8e98815">clojure-lsp</a></li></li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/development/interpreters/clojure/babashka.nix:27:3:
```
   |
27 |   buildPhase = ''
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/development/interpreters/clojure/babashka.nix:67:3:
```
   |
67 |   installPhase = ''
   |   ^
```
</li>
  </ul>
</details>

**Review by jlesquembre — APPROVED** [review]

**Pull request merged**
