### PR TITLE
buildbot: 2.3.0 -> 2.3.1

### PR DESCRIPTION
**Pull request by lopsided98**
Updates buildbot to the latest version.

I was not able to run the NixOS test on master due to #63627, which broke the test infrastructure, but the test passed on unstable.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by veprbl** [comment]
cc maintainers @nand0p @ryansydnor
@GrahamcOfBorg build buildbot buildbot-full buildbot-worker buildbot-ui
Resolves: #63483

**Comment by vcunat** [comment]
The gstreamer problem should be fixed on current master.

**Comment by veprbl** [comment]
@GrahamcOfBorg test buildbot

**Review by veprbl — APPROVED** [review]
Passes nix-review on x86_64-linux and x86_64-darwin. NixOS test passes too.

**Pull request merged**
