### PR TITLE
plasma5: 5.22.3 -> 5.22.4

### PR DESCRIPTION
**Pull request by greydot**
###### Motivation for this change

Update plasma5 to the latest stable release.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by greydot** [comment]
Dunno why you guys didn't include this into https://github.com/NixOS/nixpkgs/pull/127389

But here you go :)

**Comment by jansol** [comment]
The pool of people who could make changes to that previous PR is limited, merging it was going nowhere for ages and the diff was pretty large already due to other fixes that were needed with the 5.22 update. Personally I think it was better to get it merged with or without this update so things can finally move forward.

This should be a lot faster to get in, due to to being a fairly straightforward point release.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 132773` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
110 packages marked as broken and skipped:
</summary>
<ul>
<li>libsForQt512.applet-window-buttons</li>
<li>libsForQt512.bluedevil</li>
<li>libsForQt512.breeze-grub</li>
<li>libsForQt512.breeze-gtk</li>
<li>libsForQt512.breeze-plymouth</li>
<li>libsForQt512.breeze-qt5</li>
<li>libsForQt512.discover</li>
<li>libsForQt512.kactivitymanagerd</li>
<li>libsForQt512.kde-cli-tools</li>
<li>libsForQt512.kde-gtk-config</li>
<li>libsForQt512.kde2-decoration</li>
<li>libsForQt512.kdecoration</li>
<li>libsForQt512.kdenlive</li>
<li>libsForQt512.kdeplasma-addons</li>
<li>libsForQt512.kgamma5</li>
<li>libsForQt512.khotkeys</li>
<li>libsForQt512.kinfocenter</li>
<li>libsForQt512.kmenuedit</li>
<li>libsForQt512.krohnkite</li>
<li>libsForQt512.kscreen</li>
<li>libsForQt512.kscreenlocker</li>
<li>libsForQt512.ksshaskpass</li>
<li>libsForQt512.ksystemstats</li>
<li>libsForQt512.kwallet-pam</li>
<li>libsForQt512.kwayland-integration</li>
<li>libsForQt512.kwayland-server</li>
<li>libsForQt512.kwin</li>
<li>libsForQt512.kwin-dynamic-workspaces</li>
<li>libsForQt512.kwin-tiling</li>
<li>libsForQt512.kwrited</li>
<li>libsForQt512.layer-shell-qt</li>
<li>libsForQt512.libkscreen</li>
<li>libsForQt512.libksysguard</li>
<li>libsForQt512.milou</li>
<li>libsForQt512.oxygen</li>
<li>libsForQt512.parachute</li>
<li>libsForQt512.plasma-browser-integration</li>
<li>libsForQt512.plasma-desktop</li>
<li>libsForQt512.plasma-disks</li>
<li>libsForQt512.plasma-integration</li>
<li>libsForQt512.plasma-nm</li>
<li>libsForQt512.plasma-pa</li>
<li>libsForQt512.plasma-sdk</li>
<li>libsForQt512.plasma-systemmonitor</li>
<li>libsForQt512.plasma-thunderbolt</li>
<li>libsForQt512.plasma-vault</li>
<li>libsForQt512.plasma-workspace</li>
<li>libsForQt512.plasma-workspace-wallpapers</li>
<li>libsForQt512.polkit-kde-agent</li>
<li>libsForQt512.powerdevil</li>
<li>libsForQt512.qqc2-breeze-style</li>
<li>libsForQt512.sddm-kcm</li>
<li>libsForQt512.spectacle</li>
<li>libsForQt512.systemsettings</li>
<li>libsForQt512.xdg-desktop-portal-kde</li>
<li>libsForQt514.applet-window-buttons</li>
<li>libsForQt514.bluedevil</li>
<li>libsForQt514.breeze-grub</li>
<li>libsForQt514.breeze-gtk</li>
<li>libsForQt514.breeze-plymouth</li>
<li>libsForQt514.breeze-qt5</li>
<li>libsForQt514.discover</li>
<li>libsForQt514.kactivitymanagerd</li>
<li>libsForQt514.kde-cli-tools</li>
<li>libsForQt514.kde-gtk-config</li>
<li>libsForQt514.kde2-decoration</li>
<li>libsForQt514.kdecoration</li>
<li>libsForQt514.kdenlive</li>
<li>libsForQt514.kdeplasma-addons</li>
<li>libsForQt514.kgamma5</li>
<li>libsForQt514.khotkeys</li>
<li>libsForQt514.kinfocenter</li>
<li>libsForQt514.kmenuedit</li>
<li>libsForQt514.krohnkite</li>
<li>libsForQt514.kscreen</li>
<li>libsForQt514.kscreenlocker</li>
<li>libsForQt514.ksshaskpass</li>
<li>libsForQt514.ksystemstats</li>
<li>libsForQt514.kwallet-pam</li>
<li>libsForQt514.kwayland-integration</li>
<li>libsForQt514.kwayland-server</li>
<li>libsForQt514.kwin</li>
<li>libsForQt514.kwin-dynamic-workspaces</li>
<li>libsForQt514.kwin-tiling</li>
<li>libsForQt514.kwrited</li>
<li>libsForQt514.layer-shell-qt</li>
<li>libsForQt514.libkscreen</li>
<li>libsForQt514.libksysguard</li>
<li>libsForQt514.milou</li>
<li>libsForQt514.oxygen</li>
<li>libsForQt514.parachute</li>
<li>libsForQt514.plasma-browser-integration</li>
<li>libsForQt514.plasma-desktop</li>
<li>libsForQt514.plasma-disks</li>
<li>libsForQt514.plasma-integration</li>
<li>libsForQt514.plasma-nm</li>
<li>libsForQt514.plasma-pa</li>
<li>libsForQt514.plasma-sdk</li>
<li>libsForQt514.plasma-systemmonitor</li>
<li>libsForQt514.plasma-thunderbolt</li>
<li>libsForQt514.plasma-vault</li>
<li>libsForQt514.plasma-workspace</li>
<li>libsForQt514.plasma-workspace-wallpapers</li>
<li>libsForQt514.polkit-kde-agent</li>
<li>libsForQt514.powerdevil</li>
<li>libsForQt514.qqc2-breeze-style</li>
<li>libsForQt514.sddm-kcm</li>
<li>libsForQt514.spectacle</li>
<li>libsForQt514.systemsettings</li>
<li>libsForQt514.xdg-desktop-portal-kde</li>
</ul>
</details>
<details>

  <summary>4 packages failed to build and are new build failures:</summary>
  <ul>
<li>digikam: log was empty</li>
<li>libsForQt5.plasma-vault: log was empty</li>
<li>(libsForQt515.plasma-vault: log was empty</li>
<li>,plasma5Packages.plasma-vault): log was empty</li>
  </ul>
</details>
<details>
<summary>
63 packages built:
</summary>
<ul>
<li>haruna</li>
<li>index-fm</li>
<li>kdev-php</li>
<li>kdev-python</li>
<li>kdevelop</li>
<li>kdevelop-unwrapped</li>
<li>libsForQt5.applet-window-buttons (libsForQt515.applet-window-buttons ,plasma5Packages.applet-window-buttons)</li>
<li>libsForQt5.bluedevil (libsForQt515.bluedevil ,plasma5Packages.bluedevil)</li>
<li>libsForQt5.breeze-grub (libsForQt515.breeze-grub ,plasma5Packages.breeze-grub)</li>
<li>libsForQt5.breeze-gtk (libsForQt515.breeze-gtk ,plasma5Packages.breeze-gtk)</li>
<li>libsForQt5.breeze-plymouth (libsForQt515.breeze-plymouth ,plasma5Packages.breeze-plymouth)</li>
<li>libsForQt5.breeze-qt5 (libsForQt515.breeze-qt5 ,plasma5Packages.breeze-qt5)</li>
<li>libsForQt5.discover (libsForQt515.discover ,plasma5Packages.discover)</li>
<li>libsForQt5.kactivitymanagerd (libsForQt515.kactivitymanagerd ,plasma5Packages.kactivitymanagerd)</li>
<li>libsForQt5.kde-cli-tools (libsForQt515.kde-cli-tools ,plasma5Packages.kde-cli-tools)</li>
<li>libsForQt5.kde-gtk-config (libsForQt515.kde-gtk-config ,plasma5Packages.kde-gtk-config)</li>
<li>libsForQt5.kde2-decoration (libsForQt515.kde2-decoration ,plasma5Packages.kde2-decoration)</li>
<li>libsForQt5.kdecoration (libsForQt515.kdecoration ,plasma5Packages.kdecoration)</li>
<li>libsForQt5.kdenlive (libsForQt515.kdenlive ,plasma5Packages.kdenlive)</li>
<li>libsForQt5.kdeplasma-addons (libsForQt515.kdeplasma-addons ,plasma5Packages.kdeplasma-addons)</li>
<li>libsForQt5.kgamma5 (libsForQt515.kgamma5 ,plasma5Packages.kgamma5)</li>
<li>libsForQt5.khotkeys (libsForQt515.khotkeys ,plasma5Packages.khotkeys)</li>
<li>libsForQt5.kinfocenter (libsForQt515.kinfocenter ,plasma5Packages.kinfocenter)</li>
<li>libsForQt5.kmenuedit (libsForQt515.kmenuedit ,plasma5Packages.kmenuedit)</li>
<li>libsForQt5.krohnkite (libsForQt515.krohnkite ,plasma5Packages.krohnkite)</li>
<li>libsForQt5.kscreen (libsForQt515.kscreen ,plasma5Packages.kscreen)</li>
<li>libsForQt5.kscreenlocker (libsForQt515.kscreenlocker ,plasma5Packages.kscreenlocker)</li>
<li>libsForQt5.ksshaskpass (libsForQt515.ksshaskpass ,plasma5Packages.ksshaskpass)</li>
<li>libsForQt5.ksystemstats (libsForQt515.ksystemstats ,plasma5Packages.ksystemstats)</li>
<li>libsForQt5.kwallet-pam (libsForQt515.kwallet-pam ,plasma5Packages.kwallet-pam)</li>
<li>libsForQt5.kwayland-integration (libsForQt515.kwayland-integration ,plasma5Packages.kwayland-integration)</li>
<li>libsForQt5.kwayland-server (libsForQt515.kwayland-server ,plasma5Packages.kwayland-server)</li>
<li>libsForQt5.kwin (libsForQt515.kwin ,plasma5Packages.kwin)</li>
<li>libsForQt5.kwin-dynamic-workspaces (libsForQt515.kwin-dynamic-workspaces ,plasma5Packages.kwin-dynamic-workspaces)</li>
<li>libsForQt5.kwin-tiling (libsForQt515.kwin-tiling ,plasma5Packages.kwin-tiling)</li>
<li>libsForQt5.kwrited (libsForQt515.kwrited ,plasma5Packages.kwrited)</li>
<li>libsForQt5.layer-shell-qt (libsForQt515.layer-shell-qt ,plasma5Packages.layer-shell-qt)</li>
<li>libsForQt5.libkscreen (libsForQt515.libkscreen ,plasma5Packages.libkscreen)</li>
<li>libsForQt5.libksysguard (libsForQt515.libksysguard ,plasma5Packages.libksysguard)</li>
<li>libsForQt5.milou (libsForQt515.milou ,plasma5Packages.milou)</li>
<li>libsForQt5.oxygen (libsForQt515.oxygen ,plasma5Packages.oxygen)</li>
<li>libsForQt5.parachute (libsForQt515.parachute ,plasma5Packages.parachute)</li>
<li>libsForQt5.plasma-browser-integration (libsForQt515.plasma-browser-integration ,plasma5Packages.plasma-browser-integration)</li>
<li>libsForQt5.plasma-desktop (libsForQt515.plasma-desktop ,plasma5Packages.plasma-desktop)</li>
<li>libsForQt5.plasma-disks (libsForQt515.plasma-disks ,plasma5Packages.plasma-disks)</li>
<li>libsForQt5.plasma-integration (libsForQt515.plasma-integration ,plasma5Packages.plasma-integration)</li>
<li>libsForQt5.plasma-nm (libsForQt515.plasma-nm ,plasma5Packages.plasma-nm)</li>
<li>libsForQt5.plasma-pa (libsForQt515.plasma-pa ,plasma5Packages.plasma-pa)</li>
<li>libsForQt5.plasma-sdk (libsForQt515.plasma-sdk ,plasma5Packages.plasma-sdk)</li>
<li>libsForQt5.plasma-systemmonitor (libsForQt515.plasma-systemmonitor ,plasma5Packages.plasma-systemmonitor)</li>
<li>libsForQt5.plasma-thunderbolt (libsForQt515.plasma-thunderbolt ,plasma5Packages.plasma-thunderbolt)</li>
<li>libsForQt5.plasma-workspace (libsForQt515.plasma-workspace ,plasma5Packages.plasma-workspace)</li>
<li>libsForQt5.plasma-workspace-wallpapers (libsForQt515.plasma-workspace-wallpapers ,plasma5Packages.plasma-workspace-wallpapers)</li>
<li>libsForQt5.polkit-kde-agent (libsForQt515.polkit-kde-agent ,plasma5Packages.polkit-kde-agent)</li>
<li>libsForQt5.powerdevil (libsForQt515.powerdevil ,plasma5Packages.powerdevil)</li>
<li>libsForQt5.qqc2-breeze-style (libsForQt515.qqc2-breeze-style ,plasma5Packages.qqc2-breeze-style)</li>
<li>libsForQt5.sddm-kcm (libsForQt515.sddm-kcm ,plasma5Packages.sddm-kcm)</li>
<li>libsForQt5.spectacle (libsForQt515.spectacle ,plasma5Packages.spectacle)</li>
<li>libsForQt5.systemsettings (libsForQt515.systemsettings ,plasma5Packages.systemsettings)</li>
<li>libsForQt5.xdg-desktop-portal-kde (libsForQt515.xdg-desktop-portal-kde ,plasma5Packages.xdg-desktop-portal-kde)</li>
<li>lxqt.lxqt-config</li>
<li>plasma-applet-volumewin7mixer</li>
<li>wacomtablet</li>
</ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 132773` at 167b6f77 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>162 packages skipped due to time constraints:</summary>
  <ul>
    <li>digikam</li>
    <li>kdev-php</li>
    <li>kdev-python</li>
    <li>kdevelop-unwrapped</li>
    <li>libsForQt5.bluedevil (libsForQt515.bluedevil ,plasma5Packages.bluedevil)</li>
    <li>libsForQt5.breeze-grub (libsForQt515.breeze-grub ,plasma5Packages.breeze-grub)</li>
    <li>libsForQt5.breeze-gtk (libsForQt515.breeze-gtk ,plasma5Packages.breeze-gtk)</li>
    <li>libsForQt5.breeze-plymouth (libsForQt515.breeze-plymouth ,plasma5Packages.breeze-plymouth)</li>
    <li>libsForQt5.discover (libsForQt515.discover ,plasma5Packages.discover)</li>
    <li>libsForQt5.kactivitymanagerd (libsForQt515.kactivitymanagerd ,plasma5Packages.kactivitymanagerd)</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>7 packages built successfully:</summary>
  <ul>
    <li>libsForQt5.breeze-qt5 (libsForQt515.breeze-qt5 ,plasma5Packages.breeze-qt5)</li>
    <li>libsForQt5.kde2-decoration (libsForQt515.kde2-decoration ,plasma5Packages.kde2-decoration)</li>
    <li>libsForQt5.kdecoration (libsForQt515.kdecoration ,plasma5Packages.kdecoration)</li>
    <li>libsForQt5.kscreenlocker (libsForQt515.kscreenlocker ,plasma5Packages.kscreenlocker)</li>
    <li>libsForQt5.layer-shell-qt (libsForQt515.layer-shell-qt ,plasma5Packages.layer-shell-qt)</li>
    <li>libsForQt5.libkscreen (libsForQt515.libkscreen ,plasma5Packages.libkscreen)</li>
    <li>libsForQt5.libksysguard (libsForQt515.libksysguard ,plasma5Packages.libksysguard)</li>
  </ul>
</details>

**Review by ttuegel — APPROVED** [review]

**Pull request merged**
