### PR TITLE
Coq: 8.5pl2 -> 8.5pl3

### PR DESCRIPTION
**Pull request by vbgl**
###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] OS X
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jwiegley** [comment]
Hi @vbgl , can you please make 8.5pl1 and 8.5pl2 still available for the time being under different names?  Not every Coq dependency is automatically compatible with pl3.  For example, when Nix upgraded me to pl2, the project I was working on broke because the dependencies hadn't been updated yet.

So I'd love to have a way to build and use pl3, but I'm not ready for Coq to automatically be switched over to pl3 until everything else is ready for it.

**Comment by jwiegley** [comment]
(The particularly dependency I had problems with was Fiat; which reminds me that I need to update Nix to use the correct current version of Fiat).

**Comment by jwiegley** [comment]
@vbgl I've committed `coqPackages_8_5.fiat_HEAD`, so that we can see if it breaks with 8.5pl3.

**Comment by vbgl** [comment]
Hi John. Thanks for the suggestion. With the last commit, you can get old PL versions by overriding the derivation, e.g., `coq_8_5.override { pl = "2"; }`. Would this be enough or did you have something else in mind?

**Comment by jwiegley** [comment]
@vbgl That's perfect!  Even better than what I had in mind.

**Pull request merged**
