### PR TITLE
haskellPackages.hakyll: make buildable by Hydra

### PR DESCRIPTION
**Pull request by vaibhavsagar**
###### Motivation for this change

https://github.com/NixOS/nixpkgs/pull/104273#discussion_r527318036

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vaibhavsagar** [comment]
Thanks!

**Comment by gnidorah** [comment]
/* hackage-packages.nix is an auto-generated file -- DO NOT EDIT! */
You should
1) Edit `pkgs/development/haskell-modules/configuration-hackage2nix.yaml instead`
2) Target against `haskell-updates` branch
See #73755 as example
cc @peti

**Comment by gnidorah** [comment]
/* hackage-packages.nix is an auto-generated file -- DO NOT EDIT! */

You should remove it from pkgs/development/haskell-modules/configuration-hackage2nix.yaml see #73755

**Comment by cdepillabout** [comment]
@gnidorah Hey, sorry for the confusion here.

The `pkgs/development/haskell-modules/hackage-packages.nix` file is automatically generated using the settings in `pkgs/development/haskell-modules/configuration-hackage2nix.yaml` on the `haskell-updates` branch (and then merged into `master`).

However, after we split off a release, we no longer automatically regenerate/update the `pkgs/development/haskell-modules/hackage-packages.nix` file, so it is necessary to edit it directly.  This only applies for the release branches though.

**Pull request merged**
