### PR TITLE
facetimehd: PCIe webcam support for Macbooks

### PR DESCRIPTION
**Pull request by womfoo**
It's still early days for this driver and users will have to perform the occasional rmmod/modprobe dance.

That being said, it still beats restarting to OSX everytime for video meetings (Hangouts on Firefox and Chromium works).

This seems to behave reasonably on my MacBookPro11,3 running kernels 4.1, 4.2 and 4.3.

### CODE REVIEW

**Comment by womfoo** [comment]
Travis failed due to the test compiling against an unsupported kernel (needs >= 3.19). Any pointers on how we can fix this?

**Comment by bjornfor** [comment]
Don't know how to make travis build with linux >= 3.19. I reviewed the PR, it's OK by me.

**Comment by womfoo** [comment]
Thanks for the review @bjornfor I'll also look into putting some asserts on the package itself and see if that would help when I get some time later this week.

**Comment by womfoo** [comment]
I managed to narrow down the build to cover only >= 3.19 but travis fails due to hitting the max time limit for jobs.

**Comment by womfoo** [comment]
I also wanted to note that nox-review takes ~3.6 hours on my MacbookPro

```
Result in /tmp/nox-review-2ihqi6sm
total 24
lrwxrwxrwx 1 kranium users 73 Jan  6 06:40 result -> /nix/store/32lw3i2a4j07xvqfkdvajdsj2mqwkx9q-facetimehd-git-20160103-4.3.2
lrwxrwxrwx 1 kranium users 68 Jan  6 06:40 result-2 -> /nix/store/rr8rsjbswmjrp11qj4q58px0vhj3qhin-facetimehd-firmware-1.43
lrwxrwxrwx 1 kranium users 73 Jan  6 06:40 result-3 -> /nix/store/32lw3i2a4j07xvqfkdvajdsj2mqwkx9q-facetimehd-git-20160103-4.3.2
lrwxrwxrwx 1 kranium users 75 Jan  6 06:40 result-4 -> /nix/store/6mx6s0y39digvrx8a764kjs1n69xqzms-facetimehd-git-20160103-4.4-rc7
lrwxrwxrwx 1 kranium users 73 Jan  6 06:40 result-5 -> /nix/store/xjwij5j5ksgj9fnc0r9l7r5q8nr29s0g-facetimehd-git-20160103-4.2.6
lrwxrwxrwx 1 kranium users 74 Jan  6 06:40 result-6 -> /nix/store/xdzqz8nishf58fbi63mls5f4dd8xpjpz-facetimehd-git-20160103-4.1.13

real	223m36.753s
user	3m43.222s
sys	0m13.590s
```

Could someone review and LGTM? :)

**Comment by womfoo** [comment]
Rebased changes with the latest driver. Also included module name in the PR title.

**Comment by womfoo** [comment]
looks like github being down ruined the travis build. this builds ok with nox locally.

```
Result in /tmp/nox-review-4xy0gcje
total 36
lrwxrwxrwx 1 kranium users 71 Jan 28 19:06 result -> /nix/store/3rq6vmf3sy8fs66fksjwyk52m53sjxy0-facetimehd-git-20160127-4.4
lrwxrwxrwx 1 kranium users 73 Jan 28 19:06 result-2 -> /nix/store/kjrs3zn21kknyw94c9y35i5jwzc31ri7-facetimehd-git-20160127-4.3.4
lrwxrwxrwx 1 kranium users 73 Jan 28 19:06 result-3 -> /nix/store/6my47cwwnnk8ml2bfzp4ai9k2wwvrfar-facetimehd-git-20160127-4.3.4
lrwxrwxrwx 1 kranium users 73 Jan 28 19:06 result-4 -> /nix/store/65hlhyysdcq055dyw9z9yigj2sh7azds-facetimehd-git-20160127-4.3.4
lrwxrwxrwx 1 kranium users 74 Jan 28 19:06 result-5 -> /nix/store/k71jv4aipfai5k59pn5j35cm0cpp4vy8-facetimehd-git-20160127-4.1.15
lrwxrwxrwx 1 kranium users 75 Jan 28 19:06 result-6 -> /nix/store/imqkv6znf19bspiy7kp2w9kqf248p48f-facetimehd-git-20160127-4.4-rc8
lrwxrwxrwx 1 kranium users 71 Jan 28 19:06 result-7 -> /nix/store/3rq6vmf3sy8fs66fksjwyk52m53sjxy0-facetimehd-git-20160127-4.4
lrwxrwxrwx 1 kranium users 73 Jan 28 19:06 result-8 -> /nix/store/gqxhr66wrn6r8b6slxi3im6j7hfrqkwc-facetimehd-git-20160127-4.3.4
lrwxrwxrwx 1 kranium users 68 Jan 28 19:06 result-9 -> /nix/store/h028bhighnz007bfhna8hzhdajrq0sqb-facetimehd-firmware-1.43

real	114m6.815s
user	0m53.951s
sys	0m4.293s
```

**Comment by womfoo** [comment]
Ohai @puffnfresh @rbvermaa @aaronlevin 

I got feedback from IRC to have other people test this out before merging.

Any chance you are still on a recent Macbook and give this a shot?

Thanks in advance! :-)

**Comment by aaronlevin** [comment]
@womfoo oh, i wish I could help. I don't have a Macbook anymore!

**Comment by womfoo** [comment]
no worries @aaronlevin hopefully I'll hear from the rest :-)

**Comment by puffnfresh** [comment]
@womfoo I've also stopped using Macs but I tweeted this PR out.

**Comment by fpletz** [comment]
:+1: on the code, but I don't have a Mac to test either. I'd like to merge this in a few days if nobody objects. :panda_face:

**Comment by womfoo** [comment]
Awesome! Thanks @puffnfresh @fpletz

**Comment by ttonelli** [comment]
I can confirm that this works on my MacBook Pro 11,3 running kernel 4.4. I just had to blacklist the bdc_pci module to avoid having it take the webcam. The config was basically:

    boot.blacklistedKernelModules = ["bdc_pci"];    // among other blacklisted modules...
    hardware.facetimehd.enable = true;

Finally can have hangouts without an external webcam! Thanks @womfoo for the expression and @rbvermaa for calling my attention that this was finally available!

**Comment by womfoo** [comment]
@ttonelli  thanks for testing and pointing out bdc_pci which I've also blacklisted in configuration.nix.

Anyways, I just added a commit that automatically blacklists it.

**Comment by womfoo** [comment]
Hi @fpletz. So far its just me and @ttonelli who tested this OK. Should we now merge?

**Comment by edwtjo** [comment]
Confirmed on MBP12,4

**Comment by womfoo** [comment]
Thanks @edwtjo

**Pull request merged**
