### PR TITLE
deepin: remove from nixpkgs

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

The [Deepin Desktop Environment (DDE)](https://www.deepin.org/en/dde/) is not yet fully packaged in nixpkgs and it has shown a very difficult task to complete, as discussed in https://github.com/NixOS/nixpkgs/issues/94870. The conclusion is that it is better to completely remove it.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
Seems like a perfect project for a flake.

**Comment by worldofpeace** [comment]
> Seems like a perfect project for a flake.

Indeed, it would be a lot easier to not have in nixpkgs because of its complexity. Though IMHO atm I don't think it should be packaged at all.

**Comment by Ma27** [comment]
I think it would be good to mention this in the release notes and to also add `deepin = throw "...";` to `aliases.nix`.

**Comment by FRidh** [comment]
Merge conflicts.

**Comment by worldofpeace** [comment]
> I think it would be good to mention this in the release notes and to also add `deepin = throw "...";` to `aliases.nix`.

Yeah. This shouldn't have been merged without using

* mkRemovedOptionModule
* a throw
* a release note with the motivation

**Comment by romildo** [comment]
> Yeah. This shouldn't have been merged without using
> 
>     * mkRemovedOptionModule
> 
>     * a throw
> 
>     * a release note with the motivation

Done in PR https://github.com/NixOS/nixpkgs/pull/96879.

**Pull request merged**
