### PR TITLE
Mopidy Improvements

### PR DESCRIPTION
**Pull request by spwhitt**
Please merge https://github.com/NixOS/nixpkgs/pull/11477 first, then I will rebase this on top of it.

@jgillich I guess I misremembered making changes to `mopidy-spotify`, but it works for me regardless. Let me know if it still doesn't work for you..

### CODE REVIEW

**Comment by rickynils** [comment]
@spwhitt #11477 has been merged, please rebase

**Comment by spwhitt** [comment]
Rebased onto master and added commit which fixes #11706. @rickynils @jgillich

**Comment by rickynils** [comment]
@spwhitt It seems the Travis build failed when building the `baresip` package. Is that related to your changes?

**Comment by spwhitt** [comment]
I don't believe so. It's complaining something about ccache which seems unrelated to my changes. I won't get home to test on my linux machine for ~4hrs.

**Comment by spwhitt** [comment]
`baresip` builds on my machine so it must be unrelated.

**Comment by rickynils** [comment]
Yeah, `baresip` builds for me too. I don't know what Travis is smoking. I'll merge this, the commits look fine.

**Pull request merged**
