### PR TITLE
amdvlk: 2022.Q4.4 → 2023.Q1.2

### PR DESCRIPTION
**Pull request by toastal**
Release: https://github.com/GPUOpen-Drivers/AMDVLK/releases/tag/v-2023.Q1.1

###### Description of changes

~~Fingers crossed this helps with #216294~~ This did not fix this 32-bit issue, but it's still a valid update.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by andresilva** [comment]
I tested this locally yesterday and unfortunately it didn't fix #216294 😞.

**Review by Flakebi — APPROVED** [review]
LGTM, thanks, tested vulkaninfo and vkcube (in #200532).

**Comment by toastal** [comment]
Hmm. I checked, but I guess I missed that the bot already opened the upgrade. I wanted to test it out anyhow.

**Review by andresilva — APPROVED** [review]

**Comment by toastal** [comment]
2023.Q1.2 is tagged

**Review by andresilva — APPROVED** [review]

**Comment by andresilva** [comment]
Tested `vulkaninfo` and `vkcube` on both the 64 and 32 bit package. I'm going to go ahead and merge this.

**Pull request merged**
