### PR TITLE
prefetch-npm-deps: fix hash stability

### PR DESCRIPTION
**Pull request by lilyinstarlight**
###### Description of changes

I worked with @winterqt in Matrix DMs on figuring out an issue with non-reproducible hashes from prefetch-npm-deps after #200470 

It turns out GNU `tar` silently assumes `--mtime=0` means set mtime to current date at midnight local time rather than Unix epoch timestamp 0 (which led to different hashes when run on different days as well as different hashes when run in/out of sandbox if local time isn't UTC)

This corrects the tar call to use `--mtime=@0` which makes the cached tar files reproducible and fixes hash instability. I also recalculated all of the relevant hashes that this changed (only hosted git deps used this code branch so not all hashes needed to change)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

###### nixpkgs-review

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>evcc</li>
    <li>open-stage-control</li>
    <li>prefetch-npm-deps</li>
  </ul>
</details>

### CODE REVIEW

**Review by winterqt — APPROVED** [review]

**Comment by winterqt** [comment]
I split the docs change into a separate commit, to make it clear that that was caused by the previous changes. Thoughts?

**Comment by lilyinstarlight** [comment]
> I split the docs change into a separate commit, to make it clear that that was caused by the previous changes. Thoughts?

It looks like you may have ordered that commit before the fix rather than after (which doesn't particularly matter since it's a doc change), but separating it out to another commit is fine with me

**Comment by winterqt** [comment]
I made sure that `prefetch-npm-deps` before this change and after this change produced the same hash (unless I did something wrong), which is why I ordered it like that.

**Comment by lilyinstarlight** [comment]
> I made sure that `prefetch-npm-deps` before this change and after this change produced the same hash (unless I did something wrong), which is why I ordered it like that. Does that sound sane, or should I move it?

Oh yeah it probably did if it didn't have hosted deps

I'm good with this now

**Pull request merged**
