### PR TITLE
fetchfile: remove unused file

### PR DESCRIPTION
**Pull request by groxxda**
###### Motivation for this change

This file is not used and has invalid syntax.

CC @edolstra @7c6f434c 
###### Things done
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vcunat** [comment]
What's the invalid syntax?

**Comment by vcunat** [comment]
BTW, if implementing this, it would be better to use a fixed-output derivation (instead of checking the hash manually).

**Comment by vcunat** [comment]
Anyway, I don't think it's worth keeping it, at least in the current state.

**Comment by groxxda** [comment]
@vcunat just for completeness: `if` is not valid after `//`.
Thanks for merging :+1:

**Comment by vcunat** [comment]
Ah, right, it was missing parentheses.

**Pull request merged**
