### PR TITLE
eternal-terminal: 5.1.10 -> 6.0.4

### PR DESCRIPTION
**Pull request by pingiun**
###### Motivation for this change
Eternal Terminal has had new releases, also the repository name was changed.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @dezgeg

### CODE REVIEW

**Comment by pingiun** [comment]
The `11.by: package-maintainer` is a bit weird because I just added myself as maintainer because I want to continue to work on this

**Comment by qolii** [comment]
[I meeeeeeean](https://github.com/NixOS/nixpkgs/pull/70419) ;)

I've been updating this package the last few times, but I didn't take ownership. So, by all means feel free to take it over.

What happened w.r.t the repo name? I think my own update (which didn't do anything with the name) also built just fine. Unless it changed quite recently?

**Comment by c0bw3b** [comment]
@pingiun hello and welcome around here :)
Yes our bot will flagged you as maintainer already even though listing yourself as one is part of the PR itself.
Could you please add yourself to maintainers list in a separate commit `maintainers: add pingiun` ?

**Comment by qolii** [comment]
> Are you ok with closing #70419 ?

Yep yep! No worries.

**Comment by c0bw3b** [comment]
@GrahamcOfBorg build eternal-terminal

**Comment by pingiun** [comment]
> @pingiun hello and welcome around here :)

Thanks!

> Could you please add yourself to maintainers list in a separate commit `maintainers: add pingiun` ?

Sure, done.

**Pull request merged**
