### PR TITLE
Emacs package updates

### PR DESCRIPTION
**Pull request by ttuegel**
Besides package updates, this also changes the format of the generated packages. Instead of generating JSON, the Nix expressions are generated directly. Despite this radical change, there is not a significant change in evaluation overhead.

### CODE REVIEW

**Comment by domenkozar** [comment]
If those are generated, could they be in one file? It impacts Nix IO if we have so many files.

**Comment by ttuegel** [comment]
I can put them in one file, yes, but then I lose the ability to generate one package at a time. We would have to rely on Melpa for all our package curation. Based on my experiments, I don't believe this impacts performance significantly, but I will put together a definitive benchmark to be certain.

**Comment by ttuegel** [comment]
I marked some broken packages from `melpaStablePackages` and fixed a bug in the detection of package archive names.

**Comment by ttuegel** [comment]
I have benchmarked the one-big-file approach vs. the many-little-files approach. There is not a significant difference in evaluation time between approaches. Therefore, I think the drawbacks of the single-file approach outweigh the tiny performance gain.

## Test protocol
```
# instantiate once, untimed, so that all derivations are already in /nix/store
nix-instantiate ./. -A emacsPackagesNg.melpaPackages >/dev/null

# drop all caches for cold test
sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches'

# cold test once
command time nix-instantiate ./. -A emacsPackagesNg.melpaPackages >/dev/null

# warm test three times and take the worst time
command time nix-instantiate ./. -A emacsPackagesNg.melpaPackages >/dev/null
command time nix-instantiate ./. -A emacsPackagesNg.melpaPackages >/dev/null
command time nix-instantiate ./. -A emacsPackagesNg.melpaPackages >/dev/null
```

## Results

### One File
- cold: 131.03 s
- warm: 3.53 s

### Many Files
- cold: 131.99 s (+0.7%)
- warm: 3.63 s (+2.8%)

**Comment by oxij** [comment]
The "not one file" is my concern as well.

> I can put them in one file, yes, but then I lose the ability to
> generate one package at a time. We would have to rely on Melpa for all
> our package curation.

I think this is okay, especially considering the ease with which one
could just copy the package expression to `emacs-packages.nix` in case
one is not okay with MELPA's decision on a particular package.

> Based on my experiments, I don't believe this
> impacts performance significantly, but I will put together a
> definitive benchmark to be certain.

Which only means you're running from an SSD or a high speed RAID. I'm
pretty sure that parsing fairly huge files into ASTs (with an efficient
memory allocator) and not evaluating those is much cheaper than walking
kernel and disk structures (especially when seeking is not cheap).

**Comment by domenkozar** [comment]
@ttuegel @oxij well Nix is pretty much not usable on non-SSD. Not that we have to make that worse.

@ttuegel will this fix any of the failing packages at http://hydra.nixos.org/eval/1236698#tabs-still-fail, I'd really prefer we don't ship broken software.

**Comment by ttuegel** [comment]
> I think this is okay, especially considering the ease with which one could just copy the package expression to `emacs-packages.nix` in case one is not okay with MELPA's decision on a particular package.

It's not OK with me, because I have to keep regenerating the package set until I get one run where all the packages are available. If a single server times-out, I have to restart the whole run, which takes about an hour. This wasn't a problem when I was generating JSON because I could parse the JSON and keep old packages, but I need to generate Nix expressions directly because it's faster and Nix's JSON parser is wonky.

> Which only means you're running from an SSD or a high speed RAID.

I'm running all these tests on my single-disk, 7200 rpm spinning-drive machine. On my laptop (SSD) everything is so fast it's meaningless.

> I'm pretty sure that parsing fairly huge files into ASTs (with an efficient memory allocator) and not evaluating those is much cheaper than walking kernel and disk structures (especially when seeking is not cheap).

I posted the data above that invalidates this assumption. I think you are underestimating the decades of work that has gone into optimizing filesystems compared to the small amount of work that has gone into optimizing Nix. Obviously there is a cost, but the cost *is* less that you are saying.

> will this fix any of the failing packages at http://hydra.nixos.org/eval/1236698#tabs-still-fail, I'd really prefer we don't ship broken software.

All the packages in `melpaStablePackages` and `elpaPackages` should be fixed or marked broken. There may still be broken packages in `melpaPackages`; there are many more of those and I haven't gone through them all yet. Are you saying that I need to fix those before I merge this?

**Comment by domenkozar** [comment]
@ttuegel no, you're welcome to improve current state of packaging. I just want to make sure you know packages from `emacs24PackagesNg` set are failing.

**Comment by oxij** [comment]
> It's not OK with me, because I have to keep regenerating the package set until I get one run where all the packages are available. If a single server times-out, I have to restart the whole run, which takes about an hour. This wasn't a problem when I was generating JSON because I could parse the JSON and keep old packages, but I need to generate Nix expressions directly because it's faster and Nix's JSON parser is wonky.

This can easily be solved by serializing the intermediate structures in
emacs2nix (I highly recommend `safecopy` and/or `acid-state` packages
here since they can implement all of that with a couple of lines of code
(Template Haskell FTW!) ++ a hopefully trivial merge function).

>> Which only means you're running from an SSD or a high speed RAID.
>
> I'm running all these tests on my single-disk, 7200 rpm spinning-drive machine. On my laptop (SSD) everything is so fast it's meaningless.
>
>> I'm pretty sure that parsing fairly huge files into ASTs (with an efficient memory allocator) and not evaluating those is much cheaper than walking kernel and disk structures (especially when seeking is not cheap).
>
> I posted the data above that invalidates this assumption. I think you are underestimating the decades of work that has gone into optimizing filesystems compared to the small amount of work that has gone into optimizing Nix. Obviously there is a cost, but the cost *is* less that you are saying.

I can be wrong of course, but I suspect that your test measures
something different from what you think it does. May I get the
"one-big-file" branch somewhere so that I could profile both with
`perf`?

**Comment by ttuegel** [comment]
> This can easily be solved by serializing the intermediate structures in emacs2nix (I highly recommend `safecopy` and/or `acid-state` packages here since they can implement all of that with a couple of lines of code (Template Haskell FTW!) ++ a hopefully trivial merge function).

As soon as I cache the intermediate data, the person with the cache (me) is the only person who can safely generate the package set. That's not an immediate problem, but it will become one the first time someone wants a package updated Right Now for an important fix, and I'm not around.

> I can be wrong of course, but I suspect that your test measures something different from what you think it does. May I get the "one-big-file" branch somewhere so that I could profile both with `perf`?

Sure! It is [here](https://github.com/ttuegel/nixpkgs/tree/emacs-packages-one-file). I only put the `melpaPackages` expressions into a single file so far, but that is by far the largest set, so it should be a good benchmark.

**Comment by ttuegel** [comment]
> This can easily be solved by serializing the intermediate structures in emacs2nix (I highly recommend `safecopy` and/or `acid-state` packages here since they can implement all of that with a couple of lines of code (Template Haskell FTW!) ++ a hopefully trivial merge function).

I can also take another look at `hnix`. When I started `emacs2nix` I wasn't impressed with its pretty-printer, though.

**Comment by oxij** [comment]
With your test comparing many-files and one-file branches I get

* 25% wall time difference cold and 4% wall time difference warm on SSD
 (on laptop; cold evaluation on many-files takes 4.35 seconds here, 131s from your test seems crazy)
* 33% wall time difference cold and 3% wall time difference warm on HDD
 (on a much more powerful machine)

Which makes much more sense than your results since your warm times
differ more that your cold times, which is strange.

Are you sure you compute your percents from wall time, not user time?

Then, I applied this patch

~~~~
diff --git a/pkgs/top-level/emacs-packages.nix b/pkgs/top-level/emacs-packages.nix
index 0e267b5..d671db2 100644
--- a/pkgs/top-level/emacs-packages.nix
+++ b/pkgs/top-level/emacs-packages.nix
@@ -69,6 +69,9 @@ let
 
   emacsWithPackages = emacsWithPackages self;
 
+  melpaPackagesTest = lib.mapAttrs (n: v: toString v) self.melpaPackages;
+  #melpaPackagesTest = lib.mapAttrs (n: v: toString v) (lib.filterAttrs (n: v: lib.hasPrefix "org" n) self.melpaPackages);
+
   ## START HERE
 
   ac-haskell-process = melpaBuild rec {
~~~~

(see pull/12410-emacs2nix-many and pull/12410-emacs2nix-one branches in https://github.com/oxij/nixpkgs)

and started measuring

~~~~
   command time nix-instantiate . --eval --strict -A emacsPackagesNg.melpaPackagesTest >/dev/null
~~~~

which made the differences some several percent bigger.

Which made me notice that

* many-files test spends 100% more time in system time in cold
  tests than in warm tests.
* one-file test spends only 20% more there.

That's 5 times difference.

So I did this:

~~~~
#!/bin/sh

# instantiate once, untimed, so that all derivations are already in /nix/store
nix-instantiate ./. -A emacsPackagesNg.melpaPackages >/dev/null

echo starting

echo strace open
command strace -e open nix-instantiate . --eval --strict -A emacsPackagesNg.melpaPackagesTest >/dev/null 2>/tmp/nix-straced
cat /tmp/nix-straced
wc -l /tmp/nix-straced

testme() {
    command time nix-instantiate . --eval --strict -A emacsPackagesNg.melpaPackagesTest >/dev/null
}

cold() {
    # drop all caches for cold test
    sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches'
    testme
}

echo cold
cold
cold
cold

echo warm
testme
testme
testme
~~~~

and it shows that

* a ton of */melpa/*/*.nix files get evaluated even in "one-file" test
* the number of "open" system calls differs ~5 times between the two branches which is pretty much exactly the difference in the system time.

Seeing this I would prefer the whole nixpkgs to be in one big file.

`perf` report for the warm case:

~~~~
17.32%  nix-instantiate  libcrypto.so.1.0.0   [.] sha256_block_data_order
10.53%  nix-instantiate  libnixstore.so       [.] nix::printString
 5.38%  nix-instantiate  libc-2.21.so         [.] _int_malloc
 3.60%  nix-instantiate  libnixexpr.so        [.] yylex
 3.49%  nix-instantiate  libc-2.21.so         [.] __memcmp_sse4_1
 2.23%  nix-instantiate  libc-2.21.so         [.] _int_free
 2.01%  nix-instantiate  libc-2.21.so         [.] malloc
 1.64%  nix-instantiate  libc-2.21.so         [.] malloc_consolidate
 1.38%  nix-instantiate  libstdc++.so.6.0.20  [.] std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string
 1.25%  nix-instantiate  libnixexpr.so        [.] nix::ExprVar::eval
 1.17%  nix-instantiate  libc-2.21.so         [.] strlen
 1.12%  nix-instantiate  libnixexpr.so        [.] yyuserAction
 1.11%  nix-instantiate  libc-2.21.so         [.] __memcpy_sse2_unaligned
 0.98%  nix-instantiate  libnixexpr.so        [.] nix::ExprSelect::eval
 0.95%  nix-instantiate  libnixexpr.so        [.] std::unordered_set<std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::string> >::insert
 0.94%  nix-instantiate  libgc.so.1.0.3       [.] GC_malloc
 0.93%  nix-instantiate  libnixexpr.so        [.] nix::ExprOpUpdate::eval
 0.92%  nix-instantiate  libgc.so.1.0.3       [.] GC_allochblk_nth
 0.88%  nix-instantiate  libnixexpr.so        [.] nix::prim_removeAttrs
 0.83%  nix-instantiate  libnixexpr.so        [.] yyparse
 0.83%  nix-instantiate  libnixexpr.so        [.] nix::EvalState::callFunction
 0.82%  nix-instantiate  libstdc++.so.6.0.20  [.] std::string::reserve
 0.77%  nix-instantiate  libnixexpr.so        [.] yyglrReduce
 0.76%  nix-instantiate  libnixexpr.so        [.] nix::ExprAttrs::eval
 0.70%  nix-instantiate  libnixstore.so       [.] nix::hashDerivationModulo
 0.69%  nix-instantiate  libnixexpr.so        [.] std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > >::operator[]
 0.68%  nix-instantiate  libnixexpr.so        [.] std::string::_Rep::_M_dispose
 0.68%  nix-instantiate  libnixexpr.so        [.] nix::Bindings::find
 0.67%  nix-instantiate  libnixexpr.so        [.] nix::prim_derivationStrict
 0.67%  nix-instantiate  libnixexpr.so        [.] nix::EvalState::coerceToString
 0.67%  nix-instantiate  libstdc++.so.6.0.20  [.] std::_Rb_tree_insert_and_rebalance
 0.65%  nix-instantiate  libstdc++.so.6.0.20  [.] std::_Rb_tree_increment
 0.65%  nix-instantiate  [kernel.kallsyms]    [k] clear_page
 0.64%  nix-instantiate  nix-instantiate      [.] std::_Rb_tree<std::string, std::pair<std::string const, std::string>, std::_Select1st<std::pair<std::string const, std::string> >, std::less<std::string>, std::allocator<std::pair<std::s
 0.63%  nix-instantiate  libgc.so.1.0.3       [.] GC_build_fl
 0.61%  nix-instantiate  libnixutil.so        [.] nix::canonPath
 0.61%  nix-instantiate  [kernel.kallsyms]    [k] page_fault
 0.61%  nix-instantiate  libnixutil.so        [.] nix::parseHash32
 0.56%  nix-instantiate  nix-instantiate      [.] std::_Rb_tree<std::string, std::string, std::_Identity<std::string>, std::less<std::string>, std::allocator<std::string> >::_M_erase
 0.56%  nix-instantiate  libnixstore.so       [.] nix::unparseDerivation
 0.52%  nix-instantiate  libnixexpr.so        [.] nix::ExprVar::maybeThunk
~~~~

with the cold case is almost exactly the same surprises me only with the
`nix::printString` line. @edolstra and @shlevy might want to see this.
Other that that, it's seems pretty okay.

**Comment by ttuegel** [comment]
> Which makes much more sense than your results since your warm times differ more that your cold times, which is strange. Are you sure you compute your percents from wall time, not user time?

Yes, all the times I quoted are wall times.

> Seeing this I would prefer the whole nixpkgs to be in one big file.

I will make the necessary changes to this PR. Thanks for checking!

**Comment by ttuegel** [comment]
I just added several bug fixes and marked all the broken packages.

**Comment by shlevy** [comment]
FYI, the printString function in question: https://github.com/NixOS/nix/blob/master/src/libstore/derivations.cc#L126-L136

**Comment by shlevy** [comment]
@edolstra Perhaps it would be better to switch to a length-prefixed string instead of doing escaping?

**Comment by shlevy** [comment]
(really, we should just remove derivation serialization from the hot path...)

**Comment by ttuegel** [comment]
I have regenerated the packages as one file per set and rebased my changes to get rid of the many-file commits. Now I'm just waiting on Travis to check for evaluation errors.

**Comment by ttuegel** [comment]
Merged; thanks for the feedback, everyone!

**Comment by mdorman** [comment]
@ttuegel This merge apparently lost some packages.  The one I noticed was cperl-mode.  I'm assuming this wasn't intentional?

7c42f9a was the suspect change.

**Comment by ttuegel** [comment]
Yeah, that was not intentional. The way Melpa is structured, it's very hard to tell what packages are supposed to have stable versions, so when I generate the stable set, it's hard to tell which packages are missing and which are just unstable. I will generate that package ASAP. (When this hits Hydra, I will have a complete list of the missing packages.)

**Comment by ttuegel** [comment]
@mdorman Actually, `cperl-mode` was removed from Melpa in milkypostman/melpa@0e5185e632ef16d12e5e4284be5af83d0f700805.

**Comment by mdorman** [comment]
Well, that's a level of curation I hadn't previously witnessed on melpa.  :) I apologize for the time I've no doubt you wasted.

**Pull request merged**
