### PR TITLE
nixos/syncthing: move declarative options to the top level

### PR DESCRIPTION
**Pull request by ncfavier**
###### Motivation for this change

I don't think the `declarative` path component conveys any useful information, so let's remove it.

Diff best viewed with "Hide whitespace changes" on.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [X] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ncfavier** [comment]
@ofborg test syncthing syncthing-init

**Comment by Lassulus** [comment]
the idea was to have the declarative stuff be optional and that there is an alternative imperative usage. maybe we can make that clear in the descriptions?

**Comment by ncfavier** [comment]
OK, got a bit carried away and rewrote a lot of the descriptions.

Hopefully this is clearer.

**Comment by ncfavier** [comment]
Thanks again!

**Pull request merged**
