### PR TITLE
python3Packages.wandb: relax protobuf version

### LINKED ISSUE #193612: `python310Packages.wandb` build failure on x86_64-linux as of `671fabc9`
## Issue description
Build of `python310Packages.wandb` failed on x86_64-linux as of 671fabc93b4d1a3b38499c7b20776477c91b2b15. This is currently breaking `python3Packages.wandb`.

```
error: builder for '/nix/store/nsz2b2a4q41izr4yk5dfj8hzv7kpl024-python3.10-wandb-0.12.21.drv' failed with exit code 1;
       last 10 log lines:
       > Requirement already satisfied: pathtools in /nix/store/wzfjczmj7a7y5x5nn5qp4v18ia510156-python3.10-pathtools-0.1.2/lib/python3.10/site-packages (from wandb==0.12.21) (0.1.2)
       > Requirement already satisfied: Click!=8.0.0,>=7.0 in /nix/store/pl53qimr6imm2lxa69liajrwv2xpjxsd-python3.10-click-8.1.3/lib/python3.10/site-packages (from wandb==0.12.21) (8.1.3)
       > Requirement already satisfied: setuptools in /nix/store/3jb3dgp57429y07my17hnhbd5q9f1rm8-python3.10-setuptools-65.3.0/lib/python3.10/site-packages (from wandb==0.12.21) (65.3.0.post0)
       > Requirement already satisfied: psutil>=5.0.0 in /nix/store/bk9hj2b57nkb1kbbz4jddfrrf2dpfhby-python3.10-psutil-5.9.2/lib/python3.10/site-packages (from wandb==0.12.21) (5.9.2)
       > Requirement already satisfied: PyYAML in /nix/store/z0d74c4jyjqq2s41yxxq4jww4pa130d7-python3.10-pyyaml-6.0/lib/python3.10/site-packages (from wandb==0.12.21) (6.0)
       > Requirement already satisfied: setproctitle in /nix/store/ww5blazzb55wgji9hqldr2y0dhqmv6j0-python3.10-setproctitle-1.3.2/lib/python3.10/site-packages (from wandb==0.12.21) (1.3.2)
       > Requirement already satisfied: sentry-sdk>=1.0.0 in /nix/store/crswsrax5q2mxfbpi5c40ip8hgsfv2vj-python3.10-sentry-sdk-1.9.9/lib/python3.10/site-packages (from wandb==0.12.21) (1.9.9)
       > ERROR: Could not find a version that satisfies the requirement protobuf<4.0dev,>=3.12.0 (from wandb) (from versions: none)
       > ERROR: No matching distribution found for protobuf<4.0dev,>=3.12.0
       > 
       For full logs, run 'nix log /nix/store/nsz2b2a4q41izr4yk5dfj8hzv7kpl024-python3.10-wandb-0.12.21.drv'.
```

[full build log](https://github.com/samuela/nixpkgs-upkeep/actions/runs/3155463991)

python3Packages.wandb maintainers cc: @samuela
python310Packages.wandb maintainers cc: @samuela
Other cc: n/a

### Steps to reproduce
1. Checkout nixpkgs at commit 671fabc93b4d1a3b38499c7b20776477c91b2b15
2. Run `nix-build -A python310Packages.wandb`

## Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-1020-azure, Ubuntu, 20.04.5 LTS (Focal Fossa), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - nixpkgs: `/nix/store/sx8xlilbqymsa9341yxpivf57hi0az6r-source`
```

## Misc.
This issue was automatically generated by [nixpkgs-upkeep](https://github.com/samuela/nixpkgs-upkeep).
- [CI workflow](https://github.com/samuela/nixpkgs-upkeep/actions/runs/3155463991) that created this issue.
- Internal tags: -3881163355657976664 7833354437006588915

### PR DESCRIPTION
**Pull request by erdnaxe**
###### Description of changes

Fix failing build.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
@ofborg build python310Packages.wandb

**Comment by SuperSandro2000** [comment]
```
=================================== FAILURES ===================================
_______________________ test_controller_info_actualized ________________________
    def test_controller_info_actualized():
        # Check that the num_threads attribute reflects the actual state of the threadpools
        controller = ThreadpoolController()
        original_info = controller.info()
    
        with threadpool_limits(limits=1):
            assert all(
                lib_controller.num_threads == 1
                for lib_controller in controller.lib_controllers
            )
    
>       assert controller.info() == original_info
E       AssertionError: assert [{'filepath':...ds': 64, ...}] == [{'filepath':...ds': 64, ...}]
E         At index 0 diff: {'user_api': 'openmp', 'internal_api': 'openmp', 'prefix': 'libgomp', 'filepath': '/nix/store/kdkv4hvfjl1y7ns4brfp9yk6xv5sqr86-gfortran-9.5.0-lib/lib/libgomp.so.1.0.0', 'version': None, 'num_threads': 64} != {'user_api': 'openmp', 'internal_api': 'openmp', 'prefix': 'libgomp', 'filepath': '/nix/store/kdkv4hvfjl1y7ns4brfp9yk6xv5sqr86-gfortran-9.5.0-lib/lib/libgomp.so.1.0.0', 'version': None, 'num_threads': 80}
E         Use -v to get more diff
tests/test_threadpoolctl.py:75: AssertionError
________________________ test_command_line_command_flag ________________________
    def test_command_line_command_flag():
        pytest.importorskip("numpy")
        output = subprocess.check_output(
            [sys.executable, "-m", "threadpoolctl", "-c", "import numpy"]
        )
        cli_info = json.loads(output.decode("utf-8"))
    
        this_process_info = threadpool_info()
        for lib_info in cli_info:
>           assert lib_info in this_process_info
E           AssertionError: assert {'filepath': '/nix/store/kdkv4hvfjl1y7ns4brfp9yk6xv5sqr86-gfortran-9.5.0-lib/lib/libgomp.so.1.0.0', 'internal_api': 'openmp', 'num_threads': 80, 'prefix': 'libgomp', ...} in [{'filepath': '/nix/store/kdkv4hvfjl1y7ns4brfp9yk6xv5sqr86-gfortran-9.5.0-lib/lib/libgomp.so.1.0.0', 'internal_api': '...jy2klbnxp7qaqrh368l5-openblas-0.3.20/lib/libopenblasp-r0.3.20.so', 'internal_api': 'openblas', 'num_threads': 64, ...}]
tests/test_threadpoolctl.py:547: AssertionError
________________________ test_command_line_import_flag _________________________
    @pytest.mark.skipif(
        sys.version_info < (3, 7), reason="need recent subprocess.run options"
    )
    def test_command_line_import_flag():
        result = subprocess.run(
            [
                sys.executable,
                "-m",
                "threadpoolctl",
                "-i",
                "numpy",
                "scipy.linalg",
                "invalid_package",
                "numpy.invalid_sumodule",
            ],
            capture_output=True,
            check=True,
            encoding="utf-8",
        )
        cli_info = json.loads(result.stdout)
    
        this_process_info = threadpool_info()
        for lib_info in cli_info:
>           assert lib_info in this_process_info
E           AssertionError: assert {'filepath': '/nix/store/kdkv4hvfjl1y7ns4brfp9yk6xv5sqr86-gfortran-9.5.0-lib/lib/libgomp.so.1.0.0', 'internal_api': 'openmp', 'num_threads': 80, 'prefix': 'libgomp', ...} in [{'filepath': '/nix/store/kdkv4hvfjl1y7ns4brfp9yk6xv5sqr86-gfortran-9.5.0-lib/lib/libgomp.so.1.0.0', 'internal_api': '...jy2klbnxp7qaqrh368l5-openblas-0.3.20/lib/libopenblasp-r0.3.20.so', 'internal_api': 'openblas', 'num_threads': 64, ...}]
```

**Comment by samuela** [comment]
Result of `nixpkgs-review pr 194351` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages failed to build:</summary>
  <ul>
    <li>openai (python310Packages.openai)</li>
    <li>python310Packages.dalle-mini</li>
    <li>python310Packages.spacy</li>
    <li>python310Packages.spacy-transformers</li>
    <li>python310Packages.textacy</li>
    <li>python39Packages.dalle-mini</li>
    <li>python39Packages.openai</li>
    <li>python39Packages.spacy</li>
    <li>python39Packages.spacy-transformers</li>
    <li>python39Packages.textacy</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python310Packages.spacy-loggers</li>
    <li>python310Packages.wandb</li>
    <li>python39Packages.spacy-loggers</li>
    <li>python39Packages.wandb</li>
  </ul>
</details>

**Comment by samuela** [comment]
Huh I'm not able to reproduce the ofborg build failure... anyone have any ideas why that may differ?

**Comment by samuela** [comment]
If the package was previously failing to build in all configurations and is now only failing to build in some configurations, then I'm in favor of merging. Still, it would be nice to get to the bottom of this discrepancy between local builds and ofborg...

**Comment by samuela** [comment]
Also, what is the current protobuf version and what are the wandb protobuf version constraints? Are there any backwards compatibility issues such that we should  be specifying a different protobuf version instead of relaxing the constraints?

**Comment by erdnaxe** [comment]
https://github.com/wandb/wandb/pull/3709 is the explaination of `protobuf>=3.12.0,<4.0dev` constraint.

`python3Packages.protobuf` is 3.21.6 on NixPkgs master, so it should work without the version relax, but for some reason without this patch it does not build:
```
[...]
Requirement already satisfied: setproctitle in /nix/store/ww5blazzb55wgji9hqldr2y0dhqmv6j0-python3.10-setproctitle-1.3.2/lib/python3.10/site-packages (from wandb==0.12.21) (1.3.2)
Requirement already satisfied: sentry-sdk>=1.0.0 in /nix/store/crswsrax5q2mxfbpi5c40ip8hgsfv2vj-python3.10-sentry-sdk-1.9.9/lib/python3.10/site-packages (from wandb==0.12.21) (1.9.9)
ERROR: Could not find a version that satisfies the requirement protobuf<4.0dev,>=3.12.0 (from wandb) (from versions: none)
ERROR: No matching distribution found for protobuf<4.0dev,>=3.12.0
```

This is definitely strange. If it is neccessary I can add a comment before the version relax to explain this.

**Comment by FRidh** [comment]
See https://github.com/NixOS/nixpkgs/pull/194111. From protobuf 3.21 on the Python major version is no longer connected. The Python version for the package is now 4.21. The `version` in the Python package thus does not match with the actual version of the Python code.

**Comment by FRidh** [comment]
Could any of you also test https://github.com/NixOS/nixpkgs/pull/194111?

**Pull request merged**
