### PR TITLE
pan: update 0.139 -> 0.144, fix crash on startup, dep and feature wrangling.

### PR DESCRIPTION
**Pull request by dtzWill**
- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
One sec, investigating some dep fixups.

**Comment by dtzWill** [comment]
Look okay @edolstra ? (maintainer)

**Comment by edolstra** [comment]
Yes, looks good to me. BTW I haven't used Pan in years, so if somebody wants to take over as maintainer, feel free to do so.

**Comment by dtzWill** [comment]
Thanks! Just wanted to double-check in case this would break your favorite app! ;) :D.

**Pull request merged**
