### PR TITLE
prometheus: 2.17.2 -> 2.18.1

### PR DESCRIPTION
**Pull request by Frostman**
###### Motivation for this change

https://github.com/prometheus/prometheus/releases/tag/v2.18.0
https://github.com/prometheus/prometheus/releases/tag/v2.18.1

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---
This change is [Reviewable](https://reviewable.io/reviews/nixos/nixpkgs/87210)

### CODE REVIEW

**Comment by Frostman** [comment]
@GrahamcOfBorg test prometheus

**Review by marsam — CHANGES_REQUESTED** [review]
minio-client was recently updated and changed its options. could you please update the prometheus test?

```diff
--- a/nixos/tests/prometheus.nix
+++ b/nixos/tests/prometheus.nix
@@ -179,7 +179,7 @@ in import ./make-test-python.nix {
     s3.succeed(
         "mc config host add minio "
         + "http://localhost:${toString minioPort} "
-        + "${s3.accessKey} ${s3.secretKey} S3v4",
+        + "${s3.accessKey} ${s3.secretKey} --api s3v4",
         "mc mb minio/thanos-bucket",
     )
```

**Comment by Frostman** [comment]
@marsam thx! I've re-run `nixosTests.prometheus` and passing okay now. Additionally, I've updated the patch to 2.18.1 that was released today.

**Comment by Frostman** [comment]
@GrahamcOfBorg test prometheus

**Review by marsam — APPROVED** [review]

**Pull request merged**
