### PR TITLE
nixos/boot: test on aarch64

### PR DESCRIPTION
**Pull request by misuzu**
###### Motivation for this change
Add aarch64 support for `nixosTests.boot.uefiCdrom` `nixosTests.boot.uefiUsb` and `nixosTests.boot.uefiNetboot`.

Related: https://github.com/NixOS/nixpkgs/issues/106304

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [X] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by misuzu** [comment]
@GrahamcOfBorg test boot.biosCdrom boot.biosUsb boot.biosNetboot boot.uefiCdrom boot.uefiUsb boot.uefiNetboot

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 124415` at a65ee14c run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>ipxe</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/tools/misc/ipxe/default.nix:74:3:
```
   |
74 |   installPhase = ''
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl2` is a deprecated license, please check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/tools/misc/ipxe/default.nix:91:7:
```
   |
91 |       license = licenses.gpl2;
   |       ^
```
</li>
  </ul>
</details>

**Comment by misuzu** [comment]
@GrahamcOfBorg test boot.biosCdrom boot.biosUsb boot.biosNetboot boot.uefiCdrom boot.uefiUsb boot.uefiNetboot

**Comment by misuzu** [comment]
Thanks, @symphorien!

**Pull request merged**
