### PR TITLE
elisa: backporting Qt < 5.14 fix

### PR DESCRIPTION
**Pull request by SCOTT-HAMILTON**
###### Motivation for this change
https://hydra.nixos.org/build/130350392#tabs-summary

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ttuegel** [comment]
Why not build with Qt 5.15?

**Comment by SCOTT-HAMILTON** [comment]
My Pull Request doesn't aim at fixing elisa build against Qt5.15 (which it doesn't need anyway as [the last build on staging-20.09](https://hydra.nixos.org/build/130348960) tells). 
I just propose this pull request to fix [elisa builds](https://hydra.nixos.org/build/130350392) against Qt < 5.14 (in nixpkgs case, builds against Qt5.14)

**Comment by SuperSandro2000** [comment]
The hydra build you linked passed. Maybe the bug was somewhere else and fixed in the meanwhile?

**Comment by SCOTT-HAMILTON** [comment]
Could you link to the successful build? I can't find it.

**Comment by doronbehar** [comment]
I too don't understand exactly why apply that patch. Currently `elisa` fails to launch for me with:

```
QQmlApplicationEngine failed to load component
qrc:/qml/ElisaMainWindow.qml:175:13: Type HeaderBar unavailable
qrc:/qml/HeaderBar.qml:11:1: module "QtGraphicalEffects" is not installed
```

And applying this patch makes it work:

```
diff --git i/pkgs/applications/kde/elisa.nix w/pkgs/applications/kde/elisa.nix
index 9a51aa786fa..ee45202fe54 100644
--- i/pkgs/applications/kde/elisa.nix
+++ w/pkgs/applications/kde/elisa.nix
@@ -7,6 +7,7 @@
 , qtmultimedia
 , qtquickcontrols2
 , qtwebsockets
+, qtgraphicaleffects
 , kconfig
 , kcmutils
 , kcrash
@@ -36,6 +37,7 @@ mkDerivation rec {
     kirigami2
     qtmultimedia
     qtquickcontrols2
+    qtgraphicaleffects
     qtwebsockets
   ];
 
```

Though I don't understand why use `propagatedBuildInputs` and not normal `buildInputs`..

**Comment by peterhoeg** [comment]
Elisa works fine here (on unstable). Can somebody please explain exactly what isn't working?

**Comment by SCOTT-HAMILTON** [comment]
This is just to fix elisa build on Qt < 5.15. Qt 5.15 is the default verision for libsForQt5 on unstable, so it won't change anything for you. But people running older channels might be interested in using libsForQt5{12,14}.elisa which is the default when installing elisa on older channels.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review. If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 103802` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages marked as broken and skipped:
</summary>
<ul>
<li>libsForQt512.elisa</li>
<li>libsForQt514.elisa</li>
</ul>
</details>
<details>
<summary>
1 package built:
</summary>
<ul>
<li>libsForQt5.elisa (kdeApplications.elisa ,libsForQt515.elisa)</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

libsForQt5.elisa.log:
<details>

[1;33mwarning: unclear-gpl[0m
`gpl3` is a deprecated license, check if project uses `gpl3Plus` or `gpl3Only` and change `meta.license` accordingly.

Near pkgs/applications/kde/elisa.nix:53:5:

```
   |
53 |     license = licenses.gpl3;
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>

**Comment by doronbehar** [comment]
> This is just to fix elisa build on Qt < 5.15. Qt 5.15 is the default verision for libsForQt5 on unstable, so it won't change anything for you. But people running older channels might be interested in using libsForQt5{12,14}.elisa which is the default when installing elisa on older channels.

Then @SCOTT-HAMILTON please make the PR target the older branch that you'd like elisa to build with there.

**Comment by Thra11** [comment]
> ```
> QQmlApplicationEngine failed to load component
> qrc:/qml/ElisaMainWindow.qml:175:13: Type HeaderBar unavailable
> qrc:/qml/HeaderBar.qml:11:1: module "QtGraphicalEffects" is not installed
> ```
> 
> And applying this patch makes it work:
> 
> ```
> diff --git i/pkgs/applications/kde/elisa.nix w/pkgs/applications/kde/elisa.nix
> index 9a51aa786fa..ee45202fe54 100644
> --- i/pkgs/applications/kde/elisa.nix
> +++ w/pkgs/applications/kde/elisa.nix
> @@ -7,6 +7,7 @@
>  , qtmultimedia
>  , qtquickcontrols2
>  , qtwebsockets
> +, qtgraphicaleffects
>  , kconfig
>  , kcmutils
>  , kcrash
> @@ -36,6 +37,7 @@ mkDerivation rec {
>      kirigami2
>      qtmultimedia
>      qtquickcontrols2
> +    qtgraphicaleffects
>      qtwebsockets
>    ];
>  
> ```

Problems with missing QtGraphicalEffects in application using Kirigami may have been fixed by #108331.

**Comment by doronbehar** [comment]
I'm closing due to this being irrelevant now.

**Pull request closed without merging**
