### PR TITLE
deepin.dde-dock: init at 4.9.8

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

Add [dde-dock](https://github.com/linuxdeepin/dde-dock), a dock for Deepin Desktop Environment.

About packaging deepin for NixOS: https://github.com/NixOS/nixpkgs/issues/59023

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by romildo** [comment]
This is a dependency for `dde-file-manager`.

**Comment by worldofpeace** [comment]
So at a glance there is a plugins system that wants to load them from a directory
```
/usr/lib/dde-dock/plugins/
```

I think two most popular things to do in nixpkgs for this kind of thing are
1. have it load from directory `/run/current-system/sw/lib/dde-dock/plugins`
2. load a directory from the value of an environment variable
    I've used this one in practice

And possibly some others that I haven't thought of.

**Comment by romildo** [comment]
@GrahamcOfBorg build deepin.dde-dock

**Comment by Infinisil** [comment]
See also https://github.com/NixOS/nixpkgs/pull/59560#issuecomment-483351578

**Comment by romildo** [comment]
I have removed the NixOS module from this PR. The dbus service may be added again in a new PR that will try to better handle the deepin module(s).

**Comment by romildo** [comment]
> So at a glance there is a plugins system that wants to load them from a directory
> 
> ```
> /usr/lib/dde-dock/plugins/
> ```
> I think two most popular things to do in nixpkgs for this kind of thing are
> 
> 1. have it load from directory `/run/current-system/sw/lib/dde-dock/plugins`
> 2. load a directory from the value of an environment variable
>    I've used this one in practice
> 
> And possibly some others that I haven't thought of.

@worldofpeace I have patched the source to use the `DDE_DOCK_PLUGINS_DIR` environment variable to find plugins. The variable should then be set in the forthcoming desktop module.

**Comment by romildo** [comment]
The following packages also have similar plugins systems:
- `dde-polkit-agent` (in C++ and Qt): I have a similar fix in a forthcoming PR
- `deepin-wm` (in Vala): I do not know Vala to write a similar fix
- `deepin-mutter` (in C and glib): A similar fix can be written

**Comment by worldofpeace** [comment]
Added a wrapper, we probably should package a plugin to test it.

There's a hardcoded path at `share/polkit-1/actions/com.deepin.dde.dock.overlay.policy`
```
<annotate key="org.freedesktop.policykit.exec.path">/usr/sbin/overlayroot-disable</annotate>
<annotate key="org.freedesktop.policykit.exec.path">/sbin/overlayroot-disable</annotate>
```

Don't know what that's about.

**Comment by romildo** [comment]
> Added a wrapper,

I was originally thinking in defining the following in the deepin desktop manager module:

```
  environment.variables.DDE_DOCK_PLUGINS_DIR = [ "${config.system.path}/lib/dde-dock/plugins" ];
  environment.pathsToLink = [ "/lib/dde-dock/plugins" ];
```
instead of wrapping. It is a simpler technique already in use in nixos.

> we probably should package a plugin to test it.

`dde-file-manager` includes `lib/dde-dock/plugins/system-trays/libdde-disk-mount-plugin.so`

> There's a hardcoded path at `share/polkit-1/actions/com.deepin.dde.dock.overlay.policy`
> 
> ```
> <annotate key="org.freedesktop.policykit.exec.path">/usr/sbin/[overlayroot-disable](url)</annotate>
> <annotate key="org.freedesktop.policykit.exec.path">/sbin/overlayroot-disable</annotate>
> ```
> Don't know what that's about.

[Protecting the Root Filesystem on Ubuntu with Overlayroot](https://spin.atomicobject.com/2015/03/10/protecting-ubuntu-root-filesystem/) is about overlayroot. I do not know about it.

**Comment by worldofpeace** [comment]
> I was originally thinking in defining the following in the deepin desktop manager module:
> instead of wrapping. It is a simpler technique already in use in nixos.

I think, in general, relying on the global environment like that is best to be avoided.

**Pull request merged**
