### PR TITLE
coqPackages.MenhirLib: init at 20240715

### PR DESCRIPTION
**Pull request by damhiya**
## Description of changes

I added `coqPackages.coq-menhirlib`, and added it as a dependency of `coqPackages.compcert`. This change can be useful if someone wants to use compcert and coq-menhirlib at the same time.

I'm going to assign myself as a maintainer of `coq-menhirlib`, but I'm not currently listed in the maintainer list. I already posed another PR(https://github.com/NixOS/nixpkgs/pull/334904) that adding my profile to the maintainer list. I'll rebase this PR when https://github.com/NixOS/nixpkgs/pull/334904 merged to the master branch.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by vbgl** [comment]
This breaks compcert 3.8 and does not work with Coq 8.20. This might be easily fixed by adding other versions of `MenhirLib` for different versions of Coq.

Also, where does the `coq-menhirlib` name comes from? We usually use as attribute name the name of the library (i.e., the one we put in vernacular between `From` and `Require`).

**Comment by damhiya** [comment]
@vbgl
> This breaks compcert 3.8 and does not work with Coq 8.20. This might be easily fixed by adding other versions of `MenhirLib` for different versions of Coq.

I see. I'll add more versions.

> Also, where does the `coq-menhirlib` name comes from? We usually use as attribute name the name of the library (i.e., the one we put in vernacular between `From` and `Require`).

I didn't knew about the convention so I just used the name of the opam package, following the case of `coq-ext-lib`. I also considered `coqPackages.MenhirLib`, but I thought that might be confusing due to existence of `ocamlPackages.menhirLib`. I'll rename the library into `coqPackages.MenhirLib` if you think it is better.

**Comment by vbgl** [comment]
> I'll rename the library into `coqPackages.MenhirLib` if you think it is better.

Yes please. You are also right about `coq-ext-lib`. It might be worth renaming it at some point (and also improving the documentation).

**Comment by damhiya** [comment]
I tested following versions of compcert (CompCert does not support coq 8.20 yet)
* coqPackages_8_19.compcert (compcert 3.14)
* coqPackages_8_12.compcert (compcert 3.9)
* coqPackages_8_11.compcert (compcert 3.8)
* coqPackages_8_8.compcert (compcert 3.8)

**Comment by damhiya** [comment]
```nix
    defaultVersion =
      with lib.versions;
      lib.switch coq.coq-version [
        {
          case = range "8.12" "8.20";
          out = "20240715";
        }
        {
          case = range "8.7" "8.11";
          out = "20200624";
        }
      ] null;
```
Here, in the `pkgs/development/coq-modules/MenhirLib/default.nix`,  I used `defaultVersion` to make compcert to be built with appropriate version of `MenhirLib`, but this might not be a good practice since updating default version of `MenhirLib` may break `compcert`. Should I fix this?

**Pull request merged**
