### PR TITLE
php: 7.1.14 -> 7.1.15, 5.6.33 -> 5.6.34

### PR DESCRIPTION
**Pull request by etu**
###### Motivation for this change
A bunch of security fixes and bug fixes.

Also added myself to the list of php maintainers.

This shuould be the last updates of this months releases.

cc @globin 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by etu** [comment]
Port to stable should have been done for #36174 as well, but I don't think it was.

**Comment by obadz** [comment]
@etu, would you mind opening a PR against 17.09 cherry-picking what you think should be ported?

**Comment by fpletz** [comment]
https://github.com/NixOS/nixpkgs/compare/c143deaf16d1...848a4654ca01

**Comment by obadz** [comment]
@fpletz, thanks to you!

**Comment by etu** [comment]
@fpletz That's perfect, thanks :)

**Pull request merged**
