### PR TITLE
starship: 0.33.1 -> 0.34.1

### PR DESCRIPTION
**Pull request by Br1ght0ne**
###### Motivation for this change
https://github.com/starship/starship/releases/tag/v0.34.1

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---
This change is [Reviewable](https://reviewable.io/reviews/nixos/nixpkgs/79282)

### CODE REVIEW

**Comment by Frostman** [comment]
`nixpkgs-review` failed with the following output:

```
builder for '/nix/store/ifsagdc7vcmb9zlqwk7rp3vqsphv08rf-starship-0.34.1.drv' failed with exit code 101; last 10 log lines:
  ...
  376 |         let node_dc = DirContents::from_path(&PathBuf::from(node.path()))?;
      |                                    ^^^^^^^^^ function or associated item not found in `context::DirContents`

  error: aborting due to 4 previous errors

  For more information about this error, try `rustc --explain E0599`.
  error: could not compile `starship`.
  warning: build failed, waiting for other jobs to finish...
  error: build failed
cannot build derivation '/nix/store/rz4ybw1h3nphk8pcfzpyy36viihfqsbb-env.drv': 1 dependencies couldn't be built
[0 built (1 failed), 0.0 MiB DL]
error: build of '/nix/store/rz4ybw1h3nphk8pcfzpyy36viihfqsbb-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/79282
1 package failed to build:
starship
```

**Comment by bbigras** [comment]
I got the same error.

**Comment by bbigras** [comment]
Please try with v0.35.0 which should fix the problem.

**Comment by davidtwco** [comment]
> Please try with v0.35.0 which should fix the problem.

v0.35.1 has also been released.

**Comment by Ma27** [comment]
Did the update and added @filalex77 as co-author :)

**Pull request closed without merging**
