### PR TITLE
treewide: stop using types.string

### PR DESCRIPTION
**Pull request by jian-lin**
It is an error[1] now.

[1]: https://github.com/NixOS/nixpkgs/pull/247848

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by linsui — APPROVED** [review]

**Review by linsui — APPROVED** [review]

**Review by roberth — APPROVED** [review]
Indeed none of these look like they should ever be merged with string concatenation.

**Comment by jian-lin** [comment]
Fixed the linked issue number in the commit message.

**Comment by infinisil** [comment]
Oof I'm a bit surprised these made it in at all, the type should throw a deprecation warning when used. Thanks for the fix!

**Comment by majiru** [comment]
I am sorry for writing one of PRs that used one of these. Do these warnings not appear when building with 'nix build'? I had one in my branch for a while but never noticed any diagnostic output regarding this.

**Comment by infinisil** [comment]
@majiru They should definitely appear with both `nix-build` and `nix build`. What arguments did you use to test it?

**Comment by linsui** [comment]
I only tested my PR with nixos-rebuild. I didn't see any warning.

**Comment by emilazy** [comment]
We had some of these lying around in nix-darwin and they did not throw up any warnings (otherwise I'd have fixed them earlier). I don't know why the warning wasn't working, but it seems like this went from being accepted without complaints directly to a hard error. Not a problem for us, but I just want to flag up that this could cause problems elsewhere in the ecosystem because of that.

**Comment by infinisil** [comment]
Ahh darn, I figured out what went wrong. I thought I implemented nested type deprecation (https://github.com/NixOS/nixpkgs/pull/99132), but it turns out it had to be reverted (https://github.com/NixOS/nixpkgs/pull/121816), which I didn't remember.

**Comment by infinisil** [comment]
I opened a PR with a revert and a `lib.warn` instead of a throw

**Comment by RyzeNGrind** [comment]
Hi any updates on removing the types.string deprecation error? I am just now getting into Nix and NIxOS ecosystem and I cannot rebuild my configuration due to multiple module/nixpkg references coming from this deprecated type error. Kindly advise. 

```
[nixos@shogun:/mnt/c/Users/$USER/WSL]$ sudo nixos-rebuild switch --flake /etc/nixos#
building the system configuration...
error: The type `types.string` is deprecated. See https://github.com/NixOS/nixpkgs/pull/66346 for better alternative types.
(use '--show-trace' to show detailed location information)
```

I see that the master branch has a PR with a fix that's been merged. How do I go about replicating the changes made across the master branch into my Nix machines? Apologies if this is a noob question.

**Comment by Atemu** [comment]
@RyzeNGrind just wait a little and roll back your channel in the mean time. The fix will be in unstable in a few days at most.

**Comment by RyzeNGrind** [comment]
> 

@Atemu Thank you for your response. Is there anyway I can hot patch this fix for now so I can keep working on my systems without the several day delay? Appreciate your help with this matter.

**Comment by roberth** [comment]
`nix-channel` is above my pay grade, but if you have a flake you could upgrade to `master` fairly easily for a couple of days.

Maybe use `-I nixpkgs=https://github.com/NixOS/nixpkgs/archive/master.tar.gz` for something even less reproducible than `nix-channel`?

**Comment by emilazy** [comment]
You can just use `nix-channel --rollback`, I believe. Repeat until the errors go away.

**Comment by Atemu** [comment]
Alternatively, you can also briefly switch to the nixos-unstable-small channel which already has the fix. That's more trouble than it's worth though IMO.

**Pull request merged**
