### PR TITLE
Revert "Revert "Merge pull request #23602 from periklis/topic_qt57_darwin""

### PR DESCRIPTION
**Pull request by periklis**
Revert to get back the changeset and fix for buildInputs missing gtk3 and libinput.

This reverts commit a2eae3bc4433e8d3f3c3690532bf99fdfbd8b3a1.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by LnL7** [comment]
Testing, it's looking good so far.

**Comment by periklis** [comment]
@LnL7 Did the hydra build on linux work?

**Comment by LnL7** [comment]
All the linux builds are green, a few of the qt packages still fail on darwin but those are not new. It looks good to merge unless you also want to fix those.

- [ ] `qt75.qtdeclarative`
- [ ] `qt75.qtscript`
- [ ] `qt57.qttranslations`
```
ln: failed to create symbolic link '/nix/store/8fyyk7l2c0cvdf3k7kiq25d2ncm65zvc-qtdeclarative-5.7.1/lib/QtConcurrent.framework': File exists
builder for ‘/nix/store/cwa4h2v3rffwkqixbbvfvz2xbqkzhhwj-qtdeclarative-5.7.1.drv’ failed with exit code 1
```

**Comment by periklis** [comment]
Thx for the feedback. Let's merge the qtbase part for now. I am on the ln-failed bugs already due to qtcreator. For those i'll open another PR.

**Comment by LnL7** [comment]
Allright, can you add something like the original commit message as the first line of the commit message.

**Comment by periklis** [comment]
Sure i'll amend the commit message in a sec.

**Review by LnL7 — APPROVED** [review]

**Pull request merged**
