### PR TITLE
universal-ctags: generate manpage

### PR DESCRIPTION
**Pull request by teto**
###### Motivation for this change
ctags is a complex program with lots of flags, manpage is really helpful

###### Things done
The manpage is generated via the rst2man utility present in python.docutils. Add it as a nativeBuildInput dependancy.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
cc @mimadrid

**Comment by mimadrid** [comment]
Awesome. Thanks a lot.
Could You also update to the last git commit and delete the sed patch?

**Comment by teto** [comment]
I pushed the required changes; well that was a good idea, it helped me solve https://github.com/majutsushi/tagbar/issues/446#issuecomment-331301162

**Comment by joachifm** [comment]
Thank you

**Pull request merged**
