### PR TITLE
[staging-next] awscli: fix

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
`nimbo` will need to be addressed as well

```
       > pythonCatchConflictsPhase
       > Found duplicated packages in closure for dependency 'PyYAML':
       >   PyYAML 5.4.1 (/nix/store/fi4vpm0mqbcwhqrnwfl06zv85vsa7v98-python3.9-PyYAML-5.4.1/lib/python3.9/site-packages)
       >   PyYAML 6.0 (/nix/store/qpxjvij39nrs1zaha9fsb8sbcpa90w7g-python3.9-PyYAML-6.0/lib/python3.9/site-packages)
       >
       > Package duplicates found in closure, see above. Usually this happens if two packages depend on different version of the same dependency.
       For full logs, run 'nix log /nix/store/0v58v68wx0qksrbhc2yrkzdb7iwrli8z-nimbo-0.2.4.drv'.
       ```

**Comment by dotlambda** [comment]
> `nimbo` will need to be addressed as well

No thanks. `awscli` shouldn't have been in its `propagatedBuildInputs` in the first place because awscli is not a Python module. It also looks like it's not actually used anywhere by nimbo: https://github.com/nimbo-sh/nimbo/search?q=awscli
cc @alexeyre @jozuas

**Comment by jozuas** [comment]
> > `nimbo` will need to be addressed as well
> 
> No thanks. `awscli` shouldn't have been in its `propagatedBuildInputs` in the first place because awscli is not a Python module. It also looks like it's not actually used anywhere by nimbo: https://github.com/nimbo-sh/nimbo/search?q=awscli cc @alexeyre @jozuas

Nimbo does use `awscli`, it's just that the search query example is not accurate - `awscli` is available as `aws` once installed.

**Comment by dotlambda** [comment]
> > > `nimbo` will need to be addressed as well
> > 
> > 
> > No thanks. `awscli` shouldn't have been in its `propagatedBuildInputs` in the first place because awscli is not a Python module. It also looks like it's not actually used anywhere by nimbo: https://github.com/nimbo-sh/nimbo/search?q=awscli cc @alexeyre @jozuas
> 
> Nimbo does use `awscli`, it's just that the search query example is not accurate - `awscli` is available as `aws` once installed.

Sorry, I was inaccurate. It doesn't *import* awscli. Thus please use `makeWrapperArgs` to add awscli to the `$PATH` instead.

**Review by veprbl — APPROVED** [review]
LGTM

**Review by jonringer — APPROVED** [review]
LGTM now

**Pull request merged**
