### PR TITLE
closh init at 0.2.2

### PR DESCRIPTION
**Pull request by hlolli**
This application depends on lumo, which still isn't reviewed after 2 weeks
https://github.com/NixOS/nixpkgs/pull/44076

So this will obviously fail.

Also I have now 3 PR's waiting which include my maintainer entry, don't see a reason to add it to this one, because it stands and falls with lumo, which has my maintainer entry.

Please either review lumo first, or reject this PR and I can reopen it later.

###### Motivation for this change
Great shell based on self-hosted clojurescript

###### Things done

- [ x ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ x ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ x ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ x ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by samueldr** [comment]
`lumo` was just merged, but is [causing a bit of issues](https://github.com/NixOS/nixpkgs/pull/44076#discussion_r232503789).

```
 $ exec env -i NIXPKGS_ALLOW_UNFREE=1 nix-build -A closh
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I), at /Users/samuel/tmp/nixpkgs/nixpkgs-PR44636/pkgs/development/interpreters/clojurescript/lumo/deps.nix:10:17
(use '--show-trace' to show detailed location information)
Command exited with non-zero status 1
```

Though, continuing forward assuming this won't be an issue forever, I checked out this branch, merged master into it, then `nix-build` `closh`. 

```
~/tmp/nixpkgs/nixpkgs-PR44636 1 $ result/bin/closh --help
Could not require closh.history in file closh/main.cljc
         (new)
         Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (NO_SOURCE_FILE <embedded>:2044:72)
         Function.cljs.analyzer.error.cljs$core$IFn$_invoke$arity$3 (NO_SOURCE_FILE <embedded>:2680:92)
         (NO_SOURCE_FILE <embedded>:5990:126)
         (Object.lumo.repl.run_sync_BANG_)
         Object.cljs.js.process_deps (NO_SOURCE_FILE <embedded>:5967:185)
         Object.cljs.js.process_libs_deps (NO_SOURCE_FILE <embedded>:5970:60)
         (NO_SOURCE_FILE <embedded>:5988:306)
         (Object.lumo.repl.run_sync_BANG_)
         Object.cljs.js.process_deps (NO_SOURCE_FILE <embedded>:5967:185)
Cannot find module '/nix/store/psxsg7pvhh09pfvyr9zz6w2nr2hciws8-closh_modules/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node'
         Function.Module._resolveFilename (internal/modules/cjs/loader.cljs:581:15)
         Function.Module._load (internal/modules/cjs/loader.cljs:507:25)
         Module.require (internal/modules/cjs/loader.cljs:637:17)
         require (internal/modules/cjs/helpers.cljs:20:18)
         Object.<anonymous> (/nix/store/psxsg7pvhh09pfvyr9zz6w2nr2hciws8-closh_modules/node_modules/sqlite3/lib/sqlite3.cljs:4:15)
         Module._compile (internal/modules/cjs/loader.cljs:689:30)
         Object.Module._extensions..js (internal/modules/cjs/loader.cljs:700:10)
         Module.load (internal/modules/cjs/loader.cljs:599:32)
         tryModuleLoad (internal/modules/cjs/loader.cljs:538:12)
         Function.Module._load (internal/modules/cjs/loader.cljs:530:3)
```

Am I right in assuming this isn't the intended behaviour?

**Comment by hlolli** [comment]
I'm going to do few changes, after the lumo commit, I realized that it's smarter to add npm deps into the node-packages file, so that the endpoints are shared among more packages. I think in this case, I need to check with the closh peeps, I know exactly why you're getting it, it's a runtime error on closh. I need to see if it's compatible with lumo 1.9.0, since new lumo was only released few days ago.

**Comment by samueldr** [comment]
Oh, quick response :).

It's also possible this is a local error, or possibly from the issue with lumo; `lumo` imported `<nixpkgs>`, which in this case points to *another* branch of `nixpkgs`, (`release-18.09` on my system), while the `closh` and everything else was built on `master`.

**Review by ryantm — CHANGES_REQUESTED** [review]
Fix so `closh --help`  or `closh --version` does not return an error message.

**Comment by mmahut** [comment]
Are there any updates on this pull request, please?

**Comment by hlolli** [comment]
Had forgotten about this one :S give me few days to fix

**Comment by jeaye** [comment]
Following up on this, since it would be superb to have. Thanks for the PR, @hlolli!

**Comment by SuperSandro2000** [comment]
Closing because 1 1/2 years are not a day.

**Pull request closed without merging**
