### PR TITLE
Plasma 5.5.5

### PR DESCRIPTION
**Pull request by ttuegel**
Security updates for the release branch.

/cc @domenkozar

### CODE REVIEW

**Comment by domenkozar** [comment]
@ttuegel did you build all the files and test it starts?

**Comment by ttuegel** [comment]
I haven't built or tested on the release branch yet.

**Comment by ttuegel** [comment]
Upstream has just released yet another bugfix to this release, so it will probably be another day until I can build and test master and then update this branch.

**Comment by ttuegel** [comment]
I have built and tested the latest bugfix. Everything is working, so this PR is good-to-go.

**Comment by domenkozar** [comment]
thanks!

**Pull request merged**
