### PR TITLE
python3.pkgs.jinja2: build offline documentation

### PR DESCRIPTION
**Pull request by KAction**
- python3.pkgs.sphinxcontrib-log-cabinet: init at 1.0.1
- python3.pkgs.sphinx-issues: init at 3.0.1
- python3.pkgs.jinja2: build offline documentation

### CODE REVIEW

**Comment by KAction** [comment]
@GrahamcOfBorg build

**Comment by KAction** [comment]
@happysalada Can you please take a look?

**Comment by happysalada** [comment]
Thanks !

**Comment by Ma27** [comment]
This seems to have broken `systemd`, fix is in #229097.

**Pull request merged**
