### PR TITLE
virtualbox: 6.1.10 -> 6.1.14

### PR DESCRIPTION
**Pull request by Magicloud**
###### Motivation for this change

6.1.14 is the latest release of VirtualBox. And it contains some necessary changes to be built on Linux 5.8 kernel.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by turboMaCk — CHANGES_REQUESTED** [review]
Thanks for contribution @Magicloud.

However, the commit message doesn't follow the guideline. please check example section in https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes . Can you please `git commit --amend` it?

**Comment by evenbrenden** [comment]
Looks like VirtualBox 6.1.10 build is broken on current `nixos-unstable` (61525137fd10) when using `kernelPackages = pkgs.linuxPackages_latest`:
```
In file included from /nix/store/lm27zw14mmif9prrslgawdi0i5wpx25v-linux-5.8.6-dev/lib/modules/5.8.6/source/include/asm-generic/percpu.h:7,
                 from /nix/store/lm27zw14mmif9prrslgawdi0i5wpx25v-linux-5.8.6-dev/lib/modules/5.8.6/source/arch/x86/include/asm/percpu.h:556,
                 from /nix/store/lm27zw14mmif9prrslgawdi0i5wpx25v-linux-5.8.6-dev/lib/modules/5.8.6/source/arch/x86/include/asm/preempt.h:6,
                 from /nix/store/lm27zw14mmif9prrslgawdi0i5wpx25v-linux-5.8.6-dev/lib/modules/5.8.6/source/include/linux/preempt.h:78,
                 from /nix/store/lm27zw14mmif9prrslgawdi0i5wpx25v-linux-5.8.6-dev/lib/modules/5.8.6/source/include/linux/spinlock.h:51,
                 from /build/virtualbox-6.1.10-modsrc/vboxdrv/linux/../SUPDrvInternal.h:79,
                 from /build/virtualbox-6.1.10-modsrc/vboxdrv/linux/SUPDrv-linux.c:32:
/build/virtualbox-6.1.10-modsrc/vboxdrv/linux/SUPDrv-linux.c: In function 'supdrvOSChangeCR4':
/build/virtualbox-6.1.10-modsrc/vboxdrv/linux/SUPDrv-linux.c:760:38: error: 'cpu_tlbstate' undeclared (first use in this function); did you mean 'cpuhp_state'?
  760 |     RTCCUINTREG uOld = this_cpu_read(cpu_tlbstate.cr4);
      |                                      ^~~~~~~~~~~~
/nix/store/lm27zw14mmif9prrslgawdi0i5wpx25v-linux-5.8.6-dev/lib/modules/5.8.6/source/include/linux/percpu-defs.h:318:9: note: in definition of macro '__pcpu_size_call_return'
  318 |  typeof(variable) pscr_ret__;     \
      |         ^~~~~~~~
/build/virtualbox-6.1.10-modsrc/vboxdrv/linux/SUPDrv-linux.c:760:24: note: in expansion of macro 'this_cpu_read'
  760 |     RTCCUINTREG uOld = this_cpu_read(cpu_tlbstate.cr4);
      |                        ^~~~~~~~~~~~~
/build/virtualbox-6.1.10-modsrc/vboxdrv/linux/SUPDrv-linux.c:760:38: note: each undeclared identifier is reported only once for each function it appears in
  760 |     RTCCUINTREG uOld = this_cpu_read(cpu_tlbstate.cr4);
      |                                      ^~~~~~~~~~~~
/nix/store/lm27zw14mmif9prrslgawdi0i5wpx25v-linux-5.8.6-dev/lib/modules/5.8.6/source/include/linux/percpu-defs.h:318:9: note: in definition of macro '__pcpu_size_call_return'
  318 |  typeof(variable) pscr_ret__;     \
      |         ^~~~~~~~
/build/virtualbox-6.1.10-modsrc/vboxdrv/linux/SUPDrv-linux.c:760:24: note: in expansion of macro 'this_cpu_read'
  760 |     RTCCUINTREG uOld = this_cpu_read(cpu_tlbstate.cr4);
      |                        ^~~~~~~~~~~~~
make[4]: *** [/nix/store/lm27zw14mmif9prrslgawdi0i5wpx25v-linux-5.8.6-dev/lib/modules/5.8.6/source/scripts/Makefile.build:280: /build/virtualbox-6.1.10-modsrc/vboxdrv/linux/SUPDrv-linux.o] Error 1
make[3]: *** [/nix/store/lm27zw14mmif9prrslgawdi0i5wpx25v-linux-5.8.6-dev/lib/modules/5.8.6/source/Makefile:1756: /build/virtualbox-6.1.10-modsrc/vboxdrv] Error 2
make[2]: *** [/nix/store/lm27zw14mmif9prrslgawdi0i5wpx25v-linux-5.8.6-dev/lib/modules/5.8.6/source/Makefile:185: __sub-make] Error 2
make[2]: Leaving directory '/nix/store/lm27zw14mmif9prrslgawdi0i5wpx25v-linux-5.8.6-dev/lib/modules/5.8.6/build'
make[1]: *** [/build/virtualbox-6.1.10-modsrc/vboxdrv/Makefile-footer.gmk:114: vboxdrv] Error 2
make[1]: Leaving directory '/build/virtualbox-6.1.10-modsrc/vboxdrv'
make: *** [Makefile:58: vboxdrv] Error 2
builder for '/nix/store/1009iybgsnfr9p5vvkc19aajcxcqnklj-virtualbox-modules-6.1.10-5.8.6.drv' failed with exit code 2
cannot build derivation '/nix/store/cv7lscscdxnbnixn1dh7272az51qg7mf-kernel-modules.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/imcfygi6v5yvbd1pzav77nrj50k0z3w0-linux-5.8.6-modules.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/rjxwdazq3zff1iwb5pssgy5iql31wgkx-linux-5.8.6-modules-shrunk.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/yqq8z4y33g46yggpbah68crqd7xzj465-stage-1-init.sh.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/fh0jm66daaf4qnxpd1yx1qci05v36glm-initrd-linux-5.8.6.drv': 1 dependencies couldn't be built
```
The same configuration builds and runs fine with 6.1.14, so this is a very welcome change :slightly_smiling_face:

**Comment by Magicloud** [comment]
> Thanks for contribution @Magicloud.
> 
> However, the commit message doesn't follow the guideline. please check example section in https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes . Can you please `git commit --amend` it?

Done.

**Comment by Magicloud** [comment]
@evenbrenden One change of 6.1.14 is to support some new features of 5.8 kernel, as I recalled. But not sure if that was exactly what you got.

**Comment by bryanasdev000** [comment]
> @evenbrenden One change of 6.1.14 is to support some new features of 5.8 kernel, as I recalled. But not sure if that was exactly what you got.

Yep, thats what currently happens when you use kernel 5.8 with Virtualbox 6.1.10, more information available at:
https://www.virtualbox.org/ticket/19644?cversion=0&cnum_hist=8
But basically, we need this version bump.

Maybe @svanderburg can help with PR review?

**Comment by Ma27** [comment]
Currently testing this on my 20.09 as I'd like to upgrade my kernel to 5.8, but I need VirtualBox for work atm. If everything is fine, I'd merge & backport, but just to be sure - @evenbrenden @bryanasdev000 @Magicloud @turboMaCk are there any issues with this PR I'm currently missing?

**Comment by evenbrenden** [comment]
No problems here. Been using it with a couple of VMs (Windows and Linux). Running NixOS at `a5931fa6e3` with this PR on top.

**Comment by Ma27** [comment]
I can confirm this as well and will merge tonight. First I'd like to take a look at the failing virtualbox VM test though.

**Comment by Ma27** [comment]
Just fixed the `virtio` support that was originally disabled by @Magicloud due to a misconfigured tarball from upstream. Currently running the VM test locally, after that I'll merge!

**Review by Ma27 — APPROVED** [review]
Works for me fine since yesterday on my machine and I'm not the only one.
The test is unfortunately failing as it times out to boot a VM but this is most likely due to the test being rather slow (because of VBox in QEMU) though it got very far so the functionality of the package update is sufficiently tested IMHO.

**Comment by Ma27** [comment]
Ported to 20.09 as 07504c93648ee155c0f09f2a4b90a6a4cd2a74fc, f3d099fb1d75a2bc3786724c42d0bac1904ca656

**Pull request merged**
