### PR TITLE
open-webui: 0.3.10 -> 0.3.11

### PR DESCRIPTION
**Pull request by drupol**
status: Currently broken because of https://github.com/NixOS/nixpkgs/pull/322896

Could potentially be fixed by https://github.com/NixOS/nixpkgs/pull/332258

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by drupol** [comment]
@ofborg build open-webui

**Comment by drupol** [comment]
Open Webui is broken since #320924

This PR will stay in draft until a solution is found.

**Comment by shivaraj-bh** [comment]
It seems like `open-webui` is broken due to https://github.com/NixOS/nixpkgs/pull/322896, I tried with `asgiref 3.7.2` on python 3.12 and it works fine.

Here’s the diff if you’d like to try:
```
diff --git a/pkgs/development/python-modules/asgiref/default.nix b/pkgs/development/python-modules/asgiref/default.nix
index fecc4b98f490..96b073d091a7 100644
--- a/pkgs/development/python-modules/asgiref/default.nix
+++ b/pkgs/development/python-modules/asgiref/default.nix
@@ -10,7 +10,7 @@
 }:

 buildPythonPackage rec {
-  version = "3.8.1";
+  version = "3.7.2";
   pname = "asgiref";
   format = "setuptools";

@@ -20,7 +20,8 @@ buildPythonPackage rec {
     owner = "django";
     repo = "asgiref";
     rev = "refs/tags/${version}";
-    hash = "sha256-xepMbxglBpHL7mnJYlnvNUgixrFwf/Tc6b1zL4Wy+to=";
+    hash = "sha256-VW1PBh6+nLMD7qxmL83ymuxCPYKVY3qGKsB7ZiMqMu8=";
+    # hash = "sha256-xepMbxglBpHL7mnJYlnvNUgixrFwf/Tc6b1zL4Wy+to=";
   };

   propagatedBuildInputs = [ typing-extensions ];

```

**Comment by shivaraj-bh** [comment]
Perhaps we should wait for upstream [opentelemetry-instrumentation-asgi](https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-asgi) to support `asgiref 3.8.1`

**Comment by drupol** [comment]
Yeah I made this yesterday: https://github.com/NixOS/nixpkgs/pull/331590 but @mweinelt told me it was not a good idea.
I tried to bisect the issue in `opentelemetry-instrumentation-asgi` but I ended up modifying all the `opentelemetry` packages, and it was really a pain to understand what was going on... I gave up.

**Comment by mweinelt** [comment]
> Perhaps we should wait for upstream [opentelemetry-instrumentation-asgi](https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-asgi?rgh-link-date=2024-08-02T09%3A52%3A30Z) to support `asgiref 3.8.1`

Did anyone file an issue yet?

**Comment by drupol** [comment]
Nope, not me.

**Comment by drupol** [comment]
@ofborg build open-webui

**Pull request merged**
