### PR TITLE
rPackages.gdalraster: add system deps

### PR DESCRIPTION
**Pull request by Kupac**
## Description of changes

Added required system dependencies

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by philipp-baumann** [comment]
```sh
nix-shell -p 'rWrapper.override{packages = with rPackages; [ gdalraster ];}' -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/f5b163970956a53d4b82fd052a4a6af22d9bdb3a.tar.gz
```

```sh
configure: CXX: /nix/store/6kpjydf9x7zqa1xq2qipnwr32ki3fs2n-clang-wrapper-16.0.6/bin/c++ -std=gnu++17
checking for gdal-config... no
no
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package 'gdalraster'
* removing '/nix/store/x3a9m4bxbrhl4yvyf69wxjf27316f3ip-r-gdalraster-1.7.0/library/gdalraster'
error: builder for '/nix/store/6kcwaixkg6qzda7zk7rw49nl2ifwb342-r-gdalraster-1.7.0.drv' failed with exit code 1;
       last 10 log lines:
       > * installing *source* package 'gdalraster' ...
       > ** package 'gdalraster' successfully unpacked and MD5 sums checked
       > ** using staged installation
       > configure: CC: /nix/store/6kpjydf9x7zqa1xq2qipnwr32ki3fs2n-clang-wrapper-16.0.6/bin/cc
       > configure: CXX: /nix/store/6kpjydf9x7zqa1xq2qipnwr32ki3fs2n-clang-wrapper-16.0.6/bin/c++ -std=gnu++17
       > checking for gdal-config... no
       > no
       > configure: error: gdal-config not found or not executable.
       > ERROR: configuration failed for package 'gdalraster'
       > * removing '/nix/store/x3a9m4bxbrhl4yvyf69wxjf27316f3ip-r-gdalraster-1.7.0/library/gdalraster'
       For full logs, run 'nix log /nix/store/6kcwaixkg6qzda7zk7rw49nl2ifwb342-r-gdalraster-1.7.0.drv'.
error: 1 dependencies of derivation '/nix/store/pjg56cbi2xrfw1x2cfm2b3y4h2skf2yn-R-4.3.2-wrapper.drv' failed to build
```

**Comment by b-rodrigues** [comment]
FWIW, I built it successfully on  x86_64-linux. @philipp-baumann I guess in your case some macOS-specific config is needed?

**Comment by Kupac** [comment]
@philipp-baumann Could you or someone else check on darwin again? I rebased to current master and restructured a bit. We should find out what is missing on darwin

**Comment by Kupac** [comment]
@ofborg build rPackages.gdalraster

**Comment by philipp-baumann** [comment]
```{r}
> library(gdalraster)
code for methods in class “Rcpp_CmbTable” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_CmbTable” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_GDALRaster” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_GDALRaster” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_RunningStats” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_RunningStats” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
GDAL 3.8.5, released 2024/04/02, PROJ 9.4.0
> sessionInfo()
R version 4.3.3 (2024-02-29)
Platform: aarch64-apple-darwin22.6.0 (64-bit)
Running under: macOS Sonoma 14.2.1

Matrix products: default
BLAS:   /nix/store/csam52q8ksy40sa4q7z5ijx7jixivrby-blas-3/lib/libblas.dylib 
LAPACK: /nix/store/i2ddi7h4bn0qr1bms5bilccp0rd9fnm5-openblas-0.3.26/lib/libopenblasp-r0.3.26.dylib;  LAPACK version 3.12.0

locale:
[1] C/UTF-8/C/C/C/C

time zone: Europe/Zurich
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] gdalraster_1.9.0

loaded via a namespace (and not attached):
[1] compiler_4.3.3 cli_3.6.2      tools_4.3.3    Rcpp_1.0.12    xml2_1.3.6    
[6] rlang_1.1.3
```

**Review by jbedo — APPROVED** [review]

**Pull request merged**
