### PR TITLE
vimPlugins.harpoon: 2023-05-28 -> 2023-10-10

### PR DESCRIPTION
**Pull request by wrbbz**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by jlesquembre — APPROVED** [review]
Thanks! Maybe is worth mentioning that the harpoon version on nixpkgs doesn't work with the latest neovim.

**Comment by wrbbz** [comment]
This one should fix it
There is an error of invalid 'event' that was fixed in the latest commit

**Comment by jlesquembre** [comment]
> This one should fix it There is an error of invalid 'event' that was fixed in the latest commit

Exactly, I notice that my last comment was a bit confusing, sorry.  What I wanted to say is that current nixpkgs harpoon is broken, and this PR fixes it, I'd like to get it merged ASAP.

**Comment by dezren39** [comment]
it seems like this was fixed with #260408 a431eef36f3ec5dde105bfb874089454d235b89f

- https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/vim/plugins/generated.nix#L4062
- https://github.com/NixOS/nixpkgs/pull/260408/files#diff-54bef7a6c9c5497e77086f7935fbfe5c45e285f36f12f15b7044f42430e8e3ebR4062
- image

**Comment by wrbbz** [comment]
Yeah. Seems like it. Closing this now. Thank you!

**Pull request closed without merging**
