### PR TITLE
vopono: init at 0.8.6

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

Add [vopono](https://github.com/jamesmcm/vopono).

_vopono is a tool to run applications through VPN tunnels via temporary network namespaces. This allows you to run only a handful of applications through different VPNs simultaneously, whilst keeping your main connection as normal._

_vopono includes built-in killswitches for both Wireguard and OpenVPN._

_Currently Mullvad, AzireVPN, MozillaVPN, TigerVPN, ProtonVPN, iVPN, NordVPN, HMA (HideMyAss) and PrivateInternetAccess are supported directly, with custom configuration files also supported with the --custom argument._

_For custom connections the OpenConnect and OpenFortiVPN protocols are also supported (e.g. for enterprise VPNs). See the vopono User Guide for more details.__

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by romildo** [comment]
It may be still missing runtime dependencies.

**Comment by figsoda** [comment]
The crates.io version has a Cargo.lock

**Comment by romildo** [comment]
> It may be still missing runtime dependencies.

The runtime dependencies depend on the desired type of VPN connection:
- openfortivpn – for FortiClient VPN connections
- openvpn  – for OpenVPN connections
- shadowsocks-libev – for Shadowsocks support (Mullvad)
- wireguard-tools – for Wireguard connections

The needed tools are expected to be found in the PATH, and should be installed separately.

**Comment by romildo** [comment]
Test on my system, with the commercial HMA-VPN provider (needs a payed account):

``` console
$ result/bin/vopono -v exec --provider hma --server france --protocol OpenVPN "curl https://freegeoip.app/xml/"
[...]
namespace vopono_hma_france with pid 12288
Bind /etc/netns/vopono_hma_france/openvpn.log -> /etc/openvpn.log failed: No such file or directory
<Response>
	<IP>138.199.14.149</IP>
	<CountryCode>FR</CountryCode>
	<CountryName>France</CountryName>
	<RegionCode>PAC</RegionCode>
	<RegionName>Provence-Alpes-Côte d&#39;Azur</RegionName>
	<City>Marseille</City>
	<ZipCode>13000</ZipCode>
	<TimeZone>Europe/Paris</TimeZone>
	<Latitude>43.2855</Latitude>
	<Longitude>5.3693</Longitude>
	<MetroCode>0</MetroCode>
</Response>
[...]
```

**Review by thiagokokada — APPROVED** [review]
Result of `nixpkgs-review pr 141989` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>vopono</li>
  </ul>
</details>

**Pull request merged**
