### PR TITLE
fix font fallout from extraPostFetch -> postFetch

### LINKED ISSUE #174849: symbola fails to unpack
I'm not sure if the remote file or [fetchzip changed](https://github.com/NixOS/nixpkgs/pull/173430), but something seems to have broken recently...

### Steps To Reproduce

1. build *symbola*

### Build log
```
builder for '/nix/store/10cny769wbnnavab5hh11qllgq0bvk3y-symbola-13.00.drv' failed with exit code 1; last 8 log lines:
  
  trying https://dn-works.com/wp-content/uploads/2020/UFAS-Fonts/Symbola.zip
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
  100 3581k  100 3581k    0     0   691k      0  0:00:05  0:00:05 --:--:--  812k
  unpacking source archive /build/Symbola.zip
  error: zip file must contain a single file or directory.
  hint: Pass stripRoot=false; to fetchzip to assume flat list of files.
```

### Additional context

This also seems to be out of date since there's a version 14, but it's [uploaded as a pdf attachment rather than a zip???](https://dn-works.com/wp-content/uploads/2021/UFAS121921/Symbola.pdf)

### Notify maintainers
cc @marsam 

### Metadata

22aa8e5c7a19a9e74af9f223b0e033341629d92d

### PR DESCRIPTION
**Pull request by Artturin**
see commit msg

Closes https://github.com/NixOS/nixpkgs/issues/174849

see 

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Artturin** [comment]
one more to fix but the src for it is downloading really slow for me `kochi-substitute-naga10`

this can be merged without it

**Comment by wizeman** [comment]
`font-awesome` and `mplus-outline-fonts` seem to be broken as well.

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/176177

**Comment by sersorrel** [comment]
I think this also broke `ia-writer-duospace`:

```
       > trying https://github.com/iaolo/iA-Fonts/archive/55edf60f544078ab1e14987bc67e9029a200e0eb.tar.gz
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
       > 100 1643k    0 1643k    0     0  1944k      0 --:--:-- --:--:-- --:--:-- 8936k
       > unpacking source archive /build/55edf60f544078ab1e14987bc67e9029a200e0eb.tar.gz
       > tar (child): /build/file: Cannot open: No such file or directory
       > tar (child): Error is not recoverable: exiting now
       > tar: Child returned status 2
       > tar: Error is not recoverable: exiting now
```

**Pull request merged**
