### PR TITLE
zfsUnstable: 2.2.0-rc4 -> 2.2.0-rc5

### PR DESCRIPTION
**Pull request by adamcstephens**
## Description of changes

https://github.com/openzfs/zfs/releases/tag/zfs-2.2.0-rc5

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by adamcstephens** [comment]
Result of `nixpkgs-review pr 259625` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>23 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_4_14.zfsUnstable</li>
    <li>linuxKernel.packages.linux_4_14_hardened.zfsUnstable</li>
    <li>linuxKernel.packages.linux_4_19.zfsUnstable</li>
    <li>linuxKernel.packages.linux_4_19_hardened.zfsUnstable</li>
    <li>linuxKernel.packages.linux_5_10.zfsUnstable</li>
    <li>linuxKernel.packages.linux_5_10_hardened.zfsUnstable</li>
    <li>linuxKernel.packages.linux_5_15.zfsUnstable</li>
    <li>linuxKernel.packages.linux_5_15_hardened.zfsUnstable</li>
    <li>linuxKernel.packages.linux_5_4.zfsUnstable</li>
    <li>linuxKernel.packages.linux_5_4_hardened.zfsUnstable</li>
    <li>linuxKernel.packages.linux_6_1.zfsUnstable</li>
    <li>linuxKernel.packages.linux_hardened.zfsUnstable (linuxKernel.packages.linux_6_1_hardened.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_6_5.zfsUnstable</li>
    <li>linuxKernel.packages.linux_6_5_hardened.zfsUnstable</li>
    <li>linuxKernel.packages.linux_latest_libre.zfsUnstable</li>
    <li>linuxKernel.packages.linux_libre.zfsUnstable</li>
    <li>linuxKernel.packages.linux_lqx.zfsUnstable</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.zfsUnstable</li>
    <li>linuxKernel.packages.linux_xanmod.zfsUnstable</li>
    <li>linuxKernel.packages.linux_xanmod_latest.zfsUnstable (linuxKernel.packages.linux_xanmod_stable.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_zen.zfsUnstable</li>
    <li>zfsUnstable</li>
    <li>zfsUnstable.dev</li>
  </ul>
</details>

-----

Result of `nixpkgs-review pr 259625` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.linux_6_5.zfsUnstable</li>
    <li>linuxKernel.packages.linux_6_5_hardened.zfsUnstable</li>
    <li>linuxKernel.packages.linux_latest_libre.zfsUnstable</li>
    <li>linuxKernel.packages.linux_lqx.zfsUnstable</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.zfsUnstable</li>
    <li>linuxKernel.packages.linux_xanmod.zfsUnstable</li>
    <li>linuxKernel.packages.linux_xanmod_latest.zfsUnstable</li>
    <li>linuxKernel.packages.linux_xanmod_stable.zfsUnstable</li>
    <li>linuxKernel.packages.linux_zen.zfsUnstable</li>
  </ul>
</details>
<details>
  <summary>15 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_4_14.zfsUnstable</li>
    <li>linuxKernel.packages.linux_4_14_hardened.zfsUnstable</li>
    <li>linuxKernel.packages.linux_4_19.zfsUnstable</li>
    <li>linuxKernel.packages.linux_4_19_hardened.zfsUnstable</li>
    <li>linuxKernel.packages.linux_5_10.zfsUnstable</li>
    <li>linuxKernel.packages.linux_5_10_hardened.zfsUnstable</li>
    <li>linuxKernel.packages.linux_5_15.zfsUnstable</li>
    <li>linuxKernel.packages.linux_5_15_hardened.zfsUnstable</li>
    <li>linuxKernel.packages.linux_5_4.zfsUnstable</li>
    <li>linuxKernel.packages.linux_5_4_hardened.zfsUnstable</li>
    <li>linuxKernel.packages.linux_6_1.zfsUnstable</li>
    <li>linuxKernel.packages.linux_hardened.zfsUnstable (linuxKernel.packages.li
nux_6_1_hardened.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_libre.zfsUnstable</li>
    <li>zfsUnstable</li>
    <li>zfsUnstable.dev</li>
  </ul>
</details>

**Comment by colemickens** [comment]
Should this PR restore this section of `unstable.nix`?

https://github.com/NixOS/nixpkgs/commit/ae3682cb17b93d2d3bedf4be439c4a9688760881#diff-40db61da8cd9690f6398f3ac6a731cac833f23abd6aa53b1029f103eb38fb336

Without it this PR downgrades my kernel.

**Review by RaitoBezarius — APPROVED** [review]
Untested but LGTM.

**Comment by adamcstephens** [comment]
> Without it this PR downgrades my kernel.

Updated. You missed the 5 day window where it would have downgraded anyway. :)

**Comment by colemickens** [comment]
I had my own hacky version :speak_no_evil: and I'm patching the kernel for HDR, so I just happened to notice the rebuild when applying the earlier version.

This looks good to me, I've been running a rc4.5 for a while, rc5 is actually released, and has continued working.

**Pull request merged**
