### PR TITLE
firefoxPackages.tor-browser: 7.5.6 -> 8.0.2

### PR DESCRIPTION
**Pull request by oxij**
###### Motivation for this change

Update.

###### Things done

- [X] Cleanup looked a bit scary, so I built all `firefoxPackages` and they still build fine.
- [X] `firefox` and both `tor-browser*` outputs still work as before.

`tor-browser-bundle` is likely to need changes after this.

/cc @joachifm

### CODE REVIEW

**Comment by oxij** [comment]
Always something unexpected =/

**Comment by oxij** [comment]
@GrahamcOfBorg build firefoxPackages.firefox

**Comment by oxij** [comment]
> It took me a few moments to see what happened to `overrides` but I suppose that's an internal detail nobody is likely to depend on?

Yes. Standard `override` and `overrideAttrs` should be used instead.

OfBorg error for `tor-browser` seems really weird, though. It built flawlessly before rebase =/ I left it building on top of master to try to reproduce it, will see.

**Comment by joachifm** [comment]
@GrahamcOfBorg build firefoxPackages.firefox

**Comment by joachifm** [comment]
I take it this is good to go now?

**Comment by oxij** [comment]
Yes. Everything builds now.

**Comment by joachifm** [comment]
Awesome. Thank you

**Pull request merged**
