### PR TITLE
Hash url fixes

### PR DESCRIPTION
**Pull request by deepfire**
1. Fix iwlwifi driver URLs -- the old ones now emit HTML instead of tarballs
2. FIx transmission source package URL
3. Fix libgltf URL

### CODE REVIEW

**Comment by vcunat** [comment]
I don't see your commits changing any hashes. Why the comment? BTW, you did test the downloads, right?

**Comment by lethalman** [comment]
All the builds are successful on travis btw. Except the last nixpkgs release which failed due to long evaluation I think.

**Comment by deepfire** [comment]
@vcunat, I have traced down the old URLs now spewing out HTML instead of tarballs.  Rewrote this branch to fix the URLs.

**Comment by deepfire** [comment]
Ah, sorry folks, I have screwed up the new URLs nevertheless..

**Comment by vcunat** [comment]
Hmm, iwlwifi still not fixed, and I can't find a mirror for some of the files in there. Hopefully upstream fixes the primary sources soon.

**Comment by vcunat** [comment]
I reported the broken links [upstream](mailto:linux-wireless@vger.kernel.org).

**Comment by deepfire** [comment]
Upstream's initial question was:
```
"Grumbach, Emmanuel" <emmanuel.grumbach@intel.com> writes:
> On Tue, 2015-02-03 at 00:52 +0300, Serge Kosyrev wrote:
> It isn't very easy to figure out who should be contacted about this,
> so I went on a limb and chose the latest linux-firmware.git committer,
> which happened to be you.  : -)

Yeah - you contacted the right person.
One question though: who is using these links?
I thought all the distros were using the linux-firmware.git repo.
```

**Comment by vcunat** [comment]
All should be fixed now.

**Pull request closed without merging**
