### PR TITLE
calamares installer: quality of life improvements

### PR DESCRIPTION
**Pull request by vlinkz**
###### Description of changes

Since the release of NixOS 22.05 I have been monitoring the community response to the calamares installer, and any sore points that could be easily fixed to improve the experience. This PR addresses some of those little things that could make the default installation experience better

###### Things done

- Remove idle screen off while installing with the GNOME ISO
- Increase default verbosity, allowing for users to view `nixos-install` installation output in the calamares log view
  - Updated [calamares-nixos-extensions](https://github.com/nixos/calamares-nixos-extensions) to improve log output
- Update to the latest release of calamares: 3.2.59

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by knedlsepp** [comment]
Just watched https://youtu.be/ck4J2Faa7Fc and my main takeaway was that the option to enable/disable "strong passwords" should be mentioned before the actual password form.
(I'm sorry this is completely unrelated to your other changes)

**Comment by vlinkz** [comment]
I saw that too, but the position is handled by calamares itself, so probably better as an upstream issue: https://github.com/calamares/calamares/issues. Thanks for bringing it up though!

**Comment by tpwrules** [comment]
Is there a nice place to document some comments I had? I ran through it and had a few but wasn't sure if I should make issues, or if there was a thread somewhere.

**Comment by AndersonTorres** [comment]
> Is there a nice place to document some comments I had? I ran through it and had a few but wasn't sure if I should make issues, or if there was a thread somewhere.

Try it here or in the Discourse

**Comment by canadaduane** [comment]
I tried installing twice and gave up because it seemed stuck at 46%. I see reddit comments about this and will give it another go tonight. Is there a way to indicate progress during this period? (I'm still not sure what it's doing for 20 minutes).

**Comment by mweinelt** [comment]
I noticed that in the mentioned video  the firefox package is still part of `environment.systemPackages` instead of in `user.users.foo.packages`. We also added thunderbird. 

We made that change in https://github.com/NixOS/nixpkgs/commit/6051f8028dd0487d73a657b524e4247934d34350

**Comment by vlinkz** [comment]
Ok, I'll make appropriate changes to the config generated by the installer to best match that format. Right now Firefox is installed by default on all desktops, I'm thinking leave that, but add thunderbird commented out

**Comment by vlinkz** [comment]
> I noticed that in the mentioned video the firefox package is still part of `environment.systemPackages` instead of in `user.users.foo.packages`. We also added thunderbird.
> 
> We made that change in [6051f80](https://github.com/NixOS/nixpkgs/commit/6051f8028dd0487d73a657b524e4247934d34350)

I changed the configuration to match that in the commit. As for the rest of the issues, we should probably move them to separate issues so it's easier to track individually.

**Pull request merged**
