### PR TITLE
Updated chromium-browser versions

### PR DESCRIPTION
**Pull request by bendlas**
Latest chromium-browser versions for dev, beta and stable channels as per ./update.sh

### CODE REVIEW

**Comment by iElectric** [comment]
cc @aszlig

**Comment by bendlas** [comment]
Hm, the build failed with an ICE.
FWIW, I built it on my machine as an out-of-tree build against an otherwise pretty vanilla stable-channel system and I'm writing this message from the latest chromium-stable that resulted `39.0.2171.95 (64-bit)`.

```
$ nix-channel --list
nixos https://nixos.org/channels/nixos-14.12
```

Should I have filed the pull request against the 14.12 branch?

**Comment by aszlig** [comment]
I've got a jobset on my Hydra to do [automatic updates of Chromium](https://headcounter.org/hydra/jobset/aszlig/chromium) and found this already, looking into this along with #5730.

**Comment by bendlas** [comment]
I didn't intend to close this issue when i force pushed the commit out of my branch. I'm currently running 40.0.2214.91, built from nix.

**Comment by aszlig** [comment]
@bendlas: Haha, perfect timing, just pushed the update in ced5afc38c2ea5122bbb9c7d0e455aaeaac8cabd.

**Pull request closed without merging**
