### PR TITLE
linux: 5.4.15 -> 5.5.0

### PR DESCRIPTION
**Pull request by colemickens**
#### Motivation for this change

Update `linux-stable` to `5.5.0`since it has been released.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by colemickens** [comment]
Should I go ahead and drop 5.4.x?

**Comment by Frostman** [comment]
I've tried it using `nixpkgs-review` tool and got 50+ errors. Here are the first couple of them:

```
builder for '/nix/store/yim933vcac3n32hz8fypq34rz69q5a8v-bpftool-5.5.drv' failed with exit code 2; last 10 log lines:

  Auto-detecting system features:
  ...                        libelf: [ on  ]
  ...                           bpf: [ on  ]

  /nix/store/715fljdrspphbdk255r729zxp4w7lcgk-bash-4.4-p23/bin/bash: /build/linux-5.5/scripts/bpf_helpers_doc.py: /usr/bin/python3
: bad interpreter: No such file or directory
  make[1]: *** [Makefile:185: bpf_helper_defs.h] Error 126
  make[1]: *** Deleting file 'bpf_helper_defs.h'
  make[1]: Leaving directory '/build/linux-5.5/tools/lib/bpf'
  make: *** [Makefile:32: /build/linux-5.5/tools/lib/bpf/libbpf.a] Error 2
builder for '/nix/store/bhjvljc8wrcqx3prrs5lygwzc5hyhs56-perf-linux-5.5.drv' failed with exit code 2; last 10 log lines:
    LD       libsubcmd-in.o
    LD       libperf-in.o
    HOSTLD   pmu-events/jevents-in.o
    AR       libsubcmd.a
    AR       libperf.a
    PERF_VERSION = 5.5.0
    LD       libtraceevent-in.o
    LINK     libtraceevent.a
  make[1]: *** [Makefile.perf:225: sub-make] Error 2
  make: *** [Makefile:70: all] Error 2
```

Just in case, I'm running release-19.09 with the latest kernel. Not sure if it's something with my setup...

**Comment by dtzWill** [comment]
Ran into few failures, so far they're the same issue manifesting in various kernel-source-based-utilities like `perf`.   Here are fixes I've put together so far, FWIW:

* perf: dda91929e7dccdf860951496ac9513e273d2c0b9
* bpftrace: 624726783c7ce930cff0744f1404e801e84e43d7
...

**Comment by worldofpeace** [comment]
This conflicts with https://github.com/NixOS/nixpkgs/pull/78713

**Comment by vcunat** [comment]
How so?

**Comment by samueldr** [comment]
> Should I go ahead and drop 5.4.x?

No! 5.4 is an LTS. We keep all LTS until EOL'd.

**Comment by samueldr** [comment]
cc @NeQuissimus who's been handling kernel updates for a while.

**Comment by worldofpeace** [comment]
Hmmmmmmm, feels like I'm getting deja vu @colemickens because of https://github.com/NixOS/nixpkgs/commit/ff54d08dc84474c0cac37116e33619dfa11747b0, and it isn't the first time it happened.
Guess I should close this, sorry about that.

**Pull request closed without merging**
