### PR TITLE
mbrola-voices: extract from mbrola, allow language selection

### PR DESCRIPTION
**Pull request by mweinelt**
Allow filtering voices based on any number of extglob patterns.

## Description of changes

Restricting mbrola-voices to only one voice per language saves 387M, and is what I recommend we should do on the ISO, because it likely doesn't compromise accessbility too much.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by vcunat** [comment]
> kept as a fixed-output derivation to limit "duplicates"

I wonder if it's worth the effort to make the default one a FOD again.

For the files that often remain in people's closures.  I think it could make a significant difference for some people, unless they have `nix.settings.auto-optimise-store = true;` or filesystem-level deduplication.

**Comment by mweinelt** [comment]
> I wonder if it's worth the effort to make the default one a FOD again.

Defaulting to the derivation source now for mbrola, so the default is effectively that again.

**Comment by vcunat** [comment]
I think that piece of code doesn't work as intended?  Maybe because of the self-reference.  I still see this in the default closure
```
/nix/store/8ja11xcr6dbvh1bfc0p3ny79jdwwgvmg-mbrola-voices-0-unstable-2020-03-30
```

**Comment by vcunat** [comment]
Maybe we could write `mbrola-voices` like this?
```nix
if languages == [ ] then src // { inherit meta; } else stdenv.mkDerivation { inherit src meta; /*...*/ }

**Comment by vcunat** [comment]
🤔 the overlay approach won't be a good longer-term solution, as it really needs lots of rebuild work to get the ISOs (every time a rebuild happens).  Users would be slightly impacted on installation from that media, as hashes of those packages would differ, so they couldn't be pulled from the ISO.

Using the reduced set of voices by default... maybe, I'm no good with accessibility.  Decoupling the data and plugging it by some environment variable is probably the best shot for longer-term solutions, though it's "less pure".  Maybe this WIP PR: #329658

**Comment by vcunat** [comment]
For the immediate unblocking I increased the limit on Hydra a bit, so that we have some time to improve the closure sizes.

**Comment by vcunat** [comment]
Superseded by https://github.com/NixOS/nixpkgs/pull/329658

**Comment by vcunat** [comment]
At least I think we're not missing anything now.

**Pull request closed without merging**
