### PR TITLE
zcash: 2.1.1-1 -> 4.1.1; fix build

### PR DESCRIPTION
**Pull request by alyssais**
This is pretty much a repackaging, because a lot has changed about
zcash in two major versions.  Lots of libraries are no longer
necessary, and librustzcash is now part of the zcash package as
opposed to being a library supposed to be built seperately.

The whole thing is a buildRustPackage because that's easier than
trying to emulate buildRustPackage's dependency setup behaviour inside
a normal mkDerivation.  So that the normal zcash build process is
followed, the actual configuring and building uses the normal stdenv
behaviour.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by RaghavSood** [comment]
Result of `nixpkgs-review pr 107184` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>zcash</li>
  </ul>
</details>

**Comment by RaghavSood** [comment]
Builds and basic things like printing help work fine, I will run try and sync to the mainnet over the weekend and verify that it all works fine.

LGTM so far

Thank you for fixing this! I gave it a short some weeks ago but realized it would need to be a rewrite and shelved it.

**Review by prusnak — APPROVED** [review]
LGTM

Since you are rewriting the whole thing, maybe you can also use `nixpkgs-fmt` formatter to re-format the code (mainly to put dependencies on separate lines, making further reviews easier).

**Comment by alyssais** [comment]
> Since you are rewriting the whole thing, maybe you can also use
> `nixpkgs-fmt` formatter to re-format the code (mainly to put
> dependencies on separate lines, making further reviews easier).

I find that style very hard to read, and it's inconsistent with all the
examples in the manual, so I'm going to leave it as it is.

**Comment by alyssais** [comment]
@RaghavSood did you get a chance to try a mainnet sync?

**Comment by RaghavSood** [comment]
Apologies, I didn't get a chance to get to it last weekend.

It is syncing now, so far so good - about 10% of the way through

**Comment by RaghavSood** [comment]
Syncs fine until chaintip, cli and fetch params work as expected

**Review by RaghavSood — APPROVED** [review]

**Pull request merged**
