### PR TITLE
bluez: use python3

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/issues/18185

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @abbradar 

Note that this was not tested.

### CODE REVIEW

**Comment by Infinisil** [comment]
Python 2 still gets pulled in because of the bluez dependency. Can you make bluez use Python 3 as well?

**Comment by Infinisil** [comment]
Tested it quickly, works without problems

**Comment by dotlambda** [comment]
I'm not sure whether this should have been merged into master.

**Comment by Infinisil** [comment]
@dotlambda I think just a big number of rebuilds doesn't automatically mean staging, staging is mainly thought for stdenv big things afaik. So I think this is okay.

Also, the above failure seems to be from Rust not building again, not related to this PR (I didn't notice because I didn't test off the merge, ofborg does).

**Pull request merged**
