### PR TITLE
Update python-cryptography to 1.0.

### PR DESCRIPTION
**Pull request by mdorman**
This does require upgrading both pyasn1 and crytography-vectors to their
latest versions, as well as adding the idna package.

### CODE REVIEW

**Comment by mdorman** [comment]
Most importantly, this change depends on #9257.

I believe it's the right thing to do, at least generally---without it, and even with the rev of the `py` dependency, python-cryptography will not build, and that does disable a number of packages, including the package that got me looking into this, `borg`.

That said, I did a nox-review run, and while I saw several failures that were clearly issues with the packages in question---a few source URLs no longer work---I am not certain that all the failures were of that sort, and I'm not 100% certain how to sort the wheat from the chaff.

**Comment by vbgl** [comment]
Does this build ? I get errors about missing `ipaddress` and `enum34`. Said errors vanish after adding this packages in the `buildInputs` of `cryptography`.

**Comment by mdorman** [comment]
It does build for me, for python34, which I guess is the default.  I'm assuming from the fact that you had to add enum34, that that's not the one you're building against?

Trying to work through the issues that arise from 'nox-review' has actually led me to tweak this change a bit (as well as fix what seems to be a bunch of unbuildable packages) in some of the ways you note; I hope to finish working through those issues today, at which time I'll update this PR.

**Comment by mdorman** [comment]
I'll also note that I think you'll find if you only add those things to buildInputs, openssl (for instance), will fail.  I think they need to be propagatedBuildInputs.

That said, I am spectacularly ignorant about much of this stuff---I'm no python guy, and I'm a pretty mediocre nix guy to boot.  I just want to be able to 'nix-env -i borg'.  I'm only taking on all this other stuff in service of getting that working.  If someone more conversant and literate about this stuff is willing to take it on, I would be quite happy to step aside; this was not how I anticipated spending my weekend.

**Comment by jagajaga** [comment]
Please rename commit's name following our guide in `CONTRIBUTING.md`.

**Comment by mdorman** [comment]
This is, I believe, as far as I can take this change.

Starting from the initial changes (adding `idna`, upgrading `pyasn1`, `cryptography-vectors` and `cryptography`, now split out into individual commits), I ran `nox-rebuild` to make sure that this covered everything it could.

This lead me to add three more commits.  One upgrades the `propagatedBuildInputs` attribute for `pyopenssl` to include `pyasn1` and `idna`, both of which seem to be necessary for packages which use `cryptography`, which it already propagates.  I did this because otherwise I was adding them to several packages individually.

Then two of the packages that depend on `cryptography`, `python-SleekXMPP` and `python-Electrum` were unbuildable because the source was no longer located in the given location.  So I updated the URLs (and, inevitably, the SHAs) to reflect that.

This does not leave an entirely clean build from `nox-rebuild`!  However, I believe that the remaining failures to build (`taskw` which has a testing error, which causes `bugwarrior` to fail as well, `backintime` which has an unrelated build error, `fedpkg`, which seems to be part of the `python-fedora` stuff that already has PRs in play, and `nova` whose current version is no longer available, is three years old, and cannot be easily upgraded) do not represent issues with `cryptography`, and they're involved enough that I don't have time---and not being much of a python guy, a whole lot of enthusiasm---to try and resolve them.

**Comment by mdorman** [comment]
@jagajaga I think all the commits in this PR now conform to the document---thanks for pointing me towards is.

**Comment by mdorman** [comment]
Thanks!

**Pull request merged**
