### PR TITLE
Use ncurses6 on all platforms

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

Consistency, ncurses6 goodness for all.
Follow-up to #33376.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

(I don't have any Darwin machines to test this with, sorry)

### CODE REVIEW

**Comment by LnL7** [comment]
@GrahamcOfBorg eval

**Comment by LnL7** [comment]
I thought so, this will need to go to staging first.

**Comment by dtzWill** [comment]
Aye aye!

**Review by LnL7 — APPROVED** [review]
This looks good, now that the ncurses6 darwin fix is in staging. 😄

**Pull request merged**
