### PR TITLE
julia_18: init at 1.8.1

### PR DESCRIPTION
**Pull request by NickCao**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NickCao** [comment]
Tree diff against the binary distribution, the symlinks for system libraries are patched out.
```
1c1
< /nix/store/ca4hhym3f57vpmhgvylvqp86cmz9gbis-julia-bin-1.8.1
---
> /nix/store/xll9dwfanhdbgz0wdpns5xljqh4as4mi-julia-1.8.1
51,53d50
< │   │   ├── libatomic.so -> libatomic.so.1.2.0
< │   │   ├── libatomic.so.1 -> libatomic.so.1.2.0
< │   │   ├── libatomic.so.1.2.0
74,76d70
< │   │   ├── libcurl.so -> libcurl.so.4.8.0
< │   │   ├── libcurl.so.4 -> libcurl.so.4.8.0
< │   │   ├── libcurl.so.4.8.0
78,93d71
< │   │   ├── libgcc_s.so.1
< │   │   ├── libgfortran.so -> libgfortran.so.5.0.0
< │   │   ├── libgfortran.so.5 -> libgfortran.so.5.0.0
< │   │   ├── libgfortran.so.5.0.0
< │   │   ├── libgit2.so -> libgit2.so.1.3
< │   │   ├── libgit2.so.1.3 -> libgit2.so.1.3.0
< │   │   ├── libgit2.so.1.3.0
< │   │   ├── libgmp.so -> libgmp.so.10.4.1
< │   │   ├── libgmp.so.10 -> libgmp.so.10.4.1
< │   │   ├── libgmp.so.10.4.1
< │   │   ├── libgmpxx.so -> libgmpxx.so.4.6.1
< │   │   ├── libgmpxx.so.4 -> libgmpxx.so.4.6.1
< │   │   ├── libgmpxx.so.4.6.1
< │   │   ├── libgomp.so -> libgomp.so.1.0.0
< │   │   ├── libgomp.so.1 -> libgomp.so.1.0.0
< │   │   ├── libgomp.so.1.0.0
106d83
< │   │   ├── libLLVM-13jl.so
108,126c85,86
< │   │   ├── libLLVM.so -> libLLVM-13jl.so
< │   │   ├── libmbedcrypto.so -> libmbedcrypto.so.7
< │   │   ├── libmbedcrypto.so.2.28.0
< │   │   ├── libmbedcrypto.so.7 -> libmbedcrypto.so.2.28.0
< │   │   ├── libmbedtls.so -> libmbedtls.so.14
< │   │   ├── libmbedtls.so.14 -> libmbedtls.so.2.28.0
< │   │   ├── libmbedtls.so.2.28.0
< │   │   ├── libmbedx509.so -> libmbedx509.so.1
< │   │   ├── libmbedx509.so.1 -> libmbedx509.so.2.28.0
< │   │   ├── libmbedx509.so.2.28.0
< │   │   ├── libmpfr.so -> libmpfr.so.6.1.0
< │   │   ├── libmpfr.so.6 -> libmpfr.so.6.1.0
< │   │   ├── libmpfr.so.6.1.0
< │   │   ├── libnghttp2.so -> libnghttp2.so.14.22.0
< │   │   ├── libnghttp2.so.14 -> libnghttp2.so.14.22.0
< │   │   ├── libnghttp2.so.14.22.0
< │   │   ├── libopenblas64_.0.3.20.so
< │   │   ├── libopenblas64_.so -> libopenblas64_.0.3.20.so
< │   │   ├── libopenblas64_.so.0 -> libopenblas64_.0.3.20.so
---
> │   │   ├── libopenblas64_.so
> │   │   ├── libopenblas64_.so.0 -> libopenblas64_.so
130,135d89
< │   │   ├── libpcre2-8.so -> libpcre2-8.so.0.11.0
< │   │   ├── libpcre2-8.so.0 -> libpcre2-8.so.0.11.0
< │   │   ├── libpcre2-8.so.0.11.0
< │   │   ├── libquadmath.so -> libquadmath.so.0.0.0
< │   │   ├── libquadmath.so.0 -> libquadmath.so.0.0.0
< │   │   ├── libquadmath.so.0.0.0
142,150d95
< │   │   ├── libssh2.so -> libssh2.so.1
< │   │   ├── libssh2.so.1 -> libssh2.so.1.0.1
< │   │   ├── libssh2.so.1.0.1
< │   │   ├── libssp.so -> libssp.so.0.0.0
< │   │   ├── libssp.so.0 -> libssp.so.0.0.0
< │   │   ├── libssp.so.0.0.0
< │   │   ├── libstdc++.so -> libstdc++.so.6.0.29
< │   │   ├── libstdc++.so.6 -> libstdc++.so.6.0.29
< │   │   ├── libstdc++.so.6.0.29
157,159d101
< │   │   ├── libunwind.so -> libunwind.so.8.0.1
< │   │   ├── libunwind.so.8 -> libunwind.so.8.0.1
< │   │   ├── libunwind.so.8.0.1
163,165d104
< │   │   ├── libz.so -> libz.so.1
< │   │   ├── libz.so.1 -> libz.so.1.2.12
< │   │   ├── libz.so.1.2.12
171,172c110
< │   └── 7z
< ├── LICENSE.md
---
> │   └── 7z -> /nix/store/cnngxa3xfn55fbph8qmi42cgliwxbf7i-p7zip-17.04/bin/7z
553d490
<     │   ├── cert.pem
2443c2380
< 534 directories, 1906 files
---
> 534 directories, 1843 files
```

**Comment by MikiVanousek** [comment]
I actually need Julia on `aarch-64`urgently. Can I use the derivation from this PR? If it's working, I might use this branch of Nixpkgs and rebuild my system from it.

**Comment by NickCao** [comment]
> I actually need Julia on `aarch-64`urgently. Can I use the derivation from this PR? If it's working, I might use this branch of Nixpkgs and rebuild my system from it.

Both this derivation and the one from https://github.com/NixOS/nixpkgs/pull/191800 should work, if you are in an urgent need, the binary distribution would save you some non trivial time of compilation.

**Comment by NickCao** [comment]
> Is the test suite passing?

All of them except the skipped few.

> 1. Should we not lift in Arch’s patches into our own repo?

`fetchurl` works just fine.

> 2. `sanity.patch` should probably be split into separate patches akin to what we have for 1.0, 1.5, etc.

I would take care of that, and give them better names.

> 3. Why are we skipping tests for ...

These tests are either checking for hard-coded version numbers, or looking for a non-existent vendored copy of CA certificates.

> 4. I think the correct value for `installCheckTarget` is `testall`

Let me check it again.

> 5. I seem to recall that you need `dontStrip = true` to not break backtraces.

I'm not sure what the backtrace should look like, I would compare it with the ones from the binary distribution.

> them swapping up pieces such as Julia’s patched LLVM without understanding the implications. 

I see a bunch of warnings when compiling with our upstream LLVM, there sure could be minor issues, but given that using any system library is already giving us an unsupported build and the tests are passing, I would not be bothered with this too much.

**Comment by 7c6f434c** [comment]
I could easily imagine Julia not having sufficient tests to cover the differences in LLVM. Do we know what the patches are supposed to achieve?

**Comment by NickCao** [comment]
@Moelf would you like to provide us with some suggestions on packaging, like whether it is acceptable to use an unpatched version of llvm.

**Comment by Moelf** [comment]
From @vchuvary 

>Oh these are backend specific sometimes, So you won't see them until you run on PPC or Aarch64

**Comment by ararslan** [comment]
> Do you have the cycles to provide an opinion on what we allow Julia to vendor and not for the packaging here?

I unfortunately don't know at this point what absolutely needs to be vendored due to critical patches and what can safely use a system library. Historically the former has been at least LLVM and OpenBLAS and I suspect that's still the case. @staticfloat, as a whisperer of third party dependencies, can you comment on this at all?

I don't really know the NixOS ethos around such things but is it possible to repackage the official binaries from https://julialang.org/download? That should provide the best user experience from a Julia perspective, though perhaps not from a Nix perspective.

**Comment by Moelf** [comment]
my understanding is their "shtick" (good thing!) is the package manager can handle what traditional Linux distro can't, for example, two packages critically need to patch LLVM in incompatible ways.

**Comment by NickCao** [comment]
> I don't really know the NixOS ethos around such things but is it possible to repackage the official binaries from https://julialang.org/download? That should provide the best user experience from a Julia perspective, though perhaps not from a Nix perspective.

We already packaged the official binaries, but some do prefer to build everything from source.

**Comment by NickCao** [comment]
@ninjin I've switched to use the vendored copy of LLVM, any remaining concerns?

**Comment by vchuravy** [comment]
> You can see what patches Julia uses on its dependencies for a particular version by looking here:

That is not accurate for LLVM and LibUV. For Julia 1.8 we switched from maintaing a patchlist to maintaing a fork. So to see the patches we carry for LLVM 13: https://github.com/JuliaLang/llvm-project/compare/llvmorg-13.0.1...julia-13.0.1-3 (also see spack as a reference https://github.com/spack/spack/blob/5dc440ea92dbc1763f76c19b350c17355f96c5dc/var/spack/repos/builtin/packages/julia/package.py#L148)

Similarly the libuv patches are maintained here https://github.com/Julialang/libuv, but I am less familiar with those.

**Comment by 7c6f434c** [comment]
Testset «channels» seems to fail on aarch64-linux

This does break the build, though. Do we keep this as is or do we mark it as broken there?

**Comment by NickCao** [comment]
The tests are passing for me on aarch64:
```
julia> Test Summary: |     Pass  Broken     Total      Time
julia>   Overall     | 40348763  352659  40701422  14m09.2s
julia>     SUCCESS
```
I'm on `c3.large.arm64` from equinix metal if that matters.

**Comment by 7c6f434c** [comment]
I guess it might be subject to race conditions and slightly flaky… let's see

**Comment by staticfloat** [comment]
> That is not accurate for LLVM and LibUV. For Julia 1.8 we switched from maintaing a patchlist to maintaing a fork.

Ah, thank you for the correction Valentin.  That makes my previous comment incorrect, and we do in fact have significant patches to LLVM.

**Pull request merged**
