### PR TITLE
Add Softmaker Office and FreeOffice

### PR DESCRIPTION
**Pull request by danieldk**
###### Motivation for this change

Adds two office suites. FreeOffice is freeware, whereas SoftMaker Office requires a purchased license. This PR replaces #67105.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Review by romildo — APPROVED** [review]
Tested locally. Looks good to me.

**Comment by danieldk** [comment]
@romildo Thanks for merging this! Any chance that this could also be added to the release-19.09 branch, since there is no effect on other packages and it would be nice to have the additional office suite choices.

**Comment by romildo** [comment]
> @romildo Thanks for merging this! Any chance that this could also be added to the release-19.09 branch, since there is no effect on other packages and it would be nice to have the additional office suite choices.

@lheckemann What do you think about merging this to release-19.09?

**Comment by lheckemann** [comment]
Soft -1. Especially for packages without modules, getting them from the unstable channel should be fairly easy on 19.09 (e.g. `nix-env -f channel:nixos-unstable -iA freeoffice`). If there's a good reason why that won't work, you can convince me otherwise though :)

**Comment by danieldk** [comment]
Fair enough! I was a bit worried about the closure size (and thus leading to a lot of duplicated packages between 19.09 and unstable), but the closure of Softmaker/FreeOffice is actually quite lean (mostly  glibc, libstdc++, and X11 libs).

**Pull request merged**
