### PR TITLE
nixosTests.riak: port to python

### PR DESCRIPTION
**Pull request by Br1ght0ne**
###### Motivation for this change

#72828 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---
This change is [Reviewable](https://reviewable.io/reviews/nixos/nixpkgs/74124)

### CODE REVIEW

**Comment by filalex77** [comment]
@GrahamcOfBorg test riak

**Comment by Mic92** [comment]
riak is not yet in `all-tests.nix`. However it could be added. Than also `@GrahamcOfBorg test riak` would work.

**Comment by Mic92** [comment]
Might be also worth to bump riak: https://github.com/basho/riak/releases/tag/riak-2.9.0p5
The current version is marked as insecure.

**Review by tfc — APPROVED** [review]

**Comment by worldofpeace** [comment]
this makes me question things https://github.com/NixOS/nixpkgs/issues/33876#issuecomment-478304122. good to merge though, no point of adding to all-tests.nix because it can't even eval it

**Pull request merged**
