### PR TITLE
docbookrx: drop

### PR DESCRIPTION
**Pull request by 06kellyjac**
###### Motivation for this change

Drop docbookrx. It's had no maintainer since it was added #78389 and likely hasn't worked since the PR to fix it failing in hydra ahead of last release #147643

Also for some reason it shows up as a rebuilt package in some r-ryantm PRs #154426

~As part of dropping a package I'm guessing I'll need to write a short release note?~ Release note added

If there is interest in keeping it then there are a couple things that should be fixed:

- Add maintainer(s)
- The updated commit is [83d1d1235e3bb44506123eda337780a912581cd0](https://github.com/asciidoctor/docbookrx/commit/83d1d1235e3bb44506123eda337780a912581cd0) so the version should be corrected to `unstable-08-19`
- Fix it so it works

```
λ ./result/bin/docbookrx --help
Traceback (most recent call last):
	5: from ./result/bin/docbookrx:4:in `<main>'
	4: from /nix/store/f51yp2p28akc8677zlyrwrn35g5j3yg8-ruby-2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	3: from /nix/store/f51yp2p28akc8677zlyrwrn35g5j3yg8-ruby-2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'

# ... trimmed ...

	 2: from /nix/store/f51yp2p28akc8677zlyrwrn35g5j3yg8-ruby-2.7.5/lib/ruby/2.7.0/rubygems/specification.rb:1390:in `each'
	 1: from /nix/store/f51yp2p28akc8677zlyrwrn35g5j3yg8-ruby-2.7.5/lib/ruby/2.7.0/rubygems/specification.rb:1401:in `block in activate_dependencies'
/nix/store/f51yp2p28akc8677zlyrwrn35g5j3yg8-ruby-2.7.5/lib/ruby/2.7.0/rubygems/specification.rb:1404:in `rescue in block in activate_dependencies': Could not find 'mini_portile2' (~> 2.5.0) among 59 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/nix/store/47gmkipspq6b86dkk3b7h0mr1gj21xsb-docbookrx-env/lib/ruby/gems/2.7.0' at: /nix/store/47gmkipspq6b86dkk3b7h0mr1gj21xsb-docbookrx-env/lib/ruby/gems/2.7.0/specifications/nokogiri-1.11.7.gemspec, execute `gem env` for more information
```

cc: @adisbladis @manveru @arkivm

###### Things done

- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [X] (Package updates) Added a release notes entry if the change is major or breaking
  - [X] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 06kellyjac** [comment]
Result of `nixpkgs-review pr 154742` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by adisbladis** [comment]
I'm completely on board with dropping it.

**Comment by manveru** [comment]
No objections here.

**Comment by pennae** [comment]
removed packages should also have an alias for a bit that throws the removal reason when used, otherwise looks good

**Comment by 06kellyjac** [comment]
Thanks @pennae, added a throw alias

**Comment by pennae** [comment]
can't see it in the changes, did you forget to git add?

**Comment by 06kellyjac** [comment]
sorry, fixed

**Pull request merged**
