### PR TITLE
nextcloud-client: switch to libsecret and use it by default

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

This change makes it easier for users to setup the nextcloud client with
GNOME keyring support as discussed in the IRC[1][2].

Additionaly we now use `libsecret` instead of `libgnome-keyring` which
integrates better in a GNOME setup (libgnome-keyring defaults to the
Gnome2 library)[3].

[1] https://logs.nix.samueldr.com/nixos/2018-11-24#1745871;
[2] https://logs.nix.samueldr.com/nixos/2018-11-24#1746033;
[3] #38266

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after) (as stated in the commit message it has been discussed about this, we accept the increased closure size for usability)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Ma27** [comment]
cc @jtojnar

**Comment by jtojnar** [comment]
LGTM.

cc @alexeymuranov can you test this?

**Comment by M-Gregoire** [comment]
First of all, thank you for taking the time to work on the nextcloud client!

## The issues

I've tried using you branch for `nextcloud-client` and made a couple tests:
- Each time I restart nextcloud-client, I'm prompted with `You have been logged out of my@email.com as user me. Please login again`, with the following screen.
2018-12-01-205551_810x664_scrot

I have to enter my username/password then, it works.

- I also tried with an own cloud server (Not sure the compatibility with owncloud is very important...) and it work only right after setup. After the first restart, it asks for the username/password but redirect to the home page of owncloud wepapp instead of authenticating.
2018-12-01-191956_812x663_scrot

## The install

Just `nextcloud-client` installed from your branch without any override.

I still have `gnome-keyring` enabled but I don't believe this should be a problem:
```
  services.gnome3 = {
      gnome-keyring.enable = true;
      seahorse.enable = true;
  };
```
Is there anything else that should be installed ?

Note: The prompt is not the same as what I had when the keyring was improperly configured in the old version of `nextcloud-client`, I just had to type my password again, while in this case a get an iframe to get the token.

**Comment by alexeymuranov** [comment]
I havn't tried to test it yet, but here are a few observations about nextcloud-client version 2.5.0.  It seems to be quite different from version 2.3.3 and incompatible with it: upgrading-downgrading-upgrading seems to cause loosing connection configuration.  There are a [number of issue](https://github.com/nextcloud/desktop/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+2.5) reported about version 2.5.0, and on Ubuntu i experienced [file disappearance](https://github.com/nextcloud/desktop/issues/899) with it.

**Comment by Ma27** [comment]
@M-Gregoire thanks a lot for your detailed feedback! I'll look into it tomorrow.
@worldofpeace as you :+1:-ed @M-Gregoire's comment, did you have similar results?

@alexeymuranov I doubt that they actively support downgrades. Before I filed #50463 I tested this on my local Nextcloud setup and it managed to migrate my configurations and it found an existing sync in `~/Nextcloud`.
Regarding the issue with symlinks: the issue you've linked (nextcloud/desktop#250) states that symlinks in folder syncs aren't support officially right? But thanks a lot for the research, I'm a bit tired ATM, so I'll have a look at all the issues tomorrow :)

**Comment by alexeymuranov** [comment]
@Ma27, they are free to support or not support symlinks, but when files disappear, it is a bug IMO, and if symlinks are not supported, no changes to directory contents should be made, and otherwise synchronisation should be done properly.

**Comment by worldofpeace** [comment]
> @worldofpeace as you +1-ed @M-Gregoire's comment, did you have similar results?
@Ma27 Upon testing, within gnome3, I did notice the first issue @M-Gregoire pointed out.
Looks like it didn't unlock the keyring.

I've also tested kwallet and it operates correctly.

**Comment by Ma27** [comment]
> Each time I restart nextcloud-client, I'm prompted with You have been logged out of my@email.com as user me. Please login again, with the following screen.

hmm... I use my change already in my local setup and it works fine. Simply opening `nextcloud` and I'm logged in and it tries to sync changes.

> Not sure the compatibility with owncloud is very important

Not sure either. But please not that there's `pkgs.owncloud-client` as well. I can't test this though, I'm using Nextcloud only at work and privately.

> Is there anything else that should be installed ?

I don't think so. I figured that if the daemon is running, this should be fine.

> Note: The prompt is not the same as what I had when the keyring was improperly configured in the old version of nextcloud-client, I just had to type my password again, while in this case a get an iframe to get the token.

Which prompt do you mean? When I login in a fresh setup, the keyring asks me to unlock it with my master passphrase and then I'm logged in.

Btw the more I think about this: is it possible that you had 2.3 before testing this? I'm not sure, but this may be related to the config "migration" that happens when using the 2.5 client with 2.3 config.

> Upon testing, within gnome3, I did notice the first issue @M-Gregoire pointed out.
Looks like it didn't unlock the keyring.

Thanks for trying this out. Maybe this is gnome related (as said, I couldn't reproduce this yet), I'll try this out in a Gnome VM later this week ;)

**Comment by worldofpeace** [comment]
> Maybe this is gnome related (as said, I couldn't reproduce this yet), I'll try this out in a Gnome VM later this week ;)

The actual testing I did was within a gnome vm, forgot to mention that.

**Comment by Ma27** [comment]
> I'm unsure this is the best way to do it however. I've also noticed though seahorse that my keyring doesn't seems to unlock at startup so that might not by a nextcloud problem, even though It used to work fine.

I don't know enough about the keyring to help you here. Is this a known issue? Otherwise I'd recommend to you ask in `#nixos` (or similar), maybe there are people who successfully use Gnome keyring on a non-gnome setup :)

**Comment by M-Gregoire** [comment]
I've migrated to `kwallet` and everything worked perfectly on the first try so I'll probably stay with that!

**Comment by Ma27** [comment]
nixpkgs now uses nextcloud-client v2.5.1 since #52354, does this fix the issues for some of you here?

**Comment by Ma27** [comment]
cc @flokli do you have an idea how this could be related to `nextcloud-client`?

**Comment by flokli** [comment]
@M-Gregoire, @Ma27 I might not be the most qualified person, given I don't run a kde environment, but i3 with `desktopManager.gnome.enable = true`.

All I can tell is that every time I start nextcloud-client, a `kwalletd5` is spawned, too, and I don't get asked for a password.

**Comment by M-Gregoire** [comment]
@Ma27 @flokli This isn't a problem with nextcloud but with my wallet which didn't unlocked when my session started. I'll investigate to see if this is a nix problem or whether I did something wrong in my config.

I'm sorry for the false alarm!

**Comment by Ma27** [comment]
On 18.09 you need to override `nextcloud-client-unwrapped`. It seems as we didn't backport the latest commit which removed the wrapper (again).

I'll check tomorrow if there's a need to backport the most recent patches ok? :)

**Comment by caugner** [comment]
@Ma27 Sorry, to clarify: The latest build on 18.09 seems (i.e. a21dad5) to work, but when I switched to unstable (i.e. ead6899) it didn't work any more.

**Comment by Ma27** [comment]
Ah sorry, missed that. I don't use unstable, so I didn't notice, but nextcloud-client indeed breaks on startup on unstable. I have a theory what's causing this, I'll try to fix it :)

**Comment by Ma27** [comment]
can you please have a look at #54484, I can run `nextcloud-client` from master now.

**Pull request merged**
