### PR TITLE
python-packages numba: init at 0.21.0

### PR DESCRIPTION
**Pull request by FRidh**
This is an attempt at packaging numba, a Python JIT using LLVM.
Unfortunately llvmlite, the bindings, seem to segfault.

### CODE REVIEW

**Comment by FRidh** [comment]
Disabling static linking of libstdc++ did the track.

**Comment by FRidh** [comment]
Travis successfully built packages for Python 2.7, 3.3 and 3.4.

**Comment by FRidh** [comment]
@teh @domenkozar @garbas 
Can this be merged as it is now?

**Comment by teh** [comment]
I don't have merge permissions but I did test this and it works.

**Comment by garbas** [comment]
tested locally as well. will merge in a second!

**Pull request closed without merging**
