### PR TITLE
obs-studio: 28.0.3 -> 28.1.2, plugins fixes

### PR DESCRIPTION
**Pull request by fpletz**
###### Description of changes

Merging #194578 caused more issues than I initially anticipated. Upgrades obs-studio and fixes all plugins except obs-hyperion which is not yet compatible.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by miangraham** [comment]
Possible overlooked casualty:

Anyone using v27 on unstable had support for obs-websocket yesterday but doesn't today.

[pkgs/applications/video/obs-studio/plugins/obs-websocket.nix](https://github.com/NixOS/nixpkgs/pull/194578/files#diff-699f7b58cd66d5220fb4c43e702699c940aa02089d1183a50cfc60c7faeb6e12R31)

The plugin was removed (due to inclusion in v28) before the late decision to keep v27 around, and didn't get restored. Not sure how big a concern but seems kind to leave in place in some form for people using it.

**Comment by miangraham** [comment]
Also still missing: 22.11 release notes for the major version bump and plugin breakage, as [previously noted by raphaelr](https://github.com/NixOS/nixpkgs/pull/194578#issuecomment-1272291769).

**Comment by 06kellyjac** [comment]
@raphaelr any plans to submit these patches upstream?

**Comment by miangraham** [comment]
I'm planning to send an upstream PR with [Provide-runtime-plugin-destination-as-relative-path.patch](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/video/obs-studio/Provide-runtime-plugin-destination-as-relative-path.patch) once it's had a few days on master, since it's fixing general-case breakage for anyone building with a custom install prefix.

**Comment by 06kellyjac** [comment]
Cool

Personally I'm thinking about obs-multi-rtmp (the one I package). I'm happy to take the patch and submit a PR, with permission, but it feels better the author submit it :)

**Comment by fpletz** [comment]
> On second glance it looks like plugins are doing a hard cutover in general so maybe this doesn't matter. Anyone using much of anything on v27 will need to pull from a previous version of nixpkgs either way.

That was exactly what I was thinking when preparing this PR. I think we'll just remove v27 because maintaining plugins for both version is just too much.

**Review by SebTM — APPROVED** [review]

**Comment by fpletz** [comment]
> Also still missing: 22.11 release notes for the major version bump and plugin breakage, as [previously noted by raphaelr](https://github.com/NixOS/nixpkgs/pull/194578#issuecomment-1272291769).

I disagree, we are bumping packages all the time without mentioning it in the changelog. The commonly used plugins are working. obs-hyperion is probably not used by anyone and thus marked as broken. No need for release notes IMHO.

**Comment by SebTM** [comment]
> > Also still missing: 22.11 release notes for the major version bump and plugin breakage, as [previously noted by raphaelr](https://github.com/NixOS/nixpkgs/pull/194578#issuecomment-1272291769).
> 
> I disagree, we are bumping packages all the time without mentioning it in the changelog. The commonly used plugins are working. obs-hyperion is probably not used by anyone and thus marked as broken. No need for release notes IMHO.

See discussion #194578 here, I don't need both but some need 27 until their plugins are compatible with 28 as far as I understood?

**Comment by miangraham** [comment]
> No need for release notes IMHO

Okay, deferring to you on this one.

For the record, at the very least [the obs-websocket plugin removal](https://github.com/NixOS/nixpkgs/pull/194578/files#diff-699f7b58cd66d5220fb4c43e702699c940aa02089d1183a50cfc60c7faeb6e12R31) is a breaking change for anyone referencing it in 22.05. Easily remedied, but breaks working configs. It broke mine.

Your call on it meriting a mention or not. Cheers!

**Comment by fpletz** [comment]
> See discussion #194578 here, I don't need both but some need 27 until their plugins are compatible with 28 as far as I understood?

The plugins we have packaged and are not marked as broken are working. And that's the only thing we should care about. If we keep 27 we need to have two versions of most plugins which is insanity. People still using v27 should just use 22.05. :smirk: If I read correctly no one stepped up in the other PR that they've packages obs-plugins themselves.

**Comment by fpletz** [comment]
> For the record, at the very least [the obs-websocket plugin removal](https://github.com/NixOS/nixpkgs/pull/194578/files#diff-699f7b58cd66d5220fb4c43e702699c940aa02089d1183a50cfc60c7faeb6e12R31) is a breaking change for anyone referencing it in 22.05. Easily remedied, but breaks working configs. It broke mine.

Fair point. I've removed `obs-studio27` and added a changelog entry. Thanks.

**Comment by fpletz** [comment]
As there are currently some plugins broken on master since I merged #194578 prematurely, I'd like to merge this as soon as possible. Any other comments on the immediate changes here?

**Comment by miangraham** [comment]
Result of `nixpkgs-review pr 200639` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>obs-studio-plugins.obs-hyperion</li>
  </ul>
</details>
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>obs-studio</li>
    <li>obs-studio-plugins.looking-glass-obs</li>
    <li>obs-studio-plugins.obs-backgroundremoval</li>
    <li>obs-studio-plugins.obs-gstreamer</li>
    <li>obs-studio-plugins.obs-move-transition</li>
    <li>obs-studio-plugins.obs-multi-rtmp</li>
    <li>obs-studio-plugins.obs-nvfbc</li>
    <li>obs-studio-plugins.obs-pipewire-audio-capture</li>
    <li>obs-studio-plugins.obs-vkcapture</li>
    <li>obs-studio-plugins.wlrobs</li>
  </ul>
</details>

**Review by miangraham — APPROVED** [review]

**Comment by fpletz** [comment]
I've tested the plugins and their basic functionality. Not sure if everything works but they are being loaded correctly, can be configured and do stuff. ;) If you encounter issues please mention me in a follow-up PR or issue and we'll get that fixed ASAP.

**Comment by raphaelr** [comment]
@06kellyjac Feel free to upstream that patch, as it is right now though I doubt that this patch will work on non-Nix systems, their CMakeLists.txt contains too many `if(WIN32)`/`if(APPLE)` conditions. My CMake-fu isn't good enough to ensure it works on all of their supported systems.

**Pull request merged**
