### PR TITLE
arrow-cpp: 0.14.1 -> 0.15.0

### PR DESCRIPTION
**Pull request by tobim**
Release page: https://arrow.apache.org/release/0.15.0.html
Blog post: https://arrow.apache.org/blog/2019/10/06/0.15.0-release/

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @veprbl

### CODE REVIEW

**Comment by veprbl** [comment]
@GrahamcOfBorg build arrow-cpp python27Packages.pyarrow python37Packages.pyarrow
@GrahamcOfBorg build python27Packages.awkward python37Packages.awkward

**Review by jonringer — COMMENTED** [review]
regression in the pythonPackages.awkward package
```
[7 built (3 failed), 5 copied (4.2 MiB), 0.6 MiB DL]
error: build of '/nix/store/vlwq8acx8pmcjfih9shlgmqyc675dgkn-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/70584
7 package failed to build:
python27Packages.awkward python27Packages.uproot python27Packages.uproot-methods python37Packages.awkward python37Packages.ibis-framework python37Packages.uproot python37Packages.uproot-methods

5 package were build:
arrow-cpp python27Packages.google_cloud_bigquery python27Packages.pyarrow python37Packages.google_cloud_bigquery python37Packages.pyarrow
```

**Comment by veprbl** [comment]
@GrahamcOfBorg build arrow-cpp python27Packages.pyarrow python37Packages.pyarrow

(Issue with awkward array still needs to be resolved)

**Comment by tobim** [comment]
> regression in the pythonPackages.awkward package

Thanks for catching that, I'll have a look.

**Comment by tobim** [comment]
Created an issue upstream: https://github.com/scikit-hep/awkward-array/issues/203.
I suppose it should be ok to disable this test for the time being.

**Comment by jonringer** [comment]
We might want to wait for the awkward package to support arrow~=0.15.0

**Comment by tobim** [comment]
Consider the proposed fix in https://github.com/scikit-hep/awkward-array/pull/204.
We might wait for the next release of awkward, but I don't know how long we'll have to wait for that.

**Comment by jonringer** [comment]
could be a while depending on how the code is structured, and what assumptions were made about the arrow runtime

**Comment by veprbl** [comment]
@GrahamcOfBorg build arrow-cpp python27Packages.pyarrow python37Packages.pyarrow
@GrahamcOfBorg build python27Packages.awkward python37Packages.awkward

**Comment by tobim** [comment]
https://github.com/scikit-hep/awkward-array/releases/tag/0.12.13 containing a fix was already released a couple hours ago. Should I bump the pkg up and drop the commit that disables that one test?

**Comment by jonringer** [comment]
I would do the bump as part of this PR

**Comment by jonringer** [comment]
you will need to rebase on top of currrent master `git pull -r origin master`

**Comment by veprbl** [comment]
@GrahamcOfBorg build arrow-cpp python27Packages.pyarrow python37Packages.pyarrow
@GrahamcOfBorg build python27Packages.awkward python37Packages.awkward

**Review by veprbl — APPROVED** [review]
Passes nix-review on x86_64-linux
```
1 package failed to build:
python37Packages.ibis-framework

11 package were build:
arrow-cpp python27Packages.awkward python27Packages.google_cloud_bigquery python27Packages.pyarrow python27Packages.uproot python27Packages.uproot-methods python37Packages.awkward python37Packages.google_cloud_bigquery python37Packages.pyarrow python37Packages.uproot python37Packages.uproot-methods
```

**Pull request merged**
