### PR TITLE
{rmfakecloud, libbpf, pahole, bcc, bpftrace}: migrate to by-name

### PR DESCRIPTION
**Pull request by martinetd**
## Description of changes

Migrate all the packages I actively maintain to by-name, partly because it'll allow usage of the new merge bot, partly because I find by-name easier to work with and it looks like it's the direction nixpkgs is taking right now.

I wasn't quite sure what to do with bcc/bpftrace for the llvmPackages override, explicitly setting llvmPackages_16 in the package.nix could work but it feels cleaner to just keep them in the top level all-packages.nix, and others have been doing that so I've done the same.
I've got an update for llvmPackages_17 queued that I'll submit after this is closed (although honestly not sure if we want it before 24.05 branches -- gut feeling says we probably should because it's the default linux llvm version and anything not using the default takes up space if it's the only thing that needs it)

Since I'm far from the only maintainers on these, feel free to chip in if any of you prefer the current paths, I can drop any or all the patches.

This should come with 0 rebuilds.

(note libbpf 1.4.1 update in staging touches the same file, but since it's a pure rename git should figure it out when merging staging into master with no conflict)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by marcusramberg — APPROVED** [review]
Change lgtm.

**Comment by martinetd** [comment]
Ah, since there's no rebuild ofborg didn't cc maintainers; sorry should have done this in the pull request summary:
cc:
@mic92 (bcc)
@thoughpolice (bcc, bpftrace, libbpf)
@rvl (bpftrace)
@mfrw (bpftrace)
@vcunat (libbpf)
@sachagrunert (libbpf)
@ragnard (bcc)
@bosu (pahole)
@pacien (rmfakecloud)

**Comment by Mic92** [comment]
Looks good to me.

**Comment by vcunat** [comment]
Why not, I guess.  But some conflict did appear.

**Comment by martinetd** [comment]
> Why not, I guess. But some conflict did appear.

So I guess the git command does more behind the scenes magic than whatever github uses, both git merge and git rebase work fine locally :/
In that case I'll remove libbpf from this PR (because of the 1.4.2 update in staging that will also have a similar conflict); I'll re-open a PR just for libbpf later.

**Review by rvl — APPROVED** [review]

**Review by mfrw — APPROVED** [review]

**Pull request merged**
