### PR TITLE
hyprland: 0.6.1beta -> 0.8.1beta

### LINKED ISSUE #180323: Hyprland v0.22.0beta
###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: hyprland (only in unstable repos)

current version:0.6.1
desired version:0.22.0 beta

###### Notify maintainers

maintainers: vexerski

###### Note for maintainers

Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by wozeparrot**
###### Description of changes

Closes #180323

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by viperML** [comment]
Upstream is now building with meson instead of cmake

https://github.com/hyprwm/Hyprland/blob/main/nix/default.nix

**Comment by wozeparrot** [comment]
Isn't it still possible to build using cmake? I don't really see a benefit of moving to building with meson as the developer seems to prefer cmake over meson: https://github.com/hyprwm/Hyprland/pull/205#issuecomment-1153568693.

**Comment by viperML** [comment]
CI uses meson, and the Arch packages too

**Comment by wozeparrot** [comment]
The [hyprland wiki](https://github.com/hyprwm/Hyprland/wiki/Installation#cmake-recommended=) still recommends building with cmake.

**Comment by pinkcreeper100** [comment]
Just checking, is this pr dead?

**Comment by viperML** [comment]
The upstream flake is the de-facto way of getting HL

**Comment by fufexan** [comment]
@wozeparrot any plans to update this? I would like to help de-rot everything Hyprland in Nixpkgs.

**Comment by wozeparrot** [comment]
I feel like it would be better if we switch to building with meson. I feel like this can be closed in favour of a newer pr.

**Comment by fufexan** [comment]
> I feel like it would be better if we switch to building with meson. I feel like this can be closed in favour of a newer pr.

Sounds good. Do you want me to do it, or do you want to make it yourself?

**Comment by wozeparrot** [comment]
You can do it, I'm a bit busy these days.

**Comment by Mic92** [comment]
done https://github.com/NixOS/nixpkgs/pull/221617

**Pull request closed without merging**
