### PR TITLE
Gns3: fix build and crash

### PR DESCRIPTION
**Pull request by Atemu**
###### Motivation for this change

Builds broke in trunk-combined and it would crash on startup in my system

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by primeos — CHANGES_REQUESTED** [review]
Thanks for the PR. I had to push the changes manually, because:
- 9698a563cef237642830dc5633a956b676071817 is already in staging-next: 8c3e9313c924ac16595077fb75e5c6aad453dcb9
- 93deb26cb7a20612288a306f10122e461823296f: A modified version is now in staging-next: 06aec4278173e26e7871b5fa515f6ecff961d5bc
- b3687588fe44c193ffce4b4b02f1fc91f73764e9: It's probably best to wait with this until staging-next is merged into master.

Note: I only selected request changes so that no one merges this PR on accident, but no actions are required.

**Comment by Atemu** [comment]
Thanks!

It might be a good idea to merge the qt5Full patch despite the build still being broken as it's a very trivial fix and could then be cherry-picked to 20.03 whose (working) builds are also affected by the crash.

**Comment by primeos** [comment]
> It might be a good idea to merge the qt5Full patch despite the build still being broken as it's a very trivial fix and could then be cherry-picked to 20.03 whose (working) builds are also affected by the crash.

Yes, that would be nice. However, a problem is that GNS3 doesn't always crash (even when `qt5Full` isn't installed). I think there should be a better solution than adding `qt5Full` (approx. 1.5 GB), but we didn't find one so far. I'll try to have a closer look at this. Did you test/consider any alternatives?

**Comment by Atemu** [comment]
The reason it doesn't crash sometimes might be due to the missing QT5 dependency being accessible system-wide already because of another package the user installed.

IMO having to download 1.5GiB (though I only had to download a few MiB) is a lot better than having the application crash on you, needing to google a Nixpkgs issue with a solution and then having to install qt5Full manually.

If we find the actual dependency later, we can reduce the closure size again.

**Comment by primeos** [comment]
> The reason it doesn't crash sometimes might be due to the missing QT5 dependency being accessible system-wide already because of another package the user installed.

Yeah and in my case it probably only crashed when those dependencies where incompatible or something like that.

> IMO having to download 1.5GiB (though I only had to download a few MiB) is a lot better than having the application crash on you, needing to google a Nixpkgs issue with a solution and then having to install qt5Full manually.

Agreed, I'm mostly concerned that the whole packaging is a bit broken atm (`wrapQtAppsHook`, etc. would be better; see https://nixos.org/nixpkgs/manual/#sec-language-qt).

> If we find the actual dependency later, we can reduce the closure size again.

Yeah, that'd be best. But since I also lack time to investigate atm I pushed your commit for now: 0eaec4dee272d9dc67cee9599a41fcac1039845a (and backported in 6460602eec5ced5b9720f4d9fdb0dd717b89b4fd).
(I waited for the merge of staging as testing with `qt5Full` required too many rebuilds when I tried it and things where broken anyway.)

Closing this PR then as all changes are merged. Thanks!

**Pull request closed without merging**
