### PR TITLE
Made kernel config more customisable

### PR DESCRIPTION
**Pull request by spacekitteh**
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by spacekitteh** [comment]
so yeah, this is just adding "?" to a bunch of options, without changing any defaults

**Comment by joachifm** [comment]
Needs a rebase, at least. Would like to get some more feedback on this. cc @shlevy as well

**Comment by shlevy** [comment]
What's the goal of this exactly? I'm pretty sure the ? just means "if this kernel happens not to define this symbol, then don't error out", how is that more customizable?

**Comment by cleverca22** [comment]
i recently tried to compile usermode linux, and because nixos forces so many things to yes, i had to manually edit a fairly large chunk of the nixos config to make it even configure, this PR should solve a large chunk of that

**Comment by dezgeg** [comment]
This doesn't seem a good idea, since this now allows building a kernel which won't actually boot NixOS since the core userspace will freak out (e.g. if DEVTMPFS is missing). Would be better to group the options to "you really really need this" parts and optional parts and allow disabling some of the groups, or just have a way to totally ignore `common-config.nix` (maybe the `configFile` option to kernel already does that?).

**Pull request closed without merging**
