### PR TITLE
bisq2: init @ 2.1.0

### PR DESCRIPTION
**Pull request by emmanuelrosa**
## Description of changes

This PR adds [Bisq 2](https://bisq.wiki/Bisq_2), a decentralized bitcoin exchange that allows anyone to buy and sell bitcoin in exchange for national currencies or other cryptocurrencies.

Bisq 2 is the successor to what is now known as Bisq 1, however Bisq 2 hasn't reached feature parity with Bisq 1. Therefore, at this time, Bisq 2 doesn't replace Bisq 1, which is packaged in Nixpkgs as `bisq-desktop`.

### Verification

It is customary to verify the downloaded Bisq application by importing upstream's GPG key and verifying the signature of the downloaded package.

This Nix package includes build-time verification of the downloaded Debian package. This is to give users of this package a greater level of confirmation --compared to verification by the maintainer, (me)-- that the package has been signed by upstream. In short, if this package builds, then it's also verified.

Build-time verification is not a substitute for manually verifying the upstream package. It's a compromise.

### QR code scanning

Starting with Bisq2.1, there's a bundled "webcam app" which is used for webcam access to scan QR codes. This app does not work on NixOS because it relies on a lot of shared libraries (76 of them) which need to be patchelf'ed.

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emmanuelrosa** [comment]
I tried to address the by-name requirement, but I can't figure out what the problem is.

**Comment by emmanuelrosa** [comment]
In anticipation of migrating the `bisq-desktop` package to by-name, I named the attribute for Bisq 2 `bisq_2`, allowing me to use the attribute `bisq_1` for the current `bisq-desktop`.

However, the Bisq 2 executable is named `bisq2`. Therefore, I added the `mainProgram`  attribute so that `nix run` works.

**Comment by emmanuelrosa** [comment]
Rebased :)

**Comment by naturallaw777** [comment]
Thank you so much @emmanuelrosa! Bisq and Bisq 2 are the most important software of our time along with Bitcoin. You keeping it maintained here on NixOS is God's work!

**Comment by emmanuelrosa** [comment]
Thank you for the kind words, @naturallaw777 .

**Comment by emmanuelrosa** [comment]
I closed the PR because I'm sick and tired of wasting my time trying to please the code-checking gods.

`package.nix` is a perfectly valid Nix expression. Regardless, I formatted it twice with two different Nix formatters and the code was still rejected. This is not the first time I've had to battle with the Nixpkgs code checking bot. I write valid Nix code. I'm not trying to paint a Nix Picasso. 

Frankly, I've had enough.

**Pull request closed without merging**
