### PR TITLE
feedgnuplot: init at 1.49

### PR DESCRIPTION
**Pull request by mnacamura**
###### Motivation for this change

It is a nice tool for doing data-science things in command line.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg  build feedgnuplot

**Comment by mnacamura** [comment]
I tried to run the plot tests but they fail because they check if rendered outputs are precisely equal to those expected using gnuplot 4.6.4. gnuplot 5's rendering slightly changed. That's why the tests are skipped.
Should I disable tests even if they are skipped in upstream?

> Does feedgnuplot support the current nixpkgs version of gnuplot ?

Looking at the homepage and manual, they do not mention about gnuplot's version requirement. Actually it runs fine with gnuplot 5 in my environment.

**Comment by xeji** [comment]
> Should I disable tests even if they are skipped in upstream?

In this situation I would suggest to disable tests with a comment explaning why. This saves other people a little time to understand what's going on.

```
# tests require gnuplot 4.6.4 and are completely skipped with gnuplot 5
doCheck = false; 
```

**Comment by mnacamura** [comment]
Got it. Disabled tests.

**Comment by xeji** [comment]
Thank you.
@GrahamcOfBorg build feedgnuplot

**Pull request merged**
