### PR TITLE
python3Packages.nbval: disable failing tests

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Fix build (https://hydra.nixos.org/build/157270880) 

ZHF: #144627

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
This brings us to the broken `ipydatawidgets` package (https://hydra.nixos.org/build/157300912).

```bash
[...]
builder for '/nix/store/5d14zfiwd4v1qs6xlfkpbqjiljzd04a1-python3.8-ipydatawidgets-4.2.0.drv' failed with exit code 1; last 10 log lines:
  configuring
  no configure script, doing nothing
  building
  Executing setuptoolsBuildPhase
  Traceback (most recent call last):
    File "nix_run_setup", line 8, in <module>
      exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
    File "setup.py", line 35, in <module>
      from jupyter_packaging import (create_cmdclass, install_npm, ensure_targets,
  ModuleNotFoundError: No module named 'jupyter_packaging'
builder for '/nix/store/m1qdqhxnc0a0jac4wmpjah6a9xi61a08-python3.9-ipydatawidgets-4.2.0.drv' failed with exit code 1; last 10 log lines:
  configuring
  no configure script, doing nothing
  building
  Executing setuptoolsBuildPhase
  Traceback (most recent call last):
    File "/build/ipydatawidgets-4.2.0/nix_run_setup", line 8, in <module>
      exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
    File "setup.py", line 35, in <module>
      from jupyter_packaging import (create_cmdclass, install_npm, ensure_targets,
  ModuleNotFoundError: No module named 'jupyter_packaging'
cannot build derivation '/nix/store/p3d3fmhbsv9x0ffxx9k1nsar0wdmxksi-review-shell.drv': 2 dependencies couldn't be built
```

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 145267` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python38Packages.ipydatawidgets</li>
    <li>python39Packages.ipydatawidgets</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python38Packages.nbval</li>
    <li>python38Packages.onnx</li>
    <li>python39Packages.nbval</li>
    <li>python39Packages.onnx</li>
  </ul>
</details>

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 145267` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python38Packages.ipydatawidgets</li>
    <li>python39Packages.ipydatawidgets</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python38Packages.nbval</li>
    <li>python38Packages.onnx</li>
    <li>python39Packages.nbval</li>
    <li>python39Packages.onnx</li>
  </ul>
</details>

**Review by thiagokokada — APPROVED** [review]

**Comment by risicle** [comment]
(builds happily, macos 10.15, nixos x86_64 & aarch64)

**Pull request merged**
