### PR TITLE
erlang: main R23 -> R24

### PR DESCRIPTION
**Pull request by happysalada**
###### Motivation for this change

Proposing to use erlang 24 as the main. It came out recently, but I feel it would be better to give us time to surface problems if any before the next release. I feel in general people using unstable do know what they get into.

I'm sure this won't be a quick one and that things will break, so just opening this early.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
@NixOS/beam @dlesl
Any feedback is welcome, but no problem if you are busy.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 124587` at 266f3fe1 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/96f7af805172d348503c756bb36c0a7d">cl</a></li>
    <li><a href="https://gist.github.com/0eb1cb66912796e823cfb44a81f71445">elixir_1_8</a></li>
    <li><a href="https://gist.github.com/c7dd23d09e0b48a2fd546c6a77c6a610">wings</a></li>
  </ul>
</details>
<details>
  <summary>9 packages skipped due to time constraints:</summary>
  <ul>
    <li>erlang-ls</li>
    <li>erlang_javac</li>
    <li>erlang_odbc</li>
    <li>erlang_odbc_javac</li>
    <li>mercury</li>
    <li>nixos-install-tools</li>
    <li>notmuch-bower</li>
    <li>rabbitmq-server</li>
    <li>relxExe</li>
  </ul>
</details>
<details>
  <summary>12 packages built successfully:</summary>
  <ul>
    <li>ejabberd</li>
    <li>elixir (elixir_1_12)</li>
    <li>elixir_1_10</li>
    <li>elixir_1_11</li>
    <li>elixir_1_7</li>
    <li>elixir_1_9</li>
    <li>elixir_ls</li>
    <li>erlang</li>
    <li>erlang_nox</li>
    <li>rebar</li>
    <li>rebar3</li>
    <li>tsung</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by happysalada** [comment]
@dlesl sorry to bother you with this. I have a failure on `relxExe` that I'm not sure where it's coming from. If you have ideas on how to just 'fix' it (by fixing erlang version or something) I'm interested.

**Comment by yurrriq** [comment]
I'm hugely in favor of this. In case anyone missed it: https://blog.erlang.org/My-OTP-24-Highlights/

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 124587` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>relxExe</li>
  </ul>
</details>
<details>
  <summary>19 packages built:</summary>
  <ul>
    <li>elixir</li>
    <li>elixir_1_10</li>
    <li>elixir_1_11</li>
    <li>elixir_1_7</li>
    <li>elixir_1_9</li>
    <li>elixir_ls</li>
    <li>erlang</li>
    <li>erlang-ls</li>
    <li>erlangR23</li>
    <li>erlang_javac</li>
    <li>erlang_nox</li>
    <li>erlang_odbc</li>
    <li>erlang_odbc_javac</li>
    <li>mercury</li>
    <li>mix2nix</li>
    <li>rabbitmq-server</li>
    <li>rebar</li>
    <li>rebar3</li>
    <li>tsung</li>
  </ul>
</details>

**Comment by happysalada** [comment]
@Profpatsch I just left the elixir version on rabbitmq as is, there might be a way to upgrade elixir and erlang on it, but I'm not sure how smooth it will be. Let me know if you have strong interest in that.

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 124587` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>20 packages built:</summary>
  <ul>
    <li>elixir</li>
    <li>elixir_1_10</li>
    <li>elixir_1_11</li>
    <li>elixir_1_7</li>
    <li>elixir_1_9</li>
    <li>elixir_ls</li>
    <li>erlang</li>
    <li>erlang-ls</li>
    <li>erlangR23</li>
    <li>erlang_javac</li>
    <li>erlang_nox</li>
    <li>erlang_odbc</li>
    <li>erlang_odbc_javac</li>
    <li>mercury</li>
    <li>mix2nix</li>
    <li>rabbitmq-server</li>
    <li>rebar</li>
    <li>rebar3</li>
    <li>relxExe</li>
    <li>tsung</li>
  </ul>
</details>

**Comment by dlesl** [comment]
@happysalada I think this is fine for unstable. The other versions are still available under `beam.packages.erlangRXX`. Regarding `relxExe`, I think it should be removed, since relx is now intended to be used as a library by rebar3, and no longer produces a working standalone executable.

**Comment by happysalada** [comment]
@dlesl thanks for this! Removing it.

**Pull request merged**
