### PR TITLE
haskellPackages: update stackage and hackage

### PR DESCRIPTION
**Pull request by cdepillabout**
### This Merge

This PR is the regular merge of the `haskell-updates` branch into `master`.

This branch is being continually built and tested by hydra at https://hydra.nixos.org/jobset/nixpkgs/haskell-updates. You may be able to find an up-to-date Hydra build report at [cdepillabout/nix-haskell-updates-status](https://github.com/cdepillabout/nix-haskell-updates-status).

We roughly aim to merge these `haskell-updates` PRs at least once every two weeks. See the @NixOS/haskell [team calendar](https://cloud.maralorn.de/apps/calendar/p/H6migHmKX7xHoTFa) for who is currently in charge of this branch.

### haskellPackages Workflow Summary

Our workflow is currently described in [`pkgs/development/haskell-modules/HACKING.md`](https://github.com/NixOS/nixpkgs/blob/haskell-updates/pkgs/development/haskell-modules/HACKING.md).

The short version is this:
* We regularly update the Stackage and Hackage pins on `haskell-updates` (normally at the beginning of a merge window).
* The community fixes builds of Haskell packages on that branch.
* We aim at at least one merge of `haskell-updates` into `master` every two weeks.
* We only do the merge if the [`mergeable`](https://hydra.nixos.org/job/nixpkgs/haskell-updates/mergeable) job is succeeding on hydra.
* If a [`maintained`](https://hydra.nixos.org/job/nixpkgs/haskell-updates/maintained) package is still broken at the time of merge, we will only merge if the maintainer has been pinged 7 days in advance. (If you care about a Haskell package, become a maintainer!)

---

This is the follow-up to #169513. Come to [#haskell:nixos.org](https://matrix.to/#/#haskell:nixos.org) if you have any questions.

### CODE REVIEW

**Comment by expipiplus1** [comment]
Continuing from https://github.com/NixOS/nixpkgs/pull/169513#issuecomment-1111860187: will wait for pulseaudio to be fixed on master, @turion, I hope that's ok

**Comment by NorfairKing** [comment]
https://github.com/NixOS/nixpkgs/pull/171660 @cdepillabout Looks like I had a similar idea. I should have coordinated. How can I help?

**Comment by expipiplus1** [comment]
> Looks like I had a similar idea. I should have coordinated. How can I help?

We try and get at least one update every 2 weeks, this involves bumping the snapshot, and fixing anything in the `mergeable` set which breaks.

One good way to help would be to add yourself as a maintainer for some packages in `/pkgs/development/haskell-modules/configuration-hackage2nix/main.yaml`, that way if anything breaks on an update you'll be pinged and have an opportunity to fix it.

**Comment by cdepillabout** [comment]
@expipiplus1 We always (or at least almost always) immediately open a new PR after closing the current `haskell-updates` PR.  In fact we have a script that does it for us:

https://github.com/NixOS/nixpkgs/blob/46e402fc6e4c403f29d793bdda5d5ed4313bcf69/maintainers/scripts/haskell/merge-and-open-pr.sh

The next PR is https://github.com/NixOS/nixpkgs/pull/171763.

If you want to get this PR in as quick as possible, then basically we need help fixing packages that have become broken by this hackage bump (or possibly due to other changes in the rest of Nixpkgs).

You can find the Hydra status in https://hydra.nixos.org/jobset/nixpkgs/haskell-updates, and an easier-to-read build report at https://github.com/cdepillabout/nix-haskell-updates-status.

[At this very moment](https://github.com/cdepillabout/nix-haskell-updates-status/tree/e5c7cb1c0ad7f20e9b235db7679f694cb98c7d35), it appears there was some flakey failure on aarch64-linux, which makes the build report look like there are lots of failures, but if we restart the failed builds on Hydra, it is likely that most of these errors go away.  It is quite possible that there are few errors that need fixing.

**Pull request merged**
