### PR TITLE
vscode, vscodium: 1.46.1 -> 1.47.3

### PR DESCRIPTION
**Pull request by kuznero**
###### Motivation for this change

Upgrade packages.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by eadwu — APPROVED** [review]
Verified hashes.

**Comment by CheariX** [comment]
LGTM. Tested on NixOS.

**Comment by CheariX** [comment]
1.47.1 is out, including important security fixes.

**Comment by kuznero** [comment]
Microsoft had rapidly release 2 more versions.

**Comment by kuznero** [comment]
Ready to be merged

**Comment by kuznero** [comment]
Is there anything in Nixpkgs ecosystem that will allow to merge this simple version bumps granted all the ofborg checks pass? Or if possible, I would like to volunteer and merge it myself (if to be considered ok by responsible people). Otherwise, it is ready to be merged. cc @Mic92.

**Comment by CheariX** [comment]
I'm using this update now for more than a week. LGTM.

Btw. 1.47.3 has been released :)

**Comment by kuznero** [comment]
> I'm using this update now for more than a week. LGTM.
> 
> Btw. 1.47.3 has been released :)

Bumped it to 1.47.3 now ;) MS guys are fast these days ;)

**Pull request merged**
