### PR TITLE
pythonPackages.{pep,flake8}: undo changes from #19104

### PR DESCRIPTION
**Pull request by groxxda**
###### Motivation for this change

This change introduces breakage because `pycodestyle` and `pep8` are not API compatible and packages have not yet been updated.
The packages that are compatible should be converted to use `pycodestyle` on a per-package basis.

Introduced in #19104 
That PR also updates flake8 which breaks stuff.

This fixes  [virtmanager](http://hydra.nixos.org/build/41480713).

CC @mbld @Mic92 @garbas 
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

This reverts commit 0986a17edada11da1a910e2a015a4c57ad1279f2.

### CODE REVIEW

**Comment by FRidh** [comment]
yep that PR shouldn't have been merged.

**Comment by FRidh** [comment]
can you undo flake8 as well?

**Comment by groxxda** [comment]
@FRidh done
built `python35Packages.flake8{_3}`
Let me know if the package should have an other name. Also `flake8_3` lacks a maintainer as I'm not sure whether @garbas want's to maintain it.

**Comment by groxxda** [comment]
oh, looks like mccabe also needs reverting..

**Comment by groxxda** [comment]
i'll post a follow up pr in a minute

**Comment by FRidh** [comment]
@groxxda done in 25dcdc58d05a3e9421116a8bedd3a47815faf1f4

**Comment by groxxda** [comment]
@FRidh  sorry I somehow forgot to file the pr after hours of rebuilding :disappointed:

**Pull request merged**
