### PR TITLE
buck2: init at unstable-2023-05-17

### LINKED ISSUE #226677: Package request: buck2
**Project description**

> "Buck2, a large scale, fast, reliable, and extensible build tool developed and used by Meta. Buck2 supports a variety of languages on many platforms.
>
> Buck2's core is written in [Rust](https://www.rust-lang.org/). [Starlark](https://github.com/bazelbuild/starlark), which is a deterministic, immutable dialect of Python, is used to extend the Buck2 build system, enabling Buck2 to be language-agnostic. With Starlark, users can define their own custom rules.
>
> Buck2 leverages the Bazel spec of [Remote Build Execution](https://bazel.build/remote/rbe) as the primary means of parallelization and caching, which increases the importance of idempotency (no matter how many times an operation is performed, it yields the same result) and hermeticity (code is sealed off from the world), giving the right results, reliably.
>
> Buck2 multi-language support includes C++, Python, Java, Go, Rust, Erlang, OCaml, and more."
>
> -- https://buck2.build/docs/

**Metadata**

* homepage URL: https://buck2.build/
* source URL: https://github.com/facebook/buck2
* license: MIT and Apache 2.0
* platforms: linux and darwin (might also work on other platforms)

**Additional Notes**

It's worth noting that `buck2` appears to be updating off the `latest` branch with a re-created `git` tag upon each "release". It may be the case that `buck2` doesn't make sense to be in `nixpkgs` right now, but perhaps folks have ideas on what it could look like to update `buck2` automatically.

EDIT (17 Apr 2023): I suspect the package will go in `pkgs/development/tools/build-managers`. It's also worth adding the following note from the source URL's `README`...

> "Build uses prebuilt `protoc` binary from [protoc-bin-vendored](https://crates.io/crates/protoc-bin-vendored) crate. If these binaries to do not work on your machine (for example, when building for NixOS), path to protoc binary and protobuf include path can be specified via `BUCK2_BUILD_PROTOC` and `BUCK2_BUILD_PROTOC_INCLUDE` environment variables."

### PR DESCRIPTION
**Pull request by nickgerace**
###### Description of changes

This PR adds [buck2](https://github.com/facebook/buck2) with the ability to auto update. A big thanks to @thoughtpolice for the [inspiration on where to start](https://github.com/thoughtpolice/buck2-nix) as well as from the folks at @DeterminateSystems on advice on how to handle the difficult bits here.

> "A large-scale build tool. The successor to Buck."
> -- [https://buck2.build](https://buck2.build/)

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

###### Additional checks

- [x] Ran `nix-build -A buck2` to produce the artifacts tested
- [x] Ran `pkgs/development/tools/build-managers/buck2/update.sh` manually with varying changes to `default.nix` upon each run to simulate update scenarios

###### Additional notes

- Fixes #226677
- Related Issue mozilla/nixpkgs-mozilla#304
- Related PR mozilla/nixpkgs-mozilla#309

###### Potential Issues

- ~~Needed to pass `--allow ifd` for `nixpkgs-review pr` to be successful~~ (EDIT: fixed)
- Did not add anything to the release notes as `buck2` is not a service

### CODE REVIEW

**Review by figsoda — CHANGES_REQUESTED** [review]
Using rust nightly from external sources is not allowed due to the dependency on import-from-derivation

Instead, you can try adding `RUSTC_BOOTSTRAP = true;`, that can sometimes get around the nightly requirement using stable rust.

Consider using `nix-update-script` for `passthru.updateScript`, it will also handle updating `outputHashes`.

The bugs in `nixpkgs-mozilla` might be fixed in [fenix](https://github.com/nix-community/fenix), so if you wan to package buck2 out of tree, this can be an option.

**Comment by nickgerace** [comment]
Thank you @figsoda for the notes! I have questions and will go one by one.

> Using rust nightly from external sources is not allowed due to the dependency on import-from-derivation

Ah that explains why I needed `--allow ifd` for `nixpkgs-review pr`.

> Instead, you can try adding `RUSTC_BOOTSTRAP = true;`, that can sometimes get around the nightly requirement using stable rust.

I'll try it, but am a bit concerned since upstream `buck2` authors use a specific nightly toolchain pinned to the date. Is there an alternative to that, or is it impossible?

> Consider using `nix-update-script` for `passthru.updateScript`, it will also handle updating `outputHashes`.

Noted! That's great! Since there are [no docs](https://github.com/NixOS/nixpkgs/issues/216321) for it, is there a method you recommend for how to use and configure it?

> The bugs in `nixpkgs-mozilla` might be fixed in [fenix](https://github.com/nix-community/fenix), so if you wan to package buck2 out of tree, this can be an option.The bugs in nixpkgs-mozilla might be fixed in [fenix](https://github.com/nix-community/fenix), so if you wan to package buck2 out of tree, this can be an option.

I'm a bit confused. I should only pursue using fenix if I want to package buck2 outside of tree? Does "tree" refer to `nixpkgs`? If so, we already have a flake that builds buck2 and could just use cacheix, but I'd like to specifically include it in `nixpkgs`, if possible.

**Comment by figsoda** [comment]
> but am a bit concerned since upstream buck2 authors use a specific nightly toolchain pinned to the date

This is probably because there can potentially be breaking changes between nightly versions, not that it only works with one specific date. Though, do note that `RUSTC_BOOTSTRAP` is very hacky and only works sometimes.

> Is there an alternative to that, or is it impossible?

The only alternative is to patch buck2 to be compatible with stable rust, which is probably not the easiest job.

> is there a method you recommend for how to use and configure it?

You can add this right above `meta`

```nix

passthru.updateScript = nix-update-script { };

```

> I should only pursue using fenix if I want to package buck2 outside of tree? Does "tree" refer to nixpkgs?

Yes & Yes. Fenix is an alternative to mozilla's rust overlay and will also require IFD (which isn't allowed) to be used in nixpkgs.

**Comment by thoughtpolice** [comment]
The use of `RUSTC_BOOTSTRAP` has always made me uneasy frankly. I don't like using it. Also, buck2 has surfaced some ICEs in various nightly versions, so the version chosen in the `rust-toolchain` file is not for no reason, I think. That's not a hard rejection out of hand, but we should also open an issue upstream about the possibility of targeting a stable compiler release first. If things start breaking because it's fragile or a new stable release introduces some change that causes a failure, that would be unfortunate.

What might be better in the very short term is to instead just contribute a package to the upstream `flake.nix` file. Right now, it only provides a `devShell` so you can compile a buck2 binary. But it should also provide a buck2 package itself. Then, users of flakes can simply add it as a dependency for their own projects.

Eventually we'll have to bite the bullet on this package though, because if something else that we want to package starts requiring `buck2` itself, there's no way around it.

**Review by thoughtpolice — CHANGES_REQUESTED** [review]
As of right now, I've found that the core buck2 codebase also *rejects* any non-sanctioned compiler, during compile time; see the following `build.rs` file: https://github.com/facebook/buck2/blob/c038ed271cca720bee43374e0c3883c59a625728/app/buck2_core/build.rs#L14-L55

I'm afraid going against the grain here by patching this out seems to clearly go against the explicit wishes of the dev team, and I don't think that's a place we want to be; so for now I'm going to tag this PR as being on hold and requiring changes.

I'll look into adding a package to the upstream flake instead as a short term mitigation for flake users, at least. I have also opened an issue to track using the stable rust compiler, which will alleviate these issues upstream; see facebook/buck2#265

**Comment by nickgerace** [comment]
Thank you @figsoda. I appreciate the replies and agree @thoughtpolice that using the toolchain that buck2 authors require is a requirement. I'll look into what you've shared.

Speaking of which, hello @thoughtpolice! Thanks again for the work you've done with [buck2-nix](https://github.com/thoughtpolice/buck2-nix). I don't want to stray too far off topic because this is nixpkgs PR, so I may follow up in your repository or the [facebook/buck2](https://github.com/facebook/buck2) repository as needed.

Agreed on the use of `RUSTC_BOOTSTRAP` and the requirement of the toolchain. I think shifting to contributing to the upstream flake is a good idea. The nightly hack is not only undesired, but also untenable. I think we are all aligned here.

I'll follow your tracking issue and can also help with the flake too. Thanks for posting that! 

_As an aside, [reindeer](https://github.com/facebookincubator/reindeer) is built on stable Rust, so I will likely post a similar PR to this one here. I believe we will not run into the same issue there._

As a result of all of this discussion, I am going to close this PR. I think a draft would drift quickly due to both buck2 and nix/nixpkgs itself moving quickly, and since closed PRs are indexable, we should be good should/once the opportunity arises to add buck2. Thank you both!

**Pull request closed without merging**
