### PR TITLE
super-productivity: 9.0.5 -> 10.0.2

### PR DESCRIPTION
**Pull request by Masrkai**
## Description of changes

I messed up before because it's my first time contributing however i think i got it right this time T_T

Github release is 10.0.2 as of 7:26 9/9/2024 (GMT+3)
https://github.com/johannesjo/super-productivity/releases/tag/v10.0.2

Comparison:
https://github.com/johannesjo/super-productivity/compare/v9.0.5...v10.0.2

Home Page:
https://super-productivity.com/

## Things done
Updated the package version and hash and replaced the older sha256

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Mindavi — CHANGES_REQUESTED** [review]
Diff LGTM but please update the commit message according to the contribution guidelines.

**Comment by Masrkai** [comment]
> Diff LGTM but please update the commit message according to the contribution guidelines.

can you please reference me what I should exactly do since i am new to doing this ? @Mindavi

**Comment by Mindavi** [comment]
Change the commit message to be the same as the title of this pull request.

- `git commit --amend`
- edit the commit message to be equal to this PR title
- `git push --force-with-lease`


Rederence: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions

**Comment by Masrkai** [comment]
@Mindavi i did as you advised but what happened why did it request everyone review like that ?

**Comment by K900** [comment]
Please don't comment on this PR anymore, as everyone who was review requested will get messages.

**Pull request closed without merging**
