### PR TITLE
wine{Unstable,Staging}: 7.4 -> 7.8; winetricks: 20210825 -> 20220411

### PR DESCRIPTION
**Pull request by SFrijters**
###### Description of changes

Three upstream version bumps.
However, it seems that even wine 7.4 doesn't build on master anymore for me.
This is to be investigated.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SFrijters** [comment]
Still trying to find out how/when/why we lost the ability to parallel build...

**Comment by bendlas** [comment]
> Still trying to find out how/when/why we lost the ability to parallel build...

how does this manifest?

**Comment by SFrijters** [comment]
My NixOS config uses 12 cores by default, and since I tried to start the PR I'm getting errors like 
```
/nix/store/8x3b9g3hjyw1fdkfry01yhp8lkccnfi7-x86_64-w64-mingw32-binutils-2.38/bin/x86_64-w64-mingw32-dlltool: dlls/iphlpapi/libiphlpapi.delay.a: error reading iphlpapi_dll_s00001.o: No such file or directory
winebuild: /nix/store/8x3b9g3hjyw1fdkfry01yhp8lkccnfi7-x86_64-w64-mingw32-binutils-2.38/bin/x86_64-w64-mingw32-dlltool failed with status 1
make: *** [Makefile:96346: dlls/iphlpapi/libiphlpapi.delay.a] Error 1
make: *** Waiting for unfinished jobs....
/nix/store/8x3b9g3hjyw1fdkfry01yhp8lkccnfi7-x86_64-w64-mingw32-binutils-2.38/bin/x86_64-w64-mingw32-dlltool: dlls/iphlpapi/libiphlpapi.cross.a: error reading iphlpapi_dll_t.o: No such file or directory
winebuild: /nix/store/8x3b9g3hjyw1fdkfry01yhp8lkccnfi7-x86_64-w64-mingw32-binutils-2.38/bin/x86_64-w64-mingw32-dlltool failed with status 1
make: *** [Makefile:96346: dlls/iphlpapi/libiphlpapi.cross.a] Error 1
```

When I build wine 7.4 off its original commit dd6c7096d629d9c6814c6980180254d3336a9a3b I see no such problem (35619ce1e513fa044b341f62a633deaa458eed06 is still okay as well). But on current master (without this PR) I do get it. It's been a huge pain trying to bisect the problem because of the long compile times.

Setting `enableParallelBuilding = false`; makes it go away, but that will make rebuilding the wine variants take way too much time.

**Comment by Philipp-M** [comment]
Just tested this and it's working fine for me (better indeed than 7.4 since a few of my applications stopped working with it).

I would suggest merging this, since it's better to have a version that compiles slowly than not at all.

And investigate the parallel building issue separately.

**Comment by SFrijters** [comment]
I can remove the draft status if people want, but I probably won't run the full nixpkgs-review on it since that will now trigger so many serialized builds...

**Comment by SFrijters** [comment]
Would be nice to get https://github.com/NixOS/nixpkgs/pull/172617 first, then we can probably keep parallel builds enabled.

**Comment by SFrijters** [comment]
Result of `nixpkgs-review pr 170943` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>25 packages built:</summary>
  <ul>
    <li>grapejuice</li>
    <li>lutris</li>
    <li>lutris-free</li>
    <li>lutris-unwrapped</li>
    <li>pipelight</li>
    <li>protontricks</li>
    <li>winbox</li>
    <li>wine-staging (winePackages.stagingFull)</li>
    <li>wine-wayland (winePackages.waylandFull)</li>
    <li>wine64Packages.staging</li>
    <li>wine64Packages.stagingFull</li>
    <li>wine64Packages.unstable</li>
    <li>wine64Packages.unstableFull</li>
    <li>wine64Packages.waylandFull</li>
    <li>winePackages.staging</li>
    <li>winePackages.unstable</li>
    <li>winePackages.unstableFull</li>
    <li>wineWowPackages.staging</li>
    <li>wineWowPackages.stagingFull</li>
    <li>wineWowPackages.unstable</li>
    <li>wineWowPackages.unstableFull</li>
    <li>wineWowPackages.waylandFull</li>
    <li>winetricks</li>
    <li>yabridge</li>
    <li>yabridgectl</li>
  </ul>
</details>

**Comment by Philipp-M** [comment]
I'd like to test/review it as is, but honestly I don't know how to reduce the count of build-cores.

I tried something like:
```
NIX_BUILD_CORES=1 nix build -j 1 .#wineWowPackages.staging
```

But that's not working...

Regardless of that, I would suggest setting `enableParallelBuilding = false` so that no-one else runs into this issue, and set it back to true in this PR: #172617

**Comment by SFrijters** [comment]
I took out the big hammer and set my `nix.settings.cores` to 2 on my NixOS system for the occasion.

Since hydra was still happy building wine until now I figured I'd leave the `enableParallelBuilding` alone because the build should end up in the binary cache soon, but I can go either way.

**Review by Philipp-M — APPROVED** [review]
LGTM

**Pull request merged**
