### PR TITLE
Fix pythonPackages.moviepy

### PR DESCRIPTION
**Pull request by JohnAZoidberg**
###### Motivation for this change
The package was updated in #55757 but the list of dependencies was not.
Now it build again and I can import it in python3.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by markuskowa** [comment]
@GrahamcOfBorg build python37Packages.moviepy
@GrahamcOfBorg build python27Packages.moviepy

**Comment by markuskowa** [comment]
Needs backport to 19.03

**Comment by markuskowa** [comment]
It looks like python-2.7 is not supported anymore. Can you please mark it broken for python-2.7?

**Comment by JohnAZoidberg** [comment]
> It looks like python-2.7 is not supported anymore. Can you please mark it broken for python-2.7?

Thanks! Wasn't aware we had the capability to do that :)

**Pull request merged**
