### PR TITLE
Remove useless dont_clobber_environment.patch for Godot

### PR DESCRIPTION
**Pull request by NilsIrl**
###### Motivation for this change
* It will break and prevent building
* If this patch is really necessary it should be done upstream

Partly reverts #34971.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @Twey

### CODE REVIEW

**Comment by Twey** [comment]
The patch exists to unbreak building. This effectively prevents Godot from adding a bunch of global paths to the environment, which breaks non-sandboxed builds.

Not in disagreement that it should be upstreamed, though!

**Comment by NilsIrl** [comment]
How does it do it though?

I'm no python expert but from what I can tell the patch effectively does nothing, it just changes the way environment variables are passed through.

The patch adds env vars in a loop when before it does it sequentially.

**Comment by Twey** [comment]
The looping thing is a trivial refactor… the important part is that the patch assigns where the original appends. `Environment` comes with a `PATH` and `PKG_CONFIG_PATH` that include global paths, so using an append here effectively prepends global paths to the user's path before proceeding with the build. This patch ensures that the user's paths are passed through verbatim.

I'm curious as to how you think it breaks the build. This package has of course passed tests!

**Comment by NilsIrl** [comment]
> I'm curious as to why you think it breaks the build. This package has of course passed tests!

What I mean by "break", is that like any patch, if the original file is changed upstream, the patch might fail to be applied.

**Comment by NilsIrl** [comment]
Actually the patch does fail which is the reason I did this PR. Sorry, I did this 2 months ago, I totally forgot about it:

```
$ patchPhase
applying patch /nix/store/apfyhds62va8l0ddabdrzfhflfvhjk0a-pkg_config_additions.patch
patching file platform/x11/detect.py
Hunk #1 succeeded at 201 with fuzz 2 (offset 26 lines).
Hunk #2 succeeded at 295 with fuzz 2 (offset 26 lines).
applying patch /nix/store/ja5b801bk42vyrdydv92hh6bcg48y5y0-dont_clobber_environment.patch
patching file SConstruct
Hunk #1 FAILED at 63.
1 out of 1 hunk FAILED -- saving rejects to file SConstruct.rej
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   platform/x11/detect.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	SConstruct.orig
	SConstruct.rej
	platform/x11/detect.py.orig

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by SuperSandro2000** [comment]
Closing due to inactivity from author.

**Pull request closed without merging**
