### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
Ruby failure https://hydra.nixos.org/build/120948627
cc @manveru @vrthra

**Comment by manveru** [comment]
From a quick look, it seems that the `bison` version bump causes the Ruby issues. We should probably keep the previous version in nixpkgs alongside for now...

**Comment by FRidh** [comment]
That's kind of a last resort solution. Surely upstream must have seen the same issue?

**Comment by FRidh** [comment]
I don't like keeping an older version around but at least it unblocks staging-next 458b2cb7d67561c796c6f0660a97eea9b685fc65

**Comment by samueldr** [comment]
`autogen` won't cross-compile in staging-next. I am currently looking into trying to bisect the issue.

`nix-build -A pkgsCross.aarch64-multiplatform.autogen`

```
checking for GUILE... yes
./configure: line 16698: pkg-config: command not found
awk: fatal: cannot open file `/libguile/version.h' for reading: No such file or directory
configure: error: in `/build/autogen-5.18.12':
configure: error: cannot determine Guile version
See `config.log' for more details
builder for '/nix/store/hm1l7227ps3rzk8bp6i1mygcs3fshwj8-autogen-5.18.12-aarch64-unknown-linux-gnu.drv' failed with exit code 1
error: build of '/nix/store/hm1l7227ps3rzk8bp6i1mygcs3fshwj8-autogen-5.18.12-aarch64-unknown-linux-gnu.drv' on 'ssh://samuel@duffman' failed: builder for '/nix/store/hm1l7227ps3rzk8bp6i1mygcs3fshwj8-autogen-5.18.12-aarch64-unknown-linux-gnu.drv' failed with exit code 1
builder for '/nix/store/hm1l7227ps3rzk8bp6i1mygcs3fshwj8-autogen-5.18.12-aarch64-unknown-linux-gnu.drv' failed with exit code 1
error: build of '/nix/store/hm1l7227ps3rzk8bp6i1mygcs3fshwj8-autogen-5.18.12-aarch64-unknown-linux-gnu.drv' failed
Command exited with non-zero status 1
```

→ https://gist.github.com/6e407c41f925eb6ecb691f26e49bbcd9

**Comment by samueldr** [comment]
I have tracked this to c71ab32a678  #87705 cc @Ericson2314

**Review by samueldr — DISMISSED** [review]
Requesting changes for visibility. In its current state, this branch breaks (at least) the build of autogen.

**Comment by Ericson2314** [comment]
Checking out the failure.

**Comment by Ericson2314** [comment]
https://savannah.gnu.org/support/?109050 nice to see the issue has been reported

**Comment by samueldr** [comment]
:scream: in *2016*!

Does that point to a possible solution?

**Comment by vcunat** [comment]
Updating autogen and applying patches from Debian fixed that build for me (743a8a80b) &ndash; maybe thanks to using newer guile as dependency.  So... shall we hope that the minor update doesn't make things worse and push it to staging-next?

**Comment by vcunat** [comment]
If so, I would also add 9475ec86.

**Comment by FRidh** [comment]
Could we not deliver staging-next as in, and go for the next cycle with the fix? It means cross is broken temporarily but it would save another rebuild.

**Comment by vcunat** [comment]
For me _personally_, a few channel updates with broken cross certainly won't cause issues, but I don't know how it's generally in the community.

**Comment by FRidh** [comment]
mplayer now fails with
```
/nix/store/klg7ribk7f834yb0hn1fxs6653wzlncb-binutils-2.31.1/bin/ld: sub/font_load_ft.o: undefined reference to symbol 'FT_Get_Glyph'
/nix/store/klg7ribk7f834yb0hn1fxs6653wzlncb-binutils-2.31.1/bin/ld: /nix/store/xvr907jajxllac8lygj6w0bkvwi84nfp-freetype-2.10.2/lib/libfreetype.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:747: mplayer] Error 1
builder for '/nix/store/8wq1r408xl9wynyn4gc2b1kgvg52i3i7-mplayer-1.4.drv' failed with exit code 2
```
https://hydra.nixos.org/build/121519361

**Comment by vcunat** [comment]
That sounds like some pkg-config as well
```
sed: -e expression #1, char 0: no previous regular expression
sed: -e expression #1, char 0: no previous regular expression
Package freetype2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `freetype2.pc'
to the PKG_CONFIG_PATH environment variable
No package 'freetype2' found
```

**Comment by Ericson2314** [comment]
I was still looking at autogen---the version we had *already* contained the fix, yet `configure` didn't seem to reflect it, so I was investingating what `autoreconfHook` would do.

**Comment by Ericson2314** [comment]
Ah, so https://git.savannah.gnu.org/cgit/autogen.git/commit/?h=5cbe233387d7f7b36752736338d1cd4f71287daa wasn't enough, because there were scripts producing autoconf :scream: in our version, and one of those `PKG_CONFIG` from the patch was evaluated too early. I'll make a manual patch until we bump the versions.

**Comment by vcunat** [comment]
Great, cross-compiles for me now.  I hurried Hydra to build the commit.

Unless you object I'll just aim directly for staging with that autogen update.

**Comment by samueldr** [comment]
I'm not sure what's the frequency of staging-next being merged into master, but it does mean that the mobile nixos jobset will fail for that whole duration.

Not ideal, though I know [being tier 3](https://github.com/NixOS/rfcs/blob/master/rfcs/0046-platform-support-tiers.md#appendix-a-non-normative-description-of-platforms-in-november-2019) it's okay if it fails.

My main concern with accepting regressions in master for cross-compilation is that they sometimes end up hard to bisect. Having multiple staging-next rounds to bisect through is way harder than only one.

(Though for this particular round, the point is likely moot, I'll test with the added fix soon.)

**Comment by Ericson2314** [comment]
@samueldr what other packages are broken?

I dunno what portion of the breakage is caused by me, but I do feel bad when people bisect an error which I can tell at a glance (like the `pkg-config`) so do feel free to ping me with issues before bisecting. I never got good at monitoring Hydra, but I do see GitHub pings pretty quick.

**Comment by vcunat** [comment]
To be clear, `autogen` cross seems fixed in current `staging-next`.

**Comment by samueldr** [comment]
@Ericson2314 that was a general sentiment, this round there was a difficulties bisecting because of breakage you already fixed "internal" to that round. Though that's not really much.

I'm more worried about a situation where, let's say no one catches issues for a month or two, it can become harder to untangle.

(Still haven't validated whether there are issues elsewhere, will be doing it soon, once what's burning my CPU time is over.)

**Comment by samueldr** [comment]
Looking into it, there are issues still, but they are leafy, and less problematic, I guess they can be handled on then next cycle.

`perlNetDBus` and `bcache-tools`:

 * `pkgsCross.aarch64-multiplatform.perlPackages.NetDBus`

```
cannot run pkg-config to check dbus version at Makefile.PL line 8.
```

 * `pkgsCross.aarch64-multiplatform.bcache-tools`

```
/nix/store/n313xks5ym0s0a5v8a5285rmnmvy6ms9-bash-4.4-p23/bin/bash: pkg-config: command not found
```

Both issues seem to be related to the pkg-config change. I think the change may require some good documentation work as I fear many upstream packages are doing *maybe the wrong thing*. I say documentation, I mean it could be upstream pkg-config documentation explaining it, it even would be better, but the goal is to have some solid piece of evidence to point to when providing upstream patches.

**Comment by jtojnar** [comment]
We could make page like https://github.com/jtojnar/cmake-snips#please-fix-your-cmake-builds for cross-compilation.

**Comment by vcunat** [comment]
With this `gitMinimal` fix we're running into a bit of hydra issue.  When you fix a fixed-output derivation, the output remains the same... therefore Hydra reuses the old build instead of creating a new one, and restarting that build naturally uses the first derivation that created it.

**Comment by vcunat** [comment]
Builds of all kernels except default 5.4 are broken by this staging-next iteration: https://github.com/NixOS/nixpkgs/pull/88946#pullrequestreview-426896106

**Pull request merged**
