### PR TITLE
budgie{Packages,Plugins}: refactor & modernize

### PR DESCRIPTION
**Pull request by getchoo**
## Description of changes

The biggest changes here include

- Renaming `budgie` to `budgiePackages`
  - Puts us more inline with other scopes such as `kdePackages` and `python3Packages`
- Moving from `lib.makeScope` to `pkgs.makeScopeWithSplicing'`
  - Reduce boilerplate in our expressions and allows for a better experience in cross compiling
- (More) package tests have been added
  - Mainly via `testers.testVersion` and `testers.hasPkgConfigModules` where applicable
- `passthru.updateScript` tree-wide
  - This and the above should give us an easier time in maintiaing these packages

I know some of this may be fairly subjective (specifically the scope rename) so feel free to request for some things to be dropped. Most of this is based on [pkgs/kde](https://github.com/NixOS/nixpkgs/tree/3f35c2c40fbadf5cba8b45bbeec19879e144262c/pkgs/kde), which I just found to be quite well structured

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 test built:</summary>
  <ul>
    <li>nixosTests.budgie</li>
  </ul>
</details>

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by getchoo** [comment]
cc @bobby285271 as a member of the budgie team

**Comment by bobby285271** [comment]
Ah, I not sure if I can properly review this, I agree some of these are quite subjective. There is ongoing https://github.com/NixOS/nixpkgs/pull/319659#issuecomment-2209447523 at the same time though, how do you think of by-name here?

**Comment by getchoo** [comment]
> There is ongoing https://github.com/NixOS/nixpkgs/pull/319659#issuecomment-2209447523 at the same time though, how do you think of by-name here?

I had actually seen this recently, but thought keeping some of the core packages like gnome-shell under that scope was intentional. If that's not the case and it's encouraged we move everything we can to by-name, then I would love to adopt that here.

CC @jtojnar for any clarification/guidance here

**Comment by jtojnar** [comment]
I intend to move `gnome-shell` to top-level too, eventually – the [same arguments](https://github.com/NixOS/nixpkgs/pull/319659#issuecomment-2168078414) apply to it.

**Comment by getchoo** [comment]
closing in favor of https://github.com/NixOS/nixpkgs/pull/326687

**Pull request closed without merging**
