### PR TITLE
lua: add 5.4.2

### PR DESCRIPTION
**Pull request by raboof**
###### Motivation for this change

Refs #99261

Tested with Notion, seems to work fine.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Can we remove 5.1?

**Comment by raboof** [comment]
> Can we remove 5.1?

I see quite a few explicit references to `lua5_1` in various places still, so I guess not yet.

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 107707` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>lua5_4</li>
    <li>lua5_4_compat</li>
  </ul>
</details>

**Comment by teto** [comment]
@SuperSandro2000 lua versioning stands on its own https://www.lua.org/versions.html. 5.1 is still very popular due to luajit so it's going to stay.

**Pull request merged**
