### PR TITLE
[19.09] zfs: 0.8.2 -> 0.8.3

### PR DESCRIPTION
**Pull request by Frostman**
###### Motivation for this change

Zfs 0.8.3 is included into release-20.03 and it contains many important fixes and improvements https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.8.3 such as - Linux 5.0 compat: SIMD compatibility https://github.com/zfsonlinux/zfs/pull/8965

Additionally, synced two more minor patches to get release-19.09 up to date with master.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---
This change is [Reviewable](https://reviewable.io/reviews/nixos/nixpkgs/79938)

### CODE REVIEW

**Comment by Frostman** [comment]
I've tested it locally with `nixpkgs-review` and it succeded. The `nixosTests.installer.zfsroot` passes as well.

**Comment by Frostman** [comment]
@GrahamcOfBorg build nixosTests.installer.zfsroot

**Comment by Mic92** [comment]
Actually we should not been affected by the SIMD patch because I simply patched the kernel to expose the fpu functions needed by ZFS. I might have not backported those to stable though.

**Comment by Mic92** [comment]
However support for new kernels is a good thing to have nevertheless.

**Comment by Mic92** [comment]
I will merge this together with https://github.com/NixOS/nixpkgs/pull/80008

**Pull request closed without merging**
