### PR TITLE
dovecot_fts_xapian: 1.4.9 -> 1.4.11

### PR DESCRIPTION
**Pull request by symphorien**
###### Motivation for this change

update

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) (`external` in simple nixos mailserver)
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ju1m** [comment]
@symphorien is it ok nowadays to use SRI hashes in Nixpkgs? And in that case isn't `hash =` preferred? I can't find a policy about this on the Nixpkgs manual, but I was once told to avoid SRI hash for better backward compatibility. If you didn't already know, you could convert with:
```
$ nix hash to-base32 sha256-HPmS2Z1PIEM9fc6EerCEigQJg5BK/115zOW2uxFqjP0=
1zccd88vpdp5riwmvzsaj21hj14ahjq7m16fglyl682gkpcr5y8w
```

**Comment by symphorien** [comment]
I asked on matrix and apparently yes: https://github.com/NixOS/nixpkgs/pull/89308#issuecomment-643803495
I see no reason to backport this PR.

**Comment by SuperSandro2000** [comment]
> @symphorien is it ok nowadays to use SRI hashes in Nixpkgs? And in that case isn't `hash =` preferred? I can't find a policy about this on the Nixpkgs manual, but I was once told to avoid SRI hash for better backward compatibility. If you didn't already know, you could convert with:
> 
> ```
> $ nix hash to-base32 sha256-HPmS2Z1PIEM9fc6EerCEigQJg5BK/115zOW2uxFqjP0=
> 1zccd88vpdp5riwmvzsaj21hj14ahjq7m16fglyl682gkpcr5y8w
> ```

No supported version of nixpkgs uses a nix version which can't deal with sri hashes. It is fine to use both at this time.

**Comment by SuperSandro2000** [comment]
> @symphorien is it ok nowadays to use SRI hashes in Nixpkgs? And in that case isn't `hash =` preferred? I can't find a policy about this on the Nixpkgs manual, but I was once told to avoid SRI hash for better backward compatibility. If you didn't already know, you could convert with:
> 
> ```
> $ nix hash to-base32 sha256-HPmS2Z1PIEM9fc6EerCEigQJg5BK/115zOW2uxFqjP0=
> 1zccd88vpdp5riwmvzsaj21hj14ahjq7m16fglyl682gkpcr5y8w
> ```

No supported version of nixpkgs uses a nix version which can't deal with sri hashes. It is fine to use both at this time.

**Comment by ju1m** [comment]
@symphorien, @SuperSandro2000, thanks.
Regarding the `sha256` vs. `hash`, there is https://github.com/NixOS/nixpkgs/pull/112388

**Pull request merged**
