### PR TITLE
pgadmin: remove version constrains, which also fixes new authlib requirement

### LINKED ISSUE #183861: pgadmin4 failed to install on unstable
### Describe the bug
Adding pgadmin4 to /etc/nixos/configuration.nix and then `nixos-rebuild switch` leads to

```
Executing pipInstallPhase
/build/pgadmin4-6.11/pip-build/dist /build/pgadmin4-6.11/pip-build
Processing ./pgadmin4-6.11-py3-none-any.whl
Requirement already satisfied: six==1.* in /nix/store/nkwqyk6mxnh71qisa1lx0kqxphhdb8d0-python3.10-six-1.16.0/lib/python3.10/site-packages (from pgadmin4==6.11) (1.16.0)
Requirement already satisfied: passlib==1.* in /nix/store/snv2m22gjpnnsf9lkbsd463n0sklijr6-python3.10-passlib-1.7.4/lib/python3.10/site-packages (from pgadmin4==6.11) (1.7.4)
Requirement already satisfied: Flask-Compress==1.* in /nix/store/1xkzfzzh02v24f2lxs986mgjzzp72xfj-python3.10-Flask-Compress-1.12/lib/python3.10/site-packages (from pgadmin4==6.11) (1.12)
Requirement already satisfied: pyotp==2.* in /nix/store/acyqs6x03hpbwszsskahiylixrcsb7ll-python3.10-pyotp-2.6.0/lib/python3.10/site-packages (from pgadmin4==6.11) (2.6.0)
Requirement already satisfied: qrcode==7.* in /nix/store/xn1gi1jisjkf1nsri96x4mvzxzcqmx3x-python3.10-qrcode-7.3.1/lib/python3.10/site-packages (from pgadmin4==6.11) (7.3.1)
Requirement already satisfied: azure-mgmt-resource==21.* in /nix/store/awsx6bng6xiwp0apwdrp09aqbfs59kcz-python3.10-azure-mgmt-resource-21.1.0/lib/python3.10/site-packages (from pgadmin4==6.11) (21.1.0)
Requirement already satisfied: eventlet>=0.33.0 in /nix/store/rzh148775yfl4g7fz51yfkhj1gl9yya4-python3.10-eventlet-0.33.1/lib/python3.10/site-packages (from pgadmin4==6.11) (0.33.1)
Requirement already satisfied: ldap3==2.* in /nix/store/vvhs4sc3h02p2ki0w04cma41sz7n0nai-python3.10-ldap3-2.9.1/lib/python3.10/site-packages (from pgadmin4==6.11) (2.9.1)
Requirement already satisfied: urllib3==1.26.* in /nix/store/w5zvy2q6y69fikj8zvgxbw5zpkz0awhr-python3.10-urllib3-1.26.10/lib/python3.10/site-packages (from pgadmin4==6.11) (1.26.10)
Requirement already satisfied: SQLAlchemy==1.4.* in /nix/store/zzc2a81ylzcgm1fa355i6yhs3rmkr976-python3.10-SQLAlchemy-1.4.39/lib/python3.10/site-packages (from pgadmin4==6.11) (1.4.39)
Requirement already satisfied: Flask-WTF==1.* in /nix/store/0mz5lnv2ilvnn996nx3dca4vffgc4wl9-python3.10-flask-wtf-1.0.1/lib/python3.10/site-packages (from pgadmin4==6.11) (1.0.1)
Requirement already satisfied: Flask-SocketIO>=5.0.1 in /nix/store/2li55l0ikrammvsc5v88c41jkyg1q6ha-python3.10-Flask-SocketIO-5.1.1/lib/python3.10/site-packages (from pgadmin4==6.11) (5.1.1)
Requirement already satisfied: psutil==5.* in /nix/store/4i68xjfqg1xjzxi068a5rk7pbd0ck3dp-python3.10-psutil-5.9.1/lib/python3.10/site-packages (from pgadmin4==6.11) (5.9.1)
Requirement already satisfied: Flask-Login==0.* in /nix/store/xc1nd23y8fprhsj3hr635fnh7i4d5rhr-python3.10-flask-login-0.6.1/lib/python3.10/site-packages (from pgadmin4==6.11) (0.6.1)
Requirement already satisfied: botocore>=1.23 in /nix/store/x3vaiqf2d9p6bp52v4bw0vc4zxc9f6y7-python3.10-botocore-1.27.31/lib/python3.10/site-packages (from pgadmin4==6.11) (1.27.31)
Requirement already satisfied: bcrypt==3.* in /nix/store/s3gckwr1692kfci3hy36jjiz7qsymiv9-python3.10-bcrypt-3.2.2/lib/python3.10/site-packages (from pgadmin4==6.11) (3.2.2)
Requirement already satisfied: azure-mgmt-subscription==3.0.0 in /nix/store/5vi59p7mxi8xfms1c6954fpa1jawh9m8-python3.10-azure-mgmt-subscription-3.0.0/lib/python3.10/site-packages (from pgadmin4==6.11) (3.0.0)
Requirement already satisfied: python-dateutil==2.* in /nix/store/jl68js2ns8yin04aar7d3ajz92sjmx7s-python3.10-python-dateutil-2.8.2/lib/python3.10/site-packages (from pgadmin4==6.11) (2.8.2)

ERROR: Could not find a version that satisfies the requirement Authlib==0.15.* (from pgadmin4) (from versions: none)
ERROR: No matching distribution found for Authlib==0.15.*

error: builder for '/nix/store/s2ifwkzjz4bxqrxcy2ihdzyyrvqvkcr2-pgadmin-6.11.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/10kwashq28akvs9acca6ap5h9k0zy8mw-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/2i73wgryxbp8xr1apnmmjw3a022bw9wi-nixos-system-fw-22.11pre395754.2a93ea177c3.drv' failed to build
```                                                                                                                                         

### Steps To Reproduce
1. Add pgadmin4 to `environment.systemPackages` in `/etc/nixos/configuration.nix`
2. Run `nixos-rebuild switch`
3. Fails with error

### Expected behavior
NixOS derivation succeeds

### Notify maintainers
@gador 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
dsp:~/⁞ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.06 MiB download, 0.30 MiB unpacked):
  /nix/store/a9f4h2yjhdlk7xj3wj3p7b5r6s659qfl-bash-interactive-5.1-p16-dev
copying path '/nix/store/a9f4h2yjhdlk7xj3wj3p7b5r6s659qfl-bash-interactive-5.1-p16-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.13, NixOS, 22.11 (Raccoon), 22.11pre395754.2a93ea177c3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"nixos"`
 - channels(dsp): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by gador**
###### Description of changes

Due to an update of `Authlib` the requirements file needed to be adapted. All tests still pass with the new version.

Fixes #183861

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — COMMENTED** [review]
Maybe we should just unpin everything

**Comment by gador** [comment]
sure. Done

**Comment by SuperSandro2000** [comment]
Can we use sed to or substitute to replace all ``==`` with ``>=``? Maintaining that list is not great.

**Comment by gador** [comment]
good idea. Done :+1:

**Comment by SuperSandro2000** [comment]
@ofborg build pgadmin4

**Pull request merged**
