### PR TITLE
elpi: 1.7.0 -> 1.10.2; coq-elpi: 1.1 -> 1.3

### PR DESCRIPTION
**Pull request by CohenCyril**
###### Motivation for this change

Update `ocamlPackages.elpi` and  `coqPackages.coq-elpi` consequently.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by CohenCyril** [comment]
@grahamcofborg build ocamlPackages.elpi coqPackages_8_10.coq-elpi coqPackages_8_11.coq-elpi

**Comment by CohenCyril** [comment]
@gares @vbgl FYI

**Comment by vbgl** [comment]
@GrahamcOfBorg build coqPackages_8_10.coq-elpi coqPackages_8_11.coq-elpi

**Comment by vbgl** [comment]
Merged into 20.03 as 7c4a7a78ff0b5aa7b4db409d4ebf8a69899575ad

**Comment by gares** [comment]
thanks!

**Pull request merged**
