### PR TITLE
slack: add Darwin target

### PR DESCRIPTION
**Pull request by ersinakinci**
###### Motivation for this change

This PR adds Darwin as a target for `slack` ~~and bumps the version from 4.2.0 to 4.3.3~~.

For the Darwin target, we have to use `hdiutil` to mount the dmg and copy the app bundle from there. Using `undmg` or `xpwn` to extract the app from the dmg unfortunately yields corrupted binaries.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mmahut** [comment]
Looks like 4.3.3 is not out yet? 

```
curl: (22) The requested URL returned error: 403
error: cannot download slack-desktop-4.3.3-amd64.deb from any mirror
```

**Comment by earksiinni** [comment]
@mmahut you're correct, it's not available for Linux yet, sorry about that. I've downgraded back to 4.2.0.

On a separate note, is there a policy on having multiple versions for different platforms within the same package? Is it considered good/bad practice?

**Comment by Mic92** [comment]
Having both in the same file is considered good practice. There is not much code sharing but at least the metadata is the same.

**Comment by earksiinni** [comment]
@Mic92 but which is better, preferring to keep the same version between two different platforms or offering a more recent version for the other platform when one is available? I'm worried about breaking expressions and tooling that depend on the `version` field, assuming that the package has a single canonical version (example: [package search results](https://nixos.org/nixos/packages.html)).

**Comment by Mic92** [comment]
@earksiinni if the delay between the two is acceptable we could keep one version. Otherwise they could diverge as well.

**Pull request merged**
