### PR TITLE
gitlab: 12.4.2 -> 12.4.3

### PR DESCRIPTION
**Pull request by ghost**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @talyz @fpletz @globin @krav

### CODE REVIEW

**Review by talyz — APPROVED** [review]
Looks good!
- Built with `nix-review pr 73857`
- Tested a few things manually in local VM

**Comment by talyz** [comment]
cc @flokli

**Comment by flokli** [comment]
backported to 19.09 in 105e5282b20.

**Comment by flokli** [comment]
Hm, it seems 12.5 was also released on Nov 22: https://about.gitlab.com/blog/2019/11/22/gitlab-12-5-released/

Anybody already on it? :laughing:

**Comment by talyz** [comment]
Oh, I'll get on it today :)

**Pull request merged**
