### PR TITLE
home-assistant: support juicenet component

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
Don't merge before https://github.com/jesserockz/python-juicenet/issues/13 is resolved.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Apart from the licensing issue … tested.

**Comment by fabaff** [comment]
License file was added (https://github.com/jesserockz/python-juicenet/blob/master/LICENSE).

**Comment by dotlambda** [comment]
ping @fabaff @mweinelt

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 127997` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>home-assistant: <a href="https://termbin.com/2z4xi">plain log</a>  |  <a href="https://htmlpreview.github.io/?https://gist.githubusercontent.com/SuperSandroBot/e066e19264b7da078b6047ad99403da7/raw/index.html">pretty log </a></li>
  </ul>
</details>
<details>
<summary>
2 packages built:
</summary>
<ul>
<li>python38Packages.python-juicenet</li>
<li>python39Packages.python-juicenet</li>
</ul>
</details>

**Comment by dotlambda** [comment]
@ofborg test home-assistant

**Comment by dotlambda** [comment]
@ofborg build home-assistant

**Comment by dotlambda** [comment]
> 1 package failed to build and are new build failure

Ofborg can't reproduce, so I'm merging this.

**Pull request merged**
