### PR TITLE
MythTV: 30.0 -> 31.0

### PR DESCRIPTION
**Pull request by LouisDK1**
###### Motivation for this change

MythTV was upgraded to version 31.0

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by LouisDK1** [comment]
I made a force-push. Maybe the new commit will build?

**Comment by dasj19** [comment]
I'll check this shortly and come back with the results

**Comment by dasj19** [comment]
Ran `nix-shell -p nixpkgs-review --run "nixpkgs-review pr 93486"`and got the following issues
```
error: while evaluating 'callPackageWith' at /home/daniel/.cache/nixpkgs-review/pr-93486/nixpkgs/lib/customisation.nix:117:35, called from /home/daniel/.cache/nixpkgs-review/pr-93486/nixpkgs/pkgs/top-level/all-packages.nix:21592:12:
while evaluating 'makeOverridable' at /home/daniel/.cache/nixpkgs-review/pr-93486/nixpkgs/lib/customisation.nix:67:24, called from /home/daniel/.cache/nixpkgs-review/pr-93486/nixpkgs/lib/customisation.nix:121:8:
anonymous function at /home/daniel/.cache/nixpkgs-review/pr-93486/nixpkgs/pkgs/applications/video/mythtv/default.nix:1:1 called without required argument 'libXNVCtrl', at /home/daniel/.cache/nixpkgs-review/pr-93486/nixpkgs/lib/customisation.nix:69:16
```

**Comment by LouisDK1** [comment]
@dasj19 I forgot to remove some old dependencies. Should be fixed now.

**Comment by dasj19** [comment]
@LouisDK1 I have tried again and it still doesnt build. I put `libXNVCtrl` back as dependency as it is required, but the the `disable-os-detection.patch` fails to apply.. I think that patch needs to be adjusted to the new code.

**Comment by LouisDK1** [comment]
@sasj19 My last commit seems to be complete now and work. Was able to run `nix-shell -p nixpkgs-review --run "nixpkgs-review pr 93486"` successfully.

**Review by dasj19 — APPROVED** [review]
Yes it runs successfully indeed.

**Comment by LouisDK1** [comment]
@rycee Can you help me merge a new version of mythtv once again?

**Comment by rycee** [comment]
Thanks! Builds fine and the binaries seem to work. Rebased to master in 6eadc11005318fc4eef7da19898cff51689fb723.

**Pull request closed without merging**
