### PR TITLE
lib/systems: use a shell script for native `emulator`

### PR DESCRIPTION
**Pull request by emilazy**
This avoids pulling in all of `execline`’s closure.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilazy** [comment]
`tests.cc-wrapper.default` builds fine on `aarch64-linux`.

**Review by sternenseemann — APPROVED** [review]
Haven't tested it myself, but I think this is the best idea if we

1. Allow using `emulator` irrespective of native/cross compilation to make code simpler (i.e. avoid conditionals at usage sites (though I personally think the less emulator the better))
1. want to keep native stdenv tests quick to build without messing with nixpkgs bootstrapping internals which is a) treacherous and b) not really appropriate in `lib` which should be as generic as possible (the emulator logic in here is already pushing it). See e.g. #356979 for a use of `__bootPackages` I'd like to avoid.

**Comment by emilazy** [comment]
Yeah, discussion on previous PRs imply to me that moving the emulator stuff out of `lib` is meant to happen and it seems like a good idea to me, but not a job I feel like taking on right now. Really the systems stuff as a whole should not be in there. Agreed that the `__bootPackages` stuff is unpleasant.

**Comment by trofi** [comment]
Bisect says 4c81eb765194611cc142b392a53b2f4cf58445e7 "lib/systems: use a shell script for native `emulator`" broke the eval of `mesonEmulatorHook.crossFile` attribute in `staging` as:

```
$ nix eval --impure --expr 'with import ./. {}; mesonEmulatorHook.crossFile'
error:
       … while evaluating the attribute 'crossFile'
         at pkgs/top-level/all-packages.nix:2570:11:
         2569|         substitutions = {
         2570|           crossFile = writeText "cross-file.conf" ''
             |           ^
         2571|               [binaries]

       … in the condition of the assert statement
         at pkgs/build-support/trivial-builders/default.nix:132:5:
          131|     # TODO: To fully deprecate, replace the assertion with `lib.isString` and remove the warning
          132|     assert lib.assertMsg (lib.strings.isConvertibleWithToString text) ''
             |     ^
          133|       pkgs.writeText ${lib.strings.escapeNixString name}: The second argument should be a string, but it's a ${builtins.typeOf text} instead.'';

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: expected a string but found a set: { type = "derivation"; __ignoreNulls = true; __structuredAttrs = «thunk»; all = «thunk»; allowSubstitutes = false; args = «thunk»; buildCommand = «thunk»; buildInputs = «thunk»; builder = «thunk»; checkPhase = «thunk»; «39 attributes elided» }
```

**Comment by emilazy** [comment]
Thanks; should be fixed by https://github.com/NixOS/nixpkgs/pull/358507.

**Pull request merged**
