### PR TITLE
ocaml-pcre: use buildOcaml

### PR DESCRIPTION
**Pull request by FlorentBecker**

### CODE REVIEW

**Comment by FlorentBecker** [comment]
The build failure noticed by travis should be fixed now by https://github.com/NixOS/nixpkgs/commit/4a69e5ae856e727ac9282f08f565e4466f3cc029

**Comment by vbgl** [comment]
Is there a rationale for this change?

**Comment by FlorentBecker** [comment]
This adds "hasSharedObjects = true;" which is needed (at least) when using camlp4 extensions which depend on pcre.

**Comment by vbgl** [comment]
Thank you very much.

**Pull request merged**
