### PR TITLE
zsh-syntax-highlighting: enable build for darwin

### PR DESCRIPTION
**Pull request by periklis**
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [x] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
How would you use this package without the corresponding nixos module? I ask, because this would be a useful comment for potential users on other platforms.

**Review by loskutov — APPROVED** [review]
Thank you for this fix, I should've checked what's the platforms of zsh and duplicated that myself.

**Comment by loskutov** [comment]
@Mic92 one can easily add the `source ${pkgs.zsh-syntax-highlighting}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh` line to his zshrc manually.

**Comment by Mic92** [comment]
but that would break with every upgrade, right?

**Comment by loskutov** [comment]
Well, if you reference it as "/run/current-system/sw/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh", it won't.

**Comment by periklis** [comment]
@Mic92 as @loskutov mentioned, we osx users have to maintain our rc-files and configs by hand with some tricks, since we don't have the beautiful abstrastion of nixos services/modules/etc. The same goes for any service-like package (e.g. postgresql). I've to careful maintain my launchd plist files as long as services don't abstract/support launchd.

**Comment by Mic92** [comment]
@periklis sounds horrible :( Thanks for you pull request anyway.

**Comment by periklis** [comment]
@mic92 i know, but i am not aware of the feasibility to abstrast services like launchd on osx, yet.

**Comment by Mic92** [comment]
maybe launchd profiles could become part of nixpkgs like it does in homebrew.

**Pull request merged**
