### PR TITLE
elm: 0.16.0 -> 0.17.0

### PR DESCRIPTION
**Pull request by sjmackenzie**
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [X] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by domenkozar** [comment]
Woot I just looked if someone did this or should I start it :) Thanks! cc @datakurre

**Comment by domenkozar** [comment]
Building and testing on my project.

**Comment by sjmackenzie** [comment]
you're going to have to make quite a few changes to your src, it's better to test it on a small hello world type app.

**Comment by domenkozar** [comment]
@sjmackenzie yeah I know, it's small should should be quick. Also I'm fine if I get a bunch of type errors, that means Elm works :)

**Comment by sjmackenzie** [comment]
Yeah, also need to wait for the editors to update their plugins, the editors register the syntax change as an error. (btw anybody interested in getting https://github.com/bitkeeper-scm/bitkeeper into nix?)

**Comment by domenkozar** [comment]
Atom already updated :) Thanks this work! (sorry no particular interest into bitkeeper)

**Comment by sjmackenzie** [comment]
np

**Comment by sjmackenzie** [comment]
btw that was the fastest merge I've ever had in nixpkgs, really awesome stuff, thanks a lot for that.

**Pull request merged**
