### PR TITLE
phpPackages.exts.pdo_odbc: init for all versions of php

### PR DESCRIPTION
**Pull request by etu**
###### Motivation for this change
You mentioned that this module was missing, so here it comes :)

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [N/A] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by etu** [comment]
@GrahamcOfBorg build php74Packages.exts.pdo_odbc php73Packages.exts.pdo_odbc php72Packages.exts.pdo_odbc

**Comment by aanderse** [comment]
Awesome! Thank you @etu :tada: Did you get a chance to test?

**Comment by etu** [comment]
@aanderse It builds and loads as an extension, so should be fine. But I haven't had a real database to connect it to.

**Comment by aanderse** [comment]
Thanks @etu!

**Pull request merged**
