### PR TITLE
code-browser: init at 7.1.20

### PR DESCRIPTION
**Pull request by jacereda**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jacereda** [comment]
This builds on top of #88545

**Comment by Lassulus** [comment]
getting this error during review:
```
error: build of '/nix/store/ppcrv05yxvw27myf4wa98vq8nlsvvbr5-code-browser-7.1.20.drv' on 'ssh://nix@morpheus.r' failed: builder for '/nix/store/ppcrv05yxvw27myf4wa98vq8nlsvvbr5-code-browser-7.1.20.drv' failed with exit code 2
builder for '/nix/store/ppcrv05yxvw27myf4wa98vq8nlsvvbr5-code-browser-7.1.20.drv' failed with exit code 1; last 10 log lines:
  ar rcs /build/code-browser-7.1.20/libcopper-gtk.a /build/code-browser-7.1.20/gtk.o
  make[1]: Leaving directory '/build/code-browser-7.1.20/libs/copper-ui'
  make[1]: Entering directory '/build/code-browser-7.1.20'
  Compiling...
  Resources...
  /nix/store/npfsrhkjww5q7sax7p7ijcrj3wlbrxn7-bash-4.4-p23/bin/bash: libs/copper-ui/utils/gen-res: /usr/bin/env: bad interpreter: No such file or directory
  make[1]: *** [Makefile:62: /build/code-browser-7.1.20/resources.o] Error 126
  make[1]: Leaving directory '/build/code-browser-7.1.20'
  make: *** [Makefile:94: with-local-libs] Error 2
  builder for '/nix/store/ppcrv05yxvw27myf4wa98vq8nlsvvbr5-code-browser-7.1.20.drv' failed with exit code 2
error: build of '/nix/store/dfhn2mbswlkr8zx6zqsbdy64kd35zgxz-code-browser-7.1.20.drv' on 'ssh://nix@morpheus.r' failed: builder for '/nix/store/dfhn2mbswlkr8zx6zqsbdy64kd35zgxz-code-browser-7.1.20.drv' failed with exit code 2
builder for '/nix/store/dfhn2mbswlkr8zx6zqsbdy64kd35zgxz-code-browser-7.1.20.drv' failed with exit code 1; last 10 log lines:
  ar rcs /build/code-browser-7.1.20/libcopper-gtk.a /build/code-browser-7.1.20/gtk.o
  make[1]: Leaving directory '/build/code-browser-7.1.20/libs/copper-ui'
  make[1]: Entering directory '/build/code-browser-7.1.20'
  Compiling...
  Resources...
  /nix/store/npfsrhkjww5q7sax7p7ijcrj3wlbrxn7-bash-4.4-p23/bin/bash: libs/copper-ui/utils/gen-res: /usr/bin/env: bad interpreter: No such file or directory
  make[1]: *** [Makefile:62: /build/code-browser-7.1.20/resources.o] Error 126
  make[1]: Leaving directory '/build/code-browser-7.1.20'
  make: *** [Makefile:94: with-local-libs] Error 2
  builder for '/nix/store/dfhn2mbswlkr8zx6zqsbdy64kd35zgxz-code-browser-7.1.20.drv' failed with exit code 2
cannot build derivation '/nix/store/p7bf1r38lcjxrhrcqm60pphdj6mbsdy7-env.drv': 2 dependencies couldn't be built
[0 built (2 failed), 1 copied (0.9 MiB), 0.0 MiB DL]
error: build of '/nix/store/p7bf1r38lcjxrhrcqm60pphdj6mbsdy7-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/88548
2 packages failed to build:
code-browser-gtk code-browser-qt
```

**Comment by jacereda** [comment]
Is that using `nixpkgs-review` or something similar? I can't reproduce it...

**Comment by Lassulus** [comment]
yes with nixpkgs-review. maybe you need to rebase on master? nixpkgs-review does this automatically

**Comment by Lassulus** [comment]
@GrahamcOfBorg build code-browser-gtk code-browser-qt

**Comment by jacereda** [comment]
This is what I get after rebasing. Maybe it suceeds for me because it isn't sandboxed?

```
[jacereda@imac:~/nixpkgs]$ nix-shell -p nix-review

[nix-shell:~/nixpkgs]$ nixpkgs-review
usage: /nix/store/pfagx59b82ycn0jpxv5rskqj4z11jfy5-nixpkgs-review-2.3.1/bin/nixpkgs-review [-h] {post-result,approve,merge,pr,rev,wip} ...
/nix/store/pfagx59b82ycn0jpxv5rskqj4z11jfy5-nixpkgs-review-2.3.1/bin/nixpkgs-review: error: the following arguments are required: subcommand

[nix-shell:~/nixpkgs]$ nixpkgs-review pr 88548
$ git -c fetch.prune=false fetch --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/88548/head:refs/nixpkgs-review/1
remote: Enumerating objects: 74, done.        
remote: Counting objects: 100% (74/74), done.        
remote: Compressing objects: 100% (15/15), done.        
remote: Total 103 (delta 65), reused 59 (delta 59), pack-reused 29        
Receiving objects: 100% (103/103), 74.26 KiB | 475.00 KiB/s, done.
Resolving deltas: 100% (69/69), completed with 37 local objects.
From https://github.com/NixOS/nixpkgs
   13209156c19..1d8caa0db05  master               -> refs/nixpkgs-review/0
 + a7574c56689...0469b699068 refs/pull/88548/head -> refs/nixpkgs-review/1  (forced update)
$ git worktree add /home/jacereda/.cache/nixpkgs-review/pr-88548-1/nixpkgs 1d8caa0db058c3ac5ad55db7bc353a56110a88f0
Preparing worktree (detached HEAD 1d8caa0db05)
Updating files: 100% (22570/22570), done.
HEAD is now at 1d8caa0db05 gerrit: 3.2.2 -> 3.2.3 (#96304)
$ nix-env -f /home/jacereda/.cache/nixpkgs-review/pr-88548-1/nixpkgs -qaP --xml --out-path --show-trace
$ git merge --no-commit 0469b699068be6e2d74e1ac882245cc631995028
Auto-merging pkgs/top-level/all-packages.nix
Automatic merge went well; stopped before committing as requested
$ nix-env -f /home/jacereda/.cache/nixpkgs-review/pr-88548-1/nixpkgs -qaP --xml --out-path --show-trace --meta
2 packages added:
code-browser-qt (init at 7.1.20) code-browser-gtk (init at 7.1.20)

$ nix build --no-link --keep-going --option build-use-sandbox relaxed -f /home/jacereda/.cache/nixpkgs-review/pr-88548-1/build.nix
warning: ignoring the user-specified setting 'sandbox', because it is a restricted setting and you are not a trusted user
https://github.com/NixOS/nixpkgs/pull/88548
2 packages built:
code-browser-gtk code-browser-qt

$ nix-shell /home/jacereda/.cache/nixpkgs-review/pr-88548-1/shell.nix

[nix-shell:~/.cache/nixpkgs-review/pr-88548-1]$ 

```

**Comment by Lassulus** [comment]
are you running the build on nixos?

**Comment by jacereda** [comment]
Yes.

**Comment by Lassulus** [comment]
I guess the sandbox is indeed the problem: ` /nix/store/npfsrhkjww5q7sax7p7ijcrj3wlbrxn7-bash-4.4-p23/bin/bash: libs/copper-ui/utils/gen-res: /usr/bin/env: bad interpreter: No such file or directory` since `/usr/bin/env` is not available inside it

**Comment by jacereda** [comment]
Added a `patchSheBangs`.

**Comment by Lassulus** [comment]
the gtk version crashed for me if I want to open a file?

**Comment by jacereda** [comment]
Works for me, although the first time takes a while until it opens the dialog. Seems to be related to UDisk2VolumeMonitor according to the logs.

Subsequent Open operations are instantaneous.

**Comment by jacereda** [comment]
Oh, and take a look at the "Open Directory" option on a code base and select "View/Zoomable View", it rocks.

**Pull request merged**
