### PR TITLE
nodejs-5_x: 5.6.0 -> 5.7.0

### PR DESCRIPTION
**Pull request by gilligan**
- Update nodejs 5.x to latest version: `5.7.0`
- Built and tested on `darwin`

### CODE REVIEW

**Comment by hrdinka** [comment]
cc @cillianderoiste @Havvy.

**Comment by gilligan** [comment]
Since the travis ci build failure looks totally unrelated i'll just try again

**Comment by domenkozar** [comment]
cc @svanderburg

**Comment by gilligan** [comment]
Finally green ;-)

**Comment by zimbatm** [comment]
LGTM

**Pull request merged**
