### PR TITLE
Backport Plasma 5.8

### PR DESCRIPTION
**Pull request by ttuegel**
###### Motivation for this change

Plasma 5.8 is a LTS release from upstream which will continue to receive bug fixes for the lifetime of NixOS 16.09. This is strictly a backport of patches from master.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vandenoever** [comment]
What is the best way to test this PR? I guess it can only be tested for the whole system. Can i tell configuration.nix to use it or change a channel setting?

**Comment by ttuegel** [comment]
> I guess it can only be tested for the whole system. Can i tell configuration.nix to use it or change a channel setting?

Yes, you need to test your whole system. You can pass the remote tarball as an option to `nixos-rebuild` like this:
```
nixos-rebuild -I nixpkgs=https://api.github.com/repos/ttuegel/Nixpkgs/tarball/344723265455f8290fb9e7e7fd65668a1e78970e ...
```

**Comment by vandenoever** [comment]
It build and it works fine. I've used it for about an hour so far. Screen (un)locking works. Logging in and out works. Adding desktop widgets works.
Switching desktops works.

KRunner crashes very easily but already did so in 5.7.

An important note: user should not have installed kwin or any plasma packages in the personal profile.

**Comment by vandenoever** [comment]
The network manager widget does not work. I see two different error messages:
```
Fout bij het laden van QML-bestand: file:///nix/store/xhpanjz21ycxqkj9w7cr85rvmqdgihk2-plasma-nm-5.8.3/share/plasma/plasmoids/org.kde.plasma.networkmanagement/contents/ui/main.qml:37:34: Type PopupDialog unavailable
```
```
Fout bij het laden van QML-bestand: file:///nix/store/xhpanjz21ycxqkj9w7cr85rvmqdgihk2-plasma-nm-5.8.3/share/plasma/plasmoids/org.kde.plasma.networkmanagement/contents/ui/main.qml:37:34: Type PopupDialog unavailable
file:///nix/store/xhpanjz21ycxqkj9w7cr85rvmqdgihk2-plasma-nm-5.8.3/share/plasma/plasmoids/org.kde.plasma.networkmanagement/contents/ui/PopupDialog.qml:74:23: Type ConnectionItem unavailable
file:///nix/store/xhpanjz21ycxqkj9w7cr85rvmqdgihk2-plasma-nm-5.8.3/share/plasma/plasmoids/org.kde.plasma.networkmanagement/contents/ui/ConnectionItem.qml:389:17: Cannot assign to non-existent property "revealPasswordButtonShown"
```

**Comment by ttuegel** [comment]
> The network manager widget does not work. I see two different error messages:

I can't reproduce this. You have `networking.networkmanager.enable = true;` in `configuration.nix`, and `plasma-nm` is not installed in your user's profile?

**Comment by vandenoever** [comment]
> You have networking.networkmanager.enable = true; in configuration.nix?
Yes and `nmcli` works for the normal user so I'm not without network.

> plasma-nm is not installed in your user's profile?
Yes, it is not installed for a normal user.

`/nix/store/xhpanjz21ycxqkj9w7cr85rvmqdgihk2-plasma-nm-5.8.3/share/plasma/plasmoids/org.kde.plasma.networkmanagement/contents/ui/PopupDialog.qml` is present in the system and readable to everyone. For some weird reason main.qml cannot load a file that's in the same directory.

The NM widget does not work on the desktop and not on the panel. I've tried a lot of other widgets. They all work.

**Comment by vandenoever** [comment]
`PopupDialog.qml:74:23: Type ConnectionItem unavailable`
And yet, `/nix/store/xhpanjz21ycxqkj9w7cr85rvmqdgihk2-plasma-nm-5.8.3/share/plasma/plasmoids/org.kde.plasma.networkmanagement/contents/ui/ConnectionItem.qml` exists.

But a bit further down:
`ConnectionItem.qml:389:17: Cannot assign to non-existent property "revealPasswordButtonShown`
This is on PlasmaComponents.TextField. 
That property was added to `src/declarativeimports/plasmacomponents/qml/TextField.qml` in 5.26.

Maybe the old qml is somehow in the path due an older kde application being installed, e.g. kate-16.08.

**Comment by vandenoever** [comment]
I've deinstalled kate-16.08 and then the NM widget works. When kate-16.08 is reinstalled, the NM widget is broken again.
Somehow installing kate-16.08 exposes a path for 'old' qml files to the environment which is then picked up by plasma.
If kate would also depend on frameworks 5.26, things would be fine.

**Comment by ttuegel** [comment]
> Somehow installing kate-16.08 exposes a path for 'old' qml files to the environment which is then picked up by plasma.
> If kate would also depend on frameworks 5.26, things would be fine.

Kate must depend on Frameworks 5.26 because there is no other version available. Could you point out which QML file is propagated to the user environment? Kate should only be providing binaries and `.desktop` files (for the menu).

**Comment by vandenoever** [comment]
kate-16.08.2/nix-support/propagated-user-env-packages
```
/nix/store/ixm535i33zddyq7vj8fgfjfcp4szyxl4-kate-16.08.2                         
/nix/store/nbwh3lhqj9gavhn4r02pa3764ml4rcyr-kcoreaddons-5.24.0                   
/nix/store/8v71l1pdhp07hvq20v7z6937gd0fbz5r-shared-mime-info-1.7                 
/nix/store/10kp635h5p628m0lw960b0hv9mb2s3hg-kglobalaccel-5.24.0                  
/nix/store/p2n4ylxmckhr06vw53yihiazd2g4p9fg-breeze-icons-5.24.0                  
/nix/store/sk36xjb41jdnk363xhhdijndd29fr36l-kio-5.24.0                           
/nix/store/rz77l1dc0lfhf9i7x5byjrrkwsxh2h48-kjobwidgets-5.24.0                   
/nix/store/ma9rnvxcj4z7yxzpd4x32i3sl97dwaw9-knotifications-5.24.0                 
/nix/store/qw17wagm3y76fimgq7ydr5ss4bdpfwpk-phonon-qt5-4.9.0                     
/nix/store/gxayzyx6wxzsbfznd0k88qyvwvawfg2z-kwallet-5.24.0                       
/nix/store/9xq1cpaig0bkqf18lpv2ri361kj33ksq-kinit-5.24.0                         
/nix/store/f5z7xs2c44nx9nbghbz556ssd63fm80m-konsole-16.08.2                      
/nix/store/pngfqlg9rsagjmf0a83jzk5ccf4d1pc3-kdelibs4support-5.24.0               
/nix/store/xjllfl5cjrldc945riqhrxg4lbjq807g-kded-5.24.0                          
/nix/store/af61v101hybwjcna3qmn2m973fxyil9s-network-manager-1.2.4                
```

**Comment by vandenoever** [comment]
So I guess KF 5.26 or 5.27 would need to be backported first for the plasma backport to work.

**Comment by ttuegel** [comment]
KDE Frameworks 5.26 is already backported as part of this PR (b5f4e8e). If you are building your system from this PR, Frameworks 5.24 doesn't exist!

**Comment by vandenoever** [comment]
I've run
```
nixos-rebuild -I nixpkgs=https://api.github.com/repos/ttuegel/Nixpkgs/tarball/34472326545
```
but that does not put that path as the channel for the normal user apparently.
So if this is merged it'll work fine since then kate will use kf 5.26.

So by all means :shipit:

**Comment by ttuegel** [comment]
I merged this along with a new patch from master that should stop user environment packages from causing problems for Plasma in the future.

**Pull request merged**
