### PR TITLE
vimPlugins.nvim-treesitter.{grammarToPlugin,grammarPlugins}: init

### PR DESCRIPTION
**Pull request by figsoda**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by teto** [comment]
awesome ! This is something I've wanted for a long time !

My scenario is: I want to add vimPlugins.orgmode to neovim and have it work out of the box without extra configuration. This is a good example because orgmode needs a treesitter grammar. So I added in vim/overrides.nix
``` 
 orgmode = super.orgmode.overrideAttrs (old: {
    dependencies = with self; [ nvim-treesitter.grammarPlugins.org ];
  });
```
and tested it after a rebuild:
```                                                                                                          
Error detected while processing /home/teto/home/config/nvim/init.lua:
E5113: Error while calling lua chunk: ...pack/myNeovimPackages/start/orgmode/lua/orgmode/init.lua:71: modul
e 'nvim-treesitter.parsers' not found:
        no field package.preload['nvim-treesitter.parsers']
        no file '/nix/store/87z6via3qbw1227398sf24w7xik94rsv-luajit-2.1.0-2022-10-04-env/share/lua/5.1/nvim
-treesitter/parsers.lua'
```
my understanding is that nvim-treesitter.grammarPlugins.org just brings the parser but that was already available via tree-sitter-grammars.tree-sitter-org-nvim. 
Just installing the parser isn't enough, it should bring nvim-treesitter as a dependency. This may create a collision problem but I think we can work around it when files are the same (maybe symlinkEnv doesn't even complain then).

**Comment by figsoda** [comment]
> Just installing the parser isn't enough, it should bring nvim-treesitter as a dependency.

this should already be possible with this:
```nix
{
  dependencies = with self; [ (nvim-treesitter.withGrammars (p: [ p.org ])) ];
}
```

> This may create a collision problem

this shouldn't be an issue any more after https://github.com/NixOS/nixpkgs/pull/201548

> my understanding is that nvim-treesitter.grammarPlugins.org just brings the parser but that was already available via tree-sitter-grammars.tree-sitter-org-nvim.

true, since all the nvim-treesitter stuff is mostly about keeping the grammars compatible with the queries using the upstream lock file

**Comment by teto** [comment]
seems like it is `(nvim-treesitter.withPlugins (p: [ p.org ]))` and not withGrammar. I've tested the tip with https://github.com/NixOS/nixpkgs/pull/208117/files and it works so not sure we need this MR anymore ? (`withGrammars` would be better than `withPlugins`)

**Comment by figsoda** [comment]
>  and not withGrammar.
yep, I had a typo. I agree that `withGrammars` is a better name than `withPlugins`, but I don't have a strong feeling about it so I just kept the name for backwards compatibility

I am going to close this since it doesn't seem to be needed

**Pull request closed without merging**
