### PR TITLE
vimPlugins.neon: init at 2021-07-30

### LINKED ISSUE #136041: Request: vimPlugins.neon
**Project description**
> Customizable coloscheme with dark and light options, vivid colors and easy on the eye.

**Metadata**

* homepage URL: https://github.com/rafamadriz/neon
* source URL: https://github.com/rafamadriz/neon
* license: gpl3
* platforms: unix, linux, darwin

### PR DESCRIPTION
**Pull request by sestrella**
###### Motivation for this change

Fixes https://github.com/NixOS/nixpkgs/issues/136041

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sestrella** [comment]
`nix-shell -p nixpkgs-review --run "nixpkgs-review pr 136130"` output:

```
109 packages built:
- spacevim
- vimPlugins.Coqtail
- vimPlugins.LeaderF
- vimPlugins.Tagbar
- vimPlugins.UltiSnips
- vimPlugins.ale
- vimPlugins.auto-session
- vimPlugins.bufferline-nvim
- vimPlugins.chadtree
- vimPlugins.cmp-buffer
- vimPlugins.cmp-calc
- vimPlugins.cmp-emoji
- vimPlugins.cmp-nvim-lsp
- vimPlugins.cmp-nvim-lua
- vimPlugins.cmp-path
- vimPlugins.cmp-vsnip
- vimPlugins.cmp_luasnip
- vimPlugins.coc-lua
- vimPlugins.compe-tmux
- vimPlugins.denite
- vimPlugins.deol-nvim
- vimPlugins.deoplete-fish
- vimPlugins.deoplete-khard
- vimPlugins.deoplete-nvim
- vimPlugins.edge
- vimPlugins.feline-nvim
- vimPlugins.formatter-nvim
- vimPlugins.friendly-snippets
- vimPlugins.fugitive
- vimPlugins.fugitive-gitlab-vim
- vimPlugins.gentoo-syntax
- vimPlugins.git-worktree-nvim
- vimPlugins.gitsigns-nvim
- vimPlugins.glow-nvim
- vimPlugins.gruvbox-material
- vimPlugins.gruvbox-nvim
- vimPlugins.gv-vim
- vimPlugins.indent-blankline-nvim
- vimPlugins.kommentary
- vimPlugins.lightspeed-nvim
- vimPlugins.lir-nvim
- vimPlugins.lsp_signature-nvim
- vimPlugins.luasnip
- vimPlugins.lush-nvim
- vimPlugins.mattn-calendar-vim
- vimPlugins.minimap-vim
- vimPlugins.ncm2-ultisnips
- vimPlugins.neco-vim
- vimPlugins.neogit
- vimPlugins.neon
- vimPlugins.neorg
- vimPlugins.neoscroll-nvim
- vimPlugins.neovim-ayu
- vimPlugins.nterm-nvim
- vimPlugins.null-ls-nvim
- vimPlugins.nvim-autopairs
- vimPlugins.nvim-base16
- vimPlugins.nvim-cmp
- vimPlugins.nvim-compe
- vimPlugins.nvim-dap
- vimPlugins.nvim-gps
- vimPlugins.nvim-highlite
- vimPlugins.nvim-hlslens
- vimPlugins.nvim-jdtls
- vimPlugins.nvim-lspconfig
- vimPlugins.nvim-notify
- vimPlugins.nvim-tree-lua
- vimPlugins.nvim-ts-rainbow
- vimPlugins.onedark-nvim
- vimPlugins.packer-nvim
- vimPlugins.refactoring-nvim
- vimPlugins.rhubarb
- vimPlugins.rust-tools-nvim
- vimPlugins.sonokai
- vimPlugins.sql-nvim
- vimPlugins.symbols-outline-nvim
- vimPlugins.telescope-frecency-nvim
- vimPlugins.telescope-fzf-native-nvim
- vimPlugins.telescope-fzf-writer-nvim
- vimPlugins.telescope-fzy-native-nvim
- vimPlugins.telescope-nvim
- vimPlugins.telescope-symbols-nvim
- vimPlugins.telescope-z-nvim
- vimPlugins.toggleterm-nvim
- vimPlugins.traces-vim
- vimPlugins.vim-android
- vimPlugins.vim-capslock
- vimPlugins.vim-clap
- vimPlugins.vim-colorschemes
- vimPlugins.vim-dadbod-completion
- vimPlugins.vim-dadbod-ui
- vimPlugins.vim-elixir
- vimPlugins.vim-flog
- vimPlugins.vim-git
- vimPlugins.vim-jinja
- vimPlugins.vim-lsp
- vimPlugins.vim-matchup
- vimPlugins.vim-mucomplete
- vimPlugins.vim-plug
- vimPlugins.vim-sandwich
- vimPlugins.vim-snippets
- vimPlugins.vim-textobj-variable-segment
- vimPlugins.vim-tpipeline
- vimPlugins.vim-twiggy
- vimPlugins.vim-unimpaired
- vimPlugins.vim-wakatime
- vimPlugins.vimade
- vimPlugins.vimtex
- vimPlugins.wilder-nvim
```

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 136130` at 56463492 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/8a5c8765f6c5957ce15c718b882ab943">vimPlugins.vim-colorschemes</a></li>
  </ul>
</details>
<details>
  <summary>110 packages built successfully:</summary>
  <ul>
    <li>spacevim</li>
    <li>tests.vim.test_vim_with_vim_nix</li>
    <li>tests.vim.test_vim_with_vim_nix_using_plug</li>
    <li>vimPlugins.Coqtail</li>
    <li>vimPlugins.LeaderF</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.auto-session</li>
    <li>vimPlugins.bufferline-nvim</li>
    <li>vimPlugins.chadtree</li>
    <li>vimPlugins.cmp-buffer</li>
    <li>vimPlugins.cmp-calc</li>
    <li>vimPlugins.cmp-emoji</li>
    <li>vimPlugins.cmp-nvim-lsp</li>
    <li>vimPlugins.cmp-nvim-lua</li>
    <li>vimPlugins.cmp-path</li>
    <li>vimPlugins.cmp-vsnip</li>
    <li>vimPlugins.cmp_luasnip</li>
    <li>vimPlugins.coc-lua</li>
    <li>vimPlugins.compe-tmux</li>
    <li>vimPlugins.denite-nvim</li>
    <li>vimPlugins.deol-nvim</li>
    <li>vimPlugins.deoplete-fish</li>
    <li>vimPlugins.deoplete-khard</li>
    <li>vimPlugins.deoplete-nvim</li>
    <li>vimPlugins.edge</li>
    <li>vimPlugins.feline-nvim</li>
    <li>vimPlugins.formatter-nvim</li>
    <li>vimPlugins.friendly-snippets</li>
    <li>vimPlugins.fugitive-gitlab-vim</li>
    <li>vimPlugins.gentoo-syntax</li>
    <li>vimPlugins.git-worktree-nvim</li>
    <li>vimPlugins.gitsigns-nvim</li>
    <li>vimPlugins.glow-nvim</li>
    <li>vimPlugins.gruvbox-material</li>
    <li>vimPlugins.gruvbox-nvim</li>
    <li>vimPlugins.gv-vim</li>
    <li>vimPlugins.indent-blankline-nvim</li>
    <li>vimPlugins.kommentary</li>
    <li>vimPlugins.lightspeed-nvim</li>
    <li>vimPlugins.lir-nvim</li>
    <li>vimPlugins.lsp_signature-nvim</li>
    <li>vimPlugins.luasnip</li>
    <li>vimPlugins.lush-nvim</li>
    <li>vimPlugins.mattn-calendar-vim</li>
    <li>vimPlugins.minimap-vim</li>
    <li>vimPlugins.ncm2-ultisnips</li>
    <li>vimPlugins.neco-vim</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neon</li>
    <li>vimPlugins.neorg</li>
    <li>vimPlugins.neoscroll-nvim</li>
    <li>vimPlugins.neovim-ayu</li>
    <li>vimPlugins.nterm-nvim</li>
    <li>vimPlugins.null-ls-nvim</li>
    <li>vimPlugins.nvim-autopairs</li>
    <li>vimPlugins.nvim-base16</li>
    <li>vimPlugins.nvim-cmp</li>
    <li>vimPlugins.nvim-compe</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-gps</li>
    <li>vimPlugins.nvim-highlite</li>
    <li>vimPlugins.nvim-hlslens</li>
    <li>vimPlugins.nvim-jdtls</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-notify</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-ts-rainbow</li>
    <li>vimPlugins.onedark-nvim</li>
    <li>vimPlugins.packer-nvim</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.rust-tools-nvim</li>
    <li>vimPlugins.sonokai</li>
    <li>vimPlugins.sql-nvim</li>
    <li>vimPlugins.symbols-outline-nvim</li>
    <li>vimPlugins.tagbar</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.toggleterm-nvim</li>
    <li>vimPlugins.traces-vim</li>
    <li>vimPlugins.ultisnips</li>
    <li>vimPlugins.vim-android</li>
    <li>vimPlugins.vim-capslock</li>
    <li>vimPlugins.vim-clap</li>
    <li>vimPlugins.vim-dadbod-completion</li>
    <li>vimPlugins.vim-dadbod-ui</li>
    <li>vimPlugins.vim-elixir</li>
    <li>vimPlugins.vim-flog</li>
    <li>vimPlugins.vim-fugitive</li>
    <li>vimPlugins.vim-git</li>
    <li>vimPlugins.vim-jinja</li>
    <li>vimPlugins.vim-lsp</li>
    <li>vimPlugins.vim-matchup</li>
    <li>vimPlugins.vim-mucomplete</li>
    <li>vimPlugins.vim-plug</li>
    <li>vimPlugins.vim-rhubarb</li>
    <li>vimPlugins.vim-sandwich</li>
    <li>vimPlugins.vim-snippets</li>
    <li>vimPlugins.vim-textobj-variable-segment</li>
    <li>vimPlugins.vim-tpipeline</li>
    <li>vimPlugins.vim-twiggy</li>
    <li>vimPlugins.vim-unimpaired</li>
    <li>vimPlugins.vim-wakatime</li>
    <li>vimPlugins.vimade</li>
    <li>vimPlugins.vimtex</li>
    <li>vimPlugins.wilder-nvim</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`configurePhase` should probably contain `runHook preConfigure` and `runHook postConfigure`.

Near pkgs/misc/vim-plugins/build-vim-plugin.nix:28:14:
```
   |
28 |       inherit unpackPhase configurePhase buildPhase addonInfo preInstall postInstall;
   |              ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/misc/vim-plugins/build-vim-plugin.nix:28:14:
```
   |
28 |       inherit unpackPhase configurePhase buildPhase addonInfo preInstall postInstall;
   |              ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by teto** [comment]
I've merged an update to generated.nix that requires you to rebase this PR sry.

**Comment by sestrella** [comment]
@teto no worries, I rebased the branch

**Comment by sestrella** [comment]
Got an error running `nix-shell -p nixpkgs-review --run "nixpkgs-review pr 136130"`  (after the rebase) I'll take a look later on today.

```
$ nix --experimental-features nix-command build --no-link --keep-going -f /Users/sestrella/.cache/nixpkgs-review/pr-136130-1/build.nix
error: builder for '/nix/store/wsll5i829x83c18r06h6lgf5l2rnrbm2-maple.drv' failed with exit code 1;
       last 10 log lines:
       >
       > ERROR: cargoSha256 is out of date
       >
       > Cargo.lock is not the same in maple-vendor.tar.gz
       >
       > To fix the issue:
       > 1. Use "0000000000000000000000000000000000000000000000000000" as the cargoSha256 value
       > 2. Build the derivation and wait for it to fail with a hash mismatch
       > 3. Copy the 'got: sha256:' value back into the cargoSha256 field
       >
       For full logs, run 'nix log /nix/store/wsll5i829x83c18r06h6lgf5l2rnrbm2-maple.drv'.
error: 1 dependencies of derivation '/nix/store/82y98qsg7dqd2cy48g0fnzvl5l2r92an-vimplugin-vim-clap-2021-08-30.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ygdc7hbf6a46q94md76xhp0b4v58437b-review-shell.drv' failed to build

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/136130

1 package failed to build:
vimPlugins.vim-clap
```

**Comment by teto** [comment]
you can drop the second commit. What's funny is that first commit contains changes unrelated to neon (it shouldn't), probably a bug in our update.py script there.

**Comment by sestrella** [comment]
@teto I dropped the `vimPlugins: update` commit and just leave the one related to `neon`, you are right I think the `update.py` script is not only adding a new plugin, but it also updates other existing plugins, this is the command I used locally:

```sh
GITHUB_API_TOKEN=<token> ./pkgs/misc/vim-plugins/update.py --add "rafamadriz/neon@main" --proc 2 --debug DEBUG
```

**Comment by sestrella** [comment]
Moving forward, It would be nice to let the script figure out the default branch by calling `GET /repos/{owner}/{repo}` first using the information provided by `--add "{owner}/{repo}`, I'm going to open an issue in order to star a discussion.

https://docs.github.com/en/rest/reference/repos#get-a-repository--code-samples

**Comment by teto** [comment]
it passes nixpkgs-review. Now we have to be careful for the next vimPlugins update round, if there is a vim-clap maintainer.

**Comment by figsoda** [comment]
vim-clap has a rust package specified in `overrides.nix` that needs to have its `cargoSha256` updated. `update.py` currently doesn't handle that so it needs to be manually updated

**Pull request merged**
