### PR TITLE
add new version unison(2.48.3)

### PR DESCRIPTION
**Pull request by shen390s**
add new version of unison(2.48.3)

### CODE REVIEW

**Comment by vcunat** [comment]
So, this is the version from master added as a separate version to 14.12? Hmm, I'm unsure ATM.

**Comment by shen390s** [comment]
I have not checked with master but it seems the same as master

**Comment by vcunat** [comment]
I don't really see a reason to push such changes to 14.12 now, as it's no longer maintained except for severe security fixes after 15.09 got out, and that one does contain unison-2.48.3.

**Comment by vcunat** [comment]
I hope you don't mind much.

**Pull request closed without merging**
