### PR TITLE
nixos-container: use systemd-run instead of nsenter

### LINKED ISSUE #30019: nixos-container should use systemd-run -M <machine>
## Issue description

Currently nixos-container.pl uses `nsenter` to attach to containers.
However this methods miss out some container context and does not create a pseudo tty.
`systemd-run -M <container> --pty` is the offical method recommended by upstream: https://github.com/systemd/systemd/issues/4215
Previous there was an attempt to use `machinectl shell`, which does not return the exit code.

cc @wlhlm

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

### PR DESCRIPTION
**Pull request by uvNikita**
###### Motivation for this change
This is the first step for unprivileged nixos containers support.
Fixes #30019. See also #18825, #57083, and #67130.

@Mic92 I see you commented about `--pty` and `--pipe` options in #30019. I'm not sure if I should add it here or not.
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @danbst @mmahut @Mic92

### CODE REVIEW

**Comment by arianvp** [comment]
Looks good to me

**Review by fpletz — APPROVED** [review]
Verified that the behaviour is the same and now running all container tests. Will merge after they have passed. Thanks a lot! :+1:

**Comment by veprbl** [comment]
There is an issue reported to be caused by this: https://github.com/NixOS/nixpkgs/issues/72407#issuecomment-573540906
Could you, please, check?

**Comment by Ma27** [comment]
@fpletz @veprbl @arianvp @uvNikita this breaks the `container`-backend of `nixops` (and probably more): when deploying a container and running `switch-to-configuration` via `nixos-container run`, `systemd` will be reloaded (which seems to kill the `systemd-run` call) and causes a hanging command (at least when using `nixops`). I just confirmed locally that reverting this change fixes the issue.

Please also note that this isn't in the `nixos-19.09` tree although it's in the 19.09 milestone.

As this is an actual regression, I'd love to see this resolved before releasing 20.03 (cc @worldofpeace @disassembler). I can currently think of two solutions:

* Reverting the entire commit (at least for 20.03) and finding a better solution for 20.09
* Adding some kind of `--no-systemd` flag to `nixos-container run` which uses the old `nsenter` approach.

Any further ideas?

**Comment by worldofpeace** [comment]
@Ma27 Awesome that your so on top of this stuff. I suggest a revert would be best, we're cutting it very close.

**Comment by Ma27** [comment]
Opened #83392 which reverts this on `release-20.03`. Before merging this, I'd love to see some feedback of the original author and reviewers though :)

**Pull request merged**
