### PR TITLE
boot: Update to 2.2.0

### PR DESCRIPTION
**Pull request by ragnard**
Update to latest release.

### CODE REVIEW

**Comment by ragnard** [comment]
Hold off this one for a while. Looks like 2.2.0 might be a little bit broken currently.

**Comment by ragnard** [comment]
Changed sha to reflect upstream updates. Good to go now.

**Comment by jagajaga** [comment]
Please rename commit's name according our guide in `CONTRIBUTING.md`.

**Comment by ragnard** [comment]
@jagajaga Done, I believe.

**Pull request merged**
