### PR TITLE
teamviewer: Build with latest qt5

### PR DESCRIPTION
**Pull request by adisbladis**
###### Motivation for this change
See https://github.com/NixOS/nixpkgs/issues/33798

Seems to work fine for me though I haven't tested connecting to anyone as I don't use teamviewer myself.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @jagajaga

### CODE REVIEW

**Comment by worldofpeace** [comment]
There was reports of segfaults with latest `qt5` https://github.com/NixOS/nixpkgs/pull/53117
See also https://github.com/NixOS/nixpkgs/pull/54259#issuecomment-455487075.

So this should be tested by an actual user.

**Comment by adisbladis** [comment]
Ping @jagajaga

**Comment by Ma27** [comment]
Would you mind having a look at #67244? This bumps teamviewer to the latest version and wraps QT properly. Also didn't encounter any issues with the new teamviewer version :)

**Comment by worldofpeace** [comment]
Superseded by https://github.com/NixOS/nixpkgs/pull/67244

**Pull request closed without merging**
