### PR TITLE
terraform-provider-keycloak: init at 1.20.0

### PR DESCRIPTION
**Pull request by eonpatapon**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by eonpatapon** [comment]
`terraform-provider-atlas` repo seems to have disappear.

tested the build of all providers (eg `nix-build -A terraform-providers`)

**Comment by flokli** [comment]
This needs a rebase, as a lot in `data.nix` has changed in the meantime.

Did you check if just adding it to `slugs` in `update-all`, and treating it like most other providers works?

**Comment by eonpatapon** [comment]
@flokli rebased and used the latest version

It can't be added to `data.nix` as the repo doesn't contain it's dependencies like the others. Also it's using go modules.

**Comment by flokli** [comment]
```
4 packages built:
terraform-full terraform-providers.keycloak terraform_0_11-full terragrunt
```

**Pull request merged**
