### PR TITLE
python3Packages.cryptography: 3.4.2 -> 36.0.0

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change
https://github.com/pyca/cryptography/blob/36.0.0/CHANGELOG.rst#3600---2021-11-21

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by primeos** [comment]
How well is this tested? Last time you noticed that this breaks a few packages and we had to revert it: https://github.com/NixOS/nixpkgs/pull/140024#issuecomment-939403187

Hopefully the situation improved in the meantime but I wouldn't be surprised if there are some breakages left. My plan was to run a full nixpkgs-review on Python packages but unfortunately I didn't get around to it yet as it requires a lot of disk space (and time). Or someone monitors Hydra for regressions.

**Comment by mweinelt** [comment]
I didn't test this, I just prepared this now that home-assistant depends on it. Currently in the process of updating home-assistant, so both my attention and compute are exhausted.

**Comment by risicle** [comment]
`sslyze` needs some requirements hacking:

```
ERROR: Could not find a version that satisfies the requirement cryptography<4.0,>=2.6 (from sslyze) (from versions: none)
ERROR: No matching distribution found for cryptography<4.0,>=2.6
```

**Comment by mweinelt** [comment]
@veehaitch Would you mind looking into bumping sslyze and nassl? The latter fails because of known vulnerabilities.

**Comment by risicle** [comment]
Have built a lot of depending packages on 3 platforms (macos 10.15, nixos x86_64 & aarch64) and that's the only issue I've been able to find. Think it's probably good enough for staging.

**Review by risicle — APPROVED** [review]

**Comment by risicle** [comment]
Oh, including `mitmproxy` and `fido2`.

**Pull request merged**
