### PR TITLE
 libreoffice: add zh-CN language support 

### PR DESCRIPTION
**Pull request by bobby285271**
###### Motivation for this change

Add zh-CN language support for Libreoffice

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vcunat** [comment]
You didn't test it works well, right?

**Comment by bobby285271** [comment]
I was ashamed to admit that I didn' t test that...😂 But I really need it...

**Comment by vcunat** [comment]
No need to be ashamed.  I assume you don't have enough resources for the build.

I've wanted to add Czech for some time, so let me test it with both.  (I don't know Chinese at all, but I'll see if it runs and shows Chinese-like chars.)

**Review by vcunat — APPROVED** [review]
The default version looks good.

**Pull request merged**
