### PR TITLE
flutter326: init at 3.26.0-0.1pre

### PR DESCRIPTION
**Pull request by RossComputerGuy**
## Things done

New prerelease Flutter, need it for some work I'm doing that relies on this engine PR https://github.com/flutter/engine/pull/54575.

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by RossComputerGuy** [comment]
No, it should be pointing to beta because we fetched it under the beta channel.

**Comment by FlafyDev** [comment]
> No, it should be pointing to beta because we fetched it under the beta channel.

oh awesome

I tried using `flutter326` but can't create a project or build anything. is this an issue?

```
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel [user-branch], 0.0.0-unknown, on NixOS 24.11 (Vicuna) 6.6.52, locale en_IL)
    ! Flutter version 0.0.0-unknown on channel [user-branch] at
      /nix/store/8wjfnk3yggfhq8agys9hbg4r771qf18w-flutter-wrapped-3.26.0-0.1.pre-sdk-links
(...)
```

```
❯ flutter build linux --release
Resolving dependencies... 
Note: leak_tracker_flutter_testing is pinned to version 3.0.8 by flutter_test from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.

The current Flutter SDK version is 0.0.0-unknown.

Because every version of flutter_test from sdk depends on leak_tracker_flutter_testing >=2.0.3 which requires
  Flutter SDK version >=3.18.0-18.0.pre.54, flutter_test from sdk is forbidden.
So, because fluttertestproj depends on flutter_test from sdk, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Try using the Flutter SDK version: 3.24.3. 
Failed to update packages.
```

seems like it doesn't know the version of the sdk so it can't resolve dependencies

**Comment by RossComputerGuy** [comment]
The version JSON file gets messed up in the wrapper.

**Comment by RossComputerGuy** [comment]
Ok, this should work now that the version file isn't being used from the prepared artifacts.

**Comment by RossComputerGuy** [comment]
Tested this and it works, artifact hashes got messed up so I'll fix those.

**Review by FlafyDev — APPROVED** [review]
LGTM

can't really nixpkgs-review rn because of limited storage. but I tried relevant packages and everything seems to work 👍

**Comment by RossComputerGuy** [comment]
Well, we'll just merge and see what happens.

**Pull request merged**
