### PR TITLE
xsimd: Fix all test failures on all platforms

### PR DESCRIPTION
**Pull request by doronbehar**
Some tests fail on some platforms, and now every patch disables 1 test.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by doronbehar** [comment]
@ofborg build xsimd

**Comment by doronbehar** [comment]
@ofborg build pkgsMusl.xsimd

**Comment by doronbehar** [comment]
@ofborg build pkgsMusl.xsimd xsimd

**Comment by doronbehar** [comment]
@ofborg build pkgsMusl.xsimd xsimd

**Comment by doronbehar** [comment]
A single test fails in `pkgsMusl.diffutils` (`test-init.sh`) on aarch64-linux... Interesting, but unrelated.

**Comment by yu-re-ka** [comment]
aarch64-linux musl is entirely broken due to outdated bootstrap binaries

**Review by yu-re-ka — APPROVED** [review]

**Comment by yu-re-ka** [comment]
@vcunat this will cause a rebuild of xsimd for darwin in staging-next; is that okay?

**Comment by doronbehar** [comment]
I don't think we have a choice, because the scipy for darwin requires that xsimd update, and this xsimd update requires those patches and these patches trigger the darwin rebuild.

**Comment by yu-re-ka** [comment]
Right, aarch64-darwin was still broken after #246200

**Comment by doronbehar** [comment]
Let's give @risicle a few hours to tell us if they can test this on a aarch64-darwin and if not, I am ready to take the risk and merge this, as I'm fairly confident.

**Comment by yu-re-ka** [comment]
Built xsimd on aarch64-darwin 🎉

**Comment by yu-re-ka** [comment]
```
=========================== short test summary info ============================
ERROR lib/python3.10/site-packages/scipy/datasets/tests/test_data.py::TestDatasets::test_existence_all - OSError: [Errno 30] Read-only file system: '/homeless-shelter'
ERROR lib/python3.10/site-packages/scipy/datasets/tests/test_data.py::TestDatasets::test_ascent - OSError: [Errno 30] Read-only file system: '/homeless-shelter'
ERROR lib/python3.10/site-packages/scipy/datasets/tests/test_data.py::TestDatasets::test_face - OSError: [Errno 30] Read-only file system: '/homeless-shelter'
ERROR lib/python3.10/site-packages/scipy/datasets/tests/test_data.py::TestDatasets::test_electrocardiogram - OSError: [Errno 30] Read-only file system: '/homeless-shelter'
= 41984 passed, 2839 skipped, 135 xfailed, 10 xpassed, 4655 warnings, 4 errors in 110.83s (0:01:50) =

**Comment by vcunat** [comment]
So hopefully add this one?  https://github.com/NixOS/nixpkgs/pull/246152/commits/9b5c34b739cbd9d4d92e2cc7785d9b5724c2a6de

**Comment by yu-re-ka** [comment]
staging-next with this and 9b5c34b739cbd9d4d92e2cc7785d9b5724c2a6de cherry-picked can build scipy on aarch64-darwin

**Pull request merged**
