### PR TITLE
discord 0.0.26 -> 0.0.27

### PR DESCRIPTION
**Pull request by daemonspudguy**
Since no one else is gonna merge this change from master, here's a PR.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Scrumplex** [comment]
Could you redo the commit by cherry-picking the original, instead of creating a new one?

See https://nixos.org/manual/nixpkgs/stable/#submitting-changes-stable-release-branches-manual-backports

**Comment by daemonspudguy** [comment]
It's been cherrypicked.

**Comment by OPNA2608** [comment]
`nixos-*` branches are automation-driven, if the change is on master then please just wait. It'll find its way to unstable eventually: https://nixpk.gs/pr-tracker.html?pr=230427

**Comment by daemonspudguy** [comment]
And discord is one of those programs that is 100% non-functional without updates. That's why I made this PR.

**Comment by Scrumplex** [comment]
> And discord is one of those programs that is 100% non-functional without updates. That's why I made this PR.

Nixpkgs ships with a script that should work around that though: https://github.com/NixOS/nixpkgs/blob/11a10a9c49cecb543a9dfe57f2dd2c9b75d93ad6/pkgs/applications/networking/instant-messengers/discord/disable-breaking-updates.py

**Comment by daemonspudguy** [comment]
And it didn't work. I had to add the master branch to my flake to get Discord to work again.

**Comment by daemonspudguy** [comment]
Again, I wouldn't have made this PR if I didn't have Discord stop working.

**Comment by OPNA2608** [comment]
Please check if the wrapper script reports anything on your side if you run `Discord` from a terminal. If your `~/.config/discord/settings.json` is malformed, you might have to fix it yourself. Using 0.0.26 works fine for me, as long as the settings file is correct.
```
↪ Discord 
[Nix] Disabling updates already done
Discord 0.0.26
Starting app.
```

**Comment by daemonspudguy** [comment]
I added the master branch of nixpkgs to my flake.nix file, specifically to upgrade Discord. I'm not downgrading it.

**Comment by OPNA2608** [comment]
The `nixos-unstable` channel has now advanced enough to pick up the Discord bump.

image

image

**Pull request closed without merging**
