### PR TITLE
starship: 1.3.0 -> 1.5.4

### PR DESCRIPTION
**Pull request by Lyndeno**
###### Description of changes

Update starship to [1.5.4](https://github.com/starship/starship/releases/tag/v1.5.4)

starship 1.5.4 uses ```available_parallelism```, which was stabilized in [Rust 1.59.0](https://blog.rust-lang.org/2022/02/24/Rust-1.59.0.html), thus this is a draft until rustc is updated in nixpkgs.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Lyndeno** [comment]
Needs #164352 to undraft.

**Comment by kidonng** [comment]
Please bump to https://github.com/starship/starship/releases/tag/v1.5.4 next time you update.

**Comment by Lyndeno** [comment]
Just waiting on #161726 to reach master.

https://nixpk.gs/pr-tracker.html?pr=161726

**Review by danth — APPROVED** [review]

**Comment by msfjarvis** [comment]
Result of `nixpkgs-review pr 164345` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>starship</li>
  </ul>
</details>

**Comment by alyssais** [comment]
Rust 1.59.0 is now in master.  (In future, you can just PR stuff like this to whichever branch the Rust upgrade has made it to.  That way it can be merged early and will become available in master as soon as the Rust update is.)

**Comment by Lyndeno** [comment]
Can anyone build and test this? I do not have access to a Nix installation at the moment to test.

**Comment by msfjarvis** [comment]
Result of `nixpkgs-review pr 164345` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>starship</li>
  </ul>
</details>

**Review by danth — APPROVED** [review]

**Comment by happysalada** [comment]
alright, having a go at it here https://github.com/NixOS/nixpkgs/pull/168014

**Pull request closed without merging**
