### PR TITLE
trilium-desktop: remove duplicate desktop item

### PR DESCRIPTION
**Pull request by eliandoran**
###### Motivation for this change

It appears that the Trilium Desktop application creates its own desktop icon each time the application starts. This is in contrast with the `.desktop` file which is already created by the package itself.

The `.desktop` file created by the application is not actually working, as it has the wrong `Exec` value.

###### Things done

Considering that the application creating its own icon in `~/.local/share/applications` is also a seemingly strange behavior, a patch was done to no longer create the desktop item at start-up.

The application will still have the desktop item of the package.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by FliegendeWurst — CHANGES_REQUESTED** [review]
This won't work because the package doesn't build Trilium from source (you applied the patch to the server application).

**Comment by eliandoran** [comment]
> This won't work because the package doesn't build Trilium from source (you applied the patch to the server application).

You're absolutely right. Strangely enough, it worked when testing it. Perhaps the patch is not needed at all anymore.
I'll check and come back with an answer.

**Comment by eliandoran** [comment]
@FliegendeWurst , you were right about applying the patch incorrectly. I used another approach where I extract the `.asar` archive where the source code is, apply the patch there and pack it back in. It appears to be working, in the sense that there is no longer a shortcut created by the `trilium` desktop application in `~/.local/share/applications`.

**Review by FliegendeWurst — APPROVED** [review]
Works as expected

**Comment by FliegendeWurst** [comment]
BTW this change finally fixes #76567 :)

**Comment by Myaats** [comment]
Superseded by #204680, it takes advantage of a new check and does not involve patching the asar archive.

**Pull request closed without merging**
