### PR TITLE
doc: improve 20.09 release notes

### PR DESCRIPTION
**Pull request by davidak**
###### Motivation for this change

the release notes had the same issue as mentioned in https://github.com/NixOS/nixos-homepage/pull/619#discussion_r512932899

cc @jonringer 

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by davidak** [comment]
I was unable to edit the Backward Incompatibilities and Other Notable Changes sections since adding a `<br />` to the text let the whole thing explode.

```
[davidak@gaming:~/code/nixpkgs]$ nix-build nixos/release.nix -A manual.x86_64-linux
these derivations will be built:
  /nix/store/1nly4qw4472mrc04dxfkkr9nwcvsf09n-options-docbook.xml.drv
  /nix/store/bvh9radbcynq2vwv8vldr1chn2bkbhch-generated-docbook.drv
  /nix/store/2brvdhbwy8yasagk2hrpv82id1d1b3pj-nixos-manual-combined.drv
  /nix/store/pafbf1k4nq2hbrb9w5gawqzzf3ghmsqk-manual-olinkdb.drv
  /nix/store/7ryxaplv8m3z25v4y7h6w4hydbnca0rj-nixos-manual-html.drv
building '/nix/store/1nly4qw4472mrc04dxfkkr9nwcvsf09n-options-docbook.xml.drv'...
building '/nix/store/bvh9radbcynq2vwv8vldr1chn2bkbhch-generated-docbook.drv'...
building '/nix/store/2brvdhbwy8yasagk2hrpv82id1d1b3pj-nixos-manual-combined.drv'...

manual-combined.xml:85624: element itemizedlist: Relax-NG validity error : Expecting an element listitem, got nothing
 85620      <para>
 85621         Services:
 85622      </para>
 85623      <itemizedlist>
 85624       <listitem>
 85625        <para>
 85626         <xref linkend="opt-services.ankisyncd.enable"/> Anki sync server

manual-combined.xml:85162: element section: Relax-NG validity error : Did not expect element section there
 85158    This section lists the release notes for each stable version of NixOS and
 85159    current unstable revision.
 85160   </para>
 85161   <section xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xi="http://www.w3.org/2001/XInclude" version="5.0" xml:id="sec-release-21.03">
 85162   <title>Release 21.03 (&#x201C;Okapi&#x201D;, 2021.03/??)</title>
 85163
 85164   <section xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xi="http://www.w3.org/2001/XInclude" version="5.0" xml:id="sec-release-21.03-highlights">

manual-combined.xml:85162: element section: Relax-NG validity error : Element appendix has extra content: section
 85158    This section lists the release notes for each stable version of NixOS and
 85159    current unstable revision.
 85160   </para>
 85161   <section xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xi="http://www.w3.org/2001/XInclude" version="5.0" xml:id="sec-release-21.03">
 85162   <title>Release 21.03 (&#x201C;Okapi&#x201D;, 2021.03/??)</title>
 85163
 85164   <section xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xi="http://www.w3.org/2001/XInclude" version="5.0" xml:id="sec-release-21.03-highlights">

manual-combined.xml:3: element info: Relax-NG validity error : Element book has extra content: info
     1  <?xml version="1.0"?>
     2  <book xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xi="http://www.w3.org/2001/XInclude" version="5.0" xml:id="book-nixos-manual">
     3   <info>
     4    <title>NixOS Manual</title>
     5    <subtitle>Version 21.03
     6    </subtitle>
     7   </info>

manual-combined.xml fails to validate
builder for '/nix/store/2brvdhbwy8yasagk2hrpv82id1d1b3pj-nixos-manual-combined.drv' failed with exit code 3
cannot build derivation '/nix/store/7ryxaplv8m3z25v4y7h6w4hydbnca0rj-nixos-manual-html.drv': 1 dependencies couldn't be built
error: build of '/nix/store/7ryxaplv8m3z25v4y7h6w4hydbnca0rj-nixos-manual-html.drv' failed
```

**Comment by jonringer** [comment]
I saw https://github.com/NixOS/nixpkgs/pull/101871 first, do you mind rebasing

**Comment by davidak** [comment]
@jonringer done

**Comment by jonringer** [comment]
thanks!

**Pull request merged**
