### PR TITLE
travis-ci: don’t merge prs

### PR DESCRIPTION
**Pull request by matthewbauer**
Travis has a frustrating habit of wanting to merge PRs into master. This is
fine when Nixpkgs is working 100% but that means that when master is failing
the PR is also failing (even though the PR author has literally no control over
master). This is a solution that I think will work out better for everybody.

First, ```nox-review pr``` has a new option called ```--no-merge```  that will mean that
nox-review won’t try to merge PRs into master. Note that Nox was updated in
94400c0. To prevent Travis from breaking, please verify that this is in
nixpkgs-unstable. You can verify with,

```sh
rev=$(git ls-remote https://github.com/nixos/nixpkgs-channels refs/heads/nixpkgs-unstable | awk '{print $1}')
if git merge-base --is-ancestor 94400c0 $rev; then
  echo ok to merge
else
  echo do not merge
fi
```

Second, the Travis CI script will now check out the HEAD commit of the PR (which
the author can actually change) instead of the MERGE commit.

Together, these changes should mean that PR authors are only responsible for
their own HEADs. This may solve some potential problems but also means PR
authors should start carrying about what is actually in HEAD. Basically, you
should branching off of a working version of Nixpkgs. This should probably be a
commit of something that has gone through Hydra testing like ```nixpkgs-17.09-darwin``` or
```nixos-17.09```. At the very least you should branch off of nixpkgs-unstable unless
you absolutely need something that has been touched since then! (in that case
just branch off of the latest working commit). Basic idea, do NOT blindly branch
off of nixpkgs/master!

This is a preliminary note I’ve made that should probably be included somewhere.
I’ll probably make a mailing list request. Note to PR authors:

> For Travis CI to succeed, you need to pay attention to what Nixpkgs commit you
branched off of. Because Nixpkgs is huge, Travis CI needs the binary cache to be
available, so you need to make sure your base commit has entered the binary
cache. It is recommended that you use nixpkgs-unstable or nixos-unstable as a
base.

The following commands will set this up for you,

```shell
git remote add https://github.com/nixos/nixpkgs-channels nixpkgs-channels
git fetch nixpkgs-channels nixpkgs-unstable
```

and to create a new branch,
```shell
git checkout -b YOUR_BRANCH_NAME nixpkgs-channels/nixpkgs-unstable
```

or if you have already create a branch,
```shell
git rebase nixpkgs-channels/nixpkgs-unstable
```

> Make sure you still merge into nixpkgs master! If there are merge conflicts with
master, you will still need to resolve them.

Testing for Travis is always difficult so I really can't know how well this works until this PR is opened.

### CODE REVIEW

**Comment by ThomasMader** [comment]
It might make sense to add a delay to the start of the travis-ci PR run because it seems many people including me commit something and a few minutes later realize that there still needs to be done something and force push again. Even this PR created three build runs. (https://travis-ci.org/NixOS/nixpkgs/builds/276596580, https://travis-ci.org/NixOS/nixpkgs/builds/276601311 and https://travis-ci.org/NixOS/nixpkgs/builds/276602831)
It seems that the CI system gets stressed out too much because of this for no good reason.
If one would add a delay of say 30 to 60 minutes, many of the builds would vanish and the overall time should go down drastically.
Even better would be if an old build run could be canceled before a new one is created.

**Comment by matthewbauer** [comment]
> It might make sense to add a delay to the start of the travis-ci PR run because it seems many people including me commit something and a few minutes later realize that there still needs to be done something and force push again

We're pretty much confined to how Travis works. As soon as a commit is pushed to a either a branch or an open PR, it starts a 50 minute timer that we get to build something. Travis basically sets these rules and we have to follow them. One thing you can do, though, is set up Travis for your Nixpkgs fork and get better response times because Travis sets quotas per-repo.

Update:

I don't know who has admin permissions on Travis but turning this on might be a little helpful:

```
Auto Cancellation allows you to only run builds for the latest commits in the queue. This setting can be applied to builds for Branch builds and Pull Request builds separately. Builds will only be canceled if they are waiting to run, allowing for any running jobs to finish.
```

**Comment by fpletz** [comment]
I've enabled Auto Cancellation for Pull Requests on Travis since I seem to have the permission somehow. :panda_face: 

As far as this PR is concerned I'm undecided. It would certainly be better to test with the merged changes because this will ultimately happen. The committer could have have based his PR on an old commit from master.

**Comment by matthewbauer** [comment]
> It would certainly be better to test with the merged changes because this will ultimately happen. The committer could have have based his PR on an old commit from master.

I guess my hope is that Hydra would pick these up. We get ~50 minutes of free CPU time to evaluate a PR with Travis. We're never going to be as thorough as Hydra so let's just use it as a kind of smoke test on PRs. As a rule, aim for 0 false negatives on Travis and 0 false positives on Hydra.

**Comment by peterhoeg** [comment]
I typically work against unstable to have as much already compiled as possible. Then I rebase against master and push that or alternatively cherry-pick the commits if rebase fails. I was under the impression that that was the "Best Practice (tm)".

**Comment by matthewbauer** [comment]
> I typically work against unstable to have as much already compiled as possible. Then I rebase against master and push that or alternatively cherry-pick the commits if rebase fails.

I don't think you really need to rebase on master unless there's a merge conflict (which GitHub should tell you). I'm really not sure if there is a best practice yet, but we probably should have one. I'd suspect almost everyone just bases off of master which I would say is a bad practice.

**Comment by ThomasMader** [comment]
> We're pretty much confined to how Travis works. As soon as a commit is pushed to a either a branch or an open PR, it starts a 50 minute timer that we get to build something. Travis basically sets these rules and we have to follow them. One thing you can do, though, is set up Travis for your Nixpkgs fork and get better response times because Travis sets quotas per-repo.

https://blog.travis-ci.com/2013-08-21-abort-mission-cancel-running-builds/ says it's possible via their console client.
Something like the following should be possible I think but I just skipped over their API and don't have any experience with Travis. (https://docs.travis-ci.com/api/#builds)

- A new commit is pushed as PR and it is checked if there are already waiting PR builds
- If so the job isn't gonna be created but stored in unknownPlaceQueue (The question is where)
  If there is another build in unknownPlaceQueue with the same PR number the old one is replaced by the new one.
- The next time a push comes in the check releases/starts the oldest PRs from the unknownPlaceQueue till there is one waiting PR build on Travis

This is very rough but should be sufficient to get the idea.

**Comment by primeos** [comment]
### From the ML:

> Often it won't be able to finish in time, thus failing, causing the contributor to think they might have done something wrong.

We could prevent this by running something like the following:
```bash
timeout 45m ./maintainers/scripts/travis-nox-review-pr.sh $TARGETS \
  || if [[ $? -eq 124 ]]; then (>&2 echo "Timeout"); fi
```

But a drawback would be that this could produce successful (green) CI builds that might fail after the timeout (except there's a special exit code that we could use).

### Regarding the PR:

Imho this might make it more complicated for new contributors to submit PRs and is prone to human error.

Another solution could be to extract the changes of a PR (i.e. the changes/commits show by GitHub) and cherry-pick them onto `channels/nixpkgs-unstable`. We could e.g. get these changes by specifying the following range: `^origin/master HEAD` (commits reachable from `HEAD` without the ones reachable from `origin/master`, where HEAD is the most recent commit of that PR and `origin` points to this repository). That should improve the build-time and reduce timeouts since most/all dependencies should be available from the binary cache but compared to the approach from @matthewbauer this has the disadvantage that the author of an PR doesn't have a direct control over the HEAD of the CI build (i.e. the CI build will fail when `channels/nixpkgs-unstable` is currently failing). Additionally this will obviously fail when the commits can't be applied onto `channels/nixpkgs-unstable` which will cause problems when `channels/nixpkgs-unstable` lags behind (and I just noticed that it's currently 11 days behind which is too much imho...). We could try to improve this by using something like `origin/master@{yesterday}` instead.

Could this improve things or is it a bad idea?

**Comment by c0bw3b** [comment]
@matthewbauer @Mic92 I think this has become irrelevant after #31605

**Pull request closed without merging**
