### PR TITLE
ocamlPackages.tezos-lmdb: remove at 7.4

### PR DESCRIPTION
**Pull request by vbgl**
###### Motivation for this change

Current hash seems wrong.

cc maintainer @ulrikstrid

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ulrikstrid** [comment]
What's up with the hashes? Are every changing upstream? 

Sidenote: ligo updated to a later version of tezos so we can probably drop this specific package if we don't want to keep it

**Comment by prusnak** [comment]
@vbgl will you fix another PR which drops `tezos-lmdb` completely, please?

**Comment by vbgl** [comment]
I’ve amended the commit to remove the broken package.

**Comment by prusnak** [comment]
@ulrikstrid ack?

**Comment by ulrikstrid** [comment]
I can double check tomorrow, but it should be fine

**Comment by ulrikstrid** [comment]
It seems like `tezos-storage` still depends on this (I didn't know), but it also depends on i`rmin < 2.7.0` so I'm not sure how to handle it. We can remove the module and re-introduce it if I need it.

**Comment by vbgl** [comment]
May this be merged?

**Review by ulrikstrid — CHANGES_REQUESTED** [review]
Sadly I will still need this for LIGO even after the latest upgrades. We could remove it now but I'll have to re-add it soon.

I'm OK with removing it now since I'm still having other problems with the current version.

**Comment by ulrikstrid** [comment]
I have opened a large PR #134424 to update all of the Tezos packages to the latest release including fixing `tezos-lmdb`. I think we can close this PR and just concentrate our efforts there instead.

**Comment by prusnak** [comment]
Superseded by https://github.com/NixOS/nixpkgs/pull/134424

**Pull request closed without merging**
