### PR TITLE
 nix-zsh-completions: 0.3.8 -> 0.3.9 ,  nix-bash-completions: 0.6.5 -> 0.6.6 

### PR DESCRIPTION
**Pull request by hedning**
###### Motivation for this change

For ZSH this adds stuff like `nix-build channel:<tab>` and the new `--option`s to the legacy commands (this was already fixed for Bash).

Also a few bug fixes. For both shells this fixes a bug in darwin where completing attribute paths of urls would fail if the user hadn't installed `sha256sum` to the PATH (thanks to @LnL7).

Please backport to 18.03. 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by LnL7** [comment]
@GrahamcOfBorg build nix-bash-completions nix-zsh-completions

**Review by LnL7 — APPROVED** [review]
I was going to ask for a version bump. 😄

**Comment by LnL7** [comment]
Backported to 18.03 in e249e593778.

**Comment by hedning** [comment]
Thanks :) yeah, been putting it off for too long :slightly_frowning_face:

**Pull request merged**
