### PR TITLE
kanidm: 1.2.1 -> 1.2.3

### PR DESCRIPTION
**Pull request by bjornfor**
## Description of changes

* https://github.com/kanidm/kanidm/releases/tag/v1.2.2
* https://github.com/kanidm/kanidm/releases/tag/v1.2.3

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by adamcstephens** [comment]
x86_64
/nix/store/am741f9j9yix41qj8623djjvp8mmzx7m-vm-test-run-kanidm

aarch64
/nix/store/bspmnnz64kx2bf9arfzprkws6dfafii1-vm-test-run-kanidm

**Comment by Underknowledge** [comment]
Tryed to install Kanidm on 24.05 but I alway build from source (also failing)
out from Discord from @max-privatevoid 
seems like a build machine choked on it https://hydra.nixos.org/build/262381433#tabs-summary


```log
[1/0/12 built] building kanidm-1.2.3 (checkPhase):    Compiling orca v1.2.3 (/build/source/tools/orca)
[1/0/12 built] building kanidm-1.2.3 (checkPhase): warning: build failed, waiting for other jobs to finish...
[1/0/12 built] building kanidm-1.2.3 (checkPhase): warning: build failed, waiting for other jobs to finish...
error: builder for '/nix/store/6pwxbjl6makq9y88xjbh5fqisjc413gi-kanidm-1.2.3.drv' failed with exit code 101;
       last 10 log lines:
       >    Compiling orca v1.2.3 (/build/source/tools/orca)
       > thread 'main' panicked at cargo-auditable/src/rustc_wrapper.rs:101:39:
       > called `Option::unwrap()` on a `None` value
       > note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
       > error: could not compile `kanidmd_lib` (lib)
       > warning: build failed, waiting for other jobs to finish...
       > thread 'main' panicked at cargo-auditable/src/rustc_wrapper.rs:101:39:
       > called `Option::unwrap()` on a `None` value
       > note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
       > error: could not compile `kanidmd_lib` (lib test)
       For full logs, run 'nix log /nix/store/6pwxbjl6makq9y88xjbh5fqisjc413gi-kanidm-1.2.3.drv'.
error: 1 dependencies of derivation '/nix/store/mjnmhcz9b81c2db2ngi5wvr4lp1n8l96-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ldxgjb29njsp9csbkdk6zn451i8hzqsx-unit-kanidm.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/db3fqsp0k3vp99f7zadfckk46y4dxiwq-nixos-system-connix-24.05.20240611.47b604b.drv' failed to build
``` 

```
   Compiling kanidmd_lib_macros v1.2.3 (/build/source/server/lib-macros)
   Compiling orca v1.2.3 (/build/source/tools/orca)
thread 'main' panicked at cargo-auditable/src/rustc_wrapper.rs:101:39:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: could not compile `kanidmd_lib` (lib)
warning: build failed, waiting for other jobs to finish...
thread 'main' panicked at cargo-auditable/src/rustc_wrapper.rs:101:39:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: could not compile `kanidmd_lib` (lib test)
```

To little knowledge to say if this is a rust version thing or a application problem
https://github.com/kanidm/kanidm/tree/v1.2.3/tools/orca

**Comment by erictapen** [comment]
From what I can say, the build just times out after 3 hours? I think we'd need to set the timeout time higher here.

**Comment by adamcstephens** [comment]
There's nothing to change here. The hydra build was re-run and it took 27 minutes. <https://hydra.nixos.org/build/262381433#tabs-summary>

I also spoke with @Underknowledge and they were trying to build kanidm on a system with 8GB of memory, which likely isn't enough for this package.

**Pull request merged**
