### PR TITLE
release-lib: Cache cross nixpkgs evals too, and other fixes

### PR DESCRIPTION
**Pull request by Ericson2314**
###### Motivation for this change

This will help with release-cross.nix eval time. It also allowed me to
share code between the cross and native helpers.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peti** [comment]
This PR breaks the https://hydra.nixos.org/jobset/nixpkgs/haskell-updates job. It's evaluation is driven by  https://github.com/peti/ci/blob/master/haskell-nixpkgs.nix which has worked fine for years, but now I'm getting plenty of evaluation errors:

~~~
error: while evaluating 'setAttrByPath' at /home/simons/.nix-defexpr/lib/attrsets.nix:57:29, called from /home/simons/.nix-defexpr/lib/attrsets.nix:60:41:
while evaluating 'getAttrFromPath' at /home/simons/.nix-defexpr/lib/attrsets.nix:73:31, called from /home/simons/src/ci/haskell-nixpkgs.nix:28:72:
while evaluating 'attrByPath' at /home/simons/.nix-defexpr/lib/attrsets.nix:24:35, called from /home/simons/.nix-defexpr/lib/attrsets.nix:75:8:
value is a function while a set was expected, at /home/simons/.nix-defexpr/pkgs/top-level/release-lib.nix:12:6
~~~

**Comment by Ericson2314** [comment]
Sorry I thought I tested everything with `release.nix` and `release-cross.nix`. what you actually want is:
```
pkgsFor = pkgsForCross null
```
Which will allow for slightly better caching. I'll fix.

**Comment by peti** [comment]
Will you commit a fix soon? If not, then I'd prefer to revoke those breaking changes for the time being.

**Comment by Ericson2314** [comment]
@peti sorry my computer broke. Pushing in a moment.

**Comment by Ericson2314** [comment]
#49795 is the fix.

**Pull request merged**
