### PR TITLE
kde/plasma5: 5.24.0 -> 5.24.3

### PR DESCRIPTION
**Pull request by InternetUnexplorer**
###### Description of changes

Now that https://github.com/NixOS/nixpkgs/pull/158716 has landed in master, here's 5.24.3 which includes four weeks of bugfixes:
- https://kde.org/announcements/plasma/5/5.24.1
- https://kde.org/announcements/plasma/5/5.24.2
- https://kde.org/announcements/plasma/5/5.24.3

A few additional changes were required:
- Renamed `plasma-phone-components` to `plasma-mobile` in line with upstream; feedback would be appreciated here as I've never renamed a package before and I'm not sure if I did it correctly!
- Added `networkmanager-qt` as a build input for `plasma-mobile`
- Updated `kde-rounded-corners` to the latest release (`v0.1.1`) to fix an error when building against KWin ≥ 5.24.2

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by andrevmatos — APPROVED** [review]
I've been running this for some time, everything is running fine! I'm no maintainer, but this is a vote to get this approved.

**Review by K900 — APPROVED** [review]
Been running this since the staging merge, LGTM

**Comment by InternetUnexplorer** [comment]
Tiny change, the inputs for `plasma-mobile` seem to be carefully organized so I just pushed a change that moves `networkmanager-qt` up to the rest of the KDE stuff, everything else should still be the same :)

I'm also wondering if it would be a good idea to test the `plasma-mobile` stuff just to make sure it still works; this PR doesn't change much but some changes were required and I don't know how to test them aside from making sure that everything still builds.

**Review by drupol — APPROVED** [review]

**Comment by SuperSamus** [comment]
What do you think about #164451?

**Comment by drupol** [comment]
> What do you think about #164451?

Could be tackled in a PR after this one, I have the feeling that those two are not really related.
One PR is to update Plasma, the other is to enable power-profiles-daemon.

**Comment by peterhoeg** [comment]
@samueldr for the plasma mobile stuff

**Comment by peterhoeg** [comment]
Looks safe, let's get it in there.

**Pull request merged**
