### PR TITLE
sway: add postSessionCommands

### PR DESCRIPTION
**Pull request by Artturin**
###### Things done

tested with 
```
disabledModules = [ "programs/sway.nix" ];

imports = let
  pkgsArtturin = builtins.fetchTarball {
    url = "https://github.com/Artturin/nixpkgs/archive/e2cb7cc64376e79b5e3aa0205fef4802f12f7dc3.tar.gz";
    sha256 = "08npq9awcd5w296jminbrz63vv6r1h4y1hkz3a1ysa6qm0n2qvl9";
  };
in [
  (import "${pkgsArtturin}/nixos/modules/programs/sway.nix")
];

nixpkgs.overlays = let
    pkgsArtturin = pkgs.fetchFromGitHub {
    owner = "Artturin";
    repo = "nixpkgs";
    rev = "e2cb7cc64376e79b5e3aa0205fef4802f12f7dc3";
    sha256 = "08npq9awcd5w296jminbrz63vv6r1h4y1hkz3a1ysa6qm0n2qvl9";
  };
    sway-overlay = self: super: {
      sway = super.callPackage "${pkgsArtturin}/pkgs/applications/window-managers/sway/wrapper.nix" { };
    };
  in
  [
    sway-overlay 
  ];

  programs.sway = {
    enable = true;
    postSessionCommands = ''
      echo "a test" > /home/USER/ifexists-then-it-works
    '';
    wrapperFeatures.gtk = true;
  };
```

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Artturin** [comment]
Result of `nixpkgs-review pr 126313` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>sway</li>
    <li>waybar</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 126313` at e2cb7cc6 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package skipped due to time constraints:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>sway</li>
    <li>waybar</li>
  </ul>
</details>

**Comment by primeos** [comment]
Hm, I'm not really convinced (yet) that this is a good idea. Dropping `exec` should be fine but probably looks a bit strange in the process list (not a big deal but I'd prefer it if the wrapper process wouldn't stick around - then again the X11 wrapper also stays around, IIRC).

Anyway, what I'm missing are the use-cases for this. `extraSessionCommands` is already an optional helper but at least that one can be quite useful for environment variables, systemd logging, etc. The main example that you've provided is `systemctl --user stop graphical-session.target` but I'm not sure if that's ideal. Users should likely run that command before Sway exits (otherwise most of the user units that depend on that target have likely already crashed due to loosing access to the Wayland socket) and additionally `postSessionCommands` could cause unexpected issues when running multiple Sway instances (though this e.g. affects `extraSessionCommands` as well (although to a more limited extend, IMO) and is up to the users).

Possible alternatives are `.bash_profile` (etc.) and overriding the exit shortcut (the latter would also make it possible to run commands before exiting Sway).

I'd like to get some additional opinions on this.

**Comment by jonringer** [comment]
one ramification of remove the exec's is that bash will be the one to intercept signals. And this may not be desirable, as I've had orphaned processes in the past because this type of behavior

**Comment by Artturin** [comment]
can't think of uses for this rn
will reopen if there's interest

**Pull request closed without merging**
