### PR TITLE
spdlog: test & build shared library

### PR DESCRIPTION
**Pull request by drewrisinger**
###### Motivation for this change

https://github.com/gabime/spdlog/releases/tag/v1.8.0

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by drewrisinger** [comment]
Currently failing on ``waybar``.

**Comment by FlorianFranzen** [comment]
@drewrisinger Please bump the update to v1.8.1 and then I will take a look at the waybar issue.

**Comment by SuperSandro2000** [comment]
@drewrisinger The updates are already in master. Some of the other changes not. Could you update your PR to reflect that? Otherwise I will close it in a couple of weeks.

**Comment by drewrisinger** [comment]
@SuperSandro2000 done

**Comment by Mic92** [comment]
Result of `nixpkgs-review pr 97470` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>python37Packages.qasm2image</li>
    <li>python38Packages.qasm2image</li>
    <li>python39Packages.qasm2image</li>
  </ul>
</details>
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>gerbera</li>
    <li>python39Packages.qiskit</li>
    <li>python39Packages.qiskit-aer</li>
    <li>python39Packages.qiskit-aqua</li>
    <li>python39Packages.qiskit-ignis</li>
    <li>python39Packages.tiledb</li>
  </ul>
</details>
<details>
  <summary>21 packages built:</summary>
  <ul>
    <li>bear</li>
    <li>cloudcompare</li>
    <li>hal-hardware-analyzer</li>
    <li>lizardfs</li>
    <li>mtxclient</li>
    <li>nheko</li>
    <li>pdal</li>
    <li>python37Packages.qiskit</li>
    <li>python37Packages.qiskit-aer</li>
    <li>python37Packages.qiskit-aqua</li>
    <li>python37Packages.qiskit-ignis</li>
    <li>python37Packages.tiledb</li>
    <li>python38Packages.qiskit</li>
    <li>python38Packages.qiskit-aer</li>
    <li>python38Packages.qiskit-aqua</li>
    <li>python38Packages.qiskit-ignis</li>
    <li>python38Packages.tiledb</li>
    <li>spdlog (spdlog_1)</li>
    <li>spdlog_0</li>
    <li>tiledb</li>
    <li>waybar</li>
  </ul>
</details>

**Comment by Mic92** [comment]
Gerbera is also broken in master: https://hydra.nixos.org/build/131900140/nixlog/2
tilesdb is broken on master: https://hydra.nixos.org/build/131882622
and qiskit as well: https://hydra.nixos.org/build/131879057

**Pull request merged**
