### PR TITLE
kubernetes: 1.5.6 -> 1.6.6

### PR DESCRIPTION
**Pull request by LnL7**
###### Motivation for this change

The nixos test fails for me, both before an after these changes.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by NeQuissimus** [comment]
Should we maybe go to 1.7 directly?

**Comment by 0xABAB** [comment]
Are you aware of https://github.com/NixOS/nixpkgs/pull/25426? That seems to have received much more input from various people already.

**Comment by NeQuissimus** [comment]
We should indeed pool the work in one PR

**Comment by LnL7** [comment]
@0xABAB I missed that one. It contains some more improvements, but uses upstream images for the services instead of building from source.

**Comment by offlinehacker** [comment]
I'm closing this in favor of https://github.com/NixOS/nixpkgs/pull/25426

**Pull request closed without merging**
