### PR TITLE
Remove old OCaml versions.

### PR DESCRIPTION
**Pull request by Zimmi48**
###### Motivation for this change

OCaml is currently shipped in more than 10 versions on nixpkgs (which is quite original compared to the general policy in nixpkgs of maintaining very few versions). In particular, there are 4 version pre-OCaml 4 and only one broken package (Matita) and one very old version of Coq (8.3) depend on them. It seems like it is time for this clean-up.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Note that I am not sure if `nox-review wip` is enough to properly test this. I might have missed some stuff.

### CODE REVIEW

**Comment by Mic92** [comment]
It would be also interesting how many 4.0x versions we need. But I have not enough inside knowledge to decide that.

**Comment by Zimmi48** [comment]
@Mic92 I thought about going further and removing everything before 4.02 but I figured I would have more difficulties and I'd wait for feedback here before doing so.

**Comment by vbgl** [comment]
Please also remove matita. It has been broken for decades.

**Comment by Zimmi48** [comment]
OK

**Comment by Zimmi48** [comment]
The last commit was done quickly and is untested.

**Comment by Mic92** [comment]
There is an evaluation error still there according to ofBorg.

**Comment by Zimmi48** [comment]
Seems to have passed now.

**Pull request merged**
