### PR TITLE
KDE Plasma 5.7 and KDE Frameworks 5.24

### PR DESCRIPTION
**Pull request by vandenoever**
###### Motivation for this change

Upgrade to new versions of kde plasma and kde frameworks.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vandenoever** [comment]
Logged in and ran plasma fine. Tested some plasma settings, control panel, krunner.

The package kwayland moved from plasma to kde frameworks.

**Comment by vandenoever** [comment]
I'm not sure why the checks are failing.

**Comment by FRidh** [comment]
Great! It seems the hash of `i-score` is wrong. Now because you update some of its dependencies Nox tests whether `i-score` still builds but fails, becaus of the wrong hash. This is not your fault.

**Comment by FRidh** [comment]
I'm on low bandwidth currently, but tomorrow I'll test this PR.

**Comment by vandenoever** [comment]
@FRidh great, I have my typical usage pattern and this is a very larget update, so I cannot vouch for verything, but so far it's looking good.

**Comment by vandenoever** [comment]
The digital clock lays out wrong in the panel. It takes up a bit of width, but renders outside that.
This was already an issue in plasma 5.6. I wonder if other plasma users on nixos also see this.

**Comment by ttuegel** [comment]
@vandenoever What font do you use for the clock Plasmoid? I don't see this problem with Deja Vu Sans.

**Comment by vandenoever** [comment]
@ttuegel The digital clock widget is just text, so font is a prime suspect. However, a different font makes no difference. Also I've removed the entire panel and replaced it with a default panel. 
When the panel is on the left or right side of the screen, the characters scale well with the width of the panel.

**Comment by FRidh** [comment]
plasma-integration misses Breeze.

**Comment by vandenoever** [comment]
I can add breeze and breeze-icons as a dependency to plasma-integration.

I've not installed plasma-integration here, what is it for?

**Comment by FRidh** [comment]
One of my packages needed it, forgot which one.

Building all of KDE now with `nix-build -E 'with import <nixpkgs>{}; with pkgs; with stdenv.lib; builtins.filter isDerivation (builtins.attrValues kde5)' -I nixpkgs=.`

**Comment by vandenoever** [comment]
@FRidh can you tell me what the diff was that you added?

**Comment by FRidh** [comment]
@vandenoever actually, I haven't fixed it. I tried adding breeze but it would still fail.

**Comment by FRidh** [comment]
the kde5 module seems to need plasma-integration

**Comment by ttuegel** [comment]
`plasma-integration` is installed by default. It integrates the look-and-feel of Qt applications into the Plasma desktop.

**Comment by vandenoever** [comment]
@FRidh: the command-line option you give says calamares is marked as broken. How do you prevent it from considering calamares?

**Comment by FRidh** [comment]
Maybe you can use `--keep-going` or `-k`, I am not sure though.

**Comment by vandenoever** [comment]
@FRidh so you're not seeing that error? I've simply removed calameres from all-packages for testing.
Also disabled ark because it needs unrar which is non-free.

**Comment by FRidh** [comment]
I rebased your PR onto 65ac26e28a9191cb95410832e2272a1fe1d910e9 before I checked it. I didn't use the `-k` flag myself so that's probably why I didn't encounter any other issues.

Unless you absolutely not want to I suggest you enable building unfree software since `ark` is quite useful.

**Comment by vandenoever** [comment]
Is it possible to build ark without unrar automatically if nonfree software is disabled?
Not building it because there's no unrar seems harsh.

**Comment by FRidh** [comment]
@vandenoever I suppose you could update the ark expression with somethng like
```
propagatedBuildInputs = [ ... ] ++ stdenv.lib.optionals config.allowUnfree [ unzip zip ]
```

**Comment by vandenoever** [comment]
I've added plasma-qt5 as dependency to plasma-integration. I can now build all that depends on plasma and frameworks, including ark.

**Comment by FRidh** [comment]
I just checked out 411e59c, rebased onto 65ac26e28a9191cb95410832e2272a1fe1d910e9 and ran 
```
nix-build -E 'with import <nixpkgs>{}; with pkgs; with stdenv.lib; builtins.filter isDerivation (builtins.attrValues kde5)' -I nixpkgs=.
```
Calamares seems to fail:
```
[ 23%] Generating nl-plasmanetworkmanagement_sshui.gmo
[ 23%] Generating nl-plasmanetworkmanagement_pptpui.gmo
/tmp/nix-build-calamares-1.0.drv-0/calamares-dabfb68/src/libcalamaresui/utils/YamlUtils.cpp: In function 'QVariant CalamaresUtils::yamlToVariant(const YAML::Node&)':
/tmp/nix-build-calamares-1.0.drv-0/calamares-dabfb68/src/libcalamaresui/utils/YamlUtils.cpp:46:42: error: 'yamlScalarToVariant' was not declared in this scope
         return yamlScalarToVariant( node );
                                          ^
/tmp/nix-build-calamares-1.0.drv-0/calamares-dabfb68/src/libcalamaresui/utils/YamlUtils.cpp:49:44: error: 'yamlSequenceToVariant' was not declared in this scope
         return yamlSequenceToVariant( node );
                                            ^
/tmp/nix-build-calamares-1.0.drv-0/calamares-dabfb68/src/libcalamaresui/utils/YamlUtils.cpp:52:39: error: 'yamlMapToVariant' was not declared in this scope
         return yamlMapToVariant( node );
                                       ^
[ 23%] Generating nl-plasmanetworkmanagement_openvpnui.gmo
[ 23%] Generating nl-plasmanetworkmanagement_openswanui.gmo
[ 23%] Generating nl-plasmanetworkmanagement_openconnectui.gmo
[ 24%] Generating nl-plasmanetworkmanagement_l2tpui.gmo
[ 24%] Generating nl-plasmanetworkmanagement-libs.gmo
src/libcalamaresui/CMakeFiles/calamaresui.dir/build.make:217: recipe for target 'src/libcalamaresui/CMakeFiles/calamaresui.dir/utils/YamlUtils.cpp.o' failed
make[2]: *** [src/libcalamaresui/CMakeFiles/calamaresui.dir/utils/YamlUtils.cpp.o] Error 1
CMakeFiles/Makefile2:208: recipe for target 'src/libcalamaresui/CMakeFiles/calamaresui.dir/all' failed
make[1]: *** [src/libcalamaresui/CMakeFiles/calamaresui.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
note: keeping build directory ‘/tmp/nix-build-calamares-1.0.drv-0’
builder for ‘/nix/store/z7rybvgi2kgf7p0ifybaz2p7gbvdd9h0-calamares-1.0.drv’ failed with exit code 2
```

**Comment by vandenoever** [comment]
I did not build calamares because it is marked as broken.
```
error: Package ‘calamares-1.0’ in ‘/home/home/nixpkgs/pkgs/tools/misc/calamares/default.nix:50’ is marked as broken, refusing to evaluate.
```

**Comment by FRidh** [comment]
I am now using this PR and have encountered only one small issue. In the `Look and Feel` settings Breeze is shown twice.

(And dual screen with Plasma is unfortunately still horrible...)

**Comment by vandenoever** [comment]
Dual screen issue may go away after setting it up once. That was the case here and now it works fine for me (laptop with sometimes external screen, both full hd).

**Comment by FRidh** [comment]
@vandenoever If I stick with one setup then its indeed fine, but I change between two dual screen setups and at times without any extra screen. Making the kscreen config read-only after the initial setup already helped a lot.

**Comment by ttuegel** [comment]
There is a bug in Ark which prevents it from starting in Plasma 5.7. Until Applications 16.04.3 is released, we will have to backport [this patch](https://quickgit.kde.org/?p=ark.git&a=commitdiff&h=132743e572fb7550cbfbbe8db848f2a28a0001cb).

**Comment by vandenoever** [comment]
Ok, I can add it. Btw, it seem 7z can be used instead of unrar on the cmdline. Did not yet check if ark can use 7z instead of unrar.

**Comment by vandenoever** [comment]
@ttuegel I've added the patch to ark and compiled and tested it. It works fine.

**Comment by ttuegel** [comment]
:+1: Thanks!

**Comment by vandenoever** [comment]
You're welcome. Your upgrade scripts really helped to make this quite smooth.

**Pull request merged**
