### PR TITLE
ferium: 4.1.5 -> 4.1.8

### PR DESCRIPTION
**Pull request by soupglasses**
###### Description of changes

Updates ferium to 4.1.8. [`CHANGELOG`](https://github.com/gorilla-devs/ferium/blob/v4.1.8/CHANGELOG.md)

This PR also adds in an install section for `installShellCompletion` to build the completions for ferium, as the required `complete` command is now working inside a build enviroment since 4.1.7 [`v4.1.7 CHANGELOG`](https://github.com/gorilla-devs/ferium/blob/v4.1.7/CHANGELOG.md#v417).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by winterqt — CHANGES_REQUESTED** [review]
Please split into three commits:
1. bumping the package
2. installing the shell completions
3. adding yourself as a maintainer

**Comment by imsofi** [comment]
> Please split into three commits:
> 
> 1. bumping the package
> 2. installing the shell completions
> 3. adding yourself as a maintainer

Ah yeah my bad, did more than i should have in one commit. They have now been split up.

**Review by winterqt — CHANGES_REQUESTED** [review]
Apologies for being so pedantic, but do you mind reordering them to:
1. bumping the package
2. installing the shell completions
3. adding yourself as a maintainer

My reasoning for this is that the bump is the main reason for this PR, the shell completions change the package, and the addition of a maintainer doesn't change the package. Thanks!

**Review by leo60228 — APPROVED** [review]

**Comment by imsofi** [comment]
> Apologies for being so pedantic, but do you mind reordering them to:
> 
> 1. bumping the package
> 2. installing the shell completions
> 3. adding yourself as a maintainer
> 
> My reasoning for this is that the bump is the main reason for this PR, the shell completions change the package, and the addition of a maintainer doesn't change the package. Thanks!

I fail to see how this may be helpful. I read it as:

1. I set myself up to be a maintainer for this package, committing to keep it up to date and ensure it is not broken.
2. I now update it 4.1.5 -> 4.1.8 to get it to the latest version.
3. I add in a feature i have been working on for the past week to get completions built in to the nix package.

So I add myself as maintainer -> upgrade -> add a few feature.
It would be a bit weird to upgrade, add a new feature, but then say after the fact that I am now a maintainer after I added those changes. As then there would exist a state of the file where changes i maintain exist without my name attached to them outside of looking it up in git.

**Review by winterqt — APPROVED** [review]

**Pull request merged**
