### PR TITLE
nixos/mpd: use upstream units

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Motivation for this change

Reducing the maintanance cost by using the systemd units provided by upstream.

###### Things done

- [x] Tested via `nixosTests.mpd`
- [x] Tested socket activation
- [x] Tested a custom `dataDir`
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by emmanuelrosa — COMMENTED** [review]
I ran the tests as well and they passed. 

My only concern is that I was unable to find the merged *.service files. I was expecting to find an mpd.service file in the Nix store which contained the merged content of the upstream system unit file and the unit file produced by the module. But I could only find the one generated by the module.

**Comment by rnhmjoj** [comment]
The unit files inside the package, I don't think they're ever copied somewhere else.

**Comment by emmanuelrosa** [comment]
What about the `systemd.packages` option? I looks to me like it generates files in `/etc/systemd/`: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/system/boot/systemd.nix#L947

**Comment by rnhmjoj** [comment]
Ah, I think I get what you mean now: no, the unit definitions are not merged into a new file.
If you run `systemctl cat mpd` you will understand: both files are parsed by systemd separately.
I think you can only see the result of the "merging" with `systemctl show mpd`.

**Comment by emmanuelrosa** [comment]
OK, I ran the tests interactively to get access to the running VMs, and I confirmed that systemd parsed both service files; The one from upstream and the one generated by the mpd NixOS module. Looks good to me!

**Comment by rnhmjoj** [comment]
Ok, I'm merging this, then. Thank you for the testing!

**Pull request merged**
