### PR TITLE
new package: passlib

### PR DESCRIPTION
**Pull request by psibi**

### CODE REVIEW

**Comment by psibi** [comment]
CC: @iElectric 

Can you look into this ? I guess this is the same error in Travis-CI which we saw earlier.

**Comment by cillianderoiste** [comment]
@psibi it looks like the pypy tests are failing. Are you able to run the command that fails locally?:
`nix-build -A python34Packages.passlib -A python33Packages.passlib -A python27Packages.passlib -A pypyPackages.passlib /path/to/nixpkgs`

**Comment by psibi** [comment]
@cillianderoiste Thanks, fixed them.

**Comment by psibi** [comment]
@cillianderoiste That works fine locally. At the end I get something like this:

````
/nix/store/ina4rknqn8qjxls6ky0rafhkqpqzcq7d-python3.4-passlib-1.6.2
/nix/store/rd5mb4crhis44g6gw0rnamak335n4aq2-python3.3-passlib-1.6.2
/nix/store/nqy4riz860cqykwqm3dcp13ndpx6l33l-python2.7-passlib-1.6.2
/nix/store/1cl9rlydahy38dph03667kr3z7bgmwya-pypy2.4-passlib-1.6.2
````

**Pull request merged**
