### PR TITLE
WIP gnome3: remove 3.20

### PR DESCRIPTION
**Pull request by groxxda**
###### Motivation for this change

We don't have the manpower to maintain more than one gnome version
#### TODO
- [ ] Port gnome3_20.vte-select-text
###### Things done
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by DamienCassou** [comment]
Thanks

**Comment by vcunat** [comment]
This should wait a couple weeks so that it can serve as fallback for people having problems with 3.22.

**Comment by lethalman** [comment]
There's no reason to remove it in staging:
1. Wait GNOME 3.22 to be in unstable channel
2. Send a mail once it's in unstable channel
3. Wait at least a week for people to use it
4. If all it's ok, remove GNOME 3.20

**Comment by groxxda** [comment]
I will rebase to master once the updates land there.
This PR will show merge conflicts if there were commits to gnome 3.20 in the mean time, so I will know I have to forward port them.

**Comment by globin** [comment]
ping @groxxda this should be ready now, right? I'd like to get this in soon preparing for 17.03. If you don't have the time I can finish this off, too?

**Pull request closed without merging**
