### PR TITLE
Gnome 3.34.1

### PR DESCRIPTION
**Pull request by hedning**
###### Things done

Staging updates will come in a separate pr.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by worldofpeace** [comment]
We'll just say this point release was very needed and proactive :smile:

**Comment by hedning** [comment]
Yeah, the zero releases tend have a few issues :/

Built everything (and a large part of the reverse dependencies). Think this is good to go tbh.

- moved `evince` back to tarball as they now contain meson
- removed gio-unix ld flag from gnome-terminal as that's fixed upstream
- ran up a VM to check that gdm/gnome-session works correctly

**Comment by worldofpeace** [comment]
@hedning Seems good to me also. Will run some checks now and probably merge shortly.

**Comment by hedning** [comment]
gnome-shell and mutter is late updating, so we'll just do them in a separate pr.

**Pull request merged**
