### PR TITLE
man-db: add gzip to the executable PATH wrapper

### PR DESCRIPTION
**Pull request by ShamrockLee**
###### Description of changes

Add `gzip` to the packages to be append to `PATH` by `wrapProgram`.

`gzip` is so common that we often assume everyono has it in their environmont. This is not the case in a very bare-bone environment setup. Considering many program relies on `man` to display their `--help` message, it should be able to work without dependency to the environment executable such as `gzip`.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [X] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bjornfor** [comment]
This PR rebuilds so many packages that it should target branch "staging" instead of "master".

**Comment by ShamrockLee** [comment]
> This PR rebuilds so many packages that it should target branch "staging" instead of "master".

Thanks you!

**Comment by bjornfor** [comment]
> > This PR rebuilds so many packages that it should target branch "staging" instead of "master".
> 
> Thanks you for telling me that!

I think you can re-target a different branch in an existing PR. Look for it next time. (I haven't done so myself yet.)

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging

**Comment by ShamrockLee** [comment]
I just found the GitHub to choose a different base branch for an existing PR, and will try the next time.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request

**Comment by ShamrockLee** [comment]
> https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging

I used this to rebase and create another PR after failing to find a way to switch the merge-to branch.

**Pull request closed without merging**
