### PR TITLE
nixos: add deCONZ Zigbee gateway support

### PR DESCRIPTION
**Pull request by bjornfor**
## Description of changes

Add a NixOS module (and test) for the deCONZ Zigbee gateway software.

Commit list:

- deconz: update meta
- nixos/deconz: init
- nixos/tests/deconz: init
- deconz: add NixOS test to passthru.tests

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AndersonTorres** [comment]
The changes over deconz can be squashed in only one commit.

**Comment by bjornfor** [comment]
> The changes over deconz can be squashed in only one commit.

What would the topic be of such a commit?

**Comment by AndersonTorres** [comment]
```
deconz: refactor


- bullet
- list
- of
- changes
```

**Comment by bjornfor** [comment]
It's not refactoring though (https://en.wikipedia.org/wiki/Code_refactoring), since the patches introduce externally visible changes. (Actually, that's the only thing they do, so the changes are in fact of a non-refactoring character.)

I guess we could group 3 out of 4 deconz commits under `deconz: improve meta attributes` (+ bullet list body). But why? Is it to minimize the number of commits in a PR? That would take a 6 commit PR down to 4 commits. But we could make even bigger reductions by collapsing them all into the PR title `nixos: add deCONZ Zigbee gateway support`. ('m not suggesting that we do that.)

I think I prefer small and to-the-point commits. But if you have strong feelings about it, I can squash 3 deconz commits into 1?

**Comment by bjornfor** [comment]
Ok, that's fair. I've squashed.

**Review by AndersonTorres — APPROVED** [review]

**Pull request merged**
