### PR TITLE
nixos/make-test: don't pick up impure overlays

### PR DESCRIPTION
**Pull request by bjornfor**
###### Motivation for this change
Specify overlays = [] to prevent nixpkgs from evaluating overlays from
$HOME etc.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @tfc @Ekleog @aszlig

### CODE REVIEW

**Comment by bjornfor** [comment]
Several nixos tests also imported nixpkgs but left out the overlays argument (impure). Added a 2nd commit to fix those.

**Comment by aszlig** [comment]
Hm, maybe it's a better idea to just import `../../pkgs/top-level` instead, because every time there is a new attribute added to [`impure.nix`](https://github.com/NixOS/nixpkgs/blob/9ed43c870eb1b4c1ad147288788f90709ef9f32e/pkgs/top-level/impure.nix) we need to change the arguments of all those imports again?

**Comment by bjornfor** [comment]
> Hm, maybe it's a better idea to just import ../../pkgs/top-level instead, because every time there is a new attribute added to impure.nix we need to change the arguments of all those imports again?

That sounds like a good idea, but I'm not sure what to pass to the one and only mandatory `../../pkgs/top-level/default.nix` argument named `localSystem`. On my x86 system it seems the `localSystem` value passed is `{}`. Is that a reasonable value to "hardcode" into all nixpkgs imports in the various nixos tests? Ping @Ericson2314.

**Comment by bjornfor** [comment]
Hopefully unneeded now that https://github.com/NixOS/nixpkgs/pull/203028 is merged (and a lot of refactoring since this diff was made).

**Pull request closed without merging**
