### PR TITLE
rstudio: 2023.09.0+463 -> 2023.12.0+369

### PR DESCRIPTION
**Pull request by b-rodrigues**
## Description of changes

This is a draft PR because I tried upgrading to the latest version of RStudio, but there seems to be an issue with CMake. See next message with the error message.

- Upgraded to current version (2023.12.0+369 "Ocean Storm"): commits https://github.com/b-rodrigues/nixpkgs/commit/6919a0a7295a6795c9ac0e20ec434b747fdba217 and https://github.com/b-rodrigues/nixpkgs/commit/1f1623bc18b9f946c0dcb7e0bd0d529c6909ccb5
- Upgraded boost version (from 1.81 to 1.83): commits https://github.com/b-rodrigues/nixpkgs/commit/5a9439f74a50196f3cf256d9af176b202a3880ca and https://github.com/b-rodrigues/nixpkgs/commit/872395a585473a0415b0a74262e60af309ba4537  This was needed because using boost at version 1.81 resulted in error indicating that this release of boost was too old.
- Updated use-system-node-patch: commits https://github.com/b-rodrigues/nixpkgs/commit/03ba137ae564eed4c8517bb66187d79687ff19eb , https://github.com/b-rodrigues/nixpkgs/commit/d66f51d9db7d9e0cf88a5ec8af6dde8d0da85df7 and https://github.com/b-rodrigues/nixpkgs/commit/123bd723cfd9e90c3fced89fc228445a5fac3368

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by b-rodrigues** [comment]
Trying to build now results in following message:

```
-- Configuring incomplete, errors occurred!
error: builder for '/nix/store/jn4im93rx67cp0z2yzgdr6swyy8f9vwb-RStudio-2023.12.0+369.drv' failed with exit code 1;
       last 10 log lines:
       > -- Looking for group_member
       > -- Looking for group_member - found
       > -- Performing Test HAVE_EXECINFO
       > -- Performing Test HAVE_EXECINFO - Success
       > -- Configured to build DESKTOP
       > -- Found LibR: /nix/store/m3lp6c2vgb6lvznfn8ichz8di4r51s8m-R-4.3.2/lib/R
       > -- Found R: /nix/store/m3lp6c2vgb6lvznfn8ichz8di4r51s8m-R-4.3.2/lib/R
       > -- Found Qt: /nix/store/pq91ai5s5h7nn3l2pa9cbrniw1cszpvj-qmake-hook/bin/qmake
       > -- Packaging RStudio for
       > -- Configuring incomplete, errors occurred!
       For full logs, run 'nix log /nix/store/jn4im93rx67cp0z2yzgdr6swyy8f9vwb-RStudio-2023.12.0+369.drv'.
error: 1 dependencies of derivation '/nix/store/4ldy5gahsal3azl4z8gnyibdqdszzav6-nix-shell.drv' failed to build
```

This is the configuration steps that fails:

```
-- Looking for getpeereid - not found
```

no idea what this is though

**Comment by philipp-baumann** [comment]
> getpeereid

could this maybe be related to this? https://github.com/rstudio/rstudio/issues/9600

**Comment by b-rodrigues** [comment]
Perhaps, but according to that thread it was an issue of gcc being too old: I don’t think we have this problem here?

**Comment by philipp-baumann** [comment]
Result of `nixpkgs-review pr 275649` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)

$ /nix/store/fgp1c16hly3960pnw765ac11a1p0a39r-nix-2.18.1/bin/nix-shell /Users/philipp/.cache/nixpkgs-review/pr-275649/shell.nix --nix-path nixpkgs=/Users/philipp/.cache/nixpkgs-review/pr-275649/nixpkgs nixpkgs-overlays=/tmp/tmpsh0gpt9r

**Comment by philipp-baumann** [comment]
> Perhaps, but according to that thread it was an issue of gcc being too old: I don’t think we have this problem here?

it is a bit strange though yes. Your current PR commit compiles on aarch64-darwin, so I wonder whether some specific gcc related imports in `nativeBuildInputs` could resolve on linux platforms. A wild guess because I am quite a nix beginner.

**Comment by b-rodrigues** [comment]
I've updated the source to use the latest rsconnect, and still get the same error message:

```
Looking for strtod_l - not found
Looking for getpeereid - not found
```

**Comment by b-rodrigues** [comment]
Closing this as @Kupac got it working over here

https://github.com/NixOS/nixpkgs/pull/289393

**Pull request closed without merging**
