### PR TITLE
cups: 2.4.3 -> 2.4.5

### PR DESCRIPTION
**Pull request by onny**
Diff: https://github.com/OpenPrinting/cups/compare/None...v2.4.4

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
The diff link is broken.

**Comment by wentasah** [comment]
I can confirm that this fixes a crash in Firefox.

I'm not sure about backporting to 23.05. According to the [upstream issue](https://github.com/OpenPrinting/cups/issues/719), the problem appears only in version 2.4.3 which is not in 23.05 (the backport label was removed in #235373).

**Comment by onny** [comment]
I really would like to see newer cups version in stable since they have a lot of bug fixes. @mweinelt can we backport it?

**Comment by wegank** [comment]
2.4.5 is out: https://github.com/OpenPrinting/cups/releases/tag/v2.4.5

**Comment by onny** [comment]
Thank you @wegank, updated this PR. Both releases seems to only contain hotfixes

**Review by wegank — APPROVED** [review]

**Review by SuperSandro2000 — APPROVED** [review]

**Pull request merged**
