### PR TITLE
vala_0_{48,54}: drop

### PR DESCRIPTION
**Pull request by amaxine**
## Description of changes

0.54 is out of support and no packages use it. 0.56 and 0.48 are both LTS and still supported, so that's all we should keep for now.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by tengkuizdihar — APPROVED** [review]

**Comment by jtojnar** [comment]
Where did you find 0.48 is still supported? It looks like the last release was [two years ago](https://github.com/GNOME/vala/releases/tag/0.48.25).

**Comment by amaxine** [comment]
https://wiki.gnome.org/Projects/Vala still claims so, but it does seem... questionable

> The supported stable release branches with Long-Term Support are 0.48 and 0.56.

**Comment by jtojnar** [comment]
Looks like it was [removed](https://github.com/vala-lang/vala-www/commit/748295efc5127647ecc9930407e5eb9769808dfa#diff-28043ff911f28a5cb5742f7638363546311225a63eabc365af5356c70d4deb77L585-R605) from the [new website](https://vala.dev/).

**Comment by amaxine** [comment]
It's still mentioned in the Matrix room topic right now - but since we don't have anything using 0.48 either I'll drop it too.

**Review by jtojnar — APPROVED** [review]

**Pull request merged**
