### PR TITLE
gitAndTools.gh: enable checks

### PR DESCRIPTION
**Pull request by zowoq**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by mweinelt — APPROVED** [review]
LGTM.

Thanks!

**Comment by zowoq** [comment]
@mweinelt I opened a PR instead of just pushing to master as I wanted this to build on all ofborg platforms before merging.

**Comment by mweinelt** [comment]
Ah, sorry. This would've been a great motivational text.

**Comment by zowoq** [comment]
> This would've been a great motivational text.

I don't understand what this means?

**Comment by mweinelt** [comment]
I couldn't have guessed your intent, so writing it down probably would've helped. Thought the "Motivation for this change" section could've been a good spot.

But I grant you that I might have merged too fast. Shame on me.

**Pull request merged**
