### PR TITLE
termusic: 0.9.0 -> 0.9.1, fix build

### PR DESCRIPTION
**Pull request by VuiMuich**
## Description of changes

Fix build issues with rust `1.80.0` and contribute to:
#332957

*Marked as draft until it is clear if upstream is quick to release an version bump to get their fix released, see this https://github.com/tramhao/termusic/issues/358

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by VuiMuich** [comment]
Upstream maintainer has confirmed to release a version bump, so this will be changed to a version update as well as soon as it happened there.

**Comment by VuiMuich** [comment]
I am working on the update, but I get this error, which I cannot figure out yet, how to solve:
```
error: builder for '/nix/store/0afnkjrw4hzfqzi6d7skcds7cfxl16lb-termusic-0.9.1.drv' failed with exit code 101;
       last 10 log lines:
       > ++ cargo test -j 4 --profile release --target x86_64-unknown-linux-gnu --offline -- --test-threads=4
       > warning: `/build/.cargo/config` is deprecated in favor of `config.toml`
       > note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
       > warning: `/build/.cargo/config` is deprecated in favor of `config.toml`
       > note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
       > error: the listed checksum of `/build/termusic-0.9.1-vendor.tar.gz/soundtouch-ffi/src/lib.rs` has changed:
       > expected: 49b1a2fa7698edd0b89328daff83a96284c1874bb1b35a06e17aaf6194b035d0
       > actual:   b367ac09c56ffb5751ee62afbf46ddd23c65adcff8812e702ebc59bc7e44dd6a
       >
       > directory sources are not intended to be edited, if modifications are required then it is recommended that `[patch]` is used with a forked copy of the source
```
I am trying now to build with `doCheck = false` to see if the build basically works.

**Comment by VuiMuich** [comment]
It builds and runs well, whithout the `checkPhase`, but of course it would be nicer to solve this properly. Since I am a bit out of my depth in this case, I would appreciate a little help from reviewers in this case.

**Comment by VuiMuich** [comment]
So with the two patches from upstream master everything seems fine now.
Also I learned that `cargo nextest` is significantly faster (at least 20%) so I think its useful to make use of it..

**Comment by devhell** [comment]
Thanks, @VuiMuich, for doing this. I'm a bit in a bind and have no resources to work on this currently, so thank you again very much for taking it on. :beers:

**Review by devhell — APPROVED** [review]

**Comment by devhell** [comment]
If someone could merge this please, I'd be grateful. Thank you.

**Comment by VuiMuich** [comment]
> Thanks, @VuiMuich, for doing this. I'm a bit in a bind and have no resources to work on this currently, so thank you again very much for taking it on. :beers: 

Thanks for the review and approval.
It was actually a nice "puzzle", though I still don't understand how the hash mismatch for the soundtouch-ffi crate happened during vendoring.

**Comment by VuiMuich** [comment]
@NixOS/nixpkgs-merge-bot merge

**Comment by VuiMuich** [comment]
Good bot! 🤖 Bad human (for not reading the docs of the bot fully before jumping to action excitedly). 😕

**Comment by VuiMuich** [comment]
Thanks for the merge ☺️

**Pull request merged**
