### PR TITLE
haskellPackages.bank-holidays-england: unbroken

### PR DESCRIPTION
**Pull request by samdoshi**
###### Motivation for this change

`haskellPackages.bank-holidays-england` is not broken.

```
$ nix-build -A haskellPackages.bank-holidays-england --arg config '{allowBroken = true;}'
/nix/store/8wv2n6l57wrdkycd20sf8irfdwp7izn1-bank-holidays-england-0.2.0.4
```

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
@GrahamcOfBorg eval

**Review by jonringer — COMMENTED** [review]
```
while evaluating the attribute 'buildInputs' of the derivation 'matterhorn-50200.8.0' at /home/jon/.cache/nixpkgs-review/pr-84001/nixpkgs/pkgs/development/haskell-modules/generic-builder.nix:291:3:
while evaluating the attribute 'propagatedBuildInputs' of the derivation 'brick-skylighting-0.3' at /home/jon/.cache/nixpkgs-review/pr-84001/nixpkgs/pkgs/development/haskell-modules/generic-builder.nix:291:3:
while evaluating 'getOutput' at /home/jon/.cache/nixpkgs-review/pr-84001/nixpkgs/lib/attrsets.nix:464:23, called from undefined position:
while evaluating anonymous function at /home/jon/.cache/nixpkgs-review/pr-84001/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:156:17, called from undefined position:
attribute 'brick_0_52_1' missing, at /home/jon/.cache/nixpkgs-review/pr-84001/nixpkgs/pkgs/development/haskell-modules/configuration-common.nix:1472:15
```

**Review by jonringer — COMMENTED** [review]
to get it to build:
```
$ git diff
diff --git a/pkgs/development/haskell-modules/configuration-common.nix b/pkgs/development/haskell-modules/configuration-common.nix
index e34126053df..639329a22ea 100644
--- a/pkgs/development/haskell-modules/configuration-common.nix
+++ b/pkgs/development/haskell-modules/configuration-common.nix
@@ -1469,7 +1469,7 @@ self: super: {
   # 2020-03-31 - "..." it broke again. so here's a more complicated way -- kiwi
   matterhorn = super.matterhorn.override {
     brick-skylighting = self.brick-skylighting.override {
-      brick = self.brick_0_52_1.override {
+      brick = self.brick.override {
         vty = self.vty_5_28_2;
       };
     };
diff --git a/pkgs/development/haskell-modules/hackage-packages.nix b/pkgs/development/haskell-modules/hackage-packages.nix
index bdb222b6c99..c906b017858 100644
--- a/pkgs/development/haskell-modules/hackage-packages.nix
+++ b/pkgs/development/haskell-modules/hackage-packages.nix
@@ -36239,7 +36239,6 @@ self: {
        description = "Calculation of bank holidays in England and Wales";
        license = stdenv.lib.licenses.bsd3;
        hydraPlatforms = stdenv.lib.platforms.none;
-       broken = true;
      }) {};

   "banwords" = callPackage
```

also, please target master when doing this

haskell-updates is for @peti to use when doing large rebuilds from hackage

**Comment by samdoshi** [comment]
> haskell-updates is for @peti to use when doing large rebuilds from hackage

Sorry, I was following the instructions from here:

https://discourse.nixos.org/t/call-to-action-for-updating-haskell-packages-after-bump-to-lts-15/6071

> When sending PRs to nixpkgs for Haskell-related changes, make sure to set the base branch as haskell-updates, not master.

**Comment by jonringer** [comment]
I will defer to @cdepillabout  about this. 

I think the hackage2nix needs to be re-ran to propagate the changes.

**Comment by rnhmjoj** [comment]
> haskell-updates is for @peti to use when doing large rebuilds from hackage

I've used this branch is the last couple of fixes I've submitted. This is fine.

**Comment by cdepillabout** [comment]
This looks good to me, but will probably be superseded by https://github.com/NixOS/nixpkgs/pull/84001/files.

**Comment by samdoshi** [comment]
@cdepillabout that link is back to this PR, is there is a different PR you meant to link to?

**Comment by cdepillabout** [comment]
@samdoshi Ah, sorry, it should be a link to the following:

https://github.com/NixOS/nixpkgs/pull/84039

**Comment by samdoshi** [comment]
Closing in favour of #84039

**Pull request closed without merging**
