### PR TITLE
[24.05] nixos/release: drop i686-linux support

### PR DESCRIPTION
**Pull request by RaitoBezarius**
## Description of changes

**Discussion for 24.05**

At the time of writing, an increased source of failure in our CI is related to i686-linux.

While I do wish to support 32 bits x86 system further, the reality is that we cannot identify in our community maintainers for `i686-linux` that can provide continuous maintenance for our i686-linux packages.

As a matter of fact, `i686-linux` is probably broken in nixpkgs, we decide to rip off the band-aid and drop the support.

Next steps could involve to extract a core package set of nixpkgs / NixOS in an out-of-tree repository to offer a simple 32 bits NixOS support with a cache or to find maintainers who are willing to work on i686 support.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
Note: dropping the i686 ISO would need also changes elsewhere &ndash; at least 
- [ ] https://github.com/NixOS/nixos-channel-scripts/blob/master/mirror-nixos-branch.pl

I think it's a good direction to at least reduce the amount of i686 NixOS tests, but I'm not sure how far to go.  We surely want to keep building (and caching) some i686 packages.

**Comment by vcunat** [comment]
Do you think we need some kind of wider feedback from community before proceeding with reducing i686 builds?  I'm interested in this, because I believe it would noticeably ease burden on our build infra.

**Comment by RaitoBezarius** [comment]
> Do you think we need some kind of wider feedback from community before proceeding with reducing i686 builds? I'm interested in this, because I believe it would noticeably ease burden on our build infra (especially the NixOS tests seem like a bad tradeoff for i686).

No, I think we can proceed at dropping i686-linux now.

**Comment by vcunat** [comment]
Our [RFC](https://github.com/NixOS/rfcs/blob/master/rfcs/0046-platform-support-tiers.md#tier-3-1) says that stdenv for i686 should be a channel blocker.  That sounds fine to me, as we still want to keep building packages like wine or steam anyway.  But to keep the promise, we'd need to amend the channel blocking set. 

- `tested` in nixos/release-combined.nix
- and perhaps also `unstable` in pkgs/top-level/release.nix &ndash; otherwise I don't think this promise was (and will be) kept for the `nixpkgs-unstable` channel

**Comment by vcunat** [comment]
https://nixos.org/download has a link to 32-bit stable ISO.  I suspect we'll forget and it will get broken on release, but I suppose it won't be a big deal.

**Comment by vcunat** [comment]
The last `nixos-unstable` channel is without i686 download now:
https://releases.nixos.org/nixos/unstable/nixos-24.05pre564493.b0d36bd0a420

**Comment by RaitoBezarius** [comment]
> [nixos.org/download](https://nixos.org/download) has a link to 32-bit stable ISO. I suspect we'll forget and it will get broken on release, but I suppose it won't be a big deal.

We should send a PR to the homepage to update it.

**Comment by vcunat** [comment]
I hear nothing potentially blocking this PR from merging?

**Comment by RaitoBezarius** [comment]
> I hear nothing potentially blocking this PR from merging?

Yes feel free to proceed.

**Pull request merged**
