### PR TITLE
numpy: add version 1.9

### PR DESCRIPTION
**Pull request by adnelson**
@FRidh 
###### Things done
- [ ] Tested using sandboxing (`nix-build --option build-use-sandbox true` or [nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [X] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
> Format the commits in the following way:
>
> (pkg-name | service-name): (from -> to | init at version | refactor | etc)

While we discussed it before, I like to bring it up again. Why do you want to have the older version in Nixpkgs? If you need it, you can add it to your expression. I suppose you also have somewhere a file you share between specific expressions, or say a repository you share between coworkers?

I'm not opposed to having it in here because I think it can be useful, but as we're not building binaries and the expression is the same as for current versions of numpy I don't really see the use.

**Comment by zimbatm** [comment]
I think that redundant libraries should only be kept if two programs have conflicting requirements. Most programs should have at most two versions in case there are major incompatibilities and users need time to migrate their data. The only exception would be compilers which can have N versions where N is the number of major.minor versions.

**Comment by FRidh** [comment]
Which is also the general rule here.

**Comment by adnelson** [comment]
@FRidh since I'm not changing the version, but adding a new version, I'm not sure how that formatting rule applies.

While it's certainly possible to just insert the new version of `numpy` in a `packageOverrides` or similar, I'm not sure why we were removing the old version. I personally had trouble getting `scipy` and pandas to pass their unit test suites with the versions of `numpy` and `scipy` that we have in `nixpkgs`. While that may or may not be the case now, it's demonstrably the case that:

* The authors of numpy/scipy/pandas don't seem to place a high premium on backwards compatibility, and so having fixed version is helpful
* These packages are expensive to build, which makes it helpful to have them in `nixpkgs`
* There are already several versions of `numpy` and `scipy` (and several other libraries) in `nixpkgs`, so it seems like a small cost to add one more

If there's strong opposition to adding another version of numpy, I have a workaround, but I'm struggling to see the major downside to just defining several versions of numpy and letting consumers of nixpkgs choose whichever one they need.

**Comment by FRidh** [comment]
@adnelson 
> Also I'm not sure why you asked me to create a new PR earlier if you were going to object to it...

I am not objecting to it, at all. The reason I asked for new PR's was because there were multiple unrelated changes/packages in the PR, and so they could be discussed separately.

And I was wondering why you really need this version of `numpy` here, especially because right now we're not building any binaries. I'm all for having multiple versions, which is why in my PR's on automating some of the url/hash fetching I included all available versions and added a version parameter so it would be possible to just override and we would not need to add explicit versions like this.

> since I'm not changing the version, but adding a new version, I'm not sure how that formatting rule applies. (EDIT: I guess "init at 1.9"...? except I'm not initing. Is add version 1.9 really that problematic of a commit message?)

We all now what you mean. It's just to add a bit of structure to the messages and making it easier to grep through the log. And indeed, `numpy` is already there, so it is not an init for `numpy`, but it is for the attribute `numpy_1_9`. Consider it nitpicking.

Anyway, if you could update it to using the pypi mirror as url I'll merge it.

**Comment by adnelson** [comment]
It's OK, I actually agree that there shouldn't be a proliferation of numpy packages. For my purposes I can just patch pythonPackages as we had talked about in that other PR, so it's fine. My apologies for being a bit prickly about it.

**Pull request closed without merging**
