### PR TITLE
u-boot: Add Raspberry Pi 4 build

### PR DESCRIPTION
**Pull request by samueldr**
Builds on #70793 

###### Things done

- ✔️ Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - ✔️ NixOS
   - 🔲 macOS
   - 🔲 other Linux distributions
- 🔲 Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- ✔️ Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- 🔲 Tested execution of all binary files (usually in `./result/bin/`)
- 🔲 Determined the impact on package closure size (by running `nix path-info -S` before and after)
- 🔲 Ensured that relevant documentation is up to date
- ✔️ Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Yet untested, though this was verified as building using cross-compilation, for both 32 and 64 bit variants.

### CODE REVIEW

**Comment by tkerber** [comment]
Just gave this a whirl, changing `nixos/modules/system/boot/loader/raspberrypi/uboot-builder.{nix,sh}` to accommodate it. Unfortunately, I got stuck at the rainbow boot screen, so I cannot confirm this working.

**Comment by samueldr** [comment]
Hmm, there's changes missing for an sd-image to work. Though I won't have the time to do that until after NixCon.

 * https://github.com/NixOS/nixpkgs/blob/dd050270c78a0e214ed7cb9e25bae43b45406473/nixos/modules/installer/cd-dvd/sd-image-aarch64.nix#L52-L55

Around there the u-boot for raspberry 4 will need to be copied, and config.txt will need to be extended to configure per-generation around here:

 * https://github.com/NixOS/nixpkgs/blob/dd050270c78a0e214ed7cb9e25bae43b45406473/nixos/modules/installer/cd-dvd/sd-image-aarch64.nix#L39

Once done, a build of the generic sd image, with the generic latest kernel, and hopefully it works.

**Comment by tkerber** [comment]
I deployed straight to my running machine with nixops, fortunately making a backup of `/boot` beforehand. I'll try an sd card image later.

**Comment by samueldr** [comment]
This is blocked until there is a `bcm2711-rpi-4-b.dts` from mainline.

With the current state of this branch, adding a `bcm2711-rpi-4-b.dtb` to the root of the FIRMWARE partition of the sd_image will make u-boot successfully boot. Though, since mainline kernel does not yet have the rpi 4 device tree, it fails to continue booting.

This might be a bigger issue since it's looking like the next LTS (5.4) will not have rpi 4 support. In this situation, building the firmware partition may differ depending on the kernel it is built with. Or, alternatively, depend on a mainline latest kernel build in addition to last LTS. Or, final alternative, is that u-boot imports the kernel device trees (as they usually do) with an rpi-4 dts, and then everything is fine and self-contained.

**Comment by ardumont** [comment]
> With the current state of this branch, adding a bcm2711-rpi-4-b.dtb to the root of the FIRMWARE partition of the sd_image will make u-boot successfully boot. 

yes, u-boot starts up fine.

>  Though, since mainline kernel does not yet have the rpi 4 device tree, it fails to continue booting.

And there i'm stuck on 'Starting kernel...` (extlinux.conf is read alright).
So that must be why i got stuck here.

**Comment by timokau** [comment]
Here's an [issue](https://github.com/lategoodbye/rpi-zero/issues/43) tracking the mainlining efforts.

**Comment by samueldr** [comment]
Still desired, still blocked.

**Comment by mohe2015** [comment]
@samueldr Would this not work with pkgs.linuxPackages_rpi4 ?

**Comment by aneeshusa** [comment]
AFAICT this has been superseded by https://github.com/NixOS/nixpkgs/pull/97883 so closing - please reopen if this if I missed something and this is still desired as a separate PR.

**Pull request closed without merging**
