### PR TITLE
teams-for-linux: 1.2.8 -> 1.3.2

### PR DESCRIPTION
**Pull request by YarekTyshchenko**
## Description of changes

Update teams-for-linux

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by lilyinstarlight — APPROVED** [review]
Looks good to me and works in my testing! Is there any reason this is marked as draft?

I'd like for this to supersede #248648

**Review by lilyinstarlight — CHANGES_REQUESTED** [review]
I did some testing and it looks like the `screensharing-wayland-hack-fix.patch` is no longer necessary. Do you think you could remove the file and the `patches = [ ... ]` lines in this PR?

Thanks again!

**Review by lilyinstarlight — CHANGES_REQUESTED** [review]
I feel like I'm being a little nitpicky, but could you update the second commit's message to fit the contributing guidelines? 😅

Something like "teams-for-linux: remove wayland patch for screensharing fixed upstream"

**Comment by YarekTyshchenko** [comment]
No probs. This is my first contribution and I'd like to get all the details right. Thank you for taking the time to review!

**Review by lilyinstarlight — APPROVED** [review]
Looks good to me now! Once ofborg/CI finishes, I'll go ahead and merge this

Also welcome to nixpkgs! :)

**Comment by dschrempf** [comment]
I can confirm that changing electron to version `electron_24` makes Teams usable again.

BTW: @Arcayr , how did you get the debug log? The only thing I could get was rather non-informative stack trace via `journalctl`. Neither `teams-for-linux --webDebug`, nor `teams-for-linux --appLogLevel ...` helped.

**Comment by lilyinstarlight** [comment]
Downgrade to `electron_24` is at #254379

**Pull request merged**
