### PR TITLE
swift: fix build and mark as unbroken on darwin

### PR DESCRIPTION
**Pull request by corngood**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [x] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by corngood** [comment]
Result of `nixpkgs-review pr 326588` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>23 packages built:</summary>
  <ul>
    <li>deadbeef</li>
    <li>deadbeef-with-plugins</li>
    <li>ghidra-extensions.ghidraninja-ghidra-scripts</li>
    <li>sourcekit-lsp</li>
    <li>swift</li>
    <li>swift-corelibs-libdispatch</li>
    <li>swift-corelibs-libdispatch.dev</li>
    <li>swift-corelibs-libdispatch.man</li>
    <li>swift-format</li>
    <li>swift.man</li>
    <li>swiftPackages.Foundation</li>
    <li>swiftPackages.Foundation.dev</li>
    <li>swiftPackages.XCTest</li>
    <li>swiftPackages.swift-docc</li>
    <li>swiftPackages.swift-driver</li>
    <li>swiftPackages.swift-unwrapped</li>
    <li>swiftPackages.swift-unwrapped.dev</li>
    <li>swiftPackages.swift-unwrapped.doc</li>
    <li>swiftPackages.swift-unwrapped.lib</li>
    <li>swiftPackages.swift-unwrapped.man</li>
    <li>swiftPackages.swiftNoSwiftDriver</li>
    <li>swiftPackages.swiftNoSwiftDriver.man</li>
    <li>swiftPackages.swiftpm</li>
  </ul>
</details>

**Comment by corngood** [comment]
Result of `nixpkgs-review pr 326588` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages marked as broken and skipped:</summary>
  <ul>
    <li>anki</li>
    <li>anki.dist</li>
    <li>anki.doc</li>
    <li>anki.man</li>
    <li>ki</li>
    <li>ki.dist</li>
    <li>mnemosyne</li>
    <li>mnemosyne.dist</li>
    <li>mpc-qt</li>
  </ul>
</details>
<details>
  <summary>13 packages failed to build:</summary>
  <ul>
    <li>dotnetCorePackages.dotnet_8.aspnetcore</li>
    <li>dotnetCorePackages.dotnet_8.runtime</li>
    <li>dotnetCorePackages.dotnet_8.sdk</li>
    <li>dotnetCorePackages.dotnet_8.sdk.artifacts</li>
    <li>dotnetCorePackages.dotnet_8.sdk.packages</li>
    <li>dotnetCorePackages.dotnet_8.vmr</li>
    <li>dotnetCorePackages.dotnet_9.aspnetcore</li>
    <li>dotnetCorePackages.dotnet_9.runtime</li>
    <li>dotnetCorePackages.dotnet_9.sdk</li>
    <li>dotnetCorePackages.dotnet_9.sdk.artifacts</li>
    <li>dotnetCorePackages.dotnet_9.sdk.packages</li>
    <li>dotnetCorePackages.dotnet_9.vmr</li>
    <li>gonic</li>
  </ul>
</details>
<details>
  <summary>53 packages built:</summary>
  <ul>
    <li>ani-cli</li>
    <li>cplay-ng</li>
    <li>cplay-ng.dist</li>
    <li>curseradio</li>
    <li>curseradio.dist</li>
    <li>dark-mode-notify</li>
    <li>dmlive</li>
    <li>dockutil</li>
    <li>dra-cla</li>
    <li>ff2mpv</li>
    <li>ff2mpv-go</li>
    <li>ghidra-extensions.ghidraninja-ghidra-scripts</li>
    <li>hydrus</li>
    <li>hydrus.doc</li>
    <li>invidtui</li>
    <li>klipperscreen</li>
    <li>mov-cli</li>
    <li>mov-cli.dist</li>
    <li>mpv</li>
    <li>mpv-unwrapped</li>
    <li>mpv-unwrapped.dev</li>
    <li>mpv-unwrapped.doc</li>
    <li>mpv-unwrapped.man</li>
    <li>needle</li>
    <li>photoqt</li>
    <li>plex-media-player</li>
    <li>python311Packages.mpv</li>
    <li>python311Packages.mpv.dist</li>
    <li>python312Packages.mpv</li>
    <li>python312Packages.mpv.dist</li>
    <li>somafm-cli</li>
    <li>sourcekit-lsp</li>
    <li>subtitleedit</li>
    <li>supersonic</li>
    <li>swift</li>
    <li>swift-format</li>
    <li>swift.man</li>
    <li>swiftPackages.XCTest</li>
    <li>swiftPackages.swift-docc</li>
    <li>swiftPackages.swift-driver</li>
    <li>swiftPackages.swift-unwrapped</li>
    <li>swiftPackages.swift-unwrapped.dev</li>
    <li>swiftPackages.swift-unwrapped.doc</li>
    <li>swiftPackages.swift-unwrapped.lib</li>
    <li>swiftPackages.swift-unwrapped.man</li>
    <li>swiftPackages.swiftNoSwiftDriver</li>
    <li>swiftPackages.swiftNoSwiftDriver.man</li>
    <li>swiftPackages.swiftpm</li>
    <li>tomato-c</li>
    <li>wtwitch</li>
    <li>xcodes</li>
    <li>youtube-tui</li>
    <li>ytfzf</li>
  </ul>
</details>

**Review by emilazy — APPROVED** [review]
cc @risicle https://github.com/NixOS/nixpkgs/issues/318674

For context: Swift builds and uses its own Clang(!) which I guess doesn’t like this flag? Not sure if there’s a “better” resolution here.

**Comment by corngood** [comment]
I'll take care of the dotnet failures separately.  It seems to be unrelated to swift and just some breakage that slipped in while everything was disabled.

**Pull request merged**
