### PR TITLE
nixops: make overrides build instead of failing with 'nixops-_version_-py2-none-any.whl is not a valid wheel filename'

### PR DESCRIPTION
**Pull request by teto**
###### Motivation for this change
I have a backlog of 3/4 PRs in my nixops repo and I got fed up with running ./dev-shell every time I wanted to use nixops. I wanted to install my fork instead but when overriding the src attribute of nixops I would end up with:
'nixops-_version_-py2-none-any.whl is not a valid wheel filename'.

One workaround is https://github.com/grahamc/network/blob/master/shell.nix#L14
It appears that nixops/release.nix has its own nix package. A better solution might
be to move these changes back to nixpkgs.

###### Things done
Make   
```
nixops-dev = super.nixops.overrideAttrs ( src: {
    name = "nixops-dev";
    src = myCustomFork...;
  });
```
installable.

The changes seem to break the documentation generation but as I know nothing about this and it seemed a bit complex (plus I know the doc system changed recently), I would appreciate it someone knowledgeable in the area could provide a patch @grahamc ?

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by teto** [comment]
@domenkozar the nixops doc building process is kinda confusing (I admit I quickly glaced over it), if you a patch/advice on how to improve it so that one can build everything from a nixops fork with just the nixpkgs derivation that would be cool

**Comment by domenkozar** [comment]
So the real fix is `substituteInPlace $i --subst-var-by version ${version}` and the rest is refactoring, afaik

**Comment by teto** [comment]
I alos noticed lots of duplication between nixops and nixpkgs so I had hoped for a maintainer to do both ?

**Comment by lheckemann** [comment]
@GrahamcOfBorg build nixopsUnstable

**Review by ryantm — CHANGES_REQUESTED** [review]
Please fix the merge conflict

**Comment by domenkozar** [comment]
I don't think we should merge this as-is. The generic.nix used to contain common paths, I don't see how this change improve things (refactoring wise).

**Comment by teto** [comment]
I close it because I don't intend to work on it anymore even though I would very much like to see the functionality.

**Comment by domenkozar** [comment]
Something we're using:

```
        nixops = (import (fetchFromGitHub {
          owner = "hercules-ci";
          repo = "nixops";
          rev = "b3cac58dc22cea42c1c47b4c1f13d23cbe377e1d";
          sha256 = "0lgaiczp02p3mbqbd9wc4sxrcwaym3sbkixb85n1id5j6rpwxs4h";
          } + "/release.nix") { nixpkgs = pkgs.path; }).build.x86_64-linux;
```

**Pull request closed without merging**
