### PR TITLE
flashplayer: cleanup, use archive as a source

### PR DESCRIPTION
**Pull request by abbradar**
Most work done by @ericsagnes. Followup on https://github.com/NixOS/nixpkgs/issues/11571. (EDIT: was #11588)

### CODE REVIEW

**Comment by ktosiek** [comment]
The patch works for me. I was bitten by those missing files quite a few times already.

**Comment by ericsagnes** [comment]
Thanks for making the PR!

**Comment by vcunat** [comment]
The pushed commit makes flash fail to build on `i686-linux`. The problem is that the `flash-plugin*.tar.gz` glob doesn't work there, as shown by the following log with added `ls -l` commands.
```
building path(s) ‘/nix/store/fs4gpgdrvfz94ic92zafxxzmyryqi9kp-flashplayer-11.2.202.554’
unpacking sources
unpacking source archive /nix/store/ynn9xn3sa4zhak3yp9vrsrpwz41g129y-fp_11.2.202.554_archive.zip
source root is .
total 12
-rw-r--r-- 1 nixbld nixbld 4896 Dec 17 11:11 env-vars
drwxr-xr-x 5 nixbld nixbld 4096 Dec 17 11:11 fp_11.2.202.554_archive
total 12656
-rw-rw-rw- 1 nixbld nixbld 6963199 Dec  1 08:05 flashplayer_11_2r202_554_linux.i386.tar.gz
-rw-rw-rw- 1 nixbld nixbld 5992629 Dec  1 08:05 flashplayer_11_2r202_554_linux_sa.i386.tar.gz
tar: option requires an argument -- 'f'
Try 'tar --help' or 'tar --usage' for more information.
```

**Comment by abbradar** [comment]
Argh, so we have (in different places) `32bit` and `64bit`, `i386` and `x86_64`, `flash-plugin` and `flashplayer` and geez, even their naming conventions are completely different!

I'll look at this.

**Comment by abbradar** [comment]
Fixed at https://github.com/NixOS/nixpkgs/commit/8c1770769fb2f68b881c3d1abbe9b43dde114510

**Comment by vcunat** [comment]
OK. Now I finished picking all flash changes to release-15.09 to keep the security updates easier.

**Comment by abbradar** [comment]
Nice, thanks!

**Comment by vcunat** [comment]
Thanks, too :-)

**Pull request merged**
