### PR TITLE
travis: disable for pull requests

### PR DESCRIPTION
**Pull request by Mic92**
travis is too slow for us and confuse contributors, who think they have
to get travis tests green.
We have now pr bots instead.

also see: https://github.com/NixOS/nixpkgs/issues/6652

### CODE REVIEW

**Comment by FRidh** [comment]
Can you also include the referred scripts.

**Comment by Mic92** [comment]
`travis-nox-review-pr.sh` removed

**Comment by globin** [comment]
:+1:

**Comment by c0bw3b** [comment]
I agree with this too.
Travis jobs provided _some_ level of information _sometimes_ in the past but was not to be trusted entirely and now we have those informations from the different Borg checks.
And we can still run a `nox-review` on our own for the big PRs.

**Pull request merged**
