### PR TITLE
haskell-generic-builder: support badPlatforms

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Motivation for this change

See

* <https://github.com/NixOS/cabal2nix/issues/497>
* <https://github.com/NixOS/cabal2nix/pull/506>
* <https://github.com/peti/distribution-nixpkgs/pull/13>

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by maralorn** [comment]
You might want to fix the commit title like I fixed the PR title.

**Comment by maralorn** [comment]
Huh, I can find 0 documentation on the `badPlatforms` field.

For convenience I am pasting from `lib/meta.nix`.
```
      A package is available on a platform if both
        1. One of `meta.platforms` pattern matches the given platform.
        2. None of `meta.badPlatforms` pattern matches the given platform.
```
In this light, this change looks completely sane.

**Comment by sternenseemann** [comment]
> Huh, I can find 0 documentation on the badPlatforms field.

Yes, it is also not 100% safe against removal, but we can easily emulate it in `haskellPackages.mkDerivation` if we want to keep using it.

**Review by maralorn — APPROVED** [review]
LGTM, when you fix the commit typo

**Pull request merged**
