### PR TITLE
obs-studio: patch to fix libobs.po on arm64

### PR DESCRIPTION
**Pull request by hufman**
## Description of changes
The current OBS Studio has [a bug](https://github.com/obsproject/obs-studio/issues/7972) that generates an incorrect libobs pkgconfig file on ARM systems, preventing plugins from being compiled against it. This PR packages an Arch patch to hardcode the relevant option, another approach is to [render the CMake expression](https://github.com/obsproject/obs-studio/pull/10008) before writing the pkgconfig file. OBS is instead [pursuing a different approach](https://github.com/obsproject/obs-studio/pull/9787) for the next release, but this patch will help until that version is released and packaged.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [X] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [X] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by hufman** [comment]
This should fix #270050

**Comment by fpletz** [comment]
After reading the linked issues PR, this looks good. I'm wondering however why the second hunk from https://git.alpinelinux.org/aports/tree/community/obs-studio/broken-config.patch?id=a92887564dcc65e07b6be8a6224fda730259ae2b is not needed.

**Review by eclairevoyant — CHANGES_REQUESTED** [review]
Fetching the patch is preferred, any reason why that's not being done here?

**Comment by hufman** [comment]
Good morning!
The second hunk of the patch didn't seem to be needed in my setup, so to reduce possible future conflicts I opted to not include it.
Instead of fetching directly, I needed to adjust the patch slightly to work with the slightly different version included in Nixos (the line number changed by one, so the patch application warns about being slightly dirty). I also didn't want to add load to Alpine's hosting. It still worked with the warning, so I could easily adjust this PR to fetch it if desired.

**Comment by eclairevoyant** [comment]
Conflicts shouldn't be an issue if they're fixing it on the next release. As mentioned in https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#patches:

> Patches available online should be retrieved using fetchpatch.

I'd prefer to adhere to the guidelines here.

**Comment by hufman** [comment]
Turns out the Alpine patch does not apply cleanly after rebasing to the new 30.0.2 version (which no longer has a `cmake/external` directory that the second hunk targets). Using the current PR diff still works and OBS 30.0.2 successfully launches and offers the selected plugins.

**Comment by eclairevoyant** [comment]
Then the second hunk can be excluded, `fetchpatch` takes other args

**Comment by hufman** [comment]
Neat, that fixed it, thanks!

**Comment by hufman** [comment]
Can you trigger an ofborg rebuild? It looks like the builder had a disk space issue, hopefully not caused by this PR!

**Comment by eclairevoyant** [comment]
@ofborg eval

**Review by fpletz — APPROVED** [review]

**Pull request merged**
