### PR TITLE
llvmPackages_10: rc2 -> rc3

### PR DESCRIPTION
**Pull request by ggreif**
###### Motivation for this change

http://lists.llvm.org/pipermail/llvm-dev/2020-March/139729.html

###### Things done

- `s/rc2/rc3/g`
- updated hashes
- additionally cherry-picked 3 commits from `llvm-project/master`:
  - llvm/llvm-project@d21664c
  - llvm/llvm-project@3a0f6e6
  - llvm/llvm-project@87dac7d

such that clang can automatically pick up the polly plugin from the
`llvm-polly` build.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ggreif** [comment]
@GrahamcOfBorg build llvmPackages_10

**Comment by ggreif** [comment]
Local build on Darwin `nix-build -A llvmPackages_10` gives
```
Scanning dependencies of target clangTidyCppCoreGuidelinesModule
[ 93%] Built target clangTidyAbseilModule
[ 93%] Linking CXX static library ../../../../lib/libclangTidyCppCoreGuidelinesModule.a
[ 93%] Built target clangTidyFuchsiaModule
[ 93%] Built target clangTidyCppCoreGuidelinesModule
Scanning dependencies of target clangTidyBugproneModule
Undefined symbols for architecture x86_64:
  "getPollyPluginInfo()", referenced from:
[ 93%] Linking CXX static library ../../../../lib/libclangTidyBugproneModule.a
      (anonymous namespace)::EmitAssemblyHelper::EmitAssemblyWithNewPassManager(clang::BackendAction, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream> >) in BackendUtil.cpp.o
ld: symbol(s) not found for architecture x86_64
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [tools/clang-shlib/CMakeFiles/clang-cpp.dir/build.make:1685: lib/libclang-cpp.dylib] Error 1
make[1]: *** [CMakeFiles/Makefile2:10545: tools/clang-shlib/CMakeFiles/clang-cpp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 93%] Built target clangTidyBugproneModule
make: *** [Makefile:130: all] Error 2
builder for '/nix/store/qgaq87wflydxnzbs7r8x1l0dnw9bqz8y-clang-10.0.0rc3.drv' failed with exit code 2
error: build of '/nix/store/qgaq87wflydxnzbs7r8x1l0dnw9bqz8y-clang-10.0.0rc3.drv' failed
```

**Comment by ggreif** [comment]
@Meinersbur may I reach out to you because of the above build error? https://github.com/llvm/llvm-project/commit/d7afdb596e865c11b853d8c5df7d96d594170e1c looks like a relevant commit for debugging this, but I am not knowledgeable enough about its mechanics. The major question is whether Polly is in `clang` by default and how it should be activated via `cmake` if not.

**Comment by DieGoldeneEnte** [comment]
I can confirm the same error on linux.
If I understand it correctly we need to enable polly with LLVM_ENABLE_PROJECTS, but I only had a quick look.

**Comment by Meinersbur** [comment]
I don't now what `nix-build` does. We cherry-picked into rc3 that LLVM_POLLY_LINK_INTO_TOOLS default to ON when polly is in LLVM_ENABLE_PROJECTS. `LINK_POLLY_INTO_TOOLS` and `WITH_POLLY` was internal before and should not have been set directly. After https://reviews.llvm.org/D61446, they do not exist anymore.

What cmake variables does `nix-build` set? I suggest to clean them up. Does the nix package apply any additional patches (like debian)?

**Comment by Meinersbur** [comment]
> The major question is whether Polly is in `clang` by default and how it should be activated via `cmake` if not.

Polly is built in the `all` target with `LLVM_ENABLE_PROJECTS=polly` or `LLVM_ENABLE_PROJECTS=all`. It is also added to clang (and opt/bugoint) if  `LLVM_POLLY_LINK_INTO_TOOLS=ON`, by creating a dependency to `getPollyPluginInfo`.

There were bugs with dylibs before. See https://github.com/llvm/llvm-project/issues/120

**Comment by Meinersbur** [comment]
The fixes https://github.com/llvm/llvm-project/commit/3a0f6e699bb6d96dc62dce6faef20ac26cf103fd and https://github.com/llvm/llvm-project/commit/87dac7da68ea1e0adac78c59ef1891dcf9632b67 are not cherry-picked into clang because of the risk so short before the release. They should be in clang 10.0.1.

If your package manager supports it, you could apply the patches locally.

**Comment by ggreif** [comment]
@Meinersbur Thanks for the hints! I have included the three relevant commits as patches to `llvm` and `clang`, and now I see (in the polly-flavoured `llvm`):
```
[nix-shell:~/nixpkgs]$ cat /nix/store/l8ij9nzph5m6pl0dr9zn3k22p4zaqgzi-llvm-10.0.0rc3/lib/cmake/llvm/LLVMConfigExtensions.cmake
set(LLVM_STATIC_EXTENSIONS Polly)
```
How can I test whether the corresponding `clang` also picks up the polly-flavour?

**Comment by ggreif** [comment]
@DieGoldeneEnte PTAL, I think this is ready for merging. CC @basvandijk

**Comment by Meinersbur** [comment]
> The non-polly flavour doesn't understand `-polly`, while the former, based on `llvm-polly` does. In the `llvm-polly` build, we simply add `polly` as a subdirectory into `$sourceRoot/tools`. The `clang` build then picks it up from there via `cmake` config file. No `LLVM_ENABLE_PROJECTS=polly` (or such) flags are needed.

In course of moving to the git monorepository, LLVM changed the project layout from polly in the `llvm/tools` subdirectory to polly in a sibling directory of llvm, i.e. a top-level directory in the monorepository (like all the other LLVM subprojects). The mechanisms are slightly different. While before the monorepository, you could assume that if somebody explicitly checked-out polly they also want to activate it (i.e. the project is enabled by default of the repository is present), with the monorepository nearly everyone has it checked out (To explicitly enable it, use LLVM_ENABLE_PROJECTS=polly).

Since the the developers, including me, are using the monorepository layout, the subproject will be less-and-less tested, and I expect it to be removed at some point to simplify the build system.

**Comment by DieGoldeneEnte** [comment]
@ggreif LGTM. It compiles without problems and polly is only available for the polly-variant.
Moving to the monorepository layout is in my opinion a good idea, but out of scope for this change.

**Comment by ggreif** [comment]
> Moving to the monorepository layout is in my opinion a good idea, but out of scope for this change.

Dito. Let's iterate.

**Comment by ggreif** [comment]
Ping @dtzWill @matthewbauer

**Comment by basvandijk** [comment]
@GrahamcOfBorg build llvmPackages_10 llvmPackages_10.clang-polly-unwrapped llvmPackages_10.clang-unwrapped

**Pull request merged**
