### PR TITLE
Openclonk 8.1

### PR DESCRIPTION
**Pull request by lheckemann**
###### Motivation for this change
New upstream version

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by lheckemann** [comment]
@lluchs you might care about this?

**Comment by lluchs** [comment]
Thanks for updating OpenClonk! The overall result is exactly what we expect to happen. OC on Mac doesn't work because we currently don't have any Mac developers  (although it does build successfully with XCode, I don't know what's wrong with nix's clang). While we fixed the issue with requiring SSE on all platforms, OC won't work on ARM in any case because it requires OpenGL 3.2, but there is only OpenGL ES available there.

So I suggest you disable building openclonk on everything but x86 Linux.

**Comment by lheckemann** [comment]
>OC requires OpenGL 3.2, but there is only OpenGL ES available there.

Not necessarily. There's no reason a PCIe graphics card couldn't be used with an ARM board. I'll rerun the builds so I can see the logs for arm and maybe fix the build if it's easy.

**Comment by lheckemann** [comment]
So the issue is that the BLAKE2 implementation is the [SSE one](https://github.com/BLAKE2/BLAKE2/tree/master/sse/) which assumes at least SSE2, which isn't available on ARM. This shouldn't be too hard to fix but it should probably be done upstream.

**Comment by lheckemann** [comment]
For the BLAKE2 issue,
[upstream issue](https://bugs.openclonk.org/view.php?id=2017)
[debian patch](https://salsa.debian.org/games-team/openclonk/commit/9822f90d2b5ff470ebd9998aa451443b45f1c429)

In the meantime, there shouldn't be any further obstacles to merging.

**Pull request merged**
