### PR TITLE
python3Packages.s3transfer: enable tests

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Enable tests

Related #154264

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 154280` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>mlflow-server</li>
  </ul>
</details>
<details>
  <summary>51 packages failed to build:</summary>
  <ul>
    <li>aws-sam-cli</li>
    <li>awslimitchecker</li>
    <li>home-assistant</li>
    <li>lexicon</li>
    <li>mapproxy</li>
    <li>python310Packages.buildbot</li>
    <li>python310Packages.buildbot-full</li>
    <li>python310Packages.buildbot-ui</li>
    <li>python310Packages.cartopy</li>
    <li>python310Packages.celery</li>
    <li>python310Packages.certbot-dns-route53</li>
    <li>python310Packages.cloudsplaining</li>
    <li>python310Packages.dependency-injector</li>
    <li>python310Packages.django-raster</li>
    <li>python310Packages.django-rq</li>
    <li>python310Packages.djmail</li>
    <li>python310Packages.fiona</li>
    <li>python310Packages.flower</li>
    <li>python310Packages.flowlogs_reader</li>
    <li>python310Packages.gensim</li>
    <li>python310Packages.geopandas</li>
    <li>python310Packages.gradient</li>
    <li>python310Packages.hass-nabucasa</li>
    <li>python310Packages.mapbox</li>
    <li>python310Packages.moto</li>
    <li>python310Packages.osmnx</li>
    <li>python310Packages.parsedmarc</li>
    <li>python310Packages.pathy</li>
    <li>python310Packages.pyhiveapi</li>
    <li>python310Packages.sentry-sdk</li>
    <li>python310Packages.serverlessrepo</li>
    <li>python310Packages.slack-sdk</li>
    <li>python310Packages.slicedimage</li>
    <li>python310Packages.smart-open</li>
    <li>python310Packages.snowflake-connector-python</li>
    <li>python310Packages.snowflake-sqlalchemy</li>
    <li>python310Packages.spacy</li>
    <li>python310Packages.spacy-transformers</li>
    <li>python310Packages.tensorboardx</li>
    <li>python310Packages.textacy</li>
    <li>python39Packages.cartopy</li>
    <li>python39Packages.geopandas</li>
    <li>python39Packages.osmnx</li>
    <li>python39Packages.serverlessrepo</li>
    <li>python39Packages.snowflake-connector-python</li>
    <li>python39Packages.snowflake-sqlalchemy</li>
    <li>python39Packages.spacy</li>
    <li>python39Packages.spacy-transformers</li>
    <li>python39Packages.textacy</li>
    <li>sourcehut.metasrht</li>
    <li>tts</li>
  </ul>
</details>
<details>
  <summary>102 packages built:</summary>
  <ul>
    <li>alerta-server</li>
    <li>aws-google-auth</li>
    <li>aws-mfa</li>
    <li>awscli</li>
    <li>awscli2</li>
    <li>awslogs</li>
    <li>barman</li>
    <li>bash-my-aws</li>
    <li>buildbot (python39Packages.buildbot)</li>
    <li>buildbot-full (python39Packages.buildbot-full)</li>
    <li>buildbot-ui (python39Packages.buildbot-ui)</li>
    <li>certbot-full</li>
    <li>checkov</li>
    <li>cloud-custodian</li>
    <li>credstash (python39Packages.credstash)</li>
    <li>cura</li>
    <li>deja-dup</li>
    <li>duplicity</li>
    <li>duply</li>
    <li>dvc-with-remotes</li>
    <li>elasticsearch-curator</li>
    <li>git-remote-codecommit</li>
    <li>gns3-gui</li>
    <li>gns3-server</li>
    <li>iceshelf</li>
    <li>luigi</li>
    <li>moodle-dl</li>
    <li>moz-phab</li>
    <li>nimbo</li>
    <li>ntfy</li>
    <li>octoprint</li>
    <li>parquet-tools</li>
    <li>python310Packages.aws-sam-translator</li>
    <li>python310Packages.boto3</li>
    <li>python310Packages.cfn-lint</li>
    <li>python310Packages.credstash</li>
    <li>python310Packages.django-anymail</li>
    <li>python310Packages.ec2instanceconnectcli</li>
    <li>python310Packages.fs-s3fs</li>
    <li>python310Packages.mypy-boto3-builder</li>
    <li>python310Packages.mypy-boto3-s3</li>
    <li>python310Packages.pyathena</li>
    <li>python310Packages.pycognito</li>
    <li>python310Packages.rasterio</li>
    <li>python310Packages.s3transfer</li>
    <li>python310Packages.sagemaker</li>
    <li>python310Packages.sapi-python-client</li>
    <li>python310Packages.warrant</li>
    <li>python39Packages.aws-sam-translator</li>
    <li>python39Packages.boto3</li>
    <li>python39Packages.celery</li>
    <li>python39Packages.certbot-dns-route53</li>
    <li>python39Packages.cfn-lint</li>
    <li>python39Packages.cloudsplaining</li>
    <li>python39Packages.dependency-injector</li>
    <li>python39Packages.django-anymail</li>
    <li>python39Packages.django-raster</li>
    <li>python39Packages.django-rq</li>
    <li>python39Packages.djmail</li>
    <li>python39Packages.ec2instanceconnectcli</li>
    <li>python39Packages.fiona</li>
    <li>python39Packages.flower</li>
    <li>python39Packages.flowlogs_reader</li>
    <li>python39Packages.fs-s3fs</li>
    <li>python39Packages.gensim</li>
    <li>python39Packages.gradient</li>
    <li>python39Packages.hass-nabucasa</li>
    <li>python39Packages.mapbox</li>
    <li>python39Packages.moto</li>
    <li>python39Packages.mypy-boto3-builder</li>
    <li>python39Packages.mypy-boto3-s3</li>
    <li>python39Packages.parsedmarc</li>
    <li>python39Packages.pathy</li>
    <li>python39Packages.pyathena</li>
    <li>python39Packages.pycognito</li>
    <li>python39Packages.pyhiveapi</li>
    <li>python39Packages.rasterio</li>
    <li>python39Packages.s3transfer</li>
    <li>python39Packages.sagemaker</li>
    <li>python39Packages.sapi-python-client</li>
    <li>python39Packages.sentry-sdk</li>
    <li>python39Packages.slack-sdk</li>
    <li>python39Packages.slicedimage</li>
    <li>python39Packages.smart-open</li>
    <li>python39Packages.tensorboardx</li>
    <li>python39Packages.warrant</li>
    <li>s3bro</li>
    <li>s4cmd</li>
    <li>snakemake</li>
    <li>sourcehut.buildsrht</li>
    <li>sourcehut.coresrht</li>
    <li>sourcehut.dispatchsrht</li>
    <li>sourcehut.gitsrht</li>
    <li>sourcehut.hgsrht</li>
    <li>sourcehut.hubsrht</li>
    <li>sourcehut.listssrht</li>
    <li>sourcehut.mansrht</li>
    <li>sourcehut.pastesrht</li>
    <li>sourcehut.todosrht</li>
    <li>ssm-session-manager-plugin</li>
    <li>streamlit</li>
    <li>tribler</li>
  </ul>
</details>

**Comment by lamdor** [comment]
@fabaff This seems to be failing for me on `aarch64-darwin` on MacOS. The test failure I'm getting is:
```
error: builder for '/nix/store/w5nwvfn71y90b2nm6cfgqv5q1kvwhpq9-python3.9-s3transfer-0.5.0.drv' failed with exit code 1;
       last 10 log lines:
       >     with self.assertRaisesRegexp(
       >
       > tests/unit/test_subscribers.py::TestSubscribers::test_not_callable_in_subclass_subscriber_method
       >   /private/tmp/nix-build-python3.9-s3transfer-0.5.0.drv-0/source/tests/unit/test_subscribers.py:81: DeprecationWarning: Please use assertRaisesRegex instead.
       >     with self.assertRaisesRegexp(
       >
       > -- Docs: https://docs.pytest.org/en/stable/warnings.html
       > =========================== short test summary info ============================
       > FAILED tests/unit/test_compat.py::TestBaseManager::test_can_provide_signal_handler_initializers_to_start
       > =========== 1 failed, 601 passed, 28 skipped, 44 warnings in 23.11s ============
       For full logs, run 'nix log /nix/store/w5nwvfn71y90b2nm6cfgqv5q1kvwhpq9-python3.9-s3transfer-0.5.0.drv'.
```

It fails for me consistently.

Here's the full build log [s3transfer-build-log.txt](https://github.com/NixOS/nixpkgs/files/7857180/s3transfer-build-log.txt).

Please let me know if I can help run a specific branch/test to help or if maybe `tests/unit/test_compat.py` needs added to `disabledTestPaths`? I'm sort of at a loss on where to start to fix it.

**Comment by duckpuppy** [comment]
I'm getting the error on `x86_64-darwin` as well.

**Comment by YorikSar** [comment]
I'm also affected by this.

@lamdor @duckpuppy Did you happen to open an issue about this?

**Comment by lamdor** [comment]
@YorikSar I haven't yet had time to look more into it and create an issue. If someone beats me to it, that would be great.

**Comment by fabaff** [comment]
It still fails (https://hydra.nixos.org/eval/1738910?filter=s3transfer&compare=1738843&full=#tabs-still-fail).

Looks like that a condition for tests is needed for Darwin.

**Comment by fabaff** [comment]
Perhaps somebody from @NixOS/darwin-maintainers could help.

**Comment by thefloweringash** [comment]
This passes for me on python 3.7, but fails on 3.8 and 3.9 (and probably any later version). The stack trace implicates multiprocessing. There was a change in python 3.8 that defaults multiprocessing to `spawn` instead of `fork` on macOS ([bpo-33725](https://bugs.python.org/issue33725), https://github.com/python/cpython/pull/13603). I suspect the underlying issue here is that upstream tests aren't compatible with `spawn` multiprocessing, and pass on linux where the default is still `fork`.

**Comment by lamdor** [comment]
I submitted a PR which ignores that test_compat on darwin. I've verified that then it is able to build s3transfer without any issue: https://github.com/NixOS/nixpkgs/pull/155896

**Pull request merged**
