### PR TITLE
ffmpeg(and -full) updates, use SDL2 instead of SDL for versions >3.2

### PR DESCRIPTION
**Pull request by MP2E**
###### Motivation for this change
ffmpeg released version 3.3 recently so this updates both ffmpeg and ffmpeg-full, this PR also addresses issue #24658 

ffmpeg-full had 2 options removed, '--enable-memalign-hack' and '--enable-x11grab'.

x11grab was deprecated and removed in favor of libxcb, the memalign hacks configure option was fully removed from ffmpeg

as a side note, should older ffmpeg 3.x releases get removed?
###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
We should delete any ffmpeg that we can, meaning other packages can upgrade to newer ffmpegs.

**Comment by vcunat** [comment]
The announcement mentions nothing about backwards compatibility. I see a couple of fields [removed](https://abi-laboratory.pro/tracker/compat_report/ffmpeg/3.2.4/3.3/c9c8e/abi_compat_report.html#Type_Problems_High) from `struct AVFilterLink`. I suspect this won't cause a major problem and we can attempt to just update it like this.

**Comment by MP2E** [comment]
I added another commit removing ffmpeg 3.2 and 3.1 if we would like to go forward with removing them, however, this commit can also be safely ignored if instead it would be better to keep them. Either way is fine by me. ffmpeg 3.1 is not needed anymore because nothing in the tree depends on it, so we could also go the middle ground route and only remove ffmpeg_3_1.

**Comment by MP2E** [comment]
Travis found some programs that were depending on ffmpeg_3_2, changed those to use ffmpeg

**Review by fpletz — APPROVED** [review]

**Comment by MP2E** [comment]
After some testing, I went ahead and pushed! Would be happy to follow up with any issues if they arise.

**Pull request closed without merging**
