### PR TITLE
node-packages: update & cleanup

### PR DESCRIPTION
**Pull request by cko**
- update packages for v4
- remove files and generation for v0_10 and v5 packages as nodejs-5_x and nodejs-0_10 are no longer supported

(also discussed in #19966)

### CODE REVIEW

**Comment by vcunat** [comment]
Nitpick: in `pkgs/development/node-packages/node-env.nix` you seem to be just adding spaces to empty lines.

**Comment by gilligan** [comment]
We were discussing switching the nodejs default version from v4 to v6 - maybe you want to add this to this PR? Then i can close #19966

**Comment by cko** [comment]
@gilligan [x] done
@vcunat this file is generated and I didn't want to touch it manually

**Comment by gilligan** [comment]
@cko This PR updated `nodejs` to export nodejs-6 but `nodePackages` is still set to `nodePackages_4_x;`!

**Pull request merged**
