### PR TITLE
pythonPackages.tensorflow 1.0.0 -> 1.1.0

### PR DESCRIPTION
**Pull request by jyp**
###### Motivation for this change

Update to recent version

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
This package still needs a maintainer. Are you going to maintain this?

**Comment by jyp** [comment]
I plan to maintain it yes.

**Comment by FRidh** [comment]
Please add yourself as maintainer of this package. In the future, when you open a PR for this package, I'll simply merge it.

**Comment by jyp** [comment]
@FRidh Shall I update this PR to make myself maintainer, or create another one?

**Comment by FRidh** [comment]
no, in here

**Comment by jyp** [comment]
@FRidh done, let me know if I did anything wrong.

**Comment by FRidh** [comment]
Thanks. I squashed and pushed 7b5356ed5e89b5c241d89191a2350e402007e44d.

**Pull request closed without merging**
