### PR TITLE
nixos/version: allow overriding, use 24-bit colour code

### PR DESCRIPTION
**Pull request by SigmaSquadron**
<details>
<summary>1. use 24-bit ANSI colour code</summary>

It's almost 2025; we don't need to use 3-bit colour anymore. Let's use the [proper colour code](https://github.com/NixOS/nixos-artwork/blob/ea1384e183f556a94df85c7aa1dcd411f5a69646/logo/README.md#colours) for NixOS' light blue.

Other distributions have already done this:
1. [Fedora Linux](https://bugzilla.redhat.com/show_bug.cgi?id=1823099) (2020)
2. [Arch Linux](https://bugs.archlinux.org/task/66217) (2020) + some Arch forks
3. [Chimera Linux](https://github.com/chimera-linux/cports/commit/6cf871f61daae93631abe9028553891c4b09b5e8) (2022)

</details>

<details>
<summary>2. add <code>extraOSReleaseArgs</code> and <code>extraLSBReleaseArgs</code></summary>

A free-form `attrsOf str` option that is merged with the /etc/os-release
builder, allowing downstreams to customise arbitrary os-release fields.
This is separate from the variant option, as using an attribute set
merge means one gets an infinte recursion when making extraOSReleaseArgs
a recursive set, and the variant attribute is useful to define elsewhere
or multiple times.

This also removes the SUPPORT_END tag that was added erroneously to `unstable`.

</details>

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested basic functionality of all changes.
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md)
  - [ ] (Module updates) Added a release notes entry if the change is significant
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilazy** [comment]
Would it be possible to include the old colour as well for backwards compatibility with terminal emulators that don’t support 24‐bit colour? There are still some in wide use.

**Comment by emilazy** [comment]
Fair enough. It’s not about the screens so much as the terminal emulators, but admittedly I suspect a strong majority of non‐Terminal.app terminals have caught up by now.

**Comment by SigmaSquadron** [comment]
> Terminal.app

I... wasn't considering Darwin. Is this used by nix-darwin or standalone Nix on Darwin somehow?

**Comment by SigmaSquadron** [comment]
Looks like a lot of the changes from this PR were implemented elsewhere in the recent `staging-next` merged. There's only the ANSI_COLOR change and the override left.

**Review by RossComputerGuy — APPROVED** [review]

**Review by jopejoe1 — APPROVED** [review]

**Pull request merged**
