### PR TITLE
libav: support Darwin & install docs/manpages

### PR DESCRIPTION
**Pull request by ryanartecona**
#### Things done:
- [ ] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
  _This...didn't work for me. I got an "Operation not permitted" before any other output, but no other context._
- Built on platform(s)
  - [ ] NixOS
  - [x] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
  _I tried, but it took a long time and then failed building chromaprint. Not sure if it succeeded before, but TBH my laptop is almost out of juice._
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
##### darwin support

Looks like `$CC` defaults to gcc, which isn't in the darwin stdenv. Fixed that, so now it builds and runs for me on darwin.
##### extra tools

There are some auxiliary tools in libav like `qt-faststart` and `aviocat` which aren't compiled or installed by default. Here's the full list:

```
aviocat
cws2fws
graph2dot
ismindex
patcheck
pktdumper
probetest
qt-faststart
trasher
```

Not including the main `avconv` and `avprobe` executables. I wasn't sure if these new tools should go in a separate output or not. It looks like there's already an output named 'tools', but which only has `avplay` so that the main derivation doesn't keep the SDL dep. 
##### install the manpages

Also, docs/manuals I guess aren't built by default? It looks like they should be in `./configure --help`, but they didn't get installed for me unless I included the `install-doc` and `install-man` targets.

---

cc @vcunat

### CODE REVIEW

**Comment by vcunat** [comment]
> Not including the main avconv and avprobe executables.

The current state does install those two executables to the main output, at least on Linux.

**Comment by ryanartecona** [comment]
Oh, for sure. I meant those two were already being installed, since they
don't require special treatment.

On Friday, March 18, 2016, Vladimír Čunát <notifications@github.com> wrote:

> Not including the main avconv and avprobe executables.
>
> The current state does install those two executables to the main output,
> at least on Linux.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/pull/14005#issuecomment-198251002>
>


-- 
Ryan Artecona

**Comment by ryanartecona** [comment]
Looks like the travis build failed because the `install-doc` target wasn't there in libav v9.18. I'll take a look next chance I get.

**Comment by vcunat** [comment]
IIRC we might drop the older versions anyway.

**Comment by ryanartecona** [comment]
I don't see any references to `libav_9` anywhere, so that should be safe to drop. A couple packages still depend on `libav_0_8` specifically, though (keyfinder and oraclejdk/jdk-linux-base). 

Looks like the `install-doc` target is missing in older versions, but `install-man` is still there. I was more interested in at least getting the manpages installing, so I can just drop `install-doc` for now. I'll push a new commit and see if that passes.

**Comment by ryanartecona** [comment]
Looks like the latest CI build gets past building dependent packages, and only fails at the merge step. Safe to merge?

**Comment by vcunat** [comment]
It didn't build on sandboxed Linux, but I fixed that, and I updated the 11 branch.

**Pull request merged**
