### PR TITLE
python3Packages.spacy: 2.2.0 -> 2.2.1

### PR DESCRIPTION
**Pull request by danieldk**
###### Motivation for this change

Bugfix update to spaCy 2.2.0. One change fixes the tag mapping for Dutch. This also requires an updated model for Dutch, which is in the second commit.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by jonringer** [comment]
how does this play with the large model update you did?

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS
diff LGTM
patch
spacy executable seems to still work

```
https://github.com/NixOS/nixpkgs/pull/70333
2 package were build:
python37Packages.spacy python37Packages.textacy
```

**Comment by danieldk** [comment]
> how does this play with the large model update you did?

The model update updated all models to version 2.2.0. However, there was a bug in spaCy for Dutch, which requires updating just this model to version 2.2.1 (the other models are still at 2.2.0).

**Comment by jonringer** [comment]
I came to that realization, and just merged xD

**Pull request merged**
