### PR TITLE
calibre: fix epub-viewer

### PR DESCRIPTION
**Pull request by fabianhjr**
###### Description of changes

Fixes an issue with epub-viewer after the recent major version bump of calibre ( #194912 )

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kilianar** [comment]
Sorry for the inconvenience, i missed that when updating `calibre` and thanks for fixing the issue.

I think we can remove the fallowing reference to `pyqtwebengine` because it only provides python bindings for `Qt5`:
https://github.com/NixOS/nixpkgs/blob/ef0ed284ea6ce8d14de9575d1962e70590c29bfe/pkgs/applications/misc/calibre/default.nix#L127-L131

**Comment by khrj** [comment]
Hi, this is causing calibre (specifically `qtwebengine-6.4.0`) to be built from source, but I'm not sure why. This takes more than a few hours and results in OOM errors on a 16gb machine. I'm not sure why hydra didn't build qtwebengine-6.4.0 and I don't know how to check

**Comment by kilianar** [comment]
There is some discussion [at discourse](https://discourse.nixos.org/t/why-is-qt6-qtwebengine-failing-ulimit-n/19539/10) about this issue.

For a quick fix you can just remove `pyqt6-webengine` from the build inputs (most of the functionality should work without it).

**Comment by fabianhjr** [comment]
> Hi, this is causing calibre (specifically `qtwebengine-6.4.0`) to be built from source, but I'm not sure why. This takes more than a few hours and results in OOM errors on a 16gb machine. I'm not sure why hydra didn't build qtwebengine-6.4.0 and I don't know how to check

It causes qtwebengine-6 to be built because it is a dependency of calibre-6, specifically epub-viewer and other binaries.

If you don't need epub-viewer or other binaries that depend on qtwebengine-6 you could remove that dependency on a nixpkgs fork or override.

**Comment by fabianhjr** [comment]
> Sorry for the inconvenience, i missed that when updating calibre and thanks for fixing the issue.

No worries, thanks for the version upgrade :3

**Pull request merged**
