### PR TITLE
pahole: 1.24-unstable-2023-03-02 -> 1.25

### PR DESCRIPTION
**Pull request by trofi**
Use released tarball with latest DWARF changes support.

Changes: https://lore.kernel.org/bpf/ZDG4qxirpIfmbiip@kernel.org/T/

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by martinetd** [comment]
Thanks! I saw the release this morning and wanted to find time for this today :)

I notice we never added bpf tests to pahole's passthru, would you mind adding something like ↓ or I'll do it in a follow-up PR
```
  passthru.tests = {
    bpf = nixosTests.bpf;
  };
```

Meanwhile, I think that might work...
@ofborg build nixosTests.bpf

**Review by martinetd — APPROVED** [review]
aarch64 failing on kfunc is a known issue ( https://github.com/iovisor/bpftrace/issues/2496 incorrectly lead me to believe it should work ; sorry I forgot about it I'll fix the test)

The BTF part passed on both linux archs, so all good for me. I'll submit a separate patch for the passthru tests if you don't.

**Comment by trofi** [comment]
Added "pahole: add `nixosTests.bpf` to `passthru.tests`"

**Review by martinetd — APPROVED** [review]
Thanks!

**Pull request merged**
