### PR TITLE
override newaliases and mailq with symlinks

### PR DESCRIPTION
**Pull request by phunehehe**
ref https://github.com/NixOS/nixpkgs/issues/12017

### CODE REVIEW

**Comment by phunehehe** [comment]
@peti I'm sure this is ugly, but just FTR it seems to work
feel free to close in favor of a cleaner fix :)

**Comment by peti** [comment]
I don't know ... this "fix" seems like a really bad idea. The build process is broken in some way, and this patch manually overwrites some of the broken artifacts (that we are aware of). I'd rather not merge this patch but fix the Postfix build process instead.

**Comment by phunehehe** [comment]
(fully agree, I didn't mean for this to be merged or anything)

**Comment by phunehehe** [comment]
now that I come to think of it, maybe I should have closed immediately after opening :">

**Comment by phunehehe** [comment]
I'm thinking about reviving this, now that the problem seems to come from Postfix instead of Nixpkgs. Debian/Ubuntu does the same thing http://anonscm.debian.org/cgit/users/lamont/postfix.git/tree/debian/rules#n123.

**Comment by gebner** [comment]
Interestingly, the archlinux package doesn't need to fix anything: https://projects.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/postfix

**Comment by phunehehe** [comment]
@gebner I think that's because they don't define mailq_path and newaliases_path, in that case mailq and newaliases are simply not created. Looks like they are legacy commands.

**Pull request closed without merging**
