### PR TITLE
nixos/wireless: fix failure on missing config file 

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Description of changes

Fix issue #212347

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested via
  - [x] `nixosTests.wpa_supplicant`
  - [x] `nixosTests.connman`
- [x] Tested compilation of all packages that depend on this change (none)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by adamcstephens** [comment]
Should there be a test added for the wpa supplicant change? One to test that wpa supplicant starts without a config may be useful.

**Comment by rnhmjoj** [comment]
> One to test that wpa supplicant starts without a config may be useful.

It's exactly what the connman test does.

**Comment by adamcstephens** [comment]
> It's exactly what the connman test does.

Ok, but that's in the context of connman. The logic is in wpa supplicant. While this change benefits connman, it's not limited to the use with connman.

**Comment by rnhmjoj** [comment]
> While this change benefits connman, it's not limited to the use with connman.

It pretty much is: without a configuration file you can only control wpa_supplicant from dbus, so essentially only connman and maybe NetworkManager. I could just test that the daemon is running without connman.

**Comment by rnhmjoj** [comment]
I should have fixed the test unrealiability.

**Comment by adamcstephens** [comment]
I'm disappointed that my feedback was dismissed without consideration and that you merged this without any approvals or supporting feedback. While this is possible given your privileges, I consider it poor practice.

**Comment by rnhmjoj** [comment]
> I'm disappointed that my feedback was dismissed without consideration

I did consider your suggestion and I tried to explain why I don't think an additional test is useful.
Since you gave my comment a thumb up I assumed you had agreed with this, I didn't mean to dismiss you.

I'll explain further: when changing a NixOS module one should ideally run all related tests to make sure it won't break any functionality. So, whether this case is tested in `nixosTests.wpa_supplicant` or `nixosTests.connman` it shouldn't matter. Also, testing this in `nixosTests.wpa_supplicant` or elsewhere would require starting an additional VM or building a specialised config: quite expensive for a redudant check.

> I consider it poor practice.

Given the issue has been up a week, that nobody else commented on the PR, the fix is trivial and I am the only maintainer of this module, I don't think it's inappropriate.

**Pull request merged**
