### PR TITLE
thunderbird: 102.13.0 -> 115.0

### PR DESCRIPTION
**Pull request by NickCao**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NickCao** [comment]
`thunderbird-bin` works fine, now building from source.

**Comment by drupol** [comment]
To test it: `nix run "github:NixOS/nixpkgs?ref=pull/242970/head#thunderbird"`

**Review by drupol — APPROVED** [review]

**Comment by NickCao** [comment]
There seem to be some issues with the source build, like the sidebar for opening calendar/chat is missing.

**Comment by NickCao** [comment]
> There seem to be some issues with the source build, like the sidebar for opening calendar/chat is missing.

Which, according to the debug console, has something to do with timezones:
screenshot-2023-07-12-19-06-02

And `export TZ=UTC` does workaround the issue.

**Comment by drupol** [comment]
Let me know if you made an update PR, I'll review it

**Comment by NickCao** [comment]
I have no idea how to properly fix this, as the same issue does not manifest on the official binaries.

**Comment by NickCao** [comment]
I think I'm getting close to the bottom of the rabbit hole, the following snippet

```js
let db = Cc["@mozilla.org/calendar/timezone-database;1"].getService(Ci.calITimezoneDatabase)
db.getTimezoneDefinition("Asia/Shanghai")
```

evaluates to

```
"BEGIN:VTIMEZONE
TZID:Asia/Shanghai
X-TZINFO:Asia/Shanghai[2023c]
<redacted>
```

in the official binaries, but to

```
"BEGIN:VTIMEZONE
TZID:Asia/Shanghai
Asia/Shanghai[2023c]
BEGIN:STANDARD
<redacted>
```

in our build, and the result seem to get parsed by an [ical parser](https://github.com/darktrojan/ical.js), which bails out on the offending line.

**Comment by drupol** [comment]
wow, nice finding, how come it does that?

**Comment by NickCao** [comment]
The backing implementation is at https://github.com/mozilla/releases-comm-central/blob/7ae1cedd6ee55b7c7d9310f9e733af8e3870e02f/calendar/base/src/TimezoneDatabase.cpp#L66, so we can blame icu again?

**Comment by NickCao** [comment]
Got a minimal reproduce of the output, but the result does not seem to differ on icu72

```cpp
#include <unicode/vtzone.h>
#include <unicode/ustream.h>
#include <iostream>

int main() {
  auto* icuTimezone = icu::VTimeZone::createVTimeZoneByID("Asia/Shanghai");
  icu::UnicodeString vtimezoneDef;
  UErrorCode err = U_ZERO_ERROR;
  icuTimezone->write(vtimezoneDef, err);
  std::cout << vtimezoneDef << std::endl;
}

```

**Comment by vcunat** [comment]
Could this be related to this Firefox issue?
https://github.com/NixOS/nixpkgs/issues/238025

**Comment by NickCao** [comment]
That one is due to firefox sandbox, this does not seem to be.

**Comment by mweinelt** [comment]
Requires a backport to stable, but let's not just yet make 115 the default on stable.

FWIW: I think skipping the maintainer review and immediately going for the default version was not ideal, given our lack of experience with the new release.

**Comment by vcunat** [comment]
Yeah, it would be most likely OK to go this fast with the usual non-major updates but this case 
surprised me.

**Comment by NickCao** [comment]
Got Arch Linux users to.reproduce the bug. Shall we file this upstream then?

**Comment by vcunat** [comment]
I mean, I personally don't put much weight into contents of `.meta.maintainers`; here I meant the speed and amount of testing.

**Comment by natsukagami** [comment]
Could it be something related to this? https://bugzilla.mozilla.org/show_bug.cgi?id=1790071 https://unicode-org.atlassian.net/browse/ICU-22132

**Comment by mweinelt** [comment]
Looks too old I think, and was resolved in Firefox 107, which is 9 months old at this point.

**Comment by vcunat** [comment]
So either we apply this in our `icu` or we let Thunderbird use its vendored `icu`?

**Comment by natsukagami** [comment]
I can confirm building thunderbird with a patched `icu` solves the problem

**Comment by lovesegfault** [comment]
I suspect the better solution here is letting Thunderbird vendor `icu`, at least then we don't risk breaking others by applying their patch to the global pkg...

Not sure, neither option is great.

**Comment by vcunat** [comment]
I agree neither is great, which is why I pinged the upstream issue.

**Comment by natsukagami** [comment]
Looks like Arch Linux is letting thunderbird use the vendored `icu`: https://gitlab.archlinux.org/archlinux/packaging/packages/thunderbird/-/commit/b50b933d22d7277d2833945fbf27e7551af5014b

**Comment by mweinelt** [comment]
I think adding it to `extraPatches` on thunderbird-115 is the least invasive way.

**Comment by vcunat** [comment]
What do you think about adding versioned top-level attributes like we have `firefox-esr*`?  Otherwise it's e.g. cumbersome to use a wrapped non-default version.

**Comment by NickCao** [comment]
I'm somehow against adding these logic to `all-packages.nix`, we'd better handle these wrappings in the `thunderbirdPackages` package set.

**Comment by kevincox** [comment]
Actually even with the timezone set I am getting error synchronizing some calendars resulting in them not appearing at all.

**Comment by kevincox** [comment]
```
Calendar: NS_ERROR_XPC_JS_THREW_JS_OBJECT: ParserError: invalid line (no token ";" or ":") "America/Toronto[2023c]"'ParserError: invalid line (no token ";" or ":") "America/Toronto[2023c]"' when calling method: [calITimezoneService::getTimezone]
    getTimezone resource:///modules/calendar/calStorageHelpers.jsm:83
    newDateTime resource:///modules/calendar/calStorageHelpers.jsm:111
    getEventFromRow resource:///modules/calendar/CalStorageItemModel.jsm:690
    getEventFromRow resource:///modules/calendar/CalStorageCachedItemModel.jsm:159
    start resource:///modules/calendar/CalStorageItemModel.jsm:195
    handleResultInner resource:///modules/calendar/CalStorageDatabase.jsm:236
CalStorageDatabase.jsm:250
```

**Comment by kevincox** [comment]
Yeah, I just saw that a few minutes ago and am building now.

**Comment by kevincox** [comment]
I can confirm that https://github.com/NixOS/nixpkgs/pull/243179 fixes that issue. My calendars are now all loading.

**Pull request merged**
