### PR TITLE
meson: 0.57.1 -> 0.59.1

### PR DESCRIPTION
**Pull request by sefidel**
###### Motivation for this change
Bump versions.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by jtojnar — COMMENTED** [review]
Changes look okay:

- https://mesonbuild.com/Release-notes-for-0-58-0.html
- https://mesonbuild.com/Release-notes-for-0-59-0.html

but this will likely break systemd and maybe other packages, see https://github.com/NixOS/nixpkgs/pull/124806

**Comment by boppyt** [comment]
I see. Maybe I should either close/set this to draft for now?

**Comment by risicle** [comment]
Successfully built `knot-resolver` `glib` `cairomm` `pangomm` `harfbuzz` `dav1d` `atk` `gegl` on macos 10.15 & nixos x86_64.

**Comment by colemickens** [comment]
Thanks for this, I steal these meson PRs for `nixpkgs-wayland` since wlroots/sway/wayfire want newest meson often.

**Comment by primeos** [comment]
I guess this PR can be closed in favor of https://github.com/NixOS/nixpkgs/pull/144779 now. Feel free to reopen if I'm wrong.

**Pull request closed without merging**
