### PR TITLE
nixdoc: init at 1.0.1

### PR DESCRIPTION
**Pull request by tazjin**
###### Motivation for this change

Adds nixdoc, a tool to generate documentation for Nix functions in the
standard library.

See #49275 for some background information.

Note that the derivation used is generated by `carnix` and rather large, as there is no Rust package set in `nixpkgs`. This is similar to the derivation used for `carnix` itself, and `way-cooler`.

cc: @grahamc @jD91mZM2 @joachifm 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Infinisil** [comment]
@Grahamcofborg build nixdoc

**Comment by Mic92** [comment]
I have changed it back to `buildRustPackage` to reduce the expression size (25 lines instead of 866 lines) https://github.com/Mic92/nixpkgs/commit/064f35037aaa007487a26637c18a45edcbee6759

**Comment by tazjin** [comment]
@Mic92 Works for me! It looks like Hydra doesn't currently have `rustc` cached, so we'll have to ask for a build at some later time.

**Comment by Mic92** [comment]
I prefer https://github.com/NixOS/nixpkgs/pull/49275

**Comment by Mic92** [comment]
@tazjin I was confused by the UI. It looked like your other pull request contained my commit already, but It was just a reference.

**Comment by Mic92** [comment]
https://github.com/NixOS/nixpkgs/pull/49358

**Pull request closed without merging**
