### PR TITLE
udiskie: 1.7.2 -> 1.7.3

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

/cc maintainer @AndersonTorres

### CODE REVIEW

**Comment by dotlambda** [comment]
I also propose to migrate udiskie to python3 because py2 is deprecated since version 1.7.2.

**Comment by adisbladis** [comment]
I changed it to python 3 in https://github.com/NixOS/nixpkgs/commit/f772b8d2983ff75d460ab1d85fe067ccef866fb7

Works nicely. Thanks!

**Comment by mdorman** [comment]
Attempting to build this fails for me:
```
installing
/tmp/nix-build-udiskie-1.7.3.drv-0/source/dist /tmp/nix-build-udiskie-1.7.3.drv-0/source
Processing ./udiskie-1.7.3-py2-none-any.whl
Collecting PyYAML (from udiskie==1.7.3)
  Could not find a version that satisfies the requirement PyYAML (from udiskie==1.7.3) (from versions: )
No matching distribution found for PyYAML (from udiskie==1.7.3)
```

**Comment by adisbladis** [comment]
@mdorman Sorry.. My bad. Fixed in https://github.com/NixOS/nixpkgs/commit/afab19eabdf82271779160a304d82b6b89148ebb

**Pull request merged**
