### PR TITLE
python3Packages.pygments: 2.7.4 -> 2.8.1

### PR DESCRIPTION
**Pull request by mbrgm**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by dotlambda — CHANGES_REQUESTED** [review]
Please add `pythonImportsCheck` and correct the commit message.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 116710` at ca8f9a24 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>745 packages marked as broken and skipped:</summary>
  <ul>
    <li>adobe-reader</li>
    <li>agdaPackages.iowa-stdlib</li>
    <li>aldor</li>
    <li>aliceml</li>
    <li>alliance</li>
    <li>amule</li>
    <li>amuleDaemon</li>
    <li>amuleGui</li>
    <li>aqemu</li>
    <li>atom-beta</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>20817 packages skipped due to time constraints:</summary>
  <ul>
    <li>AusweisApp2</li>
    <li>EBTKS</li>
    <li>EmptyEpsilon</li>
    <li>Fabric</li>
    <li>Literate</li>
    <li>MIDIVisualizer</li>
    <li>MMA</li>
    <li>OSCAR</li>
    <li>OVMF</li>
    <li>OVMF-CSM</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>80 packages built successfully:</summary>
  <ul>
    <li><a href="https://gist.github.com/da1f91d56aa8228c4207ced89fd98d04">asciidoctor</a></li></li>
    <li><a href="https://gist.github.com/9ec3770f5f875ab4762faf07446155dd">atk</a></li> (gnome2.atk ,gnome3.atk)</li>
    <li><a href="https://gist.github.com/ff0cab799953decb57c6201ffaebf504">cairo</a></li> (gnome2.cairo)</li>
    <li><a href="https://gist.github.com/b3e5b39dc8f6b04de6de71c1998e1562">epoxy</a></li></li>
    <li><a href="https://gist.github.com/d198a35aea7d39e02cd2b50aa306895c">fontconfig</a></li></li>
    <li><a href="https://gist.github.com/06e9de306985f25b14e16538a07104f6">gd</a></li></li>
    <li><a href="https://gist.github.com/31627957f7efb3f6d0a683c897199684">gdk-pixbuf</a></li></li>
    <li><a href="https://gist.github.com/06246e01c5107a1528b7e17ed60c3eb2">glib</a></li> (gnome2.glib ,gnome3.glib)</li>
    <li><a href="https://gist.github.com/761029602c3e2af3efaba4b92f941d76">gtk-doc</a></li> (gnome2.gtkdoc)</li>
    <li><a href="https://gist.github.com/df8bc4b7bfe999a24f2f5605b84dbbdc">gobject-introspection</a></li> (gnome3.gobject-introspection)</li>
    <li><a href="https://gist.github.com/f516aff02009fd51389f68e49d2b306c">gsettings-desktop-schemas</a></li> (gnome3.gsettings-desktop-schemas)</li>
    <li><a href="https://gist.github.com/fc284abb251b849094f423e5aeac26a5">gts</a></li></li>
    <li><a href="https://gist.github.com/c7ee96bb0497225207557df88404dad0">harfbuzz</a></li></li>
    <li><a href="https://gist.github.com/5f8f193360498008e062de77d60fc461">json-glib</a></li></li>
    <li>libGL</li>
    <li><a href="https://gist.github.com/1dec987045bec974401bf0512c141109">libqrtr-glib</a></li></li>
    <li><a href="https://gist.github.com/0ed6ffcf4180478181b1a443cd009435">libva</a></li></li>
    <li><a href="https://gist.github.com/d815fadef66b5a531195ef7b66ab1025">libva-minimal</a></li></li>
    <li><a href="https://gist.github.com/c0e38cf1e03d744d164ff9d364651a0d">mesa</a></li></li>
    <li><a href="https://gist.github.com/a6f336f9da730605c4a60bd29f490543">pango</a></li></li>
    <li><a href="https://gist.github.com/45194f2e8befafb233409771b21c9d94">python38Packages.Babel</a></li></li>
    <li><a href="https://gist.github.com/f70c4c1466402f1576aa0d108001c52b">python38Packages.Mako</a></li></li>
    <li><a href="https://gist.github.com/ee91663e0c40a266df7910ac329dd4dc">python38Packages.alabaster</a></li></li>
    <li><a href="https://gist.github.com/f19c8c5f96968470f8c6395349475e8e">python38Packages.apipkg</a></li></li>
    <li><a href="https://gist.github.com/8bc69ff9c133f2d6946e7e1302105a6d">python38Packages.astor</a></li></li>
    <li><a href="https://gist.github.com/63f0175142d0f8f7f6afbdb277891b18">python38Packages.async_generator</a></li></li>
    <li><a href="https://gist.github.com/39717e3014de8aaf91fdf7db08ea966b">python38Packages.backcall</a></li></li>
    <li><a href="https://gist.github.com/4de36a1a54ede5fc9b315c89758e3860">python38Packages.blinker</a></li></li>
    <li><a href="https://gist.github.com/c3c1bf8d45b538d34a723c70b44005b4">python38Packages.brotli</a></li></li>
    <li><a href="https://gist.github.com/71de8f516ab5c05fa698237a93fe14c1">python38Packages.click</a></li></li>
    <li><a href="https://gist.github.com/80ee192fa24268fd6ffe8fd2cea0ca4b">python38Packages.entrypoints</a></li></li>
    <li><a href="https://gist.github.com/e4c8cc5ec9bf7dd58b72e180dc9b51c0">python38Packages.execnet</a></li></li>
    <li><a href="https://gist.github.com/95b882cc7a68b9eaf4a3cd252744e4ad">python38Packages.flake8</a></li></li>
    <li><a href="https://gist.github.com/15776ad4910ad640e2047fc2bef93f2d">python38Packages.flaky</a></li></li>
    <li><a href="https://gist.github.com/cad78dd970dc2cb636c695c10399ad4a">python38Packages.fontforge</a></li></li>
    <li><a href="https://gist.github.com/9b653be532c876bbac2ef93a658b1821">python38Packages.freezegun</a></li></li>
    <li><a href="https://gist.github.com/174a3fd2a6d50beb5b3b9adef678e6d8">python38Packages.gunicorn</a></li></li>
    <li><a href="https://gist.github.com/9ae61be7824fe5def2d832e1c51593ca">python38Packages.html5lib</a></li></li>
    <li><a href="https://gist.github.com/b37b791c8ec702291ca5e7280b9eb76a">python38Packages.intreehooks</a></li></li>
    <li><a href="https://gist.github.com/5027b7ba95c0815291d1922958bfee1a">python38Packages.iso8601</a></li></li>
    <li><a href="https://gist.github.com/768c940221c8a4b26ccca5f5a58213ce">python38Packages.jdcal</a></li></li>
    <li><a href="https://gist.github.com/2beedea1075d081d2d7f18c4e738917f">python38Packages.jinja2</a></li></li>
    <li><a href="https://gist.github.com/4b93d2e7d8a34cd2c01301f13675a8d2">python38Packages.jupyterlab-pygments</a></li></li>
    <li><a href="https://gist.github.com/1649cc50608678c89b9d8e2f9f862eb2">python38Packages.libevdev</a></li></li>
    <li><a href="https://gist.github.com/a597f0ef069228cc56472bd391d8c0fe">python38Packages.mccabe</a></li></li>
    <li><a href="https://gist.github.com/19eba5abdec983825194a24dba597d2b">python38Packages.munkres</a></li></li>
    <li><a href="https://gist.github.com/7cb0c04b7f160344cd27bb5a52038573">python38Packages.pastel</a></li></li>
    <li><a href="https://gist.github.com/1a327df0ea9828855d0ae551e5a3a162">python38Packages.pep517</a></li></li>
    <li><a href="https://gist.github.com/8ad474c9ff43024045f7984f5995bde5">python38Packages.psutil</a></li></li>
    <li><a href="https://gist.github.com/6661418e8dfcc836290323fee46b6693">python38Packages.pyasn1-modules</a></li></li>
    <li><a href="https://gist.github.com/e27a228a2b33475508b90bc74a2e5681">python38Packages.pycairo</a></li></li>
    <li><a href="https://gist.github.com/06a8dd89384a1e56d25e5adf06480626">python38Packages.pydocstyle</a></li></li>
    <li><a href="https://gist.github.com/0b51d4c2704170fc121160775b085de9">python38Packages.pygments</a></li></li>
    <li><a href="https://gist.github.com/b066b80664d8b00f9c8043db93ef1b81">python38Packages.pygobject3</a></li></li>
    <li><a href="https://gist.github.com/78b2d0601f3e191a60dbf64c2eb92c36">python38Packages.pylama</a></li></li>
    <li><a href="https://gist.github.com/017aa6c997a7cfa284ffd693f94ad088">python38Packages.pytest</a></li> (python38Packages.pytest_6)</li>
    <li><a href="https://gist.github.com/0aae6caf620374c008a35158e91b09ff">python38Packages.pytest-asyncio</a></li></li>
    <li><a href="https://gist.github.com/2876940d3d63730ea7a586913227ee62">python38Packages.pytestcov</a></li> (python38Packages.pytest-cov)</li>
    <li><a href="https://gist.github.com/6d39fbe15c11f6a54cf514e094958107">python38Packages.pytest-expect</a></li></li>
    <li><a href="https://gist.github.com/6c1fb12d75f9ef6ac2895fe7f537f8cf">python38Packages.pytest-flake8</a></li></li>
    <li><a href="https://gist.github.com/dc15a35ac03a39136171b9bc63224e0b">python38Packages.pytest-forked</a></li></li>
    <li><a href="https://gist.github.com/36ca701691f90c35aa28bf504794b5e1">python38Packages.pytest-freezegun</a></li></li>
    <li><a href="https://gist.github.com/e1e4c361669f0d51463687146a1d1f6b">python38Packages.pytest-mock</a></li></li>
    <li><a href="https://gist.github.com/91d19195c2604e805733a4304aeb366d">python38Packages.pytestrunner</a></li> (python38Packages.pytest-runner)</li>
    <li><a href="https://gist.github.com/bb5f02372a2607d1a0ede65ba37fc9bf">python38Packages.pytest-subtests</a></li></li>
    <li><a href="https://gist.github.com/e5b95c10473c7b3a30c68e50a65b5623">python38Packages.pytest-xdist</a></li> (python38Packages.pytest_xdist)</li>
    <li>python38Packages.pytestCheckHook</li>
    <li><a href="https://gist.github.com/8fcf678aa78c4bf0b95eebceace17dce">python38Packages.pytoml</a></li></li>
    <li><a href="https://gist.github.com/8f1de14f1a0469126096e7a0c2cab16e">python38Packages.send2trash</a></li></li>
    <li><a href="https://gist.github.com/9e9bcedf91da67f9c6ed6f65bb99ff6c">python38Packages.simplejson</a></li></li>
    <li><a href="https://gist.github.com/faf7fadd82038e24de40b49439532c01">python38Packages.sqlparse</a></li></li>
    <li><a href="https://gist.github.com/e2d32f4e7a8d64218ab64eb00a418b66">python38Packages.text-unidecode</a></li></li>
    <li><a href="https://gist.github.com/870ee2b54ac65e8fae1d01c00b935a71">python38Packages.webencodings</a></li></li>
    <li><a href="https://gist.github.com/7f48e76d39f014e3bf644269c812c13c">python38Packages.whoosh</a></li></li>
    <li><a href="https://gist.github.com/cd841649e0b06795f6068b23d7318992">shared-mime-info</a></li></li>
    <li><a href="https://gist.github.com/f4fb2ae66c49f26a1dc7268d1cd5128d">volk</a></li></li>
    <li><a href="https://gist.github.com/fd665d668899d2ef0fd0b8524841b529">wayland</a></li></li>
    <li><a href="https://gist.github.com/b95ff7f73cafb1fa1768b04942d31bea">wayland-protocols</a></li></li>
    <li><a href="https://gist.github.com/c4161560345b360243886aba618c75af">xlibsWrapper</a></li> (xorg.xlibsWrapper)</li>
    <li><a href="https://gist.github.com/2f9f82475cee7497629d1342a0a75207">xorg.libXft</a></li></li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/Pygments/default.nix:25:5:
```
   |
25 |     maintainers = with lib.maintainers; [ ];
   |     ^
```
</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 116710` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages built:
</summary>
<ul>
<li>python38Packages.pygments</li>
<li>python39Packages.pygments</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
python38Packages.pygments:
<details>


warning: maintainers-missing
Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/Pygments/default.nix:25:5:

```
   |
25 |     maintainers = with lib.maintainers; [ ];
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md
warning: python-include-tests
Add a `checkPhase` for tests, or at least `pythonImportsCheck`.

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/python-include-tests.md
</details>
</details>

**Review by dotlambda — APPROVED** [review]

**Comment by FRidh** [comment]
part of https://github.com/NixOS/nixpkgs/pull/117452

**Pull request closed without merging**
