### PR TITLE
gocd-agent: 16.9.0-4001 -> 19.3.0-8959

### PR DESCRIPTION
**Pull request by cryptix**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Infinisil** [comment]
@GrahamcOfBorg build gocd-agent

Pinging the maintainers @grahamc and @swarren83

**Comment by c0bw3b** [comment]
@GrahamcOfBorg test gocd-agent

**Review by grahamc — APPROVED** [review]

**Comment by Infinisil** [comment]
Test is failing

**Comment by cryptix** [comment]
I deployed these into nixops container and made a small pipeline that does it's job.

I'm fairly new to the gocd project so I'm not sure I can interpret the test failure but looking at [the log](https://logs.nix.ci/?key=nixos/nixpkgs.61309&attempt_id=db70c4d0-4a08-4aa5-897a-b1368b81ef58), it looks like it started but then there might be some API change.

```
...
gocd_agent: running command: nc -z localhost 8153
gocd_agent# Connection to localhost 8153 port [tcp/quantastor] succeeded!
gocd_agent: exit status 0
(0.06 seconds)
(274.06 seconds)
gocd_agent: waiting for unit ‘gocd-agent’
gocd_agent: running command: systemctl --no-pager show "gocd-agent"
gocd_agent: exit status 0
(0.44 seconds)
(0.44 seconds)
gocd_agent: waiting for success: curl localhost:8153/go/api/agents -H 'Accept: application/vnd.go.cd.v2+json' | /nix/store/ng0k22dgkj8wk1b4akiw0h8h51m4d8jp-jq-1.6-bin/bin/jq -e ._embedded.agents[0].uuid
gocd_agent: running command: curl localhost:8153/go/api/agents -H 'Accept: application/vnd.go.cd.v2+json' | /nix/store/ng0k22dgkj8wk1b4akiw0h8h51m4d8jp-jq-1.6-bin/bin/jq -e ._embedded.agents[0].uuid
gocd_agent#   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
gocd_agent#                                  Dload  Upload   Total   Spent    Left  Speed
100   201    0   201    0     0     55      0 --:--:--  0:00:03 --:--:--    55
gocd_agent: exit status 1
(3.84 seconds)
...
```

and then it repeats the same `curl .. | jq ..` over and over. So I guess that is [this line in the test](https://github.com/NixOS/nixpkgs/blob/62d4c2b34a10afea0365a70e6901a3fc888d9288/nixos/tests/gocd-agent.nix#L37). I'm not familiar with these yet but will try running them.

I'm also not sure if this needs #61310 first but it doesn't look like [the API](https://api.gocd.org/current/#get-all-agents) that is queried changed.

**Comment by cryptix** [comment]
when I run the test locally, the agent restarts over and over:

```
gocd_agent# [  219.374789] systemd[1]: gocd-agent.service: Scheduled restart job, restart counter is at 4.
gocd_agent# [  219.377574] systemd[1]: Stopped GoCD Agent.
gocd_agent# [  219.380694] systemd[1]: Started GoCD Agent.
gocd_agent# [  219.746891] ksv8q94kadpp60pd27vjf7mlv9kk3l6d-unit-script-gocd-agent-start[1097]: [Sat May 25 10:05:02 GMT 2019] Starting process:
gocd_agent# [  219.748384] ksv8q94kadpp60pd27vjf7mlv9kk3l6d-unit-script-gocd-agent-start[1097]: [Sat May 25 10:05:02 GMT 2019]   Working directory    : /var/lib/go-agent
gocd_agent# [  219.750021] ksv8q94kadpp60pd27vjf7mlv9kk3l6d-unit-script-gocd-agent-start[1097]: [Sat May 25 10:05:02 GMT 2019]   Application arguments: [-serverUrl, https://127.0.0.1:8154/go]
gocd_agent# [  219.756212] ksv8q94kadpp60pd27vjf7mlv9kk3l6d-unit-script-gocd-agent-start[1097]: [Sat May 25 10:05:02 GMT 2019]            GoCD Version: 19.3.0-8959
gocd_agent# [  220.134281] ksv8q94kadpp60pd27vjf7mlv9kk3l6d-unit-script-gocd-agent-start[1097]: Could not find file `config/agent-bootstrapper-logback.xml'. Attempting to load from classpath.
gocd_agent# [  220.136116] ksv8q94kadpp60pd27vjf7mlv9kk3l6d-unit-script-gocd-agent-start[1097]: Using classpath resource `jar:onejar:lib/agent-bootstrapper-19.3.0-8959-classes.jar!/config/agent-bootstrapper-logback.xml'.
gocd_agent# [  220.517214] ksv8q94kadpp60pd27vjf7mlv9kk3l6d-unit-script-gocd-agent-start[1097]: SLF4J: Class path contains multiple SLF4J bindings.
gocd_agent# [  220.518758] ksv8q94kadpp60pd27vjf7mlv9kk3l6d-unit-script-gocd-agent-start[1097]: SLF4J: Found binding in [jar:onejar:lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
gocd_agent# [  220.521006] ksv8q94kadpp60pd27vjf7mlv9kk3l6d-unit-script-gocd-agent-start[1097]: SLF4J: Found binding in [jar:file:/var/lib/go-agent/data/deps-c70875047c6215d7-agent-launcher.jar/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
gocd_agent# [  220.526965] ksv8q94kadpp60pd27vjf7mlv9kk3l6d-unit-script-gocd-agent-start[1097]: SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
gocd_agent# [  220.585098] ksv8q94kadpp60pd27vjf7mlv9kk3l6d-unit-script-gocd-agent-start[1097]: SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
gocd_agent# [  220.603913] ksv8q94kadpp60pd27vjf7mlv9kk3l6d-unit-script-gocd-agent-start[1097]: Could not find file `config/agent-launcher-logback.xml'. Attempting to load from classpath.
gocd_agent# [  220.605733] ksv8q94kadpp60pd27vjf7mlv9kk3l6d-unit-script-gocd-agent-start[1097]: Using classpath resource `jar:file:/var/lib/go-agent/data/deps-c70875047c6215d7-agent-launcher.jar/agent-launcher-19.3.0-8959-classes.jar!/config/agent-launcher-logback.xml'.
gocd_agent# [  230.754302] ksv8q94kadpp60pd27vjf7mlv9kk3l6d-unit-script-gocd-agent-start[1097]: Already running agent launcher in this folder.
gocd_agent# [  241.800760] systemd[1]: gocd-agent.service: Main process exited, code=exited, status=173/n/a
gocd_agent# [  241.801840] systemd[1]: gocd-agent.service: Failed with result 'exit-code'.
gocd_agent# [  271.871831] systemd[1]: gocd-agent.service: Service RestartSec=30s expired, scheduling restart.
gocd_agent# [  271.875521] systemd[1]: gocd-agent.service: Scheduled restart job, restart counter is at 5.
gocd_agent# [  271.877586] systemd[1]: Stopped GoCD Agent.
gocd_agent# [  271.882729] systemd[1]: Started GoCD Agent.
gocd_agent# [  272.273748] ksv8q94kadpp60pd27vjf7mlv9kk3l6d-unit-script-gocd-agent-start[1143]: [Sat May 25 10:05:55 GMT 2019] Starting process:
gocd_agent# [  272.275266] ksv8q94kadpp60pd27vjf7mlv9kk3l6d-unit-script-gocd-agent-start[1143]: [Sat May 25 10:05:55 GMT 2019]   Working directory    : /var/lib/go-agent
gocd_agent# [  272.277025] ksv8q94kadpp60pd27vjf7mlv9kk3l6d-unit-script-gocd-agent-start[1143]: [Sat May 25 10:05:55 GMT 2019]   Application arguments: [-serverUrl, https://127.0.0.1:8154/go]
gocd_agent# [  272.282185] ksv8q94kadpp60pd27vjf7mlv9kk3l6d-unit-script-gocd-agent-start[1143]: [Sat May 25 10:05:55 GMT 2019]            GoCD Version: 19.3.0-8959
gocd_agent# [  272.662018] ksv8q94kadpp60pd27vjf7mlv9kk3l6d-unit-script-gocd-agent-start[1143]: Could not find file `config/agent-bootstrapper-logback.xml'. Attempting to load from classpath.
gocd_agent# [  272.663806] ksv8q94kadpp60pd27vjf7mlv9kk3l6d-unit-script-gocd-agent-start[1143]: Using classpath resource `jar:onejar:lib/agent-bootstrapper-19.3.0-8959-classes.jar!/config/agent-bootstrapper-logback.xml'.
gocd_agent# [  273.054640] ksv8q94kadpp60pd27vjf7mlv9kk3l6d-unit-script-gocd-agent-start[1143]: SLF4J: Class path contains multiple SLF4J bindings.
gocd_agent# [  273.056229] ksv8q94kadpp60pd27vjf7mlv9kk3l6d-unit-script-gocd-agent-start[1143]: SLF4J: Found binding in [jar:onejar:lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
gocd_agent# [  273.057992] ksv8q94kadpp60pd27vjf7mlv9kk3l6d-unit-script-gocd-agent-start[1143]: SLF4J: Found binding in [jar:file:/var/lib/go-agent/data/deps-22350876eb6f4069-agent-launcher.jar/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
gocd_agent# [  273.065251] ksv8q94kadpp60pd27vjf7mlv9kk3l6d-unit-script-gocd-agent-start[1143]: SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
gocd_agent# [  273.126405] ksv8q94kadpp60pd27vjf7mlv9kk3l6d-unit-script-gocd-agent-start[1143]: SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
gocd_agent# [  273.144871] ksv8q94kadpp60pd27vjf7mlv9kk3l6d-unit-script-gocd-agent-start[1143]: Could not find file `config/agent-launcher-logback.xml'. Attempting to load from classpath.
gocd_agent# [  273.146574] ksv8q94kadpp60pd27vjf7mlv9kk3l6d-unit-script-gocd-agent-start[1143]: Using classpath resource `jar:file:/var/lib/go-agent/data/deps-22350876eb6f4069-agent-launcher.jar/agent-launcher-19.3.0-8959-classes.jar!/config/agent-launcher-logback.xml'.
gocd_agent# [  283.292279] ksv8q94kadpp60pd27vjf7mlv9kk3l6d-unit-script-gocd-agent-start[1143]: Already running agent launcher in this folder.
gocd_agent# [  294.338727] systemd[1]: gocd-agent.service: Main process exited, code=exited, status=173/n/a
gocd_agent# [  294.339889] systemd[1]: gocd-agent.service: Failed with result 'exit-code'.
```

I'm not sure what is different from my nixops setup but I will try to figure it out.

**Comment by flokli** [comment]
While porting the tests to python (https://github.com/NixOS/nixpkgs/pull/74082), I stumbled over the tests already currently being broken on master. It seems to be a misconfiguration there. Could you maybe take a look?

**Comment by grahamc** [comment]
@GrahamcOfBorg build gocd-server

**Pull request merged**
