### PR TITLE
alacritty: 0.3.3 -> 0.4.0

### PR DESCRIPTION
**Pull request by Br1ght0ne**
Also:
- remove postPatch (config is not generated anymore; i.e. there's no `mouse.rs` or `xdg-open` mentions anywhere

###### Motivation for this change

https://github.com/jwilm/alacritty/releases/tag/v0.4.0

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @Mic92

---
This change is [Reviewable](https://reviewable.io/reviews/nixos/nixpkgs/74187)

### CODE REVIEW

**Comment by filalex77** [comment]
@GrahamcOfBorg build alacritty

**Comment by filalex77** [comment]
Would be great if somebody ran a build on Darwin (and merged, probably) ;)

**Comment by Mic92** [comment]
@GrahamcOfBorg build alacritty

**Comment by filalex77** [comment]
@Mic92 Probably doesn't work because the PR is merged. Oh well, we'll just have to wait and see :(

**Pull request merged**
