### PR TITLE
coc-pyright: init at 1.1.113

### PR DESCRIPTION
**Pull request by cpcloud**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
@cpcloud please resolve the merge conflict and give me a ping so that we can merge it before the next one is created.

**Comment by cpcloud** [comment]
Ok. It takes about 30 minutes to run `generate.sh`. Hopefully there aren't any conflicting things merged in the meantime.

**Comment by cpcloud** [comment]
Ping @SuperSandro2000

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 113922` at 19596401 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages marked as broken and skipped:</summary>
  <ul>
    <li>python39Packages.batchspawner</li>
    <li>python39Packages.dockerspawner</li>
    <li>python39Packages.jupyterhub</li>
    <li>python39Packages.jupyterhub-ldapauthenticator</li>
    <li>python39Packages.jupyterhub-systemdspawner</li>
    <li>python39Packages.jupyterhub-tmpauthenticator</li>
    <li>python39Packages.oauthenticator</li>
  </ul>
</details>
<details>
  <summary>20 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/385bcfe5e3c9a437f7082d8c1dbd87bb">parity-ui</a></li></li>
    <li><a href="https://gist.github.com/df202db6af1aedf6a0c4b8483e7a07b9">python37Packages.batchspawner</a></li></li>
    <li><a href="https://gist.github.com/9b89fd780f8c275996eaea20cc70f1be">python37Packages.dockerspawner</a></li></li>
    <li><a href="https://gist.github.com/320dfc2dbba88feecb6429e9fcc89719">python37Packages.jupyterhub</a></li></li>
    <li><a href="https://gist.github.com/65b61d8d13c19adcc268c788aa96b8ab">python37Packages.jupyterhub-ldapauthenticator</a></li></li>
    <li><a href="https://gist.github.com/c169f1705a37e4cfaf9d7dc7628f7ca5">python37Packages.jupyterhub-systemdspawner</a></li></li>
    <li><a href="https://gist.github.com/6b568bf29b631656c1eb20202c638ec3">python37Packages.jupyterhub-tmpauthenticator</a></li></li>
    <li><a href="https://gist.github.com/4e0aa0734582ea48e133c366c5142363">python37Packages.oauthenticator</a></li></li>
    <li><a href="https://gist.github.com/de81aa78ee54403459903bb54e6fdff9">python38Packages.batchspawner</a></li></li>
    <li><a href="https://gist.github.com/65d3941d3440c34bba2184d3ebd3a980">python38Packages.dockerspawner</a></li></li>
    <li><a href="https://gist.github.com/4e4ba19b4d3d044b5660a3690730a9c2">python38Packages.jupyterhub</a></li></li>
    <li><a href="https://gist.github.com/2a04d5aa59df05117a78ee4afb9233eb">python38Packages.jupyterhub-ldapauthenticator</a></li></li>
    <li><a href="https://gist.github.com/92ca9bd0802c821481b7a5e25f7a1f5b">python38Packages.jupyterhub-systemdspawner</a></li></li>
    <li><a href="https://gist.github.com/930802fbf36c1dd604ad3b635305c3a1">python38Packages.jupyterhub-tmpauthenticator</a></li></li>
    <li><a href="https://gist.github.com/c213816c18f646632dba27daff89ee4e">python38Packages.oauthenticator</a></li></li>
    <li><a href="https://gist.github.com/357368ec814637915c8679c7ab36980b">spacevim</a></li></li>
    <li><a href="https://gist.github.com/492404528d145f71a0e83e1dc9fedb24">styx</a></li></li>
    <li><a href="https://gist.github.com/dbe5084ad277b0defb85f89c448f8c73">teleprompter</a></li></li>
    <li><a href="https://gist.github.com/1c5837c7d6200c4c2bea143702bb35db">vscode-extensions.matklad.rust-analyzer</a></li></li>
    <li><a href="https://gist.github.com/aec984a50d3456827aa0d4f9978bf24e">vscode-extensions.vadimcn.vscode-lldb</a></li></li>
  </ul>
</details>

**Pull request merged**
