### PR TITLE
moreutils: 0.54 -> 0.55

### PR DESCRIPTION
**Pull request by k0ral**

### CODE REVIEW

**Comment by iElectric** [comment]
@joeyh are moreutils 0.55 tarballs somewhere distributed?

**Comment by joeyh** [comment]
Domen Kožar wrote:
> @joeyh are moreutils 0.55 tarballs somewhere distributed?

Not yet. Normally there would be an upload to Debian, but it's in
freeze.

Perhaps Nicolas could upload the new release to Debian experimental
though.

-- 
see shy jo

**Comment by joeyh** [comment]
Dear Joey,
dear Domen,

> [...] Normally there would be an upload to Debian, but it's in
> freeze.
> 
> Perhaps Nicolas could upload the new release to Debian experimental
> though.

Debian package moreutils_0.55-1 is scheduled [1] and will hopefully be 
uploaded to experimental within the next days.

Kind regards,
Nicolas


[1]: 
http://mentors.debian.net/debian/pool/main/m/moreutils/moreutils_0.55-1.dsc

**Comment by joeyh** [comment]
Dear Domen,

the moreutils-0.55 tar archive is no available at

http://ftp.debian.org/debian/pool/main/m/moreutils/moreutils_0.55.orig.tar.gz

Kind regards,
Nicolas

**Comment by iElectric** [comment]
Thanks!

**Comment by iElectric** [comment]
Let's use the source tarball then.

**Comment by k0ral** [comment]
Updated to use tarball.

**Pull request merged**
