### PR TITLE
doc/gnome: Port to Markdown

### LINKED ISSUE #104965: Convert Gnome from Docbook to CommonMark
This issue tracks the conversion of `/doc/languages-frameworks/gnome.xml` from Docbook to CommonMark per [RFC 72](https://github.com/NixOS/rfcs/blob/master/rfcs/0072-commonmark-docs.md).

If you intend to work on this conversion, please comment below!

# Instructions for performing this conversion

1. Post in this issue that you intend to work on it. (Please also post if you stop working on it)
2. Checkout a new branch of nixpkgs master.
3. Edit `doc/languages-frameworks/index.xml`: change `gnome.xml` to `gnome.section.xml`.
4. Convert the contents from Docbook to [CommonMark](https://commonmark.org/). Follow [conversion best practices](https://github.com/NixOS/nixpkgs/issues/105243). Use existing `.md` sections for inspiration.
5. Convert the contents from Docbook to [CommonMark](https://commonmark.org/). Use existing `.md` sections for inspiration.
6. Use `nix-build` from the `doc/` folder to build the manual.
7. Preview the manual on your computer at `http://0.0.0.0:8000/manual.html` after running from `doc/` folder:
  ```
  nix-shell -p python3 --run 'python3 -m http.server --directory ./result/share/doc/nixpkgs'
  ```
8. When it looks good, submit a PR and reference this issue.

### PR DESCRIPTION
**Pull request by jtojnar**
Closes: #104965

* Changed `variablelist` entries to separate sections
* Added anchors to list items inline using the [span syntax](https://pandoc.org/MANUAL.html#extension-bracketed_spans).
* ~~Admonitions do not seem to work using the [fenced div syntax](https://pandoc.org/MANUAL.html#extension-fenced_divs) (even though pandoc uses them in docbook→markdown conversion), will use docbook for now.~~ Fixed in pandoc.

### CODE REVIEW

**Comment by jtojnar** [comment]
Rebased onto staging-next. Can be tested without rebuilding the world now.

**Comment by ryantm** [comment]
I tried building the manual with this PR's changeset and it failed to apply all the patches:

```
builder for '/nix/store/h37h3kssv82np8h3r6a174awg0zb9s12-pandoc-2.11.2.drv' failed with exit code 1; last 10 log lines:
  applying patch /nix/store/mfxkx77s89zfyd9rhlggkqdmalzxjjc7-e516f89eead99054531d96832efa50e40cba48e5.patch
  patching file src/Text/Pandoc/Writers/Docbook.hs
  applying patch /nix/store/z71nh146w4yxzx5hdw8v5zaiqa6imwc1-340f7a6e538451f39bfa80116f3b907e018253e0.patch
  patching file src/Text/Pandoc/Writers/Docbook.hs
  applying patch /nix/store/hpjfc6jjm9v8hhhr6nhq0mprxkmqpidl-1ce1e61755bb6ebe57bebe8dadfa0448a2f31a63.patch
  patching file src/Text/Pandoc/Writers/Docbook.hs
  Hunk #1 succeeded at 44 with fuzz 2 (offset 4 lines).
  Hunk #2 succeeded at 95 (offset 4 lines).
  Hunk #3 FAILED at 177.
  1 out of 3 hunks FAILED -- saving rejects to file src/Text/Pandoc/Writers/Docbook.hs.rej
```

**Comment by jtojnar** [comment]
Yeah, the two pandoc patches change neighbouring regions and line-based patches cannot handle that. I have rebased the second one onto the first one now that https://github.com/jgm/pandoc/pull/6923 has been merged.

**Review by jtojnar — COMMENTED** [review]
The diff of the generated HTML looks acceptable to me now. It entails the following:

* Semantic literals have been replaced by non-specific backtick code element.
* Inline anchors are now placed next to the span they are attached to, instead of adding `id` attribute to the span itself. I might open a pandoc PR to correct this but it works fine as is.
* Anchors for paragraphs/list items are now inline anchors at their beginning, since Pandoc’s Markdown currently does not allow attaching `id`s to paragraphs or list items.
* When building EPUB, there is the following warning `Xref is only supported to listitems in an orderedlist: ssec-gnome-hooks-gdk-pixbuf`.
* The definition list has been replaced by headings as described above.

**Comment by jtojnar** [comment]
Actually, the EPUB seems to produce the following incorrect link `<a class="xref" href="sec-language-gnome.html#ssec-gnome-hooks-gdk-pixbuf">???</a>` but it has been like that even before the Markdown conversion.

**Comment by jtojnar** [comment]
Actually, it is not even limited to EPUB. Fixed that now as well.

**Review by ryantm — APPROVED** [review]
Code, rendering, and diff with master manual all look good.

Adding patches to the regular pandoc derivation is kind of a bit of a departure from our regular policies, but those patches are in master, and we should be able to clean that up in a bit, and it seems nice if people want to do stuff with the manual to not have to know some special argument to pass, so I'm going to merge it.

**Pull request merged**
