### PR TITLE
nixos/qemu-vm: fix diskless VMs

### PR DESCRIPTION
**Pull request by RaitoBezarius**
###### Description of changes

Previously, it was possible to run with a tmpfs / with `virtualisation.diskImage = null;`, this was likely broken by my changes in 4b4e4c3ef930c6106918d27a933de1b6965eff2c.

It is reintroduced by disabling properly the bootloader for now, as it is complicated to make it work with.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by alyssais — APPROVED** [review]
This fixes my NixOS test that uses `virtualisation.diskImage = null`, thanks!

**Review by alyssais — CHANGES_REQUESTED** [review]
Actually this appears to have broken other things.  A NixOS test node with no options set now says "error: No device specified for mount point ‘/’.".

**Comment by RaitoBezarius** [comment]
Running an evaluation here https://hydra.nixos.org/jobset/nixos/python-test-refactoring with merge-base.

**Comment by RaitoBezarius** [comment]
Evaluation shows no extra failures, beyond existing ones.

**Comment by vcunat** [comment]
This merge brought back some errors https://hydra.nixos.org/eval/1794619  (related to PR #229826)

I hope that some of you understand why, or at least better than me.

**Comment by vcunat** [comment]
@RaitoBezarius: so, reverting for now?  https://github.com/NixOS/nixpkgs/pull/230386

**Comment by RaitoBezarius** [comment]
I can take a look to them tomorrow, but I am okay with revert if you prefer to unblock the channel now.

**Comment by vcunat** [comment]
OK, merged for now.  I'm trying to keep the lag of the channels small continuously, say under 48h for `-small` ones.

**Comment by RaitoBezarius** [comment]
Result of `nixpkgs-review pr 228047` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>tests.testers.nixosTest-example</li>
    <li>tests.trivial-builders.references</li>
  </ul>
</details>

**Comment by RaitoBezarius** [comment]
For reference, the problem is here:
```
machine: must succeed: mount
machine # [    5.571187] dbus-daemon[899]: dbus[899]: Unknown username "systemd-timesync" in message bus configuration file
(finished: must succeed: mount, in 0.02 seconds)
devtmpfs on /dev type devtmpfs (rw,nosuid,size=75688k,nr_inodes=186849,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=3,mode=620,ptmxmode=666)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,size=756880k)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /run type tmpfs (rw,nosuid,nodev,size=378440k,mode=755)
ramfs on /run/keys type ramfs (rw,nosuid,nodev,relatime,mode=750)
tmpfs on /run/wrappers type tmpfs (rw,nodev,relatime,size=756880k,mode=755)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
/dev/vdb on / type ext4 (rw,relatime)
nix-store on /nix/.ro-store type 9p (rw,relatime,dirsync,loose,access=client,msize=16384,trans=virtio)
tmpfs on /nix/.rw-store type tmpfs (rw,relatime,mode=755)
shared on /tmp/shared type 9p (rw,relatime,sync,dirsync,access=client,msize=16384,trans=virtio)
xchg on /tmp/xchg type 9p (rw,relatime,sync,dirsync,access=client,msize=16384,trans=virtio)
overlay on /nix/store type overlay (rw,relatime,lowerdir=/mnt-root/nix/.ro-store,upperdir=/mnt-root/nix/.rw-store/store,workdir=/mnt-root/nix/.rw-store/work)
overlay on /nix/store type overlay (ro,relatime,lowerdir=/mnt-root/nix/.ro-store,upperdir=/mnt-root/nix/.rw-store/store,workdir=/mnt-root/nix/.rw-store/work)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
ramfs on /run/credentials/systemd-tmpfiles-setup-dev.service type ramfs (ro,nosuid,nodev,noexec,relatime,mode=700)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
ramfs on /run/credentials/systemd-sysctl.service type ramfs (ro,nosuid,nodev,noexec,relatime,mode=700)
ramfs on /run/credentials/systemd-tmpfiles-setup.service type ramfs (ro,nosuid,nodev,noexec,relatime,mode=700)
```

**Comment by RaitoBezarius** [comment]
(double nix store mounts)

**Pull request merged**
