### PR TITLE
first batch of compatible applications

### PR DESCRIPTION
**Pull request by freezeboy**
###### Motivation for this change

Add more expressions to darwin platform. Basically, simply changing locally the `meta.platforms` field and trying to recompile. When build succeeds, replace the value by `platforms.unix`.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by freezeboy** [comment]
Related to #55770

**Comment by FRidh** [comment]
The commit title should say what the commit implements.

**Comment by freezeboy** [comment]
Is it better this way ?

Don't know how to fix the **grahamcofborg-eval-nixpkgs-unstable-jobset** problem

**Comment by matthewbauer** [comment]
@grahamcofborg eval

**Comment by vcunat** [comment]
That problem was due to a breakage on master that had been fixed in the meantime.

**Comment by freezeboy** [comment]
I suppose I should still do something, but no idea what

**Comment by vcunat** [comment]
Why?  It shows green now, doesn't it?

**Comment by freezeboy** [comment]
well nobody/norobot merges it

**Comment by vcunat** [comment]
I'm not a darwin person, but it seems unlikely more people will react to this.

**Comment by vcunat** [comment]
You can review [the result](https://hydra.nixos.org/eval/1506165#tabs-new).
- There might be new packages from others mixed in.
- Some errors are due to transient problems, e.g. stuff depending on the failed go build.

**Comment by freezeboy** [comment]
Not bad at all, thank you for the link, do you know how to trigger a new attempt ? I tried some of the failed ones and I confirm that it was a temp problem.

**Comment by vcunat** [comment]
There have some large dependency updates, so they should all get rebuilt (within a few days).  You can see those on links like https://hydra.nixos.org/job/nixpkgs/trunk/fsql.x86_64-darwin

**Pull request merged**
