### PR TITLE
jikes: removing

### PR DESCRIPTION
**Pull request by cko**
#### Motivation for this change 
Jikes was an alternative Java compiler. The last release was in 2005 and it hasn't been touched in years. The last Java version it (partially) supports is Java 5. There are no packages depending on it.
Homepage: https://sourceforge.net/projects/jikes/ 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by worldofpeace** [comment]
@cke You need to remove the callPackage in `all-packages.nix` and add an alias to `aliases.nix`.

**Comment by worldofpeace** [comment]
And by an alias I mean something like https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/aliases.nix#L309. And we'll remove it in the next nixos release.

**Comment by cko** [comment]
Thanks @worldofpeace ! I've updated the PR.

**Review by worldofpeace — APPROVED** [review]
LGTM, will backport to the beta release. Can you squash your commits into one?

**Review by jonringer — APPROVED** [review]
`nix-review` looks right

```
$ nix-env -f /home/jon/.cache/nix-review/pr-70666/nixpkgs -qaP --xml --out-path --show-trace --meta
Nothing changed
https://github.com/NixOS/nixpkgs/pull/70666
No packages were successfully build, skip nix-shell
$ git worktree prune
```

EDIT: please squash commits into one :)

**Comment by cko** [comment]
I squashed the commits into one

**Comment by jonringer** [comment]
commits should be written in the "imperative mood" https://git.kernel.org/pub/scm/git/git.git/tree/Documentation/SubmittingPatches?id=HEAD#n133 but it's close enough so I'll merge :)

```
jikes: Remove
```

**Comment by worldofpeace** [comment]
backported in 30ceb5114708861f2d431fb52c31f50e90df5a97.
also did eb8f8180d8f60bb91d7eb0f16afa8f43c2a87332 because in certain instances, when the message doesn't include the packagename, people have no idea why they're seeing this message.

**Pull request merged**
