### PR TITLE
haskellPackages.texmath: fix ghc710x build inputs

### PR DESCRIPTION
**Pull request by LnL7**
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [x] OS X
  - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peti** [comment]
This patch is hard to review because it contains numerous seemingly unrelated changes.

**Comment by LnL7** [comment]
Line 216 is the only change, I sorted the lines and moved a few other `<ghc8` comment. I can make this a single line diff if you want.

**Comment by peti** [comment]
If you could split the two changes into two commits, that would help a lot!

**Comment by LnL7** [comment]
@peti Any idea why we need so many overrides for `ghc7.x`, I've noticed that a number of these are build flags that are not conditional (like this case) https://github.com/jgm/texmath/blob/master/texmath.cabal#L81

**Comment by peti** [comment]
The `executable` flag defaults to `false`, which means that the `texmath` executable won't be built. Therefore, the build does not actually depend on `network-uri`. Cabal 1.24.x knows this and the build works fine without that library, but GHC 7.10.x uses an older version of Cabal  -- which does not handle this case correctly -- and therefore the build fails unless the library is present (even though it's not going to be used). It's a very unfortunate situation.

**Pull request merged**
