### PR TITLE
proot: allow static compilation

### PR DESCRIPTION
**Pull request by bosu**
Thus nix compiled proot becomes useful on other Linuxes.

### CODE REVIEW

**Comment by 7c6f434c** [comment]
Do we want to make talloc static build unconditional? It is a dependency of many things via samba

**Comment by bosu** [comment]
Regarding talloc, the change is exporting already built object. talloc build itself is unchanged.

**Comment by 7c6f434c** [comment]
>Regarding talloc, the change is exporting already built object. talloc build itself is unchanged.

I think it changes an output path of talloc by default.

**Comment by copumpkin** [comment]
Looks like this got lost somewhere #17854

**Pull request merged**
