### PR TITLE
vim-plugins: turn filetype and syntax before sourcing the plugins

### PR DESCRIPTION
**Pull request by kalbasit**
###### Motivation for this change

Currently, all the plugins are loaded *after* all the plugins have already been loaded. This could break some plugins, for instance, vim-terraform assumes the filetype detection has already been enabled.

This commit follows [VAM's recommendation](https://github.com/MarcWeber/vim-addon-manager/tree/d9e865f3c2de5d9b7eabbc976f606cf1b89e29ea#recommended-setup) and enables filetype and syntax before sourcing any of the plugins.

This was discovered after a follow up with vim-terraform's maintainer on an upstream pull request: https://github.com/hashivim/vim-terraform/pull/133

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @timokau @gloaming

### CODE REVIEW

**Comment by kalbasit** [comment]
Please backport this to 19.09.

**Comment by dimbleby** [comment]
It's possible that you're going to get into a tangle here: some plugin managers have the opposite requirement.  Eg pathogen asks you to turn `filetype on` after doing its thing and vundle explicitly asks you to set `filetype off` first...

Good luck!

**Comment by kalbasit** [comment]
> It's possible that you're going to get into a tangle here: some plugin managers have the opposite requirement. Eg pathogen asks you to turn `filetype on` after doing its thing and vundle explicitly asks you to set `filetype off` first...
> 
> Good luck!

Ah, thank you for pointing that out @dimbleby. I removed vundle and neobundle since they're not actually implemented and will probably include the settings directly with the plugin implementation for this to work correctly.

**Comment by kalbasit** [comment]
I tested the following implementation with the `vim-terraform` plugin since it's the only one that falls on me if filetype was not enabled properly at the right time.

```
# Pathogen
nix-build -I nixpkgs=. -E 'with import <nixpkgs> {}; neovim.override { configure = { pathogen.pluginNames = [ "vim-terraform" ]; }; }' --show-trace

# VAM
nix-build -I nixpkgs=. -E 'with import <nixpkgs> {}; neovim.override { configure = { vam.pluginDictionaries = [ "vim-terraform" ]; }; }' --show-trace 
```

All the above-compiled vim were then tested by opening a Terraform file, I see no errors and the filetype is set correctly to `terraform` instead of `tf`.

I was not able to verify that vim-terraform is able to load correctly with the native plugins (I'm not sure how that even works), so I left that implementation unchanged by adding the `filetype indent plugin on | syn on` at the end of the implementation. I tried with the following command

```
nix-build -I nixpkgs=. -E 'with import <nixpkgs> {}; neovim.override { configure = { packages.myVimPackage = { start = [ "vim-terraform" ]; }; }; }' --show-trace
```

**Comment by timokau** [comment]
Didn't you open a similar PR already? This all seems very familiar to me.

Unfortunately I'm pretty short on time currently, so I can't test this extensively. I'm not entirely sure if turning both of these on is the right thing to do, but I'll let you and the other people interested in vim decide here.

**Comment by kalbasit** [comment]
Yes, indeed.

In #66536, we fixed the manifest generation but the runtime was still broken. This PR reverts #66536 and just fixes the root cause of us not respecting the recommend usage of the plugins we support, Pathogen, Vam and Plug.

**Review by jonringer — APPROVED** [review]
```
[2 built, 1 copied (32.4 MiB), 6.8 MiB DL]
https://github.com/NixOS/nixpkgs/pull/77143
1 package built:
vimPlugins.vim-terraform
```

**Comment by jonringer** [comment]
@GrahamcOfBorg build vimPlugins.vim-terraform

**Review by Ma27 — APPROVED** [review]

**Pull request merged**
