### PR TITLE
systray-x: init at 0.9.2

### LINKED ISSUE #212815: Add SysTray-X
**Project description**
SysTray-X: A system tray extension for Thunderbird 68+. Needs both the addon AND the companion app installed to work. Will not work with full wayland desktops. 

**Metadata**

* homepage URL: https://github.com/Ximi1970/systray-x
* source URL: https://github.com/Ximi1970/systray-x
* license: mpl2.0
* platforms: linux

### PR DESCRIPTION
**Pull request by Zahrun**
###### Description of changes

Closes https://github.com/NixOS/nixpkgs/issues/212815

The only catch and last mile I didn't figure out is that thunderbird seems to ignore the files in `/run/current-system/sw/lib/mozilla`. So after installation, I manually did the following commands and could confirm it works properly:
```
cp /run/current-system/sw/lib/mozilla/native-messaging-hosts/SysTray_X.json ~/.mozilla/native-messaging-hosts
cp /run/current-system/sw/lib/mozilla/thunderbird-addons/extensions/systray-x@Ximi1970.xpi ~/.thunderbird/${myprofile}/extensions/
```
Any ideas @edolstra @lovesegfault @nbp @vcunat ?

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ocfox** [comment]
Are you sure this works?

**Comment by Zahrun** [comment]
> Are you sure this works?

As I mention in the PR,

> The only catch and last mile I didn't figure out is that thunderbird seems to ignore the files in /run/current-system/sw/lib/mozilla. So after installation, I manually did the following commands and could confirm it works properly:
> ```
> cp /run/current-system/sw/lib/mozilla/native-messaging-hosts/SysTray_X.json ~/.mozilla/native-messaging-hosts
> cp /run/current-system/sw/lib/mozilla/thunderbird-addons/extensions/systray-x@Ximi1970.xpi ~/.thunderbird/${myprofile}/extensions/
> ```

**Comment by ocfox** [comment]
But why a separate package Thunderbird extension is? No similar practice in nixpkgs.

**Comment by Zahrun** [comment]
> But why a separate package Thunderbird extension is? No similar practice in nixpkgs.

The addon uses the WebExtension API's to control an external system dependent system tray application.
      Needs both the addon AND the companion app installed to work.

**Comment by ocfox** [comment]
I think it should remove the extensions and just package the binary.

**Comment by Zahrun** [comment]
> I think it should remove the extensions and just package the binary.

I am fine with removing the extension, which is systray-x@Ximi1970.xpi.
However, we still need the /run/current-system/sw/lib/mozilla/native-messaging-hosts/SysTray_X.json file to tell thunderbird to load the binary. When I look in that folder, I also have a file called `org.kde.plasma.browser_integration.json`, I think it works with Firefox. So we have a package doing this type of installation already, but not for thunderbird so far.

**Comment by Zahrun** [comment]
It seems support was added to firefox in https://github.com/NixOS/nixpkgs/pull/31572 and latest modified in https://github.com/NixOS/nixpkgs/commit/ec8a9cddc814ea3ee60ae3984ccd17d70bf26d0a

I can try to replicate this for thunderbird, a very similar patch should work. Can I do this in this PR or should it be a seperate PR?

**Comment by KodyVB** [comment]
Hello, I'm curious about the status of this. Are we waiting for something with regards to this, does it conflict too much with the norms of Nix packages, or was it just forgotten over the months? As someone who's trying to switch from a distro with systray-x, I've grown very used to having it, lol. No pressure on anyone, though - I know how busy life can get

**Comment by Zahrun** [comment]
I personnaly shifted to wayland and betterbird, which now includes a systray option. I am fine with closing this PR.

**Comment by KodyVB** [comment]
I didn't know about Betterbird before, but between that and the "Minimize on close" add-on, I think I'm pretty much covered and won't need to use Systray with Thunderbird. Thank you @Zahrun !

**Pull request closed without merging**
