### PR TITLE
super-slicer-latest: 2.3.57.12 -> 2.4.58.3

### PR DESCRIPTION
**Pull request by Wulfsta**
###### Description of changes

Update [latest version](https://github.com/supermerill/SuperSlicer/releases/tag/2.4.58.3) of super-slicer.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by newAM — APPROVED** [review]
Builds on `x86_64-linux`, was able to slice a simple STL.

**Review by winterqt — CHANGES_REQUESTED** [review]
Please update the commit message to conform with the [guidelines](https://nixos.org/manual/nixpkgs/stable/#submitting-changes-making-patches): `super-slicer-latest: 2.3.57.12 -> 2.4.58.3`.

**Comment by Wulfsta** [comment]
> Please update the commit message to conform with the [guidelines](https://nixos.org/manual/nixpkgs/stable/#submitting-changes-making-patches): `super-slicer-latest: 2.3.57.12 -> 2.4.58.3`.

Sorry, been a while since I contributed to this repo.

**Review by winterqt — APPROVED** [review]

**Comment by cab404** [comment]
hey, could at least wait for a maintainer @winterqt >.>

**Comment by winterqt** [comment]
@cab404 You're right, sorry >.<

Doesn't excuse the fact that I merged prematurely, but I didn't see any issues with the changes here, and the package built. If you do see any issues please let me know and I can revert immediately. Again, my sincerest of apologies.

**Comment by cab404** [comment]
yeah, LGTM after some use

**Pull request merged**
