### PR TITLE
git: 2.17.0 -> 2.17.1

### PR DESCRIPTION
**Pull request by tilpner**
Trivial bump for minor version update, nothing else should need changing

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
Let's hope it goes smoother than the "2.16.2 -> 2.17.0" bump :-)
https://github.com/NixOS/nixpkgs/pull/38636#issuecomment-380712557

**Comment by xeji** [comment]
Mainly security fixes, changelog: https://github.com/git/git/blob/master/Documentation/RelNotes/2.17.1.txt

**Comment by xeji** [comment]
@GrahamcOfBorg  build git

**Comment by xeji** [comment]
Failed tests on Darwin don't look nice.

**Comment by orivej** [comment]
@NeQuissimus has commited this in 9db1f486e15107e417b63119ad5e1917ee126599

**Comment by NeQuissimus** [comment]
Oh, my bad, I did not see this PR!

**Pull request closed without merging**
