### PR TITLE
Ruby updates

### PR DESCRIPTION
**Pull request by zimbatm**
All three releases have been public since 18 Aug 2015

### CODE REVIEW

**Comment by garbas** [comment]
@zimbatm there is a typo ... ';' is missing

**Comment by zimbatm** [comment]
woops sorry, fixed now

**Comment by garbas** [comment]
@zimbatm still fails to evaluate (https://travis-ci.org/NixOS/nixpkgs/builds/95170411) i think problem in case patchlevel is 0 it should not include any patches from patchsets.nix

**Comment by zimbatm** [comment]
Thanks I've been working on a fix, hopefully it will pass this time. This patchset is nice but it makes it harder to do ruby upgrades.

**Comment by zimbatm** [comment]
The build time has exceeded some sort of limit on the CI

**Pull request closed without merging**
