### PR TITLE
qutebrowser: make youtube work again

### PR DESCRIPTION
**Pull request by gebner**
Since upgrading PyQt to 5.5 #12213, visiting a youtube video in qutebrowser made it segfault.  This happened because qutebrowser was still using Qt plugins from version 5.4.  In addition the new Qt version also requires newer gstreamer plugins.

After upgrading the plugins, qutebrowser doesn't segfault anymore on youtube, and can play videos on _other_ sites.  However, youtube itself still doesn't work, it says "secure connection setup failed" and "unacceptable TLS certificate".

How to reproduce:
`GST_DEBUG=5 GST_DEBUG_NO_COLOR=1 GNUTLS_DEBUG_LEVEL=5 ./result/bin/qutebrowser --temp-basedir https://www.youtube.com/watch\?v=GOXjtR4N524`

Relevant log output:
`gnutls[5]: REC[0x7f19e80137e0]: Sent Packet[2] Alert(21) in epoch 1 and length: 31`
`0:00:00.491417269 23875      0x37fb450 INFO             souphttpsrc gstsouphttpsrc.c:1322:gst_soup_http_src_finished_cb:<source> finished, io status: 1`
`0:00:00.491455005 23875      0x37fb450 WARN             souphttpsrc gstsouphttpsrc.c:1556:gst_soup_http_src_parse_status:<source> error: Secure connection setup failed.`
`0:00:00.491459709 23875      0x37fb450 WARN             souphttpsrc gstsouphttpsrc.c:1556:gst_soup_http_src_parse_status:<source> error: Unacceptable TLS certificate (6), URL: https://r8---sn-bvvbax-8pxs.googlevideo.com/videoplayback?fexp=9413142%2C9416126%2C9417740%2C9419451%2C9420096%2C9420452%2C9422541%2C9422596%2C9423662%2C9424114%2C9424777%2C9425078%2C9425382%2C9426480%2C9426874%2C9426906&ratebypass=yes&mm=31&ipbits=0&mn=sn-bvvbax-8pxs&itag=18&dur=2807.756&initcwndbps=1065000&id=o-AKgrurCqeWvsG0GMU9VIz5I4LfGoLwwxK2U8fB2YuEiN&pl=16&source=youtube&mv=m&mime=video%2Fmp4&ms=au&signature=894F669541AA4A8C1815943139D63FC8452409D0.CF6FA534C0E7A58F7FFDD61116706119FB725DD4&lmt=1415400005735118&ip=84.112.114.160&upn=Q_rV2f3ycPg&mt=1452420191&expire=1452441939&requiressl=yes&sver=3&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&key=yt6&cpn=oEF_qqB7ZGxWTRDl&ptk=All3Media&oid=RdtVKdmbznqbJP7pYackwQ&pltype=contentugc&c=WEB&cver=html5, Redirect to: (NULL)`

Videos over https do work on other sites, it's just youtube where it fails with this TLS error.  I can fetch the url from the log file just fine using wget, curl, and gnutls-cli, so it doesn't seem to be a missing certificate.

AFAICT, gstreamer uses libsoup internally to handle https.  Are there any required build inputs, environment variables, etc. that I am missing?

Any ideas?

cc @lethalman @ttuegel @jagajaga

### CODE REVIEW

**Comment by gebner** [comment]
Upgrading qutebrowser to the current version doesn't help either... (Please tell me if I should file a separate PR for the version bump.)

**Comment by gebner** [comment]
Ok, this happens because of the nss upgrade from 3.20.1 to 3.21 in 86bf3662df02407a940f0a2c1373faf29a424882.  If I switch back to the old `/etc/ssl/certs/ca-certificates.crt` everything works.

**Comment by gebner** [comment]
And it isn't limited to qutebrowser either; the same bug also happens with `gst-launch-1.0`:
`gst-launch-1.0 -v playbin uri='https://r8---sn-bvvbax-8pxs.googlevideo.com/videoplayback?mime=video%2Fmp4&expire=1452445526&source=youtube&itag=18&pl=16&dur=2807.756&initcwndbps=2135000&ipbits=0&fexp=9407187%2C9407535%2C9416126%2C9420452%2C9421665%2C9421982%2C9422596%2C9423662%2C9423715%2C9424091%2C9426340%2C9426406%2C9426759&ratebypass=yes&sver=3&signature=6169771E96DCA7C4C39C7F9D6A37EDCD36049DC3.6CA280F37292BBC633DAFBED77ED02F3891F60AC&upn=qpWgN7CetIo&id=o-AH46yQAJdCwDXCfcX6jprDYvN2PNJvCwsj_1E_PA7gxP&mn=sn-bvvbax-8pxs&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&ms=au&mv=m&mt=1452423877&mm=31&ip=84.112.114.160&key=yt6&requiressl=yes&lmt=1415400005735118&cpn=kEVeeh7MR5Wbrnph&ptk=All3Media&oid=RdtVKdmbznqbJP7pYackwQ&pltype=contentugc&c=WEB&cver=html5'`

Plays the video with the old certificates file, but not with the new one.

However, I can't see a difference with gnutls-cli or `openssl s_client`...

**Comment by gebner** [comment]
Ok, it works after upgrading glib-networking and libsoup to the current versions!

**Comment by jagajaga** [comment]
These updates cause mass-rebuild. Can you create a new PR with them to a `staging` branch (with qutebrowser also)?

**Comment by gebner** [comment]
Done, I have opened #12414 against staging.

**Pull request closed without merging**
