### PR TITLE
inter-ui: remove inter-ui

### PR DESCRIPTION
**Pull request by supermarin**
###### Motivation for this change

This font seems to be a duplicate and outdated version of:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/data/fonts/inter/default.nix

Revamp of whatever disaster happened here: https://github.com/NixOS/nixpkgs/pull/117827

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Please also remove the entry in top-level.nix.

**Comment by supermarin** [comment]
@SuperSandro2000 thanks, just pushed seconds ago

**Comment by SuperSandro2000** [comment]
And I missed something else, sorry about that: it also requires an entry in aliases.nix.

**Comment by supermarin** [comment]
@SuperSandro2000 good point!

**Comment by supermarin** [comment]
@SuperSandro2000 let me know if you need anything else

**Pull request merged**
