### PR TITLE
endless-sky: 0.9.8 -> 0.9.10

### PR DESCRIPTION
**Pull request by willghatch**
###### Motivation for this change
New upstream release

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [?] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`

I ran that command inside my working git repo with the updated package definition.  It said it “No diff detected”.  I'm really not sure how that review tool is supposed to be run.  Is that what I'm supposed to do, or is it something completely different?  At any rate, I don't think any other package depends on endless-sky, but I'm not really sure how to verify that.

- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @lheckemann

### CODE REVIEW

**Comment by lheckemann** [comment]
@GrahamcOfBorg build endless-sky

**Comment by lheckemann** [comment]
Thanks, completely missed this release since there was no blog post about it!

**Comment by willghatch** [comment]
@lheckemann, thanks for merging!  But since I'll likely send more PRs to nixpkgs, would you mind clarifying for me the `nix-review` bullet point?  Are you supposed to just run that command inside your working git clone of nixpkgs, or are you supposed to do something else?  Or is there somewhere other than the PR template that explains it?

**Comment by lheckemann** [comment]
First off: none of the bullet points are hard requirements, except being fine with the licencing as outlined in CONTRIBUTING.md.

As for nix-review, I'm not entirely sure. I think it's for testing _unstaged_ changes in your git checkout, which is of course quite an individual workflow preference. In addition, since endless-sky is a leaf package (nothing depends on it), there's not much point in using it beyond checking if ES itself builds.

**Pull request merged**
