### PR TITLE
gotop: 3.0.0 -> 3.4.5

### LINKED ISSUE #81560: Update upstream gotop package
**Project description**
gotop is already a Nix package.  The upstream maintainer is no longer maintaining the package, and a new repository and maintainer (myself) is developing and maintaining the software.  I'm requesting that the Nix package point at the new upstream repository, and version bump to the latest release (3.3.2).

The original repository README includes an out-of-maintenance notice as well as a link to the new repository.

**Metadata**

* homepage URL: https://github.com/xxxserxxx/gotop
* source URL: https://github.com/xxxserxxx/gotop
* license: Same as before, AGPL 3.0
* platforms: Windows, Darwin, FreeBSD 386 & amd64; Linux 386, amd64, ARM 5-7, ARM64

I gave updating the package myself a shot but eventually got stuck with deps.nix; while generated and referenced, `nix-build` is ignoring it so I'm doing something wrong. It's probably better if the package maintainer manage this.

### PR DESCRIPTION
**Pull request by marsam**
###### Motivation for this change

Update src with maintained fork

Closes https://github.com/NixOS/nixpkgs/issues/81560
cc @xxxserxxx

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by magnetophon** [comment]
``nix-review pr 81622`` gives me:
```
builder for '/nix/store/xjvyyhmck6yqd2yykg8y3y9z0vbdwh29-gotop-3.4.5-go-modules.drv' failed with exit code 1; last 10 log lines:
  agent> executing /nix/bin/nix-store
  unpacking sources
  unpacking source archive /nix/store/mb9hyabwizqmr2dflw2by5nbwpr18q2r-source
  source root is source
  patching sources
  configuring
  building
  go: github.com/StackExchange/wmi@v0.0.0-20180116203802-5d049714c4a6: Get "https://proxy.golang.org/github.com/%21stack%21exchange/wmi/@v/v0.0.0-20180116203802-5d049714c4a6.mod": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:48100->[::1]:53: read: connection refused
  builder for '/nix/store/xjvyyhmck6yqd2yykg8y3y9z0vbdwh29-gotop-3.4.5-go-modules.drv' failed with exit code 1
  12868: failed: NixTransientFailure builder for '/nix/store/xjvyyhmck6yqd2yykg8y3y9z0vbdwh29-gotop-3.4.5-go-modules.drv' failed with exit code 1
cannot build derivation '/nix/store/xs8j5w1hpy5qhr4jqyyqi3x7vrpqazvk-gotop-3.4.5.drv': 1 dependencies couldn't be built
```

**Comment by kalbasit** [comment]
@GrahamcOfBorg build gotop

**Review by Valodim — APPROVED** [review]
works as expected.

@magnetophon the build error seems to be a connectivity issue

**Review by Br1ght0ne — APPROVED** [review]
diff LGTM
executable works
```
[4 built, 0.0 MiB DL]
https://github.com/NixOS/nixpkgs/pull/81622
1 package built:
gotop
```

**Comment by xxxserxxx** [comment]
Thank you.

**Pull request merged**
