### PR TITLE
[23.05] matrix-hookshot: 4.4.1 -> 4.5.1

### PR DESCRIPTION
**Pull request by chvp**
## Description of changes

https://github.com/matrix-org/matrix-hookshot/releases/tag/4.5.0 https://github.com/matrix-org/matrix-hookshot/releases/tag/4.5.1

https://github.com/matrix-org/matrix-hookshot/security/advisories/GHSA-fr97-pv6w-4cj6

(cherry picked from commit 3ba4996d21857d883046553549f13bdc34022ee7)

Backport of #257423

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabianhjr** [comment]
Manual backport due to automatic backport failure: https://github.com/NixOS/nixpkgs/pull/257423#issuecomment-1737094641

**Review by fabianhjr — APPROVED** [review]

**Review by fabianhjr — CHANGES_REQUESTED** [review]
Could you change the cherry-picked commit to the one that was merged into the main branch?

It helps with tracking: bbf12a916929e8b361a159f44a1e31d59b6c2d2a

**Comment by chvp** [comment]
Sure, I can do that later today, but the message that the github-actions bot places in case of backport failure should be changed to reflect that, if that is the standard procedure. (Because I did nothing more then run the commands it gave me, fixing the conflict and then continuing the cherry-pick.

**Comment by chvp** [comment]
Done.

**Review by fabianhjr — APPROVED** [review]

**Pull request merged**
