### PR TITLE
staging-next 2023-01-05

### PR DESCRIPTION
**Pull request by vcunat**
- workflow docs: https://nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy
- important jobs:
  https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
  https://hydra.nixos.org/job/nixos/staging-next-small/tested
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next
  https://hydra.nixos.org/jobset/nixos/staging-next-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/205270

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
the ``programs.iay.package`` option needs to be converted to docbook to fix the manual build

**Comment by ncfavier** [comment]
I don't know why it's still failing. Looks like it's not taking the last two commits into account? At least `options.json` builds fine locally.

**Comment by wegank** [comment]
@ncfavier You merged #209188 into staging-next ;-)

**Comment by winterqt** [comment]
I just triggered a rerun.

**Comment by winterqt** [comment]
> @ncfavier You merged #209188 into staging-next ;-)

Which is this branch, so the build should succeed? Don't see what you mean, unless you're just mistaken :D

**Comment by wegank** [comment]
@winterqt Indeed, I just made a mistake. I meant that #209188 should be merged into master to fix ofborg errors as soon as possible, but this PR should be fine if the commit is included.

**Comment by ncfavier** [comment]
Looks like the workflow isn't even checking out the right commit? https://github.com/NixOS/nixpkgs/actions/runs/3849505975/jobs/6558632218#step:2:549

I wonder what e3117f1c587cbc4550752363ef1bdf4fac046729 is.

@wegank, oh it's also broken on master? I'll make another PR then.

**Comment by wegank** [comment]
Yes, since #207797 was merged into master three hours ago.

**Comment by vcunat** [comment]
> I wonder what https://github.com/NixOS/nixpkgs/commit/e3117f1c587cbc4550752363ef1bdf4fac046729 is. Maybe GitHub just needs some time to update refs/pull/<this PR>/merge because of the large number of commits?

That's just a temporary commit created by GitHub workflow to merge PR with the target branch.

**Comment by vcunat** [comment]
darwin is in big trouble, even after a few retries:
- [ ] some `dejagnu` on aarch64-darwin: https://hydra.nixos.org/build/204316848
- [ ] `stdenv` on x86_64-darwin &ndash; doesn't show well on Hydra, locally I get
  ```
  error: output '/nix/store/rvxxk1i3fqwvsxqyik5bk1s0zrphhh5d-stdenv-darwin' is not allowed to refer to the following paths:
         /nix/store/gd8ya01x7zk5lkwg261c1xqs1cfgf0q4-libiconv-50
         /nix/store/q1rxhs1frlznc1x1y0lqmgh5rlp2w3vs-gettext-0.21
         /nix/store/rsl77yd5mm22gvlrdqhqdva8n4axb1p8-bootstrap-tools
  ```

**Comment by NickCao** [comment]
x86_64-darwin `stdenv` is addressed in https://github.com/NixOS/nixpkgs/pull/209271

**Comment by wegank** [comment]
@vcunat The `dejagnu` failure is even reproducible on master on my machine (aarch64-darwin, macOS 13.1). Not sure if temporarily disabling the tests is a good idea.

**Comment by vcunat** [comment]
Maybe `dejagnu` maintainer could have a look?  @vrthra

**Comment by mweinelt** [comment]
> Maybe `dejagnu` maintainer could have a look? @vrthra

Last contribution to nixpkgs >5y ago.

**Comment by winterqt** [comment]
> @vcunat The `dejagnu` failure is even reproducible on master on my machine (aarch64-darwin, macOS 13.1). Not sure if temporarily disabling the tests is a good idea.

It seems that the sandbox actually fixes the issue. At least for me, building with the sandbox disabled causes it to fail, while building with the sandbox enabled makes it work fine.

**Comment by winterqt** [comment]
```
Running ../testsuite/runtest.main/nested/testsuite/bug.test/pr42399-sub.exp ...
parent: sync byte write: broken pipe
```

This seems to be the issue for both unresolved tests.

**Comment by vcunat** [comment]
> It seems that the sandbox actually fixes the issue.

I don't think we can rely on the sandbox on `*-darwin` anytime soon.  (Though I don't know much about this stuff.)

**Comment by winterqt** [comment]
> I don't think we can rely on the sandbox on `*-darwin` anytime soon. (Though I don't know much about this stuff.)

Correct, sadly.

**Comment by Mindavi** [comment]
A cross regression slipped in for the cargo build, as far as I can tell.

<details><summary>build log of derivation /nix/store/w9p9g4gkqk7qqfhsai6l9qrcyq619y88-cargo-aarch64-unknown-linux-gnu-1.66.1.drv</summary>

```
 Below is the build log of derivation /nix/store/w9p9g4gkqk7qqfhsai6l9qrcyq619y88-cargo-aarch64-unknown-linux-gnu-1.66.1.drv. It was built on localhost.

unpacking sources
unpacking source archive /nix/store/s3b50xp1cp9cszk5xqcn42ky7ij4fg4d-rustc-1.66.1-src.tar.gz
source root is rustc-1.66.1-src
Executing cargoSetupPostUnpackHook
Finished cargoSetupPostUnpackHook
setting SOURCE_DATE_EPOCH to timestamp 1673388722 of file rustc-1.66.1-src/vendor/yansi/src/windows.rs
patching sources
updateAutotoolsGnuConfigScriptsPhase
configuring
building
Executing cargoBuildHook
/build/rustc-1.66.1-src/src/tools/cargo /build/rustc-1.66.1-src
++ env CC_x86_64-unknown-linux-gnu=/nix/store/iiq295j1z4q1sxmdbrl2j8ma3l5ns4wr-gcc-wrapper-11.3.0/bin/cc CXX_x86_64-unknown-linux-gnu=/nix/store/iiq295j1z4q1sxmdbrl2j8ma3l5ns4wr-gcc-wrapper-11.3.0/bin/c++ CC_aarch64-unknown-linux-gnu=/nix/store/g54w8f1glcxym9g3pplj7dcj4nkkz1lh-aarch64-unknown-linux-gnu-stage-final-gcc-wrapper-9.5.0/bin/aarch64-unknown-linux-gnu-cc CXX_aarch64-unknown-linux-gnu=/nix/store/g54w8f1glcxym9g3pplj7dcj4nkkz1lh-aarch64-unknown-linux-gnu-stage-final-gcc-wrapper-9.5.0/bin/aarch64-unknown-linux-gnu-c++ cargo build -j 8 --target aarch64-unknown-linux-gnu --frozen --release
   Compiling libc v0.2.135
   Compiling pkg-config v0.3.25
   Compiling autocfg v1.1.0
   Compiling proc-macro2 v1.0.46
   Compiling unicode-ident v1.0.5
   Compiling syn v1.0.102
   Compiling version_check v0.9.3
   Compiling cfg-if v1.0.0
   Compiling serde_derive v1.0.147
   Compiling serde v1.0.147
   Compiling memchr v2.5.0
   Compiling typenum v1.16.0
   Compiling log v0.4.14
   Compiling cfg-if v0.1.10
   Compiling getrandom v0.2.0
   Compiling bitflags v1.3.2
   Compiling tinyvec_macros v0.1.0
   Compiling crc32fast v1.3.2
   Compiling matches v0.1.8
   Compiling tinyvec v1.6.0
   Compiling quote v1.0.18
   Compiling generic-array v0.14.4
   Compiling jobserver v0.1.24
   Compiling cc v1.0.73
   Compiling once_cell v1.12.0
   Compiling rand_core v0.6.2
   Compiling unicode-bidi v0.3.4
   Compiling proc-macro-error-attr v1.0.4
   Compiling unicode-normalization v0.1.22
   Compiling percent-encoding v2.1.0
   Compiling ryu v1.0.5
   Compiling lazy_static v1.4.0
   Compiling form_urlencoded v1.0.1
   Compiling aho-corasick v0.7.18
   Compiling indexmap v1.9.1
   Compiling proc-macro-error v1.0.4
   Compiling idna v0.2.0
   Compiling anyhow v1.0.65
   Compiling os_str_bytes v6.0.0
   Compiling regex-syntax v0.6.26
   Compiling libz-sys v1.1.3
   Compiling openssl-sys v0.9.72
   Compiling libnghttp2-sys v0.1.4+1.41.0
   Compiling libssh2-sys v0.2.23
   Compiling curl-sys v0.4.55+curl-7.83.1
   Compiling libgit2-sys v0.14.1+1.5.0
   Compiling regex-automata v0.1.10
   Compiling serde_json v1.0.85
   Compiling bstr v0.2.17
   Compiling atty v0.2.14
   Compiling num-traits v0.2.12
   Compiling foreign-types-shared v0.1.1
   Compiling openssl v0.10.38
   Compiling curl v0.4.43
   Compiling itoa v1.0.2
   Compiling regex v1.5.6
   Compiling ppv-lite86 v0.2.8
   Compiling openssl-probe v0.1.5
   Compiling hashbrown v0.12.3
   Compiling termcolor v1.1.2
   Compiling rand_chacha v0.3.0
   Compiling foreign-types v0.3.2
   Compiling crypto-common v0.1.6
   Compiling block-buffer v0.10.2
   Compiling filetime v0.2.14
   Compiling socket2 v0.4.1
   Compiling crossbeam-utils v0.8.8
   Compiling same-file v1.0.6
   Compiling subtle v2.4.1
   Compiling strsim v0.10.0
   Compiling heck v0.4.0
   Compiling digest v0.10.6
   Compiling walkdir v2.3.2
   Compiling flate2 v1.0.16
   Compiling tar v0.4.38
   Compiling clap_derive v3.2.18
   Compiling rand v0.8.5
   Compiling clap_lex v0.2.2
   Compiling bitmaps v2.1.0
   Compiling im-rc v15.1.0
   Compiling static_assertions v1.1.0
   Compiling textwrap v0.15.0
   Compiling either v1.6.0
   Compiling bytes v1.0.1
   Compiling semver v1.0.12
   Compiling hex v0.3.2
   Compiling fnv v1.0.7
   Compiling utf8parse v0.1.1
   Compiling remove_dir_all v0.5.3
   Compiling tempfile v3.2.0
   Compiling vte v0.3.3
   Compiling globset v0.4.9
   Compiling crypto-hash v0.3.4
   Compiling clap v3.2.20
   Compiling combine v4.6.6
   Compiling itertools v0.10.5
   Compiling sized-chunks v0.6.4
   Compiling kstring v2.0.0
   Compiling ordered-float v2.10.0
   Compiling cargo v0.67.1 (/build/rustc-1.66.1-src/src/tools/cargo)
error: linking with `/nix/store/iiq295j1z4q1sxmdbrl2j8ma3l5ns4wr-gcc-wrapper-11.3.0/bin/cc` failed: exit status: 1
  |
  = note: "/nix/store/iiq295j1z4q1sxmdbrl2j8ma3l5ns4wr-gcc-wrapper-11.3.0/bin/cc" "-m64" "/build/rustconTekW/symbols.o" "/build/rustc-1.66.1-src/target/release/build/cargo-af53de2408d15507/build_script_build-af53de2408d15507.build_script_build.38379bc1-cgu.0.rcgu.o" "/build/rustc-1.66.1-src/target/release/build/cargo-af53de2408d15507/build_script_build-af53de2408d15507.build_script_build.38379bc1-cgu.1.rcgu.o" "/build/rustc-1.66.1-src/target/release/build/cargo-af53de2408d15507/build_script_build-af53de2408d15507.build_script_build.38379bc1-cgu.10.rcgu.o" "/build/rustc-1.66.1-src/target/release/build/cargo-af53de2408d15507/build_script_build-af53de2408d15507.build_script_build.38379bc1-cgu.11.rcgu.o" "/build/rustc-1.66.1-src/target/release/build/cargo-af53de2408d15507/build_script_build-af53de2408d15507.build_script_build.38379bc1-cgu.12.rcgu.o" "/build/rustc-1.66.1-src/target/release/build/cargo-af53de2408d15507/build_script_build-af53de2408d15507.build_script_build.38379bc1-cgu.13.rcgu.o" "/build/rustc-1.66.1-src/target/release/build/cargo-af53de2408d15507/build_script_build-af53de2408d15507.build_script_build.38379bc1-cgu.14.rcgu.o" "/build/rustc-1.66.1-src/target/release/build/cargo-af53de2408d15507/build_script_build-af53de2408d15507.build_script_build.38379bc1-cgu.15.rcgu.o" "/build/rustc-1.66.1-src/target/release/build/cargo-af53de2408d15507/build_script_build-af53de2408d15507.build_script_build.38379bc1-cgu.2.rcgu.o" "/build/rustc-1.66.1-src/target/release/build/cargo-af53de2408d15507/build_script_build-af53de2408d15507.build_script_build.38379bc1-cgu.3.rcgu.o" "/build/rustc-1.66.1-src/target/release/build/cargo-af53de2408d15507/build_script_build-af53de2408d15507.build_script_build.38379bc1-cgu.4.rcgu.o" "/build/rustc-1.66.1-src/target/release/build/cargo-af53de2408d15507/build_script_build-af53de2408d15507.build_script_build.38379bc1-cgu.5.rcgu.o" "/build/rustc-1.66.1-src/target/release/build/cargo-af53de2408d15507/build_script_build-af53de2408d15507.build_script_build.38379bc1-cgu.6.rcgu.o" "/build/rustc-1.66.1-src/target/release/build/cargo-af53de2408d15507/build_script_build-af53de2408d15507.build_script_build.38379bc1-cgu.7.rcgu.o" "/build/rustc-1.66.1-src/target/release/build/cargo-af53de2408d15507/build_script_build-af53de2408d15507.build_script_build.38379bc1-cgu.8.rcgu.o" "/build/rustc-1.66.1-src/target/release/build/cargo-af53de2408d15507/build_script_build-af53de2408d15507.build_script_build.38379bc1-cgu.9.rcgu.o" "/build/rustc-1.66.1-src/target/release/build/cargo-af53de2408d15507/build_script_build-af53de2408d15507.16vk208nrbaqbxnu.rcgu.o" "-Wl,--as-needed" "-L" "/build/rustc-1.66.1-src/target/release/deps" "-L" "/nix/store/mwa7pqvphk6jrzdsk8a3clija0gbqc0b-zlib-aarch64-unknown-linux-gnu-1.2.13/lib" "-L" "/nix/store/8bzn95hgx2gs3marj3kr1hk3jrfv9a2z-rustc-1.66.1/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/build/rustc-1.66.1-src/target/release/deps/libtar-9a16f1146827c5e1.rlib" "/build/rustc-1.66.1-src/target/release/deps/libfiletime-421879cd737e5f09.rlib" "/build/rustc-1.66.1-src/target/release/deps/libflate2-86a014bff4497b20.rlib" "/build/rustc-1.66.1-src/target/release/deps/liblibz_sys-9e484850690f2a46.rlib" "/build/rustc-1.66.1-src/target/release/deps/libcfg_if-d478b96c366512b5.rlib" "/build/rustc-1.66.1-src/target/release/deps/liblibc-76d82e7d4be2b0ea.rlib" "/build/rustc-1.66.1-src/target/release/deps/libcrc32fast-fd689b8adfe25172.rlib" "/build/rustc-1.66.1-src/target/release/deps/libcfg_if-f5d55029c13eefd3.rlib" "/nix/store/8bzn95hgx2gs3marj3kr1hk3jrfv9a2z-rustc-1.66.1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-ea36449fed18305b.rlib" "/nix/store/8bzn95hgx2gs3marj3kr1hk3jrfv9a2z-rustc-1.66.1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-e9cace0cee982f9d.rlib" "/nix/store/8bzn95hgx2gs3marj3kr1hk3jrfv9a2z-rustc-1.66.1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-3872b3eac61be1a9.rlib" "/nix/store/8bzn95hgx2gs3marj3kr1hk3jrfv9a2z-rustc-1.66.1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-c73e346dd41f8b9d.rlib" "/nix/store/8bzn95hgx2gs3marj3kr1hk3jrfv9a2z-rustc-1.66.1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-4538e2ed064a3a2f.rlib" "/nix/store/8bzn95hgx2gs3marj3kr1hk3jrfv9a2z-rustc-1.66.1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-2321d2de3bec0d41.rlib" "/nix/store/8bzn95hgx2gs3marj3kr1hk3jrfv9a2z-rustc-1.66.1/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-04b12a19c2543db2.rlib" "/nix/store/8bzn95hgx2gs3marj3kr1hk3jrfv9a2z-rustc-1.66.1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-bc065996ad08a7bb.rlib" "/nix/store/8bzn95hgx2gs3marj3kr1hk3jrfv9a2z-rustc-1.66.1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-041fd64f04c9b036.rlib" "/nix/store/8bzn95hgx2gs3marj3kr1hk3jrfv9a2z-rustc-1.66.1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-663a2863325948cc.rlib" "/nix/store/8bzn95hgx2gs3marj3kr1hk3jrfv9a2z-rustc-1.66.1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-904f004fa2ba4aa2.rlib" "/nix/store/8bzn95hgx2gs3marj3kr1hk3jrfv9a2z-rustc-1.66.1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-3f0d450f2c9d1720.rlib" "/nix/store/8bzn95hgx2gs3marj3kr1hk3jrfv9a2z-rustc-1.66.1/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-5eeb3ea5e92be670.rlib" "/nix/store/8bzn95hgx2gs3marj3kr1hk3jrfv9a2z-rustc-1.66.1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-9d8e9b237b453516.rlib" "/nix/store/8bzn95hgx2gs3marj3kr1hk3jrfv9a2z-rustc-1.66.1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-fbca13ba953f17d2.rlib" "/nix/store/8bzn95hgx2gs3marj3kr1hk3jrfv9a2z-rustc-1.66.1/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-9ec9a1e5b6ad49f4.rlib" "/nix/store/8bzn95hgx2gs3marj3kr1hk3jrfv9a2z-rustc-1.66.1/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-37817752bb8d0deb.rlib" "/nix/store/8bzn95hgx2gs3marj3kr1hk3jrfv9a2z-rustc-1.66.1/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-b7433e602cfd87c3.rlib" "/nix/store/8bzn95hgx2gs3marj3kr1hk3jrfv9a2z-rustc-1.66.1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-2ef5491ab7b98245.rlib" "/nix/store/8bzn95hgx2gs3marj3kr1hk3jrfv9a2z-rustc-1.66.1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-e3d02613e0198423.rlib" "-Wl,-Bdynamic" "-lz" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/nix/store/8bzn95hgx2gs3marj3kr1hk3jrfv9a2z-rustc-1.66.1/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/build/rustc-1.66.1-src/target/release/build/cargo-af53de2408d15507/build_script_build-af53de2408d15507" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs"
  = note: /nix/store/178vvank67pg2ckr5ic5gmdkm3ri72f3-binutils-2.39/bin/ld: skipping incompatible /nix/store/mwa7pqvphk6jrzdsk8a3clija0gbqc0b-zlib-aarch64-unknown-linux-gnu-1.2.13/lib/libz.so when searching for -lz
          /nix/store/178vvank67pg2ckr5ic5gmdkm3ri72f3-binutils-2.39/bin/ld: cannot find -lz: No such file or directory
          /nix/store/178vvank67pg2ckr5ic5gmdkm3ri72f3-binutils-2.39/bin/ld: skipping incompatible /nix/store/mwa7pqvphk6jrzdsk8a3clija0gbqc0b-zlib-aarch64-unknown-linux-gnu-1.2.13/lib/libz.so when searching for -lz
          collect2: error: ld returned 1 exit status
          

error: could not compile `cargo` due to previous error
warning: build failed, waiting for other jobs to finish...
```

</details>

I'll see if I can find which PR this is related to....

**Comment by K900** [comment]
Mesa x86_64-darwin builds on SDK 11, pushed to #210062 to simplify testing Qt.

**Comment by figsoda** [comment]
https://github.com/NixOS/nixpkgs/pull/210394 for the rust cross compilation fix

**Comment by mweinelt** [comment]
Most failed packages at this point are due to recursing into python311.pkgs, which will receive fixes over the next weeks and months, as libraries are catching up.

**Comment by vcunat** [comment]
Perhaps `libepoxy` regression on x86_64-darwin is notable, with review-tools reporting 452 builds just because of that.  Log: https://hydra.nixos.org/build/204450990

**Pull request merged**
