### PR TITLE
Revert "unscd: init at 0.53"

### LINKED ISSUE #169157: failure to build `lazy-options.json` on the main branch on x86_64-linux
### Describe the bug

Build failure

### Steps To Reproduce

On 6d21daa43e7459db7aee4fec22fb209e3047d3ae, do a nixos-rebuild

### Expected behavior

Build

### Additional context

```
building '/nix/store/4ljfw24cysbshllrvb5rm2ygndvf6pwz-lazy-options.json.drv'...
error: attribute 'stdenv' missing

       at /nix/store/5rid53r50kj9iai1f880vccndyspay8g-nixos/modules/services/system/nscd.nix:38:22:

           37|         type = types.package;
           38|         default = if pkgs.stdenv.hostPlatform.libc == "glibc"
             |                      ^
           39|           then pkgs.stdenv.cc.libc.bin

       … while evaluating the attribute 'default'

       at /nix/store/5rid53r50kj9iai1f880vccndyspay8g-nixos/modules/services/system/nscd.nix:38:9:

           37|         type = types.package;
           38|         default = if pkgs.stdenv.hostPlatform.libc == "glibc"
             |         ^
           39|           then pkgs.stdenv.cc.libc.bin

       … while evaluating 'isDerivation'

       at /nix/store/r40kv5ppdkqkgalimszl7hsvhz8csq1c-lib/attrsets.nix:427:18:

          426|   */
          427|   isDerivation = x: x.type or null == "derivation";
             |                  ^
          428|

       … from call site

       at /nix/store/r40kv5ppdkqkgalimszl7hsvhz8csq1c-lib/options.nix:256:8:

          255|   scrubOptionValue = x:
          256|     if isDerivation x then
             |        ^
          257|       { type = "derivation"; drvPath = x.name; outPath = x.name; name = x.name; }

       … while evaluating 'scrubOptionValue'

       at /nix/store/r40kv5ppdkqkgalimszl7hsvhz8csq1c-lib/options.nix:255:22:

          254|   */
          255|   scrubOptionValue = x:
             |                      ^
          256|     if isDerivation x then

       … from call site

       at /nix/store/r40kv5ppdkqkgalimszl7hsvhz8csq1c-lib/options.nix:235:54:

          234|         // optionalAttrs (opt ? example) { example = scrubOptionValue opt.example; }
          235|         // optionalAttrs (opt ? default) { default = scrubOptionValue opt.default; }
             |                                                      ^
          236|         // optionalAttrs (opt ? defaultText) { default = opt.defaultText; }

       … while evaluating the attribute 'default'

       at /nix/store/r40kv5ppdkqkgalimszl7hsvhz8csq1c-lib/options.nix:235:44:

          234|         // optionalAttrs (opt ? example) { example = scrubOptionValue opt.example; }
          235|         // optionalAttrs (opt ? default) { default = scrubOptionValue opt.default; }
             |                                            ^
          236|         // optionalAttrs (opt ? defaultText) { default = opt.defaultText; }

       … while evaluating 'isDerivation'

       at /nix/store/r40kv5ppdkqkgalimszl7hsvhz8csq1c-lib/attrsets.nix:427:18:

          426|   */
          427|   isDerivation = x: x.type or null == "derivation";
             |                  ^
          428|

       … from call site

       at /nix/store/5rid53r50kj9iai1f880vccndyspay8g-nixos/lib/make-options-doc/default.nix:42:8:

           41|   substSpecial = x:
           42|     if lib.isDerivation x then { _type = "derivation"; name = x.name; }
             |        ^
           43|     else if builtins.isAttrs x then lib.mapAttrs (name: substSpecial) x

       … while evaluating 'substSpecial'

       at /nix/store/5rid53r50kj9iai1f880vccndyspay8g-nixos/lib/make-options-doc/default.nix:41:18:

           40|   # effect, since _type is already used by the module system.
           41|   substSpecial = x:
             |                  ^
           42|     if lib.isDerivation x then { _type = "derivation"; name = x.name; }

       … from call site

       at /nix/store/5rid53r50kj9iai1f880vccndyspay8g-nixos/lib/make-options-doc/default.nix:51:54:

           50|     // lib.optionalAttrs (opt ? example) { example = substSpecial opt.example; }
           51|     // lib.optionalAttrs (opt ? default) { default = substSpecial opt.default; }
             |                                                      ^
           52|     // lib.optionalAttrs (opt ? type) { type = substSpecial opt.type; }
Cacheable portion of option doc build failed.
Usually this means that an option attribute that ends up in documentation (eg `default` or `description`) depends on the restricted module arguments `config` or `pkgs`.

Rebuild your configuration with `--show-trace` to find the offending location. Remove the references to restricted arguments (eg by escaping their antiquotations or adding a `defaultText`) or disable the sandboxed build for the failing module by setting `meta.buildDocsInSandbox = false`.

error: builder for '/nix/store/4ljfw24cysbshllrvb5rm2ygndvf6pwz-lazy-options.json.drv' failed with exit code 1
```

### Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.3, NixOS, 22.05 (Quokka), 22.05.git.4cea7a03db4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(root): `"nixos, nixos-small"`
 - channels(fabian): `"home-manager, nixos-19.03-19.03, nixos-19.09-19.09, nixos-20.03-20.03, nixos-20.09-20.09, nixos-21.05-21.05, nixos-21.11-21.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by dasJ**
Reverts NixOS/nixpkgs#124019 to unbreak ofborg's manual job

### CODE REVIEW

**Review by thiagokokada — APPROVED** [review]
Really curious how the module changes would block the channel.

Maybe it would be better to introduce the module changes separated from the unscd package itself.

Anyway, approved.

**Comment by alyssais** [comment]
Missing `defaultText` -> sandboxed manual build failure -> channel blocked?

**Comment by thiagokokada** [comment]
> Missing `defaultText` -> sandboxed manual build failure -> channel blocked?

I don't think `defaultText` is a required field for an option, but I may be wrong here.

**Comment by pennae** [comment]
> I don't think defaultText is a required field for an option, but I may be wrong here.

it is if the `default` references `pkgs` or `config` in some way, which is what happened here

**Comment by thiagokokada** [comment]
> > I don't think defaultText is a required field for an option, but I may be wrong here.
> 
> it is if the `default` references `pkgs` or `config` in some way, which is what happened here

I am pretty sure that I saw in the past fields with `default = pkgs.something` (was very common for `package` option in modules) without `defaultText` and not having any issues. But this was way before (NixOS 19.09 or 21.05), maybe something changed.

**Comment by alyssais** [comment]
It's a fairly recent change.

**Comment by thiagokokada** [comment]
> It's a fairly recent change.

Huh... nice to know them.

**Comment by zowoq** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/169196

**Pull request closed without merging**
