### PR TITLE
nixos/redis: allow to move the state directory

### PR DESCRIPTION
**Pull request by JulesdeCube**
## Description of changes

The NixOS Redis module use the systemd `StateDirectory` directive to create the directory where redis will store it's data. this limit the placement of directory under `/var/lib`.

This PR:
- introduce the `dir` redis server option to allow to move the redis folder outside `/var/lib`.
- introduce a new oneshot systemd service to create the redis state directory when it's override by `dir` option.
- introduce the `dbFilename` redis server option to allow to modifed the previously hardcoded value.
- modify the redis test to validate the new `dir` redis server option.

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [X] `sandbox = true`
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by bjornfor** [comment]
> this limit the placement of directory under /var/lib.

What about using a bind mount on top of /var/lib/STATE_DIRECTORY? Doesn't that work and is simpler (works for all services without NixOS module changes)?

**Comment by JulesdeCube** [comment]
> > this limit the placement of directory under /var/lib.
> 
> What about using a bind mount on top of /var/lib/STATE_DIRECTORY? Doesn't that work and is simpler (works for all services without NixOS module changes)?

You can´t use a bind mount because the `/var/lib/STATE_DIRECTORY` directory is created at run time by systemd `StateDirectory` directive therefore the bind mount will fail as the target and propably source directory (example `/data/redis`) didn´t exist. furthermore with a bind mount mounting you can´t specify permission and ownership.

**Comment by bjornfor** [comment]
> You can´t use a bind mount because the `/var/lib/STATE_DIRECTORY` directory is created at run time by systemd `StateDirectory` directive therefore the bind mount will fail as the target and propably source directory (example `/data/redis`) didn´t exist. furthermore with a bind mount mounting you can´t specify permission and ownership.

Did you test it?

The `fileSystems` module creates both source and destination directories, and permissions can be configured with systemd-tmpfiles on the source directory:

```nix
  fileSystems = {
    "/var/lib/foo" = {
      device = "/data/foo";
      options = [ "bind" ];
    };
  };
  systemd.tmpfiles.rules = [
    # Type Path Mode User Group Age Argument
    "d /data/foo 0770 user1 group1 - -"
  ];
```

I didn't test this with systemd, but it [should work](https://github.com/systemd/systemd/issues/25097).

**Comment by JulesdeCube** [comment]
excuse me for the delay,

I try your proposition this weekend and it work (no need for `systemd.tmpfiles.rules`).

It have try before with only the `mount.8` command that fail when the folder don´t exist.

`fileSystems` generate the `/etc/fstab` file that is used to by [`systemd-fstab-generator`](https://www.freedesktop.org/software/systemd/man/latest/systemd-fstab-generator.html) to generate the `systemd.mount` units.

According to the `systemd.mount` it create the mounting point if it didn´t exist (see [`Where=`](https://www.freedesktop.org/software/systemd/man/latest/systemd.mount.html#Where=) )

After that the redis service set the right permission at statup.

So excuse me for this useless PR and thank for the time you take to answer me.

**Pull request closed without merging**
