### PR TITLE
treewide: remove obsolete attribute goPackagePath in buildGoModule derivations

### PR DESCRIPTION
**Pull request by timstott**
###### Motivation for this change

The `buildGoModule` infrastructure does not make use of `goPackagePath`, it is a residue from `buildGoPackage`. 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zimbatm** [comment]
buildGoModule also has to be changed to remove or make that attribute optional. Currently all the packages are failing to build, see https://github.com/NixOS/nixpkgs/blob/e828343d7c2244e3366dfc1f7eab578ce791ec0d/pkgs/development/go-packages/generic/default.nix#L94-L98

**Comment by zimbatm** [comment]
it might be easier to write a simplified `pkgs.buildGoModule2` rather than keep this back-compat.

**Comment by zimbatm** [comment]
Result of `nixpkgs-review pr 95092` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
<br>- vimPlugins.YouCompleteMe
<br>- ycmd
</details>
<details>
  <summary>26 packages built:</summary>
<br>- age
<br>- caddy
<br>- coredns
<br>- drone
<br>- godef
<br>- gomodifytags
<br>- gomuks
<br>- gopkgs
<br>- gosec
<br>- hcloud
<br>- iamy
<br>- kapow
<br>- kind
<br>- kube3d
<br>- matterbridge
<br>- oneshot
<br>- reftools
<br>- sensu-go-agent
<br>- sensu-go-backend
<br>- sensu-go-cli
<br>- shadowfox
<br>- styx
<br>- tailscale
<br>- telegraf
<br>- vimPlugins.vim-go
<br>- zsh-history
</details>

**Comment by timstott** [comment]
Result of `nixpkgs-review pr 95092` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>28 packages built:</summary>
<br>- age
<br>- caddy
<br>- coredns
<br>- drone
<br>- godef
<br>- gomodifytags
<br>- gomuks
<br>- gopkgs
<br>- gosec
<br>- hcloud
<br>- iamy
<br>- kapow
<br>- kind
<br>- kube3d
<br>- matterbridge
<br>- oneshot
<br>- reftools
<br>- sensu-go-agent
<br>- sensu-go-backend
<br>- sensu-go-cli
<br>- shadowfox
<br>- styx
<br>- tailscale
<br>- telegraf
<br>- vimPlugins.YouCompleteMe
<br>- vimPlugins.vim-go
<br>- ycmd
<br>- zsh-history
</details>

**Review by zimbatm — APPROVED** [review]
looking good!

**Comment by timstott** [comment]
Result of `nixpkgs-review pr 95092` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>37 packages built:</summary>
<br>- age
<br>- caddy
<br>- clash
<br>- coredns
<br>- drone
<br>- drone-cli
<br>- gitAndTools.git-bug
<br>- godef
<br>- gomodifytags
<br>- gomuks
<br>- gopkgs
<br>- gosec
<br>- hcloud
<br>- iamy
<br>- kapow
<br>- kind
<br>- kube3d
<br>- kubeprompt
<br>- matterbridge
<br>- mkcert
<br>- nix-build-uncached
<br>- oneshot
<br>- reftools
<br>- sensu-go-agent
<br>- sensu-go-backend
<br>- sensu-go-cli
<br>- shadowfox
<br>- sourcehut.buildsrht
<br>- sourcehut.gitsrht
<br>- sourcehut.hgsrht
<br>- styx
<br>- tailscale
<br>- telegraf
<br>- vimPlugins.YouCompleteMe
<br>- vimPlugins.vim-go
<br>- ycmd
<br>- zsh-history
</details>

**Comment by timstott** [comment]
This is ready to be merged @zimbatm :tada:

**Comment by zimbatm** [comment]
thanks for your contribution!

**Pull request merged**
