### PR TITLE
gnomeExtensions.dash-to-panel: 43 -> 45

### PR DESCRIPTION
**Pull request by newAM**
###### Motivation for this change

Update dash-to-panel to 45.

Changes:
https://github.com/home-sweet-gnome/dash-to-panel/compare/v43...v44
https://github.com/home-sweet-gnome/dash-to-panel/compare/v44...v45

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - N/A x86_64-darwin
  - N/A aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by buckley310** [comment]
Is it just me, or does v44 not support GNOME 41?
It looks like gs41 support was added, but then removed:
https://github.com/home-sweet-gnome/dash-to-panel/commits/v44/metadata.json

**Comment by newAM** [comment]
Oh, good catch, I missed that commit.

Looks like the tracking issue for 41 is here: https://github.com/home-sweet-gnome/dash-to-panel/issues/1512

**Comment by piegamesde** [comment]
They just released v45 with GNOME 41 support: https://github.com/home-sweet-gnome/dash-to-panel/releases/tag/v45

Please keep the upgrades as separate commits: v45 also drops support for GNOME 40, this will make possible backporting or pinning easier.

**Comment by newAM** [comment]
> Please keep the upgrades as separate commits: v45 also drops support for GNOME 40, this will make possible backporting or pinning easier.

Done!  Thanks for the heads up.

**Review by piegamesde — APPROVED** [review]

**Comment by newAM** [comment]
Tested the new version on nixos unstable (gnome 41), it works:
Screenshot from 2021-11-13 21-02-30

**Comment by buckley310** [comment]
Looks good here.

**Pull request merged**
