### PR TITLE
gramps: add support for recommended packages, add joncojonathan to maintainers

### PR DESCRIPTION
**Pull request by joncojonathan**
###### Motivation for this change
Added maintainers data and populated with @joncojonathan.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [n/a] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [n/a] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by timokau** [comment]
This makes #48008 unnecessary right?

As a nitpick: Please use imperative in your commit messages (e.g. `gramps: add support for recommended packages`). You can change that with an interactive rebase (`git rebase --interactive HEAD~2`, then mark the packages you want to edit with `r`).

**Comment by joncojonathan** [comment]
> This makes #48008 unnecessary right?

It does.  Sorry, I wasn't expecting that behaviour from the PR process.

> As a nitpick: Please use imperative in your commit messages (e.g. `gramps: add support for recommended packages`). You can change that with an interactive rebase (`git rebase --interactive HEAD~2`, then mark the packages you want to edit with `r`).

Noted, thanks.

**Comment by timokau** [comment]
Yeah for small changes like these which depend on each other it makes sense to combine them in one PR.

Also please remove the dot at the end of the commit messages.

**Comment by joncojonathan** [comment]
Understood, I'll make sure I don't submit with those in future.  Does the
full stop break a process somewhere?

I'm assuming you don't need me to edit these commit messages?

**Comment by timokau** [comment]
> Understood, I'll make sure I don't submit with those in future. Does the full stop break a process somewhere?

No, its just a matter of standardization.

> I'm assuming you don't need me to edit these commit messages?

I did assume you'd do that, which is why I explained how to do it. Any reason not to?

**Comment by joncojonathan** [comment]
@timokau I've recommitted without the ending full stop.  I appreciate the tuition in use of `git1, never done an interactive rebase before.

Only reason I wouldn't have done is because it seems like something I'd let slide once and just let them know.  There's nothing in [the contributing guide](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md) that says to not have a closing period, only for `meta.description`.  I'll propose a clarification in that to help others.

Thanks again for the `git` tips.

**Comment by timokau** [comment]
I personally think my job as a reviewer is it to hold the people whose contributions I review to a high standard. I make plenty of mistakes when contributing myself and appreciate when the people reviewing my code do the same. Unfortunately there are no clear review guidelines for nixpkgs, so someone else may review differently. Fixing a commit message should not take very long. Maybe the first time it does, but aferwards you'll know your tooling better. I hope I don't sound antagonistic, I'm grateful for your contribution.

These rules aren't in the contribution guide, but they are [general git convention](https://chris.beams.io/posts/git-commit/). It couln't hurt to mention that in the contribution guidelines though.

Thanks for fixing the punctuation. The commit messages are still not in imperative ("`add`" instead of "`added`") and you added a merge conflict I don't understand though (you can also drop that with an interactive rebase).

**Comment by joncojonathan** [comment]
Should be imperative now @timokau, I saw you'd renamed the PR so lost track and completely forgot to change the commit message, sorry.

No problem holding me to a high standard, I'd do the same, just with a different approach.  I'll read the general git convention link as I'm still very green when it comes to using `git`.

Everything look OK now?  I think I managed to drop the merge conflict.  Really like this interactive rebase thing!

**Comment by timokau** [comment]
@GrahamcOfBorg build gramps

Looks perfect, thank you for the contribution and your patience with the review :) Merge pending on the bots approval.

**Pull request merged**
