### PR TITLE
Gitlab version bump

### PR DESCRIPTION
**Pull request by Zer0-**
###### Things done:

(http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- [ X] Built on platform(s): NixOS / Linux

### CODE REVIEW

**Comment by domenkozar** [comment]
cc @globin @fpletz

**Comment by globin** [comment]
Ah you found the mail sending bug :heart:
Already tried finding that but didn't see the typo :hear_no_evil: 

Generally we use the upstream Gemfile.lock and generate a new gemset.nix (adding the nulladapter) from there but should be find for this minor bump.

**Comment by joachifm** [comment]
Should 10198b586e4c7a177b7922c511c0176051f730c4 be included in the release, seeing as it fixes a bug?

**Comment by globin** [comment]
Yes, will you cherry-pick?

**Comment by joachifm** [comment]
Sure. Do you want the version bump, too?

**Comment by globin** [comment]
Yes, it's only a bugfix release. :+1:

**Comment by joachifm** [comment]
Done

**Comment by phil-legitmix** [comment]
> Generally we use the upstream Gemfile.lock

Oh dang sorry gents I am not a ruby developer. That would have saved me from writing a bunch of vim macros to get gem sha hashes for me :/

**Comment by globin** [comment]
Cheers :beers:

**Comment by fpletz** [comment]
For the record: I think we should backport all Gitlab version bumps to our latest stable release as most of them contain important fixes. Gitlab is moving fast (1 release per month) and old versions won't get security fixes.

**Comment by domenkozar** [comment]
:+1:

**Pull request merged**
