### PR TITLE
mutt: 2.0.5 -> 2.0.6

### PR DESCRIPTION
**Pull request by matthiasbeyer**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 115313` at 48c2a14f run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/98bb7a4f978dc9cbbe48781601d723dd">grepm</a></li></li>
    <li><a href="https://gist.github.com/c22e3d4d1933bd807b7fe546e6ff7faa">mutt</a></li> (mutt-with-sidebar)</li>
  </ul>
</details>

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 115313` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>grepm</li>
    <li>mutt (mutt-with-sidebar)</li>
  </ul>
</details>

**Comment by matthiasbeyer** [comment]
So this is where we at? We have automatic reviews for automatic PRs (okay, this one was a manual one...)?
Now, where is my automatic merge and my automatic update for my installation?

Maybe we should just shut down nixpkgs and let bots do all the work, what'd you think?

**Review by siraben — APPROVED** [review]
LGTM. I ran the nixpkgs-review on darwin manually.

**Comment by grahamc** [comment]
> what'd you think?

I think we need to take care to remember that the automatic builds / runs (by bots or by humans) are useful tools, but we also need people to review the expressions, look for license changes, security vulnerabilities deserving of backport, style, etc.

**Review by rnhmjoj — APPROVED** [review]
Changelog is [here](https://gitlab.com/muttmua/mutt/-/commit/98f8cb831b2944ba6a21c34d1943cfa0b9bedc9a): it's only a couple of bug fixes.
Built and run with my config: looks fine.

**Pull request merged**
