### PR TITLE
ark-pixel-font: fix build

### LINKED ISSUE #310751: Build failure: pixel-font-builder
### Steps To Reproduce

looking over broken python packages for ZHF and pixel-font-builder is missing a python module and needs a dependency relaxed.

1. build *pixel-font-builder"

### Build log

https://hydra.nixos.org/build/257387773/nixlog/1/tail
```
Checking runtime dependencies for pixel_font_builder-0.0.19-py3-none-any.whl
  - fonttools>=4.51.0 not satisfied by version 4.49.0
  - pcffont not installed
```

### Additional context

pcffont not part of nixpkgs
https://github.com/TakWolf/pcffont

would add it but no longer a maintainer

### Notify maintainers

@h7x4

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by eclairevoyant**
## Description of changes

- **python311Packages.bdffont: 0.0.20 -> 0.0.24**
- **python311Packages.pcffont: init at 0.0.11**
- **python311Packages.pixel-font-builder: 0.0.19 -> 0.0.24**
- **ark-pixel-font: 2024.04.05 -> 2024.05.12**

fixes #310751

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by eclairevoyant** [comment]
Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>13 packages built:</summary>
  <ul>
    <li>ark-pixel-font</li>
    <li>python311Packages.bdffont</li>
    <li>python311Packages.bdffont.dist</li>
    <li>python311Packages.pcffont</li>
    <li>python311Packages.pcffont.dist</li>
    <li>python311Packages.pixel-font-builder</li>
    <li>python311Packages.pixel-font-builder.dist</li>
    <li>python312Packages.bdffont</li>
    <li>python312Packages.bdffont.dist</li>
    <li>python312Packages.pcffont</li>
    <li>python312Packages.pcffont.dist</li>
    <li>python312Packages.pixel-font-builder</li>
    <li>python312Packages.pixel-font-builder.dist</li>
  </ul>
</details>

**Review by ghost — APPROVED** [review]
LGTM. Thanks!

**Comment by TakWolf** [comment]
The latest version of `bdffont` and `pcffont` should be able to rollback to Python 10.
I don't know much about Nix, but it seems that they are currently marked as python11

**Comment by eclairevoyant** [comment]
Not sure about `bdffont` offhand, but `pixel-font-builder` uses `enum.StrEnum` which was only [added in python 3.11](https://docs.python.org/3/library/enum.html#enum.StrEnum), hence the restriction there.

I'll bump the version of `ark-pixel-font` though, thanks.

**Review by nicoonoclaste — APPROVED** [review]

**Comment by eclairevoyant** [comment]
Result of `nixpkgs-review pr 310779` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>13 packages built:</summary>
  <ul>
    <li>ark-pixel-font</li>
    <li>python311Packages.bdffont</li>
    <li>python311Packages.bdffont.dist</li>
    <li>python311Packages.pcffont</li>
    <li>python311Packages.pcffont.dist</li>
    <li>python311Packages.pixel-font-builder</li>
    <li>python311Packages.pixel-font-builder.dist</li>
    <li>python312Packages.bdffont</li>
    <li>python312Packages.bdffont.dist</li>
    <li>python312Packages.pcffont</li>
    <li>python312Packages.pcffont.dist</li>
    <li>python312Packages.pixel-font-builder</li>
    <li>python312Packages.pixel-font-builder.dist</li>
  </ul>
</details>

**Pull request merged**
