### PR TITLE
enlightenment.efl: 1.21.1 -> 1.22.1

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

Update efl to version 1.22.1.
[Enlightenment Foundation Libraries 1.22 Release](https://www.enlightenment.org/news/efl-1.22.0)
[EFL 1.22.1 release](https://www.enlightenment.org/news/efl-1.22.1)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by romildo** [comment]
@GrahamcOfBorg build enlightenment.efl enlightenment.terminology enlightenment.enlightenment enlightenment.econnman enlightenment.rage enlightenment.ephoto pythonPackages.python-efl

**Comment by c0bw3b** [comment]
@GrahamcOfBorg build enlightenment.enlightenment enlightenment.terminology pythonPackages.python-efl

**Comment by c0bw3b** [comment]
A local nix-review of the whole PR ended with:
```shell
builder for '/nix/store/c607qhmbxh1x5w9nackkkvfddqalf1a5-python3.7-python-efl-1.21.0.drv' failed with exit code 1; last 10 log lines:
  efl/eo/efl.eo.c: In function ‘__pyx_pf_3efl_2eo_8event_global_thaw’:
  efl/eo/efl.eo.c:1984:3: error: too many arguments to function ‘efl_event_global_thaw’
     efl_event_global_thaw(((Eo const *)efl_object_class_get()));
     ^~~~~~~~~~~~~~~~~~~~~
  In file included from /nix/store/p4z6kzani0zfcqdrnlya699hgr5hlkm7-efl-1.22.1/include/eo-1/Eo.h:216:0,
                   from efl/eo/efl.eo.c:614:
  /nix/store/p4z6kzani0zfcqdrnlya699hgr5hlkm7-efl-1.22.1/include/eo-1/efl_object.eo.h:511:12: note: declared here
   EOAPI void efl_event_global_thaw(void);
              ^~~~~~~~~~~~~~~~~~~~~
  error: command 'gcc' failed with exit status 1
[...]
3 package failed to build:
enlightenment.econnman python27Packages.pythonefl python37Packages.pythonefl
```

Let's wait for ofBorg's build results

**Comment by c0bw3b** [comment]
@GrahamcOfBorg build enlightenment.econnman

**Comment by c0bw3b** [comment]
So it's actually breaking `econnman` :/

**Comment by romildo** [comment]
The [`python-efl` git repository](https://git.enlightenment.org/bindings/python/python-efl.git/) already has fixes for that.

Updating `pythonefl` to current git revision works. @c0bw3b what do you think about doing this until a new release is done?

``` patch
modified   pkgs/development/python-modules/python-efl/default.nix
@@ -1,21 +1,22 @@
-{ stdenv, fetchurl, buildPythonPackage, pkgconfig, python, enlightenment }:
+{ stdenv, fetchgit, buildPythonPackage, pkgconfig, python, enlightenment }:
 
 # Should be bumped along with EFL!
 
 buildPythonPackage rec {
   name = "python-efl-${version}";
-  version = "1.21.0";
+  version = "2019-04-23";
 
-  src = fetchurl {
-    url = "http://download.enlightenment.org/rel/bindings/python/${name}.tar.xz";
-    sha256 = "08x2cv8hnf004c3711250wrax21ffj5y8951pvk77h98als4pq47";
+  src = fetchgit {
+    url = https://git.enlightenment.org/bindings/python/python-efl.git;
+    rev = "8ff30f9eddd4bd5b89fae96ad090f964480e4179";
+    sha256 = "1mhzs2gmwx4wc07p3pdbg6z8ja4sq4sfrj5v36frz4paj7bwk4d6";
   };
 
   nativeBuildInputs = [ pkgconfig ];
 
   buildInputs = [ enlightenment.efl ];
 
-  propagatedBuildInputs = [ python.pkgs.dbus-python ];
+  propagatedBuildInputs = [ python.pkgs.dbus-python python.pkgs.cython ];
 
   preConfigure = ''
     export NIX_CFLAGS_COMPILE="$(pkg-config --cflags efl) -I${stdenv.lib.getDev python.pkgs.dbus-python}/include/dbus-1.0 $NIX_CFLAGS_COMPILE"
```

**Comment by c0bw3b** [comment]
From the git repo it seems the publication of [release 1.22 ](https://git.enlightenment.org/bindings/python/python-efl.git/commit/) is imminent.

**Review by c0bw3b — APPROVED** [review]
Local nix-review is ok:
```shell
8 package were build:
enlightenment.econnman enlightenment.efl enlightenment.enlightenment enlightenment.ephoto enlightenment.rage enlightenment.terminology python27Packages.pythonefl python37Packages.pythonefl
```

**Pull request merged**
