### PR TITLE
adding grub option to avoid #21830 to documentation

### PR DESCRIPTION
**Pull request by ghost**
###### Motivation for this change
A simple documentation update - there is no single point of reference in the documentation for a luks-encrypted setup with grub which requires new users to look through issues on github, instead of the documentation.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vcunat** [comment]
I didn't have to do that &ndash; I guess it only applies if `/boot` is encrypted, so the text should reflect it (if it's so).

**Comment by Riptawr** [comment]
well, i couldn't install it and my ```/boot``` is on the encrpyted ```/``` - i'll add it to the description then

**Comment by vcunat** [comment]
I'd simply reformulate it to mention `/boot`.  I suspect it might be common to e.g. just encrypt `/home` (my case).

**Comment by Riptawr** [comment]
I did not have the chance to look at NixOs specifically in that regard, but everything less than full disk encryption leaves you open to many attacks - the simplest is to install a keylogger on a non-encrpyted part of the system and snoop your password for /home. 

The [arch wiki](https://wiki.archlinux.org/index.php/disk_encryption) summs it up nicely though, but i am guessing full disk encryption will be a must for the more paranoid of us, so we may encounter this issue more often than expected.

**Comment by Riptawr** [comment]
edited it, please have another look. Keep forgetting this is not markdown

**Comment by vcunat** [comment]
(topic diversion) Heh, in my case I don't dream of such an advanced attack.  The only realistic scenario here is that someone might steal the tiny machine, and even there it seems rather unlikely (s)he would be interested in any data.  But certainly, some will want/need better security; all my work is published immediately :-)

**Comment by vcunat** [comment]
I squashed and used the `<filename>` tag to be more consistent.

**Comment by vcunat** [comment]
Thanks!

**Pull request closed without merging**
