### PR TITLE
nixos/rss2email: globally install rss2email

### PR DESCRIPTION
**Pull request by alyssais**
For man pages.

### CODE REVIEW

**Comment by Ekleog** [comment]
Hmmm… The `r2e` that would be in `$PATH` would have no link whatsoever with the one enabled by the service as far as I remember, so it would sound like a footgun, but the manpage *is* a point.

Do you think it'd be reasonable to split the `rss2email` derivation to have `rss2email.man`, and only include the `.man` in `systemPackages`? This way it wouldn't be as much of a trap

**Comment by alyssais** [comment]
What do you mean? it’s the same package as in the ExecStart?

**Comment by Ekleog** [comment]
Indeed, what I mean is doing `r2e run` won't actually run `rss2email`, because it'd operate as a different user -- so the `r2e` in `$PATH` would have no way to interoperate with the `services.rss2email` module -- contrarily to what I usually see with modules that make available something in `systemPackages`

**Comment by alyssais** [comment]
Léo Gaspard <notifications@github.com> writes:

> Indeed, what I mean is doing `r2e run` won't actually run `rss2email`,
> because it'd operate as a different user -- so the `r2e` in `$PATH`
> would have no way to interoperate with the `services.rss2email` module
> -- contrarily to what I usually see with modules that make available
> something in `systemPackages`

I don't find that surprising at all.  I've seen lots of modules that
install packages globally in a similar style.  I'd be more surprised if
rss2email _was_ some magic program for interacting with the service, to
be honest -- I'd expect that to be rss2emailctl or something.

**Comment by Ekleog** [comment]
Then I guess I just never noticed these services, and this is good to go :) my experience has been mostly with (systemd and) opensmtpd, where the *ctl command is installed -- I haven't noticed many other packages globally-installing packages, but if I just missed them, then that's all good!

**Pull request merged**
