### PR TITLE
gopass: 1.15.14 -> 1.15.15 with added updateScript

### PR DESCRIPTION
**Pull request by kachick**
Release: https://github.com/gopasspw/gopass/releases/tag/v1.15.15

Related projects are already updated https://github.com/NixOS/nixpkgs/pull/358760, https://github.com/NixOS/nixpkgs/pull/358876
And nixpkgs-update skipped because of the title matched with one of above PRs. https://nixpkgs-update-logs.nix-community.org/gopass/2024-11-25.log

```
gopass 1.15.14 -> 1.15.15 https://github.com/gopasspw/gopass/releases
attrpath: gopass
Checking auto update branch...
No auto update branch exists
There might already be an open PR for this update:
- gopass-jsonapi: 1.15.14 -> 1.15.15
  URL "https://api.github.com/repos/NixOS/nixpkgs/issues/358760"
```

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by kachick** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 360950`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>git-credential-gopass</li>
    <li>gopass</li>
    <li>gopass-hibp</li>
    <li>gopass-summon-provider</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:x: 4 packages failed to build:</summary>
  <ul>
    <li>git-credential-gopass</li>
    <li>gopass</li>
    <li>gopass-hibp</li>
    <li>gopass-summon-provider</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:x: 4 packages failed to build:</summary>
  <ul>
    <li>git-credential-gopass</li>
    <li>gopass</li>
    <li>gopass-hibp</li>
    <li>gopass-summon-provider</li>
  </ul>
</details>

---


Failed in macos

pr-360950/logs/gopass-x86_64-darwin.log

```
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/6aa55h0gjgqrq5d85r0sp9gx12v0kcx9-source
source root is source
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: buildPhase
@nix { "action": "setPhase", "phase": "buildPhase" }
Building subPackage ./.
# github.com/kbinani/screenshot
vendor/github.com/kbinani/screenshot/darwin.go:9:10: fatal error: 'ScreenCaptureKit/ScreenCaptureKit.h' file not found
#include <ScreenCaptureKit/ScreenCaptureKit.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by kachick** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 360950`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>git-credential-gopass</li>
    <li>gopass</li>
    <li>gopass-hibp</li>
    <li>gopass-summon-provider</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>git-credential-gopass</li>
    <li>gopass</li>
    <li>gopass-hibp</li>
    <li>gopass-summon-provider</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>git-credential-gopass</li>
    <li>gopass</li>
    <li>gopass-hibp</li>
    <li>gopass-summon-provider</li>
  </ul>
</details>

**Comment by sikmir** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 360950`

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>git-credential-gopass</li>
    <li>gopass</li>
    <li>gopass-hibp</li>
    <li>gopass-summon-provider</li>
  </ul>
</details>

**Review by sikmir — APPROVED** [review]

**Comment by kachick** [comment]
Failed `ofborg-eval-lib-tests — nix-build --arg pkgs import ./. {} ./lib/tests/release.nix` from https://github.com/NixOS/nixpkgs/pull/354738, I'll rebase to avoid it.

**Review by sikmir — APPROVED** [review]

**Comment by kachick** [comment]
Thanks!

**Pull request merged**
