### PR TITLE
Qtile window manager - http://www.qtile.org/

### PR DESCRIPTION
**Pull request by kamilchm**

### CODE REVIEW

**Comment by jagajaga** [comment]
Separate commits for service and pkg.
And rename them as it said in `CONTRIBUTING.md`

**Comment by kamilchm** [comment]
Sure, I missed ``CONTRIBUTING.md``. I'll fix it.

**Comment by domenkozar** [comment]
Ping :)

**Comment by kamilchm** [comment]
I found few minor bugs in it. Probably missing dependencies like dbus etc..
I'll prepare new PRs when I make sure it works.

**Comment by kamilchm** [comment]
Maybe some can help me with one problem?
There's a restart command in qtile to changing its config in action hooks.
It execute ``sys.executable`` https://github.com/qtile/qtile/blob/develop/libqtile/manager.py#L1304
But when it tries to do this from nix installation, there's a python error:
```
/nix/store/8lzdi1wbgyxbibsc04lnykc5rpfyr87p-python-2.7.10/bin/python2.7: can't open file '.qtile-wrapped': [Errno 2] No such file or directory
```
Looks like that ``sys.executable`` can't find ``qtile`` installation :(
Does anyone know how can I fix that?

**Comment by jagajaga** [comment]
Can't you patch it to run absolute path?

**Comment by kamilchm** [comment]
I was wondering if this isn't something common with other python packages and perhaps there's already something in nix to do it better, like wrapPythonPrograms or smth..

**Comment by jagajaga** [comment]
cc @domenkozar

**Pull request closed without merging**
