### PR TITLE
Update Monero for upcoming hard fork

### LINKED ISSUE #48294: Upgrade xmr-stak to v2.5.0 urgent
## Issue description
Monero is hardforking and changing the proof of work. xmr-stak must be upgraded to v2.5.0 before the 18th of Oct (Thu), or it will stop working

Thanks @fpletz

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Motivation for this change
Fix #48294 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change
- [x] Tested compilation of all pkgs that depend on this change (none)
- [x] Tested execution of all binary files
- [ ] Determined the impact on package closure size
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

This should also be backported to stable.

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build monero-gui

**Comment by Mic92** [comment]
I think monero-gui also needs an update. It built before.

**Comment by fpletz** [comment]
There hasn't been a new release of monero-gui yet. I'll check if packaging a commit from master makes sense.

**Comment by rnhmjoj** [comment]
This happens everytime there is a hard fork: the gui needs monero core to build so it breaks when the daemon is updated.

**Comment by rnhmjoj** [comment]
The GUI has been updated!

**Comment by samueldr** [comment]
@GrahamcOfBorg build monero-gui

**Review by samueldr — APPROVED** [review]
It might be of interest to remove darwin and aarch64 from the non-building platforms, but that's not the point of this PR.

**Comment by samueldr** [comment]
Ugh... tried to backport and it looks like something broke; this is on current master:

```
 $ exec env -i NIXPKGS_ALLOW_UNFREE=1 nix-build -A monero-gui --max-jobs 1
these derivations will be built:
  /nix/store/g0l9rxznmiaiy3dwva9ha7690nh4sp1j-source.drv
  /nix/store/bd6ay96gkrbjk8ph51mg75icicy68wvj-monero-gui-0.13.0.2.drv
building '/nix/store/g0l9rxznmiaiy3dwva9ha7690nh4sp1j-source.drv'...

trying https://github.com/monero-project/monero-gui/archive/v0.13.0.2.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   136    0   136    0     0    635      0 --:--:-- --:--:-- --:--:--   632
100 2846k    0 2846k    0     0  1562k      0 --:--:--  0:00:01 --:--:-- 3764k
unpacking source archive /build/v0.13.0.2.tar.gz
fixed-output derivation produced path '/nix/store/f59rc7qmr2b1f1jyychwln3p4nw7lm1w-source' with sha256 hash '17b1ihq52rincix44ldj2k6dfy0qyf5007j32bwly3r1ik511yhx' instead of the expected hash '02419rqi3zfy6yjyw3b3gvkbxh2ypdfpijiiklc7lyblb9nnjr68'
cannot build derivation '/nix/store/bd6ay96gkrbjk8ph51mg75icicy68wvj-monero-gui-0.13.0.2.drv': 1 dependencies couldn't be built
error: build of '/nix/store/bd6ay96gkrbjk8ph51mg75icicy68wvj-monero-gui-0.13.0.2.drv' failed
Command exited with non-zero status 1

 → exit status: 1
```

Either: the hash wasn't right in this PR (but then what did ofborg build?) or upstream moved the tag (uuuuuuuuggghhhhhh). @rnhmjoj any ideas which of the two happened? Is the new hash expected? Did something happen to monero-gui (and would you know? are you following that project?)

(oh, and all negative feelings are towards the situation, not towards the people here.)

**Comment by rnhmjoj** [comment]
It really has changed: not sure what happened here. They released a new versione anyway so l'll update it.

**Comment by samueldr** [comment]
Touching a tag makes me sad :/. cc me in the new PR, I'll backport with the update. Thanks!

**Pull request merged**
