### PR TITLE
remind: ignore beta versions in updateScript

### PR DESCRIPTION
**Pull request by afh**
Add `ignoredVersions` to `gitUpdater` to only update to official releases and omit beta versions.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by 7c6f434c** [comment]
What's the point of `.*` at the end? If anything, I would add something at the beginning (to have `(-BETA[.])` or `[-]BETA[.]`) because the expressions is passed to grep as-is without `--` in front.

**Comment by afh** [comment]
The point of `.*` at the end is to ignore the beta version from remind beta tags (see [list of tags](https://salsa.debian.org/dskoll/remind/-/tags)).

A more precise regex would be `-BETA-[0-9]+`, but I didn't want to be too limiting. Happy to make the necessary adjustments if you think they are beneficial.

**Comment by 7c6f434c** [comment]
Look at how the expression is used in the script. It is a substring match, not a full-version match. And if it were a full-version match, you would need `.*` before the BETA too. 

What is worse, it is a parameter to `grep` passed in a way where `-` at the beginning may cause grep to misinterpret it as a bunch of flags.

**Comment by afh** [comment]
Thanks for the additional context, I'll have another and closer look

**Comment by afh** [comment]
Looking at [`generic-updater.nix`:59](https://github.com/NixOS/nixpkgs/blob/e83abe23cb19510523603f7609703037a484e444/pkgs/common-updater/generic-updater.nix#L59) I see that the `-q`, `-E`, and `-e` options are passed to grep.
According to `grep(1)` (I might be looking at the wrong one) the `-e` _"option can be used to protect a pattern beginning with “-”."_

From my possibly too simplistics tests (see below) the '-BETA.*` regular expression should work just fine.

```bash
% export tag=2.02.00-BETA-3
% grep -E -e '-BETA.*' <<< "$tag"
2.02.00-BETA-3
```

I ask further, because I'm interested in deepening my understanding of the generic updater 🙂

**Comment by 7c6f434c** [comment]
Ah that's good then.

Then you just don't need `.*` at the end because grep defaults to substring-match

**Comment by afh** [comment]
Thanks for the quick verification, @7c6f434c. I went ahead and removed the unnecessary `.*`.

**Comment by afh** [comment]
Thanks for merging this already, @7c6f434c. Let's see if the update picks up the [05.02.00 release](https://salsa.debian.org/dskoll/remind/-/tags/05.02.00) 🤞

**Comment by afh** [comment]
@7c6f434c I closed the [PR](https://github.com/NixOS/nixpkgs/pull/365476) from ryanbot that proposed to update remind to 05.02.00-BETA-3, since then this PR has been merged and remind 05.02.01 has been released.
Yet ryanbot has yet to issue another PR. A couple of question you or someone you know my help to answer:

Is there a need to trigger it manually? If yes, how?
Does it usually take a few days/weeks until ryanbot picks up new updates and I should see this as an opportunity to exercise my patience?🙂

**Comment by 7c6f434c** [comment]
It runs automatically within the allocated infrastructure amount. My initial estimate would be a day or too when everything is good, and a week when something breaks down and needs fixing (in a way not specific to a given package). I might be wrong.

**Comment by afh** [comment]
Thanks for the context, @7c6f434c, I'll keep an eye out for a bot remind PR in the coming days then.

**Pull request merged**
