### PR TITLE
python310Packages.treq: fix aarch64-darwin

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 172117` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages failed to build:</summary>
  <ul>
    <li>magic-wormhole (python39Packages.magic-wormhole)</li>
    <li>matrix-synapse</li>
    <li>matrix-synapse-plugins.matrix-synapse-mjolnir-antispam</li>
    <li>matrix-synapse-plugins.matrix-synapse-shared-secret-auth</li>
    <li>python310Packages.klein</li>
    <li>python310Packages.magic-wormhole</li>
    <li>python310Packages.magic-wormhole-mailbox-server</li>
    <li>python310Packages.treq</li>
    <li>python39Packages.klein</li>
    <li>python39Packages.magic-wormhole-mailbox-server</li>
    <li>python39Packages.treq</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
@siraben can you provide some logs? Ofborg is not building for aarch64.

**Comment by siraben** [comment]
```
❯ nix log /nix/store/cc1g26jj3wqynz51n7g6agv5vk09q7kz-python3.9-treq-22.2.0.drv | ix
http://ix.io/3Xni
```

**Comment by risicle** [comment]
```
error: builder for '/nix/store/86sm6jvvlvvfcja865fy91vgd6js167z-python3.9-treq-22.2.0.drv' failed with exit code 1;
       last 10 log lines:
       > Traceback (most recent call last):
       > Failure: twisted.trial.util.DirtyReactorAggregateError: Reactor was unclean.
       > Selectables:
       > <twisted.internet.process.ProcessReader object at 0x109c78a00>
       >
       > treq.test.test_treq_integration.HTTPSTreqIntegrationTests.test_cookie
       > -------------------------------------------------------------------------------
       > Ran 227 tests in 12.513s
       >
       > FAILED (errors=24, successes=204)
       For full logs, run 'nix log /nix/store/86sm6jvvlvvfcja865fy91vgd6js167z-python3.9-treq-22.2.0.drv'.
```

**Comment by risicle** [comment]
It gets juicier:

```
Traceback (most recent call last):
  File "/nix/store/b6p7rx3x8mgznmjwfp7qz101f0rvg4j3-python3.9-treq-22.2.0/lib/python3.9/site-packages/treq/test/test_api.py", line 122, in test_post_json_with_data
    treq.post(
  File "/nix/store/b6p7rx3x8mgznmjwfp7qz101f0rvg4j3-python3.9-treq-22.2.0/lib/python3.9/site-packages/treq/api.py", line 32, in post
    return _client(kwargs).post(url, data=data, _stacklevel=4, **kwargs)
  File "/nix/store/b6p7rx3x8mgznmjwfp7qz101f0rvg4j3-python3.9-treq-22.2.0/lib/python3.9/site-packages/treq/client.py", line 182, in post
    return self.request('POST', url, data=data, **kwargs)
  File "/nix/store/b6p7rx3x8mgznmjwfp7qz101f0rvg4j3-python3.9-treq-22.2.0/lib/python3.9/site-packages/treq/client.py", line 267, in request
    d = wrapped_agent.request(
  File "/nix/store/kvfl93xys8h8jyvkr1vnr511wjx2xhci-python3.9-Twisted-22.4.0/lib/python3.9/site-packages/twisted/web/client.py", line 1480, in request
    deferred = self._agent.request(method, uri, headers, bodyProducer)
  File "/nix/store/kvfl93xys8h8jyvkr1vnr511wjx2xhci-python3.9-Twisted-22.4.0/lib/python3.9/site-packages/twisted/web/client.py", line 1573, in request
    deferred = self._agent.request(method, uri, headers, bodyProducer)
  File "/nix/store/kvfl93xys8h8jyvkr1vnr511wjx2xhci-python3.9-Twisted-22.4.0/lib/python3.9/site-packages/twisted/web/client.py", line 1352, in request
    d = self._agent.request(method, uri, headers, bodyProducer)
  File "/nix/store/kvfl93xys8h8jyvkr1vnr511wjx2xhci-python3.9-Twisted-22.4.0/lib/python3.9/site-packages/twisted/web/client.py", line 1148, in request
    endpoint = self._getEndpoint(parsedURI)
  File "/nix/store/kvfl93xys8h8jyvkr1vnr511wjx2xhci-python3.9-Twisted-22.4.0/lib/python3.9/site-packages/twisted/web/client.py", line 1132, in _getEndpoint
    return self._endpointFactory.endpointForURI(uri)
  File "/nix/store/kvfl93xys8h8jyvkr1vnr511wjx2xhci-python3.9-Twisted-22.4.0/lib/python3.9/site-packages/twisted/web/client.py", line 1003, in endpointForURI
    connectionCreator = self._policyForHTTPS.creatorForNetloc(
  File "/nix/store/kvfl93xys8h8jyvkr1vnr511wjx2xhci-python3.9-Twisted-22.4.0/lib/python3.9/site-packages/twisted/web/client.py", line 359, in creatorForNetloc
    return optionsForClientTLS(hostname.decode("ascii"), trustRoot=self._trustRoot)
  File "/nix/store/kvfl93xys8h8jyvkr1vnr511wjx2xhci-python3.9-Twisted-22.4.0/lib/python3.9/site-packages/twisted/internet/_sslverify.py", line 1258, in optionsForClientTLS
    return ClientTLSOptions(hostname, certificateOptions.getContext())
  File "/nix/store/kvfl93xys8h8jyvkr1vnr511wjx2xhci-python3.9-Twisted-22.4.0/lib/python3.9/site-packages/twisted/internet/_sslverify.py", line 1632, in getContext
    self._context = self._makeContext()
  File "/nix/store/kvfl93xys8h8jyvkr1vnr511wjx2xhci-python3.9-Twisted-22.4.0/lib/python3.9/site-packages/twisted/internet/_sslverify.py", line 1663, in _makeContext
    ctx.set_verify(verifyFlags, _verifyCallback)
  File "/nix/store/ca7yzmhwyy8srbfcblharn1ay205x4dl-python3.9-pyopenssl-22.0.0/lib/python3.9/site-packages/OpenSSL/SSL.py", line 1128, in set_verify
    self._verify_helper = _VerifyHelper(callback)
  File "/nix/store/ca7yzmhwyy8srbfcblharn1ay205x4dl-python3.9-pyopenssl-22.0.0/lib/python3.9/site-packages/OpenSSL/SSL.py", line 359, in __init__
    self.callback = _ffi.callback(
builtins.MemoryError: Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this. For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks
```

**Comment by risicle** [comment]
And all comes full circle back to https://github.com/pyca/pyopenssl/issues/873

**Comment by SuperSandro2000** [comment]
> And all comes full circle back to [pyca/pyopenssl#873](https://github.com/pyca/pyopenssl/issues/873)

Based on the last comments in the thread:
- We could disable pyopenssl for aarch64-darwin
- We could disable pyopenssl for aarch64-darwin on python 3.9 only

**Comment by risicle** [comment]
I experience the issue for both python 3.9 & 3.10

**Comment by SuperSandro2000** [comment]
Then I disable it for aarch64-darwin for now until someone (that is not me) fixes it.

**Comment by SuperSandro2000** [comment]
I opened #172397 which makes this PR redundant.

**Pull request closed without merging**
