### PR TITLE
Avoid package attributes starting with a digit 

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Motivation for this change
See the release notes.

###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS)
- [x] Built NixOS manual
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
I like the intention, but don't like the `_`. Just a $0.02.

**Comment by rnhmjoj** [comment]
What do you propose? I went with an underscore because there are already two packages doing this in nixpkgs.

**Comment by Mic92** [comment]
Please also add renamed packages to `pkgs/top-level/aliases.nix`

**Comment by vcunat** [comment]
I wonder what's the precedent, in major packaging systems.  Have you looked?

Nitpick: you forgot `2048-in-terminal`.

**Comment by rnhmjoj** [comment]
> I wonder what's the precedent, in major packaging systems. Have you looked?
Not yet, I will research a bit.

> Nitpick: you forgot 2048-in-terminal.
Ah, right. I forgot to link it: 2048-in-terminal is addressed in https://github.com/NixOS/nixpkgs/pull/33846

**Comment by orivej** [comment]
Other package managers do not avoid names starting with digits:
- http://gpo.zugaina.org/net-nds/389-ds-base
- https://aur.archlinux.org/packages/389-ds-base/

It seems that this issue is better addressed in Nix rather than in Nixpkgs: `[ 2bwm ]` should not be parsed as `[ 2 bwm ]`.

**Comment by vcunat** [comment]
Hmm, changing nix for this is an interesting option.  Still, my eye might tend to parse "389-ds" as subtraction...

**Comment by orivej** [comment]
The eye will adjust. Nix supports `-` in attribute names, and I don't think that `a-4-b` (an ID) should be parsed differently from `4-a-b` (currently a subtraction of `a-b` from 4).

**Comment by vcunat** [comment]
It would be quite an incompatible change.  When I remember how the ["x:x" change](https://github.com/NixOS/nix/issues/836) goes...

**Comment by orivej** [comment]
I have checked that modifying the lexer to support IDs starting with an integer (and prioritizing INTs to IDs to disambiguate) does not affect parsing of any `.nix` file in Nixpkgs `master`. I am going to make a PR with this change (after adding tests). WRT this PR, I'd prefer that names in `all-packages.nix` continue to begin with digits; underscored aliases may be added to `aliases.nix`.

In https://github.com/NixOS/nixpkgs/commit/0b167040006f97e56eac60864112f46804e4f2de#r14008920 @edolstra said:

> Please don't start package names with a digit. It confuses nix-env and requires quoting of attributes.

But e.g. `nix-env -iA 2048-in-terminal` works, and the proposed change will obsolete quoting.

**Comment by rnhmjoj** [comment]
@orivej I didn't consider changing Nix syntax. I'm not sure about it though.

**Comment by dtzWill** [comment]
(however this gets resolved, please include 2048-in-terminal here as well, since it should be handled the same as others in this PR.  Thanks!)

**Pull request merged**
