### PR TITLE
itch: 25.6.2 -> 26.1.2

### LINKED ISSUE #220844: itch: error: Package ‘electron-11.5.0’ is marked as insecure, refusing to evaluate.
### Describe the bug

I can't update my system when itch should be installed:

>error: Package ‘electron-11.5.0’ in /nix/store/5wja3wj4lq4gijjgg2lx3966pf6lzijc-nixos-22.11/nixos/pkgs/development/tools/electron/generic.nix:27 is marked as insecure, refusing to evaluate.

### Steps To Reproduce
1. have `itch` in 
2. `nixos-rebuild switch`

### Expected behavior
no error

### Additional context

also reproducible on unstable

i guess electron needs an update

or use a later electron version, if possible

### Notify maintainers

@pasqui23

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.0, NixOS, 22.11 (Raccoon), 22.11.2999.a7cc81913bb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### LINKED ISSUE #252457: Build failure: itch
### Steps To Reproduce

1. build *itch*

### Build log

```
error: Package ‘electron-11.5.0’ in /nix/store/64s7nc8hrzifkg5861rggklz1cld16h3-nixos-23.05/nixos/pkgs/development/tools/electron/binary/generic.nix:27 is marked as insecure, refusing to evaluate.


       Known issues:
        - Electron version 11.5.0 is EOL

       You can install it anyway by allowing this package, using the
       following methods:

       a) To temporarily allow all insecure packages, you can use an environment
          variable for a single invocation of the nix tools:

            $ export NIXPKGS_ALLOW_INSECURE=1

        Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
        (Flake) command, `--impure` must be passed in order to read this
        environment variable.

       b) for `nixos-rebuild` you can add ‘electron-11.5.0’ to
          `nixpkgs.config.permittedInsecurePackages` in the configuration.nix,
          like so:

            {
              nixpkgs.config.permittedInsecurePackages = [
                "electron-11.5.0"
              ];
            }

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
          ‘electron-11.5.0’ to `permittedInsecurePackages` in
          ~/.config/nixpkgs/config.nix, like so:

            {
              permittedInsecurePackages = [
                "electron-11.5.0"
              ];
            }
(use '--show-trace' to show detailed location information)
```

### Notify maintainers

@pasqui23 

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.46, NixOS, 23.05 (Stoat), 23.05.2975.a16f7eb56e88`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `"nixos-23.05"`
 - channels(username): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### PR DESCRIPTION
**Pull request by SuperSamus**
## Description of changes

While this new version is still a beta (some of the icons will be blue), the Electron version is not insecure anymore, with the number literally doubled (from 11 to 22).
Closes #220844 for real.
Closes #252457.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 248321` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>itch</li>
  </ul>
</details>

**Comment by davidak** [comment]
The beta/development/canary version is using a different namespace, so it does not use the existing data (login, installed games).

stable: `/home/davidak/.config/itch/`
canary: `/home/davidak/.config/kitch/`

That is by design: https://github.com/itchio/itch/issues/1906

So it might be better to create a new package for the canary version to not confuse users.

AUR calls it [kitch](https://aur.archlinux.org/packages/kitch), which seem to be the official name: https://itchio.itch.io/kitch

**Comment by SuperSamus** [comment]
The idea of having both itch and kitch in nixpkgs doesn't convince me...
Maybe it's better to close this and wait for the stable release?

**Comment by davidak** [comment]
>The idea of having both itch and kitch in nixpkgs doesn't convince me...

We have beta versions for other packages, like browsers. But it's an additional package for a different audience. If they offer it to users, why not package it?

>Maybe it's better to close this and wait for the stable release?

This package has to be updated to the next stable version to keep working as the user expects.

**Comment by pasqui23** [comment]
I am trying to build it but `itch-setup` fails with the followig error:

```warning: binary cache 'http://127.0.0.1:12304' is for Nix stores with prefix 'Nix::Store::getStoreDir', not '/nix/store'
error: builder for '/nix/store/1f6r4kk0zpv1p1xj7ps7z63hrwvk7i23-source.drv' failed with exit code 1;
       last 7 log lines:
       >
       > trying https://broth.itch.ovh/kkitch/linux-amd64/26.1.2/archive/default#.zip
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       >   0    37    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
       > curl: (22) The requested URL returned error: 404
       > error: cannot download source from any mirror
       For full logs, run 'nix log /nix/store/1f6r4kk0zpv1p1xj7ps7z63hrwvk7i23-source.drv'.
error: 1 dependencies of derivation '/nix/store/xngr2cvq7x6k24gb3mblap1007rxzczb-kitch-26.1.2.drv' failed to build
```

**Comment by SuperSamus** [comment]
Reopening because Itch is now not working at all. With this, it works again.
I added a small modification so that the application still thinks it's Itch (instead of Kitch).
Tested both a Linux game (Baba is You) and a Windows game (Super Hexagon).

**Comment by SuperSamus** [comment]
Anything missing for this to be merged?

**Pull request merged**
