### PR TITLE
xivlauncher: 1.0.3 -> 1.0.4

### PR DESCRIPTION
**Pull request by witchof0x20**
###### Description of changes

Updates xivlauncher to 1.0.4

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by witchof0x20** [comment]
Changelog notes from upstream in case this causes a regression for someone and they want to refer back to this PR.
-     Updated bundled wine version to wine-xiv-git to 8.5.r4
-     Updated Mac FMV URL (this should fix some issues on new UNIX installs)
-     Updated parts of the interface to be more uniform
-     Added troubleshooting tab for common operations & fixes
-     Added the option to launch without 3rd-party plugins
-     Improved "IsIgnoringSteam" behaviour on steam deck


⚠️ Notice for Linux Users
This update is being gradually rolled out - the official flatpak release will be the first to recieve the update and is the best way to use XIVLauncher.Core on Linux. If you have installed the launcher from another package manager, you will have to wait for the maintainer to update the package themselves. @linux maintainers 

❗ Known Issue
In our efforts to update the build of Wine to something more recent, we have seen an issue with certain plugins that rely on WebSockets. (GoodFriend, ExtraChat, etc). Wine 8.1 and newer default the Windows Version set in Wine to Windows 10, which can break this functionality as it's not correctly implemented in Wine. 

If you're encountering network issues related to your plugins, you can set the winver back to Windows 7 from XIVLauncher's Wine settings tab by clicking the Wine Configuration box. Our next release will put the default back to Windows 7 unless we can sort out why this is happening and get it fixed in Wine.

**Comment by sersorrel** [comment]
Result of `nixpkgs-review pr 238612` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>xivlauncher</li>
  </ul>
</details>

It builds and launches, but when I try to launch the game I get some logspam and no game:

```
wine: could not load ntdll.so: libunwind.so.8: cannot open shared object file: No such file or directory
```

Adding `libunwind` to buildInputs doesn't help...

I feel like I ran into something like this before but I don't remember any of the details.

**Comment by witchof0x20** [comment]
So the game does run for me, but I have seen this issue before when using the new wine. I'll add in the fix I use in my local config.

**Comment by witchof0x20** [comment]
Actually, hmm. 
```
      channels.unstable.xivlauncher.override
        {
          steam-run = (channels.unstable.steam.override
            {
              extraPkgs = pkgs: [ pkgs.gamemode.lib pkgs.libunwind ];
            }
          ).run;
        }
```
is what I use.

**Comment by witchof0x20** [comment]
Pushed up my fix, it feels a bit hacky, but it does fix the libunwind issue.

**Comment by witchof0x20** [comment]
Nevermind I failed to check it. Working on it....

**Comment by witchof0x20** [comment]
Okay, full tests done with this push
```
rm -r ~/.xlcore/wineprefix
rm -r ~/.xlcore/compatibilitytool/beta
NIXPKGS_ALLOW_UNFREE=1 nix run --impure .#xivlauncher
```

**Comment by sersorrel** [comment]
seems good now!

**Review by keysmashes — APPROVED** [review]

**Comment by sersorrel** [comment]
on further testing, something seems not entirely happy (symptoms: not able to type in Wotsit):

image

but I _think_ this is related to chatter I saw in discord over the last couple of days, and opening winecfg and changing the emulated Windows version to Windows 7 (from Windows 10) seems to have fixed it, so I think this is not a packaging problem.

**Review by keysmashes — APPROVED** [review]
i already reviewed this ofborg

**Pull request merged**
