### PR TITLE
lazygit: 0.40.0 -> 0.40.2

### PR DESCRIPTION
**Pull request by khaneliman**
## Description of changes
Upgrade lazygit to resolve bug on current version
Also Related PR: https://github.com/NixOS/nixpkgs/pull/246386

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by paveloom — APPROVED** [review]
Beat me by a couple of minutes: https://github.com/NixOS/nixpkgs/pull/247747.

**Comment by khaneliman** [comment]
> Beat me by a couple of minutes: #247747.

Was having issues with lazygit last couple days and thought i broke something in my config but then saw the release notes about bugs since new 4.0 release. Use it so often just wanted to get it updated haha

**Review by booniepepper — APPROVED** [review]

**Comment by pbsds** [comment]
Result of `nixpkgs-review pr 247746` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>lazygit</li>
  </ul>
</details>

**Review by pbsds — APPROVED** [review]

**Review by eclairevoyant — COMMENTED** [review]
any reason to not add `meta.mainProgram`?

**Comment by khaneliman** [comment]
> any reason to not add `meta.mainProgram`?

Nah, do you want to add it ? Otherwise I can do it when I get home tonight.

**Comment by pbsds** [comment]
> any reason to not add `meta.mainProgram`?

It defaults to `pname`

**Comment by eclairevoyant** [comment]
> > any reason to not add `meta.mainProgram`?
> 
> It defaults to `pname`

I guess you missed the news? #246386

**Comment by khaneliman** [comment]
@eclairevoyant Alright, updated with the mainProgram commit.

**Review by eclairevoyant — APPROVED** [review]

**Pull request merged**
