### PR TITLE
Crossfixes

### PR DESCRIPTION
**Pull request by Artturin**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by jtojnar — APPROVED** [review]

**Comment by Artturin** [comment]
@jtojnar fyi `glib-networking.tests.installedTests` fails but its caused by this PR

```
vm-test-run-glib-networking> Running test: glib-networking/certificate-gnutls.test
vm-test-run-glib-networking> # random seed: R02S2c03f7a14171b1db2a5d1bbfd08e9bf8
vm-test-run-glib-networking> # GLib-GIO-DEBUG: _g_io_module_get_default: Found default implementation gnutls (GTlsBackendGnutls) for ?gio-tls-backend?
vm-test-run-glib-networking> Bail out! GLib-Net:ERROR:../tls/tests/certificate.c:929:main: assertion failed: (gnutls_pkcs11_add_provider (module_path, NULL) == GNUTLS_E_SUCCESS)
vm-test-run-glib-networking> FAIL: glib-networking/certificate-gnutls.test (Child process killed by signal 6)
vm-test-run-glib-networking> Running test: glib-networking/environment-libproxy.test
vm-test-run-glib-networking> Executing: glib-networking/environment-libproxy.test
vm-test-run-glib-networking> # random seed: R02Seca6cdf72cd2209ad0f65bda86fef497
vm-test-run-glib-networking> 1..3
vm-test-run-glib-networking> # Start of proxy tests
vm-test-run-glib-networking> # Start of environment tests
vm-test-run-glib-networking> ok 1 /proxy/environment/uri
vm-test-run-glib-networking> ok 2 /proxy/environment/socks
vm-test-run-glib-networking> ok 3 /proxy/environment/ignore
vm-test-run-glib-networking> # End of environment tests
vm-test-run-glib-networking> # End of proxy tests
vm-test-run-glib-networking> PASS: glib-networking/environment-libproxy.test
vm-test-run-glib-networking> SUMMARY: total=6; passed=4; skipped=0; failed=2; user=2.0s; system=0.7s; maxrss=41152
vm-test-run-glib-networking> FAIL: glib-networking/connection-gnutls.test (Child process killed by signal 6)
vm-test-run-glib-networking> FAIL: glib-networking/certificate-gnutls.test (Child process killed by signal 6)
vm-test-run-glib-networking> cleanup
vm-test-run-glib-networking> kill machine (pid 8)
vm-test-run-glib-networking> machine # qemu-kvm: terminating on signal 15 from pid 6 (/nix/store/xcaaly5shfy227ffs8nipxrd49b56iqq-python3-3.10.8/bin/python3.10)
vm-test-run-glib-networking> (finished: cleanup, in 0.21 seconds)
vm-test-run-glib-networking> Traceback (most recent call last):
vm-test-run-glib-networking>   File "/nix/store/wmimjvsw82dj7mj5vrvqsz3wyc7zgjyq-nixos-test-driver-1.1/bin/.nixos-test-driver-wrapped", line 9, in <module>
vm-test-run-glib-networking>     sys.exit(main())
vm-test-run-glib-networking>   File "/nix/store/wmimjvsw82dj7mj5vrvqsz3wyc7zgjyq-nixos-test-driver-1.1/lib/python3.10/site-packages/test_driver/__init__.py", line 114, in main
vm-test-run-glib-networking>     driver.run_tests()
vm-test-run-glib-networking>   File "/nix/store/wmimjvsw82dj7mj5vrvqsz3wyc7zgjyq-nixos-test-driver-1.1/lib/python3.10/site-packages/test_driver/driver.py", line 146, in run_tests
vm-test-run-glib-networking>     self.test_script()
vm-test-run-glib-networking>   File "/nix/store/wmimjvsw82dj7mj5vrvqsz3wyc7zgjyq-nixos-test-driver-1.1/lib/python3.10/site-packages/test_driver/driver.py", line 142, in test_script
vm-test-run-glib-networking>     exec(self.tests, symbols, None)
vm-test-run-glib-networking>   File "<string>", line 1, in <module>
vm-test-run-glib-networking>   File "/nix/store/wmimjvsw82dj7mj5vrvqsz3wyc7zgjyq-nixos-test-driver-1.1/lib/python3.10/site-packages/test_driver/machine.py", line 600, in succeed
vm-test-run-glib-networking>     raise Exception(
vm-test-run-glib-networking> Exception: command `gnome-desktop-testing-runner  -d '/nix/store/jxvx7z8haw58hff2dwlvz31kam5yxc8l-glib-networking-2.74.0-installedTests/share'` failed (exit code 2)
```

**Comment by Mindavi** [comment]
Thanks for fixing!

**Comment by jtojnar** [comment]
I think you meant to say it is **not** caused by this PR – I see the following on nixos-unstable:

```
SUMMARY: total=6; passed=4; skipped=0; failed=2; user=0.3s; system=0.2s; maxrss=41252
FAIL: glib-networking/connection-gnutls.test (Child process killed by signal 6)
FAIL: glib-networking/certificate-gnutls.test (Child process killed by signal 6)
```

**Comment by Artturin** [comment]
> I think you meant to say it is **not** caused by this PR – I see the following on nixos-unstable:
> 
> ```
> SUMMARY: total=6; passed=4; skipped=0; failed=2; user=0.3s; system=0.2s; maxrss=41252
> FAIL: glib-networking/connection-gnutls.test (Child process killed by signal 6)
> FAIL: glib-networking/certificate-gnutls.test (Child process killed by signal 6)
> ```

Yeah that's what I meant to say

**Pull request merged**
