### PR TITLE
vinegar: 1.7.3 -> 1.7.4

### PR DESCRIPTION
**Pull request by ardishko**
## Description of changes

Updated vinegar from 1.7.3 to 1.7.4.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jnsgruk** [comment]
Result of `nixpkgs-review pr 291815` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>vinegar</li>
  </ul>
</details>

**Comment by jnsgruk** [comment]
Hi, thanks for this! Looks like the build isn't quite working correctly. One of the patches being carried now fails to apply. Are you able to investigate? Let me know if you need a hand.

```
include/wine/server_protocol.h updated
include/wine/server_protocol.h updated
server/trace.c updated
server/request.h updated
applying patch /nix/store/p2qhadv6sgc1dk60wqxnnnrpsh25ci1l-cert-path.patch
patching file dlls/crypt32/unixlib.c
Hunk #1 succeeded at 660 (offset 6 lines).
applying patch /nix/store/mhdh3kzkmsldjj1l8si043y83dqlx956-vinegar-wine-segregrevert.patch
patching file dlls/ntdll/signal_x86_64.c
Hunk #1 FAILED at 559.
1 out of 1 hunk FAILED -- saving rejects to file dlls/ntdll/signal_x86_64.c.rej
patching file dlls/ntdll/tests/exception.c
Hunk #1 succeeded at 1810 (offset -15 lines).
Hunk #2 FAILED at 3278.
Hunk #3 FAILED at 3618.
Hunk #4 FAILED at 3639.
Hunk #5 succeeded at 3800 (offset -603 lines).
3 out of 5 hunks FAILED -- saving rejects to file dlls/ntdll/tests/exception.c.rej
patching file dlls/ntdll/unix/signal_x86_64.c
Hunk #1 succeeded at 423 with fuzz 2 (offset 10 lines).
Hunk #2 succeeded at 827 (offset 14 lines).
Hunk #3 succeeded at 866 (offset 14 lines).
Hunk #4 succeeded at 898 (offset 14 lines).
Hunk #5 succeeded at 1072 (offset 15 lines).
Hunk #6 succeeded at 1143 (offset 10 lines).
Hunk #7 succeeded at 1376 (offset 6 lines).
Hunk #8 succeeded at 2793 (offset 245 lines).
Hunk #9 succeeded at 2813 with fuzz 1 (offset 247 lines).
```

**Comment by sochotnicky** [comment]
For what it's worth I have the same patching errors when trying to build the previous PR in https://github.com/NixOS/nixpkgs/pull/289265

so I don't think it's necessarily this PR that's buggy.

**Comment by Scrumplex** [comment]
Result of `nixpkgs-review pr 291815` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>vinegar</li>
  </ul>
</details>

**Comment by Scrumplex** [comment]
It seems like the patches done to wine-staging do not apply anymore. Perhaps we want to pin wine to a certain version or update the patches ourselves?

**Comment by raidenovich** [comment]
Oh, I completely forgot about this PR. I have another one up that pins the WINE version and applies all of the patches.

up to date PR: https://github.com/NixOS/nixpkgs/pull/305099

**Pull request closed without merging**
