### PR TITLE
libcxx[abi]: use clang-override stdenv to build

### PR DESCRIPTION
**Pull request by gridaphobe**
This fixes the error described by #6934.

Pinging @shlevy before committing upstream because I don't see why this would fix anything...

### CODE REVIEW

**Comment by tel** [comment]
+1

**Comment by gridaphobe** [comment]
Hrm, based on https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/cc-wrapper/default.nix#L172-L176 it seems that the choice to use the regular stdenv for libcxx[abi] was quite deliberate.

**Comment by shlevy** [comment]
Will review this later today or tomorrow morning at latest.

**Comment by edolstra** [comment]
This fixes the problem for me, but I can't judge the correctness.

**Comment by gridaphobe** [comment]
@edolstra IIUC this will force building `libcxx[abi]` with the default cc instead of the newly-built clang. I think this is fine though, http://libcxx.llvm.org/ suggests that `libcxx` can be built by clang or gcc, and testing on my nixos server confirms.

**Comment by edolstra** [comment]
Do you know why cmake barfs with the newly-built clang?

**Comment by gridaphobe** [comment]
The stdenv in llvmPackages is somehow incomplete, it lacks `make` and `install_name_tool`, and probably other things too. I have no clue why that is though..

**Comment by aflatter** [comment]
This PR solves the problem for me. Thanks!

**Comment by shlevy** [comment]
The problem is with `wrapCC`, working on a proper fix

**Comment by shlevy** [comment]
@gridaphobe or others: Can you please test https://github.com/shlevy/nixpkgs/commit/6bb25568a938fae53bf26eb8d3da824de34d1213? I'm not at a computer that can do so in a reasonable amount of time and the network I'm on blocks ssh :angry:

**Comment by edolstra** [comment]
@shlevy With your change I still get the same cmake error in libc++abi.

**Comment by shlevy** [comment]
@edolstra https://github.com/NixOS/nixpkgs/issues/6934#issue-63542833 <- is that log representative?

**Comment by edolstra** [comment]
It's slightly different:
```
nix-build -A stdenv
these derivations will be built:
  /nix/store/jgcpz1n5c9zvl72504w1v3hn40505r58-libc++abi-3.6.0.drv
  /nix/store/r0flzl29lzx421yqh067hyikqvd97acq-libc++-3.6.0.drv
  /nix/store/z71pw1gv9c91kk5mgl476bgb9d94mxx1-cctools-port-862.drv
  /nix/store/ag07q8vvmgzfs3135z9r2kb3j32g2zx3-clang-wrapper-wrapper-3.6.0.drv
  /nix/store/yqaaxcjhcg7wfsraflz4n0byali1avrd-stdenv-darwin-boot-3.drv
building path(s) ‘/nix/store/r1k8bzljcpfk9af6v7wmhw1s8h972xjq-libc++abi-3.6.0’
unpacking sources
unpacking source archive /nix/store/ay21kc17akv991dsaac0i5j0jpvlc522-libcxxabi-3.6.0.src.tar.xz
source root is libcxxabi-3.6.0.src
unpacking source archive /nix/store/4cvrfp8dcqfcqk3w7nkxpbbw0r735yv0-libcxx-3.6.0.src.tar.xz
unpacking source archive /nix/store/kpka13b52vj6kcnwnq5dcglr874cff0g-llvm-3.6.0.src.tar.xz
patching sources
configuring
fixing cmake files...
cmake flags: -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_BUILD_RPATH=ON -DCMAKE_INSTALL_PREFIX=/nix/store/r1k8bzljcpfk9af6v7wmhw1s8h972xjq-libc++abi-3.6.0 -DLLVM_PATH=/private/tmp/nix-build-libc++abi-3.6.0.drv-6/llvm-3.6.0.src -DLIBCXXABI_LIBCXX_INCLUDES=/private/tmp/nix-build-libc++abi-3.6.0.drv-6/libcxx-3.6.0.src/include 
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_C_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_C_COMPILER
CMake Error: Could not find cmake module file: /tmp/nix-build-libc++abi-3.6.0.drv-6/libcxxabi-3.6.0.src/build/CMakeFiles/3.2.1/CMakeCCompiler.cmake
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_CXX_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_CXX_COMPILER
CMake Error: Could not find cmake module file: /tmp/nix-build-libc++abi-3.6.0.drv-6/libcxxabi-3.6.0.src/build/CMakeFiles/3.2.1/CMakeCXXCompiler.cmake
CMake Error at CMakeLists.txt:8 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting the CMake cache entry
  CMAKE_C_COMPILER to the full path to the compiler, or to the compiler name
  if it is in the PATH.


CMake Error at CMakeLists.txt:8 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting the CMake cache entry
  CMAKE_CXX_COMPILER to the full path to the compiler, or to the compiler
  name if it is in the PATH.


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
builder for ‘/nix/store/jgcpz1n5c9zvl72504w1v3hn40505r58-libc++abi-3.6.0.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/z71pw1gv9c91kk5mgl476bgb9d94mxx1-cctools-port-862.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/r0flzl29lzx421yqh067hyikqvd97acq-libc++-3.6.0.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/ag07q8vvmgzfs3135z9r2kb3j32g2zx3-clang-wrapper-wrapper-3.6.0.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/yqaaxcjhcg7wfsraflz4n0byali1avrd-stdenv-darwin-boot-3.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/yqaaxcjhcg7wfsraflz4n0byali1avrd-stdenv-darwin-boot-3.drv’ failed
```

**Comment by shlevy** [comment]
Damn, going to be on the road all day and won't be able to look into this in detail again until tomorrow. @edolstra Any obvious reason why the overridden stdenv shouldn't be able to find make/cc?

**Comment by shlevy** [comment]
Rough guess that I can't test yet: the combination of clang with purity patches + nativeTools = true is the problem here.

**Comment by shlevy** [comment]
Probably the proper solution is to fix wrapCC then. I'll poke around tomorrow.

**Comment by gridaphobe** [comment]
@shlevy I think I've found the root of the issue, which is that our `stage1.cc` is our only reference to apple's cli-tools. Thus, when overrideCC replaces `stage1.cc` with `clang`, we lose all of the apple cli-tools that we need to finish building the stdenv.

Adding the cli-tools to the `initialPath` ought to resolve everything properly, testing now.

**Comment by shlevy** [comment]
@gridaphobe Ah, good catch!

**Comment by gridaphobe** [comment]
Fixed more properly in 7f5367c69df3095eb3890bb116092486b099e7c6. I skipped staging since master was completely broken on darwin anyway.

**Pull request closed without merging**
