### PR TITLE
graph-tool: 2.12 -> 2.16

### PR DESCRIPTION
**Pull request by count0**

### CODE REVIEW

**Comment by FRidh** [comment]
According to the log the hash you gave is wrong.

**Comment by joelmo** [comment]
The sha256 attribute is a sha256 string base encoded. You can use nix-prefetch-url to get the hash or use the build log. Tested at this end, I get this hash: `03b1pmh2gvsgyq491gvskx8fwgqy9k942faymdnhwpbbbfhx911p`.

**Comment by count0** [comment]
@joelmo I used the `sha256sum` command line program, which gives an hex hash. The checks don't seem to complain now.

**Comment by joelmo** [comment]
Each commit is tested individually, `graph-tool: Use correct upstream source` passes but `graph-tool: 2.12 -> 2.16` is where you need to change the sha256 attribute.

**Comment by count0** [comment]
The test timed out, but otherwise things seem fine.

**Comment by FRidh** [comment]
can you squash the commits

**Pull request merged**
