### PR TITLE
maintainers: add atila

### PR DESCRIPTION
**Pull request by AtilaSaraiva**
###### Motivation for this change
I want to help writing derivations for some packages not preset yet in the nixpkgs repo.

###### Things done
Added myseld to the maintainers list.

### CODE REVIEW

**Comment by AtilaSaraiva** [comment]
Fixed the error reported by ofborg.

**Comment by ius** [comment]
The list is ~mostly alphabetically sorted. Consider inserting yourself at the right location?

**Comment by AtilaSaraiva** [comment]
Thx for the review! Done.

**Comment by AtilaSaraiva** [comment]
I will put my addition inside another PR.

**Pull request closed without merging**
