### PR TITLE
openvscode-server: 1.69.2 -> 1.73.1

### PR DESCRIPTION
**Pull request by shadaj**
###### Description of changes

Update to latest VS Code upstream

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dguenther** [comment]
Thanks for the update! Tested this on x86_64-darwin running macOS 13.0.1 by running `nix-build ../nixpkgs -A openvscode-server --pure`. I received the following error:

```
npm ERR! gyp http GET https://nodejs.org/download/release/v16.18.1/node-v16.18.1-headers.tar.gz
npm ERR! gyp WARN install got an error, rolling back install
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
npm ERR! gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad 
npm ERR! gyp ERR! stack network settings.
```

Which seems to manifest as a result of trying to download node headers, which it shouldn't be doing. I was able to fix the issue with the following patch:

```diff
diff --git a/pkgs/servers/openvscode-server/default.nix b/pkgs/servers/openvscode-server/default.nix
index 11bd2b638f3..e4f558c790b 100644
--- a/pkgs/servers/openvscode-server/default.nix
+++ b/pkgs/servers/openvscode-server/default.nix
@@ -59,13 +59,6 @@ in stdenv.mkDerivation rec {
     outputHash = "sha256-7UBXigQj7c+fuHPIM5BbRe02DuL+cs6VbQ/D84Yk8i4=";
   };
 
-  # Extract the Node.js source code which is used to compile packages with
-  # native bindings
-  nodeSources = runCommand "node-sources" {} ''
-    tar --no-same-owner --no-same-permissions -xf ${nodejs.src}
-    mv node-* $out
-  '';
-
   nativeBuildInputs = [
     nodejs yarn' python3 pkg-config makeWrapper git jq moreutils
   ];
@@ -102,9 +95,9 @@ in stdenv.mkDerivation rec {
 
     # set offline mirror to yarn cache we created in previous steps
     yarn --offline config set yarn-offline-mirror "${yarnCache}"
-  '' + lib.optionalString stdenv.isLinux ''
+
     # set nodedir, so we can build binaries later
-    npm config set nodedir "${nodeSources}"
+    npm config set nodedir "${nodejs}"
   '';
 
   buildPhase = ''
```

And tested starting openvscode-server and installing the rust-analyzer plugin to make sure it works. Since it passes the ofborg tests, I think it'd be okay to merge this, but it'd be nice to apply the above patch and retest on x86_64-linux at some point.

**Comment by shadaj** [comment]
@dguenther hmm, this is strange; I'd expect the `remove-node-download.patch` to have made sure that there is no Node download.

Also, the patch you made shouldn't have affected `x86_64-darwin`, right? Since the `nodedir` is only configured on Linux. So I think something a bit stranger might be going on, especially since things do seem to be building in CI.

**Comment by dguenther** [comment]
The `remove-node-download.patch` file skips the download of the Node executable that's packaged with the transpiled output -- this issue stems from `node-gyp` downloading Node headers for the purpose of compiling native code.

The patch in my comment directs node-gyp to the location of the headers on Mac as well as Linux. I suspect this issue is related, since it did work at some point: https://github.com/NixOS/nixpkgs/issues/195404

I'm also not certain whether OfBorg builds with `--pure`, without which the CI should build. Regardless, I'll leave an approve on this since I don't think it should be related to the version bump.

**Review by dguenther — APPROVED** [review]

**Comment by shadaj** [comment]
Ooh that makes sense, misread your patch. I'll update to include it shortly!

**Comment by shadaj** [comment]
@dguenther integrated your patch!

**Review by dguenther — APPROVED** [review]
Nice, thanks!

**Pull request merged**
