### PR TITLE
[19.09] firefox: 71.0 -> 72.0

### PR DESCRIPTION
**Pull request by andir**
###### Motivation for this change

This bumps firefox 71.0 to 72.0. It also removes the patch @fpletz added with 71.0 with the upstream version of that patch that supposedly fixes more issue with e.g. riot.im. 

Call for testers: @maralorn @fpletz

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [X] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by andir** [comment]
I am kinda unhappy about the use of `dontFixLibtool` here... I think it would be better to fixup the cargo hashsum check by putting back the unmodified file.

**Comment by taku0** [comment]
Also `firefox-esr` should be updated (`68.3.0esr` -> `68.4.0esr`).

**Comment by maralorn** [comment]
I have compiled this (e.g. firefox 72) successfully and tried it out it bit. I don‘t see any problems. riot.im works.

**Comment by andir** [comment]
Added the `-esr-68` update as well build is still running against this branch.

**Pull request merged**
