### PR TITLE
flacon: 2.0.1 -> 2.1.1

### PR DESCRIPTION
**Pull request by ndowens**
###### Motivation for this change
Update

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
Flacon segfaults on my machine, when trying to open a file (File -> Add File)

```
$ flacon
** (flacon:32274): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
(flacon:32274): GLib-GIO-ERROR **: No GSettings schemas are installed on the system
Trace/breakpoint trap
```

**Review by matthiasbeyer — APPROVED** [review]

**Comment by ndowens** [comment]
@Mic92 weird, i just went to file, add file and it didnt crash on me at all

**Comment by Mic92** [comment]
Probably some environment variable is not set to make `Gsettings` working correctly while you are using a Desktop environment such as Gnome.

**Comment by ndowens** [comment]
Hmm dunno I use awesome. So I don't have gnome installed at all

**Comment by ndowens** [comment]
@Mic92 I added gsettings schemes; I got that inital error on startup but adding a file didn't cause a segfault for me, so maybe this will fix it

**Comment by Mic92** [comment]
I had to point XDG_DATA_DIRS to gtk3 to make it working.

**Pull request closed without merging**
