### PR TITLE
vscode: 1.30.2 -> 1.31.0

### PR DESCRIPTION
**Pull request by eadwu**
###### Motivation for this change
Tested on x86_64.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by veprbl** [comment]
@eadwu do you think you could add yourself to `meta.maintainers`?

**Comment by eadwu** [comment]
Can someone verify whether or not the native modules have their dependencies? Such as for `ldd result/lib/vscode/resources/app/node_modules.asar.unpacked/node-pty/build/Release/pty.node`, I'm getting `libstdc++.so.6 => not found`.

**Comment by worldofpeace** [comment]
Yeah I get `libstdc++.so.6 => not found` as well.

Guess we can fix that later.

**Comment by worldofpeace** [comment]
Thanks @eadwu :sparkles:

**Comment by eadwu** [comment]
Should this still be backported, considering the next stable is coming pretty soon?

**Comment by worldofpeace** [comment]
> Should this still be backported, considering the next stable is coming pretty soon?

Backporting this one should be fine, even with the next stable coming soon. 
We'd stop once 18.09 reaches eol.

**Pull request merged**
