### PR TITLE
Enables /etc/rc.local compatibility via systemd

### PR DESCRIPTION
**Pull request by ghost**
Remaking previous pull-request https://github.com/NixOS/nixpkgs/pull/5819 in order to have the /etc/rc.local file controlled by the NixOS itself.

### CODE REVIEW

**Comment by bjornfor** [comment]
I'm a bit unsure if this is a good idea. Traditional rc.local was being run synchronously in a particular phase of the boot, typically towards the end. This PR adds a rc.local that will run asynchronously _somewhere_ during the boot (after network.target). How does one know what is available and what is not at the time rc.local is run?

Is it intentional to mask errors with "exit 0"? I personally would prefer to get notified if the script fails, not hide the fact.

**Comment by arno01** [comment]
Yes, `exit 0` is intentionally there, so that systemd will know that `/etc/rc.local` has been executed so that `systemctl status rc-local.service` will show it with its childs.

The `/etc/rc.local` file can have dozens or more commands and if one of them will fail it doesn't mean that the other ones have failed too.

Also, in several Linux distros I've seen `exit 0` by default in `/etc/rc.local` file and it asked to place commands before `exit 0`.

**Comment by arno01** [comment]
@bjornfor if you have good idea how to set the order synchronously leveraging the systemd, please let me know. I'm not a deep expert of systemd, it's something new to me.

**Comment by bjornfor** [comment]
AFAIK, there is no way to run it synchronously with systemd (but I'm no expert). I think the only way is to specify dependencies to achieve the needed execution order (constraints). That's why I'm wondering if this PR is a good idea... My thinking is that this rc.local option is too generic for the asynchronous world of systemd.

The option that @7c6f434c mentioned, boot.postBootCommands, is said to run before systemd is started. (And I would presume it runs synchronously...) Does that option meet your requirements?

(Ok, I didn't know "exit 0" was a common thing in rc.local.)

**Comment by arno01** [comment]
@bjornfor `boot.postBootCommands  Shell commands to be executed just before systemd is started.` - not sure if this is something I want. This way it would run it too early... And I want a control over `/etc/rc.local` so that I can use `systemctl status rc-local.service` to see its running children and "stop/staart/restart".

**Comment by 7c6f434c** [comment]
>AFAIK, there is no way to run it synchronously with systemd (but I'm no expert). I think the only way is to specify dependencies to achieve the needed execution order (constraints). That's why I'm wondering if this PR is a good idea... My thinking is that this rc.local option is too generic for the asynchronous world of systemd.
>
>The option that @7c6f434c mentioned, boot.postBootCommands, is said to run before systemd is started. (And I would presume it runs synchronously...) Does that option meet your requirements?

Having an option to run something late enough asynchronously and an
option to run something before systemd synchronously is a good idea; 
but the difference would have to be described somewhere.

>(Ok, I didn't know "exit 0" was a common thing in rc.local.)

**Comment by bjornfor** [comment]
Ok. I can see this has its use case.

**Comment by peti** [comment]
Well, personally, I wouldn't anything that I'd want to run in this hook. I'm not sure what to think of the batching: I'd prefer separate commands to run separately so that each of them has its own status. Also, there seems to be no way to specify the dependencies for the commands in this unit, which is a requirement for executing them safely within systemd.

**Comment by arno01** [comment]
Definitely not everyone would use/need this. And definitely there are some people who would need it.
What is great about Open Source is that people have an option, either to use what others wrote or to write it by yourself. With this commit it makes it easy with the latter.
However this is up to the Devs whether or not to accept this commit to master.
My part was to make it available, at least in this kind of form ;-)

**Comment by peti** [comment]
What kind of command would you put into this `rc.local` hook? Can you give an example?

**Comment by peti** [comment]
Also, what is the point of writing a file called `/etc/rc.local` and have systemd execute that instead of writing the commands into the systemd unit directly? What advantage do we gain by having `/etc/rc.local` symlink to the store instead of executing the script directly from the store?

**Comment by arno01** [comment]
@peti I already wrote it here https://github.com/NixOS/nixpkgs/pull/5819#issuecomment-70404577

But generally speaking -> anything that I need to quickly put there if I'm in lack of time to develop .nix service modules. 
For example, I've migrated my mail server from Debian to NixOS and I wanted to ensure that it will be "more" available in case if the VPS provider reboots the VPS due to maintenance or whatsoever. To make it "more" available I really needed to put `opendkim` into the `/etc/rc.local` file.

**Comment by peti** [comment]
@arno01, both of the commands you gave in the earlier PR will fail unless they're executed after their required resources have become available. Executing them in an environment that says "network must be up" is not the same thing as saying "/sys must be mounted" or "/var must be mounted", etc.

**Comment by 7c6f434c** [comment]
>Also, what is the point of writing a file called `/etc/rc.local` and have systemd execute that instead of writing the commands into the systemd unit directly? What advantage do we gain by having `/etc/rc.local` symlink to the store instead of executing the script directly from the store?

An alternative inspection path, so you can see same things in the same
place as on some other systems (where it doesn't break Nix usage).

Yes, I have /usr/bin/env symlink on my system.

**Comment by arno01** [comment]
@peti just did reboot my server and everything is working totally fine

``
[root@mail:~]# systemctl status rc-local.service
● rc-local.service - Execute /etc/rc.local
   Loaded: loaded (/nix/store/hash-unit-rc-local.service/rc-local.service)
   Active: active (exited) since Sun 2015-01-18 20:21:04 CET; 20s ago
  Process: 1275 ExecStart=/etc/rc.local (code=exited, status=0/SUCCESS)
 Main PID: 1275 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/rc-local.service
           ├─1289 /run/current-system/sw/bin/opendkim -x /etc/opendkim.conf -u opendkim -P /var/run/opendkim/opendkim.pid -l
           └─1290 /run/current-system/sw/bin/opendkim -x /etc/opendkim.conf -u opendkim -P /var/run/opendkim/opendkim.pid -l

Jan 18 20:21:04 mail systemd[1]: Started Execute /etc/rc.local.

[root@mail:~]# cat /sys/block/sda/queue/scheduler
noop cfq [deadline] 

[root@mail:~]# uptime 
 20:21pm  up   0:00,  1 user,  load average: 0.40, 0.11, 0.04

``

`After=network.target` I took from https://lists.debian.org/debian-user/2014/08/msg01366.html

**Pull request closed without merging**
