### PR TITLE
WIP lib: Better extensible attrsets

### PR DESCRIPTION
**Pull request by Ericson2314**
###### Motivation for this change

This is a WIP implementation of something like @edolstra's `{{...}}` recursive attrsets (from older https://gist.github.com/edolstra/29ce9d8ea399b703a7023073b0dbc00d), but with the `self`-`super` pattern. I'm all for the more ambitious goals (sharing abstractions for nixos/nixpkgs, no `callPackage`, prioritizes or something finer-grained over `super` sledge-hammer, etc), but fear without incremental steps like this, they won't happen.

  - Like it or not, `self` `super` is today's semantics for Nixpkgs
  - Doesn't try to fight `callPackage`, works very well with `self.callPackage` in the manner of Haskell package sets.
  - Recursion on merge solves the problem of deep overrides in overlays / recursive package sets
 
In particular, having both the inner and outer fixed points solves the problems with https://github.com/NixOS/nixpkgs/pull/44196 and my `injectOverride` alternative:
   - "Copying" (rebinding) an inner extensible attribute set just works, future overrides of the original won't affect the copy
  - overriding inside works per recursive merge
  - no `overrideScope` needed as one can just use `makeScope` to bind a local `callPackage` which will be updated automatically by extensible attrset merge.

The last commit is an example rushed example of how it simplifies `llvmPackages_5` and `darwin` inner attribute set overriding in the Darwin bootstrapping. Further simplification would come from the unrelated change of having just `llvmPackages_*.{tools,libraries}`, rather than that + the legacy smushing of everything inside those alongside.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

CC @ElvishJerricco

### CODE REVIEW

**Comment by edolstra** [comment]
No, this is a wrong direction for Nix. I don't want to have to explain to users what a "monoidal extension" is. The Nix language (as a DSL) should provide the proper concepts, they should not be provided in a library. Also, I suspect that this will make Nixpkgs evaluation even slower and memory-hungry.

**Comment by Ericson2314** [comment]
@edolstra don't miss the forest for the trees :)

1. All the monoid stuff is just an implemention detail. It can be inlined away.

2. If we make `zipAttrsWith` a built-in there should be little performance impact. (Typically the overlay atteset is vastly smaller, and the overriding vs new attrs vastly smaller than that.)

**Comment by ElvishJerricco** [comment]
I agree with @Ericson2314 about trying to do things incrementally; we're not going to be able to convert all of nixpkgs to the new system at once whenever we do get the language level feature. But @Ericson2314, I would recommend finding more friendly names for this stuff. IMO this has little to do with the term "monoid", because it's not actually abstract over the monoid in use. It'd be like calling `||` "monoidal choice".

**Comment by edolstra** [comment]
@Ericson2314 That's what we've been doing for the last few years: we have stuff like the module system as a library feature. Now it's time to do it properly as a language feature.

**Comment by Ericson2314** [comment]
@ElvishJerricco no it actually is abstract over all monoids in this implementation, just as we talked about long ago. The *user* doesn't need to worry about arbitrary monoids, but by the same token it is bad and a sign of the WIP-ness of this PR that they currently use any of the monad-polymorphic stuff.

@edolstra Yes, NixOS is ready, but Nixpkgs-the-package-set isn't. The most widely used things in nixpkgs like stdenv and cc-wrapepr are known-bad, and the langauge-specific/nested package stuff is not at all standardized. If your proposal only talked about NixOS, it would be one thing, but as it aims for the unified abstraction for packages and configurations, we have no choice but to first whip Nixpkgs-the-package-set into shape.

**Comment by Ericson2314** [comment]
@edolstra @ElvishJerricco and @angerman in particular are doing some cool work with next-gen Haskell infra using the NixOS module system. A wonderful sequence of events would be.

1. Merge cleaned up version of this
2. Get everything in nixpkgs using nested `self: super: { .. }` package sets / overriding
4. New Haskell stuff done with NixOS modules, possible extended modules
5. Use @Profpatsch's type checker work to separate merging / checking aspects of module system
6. Use Module system instead of `self: super: { .. }` package sets.
7. Deal with any remaining `callPackage` and friends (e.g. make that compat layer)
8. NixOS + Nixpkgs all uses improved module system (maybe with some deprecated layers)
9. Some static typing stuff is finally ready?
10. Enshrine everything with new syntax.

**Comment by mmahut** [comment]
Are there any updates on this pull request, please?

**Comment by Infinisil** [comment]
Relevant rfc: https://github.com/NixOS/rfcs/pull/67

**Pull request closed without merging**
