### PR TITLE
txr: 209 -> 216

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

Versions 210-215 crashed during tests,
but this one looks good! Enjoy!

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by tomberek — APPROVED** [review]
Builds, runs on Ubuntu.
Did NOT check Darwin. Note ofborg failure.

**Comment by grahamc** [comment]
@GrahamcOfBorg build txr

**Comment by Infinisil** [comment]
Can confirm the same failure on my mac. I suggest disabling darwin

**Comment by dtzWill** [comment]
Hmm, well not sure what's going on but it looks like upstream provides OSX prebuilt binaries for this?

https://bintray.com/kazinator/Binaries/TXR/

Or is this something that might be NixOS+Darwin specific?

**Comment by dtzWill** [comment]
@Infinisil or @grahamc : I'd like to poke a bit at the Darwin failure--and email upstream to see if they have any ideas (or it's a bug in which case I'm glad to have reported it :)).  Anyway I can't seem to get the full build log from any of the failed attempts, only the summaries.  And the full log for the last build which just says "no attempt since disabled on this platform" in its own way :).

Can either of you help -- grab me a build log from a failure? I suppose ideally we'd do it with some of TXR's debug/checking but for a first pass just seeing the failure would be good.  Thanks!

**Pull request merged**
