### PR TITLE
[WIP] python.pkgs.mycroft-precise: init at 2020-02-14

### PR DESCRIPTION
**Pull request by timokau**
###### Motivation for this change

I wanted to experiment with hotword-triggered voice memos. Unfortunately this turned out to be more complicated than I had hoped.

For now `python3.pkgs.mycroft-precise` builds and runs. It doesn't work as expected though. Maybe https://github.com/MycroftAI/mycroft-precise/pull/141 will help. I don't know when or if I'll continue to work on this, so I thought I'd put it out there in its current state.

**If you'd like to take this over, please do. I maintain enough packages already and I'm not sure if I'll finish this and commit to maintaining it.**

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by timokau** [comment]
If you want to play with this, clone the community data repository at `https://github.com/MycroftAI/precise-community-data` and use one of the models. For example if you've cloned the repo to `~/repos/Precise-Community-Data` and unpacked the `computer` model under `computer/model`, you can use `precise-engine` to detect the hotword in their sample data:

```
result/bin/precise-engine ~/repos/Precise-Community-Data/computer/models/computer-en-0.2.0-20190814-eltocino/computer-en.pb < ~/repos/Precise-Community-Data/computer/en/computer-en-117c2f25-4ab5-4620-84c4-84cf1bb7af49.wav
```

you should see an activation above 0.5 for their samples (currently that is not the case). Alternatively you can try it with your microphone's input:

```
result/bin/precise-listen -b ~/repos/Precise-Community-Data/computer/models/computer-en-0.2.0-20190814-eltocino/computer-en.pb
```

a `!` should pop up when you say the word "computer" (it currently doesn't though).

**Comment by timokau** [comment]
Abusing this PR a bit for a test.
/marvin triage

**Comment by timokau** [comment]
Hi!

The marvin-mk2 bot is now [discontinued](https://github.com/timokau/marvin-mk2/issues/34#issuecomment-1100656280). I have removed the relevant tags from this PR. If you still need someone to look at it, one option would be to ask in [this discourse thread](https://discourse.nixos.org/t/prs-ready-for-review/3032).

I am posting this notice to all open PRs with the `marvin` tag. Please understand that following all of these discussions would take too much time, so I will unsubscribe from this PR unless I have already been involved in it before this message.

**Comment by timokau** [comment]
I do not intend to pick this up any time soon.

**Comment by mweinelt** [comment]
If you're still interested in mycroft itself, may I interest you in #161596?

**Comment by timokau** [comment]
Thanks for the pointer!

**Pull request closed without merging**
