### PR TITLE
sphinx: 5.3.0 -> 7.2.6

### PR DESCRIPTION
**Pull request by natsukium**
## Description of changes

Diff: https://github.com/sphinx-doc/sphinx/compare/v5.3.0...v7.2.6
Changelog: https://www.sphinx-doc.org/en/master/changes.html#release-7-2-6-released-sep-13-2023

A successor to https://github.com/NixOS/nixpkgs/pull/244625

The commit 1eb8fcf085f39f4ea478b6c3daa707b1df9f6d29 adds `pythonNamespaces` to all `sphinxcontrib-*` packages in order to fix the import error reported in the following comment.
https://github.com/NixOS/nixpkgs/pull/210338#issuecomment-1447063024
This is an existing approach that fixes the legacy setuptools namespace issue that @tjni investigated.

I also picked a commit to standardize the pname, as noted in this comment.
https://github.com/NixOS/nixpkgs/pull/244625#issuecomment-1650257767

related PRs
- https://github.com/NixOS/nixpkgs/pull/210338
- https://github.com/NixOS/nixpkgs/pull/244625
- https://github.com/NixOS/nixpkgs/pull/249230

cc @AndersonTorres @mweinelt @ncfavier @SuperSandro2000 @tjni

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by natsukium** [comment]
@ofborg build python311Packages.wrapt

**Comment by trofi** [comment]
`git bisect` says ce209976f569f4e62c406fa3b4344c8e9b23830f `sphinx: 5.3.0 -> 7.2.6` caused build failures in `staging-next` for at least `python3.pkgs.breathe`, `libcamera`, `ghc`.

`libcamera` fails as:

```
[153/158] Generating Documentation/documentation with a custom command
FAILED: Documentation/html
/nix/store/dzsd3p2zpvkdq4z72vh1yfqcysyhllim-python3.11-sphinx-7.2.6/bin/sphinx-build -D release=v0.0.5 -q -W -b html /build/libcamera/Documentation Documentation/html
/nix/store/m6b4x4a5dk83rhzf293xq5csjcj4nlgn-python3.11-sphinxcontrib-applehelp-1.0.2/lib/python3.11/site-packages/sphinxcontrib/applehelp/__init__.py:24: RemovedInSphinx80Warning: The alias 'sphinx.util.SkipProgressMessage' is deprecated, use 'sphinx.util.display.SkipProgressMessage' instead. Check CHANGES for Sphinx API modifications.
  from sphinx.util import SkipProgressMessage, progress_message
/nix/store/m6b4x4a5dk83rhzf293xq5csjcj4nlgn-python3.11-sphinxcontrib-applehelp-1.0.2/lib/python3.11/site-packages/sphinxcontrib/applehelp/__init__.py:24: RemovedInSphinx80Warning: The alias 'sphinx.util.progress_message' is deprecated, use 'sphinx.util.display.progress_message' instead. Check CHANGES for Sphinx API modifications.
  from sphinx.util import SkipProgressMessage, progress_message
/nix/store/kbwpk8fvpg3c7xz68cnh9cd46r69jx5c-python3.11-sphinxcontrib-htmlhelp-2.0.0/lib/python3.11/site-packages/sphinxcontrib/htmlhelp/__init__.py:26: RemovedInSphinx80Warning: The alias 'sphinx.util.progress_message' is deprecated, use 'sphinx.util.display.progress_message' instead. Check CHANGES for Sphinx API modifications.
  from sphinx.util import progress_message

Theme error:
An error happened in rendering the page api-html/index.
Reason: UndefinedError("'style' is undefined")
```

**Comment by vcunat** [comment]
Hydra shows the same log for ghc:
https://hydra.nixos.org/build/239551789/nixlog/1/tail

**Comment by mweinelt** [comment]
cc @sternenseemann for ghc

We already had a patch for that iirc.

**Comment by sternenseemann** [comment]
That's a new issue, I think, the patch was for 6.0 and is either applied in nixpkgs or upstreamed into GHC. I've opened https://gitlab.haskell.org/ghc/ghc/-/issues/24129 for now, since I can't look into it myself atm.

**Comment by vcunat** [comment]
https://github.com/NixOS/nixpkgs/pull/263923

**Pull request merged**
