### PR TITLE
spidermonkey_52: don't use jemalloc w/musl

### PR DESCRIPTION
**Pull request by dtzWill**
- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by orivej** [comment]
Why do you want to disable jemalloc?

**Comment by dtzWill** [comment]
Not so much don't want as it doesn't work so disable it instead of failing to build :).

Historically musl wasn't compatible with malloc replacements, with 1.1.20 (days old) being first with support.

The build failure didn't look too bad but since I'm not sure it would work anyway seemed best to disable it.

**Comment by Mic92** [comment]
Should this be backported?

**Comment by orivej** [comment]
@dtzWill Since 1.1.20 is already merged, would you revert this if it is not necessary? (Actually older musls can be used with external allocators as long as they are built without the internal one.)

**Comment by dtzWill** [comment]
> @dtzWill Since 1.1.20 is already merged, would you revert this if it is not necessary? (Actually older musls can be used with external allocators as long as they are built without the internal one.)

Of course! Looking into it briefly I'm not optimistic about jemalloc-- having trouble getting the test-suite (for the jemalloc package itself, not the one vendored in mozjs) to not crash w/musl on versions 5.0.1 (our default), 5.1.0 (latest), or the current 'dev' branch code.  That said, various musl-based distributions package it so maybe it's worth looking into further.

FWIW the build failure was due to attempting to include 'sys/sysctl.h' which doesn't exist w/musl.

**Comment by dtzWill** [comment]
Quick follow-up in terms of Nixpkgs and jemalloc+musl:

* jemalloc 4.5.0 seems to work w/musl 1.1.20 (and 1.1.19)
* jemalloc 5.x does not work with musl 1.1.20 but seems to work with musl 1.1.19
* spidermonkey52 doesn't build against 1.1.20 or 1.1.19 as-is (sys/sysctl.h issue).

Where by jemalloc "working" I mean "jemalloc tests pass".

**Comment by orivej** [comment]
I had used musl with jemalloc 3.6.0.

`sys/sysctl.h` seems to be a BSD header, it does not exist on Linux even with Glibc.

**Comment by dtzWill** [comment]
Well it seems to exist in our glibc's include directory (in `glibc.dev`).
Dunno.

**Comment by vcunat** [comment]
> Historically musl wasn't compatible with malloc replacements, with 1.1.20 (days old) being first with support.

:scream:

**Pull request merged**
