### PR TITLE
gcc: 9.1.0 -> 9.2.0

### PR DESCRIPTION
**Pull request by xbreak**
###### Motivation for this change
gcc 9.2.0 is a bug-fix release, c.f. https://gcc.gnu.org/gcc-9/changes.html for details.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested compilation of internal packages that use gcc9Stdenv
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc  @Synthetica9, @dtzWill

### CODE REVIEW

**Review by vcunat — APPROVED** [review]
Works fine for me.

**Comment by mmahut** [comment]
@GrahamcOfBorg build gcc

**Comment by vcunat** [comment]
(this PR doesn't update the default `gcc`)

**Comment by mmahut** [comment]
Right, thank you.

@GrahamcOfBorg build gcc9

**Comment by mmahut** [comment]
Builds for me fine, working fine as well.

**Pull request merged**
