### PR TITLE
llvmPackages_19: 19.1.1 -> 19.1.3

### PR DESCRIPTION
**Pull request by paparodeo**
https://github.com/llvm/llvm-project/releases/tag/llvmorg-19.1.3

bolt is broken on x86_64-darwin on master  https://hydra.nixos.org/build/276866191 due to trying to write an archive to the llvm package store. applied upstream change https://github.com/llvm/llvm-project/commit/5909979869edca359bcbca74042c2939d900680e to fix.

had to make one tweak to fix the workaround for `libclc` that our wrappers can't accept `-arch`. `libclc` needs a wrapped `c++` to get header access but an unwrapped `clang`.
this fixes  https://hydra.nixos.org/build/276170976/nixlog/1/tail

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by paparodeo** [comment]
@ofborg build llvmPackages_19

**Comment by paparodeo** [comment]
@ofborg build llvmPackages_19

**Comment by paparodeo** [comment]
> Oh, I was kinda wanting to do this after 24.11 heh. Are the fixes important enough for 24.11?

why? there were some erroneous symbols left in libc++ for 19.1.0 that were removed in 19.1.2. the change log lists various other bug fixes. seems perfectly acceptable to go in 24.11.

**Comment by RossComputerGuy** [comment]
> why?

Because it came out after the breaking changes freeze.

**Comment by paparodeo** [comment]
> > why?
> 
> Because it came out after the breaking changes freeze.

bugfixes and minor version updates aren't breaking changes (as long as they don't have breaking changes)
https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#changes-acceptable-for-releases

**Comment by RossComputerGuy** [comment]
I forgot that it doesn't have breaking changes lol.

**Comment by RossComputerGuy** [comment]
```
Result of `nixpkgs-review pr 352781` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>magnetophonDSP.ConstantDetuneChorus</li>
    <li>magnetophonDSP.VoiceOfFaust</li>
  </ul>
</details>
<details>
  <summary>9 packages failed to build:</summary>
  <ul>
    <li>emscriptenPackages.json_c</li>
    <li>emscriptenPackages.json_c.dev</li>
    <li>emscriptenPackages.libxml2</li>
    <li>emscriptenPackages.libxml2.bin</li>
    <li>emscriptenPackages.libxml2.dev</li>
    <li>emscriptenPackages.libxml2.devdoc</li>
    <li>emscriptenPackages.xmlmirror</li>
    <li>emscriptenPackages.xmlmirror.doc</li>
    <li>emscriptenPackages.zlib</li>
  </ul>
</details>
<details>
  <summary>76 packages built:</summary>
  <ul>
    <li>bolt_19 (llvmPackages_19.bolt)</li>
    <li>bolt_19.dev (llvmPackages_19.bolt.dev)</li>
    <li>bpf-linker</li>
    <li>clang_19 (llvmPackages_19.clang)</li>
    <li>emscripten</li>
    <li>faust</li>
    <li>faust2alqt</li>
    <li>faust2alsa</li>
    <li>faust2csound</li>
    <li>faust2firefox</li>
    <li>faust2jack</li>
    <li>faust2jackrust</li>
    <li>faust2jaqt</li>
    <li>faust2ladspa</li>
    <li>faust2lv2</li>
    <li>faust2sc</li>
    <li>faustPhysicalModeling</li>
    <li>faustlive</li>
    <li>guitarix</li>
    <li>kapitonov-plugins-pack</li>
    <li>lld_19 (llvmPackages_19.lld)</li>
    <li>lld_19.dev (llvmPackages_19.lld.dev)</li>
    <li>lld_19.lib (llvmPackages_19.lld.lib)</li>
    <li>lldb_19 (llvmPackages_19.lldb)</li>
    <li>lldb_19.dev (llvmPackages_19.lldb.dev)</li>
    <li>lldb_19.lib (llvmPackages_19.lldb.lib)</li>
    <li>llvmPackages_19.bintools</li>
    <li>llvmPackages_19.bintools-unwrapped</li>
    <li>llvmPackages_19.bintoolsNoLibc</li>
    <li>llvmPackages_19.clang-manpages</li>
    <li>llvmPackages_19.clang-tools</li>
    <li>llvmPackages_19.clang-unwrapped</li>
    <li>llvmPackages_19.clang-unwrapped.dev</li>
    <li>llvmPackages_19.clang-unwrapped.lib</li>
    <li>llvmPackages_19.clang-unwrapped.python</li>
    <li>llvmPackages_19.clangNoCompilerRt</li>
    <li>llvmPackages_19.clangNoCompilerRtWithLibc</li>
    <li>llvmPackages_19.clangNoLibc</li>
    <li>llvmPackages_19.clangNoLibcxx</li>
    <li>llvmPackages_19.clangUseLLVM</li>
    <li>llvmPackages_19.clangWithLibcAndBasicRtAndLibcxx</li>
    <li>llvmPackages_19.compiler-rt</li>
    <li>llvmPackages_19.compiler-rt-no-libc</li>
    <li>llvmPackages_19.compiler-rt-no-libc.dev</li>
    <li>llvmPackages_19.compiler-rt.dev</li>
    <li>llvmPackages_19.libclc</li>
    <li>llvmPackages_19.libclc.dev</li>
    <li>llvmPackages_19.libcxx</li>
    <li>llvmPackages_19.libcxx.dev</li>
    <li>llvmPackages_19.libcxxClang</li>
    <li>llvmPackages_19.libcxxStdenv</li>
    <li>llvm_19 (llvmPackages_19.libllvm)</li>
    <li>llvm_19.dev (llvmPackages_19.libllvm.dev)</li>
    <li>llvm_19.lib (llvmPackages_19.libllvm.lib)</li>
    <li>llvm_19.python (llvmPackages_19.libllvm.python)</li>
    <li>llvmPackages_19.libunwind</li>
    <li>llvmPackages_19.libunwind.dev</li>
    <li>llvmPackages_19.lldb-manpages</li>
    <li>llvmPackages_19.lldbPlugins.llef</li>
    <li>llvmPackages_19.llvm-manpages</li>
    <li>llvmPackages_19.mlir</li>
    <li>llvmPackages_19.mlir.dev</li>
    <li>llvmPackages_19.openmp</li>
    <li>llvmPackages_19.openmp.dev</li>
    <li>llvmPackages_19.stdenv</li>
    <li>magnetophonDSP.CharacterCompressor</li>
    <li>magnetophonDSP.CompBus</li>
    <li>magnetophonDSP.LazyLimiter</li>
    <li>magnetophonDSP.MBdistortion</li>
    <li>magnetophonDSP.RhythmDelay</li>
    <li>magnetophonDSP.faustCompressors</li>
    <li>magnetophonDSP.pluginUtils</li>
    <li>magnetophonDSP.shelfMultiBand</li>
    <li>mooSpace</li>
    <li>open-music-kontrollers.mephisto</li>
    <li>tambura</li>
  </ul>
</details>
```

**Comment by paparodeo** [comment]
the emscriptenPackages are broken on master

**Comment by paparodeo** [comment]
added patch from https://github.com/llvm/llvm-project/commit/5909979869edca359bcbca74042c2939d900680e which fixes the bolt darwin build (currently broken on master)

**Comment by paparodeo** [comment]
changed to `runCommand` rather than `runCommandLocal` and added a comment. moved to staging for reasons.

**Review by emilazy — APPROVED** [review]

**Comment by paparodeo** [comment]
could this get the back port 24.11 label?

**Pull request merged**
