### PR TITLE
python3Packages.fs: fix tests on darwin

### PR DESCRIPTION
**Pull request by tricktron**
Refactors to `pytestCheckHook` and removes unused `nose` dependency.

###### Motivation for this change

ZHF: #97479
@NixOS/nixos-release-managers  

On darwin and python 3.8.5 there seems to be a problem. See https://github.com/PyFilesystem/pyfilesystem2/issues/430

So I just disabled the failing test for now.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
Running macos 10.14, I have a suspicion that `tests/test_tarfs.py::TestWriteGZippedTarFS::test_getinfo` may be flakey. I got a single failure on `python37Packages.fs` but afterwards it built fine. Unfortunately I didn't get a full log for the failed build because I expected to be able to reproduce it.

**Review by risicle — APPROVED** [review]
Other than that, WFM, LGTM on macos 10.14 & linux x86_64.

**Comment by jonringer** [comment]
@risicle you should be able to see that "builder for '......drv' failed" if you pass the drv path to `nix log` it will show you the build logs.

unless you're running these on a remote machine, then that's a little more complicated, but do-able

**Comment by risicle** [comment]
Oh, I've closed the tab now...

**Comment by tricktron** [comment]
@jonringer @risicle Ready to merge or do you want me to change something?

**Comment by risicle** [comment]
I think it's fine :+1:

**Comment by jonringer** [comment]
Please follow [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md) and [manual#submitting-changes-making-patches ](https://nixos.org/nixpkgs/manual/#submitting-changes-making-patches) and squash the fix-up commits.

This can be done without `git rebase -i` by doing:
```
git reset HEAD~1                    # move fix-up commits into unstaged
git add -- pkgs/                    # move changes into staged
git commit --amend --no-edit        # add changes to previous commit
git push ... ... --force            # modify current PR branch
```

However, `git rebase -i` is a more powerful alternative, I created a small video demonstrating it's use [here](https://www.youtube.com/watch?v=OR8Q-4PLalc). A more indepth text tutorial can be found [here](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase)

**Comment by tricktron** [comment]
@jonringer I rebased and fixuped the last commit.

**Review by risicle — APPROVED** [review]
Still WFM macos 10.14, non-nixos linux x86_64.

You have merge rights yourself so I'll let you do the honors.

**Comment by tricktron** [comment]
@risicle I guess you are talking to @jonringer because I don't have merge rights as far as I know😄.

**Comment by risicle** [comment]
You appear to be a "Member". Is there no big green merge button for you?

**Comment by tricktron** [comment]
> You appear to be a "Member". Is there no big green merge button for you?

@risicle: Nope, I only see: _Only those with write access to this repository can merge pull requests._. What is needed to get merge right access?

**Comment by risicle** [comment]
Lord knows, I think some drunk fool gave it to me

**Comment by jonringer** [comment]
@risicle member just means that you belong to a group within the NixOS (github) organization. Doesn't determine repo privileges

**Pull request merged**
