### PR TITLE
[WIP] Mame: init at 0.195

### PR DESCRIPTION
**Pull request by bignaux**
###### Motivation for this change

Some help on this big client would be appreciate :
* darwin support
* qt is not well managed
* installation phase needs improvements

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthewbauer** [comment]
Note that sdlmame already exists but it looks like yours is much more up to date. If you can get this working, you should remove sdlmame (and provide an alias).

**Comment by timokau** [comment]
@bignaux will you be finishing this or should it be closed?

**Comment by bignaux** [comment]
i should have a look. My pb is computer power, it took me 8H for build this.

**Comment by timokau** [comment]
Why would that take so long? Did you build all the dependencies?

**Comment by bignaux** [comment]
No, it's a heavy project emulating lot of arch, the best imho.

**Comment by timokau** [comment]
Still 8h build time seems a bit excessive for a single application.

**Comment by nyanloutre** [comment]
Hello, are you still working on it ?

**Pull request closed without merging**
