### PR TITLE
libsurvive, monado, xrgears init

### PR DESCRIPTION
**Pull request by expipiplus1**
`xrgears` worked with no trouble at all with `monado`

Run with the following after calibrating with `survive-cli`

```
nix-shell -p monado xrgears
monado-service &
xrgears
```

I am unable to test with SteamVR because of several
OpenXR/SteamVR issues. Hopefully having xrgears packaged will help in
resolving these.

- https://github.com/ValveSoftware/SteamVR-for-Linux/issues/412
- https://github.com/ValveSoftware/SteamVR-for-Linux/issues/413
- https://github.com/ValveSoftware/SteamVR-for-Linux/issues/95
- https://github.com/NixOS/nixpkgs/issues/92795

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by expipiplus1** [comment]
@Ralith is probably a good person to review

**Comment by expipiplus1** [comment]
rebased to try and fix the eval error

**Review by Ralith — APPROVED** [review]

**Comment by expipiplus1** [comment]
Oh, I also added an option to permit using monado as a standalone OXR driver: https://github.com/NixOS/nixpkgs/pull/107001/files#diff-106b24654c76c529dc27594b37db5f3597a22b6e8f3d8a8a6ebea6f289d73aa0R5-R9

**Comment by expipiplus1** [comment]
not sure what these eval errors are about, have rebased again.

**Comment by expipiplus1** [comment]
Fixed eval errors with s/libusb/libusb1/

**Comment by prusnak** [comment]
Superseded by https://github.com/NixOS/nixpkgs/pull/108820 where I rebased  @expipiplus1's  changes on top of the current master.

**Pull request closed without merging**
