### PR TITLE
firefox-unwrapped: workaround issues on non-Gnome wayland WM's on FF 92

### LINKED ISSUE #137649: Firefox 92 on Sway - Menus are invisible and freeze the whole UI
### Describe the bug
After upgrading to Firefox 92 on NixOS unstable, anything that requires a menu or a tooltip in the browser (hamburger menu, right click context menus, tooltips on tabs, etc.) stopped working. The menu itself isn't rendered, the whole UI freezes and sometimes the cursor changes to a hand, indicating a clickable button, but nothing happens when clicking where the button should be. Clicking outside the area where the menu should appear restores Firefox to a usable state, until another menu button is pressed.

### Steps To Reproduce
1. Open Firefox
2. Click the hamburger menu button on the top right corner

### Expected behavior
The main settings menu for Firefox should appear.

### Screenshots
The hamburger button remains in a "clicked" state and the entire UI freezes, the mouse cursor might change to a hand, but no menu is rendered.

### Additional context
Running Firefox on Sway with `MOZ_ENABLE_WAYLAND=1` and `"gfx.webrender.all" = true;`

### Notify maintainers
@lovesegfault @mweinelt @edolstra @NeQuissimus @vcunat 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/xq77wmzk8d306anyk9rsvl4i4h7ihchw-bash-interactive-4.4-p23-dev
copying path '/nix/store/xq77wmzk8d306anyk9rsvl4i4h7ihchw-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.2, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210908_3c56f62`
 - channels(root): `"nixos-21.11pre314199.f6e9e908ccb, home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- firefox
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by lovesegfault**
###### Motivation for this change
Closes: #137649

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lovesegfault** [comment]
Result of `nixpkgs-review pr 137671` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>icedtea_web (icedtea8_web)</li>
    <li>firefox (firefox-wrapper ,firefoxWrapper)</li>
    <li>firefox-unwrapped</li>
    <li>firefox-wayland</li>
    <li>slimerjs</li>
  </ul>
</details>

**Comment by lovesegfault** [comment]
I've tested this and have it running on my system, and it indeed fixes the issues from #137649, additional confirmation before testing would be nice too.

**Comment by lovesegfault** [comment]
92 made it to the 21.05 release, so I've marked this for backporting

**Review by vcunat — APPROVED** [review]
Sounds good.  I'm not running any affected configuration.

**Pull request merged**
