### PR TITLE
cairo: 1.15.14 -> 1.16.0

### PR DESCRIPTION
**Pull request by dtzWill**
- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
On Fri, 19 Oct 2018 20:36:31 -0700, GrahamC of Borg <notifications@github.com> wrote:
> 
> Failure on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.48734&attempt_id=63818019-f6f1-4e76-9bb0-f1acba42b048)
> 
> Attempted: cairo
> 
> <details><summary>Partial log (click to expand)</summary><p>
> 
> ```
> building '/nix/store/0782dybi3wk39b41j447mpc2cdfxh9ni-curl-7.61.1.drv'...
> /nix/store/ic9jk332yd71lwvgdwsi8jh4jjmw5j63-cctools-binutils-darwin-wrapper/nix-support/setup-hook: fork: retry: Resource temporarily unavailable
> /nix/store/ic9jk332yd71lwvgdwsi8jh4jjmw5j63-cctools-binutils-darwin-wrapper/nix-support/setup-hook: fork: retry: Resource temporarily unavailable
> /nix/store/ic9jk332yd71lwvgdwsi8jh4jjmw5j63-cctools-binutils-darwin-wrapper/nix-support/setup-hook: fork: retry: Resource temporarily unavailable
> /nix/store/ic9jk332yd71lwvgdwsi8jh4jjmw5j63-cctools-binutils-darwin-wrapper/nix-support/setup-hook: fork: retry: Resource temporarily unavailable
> /nix/store/ic9jk332yd71lwvgdwsi8jh4jjmw5j63-cctools-binutils-darwin-wrapper/nix-support/setup-hook: fork: Resource temporarily unavailable
> builder for '/nix/store/0782dybi3wk39b41j447mpc2cdfxh9ni-curl-7.61.1.drv' failed with exit code 254
> cannot build derivation '/nix/store/g7rz97wj7p7vv63m0zvdhnay81b4wqjj-cairo-1.16.0.tar.xz.drv': 1 dependencies couldn't be built
> cannot build derivation '/nix/store/fy1is1h8q17lxkqwi8swqp6zdlfimksg-cairo-1.16.0.drv': 1 dependencies couldn't be built
> error: build of '/nix/store/fy1is1h8q17lxkqwi8swqp6zdlfimksg-cairo-1.16.0.drv' failed
> ```
> </p></details>

Just noting the failure on Darwin appears to be unrelated.

**Comment by timokau** [comment]
For what its worth, I think in those situations the right thing to do is to mark the failing dependency as broken. That way at least it is documented, no resources are wasted in the future and nobody will be confused.

**Comment by dtzWill** [comment]
Oh I thought it was just a (presumably transient) builder failure.

Actually it better be since the failure was in curl xD.

Round 2, fight!

@GrahamCOfBorg build cairo

**Comment by xeji** [comment]
Actually it's `nghttp2` that fails on darwin.

**Comment by dtzWill** [comment]
@GrahamcOfBorg build cairo

**Comment by dtzWill** [comment]
@GrahamcOfBorg build cairo

**Comment by dtzWill** [comment]
@GrahamcOfBorg build nghttp2

**Comment by dtzWill** [comment]
Well, won't make things worse for Darwin and should be good on Linux.  Here we go!

(ping me if you have problems, I'll be watching but might not notice immediately :))

**Pull request merged**
