### PR TITLE
python3Packages.mediapipe: init at 0.8.6

### PR DESCRIPTION
**Pull request by emilytrau**
###### Motivation for this change

Package Google's mediapipe image processing library. This uses the pre-built wheel versions. I attempted to try building from source, but the build system is a custom mix of setup.py and Bazel. I tried basing it on `buildBazelPackage` but it didn't seem to cover this use case. It may be something to look into in the future, as the wheel is potentially missing features such GPU support.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 132275` at 32078e67 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/603d49d284dc9c534c1f6523d02ff430">python38Packages.mediapipe</a></li>
    <li><a href="https://gist.github.com/0fca1187087373577575ec01387e91ed">python39Packages.mediapipe</a></li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: unused-argument

Unused argument: `pkgs`.
Near pkgs/development/python-modules/mediapipe/default.nix:1:16:
```
  |
1 | { lib, stdenv, pkgs, buildPythonPackage, fetchPypi, autoPatchelfHook
  |                ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Review by jonringer — COMMENTED** [review]
maintaining wheels are very exhausting. I would prefer to use the source code https://github.com/google/mediapipe if it's not painful to maintain.

**Comment by angustrau** [comment]
@jonringer that was my first attempt, but the build system is such a complex mish-mash of python and bazel that I couldn't get it to work. Perhaps someone more familiar with hazel could take another look

**Comment by angustrau** [comment]
Closed as stale

**Pull request closed without merging**
