### PR TITLE
Renames stateVersion to stateEpoch

### PR DESCRIPTION
**Pull request by samueldr**
###### Motivation for this change

Initially thrown on the wall [2018-10-07](https://logs.nix.samueldr.com/nixos/2018-10-07#1538875683-1538875214;).

This change is to reduce the support questions like this:

> I changed `stateVersion` in my `configuration.nix` and NixOS hasn't been upgraded to the next release. What gives?

Using the release version as a marker to decide between stateful schemas is in itself a good idea, but might not be the best interface to present to the end-users.

Having a monotonically incrementing opaque number will reduce confusion.

The number `100` has been chosen as:

  * It is bigger than 18.09 when compared as a version
  * Allows us to start "at zero" in a new range.

The number would have been `1` if possible, but existing `stateVersion = xx.yy;` makes it harder to implemented in such a way.

Additionally, decoupling the release version makes it so it is possible to have concurrent incompatible changes in `unstable`, while staying compatible, making for a better rolling-release approximation.

###### Things done

- ✔️ Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - ✔️ NixOS
- ⬜ Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- ⬜ Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- ⬜ Tested execution of all binary files (usually in `./result/bin/`)
- ⬜ Determined the impact on package closure size (by running `nix path-info -S` before and after)
- ✔️ Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Expectations

A bit of bikeshedding. A bit of criticism about the implementation.

Please consider the idea and propose better implementations, but don't hang yourself up on details of the implementation. I'm more interested in the big picture than corner case things. Once the big picture is better unveiled, and everything falls in place, the details can be worked out. Thanks.

### CODE REVIEW

**Comment by samueldr** [comment]
From IRC:

> [22:25:28] <ekleog> potential issue: release notes were done for releases, now the “manual steps for upgrading” needs to be done in a stateEpoch log which needs to be somewhere
> [22:25:42] <samueldr> ekleog: right!
> [22:26:01] <samueldr> but thos possibly can be coupled with the release notes
> [22:27:13] <samueldr> describing that for 101, foo's stateful directory will move from /dev/null to /dev/urandom, and for 102 bar's configuration file needs to be written in COBOL

So yeah, good point there, this makes it a tad harder to describe the changes in the release notes. Though, while the number itself is uncoupled from the releases, the notes about incompatible changes could realistically still be described in the release notes.

Though, since not *all* changes requiring an increase in `stateEpoch` requires to increment it, it's entirely possible  that during a single release only one epoch is going to be used. Even possible through two releases, while the following could have three, or more!

**Comment by srhb** [comment]
While this *may* cause people to not suddenly bump the variable on their own despite the warnings, I think it's going to increase the support burden, not the other way around, since it still has the same meaning but now has an extra layer of indirection in order to actually understand what's going on. In general, I doubt making the meaning of a certain value more opaque is an improvement.

I think it would be preferable to improve the documentation in both the generated warning and in the actual docs -- a link with some long-form prose in the "don't do this"-comment would be especially good.

**Comment by Infinisil** [comment]
What we'd really need is a state version for everything that needs state separately. So nginx has its state version, postgresql, etc. These are 0 by default and increase on every state incompatible update. Advantages:
- Allows users to only update/migrate a single part
- We could implement automatic migrations for some parts and only provide manual ones for others

In addition, these state versions could be stored alongside the data itself, in `/var/lib/nixos/stateversion` preferably. To be able to access these values in the configuration, we should modify `nixos-rebuild` to read the target hosts `stateversion` file and pass it to the configuration at the start. This has the advantage that nobody needs to track this version in their configuration, which I always thought was a bit annoying and unnecessary.

So *if* we're gonna change how this state version thing works, why not go all out and implement it properly.

**Comment by Infinisil** [comment]
> That would make building the configuration impure

Ah right, good point.

Now what we'd need is a separate command `nixos-generate-state-versions` which fetches the target hosts `/var/lib/nixos/stateversion` and puts it into an `/etc/nixos/state-versions.nix` file. But hold on, we pretty much have something like this already, `nixos-generate-config` for `hardware-configuration.nix`!

So how about extending `nixos-generate-config` to output a state version configuration as well. Maybe even integrate it into `nixos-rebuild` somehow.

**Comment by oxij** [comment]
:-1: on doing this.

:+1: on splitting into tiny per-service pieces.

See also https://github.com/NixOS/nixpkgs/commit/1f0b6922d3c2de3da235a7075d0d3cb9255b7cd7#commitcomment-29001452 and https://github.com/NixOS/nixpkgs/commit/4d1332e507fe55103bc5ddd0a384447dc7833e12#commitcomment-30039646

**Comment by Ekleog** [comment]
@samueldr I think this should be turned into an RFC, and it would basically never merge otherwise, isn't it?

**Comment by lucasew** [comment]
Closing as it is abandoned.

**Pull request closed without merging**
