### PR TITLE
bind: fix build on machines where glibc does not provide L1 cache size

### PR DESCRIPTION
**Pull request by NickCao**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by newAM — APPROVED** [review]
Built and ran on `aarch64-linux`, also reviewed the code changes in the patch, looks good.

**Comment by gador** [comment]
Result of `nixpkgs-review pr 163854` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>tests.nixos-functions.nixos-test</li>
    <li>tests.nixos-functions.nixosTest-test</li>
  </ul>
</details>
<details>
  <summary>31 packages failed to build:</summary>
  <ul>
    <li>acme-sh</li>
    <li>autofs5</li>
    <li>bashSnippets</li>
    <li>bind</li>
    <li>blueberry</li>
    <li>check-wmiplus</li>
    <li>cinnamon.cinnamon-common</li>
    <li>cinnamon.cinnamon-gsettings-overrides</li>
    <li>cinnamon.cinnamon-screensaver</li>
    <li>cinnamon.cinnamon-session</li>
    <li>cinnamon.cjs</li>
    <li>cinnamon.nemo</li>
    <li>cinnamon.pix</li>
    <li>cinnamon.warpinator</li>
    <li>cinnamon.xapps</li>
    <li>cinnamon.xreader</li>
    <li>cinnamon.xviewer</li>
    <li>dig (dnsutils)</li>
    <li>dwm-status</li>
    <li>host</li>
    <li>inxi</li>
    <li>monitoring-plugins</li>
    <li>nmapsi4</li>
    <li>python310Packages.xapp</li>
    <li>python39Packages.xapp</li>
    <li>sssd</li>
    <li>tests.trivial-builders.references</li>
    <li>testssl</li>
    <li>twa</li>
    <li>xed-editor</li>
    <li>xplayer</li>
  </ul>
</details>

**Comment by gador** [comment]
Result of `nixpkgs-review pr 163854` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>26 packages failed to build:</summary>
  <ul>
    <li>acme-sh</li>
    <li>autofs5</li>
    <li>bashSnippets</li>
    <li>bind</li>
    <li>blueberry</li>
    <li>cinnamon.cinnamon-common</li>
    <li>cinnamon.cinnamon-screensaver</li>
    <li>cinnamon.cinnamon-session</li>
    <li>cinnamon.cjs</li>
    <li>cinnamon.nemo</li>
    <li>cinnamon.pix</li>
    <li>cinnamon.warpinator</li>
    <li>cinnamon.xapps</li>
    <li>cinnamon.xreader</li>
    <li>cinnamon.xviewer</li>
    <li>dig (dnsutils)</li>
    <li>dwm-status</li>
    <li>host</li>
    <li>inxi</li>
    <li>monitoring-plugins</li>
    <li>python310Packages.xapp</li>
    <li>python39Packages.xapp</li>
    <li>sssd</li>
    <li>twa</li>
    <li>xed-editor</li>
    <li>xplayer</li>
  </ul>
</details>

**Comment by NickCao** [comment]
> Result of `nixpkgs-review pr 163854` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
> 26 packages failed to build:

Are you building via qemu-user or real harware?

**Comment by gador** [comment]
this was built using qemu

**Comment by NickCao** [comment]
Closing as not longer needed due to https://github.com/NixOS/nixpkgs/pull/164586

**Pull request closed without merging**
