### PR TITLE
emacs: add mailutils support

### PR DESCRIPTION
**Pull request by AndersonTorres**
Flagged via `withMailutils` (true by default).

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by AndersonTorres** [comment]
Picking the work from @Adopi at https://github.com/NixOS/nixpkgs/pull/291017

**Comment by AndersonTorres** [comment]
The error catched  by ofborg is not directly related to Emacs, but to another, stdenv-related thing.

**Review by hraban — APPROVED** [review]

**Comment by hraban** [comment]
Tons of test failures for some reason

**Comment by AndersonTorres** [comment]
> Tons of test failures for some reason

Something broke Staging again...

**Comment by hraban** [comment]
Nix question if you happen to know this: if I wanted to build this file as if it were transplanted into e.g. nixpkgs-unstable, what would be the way? The only thing I can think of is to create a copy of <nixpkgs>, patch in this one file, IFD that, then build .emacs from it... not very scalable if there are many changed files, among other things.

Is there some sort of .overrideFrom , which lets a pkgs.callPackage "reimport" a previous call with its own context?

**Comment by AndersonTorres** [comment]
If I am not misunderstanding you, it looks like an overlay.

https://ryantm.github.io/nixpkgs/using/overlays/
https://nixos-and-flakes.thiscute.world/nixpkgs/overlays
https://nixos.wiki/wiki/Overlays

**Comment by hraban** [comment]
But if I overlay 

> If I am not misunderstanding you, it looks like an overlay.
> 
> https://ryantm.github.io/nixpkgs/using/overlays/ https://nixos-and-flakes.thiscute.world/nixpkgs/overlays https://nixos.wiki/wiki/Overlays

I don't think that's quite the same;

```
$ nix build --print-build-logs --impure --expr 'let pnew = builtins.getFlake "github:nixos/nixpkgs/pull/291209/head"; pold = import <nixpkgs> { overlays = [ (self: super: { inherit (pnew.legacyPackages.${pold.system}) emacs; }) ]; }; in pold.emacs'
```

Will build this entire Emacs from staging, with all its dependencies from staging. I want to just try out your patch as if it were applied to my existing nixpkgs, say nixpkgs-unstable. So with everything as-is in pold. Not pulling in the world and rebuilding it based on its current position in pnew.

If anything it's more like a "reverse overlay" if that makes sense?

**Comment by jian-lin** [comment]
> just try out your patch as if it were applied to my existing nixpkgs, say nixpkgs-unstable

For this purpose, I use a local nixpkgs repo:
1. create a new branch starting at the commit of your current system
2. fetch patchs: `git fetch upstream pull/253227/head`
3. cherry-pick patches
4. build Emacs using that local nixpkgs repo

**Comment by hraban** [comment]
> > just try out your patch as if it were applied to my existing nixpkgs, say nixpkgs-unstable
> 
> For this purpose, I use a local nixpkgs repo:
> 
>     1. create a new branch starting at the commit of your current system
> 
>     2. fetch patches: `git fetch upstream pull/253227/head`
> 
>     3. cherry-pick patches
> 
>     4. build Emacs using that local nixpkgs repo

Same, but clearly a departure from how easy it is to do "forward overlays" if that makes sense. It's fine for dev I guess, but if I want to actually start using this in existing systems, this doesn't really work. Meanwhile I use PR-based overlays all the time in my own config.

**Comment by jian-lin** [comment]
> actually start using this in existing systems, this doesn't really work

I personally use flake so it is trivial to use a [forked nixpkgs](https://github.com/linj-fork/nixpkgs/tree/nixos-unstable-patched) to apply some PRs to my system.

Not sure what mean by "forward overlays" and "PR-based overlays" though.

**Comment by hraban** [comment]
> > actually start using this in existing systems, this doesn't really work
> 
> I personally use flake so it is trivial to use a [forked nixpkgs](https://github.com/linj-fork/nixpkgs/tree/nixos-unstable-patched) to apply some PRs to my system.
> 
> Not sure what you mean by "forward overlays" and "PR-based overlays" though.

Regular overlays. I also use flakes but I don't want to cherry-pick changes from a PR on my own branch, I just want to use the PR itself. Cherry-picking changes and manually keeping branches up-to-date is _distinctly_ different from the regular flow.

In the end they would both use overlays, and where they come from (flakes / fetchtarball etc) is irrelevant. I just don't want to mess with git and cherry-pick--that gets old fast.

E.g. in this case: I want to "reapply" the original call to `callPackage` that builds emacs, but from my own pkgs's `callPackage`. So instead of explicitly overriding certain arguments (which is `.override`), I want to do something more like.. `mypkgs.callPackage.inherit newpkgs.emacs29`, or whatever the syntax would be.

Anyway it's clear from this conversation that this functionality doesn't exist :P Thanks though!

**Comment by jian-lin** [comment]
> I don't want to cherry-pick changes from a PR on my own branch, I just want to use the PR itself

Maybe `applyPatches` is what you are looking for?
It works pretty well if
- you only use Nixpkgs packages but not other things such as modules
- your patches have no conflict (otherwise messing with git is inevitable)

> In the end they would both use overlays

I do not think overlays can be used to apply PRs which change modules.

**Comment by hraban** [comment]
> > I don't want to cherry-pick changes from a PR on my own branch, I just want to use the PR itself
> 
> Maybe `applyPatches` is what you are looking for? It works pretty well if
> 
>     * you only use Nixpkgs packages but not other things such as modules
> 
>     * your patches have no conflict (otherwise messing with git is inevitable)
The fact that it's a pr, or even in git at all, is a bit of a red herring. It's the wrong layer of abstraction to keep this generalizable. I was hypothesizing about a pure Nix solution.
> 
> > In the end they would both use overlays
> 
> I do not think overlays can be used to apply PRs which change modules.

It's a shame that there's no "reverse callPackage" functionality. 🤷

**Pull request closed without merging**
