### PR TITLE
nodePackages: 6_x -> 8_x

### PR DESCRIPTION
**Pull request by Mic92**
###### Motivation for this change

8_x is now the latest recommend lts version of node.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
```
@GrahamcOfBorg build altcoins.parity-ui azure-cli crashplansb create-cycle-app emojione fast-cli imapnotify lessc meguca npm2nix python36Packages.jupyterhub python36Packages.jupyterhub-ldapauthenticator python36Packages.oauthenticator quassel-webserver shout sloc statsd styx triton twemoji-color-font twitterBootstrap uchiwa wring
```

**Comment by Mic92** [comment]
darwin reports the following to be broken:

```
error: build of '/nix/store/491znz45c9yg0rw25v6ya21q56nhaz60-node-fast-cli-1.0.0.drv', '/nix/store/fmsl6wqk0vvk39jdchhyn2dn0kycqm2l-node-statsd-0.8.0.drv', '/nix/store/hdmp78b4krsag4hv5sx5nqs7k60nr6f6-node-quassel-webserver-2.2.8.drv', '/nix/store/j8ixc37gvfwkbgbala2q196mgdzk7w7j-node-azure-cli-0.10.19.drv' failed
```

**Comment by Mic92** [comment]
@GrahamcOfBorg build  quassel-webserver

**Comment by Mic92** [comment]
@GrahamcOfBorg build twemoji-color-font

**Comment by Mic92** [comment]
On my system CrashPlanSmb and twitter-bootstrap fails to build:

```
Unable to load plugin O2 please make sure that it is installed under or at the same level as less
builder for '/nix/store/db0sig0sja0hp6pyh0sxcv7fb804jq6y-twitter-bootstrap-2.3.2.drv' failed with exit code 1
error: build of '/nix/store/6a76vf26jmrig0hpq5zbmk0h1ndmvks5-CrashPlanSmb_6.7.0_1512021600670_4503.drv', '/nix/store/db0sig0sja0hp6pyh0sxcv7fb804jq6y-twitter-bootstrap-2.3.2.drv' failed
```

**Comment by Mic92** [comment]
cc @xvapx regarding crash plan (this is not part of nodePackages itself).

**Comment by Mic92** [comment]
boostrapTwitter is removed here: https://github.com/NixOS/nixpkgs/pull/45704/files

**Comment by xvapx** [comment]
@Mic92 I'm looking into it

**Comment by xvapx** [comment]
@Mic92 crashplan is broken, I've opened #45735.

**Pull request merged**
