### PR TITLE
nixos/caddy: update ca option

### PR DESCRIPTION
**Pull request by jlesquembre**
###### Motivation for this change

The generated json configuration returns this warning:
the 'issuer' field is deprecated and will be removed in the future; use 'issuers' instead

Updated the config to use "issuers" instead of "issuer"

Also, now it's possible to set the ca option null to not inject
automatically any ca. This is useful if you don't want to generate any
certificates or if you want to define a more fine-graned ca config
manually (e.g.: use different ca per domain)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

ping @Br1ght0ne @sephii

### CODE REVIEW

**Comment by aanderse** [comment]
**DARN**
Mouse slipped and I clicked merge. Never happened to me before... I was about to say this:

@davidak do you know anything about `caddy` to review this? Unfortunately I have never used it...

**Comment by davidak** [comment]
@aanderse no problem. that can happen

yes, i use caddy on my servers and can try to review it

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 133671` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 test built:</summary>
  <ul>
    <li>nixosTests.caddy</li>
  </ul>
</details>

**Review by davidak — COMMENTED** [review]
the changes look sane.

the actual  change is very small, most is indentation

it still builds and the test runs successfully, so it does generate a valid config

**Comment by aanderse** [comment]
Thank you so much @davidak!

**Comment by jlesquembre** [comment]
@aanderse @davidak thanks to both of you

just to recap the changes, other than the indentation (because I added an extra if conditions) there are 2 changes:
- The "issuer" field in TLS automation policies was changed to "issuers" (The singular form was deprecated on v2.3.0, see [caddy 2.3.0 release notes](https://github.com/caddyserver/caddy/releases/tag/v2.3.0)
- Related to that change, now it's possible to set the `ca` option to null. That way, nix will not add any issuers automatically, which  makes sense in more complex configurations.

**Pull request merged**
