### PR TITLE
sqlite3: 3.14.1 -> 3.15.0

### PR DESCRIPTION
**Pull request by wmertens**
###### Motivation for this change

Row values allow paging without offset :)
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [x] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Tested on Darwin

### CODE REVIEW

**Comment by wmertens** [comment]
As a bonus, I enabled FTS5 which seems like an awesome full-text search extension. See it in use at http://charlesleifer.com/blog/using-the-sqlite-json1-and-fts5-extensions-with-python/#fts5-with-python

**Comment by wmertens** [comment]
@edolstra any objections?

**Comment by Mic92** [comment]
I had to add libm to the link flags for fts5 on nixos:

```patch
diff --git a/pkgs/development/libraries/sqlite/default.nix b/pkgs/development/libraries/sqlite/default.nix
index 57ec463..cc99b8d 100644
--- a/pkgs/development/libraries/sqlite/default.nix
+++ b/pkgs/development/libraries/sqlite/default.nix
@@ -47,6 +47,8 @@ stdenv.mkDerivation {
       export NIX_CFLAGS_COMPILE="$NIX_CFLAGS_COMPILE -DUSE_PREAD64 -D_LARGEFILE64_SOURCE"
     fi
 
+    export NIX_LDFLAGS="$NIX_LDFLAGS -lm"
+
     echo ""
     echo "NIX_CFLAGS_COMPILE = $NIX_CFLAGS_COMPILE"
     echo ""
```

**Comment by wmertens** [comment]
Thanks @Mic92!

I added that line and confirmed it to build, so since now it's tested on Linux and Darwin and there were no objections I'm merging.

**Pull request merged**
