### PR TITLE
[wip] k3s: 1.22.3+k3s1 -> 1.23.3+k3s1

### LINKED ISSUE #156615: k3s: update script is broken
Due to changes to K3s's download script update script is currently broken.

Currently I plan fixing the update script after #158089 is merged.

### PR DESCRIPTION
**Pull request by superherointj**
Closes #156615

THIS IS AN EARLY DRAFT

Building K3s is currently broken so I'm attempting to use buildGoModule instead. It is broken still. Trying to sort out things out. And Yes, I have no idea on what I'm doing. And
I wouldn't mind keeping things as they are if updates weren't broken.

I'll try to mimic this (haven't yet):
https://github.com/k3s-io/k3s/blob/master/scripts/build

UPDATE:
K3s builds when using buildGoModule. But tests are failing still.

Code I'm using:

pkgs/applications/networking/cluster/k3s/default.nix
```
let
  k3sVersion = "1.23.3+k3s1";     # k3s git tag
  k3sCommit = "5fb370e53e0014dc96183b8ecb2c25a61e891e76"; # k3s git commit at the above version
  k3sRepoSha256 = "0vlsqy4iccjmf4nslmr0a7w5pbb4891j2qk5dr5fsbvgdnq6xm6i";
in
    buildGo117Module rec {
      name = "k3s";
      version = k3sVersion;

      src = fetchgit {
        url = "https://github.com/k3s-io/k3s";
        rev = "v${k3sVersion}";
        sha256 = k3sRepoSha256;
      };

      vendorSha256 = "sha256-9+2k/ipAOhc8JJU+L2dwaM01Dkw+0xyrF5kt6mL19G0=";

      subPackages = [ "." ];

      passthru.tests = { inherit (nixosTests) k3s-single-node k3s-single-node-docker; };
    }
```

Please *ignore*:
1) Update script
2) Patch
3) Traefik
4) Junk

Tests are breaking as:

nix build .#k3s.passthru.tests.k3s-single-node
```
Error: unknown command "kubectl" for "kubectl"
Exception: command `k3s kubectl cluster-info` failed (exit code 1)
```
Full logs: https://termbin.com/gi7p

I've added a wrapper, and the wrapper when tested in ./result/bin/* seems fine. The applications are executed as expected.

@euank @bryanasdev000

### CODE REVIEW

**Comment by euank** [comment]
I like the idea of switching to buildGoModule if we can.
I'm pretty sure when I first packaged this, it wasn't using go modules yet upstream, so that wasn't an option.
It looks like upstream is using go modules now, so we might be able to switch.

Unfortunately, most of the complexity isn't captured in this PR yet, so there's still work to do.

I'll try to outline the steps that k3s goes through upstream, and what challenges we have mimicing it, which I think might help explain the state of what we had, and why I think this PR is still missing some stuff.

## How k3s is built upstream

Firstly, [scripts/ci](https://github.com/k3s-io/k3s/blob/v1.23.3%2Bk3s1/scripts/ci) is the sorta default "here's how k3s is built". If you just run 'make' in the k3s repo, that's the script that's run to build the final binary.

It has three steps that we care about: download, build, and package. Let's look at each of those three steps.

### download

[This script](https://github.com/k3s-io/k3s/blob/v1.23.3%2Bk3s1/scripts/download).

Effectively, this downloads:

1. The traefik chart, which will be referenced in 'package'
2. a 'k3s-root' release, also referenced in 'package'
3. source code for containerd & runc, referenced in 'build'

These can be modeled in nixpkgs as fetchurl / fetchFromGitHub / etc.

We'll come back to these in build/package steps where they're actually used.

### build

[This step](https://github.com/k3s-io/k3s/blob/v1.23.3%2Bk3s1/scripts/build).

The goal of 'build' is to produce the following binaries:
1. 'bin/k3s' (from `./cmd/server`; formerly [called 'bin/containerd'](https://github.com/k3s-io/k3s/pull/4757#pullrequestreview-833512138) confusingly) -- This is most of the binaries k3s bundles, all as one multi-call binary. Confusingly, this is _not_ the final k3s binary you run as a user (also named 'k3s'), but rather this is one layer down. I'll explain this below.
2.  `bin/cni` (from `github.com/rancher/plugins.git`) -- This is all the CNI plugins k3s supports
3. `bin/containerd` -- I think this used to be part of `bin/k3s`, but [got split out](https://github.com/k3s-io/k3s/blob/v1.23.3%2Bk3s1/docs/adrs/002-standalone-containerd.md).
4. `bin/runc`

So, in 1 above I mentioned that this isn't the final k3s binary. The reason for this is that k3s operates in a kinda weird way. When you run `k3s kubectl --version`, what happens is:

1. k3s creates a data dir and extracts kubectl to it (`$HOME/.rancher/k3s/data/$hash` or `/var/lib/rancher/k3s/data/$hash` for root)
2. k3s runs $dataDir/bin/kubectl

What this PR is currently doing is building the 'bin/k3s' mentioned above, which is _not_ the thing that normally gets shipped, hence why we have 'kubectl command not found' etc.

Anyway, on to package.

### package

The important parts are in [package-cli](https://github.com/k3s-io/k3s/blob/v1.23.3%2Bk3s1/scripts/package-cli).

This does the following:

1. Create `./build/data/${HASH}.tar.zst`, which is a tarball of `bin/k3s`, `/bin/cni`, `./bin/containerd`, `./bin/runc`, all the multi-call symlinks (bin/kubectl etc), and some config data.
2. run 'go generate', which takes 'build/data/$HASH.tar.zstd', the k3s-root mentioned above, and the traefik chart mentioned above, and uses 'bindata' to turn them into go source code (giant byte array consts more or less). See [pkg/codegen](https://github.com/k3s-io/k3s/blob/5fb370e53e0014dc96183b8ecb2c25a61e891e76/pkg/codegen/main.go#L19).
3. build the final 'k3s' command from `./cmd/k3s/main.go`. This includes the compiling in the go-bindata generated data.tar.zstd mentioned above.

The end result of this build is now the actual binary that people usually think of as the 'k3s' binary.

## What does this mean for nixpkgs packaging of k3s?

The main challenge we have building k3s comes from the 'data.tar.zstd' step. Basically, the final k3s binary has a giant compressed blob in it, and that blob contains binaries which may be dynamically linked (in fact are dynamically linked in the previous k3s build. Upstream they're not, but nixpkgs can get away with more dynamic linking and probably should).

The compression means that we have to propagate any dynamically linked contents of that tarball (cni, k3s, containerd, runc).
The easiest way to do that seems to be modeling those contents as a separate nix derivation and using ['propagatedBuildInputs'](https://github.com/NixOS/nixpkgs/blob/529051ddb4bbf61dd308a13478d54cb576429b81/pkgs/applications/networking/cluster/k3s/default.nix#L190-L192).

### What alternatives do we have?

There are a few different things we can think about doing to make things easier here. First of all, we can consider whether we use upstream's exact commits for runc & containerd, or whether we use the existing nixpkgs ones. We could probably just include a symlink in the tarball, propagate the input, and not even have to duplicate the data. This seems like it's a good idea for runc (since k3s doesn't carry runc patches). For containerd, I think they're planning to move it back into the multi-call binary, and so it's probably diverging a step too far.

We also need to figure out if buildGoModule can actually work for us or not. I'm pretty confident it can work for the 'build' bit (what this PR already does), but I'm not 100% sure if it can work for the 'package' step. That step requires that we have run `go generate` at some point. Maybe we can model it as `k3s-build`, and then do a separate derivation that transforms `$src` to `go-generated-source`, which would be an intermediate derivation that is $src + k3s-build binaries + go generate, and that src is used for the final `package` `buildGoModule`? That seems like it might work.

-----

Anyway, that's kinda my thought dump about how upstream builds this and the troubles nixpkgs faces in mimicing it.

I do think we're forced to mimic the packaging setup somewhat closely, or else we don't really have k3s anymore at all.

All that said, thanks a ton for spending some time looking at this! I'm happy to help update this further since the packaging is sorely in need of some improvements, and it's clear upstream made some changes which necessitate doing them sooner rather than later.

**Comment by superherointj** [comment]
@euank Thanks for the comprehensive answer. I had no idea of some the things you mentioned. Really happy to have you here!

> the 'package' step requires that `go generate` at some point. Maybe we can model it as `k3s-build`, and then in the final buildGoModule derivation, we can do a `preBuildPhase` that copies in the binaries and runs `go generate`? That seems like it might work.

In Linkerd, I have succesfully used `go generate` in buildGoModule, as:
```
  preBuild = ''
    env GOFLAGS="" go generate ./viz/static
  '';
```
*GOFLAGS="" was necessary for Linkerd but may not be necessary here.

> I do think we're forced to mimic the packaging setup somewhat closely, or else we don't really have k3s anymore at all.

Sure.

> All that said, thanks a ton for spending some time looking at this! I'm happy to help update this further since the packaging is sorely in need of some improvements, and it's clear upstream made some changes which necessitate doing them sooner rather than later.

Your contribution here is very important. Your awareness of K3s inner workings is much better than mine. If I were to fully re-package K3s myself likely you'd have to patch it too much. It might be more productive if you could fix the packaging. And I'd fix the auto-update script. Let me know.

**Comment by euank** [comment]
I should have some time to go through the update sometime this week. I'll give it a go, and report back here.

**Comment by euank** [comment]
I got a draft PR up over here that seems to mostly work: https://github.com/NixOS/nixpkgs/pull/158089

It switches to `buildGoModule`, and it feels mildly better than the previous derivation, but it still has a couple patches, and still feels somewhat complicated.

My current plan is to fix the few remaining bits (which I've noted on that draft PR), switch my own k3s cluster to it, and if those things both go well I'll move it out of draft.

**Comment by superherointj** [comment]
Closed in favor of #158089

**Pull request closed without merging**
