### PR TITLE
Interactive `env` for developing Agda packages, and misc cleanup

### PR DESCRIPTION
**Pull request by Ericson2314**
- The first commit is what @Fuuzetsu wanted in the comments for https://github.com/NixOS/nixpkgs/pull/7769.
- The second commit makes the unreadable diff but has no effect on the evaluated expression.
- The third commit does just what it says it does.
- The forth commit is the only part that needs real testing. hence the [WIP]. Since I believe no package used added `null`s that `preprocess` would removed, travis should hopefully move quickly.

### CODE REVIEW

**Comment by Ericson2314** [comment]
Looks like build was killed for taking too long.

**Comment by vcunat** [comment]
For people interested in Agda, there seems to be an important regression: http://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.AgdaStdlib.x86_64-linux

**Comment by Fuuzetsu** [comment]
@vcunat no regression, just the stdlib package needs updating. When I was testing 2.4.2.3 rc, the state of the matter was that you had to check out a specific branch from the repo. If it's tagged properly now then we can just update the package and it will work.

**Comment by vcunat** [comment]
Well, by "regression" I meant: it used to build recently and doesn't anymore (according to Hydra).

**Comment by Fuuzetsu** [comment]
@vcunat 7c09d9d2915317580e14733cde839f88b08a5718 should do it

**Comment by jagajaga** [comment]
cc @oxij

**Comment by Ericson2314** [comment]
Ok, build all the Agda libs myself so I'm removing the WIP.

**Comment by Ericson2314** [comment]
Hey all, any feedback on this? At least the first 2 commits should be pretty uncontroversial.

**Comment by Fuuzetsu** [comment]
Sorry, slipped my mind. You should always feel free to nag me about such things, the likelyhood of me forgetting is pretty high… Everything looks fine just wanted to test it a bit but I can take your word that it works. We can always revisit in the future if it does not as we don't have that many Agda users yet.

**Comment by Ericson2314** [comment]
Thanks @Fuuzetsu, and no worries, I just figured we were waiting for oxij to comment or something.

**Pull request merged**
