### PR TITLE
yubikey-manager: 4.0.9 -> 5.0.0

### PR DESCRIPTION
**Pull request by afh**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Lassulus** [comment]
Result of `nixpkgs-review pr 198958` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>gen-oath-safe</li>
    <li>yubikey-manager</li>
    <li>yubikey-manager-qt</li>
    <li>yubioath-desktop</li>
  </ul>
</details>

**Comment by Lassulus** [comment]
hmm, getting errors when running `ykman-gui`
```
qml: qrc:/qml/YubiKey.qml:208: TypeError: Cannot read property 'success' of undefined
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
qml: Function not found: 'yubikey.controller.refresh' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: qrc:/qml/YubiKey.qml:208: TypeError: Cannot read property 'success' of undefined
```

**Comment by afh** [comment]
Thanks for testing @Lassulus, much appreciated!

The major version change of yubikey-manager indicates breaking changes to prior versions, so it doesn't surprise me that [yubikey-manager-qt](https://github.com/Yubico/yubikey-manager-qt), which has not seen a release or updates in about a year, doesn't work with yubikey-manager 5.x (see also [yubikey-manager-qt#328](https://github.com/Yubico/yubikey-manager-qt/issues/328)).

First thing that comes to mind is to copy the current, i.e. prior to the changes in this PR, `yubikey-manager/default.nix` to `yubikey-manager/40.nix`, declare `yubikey-manager40` in `pkgs/top-level/all-packages` based on `40.nix` and make the yubikey-manager-qt derivation depend on that.

What do you think?
In case you agree that the changes outlined above are a viable path forward I'm happy to amend this PR accordingly.

**Comment by Lassulus** [comment]
sounds good, I guess yubikey-manager4 is good enough? since there was no 4.1.* ideally we would remove the old version anyways after the gui is updated.

**Comment by afh** [comment]
Thanks for the quick response, @Lassulus.

I agree `yubikey-manager4` is good enough and yes, once `yubikey-manager-qt` is updated to support yubikey-manager 5.x the `yubikey-manager4` derivation should be removed.

The changes in this PR have been updated to accordingly to earlier comments and I look forward to your review and further comments :)

**Comment by Lassulus** [comment]
Result of `nixpkgs-review pr 198958` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>gen-oath-safe</li>
    <li>yubikey-manager</li>
    <li>yubikey-manager4</li>
    <li>yubioath-desktop</li>
  </ul>
</details>

**Comment by Lassulus** [comment]
thanks for taking care!

**Comment by afh** [comment]
Thanks for merging @Lassulus, much appreciated 🙏

**Pull request merged**
