### PR TITLE
tor-browser: use system install & simplify wrapper

### LINKED ISSUE #91925: tor-browser-bundle-bin: Input method integradion does not work
**Describe the bug**
Input method does not work in torbrowser `tor-browser-bundle-bin` version `9.5`.

**To Reproduce**
1. Add it with home-manager or `nix-env`.
2. Type command `torbrowser` 
3. Try switching ~~fcitx~~fcitx5 input method engines.

**Expected behavior**
Dvorak and Chewing installed with fcitx can be used in Tor Browser.

**Screenshots**

**Additional context**
It starts from version `9.5`. (Thanks a lot to all the people that make 9.5 available!)
The input method framework I'm using is ~~fcitx~~ (now fcitx5).
I'm not sure if it is an upstream issue, nor if it is on purpose (to harden or something).

**Notify maintainers**

@offlinehacker @matejc @doublec @thoughtpolice @joachifm @hax404 @scaredmushroom 

**Metadata**
(`nix-shell -p nix-info --run "nix-info -m"` result)
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.43, NixOS, 20.09pre228204.467ce5a9f45 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.5`
 - channels(root): `"nixos-20.09pre231796.22a81aa5fc1"`
 - channels(shamrock): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: tor-browser-boundle-bin, torbrowser
# a list of nixos modules affected by the problem
module:
```

### LINKED ISSUE #272670: `fcitx5` unable to work in `tor-browser` in `xfce`
### Describe the bug
`fcitx5` unable to work in `tor-browser` in `xfce`

Fcitx5 is an [nput method framework with a lightweight core, offering additional language support via addons, like Japanese, Korean and Chinese. Without it, we cannot type Japanese, Korean, and Chinese.

However, `fcitx5` is working fine with other browser like `firefox`
Is the nixpkgs version or `tor-borwser` implemented some kind of sandbox so that fcitx5 is not working with it?

### Expected behavior
Japanese, Korean or Chinese can be typed with `fcitx5` in `tor-browser`

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.61-hardened1, NixOS, 23.11 (Tapir), 23.11.20231202.933d7dc`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"home-manager-23.11.tar.gz, nixos-23.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by felschr**
## Description of changes
The `tor-browser` package uses a complex wrapper around the binary that provides some isolation.
I want to start a discussion whether this really adds any benefit.

Some downsides of the wrapper:
- it creates and uses a default profile; other profiles cannot be used (see #243605)
- it adds quite a bit of complexity
- the wrapper differs a lot from the simple one in `mullvad-browser`

My suggestion would be to use a system installation (by creating a `system-install` besides the binary) with a simple `makeWrapper` for the `tor-browser` package, which also aligns it even more with the `mullvad-browser` package. If a user really requires more isolation than the default Tor Browser installation, they should probably create their own wrapper. That's just my opinion, though. I'm open to other suggestions.

The Tor Browser directory changes to `~/.tor project/firefox`, which is a breaking change (although most Tor Browser users probably don't mind losing their state).

Fixes #91925, fixes #272670

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by felschr** [comment]
I just noticed that 23.11 feature freeze is in 3 days, so not sure if we can still get this ready in time.
@panicgh, what are your thoughts on these changes?

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by felschr** [comment]
Added some finishing touches & personally I'm happy with these changes.

This PR is based on the changes on https://github.com/NixOS/nixpkgs/pull/256934 and should only be merged afterwards.
The new commits in this PR are: 1076d32a31c9cf22ca9abdfd3d5808708d2f2de1 b6d00b155102ad731d7c6ff32cb75e57f38f11c8

**Comment by rhendric** [comment]
> The Tor Browser directory changes to `~/.tor project/firefox`

So becomes less XDG-Base-Directory-compliant? :frowning_face:

**Comment by felschr** [comment]
> So becomes less XDG-Base-Directory-compliant? ☹️

I haven't found a way to change this directory, except via a build flag.
But since this is a binary distribution, I can't change that unfortunately.

**Comment by rhendric** [comment]
The current wrapper seems to manage it somehow. I'm not an expert on how TBB works or all of the tradeoffs you're looking at; I just don't like seeing this thing that I care about regress in order to fix things of dubious relevance to me.

**Comment by felschr** [comment]
@panicgh your thoughts?

**Comment by panicgh** [comment]
I don't feel competent enough to judge for or against this proposal.

**Comment by felschr** [comment]
The simplified wrapper fixes some issues like #272670 / #272972.
Another thing I noticed is that it enables support for the compact title bar (on Gnome at least).

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
One thing I just noticed, that under wayland there is no icon in the kde taskbar.

**Comment by felschr** [comment]
> One thing I just noticed, that under wayland there is no icon in the kde taskbar.

I fixed the desktop file. Seems that on Wayland icon are always derived from desktop fiels:
https://nicolasfella.de/posts/fixing-wayland-taskbar-icons/

But I haven't tested this yet.

**Review by SuperSandro2000 — APPROVED** [review]
works like a charm now

**Comment by felschr** [comment]
@SuperSandro2000
So, is the `~/.local/share/tor-browser/TorBrowser/Data/Browser/` -> `~/.tor project/firefox/` change fine like this?
Should we add a release notes entry?

Any chance we can even backport this, since it also fixes some issues (#91925, #272670)?

**Review by marsam — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
> So, is the `~/.local/share/tor-browser/TorBrowser/Data/Browser/` -> `~/.tor project/firefox/` change fine like this?
> Should we add a release notes entry?

I didn't test it indepth but it seemed to work for me. 😅 I don't know if we break tor logins (forget how they are called) or custom settings

**Comment by ShamrockLee** [comment]
Could we backport this one? This change vastly improves the UX for people who use input methods.

**Comment by SuperSandro2000** [comment]
This should have been backported to 23.11 already.

**Comment by ShamrockLee** [comment]
> This should have been backported to 23.11 already.

Oops! Thanks for reminding.

**Pull request merged**
