### PR TITLE
davinci-resolve: add street to fix build

### PR DESCRIPTION
**Pull request by orivej**
## Description of changes

Fixes build after #274007

Without the street the build fails with:

```
downloadid is f38fc270c4c040bea4782182d0fbb367
resolveurl is Error: Must register to be able to perform the download
curl: (3) URL rejected: Malformed input to a URL function
```

If you've already build this version of davinci-resolve, in order to test this change you need to change the fixed outputHash.

/cc @amarshall for testing

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by amarshall — APPROVED** [review]
Verified:

- Failure of non-studio without this change
- Success of non-studio and studio with this change
- Hash is unchanged, so did not bother to verify beyond the download

**Review by chewblacka — APPROVED** [review]

**Comment by chewblacka** [comment]
Closes https://github.com/NixOS/nixpkgs/issues/282182

**Review by kristoff3r — APPROVED** [review]

**Review by nrabulinski — APPROVED** [review]

**Review by TethysSvensson — APPROVED** [review]

**Comment by h7x4** [comment]
The changes look good, but could you split the part where you add yourself as maintainer into another commit?

**Comment by TethysSvensson** [comment]
> The changes look good, but could you split the part where you add yourself as maintainer into another commit?

Personally I think it's very unhelpful to nitpick fixes to packages that are obviously broken.

Would it be better if this was split up? Probably. Does it matter enough that we want to delay getting a fix out? In my opinion, no.

**Comment by h7x4** [comment]
I see where you're coming from, but I do not generally consider creating commits for each logical unit to be a nitpick. In this case, it's probably insignificant enough to prioritize merging though.

**Pull request merged**
