### PR TITLE
prisma-engines: 4.11.0 -> 4.12.0

### PR DESCRIPTION
**Pull request by ivan**
###### Description of changes

https://github.com/prisma/prisma-engines/compare/4.11.0...4.12.0

https://github.com/prisma/prisma/releases/tag/4.12.0

I removed `"-p" "introspection-core"` because introspection-core is gone in prisma-engines.

I copied `Cargo.lock` from prisma-engines@4.12.0.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

cc maintainers @pamplemousse @pimeys @tomhoule

### CODE REVIEW

**Comment by tomhoule** [comment]
It doesn't relate directly to this PR, but I don't understand why we have a committed Cargo.lock in nixpkgs now, it wasn't the case until very recently and I didn't get a notification when that happened. Git blame points to 0f2c778f2 but that's not super helpful. Does anybody have more context?

Otherwise the PR looks good to me. You might want to update nodePackages.prisma too.

**Comment by tomhoule** [comment]
Ok found when and how that happened: https://github.com/NixOS/nixpkgs/pull/221716

**Comment by ivan** [comment]
@pimeys thanks for the review. I updated the hash for nodePackages.prisma now.

**Review by pimeys — APPROVED** [review]

**Comment by lucasew** [comment]
Result of `nixpkgs-review pr 223700` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>prisma-engines</li>
  </ul>
</details>

**Review by tomhoule — APPROVED** [review]

**Pull request merged**
