### PR TITLE
syncthing: 0.11.13 -> 0.11.15

### PR DESCRIPTION
**Pull request by ctheune**

### CODE REVIEW

**Comment by jagajaga** [comment]
Could you please rename commit's name to  `syncthing: 0.11.13 -> 0.11.15`?

**Comment by ctheune** [comment]
Done!

**Comment by ctheune** [comment]
Damn.

**Comment by jagajaga** [comment]
No. Not the PR's name but the commit's one.
You can do it by doing
```
git rebase -i HEAD~2
```
And do force push after that.

**Comment by ctheune** [comment]
I think I got it - better now?

Thanks for the pointer!

**Comment by jagajaga** [comment]
Awesome, thank you :)

**Pull request merged**
