### PR TITLE
buho: Add missing dependencies

### PR DESCRIPTION
**Pull request by onny**
###### Description of changes

Add dependencies which were accidentally missing in a previous PR for the app buho https://github.com/NixOS/nixpkgs/pull/153838  

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dotlambda** [comment]
@ofborg build buho

**Review by dotlambda — CHANGES_REQUESTED** [review]
Commit messages should start with `libsForQt5.`

**Comment by SuperSandro2000** [comment]
Also it would be great to use the libraries in this PR.

**Comment by dotlambda** [comment]
> Also it would be great to use the libraries in this PR.

They are already being used: #153838

**Comment by SuperSandro2000** [comment]
> > Also it would be great to use the libraries in this PR.
> 
> They are already being used: #153838

How is ofborg not complaining about this?

**Comment by dotlambda** [comment]
> How is ofborg not complaining about this?

That's what I was wondering too: https://github.com/NixOS/nixpkgs/pull/153838#issuecomment-1107934589

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 170251` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>libsForQt512.mauikit-accounts</li>
    <li>libsForQt512.mauikit-texteditor</li>
    <li>libsForQt514.mauikit-accounts</li>
    <li>libsForQt514.mauikit-texteditor</li>
  </ul>
</details>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>buho</li>
    <li>libsForQt5.mauikit-accounts (libsForQt515.mauikit-accounts ,plasma5Packages.mauikit-accounts)</li>
    <li>libsForQt5.mauikit-texteditor (libsForQt515.mauikit-texteditor ,plasma5Packages.mauikit-texteditor)</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
> Commit messages should start with `libsForQt5.`

ping @onny

**Comment by onny** [comment]
Sorry I'm currently struggling with this commit. Unfortunately QT5 apps or especially Mauikit apps crash in my user configuration and I'm not sure why. When trying to run apps on `nixos-shell` insde a virtual machine, I cannot get a graphical session with QT support working.
So maybe I'll have to use a different machine with a "fresh" install of NixOS to get it to work again :)

**Comment by dotlambda** [comment]
@onny Everything but the incons works for me, so I would merge it with the changed commit messages.

**Pull request merged**
