### PR TITLE
mitmproxy: convert to python3Packages

### PR DESCRIPTION
**Pull request by veehaitch**
###### Motivation for this change

For the [scripting API of mitmproxy](https://docs.mitmproxy.org/stable/addons-scripting/), it is useful to have it available as Python module:
- Converted mitmproxy to a Python 3 package
- I've also removed the following dependencies which are apparently not required (any more):
  * cffi
  * h11
  * hpack
  * itsdangerous
  * jinja2
  * markupsafe
  * publicsuffix2
  * pycparser
  * six
  * werkzeug
- Tests run fine on NixOS
- ~mitmproxy v5.2 is already out but apparently it has issues with urwid 2.1: https://github.com/mitmproxy/mitmproxy/pull/4086~ 
- Updated mitmproxy to v5.2

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by kamilchm — APPROVED** [review]

**Comment by FRidh** [comment]
It is likely the module will break at times because dependencies cannot be met, which can be overridden as an application. In the past dependencies had to be overridden quite often, so I am a bit skeptical to this change. Not blocking it though.

**Comment by veehaitch** [comment]
> It is likely the module will break at times because dependencies cannot be met, which can be overridden as an application. In the past dependencies had to be overridden quite often, so I am a bit skeptical to this change. Not blocking it though.

I see your point; actually, exactly this is what happened for Mitmproxy v5.2 which downgraded urwid. Guess we have to skip this version and wait for 5.2.1. Still, IMHO, its the better option to have a Python package here.

**Comment by veehaitch** [comment]
I've updated mitmproxy to v5.2 since upstream introduced support for urwid v2.1.1.

**Comment by FRidh** [comment]
> I see your point; actually, exactly this is what happened for Mitmproxy v5.2 which downgraded urwid. 

Well, then I take it you accept it that there may be periods of time it is not possible to have a functioning mitmproxy in Nixpkgs.

**Comment by veehaitch** [comment]
> > I see your point; actually, exactly this is what happened for Mitmproxy v5.2 which downgraded urwid.
> 
> Well, then I take it you accept it that there may be periods of time it is not possible to have a functioning mitmproxy in Nixpkgs.

There might be some quirks, yes. But this also holds true for other Python packages in Nixpkgs, doesn't it?

**Comment by jonringer** [comment]
@veehaitch that's correct. Due to how python can only import one version of a module, introducing many versions of a given dependency is not feasible, and will likely break some users depending on which packages are introduced.

**Comment by risicle** [comment]
> Due to how python can only import one version of a module, introducing many versions of a given dependency is not feasible

@jonringer I've been thinking about the fundamental "why?"s of this lately, because I realized that it's not as if even c allows you to "import" (link to) more than one version of a library at once. And we don't have this "one version" stipulation with `pkgs/development/libraries/`. I think the difference really is that with python we expect to be able to compose an arbitrary collection of python packages together into an env and for it to "just work", a common python pattern that doesn't have a straight equivalent in the world of c libraries.

Anyway as far as I'm concerned, this is something that you've removed from my todo list, @veehaitch.

Though I think you might have got the patch's hash wrong. And it's always nice to give `fetchpatch` patches a name, e.g. `name = "urwid-lt-2.1.0.patch";`

And this'll need a rebase so that it survives the big `python-packages.nix` sort of 2020.

Otherwise WFM macos 10.14. :+1:

**Review by risicle — APPROVED** [review]

**Comment by veehaitch** [comment]
> Though I think you might have got the patch's hash wrong (I get 1z5r8izg5nvay01ywl3xc6in1vjfi9f144j057p3k5rzfliv49gg). And it's always nice to give fetchpatch patches a name, e.g. name = "urwid-lt-2.1.0.patch";

Indeed, thanks! Done.

> And this'll need a rebase so that it survives the big python-packages.nix sort of 2020.

Done.

Additionally, the derivation now runs all the tests except one. All tests pass on NixOS. Builds and works on macOS 10.15.6.

**Review by jonringer — APPROVED** [review]
LGTM

```
https://github.com/NixOS/nixpkgs/pull/93701
2 packages built:
mitmproxy python37Packages.mitmproxy
```

**Pull request merged**
