### PR TITLE
cool-retro-term: add missing dependencies and fix qmltermwidget, fixes #12027

### LINKED ISSUE #12027: Cool-retro-term fails to run
After running `$ nix-env -i cool-retro-term`, cool-retro-term doesn't seem to work. When attempting to run, it outputs errors and hangs:

```
$ cool-retro-term --verbose
QQmlApplicationEngine failed to load component
qrc:/main.qml:23 module "QtQuick.Controls" is not installed
qrc:/main.qml:24 module "QtGraphicalEffects" is not installed
qrc:/main.qml:23 module "QtQuick.Controls" is not installed
qrc:/main.qml:24 module "QtGraphicalEffects" is not installed
```

This is on the current nixos-unstable channel:

```
$ nixos-version 
16.03pre73316.93d8671 (Emu)
```

### PR DESCRIPTION
**Pull request by svenkeidel**
This fixes #12027 at least for me. @ttuegel, @kragniz, let me know if it also works for you.

Best,
Sven

### CODE REVIEW

**Comment by nckx** [comment]
:+1: Works here.

**Comment by kragniz** [comment]
:+1: I can confirm this fixes #12027.

**Comment by svenkeidel** [comment]
I have no commit bit, can someone with commit rights please merge this. Thanks.

**Comment by nckx** [comment]
Sure.

**Pull request merged**
