### PR TITLE
petsc: 3.17.4 -> 3.19.1, fixed build and quicktests

### PR DESCRIPTION
**Pull request by yl3dy**
###### Description of changes

Fixed PETSc build. Versions earlier than 3.18.6 fail because of incorrect make option generation, newer ones required a patch for quicktests to ignore MPI messages about missing network. Updated to the most recent version and added a patch.

See the relevant bug report: https://github.com/NixOS/nixpkgs/issues/229328

ZHF: https://github.com/NixOS/nixpkgs/issues/230712

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by yl3dy** [comment]
Result of `nixpkgs-review pr 233410` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>getdp</li>
    <li>petsc</li>
  </ul>
</details>

**Comment by RaitoBezarius** [comment]
Result of `nixpkgs-review pr 233410` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>getdp</li>
    <li>petsc</li>
  </ul>
</details>

**Comment by RaitoBezarius** [comment]
Result of `nixpkgs-review pr 233410` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Comment by RaitoBezarius** [comment]
Result of `nixpkgs-review pr 233410` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Review by RaitoBezarius — APPROVED** [review]

**Comment by yl3dy** [comment]
@RaitoBezarius Should I add the backport label? Or the branchoff hasn't happened yet?

**Comment by RaitoBezarius** [comment]
The branch-off didn't happen yet ;)
-- 

Ryan Lahfa

**Pull request merged**
