### PR TITLE
font-awesome: 6.4.2 -> 6.5.2

### PR DESCRIPTION
**Pull request by afresquet**
## Description of changes

[Changelog](https://fontawesome.com/docs/changelog/)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by singatias** [comment]
Hi @afresquet, I was about to do the same thing but I didn't figure out where is the sha256sum is coming from, I downloaded the official package from font-awesome website for the desktop .zip and I was wondering what to do in case I want to help maintainers updating packages when needed.

Thank you :)

**Comment by afresquet** [comment]
> Hi @afresquet, I was about to do the same thing but I didn't figure out where is the sha256sum is coming from, I downloaded the official package from font-awesome website for the desktop .zip and I was wondering what to do in case I want to help maintainers updating packages when needed.
> 
> Thank you :)

Hello, I used [nurl](https://github.com/nix-community/nurl), the command and output look like this:
```sh
$ nix run nixpkgs#nurl -- https://github.com/FortAwesome/Font-Awesome/ 6.5.1
fetchFromGitHub {
  owner = "FortAwesome";
  repo = "Font-Awesome";
  rev = "6.5.1";
  hash = "sha256-fwMr7af/YUmkb83JFo+KlDQCYXazAYxlbKWVyej2phg=";
}
```
btw, if you react with :+1: instead of :tada: it will show up higher in priority since they filter by that emoji :smiley:

**Comment by singatias** [comment]
> > Hi @afresquet, I was about to do the same thing but I didn't figure out where is the sha256sum is coming from, I downloaded the official package from font-awesome website for the desktop .zip and I was wondering what to do in case I want to help maintainers updating packages when needed.
> > Thank you :)
> 
> Hello, I used [nurl](https://github.com/nix-community/nurl), the command and output look like this:
> 
> ```shell
> $ nix run nixpkgs#nurl -- https://github.com/FortAwesome/Font-Awesome/ 6.5.1
> fetchFromGitHub {
>   owner = "FortAwesome";
>   repo = "Font-Awesome";
>   rev = "6.5.1";
>   hash = "sha256-fwMr7af/YUmkb83JFo+KlDQCYXazAYxlbKWVyej2phg=";
> }
> ```
> 
> btw, if you react with 👍 instead of 🎉 it will show up higher in priority since they filter by that emoji 😃

Awesome thank you :D

**Review by MaxwellDupre — APPROVED** [review]
simple version bump.

**Review by JohnRTitor — COMMENTED** [review]
Can you squash the two commits? since the older one never hit nixpkgs.

**Review by JohnRTitor — APPROVED** [review]

**Comment by tomberek** [comment]
Result of `nixpkgs-review pr 285394` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>font-awesome (font-awesome_6)</li>
  </ul>
</details>

**Pull request merged**
