### PR TITLE
Fix the bash patch 42 hash as it change upstream

### PR DESCRIPTION
**Pull request by thedebugger**

### CODE REVIEW

**Comment by copumpkin** [comment]
It's already fixed in staging, and we're mirroring the old file temporarily (which should get picked up automatically by the build substitution mechanism). We avoided putting it straight into master to avoid a mass rebuild.

**Comment by copumpkin** [comment]
(also, this is probably the 10th PR/issue on this topic I've seen. What a shitshow a tiny modification can cause!)

**Comment by thedebugger** [comment]
@copumpkin okay, great! thanks! (note to myself - go through the PRs next time!)

**Comment by copumpkin** [comment]
@thedebugger eh, I appreciate you (and the others) taking the initiative to fix it. I think it's something the community needs to be more resilient to.

Perhaps by auto-mirroring all fixed-input sources (smaller than X) to the nixos.org binary cache server? Unfortunately then we stop noticing if we have a broken source, so we'd need some combination of a mirroring scheme plus a notification mechanism that upstream changed/disappeared.

**Comment by copumpkin** [comment]
Closing as this is dealt with elsewhere.

**Comment by thedebugger** [comment]
@copumpkin In general I agree, but in this particular case the error is in upstream - the bash patch shouldn't change after it was released. They should have released a new patch (maybe 43?) to fix that. And thanks for providing the feedback! It is nice to get a quick feedback from the nix community.

**Pull request closed without merging**
