### PR TITLE
systemd: enable oomd by default

### PR DESCRIPTION
**Pull request by lovesegfault**
###### Motivation for this change
It's not clear why we had this set to false before, so I'm enabling it by
default for the main systemd derivation. `systemdMinimal` remains unchanged.

cc. @flokli
Fixes https://github.com/NixOS/nixpkgs/issues/113903

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Fedora enables this by default https://fedoraproject.org/wiki/Changes/EnableSystemdOomd

**Comment by flokli** [comment]
> Fedora enables this by default https://fedoraproject.org/wiki/Changes/EnableSystemdOomd

Yes, but they have a way to test this. I don't think there's anything against adding it (and maybe by default) once we have a VM test.

**Comment by Artturin** [comment]
tested with
```nix
  systemd = {
    package = (pkgs.systemd.override { withOomd = true; });
    additionalUpstreamSystemUnits = [ "dbus-org.freedesktop.oom1.service" "systemd-oomd.service" ];
    services.systemd-oomd = {
      wantedBy = [ "multi-user.target" ];
    };
  };

  users.users.systemd-oom = {
    group = "systemd-oom";
    isSystemUser = true;
  };
  users.groups.systemd-oom = { };
```

`systemd-run --user tail /dev/zero`

```
kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=user.slice,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/user@1000.service/app.slice/run-r5bda2dc9204b4a47a8c186266be2e133.service,task=/run/current-sy,pid=132040,uid=1000
kernel: Out of memory: Killed process 132040 (/run/current-sy) total-vm:51597328kB, anon-rss:25922220kB, file-rss:4kB, shmem-rss:0kB, UID:1000 pgtables:100604kB oom_score_adj:0
systemd[1]: user@1000.service: A process of this unit has been killed by the OOM killer.
systemd[3862]: run-r5bda2dc9204b4a47a8c186266be2e133.service: A process of this unit has been killed by the OOM killer.
kernel: oom_reaper: reaped process 132040 (/run/current-sy), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
systemd[3862]: run-r5bda2dc9204b4a47a8c186266be2e133.service: Main process exited, code=killed, status=9/KILL
systemd[3862]: run-r5bda2dc9204b4a47a8c186266be2e133.service: Failed with result 'oom-kill'.
systemd[3862]: run-r5bda2dc9204b4a47a8c186266be2e133.service: Consumed 54.620s CPU time.
```

**Comment by lf-** [comment]
@Artturin that is the kernel killing the process, oomd did not kill it. I suspect that's down to highly conservative defaults on oomd settings, for what it's worth.

**Comment by Artturin** [comment]
hah okay
i'll try setting fedoras defaults
https://src.fedoraproject.org/rpms/systemd/blob/rawhide/f/10-oomd-defaults.conf
https://src.fedoraproject.org/rpms/systemd/blob/rawhide/f/10-oomd-root-slice-defaults.conf
https://src.fedoraproject.org/rpms/systemd/blob/rawhide/f/10-oomd-user-service-defaults.conf

**Comment by felschr** [comment]
Ubuntu 22.04 LTS will also use systemd-ood by default:
https://www.phoronix.com/scan.php?page=news_item&px=Ubuntu-22.04-Systemd-OOMD

**Comment by flokli** [comment]
@lovesegfault can you rebase this and add a VM test? We could probably pick the example from https://fedoraproject.org/wiki/Changes/EnableSystemdOomd#How_to_test.

**Pull request closed without merging**
