### PR TITLE
gnujump: init at 1.0.8

### PR DESCRIPTION
**Pull request by fgaz**
###### Motivation for this change

A classic.

Can someone test if it works on darwin too? The website only mentions GNU/Linux.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
@GrahamcOfBorg build gnujump

**Comment by dtzWill** [comment]
Please switch the source URL to use the mirror://gnu .

Also if you want to see if it at least builds on Darwin, include it in platforms and helpful Borg bot will let us know how that works out :).

**Comment by fgaz** [comment]
@GrahamcOfBorg build gnujump

**Comment by fgaz** [comment]
Right, I don't have the bits to do that. @dtzWill could you trigger it?

**Comment by dtzWill** [comment]
I thought just pushing the commit would be enough, whoops.  Sure:

@GrahamcOfBorg build gnujump

**Comment by dtzWill** [comment]
lmao the sounds :+1:

**Comment by dtzWill** [comment]
Asked folks on #nix-darwin and it seems we should disable Darwin support for now.  Thanks for giving it a try.  Here's what they said:

> we've had issues SDL-config on hydra before
if it's back we should fix that or disable the build otherwise it blocks one of the macs for ~10h with every rebuild

**Comment by fgaz** [comment]
I don't know if the the push triggered a notification, but in case it didn't: I removed darwin from platforms

**Pull request merged**
