### PR TITLE
matrix-nio: update

### PR DESCRIPTION
**Pull request by symphorien**
Support for decrypting images in pantalaimon

Briefly tested pantalaimon.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by emilazy** [comment]
Result of `nixpkgs-review pr 87610` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
<br>- pantalaimon
<br>- python37Packages.matrix-nio
<br>- weechatScripts.weechat-matrix
</details>

**Review by emilazy — APPROVED** [review]
weechat-matrix seems to work fine for me.

**Comment by symphorien** [comment]
Updated matrix-nio to 0.12.0.
Changelog https://github.com/poljar/matrix-nio/blob/master/CHANGELOG.md
Checked with pantalaimon that I could do interactive verification.

**Review by emilazy — APPROVED** [review]
Been running this for a few days with weechat-matrix, seems fine to me.

**Comment by symphorien** [comment]
Apparently pantalaimon was independently udpated elsewhere, remains only the matrix-nio update.

**Comment by Ekleog** [comment]
Thank you! :D

**Pull request merged**
