### PR TITLE
python312Packages.ollama: 0.4.4 -> 0.4.5

### PR DESCRIPTION
**Pull request by fabaff**
Diff: https://github.com/ollama/ollama-python/compare/refs/tags/v0.4.4...v0.4.5

Changelog: https://github.com/ollama/ollama-python/releases/tag/v0.4.5

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by lucasew** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 369637`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 8 packages marked as broken and skipped:</summary>
  <ul>
    <li>private-gpt</li>
    <li>private-gpt.dist</li>
    <li>python312Packages.llama-index-embeddings-ollama</li>
    <li>python312Packages.llama-index-embeddings-ollama.dist</li>
    <li>python312Packages.llama-index-llms-ollama</li>
    <li>python312Packages.llama-index-llms-ollama.dist</li>
    <li>python312Packages.private-gpt</li>
    <li>python312Packages.private-gpt.dist</li>
  </ul>
</details>
<details>
  <summary>:fast_forward: 1 package blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>:x: 43 packages failed to build:</summary>
  <ul>
    <li>almanah</li>
    <li>ciscoPacketTracer8</li>
    <li>etherape</li>
    <li>glom</li>
    <li>glom.dev</li>
    <li>glom.devdoc</li>
    <li>glom.doc</li>
    <li>glom.lib</li>
    <li>gnome-inform7</li>
    <li>goocanvas2</li>
    <li>goocanvas2.dev</li>
    <li>goocanvas2.devdoc</li>
    <li>goocanvasmm2</li>
    <li>goocanvasmm2.dev</li>
    <li>gpredict</li>
    <li>gscan2pdf</li>
    <li>gscan2pdf.man</li>
    <li>home-assistant-component-tests.ollama</li>
    <li>ocrfeeder</li>
    <li>oterm</li>
    <li>oterm.dist</li>
    <li>pdf-quench</li>
    <li>perl538Packages.GooCanvas2</li>
    <li>perl538Packages.GooCanvas2.devdoc</li>
    <li>perl538Packages.GooCanvas2CairoTypes</li>
    <li>perl538Packages.GooCanvas2CairoTypes.devdoc</li>
    <li>perl540Packages.GooCanvas2</li>
    <li>perl540Packages.GooCanvas2.devdoc</li>
    <li>perl540Packages.GooCanvas2CairoTypes</li>
    <li>perl540Packages.GooCanvas2CairoTypes.devdoc</li>
    <li>php81Extensions.yaml</li>
    <li>php82Extensions.yaml</li>
    <li>php83Extensions.yaml</li>
    <li>php84Extensions.yaml</li>
    <li>python312Packages.goocalendar</li>
    <li>python312Packages.goocalendar.dist</li>
    <li>python313Packages.goocalendar</li>
    <li>python313Packages.goocalendar.dist</li>
    <li>shutter</li>
    <li>sm64ex</li>
    <li>sm64ex-coop</li>
    <li>tryton</li>
    <li>tryton.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 28 packages built:</summary>
  <ul>
    <li>ani-cli</li>
    <li>ente-auth</li>
    <li>ente-auth.debug</li>
    <li>ente-auth.pubcache</li>
    <li>helmsman</li>
    <li>jan</li>
    <li>lug-helper</li>
    <li>moon</li>
    <li>nagios</li>
    <li>nicotine-plus</li>
    <li>nicotine-plus.dist</li>
    <li>open-vm-tools</li>
    <li>open-vm-tools-headless</li>
    <li>open-vm-tools-headless.dev</li>
    <li>open-vm-tools.dev</li>
    <li>pam_ldap</li>
    <li>paper-age</li>
    <li>python312Packages.langchain-ollama</li>
    <li>python312Packages.langchain-ollama.dist</li>
    <li>python312Packages.ollama</li>
    <li>python312Packages.ollama.dist</li>
    <li>python313Packages.ollama</li>
    <li>python313Packages.ollama.dist</li>
    <li>spotube</li>
    <li>ttysvr</li>
    <li>vscode-extensions.timonwong.shellcheck</li>
    <li>xsnow</li>
    <li>zsh-you-should-use</li>
  </ul>
</details>

**Comment by lucasew** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 369637`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 8 packages marked as broken and skipped:</summary>
  <ul>
    <li>private-gpt</li>
    <li>private-gpt.dist</li>
    <li>python312Packages.llama-index-embeddings-ollama</li>
    <li>python312Packages.llama-index-embeddings-ollama.dist</li>
    <li>python312Packages.llama-index-llms-ollama</li>
    <li>python312Packages.llama-index-llms-ollama.dist</li>
    <li>python312Packages.private-gpt</li>
    <li>python312Packages.private-gpt.dist</li>
  </ul>
</details>
<details>
  <summary>:fast_forward: 1 package blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>:x: 37 packages failed to build:</summary>
  <ul>
    <li>blender-hip</li>
    <li>das</li>
    <li>das.dist</li>
    <li>home-assistant-component-tests.ollama</li>
    <li>kak-tree-sitter</li>
    <li>libLAS</li>
    <li>libsForQt5.discover</li>
    <li>oterm</li>
    <li>oterm.dist</li>
    <li>protonmail-bridge-gui</li>
    <li>prowler</li>
    <li>prowler.dist</li>
    <li>python312Packages.dash</li>
    <li>python312Packages.dash-bootstrap-components</li>
    <li>python312Packages.dash-bootstrap-components.dist</li>
    <li>python312Packages.dash.dist</li>
    <li>python312Packages.meshtastic</li>
    <li>python312Packages.meshtastic.dist</li>
    <li>python312Packages.nipy</li>
    <li>python312Packages.nipy.dist</li>
    <li>python312Packages.niworkflows</li>
    <li>python312Packages.niworkflows.dist</li>
    <li>python312Packages.transforms3d</li>
    <li>python312Packages.transforms3d.dist</li>
    <li>python313Packages.dash</li>
    <li>python313Packages.dash-bootstrap-components</li>
    <li>python313Packages.dash-bootstrap-components.dist</li>
    <li>python313Packages.dash.dist</li>
    <li>python313Packages.meshtastic</li>
    <li>python313Packages.meshtastic.dist</li>
    <li>python313Packages.nipy</li>
    <li>python313Packages.nipy.dist</li>
    <li>python313Packages.transforms3d</li>
    <li>python313Packages.transforms3d.dist</li>
    <li>sentry-native</li>
    <li>solc</li>
    <li>streamcontroller</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 150 packages built:</summary>
  <ul>
    <li>antora-ui-default</li>
    <li>argc</li>
    <li>asdf-vm</li>
    <li>blender</li>
    <li>blendfarm</li>
    <li>bootc</li>
    <li>cargo-lambda</li>
    <li>checkstyle</li>
    <li>cli11</li>
    <li>clightning</li>
    <li>cloudflared</li>
    <li>cosmic-store</li>
    <li>databricks-cli</li>
    <li>dotbot</li>
    <li>dotbot.dist</li>
    <li>envision</li>
    <li>eslint_d</li>
    <li>faircamp</li>
    <li>flatpak</li>
    <li>flatpak-builder</li>
    <li>flatpak-builder.doc</li>
    <li>flatpak-builder.installedTests</li>
    <li>flatpak-builder.man</li>
    <li>flatpak.debug</li>
    <li>flatpak.dev</li>
    <li>flatpak.devdoc</li>
    <li>flatpak.doc</li>
    <li>flatpak.installedTests</li>
    <li>flatpak.man</li>
    <li>flowblade</li>
    <li>fractal</li>
    <li>genpass</li>
    <li>gfold</li>
    <li>git-trim</li>
    <li>gnome-builder</li>
    <li>gnome-builder.devdoc</li>
    <li>gnome-software</li>
    <li>gummy</li>
    <li>imgproxy</li>
    <li>iptsd</li>
    <li>jbang</li>
    <li>jdt-language-server</li>
    <li>justbuild</li>
    <li>kak-tree-sitter-unwrapped</li>
    <li>kazumi</li>
    <li>kazumi.debug</li>
    <li>kazumi.pubcache</li>
    <li>kdePackages.discover</li>
    <li>kdePackages.discover.debug</li>
    <li>kdePackages.discover.dev</li>
    <li>kdePackages.discover.devtools</li>
    <li>kdePackages.flatpak-kcm</li>
    <li>kdePackages.flatpak-kcm.debug</li>
    <li>kdePackages.flatpak-kcm.dev</li>
    <li>kdePackages.flatpak-kcm.devtools</li>
    <li>kicad</li>
    <li>kicad-small</li>
    <li>kicadAddons.kikit</li>
    <li>kicadAddons.kikit-library</li>
    <li>kikit</li>
    <li>kikit.dist</li>
    <li>libsForQt5.flatpak-kcm</li>
    <li>lilypond-unstable</li>
    <li>lilypond-unstable-with-fonts</li>
    <li>lms</li>
    <li>louvre</li>
    <li>louvre.dev</li>
    <li>malcontent-ui</li>
    <li>malcontent-ui.dev</li>
    <li>malcontent-ui.lib</li>
    <li>matomo</li>
    <li>matomo-beta</li>
    <li>megapixels</li>
    <li>micromamba</li>
    <li>monitor</li>
    <li>nextdns</li>
    <li>nezha-theme-admin</li>
    <li>noseyparker</li>
    <li>openusd</li>
    <li>osm2pgsql</li>
    <li>ostree</li>
    <li>ostree-full</li>
    <li>ostree-full.dev</li>
    <li>ostree-full.installedTests</li>
    <li>ostree-full.man</li>
    <li>ostree-rs-ext</li>
    <li>ostree.dev</li>
    <li>ostree.installedTests</li>
    <li>ostree.man</li>
    <li>pantheon.appcenter</li>
    <li>pantheon.elementary-greeter</li>
    <li>pantheon.elementary-onboarding</li>
    <li>pantheon.sideload</li>
    <li>pantheon.switchboard-plug-applications</li>
    <li>pantheon.switchboard-with-plugs</li>
    <li>pantheon.wingpanel-applications-menu</li>
    <li>pantheon.wingpanel-with-indicators</li>
    <li>peergos</li>
    <li>python312Packages.kicad</li>
    <li>python312Packages.langchain-ollama</li>
    <li>python312Packages.langchain-ollama.dist</li>
    <li>python312Packages.ollama</li>
    <li>python312Packages.ollama.dist</li>
    <li>python312Packages.openusd</li>
    <li>python312Packages.pcbnewtransition</li>
    <li>python312Packages.pcbnewtransition.dist</li>
    <li>python313Packages.kicad</li>
    <li>python313Packages.ollama</li>
    <li>python313Packages.ollama.dist</li>
    <li>python313Packages.openusd</li>
    <li>python313Packages.pcbnewtransition</li>
    <li>python313Packages.pcbnewtransition.dist</li>
    <li>rednotebook</li>
    <li>rednotebook.dist</li>
    <li>remmina</li>
    <li>rpm-ostree</li>
    <li>rpm-ostree.dev</li>
    <li>rpm-ostree.devdoc</li>
    <li>rpm-ostree.man</li>
    <li>soapui</li>
    <li>telepresence2</li>
    <li>tinygo</li>
    <li>torrenttools</li>
    <li>ueberzugpp</li>
    <li>vala-language-server</li>
    <li>wivrn</li>
    <li>xdg-desktop-portal</li>
    <li>xdg-desktop-portal-gnome</li>
    <li>xdg-desktop-portal-gtk</li>
    <li>xdg-desktop-portal-shana</li>
    <li>xdg-desktop-portal-xapp</li>
    <li>xdg-desktop-portal.installedTests</li>
    <li>xfce.catfish</li>
    <li>xfce.catfish.dist</li>
    <li>xfce.gigolo</li>
    <li>xfce.gigolo.dev</li>
    <li>xfce.parole</li>
    <li>xfce.parole.dev</li>
    <li>xfce.ristretto</li>
    <li>xfce.ristretto.dev</li>
    <li>xfce.xfce4-panel-profiles</li>
    <li>xfce.xfce4-taskmanager</li>
    <li>xfce.xfce4-taskmanager.dev</li>
    <li>xfce.xfce4-terminal</li>
    <li>xfce.xfce4-terminal.dev</li>
    <li>xfce.xfce4-volumed-pulse</li>
    <li>xfce.xfce4-volumed-pulse.dev</li>
    <li>xfce.xfmpc</li>
    <li>xfce.xfmpc.dev</li>
    <li>ytfzf</li>
  </ul>
</details>

**Comment by fabaff** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 369637`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 8 packages marked as broken and skipped:</summary>
  <ul>
    <li>private-gpt</li>
    <li>private-gpt.dist</li>
    <li>python312Packages.llama-index-embeddings-ollama</li>
    <li>python312Packages.llama-index-embeddings-ollama.dist</li>
    <li>python312Packages.llama-index-llms-ollama</li>
    <li>python312Packages.llama-index-llms-ollama.dist</li>
    <li>python312Packages.private-gpt</li>
    <li>python312Packages.private-gpt.dist</li>
  </ul>
</details>
<details>
  <summary>:x: 3 packages failed to build:</summary>
  <ul>
    <li>home-assistant-component-tests.ollama</li>
    <li>oterm</li>
    <li>oterm.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 6 packages built:</summary>
  <ul>
    <li>python312Packages.langchain-ollama</li>
    <li>python312Packages.langchain-ollama.dist</li>
    <li>python312Packages.ollama</li>
    <li>python312Packages.ollama.dist</li>
    <li>python313Packages.ollama</li>
    <li>python313Packages.ollama.dist</li>
  </ul>
</details>

**Comment by happysalada** [comment]
merging since ollama is broken on latest unstable because of the missing pydantic dependency.

**Comment by mweinelt** [comment]
This broke the home-assistant integration for ollama :melting_face:

**Comment by lucasew** [comment]
> This broke the home-assistant integration for ollama 🫠

What error?

**Comment by mweinelt** [comment]
grafik

**Pull request merged**
