### PR TITLE
Fix 64-bit Wine builds

### LINKED ISSUE #14627: wine-wow-*-staging fails to build
### Steps to reproduce
```$ nix-build -E 'with import <nixpkgs> {}; wineStaging.override { wineBuild = "wineWow"; }'```

## Technical details

* System: recent NixOS, sandboxed
* Nixpkgs version: current master, e.g. 48972763c86; it used to build on f9cae4f6dc8be7
* Example output: 
```
gcc -m64 -c -o crypt_md4.o /tmp/nix-build-wine-wow-1.9.7-staging.drv-0/wine-1.9.7/dlls/advapi32/crypt_md4.c -I. \
  -I/tmp/nix-build-wine-wow-1.9.7-staging.drv-0/wine-1.9.7/dlls/advapi32 -I../../include \
  -I/tmp/nix-build-wine-wow-1.9.7-staging.drv-0/wine-1.9.7/include -D__WINESRC__ -D_ADVAPI32_ \
  -D_REENTRANT -fPIC -Wall -pipe -fno-strict-aliasing -Wdeclaration-after-statement -Wempty-body \
  -Wignored-qualifiers -Wstrict-prototypes -Wtype-limits -Wunused-but-set-parameter -Wvla \
  -Wwrite-strings -Wpointer-arith -Wlogical-op -gdwarf-2 -gstrict-dwarf -g -O2
/tmp/nix-build-wine-wow-1.9.7-staging.drv-0/wine-1.9.7/dlls/advapi32/crypt_md4.c: In function 'MD4Update':
/tmp/nix-build-wine-wow-1.9.7-staging.drv-0/wine-1.9.7/dlls/advapi32/crypt_md4.c:134:1: internal compiler error: in choose_baseaddr, at config/i386/i386.c:10412
 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
```

### PR DESCRIPTION
**Pull request by abbradar**
###### Things done
- [ ] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Closes #14627. Still building but it seems to progress further already. cc @vcunat

### CODE REVIEW

**Comment by abbradar** [comment]
`wine64` built fine, but `wineWow` obviously wants to build a special GCC for itself, which would take a while... I suppose we don't want to build this GCC on Hydra (we don't build WOW version there anyway) so I'll hide it.

**Comment by vcunat** [comment]
I'll test wine-wow now, as I need it anyway.

**Comment by vcunat** [comment]
Nitpick: I'd drop "add gcc49_multi" from the commit name.

**Comment by abbradar** [comment]
Yep, thanks -- fixed.

**Comment by abbradar** [comment]
Updated to include mention of the upstream bug.

**Comment by vcunat** [comment]
Very good work! Nitpick: I expect the next release will be 5.4 and not 5.3.1.

I'm still building, as I'm without access to a fast machine ATM.

**Comment by abbradar** [comment]
Reworded it to be versioning policy agnostic ~_^. I've built it -- `winecfg` runs wine but I haven't tested it further. Since you have something to actually run (if I understand correctly) let's wait for you to finish.

**Comment by vcunat** [comment]
I/we do, but it may take ~~24h before I get any results from that. It's probably not worth to wait for that.

**Comment by abbradar** [comment]
OK, let's merge then -- `notepad` runs fine, at least.

**Pull request merged**
