### PR TITLE
libvirt: 6.3.0 -> 6.6.0

### PR DESCRIPTION
**Pull request by basvandijk**
###### Motivation for this change

https://github.com/libvirt/libvirt/blob/master/NEWS.rst#v660-2020-08-02

###### Things done

Also upgrades `python3Packages.libvirt`
and patches the `rpcgen` tool from Apple's `developer_cmds` package.

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by basvandijk** [comment]
@GrahamcOfBorg build libvirt python3Packages.libvirt

**Comment by basvandijk** [comment]
@GrahamcOfBorg eval

**Comment by basvandijk** [comment]
The build fails on darwin when build in a sandbox:
```
nix-build -A libvirt --option sandbox true
...
rpcgen: rpcgen: $RPCGEN_CPP: /usr/bin/clang-cpp$RPCGEN_CPP: /usr/bin/clang-cpp: rpcgen: : No such file or directory
No such file or directory
rpcgen: $RPCGEN_CPP: /usr/bin/clang-cpprpcgen: : No such file or directory
$RPCGEN_CPP: /usr/bin/clang-cpp: $RPCGEN_CPP: /usr/bin/clang-cppNo such file or directory
: No such file or directory
...
  CC       logging/virtlogd-log_daemon.o
In file included from ../../src/logging/log_daemon.c:32:
In file included from ../../src/admin/admin_server_dispatch.h:23:
In file included from ../../src/rpc/virnetserverprogram.h:24:
../../src/rpc/virnetmessage.h:41:5: error: must use 'struct' tag to refer to type 'virNetMessageHeader'
    virNetMessageHeader header;
    ^
    struct
../../src/rpc/virnetmessage.h:41:25: error: field has incomplete type 'struct virNetMessageHeader'
    virNetMessageHeader header;
                        ^
../../src/rpc/virnetmessage.h:25:16: note: forward declaration of 'struct virNetMessageHeader'
typedef struct virNetMessageHeader *virNetMessageHeaderPtr;
               ^
../../src/logging/log_daemon.c:916:47: error: use of undeclared identifier 'VIR_LOG_MANAGER_PROTOCOL_PROGRAM'
    if (!(logProgram = virNetServerProgramNew(VIR_LOG_MANAGER_PROTOCOL_PROGRAM,
                                              ^
../../src/logging/log_daemon.c:917:47: error: use of undeclared identifier 'VIR_LOG_MANAGER_PROTOCOL_PROGRAM_VERSION'
                                              VIR_LOG_MANAGER_PROTOCOL_PROGRAM_VERSION,
                                              ^
../../src/logging/log_daemon.c:929:53: error: use of undeclared identifier 'ADMIN_PROGRAM'
        if (!(adminProgram = virNetServerProgramNew(ADMIN_PROGRAM,
                                                    ^
../../src/logging/log_daemon.c:930:53: error: use of undeclared identifier 'ADMIN_PROTOCOL_VERSION'
                                                    ADMIN_PROTOCOL_VERSION,
                                                    ^
6 errors generated.
```

I suspect it succeeds outside the sandbox since I have Xcode installed. I'll figure out which dependency to add to make it succeed inside the sandbox.

**Comment by basvandijk** [comment]
Problem solved. It should be ready for review now.

@GrahamcOfBorg build libvirt python3Packages.libvirt

**Comment by basvandijk** [comment]
@GrahamcOfBorg eval

**Review by jonringer — APPROVED** [review]
LGTM from linux PoV

```
https://github.com/NixOS/nixpkgs/pull/98937
1 package failed to build:
virt-manager-qt

24 packages built:
collectd collectd-data docker-machine-kvm docker-machine-kvm2 gnome3.gnome-boxes haskellPackages.libvirt-hs libvirt libvirt-glib libvmi minikube minishift python37Packages.libvirt python38Packages.libvirt rubyPackages.ruby-libvirt rubyPackages_2_5.ruby-libvirt rubyPackages_2_7.ruby-libvirt terraform-full terraform-providers.libvirt terraform_0_11-full terragrunt virt-manager virt-top virt-viewer virtlyst
```
would like darwin to review as well @NixOS/darwin-maintainers

**Comment by basvandijk** [comment]
@jonringer thanks for checking! I see that `virt-manager-qt` was [already failing on master](https://hydra.nixos.org/job/nixpkgs/trunk/virt-manager-qt.x86_64-linux).

I do see ofborg reporting between 500 and 1000 packages on darwin need to be rebuild (likely due to the `darwin.developer_cmds` change). So I think it's better to retarget this to `staging`.

**Comment by basvandijk** [comment]
Closing this in favor of https://github.com/NixOS/nixpkgs/pull/99043 which is targeted against staging.

**Pull request closed without merging**
