### PR TITLE
Avoid top-level `with` in `pkgs/development`

### PR DESCRIPTION
**Pull request by philiptaron**
## Description of changes

Using `with` at a top-level scope is [an anti-pattern](https://nix.dev/guides/best-practices#with-scopes). The tracking issue is #208242. This is a pure refactor: there is no functional change contained in this PR, though spot the bug fix where `libiconv` wasn't injected!

I used the refactor strategy that looks for the uses of names [coming from `lib`, `pkgs`, `python3Packages`, and more](https://gist.github.com/philiptaron/04326000d5ff20cb72c2805efd09701c). 

Following advice, I also preferred to inherit names from `lib` instead of `builtins` where there was a choice. I also preferred to inherit from `lib` in one place, rather than to have a mixture of `lib.thing` and `inherit (lib) thing`.

There are no rebuilds when I run `nixpkgs-review rev HEAD`, so I've targeted master with this PR.

See also:
- https://github.com/NixOS/nixpkgs/pull/295975

Remaining top-level `with` expressions in `pkgs/development`:

```
$ rg '^with' -tnix --sort=path pkgs/development/
pkgs/development/lisp-modules-new-obsolete/shell.nix
1:with import ../../../default.nix {};

pkgs/development/lisp-modules-obsolete/shell.nix
1:with import ../../../default.nix {};

pkgs/development/lua-modules/overrides.nix
59:with prev;

pkgs/development/ocaml-modules/janestreet/0.12.nix
5:with self;

pkgs/development/ocaml-modules/janestreet/0.14.nix
8:with self;

pkgs/development/ocaml-modules/janestreet/0.15.nix
11:with self;

pkgs/development/ocaml-modules/janestreet/0.16.nix
11:with self;

pkgs/development/ocaml-modules/janestreet/default.nix
5:with self;

pkgs/development/ocaml-modules/janestreet/old.nix
27:with self;

pkgs/development/r-modules/generate-shell.nix
1:with import ../../.. {};

pkgs/development/ruby-modules/testing/tap-support.nix
1:with builtins;

pkgs/development/ruby-modules/testing/testing.nix
1:with builtins;

pkgs/development/tools/misc/travis/shell.nix
3:with import <nixpkgs> {};
```

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
This change is practically impossible to review and the upside is questionable. At least open individual PRs so that the involved subsystem maintainers can decide individually if they want to change this or not (there are also multiple way to fix this “problem”, so people will have opinions).

**Comment by philiptaron** [comment]
Thanks for your feedback, @sternenseemann. 

The change ought to be reviewed in three ways:

1. By judging the rebuild count. There is no semantic change.
2. By looking through the files to see the pattern. It's quite mechanical.
3. By reading through the linked issues. You'll see that many similar changes to reduce the number of `with` expressions at a top-level scope have been merged.

Here's [the discourse post](https://github.com/NixOS/nixpkgs/pull/295975) where I announced my intent to embark on this refactor.

As to the multiple ways to do it: there are only two ways to remove top-level with. Suppose we're talking about `with foo;`. 

The first way is to replace every location that got its symbols from `foo` with `foo.symbol` where previously there was just `symbol`. This induces a change everywhere in the file and makes longer symbols everywhere. It's also nigh impossible to do mechanically, and therefore is error-prone.

The second way is the one I've used here. `with foo` is replaced with `let inherit (foo) all used symbols; in`. This contains the change to the top of the file, is able to be performed mechanically, and directly corresponds to the previous semantics.

I am able to do multiple PRs; if I've misjudged on the correct size of a PR, I apologize. The other ways has its downside as well: people don't like a flood of PRs either!

**Comment by fricklerhandwerk** [comment]
Still, I agree it's too much responsibility and too much of a cognitive burden to focus on endless pages of code to make sure no nonsense snuck in. I also recommend splitting it into easy-to-digest PRs.

**Comment by philiptaron** [comment]
> I also recommend splitting it into easy-to-digest PRs.

What granularity do you recommend? Each of these commits is able to stand on their own, and could correspond to a PR. Maybe by maximum four commits per PR, so roughly 17 PRs?

**Comment by maralorn** [comment]
If we are talking about diffusion of responsibility maybe one PR per subsystem/maintainer group would make sense?

**Comment by maralorn** [comment]
I have to say I really don’t like the huge import lists. But I agree that getting rid of toplevel with is probably worth it.

**Comment by sternenseemann** [comment]
> By judging the rebuild count. There is no semantic change.

ofborg has blind spots, the change still needs to be verified by careful review.

> You'll see that many similar changes to reduce the number of `with` expressions at a top-level scope have been merged.

Nixpkgs has no code style or global guidelines. Consequently, code style and conventions differ troughout it. In the absence of a RFC supported decision, it is best to defer the decision to the people working with the code in question, the maintainers on a case-by-case basis.

> The first way is to replace every location that got its symbols from `foo` with `foo.symbol` where previously there was just `symbol`. This induces a change everywhere in the file and makes longer symbols everywhere. It's also nigh impossible to do mechanically, and therefore is error-prone.
> 
> The second way is the one I've used here. `with foo` is replaced with `let inherit (foo) all used symbols; in`. This contains the change to the top of the file, is able to be performed mechanically, and directly corresponds to the previous semantics.

It does *not* correspond to the previous semantics – otherwise this change would be pointless. With this change the “imported” symbols will shadow existing symbols of the same name when they didn't before. It needs to be verified that this isn't the case anywhere. Notably, the other approach wouldn't have this problem (but the inflated diff you mention).

**Comment by maralorn** [comment]
> It does _not_ correspond to the previous semantics – otherwise this change would be pointless. With this change the “imported” symbols will shadow existing symbols of the same name when they didn't before. It needs to be verified that this isn't the case anywhere. Notably, the other approach wouldn't have this problem (but the inflated diff you mention).

Yeah, this change in meaning is exactly the point of this pr, isn’t it? I think both approaches need to verify that no shadowing is happening. In the one approach we need to check that no inherit statement introduces shadowing in the other approach we need to check that we nowhere use `bar.foo` even though there is also `foo` in scope. The inherit statement has the slight advantage that we only need to check it for that statement while in theory the qualified approach needs to be checked at every usage site.

**Comment by philiptaron** [comment]
Please bear with me as I learn to communicate in ways that don't start or continue arguments and debates.

As a high-level statement:

I hope through these changes to make all of nixpkgs more readable and less magic. I hope you're committed to that same goal. As @fricklerhandwerk [wrote](https://discourse.nixos.org/t/removing-most-uses-of-top-level-with/41233/2):

> Awesome, this would be a huge improvement in ease of readability! I vividly remember being thoroughly confused where names come from, and that made Nixpkgs feel like way too much magic.

What I'd appreciate is not denigrating, belittling, or claiming that this work is impossible. It's not. It's just work. And I -- we -- can do it.

<hr/>

On the semantics discussion:

What I'm trying to communicate by "directly corresponds to the previous semantics" is that any symbol `s` that was looked up from attrset `a` before this PR continues to be looked up from attrset `a` after this PR. Nothing more or less. It's a statement of _continued correctness_ in the face of a change in lookup semantics, from implicit (`with a`) to explicit (`let inherit (a) ...; in`).

Emphasis on the **corresponds**. 🙂 

As Maralorn points out, that does take some deftness to avoid shadowing. My way to avoid this is two-fold:

1. Look through each of the symbols chosen by the tool. Since the tool has a false-negative problem -- it'll inherit a symbol that isn't actually used as a symbol -- I have to do this anyway.
2. If any of them were passed as an argument to the function (say, in `callPackage` style), remove or rescope. This one happens a good amount.
3. If any of them are within a `with` block (very uncommon), check whether that `with` expose the same name. If it's `lib`, this is also quite unlikely. Remove or rescope if so.

<hr/>

As for this PR, I'm closing it and splitting it up into more PRs per the feedback in this thread. I look forward to a more targeted discussion in those PRs.

**Comment by philiptaron** [comment]
All changes in this PR are landed in more specific ones, or obviated by intervening changes.

- https://github.com/NixOS/nixpkgs/pull/299057
- https://github.com/NixOS/nixpkgs/pull/299245
- https://github.com/NixOS/nixpkgs/pull/299241
- https://github.com/NixOS/nixpkgs/pull/299236
- https://github.com/NixOS/nixpkgs/pull/299058
- https://github.com/NixOS/nixpkgs/pull/299022
- https://github.com/NixOS/nixpkgs/pull/299015
- https://github.com/NixOS/nixpkgs/pull/299010
- https://github.com/NixOS/nixpkgs/pull/299002
- https://github.com/NixOS/nixpkgs/pull/298996
- https://github.com/NixOS/nixpkgs/pull/299056

Obviated by other changes:
- https://github.com/NixOS/nixpkgs/pull/293124

**Pull request closed without merging**
