### PR TITLE
zeal: add xcb-util-keysyms to buildInputs

### PR DESCRIPTION
**Pull request by itcowed**
solves #8008 

see https://github.com/zealdocs/zeal#requirements for reasoning of solution

### CODE REVIEW

**Comment by edolstra** [comment]
Could you use a valid Author field (in particular email address) in your Git commits? Thanks!

**Comment by dnhgff** [comment]
that is a reasonable request. i will see what i can do about that today

**Comment by dnhgff** [comment]
@edolstra  email added

**Comment by lethalman** [comment]
cc @svenkeidel

**Comment by svenkeidel** [comment]
I will take a look at this.

**Comment by svenkeidel** [comment]
For some reason it worked for me without xcb-util-keysyms. But the project lists xcb-util-keysyms as an official [dependency](https://github.com/zealdocs/zeal#requirements), so I guess it is ok. I'm good with the change.

**Comment by svenkeidel** [comment]
I have no commit bit, I cannot merge this PR.

**Comment by lethalman** [comment]
Thanks.

**Pull request merged**
