### PR TITLE
python310Packages.pluggy: 1.0.0 -> 1.2.0

### PR DESCRIPTION
**Pull request by dotlambda**
###### Description of changes
Diff: https://github.com/pytest-dev/pluggy/compare/refs/tags/1.0.0...1.2.0

Changelog: https://github.com/pytest-dev/pluggy/blob/refs/tags/1.2.0/CHANGELOG.rst

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by trofi** [comment]
Bisect says c24313730ad80d165f7a1104f6431749ae16881b `python310Packages.pluggy: 1.0.0 -> 1.2.0` broke `python310Packages.virtualenv` build on `staging`:

```
$ nix build --no-link -f. python310Packages.virtualenv -L
...
python3.10-virtualenv> Executing pytestCheckPhase
python3.10-virtualenv> INTERNALERROR> Traceback (most recent call last):
python3.10-virtualenv> INTERNALERROR>   File "/nix/store/d25c59i7i4fzwzrignmg8c6y2r53zzj7-python3.10-pytest-7.2.1/lib/python3.10/site-packages/_pytest/main.py", line 266, in wrap_session
python3.10-virtualenv> INTERNALERROR>     config._do_configure()
python3.10-virtualenv> INTERNALERROR>   File "/nix/store/d25c59i7i4fzwzrignmg8c6y2r53zzj7-python3.10-pytest-7.2.1/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1037, in _do_configure
python3.10-virtualenv> INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
python3.10-virtualenv> INTERNALERROR>   File "/nix/store/nd2wrig3f99r8nqawl9n65mhy8xflqw2-python3.10-pluggy-1.2.0/lib/python3.10/site-packages/pluggy/_hooks.py", line 452, in call_historic
python3.10-virtualenv> INTERNALERROR>     res = self._hookexec(self.name, self._hookimpls, kwargs, False)
python3.10-virtualenv> INTERNALERROR>   File "/nix/store/nd2wrig3f99r8nqawl9n65mhy8xflqw2-python3.10-pluggy-1.2.0/lib/python3.10/site-packages/pluggy/_manager.py", line 112, in _hookexec
python3.10-virtualenv> INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
python3.10-virtualenv> INTERNALERROR>   File "/nix/store/nd2wrig3f99r8nqawl9n65mhy8xflqw2-python3.10-pluggy-1.2.0/lib/python3.10/site-packages/pluggy/_callers.py", line 116, in _multicall
python3.10-virtualenv> INTERNALERROR>     raise exception.with_traceback(exception.__traceback__)
python3.10-virtualenv> INTERNALERROR>   File "/nix/store/nd2wrig3f99r8nqawl9n65mhy8xflqw2-python3.10-pluggy-1.2.0/lib/python3.10/site-packages/pluggy/_callers.py", line 80, in _multicall
python3.10-virtualenv> INTERNALERROR>     res = hook_impl.function(*args)
python3.10-virtualenv> INTERNALERROR>   File "/build/virtualenv-20.19.0/tests/conftest.py", line 26, in pytest_configure
python3.10-virtualenv> INTERNALERROR>     order = manager.hook.pytest_collection_modifyitems._nonwrappers
python3.10-virtualenv> INTERNALERROR> AttributeError: '_HookCaller' object has no attribute '_nonwrappers'
```

**Comment by vcunat** [comment]
Reverted for now.

**Comment by dotlambda** [comment]
An update to virtualenv 20.24.0 fixes this: https://github.com/NixOS/nixpkgs/pull/244115

**Comment by SuperSandro2000** [comment]
which will be included in the python-updates run #244135

**Pull request merged**
