### PR TITLE
github-runner: fix hash

### PR DESCRIPTION
**Pull request by superherointj**
github-runner: fix hash

image

https://github.com/NixOS/nixpkgs/pull/220469#issuecomment-1464986306

### CODE REVIEW

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 220716` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>github-runner</li>
  </ul>
</details>

**Review by newAM — APPROVED** [review]
Hash is good.  Builds on x86_64-linux for me.

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 220716` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>github-runner</li>
  </ul>
</details>

**Comment by aanderse** [comment]
Thanks!

**Pull request merged**
