### PR TITLE
mov-cli: 1.5.4 -> 4.3.14

### LINKED ISSUE #310910: Update request: mov-cli 1.5.4 → 4.3.14
- Package name: `mov-cli`
- Latest released version: `4.3.14`

- Current version on the unstable channel: `1.5.7`
- Current version on the stable/release channel: `1.5.4`

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@Baitinq 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

### PR DESCRIPTION
**Pull request by youhaveme9**
## Description of changes

Closes  #310910

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Roshaen** [comment]
Hello everyone,
This is my first time contributing to nixpkgs.
I have tried my best to follow the contribution guide but still I request to please suggest if any changes required.
Thank you

**Comment by RaghavSood** [comment]
@GrahamcOfBorg build python311Packages.mov-cli python312Packages.mov-cli

**Comment by RaghavSood** [comment]
Result of `nixpkgs-review pr 311026` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>mov-cli</li>
    <li>mov-cli.dist</li>
  </ul>
</details>

**Comment by RaghavSood** [comment]
Your commit message should match `{packageName}: {oldVersion} -> {newVersion}`

Looks like this is a pretty significant bump, so many of the dependencies have changes - you would need to add those to the derivation before the build works.

**Comment by RaghavSood** [comment]
@GrahamcOfBorg build mov-cli

My mistake, didn't see the package path

**Comment by Roshaen** [comment]
> Your commit message should match `{packageName}: {oldVersion} -> {newVersion}`
> 
> Looks like this is a pretty significant bump, so many of the dependencies have changes - you would need to add those to the derivation before the build works.

I have added the required dependencies in the derivation but `devgoldyutils` and `mov-cli-test` are undefined.
Without these two packages the build is successful in aarch64-darwin

**Comment by Roshaen** [comment]
> Your commit message should match `{packageName}: {oldVersion} -> {newVersion}`
> 
> Looks like this is a pretty significant bump, so many of the dependencies have changes - you would need to add those to the derivation before the build works.

I have added all the required dependencies in the derivation but the packages `devgoldyutils` and `mov-cli-test` are undefined

**Comment by RaghavSood** [comment]
> I have added all the required dependencies in the derivation but the packages `devgoldyutils` and `mov-cli-test` are undefined

They might be packages not defined in nixpkgs yet (or defined under another name) - try searching the pypi or source links in the repo to see if they're under another name.

If not, you'll have to first add those to nixpkgs before you can use them to complete this update.

**Comment by Roshaen** [comment]
> > I have added all the required dependencies in the derivation but the packages `devgoldyutils` and `mov-cli-test` are undefined
> 
> They might be packages not defined in nixpkgs yet (or defined under another name) - try searching the pypi or source links in the repo to see if they're under another name.
> 
> If not, you'll have to first add those to nixpkgs before you can use them to complete this update.

I have checked, these packages are not defined in the nixpkgs yet. So, we have to add these first in nixpkgs.

**Comment by Roshaen** [comment]
Hey @RaghavSood 
I have raised a PR for adding `devgoldyutils` in nixpkgs
I request you to review it.

**Comment by Roshaen** [comment]
> > > I have added all the required dependencies in the derivation but the packages `devgoldyutils` and `mov-cli-test` are undefined
> > 
> > 
> > They might be packages not defined in nixpkgs yet (or defined under another name) - try searching the pypi or source links in the repo to see if they're under another name.
> > If not, you'll have to first add those to nixpkgs before you can use them to complete this update.
> 
> I have checked, these packages are not defined in the nixpkgs yet. So, we have to add these first in nixpkgs.

I'm trying to add mov-cli-test to nixpkgs but it depends on mov-cli version >=4.2
The current version of mov-cli in nixpkgs is 1.5.4 which is causing build failure of mov-cli-test
```
> Checking runtime dependencies for mov_cli_test-1.1.5-py3-none-any.whl
>      - mov-cli>=4.2 not satisfied by version 1.5.7
```
Can you tell me what could be done to resolve this issue?

**Comment by r3tr0ananas** [comment]
> > > > I have added all the required dependencies in the derivation but the packages `devgoldyutils` and `mov-cli-test` are undefined
> > > 
> > > 
> > > They might be packages not defined in nixpkgs yet (or defined under another name) - try searching the pypi or source links in the repo to see if they're under another name.
> > > If not, you'll have to first add those to nixpkgs before you can use them to complete this update.
> > 
> > 
> > I have checked, these packages are not defined in the nixpkgs yet. So, we have to add these first in nixpkgs.
> 
> I'm trying to add mov-cli-test to nixpkgs but it depends on mov-cli version >=4.2 The current version of mov-cli in nixpkgs is 1.5.4 which is causing build failure of mov-cli-test
> 
> ```
> > Checking runtime dependencies for mov_cli_test-1.1.5-py3-none-any.whl
> >      - mov-cli>=4.2 not satisfied by version 1.5.7
> ```
> 
> Can you tell me what could be done to resolve this issue?

This shouldn't be an issue anymore, as I removed the dependency for mov-cli in mov-cli-test.

**Comment by Roshaen** [comment]
Hey @r3tr0ananas 
`pytubefix` is a dependency for `mov-cli-test` which is not present in nixpkgs yet
Should I add it first?

**Comment by r3tr0ananas** [comment]
> Created a PR adding `pytubefix` Can you please review it? #314822

I can't as i am not a reviewer.

**Comment by Roshaen** [comment]
> Hey @r3tr0ananas `pytubefix` is a dependency for `mov-cli-test` which is not present in nixpkgs yet
> 
> Created a PR adding `pytubefix` Can you please review it? #314822

Hey @RaghavSood Can you please review this PR?

**Comment by Roshaen** [comment]
Hey @RaghavSood 
Raised PR for mov-cli-test : https://github.com/NixOS/nixpkgs/pull/314898
Please review it

Thanks

**Review by JohnAZoidberg — APPROVED** [review]
Tested by running `./result/bin/mov-cli -s test abc` and I can play Big Buck bunny" :)

**Comment by JohnAZoidberg** [comment]
> Hello everyone, This is my first time contributing to nixpkgs. I have tried my best to follow the contribution guide but still I request to please suggest if any changes required. Thank you

Thank you! Sorry it took you so long to get it merged. Great first change, updating it from a very old version.

**Comment by JohnAZoidberg** [comment]
Thanks @r3tr0ananas for helping out.

**Pull request merged**
