### PR TITLE
Modernize psutils and fix Darwin build

### PR DESCRIPTION
**Pull request by afh**
###### Description of changes

When building psutils using `nix shell nixpkgs#psutils` the build fails with exit code 2 `gcc: command not found`.

<details><summary>last 10 log lines</summary>

```sh
error: builder for '/nix/store/ax00m59llahk44w81698h92jnp9knhrs-psutils-17.drv' failed with exit code 2;
       last 10 log lines:
       > source root is psutils
       > setting SOURCE_DATE_EPOCH to timestamp 858120785 of file psutils/showchar.sh
       > patching sources
       > updateAutotoolsGnuConfigScriptsPhase
       > configuring
       > building
       > build flags: SHELL=/nix/store/mxvgjwzdvrl81plvgqnzbrqb14ccnji6-bash-5.2-p15/bin/bash
       > gcc -DPAPER=\"a4\" -DUNIX -O -Wall   -c -o psbook.o psbook.c
       > /nix/store/mxvgjwzdvrl81plvgqnzbrqb14ccnji6-bash-5.2-p15/bin/bash: line 1: gcc: command not found
       > make: *** [<builtin>: psbook.o] Error 127
       For full logs, run 'nix log /nix/store/ax00m59llahk44w81698h92jnp9knhrs-psutils-17.drv'
```

</details>

Adding `makeFlags` resolved the issue for me on aarch64-darwin.

❓ Should the `makeFlags` only be applied on Darwin or are they acceptable or even also desirable on other platforms?

Additionally I went ahead and "modernized" the package to the best of my knowledge and changed the src URL as the ftp URL timed out for me.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 241869` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 241869` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>psutils</li>
  </ul>
</details>

**Comment by wegank** [comment]
@ofborg build psutils psutils.passthru.tests

**Comment by afh** [comment]
Thanks for merging, @wegank, very much appreciated! This will be quite useful for folks like me wanting to use groff on Darwin with `enableHtml = true` 👍

**Pull request merged**
