### PR TITLE
arduino: 1.6.9 -> 1.6.12

### PR DESCRIPTION
**Pull request by cko**
###### Things done
- [x] Tested using sandboxing
  `nix-env --option build-use-sandbox true -f . -iA arduino`
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by binarin** [comment]
Thanks @cko. Could you also remove all mentions of package/library indexes from both `default.nix` and `downloads.nix`? After https://github.com/arduino/Arduino/issues/5143 they are no longer needed.

**Comment by rasendubi** [comment]
Build fails for me:
```
...
untar-unzip-download:
      [get] Getting: https://github.com/arduino-libraries/Firmata/archive/2.5.3.zip
      [get] To: /tmp/nix-build-arduino-1.6.12.drv-0/Arduino-1.6.12-src/build/Firmata-2.5.3.zip
      [get] Error getting https://github.com/arduino-libraries/Firmata/archive/2.5.3.zip to /tmp/nix-build-arduino-1.6.12.drv-0/Arduino-1.6.12-src/build/Firmata-2.5.3.zip

untar-unzip-checksum:
     [echo] Testing checksum of "Firmata-2.5.3.zip"
 [checksum] Could not find file /tmp/nix-build-arduino-1.6.12.drv-0/Arduino-1.6.12-src/build/Firmata-2.5.3.zip to generate checksum for.

BUILD FAILED
/tmp/nix-build-arduino-1.6.12.drv-0/Arduino-1.6.12-src/build/build.xml:102: The following error occurred while executing this line:
/tmp/nix-build-arduino-1.6.12.drv-0/Arduino-1.6.12-src/build/build.xml:627: The following error occurred while executing this line:
/tmp/nix-build-arduino-1.6.12.drv-0/Arduino-1.6.12-src/build/build.xml:207: The following error occurred while executing this line:
/tmp/nix-build-arduino-1.6.12.drv-0/Arduino-1.6.12-src/build/build.xml:224: The following error occurred while executing this line:
/tmp/nix-build-arduino-1.6.12.drv-0/Arduino-1.6.12-src/build/build.xml:242: The following error occurred while executing this line:
/tmp/nix-build-arduino-1.6.12.drv-0/Arduino-1.6.12-src/build/build.xml:830: Could not find file /tmp/nix-build-arduino-1.6.12.drv-0/Arduino-1.6.12-src/build/Firmata-2.5.3.zip to generate checksum for.

Total time: 5 seconds
builder for ‘/nix/store/0w4dfnvcsvjzr63npfysk172znykjx9d-arduino-1.6.12.drv’ failed with exit code 1
error: build of ‘/nix/store/0w4dfnvcsvjzr63npfysk172znykjx9d-arduino-1.6.12.drv’ failed
```

**Review by grahamc — CHANGES_REQUESTED** [review]
I'm getting the same error about /tmp/nix-build-arduino-1.6.12.drv-0/Arduino-1.6.12-src/build/Firmata-2.5.3.zip.

**Comment by binarin** [comment]
@cko, you removed not only 3 index files, but every other external file download needed by build process. So somehow you are not using sandboxed build, assuming that it builds at your machine.

**Comment by cko** [comment]
@binarin I updated the PR. Could you have a look if I removed the right things?

**Comment by cko** [comment]
wrote a new PR from scratch (#19335). Hopefully this one is better.

**Pull request closed without merging**
