### PR TITLE
vector: 0.31.0 -> 0.33.0

### PR DESCRIPTION
**Pull request by happysalada**
## Description of changes

a simple update that also fixes a regression introduced in 0.31.0
The upgrade should be painless

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by thoughtpolice — APPROVED** [review]

**Comment by natsukium** [comment]
It looks like the patch needs to be updated.
```
> applying patch /nix/store/0ajg01j3d8gvicrxylkz6w2mi6cn813a-rust-1.71-unnecessary-mut.diff
       > patching file lib/vector-core/src/tls/incoming.rs
       > Reversed (or previously applied) patch detected!  Assume -R? [n]
       > Apply anyway? [n]
       > Skipping patch.
       > 2 out of 2 hunks ignored -- saving rejects to file lib/vector-core/src/tls/incoming.rs.rej
```

**Comment by happysalada** [comment]
@natsukium the patch just needed to be removed, thanks!
I'm going to wait for ofborg to finish just to make sure if that is fine with you.

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 250588` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>vector</li>
  </ul>
</details>

**Comment by happysalada** [comment]
I've checked a bit more the problem and it seems that with the latest release, they are patching the source of openssl in order to use 3.1 instead of 1.1
cargo doesn't like that with vendored dependencies.
I've opened https://github.com/vectordotdev/vector/issues/18339 upstream to discuss the issue.
I'm leaving this as draft for now.

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 250588` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>vector</li>
  </ul>
</details>

**Comment by happysalada** [comment]
I was just trying to see if things changed with rust 1.72, it appears they didn't.
upstream said that a fix in 1.73 might fix things. I'll rebase again then.

**Comment by happysalada** [comment]
I've just pushed the update to 0.33.0
upstream has removed the git dependency that was problematic, so this should be good to go.
no major changes, just the default format has been changed from toml to yaml (toml still supported though). I'm going to make a PR for the module a little later.
I'm waiting for ofborg, if anyone has time please review. (this is just a simple update).
I don't want to wait too long, since the last minor update was missed.

**Comment by happysalada** [comment]
alright, ofborg is passing, I'm going to wait 24h more just in case someone has something to say.

**Review by thoughtpolice — APPROVED** [review]
lgtm 👍🏻

**Pull request merged**
