### PR TITLE
syslinux: apply patches to fix pointer mismatch

### PR DESCRIPTION
**Pull request by magneticflux-**
Fixes the new errors found by GCC 14 by applying patches from Arch Linux.

Later commits clean up the stack of patches without altering existing behavior since the previous Arch Linux patch location is archived now and new patches go to GitLab.

Goes further than https://github.com/NixOS/nixpkgs/pull/367685 and https://github.com/NixOS/nixpkgs/pull/367948 by hopefully addressing the root cause now that the immediate build is fixed.

@gador Did you see a build failure complaining about `tftp_put`? I didn't notice one and Arch Linux doesn't have one like that so I'm not sure it's needed, but I can add it back in!

@vcunat I removed the warning suppression you added so we can be notified if anything else shows up in GCC 15 or whenever. The other added option `-fcommon` doesn't seem to be used by Arch Linux; instead they add `-z muldefs`? (I think?) Not sure if one is better than the other.

I can also squash all the patch rearranging, I just separated them to make it easier to tell where each one went.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by K900** [comment]
@ofborg test boot.biosCdrom

**Comment by vcunat** [comment]
No idea if there's any difference between the two (by glancing at their docs).

**Comment by gador** [comment]
> @gador Did you see a build failure complaining about tftp_put? I didn't notice one and Arch Linux doesn't have one like that so I'm not sure it's needed, but I can add it back in!

I don't remember, but if this works I'm good 👍

**Comment by philiptaron** [comment]
Thank you!

**Pull request merged**
