### PR TITLE
wine: 1.8.6 -> 2.0

### PR DESCRIPTION
**Pull request by bendlas**
###### Motivation for this change

Major stable release along with new versions for sub-packages

###### Things done

- Built on platform(s)
   - [x] NixOS
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by avnik** [comment]
LGTM!

btw, where you pick  gecko/mono versions for pull?

**Comment by bendlas** [comment]
@avnik http://wiki.winehq.org/Gecko and http://wiki.winehq.org/Mono

it's commented in the source file

**Comment by avnik** [comment]
@bendlas  Ahh, just not seen it in diff.

Will update unstable/staging myself, as soon as staging will be tagged

**Comment by MP2E** [comment]
LGTM! I pulled these changes in locally, builds fine and runs the win32 binaries I had around

**Pull request merged**
