### PR TITLE
protobuf_25: 25.2 -> 25.3

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Changelog: https://github.com/protocolbuffers/protobuf/releases/tag/v25.3

cc @jonringer 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 289224` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>protobuf_25</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 289224` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>protobuf_25</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 289224` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>protobuf_25</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 289224` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>protobuf_25</li>
  </ul>
</details>

**Review by superherointj — APPROVED** [review]

**Comment by kirillrdy** [comment]
anyone can comment on CI errors?

**Comment by GaetanLepage** [comment]
> anyone can comment on CI errors?

Yes, they are caused by `python3Packages.protobuf` not building with this version.
It was already the case with 25.2, hence not a regression.
I am working on a fix before updating the default `protobuf` to `protobuf_25`.

**Comment by kirillrdy** [comment]
`protobuf_25` and `python3Packages.protobuf` builds on master, where is the regression coming from ?

**Comment by GaetanLepage** [comment]
`python3Packages.protobuf` builds fine on `master` because it relies on the sources of `pkgs.protobuf`, which is `protobuf_24`.
What doesn't build is the python binding of `protobuf_25` (which cannot be directly built, you can however set `protobuf = protobuf_25;` in `all-packages.nix`).

**Comment by kirillrdy** [comment]
thank you for clarification, what is the merge plan for this ? merging this breaks `protobuf_25.tests`

**Comment by GaetanLepage** [comment]
> thank you for clarification, what is the merge plan for this ? merging this breaks `protobuf_25.tests`

I would encourage a merge of this PR as it doesn't bring any regression.
`protobuf_25.tests` are also broken on `master` for the same reason (i.e. `python3Packages.protobuf`'s tests fail).

**Comment by superherointj** [comment]
kirillrdy thanks for keeping a keen eye on this.

I agree with Gaetan that merging this does not break `protobuf_25.tests`. But also, doesn't fix `protobuf_25.tests`. It just upgrades the Go package. Which was my initial reasoning on this too. (I had been using protobuf in Go, but not Python.)

To show master is already broken:
image

So I think, merging this makes sense. As it only affects `protobuf_25`. And does not cause breakage of other things. And if Python part is fixed. It should be fixed for the new version. So it is an advancement still and desirable to have this PR merged.

**Comment by superherointj** [comment]
Maybe because we know that python test is specifically broken, we should mark it broken?

**Comment by GaetanLepage** [comment]
> Maybe because we know that python test is specifically broken, we should mark it broken?

The C++ library (`pkgs.protobuf_25`) itself is not broken. Also, the only version of the python bindings that exist in nixpkgs (i.e. `python3Packages.protobuf`) is built against the default protobuf (24.4 currently) and is not broken.
So no package is actually broken currently.

**Comment by superherointj** [comment]
I meant the test that is broken. Not the package.

**Comment by superherointj** [comment]
Something like this could work:
image
But there may exist a better way to do this.

**Comment by GaetanLepage** [comment]
@superherointj I directly marked the python package as broken for protobuf newer than 25. Does that work for you ?
The test is automatically marked as broken for `protobuf_25`.

**Comment by superherointj** [comment]
> @superherointj I directly marked the python package as broken for protobuf newer than 25. Does that work for you ? The test is automatically marked as broken for `protobuf_25`.

Yes. That is a much better idea indeed.

**Comment by superherointj** [comment]
Whenever marking a package broken it is usual to add a comment for:
- date
- error
- tracking issue
That is still missing.

**Comment by GaetanLepage** [comment]
> Whenever marking a package broken it is usual to add a comment for:
> 
>     * date
> 
>     * error
> 
>     * tracking issue

Sure ! Done

**Review by superherointj — APPROVED** [review]

**Review by SomeoneSerge — APPROVED** [review]

**Pull request merged**
