### PR TITLE
luaPackages: init some neovim packages

### PR DESCRIPTION
**Pull request by mrcjkb**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by mrcjkb** [comment]
Result of `nixpkgs-review pr 275841` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>lua54Packages.neotest</li>
  </ul>
</details>
<details>
  <summary>24 packages built:</summary>
  <ul>
    <li>lua51Packages.commons-nvim</li>
    <li>lua51Packages.funnyfiles-nvim</li>
    <li>lua51Packages.fzf-lua</li>
    <li>lua51Packages.neotest</li>
    <li>lua51Packages.nvim-nio</li>
    <li>lua52Packages.commons-nvim</li>
    <li>lua52Packages.funnyfiles-nvim</li>
    <li>lua52Packages.fzf-lua</li>
    <li>lua52Packages.neotest</li>
    <li>lua52Packages.nvim-nio</li>
    <li>lua53Packages.commons-nvim</li>
    <li>lua53Packages.funnyfiles-nvim</li>
    <li>lua53Packages.fzf-lua</li>
    <li>lua53Packages.neotest</li>
    <li>lua53Packages.nvim-nio</li>
    <li>lua54Packages.commons-nvim</li>
    <li>lua54Packages.funnyfiles-nvim</li>
    <li>lua54Packages.fzf-lua</li>
    <li>lua54Packages.nvim-nio</li>
    <li>luajitPackages.commons-nvim</li>
    <li>luajitPackages.funnyfiles-nvim</li>
    <li>luajitPackages.fzf-lua</li>
    <li>luajitPackages.neotest</li>
    <li>luajitPackages.nvim-nio</li>
  </ul>
</details>

**Comment by mrcjkb** [comment]
I will have to leave this as draft until https://github.com/NixOS/nixpkgs/pull/272647 hits `master`, because `rocks.nvim` depends on `fidget.nvim`.

**Comment by mrcjkb** [comment]
Strange that this didn't show any failures, given the missing dependency.

**Comment by mrcjkb** [comment]
nixpkgs-review on x86_64-linux:

<details>

```
1 package marked as broken and skipped:
lua54Packages.neotest

49 packages built:
lua51Packages.commons-nvim lua51Packages.funnyfiles-nvim lua51Packages.fzf-lua lua51Packages.lua-utils-nvim lua51Packages.neotest lua51Packages.nvim-nio lua51Packages.rocks-config-nvim lu
a51Packages.rocks-dev-nvim lua51Packages.rocks-git-nvim lua51Packages.rocks-nvim lua52Packages.commons-nvim lua52Packages.funnyfiles-nvim lua52Packages.fzf-lua lua52Packages.lua-utils-nvi
m lua52Packages.neotest lua52Packages.nvim-nio lua52Packages.rocks-config-nvim lua52Packages.rocks-dev-nvim lua52Packages.rocks-git-nvim lua52Packages.rocks-nvim lua53Packages.commons-nvi
m lua53Packages.funnyfiles-nvim lua53Packages.fzf-lua lua53Packages.lua-utils-nvim lua53Packages.neotest lua53Packages.nvim-nio lua53Packages.rocks-config-nvim lua53Packages.rocks-dev-nvi
m lua53Packages.rocks-git-nvim lua53Packages.rocks-nvim lua54Packages.commons-nvim lua54Packages.funnyfiles-nvim lua54Packages.fzf-lua lua54Packages.lua-utils-nvim lua54Packages.nvim-nio 
lua54Packages.rocks-config-nvim lua54Packages.rocks-dev-nvim lua54Packages.rocks-git-nvim lua54Packages.rocks-nvim luajitPackages.commons-nvim luajitPackages.funnyfiles-nvim luajitPackage
s.fzf-lua luajitPackages.lua-utils-nvim luajitPackages.neotest luajitPackages.nvim-nio luajitPackages.rocks-config-nvim luajitPackages.rocks-dev-nvim luajitPackages.rocks-git-nvim luajitP
ackages.rocks-nvim
```
</details>

**Comment by mrcjkb** [comment]
@teto fidget.nvim has reached master, so this is ready now.

**Comment by teto** [comment]
pretty cool ty.

**Pull request merged**
