### PR TITLE
warzone2100: 4.4.1 -> 4.4.2

### PR DESCRIPTION
**Pull request by fgaz**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by MikHulk** [comment]
Hi,

This package doesn't build for me with this update:

```
building '/nix/store/ql2g2hk6n174j57iwbchcr4m6f56l8fp-warzone2100_src.tar.xz.drv'...

trying https://downloads.sourceforge.net/warzone2100/releases/4.4.1/warzone2100_src.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   394  100   394    0     0    598      0 --:--:-- --:--:-- --:--:--   597
100   365  100   365    0     0    137      0  0:00:02  0:00:02 --:--:--   366
100  467M  100  467M    0     0  50.9M      0  0:00:09  0:00:09 --:--:-- 73.4M
error: hash mismatch in fixed-output derivation '/nix/store/ql2g2hk6n174j57iwbchcr4m6f56l8fp-warzone2100_src.tar.xz.drv':
         specified: sha256-8vbwO4PXEOyZqGiSz1yqhe8jfe4E4iv908mc+8xuH8I=
            got:    sha256-O5Yqxqp1vKYr8uvAZ1SdsI/kocOzg0KRCirCqqvLrN4=
error: 1 dependencies of derivation '/nix/store/p5z3dbm245fkwvh00s6rfn3z7rc4lbrf-warzone2100-4.4.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/cl73whndym0mls859x6ig4rpqy4wzxa4-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/w6x8wr414666nnrxps0d30ddiw5pl3sm-nixos-system-labo-23.11.1779.cf28ee258fd5.drv' failed to build
```

I tried to dinf something about this error, but nothing interesting. Any Idea ?

**Comment by fgaz** [comment]
@MikHulk I see from the log that you are building version 4.4.1, which was shortly affected by [this problem](https://github.com/NixOS/nixpkgs/pull/272701#issuecomment-1850364885). Updating nixpkgs to a revision that includes #273585 should fix the issue.

**Comment by MikHulk** [comment]
Thank you @fgaz . How can I do that ? With other pkg I just need to upgrade with:

```
nixos-rebuild switch --upgrade
```
I am on the newest version of nixos 23.11. When I made this issue 4.4.1 was the only version available here https://search.nixos.org/packages?query=warzone. But it appears 4.4.2 is available now and I could install the package. 

That's weird...

**Comment by fgaz** [comment]
It takes up to a few days for packages to reach the channels https://nixpk.gs/pr-tracker.html?pr=273734

**Pull request merged**
