### PR TITLE
home-assistant: 2021.12.8 -> 2021.12.9

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change
https://github.com/home-assistant/core/releases/tag/2021.12.9

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
```pytb
______________________ test_config_platform_valid[pyloop] ______________________
[gw42] linux -- Python 3.9.9 /nix/store/dn4fwp0yx6nsa85cr20cwvdmg64xwmcy-python3-3.9.9/bin/python3.9
mock_is_file = None
loop = <_UnixSelectorEventLoop running=False closed=False debug=False>
    def test_config_platform_valid(mock_is_file, loop):
        """Test a valid platform setup."""
        files = {YAML_CONFIG_FILE: BASE_CONFIG + "light:\n  platform: demo"}
        with patch_yaml_files(files):
            res = check_config.check(get_test_config_dir())
            assert res["components"].keys() == {"homeassistant", "light"}
>           assert res["components"]["light"] == [{"platform": "demo"}]
E           AssertionError: assert [] == [{'platform': 'demo'}]
E             Right contains one more item: {'platform': 'demo'}
E             Use -v to get the full diff
files      = {'configuration.yaml': 'homeassistant:\n  name: Home\n  latitude: -26.107361\n  longitude: 28.054500\n  elevation: 1600\n  unit_system: metric\n  time_zone: GMT\n\n\nlight:\n  platform: demo'}
loop       = <_UnixSelectorEventLoop running=False closed=False debug=False>
mock_is_file = None
res        = {'components': HomeAssistantConfig([('homeassistant', OrderedDict([('name', 'Home'), ('latitude', -26.107361), ('longi...- Requirements for recorder not found: ['sqlalchemy==1.4.27']."])]), 'secret_cache': {}, 'secrets': OrderedDict(), ...}
tests/scripts/test_check_config.py:61: AssertionError
```

No idea yet.

**Comment by Mic92** [comment]
This one should be fixable no? `Requirements for recorder not found: ['sqlalchemy==1.4.27'].`

**Comment by mweinelt** [comment]
Broken due to a pytest-httpx that updated multiple dependencies in incompatible ways, so we have to wait for the next home-assistant release to catch up. Marking this PR as a draft. Until then home-assistant remains broken on master.

**Comment by fabaff** [comment]
#154966 fixes `master`.

**Pull request merged**
