### PR TITLE
dropbox: 3.14.7 -> 3.18.1

### PR DESCRIPTION
**Pull request by bendlas**
###### Things done

Reverted #14077 due to reasons detailed there and on the revert commit.
- Built on platform(s)
  - [x] NixOS
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @jagajaga @peterhoeg @joachifm

### CODE REVIEW

**Comment by jagajaga** [comment]
I really liked the idea behind renaming.

**Comment by joachifm** [comment]
@jagajaga can you elaborate? I find @bendlas's arguments convincing, but I'm sure there are tradeoffs I'm unaware of. If anything, would it not make more sense to rename the dropbox binary to `dropboxd` or something rather than mess with the command-line interface?

**Comment by bendlas** [comment]
@jagajaga So, what _was_ the idea "behind" it and what did you like about it? As far as I could tell, it was a case of "let's do the first thing that looks like fixing the problem". IMHO a non-existing problem for that matter.

Also, how are you running dropbox? I'm starting it via `dropbox start` in my `.xprofile` and since dropbox is usually quiet, I didn't even notice the breakage till now. I could go on about changes being labeled "minor refactoring" and then still breaking user scripts, but I'll leave that to imagination.

I understand that it's slightly confusing to have `dropbox` as well as `dropbox-cli` with the latter being the one that you actually want to install, but renaming an established CLI tool is far worse than not solving it at all.
Why not just rename the __packages__, not the binary: `dropbox -> dropbox-pkg` `dropbox-cli -> dropbox` and leaving `dropbox-cli` as a deprecated alias for `dropbox`? This would also solve the confusion without rolling a tool with a name different from _every other distribution_ as well as the vendor-intended name.

**Comment by ttuegel** [comment]
> I understand that it's slightly confusing to have dropbox as well as dropbox-cli with the latter being the one that you actually want to install, but renaming an established CLI tool is far worse than not solving it at all.

I don't quite understand this statement. I don't use, and have never used, dropbox-cli. Anyway, renaming against upstream is a non-starter.

**Pull request merged**
