### PR TITLE
python311Packages.fiona: 1.9.4.post1 -> 1.9.5

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Update and fix `fiona`.
Changelog: https://github.com/Toblerity/Fiona/releases/tag/1.9.5

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 262886` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages failed to build:</summary>
  <ul>
    <li>python310Packages.bsuite</li>
    <li>python310Packages.bsuite.dist</li>
    <li>python310Packages.plotnine</li>
    <li>python310Packages.plotnine.dist</li>
    <li>python311Packages.bsuite</li>
    <li>python311Packages.bsuite.dist</li>
    <li>python311Packages.plotnine</li>
    <li>python311Packages.plotnine.dist</li>
  </ul>
</details>
<details>
  <summary>20 packages built:</summary>
  <ul>
    <li>python310Packages.fiona</li>
    <li>python310Packages.fiona.dist</li>
    <li>python310Packages.folium</li>
    <li>python310Packages.folium.dist</li>
    <li>python310Packages.geopandas</li>
    <li>python310Packages.geopandas.dist</li>
    <li>python310Packages.osmnx</li>
    <li>python310Packages.osmnx.dist</li>
    <li>python310Packages.wktutils</li>
    <li>python310Packages.wktutils.dist</li>
    <li>python311Packages.fiona</li>
    <li>python311Packages.fiona.dist</li>
    <li>python311Packages.folium</li>
    <li>python311Packages.folium.dist</li>
    <li>python311Packages.geopandas</li>
    <li>python311Packages.geopandas.dist</li>
    <li>python311Packages.osmnx</li>
    <li>python311Packages.osmnx.dist</li>
    <li>python311Packages.wktutils</li>
    <li>python311Packages.wktutils.dist</li>
  </ul>
</details>

**Comment by sikmir** [comment]
Result of `nixpkgs-review pr 262886` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.bsuite</li>
    <li>python310Packages.bsuite.dist</li>
    <li>python311Packages.bsuite</li>
    <li>python311Packages.bsuite.dist</li>
  </ul>
</details>
<details>
  <summary>24 packages failed to build:</summary>
  <ul>
    <li>python310Packages.fiona</li>
    <li>python310Packages.fiona.dist</li>
    <li>python310Packages.folium</li>
    <li>python310Packages.folium.dist</li>
    <li>python310Packages.geopandas</li>
    <li>python310Packages.geopandas.dist</li>
    <li>python310Packages.osmnx</li>
    <li>python310Packages.osmnx.dist</li>
    <li>python310Packages.plotnine</li>
    <li>python310Packages.plotnine.dist</li>
    <li>python310Packages.wktutils</li>
    <li>python310Packages.wktutils.dist</li>
    <li>python311Packages.fiona</li>
    <li>python311Packages.fiona.dist</li>
    <li>python311Packages.folium</li>
    <li>python311Packages.folium.dist</li>
    <li>python311Packages.geopandas</li>
    <li>python311Packages.geopandas.dist</li>
    <li>python311Packages.osmnx</li>
    <li>python311Packages.osmnx.dist</li>
    <li>python311Packages.plotnine</li>
    <li>python311Packages.plotnine.dist</li>
    <li>python311Packages.wktutils</li>
    <li>python311Packages.wktutils.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python310Packages.scikit-misc</li>
    <li>python310Packages.scikit-misc.dist</li>
    <li>python311Packages.scikit-misc</li>
    <li>python311Packages.scikit-misc.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
@sikmir are you able to build `netcdf` on `master` ?

**Comment by wegank** [comment]
> Indeed, it seems to fail on darwin:
> 
> ```
> FAIL: run_nc4_tests.sh
> ======================
> *** Testing ncgen3 for netCDF-4.
> *** creating netCDF-4 file c0_4.nc from c0.cdl...
> dyld[87361]: Library not loaded: @rpath/libhdf5_hl.310.dylib
>   Referenced from: <no uuid> /private/tmp/nix-build-netcdf-4.9.2.drv-0/netcdf-c-4.9.2/ncgen3/.libs/ncgen3
>   Reason: tried: '/private/tmp/nix-build-netcdf-4.9.2.drv-0/netcdf-c-4.9.2/liblib/.libs/libhdf5_hl.310.dylib' (no such file), '/nix/store/w2vc36964qpm78gxi85x10fkkx2i23yi-swift-corefoundation-unstable-2018-09-14/Library/Frameworks/libhdf5_hl.310.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/nix/store/w2vc36964qpm78gxi85x10fkkx2i23yi-swift-corefoundation-unstable-2018-09-14/Library/Frameworks/libhdf5_hl.310.dylib' (no such file), '/nix/store/w2vc36964qpm78gxi85x10fkkx2i23yi-swift-corefoundation-unstable-2018-09-14/Library/Frameworks/libhdf5_hl.310.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/nix/store/w2vc36964qpm78gxi85x10fkkx2i23yi-swift-corefoundation-unstable-2018-09-14/Library/Frameworks/libhdf5_hl.310.dylib' (no such file), '/usr/local/lib/libhdf5_hl.310.dylib' (no such file), '/usr/lib/libhdf5_hl.310.dylib' (no such file, not in dyld cache)
> ./run_nc4_tests.sh: line 13: 87361 Abort trap: 6           ${NCGEN3} -k3 -b -o c0_4.nc ${ncgen3c0}
> FAIL run_nc4_tests.sh (exit status: 134)
> ```

Looks like `hdf5` needs to be fixed:

```bash
$ nix-build -A hdf5
/nix/store/0fvdgdvpv92a7nwrfvzh7c3aippwl9a7-hdf5-1.14.2
$ otool -L result/lib/libhdf5_hl.310.dylib
result/lib/libhdf5_hl.310.dylib:
        @rpath/libhdf5_hl.310.dylib (compatibility version 310.0.0, current version 310.0.2)
        @rpath/libhdf5.310.dylib (compatibility version 310.0.0, current version 310.2.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
```

While `@rpath/libhdf5_hl.310.dylib` should be gone by adding `fixDarwinDylibNames`, fixing `@rpath/libhdf5.310.dylib` would need some manual `install_name_tool` changes.

**Comment by GaetanLepage** [comment]
> Looks like `hdf5` needs to be fixed:

This is out of the scope of this PR though, right ?

**Comment by wegank** [comment]
> > Looks like `hdf5` needs to be fixed:
> 
> This is out of the scope of this PR though, right ?

Definitely. `python311Packages.fiona` was already [failing on staging-next](https://hydra.nixos.org/job/nixpkgs/staging-next/python311Packages.fiona.x86_64-darwin/all) due to netcdf, so on master, it's not a regression from this PR.

**Review by wegank — APPROVED** [review]

**Comment by wegank** [comment]
@ofborg build python311Packages.fiona python311Packages.fiona.passthru.tests python311Packages.scikit-misc python311Packages.scikit-misc.passthru.tests

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 262886` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.bsuite</li>
    <li>python310Packages.bsuite.dist</li>
    <li>python311Packages.bsuite</li>
    <li>python311Packages.bsuite.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python310Packages.plotnine</li>
    <li>python310Packages.plotnine.dist</li>
    <li>python311Packages.plotnine</li>
    <li>python311Packages.plotnine.dist</li>
  </ul>
</details>
<details>
  <summary>24 packages built:</summary>
  <ul>
    <li>python310Packages.fiona</li>
    <li>python310Packages.fiona.dist</li>
    <li>python310Packages.folium</li>
    <li>python310Packages.folium.dist</li>
    <li>python310Packages.geopandas</li>
    <li>python310Packages.geopandas.dist</li>
    <li>python310Packages.osmnx</li>
    <li>python310Packages.osmnx.dist</li>
    <li>python310Packages.scikit-misc</li>
    <li>python310Packages.scikit-misc.dist</li>
    <li>python310Packages.wktutils</li>
    <li>python310Packages.wktutils.dist</li>
    <li>python311Packages.fiona</li>
    <li>python311Packages.fiona.dist</li>
    <li>python311Packages.folium</li>
    <li>python311Packages.folium.dist</li>
    <li>python311Packages.geopandas</li>
    <li>python311Packages.geopandas.dist</li>
    <li>python311Packages.osmnx</li>
    <li>python311Packages.osmnx.dist</li>
    <li>python311Packages.scikit-misc</li>
    <li>python311Packages.scikit-misc.dist</li>
    <li>python311Packages.wktutils</li>
    <li>python311Packages.wktutils.dist</li>
  </ul>
</details>

**Review by wegank — APPROVED** [review]

**Comment by GaetanLepage** [comment]
https://github.com/ofborg build python311Packages.fiona python311Packages.fiona.passthru.tests python311Packages.scikit-misc python311Packages.scikit-misc.passthru.tests

**Review by imincik — CHANGES_REQUESTED** [review]
Thank you for contributing.

Changes look good to me, but I suggest to move change of source (from pypi to Gh) to separate commit. Currently, this change is not even mentioned in commit message.

**Comment by imincik** [comment]
@GaetanLepage , if you are interested in maintenance of some geospatial packages you are welcome to join [Geospatial team](https://github.com/NixOS/nixpkgs/blob/8efd5d1e283604f75a808a20e6cde0ef313d07d4/maintainers/team-list.nix#L324).

**Comment by GaetanLepage** [comment]
> @GaetanLepage , would you please extract change of source for Fiona package to separate commit ? Sorry for bothering with this, but I think that change of source (especially when changing from Pypi) is quite important change which shouldn't be lost between some other changes. Thank you.

I am not sure to get what you mean.
In the `fiona` commit, I did the following:

1. Update dependencies:
  a. `cython` -> `cython_3`
  b. +`oldest-supported-numpy`
2. Remove now useless `postPatch` section
3. Update the package version:
  a. `version`: `1.9.4.post1` -> `1.9.5`
  b. Change the `hash` accordingly
4. `format = "pyproject"` -> `pyproject = true` (now recommended)

You want me to split those 4 sub-changes ?
If so, how would you cut it ?

**Comment by imincik** [comment]
> I am not sure to get what you mean.

I am very sorry for confusion. I see, there is no change of source in Fiona. It is good as it is.

But for scikit-misc, there is a change of source from Pypi to GH and I see following commit message:
```
python311Packages.scikit-misc: fix build
Changelog: https://github.com/Toblerity/Fiona/releases/tag/1.9.5
```
I suggest to replace `fix build` text with `change package source from Pypi to GitHub` and remove next line `Changelog: ...`.

**Comment by GaetanLepage** [comment]
> I suggest to replace `fix build` text with `change package source from Pypi to GitHub` and remove next line `Changelog: ...`.

My bad. I was 100% sure that I had changed the `scikit-misc` commit message already, but I have overwritten it by mistake.
Now it should be good !

**Review by veprbl — APPROVED** [review]

**Comment by imincik** [comment]
Thanks @GaetanLepage .

**Pull request merged**
