### PR TITLE
Preserve environment variables from base image in Docker buildImage

### PR DESCRIPTION
**Pull request by thomasjm**
###### Motivation for this change

Normal Dockerfiles preserve the `config.Env` setting from the image they're based upon. This change makes the `dockerTools` `buildImage` command work the same way: if building on a `fromImage`, extract the environment variables setting and prepend it to the new image's setting. 

For reference: the [Docker image spec](https://github.com/moby/moby/blob/master/image/spec/v1.2.md#docker-image-specification-v120)

###### Things done

I've tested building images with this on my local machine. Most of the steps below don't seem applicable and I'm not sure how `dockerTools` is tested.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by thomasjm** [comment]
Friendly ping, does anyone know who would be best to review this?

If this is received positively I'd also like to open another PR to preserve the "history" fields from the previous image (in a pure way of course).

**Comment by mmahut** [comment]
Are there any updates on this pull request, please?

**Comment by nrdxp** [comment]
@thomasjm, if you have time to fix the merge conflicts, I'd be glad to properly review this and see if we can't get it merged in time for 21.05. Seems like a really good idea to me.

**Comment by thomasjm** [comment]
Hi @nrdxp -- actually, after making this PR I ended up doing a more extensive refactor of the Docker stuff. I've been using my fork ever since but I always meant to rebase it on Nixpkgs and see if the community was interested.

You can see what it looks like [here](https://github.com/thomasjm/nixpkgs-docker). Highlights include moving large shell scripts into their own files, adding a test suite, fixing various bugs, adding a couple new options, and improving support for multi-layered images (including what this PR does for all of the config fields).

I know there's been some divergence from the main Nixpkgs, but would you be interested in some of this stuff?

**Comment by nrdxp** [comment]
I believe their are many users who could benefit from your fork, if you don't mind doing the heavy work to factor it into a larger PR, I'd be glad to review and attempt to get some eyes on it.

**Comment by louisblin** [comment]
FYI, I believe this particular feature has already been implemented in #87253 since then. It would be nice to merge any other feature you've been adding to your fork though !

**Comment by thomasjm** [comment]
Oh nice -- I'll close this then, and put it on my todo list to investigate what parts of my fork would make sense to merge.

**Pull request closed without merging**
