### PR TITLE
traefik: 1.7.14 -> 1.7.21

### PR DESCRIPTION
**Pull request by ngerstle**
###### Motivation for this change

I noticed that traefik was several versions out of date. With full respect to https://github.com/NixOS/nixpkgs/pull/76723 and the 1.7 vs 2.0 discussion, this bumps the older, but still maintained, 1.7 version of traefik.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by ngerstle** [comment]
@ehmry I don't have access to merge, so you or or another maintainer will need to do so.

**Review by rnhmjoj — APPROVED** [review]
Builds and run with nix-review. Being a bugfix release it makes sense to target 20.03 and 19.09.

**Comment by rnhmjoj** [comment]
Changing the branch from github creates a mess, I'll manually merge this.

**Comment by rnhmjoj** [comment]
release-20.03: 3c45fc87818cd887bdef22d81f17e18ee1bc814f
release-19.09: 52c112597c6be23d47c0e4e337b03c68dcf26fb0

**Pull request closed without merging**
