### PR TITLE
dbeaver: 22.2.2 -> 22.3.3

### PR DESCRIPTION
**Pull request by DorZion**
###### Description of changes

Upgrade dbeaver from 22.2.2 to 22.3.3

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by wegank — CHANGES_REQUESTED** [review]
Hash mismatch

**Comment by DorZion** [comment]
@wegank Are you sure? Any idea how can I verify the hash? Maybe I did something wrong.
Nix wasn't complaining about the it when installing on my own machine (it did complain when I put the wrong hash though).

**Comment by wegank** [comment]
@ofborg build dbeaver dbeaver.passthru.tests

**Comment by wegank** [comment]
dbeaver reports different hashes on aarch64-linux and x86_64-linux on ofborg, and that's... strange.

**Comment by DorZion** [comment]
Honestly, I have no idea what to do in this case.

That's a long shot but the only thing I can think of is the maven override in the expression. It's not really overridden anymore in `all-packages.nix`, maybe that causes that weird behavior?

**Comment by DorZion** [comment]
@wegank How can we push this forward?

**Comment by fabianhjr** [comment]
Taking a look

**Comment by fabianhjr** [comment]
got

```
error: hash mismatch in fixed-output derivation '/nix/store/zykycsgd8hblfcxfr2jvi273dm7b61zg-dbeaver-22.3.3-maven-deps.drv':
         specified: sha256-vS7lPTDfMiA0m0nR8B2x8t5Qag031jxxjfOeEXJ/SaE=
            got:    sha256-2x0xR29x7l5l/k3zk1Q5AxItHQVFtJ2C1bX41Cdf6N8=
error: 1 dependencies of derivation '/nix/store/q2wfac2ms2c4pf90n3ibc7dx4xaq9jld-dbeaver-22.3.3.drv' failed to build
```

on staging-next

**Comment by wegank** [comment]
I guess something like in #213485 must be done, although I have no idea how to do it.

**Comment by fabianhjr** [comment]
Yeah, probably will need a dependency pin.

**Comment by teto** [comment]
new versions are out : 23.X . 
Leaving this here just in case someone is interested https://github.com/NixOS/nixpkgs/issues/228507

**Comment by wegank** [comment]
Superseded by #232348.

**Pull request closed without merging**
