### PR TITLE
teensy-loader-cli: consistent naming, version bump

### PR DESCRIPTION
**Pull request by lowfatcomputing**
- Made the naming between the git repo, all-packages.nix, and default.nix consistent.
- bumped the version to the latest in the git repo (for support of newer teensy microcontrollers.

@the-kenny

### CODE REVIEW

**Comment by the-kenny** [comment]
I wonder if we should alias ```teensy-loader``` to ```teensy-loader-cli``` for backwards compatibility.

**Comment by lowfatcomputing** [comment]
`teensy-loader` refers specifically to [the gui app](https://www.pjrc.com/teensy/loader.html). I don't think we should have an alias because it would conflict.

**Comment by the-kenny** [comment]
Agreed, that's a good point. Merging now.

**Comment by the-kenny** [comment]
Merged as 937741c9f3e5bbfddb751a39a19344995af3629e

**Pull request closed without merging**
