### PR TITLE
rich: make `ipywidgets` dependency optional

### PR DESCRIPTION
**Pull request by twoolie**
###### Motivation for this change

`ipywidgets` is used only in a single function for novelty value, and is not required 99.9% of the time, but pulls in a massive dependency closure from IPython. 

The function in question detects whether ipywidgets is importable and falls back to regular output.

    # Before: 
    $ nix path-info -S /nix/store/zyw068w4cvkgvdmjpr4i6ihvkc05mn1s-python3.8-rich-9.13.0 -h          
    /nix/store/zyw068w4cvkgvdmjpr4i6ihvkc05mn1s-python3.8-rich-9.13.0	 203.2M

    #After:
    $ nix path-info -S /nix/store/san5g1xh6hpj23szk7xlmsf8jvmmivqq-python3.8-rich-9.13.0 -h
    /nix/store/san5g1xh6hpj23szk7xlmsf8jvmmivqq-python3.8-rich-9.13.0	 107.3M

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 121243` at 32d77de2 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>15 packages marked as broken and skipped:</summary>
  <ul>
    <li>python38Packages.datashader</li>
    <li>python38Packages.ignite</li>
    <li>python38Packages.optuna</li>
    <li>python38Packages.pymc3</li>
    <li>python38Packages.shap</li>
    <li>python38Packages.skorch</li>
    <li>python38Packages.spacy</li>
    <li>python38Packages.textacy</li>
    <li>python38Packages.thinc</li>
    <li>python39Packages.ignite</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/15f8705720428d11d3a3bab349423836">nrfutil</a></li>
    <li><a href="https://gist.github.com/874af45b9ef375461224c768443f6ada">python38Packages.cirq</a></li>
    <li><a href="https://gist.github.com/d4b4ea290a96a4d5d50bf21154fa50cc">python39Packages.cirq</a></li>
    <li><a href="https://gist.github.com/c74f7ee266e8dfd44bf2d887a8555e04">tockloader</a></li>
  </ul>
</details>
<details>
  <summary>82 packages skipped due to time constraints:</summary>
  <ul>
    <li>apache-airflow</li>
    <li>backblaze-b2</li>
    <li>check_systemd</li>
    <li>conan</li>
    <li>deja-dup</li>
    <li>duplicity</li>
    <li>duply</li>
    <li>evdevremapkeys</li>
    <li>ffmpeg-normalize</li>
    <li>gnome-keysign</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>97 packages built successfully:</summary>
  <ul>
    <li>aiodnsbrute</li>
    <li>ansible-lint (python38Packages.ansible-lint)</li>
    <li>checkov</li>
    <li>dpt-rp1-py</li>
    <li>evillimiter</li>
    <li>gdown (python38Packages.gdown)</li>
    <li>kaggle (python38Packages.kaggle)</li>
    <li>ldeep</li>
    <li>lieer</li>
    <li>magic-wormhole (python38Packages.magic-wormhole)</li>
    <li>mathlibtools (python38Packages.mathlibtools)</li>
    <li>papis (python38Packages.papis)</li>
    <li>past-time</li>
    <li>piston-cli</li>
    <li>python38Packages.afdko</li>
    <li>python38Packages.aiosmb</li>
    <li>python38Packages.ansible-kernel</li>
    <li>python38Packages.ansible-runner</li>
    <li>python38Packages.b2sdk</li>
    <li>python38Packages.cve-bin-tool</li>
    <li>python38Packages.datasets</li>
    <li>python38Packages.enrich</li>
    <li>python38Packages.ffmpeg-progress-yield</li>
    <li>python38Packages.graphtage</li>
    <li>python38Packages.habanero</li>
    <li>python38Packages.huggingface-hub</li>
    <li>python38Packages.hyperopt</li>
    <li>python38Packages.internetarchive</li>
    <li>python38Packages.mesa</li>
    <li>python38Packages.moviepy</li>
    <li>python38Packages.msldap</li>
    <li>python38Packages.myfitnesspal</li>
    <li>python38Packages.nltk</li>
    <li>python38Packages.nototools</li>
    <li>python38Packages.panel</li>
    <li>python38Packages.papermill</li>
    <li>python38Packages.parfive</li>
    <li>python38Packages.perfplot</li>
    <li>python38Packages.plexapi</li>
    <li>python38Packages.proglog</li>
    <li>python38Packages.pyppeteer</li>
    <li>python38Packages.python-daemon</li>
    <li>python38Packages.python-miio</li>
    <li>python38Packages.python-mpv-jsonipc</li>
    <li>python38Packages.rbtools</li>
    <li>python38Packages.rich</li>
    <li>python38Packages.sacremoses</li>
    <li>python38Packages.surepy</li>
    <li>python38Packages.tqdm</li>
    <li>python38Packages.transformers</li>
    <li>python38Packages.twine</li>
    <li>python39Packages.afdko</li>
    <li>python39Packages.aiosmb</li>
    <li>python39Packages.ansible-kernel</li>
    <li>python39Packages.ansible-lint</li>
    <li>python39Packages.ansible-runner</li>
    <li>python39Packages.b2sdk</li>
    <li>python39Packages.cve-bin-tool</li>
    <li>python39Packages.datasets</li>
    <li>python39Packages.enrich</li>
    <li>python39Packages.ffmpeg-progress-yield</li>
    <li>python39Packages.gdown</li>
    <li>python39Packages.graphtage</li>
    <li>python39Packages.habanero</li>
    <li>python39Packages.huggingface-hub</li>
    <li>python39Packages.hyperopt</li>
    <li>python39Packages.internetarchive</li>
    <li>python39Packages.kaggle</li>
    <li>python39Packages.magic-wormhole</li>
    <li>python39Packages.mathlibtools</li>
    <li>python39Packages.mesa</li>
    <li>python39Packages.moviepy</li>
    <li>python39Packages.msldap</li>
    <li>python39Packages.myfitnesspal</li>
    <li>python39Packages.nltk</li>
    <li>python39Packages.panel</li>
    <li>python39Packages.papermill</li>
    <li>python39Packages.papis</li>
    <li>python39Packages.parfive</li>
    <li>python39Packages.perfplot</li>
    <li>python39Packages.plexapi</li>
    <li>python39Packages.proglog</li>
    <li>python39Packages.pyppeteer</li>
    <li>python39Packages.python-daemon</li>
    <li>python39Packages.python-miio</li>
    <li>python39Packages.python-mpv-jsonipc</li>
    <li>python39Packages.rbtools</li>
    <li>python39Packages.rich</li>
    <li>python39Packages.sacremoses</li>
    <li>python39Packages.surepy</li>
    <li>python39Packages.tqdm</li>
    <li>python39Packages.transformers</li>
    <li>python39Packages.twine</li>
    <li>r128gain</li>
    <li>sacad</li>
    <li>spotdl</li>
    <li>tinyprog</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement.

**Review by FRidh — CHANGES_REQUESTED** [review]
options like these don't add much values, because one can just add a Python package they want as a dependency to their environment.

It seems ipywidgets is an optional dependency according to the `pyproject.toml`, so in that case I propose removing it entirely as a dependency.

**Comment by risicle** [comment]
It's worth checking first whether there's any (significant) difference between the outputs of a derivation built with and without `ipywidgets` in case the installer does anything conditionally.

**Comment by risicle** [comment]
Doing a basic check it does appear that the sole difference is in `nix-support/propagated-build-inputs` (apart from presumably the file path embedded in the `pyc` files).

Should also see whether there are any conditional ipywidgets-related tests we'd be missing out on by not even including this in `checkInputs`.

**Comment by risicle** [comment]
Nope doesn't look like there is, yeah, I'd be all for removing it.

Now we get to find out which downstream packages break because they were implicitly depending on its inclusion here ;)

**Comment by twoolie** [comment]
@FRidh is there any part of the hydra build system that looks at breakages that occur to packages when their optional (default false) dependencies get bumped? Is there no value in keeping this dependency listed such that it can be tracked by later updates?

**Comment by risicle** [comment]
I think the answer is no. FWIW I did a full rebuild with `ipywidgets` removed and didn't get any (new) failures.

**Comment by twoolie** [comment]
@FRidh Anything else that needs changing? can this merge?

**Pull request merged**
