### PR TITLE
pocketbase: add passthru.updateScript

### PR DESCRIPTION
**Pull request by thilobillerbeck**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ x Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by thilobillerbeck** [comment]
@dit7ya did you already get the chance to look at the changes?

**Comment by thilobillerbeck** [comment]
anyone else? This update is unfortunately already out of date

**Review by dit7ya — APPROVED** [review]
Tested a bit and seems to work fine.

**Comment by dit7ya** [comment]
Result of `nixpkgs-review pr 266464` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>pocketbase</li>
  </ul>
</details>

**Comment by Atemu** [comment]
This is a patch update. While giving maintainers some time for reviews is certainly something you should do with patch updates aswell, this can be in conflict with getting things merged because maintainers are sadly often unresponsive. 

Without prior experience with you guys, it's very hard for a committer to judge whether you'd answer any time soon. If @drupol had known you guys are actually still maintaining this package, they would have likely waited for you to test and approve :)

Additionally, r-ryanttm was just simply faster in getting .4 out. You should see this as a benefit as it saves you a little work too.

@thilobillerbeck just rebase your commit to only add the test script. That should be a very low-risk uncontroversial change and it's slightly cleaner to do that in a separate PR anyways.

**Comment by drupol** [comment]
Hello there,

There's an explanation to everything.

I often use [`dash`](https://github.com/dlvhdr/gh-dash) for reviewing PRs. In `dash`, I have the filter "[From r-ryantm only](https://github.com/drupol/nixos-x260/blob/e127b217763ef98da5479f0b1b9aab8823200cbd/hosts/common/home.nix#L246)" which only shows PRs from r-ryantm's bot, awaiting to be merged and where the status is green.

For each PRs I see in there, I open the PR and do a quick review. If **and only if** the PR is a minor upgrade bump (_like this PR_), I usually merge it immediately. If not, I approve it and wait for someone else or the maintainer to comment.

So, I apologize for the delay here, it's not personal at all, we are all just doing our best to review things here, based on our availabilities. IMHO, that process is still not yet optimized, but we're slowly getting there.

**Comment by Atemu** [comment]
@drupol perhaps you could configure it to exclude PRs less than a few days old. That way package maintainers have a reasonable amount of time to respond.

**Comment by drupol** [comment]
> @drupol perhaps you could configure it to exclude PRs less than a few days old. That way package maintainers have a reasonable amount of time to respond.

Good idea!

Sadly, there's no way to create such filters in `dash`, but from now on, I will only manually select PRs that are at least 7 days old.

**Review by drupol — APPROVED** [review]

**Comment by thilobillerbeck** [comment]
@drupol no worries, I didn't want to bother you. I was just confused on how things went. Thanks for your work. :+1: 

>  You should see this as a benefit as it saves you a little work too.

I absolutely do, this was just about this setting stale and the other one being processed in a few hours, but this seems to be resolved by now. And the fact that this PR contained more than a version bump.

> @thilobillerbeck just rebase your commit to only add the test script. That should be a very low-risk uncontroversial change and it's slightly cleaner to do that in a separate PR anyways.

Just did that. :)

**Pull request merged**
