### PR TITLE
Update utop and camlp4

### PR DESCRIPTION
**Pull request by samuelrivas**
The current version of `camlp4` in `nixpkgs` causes some problems with `utop` and `async`. A way to reproduce it is:
- Get a shell in the latest `nixpkgs`

```
nix-shell -E 'with import ./. {}; stdenv.mkDerivation (with ocamlPackages_4_02_1; { name = "foo"; buildInputs = [ utop async findlib ]; })' "<nixpkgs>
```
- Run utop
- Check that `#utop_help;;` outputs something
- Load Async: `#require "async";;`
- `#utop_help` doesn't output anything, nor does `#topfind_log`

Just upgrading `camlp4` solves the issue, but I tried to upgrade `utop` first while debugging, so feel free to merge that too.

### CODE REVIEW

**Comment by samuelrivas** [comment]
Travis got oomkilled again :(

**Comment by jwilberding** [comment]
:+1:

**Comment by vbgl** [comment]
About camlp4, please check that the `postConfigure` hook is still needed (I think they’ve solved part of the issue upstream https://github.com/ocaml/camlp4/commit/81ed5cf2e857c08e433d891328767ad7f07f1447). Can you also replace `fetchurl` by `fetchzip` or `fetchFromGitHub` that are more reliable than the first. Thank you.

**Comment by samuelrivas** [comment]
Yep, one of the substitutions was not needed, but as far as I can see the other one still is.

I moved to fetchzip as well

**Comment by vbgl** [comment]
Would you like to squash the three `camlp4` commits into one?

**Comment by samuelrivas** [comment]
Done

**Comment by vbgl** [comment]
Thanks.

**Pull request merged**
