### PR TITLE
numix-icon-theme-square: init at 2016-11-23

### PR DESCRIPTION
**Pull request by romildo**
###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by joachifm** [comment]
Travis reports hash mismatch during the darwin build

**Comment by romildo** [comment]
I have no idea why Travis reports hash mismatch. I have obtained the hash using `nix-prefetch-url`:

```
$ nix-prefetch-url -A numix-icon-theme-square.src
downloading ‘https://github.com/numixproject/numix-icon-theme-square/archive/1c30eb02aea3d95c49f95c212702b56e93ac9043.tar.gz’... [1026/0 KiB, 197.4 KiB/s]
unpacking...
path is ‘/nix/store/2l51clanpa5znk95acmdyjfyw3v8qq4c-numix-icon-theme-square-1c30eb02aea3d95c49f95c212702b56e93ac9043-src’
1d2car4dsh1dnim9jlakm035ydqd1f115cagm6zm8gwa5w9annag

$ grep sha256 pkgs/data/icons/numix-icon-theme-square/default.nix
    sha256 = "1d2car4dsh1dnim9jlakm035ydqd1f115cagm6zm8gwa5w9annag";
```

**Comment by joachifm** [comment]
Maybe exclude darwin from platforms/set to linux only until the cause is identified.

**Comment by romildo** [comment]
There is a similar issue with PR [xdgmenumaker: 0.9 -> 1.1](https://github.com/NixOS/nixpkgs/pull/20065) (which is already more than a month old).

**Comment by romildo** [comment]
Is it possible to exclude a platform in the nix expression? If so, how to?

**Comment by joachifm** [comment]
I think you can do something like `platforms = allBut darwin`

**Comment by joachifm** [comment]
Ofc. it'd be nice to understand what's happening & address the underlying issue.

**Comment by joachifm** [comment]
If you do the same for menumaker we can integrate that too.

**Comment by romildo** [comment]
Done.

**Pull request merged**
