### PR TITLE
Applespi: Package and Nixos flag

### PR DESCRIPTION
**Pull request by justgerd**
###### Motivation for this change
Applespi is required on newish macbooks for keyboard and trackpad to work. This adds a package for the driver and a flag to enable it.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by matthewbauer — APPROVED** [review]

**Review by infinisil — APPROVED** [review]
LGTM, just need to fix the conflict and I'll merge it

**Comment by samueldr** [comment]
I think it'd be interesting to have either this or #57419 merged by 19.09, so that newer apple laptops can be made more reasonably usable. Though, I think this PR is more appropriate, as it also adds an option to make it more usable.

Adding this one to the 19.09 milestone; the conflicts are likely trivial (module-list, all-packages), meaning that any nixpkgs contributor can fix it by that time. Hopefully one who can test the change.

**Comment by gerd2002** [comment]
apparently as of the upcoming v5.3 kernel release, the driver has been upstreamed and merged into the kernel? making this PR partially unnecessary as long as it is built into the kernel as a module.
https://github.com/torvalds/linux/commit/038b1a05eae6666b731920e46f47d8e2332e07ff#diff-21f587dcb9b25ed3dcff9dade6b0aa67

**Comment by samueldr** [comment]
No worries, I was triaging random PRs.

At least the current status of this PR is known, anyone wanting to take it up now knows.

**Comment by xaverdh** [comment]
I think this can be closed as #71812 landed in master.

**Comment by justgerd** [comment]
Yep, I agree with you. Applespi seems to have landed in the mainline kernel.

**Pull request closed without merging**
