### PR TITLE
emacsPackages*: Move to emacs*.pkgs

### PR DESCRIPTION
**Pull request by adisbladis**
###### Motivation for this change

This makes it much easier to create customisations around emacs via
the two new convenience passthru attrs:
- `emacs.pkgs.withPackages`: like `emacsWithPackages` but now exists on all emacsen derivations
- `emacs.pkgs`: What used to be emacsPackages is now `emacs.pkgs`

The previous versioned names `emacs*Packages` have been moved to
aliases.nix and are now considered deprecated in favour of `emacs*.pkgs`.

I believe that it's much easier to use this API correctly than the previous API.
I also believe that this provides a much better UX which is more symmetrical (the `-nox` derivations did not have package sets available, so if you wanted to use `emacsWithPackages` with them you had to figure it out on your own), but I'm open to inputs on something I might have missed or other perspectives.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @etu @bqv @alyssais @bendlas @tadfisher 
Also cc @FRidh for how this possibly could be replicated for the Python package sets (to be clear I'm talking about deprecation of the `python*Packages` names).

### CODE REVIEW

**Comment by FRidh** [comment]
> set which contains `emacs.withPackages`. For example, to override
`emacs.pkgs.emacs.withPackages`,

This is the reason we have with Python `let mypython = python3.override { self = mypython;}; in mypython;`. An alternative to this or having to write `python3.pkg.python.withPackages` is to move `withPackages` into the package set like Haskell does it, so you get `python3.pkgs.withPackages`. I find the Haskell approach clearest.

**Comment by bqv** [comment]
No reason python3.withPackages couldn't be the endorsed way, no?

**Comment by FRidh** [comment]
> No reason python3.withPackages couldn't be the endorsed way, no?

Maybe I wasn't clear enough. With the approach in this PR, one *has* to use `python3.pkgs.python.withPackages` if overrides need to be taken into account. There is still a `python3.pkgs.withPackages` but that won't consider the overrides unless one uses `let mypython = python3.override { self = mypython;}; in mypython;.`. This has caused quite some confusion, and that is why I think the Haskell approach is clearest.

**Comment by FRidh** [comment]
Related PR for PHP https://github.com/NixOS/nixpkgs/pull/107044.

**Comment by FRidh** [comment]
Wrote a draft for an RFC on this topic https://github.com/NixOS/rfcs/pull/83.

**Comment by FRidh** [comment]
@adisbladis and I had a short chat. RFC 83 will still take a while, and this follows the spirit of it very closely. The most invasive possible change would likely be `emacs.pkgs` versus `emacsPackages`, but its too early to say. Let's not way on that.

**Pull request merged**
