### PR TITLE
hostapd/wpa_supplicant: update urls

### PR DESCRIPTION
**Pull request by mguentner**
###### Motivation for this change

old urls are unreachable

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
Both appear to redirect to https

**Comment by mguentner** [comment]
I only see a HTTP 200 OK, however the files are also available through https.

```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 212.71.239.96...
* TCP_NODELAY set
* Connected to w1.fi (212.71.239.96) port 80 (#0)
> GET /releases/wpa_supplicant-2.6.tar.gz HTTP/1.1
> Host: w1.fi
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Sun, 17 Sep 2017 11:35:13 GMT
< Server: Apache/2.2.22 (Ubuntu)
< Last-Modified: Sun, 02 Oct 2016 19:29:18 GMT
< ETag: "1d3d98-2a03f4-53de6d7ed9f80"
< Accept-Ranges: bytes
< Content-Length: 2753524
< Content-Type: application/x-gzip
<
{ [1116 bytes data]
100 2688k  100 2688k    0     0  1344k      0  0:00:02  0:00:02 --:--:-- 1183k
* Connection #0 to host w1.fi left intact
```

**Comment by joachifm** [comment]
(Redirects in my browser :) 

It's nice to use https when it is available, seeing as you're updating the urls anyway.

**Comment by mguentner** [comment]
Fair enough. I changed the urls to https.

**Comment by joachifm** [comment]
Thank you

**Pull request merged**
