### PR TITLE
vimPlugins.luvit-meta: init at 2024-01-20

### PR DESCRIPTION
**Pull request by josh**
## Description of changes

Add `vimPlugins.luvit-meta`.

https://github.com/Bilal2453/luvit-meta/

Some more context, I ran into this repo as a dependency while trying to use the [lazydev.nvim](https://github.com/folke/lazydev.nvim) plugin which is already available in nixpkgs as `vimPlugins.lazydev-nvim`.

I used `vim-plugins-updater add` to insert this entry. <del>Should I also run `vim-plugins-updater` itself to generate the `generated.nix` change too? I wasn't sure if that was going to attempt to update all plugin revs.</del>

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by PerchunPak** [comment]
> Should I also run vim-plugins-updater itself to generate the generated.nix change too? I wasn't sure if that was going to attempt to update all plugin revs.

It will, just commit only changes related to this plugin (as it is done in other PRs: [1](https://github.com/NixOS/nixpkgs/pull/334228/files#diff-54bef7a6c9c5497e77086f7935fbfe5c45e285f36f12f15b7044f42430e8e3eb), [2](https://github.com/NixOS/nixpkgs/pull/329264/files#diff-54bef7a6c9c5497e77086f7935fbfe5c45e285f36f12f15b7044f42430e8e3eb), [3](https://github.com/NixOS/nixpkgs/pull/334213/files#diff-54bef7a6c9c5497e77086f7935fbfe5c45e285f36f12f15b7044f42430e8e3eb))

**Review by PerchunPak — APPROVED** [review]
LGTM

Result of `nixpkgs-review pr 331008` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>vimPlugins.luvit-meta</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

[CC](https://github.com/NixOS/nixpkgs/pull/333817#issuecomment-2294798601) @GaetanLepage

**Comment by GaetanLepage** [comment]
Looks good to me, but are you sure that this is actually a vim plugin ?
Have you been able to successfully test it locally ?

**Comment by josh** [comment]
The lua code seems to load correctly when its pushed on to the vim rtp. That said, I don't know if it's better organized in nixpkgs along with other lua packages rather than under `vimPlugins` namespace.

**Comment by GaetanLepage** [comment]
> The lua code seems to load correctly when its pushed on to the vim rtp. That said, I don't know if it's better organized in nixpkgs along with other lua packages rather than under `vimPlugins` namespace.

Probably under `luaPackages.` then. What do you think @teto ?

**Comment by teto** [comment]
if it worked like this then this is fine and we can merge. It seems to be just definitions, not a library. It has no rockspec, is not on luarocks.org either.

**Pull request merged**
