### PR TITLE
[staging-next] Update GuPNP

### PR DESCRIPTION
**Pull request by fabianhjr**
## Description of changes

Due to breakage of gupnp 1.4.z on staging-next, this causes quite a rebuild so targeting staging-next.

Targetting: https://github.com/NixOS/nixpkgs/pull/248496

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
> Due to breakage of gupnp 1.4.z

Will #246931 help? Switching between libsoup 2/3 [^1] is not something I can do bravely and I am honestly more confident to review #246931 instead if the breakage is caused by meson 1.2 :bow: 

[^1]: If I read the changes right bbcd089a930dfa9f0f8797b474a400b9a5ecf4a2 and a40f54fbc2596ce8f52f621648847a68253277cd is doing this. See the #182618 "Main pain points", in my experience some of the breakage can only be observe in run-time, though I did not check what reverse dependencies are evolved here.

**Comment by fabianhjr** [comment]
Will be testing soon, about to finish compilation.

**Comment by fabianhjr** [comment]
Checked https://github.com/NixOS/nixpkgs/pull/246931, that would indeed help.

**Comment by fabianhjr** [comment]
Booted succesfully into a system with these changes on top of staging-next. gnome-shell seems fine, anything I should test in particular?

**Pull request closed without merging**
