### PR TITLE
python3Packages.web: 0.61 -> 0.62, fix build

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Motivation for this change
Closes #95538

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105198` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>bareos</li>
    <li>pepper</li>
  </ul>
</details>
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>ceph</li>
    <li>ceph-client</li>
    <li>libceph</li>
    <li>sabnzbd</li>
    <li>samba4Full</li>
  </ul>
</details>
<details>
  <summary>21 packages built:</summary>
  <ul>
    <li>fava</li>
    <li>flexget</li>
    <li>mnemosyne</li>
    <li>python27Packages.dbutils</li>
    <li>python37Packages.WSME</li>
    <li>python37Packages.cheroot</li>
    <li>python37Packages.cherrypy</li>
    <li>python37Packages.dbutils</li>
    <li>python37Packages.pyalgotrade</li>
    <li>python37Packages.web</li>
    <li>python37Packages.ws4py</li>
    <li>python37Packages.zerobin</li>
    <li>python38Packages.WSME</li>
    <li>python38Packages.cheroot</li>
    <li>python38Packages.cherrypy</li>
    <li>python38Packages.dbutils</li>
    <li>python38Packages.pyalgotrade</li>
    <li>python38Packages.web</li>
    <li>python38Packages.ws4py</li>
    <li>python38Packages.zerobin</li>
    <li>tribler</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105198` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>bareos</li>
    <li>pepper</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>sabnzbd</li>
  </ul>
</details>
<details>
  <summary>25 packages built:</summary>
  <ul>
    <li>ceph (ceph-dev)</li>
    <li>ceph-client</li>
    <li>fava</li>
    <li>flexget</li>
    <li>libceph</li>
    <li>mnemosyne</li>
    <li>python27Packages.dbutils</li>
    <li>python37Packages.WSME</li>
    <li>python37Packages.cheroot</li>
    <li>python37Packages.cherrypy</li>
    <li>python37Packages.dbutils</li>
    <li>python37Packages.pyalgotrade</li>
    <li>python37Packages.web</li>
    <li>python37Packages.ws4py</li>
    <li>python37Packages.zerobin</li>
    <li>python38Packages.WSME</li>
    <li>python38Packages.cheroot</li>
    <li>python38Packages.cherrypy</li>
    <li>python38Packages.dbutils</li>
    <li>python38Packages.pyalgotrade</li>
    <li>python38Packages.web</li>
    <li>python38Packages.ws4py</li>
    <li>python38Packages.zerobin</li>
    <li>sambaFull (samba4Full)</li>
    <li>tribler</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105198` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>bareos</li>
    <li>pepper</li>
  </ul>
</details>
<details>
  <summary>26 packages built:</summary>
  <ul>
    <li>ceph</li>
    <li>ceph-client</li>
    <li>fava</li>
    <li>flexget</li>
    <li>libceph</li>
    <li>mnemosyne</li>
    <li>python27Packages.dbutils</li>
    <li>python37Packages.WSME</li>
    <li>python37Packages.cheroot</li>
    <li>python37Packages.cherrypy</li>
    <li>python37Packages.dbutils</li>
    <li>python37Packages.pyalgotrade</li>
    <li>python37Packages.web</li>
    <li>python37Packages.ws4py</li>
    <li>python37Packages.zerobin</li>
    <li>python38Packages.WSME</li>
    <li>python38Packages.cheroot</li>
    <li>python38Packages.cherrypy</li>
    <li>python38Packages.dbutils</li>
    <li>python38Packages.pyalgotrade</li>
    <li>python38Packages.web</li>
    <li>python38Packages.ws4py</li>
    <li>python38Packages.zerobin</li>
    <li>sabnzbd</li>
    <li>samba4Full</li>
    <li>tribler</li>
  </ul>
</details>

**Comment by jonringer** [comment]
if you want to wait for https://github.com/NixOS/nixpkgs/pull/104781 to be merged, you can drop the ignore collision commits

**Comment by jonringer** [comment]
#104781 was merged, you should be able to remove the ignore collision commits

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105198` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>bareos</li>
    <li>pepper</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python39Packages.WSME</li>
    <li>sambaFull (samba4Full)</li>
  </ul>
</details>
<details>
  <summary>31 packages built:</summary>
  <ul>
    <li>ceph (ceph-dev)</li>
    <li>ceph-client</li>
    <li>fava</li>
    <li>flexget</li>
    <li>libceph</li>
    <li>mnemosyne</li>
    <li>python37Packages.WSME</li>
    <li>python37Packages.cheroot</li>
    <li>python37Packages.cherrypy</li>
    <li>python37Packages.dbutils</li>
    <li>python37Packages.pyalgotrade</li>
    <li>python37Packages.web</li>
    <li>python37Packages.ws4py</li>
    <li>python37Packages.zerobin</li>
    <li>python38Packages.WSME</li>
    <li>python38Packages.cheroot</li>
    <li>python38Packages.cherrypy</li>
    <li>python38Packages.dbutils</li>
    <li>python38Packages.pyalgotrade</li>
    <li>python38Packages.web</li>
    <li>python38Packages.ws4py</li>
    <li>python38Packages.zerobin</li>
    <li>python39Packages.cheroot</li>
    <li>python39Packages.cherrypy</li>
    <li>python39Packages.dbutils</li>
    <li>python39Packages.pyalgotrade</li>
    <li>python39Packages.web</li>
    <li>python39Packages.ws4py</li>
    <li>python39Packages.zerobin</li>
    <li>sabnzbd</li>
    <li>tribler</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 105198` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package marked as broken and skipped:
</summary>
<ul>
<li>pepper</li>
</ul>
</details>
<details>
<summary>
28 packages built:
</summary>
<ul>
<li>fava</li>
<li>flexget</li>
<li>mnemosyne</li>
<li>python37Packages.WSME</li>
<li>python37Packages.cheroot</li>
<li>python37Packages.cherrypy</li>
<li>python37Packages.dbutils</li>
<li>python37Packages.pyalgotrade</li>
<li>python37Packages.web</li>
<li>python37Packages.ws4py</li>
<li>python37Packages.zerobin</li>
<li>python38Packages.WSME</li>
<li>python38Packages.cheroot</li>
<li>python38Packages.cherrypy</li>
<li>python38Packages.dbutils</li>
<li>python38Packages.pyalgotrade</li>
<li>python38Packages.web</li>
<li>python38Packages.ws4py</li>
<li>python38Packages.zerobin</li>
<li>python39Packages.cheroot</li>
<li>python39Packages.cherrypy</li>
<li>python39Packages.dbutils</li>
<li>python39Packages.pyalgotrade</li>
<li>python39Packages.web</li>
<li>python39Packages.ws4py</li>
<li>python39Packages.zerobin</li>
<li>sabnzbd</li>
<li>tribler</li>
</ul>
</details>

**Pull request merged**
