### PR TITLE
network-manager: 1.6.2 -> 1.8.2

### PR DESCRIPTION
**Pull request by bkchr**
###### Motivation for this change
Requires https://github.com/NixOS/nixpkgs/pull/29371 for nox-review without errors.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by teto** [comment]
Thanks for the patch. Tested with wifi/wired connections, works well here <3

**Comment by teto** [comment]
Hum actually when trying to setup my vpn so maybe an override for modprobe might be required ? 
I am getting the source to check.
```
sept. 15 10:33:30 jedha ipsec_starter[3087]: 
sept. 15 10:33:32 jedha NetworkManager[716]: Starting strongSwan 5.6.0 IPsec [starter]...
sept. 15 10:33:32 jedha NetworkManager[716]: Loading config setup
sept. 15 10:33:32 jedha NetworkManager[716]: Loading conn 'nm-ipsec-l2tp-3205'
sept. 15 10:33:32 jedha ipsec_starter[3217]: Starting strongSwan 5.6.0 IPsec [starter]...
sept. 15 10:33:32 jedha ipsec_starter[3217]: Loading config setup
sept. 15 10:33:32 jedha ipsec_starter[3217]: Loading conn 'nm-ipsec-l2tp-3205'
sept. 15 10:33:32 jedha NetworkManager[716]: sh: modprobe : commande introuvable
sept. 15 10:33:32 jedha NetworkManager[716]: sh: modprobe : commande introuvable
sept. 15 10:33:32 jedha NetworkManager[716]: sh: modprobe : commande introuvable
sept. 15 10:33:32 jedha NetworkManager[716]: sh: modprobe : commande introuvable
sept. 15 10:33:32 jedha NetworkManager[716]: sh: modprobe : commande introuvable
sept. 15 10:33:32 jedha NetworkManager[716]: found netkey IPsec stack
sept. 15 10:33:32 jedha ipsec_starter[3217]: found netkey IPsec stack
sept. 15 10:33:32 jedha ipsec_starter[3233]: Attempting to start charon...
```

**Comment by teto** [comment]
I was wondering why the nixos-rebuild succeeded even though I could not compile it from source.
I added autoreconfHook in nativeBuildInputs which got me a bit farther (than the previous error "substitute(): ERROR: file 'configure' does not exist") but I believe that's because the archive embeds already a configure script.

Now it fails on
```
./configure: line 27817: syntax error near unexpected token `1.0'
./configure: line 27817: `GTK_DOC_CHECK(1.0)'
```
even though I have gnome2.gtk-doc installed. Wouldn't it be best if the derivation could work from the source rather than the archive ?

**Comment by teto** [comment]
The following patch seems to help. with-distro and with-libsoup flags seem useless now (`configure: WARNING: unrecognized options: --with-distro, --with-libsoup` )
https://github.com/teto/nixpkgs/commit/486e61d46994fd4cf514f8e635c43fb203994edf

There is  another problem I don't know how to fix
```
config.status: executing po/stamp-it commands
config.status: error: po/Makefile.in.in was not created by intltoolize.
```

**Comment by bkchr** [comment]
Hmm weird that you need this patch. My compilation worked without any problems, but I will integrate your patch :)

**Comment by bkchr** [comment]
Okay, I updated the pr. I also could fix the po/Makefile error.

**Comment by teto** [comment]
Great now it compiles just fine even without the configure script.

**Comment by jtojnar** [comment]
Could you also bump the applet version, please? It will probably work better if they match.

**Comment by eqyiel** [comment]
Thanks for working on this.  1.8.2 at least is critical if you use NM for VPN connections because it contains this commit: https://cgit.freedesktop.org/NetworkManager/NetworkManager/commit/?id=6f61497a1beb20ff2f224d163685b78c7baa76b0

Other discussions:
https://bugs.launchpad.net/ubuntu/+source/network-manager/+bug/1624317
https://bugzilla.gnome.org/show_bug.cgi%3Fid=783569

**Comment by teto** [comment]
I still fail to connect to my VPN but this might be unrelated to the PR and more having to strongSwan.
I would like to find the source of the `sh: modprobe : commande introuvable` ("command not found"). is that a nm shell script ? or a strongSwan ?  as for the "PKCS11 module '<name>' lacks library path", I don't know if that matters.
```
sept. 16 14:40:49 jedha NetworkManager[12801]: Starting strongSwan 5.6.0 IPsec [starter]..
sept. 16 14:40:49 jedha NetworkManager[12801]: Loading config setup
sept. 16 14:40:49 jedha NetworkManager[12801]: Loading conn 'nm-ipsec-l2tp-26372'
sept. 16 14:40:49 jedha ipsec_starter[26401]: Starting strongSwan 5.6.0 IPsec [starter]...
sept. 16 14:40:49 jedha ipsec_starter[26401]: Loading config setup
sept. 16 14:40:49 jedha ipsec_starter[26401]: Loading conn 'nm-ipsec-l2tp-26372'
sept. 16 14:40:49 jedha NetworkManager[12801]: sh: modprobe : commande introuvable
sept. 16 14:40:49 jedha NetworkManager[12801]: sh: modprobe : commande introuvable
sept. 16 14:40:49 jedha NetworkManager[12801]: sh: modprobe : commande introuvable
sept. 16 14:40:49 jedha NetworkManager[12801]: sh: modprobe : commande introuvable
sept. 16 14:40:49 jedha NetworkManager[12801]: sh: modprobe : commande introuvable
sept. 16 14:40:49 jedha NetworkManager[12801]: found netkey IPsec stack
sept. 16 14:40:49 jedha ipsec_starter[26401]: found netkey IPsec stack
sept. 16 14:40:49 jedha ipsec_starter[26428]: Attempting to start charon...
sept. 16 14:40:49 jedha NetworkManager[12801]: <warn>  [1505540449.9427] vpn-connection[0x
sept. 16 14:40:49 jedha charon[26429]: 00[DMN] Starting IKE charon daemon (strongSwan 5.6.
sept. 16 14:40:49 jedha charon[26429]: 00[CFG] PKCS11 module '<name>' lacks library path
sept. 16 14:40:50 jedha charon[26429]: 00[CFG] dnscert plugin is disabled
sept. 16 14:40:50 jedha charon[26429]: 00[NET] using forecast interface wlp2s0
```

**Comment by eqyiel** [comment]
I bumped the applet version, @bkchr could you cherry-pick https://github.com/eqyiel/nixpkgs/commit/07b6a8f71d3ed53c9fd1fd81f0a856ee95cfb7b5?

I'm using both right now and it seems OK: 
```
eqyiel@ayanami ~ % journalctl -u network-manager -b 0 -l | cat
-- Logs begin at Wed 2017-09-06 08:21:55 ACST, end at Sat 2017-09-16 18:23:01 ACST. --
Sep 16 18:19:25 ayanami systemd[1]: Starting Network Manager...
Sep 16 18:19:26 ayanami systemd[1]: Started Network Manager.
Sep 16 18:19:33 ayanami NetworkManager[1049]: libndp: ndp_sock_open: Failed to create ICMP6 socket.
Sep 16 18:19:33 ayanami NetworkManager[1049]: <error> [1505551773.9445] device (wlp3s0): addrconf6: failed to start neighbor discovery: failure creating libndp socket: Address family not supported by protocol (97)
Sep 16 18:19:33 ayanami dhclient[1441]: DHCPREQUEST on wlp3s0 to 255.255.255.255 port 67
Sep 16 18:19:33 ayanami dhclient[1441]: DHCPACK from 192.168.1.1
Sep 16 18:19:34 ayanami dhclient[1441]: bound to 192.168.1.174 -- renewal in 20729 seconds.
```

(the errors are related to having disabled ipv6)

**Comment by bkchr** [comment]
I could cherry pick, but I think you could also open your own pull request. As I understand that right, the applet is only for gnome? It you want, open a pr and link this pr :)

**Comment by bkchr** [comment]
Added your commit and removed libselinux. nox-review is still running for the changes.

**Comment by bkchr** [comment]
nox-review did not report any errors :)

**Comment by eqyiel** [comment]
Thanks, I wasn't sure what to do about that!

**Comment by eqyiel** [comment]
Can we move this forward?

**Comment by bkchr** [comment]
@Phreedom @rickynils could you merge this pr?

**Comment by eqyiel** [comment]
@rickynils thanks!

**Pull request merged**
