### PR TITLE
dwarf-fortress: add dfhack

### PR DESCRIPTION
**Pull request by a1russell**
I added [dfhack](https://github.com/DFHack/dfhack) as an option to dwarf-fortress via the enableDFHack option.

At the same I did do some refactoring in order to keep the code clean, adding template files, etc. Otherwise I feel the addition of dfhack would have made things quite ugly.

### CODE REVIEW

**Comment by the-kenny** [comment]
Did you see https://github.com/NixOS/nixpkgs/pull/9972 ?

**Comment by a1russell** [comment]
No, unfortunately I didn't. That must have happened as I was working on this. I did try to ask around on IRC a few times, and @roconnor said it would be fine for me to work on this, but I never caught you @the-kenny.

I haven't had a chance to try that new package yet, but from reading it seems that it would require two steps: run `dfhack_install_dir` and *then* run `dfhack`.

My approach I am hoping is cleaner than that. If I'm wrong about how to run dfhack from #9972 then problem solved for me.

**Comment by the-kenny** [comment]
If this PR implements a cleaner solution, I'm all for it. Unfortunately I'm quite busy right now and can't say when I'll be able to compare both implementations.

**Comment by a1russell** [comment]
I've attempted to contact @robbinch who created the other pull request. I'll try and get their feedback. Perhaps we can merge our efforts somehow. Anyone else you would trust to review the implementations in lieu of yourself, @the-kenny?

**Comment by robbinch** [comment]
Hi, my opinion follows:
##### Pros
* Integrates better with existing dwarf fortress package.
* DFHack binary includes stonesense. (#10082 doesn't)

##### Cons
* Does not build DFHack from source. (#10082 does)

Is it too much to ask to build DFHack from source in this PR? I think doing this will make an even cleaner solution.

**Comment by a1russell** [comment]
@robbinch Sure, I'll change it to build from source. Thanks for taking a look.

**Comment by a1russell** [comment]
Since it was quite a bit of difference, and I wanted to be able to see this version as a reference, I did the work to build dfhack from source in a new branch and put it into #10800. I'll close this PR if you end up liking #10800.

**Comment by a1russell** [comment]
Closed in favor of #10800

**Pull request closed without merging**
