### PR TITLE
processing: 3.4 -> 3.5.3

### LINKED ISSUE #66518: Processing seems broken
**Describe the bug**

```
$ nix run nixpkgs.processing
trace: WARNING: Public updates for Oracle Java SE 8 released after January 2019 will not be available for business, commercial or production use without a commercial license. See https://java.com/en/download/release_notice.jsp for more information.
hash mismatch in fixed-output derivation '/nix/store/74jkcqrddp7nxijr3ha09d2mnfck5836-reference.zip':
  wanted: sha256:0ai0cr62gc7n6y22ki3qibyj1qnlaxv1miqxmmahfk3hpbyfqz9n
  got:    sha256:198bpk8mzns6w5h0zdf50wr6iv7sgdi6v7jznj5rbsnpgyilxz35
cannot build derivation '/nix/store/sdxr2sy0w81hfv24y7n1h0vcdk6hd2y1-processing3-3.4.drv': 1 dependencies couldn't be built
[0 built (1 failed)]
error: build of '/nix/store/sdxr2sy0w81hfv24y7n1h0vcdk6hd2y1-processing3-3.4.drv' failed
```

**Metadata**

```
$ nix run nixpkgs.nix-info -c nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.49, NixOS, 19.03.172866.4649b6ef4b5 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.172866.4649b6ef4b5"`
 - channels(dehos): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by lopsided98**
###### Motivation for this change

Package was out-of-date and broken due to a change of an unversioned URL.

Fixes #66518.

###### Things done

Updates processing to the latest version and fixes the `reference.zip` hash. AFAIK, there is no versioned URL for this file.

Since Processing 3 is the only version included in nixpkgs now, I moved the `processing3` attribute to `aliases.nix`.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @juliendehos Can you see if this works for you?

### CODE REVIEW

**Comment by mmahut** [comment]
@GrahamcOfBorg build processing

**Comment by juliendehos** [comment]
Works for me too. Thanks.

**Comment by maxdevjs** [comment]
@lopsided98 @juliendehos I am on (NixOS) 19.03 channel and I still have the old Processing issue (as I report in #73900). To have the fixed package what should I do? To switch to 19.09 channel?

**Comment by juliendehos** [comment]
@maxdevjs Yes, or just run `nix run -f channel:nixos-19.09 processing -c processing`

**Comment by maxdevjs** [comment]
@juliendehos thank you very much

**Comment by maxdevjs** [comment]
Curiosity: how could I know that the fixed package is in another channel? Is [https://nixos.org/nixos/packages.html?attr=processing](https://nixos.org/nixos/packages.html?attr=processing) the only way?

**Comment by volth** [comment]
I think we could remove `reference.zip` from the `processing` derivation (completely or by moving it to a separate `processing-reference`), because upstream constantly changes it and it breaks `sha256`

**Comment by maxdevjs** [comment]
Happening again today

**Comment by maxdevjs** [comment]
Hello, could that `reference.zip` be removed? I upgraded to `20.03` and still can not install processing :)

**Pull request merged**
