### PR TITLE
lib: Fix #30902

### LINKED ISSUE #30902: Derivation platform checking compares against wrong machine
## Issue description

The logic in `pkgs/stdenv/generic/check-meta.nix` for checking the `meta.platforms` attribute currently compares `meta.platforms` against the `stdenv.system` attribute. In my cross-compilation environment `stdenv.system` is the double of my build platform, `x86_64-linux`.

It seems to me like this should rather be compared against `stdenv.hostPlatform.system`. Unfortunately, this attribute has slightly different semantics than `stdenv.system`. For instance, in the case of `armv7l-hf-multiplatform` it is `arm-linux` whereas the value expected by `uboot` is something like `armv7l-linux`. 

How much detail should `meta.system` capture?

Pinging @Ericson2314.

### PR DESCRIPTION
**Pull request by Ericson2314**
###### Motivation for this change

See the "lib, stdenv: Check..." commit for details. 

Work in progress because I need to overhaul `release-lib.nix`, and maybe other uses of `meta.platforms`.

 Fixes #30902

###### Things done

Need to ensure `release-lib.nix` packages still eval fine.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

CC @bgamari @dtzWill

### CODE REVIEW

**Comment by grahamc** [comment]
@GrahamcOfBorg eval

**Comment by Ericson2314** [comment]
@dtzWill lets land this first. Frankly, I'm not sure how you made it so far without it.

**Comment by dtzWill** [comment]
Haha, not sure! Will take a look shortly.

**Comment by Ericson2314** [comment]
I can eval everything locally, but it kills @GrahamcOfBorg so not sure what that's about. I hope its not just me making everything more expensive.

**Comment by Ericson2314** [comment]
The message is from Boehm GC, to be clear.

**Comment by dtzWill** [comment]
I could be wrong but I think evaluating all of nixpkgs is beyond our Borg friend's limits currently.

Large hydra evaluations specifically strip out a bunch of stuff to reduce memory, so it's not without precedent to find evaluating all the things a large task :).

That said, it may be worth quickly testing time/memory of a large evaluation before and after this change -- regressing too badly on this will negatively impact almost everyone and probably summon an angry mob.  But just be sure this doesn't 2x evaluation time or something :P.

Borg may want to use a larger heap, which I think is the usual way to workaround that error. I forget the environment variable name O:).

Not sure where previous discussion of this ended up, for example: https://github.com/NixOS/nixpkgs/pull/33747#issuecomment-357058857

Ideally of course we'd be constantly making evaluation faster using less memory :D.

**Comment by grahamc** [comment]
> I think evaluating all of nixpkgs is beyond our Borg friend's limits currently.

OfBorg's evaluators have 16G of RAM.

> it may be worth quickly testing time/memory of a large evaluation before and after this change -- regressing too badly on this will negatively impact almost everyone and probably summon an angry mob.

Agreed :)

Especially on:

> just be sure this doesn't 2x evaluation time or something :P

> Borg may want to use a larger heap, which I think is the usual way to workaround that error. I forget the environment variable name O:).

I think we want `GC_MAXIMUM_HEAP_SIZE` but I'm not sure what to set it to. I think this eval error is reproducible outside of borg using the outpaths.nix https://github.com/NixOS/ofborg/blob/released/ofborg/src/outpaths.nix Basically:

```
cp ../ofborg/ofborg/src/outpaths.nix .; nix-env -f ./outpaths.nix -qaP --no-name --out-path --arg checkMeta true > outs
```

Can someone do a bit of trial and error on that? I can set the variable on the evaluators.

**Comment by grahamc** [comment]
@GrahamcOfBorg eval

also this ^ I'll keep tabs on the eval in my monitoring.

**Comment by dtzWill** [comment]
I forget if it helped but I'll just note that we do use a boehmgc that is /not/ tuned for "large" heaps where IIRC "large" is definitely smaller than what we use on most evals.

https://github.com/ivmai/bdwgc/blob/b5cab5aacd263577af3502ecf068612591d27704/configure.ac#L840
https://github.com/ivmai/bdwgc/blob/master/doc/README.macros

Err nevermind this, until I look into it more (or someone else does), just wanted to mention while on the subject.

**Comment by grahamc** [comment]
This PR doesn't seem to have a substantial impact ...  but I only looked at four evals in some fairly lousy data.

**Comment by grahamc** [comment]
@dtzWill before pinging Eelco, can you try it and see if it makes an improvement? :)

**Comment by dtzWill** [comment]
> @dtzWill before pinging Eelco, can you try it and see if it makes an improvement? 

Sure.  But since [he introduced the enableLargeConfig option](8e2e4216ba09cc0412c9f3d1a1b8076e77827be8) it seemed likely he had existing knowledge/experience/opinions/insights on the subject before investigating myself.  Anyway, point taken I'll drop it until I have evidence it helps :).

**Comment by grahamc** [comment]
It seems master went over the line, so we must have been mighty close:

 - https://github.com/NixOS/ofborg/commit/03a2d8427a83fdc893a965cc3b5c5a59b5c0509d
 - https://github.com/NixOS/ofborg/commit/70b55fba42ead4ac21a43c9c9f917ed9ecdd4641

@GrahamcOfBorg eval

**Comment by Ericson2314** [comment]
Woah, surprised this is considered a rebuild, but glad it evals!

**Comment by Ericson2314** [comment]
@vcunat have time to luck at this? I'll track down the rebuilds cause, but I think the basic concept isn't going to change to much from this.

**Comment by vcunat** [comment]
I've known about this PR from the beginning, but even this weekend got filled by issues that felt more urgent (like retpoline for our kernels).

The approach sounds OK in general, though I'd be careful about impact on overall evaluation performance.

**Comment by Ericson2314** [comment]
@vcunat I'd like to add some cross jobs to nixpkgs-unstable for 18.03, and this is more or less a prereq to doing that properly.

**Comment by Ericson2314** [comment]
e.g. https://hydra.nixos.org/jobset/nixpkgs/cross-trunk/evals?page=1 somebody just destroyed it, and I have no idea how.

**Comment by dtzWill** [comment]
@Ericson2314 can you reproduce any of those failures? Generally (most/all?) are due to building the cross-cc, but that seems to build fine for me in various configurations.
This job includes cross-cc and is marked as failing but builds for me on master:
```
$ nix build -f pkgs/top-level/release-cross.nix rpi.busybox
```

Maybe builders were having a bad day? Or did you do something to fix things since those evals?

**Comment by vcunat** [comment]
_Someone restarted them and they seem mostly OK again._

**Comment by Ericson2314** [comment]
@dtzWill I restarted hydra. Spurious or not, though, I want us to be held to (some of) the builds succeeding.

**Comment by dtzWill** [comment]
How's this looking?

**Comment by Ericson2314** [comment]
I should rebase, and fix the rebuilds. Will try tonight!

**Comment by vcunat** [comment]
This is still waiting for some fixes, right?

**Comment by Ericson2314** [comment]
Yeah sorry. Didn't do it that last weekend or this one. I'll try now.

**Comment by vcunat** [comment]
I suppose we can cherry-pick such stuff to 18.03, during March at least.

**Comment by lopsided98** [comment]
#36232 has a bunch of other changes for U-Boot, so I included the `removeAttrs` fix there.

**Comment by Ericson2314** [comment]
Only checked linux, but just need to fix `pharo` eval on that platform.

**Comment by Ericson2314** [comment]
Ok, pre-fixed all the misbehaving packages so this is ready for final review! No more rebuilds anymore.

**Comment by Ericson2314** [comment]
I need to do a PR on top of this, so I'm going to merge it. Feel free to revert if eval time problems arise, but this should be good in all other respects.

**Comment by orivej** [comment]
@Ericson2314 Could you help updating this platforms line in `boost`: https://github.com/NixOS/nixpkgs/blob/18.03/pkgs/development/libraries/boost/generic.nix#L92? Currently Hydra attempts to build `boost155` for Aarch64 and fails.

**Comment by Ericson2314** [comment]
One can fall back on the legacy stuff by using https://github.com/NixOS/nixpkgs/blob/master/lib/systems/doubles.nix#L45 . I think that's easiest for now.

**Comment by orivej** [comment]
Thank you! We can replace `platforms.unix` with `systems.doubles.unix` on that line to fix it. However, may we express it in a non-legacy way?

**Comment by Ericson2314** [comment]
Yeah. The new ones are https://github.com/NixOS/nixpkgs/blob/master/lib/systems/for-meta.nix made from https://github.com/NixOS/nixpkgs/blob/master/lib/systems/inspect.nix . There's still no negation but if you combine the x86 pattern with all the unix ones, you can get `isx86 && isUnix`.

**Pull request merged**
