### PR TITLE
jetbrains.{idea,pycharm}-community-src: 2023.3.2 -> 2024.1.3

### PR DESCRIPTION
**Pull request by ShadowRZ**
## Description of changes

Bumps the source build of IDEA / PyCharm Community to 2024.1.3.

Also fixes a security issue in earlier version: https://blog.jetbrains.com/security/2024/06/updates-for-security-issue-affecting-intellij-based-ides-2023-1-and-github-plugin/

IDEA 2024.1.3: https://blog.jetbrains.com/idea/2024/06/intellij-idea-2024-1-3/
PyCharm 2024.1.3: https://youtrack.jetbrains.com/articles/PY-A-233538230/PyCharm-2024.1.3-241.17890.14-build-Release-Notes

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by NyCodeGHG** [comment]
2024.1.2 is out:
https://blog.jetbrains.com/idea/2024/05/intellij-idea-2024-1-2/
https://blog.jetbrains.com/pycharm/2024/05/pycharm-2024-1-2/

**Comment by ShadowRZ** [comment]
> 2024.1.2 is out: https://blog.jetbrains.com/idea/2024/05/intellij-idea-2024-1-2/ https://blog.jetbrains.com/pycharm/2024/05/pycharm-2024-1-2/

Updated: https://github.com/NixOS/nixpkgs/commit/21d06554fd51f8bd7b5245a7d1d392ecc4092999

**Review by leona-ya — CHANGES_REQUESTED** [review]
I'm sorry, but can you update again because of https://blog.jetbrains.com/security/2024/06/updates-for-security-issue-affecting-intellij-based-ides-2023-1-and-github-plugin/ please?

**Comment by ShadowRZ** [comment]
The PR has been updated to use IDEA / PyCharm 2024.1.3.

**Comment by NyCodeGHG** [comment]
Result of `nixpkgs-review pr 316185` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>jetbrains.idea-community (jetbrains.idea-community-src)</li>
    <li>jetbrains.pycharm-community (jetbrains.pycharm-community-src)</li>
  </ul>
</details>
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>jetbrains.clion</li>
    <li>jetbrains.datagrip</li>
    <li>jetbrains.dataspell</li>
    <li>jetbrains.gateway</li>
    <li>jetbrains.goland</li>
    <li>jetbrains.idea-community-bin</li>
    <li>jetbrains.idea-ultimate</li>
    <li>jetbrains.mps</li>
    <li>jetbrains.phpstorm</li>
    <li>jetbrains.pycharm-community-bin</li>
    <li>jetbrains.pycharm-professional</li>
    <li>jetbrains.rider</li>
    <li>jetbrains.ruby-mine</li>
    <li>jetbrains.rust-rover</li>
    <li>jetbrains.webstorm</li>
    <li>jetbrains.writerside</li>
  </ul>
</details>

**Comment by NyCodeGHG** [comment]
build log: https://gist.github.com/NyCodeGHG/19e6192d7155e0dfe921372db8f8e1d3

**Comment by NyCodeGHG** [comment]
@ofborg build jetbrains.idea-community-src jetbrains.pycharm-community-src

**Review by ShadowRZ — COMMENTED** [review]
> build log: https://gist.github.com/NyCodeGHG/19e6192d7155e0dfe921372db8f8e1d3 

👀 Seems like JetBrains JDK has been upgraded to 21 and broke IDEA build. It can compile on my machine as it's still using JDK 17.

I'm not sure if I can make it compile under JDK 21.

**Review by ShadowRZ — COMMENTED** [review]
OK I dont't think it can be migrated to JDK 21 simply, and per https://intellij-support.jetbrains.com/hc/en-us/community/posts/18702212774418/comments/18766543552146 bumping to JDK 21 is not even scheduled for the 2024.2 version :(

**Comment by ShadowRZ** [comment]
With https://github.com/NixOS/nixpkgs/pull/320808 it should be fine to merge this.

**Review by leona-ya — APPROVED** [review]
thanks! :3

**Pull request merged**
