### PR TITLE
rust-rover: init at 2023.2-EAP

### PR DESCRIPTION
**Pull request by sylk0s**
## Description of changes

Added RustRover package for the new Jetbrains Rust IDE.
https://www.jetbrains.com/rust/

Also in the process I had to run the updater script for a few other Jetbrains products in the process of making RustRover work. I more or less used the exact same template as RubyMine.

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sylk0s** [comment]
So... my guess is that the error here is coming from the lack of darwin entry for RustRover in the versions.json? I'm not familiar with MACOS/darwin, so I didn't add a darwin entry and everything seemed to work fine regardless. Otherwise I'm not sure why the ofborg-eval isn't working. Feedback here would be appreciated :3

**Comment by sylk0s** [comment]
After poking around with expanding macros, It's giving a different error than the one from that issue you mentioned, but it's still not working. 

20230915_12h05m00s_grim

My thoughts are generally that the IDE is still in an open early access stage, and so bugs are to be expected all around, so I'm not *as* worried about trying to patch every thing wrong with it for now... may be better to wait until the IDE is closer to full release?

It's also a different error, so maybe there's something else wrong with it as well? Could you try to replicate the same error that intellij-rust was giving?

**Comment by GenericNerdyUsername** [comment]
Is this obsoleted by #255283 ?

**Comment by sylk0s** [comment]
I think so. That PR seems to have done a better job than I did in adding the package...

**Pull request closed without merging**
