### PR TITLE
Gnome 3.34.4

### PR DESCRIPTION
**Pull request by hedning**
###### Motivation for this change

mutter news:

```

* Handle mode set race conditions more gracefully [Jonas; !1007]
* Fix fallback to GLES2 [Adam; #635]
* Fix interoperation with wl_data_device_manager v1 [Carlos; #965]
* Fix visual glitches with offscreen effects applied [Georges; !992]
* Favor text over images in clipboard manager [Carlos; #919]
* Fixes crashes [Jonas, Carlos; !961, !869]
* Plugged memory leaks [Sebastian, Adam; !1002, !1011]
* Misc. bug fixes [Carlos, Robert, Olivier; !1005, #878, !1031, !1034, !1040]

```

gnome-shell news:
```

* Switch screen-recorder back to VP8 [Björn; #256]



```
epiphany news:

```
 * Changing web app icon in preferences dialog should copy icon (#810, ignapk)
 * Fix new tab page with few items in history (#986)
 * Fix Favorites and Mobile bookmarks not tagged correctly when localized (#1015, Jonathan Kang)
 * Fix password manager user account selector (#1018)
 * Hide view source context menu item when on view source page (#1046)
 * Fix memory corruption in view source mode (#1065)
 * Fix crash when parsing session state (#1092)
 * Fix improper warning when closing multiple tabs (#1093)
 * Fix occasional failure to start up (!537)
 * Fix memory corruption when loading adblock filters
```
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by worldofpeace** [comment]
@hedning I'm going to try to do backports on the stable channel consistently, so :+1: on backports.

**Comment by worldofpeace** [comment]
I built the gnome vm with this PR.

**Comment by hedning** [comment]
Yep, running with this on hardware at the moment, seems fine.

**Comment by worldofpeace** [comment]
@hedning Added commits for updates that are just for the apps.

**Comment by jtojnar** [comment]
Changelogs

```
1de94d59af634516ce1085f6e99f2a33b086e22f: gnome3.gnome-control-center: 3.34.2 -> 3.34.4
	(https://ftp.gnome.org/pub/GNOME/sources/gnome-control-center/3.34/gnome-control-center-3.34.4.news)
	================
	Version 3.34.4
	================
	
	- Updated translations
	
	Thunderbolt
	- Fix memory leak
	
	Printers
	- Fix read of freed memory
	
	User Accounts
	- Use absolute path of command usermod
	- Fix carousel arrow location when animations are disabled
	- Fix memory leak
	- Fix uninitialized variable
	
	Region & Language
	- Fix LC_* variables not being correctly reset
	
	Sound
	- Add missing subwoofer icons
	
	
a5000f07a64689ccc6fb926485bb84b0ae297244: gnome3.evolution-data-server: 3.34.3 -> 3.34.4
	(https://ftp.gnome.org/pub/GNOME/sources/evolution-data-server/3.34/evolution-data-server-3.34.4.news)
	Evolution-Data-Server 3.34.4 2020-02-14
	---------------------------------------
	
	Bug Fixes:
		I#179 - Calendar: Handle errors in file backend's refresh thread gracefully (Milan Crha)
		I#184 - WebDAV: Privilege with multiple child elements not handled properly (Milan Crha)
		evo-I#686 - Broken search folder that includes all mails from other search folders (Milan Crha)
	
	Miscellaneous:
		EDBusServer: Delay new module load (Milan Crha)
		alarm-notify: Double-free with certain types of the reminder (Milan Crha)
	
	Translations:
		Umarzuki Bin Mochlis Moktar (ms)
	
	
769786b4a63fceb9e9e8b081adbc9ed1050d12da: gnome3.iagno: 3.34.4 -> 3.34.5
	(https://ftp.gnome.org/pub/GNOME/sources/iagno/3.34/iagno-3.34.5.news)
	3.34.5 â€“ February 14, 2020
	=============================
	
	Translation release, with some metadatas fixes.
	
	Updated translation:
	  Malay: Umarzuki Bin Mochlis Moktar
	
	
d02a96dd6c7c62124b1c63e485416accf3635c03: gnome3.gnome-tetravex: 3.34.1 -> 3.34.4
	(https://ftp.gnome.org/pub/GNOME/sources/gnome-tetravex/3.34/gnome-tetravex-3.34.4.news)
	3.34.4 - February 14, 2020
	=============================
	
	Just a translation release.
	
	Updated translation:
	  Malay: Umarzuki Bin Mochlis Moktar
	
	
0bd27fd551e96c6dfb2b4328970c5c8a9f73d0b7: gnome3.gnome-taquin: 3.34.3 -> 3.34.4
	(https://ftp.gnome.org/pub/GNOME/sources/gnome-taquin/3.34/gnome-taquin-3.34.4.news)
	3.34.4 – February 14, 2020
	=============================
	
	Translation release, with some metadatas fixes.
	
	Updated translation:
	  Indonesian: Andika Triwidada
	
	3.34.3 – January 6, 2020
	
34aba8056fa8324df5995ee12497befa94d6dea8: gnome3.gnome-klotski: 3.34.3 -> 3.34.4
	(https://ftp.gnome.org/pub/GNOME/sources/gnome-klotski/3.34/gnome-klotski-3.34.4.news)
	3.34.4 - February 14, 2020
	===========================
	
	Translation release, with some metadatas fixes.
	
	Translation updated:
	  Malay: Umarzuki Bin Mochlis Moktar
	
	
66472c3c241934b1fabfe468e41ce04e49a40e00: gnome3.four-in-a-row: 3.34.3 -> 3.34.4
	(https://ftp.gnome.org/pub/GNOME/sources/four-in-a-row/3.34/four-in-a-row-3.34.4.news)
	3.34.4 - February 14, 2020
	=============================
	
	Translation release, with some metadatas fixes.
	
	Updated translations:
	  French (help): Charles Monzat
	  Malay: Umarzuki Bin Mochlis Moktar
	
	
dfdfa745c56cd016e7d6c242a4b3bee70d588a27: gnome3.file-roller: 3.32.3 -> 3.32.4
	(https://ftp.gnome.org/pub/GNOME/sources/file-roller/3.32/file-roller-3.32.4.news)
	version 3.32.4
	--------------
	
	 New or updated application translations:
	
	  * Japanese (Ryuta Fujii)
	  * Malay (Umarzuki Bin Mochlis Moktar)
	
	
f330f46c15b3ecf977ecb855fac2e230318ad47b: gnome3.geary: 3.34.1 -> 3.34.2
	(https://ftp.gnome.org/pub/GNOME/sources/geary/3.34/geary-3.34.2.news)
	Version 3.34.2
	~~~~~~~~~~~~~~
	Released: 2019-11-24
	
	Enhancements included in this release:
	
	 * Bug fixes and server compatibility improvements
	 * User interface translation updates
	
	See <https://gitlab.gnome.org/GNOME/geary/-/milestones/14> for full
	details.
	
	Thanks to all who contributed code fixes and enhancements to this
	release:
	
	 * Mario Ravalli <mario@raval.li>
	 * Alex Henrie <alexhenrie24@gmail.com>
	
	Thanks also to all who contributed translations, for the user
	interface:
	
	 * Asier Sarasua Garmendia (eu)
	
	And for the user manual:
	 * Daniel Mustieles (es)
	
	
	
509e1b4763ce62f9b12ab85cebe484fa2cf798f3: gnome3.simple-scan: 3.34.2 -> 3.34.4
	(https://ftp.gnome.org/pub/GNOME/sources/simple-scan/3.34/simple-scan-3.34.4.news)
	Overview of changes in simple-scan 3.34.4
	
	  * Fix page shortcuts no longer working.
	
	
391ab233f9ac7148ce2e740f1f6279b66297b1d0: gnome3.gnome-disk-utility: 3.34.0 -> 3.34.4
	(https://ftp.gnome.org/pub/GNOME/sources/gnome-disk-utility/3.34/gnome-disk-utility-3.34.4.news)
	3.34.4 - February 16, 2020
	==========================
	
	Updated translations:
	 * Ask Hjorth Larsen (da), Danial Behzadi (fa), Fabio Tomat (fur),
	   Nathan Follens (nl), Umarzuki Bin Mochlis Moktar (ms), Yi-Jyun Pan (zh_TW)
	
	
c5590c6efabf085b86f99e82ef318d07c8b6c27a: gnome3.dconf-editor: 3.34.3 -> 3.34.4
	(https://ftp.gnome.org/pub/GNOME/sources/dconf-editor/3.34/dconf-editor-3.34.4.news)
	dconf-editor 3.34.4
	=====================
	
	Just a translations release.
	
	Translations updated:
	  Chinese (Taiwan): Yi-Jyun Pan
	  Malay: Umarzuki Bin Mochlis Moktar
	
	
539493f2cd43a359505502c942043f74384dd34a: gnome3.gnome-music: 3.34.3 -> 3.34.4
	(https://ftp.gnome.org/pub/GNOME/sources/gnome-music/3.34/gnome-music-3.34.4.news)
	Overview of changes in 3.34.4
	=============================
	
	* Various crash and bugfixes
	
	Thanks to our contributors this release:
	 Chinmay Gurjar
	 Jean Felder
	 Marinus Schraal
	
	Translation updated:
	 Italian
	
	
2fd97821a66781edcb5062fe0d7d436e454ad1bb: gnome3.evolution: 3.34.3 -> 3.34.4
	(https://ftp.gnome.org/pub/GNOME/sources/evolution/3.34/evolution-3.34.4.news)
	Evolution 3.34.4 2020-02-14
	---------------------------
	
	Bug Fixes:
		I#740 - 'open-map:' URI passed to browser (Milan Crha)
		I#745 - PST importer: Fix name of MIME multipart/alternative (Ángel)
		I#752 - Incorrect time shown in Reply credits for Australia/Adelaide (Milan Crha)
		I#760 - ECompEditor: Typing end time messes up start time (Milan Crha)
	
	Miscellaneous:
		Emoticon: Replace Unicode variant for face-smile and face-sad with Emoji (Milan Crha)
	
	
9f00427bdd250fe79a685bfef8e7c4ad423321b1: meld: 3.20.1 -> 3.20.2
	(https://ftp.gnome.org/pub/GNOME/sources/meld/3.20/meld-3.20.2.news)
	
	2020-02-16 meld 3.20.2
	======================
	
	  Fixes:
	
	   * Fix crash when launched from external process on Windows (Vasily Galkin)
	   * Fix single-instance behaviour on Windows (Vasily Galkin)
	   * Fix display of large file sizes (Andrey Efremov)
	   * Set file chooser encoding to autodetect by default (Kai Willadsen)
	   * Always use UTF-8 as user's "current" encoding on Windows (Kai Willadsen)
	   * Fix ignoring blank lines on text-filtered files in folder comparison (Kai
	     Willadsen)
	   * Fix expand/collapse actions for missing folders (Kai Willadsen)
	   * Fix some incorrect action sensitivity settings (Kai Willadsen)
	   * Fix height of commit dialog (Kai Willadsen)
	   * Fix install support for Python 3.8 (Kai Willadsen)
	   * Add support for file debug logging on Windows (Kai Willadsen)
	   * Fix icon display on Windows (Kai Willadsen)
	
	   * Issues fixed: 267, 279, 314, 322, 337, 341, 342, 350, 351, 359
	
	
	  Translations:
	
	   * Anders Jonsson (sv)
	   * Andika Triwidada (id)
	   * Asier Sarasua Garmendia (eu)
	   * Balázs Úr (hu)
	   * Daniel Mustieles (es)
	   * Marek Černocký (cs)
	   * Milo Casagrande (it)
	   * Piotr Drąg (pl)
	   * Rafael Fontenelle (pt_BR)
	
	
7f5a2ba1ae5e63c0bcba913a9df3c18aeb91ab5a: gnome3.gnome-photos: 3.34.0 -> 3.34.1
	Probably not a GNOME package
86cd4d110f9f92cc5bc906116e04ef26082aff7e: epiphany: 3.34.3.1 -> 3.34.4
	(https://ftp.gnome.org/pub/GNOME/sources/epiphany/3.34/epiphany-3.34.4.news)
	3.34.4 - February 14, 2020
	==========================
	
	 * Changing web app icon in preferences dialog should copy icon (#810, ignapk)
	 * Fix new tab page with few items in history (#986)
	 * Fix Favorites and Mobile bookmarks not tagged correctly when localized (#1015, Jonathan Kang)
	 * Fix password manager user account selector (#1018)
	 * Hide view source context menu item when on view source page (#1046)
	 * Fix memory corruption in view source mode (#1065)
	 * Fix crash when parsing session state (#1092)
	 * Fix improper warning when closing multiple tabs (#1093)
	 * Fix occasional failure to start up (!537)
	 * Fix memory corruption when loading adblock filters
```

**Comment by jtojnar** [comment]
`gnome3.gnome-photos` is alias so the script did not find it before:

```
(https://ftp.gnome.org/pub/GNOME/sources/gnome-photos/3.34/gnome-photos-3.34.1.news)
Overview of changes in 3.34.1
=============================

* Updated translations:
 Catalan
 English (British)
 French
 Japanese
 Malay
 Persian

```

**Review by jtojnar — APPROVED** [review]
changes look reasonable

**Pull request merged**
