### PR TITLE
Updated apcupsd to version 3.14.13

### PR DESCRIPTION
**Pull request by ikervagyok**

### CODE REVIEW

**Comment by bjornfor** [comment]
Built locally, pushed to master and release-14.12.

**Comment by waltermodbus** [comment]
apcupsd (v3.14.13) does not fully work with modbus and delivers NaN values due to FP error.

**Comment by bjornfor** [comment]
@waltermodbus: Do you know whether that is specific to the apcupsd in nixpkgs (how we build it) or is the apcupsd source itself at fault?

**Comment by waltermodbus** [comment]
I am referring to oleg pkgs.

----- Ursprüngliche Nachricht -----
Von: Bjørn Forsman <notifications@github.com>
Gesendet: Dienstag, 14. Juli 2015 19:35
An: NixOS/nixpkgs <nixpkgs@noreply.github.com>
Cc: waltermodbus <bauer1walter@gmail.com>
Betreff: Re: [nixpkgs] Updated apcupsd to version 3.14.13 (#8215)

@waltermodbus: Do you know whether that is specific to the apcupsd in nixpkgs (how we build it) or is the apcupsd source itself at fault?

**Pull request closed without merging**
