### PR TITLE
[Backport release-23.11]  zfs: 2.2.1 -> 2.2.2, zfs_2_1: 2.1.13 -> 2.1.14

### PR DESCRIPTION
**Pull request by amarshall**
## Description of changes

Manual backport of https://github.com/NixOS/nixpkgs/pull/271328, since that will definitely conflict. Verify that PR is merged before merging this.

Includes fix for long-standing data corruption bugs, especially made more apparent in the 2.2 series.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by adamcstephens — APPROVED** [review]
Result of `nixpkgs-review pr 271366` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.linux_6_6.zfs_2_1</li>
    <li>linuxKernel.packages.linux_latest_libre.zfs_2_1</li>
    <li>linuxKernel.packages.linux_zen.zfs_2_1</li>
  </ul>
</details>
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>diffoscope</li>
    <li>diffoscope.dist</li>
    <li>diffoscope.man</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.zfs (linuxKernel.packages.linux_testing_bcachefs.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.zfs_2_1</li>
  </ul>
</details>
<details>
  <summary>105 packages built:</summary>
  <ul>
    <li>appvm</li>
    <li>booster</li>
    <li>ceph</li>
    <li>ceph-client</li>
    <li>ceph-csi</li>
    <li>ceph.dev</li>
    <li>ceph.doc</li>
    <li>libceph (ceph.lib ,libceph.dev ,libceph.doc ,libceph.lib ,libceph.man)</li>
    <li>ceph.man</li>
    <li>check_zfs</li>
    <li>collectd</li>
    <li>docker-machine-kvm</li>
    <li>docker-machine-kvm2</li>
    <li>easysnap</li>
    <li>gnome.gnome-boxes</li>
    <li>guestfs-tools</li>
    <li>libguestfs</li>
    <li>libguestfs-with-appliance</li>
    <li>librenms</li>
    <li>libvirt</li>
    <li>libvirt-glib</li>
    <li>libvirt-glib.dev</li>
    <li>libvirt-glib.devdoc</li>
    <li>linuxKernel.packages.linux_4_19.zfs (linuxKernel.packages.linux_4_19.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_4_19.zfs_2_1</li>
    <li>linuxKernel.packages.linux_4_19_hardened.zfs (linuxKernel.packages.linux_4_19_hardened.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_4_19_hardened.zfs_2_1</li>
    <li>linuxKernel.packages.linux_5_10.zfs (linuxKernel.packages.linux_5_10.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_5_10.zfs_2_1</li>
    <li>linuxKernel.packages.linux_5_10_hardened.zfs (linuxKernel.packages.linux_5_10_hardened.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_5_10_hardened.zfs_2_1</li>
    <li>linuxKernel.packages.linux_5_15.zfs (linuxKernel.packages.linux_5_15.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_5_15.zfs_2_1</li>
    <li>linuxKernel.packages.linux_5_15_hardened.zfs (linuxKernel.packages.linux_5_15_hardened.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_5_15_hardened.zfs_2_1</li>
    <li>linuxKernel.packages.linux_5_4.zfs (linuxKernel.packages.linux_5_4.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_5_4.zfs_2_1</li>
    <li>linuxKernel.packages.linux_5_4_hardened.zfs (linuxKernel.packages.linux_5_4_hardened.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_5_4_hardened.zfs_2_1</li>
    <li>linuxKernel.packages.linux_6_1.zfs (linuxKernel.packages.linux_6_1.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_6_1.zfs_2_1</li>
    <li>linuxKernel.packages.linux_hardened.zfs (linuxKernel.packages.linux_6_1_hardened.zfs ,linuxKernel.packages.linux_hardened.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_hardened.zfs_2_1 (linuxKernel.packages.linux_6_1_hardened.zfs_2_1)</li>
    <li>linuxKernel.packages.linux_6_5.zfs (linuxKernel.packages.linux_6_5.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_6_5.zfs_2_1</li>
    <li>linuxKernel.packages.linux_6_5_hardened.zfs (linuxKernel.packages.linux_6_5_hardened.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_6_5_hardened.zfs_2_1</li>
    <li>linuxKernel.packages.linux_6_6.zfs (linuxKernel.packages.linux_6_6.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_latest_libre.zfs (linuxKernel.packages.linux_latest_libre.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_libre.zfs (linuxKernel.packages.linux_libre.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_libre.zfs_2_1</li>
    <li>linuxKernel.packages.linux_lqx.zfs (linuxKernel.packages.linux_lqx.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_lqx.zfs_2_1</li>
    <li>linuxKernel.packages.linux_xanmod.zfs (linuxKernel.packages.linux_xanmod.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_xanmod.zfs_2_1</li>
    <li>linuxKernel.packages.linux_xanmod_latest.zfs (linuxKernel.packages.linux_xanmod_latest.zfsUnstable ,linuxKernel.packages.linux_xanmod_stable.zfs ,linuxKernel.packages.linux_xanmod_stable.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.zfs_2_1 (linuxKernel.packages.linux_xanmod_stable.zfs_2_1)</li>
    <li>linuxKernel.packages.linux_zen.zfs (linuxKernel.packages.linux_zen.zfsUnstable)</li>
    <li>mgmt</li>
    <li>minikube</li>
    <li>minishift</li>
    <li>multipass</li>
    <li>nixops_unstable</li>
    <li>nixops_unstable.dist</li>
    <li>ocamlPackages.ocaml_libvirt</li>
    <li>partition-manager</li>
    <li>perl536Packages.SysVirt</li>
    <li>perl536Packages.SysVirt.devdoc</li>
    <li>perl538Packages.SysVirt</li>
    <li>perl538Packages.SysVirt.devdoc</li>
    <li>python310Packages.guestfs</li>
    <li>python310Packages.guestfs.dist</li>
    <li>python310Packages.libvirt</li>
    <li>python310Packages.libvirt.dist</li>
    <li>python310Packages.py-libzfs</li>
    <li>python310Packages.py-libzfs.dist</li>
    <li>python311Packages.guestfs</li>
    <li>python311Packages.guestfs.dist</li>
    <li>python311Packages.libvirt</li>
    <li>python311Packages.libvirt.dist</li>
    <li>python311Packages.py-libzfs</li>
    <li>python311Packages.py-libzfs.dist</li>
    <li>qemu_full</li>
    <li>qemu_full.debug</li>
    <li>qemu_full.ga</li>
    <li>rubyPackages.ruby-libvirt</li>
    <li>rubyPackages_3_2.ruby-libvirt</li>
    <li>rubyPackages_3_3.ruby-libvirt</li>
    <li>samba4Full</li>
    <li>samba4Full.dev</li>
    <li>samba4Full.man</li>
    <li>sanoid</li>
    <li>vagrant</li>
    <li>virt-manager</li>
    <li>virt-manager-qt</li>
    <li>virt-manager.dist</li>
    <li>virt-top</li>
    <li>virt-viewer</li>
    <li>zfs (zfsUnstable)</li>
    <li>zfs.dev (zfsUnstable.dev)</li>
    <li>zfs_2_1</li>
    <li>zfs_2_1.dev</li>
    <li>zfstools</li>
    <li>zpool-auto-expand-partitions</li>
    <li>zxfer</li>
  </ul>
</details>

---

Result of `nixpkgs-review pr 271366` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>30 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.linux_6_5.zfs</li>
    <li>linuxKernel.packages.linux_6_5.zfsUnstable</li>
    <li>linuxKernel.packages.linux_6_5.zfs_2_1</li>
    <li>linuxKernel.packages.linux_6_5_hardened.zfs</li>
    <li>linuxKernel.packages.linux_6_5_hardened.zfsUnstable</li>
    <li>linuxKernel.packages.linux_6_5_hardened.zfs_2_1</li>
    <li>linuxKernel.packages.linux_6_6.zfs</li>
    <li>linuxKernel.packages.linux_6_6.zfsUnstable</li>
    <li>linuxKernel.packages.linux_6_6.zfs_2_1</li>
    <li>linuxKernel.packages.linux_latest_libre.zfs</li>
    <li>linuxKernel.packages.linux_latest_libre.zfsUnstable</li>
    <li>linuxKernel.packages.linux_latest_libre.zfs_2_1</li>
    <li>linuxKernel.packages.linux_lqx.zfs</li>
    <li>linuxKernel.packages.linux_lqx.zfsUnstable</li>
    <li>linuxKernel.packages.linux_lqx.zfs_2_1</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.zfs</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.zfsUnstable</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.zfs_2_1</li>
    <li>linuxKernel.packages.linux_xanmod.zfs</li>
    <li>linuxKernel.packages.linux_xanmod.zfsUnstable</li>
    <li>linuxKernel.packages.linux_xanmod.zfs_2_1</li>
    <li>linuxKernel.packages.linux_xanmod_latest.zfs</li>
    <li>linuxKernel.packages.linux_xanmod_latest.zfsUnstable</li>
    <li>linuxKernel.packages.linux_xanmod_latest.zfs_2_1</li>
    <li>linuxKernel.packages.linux_xanmod_stable.zfs</li>
    <li>linuxKernel.packages.linux_xanmod_stable.zfsUnstable</li>
    <li>linuxKernel.packages.linux_xanmod_stable.zfs_2_1</li>
    <li>linuxKernel.packages.linux_zen.zfs</li>
    <li>linuxKernel.packages.linux_zen.zfsUnstable</li>
    <li>linuxKernel.packages.linux_zen.zfs_2_1</li>
  </ul>
</details>
<details>
  <summary>88 packages built:</summary>
  <ul>
    <li>appvm</li>
    <li>booster</li>
    <li>ceph</li>
    <li>ceph-client</li>
    <li>ceph-csi</li>
    <li>ceph.dev</li>
    <li>ceph.doc</li>
    <li>libceph (ceph.lib ,libceph.dev ,libceph.doc ,libceph.lib ,libceph.man)</li>
    <li>ceph.man</li>
    <li>check_zfs</li>
    <li>collectd</li>
    <li>diffoscope</li>
    <li>diffoscope.dist</li>
    <li>diffoscope.man</li>
    <li>docker-machine-kvm</li>
    <li>docker-machine-kvm2</li>
    <li>easysnap</li>
    <li>gnome.gnome-boxes</li>
    <li>libguestfs</li>
    <li>librenms</li>
    <li>libvirt</li>
    <li>libvirt-glib</li>
    <li>libvirt-glib.dev</li>
    <li>libvirt-glib.devdoc</li>
    <li>linuxKernel.packages.linux_4_19.zfs (linuxKernel.packages.linux_4_19.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_4_19.zfs_2_1</li>
    <li>linuxKernel.packages.linux_4_19_hardened.zfs (linuxKernel.packages.linux_4_19_hardened.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_4_19_hardened.zfs_2_1</li>
    <li>linuxKernel.packages.linux_5_10.zfs (linuxKernel.packages.linux_5_10.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_5_10.zfs_2_1</li>
    <li>linuxKernel.packages.linux_5_10_hardened.zfs (linuxKernel.packages.linux_5_10_hardened.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_5_10_hardened.zfs_2_1</li>
    <li>linuxKernel.packages.linux_5_15.zfs (linuxKernel.packages.linux_5_15.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_5_15.zfs_2_1</li>
    <li>linuxKernel.packages.linux_5_15_hardened.zfs (linuxKernel.packages.linux_5_15_hardened.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_5_15_hardened.zfs_2_1</li>
    <li>linuxKernel.packages.linux_5_4.zfs (linuxKernel.packages.linux_5_4.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_5_4.zfs_2_1</li>
    <li>linuxKernel.packages.linux_5_4_hardened.zfs (linuxKernel.packages.linux_5_4_hardened.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_5_4_hardened.zfs_2_1</li>
    <li>linuxKernel.packages.linux_6_1.zfs (linuxKernel.packages.linux_6_1.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_6_1.zfs_2_1</li>
    <li>linuxKernel.packages.linux_hardened.zfs (linuxKernel.packages.linux_6_1_hardened.zfs ,linuxKernel.packages.linux_hardened.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_hardened.zfs_2_1 (linuxKernel.packages.linux_6_1_hardened.zfs_2_1)</li>
    <li>linuxKernel.packages.linux_libre.zfs (linuxKernel.packages.linux_libre.zfsUnstable)</li>
    <li>linuxKernel.packages.linux_libre.zfs_2_1</li>
    <li>mgmt</li>
    <li>minikube</li>
    <li>minishift</li>
    <li>nixops_unstable</li>
    <li>nixops_unstable.dist</li>
    <li>ocamlPackages.ocaml_libvirt</li>
    <li>partition-manager</li>
    <li>perl536Packages.SysVirt</li>
    <li>perl536Packages.SysVirt.devdoc</li>
    <li>perl538Packages.SysVirt</li>
    <li>perl538Packages.SysVirt.devdoc</li>
    <li>python310Packages.guestfs</li>
    <li>python310Packages.guestfs.dist</li>
    <li>python310Packages.libvirt</li>
    <li>python310Packages.libvirt.dist</li>
    <li>python310Packages.py-libzfs</li>
    <li>python310Packages.py-libzfs.dist</li>
    <li>python311Packages.guestfs</li>
    <li>python311Packages.guestfs.dist</li>
    <li>python311Packages.libvirt</li>
    <li>python311Packages.libvirt.dist</li>
    <li>python311Packages.py-libzfs</li>
    <li>python311Packages.py-libzfs.dist</li>
    <li>qemu_full</li>
    <li>qemu_full.ga</li>
    <li>rubyPackages.ruby-libvirt</li>
    <li>rubyPackages_3_2.ruby-libvirt</li>
    <li>rubyPackages_3_3.ruby-libvirt</li>
    <li>sanoid</li>
    <li>vagrant</li>
    <li>virt-manager</li>
    <li>virt-manager-qt</li>
    <li>virt-manager.dist</li>
    <li>virt-top</li>
    <li>virt-viewer</li>
    <li>zfs (zfsUnstable)</li>
    <li>zfs.dev (zfsUnstable.dev)</li>
    <li>zfs_2_1</li>
    <li>zfs_2_1.dev</li>
    <li>zfstools</li>
    <li>zpool-auto-expand-partitions</li>
    <li>zxfer</li>
  </ul>
</details>

**Review by newAM — APPROVED** [review]
`zfs_2_1` builds and runs.

**Review by ius — APPROVED** [review]
This should be merged, given that https://github.com/NixOS/nixpkgs/pull/271328 is too..

_zfs_ (i.e. v2.2.2) works on my machine (fwiw, I did not upgrade my pool)..

**Comment by adamcstephens** [comment]
@RaitoBezarius did you want to wait on this still, or should we proceed with the backport?

**Comment by RaitoBezarius** [comment]
Please proceed, I already reviewed the stuff

**Pull request merged**
