### PR TITLE
nixd: 2.1.2 -> 2.2.0; {nixf,nixt}: init

### PR DESCRIPTION
**Pull request by Aleksanaa**
## Description of changes

Separated `nixf` and `nixt` into different packages, requested by @inclyc. They can be consumed by other nix tools.

Packaging structure suggested in https://github.com/NixOS/nixpkgs/tree/master/pkgs/by-name#further-possible-refactorings, opinions welcomed.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Aleksanaa** [comment]
@ofborg build nixf.passthru.tests nixt.passthru.tests

**Comment by Aleksanaa** [comment]
Forgot to make it overridable

**Comment by Aleksanaa** [comment]
Actually enabled tests now.

**Comment by Aleksanaa** [comment]
I disabled the tests for now

**Comment by inclyc** [comment]
> I disabled the tests for now (https://github.com/nix-community/nixd/issues/519)

This LGTM because regression tests are intended to be executed at CI, in development, and previously we almost always have some trouble with it in Nix sandbox, because actually some features are relied with nix itself. Some tests never pass after macOS updates, some tests only work with a `NIX_PATH`.

**Review by inclyc — APPROVED** [review]

**Review by drupol — CHANGES_REQUESTED** [review]
Nice stuff, I've learned quite a bunch of stuff by reading this PR.

I might not be the right person to tell if using this is the best pattern to abstract the common attributes, but it looks pretty cool.

I also notice that `nix-update-script` is gone, would it be a good idea to restore it?

**Comment by Aleksanaa** [comment]
> I also notice that `nix-update-script` is gone, would it be a good idea to restore it?

Ah, I'm not familiar with update scripts, but I'll give it a try to see if it works.

**Comment by drupol** [comment]
Just for my own information, what are the differences (pros/cons) in using `lib.recursiveUpdate` and the override mechanism implemented in this [file](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/php/builders/v1/build-composer-project.nix)?

**Comment by Aleksanaa** [comment]
> Just for my own information, what are the differences (pros/cons) in using `lib.recursiveUpdate` and the override mechanism implemented in this [file](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/php/builders/v1/build-composer-project.nix)?

Just because it's handy? If there are more packages then we should definitely make a builder

**Comment by Aleksanaa** [comment]
However, I am indeed more interested in the problem of the lack of a unified structure for several derivations that share the same attribute. The solution in this PR is just a temporary one that I came up with. Maybe we will eventually use a predefined by-name entrance (such as packages.nix, builder.nix, or some other structure?) to achieve this.

**Comment by Aleksanaa** [comment]
`lib.recursiveUpdate` looks very useful in this case, but it breaks `builtins.unsafeGetAttrPos` as the latter cannot understand what happens. This further breaks `meta.position` and nix-update (https://github.com/Mic92/nix-update/blob/c8ba353d2222993423b6f69d08c02370cc599522/nix_update/eval.py#L154-L161).

So another day another lesson 😵‍💫

**Review by inclyc — APPROVED** [review]

**Review by drupol — APPROVED** [review]

**Pull request merged**
