### PR TITLE
sbcl: 1.4.0 -> 1.4.1

### PR DESCRIPTION
**Pull request by mimame**
###### Motivation for this change

Update sbcl to the last version

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg maxima

**Comment by 7c6f434c** [comment]
(if I don't have permissions, at least I will know how the failure looks like)

**Comment by NeQuissimus** [comment]
My nox reports build failures: (no idea if this is new)

```
; compiling (DECLAIM (INLINE MAKE-STATIC-VECTOR))
; compiling (DEFUN MAKE-STATIC-VECTOR ...)
; compiling (DEFINE-COMPILER-MACRO MAKE-STATIC-VECTOR ...)builder for ‘/nix/store/q42750p8qdb3mcrik8yxwm8dw8jvlxaf-lisp-iolib-v0.8.3.drv’ failed with exit code 1
error: build of ‘/nix/store/q42750p8qdb3mcrik8yxwm8dw8jvlxaf-lisp-iolib-v0.8.3.drv’ failed
```

**Comment by 7c6f434c** [comment]
`iolib` in some versions of `lispPackages` (there are options for different ASDF) could fail, that's true.

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg maxima

**Comment by 7c6f434c** [comment]
I bumped SBCL to an unstable revision after looking the upstream bug tracker… The `iolib` failure was fixed by the upstream fixes.

**Pull request merged**
