### PR TITLE
glm: 0.9.9.8 -> 1.0.1, opensplat: 1.1.2 -> 1.1.3, fix frogatto's engine's build

### PR DESCRIPTION
**Pull request by jcaesar**
## Description of changes

This PR is a re-open of #308253 on staging, as per maintainer request. Description of the original PR:

---

* glm
  * changelog: [1.0.0](https://github.com/g-truc/glm/releases/tag/1.0.0) [1.0.1](https://github.com/g-truc/glm/releases/tag/1.0.1)
   * The 1.0 "release" seems to have put some features behind "experimental" [gates](https://github.com/g-truc/glm/blob/45008b225e28eb700fa0f7d3ff69b7c1db94fadf/glm/gtx/matrix_decompose.hpp#L24), so a define is necessary to avoid build failures on some dependent packages
    
 * opensplat
   * changelog: [1.1.3](https://github.com/pierotofy/OpenSplat/releases/tag/v1.1.3)
   * The license change corrects an error on my part in the init pr
 * frogatto / anura-engine:
   * The glm update broke its build, but it also already contained an unrelated `-Werror` build failure . Cleanup en passant.
   * I don't plan on testing whether this actually runs
   
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by jcaesar** [comment]
@Scrumplex Since it seems like no divine input is coming to [this pr](https://github.com/NixOS/nixpkgs/pull/308253#issuecomment-2135266950), I moved it to staging as requested. (I can't set the old PR to draft status again, so I think changing branches there would be a bad idea.)

Is this as you intended? It seems somewhat counterproductive. I can't test anything here because even building opensplat without cuda takes >1000 builds, and ofborg fails with something seemingly unrelated. The previous PR I could at least build, even on my notebook, with `nixpkgs-review pr 308253 `--build-args=--max-jobs 1 --cores 3 -vL`.

**Comment by smancill** [comment]
I think we can merge this.

**Review by smancill — APPROVED** [review]

**Comment by smancill** [comment]
@jcaesar could you rebase again, please, so I can merge this. There is a conflict.

**Comment by jcaesar** [comment]
Conflict resolved. Thanks in advance.

**Review by smancill — APPROVED** [review]

**Comment by smancill** [comment]
Thanks for all your work. Sorry for not merging sooner.

**Pull request merged**
