### PR TITLE
vimPlugins: add vim-dirtytalk (wordlist)

### PR DESCRIPTION
**Pull request by yavko**
###### Description of changes
Adds the vim-dirty talk plugin which adds a wordlist of words programmers frequently use, but aren't in the main wordlists

###### Things done

- Built on platform(s) **Not applicable**
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html)) **Not applicable**
- [ ] Tested, as applicable: **Not applicable**
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage) **Not applicable**
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`) **Not applicable**
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking **Not applicable**
  - [ ] (Module updates) Added a release notes entry if the change is significant **Not applicable**
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module **Not applicable**
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes **Not applicable**
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
You must run the update.py script in the same directory.

**Comment by yavko** [comment]
> You must run the update.py script in the same directory.

done

**Comment by figsoda** [comment]
please rebase on master instead of merging, and your commit message should be `vimPlugins.vim-dirtytalk: init at 2022-10-31`, which the update script should automatically do

**Comment by PerchunPak** [comment]
Hi @yavko,

Would you mind rebasing (or more accurately recreating) this PR when you have a moment? It should ideally look like this:

```bash
git clone https://github.com/yavko/nixpkgs && cd nixpkgs
git remote add upstream https://github.com/NixOS/nixpkgs
git fetch upstream
git checkout upstream/master
git branch -d patch-1
git switch -c patch-1 upstream/master
nix-shell -p vimPluginsUpdater --run 'vim-plugins-updater add "psliwka/vim-dirtytalk"'
nix-shell -p vimPluginsUpdater --run 'vim-plugins-updater -n'
# then go to `pkgs/applications/editors/vim/plugins/generated.nix`
# and only include changes for this plugin
git commit --amend --no-edit
git push -f origin
```

If it's not something you're concerned about anymore, feel free to close the PR—no worries at all. I totally understand if too much time has passed.

---

Also, `:DirtytalkUpdate` won't work on Nix. Is it possible to call it during the build of the plugin?

**Comment by SuperSandro2000** [comment]
> If it's not something you're concerned about anymore, feel free to close the PR—no worries at all. I totally understand if too much time has passed.

You can always create a PR yourself.

> Also, :DirtytalkUpdate won't work on Nix. Is it possible to call it during the build of the plugin?

If it downloads data we need to prefetch that.

---

Closing because of age of the PR and it is kinda stale.

**Comment by PerchunPak** [comment]
> You can always create a PR yourself.

I reviewed dozens of such stale PRs just to revive some of them (and also no one reviews vimplugins PRs atm, so...)

**Pull request closed without merging**
