### PR TITLE
chromium-codecs-ffmpeg-extra 111306 -> 114023

### PR DESCRIPTION
**Pull request by numkem**
## Description of changes

Updated chromium-codecs-ffmpeg-extra to fix tab crashing with Vivaldi 6.6 when there is a video present in the page.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by FPtje — APPROVED** [review]
Thanks for the update! I hadn't noticed things were broken myself.

Review: 

- [x] package name fits guidelines
  - Unchanged 
- [x] package version fits guidelines
- [x] package builds on x86-64-linux
- [x] executables tested on ARCHITECTURE
  - No executables, just one `.so` file. Verified that this looks normal with `file` and `ldd`
- [x] all depending packages build
  - Running `nixpkgs-review` states that the yandex browser cannot be built, but the error is that the `.deb` cannot be found. Definitely unrelated to this PR :+1: 
- [x] patches have a comment describing either the upstream URL or a reason why the patch wasn't upstreamed
  - No patches are present
- [x] patches that are remotely available are fetched rather than vendored

**Comment by numkem** [comment]
Can this be merged? I would be beneficial for everyone using Vivaldi.

**Comment by yayayayaka** [comment]
Result of `nixpkgs-review pr 295003` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>yandex-browser-corporate</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>exodus</li>
    <li>vivaldi-ffmpeg-codecs</li>
    <li>yandex-browser</li>
    <li>yandex-browser-beta</li>
  </ul>
</details>

**Review by yayayayaka — APPROVED** [review]
The `yandex-browser-corporate` build failure is unrelated. Diff looking good to me.

**Pull request merged**
