### PR TITLE
fwupd: 1.9.25 -> 2.0.1

### PR DESCRIPTION
**Pull request by r-vdp**
- **fwupd: format**
- **fwupd: 1.9.25 -> 2.0.1**

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 351772`

---
### `x86_64-linux`
<details>
  <summary>:x: 19 packages failed to build:</summary>
  <ul>
    <li>gnome-firmware</li>
    <li>gnome-software</li>
    <li>kdePackages.discover</li>
    <li>kdePackages.discover.debug</li>
    <li>kdePackages.discover.dev</li>
    <li>kdePackages.discover.devtools</li>
    <li>libsForQt5.discover</li>
    <li>pantheon.elementary-greeter</li>
    <li>pantheon.elementary-onboarding</li>
    <li>pantheon.elementary-settings-daemon</li>
    <li>pantheon.switchboard-plug-about</li>
    <li>pantheon.switchboard-plug-pantheon-shell</li>
    <li>pantheon.switchboard-plug-power</li>
    <li>pantheon.switchboard-plug-security-privacy</li>
    <li>pantheon.switchboard-with-plugs</li>
    <li>pantheon.wingpanel-applications-menu</li>
    <li>pantheon.wingpanel-indicator-power</li>
    <li>pantheon.wingpanel-quick-settings</li>
    <li>pantheon.wingpanel-with-indicators</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 8 packages built:</summary>
  <ul>
    <li>fwupd</li>
    <li>fwupd.debug</li>
    <li>fwupd.dev</li>
    <li>fwupd.devdoc</li>
    <li>fwupd.installedTests</li>
    <li>fwupd.lib</li>
    <li>fwupd.man</li>
    <li>libsForQt5.kinfocenter</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:x: 18 packages failed to build:</summary>
  <ul>
    <li>gnome-firmware</li>
    <li>kdePackages.discover</li>
    <li>kdePackages.discover.debug</li>
    <li>kdePackages.discover.dev</li>
    <li>kdePackages.discover.devtools</li>
    <li>libsForQt5.discover</li>
    <li>pantheon.elementary-greeter</li>
    <li>pantheon.elementary-onboarding</li>
    <li>pantheon.elementary-settings-daemon</li>
    <li>pantheon.switchboard-plug-about</li>
    <li>pantheon.switchboard-plug-pantheon-shell</li>
    <li>pantheon.switchboard-plug-power</li>
    <li>pantheon.switchboard-plug-security-privacy</li>
    <li>pantheon.switchboard-with-plugs</li>
    <li>pantheon.wingpanel-applications-menu</li>
    <li>pantheon.wingpanel-indicator-power</li>
    <li>pantheon.wingpanel-quick-settings</li>
    <li>pantheon.wingpanel-with-indicators</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 8 packages built:</summary>
  <ul>
    <li>fwupd</li>
    <li>fwupd.debug</li>
    <li>fwupd.dev</li>
    <li>fwupd.devdoc</li>
    <li>fwupd.installedTests</li>
    <li>fwupd.lib</li>
    <li>fwupd.man</li>
    <li>libsForQt5.kinfocenter</li>
  </ul>
</details>

---
### `x86_64-darwin`

---
### `aarch64-darwin`

**Comment by r-vdp** [comment]
Yeah, it's definitely still work in progress... 

I'll try to check out those build failures tomorrow.

**Comment by GaetanLepage** [comment]
> Yeah, it's definitely still work in progress...
> 
> I'll try to check out those build failures tomorrow.

Sure, don't hesitate to ask me for the logs.

**Comment by GaetanLepage** [comment]
> We could patch in the fix, but I don't think that that's the right thing to do here.
> We can find the bug trackers for the different projects and file bugs.

I agree, let's share this information upstream. Feel free to ping me there too.
Thanks for your investigation.

**Comment by r-vdp** [comment]
Ok, https://github.com/fwupd/fwupd/pull/7994 should fix the issue with applications building against libfwupd and not finding .

There are still several failures due to changes in fwupd. I think the gnome failures are fixed on staging-next, I'm not sure about the kde and pantheon ones.

**Comment by GaetanLepage** [comment]
> There are still several failures due to changes in fwupd. I think the gnome failures are fixed on staging-next, I'm not sure about the kde and pantheon ones.

Ok let's wait for it to land on `master` than. I heard that this could be happening later today.

**Comment by GaetanLepage** [comment]
> There are still several failures due to changes in fwupd. I think the gnome failures are fixed on staging-next, I'm not sure about the kde and pantheon ones.

`staging-next` has landed in `master` a few days ago. Can you try again ?

**Comment by r-vdp** [comment]
@NixOS/pantheon this breaks the build of `pantheon.elementary-settings-daemon`. What's the upstream situation for that package? How would you suggest we proceed here?

**Comment by r-vdp** [comment]
I checked with @K900 on matrix, they are ok with us breaking the plasma 5 discover package with this PR.

gnome-software was fixed with the staging merge, gnome-firmware needs a version bump, see linked PR above.

I have no idea about pantheon, let's give them some time to react.

**Comment by GaetanLepage** [comment]
> I checked with @K900 on matrix, they are ok with us breaking the plasma 5 discover package with this PR.
> 
> gnome-software was fixed with the staging merge, gnome-firmware needs a version bump, see linked PR above.
> 
> I have no idea about pantheon, let's give them some time to react.

Ok, thank you for the update.

**Comment by bobby285271** [comment]
> pantheon.elementary-settings-daemon

Thanks for the ping, there is https://gitlab.archlinux.org/archlinux/packaging/packages/pantheon-settings-daemon/-/blob/main/fwupd-2.0-compat.patch you can fetchpatch, I will try to upstream it.

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 351772`

---
### `x86_64-linux`
<details>
  <summary>:x: 13 packages failed to build:</summary>
  <ul>
    <li>libsForQt5.discover (plasma5Packages.discover)</li>
    <li>pantheon.elementary-greeter</li>
    <li>pantheon.elementary-onboarding</li>
    <li>pantheon.elementary-settings-daemon</li>
    <li>pantheon.switchboard-plug-about</li>
    <li>pantheon.switchboard-plug-pantheon-shell</li>
    <li>pantheon.switchboard-plug-power</li>
    <li>pantheon.switchboard-plug-security-privacy</li>
    <li>pantheon.switchboard-with-plugs</li>
    <li>pantheon.wingpanel-applications-menu</li>
    <li>pantheon.wingpanel-indicator-power</li>
    <li>pantheon.wingpanel-quick-settings</li>
    <li>pantheon.wingpanel-with-indicators</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 14 packages built:</summary>
  <ul>
    <li>fwupd</li>
    <li>fwupd.debug</li>
    <li>fwupd.dev</li>
    <li>fwupd.devdoc</li>
    <li>fwupd.installedTests</li>
    <li>fwupd.lib</li>
    <li>fwupd.man</li>
    <li>gnome-firmware</li>
    <li>gnome-software</li>
    <li>kdePackages.discover</li>
    <li>kdePackages.discover.debug</li>
    <li>kdePackages.discover.dev</li>
    <li>kdePackages.discover.devtools</li>
    <li>libsForQt5.kinfocenter (plasma5Packages.kinfocenter)</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:x: 13 packages failed to build:</summary>
  <ul>
    <li>libsForQt5.discover (plasma5Packages.discover)</li>
    <li>pantheon.elementary-greeter</li>
    <li>pantheon.elementary-onboarding</li>
    <li>pantheon.elementary-settings-daemon</li>
    <li>pantheon.switchboard-plug-about</li>
    <li>pantheon.switchboard-plug-pantheon-shell</li>
    <li>pantheon.switchboard-plug-power</li>
    <li>pantheon.switchboard-plug-security-privacy</li>
    <li>pantheon.switchboard-with-plugs</li>
    <li>pantheon.wingpanel-applications-menu</li>
    <li>pantheon.wingpanel-indicator-power</li>
    <li>pantheon.wingpanel-quick-settings</li>
    <li>pantheon.wingpanel-with-indicators</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 13 packages built:</summary>
  <ul>
    <li>fwupd</li>
    <li>fwupd.debug</li>
    <li>fwupd.dev</li>
    <li>fwupd.devdoc</li>
    <li>fwupd.installedTests</li>
    <li>fwupd.lib</li>
    <li>fwupd.man</li>
    <li>gnome-firmware</li>
    <li>kdePackages.discover</li>
    <li>kdePackages.discover.debug</li>
    <li>kdePackages.discover.dev</li>
    <li>kdePackages.discover.devtools</li>
    <li>libsForQt5.kinfocenter (plasma5Packages.kinfocenter)</li>
  </ul>
</details>

**Comment by r-vdp** [comment]
Yeah, so we just need the pantheon fixes in, and then we should be able to merge this.

**Comment by bobby285271** [comment]
35d963f9c5c769a63510072cbeff6725925410e7 d8e545500a7adbf0a4c010dee1c055f33248c232 is now in master.

**Comment by r-vdp** [comment]
@GaetanLepage I rebased on top of master for the pantheon fixes, but I'm in between airplanes. If you could run another nixpkgs-review, then we can probably get this merged soon now.

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 351772`

---
### `x86_64-linux`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>libsForQt5.discover</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 26 packages built:</summary>
  <ul>
    <li>fwupd</li>
    <li>fwupd.debug</li>
    <li>fwupd.dev</li>
    <li>fwupd.devdoc</li>
    <li>fwupd.installedTests</li>
    <li>fwupd.lib</li>
    <li>fwupd.man</li>
    <li>gnome-firmware</li>
    <li>gnome-software</li>
    <li>kdePackages.discover</li>
    <li>kdePackages.discover.debug</li>
    <li>kdePackages.discover.dev</li>
    <li>kdePackages.discover.devtools</li>
    <li>libsForQt5.kinfocenter</li>
    <li>pantheon.elementary-greeter</li>
    <li>pantheon.elementary-onboarding</li>
    <li>pantheon.elementary-settings-daemon</li>
    <li>pantheon.switchboard-plug-about</li>
    <li>pantheon.switchboard-plug-pantheon-shell</li>
    <li>pantheon.switchboard-plug-power</li>
    <li>pantheon.switchboard-plug-security-privacy</li>
    <li>pantheon.switchboard-with-plugs</li>
    <li>pantheon.wingpanel-applications-menu</li>
    <li>pantheon.wingpanel-indicator-power</li>
    <li>pantheon.wingpanel-quick-settings</li>
    <li>pantheon.wingpanel-with-indicators</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>libsForQt5.discover</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 25 packages built:</summary>
  <ul>
    <li>fwupd</li>
    <li>fwupd.debug</li>
    <li>fwupd.dev</li>
    <li>fwupd.devdoc</li>
    <li>fwupd.installedTests</li>
    <li>fwupd.lib</li>
    <li>fwupd.man</li>
    <li>gnome-firmware</li>
    <li>kdePackages.discover</li>
    <li>kdePackages.discover.debug</li>
    <li>kdePackages.discover.dev</li>
    <li>kdePackages.discover.devtools</li>
    <li>libsForQt5.kinfocenter</li>
    <li>pantheon.elementary-greeter</li>
    <li>pantheon.elementary-onboarding</li>
    <li>pantheon.elementary-settings-daemon</li>
    <li>pantheon.switchboard-plug-about</li>
    <li>pantheon.switchboard-plug-pantheon-shell</li>
    <li>pantheon.switchboard-plug-power</li>
    <li>pantheon.switchboard-plug-security-privacy</li>
    <li>pantheon.switchboard-with-plugs</li>
    <li>pantheon.wingpanel-applications-menu</li>
    <li>pantheon.wingpanel-indicator-power</li>
    <li>pantheon.wingpanel-quick-settings</li>
    <li>pantheon.wingpanel-with-indicators</li>
  </ul>
</details>

---
### `x86_64-darwin`

---
### `aarch64-darwin`

**Comment by GaetanLepage** [comment]
> @GaetanLepage I rebased on top of master for the pantheon fixes, but I'm in between airplanes. If you could run another nixpkgs-review, then we can probably get this merged soon now.

Yes it looks good ! Only `discovery` is failing.

**Comment by GaetanLepage** [comment]
I'll wait for your approval and merge then :)

**Comment by r-vdp** [comment]
I am just waiting for ofborg to finish. But I'm on holidays and I'll be out most of the day, so feel free to merge once ofborg is done!

**Comment by r-vdp** [comment]
(I can't formally approve since I'm the PR author)

**Pull request merged**
