### PR TITLE
Adding Danish dictionary to Aspell

### PR DESCRIPTION
**Pull request by Lindstroem**
I have added the Danish dictionary to Aspell. It is my first pull request for NixOS and GitHub, and hope I am doing everything by the book. Please correct me, if I am not doing things by the book.

I have tested the Danish dictionary using Aspell command line tool and Emacs.

### CODE REVIEW

**Comment by pSub** [comment]
Builds fine locally. Thanks!

**Comment by pSub** [comment]
Ah, could you rebase your changes against master instead of merging?

**Comment by pSub** [comment]
I've cherry picked your commit as 012bb48a186476a3381e04898a2557e31e6d3d1d.

**Comment by Lindstroem** [comment]
Dear Mr. Wittmann,

OK. I tried to rebase instead of merging. I am new to both NixOS and Git,
so it took some time to get it right - If I have gotten it right.

But if you cherry picked the change, it do not matter.


Thanks,

Mads Lindstrøm

2015-04-16 19:38 GMT+02:00 Pascal Wittmann <notifications@github.com>:

**Comment by pSub** [comment]
You've got it right. Thanks again for your contribution!

**Pull request closed without merging**
