### PR TITLE
linux_zen: 5.9.14 -> 5.10.1

### PR DESCRIPTION
**Pull request by Atemu**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

/marvin opt-in
/status needs_reviewer

cc @andresilva

### CODE REVIEW

**Comment by andresilva** [comment]
Result of `nixpkgs-review pr 107003` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxPackages_zen.ixgbevf</li>
    <li>linuxPackages_zen.lttng-modules</li>
    <li>linuxPackages_zen.ndiswrapper</li>
    <li>linuxPackages_zen.nvidia_x11_legacy304</li>
    <li>linuxPackages_zen.phc-intel</li>
    <li>linuxPackages_zen.rtl8723bs</li>
    <li>linuxPackages_zen.sch_cake</li>
    <li>linuxPackages_zen.tbs</li>
  </ul>
</details>
<details>
  <summary>25 packages failed to build:</summary>
  <ul>
    <li>linuxPackages_zen.akvcam</li>
    <li>linuxPackages_zen.amdgpu-pro</li>
    <li>linuxPackages_zen.anbox</li>
    <li>linuxPackages_zen.broadcom_sta</li>
    <li>linuxPackages_zen.chipsec</li>
    <li>linuxPackages_zen.cryptodev</li>
    <li>linuxPackages_zen.dpdk</li>
    <li>linuxPackages_zen.ena</li>
    <li>linuxPackages_zen.evdi</li>
    <li>linuxPackages_zen.mwprocapture</li>
    <li>linuxPackages_zen.mxu11x0</li>
    <li>linuxPackages_zen.nvidia_x11_legacy340</li>
    <li>linuxPackages_zen.nvidia_x11_legacy390</li>
    <li>linuxPackages_zen.oci-seccomp-bpf-hook</li>
    <li>linuxPackages_zen.rtl8192eu</li>
    <li>linuxPackages_zen.rtl8812au</li>
    <li>linuxPackages_zen.rtl8814au</li>
    <li>linuxPackages_zen.rtl8821au</li>
    <li>linuxPackages_zen.rtl8821ce</li>
    <li>linuxPackages_zen.rtl8821cu</li>
    <li>linuxPackages_zen.rtl88x2bu</li>
    <li>linuxPackages_zen.rtl88xxau-aircrack</li>
    <li>linuxPackages_zen.rtlwifi_new</li>
    <li>linuxPackages_zen.virtualbox</li>
    <li>linuxPackages_zen.virtualboxGuestAdditions</li>
  </ul>
</details>
<details>
  <summary>47 packages built:</summary>
  <ul>
    <li>linuxPackages_zen.acpi_call</li>
    <li>linuxPackages_zen.asus-wmi-sensors</li>
    <li>linuxPackages_zen.batman_adv</li>
    <li>linuxPackages_zen.bbswitch</li>
    <li>linuxPackages_zen.bcc</li>
    <li>linuxPackages_zen.bpftrace</li>
    <li>linuxPackages_zen.can-isotp</li>
    <li>linuxPackages_zen.cpupower</li>
    <li>linuxPackages_zen.ddcci-driver</li>
    <li>linuxPackages_zen.digimend</li>
    <li>linuxPackages_zen.facetimehd</li>
    <li>linuxPackages_zen.fwts-efi-runtime</li>
    <li>linuxPackages_zen.gcadapter-oc-kmod</li>
    <li>linuxPackages_zen.hyperv-daemons</li>
    <li>linuxPackages_zen.intel-speed-select</li>
    <li>linuxPackages_zen.it87</li>
    <li>linuxPackages_zen.jool</li>
    <li>linux_zen (linuxPackages_zen.kernel)</li>
    <li>linuxPackages_zen.mba6x_bl</li>
    <li>linuxPackages_zen.netatop</li>
    <li>linuxPackages_zen.nvidia_x11 (linuxPackages_zen.nvidia_x11_beta)</li>
    <li>linuxPackages_zen.nvidia_x11_vulkan_beta</li>
    <li>linuxPackages_zen.nvidiabl</li>
    <li>linuxPackages_zen.openafs (linuxPackages_zen.openafs_1_8)</li>
    <li>linuxPackages_zen.openafs_1_9</li>
    <li>linuxPackages_zen.openrazer</li>
    <li>linuxPackages_zen.perf</li>
    <li>linuxPackages_zen.ply</li>
    <li>linuxPackages_zen.r8125</li>
    <li>linuxPackages_zen.r8168</li>
    <li>linuxPackages_zen.sysdig</li>
    <li>linuxPackages_zen.system76</li>
    <li>linuxPackages_zen.system76-acpi</li>
    <li>linuxPackages_zen.system76-io</li>
    <li>linuxPackages_zen.systemtap</li>
    <li>linuxPackages_zen.tmon</li>
    <li>linuxPackages_zen.tp_smapi</li>
    <li>linuxPackages_zen.turbostat</li>
    <li>linuxPackages_zen.tuxedo-keyboard</li>
    <li>linuxPackages_zen.usbip</li>
    <li>linuxPackages_zen.v4l2loopback</li>
    <li>linuxPackages_zen.v86d</li>
    <li>linuxPackages_zen.vhba</li>
    <li>linuxPackages_zen.x86_energy_perf_policy</li>
    <li>linuxPackages_zen.xpadneo</li>
    <li>linuxPackages_zen.zenpower</li>
    <li>linuxPackages_zen.zfs (linuxPackages_zen.zfsStable ,linuxPackages_zen.zfsUnstable)</li>
  </ul>
</details>

**Comment by andresilva** [comment]
I guess some new kernel modules need changes to support 5.10.

**Review by andresilva — APPROVED** [review]

**Comment by eyJhb** [comment]
evdi is fixed in a PR that hopefully will be merged soon.

Also coordination with this?  #106916

**Comment by Atemu** [comment]
linux_latest has been updeted to 5.10 already in master, I'm not so sure whether that bump is important.

**Comment by TredwellGit** [comment]
It is important for using new kernel features.

**Comment by Atemu** [comment]
Just ran into an error with dex2oatd while building an image with robotnix which I am not able to reproduce on 5.9-zen:

```
dex2oatd E 12-17 11:47:11  3370  3370 dex2oat.cc:2200] Failed to copy oat file to file: out/soong/cheeseburger/dex_apexjars_unstripped/system/framework/arm/apex.oat: Invalid argument
dex2oatd E 12-17 11:47:11  3370  3370 fd_file.cc:175] File out/soong/cheeseburger/dex_apexjars_unstripped/system/framework/arm/apex.oat wasn't explicitly flushed before destruction.
dex2oatd E 12-17 11:47:11  3370  3370 fd_file.cc:178] File out/soong/cheeseburger/dex_apexjars_unstripped/system/framework/arm/apex.oat wasn't explicitly closed before destruction.
dex2oatd F 12-17 11:47:11  3370  3370 fd_file.cc:180] Check failed: guard_state_ >= GuardState::kClosed (guard_state_=Base, GuardState::kClosed=Closed)
```

(at the end of the 2h build process of course...)

Have you ever run across something like this @danielfullmer?

Currently rebuilding with vanilla 5.10.

**Comment by danielfullmer** [comment]
@Atemu No, I haven't seen that error message in any robotnix builds before.

**Comment by Atemu** [comment]
Thanks!

The same happens on vanilla 5.10, so not a linux_zen-specific issue. (https://github.com/danielfullmer/robotnix/issues/74)

**Comment by Atemu** [comment]
Oh yeah, should probably also mention over here that the issue above was most likely caused by ZFS and also happens on the vanilla 5.10 kernel.

I didn't test 5.10-zen very much because of this but the kernel itself was working fine when I did use it.

**Comment by 7c6f434c** [comment]
Back in the old days headers were the oldest kernel version available, not the latest, and it still was generally fine.

**Pull request merged**
