### PR TITLE
youtube-dl: 2020.11.24 -> 2020.11.26

### PR DESCRIPTION
**Pull request by Luflosi**
###### Motivation for this change
https://github.com/ytdl-org/youtube-dl/releases/tag/2020.11.26

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lukegb** [comment]
Result of `nixpkgs-review pr 104931` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>bomi</li>
    <li>python37Packages.tubeup</li>
    <li>python38Packages.tubeup</li>
  </ul>
</details>
<details>
  <summary>35 packages built:</summary>
  <ul>
    <li>catt</li>
    <li>celluloid</li>
    <li>curseradio</li>
    <li>haskellPackages.cut-the-crap</li>
    <li>jellyfin-mpv-shim</li>
    <li>jftui</li>
    <li>kodi-cli</li>
    <li>lollypop</li>
    <li>minitube</li>
    <li>mkchromecast</li>
    <li>mopidy-youtube</li>
    <li>mpc-qt</li>
    <li>mps-youtube</li>
    <li>mpv</li>
    <li>mpvScripts.mpris</li>
    <li>persepolis</li>
    <li>plex-media-player</li>
    <li>plex-mpv-shim</li>
    <li>python27Packages.pafy</li>
    <li>python27Packages.youtube-dl</li>
    <li>python27Packages.youtube-dl-light</li>
    <li>python37Packages.mpv</li>
    <li>python37Packages.pafy</li>
    <li>python37Packages.youtube-dl</li>
    <li>python37Packages.youtube-dl-light</li>
    <li>python38Packages.mpv</li>
    <li>python38Packages.pafy</li>
    <li>youtube-dl (python38Packages.youtube-dl)</li>
    <li>youtube-dl-light (python38Packages.youtube-dl-light)</li>
    <li>qimgv</li>
    <li>somafm-cli</li>
    <li>sublime-music</li>
    <li>tartube</li>
    <li>tuijam</li>
    <li>ytcc</li>
  </ul>
</details>

**Review by lukegb — APPROVED** [review]
youtube-dl doesn't seem to run in that environment though, I get

```
Traceback (most recent call last):
  File "/nix/store/mw9hjrzgd81qbdq4anscpxgsc0j46my2-python3.8-youtube-dl-2020.11.26/bin/.youtube-dl-wrapped", line 6, in <module>
    from youtube_dl import main
  File "/nix/store/ka6q3w2vyj979jp0iqc86ddnb5xvczcz-python3.7-youtube-dl-2020.11.26/lib/python3.7/site-packages/youtube_dl/__init__.py", line 15, in <module>
    from .options import (
  File "/nix/store/ka6q3w2vyj979jp0iqc86ddnb5xvczcz-python3.7-youtube-dl-2020.11.26/lib/python3.7/site-packages/youtube_dl/options.py", line 8, in <module>
    from .downloader.external import list_external_downloaders
  File "/nix/store/ka6q3w2vyj979jp0iqc86ddnb5xvczcz-python3.7-youtube-dl-2020.11.26/lib/python3.7/site-packages/youtube_dl/downloader/__init__.py", line 5, in <module>
    from .hls import HlsFD
  File "/nix/store/ka6q3w2vyj979jp0iqc86ddnb5xvczcz-python3.7-youtube-dl-2020.11.26/lib/python3.7/site-packages/youtube_dl/downloader/hls.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "/nix/store/4p0d9jzgfn0xj2sbqb1clahxmq2g1s9s-python3.7-pycryptodome-3.9.9/lib/python3.7/site-packages/Crypto/Cipher/__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "/nix/store/4p0d9jzgfn0xj2sbqb1clahxmq2g1s9s-python3.7-pycryptodome-3.9.9/lib/python3.7/site-packages/Crypto/Cipher/_mode_ecb.py", line 35, in <module>
    raw_ecb_lib = load_pycryptodome_raw_lib("Crypto.Cipher._raw_ecb", """
  File "/nix/store/4p0d9jzgfn0xj2sbqb1clahxmq2g1s9s-python3.7-pycryptodome-3.9.9/lib/python3.7/site-packages/Crypto/Util/_raw_api.py", line 308, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cpython-38-x86_64-linux-gnu.so': /nix/store/4p0d9jzgfn0xj2sbqb1clahxmq2g1s9s-python3.7-pycryptodome-3.9.9/lib/python3.7/site-packages/Crypto/Util/../Cipher/_raw_ecb.cpython-38-x86_64-linux-gnu.so: cannot open shared object file: No such file or directory, Trying '_raw_ecb.abi3.so': /nix/store/4p0d9jzgfn0xj2sbqb1clahxmq2g1s9s-python3.7-pycryptodome-3.9.9/lib/python3.7/site-packages/Crypto/Util/../Cipher/_raw_ecb.abi3.so: cannot open shared object file: No such file or directory, Trying '_raw_ecb.so': /nix/store/4p0d9jzgfn0xj2sbqb1clahxmq2g1s9s-python3.7-pycryptodome-3.9.9/lib/python3.7/site-packages/Crypto/Util/../Cipher/_raw_ecb.so: cannot open shared object file: No such file or directory
```

which is incredibly suspicious because there's both a python3.8 and python3.7 youtube-dl hanging out there.

Anyway, unsetting PYTHONPATH and running ./results/youtube-dl/bin/youtube-dl on a Spreaker URL (new in this release) seems to work properly, so LGTM.

**Comment by Ma27** [comment]
@AndersonTorres can you also take care of the backport? :)

**Comment by AndersonTorres** [comment]
@Ma27 looks fine but I never dit it before. Do you have a link to a tutorial or something?

**Comment by SuperSandro2000** [comment]
> @Ma27 looks fine but I never dit it before. Do you have a link to a tutorial or something?

https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#backporting-changes

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 104931` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages marked as broken and skipped:</summary>
  <ul>
    <li>haskellPackages.cut-the-crap</li>
    <li>jellyfin-mpv-shim</li>
    <li>kodi-cli</li>
    <li>persepolis</li>
    <li>sublime-music</li>
  </ul>
</details>
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>mopidy-youtube</li>
    <li>mpc-qt</li>
    <li>python37Packages.tubeup</li>
    <li>python38Packages.tubeup</li>
  </ul>
</details>
<details>
  <summary>19 packages built:</summary>
  <ul>
    <li>catt</li>
    <li>curseradio</li>
    <li>mkchromecast</li>
    <li>mps-youtube</li>
    <li>plex-mpv-shim</li>
    <li>python27Packages.pafy</li>
    <li>python27Packages.youtube-dl</li>
    <li>python27Packages.youtube-dl-light</li>
    <li>python37Packages.mpv</li>
    <li>python37Packages.pafy</li>
    <li>python37Packages.youtube-dl</li>
    <li>python37Packages.youtube-dl-light</li>
    <li>python38Packages.mpv</li>
    <li>python38Packages.pafy</li>
    <li>youtube-dl (python38Packages.youtube-dl)</li>
    <li>youtube-dl-light (python38Packages.youtube-dl-light)</li>
    <li>somafm-cli</li>
    <li>tuijam</li>
    <li>ytcc</li>
  </ul>
</details>

Broken packages are either already fixed or require youtube-dlc

**Comment by erictapen** [comment]
Was backported in 939603027de367119ad47adb3b5cda75d300c871.

**Pull request merged**
