### PR TITLE
qownnotes: 19.7.3 -> 19.8.6, use qt's mkDerivation

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

Update, fix (cc #65399).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @dtzWill O:)

### CODE REVIEW

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS
diff LGTM
binary seems to work
leaf package

```
[3 built, 5 copied (6.5 MiB), 1.2 MiB DL]
https://github.com/NixOS/nixpkgs/pull/66987
1 package were build:
qownnotes
```

**Review by worldofpeace — APPROVED** [review]
LGTM, executes on my machine without runtime error. Confirmed it's wrapped.

**Comment by worldofpeace** [comment]
Can you squash your commits @dtzWill?

**Comment by dtzWill** [comment]
Squashed, rebased, pushed! <3

**Pull request merged**
