### PR TITLE
ocamlPackages.elpi: 1.10.2 -> 1.11.0

### PR DESCRIPTION
**Pull request by CohenCyril**
###### Motivation for this change

Update ocamlPackages.elpi version.
Does not build yet... (@vbgl @gares I do not understand why...)
cf https://gist.github.com/CohenCyril/fb450004e71c822313fb84da611b20d8#file-build_log-L63-L66

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by CohenCyril** [comment]
@GrahamcOfBorg build ocamlPackages.elpi

**Comment by vbgl** [comment]
Then #87694 should fix this.

**Comment by CohenCyril** [comment]
@gares @vbgl I rebased on #87694 for the test, and it remove one error message out of three.
cf https://gist.github.com/CohenCyril/0bf93ea4c36d0282b207cb334436251d

**Comment by CohenCyril** [comment]
@GrahamcOfBorg build ocamlPackages.elpi

**Comment by CohenCyril** [comment]
@vgbl commit 20b558a works for me, I had to bump up ocaml-migrate-parsetree and ppxfind, should I do it globally or via overrides? in a separate PR or in this one?

**Comment by vbgl** [comment]
If the changes are independent, separate PRs I find easier to review.

Updating ppxfind might break a few things.

**Comment by vbgl** [comment]
After quick testing, it seems that OMP and ppxfind should be both updated at once. Also, to avoid breaking 2⁸ packages, you may need #87824.

**Comment by gares** [comment]
@CohenCyril , is the bump of ppxfind really needed?

**Comment by CohenCyril** [comment]
> > @CohenCyril , is the bump of ppxfind really needed?
> 
> it was needed for OMP 1.7 but maybe not for 1.6 let me check!

nop... (https://github.com/jeremiedimino/ppxfind/releases/tag/1.4)

**Review by vbgl — CHANGES_REQUESTED** [review]
There is no need for the complexity of several versions of OMP and ppxfind.

**Comment by CohenCyril** [comment]
> There is no need for the complexity of several versions of OMP and ppxfind.

Good to know, I did not know how to check whether a change like #88087 broke stuff, so I worked-around. I will update this PR as soon as #88087 is merged. But anyway I am still waiting for coq-elpi's next release before changing this pr to "ready".

**Comment by gares** [comment]
This is draft PR ready to be promoted to a real PR? It seems so

**Comment by Zimmi48** [comment]
@CohenCyril I recommend fetching the dune-release tarball, i.e. something like
```nix
{
  src = fetchzip {
    url = "https://github.com/LPCIC/elpi/releases/download/v${version}/elpi-v${version}.tbz";
    sha256 = "15hamy9ifr05kczadwh3yj2gmr12a9z1jwppmp5yrns0vykjbj76";
}
```

so that `elpi -version` works correctly.

It's also a bit depressing that this PR has to move away from using `buildDunePackage`, with all the complexity that calling `mkDerivation` directly entails.

**Comment by CohenCyril** [comment]
@gares
> This is draft PR ready to be promoted to a real PR? It seems so

Not until we release hiearchy builder (I faked the existence of `0.9.1+alpha1` here)

@Zimmi48 
> @CohenCyril I recommend fetching the dune-release tarball, i.e. something like

I will try




> It's also a bit depressing that this PR has to move away from using `buildDunePackage`, with all the complexity that calling `mkDerivation` directly entails.

I agree,... @gares what difference would it make if we called dune directly rather than make?

**Comment by CohenCyril** [comment]
@GrahamcOfBorg build ocamlPackages.elpi

**Comment by CohenCyril** [comment]
@GrahamcOfBorg build ocamlPackage.elpi coqPackages_8_11.coq-elpi coqPackages_8_11.hierarchy-builder

**Comment by gares** [comment]
> I agree,... @gares what difference would it make if we called dune directly rather than make?

The only different thing is that in Makefile I *hack* elpi.install since it wants to install ppxfindcache_* which are *internal* binaries. I can't make them internal otherwise dune does not build them before calling the ppx rules that these binaries. I've never figured out if it is a real bug, or if I'm doing something wrong. I may even had open a bug on dune and forgot.

How does nix compute which files are part of a package?

**Comment by CohenCyril** [comment]
> How does nix compute which files are part of a package?

everything that is copied to the `$out` directory is part of the package.

**Comment by gares** [comment]
hum, then you can probably call dune and only keep the `elpi` binary (no other binary in $out/bin)

**Comment by CohenCyril** [comment]
alright!

**Comment by gares** [comment]
It's green

**Comment by CohenCyril** [comment]
> hum, then you can probably call dune and only keep the `elpi` binary (no other binary in $out/bin)

@gares, the contents of `$out/bin` is `elpi`, `ppxfindcache_deriving_std` and `ppxfindcache_elpi_trace_deriving_std`.
If I try to remove anything, `coq-elpi` does not compile anymore. Is it normal?

**Comment by gares** [comment]
these binaries are not used by coq-elpi Makefile. So it is fishy. (Also, I remove them in Opam...)

**Comment by gares** [comment]
You can leave them there, they won't hurt. They are just useless.

**Comment by CohenCyril** [comment]
@GrahamcOfBorg build ocamlPackage.elpi coqPackages_8_11.coq-elpi coqPackages_8_11.hierarchy-builder

**Comment by CohenCyril** [comment]
@vbgl all green :+1:

**Comment by vbgl** [comment]
@GrahamcOfBorg build coqPackages_8_11.hierarchy-builder

**Review by vbgl — APPROVED** [review]

**Pull request merged**
