### PR TITLE
prosody: fixes

### PR DESCRIPTION
**Pull request by arcnmx**
###### Motivation for this change

Either I'm crazy or no one uses lua/prosody :(

Each of these changes were necessary to get it to run again on my system. I'm open to suggestions on how to name/approach the luaEnv extension problem, or otherwise utilize setuphooks to make the old way work again. To summarize the problems I ran into:

- `LUA_PATH`/`LUA_CPATH` are now empty variables, and generating them from `luaEnv` appears to be the recommended way to replace them (cc @teto who can confirm this or offer suggestions?)
- `makeWrapper` cannot handle prefixing values that contain special wildcard characters such as the `?` placeholder used by lua paths
  this commit is separate because it can be reverted later once the bug affecting `makeWrapper` is identified/fixed
- using `luaEnv` as the sole source for `LUA_PATH`/`LUA_CPATH` means that `withExtraLibs` can't be used to add lua packages to the closure/wrapper (like it could in the past)
  the new extension function approach might be "better" anyway because it's guaranteed to use the correct luaPackages package set (and there's precedent in nixpkgs for other similar wrappers for python/etc that do this afair), but it isn't as obvious/discoverable to use.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by fpletz — APPROVED** [review]
Unfortunately I'm not using prosody anymore. But the NixOS test now works again with your changes and I see no reason not to merge this. Thanks! :+1:

**Comment by Izorkin** [comment]
Error add package `luadbi-mysql`
```
  withExtraLuaPackages = [ pkgs.luajitPackages.luadbi-mysql ];
```
```
error: attempt to call something which is not a function but a list

       at /home/lafiel/works/src-nix/nixpkgs/pkgs/servers/xmpp/prosody/default.nix:21:8:

           20|     ++ lib.optional withDBI p.luadbi
           21|     ++ withExtraLuaPackages p
             |        ^
           22|   );

```

```
  withExtraLuaPackages = [ "luadbi-mysql" ];
```
```
error: attempt to call something which is not a function but a list

       at /home/lafiel/works/src-nix/nixpkgs/pkgs/servers/xmpp/prosody/default.nix:21:8:

           20|     ++ lib.optional withDBI p.luadbi
           21|     ++ withExtraLuaPackages p
             |        ^
           22|   );

```

**Comment by arcnmx** [comment]
> Error add package `luadbi-mysql`

It would be useful to add an example somewhere, yeah. Try `p: [ p.luadbi-mysql ]` instead.

**Comment by Izorkin** [comment]
@arcnmx thanks, working!

**Comment by talyz** [comment]
I guess 16d0b4a69f94adb523da8732b231b0d1738bd713 shouldn't have been merged, since the bug it works around was already fixed?

**Comment by arcnmx** [comment]
> I guess [16d0b4a](https://github.com/NixOS/nixpkgs/commit/16d0b4a69f94adb523da8732b231b0d1738bd713) shouldn't have been merged, since the bug it works around was already fixed?

Well no, the fix is still stuck in staging at the moment. I'd been waiting to make a revert PR because I wasn't sure how quickly it was going to run through staging-next but I should go ahead and just do that now.

**Pull request merged**
