### PR TITLE
turses: switch back to python 3.7

### PR DESCRIPTION
**Pull request by booxter**

### CODE REVIEW

**Review by FRidh — CHANGES_REQUESTED** [review]
motivation is missing from commit msg

**Comment by mmahut** [comment]
@booxter any updates please?

**Comment by booxter** [comment]
@mmahut @FRidh I thought getting rid of older python builds is a motivation itself because it eventually allows to not ship / install older language stack + removes a special case in the `turses` package. But if it's not, then this should be closed.

**Comment by FRidh** [comment]
Yes, you are right about that, however, your commit message says "switch back..." which implies it was done for a reason. Does that reason no longer apply then? It's just a matter of communication here.

**Comment by Mic92** [comment]
i.e: Fix python3.7 support

**Pull request merged**
