### PR TITLE
coreboot-toolchain: if gnat11.meta.broken then omit ada

### PR DESCRIPTION
**Pull request by ghost**
ZHF: #172160

###### Description of changes

Gnat requires a long and increasingly-fragile bootstrapping chain; it has [been broken in past releases](https://github.com/NixOS/nixpkgs/commit/6ac7b19c978e951c124c5ea434c94f95f593888e) and recently [broke just six days before the end of ZHF 22.05](https://github.com/NixOS/nixpkgs/issues/172160#issuecomment-1128719763), and remains broken, which **puts coreboot-tools at risk of being [marked broken](https://github.com/NixOS/nixpkgs/pull/173671) in the 22.05 release**.  The [only proposed fix for gnat](https://github.com/NixOS/nixpkgs/issues/172160#issuecomment-1133012282) requires a patch to `glibc`, which would cause a global rebuild; the ZHF managers are unlikely to agree to something like that with 10 days left until release.

To guard against `coreboot-tools` being marked broken in 22.05 and future releases, let's fall back to omitting ada support (and therefore libgfxinit) rather than failing completely.

Tested with gnat11 marked broken.

On systems that do not pull from cachix, PR #171223 is also required in order to fully unbreak coreboot-toolchain.  Please consider merging that PR as well.  It isn't possible to build `coreboot-toolchain` without that; the only reason we aren't getting failures is because of cached artifacts.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by a-m-joseph** [comment]
@ofborg build coreboot-toolchain

**Comment by a-m-joseph** [comment]
@ofborg build coreboot-toolchain

**Comment by a-m-joseph** [comment]
@ofborg build coreboot-toolchain

**Comment by a-m-joseph** [comment]
ofborg says: coreboot-toolchain on x86_64-linux — [Success](https://github.com/NixOS/nixpkgs/pull/173808/checks?check_run_id=6532657540)

My own rebuild is still running but I will undraft this (and revert the mark-gnat-broken patch) based on ofborg's success.

**Comment by felixsinger** [comment]
I will reply later in the day. I don't have time now.

**Comment by a-m-joseph** [comment]
Closed by #173893 (for this release cycle, at least)

**Pull request closed without merging**
