### PR TITLE
lego: 4.8.0 -> 4.9.0

### PR DESCRIPTION
**Pull request by esclear**
###### Description of changes
[Changelog](https://github.com/go-acme/lego/releases/tag/v4.9.0)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by m1cr0man — APPROVED** [review]
Built (via rebase) against #191861. Don't see anything in the change log to be concerned about. Happy to merge 🙂

**Review by andrew-d — APPROVED** [review]

**Comment by rien** [comment]
Hi, it seems that this update broke ACME in my particular setup (wildcard cert, DNS-01 with CNAME's). Apparently a known issue: https://github.com/go-acme/lego/issues/1710

I'll try to look for a fix.

**Comment by m1cr0man** [comment]
You could potentially disable the [dnsPropagationCheck](https://search.nixos.org/options?channel=22.05&show=security.acme.certs.%3Cname%3E.dnsPropagationCheck&from=0&size=50&sort=relevance&type=packages&query=dnsProp) in the mean time, assuming your provider instantly sets new records. Otherwise yeah you might have to wait. If you can figure out a patch for lego itself you could inject and build that in NixOS too using an overlay.

**Comment by rien** [comment]
I've tried that fix just now, and it does not seem to work.

It seems they are looking at the issue, so I'll wait a bit. In the meantime, I'll try to downgrade `lego`.

**Comment by m1cr0man** [comment]
Oh of course - you could roll back lego too. Assuming you are using flakes:

- Add the nixpkgs repo at a revision before this PR (nixpkgs_old).
- Add an overlay setting lego to the old package

I'm on mobile but I'd otherwise type out an example overlay 😅

**Comment by rien** [comment]
Downgrade lego has resolved my issue.

**Comment by m1cr0man** [comment]
Great. I'll keep an eye out for the next lego update and might ask you to test it if you have the time 🙂

**Comment by rien** [comment]
I've already subbed on that issue :) I'll keep an eye out as well.

**Comment by mweinelt** [comment]
It would probably be best to nudge the maintainer by offering to test this.

**Pull request merged**
