### PR TITLE
python3Packages.zigpy: 0.26.0 -> 0.28.2, python3Packages.aiosqlite: 0.12.0 -> 0.16.0, python3Packages.zha-quirks: 0.0.47 -> 0.0.48, fix tests

### PR DESCRIPTION
**Pull request by mvnetbiz**
###### Motivation for this change
Fix zigpy modules

###### Things done
- Updated zigpy
- updated aiosqlite

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mvnetbiz** [comment]
zha-quirks is also broken again, let me fix that first.

**Comment by mvnetbiz** [comment]
I have some other problem preventing me from loading my complete Homeassistant config, but this loads the zha component in a vm fine.

**Comment by mvnetbiz** [comment]
Result of `nixpkgs-review pr 106778` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python39Packages.databases</li>
    <li>python39Packages.fastapi</li>
    <li>python39Packages.orm</li>
    <li>python39Packages.starlette</li>
  </ul>
</details>
<details>
  <summary>8 packages failed to build:</summary>
  <ul>
    <li>python37Packages.databases</li>
    <li>python37Packages.fastapi</li>
    <li>python37Packages.orm</li>
    <li>python37Packages.starlette</li>
    <li>python38Packages.databases</li>
    <li>python38Packages.fastapi</li>
    <li>python38Packages.orm</li>
    <li>python38Packages.starlette</li>
  </ul>
</details>
<details>
  <summary>24 packages built:</summary>
  <ul>
    <li>python37Packages.aiosqlite</li>
    <li>python37Packages.bellows</li>
    <li>python37Packages.zha-quirks</li>
    <li>python37Packages.zigpy</li>
    <li>python37Packages.zigpy-deconz</li>
    <li>python37Packages.zigpy-znp</li>
    <li>python38Packages.aiosqlite</li>
    <li>python38Packages.bellows</li>
    <li>python38Packages.zha-quirks</li>
    <li>python38Packages.zigpy</li>
    <li>python38Packages.zigpy-cc</li>
    <li>python38Packages.zigpy-deconz</li>
    <li>python38Packages.zigpy-xbee</li>
    <li>python38Packages.zigpy-zigate</li>
    <li>python38Packages.zigpy-znp</li>
    <li>python39Packages.aiosqlite</li>
    <li>python39Packages.bellows</li>
    <li>python39Packages.zha-quirks</li>
    <li>python39Packages.zigpy</li>
    <li>python39Packages.zigpy-cc</li>
    <li>python39Packages.zigpy-deconz</li>
    <li>python39Packages.zigpy-xbee</li>
    <li>python39Packages.zigpy-zigate</li>
    <li>python39Packages.zigpy-znp</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
> Result of `nixpkgs-review pr 106778` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
> 
> 4 packages marked as broken and skipped:
> 8 packages failed to build:
> * python37Packages.databases
> * python37Packages.fastapi
> * python37Packages.orm
> * python37Packages.starlette
> * python38Packages.databases
> * python38Packages.fastapi
> * python38Packages.orm
> * python38Packages.starlette
> 
> 24 packages built:

The build failures should be fixed in one of my big python PRs.

**Comment by mweinelt** [comment]
I'm sorry I missed this, it was WIP when I first looked at it and I didn't notice when it was finished. By now the most recent version of home-assistant depends on even newer versions, e.g.:

```
homeassistant/components/zha/manifest.json
13:    "zigpy==0.29.0",
homeassistant/components/zha/manifest.json
10:    "zha-quirks==0.0.51",
```

Superseded by #107975.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 106778` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
4 packages marked as broken and skipped:
</summary>
<ul>
<li>python39Packages.databases</li>
<li>python39Packages.fastapi</li>
<li>python39Packages.orm</li>
<li>python39Packages.starlette</li>
</ul>
</details>
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>python38Packages.orm: log was empty</li>
  </ul>
</details>
<details>
<summary>
31 packages built:
</summary>
<ul>
<li>python37Packages.aiosqlite</li>
<li>python37Packages.bellows</li>
<li>python37Packages.databases</li>
<li>python37Packages.fastapi</li>
<li>python37Packages.orm</li>
<li>python37Packages.starlette</li>
<li>python37Packages.zha-quirks</li>
<li>python37Packages.zigpy</li>
<li>python37Packages.zigpy-deconz</li>
<li>python37Packages.zigpy-znp</li>
<li>python38Packages.aiosqlite</li>
<li>python38Packages.bellows</li>
<li>python38Packages.databases</li>
<li>python38Packages.fastapi</li>
<li>python38Packages.starlette</li>
<li>python38Packages.zha-quirks</li>
<li>python38Packages.zigpy</li>
<li>python38Packages.zigpy-cc</li>
<li>python38Packages.zigpy-deconz</li>
<li>python38Packages.zigpy-xbee</li>
<li>python38Packages.zigpy-zigate</li>
<li>python38Packages.zigpy-znp</li>
<li>python39Packages.aiosqlite</li>
<li>python39Packages.bellows</li>
<li>python39Packages.zha-quirks</li>
<li>python39Packages.zigpy</li>
<li>python39Packages.zigpy-cc</li>
<li>python39Packages.zigpy-deconz</li>
<li>python39Packages.zigpy-xbee</li>
<li>python39Packages.zigpy-zigate</li>
<li>python39Packages.zigpy-znp</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

python37Packages.bellows:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>
python37Packages.zigpy-deconz:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>
python38Packages.bellows:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>
python38Packages.zigpy-deconz:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>
python39Packages.bellows:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>
python39Packages.zigpy-deconz:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>

orm is being fixed in another pr.

**Pull request closed without merging**
