### PR TITLE
cosmic-comp: unstable-2023-10-04 -> unstable-2023-11-13

### PR DESCRIPTION
**Pull request by nyabinary**
## Description of changes
Formatting, move cosmic-comp to by-name, updating, and fixed package (xwayland was broken)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alyssais** [comment]
For the same reason as in https://github.com/NixOS/nixpkgs/pull/266378#pullrequestreview-1723096205, are there user-visible changes in this update?

**Comment by Nyabinary** [comment]
> For the same reason as in [#266378 (review)](https://github.com/NixOS/nixpkgs/pull/266378#pullrequestreview-1723096205), are there user-visible changes in this update?

Yes, theming support and also xwayland was broken in the derivation before.

**Comment by alyssais** [comment]
> xwayland was broken in the derivation before.

I mean, we can fix that one without committing a new Cargo.lock.

But theming support is a good reason!

**Review by alyssais — APPROVED** [review]

**Review by alyssais — CHANGES_REQUESTED** [review]
Please don't set `repo = pname;`.  It adds indirection, which reduces cognitive overhead when reading, but isn't going to ever safe us any work.  It was fine as it was.

**Comment by Nyabinary** [comment]
> Please don't set `repo = pname;`. It adds indirection, which reduces cognitive overhead when reading, but isn't going to ever safe us any work. It was fine as it was.

Aw alright :3

**Review by alyssais — APPROVED** [review]

**Review by alyssais — APPROVED** [review]

**Pull request merged**
