### PR TITLE
mkvtoolnix: 53.0.0 -> 55.0.0

### PR DESCRIPTION
**Pull request by tricktron**
###### Motivation for this change

Update `mkvtoolnix` to the latest version. This may lead to a possible merge conflict with the automatic pull request https://github.com/NixOS/nixpkgs/pull/114742

###### Change details

- The new `-lc++fs` is needed for `clang7` because `mkvtoolnix` now uses the `c++17 std::filesystem` instead of the `boost/filesystem`.
- The `"-DCMAKE_INSTALL_PREFIX="` cmake flag removes the prefix to fix the
```bash
ld: warning: directory not found for option
'-L/nix/store/3wzvdvkj8aajgnn6l240vq5fbgvjw91w-libmatroska-1.6.2//nix/store/3wzvdvkj8aajgnn6l240vq5fbgvjw91w-libmatroska-1.6.2/lib'
```
(See the [latest hydra logs](https://hydra.nixos.org/build/138004974/nixlog/1))

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 116296` at 6cd0ab08 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>libsForQt512.elisa</li>
    <li>libsForQt514.elisa</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build (new failures):</summary>
  <ul>
    <li><a href="https://gist.github.com/e6d37cef8686583cac194c6791e7ccff">obs-ndi</a></li></li>
  </ul>
</details>
<details>
  <summary>8 packages skipped due to time constraints:</summary>
  <ul>
    <li>liblinphone</li>
    <li>libsForQt5.elisa (libsForQt515.elisa ,plasma5Packages.elisa)</li>
    <li>linphone</li>
    <li>megaglest</li>
    <li>minitube</li>
    <li>reaper</li>
    <li>strawberry</li>
    <li>vlc (vlc_qt5)</li>
  </ul>
</details>
<details>
  <summary>22 packages built successfully:</summary>
  <ul>
    <li><a href="https://gist.github.com/541064d3ef10c023a7f7d78626471811">gerbera</a></li></li>
    <li><a href="https://gist.github.com/4af44510d79019f0df500713f3884311">libebml</a></li></li>
    <li><a href="https://gist.github.com/9f1f81b4bd54f30267998656174ae92c">libmatroska</a></li></li>
    <li><a href="https://gist.github.com/ef73537e9148acc4002d60b497db5164">libsForQt5.phonon-backend-vlc</a></li> (libsForQt515.phonon-backend-vlc ,plasma5Packages.phonon-backend-vlc)</li>
    <li><a href="https://gist.github.com/7ea9c1332b30731d2943e066f6f04da7">libsForQt512.phonon-backend-vlc</a></li></li>
    <li><a href="https://gist.github.com/4dc25012d5aaba9eb851a9397f634161">libsForQt514.phonon-backend-vlc</a></li></li>
    <li><a href="https://gist.github.com/ae8507d3118100cc1ea293907ff1ec76">libvlc</a></li></li>
    <li><a href="https://gist.github.com/cb6ad2145e7d7673e52ea013a3fe4e69">mediastreamer</a></li></li>
    <li><a href="https://gist.github.com/e053ebe924e707d1f75fe7b0de7d8a6d">mediastreamer-openh264</a></li></li>
    <li><a href="https://gist.github.com/70a8c7c757f03ad6a62adbad4c1d4bbc">mkvtoolnix</a></li></li>
    <li><a href="https://gist.github.com/3ac05a73f854eb74b0e90ca1bece9c31">mkvtoolnix-cli</a></li></li>
    <li><a href="https://gist.github.com/810af6511fbb2fc5c9c6e4f2d916e559">mpvScripts.convert</a></li></li>
    <li><a href="https://gist.github.com/ec8eefe731872d8842f6ecd0703e6c62">msilbc</a></li></li>
    <li><a href="https://gist.github.com/ae0464a02128984f67e32f6b955625c0">obs-gstreamer</a></li></li>
    <li><a href="https://gist.github.com/a1360f6fa6146fc35c8563e8fda27712">obs-move-transition</a></li></li>
    <li><a href="https://gist.github.com/76ee7e6a71e41da3c112a13bd4573dd7">obs-studio</a></li></li>
    <li><a href="https://gist.github.com/9db039c116befff93ccb00d3e061eb7a">obs-v4l2sink</a></li></li>
    <li><a href="https://gist.github.com/f81878a52ca4684a142dcd0ba3a74e19">obs-wlrobs</a></li></li>
    <li><a href="https://gist.github.com/a735f93e88c77c0332306addd3774f5e">pympress</a></li></li>
    <li><a href="https://gist.github.com/92c66deb78893b2fb7537e3bc8a6c6a3">python38Packages.python-vlc</a></li></li>
    <li><a href="https://gist.github.com/7b535de410f95ce4f5ab60a7e8a7cd7d">python39Packages.python-vlc</a></li></li>
    <li><a href="https://gist.github.com/e6f94ef361674d2bd13a29331f77be9d">tribler</a></li></li>
  </ul>
</details>
<details>
  <summary>6 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

qt5.wrapQtAppsHook is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/applications/video/mkvtoolnix/default.nix:30:3:
```
   |
30 |   buildInputs = [
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/applications/video/mkvtoolnix/default.nix:37:3:
```
   |
37 |   buildPhase   = "drake -j $NIX_BUILD_CORES";
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/applications/video/mkvtoolnix/default.nix:38:3:
```
   |
38 |   installPhase = "drake install -j $NIX_BUILD_CORES";
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl2` is a deprecated license, check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/applications/video/mkvtoolnix/default.nix:64:5:
```
   |
64 |     license     = licenses.gpl2;
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`lgpl21` is a deprecated license, check if project uses `lgpl21Plus` or `lgpl21Only` and change `meta.license` accordingly.

Near pkgs/development/libraries/libebml/default.nix:24:5:
```
   |
24 |     license = licenses.lgpl21;
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`lgpl21` is a deprecated license, check if project uses `lgpl21Plus` or `lgpl21Only` and change `meta.license` accordingly.

Near pkgs/development/libraries/libmatroska/default.nix:27:5:
```
   |
27 |     license = licenses.lgpl21;
   |     ^
```
</li>
  </ul>
</details>

**Comment by rnhmjoj** [comment]
While you're at it, can you change the license to `gpl2Only`?

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]
Please do one commit per package update.

**Comment by tricktron** [comment]
@rnhmjoj Done
@SuperSandro2000 Done

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 116296` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages marked as broken and skipped:
</summary>
<ul>
<li>libsForQt512.elisa</li>
<li>libsForQt514.elisa</li>
</ul>
</details>
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>obs-ndi: log was empty</li>
  </ul>
</details>
<details>
<summary>
30 packages built:
</summary>
<ul>
<li>gerbera</li>
<li>libebml</li>
<li>liblinphone</li>
<li>libmatroska</li>
<li>libsForQt5.elisa (libsForQt515.elisa ,plasma5Packages.elisa)</li>
<li>libsForQt5.phonon-backend-vlc (libsForQt515.phonon-backend-vlc ,plasma5Packages.phonon-backend-vlc)</li>
<li>libsForQt512.phonon-backend-vlc</li>
<li>libsForQt514.phonon-backend-vlc</li>
<li>libvlc</li>
<li>linphone</li>
<li>mediastreamer</li>
<li>mediastreamer-openh264</li>
<li>megaglest</li>
<li>minitube</li>
<li>mkvtoolnix</li>
<li>mkvtoolnix-cli</li>
<li>mpvScripts.convert</li>
<li>msilbc</li>
<li>obs-gstreamer</li>
<li>obs-move-transition</li>
<li>obs-studio</li>
<li>obs-v4l2sink</li>
<li>obs-wlrobs</li>
<li>pympress</li>
<li>python38Packages.python-vlc</li>
<li>python39Packages.python-vlc</li>
<li>reaper</li>
<li>strawberry</li>
<li>tribler</li>
<li>vlc (vlc_qt5)</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
gerbera:
<details>


warning: unclear-gpl
`gpl2` is a deprecated license, check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/servers/gerbera/default.nix:73:5:

```
   |
73 |     license = licenses.gpl2;
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
</details>

**Review by rnhmjoj — APPROVED** [review]
Thank you, all. Looks good to me.

**Pull request merged**
