### PR TITLE
create_ap: fix path

### PR DESCRIPTION
**Pull request by SCOTT-HAMILTON**
###### Description of changes

Fixed the path for create_ap module using [this script](https://gist.github.com/SCOTT-HAMILTON/63070397f9369c44fa47c26750531803) made for the occasion.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Pinging maintainer: @onny

### CODE REVIEW

**Comment by onny** [comment]
Hey @SCOTT-HAMILTON thanks for working on this module and package :)

If the script `create_ap` is missing some dependencies we should definitely add them. Because `create_ap` could also be run from the command line outside of the module, I added the dependencies to the `wrapProgram` path here `pkgs/os-specific/linux/linux-wifi-hotspot/default.nix`:
```
  postInstall = ''
    wrapProgram $out/bin/create_ap \
      --prefix PATH : ${lib.makeBinPath [
          hostapd getopt iw which dnsmasq iproute2 flock iptables gawk
        ]}
```

Maybe we should the missing dependencies here instead?

**Comment by SCOTT-HAMILTON** [comment]
Made that change, you're right.

**Review by onny — APPROVED** [review]
LGTM! Thank you for enhancing the package :)

**Comment by happysalada** [comment]
borg seems to fail on building of a dependency, I guess staging is broken, but it seems unrelated.
I'm going to go ahead with merging, but posting what is happening here in case that commit gets inspected later on.

**Pull request merged**
