### PR TITLE
orca-slicer: 2.1.1 -> 2.2.0

### PR DESCRIPTION
**Pull request by jonboh**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

I've removed `previousAttrs.patches` from patches as the latest stable release of BambuStudio still needs the `meshboolean-const.patch`, but OrcaSlicer has already performed this change in their own code. Once the stable release of BambuStudio fixes that issue as well it can be added back again and remove the explicit mention of the 0001 patch. Also, the 0002 patch is no longer necessary.

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by pinpox** [comment]
There is also this PR: which fixes some bugs and adds another maintainer. https://github.com/NixOS/nixpkgs/pull/348091
I think we should merge that first to avoid conflicts

**Comment by pinpox** [comment]
@jonboh https://github.com/NixOS/nixpkgs/pull/348091 fixed some segaults, but made this PR have merge conflicts. Could you rebase against master and test it again?

**Comment by jonboh** [comment]
rebased and retested, `orca-slicer` starts ok, slices, and I've been able to upload a print  from the slicer to my printer, changing settings is as well ok

**Review by Wulfsta — APPROVED** [review]

**Comment by Wulfsta** [comment]
Built `orca-slicer` and sliced some models, everything seems to work.

@jonboh for future reference, please do not create pull requests to git repositories from your master branch. Doing so makes simple commands like `git fetch upstream pull/352156/head:master` unavailable, since it wants to write into the `master` branch, which already exists.

**Comment by Theaninova** [comment]
Runs fine for me, tested using this overlay
```nix
(orca-slicer.overrideAttrs (
  final: prev: {
    version = "2.2.0";
    src = fetchFromGitHub {
      owner = "SoftFever";
      repo = "OrcaSlicer";
      rev = "v${final.version}";
      hash = "sha256-h+cHWhrp894KEbb3ic2N4fNTn13WlOSYoMsaof0RvRI=";
    };
    patches = builtins.filter (
      p:
      (builtins.baseNameOf p) != "0002-fix-build-for-gcc-13.diff"
      && (builtins.baseNameOf p) != "meshboolean-const.patch"
    ) prev.patches;
  }
))
```

**Pull request merged**
