### PR TITLE
clang-analyzer: use current LLVM version

### LINKED ISSUE #349404: clang-analyzer’s scan-view: ModuleNotFoundError: No module named 'imp'
### Describe the bug
```none
Traceback (most recent call last):
  File "/nix/store/sff9aqyzw1frvs3559ywdlrn9kkmzlh4-clang-analyzer-14.0.6/bin/scan-view", line 9, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```

### Steps To Reproduce
1. `nix shell nixpkgs#clang-analyzer`
2. `scan-view`

### Expected behavior
Whatever scan-view would normally do

### Notify maintainers

@thoughtpolice

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.2, NixOS, 24.11 (Vicuna), 24.11.20241009.5633bcf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/60sn02zhawl3kwn0r515zff3h6hg6ydz-source`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by jackwilsdon**
Fixes #349404 by updating `clang-analyzer` to the latest version of LLVM (which has https://github.com/llvm/llvm-project/commit/1be4db73642fa0658d3b1e1dad7ec95259d1d261).

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by jackwilsdon** [comment]
Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>clang-analyzer</li>
  </ul>
</details>

**Comment by emilazy** [comment]
Is there a reason to use LLVM 17 specifically here? The current default on most platforms is 18 and we have 19.

**Comment by jackwilsdon** [comment]
Oops! I thought it was the latest for some reason. I've updated it to just use `llvmPackages` now, as it seems to work fine with that (and means it should stay up to date).

**Comment by emilazy** [comment]
Looks like you’ve accidentally reformatted the entire `all-packages.nix` file.

**Comment by jackwilsdon** [comment]
:facepalm: fixed, sorry!

**Comment by emilazy** [comment]
I’m actually wondering why we have this package. Our main `clang` package ships `scan-build`, though we do patch it additionally in this derivation to respect `NIX_CFLAGS_COMPILE`. Does the `scan-build` in `clang` work? Maybe we should just move the patch into there instead if it’s necessary. cc @Mic92 who added the patch

**Comment by Mic92** [comment]
@emilazy historically we had all clang tools in the clang-tools package. At some point clang started to have them as well in their own package but unwrapped. I think we should move the wrapper all to the clang package because we sometimes end up with the unwrapped version in devshells if both packages are included.

**Comment by Mic92** [comment]
However this might cause a mass-rebuild, so maybe we want to merge this pull request before.

**Comment by emilazy** [comment]
Thanks for the context. I agree on the correct direction forward and that it seems fine to merge this until that is achieved.

**Pull request merged**
