### PR TITLE
Add vim plugins

### PR DESCRIPTION
**Pull request by matthiasbeyer**
###### Motivation for this change

Some vim plugins I had in my configuration.nix, but never put into nixpkgs.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bjornfor** [comment]
@matthiasbeyer: I noticed that none of these plugins have a version number (date). Also, it seems that most plugins these days are simply listed in pkgs/misc/vim-plugins/vim-plugin-names and then autogenerated from that. See comment in top of pkgs/misc/vim-plugins/default.nix. Perhaps use this workflow?

**Comment by jagajaga** [comment]
Please properly generate plugins with vim2nix and add also them to a list for autogeneration.

**Comment by matthiasbeyer** [comment]
In the process of doing this right now...

**Comment by matthiasbeyer** [comment]
This takes ridiculous long, I don't care enough.

**Pull request closed without merging**
