### PR TITLE
datadog-agent: update go packages and sub-packages

### PR DESCRIPTION
**Pull request by Izorkin**
###### Motivation for this change
Update go packages and sub-packages.
Datadog-trace-agent moved to datadog-agent - https://github.com/DataDog/datadog-trace-agent/blob/moved/README.md
Update datadog-process-agent to version 6.10.0

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Izorkin** [comment]
cc @kalbasit @rvl

**Comment by kalbasit** [comment]
I'm not able to build this PR.

```console
 λ  nix-shell -p nix-review --run 'nix-review pr 56567'
these paths will be fetched (0.02 MiB download, 0.09 MiB unpacked):
  /nix/store/4g4vr4154qn7dv4l03hxjjbiv83xn5cm-nix-review-1.0.1
copying path '/nix/store/4g4vr4154qn7dv4l03hxjjbiv83xn5cm-nix-review-1.0.1' from 'https://cache.nixos.org'...
$ git fetch --force https://github.com/NixOS/nixpkgs master:refs/nix-review/0 pull/56567/head:refs/nix-review/1
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Total 35 (delta 31), reused 31 (delta 31), pack-reused 4
Unpacking objects: 100% (35/35), done.
From https://github.com/NixOS/nixpkgs
   ab9c2c11483..81bf897e294  master               -> refs/nix-review/0
 + 2d178c80d65...ce2ef06c353 refs/pull/56567/head -> refs/nix-review/1  (forced update)
$ git worktree add /yl/.cache/nix-review/pr-56567/nixpkgs 81bf897e294a27b59b73f6a76942b1405923e99e
Preparing worktree (detached HEAD 81bf897e294)
HEAD is now at 81bf897e294 python.pkgs.filetype: 1.0.4 -> 1.0.5
$ git merge --no-commit ce2ef06c353ae6aeca843c0da9f9fe363c1b2bd7
Auto-merging pkgs/top-level/all-packages.nix
Removing pkgs/tools/networking/dd-agent/datadog-trace-agent.nix
Removing pkgs/tools/networking/dd-agent/datadog-trace-agent-deps.nix
Automatic merge went well; stopped before committing as requested
$ nix build --no-link --keep-going --max-jobs 12 --option build-use-sandbox true -f /yl/.cache/nix-review/pr-56567/build.nix
cannot build on 'ssh://builder@zeus.home.nasreddine.com': cannot connect to 'builder@zeus.home.nasreddine.com': ssh: Could not resolve hostname zeus.home.nasreddine.com: Name or service not known
builder for '/nix/store/1c4g69ylvqf09axw7bmr00fdcl34wz02-python2.7-pg8000-1.13.1.drv' failed with exit code 1; last 10 log lines:
  adding 'pg8000-1.13.1.dist-info/METADATA'
  adding 'pg8000-1.13.1.dist-info/WHEEL'
  adding 'pg8000-1.13.1.dist-info/top_level.txt'
  adding 'pg8000-1.13.1.dist-info/RECORD'
  removing build/bdist.linux-x86_64/wheel
  installing
  /build/pg8000-1.13.1/dist /build/pg8000-1.13.1
  DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
  Processing ./pg8000-1.13.1-py2-none-any.whl
  pg8000 requires Python '>=3.5' but the running Python is 2.7.15
cannot build derivation '/nix/store/abm5xrdpc8zb6pl0n95g5600xfnc88vk-python2.7-datadog-integration-postgres-git-2018-09-18.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/s2ww4k354qq5i6czpw51fb2mkjdf028g-python-2.7.15-env.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/48gvv1gcdfpk9k5vimjpfrpiypdr2kjl-datadog-agent-6.10.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/x40gz316np53s19j7hd2iyramnr2d5wz-env.drv': 1 dependencies couldn't be built
[44 built (1 failed), 230 copied (972.9 MiB), 222.5 MiB DL]
error: build of '/nix/store/x40gz316np53s19j7hd2iyramnr2d5wz-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/56567
1 package failed to build:
datadog-agent

1 package were build:
datadog-process-agent
```

**Comment by kalbasit** [comment]
@GrahamcOfBorg build datadog-agent datadog-process-agent

**Comment by Izorkin** [comment]
In rev c60d946fa30f04c6a9795d2a9d040f02253ad847 normal build

**Comment by Izorkin** [comment]
cc @FRidh 
Datadog error build with latest updates. Error build package python2.7-pg8000-1.13.1. Need version 1.12.5

**Comment by kalbasit** [comment]
@Izorkin it's recommended to fix the issue rather than a downgrade of a package.

**Comment by kalbasit** [comment]
@GrahamcOfBorg build datadog-agent datadog-process-agent

**Comment by Izorkin** [comment]
Thanks!

**Pull request merged**
