### PR TITLE
GNUstep packages for NixOS

### PR DESCRIPTION
**Pull request by ashalkhakov**
I would like NixOS to support repeatable builds for GNUstep, since obtaining up-to-date GS on Debian/Ubuntu is quite a bit of pain.

Currently, Gorm and ProjectCenter applications compile and mostly work (but only if environment is set up properly), and I'm figuring out the way forward from here.

I'll keep updating this PR as I move along.

For now, I'd like to create some build support for building GS-based applications. The issue is that GS by default (a) hard-codes some vital paths, and (b) tries to write to locations in the gnustep-make package (as a consequence of (a)). I think that it should be possible to generate a gnustep conf file containing all the necessary paths and then sourcing GNUstep.sh prior to building, which should simplify things considerably.

Also note that I haven't tested if it will work under Darwin, yet (despite what the platforms metadata will tell).

### CODE REVIEW

**Comment by lethalman** [comment]
When adding new commits, we don't get notified. Please tell us if you want further review or not.

**Comment by ashalkhakov** [comment]
@lethalman: I remember that. Sorry for the confusion; there isn't much to review (yet). Although, you might want to take a look at the .nix expressions.

I've introduced some Nix-specific environment variables and a runtime wrapper. GWorkspace doesn't work (raises an exception, probably has to do with the gdomap/gdnc daemons), and there are still some issues with Gorm and ProjectCenter (e.g. it will always fail to find gdb and gmake, looking for /usr/bin/gdb and /usr/bin/gmake, both requiring a patch).

How to deal with the following situation? Gorm is not required to build ProjectCenter, but ProjectCenter will invoke Gorm at runtime if it is present. Does it mean that Nix will have to re-wrap the existing ProjectCenter binary to include Gorm into the runtime environment when Gorm is installed?

**Comment by lethalman** [comment]
Does it run just a gorm executable, or needs some lib etc.? If it's just an executable, then forget about gorm in project center. The user will eventually install gorm and will be IN PATH for projectcenter.

**Comment by ashalkhakov** [comment]
I suppose it does something more complicated. Having Gorm in PATH is not
sufficient. I'll take a look at this issue after tackling NSNotifications
not working.

2015-01-30 16:57 GMT+06:00 lethalman <notifications@github.com>:

> Does it run just a gorm executable, or needs some lib etc.? If it's just
> an executable, then forget about gorm in project center. The user will
> eventually install gorm and will be IN PATH for projectcenter.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/pull/5197#issuecomment-72184924>.
>



-- 
Cheers,
Artyom Shalkhakov

**Comment by ashalkhakov** [comment]
I think I've tracked down the following issue. GWorkspace, when run, fails with "Problem posting notification", with the reason being: NSURL initFileURLWithPath nil string parameter.

This is due to the call [ws fullPathForApplication: wsname] yielding nil (GWorkspace/Dock/Dock.m:132), where wsname = @".GWorkspace-wrapped". Had wsname been @"GWorkspace", things would go as expected. So, I started thinking about alternatives to makeWrapper.

I've introduced NIX_GNUSTEP_* variables, and the runtime wrapper will only export GNUSTEP_CONFIG_FILE, containing definitions of these variables.

Is it possible to have NixOS maintain NIX_GNUSTEP_* environment variables automatically? Say a user installs gworkspace, then their NIX_GNUSTEP_SYSTEM_APPS points to ~/.nix-profile/bin. If no GNUstep package is installed, then the NIX_GNUSTEP_SYSTEM_APPS is null (not set). Likewise, if gworkspace is installed system-wide, then NIX_GNUSTEP_SYSTEM_APPS points to a directory under the system-wide profile. Obviously this is only a rough idea.

An alternative would be setting these variables manually (e.g. in extraCmds of myEnvFun). Which approach would you recommend, @lethalman?

**Comment by lethalman** [comment]
@ashalkhakov if you do that, there's no reason to use nix at all. How would it work e.g. in nix-shell? How would you test two gnustep at once?

**Comment by jagajaga** [comment]
@ashalkhakov @lethalman any further ideas and progress about this PR?

**Comment by ashalkhakov** [comment]
Sorry for the delay.

I took a look at my notes. Things that should mostly work:

* packaging software that depends on gnustep-make to build (one issue to deal with is the hard-coding of paths to various sensitive locations in GNUstep; to overcome this, I've patched gnustep-make such that it includes all .make files from all directories that are specified in the NIX_GNUSTEP_MAKEFILES_ADDITIONAL environment variable, instead of including $GNUSTEP_MAKEFILES/share/GNUstep/Makefiles/Additional/*.make, as it is usually done on other systems)
* gdomap daemon starts as root
* actual GNUstep applications have to be started via a wrapper script 
* gdnc, gpbs should start

What doesn't work:
* none of the major apps work (e.g. GWorkspace doesn't work)

GNUstep applications are written with the assumption that the state of the system is not fixed during compilation; e.g. GWorkspace IIRC depends on some other packages being installed as plugins to its own directories. I have no idea how to support this in NixOS.

**Comment by matthewbauer** [comment]
ping @ashalkhakov 

Are you still working on this? I've got a mergeable branch based off of this: matthewbauer/nixpkgs#1

**Comment by ashalkhakov** [comment]
@matthewbauer: that's great! Please by all means, continue the work. I don't have the time to carry on, unfortunately.

**Comment by joachifm** [comment]
Closing in favour of https://github.com/NixOS/nixpkgs/pull/16762

**Pull request closed without merging**
