### PR TITLE
nixos/gitlab: Package gitlab-rails

### PR DESCRIPTION
**Pull request by bgamari**
###### Motivation for this change

This utility (particularly `gitlab-rails console`) is packaged by GitLab
Omnibus and is used for diagnostics and maintenance operations.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by flokli** [comment]
@GrahamcOfBorg test gitlab

**Comment by flokli** [comment]
`gitlab-rails` got lost somewhere - see GrahamcOfBorg's output:

https://logs.nix.ci/?attempt_id=b4003a27-669d-4271-b7ca-892f07abfc11&key=nixos%2Fnixpkgs.58284

**Review by flokli — CHANGES_REQUESTED** [review]
gitlab-rails isn't defined anywhere.

**Comment by flokli** [comment]
I recovered the missing derivation from https://github.com/NixOS/nixpkgs/commit/401eb52a9dc850dd1ccb47953b4a800f143ffc54, added it to the commit and rebased. LMK if that looks good to you.

**Review by flokli — APPROVED** [review]

**Comment by bgamari** [comment]
I just pushed a fixed commit. Thanks @flokli!

**Comment by flokli** [comment]
backported to 19.03 in 34aeed1ca00.

**Pull request merged**
