### PR TITLE
Cypress 3.4.1: Fix files used for verification.

### PR DESCRIPTION
**Pull request by gomain**
###### Motivation for this change
Cypress 3.4.1 fails to run giving verification errors.
To reproduce:

  1. Install cypress from `nixpkgs` --> gets version 3.4.1
  2. In project package directory, install cypress with `CYPRESS_INSTALL_BINARY=0 npm install cypress@3.4.1`
  3. run ``CYPRESS_RUN_BINARY=`which Cypress` $(npm bin)/cypress open``
  
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by mmahut** [comment]
@GrahamcOfBorg build cypress

**Comment by bbigras** [comment]
This seems to work fine :+1: . Can you update to 3.5.0?

**Review by bbigras — APPROVED** [review]
It builds and runs fine :+1: thanks

**Comment by mmahut** [comment]
@GrahamcOfBorg build cypress

**Comment by bbigras** [comment]
Thank you very much for your time. :+1:

**Pull request merged**
