### PR TITLE
python3Packages.typer: 0.3.2 -> 0.4.0

### LINKED ISSUE #129479: python3Packages.typer does not support click v8
**Describe the bug**
typer is incompatible with click 8: https://github.com/tiangolo/typer/issues/280

**Steps to reproduce**
```
$ nix-shell -p python3Packages.typer
...
ERROR: Could not find a version that satisfies the requirement click<7.2.0,>=7.1.1 (from typer)
ERROR: No matching distribution found for click<7.2.0,>=7.1.1
builder for '/nix/store/lzz3rbni4xfpksmqlk8filkkch5z2gaw-python3.8-typer-0.3.2.drv' failed with exit code 1
```

**Notify maintainers**
@winpat 

**Metadata**
```yaml
 - system: `"x86_64-linux"`
 - host os: `Linux 3.10.0-1160.25.1.el7.x86_64, Red Hat Enterprise Linux Server, 7.9 (Maipo)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixpkgs-21.11pre300649.3e0ce8c5d47"`
 - nixpkgs: `/root/.nix-defexpr/channels/nixpkgs`
```
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pythonPackages.typer
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 0.4.0

Change log: https://github.com/tiangolo/typer/releases/tag/0.4.0

Fixes #129479

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by jtojnar — APPROVED** [review]

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 136159` at 3c190ee2 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>python38Packages.spacy</li>
    <li>python38Packages.spacy-transformers</li>
    <li>python38Packages.textacy</li>
    <li>python39Packages.spacy</li>
    <li>python39Packages.spacy-transformers</li>
    <li>python39Packages.textacy</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/1e63936b3dc1bd2c15a829aaa7c0acc6">markdown-anki-decks</a></li>
  </ul>
</details>
<details>
  <summary>1 package skipped due to time constraints:</summary>
  <ul>
    <li>python39Packages.teslajsonpy</li>
  </ul>
</details>
<details>
  <summary>7 packages built successfully:</summary>
  <ul>
    <li>python38Packages.authcaptureproxy</li>
    <li>python38Packages.pathy</li>
    <li>python38Packages.teslajsonpy</li>
    <li>python38Packages.typer</li>
    <li>python39Packages.authcaptureproxy</li>
    <li>python39Packages.pathy</li>
    <li>python39Packages.typer</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by davidak** [comment]
this breaks `markdown-anki-decks`

```
builder for '/nix/store/0ak8p8d201w2k4ikib0wnp324712z4a4-markdown-anki-decks-1.0.0.drv' failed with exit code 1; last 10 log lines:
  Removed build tracker: '/build/pip-req-tracker-57kxxp3r'
  Finished creating a wheel...
  Finished executing pipBuildPhase
  installing
  Executing pipInstallPhase
  /build/markdown-anki-decks-1.0.0/dist /build/markdown-anki-decks-1.0.0
  Processing ./markdown_anki_decks-1.0.0-py3-none-any.whl
  Requirement already satisfied: python-frontmatter<2.0.0,>=1.0.0 in /nix/store/a4ah5a9r9z58y77rzd41aclqfdfqqg8v-python3.9-python-frontmatter-1.0.0/lib/python3.9/site-packages (from markdown-anki-decks==1.0.0) (1.0.0)
  ERROR: Could not find a version that satisfies the requirement typer<0.4.0,>=0.3.2 (from markdown-anki-decks) (from versions: none)
  ERROR: No matching distribution found for typer<0.4.0,>=0.3.2
```

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 136159` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages failed to build:</summary>
  <ul>
    <li>markdown-anki-decks</li>
    <li>python38Packages.spacy</li>
    <li>python38Packages.spacy-transformers</li>
    <li>python38Packages.textacy</li>
    <li>python39Packages.spacy</li>
    <li>python39Packages.spacy-transformers</li>
    <li>python39Packages.textacy</li>
  </ul>
</details>
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>python38Packages.authcaptureproxy</li>
    <li>python38Packages.pathy</li>
    <li>python38Packages.teslajsonpy</li>
    <li>python38Packages.typer</li>
    <li>python39Packages.authcaptureproxy</li>
    <li>python39Packages.pathy</li>
    <li>python39Packages.teslajsonpy</li>
    <li>python39Packages.typer</li>
  </ul>
</details>

**Review by davidak — APPROVED** [review]
Changes look good

Builds

some packages fail to builds, but it did not work at all before, so this state is an improvement

**Pull request merged**
