### PR TITLE
bash-completion: 2.9 -> 2.10

### PR DESCRIPTION
**Pull request by sugar700**
###### Motivation for this change

Getting pytest 5.4 to work step-by-step.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)

  ```
  /nix/store/armxwrdc3q6sxiy1by5jaiq47snl54na-bash-completion-2.9      988616
  /nix/store/lprn1plgvxkzzvmmv1yvic8q433ah0dl-bash-completion-2.10    1001576
   ```

- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Also, I tested whether this works with `unset BASH_COMPLETION_VERSINFO; . result/etc/profile.d/bash_completion.sh` in nix-shell. I'm pretty sure I could have done it in a smarter way, but at the very least, it has shown that unzip supports files with `aab` extension which was introduced in 2.10 (see https://github.com/scop/bash-completion/blob/master/CHANGES).

### CODE REVIEW

**Comment by xfix** [comment]
Seems like gcc completions assume x86 CPU.

**Comment by xfix** [comment]
@GrahamcOfBorg build bash-completion

**Comment by xfix** [comment]
Chances are this is broken on macOS, can somebody run this on Darwin?

**Comment by jtojnar** [comment]
@GrahamcOfBorg build bash-completion

**Comment by xfix** [comment]
stdenv for darwin on staging is broken, okay then...

Rebased newest staging, but I'm not sure if it's going to help with anything. Oh well, if Darwin is broken, it likely doesn't block this package update.

**Comment by jtojnar** [comment]
@GrahamcOfBorg build bash-completion

**Comment by jtojnar** [comment]
Thanks. Also pushed GNOME Shell fix, which would have been broken by this.

**Pull request merged**
