### PR TITLE
malcontent: 0.4.0 → 0.6.0

### PR DESCRIPTION
**Pull request by jtojnar**
At the moment fails due to cyclic dependency https://gitlab.freedesktop.org/pwithnall/malcontent/issues/16

###### Motivation for this change
* https://gitlab.freedesktop.org/pwithnall/malcontent/-/tags/0.5.0
* https://gitlab.freedesktop.org/pwithnall/malcontent/-/tags/0.6.0

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by worldofpeace** [comment]
> At the moment fails due to cyclic dependency https://gitlab.freedesktop.org/pwithnall/malcontent/issues/16

Aww that sucks. I guess the only solution for that, as you mentioned there, is to split the projects up.

**Comment by worldofpeace** [comment]
It seems @hedning just dropped it from flatpak https://github.com/hedning/nixpkgs/commit/cdf3594507a66aad27e8831e7ae45a24218bd53c.

Also heads up @hedning, @jtojnar has already done the bump to 0.6.0 here https://github.com/hedning/nixpkgs/commit/60a3fbcaa14b54995909bf23e0a6722e4dfb8305.

**Comment by hedning** [comment]
Yeah, I didn't want to mess around too much. Checked fedora which doesn't enable the malcontent option in flatpak either.

**Comment by jtojnar** [comment]
Let’s just remove it from flatpak for now. Having the module is more convenient for me for testing.

**Pull request merged**
