### PR TITLE
k3s: 1.20.4+k3s1 -> 1.20.5+k3s1

### PR DESCRIPTION
**Pull request by superherointj**
k3s: 1.20.4+k3s1 -> [1.20.5+k3s1](https://github.com/k3s-io/k3s/releases/tag/v1.20.5%2Bk3s1)

Tested on aarch64.

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 118822` at 296458ae run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>k3s</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

makeWrapper is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/applications/networking/cluster/k3s/default.nix:251:3:
```
    |
251 |   buildInputs = [
    |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

util-linux is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/applications/networking/cluster/k3s/default.nix:251:3:
```
    |
251 |   buildInputs = [
    |   ^
```
</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Can you add the suggestion from the bot?

**Comment by superherointj** [comment]
> Can you add the suggestion from the bot?

* Moved 'makeWrapper' from buildInputs to nativeBuildInputs. [Ok]
* Won't move 'util-linux' because it seems to be runtime dependency of kubelet. As I don't understand the internals of this I'd prefer leaving it as it is. How can the bot be notified of this?

**Review by bachp — APPROVED** [review]

**Review by euank — APPROVED** [review]
Thanks :+1:

**Pull request merged**
