### PR TITLE
Tor-browser: 9.5 -> 9.5.3

### PR DESCRIPTION
**Pull request by ravenjoad**
###### Motivation for this change
https://blog.torproject.org/new-release-tor-browser-951

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TethysSvensson** [comment]
I've tested this on my machine it works well enough to browser youtube with audio.

Note that this fixes the current master, as version 9.5 has been yanked from their website.

**Comment by TethysSvensson** [comment]
@KarlJoad Since 9.5.3 is already out, perhaps you could update the PR to use that instead?

**Comment by KarlJoad** [comment]
9.5.3 came out just today. Will update the pull request soon.

**Comment by TethysSvensson** [comment]
I've just tested 9.5.3 as well. It seems to work too.

**Review by jonringer — COMMENTED** [review]
do you mind squashing the the bump into the previous bump?

```
git rebase -i HEAD^
# switch lines if commits out of order
# change second commit from `pick` to `squash`
# save and exit
```

**Comment by KarlJoad** [comment]
> 
> 
> do you mind squashing the the bump into the previous bump?
> 
> ```
> git rebase -i HEAD^
> # switch lines if commits out of order
> # change second commit from `pick` to `squash`
> # save and exit
> ```

This should do the trick.

**Review by jonringer — APPROVED** [review]
diff LGTM
gui launches fine

```
https://github.com/NixOS/nixpkgs/pull/94019
1 package built:
torbrowser
```

**Comment by jonringer** [comment]
32bit version builds as well

**Pull request merged**
