### PR TITLE
shadowsocks-rust: enable more optional features

### PR DESCRIPTION
**Pull request by NickCao**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by azuwis** [comment]
@NickCao I believe this commit brakes optional features.

After:

```
$ nix path-info github:nixos/nixpkgs/794d06eca234ba2c1a75e37b8f9c11d7cf9e100b#shadowsocks-rust
/nix/store/s7ih29d44fn9ihhybvc9vyqdjysl3qjm-shadowsocks-rust-1.15.2
$ sudo /nix/store/s7ih29d44fn9ihhybvc9vyqdjysl3qjm-shadowsocks-rust-1.15.2/bin/sslocal -c /etc/shadowsocks/config.json
loading config "/etc/shadowsocks/config.json", `protocol` invalid, unrecognized protocol tun
```

Before:

```
~/src/nixpkgs $ git rev-parse 794d06eca234ba2c1a75e37b8f9c11d7cf9e100b~                                     
55df49ae73c3144350f131c1f3c86b61c4b5c881
$ nix path-info github:nixos/nixpkgs/55df49ae73c3144350f131c1f3c86b61c4b5c881#shadowsocks-rust
/nix/store/r1j9p3s01aqw8l3hsb5n5mfjgxiv1fas-shadowsocks-rust-1.15.2
$ sudo /nix/store/r1j9p3s01aqw8l3hsb5n5mfjgxiv1fas-shadowsocks-rust-1.15.2/bin/sslocal -c /etc/shadowsocks/config.json
2023-02-20T10:22:18.342192+08:00 INFO  shadowsocks local 1.15.2 build 2023-01-29T18:55:04.569495+00:00
2023-02-20T10:22:18.343002+08:00 INFO  shadowsocks tun device utun99, mode tcp_only
```

**Comment by azuwis** [comment]
shadowsocks-rust is the only package that use `cargoBuildFeatures`, maybe this flag is not fully tested.

**Comment by NickCao** [comment]
Turns out I should have used `buildFeatures` not `cargoBuildFeatures`, https://github.com/NixOS/nixpkgs/blob/1f8ac70db85189f2e58bc93259ab06b703d393ea/pkgs/build-support/rust/build-rust-package/default.nix#L115

**Comment by NickCao** [comment]
Fixing in https://github.com/NixOS/nixpkgs/pull/217267

**Pull request merged**
