### PR TITLE
Correct derivation of pthreads on mingw64

### PR DESCRIPTION
**Pull request by bnikolic**
The C compiler is needed -- copy and paste error from the headers
derivation?

###### Motivation for this change

Mingw64-pthreads fails to configure currently as it can not find the C compiler. This correct the defect.

###### Things done

https://hydra.nixos.org/eval/1423028

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bnikolic** [comment]
@Ericson2314

**Comment by Ericson2314** [comment]
@bnikolic Thanks! Can you add this to `pkgs/top-level/release-cross.nix`?

**Comment by bnikolic** [comment]
@Ericson2314 Revised -- I haven't used release-cross before so please check

**Comment by Ericson2314** [comment]
Thanks! I'll get it tested.

**Comment by Ericson2314** [comment]
(For the record, the diff is just borked. @LnL7's pharo fix was merged separately.

**Pull request merged**
