### PR TITLE
nix-du: init at 0.1.1

### PR DESCRIPTION
**Pull request by symphorien**
###### Motivation for this change

package https://github.com/symphorien/nix-du

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build nix-du

**Comment by Mic92** [comment]
@grahamc do we have a sandbox again on macOS? `sandbox-exec: sandbox_apply_container: Operation not permitted` seems like it does.

**Comment by symphorien** [comment]
I might be because the test suite runs nix (on a local, temporary store). I think the error messages come from these nix invocations. Unfortunately I can't test on MacOS. Do you think adding the option `--option sandbox false` when running the tests would help ?
otherwise I will just set `doCheck` to false on darwin.

**Comment by Mic92** [comment]
It should help, if it runs nix in single-user mode.

**Comment by symphorien** [comment]
so I just pushed a patch to add `--option sandbox false`, can someone invoke @GrahamcOfBorg again ?

**Comment by Mic92** [comment]
@GrahamcOfBorg build nix-du

**Comment by symphorien** [comment]
Ok this just disables tests for now on darwin.

**Comment by symphorien** [comment]
Just if you are curious why it failed even when disabling the sandbox:
nix uses a minimal sandbox even if `--option sandbox false` is passed. To disable it
an environment variable is needed.
https://github.com/NixOS/nix/blob/master/src/libstore/build.cc#L2818

**Comment by Mic92** [comment]
Interesting. Too bad macOS does not allow to nest those.

**Pull request merged**
