### PR TITLE
pro-office-calculator: init at 1.0.6

### PR DESCRIPTION
**Pull request by pmiddend**
###### Motivation for this change

Seems to be an addicting game, and it's not in nixpkgs yet.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by symphorien** [comment]
When running it (on x86_64-linux) I get an illegal instruction:
```
Program received signal SIGILL, Illegal instruction.
0x00007ffff5b2f1c5 in ?? () from /nix/store/x3jacyl2lp46wcd6n9qyn07rhafnsp1q-gcc-7.3.0-lib/lib/libstdc++.so.6
(gdb) where
#0  0x00007ffff5b2f1c5 in ?? () from /nix/store/x3jacyl2lp46wcd6n9qyn07rhafnsp1q-gcc-7.3.0-lib/lib/libstdc++.so.6
#1  0x00007ffff5b2f332 in std::random_device::_M_getval() () from /nix/store/x3jacyl2lp46wcd6n9qyn07rhafnsp1q-gcc-7.3.0-lib/lib/libstdc++.so.6
#2  0x0000000000514c10 in randomSeed() ()
#3  0x00000000004219d6 in _GLOBAL__sub_I_game_logic.cpp ()
#4  0x00000000005427ad in __libc_csu_init ()
#5  0x00007ffff4f11b1d in __libc_start_main () from /nix/store/mrfcv8ipiksfdrx3xq7dvcrzgg2jdfsw-glibc-2.27/lib/libc.so.6
#6  0x0000000000423eaa in _start ()
```

**Comment by pmiddend** [comment]
@symphorien "Works for me", same architecture. What could be the difference between our machines?

**Comment by pmiddend** [comment]
Can anybody else test this on their machine?

**Comment by symphorien** [comment]
The illegal instruction is rdrand, and indeed my processor does not support it.
Given the backtrace, it seems this is not a bug in pro-office-calculator, but deeper in the dependency tree. Maybe the libstdc++ is built with rdrand support mandatory (this would surprise me, but...)
In any case it is probably not a blocker for your PR.

**Comment by symphorien** [comment]
In fact I think it is a bug in pro-office-calculator: https://github.com/RobJinman/pro_office_calc/issues/5

**Comment by pmiddend** [comment]
I'll try to incorporate the patch into the derivation.

**Comment by pmiddend** [comment]
@symphorien Ok, done. Can you test again?

**Comment by symphorien** [comment]
It works, thanks.

**Pull request merged**
