### PR TITLE
qtwebkit: Mark known vulnerable

### PR DESCRIPTION
**Pull request by mweinelt**
The browser engine is based off an old Webkit version, receives no security backports, does no releases.

The WebKitGTK people have counted over 500 CVEs they fixed since 2016.

Adding known vulnerable to make people aware they're using a browser engine that is not up to todays standards and could very likely be easily compromised.

https://blogs.gnome.org/mcatanzaro/2017/02/08/an-update-on-webkit-security-updates/
https://github.com/qutebrowser/qutebrowser/issues/4039#issue-338246939
https://blogs.gnome.org/mcatanzaro/2022/11/04/stop-using-qtwebkit/

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
76 packages affected:
- alkimia (†8.1.1)
 - alkimia (†8.1.1)
 - alkimia (†8.1.1)
 - apitrace (†7.1-572-g26966134)
 - apmplanner2 (†2.0.28)
 - brewtarget (†2.3.1)
 - calligra (†3.2.1)
 - cb2bib (†2.0.0)
 - fontmatrix (†0.6.0-qt5)
 - foxitreader (†2.4.4.0911)
 - goldendict (†2022-05-10)
 - kdev-php (†22.08.3)
 - kdev-php (†22.08.3)
 - kdev-php (†22.08.3)
 - kdev-php (†22.08.3)
 - kdev-python (†22.08.3)
 - kdev-python (†22.08.3)
 - kdev-python (†22.08.3)
 - kdev-python (†22.08.3)
 - kdevelop (†22.08.3)
 - kdevelop (†22.08.3)
 - kdevelop (†22.08.3)
 - kdevelop (†22.08.3)
 - kdevelop-with-plugins (†)
 - kdevelop-with-plugins (†)
 - kdevelop-with-plugins (†)
 - kdevelop-with-plugins (†)
 - kdewebkit (†5.99.0)
 - kdewebkit (†5.99.0)
 - kdewebkit (†5.99.0)
 - kexi (†3.2.0)
 - kmymoney (†5.1.3)
 - kreport (†3.2.0)
 - kreport (†3.2.0)
 - kreport (†3.2.0)
 - lsd2dsl (†0.5.4)
 - mendeley (†1.19.5-stable_amd64)
 - minizinc-ide (†2.5.5)
 - mythtv (†31.0)
 - nixnote2 (†2.0.2)
 - notepadqq (†1.4.8)
 - odoo (†15.0.20220506)
 - omedit (†1.18.0)
 - omshell (†1.18.0)
 - openboard (†1.6.1)
 - openlp (†2.4.6)
 - openlp-full (†2.4.6)
 - openmodelica-combined (†)
 - openshot-qt (†2.6.1)
 - pixinsight (†1.8.9-1)
 - python3.10-PyQt5 (†5.15.7)
 - python3.10-scudcloud (†1.65)
 - python3.9-PyQt5 (†5.15.7)
 - qgis (†3.22.10)
 - qgis (†3.26.2)
 - qlandkartegt (†1.8.1)
 - qt-full (†5.12.10)
 - qt-full (†5.14.2)
 - qt-full (†5.15.7)
 - qtwebkit (†5.212.0-alpha4)
 - qtwebkit (†5.212.0-alpha4)
 - qtwebkit (†5.212.0-alpha4)
 - qtwebkit-plugins-unstable (†2017-01-25)
 - qtwebkit-plugins-unstable (†2017-01-25)
 - qtwebkit-plugins-unstable (†2017-01-25)
 - quiterss (†0.19.4)
 - rocs (†22.08.3)
 - rocs (†22.08.3)
 - rocs (†22.08.3)
 - sleepyhead (†1.0.0-beta-git)
 - smtube (†21.10.0)
 - subsurface (†5.0.2)
 - swift-im (†4.0.2)
 - teamviewer (†15.29.4)
 - trojita-unstable (†2022-08-22)
 - wkhtmltopdf (†0.12.6)

**Comment by K900** [comment]
Our fork is somewhat more maintained, but still not particularly _well_ maintained, definitely not on the same level as Chromium or others. Also, just checking the list of things that depend on it, the only thing that jumps out at me is kdevelop, and that can use qtwebengine so should probably just be switched over (it currently depends on both for some reason).

**Comment by K900** [comment]
Also checked `rocs`, also builds just fine without it.

**Comment by K900** [comment]
`apitrace` is another thing I might care about but ours is disturbingly outdated anyway. I'll look into it.

**Comment by K900** [comment]
apitrace update here: https://github.com/NixOS/nixpkgs/pull/201032

**Comment by jian-lin** [comment]
FYI, this [fork](https://github.com/xiaoyifang/goldendict) of goldendict replaces qtwebkit with qtwebengine.

**Comment by mweinelt** [comment]
> FYI, this [fork](https://github.com/xiaoyifang/goldendict) of goldendict replaces qtwebkit with qtwebengine.

cc @gebner @astsmtl @sikmir

**Comment by ajs124** [comment]
Does this PR count towards progress for #53079?

**Comment by K900** [comment]
Well, it drops at least two packages, so I'd say yes.

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by gador** [comment]
`teamviewer` seems to be working fine without `qtwebkit` too

**Comment by mweinelt** [comment]
Feel free to provide a follow-up PR!

**Comment by vcunat** [comment]
Some of the [newly disappeared packages](https://hydra.nixos.org/eval/1785775#tabs-removed) still have `meta.maintainers`, so those might want to know:
- [ ] `apmplanner2`: @wucke13
- [ ] `brewtarget`: @mmahut
- [ ] `calligra`: @ebzzry, @zraexy
- [ ] `cb2bib`: @edwtjo
- [ ] `goldendict`: @gebner, @astsmtl, @sikmir
- [ ] `kmymoney`: @aidalgol, @das-g
- [ ] `libsForQt5.kdewebkit`: `@ttuegel` already requested, @nyanloutre
- [ ] `libsForQt5.kreport`: @zraexy
- [ ] `libsForQt5.qtwebkit` and `-plugins`: @abbradar, @periklis
- [ ] `lsd2dsl`: @sikmir
- [ ] `minizincide`: @dtzWill
- [ ] `mythtv`: @titanous
- [ ] `nixnote2`: @htr
- [ ] `notepadqq`: @rszibele
- [ ] `odoo`: @mkg20001
- [ ] `openboard`: @fufexan
- [ ] `openmodelica.*`: @balodja, @grwlf
- [ ] `openshot-qt`: @AndersonTorres
- [ ] `qgis` and `qgis-ltr`: @lsix, @sikmir, @erictapen, @willcohen
- [ ] `qlandkartegt`: @sikmir
- [ ] `quiterss`: @primeos
- [ ] `scudcloud`: @volhovm
- [ ] `sleepyhead`: @krav
- [ ] `smtube`: @vbgl
- [ ] `swift-im`: @orivej
- [ ] `trojita`: @ehmry
- [ ] `wkhtmltopdf`: @jb55

**Comment by vcunat** [comment]
Oh no... both graphical ISOs got also removed by this!

**Comment by K900** [comment]
Wait what why

**Comment by vcunat** [comment]
🤔  I see `qt-full-5.15.7` in the system-path derivation.

**Comment by vcunat** [comment]
```nix
    # Needed for calamares QML module packagechooserq
    libsForQt5.full
```

**Comment by K900** [comment]
That definitely doesn't look right. It should probably just be qtdeclarative.

**Comment by vcunat** [comment]
Perhaps calamares maintainers can help: @manveru, @vlinkz.  (also when I blamed the line)

**Comment by vlinkz** [comment]
Yeah without that some qml parts of calamares break, but should be possible to pinpoint exactly which packages are needed instead. I'll look into it

**Comment by aidalgol** [comment]
Looks like kmymoney is affected by this because it takes `kdewebkit` as an input.  What should it be using instead?  [Upstream's dependency list](https://invent.kde.org/office/kmymoney/-/wikis/Build-environment) does not specify any specific web engine, but [`CMakeLists.txt`](https://invent.kde.org/office/kmymoney/-/blob/e2c4fa770527708ed5525daffd0ac76ab94afb99/CMakeLists.txt#L113) tries to find `WebEngineWidgets` and `WebKitWidgets`.

**Comment by das-g** [comment]
PR to switch kmymoney from qtwebkit to qtwebengine: #201953

**Comment by AndersonTorres** [comment]
I believe `pyqt5_with_qtwebkit` is the one offending openshot.

**Comment by vlinkz** [comment]
PR for calamares installation cd: #201991

**Comment by vcunat** [comment]
Note that qtwebengine currently depends on long-vulnerable python2, so it would also get dropped "soon", e.g. by PR https://github.com/NixOS/nixpkgs/pull/201859

**Comment by K900** [comment]
Arch has patches for building it with Python3, maybe we should yoink those: https://github.com/archlinux/svntogit-packages/tree/packages/qt5-webengine/trunk

**Comment by AndersonTorres** [comment]
https://github.com/NixOS/nixpkgs/pull/202059

**Comment by mweinelt** [comment]
Thanks everyone for helping clean up!

**Comment by tobiasBora** [comment]
I'm beaten by this bug when I put `full`, but `qtbase` is not enough to build the package (errors about `UiTools`). Is there a `full`-like package that only contains packages that build?

**Comment by K900** [comment]
The package you want is `qttools` in `nativeBuildInputs`.

**Comment by tobiasBora** [comment]
Ahah thanks, I come up to the same conclusion using `nix-locate`, so I guess `full` should not be used anymore? Should'nt we provide a `full`-like for quick development? Also, what's the difference between qtbas of `qtdeclarative`?

**Comment by K900** [comment]
I'd say we should have never had a `full`-like. `qtbase` is QtCore and QtWidgets, `qtdeclarative` is, well, QtDeclarative.

**Pull request merged**
