### PR TITLE
libb2: 0.97 -> 0.98 and fix build on ARM

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
https://hydra.nixos.org/job/nixpkgs/trunk/libb2.aarch64-linux

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @dfoxfranke @dezgeg

### CODE REVIEW

**Comment by dfoxfranke** [comment]
LGTM.

**Comment by dotlambda** [comment]
@dezgeg Please merge if you don't have any objections as you were the one who added `--enable-fat`.

**Comment by dotlambda** [comment]
ping @dezgeg

**Comment by dezgeg** [comment]
Thank you!

**Pull request merged**
