### PR TITLE
nixos/systemd-userdbd: add option to enable

### PR DESCRIPTION
**Pull request by erincandescent**
###### Description of changes
This service is shipped as a part of upstream systemd but not currently
incldued in NixOS. This change adds a configuration option which may
be used to enable it

###### Things done
- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by erincandescent** [comment]
(My motivation for this is that I have [a PAM module](https://github.com/erincandescent/pam_sduserdb) which depends upon userdbd)

**Comment by arianvp** [comment]
Bit off topic but pam_systemd already supports systemd-userdb. Why a new
pam module?

**Comment by erincandescent** [comment]
`pam_systemd` is just a session module - it handles things like registering with logind

`pam_sduserdb` is an account module - it handles things like "is this account enabled?"

**Review by arianvp — APPROVED** [review]

**Comment by arianvp** [comment]
It would be nice if we can add a VM test that makes sure all the userdbd stuff works.  e.g. that we can query `/etc/shadow` through it etc.   Maybe just some calls to `userdbctl` to make sure everything is alright as a smoke test? This just makes sure that we don't accidentally break it with our systemd-specific patches.  Apart from that LGTM.

**Comment by erincandescent** [comment]
> Thanks gotcha. It seems the account module that systemd ships is systemd-home but that only deals with user records in the home folder; not generic user records. Bit surprising to me!

On other Linux systems this would be handled via `pam_unix -> getspent(3) -> nss_systemd` but shadow _can't_ go through `nscd` (unless you want to do all your DNS resolutions as root 😨)

**Comment by arianvp** [comment]
Bit tempted to ship `pam_sduserdb` in NixOS proper now and use NSCD just for DNS.  I think it would solve a lot of our issues we've had with nscd, dynamic users and service restarts...  (CC @flokli )

**Comment by erincandescent** [comment]
You still need nss_systemd (and hence nscd) for all apps which do traditional NSS based user lookups (getpwent, getpwnam, getpwuid, etc)

**Comment by arianvp** [comment]
@erincandescent would you want to add a simple VM test?

**Comment by flokli** [comment]
@erincandescent if you can't add a test, can you describe how to test this?

Including this in a VM test is important, so we spot potential regressions, and also see how this is supposed to work.

**Comment by erincandescent** [comment]
The `userdb` command isn't helpful here, because if it can't talk to `userdbd` it falls back on its own internal implementation of it.

So I think the best bet is to pull in `libvarlink` and do a direct call to the service. Something like checking the following succeeds:
```
varlink call unix:/run/systemd/userdb/io.systemd.Multiplexer/io.systemd.UserDatabase.GetUserRecord '{"uid":0, "service":"io.systemd.Multiplexer"}'
```

**Pull request closed without merging**
