### PR TITLE
libs: make splitString also split last separator

### PR DESCRIPTION
**Pull request by Ekleog**
This should fix https://github.com/NixOS/nixpkgs/issues/23681.

I have tested using nix-repl, not tested every file using it as hydra should be able to do it better than me.

Hope that helps!

### CODE REVIEW

**Review by zimbatm — COMMENTED** [review]
Even if technically it's a breaking change, it shouldn't happen most of the time and it makes the function more in line with any other language that I have used.

I would still live to see some tests added to the code before approving the change.

**Review by globin — APPROVED** [review]

**Comment by Ekleog** [comment]
@zimbatm : I've just pushed a commit filling in lib/tests.nix, is that what you meant? (checked it worked by using `nix-instantiate --eval --strict --show-trace lib/tests.nix`, found by git grep'ing for "tests.nix", it seems to work) Or is it more tests like the ones @vcunat exposed [here](https://github.com/NixOS/nixpkgs/issues/23681#issuecomment-285534808) that you're speaking about?

**Comment by zimbatm** [comment]
Yeah thanks for taking the time and figuring this out. I suppose we should have a better testing framework in place but that will do.

**Comment by vcunat** [comment]
All problems are probably fixed now.

**Comment by zimbatm** [comment]
you're the best @vcunat

**Comment by butterflya** [comment]
Why do we merge such a horrible implementation? (The first version was horrible too, of course, but this would have been a good occassion to fix it.)

Compare with how Haskell does it (which is better): http://hackage.haskell.org/package/split-0.1.2.3/docs/src/Data-List-Split-Internals.html#splitOn

**Comment by zimbatm** [comment]
@butterflya I'm not sure of what you're complaining about. Do you mean that you want to change the semantic so that `strings.splitString "." "a..b"` returns `["a" ".b"]`?

**Comment by butterflya** [comment]
@zimbatm No, the point I was trying to make is that the Haskell implementation is composed of other functions and is a one liner. The version in Nix is the complete opposite of that.

I don't think we should unmerge it again (for the sake of progress), but I am saying that there is *much* room for improvement.

**Comment by vcunat** [comment]
I think the (original) author had performance in mind.  Nix lists are monolithic arrays, unlike what functional languages typically provide.

**Comment by zimbatm** [comment]
@butterflya in that case the occasion is not lost, you can still propose the improvements in a separate PR. And thanks to the tests provided in this PR it will also make it easier to test for conformance.

**Pull request merged**
