### PR TITLE
tree-sitter: add many new grammars

### PR DESCRIPTION
**Pull request by Kranzes**
###### Motivation for this change
Added a lot of new grammars to tree-sitter, many are from the list over at https://github.com/nvim-treesitter/nvim-treesitter.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kranzes** [comment]
Result of `nixpkgs-review pr 151146` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>tree-sitter-grammars.tree-sitter-d</li>
    <li>tree-sitter-grammars.tree-sitter-teal</li>
  </ul>
</details>
<details>
  <summary>40 packages built:</summary>
  <ul>
    <li>difftastic</li>
    <li>tree-sitter-grammars.tree-sitter-bibtex</li>
    <li>tree-sitter-grammars.tree-sitter-cmake</li>
    <li>tree-sitter-grammars.tree-sitter-commonlisp</li>
    <li>tree-sitter-grammars.tree-sitter-cuda</li>
    <li>tree-sitter-grammars.tree-sitter-devicetree</li>
    <li>tree-sitter-grammars.tree-sitter-dockerfile</li>
    <li>tree-sitter-grammars.tree-sitter-elixir</li>
    <li>tree-sitter-grammars.tree-sitter-elm</li>
    <li>tree-sitter-grammars.tree-sitter-erlang</li>
    <li>tree-sitter-grammars.tree-sitter-fortran</li>
    <li>tree-sitter-grammars.tree-sitter-gdscript</li>
    <li>tree-sitter-grammars.tree-sitter-glimmer</li>
    <li>tree-sitter-grammars.tree-sitter-glsl</li>
    <li>tree-sitter-grammars.tree-sitter-godot-resource</li>
    <li>tree-sitter-grammars.tree-sitter-gomod</li>
    <li>tree-sitter-grammars.tree-sitter-graphql</li>
    <li>tree-sitter-grammars.tree-sitter-heex</li>
    <li>tree-sitter-grammars.tree-sitter-hjson</li>
    <li>tree-sitter-grammars.tree-sitter-http</li>
    <li>tree-sitter-grammars.tree-sitter-json5</li>
    <li>tree-sitter-grammars.tree-sitter-kotlin</li>
    <li>tree-sitter-grammars.tree-sitter-ledger</li>
    <li>tree-sitter-grammars.tree-sitter-llvm</li>
    <li>tree-sitter-grammars.tree-sitter-make</li>
    <li>tree-sitter-grammars.tree-sitter-perl</li>
    <li>tree-sitter-grammars.tree-sitter-pioasm</li>
    <li>tree-sitter-grammars.tree-sitter-prisma</li>
    <li>tree-sitter-grammars.tree-sitter-pug</li>
    <li>tree-sitter-grammars.tree-sitter-query</li>
    <li>tree-sitter-grammars.tree-sitter-r</li>
    <li>tree-sitter-grammars.tree-sitter-ruby</li>
    <li>tree-sitter-grammars.tree-sitter-scss</li>
    <li>tree-sitter-grammars.tree-sitter-sparql</li>
    <li>tree-sitter-grammars.tree-sitter-supercollider</li>
    <li>tree-sitter-grammars.tree-sitter-surface</li>
    <li>tree-sitter-grammars.tree-sitter-tlaplus</li>
    <li>tree-sitter-grammars.tree-sitter-turtle</li>
    <li>tree-sitter-grammars.tree-sitter-vue</li>
    <li>tree-sitter-grammars.tree-sitter-yang</li>
  </ul>
</details>

**Comment by Kranzes** [comment]
Result of `nixpkgs-review pr 151146` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>39 packages built:</summary>
  <ul>
    <li>difftastic</li>
    <li>tree-sitter-grammars.tree-sitter-bibtex</li>
    <li>tree-sitter-grammars.tree-sitter-cmake</li>
    <li>tree-sitter-grammars.tree-sitter-commonlisp</li>
    <li>tree-sitter-grammars.tree-sitter-cuda</li>
    <li>tree-sitter-grammars.tree-sitter-devicetree</li>
    <li>tree-sitter-grammars.tree-sitter-dockerfile</li>
    <li>tree-sitter-grammars.tree-sitter-elixir</li>
    <li>tree-sitter-grammars.tree-sitter-elm</li>
    <li>tree-sitter-grammars.tree-sitter-erlang</li>
    <li>tree-sitter-grammars.tree-sitter-fortran</li>
    <li>tree-sitter-grammars.tree-sitter-gdscript</li>
    <li>tree-sitter-grammars.tree-sitter-glimmer</li>
    <li>tree-sitter-grammars.tree-sitter-glsl</li>
    <li>tree-sitter-grammars.tree-sitter-godot-resource</li>
    <li>tree-sitter-grammars.tree-sitter-gomod</li>
    <li>tree-sitter-grammars.tree-sitter-graphql</li>
    <li>tree-sitter-grammars.tree-sitter-heex</li>
    <li>tree-sitter-grammars.tree-sitter-hjson</li>
    <li>tree-sitter-grammars.tree-sitter-http</li>
    <li>tree-sitter-grammars.tree-sitter-json5</li>
    <li>tree-sitter-grammars.tree-sitter-kotlin</li>
    <li>tree-sitter-grammars.tree-sitter-ledger</li>
    <li>tree-sitter-grammars.tree-sitter-llvm</li>
    <li>tree-sitter-grammars.tree-sitter-make</li>
    <li>tree-sitter-grammars.tree-sitter-perl</li>
    <li>tree-sitter-grammars.tree-sitter-pioasm</li>
    <li>tree-sitter-grammars.tree-sitter-prisma</li>
    <li>tree-sitter-grammars.tree-sitter-pug</li>
    <li>tree-sitter-grammars.tree-sitter-query</li>
    <li>tree-sitter-grammars.tree-sitter-r</li>
    <li>tree-sitter-grammars.tree-sitter-scss</li>
    <li>tree-sitter-grammars.tree-sitter-sparql</li>
    <li>tree-sitter-grammars.tree-sitter-supercollider</li>
    <li>tree-sitter-grammars.tree-sitter-surface</li>
    <li>tree-sitter-grammars.tree-sitter-tlaplus</li>
    <li>tree-sitter-grammars.tree-sitter-turtle</li>
    <li>tree-sitter-grammars.tree-sitter-vue</li>
    <li>tree-sitter-grammars.tree-sitter-yang</li>
  </ul>
</details>

**Comment by DieracDelta** [comment]
I've tested building all grammars from @Kranzes branch into neovim on aarch64-darwin. No errors, this runs fine. I didn't open treesitter on all possible languages but it seems to work.

**Review by fufexan — APPROVED** [review]

**Review by SuperSandro2000 — APPROVED** [review]
I am not sure what https://github.com/nvim-treesitter/tree-sitter-query is about.

**Comment by Profpatsch** [comment]
Thank you, pretty cool.

**Comment by leo60228** [comment]
> I am not sure what https://github.com/nvim-treesitter/tree-sitter-query is about.

@SuperSandro2000 It's for [tree-sitter query files](https://tree-sitter.github.io/tree-sitter/using-parsers#pattern-matching-with-queries) (used for defining syntax highlights). (found this PR because I didn't remember upstreaming a package for tree-sitter-pioasm...)

**Pull request merged**
