### PR TITLE
[20.09] zfs 0.8.5

### PR DESCRIPTION
**Pull request by srhb**
Backport of #99965 + unmark broken on 5.9

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by srhb** [comment]
@GrahamcOfBorg test zfs

**Comment by tbechthomassen** [comment]
Tested. Seems to work. My system boots, zfs reports no errors, all pools found and working.

**Comment by srhb** [comment]
Result of `nixpkgs-review pr 105238` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>bareos</li>
    <li>linuxPackages_hardkernel_4_14.zfs</li>
    <li>linuxPackages_hardkernel_4_14.zfsStable</li>
    <li>linuxPackages_hardkernel_latest.zfs</li>
    <li>linuxPackages_hardkernel_latest.zfsStable</li>
    <li>virt-manager-qt</li>
  </ul>
</details>
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>tests.nixos-functions.nixosTest-test</li>
  </ul>
</details>
<details>
  <summary>68 packages built:</summary>
  <ul>
    <li>ceph (ceph-dev)</li>
    <li>ceph-client</li>
    <li>collectd</li>
    <li>collectd-data</li>
    <li>docker-machine-kvm</li>
    <li>docker-machine-kvm2</li>
    <li>easysnap</li>
    <li>gnome3.gnome-boxes</li>
    <li>grub2 (grub2_full)</li>
    <li>grub2_efi</li>
    <li>grub2_pvgrub_image</li>
    <li>grub2_xen</li>
    <li>haskellPackages.libvirt-hs</li>
    <li>haskellPackages.libzfs</li>
    <li>libceph</li>
    <li>libguestfs</li>
    <li>libvirt</li>
    <li>libvirt-glib</li>
    <li>libvirt_5_9_0</li>
    <li>libvmi</li>
    <li>linuxPackages-libre.zfs (linuxPackages-libre.zfsStable)</li>
    <li>linuxPackages.zfs (linuxPackages.zfsStable ,linuxPackages_5_4.zfs ,linuxPackages_5_4.zfsStable)</li>
    <li>linuxPackages_4_14.zfs (linuxPackages_4_14.zfsStable)</li>
    <li>linuxPackages_4_19.zfs (linuxPackages_4_19.zfsStable)</li>
    <li>linuxPackages_4_4.zfs (linuxPackages_4_4.zfsStable)</li>
    <li>linuxPackages_4_9.zfs (linuxPackages_4_9.zfsStable)</li>
    <li>linuxPackages_5_8.zfs (linuxPackages_5_8.zfsStable)</li>
    <li>linuxPackages_5_9.zfs (linuxPackages_5_9.zfsStable ,linuxPackages_latest.zfs ,linuxPackages_latest.zfsStable)</li>
    <li>linuxPackages_hardened.zfs (linuxPackages_hardened.zfsStable)</li>
    <li>linuxPackages_latest-libre.zfs (linuxPackages_latest-libre.zfsStable)</li>
    <li>linuxPackages_latest_hardened.zfs (linuxPackages_latest_hardened.zfsStable)</li>
    <li>linuxPackages_latest_xen_dom0.zfs (linuxPackages_latest_xen_dom0.zfsStable)</li>
    <li>linuxPackages_latest_xen_dom0_hardened.zfs (linuxPackages_latest_xen_dom0_hardened.zfsStable)</li>
    <li>linuxPackages_testing_bcachefs.zfs (linuxPackages_testing_bcachefs.zfsStable)</li>
    <li>linuxPackages_xen_dom0.zfs (linuxPackages_xen_dom0.zfsStable)</li>
    <li>linuxPackages_xen_dom0_hardened.zfs (linuxPackages_xen_dom0_hardened.zfsStable)</li>
    <li>linuxPackages_zen.zfs (linuxPackages_zen.zfsStable)</li>
    <li>minikube</li>
    <li>minishift</li>
    <li>nixops</li>
    <li>nixopsUnstable</li>
    <li>nixops_1_6_1</li>
    <li>os-prober</li>
    <li>perl530Packages.SysVirt</li>
    <li>perl532Packages.SysVirt</li>
    <li>python27Packages.guestfs</li>
    <li>python27Packages.libvirt</li>
    <li>python37Packages.guestfs</li>
    <li>python37Packages.libvirt</li>
    <li>python38Packages.guestfs</li>
    <li>python38Packages.libvirt</li>
    <li>rubyPackages.ruby-libvirt (rubyPackages_2_6.ruby-libvirt)</li>
    <li>rubyPackages_2_5.ruby-libvirt</li>
    <li>rubyPackages_2_7.ruby-libvirt</li>
    <li>sambaFull (samba4Full)</li>
    <li>sanoid</li>
    <li>terraform-full</li>
    <li>terraform-providers.libvirt</li>
    <li>terraform_0_11-full</li>
    <li>terragrunt</li>
    <li>vagrant</li>
    <li>virt-manager</li>
    <li>virt-top</li>
    <li>virt-viewer</li>
    <li>virtlyst</li>
    <li>zfs (zfsStable)</li>
    <li>zfsUnstable</li>
    <li>zfstools</li>
  </ul>
</details>

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 105238 [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>6 packages marked as broken and skipped:</summary>  <ul>    <li>bareos</li>    <li>linuxPackages_hardkernel_4_14.zfs</li>    <li>linuxPackages_hardkernel_4_14.zfsStable</li>    <li>linuxPackages_hardkernel_latest.zfs</li>    <li>linuxPackages_hardkernel_latest.zfsStable</li>    <li>virt-manager-qt</li>  </ul></details><details>  <summary>1 package blacklisted:</summary>  <ul>    <li>tests.nixos-functions.nixosTest-test</li>  </ul></details><details>  <summary>68 packages built:</summary>  <ul>    <li>ceph (ceph-dev)</li>    <li>ceph-client</li>    <li>collectd</li>    <li>collectd-data</li>    <li>docker-machine-kvm</li>    <li>docker-machine-kvm2</li>    <li>easysnap</li>    <li>gnome3.gnome-boxes</li>    <li>grub2 (grub2_full)</li>    <li>grub2_efi</li>    <li>grub2_pvgrub_image</li>    <li>grub2_xen</li>    <li>haskellPackages.libvirt-hs</li>    <li>haskellPackages.libzfs</li>    <li>libceph</li>    <li>libguestfs</li>    <li>libvirt</li>    <li>libvirt-glib</li>    <li>libvirt_5_9_0</li>    <li>libvmi</li>    <li>linuxPackages-libre.zfs (linuxPackages-libre.zfsStable)</li>    <li>linuxPackages.zfs (linuxPackages.zfsStable ,linuxPackages_5_4.zfs ,linuxPackages_5_4.zfsStable)</li>    <li>linuxPackages_4_14.zfs (linuxPackages_4_14.zfsStable)</li>    <li>linuxPackages_4_19.zfs (linuxPackages_4_19.zfsStable)</li>    <li>linuxPackages_4_4.zfs (linuxPackages_4_4.zfsStable)</li>    <li>linuxPackages_4_9.zfs (linuxPackages_4_9.zfsStable)</li>    <li>linuxPackages_5_8.zfs (linuxPackages_5_8.zfsStable)</li>    <li>linuxPackages_5_9.zfs (linuxPackages_5_9.zfsStable ,linuxPackages_latest.zfs ,linuxPackages_latest.zfsStable)</li>    <li>linuxPackages_hardened.zfs (linuxPackages_hardened.zfsStable)</li>    <li>linuxPackages_latest-libre.zfs (linuxPackages_latest-libre.zfsStable)</li>    <li>linuxPackages_latest_hardened.zfs (linuxPackages_latest_hardened.zfsStable)</li>    <li>linuxPackages_latest_xen_dom0.zfs (linuxPackages_latest_xen_dom0.zfsStable)</li>    <li>linuxPackages_latest_xen_dom0_hardened.zfs (linuxPackages_latest_xen_dom0_hardened.zfsStable)</li>    <li>linuxPackages_testing_bcachefs.zfs (linuxPackages_testing_bcachefs.zfsStable)</li>    <li>linuxPackages_xen_dom0.zfs (linuxPackages_xen_dom0.zfsStable)</li>    <li>linuxPackages_xen_dom0_hardened.zfs (linuxPackages_xen_dom0_hardened.zfsStable)</li>    <li>linuxPackages_zen.zfs (linuxPackages_zen.zfsStable)</li>    <li>minikube</li>    <li>minishift</li>    <li>nixops</li>    <li>nixopsUnstable</li>    <li>nixops_1_6_1</li>    <li>os-prober</li>    <li>perl530Packages.SysVirt</li>    <li>perl532Packages.SysVirt</li>    <li>python27Packages.guestfs</li>    <li>python27Packages.libvirt</li>    <li>python37Packages.guestfs</li>    <li>python37Packages.libvirt</li>    <li>python38Packages.guestfs</li>    <li>python38Packages.libvirt</li>    <li>rubyPackages.ruby-libvirt (rubyPackages_2_6.ruby-libvirt)</li>    <li>rubyPackages_2_5.ruby-libvirt</li>    <li>rubyPackages_2_7.ruby-libvirt</li>    <li>sambaFull (samba4Full)</li>    <li>sanoid</li>    <li>terraform-full</li>    <li>terraform-providers.libvirt</li>    <li>terraform_0_11-full</li>    <li>terragrunt</li>    <li>vagrant</li>    <li>virt-manager</li>    <li>virt-top</li>    <li>virt-viewer</li>    <li>virtlyst</li>    <li>zfs (zfsStable)</li>    <li>zfsUnstable</li>    <li>zfstools</li>  </ul></details>

**Pull request merged**
