### PR TITLE
perl526: drop

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

End-of-life upstream (https://www.cpan.org/src/README.html)

### CODE REVIEW

**Comment by volth** [comment]
@GrahamcOfBorg build hydra

**Comment by volth** [comment]
@GrahamcOfBorg build hydra

**Comment by Mic92** [comment]
Do you mean this unit? https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/http/unit/default.nix#L35 perl could be just removed here right?

**Comment by volth** [comment]
Yes and https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/http/unit/default.nix#L55

or it could be surrounded with something like ```optionalString (pkgs?perl526) ...``` for 18.09 compatibility

**Comment by Mic92** [comment]
What is actually the motivation for staging, given that removing packages should not create rebuilds except for a few packages in theory?

**Comment by volth** [comment]
> What is actually the motivation for staging, given that removing packages 

1. switching from Nix packages to Perl build-ins might cause mass rebuild
2. possible merge conflicts with regular bot PRs like https://github.com/NixOS/nixpkgs/pull/51548

**Pull request merged**
