### PR TITLE
darwin.builder: prefer shutting down over halting VM

### PR DESCRIPTION
**Pull request by winterqt**
###### Description of changes

This is preferable because it prevents things like disk corruption (requiring the user to delete the disk image when starting up) that I consistently ran into.

Let me know if the commit structure/wording/etc should be changed (e.g. should I use `darwin.builder` instead of `doc/.../darwin-builder` in the last commit? Your initial commit just said `Add documentation`, and the last commit touching those docs just used `darwin.builder` *shrug*).

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Gabriella439** [comment]
Actually, I think there might be a simpler solution, which is to use the `system_powerdown` `qemu` command instead of `quit`.  It triggers a graceful shutdown, like this:

```
(qemu) system_powerdown
(qemu) [  OK  ] Removed slice Slice /system/modprobe.
[  OK  ] Removed slice Slice /user/1000.
[  OK  ] Stopped target Multi-User System.
…
[  OK  ] Reached target Late Shutdown Services.
[  OK  ] Finished System Power Off.
[  OK  ] Reached target System Power Off.
[  345.189964] reboot: Power down
```

**Comment by winterqt** [comment]
Ah, nice; I was looking to see if something like that existed, but couldn't find it.

Should I just reuse this PR to change the docs, or would you rather open a new one?

**Comment by Gabriella439** [comment]
https://github.com/NixOS/nixpkgs/pull/208524

**Comment by winterqt** [comment]
Would you be opposed to making both changes, so the user can shut it down from both the QEMU console and without that sort of intervention?

**Comment by Gabriella439** [comment]
Yes.  Maybe it would be easier if you extended your PR, then

**Comment by winterqt** [comment]
Amended the doc commit, PTAL.

> Let me know if the commit structure/wording/etc should be changed (e.g. should I use `darwin.builder` instead of `doc/.../darwin-builder` in the last commit? Your initial commit just said `Add documentation`, and the last commit touching those docs just used `darwin.builder` *shrug*).

**Review by Gabriella439 — APPROVED** [review]

**Pull request merged**
