### PR TITLE
stc-cli: init at 1.4

### PR DESCRIPTION
**Pull request by ivankovnatsky**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ivankovnatsky** [comment]
Result of `nixpkgs-review pr 224792` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>stc</li>
  </ul>
</details>

**Review by 06kellyjac — COMMENTED** [review]
I would strongly prefer this package be called syncthing-cli considering it's a decent name that fits the project still, and is in the tags.

There's already https://github.com/dudykr/stc which has many more stars
And the stc that is syncthing-cli is pretty dead having no changes in a year

This stc: https://github.com/dudykr/stc will likely be packaged once it's off the rust nightly releases

**Comment by ivankovnatsky** [comment]
> I would strongly prefer this package be called syncthing-cli considering it's a decent name that fits the project still, and is in the tags.
> 
> There's already https://github.com/dudykr/stc which has many more stars And the stc that is syncthing-cli is pretty dead having no changes in a year
> 
> This stc: https://github.com/dudykr/stc will likely be packaged once it's off the rust nightly releases

Do you think we should call the binary also `syncthing-cli` or just the package?

**Comment by Lassulus** [comment]
`syncthing-cli` is already aliased to `syncthing` in `pkgs/top-level/aliases.nix`

**Comment by ivankovnatsky** [comment]
Renamed to `stc-cli`. Probably not ideal, but we should definitely have room now.

**Comment by Lassulus** [comment]
hmm, I would prefer the original name `stc` over `stc-cli` because I suspect the c in stc stands for cli and now we would have 'SyncThing-cli-cli` ;)

**Comment by Lassulus** [comment]
Result of `nixpkgs-review pr 224792` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>stc-cli</li>
  </ul>
</details>

**Pull request merged**
