### PR TITLE
Revert "Unwrap python scripts when building an environment"

### LINKED ISSUE #301498: Build failure: pypy3
### Steps To Reproduce

1. build `pypy3`

### Build log

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/5n8ridrwkr7jwlm2i02z60y9w4lfvjrg-pypy3.9-v7.3.12-src.tar.bz2
source root is pypy3.9-v7.3.12-src
setting SOURCE_DATE_EPOCH to timestamp 1686821484 of file pypy3.9-v7.3.12-src/testrunner/test/test_scratchbox_runner.py
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
applying patch /nix/store/lgy8qxprnymy5frfsmgksjp823icbl0p-dont_fetch_vendored_deps.patch
patching file lib_pypy/pypy_tools/build_cffi_imports.py
Hunk #1 succeeded at 257 (offset 32 lines).
applying patch /nix/store/39xaxcfgaasiazb7vzrmkilp8g988alj-tk_tcl_paths.patch
patching file lib_pypy/_tkinter/tklib_build.py
Hunk #1 succeeded at 17 with fuzz 2.
applying patch /nix/store/vbrsc4clqvi0cdf0bznyknbzrsmwckax-sqlite_paths.patch
patching file lib_pypy/_sqlite3_build.py
Hunk #1 succeeded at 321 (offset 20 lines).
substituteStream(): WARNING: '--replace' is deprecated, use --replace-{fail,warn,quiet}. (file 'lib_pypy/pypy_tools/build_cffi_imports.py')
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
Updating Autotools / GNU config script to a newer upstream version: ./rpython/rlib/rvmprof/src/shared/libbacktrace/config.sub
Updating Autotools / GNU config script to a newer upstream version: ./pypy/tool/release/config.guess
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
debug: WARNING: Library path not found, using compiled-in sys.path, with
debug: WARNING: sys.prefix = '/build/pypy2.7-v7.3.12-src'
debug: WARNING: Make sure the pypy binary is kept inside its tree of files.
debug: WARNING: It is ok to create a symlink to it from somewhere else.
'import site' failed
debug: OperationError:
debug:  operror-type: ImportError
debug:  operror-value: No module named encodings
```

### Additional context

No extra python packages, overlays or anything were added. This build failure happens on both master and nixos-unstable.

### Notify maintainers
@andersk 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.2-zen2, NixOS, 24.05 (Uakari), 24.05.20240329.d8fe5e6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - channels(grimmauld): `""`
 - nixpkgs: `/nix/store/cb1gs888vfqxawvc65q1dk6jzbayh3wz-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by SuperSandro2000**
This reverts commit 96118850f323f41c163f1f5a8231128879fb2f2e from #297628

Closes #301498

## Description of changes

The sed does bad assumptions and breaks python scripts like pretalx-manager https://github.com/NixOS/nixpkgs/pull/302315 (https://github.com/pretalx/pretalx/blob/dd9f39179a918c9b943fb64da0797fae930ff170/src/manage.py#L2) or xonsh https://github.com/NixOS/nixpkgs/pull/301449

Tested in https://github.com/NixOS/nixpkgs/pull/302315 by setting ``dontWrapPythonPrograms = true`` which unbroke the script. Before ``import os`` was being deleted by sed in line 3.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
With just the first revert gobject-introspection didn't want to build and complained about missing python packages, so I assume we also need to revert the other python changes. As they wheren't done in proper commits, I needed to split the commit a bit.

**Comment by SamLukeYes** [comment]
https://github.com/NixOS/nixpkgs/pull/301449 might also need to be reverted if this PR is merged, or xonsh users will likely encounter https://github.com/NixOS/nixpkgs/issues/248978 again

**Comment by domenkozar** [comment]
If only two packages are broken it might make more sense to workaround the issue and properly fix it?

**Comment by LordGrimmauld** [comment]
> If only two packages are broken it might make more sense to workaround the issue and properly fix it?

it is definitely more, i used `git bisect` and determined https://github.com/NixOS/nixpkgs/issues/301498 to  be caused by https://github.com/NixOS/nixpkgs/pull/297628 as well. Its not just xonsh and some libs.

**Comment by FRidh** [comment]
We should revert the changes, make fixes where needed, create a separate test job, reiterate when needed, and then submit again to staging.

**Comment by SuperSandro2000** [comment]
> If only two packages are broken it might make more sense to workaround the issue and properly fix it?

I think the unwrap logic is doing not always true assumptions and is currently hit or miss and can cause random breakages in undefined places.

**Comment by alyssais** [comment]
This has also broken mailman at runtime, [as can be seen](https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.mailman.x86_64-linux) from its NixOS test.

**Comment by SuperSandro2000** [comment]
Since no one opposed reverting this with an alternative in the last 4 days, I think we should just merge this to fix wrapped applications.


@vcunat can we get this into staging-next to get this fixed faster or should we target staging?

**Comment by alyssais** [comment]
> can we get this into staging-next to get this fixed faster or should we target staging?

[There is no staging-next currently underway](https://github.com/NixOS/nixpkgs/compare/master...staging-next), so this should just be merged into staging before the next staging-next starts.

**Comment by vcunat** [comment]
It rebuilds darwin stdenv.  You don't suggest making a separate staging-next iteration just for this change, right?

**Comment by SuperSandro2000** [comment]
> It rebuilds darwin stdenv. You don't suggest making a separate staging-next iteration just for this change, right?

Na, we just merge it into staging and take it with that.

Also I've just added the 24.05 milestone, as this is release critical.

**Comment by SuperSandro2000** [comment]
Cross-posting from https://github.com/NixOS/nixpkgs/pull/303057#issuecomment-2049602121 to for visibility:

Do we need to carry over [`e05a3ec` (#303057)](https://github.com/NixOS/nixpkgs/pull/303057/commits/e05a3ec1ce20846f4520433b15b61814ae61ec19) because of the update or can we drop that here, too?

**Comment by mweinelt** [comment]
Feel free to test that out. I don't know.

**Comment by SuperSandro2000** [comment]
> Are there any known/suspected affected packages apart from xonsh and pretalx? It's a bit hard to verify that the proposed fix works with just two examples and (seemingly?) no relevant tests.

pypy3 but that's generally not that well maintained. 

I think this could affect all wrapped scripts that are not generated by the build tooling and are just copied to $out/bin (eg https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/pr/pretalx/package.nix#L153)

**Comment by mweinelt** [comment]
> pypy3 but that's generally not that well maintained.

The only way to make it work is by recursing into the package set.

**Comment by LordGrimmauld** [comment]
pypy3 on nixos is itself a mess, as it makes some very specific assumptions about argv and python path env var at build time. I am honestly amazed it built at all before... That said: such a change as the here-reverted PR made might warrant revisiting *some* python applications that made questionable assumptions before. https://github.com/NixOS/nixpkgs/pull/297628 having broken pypy3 doesn't mean pypy3 had reasonable build logic even before it was blown to pieces. The installation logic is quite involved as it goes through multiple iterations of wrapping and compiling, it doesn't just build all at once.

**Comment by jonringer** [comment]
>  Getting this fixed is release critical, the new feature is not, and fixing this will cause a lot of rebuilds, hence we should get this definitely into the next staging-next cycle to not delay build failure fixing for the 24.05 release.

Agree with this sentiment. Getting it into staging now should make it available before ZHF.

**Comment by jonringer** [comment]
Going on the recommendation of @FRidh 

> We should revert the changes, make fixes where needed, create a separate test job, reiterate when needed, and then submit again to staging.

I'm going to merge this into staging. There's not currently a staging-next job open to expedite this, so the only other option would be to merge to master, or take more time for a more complete solution (which I think would be better tackled in a separate jobset).

**Pull request merged**
