### PR TITLE
chefdk: 2.4.17 -> 4.7.73

### PR DESCRIPTION
**Pull request by jerith666**
#### Motivation for this change

fixes breakage due to dependency on older version of ruby

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by nlewo — CHANGES_REQUESTED** [review]
@jerith666 Could you fix the aarch64 build or disable this platform (since this build is failing)?

**Comment by jerith666** [comment]
I don't have an aarch64 machine to test on, so I've just marked it broken.

**Comment by nlewo** [comment]
@GrahamcOfBorg build chefdk

**Comment by nlewo** [comment]
Thx @jerith666

**Pull request merged**
