### PR TITLE
NetBox 3.6

### PR DESCRIPTION
**Pull request by minijackson**
## Description of changes

Based on #252854

Introduces NetBox 3.6.2, marks NetBox 3.5.9 as EOL, removes NetBox 3.3.*

One thing that's different from #252854 is that the `netbox` attribute points to the latest version. This shouldn't have any bad consequence, since I've replaced any `netbox` usage in the NixOS modules & NixOS tests by `netbox_3_6`.

NetBox release notes:

- https://github.com/netbox-community/netbox/releases/tag/v3.6.0 (with breaking changes)
- https://github.com/netbox-community/netbox/releases/tag/v3.6.1
- https://github.com/netbox-community/netbox/releases/tag/v3.6.2
- https://github.com/netbox-community/netbox/releases/tag/v3.6.3

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

cc @n0emis & @RaitoBezarius

---

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>netbox (netbox_3_6)</li>
  </ul>
</details>

### CODE REVIEW

**Comment by minijackson** [comment]
Quick question @n0emis: do you want to be added to the maintainer list for `netbox_3_5`? (and same question for all future releases). Just asking to make sure, and I'll update the PR.

**Review by RaitoBezarius — APPROVED** [review]

**Comment by n0emis** [comment]
> Quick question @n0emis: do you want to be added to the maintainer list for `netbox_3_5`? (and same question for all future releases). Just asking to make sure, and I'll update the PR.

yes please

**Comment by minijackson** [comment]
@n0emis done!

I've also updated to [3.6.3](https://github.com/netbox-community/netbox/releases/tag/v3.6.3) that released a few minutes ago, and removed the now unused `fetchpatch` argument.

I've reran both tests, and `nixpkgs-review`, all pass.

**Comment by RaitoBezarius** [comment]
When CI passes, let's merge.

**Pull request merged**
