### PR TITLE
libreoffice: add zh-TW locale

### PR DESCRIPTION
**Pull request by rypervenche**
## Description of changes
Add all of the supported locales from the `solenv/inc/langlist.mk` source file (see the `completelangiso` variable).

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by rypervenche** [comment]
@raskin
I'm not sure if I was supposed to do this PR as a bug or not or if I was supposed to ping the maintainer so I'll just do it here. Apologies if I've done this wrong.

**Comment by 7c6f434c** [comment]
It's not a bug, it's been intentional — as locales have been seen as large even in terms of the LibreOffice package size, we added the specific ones someone PR'd for personal interest. What's the size situation now (I fell into the pattern and stopped tracking the size impact)?

**Comment by rypervenche** [comment]
Ahhh yes, it does add a little more than double the size. I was mostly wanting this for the zh-TW Chinese locale. I don't expect to you to add that just for one user, but if that's a possibility that would be cool. Otherwise, I'll have to see what I can do given my limited hardware.

### Current locales
[nix-shell:/nix/store]# `du -Lsh /nix/store/q5wrcaw5dmfdp9mvpxkj2wpjd58g2g9k-libreoffice-24.2.5.2-wrapped/`
**416M**	/nix/store/q5wrcaw5dmfdp9mvpxkj2wpjd58g2g9k-libreoffice-24.2.5.2-wrapped/

[nix-shell:/nix/store]# `du -Lsh hzb0iyzwcmvz1yfzy3jk2gq39dqzqam7-libreoffice-24.2.5.2/`
**1.3G**	hzb0iyzwcmvz1yfzy3jk2gq39dqzqam7-libreoffice-24.2.5.2/

### All locales
[nix-shell:/nix/store]# `du -Lsh /nix/store/m9mq3dgj94a0y1z8paxnabgw95d4xhi5-libreoffice-24.2.5.2-wrapped`
**592M**	/nix/store/m9mq3dgj94a0y1z8paxnabgw95d4xhi5-libreoffice-24.2.5.2-wrapped

[nix-shell:/nix/store]# `du -Lsh 6z0ifiyjdrw6kmds0sww9f1cind25pna-libreoffice-24.2.5.2/`
**2.9G**	6z0ifiyjdrw6kmds0sww9f1cind25pna-libreoffice-24.2.5.2/

**Comment by 7c6f434c** [comment]
And how much space would zh-TW locale take? Most of the previous locales were basically by a single user's PR.

I guess eventually we will be forced to learn to split locales into single packages with the wrapper making sure that the chosen ones are made available, but that requires multiple rebuilds to figure out…

**Comment by rypervenche** [comment]
> And how much space would zh-TW locale take? Most of the previous locales were basically by a single user's PR.

111.691 MiB total added on, which includes both the extra space from unwrapped and the wrapped derivations:

#### default libreoffice-fresh
`$ du -Ls /nix/store/zi4nivfr10s75gyz2xx2b7bad4g3dh8c-libreoffice-24.2.5.2-wrapped`
**425388**	/nix/store/zi4nivfr10s75gyz2xx2b7bad4g3dh8c-libreoffice-24.2.5.2-wrapped
`$ du -Ls /nix/store/9vn3ls2j1gzfqbldl5iyasl2kxm7xwvs-libreoffice-24.2.5.2`
**1353060**	/nix/store/9vn3ls2j1gzfqbldl5iyasl2kxm7xwvs-libreoffice-24.2.5.2

#### adding zh-TW locale to default langs
`$ du -Ls /nix/store/b4v39z0b7qq4520a1ajwbamngs2xrkp2-libreoffice-24.2.5.2-wrapped`
**434036**	/nix/store/b4v39z0b7qq4520a1ajwbamngs2xrkp2-libreoffice-24.2.5.2-wrapped
`$ du -Ls /nix/store/gwb0d8vkgl3llmsvcyk3s63z27ydri77-libreoffice-24.2.5.2`
**1458784**	/nix/store/gwb0d8vkgl3llmsvcyk3s63z27ydri77-libreoffice-24.2.5.2

**Comment by 7c6f434c** [comment]
Is the size of  `lib/libreoffice/help/zh-CN` roughly 35M or roughly 100M?

Anyway, even if it is three times a typical locale, not a reason against merging a single language for now, but I would prefer to keep not adding further help languages until a user submits a PR for them.

**Comment by rypervenche** [comment]
`# du -sh /nix/store/gwb0d8vkgl3llmsvcyk3s63z27ydri77-libreoffice-24.2.5.2/lib/libreoffice/help/zh-CN`
**33M**	/nix/store/gwb0d8vkgl3llmsvcyk3s63z27ydri77-libreoffice-24.2.5.2/lib/libreoffice/help/zh-CN

Would it be best to open a new PR for this then or simply update my commit if I wanted to get only zh-TW added?

(also thank you for taking the time to discuss this and for taking my request seriously)

**Comment by 7c6f434c** [comment]
Oops, sorry, I wanted to ask both zh-CN and zh-TW for comparison. 

I am fine with renaming the commit and the PR in-place.

**Comment by rypervenche** [comment]
I have updated the commit to only add the "zh-TW" locale.

The two locales are roughly the same size:
`du -s /nix/store/gwb0d8vkgl3llmsvcyk3s63z27ydri77-libreoffice-24.2.5.2/lib/libreoffice/help/zh-{CN,TW}`
**33180**	/nix/store/gwb0d8vkgl3llmsvcyk3s63z27ydri77-libreoffice-24.2.5.2/lib/libreoffice/help/zh-CN
**32512**	/nix/store/gwb0d8vkgl3llmsvcyk3s63z27ydri77-libreoffice-24.2.5.2/lib/libreoffice/help/zh-TW

**Pull request merged**
