### PR TITLE
armitage: init at unstable-2022-12-05

### PR DESCRIPTION
**Pull request by emilytrau**
###### Description of changes

Graphical cyber attack management tool for Metasploit
https://github.com/redcanari/armitage

Related to #81418

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by onny** [comment]
The default.nix looks a bit complicated, could we split this up into `pkgs/tools/security/armitage/default.nix` and `pkgs/tools/security/armitage/teamserver.nix`?

**Comment by D3vil0p3r** [comment]
@emilytrau this package seems to work. When will this PR be merged?

**Comment by emilytrau** [comment]
@D3vil0p3r thanks for reviewing! happy to merge with your approval :)

**Comment by D3vil0p3r** [comment]
> @D3vil0p3r thanks for reviewing! happy to merge with your approval :)

I would just change the source from redcanari to https://github.com/r00t0v3rr1d3/armitage (that is the same used in [Kali Linux](https://gitlab.com/kalilinux/packages/armitage/-/blob/kali/master/debian/upstream/metadata?ref_type=heads).

**Comment by D3vil0p3r** [comment]
LGTM

**Comment by D3vil0p3r** [comment]
@emilytrau can be also backported to stable (23.11)?

**Comment by emilytrau** [comment]
sure

**Pull request merged**
