### PR TITLE
noto-fonts-cjk: fix rendering issues

### PR DESCRIPTION
**Pull request by midchildan**
###### Motivation for this change

The variable font build of Noto CJK was displaying tofus on some GTK
apps. This fixes the issue by using non-variable OTCs instead.

https://github.com/NixOS/nixpkgs/pull/145767#issuecomment-1016437188

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Before
Screenshot from 2022-01-22 03-25-57

After
Screenshot from 2022-01-22 03-17-18

### CODE REVIEW

**Review by NickCao — APPROVED** [review]
LGTM, tested on my machine and fonts now look exactly as expected.

**Comment by Mathnerd314** [comment]
Maybe open a tracking issue to switch back to the variable fonts in the future? Fedora is switching to variable fonts by default (https://fedoraproject.org/wiki/Changes/DefaultToNotoFonts as mentioned in https://github.com/NixOS/nixpkgs/pull/145767#issuecomment-1018123659) - after they make a release the breakages should eventually get solved.

I would open it but I don't know how those screenshots were generated.

**Comment by NickCao** [comment]
The gtk application in question is gedit, I think we can use the nixos test framework to automatically generate this kind of screenshots.

**Comment by NickCao** [comment]
Strangely, the change proposal from Fedora has no metion of potential incompatibilities.

**Comment by Mathnerd314** [comment]
They mention "legacy applications", but yeah. Maybe the non-CJK variable fonts don't have the problems the CJK ones do.

**Comment by NickCao** [comment]
I've came up with a sample test for noto fonts: https://github.com/NickCao/nixpkgs/commit/f884faf9906406ef3b7a7f7bae9e7a423da867bc, which can generate screenshots like , to catch future rendering issues.

**Comment by Mathnerd314** [comment]
Alright, I filed https://github.com/NixOS/nixpkgs/issues/156131. I'm not planning to track it down, but of course if someone has some free time they're welcome to.

**Pull request merged**
