### PR TITLE
swayosd: unstable-2023-07-18 -> unstable-2023-09-26

### PR DESCRIPTION
**Pull request by barab-i**
## Description of changes

swayosd: unstable-2023-07-18 -> unstable-2023-09-26
homepage: https://github.com/ErikReider/SwayOSD
swayosd-server should be launched and use 'swayosd-client' instead of 'swayosd'.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by MikaelFangel** [comment]
Please make the commit adding yourself as a maintainer appear before the commit updating the package, and it should also have the correct format: `maintainers: add <handle>`. See [https://github.com/NixOS/nixpkgs/blob/fac16fbfae144461f41accc3455682e052e6ce49/CONTRIBUTING.md#commit-conventions](https://github.com/NixOS/nixpkgs/blob/fac16fbfae144461f41accc3455682e052e6ce49/CONTRIBUTING.md#commit-conventions)

**Comment by MikaelFangel** [comment]
Result of nixpr review:
<details>
<summary>1 package built:</summary>
swayosd
</details>

**Comment by barab-i** [comment]
> Result of nixpr review:
> 1 package built:
> swayosd

Sorry, I couldn't understand what is incorrect situation here.

**Comment by MikaelFangel** [comment]
> > Result of nixpr review:
> 
> > 1 package built:
> 
> > swayosd
> 
> 
> 
> Sorry, I couldn't understand the incorrect situation here. 

There is no issue. I just completed one of the checks (:

**Comment by hakan-demirli** [comment]
I was about to open a PR but I found this. 
I think there is a problem with the tests. It says it's been running for the last 2 months.

**Comment by barab-i** [comment]
I just noticed that the location of swayosd's files has changed. I'll resolve conflicts.

**Review by Janik-Haag — APPROVED** [review]
LGTM

**Comment by Janik-Haag** [comment]
Gonna merge this since @Aleksanaa had enough time to review this but didn't.
Also thank you for your contribution. Welcome to nixpkgs :D

**Comment by augustebaum** [comment]
Hi, this update broke my setup (presumably because of the change to `swayosd-{server,client}`). Does any of you have a working setup going that I could use to fix mine? I'm not sure where to ask this so please let me know if some other place would be better suited.

**Comment by Janik-Haag** [comment]
Shouldn't changing the binary name in your config fix this?

**Pull request merged**
