### PR TITLE
teams-for-linux: 1.4.10 -> 1.4.11

### PR DESCRIPTION
**Pull request by chvp**
## Description of changes

https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.4.11

Only relevant for Darwin, and I only tested on Linux.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Samasaur1** [comment]
This fails on aarch64-darwin for me with this at the end of the log:
```
Running phase: buildPhase
yarn run v1.22.19
$ /private/tmp/nix-build-teams-for-linux-1.4.11.drv-0/source/node_modules/.bin/electron-builder --dir --macos --arm64 -c.electronDist=/nix/store/cnlzmc2h1bnj1m7mw4xmpim0cvgqamci-electron-28.0.0/libexec/electron -c.e>
  • electron-builder  version=24.9.1 os=23.3.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=darwin arch=arm64 electron=28.0.0 appOutDir=dist/mac-arm64
  • copying Electron  source=/nix/store/cnlzmc2h1bnj1m7mw4xmpim0cvgqamci-electron-28.0.0/libexec/electron/Electron.app destination=/private/tmp/nix-build-teams-for-linux-1.4.11.drv-0/source/dist/mac-arm64/Electron.a>
  ⨯ corrupted Electron dist  failedTask=build stackTrace=Error: corrupted Electron dist
    at createMacApp (/private/tmp/nix-build-teams-for-linux-1.4.11.drv-0/source/node_modules/app-builder-lib/src/electron/electronMac.ts:90:11)
    at beforeCopyExtraFiles (/private/tmp/nix-build-teams-for-linux-1.4.11.drv-0/source/node_modules/app-builder-lib/src/electron/ElectronFramework.ts:82:5)
    at MacPackager.doPack (/private/tmp/nix-build-teams-for-linux-1.4.11.drv-0/source/node_modules/app-builder-lib/src/platformPackager.ts:288:7)
    at MacPackager.pack (/private/tmp/nix-build-teams-for-linux-1.4.11.drv-0/source/node_modules/app-builder-lib/src/macPackager.ts:188:9)
    at Packager.doBuild (/private/tmp/nix-build-teams-for-linux-1.4.11.drv-0/source/node_modules/app-builder-lib/src/packager.ts:442:9)
    at executeFinally (/private/tmp/nix-build-teams-for-linux-1.4.11.drv-0/source/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/private/tmp/nix-build-teams-for-linux-1.4.11.drv-0/source/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/private/tmp/nix-build-teams-for-linux-1.4.11.drv-0/source/node_modules/app-builder-lib/src/packager.ts:337:12)
    at executeFinally (/private/tmp/nix-build-teams-for-linux-1.4.11.drv-0/source/node_modules/builder-util/src/promise.ts:12:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Result of `nix-info -m`:
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.3.0, macOS 14.3.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by drupol** [comment]
OK so I guess it's still broken on Darwin then :)

**Comment by drupol** [comment]
Do you use Wayland or X11 ?

**Comment by dschrempf** [comment]
X11.

**Comment by drupol** [comment]
OK, then it might be a regression. I can't test since I don't use it anymore, I use Chromium + Teams app instead.

**Comment by chvp** [comment]
It's working for me on Wayland. Looking at the [upstream changes](https://github.com/IsmaelMartinez/teams-for-linux/compare/v1.4.10...v1.4.11), it seems very unlikely that it was this update that broke screen sharing.

**Comment by dschrempf** [comment]
Thanks for having a look! Sharing via Chromium does work normally, so I am using this as a workaround for now. I will try to debug later!

**Comment by dschrempf** [comment]
Most likely relevant: https://github.com/IsmaelMartinez/teams-for-linux/issues/1108

There seems to be a fix 1.4.12 (untested). Downgrading to 1.4.10 also seems to work.

**Comment by dschrempf** [comment]
1.4.12 fixes the issue. I will create a PR.

**Pull request merged**
