### PR TITLE
libreoffice: 5.1.0.3 -> 5.1.2.2

### PR DESCRIPTION
**Pull request by vandenoever**
###### Things done
- [ ] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by 7c6f434c** [comment]
Does this build? In commit b338187e71829bbf2c0a51bfd8db065864c62ab8 in master I regenerated `libreoffice-srcs.nix` (dependency tarball list) and there are a few changes, but I haven't checked if they are relevant to the build itself.

**Comment by vandenoever** [comment]
I've not managed to build it yet. The build takes very long on my machine.

**Comment by 7c6f434c** [comment]
@domenkozar Do we do such updates on stable? If yes, I guess it is better to pluck my update from master.

**Comment by domenkozar** [comment]
Exactly.

**Comment by vandenoever** [comment]
Sounds good to me. I did not realize there was another patch.

**Comment by joachifm** [comment]
@vandenoever The commit in question is b338187e71829bbf2c0a51bfd8db065864c62ab8

**Pull request closed without merging**
