### PR TITLE
qtbase: setup-hook: Don't override cmakeBuildType. 

### LINKED ISSUE #273632: Setting or overriding `cmakeBuildType` does not work for Qt applications
When we set or override `cmakeBuildType = "Debug"` for a Qt program such as `meshlab`, it has no effect:

```sh
NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixos-23.11.tar.gz nix-build --expr '(import <nixpkgs> {}).meshlab.overrideAttrs (old: { cmakeBuildType = "Debug"; preUnpack = "echo $cmakeBuildType; exit 1"; })'
```

```
this derivation will be built:
  /nix/store/kzij2izq2f80lq5c00zskjnq5liladm4-meshlab-2022.02.drv
building '/nix/store/kzij2izq2f80lq5c00zskjnq5liladm4-meshlab-2022.02.drv'...
qtPreHook
unpacking sources
Release
```

It still prints `Release`.

That is frustrating and confusing.

I would like to override it to get debug symbols for a crash, and it simply has no effect because of this.

As described on https://discourse.nixos.org/t/single-cmakebuildtype-shared-between-derivation-and-dependency/35184 this is because the `qtbase` setup hook (here `qt-5`, same for `qt-6`), sets it unconditionally:

https://github.com/NixOS/nixpkgs/blob/d600f006643e074c2ef1d72e462e218b647a096c/pkgs/development/libraries/qt-5/hooks/qtbase-setup-hook.sh#L25-L31

We should fix this somehow.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by nh2**
## Description of changes

The goal is to fix #273632.

But I am not an expert in the nixpkgs Qt stuff, so marking it as draft PR for now.

cc @NixOS/qt-kde

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by peterhoeg** [comment]
This looks perfectly sane to me. @NickCao or @K900 - any thoughts?

**Comment by K900** [comment]
Honestly I'd support getting rid of this entirely. It just feels unnecessarily spooky.

**Comment by nh2** [comment]
> Honestly I'd support getting rid of this entirely. It just feels unnecessarily spooky.

@K900 That's beyond what I can do here though; should we merge this until then?

**Comment by K900** [comment]
Retarget to staging-next please.

**Comment by NickCao** [comment]
Superseded by https://github.com/NixOS/nixpkgs/pull/307573

**Pull request closed without merging**
