### PR TITLE
rust-analyzer: 2020-10-19 -> 2020-11-09 and fix build

### LINKED ISSUE #103009: rust-analyzer build fails on latest master
```
running 31 tests
test cargo_target_spec::tests::test_cfg_expr_minimal_features_needed ... ok
test diagnostics::to_proto::tests::rustc_wrong_number_of_parameters ... ok
test markdown::tests::test_format_docs_handles_plain_text ... ok
test markdown::tests::test_format_docs_keeps_comments_outside_of_rust_block ... ok
test markdown::tests::test_format_docs_skips_comments_in_rust_block ... ok
test semantic_tokens::tests::test_diff_remove_from_end ... ok
test semantic_tokens::tests::test_diff_remove_from_middle ... ok
test to_proto::tests::conv_fold_line_folding_only_fixup ... ok
test diagnostics::to_proto::tests::macro_compiler_error ... ok
test markdown::tests::test_format_docs_handles_complex_code_block_attrs ... ok
test markdown::tests::test_code_blocks_in_comments_marked_as_rust ... ok
test markdown::tests::test_format_docs_preserves_newlines ... ok
test markdown::tests::test_code_blocks_in_comments_marked_as_text ... ok
test markdown::tests::test_format_docs_handles_rust_alias ... ok
test markdown::tests::test_format_docs_handles_non_rust ... ok
test lsp_utils::tests::test_apply_document_changes ... ok
test semantic_tokens::tests::test_diff_insert_at_end ... ok
test diagnostics::to_proto::tests::rustc_mismatched_type ... ok
test semantic_tokens::tests::test_diff_insert_in_middle ... ok
test diagnostics::to_proto::tests::rustc_incompatible_type_for_trait ... ok
test diagnostics::to_proto::tests::handles_macro_location ... ok
test diagnostics::to_proto::tests::rustc_unused_variable_as_info ... ok
test diagnostics::to_proto::tests::snap_multi_line_fix ... ok
test semantic_tokens::tests::test_diff_insert_at_beginning ... ok
test markdown::tests::test_format_docs_adds_rust ... ok
test markdown::tests::test_format_docs_does_not_skip_lines_if_plain_text ... ok
test semantic_tokens::tests::test_diff_remove_from_beginning ... ok
test diagnostics::to_proto::tests::rustc_unused_variable ... ok
test diagnostics::to_proto::tests::rustc_unused_variable_as_hint ... ok
test diagnostics::to_proto::tests::clippy_pass_by_ref ... ok
test cli::load_cargo::tests::test_loading_rust_analyzer ... FAILED

failures:

---- cli::load_cargo::tests::test_loading_rust_analyzer stdout ----
thread 'cli::load_cargo::tests::test_loading_rust_analyzer' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to find sysroot for Cargo.toml file /build/source/Cargo.toml. Is rust-src installed?

Caused by:
    could not find libcore in sysroot path `/nix/store/ffrvkirp3dxna998jm5j0wadjgyqf1pg-rust-src` (`RUST_SRC_PATH` might be incorrect, try unsetting it)', crates/rust-analyzer/src/cli/load_cargo.rs:109:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    cli::load_cargo::tests::test_loading_rust_analyzer

test result: FAILED. 30 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'
builder for '/nix/store/kfdqljg7xf42372f82vz8dbvx84mwgfv-rust-analyzer-unwrapped-unstable-2020-10-19.drv' failed with exit code 101
cannot build derivation '/nix/store/kifik42ihmi8yf8yclymrx3xslrf50d1-rust-analyzer-unstable-2020-10-19.drv': 1 dependencies couldn't be built
```

cc @oxalica

### PR DESCRIPTION
**Pull request by oxalica**
###### Motivation for this change
Bump version and fix #103009

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
  - broken -> 91.6M
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by oxalica** [comment]
ping @jonringer for review

**Comment by oxalica** [comment]
Blocked by #103009

**Comment by jonringer** [comment]
looks like there's also conflicts now as well

**Comment by oxalica** [comment]
@jonringer Rebased and fixed build with rustc 1.47.0 on master

**Comment by austinbutler** [comment]
Result of `nixpkgs-review pr 101773` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>lumo</li>
  </ul>
</details>
<details>
  <summary>25 packages built:</summary>
  <ul>
    <li>antora</li>
    <li>castnow</li>
    <li>epgstation</li>
    <li>fast-cli</li>
    <li>gtop</li>
    <li>iosevka</li>
    <li>joplin</li>
    <li>mastodon-bot</li>
    <li>mirakurun</li>
    <li>netlify-cli</li>
    <li>pm2</li>
    <li>pulp</li>
    <li>redoc-cli</li>
    <li>rust-analyzer</li>
    <li>rust-analyzer-unwrapped</li>
    <li>thelounge</li>
    <li>vimPlugins.coc-jest</li>
    <li>vimPlugins.coc-prettier</li>
    <li>vimPlugins.coc-snippets</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-tslint</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vscode-extensions.matklad.rust-analyzer</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
    <li>wasm-text-gen</li>
  </ul>
</details>

**Pull request merged**
