### PR TITLE
qjackctl: 4.0 -> 4.2, qt4 -> qt5

### PR DESCRIPTION
**Pull request by joelmo**
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by cillianderoiste** [comment]
The travis build just fails because it's building too much. @joelmo do we really need xlibs here?

**Comment by joelmo** [comment]
If I don't have it I get this:
`qjackctl.cpp:72:23: fatal error: X11/Xatom.h: No such file or directory`

**Comment by cillianderoiste** [comment]
Hi @joelmo, the error in Travis is now: 

    checking for qmake... /usr/bin/qmake
    configure: error: qmake-qt5 not found in current PATH. Maybe QT development environment isn't available. (qt5-devel)

Perhaps it works locally if you don't have chroot-builds enabled for nix?

**Comment by joelmo** [comment]
I have tested in sandbox now, and everything is fine here. Could you checkout my branch and try? (https://github.com/joelmo/nixpkgs/tree/qjackctl)

**Comment by cillianderoiste** [comment]
Indeed, it builds and runs fine here. Thanks.

**Pull request merged**
