### PR TITLE
zigbee2mqtt: 1.16.2 -> 1.20.0

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

4.8M derivation size :man_shrugging: 

https://github.com/NixOS/nixpkgs/pull/108130#issuecomment-753606579

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by sweber83 — APPROVED** [review]
@mweinelt 
Your PR is running on my raspi since yesterday.
Working fine so far!

**Comment by mweinelt** [comment]
Yeah, I was just dabbling with the size of the derivation. I'm still hesitant to merge this for well-known reasons.

**Comment by mbrgm** [comment]
@mweinelt So the derivation size is holding this back?

**Comment by mweinelt** [comment]
Superseded by #147985.

**Comment by sweber83** [comment]
@mweinelt 
Did the backported patch (https://github.com/NixOS/nixpkgs/pull/142319) not solve the derivation size issue?
Or was there another reason for closing this pr?

**Comment by mweinelt** [comment]
See https://github.com/NixOS/nixpkgs/pull/147792.

**Pull request closed without merging**
