### PR TITLE
ppp: 2.4.9 -> 2.5.0

### PR DESCRIPTION
**Pull request by yu-re-ka**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by yu-re-ka** [comment]
ppp 2.5.0 has been released, however there is no patch yet for networkmanager to build with it and the meson build system

https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/merge_requests/1558/

**Comment by yu-re-ka** [comment]
Added patch for networkmanager, which has just been merged upstream

**Comment by mweinelt** [comment]
Nothing immediately stands out, that would require changes to the module.

```
What's new in ppp-2.5.0.
************************

The 2.5.0 release is a major release of pppd which contains breaking 
changes for third-party plugins, a complete revamp of the build-system
and that allows for flexibility of configuring features as needed.

In Summary:
* Support for PEAP authentication by Eivind Næss and Rustam Kovhaev
* Support for loading PKCS12 certificate envelopes 
* Adoption of GNU Autoconf / Automake build environment, by Eivind Næss
  and others.
* Support for pkgconfig tool has been added by Eivind Næss.
* Bunch of fixes and cleanup to PPPoE and IPv6 support by Pali Rohár.
* Major revision to PPPD's Plugin API by Eivind Næss.
  - Defines in which describes what features was included in pppd
  - Functions now prefixed with explicit ppp_* to indicate that
    pppd functions being called.
  - Header files were renamed to better align with their features,
    and now use proper include guards
  - A pppdconf.h file is supplied to allow third-party modules to use
    the same feature defines pppd was compiled with.
  - No extern declarations of internal variable names of pppd, 
    continued use of these extern variables are considered 
    unstable.
* Lots of internal fixes and cleanups for Radius and PPPoE by Jaco Kroon
* Dropped IPX support, as Linux has dropped support in version 5.15
  for this protocol.
* Many more fixes and cleanups.
* Pppd is no longer installed setuid-root.
* New pppd options:
  - ipv6cp-noremote, ipv6cp-nosend, ipv6cp-use-remotenumber,
    ipv6-up-script, ipv6-down-script
  - -v, show-options
  - usepeerwins, ipcp-no-address, ipcp-no-addresses, nosendip
* On Linux, any baud rate can be set on a serial port provided the
  kernel serial driver supports that.

Note that if you have built and installed previous versions of this
package and you want to continue having configuration and TDB files in
/etc/ppp, you will need to use the --sysconfdir option to ./configure.

For a list of the changes made during the 2.4 series releases of this
package, see the Changes-2.4 file.
```

**Review by mweinelt — APPROVED** [review]

**Comment by yu-re-ka** [comment]
Fixed `sstp`

**Comment by yu-re-ka** [comment]
`pkgs/os-specific/darwin/apple-source-releases/configd/default.nix` includes ppp, and I would like to confirm that it still works

**Comment by mweinelt** [comment]
Also breaks `pptpd`.

**Comment by yu-re-ka** [comment]
Fedora rawhide has updated to ppp 2.5.0 but they don't have patches for pptpd  (yet): https://src.fedoraproject.org/rpms/pptpd/commits/rawhide
Upstream hasn't seen new commits since 4 years.

Alpine doesn't package pptpd

Debian and Arch have not updated to ppp 2.5.0 yet

**Comment by yu-re-ka** [comment]
CC @obadz for pptpd

**Comment by maxeaubrey** [comment]
Fyi #227809 covers the nm patch you're pulling in here.

**Comment by yu-re-ka** [comment]
The `pppd` test is broken

**Comment by yu-re-ka** [comment]
The rename of the `rp-pppoe` plugin to `pppoe` should be documented in the release notes, as this is a breaking change in users' configs

**Comment by trofi** [comment]
Bisect says b65e9775fb4dc633978ec67156415cb32df661af `ppp: 2.4.9 -> 2.5.0` broke `networkmanager-1.42.6` in `staging`:

```
$ nix build --no-link -f. -L networkmanager
...
networkmanager> ../src/core/ppp/nm-pppd-plugin.c: In function 'nm_phasechange':
networkmanager> ../src/core/ppp/nm-pppd-plugin.c:128:34: error: 'ifname' undeclared (first use in this function); did you mean 'tzname'?
networkmanager>   128 |         ifindex = if_nametoindex(ifname);
networkmanager>       |                                  ^~~~~~
networkmanager>       |                                  tzname
```

**Comment by vcunat** [comment]
Also [`connman`](https://hydra.nixos.org/build/217664797/nixlog/1/tail).  Fix perhaps in https://git.kernel.org/pub/scm/network/connman/connman.git/commit/?id=a48864a2e5d2a725dfc6eef567108bc13b43857f

/cc maintainer @matejc.

**Comment by vcunat** [comment]
And `gnome.{networkmanager-l2tp,networkmanager-fortisslvpn}`.  Maintainers: @jtojnar, @domenkozar, @obadz, @maxeaubrey, @abbradar.

**Comment by maxeaubrey** [comment]
sstp: doesn't have a new release yet but we can pull this patch https://gitlab.gnome.org/GNOME/network-manager-sstp/-/commit/852db07dc7d19c37e398d831410bd94c8659a210
fortisslvpn: probably https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn/-/commit/084ef529c5fb816927ca54866f66b340265aa9f6 + https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn/-/commit/8773f772d39f8eee6edc1fd2e5437c754ed41e1e
l2tp: 1.20.10 fixes building against 2.5.0 https://github.com/nm-l2tp/NetworkManager-l2tp/releases/tag/1.20.10

**Comment by maxeaubrey** [comment]
@vcunat my bad, sstp looks to have also fixed this across two separate commits, probably needs this first too. https://gitlab.gnome.org/GNOME/network-manager-sstp/-/commit/da96f8ed5bf34c4949fdde58ca5e00cbf879b509

Considering both seem to get scarce releases, in my opinion it'd also be ok to update them to `unstable-$date` to simplify things. I'll take a look at doing that in a few days if no one gets there first, I just don't have the time tonight.

**Comment by vcunat** [comment]
All the three are channel blockers, as they're included in the gnome ISO.

**Comment by vcunat** [comment]
Uwww... pulling both merge patches wasn't enough.  With latest commit (and autoreconfHook) it also failed
```
/nix/store/arq10xrdh6yw3hgxils68cnjm0yr756a-coreutils-9.1/bin/install: cannot create regular file '/nix/store/ir41b0rw68hzd5g6mwq4nv6nmq3hbgdv-ppp-2.5.0/lib/pppd/2.5.0/nm-sstp-pppd-plugin.so': Permission denied
```
I don't know... I don't think I can spend that much time on this.

**Comment by maxeaubrey** [comment]
Ack, thanks for checking. I'll try to find time tomorrow night to give this a go.

**Comment by vcunat** [comment]
https://github.com/NixOS/nixpkgs/pull/229416

**Comment by yu-re-ka** [comment]
@truvatech see #229990

**Comment by farnoy** [comment]
This upgrade broke NetworkManager PPPoE connections. I created an [issue upstream](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/1312). Note that this is different from the build issue mentioned earlier in this thread.

**Pull request merged**
