### PR TITLE
pleroma: wrap pleroma_ctl with RELEASE_COOKIE

### PR DESCRIPTION
**Pull request by picnoir**
At the moment, we can't run `pleroma_ctl` interactively: we're not injecting the deployment cookie path. Wrapping the binary with the appropriate value.

Fixing the NixOS test as well: the toot patch was not applying cleanly. We don't need this patch anymore, the issue has been fixed upstream.

See individual commit message for more information.

CC @Kloenk who has a similar fix at https://github.com/NixOS/nixpkgs/pull/154740

###### Things donecommits

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NinjaTrappeur** [comment]
As pointed by @Kloenk , the env variable need to be set to the actual cookie value, not the path to the file containing it.

I just force pushed a small change `cat`-ing the content of the file to a variable. Sadly, `wrapProgram` is escaping the string value, we have to come up with our own wrapper :(

**Comment by NinjaTrappeur** [comment]
@GrahamcOfBorg test pleroma

**Comment by cole-h** [comment]
@ofborg eval

**Comment by NinjaTrappeur** [comment]
The NixOS test is now working again. We were missing `hexdump` in the preStart closure, hence failing to generate the deployment cookie.

Our previous usage of the `RELEASE_COOKIE` env variable was buggy: we were setting the cookie to be the string `/var/lib/pleroma/.cookie` instead of the actual content of that file. Since it was not trying to read the actual file, the hexdump failure was not failing the startup since we were ot trying to read the actual file.

We now explicitly reference `pkgs.hexdump` and read from the actual cookie through the `pleroma` and `pleroma_ctl` wrappers.

@GrahamcOfBorg test

**Review by kloenk — APPROVED** [review]
LGTM, did not test locally

**Comment by NinjaTrappeur** [comment]
I deployed that to my instance (that had one of those 0-bytes cookie file), it worked as expected.

I'll leave this open a couple of days before merging in case @yu-re-ka want to have a look.

**Comment by cole-h** [comment]
@ofborg eval

(GitHub's API was unhappy earlier)

**Comment by yu-re-ka** [comment]
Pleroma fails to start with this change:

```
[yuka@yaya:~]$ sudo systemctl status pleroma
× pleroma.service - Pleroma social network
     Loaded: loaded (/etc/systemd/system/pleroma.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sun 2022-03-20 12:36:32 CET; 51s ago
    Process: 377195 ExecStartPre=/nix/store/s47m7p3mx9pdibkyzdn4sjx9qph7irk8-pleromaStartPre/bin/pleromaStartPre (code=exited, status=1/FAILURE)
         IP: 0B in, 0B out
        CPU: 39ms

Mar 20 12:36:32 yaya systemd[1]: Starting Pleroma social network...
Mar 20 12:36:32 yaya pleromaStartPre[377195]: Creating cookie file
Mar 20 12:36:32 yaya pleromaStartPre[377215]: 16+0 records in
Mar 20 12:36:32 yaya pleromaStartPre[377215]: 16+0 records out
Mar 20 12:36:32 yaya pleromaStartPre[377215]: 16 bytes copied, 6.3223e-05 s, 253 kB/s
Mar 20 12:36:32 yaya pleromaStartPre[377246]: cat: /nix/store/xflkbv6cks96r5nq34d45g7mh97v3ykr-pleroma-2.4.2/releases/COOKIE: No such file or directory
Mar 20 12:36:32 yaya systemd[1]: pleroma.service: Control process exited, code=exited, status=1/FAILURE
Mar 20 12:36:32 yaya systemd[1]: pleroma.service: Failed with result 'exit-code'.
Mar 20 12:36:32 yaya systemd[1]: Failed to start Pleroma social network.

[yuka@yaya:~]$ 
```

**Comment by yu-re-ka** [comment]
Ah, everyone who has set `pleroma.package` to something has to add a `.override { cookieFile = "/var/lib/pleroma/.cookie"; }` now. I don't really like that this breaks existing setups without any warning.

**Comment by NinjaTrappeur** [comment]
Oops, I did not think about that use case. I left the default to no
override in the hope of not breaking the existing setups ><

My apologies.

**Comment by NinjaTrappeur** [comment]
I think https://github.com/NixOS/nixpkgs/pull/164398/commits/e7f6370701a3e65082e67cd0f9696bcd32c2e9ec is still useful.

**Pull request merged**
