### PR TITLE
nixos/adguardhome: improve configFile creation

### PR DESCRIPTION
**Pull request by rhoriguchi**
###### Motivation for this change

Currently, `bind_host` and `bind_port` get set through individual setting options.
https://github.com/NixOS/nixpkgs/blob/fad04722fc3d692e3511e58e337ec9fa627f5ba5/nixos/modules/services/networking/adguardhome.nix#L15-L24

That's why it makes no sense to check if `bind_host` is set since it will always be set.
https://github.com/NixOS/nixpkgs/blob/fad04722fc3d692e3511e58e337ec9fa627f5ba5/nixos/modules/services/networking/adguardhome.nix#L92-L97

This change will make it so that individual setting options are always respected.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by CRTified** [comment]
> Currently, bind_host and bind_port get set through individual setting options.

No, they don't. AdGuard has two `bind_host` and `bind_port` settings:
 - In the root level of the config, which dictates the address for the web interface (and is configured by `services.adguardhome.host` and `.port`,
 - Under the `dns` tree (which can also be written as a list under the key `bind_hosts`). This sets the address of the DNS server.

This is an important difference, and both need to be set.

**Comment by rhoriguchi** [comment]
> > Currently, bind_host and bind_port get set through individual setting options.
> 
> No, they don't. AdGuard has two `bind_host` and `bind_port` settings:
> 
>     * In the root level of the config, which dictates the address for the web interface (and is configured by `services.adguardhome.host` and `.port`,
> 
>     * Under the `dns` tree (which can also be written as a list under the key `bind_hosts`). This sets the address of the DNS server.
> 
> 
> This is an important difference, and both need to be set.

Good point, I didn't see the `"dns"` prefix. That setting `dns.bind_host` seems not required, after version `v0.106.0` <https://github-wiki-see.page/m/AdguardTeam/AdGuardHome/wiki/Configuration>

I've added en extra line to cover the case pre `v0.106.0`.
https://github.com/NixOS/nixpkgs/blob/a2cee3bc10bdaf4ac2988cec3a6d09fd861efb23/nixos/modules/services/networking/adguardhome.nix#L15-L20

**Comment by rhoriguchi** [comment]
> Because it gets changed to `dns.bind_hosts` (which will be a list). I'd still prefer to not set a default value (especially when it's a list). Otherwise, `cfg.host` will be added to the list, even if the user sets a different value (for `bind_hosts`) and this can lead to the DNS being exposed on an undesired interface. Making it hard to do so by accident is IMHO important, to prevent amplification attacks in bad network configurations.

Isn't this the best option, that way it can easily be set with `services.adguardhome.host` and `services.adguardhome.port`? Otherwise, I think it's kinda strange the same option can be set through `services.adgaurdhome.settings` and the mentioned ones, which is even more confusing.

https://github.com/NixOS/nixpkgs/blob/e6fd3a24ee84da143d177fb0339bfdb3a7985dc2/nixos/modules/services/networking/adguardhome.nix#L15-L22

---

An option would be to add a `hosts` setting which is `hosts` if set else it's just the value of `host` as list. The reason for this is backwards compatibility.

**Review by CRTified — APPROVED** [review]
Looks good to me now. This PR now basically adds two assertions so that the user doesn't accidentally set `bind_host` and `bind_port` for the web interface which are intended to be configured by explicitly existing options.

**Comment by CRTified** [comment]
Might need a closer look, as these assertions in combination with default values break non-declarative setups. This PR might also conflict with #198691

**Comment by rhoriguchi** [comment]
Closing because of #176701

**Pull request closed without merging**
