### PR TITLE
adoptopenjdk-bin: 11.0.9 -> 11.0.10, 15.0.1 -> 15.0.2, 8.0.272 -> 8.0…

### PR DESCRIPTION
**Pull request by andreoss**
###### Motivation for this change
Update OpenJDK
8.0.282: https://builds.shipilev.net/backports-monitor/release-notes-openjdk8u282.txt https://www.oracle.com/java/technologies/javase/8u281-relnotes.html
11.0.10: https://www.oracle.com/java/technologies/javase/11-0-10-relnotes.html 
15.0.2: https://www.oracle.com/java/technologies/javase/15-0-2-relnotes.html
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by taku0** [comment]
LGTM.  Please rebase on `staging` because this PR triggers mass-rebuilds.

**Comment by andreoss** [comment]
@taku0 Done.

**Comment by taku0** [comment]
Something is wrong. This PR should contain only two commits. Could you try the following commands?

```
git fetch upstream staging:staging
git rebase staging
```

**Comment by andreoss** [comment]
@taku0 It seems to be fine now.

**Pull request merged**
