### PR TITLE
Mumps: refactor coin-or-mumps related code while keeping compatible.

### PR DESCRIPTION
**Pull request by qbisi**
## Motivation
nixpkgs#mumps is mainly used by ipopt and casadi, which use a coin-or-mumps compatible varient.
However those coin-or-mumps related code makes nixpkgs#mumps hard to maintain and contribute by other users.
This pr keep nixpkgs#mumps in parrallel with mumps-seq in Debian while keeping the minimal coinmumps compatible file
"mumps_mpi.h". Fix to upstream casadi should work with the new nixpkgs#mumps.

@nim65s
@abbradar

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by qbisi** [comment]
After this pr is merged, there will be another update for mumps-par built with mpi support, many downstream packages urgently want this (mumps-par) such as pastix or petsc.

**Comment by nim65s** [comment]
cc @MatthewCroughan

**Comment by nim65s** [comment]
Result of `nixpkgs-review pr 350824` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>45 packages failed to build:</summary>
  <ul>
    <li>aligator</li>
    <li>aligator.doc</li>
    <li>casadi</li>
    <li>crocoddyl</li>
    <li>crocoddyl.doc</li>
    <li>pinocchio</li>
    <li>pinocchio.doc</li>
    <li>proxsuite-nlp</li>
    <li>proxsuite-nlp.doc</li>
    <li>python311Packages.aerosandbox</li>
    <li>python311Packages.aerosandbox.dist</li>
    <li>python311Packages.aligator</li>
    <li>python311Packages.aligator.doc</li>
    <li>python311Packages.casadi</li>
    <li>python311Packages.crocoddyl</li>
    <li>python311Packages.crocoddyl.doc</li>
    <li>python311Packages.example-robot-data</li>
    <li>python311Packages.example-robot-data.doc</li>
    <li>python311Packages.neuralfoil</li>
    <li>python311Packages.neuralfoil.dist</li>
    <li>python311Packages.pinocchio</li>
    <li>python311Packages.pinocchio.doc</li>
    <li>python311Packages.proxsuite-nlp</li>
    <li>python311Packages.proxsuite-nlp.doc</li>
    <li>python311Packages.tsid</li>
    <li>python311Packages.tsid.doc</li>
    <li>python312Packages.aerosandbox</li>
    <li>python312Packages.aerosandbox.dist</li>
    <li>python312Packages.aligator</li>
    <li>python312Packages.aligator.doc</li>
    <li>python312Packages.casadi</li>
    <li>python312Packages.crocoddyl</li>
    <li>python312Packages.crocoddyl.doc</li>
    <li>python312Packages.example-robot-data</li>
    <li>python312Packages.example-robot-data.doc</li>
    <li>python312Packages.neuralfoil</li>
    <li>python312Packages.neuralfoil.dist</li>
    <li>python312Packages.pinocchio</li>
    <li>python312Packages.pinocchio.doc</li>
    <li>python312Packages.proxsuite-nlp</li>
    <li>python312Packages.proxsuite-nlp.doc</li>
    <li>python312Packages.tsid</li>
    <li>python312Packages.tsid.doc</li>
    <li>tsid</li>
    <li>tsid.doc</li>
  </ul>
</details>
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>bonmin</li>
    <li>ipopt</li>
    <li>mumps</li>
    <li>openturns</li>
    <li>python311Packages.openturns</li>
    <li>python311Packages.pygmo</li>
    <li>python312Packages.openturns</li>
    <li>python312Packages.pygmo</li>
  </ul>
</details>

**Comment by nim65s** [comment]
Result of `nixpkgs-review pr 350824` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>50 packages built:</summary>
  <ul>
    <li>aligator</li>
    <li>aligator.doc</li>
    <li>bonmin</li>
    <li>casadi</li>
    <li>crocoddyl</li>
    <li>crocoddyl.doc</li>
    <li>ipopt</li>
    <li>openturns</li>
    <li>pinocchio</li>
    <li>pinocchio.doc</li>
    <li>proxsuite-nlp</li>
    <li>proxsuite-nlp.doc</li>
    <li>python311Packages.aerosandbox</li>
    <li>python311Packages.aerosandbox.dist</li>
    <li>python311Packages.aligator</li>
    <li>python311Packages.aligator.doc</li>
    <li>python311Packages.casadi</li>
    <li>python311Packages.crocoddyl</li>
    <li>python311Packages.crocoddyl.doc</li>
    <li>python311Packages.example-robot-data</li>
    <li>python311Packages.example-robot-data.doc</li>
    <li>python311Packages.neuralfoil</li>
    <li>python311Packages.neuralfoil.dist</li>
    <li>python311Packages.openturns</li>
    <li>python311Packages.pinocchio</li>
    <li>python311Packages.pinocchio.doc</li>
    <li>python311Packages.proxsuite-nlp</li>
    <li>python311Packages.proxsuite-nlp.doc</li>
    <li>python311Packages.tsid</li>
    <li>python311Packages.tsid.doc</li>
    <li>python312Packages.aerosandbox</li>
    <li>python312Packages.aerosandbox.dist</li>
    <li>python312Packages.aligator</li>
    <li>python312Packages.aligator.doc</li>
    <li>python312Packages.casadi</li>
    <li>python312Packages.crocoddyl</li>
    <li>python312Packages.crocoddyl.doc</li>
    <li>python312Packages.example-robot-data</li>
    <li>python312Packages.example-robot-data.doc</li>
    <li>python312Packages.neuralfoil</li>
    <li>python312Packages.neuralfoil.dist</li>
    <li>python312Packages.openturns</li>
    <li>python312Packages.pinocchio</li>
    <li>python312Packages.pinocchio.doc</li>
    <li>python312Packages.proxsuite-nlp</li>
    <li>python312Packages.proxsuite-nlp.doc</li>
    <li>python312Packages.tsid</li>
    <li>python312Packages.tsid.doc</li>
    <li>tsid</li>
    <li>tsid.doc</li>
  </ul>
</details>

**Review by nim65s — APPROVED** [review]
That's amazing, thanks a lot !

**Comment by nim65s** [comment]
Result of `nixpkgs-review pr 350824` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>54 packages built:</summary>
  <ul>
    <li>aligator</li>
    <li>aligator.doc</li>
    <li>bonmin</li>
    <li>casadi</li>
    <li>crocoddyl</li>
    <li>crocoddyl.doc</li>
    <li>ipopt</li>
    <li>mumps</li>
    <li>openturns</li>
    <li>pagmo2</li>
    <li>pinocchio</li>
    <li>pinocchio.doc</li>
    <li>proxsuite-nlp</li>
    <li>proxsuite-nlp.doc</li>
    <li>python311Packages.aerosandbox</li>
    <li>python311Packages.aerosandbox.dist</li>
    <li>python311Packages.aligator</li>
    <li>python311Packages.aligator.doc</li>
    <li>python311Packages.casadi</li>
    <li>python311Packages.crocoddyl</li>
    <li>python311Packages.crocoddyl.doc</li>
    <li>python311Packages.example-robot-data</li>
    <li>python311Packages.example-robot-data.doc</li>
    <li>python311Packages.neuralfoil</li>
    <li>python311Packages.neuralfoil.dist</li>
    <li>python311Packages.openturns</li>
    <li>python311Packages.pinocchio</li>
    <li>python311Packages.pinocchio.doc</li>
    <li>python311Packages.proxsuite-nlp</li>
    <li>python311Packages.proxsuite-nlp.doc</li>
    <li>python311Packages.pygmo</li>
    <li>python311Packages.tsid</li>
    <li>python311Packages.tsid.doc</li>
    <li>python312Packages.aerosandbox</li>
    <li>python312Packages.aerosandbox.dist</li>
    <li>python312Packages.aligator</li>
    <li>python312Packages.aligator.doc</li>
    <li>python312Packages.casadi</li>
    <li>python312Packages.crocoddyl</li>
    <li>python312Packages.crocoddyl.doc</li>
    <li>python312Packages.example-robot-data</li>
    <li>python312Packages.example-robot-data.doc</li>
    <li>python312Packages.neuralfoil</li>
    <li>python312Packages.neuralfoil.dist</li>
    <li>python312Packages.openturns</li>
    <li>python312Packages.pinocchio</li>
    <li>python312Packages.pinocchio.doc</li>
    <li>python312Packages.proxsuite-nlp</li>
    <li>python312Packages.proxsuite-nlp.doc</li>
    <li>python312Packages.pygmo</li>
    <li>python312Packages.tsid</li>
    <li>python312Packages.tsid.doc</li>
    <li>tsid</li>
    <li>tsid.doc</li>
  </ul>
</details>

**Comment by qbisi** [comment]
I am going to create a separate mumps-par built with mpi and scalapack, the dependecy scalapack is broken on darwin,  mumps-par is a library and i would like to put it under pkgs/development/library

**Comment by nim65s** [comment]
Are you currently at nixcon ? It would be way easier to discuss this in person

**Comment by qbisi** [comment]
No, i am new to nix/nixpkgs/nixos. Maybe we can discuss this in matrix channel or telegram.

**Review by nim65s — CHANGES_REQUESTED** [review]
This should be closed in favor of #351476 now

**Pull request closed without merging**
