### PR TITLE
python3Packages.mautrix: 0.8.17 -> 0.9.2

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

https://github.com/tulir/mautrix-python/releases/tag/v0.9.2
https://github.com/tulir/mautrix-python/releases/tag/v0.9.1
https://github.com/tulir/mautrix-python/releases/tag/v0.9.0
https://github.com/tulir/mautrix-python/releases/tag/v0.8.18

Adds alot more optional dependencies.

Cherry-picked out of #123760.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Breaks the pinning of this library on both mautrix-telegram and mautrix-signal, but I guess we're not in a hurry anyway.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 123761` at 010a58fe run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/d6794981ec56222ff7a0ae0a0964f1d2">mautrix-signal</a></li>
    <li><a href="https://gist.github.com/9f18dcbf6090e911e3c34d6445b79a4c">mautrix-telegram</a></li>
  </ul>
</details>
<details>
  <summary>3 packages built successfully:</summary>
  <ul>
    <li>python38Packages.mautrix (python38Packages.mautrix-appservice)</li>
    <li>python39Packages.mautrix (python39Packages.mautrix-appservice)</li>
    <li>tests.trivial</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by Ma27** [comment]
Marking it as draft until the downstream applications have new releases supporting this release :)

**Comment by mweinelt** [comment]
@Ma27 I think mautrix-telegram allows newer mautrix versions by now. Are you interested in picking this PR up? 

https://github.com/mautrix/telegram/blob/v0.10.1/requirements.txt#L8

**Comment by mweinelt** [comment]
Obsolete.

**Pull request closed without merging**
