### PR TITLE
python3Packages.flask-babel: 2.0.0 -> 3.0.0

### PR DESCRIPTION
**Pull request by mweinelt**
https://github.com/python-babel/flask-babel/releases/tag/v3.0.0

Drop the duplicate package flaskbabel.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by dotlambda — CHANGES_REQUESTED** [review]
Please make sure to convert any use of `flaskbabel` in Nixpkgs.

**Comment by mweinelt** [comment]
> Please make sure to convert any use of `flaskbabel` in Nixpkgs.

Ah yeah, thanks for the reminder.

**Review by dotlambda — COMMENTED** [review]
I think it's fair to add @matejc to the flask-babel maintainers.

**Review by SuperSandro2000 — APPROVED** [review]
diff LGTM

**Comment by collares** [comment]
ofBorg tagged me, so: Since Sage 9.2, we no longer ship the deprecated sagenb package, and therefore a bunch of flask-* dependencies are no longer required by Sage. This is also the case for flask-babel. I will submit a clean-up PR to remove the Sage team from the maintainer list of those packages later.

**Comment by gador** [comment]
ok..So no one ran a `nixpkgs-review` here?
This update breaks pgadmin. Would have been nice to fix it up before this got merged

**Comment by NickCao** [comment]
Is https://github.com/NixOS/nixpkgs/pull/212982 gonna solve this?

**Comment by gador** [comment]
> Is #212982 gonna solve this? (Looks no)

No, unfortunately not.

Oh I see you wrote a patch, too

**Comment by gador** [comment]
I'm fine with either patch ;-)

**Comment by NickCao** [comment]
You are the maintainer, I would leave it to you.

**Comment by NickCao** [comment]
Located a few more regressions, really should have ran nixpkgs-review before merging, I'm handling it.

**Pull request merged**
