### PR TITLE
buildGoModule: use proxyVendor instead of runVend

### PR DESCRIPTION
**Pull request by zowoq**
###### Motivation for this change

`proxyVendor` provides the same functionality (with sightly worse performance) as `runVend` while also addressing another edge case (vendoring with case sensitivity problems). As there is currently only ~10 packages that use either of them there isn't much point in keeping both.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zowoq** [comment]
This PR just flips the switch and can go straight to master, I'll do docs + cleanup in follow up PRs as it'll trigger a rebuild of all `buildGoModule` packages.

**Comment by zowoq** [comment]
Some of these didn't even need `runVend`... I'll fix them on master so they can be dropped from this PR.

**Comment by zowoq** [comment]
Draft as another `runVend` has been added on master. 

I'll merge this in 24hrs, I'll make sure all packages are fixed then.

**Comment by zowoq** [comment]
@ofborg eval

**Comment by balsoft** [comment]
I'd like to note here that `proxyVend = true` didn't work as a "drop-in" replacement for `runVend` in case of a package I maintain (I get errors like `cannot find package "." in:`). I don't have the time or energy to debug this or why it's happpening, but for anyone else looking for a quick-and-dirty solution to get back the old behavior, just get the `vend` package somehow (e.g. pull an older nixpkgs revision) and then add

```
    overrideModAttrs = n: {
      postBuild = ''
        rm vendor -rf
        ${vend}/bin/vend
      '';
    };
```

to your `buildGoModule`.

**Pull request merged**
