### PR TITLE
bun: 1.1.34 -> 1.1.36

### PR DESCRIPTION
**Pull request by sandydoo**
###### Changelog
- https://github.com/oven-sh/bun/releases/tag/bun-v1.1.36
- https://bun.sh/blog/bun-v1.1.35

###### Updates performed
- Ran passthru.UpdateScript

###### To inspect upstream changes
- [Compare changes on GitHub](https://github.com/oven-sh/bun/compare/bun-v1.1.34...bun-v1.1.36)

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by sandydoo** [comment]
> ```
>        > Running phase: postPatchelf
>        > dyld[69576]: Symbol not found: _ubrk_clone
>        >   Referenced from: /nix/store/zz94xy01809rlwp70hakg5ws10acma3v-bun-1.1.36/bin/bun
>        >   Expected in: /usr/lib/libicucore.A.dylib
>        > /nix/store/nwvga652738sh96zj456ry0xfnh9sjzv-stdenv-darwin/setup: line 1725: 69576 Abort trap: 6           SHELL="bash" $out/bin/bun completions $completions_dir
>        For full logs, run 'nix log /nix/store/zhlf2ps8dp2khlk6xpyzhc0mnfif9m15-bun-1.1.36.drv'.
> ```
> 
> [oven-sh/bun#6035](https://github.com/oven-sh/bun/issues/6035)

Addressed in https://github.com/NixOS/nixpkgs/pull/358195

**Comment by pan93412** [comment]
v1.1.37 just released. How about bump to it? https://github.com/oven-sh/bun/releases/tag/bun-v1.1.37

**Comment by medv** [comment]
@pan93412 https://github.com/NixOS/nixpkgs/pull/359733

**Comment by sandydoo** [comment]
Closing in favour of https://github.com/NixOS/nixpkgs/pull/359733.

**Pull request closed without merging**
