### PR TITLE
pantalaimon, matrix-nio: update

### PR DESCRIPTION
**Pull request by symphorien**
##### Motivation for this change

update

changelog in commit message

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102278` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>pantalaimon</li>
    <li>weechatScripts.weechat-matrix</li>
  </ul>
</details>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>mirage-im</li>
    <li>python37Packages.matrix-nio</li>
    <li>python38Packages.matrix-nio</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102278` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>mirage-im</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>pantalaimon</li>
    <li>python37Packages.matrix-nio</li>
    <li>python38Packages.matrix-nio</li>
    <li>weechatScripts.weechat-matrix</li>
  </ul>
</details>

**Comment by symphorien** [comment]
@GrahamcOfBorg build mirage-im pantalaimon weechatScripts.weechat-matrix

builds fine here, let's see what ofborg says.

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102278` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>mirage-im</li>
    <li>pantalaimon</li>
    <li>python37Packages.matrix-nio</li>
    <li>python38Packages.matrix-nio</li>
    <li>weechatScripts.weechat-matrix</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
@symphorien still fails to build with the same error on darwin.

**Comment by symphorien** [comment]
As far as I can tell mirage-im has never built on darwin https://hydra.nixos.org/job/nixpkgs/trunk/mirage-im.x86_64-darwin/all

**Comment by DamienCassou** [comment]
The pantalaimon update works for me.

**Pull request merged**
