### PR TITLE
vimPlugins.lens-vim: init at 2020-04-24

### PR DESCRIPTION
**Pull request by ivankovnatsky**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sevenfourk** [comment]
weird thing:

```console
❯ GITHUB_API_TOKEN=[xx] ./update.py --add "camspiers/lens.vim"
HTTP Error 404: Not Found, Retrying in 3 seconds...
HTTP Error 404: Not Found, Retrying in 6 seconds...
HTTP Error 404: Not Found, Retrying in 12 seconds...
653 plugins were checked, 1 plugin(s) could not be downloaded:

vim-slime: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "./update.py", line 381, in prefetch
    plugin, redirect = prefetch_plugin(owner, repo, branch, alias, cache)
  File "./update.py", line 235, in prefetch_plugin
    commit, date = repo.latest_commit()
  File "./update.py", line 67, in f_retry
    return f(*args, **kwargs)
  File "./update.py", line 112, in latest_commit
    with urllib.request.urlopen(commit_req, timeout=10) as req:
  File "/nix/store/5aq2ix4vmk8bxs20ddqi48vc4bnk8zr5-python3-3.8.6/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/nix/store/5aq2ix4vmk8bxs20ddqi48vc4bnk8zr5-python3-3.8.6/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/nix/store/5aq2ix4vmk8bxs20ddqi48vc4bnk8zr5-python3-3.8.6/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/nix/store/5aq2ix4vmk8bxs20ddqi48vc4bnk8zr5-python3-3.8.6/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/nix/store/5aq2ix4vmk8bxs20ddqi48vc4bnk8zr5-python3-3.8.6/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/nix/store/5aq2ix4vmk8bxs20ddqi48vc4bnk8zr5-python3-3.8.6/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by SuperSandro2000** [comment]
I use ``GITHUB_API_TOKEN=$GITHUB_TOKEN ./pkgs/misc/vim-plugins/update.py --proc 10`` to regenerate the file.

**Comment by sevenfourk** [comment]
it feels like something wrong with: "jpalardy/vim-slime", but the repo is there, not really obvious what could that be.

**Comment by sevenfourk** [comment]
split into two commits for better trackability.

**Comment by onsails** [comment]
> weird thing:
> 
> ```
> ❯ GITHUB_API_TOKEN=[xx] ./update.py --add "camspiers/lens.vim"
> HTTP Error 404: Not Found, Retrying in 3 seconds...
> HTTP Error 404: Not Found, Retrying in 6 seconds...
> HTTP Error 404: Not Found, Retrying in 12 seconds...
> 653 plugins were checked, 1 plugin(s) could not be downloaded:
> 
> vim-slime: HTTP Error 404: Not Found
> Traceback (most recent call last):
>   File "./update.py", line 381, in prefetch
>     plugin, redirect = prefetch_plugin(owner, repo, branch, alias, cache)
>   File "./update.py", line 235, in prefetch_plugin
>     commit, date = repo.latest_commit()
>   File "./update.py", line 67, in f_retry
>     return f(*args, **kwargs)
>   File "./update.py", line 112, in latest_commit
>     with urllib.request.urlopen(commit_req, timeout=10) as req:
>   File "/nix/store/5aq2ix4vmk8bxs20ddqi48vc4bnk8zr5-python3-3.8.6/lib/python3.8/urllib/request.py", line 222, in urlopen
>     return opener.open(url, data, timeout)
>   File "/nix/store/5aq2ix4vmk8bxs20ddqi48vc4bnk8zr5-python3-3.8.6/lib/python3.8/urllib/request.py", line 531, in open
>     response = meth(req, response)
>   File "/nix/store/5aq2ix4vmk8bxs20ddqi48vc4bnk8zr5-python3-3.8.6/lib/python3.8/urllib/request.py", line 640, in http_response
>     response = self.parent.error(
>   File "/nix/store/5aq2ix4vmk8bxs20ddqi48vc4bnk8zr5-python3-3.8.6/lib/python3.8/urllib/request.py", line 569, in error
>     return self._call_chain(*args)
>   File "/nix/store/5aq2ix4vmk8bxs20ddqi48vc4bnk8zr5-python3-3.8.6/lib/python3.8/urllib/request.py", line 502, in _call_chain
>     result = func(*args)
>   File "/nix/store/5aq2ix4vmk8bxs20ddqi48vc4bnk8zr5-python3-3.8.6/lib/python3.8/urllib/request.py", line 649, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 404: Not Found
> ```

fixed in #106126

**Comment by sevenfourk** [comment]
@onsails thanks.

**Comment by sevenfourk** [comment]
updated.

**Comment by jonringer** [comment]
upstream is now broken
```
  E154: Duplicate tag "g:lens#animate" in file /nix/store/0pmg6qgp9mrj5cwwbm6yyq6haia31g2n-vimplugin-lens-vim-2020-04-24/share/vim-plugins/lens-vim/doc/lens.txtFailed to build help tags!
cannot build derivation '/nix/store/662vpbk71xczhjn1v71crhkh0v3vnca9-env.drv': 1 dependencies couldn't be built
[1 built (1 failed), 0.0 MiB DL]
error: build of '/nix/store/662vpbk71xczhjn1v71crhkh0v3vnca9-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/105810
1 package failed to build:
vimPlugins.lens-vim
```

**Comment by sevenfourk** [comment]
created pr: https://github.com/camspiers/lens.vim/pull/40/files

**Comment by SuperSandro2000** [comment]
If upstream takes to long you can add your commit with fetchpatches.

**Comment by sevenfourk** [comment]
@SuperSandro2000 got it.

**Comment by sevenfourk** [comment]
❯ nixpkgs-review pr 105810                                                                                                                                                                                                                 
2 packages built:
spacevim vimPlugins.lens-vim

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 105810 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>2 packages built:</summary>  <ul>    <li>spacevim</li>    <li>vimPlugins.lens-vim</li>  </ul></details>

**Pull request merged**
