### PR TITLE
trivy: 0.36.0 -> 0.36.1

### PR DESCRIPTION
**Pull request by fabaff**
Diff: https://github.com/aquasecurity/trivy/compare/v0.36.0...v0.36.1

Changelog: https://github.com/aquasecurity/trivy/releases/tag/v0.36.1

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 209730` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>trivy</li>
  </ul>
</details>

**Comment by stephank** [comment]
Result of `nixpkgs-review pr 209730` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>trivy</li>
  </ul>
</details>

This is the `installCheckPhase`:

```
running install tests
panic: open /etc/protocols: operation not permitted

goroutine 1 [running]:
modernc.org/libc/honnef.co/go/netdb.init.0()
	modernc.org/libc@v1.16.7/honnef.co/go/netdb/netdb.go:700 +0x780
```

It's not immediately obvious from the diff what's causing it to access `/etc/protocols`, but the sandbox is disallowing it. Maybe one of the dependency upgrades?

**Comment by 06kellyjac** [comment]
Hmmmmm, works fine on my linux box with all sandboxing on.
Does darwin even have an `/etc/protocols` just on the host outside of sandboxing?

**Comment by stephank** [comment]
Yes, it does have an `/etc/protocols`.

It looks like the difference is: the Linux sandbox has a very limited `/etc` without `/etc/protocols` causing `ENOENT`, while macOS can't chroot and instead limits access causing `EPERM`. The code only handles `ENOENT`: https://gitlab.com/cznic/libc/-/blob/bc4740f8667d1763148074e63f2e6f2e02a03daa/honnef.co/go/netdb/netdb.go#L699

There's a special flag `__darwinAllowLocalNetworking` that opens up the sandbox a bit, but not `/etc/protocols`. Maybe we can PR Nix to expand it, see if that fixes it.

For now, I guess we just have to disable the tests on Darwin? It's going to be a while before we can depend on a change in Nix.

**Review by stephank — APPROVED** [review]
Scratch that. I asked around and it looks like Hydra builders don't have the sandbox enabled on macOS. So this should be good to go as-is.

**Comment by fabaff** [comment]
Thanks guys, for the input on darwin.

**Pull request merged**
