### PR TITLE
paperless-ngx: adopt, 2.11.4 -> 2.11.6

### PR DESCRIPTION
**Pull request by SuperSandro2000**
## Description of changes

@lukegb @gador @erikarvstedt @Flakebi  please make yourself known if you want to keep the maintainer status in the next days

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by lukegb — APPROVED** [review]
Works for me, I haven't really had time to keep up with paperless. Thanks!

**Comment by Flakebi** [comment]
I’m still using it, but I don’t need to be a maintainer :)

**Comment by leona-ya** [comment]
I also opened an update PR that also updates nltk (#336802). I think wihout the nltk update it breaks, but not sure. I can also make that a seperate PR because it's a breaking change :unamused:

**Comment by erikarvstedt** [comment]
I run a fork of an older version of paperless, so I'm currently not tracking development of paperless-ngx.

But as its original author, I'm very familiar with the pkg and the module and was able to provide helpful feedback on architectural changes in the past. So it makes sense if I still get notified of new PRs.

**Comment by gador** [comment]
Hi @SuperSandro2000 I did some work upstream a bit ago, but haven't touched the upstream code in a while. I still use `paperless-ngx`, but I don't need to be a maintainer :+1:

**Review by erikarvstedt — APPROVED** [review]
- [x] `nixosTests.paperless` succeeds on `x86_64-linux`

**Pull request merged**
