### PR TITLE
libadwaita: 1.0.0-alpha.1 -> 1.0.0-alpha.2

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
https://gitlab.gnome.org/GNOME/libadwaita/-/blob/1.0.0-alpha.2/NEWS

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 131276` at c6e18173 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/a2873cf4f3e708868f393774f39ebc5c">gnome.gnome-todo</a></li>
    <li><a href="https://gist.github.com/beec4f9909731d2a56a02011c054c076">kooha</a></li>
    <li><a href="https://gist.github.com/7eb150caa8c5669362315ee2c706b752">libadwaita</a></li>
    <li><a href="https://gist.github.com/a75a71ee2066ef0cb4f036cfff05533d">mousai</a></li>
    <li><a href="https://gist.github.com/1fa045bb3d7184c3599c7c620ca2afb5">notejot</a></li>
    <li><a href="https://gist.github.com/a8a51600b61928969c5f07cf45fbc1d7">shortwave</a></li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Review by SuperSandro2000 — APPROVED** [review]
diff LGTM

**Comment by dotlambda** [comment]
The failure on aarch64 seems to be new. I'll investigate.

**Review by davidak — APPROVED** [review]
Change looks good

Builds, runs

waiting for aarch64 build status before merge

**Comment by bobby285271** [comment]
Any updates? libadwaita 1.0.0-alpha.2 is needed for updating `khronos` (1.0.8 -> 3.5.7), otherwise `khronos` will fail to build with:

```
../src/MainWindow.vala:45.16-45.36: error: The type name `Adw.ViewStack' could not be found
        public unowned Adw.ViewStack title_stack;
               ^^^^^^^^^^^^^^^^^^^^^
../src/MainWindow.vala:47.16-47.36: error: The type name `Adw.ViewStack' could not be found
        public unowned Adw.ViewStack win_stack;
```

**Comment by dotlambda** [comment]
@ofborg build mousai

**Pull request merged**
