### PR TITLE
erlangR18: 18.0 -> 18.2

### PR DESCRIPTION
**Pull request by ericsagnes**
[Release informations](http://www.erlang.org/news/97)

### CODE REVIEW

**Comment by couchemar** [comment]
Just checked (nox-review) with nixpkgs-unstable (3087ef3), builds and works fine.
Can not check against master at this moment...

**Comment by sjmackenzie** [comment]
@couchemar what was your exact command please? did you run `nox-review` in the `nixpkgs` dir? How does one point `nox-review` to a specific rev of a specific repo?

**Comment by couchemar** [comment]
@sjmackenzie something like this:
```
$ nix-instantiate --find-file nixpkgs
/nix/store/00qrfml0jvhg52asi1ilkn33sjanl5ac-nixpkgs-16.03pre71923.3087ef3/nixpkgs
$ cd nixpkgs
$ git checkout 3087ef3 # my nixpkgs-unstable reference
$ hub fetch ericsagnes update/erlang # fetch this pull request branch using (https://hub.github.com/)
$ git log ericsagnes/update/erlang
commit b67ac40a8230e2e16ed66f5bb01f0e3f94b2780a
Author: Eric Sagnes <eric.sagnes@gmail.com>
Date:   Thu Dec 17 09:01:49 2015 +0900

    erlangR18: 18.0 -> 18.2
$ git cherry-pick --no-commit b67ac40a8230e2e16ed66f5bb01f0e3f94b2780a
$ now-review wip
```

**Comment by sjmackenzie** [comment]
cheers mate - thanks

**Pull request merged**
