### PR TITLE
 nixos/systemd-boot: Add support for an XBOOTLDR partition

### PR DESCRIPTION
**Pull request by sdht0**
## Description of changes

Continuation of PR #260241 which I closed inadvertently.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by sdht0** [comment]
@nikstur @RaitoBezarius ideally qemu-vm should provide an option to override the `systemImage`. However, I avoided making any changes and indirectly used `useBootLoader=false` option as a workaround.

**Comment by sdht0** [comment]
@nikstur @RaitoBezarius gentle ping

**Comment by sdht0** [comment]
@nikstur @RaitoBezarius can you please take a look at the last blocker for this PR? Specifically [these lines](https://github.com/NixOS/nixpkgs/pull/285401/files#diff-f71ea5f910763bce18731f20cfb7fa3c6f31d4ebecf3a37c75cf410858b5bb53R31-R35).

**Comment by nikstur** [comment]
Looks good from my side.

**Comment by sdht0** [comment]
Thanks.

@ElvishJerricco @JulienMalka can we merge this then?

cc @RaitoBezarius

**Comment by JulienMalka** [comment]
@ofborg test systemd-boot

**Comment by sdht0** [comment]
Fixed a merge conflict.

**Comment by sdht0** [comment]
@ofborg test systemd-boot

**Review by ElvishJerricco — APPROVED** [review]
LGTM. @RaitoBezarius shall we merge?

**Review by RaitoBezarius — APPROVED** [review]

**Comment by RaitoBezarius** [comment]
Let's go, I want to say that @sdht0 you have been incredibly patient with us, I would like to point out this is something I rarely see in nixpkgs contributions and a big big big thank you, this has been a very pleasant experience for me to review, even beyond the disagreements.

**Comment by colemickens** [comment]
Very cool that (the original accidentally closed) PR was your first PR in nixpkgs, @sdht0! Quite a cool first contribution, and more already since then. :sunglasses: :rocket:

**Pull request merged**
