### PR TITLE
libdvdcss: 1.3.0 -> 1.3.99

### PR DESCRIPTION
**Pull request by AndersonTorres**

### CODE REVIEW

**Comment by codyopel** [comment]
@AndersonTorres 
Is there a reason why you're updating to a test release instead of using stable 1.3.0?
http://git.videolan.org/?p=libdvdcss.git;a=tag;h=10e1add99897d767bc6522220f25b8f90efbf7f5
This is a pre-1.4.0 release.

**Comment by AndersonTorres** [comment]
Well, I just followed the monitor.nixos.org status. But I didn't notice it is a pre-release.

**Comment by vcunat** [comment]
If there isn't a specific reason to take this version, I think it's better to wait for a proper release.

**Comment by AndersonTorres** [comment]
OK, just wait :)

**Comment by MP2E** [comment]
Closing issue to clean up our PRs a bit, please reopen if needed

**Pull request closed without merging**
