### PR TITLE
nixos/acme: improve some descriptions

### PR DESCRIPTION
**Pull request by tomcur**
###### Motivation for this change
In the ACME module documentation: make some links explicit and improve description consistency.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by drewrisinger — COMMENTED** [review]
Improvements look good to me, though I honestly don't know enough about ``<link>`` tags (XML??) to comment on that part.

**Comment by Beskhue** [comment]
@drewrisinger I've not seen documentation on it, but such links are rendered as actual links on e.g. https://nixos.org/nixos/options.html.

**Comment by drewrisinger** [comment]
Found a random example.
https://github.com/NixOS/nixpkgs/blob/8a061ebdef44864b835a1b6b4baf83931274c962/nixos/modules/security/duosec.nix#L75

**Comment by drewrisinger** [comment]
Found a random example.
https://github.com/NixOS/nixpkgs/blob/8a061ebdef44864b835a1b6b4baf83931274c962/nixos/modules/security/duosec.nix#L75

**Comment by drewrisinger** [comment]
Looks like your links fit the format, so changing to approval.

**Review by drewrisinger — APPROVED** [review]
Link format LGTM based on other examples. Diff LGTM

**Comment by marsam** [comment]
Thanks!

**Pull request merged**
