### PR TITLE
mirrors: more imagemagick mirrors

### PR DESCRIPTION
**Pull request by cheecheeo**
This is more-or-less the mirrors modifications from #8302.

### CODE REVIEW

**Comment by lethalman** [comment]
cc @vcunat

**Comment by edolstra** [comment]
Given that this is used by only one package, why have this in mirrors.nix at all? We can just do
```
src = fetchurl {
  urls = [ url1 url2 ... ];
  ...
};
```
in the ImageMagick Nix expression.

(Actually, the `libfpx` package also uses mirror://imagemagick/, but it refers to a `delegates` subdirectory that apparently doesn't exist on these mirrors.)

**Comment by cheecheeo** [comment]
@edolstra Interesting find, it looks like more investigation is needed. I'll try and track down mirrors that have both the imagemagick tarball and a delegates directory and update this pull request accordingly.

**Comment by cheecheeo** [comment]
Please take another look.

**Comment by vcunat** [comment]
Looks good to me. I don't think we need many mirrors for these, but it shouldn't make anything worse.

**Comment by cheecheeo** [comment]
@vcunat thanks!

**Pull request closed without merging**
