### PR TITLE
Don't use the 'nix' command

### PR DESCRIPTION
**Pull request by edolstra**
###### Motivation for this change

In Nix 2.4, the `nix` command requires `experimental-features = nix-command` in `nix.conf`. So we can't use it in `nixos-install` or in the activation script yet.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [X] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tfc** [comment]
The changes in the python driver look like drive-by changes, or do they fix some kind of concrete problem that you ran into?

**Comment by edolstra** [comment]
Yes, without them the installer test hangs.

**Comment by tfc** [comment]
The changes look innocent so i'd have no objections merging them but i am interested in understanding how the pre-allocated queue size or the end-pattern blocked this specific test while they work on more than 200 other tests.

**Comment by edolstra** [comment]
Probably because they don't write more than 1000 lines to the serial console between commands.

**Comment by LnL7** [comment]
Can this also be backported to 19.09 or will it also require fixes for the tests there?

**Pull request merged**
