### PR TITLE
nixos/wireplumber: start wireplumber after xdg-deskop-portal if enabled

### PR DESCRIPTION
**Pull request by jnsgruk**
###### Description of changes

A simple change that ensures that if `xdg-desktop-portal` is enabled in system config, then wireplumber is started after it. On all my machines, I get the following journal messages on each boot:

```
Apr 20 13:46:28 loki wireplumber[2477]: Can't find org.freedesktop.portal.Desktop. Is xdg-desktop-portal running?
Apr 20 13:46:28 loki wireplumber[2477]: found session bus but no portal
```

After this change, I no longer see this issue. I do still see errors like so, but will target those in another PR:

```
Apr 20 13:46:30 loki wireplumber[2477]: <WpPortalPermissionStorePlugin:0x4c7c40> Failed to call Lookup: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for camera
```

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by K900** [comment]
Is the issue just log noise? It should be able to reconnect to the portal even if started early.

**Comment by jnsgruk** [comment]
Hey, yeh I haven't noticed any particular degradation in the functionality, just a bunch of log messages on every boot.

**Review by RaitoBezarius — APPROVED** [review]
Looks sane but I'd appreciate if @K900 validated this change as he's the pipewire person :D.

**Comment by K900** [comment]
The change itself seems OK, but I don't really see why we should add another serialization point to the startup process just to avoid one racy log message.

**Comment by jnsgruk** [comment]
Fair enough - if this isn't really a problem I guess it's fine to just close this. It seemed odd to me that we wouldn't just start wireplumber once everything it needs is up and running, but I'm by no means an expert on this particular stack :)

**Comment by K900** [comment]
It doesn't really need the portal to _start_, the portal is basically used for screen capture access for apps and not much else.

**Pull request closed without merging**
