### PR TITLE
New package: xbindkeys-config

### PR DESCRIPTION
**Pull request by benley**
The patch is borrowed verbatim from Debian. It is under the same license as the rest of the package, and is necessary for the app to work.

There does not seem to be a canonical upstream homepage for this app other than Debian itself.

[Review on Reviewable](https://reviewable.io/reviews/nixos/nixpkgs/6252)

### CODE REVIEW

**Comment by lethalman** [comment]
It's weird but I use xbindkeys everyday. What's actually not working?

**Comment by lethalman** [comment]
Ok was very confused by the PR sorry in the previous comment. Can you please create a different directory for this xbindkeys-config? It's a different codebase, it must not be in the xbindkeys directory. Thanks.

**Comment by benley** [comment]
Sure, not a problem.  I moved it to a separate directory, adjacent to xbindkeys.

**Comment by lethalman** [comment]
Travis passed, thanks.

**Pull request merged**
