### PR TITLE
rlottie: 0.1 -> 0.2

### PR DESCRIPTION
**Pull request by musfay**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

rlottie is not `unfree`. Debian and Fedora also puts it into their main repos.

### CODE REVIEW

**Comment by musfay** [comment]
Result of `nixpkgs-review pr 125942` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>lottieconverter</li>
    <li>rlottie</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 125942` at 642dce49 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>lottieconverter</li>
    <li>rlottie</li>
  </ul>
</details>

**Review by risicle — APPROVED** [review]
`nixpkgs-review` reveals no new failures, macos 10.15, nixos x86_64

(btw `lottieconverter` fails on macos with `g++: command not found`, so probably just needs the normal fix to substitute `stdenv.cc`)

**Review by CRTified — APPROVED** [review]

**Comment by CRTified** [comment]
Result of `nixpkgs-review pr 125942` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>lottieconverter</li>
    <li>rlottie</li>
  </ul>
</details>

**Comment by tomberek** [comment]
Result of `nixpkgs-review pr 125942` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>lottieconverter</li>
    <li>rlottie</li>
  </ul>
</details>

**Comment by tomberek** [comment]
> `nixpkgs-review` reveals no new failures, macos 10.15, nixos x86_64
> 
> (btw `lottieconverter` fails on macos with `g++: command not found`, so probably just needs the normal fix to substitute `stdenv.cc`)

make new PR for lottieconverter?

**Pull request merged**
