### PR TITLE
lowdown: 0.8.5 -> 0.8.6

### PR DESCRIPTION
**Pull request by sternenseemann**
https://github.com/kristapsdz/lowdown/blob/b4483d0ef85990f54b864158ab786b4a5b3904fa/versions.xml#L1112-L1125

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
@ofborg build nixUnstable

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 133007` at d1c0ed87 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built successfully:</summary>
  <ul>
    <li>hydra-unstable</li>
    <li>lowdown</li>
    <li>nix-update</li>
    <li>nixUnstable</li>
    <li>nixpkgs-review</li>
  </ul>
</details>

**Comment by risicle** [comment]
`nixpkgs-review` happy, macos 10.15 & nixos x86_64

**Comment by SuperSandro2000** [comment]
@ofborg build nixUnstable nix

**Pull request merged**
