### PR TITLE
Add devcontainer CLI

### PR DESCRIPTION
**Pull request by joshspicer**
## Description of changes

Adds the devcontainer CLI, an open specification development environment project started by Microsoft. 

The dev container specification is utilized by VS Code's 'Dev Containers' extension, GitHub Codespaces, and [more](https://containers.dev/supporting).

The source code for the project can be found on GitHub: https://github.com/devcontainers/cli.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Janik-Haag — COMMENTED** [review]
Hi, thank you for your contribution. 
You probably want to add the package like described in https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/javascript.section.md#adding-and-updating-javascript-packages-in-nixpkgs-javascript-adding-or-updating-packages (yes I know running the generate.sh takes a horrific amount of time..) and remove `devcontainer/package.nix`

**Comment by joshspicer** [comment]
Hi @Janik-Haag - the [documentation here](https://github.com/NixOS/nixpkgs/tree/master/pkgs#quick-start-to-adding-a-package) makes it sounds like they direction i've gone is the current way to go about this - is that not true?

Also, I had a really tough time getting the aliasing working and all the examples I looked at seems overly complicated (eg `bitwarden-cli` is tied to another package somehow?).  Do I need to add to `all-packages.nix` in this case?  How do I accomplish the same thing i'm doing here (alias to a usable package name like `devcontainer` and not `nodePackages_@devcontainers/cli`)?

**Comment by joshspicer** [comment]
Hey there! I've tried your suggestion, moving the package under nodePackages (ie `nodePackages.devcontainer).

https://github.com/NixOS/nixpkgs/commit/1710736a01597fdebfe415148366fbf9e40a6ef6

Can't seem to get it to build though, with the error citing:

```
nix-build -A nodePackages.devcontainer --verbose

...
downloading 'https://cache.nixos.org/nar/1v7147l9i77r708g125cncjm59drgbq6s36g5f6npgc420hhw7f4.nar.xz'...
copying path '/nix/store/16mv7ipba73qn6aads1r2x3vm11bq12x-gnupg-2.4.1' from 'https://cache.nixos.org'...
downloading 'https://cache.nixos.org/nar/0pahzhla94vkv035yi655rqmfx6fmdksrj6iqx4sw8vyvffw7ccd.nar.xz'...
error: suspicious ownership or permission on '/nix/store/28f0dqyzdh5c7myng0n0a7jp2xyc8l9f-addintegrityfields.js' for output 'out'; rejecting this build output
error: 1 dependencies of derivation '/nix/store/jpk8n8h3y7wxqs0idb927b6j8hlwa4ii-devcontainer-0.55.0.drv' failed to build
```

Any idea what needs to be done here?  Strange that i'm not repro'ing with my approach above

**Comment by WolfangAukang** [comment]
@Janik-Haag wouldn't it be better to use (for this specific case) `mkYarnPackage` instead of adding it to the `nodePackages`? I ask this because this is a CLI application that could be added to the packages list as usual, and because there has been an effort of using `buildNpmPackage` and `mkYarnPackage` instead.

@joshspicer I was able to build it by pulling from source:
```
{ lib
, mkYarnPackage
, fetchFromGitHub
, fetchYarnDeps
}:

mkYarnPackage rec {
  pname = "devcontainers";
  version = "0.55.0";

  src = fetchFromGitHub {
    owner = "devcontainers";
    repo = "cli";
    rev = "v${version}";
    hash = "sha256-NrN9q8pa9MQWea1MOyQYZMudf1byEX44rgYqiK8qYnQ=";
  };

  yarnLock = "${src}/yarn.lock";
  packageJSON = ./package.json;

  offlineCache = fetchYarnDeps {
    inherit yarnLock;
    hash = "sha256-puKgUp24IdbAKaBayFxVgIiS4vZHSMVjC+WdUS7yvbs=";
  };

  buildPhase = ''
    runHook preBuild

    yarn --offline compile

    runHook postBuild
  '';

}
```

I didn't add the `meta` part, and it needs the `package.json` committed to nixpkgs. But can you please check if it works for you?

**Comment by joshspicer** [comment]
Hi @WolfangAukang, thanks for taking a look!  I like your approach of cloning directly.  Unfortunately i'm running into missing `node-pty` errors:

Here's how to repro:

```
@joshspicer ➜ /nix/store $ cd /nix/store/1psi4mp48ldkzrlkbniyxwmmzd8vislc-devcontainers-cli-0.55.0/

@joshspicer ➜ /nix/store/1psi4mp48ldkzrlkbniyxwmmzd8vislc-devcontainers-cli-0.55.0 $ ls
bin  libexec  tarballs

@joshspicer ➜ /nix/store/1psi4mp48ldkzrlkbniyxwmmzd8vislc-devcontainers-cli-0.55.0 $ cat /workspaces/example/.devcontainer.json 
{
    "image": "mcr.microsoft.com/devcontainers/base"
}

@joshspicer ➜ /nix/store/1psi4mp48ldkzrlkbniyxwmmzd8vislc-devcontainers-cli-0.55.0 $ 
bin/devcontainer up --workspace-folder /workspaces/example/
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /nix/store/1psi4mp48ldkzrlkbniyxwmmzd8vislc-devcontainers-cli-0.55.0/libexec/@devcontainers/cli/node_modules/node-pty/lib/unixTerminal.js
- /nix/store/1psi4mp48ldkzrlkbniyxwmmzd8vislc-devcontainers-cli-0.55.0/libexec/@devcontainers/cli/node_modules/node-pty/lib/index.js
- /nix/store/1psi4mp48ldkzrlkbniyxwmmzd8vislc-devcontainers-cli-0.55.0/libexec/@devcontainers/cli/deps/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js
- /nix/store/1psi4mp48ldkzrlkbniyxwmmzd8vislc-devcontainers-cli-0.55.0/libexec/@devcontainers/cli/deps/@devcontainers/cli/devcontainer.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/nix/store/1psi4mp48ldkzrlkbniyxwmmzd8vislc-devcontainers-cli-0.55.0/libexec/@devcontainers/cli/node_modules/node-pty/lib/unixTerminal.js:34:15)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/nix/store/1psi4mp48ldkzrlkbniyxwmmzd8vislc-devcontainers-cli-0.55.0/libexec/@devcontainers/cli/node_modules/node-pty/lib/unixTerminal.js',
    '/nix/store/1psi4mp48ldkzrlkbniyxwmmzd8vislc-devcontainers-cli-0.55.0/libexec/@devcontainers/cli/node_modules/node-pty/lib/index.js',
    '/nix/store/1psi4mp48ldkzrlkbniyxwmmzd8vislc-devcontainers-cli-0.55.0/libexec/@devcontainers/cli/deps/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js',
    '/nix/store/1psi4mp48ldkzrlkbniyxwmmzd8vislc-devcontainers-cli-0.55.0/libexec/@devcontainers/cli/deps/@devcontainers/cli/devcontainer.js'
  ]
}
``` 

I spent a bit of time trying to follow some of the docs in [packaging with `node-gyp`](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/javascript.section.md#javascript-packages-inside-nixpkgs-javascript-packages-nixpkgs), effectively adding `nativeBuildInputs = [ nodejs.pkgs.node-pre-gyp nodejs.pkgs.node-gyp-build ];`, but I haven't been able to pinpoint it yet.  Seems fixable though - any ideas?

Full source to get that repro above: https://github.com/NixOS/nixpkgs/commit/98f5161b57366055b162674bfa4898189ce1bcc1

**Comment by WolfangAukang** [comment]
This is where my knowledge falls short. My recommendation would be pinging the folks at [Matrix](https://app.element.io/#/room/#nodejs:nixos.org) dedicated to NodeJS to see what can be done in this case.

**Comment by sikmir** [comment]
Done in #301313

**Pull request closed without merging**
