### PR TITLE
dbeaver: 22.2.2 -> 23.0.4

### PR DESCRIPTION
**Pull request by RohanHart**
###### Description of changes

Update to 23.0.4 with pinned dependencies to avoid issues like #213199 and #198222

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by RohanHart** [comment]
It seems there's still something in the dependencies which is not pinned. Unfortunately it's a very complex build

**Comment by RohanHart** [comment]
The Tycho plugin depends on `org.eclipse.equinox.p2.transport.ecf` which has version-ranged dependencies. Not sure how to pin such a deep transitive dependency

**Comment by RohanHart** [comment]
It seems that @samueldr's change provides a hint as to how to obtain a prebuilt Tycho https://gitlab.com/samueldr/nixos-configuration/blob/4f0ddd6b25082ebb69a80c0f42af2bba687b56e0/overlays/samueldr/pkgs/applications/misc/dbeaver/__source-based.nix#L67
See also #34182

**Comment by wegank** [comment]
@ofborg build dbeaver dbeaver.passthru.tests

**Comment by robsliwi** [comment]
Stumbled across this one today and have seen that there is a newer version of dbeaver out, here a PR that bumps it to the newest one without any additional patches necessary (at least locally): https://github.com/NixOS/nixpkgs/pull/249293

**Comment by RohanHart** [comment]
Those additional patches weren't required to build locally either as long as the dependencies don't change between builds. The Tycho plugin hasn't been updated in DBeaver for a while and these open dependencies from https://mvnrepository.com/artifact/org.eclipse.platform/org.eclipse.equinox.p2.transport.ecf/1.3.300 will likely break any build because new versions come out all the time.

**Pull request closed without merging**
