### PR TITLE
buho: init at 2.1.1

### PR DESCRIPTION
**Pull request by onny**
###### Motivation for this change
This PR packages the note taking app [buho](https://invent.kde.org/maui/buho) including mauikit dependencies.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by onny** [comment]
Hm I'm able to run the application but somehow the icons are missing :(

image

**Comment by AndersonTorres** [comment]
Three independent packages modifying five frakking files, and you did it in only one commit?

Please split them accordingly.

In case you need documentation help: 

https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History
https://emmanuelbernard.com/blog/2014/04/14/split-a-commit-in-two-with-git/
https://stackoverflow.com/questions/6217156/break-a-previous-commit-into-multiple-commits

**Comment by onny** [comment]
> Hm I'm able to run the application but somehow the icons are missing :(
> 
> image

@dotlambda Does the Mauikit app `index-fm` is working for you including styling? For me icons etc is missing :(

**Comment by AndersonTorres** [comment]
Usually the missing icons imply that the app expects the icons in a certain place, however that place does not exist. Sometimes it can be solved by wrapping the app, setting some environment variable in order to tell the app where are the icons.

**Comment by onny** [comment]
The app is now compiling and running fine for me, ready for review :)

**Comment by dotlambda** [comment]
> @dotlambda Does the Mauikit app `index-fm` is working for you including styling? For me icons etc is missing :(

No, icons are also missing for me. I've stopped worrying about that though as I don't run KDE and just hope that it works on Plasma. But even if that's not the case I'm not motived enough to dig into the issue.

**Comment by dotlambda** [comment]
Missing icons might be related to https://bugs.kde.org/show_bug.cgi?id=435236

**Review by dotlambda — CHANGES_REQUESTED** [review]
Please split into three commits.

**Comment by onny** [comment]
I solved the issue with missing icons, see here https://github.com/NixOS/nixpkgs/issues/168102
Good point in splitting the commits, I‘ll do this tomorrow :)

**Comment by onny** [comment]
New PRs for dependencies / required libraries:
- mauikit-accounts https://github.com/NixOS/nixpkgs/pull/170110
- mauikit-texteditor https://github.com/NixOS/nixpkgs/pull/170112

**Comment by dotlambda** [comment]
No need for three PRs, just three commits in this PR.

**Comment by dotlambda** [comment]
@AndersonTorres Excuse me??

**Comment by dotlambda** [comment]
@grahamc Why did ofborg not color things red here?
```
error: Function called without required argument "mauikit-accounts"
```

**Comment by dotlambda** [comment]
> @grahamc Why did ofborg not color things red here?
> 
> ```
> error: Function called without required argument "mauikit-accounts"
> ```

@cole-h Could you have a look?

**Pull request merged**
