### PR TITLE
grpc: 1.37.1 -> 1.38.0

### PR DESCRIPTION
**Pull request by marsam**
###### Motivation for this change

https://github.com/grpc/grpc/releases/tag/v1.38.0
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 123855` at 99a856c4 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>55 packages marked as broken and skipped:</summary>
  <ul>
    <li>python38Packages.arviz</li>
    <li>python38Packages.dm-sonnet</li>
    <li>python38Packages.graph_nets</li>
    <li>python38Packages.ignite</li>
    <li>python38Packages.optuna</li>
    <li>python38Packages.pymc3</li>
    <li>python38Packages.pytorchWithCuda</li>
    <li>python38Packages.pywick</li>
    <li>python38Packages.rl-coach</li>
    <li>python38Packages.shap</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>7 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/da26574f7282ab06862dbca7a3741a1a">bear</a></li>
    <li>home-assistant</li>
    <li><a href="https://gist.github.com/add7acbacf65bc36a8924425f0313ee9">murmur</a></li>
    <li><a href="https://gist.github.com/10969e15a77449a4c2c6baae1332f959">python38Packages.cirq</a></li>
    <li><a href="https://gist.github.com/a2edef1d8439e8fd5b17dfdc1e23c0d7">python38Packages.cirq-google</a></li>
    <li><a href="https://gist.github.com/b245a7d65ed952fa67dad8be42c59491">python39Packages.cirq</a></li>
    <li><a href="https://gist.github.com/fa7a797aa9b7aaad54a61d90699d1e21">python39Packages.cirq-google</a></li>
  </ul>
</details>
<details>
  <summary>37 packages skipped due to time constraints:</summary>
  <ul>
    <li>kmymoney</li>
    <li>python38Packages.baselines</li>
    <li>python38Packages.edward</li>
    <li>python38Packages.mask-rcnn</li>
    <li>python38Packages.pyro-ppl</li>
    <li>python38Packages.pytorch (python38Packages.pytorchWithoutCuda)</li>
    <li>python38Packages.pytorch-lightning</li>
    <li>python38Packages.pytorch-metric-learning</li>
    <li>python38Packages.rising</li>
    <li>python38Packages.scikit-tda</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>98 packages built successfully:</summary>
  <ul>
    <li>beancount (python38Packages.beancount)</li>
    <li>cinnamon.warpinator</li>
    <li>deja-dup</li>
    <li>duplicity</li>
    <li>duply</li>
    <li>dvc-with-remotes</li>
    <li>fava</li>
    <li>gcalcli</li>
    <li>git-annex-remote-googledrive</li>
    <li>grpc</li>
    <li>ledger2beancount</li>
    <li>lieer</li>
    <li>lndmanage</li>
    <li>opensnitch-ui</li>
    <li>python38Packages.beancount_docverif</li>
    <li>python38Packages.chirpstack-api</li>
    <li>python38Packages.drivelib</li>
    <li>python38Packages.goobook</li>
    <li>python38Packages.google-api-core</li>
    <li>python38Packages.google-api-python-client</li>
    <li>python38Packages.google-cloud-access-context-manager</li>
    <li>python38Packages.google-cloud-asset</li>
    <li>python38Packages.google-cloud-automl</li>
    <li>python38Packages.google-cloud-bigquery</li>
    <li>python38Packages.google-cloud-bigquery-datatransfer</li>
    <li>python38Packages.google-cloud-bigtable</li>
    <li>python38Packages.google-cloud-container</li>
    <li>python38Packages.google-cloud-core</li>
    <li>python38Packages.google-cloud-dataproc</li>
    <li>python38Packages.google-cloud-datastore</li>
    <li>python38Packages.google-cloud-dlp</li>
    <li>python38Packages.google-cloud-dns</li>
    <li>python38Packages.google-cloud-error-reporting</li>
    <li>python38Packages.google-cloud-firestore</li>
    <li>python38Packages.google-cloud-iam</li>
    <li>python38Packages.google-cloud-iot</li>
    <li>python38Packages.google-cloud-kms</li>
    <li>python38Packages.google-cloud-language</li>
    <li>python38Packages.google-cloud-logging</li>
    <li>python38Packages.google-cloud-monitoring</li>
    <li>python38Packages.google-cloud-org-policy</li>
    <li>python38Packages.google-cloud-os-config</li>
    <li>python38Packages.google-cloud-pubsub</li>
    <li>python38Packages.google-cloud-redis</li>
    <li>python38Packages.google-cloud-resource-manager</li>
    <li>python38Packages.google-cloud-runtimeconfig</li>
    <li>python38Packages.google-cloud-secret-manager</li>
    <li>python38Packages.google-cloud-securitycenter</li>
    <li>python38Packages.google-cloud-spanner</li>
    <li>python38Packages.google-cloud-speech</li>
    <li>python38Packages.google-cloud-storage</li>
    <li>python38Packages.google-cloud-tasks</li>
    <li>python38Packages.google-cloud-texttospeech</li>
    <li>python38Packages.google-cloud-trace</li>
    <li>python38Packages.google-cloud-translate</li>
    <li>python38Packages.google-cloud-videointelligence</li>
    <li>python38Packages.google-cloud-vision</li>
    <li>python38Packages.google-cloud-websecurityscanner</li>
    <li>python38Packages.googleapis-common-protos</li>
    <li>python38Packages.grpc_google_iam_v1</li>
    <li>python38Packages.grpcio</li>
    <li>python38Packages.grpcio-gcp</li>
    <li>python38Packages.grpcio-tools</li>
    <li>python38Packages.oauthenticator</li>
    <li>python38Packages.pathy</li>
    <li>python38Packages.proto-plus</li>
    <li>python38Packages.pydrive</li>
    <li>python38Packages.weboob</li>
    <li>python38Packages.woob</li>
    <li>python39Packages.beancount</li>
    <li>python39Packages.beancount_docverif</li>
    <li>python39Packages.chirpstack-api</li>
    <li>python39Packages.drivelib</li>
    <li>python39Packages.goobook</li>
    <li>python39Packages.google-api-core</li>
    <li>python39Packages.google-api-python-client</li>
    <li>python39Packages.google-cloud-access-context-manager</li>
    <li>python39Packages.google-cloud-bigtable</li>
    <li>python39Packages.google-cloud-core</li>
    <li>python39Packages.google-cloud-dns</li>
    <li>python39Packages.google-cloud-firestore</li>
    <li>python39Packages.google-cloud-logging</li>
    <li>python39Packages.google-cloud-org-policy</li>
    <li>python39Packages.google-cloud-resource-manager</li>
    <li>python39Packages.google-cloud-runtimeconfig</li>
    <li>python39Packages.google-cloud-trace</li>
    <li>python39Packages.google-cloud-videointelligence</li>
    <li>python39Packages.googleapis-common-protos</li>
    <li>python39Packages.grpc_google_iam_v1</li>
    <li>python39Packages.grpcio</li>
    <li>python39Packages.grpcio-gcp</li>
    <li>python39Packages.grpcio-tools</li>
    <li>python39Packages.oauthenticator</li>
    <li>python39Packages.proto-plus</li>
    <li>python39Packages.pydrive</li>
    <li>python39Packages.weboob</li>
    <li>python39Packages.woob</li>
    <li>wal_e</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/grpcio-tools/default.nix:27:5:
```
   |
27 |     maintainers = with maintainers; [ ];
   |     ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by gebner** [comment]
Are you sure that grpc 1.38 is supposed to work with the current abseil version?  The grpc pkg-config files require `absl_base` and more, but our abseil version doesn't even provide pkg-config files.

This breaks at least `bear`.  Upgrading abseil fixes this.  #124030

**Comment by mweinelt** [comment]
I bisected the murmur breakage to this merge request:

```
04e18727c4f1797b00e9505ac9185a38c764e0f1 is the first bad commit
commit 04e18727c4f1797b00e9505ac9185a38c764e0f1
Author: Mario Rodas <marsam@users.noreply.github.com>
Date:   Thu May 20 04:20:00 2021 +0000

    grpc: 1.37.1 -> 1.38.0
    
    https://github.com/grpc/grpc/releases/tag/v1.38.0

 pkgs/development/libraries/grpc/default.nix | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
```

It looks like this, even though grpc inputs are conditional and default to false:

```
cd src/murmur/ && ( test -e Makefile || /nix/store/b7jqnhqn6mw9ly6dk1232hddbnc1166z-qtbase-5.15.2-dev/bin/qmake -o Makefile /build/source/src/murmur/murmur.pro PREFIX=/nix/store/zxrq27ja0pnbr47fcmlm9ywlh41v86pg-murmur-1.3.4 NIX_OUTPUT_OUT=/nix/store/zxrq27ja0pnbr47fcmlm9ywlh41v86pg-murmur-1.3.4 NIX_OUTPUT_DEV=/nix/store/zxrq27ja0pnbr47fcmlm9ywlh41v86pg-murmur-1.3.4 NIX_OUTPUT_BIN=/nix/store/zxrq27ja0pnbr47fcmlm9ywlh41v86pg-murmur-1.3.4 NIX_OUTPUT_DOC=/nix/store/zxrq27ja0pnbr47fcmlm9ywlh41v86pg-murmur-1.3.4/share/doc/qt-5.15.2 NIX_OUTPUT_QML=/nix/store/zxrq27ja0pnbr47fcmlm9ywlh41v86pg-murmur-1.3.4/lib/qt-5.15.2/qml NIX_OUTPUT_PLUGIN=/nix/store/zxrq27ja0pnbr47fcmlm9ywlh41v86pg-murmur-1.3.4/lib/qt-5.15.2/plugins CONFIG+=release CONFIG+=c++11 CONFIG+=shared CONFIG+=no-g15 CONFIG+=packaged CONFIG+=no-update CONFIG+=no-embed-qt-translations CONFIG+=bundled-celt CONFIG+=no-bundled-opus CONFIG+=no-bundled-speex DEFINES+=PLUGIN_PATH=/nix/store/zxrq27ja0pnbr47fcmlm9ywlh41v86pg-murmur-1.3.4/lib/mumble CONFIG+=no-speechd CONFIG+=no-client CONFIG+=grpc ) && make -f Makefile release
Project ERROR: pkg-config could not find package grpc
make: *** [Makefile:500: sub-src-murmur-release_ordered] Error 3
builder for '/nix/store/xr1rvv464zyh7hxv5piwrh2nzj8p024y-murmur-1.3.4.drv' failed with exit code 2
```

**Comment by gebner** [comment]
@mweinelt murmur builds with #124030, I think I'm just gonna merge that PR then.

**Pull request merged**
