### PR TITLE
github-copilot-cli: drop

### PR DESCRIPTION
**Pull request by dotlambda**
It was maliciously marked as free: https://github.com/NixOS/nixpkgs/pull/228854

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by winterqt — COMMENTED** [review]
Not sure about maliciously, but yeah... it's definitely not free. Maybe we just mark as unfree instead?

**Comment by dotlambda** [comment]
> Not sure about maliciously

It says `license = licenses.free`. The only reason to do so is if you want to hide that it's unfree. Otherwise not setting `meta.license` would have the same effect.



> Maybe we just mark as unfree instead?

I'm not willing to help fix this package that added 3k lines to nixpkgs while removing it from `nodePackages`

**Comment by malob** [comment]
That's quite the accusation.

**Comment by dotlambda** [comment]
It's not necessarily supposed to be taken 100% seriously. But please go ahead and fix this.

**Comment by wegank** [comment]
I doubt if the package should be deleted, given that it has active users and even [a fish plugin in nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/shells/fish/plugins/github-copilot-cli-fish.nix).

Opened #254363 to mark the package as unfree.

**Comment by ehmry** [comment]
I merged #254363 before I saw this PR. I am also in favor of flushing this turd.

**Comment by malob** [comment]
This was an oversight on my part. Sorry about that. The package on NPM doesn't contain a license, and not knowing much about how licenses work, I didn't know what to select for the license, so I picked `licenses.free`, and hoped that other folks would point out if that was wrong. Might be a good idea for the `nixpkgs` manual to explicitly say in the [`lib.licenses.unfree`](https://nixos.org/manual/nixpkgs/stable/#lib.licenses.unfree-unfree) that if a package does not have a license explicitly specified, the the package should be marked as `unfree`.

**Pull request closed without merging**
