### PR TITLE
fnott: 1.3.0 -> 1.4.0

### PR DESCRIPTION
**Pull request by christoph-heiss**
###### Description of changes

Changelog: https://codeberg.org/dnkl/fnott/releases/tag/1.4.0

Fixes an actual problem for me, as older versions crash on scaled output devices.

This also removes the dot at the end of the description, which should not be there per the style-guides (very small nit, thus thought I just include it).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NickCao** [comment]
There is now a bundled copy of nanosvg in the source: https://codeberg.org/dnkl/fnott/src/branch/master/3rd-party/nanosvg, under the [Zlib license](https://codeberg.org/dnkl/fnott/src/branch/master/3rd-party/nanosvg/LICENSE.txt).

**Comment by christoph-heiss** [comment]
AFAICS, this is also already the case as of version 1.3.0. To be exact, nanosvg is present in the source tree since at least version 1.1.1, released on 09.11.2021(!).

So I do not see how this is relevant, besides that it would not affect packaging anyway.

**Comment by NickCao** [comment]
I think we should add it to the `license` field?

**Comment by christoph-heiss** [comment]
I guess we can do it, better (very) late than never, I guess. IANAL by any means, but I would not have thought this affects fnott itself.

Just to give another datapoint: Looking at [repology](https://repology.org/project/fnott/versions), no other (big) distribution seems to do this; I checked Arch, openSUSE, T2, Alpine.

Paging @polykernel here: What do you think?

**Comment by NickCao** [comment]
The [LiGurOS](https://repology.org/repository/liguros_stable) gentoo overlay does list both licenses: https://gpo.zugaina.org/Overlays/guru/gui-apps/fnott, maybe the other (big) distributions just did not pay enough attention as we did. And as seen in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=982145#74, the bundled copy of nanosvg is supposed to be listed in `debian/copyright`.

**Comment by christoph-heiss** [comment]
The Debian bug indeed sets a good precedent for us; I've pushed an additional commit adding the zlib license to the list.
Thanks for finding and linking this!

**Comment by polykernel** [comment]
When I first added and subsequently updated fnott, I admittedly did not notice that the vendored nanosvg was under a different license(carelessness on my part). That being said, I am also not familiar with licensing and copyright and the impacts of the source being mixed-licensed (perhaps someone more knowledgeable in this area can chime in), but I think listing the Zlib license as per Nick's suggestion would be the appropriate step here to transparently communicate that the source is mixed-licensed. As a precedent, this is already the case for fuzzel which optionally depends on nanosvg.

**Comment by NickCao** [comment]
@ofborg eval

**Review by NickCao — APPROVED** [review]

**Pull request merged**
