### PR TITLE
junit: remove (broken since 2015)

### PR DESCRIPTION
**Pull request by freezeboy**
###### Motivation for this change

junit is broken since 5 years
the expression is trying to use ant and upstream project is using maven
anyway junit is usually installed via maven/gradle inside apps so why package it with nix ?

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wamserma** [comment]
Doing a quick grep over nixpkgs, this seems fine once https://github.com/NixOS/nixpkgs/pull/98130 is merged.
`nix-shell -p nixpkgs-review --run "nixpkgs-review 102423"` will then tell.

**Comment by wamserma** [comment]
ping @asbachb @raboof to have ppl more familiar with the Java environment on this PR

**Comment by asbachb** [comment]
Basically it's not uncommon to package libraries like junit as system package. All big vendors are doing so (e.g. Ubuntu https://packages.ubuntu.com/search?keywords=junit&searchon=names&suite=focal&section=all).

In theory you could use junit as standalone application. But I guess that use case is rather uncommon.

**Review by raboof — APPROVED** [review]
I agree typically you'd get junit via the build tool (maven/gradle/sbt/...).

While I guess I can see how in theory you could have a scenario where it'd be useful to have it in the distro, that seems pretty obscure. I wouldn't be opposed to introducing a fixed version of the derivation at some point (along with a strong use case), but I'm in favor of deleting the broken package now.

**Review by asbachb — APPROVED** [review]

**Review by wamserma — CHANGES_REQUESTED** [review]
No. Keep junixsocket, see https://github.com/NixOS/nixpkgs/pull/98130

**Comment by freezeboy** [comment]
Oops, so this PR has to wait for your change before being merged

**Comment by SuperSandro2000** [comment]
Closing since there is effort to update it.

**Pull request closed without merging**
