### PR TITLE
Package some security/pentesting tools

### PR DESCRIPTION
**Pull request by globin**
###### Motivation for this change
All of these hadn't been packaged, yet.

For the cases where the git version is packaged, the currently released version was quite outdated and didn't contain a number of bug fixes.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peterhoeg** [comment]
fierce and dnsenum have no ```meta```.

**Comment by globin** [comment]
Fixed

**Comment by peterhoeg** [comment]
nitpick alert - dnsenum and fierce do not run the preInstall/postInstall hooks. Otherwise looks good.

**Review by orivej — APPROVED** [review]

**Comment by c0bw3b** [comment]
--> #61714

**Pull request closed without merging**
