### PR TITLE
winePackages.{stable,unstable,staging}: * -> 9.0; winetricks: 20230212 -> 20240105

### LINKED ISSUE #281752: Update request: wine 8.0.2 → 9.0
- Wine
- Latest released version: 9.0

- Current version on the unstable channel: 8.0.2
- Current version on the stable/release channel: 8.0.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@avnik @reckenrode 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by SFrijters**
## Description of changes

https://gitlab.winehq.org/wine/wine/-/releases/wine-9.0

Includes #279064 for convenience.

I haven't fully tested this yet; so far winePackages.staging builds on x86_64-linux.

Closes #281752 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by SFrijters** [comment]
Do we want to act on

"The new WoW64 mode is not yet enabled by default. It can be enabled by passing the `--enable-archs=i386,x86_64` option to configure. This is expected to work for most applications, but there are still some limitations, in particular:
* Lack of support for 16-bit code.
* Reduced OpenGL performance and lack of ARB_buffer_storage extension"
support.

**Comment by nyabinary** [comment]
> Do we want to act on
> 
> "The new WoW64 mode is not yet enabled by default. It can be enabled by passing the `--enable-archs=i386,x86_64` option to configure. This is expected to work for most applications, but there are still some limitations, in particular:
> 
>     * Lack of support for 16-bit code.
> 
>     * Reduced OpenGL performance and lack of ARB_buffer_storage extension"
>       support.

In my opinion, yes, it seems worth the tradeoffs.

**Comment by kirillrdy** [comment]
> The new WoW64 mode is not yet enabled by default.
we can make it an option ?

**Comment by wegank** [comment]
We already have `wineWow64Packages`, don't we?

https://github.com/NixOS/nixpkgs/blob/2f611d661b2b323cddf8e76da088968fb5523ab4/pkgs/applications/emulators/wine/packages.nix#L45-L55

**Comment by kirillrdy** [comment]
Right,  so we don't need to do anything 😄

**Comment by SFrijters** [comment]
Result of `nixpkgs-review pr 281905` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>airwave</li>
    <li>vinegar</li>
    <li>wineWow64Packages.minimal</li>
  </ul>
</details>
<details>
  <summary>36 packages built:</summary>
  <ul>
    <li>exactaudiocopy</li>
    <li>grapejuice</li>
    <li>grapejuice.dist</li>
    <li>pipelight</li>
    <li>playonlinux</li>
    <li>protontricks</li>
    <li>protontricks.dist</li>
    <li>q4wine</li>
    <li>synthesia</li>
    <li>vkd3d</li>
    <li>vkd3d-proton</li>
    <li>winbox</li>
    <li>wine (winePackages.stableFull ,winePackages.unstableFull)</li>
    <li>wine-staging (winePackages.stagingFull)</li>
    <li>wine64 (wine64Packages.stableFull ,wine64Packages.unstableFull)</li>
    <li>wine64Packages.base (wine64Packages.stable ,wine64Packages.unstable)</li>
    <li>winePackages.fonts (wine64Packages.fonts ,wineWow64Packages.fonts ,wineWowPackages.fonts)</li>
    <li>wine64Packages.minimal</li>
    <li>wine64Packages.staging</li>
    <li>wine64Packages.stagingFull</li>
    <li>winePackages.base (winePackages.stable ,winePackages.unstable)</li>
    <li>winePackages.minimal</li>
    <li>winePackages.staging</li>
    <li>wineWow64Packages.base (wineWow64Packages.stable ,wineWow64Packages.unstable)</li>
    <li>wineWow64Packages.full (wineWow64Packages.stableFull ,wineWow64Packages.unstableFull)</li>
    <li>wineWow64Packages.staging</li>
    <li>wineWow64Packages.stagingFull</li>
    <li>wineWowPackages.base (wineWowPackages.stable ,wineWowPackages.unstable)</li>
    <li>wineWowPackages.full (wineWowPackages.stableFull ,wineWowPackages.unstableFull)</li>
    <li>wineWowPackages.minimal</li>
    <li>wineWowPackages.staging</li>
    <li>wineWowPackages.stagingFull</li>
    <li>wineasio</li>
    <li>winetricks</li>
    <li>yabridge</li>
    <li>yabridgectl</li>
  </ul>
</details>

**Comment by SFrijters** [comment]
Result of `nixpkgs-review pr 281905` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>vinegar</li>
  </ul>
</details>
<details>
  <summary>38 packages built:</summary>
  <ul>
    <li>airwave</li>
    <li>exactaudiocopy</li>
    <li>grapejuice</li>
    <li>grapejuice.dist</li>
    <li>pipelight</li>
    <li>playonlinux</li>
    <li>protontricks</li>
    <li>protontricks.dist</li>
    <li>q4wine</li>
    <li>synthesia</li>
    <li>vkd3d</li>
    <li>vkd3d-proton</li>
    <li>winbox</li>
    <li>wine (winePackages.stableFull ,winePackages.unstableFull)</li>
    <li>wine-staging (winePackages.stagingFull)</li>
    <li>wine64 (wine64Packages.stableFull ,wine64Packages.unstableFull)</li>
    <li>wine64Packages.base (wine64Packages.stable ,wine64Packages.unstable)</li>
    <li>winePackages.fonts (wine64Packages.fonts ,wineWow64Packages.fonts ,wineWowPackages.fonts)</li>
    <li>wine64Packages.minimal</li>
    <li>wine64Packages.staging</li>
    <li>wine64Packages.stagingFull</li>
    <li>winePackages.base (winePackages.stable ,winePackages.unstable)</li>
    <li>winePackages.minimal</li>
    <li>winePackages.staging</li>
    <li>wineWow64Packages.base (wineWow64Packages.stable ,wineWow64Packages.unstable)</li>
    <li>wineWow64Packages.full (wineWow64Packages.stableFull ,wineWow64Packages.unstableFull)</li>
    <li>wineWow64Packages.minimal</li>
    <li>wineWow64Packages.staging</li>
    <li>wineWow64Packages.stagingFull</li>
    <li>wineWowPackages.base (wineWowPackages.stable ,wineWowPackages.unstable)</li>
    <li>wineWowPackages.full (wineWowPackages.stableFull ,wineWowPackages.unstableFull)</li>
    <li>wineWowPackages.minimal</li>
    <li>wineWowPackages.staging</li>
    <li>wineWowPackages.stagingFull</li>
    <li>wineasio</li>
    <li>winetricks</li>
    <li>yabridge</li>
    <li>yabridgectl</li>
  </ul>
</details>

**Comment by Amanse** [comment]
> https://bugs.winehq.org/show_bug.cgi?id=55604 so we may need to modify the patch if we want to keep it @nyanbinary

small typo in username, @nyabinary is the correct one

**Comment by nyabinary** [comment]
Also isn't Wayland support in mainline Wine 9.0 now? (Just disabled by default though)

**Comment by Amanse** [comment]
> Also isn't Wayland support in mainline Wine 9.0 now? (Just disabled by default though)

yes, just need to add one registry entry in your prefix, no compile step or anything needed

**Comment by SFrijters** [comment]
Is the latest commit I added a step in the right direction w.r.t. wayland?

**Comment by Amanse** [comment]
> which here are added only if the supportFlag waylandSupport is true.

ah yes, that makes sense, but it does compile without adding any extra dependency, i only changed source and it worked, did not check if wayland was working on the result, probably should check that

**Comment by SuperSamus** [comment]
I'd say that it's better to add `waylandSupport = true` to the `full` set, instead of having a dedicated `wine-wayland` package only for it. (Consider that the user also has to make some registry edits, it's something that is intentionally hidden. Making a dedicated package makes no sense, IMO)

Then, when it'll be more stable, it could be supported by `base` as well (or even right now, if it doesn't make the derivation significant bigger).

**Comment by SuperSamus** [comment]
Also, the extra packages for Wayland are:
https://github.com/NixOS/nixpkgs/blob/21ab626da4ecc7ee570c32ff51f2690bf1ba18be/pkgs/applications/emulators/wine/base.nix#L102-L105

That was for `wine-wayland`, are all of them still needed?
(BTW, [relevant discussion on Arch](https://gitlab.archlinux.org/archlinux/packaging/packages/wine/-/issues/11))

**Comment by Amanse** [comment]
> Then, when it'll be more stable, it could be supported by base as well (or even right now, if it doesn't make the derivation significant bigger).

Doing it right now seems fine, it is available in the base package in every other distro anyway

**Comment by Amanse** [comment]
> are all of them still needed?

wine docs haven't updated yet on winehq but the patches in wine were from the same dev, so proobably? otherwise will need to compile and check

**Comment by SFrijters** [comment]
As I'm not a wayland user myself I propose to leave that particular cleanup out of this update and someone can make a followup for that? Or someone can add an update to this - I've stripped my proposed wayland change.

**Comment by Amanse** [comment]
I am trying to compile right now, changes that should be made according to me
- waylandSupport flag set same as x11Support
- not adding the -wayland prefix based on the supportFlag

Will it be better to remove wayland sources now all together or should they be kept to make a seperate wayland package?

I am trying to compile right now by removing these parts, will report back with the results

**Comment by Amanse** [comment]
It compiles, i can put the commit in this PR if that is okay, although since it also removes the -wayland package maybe it should be different? or should that package stay?

**Comment by Amanse** [comment]
I cannot add commits to this PR, I might have to open another PR unless someone else who can add commits here do it

**Comment by nyabinary** [comment]
Could we make wine-staging support ``overrideAttrs`` with this too? Also this new wow64 mode, is there an option here?
image

**Comment by Amanse** [comment]
> Could we make wine-staging support overrideAttrs with this too? 
isn't that possible with overlays?

**Comment by nyabinary** [comment]
> > Could we make wine-staging support overrideAttrs with this too?
> 
> isn't that possible with overlays?

wine-staging supports & uses overrideDerivation not overrideAttrs currently:
https://github.com/NixOS/nixpkgs/blob/5d4dd2a3645c048ead9b28a761e7e9d7644c078c/pkgs/applications/emulators/wine/staging.nix#L10

**Comment by SFrijters** [comment]
I would still prefer to keep this PR focused as much as possible on just bumping the versions, and leave cleanups / QoL features to smaller separate PRs later. Otherwise I fear this one will get stalled while the requisite discussion and bikeshedding happens :).

**Comment by 7c6f434c** [comment]
Yeah OK let's just do the bump first.

**Comment by nyabinary** [comment]
> > > Could we make wine-staging support overrideAttrs with this too?
> > 
> > 
> > isn't that possible with overlays?
> 
> wine-staging supports & uses overrideDerivation not overrideAttrs currently:
> 
> https://github.com/NixOS/nixpkgs/blob/5d4dd2a3645c048ead9b28a761e7e9d7644c078c/pkgs/applications/emulators/wine/staging.nix#L10

did anyone do this btw?

**Comment by Amanse** [comment]
i tried with 9.1 but 9.1 has some patch mismatch (regardless of overrideDerivation or overrideAttrs) and wasn't compiling for me

**Comment by reckenrode** [comment]
I can do it with my Darwin cleanup. I use wine-staging in another derivation and need to add the msync patch. The lack of `overrtideAttrs` is a bit painful. I’ll try to get something out next week regardless of the status of the `overrideSDK` changes.

**Comment by nyabinary** [comment]
> I can do it with my Darwin cleanup. I use wine-staging in another derivation and need to add the msync patch. The lack of `overrtideAttrs` is a bit painful. I’ll try to get something out next week regardless of the status of the `overrideSDK` changes.

Nice keep me posted! :3

**Pull request merged**
