### PR TITLE
linux.stdenv: revert gcc11 update for x86_64-linux

### PR DESCRIPTION
**Pull request by cab404**
###### Description of changes
Reverting changes to x86_64-linux stdenv from [this PR](https://github.com/NixOS/nixpkgs/pull/165732/).

This should fix everything broken by mismatched glibc — and we should only start updating gcc when we have ways to propagate this change recursively through dependencies on per-package basis.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
The list you posted in matrix https://gist.github.com/cab404/96259f25450d778e744108c0ea9bfaa8

All the hardened kernel kernel modules can be ignored, they are constantly broken.

Only 150 breakages for such a change is IMO very good work. No reason to revert that bump a month later. I'd suggest to rather fix the broken packages from that list you personally care about.

**Comment by cab404** [comment]
> The list you posted in matrix https://gist.github.com/cab404/96259f25450d778e744108c0ea9bfaa8
> 
> All the hardened kernel kernel modules can be ignored, they are constantly broken.
> 
> Only 150 breakages for such a change is IMO very good work. No reason to revert that bump a month later. I'd suggest to rather fix the broken packages from that list you personally care about.

That’s 150 top-level ones. I’ve dropped every "Dependency failed" from that list, and everything except x86_64 — here’s a complete list of everything (1424 packages) broken in that PR https://hydra.nixos.org/eval/1756238#tabs-now-fail

**Comment by cab404** [comment]
And we’ve tried [some automated fixing](https://github.com/NixOS/nixpkgs/pull/175177#pullrequestreview-988637292) with @balsoft — that’s doable, however the concept that something breaking several percents of all nixpkgs got merged in the first place is a bit strange to me

**Review by mweinelt — CHANGES_REQUESTED** [review]
We will always leave unmaintained software behind every now and then. A stdenv compiler bump is one of these occasions and I'm opposed to reverting this bump on a whim.

**Comment by mweinelt** [comment]
Sorry, we can't do that route. The only way for these stragglers is forward.

**Comment by cab404** [comment]
Oh, yeah, sure, forgot to close it. Still sad nixpkgs is like that(

**Comment by mweinelt** [comment]
This changeset still tries to downgrade gcc on x86_64.

**Comment by cab404** [comment]
> This changeset still tries to downgrade gcc on x86_64.

Sorry, missed the button

**Comment by cab404** [comment]
> > It's more or less about having to break anything at all, especially since it's Nix we are talking about.
> 
> Some treewide changes can break things and that is not super great but okay. You can't test every change with over 50 000 packages beforehand and then the fallout should be cleaned up.

I would probably say that with frequency at which gcc updates, we can let it check all of the packages over a week or so :shrug:

**Pull request closed without merging**
