### PR TITLE
gdm: start gdm on tty7 rather than default tty1

### PR DESCRIPTION
**Pull request by pierrechevalier83**
- Fixes nixos-rebuild switch/test issue with GNOME
  https://github.com/NixOS/nixpkgs/issues/21439
- The solution was given here:
  https://github.com/deedrah/nixpkgs/commit/d761e66a41e09bb0a1ebe31612f3678f9ba801a1#commitcomment-25382880

###### Motivation for this change

I can't use nixos-rebuild switch at the moment. I was waiting for someone else to create a pull request, but I thought I might as well.

###### Things done

As per comments on ticket, went for solution that was brought forward by @deedrah and @bjornfor: start gdm on tty7.
Tested and works for me with gnome 3.24 + gdm + X11.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by bjornfor — APPROVED** [review]

**Comment by bjornfor** [comment]
Thanks! I'm running the NixOS tests now. If they pass I'll merge. (I don't have a NixOS machine on master branch.)

**Comment by bjornfor** [comment]
```nix-build nixos/tests/gnome3-gdm.nix``` fails on my system. But it _also_ fails on master. Looking at hydra.nixos.org I see nixos.tests.gnome3-gdm failed, but due to "Cancelled by user". Hm...

On my system the test times out after printing this block of test repeatedly for a long time:

```
machine: must succeed: xwininfo -root -tree | sed 's/.*0x[0-9a-f]* \"\([^\"]*\)\".*/\1/; t; d'
machine# No protocol specified
machine# xwininfo: error: unable to open display ":0.0"
machine: exit status 0
```

Anyway, I think we can revert 440178d729efbc279a70c93495b6212db029f180 ("gdm: don't start getty@tty1 if enabled"), and remove the other lines regarding "getty@tty1" in nixos/modules/services/x11/display-managers/gdm.nix.

**Comment by pierrechevalier83** [comment]
Thanks for the review @bjornfor. I've removed the references to getty. Things still seem to work for me 😄

**Comment by bjornfor** [comment]
Yep, since the tests not working on my system is not a regression, I don't think it should block integration.

**Review by bjornfor — APPROVED** [review]

**Review by jtojnar — APPROVED** [review]
Not really my area of expertise but it seems to work with GNOME 3.26.

**Comment by bjornfor** [comment]
Applied to master (c46d4dab967572be809f302aef36ed07d4976492 and 2 parents). Thanks!

**Pull request closed without merging**
