### PR TITLE
mingw-64: 6.0.0 -> 9.0.0

### PR DESCRIPTION
**Pull request by pstn**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 130864` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>18 packages built:</summary>
  <ul>
    <li>grapejuice</li>
    <li>lutris</li>
    <li>lutris-free</li>
    <li>lutris-unwrapped</li>
    <li>pipelight</li>
    <li>playonlinux</li>
    <li>wine (winePackages.full)</li>
    <li>wine-staging</li>
    <li>winePackages.base (winePackages.stable)</li>
    <li>winePackages.staging</li>
    <li>winePackages.unstable</li>
    <li>wineWowPackages.base (wineWowPackages.stable)</li>
    <li>wineWowPackages.full</li>
    <li>wineWowPackages.staging</li>
    <li>wineWowPackages.unstable</li>
    <li>winetricks</li>
    <li>yabridge</li>
    <li>yabridgectl</li>
  </ul>
</details>

**Comment by pstn** [comment]
Pinging @PlushBeaver, @alyssais, @Ericson2314 and @matthewbauer  since they were involved in the past and there is no maintainer

**Comment by pstn** [comment]
Oh and I completely failed to reproduce any failures for `nixos-install-tools` and since ofborg isn't complaining I assume the failure is due to state of nixpkgs at the moment of the review running.

**Comment by siraben** [comment]
@pstn nixos-install-tools has been failing for me, it's fine.

**Comment by siraben** [comment]
LGTM.

**Pull request merged**
