### PR TITLE
tmuxp: 1.7.2 -> 1.9.2

### PR DESCRIPTION
**Pull request by arcnmx**
###### Motivation for this change

1.7.2 doesn't build since a dependency was updated

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
Breaks for me when starting it like this:

```
→ ./result/bin/tmuxp                                                                                                            [da2d5493f69]
Traceback (most recent call last):
  File "/nix/store/hwizfgvhgmg79hmdd4qqcxynq2dbnmhj-tmuxp-1.9.2/bin/.tmuxp-wrapped", line 6, in <module>
    from tmuxp import cli
  File "/nix/store/hwizfgvhgmg79hmdd4qqcxynq2dbnmhj-tmuxp-1.9.2/lib/python2.7/site-packages/tmuxp/__init__.py", line 11, in <module>
    from . import cli, config, util
  File "/nix/store/hwizfgvhgmg79hmdd4qqcxynq2dbnmhj-tmuxp-1.9.2/lib/python2.7/site-packages/tmuxp/cli.py", line 17, in <module>
    from libtmux import __version__ as libtmux_version
  File "/nix/store/3j43d1lmk0s6l813j8k1754jv8slyljl-python2.7-libtmux-0.10.1/lib/python2.7/site-packages/libtmux/__init__.py", line 12, in <module>
    from .pane import Pane
  File "/nix/store/3j43d1lmk0s6l813j8k1754jv8slyljl-python2.7-libtmux-0.10.1/lib/python2.7/site-packages/libtmux/pane.py", line 11, in <module>
    from .common import TmuxMappingObject, TmuxRelationalObject
  File "/nix/store/3j43d1lmk0s6l813j8k1754jv8slyljl-python2.7-libtmux-0.10.1/lib/python2.7/site-packages/libtmux/common.py", line 17, in <module>
    from ._compat import MutableMapping, console_to_str, str_from_console
  File "/nix/store/3j43d1lmk0s6l813j8k1754jv8slyljl-python2.7-libtmux-0.10.1/lib/python2.7/site-packages/libtmux/_compat.py", line 4, in <module>
    from collections.abc import MutableMapping
ImportError: No module named abc
```

**Comment by arcnmx** [comment]
Sidestepped by switching to python 3.

**Review by SuperSandro2000 — COMMENTED** [review]
Do you mind adding yourself as a maintainer?

**Comment by arcnmx** [comment]
> Do you mind adding yourself as a maintainer?

Honestly I barely use the package myself and have no interest in maintaining it, sorry.

**Pull request closed without merging**
