### PR TITLE
wlroots_0_16: 0.16.0 -> 0.16.1

### PR DESCRIPTION
**Pull request by budimanjojo**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by NobbZ — CHANGES_REQUESTED** [review]
Please rebase your changes on `master`.

**Comment by budimanjojo** [comment]
@NobbZ done

**Review by NobbZ — CHANGES_REQUESTED** [review]
Please **rebase** on master!

Your PR should have a single commit, with a single parent which is reachable from `master`.

**Review by primeos — CHANGES_REQUESTED** [review]
Yes, [Merge branch 'NixOS:master' into patch-1](https://github.com/NixOS/nixpkgs/pull/212110/commits/ddc3d0c6455093ff56f62b743e90bc6cb901c362) shouldn't be there (from the GitHub UI it seems like a normal but empty commit). https://git-rebase.io/ might help ;)

And please also do check `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"` (definitely required here - would be nice if you could also post the result / final output) and test Sway for such changes (updating libraries is a bit more difficult to start with than updating unmaintained packages but the checklist and https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md should help). Thanks!

And welcome to Nixpkgs :)

**Comment by budimanjojo** [comment]
@NobbZ @primeos I don't know how to undo what I did with the `Merge branch` and fix this PR without creating a new PR (I don't mind to do it but not sure if you guys will be fine with that). So, either I create a new PR or you guys can do the commit into this repo for me.

**Comment by NobbZ** [comment]
I talked to @budimanjojo in the Discord and agreed to do the rebase for them.

Other than the rebase woes, the PR looks fine to me now.

I will run a quick review for `x86_64-linux` and if that suceeds I will approve, though be warned, as I do not use wayland, I can't say anything about whether the subject actually works.

**Review by primeos — APPROVED** [review]
Thanks @NobbZ! This LGTM then :)

**Comment by NobbZ** [comment]
Result of `nixpkgs-review pr 212110` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>nwg-panel</li>
  </ul>
</details>
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>labwc</li>
    <li>river</li>
    <li>rivercarro</li>
    <li>sway</li>
    <li>sway-contrib.grimshot</li>
    <li>sway-unwrapped</li>
    <li>waybar</li>
    <li>wlprop</li>
    <li>wlroots_0_16</li>
  </ul>
</details>

**Comment by budimanjojo** [comment]
Sorry it takes so long to clone the repo locally and do the test. I have the same result: 
```
this path will be fetched (0.03 MiB download, 0.13 MiB unpacked):
  /nix/store/yfxddhxprdld16lbirk71j3b9ny240vw-nixpkgs-review-2.6.4
copying path '/nix/store/yfxddhxprdld16lbirk71j3b9ny240vw-nixpkgs-review-2.6.4' from 'https://cache.nixos.org'...
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0
From https://github.com/NixOS/nixpkgs
 * [new branch]              master     -> refs/nixpkgs-review/0
$ git worktree add /home/budiman/.cache/nixpkgs-review/rev-2446b2d24deb7f1417848eefdd8d035b1d230b7b/nixpkgs c24fb332623e5d5fffc550379da43de8c01f5229
Preparing worktree (detached HEAD c24fb332623)
Updating files: 100% (33335/33335), done.
HEAD is now at c24fb332623 Merge pull request #211521 from r-ryantm/auto-update/kubeseal
$ nix-env --option system x86_64-linux -f /home/budiman/.cache/nixpkgs-review/rev-2446b2d24deb7f1417848eefdd8d035b1d230b7b/nixpkgs -qaP --xml --out-path --show-trace
$ git merge --no-commit --no-ff 2446b2d24deb7f1417848eefdd8d035b1d230b7b
Automatic merge went well; stopped before committing as requested
$ nix-env --option system x86_64-linux -f /home/budiman/.cache/nixpkgs-review/rev-2446b2d24deb7f1417848eefdd8d035b1d230b7b/nixpkgs -qaP --xml --out-path --show-trace --meta
derivation 'systemd-252.4' has invalid meta attribute 'badPlatforms'
derivation 'systemd-minimal-252.4' has invalid meta attribute 'badPlatforms'
derivation 'systemd-stage-1-252.4' has invalid meta attribute 'badPlatforms'
derivation 'systemd-stage-1-network-252.4' has invalid meta attribute 'badPlatforms'
10 packages updated:
grimshot labwc nwg-panel river rivercarro sway sway-unwrapped waybar wlprop-unstable wlroots_0_16 (0.16.0 → 0.16.1)
                                                                                                                                                                                                                                         
$ nix --experimental-features nix-command build --no-link --keep-going --option build-use-sandbox relaxed -f /home/budiman/.cache/nixpkgs-review/rev-2446b2d24deb7f1417848eefdd8d035b1d230b7b/build.nix
error: builder for '/nix/store/z0v185bmk3ljbin3i289gf4ynac1jj9l-python3.10-dasbus-1.7.drv' failed with exit code 1;
       last 10 log lines:
       >   File "/build/dasbus-1.7/tests/lib_dbus.py", line 194, in _run_test
       >     self.assertEqual(client.exitcode, 0, msg)
       > AssertionError: 1 != 0 : _call_hello_sync has finished with 1
       >
       > ----------------------------------------------------------------------
       > Ran 232 tests in 683.199s
       >
       > FAILED (failures=4)
       > Test failed: <unittest.runner.TextTestResult run=232 errors=0 failures=4>
       > error: Test failed: <unittest.runner.TextTestResult run=232 errors=0 failures=4>
       For full logs, run 'nix log /nix/store/z0v185bmk3ljbin3i289gf4ynac1jj9l-python3.10-dasbus-1.7.drv'.
error: 1 dependencies of derivation '/nix/store/q2az7chakh2hz64h9ixm4k9dba772vzn-nwg-panel-0.7.11.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ih2x9sqvvlykm3yb7akbpca1ihd1kn2g-review-shell.drv' failed to build
1 package failed to build:
nwg-panel
                                                                                                                                                                                                                                         
9 packages built:
labwc river rivercarro sway sway-contrib.grimshot sway-unwrapped waybar wlprop wlroots_0_16
                                                                                                                                                                                                                                         
$ nix-shell /home/budiman/.cache/nixpkgs-review/rev-2446b2d24deb7f1417848eefdd8d035b1d230b7b/shell.nix
this path will be fetched (0.06 MiB download, 0.31 MiB unpacked):
  /nix/store/1f1k3nl1v1qwv6jh9bawyr1f7m4wj1a8-bash-interactive-5.2-p15-dev
copying path '/nix/store/1f1k3nl1v1qwv6jh9bawyr1f7m4wj1a8-bash-interactive-5.2-p15-dev' from 'https://cache.nixos.org'...
                                                                                                                                                                                                                                         
[nix-shell:~/.cache/nixpkgs-review/rev-2446b2d24deb7f1417848eefdd8d035b1d230b7b]$
```

**Review by NobbZ — APPROVED** [review]
`nwg-pannel` fails to build on `master` as well due to failing tests in `dasbus`, a python package.

**Pull request merged**
