### PR TITLE
puppet-lint: 2.3.4 -> 2.4.2

### LINKED ISSUE #145359: Puppet-lint is >3 years out of date
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: puppet-lint

current version: 2.3.6
desired version: 2.5.2

###### Notify maintainers

maintainers: @alyssais 

###### Note for maintainers

Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by petrosagg**
###### Motivation for this change

Fixes #145359

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by petrosagg** [comment]
@John-Colvin could you give this a spin?

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/145364 how'd you update to 2.4.2 instead of the newest 2.5.2?

i did
```
bundler update
bundle lock
bundix
```

**Comment by Artturin** [comment]
Closing in favor of https://github.com/NixOS/nixpkgs/pull/145364

**Comment by petrosagg** [comment]
@Artturin  hm, that's strange. I checked the package's github release and the latest one was 2.4.2 and I also checked the version packaged in AUR which is also 2.4.2 https://aur.archlinux.org/packages/puppet-lint/

So I concluded that the original issue must have been a typo.

**Comment by petrosagg** [comment]
Ok, I see what happened. The package sources are from this forked repo https://github.com/puppetlabs/puppet-lint/tags

Sorry about it!

**Pull request closed without merging**
