### PR TITLE
rss2email: 3.9 -> 3.10

### PR DESCRIPTION
**Pull request by Ekleog**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @Profpatsch 

@GrahamcOfBorg build rss2email nixosTests.rss2email

### CODE REVIEW

**Comment by Ekleog** [comment]
@GrahamcOfBorg build nixosTests.rss2email

**Comment by Profpatsch** [comment]
Whooo

**Comment by Profpatsch** [comment]
@GrahamcOfBorg test rss2email

**Comment by Profpatsch** [comment]
Do you want to fix the `rss2email` test before we merge? The dependent `opensmpt` test has a problem.

**Comment by jb55** [comment]
@Profpatsch have you had any issues with rss2email sending multiple of the same email? I had to turn rss2email off awhile ago because of that

**Comment by Profpatsch** [comment]
> @Profpatsch have you had any issues with rss2email sending multiple of the same email? I had to turn rss2email off awhile ago because of that

Was it in 3.x? Some people didn’t like the 2 -> 3 rewrite because it introduced some bugs from what I heard.

**Comment by Ekleog** [comment]
@Profpatsch Being currently with no time to fix it, I'd say we can merge and see later. Intuitively it's due to the opensmtpd version upgrade which introduced another config file format, and should be pretty quick to fix, but I just don't have time right now.

And as the 19.09 cutoff is quite soon… maybe let's just merge by then? :)

**Comment by Ekleog** [comment]
@jb55 Got this neither with 3.9 nor with 3.10

**Comment by risicle** [comment]
`nix-review` checks out for me, macos 10.13.

**Pull request merged**
