### PR TITLE
cosmic-comp: unstable-2023-11-13 -> 1.0.0-alpha.1

### PR DESCRIPTION
**Pull request by a-kenji**
## Description of changes

Do not merge, needs `rustc --version: 1.80.0`

Part of:  #259641
Obligatory: https://github.com/NixOS/nixpkgs/issues/327063

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by alyssais** [comment]
Are there user-facing changes in this upgrade, since this adds a new Cargo.lock?

**Comment by alyssais** [comment]
Same question as in https://github.com/NixOS/nixpkgs/pull/332252#issuecomment-2271031763.  Let's merge this concurrently with the Rust upgrade, so please retarget to staging.

**Comment by a-kenji** [comment]
Notable user facing changes:
- gesture support
- way more configuration options
- smoother rendering

Thank you for the review,
I rebased to staging, is the version attribute correct?

**Comment by alyssais** [comment]
> is the version attribute correct?

It looks right to me, but I'm still looking for confirmation that we should be using the tag.

**Review by alyssais — APPROVED** [review]

**Comment by alyssais** [comment]
>   = note: /nix/store/d58kbbwjsdp3n5l91sx5pgg5i3p7llyh-binutils-2.42/bin/ld: cannot find -lpixman-1: No such file or directory

**Review by alyssais — APPROVED** [review]
Tested building the merge with staging-next (for Rust 1.80).

**Pull request merged**
