### PR TITLE
new package: hatt

### PR DESCRIPTION
**Pull request by psibi**

### CODE REVIEW

**Comment by psibi** [comment]
CC: @peti  Any idea on why this failed in Travis ? Works locally for me in ghc-7.8.4.

**Comment by peti** [comment]
Travis-CI produces false-positives like crazy. Personally, I completely ignore those builds.

Anyway, do you realize that `hatt` is available in Nixpkgs already?

    $ nix-build "<nixpkgs>" -A haskell-ng.packages.ghc784.hatt
    /nix/store/h9bfc36blbdng6w0h8dhyi4rpsws8lai-haskell-hatt-1.5.0.3

**Comment by psibi** [comment]
@peti Wow, didn't realize that! I just searched on here https://nixos.org/nixos/packages.html before submitting the patch. :)

**Comment by peti** [comment]
As a rule of thumb, the `haskell-ng.packages.ghcXYZ` set has every package within a day or two after it's been uploaded to Hackage.

**Comment by psibi** [comment]
@peti Where exactly is hatt expression currently in the nixpkgs repository ? Sorry, it was trivial to find but even the search is giving me empty result (https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=hatt)

**Comment by peti** [comment]
Everything is in `pkgs/development/haskell-modules/hackage-packages.nix`. See the "A Journey into the Haskell NG infrastructure" postings in https://github.com/NixOS/nixpkgs/issues/4941 for further details.

**Pull request closed without merging**
