### PR TITLE
zoom-us 5.5.7938.0228 -> 5.6.13632.0328

### PR DESCRIPTION
**Pull request by LutzCle**
###### Motivation for this change

Zoom fails to start with the message: "Update required: Your app version needs to be 5.6.1 (13632.0328) or higher to sign in. Please update to continue."

This PR backports 5.6.13632.0328 from the master branch.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 118717` at d9620068 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>zoom-us</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: unused-argument

Unused argument: `fetchFromGitHub`.
Near pkgs/applications/networking/instant-messengers/zoom-us/default.nix:5:3:
```
  |
5 | , fetchFromGitHub
  |   ^
```
</li>
  </ul>
</details>

**Comment by doronbehar** [comment]
@LutzCle could you please remove the unused argument `fetchFromGitHub`?

**Comment by LutzCle** [comment]
@doronbehar Done.

**Review by doronbehar — APPROVED** [review]

**Comment by doronbehar** [comment]
Haven't noticed this is a backport when I asked to remove the unused arguments, but whatever..

**Comment by LutzCle** [comment]
No worries - thanks for the merge ;-)

**Pull request merged**
