### PR TITLE
[23.05] dendrite: 0.12.0 -> 0.13.3

### PR DESCRIPTION
**Pull request by hexop**
## Description of changes

Update the version of dendrite in 23.05 because the last version exhibits some problems to maintain room state. Backport the changes in #242183 #243634 #248492 #251063 #257823

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ajs124** [comment]
please read the manual on how to do backports and which branch to target for what

**Comment by hexop** [comment]
Thanks for notifying me of my rookie mistakes @ajs124, I have now properly backported all the necessary commits, this time making sure that I used the proper flags for the cherry-pick. I think I am using the correct branches (release-23.05) as it's stated in CONTRIBUTING.md, did I mess up in any way?

**Comment by hexop** [comment]
Result of `nixpkgs-review pr 251451` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>dendrite</li>
  </ul>
</details>

**Comment by sefidel** [comment]
Dendrite 0.13.3 has been released.

**Changelog**
https://github.com/matrix-org/dendrite/releases/tag/v0.13.3

**Nixpkgs PR**
https://github.com/NixOS/nixpkgs/pull/257823

**Comment by hexop** [comment]
Result of `nixpkgs-review pr 251451` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>dendrite</li>
  </ul>
</details>

**Pull request merged**
