### PR TITLE
nixos/alsa: added sound.hdaJackRetask option

### PR DESCRIPTION
**Pull request by pasqui23**
###### Motivation for this change
https://discourse.nixos.org/t/fixing-audio-on-asus-strix-scar-17-g733qs/12687/10

Oftentimes audio on linux needs to be reconfigured by hda-jack-retask and while it is not possible to use it directly on NixOS this option allow to retask jack pins on NixOS

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bb2020** [comment]
What about using `hardware.firmware` or adding a `udev` rule to echo necessary kernel module parameter right after device creation?

**Comment by pasqui23** [comment]
It did not work on my laptop, and I imagine on others too.
Also early patching, adding files to `hardware.firmware`, would require to recompile the kernel with `CONFIG_SND_HDA_PATCH_LOADER=y`.

Finally some guides would ask to only fix some pins,like the one I've followed, and a module would allow more flexibility in module placement.

I don't know how to write udev rules especially to trigger after device creation. Hell, I don't even know what device to look for!

**Comment by bb2020** [comment]
Modifying `alsa` module for a specific sound card seems excessive to me. I think this should be done at `modprobe` or `udev` level not as a `systemd` service.

Example: https://bbs.archlinux.org/viewtopic.php?id=259661.

**Comment by pasqui23** [comment]
It's not for a specific sound card, there are many guides on the internet about hdajackretask that would not work on NixOS as it requires write access to `/lib`.

In essence is for all sound cards requring hdajackretask.

Also, why the objection to doing it as a systemd service?

**Comment by bb2020** [comment]
`hdajackretask` creates a `modprobe.conf` patch file. It is not intended to be used as a `systemd` service.
It is hard to serialize `systemd` services.

If `hdajackretask` isn't working properly under NixOS, you can try running it on another distro and then copy its output into `boot.extraModprobeConfig` under NixOS.

**Comment by pasqui23** [comment]
So it turns out that the approach I took here is unstable as the name of the files to manipulate can change between reboot, and @bb2020 was right in criticizing my approach

**Comment by bb2020** [comment]
Thanks for your understanding.

Some `systemd` services (also `pulse`) depends on `alsa` itself so the hardware configuration should be done at `modprobe`/`udev` level. This kind of quirks are solvable in `configuration.nix`, but it is hard to generalize for everyone's system.

**Pull request closed without merging**
