### PR TITLE
isabelle: 2014 -> 2015

### PR DESCRIPTION
**Pull request by svenkeidel**
Hi,

I updated to the 2015 version. @jwiegley can you take a look?

Best,
Sven

### CODE REVIEW

**Comment by jwiegley** [comment]
Hi @svenkeidel, I'll be happy to look.  I'm traveling now, so it will be a few days.

**Comment by svenkeidel** [comment]
I working my way through the isabelle tutorial and came to the 4.2 "Document Preparation". The commands

```
isabelle mkroot -d MySession
isabelle build -D MySession
```

need latex to work properly, so I added texlive as a dependency.

**Comment by svenkeidel** [comment]
@jwiegley, the old download link for isabelle 2014 does not work anymore. Have you had the time to look at my PR?

Best,
Sven

**Comment by jwiegley** [comment]
So, TeXlive as a dependency is pretty unacceptable, unless you make it conditional on an attribute that is false by default, so that people can enable it if they really want to.

**Comment by vcunat** [comment]
I agree with the last comment; texLive a rather heavy thing.

**Comment by svenkeidel** [comment]
@jwiegley I tried to make the TexLive dependency optional, but it still defines TexLive as a dependency even if the default for TexLive support is false. Can you help me, I'm stuck on this.

**Comment by gebner** [comment]
Can we merge at least the update, without the texlive changes?

In any case, I'm not sure that we should include a specific texlive package set.  AFAICT `isabelle document` accepts a user-specified `root.tex` file as input, which could use any latex package, so you probably want to provide your own version of texlive anyhow.

**Comment by vcunat** [comment]
Note that in the meantime `texLive` is deprecated and will probably get removed soon. There's new and much lighter `texlive` since the summer.

**Comment by vcunat** [comment]
OK, picked the update to master. It builds and seems to start fine.

**Comment by vcunat** [comment]
It will be better to file a separate PR if you still want some additional changes.

**Pull request closed without merging**
