### PR TITLE
tcsd module: expose firmwarePCRs and kernelPCRs

### PR DESCRIPTION
**Pull request by ts468**

### CODE REVIEW

**Comment by ts468** [comment]
@alexanderkjeldaas: Are the default values fine with you?

**Comment by alexanderkjeldaas** [comment]
@ts468  I don't see PCR11 used by IMA.  Which system uses it?  The others are fine.

**Comment by ts468** [comment]
@alexanderkjeldaas Thanks for the fast reply! PCR10 and PCR11 were just the values in the example from the manpage of tscd.conf. What do you think about PCR08-PCR12 as default to match TrustedGRUB2 (https://github.com/Sirrix-AG/TrustedGRUB2)?

**Comment by alexanderkjeldaas** [comment]
@ts468 That seems reasonable.

From TrustedGRUB2:
 * PCR 10 Everything that is loaded from disk (grub2-modules, Linux-kernel, initrd, ntldr, etc.) // TODO: fonts, themes, locales
 * PCR 11 contains all commandline arguments from scripts (e.g. grub.cfg) and those entered in the shell
 * PCR 12 LUKS-header

**Comment by ts468** [comment]
@alexanderkjeldaas Thanks for your help! I've updated kernelPCRs in #9090.

**Pull request merged**
