### PR TITLE
GCC: darwin support

### PR DESCRIPTION
**Pull request by matthewbauer**
###### Motivation for this change

This sets the "--disable-bootstrap" flag for Darwin. It was the only way I could get this to work.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthewbauer** [comment]
Maybe? Darwin is using clang right now so I didn't think there would need to be a mass rebuild. Is that being caused by changing the builder.sh? Perhaps we could add a patchelf stub for Darwin.

**Comment by vcunat** [comment]
Yes, `builder.sh` change causes stdenv rebuild on Linux, so this shouldn't go directly to master.

**Comment by matthewbauer** [comment]
It doesn't really do anything for Linux... Is there a reason Linux has patchelf in stdenv and Darwin doesn't? Would it be possible to add a no-op when calling "patchelf" on Darwin?

**Comment by wmertens** [comment]
@matthewbauer Darwin doesn't use elf…

**Comment by matthewbauer** [comment]
@wmertens Yes, but a lot of Nix scripts just assume it's available because it's in stdenv and there isn't really a good way to check whether it's ELF or Mach-O or whatever.

**Comment by vcunat** [comment]
I don't think this is about ELF, really. The build scripts mainly change RPATH and interpreter, and it appears the Darwin executable format [*does* support](http://stackoverflow.com/a/9263735/587396) those concepts, so what about creating a simple patchelf script for Darwin that's just a wrapper around `otool` to share the most commonly used part of CLI with other platforms?

**Comment by vcunat** [comment]
Linkify: #16806

**Pull request closed without merging**
