### PR TITLE
python3Packages.testfixtures: 6.18.1 -> 6.18.3

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 6.18.3

CHange log: https://github.com/simplistix/testfixtures/blob/master/CHANGELOG.rst#6183-29-sep-2021

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by smancill** [comment]
Result of `nixpkgs-review pr 139906` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>privacyidea</li>
  </ul>
</details>
<details>
  <summary>30 packages built:</summary>
  <ul>
    <li>bump2version</li>
    <li>check-esxi-hardware</li>
    <li>python38Packages.connexion</li>
    <li>python38Packages.django-simple-captcha</li>
    <li>python38Packages.openerz-api</li>
    <li>python38Packages.praw</li>
    <li>python38Packages.prawcore</li>
    <li>python38Packages.pykwalify</li>
    <li>python38Packages.pywbem</li>
    <li>python38Packages.scrapy</li>
    <li>python38Packages.scrapy-deltafetch</li>
    <li>python38Packages.scrapy-fake-useragent</li>
    <li>python38Packages.scrapy-splash</li>
    <li>python38Packages.sopel</li>
    <li>python38Packages.testfixtures</li>
    <li>python38Packages.west</li>
    <li>python39Packages.connexion</li>
    <li>python39Packages.django-simple-captcha</li>
    <li>python39Packages.openerz-api</li>
    <li>python39Packages.praw</li>
    <li>python39Packages.prawcore</li>
    <li>python39Packages.pykwalify</li>
    <li>python39Packages.pywbem</li>
    <li>python39Packages.scrapy</li>
    <li>python39Packages.scrapy-deltafetch</li>
    <li>python39Packages.scrapy-fake-useragent</li>
    <li>python39Packages.scrapy-splash</li>
    <li>python39Packages.sopel</li>
    <li>python39Packages.testfixtures</li>
    <li>python39Packages.west</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 139906` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>privacyidea</li>
    <li>python38Packages.scrapy</li>
    <li>python38Packages.scrapy-deltafetch</li>
    <li>python38Packages.scrapy-fake-useragent</li>
    <li>python38Packages.scrapy-splash</li>
  </ul>
</details>
<details>
  <summary>28 packages built:</summary>
  <ul>
    <li>bump2version</li>
    <li>check-esxi-hardware</li>
    <li>giara</li>
    <li>home-assistant</li>
    <li>python38Packages.connexion</li>
    <li>python38Packages.django-simple-captcha</li>
    <li>python38Packages.openerz-api</li>
    <li>python38Packages.praw</li>
    <li>python38Packages.prawcore</li>
    <li>python38Packages.pykwalify</li>
    <li>python38Packages.pywbem</li>
    <li>python38Packages.sopel</li>
    <li>python38Packages.testfixtures</li>
    <li>python38Packages.west</li>
    <li>python39Packages.connexion</li>
    <li>python39Packages.django-simple-captcha</li>
    <li>python39Packages.openerz-api</li>
    <li>python39Packages.praw</li>
    <li>python39Packages.prawcore</li>
    <li>python39Packages.pykwalify</li>
    <li>python39Packages.pywbem</li>
    <li>python39Packages.scrapy</li>
    <li>python39Packages.scrapy-deltafetch</li>
    <li>python39Packages.scrapy-fake-useragent</li>
    <li>python39Packages.scrapy-splash</li>
    <li>python39Packages.sopel</li>
    <li>python39Packages.testfixtures</li>
    <li>python39Packages.west</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Please target staging.

**Comment by fabaff** [comment]
I remove the `wekzeug` commit which should reduce the amount of touched packages.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 139906` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>33 packages built:</summary>
  <ul>
    <li>bump2version</li>
    <li>check-esxi-hardware</li>
    <li>giara</li>
    <li>home-assistant</li>
    <li>privacyidea</li>
    <li>python38Packages.connexion</li>
    <li>python38Packages.django-simple-captcha</li>
    <li>python38Packages.openerz-api</li>
    <li>python38Packages.praw</li>
    <li>python38Packages.prawcore</li>
    <li>python38Packages.pykwalify</li>
    <li>python38Packages.pywbem</li>
    <li>python38Packages.scrapy</li>
    <li>python38Packages.scrapy-deltafetch</li>
    <li>python38Packages.scrapy-fake-useragent</li>
    <li>python38Packages.scrapy-splash</li>
    <li>python38Packages.sopel</li>
    <li>python38Packages.testfixtures</li>
    <li>python38Packages.west</li>
    <li>python39Packages.connexion</li>
    <li>python39Packages.django-simple-captcha</li>
    <li>python39Packages.openerz-api</li>
    <li>python39Packages.praw</li>
    <li>python39Packages.prawcore</li>
    <li>python39Packages.pykwalify</li>
    <li>python39Packages.pywbem</li>
    <li>python39Packages.scrapy</li>
    <li>python39Packages.scrapy-deltafetch</li>
    <li>python39Packages.scrapy-fake-useragent</li>
    <li>python39Packages.scrapy-splash</li>
    <li>python39Packages.sopel</li>
    <li>python39Packages.testfixtures</li>
    <li>python39Packages.west</li>
  </ul>
</details>

**Pull request merged**
