### PR TITLE
postgresql_17: init at 17.0

### PR DESCRIPTION
**Pull request by wolfgangwalther**
Took the new v17 out of #345260 to target master directly, but left the `postgresql: 16 -> 17` over there for later.

@ma27 @SuperSandro2000 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by kirillrdy** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 351253`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 12 packages marked as broken and skipped:</summary>
  <ul>
    <li>postgresql12JitPackages.pg_ivm</li>
    <li>postgresql12JitPackages.plv8</li>
    <li>postgresql12Packages.pg_ivm</li>
    <li>postgresql13JitPackages.plv8</li>
    <li>postgresql14JitPackages.plv8</li>
    <li>postgresql15JitPackages.plv8</li>
    <li>postgresql16JitPackages.plv8</li>
    <li>postgresql17JitPackages.cstore_fdw</li>
    <li>postgresql17JitPackages.pg_ed25519</li>
    <li>postgresql17JitPackages.plv8</li>
    <li>postgresql17JitPackages.smlar</li>
    <li>postgresql17Packages.cstore_fdw</li>
  </ul>
</details>
<details>
  <summary>:x: 32 packages failed to build:</summary>
  <ul>
    <li>postgresql12JitPackages.lantern</li>
    <li>postgresql12JitPackages.plr</li>
    <li>postgresql12Packages.plr</li>
    <li>postgresql13JitPackages.lantern</li>
    <li>postgresql13JitPackages.plr</li>
    <li>postgresql13Packages.plr</li>
    <li>postgresql14JitPackages.lantern</li>
    <li>postgresql14JitPackages.plr</li>
    <li>postgresql14Packages.plr</li>
    <li>postgresql15JitPackages.lantern</li>
    <li>postgresql15JitPackages.plr</li>
    <li>postgresql15Packages.plr</li>
    <li>postgresql16JitPackages.lantern</li>
    <li>postgresql16JitPackages.plr</li>
    <li>postgresql16Packages.plr</li>
    <li>postgresql17JitPackages.citus</li>
    <li>postgresql17JitPackages.lantern</li>
    <li>postgresql17JitPackages.pg_auto_failover</li>
    <li>postgresql17JitPackages.pgvecto-rs</li>
    <li>postgresql17JitPackages.plr</li>
    <li>postgresql17JitPackages.repmgr</li>
    <li>postgresql17JitPackages.timescaledb</li>
    <li>postgresql17JitPackages.timescaledb-apache</li>
    <li>postgresql17JitPackages.timescaledb_toolkit</li>
    <li>postgresql17Packages.citus</li>
    <li>postgresql17Packages.pg_auto_failover</li>
    <li>postgresql17Packages.pgvecto-rs</li>
    <li>postgresql17Packages.plr</li>
    <li>postgresql17Packages.repmgr</li>
    <li>postgresql17Packages.timescaledb</li>
    <li>postgresql17Packages.timescaledb-apache</li>
    <li>postgresql17Packages.timescaledb_toolkit</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 180 packages built:</summary>
  <ul>
    <li>postgresql12JitPackages.pg_cron</li>
    <li>postgresql12JitPackages.pg_similarity</li>
    <li>postgresql12JitPackages.pg_squeeze</li>
    <li>postgresql12JitPackages.pg_topn</li>
    <li>postgresql12JitPackages.pgroonga</li>
    <li>postgresql12JitPackages.tds_fdw</li>
    <li>postgresql12Packages.lantern</li>
    <li>postgresql12Packages.pg_cron</li>
    <li>postgresql12Packages.pg_similarity</li>
    <li>postgresql12Packages.pg_squeeze</li>
    <li>postgresql12Packages.pg_topn</li>
    <li>postgresql12Packages.pgroonga</li>
    <li>postgresql12Packages.plv8</li>
    <li>postgresql12Packages.tds_fdw</li>
    <li>postgresql13JitPackages.pg_cron</li>
    <li>postgresql13JitPackages.pg_ivm</li>
    <li>postgresql13JitPackages.pg_similarity</li>
    <li>postgresql13JitPackages.pg_squeeze</li>
    <li>postgresql13JitPackages.pg_topn</li>
    <li>postgresql13JitPackages.pgroonga</li>
    <li>postgresql13JitPackages.tds_fdw</li>
    <li>postgresql13Packages.lantern</li>
    <li>postgresql13Packages.pg_cron</li>
    <li>postgresql13Packages.pg_ivm</li>
    <li>postgresql13Packages.pg_similarity</li>
    <li>postgresql13Packages.pg_squeeze</li>
    <li>postgresql13Packages.pg_topn</li>
    <li>postgresql13Packages.pgroonga</li>
    <li>postgresql13Packages.plv8</li>
    <li>postgresql13Packages.tds_fdw</li>
    <li>postgresql14JitPackages.pg_cron</li>
    <li>postgresql14JitPackages.pg_ivm</li>
    <li>postgresql14JitPackages.pg_similarity</li>
    <li>postgresql14JitPackages.pg_squeeze</li>
    <li>postgresql14JitPackages.pg_topn</li>
    <li>postgresql14JitPackages.pgroonga</li>
    <li>postgresql14JitPackages.tds_fdw</li>
    <li>postgresql14Packages.lantern</li>
    <li>postgresql14Packages.pg_cron</li>
    <li>postgresql14Packages.pg_ivm</li>
    <li>postgresql14Packages.pg_similarity</li>
    <li>postgresql14Packages.pg_squeeze</li>
    <li>postgresql14Packages.pg_topn</li>
    <li>postgresql14Packages.pgroonga</li>
    <li>postgresql14Packages.plv8</li>
    <li>postgresql14Packages.tds_fdw</li>
    <li>postgresql15JitPackages.pg_cron</li>
    <li>postgresql15JitPackages.pg_ivm</li>
    <li>postgresql15JitPackages.pg_similarity</li>
    <li>postgresql15JitPackages.pg_squeeze</li>
    <li>postgresql15JitPackages.pg_topn</li>
    <li>postgresql15JitPackages.pgroonga</li>
    <li>postgresql15JitPackages.tds_fdw</li>
    <li>postgresql15Packages.lantern</li>
    <li>postgresql15Packages.pg_cron</li>
    <li>postgresql15Packages.pg_ivm</li>
    <li>postgresql15Packages.pg_similarity</li>
    <li>postgresql15Packages.pg_squeeze</li>
    <li>postgresql15Packages.pg_topn</li>
    <li>postgresql15Packages.pgroonga</li>
    <li>postgresql15Packages.plv8</li>
    <li>postgresql15Packages.tds_fdw</li>
    <li>postgresql16JitPackages.pg_cron</li>
    <li>postgresql16JitPackages.pg_ivm</li>
    <li>postgresql16JitPackages.pg_similarity</li>
    <li>postgresql16JitPackages.pg_squeeze</li>
    <li>postgresql16JitPackages.pg_topn</li>
    <li>postgresql16JitPackages.pgroonga</li>
    <li>postgresql16JitPackages.tds_fdw</li>
    <li>postgresql16Packages.lantern</li>
    <li>postgresql16Packages.pg_cron</li>
    <li>postgresql16Packages.pg_ivm</li>
    <li>postgresql16Packages.pg_similarity</li>
    <li>postgresql16Packages.pg_squeeze</li>
    <li>postgresql16Packages.pg_topn</li>
    <li>postgresql16Packages.pgroonga</li>
    <li>postgresql16Packages.plv8</li>
    <li>postgresql16Packages.tds_fdw</li>
    <li>postgresql17JitPackages.anonymizer</li>
    <li>postgresql17JitPackages.apache_datasketches</li>
    <li>postgresql17JitPackages.h3-pg</li>
    <li>postgresql17JitPackages.hypopg</li>
    <li>postgresql17JitPackages.jsonb_deep_sum</li>
    <li>postgresql17JitPackages.periods</li>
    <li>postgresql17JitPackages.pg_bigm</li>
    <li>postgresql17JitPackages.pg_cron</li>
    <li>postgresql17JitPackages.pg_embedding</li>
    <li>postgresql17JitPackages.pg_hint_plan</li>
    <li>postgresql17JitPackages.pg_hll</li>
    <li>postgresql17JitPackages.pg_ivm</li>
    <li>postgresql17JitPackages.pg_libversion</li>
    <li>postgresql17JitPackages.pg_net</li>
    <li>postgresql17JitPackages.pg_partman</li>
    <li>postgresql17JitPackages.pg_rational</li>
    <li>postgresql17JitPackages.pg_relusage</li>
    <li>postgresql17JitPackages.pg_repack</li>
    <li>postgresql17JitPackages.pg_roaringbitmap</li>
    <li>postgresql17JitPackages.pg_safeupdate</li>
    <li>postgresql17JitPackages.pg_similarity</li>
    <li>postgresql17JitPackages.pg_squeeze</li>
    <li>postgresql17JitPackages.pg_topn</li>
    <li>postgresql17JitPackages.pg_uuidv7</li>
    <li>postgresql17JitPackages.pgaudit</li>
    <li>postgresql17JitPackages.pgjwt</li>
    <li>postgresql17JitPackages.pgmq</li>
    <li>postgresql17JitPackages.pgroonga</li>
    <li>postgresql17JitPackages.pgrouting</li>
    <li>postgresql17JitPackages.pgsodium</li>
    <li>postgresql17JitPackages.pgsql-http</li>
    <li>postgresql17JitPackages.pgtap</li>
    <li>postgresql17JitPackages.pgvector</li>
    <li>postgresql17JitPackages.plpgsql_check</li>
    <li>postgresql17JitPackages.postgis</li>
    <li>postgresql17JitPackages.postgis.doc</li>
    <li>postgresql17JitPackages.rum</li>
    <li>postgresql17JitPackages.system_stats</li>
    <li>postgresql17JitPackages.tds_fdw</li>
    <li>postgresql17JitPackages.temporal_tables</li>
    <li>postgresql17JitPackages.tsearch_extras</li>
    <li>postgresql17JitPackages.tsja</li>
    <li>postgresql17JitPackages.wal2json</li>
    <li>postgresql17Packages.anonymizer</li>
    <li>postgresql17Packages.apache_datasketches</li>
    <li>postgresql17Packages.h3-pg</li>
    <li>postgresql17Packages.hypopg</li>
    <li>postgresql17Packages.jsonb_deep_sum</li>
    <li>postgresql17Packages.lantern</li>
    <li>postgresql17Packages.periods</li>
    <li>postgresql17Packages.pg_bigm</li>
    <li>postgresql17Packages.pg_cron</li>
    <li>postgresql17Packages.pg_ed25519</li>
    <li>postgresql17Packages.pg_embedding</li>
    <li>postgresql17Packages.pg_hint_plan</li>
    <li>postgresql17Packages.pg_hll</li>
    <li>postgresql17Packages.pg_ivm</li>
    <li>postgresql17Packages.pg_libversion</li>
    <li>postgresql17Packages.pg_net</li>
    <li>postgresql17Packages.pg_partman</li>
    <li>postgresql17Packages.pg_rational</li>
    <li>postgresql17Packages.pg_relusage</li>
    <li>postgresql17Packages.pg_repack</li>
    <li>postgresql17Packages.pg_roaringbitmap</li>
    <li>postgresql17Packages.pg_safeupdate</li>
    <li>postgresql17Packages.pg_similarity</li>
    <li>postgresql17Packages.pg_squeeze</li>
    <li>postgresql17Packages.pg_topn</li>
    <li>postgresql17Packages.pg_uuidv7</li>
    <li>postgresql17Packages.pgaudit</li>
    <li>postgresql17Packages.pgjwt</li>
    <li>postgresql17Packages.pgmq</li>
    <li>postgresql17Packages.pgroonga</li>
    <li>postgresql17Packages.pgrouting</li>
    <li>postgresql17Packages.pgsodium</li>
    <li>postgresql17Packages.pgsql-http</li>
    <li>postgresql17Packages.pgtap</li>
    <li>postgresql17Packages.pgvector</li>
    <li>postgresql17Packages.plpgsql_check</li>
    <li>postgresql17Packages.plv8</li>
    <li>postgresql17Packages.postgis</li>
    <li>postgresql17Packages.postgis.doc</li>
    <li>postgresql17Packages.rum</li>
    <li>postgresql17Packages.smlar</li>
    <li>postgresql17Packages.system_stats</li>
    <li>postgresql17Packages.tds_fdw</li>
    <li>postgresql17Packages.temporal_tables</li>
    <li>postgresql17Packages.tsearch_extras</li>
    <li>postgresql17Packages.tsja</li>
    <li>postgresql17Packages.wal2json</li>
    <li>postgresql_17</li>
    <li>postgresql_17.debug</li>
    <li>postgresql_17.dev</li>
    <li>postgresql_17.doc</li>
    <li>postgresql_17.lib</li>
    <li>postgresql_17.man</li>
    <li>postgresql_17_jit</li>
    <li>postgresql_17_jit.debug</li>
    <li>postgresql_17_jit.dev</li>
    <li>postgresql_17_jit.doc</li>
    <li>postgresql_17_jit.lib</li>
    <li>postgresql_17_jit.man</li>
  </ul>
</details>

**Comment by kirillrdy** [comment]
you can ignore plr build error, something with my system 

```
trying https://github.com/postgres-plr/plr/archive/REL8_4_7.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (77) error setting certificate file: /nix/store/mqvcvn7vpzsrihgj3ph39mbvyyj435bc-nss-cacert-3.104/etc/ssl/certs/ca-bundle.crt
```

fails in nix-build, but works in firefox, as for other build failures shouldn't be a blocker

**Review by kirillrdy — APPROVED** [review]

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by Ma27** [comment]
Will try to take a look today.

**Comment by SuperSandro2000** [comment]
```
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/9q013zfhhsri1i0yiy2jvyjygbig5kgy-source
       > source root is source
       > Executing cargoSetupPostUnpackHook
       > unpacking source archive /nix/store/idm3m7hwx194hcl9lk4ydf56w8v8lw1v-timescaledb_toolkit-1.18.0-vendor.tar.gz
       > Finished cargoSetupPostUnpackHook
       > Running phase: patchPhase
       > Executing cargoSetupPostPatchHook
       > Validating consistency between /build/source/Cargo.lock and /build/timescaledb_toolkit-1.18.0-vendor.tar.gz/Cargo.lock
       > Finished cargoSetupPostPatchHook
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > Running phase: buildPhase
       > Executing cargo-pgrx buildPhase
       > error: unexpected argument '--pg17' found
       >
       >   tip: a similar argument exists: '--pg16'
       >
       > Usage: cargo pgrx init <--pg11 <PG11>|--pg12 <PG12>|--pg13 <PG13>|--pg14 <PG14>|--pg15 <PG15>|--pg16 <PG16>|--base-port <BASE_PORT>|--base-testing-port <BASE_TESTING_PORT>|--configu
re-flag <CONFIGURE_FLAG>|--valgrind>
       >
       > For more information, try '--help'.
       For full logs, run 'nix log /nix/store/m8c1zlmjbzylx1ci1x3fy5fivv3yx6d9-timescaledb_toolkit-1.18.0.drv'.
```

```
       > [ 96%] Built target phony_always_runs                                                                                                                            13:43:18 [468/47203]
       > [100%] Linking C shared module lantern.so
       > ./third_party/usearch/include/usearch/index_plugins.hpp:1217:9: loop not vectorized: loop control flow is not understood by vectorizer
       > ld: warning: ./third_party/usearch/include/usearch/index_plugins.hpp:1217:9: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformatio
n might be disabled or specified as part of an unsupported transformation ordering
       > ./third_party/usearch/include/usearch/index_plugins.hpp:1217:9: loop not vectorized: loop control flow is not understood by vectorizer
       > ld: warning: ./third_party/usearch/include/usearch/index_plugins.hpp:1217:9: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformatio
n might be disabled or specified as part of an unsupported transformation ordering
       > ./third_party/usearch/include/usearch/index_plugins.hpp:1217:9: loop not vectorized: loop control flow is not understood by vectorizer
       > ld: warning: ./third_party/usearch/include/usearch/index_plugins.hpp:1217:9: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformatio
n might be disabled or specified as part of an unsupported transformation ordering
       > [100%] Built target lantern
       > /nix/store/717iy55ncqs0wmhdkwc5fg2vci5wbmq8-bash-5.2p32/bin/bash: line 1: /build/source/scripts/link_llvm_objects.sh: cannot execute: required file not found
       > make[2]: *** [CMakeFiles/link_llvm_objects.dir/build.make:70: CMakeFiles/link_llvm_objects] Error 127
       > make[1]: *** [CMakeFiles/Makefile2:124: CMakeFiles/link_llvm_objects.dir/all] Error 2
       > make: *** [Makefile:156: all] Error 2
       For full logs, run 'nix log /nix/store/ps7mih9n54kfbcixjrb35j548c8r1v9c-postgresql-lantern-0.3.3.drv'.
```

```
       > Finished cargoSetupPostUnpackHook
       > Running phase: patchPhase
       > applying patch /nix/store/6aycak0abnwp2810409yll8280h5fb62-0001-read-clang-flags-from-environment.diff
       > patching file crates/c/build.rs
       > Executing cargoSetupPostPatchHook
       > Validating consistency between /build/source/Cargo.lock and /build/cargo-vendor-dir/Cargo.lock
       > Finished cargoSetupPostPatchHook
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > Running phase: buildPhase
       > Executing cargo-pgrx buildPhase
       > error: unexpected argument '--pg17' found
       >
       >   tip: a similar argument exists: '--pg16'
       >
       > Usage: cargo pgrx init <--pg12 <PG12>|--pg13 <PG13>|--pg14 <PG14>|--pg15 <PG15>|--pg16 <PG16>|--base-port <BASE_PORT>|--base-testing-port <BASE_TESTING_PORT>|--configure-flag <CONFI
GURE_FLAG>|--valgrind|--jobs <JOBS>>
       >
       > For more information, try '--help'.
       For full logs, run 'nix log /nix/store/8w349sanqwlnznag33c8bhnlm09gjsc4-pgvecto-rs-0.3.0.drv'.
```

**Review by Ma27 — CHANGES_REQUESTED** [review]
I get a different hash for plr:

```
error: hash mismatch in fixed-output derivation '/nix/store/mxfgna9mmiiykdy1zlbc2qv8fzlznk1z-source.drv':
        likely URL: https://github.com/postgres-plr/plr/archive/REL8_4_7.tar.gz
         specified: sha256-t5tniqTYNCXb3Q4ii69kr+rx7e9LIkLzlcpqk4X8wiQ=
            got:    sha256-PdvFEmtKfLT/xfaf6obomPR5hKC9F+wqpfi1heBphRk=
```

Do you still have the old one so we can investigate what has changed?

**Comment by SuperSandro2000** [comment]
> pg17 is not supported upstream, yet

Maybe we should just mark them as broken to reduce the noise? that would it make way easier for me to merge this PR.

**Comment by Ma27** [comment]
> Maybe we should just mark them as broken to reduce the noise? that would it make way easier for me to merge this PR.

Agreed.

**Review by Ma27 — APPROVED** [review]
Thanks!

And again, I'd like to emphasize that your work on the postgresql subsystem is greatly appreciated! <3

**Comment by philon123** [comment]
Hi @wolfgangwalther I'm not sure where to write, hope this isn't too bad of a place. 


I noticed [your comment](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/servers/sql/postgresql/ext/timescaledb.nix#L45) about TimescaleDB v2.17 dropping support for Postgres 13, and that blocking the upgrade of the package. I don't understand the details of this conflict, however I would like to keep my TimescaleDB and Postgres upgraded to the newest stable version, and was wondering when it will be possible? At the moment, the latest version in nixpkgs is 2.14.2, which was released on 2024-02-20 and is quite outdated. 


If there is anything I can do to support the update, I would be happy to try. If I could locally build 2.17.2 and somehow use that in my flake, I would also be glad but a link in the right direction would be amazing!

**Pull request merged**
