### PR TITLE
losslesscut-bin: 3.58.0 -> 3.61.1

### LINKED ISSUE #286569: Update request: losslesscut-bin 3.58.0 → 3.59.1
- Package name: losslesscut-bin
- Latest released version: [3.59.1](https://github.com/mifi/lossless-cut/releases/tag/v3.59.1)

- Current version on the unstable channel: 3.58.0
- Current version on the stable/release channel: 3.58.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@ShamrockLee

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by ShamrockLee**
## Description of changes

This PR closes #286569 #315306

Let's also backport this version update after testing this PR.

Cc: @jyothisv @TanvirOnGH

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by TanvirOnGH** [comment]
Works fine. Merge please.

**Comment by ShamrockLee** [comment]
@TanvirOnGH Thank you!

Could you help me run nixpkgs-review, please?

```sh
cd path/to/nixpkgs
nix run --extra-experimental-featurus "nix-command flakes" github:NixOS/nixpkgs/nixos-unstable#nixpkgs-review pr 317795
```

**Comment by TanvirOnGH** [comment]
@ShamrockLee 
```nix
nixpkgs on  master 
~ nix run github:NixOS/nixpkgs/nixos-unstable#nixpkgs-review pr 317795
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/317795/head:refs/nixpkgs-review/1
remote: Enumerating objects: 74, done.
remote: Counting objects: 100% (58/58), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 74 (delta 45), reused 52 (delta 43), pack-reused 16
Unpacking objects: 100% (74/74), 292.78 KiB | 702.00 KiB/s, done.
From https://github.com/NixOS/nixpkgs
 * [new branch]                master                -> refs/nixpkgs-review/0
 * [new ref]                   refs/pull/317795/head -> refs/nixpkgs-review/1
$ git worktree add /home/user/.cache/nixpkgs-review/pr-317795/nixpkgs f7207adcc68d9cafa29e3cd252a18743ae512c6a
Preparing worktree (detached HEAD f7207adcc68d)
Updating files: 100% (41566/41566), done.
HEAD is now at f7207adcc68d Merge pull request #318858 from r-ryantm/auto-update/seaweedfs
$ git merge --no-commit --no-ff 56e05f27a3a9da27f74a03e0c7a5907f53c14d14
Auto-merging pkgs/applications/video/losslesscut-bin/default.nix
Automatic merge went well; stopped before committing as requested
$ nix build --file /nix/store/89ax6r73alrwx78yhlbnff1sdmqq886r-nixpkgs-review-2.10.4/lib/python3.11/site-packages/nixpkgs_review/nix/review-shell.nix --nix-path nixpkgs=/home/user/.cache/nixpkgs-review/pr-317795/nixpkgs nixpkgs-overlays=/tmp/tmpzdfqytvm --extra-experimental-features nix-command no-url-literals --no-link --keep-going --no-allow-import-from-derivation --option build-use-sandbox relaxed --argstr system x86_64-linux --argstr nixpkgs-path /home/user/.cache/nixpkgs-review/pr-317795/nixpkgs --argstr nixpkgs-config-path /tmp/tmpudhtoawo.nix --argstr attrs-path /home/user/.cache/nixpkgs-review/pr-317795/attrs.nix

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/317795

1 package built:
losslesscut-bin

$ /nix/store/fwrdsdlpqfhm6p4z9dk19vniw14mmq3s-nix-2.18.2/bin/nix-shell --argstr system x86_64-linux --argstr nixpkgs-path /home/user/.cache/nixpkgs-review/pr-317795/nixpkgs --argstr nixpkgs-config-path /tmp/tmpudhtoawo.nix --argstr attrs-path /home/user/.cache/nixpkgs-review/pr-317795/attrs.nix --nix-path nixpkgs=/home/user/.cache/nixpkgs-review/pr-317795/nixpkgs nixpkgs-overlays=/tmp/tmpzdfqytvm /nix/store/89ax6r73alrwx78yhlbnff1sdmqq886r-nixpkgs-review-2.10.4/lib/python3.11/site-packages/nixpkgs_review/nix/review-shell.nix
```

**Comment by ShamrockLee** [comment]
@TanvirOnGH Thank you very much for helping test it!

> Works fine. Merge, please.

You could formally approve this PR through GitHub code review to help the committers notice it.

**Review by ghost — APPROVED** [review]

**Review by Aleksanaa — APPROVED** [review]

**Pull request merged**
