### PR TITLE
Add Thrust 0.7.6

### PR DESCRIPTION
**Pull request by ozanvos**
I've created a package for [Thrust](https://github.com/breach/thrust) based on atom-shell package. This is my first go at submitting a nix package, please let me know if there are any problems.

### CODE REVIEW

**Comment by lethalman** [comment]
We prefer to compile sources rather than downloading binaries when possible.

**Comment by vcunat** [comment]
I just tried this on master, after doing the trivial replacement ``cc.gcc`` -> ``cc.cc``, but nothing happens when I run the executable (no window appears).

**Comment by osener** [comment]
Sorry for not following up on this. Before submitting this I tried compiling Thrust manually and got discouraged about all the bootstrap process and Chromium compilation so I packaged the binaries (which are their intended distribution method) the way node-webkit and atom-shell do it. After @lethalman's comment I wanted to try source builds again but never got around to it.

@vcunat This is a framework like node-webkit but instead of using JS code it uses STDIN for receiving commands and creating the window. My main intention of packaging Thrust was that I have a Haskell wrapper for it (still unpublished, but the API looks like [this](https://gist.github.com/osener/17f16ebd78064d2931b9)) and their binaries don't work on NixOS.

A kinda messy one-liner for creating a window would be:
```sh
echo '{"_type":"window","_id":1,"_action":"create","_args":{"tag":"WinArgs","root_url":"http://nixos.org/"}}\n--(Foo)++__THRUST_SHELL_BOUNDARY__++(Bar)--\n{"_id":3,"_method":"show","_action":"call","_args":{"tag":"WinArgs"},"_target":1}\n--(Foo)++__THRUST_SHELL_BOUNDARY__++(Bar)--' | thrust_shell
```

**Comment by vcunat** [comment]
Ah, I didn't really try to understand what it is I was trying to test :-) I was inclined to merge, as you should know much better than me whether it works or not, but still... the example you provided segfaults for me, which could be a sign of some packaging problem. Does it work for you (I was on commit af81942cc599) ?

**Comment by osener** [comment]
@vcunat I've only just gotten around to testing this with an up-to-date NixOS installation (I couldn't upgrade my system for some reason).  It took me an unreasonable amount of time to test it (sorry about that) but I can't reproduce the segfault with the fresh installation. 

The problem might be that I'd only tested the one-liner with zsh. In bash no window appears (but I don't get a segfault either).

**Comment by pSub** [comment]
Pushed as 97160a8644dddc2d08a2f40ee1bed7ccd53f9cc0.

**Pull request closed without merging**
