### PR TITLE
Several CVEs

### PR DESCRIPTION
**Pull request by grahamc**
# Please review.

nox-review is running on my build server. It isn't a small set of changes.
###### Things done:
- [X] Tested via `nix.useChroot`.
- [ ] Built on platform(s): .
- [ ] Tested compilation of all pkgs that depend on this change.
- [ ] Tested execution of binary products.
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
## Not Updated...

There are some CVEs I'm not updating for, because I'm going for low-hanging fruit to get as many as possible.
- https://lwn.net/Vulnerabilities/674843/ rails-html-sanitizer, used it gitlab
- https://lwn.net/Vulnerabilities/674609/ qemu, which they don't seem to have an updated release to patch?
- https://lwn.net/Vulnerabilities/674707/ webkitgtk4 which I'm not sure we use or not
- https://lwn.net/Vulnerabilities/672314/ ffmpeg, 3.0.0 is out, 2.8.6 is vulnerable, there may be a patch, and 1.x is way old. The ffmpeg nix expressions seem pretty complicated, and needlessly tied together into a "generic" expression. I'm going to leave this one be, too.
- https://lwn.net/Vulnerabilities/674075/ xen, but I think we're patched. Should we have a 4.6.1 though? 
- https://lwn.net/Vulnerabilities/668127/ firefox / thunderbird / seamonkey, the generate_sources doesn't seem to run: `./generate_sources.rb:25:in`<main>': undefined method `match' for nil:NilClass (NoMethodError)`
- https://lwn.net/Vulnerabilities/671915/ libtiff, since the patch may not fix the issue, and upstream has not released a fix.

### CODE REVIEW

**Comment by pSub** [comment]
It would be nice if you could mention the CVE number in the commit message.

**Comment by grahamc** [comment]
Will-do, @pSub. Should it be on the top-line, or in the body?

**Comment by pSub** [comment]
That doesn't matter. Thanks.

**Comment by grahamc** [comment]
Not updated, but vulnerable: gitlab, due to rails-html-sanitizer https://lwn.net/Vulnerabilities/?n=20&offset=80 -- seems to be a bit more complicated of an update than just bumping a version. Should be upped to 1.0.3 I believe.

**Comment by grahamc** [comment]
Not updated: qemu for https://lwn.net/Vulnerabilities/674609/ because they don't seem to have issued a new version.

**Comment by grahamc** [comment]
Worth checking in to if the polarssl commit fixes https://github.com/NixOS/nixpkgs/issues/6568

**Comment by grahamc** [comment]
Updated pythonmagick because its download URL changed anyway.

**Comment by grahamc** [comment]
Updated moodle to 2.8.10, but 2.8.x is only supported for security patches.

**Comment by grahamc** [comment]
I think it is ready for review. I suspect we should also backport many / all of these to 15.09.

**Comment by fpletz** [comment]
Great! Thanks! :beers:

**Comment by vcunat** [comment]
Would you test `git cherry-pick -x` of these commits on top of 15.09? It seems like smaller updates, so testing they build is probably enough.

**Comment by fpletz** [comment]
@vcunat I pushed some other security updates to master yesterday. My plan later today would be to test these and the ones from this PR on top of 15.09 and push. Didn't have time to finish that yesterday.

**Comment by vcunat** [comment]
That's fine. I saw no indication you or someone else wanting to backport them.

**Pull request merged**
