### PR TITLE
fetchurl: allow empty hash

### PR DESCRIPTION
**Pull request by matthewbauer**
Meant as a companion to https://github.com/NixOS/nix/pull/3674

This just resets outputHash if nothing is passed in.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ericson2314** [comment]
With these PRs, we can amend our tutorials to tell people to always comment out the hash when changing the URL to avoid MITM attacks.

**Review by Ericson2314 — APPROVED** [review]

**Comment by matthewbauer** [comment]
*This should probably only be merged after a Nix release contains https://github.com/NixOS/nix/pull/3674/commits/762273f1fd48b2b2f2bbedca65abfd4c07b5af05.

**Comment by baloo** [comment]
@matthewbauer I think I'm hitting an error on this:
```
$ nix eval --show-trace nixpkgs.tmux
trace: lib.zip is deprecated, use lib.zipAttrsWith instead
trace: `lib.nixpkgsVersion` is deprecated, use `lib.version` instead!
trace: `types.list` is deprecated; use `types.listOf` instead
trace: warning: types.string is deprecated because it quietly concatenates strings
trace: types.optionSet is deprecated; use types.submodule instead
trace: Warning: `showVal` is deprecated and will be removed in the next release, please use `traceSeqN`
trace: `mkStrict' is obsolete; use `mkOverride 0' instead.
error: while evaluating the attribute 'out' at /home/baloo/dev/nixpkgs/lib/customisation.nix:153:11:
while evaluating the attribute 'drvAttrs' at /nix/store/6annsr58zdx7w6zwda1zc7rpl6m1md2p-nix-2.3.7/share/nix/corepkgs/derivation.nix:12:14:
while evaluating the attribute 'stdenv' at /home/baloo/dev/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:202:18:
while evaluating the attribute 'out' at /nix/store/6annsr58zdx7w6zwda1zc7rpl6m1md2p-nix-2.3.7/share/nix/corepkgs/derivation.nix:17:7:
while evaluating the attribute 'drvAttrs' at /nix/store/6annsr58zdx7w6zwda1zc7rpl6m1md2p-nix-2.3.7/share/nix/corepkgs/derivation.nix:12:14:
while evaluating the attribute 'initialPath' at /home/baloo/dev/nixpkgs/pkgs/stdenv/generic/default.nix:114:14:
while evaluating the attribute 'out' at /home/baloo/dev/nixpkgs/lib/customisation.nix:153:11:
while evaluating the attribute 'drvAttrs' at /nix/store/6annsr58zdx7w6zwda1zc7rpl6m1md2p-nix-2.3.7/share/nix/corepkgs/derivation.nix:12:14:
while evaluating the attribute 'stdenv' at /home/baloo/dev/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:202:18:
while evaluating the attribute 'out' at /nix/store/6annsr58zdx7w6zwda1zc7rpl6m1md2p-nix-2.3.7/share/nix/corepkgs/derivation.nix:17:7:
while evaluating the attribute 'drvAttrs' at /nix/store/6annsr58zdx7w6zwda1zc7rpl6m1md2p-nix-2.3.7/share/nix/corepkgs/derivation.nix:12:14:
while evaluating the attribute 'defaultNativeBuildInputs' at /home/baloo/dev/nixpkgs/pkgs/stdenv/generic/default.nix:114:14:
while evaluating the attribute 'out' at /home/baloo/dev/nixpkgs/lib/customisation.nix:153:11:
while evaluating the attribute 'drvAttrs' at /nix/store/6annsr58zdx7w6zwda1zc7rpl6m1md2p-nix-2.3.7/share/nix/corepkgs/derivation.nix:12:14:
while evaluating the attribute 'stdenv' at /home/baloo/dev/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:202:18:
while evaluating the attribute 'out' at /nix/store/6annsr58zdx7w6zwda1zc7rpl6m1md2p-nix-2.3.7/share/nix/corepkgs/derivation.nix:17:7:
while evaluating the attribute 'drvAttrs' at /nix/store/6annsr58zdx7w6zwda1zc7rpl6m1md2p-nix-2.3.7/share/nix/corepkgs/derivation.nix:12:14:
while evaluating the attribute 'defaultNativeBuildInputs' at /home/baloo/dev/nixpkgs/pkgs/stdenv/generic/default.nix:114:14:
while evaluating the attribute 'out' at /home/baloo/dev/nixpkgs/lib/customisation.nix:153:11:
while evaluating the attribute 'drvAttrs' at /nix/store/6annsr58zdx7w6zwda1zc7rpl6m1md2p-nix-2.3.7/share/nix/corepkgs/derivation.nix:12:14:
while evaluating the attribute 'bintools' at /home/baloo/dev/nixpkgs/pkgs/build-support/cc-wrapper/default.nix:99:10:
while evaluating the attribute 'out' at /home/baloo/dev/nixpkgs/lib/customisation.nix:153:11:
while evaluating the attribute 'drvAttrs' at /nix/store/6annsr58zdx7w6zwda1zc7rpl6m1md2p-nix-2.3.7/share/nix/corepkgs/derivation.nix:12:14:
while evaluating the attribute 'bintools_bin' at /home/baloo/dev/nixpkgs/pkgs/build-support/bintools-wrapper/default.nix:82:10:
while evaluating the attribute 'out' at /home/baloo/dev/nixpkgs/lib/customisation.nix:153:11:
while evaluating the attribute 'drvAttrs' at /nix/store/6annsr58zdx7w6zwda1zc7rpl6m1md2p-nix-2.3.7/share/nix/corepkgs/derivation.nix:12:14:
while evaluating the attribute 'nativeBuildInputs' at /home/baloo/dev/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:218:11:
while evaluating the attribute 'out' at /home/baloo/dev/nixpkgs/lib/customisation.nix:153:11:
while evaluating the attribute 'drvAttrs' at /nix/store/6annsr58zdx7w6zwda1zc7rpl6m1md2p-nix-2.3.7/share/nix/corepkgs/derivation.nix:12:14:
while evaluating the attribute 'nativeBuildInputs' at /home/baloo/dev/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:218:11:
while evaluating the attribute 'out' at /home/baloo/dev/nixpkgs/lib/customisation.nix:153:11:
while evaluating the attribute 'all' at /home/baloo/dev/nixpkgs/lib/customisation.nix:149:12:
while evaluating the attribute 'pkgs' at /home/baloo/dev/nixpkgs/pkgs/development/interpreters/perl/default.nix:110:7:
while evaluating the attribute 'version' at /home/baloo/dev/nixpkgs/pkgs/top-level/perl-packages.nix:22348:3:
while evaluating the attribute 'out' at /home/baloo/dev/nixpkgs/lib/customisation.nix:153:11:
while evaluating the attribute 'drvAttrs' at /nix/store/6annsr58zdx7w6zwda1zc7rpl6m1md2p-nix-2.3.7/share/nix/corepkgs/derivation.nix:12:14:
while evaluating the attribute 'buildInputs' at /home/baloo/dev/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:221:11:
while evaluating the attribute 'out' at /home/baloo/dev/nixpkgs/lib/customisation.nix:153:11:
while evaluating the attribute 'all' at /home/baloo/dev/nixpkgs/lib/customisation.nix:149:12:
while evaluating the attribute 'pkgs' at /home/baloo/dev/nixpkgs/pkgs/development/interpreters/perl/default.nix:110:7:
while evaluating the attribute 'perlPackages' at /home/baloo/dev/nixpkgs/pkgs/top-level/perl-packages.nix:22:3:
while evaluating the attribute 'OpenGL' at /home/baloo/dev/nixpkgs/pkgs/top-level/perl-packages.nix:14917:3:
while evaluating the attribute 'outPath' at /home/baloo/dev/nixpkgs/lib/customisation.nix:164:7:
while evaluating the attribute 'buildInputs' of the derivation 'perl5.30.3-OpenGL-0.70' at /home/baloo/dev/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:192:11:
while evaluating the attribute 'propagatedBuildInputs' of the derivation 'glu-9.0.1' at /home/baloo/dev/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:192:11:
while evaluating the attribute 'buildCommand' of the derivation 'libGL-1.3.1' at /home/baloo/dev/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:192:11:
while evaluating the attribute 'buildInputs' of the derivation 'libglvnd-1.3.1' at /home/baloo/dev/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:192:11:
while evaluating the attribute 'buildInputs' of the derivation 'libX11-1.6.8' at /home/baloo/dev/nixpkgs/pkgs/servers/x11/xorg/default.nix:706:5:
while evaluating the attribute 'nativeBuildInputs' of the derivation 'xorgproto-2019.1' at /home/baloo/dev/nixpkgs/pkgs/servers/x11/xorg/default.nix:2682:5:
while evaluating the attribute 'out.outPath' at /home/baloo/dev/nixpkgs/lib/customisation.nix:156:13:
while evaluating the attribute 'nativeBuildInputs' of the derivation 'meson-0.54.2' at /home/baloo/dev/nixpkgs/pkgs/development/interpreters/python/mk-python-derivation.nix:108:3:
while evaluating 'chooseDevOutputs' at /home/baloo/dev/nixpkgs/lib/attrsets.nix:475:22, called from undefined position:
while evaluating 'optionals' at /home/baloo/dev/nixpkgs/lib/lists.nix:270:5, called from /home/baloo/dev/nixpkgs/pkgs/development/interpreters/python/mk-python-derivation.nix:120:8:
while evaluating 'hasSuffix' at /home/baloo/dev/nixpkgs/lib/strings.nix:212:5, called from /home/baloo/dev/nixpkgs/pkgs/development/interpreters/python/mk-python-derivation.nix:120:23:
while evaluating the attribute 'src.name' at /home/baloo/dev/nixpkgs/pkgs/development/tools/build-managers/meson/default.nix:13:3:
while evaluating 'makeOverridable' at /home/baloo/dev/nixpkgs/lib/customisation.nix:67:24, called from /home/baloo/dev/nixpkgs/pkgs/development/tools/build-managers/meson/default.nix:13:9:
while evaluating anonymous function at /home/baloo/dev/nixpkgs/pkgs/development/interpreters/python/fetchpypi.nix:23:21, called from /home/baloo/dev/nixpkgs/lib/customisation.nix:69:16:
anonymous function at /home/baloo/dev/nixpkgs/pkgs/build-support/fetchurl/boot.nix:5:1 called with unexpected argument 'hash', at /home/baloo/dev/nixpkgs/pkgs/development/interpreters/python/fetchpypi.nix:26:6
```

I'm running nix-2.3.7 (which I believe to be up to date) and I think no releases of nix currently includes NixOS/nix#3674

**Comment by baloo** [comment]
nevermind, I can actually use a nix unstable release:
```
nix-env -i -A nixpkgs.nixUnstable
```

**Comment by matthewbauer** [comment]
Yeah - no release contains this, but it's okay since you can get the error directly from Nix instead of Nix.

I think you could be hitting a bug though - fetchpypi will probably fail like this with fetchurl/boot.nix. It's been like that since 807413384443b3e65d8f4624b6650695f7c18e78 though.

**Comment by FRidh** [comment]
@baloo note there is also 
```
error: --- TypeError ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix
in file: /nix/store/5zl5wpzvsg2f0vczimzxhspk6bn4brgx-source/pkgs/build-support/fetchzip/default.nix (17:2)

anonymous function at /nix/store/5zl5wpzvsg2f0vczimzxhspk6bn4brgx-source/pkgs/build-support/fetchurl/boot.nix:5:1 called with unexpected argument 'recursiveHash'
```

I wish Nixpkgs would evaluate cleanly.

**Comment by baloo** [comment]
@FRidh good catch!

**Pull request merged**
