### PR TITLE
noto-fonts: update 2017-10-24 -> 2018-11-30

### PR DESCRIPTION
**Pull request by colemickens**
###### Motivation for this change

Update the Noto fonts, particularly to avoid an old ligature issue. Fixes: #51498.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by c0bw3b** [comment]
@GrahamcOfBorg build noto-fonts

**Comment by Mic92** [comment]
```
fixed-output derivation produced path '/nix/store/44l43pfm338impslqnjdbrxl9h4cfid4-noto-fonts-extra-2018-11-30' with sha256 hash '0l94aiy1b3qirg2mmbagbr0014vqk32za79pzck1acy2hgy716kq' instead of the expected hash '1lih49bqmsmblczvbl7qb1bhn
0bq8v5xkr991b3gjghpdkx584bc'
cannot build derivation '/nix/store/86vmv8dsi4vrdj6gxzcq64vlb807fgas-env.drv': 1 dependencies couldn't be built
[1 built (1 failed), 0.0 MiB DL]
error: build of '/nix/store/86vmv8dsi4vrdj6gxzcq64vlb807fgas-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/51500
1 package failed to build:
noto-fonts-extra

1 package were build:
noto-fonts
```

**Comment by lheckemann** [comment]
This should probably use fetchFromGitHub, which may fix the above hash error.

**Comment by worldofpeace** [comment]
@GrahamcOfBorg build noto-fonts

**Review by worldofpeace — APPROVED** [review]

**Comment by c0bw3b** [comment]
[It was there before](https://hydra.nixos.org/build/64564029/nixlog/1) on aarch664

**Comment by c0bw3b** [comment]
I'm confused about the naming of `$out`

On aarch64 it ends up being `/nix/store/<blah>-noto-fonts-${version}`
But on x64-linux it is `/nix/store/<blah>-noto-fonts-${rev}`

It wont prevent the use of the font but I wonder why Nix has a different behaviour

**Pull request merged**
