### PR TITLE
dde-polkit-agent: init at 0.2.1; dpa-ext-gnomekeyring: init at 0.1.0

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

- Add [dde-polkit-agent](https://github.com/linuxdeepin/dde-polkit-agent) (PolicyKit agent for Deepin Desktop Environment)

- Add [dpa-ext-gnomekeyring](https://github.com/linuxdeepin/dpa-ext-gnomekeyring) (GNOME keyring extension for dde-polkit-agent)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by romildo** [comment]
@GrahamcOfBorg build deepin.dde-polkit-agent deepin.dpa-ext-gnomekeyring

**Comment by xeji** [comment]
@GrahamcOfBorg eval

**Comment by romildo** [comment]
@GrahamcOfBorg build deepin.dde-polkit-agent deepin.dpa-ext-gnomekeyring

**Comment by romildo** [comment]
@xeji I think it is ok now. It seems that `grahamcofborg-eval` was failing because of `libgnome_keyring3`. After replacing it by `gnome3.libgnome-keyring` it succeeds.

**Pull request merged**
