### PR TITLE
ibus-table: revert 1.9.21 -> 1.9.20

### PR DESCRIPTION
**Pull request by laMudri**
###### Motivation for this change
Reverts the two commits of #53080, because of issue #56621.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by xeji — DISMISSED** [review]
Most of these 13 commits look like they don't belong here.

**Comment by laMudri** [comment]
I've now cleaned this up and tested again.

**Comment by jtojnar** [comment]
I would prefer a proper fix with `wrapGAppsHook`.

**Comment by laMudri** [comment]
Better solution at #61978.

**Pull request closed without merging**
