### PR TITLE
nginx: fix compatibility with zlib-ng

### LINKED ISSUE #357522: nginx: gzip filter failed to use preallocated memory: 350336 of 336176
## Describe the bug

Since NixOS 24.11, nginx (mainline / 1.27.2) with gzip enabled logs many of these:

```
gzip filter failed to use preallocated memory: 350336 of 336176 while sending to client
```

The numbers are consistent. [The formula nginx uses](https://github.com/nginx/nginx/blob/release-1.27.2/src/http/modules/ngx_http_gzip_filter_module.c#L528-L530) to determine the allocation appears to be insufficient for zlib-ng 2.2.0. See zlib-ng [release notes](https://github.com/zlib-ng/zlib-ng/releases/tag/2.2.0) and [PORTING.md](https://github.com/zlib-ng/zlib-ng/blob/2.2.0/PORTING.md?plain=1#L23). There is also an [upstream nginx issue](https://github.com/nginx/nginx/issues/263).

I'm not sure if the patch listed in the upstream issue, from https://github.com/zlib-ng/patches/tree/master/nginx, is something we would want. Or maybe just the portion that adjusts the allocation formula.

EDIT: Applying just this hunk appears to fix the issue for me:
https://github.com/zlib-ng/patches/blob/5a036c0a00120c75ee573b27f4f44ade80d82ff2/nginx/1.26.2-zlib-ng.patch#L125-L157

This hunk applies cleanly to both current stable and mainline in NixOS 24.11.

## Steps To Reproduce

1. Enable nginx with gzip compression, for example via `services.nginx.recommendedGzipSettings = true`
2. Request a resource with `Accept-Encoding: gzip`. (The resource must be larger than `gzip_min_length`, which is 256 with NixOS recommended settings.)

## Expected behavior

No error logged.

## Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.60, NixOS, 24.11 (Vicuna), 24.11.20241116.057f63b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `""`
 - nixpkgs: `/nix/store/idq1bmwwy9rlkc21hccvx42wlwpxsx1f-source`
```

## Notify maintainers

nginx maintainers: @fpletz @RaitoBezarius @dasJ @Conni2461 @helsinki-Jo @ulrikstrid 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by fpletz**
Fix #357522.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by dasJ — APPROVED** [review]

**Comment by Izorkin** [comment]
Small fix:
```diff
diff --git a/pkgs/servers/http/nginx/generic.nix b/pkgs/servers/http/nginx/generic.nix
index 12c3e2ed6302..c576031da8ea 100644
--- a/pkgs/servers/http/nginx/generic.nix
+++ b/pkgs/servers/http/nginx/generic.nix
@@ -156,7 +156,7 @@ stdenv.mkDerivation {
       '';
     })
     ./nix-skip-check-logs-path.patch
-  ] ++ lib.optionals (lib.elem pname ["nginx" "angie"]) [
+  ] ++ lib.optionals (lib.elem pname [ "angie" "angieQuic" "nginx" "nginxQuic" ]) [
     # https://github.com/NixOS/nixpkgs/issues/357522
     # https://github.com/zlib-ng/patches/blob/5a036c0a00120c75ee573b27f4f44ade80d82ff2/nginx/README.md
     (fetchpatch {

```

**Comment by fpletz** [comment]
Thanks for the hint! I think I'll just reverse the pname check because the only incompatible variant is actually `openresty`.

**Comment by Izorkin** [comment]
There's also `tengine` package.

**Review by Izorkin — APPROVED** [review]

**Review by Izorkin — APPROVED** [review]

**Review by ulrikstrid — APPROVED** [review]

**Comment by fpletz** [comment]
Pushed another small fix for Darwin.

**Review by ulrikstrid — APPROVED** [review]

**Pull request merged**
