### PR TITLE
mumble: 1.4.287 -> 1.5.634

### PR DESCRIPTION
**Pull request by felixsinger**
## Description of changes

There are still issues left and at least one more release candidate is expected. So for now this pull request just serves for build-tesing.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by infinisil** [comment]
Could you please remove me as a maintainer? I don't have a lot of time to maintain packages recently, and I'm not using mumble anymore right now either.

Perhaps @K900 would be willing to become a maintainer instead?

**Comment by felixsinger** [comment]
@Lilacious volunteered to join as a maintainer.

@infinisil Could you create a pull request? I feel it's a bit weird to remove other people. I rather would like to ack it :)

**Comment by infinisil** [comment]
Fair enough, will do, thanks!

**Comment by infinisil** [comment]
( https://github.com/NixOS/nixpkgs/pull/302858 )

**Comment by Lilacious** [comment]
Updated to a new release candidate.

**Comment by felixsinger** [comment]
Mumble stable 1.5.634 just got released.

**Comment by felixsinger** [comment]
@infinisil I assume you are not interested in reviewing. So I'm removing you from reviewers, since you said earlier that you don't use it anyway. You are welcome to review though!

**Comment by keenanweaver** [comment]
Getting a build error with the overlay:

```
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/298758/head:refs/nixpkgs-review/1
$ git worktree add /home/keenan/.cache/nixpkgs-review/pr-298758-1/nixpkgs 3f5dbb066792fedc1d8cd889fb60c7ac58444f6c
Preparing worktree (detached HEAD 3f5dbb066792)
Updating files: 100% (41127/41127), done.
HEAD is now at 3f5dbb066792 Merge pull request #312883 from christoph-heiss/floorp/update
$ git merge --no-commit --no-ff 60535327cfee93c99da29a7dbdebcc704b6934f3
Automatic merge went well; stopped before committing as requested
$ nix build --file /nix/store/n0ahhfycjdkwvzzr2sq8h8z71n2w5yzk-nixpkgs-review-2.10.4/lib/python3.11/site-packages/nixpkgs_review/nix/review-shell.nix --nix-path nixpkgs=/home/keenan/.cache/nixpkgs-review/pr-298758-1/nixpkgs nixpkgs-overlays=/tmp/tmpurgzhetp --extra-experimental-features nix-command no-url-literals --no-link --keep-going --no-allow-import-from-derivation --option build-use-sandbox relaxed --argstr system x86_64-linux --argstr nixpkgs-path /home/keenan/.cache/nixpkgs-review/pr-298758-1/nixpkgs --argstr nixpkgs-config-path /tmp/tmpu0y7gcay.nix --argstr attrs-path /home/keenan/.cache/nixpkgs-review/pr-298758-1/attrs.nix
error: builder for '/nix/store/lw76ignrp1ny3zm9jfhnmyz4vaxmp4ia-mumble-1.5.634.drv' failed with exit code 2;
       last 25 log lines:
       > [ 42%] Building CXX object src/CMakeFiles/shared.dir/ServerResolverRecord.cpp.o
       > [ 42%] Building CXX object src/CMakeFiles/shared.dir/SSL.cpp.o
       > [ 43%] Building CXX object src/CMakeFiles/shared.dir/SSLLocks.cpp.o
       > [ 43%] Building CXX object src/CMakeFiles/shared.dir/Timer.cpp.o
       > [ 43%] Building CXX object src/CMakeFiles/shared.dir/UnresolvedServerAddress.cpp.o
       > [ 43%] Built target se
       > [ 43%] Building CXX object src/CMakeFiles/shared.dir/Version.cpp.o
       > [ 44%] Building CXX object src/CMakeFiles/shared.dir/VolumeAdjustment.cpp.o
       > [ 44%] Building CXX object src/CMakeFiles/shared.dir/crypto/CryptographicHash.cpp.o
       > [ 44%] Building CXX object src/CMakeFiles/shared.dir/crypto/CryptographicRandom.cpp.o
       > [ 44%] Building CXX object src/CMakeFiles/shared.dir/crypto/CryptStateOCB2.cpp.o
       > /build/source/src/MumbleProtocol.cpp: In instantiation of 'bool Mumble::Protocol::UDPDecoder<role>::decodeAudio_legacy(gsl::span<const unsigned char>, Mumble::Protocol::AudioCodec) [with Mumble::Protocol::Role role = Mumble::Protocol::Role::Client]':
       > /build/source/src/MumbleProtocol.cpp:885:2:   required from here
       > /build/source/src/MumbleProtocol.cpp:784:71: error: conversion from 'uint64_t' {aka 'long long unsigned int'} to 'gsl::span<unsigned char>::size_type' {aka 'unsigned int'} may change value [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wconversion-Werror=conversion8;;]
       >   784 |                 m_audioData.payload = gsl::span< byte >(payloadBegin, payloadSize);
       >       |                                                                       ^~~~~~~~~~~
       > /build/source/src/MumbleProtocol.cpp: In instantiation of 'bool Mumble::Protocol::UDPDecoder<role>::decodeAudio_legacy(gsl::span<const unsigned char>, Mumble::Protocol::AudioCodec) [with Mumble::Protocol::Role role = Mumble::Protocol::Role::Server]':
       > /build/source/src/MumbleProtocol.cpp:885:2:   required from here
       > /build/source/src/MumbleProtocol.cpp:784:71: error: conversion from 'uint64_t' {aka 'long long unsigned int'} to 'gsl::span<unsigned char>::size_type' {aka 'unsigned int'} may change value [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wconversion-Werror=conversion8;;]
       > [ 45%] Building CXX object src/CMakeFiles/shared.dir/__/3rdparty/arc4random/arc4random_uniform.cpp.o
       > cc1plus: all warnings being treated as errors
       > make[2]: *** [src/CMakeFiles/shared.dir/build.make:242: src/CMakeFiles/shared.dir/MumbleProtocol.cpp.o] Error 1
       > make[2]: *** Waiting for unfinished jobs....
       > make[1]: *** [CMakeFiles/Makefile2:1203: src/CMakeFiles/shared.dir/all] Error 2
       > make: *** [Makefile:136: all] Error 2
       For full logs, run 'nix log /nix/store/lw76ignrp1ny3zm9jfhnmyz4vaxmp4ia-mumble-1.5.634.drv'.
error: 1 dependencies of derivation '/nix/store/4aw5ai8qwdmg5xhayg0447b7kqrcm39h-mumble-overlay-1.5.634.drv' failed to build
error: 1 dependencies of derivation '/nix/store/pq8g5vk8grvlvjki8b57hidl65l3xlsv-review-shell.drv' failed to build

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/298758

1 package failed to build:
mumble_overlay

5 packages built:
ioq3-scion ioquake3 mumble murmur quake3demo

error: build log of '/nix/store/4aw5ai8qwdmg5xhayg0447b7kqrcm39h-mumble-overlay-1.5.634.drv^*' is not available
error: build log of '/nix/store/3k3cngblka7pfrxhj3n901w7b8x8bg84-mumble-overlay-1.5.634' is not available
$ /nix/store/62nhzqm27dadv0czp5gqnnc38xfbi8k4-nix-2.18.2/bin/nix-shell --argstr system x86_64-linux --argstr nixpkgs-path /home/keenan/.cache/nixpkgs-review/pr-298758-1/nixpkgs --argstr nixpkgs-config-path /tmp/tmpu0y7gcay.nix --argstr attrs-path /home/keenan/.cache/nixpkgs-review/pr-298758-1/attrs.nix --nix-path nixpkgs=/home/keenan/.cache/nixpkgs-review/pr-298758-1/nixpkgs nixpkgs-overlays=/tmp/tmpurgzhetp /nix/store/n0ahhfycjdkwvzzr2sq8h8z71n2w5yzk-nixpkgs-review-2.10.4/lib/python3.11/site-packages/nixpkgs_review/nix/review-shell.nix
```

**Comment by RSWilli** [comment]
What's the status on this? Any progress?

**Review by Lilacious — APPROVED** [review]

**Comment by Avi-D-coder** [comment]
Someone should check this but I don't believe `"-D bundled-rnnoise=OFF"` is followed by mumble with this version. This means rnnoise should no longer be a dep.

https://github.com/mumble-voip/mumble/blob/master/CMakeLists.txt

**Comment by Avi-D-coder** [comment]
See https://github.com/mumble-voip/mumble/issues/6395

**Comment by Lilacious** [comment]
Thank you for pointing it out. I didn't encounter any obvious issues testing mumble without `"-D bundled-rnnoise=OFF"`, so I will update the pr soon.

**Review by keenanweaver — APPROVED** [review]

**Review by felixsinger — COMMENTED** [review]
Looks good to me. Thanks!

**Review by Lilacious — APPROVED** [review]

**Pull request merged**
