### PR TITLE
glibc: don't use bootstrap libgcc_s

### LINKED ISSUE #36947: libgcc_s is from bootstrap tools??
## Issue description

Time for a libgcc package? :grin:

We probably want to have libgcc_s matching our compiler (and not frozen to whatever is in our bootstrap tools).

diffoscope between libgcc_s.so.1 in stdenv.cc.cc.lib and glibc: https://gist.github.com/dtzWill/596b43d5c16178f570b5357e941ea587

Note that this libgcc_s (the old one from gcc 5.3 apparently) is what everything links to (that needs it), easy example is lzip.

https://github.com/NixOS/nixpkgs/blob/25edc476fd9fe1bd8bedf571d218ba4f27fb5a27/pkgs/development/libraries/glibc/default.nix#L36
(Comment suggests the glibc used in stdenv won't be copied like this, but that's not true)

A separate libgcc package (or compiler-rt? :D) would be best, but if nothing else we probably should use a libgcc that matches our compiler.

### Steps to reproduce

```console
$ nix build -f channel:nixos-unstable glibc
$ readelf -a ./result/lib/libgcc_s.so.1
...
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000e (SONAME)             Library soname: [libgcc_s.so.1]
 0x000000000000001d (RUNPATH)            Library runpath: [/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-glibc-2.23/lib]
...
```

### PR DESCRIPTION
**Pull request by dtzWill**
Fixes #36947

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Huge rebuild, have not tested everything obviously :).

Wanted to see what broke and was surprised to find
that things didn't immediately and completely break.

I'm curious if clang works after this, we'll see!

### CODE REVIEW

**Comment by dtzWill** [comment]
Yep, `tests.cc-wrapper-clang-5` fails with this, as expected.  Need to teach it to find libs in `gcc.lib` or perhaps create a merged variant and point clang at that...

**Comment by dtzWill** [comment]
build log of the failure, for the curious: https://gist.github.com/dtzWill/9aea1fb5695788fcb0a63c96f32d36d4

This is the error we currently find w/trying to use clang as a cross-compiler, which is what started me looking into all of this :).

cc #36867

**Comment by Mic92** [comment]
@dtzWill if you are at it, could you maybe also teach clang to find c++ stdlib headers without compiler wrappers on linux? This would fix all tooling that uses libclang. I tried to fix it in https://github.com/llvm-mirror/clang/blob/master/lib/Driver/ToolChains/Linux.cpp#L758 but this only affects clang from a build directory.

**Comment by Mic92** [comment]
that one looks also interesting: https://github.com/llvm-mirror/clang/blob/master/lib/Driver/ToolChains/Linux.cpp#L804

**Comment by Ericson2314** [comment]
Yeah we need to get change GCC at some point so the compiler itself and runtime libraries are built separately. That will make the one problem caused by this go away!

**Comment by vcunat** [comment]
Hmm, I suppose we can afford this now that we have `gcc.lib` split away.

**Comment by Ekleog** [comment]
Hmm, I think this issue is currently making some builds fail for 18.03, esp. ones that are required for the channel to move forward and actually come into existence (spidermonkey_38 for i686 in particular is required by tests that are required for 18.03, if I read hydra correctly).

Would it make sense to merge this PR into `release-18.03` and see what happens, so that we get a better idea of what exactly is broken by it? Anyway I feel like the channel won't move forward until this PR or a similar one is merged, so I don't think there is much to lose (apart from hydra building time)?

(cc ZHF https://github.com/NixOS/nixpkgs/issues/36453)

**Comment by vcunat** [comment]
Eh, better not do such experiments directly on 18.03 anymore.  _After_ it's confirmed that this works good, we can cherry-pick it in 18.03.  We may have a separate temporary jobset if you think there's a risk of mass breakage, but I suppose it won't be that risky.

**Comment by pbogdan** [comment]
Plus 18.03's tested job already succeeded so as I understand it this shouldn't block channel updates (I can't see the channel being created yet but I suppose that's a different issue).

**Comment by dtzWill** [comment]
Perhaps a new jobset would be appropriate then?

**Comment by Ericson2314** [comment]
I added the 18.09 milestone because I definitely want this to happen by then. *not* trying to say it shouldn't also happen for 18.03 :).

**Comment by Ericson2314** [comment]
Can we still do this? A quick hack for LLVM in cc-wrapper should be easy enough.

**Comment by dtzWill** [comment]
Agreed, and we can probably improve the libclang situation while we're at it.

Definitely want this to happen, just not sure when :)

**Comment by lopsided98** [comment]
Doing this would make everything that needs on `libgcc_s.so` depend on gcc, right? Shouldn't we have a libgcc package like pretty much every other distribution to avoid this?

**Comment by Ericson2314** [comment]
We soon will for compiler-rt! https://github.com/NixOS/nixpkgs/pull/39743

**Comment by woffs** [comment]
Has ever anyone tried to build a i686 desktop system using this patch? I get funny errors: autoconf does not find m4, ghc does not find libgcc_s.so.1

**Comment by Ericson2314** [comment]
https://reviews.llvm.org/D28791 According to this flame war, while one can use compiler-rt instead of libgcc, crt* must still be gotten from gcc on linux. Hmm.

**Comment by bobvanderlinden** [comment]
Is this related to the failing qtbase tests on i686-linux? (https://hydra.nixos.org/build/81376319/nixlog/1) If so, it would be awesome to get it in 18.09.

**Comment by vcunat** [comment]
@bobvanderlinden: yes, see https://github.com/NixOS/nixpkgs/issues/36947#issuecomment-416372860 for the workaround I _planned_ (but doesn't seem to be happening).

**Comment by dtzWill** [comment]
Ship it? ;)

**Review by matthewbauer — APPROVED** [review]

**Comment by dtzWill** [comment]
@GrahamcOfBorg build pkgsi686Linux.dejagnu

**Comment by pbogdan** [comment]
FWIW `dejagnu` is broken on `x86_64-linux` and `i686-linux` with these changes. As I understand it the library may be dynamically loaded by glibc at runtime which makes hunting down failures more difficult (in this case it seems it's some code in `tcl` that triggers loading the library which is no longer available on the search path).

**Comment by pbogdan** [comment]
`gnutls` test suite fails too.

**Comment by matthewbauer** [comment]
@dtzWill is there any way to avoid these issues? I still like getting rid of references to libgcc... But it may need to wait for another time?

**Comment by matthewbauer** [comment]
Ok let's revert for now. ideally we can get this fixed at a later point. 319ebef3a361a914fc2e3b90bc9ff66ed8d2e107 is the revert.

**Comment by dtzWill** [comment]
Aww can't reopen this? :crying_cat_face: 

Suppose can always make a new one if someone finds time to tackle the issues.

Not sure I prefer the current state (subtle issues everywhere) over breaking things explicitly and forcing the issue, but that's just me O:).  Probably not best to do that with a release looming, I admit... :)

**Comment by amjoseph-nixpkgs** [comment]
I figured out the [root cause](https://github.com/NixOS/nixpkgs/pull/210112#issuecomment-1379542735) of these segfaults.

**Pull request merged**
