### PR TITLE
python3Packages.ptpython: 2.0.6 -> 3.0.1

### PR DESCRIPTION
**Pull request by i077**
###### Motivation for this change
ptpython here hasn't been updated in a few months, so I'm bringing it (and prompt_toolkit, a dependency which also needed updating) up to date.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
We need to wait with prompt_toolkit until all/ost reverse deps have been tested to work with it.

**Comment by i077** [comment]
@FRidh Is that a check that's triggered automatically? Or is there something I can run to evaluate packages that change?

**Comment by i077** [comment]
Okay, so the command is still running on my machine, but it has 2 remaining packages to evaluate: `python37Packages.optuna` (which is hanging on one test) and presumably something else that depends on it since it's not being built alongside. It looks like (comparing with the latest eval from [Hydra](https://hydra.nixos.org/eval/1577840)) the former is going to fail to build anyways (so thus the latter will as well), so I'm just going to stop it there.

The only thing that would be newly failing is `papis` simply because it asks for `prompt_toolkit<3,>=2.0.5`. The other packages that fail are failing the same way they did on the latest Hydra eval.

**Comment by i077** [comment]
Looks like papis [is removing](https://github.com/papis/papis/pull/243/files#diff-2eeaed663bd0d25b7e608891384b7298L69) upper bounds on their dependencies, so this would be fixed by their next release.

**Review by jonringer — APPROVED** [review]
LGTM

failures are also broken on master
```
https://github.com/NixOS/nixpkgs/pull/83401
1 package marked as broken and skipped:
ihaskell

1 package blacklisted:
tests.nixos-functions.nixosTest-test

21 package failed to build:
ape fluidasserts litecli papis python37Packages.datashader python37Packages.dftfit python37Packages.google_cloud_bigquery python37Packages.intake python37Packages.robotframework-tools python37Packages.scikit-tda python38Packages.datashader python38Packages.dftfit python38Packages.google_cloud_bigquery python38Packages.intake python38Packages.modeled python38Packages.moretools python38Packages.papis python38Packages.robotframework-tools python38Packages.scikit-tda python38Packages.zetup topydo

164 package built:
adafruit-ampy aws_shell cq-editor deeptools fdroidserver gnome3.accerciser jira-cli john jupyter lexicon mycli nbstripout pantalaimon paperless pgcli python37Packages.Nikola python37Packages.Pweave python37Packages.altair python37Packages.androguard python37Packages.ansible-kernel python37Packages.bash_kernel python37Packages.bugwarrior python37Packages.caffe python37Packages.chart-studio python37Packages.click-repl python37Packages.colorcet python37Packages.cufflinks python37Packages.dash python37Packages.greatfet python37Packages.holoviews python37Packages.hvplot python37Packages.ipdb python37Packages.ipdbplugin python37Packages.ipykernel python37Packages.ipympl python37Packages.ipyparallel python37Packages.ipython python37Packages.ipywidgets python37Packages.jira python37Packages.jupyter python37Packages.jupyter_client python37Packages.jupyter_console python37Packages.jupyter_core python37Packages.jupyterhub python37Packages.jupyterhub-ldapauthenticator python37Packages.jupyterlab python37Packages.jupyterlab_launcher python37Packages.jupyterlab_server python37Packages.jupytext python37Packages.kmapper python37Packages.line_profiler python37Packages.mask-rcnn python37Packages.modeled python37Packages.moretools python37Packages.nbconflux python37Packages.nbconvert python37Packages.nbdime python37Packages.nbformat python37Packages.nbmerge python37Packages.nbsmoke python37Packages.nbsphinx python37Packages.nbval python37Packages.notebook python37Packages.notedown python37Packages.oauthenticator python37Packages.onnx python37Packages.optuna python37Packages.papermill python37Packages.phik python37Packages.plotly python37Packages.prompt_toolkit python37Packages.ptpython python37Packages.pygmo python37Packages.python-dotenv python37Packages.qiskit-terra python37Packages.qtconsole python37Packages.rpy2 python37Packages.runway-python python37Packages.scapy python37Packages.scikit-bio python37Packages.softlayer python37Packages.sopel spyder python37Packages.spyder-kernels python37Packages.spyder-kernels_0_5 python37Packages.spyder_3 python37Packages.vega python37Packages.widgetsnbextension python37Packages.zetup python38Packages.Pweave python38Packages.altair python38Packages.androguard python38Packages.ansible-kernel python38Packages.bash_kernel python38Packages.bugwarrior python38Packages.caffe python38Packages.chart-studio python38Packages.click-repl python38Packages.colorcet python38Packages.cufflinks python38Packages.dash python38Packages.greatfet python38Packages.holoviews python38Packages.hvplot python38Packages.ipdb python38Packages.ipdbplugin python38Packages.ipykernel python38Packages.ipympl python38Packages.ipyparallel python38Packages.ipython python38Packages.ipywidgets python38Packages.jira python38Packages.jupyter python38Packages.jupyter_client python38Packages.jupyter_console python38Packages.jupyter_core python38Packages.jupyterhub python38Packages.jupyterhub-ldapauthenticator python38Packages.jupyterlab python38Packages.jupyterlab_launcher python38Packages.jupyterlab_server python38Packages.jupytext python38Packages.kmapper python38Packages.line_profiler python38Packages.nbconflux python38Packages.nbconvert python38Packages.nbdime python38Packages.nbformat python38Packages.nbmerge python38Packages.nbsmoke python38Packages.nbsphinx python38Packages.nbval python38Packages.notebook python38Packages.notedown python38Packages.oauthenticator python38Packages.onnx python38Packages.papermill python38Packages.pgcli python38Packages.phik python38Packages.plotly python38Packages.prompt_toolkit python38Packages.ptpython python38Packages.pygmo python38Packages.python-dotenv python38Packages.qiskit-terra python38Packages.qtconsole python38Packages.rpy2 python38Packages.runway-python python38Packages.scapy python38Packages.scikit-bio python38Packages.softlayer python38Packages.sopel python38Packages.spyder-kernels python38Packages.spyder-kernels_0_5 python38Packages.vega python38Packages.widgetsnbextension sage sageWithDoc snakemake streamlit tebreak theharvester todoman xonsh
```

**Pull request merged**
