### PR TITLE
jabref: 3.8.1 -> 4.3.1

### PR DESCRIPTION
**Pull request by layus**
Previous version is one year old.

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
- [X] Tested execution of all binary files (usually in `./result/bin/`)

---

/cc @gebner

### CODE REVIEW

**Comment by layus** [comment]
And also that oraclejdk is not packaged for Darwin. Do you have any idea of what it would take to packages openjfx ?

**Comment by gebner** [comment]
See #16727.  @mekeor (user now deleted) started to write an openjfx overlay once: https://github.com/NixOS/nixpkgs/issues/16727#issuecomment-343757642  But I don't think it worked.

**Comment by Mic92** [comment]
Is it better to switch to oraclejdk or leave the old version as it is?

**Comment by gebner** [comment]
Another "solution" is to switch to `jetbrains.jdk` on linux, which happens to include javafx.

**Comment by layus** [comment]
Okay, there is no consensus on this. @gebner Feel free to do whatever you think best. I am closing this PR in the meantime. Maybe an issue would be better to track the status of this ?

**Pull request closed without merging**
