### PR TITLE
brave: fix overriding and update 1.64.116 -> 1.64.122

### PR DESCRIPTION
**Pull request by spitulax**
## Description of changes

- Fix overriding
#298042 moved the derivation function to `make-brave.nix`, breaking previous calls to `override` function.
This PR exposes some arguments to `default.nix` so these would be overridable like previously.

- Update from 1.64.116 to 1.64.122
Release note: https://github.com/brave/brave-browser/releases/tag/v1.64.122

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by wegank** [comment]
I'm not a fan of duplicating arguments like `commandLineArgs ? ""`. Instead, how about this:

```nix
# Expression generated by update.sh; do not edit it by hand!
{ stdenv, callPackage, ... }@args:

if stdenv.isAarch64 then
  callPackage ./make-brave.nix (removeAttrs args [ "callPackage" ]) {
    pname = "brave";
    version = "1.64.116";
    url = "https://github.com/brave/brave-browser/releases/download/v1.64.116/brave-browser_1.64.116_arm64.deb";
    hash = "sha256-XC3GnutiTYdCOJPegj8MRYC5dRrBoKBg4k50ZFrlj4E=";
    platform = "aarch64-linux";
  }
else if stdenv.isx86_64 then
  callPackage ./make-brave.nix (removeAttrs args [ "callPackage" ]) {
    pname = "brave";
    version = "1.64.116";
    url = "https://github.com/brave/brave-browser/releases/download/v1.64.116/brave-browser_1.64.116_amd64.deb";
    hash = "sha256-mnvFPfZu44TZGdUb+AxaJbecQrXkIzJkYvB4GO55uv0=";
    platform = "x86_64-linux";
  }
else
  throw "Unsupported platform."
```

**Comment by spitulax** [comment]
> I'm not a fan of duplicating arguments like `commandLineArgs ? ""`. Instead, how about this, which is a three-line change:
> 
> ```nix
> # Expression generated by update.sh; do not edit it by hand!
> { stdenv, callPackage, ... }@args:
> 
> if stdenv.isAarch64 then
>   callPackage ./make-brave.nix (removeAttrs args [ "callPackage" ]) {
>     pname = "brave";
>     version = "1.64.116";
>     url = "https://github.com/brave/brave-browser/releases/download/v1.64.116/brave-browser_1.64.116_arm64.deb";
>     hash = "sha256-XC3GnutiTYdCOJPegj8MRYC5dRrBoKBg4k50ZFrlj4E=";
>     platform = "aarch64-linux";
>   }
> else if stdenv.isx86_64 then
>   callPackage ./make-brave.nix (removeAttrs args [ "callPackage" ]) {
>     pname = "brave";
>     version = "1.64.116";
>     url = "https://github.com/brave/brave-browser/releases/download/v1.64.116/brave-browser_1.64.116_amd64.deb";
>     hash = "sha256-mnvFPfZu44TZGdUb+AxaJbecQrXkIzJkYvB4GO55uv0=";
>     platform = "x86_64-linux";
>   }
> else
>   throw "Unsupported platform."
> ```

That was my first solution too. I've taken a look at chromium package source and it puts each arguments in `default.nix`, so I went with that. I suppose this is a better solution and I'm going to change it.

**Comment by ribru17** [comment]
Hello, sorry to butt in, but how should something like `commandLineArgs` be applied after this change? Before I had:
```nix
  brave = (pkgs.brave.override {
    commandLineArgs = [ "--force-device-scale-factor=1.5" ];
  });
```
but now this fails to build. Sorry for the noobie question!

**Comment by spitulax** [comment]
> Hello, sorry to butt in, but how should something like `commandLineArgs` be applied after this change? Before I had:
> ```nix
>   brave = (pkgs.brave.override {
>     commandLineArgs = [ "--force-device-scale-factor=1.5" ];
>   });
> ```
> but now this fails to build. Sorry for the noobie question!
> 
> EDIT: Something like the following will build, but not apply the actual options:
> ```nix
>   brave = (pkgs.brave.overrideAttrs (oldAttrs: {
>     commandLineArgs = [ "--force-device-scale-factor=1.5" ];
>   }));
> ```

That is the problem this PR should fix, but this PR has not been merged to nixpkgs-unstable and nixos-unstable as seen in https://nixpk.gs/pr-tracker.html?pr=303570. If you're using those branches you might want to override brave with the package from the master branch until this gets merged to the other branches.

**Comment by ribru17** [comment]
Ah, ok that makes sense. Thank you so much!!

**Pull request merged**
