### PR TITLE
firejail: 0.9.70 -> 0.9.72

### PR DESCRIPTION
**Pull request by onny**
###### Description of changes

Changelog https://github.com/netblue30/firejail/releases/tag/0.9.72

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by onny** [comment]
Result of `nixpkgs-review pr 211245` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>firejail</li>
    <li>orjail</li>
  </ul>
</details>

**Comment by dcarosone** [comment]
Still investigating cause, but this seems to have broken my firejail of firefox somehow.  Firejail emits a bunch of various warnings (most of which have been there forever, one of which might be new, or at least I don't recognise - something about stacking profiles) and then at the end gets a "no such file or directory" trying to start the child.

I rolled back for now and will look into it more later as well as read firejail changelogs (maybe I have to adapt something in my config?), just noting here in case others find something similar.

**Comment by onny** [comment]
Thanks for noticing. Got issues here two and going two investigate this, possibly git bisecting or something like this.

**Comment by revuwa** [comment]
Same here, after upgrading to new version (0.9.72) none of my firejailed apps will start anymore.
Three different errors appear, (just four examples, each):

1. mpv | tenacity | mediainfo | zathura | ...
`Cannot start application: Permission denied`
2. chromium | imv | gimp | keepassxc | ...
`Cannot start application: No such file or directory`
3. nano | nvim | fzf | file | ...
`fish: Unknown command: --`
`fish:` 
`--`
`^^`


The last one could be related to:

```
- modif: set --shell=none as the default
- modif: removed --shell= command
```

Source (changelog): https://github.com/netblue30/firejail/releases/tag/0.9.72
Because I use the Fish shell, and there "was" some trouble with this point -> https://github.com/netblue30/firejail/issues/5445

Interesting` is, that all of my wrapped apps:
```
programs.firejail = {
    enable = true;
    wrappedBinaries = { ...
```
won't work since firejail 0.9.72, but if I manually run them like:
`firejail nvim`
most of them work with the current version, too 🤷‍♂️

As workaround I temporary switched back to previous version (over configuration.nix):
```
  nixpkgs.overlays = [
    (self: super: {
      firejail = super.firejail.overrideAttrs (old: {
        version = "0.9.70";
        src = super.fetchFromGitHub {
          owner = "netblue30";
          repo = "firejail";
          rev = "0.9.70";
          sha256  = "sha256-x1txt0uER66bZN6BD6c/31Zu6fPPwC9kl/3bxEE6Ce8=";
        };
      });
    })
  ];
```
which works fine.

Hope this helps someone somehow...

**Comment by onny** [comment]
I'm going to revert this PR and trying to find the culprit using git bisect

**Comment by rusty-snake** [comment]
@onny The cause for this is very likely the fact that specifying the the end-of-option indicator `--` causes firejail to start the program via `$SHELL -c <PROGRAM>` rather than using `execve(<PROGRAM>)` as it does w/o end-of-option indicator. 

See also:

- https://github.com/netblue30/firejail/issues/5599
- https://github.com/netblue30/firejail/issues/5605
- https://github.com/netblue30/firejail/issues/5606

**Comment by onny** [comment]
@rusty-snake Do you have a patch which we can apply? I tried the latest firejail master branch which is working for some wrappedBinaries but for example still fails for librewolf:
```
#! /nix/store/qqa28hmysc23yy081d178jfd9a1yk8aw-bash-5.2-p15/bin/bash -e
exec /run/wrappers/bin/firejail '--net=tornet' '--dns=46.182.19.48' '--ignore=private-dev' '--env=GTK_THEME=Adwaita:dark' '--env=MOZ_ENABLE_WAYLAND=1' '--dbus-user.talk=org.freedesktop.Notifications' '--profile=/nix/store/v0phcgd2bd8sjcnw5b0w2v3jl9w2p2gy-firejail-0.9.73/etc/firejail/librewolf.profile' -- /nix/store/sn35if55flrlx3rlp620r70pg9a0iq7n-librewolf-109.0.1-2/bin/librewolf "$@"
```
Results in
```
[...]
Cannot start application: No such file or directory
```

I also tried to revert a potential regression
``` 
substituteInPlace src/firejail/main.c \
  --replace 'int arg_shell_none = 1' 'int arg_shell_none = 0'
```
Still no luck :(

**Comment by onny** [comment]
Reverting this specific commit https://github.com/netblue30/firejail/commit/7ad735deafa80114a17b20790de63f7e973b1bb4 fixes the issue for me

Changing line https://github.com/netblue30/firejail/blob/7ad735deafa80114a17b20790de63f7e973b1bb4/src/firejail/sandbox.c#L531
```
	else if (!arg_appimage && !arg_doubledash) {
```
to
```
	else if (!arg_appimage) {
```
fixes it :)

**Pull request merged**
