### PR TITLE
python3Packages.canmatrix: 0.9.1 -> 0.9.3

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 0.9.3

Commit log: https://github.com/ebroecker/canmatrix/commits/development

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 111007` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>python37Packages.canmatrix</li>
    <li>python37Packages.canopen</li>
    <li>python38Packages.canmatrix</li>
    <li>python38Packages.canopen</li>
    <li>python39Packages.canmatrix</li>
    <li>python39Packages.canopen</li>
  </ul>
</details>

**Review by sorki — APPROVED** [review]
LGTM, Thank you! Consider adding yourself to maintainers :-)

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 111007` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>3 packages failed to build and are new build failures:</summary>
  <ul>
<li>python37Packages.canopen: log was empty</li>
<li>python38Packages.canopen: log was empty</li>
<li>python39Packages.canopen: log <a href="https://termbin.com/tvi1">https://termbin.com/tvi1</a></li>
  </ul>
</details>
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>python37Packages.canmatrix</li>
<li>python38Packages.canmatrix</li>
<li>python39Packages.canmatrix</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 111007` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
6 packages built:
</summary>
<ul>
<li>python37Packages.canmatrix</li>
<li>python37Packages.canopen</li>
<li>python38Packages.canmatrix</li>
<li>python38Packages.canopen</li>
<li>python39Packages.canmatrix</li>
<li>python39Packages.canopen</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 111007` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>3 packages failed to build and are new build failures:</summary>
  <ul>
<li>python37Packages.canopen: log was empty</li>
<li>python38Packages.canopen: log was empty</li>
<li>python39Packages.canopen: log <a href="https://termbin.com/n16g">https://termbin.com/n16g</a></li>
  </ul>
</details>
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>python37Packages.canmatrix</li>
<li>python38Packages.canmatrix</li>
<li>python39Packages.canmatrix</li>
</ul>
</details>

**Comment by mweinelt** [comment]
Ah, sorry. I came upon the same issue and fixed it in cb4fe8e0cda8e4af51a54b7cfb3c2385894e7958. Can you rebase, sorry for not checking the pull requests first.

**Review by mweinelt — APPROVED** [review]

**Pull request merged**
