### PR TITLE
python310Packages.pyjwt: 2.3.0 -> 2.4.0

### PR DESCRIPTION
**Pull request by fabaff**
###### Description of changes
https://github.com/jpadilla/pyjwt/releases/tag/2.4.0

https://github.com/jpadilla/pyjwt/security/advisories/GHSA-ffqj-6fqr-9h24

Looks like there is a little mix up with the assigned CVE at the moment.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dotlambda** [comment]
> What's the hold up here?

Nixpkgs-review used to show some breakage, maybe that changed.

**Comment by fabaff** [comment]
- `torchinfo` failure addressed in #176271

**Comment by fabaff** [comment]
> What's the hold up here?

There was an issue with `beets`.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 173284` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>tts</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Looks that I have to move this into #175805 as `nix-review` takes forever locally.

**Comment by fabaff** [comment]
The status looked like this before `pytorch` came...

```
[6/826/837 built (16 failed),...
```

Around 50 % of the failures are AVX instructions-related.

**Comment by vcunat** [comment]
FYI, staging-next is just starting up, PR https://github.com/NixOS/nixpkgs/pull/177171

**Comment by dotlambda** [comment]
Let's merge this into staging-next and address the failures there.

**Comment by fabaff** [comment]
The `pyjwt` update was done with #175396.

**Comment by vcunat** [comment]
The pyjwt update got to master now.

**Comment by vcunat** [comment]
Oh and PR https://github.com/NixOS/nixpkgs/pull/177450
... so I'll assume that this PR isn't needed anymore.

**Pull request closed without merging**
