### PR TITLE
fontconfig: 2.13.92 -> 2.13.93

### PR DESCRIPTION
**Pull request by alyssais**
###### Motivation for this change

All the patches we were applying before have been included in this release.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
Changes: https://gitlab.freedesktop.org/fontconfig/fontconfig/-/compare/2.13.92...2.13.93

Interesting commits:

- Take effect sysroot functionality to the default config file

  Likely not an issue for us – from the message, it seems like it is only affected by environment variable. Unless FcConfigGetSysRoot returns $out.

- Fix cache conflicts on OSTree based system 

  We also reset mtime IIRC but we generate cache ourselves so hopefully, this is not issue. I think the cache is loaded at program start-up so it should not affect us anyway.

  Or are cache rebuilds supposed to be reflected at app at runtime?

- Add Meson build system

  Do we want to switch now or later?

- Make more clearer the license terms

  Still a mess, probably nothing to do for now.

**Comment by alyssais** [comment]
> - Add Meson build system
>
>   Do we want to switch now or later?

No reason to block the upgrade on that, IMO.

**Review by jtojnar — APPROVED** [review]
Looking at the [source code](https://gitlab.freedesktop.org/fontconfig/fontconfig/-/blob/fd3eebad741c0fdfce2a7e44f9b3ac8895b70a58/src/fccfg.c#L224) the sysroot of `FcConfigGetSysRoot` is NULL when not manually set (through the setter or env var) so that should be fine.

**Comment by alyssais** [comment]
Hmm, since this change, GTK programs have had messed up fonts for me.  I don't use many GTK programs so I didn't notice at first.  Text is forced to monospace, or sometimes a Times New Roman lookalike.

**Comment by Mindavi** [comment]
I've seen that too on the pinephone, but I can't tell if it's due to this. The whole UI has a weird font now (phosh).

**Comment by alyssais** [comment]
@Mindavi should have been fixed by #129675.

**Pull request merged**
