### PR TITLE
nixos/almir: option for url prefix & minor changes

### PR DESCRIPTION
**Pull request by offlinehacker**

### CODE REVIEW

**Comment by iElectric** [comment]
For the prefix option I'd rather see `extraAppConfig` for a general solution.

**Comment by offlinehacker** [comment]
Well here the problem is that config has a structure and allowing user to write everywhere(app main) is kinda bad practice. I rather have explicit meaningfull options.

**Comment by offlinehacker** [comment]
Also here you have to change pythonpath and add pastedeploy, while this could be solved by appending to systemd options, besides being ugly, it has high risk of breaking and is again bad practice.

**Comment by iElectric** [comment]
Why do you need the prefix? To setup ssl see https://github.com/Pylons/waitress/blob/master/docs/index.rst#passing-the-x_forwarded_proto-header-to-set-wsgiurl_scheme

**Comment by offlinehacker** [comment]
What does it have to do with https. I need prefix, so i can put almir on
sub URL like /backup, i know i can use different port, but i don't want to,
because of port forwarding/firewall complications in my use case and
because i don't want to.

**Comment by offlinehacker** [comment]
We have similar options in other services and it makes sense to me, that
service supports exposing itself on sub URL, which apparently in some cases
is not as simple as setting some header on proxy server.

**Comment by iElectric** [comment]
I'll take a look if we can solve this using extra config as a more general solution then

**Pull request closed without merging**
