### PR TITLE
security.pam.usb: fix url

### PR DESCRIPTION
**Pull request by fadenb**
Hey,

pamusb.org no longer serves the intended content. This links to the most current version on archive.org with meaningful content.

### CODE REVIEW

**Comment by peterhoeg** [comment]
It's available here: https://github.com/aluzzardi/pam_usb/wiki

**Comment by fadenb** [comment]
@peterhoeg: Thanks, did not find that URL before.

Updated the PR accordingly.

**Comment by peterhoeg** [comment]
Cool, thanks!

**Comment by balsoft** [comment]
Sorry for offtopic, but is pam.usb working as of now? For me it fails because it is unable to find udisks 1.0 on DBUS, and if I add pkgs.udisks to services.dbus.packages it complains about timeouts. Is there any working setup?

**Pull request merged**
