### PR TITLE
dropbox: stable 3.4.4 -> 3.4.6

### PR DESCRIPTION
**Pull request by bendlas**

### CODE REVIEW

**Comment by jagajaga** [comment]
https://github.com/NixOS/nixpkgs/pull/7893

**Comment by bendlas** [comment]
@jagajaga Please reopen, one is for master, one is for stable branch!

**Comment by jagajaga** [comment]
Tested?

**Comment by bendlas** [comment]
No

**Comment by ttuegel** [comment]
Merged on the command line as 624049d.

**Pull request closed without merging**
