### PR TITLE
mumble: use our celt library

### PR DESCRIPTION
**Pull request by abbradar**
cc @viric @geerds

### CODE REVIEW

**Comment by viric** [comment]
Hello. Thank you for the PR.

Can you ellaborate why this is better than using the celt included in mumble? Did you find any problem?

**Comment by abbradar** [comment]
@viric No, this is more of "avoid in-tree libraries when we have one in repositories" change -- I've noticed and done this occasionally while looking for other (fixed in `master` it seems) bug.

**Comment by copumpkin** [comment]
In general, in-tree libraries seem like a hack to work around the lack of a good dependency management system, which I think we can provide. They just grow closure sizes, increase build time, decrease resilience against major bugs in dependencies, and don't provide much value as far as I can tell. The main thing I can see in favor of them is that they produce a more predictable (and tested by others) artifact.

**Comment by lethalman** [comment]
:+1: if it works

**Comment by viric** [comment]
I have no preference in using a nix celt. Feel free to merge it, those who
have any preference. :)

On Fri, Jul 31, 2015 at 05:26:35AM -0700, lethalman wrote:
> :+1: if it works
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/NixOS/nixpkgs/pull/9065#issuecomment-126674815

-- 
(Escriu-me xifrat si saps PGP / Write ciphered if you know PGP)
PGP key D4831A8A - https://emailselfdefense.fsf.org/

**Comment by abbradar** [comment]
Tested this with old 1.2.3 server (which forces CELT), works nice. Merging.

**Pull request merged**
