### PR TITLE
softether: add vpnserver.settings option

### PR DESCRIPTION
**Pull request by mjsir911**
###### Motivation for this change

Currently softether needs to be configured through the cli `vpncmd`, which is both confusing and not reproducible easily. The configuration file is *mostly* compatible with nixos objects/hashmaps/dicts, with the exception that the configuration file includes types, and differentiates between `string` and `byte`.

Semantics for `softether.settings` worked off of NixOS/rfcs#42

Looking for advice on how to approach typed options, a lot of the time defaults are good enough, but something I've run into is that the hashed password must be a `byte` type.

What i'm doing right now is using an object: `{type="byte"; value="whatever==="}`

Example nixos configuration:
```nix
services.softether = { 
	enable = true; 
	vpnserver = { 
		enable = true; 
		settings.root = { 
			LocalBridgeList.LocalBridge0 = { 
				DeviceName = "soft"; 
				HubName = "DEFAULT"; 
				TapMode = true; 
			}; 
			ListenerList.Listener0 = { 
				Enabled = true; 
				Port = 5555; 
			}; 
			VirtualHUB.DEFAULT = { 
				Online = true; 
				SecurityAccountDatabase.UserList.Ridl3y = { 
					AuthNtLmSecureHash = {type="byte"; value="aaaaaaaaaaaaaaaaaaaaaa==";}; 
					AuthPassword = {type="byte"; value="aaaaaaaaaaaaaaaaaaaaaaaaaaa=";}; 
					AuthType = 1; 
				}; 
			}; 
		}; 
	}; 
}
```

Turns into:
```
declare root
{
        declare ListenerList
        {
                declare Listener0
                {
                        bool Enabled true
                        uint Port 5555
                }
        }
        declare LocalBridgeList
        {
                declare LocalBridge0
                {
                        string DeviceName soft
                        string HubName DEFAULT
                        bool TapMode true
                }
        }
        declare ServerConfiguration
        {
        }
        declare VirtualHUB
        {
                declare DEFAULT
                {
                        bool Online true
                        declare SecurityAccountDatabase
                        {
                                declare UserList
                                {
                                        declare Ridl3y
                                        {
                                                byte AuthNtLmSecureHash aaaaaaaaaaaaaaaaaaaaaa==
                                                byte AuthPassword aaaaaaaaaaaaaaaaaaaaaaaaaaa=
                                                uint AuthType 1
                                        }
                                }
                        }
                }
        }
}
```

###### TODO:
- [ ] maybe better type specification
- [x] figure out how to specify default values, and which values should be default, and which values are autofilled on app startup
- [x] mutable vs immutable configs (see [`znc/default.nix`](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/znc/default.nix))

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by gnidorah** [comment]
Unfortunately I don't use SoftEther since 2018.
Added SoftEther maintainer for review

**Comment by fricklerhandwerk** [comment]
@mjsir911 are you still interested in this PR?

**Comment by mjsir911** [comment]
I am @fricklerhandwerk, as long as it can get the attention needed to merge

**Comment by fricklerhandwerk** [comment]
Okay, I’ll look into the changes these days.

**Comment by fricklerhandwerk** [comment]
Well, "these days" didn't happen, I just can't find enough time. But it's on my list, I won't forget, and I want to use it, so I'll be back with test and review.

**Comment by mjsir911** [comment]
> Well, "these days" didn't happen, I just can't find enough time. But it's on my list, I won't forget, and I want to use it, so I'll be back with test and review.

thank you for the updated @fricklerhandwerk! Glad to hear its still on your radar, I'll await review patiently :)

**Comment by mjsir911** [comment]
A solution around the custom data type `{type="byte"; value="aaaaaaaaaaaaaaaaaaaaaa==";}` fields is to just explicitly specify the `root.VirtualHUB.*.SecurityAccountDatabase.UserList.*.{AuthNtLmSecureHash,AuthPassword}` types and coerce them that way. Not sure if this works, if the type information specified in `options` can be translated to the data translation to config file.

**Comment by roberth** [comment]
Please rebase this on `origin/master`. If you aren't familiar with rebase, checkout jonringer's https://www.youtube.com/watch?v=OR8Q-4PLalc

**Comment by mjsir911** [comment]
Oh, geez, thanks @roberth, not sure what happened :/

**Comment by fricklerhandwerk** [comment]
Still relevant, I haven't forgotten.

**Comment by Janik-Haag** [comment]
@fricklerhandwerk @mjsir911 what has to happen to unstale this/to get this merged?

**Pull request closed without merging**
