### PR TITLE
Let folks try xi-editor (`xi-core`) and various front-ends.

### PR DESCRIPTION
**Pull request by dtzWill**
They're all WIP (as in "upstream is still working towards a release") but
having them packaged makes it easier to get started and see what it's about.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
Build failure seems unrelated, at least I sure hope so! Snippet:
```
undefined variable 'xenPackages' at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-0-gleber.ewr1.nix.ci/pkgs/top-level/all-packages.nix:19705:9
```

**Comment by dtzWill** [comment]
I'm new to them all-- packaged them so I could try them myself :).  My
impression after very brief use is that I don't know that any of them are
ready for contending as your primary editor just yet.  Couldn't say how far
that is, I expect the looking at the xi-mac frontend would give the best
picture. I believe there are a few talks and videos that might shed more
light on things, but haven't looked through them myself.

**Comment by Mic92** [comment]
It also seems to be more a research project then something people would actually use.

**Comment by Mic92** [comment]
I also tried to package oni, but it was still crashing on startup for me: https://github.com/Mic92/nur-packages/blob/master/pkgs/oni/default.nix

**Comment by teto** [comment]
@Mic92 the overlay at https://github.com/NixOS/nixpkgs/issues/38231#issuecomment-427568905 works for me to install/run oni. The only problem is if you configure vim with nix, then oni won't get wrapped.
If it's that bad, maybe xi-frontends should go to NUR meanwhile.

**Comment by dtzWill** [comment]
Hmm, okay I'll move to my nur repo instead then ^_^.

**Comment by dtzWill** [comment]
(thanks for the good suggestion!)

**Comment by milahu** [comment]
> Hmm, okay I'll move to my nur repo instead then ^_^.

https://github.com/dtzWill/nur-packages/tree/master/pkgs/xi

**Pull request closed without merging**
