### PR TITLE
gtklick: init at 0.6.4

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by copumpkin** [comment]
@DavidCalvo looks like you included a ton of unrelated history in here. Can you just cherry-pick the relevant commit?

**Comment by DavidCalvo** [comment]
It seems I've messed things up. I'll try to fix it.

Sorry for the inconvenience. It's my first PR here.

**Comment by jgillich** [comment]
Look like your commits are based on the stable branch, so you need to rebase on master.

**Comment by DavidCalvo** [comment]
That's right, I forgot to rebase my commits on master.

I think it's fixed now.

**Pull request merged**
