### PR TITLE
Update androidStudioPackages.beta androidStudioPackages.canary and androidStudioPackages.stable

### PR DESCRIPTION
**Pull request by freshprince**
## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

CC: package maintainer @alapshin

### CODE REVIEW

**Comment by kirillrdy** [comment]
@freshprince greetings !

can you please change PR title to use attribute name, in this case androidStudioPackages.{stable,beta,canery} you can see previous PR's as example. This is done so that people can find duplicate inflight PRs ( github search isnt greate )

**Comment by kirillrdy** [comment]
Result of `nixpkgs-review pr 258549` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>android-studio</li>
    <li>androidStudioPackages.beta</li>
    <li>androidStudioPackages.canary</li>
    <li>androidStudioPackages.dev</li>
  </ul>
</details>

**Review by alapshin — APPROVED** [review]

**Comment by kirillrdy** [comment]
@freshprince sorry I only now remembered about this PR, is it possible to update stable to 2023.1.1.22 part of this PR ?

**Comment by freshprince** [comment]
> @freshprince sorry I only now remembered about this PR

No worries.

> is it possible to update stable to 2023.1.1.22 part of this PR ?

Sure, but AFAICS 2023.1.1 has no stable release yet. 2023.1.1.22 is release candidate only and the latest RC is 2023.1.1.25. But maybe my information is outdated?

I've updated beta to 2023.1.1.25 and canary to 2023.2.1.14.

**Review by kirillrdy — APPROVED** [review]
Result of `nixpkgs-review pr 258549` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>android-studio (androidStudioPackages.stable)</li>
    <li>androidStudioPackages.beta</li>
    <li>androidStudioPackages.canary</li>
    <li>androidStudioPackages.dev</li>
  </ul>
</details>

**Pull request merged**
