### PR TITLE
linux_5_10: 5.10.15 -> 5.10.16, linux_5_11: init at 5.11

### PR DESCRIPTION
**Pull request by adisbladis**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by archseer** [comment]
Fails on ZFS. Looking forward to this one :)

**Comment by NeQuissimus** [comment]
Let me take a look, I am pretty sure ZFS 2.0.3 has support for 5.11

**Comment by NeQuissimus** [comment]
@ofborg test kernel-latest latestKernel.login

**Comment by NeQuissimus** [comment]
@ofborg test zfs.unstable zfs.installer zfs.stable

**Comment by NeQuissimus** [comment]
59b31663b6af50e997b1755f9037b35571ce5b00 is going to need a port to stable

**Review by NeQuissimus — APPROVED** [review]

**Review by jcumming — APPROVED** [review]
LGTM. Have not tested.

**Comment by maxeaubrey** [comment]
I can no longer build my system using latest with this merged, had to switch back to 5.10
[5.11.txt](https://github.com/NixOS/nixpkgs/files/6005686/5.11.txt)

**Comment by mweinelt** [comment]
Same, to cut this short:

```
GOT: # configuration written to .config
GOT: #
GOT: make[1]: Leaving directory '/build/linux-5.11/build'
GOT: make: Leaving directory '/build/linux-5.11'
warning: unused option: DEBUG_STACKOVERFLOW
error: unused option: DRM_AMD_DC_DCN3_0
warning: unused option: EXT4_ENCRYPTION
warning: unused option: F2FS_FS_ENCRYPTION
warning: unused option: KEXEC_FILE
warning: unused option: RCU_PERF_TEST
builder for '/nix/store/kxvnhl7nbzi2knmc5h7689yavlxbi8h5-linux-config-5.11.drv' failed with exit code 255
```

**Comment by Luflosi** [comment]
Does something need to be done before this can be ported to stable?

**Comment by Ma27** [comment]
@NeQuissimus @adisbladis IIRC we always backport new kernel versions to stable. Is there any reason this isn't done here?

**Comment by NeQuissimus** [comment]
@Ma27 We usually do after one or two dot-releases in order to see whether everything works on `master` and the hardened patch sets are available.
We are probably at the point where we could PR 5.11 to `release-20.09`.

**Pull request merged**
