### PR TITLE
headlines: init at 0.7.2

### PR DESCRIPTION
**Pull request by chuangzhu**
###### Description of changes

https://gitlab.com/caveman250/Headlines

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by dasj19 — APPROVED** [review]
builds with nix-review, and the binary runs

**Comment by dasj19** [comment]
are we missing a dependency. An attempt to play a video message ends in:
```
(headlines:633001): GStreamer-Play-ERROR **: 22:08:22.935: GstPlay: 'playbin' element not found, please check your setup
fish: Job 1, 'headlines' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

**Comment by chuangzhu** [comment]
> GstPlay: 'playbin' element not found

Fixed but another error occurred. Have no idea how this can be fixed:

```
** (headlines:944317): CRITICAL **: 21:01:26.183: Error from element /GstPlayBin:playbin/GstPlaySink:playsink/GstBin:abin/GstPulseSink:pulsesink0: The stream is in the wrong format.
The stream is in the wrong format.
../gst-libs/gst/audio/gstaudiobasesink.c(1117): gst_audio_base_sink_wait_event (): /GstPlayBin:playbin/GstPlaySink:playsink/GstBin:abin/GstPulseSink:pulsesink0:
Sink not negotiated before eos event.
```

**Comment by dasj19** [comment]
The latest version always crashes for me after loading the gui.
```
** (process:1648300): WARNING **: 18:01:03.441: Can't set the global locale to the user's preferred locale.
   locale::facet::_S_create_c_locale name not valid
   The environment variable LANG may be wrong.


(process:1648300): Gtk-WARNING **: 18:01:03.443: Locale not supported by C library.
	Using the fallback 'C' locale.

(headlines:1648300): Gtk-WARNING **: 18:01:03.583: Allocating size to AdwViewSwitcherBar 0x17b62f0 without calling gtk_widget_measure(). How does the code know the size to allocate?

(headlines:1648300): Gtk-CRITICAL **: 18:01:03.583: Allocation height too small. Tried to allocate 899x0, but AdwViewSwitcherBar 0x17b62f0 needs at least 899x45.

(headlines:1648300): Gtk-CRITICAL **: 18:01:03.583: Allocation height too small. Tried to allocate 899x0, but GtkActionBar 0x17b6480 needs at least 899x45.

(headlines:1648300): Gtk-CRITICAL **: 18:01:03.583: Allocation height too small. Tried to allocate 899x0, but GtkRevealer 0x17c8290 needs at least 899x45.

(headlines:1648300): Gtk-CRITICAL **: 18:01:03.583: Allocation height too small. Tried to allocate 899x0, but GtkCenterBox 0x17b6610 needs at least 899x45.

(headlines:1648300): Gtk-CRITICAL **: 18:01:03.583: Allocation height too small. Tried to allocate 0x-1, but GtkBox 0x17c07e0 needs at least 0x0.

(headlines:1648300): Gtk-WARNING **: 18:01:03.583: gtk_widget_size_allocate(): attempt to allocate GtkBox box 0x17c07e0 with width 0 and height -1

(headlines:1648300): Gtk-CRITICAL **: 18:01:03.583: Allocation height too small. Tried to allocate 320x-1, but AdwViewSwitcher 0x17b67a0 needs at least 320x44.

(headlines:1648300): Gtk-WARNING **: 18:01:03.583: gtk_widget_size_allocate(): attempt to allocate AdwViewSwitcher viewswitcher 0x17b67a0 with width 300 and height -1

(headlines:1648300): Gtk-CRITICAL **: 18:01:03.583: Allocation height too small. Tried to allocate 0x0, but AdwViewSwitcherButton 0x17d4260 needs at least 0x44.

(headlines:1648300): Gtk-CRITICAL **: 18:01:03.583: Allocation width too small. Tried to allocate 0x0, but AdwViewSwitcherButton 0x17d4260 needs at least 16x0.

(headlines:1648300): Gtk-CRITICAL **: 18:01:03.583: Allocation height too small. Tried to allocate 0x0, but GtkStack 0x179ef90 needs at least 0x44.

(headlines:1648300): Gtk-CRITICAL **: 18:01:03.583: Allocation width too small. Tried to allocate 0x0, but GtkStack 0x179ef90 needs at least 16x0.

(headlines:1648300): Gtk-CRITICAL **: 18:01:03.583: Allocation height too small. Tried to allocate 0x0, but AdwViewSwitcherButton 0x17d4470 needs at least 0x44.

(headlines:1648300): Gtk-CRITICAL **: 18:01:03.583: Allocation width too small. Tried to allocate 0x0, but AdwViewSwitcherButton 0x17d4470 needs at least 16x0.

(headlines:1648300): Gtk-CRITICAL **: 18:01:03.583: Allocation height too small. Tried to allocate 0x0, but GtkStack 0x17d99b0 needs at least 0x44.

(headlines:1648300): Gtk-CRITICAL **: 18:01:03.583: Allocation width too small. Tried to allocate 0x0, but GtkStack 0x17d99b0 needs at least 16x0.

(headlines:1648300): Gtk-CRITICAL **: 18:01:03.583: Allocation height too small. Tried to allocate 0x0, but AdwViewSwitcherButton 0x17d4680 needs at least 0x44.

(headlines:1648300): Gtk-CRITICAL **: 18:01:03.583: Allocation width too small. Tried to allocate 0x0, but AdwViewSwitcherButton 0x17d4680 needs at least 16x0.

(headlines:1648300): Gtk-CRITICAL **: 18:01:03.583: Allocation height too small. Tried to allocate 0x0, but GtkStack 0x17ea3f0 needs at least 0x44.

(headlines:1648300): Gtk-CRITICAL **: 18:01:03.583: Allocation width too small. Tried to allocate 0x0, but GtkStack 0x17ea3f0 needs at least 16x0.

(headlines:1648300): Gtk-CRITICAL **: 18:01:03.583: Allocation height too small. Tried to allocate 0x-1, but GtkBox 0x17c0960 needs at least 0x0.

(headlines:1648300): Gtk-WARNING **: 18:01:03.583: gtk_widget_size_allocate(): attempt to allocate GtkBox box 0x17c0960 with width 0 and height -1

(headlines:1648300): Gtk-WARNING **: 18:01:03.604: Allocating size to AdwViewSwitcherBar 0x17b62f0 without calling gtk_widget_measure(). How does the code know the size to allocate?

** (headlines:1648300): WARNING **: 18:01:03.663: Json::CharReader error: * Line 1, Column 1
  Syntax error: value, object or array expected.

Segmentation fault (core dumped)
```

**Comment by dasj19** [comment]
I have fiddled a bit with the package definition.
I fulfilled all pkg-config complaints of missing packages but the app still crashes (maybe it receives malformed json from the api).
Here is what I used:
```
{ lib
, stdenv
, cmake
, pkg-config
, libmicrohttpd
, curl
, openssl
, jsoncpp
, libxml2
, ffmpeg
, gst_all_1
, youtube-dl
, boost
, websocketpp
, libadwaita
, gtkmm4
, libsecret
, fetchFromGitLab
, makeWrapper
, xdg-utils
, pcre
, pcre2
, util-linux
, libselinux
, libsepol
, fribidi
, libgcrypt
, libthai
, libgpg-error
, libdatrie
, gnutls
, xorg
, libtasn1
, p11-kit
}:

stdenv.mkDerivation rec {
  pname = "headlines";
  version = "0.7.2";

  src = fetchFromGitLab {
    owner = "caveman250";
    repo = "Headlines";
    rev = version;
    sha256 = "sha256-wamow0UozX5ecKbXWOgsWCerInL4J0gK0+Muf+eoO9k=";
  };

  nativeBuildInputs = [
    cmake
    pkg-config
    makeWrapper
  ];

  buildInputs = [
    pcre
    pcre2
    p11-kit
    libtasn1
    gnutls
    xorg.libXdmcp
    fribidi
    util-linux
    libselinux
    libsepol
    libgcrypt
    libthai
    libgpg-error
    libdatrie
    libmicrohttpd
    curl
    openssl
    jsoncpp
    libxml2
    ffmpeg
    youtube-dl
    boost
    websocketpp
    libadwaita
    gtkmm4
    libsecret
    gst_all_1.gstreamer 
  ] ++ (with gst_all_1; [
    gstreamer
    gst-libav
    gst-plugins-base
    (gst-plugins-good.override { gtkSupport = true; })
    gst-plugins-bad
  ]);

  cmakeFlags = [
    "-DCMAKE_BUILD_TYPE=RelWithDebInfo"
    "-DDIST_BUILD=ON"
  ];

  postFixup = ''
    wrapProgram "$out/bin/headlines" \
      --prefix PATH : "${lib.makeBinPath [ xdg-utils youtube-dl ffmpeg ]}" \
      --prefix GST_PLUGIN_SYSTEM_PATH_1_0 : "$GST_PLUGIN_SYSTEM_PATH_1_0"
  '';

  meta = with lib; {
    description = "GTK4 / Libadwaita Reddit client written in C++";
    homepage = "https://gitlab.com/caveman250/Headlines";
    license = licenses.gpl3Plus;
    platforms = platforms.linux;
    maintainers = with maintainers; [ chuangzhu ];
  };
}
```
A lot of dependencies, maybe should be reported upstream and ask for a dependency cleanup..

**Comment by dasj19** [comment]
I have dug out some information about my app crashing and reported upstream: https://gitlab.com/caveman250/Headlines/-/issues/92 ... seems to be an issue with me not being login and the app requesting a login-only resource.

**Comment by chuangzhu** [comment]
> I fulfilled all pkg-config complaints of missing packages

These are just `Requires.private` dependencies. Since we are not doing static linking here, these can be safely ignored.

> The latest version always crashes for me after loading the gui.

I can't reproduce.

**Comment by dasj19** [comment]
Ok, I have tested again with nix-review. This time no crashes but videos would still not play at all.
```
** (headlines:109595): CRITICAL **: 18:18:46.488: Error from element /GstPlayBin:playbin/GstPlaySink:playsink/GstBin:abin/GstPulseSink:pulsesink2: The stream is in the wrong format.
The stream is in the wrong format.
../gst-libs/gst/audio/gstaudiobasesink.c(1117): gst_audio_base_sink_wait_event (): /GstPlayBin:playbin/GstPlaySink:playsink/GstBin:abin/GstPulseSink:pulsesink2:
Sink not negotiated before eos event.
```

**Comment by chuangzhu** [comment]
I dug a bit into the problem and seems that it's because GStreamer cannot parse M3U files with multiple resolution options. Anyway, I don't think it is a bug of packaging. I'll mark this PR ready to merge.

**Pull request merged**
