### PR TITLE
librealsense: 2.38.0 -> 2.40.0

### PR DESCRIPTION
**Pull request by freezeboy**
###### Motivation for this change

Upstream update

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by brian-dawn — APPROVED** [review]
Looks good to me!

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105297` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>librealsenseWithCuda</li>
    <li>python27Packages.pyrealsense2WithCuda</li>
    <li>python37Packages.pyrealsense2WithCuda</li>
    <li>python38Packages.pyrealsense2WithCuda</li>
  </ul>
</details>
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>librealsense (librealsenseWithoutCuda)</li>
    <li>python27Packages.pyrealsense2 (python27Packages.pyrealsense2WithoutCuda)</li>
    <li>python37Packages.pyrealsense2 (python37Packages.pyrealsense2WithoutCuda)</li>
    <li>python38Packages.pyrealsense2 (python38Packages.pyrealsense2WithoutCuda)</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105297` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>librealsense (librealsenseWithoutCuda)</li>
    <li>librealsenseWithCuda</li>
    <li>python27Packages.pyrealsense2 (python27Packages.pyrealsense2WithoutCuda)</li>
    <li>python27Packages.pyrealsense2WithCuda</li>
    <li>python37Packages.pyrealsense2 (python37Packages.pyrealsense2WithoutCuda)</li>
    <li>python37Packages.pyrealsense2WithCuda</li>
    <li>python38Packages.pyrealsense2 (python38Packages.pyrealsense2WithoutCuda)</li>
    <li>python38Packages.pyrealsense2WithCuda</li>
  </ul>
</details>

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 105297 [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>8 packages built:</summary>  <ul>    <li>librealsense (librealsenseWithoutCuda)</li>    <li>librealsenseWithCuda</li>    <li>python27Packages.pyrealsense2 (python27Packages.pyrealsense2WithoutCuda)</li>    <li>python27Packages.pyrealsense2WithCuda</li>    <li>python37Packages.pyrealsense2 (python37Packages.pyrealsense2WithoutCuda)</li>    <li>python37Packages.pyrealsense2WithCuda</li>    <li>python38Packages.pyrealsense2 (python38Packages.pyrealsense2WithoutCuda)</li>    <li>python38Packages.pyrealsense2WithCuda</li>  </ul></details>

**Pull request merged**
