### PR TITLE
sundials: 5.1.0 -> 5.3.0

### PR DESCRIPTION
**Pull request by krtab**
###### Motivation for this change
Bump version

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — APPROVED** [review]
LGTM

failures are broken on target branch
```
https://github.com/NixOS/nixpkgs/pull/91441
1 package failed to build:
python27Packages.scikits-odes

3 packages built:
python37Packages.scikits-odes python38Packages.scikits-odes sundials
```

**Comment by jonringer** [comment]
@krtab thanks for opening your first PR with nixpkgs :)

**Comment by krtab** [comment]
You're welcome. Thanks for your review, and yhanks to @RaitoBezarius for helping me with it and spreading the gospel.

**Comment by idontgetoutmuch** [comment]
@krtab thanks for doing this and @jonringer thanks for reviewing. I have been playing with 5.3 for some weeks.

**Pull request merged**
