### PR TITLE
swiftshader: 2020-06-17 -> 2020-11-06

### PR DESCRIPTION
**Pull request by expipiplus1**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
I get the following error when compiling.
```
_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=/nix/store/nvh8qksd7s0qydhjdgzgd7ns002nqm7g-swiftshader-2020-11-06
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- The ASM compiler identification is GNU
-- Found assembler: /nix/store/lfl1davviy5mai3g80mpy2gkb97rh9j5-gcc-wrapper-9.3.0/bin/gcc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /nix/store/lfl1davviy5mai3g80mpy2gkb97rh9j5-gcc-wrapper-9.3.0/bin/gcc
-- Check for working C compiler: /nix/store/lfl1davviy5mai3g80mpy2gkb97rh9j5-gcc-wrapper-9.3.0/bin/gcc - broken
CMake Error at /nix/store/4fiibyqiq5y0dc1ma3far935r2sn58ak-cmake-3.18.2/share/cmake-3.18/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "/nix/store/lfl1davviy5mai3g80mpy2gkb97rh9j5-gcc-wrapper-9.3.0/bin/gcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /build/SwiftShader-4ed9d34/build/CMakeFiles/CMakeTmp

    Run Build Command(s):/nix/store/kql5zqxkk5xmnmpfcyfzydbvw444i9i8-gnumake-4.3/bin/make cmTC_c89fc/fast && /nix/store/kql5zqxkk5xmnmpfcyfzydbvw444i9i8-gnumake-4.3/bin/make  -f CMakeFiles/cmTC_c89fc.dir/build.make CMakeFiles/cmTC_c89fc.dir/build
    make[1]: Entering directory '/build/SwiftShader-4ed9d34/build/CMakeFiles/CMakeTmp'
    make[1]: /bin/sh: No such file or directory
    make[1]: *** [CMakeFiles/cmTC_c89fc.dir/build.make:84: CMakeFiles/cmTC_c89fc.dir/testCCompiler.c.o] Error 127
    make[1]: Leaving directory '/build/SwiftShader-4ed9d34/build/CMakeFiles/CMakeTmp'
    make: *** [Makefile:140: cmTC_c89fc/fast] Error 2





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:19 (project)


-- Configuring incomplete, errors occurred!
See also "/build/SwiftShader-4ed9d34/build/CMakeFiles/CMakeOutput.log".
See also "/build/SwiftShader-4ed9d34/build/CMakeFiles/CMakeError.log".
```

**Comment by expipiplus1** [comment]
Perhaps you have an overlay or some config option interfering? Both myself and @ofborg are able to build it.

**Comment by expipiplus1** [comment]
Is is possible to get this merged, please?

**Comment by expipiplus1** [comment]
ping?

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 103123` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>swiftshader</li>
  </ul>
</details>

**Comment by expipiplus1** [comment]
Thanks!

**Pull request merged**
