### PR TITLE
terra: 2016-06-09 -> 1.0.0-beta1

### PR DESCRIPTION
**Pull request by alesya-h**
###### Motivation for this change

Terra 1.0.0-beta1 has been released

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ryantm** [comment]
@alesguzik If upstream has a differentiation between stable and unstable releases, we try to provide the stable version in nixpkgs. It looks like this is an unstable version, so it shouldn't be packaged as the main version. If it is necessary to provide this version as a dependency, I think it should be under a different top-level attrpath name like `terra_1.0.0-beta1`.

I'm going to close this as is, but feel free to disagree here, and anyone should feel free to reopen if they disagree.

**Comment by alesguzik** [comment]
@ryantm this is the closest thing there is to the "release" version. 2016-06-09 that nixpkgs currently has is not a release version: tagged versions are 
image

Those tags correspond to the changelog entries.

**Comment by ryantm** [comment]
Looking at that is what gives me the impression they are migrating from a stable release cycle using the date of the release, to a numbered versioning system where 1.0.0-beta is an unstable preview release of the stable 1.0.0 release. Basically the "beta" in the name looks a lot more unstable than a date in the name.

I'm really just basing it off those release names though. If you know more about how the project is run and want to reopen this, I'll defer to you.

**Comment by alesguzik** [comment]
@ryantm they do plan to migrate to it as soon as it will be stable. Date releases are not "stable", it's that the project has been in alpha all this time, and those were just some arbitrary reference points. And the version that we have in nixpkgs is not even one of those reference points. And it is not known when the 1.0.0 will be released. Basically without this PR we are leaving nixpkgs with an arbitrary alpha version that is 2.5 years old. I understand that after 1.0.0 release it will make sense to have only semver stable releases in nixpkgs, but until 1.0.0 is out, I think it is most reasonable to use this one.

**Comment by ryantm** [comment]
@GrahamcOfBorg build terra

**Comment by ryantm** [comment]
Thanks, looks good!

**Comment by alesguzik** [comment]
@ryantm thanks!

**Pull request merged**
