### PR TITLE
firefox 65.0.2 -> 66, 60.5.2esr -> 60.6.0esr, firefox-bin: 65.0.2 -> 66.0

### PR DESCRIPTION
**Pull request by andir**
###### Motivation for this change

FireFox 66 will be released today. The final tarball is already released and the binaries are build.

Changelog is not yet available but should be at:

https://www.mozilla.org/en-US/firefox/66.0/releasenotes/
and
https://www.mozilla.org/en-US/firefox/60.6.0/releasenotes/

### CODE REVIEW

**Comment by andir** [comment]
@GrahamcOfBorg eval
@GrahamcOfBorg build rust-cbindgen

**Comment by Mic92** [comment]
Anything particular to test?

```
nix-review pr 56689
$ git fetch --force https://github.com/NixOS/nixpkgs master:refs/nix-review/0 pull/56689/head:refs/nix-review/1
remote: Enumerating objects: 8590, done.
remote: Counting objects: 100% (8590/8590), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 17401 (delta 8579), reused 8585 (delta 8579), pack-reused 8811
Receiving objects: 100% (17401/17401), 10.65 MiB | 16.77 MiB/s, done.
Resolving deltas: 100% (12569/12569), completed with 2530 local objects.
From https://github.com/NixOS/nixpkgs
   538ce21fe8e..f5c63cbb54f  master               -> refs/nix-review/0
 + 1e8d1d0fd5e...94d9400b4d6 refs/pull/56689/head -> refs/nix-review/1  (forced update)
$ git worktree add /home/s1691654/.cache/nix-review/pr-56689/nixpkgs f5c63cbb54fa64c4889b07e7c7f2ae85ca3d5ce4
Preparing worktree (detached HEAD f5c63cbb54f)
HEAD is now at f5c63cbb54f Merge pull request #57018 from andir/davix
$ git merge --no-commit 94d9400b4d65de02af8cb421d8e85698a7f7246d
Automatic merge went well; stopped before committing as requested
$ nix build --no-link --keep-going --max-jobs 72 --option build-use-sandbox true -f /home/s1691654/.cache/nix-review/pr-56689/build.nix
[5/22/35 built, 362 copied (5301.9/5303.4 MiB), 1393.8 MiB DL] building firefox-unwrapped-66.0 (buildPhase): /nix/store/ghzg4kg0sjif58smj2lfm2bdvjwim85y-gcc-wrapper-7.4.0/bin/g++ -o nsHttpHan[5/22/35 built, 362 copied (5301.9/5303.4 MiB), 1393.8 MiB DL] building firefox-unwrapped-66.0 (buildPhase): /nix/store/ghzg4kg0sjif58smj2lfm2bdvjwim85y-gcc-wrapper-7.4.0/bin/g++ -o s_trunc.o[5/22/35 built, 362 copied (5301.9/5303.4 MiB), 1393.8 MiB DL] building firefox-unwrapped-66.0 (buildPhase): /build/firefox-66.0/gfx/skia/skia/src/core/SkPixmap.cpp:236:15: warning: this stat[5/22/35 built, 362 copied (5301.9/5303.4 MiB), 1393.8 MiB DL] building tor-browser-unwrapped-7.5.6 (buildPhase): /nix/store/ghzg4kg0sjif58smj2lfm2bdvjwim85y-gcc-wrapper-7.4.0/bin/gcc -std=gn[35 built, 362 copied (5301.9 MiB), 1393.8 MiB DL]
https://github.com/NixOS/nixpkgs/pull/56689
3 package are marked as broken and were skipped:
firefox-esr-52-unwrapped firefoxPackages.firefox-esr-52 firefoxPackages.icecat-52

14 package were build:
chatzilla conkeror-unwrapped dropbox dropbox-cli firefox-bin-unwrapped firefox-esr-60-unwrapped xulrunner icecat-unwrapped tor-browser-unwrapped firefoxPackages.tor-browser-7-5 icedtea_web mozplugger rust-cbindgen slimerjs

$ nix-shell /home/s1691654/.cache/nix-review/pr-56689/shell.nix
bash: /tmp/env-vars: cannot overwrite existing file
```

**Comment by andir** [comment]
Test if they work as browser :)

As for all the packages that will be built as a side-effect they should be fine if the firefox's work.

**Comment by Mic92** [comment]
Sent with firefox 66.

**Pull request merged**
