### PR TITLE
 pythonPackages.asyncssh: 1.15.1 -> 1.16.1, fixing build with some caveats around ec25519 support

### PR DESCRIPTION
**Pull request by risicle**
###### Motivation for this change
This "fixes" the build of `asyncssh` mostly through bumping the version. The thing that broke `asyncssh` was its move in `1.15.1` to depending on openssl 1.1.x for its ec25519 support. The default `cryptography` and `pyopenssl` packages are of course built with openssl 1.0.x, so this caused test failures. `1.16.1` added skip-checks to allow the tests to still pass without ec25519 support.

But of course this means that the package, built against the default `cryptography` and `pyopenssl` packages, **won't** support ec25519, which sucks. But the only way of enabling that support is by using overridden versions of those packages which would of course produce collisions against any packages using the default versions of those dependencies. Which is quite a lot of them.

Sooo... I thought it best not to do that by default, settling for supplying an "easy route" for those needing ec25519 support - overriding the `openssl` argument with a 1.1.x version should cause all of the required overriding to happen, while in the normal case the `.override`s don't end up affecting the output hash and so there should be no duplicate packages produced.

Phew. _That_ was a fun evening.

cc @worldofpeace 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by worldofpeace** [comment]
... https://github.com/ronf/asyncssh/commit/1dee113bb3e4a6888de562b0413e9abd6a0f0f04

I also have https://github.com/NixOS/nixpkgs/commit/a39bb0fd995382f5fbd7547820af939bd4905759 in staging since we needed the `cryptography` update that happened there.

Though we will need https://github.com/NixOS/nixpkgs/pull/60553/commits/89e121e9c23696529713921b9d8306320351904f when update openssl and maybe we could fix the file bit permissions upstream for the `sftp` test?

**Comment by risicle** [comment]
> ... ronf/asyncssh@1dee113

Hah! I didn't spot that one. A good decision.

It didn't occur to me to check staging for fixes - going to have to add that to my checklist...

**Comment by worldofpeace** [comment]
Looks like you've integrated the `pyopenssl` change #61325.
Sorry that you went out of your way to fix this and I already did similar.

Do you think upstream could use `0o321` for the sftp test?

**Comment by risicle** [comment]
I suspect they want to flex all the muscles of the tests they can.

Closing this.

**Pull request closed without merging**
