### PR TITLE
icu: 59 -> 64

### PR DESCRIPTION
**Pull request by JohnAZoidberg**
###### Motivation for this change
https://github.com/unicode-org/icu/releases/tag/release-64-2

They say updates can go smoothly so let's try! (http://userguide.icu-project.org/icufaq)

We should probably get rid of the old versions that are not needed anymore if everything builds after this. It doesn't look like they have any LTS versions - they're just releasing new versions.

Obsoletes or resolves: #39388 and #52632

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
Could you rebase? It appears there are some incorrect commits.

**Comment by JohnAZoidberg** [comment]
@GrahamcOfBorg build icu

**Comment by vcunat** [comment]
I managed to fix a few regressions quickly.  PyICU is the only remaining problem I know about; there the compile flags isn't respected I suspect.

**Comment by vcunat** [comment]
Hopefully fine now: https://github.com/NixOS/nixpkgs/commit/326148ec9

**Pull request merged**
