### PR TITLE
cargo-semver-checks: 0.33.0 -> 0.33.0-unstable-2024-08-04

### PR DESCRIPTION
**Pull request by a-kenji**
## Description of changes

Reference: #332957 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by matthiasbeyer — CHANGES_REQUESTED** [review]
We don't package prereleases, so blocking this.

**Comment by a-kenji** [comment]
I will close the PR then, if the maintainer prefers a broken package.

**Comment by emilazy** [comment]
We package plenty of prereleases and this package is about to be broken on `master`. @matthiasbeyer if you’re unwilling to consider bumping to a Git revision temporarily, would you be able to do the work to backport the Rust 1.80 fixes?

**Comment by matthiasbeyer** [comment]
> We package plenty of prereleases

I was always told that we do not do this whenever I tried to package something off of a prerelease!

I'd wait until https://github.com/obi1kenobi/cargo-semver-checks/issues/851 is resolved and then update the package like we normally do.

**Comment by alyssais** [comment]
> I was always told that we do not do this whenever I tried to package something off of a prerelease!

It's best to avoid where possible, but it's not banned.  We have [explicit documentation](https://github.com/NixOS/nixpkgs/blob/6b3a0ab73efe7cd524623f9e4e8be5e3dab2233b/pkgs/README.md#package-naming) about how to do it, even.

**Comment by emilazy** [comment]
> I was always told that we do not do this whenever I tried to package something off of a prerelease!

Like most things in Nixpkgs, ask two committers, get three opinions 😆

I suspect I’m more cavalier about it than most; I’m happy packaging a prerelease if any of the following are true:

1. The package is clearly sufficiently dead that we shouldn’t expect another release, but fixes have piled up in the repository since. (Often happens in moribund projects that nonetheless found some time over the years to hit the GitHub merge button on fixes people ran into when trying to keep it going.)

2. Upstream has in some way indicated that they consider prereleases to be acceptable for users, by explicitly recommending them, offering them as a prominent download on their site without warnings of being unstable, giving the go‐ahead to package the HEAD when asked, or explicitly conveying that they intend to get around to cutting a release of the current state at some point.

3. Upstream seems active and disciplined (so we can expect their tree to be kept in a good state and there to be a release that gets us back on the train in a timely fashion), it unblocks some Nixpkgs work that matters to me, and a quick glance at the commits since the last release don’t show any major upheavals or other causes for concern.

This counts as 3 to me, but an upstream release would definitely be better, so hopefully we’ll get one soon!

**Comment by obi1kenobi** [comment]
👋 `cargo-semver-checks` maintainer here 👋 Thanks to everyone here for supporting it in Nixpkgs!

I'll have a new release out shortly.

Thanks for letting me know about the problem with the previous version and Rust 1.80 — I wasn't otherwise aware of it. If you run into any other issues, please give me a ping anytime!

Also, if there's a way to extend [the existing `cargo-semver-checks` publish pipeline](https://github.com/obi1kenobi/cargo-semver-checks/blob/main/.github/workflows/ci.yml#L1769-L1842) to simplify your workflow here, I'd love to chat more and I'd be happy to accept PRs toward that goal!

**Comment by obi1kenobi** [comment]
The new release has finished building and is live now: https://github.com/obi1kenobi/cargo-semver-checks/releases/tag/v0.34.0

**Comment by emilazy** [comment]
Thanks for the fantastic software @obi1kenobi 💜

I don’t think there’s anything in particular that would help Nixpkgs beyond the usual good practices – regular releases with CI assurance that keep on top of new compiler and dependency versions. Anything that’s published via GitHub releases is something we can create automatic update PRs on our end for.

If I had to make a suggestion, it would be to test with the latest nightly compiler in your CI (in addition to your MSRV, of course). That way this issue would have been flagged up earlier and it’s more likely you could have cut a release that works on 1.80 before the final version was released. (And, of course, the same goes for bumping crate dependencies and making sure everything still works after that, but given the nature of the tool I don’t think there’s anything new I could tell you about that!)

**Comment by emilazy** [comment]
(Well, if you could fix the `detects_target_dependencies` test depending on the network that would be great too, but we’re used to disabling tests that require network access!)

**Comment by obi1kenobi** [comment]
> Thanks for the fantastic software @obi1kenobi 💜

Thank you 😊

> I don’t think there’s anything in particular that would help Nixpkgs beyond the usual good practices – regular releases with CI assurance that keep on top of new compiler and dependency versions. Anything that’s published via GitHub releases is something we can create automatic update PRs on our end for.

Nice, good to know! `cargo-semver-checks` is always released only via GitHub Actions and comes with a tag and GitHub release entry, so it should be a good candidate for automation.

> If I had to make a suggestion, it would be to test with the latest nightly compiler in your CI (in addition to your MSRV, of course).

This is a bit complicated.

Latest nightly doesn't always pass because the underlying rustdoc JSON format often has breaking changes. Adding support for new formats requires new nightly first, then a new `rustdoc-types` release (which I don't control and which might be delayed by days/weeks), then new `trustfall-rustdoc-adapter` and `trustfall-rustdoc` releases (which I do control) and finally a PR in `cargo-semver-checks` like this one: https://github.com/obi1kenobi/cargo-semver-checks/pull/852/files

I also think that my automation that auto-applies `cargo update` weekly might have applied the `time` dependency upgrade before I noticed it caused breakage. It fixed `HEAD` automatically, but I didn't know the prior release had issues since [the (also automated) process for adding new Rust releases to the CI matrix](https://github.com/obi1kenobi/cargo-semver-checks/blob/main/.github/workflows/add_new_rust_to_matrix.yml) added 1.80 successfully just a few days prior and nothing seemed to break.

I'm hoping situations like Rust 1.80 + time are quite rare and might not be worth adding more automation around _at this time_. If we get more than one of these per year, I'll revisit and add even more testing, like "does the latest-release tag still build on all its stated supported Rust versions".

> (Well, if you could fix the `detects_target_dependencies` test depending on the network that would be great too, but we’re used to disabling tests that require network access!)

Unfortunately I think what's using the network there is `cargo`, not `cargo-semver-checks`, so it's not an easy fix.

To avoid the network call:
- We'd need the relevant `async-std` version and its dependencies to be part of cargo's cache already.
- We'd need that crate's lockfile to be checked in.

I can do the latter. The former sounds like we need to tweak the Nixpkgs build step, and I'm not sure how to do that.

Also not particularly sure if it's worth doing — I doubt that test can be broken unless you do extensive source-level patching of `cargo-semver-checks` which I don't think Nixpkgs is likely to need anytime soon.

***

As an aside, I'm surprised to see these two tests get disabled on account of needing a nightly feature:
https://github.com/NixOS/nixpkgs/pull/334394/files#diff-d2b351bdb69433869ad57b52513b4b8972d754a86658fbcca2e46b960876c2d9R39-R41

I don't think any of our tests require nightly, and in fact our CI runs all tests on all supported Rust versions. So, maybe worth another look at some point?

**Comment by emilazy** [comment]
Opened https://github.com/NixOS/nixpkgs/pull/334718 for the bump.

> This is a bit complicated.
> 
> Latest nightly doesn't always pass because the underlying rustdoc JSON format often has breaking changes. Adding support for new formats requires new nightly first, then a new `rustdoc-types` release (which I don't control and which might be delayed by days/weeks), then new `trustfall-rustdoc-adapter` and `trustfall-rustdoc` releases (which I do control) and finally a PR in `cargo-semver-checks` like this one: https://github.com/obi1kenobi/cargo-semver-checks/pull/852/files
> 
> I also think that my automation that auto-applies `cargo update` weekly might have applied the `time` dependency upgrade before I noticed it caused breakage. It fixed `HEAD` automatically, but I didn't know the prior release had issues since [the (also automated) process for adding new Rust releases to the CI matrix](https://github.com/obi1kenobi/cargo-semver-checks/blob/main/.github/workflows/add_new_rust_to_matrix.yml) added 1.80 successfully just a few days prior and nothing seemed to break.
> 
> I'm hoping situations like Rust 1.80 + time are quite rare and might not be worth adding more automation around _at this time_. If we get more than one of these per year, I'll revisit and add even more testing, like "does the latest-release tag still build on all its stated supported Rust versions".

Okay, it sounds like you’ve thought this through pretty thoroughly! I’m wondering if having non‐blocking CI for nightly compilers might still be a net positive here, though? I assume you keep on top of rustdoc changes anyway, so the notification of those probably wouldn’t do you much good, but it’d help flag up issues like this.

Though, yes, I agree: 1.80 has been awful and I hope that the Rust team don’t make a habit of this kind of thing.

> I can do the latter. The former sounds like we need to tweak the Nixpkgs build step, and I'm not sure how to do that.
> 
> Also not particularly sure if it's worth doing — I doubt that test can be broken unless you do extensive source-level patching of `cargo-semver-checks` which I don't think Nixpkgs is likely to need anytime soon.

Gotcha. We’re fine with disabling network‐dependent tests; it happens all the time.

> As an aside, I'm surprised to see these two tests get disabled on account of needing a nightly feature: https://github.com/NixOS/nixpkgs/pull/334394/files#diff-d2b351bdb69433869ad57b52513b4b8972d754a86658fbcca2e46b960876c2d9R39-R41
> 
> I don't think any of our tests require nightly, and in fact our CI runs all tests on all supported Rust versions. So, maybe worth another look at some point?

You’re right; these pass now. I’ve re‐enabled them in the new PR.

I’ve also opened https://github.com/obi1kenobi/cargo-semver-checks/issues/855 for the one remaining nit I can see in terms of what would make the packaging story for us easier. Thank you again for taking the time to ask about our packaging and being open to improvements! I would say you’re already doing a stellar job as an upstream :)

**Comment by obi1kenobi** [comment]
Thanks for the useful suggestions! I appreciate you thinking this through with me, and I'm happy to do what I can to make your work easier :)

> I’m wondering if having non‐blocking CI for nightly compilers might still be a net positive here, though? I assume you keep on top of rustdoc changes anyway, so the notification of those probably wouldn’t do you much good, but it’d help flag up issues like this.

That's pretty much the exact current setup:
- I get GitHub-mentioned whenever anyone opens a PR that includes changes to rustdoc JSON, so I always have ~one day's notice of any format changes before they appear in nightly.
- `cargo-semver-checks` runs nightly Rust tests but doesn't block if they fail.

While I'm sure there are improvements one could make from here, it feels like there's nothing easy and obvious remaining — we seem to have picked all the low-hanging fruit here.

> You’re right; these pass now. I’ve re‐enabled them in the new PR.

Yay, nice! If you find that tests are failing for you in the future and it isn't purely a network issue, please feel free to ping me on the relevant PR or issue. I'd be happy to look and make sure it isn't some unfortunate Heisenbug.

I'm taking a look at the new issue you opened now, and will chat more there.

> Thank you again for taking the time to ask about our packaging and being open to improvements! I would say you’re already doing a stellar job as an upstream :)

Of course, thank you for all the work you've been doing — I appreciate it!

**Pull request closed without merging**
