### PR TITLE
nixos/transmission: Enable configuring permissions of home dir

### PR DESCRIPTION
**Pull request by doronbehar**
###### Motivation for this change

Continuing from @dsg22's work in https://github.com/NixOS/nixpkgs/commit/077934e1928f7cbfa7f4391f960dce3807515c5e, today I noticed that with a downloadDir pointing e.g to  `${homeDir}/Downloads` (The default), it's impossible to `cd` to it since the `${homeDir}` permissions are always set to `700`. It's funny this hasn't bothered anyone up until now.. With these changes, the default allows `750` access to the `${homeDir}` and the `${downloadDir}` so at least by default users in the `transmission` group will be able to access it.

Also, I did some small variables renames I think improve the readability of the service, hope it's OK with you.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc:
* @dsg22 - The author of https://github.com/NixOS/nixpkgs/commit/077934e1928f7cbfa7f4391f960dce3807515c5e .
* @coreyoconnor - you seem to be the maintainer of this module according to the test file.
* @Lassulus - Since it seems you merged @dsg22's PR.

### CODE REVIEW

**Comment by bb2020** [comment]
Another problem is when `downloadDir` is changed and if transmission user can not create the new directory, the service fails to start. This is especially important if the destination directory is owned by root (for example `/home/mytransmission`). I have made some changes to address the issue on top of your commit: https://github.com/bb2020/nixpkgs/commit/3f5e465bf8b3468fdb9f4a570b801b1f90376d3d

**Comment by doronbehar** [comment]
I'm not sure I figured out what you mean. Are you saying that the preStart script creating the necessary directories is being run by `transmission` as this is the user of the systemd service? Meaning that if the user `transmission` can't create these directories then the service will fail?

I'm not sure how exactly your changes improve that, nothing there elevates the permissions of the preStart script so that the `mkdir` command is being run `root`. Besides, I think if someone chooses such a non standard directory as a download-dir, it's rather reasonable that he will manually create it and then the preStart script will only set the permissions.

**Comment by bb2020** [comment]
`transmission` user is not a super user, so it can not create necessary folders when non-default `downloadDir` is used. By running `preStart` as root, this can be solved. I've modified my comment above to include only two more lines.

**Comment by doronbehar** [comment]
Thanks for clarifying this @bb2020. The question is, are you sure the preStart script won't fail because the `ExecStartPre` is being run by `transmission` which is not privileged? Also what does this line do:

https://github.com/bb2020/nixpkgs/blob/c0cac417e4ad094dbd9a7ca2776d97b409722b8c/nixos/modules/services/torrent/transmission.nix#L141

?

As for this privileges doubt, according to `systemd.service`'s man page (see [this table](https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStart=)), we should use the `+` as a prefix to the `ExecStartPre` and this will ensure the `ExecStartPre` script will be able to actually `mkdir` this directories.

**Comment by bjornfor** [comment]
This reminds me that @aszlig wrote about a "directories" module in https://github.com/NixOS/nixpkgs/pull/59988#issuecomment-533868004. I think having something like that in NixOS would be nice, and help with issues like this.

**Comment by bb2020** [comment]
> today I noticed that with a downloadDir pointing e.g to ${homeDir}/Downloads (The default), it's impossible to cd to it since the ${homeDir} permissions are always set to 700

If you ask me, introducing `homeDirPermissions ` is not necessary. Assigning `homeDir` dir to `770` and `settingsDir` to `700` should be sufficient.

> what does this line do: https://github.com/bb2020/nixpkgs/blob/c0cac417e4ad094dbd9a7ca2776d97b409722b8c/nixos/modules/services/torrent/transmission.nix#L141

`PermissionsStartOnly` runs `preStart` as root, but not the service process itself. However it looks like it is deprecated and similar modules have been ported to `systemd.tmpfiles`.

I've made some changes here that fixes both issues, I presume. https://github.com/bb2020/nixpkgs/commit/a06e0a1408bba759b603d3f553320832308b06f1

**Comment by doronbehar** [comment]
Now that's the systemd way of handling this! Kind of makes @aszlig's thing redundant doesn't it? @bb2020 would you like to create a new PR? I'm off my laptop at the moment...

**Comment by bb2020** [comment]
It is actually a discouraged method. However, I see it is widely used by many modules 😃 
I don't have time to test it though. I was hoping you would test it and go on with this PR.

**Comment by doronbehar** [comment]
Discouraged? That's interesting.. Have you discovered it's discouraged in an RFC perhaps?

**Comment by bb2020** [comment]
It was previously discussed in some `nixpkgs` issues.

**Comment by doronbehar** [comment]
It'd be nice to talk it over at [nixos/RFCs](https://github.com/NixOS/rfcs), or the forums.. When I'll find the time I'll quote you so you could join the discussion :)

P.S I'll test your implementation as well.

**Comment by doronbehar** [comment]
BTW Speaking of improvements to this module, does anybody has a clear guess on how to fix this warnings I've been getting lately:

```
trace: warning: In file /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/services/torrent/transmission.nix
a list is being assigned to the option config.users.users.
This will soon be an error as type loaOf is deprecated.
See https://git.io/fj2zm for more information.
Do
  users.users =
    { transmission = {...}; ...}
instead of
  users.users =
    [ { name = "transmission"; ...} ...]

trace: warning: In file /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/services/torrent/transmission.nix
a list is being assigned to the option config.users.groups.
This will soon be an error as type loaOf is deprecated.
See https://git.io/fj2zm for more information.
Do
  users.groups =
    { transmission = {...}; ...}
instead of
  users.groups =
    [ { name = "transmission"; ...} ...]
```

**Comment by Lassulus** [comment]
I would prefer this over https://github.com/NixOS/nixpkgs/pull/78113 since i want transmission group members to be able to write/move files inside the transmission directory

**Comment by aszlig** [comment]
> This reminds me that @aszlig wrote about a "directories" module in [#59988 (comment)](https://github.com/NixOS/nixpkgs/pull/59988#issuecomment-533868004). I think having something like that in NixOS would be nice, and help with issues like this.

For thinks like eg. runtime or state directories, systemd can already handle this (as @doronbehar mentioned), but AFAIK it only applies to those standard directory layouts and not arbitrary directories. The module above however is fairly complex (mainly because it also supports POSIX ACLs), so I'm not really sure whether it would be worth introducing additional complexity if it's only used for like 2 modules.

**Comment by bjornfor** [comment]
> The module above however is fairly complex (mainly because it also supports POSIX ACLs), so I'm not really sure whether it would be worth introducing additional complexity if it's only used for like 2 modules.

Perhaps a module like that might have more user out-of-tree than in-tree? I know that personally I would use it out-of-tree (for my nixos configs).

**Comment by doronbehar** [comment]
I'm closing this as I will (some when in the future) create a PR with broader changes for permissions of services/modules - as mentioned in that discourse thread^ (https://discourse.nixos.org/t/nixpkgs-policy-as-for-systemd-prestart-setup-scripts-vs-systemd-tmpfiles/5839/1).

In the meantime, I'm using:

```nix
    systemd.services.transmission.serviceConfig.ExecStartPre = pkgs.lib.mkForce null;
```

**Pull request closed without merging**
