### PR TITLE
nixos/syncthing: add option to set GUI credentials

### LINKED ISSUE #85336: Declare Syncthing GUI password option
## Issue description

NixOS' [Syncthing service module](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/syncthing.nix) doesn't provide a way to set a password on the GUI. Without a password, any user on the machine (if listening on localhost) can see the files being synced.

Syncthing's [`config.xml`](https://docs.syncthing.net/users/config.html) has a `password` field which takes a hashed password and can restrict access to the GUI. Could NixOS provide a configuration option for that field?

### PR DESCRIPTION
**Pull request by syberant**
Fixes: #85336

This extends the script that's updating the syncthing config a bit.
I have tested it on my machine (famous last words) and it works fine there, I was on an old pinned commit though and have just cherry-picked it on to the master branch.
~~I'm planning to better test it soon but for now I'm putting it up here as a draft.~~
I didn't really have time to learn how proper NixOS tests work and don't need the functionality right now, might come back to it later.

###### Motivation for this change
This adds the ability to declaratively set a username and password for syncthing. See the issue for more details.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by totoroot** [comment]
May I asked why this was closed. Simply because no one cared to review and merge?

**Comment by syberant** [comment]
Sorry, it's because I've only contributed 1 package and a few bugfixes before.
I got kind of jumpy at messing with passwords so I wanted some kind of NixOS test but I've never worked with them before, got a bit stuck and suddenly got pretty busy.

After a while I closed it because I didn't like keeping it up without progress, reasoning being that the code is still there if I or somebody else (maybe a little more experienced) wants to pick it up again.

**Comment by bjornfor** [comment]
I think the next iteration of this PR should read the password from an arbitrary path at runtime. Then people can either keep the secret completely out of the nix store, or not, depending on their threat model.

**Comment by syberant** [comment]
Hmm, keeping it out of the store does seem nice. Mitigating factor is that syncthing's [`gui.password`](https://docs.syncthing.net/users/config.html#config-option-gui.password) is a hash instead of just plaintext password.

**Comment by keithy** [comment]
Except it doesnt appear to be a hash when you set it

**Comment by syberant** [comment]
Ah, I missed that you could set the password via a flag, could also be a good option to implement this.
What I did in this experimental PR was to change the (a bit hacky) script directly updating the config file to also change the password field (which is fortunately hashed and not plaintext in the file).

**Comment by keithy** [comment]
Done!
https://gitlab.com/keithy/nixnet/-/blob/test/use/syncthing/set_gui_user_password.nix

**Comment by syberant** [comment]
Nice! That also reads the password from an arbitrary path at runtime as @bjornfor suggested.
If you want to I think a PR would be warmly received.

**Comment by keithy** [comment]
As you can see its quite new, aim to PR shortly.

**Comment by nrbray** [comment]
> Done! https://gitlab.com/keithy/nixnet/-/blob/test/use/syncthing/set_gui_user_password.nix

Page Not Found

**Comment by keithy** [comment]
```
{ config, options, pkgs, lib, ... }:

with lib;
let  
  cfg = config.services.syncthing;

  setCredScript = pkgs.writers.writeBash "syncthing-set-gui-creds" ''
    ${config.services.syncthing.package}/bin/syncthing generate \
      --gui-user=${cfg.guiUser} --gui-password=- < ${cfg.guiPasswordFile}
    '';
in
{
  options.services.syncthing = {
    guiUser = mkOption {
      type = types.nullOr types.str;
      default = null;
      example = "admin";
      description = ''
          The gui users
      '';
    };
    guiPasswordFile = mkOption {
      type = types.nullOr types.str;
      default = null;
      example = "/run/secrets/syncthing.password";
      description = ''
          The gui password file
      '';
    };
  };

  config.systemd.services.syncthing = mkIf cfg.enable {
    serviceConfig = {
      ExecStartPre = mkIf (cfg.guiUser != null || cfg.guiPasswordFile != null) 
        "${setCredScript}";
    };
  };
}

```

**Comment by keithy** [comment]
{ config, options, pkgs, lib, ... }:

with lib;
let  
  cfg = config.services.syncthing;

  setCredScript = pkgs.writers.writeBash "syncthing-set-gui-creds" ''
    ${config.services.syncthing.package}/bin/syncthing generate \
      --gui-user=${cfg.guiUser} --gui-password=- < ${cfg.guiPasswordFile}
    '';
in
{
  options.services.syncthing = {
    guiUser = mkOption {
      type = types.nullOr types.str;
      default = null;
      example = "admin";
      description = ''
          The gui users
      '';
    };
    guiPasswordFile = mkOption {
      type = types.nullOr types.str;
      default = null;
      example = "/run/secrets/syncthing.password";
      description = ''
          The gui password file
      '';
    };
  };

  config.systemd.services.syncthing = mkIf cfg.enable {
    serviceConfig = {
      ExecStartPre = mkIf (cfg.guiUser != null || cfg.guiPasswordFile != null) 
        "${setCredScript}";
    };
  };
}

**Pull request closed without merging**
