### PR TITLE
firefox-bin: 43.0.3 -> 43.0.4

### PR DESCRIPTION
**Pull request by taku0**
- Re-enable SHA-1 certificates
- Bug fixes

https://www.mozilla.org/en-US/firefox/43.0.4/releasenotes/

### CODE REVIEW

**Comment by copumpkin** [comment]
> Re-enable SHA-1 certificates

:angry: (but I understand)

**Comment by vcunat** [comment]
Is there a reason why `firefox-bin` has no wrapper? Our wiki even [has work-around for that](https://nixos.org/wiki/Firefox). Now I changed FF-like browsers to be wrapped by default #12299, as almost all people want that version, so why not the same for `firefox-bin` as well?

**Comment by taku0** [comment]
It's just my laziness. In NixOS, `MOZ_PLUGIN_PATH` is configured by `nixos/modules/programs/environment.nix`, so that I can use Flash Player without a wrapper.

I will create a wrapped package soon.

**Comment by taku0** [comment]
@vcunat Created a wrapped package: #12416.

**Pull request merged**
