### PR TITLE
python3Packages.python-awair: init at 0.2.1

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Python library for the Awair API

https://github.com/ahayworth/python_awair

Switch to `poetry-core` [suggested](https://github.com/ahayworth/python_awair/pull/22) to upstream.

This is a Home Assistant dependency.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 114470` at 9625b922 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/ca4f7efb1f3903f140bbf85b7ec0102b">python37Packages.python-awair</a></li></li>
    <li><a href="https://gist.github.com/e0d62f4a14271a5b8a967b62a650782d">python38Packages.python-awair</a></li></li>
  </ul>
</details>

**Comment by ahayworth** [comment]
@fabaff I've published 0.2.2 which switches to poetry-core, if you'd prefer to use that instead!

**Comment by SuperSandro2000** [comment]
> @fabaff I've published 0.2.2 which switches to poetry-core, if you'd prefer to use that instead!

We can do that in another PR.

**Comment by fabaff** [comment]
Thanks for the heads-up, @ahayworth.

Thanks for the review, @SuperSandro2000

**Pull request merged**
