### PR TITLE
perlPackages: update

### PR DESCRIPTION
**Pull request by volth**
Update `perlPackages` to the latest CPAN versions
Fixes #48857
Fixes #62278
Fixes #63230
Fixes #64137

@aanderse @rycee

### CODE REVIEW

**Comment by volth** [comment]
@GrahamcOfBorg build hydra

**Comment by jonringer** [comment]
buildilng of hydra fails for me

<details> <summary>Fail log </summary> 

```
$ git log --oneline | head -n5 # just to show im oim on the right branch
5e2e9764248 perlPackages.AppClusterSSH: init at 4.13.2
9fad02b798a [cpan2nix] perlPackages.DeviceSerialPort: init at 1.04
b24496a3492 [cpan2nix] perlPackages.DistZillaPluginTestMinimumVersion: 2.000008 -> 2.000010
b8e6ffb1547 [cpan2nix] perlPackages.CatalystViewJSON: 0.36 -> 0.37
b3e67a31057 [cpan2nix] perlPackages.TaskFreecellSolverTesting: cleanup

$ nix-build default.nix -A hydra --cores 1 --show-trace
...
Cases: 15  Tried: 6  Errors: 0  Failures: 0  creating: test-zip-archive.-6e79b56754d3fb92/dir1
  creating: test-zip-archive.-6e79b56754d3fb92/dir1/dir2
 inflating: test-zip-archive.-6e79b56754d3fb92/dir1/dir2/hello
extracting: test-zip-archive.-6e79b56754d3fb92/dir1/hi
Cases: 15  Tried: 11  Errors: 0  Failures: 0  creating: test-zip-archive.-6e79b56754d3fb92/dir3
extracting: test-zip-archive.-6e79b56754d3fb92/dir3/hi
Cases: 15  Tried: 14  Errors: 0  Failures: 0Archive:  ./test-zip-archive.-6e79b56754d3fb92/testUnzip.zip
   creating: test-zip-archive.-6e79b56754d3fb92/test_dir_with_symlinks4/
   creating: test-zip-archive.-6e79b56754d3fb92/test_dir_with_symlinks4/1/
 extracting: test-zip-archive.-6e79b56754d3fb92/test_dir_with_symlinks4/1/file.txt
error: invalid zip file with overlapped components (possible zip bomb)
### Failure in: 14
tests/test-zip-archive.hs:273
unzip succeeds
Cases: 15  Tried: 15  Errors: 0  Failures: 1
test-zip-archive.-6e79b56754d3fb92/test_dir_with_symlinks2/
test-zip-archive.-6e79b56754d3fb92/test_dir_with_symlinks2/1/
test-zip-archive.-6e79b56754d3fb92/test_dir_with_symlinks2/1/file.txt
test-zip-archive.-6e79b56754d3fb92/test_dir_with_symlinks2/link_to_file
test-zip-archive.-6e79b56754d3fb92/test_dir_with_symlinks2/link_to_directory
test-zip-archive.-6e79b56754d3fb92/test_dir_with_symlinks2/link_to_directory/file.txt
test-zip-archive.-6e79b56754d3fb92/test_dir_with_symlinks2/
test-zip-archive.-6e79b56754d3fb92/test_dir_with_symlinks2/1/
test-zip-archive.-6e79b56754d3fb92/test_dir_with_symlinks2/1/file.txt
test-zip-archive.-6e79b56754d3fb92/test_dir_with_symlinks2/link_to_file
test-zip-archive.-6e79b56754d3fb92/test_dir_with_symlinks2/link_to_directory
Test suite test-zip-archive: FAIL
Test suite logged to: dist/test/zip-archive-0.4.1-test-zip-archive.log
0 of 1 test suites (0 of 1 test cases) passed.
checking for struct utmpx.ut_syslen... no
builder for '/nix/store/c09c5b30vn3941cv0gkvn7s17ksy4453-zip-archive-0.4.1.drv' failed with exit code 1
cannot build derivation '/nix/store/mb3c4rakfqgb9n44kbvgbsjxbymr3vfi-darcs-2.14.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/0prm7lz5nvcpdm24q9qryr59d9d0v2q5-nix-build.drv': 1 dependencies couldn't be built
error: build of '/nix/store/0prm7lz5nvcpdm24q9qryr59d9d0v2q5-nix-build.drv' failed
```

</details>

**Comment by volth** [comment]
> buildilng of hydra fails for me

The same before this PR

nix-build --option binary-caches http://cache.nixos.org/ -E "(import (builtins.fetchTarball https://github.com/NixOS/nixpkgs/archive/staging.tar.gz) { }).hydra"

It is something broken in `haskellPackages`, not `perlPackages`

**Comment by volth** [comment]
ping?

**Comment by volth** [comment]
@peti 
could you please ```s/gdk_pixbuf/gdk-pixbuf/g``` in the script which generates "hackage-packages.nix" ?
ofborg fails: https://gist.github.com/GrahamcOfBorg/a82c866c1ea14360edaa8f72276238d8

**Comment by peti** [comment]
@volth, this has been done in https://github.com/NixOS/cabal2nix/pull/424 already. Note that I don't re-generate anything in `staging`. I target only `master`.

**Comment by volth** [comment]
`master` is not yet regenerated (https://github.com/NixOS/nixpkgs/commits/master/pkgs/development/haskell-modules/hackage-packages.nix)
ok, let's wait update of `master` and its merge to `staging`

**Comment by FRidh** [comment]
please rebase

**Comment by peti** [comment]
@volth,

> ok, let's wait update of `master` and its merge to `staging`

I cannot re-generate `master` until `staging` has been merged because that update would break all code that depends on `gdk-pixbuf` (which does not exist in `master`).

**Comment by volth** [comment]
It seems fixed on staging: https://github.com/NixOS/nixpkgs/commit/360e687df95edb120ca4090acfe83a9518102953#diff-e4ed6fefa9564bfd27ee249e42e145e2

**Comment by aanderse** [comment]
@jonringer @peti Any outstanding issues preventing a merge to `staging` or should we pull the trigger?

**Pull request merged**
