### PR TITLE
Fix i3 and rxvt-unicode on OS X.

### PR DESCRIPTION
**Pull request by cresh**
These are fixes I made for [joelteon/nixpkgs](https://github.com/joelteon/nixpkgs) that haven't made it over to upstream master, yet.  I've cherry-picked them into this pull request.  You can find the original pull requests and discussions at [https://github.com/joelteon/nixpkgs/pull/16](https://github.com/joelteon/nixpkgs/pull/16) and [https://github.com/joelteon/nixpkgs/pull/19](https://github.com/joelteon/nixpkgs/pull/19).

### CODE REVIEW

**Comment by shlevy** [comment]
@cresh can you pull out the xcb-util-cursor commit/revert pair?

**Comment by cresh** [comment]
Thanks for the detailed review, I've rebased according to your suggestions.

**Comment by gridaphobe** [comment]
@cresh are you actually able to build `rxvt_unicode` on darwin? I'm getting a build failure (well, test-suite specifically) at `gdk-pixbuf`.

**Comment by cresh** [comment]
@gridaphobe Yes, `rxvt_unicode` builds fine for me on OS X 10.10.2.

**Pull request merged**
