### PR TITLE
gnome2.gnome_icon_theme: 2.91.93 -> 3.12.0

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

- gnome2.gnome_icon_theme: 2.91.93 -> 3.12.0
- gnome2.gnome_icon_theme: use pname and version
- gnome2.gnome_icon_theme: add meta attributes
- gnome2.gnome_icon_theme: change platform to unix
- gnome2.gnome_icon_theme: minor layout change
- gnome2.gnome_icon_theme: do not drop icon theme cache
- treewide: rename gnome2.gnome_icon_theme package to use dashes

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by rasendubi — APPROVED** [review]
The diff looks good to me :+1:

**Comment by jtojnar** [comment]
Ugh, do these things still work? GNOME panel has changed its API at least three times so I doubt Alarm clock will do anything.

I would just remove as much of gnome2 attribute set as possible.

**Comment by romildo** [comment]
I am more interested in `gnome-icon-theme` because there are several other icon themes that still inherits from it.

I intend to add dependencies for icon themes (at least the ones I maintain) according to the inheritance declared in their `index.theme`.

**Comment by jtojnar** [comment]
Could you also move it out of `gnome2` attribute set, then? I intend to get rid of it this cycle.

**Comment by romildo** [comment]
> Could you also move it out of `gnome2` attribute set, then? I intend to get rid of it this cycle.

Done.

**Review by jtojnar — APPROVED** [review]

**Pull request merged**
