### PR TITLE
pythonPackages.pygments: enable tests

### PR DESCRIPTION
**Pull request by risicle**
###### Motivation for this change
In #117810 I was annoyed by tests being disabled for `pygments`, so I implemented the same trick as used for `hypothesis` to allow only `pytest` to be built with an untested `pygments`.

As for the 2.5.x branch, used in `python2Packages`, the advice over circular dependencies appears to be outdated - I didn't have a problem just enabling these.

I've done a full re-eval successfully (obviously not a full rebuild) and built a number of key packages.. is there anything else I've missed?

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
@ofborg build python38Packages.sphinx

**Review by dotlambda — COMMENTED** [review]
Why don't we do this within `5.nix` and `default.nix`?
This trick only works because these two packages are not in pytest's `propagatedBuildInputs`. That they are not is only apparent from within the expression.

**Comment by risicle** [comment]
:shrug: I don't know, to me it's 6 of one and half a dozen of the other. I just went with what was being done for `hypothesis`.

**Comment by SuperSandro2000** [comment]
> Why don't we do this within `5.nix` and `default.nix`?

Tests should be activated for 5.nix, too.

**Comment by SuperSandro2000** [comment]
> Why don't we do this within `5.nix` and `default.nix`?
> This trick only works because these two packages are not in pytest's `propagatedBuildInputs`. That they are not is only apparent from within the expression.

This trick does not work when packages are in propagatedBuildInputs because then pip can think the package is already installed and does not install anything.

**Pull request merged**
