### PR TITLE
treewide: pkgconfig -> pkg-config

### PR DESCRIPTION
**Pull request by siraben**
###### Motivation for this change
`pkg-config` is the preferred naming.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by siraben** [comment]
Goal is rebuild 0.

**Comment by siraben** [comment]
Ignoring EditorConfig checks.

**Comment by jonringer** [comment]
```
anonymous function at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/ofborg-evaluator-1/pkgs/tools/networking/curl/default.nix:1:1 called with unexpected argument 'pkgconfig',
```

**Comment by jonringer** [comment]
honestly, I would just `s/pkgconfig/pkg-config/g` everything, then just add an `pkgconfig = pkg-config` in alias.nix

**Comment by siraben** [comment]
> honestly, I would just `s/pkgconfig/pkg-config/g` everything, then just add an `pkgconfig = pkg-config` in alias.nix

This wouldn't work because there's several instances of `pkgconfig` being used in strings, e.g. in `installPhase`.

**Comment by jonringer** [comment]
but the command name exported is `pkg-config`
```
$ tree ./result/bin/
./result/bin/
└── pkg-config
```

**Comment by siraben** [comment]
e.g. `$out/{lib,share}/pkgconfig`

**Comment by siraben** [comment]
Also occurs in various Qt, Python packages and meson files.

**Comment by jonringer** [comment]
ah, said times :(

**Review by jonringer — COMMENTED** [review]
do you mind undoing the changes to ` pkgs/tools/misc/microplane/deps.nix` , I think the new line is causing the three re-builds

Otherwise LGTM

**Comment by jonringer** [comment]
actually, the builds were quite fast. Going to merge this before it bit rots

**Review by jonringer — COMMENTED** [review]
LGTM

Result of `nixpkgs-review pr 109595` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>microplane</li>
    <li>solfege</li>
    <li>spacevim</li>
  </ul>
</details>

**Comment by siraben** [comment]
`deps.nix` is probably autogenerated, so this change should be harmless.

**Comment by siraben** [comment]
Remaining progress:
```
or i in pkgs/*; do printf "%s %s\n" "$i" "$(rg 'pkgconfig' "$i" | wc -l)"; done | sort -r -n -k 2
pkgs/development 2135
pkgs/applications 1036
pkgs/servers 638
pkgs/tools 520
pkgs/os-specific 238
pkgs/top-level 73
pkgs/build-support 28
pkgs/desktops 11
pkgs/misc 9
pkgs/games 4
pkgs/test 0
pkgs/stdenv 0
pkgs/shells 0
pkgs/pkgs-lib 0
pkgs/data 0
pkgs/common-updater 0
```

**Comment by jonringer** [comment]
thanks for doing this :). It was getting tiring to say "please use `pkg-config`, I know there's several thousand instances of `pkgconfig` used, but please trust me it's there for historical reasons"

**Comment by SuperSandro2000** [comment]
> thanks for doing this :). It was getting tiring to say "please use `pkg-config`, I know there's several thousand instances of `pkgconfig` used, but please trust me it's there for historical reasons"

Same for me. Especially if people get pissed about it.

**Pull request merged**
