### PR TITLE
staging-next-22.11 - iteration 7 - 2023-04-13

### PR DESCRIPTION
**Pull request by vcunat**
- workflow docs: https://nixos.org/manual/nixpkgs/stable/#submitting-changes-stable-release-branches
- important job: https://hydra.nixos.org/job/nixpkgs/staging-next-22.11/unstable#tabs-constituents
- jobset: https://hydra.nixos.org/jobset/nixpkgs/staging-next-22.11
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next-22.11 PR: https://github.com/NixOS/nixpkgs/pull/223595
- - - 
##### Significant breakages
(will be edited in future)
- [x] `libreoffice` tests https://hydra.nixos.org/build/215973648
  ~Probably~ broken by libxml2 update; hopefully a problem in the tests themselves.
- [x] `python3Packages.anyio` tests on *-linux https://hydra.nixos.org/build/216094585

### CODE REVIEW

**Comment by vcunat** [comment]
@7c6f434c: any suggestion on what approach to take about the [libreoffice tests](https://hydra.nixos.org/build/215973648/nixlog/6/tail) that regressed due to [libxml2 security update](https://gitlab.gnome.org/GNOME/libxml2/-/compare/v2.10.3...v2.10.4)?  (I verified that just reverting the single commit makes the errors go away.)

**Comment by 7c6f434c** [comment]
Hm, this is the old Stil on a release branch, and maybe the change does indeed slightly change the thing LibreOffice cares about? I don't think this is worse than some of the other tests we have edited out, and I wouldn't expect any useful information about this LO+libxml2 version combination to be spontaneously provided by upstream. So commenting this out sounds fine to me. (I never use release branches, so I don't have any idea whether backporting larger LO bumps is sensible)

**Comment by vcunat** [comment]
Version probably doesn't matter here.  7.4.2.3 also shows the same.  I think it's just about 22.11 applying the libxml2 bump first and we'll get it on nixpkgs master this week, too.

**Comment by 7c6f434c** [comment]
I suppose `sed -e 's@.*"/html/body/div/table/tr/th".*@//&@' -i sw/qa/extras/htmlexport/htmlexport.cxx` might work, but I am not going to build LibreOffice locally any time soon…

(it should basically make the useful part of the body of `DECLARE_HTMLEXPORT_TEST(testReqIfTable, "reqif-table.xhtml")` commented out in that file)

**Comment by vcunat** [comment]
I have lots of CPUs available and looking into it for several minutes already.

**Comment by vcunat** [comment]
My attempt didn't work but yours did, so I'm pushing that in your name.

**Pull request merged**
