### PR TITLE
[19.03] gitlab updates

### PR DESCRIPTION
**Pull request by flokli**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/pull/66621

had to cherry-pick some changes from unstable as well.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @lheckemann @talyz @bgamari

### CODE REVIEW

**Comment by adisbladis** [comment]
@GrahamcOfBorg test gitlab

**Comment by flokli** [comment]
For some reason, `gitlab-rake gitlab:shell:create_hooks` is failing like this:

```
gitlab# [  359.493137] 0qa9yb6sfx690qahdhljghmryvm2yjwf-unit-script-gitlab-pre-start[1105]: rake aborted!
gitlab# [  359.494934] 0qa9yb6sfx690qahdhljghmryvm2yjwf-unit-script-gitlab-pre-start[1105]: Don't know how to build task 'gitlab:shell:create_hooks' (See the list of available tasks with `rake --tasks`)
gitlab# [  359.501036] 0qa9yb6sfx690qahdhljghmryvm2yjwf-unit-script-gitlab-pre-start[1105]: /nix/store/gb4ggiirx02310n9z421jwgwk2qg366n-gitlab-env-12.1.6/lib/ruby/gems/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
gitlab# [  359.503296] 0qa9yb6sfx690qahdhljghmryvm2yjwf-unit-script-gitlab-pre-start[1105]: (See full trace by running task with --trace)
```

Interestingly, this works just fine on unstable (with pretty much the same codebase in `pkgs/applications/version-management/gitlab`), so I don't really understand what's going on.

**Comment by globin** [comment]
gitlab:shell:create_hooks has been removed upstream, I'm pretty sure i removed this on master, will try to get to test this on our instance tomorrow. But don't necessarily block merging on this, looks fine generally.

**Comment by flokli** [comment]
I'd rather not break the gitlab vm tests on 19.03. will have a look later today, thanks for the pointer!

**Comment by flokli** [comment]
I gave this a close look - the removal of the `create_hooks` command happened inside 783c2f61066ff25718df39f4b5d4ef1193ed86d9.

I managed to spot some other missed commits, the nixos module on master and in this PR are now in sync (except 3f4a353737f165d4935c0404404c0de6eea92093 not applied).

**Comment by flokli** [comment]
@GrahamcOfBorg test gitlab

**Comment by flokli** [comment]
@globin did you get a chance to give this a test run on your instance?

**Comment by ciil** [comment]
@flokli just tested with our instance, lgtm!

**Comment by flokli** [comment]
Thanks!

**Pull request merged**
