### PR TITLE
vlang: update to latest

### PR DESCRIPTION
**Pull request by happysalada**
###### Description of changes

I had a go at an update of vlang.
here is where I am at.
On darwin, I've got a failure almost immediately with
```
vlang> cc  -std=gnu99 -w -o v1.exe /nix/store/2pn7pylgi3lhjjkp64456j5afdlv93r0-source/v.c -lm -lpthread
vlang> In file included from /nix/store/2pn7pylgi3lhjjkp64456j5afdlv93r0-source/v.c:1986:
vlang> /nix/store/c834w8pg8ypl9lcaxqgj2bpsxbv518rn-Libsystem-1238.60.2/include/sys/ptrace.h:99:38: error:
unknown type name 'caddr_t'
vlang> int     ptrace(int _request, pid_t _pid, caddr_t _addr, int _data);
vlang>                                          ^
vlang> 1 error generated.
vlang> make: *** [GNUmakefile:113: all] Error 1
```

on linux, I get the thing to compilation to finish, but upon the ldd step I get a
```
> cc  -std=gnu99 -w -o v1.exe /nix/store/2pn7pylgi3lhjjkp64456j5afdlv93r0-source/v.c -lm -lpthread
vlang> ./v1.exe -no-parallel -o v2.exe  cmd/v
vlang> ./v2.exe -nocache -o ./v  cmd/v
vlang> rm -rf v1.exe v2.exe
vlang> ==================
vlang> tcc: error: file '/build/source/thirdparty/tcc/lib/libgc.a' not found
vlang> ...
vlang> ==================
vlang> (Use `v -cg` to print the entire error message)
vlang>
vlang> builder error:
vlang> ==================
vlang>
vlang> This is a compiler bug, please report it using `v bug file.v`.
vlang>
vlang> https://github.com/vlang/v/issues/new/choose
vlang>
vlang> You can also use #help on Discord: https://discord.gg/vlang
vlang>
vlang> make: *** [GNUmakefile:117: all] Error 1
```

@Madouura I know you've worked on this before, you might have a better idea than me.
I originally thought it was a missing libgc library, so I pulled that repo and built it, but it doesn't provide libgc.a file, not in the normal derivation nor in the dev version. So not sure how to continue ther.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
I've now got the libgc.a error fixed, the file is in pkgsStatic.boehmgc
I now get another error
```
==================
vlang> tcc: error: undefined symbol 'sigsetjmp'
vlang> ...
```
no idea what that is about.

**Comment by happysalada** [comment]
I've tried modifying the CFLAGS but that didn't work. The missing header file is in glibc, I just don't know how to pass that to the tcc compilation process.
I've opened an issue on vlang https://github.com/vlang/v/issues/18183

**Comment by happysalada** [comment]
I've got one step further, the v compilation works, but it fails on building the tools

```
this derivation will be built:
  /nix/store/n4wna216320mb7npb1v4xrlx4nbqqs61-vlang-weekly.2023.19.drv
vlang> building '/nix/store/n4wna216320mb7npb1v4xrlx4nbqqs61-vlang-weekly.2023.19.drv'
vlang> unpacking sources
vlang> unpacking source archive /nix/store/rq8s4xv490g36hzqyyhmix7hh72ljxna-source
vlang> source root is source
vlang> patching sources
vlang> configuring
vlang> no configure script, doing nothing
vlang> building
vlang> build flags: SHELL=/nix/store/ywi6kzrk88zl22jvazdnlfaf9rqrj2aq-bash-5.2-p15/bin/bash local=1
vlang> ldd: /bin/ls: $No such file or directory
vlang> Using local vc
vlang> Using local tcc
vlang> gcc  -std=gnu99 -w -o v1.exe /nix/store/2pn7pylgi3lhjjkp64456j5afdlv93r0-source/v.c -lm -lpthread
vlang> ./v1.exe -no-parallel -o v2.exe  cmd/v
vlang> ./v2.exe -nocache -o ./v  cmd/v
vlang> rm -rf v1.exe v2.exe
vlang> Your `tcc` is working. Good - it is much faster at compiling C source code.
vlang> V has been successfully built
vlang> V 0.3.4 a7f84e7
vlang> buildPhase completed in 2 minutes 19 seconds
vlang> installing
vlang> launch_tool vexe        : /nix/store/4m7m7xx2qwvkkyb44csj9ynw3qyzf5fw-vlang-weekly.2023.19/lib/v
vlang> launch_tool vroot       : /nix/store/4m7m7xx2qwvkkyb44csj9ynw3qyzf5fw-vlang-weekly.2023.19/lib
vlang> launch_tool tool_source : /nix/store/4m7m7xx2qwvkkyb44csj9ynw3qyzf5fw-vlang-weekly.2023.19/lib/cmd/
tools/vbuild-tools.v
vlang> launch_tool tool_exe    : /nix/store/4m7m7xx2qwvkkyb44csj9ynw3qyzf5fw-vlang-weekly.2023.19/lib/cmd/
vlang> launch_tool tool_args   : '-v' 'build-tools'
vlang> launch_tool should_compile: true
vlang> Compiling vbuild-tools with: "'/nix/store/4m7m7xx2qwvkkyb44csj9ynw3qyzf5fw-vlang-weekly.2023.19/lib
/v' -skip-unused '/nix/store/4m7m7xx2qwvkkyb44csj9ynw3qyzf5fw-vlang-weekly.2023.19/lib/cmd/tools/vbuild-to
vlang> cannot compile `/nix/store/4m7m7xx2qwvkkyb44csj9ynw3qyzf5fw-vlang-weekly.2023.19/lib/cmd/tools/vbui
ld-tools.v`:
vlang> ==================
vlang> tcc: error: library 'atomic' not found
vlang> ...
vlang> ==================
vlang> (Use `v -cg` to print the entire error message)
vlang>
vlang> builder error:
vlang> ==================
vlang>
vlang> This is a compiler bug, please report it using `v bug file.v`.
vlang>
vlang> https://github.com/vlang/v/issues/new/choose
vlang>
vlang> You can also use #help on Discord: https://discord.gg/vlang
vlang>
vlang>
```

**Comment by happysalada** [comment]
@AndersonTorres I needed to disable checks for tinycc static, let me know if that is not ok.

**Comment by AndersonTorres** [comment]
> @AndersonTorres I needed to disable checks for tinycc static, let me know if that is not ok.

Fell free to do as needed.

**Comment by tengkuizdihar** [comment]
Feel free to do as needed, I think it's also intended for us not to use tinycc from the start for vlang when you're compiling it for production use

**Comment by happysalada** [comment]
@tengkuizdihar I could remove the reference to tinycc completely, but the warning bothered me a bit (it's looking for tcc.exe). We can think about removing it totally in the future for sure.

**Pull request merged**
