### PR TITLE
monad-control: 0.3.3.0 -> 1.0.0.1 + reverse dependency upgrades

### PR DESCRIPTION
**Pull request by k0ral**

### CODE REVIEW

**Comment by iElectric** [comment]
@peti

**Comment by peti** [comment]
What effect do these updates have on other packages?

**Comment by k0ral** [comment]
From the changelog:

    Switch the associated data types StT and StM to associated type synonyms.
    
    This is an API breaking change. To fix your MonadTransControl or
    MonadBaseControl instances simply remove the StT or StM constructors
    and deconstructors for your monad transformers or monad.

I have included some impacted packages in this PR, but there may be others (among the [196](http://packdeps.haskellers.com/reverse/monad-control) reverse dependencies as of today), I've only checked those I use on a daily basis. Perhaps I should have used the staging branch ?

**Comment by peti** [comment]
The staging branch is for changes that have been tested, verified, and that are known to work. We use the branch only to batch changes that trigger massive re-builds.

I'm not sure what to do about this PR. My gut felling is that it's going to affect many other packages, but I don't know for sure and I don't have the time to test it either because I'm working on the `haskellngPackages` set instead. I'd rather defer to someone else to make the decision whether to merge or not.

**Comment by peti** [comment]
OK, lets merge this. Feel free to revert if this patch turns out to be a bad idea.

**Pull request merged**
