### PR TITLE
glib: use tested version when `doCheckByDefault` is set

### PR DESCRIPTION
**Pull request by oxij**
Yet another^3 followup to #39464. Fork-off out of #43627 based on comment by @orivej.

### CODE REVIEW

**Review by matthewbauer — APPROVED** [review]

**Comment by oxij** [comment]
rebased. ping

**Comment by matthewbauer** [comment]
@grahamcofborg glib

I just want to make sure the darwin build still works.

**Comment by oxij** [comment]
@GrahamcOfBorg build glib

**Comment by oxij** [comment]
@matthewbauer ping

**Pull request merged**
