### PR TITLE
Plasma 6.0.1

### PR DESCRIPTION
**Pull request by K900**
## Description of changes

https://kde.org/announcements/plasma/6.0.1/

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by K900** [comment]
Result of `nixpkgs-review pr 293690` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>15 packages failed to build:</summary>
  <ul>
    <li>kdePackages.kdev-php</li>
    <li>kdePackages.kdev-php.debug</li>
    <li>kdePackages.kdev-php.dev</li>
    <li>kdePackages.kdev-python</li>
    <li>kdePackages.kdev-python.debug</li>
    <li>kdePackages.kdev-python.dev</li>
    <li>kdePackages.kdevelop</li>
    <li>kdePackages.kdevelop.debug</li>
    <li>kdePackages.kdevelop.dev</li>
    <li>kdePackages.kwayland-integration</li>
    <li>kdePackages.kwayland-integration.debug</li>
    <li>kdePackages.kwayland-integration.dev</li>
    <li>kdePackages.umbrello</li>
    <li>kdePackages.umbrello.debug</li>
    <li>kdePackages.umbrello.dev</li>
  </ul>
</details>
<details>
  <summary>324 packages built:</summary>
  <ul>
    <li>kdePackages.akonadi-calendar</li>
    <li>kdePackages.akonadi-calendar-tools</li>
    <li>kdePackages.akonadi-calendar-tools.debug</li>
    <li>kdePackages.akonadi-calendar-tools.dev</li>
    <li>kdePackages.akonadi-calendar.debug</li>
    <li>kdePackages.akonadi-calendar.dev</li>
    <li>kdePackages.akonadi-import-wizard</li>
    <li>kdePackages.akonadi-import-wizard.debug</li>
    <li>kdePackages.akonadi-import-wizard.dev</li>
    <li>kdePackages.akonadi-search</li>
    <li>kdePackages.akonadi-search.debug</li>
    <li>kdePackages.akonadi-search.dev</li>
    <li>kdePackages.akonadiconsole</li>
    <li>kdePackages.akonadiconsole.debug</li>
    <li>kdePackages.akonadiconsole.dev</li>
    <li>kdePackages.akregator</li>
    <li>kdePackages.akregator.debug</li>
    <li>kdePackages.akregator.dev</li>
    <li>kdePackages.bluedevil</li>
    <li>kdePackages.bluedevil.debug</li>
    <li>kdePackages.bluedevil.dev</li>
    <li>kdePackages.breeze</li>
    <li>kdePackages.breeze-grub</li>
    <li>kdePackages.breeze-grub.debug</li>
    <li>kdePackages.breeze-grub.dev</li>
    <li>kdePackages.breeze-gtk</li>
    <li>kdePackages.breeze-gtk.debug</li>
    <li>kdePackages.breeze-gtk.dev</li>
    <li>kdePackages.breeze-plymouth</li>
    <li>kdePackages.breeze-plymouth.debug</li>
    <li>kdePackages.breeze-plymouth.dev</li>
    <li>kdePackages.breeze.debug</li>
    <li>kdePackages.breeze.dev</li>
    <li>kdePackages.breeze.qt5</li>
    <li>kdePackages.calendarsupport</li>
    <li>kdePackages.calendarsupport.debug</li>
    <li>kdePackages.calendarsupport.dev</li>
    <li>kdePackages.discover</li>
    <li>kdePackages.discover.debug</li>
    <li>kdePackages.discover.dev</li>
    <li>kdePackages.dolphin</li>
    <li>kdePackages.dolphin-plugins</li>
    <li>kdePackages.dolphin-plugins.debug</li>
    <li>kdePackages.dolphin-plugins.dev</li>
    <li>kdePackages.dolphin.debug</li>
    <li>kdePackages.dolphin.dev</li>
    <li>kdePackages.drkonqi</li>
    <li>kdePackages.drkonqi.debug</li>
    <li>kdePackages.drkonqi.dev</li>
    <li>kdePackages.eventviews</li>
    <li>kdePackages.eventviews.debug</li>
    <li>kdePackages.eventviews.dev</li>
    <li>kdePackages.fcitx5-configtool</li>
    <li>kdePackages.fcitx5-with-addons</li>
    <li>kdePackages.flatpak-kcm</li>
    <li>kdePackages.flatpak-kcm.debug</li>
    <li>kdePackages.flatpak-kcm.dev</li>
    <li>kdePackages.grantlee-editor</li>
    <li>kdePackages.grantlee-editor.debug</li>
    <li>kdePackages.grantlee-editor.dev</li>
    <li>kdePackages.gwenview</li>
    <li>kdePackages.gwenview.debug</li>
    <li>kdePackages.gwenview.dev</li>
    <li>kdePackages.incidenceeditor</li>
    <li>kdePackages.incidenceeditor.debug</li>
    <li>kdePackages.incidenceeditor.dev</li>
    <li>kdePackages.kactivitymanagerd</li>
    <li>kdePackages.kactivitymanagerd.debug</li>
    <li>kdePackages.kactivitymanagerd.dev</li>
    <li>kdePackages.kaddressbook</li>
    <li>kdePackages.kaddressbook.debug</li>
    <li>kdePackages.kaddressbook.dev</li>
    <li>kdePackages.kalgebra</li>
    <li>kdePackages.kalgebra.debug</li>
    <li>kdePackages.kalgebra.dev</li>
    <li>kdePackages.kclock</li>
    <li>kdePackages.kclock.debug</li>
    <li>kdePackages.kclock.dev</li>
    <li>kdePackages.kde-cli-tools</li>
    <li>kdePackages.kde-cli-tools.debug</li>
    <li>kdePackages.kde-cli-tools.dev</li>
    <li>kdePackages.kde-gtk-config</li>
    <li>kdePackages.kde-gtk-config.debug</li>
    <li>kdePackages.kde-gtk-config.dev</li>
    <li>kdePackages.kdecoration</li>
    <li>kdePackages.kdecoration.debug</li>
    <li>kdePackages.kdecoration.dev</li>
    <li>kdePackages.kdepim-addons</li>
    <li>kdePackages.kdepim-addons.debug</li>
    <li>kdePackages.kdepim-addons.dev</li>
    <li>kdePackages.kdepim-runtime</li>
    <li>kdePackages.kdepim-runtime.debug</li>
    <li>kdePackages.kdepim-runtime.dev</li>
    <li>kdePackages.kdeplasma-addons</li>
    <li>kdePackages.kdeplasma-addons.debug</li>
    <li>kdePackages.kdeplasma-addons.dev</li>
    <li>kdePackages.kgamma</li>
    <li>kdePackages.kgamma.debug</li>
    <li>kdePackages.kgamma.dev</li>
    <li>kdePackages.kglobalacceld</li>
    <li>kdePackages.kglobalacceld.debug</li>
    <li>kdePackages.kglobalacceld.dev</li>
    <li>kdePackages.kinfocenter</li>
    <li>kdePackages.kinfocenter.debug</li>
    <li>kdePackages.kinfocenter.dev</li>
    <li>kdePackages.kio-extras</li>
    <li>kdePackages.kio-extras.debug</li>
    <li>kdePackages.kio-extras.dev</li>
    <li>kdePackages.kmail</li>
    <li>kdePackages.kmail.debug</li>
    <li>kdePackages.kmail.dev</li>
    <li>kdePackages.kmenuedit</li>
    <li>kdePackages.kmenuedit.debug</li>
    <li>kdePackages.kmenuedit.dev</li>
    <li>kdePackages.knights</li>
    <li>kdePackages.knights.debug</li>
    <li>kdePackages.knights.dev</li>
    <li>kdePackages.knotes</li>
    <li>kdePackages.knotes.debug</li>
    <li>kdePackages.knotes.dev</li>
    <li>kdePackages.konqueror</li>
    <li>kdePackages.konqueror.debug</li>
    <li>kdePackages.konqueror.dev</li>
    <li>kdePackages.kontact</li>
    <li>kdePackages.kontact.debug</li>
    <li>kdePackages.kontact.dev</li>
    <li>kdePackages.korganizer</li>
    <li>kdePackages.korganizer.debug</li>
    <li>kdePackages.korganizer.dev</li>
    <li>kdePackages.kpipewire</li>
    <li>kdePackages.kpipewire.debug</li>
    <li>kdePackages.kpipewire.dev</li>
    <li>kdePackages.krdc</li>
    <li>kdePackages.krdc.debug</li>
    <li>kdePackages.krdc.dev</li>
    <li>kdePackages.krfb</li>
    <li>kdePackages.krfb.debug</li>
    <li>kdePackages.krfb.dev</li>
    <li>kdePackages.krunner</li>
    <li>kdePackages.krunner.debug</li>
    <li>kdePackages.krunner.dev</li>
    <li>kdePackages.kscreen</li>
    <li>kdePackages.kscreen.debug</li>
    <li>kdePackages.kscreen.dev</li>
    <li>kdePackages.kscreenlocker</li>
    <li>kdePackages.kscreenlocker.debug</li>
    <li>kdePackages.kscreenlocker.dev</li>
    <li>kdePackages.ksshaskpass</li>
    <li>kdePackages.ksshaskpass.debug</li>
    <li>kdePackages.ksshaskpass.dev</li>
    <li>kdePackages.ksystemstats</li>
    <li>kdePackages.ksystemstats.debug</li>
    <li>kdePackages.ksystemstats.dev</li>
    <li>kdePackages.kwallet-pam</li>
    <li>kdePackages.kwallet-pam.debug</li>
    <li>kdePackages.kwallet-pam.dev</li>
    <li>kdePackages.kwayland</li>
    <li>kdePackages.kwayland.debug</li>
    <li>kdePackages.kwayland.dev</li>
    <li>kdePackages.kweather</li>
    <li>kdePackages.kweather.debug</li>
    <li>kdePackages.kweather.dev</li>
    <li>kdePackages.kwin</li>
    <li>kdePackages.kwin.debug</li>
    <li>kdePackages.kwin.dev</li>
    <li>kdePackages.kwrited</li>
    <li>kdePackages.kwrited.debug</li>
    <li>kdePackages.kwrited.dev</li>
    <li>kdePackages.layer-shell-qt</li>
    <li>kdePackages.layer-shell-qt.debug</li>
    <li>kdePackages.layer-shell-qt.dev</li>
    <li>kdePackages.libgravatar</li>
    <li>kdePackages.libgravatar.debug</li>
    <li>kdePackages.libgravatar.dev</li>
    <li>kdePackages.libkscreen</li>
    <li>kdePackages.libkscreen.debug</li>
    <li>kdePackages.libkscreen.dev</li>
    <li>kdePackages.libksieve</li>
    <li>kdePackages.libksieve.debug</li>
    <li>kdePackages.libksieve.dev</li>
    <li>kdePackages.libksysguard</li>
    <li>kdePackages.libksysguard.debug</li>
    <li>kdePackages.libksysguard.dev</li>
    <li>kdePackages.libplasma</li>
    <li>kdePackages.libplasma.debug</li>
    <li>kdePackages.libplasma.dev</li>
    <li>kdePackages.mailcommon</li>
    <li>kdePackages.mailcommon.debug</li>
    <li>kdePackages.mailcommon.dev</li>
    <li>kdePackages.mailimporter</li>
    <li>kdePackages.mailimporter.debug</li>
    <li>kdePackages.mailimporter.dev</li>
    <li>kdePackages.mbox-importer</li>
    <li>kdePackages.mbox-importer.debug</li>
    <li>kdePackages.mbox-importer.dev</li>
    <li>kdePackages.merkuro</li>
    <li>kdePackages.merkuro.debug</li>
    <li>kdePackages.merkuro.dev</li>
    <li>kdePackages.messagelib</li>
    <li>kdePackages.messagelib.debug</li>
    <li>kdePackages.messagelib.dev</li>
    <li>kdePackages.milou</li>
    <li>kdePackages.milou.debug</li>
    <li>kdePackages.milou.dev</li>
    <li>kdePackages.ocean-sound-theme</li>
    <li>kdePackages.ocean-sound-theme.debug</li>
    <li>kdePackages.ocean-sound-theme.dev</li>
    <li>kdePackages.okular</li>
    <li>kdePackages.okular.debug</li>
    <li>kdePackages.okular.dev</li>
    <li>kdePackages.oxygen</li>
    <li>kdePackages.oxygen-sounds</li>
    <li>kdePackages.oxygen-sounds.debug</li>
    <li>kdePackages.oxygen-sounds.dev</li>
    <li>kdePackages.oxygen.debug</li>
    <li>kdePackages.oxygen.dev</li>
    <li>kdePackages.oxygen.qt5</li>
    <li>kdePackages.pim-data-exporter</li>
    <li>kdePackages.pim-data-exporter.debug</li>
    <li>kdePackages.pim-data-exporter.dev</li>
    <li>kdePackages.pim-sieve-editor</li>
    <li>kdePackages.pim-sieve-editor.debug</li>
    <li>kdePackages.pim-sieve-editor.dev</li>
    <li>kdePackages.pimcommon</li>
    <li>kdePackages.pimcommon.debug</li>
    <li>kdePackages.pimcommon.dev</li>
    <li>kdePackages.plasma-activities</li>
    <li>kdePackages.plasma-activities-stats</li>
    <li>kdePackages.plasma-activities-stats.debug</li>
    <li>kdePackages.plasma-activities-stats.dev</li>
    <li>kdePackages.plasma-activities.debug</li>
    <li>kdePackages.plasma-activities.dev</li>
    <li>kdePackages.plasma-browser-integration</li>
    <li>kdePackages.plasma-browser-integration.debug</li>
    <li>kdePackages.plasma-browser-integration.dev</li>
    <li>kdePackages.plasma-desktop</li>
    <li>kdePackages.plasma-desktop.debug</li>
    <li>kdePackages.plasma-desktop.dev</li>
    <li>kdePackages.plasma-disks</li>
    <li>kdePackages.plasma-disks.debug</li>
    <li>kdePackages.plasma-disks.dev</li>
    <li>kdePackages.plasma-firewall</li>
    <li>kdePackages.plasma-firewall.debug</li>
    <li>kdePackages.plasma-firewall.dev</li>
    <li>kdePackages.plasma-integration</li>
    <li>kdePackages.plasma-integration.debug</li>
    <li>kdePackages.plasma-integration.dev</li>
    <li>kdePackages.plasma-integration.qt5</li>
    <li>kdePackages.plasma-mobile</li>
    <li>kdePackages.plasma-mobile.debug</li>
    <li>kdePackages.plasma-mobile.dev</li>
    <li>kdePackages.plasma-nano</li>
    <li>kdePackages.plasma-nano.debug</li>
    <li>kdePackages.plasma-nano.dev</li>
    <li>kdePackages.plasma-nm</li>
    <li>kdePackages.plasma-nm.debug</li>
    <li>kdePackages.plasma-nm.dev</li>
    <li>kdePackages.plasma-pa</li>
    <li>kdePackages.plasma-pa.debug</li>
    <li>kdePackages.plasma-pa.dev</li>
    <li>kdePackages.plasma-sdk</li>
    <li>kdePackages.plasma-sdk.debug</li>
    <li>kdePackages.plasma-sdk.dev</li>
    <li>kdePackages.plasma-systemmonitor</li>
    <li>kdePackages.plasma-systemmonitor.debug</li>
    <li>kdePackages.plasma-systemmonitor.dev</li>
    <li>kdePackages.plasma-thunderbolt</li>
    <li>kdePackages.plasma-thunderbolt.debug</li>
    <li>kdePackages.plasma-thunderbolt.dev</li>
    <li>kdePackages.plasma-vault</li>
    <li>kdePackages.plasma-vault.debug</li>
    <li>kdePackages.plasma-vault.dev</li>
    <li>kdePackages.plasma-welcome</li>
    <li>kdePackages.plasma-welcome.debug</li>
    <li>kdePackages.plasma-welcome.dev</li>
    <li>kdePackages.plasma-workspace</li>
    <li>kdePackages.plasma-workspace-wallpapers</li>
    <li>kdePackages.plasma-workspace-wallpapers.debug</li>
    <li>kdePackages.plasma-workspace-wallpapers.dev</li>
    <li>kdePackages.plasma-workspace.debug</li>
    <li>kdePackages.plasma-workspace.dev</li>
    <li>kdePackages.plasma5support</li>
    <li>kdePackages.plasma5support.debug</li>
    <li>kdePackages.plasma5support.dev</li>
    <li>kdePackages.plymouth-kcm</li>
    <li>kdePackages.plymouth-kcm.debug</li>
    <li>kdePackages.plymouth-kcm.dev</li>
    <li>kdePackages.polkit-kde-agent-1</li>
    <li>kdePackages.polkit-kde-agent-1.debug</li>
    <li>kdePackages.polkit-kde-agent-1.dev</li>
    <li>kdePackages.powerdevil</li>
    <li>kdePackages.powerdevil.debug</li>
    <li>kdePackages.powerdevil.dev</li>
    <li>kdePackages.print-manager</li>
    <li>kdePackages.print-manager.debug</li>
    <li>kdePackages.print-manager.dev</li>
    <li>kdePackages.qqc2-breeze-style</li>
    <li>kdePackages.qqc2-breeze-style.debug</li>
    <li>kdePackages.qqc2-breeze-style.dev</li>
    <li>kdePackages.sddm-kcm</li>
    <li>kdePackages.sddm-kcm.debug</li>
    <li>kdePackages.sddm-kcm.dev</li>
    <li>kdePackages.spectacle</li>
    <li>kdePackages.spectacle.debug</li>
    <li>kdePackages.spectacle.dev</li>
    <li>kdePackages.sweeper</li>
    <li>kdePackages.sweeper.debug</li>
    <li>kdePackages.sweeper.dev</li>
    <li>kdePackages.systemsettings</li>
    <li>kdePackages.systemsettings.debug</li>
    <li>kdePackages.systemsettings.dev</li>
    <li>kdePackages.wacomtablet</li>
    <li>kdePackages.wacomtablet.debug</li>
    <li>kdePackages.wacomtablet.dev</li>
    <li>kdePackages.xdg-desktop-portal-kde</li>
    <li>kdePackages.xdg-desktop-portal-kde.debug</li>
    <li>kdePackages.xdg-desktop-portal-kde.dev</li>
    <li>kdePackages.yakuake</li>
    <li>kdePackages.yakuake.debug</li>
    <li>kdePackages.yakuake.dev</li>
    <li>kdePackages.zanshin</li>
    <li>kdePackages.zanshin.debug</li>
    <li>kdePackages.zanshin.dev</li>
    <li>syncthingtray-qt6</li>
  </ul>
</details>

**Comment by ilya-fedin** [comment]
> 15 packages failed to build:
>     * kdePackages.kwayland-integration

Is that really ok? This package contains plugins with Wayland backends for other libraries such as KWindowSystem

**Comment by ilya-fedin** [comment]
Ah, I thought kdePackages has Qt 6 packages only

**Comment by K900** [comment]
The scripts pick up everything that's still released as part of the big package sets, even stuff that's not ported yet. We can probably filter it out if we really wanted to, but I've just been manually setting `meta.broken` where appropriate.

**Pull request merged**
