### PR TITLE
iterm2: 3.5.4 -> 3.5.10

### PR DESCRIPTION
**Pull request by rwxg**
## Things done

- Built on platform(s)
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by NetaliDev** [comment]
Please change the target branch of the PR to `master`. You are currently targeting a release-branch.

**Comment by rwxg** [comment]
> Please change the target branch of the PR to `master`. You are currently targeting a release-branch.

I based my change off of the `24.11-darwin` release branch, changing the target to `master` added all commits in the darwin-branch to this PR as you see. This doesn't seem right, please advise - should I have done something different since this is a darwin-specific package?

**Comment by NetaliDev** [comment]
Just rebase your branch with the current master branch. This should do the trick.

**Comment by NetaliDev** [comment]
I have rebased the PR for you :)

**Comment by rwxg** [comment]
> I have rebased the PR for you :)

Ah, crud! I was caught up in something & just did it myself before seeing your update. Hope that doesn't break anything, seemed fine on my machine. Thanks a lot for the help, in any case!

**Comment by NetaliDev** [comment]
You have only re-triggered the CI, so everything is okay :)

Now we have to wait for the CI (may take a day or even longer) and the CI will then add the maintainers of iterm2 as reviewers and if they have nothing against your update, we can merge it :)

**Comment by NetaliDev** [comment]
Ah okay, I just saw that hydra builds are disabled for this package and therefore the maintainers weren't added as reviewers, so let's do this manually: @steinybot @tricktron

**Pull request merged**
