### PR TITLE
dbeaver: 6.1.4 -> 6.1.5

### PR DESCRIPTION
**Pull request by jojosch**
###### Motivation for this change
https://dbeaver.io/2019/08/18/dbeaver-6-1-5/

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
```
/nix/store/6qdvd3k3gcwk6q4nlyf47mfv81vwrh46-dbeaver-ce-6.1.4	  984310544
/nix/store/y2cm10nawnxr4v3fsc0bn0w4wpf8rr5z-dbeaver-ce-6.1.5	  980274352
```
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @samueldr

### CODE REVIEW

**Comment by samueldr** [comment]
Hi, thanks for the update!

@jojosch do you want to take up maintainership of the `dbeaver` package? I stopped using it since my employment situation changed. I see you've lately been keeping it up to date, which is great :+1:.

If you desire so, you can add yourself to the [meta.maintainers](https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes) attribute (after adding yourself to the [`maintainers-list`](https://github.com/NixOS/nixpkgs/blob/master/maintainers/maintainer-list.nix)). You can also remove my name from the list if add yourself. I will wait for an answer to this before merging.

If you have any questions, don't hesitate to ask.

**Comment by jojosch** [comment]
> If you desire so, you can add yourself to the [meta.maintainers](https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes) attribute (after adding yourself to the [`maintainers-list`](https://github.com/NixOS/nixpkgs/blob/master/maintainers/maintainer-list.nix)). You can also remove my name from the list if add yourself. I will wait for an answer to this before merging.

I opened a pull request (#68012) adding myself as a maintainer - will push an update here after the other pull request is merged.

**Review by aanderse — APPROVED** [review]
Tested connecting to a `mssql` database successfully. LGTM :+1:

**Comment by srhb** [comment]
Would have been fine to add the maintainers commit to this PR as well (for reference to people of the future) -- but merged! :)

**Review by samueldr — APPROVED** [review]

**Pull request merged**
