### PR TITLE
dotnetCorePackages.*_5*: 5.0.0 -> 5.0.6

### LINKED ISSUE #125735: dotnetCorePackages.net_5_0 is out of date, and out of sync with sdk_5_0
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)
  - #112582 is also out of date

###### Project name
`nix search` name: (I'm not sure how to check this on a system with flakes)

current version: 5.0.0 / 5.0.3
desired version: 5.0.6

###### Additional note
I have a PR open for packaging netcoredbg (#103940). Building netcoredbg requires knowing the version of the runtime bundled with the SDK. Currently, the `net_5_0` package and `sdk_5_0` package are out of sync, making this difficult. The easiest solution would be to make sure to keep these in sync, but another option might be to add something like `passthrough.runtimeVersion`.

###### Notify maintainers

maintainers: @kuznero

###### Note for maintainers

Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
closes: https://github.com/NixOS/nixpkgs/issues/125735
closes: https://github.com/NixOS/nixpkgs/pull/112582

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](./CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 125736` at 30a5a5af run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/c7a34ce5c89f1bc7f38e32cdc1619579">dotnetCorePackages.net_5_0</a></li>
    <li><a href="https://gist.github.com/0c8406f1e8eadca92fb5339688ddb0a6">fsharp41</a></li>
    <li><a href="https://gist.github.com/f4af96a9ceba05c536d33ca6fb6f0783">msbuild</a></li>
    <li><a href="https://gist.github.com/ad5eedf49eca4ca423f9e28b19c4c4d2">omnisharp-roslyn</a></li>
    <li><a href="https://gist.github.com/3456b652f85c5ec38feaeae23d3c0365">opentabletdriver</a></li>
    <li><a href="https://gist.github.com/14cc3e4d818a2e86cab3d53c92e29c30">osu-lazer</a></li>
    <li><a href="https://gist.github.com/41ff52c67ccf29c942ca037898fbe88b">roslyn</a></li>
    <li><a href="https://gist.github.com/934a45d0b17327e12d22c628acc58781">ryujinx</a></li>
  </ul>
</details>
<details>
  <summary>4 packages built successfully:</summary>
  <ul>
    <li>dotnet-sdk_5 (dotnetCorePackages.sdk_5_0)</li>
    <li>dotnetCorePackages.aspnetcore_5_0</li>
    <li>jellyfin</li>
    <li>jetbrains.rider</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Review by oxalica — COMMENTED** [review]
`osu-lazer` works. Maybe also need to re-generate deps of `roslyn`?

**Comment by IvarWithoutBones** [comment]
Could the deps of `Ryujinx` be regenerated as well? That should fix the current build failure.

**Comment by jonringer** [comment]
Even after regenerating them, they still seem to fail

**Comment by oxalica** [comment]
@jonringer Do you use the updated dotnet SDK to regenerate it? The update script will pick it from your system by default.

**Comment by jonringer** [comment]
> @jonringer Do you use the updated dotnet SDK to regenerate it? The update script will pick it from your system by default.

I believe I did `NIX_PATH=nixpkgs=$PWD` but I'll try again today

**Comment by ratsclub** [comment]
I'm waiting this PR to update the `fsharp` package to the latest release. As far as I know it depends on [dotnet 5.0.300](https://github.com/dotnet/fsharp/blob/200af477025bc397c3322cd0dad26616aff9f34f/global.json#L7) so I'm not sure if the package `fsharp41` will continue to work.

**Comment by jonringer** [comment]
Maybe as a compromise, I can merged this to `staging-next`, and we can just stabilize there?

**Comment by jonringer** [comment]
current status:
```
8 packages failed to build:
fsharp41 github-runner msbuild omnisharp-roslyn python-language-server roslyn ryujinx wasabibackend

14 packages built:
btcpayserver dotnet-sdk_3 dotnet-sdk_5 dotnetCorePackages.aspnetcore_3_1 dotnetCorePackages.aspnetcore_5_0 dotnetCorePackages.net_5_0 dotnetCorePackages.netcore_3_1 jellyfin jetbrains.rider nbxplorer opentabletdriver osu-lazer radarr vscode-extensions.ms-vsliveshare.vsliveshare
```

**Comment by ratsclub** [comment]
About fsharp41: https://github.com/NixOS/nixpkgs/pull/126262

**Comment by avdv** [comment]
Also note https://github.com/NixOS/nixpkgs/pull/136329  - maybe this fixes the build for omnisharp-roslyn on top of this?

**Comment by avdv** [comment]
I have locally upgraded dotnet 5 to 5.0.9 / 5.0.400.

Current status:
```
6 packages failed to build:
discordchatexporter-cli github-runner osu-lazer python-language-server ryujinx wasabibackend

19 packages built:
ArchiSteamFarm azure-functions-core-tools btcpayserver depotdownloader dotnet-sdk_3 dotnet-sdk_5 dotnetCorePackages.aspnetcore_3_1 dotnetCorePackages.aspnetcore_5_0 dotnetCorePackages.net_5_0 dotnetCorePackages.netcore_3_1 jellyfin jetbrains.rider msbuild nbxplorer omnisharp-roslyn opentabletdriver radarr roslyn vscode-extensions.ms-vsliveshare.vsliveshare
```

**Comment by avdv** [comment]
I also updated dotnet 3.1* to the latest version.

Current status:
```
1 package failed to build:
github-runner

24 packages built:
ArchiSteamFarm azure-functions-core-tools btcpayserver depotdownloader discordchatexporter-cli dotnet-sdk_3 dotnet-sdk_5 dotnetCorePackages.aspnetcore_3_1 dotnetCorePackages.aspnetcore_5_0 dotnetCorePackages.net_5_0 dotnetCorePackages.netcore_3_1 jellyfin jetbrains.rider msbuild nbxplorer omnisharp-roslyn opentabletdriver osu-lazer python-language-server radarr roslyn ryujinx vscode-extensions.ms-vsliveshare.vsliveshare wasabibackend
```
But the github-runner package builds successfully in isolation, only failed with a test failure within nixpkgs-review...


@jonringer my updated branch is here: https://github.com/avdv/nixpkgs/tree/bump-dotnet Feel free to incorporate it into your PR, or should I just open a new one?

**Comment by avdv** [comment]
Seems like I can do dotnet 5.0.9 -> 5.0.10 now: https://github.com/dotnet/core/blob/main/release-notes/5.0/5.0.10/5.0.10.md

**Comment by avdv** [comment]
I did upgrade to 5.0.10 too. New branch is here: https://github.com/avdv/nixpkgs/tree/bump-dotnet_take-2

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>25 packages built:</summary>
  <ul>
    <li>ArchiSteamFarm</li>
    <li>azure-functions-core-tools</li>
    <li>btcpayserver</li>
    <li>depotdownloader</li>
    <li>discordchatexporter-cli</li>
    <li>dotnet-sdk_3</li>
    <li>dotnet-sdk_5</li>
    <li>dotnetCorePackages.aspnetcore_3_1</li>
    <li>dotnetCorePackages.aspnetcore_5_0</li>
    <li>dotnetCorePackages.net_5_0</li>
    <li>dotnetCorePackages.netcore_3_1</li>
    <li>github-runner</li>
    <li>jellyfin</li>
    <li>jetbrains.rider</li>
    <li>msbuild</li>
    <li>nbxplorer</li>
    <li>omnisharp-roslyn</li>
    <li>opentabletdriver</li>
    <li>osu-lazer</li>
    <li>python-language-server</li>
    <li>radarr</li>
    <li>roslyn</li>
    <li>ryujinx</li>
    <li>vscode-extensions.ms-vsliveshare.vsliveshare</li>
    <li>wasabibackend</li>
  </ul>
</details>

**Comment by avdv** [comment]
FYI, I have just created a new PR with my changes: #138296

**Comment by jonringer** [comment]
#138296 was merged

**Pull request closed without merging**
