### PR TITLE
mesa: 23.3.1 -> 23.3.2

### PR DESCRIPTION
**Pull request by K900**
i686 patch got merged

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
  - [x] i686-linux
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by jansol — APPROVED** [review]

**Comment by trofi** [comment]
Bisect says something regressed in this release and `gjs.tests` now fails with thie following device init failure:

```
$ nix build --no-link -f. gjs.tests --keep-going -j3 -L
...
vm-test-run-gjs> machine # Stack trace of thread 1176:
vm-test-run-gjs> machine # #0  0x00007f69e858102c __pthread_kill_implementation (libc.so.6 + 0x8d02c)
vm-test-run-gjs> machine # #1  0x00007f69e8531e06 raise (libc.so.6 + 0x3de06)
vm-test-run-gjs> machine # #2  0x00007f69e851a8f5 abort (libc.so.6 + 0x268f5)
vm-test-run-gjs> machine # #3  0x00000000005b7eea OsAbort (Xorg + 0x1b7eea)
vm-test-run-gjs> machine # #4  0x00000000005bd5a3 AbortServer (Xorg + 0x1bd5a3)
vm-test-run-gjs> machine # #5  0x00000000005be4a5 FatalError (Xorg + 0x1be4a5)
vm-test-run-gjs> machine # #6  0x00000000005b5415 OsSigHandler (Xorg + 0x1b5415)
vm-test-run-gjs> machine # #7  0x00007f69e8531eb0 __restore_rt (libc.so.6 + 0x3deb0)
vm-test-run-gjs> machine # #8  0x00007f69e63336e0 llvmpipe_screen_get_fd (kms_swrast_dri.so + 0x70b6e0)
vm-test-run-gjs> machine # #9  0x00007f69e68a8884 u_pipe_screen_get_param_defaults (kms_swrast_dri.so + 0xc80884)
vm-test-run-gjs> machine # #10 0x00007f69e5cdcb50 dri2_init_screen_extensions (kms_swrast_dri.so + 0xb4b50)
vm-test-run-gjs> machine # #11 0x00007f69e5cdcf70 dri_swrast_kms_init_screen (kms_swrast_dri.so + 0xb4f70)
vm-test-run-gjs> machine # #12 0x00007f69e5ce5094 driCreateNewScreen2 (kms_swrast_dri.so + 0xbd094)
vm-test-run-gjs> machine # #13 0x00007f69e7ed6cb0 dri_screen_create_for_driver (libgbm.so.1 + 0x4cb0)
vm-test-run-gjs> machine # #14 0x00007f69e7ed7210 dri_screen_create_sw (libgbm.so.1 + 0x5210)
vm-test-run-gjs> machine # #15 0x00007f69e7ed73db dri_device_create (libgbm.so.1 + 0x53db)
vm-test-run-gjs> machine # #16 0x00007f69e7ed577c find_backend (libgbm.so.1 + 0x377c)
vm-test-run-gjs> machine # #17 0x00007f69e7ed58b4 gbm_create_device (libgbm.so.1 + 0x38b4)
vm-test-run-gjs> machine # #18 0x00007f69e7eec4d1 glamor_egl_init (libglamoregl.so + 0x94d1)
vm-test-run-gjs> machine # #19 0x00007f69e7f2677a PreInit (modesetting_drv.so + 0xc77a)
vm-test-run-gjs> machine # #20 0x0000000000488916 InitOutput (Xorg + 0x88916)
vm-test-run-gjs> machine # #21 0x00000000004495b0 dix_main (Xorg + 0x495b0)
vm-test-run-gjs> machine # #22 0x00007f69e851c0ce __libc_start_call_main (libc.so.6 + 0x280ce)
vm-test-run-gjs> machine # #23 0x00007f69e851c189 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x28189)
vm-test-run-gjs> machine # #24 0x0000000000432825 _start (Xorg + 0x32825)
vm-test-run-gjs> machine # ELF object binary architecture: AMD x86-64
```

Reverting be9351cb7cbd712c20d35282226288f7321809b8 `mesa: 23.3.1 -> 23.3.2` restores the test.

**Comment by vcunat** [comment]
The .3 bump of mesa didn't fix this?

**Comment by trofi** [comment]
Ah, maybe I started from a too old state. I'll retest against the `staging`.

**Comment by trofi** [comment]
> The .3 bump of mesa didn't fix this?

`staging` with `mesa-23.3.3` works fine. Thank you!

**Comment by vcunat** [comment]
To be clear, 23.3.3 is in `nixos-unstable` channel already.

**Pull request merged**
