### PR TITLE
tiled: 1.8.4 -> 1.9.1

### PR DESCRIPTION
**Pull request by mendsec**
I've put the sha256 results from command:
nix-prefetch-url --unpack https://github.com/mapeditor/tiled/archive/74bee555225cdf98a408966ad657bc5c8cadb8ab.zip

And meeting the contribution rules.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
The package does not build.

**Comment by fabiomen10** [comment]
> The package does not build.

How to re-rebuild? Making a new commit?

**Comment by SuperSandro2000** [comment]
Building the package another time will not change something about the following build error:


```
building '/nix/store/vr30rz30xvmrcm24jdkd798qwqdrkdyw-source.drv'...
trying https://github.com/bjorn/tiled/archive/v1.9.1.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 16.3M    0 16.3M    0     0  11.0M      0 --:--:--  0:00:01 --:--:-- 14.8M
unpacking source archive /build/v1.9.1.tar.gz
building '/nix/store/bkv5chxpmp8magybl120djx4lk9rl4wh-tiled-1.9.1.drv'...
qmakePrePhase
qtPreHook
unpacking sources
unpacking source archive /nix/store/ynhc9a4g9p15dlw1abhnwm6p5qccx86f-source
source root is source
patching sources
configuring
QMAKEPATH=/nix/store/gg6b5gfmyhqk5l08bjswrhijzr1bfa1p-qtbase-5.15.5-dev:/nix/store/mm8xz9fqjamba7pjvlk7z9rpib7v4x7a-qtwayland-5.15.5-dev:/nix/store/l2v8rq9282bhpfd8d272mvgs8gdzggj5-qtdeclarative-5.15.5-dev:/nix/store/07k3q3mb98h8ckwvrzf4si4qxzl1gw14-qtsvg-5.15.5-dev:/nix/store/885jxk7jglx7pnikyl239lbnlm3c1ps5-qttools-5.15.5-dev
qmake PREFIX=/nix/store/cbl86s3nxgmp63nj5zgmfw43if9caz60-tiled-1.9.1 NIX_OUTPUT_OUT=/nix/store/cbl86s3nxgmp63nj5zgmfw43if9caz60-tiled-1.9.1 NIX_OUTPUT_DEV=/nix/store/cbl86s3nxgmp63nj5zgmfw43if9caz60-tiled-1.9.1 NIX_OUTPUT_BIN=/nix/store/cbl86s3nxgmp63nj5zgmfw43if9caz60-tiled-1.9.1 NIX_OUTPUT_DOC=/nix/store/cbl86s3nxgmp63nj5zgmfw43if9caz60-tiled-1.9.1/share/doc/qt-5.15.5 NIX_OUTPUT_QML=/nix/store/cbl86s3nxgmp63nj5zgmfw43if9caz60-tiled-1.9.1/lib/qt-5.15.5/qml NIX_OUTPUT_PLUGIN=/nix/store/cbl86s3nxgmp63nj5zgmfw43if9caz60-tiled-1.9.1/lib/qt-5.15.5/plugins CONFIG+=release QMAKE_LRELEASE=/nix/store/885jxk7jglx7pnikyl239lbnlm3c1ps5-qttools-5.15.5-dev/bin/lrelease
Usage: qmake [mode] [options] [files]
QMake has two modes, one mode for generating project files based on
some heuristics, and the other for generating makefiles. Normally you
shouldn't need to specify a mode, as makefile generation is the default
mode for qmake, but you may use this to test qmake on an existing project
Mode:
  -project       Put qmake into project file generation mode
                 In this mode qmake interprets [files] as files to
                 be added to the .pro file. By default, all files with
                 known source extensions are added.
                 Note: The created .pro file probably will 
                 need to be edited. For example add the QT variable to 
                 specify what modules are required.
  -makefile      Put qmake into makefile generation mode (default)
                 In this mode qmake interprets files as project files to
                 be processed, if skipped qmake will try to find a project
                 file in your current working directory
Warnings Options:
  -Wnone         Turn off all warnings; specific ones may be re-enabled by
                 later -W options
  -Wall          Turn on all warnings
  -Wparser       Turn on parser warnings
  -Wlogic        Turn on logic warnings (on by default)
  -Wdeprecated   Turn on deprecation warnings (on by default)
Options:
   * You can place any variable assignment in options and it will be *
   * processed as if it was in [files]. These assignments will be    *
   * processed before [files] by default.                            *
  -o file        Write output to file
  -d             Increase debug level
  -t templ       Overrides TEMPLATE as templ
  -tp prefix     Overrides TEMPLATE so that prefix is prefixed into the value
  -help          This help
  -v             Version information
  -early         All subsequent variable assignments will be
                 parsed right before default_pre.prf
  -before        All subsequent variable assignments will be
                 parsed right before [files] (the default)
  -after         All subsequent variable assignments will be
                 parsed after [files]
  -late          All subsequent variable assignments will be
                 parsed right after default_post.prf
  -norecursive   Don't do a recursive search
  -recursive     Do a recursive search
  -set <prop> <value> Set persistent property
  -unset <prop>  Unset persistent property
  -query <prop>  Query persistent property. Show all if <prop> is empty.
  -qtconf file   Use file instead of looking for qt.conf
  -cache file    Use file as cache           [makefile mode only]
  -spec spec     Use spec as QMAKESPEC       [makefile mode only]
  -nocache       Don't use a cache file      [makefile mode only]
  -nodepend      Don't generate dependencies [makefile mode only]
  -nomoc         Don't generate moc targets  [makefile mode only]
  -nopwd         Don't look for files in pwd [project mode only]
error: builder for '/nix/store/bkv5chxpmp8magybl120djx4lk9rl4wh-tiled-1.9.1.drv' failed with exit code 1;
```

**Comment by onny** [comment]
Result of `nixpkgs-review pr 188687` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>tiled</li>
  </ul>
</details>

**Comment by bjorn** [comment]
Could be closed since it was superseded by #188839.

**Pull request closed without merging**
