### PR TITLE
vscodeExtensions.ms-vscode-remote.remote-ssh: 0.48.0 -> 0.50.0

### PR DESCRIPTION
**Pull request by Mic92**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by veprbl** [comment]
@GrahamcOfBorg eval

**Comment by tbenst** [comment]
Unfortunately, this does not function for me, and I can see no obvious reason why. In VScode, extension is not listed under "Enabled," but if I search for it I do see an option to uninstall, so it's detected on some level. remote-ssh is not available as a command.

I sadly don't have bandwidth to investigate right now

**Review by jonringer — APPROVED** [review]
LGTM
builds fine

```
[nix-shell:/home/jon/.cache/nixpkgs-review/pr-82487]$ nix-build ./nixpkgs/ -A vscode-extensions.ms-vscode-remote
these derivations will be built:
  /nix/store/0amya2q2zsa5vqp70n6aq72nrwp5apmw-ms-vscode-remote-remote-ssh.zip.drv
  /nix/store/9d7ph10a0alxafcwwzjikkjhkvbmc74w-vscode-extension-ms-vscode-remote-remote-ssh-0.50.0.drv
building '/nix/store/0amya2q2zsa5vqp70n6aq72nrwp5apmw-ms-vscode-remote-remote-ssh.zip.drv'...

trying https://ms-vscode-remote.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode-remote/extension/remote-ssh/0.50.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  671k  100  671k    0     0   201k      0  0:00:03  0:00:03 --:--:--  201k
building '/nix/store/9d7ph10a0alxafcwwzjikkjhkvbmc74w-vscode-extension-ms-vscode-remote-remote-ssh-0.50.0.drv'...
unpacking sources
unpacking source archive /nix/store/nc1z3z34avqwwyg31lky9q6pil70c8l8-ms-vscode-remote-remote-ssh.zip
source root is extension
setting SOURCE_DATE_EPOCH to timestamp 1583788674 of file extension/README.md
patching sources
configuring
building
installing
post-installation fixup
patching script interpreter paths in /nix/store/20acnnrq02kdfbzy0a17lvq8l96zm6g5-vscode-extension-ms-vscode-remote-remote-ssh-0.50.0
/nix/store/20acnnrq02kdfbzy0a17lvq8l96zm6g5-vscode-extension-ms-vscode-remote-remote-ssh-0.50.0/ms-vscode-remote.remote-ssh/out/utils/terminateProcess.sh: interpreter directive changed from "/bin/bash" to "/nix/store/z4ajipns0l1s8b2lrgpy6nng4cys7h99-bash-4.4-p23/bin/bash"
/nix/store/20acnnrq02kdfbzy0a17lvq8l96zm6g5-vscode-extension-ms-vscode-remote-remote-ssh-0.50.0/ms-vscode-remote.remote-ssh/out/local-server/askpass.sh: interpreter directive changed from "/bin/sh" to "/nix/store/z4ajipns0l1s8b2lrgpy6nng4cys7h99-bash-4.4-p23/bin/sh"
checking for references to /build/ in /nix/store/20acnnrq02kdfbzy0a17lvq8l96zm6g5-vscode-extension-ms-vscode-remote-remote-ssh-0.50.0...
/nix/store/20acnnrq02kdfbzy0a17lvq8l96zm6g5-vscode-extension-ms-vscode-remote-remote-ssh-0.50.0
```

**Comment by tbenst** [comment]
@jonringer did you see my comment? Even though this builds, when I tested it was not functional. Unless someone can comment that they functionally tested that this works, can you please revert?

**Comment by jonringer** [comment]
looks like all vscode extensions are broken on master due to the a change in makeDesktopItem

**Comment by jonringer** [comment]
```
[21:42:11] jon@jon-desktop /home/jon/projects/nixpkgs (master)
$ nix-shell -p "with import ./. {}; vscode-with-extensions.override { vscodeExtensions = with vscode-extensions; [ ms-vscode-remote.remote-ssh ];}"
these derivations will be built:
  /nix/store/dcrmlf7vax4ksy7lgwlacqmbbhgiam9a-code-url-handler.desktop.drv
  /nix/store/ixbcwj7mjx4cqwzip4f885qihz23bi7r-code.desktop.drv
  /nix/store/nxrjisrdafnrf7j3psq3fqxflyr63vnv-VSCode_1.43.0_linux-x64.tar.gz.drv
  /nix/store/8qjcw0mrq6byqa5cyhvlf5vj9l5n1ag3-vscode-1.43.0.drv
  /nix/store/r4lhsfphyhwsvdwwwh7ilk7p8sr2rfi0-vscode-extensions.drv
  /nix/store/01vd6miz98m65hpk742xna8fb48a5z1m-vscode-with-extensions-1.43.0.drv
building '/nix/store/r4lhsfphyhwsvdwwwh7ilk7p8sr2rfi0-vscode-extensions.drv'...
building '/nix/store/dcrmlf7vax4ksy7lgwlacqmbbhgiam9a-code-url-handler.desktop.drv'...
building '/nix/store/ixbcwj7mjx4cqwzip4f885qihz23bi7r-code.desktop.drv'...
building '/nix/store/nxrjisrdafnrf7j3psq3fqxflyr63vnv-VSCode_1.43.0_linux-x64.tar.gz.drv'...
Running desktop-file validation
/nix/store/3l89k3y5f6x65wb5zfja9vya3xr6x35f-code-url-handler.desktop/share/applications/code-url-handler.desktop: error: value "@out@/share/pixmaps/code.png" for key "Icon" in group "Desktop Entry" looks like a relative path, instead of being an absolute path to an icon or an icon name
/nix/store/3l89k3y5f6x65wb5zfja9vya3xr6x35f-code-url-handler.desktop/share/applications/code-url-handler.desktop: hint: value "Utility;TextEditor;Development;IDE;" for key "Categories" in group "Desktop Entry" contains more than one main category; application might appear more than once in the application menu
Running desktop-file validation
/nix/store/nnci669k7fh3izay9wf0b3z83lifqy86-code.desktop/share/applications/code.desktop: error: value "@out@/share/pixmaps/code.png" for key "Icon" in group "Desktop Entry" looks like a relative path, instead of being an absolute path to an icon or an icon name
/nix/store/nnci669k7fh3izay9wf0b3z83lifqy86-code.desktop/share/applications/code.desktop: hint: value "Utility;TextEditor;Development;IDE;" for key "Categories" in group "Desktop Entry" contains more than one main category; application might appear more than once in the application menu
/nix/store/nnci669k7fh3izay9wf0b3z83lifqy86-code.desktop/share/applications/code.desktop: error: value "@out@/share/pixmaps/code.png" for key "Icon" in group "Desktop Action new-empty-window" looks like a relative path, instead of being an absolute path to an icon or an icon name
created 1 symlinks in user environment
builder for '/nix/store/ixbcwj7mjx4cqwzip4f885qihz23bi7r-code.desktop.drv' failed with exit code 1
cannot build derivation '/nix/store/8qjcw0mrq6byqa5cyhvlf5vj9l5n1ag3-vscode-1.43.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/01vd6miz98m65hpk742xna8fb48a5z1m-vscode-with-extensions-1.43.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/01vd6miz98m65hpk742xna8fb48a5z1m-vscode-with-extensions-1.43.0.drv' failed
```

**Comment by jonringer** [comment]
likely a regression from https://github.com/NixOS/nixpkgs/commit/7df81361e48167ed5e8de12dac5969ae4670732d

cc @orivej

**Comment by jonringer** [comment]
Actually I take that back, it seems 9665977f4cca4333add0a061db78daa2b650f0b0 caused the regression

**Comment by tbenst** [comment]
Ah thanks for the excellent bisecting

**Pull request merged**
