### PR TITLE
matrix-appservice-irc: 2.0.1 -> 3.0.0

### PR DESCRIPTION
**Pull request by mweinelt**
https://github.com/matrix-org/matrix-appservice-irc/releases/tag/3.0.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by uninsane** [comment]
```
error:
       … while evaluating the option `system.build.toplevel':

       … while evaluating definitions from `/nix/store/24q9qw6wk1amlq0vgiifdnp8nw9mr7mm-nixpkgs-patched-uninsane/nixos/modules/system/activation/top-level.nix':

       … while evaluating the option `warnings':

       … while evaluating definitions from `/nix/store/24q9qw6wk1amlq0vgiifdnp8nw9mr7mm-nixpkgs-patched-uninsane/nixos/modules/system/boot/systemd.nix':

       … while evaluating the option `systemd.services.matrix-appservice-irc.serviceConfig':

       … while evaluating definitions from `/nix/store/24q9qw6wk1amlq0vgiifdnp8nw9mr7mm-nixpkgs-patched-uninsane/nixos/modules/system/boot/systemd.nix':

       … while evaluating the option `systemd.services.matrix-appservice-irc.preStart':

       … while evaluating definitions from `/nix/store/24q9qw6wk1amlq0vgiifdnp8nw9mr7mm-nixpkgs-patched-uninsane/nixos/modules/services/matrix/appservice-irc.nix':

       … while evaluating the option `services.matrix-appservice-irc.settings.ircService.mediaProxy.publicUrl':

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: The option `services.matrix-appservice-irc.settings.ircService.mediaProxy.publicUrl' was accessed but has no value defined. Try setting the option.
``

@mweinelt `mediaProxy.publicUrl` doesn't have a default value, which is a problem since we use `builtins.toJSON cfg.settings` to create the config file. is it enough to make this `types.nullOr types.str` and default it to null?

**Comment by mweinelt** [comment]
It can't be null. Set a public URL or media won't be accessible.

**Comment by uninsane** [comment]
> It can't be null. Set a public URL or media won't be accessible.

what am i supposed to set the URL to? i just run synapse, with matrix-appservice-irc. do i set this to my homeserver URL? do i install some other package that does the proxying and point it to that? more interested in fixing the eval than in enabling image embeds in IRC tbh.

**Comment by mweinelt** [comment]
Reverse proxy http://localhost:11111/media

**Comment by mweinelt** [comment]
https://github.com/matrix-org/matrix-appservice-irc/blob/develop/config.schema.yml#L174-L185

Check the schema, all of these settings are required, but I cannot guess your reverse proxy URL.

**Pull request merged**
