### PR TITLE
dialect: 2.0.2 -> 2.1.1

### PR DESCRIPTION
**Pull request by foo-dogsquared**
###### Description of changes

Updated versions of the app now require blueprint-compiler 0.4.0 (with PR available at #190223) but seeing that it works even the current version (0.2.0), I thought to proceed and update it.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by linsui — APPROVED** [review]
Works for me.

**Comment by linsui** [comment]
Maybe we can add an update script.

**Comment by linsui** [comment]
So please add

```nix
  passthru = {
    updateScript = nix-update-script {
      attrPath = pname;
    };
  };
```

**Comment by foo-dogsquared** [comment]
> So please add
> 
> ```nix
>   passthru = {
>     updateScript = nix-update-script {
>       attrPath = pname;
>     };
>   };
> ```

Done.

**Review by linsui — APPROVED** [review]

**Comment by foo-dogsquared** [comment]
Updated to Dialect 2.1.1 (which was released just after the approval).

@linsui, you might want to take a look again.

**Review by linsui — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
> So please add

We don't necessarily need this. It is just boilerplate.

**Pull request merged**
