### PR TITLE
nixos/github-runners: Make 'enable' functional

### LINKED ISSUE #305304: github-runner: <name>.enable has no effect
The config doesn't seem to be guarded on the `enable` option. :)

## Expected behavior:

If `services.github-runner.foo.enable = false`, then that github-runner shouldn't be enabled

## Actual behavior:

The runner is enabled regardless of the `enable` setting.

/cc @veehaitch @newAM

### PR DESCRIPTION
**Pull request by chreekat**
## Description of changes

Previously, the 'enable' attribute was ignored. Now, it isn't.

Fixes #305304

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by maralorn** [comment]
:rofl: I think I have never seen this mistake before. You, sir, are living too much in the Haskell world. :laughing: 
Please cherry-pick your change onto master (instead of basing it on haskell-updates like you did) and push the result onto this branch. Then this PR should be fine again. Since your mistake only subscribed sterni and me I guess it’s fine to continue with this PR.

**Comment by maralorn** [comment]
Ah, and maybe put this into draft mode until the diff is correct to avoid further mishaps.

**Comment by chreekat** [comment]
Hahaha oops. I just blasted over to my base nipples clone while waiting for docker images to build on another project and didn't pay enough attention. I'll fix it in a bit.

**Comment by chreekat** [comment]
Thanks, autocorrect! Lol

**Comment by chreekat** [comment]
@aanderse , sorry for the earlier mess on this PR! :) Hopefully you hadn't even looked at it yet. It should be ready now.

**Review by aanderse — APPROVED** [review]
sorry @chreekat ... somehow this fell off my radar

thanks for the fix!

**Comment by chreekat** [comment]
No problem! 👍🏻

**Pull request merged**
