### PR TITLE
virt-manager: 4.1.0 -> 5.0.0

### LINKED ISSUE #359433: Update request: virt-manager 4.1.0 → 5.0.0
## Package Information

- Package name: virt-manager
- Latest released version: 5.0.0
- Current version on the unstable channel: 4.1.0
- Current version on the stable/release channel: 4.1.0

## Checklist

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

## Notify maintainers

@qknight
@offlinehacker 
@fpletz
@globin

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by fpletz**
https://github.com/virt-manager/virt-manager/releases/tag/v5.0.0

Fix #359433.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by xanderio** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 359479`

---
### `aarch64-darwin`

**Comment by xanderio** [comment]
Why did you drop support for darwin?

**Comment by xanderio** [comment]
I've just checked, and it builds and runs without problems on Darwin.

**Review by xanderio — CHANGES_REQUESTED** [review]

**Comment by fpletz** [comment]
> Why did you drop support for darwin?

Because I don't have darwin and cannot verify that it still works after this rather big refactoring. Thanks for checking!

**Review by xanderio — APPROVED** [review]

**Comment by wegank** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 359479`

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>virt-manager</li>
  </ul>
</details>

**Review by wegank — APPROVED** [review]

**Comment by fpletz** [comment]
I don't feel comfortable backporting this to 24.05 since it is a major version bump and the build system was changed. The changelog doesn't seem to mention any other breaking changes though.

**Comment by xanderio** [comment]
> I don't feel comfortable backporting this to 24.05 since it is a major version bump and the build system was changed.

It's only a major version bump if the project uses SemVer, otherwise it's just some number that got increased. I'm not sure how the build systems is involved in the backporting decision other than if it builds or not?

> The changelog doesn't seem to mention any other breaking changes though.

That observation lead my to add the backporting labels in the first place.

**Comment by fpletz** [comment]
> I'm not sure how the build systems is involved in the backporting decision other than if it builds or not?

It not only has to build but we also need to check if it actually runs. Since this is an application with a GUI this needs to be done on a running 24.05 system, i.e. in a VM. I don't see a benefit in backporting since we only support 24.05 for one month and the other changes do not warrant a backport. I've seen so much weird stuff failing unpredictably doing backporting work over the years.

I'm gonna remove the 24.05 backport label. Feel free to add it again if you want to test it.

**Pull request merged**
