### PR TITLE
nixos/nextcloud: add nginx.virtualHost option

### PR DESCRIPTION
**Pull request by iFreilicht**
If you want to change something about the nginx virtual host for nextcloud, you have to write something like

```nix
services.nginx.virtualHosts."nextcloud.example.com" = {
    listen = [
        { addr = "0.0.0.0"; port = 12345; }
    ];
};
services.nextcloud = {
    enable = true;
    hostName = "nextcloud.example.com";
};
```

With this change, you can write the entire config as part of the `nextcloud` option:

```nix
services.nextcloud = {
    enable = true;
    hostName = "nextcloud.example.com";
    nginx.virtualHost = {
        listen = [
            { addr = "0.0.0.0"; port = 12345; }
        ];
    };
};
```

This is much nicer and less error-prone. This option has precedent in other nixos modules like monica, radicle, boostack or pixelfed, but because nextcloud already has custom options under `nginx`, I chose the `nginx.virtualHost` attribute instead.

## Description of changes

* The nixos `nextcloud` modules gains an additional `nginx.virtualHost` option

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by eclairevoyant** [comment]
Is it really beneficial to duplicate the nginx config in every module, rather than using e.g. `config.services.nextcloud.hostName` if you really want to avoid errors?

**Comment by iFreilicht** [comment]
Good point. I guess not technically, but it feels more intuitive to me. Sure, you can use `config.services.nextcloud.hostName` (personally I have the hostname defined in a `let` binding), but having the nginx config right in the module makes the most obvious solution also the safest one, which seems beneficial.

This also makes the option more discoverable on sites like MyNixOS, but I understand that might not be considered a good argument.

**Review by Ma27 — CHANGES_REQUESTED** [review]
I consider this to be an anti-pattern and I'd really like to see it gone everywhere in nixpkgs: https://github.com/NixOS/nixpkgs/issues/313412

The module system is there to be used. If you need a special vhost, use the nginx module (or override parts of it to be precise).

**Comment by eclairevoyant** [comment]
Agreed with Ma27. I understand it was meant to be a simple PR, but I'm coming at it from the point of, I don't think most modules should really be touching nginx config, introducing both unnecessary coupling to nginx and duplication of code for every module that needs to reimplement the smae options for parity.

**Comment by iFreilicht** [comment]
I see, it seems your proposal to remove this pattern has general support, and I agree with the reasoning.

**Pull request closed without merging**
