### PR TITLE
uhd: 4.6.0.0 -> 4.7.0.0

### PR DESCRIPTION
**Pull request by kouyk**
https://github.com/EttusResearch/uhd/releases/tag/v4.7.0.0

There are additional tests included by upstream in this release, causing the patch file to no longer be valid. I have fixed that together in this update.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by kouyk** [comment]
Results of `nix run nixpkgs#nixpkgs-review -- rev HEAD`

```
--------- Report for 'x86_64-linux' ---------
18 packages failed to build:
abracadabra gnss-sdr gnuradio gnuradio3_8 gnuradio3_8Packages.ais gnuradio3_8Packages.grnet gnuradio3_8Packages.limesdr gnuradio3_8Packages.osmosdr gnuradio3_8Packages.osmosdr.dev gnuradio3_8Packages.rds gnuradioMinimal gnuradioPackages.osmosdr gnuradioPackages.osmosdr.dev gqrx gqrx-gr-audio gqrx-portaudio python312Packages.soapysdr-with-plugins qradiolink

21 packages built:
cubicsdr dump1090 gnuradio3_8Minimal inspectrum openwebrx openwebrx.dist pothos python311Packages.soapysdr-with-plugins rtl_433 sdrangel sdrpp sigdigger soapysdr-with-plugins soapyuhd srsran suscan uhd uhd.dev uhdMinimal uhdMinimal.dev welle-io
```

**Comment by kouyk** [comment]
> Ugh, looks like many packages are broken already on master branch.

Thanks for the confirmation! This is quite worrying given how close we are to 24.11.

**Comment by doronbehar** [comment]
I don't understand why `hydra-check` says that `gnuradio` packages fail to build due to dependencies... Also locally it starts building right away (didn't have time to see it through), I'll ask ofborg in the meantime:

@ofborg build gnuradio

@ofborg build gnuradio3_8

**Comment by doronbehar** [comment]
@ofborg build gnuradio3_8

**Comment by doronbehar** [comment]
OK as for Gnuradio 3.10, I'm optimistic that if me and/or @LunNova will fix `python311Packages.pyqt6` it will be fixed as well. (Don't have time now to dig into that, but here is a build log: https://cache.nixos.org/log/8b01w19ymf8w9grnbsr7vhd1vccgxax2-python3.11-pyqt6-6.7.0.dev2404081550.drv ).

As for ofborg's build timing out for GR 3.8, it also continues on forever locally, so I disabled the tests completely. Let's see it is fixed now:

@ofborg build gnuradio3_8

**Comment by LunNova** [comment]
pyqt6 should be building again: #348697

**Comment by doronbehar** [comment]
@ofborg build gnuradio

**Review by doronbehar — APPROVED** [review]
OK CI is green for `gnuradio` except for `x86_64-darwin` in which it times out; I'm optimistic it won't be an issue on Hydra. For `gnuradio3_8` it is fully green, and I also checked locally `gnuradio3_8Packages.{osmo,lime}sdr` and they are OK.

Diff LGTM.

**Comment by doronbehar** [comment]
Can be merged if there are no objections if you ask me.

**Comment by LunNova** [comment]
@ofborg build soapysdr

**Comment by doronbehar** [comment]
`soapysdr` is a dependency of `gnuradio`, so my previous `@ofborg build` already included that.

**Comment by LunNova** [comment]
@ofborg build soapysdr-with-plugins

**Comment by LunNova** [comment]
python312Packages.soapysdr-with-plugins is failing, but it's failing on master in the same way so nvm

**Comment by doronbehar** [comment]
> python312Packages.soapysdr-with-plugins is failing, but it's failing on master in the same way so nvm

It looks to me that it doesn't fail here..

**Comment by LunNova** [comment]
@ofborg build python312Packages.soapysdr-with-plugins

**Review by jopejoe1 — APPROVED** [review]
The 2 failed packages were failing before.

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 349079`

---
### `x86_64-linux`
<details>
  <summary>:x: 2 packages failed to build:</summary>
  <ul>
    <li>abracadabra</li>
    <li>python312Packages.soapysdr-with-plugins</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 38 packages built:</summary>
  <ul>
    <li>cubicsdr</li>
    <li>dump1090</li>
    <li>gnss-sdr</li>
    <li>gnuradio</li>
    <li>gnuradio3_8</li>
    <li>gnuradio3_8Minimal</li>
    <li>gnuradio3_8Packages.ais</li>
    <li>gnuradio3_8Packages.grnet</li>
    <li>gnuradio3_8Packages.limesdr</li>
    <li>gnuradio3_8Packages.osmosdr</li>
    <li>gnuradio3_8Packages.osmosdr.dev</li>
    <li>gnuradio3_8Packages.rds</li>
    <li>gnuradioMinimal</li>
    <li>gnuradioPackages.osmosdr</li>
    <li>gnuradioPackages.osmosdr.dev</li>
    <li>gqrx</li>
    <li>gqrx-gr-audio</li>
    <li>gqrx-portaudio</li>
    <li>inspectrum</li>
    <li>openwebrx</li>
    <li>openwebrx.dist</li>
    <li>pothos</li>
    <li>python311Packages.soapysdr-with-plugins</li>
    <li>qradiolink</li>
    <li>rtl_433</li>
    <li>sdrangel</li>
    <li>sdrpp</li>
    <li>sigdigger</li>
    <li>soapysdr-with-plugins</li>
    <li>soapyuhd</li>
    <li>srsran</li>
    <li>suscan</li>
    <li>swig3</li>
    <li>uhd</li>
    <li>uhd.dev</li>
    <li>uhdMinimal</li>
    <li>uhdMinimal.dev</li>
    <li>welle-io</li>
  </ul>
</details>

**Comment by emilazy** [comment]
cc @bcdarwin

Would have been good to get a ping about the reintroduction of an old SWIG version as we have been specifically trying to cut down on them. SInce the latest GNU Radio uses SWIG 4 I imagine it should not be too difficult to backport whatever change made that possible.

**Comment by emilazy** [comment]
FWIW, it also means another package requiring the end‐of‐life, not‐updated‐in‐three‐years original PCRE library (https://github.com/NixOS/nixpkgs/issues/356387); Debian has already removed PCRE entirely as of last year’s stable release, and they removed SWIG 3 in 2021. I think at the very least we’d want to backport PCRE2 support from SWIG 4, but I don’t feel great about reintroducing it at all – Gforth’s modified SWIG 3 fork was bad enough but at least that’s more contained and not something other packages can depend on.

This seems like another instance of “exceptions to our normal practice of not carrying multiple old versions of packages leading to knock‐on maintenance effects throughout the tree that eventually bottoms out in keeping around something that’s EOL/a security risk” – can I ask why we package GNU Radio 3.8 at all? It seems like 3.9 was released almost four years ago and 3.8 hasn’t had an update since 2022; should we really be shipping 24.11 with it at all?

**Pull request merged**
