### PR TITLE
gcc: place cross-compiled target libraries in lib output

### PR DESCRIPTION
**Pull request by lopsided98**
###### Motivation for this change

This is my take on an alternative, subjectively cleaner implementation of #58606 and #81781. The only functional difference is that the libraries are placed in $lib/$targetConfig/lib (which is the directory convention using by the GCC build scripts) rather than $lib/lib. This requires a minor change to cc-wrapper. Subjectively, I believe it is cleaner because it unifies the handling of the cross and non-cross cases and is therefore easier to reason about.

I have tested this change by building `pkgsCross.armv7l-hf-multiplatform.hello` and `pkgsCross.aarch64-multiplatform.hello`.

While searching for potential ramifications of this change, I found a patchelf invocation that is no longer needed. I have verified that the `lib` output of the native x86_64 builds of all supported GCC versions still contain no references to their corresponding `out` output after this change.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @illegalprime @floki @matthewbauer @eamsden

### CODE REVIEW

**Review by matthewbauer — APPROVED** [review]

**Comment by lopsided98** [comment]
I removed the sotruss commit because I didn't see any references to build time bash. If someone thinks it is still needed, it can be included in a different PR.

**Comment by Ericson2314** [comment]
I hope someday the location of thtings can be the same for native and cross, but if it solves a real problem it is fine for now. The GCC build system is too much of a mess to fight slowly, it has to be an all or nothing attack.

**Comment by lopsided98** [comment]
@Ericson2314 Isn't your eventual goal to always cross-compile and use prefixed compilers (#44583 #21471), in which case this would be the correct solution and `$targetConfig` would be set even for native builds.

**Comment by Ericson2314** [comment]
@lopsided98 Yes, but my goal is also to build (or at least have build outputs as if we built) standard libraries like regular libraries, which means everything goes in `$lib/lib`. Given using GCC's monolithic build system, that would mean putting target vs host libs in separate outputs so they would both be in `$output/lib`.

**Comment by misuzu** [comment]
This probably broke i686 builds: https://hydra.nixos.org/build/114095842

**Comment by lopsided98** [comment]
The problem is that `targetConfig` is set, but GCC seems to not consider this to be a cross-compiler, so it doesn't put the target libraries in a target specific directory.

**Comment by lopsided98** [comment]
#82510 should fix that.

**Pull request merged**
