### PR TITLE
grub2: fix initrd in menu entries for probed systems

### PR DESCRIPTION
**Pull request by romildo**
###### Description of changes

Fix an issue where initrd images are separated by ^ instead of space. This was ocurring with menu entries for probed linux operating systems.

An example of a buggy menu entry that was being produced:

```grub
menuentry 'Arch Linux (on /dev/nvme0n1p6)' --class arch --class gnu-linux --class gnu --class os $menuentry_id_option 'osprober-gnulinux-simple-d8017891-2064-4391-86f1-2ed452fdccd7' {
   savedefault
   insmod part_gpt
   insmod ext2
   search --no-floppy --fs-uuid --set=root d8017891-2064-4391-86f1-2ed452fdccd7
   linux /boot/vmlinuz-linux root=UUID=d8017891-2064-4391-86f1-2ed452fdccd7 rw loglevel=3 quiet
   initrd /boot/intel-ucode.img^/boot/initramfs-linux.img
}
```

See also https://savannah.gnu.org/bugs/?47681

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by romildo** [comment]
Result of `nixpkgs-review pr 189657` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>grub2 (grub2_full ,grub2_light)</li>
    <li>grub2_efi</li>
    <li>grub2_pvgrub_image</li>
    <li>grub2_xen</li>
    <li>os-prober</li>
    <li>tests.testers.nixosTest-example</li>
    <li>tests.trivial-builders.references</li>
    <li>timeshift</li>
    <li>woeusb</li>
    <li>woeusb-ng</li>
  </ul>
</details>

**Comment by romildo** [comment]
This issue has already been reported upstream: https://savannah.gnu.org/bugs/?47681

It has already also been fixed upstream, in https://git.savannah.gnu.org/cgit/grub.git/commit/?id=000b5cd04fd228f9741f5dca0491636bc0b89eb8

But a release with the fix has not been released yet.

**Comment by SuperSandro2000** [comment]
@ofborg build grub2
@ofborg test grub2

**Review by thiagokokada — APPROVED** [review]
Would be good to add a comment saying to remove this patch once a new release is cut, but otherwise LGTM.

**Comment by romildo** [comment]
> Would be good to add a comment saying to remove this patch once a new release is cut, but otherwise LGTM.

Not needed, because with an new release this patch will not apply anymore, and we will know that it should be removed.

**Comment by thiagokokada** [comment]
> > Would be good to add a comment saying to remove this patch once a new release is cut, but otherwise LGTM.
> 
> Not needed, because with an new release this patch will not apply anymore (it will fail), and we will know that it should be removed.

This still needs more overhead from whatever person are trying to bump, because the person will need to check the reason why the patch failed to apply. If there is a simple comment, it is much easier to reason about it.

**Review by thiagokokada — APPROVED** [review]

**Review by fpletz — APPROVED** [review]

**Comment by samueldr** [comment]
I don't have anything that would exercise the code path, but considering it's already in upstream there's no reason not to merge.

**Pull request merged**
