### PR TITLE
bundler: 1.14.6 -> 1.16.1

### PR DESCRIPTION
**Pull request by flokli**
Followup of #30871.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by manveru** [comment]
@zimbatm builds fine for me on NixOS too.

**Comment by zimbatm** [comment]
I'm having issues building `nix-build -A mikutter` but it's also failing on master. /cc maintainer: @midchildan

**Comment by zimbatm** [comment]
@flokli to you mind changing the base to master? it's not going to be that much to build, ruby packages are quick to build

**Comment by midchildan** [comment]
I'll look into the issue with mikutter. It might take a few days, since I'm kind of busy right now.

**Comment by flokli** [comment]
@zimbatm base is now master again. Feel free to merge :-)

**Comment by globin** [comment]
This will break gitlab probably due to a bug in bundler or our ruby infrastructure, please don't merge until this has been tested!

**Comment by flokli** [comment]
@globin Is this still valid with the latest gitlab version bumps?

**Comment by flokli** [comment]
@globin Updated PR to `bundler-1.16.0`. I as able to at least build `gitlab`. Can you give more information on what might possibly break, so I can have a closer look?

**Comment by flokli** [comment]
I rebased this to latest nixpkgs-unstable.

The gitlab service module still seems to be broken on current nixpkgs-unstable - at least the corresponding VM test fails, and I'm unable to get a new gitlab set up via the nixos module either.

So I don't really see how merging this breaks gitlab more than it currently already is.

@globin, @fpletz: Could you please elaborate?

**Comment by zimbatm** [comment]
We should probably remove gitlab from the package set. It's a large piece of software with all sorts of dependencies and ruby omnibus (which is it's own shade of hell). Each dependency change makes the upgrade difficult. Or use the debian package and buildFHS, they already bundle all the dependencies anyways.

Personally I would use the Docker image version since it's shipped by gitlab with timely security updates and has been tested thoroughly.

**Comment by FRidh** [comment]
GitLab is an example of a large project that deserves its own overlay, just like e.g. openstack.

**Comment by mkaito** [comment]
The fact that Gitlab can keep an important (for us Ruby coders) program from being updated in an OS repo is quite frankly unacceptable. Gitlab should have to conform to the Ruby world, not the other way around.

**Comment by manveru** [comment]
The alternative is to provide gitlab its own version of bundler?

**Comment by mkaito** [comment]
If the Gitlab derivation can somehow handle it internally without affecting the rest of the repo, that'd work, I suppose.

**Comment by fpletz** [comment]
This is not only a problem with Gitlab but something we've seen with other Rails applications like frab, too. Our Ruby/Bundler infrastructure is somehow broken with this new version. Please fix this first before merging this.

Regarding Gitlab: I agree that we should probably drop Gitlab. It's a big maintenance burden.

**Comment by zimbatm** [comment]
@fpletz @globin do you still use the nixpkgs gitlab?

**Comment by fpletz** [comment]
@zimbatm Yes, we do currently.

Does really nobody else experience the same problems with other ruby packages?

**Comment by manveru** [comment]
One idea would be to change the [gitlab buildInputs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/version-management/gitlab/default.nix#L41) with:

    buildInputs = [ rubyEnv rubyEnv.wrappedRuby bundler tzdata git procps dpkg nettools ];

**Comment by flokli** [comment]
Rebased and bumped to bundler 1.16.1.

**Comment by flokli** [comment]
@GrahamcOfBorg build compass

**Comment by Mic92** [comment]
Having a different bundler in ruby.devEnv and nixpkgs breaks applications that uses bundler such as `vagrant`. This is unacceptable and should be addressed.

**Comment by vcunat** [comment]
This isn't bugfix-only, right?  (and it seems risky)  Why do you think it's worth rushing it into 18.03?

**Comment by Mic92** [comment]
@vcunat because currently other applications are broken because of this.

**Comment by Mic92** [comment]
I am not sure, if the bundler in ruby.devEnv could be downgraded though. This would also fix the problem.

**Comment by Mic92** [comment]
According to the bundler homepage using rubygems 2.2 requires bundler 1.6.1: https://bundler.io/compatibility#bundler-compatibility-with-rubygems

**Comment by Mic92** [comment]
Workaround for bundler: https://github.com/NixOS/nixpkgs/issues/36880

**Comment by polynomial** [comment]
I have a team that currently can't use 18.03 because of this. What are the next steps to getting this addressed?

**Comment by mkaito** [comment]
We use overlays for this kind d of thing.

El 22 de marzo de 2018 7:14:22 GMT+00:00, Benjamin Smith <notifications@github.com> escribió:
>I have a team that currently can't use 18.03 because of this. What are
>the next steps to getting this addressed?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/NixOS/nixpkgs/pull/30881#issuecomment-375201191

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by Mic92** [comment]
@polynomial see what breaks in our bundler infrastructure, I guess.

**Comment by mguentner** [comment]
Any news on this? :gem: :sob:

**Comment by mkaito** [comment]
I put this in a private overlay, and it was causing recompiles of all kinds of things, down to libgtk. I have no idea how bundler could possibly cause libgtk to recompile, but removing the overlay fixed it.

I think the policy here should be to prefer updating core modules like bundler, and let dependants figure it out. Especially big bad stuff like Gitlab shouldn't cause this to be held back.

I run into constant "you've already activated bundler 1.16.x but are trying to activate 1.14.x" while trying to work, even without that overlay.

**Comment by manveru** [comment]
Generally, please use the `bundlerEnv{}.wrappedRuby` and also `bundlerEnv{}.bundler` instead of the global nixpkgs ones. That should alleviate 99% of the problems.

**Comment by mkaito** [comment]
I usually load ruby_2_5.devEnv via nix-shell. That would put the correct things on the path?

El 20 de abril de 2018 16:57:19 GMT+01:00, Michael Fellinger <notifications@github.com> escribió:
>Generally, please use the `bundlerEnv{}.wrappedRuby` and also
>`bundlerEnv{}.bundler` instead of the global nixpkgs ones. That should
>alleviate 99% of the problems.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/NixOS/nixpkgs/pull/30881#issuecomment-383141519

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by mguentner** [comment]
@manveru 

Thanks for the hint with `wrappedRuby`. However this still gives me

```
/nix/store/l3lbs5jfxg215hxnvi5rlf3ymyxzf2xf-bundler-1.14.6/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:40:in `block in setup': You have already activated bundler 1.16.1, but your Gemfile requires bundler 1.14.6. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
```

Do you have a working development derivation that works w/ the current master/unstable and bundix?

Also +1 to @mkaito - but priorities tend to shift if you happen to use "big bad stuff" yourself.

@globin :eyes:

**Comment by manveru** [comment]
For that I have no simple solution siche since it seems that your Gemfile
itself had a hard version lock... Any chance you could remove that line
from it?

**Comment by mguentner** [comment]
Frankly, I have no idea what is going on. Even if I remove the version lock, the error stays the same.

**Comment by Mic92** [comment]
@globin could you just push your local fix to some branch, we worked on for gitlab, so that we can continue with this update?

**Comment by Mic92** [comment]
I will take a look at https://github.com/NixOS/nixpkgs/pull/37611 instead.

**Pull request closed without merging**
