### PR TITLE
nixos/nm-applet: starts the applet with Appindicator support

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

As of version 1.18.0 Appindicator support is available in the official network-manager-applet package. To use `nm-applet` in an Appindicator environment the applet should be started  with the following command:

```
$ nm-applet --indicator
```

Without this option it does **not** appear in the Enlightenment panel systray, for instance. (edited)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by worldofpeace — CHANGES_REQUESTED** [review]
What is the difference if this is used in an environment without appindicator support?
For example, I don't need this in Pantheon. Should this instead be turned into an option?

**Comment by romildo** [comment]
> What is the difference if this is used in an environment without appindicator support?
> For example, I don't need this in Pantheon. Should this instead be turned into an option?

(I have edited your message above by accident :( but restored it from the e-mail, sorry)

I have tested on Fluxbox, Awesome, Xfce, Mate and Enlightenment. Works normally on all of them with the --indicator. My conclusion is that it does not need to be a module option. It can always be turned on.

**Comment by worldofpeace** [comment]
> > What is the difference if this is used in an environment without appindicator support?
> > For example, I don't need this in Pantheon. Should this instead be turned into an option?
> 
> (I have edited your message above by accident :( but restored it from the e-mail, sorry)
> 
> I have tested on Fluxbox, Awesome, Xfce, Mate and Enlightenment. Works normally on all of them with the `--indicator`. My conclusion is that it does not need to be a module option. It can always be turned on.

I believe it for sure requires appindicator support to exist somewhere in the DE, and what I meant was there are desktops that I believe don't need it. According to git log at https://github.com/GNOME/network-manager-applet/commit/be72dcb896f7db59084f48eb1fdc718d88c89430 the `--indicator` flag is intended to be a feature where you can "switch between indicator and status icon at runtime". So this change would always force it to use the indicator, but maybe someone wants to use the status icon. It seems to be configurable in that manner that I think it **should** have an option, but we could probably turn it on by default. What do you think?

**Comment by romildo** [comment]
Regarding Pantheon and `nm-applet`, it is not clear to me that Pantheon is making any use of `nm-applet`, although it is started in https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/desktop-managers/pantheon.nix#L242.

The network indicator in Pantheon pane looks different from `nm-applet`, and it does not go away and still works after killing `nm-applet`.

Would it be possible that Pantheon has its own network indicator and do not use `nm-applet`?

Screenshot from 2020-09-14 19 51 39

**Comment by romildo** [comment]
I have added an option to enable indicator.

**Comment by worldofpeace** [comment]
> Regarding Pantheon and `nm-applet`, it is not clear to me that Pantheon is making any use of `nm-applet`, although it is started in https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/desktop-managers/pantheon.nix#L242.
> 
> The network indicator in Pantheon pane looks different from `nm-applet`, and it does not go away and still works after killing `nm-applet`.
> 
> Would it be possible that Pantheon has its own network indicator and do not use `nm-applet`?
> 
> Screenshot from 2020-09-14 19 51 39

Pantheon does have it's own network applet, but it does make use of networkmanagerapplet in a way that it needs it as a service running in the background. (specifically it's called within switchboard-plug-network)

**Comment by worldofpeace** [comment]
I just tried this with pantheon and the session wouldn't start. Though I couldn't reproduce it afterwards, not sure what's going on there. Though, I still think it would be correct to disable there. Could you also turn off `indicator` in `pantheon.nix`?

**Comment by romildo** [comment]
> I just tried this with pantheon and the session wouldn't start. Though I couldn't reproduce it afterwards, not sure what's going on there. Though, I still think it would be correct to disable there. Could you also turn off `indicator` in `pantheon.nix`?

Done.

**Review by worldofpeace — APPROVED** [review]

**Comment by worldofpeace** [comment]
@romildo Thanks :sparkles: Merged

**Pull request merged**
