### PR TITLE
WIP: rustPlatform: 8-27 -> 9-12

### PR DESCRIPTION
**Pull request by aljce**
###### Motivation for this change

New crates and newer version of old crates become available.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by mckeankylej** [comment]
Hum that's odd it brought in my merges and old prs. Does anyone know how to get rid of those form this pr

**Comment by grahamc** [comment]
Probably because your pr branch has those extra commits. I'll fix and merge.

**Comment by mckeankylej** [comment]
I maintain my own checkout of nixpkgs does that mean I need to wipe my commits everytime I want to pr? cc @grahamc

**Comment by grahamc** [comment]
Yes. Sorry, I ran out of time for testing this. Easy to fix the branch though.

**Comment by Mic92** [comment]
@mckeankylej 

If you do `git pull --rebase` instead of `git pull` you will not get these merge commits.
Then you can create new pull request branches with `git checkout -b <name>`
and use `git rebase -i HEAD^^` to only include those patches which are relevant for this pull request.

**Comment by the-kenny** [comment]
Supeseded by febb35bd03657bfd064cea56567331540ade3f39

**Pull request closed without merging**
