### PR TITLE
super-user-spark: 0.3.2.0 -> 0.4.0.4

### PR DESCRIPTION
**Pull request by NorfairKing**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Waiting for CI to see if this works. if there is CI ... Not sure how to build this locally.

### CODE REVIEW

**Comment by NorfairKing** [comment]
This doesn't seem to build because `genvalidity-path` is marked as broken.
How can I find out why that's broken?

**Comment by NorfairKing** [comment]
Also: how would I test building this?

**Comment by jlesquembre** [comment]
@GrahamcOfBorg build super-user-spark

**Comment by jlesquembre** [comment]
Thanks for this PR! I think you forgot to update the git revision, shouldn't it be:
```
  src = fetchgit {
    url = "https://github.com/NorfairKing/super-user-spark";
    sha256 = "1gszgh27vngn5qn8grncc95l8bwrllw5xwawzh6ssrn73wa527ks";
    rev = "17e00e60ee93c2edc71388764922c63f6f941367";
  };
```
?

Also, after that update, I get an error:

```
src/SuperUserSpark/OptParse.hs:28:27: error:
    • Couldn't match expected type ‘Options.Applicative.Types.Backtracking’
                  with actual type ‘Bool’
    • In the ‘prefBacktrack’ field of a record
      In the expression:
        ParserPrefs
          {prefMultiSuffix = "", prefDisambiguate = True,
           prefShowHelpOnError = True, prefShowHelpOnEmpty = True,
           prefBacktrack = True, prefColumns = 80}
      In an equation for ‘prefs_’:
          prefs_
            = ParserPrefs
                {prefMultiSuffix = "", prefDisambiguate = True,
                 prefShowHelpOnError = True, prefShowHelpOnEmpty = True,
                 prefBacktrack = True, prefColumns = 80}
   |
28 |         , prefBacktrack = True
   |                           ^^^^

```

I think is because of `optparse-applicative` version

**Comment by NorfairKing** [comment]
@jlesquembre Thanks! I'll fix that. How do you test whether this works?

**Comment by jlesquembre** [comment]
To test it locally:

```
nix-build "<nixpkgs>" -A super-user-spark
```

We can also use GrahamcOfBorg bot after you push your changes. You can see the output here: 
https://logs.nix.ci/?key=nixos/nixpkgs.78790&attempt_id=424e298b-4f41-45a9-a985-aa245aaba5cf

To find that link, go to the checks tab, at the bottom, there is a `View more details on OfBorg` link

**Comment by NorfairKing** [comment]
No longer maintaining super-user-spark. Use home-manager.

**Pull request closed without merging**
