### PR TITLE
minitube: new package

### PR DESCRIPTION
**Pull request by nckx**
[Minitube](flavio.tordini.org/minitube) is a pretty wrapper around (Phonon/)VLC for watching YouTube videos without having to deal with the human junkyard that is youtube.com.

Unfortunately, it doesn't work:

```
gnutls tls client error: cannot load trusted Certificate Authorities: An unimplemented or disabled feature has been requested.
gnutls tls session error: Certificate verification failure (0x0042)
gnutls tls session error:  * Certificate not verified
gnutls tls session error:  * Signer not found
core tls session error: TLS client session handshake error
http access error: cannot establish HTTP/TLS session
core input error: open of `https://r2---sn-cxab5jvh-cg06.googlevideo.com/<hilarious_cat_video>' failed
core input error: Your input can't be opened
core input error: VLC is unable to open the MRL 'https://r2---sn-cxab5jvh-cg06.googlevideo.com/<hilarious_cat_video>'. Check the log for details.
gnutls tls client error: cannot load trusted Certificate Authorities: An unimplemented or disabled feature has been requested.
Phonon error: "No active input"  Phonon::NormalError  
```

Any kind souls with knowledge?

### CODE REVIEW

**Comment by vcunat** [comment]
Actually, VLC can also just open youtube URLs, which I do sometimes (also due to performance reasons), and it claims the cert isn't trustworthy. It can be clicked to ignore the problem, but it's annoying nevertheless.

**Comment by nckx** [comment]
Indeed, when I tried pasting the offending URL into VLC proper I could manually trust the cert. From then on, that particular video also plays fine in Minitube.

Then I open the next video, and it fails all over again...

**Comment by vcunat** [comment]
I believe some package in the stack isn't directed to our cert location, ``$SSL_CERT_FILE`` (I think).

**Comment by vcunat** [comment]
I'd think gnutls is the place to patch.

**Comment by vcunat** [comment]
I'll try a solution and file a PR changing our gnutls (to discuss possible alternative solutions).

**Comment by nckx** [comment]
Awesome! Looking forward to it.

**Comment by vcunat** [comment]
Done #8121. It's rather a mass rebuild, unfortunately.

**Comment by vcunat** [comment]
Pushed to staging, as reasonable usage depends on 651e83a.

**Comment by nckx** [comment]
Thank you!

**Comment by vcunat** [comment]
Thanks for a nice package :-) though I slightly miss the configurability of vlc.

**Pull request closed without merging**
