### PR TITLE
joplin-desktop: 1.8.5 -> 2.0.11

### PR DESCRIPTION
**Pull request by ecoughlan**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by emptyflask** [comment]
Looks good to me. I built on NixOS and MacOS, works on both.
Only issue is that the latest release version is now 2.1.8, but that shouldn't prevent this from merging IMO.

**Review by HugoReeves — APPROVED** [review]
Currently unable to test on NixOS or another distro, however, it looks like others have built successfully and without issue. LGTM

**Comment by SuperSandro2000** [comment]
@ecoughlan please rebase

**Comment by emptyflask** [comment]
https://github.com/NixOS/nixpkgs/pull/130611 is already merged, so we can probably close this one

**Pull request closed without merging**
