### PR TITLE
lemmy: 0.17.4 -> 0.18.0

### PR DESCRIPTION
**Pull request by adisbladis**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by adisbladis** [comment]
Patch for `tokio::test` taken from https://github.com/LemmyNet/lemmy/pull/3329 but I opted against `fetchpatch` in case the PR is updated.

**Comment by adisbladis** [comment]
Note that `lemmy-ui` fails to start:
```
Jun 25 05:28:06 nixos systemd[1]: Started Lemmy ui.
Jun 25 05:28:07 nixos node[3301544]: Inferno is in development mode.
Jun 25 05:28:07 nixos node[3301544]: /nix/store/p4rqch5s35nmmv023fwfd3nyjipm6db5-lemmy-ui/node_modules/sharp/lib/sharp.js:37
Jun 25 05:28:07 nixos node[3301544]:   throw new Error(help.join('\n'));
Jun 25 05:28:07 nixos node[3301544]:   ^
Jun 25 05:28:07 nixos node[3301544]: Error:
Jun 25 05:28:07 nixos node[3301544]: Something went wrong installing the "sharp" module
Jun 25 05:28:07 nixos node[3301544]: Cannot find module '../build/Release/sharp-linux-x64.node'
Jun 25 05:28:07 nixos node[3301544]: Require stack:
Jun 25 05:28:07 nixos node[3301544]: - /nix/store/p4rqch5s35nmmv023fwfd3nyjipm6db5-lemmy-ui/node_modules/sharp/lib/sharp.js
Jun 25 05:28:07 nixos node[3301544]: - /nix/store/p4rqch5s35nmmv023fwfd3nyjipm6db5-lemmy-ui/node_modules/sharp/lib/constructor.js
Jun 25 05:28:07 nixos node[3301544]: - /nix/store/p4rqch5s35nmmv023fwfd3nyjipm6db5-lemmy-ui/node_modules/sharp/lib/index.js
Jun 25 05:28:07 nixos node[3301544]: - /nix/store/p4rqch5s35nmmv023fwfd3nyjipm6db5-lemmy-ui/dist/js/server.js
Jun 25 05:28:07 nixos node[3301544]: Possible solutions:
Jun 25 05:28:07 nixos node[3301544]: - Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
Jun 25 05:28:07 nixos node[3301544]: - Install for the current linux-x64 runtime: "npm install --platform=linux --arch=x64 sharp"
Jun 25 05:28:07 nixos node[3301544]: - Consult the installation documentation: https://sharp.pixelplumbing.com/install
Jun 25 05:28:07 nixos node[3301544]:     at Object.<anonymous> (/nix/store/p4rqch5s35nmmv023fwfd3nyjipm6db5-lemmy-ui/node_modules/sharp/lib/sharp.js:37:9)
Jun 25 05:28:07 nixos node[3301544]:     at Module._compile (node:internal/modules/cjs/loader:1256:14)
Jun 25 05:28:07 nixos node[3301544]:     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
Jun 25 05:28:07 nixos node[3301544]:     at Module.load (node:internal/modules/cjs/loader:1119:32)
Jun 25 05:28:07 nixos node[3301544]:     at Module._load (node:internal/modules/cjs/loader:960:12)
Jun 25 05:28:07 nixos node[3301544]:     at Module.require (node:internal/modules/cjs/loader:1143:19)
Jun 25 05:28:07 nixos node[3301544]:     at require (node:internal/modules/cjs/helpers:110:18)
Jun 25 05:28:07 nixos node[3301544]:     at Object.<anonymous> (/nix/store/p4rqch5s35nmmv023fwfd3nyjipm6db5-lemmy-ui/node_modules/sharp/lib/constructor.js:11:1)
Jun 25 05:28:07 nixos node[3301544]:     at Module._compile (node:internal/modules/cjs/loader:1256:14)
Jun 25 05:28:07 nixos node[3301544]:     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
Jun 25 05:28:07 nixos node[3301544]: Node.js v18.16.1
```

**Comment by happysalada** [comment]
It looks like we are going to have to package sharp with nix
https://github.com/lovell/sharp/blob/main/docs/install.md

**Comment by happysalada** [comment]
@matejc thanks ! I would say feel free to make a PR directly against nixpkgs, happy to be tagged.
Ill let @adisbladis confirm, but i think it should be fine.

**Comment by matejc** [comment]
@adisbladis another PR: version in the ui now works https://github.com/adisbladis/nixpkgs/pull/2
Required for solving the warning for Jerboa for Lemmy (Android app connected to the instance)

**Comment by matejc** [comment]
@happysalada just happy to help, and leave all the formalities to others

**Comment by happysalada** [comment]
LGTM, is there anything else missing ?

**Comment by adisbladis** [comment]
> LGTM, is there anything else missing ?

Nope. I was waiting for another reviewer before merging.
My personal lemmy server is already running 0.18 since I opened this PR (albeit without the UI), and the UI since @matejc's additions.

**Pull request merged**
