### PR TITLE
bitcoin: 0.15.1 -> 0.16.0

### PR DESCRIPTION
**Pull request by roconnor**
Bitcoin 0.16.0 now builds against the lastest Boost.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build bitcoin

**Comment by roconnor** [comment]
@jb55 Would you like to review?

**Comment by Mic92** [comment]
@GrahamcOfBorg build bitcoind

**Comment by roconnor** [comment]
@GrahamcOfBorg build altcoins.bitcoind

**Comment by Mic92** [comment]
@GrahamcOfBorg build altcoins.bitcoind

**Comment by Mic92** [comment]
it wants at least `hexdump` on macOS.

**Comment by roconnor** [comment]
Yes.  Bitcoin has been broken on darwin for years.  I'm waiting for a darwin enthusiast to propose a patch, but it seems there aren't any bitcoin-darwin-nix enthusiasts at the moment.

Maybe one day I can borrow a friend's OSX machine and figure out people build bitcoin on that platform.

**Comment by Mic92** [comment]
Then it should be disabled at least on macOS.

**Comment by jb55** [comment]
@roconnor sure, testing it now

**Comment by jb55** [comment]
Tested ACK 2d102cb40831d5bca73c631b6eec47313ecb1317

**Comment by roconnor** [comment]
@Mic92 How to disable darwin?  A cursory pass through the nixpkgs manual didn't reveal anything to me.

**Comment by Mic92** [comment]
@roconnor  for example by changing `meta.platforms = platforms.unix;` to `platforms = platforms.linux;`.

**Comment by roconnor** [comment]
Thanks.  I'll look into it.

FWIW, I think https://github.com/NixOS/nixpkgs/issues/25188 could provide a solution to this problem if implemented.

**Comment by Mic92** [comment]
@roconnor in future maybe.

**Comment by roconnor** [comment]
@Mic92 Okay, I've added a dependency on `darwin.shell_cmds`.  I think this actually may fix the build on `darwin` but I don't have a machine to test it on.  Maybe we can try GrahamcOfBorg?

If it fails, I'll revert and change the `meta.platforms` instead.

**Comment by Mic92** [comment]
@GrahamcOfBorg build altcoins.bitcoind

**Comment by Mic92** [comment]
@LnL7 out of general interest by looking at the error message, does `bison` in nixpkgs comes from GNU or from macOS?

**Comment by roconnor** [comment]
I see, `darwin.shell_cmds` doesn't even build.  I guess this is too far out of my league.  I'll disable darwin builds.

**Comment by roconnor** [comment]
@Mic92 Darwin builds should be disabled now.  Please merge when you are satisfied.

**Comment by LnL7** [comment]
@Mic92 We don't have a separate version of bison as far as I know.

**Pull request merged**
