### PR TITLE
ruff: 0.5.0 -> 0.5.1

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Diff: https://github.com/astral-sh/ruff/compare/refs/tags/0.5.0...0.5.1

Changelog: https://github.com/astral-sh/ruff/releases/tag/0.5.1

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
The build fails with:
```
thread 'main' panicked at cargo-auditable/src/collect_audit_data.rs:77:9:
cargo metadata failure: warning: `/build/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
error: Package `ruff_python_ast v0.0.0 (/build/source/crates/ruff_python_ast)` does not have feature `schemars`. It has an optional dependency with that name, but that dependency us>

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: could not compile `ruff_python_formatter` (bin "ruff_python_formatter")
```

However, running the exact same build command:
```
CC_X86_64_UNKNOWN_LINUX_GNU=/nix/store/kp2j7yn0wzwq5piy494r54dafrh83s6s-gcc-wrapper-13.3.0/bin/cc \
CXX_X86_64_UNKNOWN_LINUX_GNU=/nix/store/kp2j7yn0wzwq5piy494r54dafrh83s6s-gcc-wrapper-13.3.0/bin/c++
CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=/nix/store/kp2j7yn0wzwq5piy494r54dafrh83s6s-gcc-wrapper-13.3.0/bin/cc CC_X86_64_UNKNOWN_LINUX_GNU=/nix/store/kp2j7yn0wzwq5piy494r54dafrh83s6s-gcc-wrapper-13.3.0/bin/cc CXX_X86_64_UNKNOWN_LINUX_GNU=/nix/store/kp2j7yn0wzwq5piy494r54dafrh83s6s-gcc-wrapper-13.3.0/bin/c++ \
CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=/nix/store/kp2j7yn0wzwq5piy494r54dafrh83s6s-gcc-wrapper-13.3.0/bin/cc \
CARGO_BUILD_TARGET=x86_64-unknown-linux-gnu \
HOST_CC=/nix/store/kp2j7yn0wzwq5piy494r54dafrh83s6s-gcc-wrapper-13.3.0/bin/cc \
HOST_CXX=/nix/store/kp2j7yn0wzwq5piy494r54dafrh83s6s-gcc-wrapper-13.3.0/bin/c++ \
cargo build -j 12 --target x86_64-unknown-linux-gnu --offline --profile release
```
from the `nix-build -A ruff.src` folder **works perfectly fine**.

Note:
- I manually added `--target-dir /tmp/ruff-target` to the build command because we can't write in the nix store
- This was executed from `nix-shell -p rust-jemalloc-sys`, the only dependency for this package


What could be wrong here ? Is it an upstream issue ? How should I report this to them ?

**Comment by eljamm** [comment]
@GaetanLepage

Adding `schemars = ["dep:schemars"]` to the features made it work for me:

```nix
  preBuild = ''
    sed -i crates/ruff_python_ast/Cargo.toml \
      -e '/\[features\]/aschemars = ["dep:schemars"]'
  '';
```

According to [Features - The Cargo Book](https://doc.rust-lang.org/cargo/reference/features.html#optional-dependencies), if a package is marked as optional then this should be implicitly set. I don't know why explicitly specifying it fixes the issue or why it works when you manually build ruff from source.

**Comment by eljamm** [comment]
As discussed in the [upstream PR](https://github.com/astral-sh/ruff/pull/12275#issuecomment-2221245280), It should be enough to patch the package with:

```nix
  # Fix compatibility with cargo-auditable
  # See: https://github.com/astral-sh/ruff/pull/12275#issuecomment-2221245280
  preBuild = ''
    sed -i 's/dep:schemars/schemars/' crates/ruff_python_ast/Cargo.toml
  '';
```

This is necessary at least for now until compatibility with cargo-auditable is fixed upstream.

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 324823` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>open-webui</li>
    <li>open-webui.dist</li>
    <li>python312Packages.langchain-community</li>
    <li>python312Packages.langchain-community.dist</li>
  </ul>
</details>
<details>
  <summary>12 packages failed to build:</summary>
  <ul>
    <li>nbqa</li>
    <li>nbqa.dist</li>
    <li>python311Packages.langchain-chroma</li>
    <li>python311Packages.langchain-chroma.dist</li>
    <li>python311Packages.pyhanko</li>
    <li>python311Packages.pyhanko.dist</li>
    <li>python311Packages.xhtml2pdf</li>
    <li>python311Packages.xhtml2pdf.dist</li>
    <li>python312Packages.langchain-chroma</li>
    <li>python312Packages.langchain-chroma.dist</li>
    <li>vunnel</li>
    <li>vunnel.dist</li>
  </ul>
</details>
<details>
  <summary>43 packages built:</summary>
  <ul>
    <li>dmarc-metrics-exporter</li>
    <li>dmarc-metrics-exporter.dist</li>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python311Packages.instructor</li>
    <li>python311Packages.instructor.dist</li>
    <li>python311Packages.langchain</li>
    <li>python311Packages.langchain-community</li>
    <li>python311Packages.langchain-community.dist</li>
    <li>python311Packages.langchain-core</li>
    <li>python311Packages.langchain-core.dist</li>
    <li>python311Packages.langchain-text-splitters</li>
    <li>python311Packages.langchain-text-splitters.dist</li>
    <li>python311Packages.langchain.dist</li>
    <li>python311Packages.langsmith</li>
    <li>python311Packages.langsmith.dist</li>
    <li>python311Packages.pytest-examples</li>
    <li>python311Packages.pytest-examples.dist</li>
    <li>python311Packages.python-lsp-ruff</li>
    <li>python311Packages.python-lsp-ruff.dist</li>
    <li>python311Packages.xsdata</li>
    <li>python311Packages.xsdata.dist</li>
    <li>python312Packages.instructor</li>
    <li>python312Packages.instructor.dist</li>
    <li>python312Packages.langchain</li>
    <li>python312Packages.langchain-core</li>
    <li>python312Packages.langchain-core.dist</li>
    <li>python312Packages.langchain-text-splitters</li>
    <li>python312Packages.langchain-text-splitters.dist</li>
    <li>python312Packages.langchain.dist</li>
    <li>python312Packages.langsmith</li>
    <li>python312Packages.langsmith.dist</li>
    <li>python312Packages.pytest-examples</li>
    <li>python312Packages.pytest-examples.dist</li>
    <li>python312Packages.python-lsp-ruff</li>
    <li>python312Packages.python-lsp-ruff.dist</li>
    <li>python312Packages.xsdata</li>
    <li>python312Packages.xsdata.dist</li>
    <li>ruff</li>
    <li>ruff-lsp</li>
    <li>ruff-lsp.dist</li>
    <li>shell-gpt</li>
    <li>shell-gpt.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 324823` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages marked as broken and skipped:</summary>
  <ul>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>open-webui</li>
    <li>open-webui.dist</li>
    <li>python311Packages.langchain-chroma</li>
    <li>python311Packages.langchain-chroma.dist</li>
    <li>python312Packages.langchain-chroma</li>
    <li>python312Packages.langchain-chroma.dist</li>
    <li>python312Packages.langchain-community</li>
    <li>python312Packages.langchain-community.dist</li>
  </ul>
</details>
<details>
  <summary>8 packages failed to build:</summary>
  <ul>
    <li>nbqa</li>
    <li>nbqa.dist</li>
    <li>python311Packages.pyhanko</li>
    <li>python311Packages.pyhanko.dist</li>
    <li>python311Packages.xhtml2pdf</li>
    <li>python311Packages.xhtml2pdf.dist</li>
    <li>vunnel</li>
    <li>vunnel.dist</li>
  </ul>
</details>
<details>
  <summary>43 packages built:</summary>
  <ul>
    <li>dmarc-metrics-exporter</li>
    <li>dmarc-metrics-exporter.dist</li>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python311Packages.instructor</li>
    <li>python311Packages.instructor.dist</li>
    <li>python311Packages.langchain</li>
    <li>python311Packages.langchain-community</li>
    <li>python311Packages.langchain-community.dist</li>
    <li>python311Packages.langchain-core</li>
    <li>python311Packages.langchain-core.dist</li>
    <li>python311Packages.langchain-text-splitters</li>
    <li>python311Packages.langchain-text-splitters.dist</li>
    <li>python311Packages.langchain.dist</li>
    <li>python311Packages.langsmith</li>
    <li>python311Packages.langsmith.dist</li>
    <li>python311Packages.pytest-examples</li>
    <li>python311Packages.pytest-examples.dist</li>
    <li>python311Packages.python-lsp-ruff</li>
    <li>python311Packages.python-lsp-ruff.dist</li>
    <li>python311Packages.xsdata</li>
    <li>python311Packages.xsdata.dist</li>
    <li>python312Packages.instructor</li>
    <li>python312Packages.instructor.dist</li>
    <li>python312Packages.langchain</li>
    <li>python312Packages.langchain-core</li>
    <li>python312Packages.langchain-core.dist</li>
    <li>python312Packages.langchain-text-splitters</li>
    <li>python312Packages.langchain-text-splitters.dist</li>
    <li>python312Packages.langchain.dist</li>
    <li>python312Packages.langsmith</li>
    <li>python312Packages.langsmith.dist</li>
    <li>python312Packages.pytest-examples</li>
    <li>python312Packages.pytest-examples.dist</li>
    <li>python312Packages.python-lsp-ruff</li>
    <li>python312Packages.python-lsp-ruff.dist</li>
    <li>python312Packages.xsdata</li>
    <li>python312Packages.xsdata.dist</li>
    <li>ruff</li>
    <li>ruff-lsp</li>
    <li>ruff-lsp.dist</li>
    <li>shell-gpt</li>
    <li>shell-gpt.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 324823` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>open-webui</li>
    <li>open-webui.dist</li>
    <li>python312Packages.langchain-community</li>
    <li>python312Packages.langchain-community.dist</li>
  </ul>
</details>
<details>
  <summary>46 packages failed to build:</summary>
  <ul>
    <li>dmarc-metrics-exporter</li>
    <li>dmarc-metrics-exporter.dist</li>
    <li>nbqa</li>
    <li>nbqa.dist</li>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python311Packages.instructor</li>
    <li>python311Packages.instructor.dist</li>
    <li>python311Packages.langchain</li>
    <li>python311Packages.langchain-chroma</li>
    <li>python311Packages.langchain-chroma.dist</li>
    <li>python311Packages.langchain-community</li>
    <li>python311Packages.langchain-community.dist</li>
    <li>python311Packages.langchain-core</li>
    <li>python311Packages.langchain-core.dist</li>
    <li>python311Packages.langchain-text-splitters</li>
    <li>python311Packages.langchain-text-splitters.dist</li>
    <li>python311Packages.langchain.dist</li>
    <li>python311Packages.langsmith</li>
    <li>python311Packages.langsmith.dist</li>
    <li>python311Packages.pyhanko</li>
    <li>python311Packages.pyhanko.dist</li>
    <li>python311Packages.pytest-examples</li>
    <li>python311Packages.pytest-examples.dist</li>
    <li>python311Packages.xhtml2pdf</li>
    <li>python311Packages.xhtml2pdf.dist</li>
    <li>python312Packages.instructor</li>
    <li>python312Packages.instructor.dist</li>
    <li>python312Packages.langchain</li>
    <li>python312Packages.langchain-chroma</li>
    <li>python312Packages.langchain-chroma.dist</li>
    <li>python312Packages.langchain-core</li>
    <li>python312Packages.langchain-core.dist</li>
    <li>python312Packages.langchain-text-splitters</li>
    <li>python312Packages.langchain-text-splitters.dist</li>
    <li>python312Packages.langchain.dist</li>
    <li>python312Packages.langsmith</li>
    <li>python312Packages.langsmith.dist</li>
    <li>python312Packages.pytest-examples</li>
    <li>python312Packages.pytest-examples.dist</li>
    <li>ruff-lsp</li>
    <li>ruff-lsp.dist</li>
    <li>shell-gpt</li>
    <li>shell-gpt.dist</li>
    <li>vunnel</li>
    <li>vunnel.dist</li>
  </ul>
</details>
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>python311Packages.python-lsp-ruff</li>
    <li>python311Packages.python-lsp-ruff.dist</li>
    <li>python311Packages.xsdata</li>
    <li>python311Packages.xsdata.dist</li>
    <li>python312Packages.python-lsp-ruff</li>
    <li>python312Packages.python-lsp-ruff.dist</li>
    <li>python312Packages.xsdata</li>
    <li>python312Packages.xsdata.dist</li>
    <li>ruff</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 324823` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>open-webui</li>
    <li>open-webui.dist</li>
    <li>python312Packages.langchain-community</li>
    <li>python312Packages.langchain-community.dist</li>
  </ul>
</details>
<details>
  <summary>46 packages failed to build:</summary>
  <ul>
    <li>dmarc-metrics-exporter</li>
    <li>dmarc-metrics-exporter.dist</li>
    <li>nbqa</li>
    <li>nbqa.dist</li>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python311Packages.instructor</li>
    <li>python311Packages.instructor.dist</li>
    <li>python311Packages.langchain</li>
    <li>python311Packages.langchain-chroma</li>
    <li>python311Packages.langchain-chroma.dist</li>
    <li>python311Packages.langchain-community</li>
    <li>python311Packages.langchain-community.dist</li>
    <li>python311Packages.langchain-core</li>
    <li>python311Packages.langchain-core.dist</li>
    <li>python311Packages.langchain-text-splitters</li>
    <li>python311Packages.langchain-text-splitters.dist</li>
    <li>python311Packages.langchain.dist</li>
    <li>python311Packages.langsmith</li>
    <li>python311Packages.langsmith.dist</li>
    <li>python311Packages.pyhanko</li>
    <li>python311Packages.pyhanko.dist</li>
    <li>python311Packages.pytest-examples</li>
    <li>python311Packages.pytest-examples.dist</li>
    <li>python311Packages.python-lsp-ruff</li>
    <li>python311Packages.python-lsp-ruff.dist</li>
    <li>python311Packages.xhtml2pdf</li>
    <li>python311Packages.xhtml2pdf.dist</li>
    <li>python312Packages.instructor</li>
    <li>python312Packages.instructor.dist</li>
    <li>python312Packages.langchain</li>
    <li>python312Packages.langchain-chroma</li>
    <li>python312Packages.langchain-chroma.dist</li>
    <li>python312Packages.langchain-core</li>
    <li>python312Packages.langchain-core.dist</li>
    <li>python312Packages.langchain-text-splitters</li>
    <li>python312Packages.langchain-text-splitters.dist</li>
    <li>python312Packages.langchain.dist</li>
    <li>python312Packages.langsmith</li>
    <li>python312Packages.langsmith.dist</li>
    <li>python312Packages.pytest-examples</li>
    <li>python312Packages.pytest-examples.dist</li>
    <li>shell-gpt</li>
    <li>shell-gpt.dist</li>
    <li>vunnel</li>
    <li>vunnel.dist</li>
  </ul>
</details>
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>python311Packages.xsdata</li>
    <li>python311Packages.xsdata.dist</li>
    <li>python312Packages.python-lsp-ruff</li>
    <li>python312Packages.python-lsp-ruff.dist</li>
    <li>python312Packages.xsdata</li>
    <li>python312Packages.xsdata.dist</li>
    <li>ruff</li>
    <li>ruff-lsp</li>
    <li>ruff-lsp.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 324823` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>open-webui</li>
    <li>open-webui.dist</li>
    <li>python312Packages.langchain-community</li>
    <li>python312Packages.langchain-community.dist</li>
  </ul>
</details>
<details>
  <summary>29 packages failed to build:</summary>
  <ul>
    <li>dmarc-metrics-exporter</li>
    <li>dmarc-metrics-exporter.dist</li>
    <li>emacsPackages.lsp-bridge</li>
    <li>nbqa</li>
    <li>nbqa.dist</li>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python311Packages.langchain</li>
    <li>python311Packages.langchain-chroma</li>
    <li>python311Packages.langchain-chroma.dist</li>
    <li>python311Packages.langchain-community</li>
    <li>python311Packages.langchain-community.dist</li>
    <li>python311Packages.langchain.dist</li>
    <li>python311Packages.pyhanko</li>
    <li>python311Packages.pyhanko.dist</li>
    <li>python311Packages.xhtml2pdf</li>
    <li>python311Packages.xhtml2pdf.dist</li>
    <li>python312Packages.langchain</li>
    <li>python312Packages.langchain-chroma</li>
    <li>python312Packages.langchain-chroma.dist</li>
    <li>python312Packages.langchain-text-splitters</li>
    <li>python312Packages.langchain-text-splitters.dist</li>
    <li>python312Packages.langchain.dist</li>
    <li>tests.testers.lycheeLinkCheck.network</li>
    <li>tests.testers.nixosTest-example</li>
    <li>tests.testers.runNixOSTest-example</li>
    <li>tests.trivial-builders.references</li>
    <li>vunnel</li>
    <li>vunnel.dist</li>
  </ul>
</details>
<details>
  <summary>31 packages built:</summary>
  <ul>
    <li>python311Packages.instructor</li>
    <li>python311Packages.instructor.dist</li>
    <li>python311Packages.langchain-core</li>
    <li>python311Packages.langchain-core.dist</li>
    <li>python311Packages.langchain-text-splitters</li>
    <li>python311Packages.langchain-text-splitters.dist</li>
    <li>python311Packages.langsmith</li>
    <li>python311Packages.langsmith.dist</li>
    <li>python311Packages.pytest-examples</li>
    <li>python311Packages.pytest-examples.dist</li>
    <li>python311Packages.python-lsp-ruff</li>
    <li>python311Packages.python-lsp-ruff.dist</li>
    <li>python311Packages.xsdata</li>
    <li>python311Packages.xsdata.dist</li>
    <li>python312Packages.instructor</li>
    <li>python312Packages.instructor.dist</li>
    <li>python312Packages.langchain-core</li>
    <li>python312Packages.langchain-core.dist</li>
    <li>python312Packages.langsmith</li>
    <li>python312Packages.langsmith.dist</li>
    <li>python312Packages.pytest-examples</li>
    <li>python312Packages.pytest-examples.dist</li>
    <li>python312Packages.python-lsp-ruff</li>
    <li>python312Packages.python-lsp-ruff.dist</li>
    <li>python312Packages.xsdata</li>
    <li>python312Packages.xsdata.dist</li>
    <li>ruff</li>
    <li>ruff-lsp</li>
    <li>ruff-lsp.dist</li>
    <li>shell-gpt</li>
    <li>shell-gpt.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 324823` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>open-webui</li>
    <li>open-webui.dist</li>
    <li>python312Packages.langchain-community</li>
    <li>python312Packages.langchain-community.dist</li>
  </ul>
</details>
<details>
  <summary>51 packages failed to build:</summary>
  <ul>
    <li>dmarc-metrics-exporter</li>
    <li>dmarc-metrics-exporter.dist</li>
    <li>emacsPackages.lsp-bridge</li>
    <li>nbqa</li>
    <li>nbqa.dist</li>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python311Packages.instructor</li>
    <li>python311Packages.instructor.dist</li>
    <li>python311Packages.langchain</li>
    <li>python311Packages.langchain-chroma</li>
    <li>python311Packages.langchain-chroma.dist</li>
    <li>python311Packages.langchain-community</li>
    <li>python311Packages.langchain-community.dist</li>
    <li>python311Packages.langchain-core</li>
    <li>python311Packages.langchain-core.dist</li>
    <li>python311Packages.langchain-text-splitters</li>
    <li>python311Packages.langchain-text-splitters.dist</li>
    <li>python311Packages.langchain.dist</li>
    <li>python311Packages.langsmith</li>
    <li>python311Packages.langsmith.dist</li>
    <li>python311Packages.pyhanko</li>
    <li>python311Packages.pyhanko.dist</li>
    <li>python311Packages.pytest-examples</li>
    <li>python311Packages.pytest-examples.dist</li>
    <li>python311Packages.python-lsp-ruff</li>
    <li>python311Packages.python-lsp-ruff.dist</li>
    <li>python311Packages.xhtml2pdf</li>
    <li>python311Packages.xhtml2pdf.dist</li>
    <li>python312Packages.instructor</li>
    <li>python312Packages.instructor.dist</li>
    <li>python312Packages.langchain</li>
    <li>python312Packages.langchain-chroma</li>
    <li>python312Packages.langchain-chroma.dist</li>
    <li>python312Packages.langchain-core</li>
    <li>python312Packages.langchain-core.dist</li>
    <li>python312Packages.langchain-text-splitters</li>
    <li>python312Packages.langchain-text-splitters.dist</li>
    <li>python312Packages.langchain.dist</li>
    <li>python312Packages.langsmith</li>
    <li>python312Packages.langsmith.dist</li>
    <li>python312Packages.pytest-examples</li>
    <li>python312Packages.pytest-examples.dist</li>
    <li>shell-gpt</li>
    <li>shell-gpt.dist</li>
    <li>tests.testers.lycheeLinkCheck.network</li>
    <li>tests.testers.nixosTest-example</li>
    <li>tests.testers.runNixOSTest-example</li>
    <li>tests.trivial-builders.references</li>
    <li>vunnel</li>
    <li>vunnel.dist</li>
  </ul>
</details>
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>python311Packages.xsdata</li>
    <li>python311Packages.xsdata.dist</li>
    <li>python312Packages.python-lsp-ruff</li>
    <li>python312Packages.python-lsp-ruff.dist</li>
    <li>python312Packages.xsdata</li>
    <li>python312Packages.xsdata.dist</li>
    <li>ruff</li>
    <li>ruff-lsp</li>
    <li>ruff-lsp.dist</li>
  </ul>
</details>

**Review by SuperSandro2000 — APPROVED** [review]

**Pull request merged**
