### PR TITLE
smassh: 3.1.4 -> 3.1.6

### PR DESCRIPTION
**Pull request by khaneliman**
Follow up to https://github.com/NixOS/nixpkgs/pull/345228 with similar fix since https://github.com/NixOS/nixpkgs/pull/344813 broke it. 

EDIT: Also bumping versions released during PR 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 345631`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>smassh</li>
    <li>smassh.dist</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>smassh</li>
    <li>smassh.dist</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>smassh</li>
    <li>smassh.dist</li>
  </ul>
</details>

**Comment by kraanzu** [comment]
Hi @khaneliman, The dooit PR had some tests issue right due to textual version mismatch? Instead of pinning textual version, I can update the repo instead

**Comment by khaneliman** [comment]
> Hi @khaneliman, The dooit PR had some tests issue right due to textual version mismatch? Instead of pinning textual version, I can update the repo instead

dooit and smassh both got broken at runtime with the textual 81 update. 

```bash
File "/nix/store/y40ddcl2k6d5lqsdhh14d9xylqy16ayf-python3.11-textual-0.81.0/lib/python3.11/site-packages/textual/message_pump.py", line 109, in __new__
    class_obj = super().__new__(cls, name, bases, class_dict, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/y40ddcl2k6d5lqsdhh14d9xylqy16ayf-python3.11-textual-0.81.0/lib/python3.11/site-packages/textual/app.py", line 785, in __init_subclass__
    raise ValueError(
ValueError: SCREENS should contain a Screen type or callable, not an instance (got instance of MainScreen for 'main')
```

**Comment by khaneliman** [comment]
It can be updated upstream to support a newer version of textual, but we just need to unbreak it with the current version of the package here, too.

**Comment by kraanzu** [comment]
Yep. I'm working on it (will push an update in a few minutes), I see that on nixos stable, the textual version is 0.53 but on unstable its the latest (0.81) this will be handled automatically.

**Comment by kraanzu** [comment]
> but we just need to unbreak it with the current version of the package here, too.

Ah I see. Sure

I also pushed a newer version so we can also add an update for that

**Comment by khaneliman** [comment]
@kraanzu figured you want to be a maintainer for this so i added you

**Comment by kraanzu** [comment]
Thanks @khaneliman, just one more change, you need to replace `appdirs` with `platformfirs` since appdirs is not maintained anymore

**Review by AimPizza — APPROVED** [review]

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 345631`

---
### `x86_64-linux`
<details>
  <summary>:x: 2 packages failed to build:</summary>
  <ul>
    <li>smassh</li>
    <li>smassh.dist</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:x: 2 packages failed to build:</summary>
  <ul>
    <li>smassh</li>
    <li>smassh.dist</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:x: 2 packages failed to build:</summary>
  <ul>
    <li>smassh</li>
    <li>smassh.dist</li>
  </ul>
</details>

**Comment by kraanzu** [comment]
Hmmm...what went wrong here

**Comment by kraanzu** [comment]
Hi @khaneliman , I think I found the issue and fixed I. You'll need to modify the version to 3.1.6 and change the hash accordingly. Other stuff should be fine

**Comment by khaneliman** [comment]
> Hi @khaneliman , I think I found the issue and fixed I. You'll need to modify the version to 3.1.6 and change the hash accordingly. Other stuff should be fine

sorry, made a tweak before going to bed. had a typo

**Comment by khaneliman** [comment]
> Hmmm...what went wrong here

sorry, made a tweak before going to bed and had a typo in the relaxedDeps

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 345631`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>smassh</li>
    <li>smassh.dist</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>smassh</li>
    <li>smassh.dist</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>smassh</li>
    <li>smassh.dist</li>
  </ul>
</details>

**Comment by khaneliman** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 345631`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>smassh</li>
    <li>smassh.dist</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>smassh</li>
    <li>smassh.dist</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>smassh</li>
    <li>smassh.dist</li>
  </ul>
</details>

**Comment by kraanzu** [comment]
Awesome. It works now !

**Pull request merged**
