### PR TITLE
opencomposite: unstable-2023-09-11 -> unstable-2023-12-28

### PR DESCRIPTION
**Pull request by Scrumplex**
## Description of changes

https://gitlab.com/znixian/OpenOVR/-/compare/cca18158a4b6921df54e84a3b23ff459f76a2bde...07321480e3db1d398d6ab1af5b06e1eb12881e9c
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Atemu — APPROVED** [review]
As discussed in https://github.com/NixOS/nixpkgs/pull/245005#issuecomment-1861586562, I can't seem to get either before or after to work with Steam to test this. Could you share your setup?

This version does build and games crash at the same point as the previous one.

**Comment by Scrumplex** [comment]
> I can't seem to get either before or after to work with Steam to test this

After some testing, I can confirm this problem. I tried to get a backtrace, and it seems to occur in Monado, specifically in some Vulkan code:

```gdb
#0  0x0000000000000000 in ?? ()
#1  0x00007fffe82d4dce in vk_name_object (vk=vk@entry=0x9d81c8, type=type@entry=VK_OBJECT_TYPE_COMMAND_POOL, object=<optimized out>, 
    name=name@entry=0x7fffe8323fa0 "client_vk_compositor command pool") at /build/source/src/xrt/auxiliary/vk/vk_debug.c:38
#2  0x00007fffe82cfe9c in client_vk_compositor_create (xcn=<optimized out>, instance=0x69bca0, 
    getProc=0x7fffe842d7b0 <vkGetInstanceProcAddr>, physicalDevice=0x678a90, device=0x706800, 
    external_fence_fd_enabled=external_fence_fd_enabled@entry=true, external_semaphore_fd_enabled=true, timeline_semaphore_enabled=false, 
    debug_utils_enabled=true, renderdoc_enabled=false, queueFamilyIndex=0, queueIndex=0)
    at /build/source/src/xrt/compositor/client/comp_vk_client.c:862
#3  0x00007fffe82cd9bf in xrt_gfx_vk_provider_create (xcn=<optimized out>, instance=<optimized out>, 
    get_instance_proc_addr=<optimized out>, physical_device=<optimized out>, device=<optimized out>, 
    external_fence_fd_enabled=external_fence_fd_enabled@entry=true, external_semaphore_fd_enabled=true, timeline_semaphore_enabled=false, 
    debug_utils_enabled=true, renderdoc_enabled=false, queue_family_index=0, queue_index=0)
    at /build/source/src/xrt/compositor/client/comp_vk_glue.c:80
#4  0x00007fffe82b3b10 in oxr_session_populate_vk (log=log@entry=0x7fffffff0040, sys=sys@entry=0x69b220, next=next@entry=0x612458, 
    sess=sess@entry=0x7cb010) at /build/source/src/xrt/state_trackers/oxr/oxr_session_gfx_vk.c:129
#5  0x00007fffe82aea2e in oxr_session_create_impl (out_session=0x7ffffffeffc8, xsi=0x7ffffffeffd0, createInfo=0x7fffffff0150, sys=0x69b220, 
    log=0x7fffffff0040) at /build/source/src/xrt/state_trackers/oxr/oxr_session.c:848
```

So perhaps some Mesa update broke this for us?

**Comment by Scrumplex** [comment]
Slighty OT.

I don't think it's a good idea to constantly keep packages like Monado and OpenComposite up-to-date. I had this idea for a while but finally decided to work on it, so now I have an automatically updating overlay for XR/AR/VR apps: https://github.com/Scrumplex/nixpkgs-xr

Right now it includes Monado and OpenComposite.

I hope to bring it into nix-community once I feel like it's in a good state.

**Comment by Scrumplex** [comment]
> After some testing, I can confirm this problem. I tried to get a backtrace, and it seems to occur in Monado, specifically in some Vulkan code ...

Welp. Good thing that I set up `nixpkgs-xr` :D

Looks like one of the many commits on January 2nd fixed OpenComposite on NixOS.

I have updated my Monado bump accordingly: https://github.com/NixOS/nixpkgs/pull/274526

**Comment by Atemu** [comment]
I'll hopefully be able to try this out later today. Were you able to start a Steam game using this?

> I don't think it's a good idea to constantly keep fast-moving packages like Monado and OpenComposite up-to-date. I had this idea for a while but finally decided to work on it, so now I have an automatically updating overlay for XR/AR/VR apps: https://github.com/Scrumplex/nixpkgs-xr

I personally don't think we need a separate repo for this. While development does happen quickly, it doesn't appear to be particularly unstable from the packaging side as evidenced by the fact that you were able to do an update after >3 months by simply bumping the src. Other projects switch frameworks and/or language a couple times in that time frame.  

I think we should be able to keep up with it with maybe the help of a little automation and that's certainly less of a hassle to set up and maintain than a nix-community repo for like two packages?

This appears to do the trick for opencomposite:

```Nix
  passthru.updateScript = nix-update-script {
    extraArgs = [ "--version=branch" ];
  };
```

    nix-shell maintainers/scripts/update.nix --argstr package opencomposite

**Comment by Scrumplex** [comment]
> I'll hopefully be able to try this out later today. Were you able to start a Steam game using this?

Yep! H3VR worked perfectly fine

> I personally don't think we need a separate repo for this. While development does happen quickly, it doesn't appear to be particularly unstable from the packaging side as evidenced by the fact that you were able to do an update after >3 months by simply bumping the src. 

While that is true, my main issue is that both OpenComposite and Monado don't provide regular releases. It's mostly a shot in the dark when bumping as we have to hope that nothing is broken. Having a separate overlay, similar to [nix-community/nixpkgs-wayland](https://github.com/nix-community/nixpkgs-wayland), allows people to always track the latest revisions for their XR stack without having to override packages themselves or wait for PRs to merge in Nixpkgs.

Considering that the number of open Nixpkgs PRs is slowly growing, I am not so sure about regularly updating unstable packages.
My main driver for doing so was so that I could use those newer versions conveniently on my own system.

**Comment by Scrumplex** [comment]
Superseded by https://github.com/NixOS/nixpkgs/pull/283976

**Pull request closed without merging**
