### PR TITLE
miniupnpc_2: 2.1 -> 2.1.20190408, miniupnpd: 2.1 -> 2.1.20190502

### PR DESCRIPTION
**Pull request by aanderse**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/pull/57320

@bobvanderlinden as the listed maintainer of the nixos upnp test do you know any reason that we should maintain the miniupnpc 1.x package from 2016? If you can't think of any reasons I'll replace my last commit with a commit to drop the 1.x package.

ping @dtzWill as potential interested party because of comments on https://github.com/NixOS/nixpkgs/pull/57320

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by aanderse** [comment]
@GrahamcOfBorg build altcoins.bitcoind altcoins.wownero

**Comment by aanderse** [comment]
@GrahamcOfBorg test upnp

**Comment by bobvanderlinden** [comment]
@aanderse Nope, no reason why the test is using miniupnpc 1. I wasn't aware of the 2. Apparently there was a reason to switch to switch nixpkgs' `miniupnpc` to version 1 and let version 2 reside under `miniupnpc_2`. See https://github.com/NixOS/nixpkgs/commit/53b059ade536f7e9b238abb4d68eaa5bee2c31f1

That said, this PR looks good to me :+1:

**Review by bobvanderlinden — APPROVED** [review]

**Comment by bobvanderlinden** [comment]
Looking at the repository of miniupnpc I couldn't find a reason why there was no release yet. Any ideas?

**Comment by aanderse** [comment]
So now I noticed `miniupnpc` is actually pointing to `miniupnpc_1` which means unless explicitly pointing to version 2.x everything is using 1.x (which is really old). After doing a quick search it seems many packages are using version 1.x so dropping the 1.x series is beyond the scope of this PR.

I don't know the different between the 1.x series and 2.x series. I assume a project rewrite or some such? It probably makes sense to eventually drop the 1.x series... if anyone is up to the task of ensuring everything still works on the 2.x series.

**Comment by bobvanderlinden** [comment]
@Mic92 Do you know why it was decided to make miniupnpc 1 the default?

@aanderse Apart from 1 vs 2, it is still unclear for.me why `2.1.20190502` is not a official release according to the GitHub releases of miniupnp. `2.1` is an official release.

**Comment by aanderse** [comment]
I'm basing it off the official website http://miniupnp.free.fr/ on the download page. Unless the website were to explicitly state github is the official source I would continue to use the main website as the most up to date source I guess... but yes I agree it is odd the github page doesn't have that release.

**Comment by bobvanderlinden** [comment]
Aah, I see. GitHub tags/releases aren't used. For anyone else, the changelog can be found here: http://miniupnp.free.fr/files/changelog.php?file=miniupnpd-2.1.20190502.tar.gz

Thanks for the information. This looks good :+1:.

**Pull request merged**
