### PR TITLE
Revert "neovim: 0.9.5 -> 0.10.0"

### PR DESCRIPTION
**Pull request by RaitoBezarius**
Please refer to https://github.com/NixOS/nixpkgs/issues/303285.

Reverts NixOS/nixpkgs#311047 as it was not supposed to happen for this release cycle.

A full message is provided in the commit message.

### CODE REVIEW

**Comment by natsukium** [comment]
I guess we need to revert these related PRs.
https://github.com/NixOS/nixpkgs/pull/312312 @bew
https://github.com/NixOS/nixpkgs/pull/312630 @PriceHiller

**Review by GaetanLepage — APPROVED** [review]
Sorry for this. I haven't paid enough attention to the release schedule.
I will take care of re-submitting it after the branch-off.

**Review by rvolosatovs — APPROVED** [review]

**Comment by RaitoBezarius** [comment]
> I guess we need to revert these related PRs. #312312 @bew #312630 @PriceHiller

Can you push the revert commits on this PR additionally and provide a reason for their reverts as well?

**Comment by PriceHiller** [comment]
> > I guess we need to revert these related PRs. #312312 @bew #312630 @PriceHiller
> 
> 
> 
> Can you push the revert commits on this PR additionally and provide a reason for their reverts as well?

Can do in about an hour when I'm at a computer.

**Comment by PriceHiller** [comment]
@RaitoBezarius 

Not sure that I have perms to push onto your PR -- feel free to incorporate my revert commit seperate from me or point me to what I need to do to get those perms.

Thanks 🙂.

I'll likewise track for the next release cycle to update Neovide.

**Comment by natsukium** [comment]
I have reverted those two commits.

@PriceHiller 
You need to become a committer to push your commits to PRs by others.

**Comment by andrevmatos** [comment]
From what I can see, the release branches and channels are expected to be created today, so this can be re-reverted then, right? What a bummer this didn't make into the release, but thank Nix for flake locks.

**Comment by wegank** [comment]
Yes, this PR can be reverted on master after branch-off.

**Comment by adamcstephens** [comment]
Thanks @RaitoBezarius for reverting. While I'd love 0.10 in 24.05, the upgrade definitely broke things.

**Comment by RaitoBezarius** [comment]
No problem, you're welcome! Thanks for everyone's understanding on this matter and swift resolution, you all are amazing :)

**Pull request merged**
