### PR TITLE
python3Packages.pyahocorasick: 1.4.0 -> 1.4.1

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 1.4.1

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Pamplemousse** [comment]
What's the community policy about grouping several packages update in a single PR?

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 128741` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python38Packages.tern</li>
    <li>python39Packages.tern</li>
  </ul>
</details>
<details>
  <summary>33 packages built:</summary>
  <ul>
    <li>detect-secrets</li>
    <li>python38Packages.angr</li>
    <li>python38Packages.angrop</li>
    <li>python38Packages.cle</li>
    <li>python38Packages.debian-inspector</li>
    <li>python38Packages.extractcode</li>
    <li>python38Packages.extractcode-7z</li>
    <li>python38Packages.extractcode-libarchive</li>
    <li>python38Packages.karton-autoit-ripper</li>
    <li>python38Packages.karton-config-extractor</li>
    <li>python38Packages.malduck</li>
    <li>python38Packages.pefile</li>
    <li>python38Packages.pyahocorasick</li>
    <li>python38Packages.pyimpfuzzy</li>
    <li>python38Packages.qiling</li>
    <li>python38Packages.scancode-toolkit</li>
    <li>python39Packages.angr</li>
    <li>python39Packages.angrop</li>
    <li>python39Packages.cle</li>
    <li>python39Packages.debian-inspector</li>
    <li>python39Packages.extractcode</li>
    <li>python39Packages.extractcode-7z</li>
    <li>python39Packages.extractcode-libarchive</li>
    <li>python39Packages.karton-autoit-ripper</li>
    <li>python39Packages.karton-config-extractor</li>
    <li>python39Packages.malduck</li>
    <li>python39Packages.pefile</li>
    <li>python39Packages.pyahocorasick</li>
    <li>python39Packages.pyimpfuzzy</li>
    <li>python39Packages.qiling</li>
    <li>python39Packages.scancode-toolkit</li>
    <li>xorex</li>
    <li>yarGen</li>
  </ul>
</details>

**Comment by fabaff** [comment]
> What's the community policy about grouping several packages update in a single PR?

I don't think that there is one. My personal view is to keep all commits together which are fixing build failures or are needed in one way or another by the packages that are re-rebuilt because of the first commit.

**Review by jonringer — APPROVED** [review]
LGTM

failures are broken on target branch
```
https://github.com/NixOS/nixpkgs/pull/128741

2 packages failed to build:
python38Packages.tern python39Packages.tern

33 packages built:
detect-secrets python38Packages.angr python38Packages.angrop python38Packages.cle python38Packages.debian-inspector python38Packages.extractcode python38Packages.extractcode-7z python38Packages.extractcode-libarchive python38Packages.karton-autoit-ripper python38Packages.karton-config-extractor python38Packages.malduck python38Packages.pefile python38Packages.pyahocorasick python38Packages.pyimpfuzzy python38Packages.qiling python38Packages.scancode-toolkit python39Packages.angr python39Packages.angrop python39Packages.cle python39Packages.debian-inspector python39Packages.extractcode python39Packages.extractcode-7z python39Packages.extractcode-libarchive python39Packages.karton-autoit-ripper python39Packages.karton-config-extractor python39Packages.malduck python39Packages.pefile python39Packages.pyahocorasick python39Packages.pyimpfuzzy python39Packages.qiling python39Packages.scancode-toolkit xorex yarGen
```

**Comment by fabaff** [comment]
Thanks for the `tern` fix in #128809.

**Pull request merged**
