### PR TITLE
connman-ncurses: init at 2015-07-21

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

A simple ncurses UI for ConnMan.

https://github.com/eurogiciel-oss/connman-json-client
https://github.com/eurogiciel-oss/connman-json-client/wiki

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bjornfor** [comment]
Please suggest to upstream to make a release. Unless there is a release, how to know if it's ready for consumers (downstream)?

**Comment by romildo** [comment]
There is a 1.0 release: https://github.com/eurogiciel-oss/connman-json-client/releases/tag/v1.0

The package version includes some fixes committed later.

I have asked for a new release: https://github.com/eurogiciel-oss/connman-json-client/issues/21.

**Comment by bjornfor** [comment]
> There is a 1.0 release: https://github.com/eurogiciel-oss/connman-json-client/releases/tag/v1.0

I saw that. The release notes weren't that reassuring: "This first release, well... improves the beta." :-) And it's from 2014.

**Comment by bjornfor** [comment]
> I have asked for a new release: eurogiciel-oss/connman-json-client#21.

Great!

**Review by orivej — APPROVED** [review]

**Comment by joachifm** [comment]
@GrahamcOfBorg eval

**Comment by joachifm** [comment]
@GrahamcOfBorg build connman-ncurses

**Pull request merged**
