### PR TITLE
servant-auth-server: fix darwin build

### PR DESCRIPTION
**Pull request by marsam**
###### Motivation for this change

servant-auth-server test suite fails on darwin https://gist.github.com/marsam/ef547f3665aa9b7032b6799094cf9cc0

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthewbauer** [comment]
This looks like something is messed up with finding /usr/bin/security. I thought it was able to find it correctly?

**Comment by matthewbauer** [comment]
I think this override is still needed:

https://github.com/NixOS/nixpkgs/commit/d69cc779b520ea74a5b52fa5691f3f8fd7fe9cf3#diff-607a8b2e94748382228f44039b753cf0

**Comment by marsam** [comment]
Thanks! that indeed fixes it. I've partially reverted that change

**Comment by matthewbauer** [comment]
Thanks!

**Pull request merged**
