### PR TITLE
icu: bugfix #71142 - Fixes icu-config reporting bad location

### PR DESCRIPTION
**Pull request by redvers**
###### Motivation for this change
Copied from issue# 71142:

**Describe the bug**

While attempting to build some software, I have discovered that icu-config --incpkgdatafile returns the wrong location which causes my downstream build to fail.

**To Reproduce**

```
[red@apophenia:~/projects/ltfs]$ nix-shell -p icu

[nix-shell:~/projects/ltfs]$ icu-config --incpkgdatafile
/nix/store/vb7zl9wdbmgkkfdkzvklh87lv29mxbds-icu4c-64.2/lib/icu/64.2/pkgdata.inc 

[nix-shell:~/projects/ltfs]$ ls -la /nix/store/vb7zl9wdbmgkkfdkzvklh87lv29mxbds-icu4c-64.2/lib/icu/64.2/pkgdata.inc 
ls: cannot access '/nix/store/vb7zl9wdbmgkkfdkzvklh87lv29mxbds-icu4c-64.2/lib/icu/64.2/pkgdata.inc': No such file or directory
```

@jtojnar provided a suggested patch which I have now applied and tested.  It resolves the issue and doesn't break any downstream packages that I have detected.

###### Things done

Applied suggested patch and created this PR

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @raskin @jtojnar @shlevy

### CODE REVIEW

**Comment by 7c6f434c** [comment]
I think it should go to staging

**Comment by redvers** [comment]
> I think it should go to staging

I'm still a little new around these parts, so I'm guessing that means using a different branch other than master?

Which would you like me to set it against?
Also - I guess since we're jumping branches I would need to open a second PR?

So, do that and leave this one in limbo?

**Comment by 7c6f434c** [comment]
Staging is the `staging` branch, this is the branch where large non-time-critical rebuilds get accumulated for some time before forcing a mass rebuild on master. I think GitHub allows you to edit Pull Request and change the target branch.

**Comment by jtojnar** [comment]
https://github.blog/2016-08-15-change-the-base-branch-of-a-pull-request/

**Comment by redvers** [comment]
> Staging is the `staging` branch, this is the branch where large non-time-critical rebuilds get accumulated for some time before forcing a mass rebuild on master. I think GitHub allows you to edit Pull Request and change the target branch.

Done!

**Review by jtojnar — APPROVED** [review]
Hopefully, `icu-config` will be removed soon but, for now, this will do.

**Pull request merged**
