### PR TITLE
erlang: 20.0 -> 20.1

### PR DESCRIPTION
**Pull request by djgoku**
Add building of erlangR20 with odbc and javac support.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by orivej** [comment]
Thank you for updating the pull request!

@LnL7 has deleted such attributes from *all packages* in #26797, and we won't reintroduce them without a reason. If you want to install one, you can use either `beam.interpreters.erlangR20_odbc` or `(erlangR20.override { odbcSupport = true; })`.

In order to merge this, there has to be one commit with the right message. You can edit the commits in the push request with `git rebase -i master` and then `git push -f`.

**Comment by djgoku** [comment]
Ahh ok, I think there are a few documentation updates that I could update for this: nixpkgs/doc/languages-frameworks/beam.xml - https://nixos.org/nixpkgs/manual/#how-to-install-beam-packages

`nix-env -f "<nixpkgs>" -qaP -A beamPackages` doesn't work for me this works though: `nix-env -f "<nixpkgs>" -qaP -A beam.interpreters`

Should I try to update these too?

**Comment by orivej** [comment]
If you mean that the documentation does not mention that erlang is available with ODBC or without X and how to install them, then please update it. Otherwise it seems up to date. (It has been updated in #26668.)

`beam.interpreters` and `beam.packages.erlang` (aka `beamPackages`) are two different sets of packages. It seems that `nix-env -f "<nixpkgs>" -qaP -A beamPackages` must have been failing with `error: hex-packages.nix:1550:9 called without required argument ‘redix_0_3_6’` since #16122. This is quite unfortunate. @gleber, could you help fix this?

**Comment by gleber** [comment]
`beamPackages` unfortunately rotted over time, since `hex2nix` mechanism is so hard to operate currently. 

Plan to fix this is in #11748 and this issue has been reported in #26279. The only thing I can do quickly is drop most of `beamPackages`, since AFAIK they are not currently used by anyone.

**Comment by orivej** [comment]
Thank you, I'm deleting transitively unbuildable packages in #31383.

**Comment by gleber** [comment]
Sounds good!

**Pull request merged**
