### PR TITLE
koboldcpp: drop unused args, refactor darwin sdks

### PR DESCRIPTION
**Pull request by 4evy**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by DontEatOreo** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 349052`

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>koboldcpp</li>
  </ul>
</details>

**Comment by DontEatOreo** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 349052 --extra-nixpkgs-config '{ allowAliases = false; allowBroken = false; allowUnfree = true; checkMeta = true; cudaSupport = true; cudaCapabilities = [ "7.5" ]; }'`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>koboldcpp</li>
  </ul>
</details>

**Comment by DontEatOreo** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 349052`

---
### `x86_64-linux`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>koboldcpp</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>koboldcpp</li>
  </ul>
</details>

**Comment by DontEatOreo** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 349052`

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>koboldcpp</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>koboldcpp</li>
  </ul>
</details>

**Comment by emilazy** [comment]
FWIW the pattern is different and simpler now in `staging-next` after https://github.com/NixOS/nixpkgs/pull/346043. (Though this form will still work for compatibility.)

**Comment by emilazy** [comment]
If you wanted to do this on `staging-next` instead, you would leave `stdenv` alone, add `apple-sdk_12` (or whichever SDK is best‐supported) and `(darwinMinVersionHook "10.15")` to `buildInputs`, remove the `-F` lines (and perhaps the `-framework`s, if the upstream build system will detect them correctly with a normal `SDKROOT`), drop the AArch64 requirement from `metalSupport`, and remove all the framework dependencies.

**Comment by DontEatOreo** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 349052`

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>koboldcpp</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>koboldcpp</li>
  </ul>
</details>

**Review by JohnRTitor — APPROVED** [review]
Diff LGTM, but @emilazy should take a look at the new apple sdk part

**Comment by emilazy** [comment]
Sorry for the slow response. The changes look correct to me, although I haven’t checked the source code extensively to determine that the macOS 12 SDK is optimal for compatibility and functionality (but if it builds and runs, then it should be fine, and any further refinements can wait).

> Does the new `apple-sdk` pattern allow building Xcode projects, or is that still not possible?
> 
> * If _it is_ possible, can you point me to a resource?
> * If _it is not_ possible, will it be possible in the future?

I’d suggest reading the [Darwin section](https://nixos.org/manual/nixpkgs/unstable/#sec-darwin) of the Nixpkgs manual (note: this is for unstable which will change a few things there soon, since the 24.11 manual isn’t on the site yet). We do have `xcbuild` packaged, although as it is sadly unmaintained upstream it cannot support some of the newer features of Xcode projects. But in general it’s a lot easier to build macOS GUI applications now, and hopefully it’ll continue to get better with developments like @viraptor’s [`ibtool` work](https://discourse.nixos.org/t/ibtool-replacement/55397)!

**Comment by DontEatOreo** [comment]
Tested again with `Phi-3.5-mini-instruct-Q4_0.gguf`, everything works as expected

Video:
<details>

https://github.com/user-attachments/assets/6cb3c0cb-e54d-4235-8db5-a6f229dcb27e

</details>

As seen in the video, the GPU gets utilized when generating text

**Pull request merged**
