### PR TITLE
home-assistant: 0.81.5 -> 0.82.0

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
~This is work in progress because the test does not run successfully. I don't have access to a real-world instance of Home Assistant right now so I'm still putting this online for review.~
Found out the problem: I had to pin `pyotp`.

`python.pkgs.protobuf3_1` needed to be removed because `parse-requirements.py` would not be able tell which version to use. That's also the reason why I improved the `assert` statement.

I cherry-picked 00209911b0cdb76b8ec53c4be595e5a0349ba472 because I want to use `fetchPypi.override`. Should I use `git cherry-pick -x` for that?

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dotlambda** [comment]
I think we should probably add the openzwave forks created by Home Assistant: https://github.com/home-assistant/home-assistant/pull/18268.
I'll try packaging them once PyPI is up again.

**Comment by etu** [comment]
> Does anyone know of a NixOS user who's running Home Assistant to control ZWave devices and might be able to test this?

I'm probably able to test it whenever you have it packaged up. My box that I run hass on with my openzwave is a raspberry though so it may take some time to build things if it needs building because I don't have any hydra or nixops set up for that yet.

My system is running on 18.09 stable, but it should be easy to test without changing too much since the modules supports specifying which hass-package to use.

**Comment by dotlambda** [comment]
You can test it right now and it should work fine. I'll probably switch to Home Assistant's source for OpenZWave but that shouldn't change much.

**Comment by etu** [comment]
> You can test it right now and it should work fine. I'll probably switch to Home Assistant's source for OpenZWave but that shouldn't change much.

@dotlambda Oh, yeah. I'm building it on my raspberry at the moment. I'll report back whenever it's done.

**Comment by etu** [comment]
@dotlambda Hey, I have 0.82.0 running on my raspberry now from your branch. It seems to be working perfectly fine with my ZWave devices :+1:

**Pull request merged**
