### PR TITLE
Monero updates

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Motivation for this change
Version bump

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change
- [x] Tested compilation of all pkgs that depend on this change using (none)
- [x] Tested execution of all binary files
- [x] Determined the impact on package closure size (≈1)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
monero-gui [never built on darwin](https://hydra.nixos.org/job/nixpkgs/trunk/monero-gui.x86_64-darwin/all), please restrict to `platforms.linux`.

**Comment by rnhmjoj** [comment]
It used to work at least around 18.03, @LnL7 fixed the build on darwin, see https://github.com/NixOS/nixpkgs/pull/38408

**Comment by xeji** [comment]
> LnL7 fixed the build on darwin

Hydra logs go back to 2018-01-28 and don't show a single successful build on darwin.

**Comment by xeji** [comment]
Anyway, let's not block the merge because of a little cleanup. Darwin can be marked as broken later.

**Pull request merged**
