### PR TITLE
haxe: 3.2.1 -> 3.4.2

### PR DESCRIPTION
**Pull request by andyli**
###### Motivation for this change

Update the haxe package from 3.2.1 to 3.4.2.
The Haxe changelog can be found at https://github.com/HaxeFoundation/haxe/blob/3.4.2/extra/CHANGES.txt

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by vcunat — APPROVED** [review]
Seems OK, builds on Linux.

**Comment by vcunat** [comment]
Thanks and welcome to nixpkgs!

**Comment by vcunat** [comment]
Oops, this update broke hxcpp.

**Comment by volth** [comment]
It should be updated too.

Haxe-in-nixpkgs needs some work, maybe I will take it:
1. There in no ```haxePackages``` akin to ```perlPackages```/```pythonPackages``` and ```hxcpp``` is the only Haxe package here.
2. Haxe has a [new VM](https://github.com/HaxeFoundation/hashlink).

**Comment by volth** [comment]
An attempt to fix ```hxcpp``` and to add ```hxjava``` and ```hxcs```: https://github.com/NixOS/nixpkgs/compare/master...volth:haxe-patch

**Pull request merged**
