### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cole-h** [comment]
@ofborg eval

"Connection timed out" -- was probably on GitHub's side. I hope.

**Comment by FRidh** [comment]
@xfix could you check why bash-completion is failing on staging-next? https://hydra.nixos.org/build/125955252/nixlog/1

**Comment by xfix** [comment]
@FRidh As far as I can tell, this build did succeed. It likely was restarted leaving no useful information to me.

@ofborg eval bash-completion

**Comment by jonringer** [comment]
went from a staging -> master every 2 weeks to a staging -> master twice in a week.

Guess this is somewhat normal before a release :stuck_out_tongue_winking_eye:

**Comment by FRidh** [comment]
Thinks just look good. There is just the systemd trouble, but that should not block everything else. And indeed, before a release its nice to get things in.

**Pull request merged**
