### PR TITLE
pythonPackages.mayavi and dependencies

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
still need to fix the vtk bindings. Unfortunately building vtk takes a lot of time.

**Comment by 7c6f434c** [comment]
@FRidh  Should this be closed or merged? Feel free to merge it yourself — I, for one, approve this conditional on the package actually working.

**Comment by acowley** [comment]
It looks like the `vtk` part is still incomplete. I can sympathize with the pain of those rebuilds.

**Comment by FRidh** [comment]
Open issue:
```
/build/VTK-7.0.0/build/ThirdParty/netcdf/vtk_netcdfcpp.h:22:24: fatal error: netcdfcpp.h: No such file or directory
```

**Comment by FRidh** [comment]
Closing because I am not working on this anymore. Building `vtk` is a real pain.

**Pull request closed without merging**
