### PR TITLE
gasket: moved to linux-kernels.nix

### PR DESCRIPTION
**Pull request by kylehendricks**
###### Description of changes
Since this is a kernel module, this needs to be added to linux-kernels.nix so that it can be built for specific kernel versions.  I missed this when initially adding this package (my first contribution and first time building a kernel module).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kylehendricks** [comment]
Looks like something is stuck?  Did I miss something?

**Comment by colino17** [comment]
Would this being unmerged be the reason that the gasket/apex modules aren't loading? I'm using the default kernel and have this in my config:

```nix
  environment.systemPackages = with pkgs; [
    gasket
  ];
```

Is there a workaround that I can add to my config to load the modules until this is merged? Thanks!

**Comment by kylehendricks** [comment]
> Would this being unmerged be the reason that the gasket/apex modules aren't loading? I'm using the default kernel and have this in my config:
> 
> ```nix
>   environment.systemPackages = with pkgs; [
>     gasket
>   ];
> ```
> 
> Is there a workaround that I can add to my config to load the modules until this is merged? Thanks!

I'm a nix noob so I'm certain there is a cleaner way to do this but this is the first thing I got that worked:
```
  boot.extraModulePackages = [
      (config.boot.kernelPackages.callPackage (builtins.fetchurl {
          url = "https://github.com/NixOS/nixpkgs/raw/eb0f101b8aa0b704e103164699350fd3914c298c/pkgs/os-specific/linux/gasket/default.nix";
          sha256 = "0hi6cnb36qqwnspb2r94pkw99zn7b22b7hxl70c6iwb0hcg7j0bz";
          }) {})
  ];
  ```

**Comment by colino17** [comment]
Thanks for the response. I had tinkered with it after my initial response and came up with a similar solution.

I added this to my config:

```nix
let gasket = config.boot.kernelPackages.callPackage /etc/nixos/packages/coral.nix {}; in
...
{
...
  boot.extraModulePackages = [ gasket ];
...
}
```
And then created a second file at /etc/nixos/packages/coral.nix that was a copy of your default.nix

**Comment by tomgray** [comment]
I've temporarily worked around this with:

```
boot.extraModulePackages = [ (pkgs.gasket.override { kernel = config.boot.kernelPackages.kernel; }) ];
```

It overrides the kernel used in the gasket derivation with the current system's kernel.

**Comment by kylehendricks** [comment]
@ofborg eval

**Comment by SuperSandro2000** [comment]
Shouldn't we then remove the entry in all-packages https://github.com/NixOS/nixpkgs/commit/eb0f101b8aa0b704e103164699350fd3914c298c#diff-ab5748dc9567516fefba8344056b51ec1866adeace380f46e58a7af3d619ea22 ?

**Comment by kylehendricks** [comment]
> Shouldn't we then remove the entry in all-packages [eb0f101#diff-ab5748dc9567516fefba8344056b51ec1866adeace380f46e58a7af3d619ea22](https://github.com/NixOS/nixpkgs/commit/eb0f101b8aa0b704e103164699350fd3914c298c#diff-ab5748dc9567516fefba8344056b51ec1866adeace380f46e58a7af3d619ea22) ?

Ah right, good call.

**Review by SuperSandro2000 — APPROVED** [review]
nit: commit should be moved to linux-kernels/kernelPackages now rather

**Comment by SuperSandro2000** [comment]
I slipped a word, I meant the commit title should be adjusted as it is not fully true anymore.

**Comment by kylehendricks** [comment]
@SuperSandro2000 Should be good to go!

**Review by SuperSandro2000 — APPROVED** [review]

**Review by philiptaron — APPROVED** [review]
Great.

**Review by xaverdh — APPROVED** [review]
Well the package needs a version bump / newer rev to work with linux >= 6.4 but that is a separate concern. This change LGTM

**Comment by kylehendricks** [comment]
Just open a separate PR for the version bump [here](https://github.com/NixOS/nixpkgs/pull/273686/).

**Comment by philiptaron** [comment]
@NickCao, as you merged #273686, could you also merge this necessary re-arrangement?

**Comment by NickCao** [comment]
Running nixpkgs-review, build seems to be failing on many kernel versions:
```
error: builder for '/nix/store/ya78kcd8c97i2g78p6z0xazhaiy1fslw-gasket-1.0-18-unstable-2023-09-05.drv' failed with exit code 2;
       last 10 log lines:
       > mkdir: cannot create directory '/nix/store/m6bmrz149b72jpwr8r0skpld758safnn-linux-4.19.297-dev/lib/modules/4.19.297-hardened1/build/.tmp_991': Permission denied
       > mkdir: cannot create directory '/nix/store/m6bmrz149b72jpwr8r0skpld758safnn-linux-4.19.297-dev/lib/modules/4.19.297-hardened1/build/.tmp_999': Permission denied
       > mkdir: cannot create directory '/nix/store/m6bmrz149b72jpwr8r0skpld758safnn-linux-4.19.297-dev/lib/modules/4.19.297-hardened1/build/.tmp_1016': Permission denied
       > mkdir: cannot create directory '/nix/store/m6bmrz149b72jpwr8r0skpld758safnn-linux-4.19.297-dev/lib/modules/4.19.297-hardened1/build/.tmp_1024': Permission denied
       > mkdir: cannot create directory '/nix/store/m6bmrz149b72jpwr8r0skpld758safnn-linux-4.19.297-dev/lib/modules/4.19.297-hardened1/build/.tmp_1050': Permission denied
       > /nix/store/q8qq40xg2grfh9ry1d9x4g7lq4ra7n81-bash-5.2-p21/bin/bash: line 1: /nix/store/m6bmrz149b72jpwr8r0skpld758safnn-linux-4.19.297-dev/lib/modules/4.19.297-hardened1/source/modules.order: Permission denied
       > make[3]: *** [/nix/store/m6bmrz149b72jpwr8r0skpld758safnn-linux-4.19.297-dev/lib/modules/4.19.297-hardened1/source/scripts/Makefile.build:462: /nix/store/m6bmrz149b72jpwr8r0skpld758safnn-linux-4.19.297-dev/lib/modules/4.19.297-hardened1/source/modules.order] Error 1
       > make[2]: *** [/nix/store/m6bmrz149b72jpwr8r0skpld758safnn-linux-4.19.297-dev/lib/modules/4.19.297-hardened1/source/Makefile:1565: _module_/nix/store/m6bmrz149b72jpwr8r0skpld758safnn-linux-4.19.297-dev/lib/modules/4.19.297-hardened1/source] Error 2
       > make[1]: *** [Makefile:153: sub-make] Error 2
       > make: *** [Makefile:24: __sub-make] Error 2
```

**Comment by kylehendricks** [comment]
Bummer, I'll check it out.

**Comment by tomgray** [comment]
Thanks a lot for making this fix.

Kernels >= 6.4 need a later version of upstream that includes https://github.com/google/gasket-driver/pull/13.

I worked around this on `nixos-23.11` with this: https://github.com/NixOS/nixpkgs/issues/244009#issuecomment-1838033732

**Comment by SuperSandro2000** [comment]
An option for earlier kernels would also to mark the package broken for them.

**Comment by kylehendricks** [comment]
> Thanks a lot for making this fix.
> 
> Kernels >= 6.4 need a later version of upstream that includes [google/gasket-driver#13](https://github.com/google/gasket-driver/pull/13).
> 
> I worked around this on `nixos-23.11` with this: [#244009 (comment)](https://github.com/NixOS/nixpkgs/issues/244009#issuecomment-1838033732)

That was fixed in [this](https://github.com/NixOS/nixpkgs/pull/273686) PR.

**Comment by kylehendricks** [comment]
> An option for earlier kernels would also to mark the package broken for them.

Good call.

**Review by philiptaron — APPROVED** [review]

**Review by NickCao — APPROVED** [review]
Result of `nixpkgs-review pr 232136` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.linux_4_19.gasket</li>
    <li>linuxKernel.packages.linux_4_19_hardened.gasket</li>
    <li>linuxKernel.packages.linux_5_10.gasket</li>
    <li>linuxKernel.packages.linux_5_10_hardened.gasket</li>
    <li>linuxKernel.packages.linux_5_4.gasket</li>
    <li>linuxKernel.packages.linux_5_4_hardened.gasket</li>
    <li>linuxPackages_4_19_hardened.gasket</li>
    <li>linuxPackages_5_10_hardened.gasket</li>
    <li>linuxPackages_5_4_hardened.gasket</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>linuxPackages_testing_bcachefs.gasket (linuxKernel.packages.linux_testing_bcachefs.gasket)</li>
  </ul>
</details>
<details>
  <summary>14 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_5_15.gasket</li>
    <li>linuxPackages_5_15_hardened.gasket (linuxKernel.packages.linux_5_15_hardened.gasket)</li>
    <li>linuxPackages.gasket (linuxKernel.packages.linux_6_1.gasket)</li>
    <li>linuxPackages_hardened.gasket (linuxPackages_6_1_hardened.gasket)</li>
    <li>linuxKernel.packages.linux_6_5.gasket</li>
    <li>linuxPackages_6_5_hardened.gasket (linuxKernel.packages.linux_6_5_hardened.gasket)</li>
    <li>linuxPackages_latest.gasket (linuxKernel.packages.linux_6_6.gasket)</li>
    <li>linuxPackages_6_6_hardened.gasket (linuxKernel.packages.linux_6_6_hardened.gasket)</li>
    <li>linuxPackages_latest-libre.gasket (linuxKernel.packages.linux_latest_libre.gasket)</li>
    <li>linuxPackages-libre.gasket (linuxKernel.packages.linux_libre.gasket)</li>
    <li>linuxPackages_lqx.gasket (linuxKernel.packages.linux_lqx.gasket)</li>
    <li>linuxPackages_xanmod.gasket (linuxKernel.packages.linux_xanmod.gasket)</li>
    <li>linuxPackages_xanmod_latest.gasket (linuxKernel.packages.linux_xanmod_latest.gasket ,linuxPackages_xanmod_stable.gasket)</li>
    <li>linuxPackages_zen.gasket (linuxKernel.packages.linux_zen.gasket)</li>
  </ul>
</details>

**Pull request merged**
