### PR TITLE
python3Packages.bitarray: 2.2.1 -> 2.3.1

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 2.3.1

Change log: https://github.com/ilanschnell/bitarray/blob/master/CHANGE_LOG

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
`nixpkgs-review` reveals no new failures on macos 10.15.

On nixos x86_64, `homeassistant`'s test fail at

```
FAILED tests/components/august/test_lock.py::test_lock_update_via_pubnub[pyloop]
```

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 130858` at 7f16cb87 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages skipped due to time constraints:</summary>
  <ul>
    <li>glasgow (python39Packages.glasgow)</li>
    <li>home-assistant</li>
    <li>python38Packages.glasgow</li>
    <li>python38Packages.pyatv</li>
    <li>python38Packages.scancode-toolkit</li>
    <li>python39Packages.pyatv</li>
    <li>python39Packages.scancode-toolkit</li>
  </ul>
</details>
<details>
  <summary>3 packages built successfully:</summary>
  <ul>
    <li>python38Packages.bitarray</li>
    <li>python39Packages.bitarray</li>
    <li>sacad</li>
  </ul>
</details>

**Review by bhipple — APPROVED** [review]

**Review by cole-h — APPROVED** [review]

**Comment by bhipple** [comment]
Result of `nixpkgs-review pr 130858` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
<br>- home-assistant
</details>
<details>
  <summary>13 packages built:</summary>
<br>- glasgow (python39Packages.glasgow)
<br>- python38Packages.bitarray
<br>- python38Packages.extractcode
<br>- python38Packages.glasgow
<br>- python38Packages.pyatv
<br>- python38Packages.scancode-toolkit
<br>- python38Packages.typecode
<br>- python39Packages.bitarray
<br>- python39Packages.extractcode
<br>- python39Packages.pyatv
<br>- python39Packages.scancode-toolkit
<br>- python39Packages.typecode
<br>- sacad
</details>

**Comment by SuperSandro2000** [comment]
> On nixos x86_64, `homeassistant`'s test fail at
> 
> ```
> FAILED tests/components/august/test_lock.py::test_lock_update_via_pubnub[pyloop]
> ```

@fabaff @mweinelt can you take a look at this?

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 130858` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>home-assistant</li>
  </ul>
</details>
<details>
  <summary>13 packages built:</summary>
  <ul>
    <li>glasgow (python39Packages.glasgow)</li>
    <li>python38Packages.bitarray</li>
    <li>python38Packages.extractcode</li>
    <li>python38Packages.glasgow</li>
    <li>python38Packages.pyatv</li>
    <li>python38Packages.scancode-toolkit</li>
    <li>python38Packages.typecode</li>
    <li>python39Packages.bitarray</li>
    <li>python39Packages.extractcode</li>
    <li>python39Packages.pyatv</li>
    <li>python39Packages.scancode-toolkit</li>
    <li>python39Packages.typecode</li>
    <li>sacad</li>
  </ul>
</details>

**Comment by fabaff** [comment]
SSDP tests of Home Assistant are failing. The `august` issue should be solved.

```bash
[...]
TypeError: __init__() got an unexpected keyword argument 'target_ip'
___________________ test_bind_failure_skips_adapter[pyloop] ____________________
[gw1] linux -- Python 3.9.6 /nix/store/nki9ywqzbvz68vr75kn2r7g1q84f5agy-python3-3.9.6/bin/python3.9

hass = <homeassistant.core.HomeAssistant object at 0x7fff8aa30700>
caplog = <_pytest.logging.LogCaptureFixture object at 0x7fff8b5ffc70>

    async def test_bind_failure_skips_adapter(hass, caplog):
        """Test that an adapter with a bind failure is skipped."""
        mock_get_ssdp = {
            "mock-domain": [
                {
                    ssdp.ATTR_UPNP_DEVICE_TYPE: "ABC",
                }
            ]
        }
        create_args = []
        did_search = 0

        @callback
        def _callback(*_):
            nonlocal did_search
            did_search += 1
            pass

        def _generate_failing_ssdp_listener(*args, **kwargs):
            create_args.append([args, kwargs])
            listener = SSDPListener(*args, **kwargs)

            async def _async_callback(*_):
                if kwargs["source_ip"] == IPv6Address("2001:db8::"):
                    raise OSError
                pass

            listener.async_start = _async_callback
            listener.async_search = _callback
            return listener

        with patch(
            "homeassistant.components.ssdp.async_get_ssdp",
            return_value=mock_get_ssdp,
        ), patch(
            "homeassistant.components.ssdp.SSDPListener",
            new=_generate_failing_ssdp_listener,
        ), patch(
            "homeassistant.components.ssdp.network.async_get_adapters",
            return_value=_ADAPTERS_WITH_MANUAL_CONFIG,
        ):
            assert await async_setup_component(hass, ssdp.DOMAIN, {ssdp.DOMAIN: {}})
            await hass.async_block_till_done()
            hass.bus.async_fire(EVENT_HOMEASSISTANT_STARTED)
            await hass.async_block_till_done()

        argset = set()
        for argmap in create_args:
            argset.add((argmap[1].get("source_ip"), argmap[1].get("target_ip")))

        assert argset == {
            (IPv6Address("2001:db8::"), None),
            (IPv4Address("192.168.1.5"), IPv4Address("255.255.255.255")),
            (IPv4Address("192.168.1.5"), None),
        }
>       assert "Failed to setup listener for" in caplog.text
E       assert 'Failed to setup listener for' in "DEBUG    homeassistant.setup:setup.py:131 Dependency ssdp will wait for dependencies ['network']\nDEBUG    homeassist...\n    listener = SSDPListener(*args, **kwargs)\nTypeError: __init__() got an unexpected keyword argument 'target_ip'\n"
E        +  where "DEBUG    homeassistant.setup:setup.py:131 Dependency ssdp will wait for dependencies ['network']\nDEBUG    homeassist...\n    listener = SSDPListener(*args, **kwargs)\nTypeError: __init__() got an unexpected keyword argument 'target_ip'\n" = <_pytest.logging.LogCaptureFixture object at 0x7fff8b5ffc70>.text

_callback  = <function test_bind_failure_skips_adapter.<locals>._callback at 0x7fffa18aeaf0>
_generate_failing_ssdp_listener = <function test_bind_failure_skips_adapter.<locals>._generate_failing_ssdp_listener at 0x7fffa18aeca0>
argmap     = [(), {'async_callback': <bound method Scanner._async_process_entry of <homeassistant.components.ssdp.Scanner object at 0x7fff8b61f160>>, 'source_ip': IPv4Address('192.168.1.5'), 'target_ip': IPv4Address('255.255.255.255')}]
argset     = {(IPv4Address('192.168.1.5'), None), (IPv6Address('2001:db8::'), None), (IPv4Address('192.168.1.5'), IPv4Address('255.255.255.255'))}
caplog     = <_pytest.logging.LogCaptureFixture object at 0x7fff8b5ffc70>
create_args = [[(), {'async_callback': <bound method Scanner._async_process_entry of <homeassistant.components.ssdp.Scanner object a...ner object at 0x7fff8b61f160>>, 'source_ip': IPv4Address('192.168.1.5'), 'target_ip': IPv4Address('255.255.255.255')}]]
did_search = 0
hass       = <homeassistant.core.HomeAssistant object at 0x7fff8aa30700>
mock_get_ssdp = {'mock-domain': [{'deviceType': 'ABC'}]}

tests/components/ssdp/test_init.py:850: AssertionError
---------------------------- Captured stderr setup -----------------------------
DEBUG:asyncio:Using selector: EpollSelector
------------------------------ Captured log setup ------------------------------
DEBUG    asyncio:selector_events.py:59 Using selector: EpollSelector
----------------------------- Captured stderr call -----------------------------
DEBUG:homeassistant.setup:Dependency ssdp will wait for dependencies ['network']
DEBUG:homeassistant.setup:Dependency network will wait for dependencies ['websocket_api']
DEBUG:homeassistant.setup:Dependency websocket_api will wait for dependencies ['http']
INFO:homeassistant.setup:Setting up http
INFO:homeassistant.setup:Setup of domain http took 0.0 seconds
INFO:homeassistant.setup:Setting up websocket_api
INFO:homeassistant.setup:Setup of domain websocket_api took 0.0 seconds
INFO:homeassistant.setup:Setting up network
DEBUG:homeassistant.components.network.util:The system could not auto detect the source ip for 224.0.0.251 on your operating system
DEBUG:homeassistant.components.network:Adapters: [{'name': 'lo', 'index': 1, 'enabled': False, 'auto': False, 'default': False, 'ipv4': [{'address': '127.0.0.1', 'network_prefix': 8}], 'ipv6': [{'address': '::1', 'flowinfo': 0, 'scope_id': 0, 'network_prefix': 128}]}]
INFO:homeassistant.setup:Setup of domain network took 0.0 seconds
INFO:homeassistant.setup:Setting up ssdp
INFO:homeassistant.setup:Setup of domain ssdp took 0.0 seconds
ERROR:homeassistant:Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/build/source/homeassistant/components/ssdp/__init__.py", line 249, in async_start
    SSDPListener(
  File "/build/source/tests/components/ssdp/test_init.py", line 815, in _generate_failing_ssdp_listener
    listener = SSDPListener(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'target_ip'
------------------------------ Captured log call -------------------------------
DEBUG    homeassistant.setup:setup.py:131 Dependency ssdp will wait for dependencies ['network']
DEBUG    homeassistant.setup:setup.py:131 Dependency network will wait for dependencies ['websocket_api']
DEBUG    homeassistant.setup:setup.py:131 Dependency websocket_api will wait for dependencies ['http']
INFO     homeassistant.setup:setup.py:218 Setting up http
INFO     homeassistant.setup:setup.py:266 Setup of domain http took 0.0 seconds
INFO     homeassistant.setup:setup.py:218 Setting up websocket_api
INFO     homeassistant.setup:setup.py:266 Setup of domain websocket_api took 0.0 seconds
INFO     homeassistant.setup:setup.py:218 Setting up network
DEBUG    homeassistant.components.network.util:util.py:153 The system could not auto detect the source ip for 224.0.0.251 on your operating system
DEBUG    homeassistant.components.network:__init__.py:57 Adapters: [{'name': 'lo', 'index': 1, 'enabled': False, 'auto': False, 'default': False, 'ipv4': [{'address': '127.0.0.1', 'network_prefix': 8}], 'ipv6': [{'address': '::1', 'flowinfo': 0, 'scope_id': 0, 'network_prefix': 128}]}]
INFO     homeassistant.setup:setup.py:266 Setup of domain network took 0.0 seconds
INFO     homeassistant.setup:setup.py:218 Setting up ssdp
INFO     homeassistant.setup:setup.py:266 Setup of domain ssdp took 0.0 seconds
ERROR    homeassistant:runner.py:87 Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/build/source/homeassistant/components/ssdp/__init__.py", line 249, in async_start
    SSDPListener(
  File "/build/source/tests/components/ssdp/test_init.py", line 815, in _generate_failing_ssdp_listener
    listener = SSDPListener(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'target_ip'
=============================== warnings summary ===============================
../../nix/store/jav7zy5j5d6pcly18cjvk6qrr1qmyj50-python3.9-pyblackbird-0.5/lib/python3.9/site-packages/pyblackbird/__init__.py:267
[...]
-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
FAILED tests/components/ssdp/test_init.py::test_scan_match_st[pyloop] - Asser...
FAILED tests/components/ssdp/test_init.py::test_scan_match_upnp_devicedesc[pyloop-manufacturer]
FAILED tests/components/ssdp/test_init.py::test_scan_match_upnp_devicedesc[pyloop-deviceType]
FAILED tests/components/ssdp/test_init.py::test_scan_description_fetch_fail[pyloop-TimeoutError]
FAILED tests/components/ssdp/test_init.py::test_scan_description_fetch_fail[pyloop-ClientError]
FAILED tests/components/ssdp/test_init.py::test_invalid_characters[pyloop] - ...
FAILED tests/components/ssdp/test_init.py::test_start_stop_scanner[pyloop] - ...
FAILED tests/components/ssdp/test_init.py::test_unexpected_exception_while_fetching[pyloop]
FAILED tests/components/ssdp/test_init.py::test_scan_with_registered_callback[pyloop]
FAILED tests/components/ssdp/test_init.py::test_unsolicited_ssdp_registered_callback[pyloop]
FAILED tests/components/ssdp/test_init.py::test_scan_second_hit[pyloop] - ass...
FAILED tests/components/ssdp/test_init.py::test_bind_failure_skips_adapter[pyloop]
ERROR tests/components/ssdp/test_init.py::test_scan_match_st[pyloop] - TypeEr...
ERROR tests/components/ssdp/test_init.py::test_partial_response[pyloop] - Typ...
ERROR tests/components/ssdp/test_init.py::test_scan_match_upnp_devicedesc[pyloop-manufacturer]
ERROR tests/components/ssdp/test_init.py::test_scan_match_upnp_devicedesc[pyloop-deviceType]
ERROR tests/components/ssdp/test_init.py::test_scan_not_all_present[pyloop]
ERROR tests/components/ssdp/test_init.py::test_scan_not_all_match[pyloop] - T...
ERROR tests/components/ssdp/test_init.py::test_scan_description_fetch_fail[pyloop-TimeoutError]
ERROR tests/components/ssdp/test_init.py::test_scan_description_fetch_fail[pyloop-ClientError]
ERROR tests/components/ssdp/test_init.py::test_scan_description_parse_fail[pyloop]
ERROR tests/components/ssdp/test_init.py::test_invalid_characters[pyloop] - T...
ERROR tests/components/ssdp/test_init.py::test_start_stop_scanner[pyloop] - T...
ERROR tests/components/ssdp/test_init.py::test_unexpected_exception_while_fetching[pyloop]
ERROR tests/components/ssdp/test_init.py::test_scan_with_registered_callback[pyloop]
ERROR tests/components/ssdp/test_init.py::test_unsolicited_ssdp_registered_callback[pyloop]
ERROR tests/components/ssdp/test_init.py::test_scan_second_hit[pyloop] - Type...
ERROR tests/components/ssdp/test_init.py::test_async_detect_interfaces_setting_empty_route[pyloop]
ERROR tests/components/ssdp/test_init.py::test_bind_failure_skips_adapter[pyloop]
= 12 failed, 13676 passed, 11 skipped, 2 xfailed, 2006 warnings, 17 errors in 2883.97s (0:48:03) =
[...]
    Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
DeprecationWarning:
    Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
DeprecationWarning:
    Call to deprecated create function Descriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
DEBUG:pyvera:DEBUG logging is ON
builder for '/nix/store/vv3vhkrqzhx2xws87a90kvjmh6z9ldjd-homeassistant-2021.8.8.drv' failed with exit code 1
error: build of '/nix/store/vv3vhkrqzhx2xws87a90kvjmh6z9ldjd-homeassistant-2021.8.8.drv' failed
````

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 130858` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>14 packages built:</summary>
  <ul>
    <li>glasgow (python39Packages.glasgow)</li>
    <li>home-assistant</li>
    <li>python38Packages.bitarray</li>
    <li>python38Packages.extractcode</li>
    <li>python38Packages.glasgow</li>
    <li>python38Packages.pyatv</li>
    <li>python38Packages.scancode-toolkit</li>
    <li>python38Packages.typecode</li>
    <li>python39Packages.bitarray</li>
    <li>python39Packages.extractcode</li>
    <li>python39Packages.pyatv</li>
    <li>python39Packages.scancode-toolkit</li>
    <li>python39Packages.typecode</li>
    <li>sacad</li>
  </ul>
</details>

**Pull request merged**
