### PR TITLE
obsidian: 1.4.11 -> 1.4.13

### PR DESCRIPTION
**Pull request by chewblacka**
## Description of changes
https://obsidian.md/changelog/2023-09-11-desktop-v1.4.12/
https://obsidian.md/changelog/2023-09-15-desktop-v1.4.13/

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by kashw2 — CHANGES_REQUESTED** [review]
Hey! Thanks for the contribution.

Looks like the hashes have been updated, but the version is still the same.

Just need to update the version number and confirm that the hashes are still correct on both platforms.

**Comment by chewblacka** [comment]
> Hey! Thanks for the contribution.
> 
> Looks like the hashes have been updated, but the version is still the same.
> 
> Just need to update the version number and confirm that the hashes are still correct on both platforms.

Apologies! I've corrected the version number. Hashes were correct.

**Comment by qbit** [comment]
Result of `nixpkgs-review pr 255434` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>obsidian</li>
  </ul>
</details>

**Review by qbit — APPROVED** [review]

**Review by kashw2 — APPROVED** [review]
LGTM, Thanks

**Comment by fabianhjr** [comment]
@OfBorg eval

**Comment by fabianhjr** [comment]
Eval was stuck before the explicit command but just realize it might be due to an unfree license. Merging as is.

**Pull request merged**
