### PR TITLE
opensupaplex: init at 7.1.2

### LINKED ISSUE #155439: Open-supaplex
**Project description**
OpenSupaplex is a 1:1 reimplementation of the original game Supaplex in C and SDL, with just a few changes to make it easy to use with game controllers, and also easy to port to any platform.

**Metadata**

* homepage URL: https://github.com/sergiou87/open-supaplex
* source URL: https://github.com/sergiou87/open-supaplex
* license: gpl3
* platforms: linux, windows, macos

### PR DESCRIPTION
**Pull request by IvarWithoutBones**
###### Motivation for this change
Closes: https://github.com/NixOS/nixpkgs/issues/155439

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [X] aarch64-linux (cross from x84 linux)
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by legendofmiracles — APPROVED** [review]
Runs and builds for me

**Comment by mausch** [comment]
Nice, didn't know about opensupaplex, this really takes me back :slightly_smiling_face: 
Tested on Linux x86_64, works perfectly.

**Comment by legendofmiracles** [comment]
@bilfue could you please also test this?
You need a local copy of nixpkgs, and then you can use `nixpkgs-review pr 155505` to automatically checkout and compile this PR.

**Comment by bilufe** [comment]
Works for me.

**Comment by legendofmiracles** [comment]
Result of `nixpkgs-review pr 155505` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>opensupaplex</li>
  </ul>
</details>

**Pull request merged**
