### PR TITLE
kde-applications: 19.12.3 -> 20.04.1

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

Also includes the required kde-frameworks update from 5.68 to 5.71.

So far okular, gwenview and okular are working (the ones that I care
about the most) but nix-review is currently running.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by peterhoeg** [comment]
Should probably be merged together with #84542 to avoid double rebuilds.

**Comment by DIzFer** [comment]
I agree on updating all of KDE all at once at this point, but if the target plasma is 5.18 (as in the mentioned PR), I'd rather include a certain revert that fixes animation speeds being slow (8fb203c6b2d).

Alternatively, skip 5.18 altogether, wait until 5.19 is ready to merge, and skip patching frameworks during the 5 minutes it would be needed (probably the way to go)

**Review by ttuegel — APPROVED** [review]
This looks good to me!

I don't have an opinion about merging this with Plasma or not. To be honest, rebuilding Frameworks + Plasma just isn't that big compared to some other ecosystems. If the Plasma update is about ready, then let's merge them both, but I wouldn't want to see this get hung up (and outdated) based on updating Plasma.

**Comment by peterhoeg** [comment]
This is quite ready - a number of packages need patches of various kinds to work.

**Comment by ttuegel** [comment]
I fixed the patches for `kcmutils` which were causing that build to fail. (The offending patch was no longer needed.) I pushed the changes to the branch.

**Comment by ttuegel** [comment]
All KDE Frameworks and Applications now build.

**Comment by ttuegel** [comment]
The NixOS Plasma test is also passing.

**Review by ttuegel — APPROVED** [review]
All KDE Applications build and run. It's not possible for me to do detailed functional testing of each application, but the sooner we have this in the unstable branch, the sooner we can root out any problems.

**Review by ttuegel — APPROVED** [review]

**Comment by peterhoeg** [comment]
Thanks for cleaning this up @ttuegel. I realize that I meant to say "This is *not* quite ready yet" earlier.... Language is hard.

**Pull request merged**
