### PR TITLE
hyprland: 0.39.1 -> 0.40.0; hyprwayland-scanner: init at 0.3.4

### PR DESCRIPTION
**Pull request by fufexan**
## Description of changes

- **hyprwayland-scanner: init at 0.3.4** - needed for Hyprland
- **hyprland: 0.39.1 -> 0.40.0** - [CHANGELOG](https://github.com/hyprwm/Hyprland/releases/v0.40.0)

Blocked until https://github.com/NixOS/nixpkgs/pull/306557 lands in master. Tracking https://nixpk.gs/pr-tracker.html?pr=306557.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Flakebi** [comment]
Looks like swaylock and hyprlock are broken on 0.40.0, so probably makes sense to include the fix: https://github.com/hyprwm/Hyprland/issues/5913

**Comment by hakan-demirli** [comment]
@fufexan It landed.
image

**Comment by fufexan** [comment]
Everything's almost working. There's one last thing left to solve.

When building, CMake complains about missing XWayland include paths:
```c
hyprland> CMake Error in CMakeLists.txt:
hyprland>   Imported target "PkgConfig::xdeps" includes non-existent path
hyprland>     "/nix/store/7q83znq247cfc65h3zzq6l82z8dr9d56-xwayland-23.2.6/include"
hyprland>   in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
hyprland>   * The path was deleted, renamed, or moved to another location.
hyprland>   * An install or uninstall procedure did not complete successfully.
hyprland>   * The installation package was faulty and references files it does not
hyprland>   provide.
```

Checking the out dir of `xwayland`, it seems there isn't any `include` dir, even though it's referenced by its pkg-config file.
Upstream, we fixed this by using [an override](https://github.com/hyprwm/Hyprland/blob/47874f09f4d14703fe0c483a46b345c7be601ace/nix/overlays.nix#L67-L75).

Ideally, this should be fixed in xwayland upstream. I've tested the latest tag, `24.0.99.902`, but it still references the non-existent path. Pinging @emantor.

Alternatively, we could solve the problem if we could remove the path from `INTERFACE_INCLUDE_DIRECTORIES`.

**Comment by Emantor** [comment]
I have a fix for the upstream xwayland meson pkgconfig generation, will pull this in once its merged.

**Comment by Aleksanaa** [comment]
So we currently need to wait for this PR to be merged upstream, a new version is released upstream, and nixpkgs updates xwayland before we can continue this PR?

**Comment by Emantor** [comment]
> So we currently need to wait for this PR to be merged upstream, a new version is released upstream, and nixpkgs updates xwayland before we can continue this PR?

My plan is to get this merged and than fetchpatch it into nixpkgs. If I read Olivier correctly we can than remove the patch with the 24.x release.

**Comment by Aleksanaa** [comment]
Merging should not be needed, just use `https://gitlab.freedesktop.org/xorg/xserver/-/commit/5acdc7b6bdb0722e7afd276f3ae538b6195f0baa.patch` and `https://gitlab.freedesktop.org/xorg/xserver/-/commit/814dd61c1b46a8a0c4a76587dd786819180f6976.patch`?

**Comment by Emantor** [comment]
> Merging should not be needed, just use `https://gitlab.freedesktop.org/xorg/xserver/-/commit/5acdc7b6bdb0722e7afd276f3ae538b6195f0baa.patch` and `https://gitlab.freedesktop.org/xorg/xserver/-/commit/814dd61c1b46a8a0c4a76587dd786819180f6976.patch`?

The first commit is enough for the backport. My assumption was that this PR is still "Draft" and there is no need to fix this right now, but it appears that this is still a draft PR since Xwayland needs fixing first. #311886

**Comment by Emantor** [comment]
https://github.com/NixOS/nixpkgs/pull/311966 which includes the 24.1.0 bump has been merged.

**Comment by Aleksanaa** [comment]
Please be quick. The current input focus issue almost caused me to send my login password to the NixOS group today 🫠

**Review by Aleksanaa — APPROVED** [review]
Okay so I've tested in a quick way:

```
nix build github:fufexan/nixpkgs/hyprland#hyprland
ln -s $(realpath ./result) /tmp/hyprland-tmp-1
```

And then logout and change login command in greetd into `/tmp/hyprland-tmp-1/bin/hyprland`, and yeah it works (However, I observed that the output settings of kanshi and hyprland seemed to have a race, but the race with swww is solved, and input issue is gone too)

**Comment by Septias** [comment]
lets gooo

**Comment by wuyoli** [comment]
This crashes my hyprland when using it with nouveau and moving my cursor to the top of the screen.
Additionally this creates a mismatch between a cursor and its hotspots (https://github.com/hyprwm/Hyprland/issues/6117)

here the logs from one of the crashes:
```
May 21 18:35:14 gravitas kernel: nouveau 0000:01:00.0: .Hyprland-wrapp[13615]: fail ttm_validate
May 21 18:35:14 gravitas kernel: nouveau 0000:01:00.0: .Hyprland-wrapp[13615]: validating bo list
May 21 18:35:14 gravitas kernel: nouveau 0000:01:00.0: .Hyprland-wrapp[13615]: validate: -22
May 21 18:35:14 gravitas kernel: nouveau 0000:01:00.0: .Hyprland-wrapp[13615]: fail ttm_validate
May 21 18:35:14 gravitas kernel: nouveau 0000:01:00.0: .Hyprland-wrapp[13615]: validating bo list
May 21 18:35:14 gravitas kernel: nouveau 0000:01:00.0: .Hyprland-wrapp[13615]: validate: -22
May 21 18:35:14 gravitas kernel: nouveau 0000:01:00.0: fifo: fault 00 [READ] at 000000000f286000 engine 00 [GR] client 01 [GPC0/T1_0] reason 02 [PTE]>
May 21 18:35:14 gravitas kernel: nouveau 0000:01:00.0: fifo:000000:0004:[.Hyprland-wrapp[13615]] rc scheduled
May 21 18:35:14 gravitas kernel: nouveau 0000:01:00.0: fifo:000000: rc scheduled
May 21 18:35:14 gravitas kernel: nouveau 0000:01:00.0: gr: TRAP ch 4 [007fa10000 .Hyprland-wrapp[13615]]
May 21 18:35:14 gravitas kernel: nouveau 0000:01:00.0: gr: GPC0/TPC0/TEX: 80000049
May 21 18:35:14 gravitas kernel: nouveau 0000:01:00.0: gr: GPC0/TPC1/TEX: 80000049
May 21 18:35:14 gravitas kernel: nouveau 0000:01:00.0: gr: GPC1/TPC0/TEX: 80000049
May 21 18:35:14 gravitas kernel: nouveau 0000:01:00.0: fifo:000000:0004:0004:[.Hyprland-wrapp[13615]] errored - disabling channel
May 21 18:35:14 gravitas kernel: nouveau 0000:01:00.0: .Hyprland-wrapp[13615]: channel 4 killed!
May 21 18:35:14 gravitas systemd[1]: Started Process Core Dump (PID 18160/UID 0).
```

**Comment by fufexan** [comment]
I can update hyprland again when there's a fix. Until then, either use an older nixpkgs, or use the flake package.

**Comment by SuperSandro2000** [comment]
Not an ideal situation just a few days before the branch off.

**Comment by fufexan** [comment]
@wuyoli I've downgraded hyprland by a few commits, can you test whether it's all working?
https://github.com/fufexan/nixpkgs/commit/7c60f015be81a848bf1eaa5353327098c53644c2

**Comment by gvolpe** [comment]
> so that we can get them working right before the branch off

Can anyone shed some light on what this is about? 😄 

---

Also, since I'm here, I just want to thank everyone involved in this! 🙏🏽 

I haven't experienced any issues so far with Hyprlock, Hypridle and Pyprland scratchpads 👍🏽

**Comment by fufexan** [comment]
> Can anyone shed some light on what this is about? 😄

NixOS 24.05 will be released soon. See more about the process [here](https://nixos.github.io/release-wiki/Release-Process.html).

**Comment by wuyoli** [comment]
@fufexan I cherry-picked your commit https://github.com/fufexan/nixpkgs/commit/7c60f015be81a848bf1eaa5353327098c53644c2 . this didn't work, but with https://github.com/NixOS/nixpkgs/commit/7185b4755708a7b253f13a8fbe256e14f26be9d0 everything worked again.

**Comment by fufexan** [comment]
Great, I'll make a quick PR then.

**Comment by fufexan** [comment]
Also, @wuyoli do screen lockers work fine? I just remembered about [Flakebi's comment](https://github.com/NixOS/nixpkgs/pull/309075#issuecomment-2099356164).

**Comment by wuyoli** [comment]
Sorry, it just crashed again, this time it wasn't obviously in connection to some action i did. 
```
May 22 00:14:44 gravitas kernel: nouveau 0000:01:00.0: fifo: SCHED_ERROR 0a [CTXSW_TIMEOUT]
May 22 00:14:44 gravitas kernel: nouveau 0000:01:00.0: fifo:000000:0003:[.Hyprland-wrapp[6875]] rc scheduled
May 22 00:14:44 gravitas kernel: nouveau 0000:01:00.0: fifo:000000: rc scheduled
May 22 00:14:44 gravitas kernel: nouveau 0000:01:00.0: fifo:000000:0003:0003:[.Hyprland-wrapp[6875]] errored - disabling channel
May 22 00:14:44 gravitas kernel: nouveau 0000:01:00.0: .Hyprland-wrapp[6875]: channel 3 killed!
May 22 00:14:44 gravitas systemd[1]: Started Process Core Dump (PID 8056/UID 0).
```
The issue with the cursor hotspot is fixed though.

**Comment by wuyoli** [comment]
> do screen lockers work fine?
no very much not. hyprland crashes instantly (I'm using swaylock)
(sorry I missed this comment previously)

**Comment by SuperSandro2000** [comment]
> The issue with the cursor hotspot is fixed though.

That's at least something. The crash could also be related to some kernel, nouveau, some driver or maybe also xwayland but that the cursor is so much off for high DPI is good to be fixed for 24.05.

**Pull request merged**
