### PR TITLE
python311Packages.aiohttp: 3.8.6 -> 3.9.1

### PR DESCRIPTION
**Pull request by dotlambda**
## Description of changes
Changelog: https://github.com/aio-libs/aiohttp/blob/v3.9.1/CHANGES.rst

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

closes https://github.com/NixOS/nixpkgs/pull/244541

### CODE REVIEW

**Comment by dotlambda** [comment]
@mweinelt This breaks home-assistant.

**Comment by mweinelt** [comment]
```
pyproject.toml
26:    "aiohttp==3.9.0;python_version>='3.12'",
27:    "aiohttp==3.8.5;python_version<'3.12'",
```

I don't think we're ready for Python 3.12 just yet, but I might take a peak soon.

**Comment by dotlambda** [comment]
Can't we patch their `pyproject.toml` such that we can use a newer aiohttp with Python 3.11?

**Comment by mweinelt** [comment]
3.9.1 has been released, and it will be required for #270457, where runtime dependency validation will become strict again.

**Comment by mweinelt** [comment]
Rebased onto master and merged into #270457. Will carry that into `python-updates` soon.

**Pull request closed without merging**
