### PR TITLE
tetex: mark as broken, migrate packages to texlive

### PR DESCRIPTION
**Pull request by langston-barrett**
Partial fix for #21770: migrate ne and enblend-enfuse to texlive.

###### Motivation for this change
`tetex` is unsupported, and the download links don't work anymore. 

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by DerTim1 — APPROVED** [review]
Approved on Nix @Ubuntu 16.04

**Comment by siddharthist** [comment]
Looks like the tests are timing out on Linux and OSX.

**Comment by vcunat** [comment]
The main remaining package is asciidoc.  I think we shouldn't mark tetex broken before migrating that one.

**Comment by siddharthist** [comment]
@vcunat I'll try to migrate that, and if I'm unsuccessful, I'll remove the commit marking tetex as broken.

**Comment by siddharthist** [comment]
I acutally can't get `asciidoc` or `a2x` working with the latex backend as it is now (even when building `asciidoc-full`), so I'm not sure how to test my changes. 

I get this error using `asciidoc`:
```
$ ./result/bin/asciidoc --backend=latex test.asciidoc 
asciidoc: WARNING: test.asciidoc: line 4: missing section: [source-filter-style]
asciidoc: FAILED: test.asciidoc: line 4: malformed section entry: template::[source-filter-style]
```
and this with `a2x`:
```
$ PATH=$PATH:$PWD/result/bin ./result/bin/a2x --backend=latex test.asciidoc
a2x: ERROR: missing latex backend
```

**Comment by DerTim1** [comment]
I think this isn't a problem with `tetex` to `texlive.combined.schema-basic`. Look at https://groups.google.com/forum/#!topic/asciidoc/uUJz3TkOhks
So maybe the best thing would be to drop latex-support or leave it as it is.

**Comment by peterhoeg** [comment]
There's a patch for asciidoc (haven't tested it) that supposedly fixes it:

https://code.google.com/archive/p/asciidoc/issues/26

**Comment by vcunat** [comment]
Oh, I forgot, I'm sorry.  Those two commits are in master now.  `asciidoc` is the only one remaining now.

**Comment by siddharthist** [comment]
@vcunat Which two commits?

**Comment by vcunat** [comment]
The ones for ne and enblend-enfuse from this PR.  See b9d6a6c and its parent.

**Comment by siddharthist** [comment]
@vcunat Thanks!

**Comment by vcunat** [comment]
:-)

**Pull request closed without merging**
