### PR TITLE
[22-05] octoprint: 1.8.1 -> 1.8.3

### PR DESCRIPTION
**Pull request by gador**
###### Description of changes

Backport of #192399

Changes made to original PR (see second commit):
- ignore Flask-Limiter version constraint

fixes several security issues
See https://github.com/OctoPrint/OctoPrint/releases/tag/1.8.3

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).
- [x] Before merging, ensure that this backport complies with the [Criteria for Backporting](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#criteria-for-backporting-changes).
Even as a non-commiter, if you find that it does not comply, leave a comment.

### CODE REVIEW

**Comment by mweinelt** [comment]
Cherry-picks need to reference the original commit they were picked from. Check se contribution guide for `cherry-pick -x`.

**Comment by gador** [comment]
@mweinelt done :+1:

**Comment by mweinelt** [comment]
> [22-05]octoprint: fix build issue with flask-limiter dependency

Please remove the [22-05] prefix from the commit message.

**Comment by gador** [comment]
shouldn't we leave it? This isn't present in current `master` and needs to only be applied to the [22-05] release (due to the old `Flask-Limiter` version)

**Comment by mweinelt** [comment]
I haven't generally seen anything like it. The commit should simply reference the attribute name, the release can be gleaned from the branch it landed on, no?

**Comment by gador** [comment]
well, sure. I rarely backport packages, so I have only very limited experience with it :wink:

**Review by mweinelt — APPROVED** [review]

**Comment by jakehamilton** [comment]
Hey @gador @mweinelt :wave:

Interestingly, after updating to the latest NixOS 22.05 (this commit) I've found that there's now a syntax error thrown from `pkgs/build-support/fetchsvn/default.nix`.

<details>
  <summary>View Terminal Output</summary>

```
➜ sudo nixos-rebuild build --flake .

building the system configuration...
warning: updating lock file '/home/short/work/config/flake.lock':
• Updated input 'nixpkgs':
    'github:nixos/nixpkgs/30b404ddafb52c2bdd613e58dcd3376167fc6f36' (2022-09-25)
  → 'github:nixos/nixpkgs/72783a2d0dbbf030bff1537873dd5b85b3fb332f' (2022-09-25)
error: syntax error, unexpected ELSE, expecting THEN

       at /nix/store/nm2slrv3chgbfdd76h6fw1nq1703fpxg-source/pkgs/build-support/fetchsvn/default.nix:30:7:

           29|       # ../repo (no trunk) -> repo
           30|       else fst path;
             |       ^
           31|
(use '--show-trace' to show detailed location information)
```

</details>

I'm not quite sure why it is broken due to the changes from this commit, but only this commit is breaking things. I've tested the previous commits in `nixos-22.05` and they're working fine. If it's unrelated I can file a separate bug. Otherwise I wanted to mention it on this PR.

**Comment by jakehamilton** [comment]
Digging in to the file mentioned in the error, I do see that there's a typo here.

image

However, cloning the repository and checking out this commit has no such error.

image

I've no idea how or why this has happened, though I really don't think it's this PR. Apologies for cluttering things up! I suppose I'm just plagued with my own random bugs for now :upside_down_face:

**Comment by mweinelt** [comment]
Check out `git fsck` on the repo.

**Pull request merged**
