### PR TITLE
boost: default to 1.8.2

### PR DESCRIPTION
**Pull request by tobim**
###### Description of changes

There is no documented reason to pin the default version to a somewhat arbitrary release. Let's see if we can lift it.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
I suppose this would better wait past 23.05 (forking off), at this point.

**Comment by tobim** [comment]
> I suppose this would better wait past 23.05 (forking off), at this point.

I wouldn't mind.

**Comment by tobim** [comment]
Maybe we should stay one release behind to reduce the patching burden.

**Comment by tobim** [comment]
@vcunat what do you think?

**Comment by vcunat** [comment]
I got no idea about the boost ecosystem, really.

**Comment by tobim** [comment]
If we do it that we way should also remove the `boost1xx` aliases. Having `boost18x` point to 1.82, but `boost` to 1.81 would be confusing.

CC @hjones2199 as maintainer.
CC @wegank, who got rid of a lot of old  versions recently.

**Comment by wegank** [comment]
Removing `boost17x` sounds good to me.

**Comment by tobim** [comment]
#240604

**Pull request closed without merging**
