### PR TITLE
antimony: 2018-10-20 -> 2019-10-30

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Motivation for this change
Version bump and fix for #65399

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change (none)
- [x] Tested execution and loaded a project.
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by c0bw3b — APPROVED** [review]
Builds and runs

**Comment by rnhmjoj** [comment]
@c0bw3b Thank you, could you cherry-pick this into 19.09 or should I open another?

**Comment by c0bw3b** [comment]
Backported in 0d39ec23b629b48b028928465fa327bdb2d31585

**Comment by rnhmjoj** [comment]
Thank you again.

**Pull request merged**
