### PR TITLE
element-web: don't inherit jitsi-meet's knownVulnerabilities

### PR DESCRIPTION
**Pull request by dotlambda**
## Description of changes
Use `jitsi-meet.src` rather than `jisti-meet` so we're not affected by `knownVulnerabilities`.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by gador** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 335753` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>element-desktop</li>
<li>element-desktop-wayland</li>
<li>element-web (element-web-unwrapped)</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
element-desktop-wayland:
<details>

Package is missing a meta section.
If the package is using runCommand please make sure to inherit or create a meta section.

An empty (vendor) directory got detected.

If this is a go package try replacing vendorSha256 = "0sjjj9z1dhilhpc8pq4154czrb79z9cm044jvn75kxcjv6v5l2m5";
with vendorSha256 = null;

got build log for '/nix/store/74jh8dcwr486qyn8x306afd7apykwyw1-element-desktop' from 'daemon'
When evaluating attribute ‘element-desktop-wayland’:
warning: unused-argument
Unused argument: `paths`.
Near pkgs/build-support/trivial-builders/default.nix:475:7:

```
    |
475 |     , paths
    |       ^
```
</details>
</details>

**Review by gador — APPROVED** [review]

**Review by nim65s — APPROVED** [review]

**Comment by emilazy** [comment]
(Do we actually know that the Jitsi VOIP functionality in Element doesn’t use libolm for its E2E?)

**Comment by nim65s** [comment]
I think it depends on the jitsi server.
But right now, vodozemac is mentionned in https://jitsi.org/blog/a-stepping-stone-towards-end-to-end-encryption-on-mobile/ but nothing yet is in https://github.com/search?q=org%3Ajitsi+vodozemac&type=code

**Comment by emilazy** [comment]
Right, okay. I reported the libolm stuff to Jitsi’s security email when I found it in `jitsi-meet` but I haven’t yet received a reply. I couldn’t find any tracking issue for the server side of things, either. Thanks for the link to the blog post, but I guess nothing has happened in over two years.

I guess since it’s a server‐side thing we can just punt and say it’s not our problem here, but I wonder if the Element security team would like to know their users are still exposed to libolm after all…

**Comment by emilazy** [comment]
I’ve reported this to Element.

**Pull request merged**
