### PR TITLE
electron_30-bin: mark as insecure because it's EOL, electron-source.electron_30: remove as it's EOL

### PR DESCRIPTION
**Pull request by emilylange**
**I intend to merge this a week from now, `2024-10-30`, a day before ZHF (see #339153)**

---

A week or so too late but here we go:

This marks the binary variant of `electron_30` as insecure and removes the source build.

`electron_30` reached its end of life on `2024-10-15`, see <https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline>.

You may also want to see #335850 from a few weeks ago doing the same thing for `electron_29`.
It provides some context for how this usually works.
  
At any rate, the following packages are affected by this and need to move to some newer not-yet-EOL `electron` release:

* [x] antares: @hatch01 (#350627)
* [ ] bilibili: @jedsek @kashw2 @Bot-wxt1221
* [ ] deltachat-desktop: @dotlambda (https://github.com/NixOS/nixpkgs/pull/355575)
* [ ] lx-music-desktop: @oosquare
* [ ] morgen: @muscaln @justanotherariel (#350630)
* [x] teams-for-linux: @muscaln @qjoly @chvp @khaneliman (#350497)
* [x] webcord-vencord: @FlafyDev @NotAShelf (#350622)
* [x] ytmdesktop: @cjshearer (#351671)

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 350549`

---
### `x86_64-linux`

### CODE REVIEW

**Comment by NotAShelf** [comment]
Electron versions sure do get deprecated fast...

I'll take a look at Webcord soon.

**Comment by cjshearer** [comment]
@NovusTheory is ytmdesktop in a position to cut a release with its latest changes (notably, electron 33)?

**Comment by khaneliman** [comment]
I'll take a look at teams-for-linux, real quick.

**Comment by NovusTheory** [comment]
> @NovusTheory is ytmdesktop in a position to cut a release with its latest changes (notably, electron 33)?

@cjshearer I was mostly working on and waiting on some feature branches to be ready and merging everything in for a 2.1 release but I can look over getting a patch release of 2.0.6 pushed which can at least upgrade electron to 33 at minimum in the stable builds. Our dev branch already has the app updated to electron 33 so we should be ready in that sense.

**Comment by NotAShelf** [comment]
webcord-vencord bump in #350622. Really unfortunate that we must lag behind latest electron, but it is what it is.

**Comment by NotAShelf** [comment]
If nobody objects, I  can tackle the antares package as well - got some free time in my hands.

**Review by teutat3s — APPROVED** [review]
Thank you for taking care of this :raised_hands:

**Review by yayayayaka — APPROVED** [review]
thanks! :)

**Comment by emilylange** [comment]
> **I intend to merge this a week from now, `2024-10-30`, a day before ZHF (see #339153)**

This was supposed to be merged one day before restricting all breaking changes, but there was a typo in the announcement they changed yesterday.
Typos in stable release schedules are nothing new. 
It was a pretty obvious typo, which I probably should have noticed. But I didn't.

At any rate, this does place us right in the "restrict all breaking changes" phase since a few hours.

@RossComputerGuy feel free to merge this PR now, a few hours late, or over the span of the next few days.
Whenever you feel like it is the right time.

**Comment by emilazy** [comment]
Security trumps the freeze, I think this is fine.

**Comment by cjshearer** [comment]
[ytmdesktop PR](https://github.com/NixOS/nixpkgs/pull/351671) for updating ytmdesktop from 2.0.5 -> 2.0.6, which bumps electron from 30 -> 33.  

Thanks for the quick turnaround @NovusTheory!

**Comment by RossComputerGuy** [comment]
Result of `nixpkgs-review pr 350549` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>bilibili</li>
    <li>deltachat-desktop</li>
    <li>electron_30</li>
    <li>lx-music-desktop</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>antares</li>
    <li>teams-for-linux</li>
    <li>webcord-vencord</li>
    <li>ytmdesktop</li>
  </ul>
</details>

**Review by RossComputerGuy — APPROVED** [review]

**Comment by RossComputerGuy** [comment]
Will merge this on Wednesday.

**Review by yayayayaka — APPROVED** [review]
thanks!

EDIT: Oh, I already approved :laughing:

**Comment by dotlambda** [comment]
I'm trying to update deltachat-desktop (which includes a bump to a supported version of electron) in https://github.com/NixOS/nixpkgs/pull/355575 but I'm struggling with electron-builder. Help would be appreciated.

**Pull request merged**
