### PR TITLE
nixos/doc/manual: print context on failing xmllint validation

### PR DESCRIPTION
**Pull request by Profpatsch**
Previously only the line numbers of a giant, internally generated XML file were
printed, without any kind of debuggability.
Now at least the mentioned lines are printed with a little bit of surrounding
context (to have something to grep for).

```
manual-combined.xml:4863: element para: Relax-NG validity error : Did not expect element para there
  4859	<chapter xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xi="http://www.w3.org/2001/XInclude" version="5.0" xml:id="sec-writing-modules">
  4860
  4861	<title>Writing NixOS Modules</title>
  4862
  4863	<para>NixOS has a modular system for declarative configuration.  This
  4864	system combines multiple <emphasis>modules</emphasis> to produce the
  4865	full system configuration.  One of the modules that constitute the
```

### CODE REVIEW

**Comment by Profpatsch** [comment]
Update: added comments, print to stderr like the original xmllint output.

**Comment by grahamc** [comment]
I love the output, I don't love that we have to do it ourselves. Can you think of an easy way to apply this to the nixpkgs docs too?

**Comment by Profpatsch** [comment]
> I love the output, I don't love that we have to do it ourselves.
Sure; on the other hand they use a pretty standard format for error messages (`file:linenumber`).

> Can you think of an easy way to apply this to the nixpkgs docs too?

Should be possible, but we already use `jing` for that it seems?
```
    xmllint --nonet --xinclude --noxincludenode manual.xml --output manual-full.xml
    ${pkgs.jing}/bin/jing ${pkgs.docbook5}/xml/rng/docbook/docbook.rng manual-full.xml
```
afaik that gives better output.

**Comment by Profpatsch** [comment]
@grahamc Do you think we can merge?

**Comment by grahamc** [comment]
Yes

**Pull request merged**
