### PR TITLE
ansible_2_16: init at 2.16.2; ansible_2_13: remove

### PR DESCRIPTION
**Pull request by natsukium**
## Description of changes

closes #274366

Diff: https://github.com/ansible/ansible/compare/v2.15.5...v2.16.2

Changelog: https://github.com/ansible/ansible/blob/v2.16.2/changelogs/CHANGELOG-v2.16.rst

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 277719` at 32cf1b2f run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/natsukium/291d3ce539472b81e26ba8f66f421ae3">python310Packages.pytest-ansible</a></li>
    <li><a href="https://gist.github.com/natsukium/07883dc01df843f891ed3f16af01a826">python311Packages.pytest-ansible</a></li>
  </ul>
</details>
<details>
  <summary>18 packages built successfully:</summary>
  <ul>
    <li>ansible (python311Packages.ansible-core)</li>
    <li>ansible-later</li>
    <li>ansible-lint</li>
    <li>ansible_2_15</li>
    <li>kargo</li>
    <li>molecule (python311Packages.molecule)</li>
    <li>python310Packages.ansible-compat</li>
    <li>python310Packages.ansible-core</li>
    <li>python310Packages.ansible-kernel</li>
    <li>python310Packages.ansible-runner</li>
    <li>python310Packages.ansible-vault-rw</li>
    <li>python310Packages.molecule</li>
    <li>python310Packages.pytest-testinfra</li>
    <li>python311Packages.ansible-compat</li>
    <li>python311Packages.ansible-kernel</li>
    <li>python311Packages.ansible-runner</li>
    <li>python311Packages.ansible-vault-rw</li>
    <li>python311Packages.pytest-testinfra</li>
  </ul>
</details>

**Comment by kirillrdy** [comment]
Result of `nixpkgs-review pr 277719` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python310Packages.pytest-ansible</li>
    <li>python310Packages.pytest-ansible.dist</li>
    <li>python311Packages.pytest-ansible</li>
    <li>python311Packages.pytest-ansible.dist</li>
  </ul>
</details>
<details>
  <summary>34 packages built:</summary>
  <ul>
    <li>ansible (ansible_2_16 ,python311Packages.ansible-core)</li>
    <li>ansible-later</li>
    <li>ansible-later.dist</li>
    <li>ansible-lint</li>
    <li>ansible-lint.dist</li>
    <li>ansible.dist (ansible_2_16.dist ,python311Packages.ansible-core.dist)</li>
    <li>kargo</li>
    <li>kargo.dist</li>
    <li>molecule (python311Packages.molecule)</li>
    <li>molecule.dist (python311Packages.molecule.dist)</li>
    <li>python310Packages.ansible-compat</li>
    <li>python310Packages.ansible-compat.dist</li>
    <li>python310Packages.ansible-core</li>
    <li>python310Packages.ansible-core.dist</li>
    <li>python310Packages.ansible-kernel</li>
    <li>python310Packages.ansible-kernel.dist</li>
    <li>python310Packages.ansible-runner</li>
    <li>python310Packages.ansible-runner.dist</li>
    <li>python310Packages.ansible-vault-rw</li>
    <li>python310Packages.ansible-vault-rw.dist</li>
    <li>python310Packages.molecule</li>
    <li>python310Packages.molecule.dist</li>
    <li>python310Packages.pytest-testinfra</li>
    <li>python310Packages.pytest-testinfra.dist</li>
    <li>python311Packages.ansible-compat</li>
    <li>python311Packages.ansible-compat.dist</li>
    <li>python311Packages.ansible-kernel</li>
    <li>python311Packages.ansible-kernel.dist</li>
    <li>python311Packages.ansible-runner</li>
    <li>python311Packages.ansible-runner.dist</li>
    <li>python311Packages.ansible-vault-rw</li>
    <li>python311Packages.ansible-vault-rw.dist</li>
    <li>python311Packages.pytest-testinfra</li>
    <li>python311Packages.pytest-testinfra.dist</li>
  </ul>
</details>

**Comment by kirillrdy** [comment]
@natsukium ansible is not maintained, so i think we can merge, and fix whatever fallout happens

**Comment by natsukium** [comment]
@kirillrdy thanks for checking.
I'm not sure why pytest-ansible is failing, but looking at the tests that have already been disabled, I guess it's not working very well.
I disabled the failing tests to update and remove ansible.

**Pull request merged**
