### PR TITLE
Merge pull request #77608 from phi-gamma/olm-remove-typing

### PR DESCRIPTION
**Pull request by phi-gamma**
Typing has been upstreamed into CPython and will cause errors
if loaded with a 3.7 interpreter. Cf.
https://github.com/python/typing/issues/573

Olm works without typing as tested via weechat-matrix.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions (Fedora 31)
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build python3Packages.python-olm python2Packages.python-olm

**Comment by phi-gamma** [comment]
@Mic92: I had no idea Python2 was still a thing on nixos. That one I didn’t
test at all. weechat builds against Python3 so it’s fine, dunno about other
downstream olm users though.

**Comment by Mic92** [comment]
I would say either mark disable the python2 build `disabled = !isPy3k;` or include typing conditionally for python2, if python2 is still supported by this library and including `typing` make the build fixed.

**Comment by phi-gamma** [comment]
Skimming the other users of libolm I couldn’t figure out whether
they still supported py2 so I made *typing* depend on py2 as
per your suggestion.

**Comment by Mic92** [comment]
@GrahamcOfBorg build python3Packages.python-olm python2Packages.python-olm

**Comment by phi-gamma** [comment]
Thanks, that was really fast!

**Pull request merged**
