### PR TITLE
bpftrace: 0.16.0 -> 0.17.0

### PR DESCRIPTION
**Pull request by mmisono**
###### Description of changes

bpftrace [v0.17.0 (release note)](https://github.com/iovisor/bpftrace/releases/tag/v0.17.0). This includes BTF support for kernel modules.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

I tested this on NixOS 22.11 with BTF support.

### CODE REVIEW

**Comment by martinetd** [comment]
Thanks for the update!
I've tested bpftrace 0.17 manually as well, doesn't look like there is any problem.

It'd be great to add a test for BTF modules though now bpftrace supports it -- could you cherry-pick the top commit of https://github.com/martinetd/nixpkgs/commits/bpftrace_btf_module ?

**Comment by mmisono** [comment]
Sure, I cherry-pick-ed and also the test passed on my environment.

**Review by martinetd — APPROVED** [review]
Thanks! looks good to me assuming ofborg tests pass (which they should given we both ran it, but you never know..)

**Review by thoughtpolice — APPROVED** [review]

**Comment by martinetd** [comment]
The test didn't pass on aarch64 (not much details, "machine # ERROR: Error attaching probe: kfunc:nf_tables:nft_trans_alloc_gfp"...), so much for assuming the VM environment would be similar enough...

I don't have any powerful aarch64 machine so it'll take a while to reproduce (I don't even know if this board can run qemu in our test configuration... probably if I figure how to disable kvm...); might want to revert my extra check if it becomes a problem.

**Comment by martinetd** [comment]
So I can run qemu (without kvm is a disaster of timeouts, but recompiling my kernel with kvm enabled and it's actually useable), struggling to upgrade bpftrace because barely 1GB of ram isn't enough when nix itself takes over 500MB... and could reproduce alright.

It looks like a problem with kfuncs in general ; I've opened https://github.com/iovisor/bpftrace/issues/2496

I've opened https://github.com/NixOS/nixpkgs/pull/214485 to disable the test on aarch64 until that is fixed.

**Pull request merged**
