### PR TITLE
python311Packages.vivisect: 1.1.0 -> 1.1.1, python311Packages.viv-utils: 0.7.7 -> 0.7.9

### PR DESCRIPTION
**Pull request by fabaff**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 229997` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages failed to build:</summary>
  <ul>
    <li>peering-manager</li>
    <li>python310Packages.django-cacheops</li>
    <li>python310Packages.django-cacheops.dist</li>
    <li>python311Packages.django-cacheops</li>
    <li>python311Packages.django-cacheops.dist</li>
    <li>python311Packages.dvclive</li>
    <li>python311Packages.dvclive.dist</li>
  </ul>
</details>
<details>
  <summary>50 packages built:</summary>
  <ul>
    <li>boofuzz</li>
    <li>boofuzz.dist</li>
    <li>dvc</li>
    <li>dvc-with-remotes</li>
    <li>dvc-with-remotes.dist</li>
    <li>dvc.dist</li>
    <li>flare-floss</li>
    <li>flare-floss.dist</li>
    <li>python310Packages.dvc-data</li>
    <li>python310Packages.dvc-data.dist</li>
    <li>python310Packages.dvc-gs</li>
    <li>python310Packages.dvc-gs.dist</li>
    <li>python310Packages.dvc-http</li>
    <li>python310Packages.dvc-http.dist</li>
    <li>python310Packages.dvc-objects</li>
    <li>python310Packages.dvc-objects.dist</li>
    <li>python310Packages.dvc-render</li>
    <li>python310Packages.dvc-render.dist</li>
    <li>python310Packages.dvc-task</li>
    <li>python310Packages.dvc-task.dist</li>
    <li>python310Packages.dvclive</li>
    <li>python310Packages.dvclive.dist</li>
    <li>python310Packages.funcy</li>
    <li>python310Packages.funcy.dist</li>
    <li>python310Packages.scmrepo</li>
    <li>python310Packages.scmrepo.dist</li>
    <li>python310Packages.viv-utils</li>
    <li>python310Packages.viv-utils.dist</li>
    <li>python310Packages.vivisect</li>
    <li>python310Packages.vivisect.dist</li>
    <li>python311Packages.dvc-data</li>
    <li>python311Packages.dvc-data.dist</li>
    <li>python311Packages.dvc-gs</li>
    <li>python311Packages.dvc-gs.dist</li>
    <li>python311Packages.dvc-http</li>
    <li>python311Packages.dvc-http.dist</li>
    <li>python311Packages.dvc-objects</li>
    <li>python311Packages.dvc-objects.dist</li>
    <li>python311Packages.dvc-render</li>
    <li>python311Packages.dvc-render.dist</li>
    <li>python311Packages.funcy</li>
    <li>python311Packages.funcy.dist</li>
    <li>python311Packages.scmrepo</li>
    <li>python311Packages.scmrepo.dist</li>
    <li>python311Packages.viv-utils</li>
    <li>python311Packages.viv-utils.dist</li>
    <li>python311Packages.vivisect</li>
    <li>python311Packages.vivisect.dist</li>
    <li>vivisect</li>
    <li>vivisect.dist</li>
  </ul>
</details>

**Comment by risicle** [comment]
@ofborg build python310Packages.django-cacheops

Expects `funcy` < 2.0

**Comment by fabaff** [comment]
> Expects funcy < 2.0

https://github.com/Suor/django-cacheops/issues/454

**Comment by onny** [comment]
> > Expects funcy < 2.0
> 
> [Suor/django-cacheops#454](https://github.com/Suor/django-cacheops/issues/454)

Looks like it got already fixed :)

**Comment by fabaff** [comment]
`django-cacheops` tests are not passing for me with the latest `funcy`.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 229997` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages marked as broken and skipped:</summary>
  <ul>
    <li>peering-manager</li>
    <li>python310Packages.django-cacheops</li>
    <li>python310Packages.django-cacheops.dist</li>
    <li>python311Packages.django-cacheops</li>
    <li>python311Packages.django-cacheops.dist</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python311Packages.dvclive</li>
    <li>python311Packages.dvclive.dist</li>
  </ul>
</details>
<details>
  <summary>62 packages built:</summary>
  <ul>
    <li>boofuzz</li>
    <li>boofuzz.dist</li>
    <li>dvc</li>
    <li>dvc-with-remotes</li>
    <li>dvc-with-remotes.dist</li>
    <li>dvc.dist</li>
    <li>flare-floss</li>
    <li>flare-floss.dist</li>
    <li>python310Packages.dvc-azure</li>
    <li>python310Packages.dvc-azure.dist</li>
    <li>python310Packages.dvc-data</li>
    <li>python310Packages.dvc-data.dist</li>
    <li>python310Packages.dvc-gs</li>
    <li>python310Packages.dvc-gs.dist</li>
    <li>python310Packages.dvc-http</li>
    <li>python310Packages.dvc-http.dist</li>
    <li>python310Packages.dvc-objects</li>
    <li>python310Packages.dvc-objects.dist</li>
    <li>python310Packages.dvc-render</li>
    <li>python310Packages.dvc-render.dist</li>
    <li>python310Packages.dvc-s3</li>
    <li>python310Packages.dvc-s3.dist</li>
    <li>python310Packages.dvc-ssh</li>
    <li>python310Packages.dvc-ssh.dist</li>
    <li>python310Packages.dvc-task</li>
    <li>python310Packages.dvc-task.dist</li>
    <li>python310Packages.dvclive</li>
    <li>python310Packages.dvclive.dist</li>
    <li>python310Packages.funcy</li>
    <li>python310Packages.funcy.dist</li>
    <li>python310Packages.scmrepo</li>
    <li>python310Packages.scmrepo.dist</li>
    <li>python310Packages.viv-utils</li>
    <li>python310Packages.viv-utils.dist</li>
    <li>python310Packages.vivisect</li>
    <li>python310Packages.vivisect.dist</li>
    <li>python311Packages.dvc-azure</li>
    <li>python311Packages.dvc-azure.dist</li>
    <li>python311Packages.dvc-data</li>
    <li>python311Packages.dvc-data.dist</li>
    <li>python311Packages.dvc-gs</li>
    <li>python311Packages.dvc-gs.dist</li>
    <li>python311Packages.dvc-http</li>
    <li>python311Packages.dvc-http.dist</li>
    <li>python311Packages.dvc-objects</li>
    <li>python311Packages.dvc-objects.dist</li>
    <li>python311Packages.dvc-render</li>
    <li>python311Packages.dvc-render.dist</li>
    <li>python311Packages.dvc-s3</li>
    <li>python311Packages.dvc-s3.dist</li>
    <li>python311Packages.dvc-ssh</li>
    <li>python311Packages.dvc-ssh.dist</li>
    <li>python311Packages.funcy</li>
    <li>python311Packages.funcy.dist</li>
    <li>python311Packages.scmrepo</li>
    <li>python311Packages.scmrepo.dist</li>
    <li>python311Packages.viv-utils</li>
    <li>python311Packages.viv-utils.dist</li>
    <li>python311Packages.vivisect</li>
    <li>python311Packages.vivisect.dist</li>
    <li>vivisect</li>
    <li>vivisect.dist</li>
  </ul>
</details>

**Pull request merged**
