### PR TITLE
netcdf: 4.7.4 -> 4.8.0

### PR DESCRIPTION
**Pull request by nh2**
###### Motivation for this change

Hopefully fixes aarch65: #115788 (see https://github.com/NixOS/nixpkgs/issues/115788#issuecomment-900506112)

Changelog: https://github.com/Unidata/netcdf-c/releases/tag/v4.8.0

###### TODO

* [x] ~Based on PR #134436, merge that first.~ I merged this one instead.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nh2** [comment]
@GrahamcOfBorg build netcdf

To see if the `aarch64` build is fixed by this.

**Comment by nh2** [comment]
`nixpkgs-review` results:

```
% NIX_PATH=nixpkgs=. nixpkgs-review rev HEAD
$ git -c fetch.prune=false fetch --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0
remote: Enumerating objects: 459, done.
remote: Counting objects: 100% (297/297), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 459 (delta 291), reused 290 (delta 290), pack-reused 162
Receiving objects: 100% (459/459), 182.63 KiB | 9.61 MiB/s, done.
Resolving deltas: 100% (303/303), completed with 99 local objects.
From https://github.com/NixOS/nixpkgs
   6bb9ad36c52..170ea681e58  master     -> refs/nixpkgs-review/0
$ git worktree add /home/niklas/.cache/nixpkgs-review/rev-1522e69a68336395b60a9abb351c918a5f1904db/nixpkgs 170ea681e5807e81788e924b8259d2a08be4b48a
Preparing worktree (detached HEAD 170ea681e58)
Updating files: 100% (27439/27439), done.
HEAD is now at 170ea681e58 Merge pull request #134462 from r-ryantm/auto-update/pt2-clone
$ nix-env --option system x86_64-linux -f /home/niklas/.cache/nixpkgs-review/rev-1522e69a68336395b60a9abb351c918a5f1904db/nixpkgs -qaP --xml --out-path --show-trace
$ git merge --no-commit --no-ff 1522e69a68336395b60a9abb351c918a5f1904db
Auto-merging pkgs/top-level/all-packages.nix
Automatic merge went well; stopped before committing as requested
$ nix-env --option system x86_64-linux -f /home/niklas/.cache/nixpkgs-review/rev-1522e69a68336395b60a9abb351c918a5f1904db/nixpkgs -qaP --xml --out-path --show-trace --meta
94 packages updated:
bicgl-unstable bicpl-unstable cdo cloudcompare conglomerate-unstable EBTKS-unstable eccodes eccodes eccodes EZminc-unstable gdal gdal gdal gdal gmt gplates grib-api inormalize libLAS libminc-unstable mapnik MapProxy merkaartor minc-tools-unstable minc-widgets mni_autoreg-unstable mod_tile-unstable N3-unstable nco ncview netcdf (4.7.4 → 4.8.0) netcdf-cxx4 netcdf-fortran netcdf-mpi (4.7.4 → 4.8.0) octave octave octopus oobicpl-unstable OpenOrienteering-Mapper openspace osmscout-server ovito paraview pdal (2.2.0 → 2.3.0) perl5.32.1-Tirex perl5.34.0-Tirex postgis postgis postgis postgis python3.8-arviz python3.8-BoltzTraP2 python3.8-cartopy python3.8-datashader python3.8-Fiona python3.8-geopandas python3.8-h5netcdf python3.8-meshio python3.8-netCDF4 python3.8-osmnx python3.8-pygmt python3.8-pymc3 python3.8-python-mapnik-unstable python3.8-rasterio python3.8-sfepy python3.8-sunpy python3.8-worldengine python3.8-wrf-python python3.9-arviz python3.9-BoltzTraP2 python3.9-cartopy python3.9-datashader python3.9-Fiona python3.9-geopandas python3.9-h5netcdf python3.9-meshio python3.9-netCDF4 python3.9-osmnx python3.9-pygmt python3.9-pymc3 python3.9-python-mapnik-unstable python3.9-rasterio python3.9-sfepy python3.9-sunpy python3.9-worldengine python3.9-wrf-python pytrainer qgis qgis-unwrapped qlandkartegt qmapshack saga sumo udig

$ nix --experimental-features nix-command build --no-link --keep-going --option build-use-sandbox relaxed -f /home/niklas/.cache/nixpkgs-review/rev-1522e69a68336395b60a9abb351c918a5f1904db/build.nix --builders @@/home/niklas/Sync/config/nix-remote-builders-benaco --option extra-substituters ssh://nix-store-user@corp2.benaco.biz ssh://static-haskell-nix-ci --option builders-use-substitutes true --max-jobs 0
error: unable to start any build; either increase '--max-jobs' or enable remote builds.
       https://nixos.org/nix/manual/#chap-distributed-builds
5 packages marked as broken and skipped:
openspace python38Packages.arviz python38Packages.pymc3 python39Packages.arviz python39Packages.pymc3

82 packages failed to build:
EBTKS apacheHttpdPackages.mod_tile bicgl bicpl cdo conglomerate eccodes ezminc gdal_2 gmt gplates grib-api inormalize libminc mapnik mapproxy merkaartor minc_tools minc_widgets mni_autoreg n3 nco ncview netcdf-mpi netcdfcxx4 netcdffortran octavePackages.ncarray octavePackages.netcdf octopus oobicpl openorienteering-mapper osmscout-server ovito paraview perl532Packages.Tirex perl534Packages.Tirex postgis postgresql11Packages.postgis postgresql12Packages.postgis python38Packages.boltztrap2 python38Packages.cartopy python38Packages.datashader python38Packages.eccodes python38Packages.fiona python38Packages.gdal python38Packages.geopandas python38Packages.h5netcdf python38Packages.meshio python38Packages.netcdf4 python38Packages.osmnx python38Packages.pygmt python38Packages.python-mapnik python38Packages.rasterio python38Packages.sfepy python38Packages.sunpy python38Packages.worldengine python38Packages.wrf-python python39Packages.boltztrap2 python39Packages.cartopy python39Packages.datashader python39Packages.eccodes python39Packages.fiona python39Packages.geopandas python39Packages.h5netcdf python39Packages.meshio python39Packages.netcdf4 python39Packages.osmnx python39Packages.pygmt python39Packages.python-mapnik python39Packages.rasterio python39Packages.sfepy python39Packages.sunpy python39Packages.worldengine python39Packages.wrf-python pytrainer qgis qgis-unwrapped qlandkartegt qmapshack saga sumo udig

5 packages built:
cloudcompare gdal libLAS netcdf pdal
```

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 134512` at 4826412f run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages marked as broken and skipped:</summary>
  <ul>
    <li>grass</li>
    <li>python38Packages.datashader</li>
    <li>python38Packages.pygmt</li>
    <li>python39Packages.datashader</li>
    <li>python39Packages.pygmt</li>
    <li>qlandkartegt</li>
  </ul>
</details>
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/b57525e74b49ff1282b8133aecafd7f9">openspace</a></li>
    <li><a href="https://gist.github.com/afd53187f733c82ebac2807b7670d042">python39Packages.cartopy</a></li>
    <li><a href="https://gist.github.com/f8c1c5eb7b996486c94e5dc9eca15e0d">python39Packages.fiona</a></li>
    <li><a href="https://gist.github.com/17ff73c8ec95df710478af8cb649fedf">python39Packages.geopandas</a></li>
  </ul>
</details>
<details>
  <summary>47 packages skipped due to time constraints:</summary>
  <ul>
    <li>apacheHttpdPackages.mod_tile (apacheHttpdPackages_2_4.mod_tile)</li>
    <li>cdo</li>
    <li>cloudcompare</li>
    <li>eccodes</li>
    <li>ezminc</li>
    <li>gdal_2</li>
    <li>gplates</li>
    <li>libLAS</li>
    <li>mapnik</li>
    <li>merkaartor</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>28 packages built successfully:</summary>
  <ul>
    <li>EBTKS</li>
    <li>bicgl</li>
    <li>bicpl</li>
    <li>conglomerate</li>
    <li>gdal (python39Packages.gdal)</li>
    <li>grib-api</li>
    <li>inormalize</li>
    <li>libminc</li>
    <li>mapproxy</li>
    <li>minc_tools</li>
    <li>minc_widgets</li>
    <li>mni_autoreg</li>
    <li>n3</li>
    <li>netcdf</li>
    <li>netcdf-mpi</li>
    <li>netcdfcxx4</li>
    <li>oobicpl</li>
    <li>python38Packages.boltztrap2</li>
    <li>python38Packages.h5netcdf</li>
    <li>python38Packages.meshio</li>
    <li>python38Packages.netcdf4</li>
    <li>python38Packages.wrf-python</li>
    <li>python39Packages.boltztrap2</li>
    <li>python39Packages.h5netcdf</li>
    <li>python39Packages.meshio</li>
    <li>python39Packages.netcdf4</li>
    <li>python39Packages.wrf-python</li>
    <li>pytrainer</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Review by rmcgibbo — APPROVED** [review]
Based on the bot results on aarch64, this looks pretty promising to me.

**Comment by nh2** [comment]
Corrected `nixpkgs-review` results on `x86_64` suggest only 1 new build failure:

* `python38Packages.datashader`

Details:

```
error: build of '/nix/store/q26l6wdzgr4ydf2d7h0wh62524wvd75s-python3.8-pytest-astropy-0.8.0.drv' on 'ssh://root@...' failed: builder for '/nix/store/q26l6wdzgr4ydf2d7h0wh62524wvd75s-python3.8-pytest-astropy-0.8.0.drv' failed with exit code 5
error: builder for '/nix/store/q26l6wdzgr4ydf2d7h0wh62524wvd75s-python3.8-pytest-astropy-0.8.0.drv' failed with exit code 1;
       last 10 log lines:
       > pytestCheckPhase
       > Executing pytestCheckPhase
       > ============================= test session starts ==============================
       > platform linux -- Python 3.8.11, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
       > rootdir: /build/pytest-astropy-0.8.0
       > plugins: hypothesis-6.14.0, astropy-header-0.1.2, doctestplus-0.9.0, filter-subpackage-0.1.1, cov-2.12.1, remotedata-0.3.2, openfiles-0.5.0, arraydiff-0.3
       > collected 0 items
       >
       > ============================ no tests ran in 0.02s =============================
       > builder for '/nix/store/q26l6wdzgr4ydf2d7h0wh62524wvd75s-python3.8-pytest-astropy-0.8.0.drv' failed with exit code 5
       For full logs, run 'nix log /nix/store/q26l6wdzgr4ydf2d7h0wh62524wvd75s-python3.8-pytest-astropy-0.8.0.drv'.
error: 1 dependencies of derivation '/nix/store/p5sf2i6ka9v08kl7flv3kxx9p7l0azig-python3.8-asdf-2.8.1.drv' failed to build
error: 2 dependencies of derivation '/nix/store/g4lkmnp1cjhj2c85nw591vkga31sjvjj-python3.8-sunpy-3.0.1.drv' failed to build
error: build of '/nix/store/bfy0wn62snv1qqbhcrrakjaf4xvhcf8d-python3.9-pytest-astropy-0.8.0.drv' on 'ssh://root@...' failed: builder for '/nix/store/bfy0wn62snv1qqbhcrrakjaf4xvhcf8d-python3.9-pytest-astropy-0.8.0.drv' failed with exit code 5
error: builder for '/nix/store/bfy0wn62snv1qqbhcrrakjaf4xvhcf8d-python3.9-pytest-astropy-0.8.0.drv' failed with exit code 1;
       last 10 log lines:
       > pytestCheckPhase
       > Executing pytestCheckPhase
       > ============================= test session starts ==============================
       > platform linux -- Python 3.9.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
       > rootdir: /build/pytest-astropy-0.8.0
       > plugins: hypothesis-6.14.0, astropy-header-0.1.2, doctestplus-0.9.0, filter-subpackage-0.1.1, cov-2.12.1, remotedata-0.3.2, openfiles-0.5.0, arraydiff-0.3
       > collected 0 items
       >
       > ============================ no tests ran in 0.02s =============================
       > builder for '/nix/store/bfy0wn62snv1qqbhcrrakjaf4xvhcf8d-python3.9-pytest-astropy-0.8.0.drv' failed with exit code 5
       For full logs, run 'nix log /nix/store/bfy0wn62snv1qqbhcrrakjaf4xvhcf8d-python3.9-pytest-astropy-0.8.0.drv'.
error: 1 dependencies of derivation '/nix/store/wsznzwjfv53ldf5dhk0l7689wmxfxglp-python3.9-asdf-2.8.1.drv' failed to build
error: 2 dependencies of derivation '/nix/store/qlsb0y9199da4j19xr02hyypd9bw3qfw-python3.9-sunpy-3.0.1.drv' failed to build
[21/0/39 built (2 failed), 5 copied (23.6 MiB), 9.1 MiB DL] building gplates-2.2.0 on ssh:[21/0/39 built (2 failed), 5 copied (23.6 MiB)error: build of '/nix/store/ad5rfbz3g0nd2mvjgd6d1b84yxbqp626-python3.8-datashader-0.13.0.drv' on 'ssh://...' failed: builder for '/nix/store/ad5rfbz3g0nd2mvjgd6d1b84yxbqp626-python3.8-datashader-0.13.0.drv' failed with exit code 1
error: builder for '/nix/store/ad5rfbz3g0nd2mvjgd6d1b84yxbqp626-python3.8-datashader-0.13.0.drv' failed with exit code 1;
       last 10 log lines:
       >
       > datashader/tests/test_xarray.py: 24 warnings
       >   /build/datashader-0.13.0/datashader/core.py:1185: PendingDeprecationWarning: dropping variables using `drop` will be deprecated; using drop_vars is encouraged.
       >     source = source.drop([col for col in columns if col not in cols_to_keep])
       >
       > -- Docs: https://docs.pytest.org/en/stable/warnings.html
       > =========================== short test summary info ============================
       > FAILED datashader/tests/test_quadmesh.py::test_raster_quadmesh_autorange_reversed[dask.array]
       > ===== 1 failed, 409 passed, 36 skipped, 105 warnings in 122.20s (0:02:02) ======
       > builder for '/nix/store/ad5rfbz3g0nd2mvjgd6d1b84yxbqp626-python3.8-datashader-0.13.0.drv' failed with exit code 1
       For full logs, run 'nix log /nix/store/ad5rfbz3g0nd2mvjgd6d1b84yxbqp626-python3.8-datashader-0.13.0.drv'.
error: 3 dependencies of derivation '/nix/store/yd6h6gfhabpr7zi8ahfz7jwsahmgv7nc-env.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rz3zbw3kvjdyks6w7syf0s7kgzf966w0-review-shell.drv' failed to build

5 packages marked as broken and skipped:
openspace python38Packages.arviz python38Packages.pymc3 python39Packages.arviz python39Packages.pymc3

3 packages failed to build:
python38Packages.datashader python38Packages.sunpy python39Packages.sunpy

84 packages built:
EBTKS apacheHttpdPackages.mod_tile bicgl bicpl cdo cloudcompare conglomerate eccodes ezminc gdal gdal_2 gmt gplates grib-api inormalize libLAS libminc mapnik mapproxy merkaartor minc_tools minc_widgets mni_autoreg n3 nco ncview netcdf netcdf-mpi netcdfcxx4 netcdffortran octavePackages.ncarray octavePackages.netcdf octopus oobicpl openorienteering-mapper osmscout-server ovito paraview pdal perl532Packages.Tirex perl534Packages.Tirex postgis postgresql11Packages.postgis postgresql12Packages.postgis python38Packages.boltztrap2 python38Packages.cartopy python38Packages.eccodes python38Packages.fiona python38Packages.gdal python38Packages.geopandas python38Packages.h5netcdf python38Packages.meshio python38Packages.netcdf4 python38Packages.osmnx python38Packages.pygmt python38Packages.python-mapnik python38Packages.rasterio python38Packages.sfepy python38Packages.worldengine python38Packages.wrf-python python39Packages.boltztrap2 python39Packages.cartopy python39Packages.datashader python39Packages.eccodes python39Packages.fiona python39Packages.geopandas python39Packages.h5netcdf python39Packages.meshio python39Packages.netcdf4 python39Packages.osmnx python39Packages.pygmt python39Packages.python-mapnik python39Packages.rasterio python39Packages.sfepy python39Packages.worldengine python39Packages.wrf-python pytrainer qgis qgis-unwrapped qlandkartegt qmapshack saga sumo udig
```

Result _before_ this PR (triggered with just a newline change in `netcdf`'s build scripts:

```
error: build of '/nix/store/bfy0wn62snv1qqbhcrrakjaf4xvhcf8d-python3.9-pytest-astropy-0.8.0.drv' on 'ssh://root@gpu-...' failed: builder for '/nix/store/bfy0wn62snv1qqbhcrrakjaf4xvhcf8d-python3.9-pytest-astropy-0.8.0.drv' failed with exit code 5
error: builder for '/nix/store/bfy0wn62snv1qqbhcrrakjaf4xvhcf8d-python3.9-pytest-astropy-0.8.0.drv' failed with exit code 1;
       last 10 log lines:
       > pytestCheckPhase
       > Executing pytestCheckPhase
       > ============================= test session starts ==============================
       > platform linux -- Python 3.9.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
       > rootdir: /build/pytest-astropy-0.8.0
       > plugins: hypothesis-6.14.0, astropy-header-0.1.2, doctestplus-0.9.0, filter-subpackage-0.1.1, cov-2.12.1, remotedata-0.3.2, openfiles-0.5.0, arraydiff-0.3
       > collected 0 items
       >
       > ============================ no tests ran in 0.01s =============================
       > builder for '/nix/store/bfy0wn62snv1qqbhcrrakjaf4xvhcf8d-python3.9-pytest-astropy-0.8.0.drv' failed with exit code 5
       For full logs, run 'nix log /nix/store/bfy0wn62snv1qqbhcrrakjaf4xvhcf8d-python3.9-pytest-astropy-0.8.0.drv'.
error: 1 dependencies of derivation '/nix/store/wsznzwjfv53ldf5dhk0l7689wmxfxglp-python3.9-asdf-2.8.1.drv' failed to build
error: build of '/nix/store/q26l6wdzgr4ydf2d7h0wh62524wvd75s-python3.8-pytest-astropy-0.8.0.drv' on 'ssh://root@ram256g-...' failed: builder for '/nix/store/q26l6wdzgr4ydf2d7h0wh62524wvd75s-python3.8-pytest-astropy-0.8.0.drv' failed with exit code 5
error: builder for '/nix/store/q26l6wdzgr4ydf2d7h0wh62524wvd75s-python3.8-pytest-astropy-0.8.0.drv' failed with exit code 1;
       last 10 log lines:
       > pytestCheckPhase
       > Executing pytestCheckPhase
       > ============================= test session starts ==============================
       > platform linux -- Python 3.8.11, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
       > rootdir: /build/pytest-astropy-0.8.0
       > plugins: hypothesis-6.14.0, astropy-header-0.1.2, doctestplus-0.9.0, filter-subpackage-0.1.1, cov-2.12.1, remotedata-0.3.2, openfiles-0.5.0, arraydiff-0.3
       > collected 0 items
       >
       > ============================ no tests ran in 0.01s =============================
       > builder for '/nix/store/q26l6wdzgr4ydf2d7h0wh62524wvd75s-python3.8-pytest-astropy-0.8.0.drv' failed with exit code 5
       For full logs, run 'nix log /nix/store/q26l6wdzgr4ydf2d7h0wh62524wvd75s-python3.8-pytest-astropy-0.8.0.drv'.
error: 1 dependencies of derivation '/nix/store/p5sf2i6ka9v08kl7flv3kxx9p7l0azig-python3.8-asdf-2.8.1.drv' failed to build
[2/4/95 built (2 failed), 4 copied (1.5 MiB), 0.0 MiB DL] building netcdf-4.7.4 on ssh://root@...: /nix/store/can473ld4dc8izcjlm4i5daxsh1yl5d8-bash-4.4-p23/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I../include -I../oc2    -error: 2 dependencies of derivation '/nix/store/6610ag91xxxhz2r975bji4vkl0j72g7j-python3.8-sunpy-3.0.1.drv' failed to build
error: 2 dependencies of derivation '/nix/store/qmv4v4h8ikrl0r7whzblwawwjfc9ksda-python3.9-sunpy-3.0.1.drv' failed to build
[7/45/93 built (2 failed), 68 copied (959.6 MiB), 0.0 MiB DL] building gdal-3.2.2 on ssh:/[2/53/93 built (2 failed), 83 copied (1110.2 M[2/53/93 built (2 failed), 83 copied (1110.2 MiB), 0.0 MiB DL] building ovito-3.4.0 on ssh://root@gpu-...: [ 94%] Building CX[2error: 2 dependencies of derivation '/nix/store/kyszljsfrpdnp7dfxgqjd7cskajciyg6-env.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1ak5nm3nyfax7fkck46k4yx1l11g3hhf-review-shell.drv' failed to build

5 packages marked as broken and skipped:
openspace python38Packages.arviz python38Packages.pymc3 python39Packages.arviz python39Packages.pymc3

2 packages failed to build:
python38Packages.sunpy python39Packages.sunpy
```

**Comment by nh2** [comment]
> Corrected `nixpkgs-review` results on `x86_64` suggest only 1 new build failure:
> 
>     * `python38Packages.datashader`

CC maintainer @costrouc

**Comment by rmcgibbo** [comment]
This seems like a net benefit. It has my :+1: as-is.

**Comment by nh2** [comment]
The failure is:

```
=========================== short test summary info ============================
FAILED datashader/tests/test_quadmesh.py::test_raster_quadmesh_autorange_reversed[dask.array]
====== 1 failed, 409 passed, 36 skipped, 105 warnings in 71.16s (0:01:11) ======
builder for '/nix/store/ad5rfbz3g0nd2mvjgd6d1b84yxbqp626-python3.8-datashader-0.13.0.drv' failed with exit code 1
```

with details:

```
============================= test session starts ==============================
platform linux -- Python 3.8.11, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /build/datashader-0.13.0
plugins: xdist-2.3.0, forked-1.3.0, nbsmoke-0.5.0
gw0 [444] / gw1 [444] / gw2 [444] / gw3 [444] / gw4 [444] / gw5 [444] / gw6 [444] / gw7 [444] / gw8 [444] / gw9 [444] / gw10 [444] / gw11 [444] / gw12 [444] / gw13 [444] / gw14 [444] / gw15 [444] / gw16 [444] / gw17 [444] / gw18 [444] / gw19 [444] / gw20 [444] / gw21 [444] / gw22 [444] / gw23 [444] / gw24 [444] / gw25 [444] / gw26 [444] / gw27 [444] / gw28 [444] / gw29 [444] / gw30 [444] / gw31 [444] / gw32 [444] / gw33 [444] / gw34 [444] / gw35 [444] / gw36 [444] / gw37 [444] / gw38 [444] / gw39 [444] / gw40 [444] / gw41 [444] / gw42 [444] / gw43 [444] / gw44 [444] / gw45 [444] / gw46 [444] / gw47 [444]m
.........s.....................................................ss....... [ 16%]
...............s..s...s..............ssssssssssss....s.s................ [ 32%]
............ssssssssss....s.......................s......s.............. [ 48%]
....................F................................................... [ 64%]
........................................................................ [ 81%]
..............................s......................................... [ 97%]
............                                                             [100%]
=================================== FAILURES ===================================
_____________ test_raster_quadmesh_autorange_reversed[dask.array] ______________
[gw15] linux -- Python 3.8.11 /nix/store/mq6bfr9m4vq0phc15abpaf9xxzgffc8x-python3-3.8.11/bin/python3.8

array_module = <module 'dask.array' from '/nix/store/sgbbg5cnj4bmpgzmw76ad9va3rs6s9iw-python3.8-dask-2021.06.2/lib/python3.8/site-packages/dask/array/__init__.py'>

    @pytest.mark.parametrize('array_module', array_modules)
    def test_raster_quadmesh_autorange_reversed(array_module):
        c = ds.Canvas(plot_width=8, plot_height=4)
        da = xr.DataArray(
            array_module.array(
                [[1, 2, 3, 4],
                 [5, 6, 7, 8]]
            ),
            coords=[('b', [-1, -2]),
                    ('a', [-1, -2, -3, -4])],
            name='Z')
    
        y_coords = np.linspace(-2.25, -0.75, 4)
        x_coords = np.linspace(-4.25, -0.75, 8)
        out = xr.DataArray(array_module.array(
            [[8., 8., 7., 7., 6., 6., 5., 5.],
             [8., 8., 7., 7., 6., 6., 5., 5.],
             [4., 4., 3., 3., 2., 2., 1., 1.],
             [4., 4., 3., 3., 2., 2., 1., 1.]],
            dtype='f8'),
            coords=[('b', y_coords),
                    ('a', x_coords)]
        )
    
        res = c.quadmesh(da, x='a', y='b', agg=ds.sum('Z'))
>       assert_eq_xr(res, out)

datashader/tests/test_quadmesh.py:213: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

agg = <xarray.DataArray (b: 4, a: 8)>
array([[3.11779227e-316, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 3....* a        (a) float64 -4.25 -3.75 -3.25 -2.75 -2.25 -1.75 -1.25 -0.75
  * b        (b) float64 -2.25 -1.75 -1.25 -0.75
b = <xarray.DataArray 'array-9c1c69efb2f94e71e88c3025373a3534' (b: 4, a: 8)>
dask.array<array, shape=(4, 8), dtype=float64...* b        (b) float64 -2.25 -1.75 -1.25 -0.75
  * a        (a) float64 -4.25 -3.75 -3.25 -2.75 -2.25 -1.75 -1.25 -0.75
close = False

    def assert_eq_xr(agg, b, close=False):
        """Assert that two xarray DataArrays are equal, handling the possibility
        that the two DataArrays may be backed by ndarrays of different types"""
        if cupy:
            if isinstance(agg.data, cupy.ndarray):
                agg = xr.DataArray(
                    cupy.asnumpy(agg.data), coords=agg.coords, dims=agg.dims
                )
            if isinstance(b.data, cupy.ndarray):
                b = xr.DataArray(
                    cupy.asnumpy(b.data), coords=b.coords, dims=b.dims
                )
        if close:
            xr.testing.assert_allclose(agg, b)
        else:
>           xr.testing.assert_equal(agg, b)
E           AssertionError: Left and right DataArray objects are not equal
E           
E           Differing values:
E           L
E               array([[3.117792e-316, 0.000000e+000, 0.000000e+000, 0.000000e+000,
E                       3.116144e-316, 1.976263e-323, 3.116142e-316, 1.581010e-322],
E                      [3.053185e-316, 1.976263e-323, 3.053183e-316, 1.383384e-322,
E                       3.044877e-316, 1.976263e-323, 3.044874e-316, 2.420922e-322],
E                      [3.122500e-316, 1.976263e-323, 3.122494e-316, 5.187689e-322,
E                       3.122641e-316, 1.976263e-323, 3.122637e-316, 2.914987e-322],
E                      [2.940177e-316, 1.976263e-323, 2.940174e-316, 2.519735e-322,
E                       3.123467e-316, 1.976263e-323, 0.000000e+000, 0.000000e+000]])
E           R
E               array([[8., 8., 7., 7., 6., 6., 5., 5.],
E                      [8., 8., 7., 7., 6., 6., 5., 5.],
E                      [4., 4., 3., 3., 2., 2., 1., 1.],
E                      [4., 4., 3., 3., 2., 2., 1., 1.]])

datashader/tests/test_pandas.py:104: AssertionError
```

Those values are very off.

**Pull request merged**
