### PR TITLE
pythonPackages.cairocffi: v1.0.2 -> v.1.1.0

### LINKED ISSUE #69126: python3Packages.cairocffi is broken
**Describe the bug**

Test stage fails

cc @FRidh

### PR DESCRIPTION
**Pull request by d-goldin**
###### Motivation for this change

Fixes: https://github.com/NixOS/nixpkgs/issues/69126
Related to: https://github.com/NixOS/nixpkgs/issues/68361

The tests were failing due the switch to pytest5.
This issue has been addressed upstream in
https://github.com/Kozea/cairocffi/commit/a500f208660ba9861828a2a92b32c33565ee18fd
which is included in v.1.1.0, so bumping the version and
updating the old patch.

Hydra log of the failure:
https://hydra.nixos.org/build/100785460/nixlog/6

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @avnik

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Works fine for me, thanks!

**Review by avnik — APPROVED** [review]
Looks good for me.
I prepared similar patch, but you was few hours faster.

**Comment by avnik** [comment]
btw folks, I like to  simplify _LIBS content to  "@cairo@", and try to offer patch to upstream (with fallback to cffi.find_library if it still starts from "@". It can be useful by other distros, where library location is pre-known.

**Comment by Mic92** [comment]
@avnik sounds good.

**Comment by Mic92** [comment]
[detached HEAD 408b7e4dac4] pythonPackages.cairocffi: v1.0.2 -> v.1.1.0
 Author: Dima <dgoldin+github@protonmail.ch>
 Date: Sun Sep 22 16:27:36 2019 +0200
 2 files changed, 63 insertions(+), 48 deletions(-)
 rewrite pkgs/development/python-modules/cairocffi/dlopen-paths.patch (64%)

**Pull request merged**
