### PR TITLE
OpenSSL-related fixes for staging-next (2024-10-02)

### PR DESCRIPTION
**Pull request by thillux**
This PR is used to track broken packages after bumping OpenSSL default version from 3.0 -> 3.3. Furthermore some more cleanup with the different OpenSSL 3.x versions is done.

[x] edk2/OVMF: upstream currently not able to build with OpenSSL 3.3, set default OpenSSL to 3.0 for this package. (see: https://github.com/tianocore/edk2/pull/6184)
[x] haskellPackages.openssl-streams: repo contains old 1024 Bit RSA key, which OpenSSL 3.3 does not accept by default. Tests failed. Upstream seems dead for some years.
[x] WIP: Adapted openssl_3 to openssl_3_0, removed openssl_3_2 which only had a single user (switched cloudflare-warp to openssl_3_3)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by mjoerg — APPROVED** [review]

**Comment by adamcstephens** [comment]
Is this only for edk2, or are you planning to add more to it? If just edk2, then the title should reflect this.

**Comment by thillux** [comment]
I'll planned to address multiple OpenSSL related issues here (if there are any). Otherwise I'll rename to EDK2 fixes.

**Review by vcunat — COMMENTED** [review]
Why not a more specific version?  Honestly I'm surprised that right now `openssl_3` points to `openssl_3_0` and `openssl` points to `openssl_3_3`.

EDIT: it's how confusingly we've setup the openssl names, I'm afraid.

**Review by LunNova — APPROVED** [review]

**Comment by thillux** [comment]
> Why not a more specific version? Honestly I'm surprised that right now `openssl_3` points to `openssl_3_0` and `openssl` points to `openssl_3_3`.
> 
> EDIT: it's how confusingly we've setup the openssl names, I'm afraid.

I nevertheless adapted this and removed openssl_3. As it is not clear if openssl_3 should point to the oldest or newest version of 3.x. openssl_3_0 and openssl_3_3 are more explicit in this now.

**Comment by vcunat** [comment]
Please don't.  Right now `openssl_3_0` is defined as a deprecated alias.  Therefore some setups won't see that attribute!  (`allowAliases = false;` nixpkgs config)

**Comment by vcunat** [comment]
I'd prefer this state fixed, but this particular PR isn't a good place, I believe.

**Comment by K900** [comment]
The alias is removed in https://github.com/NixOS/nixpkgs/pull/345998/files#diff-29ed0f5fda84c91253503c1664d60a194a324e29518d472adf846f30b8db52e3L1181

**Comment by thillux** [comment]
> I'd prefer this state fixed, but this particular PR isn't a good place, I believe.

Ok, I'll remove it again.

**Comment by K900** [comment]
I definitely prefer the result of this PR to the status quo, FWIW.

**Comment by vcunat** [comment]
I'd separate that.  And maybe it's better done in `master` instead of `staging-next`.

**Comment by emilazy** [comment]
I am not sure if it makes sense to have package name churn because my hope is that we can drop 3.0 in 25.05, given that the only issues with 3.3 have been too‐small RSA keys in tests and weird build systems like EDK2 that are poking at internal headers because they expect vendored sources.

**Comment by maralorn** [comment]
We generally prefer to not clutter nixpkgs with patches but use pkgs.fetchpatch in Haskell land.
(Genuinely uncertain whether that is unusual in nixpkgs.)

**Comment by vcunat** [comment]
I think that's general, but I don't expect there's anywhere to fetch this from yet.  BTW, I pushed that commit to `staging-next` already. (Also the `edk2` commit, as it would be -small channel blocker and I heard no objection to that part.)

**Comment by emilazy** [comment]
@maralorn I also used to have this preference, but Alyssa pointed out to me that if an unmerged pull request is force‐pushed (say, because of upstream review feedback), GitHub will sometimes garbage‐collect the old commit and break future Nixpkgs reproducibility (you can look at random old Nixpkgs PRs and see 404s on the previous commit hashes from force‐pushes). This is sort of a general problem with FODs, but it made me lean more towards vendoring patches that aren’t available in a more stable place (upstream commit, another distro’s repository, etc.).

**Comment by emilazy** [comment]
About the PR, though, I think that removing 3.2 should be uncontroversial but it could probably use a compatibility alias since it’s already seen a release. `openssl_3_0` is a better name than we have, but I would personally prefer to work on fixing EDK2 so we can just drop it; have we confirmed that those existing pins don’t build fine with an unpinned OpenSSL?

**Comment by maralorn** [comment]
> @maralorn I also used to have this preference, but Alyssa pointed out to me that if an unmerged pull request is force‐pushed (say, because of upstream review feedback), GitHub will sometimes garbage‐collect the old commit and break future Nixpkgs reproducibility.

I was aware of that problem. But I thought that can be fixed by modifying the URL to not mention the pull request. Do even the simple `/commit/` urls go dead?

**Comment by vcunat** [comment]
It's a property of git that unreachable commits are meant to be forgotten (eventually).

**Comment by emilazy** [comment]
Yeah, though IMO the rebase‐oriented GitHub code review flow means that previous versions of a PR should not be considered unreachable. There’s links directly to them from the PR pages that are 404s. Garbage collection shouldn’t lead to dangling pointers :)

But it is what it is so it’s worth keeping in mind.

**Pull request closed without merging**
