### PR TITLE
nixos-generate-config: detects parallels virtualization

### PR DESCRIPTION
**Pull request by catap**
###### Description of changes

A trivial changes that fixes `nixos-generate-config` for parallels VMs.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by catap** [comment]
@wegank, what do you think about this one?

**Comment by flokli** [comment]
This is not trivial anymore:

https://github.com/NixOS/nixpkgs/pull/179487/files#diff-a284772b505bd573f834b58591d380128545257d9e02601dbe112548526c8710R183

We tend to not backport systemd patches, but try to track systemd-stable.

Can you open a PR to systemd-stable to backport this?

**Comment by catap** [comment]
@flokli it may requires a lot of time, special that systemd 251 was released and called stable.

From another hand this trivial patch makes life of newcomers to NixOS under parallels much easy.

**Comment by flokli** [comment]
@catap systemd rebuilds are a pretty hefty mass-rebuild on our side, so would need to go through the nixpkgs staging cycle.

Please poke upstream to cherry-pick this into a point release. They did this before. We only apply nixos-specific patches.

**Comment by catap** [comment]
@flokli I've already pointed it here: https://github.com/systemd/systemd/pull/23859

**Comment by catap** [comment]
@flokli I see that you mean. An attempt to use it triggers rebuild near of all packages.

**Comment by catap** [comment]
@flokli here it is

**Comment by catap** [comment]
@SuperSandro2000, may I ask you to review one more PR which is related to parallels guest?

**Comment by flokli** [comment]
@catap setting `systemd.package` to a custom systemd package with the patch, but not overriding `pkgs.systemd` shouldn't cause a mass rebuild.

**Comment by flokli** [comment]
Ok, the simple installer test still succeeds with this, so it looks like there's no breakage in the perl code. Let's merge this in :+1:

**Pull request merged**
