### PR TITLE
vsftpd: enable seccomp

### PR DESCRIPTION
**Pull request by ajs124**
###### Motivation for this change
very securer ftpd

###### Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by peterhoeg** [comment]
While at it, how do you feel about adding a nixos test for vsftpd?

**Comment by ajs124** [comment]
Sure, I can write a basic test. Which features would you like tested that?
Starting the server, uploading and downloading a file?

Do you maybe have an example config that I could re-use for that?

**Comment by ajs124** [comment]
What do you think about the test I've already pushed to this PR?

> I suggest taking a look at some of the existing tests. It's a good way to get a feel for how to write these things.

I meant vsftpd config. This isn't my first nixos test :smile:

**Comment by peterhoeg** [comment]
> This isn't my first nixos test

I'm sorry man. I need more sleep.

One last thing - with `nixosTests` we can run the nixos tests when the package changes:     
```
passthru = {
  tests = { inherit (nixosTests) vsftpd; };
};
```

We probably want this.

Thank you for your patience!

**Pull request merged**
