### PR TITLE
Fix GHCJS 7.10

### PR DESCRIPTION
**Pull request by ElvishJerricco**
###### Motivation for this change

Fixes the old version of GHCJS

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

/cc @dmjio

### CODE REVIEW

**Comment by peti** [comment]
@GrahamcOfBorg build haskellPackages.ghcjs

**Comment by peti** [comment]
@GrahamcOfBorg build haskell.compiler.ghcjs

**Review by peti — APPROVED** [review]
Looks good to me. I triggered a test build, just to be on the safe side.

**Comment by dmjio** [comment]
@grahamc @peti @ElvishJerricco awesome! I assume this means `haskell.compiler.ghcjs` builds on Darwin as well? Couldn't tell after this comment: https://github.com/NixOS/nixpkgs/pull/38314#issuecomment-378018465

**Comment by ElvishJerricco** [comment]
@dmjio Hm I never tested the build on darwin, but that does look like a failure :/

**Comment by ElvishJerricco** [comment]
@dmjio Just tried it on my macbook. Built fine. Though I'm only on Sierra, not High Sierra

**Pull request merged**
