### PR TITLE
Rustup fix darwin build

### PR DESCRIPTION
**Pull request by happysalada**
###### Motivation for this change

fix darwin build

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 123849` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>rustup</li>
  </ul>
</details>

**Comment by happysalada** [comment]
The failure is
```
 running: "/nix/store/4akw6n9a2f1cxwcwihzf1diblbyzhkkc-clang-wrapper-7.1.0/bin/cc" "-O3" "-ffunction-sect
  cargo:warning=In file included from xz-5.2/src/liblzma/common/filter_decoder.c:13:
  cargo:warning=In file included from xz-5.2/src/liblzma/common/filter_decoder.h:16:
  cargo:warning=In file included from xz-5.2/src/liblzma/common/common.h:16:
  cargo:warning=xz-5.2/src/common/sysdefs.h:24:11: fatal error: 'config.h' file not found
```

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 123849` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>rustup</li>
  </ul>
</details>

**Comment by happysalada** [comment]
@jonringer merging this since, I've only modified darwin stuff and the build is passing.
Let me know if you think I am being a little too brash.

**Comment by jonringer** [comment]
> @jonringer merging this since, I've only modified darwin stuff and the build is passing.
> Let me know if you think I am being a little too brash.

All good, I couldn't test it anyway

**Pull request merged**
