### PR TITLE
[Backport release-21.11] vengi-tools: 0.0.14 -> 0.0.18 and related changes

### PR DESCRIPTION
**Pull request by fgaz**
###### Motivation for this change

https://github.com/NixOS/nixpkgs/pull/158094#issuecomment-1029930182 cc @turion 

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
  - [x] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fgaz** [comment]
> [ofborg](https://github.com/apps/ofborg) bot added the ofborg-internal-error label [1 minute ago](https://github.com/NixOS/nixpkgs/pull/158116#event-6009340863)

...did I do something wrong?

**Comment by fgaz** [comment]
@GrahamcOfBorg eval

**Comment by turion** [comment]
This looks fine to me, but I've never merged a nontrivial backport PR, so I'd like to have some other committer's opinion.

**Comment by cole-h** [comment]
> > [ofborg](https://github.com/apps/ofborg) bot added the ofborg-internal-error label [1 minute ago](https://github.com/NixOS/nixpkgs/pull/158116#event-6009340863)
> 
> ...did I do something wrong?

Nah, this is usually something GitHub did (i.e. sending API responses without required fields). It's just labeled so I can (eventually) check it out and make sure that's what it is, and not some silent API changes we'll have to accommodate.

**Comment by fgaz** [comment]
/status needs_reviewer

Too many "w"s :sweat_smile:

**Review by jonringer — APPROVED** [review]
diff looks goo to me, but would like a darwin user to confirm changes.

**Comment by fgaz** [comment]
@timokau for some reason marvin just undid its last action here https://github.com/NixOS/nixpkgs/pull/158116#event-6153635644

**Comment by jonringer** [comment]
@GrahamcOfBorg eval

**Comment by jonringer** [comment]
ofborg built it

**Comment by timokau** [comment]
@fgaz that happens when marvin re-requests the same reviewer as before. Github does not show that in its UI. See https://github.com/timokau/marvin-mk2/issues/86.

**Pull request merged**
