### PR TITLE
cert-viewer: use build-time version to generate manpage

### PR DESCRIPTION
**Pull request by mkg20001**
## Description of changes
Fixes cross-compile

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by bjornfor** [comment]
> Fixes cross-compile

How did you test? I'm still getting failures:

```
$ gh pr checkout 306620
$ nix-build -A pkgsCross.armv7l-hf-multiplatform.cert-viewer
[...]
Building subPackage .
fork/exec /build/go-build1820111614/b001/exe/cert-viewer: exec format error
```

(And I verified that this cross-compilation worked on the commit before https://github.com/nixos/nixpkgs/pull/306249.)

**Comment by bjornfor** [comment]
I'm not sure if this is the right way, but this seems to work:

```patch
diff --git a/pkgs/by-name/ce/cert-viewer/package.nix b/pkgs/by-name/ce/cert-viewer/package.nix
index 806758f03aef..a29bca3c9ab3 100644
--- a/pkgs/by-name/ce/cert-viewer/package.nix
+++ b/pkgs/by-name/ce/cert-viewer/package.nix
@@ -2,6 +2,8 @@
 , fetchFromGitHub
 , lib
 , installShellFiles
+, buildPackages
+, stdenv
 }:

 buildGoModule rec {
@@ -21,8 +23,13 @@ buildGoModule rec {
     installShellFiles
   ];

-  postInstall = ''
-    $out/bin/cert-viewer --help-man > cert-viewer.1
+  postInstall =
+    if stdenv.buildPlatform.canExecute stdenv.hostPlatform
+    then ''
+      go run . --help-man > cert-viewer.1
+    '' else ''
+      ${lib.getExe buildPackages.cert-viewer} --help-man > cert-viewer.1
+    '' + ''
     installManPage cert-viewer.1
   '';
```

**Comment by bjornfor** [comment]
Alternatively:

```
  postInstall =
    let
      prog =
        if stdenv.buildPlatform.canExecute stdenv.hostPlatform
        then "$out/bin/cert-viewer"
        else lib.getExe buildPackages.cert-viewer;
    in
      ''
        ${prog} --help-man > cert-viewer.1
        installManPage cert-viewer.1
      '';
```

**Comment by bjornfor** [comment]
I made the above change here: https://github.com/NixOS/nixpkgs/pull/307018

**Review by bjornfor — CHANGES_REQUESTED** [review]
Doesn't work (see earlier comments). Possible fix here: https://github.com/NixOS/nixpkgs/pull/307018

**Comment by mkg20001** [comment]
superseeded by https://github.com/NixOS/nixpkgs/pull/307018

**Pull request closed without merging**
