### PR TITLE
elixir: remove "stray" reference from its BEAM artifacts

### PR DESCRIPTION
**Pull request by NobbZ**
###### Description of changes

In the old variant of the build the elixir modules kept references to the erlang
derivation, which in turn increased the closuresize of `mixRelease` and similar
without any need for it.

This PR intends to remove the references from where they are not necessary, but
leave them where they belong and are expected.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

1 package marked as broken and skipped:
pleroma-otp

1 package failed to build:
plausible

10 packages built:
elixir elixir_1_10 elixir_1_11 elixir_1_12 elixir_1_14 elixir_ls mix2nix pleroma rabbitmq-server sonic-pi

### CODE REVIEW

**Comment by lilyinstarlight** [comment]
I just happened to see this. I'll chime in real quick to say that I've usually seen these references only be in the debug info of Elixir BEAMs. In Sonic Pi, I removed these references by stripping them using `beam_lib:strip/1`: https://github.com/sonic-pi-net/sonic-pi/blob/fd8298a4f17a2cdeec45f036c466f54ec91874d5/app/linux-release.sh#L62-L64

I'm not sure if overwriting the references in the debug info via `remove-references-to` or just stripping debug info would be preferred, but I'm mostly neutral to either

**Comment by NobbZ** [comment]
As far as I understand debug is stripped by default.

That's why I'm pulling out the fat guns.

**Comment by lilyinstarlight** [comment]
> As far as I understand debug is stripped by default

Hmm I can't spot the code in `mixRelease` that would strip them

I'm not currently at a computer to test, though, else I'd just try adding a hook to strip them instead to see if it removes references like this does and confirm

**Comment by NobbZ** [comment]
I mean in elixir they should already be stripped.

`debugInfo` is `false`, so debug should never end up in the build.

Sadly BEAMdeas does not work for me, and I haven't found a quick way to inspect the beam ASM. 

Though I will do some experiments later with an override and see if explicit stripping actually changes the situation.

**Comment by lilyinstarlight** [comment]
> I mean in elixir they should already be stripped.

If I remember correctly, it was something like only Erlang dependencies in Mix that didn't get stripped (or rebar deps or something)

> Though I will do some experiments later with an override and see if explicit stripping actually changes the situation.

That would be lovely, thank you! I can also do some experiments in a few hours when I'm able to be back to my NixOS laptop

**Comment by NobbZ** [comment]
I was able to issue a very brief check via SSH, after stripping the file the reference is gone.

Therefore I think the proper solution is to actually change `mixRelease` to conditionally strip debug symbols.

This seems to reduce closure size even more :D The file in question shrunk from 252kiB to 144kiB.

I will close this PR and continue to work on the stripping in `mixRelease` later.

**Pull request closed without merging**
