### PR TITLE
darwin: matplotlib: add needed inputs and set framework flag for darwin

### PR DESCRIPTION
**Pull request by datakurre**
Should fix pythonPackages.matplotlib on darwin.

Not completely sure, why I need to add "-I${libcxx}/include/c++/v1" to make those headers available on darwin.

Patch is required to skip matplotlib's dummy check for system python, which is not available in darwin sandbox. (matplotlib would build without it, but raise RuntimeErrors later.)

### CODE REVIEW

**Comment by datakurre** [comment]
On holde. Broken on darwin after 1.4.3 -> 1.5.0. Figuring out a new patch...

**Comment by datakurre** [comment]
This is probably ok again.

**Comment by mjhoy** [comment]
just want to report this fixed matplotlib build for me! (10.9, python34)

**Comment by domenkozar** [comment]
@datakurre is this ready to be merged?

**Comment by datakurre** [comment]
@domenkozar Yes. No one has proposed better fix yet :)

**Comment by domenkozar** [comment]
@datakurre I'd really like to get the patch upstream (or at least open an issue for matplotlib)

**Comment by datakurre** [comment]
Ok. But not sure, what would be the proper fix at upstream.

Matplotlib has OS X specific check that some features only work when it's installed on a "darwin framework python". Here I disable that check with patch, because Nixpkgs python does build "darwin framework".

@pikajude What would you think? Should Nix build a such Python on darwin that matplotlib's framework check passes, or should be request a flag from upstream to disable that check?

https://github.com/matplotlib/matplotlib/blob/master/src/_macosx.m#L6264

**Comment by domenkozar** [comment]
weel @datakurre if this fixes matplotlib for you, I'm happy to merge and we can make a better patch later.

**Comment by datakurre** [comment]
:+1:

I don't know darwin and its Nix integration too deeply to understand if there's any benefits for building Python also as a framework. If there isn't maybe then we should ask matplotlib to add build-time option for disabling that check. I recall trying matplotlib Aqua integration, but I have not tried Qt or TCL/TK integrations (I'm just scripting graphs or using it with Jupyter notebook).

**Comment by domenkozar** [comment]
It's a good start :)

**Pull request merged**
