### PR TITLE
Add package updates

### PR DESCRIPTION
**Pull request by matthiasbeyer**
I manually checked and approved the PRs in the list below.
This is a combination of all commits from these PRs and therefor closes all these PRs.
All these PRs were genereated by the semi auto-update of @r-ryantm and are version-and-hash updated patches.

All these were `cherry-pick -x`ed. I did not test-build them, but none of these had a failing Borg.

Pinging @FRidh and @Infinisil because they are mentioned in some or all of these PRs as maintainers.

###### Motivation for this change

Closes #58857
Closes #58856
Closes #58855
Closes #58854
Closes #58853
Closes #58852
Closes #58844
Closes #58843
Closes #58840
Closes #58839
Closes #58838
Closes #58837
Closes #58836
Closes #58832
Closes #58829
Closes #58821
Closes #58820
Closes #58819
Closes #58817
Closes #58818
Closes #58775
Closes #58779
Closes #58781
Closes #58782
Closes #58783
Closes #58785
Closes #58786
Closes #58788
Closes #58789
Closes #58790
Closes #58791
Closes #58793
Closes #58794
Closes #58796
Closes #58799
Closes #58802
Closes #58805
Closes #58807
Closes #58808
Closes #58810
Closes #58813
Closes #58816

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Here's a list of my "approved" notices (direct link):

https://github.com/NixOS/nixpkgs/pull/58857#pullrequestreview-223578672
https://github.com/NixOS/nixpkgs/pull/58856#pullrequestreview-223578663
https://github.com/NixOS/nixpkgs/pull/58855#pullrequestreview-223578648
https://github.com/NixOS/nixpkgs/pull/58854#pullrequestreview-223578645
https://github.com/NixOS/nixpkgs/pull/58853#pullrequestreview-223578641
https://github.com/NixOS/nixpkgs/pull/58852#pullrequestreview-223578636
https://github.com/NixOS/nixpkgs/pull/58844#pullrequestreview-223578633
https://github.com/NixOS/nixpkgs/pull/58843#pullrequestreview-223578629
https://github.com/NixOS/nixpkgs/pull/58840#pullrequestreview-223578626
https://github.com/NixOS/nixpkgs/pull/58839#pullrequestreview-223578621
https://github.com/NixOS/nixpkgs/pull/58838#pullrequestreview-223578615
https://github.com/NixOS/nixpkgs/pull/58837#pullrequestreview-223578607
https://github.com/NixOS/nixpkgs/pull/58836#pullrequestreview-223578605
https://github.com/NixOS/nixpkgs/pull/58832#pullrequestreview-223578600
https://github.com/NixOS/nixpkgs/pull/58829#pullrequestreview-223578598
https://github.com/NixOS/nixpkgs/pull/58821#pullrequestreview-223579000
https://github.com/NixOS/nixpkgs/pull/58820#pullrequestreview-223579001
https://github.com/NixOS/nixpkgs/pull/58819#pullrequestreview-223579005
https://github.com/NixOS/nixpkgs/pull/58817#pullrequestreview-223579008
https://github.com/NixOS/nixpkgs/pull/58818#pullrequestreview-223579010
https://github.com/NixOS/nixpkgs/pull/58775#pullrequestreview-223579173
https://github.com/NixOS/nixpkgs/pull/58779#pullrequestreview-223579169
https://github.com/NixOS/nixpkgs/pull/58781#pullrequestreview-223579166
https://github.com/NixOS/nixpkgs/pull/58782#pullrequestreview-223579161
https://github.com/NixOS/nixpkgs/pull/58783#pullrequestreview-223579158
https://github.com/NixOS/nixpkgs/pull/58785#pullrequestreview-223579155
https://github.com/NixOS/nixpkgs/pull/58786#pullrequestreview-223579152
https://github.com/NixOS/nixpkgs/pull/58788#pullrequestreview-223579148
https://github.com/NixOS/nixpkgs/pull/58789#pullrequestreview-223579146
https://github.com/NixOS/nixpkgs/pull/58790#pullrequestreview-223579142
https://github.com/NixOS/nixpkgs/pull/58791#pullrequestreview-223579138
https://github.com/NixOS/nixpkgs/pull/58793#pullrequestreview-223579131
https://github.com/NixOS/nixpkgs/pull/58794#pullrequestreview-223579126
https://github.com/NixOS/nixpkgs/pull/58796#pullrequestreview-223579123
https://github.com/NixOS/nixpkgs/pull/58799#pullrequestreview-223579092
https://github.com/NixOS/nixpkgs/pull/58802#pullrequestreview-223579087
https://github.com/NixOS/nixpkgs/pull/58805#pullrequestreview-223579080
https://github.com/NixOS/nixpkgs/pull/58807#pullrequestreview-223579074
https://github.com/NixOS/nixpkgs/pull/58808#pullrequestreview-223579070
https://github.com/NixOS/nixpkgs/pull/58810#pullrequestreview-223579064
https://github.com/NixOS/nixpkgs/pull/58813#pullrequestreview-223579063
https://github.com/NixOS/nixpkgs/pull/58816#pullrequestreview-223579059

### CODE REVIEW

**Comment by zimbatm** [comment]
quite satisfying to merge, nice work :)

**Comment by matthiasbeyer** [comment]
That's why I did it. Having hundrets of small version-hash-update-PRs is really not a good approach, IMO. We (as in I and a few others) already screamed at each other in IRC about that...

**Comment by markuskowa** [comment]
pythonPackages.pex is still marked as broken (https://github.com/NixOS/nixpkgs/pull/58816). Has this been tested properly?

**Comment by FRidh** [comment]
Ha, just started a Hydra job with a bunch of updates. No need for that now I think.

I occasionally do batch updates of Python packages, but it may take time (maybe once every month or perhaps 2) and it may break things. Because of some complaints on that I requested @ryantm to enable it for Python packages as well. Now, due to the large amount of Python packages, we do get flooded with these PR's.

**Pull request merged**
