### PR TITLE
webos: init novacom, novacomd, cmake-modules; add nixos service

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

Add novacom, novacomd for communicating with WebOS devices.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

I'm using the provided nixos service presently! :grin:

### CODE REVIEW

**Comment by dtzWill** [comment]
The expressions work on 17.09 (it's how I'm running this currently)-- might this be cherry-picked onto 17.09?

**Comment by dtzWill** [comment]
Ping! Not as useful as it would have been years ago but I still have a number of webOS devices I occasionally hack on.

**Comment by 7c6f434c** [comment]
@dtzWill so now you can review your own long-standing PRs and either declare them «trivial»/«enough feedback» and merge or add a «by: nixpkgs-member» label and an explanation why extra eyes are needed.

**Comment by dtzWill** [comment]
@GrahamcOfBorg test novacomd

**Comment by dtzWill** [comment]
@GrahamcOfBorg build webos.novacom webos.novacomd

**Pull request merged**
