### PR TITLE
kde_applications: 18.12.03 -> 19.04.1; kdeFrameworks: 5.56 -> 5.58; plasma-5: 5.15.3 -> 5.15.5

### PR DESCRIPTION
**Pull request by nyanloutre**
###### Motivation for this change

Some work will need to be done to make some application work.

Fixed apps:
- [x] akonadi
- [x] kdegraphics-thumbnailers
- [x] kdenlive
- [x] kdepim-runtime
- [x] kio-extras
- [x] kcalc
- [x] kmail

~kdenlive is trying to download https://github.com/rttrorg/rttr during build~

~kdepim-runtime error:~
```
[ 31%] Building CXX object resources/facebook/CMakeFiles/facebookresourcelib.dir/listjob.cpp.o
In file included from /build/kdepim-runtime-19.04.0/resources/facebook/listjob.cpp:18:0:
/build/kdepim-runtime-19.04.0/resources/facebook/listjob.h:23:10: fatal error: AkonadiCore/Item: No such file or directory
 #include <AkonadiCore/Item>
          ^~~~~~~~~~~~~~~~~~
```

the plasma5 test is passing and every dependencies are cached on https://nyanloutre.cachix.org

any help is welcome

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
a59ab5aeb21b6f38c26a1ea7522b890fb81ca418
(as well as similar fixes to what you have above)
was what I ended up with, at least or the applications I use/build.  Sorry, was working to upstream things today :innocent:.

**Comment by nyanloutre** [comment]
@dtzWill thanks I added the patch that I missed

**Comment by worldofpeace** [comment]
> kdenlive is trying to download https://github.com/rttrorg/rttr during build

That's what it does when it can't find it 
* https://github.com/KDE/kdenlive/blob/1d833e731a66b815adb5639d9a25c38368595ed6/CMakeLists.txt#L129

I don't think it's packaged so we'll need to add it.

**Comment by worldofpeace** [comment]
Fixed that in the push. Hope you don't mind.

**Comment by nyanloutre** [comment]
@worldofpeace ok no problem, I was looking at it too but didn't find how to enable the unit tests

**Comment by nyanloutre** [comment]
and as with the previous versions of kdenlive on NixOS there is missing codecs for rendering (only lossless is available)

**Comment by worldofpeace** [comment]
> and as with the previous versions of kdenlive on NixOS there is missing codecs for rendering (only lossless is available)

Which codecs?

At runtime I also saw warnings for missing
* frei0r-plugins
* ffmpeg (probably runtime optional)
* ffplay
* ffprobe

**Comment by nyanloutre** [comment]
It's similar to this issue : https://forums.linuxmint.com/viewtopic.php?t=276908

**Comment by bkchr** [comment]
The package `qtnetworkauth` does not exist? Did you just missed to commit the module?

**Comment by nyanloutre** [comment]
I added qtnetworkauth but `kdepim-runtime` is still not compiling (see the PR description)

**Comment by dtzWill** [comment]
Eep, sorry!

https://github.com/dtzWill/nixpkgs/commit/ca173a30bf054931dbd469724d9ff69afa930a0e

And not sure what problem you're seeing, I found I needed to disable fb
support w/19.03.90 (19.04rc2?):
(hopefully this was fixed and is not needed!)

https://github.com/dtzWill/nixpkgs/commit/7d9d45aea1bab86239426e9c3a9993a2f14c8960

Investigating, sorry! :)

**Comment by nyanloutre** [comment]
Is there still something blocking the merge ?

**Comment by worldofpeace** [comment]
Sorry, I just haven't had a chance to test things @nyanloutre.

Have you runtime tested the applications?

**Comment by vandenoever** [comment]
https://github.com/NixOS/nixpkgs/pull/60889 is a similar patch. It has working kmail. You can cherry pick from there.

Notably, it disable facebook from `resources/CMakeLists.txt` in `kdepim-runtime` by patching it out which is cleaner than using `sed`.

It fixes two compilation errors in `kmail` by this patch
```patch
diff --git a/agents/archivemailagent/CMakeLists.txt b/agents/archivemailagent/CMakeLists.txt
index 48ed076..9c56896 100644
--- a/agents/archivemailagent/CMakeLists.txt
+++ b/agents/archivemailagent/CMakeLists.txt
@@ -22,6 +22,7 @@ ki18n_wrap_ui(libarchivemailagent_SRCS ui/archivemailwidget.ui )
 add_library(archivemailagent STATIC ${libarchivemailagent_SRCS})
 target_link_libraries(archivemailagent
     KF5::MailCommon
+    KF5::Libkdepim
     KF5::I18n
     KF5::Notifications
     KF5::IconThemes
diff --git a/agents/followupreminderagent/CMakeLists.txt b/agents/followupreminderagent/CMakeLists.txt
index a56b730..83604cf 100644
--- a/agents/followupreminderagent/CMakeLists.txt
+++ b/agents/followupreminderagent/CMakeLists.txt
@@ -23,6 +23,7 @@ target_link_libraries(followupreminderagent
     KF5::AkonadiMime
     KF5::AkonadiAgentBase
     KF5::DBusAddons
+    KF5::FollowupReminder
     KF5::XmlGui
     KF5::KIOWidgets
     KF5::Notifications
```

**Comment by nyanloutre** [comment]
@vandenoever I cherry picked your commits, thanks

**Comment by nyanloutre** [comment]
@dtzWill in the kdepim-runtime package was qca-qt5 mandatory for runtime ? (because it's building fine without it)

**Comment by dtzWill** [comment]
On Mon, 06 May 2019 10:49:11 -0700, Paul TREHIOU <notifications@github.com> wrote:
> @dtzWill in the kdepim-runtime package was qca-qt5 mandatory for runtime ? (because it's building fine without it)

I believe I added it after inspecting build logs / the build system
files themselves -- it wasn't strictly required but when I asked myself
"should the PIM runtime be able to use the 'qt crypto architecture'?"
it seemed better to make the mistake of unnecessarily including it :).

But honestly it was mostly on a whim, so if there's reason to drop it
then it probably should be investigated / discussed :).

**Comment by dtzWill** [comment]
19.04.1 (and 5.58, plasma 5.15.5, etc), for the interested: https://kde.org/announcements/

So far been easy updates on top of the (minor) fixups needed here.

**Comment by nyanloutre** [comment]
@dtzWill I updated the PR with the new versions

**Comment by nyanloutre** [comment]
nixosTests.plasma5 ran successfully for me

**Comment by vandenoever** [comment]
I would like to abuse this thread a bit. KDE has a yearly conference. It's a great way to let people know how great KDE software works on NixOS and praise the KDE devs in person. If someone feels like presenting a talk along the lines of 'KDE/Plasma on NixOS', I'm sure it would be very much appreciated.

https://akademy.kde.org/2019/cfp

I try to go every year and it never disappoints.

**Comment by acowley** [comment]
I've also built this and done a quick video edit and render with `kdenlive`. 👍

**Comment by nyanloutre** [comment]
@acowley is lossy encoding (x264 for example) working in kdenlive now ?

**Comment by acowley** [comment]
It worked out of the box for me (x264 is what I used), but I can’t say why it worked (eg maybe I had ffmpeg available).

**Comment by worldofpeace** [comment]
Just squashed the fixup commit.

**Review by worldofpeace — APPROVED** [review]
LGTM, I'm inclined to integrate this fairly soon if there isn't any issues raised.

**Comment by worldofpeace** [comment]
[Result of nix-review](https://gist.github.com/worldofpeace/4c1ac8f702653558682e2a4bb1d0db60)


<details> <summary>Failures that are new and should be fixed</summary>

<p>

  - krita
    <details>
      <summary>build log</summary>

       https://gist.github.com/worldofpeace/c8248ff92b0ced199124bdcfdb59420f
      
    </details>


  - kdeApplications.krdc
    <details><summary>build log</summary>

       https://gist.github.com/worldofpeace/c1ea091a8ba41ced9e375d6ef4b12548

    </details>

</p>

</details>

**Comment by nyanloutre** [comment]
For Krita, it may be this issue: #35359

**Comment by vcunat** [comment]
Yes, I'm fairly certain.

**Comment by worldofpeace** [comment]
Ok krita build failure is transient, I guess this should be good now.

**Comment by worldofpeace** [comment]
Thanks to those involved :fireworks:

**Comment by vandenoever** [comment]
Awesome!

**Pull request merged**
