### PR TITLE
pythonPackages.blockdiag: 1.5.3 -> 2.0.1

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Motivation for this change
Closes #92108

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105307` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>actdiag (python38Packages.actdiag)</li>
    <li>blockdiag (python38Packages.blockdiag)</li>
    <li>nwdiag (python38Packages.nwdiag)</li>
    <li>python37Packages.actdiag</li>
    <li>python37Packages.blockdiag</li>
    <li>python37Packages.nwdiag</li>
    <li>python37Packages.seqdiag</li>
    <li>python37Packages.sphinxcontrib-blockdiag</li>
    <li>seqdiag (python38Packages.seqdiag)</li>
    <li>python38Packages.sphinxcontrib-blockdiag</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105307` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>actdiag (python38Packages.actdiag)</li>
    <li>blockdiag (python38Packages.blockdiag)</li>
    <li>nwdiag (python38Packages.nwdiag)</li>
    <li>python37Packages.actdiag</li>
    <li>python37Packages.blockdiag</li>
    <li>python37Packages.nwdiag</li>
    <li>python37Packages.seqdiag</li>
    <li>python37Packages.sphinxcontrib-blockdiag</li>
    <li>seqdiag (python38Packages.seqdiag)</li>
    <li>python38Packages.sphinxcontrib-blockdiag</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105307` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>actdiag (python38Packages.actdiag)</li>
    <li>blockdiag (python38Packages.blockdiag)</li>
    <li>nwdiag (python38Packages.nwdiag)</li>
    <li>python37Packages.actdiag</li>
    <li>python37Packages.blockdiag</li>
    <li>python37Packages.nwdiag</li>
    <li>python37Packages.seqdiag</li>
    <li>python37Packages.sphinxcontrib-blockdiag</li>
    <li>seqdiag (python38Packages.seqdiag)</li>
    <li>python38Packages.sphinxcontrib-blockdiag</li>
  </ul>
</details>

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 105307 [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>1 package marked as broken and skipped:</summary>  <ul>    <li>asciidoc-full-with-plugins</li>  </ul></details><details>  <summary>10 packages built:</summary>  <ul>    <li>actdiag (python38Packages.actdiag)</li>    <li>blockdiag (python38Packages.blockdiag)</li>    <li>nwdiag (python38Packages.nwdiag)</li>    <li>python37Packages.actdiag</li>    <li>python37Packages.blockdiag</li>    <li>python37Packages.nwdiag</li>    <li>python37Packages.seqdiag</li>    <li>python37Packages.sphinxcontrib-blockdiag</li>    <li>seqdiag (python38Packages.seqdiag)</li>    <li>python38Packages.sphinxcontrib-blockdiag</li>  </ul></details>

**Pull request merged**
