### PR TITLE
kdiff3: usable on darwin

### PR DESCRIPTION
**Pull request by aaschmid**
###### Motivation for this change

Make kdiff3 available for darwin as well using a dedicated pre-built `dmg` package as source. I already use it on my environment as a derivation just added to the `gitconfig`s `mergetool` section

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
@ofborg build kdiff3

**Comment by aaschmid** [comment]
Any further comments or would you merge @peterhoeg @Mic92?

**Comment by aaschmid** [comment]
ping @peterhoeg, any opinion?

**Comment by peterhoeg** [comment]
I don't really like the idea of one being from source and the other from binary based on platform. This isn't kdiff3 specific as such.

I see that kdiff3 has in the mean time made it to v1.9.4 - maybe things work better from source on mac with the latest version?

**Comment by aaschmid** [comment]
Ok, thanks for the feedback. Building from source on mac hasn't worked for me so far and I already invested time into trying to built. Therefore I will close this PR for now.

**Pull request closed without merging**
