### PR TITLE
 prometheus-tor-exporter: init at 0.3

### PR DESCRIPTION
**Pull request by delroth**
###### Motivation for this change
I want some monitoring for my Tor relay :) This is not a particularly widely used piece of software, but it seems to be still maintained upstream.

First time contributing and packaging things for Nix, please let me know if anything can be improved!

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by rasendubi — APPROVED** [review]

**Review by rasendubi — APPROVED** [review]

**Comment by rasendubi** [comment]
@GrahamcOfBorg build prometheus-tor-exporter

**Comment by delroth** [comment]
> Success on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.48307&attempt_id=0eed6911-4ed9-4799-9f67-b58fdc6e6417)
> 
> Attempted: prometheus-tor-exporter
> 
> Partial log (click to expand)
> ```
> source root is source
> setting SOURCE_DATE_EPOCH to timestamp 315619200 of file source/prometheus-tor-exporter.service
> patching sources
> configuring
> no configure script, doing nothing
> building
> no Makefile, doing nothing
> installing
> post-installation fixup
> /nix/store/igfgjnmki84dpvq0vnl7k8p04gcmlgm5-tor-exporter-0.3
> ```

**Comment by delroth** [comment]
(Misclick, sorry.)

**Comment by rasendubi** [comment]
Thanks and welcome! ;)

**Pull request merged**
