### PR TITLE
Xen: build EFI binaries and drop unsupported versions

### PR DESCRIPTION
**Pull request by Shados**
###### Motivation for this change
#60485 has been going nowhere, so I'm closing that in favour of trying sequential, staggered PRs for the individual changes. This PR builds EFI binaries for Xen, and drops Xen 4.5 and 4.8, both of which are _entirely_ EOL/unsupported upstream.

###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @edolstra @oxij

### CODE REVIEW

**Comment by JohnAZoidberg** [comment]
The build fails on ofBorg, can you please check that?
And also you need to rebase it on top of the latest master.

**Comment by Shados** [comment]
Fixed the build process, still need to get around to testing the produced EFI binary.

**Comment by Shados** [comment]
Did some testing, boots fine.

**Comment by mt-caret** [comment]
@Shados Thank you so much for working on this! Are there any blockers for merging this PR, or is this just waiting for review? I would love for this to be in nixpkgs...

**Comment by Shados** [comment]
Well, I expect there's likely been some bitrot since the last time I updated it, so I'll rebase again and see.

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 77421` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>14 packages built:</summary>
  <ul>
    <li>gnome3.gnome-boxes</li>
    <li>libguestfs</li>
    <li>libguestfs-with-appliance</li>
    <li>libvmi</li>
    <li>python27Packages.guestfs</li>
    <li>python37Packages.guestfs</li>
    <li>python38Packages.guestfs</li>
    <li>qemu_xen (qemu_xen_4_10)</li>
    <li>qemu_xen-light (qemu_xen_4_10-light)</li>
    <li>qubes-core-vchan-xen</li>
    <li>vagrant</li>
    <li>xen (xenPackages.xen-vanilla ,xenPackages.xen_4_10-vanilla ,xen_4_10)</li>
    <li>xen-light (xenPackages.xen-light ,xenPackages.xen_4_10-light ,xen_4_10-light)</li>
    <li>xen-slim (xenPackages.xen-slim ,xenPackages.xen_4_10-slim ,xen_4_10-slim)</li>
  </ul>
</details>

**Pull request merged**
