### PR TITLE
python39Packages.flit: 3.6.0 -> 3.7.1

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by FRidh — CHANGES_REQUESTED** [review]
In flit-core, version and format need to be inherited from flit as well.

Other than that, I think this is good. I highly doubt there are regressions when updating flit-core; as a build system that would be very problematic.

**Comment by SuperSandro2000** [comment]
> In flit-core, version and format need to be inherited from flit as well.

Done

**Review by FRidh — APPROVED** [review]
Looks good. Just waiting for CI eval to pass.

**Comment by FRidh** [comment]
```
$ nix-build -A python3.pkgs.pep517
error: attribute 'format' missing

       at /home/freddy/code/other/nixpkgs_2/pkgs/development/python-modules/flit-core/default.nix:7:25:

            6|
            7| buildPythonPackage rec {
             |                         ^
            8|   pname = "flit-core";
(use '--show-trace' to show detailed location information)
```

**Review by FRidh — CHANGES_REQUESTED** [review]
```
$ nix-build -A python3.pkgs.pep517
error: attribute 'format' missing

       at /home/freddy/code/other/nixpkgs_2/pkgs/development/python-modules/flit-core/default.nix:7:25:

            6|
            7| buildPythonPackage rec {
             |                         ^
            8|   pname = "flit-core";
(use '--show-trace' to show detailed location information)
```

**Comment by SuperSandro2000** [comment]
Reverted that. I thought format is propagated but whatever. Nothing that important.

**Pull request merged**
