### PR TITLE
Add package tpm2-tools (+ deps) to nixpkgs

### PR DESCRIPTION
**Pull request by delroth**
###### Motivation for this change
Nix doesn't have any tools to control TPM 2.0 devices, only TPM 1.2 (tpm-tools / trousers). This PR inits tpm2-tools, Intel's package for TPM 2.0 userland support.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ryantm** [comment]
@GrahamcOfBorg build ibm-sw-tpm2 tpm2-tss tpm2-tools

**Comment by delroth** [comment]
I think I fixed ibm-sw-tpm2 on Darwin -- could you re-trigger ofborg?

**Comment by ryantm** [comment]
@GrahamcOfBorg build ibm-sw-tpm2 tpm2-tss tpm2-tools

**Comment by delroth** [comment]
Marked ibm-sw-tpm2 as platforms.linux -- doesn't seem like upstream builds on MacOS properly (and I doubt it will be useful to anyone anyway, other than for running tpm2-tss tests).

The aarch64 failures seemed unrelated to this change though, seems like there's a dependency broken.

**Comment by ryantm** [comment]
Thanks!

**Pull request merged**
