### PR TITLE
Update pykms to 20190611, adapt pykms service

### LINKED ISSUE #81355: pykms service doesn't work in release 19.09 (and 18.03/18.09)
**Describe the bug**

The server from package pykms-20180208 doesn't work, thus the pykms service (which uses this package in release 19.09) doesn't work as well.

**To Reproduce**

Have the following in `configuration.nix`:
```
  environment.systemPackages = with pkgs; [
    pykms
  ];

  services.pykms.enable = true;
```

Be on release 19.09:
```
nix-channel --add https://nixos.org/channels/nixos-19.09 nixos
nix-channel --update
nixos-rebuild switch
```

And run:
```
$ client.py localhost
Connecting to localhost on port 1688...
Traceback (most recent call last):
  File "/nix/store/agy8v6vrp68h700pl76nc8xld8yj2sh2-pykms-20180208/lib/python3.7/site-packages/client.py", line 240, in <module>
    main()
  File "/nix/store/agy8v6vrp68h700pl76nc8xld8yj2sh2-pykms-20180208/lib/python3.7/site-packages/client.py", line 70, in main
    parsed = MSRPCRespHeader(response)
  File "/nix/store/agy8v6vrp68h700pl76nc8xld8yj2sh2-pykms-20180208/lib/python3.7/site-packages/dcerpc.py", line 632, in __init__
    MSRPCHeader.__init__(self, aBuffer, alignment)
  File "/nix/store/agy8v6vrp68h700pl76nc8xld8yj2sh2-pykms-20180208/lib/python3.7/site-packages/dcerpc.py", line 579, in __init__
    Structure.__init__(self,data, alignment)
  File "/nix/store/agy8v6vrp68h700pl76nc8xld8yj2sh2-pykms-20180208/lib/python3.7/site-packages/structure.py", line 87, in __init__
    self.fromString(data)
  File "/nix/store/agy8v6vrp68h700pl76nc8xld8yj2sh2-pykms-20180208/lib/python3.7/site-packages/structure.py", line 141, in fromString
    self[field[0]] = self.unpack(field[1], data[:size], dataClassOrCode = dataClassOrCode, field = field[0])
  File "/nix/store/agy8v6vrp68h700pl76nc8xld8yj2sh2-pykms-20180208/lib/python3.7/site-packages/structure.py", line 316, in unpack
    return self.unpack(two[0],data)
  File "/nix/store/agy8v6vrp68h700pl76nc8xld8yj2sh2-pykms-20180208/lib/python3.7/site-packages/structure.py", line 370, in unpack
    return unpack(format, data)[0]
struct.error: ('unpack requires a buffer of 1 bytes', "When unpacking field 'ver_major | B=5 | b''[:1]'")
```

**Expected behavior**

```
Connecting to localhost on port 1688...
Received V4 response
Response Hash has expected value: True
......
```

**Additional context**

As far as I remember, it is broken since release 2018-03. At that time, python3's version was changed from 3.6.5 to 3.7.x, which apparently caused the breakage (the way iterators work changed, or something). I think this problem was fixed by https://github.com/ThunderEX/py-kms/commit/57d51600c075fc8f121d62196a785ea5643eceb8 , but this version never made it into nixpkgs.

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.101, NixOS, 19.09.2166.ce9f1aaa39e (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(paul): `""`
 - channels(root): `"nixos-19.09.2166.ce9f1aaa39e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by pvgoran**
This updates the currently broken `pykms` package from 20180208 to 20190611 (with a new upstream), and adapts the `pykms` module to the changes (different binary names, `--logfile` option required).

###### Motivation for this change

Fixes #81355.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by peterhoeg** [comment]
Couple of things:

1. You need to do `git cherry-pick -x [commit]` to get the reference
2. We also need the nixos changes as the binary name has changed: 08f68313a47 and 81cd220c671

**Comment by pvgoran** [comment]
> Couple of things:
>     1. You need to do `git cherry-pick -x [commit]` to get the reference
>     2. We also need the nixos changes as the binary name has changed: [08f6831](https://github.com/NixOS/nixpkgs/commit/08f68313a47a2093dc0f408a706b2c125bc59c95) and [81cd220](https://github.com/NixOS/nixpkgs/commit/81cd220c67154ee7f7aaa4ea842a86fc39944d7f)

I added cherry-pick references, and added [81cd220](https://github.com/NixOS/nixpkgs/commit/81cd220c67154ee7f7aaa4ea842a86fc39944d7f). I don't think [08f6831](https://github.com/NixOS/nixpkgs/commit/08f68313a47a2093dc0f408a706b2c125bc59c95) is applicable: it's a tree-wide change which is orthogonal to the changes in question.

**Comment by pvgoran** [comment]
@peterhoeg While I'm at it, I also created #81366 to address some (perceived) shortcomings in the way logging is done in the package and the service.

**Comment by flokli** [comment]
We don't usually cherry-pick module system deprecations into already released release branches, so I'm not sure if a4e1cd3059e654a5d807c15e63c5e3197b9d481f can be cherry-picked.

Also, considering 20.03 being around the corner: Is this an issue in master and release-20.03 as well?

**Comment by peterhoeg** [comment]
> I don't think 08f6831 is applicable:

It touched the file so you would need to adapt the changes from there in the cherry-pick.

I'm with @flokli on not deprecating something in a release version - that's not going to fly.

Any chance you can wait for 20.03?

**Comment by flokli** [comment]
With 20.03 released 20.03 containing a later version, this can be closed.

**Pull request closed without merging**
