### PR TITLE
nixos-install: support -j, --cores and --option. Closes #6755

### LINKED ISSUE #6755: Support `nixos-install -j 4`
It would speed up the installation if `nixos-install` supported `--max-jobs` or `-j` parameter

### PR DESCRIPTION
**Pull request by lucabrunox**
Copied from nixos-rebuild, except I also added the doc in the manpage, stripping some other stuff not needed to know at installation time and hard to xref in docbook.

### CODE REVIEW

**Comment by iElectric** [comment]
Fixes #6755, do we want to keep the text about the options at one place?

**Comment by lethalman** [comment]
Nix does keep common options in one place, it could be done I guess.

**Comment by lethalman** [comment]
Btw I'm not sure nixos-rebuild should have the same docs as nixos-install. For example nixos-rebuild should also mention /etc/nix/nix.conf like nix-build does, whereas for nixos-install it would be only burden to read. I'd push this for now.

**Comment by lethalman** [comment]
Merging this for now, another time we can improve making docs more common for nixos tools.

**Pull request merged**
