### PR TITLE
uhd: 4.4.0.0 -> 4.5.0.0

### PR DESCRIPTION
**Pull request by doronbehar**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by hexagonal-sun** [comment]
LGTM.  I ran the update as documented and it looks as though it worked:

```
matthew@xin ~/D/nixpkgs (pkg/uhd)> nix-shell maintainers/scripts/update.nix --argstr package uhd --argstr commit true

Going to be running update for following packages:
 - uhd-4.5.0.0

Press Enter key to continue...

Running update for:
Preparing worktree (new branch 'update-tmpfftrsyp0')
Updating files: 100% (37477/37477), done.
HEAD is now at 4f03332c7031 uhd: 4.4.0.0 -> 4.5.0.0
 - uhd-4.5.0.0: UPDATING ...
 - uhd-4.5.0.0: DONE, no changes.
Deleted branch update-tmpfftrsyp0 (was 4f03332c7031).

Packages updated!
```

I wasn't aware of the `maintainers/scripts/update.nix` script; I've been executing the `update.sh` scripts manually.  In the case where the UHD update script is executed 'manually' we get:

```
./update.sh: line 7: $1: unbound variable
```

Maybe there should be a better error message in that case informing the user to use the above mechanism?

**Comment by doronbehar** [comment]
I'm more looking for a review regarding the utilities for instance, which I'm pretty sure you use :). And if you use a device supported that's even better.

**Comment by doronbehar** [comment]
@ofborg build gnuradio

**Comment by hexagonal-sun** [comment]
> I'm more looking for a review regarding the utilities for instance
Ah, apologies for the misunderstanding! I can confirm that the tools work correctly.

> And if you use a device supported that's even better.
Yes I have an N210 here which seem to work fine with this update.   I've tested the utilities as well as the UHD GNURadio block.

**Pull request merged**
