### PR TITLE
syncthing: 1.1.4 -> 1.2.0

### PR DESCRIPTION
**Pull request by emmanuelrosa**
###### Motivation for this change

The motivation for this change is to upgrade syntching from 1.1.4 to 1.2.0

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [X] other Linux distributions (Xubuntu)
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
   - [x] `syncthing-init` - failed; also fails with syncthing-1.1.4
   - [X] `syncthing-relay` - passed
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
   - [x] `syncthing-gtk`
   - [X] `qsyncthingtray`
   - [x] `syncthing-tray` 
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after): before = 59608632, after = 61636056
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

##### Release notes

- This release does not interoperate with Syncthing 0.14.45 or older.
- This release adds QUIC with NAT traversal as a new transport protocol. TCP is usually more performant and remains the preferred way of connection when possible.
- **This release adds automatic crash reporting. See https://docs.syncthing.net/users/crashrep.html for details.**
- This release makes large / variable block size the only available mode of operation; small / fixed blocks are deprecated. See https://docs.syncthing.net/advanced/folder-uselargeblocks.html for details.
- This release reverts the version naming change in #4586 (v1.1.4). Versions are now named with the time of their archiving, and the file modification time is unchanged when archiving. An exception to this is the "Trashcan" versioner which does not modify the name - instead it does set the file modification time the time of archiving.

---

### CODE REVIEW

**Review by jonringer — COMMENTED** [review]
while trying to use one of the binaries, i got this error:

```
./results/syncthing-gtk/bin/syncthing-gtk
Traceback (most recent call last):
  File "/nix/store/fgqzbqacdxi5jy1dy84adffvjn65br3x-syncthing-gtk-0.9.4/bin/..syncthing-gtk-wrapped-wrapped", line 38, in <module>
    from syncthing_gtk.app import App
  File "/nix/store/fgqzbqacdxi5jy1dy84adffvjn65br3x-syncthing-gtk-0.9.4/lib/python2.7/site-packages/syncthing_gtk/app.py", line 9, in <module>
    from gi.repository import Gtk, Gio, Gdk, GLib, GdkPixbuf
  File "/nix/store/kikf0730sv6d1wyzhmq6f1ihv3nfrh7c-python2.7-pygobject-3.32.1/lib/python2.7/site-packages/gi/importer.py", line 140, in load_module
    raise ImportError(e)
ImportError: Typelib file for namespace 'Pango', version '1.0' not found
```

**Comment by emmanuelrosa** [comment]
@jonringer I get the same error without this PR. How about you?

**Comment by emmanuelrosa** [comment]
Confirmed the tray apps do indeed work. The only things left are `syncthing-gtk` and the init NixOS test. Both of which are failing due to something other than this PR, but might as well fix them :)

**Comment by emmanuelrosa** [comment]
`syncthing-gtk` is now working :)

However, I had to manually edit the configuration generated by it's wizard (-1 command-line option) because it was incorrect; The `syncthing` WebUI URL port and API key were incorrect.

**Comment by emmanuelrosa** [comment]
The `syncthing-init` NixOS test is fixed. Finished!

**Comment by manveru** [comment]
@emmanuelrosa why was this closed?

**Comment by jonringer** [comment]
for what it's worth:

`nix-review` passes on NixOS
binaries seem to work

**Comment by emmanuelrosa** [comment]
Version 1.2.1 is out. I'm testing it.

Sent from ProtonMail mobile

-------- Original Message --------

**Pull request closed without merging**
