### PR TITLE
clightning: 23.08.1 -> 23.11

### PR DESCRIPTION
**Pull request by nepet**
## Description of changes

changelog: [https://github.com/ElementsProject/lightning/releases/tag/v23.11](https://github.com/ElementsProject/lightning/releases/tag/v23.11)

The `--disable-developer` flag got removed with this release. Developer builds are now always enabled and can be toggled at runtime by starting `lightningd` with the option `--developer`.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

CC @prusnak @jb55

### CODE REVIEW

**Comment by nepet** [comment]
Sorry for the changes cause by auto-formatting, I can patch them out if requested.

**Comment by prusnak** [comment]
> Sorry for the changes introduced by auto-formatting, I can patch them out if requested.

Yes, please revert the whitespace changes, amend the commit and do the force push.

**Comment by nepet** [comment]
Reverted the whitespace changes.

**Comment by nepet** [comment]
AFAIU it is a mix of both. `--developer` during runtime will enable dev features, basically all (or most ) of the options and commands that start with `dev-`. `--enable-debugbuild` will enable stuff that need to be set during compile time. So both combined replace the old `--enable-debug`.

**Comment by nepet** [comment]
Maybe I should change this in the release notes to make it more clear.

**Comment by prusnak** [comment]
> Maybe I should change this in the release notes to make it more clear.

Ah, okay. Only now I am noticing that you did the upstream release. 😄

**Comment by prusnak** [comment]
The [CI for x86_64 is failing](https://logs.ofborg.org/?key=nixos/nixpkgs.270897&attempt_id=731b108b-0c34-46df-ae67-1ae72aeb0d41) because of:

```
cc ccan/ccan/fdpass/fdpass.c
ccan/ccan/fdpass/fdpass.c:16:8: error: variable length array folded to constant array as an extension [-Werror,-Wgnu-folding-constant]
                char buf[CMSG_SPACE(sizeof(fd))];
                     ^
ccan/ccan/fdpass/fdpass.c:53:8: error: variable length array folded to constant array as an extension [-Werror,-Wgnu-folding-constant]
                char buf[CMSG_SPACE(sizeof(fd))];
```

1. Can you please fix the issue by applying the following patch?

``` patch
diff --git a/pkgs/applications/blockchains/clightning/default.nix b/pkgs/applications/blockchains/clightning/default.nix
index c1f06de0f1cb..d4fa4c68fe26 100644
--- a/pkgs/applications/blockchains/clightning/default.nix
+++ b/pkgs/applications/blockchains/clightning/default.nix
@@ -57,6 +57,11 @@ stdenv.mkDerivation rec {
 
   enableParallelBuilding = true;
 
+  # workaround for build issue, happens only x86_64-darwin, not aarch64-darwin
+  # ccan/ccan/fdpass/fdpass.c:16:8: error: variable length array folded to constant array as an extension [-Werror,-Wgnu-folding-constant]
+  #                 char buf[CMSG_SPACE(sizeof(fd))];
+  env.NIX_CFLAGS_COMPILE = lib.optionalString (stdenv.isDarwin && stdenv.isx86_64) "-Wno-error=gnu-folding-constant";
+
   meta = with lib; {
     description = "A Bitcoin Lightning Network implementation in C";
     longDescription = ''
```

2. Can you please report the issue upstream?

I tried aarch64_darwin locally and this one went fine, so no changes needed there.

**Comment by nepet** [comment]
Applied the patch.

**Pull request merged**
