### PR TITLE
scons: 4.1.0 -> 4.3.0

### LINKED ISSUE #156326: Update scons to 4.3.0
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: scons

current version: 4.1.0
desired version: 4.3.0

###### Notify maintainers

maintainers: @andir 

###### Note for maintainers

Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by alyssais**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by QuantMint** [comment]
#156326

**Comment by alyssais** [comment]
Thanks, I missed your PR.

**Comment by alyssais** [comment]
Oh wait, it wasn't a PR, lol. :)

**Comment by simplejack-src** [comment]
Could I get a patch added to this? (To give a better out-of-box experience for us NixOS users) Namely:


```
diff --git a/../base/SCons/Platform/posix.py b/SCons/Platform/posix.py
index 75b6c0b..0bfb461 100644
--- a/../base/SCons/Platform/posix.py
+++ b/SCons/Platform/posix.py
@@ -28,6 +28,7 @@ will usually be imported through the generic SCons.Platform.Platform()
 selection method.
 """
 
+import os
 import platform
 import subprocess
 
@@ -82,7 +83,7 @@ def generate(env):
 
     if 'ENV' not in env:
         env['ENV']        = {}
-    env['ENV']['PATH']    = '/usr/local/bin:/opt/bin:/bin:/usr/bin:/snap/bin'
+    env['ENV']['PATH']    = os.environ["PATH"]
     env['OBJPREFIX']      = ''
     env['OBJSUFFIX']      = '.o'
     env['SHOBJPREFIX']    = '$OBJPREFIX'
```

**Comment by Luflosi** [comment]
Can you elaborate on your patch? How does it "give a better out-of-box experience for us NixOS users"? What happens without this patch?

**Comment by simplejack-src** [comment]
Without the above patch, SCons tools are not found (since they don't exist in the standard Linux FHS locations). To rectify, either a line like above needs to be added to a default tool or to the SConstruct file itself.

SCons has a rationale for checking specific locations (vs. just using PATH). In particular this is to aid in making additional tools use more explicit (and aid reproducibility). However, in the NixOS case (and possibly Nix in general, depending on a users use-case), this is unnecessary (and in fact a wrong assumption) as we choose what we want available (via nix-shell/nix-env/configuration.nix/etc.) in our shells and accessible under PATH.

**Comment by simplejack-src** [comment]
** Just in case it wasn't apparent, that above patch would be against the SCons source (added via the ```patches = ``` build step in the Nix package file).

**Comment by Luflosi** [comment]
@alyssais what do you think about the patch?

**Comment by Et7f3** [comment]
Tested the patch on 4.1.0 and I approve. I wonder how without this patch package in nixpkgs compile 🤔.

**Comment by zhaofengli** [comment]
Also 4.4.0 was [released](https://github.com/SCons/scons/releases/tag/4.4.0) in July.

**Comment by wegank** [comment]
Closed by #222960.

**Pull request closed without merging**
