### PR TITLE
vimPluginsUpdater: run using @r-ryantm

### PR DESCRIPTION
**Pull request by PerchunPak**
Tested this locally, and it doesn't get rate limited. Though r-ryantm has a lot of other requests going in the background 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

CC @NixOS/neovim

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by khaneliman — APPROVED** [review]
LGTM, saw @zowoq recommend it on matrix so we can try it out and see if it works if infra is okay with it.

**Review by GaetanLepage — APPROVED** [review]

**Review by teto — APPROVED** [review]

**Comment by PerchunPak** [comment]
I think, r-ryantm doesn't open a PR if it triggers more than 100 rebuilds

**Comment by zowoq** [comment]
>  r-ryantm doesn't open a PR if it triggers more than 100 rebuilds.

This only applies to `buildPythonPackages`. The only other rebuild condition is if a PR causes > 500 rebuilds on x86_64-linux it will open the PR on staging instead of master.

**Review by GaetanLepage — APPROVED** [review]

**Comment by zowoq** [comment]
> https://nixpkgs-update-logs.nix-community.org/vimPluginsUpdater/2024-12-20.log
> Package version did not change.

It ran but it got caught on a check that was added to `nixpkgs-update` to prevent lockfile only updates. I'll add an exemption and try to run it again.

**Comment by zowoq** [comment]
> https://nixpkgs-update-logs.nix-community.org/vimPluginsUpdater/2024-12-30.log
```
Received ExitFailure 1 when running
Raw command: git commit -am "vimPluginsUpdater: 0.1 -> 0.1"
Standard output:

On branch auto-update/vimPluginsUpdater
nothing to commit, working tree clean
```
Seems the bot fails if the update has already been committed. I'll need to fix this in nixpkgs-update.

**Comment by PerchunPak** [comment]
@zowoq the bot failed again with `Package version did not change.`

https://r.ryantm.com/log/vimPluginsUpdater/2025-01-10.log

**Comment by zowoq** [comment]
Sorry, haven't got this working yet, want to fix this properly so it works for other packages rather than just adding an exemption but the bot code make some assumptions about commit handling.

**Pull request merged**
