### PR TITLE
firefox-bin: 43.0.4 -> 44.0

### PR DESCRIPTION
**Pull request by taku0**
- Various security fixes
- Improved warning pages for certificate errors and untrusted connections
- Enable H.264 if system decoder is available
- Enable WebM/VP9 video support on systems that don't support MP4/H.264
- In the animation-inspector timeline, lightning bolt icon next to animations running on the compositor thread
- Support the brotli compression format via HTTPS content-encoding
- Screenshot commands allow user choice of pixel ratio in Developer Tools
- To support unicode-range descriptor for webfonts, font matching under Linux now uses the same font matching code as other platforms
- Firefox has removed support for the RC4 decipher
- Firefox will no longer trust the Equifax Secure Certificate Authority 1024-bit root certificate or the UTN - DATACorp SGC to validate secure website certificates
- Stricter validation of web fonts

https://www.mozilla.org/en-US/firefox/44.0/releasenotes/

This version still use sha256 since sha512 is not supported by nixpkgs yet (#12645).

### CODE REVIEW

**Comment by ericsagnes** [comment]
@taku0 

> To support unicode-range descriptor for webfonts, font matching under Linux now uses the same font matching code as other platforms

Does that mean that firefox is not using `fontconfig` settings anymore?
In the latest unstable firefox 44.0.2 japanese text rendering look broken. (was working fine in 43.0.4)

firefox-44 0 2-font

I just would like to know if this is a upstream issue or something that can be fixed in nixpkgs.

**Comment by taku0** [comment]
@ericsagnes It seems so. When Chinese fonts (e.g. source-han-sans-simplified-chinese and source-han-sans-traditional-chinese) are installed alongside Japanese fonts (source-han-sans-japanese), font rendering for Japanese glyphs are broken. It worked fine in 43. If Chinese fonts are not installed, it works fine.

**Comment by ericsagnes** [comment]
@taku0 Thanks for confirming, I will use firefox 43 until upstream fix this.

**Comment by ericsagnes** [comment]
In case somebody have the same issue and reach this page, the new font matching can be disabled in `about:config` by setting `gfx.font_rendering.fontconfig.fontlist.enabled` to `false`.
The issue [will be fixed](https://bugzilla.mozilla.org/show_bug.cgi?id=1243226) in firefox 45.

**Pull request merged**
