### PR TITLE
llvmPackages_19: 19.1.0-rc2 -> 19.1.0-rc3

### PR DESCRIPTION
**Pull request by RossComputerGuy**
## Description of changes

Last 19.1.0-rc, in ~2 weeks is the full 19.1.0 release.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by RossComputerGuy** [comment]
@ofborg build llvmPackages_19.clang

**Comment by emilazy** [comment]
Result of `nixpkgs-review pr 336228` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages marked as broken and skipped:</summary>
  <ul>
    <li>faust2alqt</li>
    <li>faust2alsa</li>
    <li>faust2jack</li>
    <li>faust2jaqt</li>
    <li>faust2sc</li>
  </ul>
</details>
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>llvmPackages_19.lldb-manpages</li>
    <li>llvmPackages_19.openmp</li>
    <li>llvmPackages_19.openmp.dev</li>
  </ul>
</details>
<details>
  <summary>44 packages built:</summary>
  <ul>
    <li>bolt_19 (llvmPackages_19.bolt)</li>
    <li>bolt_19.dev (llvmPackages_19.bolt.dev)</li>
    <li>clang_19 (llvmPackages_19.clang ,llvmPackages_19.libcxxClang)</li>
    <li>emscripten</li>
    <li>faust (faust2)</li>
    <li>faust2csound</li>
    <li>faust2firefox</li>
    <li>faust2jackrust</li>
    <li>faust2ladspa</li>
    <li>faust2lv2</li>
    <li>lld_19 (llvmPackages_19.lld)</li>
    <li>lld_19.dev (llvmPackages_19.lld.dev)</li>
    <li>lld_19.lib (llvmPackages_19.lld.lib)</li>
    <li>lldb_19 (llvmPackages_19.lldb)</li>
    <li>lldb_19.dev (llvmPackages_19.lldb.dev)</li>
    <li>llvmPackages_19.clang-manpages</li>
    <li>llvmPackages_19.clang-tools</li>
    <li>llvmPackages_19.libclang (llvmPackages_19.clang-unwrapped)</li>
    <li>llvmPackages_19.libclang.dev (llvmPackages_19.clang-unwrapped.dev)</li>
    <li>llvmPackages_19.libclang.lib (llvmPackages_19.clang-unwrapped.lib)</li>
    <li>llvmPackages_19.libclang.python (llvmPackages_19.clang-unwrapped.python)</li>
    <li>llvmPackages_19.clangNoLibcNoRt (llvmPackages_19.clangNoCompilerRt)</li>
    <li>llvmPackages_19.clangNoCompilerRtWithLibc</li>
    <li>llvmPackages_19.clangNoLibc (llvmPackages_19.clangNoLibcWithBasicRt)</li>
    <li>llvmPackages_19.clangNoLibcxx (llvmPackages_19.clangWithLibcAndBasicRt)</li>
    <li>llvmPackages_19.clangUseLLVM</li>
    <li>llvmPackages_19.clangWithLibcAndBasicRtAndLibcxx</li>
    <li>llvmPackages_19.compiler-rt (llvmPackages_19.compiler-rt-libc ,llvmPackages_19.compiler-rt-no-libc)</li>
    <li>llvmPackages_19.compiler-rt.dev (llvmPackages_19.compiler-rt-libc.dev)</li>
    <li>llvmPackages_19.libcxx</li>
    <li>llvmPackages_19.libcxx.dev</li>
    <li>llvmPackages_19.stdenv (llvmPackages_19.libcxxStdenv)</li>
    <li>llvm_19 (llvmPackages_19.llvm)</li>
    <li>llvm_19.dev (llvmPackages_19.llvm.dev)</li>
    <li>llvm_19.lib (llvmPackages_19.llvm.lib)</li>
    <li>llvm_19.python (llvmPackages_19.llvm.python)</li>
    <li>llvmPackages_19.libstdcxxClang</li>
    <li>llvmPackages_19.libunwind</li>
    <li>llvmPackages_19.libunwind.dev</li>
    <li>llvmPackages_19.lldbPlugins.llef</li>
    <li>llvmPackages_19.llvm-manpages</li>
    <li>llvmPackages_19.mlir</li>
    <li>llvmPackages_19.mlir.dev</li>
    <li>tests.cc-wrapper.llvmTests.llvmPackages_19.clang (tests.cc-wrapper.llvmTests.llvmPackages_19.libcxx)</li>
  </ul>
</details>

Is the OpenMP issue pre‐existing?

**Comment by RossComputerGuy** [comment]
> Is the OpenMP issue pre‐existing?

What OpenMP issue?

**Comment by RossComputerGuy** [comment]
Looks like it's been happening for some time https://hydra.nixos.org/job/nixpkgs/trunk/llvmPackages_19.openmp.aarch64-darwin

**Review by alyssais — APPROVED** [review]

**Pull request merged**
