### PR TITLE
Revert "wireguard-tools: allow system resolvconf implementation if available"

### PR DESCRIPTION
**Pull request by zx2c4**
Reverts NixOS/nixpkgs#139530

This should never have been committed.

### CODE REVIEW

**Review by Ma27 — APPROVED** [review]
I'd like to await other feedback, but considering that this broke someone's use-case and the author of this packages strongly advises against it, I'm :+1: 

Also, as a reminder, we should check if this is now in release-21.11 (branch-off was yesterday in my tz), if that's the case and we revert, it should happen there as well.

**Comment by zx2c4** [comment]
I will not discuss this further here. If you want to discuss the patch itself, resume discussion on the original PR. The burden of argument is when submitting a patch. You can't just submit a patch, merge it prematurely, and then shift that same burden to its revert. So for that reason I'd appreciate you reverting this sooner rather than later, and then we can resume discussion on a more proper basis.

**Comment by SuperSandro2000** [comment]
Oh well... That didn't go to plan. Sorry. 😅 

The root cause of the issue is that systemd also has a resolvconf program which is a symlink to resolvectl which obviously will not work. I assumed changing the PATH order wouldn't break anything and only improve the situation for some people to make wireguard work for them. Since @Mic92 is a maintainer of this package and in addition to that a well known and trusted community member and also @Artturin said this should improve the current situation I thought I could safely count on there knowledge about nix but mistakes happen.

PS: I wouldn't mind if you could be a bit more chilled about this. Mistakes happen and the discussion in the other PR evolved around what is the perfect solution which this never claimed to be and how nix should decide on which resolvctl to use which would also require a bigger refactor and would be totally out of scope of the PR. It was supposed to be a stop gap one off hack solution to make the situation a little bit better not a perfect solution.

**Comment by zx2c4** [comment]
I'll follow up on the original PR with some suggestions.

**Pull request merged**
