### PR TITLE
[20.09] gitlab: 13.0.14 -> 13.6.0

### PR DESCRIPTION
**Pull request by ghost**
###### Motivation for this change

Backport of https://github.com/NixOS/nixpkgs/pull/99116

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ajs124** [comment]
Does this actually work?
I'm seeing this in my logs and git things don't actually seem to work: 
```
gitaly[2024]: time="2020-11-23T17:50:05+01:00" level=fatal msg="unsupported Git version: \"2.28.0\""
```

**Comment by petabyteboy** [comment]
I didn't to much testing other than running the NixOS test, so it's definitely possible. Sorry about that.
I would port git 2.29.2 as a seperate attribute and change GitLab things to use that. Does that idea sound good to you?

**Comment by kyren** [comment]
In addition to running into the gitaly issue requiring git >= 2.29, I also ran into another issue when upgrading 20.09.

If your system.stateVersion is < 20.03, then your gitlab install may be using postgres_9_6 (even if, like me, you had never explicitly enabled postgresql).  Gitlab 13.0.x works with postgres 9, but 13.6.x seems to require at least postgresql 11.  Thus, after upgrading, gitlab 13.6 fails to run one of its version upgrade scripts and fails to start.

The only remedy is to upgrade postgres from 9 to 11 using the upgrade instructions here: https://nixos.org/manual/nixos/stable/index.html#module-services-postgres-upgrading

Ideally nothing like this would ever be required when upgrading *within* a channel, but if that's not possible, at least an assert that the postgresql version is >= 11 in the nixos module would have saved me from an unpleasant surprise.

**Comment by kyren** [comment]
Just also FYI for the gitaly issue for anybody who's not already familiar with nixpkgs overlays, adding this to your nixos configuration will fix gitlab until #104896 is merged:
```
  # HACK: gitaly in nixos-20.09 requires git 2.29, which isn't yet in 20.09.
  # Remove when https://github.com/NixOS/nixpkgs/pull/104896 is merged.
  nixpkgs.overlays = [
    (self: super: {
      git = super.git.overrideAttrs (old: rec {
        version = "2.29.2";
        src = self.fetchurl {
          url = "https://www.kernel.org/pub/software/scm/git/git-${version}.tar.xz";
          sha256 = "1h87yv117ypnc0yi86941089c14n91gixk8b6shj2y35prp47z7j";
        };
      });
    })
  ];
```

**Pull request merged**
