### PR TITLE
Revert "gmailctl: 0.10.0 -> unstable-2022-03-24"

### PR DESCRIPTION
**Pull request by doronbehar**
This reverts commit de5a0ee6fc3899d8dfd120e7659a7b74a728acec - PR https://github.com/NixOS/nixpkgs/pull/165955 .

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
No need to revert this.

unstable version is required because of https://github.com/mbrt/gmailctl/issues/232 and https://github.com/mbrt/gmailctl/commit/484bb689866987580e0576165180ef06375a543f

**Comment by doronbehar** [comment]
> No need to revert this.
> 
> unstable version is required because of [mbrt/gmailctl#232](https://github.com/mbrt/gmailctl/issues/232) and [mbrt/gmailctl@484bb68](https://github.com/mbrt/gmailctl/commit/484bb689866987580e0576165180ef06375a543f)

This is still unacceptable that you merge a PR of yours like that without waiting for approval from (active) maintainer, I was about to report you because I suspected it was an attempt to infect all Nixpkgs users of this package with malware coded into gmailctl. Never the less, please create another PR that adds a comment explaining why an unstable version is needed.

**Comment by SuperSandro2000** [comment]
> I was about to report you because I suspected it was an attempt to infect all Nixpkgs users of this package with malware coded into gmailctl.

I am not sure which got you thinking this could be malware.
The commit is from https://github.com/mbrt/gmailctl/commit/484bb689866987580e0576165180ef06375a543f which is the tip of master and this is the diff https://github.com/mbrt/gmailctl/compare/v0.10.0...master.

Also if I would like to introduce malware to all users I would choose a package that are more people using and do it a lot more sneaky.

But sure I can add a comment why we track unstable.

**Comment by doronbehar** [comment]
> I am not sure which got you thinking this could be malware.
> The commit is from [mbrt/gmailctl@484bb68](https://github.com/mbrt/gmailctl/commit/484bb689866987580e0576165180ef06375a543f) which is the tip of master and this is the diff [mbrt/gmailctl@v0.10.0...master](https://github.com/mbrt/gmailctl/compare/v0.10.0...master).

I thought this was malware before you explained why you created the PR - that's the whole point of explaining yourself, especially when a change is not trivial or common.

**Pull request closed without merging**
