### PR TITLE
ghc: enable build on aarch64-darwin (aka Apple Silicon)

### PR DESCRIPTION
**Pull request by prusnak**
###### Motivation for this change

By upgrading prebuilt GHC binaries from 8.10.2 to 8.10.5 we enable bootstrap on aarch64-darwin.

-----

GHC on Darwin requires `ghc8102Binary` to bootstrap, but there are no official ghc 8.10.2 prebuilt binaries of aarch64-darwin. 

It seems the most straightforward change is to bump `ghc8102Binary` (8.10.2) to `ghc8105Binary` (8.10.5) in order to bring aarch64-darwin support for GHC.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
I'm a bit scared to remove GHC 8.10.2 to be honest, since significant work has flown into that recently and upstream [isn't really happy](https://mail.haskell.org/pipermail/glasgow-haskell-users/2021-August/027037.html) with the latest GHC releases, but maybe it's safe — difficult to tell without testing.

cc-ing @nh2 who has most recently worked on `ghc8102Binary` and has an interest in the musl binary GHC.

An option I could think of as well would be to have a `ghc8105Binary` (or `ghc8106Binary`) exclusively for bootstrapping `aarch64-darwin` for now and postpone upgrading until we have a GHC 8.10.7 release which finally puts an end to this saga. This would also avoid a full rebuild of the `haskellPackages` set, meaning we could potentially land this faster.

Would like to hear other opinions as well, haven't quite made my mind up yet.

**Comment by prusnak** [comment]
> upstream [isn't really happy](https://mail.haskell.org/pipermail/glasgow-haskell-users/2021-August/027037.html) with the latest GHC releases

I see. I guess we should wait for 8.10.7 and introduce ghc8107Binary instead (as the latest of 8.10.x series).

Whether to use `ghc8107Binary` for everything or just for aarch64-darwin is another question. I'll leave the decision up to the Haskell maintainers and update this PR accordingly.

**Comment by cdepillabout** [comment]
@sternenseemann has mentioned to me that GHC doesn't like to be reverse bootstrapped.  So this means that you might not be able to use a new `ghc8107Binary` for bootstrapping our current `ghc8106`.  I'm not sure if this will end up making things harder for you.

Although I think @sternenseemann was saying that there may have been a patch applied that allowed some older versions of GHC to be reverse bootstrapped.

You might be well aware of this, but I wasn't when I heard it first.

**Comment by maralorn** [comment]
Well, there is no ghc 8107 as of now, binary or otherwise. And when we bump to using 8107 we can also go to a newer binary.

**Comment by prusnak** [comment]
> has mentioned to me that GHC doesn't like to be reverse bootstrapped

We already bootstrap GHC 8.8.4 using GHC 8.10.2 for aarch64 and musl: https://github.com/NixOS/nixpkgs/blob/076b80d0859de5bbcb60e03b7fde14b726994b10/pkgs/top-level/haskell-packages.nix#L60-L70

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 135345` at c6da7b96 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages skipped due to time constraints:</summary>
  <ul>
    <li>haskell.compiler.ghc901</li>
    <li>haskell.compiler.ghcHEAD</li>
    <li>haskell.compiler.integer-simple.ghc901</li>
    <li>haskell.compiler.native-bignum.ghcHEAD</li>
  </ul>
</details>
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>haskell.compiler.ghc8105Binary</li>
    <li>haskell.compiler.ghc8105BinaryMinimal</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/name-and-version.md">name-and-version</a>

Did you mean to pass `pname` instead of `name` to `mkDerivation`?

Near pkgs/development/compilers/ghc/8.10.5-binary.nix:150:3:
```
    |
150 |   name = "ghc-${version}-binary";
    |   ^
```

Near pkgs/development/compilers/ghc/8.10.5-binary.nix:148:10:
```
    |
148 |   inherit version;
    |          ^
```
</li>
  </ul>
</details>

**Comment by domenkozar** [comment]
@prusnak do you plan to make the changes for only aarch64-darwin use the new binary dist?

**Comment by prusnak** [comment]
> @prusnak do you plan to make the changes for only aarch64-darwin use the new binary dist?

I can do it, sure.

**Comment by prusnak** [comment]
I reworked the PR to use `ghc8105Binary` only to bootstrap `aarch64-darwin`.

**Comment by prusnak** [comment]
It seems that ghc-8.10.6 bootstrapped via ghc-8.10.5-binary segfaults on aarch64-darwin. :-/

Will try to bootstrap with 8.10.6-binary.

**Comment by prusnak** [comment]
> Will try to bootstrap with 8.10.6-binary.

Hm, same issue, so it's not worth changing the PR from  8.10.5-binary to 8.10.6-binary.

**Comment by domenkozar** [comment]
Thanks - building to see if it works here.

**Comment by domenkozar** [comment]
@prusnak are you sure you're getting a segfault? I can compile ghc, but it gets killed (most likely due to missing signing)

**Comment by prusnak** [comment]
> @prusnak are you sure you're getting a segfault? I can compile ghc, but it gets killed (most likely due to missing signing)

```
$ ghc 
Killed: 9
```

I quickly assumed this meant segfault, but only now I realise that SIGSEGV is signal 11, so you are right. It was not a segfault, the process was killed.

**Comment by sternenseemann** [comment]
> > @prusnak are you sure you're getting a segfault? I can compile ghc, but it gets killed (most likely due to missing signing)
> 
> ```
> $ ghc 
> Killed: 9
> ```
> 
> I quickly assumed this meant segfault, but only now I realise that SIGSEGV is signal 11, so you are right. It was not a segfault, the process was killed.

Try running `log stream` and running this again, it'll tell you the precise problem (probably something like <https://github.com/NixOS/nixpkgs/issues/132660> or code signing).

**Comment by prusnak** [comment]
> it'll tell you the precise problem

Correct. This is a code-signing issue and most possibly related to #132660

```
2021-08-24 10:56:31.450563+0200 0x54136d   Default     0x0                  0      0    kernel: ignoring detached code signature on 'ghc' with cdhas    h '6b0c137429d3d8ff8ff96c9a633485395fe95f25' because it is invalid, or not a simple adhoc signature.
2021-08-24 10:56:31.450736+0200 0x54136e   Default     0x0                  0      0    kernel: CODE SIGNING: process 30727[ghc]: rejecting invalid     page at address 0x104344000 from offset 0x0 in file "/nix/store/2zjkgh2c1lp4j10xdlgyrfs4jlj641dv-ghc-8.10.6/lib/ghc-8.10.6/bin/ghc" (cs_mtime:1.0 ==     mtime:1.0) (signed:1 validated:1 tainted:1 nx:0 wpmapped:0 dirty:0 depth:0)
```

**Comment by domenkozar** [comment]
I've managed to get it to work!

See the patch in https://dpaste.com/AQQEZTU4D

**Comment by prusnak** [comment]
> I've managed to get it to work!

Thanks, trying to update my PR to include your change(s)

**Comment by prusnak** [comment]
Applied suggestions by @domenkozar in 3fe098d20f0961ca21d4c150cc5e6a9716973c48 and 5226d5017553fbe6ea29588af5d767fc9a4d6b1e

**Comment by domenkozar** [comment]
Thanks @thefloweringash for spotting that.

I've tested the current changes and ghc compiles. Once ofborg confirms it no longer rebuilds all packages for darwin I will merge this as it improves ghc situation for aarch64-darwin while staging/haskell-updates don't yet build that platform.

**Pull request merged**
