### PR TITLE
gnomeExtensions: auto-update

### PR DESCRIPTION
**Pull request by rhoriguchi**
###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by piegamesde** [comment]
Thank you for doing these. Please have a look at the collision and add it to `extensionRenames.nix`. Note that we already have a manually packaged version of `unredirect@vaina.lt`, and that we are using a custom name due to backwards compatibility.

**Comment by rhoriguchi** [comment]
> Thank you for doing these. Please have a look at the collision and add it to `extensionRenames.nix`. Note that we already have a manually packaged version of `unredirect@vaina.lt`, and that we are using a custom name due to backwards compatibility. (Also, feel free to ping me for review on anything extensions-related)

I've seen the new entry but left it because of https://github.com/NixOS/nixpkgs/blob/933dab8b5f6c44ff8135ab875ca10b9de704876d/pkgs/desktops/gnome/extensions/extensionRenames.nix#L74 since this causes no collision. Should I rename it to `disable-unredirect-fullscreen-windows-2`?

**Comment by piegamesde** [comment]
You are right, *technically* there is no collision. However I would find it weird to know one as `disable-unredirect` and the other as `disable-unredirect-fullscreen-windows`. I'd suggest to stick with our current custom name and call it `disable-unredirect-2`. What do you think? Alternatively, we can also add a mechanism so that our extension is known under both names.

**Comment by rhoriguchi** [comment]
> disable-unredirect-fullscreen-windows

IMO it makes more sense to call it the same as it is found on <https://extensions.gnome.org>. Since that is the name a user is used to and will probably search for. What would make sense is to create an alias for the other extension and that way we can call the new one `disable-unredirect-fullscreen-windows-2`.

**Comment by piegamesde** [comment]
Alias sounds good. I have a small concern about potential collisions on the aliased name: they won't be caught by our `collisions.json`. On the other hand, this is kind of true for a lot of attributes in the `gnomeExtensions` set so it wouldn't make things worse.

**Review by piegamesde — APPROVED** [review]

**Comment by rhoriguchi** [comment]
@piegamesde let me make an other update since some time has passed.

**Pull request merged**
