### PR TITLE
nixos/amazon-ec2-amis: Add NixOS 23.11

### PR DESCRIPTION
**Pull request by arianvp**
## Description of changes

These were uploaded by https://github.com/NixOS/amis

Note that this list will stop being updated from now on. Please use https://nixos.github.io/amis/ and https://nixos.github.io/amis/images.json instead. We are working on integrating this in the https://nixos.org/ website These get updated for every channel bump.

This should be enough to get the website listing them again. But we'll work to get the website get the data from  https://nixos.github.io/amis/ for 24.05

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by arianvp** [comment]
This might warrant a release note. But how does that work with backports? Do I want to backport the release note too?

**Comment by zimbatm** [comment]
Yeah, that would make sense to me. People looking at the 23.11 release note want to find the AMIs.

**Comment by arianvp** [comment]
I now added release notes to both 23.11 and 24.05. I'm not sure if this is the "right" way to do it?  Should I only add the 23.11 release notes on the 23.11 release branch? Or what is etiquette here?

**Review by zimbatm — APPROVED** [review]
LGTM

**Review by garbas — APPROVED** [review]

**Comment by arianvp** [comment]
I don't know how to make it more clear than the PR description

> Note that this list will stop being updated from now on. Please use https://nixos.github.io/amis/ and https://nixos.github.io/amis/images.json instead

**Comment by arianvp** [comment]
Basically AMIs are constantly uploaded now for every channel bump. They differ in that the one is newer than the other.

**Comment by AleXoundOS** [comment]
@arianvp, thank you very much for the explanation. It's clear now.

**Comment by arianvp** [comment]
I can maybe add a toggle to the website to only show the latest AMI by default.

**Comment by AleXoundOS** [comment]
@arianvp, maybe it would be even better to put the explanation above onto the website page. I mean: when (and maybe how) NixOS AMIs get built to be published on https://nixos.github.io/amis/. Also, brief explanation of the correlation with amazon-ec2-amis.nix and its destiny can help for those who were unaware.

**Pull request merged**
