### PR TITLE
Remove test-pkgs, buildPackages, and buildFreebsd from excluded-attrnames-at-any-depth

### PR DESCRIPTION
**Pull request by philiptaron**
- #324619

## Description of changes

The test (`nix-build pkgs/test/release/default.nix`) continues to pass.

These lines were added in https://github.com/NixOS/nixpkgs/pull/269356.

There is no difference in the package names generated.

## Things done

- [x] Tested, as applicable:
  - [x] `nix-build pkgs/test/release/default.nix`
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by infinisil — APPROVED** [review]
Needs a rebase, but I tested `nix-build pkgs/test/release` when merging this into current master, still works, so this LGTM!

**Comment by philiptaron** [comment]
Thanks, rebased.

**Comment by paparodeo** [comment]
removing `test-pkgs` seems like it creates a cycle in `freshBootstrapTools.test-pkgs` as shown by:
```
nix-instantiate  --eval --strict -E '(import ./pkgs/top-level/release-attrpaths-superset.nix { }).paths'  
```

**Comment by philiptaron** [comment]
PR immediately accepted and merged. I bet you're on Darwin. All my testing (and the CI checks) are on x86_64-linux, and I've noticed that these tests are incredibly sensitive to which system they're evaluated for.

**Comment by paparodeo** [comment]
thought I was on linux but seems like was logged into aarch64-darwin machine while running tests

**Pull request merged**
