### PR TITLE
julia.withPackages: add thomasjm as maintainer

### PR DESCRIPTION
**Pull request by thomasjm**
## Description of changes

I wanted to add myself as maintainer for the `julia.withPackages` stuff. Hopefully this is a good way to do so. I tested it in the Nix repl for all the current Julia versions.

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NickCao** [comment]
Or just add yourself to the maintainers of julia?

**Comment by thomasjm** [comment]
To each of the ~5 different versions like `1.9.nix`, `1.9-bin.nix`, etc.? I can do that if you prefer.

(I wonder if there could be a Julia team in `team-list.nix`?)

**Comment by NickCao** [comment]
> To each of the ~5 different versions like `1.9.nix`, `1.9-bin.nix`, etc.? I can do that if you prefer.

Yes

> (I wonder if there could be a Julia team in `team-list.nix`?)

Sure, we can do this later.

**Comment by thomasjm** [comment]
Done. I included a commit to put Julia's `meta` on the `julia.withPackages` environment.

**Review by NickCao — APPROVED** [review]

**Pull request merged**
