### PR TITLE
Add library function for building Stack projects.

### PR DESCRIPTION
**Pull request by mboes**
Haskell Stack now has first-class support for Nix environments. If
a project has a `shell.nix` file, building in the environment can be
done in one of two ways:

```
$ nix-shell
$ buildPhase
```

or equivalently for those that are not familiar with Nix commands,

```
$ stack [--nix] build
```

See [here](www.tweag.io/blog/stack-nix-portable-reproducible-builds) and[here](https://github.com/commercialhaskell/stack/blob/master/doc/nix_integration.md) for more background.

But to write a valid `shell.nix` file that works with Stack, currently
one needs to include a few details that essentially leak
implementation concerns, which at any rate makes it all a rather
verbose experience.

This PR proposes to add a Stack project "builder" to Nixpkgs. It's
a single function mapped to `haskell.buildStackProject`, modeled on
similar precedents in Nixpkgs such as `buildRustPackage` and
`melpaBuild`. Example usage:

```
haskell.buildStackProject {
  name = "HaskellR";
  buildInputs = [ python34Packages.ipython R zeromq zlib ];
}
```

The above determines an environment including the system dependencies
needed for letting `stack` compile the whole project including its
Haskell dependencies. Conceptually, this feature is similar to
`python3.buildEnv`.

Two things to note:
1. the intention here is to let users manage their Haskell
   dependencies via Stack, as Stack users normally do (so Nix only
   handles system dependencies).
2. stack projects are not Haskell packages. Stack's notion of
   "project" is more closely related to the Nix notion of
   "environment" than it is to the Nix notion of "package". Projects
   are composed of packages. Projects can't depend on other projects.

### CODE REVIEW

**Comment by jagajaga** [comment]
Please follow the rules of commit naming http://hydra.nixos.org/build/28700773/download/1/nixpkgs/manual.html#chap-submitting-changes.

**Comment by aristidb** [comment]
@jagajaga It's neither really a package nor a service, which naming rule would apply?

**Comment by jagajaga** [comment]
@aristidb because it's style?

**Comment by deepfire** [comment]
@jagajaga, as far as I can see, it was a question of /what/, not /why/.

**Comment by jagajaga** [comment]
Oh, I need to go to sleep :(

I think that we should name it like it's named: `haskell (or haskell support): enhancement`

**Comment by domenkozar** [comment]
cc @peti

**Comment by peti** [comment]
1. I believe this function should be provided by `haskell.lib` from `pkgs/development/haskell-modules/lib.nix`, where other support functions live, too. 

2. User documentation in `doc/haskell-users-guide.md` feels highly desirable for that code.

**Comment by mboes** [comment]
I have added a new section to the user guide regarding this. Furthermore, I updated the existing section discussing what to do when Stack complains about a missing system library.

As for the name, I submit that `haskell.buildStackProject` is more consistent with the established jurisprudence than `haskell.lib.*`. This function is not a short utility function in the sense of the other functions found in `pkgs/development/haskell-modules/lib.nix`. It's a wrapper around `mkDerivation` that plays the same role as `perl.buildPerlPackage`, `python.buildPythonPackage` or `rPackages.buildRpackage`, so I thought that this function should be similarly placed in the attribute hierarchy. I did rename the file name though, from `pkgs/build-support/haskell/stack.nix` next to where `buildRustPackage` is defined, to `pkgs/development/haskell-modules/generic-stack-builder.nix`.

I don't know if that's a better place.

**Comment by mboes** [comment]
@peti ping. :)

**Comment by mboes** [comment]
Stack's Nix support is becoming increasingly popular. I think adding this library function greatly enhances maintainability for those who need to write custom shell files. Any chance someone might have a look at this (fairly short) PR?

**Comment by jagajaga** [comment]
@peti ?

**Comment by peti** [comment]
Well, I'm basically in favor of the change, but I'm unhappy about the notion of adding this function to the top-level of the `haskell` namespace. Currently, we have `haskell.compiler` for compilers, `haskell.packages`  for package sets, and `haskell.lib` for functions. I'd prefer `buildStackProject` to live in `haskell.lib` hierarchy -- where it belongs, IMHO.

**Comment by Profpatsch** [comment]
(triage) @mboes What’s the status?

**Comment by mboes** [comment]
I believe I have addressed @peti's last comment in this latest commit.

**Comment by AlleaRizary** [comment]
hi which one should i use? haskell.lib.buildStackProject or haskell.buildStackProject??

**Pull request merged**
