### PR TITLE
[20.09] python3Packages.word2vec: fix build and tests

### PR DESCRIPTION
**Pull request by wkral**
(cherry picked from commit 6a4e785931e8e9ccd008f43cff2126861f2f182d)

###### Motivation for this change
ZHF: #97479

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wkral** [comment]
Result of `nixpkgs-review pr 98223` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python37Packages.word2vec</li>
    <li>python38Packages.word2vec</li>
  </ul>
</details>

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 98223 [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>2 packages built:</summary>  <ul>    <li>python37Packages.word2vec</li>    <li>python38Packages.word2vec</li>  </ul></details>

**Comment by wkral** [comment]
@jonringer noticed that this hasn't been merged, guessing just overlooked amongst the many PRs. If it does need work please let me know.

**Comment by jonringer** [comment]
i do a rebase, github probably had a merge right before this, and it failed to apply

**Pull request merged**
