### PR TITLE
chromium: 59.0.3071.115 -> 60.0.3112.90 (stable)

### LINKED ISSUE #25880: Cannot Install google-chrome (404).
## Issue description

I cannot upgrade my older installation of NixOs from the 16.09 channel to 17.03. I am getting 404 errors around google-chrome. Here is the error that I get:

```
building path(s) ‘/nix/store/j9gg9jq5kwkgf2iwxd43sg706kr619c2-google-chrome-stable_57.0.2987.110-1_amd64.deb’

trying https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_57.0.2987.110-1_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 

trying http://95.31.35.30/chrome/pool/main/g/google-chrome-stable/google-chrome-stable_57.0.2987.110-1_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found

trying http://mirror.pcbeta.com/google/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_57.0.2987.110-1_amd64.deb
Warning: Transient problem: timeout Will retry in 1 seconds. 3 retries left.
Warning: Transient problem: timeout Will retry in 2 seconds. 2 retries left.
Warning: Transient problem: timeout Will retry in 4 seconds. 1 retries left.
curl: (6) Couldn't resolve host 'mirror.pcbeta.com'

trying http://repo.fdzh.org/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_57.0.2987.110-1_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   185  100   185    0     0    578      0 --:--:-- --:--:-- --:--:--   579
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 
error: cannot download google-chrome-stable_57.0.2987.110-1_amd64.deb from any mirror
builder for ‘/nix/store/ma09gjhvhjl6036mldfn6wpfhq1dqxjf-google-chrome-stable_57.0.2987.110-1_amd64.deb.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/0w5ymgwxc61xnk59w2ir8yd7vbj89g0k-google-chrome-57.0.2987.110.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/cxpbg5kr91q1lrjvh7zlfwm8m6yxjk37-kernel-modules-shrunk’
cannot build derivation ‘/nix/store/4i4rjb076lxlgbdgg1ccrq3niriccq21-system-path.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/9cgbfk6habfmpk663qbg4g1plmq7pk3i-nixos-system-nixos-16.09.1942.28dc5c7d22.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/9cgbfk6habfmpk663qbg4g1plmq7pk3i-nixos-system-nixos-16.09.1942.28dc5c7d22.drv’ failed
```

### Steps to reproduce

Add google-chrome to the systemPackages

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
16.09.1903.c80a791 (Flounder)
* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.8
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"16.09.1942.28dc5c7d22"
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)
build-use-sandbox = false

### PR DESCRIPTION
**Pull request by neilmayhew**
60.0.3112.66 -> 61.0.3163.31 (beta)
61.0.3153.4  -> 62.0.3175.4  (dev)

This is the result of running the derivation's `update.sh` script.

Fixes #25880 (Cannot Install google-chrome)

###### Motivation for this change

`google-chrome` fails to build, because the debs it uses are no longer available. Its version info is pulled from `chromium` so the info needs to be fixed there.

**This needs to be cherry-picked to 17.03.**

###### Things done

Please check what applies. Note that these are not hard requirements but merely serve as information for reviewers.

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by pbogdan** [comment]
Cherry-picking this as-is on top of c40b85d4fd06613150cd665d22a4e98448662b2d (17.03 at the time of writing) seems to break the build of chromium stable for me.

**Comment by pbogdan** [comment]
Different error but seem to be getting a failure as well for chromium stable on top of 1b77c2950796d0235b2fe33551667c23ae95c2fb (current-ish master).

**Comment by Ericson2314** [comment]
See also https://github.com/NixOS/nixpkgs/pull/27822

**Comment by neilmayhew** [comment]
Closing this since #27822 addresses the build problems and this doesn't.

**Pull request closed without merging**
