### PR TITLE
dub: Updating (1.1.0 -> 1.5.0) and improving

### PR DESCRIPTION
**Pull request by ThomasMader**
###### Motivation for this change

- Updating 1.1.0 -> 1.5.0
- gcc not needed at all as dependency
- other D compilers can be used instead of dmd, so it's not good to use it as a runtime dependency.
- Adding checkPhase
- Improve package description.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ThomasMader** [comment]
###### TODO

- Need to wait for the final release of dub 1.5.0
- Add the interactive-remove.sh unittest because it should work with final 1.5.0 version. (see https://github.com/dlang/dub/issues/1224)
- Running the unittests only works with the fixes for dmd from https://github.com/NixOS/nixpkgs/pull/27743 so this PR needs to be merged first.

**Comment by ThomasMader** [comment]
This is ready to be merged from my side.

It's not building because it needs dmd which is not building on master but a fix for it comes with https://github.com/NixOS/nixpkgs/pull/28635.

**Comment by wtok** [comment]
What's the status on this now that #28635 is merged?

**Comment by ThomasMader** [comment]
https://github.com/NixOS/nixpkgs/pull/28635 is merged but there were problems with the build because of the sandboxing.
The new PR which needs to be merged ist https://github.com/NixOS/nixpkgs/pull/29469 now.

**Comment by ThomasMader** [comment]
https://github.com/NixOS/nixpkgs/pull/29469 is now merged into release-17.09 and master (build already available https://hydra.nixos.org/build/61651969) so this PR is ready to be merged.

**Pull request merged**
