### PR TITLE
GNOME: 41.2 → 41.3

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
Fixes: https://github.com/NixOS/nixpkgs/pull/156025
Fixes: https://github.com/NixOS/nixpkgs/pull/156026

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
@GrahamcOfBorg test gnome gnome-xorg

**Comment by jtojnar** [comment]
Most of the rebuild are actually just python packages via `mathplotlib` [depending on `fonttools`](https://github.com/matplotlib/matplotlib/blob/b2422b02f8ca12ad51344f262593597b79ea9f9b/doc/users/explain/fonts.rst#L53)

**Comment by sternenseemann** [comment]
@ofborg build afdko

**Comment by sternenseemann** [comment]
@ofborg build python3Packages.afdko

**Review by dasj19 — COMMENTED** [review]
As it is now this PR fails to build:
```
applying patch /nix/store/d9iqkfpahq8hci53n1hsr09hq0qwnq41-fix-paths.patch
patching file gnome-session/gnome-session.in
Hunk #1 FAILED at 3.
1 out of 1 hunk FAILED -- saving rejects to file gnome-session/gnome-session.in.rej
patching file gnome-session/main.c
error: builder for '/nix/store/xqrwrf8q36qr9jq30d4qysbw2l7l1534-gnome-session-41.3.drv' failed with exit code 1
```
I tested on x86_64 linux

**Comment by jtojnar** [comment]
Thanks, seems to work in VM now.

**Review by dasj19 — APPROVED** [review]
Yes, now it builds.

And the changes look good.

**Comment by SuperSandro2000** [comment]
Most python packages are missing import checks and they all have no maintainers. All packages need to have a maintainer. Going to add the gnome team to everything.

**Comment by jtojnar** [comment]
Yeah, sorry about that. I used some other Python package as a template and forgot to check. I guess I will add myself since the packages do not really have much to do with GNOME other than to build Cantarell fonts. Unless @sternenseemann thinks creating a fonttools team would make sense.

**Pull request merged**
