### PR TITLE
lib.licenses: refactor internal mkLicense to avoid future typo bugs

### PR DESCRIPTION
**Pull request by adisbladis**
## Description of changes

This is a follow-up to https://github.com/NixOS/nixpkgs/pull/325380 where @emilazy discovered that we have some typos in field names.

This refactoring wraps the implicit lib.licenses schema up in a factory function to ensure consistency.

While a more proper type checker like the one we use for meta checks would be better I didn't want to depend on that in more places. In fact, we might want to make meta type checks more strict on the license field.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by adisbladis** [comment]
Marking as draft until https://github.com/NixOS/nixpkgs/pull/325380 is merged.

**Comment by emilazy** [comment]
I should have thought of this :) The `//` stuff in that CUDA package made me assume that there was no real way to get reliable checking, but I guess even that could be covered by the `meta` type‐checking stuff?

**Comment by adisbladis** [comment]
> The // stuff in that CUDA package made me assume that there was no real way to get reliable checking, but I guess even that could be covered by the meta type‐checking stuff?

Indeed that would catch ad-hoc attrset additions too.

**Comment by SomeoneSerge** [comment]
> I should have thought of this :) The // stuff in that CUDA package made me assume that there was no real way to get reliable checking,

We definitely want to make this less ad hoc

**Comment by adisbladis** [comment]
If no one else is inclined I'll merge this shortly.

**Comment by Atemu** [comment]
As the author of the original code: Thanks, much better :)

**Pull request merged**
