### PR TITLE
treewide: remove all cargoSha256 usage

### PR DESCRIPTION
**Pull request by Aleksanaa**
### First treewide (easy)

Treewide command:

```bash
find . -type f -name "*.nix" -print0 | xargs -0 sed -i 's/cargoSha256 = "sha256-/cargoHash = "sha256-/g'
```

### Second treewide

Treewide bash script (which was executed in `pkgs`):

```bash
#!/usr/bin/env bash

process_line() {
    local filename=${1%:}
    if [[ $4 =~ \"(.*)\"\; ]]; then
      local sha256="${BASH_REMATCH[1]}"
    fi

    [[ -z $sha256 ]] && return 0

    local hash=$(nix hash to-sri --type sha256 $sha256)

    echo "Processing: $filename"
    echo "  $sha256 => $hash"

    sed -i "s|cargoSha256 = \"$sha256\"|cargoHash = \"$hash\"|" $filename
}

# split output by line
grep -r 'cargoSha256 = ' . | while IFS= read -r line; do
    # split them further by space
    read -r -a parts <<< "$line"
    process_line "${parts[@]}"
done
```

There are some exceptions, basically using a wrapped builder, or writing in `let`. I've manually fixed them. Would be better to check again.

### buildRustPackage changes

I'm not really sure about this part.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Aleksanaa** [comment]
Logically speaking it should not cause such rebuilds (or actually it will)?

**Comment by JohnRTitor** [comment]
Yeah, I am not sure if it's worth the rebuilding effort. Improvements like this can come atomically, like when updating that specific package.

**Comment by Aleksanaa** [comment]
Ah, I see. The hash here will not only be consumed by buildRustPackage, it also exists as an environment variable.

> Improvements like this can come atomically, like when updating that specific package.

In theory we should deprecate it and avoid further usages altogether. We have already done that for golang's vendorHash.

**Comment by h7x4** [comment]
> Yeah, I am not sure if it's worth the rebuilding effort. Improvements like this can come atomically, like when updating that specific package.

I don't know about this. It feels like it's better to do a treewide into staging and let hydra take the hit once, rather than keep spending review time on it for random PRs. It will probably also make a higher percentage of new PRs use `cargoHash`, seeing how people often use another package as reference.

**Comment by Aleksanaa** [comment]
Once we have all treewide changes done, we can let it throw a warning, and let `cargoSha256` a history. I'm currently considering completing other changes at the same time.

**Comment by Aleksanaa** [comment]
Oh the conflict is in staging, not master

**Review by JohnRTitor — APPROVED** [review]
LGTM, passes my eyeball test

**Comment by doronbehar** [comment]
Missed `rust-analyzer`, fix is at:

https://github.com/NixOS/nixpkgs/pull/326491

**Pull request merged**
