### PR TITLE
pythonPackages.fonttools: 4.14.0 → 4.18.2

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Motivation for this change

* <https://github.com/fonttools/fonttools/releases/tag/4.18.2>
* <https://github.com/fonttools/fonttools/releases/tag/4.18.1>
* <https://github.com/fonttools/fonttools/releases/tag/4.18.0>
* <https://github.com/fonttools/fonttools/releases/tag/4.17.1>
* <https://github.com/fonttools/fonttools/releases/tag/4.17.0>
* <https://github.com/fonttools/fonttools/releases/tag/4.16.1>
* <https://github.com/fonttools/fonttools/releases/tag/4.16.0>
* <https://github.com/fonttools/fonttools/releases/tag/4.15.0>

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
@GrahamcOfBorg build python3Packages.nototools

**Comment by sternenseemann** [comment]
@GrahamcOfBorg build python3Packages.nototools

**Comment by sternenseemann** [comment]
Is this a PR that should be made against `staging`? `nixpkgs-review` seems to indicate > 1000 changed attributes at least somehow.

**Comment by sternenseemann** [comment]
@GrahamcOfBorg build python3Packages.nototools

**Comment by jonringer** [comment]
python packages are pretty "cheap" in general. so <500 rebuilds is usually good

**Comment by sternenseemann** [comment]
Build failure is related to #106464. Will rebase and check again as soon as that is merged.

**Comment by sternenseemann** [comment]
@GrahamcOfBorg build python3Packages.nototools

**Comment by sternenseemann** [comment]
@GrahamcOfBorg build python3Packages.nototools

**Comment by SuperSandro2000** [comment]
@ofborg build pythonPackages.fonttools

**Comment by SuperSandro2000** [comment]
@ofborg build python3Packages.fonttools

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by sternenseemann** [comment]
Result of `nixpkgs-review pr 103818` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>26 packages marked as broken and skipped:</summary>
  <ul>
    <li>apacheKafka_0_10</li>
    <li>apacheKafka_0_11</li>
    <li>apacheKafka_0_9</li>
    <li>apacheKafka_1_0</li>
    <li>apacheKafka_1_1</li>
    <li>apacheKafka_2_0</li>
    <li>apacheKafka_2_1</li>
    <li>apacheKafka_2_2</li>
    <li>apacheKafka_2_3</li>
    <li>hadoop</li>
    <li>hadoop_2_7</li>
    <li>hadoop_2_8</li>
    <li>hadoop_2_9</li>
    <li>hol</li>
    <li>linuxPackages_hardkernel_4_14.virtualbox</li>
    <li>linuxPackages_hardkernel_latest.virtualbox</li>
    <li>octave-jit</li>
    <li>openmodelica</li>
    <li>pig</li>
    <li>python37Packages.skein</li>
    <li>python37Packages.zake</li>
    <li>python38Packages.skein</li>
    <li>python38Packages.zake</li>
    <li>python39Packages.skein</li>
    <li>python39Packages.zake</li>
    <li>spark</li>
  </ul>
</details>
<details>
  <summary>22 packages failed to build:</summary>
  <ul>
    <li>apktool</li>
    <li>avian</li>
    <li>axoloti</li>
    <li>foundationdb60</li>
    <li>hadoop_3_0</li>
    <li>hadoop_3_1</li>
    <li>hdf_java</li>
    <li>hdfview</li>
    <li>linuxPackages_5_10.virtualbox (linuxPackages_latest.virtualbox)</li>
    <li>linuxPackages_latest-libre.virtualbox</li>
    <li>linuxPackages_latest_xen_dom0.virtualbox</li>
    <li>linuxPackages_zen.virtualbox</li>
    <li>patroni</li>
    <li>processing</li>
    <li>python37Packages.foundationdb60</li>
    <li>python37Packages.slither-analyzer</li>
    <li>python38Packages.foundationdb60</li>
    <li>slither-analyzer (python38Packages.slither-analyzer)</li>
    <li>python39Packages.foundationdb60</li>
    <li>python39Packages.slither-analyzer</li>
    <li>sourcetrail</li>
    <li>tsm-client-withGui</li>
  </ul>
</details>
<details>
  <summary>270 packages built:</summary>
  <ul>
    <li>DisnixWebService</li>
    <li>R</li>
    <li>abcl</li>
    <li>adapta-gtk-theme</li>
    <li>adoptopenjdk-icedtea-web</li>
    <li>alloy (alloy5)</li>
    <li>alloy4</li>
    <li>antlr</li>
    <li>antlr3 (antlr3_5)</li>
    <li>antlr3_4</li>
    <li>antlr4 (antlr4_8)</li>
    <li>apache-jena</li>
    <li>apache-jena-fuseki</li>
    <li>apacheKafka (apacheKafka_2_5)</li>
    <li>apacheKafka_2_4</li>
    <li>ape</li>
    <li>apeClex</li>
    <li>areca</li>
    <li>asciidoc-full</li>
    <li>asciidoc-full-with-plugins</li>
    <li>azureus</li>
    <li>belle-sip</li>
    <li>btrbk</li>
    <li>buck</li>
    <li>cassandra (cassandra_3_11)</li>
    <li>cassandra_2_1</li>
    <li>cassandra_2_2</li>
    <li>cassandra_3_0</li>
    <li>ccache</li>
    <li>ccacheStdenv</li>
    <li>ccacheWrapper</li>
    <li>charles (charles4)</li>
    <li>charles3</li>
    <li>chrome-gnome-shell</li>
    <li>chromium</li>
    <li>clevis</li>
    <li>collectd</li>
    <li>collectd-data</li>
    <li>cvc4</li>
    <li>dbus_java</li>
    <li>disorderfs</li>
    <li>dotty</li>
    <li>drip</li>
    <li>dwarf-fortress-packages.dwarf-fortress-full</li>
    <li>dwarf-fortress-packages.legends-browser</li>
    <li>eclipses.eclipse-scala-sdk</li>
    <li>elasticmq</li>
    <li>elasticmq-server-bin</li>
    <li>emojione</li>
    <li>erlang_javac</li>
    <li>erlang_odbc_javac</li>
    <li>exhibitor</li>
    <li>fop</li>
    <li>foundationdb (foundationdb61)</li>
    <li>foundationdb51</li>
    <li>foundationdb52</li>
    <li>freemind</li>
    <li>freenet</li>
    <li>freetts</li>
    <li>frostwire</li>
    <li>galen</li>
    <li>gama</li>
    <li>gcs</li>
    <li>gephi</li>
    <li>global-platform-pro</li>
    <li>gnome3.gnome-session (gnome3.gnome_session)</li>
    <li>gnome3.gnome-shell (gnome3.gnome_shell)</li>
    <li>gnome3.gnome-terminal (gnome3.gnome_terminal)</li>
    <li>gnome3.gnome-tweaks (gnome3.gnome-tweak-tool)</li>
    <li>gnome3.pomodoro</li>
    <li>gnomeExtensions.easyScreenCast</li>
    <li>gnomeExtensions.gsconnect</li>
    <li>gnomeExtensions.night-theme-switcher</li>
    <li>google-chrome</li>
    <li>google-chrome-beta</li>
    <li>google-chrome-dev</li>
    <li>gradle (gradle_6)</li>
    <li>gradle_4 (gradle_4_10)</li>
    <li>gradle_5</li>
    <li>gscan2pdf</li>
    <li>haskellPackages.hevm</li>
    <li>haskellPackages.hzk</li>
    <li>haskellPackages.linearEqSolver</li>
    <li>haskellPackages.sbv</li>
    <li>herbstluftwm</li>
    <li>i2p</li>
    <li>ili2c</li>
    <li>impressive</li>
    <li>jadx</li>
    <li>jasmin</li>
    <li>java-service-wrapper</li>
    <li>javaCup</li>
    <li>javaPackages.jogl_2_3_2</li>
    <li>javaPackages.junit_4_12</li>
    <li>javaPackages.mavenHello_1_0</li>
    <li>javaPackages.mavenHello_1_1</li>
    <li>jd-gui</li>
    <li>jdepend</li>
    <li>jdk8 (openjdk8)</li>
    <li>jing (jing-trang)</li>
    <li>jitsi</li>
    <li>jmol</li>
    <li>jpexs</li>
    <li>jre8</li>
    <li>knightos-genkfs</li>
    <li>knightos-kimg</li>
    <li>knightos-mkrom</li>
    <li>knightos-mktiupgrade</li>
    <li>liberation-sans-narrow</li>
    <li>liberation_ttf (liberation_ttf_v2)</li>
    <li>liblinphone</li>
    <li>libmatthew_java</li>
    <li>libreoffice (libreoffice-still)</li>
    <li>libreoffice-fresh</li>
    <li>libreoffice-fresh-unwrapped</li>
    <li>libreoffice-qt</li>
    <li>libreoffice-unwrapped (libreoffice-still-unwrapped)</li>
    <li>lime</li>
    <li>linphone</li>
    <li>linuxPackages-libre.virtualbox</li>
    <li>linuxPackages.virtualbox (linuxPackages_5_4.virtualbox)</li>
    <li>linuxPackages_4_14.virtualbox</li>
    <li>linuxPackages_4_19.virtualbox</li>
    <li>linuxPackages_4_4.virtualbox</li>
    <li>linuxPackages_4_9.virtualbox</li>
    <li>linuxPackages_5_9.virtualbox</li>
    <li>linuxPackages_hardened.virtualbox</li>
    <li>linuxPackages_latest_hardened.virtualbox</li>
    <li>linuxPackages_latest_xen_dom0_hardened.virtualbox</li>
    <li>linuxPackages_testing_bcachefs.virtualbox</li>
    <li>linuxPackages_xen_dom0.virtualbox</li>
    <li>linuxPackages_xen_dom0_hardened.virtualbox</li>
    <li>luksmeta</li>
    <li>ma1sd</li>
    <li>maven (maven3)</li>
    <li>mercury</li>
    <li>minc_widgets</li>
    <li>monosat</li>
    <li>mucommander</li>
    <li>multimc</li>
    <li>mxisd</li>
    <li>mysql-workbench</li>
    <li>nco</li>
    <li>neo4j</li>
    <li>notmuch-bower</li>
    <li>noto-fonts-emoji</li>
    <li>octave</li>
    <li>octaveFull</li>
    <li>odpdown</li>
    <li>openems</li>
    <li>opentsdb</li>
    <li>pakcs</li>
    <li>pantheon.elementary-session-settings</li>
    <li>pdftk</li>
    <li>perl530Packages.InlineJava</li>
    <li>perl530Packages.NetZooKeeper</li>
    <li>perl532Packages.InlineJava</li>
    <li>perl532Packages.NetZooKeeper</li>
    <li>pmd</li>
    <li>polymake</li>
    <li>projectlibre</li>
    <li>python37Packages.afdko</li>
    <li>python37Packages.booleanoperations</li>
    <li>python37Packages.cnvkit</li>
    <li>python37Packages.defcon</li>
    <li>python37Packages.fontmath</li>
    <li>python37Packages.fontparts</li>
    <li>python37Packages.fontpens</li>
    <li>python37Packages.fonttools</li>
    <li>python37Packages.foundationdb51</li>
    <li>python37Packages.foundationdb52</li>
    <li>python37Packages.foundationdb61</li>
    <li>python37Packages.kazoo</li>
    <li>python37Packages.monosat</li>
    <li>python37Packages.mutatormath</li>
    <li>python37Packages.nototools</li>
    <li>python37Packages.psautohint</li>
    <li>python37Packages.python-csxcad</li>
    <li>python37Packages.python-openems</li>
    <li>python37Packages.rpy2</li>
    <li>python37Packages.ufoprocessor</li>
    <li>python38Packages.afdko</li>
    <li>python38Packages.booleanoperations</li>
    <li>python38Packages.cnvkit</li>
    <li>python38Packages.defcon</li>
    <li>python38Packages.fontmath</li>
    <li>python38Packages.fontparts</li>
    <li>python38Packages.fontpens</li>
    <li>python38Packages.fonttools</li>
    <li>python38Packages.foundationdb51</li>
    <li>python38Packages.foundationdb52</li>
    <li>python38Packages.foundationdb61</li>
    <li>python38Packages.kazoo</li>
    <li>python38Packages.monosat</li>
    <li>python38Packages.mutatormath</li>
    <li>python38Packages.nototools</li>
    <li>python38Packages.psautohint</li>
    <li>python38Packages.python-csxcad</li>
    <li>python38Packages.python-openems</li>
    <li>python38Packages.rpy2</li>
    <li>python38Packages.ufoprocessor</li>
    <li>python39Packages.afdko</li>
    <li>python39Packages.booleanoperations</li>
    <li>python39Packages.defcon</li>
    <li>python39Packages.fontmath</li>
    <li>python39Packages.fontparts</li>
    <li>python39Packages.fontpens</li>
    <li>python39Packages.fonttools</li>
    <li>python39Packages.foundationdb51</li>
    <li>python39Packages.foundationdb52</li>
    <li>python39Packages.foundationdb61</li>
    <li>python39Packages.kazoo</li>
    <li>python39Packages.monosat</li>
    <li>python39Packages.mutatormath</li>
    <li>python39Packages.nototools</li>
    <li>python39Packages.psautohint</li>
    <li>python39Packages.python-csxcad</li>
    <li>python39Packages.python-openems</li>
    <li>python39Packages.ufoprocessor</li>
    <li>rWrapper</li>
    <li>rabbitmq-java-client</li>
    <li>rep</li>
    <li>rhino</li>
    <li>rictydiminished-with-firacode</li>
    <li>ripcord</li>
    <li>rstudio</li>
    <li>rstudioWrapper</li>
    <li>scala (scala_2_13)</li>
    <li>scala_2_10</li>
    <li>scala_2_11</li>
    <li>scala_2_12</li>
    <li>scalafix</li>
    <li>scfbuild</li>
    <li>shattered-pixel-dungeon</li>
    <li>signal-cli</li>
    <li>soapui</li>
    <li>solc</li>
    <li>sqlitebrowser</li>
    <li>srcml</li>
    <li>sweethome3d.application</li>
    <li>sweethome3d.furniture-editor</li>
    <li>sweethome3d.textures-editor</li>
    <li>swiProlog</li>
    <li>swiPrologWithGui</li>
    <li>swt_jdk8</li>
    <li>tang</li>
    <li>tlaplus</li>
    <li>twemoji-color-font</li>
    <li>twitter-color-emoji</li>
    <li>udiskie</li>
    <li>ums</li>
    <li>ungoogled-chromium</li>
    <li>unoconv</li>
    <li>virtualbox</li>
    <li>virtualboxHardened</li>
    <li>virtualboxHeadless</li>
    <li>virtualboxWithExtpack</li>
    <li>visidata</li>
    <li>vmware-horizon-client</li>
    <li>vuze</li>
    <li>whirlpool-gui</li>
    <li>xits-math</li>
    <li>xmage</li>
    <li>xmloscopy</li>
    <li>xtreemfs</li>
    <li>zap</li>
    <li>zk-shell</li>
    <li>zkfuse</li>
    <li>zookeeper</li>
    <li>zookeeper_mt</li>
  </ul>
</details>

**Comment by sternenseemann** [comment]
Can reproduce all build failures on master as well, seem unrelated.

<details>
<summary>
Tested
</summary>

* apktools
* patroni (#107425)
* avian
* axoloti
* foundationdb60
* hadoop_3_0, hadoop_3_1
* hdf_java
* hdfview
* python38Packages.foundationdb60
* python37Packages.foundationdb60
* processing fails because jdk won't build without the src in /nix/store
* python37Packages.slither-analyzer
* python38Packages.slither-analyzer
* python39Packages.foundationdb60
* python39Packages.slither-analyzer
* sourcetrail
* tsm-client-withGui
* linuxPackages_5_10.virtualbox
* linuxPackages_latest-libre.virtualbox
* linuxPackages_latest_xen_dom0.virtualbox
* linuxPackages_zen.virtualbox
</details>

**Pull request merged**
