### PR TITLE
git-team: 1.7.0 -> 1.8.0

### PR DESCRIPTION
**Pull request by lockejan**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lockejan** [comment]
Okay, my issue has been using nix 2.8.1 and having sandbox enabled, as been pointed out by winterqt.
After upgrading nix to 2.11.0 I got a bit further but run into a different error now.

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/nf33wnzcpf3jll4jpd3xyghi4dhd1isa-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
@nix { "action": "setPhase", "phase": "buildPhase" }
building
go: downloading github.com/urfave/cli/v2 v2.19.2
go: downloading github.com/fatih/color v1.13.0
go: downloading github.com/stretchr/testify v1.7.0
go: downloading github.com/mattn/go-isatty v0.0.16
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading github.com/stretchr/objx v0.3.0
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading golang.org/x/sys v0.0.0-20221013171732-95e765b1cc43
go: downloading github.com/xrash/smetrics v0.0.0-20201216005158-039620a65673
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.2
go: downloading github.com/russross/blackfriday/v2 v2.1.0
github.com/hekmekk/git-team/src/shared/completion tested by
        github.com/hekmekk/git-team/src/shared/completion.test imports
        github.com/hekmekk/git-team/mocks/shared/gitconfig/interface: no required module provides package github.com/hekmekk/git-team/mocks/shared/gitconfig/interface; to add it:
        go get github.com/hekmekk/git-team/mocks/shared/gitconfig/interface

```

Testing and building without nix works fine🤔

**Comment by lockejan** [comment]
> Did you update `vendorSha256` locally so that it's perturbed from what it currently is? Since the vendor derivation used by `buildGoModule` internally is a fixed-output derivation, it won't run again unless that's changed.

Thanks for the input. No, I didn't. How can I update it again? I tried lib.fakeSha256 but that didn't make any difference for the output.

**Comment by tjni** [comment]
I was wrong, that's not the reason for the failure. The reason seems to be because https://github.com/hekmekk/git-team/commit/4fe51abd6b27b2547806b741406149781c009fc4 started using https://github.com/vektra/mockery to create mocks on the fly.

**Comment by lockejan** [comment]
> I was wrong, that's not the reason for the failure. The reason seems to be because https://github.com/hekmekk/git-team/commit/4fe51abd6b27b2547806b741406149781c009fc4 started using https://github.com/vektra/mockery to create mocks on the fly.

Hm, any idea why and how we could work around that?

**Comment by tjni** [comment]
I put up a PR to resolve this in https://github.com/NixOS/nixpkgs/pull/201972, with you as co-author. I'm sorry I don't know how to (or if I have permissions to) add a commit to this PR.

**Comment by lockejan** [comment]
Closed in favor of #201972

**Pull request closed without merging**
