### PR TITLE
vimPlugins.smart-open-nvim: init at 2024-06-12

### PR DESCRIPTION
**Pull request by DylanBulfin**
## Description of changes

Add smart-move.nvim plugin to vimPlugins

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by teto — DISMISSED** [review]
this doesn't add the plugin and breaks the formatting.

**Comment by DylanBulfin** [comment]
> this doesn't add the plugin and breaks the formatting.

My bad, should hopefully be fixed now.

**Comment by PerchunPak** [comment]
This plugin relies on `telescope-nvim` and `sqlite-lua` ([link](https://github.com/danielfalk/smart-open.nvim?tab=readme-ov-file#requirements)). Add them please as dependencies, similar to [here](https://github.com/NixOS/nixpkgs/blob/bd4f00ac7fa6b641777b5a7fb08911c456b4ed01/pkgs/applications/editors/vim/plugins/overrides.nix#L197-L199)

**Comment by DylanBulfin** [comment]
> This plugin relies on `telescope-nvim` and `sqlite-lua` ([link](https://github.com/danielfalk/smart-open.nvim?tab=readme-ov-file#requirements)). Add them please as dependencies, similar to [here](https://github.com/NixOS/nixpkgs/blob/bd4f00ac7fa6b641777b5a7fb08911c456b4ed01/pkgs/applications/editors/vim/plugins/overrides.nix#L197-L199)

Thank you for the help, for some reason I thought the override fields were for build dependencies.

**Review by PerchunPak — APPROVED** [review]
LGTM! Thanks!

[CC](https://github.com/NixOS/nixpkgs/pull/333817#issuecomment-2294798601) @GaetanLepage

**Review by GaetanLepage — APPROVED** [review]
LGTM

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 335477` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>vimPlugins.smart-open-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Pull request merged**
