### PR TITLE
blackfire: init at 1.44.0

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
Adds [Blackfire](https://blackfire.io), a proprietary profiler for PHP and other languages.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
I successfully created a profile on my NixOS server.

Rendered docs:

image

**Comment by etu** [comment]
cc @NixOS/php 

One thought without looking into too deeply: Couldn't the extension/probe bit be part of the file with all other extensions? It has support for extensions that depends on other extensions.

**Comment by jtojnar** [comment]
In my experience, separate files are better for automated updates (that reminds me I still need to write an `updateScript`) and as fair as I can tell the dependencies to other extensions are done through the PHP attribute, which I am passing to `callPackage` (would be nicer if the extensions were a separate scope with its `callPackage` but top-level `callPackage` seems to work now). Also I do not think blackfire depends on anything, or anything on blackfire.

Though there are [some incompatible extensions](https://blackfire.io/docs/up-and-running/installation#install-the-php-probe), maybe we could assert that they are not enabled at the same time?

**Comment by etu** [comment]
> In my experience, separate files are better for automated updates

Hmm, then we maybe should make a directory for php extension derivations and start splitting out things from "the big file" of all packages and extensions that we have today.

**Pull request merged**
