### PR TITLE
Fix praw

### PR DESCRIPTION
**Pull request by Mic92**
###### Motivation for this change

praw is a dependency of i3pystatus.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
Note that `name` can be removed since we have https://github.com/NixOS/nixpkgs/pull/31173

**Comment by Mic92** [comment]
oh, finally the day has come.

**Comment by Mic92** [comment]
nix-review looks good.

**Comment by Mic92** [comment]
@FRidh are you planning on removing `name` automatically in python-packages?

**Comment by FRidh** [comment]
@orivej was looking at automatically migrating expressions from `python-packages.nix` to `python-modules`. I suppose it could be part of that or come after it. In any case, it would be nice to do, yes.

I would prefer though that we try to inherit version from `src` automatically. WIth https://github.com/NixOS/nixpkgs/pull/31271 in we can enhance `fetchPypi` to just pass it thru. 

Example:

```
buildPythonPackage = rec {
  pname = "foo";
  src = fetchPypi {
    inherit pname; version = "1.2.3";
    sha256 = "adfsdffd";
  };
}
```
This would make overriding for changing version easier:
```
foo.overridePythonAttrs ({
  src = oldAttrs.src.override {
    version = "2.1.2";
    sha256 = "jdfkdsfksdf";
  };
})
```

**Comment by orivej** [comment]
> then `pname` can be inherited as well?

Yes, but wouldn't it be better to go in a different direction? Definition:
```nix
foo = buildPythonPackage rec {
  pname = "foo";
  version = "1.2.3";
  src.sha256 = "adfsdffd";
}
```

Overriding:
```nix
foo.overridePythonAttrs ({
  version = "2.1.2";
  src.sha256 = "jdfkdsfksdf";
})
```

Implementation:
```nix
mkPythonDerivation = attrs@{
  name ? "${attrs.pname}-${attrs.version}", # since #31173
  ...
}: let
  src = if !builtins.isAttrs src || lib.isDerivation src then src else fetchPypi src // {
    pname = src.pname or attrs.pname;
    version = src.version or attrs.version;
  };
in python.stdenv.mkDerivation {}
```

> @orivej was looking at automatically migrating expressions from python-packages.nix to python-modules. I suppose it could be part of that

Yes. I didn't have time on the weekend as I hoped, will try this week.

**Comment by FRidh** [comment]
What would be better about it? In my opinion, the version is an attribute of the source, so I prefer to set it there. Furthermore, I don't think we should put any "dependence" on `fetchPypi` in `buildPythonPackage`. Yes, we mostly use `fetchPypi`, but saying we by default fetch from PyPI goes a bit too far in my opinion.

**Comment by orivej** [comment]
OK, I agree that my proposal is not ideal and may be scrapped. I just want to note that the name (`pname`) and version are attributes of the final package (because they are visible to users in `nix-env -qa` and `nox`) *and* they are parameters of the source (when the source server is hosting multiple packages with a predictable scheme of mapping names and versions to URLs, such as GitHub, SourceForge and PyPI; otherwise the version is the only parameter). Now, @Mic92 is asking if we may inherit from `src` not only `version` but also `pname`: this will remove the need to provide `pname` in two places (`attrs` and `src`). I've proposed another way to achieve the same that is even shorter.

We may conceptualize that the name really is an attribute of the package and version really is an attribute of the source, and this is why they are defined in different places (`attrs.pname` and `src.version`). I'd prefer a more flat approach where we don't care about this distinction and don't provide the same attributes in two sets (inheriting from one into another), but I am not sure how to express this best in Nix. (`buildPythonPackage` could have been a reasonable implementation of this flat approach for the most of Python packages if we decided that `buildPythonPackage` by default implies `fetchPypi`, but I recognize that it is not ideal to entirely omit `fetchPypi` from the definition of the package.)

**Pull request merged**
