### PR TITLE
ubootOrangePiZero2: init

### PR DESCRIPTION
**Pull request by novmar**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](./CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by novmar** [comment]
Hello, 
I am so sorry, but  this is redo of
https://github.com/NixOS/nixpkgs/pull/124440
i was unable to fix it that PR. git is sometimes mean to me :-)
Marcel

**Review by samueldr — CHANGES_REQUESTED** [review]
`armTrustedFirmwareAllwinnerH616` is missing from `all-packages.nix`.

**Comment by novmar** [comment]
Added armTrustedFirmwareAllwinnerH616 to  all-packages.nix.

**Comment by novmar** [comment]
Hello, is there some problem with that PR ?

**Comment by samueldr** [comment]
Hi, sorry it took so much time to circle back up to this PR.

Thank you for the contribution!

**Pull request merged**
