### PR TITLE
vimPlugins.rainbow-delimiters-nvim: init at 2023-08-25

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Add vim plugin [rainbow-delimiters.nvim](https://gitlab.com/HiPhish/rainbow-delimiters.nvim).

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by GaetanLepage** [comment]
<li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.rest-nvim</li>
    <li>vimPlugins.scope-nvim</li>
    <li>vimPlugins.srcery-vim</li>
    <li>vimPlugins.ssr</li>
    <li>vimPlugins.ssr-nvim</li>
    <li>vimPlugins.switch-vim</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-media-files-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-undo-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.telescope-zoxide</li>
    <li>vimPlugins.treesj</li>
    <li>vimPlugins.unison</li>
    <li>vimPlugins.vifm-vim</li>
    <li>vimPlugins.vim-android</li>
    <li>vimPlugins.vim-codefmt</li>
    <li>vimPlugins.vim-figlet</li>
    <li>vimPlugins.vim-go</li>
    <li>vimPlugins.vim-lastplace</li>
    <li>vimPlugins.vim-markbar</li>
    <li>vimPlugins.vim-pluto</li>
    <li>vimPlugins.vim-snippets</li>
    <li>vimPlugins.vim-tmux-navigator</li>
    <li>vimPlugins.vim-tpipeline</li>
    <li>vimPlugins.yats-vim</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
`vimPlugins.sg-nvim` fails to build because of a duplicate tag in its documentation.
I made a PR upstream: https://github.com/sourcegraph/sg.nvim/pull/100

**Comment by figsoda** [comment]
I went ahead and merged #251011, this should be safe to rebase now.

For sg.nvim, you have a few options
- revert the update
- apply the patch
- wait for the PR to be merged

**Comment by GaetanLepage** [comment]
@figsoda The duplicate tag was fixed upstream !
I rebased and re-run the update script.
Everything should be fine now. I am re-reunning `nixpkgs-review`.

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 251317` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>lua54Packages.sqlite</li>
  </ul>
</details>
<details>
  <summary>106 packages built:</summary>
  <ul>
    <li>lua51Packages.sqlite</li>
    <li>lua52Packages.sqlite</li>
    <li>lua53Packages.sqlite</li>
    <li>luajitPackages.sqlite</li>
    <li>vimPlugins.ChatGPT-nvim</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.SpaceCamp</li>
    <li>vimPlugins.SpaceVim</li>
    <li>vimPlugins.alpha-nvim</li>
    <li>vimPlugins.autosave-nvim</li>
    <li>vimPlugins.barbar-nvim</li>
    <li>vimPlugins.barbecue-nvim</li>
    <li>vimPlugins.catppuccin-nvim</li>
    <li>vimPlugins.clangd_extensions-nvim</li>
    <li>vimPlugins.cmp-clippy</li>
    <li>vimPlugins.cmp-dap</li>
    <li>vimPlugins.cmp-fuzzy-buffer</li>
    <li>vimPlugins.cmp-fuzzy-path</li>
    <li>vimPlugins.cmp-npm</li>
    <li>vimPlugins.cmp-pandoc-nvim</li>
    <li>vimPlugins.codeium-vim</li>
    <li>vimPlugins.compiler-explorer-nvim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.copilot-lua</li>
    <li>vimPlugins.crates-nvim</li>
    <li>vimPlugins.dashboard-nvim</li>
    <li>vimPlugins.denops-vim</li>
    <li>vimPlugins.diffview-nvim</li>
    <li>vimPlugins.efmls-configs-nvim</li>
    <li>vimPlugins.fuzzy-nvim</li>
    <li>vimPlugins.gitlinker-nvim</li>
    <li>vimPlugins.gitsigns-nvim</li>
    <li>vimPlugins.hardtime-nvim</li>
    <li>vimPlugins.harpoon</li>
    <li>vimPlugins.haskell-tools-nvim</li>
    <li>vimPlugins.image-nvim</li>
    <li>vimPlugins.lazy-lsp-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.leap-ast-nvim</li>
    <li>vimPlugins.lir-nvim</li>
    <li>vimPlugins.lsp-zero-nvim</li>
    <li>vimPlugins.lspsaga-nvim</li>
    <li>vimPlugins.mason-lspconfig-nvim</li>
    <li>vimPlugins.mini-nvim</li>
    <li>vimPlugins.modicator-nvim</li>
    <li>vimPlugins.neo-tree-nvim</li>
    <li>vimPlugins.neodev-nvim</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neorg</li>
    <li>vimPlugins.neotest-python</li>
    <li>vimPlugins.neotest-rspec</li>
    <li>vimPlugins.null-ls-nvim</li>
    <li>vimPlugins.numb-nvim</li>
    <li>vimPlugins.nvchad</li>
    <li>vimPlugins.nvim-coverage</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-dap-python</li>
    <li>vimPlugins.nvim-lint</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-scrollview</li>
    <li>vimPlugins.nvim-spectre</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-parsers.bash</li>
    <li>vimPlugins.nvim-treesitter-parsers.dart</li>
    <li>vimPlugins.nvim-treesitter-parsers.heex</li>
    <li>vimPlugins.nvim-treesitter-parsers.java</li>
    <li>vimPlugins.nvim-treesitter-parsers.javascript</li>
    <li>vimPlugins.nvim-treesitter-parsers.re2c</li>
    <li>vimPlugins.nvim-treesitter-parsers.rust</li>
    <li>vimPlugins.nvim-treesitter-parsers.wing</li>
    <li>vimPlugins.nvim-treesitter-textobjects</li>
    <li>vimPlugins.nvim_context_vt</li>
    <li>vimPlugins.octo-nvim</li>
    <li>vimPlugins.oil-nvim</li>
    <li>vimPlugins.onedark-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.overseer-nvim</li>
    <li>vimPlugins.packer-nvim</li>
    <li>vimPlugins.playground</li>
    <li>vimPlugins.plenary-nvim</li>
    <li>vimPlugins.rainbow-delimiters-nvim</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.rest-nvim</li>
    <li>vimPlugins.sg-nvim</li>
    <li>vimPlugins.srcery-vim</li>
    <li>vimPlugins.ssr</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-media-files-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-undo-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.telescope-zoxide</li>
    <li>vimPlugins.treesj</li>
    <li>vimPlugins.unison</li>
    <li>vimPlugins.vifm-vim</li>
    <li>vimPlugins.vim-android</li>
    <li>vimPlugins.vim-lastplace</li>
    <li>vimPlugins.vim-markbar</li>
    <li>vimPlugins.vim-pluto</li>
    <li>vimPlugins.vim-snippets</li>
    <li>vimPlugins.yats-vim</li>
  </ul>
</details>

**Review by figsoda — APPROVED** [review]

**Pull request merged**
