### PR TITLE
ranger: syntax highlight previews by default

### PR DESCRIPTION
**Pull request by alyssais**
This also fixes out-of-the-box previews. I'm guessing this became commented out by default at some point.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
Looks nice (no nix higlighting unfortunately).  Also add ~2.8M to closure size. But I think it should be fine.

**Comment by rnhmjoj** [comment]
You could use pygments instead, it has nix support but it will probably increase the closure even more:
```patch
--- a/pkgs/applications/misc/ranger/default.nix
+++ b/pkgs/applications/misc/ranger/default.nix
@@ -24,6 +24,9 @@ python3Packages.buildPythonApplication rec {
   '';
 
   preConfigure = ''
+    sed -i -e 's|# pygmentize|${python3Packages.pygments}/bin/pygmentize|' \
+      ranger/data/scope.sh
+
     substituteInPlace ranger/data/scope.sh \
       --replace "/bin/echo" "echo"

 ```

**Comment by emmanuelrosa** [comment]
It's working nicely on NixOS :+1:

**Comment by alyssais** [comment]
Annoying that pygments and highlight have different command line arguments, so you can't just swap them with overrides…

I think that leaving it as highlight would be better as the default, since that's what upstream does. Then all we're doing is fixing a path rather than changing upstream's functionality.

**Comment by xeji** [comment]
> I think that leaving it as highlight would be better as the default, since that's what upstream does.

Agree. Users can easily switch to pygmentize in their `~/.config/ranger/scope.sh`

**Pull request merged**
