### PR TITLE
mfcj5320dw{lpr,cupswrapper}: init at 3.0.1-1

### PR DESCRIPTION
**Pull request by SuperSamus**
###### Things done

I copy-pasted another Brother printer derivation and changed things accordingly.
What I didn't do is testing, because I don't know how to do it, I searched on the internet and the only thing I could find is how to test packages that can be built normally.
If you tell me how I can test it, I will.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSamus** [comment]
I'm having trouble to get it to work.
I can connect to the printer no problem, but when I'm trying to print CUPS complains that "Filter failed". Looking at the logs it seems that the culprit is:
`nixos cupsd[201371]: PID 202370 (/nix/store/l5cshmkxj1f176df55lhw0wq34w385hl-cups-progs/lib/cups/filter/brother_lpdwrapper_mfcj5320dw) stopped with status 1.`
I have no idea what to do. What should I try to do? I tried taking copying the layout from many other lpd derivations, but this is the best I can do.

**Comment by SuperSamus** [comment]
Nothing, can't make it work even with USB.
More logs (with USB): [logs.txt](https://github.com/NixOS/nixpkgs/files/7360537/logs.txt)

**Comment by SuperSamus** [comment]
Very soon into the script, there's the line `cat > $INPUT_TEMP`, I piped something random to make it continue (didn't try that before).
I'm getting a weird error: `/opt/brother/Printers/mfcj5320dw/inf/ImagingArea :cannot open file !!`. But that's weird, the path is supposed to be substituted. Here is the script after the substitution by nix:
```
PRINTER="mfcj5320dw"
PRINTER_TMP=$(echo $PRINTER | sed -e 's/ //g' -e 's/-//g')



BR_CFG_PATH=/nix/store/b7300ymi4wzask5wnfprcnhq4rcp1d15-mfcj5320dwlpr-3.0.1-1/opt/brother/Printers/${PRINTER}
BR_LPD_PATH=/nix/store/b7300ymi4wzask5wnfprcnhq4rcp1d15-mfcj5320dwlpr-3.0.1-1/opt/brother/Printers/${PRINTER}


RCFILE="$BRPRINTERRCFILE"
PAPER_INF=$BR_CFG_PATH/inf/paperinfij2
#
#
#
IMAGINGAREA_FILE=$BR_CFG_PATH/inf/ImagingArea

PSCONV=$BR_LPD_PATH/lpd/psconvertij2
BRCONV=$BR_LPD_PATH/lpd/br${PRINTER}filter
if [ "$BRPRINTERRCFILE" = '' ];then
	RCFILE=`eval echo $BR_CFG_PATH/inf/brPRINTERrc | eval sed 's/PRINTER/"$PRINTER_TMP"/'`
	if [ -e /var/tmp/lprng_${PRINTER_TMP}_rcname ];then
	read -r name < /var/tmp/lprng_${PRINTER_TMP}_rcname
	fi

	if [ -z $name ];then
	:
	else
	RCFILE=$name
	fi
fi


INPUT_TEMP=`mktemp /tmp/br_input.XXXXXX`
cat > $INPUT_TEMP

rm -f /var/tmp/lprng_${PRINTER}_rcname

FILE_TYPE=`file $INPUT_TEMP | sed -e 's/^.*:[ ]*//' -e 's/[ ].*//'`

#if [ "$FILE_TYPE" = "PostScript" -o "$FILE_TYPE" = "PDF" ] ; then
	PSCONV_OP="$PAPER_INF $RCFILE $IMAGINGAREA_FILE"
	BRCONV_OP="-pi $PAPER_INF -rc $RCFILE"
#fi

trap '' 2
case "$FILE_TYPE" in      
	"PostScript")
		eval cat $INPUT_TEMP | $PSCONV $PSCONV_OP | $BRCONV $BRCONV_OP
		RET=$?
		;;
	"PDF")
		PS_TEMP=`mktemp /tmp/br_ps.XXXXXX`
		pdf2ps $INPUT_TEMP $PS_TEMP
		eval cat $PS_TEMP | $PSCONV $PSCONV_OP | $BRCONV $BRCONV_OP
		RET=$?
		rm -f $PS_TEMP
		;;
	* )
		A2PS_OP="--output=- -q -1 --no-header --borders no"
		eval cat $INPUT_TEMP | a2ps $A2PS_OP | $PSCONV $PSCONV_OP | $BRCONV $BRCONV_OP
		RET=$?
		;;
esac
trap 2

rm -f $INPUT_TEMP

exit $RET
```

**Comment by SuperSamus** [comment]
Closing because I don't intend to work on this anymore.
Still, I'd be happy to test if anyone wants to continue.

**Comment by steveeJ** [comment]
@veprbl 

> The backup option is to wrap the driver with proot to bind /opt to the path in the nix store.

sorry to revive this old thread, but i'm in a similar situation. is there an example of using proot in nixpkgs? i imagine it would be similar to `wrapProgram`.

**Comment by veprbl** [comment]
@steveeJ Maybe, see `libredirect`, it's nixpkgs-only, but should have examples in nixpkgs.

**Pull request closed without merging**
