### PR TITLE
rsyslog: include libmaxminddb

### PR DESCRIPTION
**Pull request by basilgood**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by aanderse** [comment]
@basilgood you should add `libmaxminddb` to `buildInputs`.

**Comment by aanderse** [comment]
@basilgood I was hoping someone who has done some work on this package before would review but that doesn't seem to be the case. I've looked into the docs in a bit more detail and gone through the package in nixpkgs some more so I guess we're good to go, right after you update the declaration of `rsyslog-light` in `all-packages.nix`.

Thanks!

**Comment by megheaiulian** [comment]
@aanderse Please have a look again.

**Comment by aanderse** [comment]
Thanks @megheaiulian and @basilgood. I don't use any `libmaxminddb` stuff with `rsyslog` so I'm not really in a position to test this. It is a pretty simple change and after reading through the documentation I'm inclined to think I can just click **merge**, but I'd like to at least hear one person say they've tested this and it works as expected. Have either of you tested this? Anyone?

**Comment by megheaiulian** [comment]
We're currently running this change on a server where rsyslog adds geoip info to logs.

**Pull request merged**
