### PR TITLE
nixos/libreswan: use /etc/ipsec.conf as config

### PR DESCRIPTION
**Pull request by ooesili**
###### Motivation for this change
It appears that the --config flags don't actually work, because
libreswan fails to start unless the config exists at /etc/ipsec.conf as
well. The simplest solution is just to exclusively use /etc/ipsec.conf
as a config file which seems to make libreswan happy.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ooesili** [comment]
Hmmm. Changes to the config file no longer trigger restarts of the ipsec service because there is no longer a store path that changes. Not really sure how to get around this.

**Comment by aneeshusa** [comment]
I believe you can use `restartTriggers` for this: https://github.com/NixOS/nixpkgs/search?q=restartTriggers&unscoped_q=restartTriggers

**Comment by markuskowa** [comment]
You could use `environment.etc."ipsec.conf"`. That creates a in /etc to the store path.

**Comment by ooesili** [comment]
@aneeshusa nice call, that totally worked. Just pushed up a change which I think actually made the diff smaller.

**Comment by mmahut** [comment]
Any updates on this pull request, please?

**Comment by markuskowa** [comment]
I would recommend to hold this PR back until libreswan is updated. Version 3.18, which is in nixpkgs, is from Jul 27, 2016. The most recent version is 3.29. When the problem still exists after the update we can merge this PR. 

Note that there is also a [CVE](https://libreswan.org/security/) out for pre 3.28 versions.

**Comment by iblech** [comment]
Not the original submitter, but I can confirm that this issue is still relevant and that the proposed fix works. To my eyes, it is ready to merge.

There is still another stumbling block which could be fixed in the future: ipsec does not start if the directory `/etc/ipsec.d` does not exist.

**Comment by ooesili** [comment]
I'm not using libreswan anymore (wireguard gang) so I'm not going to be able to validate changes to this PR. If someone else wants to carry across to the finish line, please do.

**Pull request closed without merging**
