### PR TITLE
neovim: Allow overriding the derivation of neovim even through the c...

### PR DESCRIPTION
**Pull request by Nadrieril**
…onfiguration wrapper

###### Motivation for this change
When using the neovim configuration options, the neovim derivation gets replaced by a wrapper that links to the actual neovim derivation output. In doing so, it hides the normal neovim derivation.
The problem is that if one wants to override an attribute of the underlying neovim (say, to patch it), using `overrideAttrs` will instead modify the wrapper, which is not the desired behavior.

This PR makes it so that calling `pkgs.neovim.overrideAttrs` always overrides the expected derivation, even when neovim gets configured before of after.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
> When using the neovim configuration options, the neovim derivation gets replaced by a wrapper that links to the actual neovim derivation output. In doing so, it hides the normal neovim derivation.

In my opinion a wrapper should always be returned for the sake of consistency.

> The problem is that if one wants to override an attribute of the underlying neovim (say, to patch it), using overrideAttrs will instead modify the wrapper, which is not the desired behavior.

`overrideAttrs` should override the call to `stdenv.mkDerivation` of the derivation that is returned. If it returns the wrapped one, then `overrideAttrs` should override that. 

> This PR makes it so that calling pkgs.neovim.overrideAttrs always overrides the expected derivation, even when neovim gets configured before of after.

Maybe its better to have an `overrideNeovim` method then instead for overriding the underlying derivation.

Anyway, I don't use `neovim` and don't know how its build.

**Comment by Nadrieril** [comment]
I agree that it would be better to always have a wrapper, but as it is now changing it may break configurations. Actually the best way would be for the wrapper to use `pkgs.neovim` instead of the locally declared neovim, but this seems tricky to me.

**Comment by Nadrieril** [comment]
Probably a better way would be to have two separate packages, like what firefox does. This would be very breaking though.

**Comment by teto** [comment]
I guess https://github.com/NixOS/nixpkgs/pull/32657 might interest you. It would be nice if you could give it a spin.

**Comment by Nadrieril** [comment]
Fixed by #32657.

**Pull request closed without merging**
