### PR TITLE
rtl8814au: init at 4.3.21

### PR DESCRIPTION
**Pull request by Lassulus**
tested with linux_4_9 and linux_4_14
---

### CODE REVIEW

**Comment by grahamc** [comment]
@GrahamcOfBorg eval

master had a bug in it, sorry

**Comment by Mic92** [comment]
@GrahamcOfBorg build linuxPackages_testing_bcachefs.rtl8814au -p linuxPackages.rtl8814au -p linuxPackages_4_15.rtl8814au -p linuxPackages_4_9.rtl8814au -p linuxPackages_
4_4.rtl8814au -p linuxPackages_copperhead_hardened.rtl8814au -p linuxPackages_xen_dom0_hardened.rtl8814au -p linuxPackages_xen_dom0.rtl8814au -p linuxPackages_latest_hardened.rtl8814au -p linuxPackages_latest_xen
_dom0.rtl8814au -p linuxPackages_latest_xen_dom0_hardened.rtl8814au -p linuxPackages_samus_4_12.rtl8814au -p linuxPackages_hardened.rtl8814au

**Comment by Mic92** [comment]
@GrahamcOfBorg build linuxPackages_testing_bcachefs.rtl8814au linuxPackages.rtl8814au linuxPackages_4_15.rtl8814au linuxPackages_4_9.rtl8814au linuxPackages_
4_4.rtl8814au  linuxPackages_copperhead_hardened.rtl8814au  linuxPackages_xen_dom0_hardened.rtl8814au  linuxPackages_xen_dom0.rtl8814au  linuxPackages_latest_hardened.rtl8814au  linuxPackages_latest_xen
_dom0.rtl8814au  linuxPackages_latest_xen_dom0_hardened.rtl8814au linuxPackages_samus_4_12.rtl8814au linuxPackages_hardened.rtl8814au

**Comment by Mic92** [comment]
@GrahamcOfBorg build linuxPackages_testing_bcachefs.rtl8814au linuxPackages.rtl8814au linuxPackages_4_15.rtl8814au linuxPackages_4_9.rtl8814au linuxPackages_4_4.rtl8814au linuxPackages_copperhead_hardened.rtl8814au linuxPackages_xen_dom0_hardened.rtl8814au linuxPackages_xen_dom0.rtl8814au linuxPackages_latest_hardened.rtl8814au linuxPackages_latest_xen
_dom0.rtl8814au linuxPackages_latest_xen_dom0_hardened.rtl8814au linuxPackages_samus_4_12.rtl8814au linuxPackages_hardened.rtl8814au

**Comment by Mic92** [comment]
@GrahamcOfBorg build linuxPackages_testing_bcachefs.rtl8814au linuxPackages.rtl8814au linuxPackages_4_15.rtl8814au linuxPackages_4_9.rtl8814au linuxPackages_
4_4.rtl8814au linuxPackages_copperhead_hardened.rtl8814au linuxPackages_xen_dom0_hardened.rtl8814au linuxPackages_xen_dom0.rtl8814au linuxPackages_latest_hardened.rtl8814au linuxPackages_latest_xen_dom0.rtl8814au linuxPackages_latest_xen_dom0_hardened.rtl8814au linuxPackages_samus_4_12.rtl8814au linuxPackages_hardened.rtl8814au

**Comment by Mic92** [comment]
oh, man github is breaking my lines. I will just do compile it on my own.

**Pull request merged**
