### PR TITLE
[20.09]: pythonPackage.python-gitlab: add missing tests requirements

### PR DESCRIPTION
**Pull request by nyanloutre**
(cherry picked from commit 9225192bf67c72ec69b7d489b0e3d368a778ee4b)

###### Motivation for this change

Cherry-picked to fix 20.09 branch

#97479

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by drewrisinger** [comment]
Change PR name to ``[20.09]: ...``
Can you also reference the original PR this is cherry-picked from?

**Comment by nyanloutre** [comment]
Original PR: #97866

**Review by drewrisinger — APPROVED** [review]
* [x] Diff LGTM
* [x] Commit LGTM
* [x] Builds

x86_64-linux
```
https://github.com/NixOS/nixpkgs/pull/98000
2 packages built:
python37Packages.python-gitlab python38Packages.python-gitlab
```

**Comment by risicle** [comment]
WFM macos 10.14

**Comment by nyanloutre** [comment]
@risicle what will be the #100000 ?

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 98000 [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>2 packages built:</summary>  <ul>    <li>python37Packages.python-gitlab</li>    <li>python38Packages.python-gitlab</li>  </ul></details>

**Pull request merged**
