### PR TITLE
root: 6.12.06 -> 6.18.04

### PR DESCRIPTION
**Pull request by veprbl**
###### Motivation for this change

To provide a more modern version of ROOT.

cc @yipengsun who pointed out the issue to me

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — APPROVED** [review]
diff LGTM
most executables show usage (didn't test them all)

```
[6 built (1 failed), 240 copied (194.9 MiB), 70.9 MiB DL]
error: build of '/nix/store/8h475w2jgvbj88svpig8prbyxq6xkiak-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/75569
2 package failed to build:
python27Packages.root_numpy python27Packages.rootpy

5 package were built:
fastnlo hepmc3 mcgrid root yoda-with-root
```

I'll open up a different PR to fix the packages broken on master
```
builder for '/nix/store/3ljrk9zfagj8zynxicvmz9v8vdfikdli-python2.7-root_numpy-4.8.0.drv' failed with exit code 1; last 10 log lines:
  setting SOURCE_DATE_EPOCH to timestamp 1547045302 of file root_numpy-4.8.0/setup.cfg
  patching sources
  configuring
  no configure script, doing nothing
  building
  Executing setuptoolsBuildPhase
  Traceback (most recent call last):
    File "nix_run_setup", line 3, in <module>
      import setuptools
  ImportError: No module named setuptools
```

**Comment by jonringer** [comment]
@GrahamcOfBorg build fastnlo hepmc3 mcgrid root yoda-with-root

**Comment by jonringer** [comment]
darwin timeout due to llvm timeout

**Comment by veprbl** [comment]
> I'll open up a different PR to fix the packages broken on master

I appreciate this a lot. However, I think the time has come to remove `python27Packages.root_numpy` and `python27Packages.rootpy` packages. The first one is replaced by `pythonPackages.uproot` аnd there are some developments to do that in ROOT itself, it seems. The second one could work without the `root_numpy` dependency, but, I assume, the package has become a bit stale, and, judging by its issue tracker, it will not work with ROOT 6.18

**Comment by jonringer** [comment]
no problem :), it was an easy fix.

For deprecating the package, feel free to do what you would like :). Python2 is EOL in 2 weeks anyway, I just don't like seeing failure noise in nix-review

**Comment by veprbl** [comment]
Well, I don't know what the plan is. But if it is to just crash all of python2 infrastructure in nixpkgs, then now is the good time to drop these.

**Comment by jonringer** [comment]
it will likely be up to @FRidh as he probably has more insight than I do. My assumption would be to let it ride until a major CVE is announced, then mark it as vulnerable or remove it entirely

**Pull request merged**
