### PR TITLE
mfi-controller: remove

### PR DESCRIPTION
**Pull request by Mic92**
reason: build fails in hydra
Do still need and want to maintain this @elitak?

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
Don't merge this, it is still referenced in `nixos/modules/services/networking/mfi.nix`

**Comment by Mic92** [comment]
Looks like there won't be any new version for mfi controller soon: https://community.ubnt.com/t5/mFi/is-MFI-dead/td-p/1388153

**Comment by elitak** [comment]
I'll have look today and let you know.

**Comment by elitak** [comment]
Yeah, this is well beyond the point of salvaging; go ahead and remove them.

**Comment by Mic92** [comment]
I suppose, you can still use a container with the old nixos release for a while.

**Comment by elitak** [comment]
Do you mean a nixos-container? I didn't think that worked anymore. It used
to be possible to have a different set of nixos modules applied to a
container, but that was reverted some months ago. Am I missing some way to
replace the entire nixpkgs in a nixos-container?

Anyway, I'm probably the only person in the world using mfi on NixOS as it
is, because that `mongodb248` package has been segfaulting since glibc was
upgraded from 2.23. I've been overriding that attr to a closure in the
store, for some time now. As you saw, the product's been completely
abandoned. All it really needs is an update to the slightly newer mongodb
API, but I'm disinclined to invest my time into decompiling java bytecode.

**Pull request merged**
