### PR TITLE
libreoffice: big cleanup + bumps

### PR DESCRIPTION
**Pull request by K900**
## Description of changes

- massively clean up expression
- add a bunch of fonts needed for tests to pass
- down to 5  skipped tests, 2 of them root caused
- allow building with Qt/KF6
- unvendor a bunch of stuff
- simplify a bunch more stuff
- not everything tested yet but I'm going to bed

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by 7c6f434c** [comment]
Read the diff, looks good, thanks for this large effort! Are you sure you shouldn't be added to maintainers?

**Comment by K900** [comment]
I'm not really interested in maintaining this long term, to be honest, I just wanted to make sure we don't ship a release with insecure libreoffice.

**Comment by 7c6f434c** [comment]
@ofborg build libreoffice-qt

**Comment by 7c6f434c** [comment]
I can't promise things won't slowly slip back because not for all things I am sure what is the cleanest way to do updates…

(But yes, the improvement is large and upstream tries not to have too much churn without reason, so hopefully things will stay better than before for a long time)

**Comment by K900** [comment]
I'm running all the builds locally, there's still some flaky tests it seems, so I'm excluding those and rerunning things a lot, which takes a while...

**Comment by K900** [comment]
I just found more flaky tests :(

**Comment by 7c6f434c** [comment]
For the avoidance of doubt, as OfBorg succeeded on one  Darwin once and on both Linux too, blocking out some more flaky tests (but still fewer overall than we had before) does not remove my approval to merge.

**Comment by 7c6f434c** [comment]
@ofborg build libreoffice-qt

**Comment by 7c6f434c** [comment]
The neutral test is ENOSPC

**Comment by K900** [comment]
Had to skip one more test, but I think we're good to go now. Rebuilding the last build that failed to confirm.

**Comment by K900** [comment]
Finally, all the tests are good.

**Pull request merged**
