### PR TITLE
inconsolata-nerdfont: init at 2.0.0

### PR DESCRIPTION
**Pull request by pasunboneleve**
###### Motivation for this change

nerdfonts-2.0.0 is a 2GB download. Each of these is < 10 MB download. It makes sense to provide separate packages for each font. This prevents issues such as described in #47921.

###### Things done

I build both, installed on my system and checked their presence with font-manager.

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FlorianFranzen** [comment]
I agree that installing all of them at once is not always what you want, but I think for this to be merged a more general solution with an auto-update script that creates derivation for all available fonts will be needed.

**Comment by jtanguy** [comment]
I have this same problem and I am trying to do the method you described. 
I have pushed my work in https://github.com/jtanguy/nixpkgs/tree/nerdfonts, but I am not sure how I should test it before making any PR.

Could somebody help me on this ?

**Comment by ryantm** [comment]
@jtanguy What are you trying to test about it?

**Comment by mmlb** [comment]
@jtanguy maybe just go ahead with the PR? I'd add an `passthru.updateScript = ./update.sh;` but lets get that feedback in a PR.

**Comment by ryantm** [comment]
Okay, let's merge it then make it better.

**Pull request merged**
