### PR TITLE
fido2luks: patch for #188524

### PR DESCRIPTION
**Pull request by ehllie**
###### Description of changes
Fixes builds by patching in a newer version of libcryptsetup-rs

###### Things done

Bumped the upstream dependency from `libcryptsetup-rs 0.4.4` to `libcryptsetup-rs 0.5.1`

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by prusnak** [comment]
Can you please send the pull request to the upstream project proposing the changes and the use the patch via the fetchpatch from Github?

**Comment by ehllie** [comment]
> Can you please send the pull request to the upstream project proposing the changes and the use the patch via the fetchpatch from Github?

Done

**Comment by prusnak** [comment]
Please add a link to https://github.com/shimunn/fido2luks/pull/50 as a comment

**Comment by qbit** [comment]
Maybe nix-review is doing something funky, but this fails to build for me:

```
[nix-shell:~/.cache/nixpkgs-review/pr-190304]$ nix log /nix/store/lc0lv86mx2lral4zqlgkb586d6hdsxva-fido2luks-0.2.20-vendor.tar.gz.drv
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/b1jz055jsq6f3l7qy18jhl88453yn36g-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
applying patch /nix/store/1k7mh0994jrxy2yd1hj8wwncv6hp1j63-libcryptsetup-rs.patch
patching file Cargo.lock
patching file Cargo.toml
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
    Updating crates.io index
error: failed to sync

Caused by:
  failed to load pkg lockfile

Caused by:
  Unable to update registry `crates-io`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  the global directory doesn't exist: No such file or directory; class=Os (2); code=NotFound (-3)
Traceback (most recent call last):
  File "/nix/store/nr39ky7gy806a7qclikfnpb9gai8k4qr-cargo-vendor-normalise/bin/.cargo-vendor-normalise-wrapped", line 42, in <module>
    main()
  File "/nix/store/nr39ky7gy806a7qclikfnpb9gai8k4qr-cargo-vendor-normalise/bin/.cargo-vendor-normalise-wrapped", line 17, in main
    assert list(data.keys()) == ["source"]
AssertionError

```

**Comment by ehllie** [comment]
> Maybe nix-review is doing something funky, but this fails to build for me:
> 
> ```
> [nix-shell:~/.cache/nixpkgs-review/pr-190304]$ nix log /nix/store/lc0lv86mx2lral4zqlgkb586d6hdsxva-fido2luks-0.2.20-vendor.tar.gz.drv
> @nix { "action": "setPhase", "phase": "unpackPhase" }
> unpacking sources
> unpacking source archive /nix/store/b1jz055jsq6f3l7qy18jhl88453yn36g-source
> source root is source
> @nix { "action": "setPhase", "phase": "patchPhase" }
> patching sources
> applying patch /nix/store/1k7mh0994jrxy2yd1hj8wwncv6hp1j63-libcryptsetup-rs.patch
> patching file Cargo.lock
> patching file Cargo.toml
> @nix { "action": "setPhase", "phase": "configurePhase" }
> configuring
> no configure script, doing nothing
> @nix { "action": "setPhase", "phase": "buildPhase" }
> building
>     Updating crates.io index
> error: failed to sync
> 
> Caused by:
>   failed to load pkg lockfile
> 
> Caused by:
>   Unable to update registry `crates-io`
> 
> Caused by:
>   failed to fetch `https://github.com/rust-lang/crates.io-index`
> 
> Caused by:
>   the global directory doesn't exist: No such file or directory; class=Os (2); code=NotFound (-3)
> Traceback (most recent call last):
>   File "/nix/store/nr39ky7gy806a7qclikfnpb9gai8k4qr-cargo-vendor-normalise/bin/.cargo-vendor-normalise-wrapped", line 42, in <module>
>     main()
>   File "/nix/store/nr39ky7gy806a7qclikfnpb9gai8k4qr-cargo-vendor-normalise/bin/.cargo-vendor-normalise-wrapped", line 17, in main
>     assert list(data.keys()) == ["source"]
> AssertionError
> ```

It might be something with nix-review. Linux builds seem to have succeeded in ofborg, and I've pulled this change to my nixos configuration and managed to unlock the boot partition with it.

**Comment by ehllie** [comment]
Closing #188524

**Pull request merged**
