### PR TITLE
treewide: add a debug-output to a few packages

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

After learning about the optional [debug](https://nixos.wiki/wiki/Debug_Symbols)-output I realized that only a few packages provide debug symbols. This PR adds the `debug`-output to an arbitrary list of packages to spread the usage of this feature.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
There were [concerns](https://github.com/NixOS/nixpkgs/issues/18530#issuecomment-246314513) about this taking too much space in binary cache so for now we have only added it to libraries whose rebuild would be too much effort for user, not leaf packages.

**Comment by Ma27** [comment]
That's actually a fair argument, however I guess that the packages I changed are rather popular (and not that many), so the outcome wins here - at least in my opinion.

@edolstra do the concerns you raised back in 2016 still apply? (tbh I'm not sure about what the current upstream infrastructure is able to withstand). If needed I'm also happy to provide more detailed information about the per-package impact on storage.

**Comment by edolstra** [comment]
I don't think this is a good idea. It's one thing to provide debug symbols for some widely used libraries (e.g. Qt), but who really needs debug symbols for `htop`?

**Comment by Ma27** [comment]
@edolstra so your main issue with this is that `htop` (and similar pkgs in here) aren't something you usually need to debug?

The main purpose here is that I wanted to add debug symbols to a few packages I frequently use to be able to easily debug e.g. core-dumps. But I agree that this list is fairly arbitrary and we may want to select a few more (or different) packages.

But may I ask if there's any reason not to enable a `debug`-output on (more or less) every derivation in `nixpkgs`? Being able to load debug-symbols for a (possibly broken) package (if needed) from the binary cache is IMHO an incredible useful feature :)

**Comment by lheckemann** [comment]
@ma27 binary cache size: #18530

**Comment by Ma27** [comment]
@lheckemann I'm aware of that discussion, it's been referenced by @jtojnar already. I mainly asked since I don't know how much of the binary-cache size can be used to serve debug-symbols of packages.

**Comment by jtojnar** [comment]
I think Eelco’s point was that the storage requirements would outweigh costs of occasional rebuilding of leaf packages. Especially since the cache keeps build artefacts indefinitely.

Estimates are in the thread: https://github.com/NixOS/nixpkgs/issues/18530#issuecomment-469053062

**Comment by Ma27** [comment]
> I think Eelco’s point was that the storage requirements would outweigh costs of occasional rebuilding of leaf packages. Especially since the cache keeps build artefacts indefinitely.

Fair enough :+1:

**Pull request closed without merging**
