### PR TITLE
Ceedling - Use Ruby 3.0 instead of latest

### PR DESCRIPTION
**Pull request by JoseAmador95**
## Description of changes

The latest version of Ceedling is not compatible with Ruby 3.1+ as Psych 4.x introduced a breaking change that is not fixed in the Ceedling gem.

https://stackoverflow.com/questions/71191685/visit-psych-nodes-alias-unknown-alias-default-psychbadalias

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by FliegendeWurst — COMMENTED** [review]
Fix looks good to me. Please change your commit message to adhere to https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions

Issue can be reproduced with `ceedling example blinky && cd blinky && ceedling`.

`master` ceedling: `/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:430:in visit_Psych_Nodes_Alias': Unknown alias: common_defines (Psych::BadAlias)`

This PR: (no such error)

**Comment by JoseAmador95** [comment]
Is the commit message ok?

**Review by FliegendeWurst — CHANGES_REQUESTED** [review]
ofborg error: `Function called without required argument "ruby_3_0".`

Are you sure Ruby 3.0 is still packaged in nixpkgs?

**Comment by JoseAmador95** [comment]
It used to work when I first raised the PR. It appears that 3.0 has been deprecated.

**Comment by FliegendeWurst** [comment]
I think in that case the only possible fix is a newer version of Ceedling.

**Pull request closed without merging**
