### PR TITLE
flutter: rename & expose builders

### LINKED ISSUE #200986: flutter: Expose flutterDrv, patch directories for external use
The [Flutter package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/flutter/default.nix) provides a `mkFlutter` function to allow customized Flutter derivations to be made.

Internally, however, it uses a `flutterDrv` function that calls `mkFlutter` with URLs generated from the given version number. Patches are also used internally, but there is no way (that I know of) to access these externally.

I propose that `flutterDrv` and `flutter2Patches`/`flutter3Patches` attributes get added to the attribute set along with `mkFlutter`, to make it easier to create custom Flutter derivations.

### PR DESCRIPTION
**Pull request by algorithmiker**
###### Description of changes
This is a follow-up of https://github.com/NixOS/nixpkgs/pull/200988,  but now it exposes it as a passthru too. 
Closes https://github.com/NixOS/nixpkgs/issues/200986

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by hacker1024 — COMMENTED** [review]
I like the idea, but I'm not too keen on the naming here. The hierarchy is not clear from the names alone - which function builds on which? If anything, I'd guess the opposite of what's actually happening.

Additionally, why should `mkFlutter` generate the SDK source URL while `mkFlutterWithDart` does not?

Maybe something along the lines of `mkFlutter` and `mkGoogleFlutter` instead?

**Comment by hacker1024** [comment]
> I am not even sure we need two functions. What do you think? EDIT: changed my mind.
> 
> What about `mkFlutter` for the one with `dartHash` and `dartVersion` and mkCustomFlutter for the more general one? Or just not exposing the first here altogether, since it is only used here.

I like `mkCustomFlutter`. I think we should expose it in case someone wants to use their own fork.

**Review by hacker1024 — APPROVED** [review]
LGTM

**Review by hacker1024 — COMMENTED** [review]
Actually, perhaps the added passthru attributes should be added in `default.nix` with `overrideAttrs`?

That way, `flutter.nix` does not need to worry about choices made in `default.nix`.

**Comment by hacker1024** [comment]
> Should we just move everything in passthru there?

In my opinion:

- `dart` makes sense in `flutter.nix` as it is used in the build process anyway
- `sdk` makes sense in `flutter.nix` as other hierarchical attributes like it are in files other than `default.nix`, such as the wrapper's `unwrapped`
- `buildFlutterApplication` might be more appropriate in `default.nix`, using the `mkFlutter` and `wrapFlutter` functions

**Review by ericdallo — APPROVED** [review]

**Pull request merged**
