### PR TITLE
sgx-psw+aesmd: 2.24 -> 2.25

### PR DESCRIPTION
**Pull request by phlip9**
## Changes

Update the `sgx-psw` package to the [latest 2.25 release](https://github.com/intel/linux-sgx/releases/tag/sgx_2.25).

+ Diff: <https://github.com/intel/linux-sgx/compare/sgx_2.24...sgx_2.25>

+ Changelog: <https://github.com/intel/linux-sgx/releases/tag/sgx_2.25>

This diff also decouples the `sgx-psw` and `sgx-sdk` builds so that `sgx-psw` no longer depends on `sgx-sdk`. I discovered that we only require some headers and a single build tool (`sgx_edger8r`) from the base sdk to build `sgx-psw`. The biggest benefit here is that I can quickly iterate on `sgx-psw`, which takes just 3 min to build, vs. waiting 1+ hour to build both `sgx-sdk` and `sgx-psw`.

I [attempted to update `sgx-sdk` and `ipp-crypto` to 2.25](https://github.com/phlip9/nixpkgs/tree/phlip9/sgx-2.25), but the SDK appears broken in some inscrutable ways. It builds successfully, but most of the sample enclaves segfault or return [error 0x1007 (SGX_ERROR_ECALL_NOT_ALLOWED)](https://github.com/intel/linux-sgx/blob/7385e10ce1106215d15f874a024ca224c7417eea/common/inc/sgx_error.h#L53) at runtime. I don't really have the patience to waste more time on the SDK. With this diff I can now focus updates on the single, useful artifact: the `aesmd` service.

**Quick Glossary:**

- **Intel SGX** is a Confidential Computing technology for running hardware-isolated enclaves and confidential VMs (Intel TDX) on Intel server CPUs alongside an untrusted hypervisor/Linux/userspace software stack.
- `sgx-psw` (Platform SoftWare) provides the `aesmd` service (Architecture Enclave Service Manager Daemon), which simplifies running enclaves and getting remote attestation quotes.

**Testing:**

These changes were tested on an SGX-enabled Azure gen2 VM (DCSv3) running NixOS.

## Run against real SGX hardware

Make sure you're running on a recent x86-64 Intel CPU, against a somewhat recent kernel with the in-tree kernel SGX driver (any NixOS config in the last few years should cover this).

Check the hardware and kernel setup:

```bash
$ journalctl --boot --dmesg --grep=sgx
kernel: sgx: EPC section 0x2c0000000-0x3bfffffff
```

In your NixOS `configuration.nix`, add something like:

```nix
  services.aesmd = {
    enable = true;
    # Include this if you're running on Azure
    quoteProviderLibrary = pkgs.sgx-azure-dcap-client;
  };
```

After a `nixos-rebuild switch`, check that the devices are configured and the `aesmd` service is running:

```bash
$ find /dev -name "*sgx*" -ls
 83      0 crw-rw----   1 root     sgx_prv   10, 126 May  8 17:21 /dev/sgx_provision
 84      0 crw-rw----   1 root     sgx       10, 125 May  8 17:21 /dev/sgx_enclave
400      0 drwxr-xr-x   2 root     root           80 May  8 17:21 /dev/sgx

$ systemctl status aesmd.service
● aesmd.service - Intel Architectural Enclave Service Manager
     Loaded: loaded (/etc/systemd/system/aesmd.service; enabled; preset: ignored)
     Active: active (running) since Sat 2024-11-02 01:56:46 UTC; 30min ago
 Invocation: 708bd878f2e7439b8717e5bbba02d307
    Process: 1464 ExecStartPre=/nix/store/vrafi5h28rnfbdxjn5lf19kk9jqxy2jj-copy-aesmd-data-files.sh (code=exited, status=0/SUCCESS)
   Main PID: 1502 (aesm_service)
         IP: 51.2K in, 9.6K out
         IO: 2.2M read, 48K written
      Tasks: 4 (limit: 9514)
     Memory: 5.2M (peak: 5.4M)
        CPU: 373ms
     CGroup: /system.slice/aesmd.service
             └─1502 /nix/store/1mq9p17qkh74fs1yk7hnrisikzmhp3y3-sgx-psw-2.25.100.3/aesm/aesm_service --no-daemon

Nov 02 01:56:46 lexe-dev-sgx systemd[1]: Started Intel Architectural Enclave Service Manager.
Nov 02 01:56:46 lexe-dev-sgx aesm_service[1502]: The path of system bundle: System Bundle
Nov 02 01:56:46 lexe-dev-sgx aesm_service[1502]: ecdsa_quote_service_bundle_name:2.0.0
Nov 02 01:56:46 lexe-dev-sgx aesm_service[1502]: epid_quote_service_bundle_name:2.0.0
Nov 02 01:56:46 lexe-dev-sgx aesm_service[1502]: le_launch_service_bundle_name:2.0.0
Nov 02 01:56:46 lexe-dev-sgx aesm_service[1502]: linux_network_service_bundle_name:2.0.0
Nov 02 01:56:46 lexe-dev-sgx aesm_service[1502]: pce_service_bundle_name:2.0.0
Nov 02 01:56:46 lexe-dev-sgx aesm_service[1502]: quote_ex_service_bundle_name:2.0.0
Nov 02 01:56:46 lexe-dev-sgx aesm_service[1502]: system_bundle:4.0.0
Nov 02 01:58:19 lexe-dev-sgx aesm_service[1502]: Azure Quote Provider: libdcap_quoteprov.so [INFO]: Debug Logging Enabled
```

Run a test enclave that exercises remote attestation:

```bash
$ nix run -L github:lexe-app/lexe-public#run-sgx-test
```

### CODE REVIEW

**Comment by symphorien** [comment]
changelog says:
> Note that PCCS is not available from this release. Please follow DCAP installation guide to use PCCSAdminTool to retrieve the attestation collaterals or use old version PCCS.

which sounds like a breaking change. I guess this has to wait for branch-off.

**Comment by phlip9** [comment]
Hey @symphorien, this package (`sgx-psw`) only includes the `aesmd` service. The PCCS service is not included, so there should be no breaking change. The upstream changelog is a bit confusing as it covers both this package and some other packages, like `sgx-sdk` and `ipp-crypto`.

**Comment by symphorien** [comment]
mmh my bad

**Comment by symphorien** [comment]
the removal of the nixos `debug` option is still a breaking change, so this still has to wait for branch off, which is tomorrow. I'll probably merge this week end, remind me next week if I forget.

**Pull request merged**
