### PR TITLE
libtiff: get rid of aarch64-darwin.nix

### PR DESCRIPTION
**Pull request by tanshihaj**
###### Description of changes
I've tried to build libtiff on aarch64-darwin using default.nix and it seems that it builds fine on my mac. Continue of this pr: https://github.com/NixOS/nixpkgs/pull/181446.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tanshihaj** [comment]
@ajs124 are you happy with this PR? Can we merge it?

**Review by ajs124 — APPROVED** [review]
diff LGTM, don't have any aarch64-darwin hardware though

**Comment by tanshihaj** [comment]
Well, I have one and I checked that it builds. Maybe we will also ask someone to check build on aarch-darwin?

I know only @risicle, he checked this pr: https://github.com/NixOS/nixpkgs/pull/182367#issuecomment-1192020011, maybe he will agree to check also this pr.

**Comment by risicle** [comment]
`libtiff.tests` reveals no new failures for me on macos 12.4 aarch64, but this will probably need to be rebased to staging (using the technique outlined in https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging). The automatic rebuild counter labels don't seem to assess darwin aarch64, but if they did you'd see this causing >500 rebuilds.

**Comment by tanshihaj** [comment]
@kalbasit @Mic92 @zowoq @ttuegel @matthewbauer @stigtsp @zakame @FRidh @jonringer @fricklerhandwerk @Ericson2314, sorry, I've messed with rebasing, can you remove yourselves as reviewer?

**Review by risicle — APPROVED** [review]

**Pull request merged**
