### PR TITLE
python3Packages: don't depend on setup hooks' bash eval (part with fewer rebuilds)

### PR DESCRIPTION
**Pull request by wolfgangwalther**
This is a part of #352976. Those packages here should cause almost no rebuilds, so targeting master.

@ShamrockLee @emilazy 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ShamrockLee** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 354811`

---
### `aarch64-linux`
<details>
  <summary>:x: 8 packages failed to build:</summary>
  <ul>
    <li>conan</li>
    <li>conan.dist</li>
    <li>python311Packages.dtw-python</li>
    <li>python311Packages.dtw-python.dist</li>
    <li>python312Packages.dtw-python</li>
    <li>python312Packages.dtw-python.dist</li>
    <li>routersploit</li>
    <li>routersploit.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 46 packages built:</summary>
  <ul>
    <li>fichub-cli</li>
    <li>fichub-cli.dist</li>
    <li>home-assistant-component-tests.efergy</li>
    <li>home-assistant-component-tests.rainforest_raven</li>
    <li>picard</li>
    <li>picard.dist</li>
    <li>python311Packages.aioraven</li>
    <li>python311Packages.aioraven.dist</li>
    <li>python311Packages.bottleneck</li>
    <li>python311Packages.bottleneck.dist</li>
    <li>python311Packages.certbot-dns-inwx</li>
    <li>python311Packages.certbot-dns-inwx.dist</li>
    <li>python311Packages.iso4217</li>
    <li>python311Packages.iso4217.dist</li>
    <li>python311Packages.macaddress</li>
    <li>python311Packages.macaddress.dist</li>
    <li>python311Packages.orange3</li>
    <li>python311Packages.orange3.dist</li>
    <li>python311Packages.pyefergy</li>
    <li>python311Packages.pyefergy.dist</li>
    <li>python311Packages.qcodes</li>
    <li>python311Packages.qcodes-contrib-drivers</li>
    <li>python311Packages.qcodes-contrib-drivers.dist</li>
    <li>python311Packages.qcodes.dist</li>
    <li>python311Packages.recordlinkage</li>
    <li>python311Packages.recordlinkage.dist</li>
    <li>python312Packages.aioraven</li>
    <li>python312Packages.aioraven.dist</li>
    <li>python312Packages.bottleneck</li>
    <li>python312Packages.bottleneck.dist</li>
    <li>python312Packages.certbot-dns-inwx</li>
    <li>python312Packages.certbot-dns-inwx.dist</li>
    <li>python312Packages.iso4217</li>
    <li>python312Packages.iso4217.dist</li>
    <li>python312Packages.macaddress</li>
    <li>python312Packages.macaddress.dist</li>
    <li>python312Packages.orange3</li>
    <li>python312Packages.orange3.dist</li>
    <li>python312Packages.pyefergy</li>
    <li>python312Packages.pyefergy.dist</li>
    <li>python312Packages.qcodes</li>
    <li>python312Packages.qcodes-contrib-drivers</li>
    <li>python312Packages.qcodes-contrib-drivers.dist</li>
    <li>python312Packages.qcodes.dist</li>
    <li>python312Packages.recordlinkage</li>
    <li>python312Packages.recordlinkage.dist</li>
  </ul>
</details>

**Comment by ShamrockLee** [comment]
`github:NixOS/nixpkgs#legacyPackages.aarch64-linux.conan` already builds on `master`, and the build seems to be inside the binary cache. It is a new failure.

Here is the build log of the failed build:
https://nixbuild.net/builds/3430998?t=EtkBCm8KBWJ1aWxkCgpidWlsZDpyZWFkGAMiCQoHCAcSAxCLAyINCgsIBBIHOgUKAxiBCDImCiQKAggbEgYIBRICCAUaFgoECgIIBQoICgYgko7txQYKBBoCCAAyFgoUCgIIGxIOCAISAxiACBIFENa00QESJAgAEiB43J0cbeJ0O_4LYoJjk06GjdQQjPtig79nv5blntuyqRpAx3MEU7748bAa76fjThvxu8nnZ4QXOmoHfSmqqEx-_uI-vIFQ0VhCIaS6uxtTm_OdCEe8IxX5TBWlb89a7g04DiIiCiCFpJ4UNuvp1VTdU5gM7de983cLPO3XikpfBD8OIo3EVA==

**Comment by ShamrockLee** [comment]
I set `settings reuse-build-failures --set false` on nixbuild.net to rebuild it, but the same test failed again.

I'll also build it on NixOnDroid, but that would take a while because my phone lacks CPU power.

@ofborg build conan

**Comment by ShamrockLee** [comment]
> > I set `settings reuse-build-failures --set false` on nixbuild.net to rebuild it, but the same test failed again.
> 
> That was on `master`? Or is master consistently building even when **not** taking it from the cache?

The failure happens when building `github:wolfgangwalther/nixpkgs/no-python-eval-master#legacyPackages.aarch64-linux.conan`.

**Comment by ShamrockLee** [comment]
Oh! Now I get what you mean. I'll build it on `master` with the `--rebuid` flag.

**Comment by ShamrockLee** [comment]
The build turns out to be reproducible on the `master` branch with the `--rebuild` flag.

The `conan` changes here seem trivial. Maybe they trigger the failure just by causing a rebuild.

**Comment by ShamrockLee** [comment]
> The build turns out to be reproducible on the `master` branch with the `--rebuild` flag.
> 
> The `conan` changes here seem trivial. Maybe they trigger the failure just by causing a rebuild.

The build log of the `master` build with `--rebuilds` by `nixbuild.net` is similar to that after this change but different from that of OfBorg. Both fail the tests.

**Comment by ShamrockLee** [comment]
@HaoZeke, what do you think about Conan's test failure?

**Comment by ShamrockLee** [comment]
> In this case, I would suggest we just disable the specific test and then continue.

The nixbuild.net aarch64-linux builder fails `test/integration/toolchains/google/test_bazeldeps.py::test_shared_windows_find_libraries`, and the OfBorg aarch64-linux builder `test/integration/remote/auth_test.py::test_token_expired`.

**Comment by ShamrockLee** [comment]
@ofborg build conan

**Comment by ShamrockLee** [comment]
Now `github:wolfgangwalther/nixpkgs/no-python-eval-master#legacyPackages.aarch64-linux.conan` builds successfully on `nixbuild.net`.

**Review by ShamrockLee — APPROVED** [review]

**Review by emilazy — APPROVED** [review]

**Pull request merged**
