### PR TITLE
crc32c: 1.1.0 -> 1.1.2

### PR DESCRIPTION
**Pull request by cpcloud**
###### Motivation for this change

- Update `crc32c`
- Enable tests

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cpcloud** [comment]
@andir Any chance you might be able to review this :smile: ?

**Review by andir — COMMENTED** [review]
On first sight this doesn't look to bad of a change. Thanks for working on this!

In general no objections to the improvments.

Can you perhaps cleanup the Git history a bit? It currently has a bunch of commits that probably don't make sense on their own (e.g. enabling tests just to disable them again etc..).

**Comment by cpcloud** [comment]
> Can you perhaps cleanup the Git history a bit? It currently has a bunch of commits that probably don't make sense on their own (e.g. enabling tests just to disable them again etc..).

Yep, wanted to preserve since there were a few formatting changes in there and for review.

**Comment by cpcloud** [comment]
The tests should be fully enabled in the `installCheckPhase`, it's just that when tests are enabled the library builds and install gtest libraries which causes issues if dependents are using the nixpkgs version of gtest since the `crc32c` version would get picked up first in some cases.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 143839` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
28 packages built:
</summary>
<ul>
<li>crc32c</li>
<li>dvc-with-remotes</li>
<li>google-cloud-cpp</li>
<li>python38Packages.gcsfs</li>
<li>python38Packages.gensim</li>
<li>python38Packages.google-cloud-automl</li>
<li>python38Packages.google-cloud-bigquery</li>
<li>python38Packages.google-cloud-storage</li>
<li>python38Packages.google-crc32c</li>
<li>python38Packages.google-resumable-media</li>
<li>python38Packages.pathy</li>
<li>python38Packages.smart-open</li>
<li>python38Packages.spacy</li>
<li>python38Packages.spacy-transformers</li>
<li>python38Packages.textacy</li>
<li>python39Packages.gcsfs</li>
<li>python39Packages.gensim</li>
<li>python39Packages.google-cloud-automl</li>
<li>python39Packages.google-cloud-bigquery</li>
<li>python39Packages.google-cloud-storage</li>
<li>python39Packages.google-crc32c</li>
<li>python39Packages.google-resumable-media</li>
<li>python39Packages.pathy</li>
<li>python39Packages.smart-open</li>
<li>python39Packages.spacy</li>
<li>python39Packages.spacy-transformers</li>
<li>python39Packages.textacy</li>
<li>snakemake</li>
</ul>
</details>

**Pull request merged**
