### PR TITLE
Update io.js (2.3.4 -> 2.4.0)

### PR DESCRIPTION
**Pull request by Havvy**
Built locally successfully.

### CODE REVIEW

**Comment by Havvy** [comment]
TravisCI build failed due to network error.

**Comment by jagajaga** [comment]
Please rename commit's name following our guide from `CONTRIBUTING.md`

**Comment by Havvy** [comment]
@jagajaga: Done

**Comment by jagajaga** [comment]
We use `pkg: v1 -> v2` with no brackets :)
And btw did you test it?

**Comment by Havvy** [comment]
Yes, I always test packages before pushing. Brackets removed. With iojs/nodejs, I keep four IRC bots continuously running.

**Comment by Havvy** [comment]
Thank you for merging. ^.^

**Comment by jagajaga** [comment]
Thank you :)
And please next time write if you have tested the pkg, that will helps a lot!

**Comment by Havvy** [comment]
I would think "Successfully built locally" would imply it was also properly
tested for correctness. But I'll be more explicit that it was tested too in
the future.

**Pull request merged**
