### PR TITLE
coqPackages.interval: 4.1.0 -> 4.1.1

### PR DESCRIPTION
**Pull request by siraben**
###### Motivation for this change
Wanted to bump to 4.2.0, but it's not out yet, in the meantime, we have 4.1.1.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 122214` at 1f10ba25 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>coqPackages.interval</li>
  </ul>
</details>
<details>
  <summary>3 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/build-support/coq/default.nix:107:3:
```
    |
107 |   installPhase = "./remake install";
    |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/build-support/coq/default.nix:106:3:
```
    |
106 |   buildPhase = "./remake -j$NIX_BUILD_CORES";
    |   ^
```
</li>
    <li>warning: unused-argument

Unused argument: `mathcomp`.
Near pkgs/development/coq-modules/interval/default.nix:2:27:
```
  |
2 | , coq, coquelicot, flocq, mathcomp
  |                           ^
```
</li>
  </ul>
</details>

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 122214` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>coqPackages.interval</li>
  </ul>
</details>

**Comment by CohenCyril** [comment]
The `buildPhase` and `installPhase` warnings are my mistake... `mkCoqDerivation` should be fixed at some point (but this is independent from this PR). As for the dependency on `mathcomp` in looks spurious indeed (and might be my mistake too, but we can fix it here).
Other than that I'm fine with the PR.

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 122214` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>coqPackages.interval</li>
  </ul>
</details>

**Pull request merged**
