### PR TITLE
Remove travis builds.

### PR DESCRIPTION
**Pull request by shlevy**
They are very unreliable and produce a lot of meaningless noise.

### CODE REVIEW

**Comment by grahamc** [comment]
(without commenting on the merits of the PR)

looks like we should also be removing ./maintainers/scripts/travis-nox-review-pr.sh and similar files.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nixos/nixpkgs/18376#-:-KR0aOqO2n-ke3BCK-Io:b-el2vaj)*

**Comment by copumpkin** [comment]
That's a reluctant 👍 from me. In its current state, I think it's worse than useless, but I want something like it to exist that works properly and that we can trust. Wasn't Hydra getting similar functionality at some point?

**Comment by shlevy** [comment]
https://github.com/NixOS/hydra/pull/326

**Comment by shlevy** [comment]
@grahamc Done

**Comment by grahamc** [comment]
I wonder if there is a bit of work which would be useful and Travis could execute. Even a simple check like "does nixpkgs evaluate?" would be better than where we are now.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nixos/nixpkgs/18376#-:-KR0bRxsf_8mXv89EccL:bqagvi0)*

**Comment by shlevy** [comment]
Maybe, but until that exists IMO it would be better to reduce the noise.

**Comment by grahamc** [comment]
So, I :lgtm: this because having unreliable testing infra is worse than none at all. I appreciate all the work that's been done to make this more reliable, and wish it had worked out better. I suspect Travis is just not the tool for this job.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nixos/nixpkgs/18376#-:-KR0fRDIJ8nPvrOqd0lb:b-x439hd)*

**Comment by siddharthist** [comment]
Does Travis ever give false positives? I've only ever seen false negatives, which isn't really a huge problem as far as I'm concerned. I think testing that includes false negatives is better than no testing.

**Comment by copumpkin** [comment]
How's that? Human trust in the tool is eroded with every false negative they need to investigate. Eventually if the rate gets high enough they stop paying attention, and it just becomes another piece of noise clamoring for a slice of limited free time.

**Comment by siddharthist** [comment]
@copumpkin It saves time. If Travis builds correctly, nobody has to manually check that a given PR builds. If Travis gave half false negatives, it would still prevent humans from building half of the time. 

That said, y'all work on this much more than I do and if Travis doesn't save you time, then please disregard my comments.

**Comment by joachifm** [comment]
I find it takes less time to determine that the travis error is spurious than it takes to do all the trivial checking currently performed by travis. I'm sure everybody agrees that Hydra is the future, but why the rush to remove travis before there's a working alternative in place? The travis apostates can safely ignore it, no?

**Comment by domenkozar** [comment]
I'm +0 on this. I do think it helps with PRs, because it doesn't give false positives.

Maybe instead we should disable it on all branches and leave it for PRs?

**Comment by shlevy** [comment]
I don't know, newcomers don't know that most of travis's failures are false. But anyway, disabling it on branches would hit 80% of what I care about personally here.

**Comment by copumpkin** [comment]
@siddharthist I guess I just value my time more than my computer's time 😄 

But yes, disabling it on branches is my main issue too. If people want it on PRs, that's fine.

**Comment by domenkozar** [comment]
I've pushed 9ba3d37 that should address the failures on commits outside PRs.

**Comment by peti** [comment]
Travis-CI *does* generate false-positives: https://github.com/NixOS/nixpkgs/issues/7304.

**Comment by shlevy** [comment]
Still getting annoying emails... @domenkozar

**Comment by domenkozar** [comment]
Every time we have a mass rebuild it happens, Travis can't rebuild ghc8 to build the NixOS manual (pandoc).

I think travis-ci does some good for us at the moment, but hopefully we'll have https://github.com/expipiplus1/hercules usable soon as new Hydra API that will allow us to add PRing functionality.

**Comment by vcunat** [comment]
Hercules :-) I hope the PR load won't [kill Hydra](http://www.perseus.tufts.edu/Herakles/hydra.html).

**Comment by domenkozar** [comment]
That's the reason it was picked :)

**Pull request closed without merging**
