### PR TITLE
keybase,keybase-gui: 5.0.0 -> 5.1.1

### PR DESCRIPTION
**Pull request by Br1ght0ne**
###### Motivation for this change
https://github.com/keybase/client/releases/tag/v5.1.1

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
```
[3 built, 2 copied (4.2 MiB), 1.2 MiB DL]
3 package were built:
kbfs keybase keybase-gui
```
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @carlsverre @np @rvolosatovs @puffnfresh

---
This change is [Reviewable](https://reviewable.io/reviews/nixos/nixpkgs/75531)

### CODE REVIEW

**Review by rvolosatovs — APPROVED** [review]
`keybase` and `keybase-gui` both seem to work fine on NixOS

**Comment by rvolosatovs** [comment]
@GrahamcOfBorg build keybase keybase-gui

**Comment by charles-dyfis-net** [comment]
Note that 5.1.0 was followed up with 5.1.1; this should probably be updated.

**Comment by filalex77** [comment]
@charles-dyfis-net Just noticed that, thanks! Will do.

**Review by charles-dyfis-net — APPROVED** [review]

**Review by puffnfresh — APPROVED** [review]

**Review by judaew — APPROVED** [review]
@charles-dyfis-net Sorry for the late answer. Just now I saw your message. It's LGTM, thanks 🌟

**Pull request merged**
