### PR TITLE
python3Packages.xmlschema: 1.4.1 -> 1.5.3

### PR DESCRIPTION
**Pull request by jonringer**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
```
https://github.com/NixOS/nixpkgs/pull/117445

9 packages built:
matrix-synapse python38Packages.fints python38Packages.pysaml2 python38Packages.sepaxml python38Packages.xmlschema python39Packages.fints python39Packages.pysaml2 python39Packages.sepaxml python39Packages.xmlschema
```

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 117445` at ee41f0e0 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages built successfully:</summary>
  <ul>
    <li>matrix-synapse</li>
    <li>python38Packages.fints</li>
    <li>python38Packages.pysaml2</li>
    <li>python38Packages.sepaxml</li>
    <li>python38Packages.xmlschema</li>
    <li>python39Packages.fints</li>
    <li>python39Packages.pysaml2</li>
    <li>python39Packages.sepaxml</li>
    <li>python39Packages.xmlschema</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern 'elementpath~=2.0.0' doesn't match anything in file 'setup.py'
Near pkgs/development/python-modules/xmlschema/default.nix:39:0:
```
   |
39 |     description = "XML Schema validator and data conversion library for Python";
   | ^
```
</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 117445` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>matrix-synapse</li>
    <li>python38Packages.fints</li>
    <li>python38Packages.pysaml2</li>
    <li>python38Packages.sepaxml</li>
    <li>python38Packages.xmlschema</li>
    <li>python39Packages.fints</li>
    <li>python39Packages.pysaml2</li>
    <li>python39Packages.sepaxml</li>
    <li>python39Packages.xmlschema</li>
  </ul>
</details>

**Review by fabaff — COMMENTED** [review]
`postPatch` should be removed. Upstream says [`install_requires=['elementpath>=2.1.2, <3.0.0'],`](https://github.com/sissaschool/xmlschema/blob/master/setup.py#L30). We have 2.2.0.

`pytestCheckHook`, `disabledTests` and `disabledTestPaths` could be used to modernize the testing part.

Update itself looks good to me.

- [x] package built (see https://github.com/NixOS/nixpkgs/pull/117445#issuecomment-805578258)
- [x] all depending packages build
- [x] tested on x86_64

```bash
...ew/pr-117445/results/python38Packages.xmlschema/lib/python3.8/site-packages]$ python
Python 3.8.8 (default, Feb 19 2021, 11:04:50) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xmlschema
>>> schema = xmlschema.XMLSchema("/home/nix-pkgs/nixpkgs/shiporder.xsd")     
>>> schema.is_valid("/home/nix-pkgs/nixpkgs/shiporder.xml")
True
```

**Review by dotlambda — CHANGES_REQUESTED** [review]
You should remove `postPatch` and switch to `pytestCheckHook`.

**Comment by jonringer** [comment]
closing in favor of #123862

**Pull request closed without merging**
