### PR TITLE
Fix thumbnails generation in nautilus

### PR DESCRIPTION
**Pull request by layus**
###### Motivation for this change

PDF thumbnails (and possibly others) are not generated in nautilus
because the thumbnailers execution is sandboxed.
`/run/current-system` is not mounted in the sandbox, and system binaries
that rely on `$PATH` are not resolvable.

It turns out that .desktop files sometimes contain an absolute path, but
I think it better to just mount /run/current-system in the sandbox
rather than enforcing all the .desktop files to contain an absolute
path, especially since some (like firefox) break when an absolute path
is used there.

```
$ rg -L Exec= /run/current-system/sw/share/thumbnailers                     
/run/current-system/sw/share/thumbnailers/gnome-font-viewer.thumbnailer
2:TryExec=gnome-thumbnail-font
3:Exec=gnome-thumbnail-font --size %s %u %o

/run/current-system/sw/share/thumbnailers/evince.thumbnailer
2:TryExec=evince-thumbnailer
3:Exec=evince-thumbnailer -s %s %u %o

/run/current-system/sw/share/thumbnailers/totem.thumbnailer
2:TryExec=/nix/store/rdiavbwkm520l12c3shc0rjbxaqd8glz-totem-3.30.0/bin/totem-video-thumbnailer
3:Exec=/nix/store/rdiavbwkm520l12c3shc0rjbxaqd8glz-totem-3.30.0/bin/totem-video-thumbnailer -s %s %u %o
```

###### Things done

- [X] Tested on NixOS
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vcunat** [comment]
Instead of `/run/current-system` it would be nicer to have e.g. a `buildEnv` of the required tools or something like that.

**Comment by layus** [comment]
This would add a dependency from nautilus to all the potential thumbnailers. I quite like the flexibility in here. But `/run/current-system/bin` may be a better pick. In vanilla nautilus they mount 
```
"--ro-bind", "/usr", "/usr",
"--ro-bind", "/lib", "/lib",
"--ro-bind", "/lib64", "/lib64",
"--symlink", "usr/bin", "/bin",
```

**Comment by vcunat** [comment]
Ah, OK.  If I understand it right, the best approach might be to build this tiny tool separately make it depend on the set of thumbnailers, but that would probably be too complex and I don't see a significant issue in `/run/current-system/bin`; the worst are probably around restrictions of direct running without installation.

**Comment by layus** [comment]
Now, given that the sandbox aims to protect about programs writing in strange locations when they only need to write one output file (like nix sandboxes), it does not hurt to provide access to the whole /run/current-system as it is a symlink to the store and the whole store is already mounted.

**Comment by vcunat** [comment]
Yes, if that's the (main) purpose of the sandbox.  I just thought you also need the thumbnailers to reside in the sandbox, and you won't have them there unless you "install" them (i.e. presence in `/nix/store` isn't enough).

**Comment by jtojnar** [comment]
We might want to do the same in `gnome-desktop` package since this is it vendored. cc @hedning

**Review by hedning — APPROVED** [review]
Looks sensible to me at least (as @jtojnar says we should do the same for gnome-desktop).

**Comment by hedning** [comment]
Ah, sorry, should've mentioned that we just merged an update to `gnome-desktop` where the thumbnailer code changed.

**Comment by layus** [comment]
@hedning This was a mess, so I rebased my changes.

**Comment by hedning** [comment]
Cheers, I'll merge after ofborg is done so we'll get this into 19.03

**Comment by hedning** [comment]
@GrahamcOfBorg build gnome3.nautilus gnome3.gnome-desktop

**Comment by hedning** [comment]
Tested nautilus and it produces pdf thumbnails. Couldn't get gnome-documents to work, but I think that's an issue with the gnome-desktop version bump (eog also fails to produce thumbnails on master now), I'll look into it.

**Comment by layus** [comment]
thanks !

**Comment by hedning** [comment]
Thanks for tracking down and fixing the issue :)

Solved the gnome-desktop problem in #56346

**Pull request merged**
