### PR TITLE
xdg-desktop-portal: 1.18.1 -> 1.18.2

### PR DESCRIPTION
**Pull request by trofi**
Changes: https://github.com/flatpak/xdg-desktop-portal/releases/tag/1.18.2

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by trofi** [comment]
Result of `nixpkgs-review pr 270085` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>fractal</li>
    <li>xdg-desktop-portal</li>
    <li>xdg-desktop-portal-gnome</li>
    <li>xdg-desktop-portal-gtk</li>
    <li>xdg-desktop-portal-xapp</li>
    <li>xdg-desktop-portal.installedTests</li>
  </ul>
</details>

**Review by jtojnar — APPROVED** [review]
Changes look okay, interesting:
- https://github.com/flatpak/xdg-desktop-portal/commit/535278dd02203be43ff7372930b017b45dbd6bfd Directory dnd support was backported.
- https://github.com/flatpak/xdg-desktop-portal/commit/b653add9bcb6a6a580a9863aae117e9376293cbc Path lookup has been tweaked.

**Comment by vcunat** [comment]
For reference, Hydra has repeatedly issues with some tests being flaky, e.g. now
```
 8/28 xdg-desktop-portal:portals / test-portals-inhibit               ERROR            2.39s   killed by signal 6 SIGABRT
>>> XDP_UNINSTALLED=1 XDG_CURRENT_DESKTOP=test XDG_DATA_DIRS=/build/source/build/tests/share G_DEBUG=gc-friendly G_TEST_SRCDIR=/build/source/tests G_TEST_BUILDDIR=/build/source/build/tests MALLOC_PERTURB_=97 /build/source/build/tests/test-portals --verbose --keep-going --tap -p /portal/inhibit

20/28 xdg-desktop-portal:portals / limited-portals-savefile           ERROR            0.93s   killed by signal 6 SIGABRT
>>> MALLOC_PERTURB_=241 XDP_UNINSTALLED=1 XDG_CURRENT_DESKTOP=limited XDG_DATA_DIRS=/build/source/build/tests/share G_DEBUG=gc-friendly G_TEST_SRCDIR=/build/source/tests G_TEST_BUILDDIR=/build/source/build/tests /build/source/build/tests/limited-portals --verbose --keep-going --tap -p /limited/savefile
```

It's a bit annoying, as it always blocks channel and moreover blocks various packages from building (and it's hard to restart them all without retrying also completely unrelated failures).

**Comment by trofi** [comment]
Looks like `inhibit` test gets unexpected callback values. I'll try to debug.

**Comment by trofi** [comment]
Having looked at the tests a bit more let's follow upstream's presubmit setup and disable known-flaky tests with `TEST_IN_CI`. Proposed the change as https://github.com/NixOS/nixpkgs/pull/272685

**Pull request merged**
