### PR TITLE
cargo-llvm-cov: init at 0.5.0

### PR DESCRIPTION
**Pull request by CobaltCause**
###### Description of changes

This packages [cargo-llvm-cov](https://github.com/taiki-e/cargo-llvm-cov), a tool for generating code coverage reports using built-in features of recent Rust toolchains.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by winterqt** [comment]
Thanks for the PR, but this is a dupe of #185183.

I'm going to apply my suggestions and merge that one sometime in the next day, since the author has not responded in a month.

I'd appreciate it if you could go over that PR if you have any suggestions/test it, if you'd like :)

Thanks again, and I hope you contribute more to Nixpkgs in the future!

**Comment by CobaltCause** [comment]
Oh lol I should've checked for that. They also appear to have gotten the tests working while I just ignored them, which is definitely better. Thanks!

**Comment by winterqt** [comment]
> They also appear to have gotten the tests working while I just ignored them

I believe I just used a less verbose method of disabling just those broken tests there.

**Comment by CobaltCause** [comment]
If you re-open this PR, I actually just reworked it in a way where all the tests run and pass properly: https://github.com/CobaltCause/nixpkgs/commit/14157246437a3fe6aafca7189f3db7df2e0263b8

**Comment by CobaltCause** [comment]
Note: refactoring this to use `fetchCrate` instead of `fetchFromGithub` causes the tests to stop working.

**Comment by winterqt** [comment]
Yes, this is because Cargo skips the fixture directories when packing for publishing, since it thinks they're unrelated crates.

I'd love to reopen this, but...
image

**Comment by CobaltCause** [comment]
Oh, yeah I did force-push to fix the tests. Should I re-open as a new PR?

**Comment by winterqt** [comment]
Go for it -- there's one change I want to try to not have to add the Cargo.lock, but other than that it's good to go :)

**Comment by CobaltCause** [comment]
Done: https://github.com/NixOS/nixpkgs/pull/197478

**Pull request closed without merging**
