### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
Tracking regressions for pythonRecompileBytecodeHook in https://github.com/NixOS/nixpkgs/issues/90516. Might have to revert.

**Comment by jonringer** [comment]
> Tracking regressions for pythonRecompileBytecodeHook in #90516. Might have to revert.

If a lot of the pain is around python2, then I say we don't revert. Python2 is being phased out, and I think having deterministic builds for python is an admirable thing.

**Comment by Mic92** [comment]
I looking forward to see this merged soon. Many things are broken in master.

**Comment by FRidh** [comment]
Pretty sure many other things will be broken once this lands ;)

**Comment by Mic92** [comment]
However tail dependencies are easier to fix since. Currently I have to rebuild firefox...

**Comment by flokli** [comment]
Yeah, I also heard [some](https://github.com/NixOS/nixpkgs/pull/91047) [reports](https://github.com/NixOS/nixpkgs/pull/91043) about boto3 and botocore being broken in master. Looking forward to see this merged aswell.

**Comment by FRidh** [comment]
Half the packages are still building but there aren't any significant regressions I could see except for the expected Python 2 breakage.

**Pull request merged**
