### PR TITLE
nixos/dhcp: fix permissions of statedir

### PR DESCRIPTION
**Pull request by qknight**
fix for https://github.com/NixOS/nixpkgs/issues/38424

(not tested)

### CODE REVIEW

**Comment by Mic92** [comment]
Please also adjust commit message accordingly or use the squash button to change the message.

**Comment by qknight** [comment]
@mic92 what would be an 'correct' or 'good' commit message?

**Comment by Mic92** [comment]
I proposed one in the title.

**Comment by qknight** [comment]
@Mic92 i'd like to have this in 18.03 also, can you tell me the documentation and processes to do that?

**Comment by abbradar** [comment]
@qknight Before backporting could you address https://github.com/NixOS/nixpkgs/commit/7be79f22f2c5876af26466902862f323c21e7209#commitcomment-28415075?

**Pull request merged**
