### PR TITLE
openldap: load client config from /etc, not the nix store

### LINKED ISSUE #181937: Openldap clients ignore system-wide LDAP client configuraiton in /etc/ldap.conf
### Describe the bug
The system-wide LDAP client configuration in `/etc/ldap.conf` is ignored by Openldap client programs.

### Steps To Reproduce
1. Put settings into `/etc/ldap.conf` via `config.settings.ldap.*`
2. Run `ldapsearch` or any other Openldap client

### Expected behavior
Openldap client programs should obey the system-wide configuration file in `/etc/ldap.conf`.

### Additional context
strace shows it's reading the example configuration from the package instead:

```
$ strace -e file ldapsearch
[...]
openat(AT_FDCWD, "/nix/store/j8mm1wgsx4vmxaxbf6ximq59ry5qj7yl-openldap-2.6.2/etc/ldap.conf", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0444, st_size=247, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/home/dan/ldaprc", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/dan/.ldaprc", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "ldaprc", O_RDONLY)    = -1 ENOENT (No such file or directory)
[...]
```

Since commit 39ef6322b5b9dcddaee2a1caf7b07c09747784a2 the openldap package no longer passes `--sysconfdir=/etc` to configure, it only passes `sysconfdir=${placeholder "out"}/etc` to make instead.

### Notify maintainers
@ajs124 @das_j @hexa

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 5.15.32, NixOS, 22.05 (Quokka), 22.05.git.c88aa8fd317M`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `""`
 - nixpkgs: `/home/dan/nixpkgs`
```

### PR DESCRIPTION
**Pull request by danc86**
###### Description of changes

Fixes #181937 by passing `sysconfdir=` twice.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
I assume you found that out emperically? Because I don't find these flags intuitive at all. :smile:

**Comment by danc86** [comment]
I've worked on (and been responsible for) enough automake messes throughout my life that I was able to guess at this "solution" :upside_down_face:

**Comment by danc86** [comment]
Well, I did run `nixpkgs-review`. It spent ~24 hours trying to build 2058 packages, of which 1331 succeeded, 44 failed, and 683 skipped. I don't think there's much value in pasting the full results here.

I quickly skimmed the failures and they all look like unrelated pre-existing breakages. I was a little concerned about `_389-ds-base` which failed with:

```
/nix/store/ld11fgq92p6bci267ywy55j9825sbi66-binutils-2.38/bin/ld: cannot find -lldap_r: No such file or directory
```

but that problem reproduces on the `master` branch too.

**Comment by mweinelt** [comment]
Sorry, merged then reverted, this should've gone into staging, not master, given that it causes alot of rebuilds.

**Review by kwohlfahrt — COMMENTED** [review]
I'm late to the party, but agree the change looks good - I guess the PR needs to be reopened now to fix the correct base branch branch?

**Comment by mweinelt** [comment]
I'm currently doing the rebase locally and moving a few things around due to the test changes I just merged. Stay tuned.

**Comment by mweinelt** [comment]
b30534eb02796423cec9fbda8f7aea535c932e3e

**Comment by danc86** [comment]
> Sorry, merged then reverted, this should've gone into staging, not master, given that it causes alot of rebuilds.

Oops, sorry about that. I'm new to Nixos and didn't know about the staging branch.

**Pull request merged**
