### PR TITLE
ell: 0.41 -> 0.42, iwd: 1.15 -> 1.16

### PR DESCRIPTION
**Pull request by amaxine**
###### Motivation for this change
https://git.kernel.org/pub/scm/libs/ell/ell.git/tree/ChangeLog?h=0.42
```
ver 0.42:
	Add support for constant time security functions.
	Add support for manipulating DHCP leases.
```

https://git.kernel.org/pub/scm/network/wireless/iwd.git/tree/ChangeLog?h=1.16
```
ver 1.16:
	Fix issue with writing provisioning files with a passphrase.
	Add support for Authenticator & Supplicant RSN Extension elements.
	Add support for handling Transition Disable info.
	Add support for SAE Hash-to-Element feature.
```

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by maxeaubrey** [comment]
`bluez` and `ofono` are also fine with the `ell` bump.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 132875` at 142c599d run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages marked as broken and skipped:</summary>
  <ul>
    <li>googleearth-pro</li>
    <li>linuxPackages_hardkernel_4_14.xpadneo</li>
    <li>linuxPackages_hardkernel_latest.xpadneo</li>
    <li>odpdown</li>
    <li>termplay</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/88b9a82923cdb64199b8a7313d39048d">gnokii</a></li>
  </ul>
</details>
<details>
  <summary>721 packages skipped due to time constraints:</summary>
  <ul>
    <li>adapta-gtk-theme</li>
    <li>adoptopenjdk-icedtea-web</li>
    <li>alfis</li>
    <li>almanah</li>
    <li>anydesk</li>
    <li>apostrophe</li>
    <li>appgate-sdp</li>
    <li>aravis</li>
    <li>arc-theme</li>
    <li>areca</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>81 packages built successfully:</summary>
  <ul>
    <li>blueman</li>
    <li>bluez (bluez5)</li>
    <li>bluez-alsa</li>
    <li>brltty</li>
    <li>bt-fw-converter</li>
    <li>coretoppings</li>
    <li>cwiid</li>
    <li>ell</li>
    <li>gammu</li>
    <li>geoclue2</li>
    <li>gimx</li>
    <li>glib-networking (gnome.glib-networking ,gnome.glib_networking)</li>
    <li>gnome.gnome-settings-daemon (gnome.gnome_settings_daemon)</li>
    <li>gnome.mutter334 (pantheon.mutter)</li>
    <li>networkmanagerapplet (gnome.networkmanagerapplet)</li>
    <li>gst_all_1.gst-plugins-bad</li>
    <li>haskellPackages.hcwiid</li>
    <li>iwd</li>
    <li>libcprime</li>
    <li>libnma</li>
    <li>libproxy</li>
    <li>qt5.qtconnectivity (libsForQt5.qtconnectivity ,qt515.qtconnectivity)</li>
    <li>qt514.qtconnectivity (libsForQt514.qtconnectivity)</li>
    <li>linuxPackages.xpadneo (linuxPackages_5_10.xpadneo)</li>
    <li>linuxPackages_4_14.xpadneo</li>
    <li>linuxPackages_4_19.xpadneo</li>
    <li>linuxPackages_4_4.xpadneo</li>
    <li>linuxPackages_4_9.xpadneo</li>
    <li>linuxPackages_5_12.xpadneo</li>
    <li>linuxPackages_5_13.xpadneo (linuxPackages_latest.xpadneo)</li>
    <li>linuxPackages_5_4.xpadneo</li>
    <li>linuxPackages_hardened.xpadneo</li>
    <li>linuxPackages_latest_hardened.xpadneo</li>
    <li>linuxPackages_lqx.xpadneo</li>
    <li>linuxPackages_testing_bcachefs.xpadneo</li>
    <li>linuxPackages_xanmod.xpadneo</li>
    <li>linuxPackages_zen.xpadneo</li>
    <li>modem-manager-gui</li>
    <li>networkmanager</li>
    <li>obex_data_server</li>
    <li>obexd</li>
    <li>obexfs</li>
    <li>obexftp</li>
    <li>ofono</li>
    <li>openobex</li>
    <li>pantheon.elementary-dpms-helper</li>
    <li>pantheon.elementary-settings-daemon</li>
    <li>pantheon.gala</li>
    <li>pantheon.switchboard-plug-bluetooth</li>
    <li>pantheon.switchboard-plug-mouse-touchpad</li>
    <li>pantheon.switchboard-plug-network</li>
    <li>pantheon.switchboard-plug-pantheon-shell</li>
    <li>pantheon.switchboard-plug-power</li>
    <li>pantheon.switchboard-plug-sound</li>
    <li>pantheon.wingpanel</li>
    <li>pantheon.wingpanel-indicator-bluetooth</li>
    <li>pantheon.wingpanel-indicator-keyboard</li>
    <li>pantheon.wingpanel-indicator-network</li>
    <li>pantheon.wingpanel-indicator-nightlight</li>
    <li>pantheon.wingpanel-indicator-notifications</li>
    <li>pantheon.wingpanel-indicator-power</li>
    <li>pantheon.wingpanel-indicator-session</li>
    <li>pantheon.wingpanel-indicator-sound</li>
    <li>pipewire</li>
    <li>pulseaudio</li>
    <li>pulseaudio-modules-bt</li>
    <li>pulseaudioFull</li>
    <li>python38Packages.bleak</li>
    <li>python38Packages.ds4drv</li>
    <li>python38Packages.pybluez</li>
    <li>python39Packages.bleak</li>
    <li>python39Packages.ds4drv</li>
    <li>python39Packages.pybluez</li>
    <li>python39Packages.python-dbusmock</li>
    <li>redfang</li>
    <li>redshift</li>
    <li>sc-controller</li>
    <li>ubertooth</li>
    <li>urserver</li>
    <li>wiiuse</li>
    <li>xwiimote</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by maxeaubrey** [comment]
`gnokii` is marked as broken already.

I guess the consequences of switch `bluez` to external ell rear their head here :grimacing: :sweat_smile: 
As there's nothing urgent about this, I guess it'd be better if it goes through `staging` (even if we usually put `bluez` changes directly thru to the main branch).

**Comment by maxeaubrey** [comment]
I'm short on time lately, finally rebased on staging.

**Pull request merged**
