### PR TITLE
vimPlugins.tssorter-nvim: init at 2024-08-16

### PR DESCRIPTION
**Pull request by poperigby**
## Description of changes

Added https://github.com/mtrajano/tssorter.nvim

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by PerchunPak — CHANGES_REQUESTED** [review]
Could you please add an entry to `generated.nix`? Just run `nix-shell -p vimPluginsUpdater --run 'vim-plugins-updater -n'` and make sure to include only the changes related to this plugin. Thanks!

**Comment by poperigby** [comment]
@PerchunPak there we go. I hope I didn't screw up the commit history.

**Comment by PerchunPak** [comment]
Oops, forgot about this. Though the commit message should be `vimPlugins.tssorter-nvim: init at 2024-08-16`. And this plugin depends on treesitter, specify it please like this https://github.com/NixOS/nixpkgs/blob/bd4f00ac7fa6b641777b5a7fb08911c456b4ed01/pkgs/applications/editors/vim/plugins/overrides.nix#L197-L199

Result of `nixpkgs-review pr 338321` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>vimPlugins.tssorter-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

Result of `nixpkgs-review pr 338321` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>vimPlugins.tssorter-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Comment by poperigby** [comment]
@PerchunPak got it. Done.

**Review by PerchunPak — APPROVED** [review]
LGTM, though cannot test it rn

CC @GaetanLepage

**Review by GaetanLepage — APPROVED** [review]
LGTM

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 338321` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>vimPlugins.tssorter-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Pull request merged**
