### PR TITLE
mesa: 23.1.7 -> 23.3.0, bump patches

### PR DESCRIPTION
**Pull request by colemickens**
## Description of changes

* Draft PR
* bumps mesa from stable to `23.3.0`
* my system is currently rebuilding with this applied (testing will be with #256154 and #259989 applied)

Maybe useful for anyone who wants to test, since we haven't merged #258017 and I don't know what the status of the 23.2 branch is for mesa. There's been no commits to the 23.2 branch since 23.2.1 was cut and released.

EDIT: To be clear, this is left as a draft, and even if it weren't is not meant to be merged as is.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
I don't understand what's happening upstream around 23.2.  There's been [no activity](https://gitlab.freedesktop.org/mesa/mesa/-/branches/active) in the branch for over five weeks now (only `staging/23.2`) and even 23.1 has newer changes and release than that.  No mention [in announcements](https://lists.freedesktop.org/archives/mesa-announce/), not even a proper announcement for _any_ non-RC 23.2 version.

For now it seems that we'll keep NixOS 23.11 on mesa-23.1, as I didn't notice anything very important in 23.2.

**Comment by tormeh** [comment]
> didn't notice anything very important

Well, according to Phoronix, ray tracing is turned on by default on RADV: https://www.phoronix.com/news/Mesa-23.2.1-Released

**Comment by vcunat** [comment]
I think I did see that, but importance is just subjective.

**Comment by pearsche** [comment]
it also fixes this https://gitlab.freedesktop.org/mesa/mesa/-/issues/8853

**Comment by whazor** [comment]
I am looking forward to AV1 video encoding on AMD graphic cards, which is added on Mesa 23.3: https://www.phoronix.com/news/AMD-Mesa-AV1-VA-API-Encode

**Comment by romatthe** [comment]
I agree that the inactivity around 23.2 is rather strange (as I was expecting at least a 23.2.2 relatively soon after the first stable 23.2 release), it would be a bit of a shame if we won't be able to land Mesa 23.2 in NixOS 23.11, since that's my only opportunity to get a new mesa release for the next 6 months. While I don't have any specific features from 23.2 that I need, it's always nice to get the general improvements, no matter how small.

I assume that even if Mesa 23.3.0-rc4 (which should release this Wednesday) turns out to be the final release of this series, the window to get it merged for NixOS 23.11 will be too small?

**Comment by vcunat** [comment]
We normally don't even use .0 releases in nixpkgs, so who knows when 23.3.1 comes.  And the window for "breaking changes" (which this probably is) was closed already.

**Comment by jansol** [comment]
[23.3.1 is out!](https://lists.freedesktop.org/archives/mesa-dev/2023-December/226085.html)

**Comment by K900** [comment]
Good. I'll get it tomorrow if @colemickens doesn't.

**Comment by Atemu** [comment]
https://github.com/NixOS/nixpkgs/pull/274177

**Pull request closed without merging**
