### PR TITLE
openai-whisper: 20230918 -> 20231117

### PR DESCRIPTION
**Pull request by mweinelt**
https://github.com/openai/whisper/blob/v20231117/CHANGELOG.md

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Tungsten842** [comment]
I believe that the entire postPatch can be removed.
Tiktoken as been unpinned in [v20231105](https://github.com/openai/whisper/blob/main/CHANGELOG.md#v20231105)
Openai-triton is always propagated and can also be removed from the package: https://github.com/NixOS/nixpkgs/blob/c757e9bd77b16ca2e03c89bf8bc9ecb28e0c06ad/pkgs/development/python-modules/torch/default.nix#L380-L381

**Comment by mweinelt** [comment]
@MayNiklas I removed the local cudaSupport flag in favor of the nixpkgs-wide one. I hope that's fine.

**Comment by MayNiklas** [comment]
> @MayNiklas I removed the local cudaSupport flag in favor of the nixpkgs-wide one, that its dependencies rely on. I hope that's fine.

I personally benefit from individual CUDA options:
When working on my whisper project, by only enabling CUDA for the whisper library instead of all of nixpkgs, I was able to reduce the packages closure size from 18GB to around half the size without hurting it's performance.

That being said: If you think it better fits the nix ecosystem - great!
You are way deeper into the details than I am so I totally trust on that!
Especially with the simplified state of the whisper package, simply overriding torch will also work so I have to agree: we don't NEED the CUDA option 👍

**Comment by mweinelt** [comment]
The benefit here is that we also don't need special handling for `rocmSupport` in every package, so I think this is ultimately benefitial.

**Comment by MayNiklas** [comment]
I'm going to check if everything still works with CUDA in my lunch break!
You're right: this is a benefit!

**Review by MayNiklas — APPROVED** [review]
Successfully tested with `nixpkgs.config.cudaSupport` set to true. Utilized my GPU as expected. Thanks for the update! 👍

**Pull request merged**
