### PR TITLE
gocode: remove

### PR DESCRIPTION
**Pull request by katexochen**
## Description of changes

_The original removal PR (https://github.com/NixOS/nixpkgs/pull/276887) was reverted on master in (https://github.com/NixOS/nixpkgs/pull/279324), as it missed some references and the fixup would cause a mass rebuild on master (https://github.com/NixOS/nixpkgs/pull/279181)._

_This PR contains both the orignial removal commit and the fixups._

---

Project has been in maintenance mode sinde 2019 and was archived in 2021: https://github.com/mdempsky/gocode

For `vim-go`, gocode support was removed in in 2020, as documented in the [changelog](https://github.com/fatih/vim-go/blob/e2e7ad7cb03049896bafda28481f252a2aa8d5bb/CHANGELOG.md?plain=1#L447-L448).

For `ycmd`, gocode was removed, too, see https://github.com/ycm-core/ycmd/blob/b34008abd3b51992a7b6342a4e4e79740417e63c/build.py#L547-L548

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by kirillrdy** [comment]
may i ask, what is the issue caused by removal of gocode ? I think its unlikely anyone still using gocode in 2024 ( famous last words )

**Comment by katexochen** [comment]
@kirillrdy there is no issue removing it. I just overlooked 2 references of it in the removal PR and now these fixups are causing mass rebuilds.

**Comment by katexochen** [comment]
Original PR was reverted on master, so we need to wait until the revert is part of staging, then I can rebase and cherry-pick the original commit into this PR.

**Comment by katexochen** [comment]
Original commit cherry-picked, PR description updated, ready for review. :heavy_check_mark:

**Review by fabianhjr — APPROVED** [review]

**Comment by rjpcasalino** [comment]
seems like https://github.com/fatih/vim-go uses `gocode` and I got a build error as a result

**Comment by katexochen** [comment]
@rjpcasalino what build error do you get? I think the base of this PR is broken, I've cherry-picked the changes on top of master to build them. Or test with nixpkgs-review:

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vimPlugins.vim-go</li>
    <li>ycmd</li>
  </ul>
</details>

**Comment by rjpcasalino** [comment]
it might be a strange issue with my setup but I'm using home manager to install vim-go and i get -
` error: 'gocode' has been removed as the upstream project was archived. 'gopls' is suggested as replacement` which makes little sense to me since vim-go is up-to-date in nixpkgs.

**Comment by rjpcasalino** [comment]
ah, I think I see why https://github.com/NixOS/nixpkgs/blob/519c93eda20a7c361e6159d853bf33b1e6236141/pkgs/applications/editors/vim/plugins/overrides.nix#L1516

**Comment by katexochen** [comment]
You seem to be using the _unstable_ channel, which might be currently broken due to the pre story of this PR that is described at the beginning of the PR description. Please be patient, this has already been reverted on master, you can [track it on the PR tracker](https://nixpk.gs/pr-tracker.html?pr=276887).

Other than that, your issue doesn't seem to be related to this PR (which is still open and not in unstable).

**Comment by rjpcasalino** [comment]
right, sorry should have commented on the merged PR. No worries. Thanks for your work with this

**Comment by fabianhjr** [comment]
Seems like staging had unrelated breakage.

`       error: evaluation aborted with the following error message: 'lib.customisation.callPackageWith: Function called without required argument "filemagic" at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/ofborg-evaluator-4/pkgs/development/python-modules/jira/default.nix:5`

Could you rebase and if it evals will merge

**Review by rjpcasalino — APPROVED** [review]

**Comment by rjpcasalino** [comment]
@katexochen just wanted to thank you again for this work. My config builds wonderfully again.

**Pull request merged**
