### PR TITLE
prometheus: bundle the webui assets and build the new React UI

### LINKED ISSUE #74844: prometheus: error reading base template: open templates/_base.html: no such file or directory
**Describe the bug**
prometheus doesn't seem to find some template file.

**To Reproduce**
1. use `services.prometheus.enable = true;`
2. run `curl localhost:9090/graph`

get
`error reading base template: open templates/_base.html: no such file or directory`

**Expected behavior**
no error

**Screenshots**

**Additional context**

**Metadata**
❯ nix run nixpkgs.nix-info -c nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.87, NixOS, 20.03pre203917.0106804da3f (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(bbigras): `"home-manager"`
 - channels(root): `"nixos-20.03pre203917.0106804da3f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

cc @benley @fpletz @globin @willibutz

### PR DESCRIPTION
**Pull request by delroth**
###### Motivation for this change

v2.14 introduced a new experimental React UI and changed how web assets
are bundled with Prometheus. A separate pre-build command is required to
generate an asset bundle that gets statically linked into the Prometheus
binary.

Fixes #74844.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by grahamc** [comment]
I'm not keen on adding 12,000 lines of code for an experimental UI.

**Comment by delroth** [comment]
Not yet, but I expect it will be within a few versions, it's intended to be a full replacement. Some light patching will also be required to have the assets bundling work without building the new UI.

The 12K lines of code is a general problem with JavaScript and Nix as far as I can tell. Many of the URLs in there are actually already cached on cache.nixos.org, so I expect we have a few overlapping gigantic lock files in nixpkgs.

**Comment by globin** [comment]
I think the solution is fine, I'd propose merging, we don't have any better solution until recursive nix etc.

**Comment by bjornfor** [comment]
-1 on adding 550 KiB of nix expressions for one package. Isn't there something else that can be done?

**Comment by yorickvP** [comment]
For vault, we package the upstream binary of the WebUI instead. Alternatively, we could use one of those tools to parse the lockfile, but that will take IFD.

**Pull request merged**
