### PR TITLE
curaLulzbot: 3.6.18 -> 3.6.21

### PR DESCRIPTION
**Pull request by charles-dyfis-net**
###### Motivation for this change

Updates numerous material profiles for recent machines (TAZ Pro, TAZ Workhorse), and fixes some other minor bugs.  No changes to slicer engine, firmware, or other dependencies.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

(Author is maintainer).

### CODE REVIEW

**Comment by charles-dyfis-net** [comment]
Please consider this PR on-hold -- it looks like the `QT_PLUGIN_PATH` change may have triggered a regression.

**Review by jonringer — COMMENTED** [review]
it's double wrapped :( 
```
$ ls -a ./results/curaLulzbot/bin/
..cura-lulzbot-wrapped-wrapped  .cura-lulzbot-wrapped  cura-lulzbot
```

**Comment by charles-dyfis-net** [comment]
When built against master, but *not* against release-19.03, we're unable to find QtQuick.Controls (and consequently have some UI elements unable to render once running), even when using `mkDerivationWith` / `wrapQtApp` / etc (and having `qtquickcontrols2` in our `buildInputs`):

```
2019-09-25 22:32:54,855 - WARNING - [(140517336824832)-MainThread] UM.Qt.QtApplication.__onQmlWarning [274]: file:///nix/store/rb83hsh2qfnbp156cljrqrg8lchndh51-cura-lulzbot-3.6.20/share/cura/resources/qml/Sidebar.qml:5:1: module "QtQuick.Controls" version 2.1 is not installed
```

I'm going to call it an evening for now and come back to this later -- but I could see needing to ask @ttuegel for a pointer.

**Comment by charles-dyfis-net** [comment]
...okay, the nice thing about maintaining a fork of an upstream program that's *also* in nixpkgs is that there's a place to look for hints. :)

As of de36bdc26949053bedea5e92280834b8bb775ce8, we're still double-wrapped (like upstream is AFAIK), but the software *actually works*.

**Comment by charles-dyfis-net** [comment]
This has moved from 3.6.20 to 3.6.21; notably, upstream has merged proper support for Qt 5.12, so we're able to drop our patch.

(There's also support for the Lulzbot Bio, for anyone having one of those prototypes / beta units).

**Comment by gebner** [comment]
@GrahamcOfBorg build curaLulzbot

**Pull request merged**
