### PR TITLE
kernel: remove 4.7

### LINKED ISSUE #19822: Phase out 4.7.x kernel
The 4.7.x kernel series has been EOL'd. How do we generally phase out kernels?
Just remove them and set an alias in `all-packages` that spits out an error message?

### PR DESCRIPTION
**Pull request by NeQuissimus**
Fixes #19822 
###### Motivation for this change

Linux kernel 4.7 has been EOL'd.

Since we always keep the set of upstream maintained kernels, this one needs to go.
Note that `grsecurity` still pulls `4.7.10` because those folks have yet to release a `4.8.x` patch.
Since we generally keep `grsecurity` up-to-date, it will eventually switch to 4.8 I presume.
Still pinging @joachifm to make him aware.

### CODE REVIEW

**Comment by grahamc** [comment]
Needs cleanup? or has cleanup?

:+1:

**Comment by NeQuissimus** [comment]
In a way both :) But you are right, I meant to do `has: clean-up`

**Comment by grahamc** [comment]
I'm wondering if we should be leaving an EOL'd kernel in 16.09. I don't want to drop it, but I doubt we're going to maintain it.

**Comment by shlevy** [comment]
I've long thought we should just stick to LTS and latest stable, on master and the release branches. It seems to be begging for trouble to have known unsupported kernels in our stable branch. @domenkozar ?

**Comment by vcunat** [comment]
I think we should cherry-pick this to 16.09, unless there's some specific reason for another way.

**Comment by vcunat** [comment]
When people explicitly override kernel branch, IMHO they should count on it disappearing when EOLd. (Upstream [clearly announces](https://www.kernel.org/category/releases.html) minimal support time for each branch.)

**Comment by NeQuissimus** [comment]
I'll cherry-pick, I agree.

**Comment by NeQuissimus** [comment]
27b37f1b9532170a043468d38eaf4bf1dbf97e09

**Pull request merged**
