### PR TITLE
systemd-boot: Revert boot counting again

### PR DESCRIPTION
**Pull request by ElvishJerricco**
## Description of changes

Unfortunately, with the specialisation-related regression caused by boot counting, and fixes like #334473 being generally hasty and unsatisfactory, the most effective way to unblock the unstable channel is to simply revert boot counting.

This was made a little tricky, as there were [three](https://github.com/NixOS/nixpkgs/pull/253260), [other](https://github.com/NixOS/nixpkgs/pull/319422), [PRs](https://github.com/NixOS/nixpkgs/pull/201202) that were merged for systemd-boot this week, which interfered with the revert. I believe I've preserved those PRs correctly, and all systemd-boot tests seem to pass, including the `specialisation` one on aarch64 (it's the only one testing the `devicetree` change).

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by emilazy — APPROVED** [review]
Looks reasonable at a skim. I hope we can get this back ASAP once the dust has settled and the channels are moving again. I will check tests on `aarch64-linux`.

**Comment by Mic92** [comment]
I don't have an intermediate use case for boot counting, so I probably won't spend time on getting it to work. This was only happening on aarch64, right?

**Comment by emilazy** [comment]
No, eval broke for the entire channel.

**Comment by ElvishJerricco** [comment]
And the specialisation bug was platform independent

**Pull request merged**
