### PR TITLE
bruno: 1.34.0 -> 1.34.2

### PR DESCRIPTION
**Pull request by gepbird**
Releases:
- https://github.com/usebruno/bruno/releases/tag/v1.34.1
- https://github.com/usebruno/bruno/releases/tag/v1.34.2

`phantomjs` was removed in https://github.com/usebruno/bruno/commit/753a576c3c86b2bf603d20dd30388c09aede17e6.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by gepbird** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 354103`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>bruno</li>
  </ul>
</details>

**Comment by gepbird** [comment]
In https://github.com/NixOS/nixpkgs/pull/339769 I found out bruno removed canvas (the unused dependency that caused issues on darwin), but it got added back again in https://github.com/usebruno/bruno/commit/cc8f3de8b.

**Comment by khaneliman** [comment]
@gepbird Were you wanting to get these in before the other PR?

**Comment by gepbird** [comment]
> @gepbird Were you wanting to get these in before the other PR?

@khaneliman

We can either go with only https://github.com/NixOS/nixpkgs/pull/354339 created by @lucasew. We're waiting for his response to reviews.

Or go with this and https://github.com/NixOS/nixpkgs/pull/354111 (in this order) created by me. If this is the case let me know and I'll update and undraft https://github.com/NixOS/nixpkgs/pull/354111.

I'm happy with either :)

**Pull request merged**
