### PR TITLE
schismtracker: 20220506 -> 20230906

### PR DESCRIPTION
**Pull request by faithanalog**
## Description of changes

Since the last version bump, schismtracker has migrated from SDL1 to SDL2. This is a change that improves audio options, video output quality, and allows mouse/keyboard capture under wayland. There's also various other fixes and improvements listed under https://github.com/schismtracker/schismtracker/releases , and an out-of-bounds memory access was fixed in some common rendering code that isn't mentioned in the release notes.

~~I don't have any macOS hardware to test darwin on, but schismtracker has working macOS CI, so I'm reasonably confident it'll work there too.~~ lol, lmao. were it so easy

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by LunNova** [comment]
Result of `nixpkgs-review pr 254476` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>schismtracker</li>
  </ul>
</details>

**Comment by faithanalog** [comment]
ah looks like the darwin build does in fact fail. i do not own a mac and do not really know how to fix this.

**Review by nagy — COMMENTED** [review]
Can you remove the word "update" from your commit message and PR title?

Also I would say the description in the PR is good. it deserves to be in the commit message as well.

**Comment by iliana** [comment]
I was able to fix the aarch64-darwin build (not tested on x86_64-darwin as I don't have hardware) with this patch:

<details><summary>[PATCH] schismtracker: fix darwin build</summary>

```diff
From 5e587172da2fed6a1d7387d0c94be9c2bcd32ae4 Mon Sep 17 00:00:00 2001
From: iliana etaoin <iliana@buttslol.net>
Date: Mon, 11 Sep 2023 00:46:44 -0700
Subject: [PATCH] schismtracker: fix darwin build

---
 pkgs/applications/audio/schismtracker/default.nix | 9 ++++++++-
 pkgs/top-level/all-packages.nix                   | 4 +++-
 2 files changed, 11 insertions(+), 2 deletions(-)

diff --git a/pkgs/applications/audio/schismtracker/default.nix b/pkgs/applications/audio/schismtracker/default.nix
index 268603e5d45..07ff60e992a 100644
--- a/pkgs/applications/audio/schismtracker/default.nix
+++ b/pkgs/applications/audio/schismtracker/default.nix
@@ -6,6 +6,7 @@
 , python3
 , SDL2
 , libXext
+, Cocoa
 }:
 
 stdenv.mkDerivation rec {
@@ -24,10 +25,16 @@ stdenv.mkDerivation rec {
 
   nativeBuildInputs = [ autoreconfHook python3 ];
 
-  buildInputs = [ SDL2 ] ++ lib.optionals stdenv.isLinux [ alsa-lib libXext ];
+  buildInputs = [ SDL2 ]
+    ++ lib.optionals stdenv.isLinux [ alsa-lib libXext ]
+    ++ lib.optionals stdenv.isDarwin [ Cocoa ];
 
   enableParallelBuilding = true;
 
+  preConfigure = lib.optionalString stdenv.isDarwin ''
+    sed s,lSDL2main,lSDL2, -i configure.ac
+  '';
+
   meta = with lib; {
     description = "Music tracker application, free reimplementation of Impulse Tracker";
     homepage = "http://schismtracker.org/";
diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
index dd8e187dba4..5b51c29882c 100644
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -30726,7 +30726,9 @@ with pkgs;
 
   ptcollab = libsForQt5.callPackage ../applications/audio/ptcollab { };
 
-  schismtracker = callPackage ../applications/audio/schismtracker { };
+  schismtracker = callPackage ../applications/audio/schismtracker {
+    inherit (darwin.apple_sdk.frameworks) Cocoa;
+  };
 
   jnetmap = callPackage ../applications/networking/jnetmap { };
 
```

</details>

**Comment by OPNA2608** [comment]
Suggested Darwin fix LGTM in principle, except `preConfigure` should use `substituteInPlace` instead of `sed`:
```nix
  # Our Darwin SDL2 doesn't have a SDL2main to link against
  preConfigure = lib.optionalString stdenv.isDarwin ''
    substituteInPlace configure.ac \
      --replace '-lSDL2main' '-lSDL2'
  '';
```

**Review by nagy — APPROVED** [review]

**Pull request merged**
