### PR TITLE
espanso: from 2.1.8 -> 2.2.1

### PR DESCRIPTION
**Pull request by raph-rc**
Motivation: bump version, 2.2.1 fixes bug that prevents the service from running on wayland.
Release notes: https://github.com/espanso/espanso/releases/tag/v2.2.1

## Description of changes

Update espanso from version 2.1.8 to 2.2.1. Changed version and sha256 hash.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by raphaelchristin** [comment]
Hey all, I am trying to bump the version of espanso so that it works on wayland. Version 2.2.1 seems to fix the issues outlined [here](https://www.reddit.com/r/NixOS/comments/1974sfo/espanso_wayland_anyone_doing_this/). However, it seems that the `cargo.lock` file is out of date and therefore I cannot run the tests using `nix-build --attr pkgs.espanso.passthru.tests`. I get the following error: 

```
---
>  "xml-rs 0.8.3",
3511c3481
< version = "0.8.8"
---
> version = "0.8.3"
3513c3483
< checksum = "4f20f14e2bd1fef6ec891d50dbb37c7290a0568a6bbd9020bf62010d02b6f80e"
---
> checksum = "b07db065a5cf61a7e4ba64f29e67db906fb1787316516c4e6e5ff0fea1efcd8a"

ERROR: cargoHash or cargoSha256 is out of date

Cargo.lock is not the same in /build/cargo-vendor-dir

To fix the issue:
1. Set cargoHash/cargoSha256 to an empty string: `cargoHash = "";`
2. Build the derivation and wait for it to fail with a hash mismatch
3. Copy the "got: sha256-..." value back into the cargoHash field
   You should have: cargoHash = "sha256-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=";

error: builder for '/nix/store/yqwjx6wjxx7w6lixplj2swgrisxws9vv-espanso-2.2.1.drv' failed with exit code 1;
       last 10 log lines:
       > ERROR: cargoHash or cargoSha256 is out of date
       >
       > Cargo.lock is not the same in /build/cargo-vendor-dir
       >
       > To fix the issue:
       > 1. Set cargoHash/cargoSha256 to an empty string: `cargoHash = "";`
       > 2. Build the derivation and wait for it to fail with a hash mismatch
       > 3. Copy the "got: sha256-..." value back into the cargoHash field
       >    You should have: cargoHash = "sha256-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=";
       >
       For full logs, run 'nix log /nix/store/yqwjx6wjxx7w6lixplj2swgrisxws9vv-espanso-2.2.1.drv'.
error: 1 dependencies of derivation '/nix/store/7rdff2ff4kvy0y1ni4bfdifswf9346py-espanso-2.2.1-test-version.drv' failed to build
```

I do not know how to update the `cargo.lock` file properly for a nix expression. I also could not find any resources on the internet or the manual. Some help in that regard/links to relevant documentation would be highly appreciated. Thanks!!

**Comment by raphaelchristin** [comment]
Should I just take the `Cargo.lock` from the release source code? That feels like a janky fix but if that is the way I will happily do that.

**Comment by pyrox0** [comment]
Can you please remove all the formatting changes? They're unrelated to this PR and don't need to be changed. And yes, copying the Cargo.lock from the original repo should work, just make sure you're getting it from the correct commit.

**Comment by raphaelchristin** [comment]
Hey thanks for the info! I will happily remove the formatting changes later today, did not notice the autoformat was on. Sorry about that. I will also grab the `Cargo.lock` from the release and add that. Should I squash the commits for a better history?

**Comment by pyrox0** [comment]
You can squash, it's not required though, so I'll leave that decision to you.

**Comment by raphaelchristin** [comment]
Alright so I removed the formatting changes and updated the Cargo.lock with another commit but now I run into this error when attempting `nix-build --attr pkgs.espanso.passthru.tests`: 

```
error: cannot evaluate a function that has an argument without a value ('lib')
       Nix attempted to evaluate a function as a top level expression; in
       this case it must have its arguments supplied either by default
       values, or passed explicitly with '--arg' or '--argstr'. See
       https://nixos.org/manual/nix/stable/language/constructs.html#functions.

       at /home/raphchr/nixpkgs/pkgs/applications/office/espanso/default.nix:1:3:

            1| { lib
             |   ^
            2| , coreutils
```

from a quick search it seems that this is caused by the package being designed to by build by `pkgs.CallPackage`. However, I do not know how to run the tests with that approach. Any help/links to docs would be greatly appreciated. Otherwise, I think that this is ready to go.

**Comment by raphaelchristin** [comment]
@pyrox0 sorry to bother you again. The automated checks seem to have failed as well as the `nix-build --attr pkgs.espanso.passthru.tests`. I am unsure how to "cleanly list package outputs after merging". It seems that the error is a missing `cxxabi` attribute. Do you have any idea of where I should look to fix this? I could not find anything relevant online. Thanks so much for you help and time!

**Comment by n8henrie** [comment]
Duplicate PR: https://github.com/NixOS/nixpkgs/pull/298530

**Comment by raphaelchristin** [comment]
Looks like the work is happening on #291484, will close this for now.

**Pull request closed without merging**
