### PR TITLE
virtualbox: 6.1.18 -> 6.1.22

### PR DESCRIPTION
**Pull request by wkral**
###### Motivation for this change
ZHF: #122042

Several of the virtualbox kernel modules would not build in https://hydra.nixos.org/eval/1670207 and the 6.1.20 release has a fix for 5.11 and 5.12 https://www.virtualbox.org/wiki/Changelog

Ran nixpkgs-review:

```
33 packages built:
linuxPackages.virtualbox linuxPackages.virtualboxGuestAdditions linuxPackages_4_14.virtualbox linuxPackages_4_14.virtualboxGuestAdditions linuxPackages_4_19.virtualbox linuxPackages_4_19.virtualboxGuestAdditions linuxPackages_4_4.virtualbox linuxPackages_4_4.virtualboxGuestAdditions linuxPackages_4_9.virtualbox linuxPackages_4_9.virtualboxGuestAdditions linuxPackages_5_11.virtualbox linuxPackages_5_11.virtualboxGuestAdditions linuxPackages_5_12.virtualbox linuxPackages_5_12.virtualboxGuestAdditions linuxPackages_5_4.virtualbox linuxPackages_5_4.virtualboxGuestAdditions linuxPackages_hardened.virtualbox linuxPackages_hardened.virtualboxGuestAdditions linuxPackages_latest_hardened.virtualbox linuxPackages_latest_hardened.virtualboxGuestAdditions linuxPackages_lqx.virtualbox linuxPackages_lqx.virtualboxGuestAdditions linuxPackages_testing_bcachefs.virtualbox linuxPackages_testing_bcachefs.virtualboxGuestAdditions linuxPackages_xanmod.virtualbox linuxPackages_xanmod.virtualboxGuestAdditions linuxPackages_zen.virtualbox linuxPackages_zen.virtualboxGuestAdditions virtualbox virtualboxExtpack virtualboxHardened virtualboxHeadless virtualboxWithExtpack
```

`Oracle_VM_VirtualBox_Extension_Pack-6.1.22.vbox-extpack` would not build because of the unfree licence.

This seemed to prevent nixpkgs-review from creating the report.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wkral** [comment]
cc @NixOS/nixos-release-managers

**Comment by wkral** [comment]
I believe this version incorporates the patch being introduced in https://github.com/NixOS/nixpkgs/pull/118740

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 123156` at 533265b3 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxPackages-libre.virtualbox</li>
    <li>linuxPackages-libre.virtualboxGuestAdditions</li>
    <li>linuxPackages_hardkernel_4_14.virtualbox</li>
    <li>linuxPackages_hardkernel_4_14.virtualboxGuestAdditions</li>
    <li>linuxPackages_hardkernel_latest.virtualbox</li>
    <li>linuxPackages_hardkernel_latest.virtualboxGuestAdditions</li>
    <li>linuxPackages_latest-libre.virtualbox</li>
    <li>linuxPackages_latest-libre.virtualboxGuestAdditions</li>
  </ul>
</details>
<details>
  <summary>3 packages skipped due to time constraints:</summary>
  <ul>
    <li>linuxPackages_testing_bcachefs.virtualbox</li>
    <li>virtualboxHeadless</li>
    <li>virtualboxWithExtpack</li>
  </ul>
</details>
<details>
  <summary>30 packages built successfully:</summary>
  <ul>
    <li>linuxPackages.virtualbox (linuxPackages_5_10.virtualbox)</li>
    <li>linuxPackages.virtualboxGuestAdditions (linuxPackages_5_10.virtualboxGuestAdditions)</li>
    <li>linuxPackages_4_14.virtualbox</li>
    <li>linuxPackages_4_14.virtualboxGuestAdditions</li>
    <li>linuxPackages_4_19.virtualbox</li>
    <li>linuxPackages_4_19.virtualboxGuestAdditions</li>
    <li>linuxPackages_4_4.virtualbox</li>
    <li>linuxPackages_4_4.virtualboxGuestAdditions</li>
    <li>linuxPackages_4_9.virtualbox</li>
    <li>linuxPackages_4_9.virtualboxGuestAdditions</li>
    <li>linuxPackages_5_11.virtualbox (linuxPackages_latest.virtualbox)</li>
    <li>linuxPackages_5_11.virtualboxGuestAdditions (linuxPackages_latest.virtualboxGuestAdditions)</li>
    <li>linuxPackages_5_12.virtualbox</li>
    <li>linuxPackages_5_12.virtualboxGuestAdditions</li>
    <li>linuxPackages_5_4.virtualbox</li>
    <li>linuxPackages_5_4.virtualboxGuestAdditions</li>
    <li>linuxPackages_hardened.virtualbox</li>
    <li>linuxPackages_hardened.virtualboxGuestAdditions</li>
    <li>linuxPackages_latest_hardened.virtualbox</li>
    <li>linuxPackages_latest_hardened.virtualboxGuestAdditions</li>
    <li>linuxPackages_lqx.virtualbox</li>
    <li>linuxPackages_lqx.virtualboxGuestAdditions</li>
    <li>linuxPackages_testing_bcachefs.virtualboxGuestAdditions</li>
    <li>linuxPackages_xanmod.virtualbox</li>
    <li>linuxPackages_xanmod.virtualboxGuestAdditions</li>
    <li>linuxPackages_zen.virtualbox</li>
    <li>linuxPackages_zen.virtualboxGuestAdditions</li>
    <li>virtualbox</li>
    <li>virtualboxExtpack</li>
    <li>virtualboxHardened</li>
  </ul>
</details>
<details>
  <summary>3 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/applications/virtualization/virtualbox/guest-additions/default.nix:74:3:
```
   |
74 |   buildPhase = ''
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/applications/virtualization/virtualbox/guest-additions/default.nix:105:3:
```
    |
105 |   installPhase = ''
    |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/stale-substitute.md">stale-substitute</a>

Stale substituteInPlace detected.
substituteStream(): WARNING: pattern '<ttm/' doesn't match anything in file 'src/vboxguest-6.1.22/vboxvideo/vbox_ttm.c'
Near pkgs/applications/virtualization/virtualbox/guest-additions/default.nix:156:0:
```
    |
156 |     description = "Guest additions for VirtualBox";
    | ^
```
</li>
  </ul>
</details>

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 123156 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>8 packages marked as broken and skipped:</summary>  <ul>    <li>linuxPackages-libre.virtualbox</li>    <li>linuxPackages-libre.virtualboxGuestAdditions</li>    <li>linuxPackages_hardkernel_4_14.virtualbox</li>    <li>linuxPackages_hardkernel_4_14.virtualboxGuestAdditions</li>    <li>linuxPackages_hardkernel_latest.virtualbox</li>    <li>linuxPackages_hardkernel_latest.virtualboxGuestAdditions</li>    <li>linuxPackages_latest-libre.virtualbox</li>    <li>linuxPackages_latest-libre.virtualboxGuestAdditions</li>  </ul></details><details>  <summary>33 packages built:</summary>  <ul>    <li>linuxPackages.virtualbox (linuxPackages_5_10.virtualbox)</li>    <li>linuxPackages.virtualboxGuestAdditions (linuxPackages_5_10.virtualboxGuestAdditions)</li>    <li>linuxPackages_4_14.virtualbox</li>    <li>linuxPackages_4_14.virtualboxGuestAdditions</li>    <li>linuxPackages_4_19.virtualbox</li>    <li>linuxPackages_4_19.virtualboxGuestAdditions</li>    <li>linuxPackages_4_4.virtualbox</li>    <li>linuxPackages_4_4.virtualboxGuestAdditions</li>    <li>linuxPackages_4_9.virtualbox</li>    <li>linuxPackages_4_9.virtualboxGuestAdditions</li>    <li>linuxPackages_5_11.virtualbox (linuxPackages_latest.virtualbox)</li>    <li>linuxPackages_5_11.virtualboxGuestAdditions (linuxPackages_latest.virtualboxGuestAdditions)</li>    <li>linuxPackages_5_12.virtualbox</li>    <li>linuxPackages_5_12.virtualboxGuestAdditions</li>    <li>linuxPackages_5_4.virtualbox</li>    <li>linuxPackages_5_4.virtualboxGuestAdditions</li>    <li>linuxPackages_hardened.virtualbox</li>    <li>linuxPackages_hardened.virtualboxGuestAdditions</li>    <li>linuxPackages_latest_hardened.virtualbox</li>    <li>linuxPackages_latest_hardened.virtualboxGuestAdditions</li>    <li>linuxPackages_lqx.virtualbox</li>    <li>linuxPackages_lqx.virtualboxGuestAdditions</li>    <li>linuxPackages_testing_bcachefs.virtualbox</li>    <li>linuxPackages_testing_bcachefs.virtualboxGuestAdditions</li>    <li>linuxPackages_xanmod.virtualbox</li>    <li>linuxPackages_xanmod.virtualboxGuestAdditions</li>    <li>linuxPackages_zen.virtualbox</li>    <li>linuxPackages_zen.virtualboxGuestAdditions</li>    <li>virtualbox</li>    <li>virtualboxExtpack</li>    <li>virtualboxHardened</li>    <li>virtualboxHeadless</li>    <li>virtualboxWithExtpack</li>  </ul></details>

**Pull request merged**
