### PR TITLE
cc-wrapper: propagate outputs

### PR DESCRIPTION
**Pull request by LnL7**
###### Motivation for this change

This makes it easier to reference the other outputs of wrapped compilers, eg.

```nix
{ pkgs, ... }:
{
  environment.systemPackages = [ gcc.man ];
}
```

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vcunat** [comment]
This assumes the compiler itself is in `.cc.out`, but that seems OK, at least for now.

**Comment by LnL7** [comment]
I could change it to use the first output instead.

**Comment by vcunat** [comment]
Yes, I think that would be better with the way we handle default outputs now.  It would also mean that `filter` would be changed to simple `tail` :-)

**Comment by edolstra** [comment]
What's wrong with saying `gcc.cc.man`? Propagating outputs seems ad hoc and potentially confusing to me.

**Comment by vcunat** [comment]
I thought the main advantage would be that `systemPackages = [ gcc ]` will provide the man pages if you have that set up, and (in future) also `nix-env`.

**Comment by LnL7** [comment]
Yes, just convenience.

**Comment by LnL7** [comment]
Given things like https://github.com/NixOS/nixpkgs/issues/26756, this could have some unwanted side effects.

**Pull request closed without merging**
