### PR TITLE
radicale: 3.0.3 -> 3.0.5

### PR DESCRIPTION
**Pull request by dotlambda**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — COMMENTED** [review]
breaks etesync-dav

```
builder for '/nix/store/fiz5962i7izaqmz4xly8b7d06ribpkg1-etesync-dav-0.20.0.drv' failed with exit code 1; last 10 log lines:
  adding 'etesync_dav-0.20.0.dist-info/top_level.txt'
  adding 'etesync_dav-0.20.0.dist-info/RECORD'
  removing build/bdist.linux-x86_64/wheel
  Finished executing setuptoolsBuildPhase
  installing
  Executing pipInstallPhase
  /build/etesync-dav-0.20.0/dist /build/etesync-dav-0.20.0
  Processing ./etesync_dav-0.20.0-py3-none-any.whl
  ERROR: Could not find a version that satisfies the requirement Radicale==3.0.3 (from etesync-dav==0.20.0) (from versions: none)
  ERROR: No matching distribution found for Radicale==3.0.3 (from etesync-dav==0.20.0)
cannot build derivation '/nix/store/kx57adwj6j3gpfnq1l02ayyh9mmc1xdz-env.drv': 1 dependencies couldn't be built
[2 built (1 failed), 9 copied (2.1 MiB), 0.4 MiB DL]
error: build of '/nix/store/kx57adwj6j3gpfnq1l02ayyh9mmc1xdz-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/96858
1 package failed to build:
etesync-dav
```

**Comment by jonringer** [comment]
please loosen the version bounds for `etesync-dav`

**Comment by dotlambda** [comment]
@jonringer Done.

**Review by jonringer — APPROVED** [review]
LGTM
shows usage

```
https://github.com/NixOS/nixpkgs/pull/96858
2 packages built:
etesync-dav radicale
```

**Pull request merged**
