### PR TITLE
exiv2: 0.27.6 -> 0.28.0

### PR DESCRIPTION
**Pull request by wegank**
###### Description of changes

From https://packages.gentoo.org/packages/media-gfx/exiv2:
> A major reverse depndency (kde-apps/libkexiv2) does not yet build against this so mask for now, see bug #906087 and bug #906090.

https://archlinux.org/todo/exiv2-028/

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by misuzu** [comment]
`github.test_CVE_2018_12265.AdditionOverflowInLoaderExifJpeg` fails on `armv7l-linux`:
```
$ nix-build . --no-out-link --fallback -A pkgs.exiv2 --system armv7l-linux
<............................................................................>
test_run (redmine.test_issue_937.DarwinCoreXmpMetadataPrint) ... ok

======================================================================
FAIL: test_run (github.test_CVE_2018_12265.AdditionOverflowInLoaderExifJpeg)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/tests/system_tests.py", line 652, in test_run
    self.compare_stderr(i, command, processed_stderr, stderr)
  File "/build/source/tests/system_tests.py", line 773, in compare_stderr
    self._compare_output(
  File "/build/source/tests/system_tests.py", line 745, in _compare_output
    self.assertMultiLineEqual(
AssertionError: 'Erro[319 chars]ata area; ignored.\n' != 'Erro[319 chars]ata area; ignored.\nUncaught exception: Overflow in addition\n'
  Error: Upper boundary of data for directory Image, entry 0x00fe is out of bounds: Offset = 0x0000002a, size = 64, exceeds buffer size by 22 Bytes; truncating the entry
  Warning: Directory Image, entry 0x0201: Strip 0 is outside of the data area; ignored.
  Warning: Directory Image, entry 0x0201: Strip 7 is outside of the data area; ignored.
+ Uncaught exception: Overflow in addition
 : Standard error does not match

----------------------------------------------------------------------
Ran 302 tests in 7.424s

FAILED (failures=1, skipped=10)


80% tests passed, 1 tests failed out of 5

Total Test time (real) =   8.16 sec

The following tests FAILED:
          1 - bugfixTests (Failed)
Errors while running CTest
make: *** [Makefile:71: test] Error 8
```

**Comment by wegank** [comment]
I'll remove that test on `stdenv.hostPlatform.isAarch32`, as in 0.27.7.

In the meantime, this PR is still in draft for gexiv2 regression on darwin, see Homebrew/homebrew-core#130959.

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 231244` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>36 packages marked as broken and skipped:</summary>
  <ul>
    <li>cataract</li>
    <li>cataract-unstable</li>
    <li>entangle</li>
    <li>gimp-with-plugins</li>
    <li>gnome.nautilus-python</li>
    <li>gnome.nautilus-python.dev</li>
    <li>gnome.nautilus-python.devdoc</li>
    <li>gnome.nautilus-python.doc</li>
    <li>kphotoalbum</li>
    <li>krename</li>
    <li>latte-dock</li>
    <li>libsForQt5.arianna</li>
    <li>libsForQt5.bismuth</li>
    <li>libsForQt5.krohnkite</li>
    <li>libsForQt5.kwin-dynamic-workspaces</li>
    <li>libsForQt5.kwin-tiling</li>
    <li>libsForQt5.kzones</li>
    <li>libsForQt5.parachute</li>
    <li>lightly-boehs</li>
    <li>lightly-qt</li>
    <li>plasma5Packages.arianna</li>
    <li>plasma5Packages.bismuth</li>
    <li>plasma5Packages.krohnkite</li>
    <li>plasma5Packages.kwin-dynamic-workspaces</li>
    <li>plasma5Packages.kwin-tiling</li>
    <li>plasma5Packages.kzones</li>
    <li>plasma5Packages.parachute</li>
    <li>python310Packages.py3exiv2</li>
    <li>python310Packages.py3exiv2.dist</li>
    <li>python311Packages.py3exiv2</li>
    <li>python311Packages.py3exiv2.dist</li>
    <li>toppler</li>
    <li>variety</li>
    <li>variety.dist</li>
    <li>vimiv-qt</li>
    <li>vimiv-qt.dist</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>darktable</li>
    <li>merkaartor</li>
  </ul>
</details>
<details>
  <summary>24 packages built:</summary>
  <ul>
    <li>exiv2</li>
    <li>exiv2.dev</li>
    <li>exiv2.doc</li>
    <li>exiv2.lib</li>
    <li>exiv2.man</li>
    <li>gegl</li>
    <li>gegl.dev</li>
    <li>gegl.devdoc</li>
    <li>gexiv2</li>
    <li>gexiv2.dev</li>
    <li>gexiv2.devdoc</li>
    <li>gimp (gimpPlugins.gimp)</li>
    <li>gimp.dev (gimpPlugins.gimp.dev)</li>
    <li>gimpPlugins.gmic</li>
    <li>gpscorrelate</li>
    <li>gramps</li>
    <li>gramps.dist</li>
    <li>libsForQt5.kfilemetadata (plasma5Packages.kfilemetadata)</li>
    <li>libsForQt5.kfilemetadata.bin (plasma5Packages.kfilemetadata.bin)</li>
    <li>libsForQt5.kfilemetadata.dev (plasma5Packages.kfilemetadata.dev)</li>
    <li>nomacs</li>
    <li>photoqt</li>
    <li>tracker-miners</li>
    <li>viking</li>
  </ul>
</details>

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 231244` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>37 packages marked as broken and skipped:</summary>
  <ul>
    <li>cataract</li>
    <li>cataract-unstable</li>
    <li>entangle</li>
    <li>gimp-with-plugins</li>
    <li>gnome.nautilus-python</li>
    <li>gnome.nautilus-python.dev</li>
    <li>gnome.nautilus-python.devdoc</li>
    <li>gnome.nautilus-python.doc</li>
    <li>kphotoalbum</li>
    <li>krename</li>
    <li>latte-dock</li>
    <li>libsForQt5.arianna</li>
    <li>libsForQt5.bismuth</li>
    <li>libsForQt5.krohnkite</li>
    <li>libsForQt5.kwin-dynamic-workspaces</li>
    <li>libsForQt5.kwin-tiling</li>
    <li>libsForQt5.kzones</li>
    <li>libsForQt5.parachute</li>
    <li>lightly-boehs</li>
    <li>lightly-qt</li>
    <li>merkaartor</li>
    <li>plasma5Packages.arianna</li>
    <li>plasma5Packages.bismuth</li>
    <li>plasma5Packages.krohnkite</li>
    <li>plasma5Packages.kwin-dynamic-workspaces</li>
    <li>plasma5Packages.kwin-tiling</li>
    <li>plasma5Packages.kzones</li>
    <li>plasma5Packages.parachute</li>
    <li>python310Packages.py3exiv2</li>
    <li>python310Packages.py3exiv2.dist</li>
    <li>python311Packages.py3exiv2</li>
    <li>python311Packages.py3exiv2.dist</li>
    <li>toppler</li>
    <li>variety</li>
    <li>variety.dist</li>
    <li>vimiv-qt</li>
    <li>vimiv-qt.dist</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>darktable</li>
  </ul>
</details>
<details>
  <summary>24 packages built:</summary>
  <ul>
    <li>exiv2</li>
    <li>exiv2.dev</li>
    <li>exiv2.doc</li>
    <li>exiv2.lib</li>
    <li>exiv2.man</li>
    <li>gegl</li>
    <li>gegl.dev</li>
    <li>gegl.devdoc</li>
    <li>gexiv2</li>
    <li>gexiv2.dev</li>
    <li>gexiv2.devdoc</li>
    <li>gimp (gimpPlugins.gimp)</li>
    <li>gimp.dev (gimpPlugins.gimp.dev)</li>
    <li>gimpPlugins.gmic</li>
    <li>gpscorrelate</li>
    <li>gramps</li>
    <li>gramps.dist</li>
    <li>libsForQt5.kfilemetadata (plasma5Packages.kfilemetadata)</li>
    <li>libsForQt5.kfilemetadata.bin (plasma5Packages.kfilemetadata.bin)</li>
    <li>libsForQt5.kfilemetadata.dev (plasma5Packages.kfilemetadata.dev)</li>
    <li>nomacs</li>
    <li>photoqt</li>
    <li>tracker-miners</li>
    <li>viking</li>
  </ul>
</details>

**Pull request merged**
