### PR TITLE
crashplan:Bump version, make it all work, and for good measure adopt the package.

### PR DESCRIPTION
**Pull request by Baughn**
I actively use crashplan, so there's a good chance I'll keep it working.

Bugfixes:
- Crashplan no longer crashes on startup.
- Further, the crashplan service is run as a non-root user.

Open questions:
- Does it really work? I had to manually change the backup target from /home/crashplan to /var/lib/crashplan/ in the UI, but as per the commit message, that might just be me.
- The wrapper script is a little ugly.

### CODE REVIEW

**Comment by domenkozar** [comment]
@Baughn good job, where you also getting nullpointer exceptions when starting crashplan?

**Comment by Baughn** [comment]
@domenkozar Yep.

This one *works*, but I'm not confident in those niggling issues yet. Ideally I'd like someone else to try it.

**Comment by benley** [comment]
I've historically run CrashPlan as root so it could read files to be backed up.  Thinking it over now, I'm not opposed to running it as an unprivileged user that could be added to other groups to give it read access to things.  Maybe it would be desirable to have a "runAsRoot" configurable, or something like that?

**Comment by Baughn** [comment]
I realised a problem with my approach: If /var/lib/crashplan is a mountpoint, and noauto is set for the mountpoint, then Crashplan will still start even if it fails to mount.

That's not a plausible configuration at present, so I'll handle it in a second PR.

**Comment by jerith666** [comment]
I just tried to use this by merging it into 77f8f35.  When I run `crashplan-desktop` as a normal user, I get:

`mkdir: cannot create directory ‘/var/lib/crashplan’: Permission denied`
`mkdir: cannot create directory ‘/var/lib/crashplan’: Permission denied`
`mkdir: cannot create directory ‘/var/lib/crashplan’: Permission denied`

**Comment by jerith666** [comment]
when I run as root, it starts up, but the file picker for what to back up does not show any files under my user's home directory.

**Comment by Baughn** [comment]
@jerith666 Yes, I got the code somewhat wrong. Consider this PR DNM until further notice.

**Pull request closed without merging**
