### PR TITLE
python3Packages.py-cpuinfo: 5.0.0 -> 7.0.0

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

noticed it was out of date in #111661 and it was causing alot of rebuilds.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by fabaff — APPROVED** [review]
The changes look good to me.

Perhaps we could add `pythonImportsCheck` additionally.

**Comment by mweinelt** [comment]
I'm not quite sure if pythonImportsCheck has an additional benefit when the tests already run, as they show whether the package could be imported as well, no?

**Comment by rhoriguchi** [comment]
[gns3-server](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/gns3/server.nix) has an override for this exact version, could probably be removed?

**Comment by mweinelt** [comment]
> [gns3-server](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/gns3/server.nix) has an override for this exact version, could probably be removed?

Thanks, removed.

**Pull request merged**
