### PR TITLE
innoextract: support extraction of multi-file archives

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

innoextract supports a ```--gog``` argument which will process extra multi-file archives distributed by gog.com

A slight downside is the increase of the closure size from 76MB to 1.4GB so we can of course make the ```withGog``` argument ```false``` instead by default.

Cc: @abbradar 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by rnhmjoj** [comment]
wow, 1.4GB is pretty bad. I see that it also supports unrar (it's non-free though).

**Comment by peterhoeg** [comment]
My line of reasoning was that considering this is more likely to be used on desktop systems where the parts of the closure is probably available, it is better than adding non-free.

The other option is of course to simply toggle it to false by default and use overrides for those that don't mind the large closure.

**Comment by rnhmjoj** [comment]
It makes sense. I'm also ok with this since I use it only when unpacking something and don't keep it installed. Why is unar's closure so big anyway? GNUstep?

**Comment by peterhoeg** [comment]
> Why is unar's closure so big anyway? GNUstep?

Yes.

**Comment by soredake** [comment]
Any progress?

**Comment by abbradar** [comment]
@peterhoeg Thanks for your work and sorry for taking a long time!

**Pull request merged**
