### PR TITLE
atlauncher: 3.4.28.1 -> 3.4.30.0

### PR DESCRIPTION
**Pull request by Tofixrs**
###### Description of changes

Updated the package + added a fix so the launcher opens if there is an update (--no-launcher-update true)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Tofixrs** [comment]
a new update was released today gonna update the pr in a sec

**Comment by ElXreno** [comment]
If I'm not mistaken, you forgot to update the hash in the last commit.
```
error: hash mismatch in fixed-output derivation '/nix/store/jdcarzjkh9bbk993haibddhqm6wrskad-ATLauncher-3.4.30.0.jar.drv':
         specified: sha256-k7XxVDcApbZPz/kBdt0P6cy+MBd3L75KscDliDFgsfY=
            got:    sha256-eSb+qH/ZoPpeOyIuoJsEpecG7uUyh0vkqZzNuxriRuI=
```

**Comment by Tofixrs** [comment]
> If I'm not mistaken, you forgot to update the hash in the last commit.
> 
> ```
> error: hash mismatch in fixed-output derivation '/nix/store/jdcarzjkh9bbk993haibddhqm6wrskad-ATLauncher-3.4.30.0.jar.drv':
>          specified: sha256-k7XxVDcApbZPz/kBdt0P6cy+MBd3L75KscDliDFgsfY=
>             got:    sha256-eSb+qH/ZoPpeOyIuoJsEpecG7uUyh0vkqZzNuxriRuI=
> ```

oh yea will fiz it asap

**Comment by GetPsyched** [comment]
Hey, @Tofixrs; thanks for the PR. Could you please update the hash and force push? Everything else seems to be running.

**Comment by Tofixrs** [comment]
There updated the last commit to include the hash

**Review by GetPsyched — APPROVED** [review]
Unfortunate middle commit to `3.4.29.1` but I think it's fine. Other than that, things look good and seem to be running well on my system along with all the checks passing.

**Comment by GetPsyched** [comment]
Can someone please review and/or merge this? It fixes a breaking issue within ATLauncher that's needed more than the version bump.

**Review by drupol — CHANGES_REQUESTED** [review]
Hi !

Thanks for your first contribution!

Could you please squash the update commits together, so there's only 2 commits in this PR?

**Comment by drupol** [comment]
I tried to fix the issue myself, but I don't have the permission to push on your branch.

**Comment by Tofixrs** [comment]
done! sorry for the wait was busy recently

**Review by drupol — APPROVED** [review]

**Pull request merged**
