### PR TITLE
Pyarrow

### PR DESCRIPTION
**Pull request by teh**
###### Motivation for this change

This is probably one for @FRidh. I've been meaning to package pyarrow for a while, but it turned out to be a bit fiddly, mainly because its reliance on static libraries.

This PR is a suggestion for how we could package pyarrow, though I understand that some changes might be a bit controversial (new static flags for snappy, thrift & lz4 e.g.).

I still need to run this through `nox-review pr` & test the plasma binary 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by dotlambda — CHANGES_REQUESTED** [review]

**Review by FRidh — CHANGES_REQUESTED** [review]
I don't see any motivation for building static libraries.

> mainly because its reliance on static libraries.

Where is that documented? Have you tried without?

**Comment by teh** [comment]
Thanks for review @dotlambda - will address and comment here when done.

@FRidh It's not documented explicitly - it's in their build files [1]. It's probably possible to patch it out but I haven't managed to do so.

[1]
https://github.com/apache/arrow/blob/master/cpp/CMakeLists.txt#L530

https://github.com/apache/arrow/blob/master/cpp/cmake_modules/FindLz4.cmake

(when setting e.g  
```    
"-DLZ4_HOME=${pkgs.lz4.dev}"
"-DLZ4_SHARED_LIB=${pkgs.lz4}/lib/liblz4.so"
``` 

you get errors like ```-- Could NOT find LZ4 (missing: LZ4_STATIC_LIB)```)

**Comment by FRidh** [comment]
@teh have you raised an issue about this?

**Comment by veprbl** [comment]
I've just learned that there is ```symlinkJoin```. I think that it would be much help when building ```arrow-cpp```.

**Comment by veprbl** [comment]
#37196

**Pull request closed without merging**
