### PR TITLE
rPackages.svglite: Fix nativeBuildInputs

### PR DESCRIPTION
**Pull request by turion**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by turion** [comment]
Without this change, I get this build error:

```
builder for '/nix/store/8m06hkbcrxazj695nh0ikdyjsm1izkrf-r-svglite-2.0.0.drv' failed with exit code 1; last 10 log lines:
  ** libs
  /nix/store/x0xd1vp2w7n38g0hzflzy8p6hyl0dwic-gcc-wrapper-10.3.0/bin/c++ -std=gnu++11 -I"/nix/store/yghr6b4377k3aqhzm1xm0vfjazbriikk-R-4.0.4/lib/R/include" -DNDEBUG  -I'/nix/store/cmr1g9xly0gnlgbpkvmiia2gl21yfs31-r-cpp11-0.2.7/library/cpp11/include' -I'/nix/store/28i6lkk4c2gbi3c53apvldlb0wcnd7i6-r-systemfonts-1.0.1/library/systemfonts/include'    -fpic  -g -O2  -c cpp11.cpp -o cpp11.o
  /nix/store/x0xd1vp2w7n38g0hzflzy8p6hyl0dwic-gcc-wrapper-10.3.0/bin/c++ -std=gnu++11 -I"/nix/store/yghr6b4377k3aqhzm1xm0vfjazbriikk-R-4.0.4/lib/R/include" -DNDEBUG  -I'/nix/store/cmr1g9xly0gnlgbpkvmiia2gl21yfs31-r-cpp11-0.2.7/library/cpp11/include' -I'/nix/store/28i6lkk4c2gbi3c53apvldlb0wcnd7i6-r-systemfonts-1.0.1/library/systemfonts/include'    -fpic  -g -O2  -c devSVG.cpp -o devSVG.o
  devSVG.cpp:21:10: fatal error: png.h: No such file or directory
     21 | #include <png.h>
        |          ^~~~~~~
  compilation terminated.
  make: *** [/nix/store/yghr6b4377k3aqhzm1xm0vfjazbriikk-R-4.0.4/lib/R/etc/Makeconf:181: devSVG.o] Error 1
  ERROR: compilation failed for package 'svglite'
  * removing '/nix/store/20jz6ihfcn5a9vcbllwraldayf1im3di-r-svglite-2.0.0/library/svglite'
[0 built (1 failed), 0.0 MiB DL]
error: build of '/nix/store/8m06hkbcrxazj695nh0ikdyjsm1izkrf-r-svglite-2.0.0.drv' failed
```

**Review by SuperSandro2000 — COMMENTED** [review]
You are sure this is not buildInputs?

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 128602 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by turion** [comment]
> You are sure this is not buildInputs?

@SuperSandro2000 No, I'm not sure. Either fixes the build. I thought it must be `nativeBuildInputs` because it's a C++ source file. But if this is wrong then I'm happy to open a PR to fix this.

**Comment by jonringer** [comment]
it's inline with all of the other rPackages, so it's at least consistent in it's current state.

Maybe all of rPackages should be revisited? At the very least, it seems to work.

**Pull request merged**
