### PR TITLE
eid-mw: fix build by restoring p11-kit module installation path

### PR DESCRIPTION
**Pull request by chvp**
## Description of changes

Since https://github.com/NixOS/nixpkgs/pull/244633, the installation path for p11-kit was picked up to be in the p11-kit out path, which obviously doesn't work. This commit restores the installation path to the value it was before https://github.com/NixOS/nixpkgs/pull/244633.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NickCao** [comment]
> Since #244633, the installation path for p11-kit was picked up to be in the p11-kit out path, which obviously doesn't work. 

May you explain this further to see it we can fix this in p11-kit itself.

**Comment by chvp** [comment]
To be honest, I don't fully understand it myself. I assume that meson generates the pkgconfig files a bit differently, but I didn't (and don't) have the time at the moment to do a full deep dive.

**Comment by NickCao** [comment]
Checked https://p11-glue.github.io/p11-glue/p11-kit/manual/devel-paths.html, so PKCS#11 modules ought to install files into `p11_module_configs`, which isn't possible in nixpkgs, the current patching method is ok. Just move it to postPatch.

**Comment by chvp** [comment]
It can't be moved to postPatch, autoreconfHook has to run first.

**Comment by NickCao** [comment]
> It can't be moved to postPatch, autoreconfHook has to run first.

You can patch `configure.ac` which is in turn used to generate `configure`.

**Comment by chvp** [comment]
> > It can't be moved to postPatch, autoreconfHook has to run first.
> 
> You can patch `configure.ac` which is in turn used to generate `configure`.

Done

**Review by NickCao — APPROVED** [review]

**Pull request merged**
