### PR TITLE
dotnetCorePackages.sdk_3_1: 3.1.102 -> 3.1.402

### PR DESCRIPTION
**Pull request by JamieMagee**
###### Motivation for this change

Security patch for .NET released earlier this week

Supersedes #92659

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by felschr** [comment]
`nixpkgs-review` results:
```
4 packages failed to build:
osu-lazer python-language-server ryujinx wasabibackend

2 packages built:
dotnet-sdk_3 jetbrains.rider
```

**Comment by JamieMagee** [comment]
@felschr I pushed the required changes to the dependent packages.

**Review by felschr — APPROVED** [review]
##### Reviewed points

- [x] package name fits guidelines
- [x] package version fits guidelines
- [x] package build on x86_64-linux
- [x] executables tested on x86_64-linux
- [x] all depending packages build

##### Possible improvements

You might want to use a more specific commit message, e.g. `dotnetCorePackages.sdk_3_1: fix dependent packages`.
Otherwise it looks good to me.

**Comment by JamieMagee** [comment]
> You might want to use a more specific commit message, e.g. dotnetCorePackages.sdk_3_1: fix dependent packages.
> Otherwise it looks good to me.

Thanks. I'll force push an updated commit to this branch (if that's allowed)

**Comment by felschr** [comment]
Yes, I'd assume this falls under https://nixos.org/manual/nixpkgs/stable/#submitting-changes-hotfixing-pull-requests.

**Comment by felschr** [comment]
ping

**Comment by JamieMagee** [comment]
@felschr Updated the commit message

**Comment by felschr** [comment]
@JamieMagee Thanks for the contribution! The dotnet packages have been out of date for quite a while :)

**Pull request merged**
