### PR TITLE
juliaup: init at 1.6.12

### LINKED ISSUE #184186: juliaup
**Project description**
Juliaup is the new installer and version multiplexer for the Julia runtime. In a few weeks it is going to be the default installer for the Julia language, as just announced on the JuliaConference last week.

It would be great to have it available in nixpkgs.

**Metadata**

* homepage URL: https://github.com/JuliaLang/juliaup
* source URL: https://github.com/JuliaLang/juliaup
* license: mit
* platforms: unix, linux, darwin, ...

### PR DESCRIPTION
**Pull request by SCOTT-HAMILTON**
###### Description of changes
Fixes https://github.com/NixOS/nixpkgs/issues/184186

###### Things done
Tested `juliaup add 1.5.1`. (Once I've made it the default version, I can't uninstall it though...)

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Emiller88** [comment]
This doesn't seem to add `julia` to the path.

**Comment by SCOTT-HAMILTON** [comment]
> This doesn't seem to add `julia` to the path.

In order to make juliaup add the binaries to path, you need to call `juliaup config modifypath true` which is a config-subcommand that is only available with the selfupdate feature. But this feature isn't meant to be used by distribution packages because it only works if juliaup is installed with the juliaupinstaller cf https://github.com/JuliaLang/juliaup/issues/236#issuecomment-1024959357.

So I think your best option is to open an issue on home-manager to add a julia module.

**Comment by schlichtanders** [comment]
Why was this pullrequest closed by yourself @SCOTT-HAMILTON ?

I am using NixOS without home-manager because I am the only user of my laptop and as such it is easier for me to define paths, etc etc. via nixos directly.

It makes totally sense that if `juliaup` is installed via nix, then only `juliaup` is available by default.

If `juliaup` then creates a julia binaries at some place under the home directory, this is perfect, as I can simply add this home directory via nixos config to my shell setup.

Please consider reopening and merging this pullrequest.

**Comment by SCOTT-HAMILTON** [comment]
> Why was this pullrequest closed by yourself @SCOTT-HAMILTON ?
> 
> I am using NixOS without home-manager because I am the only user of my laptop and as such it is easier for me to define paths, etc etc. via nixos directly.
> 
> It makes totally sense that if `juliaup` is installed via nix, then only `juliaup` is available by default.
> 
> If `juliaup` then creates julia binaries at some place under the home directory, this is perfect, as I can simply add this home directory via nixos config to my shell setup.
> 
> Please consider reopening and merging this pullrequest.

I don't have any time to work on this now. Feel free to edit or copy this as you like.

**Comment by schlichtanders** [comment]
I just tried to setup juliaup with this, but run into similar things as were already mentioned, especially that juliaup is not only installing different julia versions, but is also self-updating by default.

The official juliaup site also recommends against using OS-specific juliaup installations as of now.
> As of now, we strongly recommend to install Juliaup via the Windows Store or `curl` command above rather than through OS-specific software repositories


Here the curl command which actually worked for me on nixos.

> Juliaup can be installed on Linux or Mac by executing
    ```
    curl -fsSL https://install.julialang.org | sh
    ```
> in a shell.


Until JuliaUp has stable support for Linux OS package manager, I would put a juliaup nix-package on hold.

**Pull request closed without merging**
