### PR TITLE
firewall: add warning when firewall used with docker

### PR DESCRIPTION
**Pull request by cmoog**
###### Description of changes

Docker does not always abide by the network firewall rules
and can cause unexpected behavior. This PR adds a warning when
the docker and the network firewall are used together.

More context here: https://github.com/NixOS/nixpkgs/issues/111852

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Why are we not going this route https://github.com/NixOS/nixpkgs/issues/111852#issuecomment-786543067 ?

**Comment by cmoog** [comment]
> Why are we not going this route https://github.com/NixOS/nixpkgs/issues/111852#issuecomment-786543067 ?

I agree that fixing the root cause would be preferable. That said, the linked solution was proposed about 1.5 years ago and no progress has been made. I don't know the specifics, but I'm guessing there are some implementation complications that would require special consideration. Given the severity of this behavior, I think it would be prudent to merge this in the meantime and backport it into `22.05`, if possible.

**Comment by cmoog** [comment]
I'm going to close this as unresolved to unclutter the pending PR list. That said, I still think this is a major security problem that warrants a hot fix.

**Comment by carlthome** [comment]
Think this PR should be reopened and merged. This is a big trust issue that creeped me out when checking `iptables` manually on a NixOS host.

**Pull request closed without merging**
