### PR TITLE
mate: update to version 1.24.0

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

Update to version 1.24.0.

[Announcement](https://mate-desktop.org/blog/2020-02-10-mate-1-24-released/).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by worldofpeace** [comment]
Will review @romildo, happy to say https://github.com/NixOS/nixpkgs/issues/71427 got fixed recently.
It's a shame this happened right after 20.03 branch off.

**Comment by worldofpeace** [comment]
Could you still reproduce https://github.com/NixOS/nixpkgs/issues/75447? I couldn't in the vm.

Currently marco is crashing
```
Feb 13 21:54:25 nixos .marco-wrapped[1036]: Settings schema 'org.mate.peripherals-mouse' is not installed
```

**Review by worldofpeace — CHANGES_REQUESTED** [review]
You're missing `mate-settings-daemon` in `marco`.

I did also notice they ported several projects to using meson
* https://github.com/mate-desktop/mate-desktop/blob/master/meson.build
* https://github.com/mate-desktop/marco/blob/master/meson.build
* https://github.com/mate-desktop/mate-backgrounds/blob/master/meson.build
* https://github.com/mate-desktop/mozo/blob/master/meson.build

It'd be cool to port to them.

**Review by worldofpeace — CHANGES_REQUESTED** [review]
There's another important news item.
```
i18n: All applications have been migrated from intltools to gettext.
```

You need to remove `intiltool` for `gettext` in every expression.

**Comment by romildo** [comment]
> Could you still reproduce #75447? I couldn't in the vm.

I cannot reproduce it. I have closed the issue now.

> Currently marco is crashing
> 
> ```
> Feb 13 21:54:25 nixos .marco-wrapped[1036]: Settings schema 'org.mate.peripherals-mouse' is not installed
> ```

Fixed.

**Comment by romildo** [comment]
> There's another important news item.
> 
> ```
> i18n: All applications have been migrated from intltools to gettext.
> ```
> 
> You need to remove `intiltool` for `gettext` in every expression.

Done.

**Comment by romildo** [comment]
> There's another important news item.
> 
> ```
> i18n: All applications have been migrated from intltools to gettext.
> ```
> 
> You need to remove `intiltool` for `gettext` in every expression.

Done.

> You're missing `mate-settings-daemon` in `marco`.

Fixed.

> I did also notice they ported several projects to using meson
> 
>     * https://github.com/mate-desktop/mate-desktop/blob/master/meson.build
> 
>     * https://github.com/mate-desktop/marco/blob/master/meson.build
> 
>     * https://github.com/mate-desktop/mate-backgrounds/blob/master/meson.build
> 
>     * https://github.com/mate-desktop/mozo/blob/master/meson.build
> 
> 
> It'd be cool to port to them.

The `meson.build` files are not being distributed in the source `*.tar.xz` files, although they are available at the git repository.

**Comment by worldofpeace** [comment]
> The meson.build files are not being distributed in the source *.tar.xz files, although they are available at the git repository.

Aww, that sucks. It's pretty weird they'd advertise it but not distribute it. Perhaps they consider it experimental.

**Comment by worldofpeace** [comment]
@romildo mate-user-guide doesn't launch in the session.
Looking at the desktop file
```
Exec=yelp help:mate-user-guide
```

You need to install `yelp` in `mate.nix`.
I'm pretty sure it has an impurity that it has to be in systemPackages.

**Review by worldofpeace — CHANGES_REQUESTED** [review]
^ See above comment.

**Comment by romildo** [comment]
> @romildo mate-user-guide doesn't launch in the session.
> Looking at the desktop file
> 
> ```
> Exec=yelp help:mate-user-guide
> ```
> 
> You need to install `yelp` in `mate.nix`.
> I'm pretty sure it has an impurity that it has to be in systemPackages.

Wouldn't it be enough to use the full path for `yelp` in the desktop file?

**Comment by worldofpeace** [comment]
> > @romildo mate-user-guide doesn't launch in the session.
> > Looking at the desktop file
> > ```
> > Exec=yelp help:mate-user-guide
> > ```
> > 
> > 
> > You need to install `yelp` in `mate.nix`.
> > I'm pretty sure it has an impurity that it has to be in systemPackages.
> 
> Wouldn't it be enough to use the full path for `yelp` in the desktop file?

That's because we do it in the gnome3 module https://github.com/NixOS/nixpkgs/blob/c2dc35e6feea0ce7fcf09d10482566c9849ceb9d/nixos/modules/services/x11/desktop-managers/gnome3.nix#L355

As stated in 

>  I'm pretty sure it has an impurity that it has to be in systemPackages.

That's just from remembrance though. You could try it.

**Comment by romildo** [comment]
> > Wouldn't it be enough to use the full path for `yelp` in the desktop file?
> 
> That's because we do it in the gnome3 module
> 
> https://github.com/NixOS/nixpkgs/blob/c2dc35e6feea0ce7fcf09d10482566c9849ceb9d/nixos/modules/services/x11/desktop-managers/gnome3.nix#L355
> 
> As stated in
> 
> > I'm pretty sure it has an impurity that it has to be in systemPackages.
> 
> That's just from remembrance though. You could try it.

The user guide works when the full path to `yelp` is used in the desktop file.

But it seems that  `yelp` in `$PATH` is needed  for 'Contents' in 'Help' menus of the applications.

**Review by worldofpeace — APPROVED** [review]
I believe this is good :+1: 
I haven't QA'd very much.
(I did start every app briefly, which is when I noticed the mate-user-guide thing)

**Pull request merged**
