### PR TITLE
imagemagick: 7.1.0-5 -> 7.1.0-6

### PR DESCRIPTION
**Pull request by erictapen**
###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by veprbl** [comment]
https://imagemagick.org/script/changelog.php
```
2021-09-04 7.1.0-6 <quetzlzacatenango@image...>
Release ImageMagick version 7.1.0-6 GIT revision 19025:1161978e8:20210904
2021-08-21 7.1.0-6 <quetzlzacatenango@image...>
Tweak the bilevel image type (reference https://github.com/ImageMagick/ImageMagick/issues/4121).
Converting from LAB to RGB leads to wrong colors (reference https://github.com/ImageMagick/ImageMagick/issues/4105).
```

**Comment by veprbl** [comment]
@erictapen This can go to master

**Comment by erictapen** [comment]
@veprbl Mh interesting, the amount of reverse dependencies of imagemagick seems to fluctuate quite a bit. Rebasing to master is not possible though, as 042229148d725151a89727bf70cd117250945f9f is still in staging.

**Comment by veprbl** [comment]
> @veprbl Mh interesting, the amount of reverse dependencies of imagemagick seems to fluctuate quite a bit.

That would be interesting. Ping me if you see that.

> Rebasing to master is not possible though, as [0422291](https://github.com/NixOS/nixpkgs/commit/042229148d725151a89727bf70cd117250945f9f) is still in staging.

We could target staging-next then

**Pull request closed without merging**
