### PR TITLE
firefox: 94.0.1 -> 94.0.2, firefox-bin: 94.0 -> 94.0.2

### PR DESCRIPTION
**Pull request by taku0**
###### Motivation for this change

Release notes are not updated yet.

https://www.mozilla.org/en-US/firefox/94.0.2/releasenotes/

Supersedes: https://github.com/NixOS/nixpkgs/pull/146570

YouTube is still crashing: https://github.com/NixOS/nixpkgs/issues/146382

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabianhjr** [comment]
Hash of 94.0.2 seems to have changed:

```
error: hash mismatch in fixed-output derivation '/nix/store/ma8znwj5chrppdg3d54vqa66i7diwcmv-firefox-94.0.2.source.tar.xz.drv':
         specified: sha512-bkVxRJsCK/tFu+TUbC0nVU9fDk50enzgS7BhpiQi23T8QJmnyP94qIcTXP5RmHf+5cghtV2I8AI9/0wzTv2Gag==
            got:    sha512-AM5Pa+cR4fMJgo4DAWPmG72f4zZKjoUuZEF3yTgyB4h33qGlFnGbEGpSwNhGIZPtUsHTzHrjTqAh6x3Q9baF4g==
```

**Comment by taku0** [comment]
Fixed hashes of `firefox` and `firefox-bin`.

**Comment by fabianhjr** [comment]
Hey, I am not familiar with firefox release process. Has 94.0.2 been released or are this prerelease snapshots?

**Comment by mweinelt** [comment]
> Hey, I am not familiar with firefox release process. Has 94.0.2 been released or are this prerelease snapshots?

The release is usually available a few days before the release notes are out.

**Comment by mweinelt** [comment]
> YouTube is still crashing: #146382

Fixed on master. Will now review the source build after rebasing this branch onto master.

**Review by mweinelt — APPROVED** [review]
Both source and binary build works just fine on x86-64-linux sway/pipewire.

**Review by fabianhjr — APPROVED** [review]
Works great. :+1:

**Pull request merged**
