### PR TITLE
perlPackages.AnyEventAIO: init at 1.1

### PR DESCRIPTION
**Pull request by stigtsp**
###### Motivation for this change

Adds the `AnyEvent::AIO` Perl module.

dependencies:
perlPackages.IOAIO: init at 4.72

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Tested OK on `linux x64` and `darwin x64`

Result of `nixpkgs-review` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>perl530Packages.AnyEventAIO</li>
    <li>perl530Packages.IOAIO</li>
    <li>perl532Packages.AnyEventAIO</li>
    <li>perl532Packages.IOAIO</li>
  </ul>
</details>

### CODE REVIEW

**Comment by stigtsp** [comment]
Cc: @zakame

**Comment by stigtsp** [comment]
Cc: @Vonfry

**Comment by stigtsp** [comment]
@GrahamcOfBorg build perlPackages.AnyEventAIO
@GrahamcOfBorg build perldevelPackages.AnyEventAIO

**Comment by zakame** [comment]
Nice, for `Perl::LanguageServer` I presume?  I think I had an expression for this prepared before...

**Comment by stigtsp** [comment]
> Nice, for `Perl::LanguageServer` I presume? I think I had an expression for this prepared before...

Ah yes, it seems to be what triggered #103603. Would be great with `Perl::LanguageServer`. :)

**Comment by Vonfry** [comment]
Thanks for this pr. 

@zakame , would you like to wrap `Perl::LanguageServer` ?

**Comment by zakame** [comment]
@Vonfry yeah, let me update my stuff here and I'll post a PR soon

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 104663` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>perl530Packages.AnyEventAIO</li>
    <li>perl530Packages.IOAIO</li>
    <li>perl532Packages.AnyEventAIO</li>
    <li>perl532Packages.IOAIO</li>
  </ul>
</details>

**Pull request merged**
