### PR TITLE
github-copilot-cli: init at version 0.1.21

### PR DESCRIPTION
**Pull request by gunar**
###### Description of changes

https://githubnext.com/projects/copilot-cli/

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by gunar** [comment]
[The instructions](doc/languages-frameworks/javascript.section.md) tell me that, after calling `generate.sh`, I should execute `nix-build -A nodePackages.<new-or-updated-package>` but that's not working. I'm getting this error:

```
error: cannot evaluate a function that has an argument without a value ('pkgs')

       Nix attempted to evaluate a function as a top level expression; in
       this case it must have its arguments supplied either by default
       values, or passed explicitly with '--arg' or '--argstr'. See
       https://nixos.org/manual/nix/stable/expressions/language-constructs.html#functions.

       at /home/g/code/nixpkgs/pkgs/development/node-packages/default.nix:1:3:

            1| { pkgs, lib, nodejs, stdenv}:
             |   ^
            2|
```

**Comment by StepBroBD** [comment]
Seems like GitHub Copilot CLI got updated to 0.1.22 yesterday.

> error: cannot evaluate a function that has an argument without a value ('pkgs')

Please try `nix-build -A nodePackages."@githubnext/github-copilot-cli"`:

```
nix-build -A nodePackages."@githubnext/github-copilot-cli"                                                                                                                                                                                                                                                                                                                                                                                                                                                          
/nix/store/2sf80qlj4jf36djmw4i9ch73s3ha8m92-_at_githubnext_slash_github-copilot-cli-0.1.22
```

**Review by stepbrobd — APPROVED** [review]

**Comment by Alizter** [comment]
Result of `nixpkgs-review pr 221090` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>breitbandmessung</li>
    <li>teleprompter</li>
    <li>whalebird</li>
  </ul>
</details>
<details>
  <summary>28 packages failed to build:</summary>
  <ul>
    <li>python310Packages.batchspawner</li>
    <li>python310Packages.batchspawner.dist</li>
    <li>python310Packages.dockerspawner</li>
    <li>python310Packages.dockerspawner.dist</li>
    <li>python310Packages.jupyterhub</li>
    <li>python310Packages.jupyterhub-ldapauthenticator</li>
    <li>python310Packages.jupyterhub-ldapauthenticator.dist</li>
    <li>python310Packages.jupyterhub-systemdspawner</li>
    <li>python310Packages.jupyterhub-systemdspawner.dist</li>
    <li>python310Packages.jupyterhub-tmpauthenticator</li>
    <li>python310Packages.jupyterhub-tmpauthenticator.dist</li>
    <li>python310Packages.jupyterhub.dist</li>
    <li>python310Packages.oauthenticator</li>
    <li>python310Packages.oauthenticator.dist</li>
    <li>python311Packages.batchspawner</li>
    <li>python311Packages.batchspawner.dist</li>
    <li>python311Packages.dockerspawner</li>
    <li>python311Packages.dockerspawner.dist</li>
    <li>python311Packages.jupyterhub</li>
    <li>python311Packages.jupyterhub-ldapauthenticator</li>
    <li>python311Packages.jupyterhub-ldapauthenticator.dist</li>
    <li>python311Packages.jupyterhub-systemdspawner</li>
    <li>python311Packages.jupyterhub-systemdspawner.dist</li>
    <li>python311Packages.jupyterhub-tmpauthenticator</li>
    <li>python311Packages.jupyterhub-tmpauthenticator.dist</li>
    <li>python311Packages.jupyterhub.dist</li>
    <li>python311Packages.oauthenticator</li>
    <li>python311Packages.oauthenticator.dist</li>
  </ul>
</details>
<details>
  <summary>50 packages built:</summary>
  <ul>
    <li>antora</li>
    <li>balanceofsatoshis</li>
    <li>bitwarden-cli</li>
    <li>castnow</li>
    <li>code-server</li>
    <li>commitlint</li>
    <li>create-cycle-app</li>
    <li>emanote</li>
    <li>emanote.data</li>
    <li>epgstation</li>
    <li>fast-cli</li>
    <li>flexoptix-app</li>
    <li>google-clasp</li>
    <li>grafana-image-renderer</li>
    <li>haskellPackages.emanote</li>
    <li>haskellPackages.emanote.data</li>
    <li>haskellPackages.emanote.doc</li>
    <li>haskellPackages.tailwind</li>
    <li>haskellPackages.tailwind.doc</li>
    <li>joplin</li>
    <li>lighthouse</li>
    <li>morgen</li>
    <li>node2nix</li>
    <li>openmoji-black</li>
    <li>openmoji-color</li>
    <li>postcss-cli</li>
    <li>pulp</li>
    <li>quarto</li>
    <li>redoc-cli</li>
    <li>shepherd</li>
    <li>slack</li>
    <li>teams</li>
    <li>theLoungePlugins.plugins.closepms</li>
    <li>theLoungePlugins.plugins.giphy</li>
    <li>theLoungePlugins.themes.flat-blue</li>
    <li>theLoungePlugins.themes.flat-dark</li>
    <li>thelounge</li>
    <li>uppy-companion</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-sh</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.markdown-preview-nvim</li>
    <li>vscode</li>
    <li>vscode-extensions.matklad.rust-analyzer (vscode-extensions.rust-lang.rust-analyzer)</li>
    <li>vscode-fhs</li>
    <li>vscode-with-extensions</li>
    <li>vscodium</li>
    <li>vscodium-fhs</li>
    <li>wrangler</li>
    <li>zx</li>
  </ul>
</details>

**Comment by gunar** [comment]
Pardon my ignorance but when do we expect this PR to reach 22.11 so I can use it on my machine? Should I have opened a PR against `unstable` instead maybe so that I could use it sooner by importing it from https://github.com/NixOS/nixpkgs/archive/nixos-unstable.tar.gz?

**Comment by Luflosi** [comment]
When you make a PR against master, it will automatically reach the `unstable` channel after usually about a day, sometimes longer. It's already in the `unstable` channel: https://nixpk.gs/pr-tracker.html?pr=221090 and you can use it from there.
If you want this to be in the 22.11 release, you need to backport this PR, read the https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md document for that.

**Comment by gunar** [comment]
Thanks! I'm able to use this tool now. Awesome!

It seems then that this change to `pkgs/development/node-packages/main-programs.nix` didn't have the desired effect: https://github.com/NixOS/nixpkgs/pull/221090/files#diff-0f08eb17864401a903ab3bd4239a5bfc61a39a23d97351f1df7c09dab5a5df2dR23

Wondering what I did wrong there.

**Comment by StepBroBD** [comment]
i think you did everything correctly.

`pkgs/development/node-packages/main-programs.nix` is just telling nix package `"@githubnext/github-copilot-cli"` will produce an executable, and the executable name is `"github-copilot-cli"`.

**Comment by gunar** [comment]
Ah, got you. Indeed it works then. I could create an alias for the package I guess but this is fine for now. Thank you so much for your time @StepBroBD. You're awesome.

**Pull request merged**
