### PR TITLE
nixos/mbpfan: convert to structural settings

### PR DESCRIPTION
**Pull request by bb2020**
###### Motivation for this change

Documentation for the `conf` file is [here](https://github.com/linux-on-mac/mbpfan/blob/dd2c305593e43778f072f48e3f6331ba151548c9/mbpfan.conf).
Using ceiling temp values were resulting to higher CPU throttle instead of an increase in fan speed. Because of this issue, I've changed them to floor values.

According to documentation;
- `polling_interval` has been changed to 1. 
- `low_temp` has been changed to 55.
- `high_temp` has been changed to 58.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by aanderse — CHANGES_REQUESTED** [review]
Please `import` `mkRenamed...` for each option you have removed. Release notes might not be a bad idea either. Thanks!

**Comment by bb2020** [comment]
> Please `import` `mkRenamed...` for each option you have removed. Release notes might not be a bad idea either. Thanks!

Do you have any idea about why the chanelog is failing?

**Comment by bb2020** [comment]
> Please `import` `mkRenamed...` for each option you have removed. Release notes might not be a bad idea either. Thanks!

:+1:

**Comment by bb2020** [comment]
> Please `import` `mkRenamed...` for each option you have removed. Release notes might not be a bad idea either. Thanks!

:rocket:

**Review by aanderse — APPROVED** [review]
This is great!

**Comment by aanderse** [comment]
Sorry for the delay. Please rebase and I'll merge ASAP to avoid another conflict.

**Comment by bb2020** [comment]
> Sorry for the delay. Please rebase and I'll merge ASAP to avoid another conflict.

Rebased now.

**Comment by aanderse** [comment]
4 hours and there is another conflict already?! :rage:

**Comment by aanderse** [comment]
https://github.com/NixOS/nixpkgs/pull/155483

**Comment by bb2020** [comment]
> 4 hours and there is another conflict already?! rage Sorry for missing the mark on this... disappointed

:rofl:
My mistake. I shouldn't have appended it. Rebased again now.

**Pull request merged**
