### PR TITLE
maintainers-list: remove loveisgrief

### PR DESCRIPTION
**Pull request by JohnRTitor**
## Description of changes

Now a ghost user.

Cleanup of https://github.com/NixOS/nixpkgs/pull/339372

Requested in https://github.com/NixOS/nixpkgs/issues/339089

### CODE REVIEW

**Comment by JohnRTitor** [comment]
Since the user actually deleted their GitHub account, I think we should backport this change, along with https://github.com/NixOS/nixpkgs/pull/339372, to prevent Ofborg trying to ping a non-existing user.

**Review by donovanglover — APPROVED** [review]
Don't think this is important enough to backport.

**Comment by JohnRTitor** [comment]
Well it sends a wrong message that the package is maintained, potentially discouraging other maintainers wanting to pick it up. On search.nixos.org, it incorrectly links to a non-existing link/contact info.

**Review by SigmaSquadron — APPROVED** [review]
LGTM. Added a backport tag to the other PR.

**Pull request merged**
