### PR TITLE
Multiple buildkite agent support

### PR DESCRIPTION
**Pull request by Lucus16**
###### Motivation for this change

For a clearer diff: `git diff master:nixos/modules/services/continuous-integration/buildkite-agent.nix HEAD:nixos/modules/services/continuous-integration/buildkite-agents.nix`

Buildkite 3 supports multiple agents. We've patched nixpkgs to support this a while ago, but hadn't gotten around to contributing it back yet. There are still a few issues that I'd like opinions and/or contributions for:

- [ ] We removed the `buildkite2` package, I'm not sure if you're willing to do that at this time. The `buildkite-agent` module now forwards to the `buildkite-agents` which I believe is not compatible with `buildkite2`.
- [ ] The `meta-data` string option was removed in favor of the `tags` attrset option. The `openssh` options were removed in favor of the optional `sshKeyPath` option because there seems to be no point in requiring a public key and a private key might not always be necessary either. I believe this may break old configurations.

The initial five patches I've pushed runs in production on our servers, so they're fairly well tested, but if any changes are necessary, we may not be able to test them that easily.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Lucus16** [comment]
@grahamc @srhb I'd appreciate your opinions.

**Comment by yorickvP** [comment]
cc: @domenkozar

**Comment by domenkozar** [comment]
Not using buildkite anymore sorry :) cc @rvl

**Comment by rvl** [comment]
@Lucus16  This will be useful. It will need something added to the release notes though, especially for submodule options which have changed (such as `sshKeyPath`).

It needs a rebase so I tried rebasing the branch on nixos-unstable, but got this error when deploying:

```
building all machine configurations...
error: The option `services.buildkite-agent' in `/home/rodney/ops/nixpkgs/nixos/modules/services/continuous-integration/buildkite-agent.nix' is a prefix of options in `/home/rodney/ops/nixpkgs/nixos/modules/rename.nix'.
(use '--show-trace' to show detailed location information)
```

If I removed the change to `rename.nix`, then I could deploy multiple buildkite agents. I inspected the configs and they look OK.

Backward compatibility for a single-agent config looks good, but I wasn't able to test it.

The documentation string "Attribute set of extra agents." isn't very descriptive. For example, it doesn't say what the attr name does, because each agent entry also has a name.

**Comment by yorickvP** [comment]
`PermissionsStartOnly` is deprecated:  #53852

**Comment by Lucus16** [comment]
The change in rename does indeed need to be dropped. I've updated the documentation. Regarding the release note you asked for, is that supposed to go into `doc/release-notes.xml`, which hasn't been updated since 2012? Should I bump that version and effectively create release 0.15? Just to make sure it's fine if I arbitrarily create a new release like that?

**Comment by ivan** [comment]
For the author, reviewers, and committers: this PR was scanned and appears to add a use of the deprecated `types.string`, which emits a warning as of #66346. Before merging, please change this to another type, possibly:

- `types.str` for a single string where merging does not make sense, or cannot work
- `types.lines` for multi-line configuration or scripts where merging is possible
- `types.listOf types.str` for a mergeable list of strings

**Comment by flokli** [comment]
@Lucus16 the changes w.r.t. ssh keys make a lot of sense to me. Could you rebase this on latest master, and update the PR regarding `types.string` and `PermissionsStartOnly` usage?

**Comment by zimbatm** [comment]
We're using it on the nix-community org. /cc @adisbladis 

As long as there is a clear upgrade path, where errors can be resolved by reading the error message and following along, it's fine to break back-compat.

**Comment by flokli** [comment]
The whole structure moved from `services.buildkite-agent` to `services.buildkite-agents`, wo should be fine :-)

That being said, some of the assertions still show the old naming, and we'd still need some release notes.

**Comment by flokli** [comment]
Closing in favour of #68378.

**Comment by nh2** [comment]
Concluding comment because PR mentiones do not show up in notifications:

This was implemented in #78373.

**Pull request closed without merging**
