### PR TITLE
wvdial, wvstreams: init

### PR DESCRIPTION
**Pull request by flokli**
## Description of changes
This (re-)adds the wvdial package and wvstreams dependency.

They were initially removed as upstream was dead, and it could only build with an old openssl version.

However, there's a [patchset at openembedded](https://layers.openembedded.org/layerindex/recipe/190863/) that allows building it with a current set of libraries, and [Øl Telecom](https://bornhack.dk/bornhack-2023/villages/l-telecom-business-center/) also offered to maintain this over at [osmocom](https://gitea.osmocom.org/retronetworking/wvdial) in the future.

I successfully used `wvdialconf` to determine the modem parameters, and with this config:

```nix
  environment.wvdial = {
    dialerDefaults = ''
      Init2 = ATQ0 V1 E1 S0=0 &C1 &D2 +FCLASS=0
      Modem Type = Analog Modem
      ; Phone = <Target Phone Number>
      ISDN = 0
      ; Username = <Your Login Name>
      Init1 = ATZ
      ; Password = <Your Password>
      Modem = /dev/ttyUSB0
      Baud = 230400
    '';
  };
```

I was able to talk to the modem. Due to heavy rainfall, my ISP couldn't provide a cable connection in time, but I'm pretty convinced it'd work. I'd like to re-introduce this to nixpkgs, and actively maintain its packaging.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Lassulus** [comment]
wouldn't it be nicer to have another upstream instead of a bazillion patches?

**Comment by flokli** [comment]
> wouldn't it be nicer to have another upstream instead of a bazillion patches?

Yes, I think that's the long-term goal - having the osmocon being the new upstream and (most of) the patches merged.

**Comment by Lassulus** [comment]
so we merge for now with the patches and update later to the new upstream?

**Comment by flokli** [comment]
I think so, yes. Other distros also use that patchset. Once these patches are in a canonical upstream, we can switch our expression to build with sources from there.

**Review by Lassulus — APPROVED** [review]

**Pull request merged**
