### PR TITLE
flutter: 3.16.7 -> 3.19.0

### LINKED ISSUE #289170: Update request: flutter 3.16.7 → 3.19.0
- Package name: Flutter
- Latest released version: 3.19.0

- Current version on the unstable channel: 3.16.7
- Current version on the stable/release channel: 3.13.8

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@hacker1024 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by FlafyDev**
## Description of changes

Updates Flutter from 3.16.7 to 3.19.0
Fluffychat breaks from this change, so I'm locking it to flutter 3.16.

Also I noticed Flutter still works like normal with the patch `git-dir.patch` removed. I'm not sure what it's supposed to do but I don't think it's necessary anymore. It had conflicts when applying to 3.19.0, so I'm removing it in this PR.

fixes: #289170

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by FlafyDev** [comment]
Result of `nixpkgs-review pr 289534` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>27 packages built:</summary>
  <ul>
    <li>expidus.file-manager</li>
    <li>expidus.file-manager.debug</li>
    <li>expidus.file-manager.pubcache</li>
    <li>firmware-updater</li>
    <li>firmware-updater.debug</li>
    <li>firmware-updater.pubcache</li>
    <li>fluffychat</li>
    <li>fluffychat-web</li>
    <li>fluffychat-web.pubcache</li>
    <li>fluffychat.debug</li>
    <li>fluffychat.pubcache</li>
    <li>flutter</li>
    <li>flutter313</li>
    <li>flutter316</li>
    <li>hover</li>
    <li>intiface-central</li>
    <li>intiface-central.debug</li>
    <li>intiface-central.pubcache</li>
    <li>localsend</li>
    <li>localsend.debug</li>
    <li>localsend.pubcache</li>
    <li>rustdesk-flutter</li>
    <li>rustdesk-flutter.debug</li>
    <li>rustdesk-flutter.pubcache</li>
    <li>yubioath-flutter</li>
    <li>yubioath-flutter.debug</li>
    <li>yubioath-flutter.pubcache</li>
  </ul>
</details>

**Comment by FlafyDev** [comment]
Result of `nixpkgs-review pr 289534` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>23 packages built:</summary>
  <ul>
    <li>expidus.file-manager</li>
    <li>expidus.file-manager.debug</li>
    <li>expidus.file-manager.pubcache</li>
    <li>firmware-updater</li>
    <li>firmware-updater.debug</li>
    <li>firmware-updater.pubcache</li>
    <li>fluffychat</li>
    <li>fluffychat-web</li>
    <li>fluffychat-web.pubcache</li>
    <li>fluffychat.debug</li>
    <li>fluffychat.pubcache</li>
    <li>flutter (flutter319 ,flutterPackages.stable ,flutterPackages.v3_19)</li>
    <li>flutter313 (flutterPackages.v3_13)</li>
    <li>flutter316 (flutterPackages.v3_16)</li>
    <li>intiface-central</li>
    <li>intiface-central.debug</li>
    <li>intiface-central.pubcache</li>
    <li>localsend</li>
    <li>localsend.debug</li>
    <li>localsend.pubcache</li>
    <li>yubioath-flutter</li>
    <li>yubioath-flutter.debug</li>
    <li>yubioath-flutter.pubcache</li>
  </ul>
</details>

**Comment by FlafyDev** [comment]
I couldn't build rustdesk on aarch64-linux, skipped it in review

**Comment by FlafyDev** [comment]
@NixOS/flutter

**Review by mkg20001 — APPROVED** [review]

**Pull request merged**
