### PR TITLE
imagemagick: 7.1.1-19 -> 7.1.1-20

### PR DESCRIPTION
**Pull request by dotlambda**
## Description of changes
Diff: https://github.com/ImageMagick/ImageMagick/compare/7.1.1-19...7.1.1-20

Changelog: https://github.com/ImageMagick/Website/blob/main/ChangeLog.md

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dotlambda** [comment]
Should we just stop caring about the Perl package? It seems to break with every update.

**Comment by stigtsp** [comment]
> Should we just stop caring about the Perl package? It seems to break with every update.

Although some tests are failing - I'm not sure that perlPackages.ImageMagick is broken.

I'd be interested in looking at why the tests are failing though.

```
t/blob.t .......... Failed 1/1 subtests 
t/composite.t ..... Failed 2/18 subtests 
t/filter.t ........ Failed 5/58 subtests 
t/getattribute.t .. 1/25 Readimage: Exception 700: time limit exceeded `input.miff' @ fatal/cache.c/GetImagePixelCache/1707 at t/subroutines.pl line 938.
t/getattribute.t .. Failed 1/25 subtests 
t/montage.t ....... Readimage: Exception 700: time limit exceeded `#000000' @ fatal/cache.c/GetImagePixelCache/1707 at t/subroutines.pl line 997.
Fontconfig error: Cannot load default config file: No such file: (null)
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
t/montage.t ....... 1/19 Readimage: Exception 700: time limit exceeded `#00FF00' @ fatal/cache.c/GetImagePixelCache/1707 at t/subroutines.pl line 997.
Readimage: Exception 700: time limit exceeded `#800000' @ fatal/cache.c/GetImagePixelCache/1707 at t/subroutines.pl line 997.
Readimage: Exception 700: time limit exceeded `#008080' @ fatal/cache.c/GetImagePixelCache/1707 at t/subroutines.pl line 997.
Readimage: Exception 700: time limit exceeded `#008080' @ fatal/cache.c/GetImagePixelCache/1707 at t/subroutines.pl line 997.
t/montage.t ....... Failed 11/19 subtests 
t/ping.t .......... Failed 1/2 subtests 
t/read.t .......... 1/47 Readimage (input.avs): Exception 700: time limit exceeded `input.avs' @ fatal/cache.c/GetImagePixelCache/1707 at t/subroutines.pl line 317.
Readimage (input_rgb_lsb_08bit.mat): Exception 700: time limit exceeded `input_rgb_lsb_08bit.mat' @ fatal/cache.c/GetImagePixelCache/1707 at t/subroutines.pl line 317.
Readimage (reference/read/input_tga.miff): Exception 700: time limit exceeded `reference/read/input_tga.miff' @ fatal/cache.c/GetImagePixelCache/1707 at t/subroutines.pl line 334.
t/read.t .......... Failed 3/47 subtests 
t/setattribute.t .. 1/71 Readimage: Exception 700: time limit exceeded `input.miff' @ fatal/cache.c/GetImagePixelCache/1707 at t/subroutines.pl line 893.
SetImage: Exception 700: time limit exceeded `input.miff' @ fatal/cache.c/GetImagePixelCache/1707 at t/subroutines.pl line 898.
Readimage: Exception 700: time limit exceeded `input.miff' @ fatal/cache.c/GetImagePixelCache/1707 at t/subroutines.pl line 893.
t/setattribute.t .. Failed 1/71 subtests 
t/write.t ......... Failed 6/32 subtests 

Test Summary Report
-------------------
t/blob.t        (Wstat: 0 Tests: 1 Failed: 1)
  Failed test:  1
t/composite.t   (Wstat: 0 Tests: 18 Failed: 2)
  Failed tests:  1, 10
t/filter.t      (Wstat: 0 Tests: 58 Failed: 5)
  Failed tests:  1, 17, 32, 38, 54
t/getattribute.t (Wstat: 0 Tests: 25 Failed: 1)
  Failed test:  1
t/montage.t     (Wstat: 0 Tests: 19 Failed: 11)
  Failed tests:  1, 3, 5, 7, 9, 11-13, 15-16, 18
t/ping.t        (Wstat: 0 Tests: 2 Failed: 1)
  Failed test:  1
t/read.t        (Wstat: 0 Tests: 47 Failed: 3)
  Failed tests:  1, 14, 35
t/setattribute.t (Wstat: 0 Tests: 71 Failed: 1)
  Failed test:  40
t/write.t       (Wstat: 0 Tests: 32 Failed: 6)
  Failed tests:  1, 11, 16, 21, 26, 30
Files=9, Tests=273,  2 wallclock secs ( 0.05 usr  0.03 sys +  2.32 cusr  0.93 csys =  3.33 CPU)
Result: FAIL

```

**Comment by spiage** [comment]
I have error after this commit:
```
nix log /nix/store/a0jjpmyflz0pkghkbd9g5wkcwp1jxvz2-nixos-icons-2021-02-24.drv^*
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/fh54a9mjy598cagglf7rzkiqkj1mkyf0-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
build flags: SHELL=/nix/store/lf0wpjrj8yx4gsmw2s3xfl58ixmqk8qa-bash-5.2-p15/bin/bash DESTDIR=/nix/store/43nglpyy7ippgm99x44wcnw6bzash57f-nixos-icons-2021-02-24 prefix=
make -C icons
make[1]: Entering directory '/build/source/icons'
convert -background none -resize 16x16 ../logo/nix-snowflake.svg 16x16/apps/nix-snowflake.png
convert: time limit exceeded `../logo/nix-snowflake.svg' @ fatal/cache.c/GetImagePixelCache/1707.
make[1]: *** [Makefile:22: 16x16/apps/nix-snowflake.png] Error 1
make[1]: Leaving directory '/build/source/icons'
make: *** [Makefile:14: icons] Error 2
```

**Comment by stigtsp** [comment]
> ```
> convert -background none -resize 16x16 ../logo/nix-snowflake.svg 16x16/apps/nix-snowflake.png
> convert: time limit exceeded `../logo/nix-snowflake.svg' @ fatal/cache.c/GetImagePixelCache/1707.
> ```

This type of error is maybe the reason for the `perlPackages.ImageMagick` tests failing.

**Pull request merged**
