### PR TITLE
simp_le: 2016-02-06 -> 2016-04-17

### PR DESCRIPTION
**Pull request by groxxda**
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

**Needs #15370 !**

### CODE REVIEW

**Comment by zimbatm** [comment]
Travis error:

> Could not find a version that satisfies the requirement acme<0.6,>=0.4.1 (from simp-le==0) (from versions: )

**Comment by groxxda** [comment]
Yes, I probably should've written bigger in the PR:
**Needs #15370 ! **
:wink:

**Comment by zimbatm** [comment]
My bad :) It's looking good otherwise. Will merge as soon as the other one is good.

**Comment by zimbatm** [comment]
Perfect, thanks !

**Pull request merged**
