### PR TITLE
radicle-upstream: 0.2.3 → 0.2.9, enable on darwin

### PR DESCRIPTION
**Pull request by sikmir**
###### Motivation for this change
* [Changelog](https://github.com/radicle-dev/radicle-upstream/blob/master/CHANGELOG.md)
* Enable on darwin

###### Things done
- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by d-xo** [comment]
Apologies for the delayed review. This looks good and works great for me on nixos. Unfortunately I don't have access to a macos machine where I can test the new darwin version...

**Comment by happysalada** [comment]
There is a merge conflict. Would you be willing to have a look at it?
I have darwin and can test and merge when the change is done.

**Comment by gilescope** [comment]
@happysalada are we good to go now? The recent github outage has reminded people why these projects are important.

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 132367` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>radicle-upstream</li>
  </ul>
</details>

**Comment by happysalada** [comment]
All good, thank you for the PR!

**Pull request merged**
