### PR TITLE
factorio: 2.0.22 -> 2.0.23

### PR DESCRIPTION
**Pull request by Alexnortung**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by priegger** [comment]
I tested:
* factorio for a little (started a new game, walked around less than a minute, did not test and save games or similar)
* factoriio-space-age and factorio-headless (I upgraded my game server and connected to it, the running game still worked, I did not recognize any issues)

The experimental versions are now the same as the stable versions so I did not test anything there.

**Review by priegger — APPROVED** [review]

**Review by ChandlerSwift — APPROVED** [review]
Tested each; all appear to work fine.

**Comment by VuiMuich** [comment]
Experimental just got bumped to `2.0.24`, if you want to include that in this PR, here is the diff:
```diff
diff --git a/pkgs/by-name/fa/factorio/versions.json b/pkgs/by-name/fa/factorio/versions.json
index a39fbc165c7f..f3e99c6b153b 100644
--- a/pkgs/by-name/fa/factorio/versions.json
+++ b/pkgs/by-name/fa/factorio/versions.json
@@ -3,14 +3,14 @@
     "alpha": {
       "experimental": {
         "candidateHashFilenames": [
-          "factorio_linux_2.0.23.tar.xz"
+          "factorio_linux_2.0.24.tar.xz"
         ],
-        "name": "factorio_alpha_x64-2.0.23.tar.xz",
+        "name": "factorio_alpha_x64-2.0.24.tar.xz",
         "needsAuth": true,
-        "sha256": "3a3f27a5364d33896c8b35d352d0d2d6086b4ba98627eda71b26e57127309bfb",
+        "sha256": "6ec7a0badcf65d40aa51b168ae981bb0a6af3034b4428604e6a91504993741b8",
         "tarDirectory": "x64",
-        "url": "https://factorio.com/get-download/2.0.23/alpha/linux64",
-        "version": "2.0.23"
+        "url": "https://factorio.com/get-download/2.0.24/alpha/linux64",
+        "version": "2.0.24"
       },
       "stable": {
         "candidateHashFilenames": [
@@ -51,14 +51,14 @@
     "expansion": {
       "experimental": {
         "candidateHashFilenames": [
-          "factorio-space-age_linux_2.0.23.tar.xz"
+          "factorio-space-age_linux_2.0.24.tar.xz"
         ],
-        "name": "factorio_expansion_x64-2.0.23.tar.xz",
+        "name": "factorio_expansion_x64-2.0.24.tar.xz",
         "needsAuth": true,
-        "sha256": "8c6bb2c3afd198b8d5e1042f2babcb2db2d55645d1e84d9cfbba77cd83ae9e6a",
+        "sha256": "2319e98e2555974124b34e7364b2c67ad635531af92670a6625b400437d4acca",
         "tarDirectory": "x64",
-        "url": "https://factorio.com/get-download/2.0.23/expansion/linux64",
-        "version": "2.0.23"
+        "url": "https://factorio.com/get-download/2.0.24/expansion/linux64",
+        "version": "2.0.24"
       },
       "stable": {
         "candidateHashFilenames": [
@@ -75,15 +75,15 @@
     "headless": {
       "experimental": {
         "candidateHashFilenames": [
-          "factorio-headless_linux_2.0.23.tar.xz",
-          "factorio_headless_x64_2.0.23.tar.xz"
+          "factorio-headless_linux_2.0.24.tar.xz",
+          "factorio_headless_x64_2.0.24.tar.xz"
         ],
-        "name": "factorio_headless_x64-2.0.23.tar.xz",
+        "name": "factorio_headless_x64-2.0.24.tar.xz",
         "needsAuth": false,
-        "sha256": "e819fc9ad6df061bf9d4bffc91988dd18d0e3982c8b1c22c0525d78bda3ef216",
+        "sha256": "4644acc4195391fe19a7468c546d10a494ce1a188964c79f20cb0fa050b67120",
         "tarDirectory": "x64",
-        "url": "https://factorio.com/get-download/2.0.23/headless/linux64",
-        "version": "2.0.23"
+        "url": "https://factorio.com/get-download/2.0.24/headless/linux64",
+        "version": "2.0.24"
       },
       "stable": {
         "candidateHashFilenames": [

```

**Comment by priegger** [comment]
I'd prefer to have this merged as is, since it's already reviewed and tested. But I'm flexible there and someone with commit rights can decide. ;-)

**Pull request merged**
