### PR TITLE
[23.11] {citra,yuzuPackages}: remove package

### PR DESCRIPTION
**Pull request by shyim**
## Description of changes

Cherry-Pick of https://github.com/NixOS/nixpkgs/pull/293312

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by eclairevoyant** [comment]
Seems there's still `pkgs/applications/emulators/yuzu/sources.nix` present

**Comment by shyim** [comment]
Thanks for the hint. @eclairevoyant it's now fixed

**Comment by eclairevoyant** [comment]
Shouldn't that change be associated with the yuzu commit?

**Review by Atemu — CHANGES_REQUESTED** [review]
As explained in https://github.com/NixOS/nixpkgs/pull/293312#issuecomment-1994127648, I see no good reason to break here and the removal in master warrants further discussion too.

**Comment by thiagokokada** [comment]
I for one concur with @Atemu here that we shouldn't backport package removal to stable releases unless there is a really good reason to do so (e.g.: a known security issue that can't be fixed otherwise).

**Pull request closed without merging**
