### PR TITLE
make-derivation: enable pie hardening with musl

### LINKED ISSUE #49071: `ld.gold` crashes or produces invalid executables when Musl is used as a libc
## Issue description

`ld.gold` crashes or produces invalid executables when using the musl libc. This prevents the use of musl and GHC on `armv7l` since GHC requires `ld.musl` on that platform to work around https://sourceware.org/bugzilla/show_bug.cgi?id=16177

### Steps to reproduce

```sh
nix-build -E 'let pkgs = (import <nixpkgs> {}).pkgsMusl; in pkgs.hello.overrideDerivation(_: {CFLAGS="-fuse-ld=gold";})'
```

The above command either fails (on a bare-metal x86_64 system) or produces an executable which segfaults at start (on a x86_64 system running on VM in a laptop). Interestingly, if one passes `-static_libgcc` the produced executable is apparently correct inside the VM but also crashes on the bare-metal machine.

## Technical details

```
$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.78, NixOS, 18.09.1007.f8d156f44fb (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1pre6377_954d1f4d`
 - channels(root): `"nixos-18.09.1007.f8d156f44fb"`
 - channels(alberto): `"nixos-18.03pre120031.7ebacd1a43, nixpkgs-18.03pre119383.eafd703a63"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
The above system is the desktop bare-metal one

### PR DESCRIPTION
**Pull request by matthewbauer**
Fixes #49071

### CODE REVIEW

**Comment by FRidh** [comment]
Please describe in the commit what it fixes instead of just referring to an issue.

**Comment by matthewbauer** [comment]
Thanks- updated.

**Comment by dtzWill** [comment]
Would it make sense to enable PIE by default? Or rather, what's the reason we don't do this always?

Is performance the concern or breakage (or ...)?

Performance seems like a bad reason, don't other distributions enable by default? Such a trade-off seems like it should be opt-in, but regardless first it'd be good to sort out what the reason is before disagreeing with it :P.

**Comment by matthewbauer** [comment]
I am thinking of just doing this for now as it avoid a mass rebuild. If someone wants to try enabling PIE globally, that would be great. It will just probably be on you to debug any of the new failures.

**Comment by dtzWill** [comment]
Sound good, sorry didn't mean to make that your problem/job.... just
surprised we don't already :).

**Comment by dtzWill** [comment]
I'm seeing this break musl immediately?

https://gist.github.com/dtzWill/d93dc2211fd2d134a81cd858311f42ce

`nix build nixpkgs.pkgsMusl.bash`, dies building bootstrap compiler

What sort of builds does this not break (and presumably improves behavior for)?

Checking behavior across branches presently...

@GrahamcOfBorg build pkgsMusl.bash

**Comment by matthewbauer** [comment]
That should be fixed in 2e2afa1943a69cef6abb96a8552ddafd06f9bbd4. Hoping binutils/gcc are the only ones.

**Comment by dtzWill** [comment]
Additional failures:

* glibc
* ghc

I'm a fan of this but this looks like it was merged too eagerly and wasn't... tested at all? Including checking if the original issue was fixed since build fails long before that point AFAICT.
Unfortunately I think our testing bandwidth is thin currently, so I'm not sure how to proceed.  Maybe whack-a-mole the next few failures and cross our fingers? I'd like to avoid a revert :).

FWIW here's a few packages that no one's obligated to support BUT I build regularly and so they work reasonably well as oracles, even if they're not intended to be such:
* pkgsMusl.cachix
* pkgsMusl.nix (pkgsMusl.nixUnstable)
* pkgsMusl.llvmPackages_{5,6,7}.{llvm,clang}
Just in case that helps -- maybe we can put together a musl jobset at some point :).  (and contribute builders :))

**Comment by dtzWill** [comment]
glibc is just an addition to hardeningDisable, ghc is a bit trickier.  Currently testing this: https://github.com/dtzWill/nixpkgs/commit/0caf0a39fec296df9e59dfa368c72a5d3703317f (will report back in an hour or however long ghc takes :P).

**Comment by dtzWill** [comment]
Nope, looks like problem is with bootstrap ghc not being built -fPIC -- so either new bootstrap tarball (eep) or maybe just disable PIE for ghc? Shame b/c it might be nice to use gold linker with it...

**Comment by matthewbauer** [comment]
Yeah i was probably too quick with this! Sorry about that. I didn’t think pie could break so much. Feel free to revert it (but leave in the hardeningDisable flags for future reference).

**Comment by matthewbauer** [comment]
I would say just disable PIE for ghc. There's some weird stuff ghc bootstrapping does that makes this stuff complex. We have to do some weird patches to get this working on Android:

https://github.com/reflex-frp/reflex-platform/blob/develop/nixpkgs-overlays/mobile-ghc/8.2.y/android-patches/force-relocation-equal-pic.patch

We do have a cross-trunk jobset with some musl jobs:

https://hydra.nixos.org/jobset/nixpkgs/cross-trunk#tabs-jobs

Maybe we should add cachix to it?

**Comment by nh2** [comment]
Related problem with writeup: https://github.com/NixOS/nixpkgs/issues/129247#issuecomment-873612621

**Pull request merged**
