### PR TITLE
apacheHttpdPackages.mod_tile: init at unstable-2017-01-08

### PR DESCRIPTION
**Pull request by jglukasik**
###### Motivation for this change

Continuing my OSM tools packaging. Changes to the httpd nixos service to "enableTile" like you can "enablePerl" will be coming later, i thought it would be best to do just the nixpkgs for now.

A release for this package hasn't been cut in a long time, so i'm following the naming convention for specifying the latest commit as documented here: https://nixos.org/nixpkgs/manual/#sec-package-naming

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by aanderse** [comment]
This is an obscure module compared to `mod_perl` so I woulda just recommend documenting how to enable it via the `extraModules` option. Personally I've been trying to cut down on tyre code in that module and clean it up as it's fairly difficult to understand for those new to the nix language.

**Comment by aanderse** [comment]
@GrahamcOfBorg build apacheHttpdPackages.mod_tile
@jglukasik do you have a configuration snippet on how you tested this?

**Comment by jglukasik** [comment]
Sorry for the delay, and thanks for getting my attention back on this; I realized my `maintainers` line had an issue (I copied it in a different place that had `inherit (stdenv.lib) maintainers` at the top of the file). Just updated my commit with that fix ( `+  meta = with stdenv.lib; {` )

As for a config snippet, I've been using the following (real url replaced with XXXX here)
```
services = {
    httpd = {
       enable = true;
       adminAddr = "fake@XXXX.com";
       hostName = "XXXX.com";
       extraModules = [
         { name = "tile"; path = "${pkgs.apacheHttpdPackages.mod_tile}/modules/mod_tile.so"; }
       ];
    };
};
```

This should enable a debug page at `/mod_tile`, which i confirm by running:
```
jgl@xps ~ $ curl XXXX.com/mod_tile
NoResp200: 0
NoResp304: 0
NoResp404: 0
NoResp503: 0
NoResp5XX: 0
NoRespOther: 0
NoFreshCache: 0
NoOldCache: 0
NoVeryOldCache: 0
NoFreshRender: 0
NoOldRender: 0
NoVeryOldRender: 0
NoRespZoom00: 0
NoTileBufferReads: 0
DurationTileBufferReads: 0
NoTileBufferReadZoom00: 0
DurationTileBufferReadZoom00: 0
jgl@xps ~ $ 
```

**Comment by aanderse** [comment]
@GrahamcOfBorg build apacheHttpdPackages.mod_tile

**Review by aanderse — APPROVED** [review]
Compiles and runs as described for me. :+1:

**Pull request merged**
