### PR TITLE
firmware-linux-nonfree: update to master

### PR DESCRIPTION
**Pull request by zimbatm**
New binary blobs for the XPS 13 bluetooth radio

### CODE REVIEW

**Comment by fpletz** [comment]
You also have to update the version attribute with the current date. :)

**Comment by zimbatm** [comment]
@fpletz good catch, I put the date of the commit is that alright ?

**Comment by vcunat** [comment]
Yes. I don't really understand what's the meaning of other branches than master, e.g. https://github.com/wkennington/linux-firmware/commits/2016-01-26. @wkennington might be best able to explain that, but he seems to have forked off nixpkgs completely, even calling the OS ["Triton"](https://github.com/triton) now and not contributing to the official repo anymore. (Perhaps /cc @copumpkin due to related discussions.)

**Comment by jagajaga** [comment]
@vcunat I know that he doesn't "like" us anymore.

**Comment by fpletz** [comment]
Oh, interesting! I'm gonna bump this to the current state of https://github.com/wkennington/linux-firmware/commits/2016-01-26 because there are new versions for my iwlwifi card that depending on the kernel version sometimes causes the kernel to initialize the card up to one minute after boot which causes the wpa_supplicant service to fail on boot.

**Comment by wkennington** [comment]
Yes, you want to use the dated branches as they are a merge of iwlwifi and
linux-firmware periodically.

**Comment by fpletz** [comment]
Thanks for the clarification!

**Pull request merged**
