### PR TITLE
Resilio sync configuration fix and NixOS test

### PR DESCRIPTION
**Pull request by danieldk**
###### Motivation for this change

This change bundles two commits:

- The first commit fixes an error in the configuration when `directoryRoot` is used. The option was placed in the wrong section for current versions of Resilio Sync.
- The second commit adds tests for Resilio Sync. This test would have caught the configuration error solved in the first commit.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by danieldk** [comment]
Since Resilio Sync is unfree, I was not sure if a test could be added. If not, I will remove the test from this PR.

**Comment by danieldk** [comment]
@grahamcofborg test resilio

**Comment by danieldk** [comment]
@GrahamcOfBorg test resilio

**Comment by danieldk** [comment]
If tests for non-free packages are not possible, I can do a new PR containing just the bug fix for the Resilio Sync module.

**Comment by yesbox** [comment]
The Nixpkgs manual explains, "Note that we are not able to test or build unfree software on Hydra due to policy. Most unfree licenses prohibit us from either executing or distributing the software.".

That doesn't mean we can't have a unfree test or that a unfree test isn't useful. It's usefulness would be limited due to no Hydra, but if run manually when making changes it's still useful.

Does anyone want to please merge this?

**Comment by netvl** [comment]
Hello,

I was going to report the bug about `directoryRoot`, but apparently it is already a known issue. This prevents me from configuring rslsync correctly. Any chance of getting this merged? Thanks!

**Comment by danieldk** [comment]
@yesbox @netvl The best way to get this merge is to review the PR and once you are done post in

https://discourse.nixos.org/t/prs-already-reviewed/2617

**Comment by danieldk** [comment]
Rebased, also updated the test script to Python.

Ping `resilio-sync` maintainers: @domenkozar @thoughtpolice @cwoac

**Pull request closed without merging**
