### PR TITLE
Gx

### PR DESCRIPTION
**Pull request by zimbatm**
###### Motivation for this change

Adds `gx` and `gx-go` which are used to build `go-ipfs`. `go-ipfs` hasn't been updated yet because I need to figure out how to build a `ipfsfetch` properly.

Unlike #15914 `gx` doesn't provide a wrapper, you have to have both `gx` and `gx-go` in your path if you want to use them together.
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by rardiol** [comment]
I don't think a fetchipfs is strictly necessary. From gx's requirements "Users are encouraged to have a running IPFS daemon of at least version 0.4.0 on their machines. **If not present, gx will use the public gateway**. If you wish to publish a package, a local running daemon is a hard requirement." So I think we just need some sort of integration of nix with gx.

**Comment by kamilchm** [comment]
@zimbatm @domenkozar is there a Nix package style guide that says something about `meta`?

**Comment by zimbatm** [comment]
Not officially but I should have added myself as the maintainer. Also packages who are missing meta.platforms are not built by hydra.

**Comment by zimbatm** [comment]
Fixed in da253439ed6399f8315ee30a7b8dd32d68c7d088

**Pull request merged**
