### PR TITLE
telegram-desktop: 4.7.1 -> 4.8.0

### PR DESCRIPTION
**Pull request by NickCao**
Release note: https://github.com/telegramdesktop/tdesktop/releases/tag/v4.8.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Scrumplex** [comment]
PR title has a type :sweat_smile:

**Review by drupol — APPROVED** [review]

**Comment by NickCao** [comment]
For reviewers: I don't know how to test the change in webkitgtk, specifically which part of tdesktop uses webkitgtk, please provide some guidance if you happen to know.

**Comment by yu-re-ka** [comment]
> For reviewers: I don't know how to test the change in webkitgtk, specifically which part of tdesktop uses webkitgtk, please provide some guidance if you happen to know.

https://core.telegram.org/bots/webapps

> To see a Web App in action, try our sample [@DurgerKingBot](https://t.me/durgerkingbot).

**Comment by yu-re-ka** [comment]
It crashes when testing the example webapp with `Segmentation fault (core dumped)`.

Though even before the webkitgtk update it also didn't work properly.

**Comment by NickCao** [comment]
> It crashes when testing the example webapp with `Segmentation fault (core dumped)`.
> 
> Though even before the webkitgtk update it also didn't work properly.

Looks like a qtwayland issue, it does not crash under xwayland, page does not load though.

**Comment by SuperSandro2000** [comment]
> To see a Web App in action, try our sample [@DurgerKingBot](https://t.me/durgerkingbot).

Doesn#t work for me 
image


With the current version of telegram on master I get a segfault.

```
 ➜ sudo -E strace $(which telegram-desktop)
execve("/etc/profiles/per-user/sandro/bin/telegram-desktop", ["/etc/profiles/per-user/sandro/bi"...], 0x7ffd805d25d0 /* 179 vars */) = 0
brk(NULL)             = 0xe43000
arch_prctl(0x3001 /* ARCH_??? */, 0x7ffdeee9ac40) = -1 EINVAL (Invalid argument)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x8} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault
```

**Comment by NickCao** [comment]
Tried again with `webkitgtk_4_1` instead of  `webkitgtk_6_0` yet with no luck.

**Comment by NickCao** [comment]
Looks like we are in exactly the same situation as https://github.com/telegramdesktop/tdesktop/issues/24953

**Review by yu-re-ka — APPROVED** [review]
If this change does not make the webkit integration situation _worse_ than it is on master, I see no reason to delay the update.
The webkit integration issue can be tracked and fixed separately.

**Pull request merged**
