### PR TITLE
musescore: 2.3.2 -> 3.0

### PR DESCRIPTION
**Pull request by suhr**
- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by suhr** [comment]
@vandenoever

**Comment by worldofpeace** [comment]
@suhr You forgot to change the [`sha256`](https://github.com/NixOS/nixpkgs/blob/cd4d2388e3189dff37cd9d34a4d78c16b9bcaeff/pkgs/applications/audio/musescore/default.nix#L15).

This value can easily be retrieved by replacing it with a false hash like
```
0000000000000000000000000000000000000000000000000000
```
and then getting the correct hash from the output in your terminal when you build this.

**Comment by worldofpeace** [comment]
##### [Link To Release Notes](https://musescore.org/en/3.0)
###### For those interested

**Comment by suhr** [comment]
r?

**Comment by worldofpeace** [comment]
@GrahamcOfBorg build musescore

**Comment by worldofpeace** [comment]
Currently fails to build https://logs.nix.ci/?key=nixos/nixpkgs.52835&attempt_id=043dab25-345b-4cce-af09-58caa5f2491f

Needs investigation.

**Comment by veprbl** [comment]
@GrahamcOfBorg build musescore

**Comment by worldofpeace** [comment]
Thanks @veprbl  for fixing the build :sparkles:

**Pull request merged**
