### PR TITLE
Revert "stdenv: set NIX_DONT_SET_RPATH_FOR_TARGET on Darwin"

### PR DESCRIPTION
**Pull request by reckenrode**
This reverts commit 10c87ee2c7661b0e699b270744439b2643aaa43b.

Fixes https://github.com/NixOS/nixpkgs/issues/355622.

@emilazy @sternenseemann 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by reckenrode** [comment]
Before the revert:
```shell
$ nix-instantiate . -A pkgsCross.gnu64.pkgsBuildBuild.jq
/nix/store/idydjykv86f3wzy87jrx0pf8rzf08hmq-jq-1.7.1.drv!bin
$ nix-instantiate . -A pkgsCross.gnu64.pkgsBuildHost.jq
/nix/store/ay9bsvb6vslgi0xqmvmyfwczmnyzkqv3-jq-1.7.1.drv!bin
```

After the revert:
```shell
$  nix-instantiate . -A pkgsCross.gnu64.pkgsBuildBuild.jq
/nix/store/p3b6czc6y9ba6la6kf8j9bx6rpm3gcw4-jq-1.7.1.drv!bin
$ nix-instantiate . -A pkgsCross.gnu64.pkgsBuildHost.jq
/nix/store/p3b6czc6y9ba6la6kf8j9bx6rpm3gcw4-jq-1.7.1.drv!bin
```

**Comment by reckenrode** [comment]
I guess technically this is breaking because it changes the semantics of Darwin as a target platform, but not reverting on 24.11 would keep this major regression for cross-compilation until 25.05.

@RossComputerGuy Thoughts?

**Review by RossComputerGuy — APPROVED** [review]

**Review by emilazy — COMMENTED** [review]
Looks good in principle but can we maybe update the comment here to be more useful about our current motivation to not uncomment it, or at least add some detail in the commit message?

**Comment by szlend** [comment]
Is it still possible to get this in time for 24.11? It's a pretty big regression for cross-compilation.

**Review by szlend — APPROVED** [review]

**Comment by emilazy** [comment]
Not in time for the initial release (unless we delay it, which seems unlikely for cross), but given the release manger has approved it, it will go in the first `staging-24.11` backport cycle.

**Review by emilazy — APPROVED** [review]

**Comment by emilazy** [comment]
Would still like to see the comment and/or commit message updated, but otherwise will merge within a day or two.

**Comment by reckenrode** [comment]
I pushed an additional commit clarifying the nature of the mass rebuilds.

**Pull request merged**
