### PR TITLE
Mesa 24.3.1

### PR DESCRIPTION
**Pull request by K900**
## Description of changes

So we can test the libgbm changes.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by K900** [comment]
@NixOS/nixpkgs-vet another weird-ish failure mode: libgbm uses common.nix from Mesa, so it can't really go into by-name. I'm not sure if that's viable to detect statically though.

**Comment by philiptaron** [comment]
> @NixOS/nixpkgs-vet another weird-ish failure mode: libgbm uses common.nix from Mesa, so it can't really go into by-name. I'm not sure if that's viable to detect statically though.

Yeah, these cases just need to grin and bear it right now. `nixpkgs-vet` doesn't know how to simulate what _would_ happen if you did the migration. If it did that, it would see another error resulting from use of common.nix from another package directory.

One way to move `libgbm` and comply with these checks would be to depend on `mesa` and use the `src`, `meta`, etc properties from that derivation.

**Comment by K900** [comment]
The whole point of this setup is to allow separately bumping Mesa on Darwin, Linux and libgbm, so I'd rather not tie it that closely. I guess we can just keep this.

**Comment by philiptaron** [comment]
> I guess we can just keep this.

Yeah, that's a fine call to make. One of the reasons we used a [ratchet check](https://qntm.org/ratchet) was to let you do that if you need to, but strongly encourage the whole ecosystem to find other ways of doing things.

**Comment by K900** [comment]
Actually maybe we can pull this apart entirely, I've got ideas now.

**Comment by PedroHLC** [comment]
Passing by to (1) now with 24.3.0 released, put this draft PR back in top of the search results, (2) as a reminder for people considering opening a PR themselves that we always wait `Y.Q.1` before adding it to master.

**Comment by K900** [comment]
Rebased to 24.3.0, the libgbm changes diverged extremely hard and basically need a whole new pass.

**Comment by K900** [comment]
The treewide is back, Mesa 24.3.1 should be later today and then I plan to send it.

**Comment by trofi** [comment]
Bisect claims that d209d800b7df2d4b05ea1266b14a47cba5da129b `treewide: mesa -> libgbm (where appropriate)` broke `xwayland` build in `staging` and `staging-next` as:

```
$ nix build --no-link -f. -L xwayland
...
xwayland> Run-time dependency dri found: NO (tried pkgconfig)
xwayland> include/meson.build:9:10: ERROR: Dependency "dri" not found, tried pkgconfig
xwayland> A full log can be found at /build/xwayland-24.1.4/build/meson-logs/meson-log.txt
```

**Comment by K900** [comment]
Yeah, I think it also needs the stub. Give me a minute.

**Comment by fabianhjr** [comment]
https://github.com/NixOS/nixpkgs/pull/366034

@K900

**Comment by trofi** [comment]
The d209d800b7df2d4b05ea1266b14a47cba5da129b change also broke `enlightenment.efl`. Proposed the fix as:
- https://github.com/NixOS/nixpkgs/pull/373308

**Pull request merged**
