### PR TITLE
libinput: 1.10.3 -> 1.11.0

### PR DESCRIPTION
**Pull request by colemickens**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jtojnar** [comment]
Release notes: https://lists.freedesktop.org/archives/wayland-devel/2018-June/038349.html

**Comment by Mic92** [comment]
Is ~3000 packages enough for staging?

**Review by lukateras — APPROVED** [review]

**Comment by colemickens** [comment]
How does `staging` work? When will this commit appear in master?

**Comment by colemickens** [comment]
Weird, I guess I have this in `channels/nixos-unstable` now and didn't notice?

**Pull request merged**
