### PR TITLE
 llvmPackages: add overrideable withLibunwind

### PR DESCRIPTION
**Pull request by ghost**
See #170850

### CODE REVIEW

**Comment by AndersonTorres** [comment]
Closing as dead, unmergeable shit

**Comment by rrbutani** [comment]
@AndersonTorres why do you think this is dead/unmergable?

**Comment by ehmry** [comment]
Whatever, `llvmPackages` is messy but if it works don't break it.

**Comment by AndersonTorres** [comment]
> @AndersonTorres why do you think this is dead/unmergable?

I don't think, it is: Github interface says this can't be merged because conflicts with current codebase.

Further, this PR is 5 months old. It is rotting!

**Comment by zimbatm** [comment]
@AndersonTorres please be more respectful of other people's work. This is the second time that one of your messages got reported to the moderation team. Please DM me if you have any questions.

**Pull request closed without merging**
