### PR TITLE
nixos/pulseaudio: Set speex-float-5 as default resample-method

### PR DESCRIPTION
**Pull request by adisbladis**
The upstream default (speex-float-1) results in audible artifacts

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by worldofpeace** [comment]
Seems there is a reason why they've left this at 1
* https://gitlab.freedesktop.org/pulseaudio/pulseaudio/issues/310#note_44616

Also
> https://lists.freedesktop.org/archives/pulseaudio-discuss/2014-August/021362.html
> It's quite sad that the current default in PulseAudio was influenced by 
the needs of low-power embedded devices at the measurable expense of the 
sound quality on the typical desktop. Now, with plots, figures and 
knowledge in hand, we can fix it.

**Review by worldofpeace — APPROVED** [review]
I've never particularly cared for this default and had it at `speex-float-5` anyway. 
(like many of their defaults :smile: )

It's a good choice, at the cost of low powered embedded devices.

**Review by fpletz — APPROVED** [review]
Agree with @worldofpeace. Thanks for the links!

Since we support running NixOS on low-end ARM hardware, I suggest we mention this change in the release notes though.

**Comment by worldofpeace** [comment]
> Since we support running NixOS on low-end ARM hardware, I suggest we mention this change in the release notes though.

Sounds good.

**Comment by worldofpeace** [comment]
Added a release note.

**Pull request merged**
