### PR TITLE
rabbitmq-server: switch to python3

### PR DESCRIPTION
**Pull request by armeenm**
###### Description of changes
Appears to work fine using python3 in the build process.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by turion** [comment]
In principle great, but for some reason this broke the `x86_64-darwin`-build. I think this used to work:
https://hydra.nixos.org/build/174137098

Do you understand why?

**Comment by turion** [comment]
@build rabbitmq-server

**Comment by armeenm** [comment]
Looks like make segfaults; strange. Unfortunately, I don't have access to a Mac to examine further.

**Comment by turion** [comment]
I don't think `make` itself segfaults, but the process it spawns, here: https://github.com/rabbitmq/rabbitmq-server/blob/fd923677ec9045fbc77e1b9750c2ee2f115342ee/Makefile#L61

**Comment by reckenrode** [comment]
Result of `nixpkgs-review pr 169684` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>rabbitmq-server</li>
  </ul>
</details>

**Comment by reckenrode** [comment]
Seems this only fails on x86_64-darwin. When I use `nix develop` and run `make` manually, I get the following (more descriptive, maybe) error.

```
$ make
 GEN    deps/.hex/cache.ets
{"init terminating in do_boot",{{badmatch,{error,{file_error,"deps/.hex/cache.ets",eacces}}},[{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,450}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,123}]},{init,start_it,1,[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({{badmatch,{error,{file_error,[_],eacces}}},[{erl_eval,expr,5,[{_},{_}]},{erl_eval,exprs,5,[{_},{_}]},{init,start_it,1,[]},{init,start_em,1,[]},{init,do_boot,3,[]}]})

Crash dump is being written to: erl_crash.dump...make: *** [Makefile:61: deps/.hex/cache.ets] Error 1
```

**Comment by reckenrode** [comment]
Running `make --trace`, I get the following command as the source of the crash.

```
erl +A1 -noinput -boot no_dot_erlang  -pz /private/tmp/nix-build-rabbitmq-server-3.9.14.drv-0/rabbitmq-server-3.9.14/.erlang.mk/rebar/ebin -eval "  In = \"deps/.hex/cache.erl\",  Out = \"deps/.hex/cache.ets\",  {ok, [Props, Entries]} = file:consult(In),  Name = proplists:get_value(name, Props),  Type = proplists:get_value(type, Props),  Access = proplists:get_value(protection, Props),  NamedTable = proplists:get_bool(named_table, Props),  Keypos = proplists:get_value(keypos, Props),  Heir = proplists:get_value(heir, Props),  ReadConc = proplists:get_bool(read_concurrency, Props),  WriteConc = proplists:get_bool(write_concurrency, Props),  Compressed = proplists:get_bool(compressed, Props),  Options0 = [    Type,    Access,    {keypos, Keypos},    {heir, Heir},    {read_concurrency, ReadConc},    {write_concurrency, WriteConc}],  Options1 = case NamedTable of    true  -> [named_table | Options0];    false -> Options0  end,  Options2 = case Compressed of    true  -> [compressed | Options0];    false -> Options0  end,  Tab = ets:new(Name, Options2),  [true = ets:insert(Tab, Entry) || Entry <- Entries],  ok = ets:tab2file(Tab, Out),  init:stop()."
```

**Comment by reckenrode** [comment]
Does Hydra try to build x86_64-darwin packages on aarch64-darwin? This builds for me on an actual x86_64-darwin machine, but it fails when building for x86_64-darwin on my aarch64-darwin MBP.

Interestingly, `erlang` is listed under `buildInputs`, but it appears to be pulling in the aarch64-darwin version even when I specify `--system x86_64-darwin`.  The path to erl is:
* `/nix/store/nvngkn9yj4gx1b5jxfallzrxk2vi7l21-erlang-24.2/bin/erl`, which wraps
* `/nix/store/nvngkn9yj4gx1b5jxfallzrxk2vi7l21-erlang-24.2/lib/erlang/bin/.erl-wrapped`, which wraps
* `/nix/store/nvngkn9yj4gx1b5jxfallzrxk2vi7l21-erlang-24.2/lib/erlang/erts-12.2/bin/erlexec`.

```
$ file /nix/store/nvngkn9yj4gx1b5jxfallzrxk2vi7l21-erlang-24.2/lib/erlang/erts-12.2/bin/erlexec
/nix/store/nvngkn9yj4gx1b5jxfallzrxk2vi7l21-erlang-24.2/lib/erlang/erts-12.2/bin/erlexec: Mach-O 64-bit executable arm64
```

That doesn’t seem right, but I’m not familiar with erlang or how it handles cross-compilation (for x86_64-darwin from aarch64-arwin). However, my expectation is it would use the x86_64-darwin erlang rather than the aarch64 one.

**Comment by reckenrode** [comment]
Result of `nixpkgs-review pr 169684` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>rabbitmq-server</li>
  </ul>
</details>

**Comment by reckenrode** [comment]
If I move `elixir` and `erlang` to `depsBuildBuild`, it uses the x86_64-darwin version of erlang, but now it segfaults instead. 😂

**Comment by turion** [comment]
Thanks a lot! So we can rest assured that this is not caused by this PR here? In https://hydra.nixos.org/build/174137098 it still worked, so it probably broke on some other commit in between.

**Comment by reckenrode** [comment]
> Thanks a lot! So we can rest assured that this is not caused by this PR here? In https://hydra.nixos.org/build/174137098 it still worked, so it probably broke on some other commit in between.

Correct. I don’t think this PR is responsible for the breakage. I suspect `erlang` and `elixir` should probably be in `depsBuildBuild`, but I’d want someone who understands the finer points of dependencies better than I to confirm.

The segfault appears to be a problem with the Erlang derivation running under Rosetta 2.

Native x86_64 iMac:
```
$ uname -a
Darwin iMac 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64 i386 iMac18,3 Darwin
$ nix shell github:NixOS/nixpkgs#erlang -c erl -eval 'erlang:display(erlang:system_info(system_architecture)), halt().'  -noshell
"x86_64-apple-darwin17.7.0"
```

Native aarch64 MBP (without and with Rosetta 2):
```
$ uname -a
Darwin natalia 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64 arm64 MacBookPro18,2 Darwin
$ nix shell github:NixOS/nixpkgs#erlang -c erl -eval 'erlang:display(erlang:system_info(system_architecture)), halt().'  -noshell
"aarch64-apple-darwin21.3.0"
$ nix shell --system x86_64-darwin github:NixOS/nixpkgs#erlang -c erl -eval 'erlang:display(erlang:system_info(system_architecture)), halt().'  -noshell
fish: Job 1, 'nix shell --system x86_64-darwi…' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by turion** [comment]
Awesome, then we can merge this PR and I'll open a separate issue.

**Pull request merged**
