### PR TITLE
[Backport release 24.05] vencord: 1.10.2 -> 1.10.5

### PR DESCRIPTION
**Pull request by 4evy**
Backports:
https://github.com/NixOS/nixpkgs/pull/345423
https://github.com/NixOS/nixpkgs/pull/347442
https://github.com/NixOS/nixpkgs/pull/350964

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by DontEatOreo** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 351216`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 3 packages built:</summary>
  <ul>
    <li>vencord</li>
    <li>vencord-web-extension</li>
    <li>webcord-vencord</li>
  </ul>
</details>

**Comment by DontEatOreo** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 351216`

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>vencord</li>
    <li>vencord-web-extension</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>vencord</li>
    <li>vencord-web-extension</li>
  </ul>
</details>

**Review by NotAShelf — APPROVED** [review]
LGTM

**Review by Scrumplex — APPROVED** [review]
changes LGTM

**Comment by DontEatOreo** [comment]
I'm little bit confused. In 9744efc3b0b81a8a71855869136d40820878662b vencord's `pnpmDeps.hash` got changed

```diff
- hash = "sha256-bosCE9gBFCcM3Ww6sJmhps/cl4lovXKMieYpkqAMst8=";
+ hash = "sha256-YBWe4MEmFu8cksOIxuTK0deO7q0QuqgOUc9WkUNBwp0=";
```

The new hash builds fine on `master` *(`nix build github:nixos/nixpkgs/71fc5743a87cbbc0effb44764761205bed7bc5c7#vencord`)*, but it fails here on `release-24.05`? That's also why the first `nixpkgs-review` failed

What am I missing here?

Also the CODEOWNERS check fails, but it seems like it's totally unrelated to this PR:
<details>
<summary>Log</summary>

```console
==> Executing Duplicated Pattern Checker (116.167µs)
    Check OK
==> Executing Valid Syntax Checker (822.484µs)
    Check OK
==> Executing File Exist Checker (6.510747ms)
    [err] line 370: "pkgs/os-specific/linux/lxc/" does not match any files in repository
==> Executing [Experimental] Avoid Shadowing Checker (8.178609ms)
    Check OK
==> Executing Valid Owner Checker (5.924511002s)
    Check OK

5 check(s) executed, 1 failure(s)
Error: Process completed with exit code 3.
```
</details>

**Comment by NotAShelf** [comment]
Ah, this reminds me.

https://github.com/NixOS/nixpkgs/pull/349093#issuecomment-2421873637

**Comment by Scrumplex** [comment]
Just regenerate the hash for 24.05. One of the CI checks is gonna fail but there is no good solution here

**Comment by DontEatOreo** [comment]
> Just regenerate the hash for 24.05.

It already uses the correct hash, the hash before 9744efc3b0b81a8a71855869136d40820878662b works fine on `release-24.05`

**Review by Scrumplex — APPROVED** [review]
Ignoring codeowners check failure, as it's unrelated here. LGTM. Thanks!

**Pull request merged**
