### PR TITLE
faker: 0.0.4 -> 0.7.17 (and related changes)

### PR DESCRIPTION
**Pull request by langston-barrett**
###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by siddharthist** [comment]
I can't tell if the Travis errors are legitimate...

**Comment by NeQuissimus** [comment]
I get the same errors when invoking `nox-review wip` locally.

```
======================================================================
ERROR: __main__ (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: __main__
Traceback (most recent call last):
  File "/nix/store/v96ayp4hp476fqabmx86vgvwcn8wb7f9-python3-3.6.1/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/tmp/nix-build-dkimpy-0.6.1.drv-0/dkimpy-0.6.1/dkim/__main__.py", line 4, in <module>
    from tests import test_suite
ModuleNotFoundError: No module named 'tests'


----------------------------------------------------------------------
Ran 154 tests in 0.793s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=154 errors=1 failures=0>
config.status: creating build/bin/b4b5-archfix
error: Test failed: <unittest.runner.TextTestResult run=154 errors=1 failures=0>
config.status: creating build/bin/rb-archfix
config.status: creating build/contrib/check_perms_grsecurity.py
builder for ‘/nix/store/9l97yy47i0npcq3idpjsqhbsp3x1k3x0-dkimpy-0.6.1.drv’ failed with exit code 1
error: build of ‘/nix/store/9l97yy47i0npcq3idpjsqhbsp3x1k3x0-dkimpy-0.6.1.drv’ failed
The invocation of "nix-build -A python27Packages.email_validator -A hash-slinger -A python36Packages.python-etcd -A python36Packages.sqlobject -A python36Packages.dkimpy -A python36Packages.ansible_2_2 -A python36Packages.email_validator -A dkimpy -A python27Packages.dns -A electrum-ltc -A python27Packages.ntfy -A dd-agent -A python36Packages.faker -A ntfy -A python36Packages.sleekxmpp -A python27Packages.sipsimple -A python27Packages.dkimpy -A python36Packages.ansible -A electrum-dash -A python27Packages.ansible_2_2 -A python27Packages.sleekxmpp -A mailman -A python36Packages.ukpostcodeparser -A electrum -A python27Packages.ansible_2_3 -A ansible -A python36Packages.dns -A python27Packages.python-etcd -A python27Packages.ansible2 -A python27Packages.sqlobject -A python27Packages.ansible -A python36Packages.ansible_2_1 -A python27Packages.FormEncode -A python36Packages.FormEncode -A kargo -A blink -A python27Packages.ukpostcodeparser -A python27Packages.faker -A python27Packages.ansible_2_1 -A python36Packages.ntfy -A errbot /home/nequi/dev/nixpkgs" failed
```

**Comment by siddharthist** [comment]
@NeQuissimus Thanks for checking it out! I don't think that error is related to my changes. It also happens on master.

@leenaars Looks like you're the maintainer on that package, any input on what's causing those tests to fail?

**Comment by siddharthist** [comment]
Okay, I've updated the `dkimpy` package too, and reran
```
```

@NeQuissimus When I run `nox-review` locally, I get a weird error: https://pastebin.com/raw/aH3vsjhH. Have you seen this before? It seems like fixing it will help me catch errors in my PRs, but I'm not sure how to go about it.

**Comment by siddharthist** [comment]
I believed I've fixed the build of `dkimpy`.

**Comment by NeQuissimus** [comment]
`nox-review` still fails for me though

```
Processing ./cli53-0.4.4-py2-none-any.whl
Processing ./dkimpy-0.6.2-py2-none-any.whl
Collecting argparse (from cli53==0.4.4)
  Could not find a version that satisfies the requirement argparse (from cli53==0.4.4) (from versions: )
No matching distribution found for argparse (from cli53==0.4.4)
Installing collected packages: dkimpy
builder for ‘/nix/store/vr5dn5g7v7y7239y65c7zjiyv11vvxgy-cli53-0.4.4.drv’ failed with exit code 1
error: build of ‘/nix/store/vr5dn5g7v7y7239y65c7zjiyv11vvxgy-cli53-0.4.4.drv’ failed
The invocation of "nix-build -A python27Packages.ansible_2_1 -A electrum -A python36Packages.dns -A python27Packages.ansible2 -A python27Packages.FormEncode -A python36Packages.faker -A cli53 -A blink -A python27Packages.python-etcd -A python36Packages.python-etcd -A ntfy -A mailman -A ansible -A python27Packages.ukpostcodeparser -A dkimpy -A python27Packages.sipsimple -A python27Packages.ansible_2_2 -A kargo -A python36Packages.ansible_2_1 -A python36Packages.sqlobject -A python36Packages.FormEncode -A python27Packages.email_validator -A python27Packages.ntfy -A python36Packages.ansible_2_2 -A python27Packages.dkimpy -A hash-slinger -A electrum-dash -A python36Packages.email_validator -A python27Packages.ansible -A python36Packages.sleekxmpp -A python36Packages.dkimpy -A python27Packages.faker -A python27Packages.sqlobject -A python36Packages.ntfy -A errbot -A python36Packages.ansible -A python27Packages.ansible_2_3 -A electrum-ltc -A python27Packages.dns -A dd-agent -A python36Packages.ukpostcodeparser -A python27Packages.sleekxmpp /home/nequi/dev/nixpkgs" failed
```

**Comment by siddharthist** [comment]
@NeQuissimus Sorry to have wasted your time, I appreciate your patience and review. I've [been having trouble running `nox-review`](https://pastebin.com/raw/3eH2xc61), which is why I didn't check before making this PR. I'll try to set up a container or virtual machine or something to test it, and ping you when I get that working.

**Comment by NeQuissimus** [comment]
@siddharthist No worries. I find it only works for me if I run it outside of `nix-shell` by installing it into my environment and then running `nox-review wip` directly.

**Comment by siddharthist** [comment]
Yeah, for some reason I still get the error I linked to above 😢 Might have to wait for the resolution of #27288 or feedback on https://github.com/madjar/nox/issues/65 before I can use `nox-review` and then fix this PR. Here's the command I used:
```
nox-review pr 27106
```

**Comment by NeQuissimus** [comment]
I was not even aware of the PR functionality :)

I have two aliases in my `~/.gitconfig`:

```
prup = "!f() { git fetch upstream pull/${1}/head:pr-${1}; git checkout pr-${1}; }; f"
undo = reset HEAD~1 --mixed
```

Then I do this in my nixpkgs

```
git prup 27106
git undo # Repeat until all commits from PR are undone
nox-review wip
```

`nox-review wip` seems to work while `nox-review pr 27106` does not...

**Comment by siddharthist** [comment]
@NeQuissimus Is it possible that you're using a different version of `nix`? What happens when you run `nix-env -qaPf . --out-path` on `master`? That's how `nox` is producing the above error, I get the message:
```
error: attribute ‘webkitgtk24x’ missing, at /home/siddharthist/code/nixpkgs/pkgs/development/haskell-modules/hackage-packages.nix:202442:10
```

**Comment by NeQuissimus** [comment]
Works just fine.
Master (as of right now) lists all the good stuff :)

Also:

```bash
~ λ nix-env --version
nix-env (Nix) 1.11.11
~ λ readlink -e $(type -p nix-env) 
/nix/store/ypy3xhz1p5bf472nphhdq1z73khsx8rc-nix-1.11.11/bin/nix-env
~ λ readlink -e $(type -p nox-review)
/nix/store/jqbxpps9nmagav3fx328s59l42h8rl69-nox-0.0.5/bin/nox-review
```

**Comment by FRidh** [comment]
@siddharthist Could you rebase this and ping me afterwards?

**Comment by siddharthist** [comment]
@FRidh I've rebased and tested the build of `Faker` and `dkimpy`

**Comment by siddharthist** [comment]
I've rebased again and fixed the build of `sqlobject` by updating `FormEncode`. Putting out fires... 🤕 🔥

There are still some errors in the `nox-review`:
 * `neutron`: This package is broken and marked as broken, `nox` doesn't skip broken packages 
 * `cli53`: This package is broken but not marked. For now, I'm ignoring it
 * ??: currently working on `ryu`, not sure what will be broken after I fix that.

**Comment by siddharthist** [comment]
Actually, looks like `ryu` was the last of it. This is what `nox-review wip --against master` runs after commit 05d661a:
```
nix-build -A electrum -A python36Packages.sqlobject -A python27Packages.sqlobject -A python36Packages.FormEncode -A python36Packages.pysideShiboken -A python36Packages.spyder -A python36Packages.python-etcd -A python27Packages.email_validator -A python36Packages.pyside -A python36Packages.ansible -A ntfy -A python27Packages.ansible -A python27Packages.ansible_2_2 -A dkimpy -A electrum-dash -A python36Packages.ansible_2_2 -A python36Packages.ukpostcodeparser -A python27Packages.faker -A python27Packages.python-etcd -A python36Packages.dns -A hash-slinger -A python27Packages.sipsimple -A neutron -A dd-agent -A python27Packages.sleekxmpp -A python27Packages.dns -A python27Packages.ntfy -A python36Packages.faker -A python27Packages.ansible_2_1 -A ansible -A python27Packages.ukpostcodeparser -A python36Packages.ntfy -A electrum-ltc -A cli53 -A python27Packages.dkimpy -A blink -A python27Packages.ansible2 -A python27Packages.FormEncode -A kargo -A python27Packages.ryu -A python36Packages.ryu -A python36Packages.dkimpy -A mailman -A errbot -A python36Packages.sleekxmpp -A python27Packages.ansible_2_3 -A python36Packages.email_validator -A python36Packages.pysideTools -A python36Packages.ansible_2_1 .
```
without `cli53`, `neutron`, and `ryu`:
```
nix-build -A electrum -A python36Packages.sqlobject -A python27Packages.sqlobject -A python36Packages.FormEncode -A python36Packages.pysideShiboken -A python36Packages.spyder -A python36Packages.python-etcd -A python27Packages.email_validator -A python36Packages.pyside -A python36Packages.ansible -A ntfy -A python27Packages.ansible -A python27Packages.ansible_2_2 -A dkimpy -A electrum-dash -A python36Packages.ansible_2_2 -A python36Packages.ukpostcodeparser -A python27Packages.faker -A python27Packages.python-etcd -A python36Packages.dns -A hash-slinger -A python27Packages.sipsimple -A dd-agent -A python27Packages.sleekxmpp -A python27Packages.dns -A python27Packages.ntfy -A python36Packages.faker -A python27Packages.ansible_2_1 -A ansible -A python27Packages.ukpostcodeparser -A python36Packages.ntfy -A electrum-ltc -A python27Packages.dkimpy -A blink -A python27Packages.ansible2 -A python27Packages.FormEncode -A kargo -A python36Packages.dkimpy -A mailman -A errbot -A python36Packages.sleekxmpp -A python27Packages.ansible_2_3 -A python36Packages.email_validator -A python36Packages.pysideTools -A python36Packages.ansible_2_1 .
```
and that passes.

Note that the Travis build fails on `cli53`. If anyone else can confirm `cli53` is broken on master, then I think this is ready to merge (maybe after marking `cli53` as broken).

**Comment by FRidh** [comment]
Looks good! I'll just wait till some of the rebuilding is finished and then merge this.

**Comment by siddharthist** [comment]
@FRidh Thanks for hanging in there with the review 😄 hopefully my PRs will be expedited now that `nox-review` is working for me.

**Comment by FRidh** [comment]
This is in staging now.

**Pull request closed without merging**
