### PR TITLE
python3Packages.pillow & python3Packages.pillow-simd: Fix cross compilation

### PR DESCRIPTION
**Pull request by kip93**
Fixes the build time error:
`ModuleNotFoundError: No module named 'setuptools'`.

## Description of changes

Added `setuptools` on `nativeBuildInputs`, so that it's available at build time when cross compiling.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux (cross compiled from x86_64-linux)
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
The hook should make setuptools available, even when cross-compiling.

**Review by Majiir — APPROVED** [review]
LGTM. Confirmed this fixes cross-compiling for `armv7l`. 

bdf1a96570808dc9e11cfbb1ffa5b8a7ff001e2d (from https://github.com/NixOS/nixpkgs/pull/244135) changed pillow's format from `setuptools` to `pyproject`. Other packages in that same PR added `setuptools` to `nativeBuildInputs` for this purpose, so I think you are in the clear.

**Review by ghost — APPROVED** [review]
Fixed `pkgsCross.*.python3Packages.pillow` for me.

**Comment by vcunat** [comment]
This causes over 13k rebuilds in total.  Why merge directly to master?

**Comment by kip93** [comment]
Don't the docs say that small changes go to master? Or did I miss something?

I just saw that the CONTRIBUTING.md file got recently expanded from the time I created this PR, maybe I just missed something new there, I'll go re-read it. Sorry!

**Comment by vcunat** [comment]
The automatic red `rebuild-*` labels are there to signify that the PR is probably too large a rebuild.  I'm sure it's expected that contributors with little experience may not know things like that; so IMHO this is more of a responsibility of the person who does the merge (though it's nice when others notice and comment about it, too).

**Comment by vcunat** [comment]
Reapplied in 094bfcf23765

**Pull request merged**
