### PR TITLE
intake: 0.4.4 -> 0.5.3

### PR DESCRIPTION
**Pull request by kalbasit**
###### Motivation for this change

Fixing the intake package broken by #66348.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @costrouc @jonringer @pierothebear

### CODE REVIEW

**Comment by kalbasit** [comment]
cc @jonringer

**Review by jonringer — COMMENTED** [review]
still getting a fair number of failures

```
[39 built (6 failed), 253 copied (1574.9 MiB), 454.1 MiB DL]
error: build of '/nix/store/lxika718nsqqrv07gg6bfh2aj3j400jb-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/66412
1 package are marked as broken and were skipped:
python37Packages.imgaug

11 package failed to build:
python37Packages.aplpy python37Packages.blaze python37Packages.dask-glm python37Packages.dask-ml python37Packages.dask-xgboost python37Packages.datashader python37Packages.odo python37Packages.optuna python37Packages.starfish python37Packages.streamz python37Packages.sunpy

33 package were build:
python27Packages.bokeh python27Packages.colorcet python27Packages.holoviews python27Packages.hvplot python27Packages.panel python27Packages.param python27Packages.pyct python27Packages.pyviz-comms python27Packages.runway-python python37Packages.bokeh python37Packages.caffe python37Packages.colorcet python37Packages.dask python37Packages.dask-image python37Packages.dask-jobqueue python37Packages.dask-mpi python37Packages.distributed python37Packages.glymur python37Packages.holoviews python37Packages.hvplot python37Packages.image-match python37Packages.intake python37Packages.panel python37Packages.param python37Packages.pims python37Packages.pyct python37Packages.pyfftw python37Packages.pyviz-comms python37Packages.rl-coach python37Packages.runway-python python37Packages.scikitimage python37Packages.slicedimage python37Packages.stumpy
```

**Comment by jonringer** [comment]
looks like a lot of the failures are with astropy being broken by the numpy update (numpy is more strict about memory layout/usage/casting etc). which causes a lot of tests to fail. :(

**Comment by kalbasit** [comment]
> still getting a fair number of failures
> 
> ```
> [39 built (6 failed), 253 copied (1574.9 MiB), 454.1 MiB DL]
> error: build of '/nix/store/lxika718nsqqrv07gg6bfh2aj3j400jb-env.drv' failed
> https://github.com/NixOS/nixpkgs/pull/66412
> 1 package are marked as broken and were skipped:
> python37Packages.imgaug
> 
> 11 package failed to build:
> python37Packages.aplpy python37Packages.blaze python37Packages.dask-glm python37Packages.dask-ml python37Packages.dask-xgboost python37Packages.datashader python37Packages.odo python37Packages.optuna python37Packages.starfish python37Packages.streamz python37Packages.sunpy
> 
> 33 package were build:
> python27Packages.bokeh python27Packages.colorcet python27Packages.holoviews python27Packages.hvplot python27Packages.panel python27Packages.param python27Packages.pyct python27Packages.pyviz-comms python27Packages.runway-python python37Packages.bokeh python37Packages.caffe python37Packages.colorcet python37Packages.dask python37Packages.dask-image python37Packages.dask-jobqueue python37Packages.dask-mpi python37Packages.distributed python37Packages.glymur python37Packages.holoviews python37Packages.hvplot python37Packages.image-match python37Packages.intake python37Packages.panel python37Packages.param python37Packages.pims python37Packages.pyct python37Packages.pyfftw python37Packages.pyviz-comms python37Packages.rl-coach python37Packages.runway-python python37Packages.scikitimage python37Packages.slicedimage python37Packages.stumpy
> ```

To be fair, the following packages were also broken on master before #66348

```
python37Packages.aplpy python37Packages.blaze python37Packages.dask-glm python37Packages.dask-ml python37Packages.dask-xgboost python37Packages.datashader python37Packages.odo python37Packages.starfish python37Packages.streamz python37Packages.sunpy
```

Leaving only `python37Packages.optuna` from your list. Unsure if that package was failing prior to #66348 as I don't see it listed in your [comment](https://github.com/NixOS/nixpkgs/pull/66348#pullrequestreview-272915711).

**Comment by jonringer** [comment]
`python37Packages.optuna`  might not depend on intake, so it doesn't get grabbed in the `nix-review`. 

Either way, annoying that so much has broken from a minor bump on numpy.

**Comment by kalbasit** [comment]
> `python37Packages.optuna` might not depend on intake, so it doesn't get grabbed in the `nix-review`.
> 
> Either way, annoying that so much has broken from a minor bump on numpy.

Oh you mean 55d82d54307e9c30ef34342e68ef615e4350b0a0 broke it? That's out of scope for this PR as I'm only intending to fix what my other PR has broke.

I kindof wish that ofborg would build all Python packages anytime one of them is changed in a PR. cc @grahamc

**Comment by kalbasit** [comment]
@GrahamcOfBorg build python3Packages.param python3Packages.bokeh python3Packages.bokeh python3Packages.panel python3Packages.intake

**Comment by jonringer** [comment]
> I kindof wish that ofborg would build all Python packages anytime one of them is changed in a PR. cc @grahamc

that would be huge increase in computational volume. For stuff that <50 rebuilds, a local nix-review suffices. For larger, then it makes sense to use something like staging to experiment with many potentially large breaking changes.

**Comment by kalbasit** [comment]
> > I kindof wish that ofborg would build all Python packages anytime one of them is changed in a PR. cc @grahamc
> 
> that would be huge increase in computational volume. For stuff that <50 rebuilds, a local nix-review suffices. For larger, then it makes sense to use something like staging to experiment with many potentially large breaking changes.

hence the "I wish" :smile: 

Anyway, thanks for your help @jonringer. I'll fix the Darwin issue and merge.

**Comment by kalbasit** [comment]
I can't replicate locally on my Darwin. I'll give it another shot.

@GrahamcOfBorg build python3Packages.intake

**Pull request merged**
