### PR TITLE
Set MAIL to mailspool

### PR DESCRIPTION
**Pull request by Baughn**

### CODE REVIEW

**Comment by lethalman** [comment]
What is this needed for?

**Comment by Baughn** [comment]
The MAIL environment variable is used by a number of MUAs, such as mutt, to find the location of incoming email. It defaults to /var/mail (by glibc fiat; it isn't allowed to be unset), but it needs to be configured depending on where the MDA you've installed stores its email.

This postfix package is hardcoded to use /var/spool/mail, so I'm setting the MAIL variable correspondingly. Really, it should be set individually for all MDAs available in nixos, but I don't know where to find a complete list.

**Comment by lethalman** [comment]
Not sure but maybe this should rather be documented to the end-user to set that variable in their configuration.nix

**Comment by Baughn** [comment]
The only valid configuration with this postfix configuration is /var/spool/mail.

**Comment by Baughn** [comment]
(Also, people on average don't read the documentation. They can still override this, if they want; I'd like for the default to work. There's no benefit to a default that's a nonexistent directory.)

**Comment by lethalman** [comment]
That makes sense, but also it's not that postfix is used only for user installations, but also server installations where that MAIL may break something else. Not sure.

**Comment by Baughn** [comment]
Well--I'm not quite sure about the distinction, but I'm using it as a server install.

What the previous MAIL behaviour breaks is... all user (command-line) processing of email. It doesn't prevent email from being sent outside of the system, and it doesn't technically stop postfix from working, but all delivery to local users will in effect silently drop mail on the floor, since nothing will know where to find it.

Admittedly I'm not a mail-server expert, and you're welcome to seek a second opinion, but it seems to me that we'd be exchanging known-broken behaviour for possibly-broken behaviour that at least works in the common case.

**Comment by lethalman** [comment]
cc @edolstra

**Comment by Baughn** [comment]
Another option suggested by #postfix is to make /var/mail a symlinks to /var/spool/mail

**Comment by Baughn** [comment]
Although apparently the MAIL variable is, to paraphrase, "Old, deprecated, broken, and should die in a fire".

The symlink is the only safe way to do this, I guess? And/or configuring *each single MUA* to know where to pick up its mail. I'll wait for @edolstra to comment.

**Comment by peti** [comment]
IMHO, the module for postfix is entirely the wrong place to configure a setting that concerns mail readers.

**Comment by Baughn** [comment]
Well, it's a setting that tells the MUAs where the Postfix put their mail. Where *would* you put it?

**Comment by peti** [comment]
IMHO, it would be best to ensure that all MUAs in Nixpkgs are compiled to use `/var/spool/mail` by default to make sure they work without any configuration at all.

**Comment by Baughn** [comment]
How about adding the symlink? It's a common solution, and wouldn't need us to track down every MUA on the planet to change its compilation options. What package would that go in?

**Comment by peti** [comment]
I think it's safe to say that this PR is controversial, and despite the fact that several alternative approaches to achieve the desired goal have come up, none of them has been implemented in the last ~3 months, so I'm closing this issue for the time being.

**Comment by bjornfor** [comment]
I didn't know about this PR. Here is a related issue: https://github.com/NixOS/nixpkgs/issues/7336.

**Comment by Baughn** [comment]
I'm no longer using Nixos, mainly because I had difficultiies integrating third-party software that expects an LSB system, so this PR won't see updates.

**Pull request closed without merging**
