### PR TITLE
radare2-cutter: Allow to use Python plugins

### PR DESCRIPTION
**Pull request by Pamplemousse**
###### Motivation for this change

Cutter is a GUI front-end for the `radare2` binary analysis tool; Its features can be extended using plugins, some of them written in Python.
However, for those to work, Cutter needs to have been compiled with specific flags.
See #101511 for details and references.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
@Pamplemousse I only checked whether it compiles, please test!

**Comment by Pamplemousse** [comment]
Built and ran on NixOS;
Successfully tested a couple of plugins!

Thanks @Mic92 :)

However, I encountered two new problems:
  * plugins requiring extra Python libraries don't work (for example [angrcutter](https://github.com/yossizap/angrcutter))
  * can't have several plugins at the same time (opened radareorg/cutter#2457 about that - might be a Nix-specific problem though...)

**Comment by Mic92** [comment]
@Pamplemousse for additional python libraries you have 3 options: use an override to extend `propagatedBuildInputs` or extend the PYTHONPATH with nix-shell or an wrapper around the executable set extends PYTHONPATH.

**Comment by Pamplemousse** [comment]
I did not have time to invest into making plugins requiring python libraries work (especially given that in the current state of `Pyside`, only one plugin at a time can be used...).

However, I felt this is already a significant enough improvement from the current `Cutter` in `nixpkgs`.

@Mic92 , I rebased / squashed your commit for a cleaner history. Thanks a lot for your help!

**Pull request merged**
