### PR TITLE
hwdata: 0.375 -> 0.376

### PR DESCRIPTION
**Pull request by trofi**
Changes: https://github.com/vcrhonek/hwdata/compare/v0.375...v0.376

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by IogaMaster — CHANGES_REQUESTED** [review]
This package doesn't put any thing into `$out`, meaning this package isnt usable.
You should write the phases to properly build this package

**Comment by trofi** [comment]
> This package doesn't put any thing into `$out`, meaning this package isnt usable. You should write the phases to properly build this package

Can you clarify why you came to that conclusion? Here are the files that `hwdata` puts into `$out`:

```
$ nix build github:NixOS/nixpkgs/pull/265382/merge#hwdata
$ find result/
result/
result/share
result/share/hwdata
result/share/hwdata/pci.ids
result/share/hwdata/usb.ids
result/share/hwdata/oui.txt
result/share/hwdata/iab.txt
result/share/hwdata/pnp.ids
result/share/pkgconfig
result/share/pkgconfig/hwdata.pc
result/lib
result/lib/modprobe.d
result/lib/modprobe.d/dist-blacklist.conf
```

**Comment by wineee** [comment]
@ofborg eval

**Review by PedroHLC — APPROVED** [review]
The changelog is clear that nothing changed besides the device databases.

**Comment by IogaMaster** [comment]
Interesting, I used nix run on your branch and it said nothing was in out. But it appears to be working.

**Pull request merged**
