### PR TITLE
[21.05] openmpt123: 0.5.8 -> 0.5.11

### PR DESCRIPTION
**Pull request by OPNA2608**
###### Motivation for this change
Backporting bugfix updates to stable.
0.5.8 -> 0.5.9 [(CHANGELOG)](https://lib.openmpt.org/libopenmpt/2021/05/16/releases-0.5.9-0.4.21-0.3.30/) from #126599
0.5.9 -> 0.5.10 [(CHANGELOG)](https://lib.openmpt.org/libopenmpt/2021/07/04/releases-0.5.10-0.4.22-0.3.31/) from #129414
0.5.10 -> 0.5.11 [(CHANGELOG)](https://lib.openmpt.org/libopenmpt/2021/08/22/security-updates-0.5.11-0.4.23-0.3.32/) from #137093

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 129454` at 1534f047 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built successfully:</summary>
  <ul>
    <li>audacious (audaciousQt5)</li>
    <li>gjay</li>
    <li>openmpt123</li>
  </ul>
</details>

**Review by jonringer — COMMENTED** [review]
When backporting changes, please follow https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#backporting-changes.

Namely, you should be doing `git cherry-pick -x <rev>` from a commit that has already landed in master. If the branches have diverged, you may alter the commit or add another commit to ensure that the package is able to still evaluate and build

**Comment by OPNA2608** [comment]
Whoops, cherry-picked with `-x` now :sweat_smile:.

**Review by symphorien — APPROVED** [review]
all reverse deps build on nixos
I could play a .mod file with audacious
changelogs don't mention backward incompatibilies/removals

**Comment by risicle** [comment]
`nixpkgs-review` happy, macos 10.15 & nixos x86_64

**Review by risicle — APPROVED** [review]

**Pull request merged**
