### PR TITLE
Change download URL for IDEA editor

### PR DESCRIPTION
**Pull request by boronine**
Old download links were giving me sha mismatches during build. Worse than that, the link seemed to return non-identical files when fetched multiple times. I grabbed the new link from IntelliJ download page. Unlike the old one, this one comes with a corresponding sha file, which is nice:

https://download.jetbrains.com/idea/ideaIC-14.0.3.tar.gz
https://download.jetbrains.com/idea/ideaIC-14.0.3.tar.gz.sha256

### CODE REVIEW

**Comment by bjornfor** [comment]
CC @edwtjo

**Comment by edwtjo** [comment]
The hash you've changed to is the same as the one in the current expression, also download and download-ln redirects to the same cloudfront instance.

**Comment by boronine** [comment]
You're right about download-ln, I tested on my VPS and the files are consistent. (download-ln does not provide https://download-ln.jetbrains.com/idea/ideaIC-14.0.3.tar.gz.sha256, however, seems that download.jetbrains.com is more kosher)

I'm not sure what you mean about the sha being the same as the one in the current expression, though. When I download the community edition tarball manually and run sha256sum on it, I get `167384bfb2a1a53658cf7e069f666ff05c6a737c4bcc4145a4034ea8dabf8c07`, not `01wcpzdahkh3li2l3k2bgirnlp7hdxk9y1kyrxc3d9d1nazq8wqn`. What am I missing?

**Comment by vcunat** [comment]
@boronine: two formats are accepted -- base16 and base32.
```
$ nix-hash --type sha256 --to-base32 167384bfb2a1a53658cf7e069f666ff05c6a737c4bcc4145a4034ea8dabf8c07
01wcpzdahkh3li2l3k2bgirnlp7hdxk9y1kyrxc3d9d1nazq8wqn
```

**Comment by boronine** [comment]
So I'm guessing my problems came from my bad network (probably the only way to explain the mysteriously changing sha). I undid the sha changes, so now this PR just changes `download-ln` to `download`. Thanks for the help, and huge kudos on your work. Nix is blowing my mind.

**Comment by vcunat** [comment]
:-) Pushed. It isn't much of a change, I guess. The new URLs look cleaner and upstream web seems to rather refer to ``download`` and not ``download-ln``.

**Comment by edwtjo** [comment]
It might be kosher but in the end it's just meat :) Also why drop the https change? This PR was basically just a transport issue report, changed to HTTPS in b65e6e873f90b9febb85f5a97b0cc2ed8798304a

**Comment by vcunat** [comment]
@edwtjo: I didn't notice the http(s) issue, but it doesn't really matter, as our fetchurl uses insecure connection anyway IIRC. (The hash is known, so the way of obtaining the file doesn't matter.)

**Comment by edwtjo** [comment]
@vcunat are you saying that fetchurl doesn't validate the certificates? I know that, transport wise, you only care about the strength and validity of the hash but I thought that, it seems in error, you could at least use HTTPS for mitm detection.

**Comment by boronine** [comment]
Yeah, in this case https wouldn't add much. It looks like because their physical download servers don't support https, they have to do a 302 redirect, as opposed to a simpler CNAME redirect for http.

Regarding the main issue, I managed to reproduce it on first try:

    trying http://download-ln.jetbrains.com/idea/ideaIC-14.0.3.tar.gz
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100  182M    0  182M    0     0   704k      0 --:--:--  0:04:25 --:--:--  700k
    output path ‘/nix/store/g7qlvy5kwafdzgk98ghqfyhbw03vx1c6-ideaIC-14.0.3.tar.gz’ should have sha256 hash ‘01wcpzdahkh3li2l3k2bgirnlp7hdxk9y1kyrxc3d9d1nazq8wqn’, instead has ‘04g0l5vmld9vd34vy7yd4nf9iywh8vqmb7m3rw7abbzb7ggi3hwv’

And after some fiddling around, I figured out what the deal is. If you gunzip both the expected and the unexpected file, you get an identical tarball. 

    [alexei@nixos:~]$ sha256sum idea-correct/ideaIC-14.0.3.tar.gz
    167384bfb2a1a53658cf7e069f666ff05c6a737c4bcc4145a4034ea8dabf8c07  idea-correct/ideaIC-14.0.3.tar.gz
    [alexei@nixos:~]$ gunzip idea-correct/ideaIC-14.0.3.tar.gz --stdout | sha256sum 
    8146407310511acbe68b19a8f6eb1ce4139ae7892293422f82e473092eba6f74  -


    [alexei@nixos:~]$ sha256sum /nix/store/g7qlvy5kwafdzgk98ghqfyhbw03vx1c6-ideaIC-14.0.3.tar.gz
    9bc311df3bebafa50ecfa39e55f14690fb989c25cd1fbfc9683b355a77a1e011  /nix/store/g7qlvy5kwafdzgk98ghqfyhbw03vx1c6-ideaIC-14.0.3.tar.gz
    [alexei@nixos:~]$ gunzip --stdout /nix/store/g7qlvy5kwafdzgk98ghqfyhbw03vx1c6-ideaIC-14.0.3.tar.gz | sha256sum 
    8146407310511acbe68b19a8f6eb1ce4139ae7892293422f82e473092eba6f74  -

So it looks like the unexpected file was encoded with a different gzip version. For some reason I can't reproduce the unexpected download using plain wget or curl, it always gives me the correct file. And yet, Nix insists on downloading the incorrect one.

I'm going to guess that it's some obscure caching issue or some evil proxy somewhere. Switching from `download-ln.jetbrains.com` to `download.jetbrains.com` does seem to fix the issue, and since JetBrains provides the `.sha256` file on `download.jetbrains.com` we can blame it on them if the issue comes up again :wink:

**Comment by boronine** [comment]
Never mind, `download.jetbrains.com` does support HTTPS!

    [alexei@nixos:~]$ curl -I https://download.jetbrains.com/idea/ideaIC-14.0.3.tar.gz | grep Location
    Location: https://d1opms6zj7jotq.cloudfront.net/idea/ideaIC-14.0.3.tar.gz
    [alexei@nixos:~]$ curl -I https://d1opms6zj7jotq.cloudfront.net/idea/ideaIC-14.0.3.tar.gz
    HTTP/1.1 200 OK

In that case, https does protect the download from meddling proxies. I wouldn't imagine why a proxy would want to reincode a gzip file, but who knows!

**Comment by vcunat** [comment]
@edwtjo: it passes the ``--insecure`` option to curl (it's easy to find).

@boronine: whatever downloads I try from these, I'm still getting the hash we have in the expression.

**Pull request closed without merging**
