### PR TITLE
python3Packages.ambee: init at 0.2.1

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Python client for Ambee API

https://github.com/frenck/python-ambee

- Related Home Assistant change: https://github.com/home-assistant/core/pull/51645
- Target Home Assistant release: 2021.7.0

ToDo:

- [ ] Update `component-packages` 
- [ ] Enable tests in Home Assistant

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 126326` at 7c915252 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python38Packages.ambee</li>
    <li>python39Packages.ambee</li>
  </ul>
</details>

**Comment by frenck** [comment]
As the author of the package that is being re-packaged here. I'm against it being repacked into here.
While licensing wise I cannot stop you, I do hope you can honor my request.

**Comment by fabaff** [comment]
@frenck, what's the reason you are against it?

It's a Home Assistant dependency and as a dependency it has to be present otherwise users would not be able to use the `ambee` integration.

**Comment by frenck** [comment]
> It's a Home Assistant dependency and as a dependency it has to be present otherwise users would not be able to use the ambee integration.

That is not true. It is a pure Python package, Home Assistant will just fetch it from PyPi.

**Comment by mweinelt** [comment]
> > It's a Home Assistant dependency and as a dependency it has to be present otherwise users would not be able to use the ambee integration.
> 
> That is not true. It is a pure Python package, Home Assistant will just fetch it from PyPi using pip.
> 

That is sadly not true and probably a large part of the misunderstanding here.

Given that Nix packaging results in immutable output paths, home-assistant simply cannot go around and modify its site-packages by itself. Users need to opt-in to the components at build time and for that to be possible we need to package their individual dependencies into nixpkgs.

**Comment by frenck** [comment]
In that case you are shipping an broken Home Assistant version.

Which u definitely don't want to be part of.

Please remove it.

**Comment by lukegb** [comment]
> In that case you are shipping an broken Home Assistant version.
> 
> Which I definitely don't want to be part of.
> 
> Please remove this package, including all my other packages.
> 
> Thank for respecting my wishes as the author of the source.

Hi! I'd like to understand your concerns a little better:

* Would you be happier if we were using the release tarballs/wheels from your published PyPi releases instead?
* Have you had support load from users of NixOS as a result of this that we haven't seen? That would certainly be unfortunate and is not our intent, but it would be good to know about now.
* Would you be happier if we forked your upstream source to provide our own, or provided a similar Python package with an identical API that we can use as a drop-in replacement?
* Are you aware of similar efforts to package Home Assistant in a manner suitable for other Linux distros, such as Gentoo, that also include your packages (by necessity)? Do you have similar concerns there?

I'm also a little anxious that this thread has the potential to get heated quite quickly, so if you have the time and are willing to it might be worth setting up a quick Jitsi Meet to talk about this. Failing that, maybe we should pull this off into a separate issue thread so we can discuss there instead.

**Comment by frenck** [comment]
My wishes are above, please respect those. I have no intensional of spending time in this project. 

Thanks.

**Comment by lukegb** [comment]
> My wishes are above, please respect those. It is a fairly simple request, nothing heated about it. I have no intention of spending time in this project.
> 
> Thanks.

Thanks for your time. In a similar spirit, I'll spend no further time responding to this request. I'll leave it up to other people to decide what to do.

**Comment by frenck** [comment]
Thanks, @lukegb nevertheless thanks for your extended questions. 👍

**Comment by jtojnar** [comment]
> > Would you be happier if we forked your upstream source to provide our own, or provided a similar Python package with an identical API that we can use as a drop-in replacement?
> 
> This was already answered. Please don't repack my source in this repository was my request. I don't see how your suggestion is changing that.

The difference would be that users would no longer associate the software with you and they would surely go to nixpkgs to report bugs.

Another alternative would be requiring users to explicitly set `config.ambee.acceptThatThisPackageIsNotSupportedByUpstreamDevelopersAndIWillGoToNixpkgsToReportAnyIssues = true` to be able to install the package, or they would get an error that would make it even clearer. Would that be enough for you?

-----

We<sup>1</sup> can remove the package but that should only be a last resort after we have exhausted all other options.

That is because in the absence of the package in Nixpkgs, every NixOS user would have to create their own `ambee` package if they wanted to use it. And no, `pip` is not an option since it simply is not reproducible enough.

----

1. Well, there is not really any “we” – NixOS currently has no policy about this so the responsibility falls on the individual maintainers adding the package (@fabaff).

**Comment by frenck** [comment]
> Would that be enough for you?

I feel like I'm starting to be on repeat now. Please don't add any of my stuff to this project. Thanks 👍 

> Would that be enough for you?

No. Please don't add it to this project. Thanks 👍 

> That is because in the absence of the package in Nixpkgs, every NixOS user would have to create their own ambee package if they wanted to use it. And no, pip is not an option since it simply is not reproducible enough.

I'm aware of the consequence. Luckily the Home Assistant project does not recommend or support that either (which is unrelated but makes me worry less).

**Comment by Mic92** [comment]
Result of `nixpkgs-review pr 126326` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python38Packages.ambee</li>
    <li>python39Packages.ambee</li>
  </ul>
</details>

**Comment by Mic92** [comment]
> No. Please don't add it to this project. Thanks +1

Request kindly denied due to the lack of technical reasons. If you don't wish your code to be packaged in nixpkgs, than make sure it is not a dependency of home-assistant or choose a different license (which should have the same result).

**Comment by frenck** [comment]
@Mic92 I will re-license and bump the dependency in a way that you guys can't distribute. Mainly because of not playing nice.

Thanks 👍

**Comment by Mic92** [comment]
> @Mic92 I will re-license and bump the dependency in a way that you guys can't distribute. Mainly because of not playing nice.
> 
> Thanks +1

This would likely result in no longer being open source and hence the removal from home-assistant as well.

**Comment by frenck** [comment]
> This would likely result in no longer being open source and hence the removal from home-assistant as well.

Unfortunately, you are wrong there. I will explicitly and publicly list parties that are allowed distribution in the license.

**Comment by frenck** [comment]
This pisses me off in a way and is disrespectful. I asked nicely.

**Comment by frenck** [comment]
PS: This package is outdated and not even compatible with the target release anymore.

But I guess that didn't matter, as along as you could merge, right?

**Comment by jtojnar** [comment]
Quoting from Debian’s thread on [Distributing software written by hostile upstream developers](https://lists.debian.org/debian-project/2009/09/msg00037.html):

> If we can't have a sensible relationship with the upstream developers, then I believe it would be better not to expose Debian and our users to the problems that will likely arise from packaging and distributing their software.

I fully agree with that so I would be in favour of removing it.

**Comment by Mic92** [comment]
This is not really an issue for us, we can switch the license to an unfree one and than it is no longer build in nixpkgs but we only ship the build description for building it.

**Comment by frenck** [comment]
> This is not really an issue for us, we can switch the license to an unfree one and than it is no longer build in nixpkgs but we only ship the build description for building it.

Please do from the start, that possibility wasn't provided.

**Comment by lukegb** [comment]
Locked for now. Please see https://github.com/NixOS/nixpkgs/issues/126677#issuecomment-860071285. Please don't merge this until everyone's had a chance to cool off.

**Comment by dotlambda** [comment]
> This package is outdated and not even compatible with the target release anymore.

Our update automation for Home Assistant prints a list of outdated dependencies, so this package will surely be updated in Nixpkgs when Home Assistant is.

**Comment by domenkozar** [comment]
@frenck I'd like to point out that core contributors from the Nix community are handling your request to support our project.

I'd like to clarify from your [sponsors](https://github.com/sponsors/frenck#sponsors) page the following statement:

> Are you enjoying my work? And want to support me in my effort helping the world to become a better place by dedicating my time & knowledge to create & innovate open source software solutions. Allowing everybody on this earth the privilege to enjoy those things for free?

Do you still believe in that?

**Comment by sternenseemann** [comment]
There is no point in locking this thread if NixOS contributors are just gonna ignore that and continue posting here without @frenck being able to respond.

**Comment by eganist** [comment]
FYI, this thread has resulted in some pretty spirited discussion on [hackernews](https://news.ycombinator.com/item?id=27505277).

**Comment by SuperSandro2000** [comment]
> FYI, this thread has resulted in some pretty spirited discussion on [hackernews](https://news.ycombinator.com/item?id=27505277).

We are aware of this. Thanks for the link anyway. :)

**Comment by frenck** [comment]
See: <https://github.com/NixOS/nixpkgs/pull/126319#issuecomment-860942061>

**Comment by Eisfunke** [comment]
> > This would likely result in no longer being open source and hence the removal from home-assistant as well.
> 
> Unfortunately, you are wrong there. I will explicitly and publicly list parties that are allowed distribution in the license and allow for requesting distribution requests.

I feel the need to clarify that even a restriction like that would contradict the first criteria of the [Open Source Definition](https://opensource.org/osd):

>The license shall not restrict any party from selling or giving away the software as a component of an aggregate software distribution containing programs from several different sources.

It would also contradict the [Free Software Definition](https://www.gnu.org/philosophy/free-sw.en.html). A restriction like that would therefore result in the project no longer being open-source or free software.

**Comment by frenck** [comment]
I'm well aware of licensing and open source. It is my full-time daily driver and is visible in the very first request I made indicating the license permits it.

For me, this was not about licensing specifically. However, that point unfortunately is missed and got lost. Which is unfortunate. A lot blew up on the route, which just sucks for both parties.

In the end, I think the way this project distributes Home Assistant and the integration is not providing the intended working and thus may surprise the end user. In the end, those users are likely to knock on the doors of the Home Assistant project and their integration maintainers, not this project.

That is my concern, hence, my initially, friendly request to not include my packages, just like they don't include hundreds of other dependencies of Home Assistant either.

The way it is now discussed and thorn out of proportion is neither my nor (I'm sure) this project intention.

**Comment by gytis-ivaskevicius** [comment]
@frenck you may want to remove the second line from your GitHub profile bio:
image

Multiple compromises were offered including super explicit opt-in noted here https://github.com/NixOS/nixpkgs/pull/126326#issuecomment-860064953. What you are requesting is not FOSS thus you may need to consider making your repository private. Also please consider reading this thread as well https://news.ycombinator.com/item?id=27505277

As for inherit issue "Some peeps might create an issue on my project" - I strongly doubt that it is going to happen and if it does -  since you did not agree to any of the options which would help us avoid such issues, I am afraid that you just gonna have to just deal with it :/

**Comment by mweinelt** [comment]
I feel I've arrived somewhat late to the discussion, but I think it would be reasonable to weigh in here, because I'm home-assistant's (and coincidentally wled's) primary maintainer on nixpkgs these days.

The community consensus seems to be that we really want to keep these packages around, as dropping some of them will unnecessarily break user experiences, which I hope is also not in your interest. I'll also hope we can get to a cordial outcome despite our differences of opinion.

It is true that a lot of components to this day remain unsupported due to missing packages. This is due to the immense number of dependencies home-assistant relies on - but we are certainly catching up.

We also run a significant number of these for the components where we have all dependencies packaged up. We invest a reasonable amount of time to debug failing tests and make sure things work within our environment.

We have rarely asked upstream for support, knowing full well that NixOS is a special snowflake with regard to how everything gets composed. But please recognize that this is the place where we collaborate to bring home-assistant together with our philosophy how system administration should work. 

We take great care when updating home-assistant and its leaf packages, and the index you found is created by tooling that also compares versions of packaged and expected dependencies, so it is somewhat unlikely that we'll ship home-assistant with an outdated dependency.

I also firmly believe that our community is well aware of how we compose home-assistant, so that it runs on NixOS, that they also will be highly aware when breaking changes occur, that they might be our fault.

I'd be happy to more clearly make our users aware, that our distribution is not supported upstream and that issues should first and foremost be directed to us, if that unburdens your project. It was certainly not our intention to sour the relationship with our upstreams.

I hope that puts all technical misunderstandings to rest and we can move on.

Martin Weinelt

**Pull request merged**
