### PR TITLE
squeezer: init at 2.5.4

### PR DESCRIPTION
**Pull request by jpotier**
###### Motivation for this change

New VST

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jpotier** [comment]
One big drawback about this is the need for VST2 SDK… I don't think we can merge this as is in nixpkgs, for licensing matters.

I'm open to suggestions on how to fix this, it would be nice to have squeezer-vst available in nixos by default, for audio people like myself.

I could cheat and bundle pre-built binary vst, but I find it silly to do so, when the project is GPLv3

**Comment by magnetophon** [comment]
@jpotier Thanks!  A while ago, I tried to package it as well, but gave up...

**Comment by jpotier** [comment]
So, this PR needs either:

- help in figuring out how to build the VST2 version without legal problems, or
- wait, until the upstream repo includes a VST3 version of it that we can distribute.

Meanwhile, this package definition is working (I'm using it in a personal overlay) and you can use this if you want to add squeezer to your VST collection on NixOS, by creating an overlay and adding it manually.

**Comment by jpotier** [comment]
This is stale, and I'm not actively working on it anymore. Anyone, feel free to reopen as your own if you're interested.

**Pull request closed without merging**
