### PR TITLE
maven 3.2.3 -> 3.2.5

### PR DESCRIPTION
**Pull request by nckx**
[WIP, mesos breaks on Travis. Building locally on slow hardware.]

### CODE REVIEW

**Comment by lethalman** [comment]
The travis fail appears to be genuine, something must be wrong with this update.

**Comment by nckx** [comment]
I should like that very much; then I could fix it. But running
`nix-build ~/nixpkgs -A mesos -A chronos -A maven -A spark`
on the exact same commit works just fine here...

**Comment by pSub** [comment]
Builds fine for me as well.

**Comment by nckx** [comment]
Thanks!

**Pull request merged**
