### PR TITLE
[WIP] Add erlang modules based on Hex.pm and rebar3

### PR DESCRIPTION
**Pull request by gleber**
Hello Nix community

I am working on getting Erlang packages into Nix and here's my first stab at the problem. This establishes basic build functions and provides 5 Erlang packages. The approach is similar to what is done for Haskell. Here are main points:
- use Hex.pm as a source of tarballs (that's the only reasonable package respository for Erlang AFAIK)
- use rebar3 (alpha-quality version of rebar Erlang built tool which works with Hex.pm)
- aim at automatically importing all of newest packages on Hex (including their transitive closures) use not-yet-developed set of tools

Things which need to be done here before thix PR can be submitted:
- provide rebar3 a snapshot of "hex package registry" to avoid call to "rebar3 update" during package build (this breaks hermeticity!)

Further work:
- automate creation of pkgs/development/erlang-modules/hex/*.nix files based on rebar.config
- fetch all packages from hex.pm and create .nix files for them
- figure out how to deal with conflicting dependencies and diamond dependency graph
- figure out how if to provide multiple versions of the same package
- implement support for Elixir
- instigate discussion with Erlang community about some sort of LTS package set
- and much more along the way...

I'd love to hear some initial comments on the code to get guidance. This is my first Nixpkgs contribution.

Thanks!

### CODE REVIEW

**Comment by gleber** [comment]
@sjmackenzie FYI
@peti FYI

**Comment by gleber** [comment]
I've put registry file into repo for now, but as @obadz pointed out, this won't fly since the file is too big. I will replace it later with external git repo which would store snapshots of this file and be automatically managed by the tooling which will create .nix files for erlang packages.

**Comment by gleber** [comment]
I believe this PR is ready for inclusion. It sets up a foundation for further work and seem to be clean of deficiencies.

**Comment by sjmackenzie** [comment]
@7c6f434c. @pSub @copumpkin

**Comment by peti** [comment]
That merge should go to *master*, not to the release-15.09 branch. We can cherry-pick from master back into the release-15.09 branch later, once we're sure the code is stable, but I wouldn't do that initially.

**Comment by gleber** [comment]
I'm closing this PR and re-creating it onto master (there's no way to change base of the PR in GitHub).

**Pull request closed without merging**
