### PR TITLE
gnome-network-displays: 0.90.5 → 0.92.1

### PR DESCRIPTION
**Pull request by kevincox**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by kevincox** [comment]
Result of `nixpkgs-review pr 285395` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gnome-network-displays</li>
  </ul>
</details>

**Comment by kevincox** [comment]
Unless you feel strongly I would like to sort the imports/variables. It at least gives some consistency to them. The lines are just moved not changed so I don't think it makes much difference. 

I'll add in your comment.

**Comment by doronbehar** [comment]
> Unless you feel strongly I would like to sort the imports/variables.

What is the reasonning behind how you sorted them? I really like small diffs TBH.

**Comment by kevincox** [comment]
Just lexicographically.

**Comment by doronbehar** [comment]
I don't see any value in lexicographic ordering TBH, I think that ordering inputs according to their essentially is best. However, I won't insist, and since I'm not even using this package anymore, you may as well become a maintainer of it instead of me. Since I still care for this package a bit, I'd still be more prone to approve this reordering in a separate commit, as it's not part of the update IMO.

**Comment by kevincox** [comment]
> I think that ordering inputs according to their essentially is best.

The problem with this is that it is very subjective. Is `gtk` more important because it provides the UI or `avahi` because it provides the chromecast feature. At least lexicographic is easy to define.

I have other PRs open where the reviewer won't approve because I didn't re-sort all attributes in the file lexicographically. Seems clear that we need a policy on this one.

But as you are the maintainer I will just minimize the diff for now. Until we have a nixpkgs-wide policy maintainers rule. IMHO.

**Comment by doronbehar** [comment]
> Seems clear that we need a policy on this one.

I agree. And I think the current unwritten policy is that whatever policy the maintainer wishes to hold is the policy, unless they are unresponsive of course.

> But as you are the maintainer I will just minimize the diff for now. Until we have a nixpkgs-wide policy maintainers rule. IMHO.

Thanks for obliging, and feel free to join the maintainership :).

**Pull request merged**
