### PR TITLE
staging-next 2023-07-17

### PR DESCRIPTION
**Pull request by vcunat**
##### Helpful links

- workflow docs: https://nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy
- important jobs:
  https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
  https://hydra.nixos.org/job/nixos/staging-next-small/tested
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next
  https://hydra.nixos.org/jobset/nixos/staging-next-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/241951
- - - 
##### Mass breakages
(will be edited based on progress; just a subset)
- [x] `virtualbox`  ([link below](#issuecomment-1642521889))

### CODE REVIEW

**Comment by vcunat** [comment]
Mass darwin regressions:
 - [ ] numpy
   https://github.com/NixOS/nixpkgs/pull/244250
 - [ ] `librsvg` on x86_64-darwin
   https://hydra.nixos.org/build/228260856/nixlog/3/tail

**Comment by reckenrode** [comment]
We’re out at lunch, but I’ll look at librsvg when we get back.

**Comment by Mindavi** [comment]
p11-kit cross-compilation:

configure: error: in `/build/source':
configure: error: cannot run test program while cross compiling
See `config.log' for more details

(will probably look closer later)

**Comment by vcunat** [comment]
p11-kit was updated via PR #240925  (but I'm not looking otherwise)

**Comment by misuzu** [comment]
numpy's tests are still broken on i686-linux
```
$ nix-build . -A pkgs.python3Packages.numpy --system i686-linux
<..................................................................................................................................>
lib/python3.10/site-packages/numpy/typing/tests/test_runtime.py::TestRuntimeProtocol::test_issubclass[_NestedSequence] PASSED [100%]

=================================== FAILURES ===================================
_________________ TestRemainder.test_float_remainder_overflow __________________

self = <numpy.core.tests.test_umath.TestRemainder object at 0xdccd4490>

    @pytest.mark.skipif(IS_WASM, reason="fp errors don't work in wasm")
    def test_float_remainder_overflow(self):
        a = np.finfo(np.float64).tiny
        with np.errstate(over='ignore', invalid='ignore'):
            div, mod = np.divmod(4, a)
            np.isinf(div)
            assert_(mod == 0)
        with np.errstate(over='raise', invalid='ignore'):
            assert_raises(FloatingPointError, np.divmod, 4, a)
        with np.errstate(invalid='raise', over='ignore'):
>           assert_raises(FloatingPointError, np.divmod, 4, a)

a          = 2.2250738585072014e-308
div        = inf
mod        = 0.0
self       = <numpy.core.tests.test_umath.TestRemainder object at 0xdccd4490>

lib/python3.10/site-packages/numpy/core/tests/test_umath.py:766:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../qbm69wdh6wylp0qxris5zppghlyg5rvm-python3-3.10.12/lib/python3.10/unittest/case.py:738: in assertRaises
    return context.handle('assertRaises', args, kwargs)
        args       = (<ufunc 'divmod'>, 4, 2.2250738585072014e-308)
        context    = None
        expected_exception = <class 'FloatingPointError'>
        kwargs     = {}
        self       = <numpy.testing._private.utils._Dummy testMethod=nop>
../qbm69wdh6wylp0qxris5zppghlyg5rvm-python3-3.10.12/lib/python3.10/unittest/case.py:200: in handle
    with self:
        args       = [4, 2.2250738585072014e-308]
        callable_obj = <ufunc 'divmod'>
        kwargs     = {}
        name       = 'assertRaises'
        self       = None
../qbm69wdh6wylp0qxris5zppghlyg5rvm-python3-3.10.12/lib/python3.10/unittest/case.py:223: in __exit__
    self._raiseFailure("{} not raised by {}".format(exc_name,
        exc_name   = 'FloatingPointError'
        exc_type   = None
        exc_value  = None
        self       = <unittest.case._AssertRaisesContext object at 0xca3e30d0>
        tb         = None
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <unittest.case._AssertRaisesContext object at 0xca3e30d0>
standardMsg = 'FloatingPointError not raised by divmod'

    def _raiseFailure(self, standardMsg):
        msg = self.test_case._formatMessage(self.msg, standardMsg)
>       raise self.test_case.failureException(msg)
E       AssertionError: FloatingPointError not raised by divmod

msg        = 'FloatingPointError not raised by divmod'
self       = <unittest.case._AssertRaisesContext object at 0xca3e30d0>
standardMsg = 'FloatingPointError not raised by divmod'

../qbm69wdh6wylp0qxris5zppghlyg5rvm-python3-3.10.12/lib/python3.10/unittest/case.py:163: AssertionError
______________________________ TestKind.test_all _______________________________

self = <numpy.f2py.tests.test_kind.TestKind object at 0xdc02f790>

    def test_all(self):
        selectedrealkind = self.module.selectedrealkind
        selectedintkind = self.module.selectedintkind

        for i in range(40):
>           assert selectedintkind(i) == selected_int_kind(
                i
            ), f"selectedintkind({i}): expected {selected_int_kind(i)!r} but got {selectedintkind(i)!r}"
E           AssertionError: selectedintkind(19): expected 16 but got -1
E           assert -1 == 16
E            +  where -1 = <fortran function selectedintkind>(19)
E            +  and   16 = selected_int_kind(19)

i          = 19
selectedintkind = <fortran function selectedintkind>
selectedrealkind = <fortran function selectedrealkind>
self       = <numpy.f2py.tests.test_kind.TestKind object at 0xdc02f790>

lib/python3.10/site-packages/numpy/f2py/tests/test_kind.py:19: AssertionError
=============================== warnings summary ===============================
lib/python3.10/site-packages/numpy/core/tests/test_numeric.py::TestNonarrayArgs::test_dunder_round_edgecases[2147483647--1]
  /nix/store/00mj9m74r1kblrpsy77jz91wcb9bp74i-python3.10-numpy-1.24.2/lib/python3.10/site-packages/numpy/core/tests/test_numeric.py:198: RuntimeWarning: invalid value encountered in cast
    assert_equal(round(val, ndigits), round(np.int32(val), ndigits))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED lib/python3.10/site-packages/numpy/core/tests/test_umath.py::TestRemainder::test_float_remainder_overflow - AssertionError: FloatingPointError not raised by divmod
FAILED lib/python3.10/site-packages/numpy/f2py/tests/test_kind.py::TestKind::test_all - AssertionError: selectedintkind(19): expected 16 but got -1
= 2 failed, 26697 passed, 1509 skipped, 1307 deselected, 32 xfailed, 5 xpassed, 1 warning in 238.82s (0:03:58) =
error: builder for '/nix/store/47vmqwg29m7846pbmllfq3v0q7hb30bb-python3.10-numpy-1.24.2.drv' failed with exit code 1;
       last 10 log lines:
       > =============================== warnings summary ===============================
       > lib/python3.10/site-packages/numpy/core/tests/test_numeric.py::TestNonarrayArgs::test_dunder_round_edgecases[2147483647--1]
       >   /nix/store/00mj9m74r1kblrpsy77jz91wcb9bp74i-python3.10-numpy-1.24.2/lib/python3.10/site-packages/numpy/core/tests/test_numeric.py:198: RuntimeWarning: invalid value encountered in cast
       >     assert_equal(round(val, ndigits), round(np.int32(val), ndigits))
       >
       > -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
       > =========================== short test summary info ============================
       > FAILED lib/python3.10/site-packages/numpy/core/tests/test_umath.py::TestRemainder::test_float_remainder_overflow - AssertionError: FloatingPointError not raised by divmod
       > FAILED lib/python3.10/site-packages/numpy/f2py/tests/test_kind.py::TestKind::test_all - AssertionError: selectedintkind(19): expected 16 but got -1
       > = 2 failed, 26697 passed, 1509 skipped, 1307 deselected, 32 xfailed, 5 xpassed, 1 warning in 238.82s (0:03:58) =
       For full logs, run 'nix log /nix/store/47vmqwg29m7846pbmllfq3v0q7hb30bb-python3.10-numpy-1.24.2.drv'.
```

**Comment by vcunat** [comment]
I think there's just one more case of many builds regressing due to a single failure:
- [ ] `python3Packages.opentelemetry-api`  (all platforms)
  https://hydra.nixos.org/build/228180229/nixlog/3/tail

Overall a few hundred builds regressed.  I expect much is due to boost update (PR #240604) and can be worked around by simply pinning the failed packages to an older version. A good comparison should be
 https://hydra.nixos.org/eval/1797772?compare=1797763#tabs-now-fail

**Pull request merged**
