### PR TITLE
kor: initial at 0.3.0

### PR DESCRIPTION
**Pull request by ivankovnatsky**
## Description of changes

Package: https://github.com/yonahd/kor.
Description: A Golang Tool to discover unused Kubernetes Resources.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by onemoresuza — COMMENTED** [review]
# Reviewed points

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>kor</li>
  </ul>
</details>

- [ ] package path fits guidelines
	- The new `pkgs/by-name` directory is preferred to the old category
	hierarchy --- see [here](https://github.com/NixOS/nixpkgs/blob/491af1f1cc28df11dfbff049da4134c37d58aee9/pkgs/by-name/README.md?plain=1#L1)
- [X] package name fits guidelines
- [X] package version fits guidelines
- [X] package builds on x86_64-linux
- [X] executables tested on x86_64-linux
- [X] all depending packages build
- [X] `meta.description` is set and fits guidelines
- [X] `meta.license` fits upstream license
- [X] `meta.platforms` is set
	- Set by [`buildGoModule`](https://github.com/NixOS/nixpkgs/blob/4fc20754d8798adfb6570a0b33af022b7d2360da/pkgs/build-support/go/module.nix#L296)
- [X] `meta.maintainers` is set
- [ ] `meta.mainProgram` can be and is provided
	- The package provides one binary, `kor`; it may be set as the
	`meta.mainProgram` attribute
- [X] build time only dependencies are declared in `nativeBuildInputs`
- [X] source is fetched using the appropriate function
- [X] the list of `phases` is not overridden
- [X] when a phase (like `installPhase`) is overridden it starts with `runHook preInstall` and ends with `runHook postInstall`.
- [X] patches have a comment describing either the upstream URL or a reason why the patch wasn't upstreamed
- [X] patches that are remotely available are fetched rather than vendored

# Possible Improvements

1. The project should be on `pkgs/by-name/ko/kor/package.nix`. By doing this,
   the addition to `pkgs/all-packages.nix` may be removed.
1. The expected binary of the project seems to be `$out/bin/kor` --- as it may
   be seen from `tree`'s output below. So, it should be its `meta.mainProgram`.
	```console
	[user@hostname:~/nixpkgs]$ tree ./result # after `nix-build -A kor`
	result/
	└── bin
		└── kor

	2 directories, 1 file
	```
1. The check phase may be simplified by adding the following and removing the
   `checkPhase` override:
	```nix
	preCheck = ''
	  HOME="$(mktemp -d)"
	  export HOME
	'';
	```
1. The `kor` project had a [release](https://github.com/yonahd/kor/releases/tag/v0.3.0) in the meanwhile. It may be worth it to bump the version to it.

**Comment by onemoresuza** [comment]
Result of `nixpkgs-review pr 267199` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>kor</li>
  </ul>
</details>

**Review by onemoresuza — APPROVED** [review]

**Comment by ivankovnatsky** [comment]
@onemoresuza can I please ask you if you generated this list using software or you did it manually? 
image

**Comment by onemoresuza** [comment]
Sure!

It was manually generated based on the [New Packages Section][new-packages-section]
of the the `README` file under the `pkgs/` directory.

[new-packages-section]: <https://github.com/NixOS/nixpkgs/blob/d3fcdeccae0b3e2504493a6a4147a65f49e77630/pkgs/README.md?plain=1#L764>

**Comment by ivankovnatsky** [comment]
> Sure! It was manually generated based on the New Packages Section[1] of the the `README` file under the `pkgs/` directory. [1]: https://github.com/NixOS/nixpkgs/blob/d3fcdeccae0b3e2504493a6a4147a65f49e77630/pkgs/README.md?plain=1#L764

Got it, thanks!

**Pull request merged**
