### PR TITLE
tektoncd-cli: init at 0.13.0

### PR DESCRIPTION
**Pull request by mstrangfeld**
###### Motivation for this change
The Tekton CLI is great for interacting with Tekton pipelines and should definitely be in the nixpkgs repository.

Official website: https://tekton.dev/
Git Repository: https://github.com/tektoncd/cli

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 06kellyjac** [comment]
Thanks for the PR @mstrangfeld. I've been using a similar nix expression for a while myself, `tkn` is quite nice to use so far!

I've made a couple of changes/suggestions on a separate branch
https://github.com/06kellyjac/nixpkgs/tree/tektoncd-cli
Feel free to cherry-pick or copy/paste any you agree with.

I've successfully installed and ran `tkn version` for both your branch & my changes on nixos (x86_64) and archlinux (aarch64) (I can test it on macOS too maybe later today)

If you dont mind I'd be happy to maintain this with you. I'm down in the nixpkgs maintainers file as `jk`

**Comment by mstrangfeld** [comment]
Thank you for the suggestions @06kellyjac. I would be glad to have some help maintaining this. I have just copy/pasted your suggestions so this addition does not exceed one commit.

**Review by 06kellyjac — APPROVED** [review]
LGTM

**Comment by 06kellyjac** [comment]
Result of `nixpkgs-review pr 95320` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>tektoncd-cli</li>
  </ul>
</details>

**Comment by 06kellyjac** [comment]
- [X] reviewed the diff and commit messages
- [X] made sure ofBorg build succeeded for all applicable platforms
- [X] run nix-review for a reasonable amount of time without any failures (or marked preexisting failures as broken)

**Pull request merged**
