### PR TITLE
wrapPythonProgram: use site.addsitedir instead of PYTHONPATH

### PR DESCRIPTION
**Pull request by abbradar**
###### Motivation for this change

Consider two applications, "a" and "b". "a" uses Python 2.7 and enum34, which exports `enum` module. It calls "b" via exec, which uses Python 3.5. In this Python there's its own `enum` module, but it's overridden by enum34 because it's in `PYTHONPATH`. As a result `enum` module doesn't work and there are weird errors.

Real life example: `gajim` calls `qutebrowser` to open an URL, which crashes instead.

I don't know any better solution to this problem than the proposed patch. It looks good to me but it can potentially break some workflows which somehow rely on `PYTHONPATH` postfixes.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @domenkozar

### CODE REVIEW

**Comment by FRidh** [comment]
@abbradar I think the problem you describe is basically https://github.com/NixOS/nixpkgs/issues/11423.
https://github.com/NixOS/nixpkgs/issues/11423#issuecomment-238465989 works well for that.

@garbas, you proposed this solution as well, right?

**Comment by abbradar** [comment]
@FRidh I think the problem is somewhat different. The problem that is described there IIUC is that when you put a derivation into `propagatedBuildInputs`, you get not only its binaries but also its Python modules in your `PYTHONPATH`. `buildEnv` works nicely to isolate that. This one is messier -- inside any Python executable `PYTHONPATH` is set to its dependencies closure, and when it tries to `exec` another Python executable, the other one prefixes its `PYTHONPATH` to the first one, and hilarity ensues.

**Comment by FRidh** [comment]
Therefore I think we shouldn't set/prefix `PYTHONPATH` at all, and use `buildEnv` with  `--set PYTHONHOME`. It requires a lot of work though; a solution would have to be found for the `checkPhase`  and all the code outside `python-packages.nix` that sets `PYTHONPATH` would have to use `python.buildEnv`.

Anyway, until then I think I am fine with this change as I don't add anything to `PYTHONPATH`.

**Comment by abbradar** [comment]
Oh, I got it now -- yes, it would help. BTW this patch can be a small preparation step -- if anything relies on prefixing `PYTHONPATH` it would not work with your idea easily, and others who set it can be probably converted into `buildEnv` much more straightforwardly. This patch would force us to fix the first cases, if any.

**Comment by FRidh** [comment]
On second thought, while I don't set or append/prepend to `PYTHONPATH` myself, I think it is an important enough feature that we shouldn't break that possibility, and therefore shouldn't use `--set PYTHONPATH`.

**Comment by garbas** [comment]
i consider usage of ``-prefix`` a bug. some programs will break or behave differently just because somewhere in environment there is a PYTHONPATH defined. i'm strongly about merging this asap.

**Comment by FRidh** [comment]
> some programs will break or behave differently just because somewhere in environment there is a PYTHONPATH defined.

Agreed. And therefore we should solve the root of the problem: stop using `PYTHONPATH` in our wrappers to find Python modules.

> we should never allow to extend PYTHONPATH this way 

`PYTHONPATH` is a Python feature. People will want to be able to use it. Using `--set` completely takes away that possibility. 

> but provide a way (eg. via buildEnv) to create custom python environments.

We can add an option to `buildEnv` to modify `PYTHONPATH`, either on a per-application basis, or for the whole environment. We let `buildEnv` set or unset `PYTHONPATH`.

**Comment by adnelson** [comment]
This LGTM and would fix some issues I've had. Agreed that a better solution would be nice.

**Comment by garbas** [comment]
for me this is a quick improvement over currently (for me) broken way how we handle python binaries. i got bitten by this bug many times and in all my projects i've been using ``--set`` instead of ``--prefix`` for exactly this reason.

this PR wont fix everything in python but it for sure will make python stuff more reproducible across machines.

i would like to merge this, but i would also like some comments on this subject from @domenkozar and @bennofs

**Comment by bennofs** [comment]
100% agree with this patch. I didn't know it used `--prefix` before, that seems like madness to me! Python applications' PYTHONPATH should not depend on the environment they run in.

**Comment by garbas** [comment]
also another thing. is this triggering a mass-rebuild? i think we could easily apply this directly to master. yes quite few packages will need to be rebuilt but nothing than hydra can not handle. @domenkozar you thoughts on this?

**Comment by domenkozar** [comment]
I don't see a reason from top of my head where `--prefix` would be useful, so +1 from me.

**Comment by FRidh** [comment]
I think this breaks
```
nix-shell -p pythonPackages.ipython pythonPackages.numpy --run "ipython -c 'import numpy'"
```
because `ipython` won't be able to find `numpy`. Testing now.

(Note that I anyway think we should replace this kind of usage with `buildEnv`)

**Comment by FRidh** [comment]
invoking `pytest` already fails in checkPhase

**Comment by abbradar** [comment]
Hm, I'll try to test this more extensively and see what happens (I haven't built anything big with this because of lack of CPU time. I don't even remember what exactly, I think maybe `pip`).

**Comment by adnelson** [comment]
`ipython` is certainly one case where you wouldn't want an executable to set their own (complete) pythonpath. But it's in the minority for sure... maybe an opt-in pythonpath prefix would be better? It would be simple to make it an option in buildPythonPackage.

**Comment by abbradar** [comment]
Hm, indeed, IPython is a special case. I'm now trying an [alternative patch](https://github.com/abbradar/nixpkgs/commit/727b71d7ff1f781212df56d28c5edbc9d2585069) which removes all meddling with `$PYTHONPATH` at all and instead inserts needed paths to `sys.path`. This gives us absence of dreaded `$PYTHONPATH` propagation while not disabling it completely. A downside is further complication of The Magical sed Expression. IPython seems to work with this.

**Comment by adnelson** [comment]
We could also skip using `PYTHONPATH` and use [`PYTHONHOME`](https://docs.python.org/2/using/cmdline.html#envvar-PYTHONHOME) instead. `PYTHONHOME` would point to what `PYTHONPATH` currently points to, and then `PYTHONPATH` could be set at runtime to whatever.

```bash
                 local -a wrap_args=("$f"
                                 --set PYTHONHOME':' "$program_PYTHONPATH"
                                 --prefix PATH ':' "$program_PATH:$dir/bin")
```

I haven't tested this out yet but it seems perhaps promising?

**Comment by FRidh** [comment]
@adnelson and now you've broken `buildEnv`, because it cannot use `--set PYTHONHOME` anymore

**Comment by abbradar** [comment]
I thought that `PYTHONHOME` should be one path which point to Python "home", that is binaries and libraries. @FRidh proposed to build environments with all dependencies and set `PYTHONHOME` to them but without such an environment I don't think it can be used...

**Comment by adnelson** [comment]
@FRidh I haven't broken anything yet :wink: I didn't realize that's what `buildEnv` did, good call

**Comment by abbradar** [comment]
BTW to clarify my thoughts towards @FRidh proposition: I like it much more than the current situation, and I think we probably should go there in the long run. However, I experience a broken browser when called from my IM client right now and I suspect that there are more breakages like this in the wild. `buildEnv` proposition requires a lot of work (grep for `PYTHONPATH` to get a rough estimate) and we need something to plug the leak now...

**Comment by bennofs** [comment]
I actually think that using PYTHONHOME is not such a bad idea: you could establish the convention that PYTHONHOME is to be used for the "application-dependencies", i.e. things that for example ipython itself depends on. The PYTHONPATH would be used to add any additional dependencies then, like plugins etc.

**Comment by adnelson** [comment]
So couldn't we point `PYTHONHOME` to a call to `buildEnv` on the `propagatedBuildInputs`?

Something (conceptually, cuz I have no idea) along the lines of

```nix
mkDerivation {
  postInstall = ''
    for bin_file in $out/bin; do
      makeWrapper $bin_file \
        --set PYTHONHOME ${buildEnv {paths = propagatedBuildInputs;}}
  '';
}
```

**Comment by FRidh** [comment]
@adnelson and what is that derivation? It cannot be the actual package, it has to be outside of that or it wouldn't be a DAG. Here we're back to my suggestion of https://github.com/NixOS/nixpkgs/pull/16672. It's really easy actually, as you see in the implementation. And we could choose for now to keep `wrapPythonPrograms`.

@bennofs Do you mean adding to PYTHONPATH with Nix, or outside of Nix?

**Comment by bennofs** [comment]
@FRidh you could do both, doesn't matter.

**Comment by FRidh** [comment]
@bennofs Let's see how that works with @abbradar 's example. Each package would have a `PYTHONHOME` that points to itself, right. Dependencies would have to be symlinked then in `buildPythonPackage`. 

Now the user wants to add something to `PYTHONPATH` of application `a`, say a plugin which depends on `enum`. `b` also needs `enum` but is a different Python version. What will happen?

**Comment by abbradar** [comment]
I've replaced this patch to use `sys.path` via the sed expression now. This fixes IPython and `PYTHONPATH` usage in general.

**Comment by adnelson** [comment]
@FRidh that would be part of `buildPythonPackage`. Since I'm not familiar with `buildEnv`, here's an idea using symlinks in the derivation's `site-packages` folder. There are multiple similar ways to do this but the idea is that there is some folder which contains a package's entire python closure, and we set `PYTHONHOME` to that.

```nix
postInstall = ''
  # Symlink everything available from the python path to this folder 
  for python_path in $(echo $program_PYTHONPATH | tr : '\n'); do
    for item in $python_path/*; do
      ln -s $item $out/${python.sitePackages}/$(basename $item)
    done
  done

  # Wrap generated binaries
  for bin_file in $out/bin; do
    makeWrapper $bin_file \
      --set PYTHONHOME $out/${python.sitePackages} \
      --prefix PATH : $PATH
  done
'';
```

**Comment by adnelson** [comment]
@abbradar doesn't the change you made just reproduce the original behavior? Because the program will still inherit an external pythonpath, no?

**Comment by abbradar** [comment]
@adnelson Yes, my intent was not to disable `PYTHONPATH` completely. The problem was that nested programs inherit `PYTHONPATH`s because environment is inherited via `exec`. `sys.path`, on the other hand, is local to the current running Python program, so each one would get only its individual paths.

**Comment by adnelson** [comment]
@abbradar ah that makes sense. So this is at least an improvement :wink:

**Comment by abbradar** [comment]
@adnelson I actually don't think that we want to disable `PYTHONPATH` completely -- it's like `LD_LIBRARY_PATH` and friends and one sets it at his own risk. As we've discovered, IPython for example uses it internally. As long as it's not built up from nested applications like before I think it's fine.

**Comment by adnelson** [comment]
@abbradar gotcha :+1:

**Comment by FRidh** [comment]
@abbradar (so far) I haven't found any issues with the new proposal :+1:

**Comment by abbradar** [comment]
Ironically this doesn't solve my own problem with `gajim` because it has custom code setting `PYTHONPATH`. I think of refactoring `wrap.sh` so that it can be called for individual Python files -- this would allow people to use this patcher in more ways, hopefully avoiding setting anything my themselves. To avoid two mass-rebuilds I'll try to do it this evening so that it can (hopefully) be merged simultaneously.

**Comment by abbradar** [comment]
Pheew. Gajim was not so easy I hoped. This patchset finally fixes it and also fixes https://github.com/NixOS/nixpkgs/issues/16133:

* We now use `site.addsitedir` instead of `sys.path` -- with this, `.pth` files are correctly resolved;
* I have fixed Sed expression to properly handle Gajim and also scfbuild;
* `wrapPythonProgram` has been split and used for Gajim instead of custom `PYTHONPATH` prefixing.

**Comment by abbradar** [comment]
There was interest expressed in this patch and we now don't break `PYTHONPATH` so I want to merge it. Before it, however, it would be nice to get a review of `magicalSedExpression` changes. Not the expression itself but rather the new inserted preamble -- in particular, is `import functools` acceptable?

**Comment by FRidh** [comment]
@abbradar I can't think of any issues with the updated proposal. I've tested some Python environments and there I didn't encounter any issues (and I wouldn't expect that either). 

Can you squash some of the commits? And update in the Python docs under `buildPythonPackage` the part about `wrapPythonPrograms`. Putting in the `wrapPython` Nix expression a couple of lines what the preamble is for would be nice as well.

**Comment by abbradar** [comment]
Updated and added documentation. Regarding squashing: I'm not sure what to squash. Usually I make a commit per finished change in existing code -- those all seem more or less independent.

**Comment by RonnyPfannschmidt** [comment]
that looks awesome, can this fix tox ?

#16591
#15224

**Comment by abbradar** [comment]
Sadly I don't think so (this doesn't affect `nix-shell`). However, in case of `tox` I think we can wrap it to unset `PYTHONPATH`. Because now it has all the dependencies patched in it should work -- I'm not sure this won't break any usecases though.

**Comment by RonnyPfannschmidt** [comment]
atm tox is broken because it puts packages from its environment into the virtualenvs at setup time and then isolates them away at the other level

tox would work fine if it was not wrapped by the pythonpath thing

**Comment by abbradar** [comment]
This shouldn't be a problem already I think because there's no `PYTHONPATH` set for Tox itself now. I was rather talking about case when it's called from nix-shell which sets its own `PYTHONPATH`.

**Comment by RonnyPfannschmidt** [comment]
will this change hit 16-09 ?? - i just did a nix-env -i for tox and it has a wrapper

**Comment by abbradar** [comment]
It should have, a long time ago.

**Comment by RonnyPfannschmidt** [comment]
i am on a 16.09 channel, just updated my channels and installed tox

**Comment by RonnyPfannschmidt** [comment]
same for unstable channel

**Comment by abbradar** [comment]
```
 nixpkgs git:(master) ✗ nix-build -A pythonPackages.tox
ca/nix/store/bm5hyq5rhhrjrs85alai3gph1kq1yb53-python2.7-tox-2.3.1
 nixpkgs git:(master) ✗ cat result/bin/tox
#! /nix/store/nyj6xd7s1n1w8c0xdwk5ddhi7bjcyi9x-bash-4.3-p46/bin/bash -e
export PATH=/nix/store/hdny4a03ys50hh56k6z1w3z8sl0hf2ym-python-2.7.12/bin:/nix/store/bm5hyq5rhhrjrs85alai3gph1kq1yb53-python2.7-tox-2.3.1/bin:/nix/store/p5n1lbm3rs3d4bkpq249fg5rs2iw8kp2-python2.7-setuptools-26.1.1/bin:/nix/store/yk4qqqxq91gjd7jp2i114dywh1f2xfaw-python2.7-virtualenv-15.0.3/bin${PATH:+:}$PATH
exec -a "$0" /nix/store/bm5hyq5rhhrjrs85alai3gph1kq1yb53-python2.7-tox-2.3.1/bin/.tox-wrapped "${extraFlagsArray[@]}" "$@"
 nixpkgs git:(master) ✗ 
```

So it's in master at least, and given that the change was merged long before `release-16.09` fork it should be there, too.

**Comment by RonnyPfannschmidt** [comment]
@domenkozar any chance to see this in 16.09?

**Comment by abbradar** [comment]
@RonnyPfannschmidt As I've said it should be in 16.09 already but jsut to be sure I checked:
```
 nixpkgs git:(release-16.09) ✗ nix-build -A pythonPackages.tox
/nix/store/d1ri3241dnyl17hk2rqcbp3s5s740ng2-python2.7-tox-2.3.1
 nixpkgs git:(release-16.09) ✗ cat result/bin/tox
#! /nix/store/migghb7advw9a6hxi3vhyw2kyyxlyihx-bash-4.3-p46/bin/bash -e
export PATH=/nix/store/1940biik22bz5kc5fv1mnd2nzhc58k6m-python-2.7.12/bin:/nix/store/d1ri3241dnyl17hk2rqcbp3s5s740ng2-python2.7-tox-2.3.1/bin:/nix/store/agx8kbmp982gcbqcsxx3iy4s1n52z8pb-python2.7-setuptools-26.1.1/bin:/nix/store/x32przfwf4cl3wgybm2dpr5dvx588wp9-python2.7-virtualenv-15.0.3/bin${PATH:+:}$PATH
exec -a "$0" /nix/store/d1ri3241dnyl17hk2rqcbp3s5s740ng2-python2.7-tox-2.3.1/bin/.tox-wrapped "${extraFlagsArray[@]}" "$@"
 nixpkgs git:(release-16.09) ✗ 
```

**Comment by domenkozar** [comment]
@RonnyPfannschmidt does this fix the tox issue for you on master?

@FRidh any reason not to backport this to 16.09? It's quote late for such big python change..

**Comment by abbradar** [comment]
@domenkozar Again, this is _already_ in 16.09 -- see also for example https://github.com/NixOS/nixpkgs/commit/db31282f087f4100e7d7845f34ce888c42ac6fd3 (notice `16.09-beta` tag).

**Comment by RonnyPfannschmidt** [comment]
```
nix-channel --update
downloading Nix expressions from ‘https://nixos.org/releases/nixos/16.09/nixos-16.09beta264.aadcffc//nixexprs.tar.xz’...
downloading ‘https://nixos.org/releases/nixos/16.09/nixos-16.09beta264.aadcffc//nixexprs.tar.xz’... [3776/8658 KiB, 3355.2 KiB/s]
downloading Nix expressions from ‘https://nixos.org/releases/nixpkgs/nixpkgs-17.03pre91280.b32252d//nixexprs.tar.xz’...
downloading ‘https://nixos.org/releases/nixpkgs/nixpkgs-17.03pre91280.b32252d//nixexprs.tar.xz’... [3520/7663 KiB, 3355.2 KiB/s]
unpacking channels...
```

is this perhaps an issue with the channel lagging behind the branch?

**Comment by abbradar** [comment]
Hm, I think you have an old `tox` in your `PATH` somehow. Try running `nix-build -A pythonPackages.tox '<nixpkgs>'` and see what you have in `result`.

**Comment by RonnyPfannschmidt** [comment]
```
$ git branch
  gnome-online-account-wrapGAppsHook
  gnome-onlineaccoutns-use-wrapGAppsHook
* master
  nixos-unstable
  nixpkgs-unstable
  release-16.03
  wrapGAppsHook
$ nix-build . -A pythonPackages.tox
/nix/store/bm5hyq5rhhrjrs85alai3gph1kq1yb53-python2.7-tox-2.3.1
$ cat result/bin/tox
#! /nix/store/nyj6xd7s1n1w8c0xdwk5ddhi7bjcyi9x-bash-4.3-p46/bin/bash -e
export PATH=/nix/store/hdny4a03ys50hh56k6z1w3z8sl0hf2ym-python-2.7.12/bin:/nix/store/bm5hyq5rhhrjrs85alai3gph1kq1yb53-python2.7-tox-2.3.1/bin:/nix/store/p5n1lbm3rs3d4bkpq249fg5rs2iw8kp2-python2.7-setuptools-26.1.1/bin:/nix/store/yk4qqqxq91gjd7jp2i114dywh1f2xfaw-python2.7-virtualenv-15.0.3/bin${PATH:+:}$PATH
exec -a "$0" /nix/store/bm5hyq5rhhrjrs85alai3gph1kq1yb53-python2.7-tox-2.3.1/bin/.tox-wrapped "${extraFlagsArray[@]}" "$@"
$ git describe
16.09-beta-944-ga0b643e
```

**Comment by abbradar** [comment]
This already does contain this change (notice absence of `PYTHONPATH` exports). Maybe the problem is with something else...

**Comment by RonnyPfannschmidt** [comment]
nm, i missed that detail

on the 16.09 branch i get the same output - i was confused by the different output path

the behaviour is indeed correct
now for tools like tox it would be nice if they either had no PATH at all or used it differently

but thats something that can change in future

as far as i can tell your change correctly and nicely fixes the 2 issues i posted

**Comment by RonnyPfannschmidt** [comment]
oh, wait ,not completely

tox is fixed, PYTHONPATH is still leaking into nix-shell

**Comment by abbradar** [comment]
Can you perhaps submit a PR for this? The workaround should be quite simple -- you need to add `--set PYTHONPATH ""` to `makeWrapperArgs` for the `tox` derivation.

**Comment by RonnyPfannschmidt** [comment]
imho there should be a default decision on what nix python programs do wrt inheriting pythonpath

users tend to use it, so its certainly valid - a tool in nix that does filter nix store paths out of env vars in wrappers might be whats helpfull

**Comment by FRidh** [comment]
`PYTHONPATH` in nix-shell is set with a setup hook, and has a different purpose. I hope with `nix use` setup hooks won't be run, and `PYTHONPATH` therefore won't be set.

**Comment by RonnyPfannschmidt** [comment]
@FRidh sounds perfect, i'd like to be free of nix-shell, from my POV its a tool for developing nix packages, not using them in develpment environments

**Comment by FRidh** [comment]
Currently we add the following to scripts
```
preamble = ''
          import sys
          import site
          import functools
          sys.argv[0] = '"'$(readlink -f "$f")'"'
          functools.reduce(lambda k, p: site.addsitedir(p, k), ['"$([ -n "$program_PYTHONPATH" ] && (echo "'$program_PYTHONPATH'" | sed "s|:|','|g") || true)"'], site._init_pathinfo())
        '';
```
and we also create a wrapper. I don't think we should do both. In case of Python code, we should add this code, and in the case of a non-Python program, we should create a wrapper.

The wrappers can be problematic, e.g. when the program that is wrapped calls itself using `python program args` instead of `./program args`.

I would like to make the following change:
1. in case of Python code, we patch the shebang and optionally add the preamble. Python applications will be able to find the modules they require if the preamble is added. They can find the interpreter because we patched the shebang, but they cannot find additional scripts provided by the application or dependencies because they're not on `PATH`. In the long run we might want to get rid of the preamble.
2. we do not create wrappers in Python package derivations, but, a bit like with KDE, we have a `${name}-${version}-wrapped`. Here we use either the wrappers as we have now, or my `buildEnv` approach. Any manual wrapping would also be done here in the `fixupPhase`. We add `wrapped` and `unwrapped` attributes.

Important is that `${name}-${version}-wrapped` doesn't set `pythonPath` so its `site-packages` isn't added by the setup-hook.

**Pull request merged**
