### PR TITLE
lightdm: 1.18.1 -> 1.22.0

### PR DESCRIPTION
**Pull request by ndowens**
###### Motivation for this change
Update

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by obadz** [comment]
Worked for me!

**Comment by obadz** [comment]
hmmm @ndowens, how did you get comfortable that the patch was no longer required?

**Comment by ndowens** [comment]
Looked at it and also didn't compile with it

**Comment by obadz** [comment]
Ok I guess let's go with it in master for now…

**Comment by obadz** [comment]
@wkennington, looks like you authored the patch in 3988cfcbff. Feel free to opine :)

**Pull request merged**
