### PR TITLE
python311Packages.scikit-survival: 0.21.0 -> 0.22.1; fix build

### PR DESCRIPTION
**Pull request by ghost**
## Description of changes
update to 0.22.1 fixes broken build
https://github.com/sebp/scikit-survival/releases/tag/v0.22.1
https://github.com/sebp/scikit-survival/releases/tag/v0.22.0

https://hydra.nixos.org/build/239166746
ZHF: #265948

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by robert-manchester** [comment]
Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python310Packages.scikit-survival</li>
    <li>python310Packages.scikit-survival.dist</li>
    <li>python311Packages.scikit-survival</li>
    <li>python311Packages.scikit-survival.dist</li>
  </ul>
</details>

**Comment by robert-manchester** [comment]
ZHF: #265948

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 266019` at a0370a39 run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/natsukium/2dffc3264ac2b38d6369a4b8f4d6934f">python310Packages.scikit-survival</a></li>
    <li><a href="https://gist.github.com/natsukium/350e565ded1cd6d55dcf53b891ab02a9">python311Packages.scikit-survival</a></li>
  </ul>
</details>

**Comment by wamserma** [comment]
Result of `nixpkgs-review pr 266019` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python310Packages.scikit-survival</li>
    <li>python310Packages.scikit-survival.dist</li>
    <li>python311Packages.scikit-survival</li>
    <li>python311Packages.scikit-survival.dist</li>
  </ul>
</details>

**Comment by wamserma** [comment]
> Result of `nixpkgs-review pr 266019` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)

Please adjust `meta.broken`.

**Comment by natsukium** [comment]
I don't think this is a significant error.
We just need to add this test to disabledTests as a flaky one.
```
>           return func(*args, **kwds)
E           AssertionError: 
E           Arrays are not almost equal to 5 decimals
E           alphas[22] [0].a mismatch
E           Mismatched elements: 1 / 1 (100%)
E           Max absolute difference: 2.79955566e-05
E           Max relative difference: 1.03381292e-12
E            x: array(27079905.88052)
E            y: array(27079905.8805)
```

<details><summary></summary>

```
=================================== FAILURES ===================================
_ TestCoxnetBaselineModel.test_baseline_predict[predict_cumulative_hazard_function-False] _

self = <test_coxnet.TestCoxnetBaselineModel object at 0x168aed4e0>
breast_cancer = (     X200726_at  ...  size
0     10.926361  ...   3.0
1     12.242090  ...   3.0
2     11.661716  ...   2.5
3     12.... True,  404.), (False, 2225.),
       (False, 2722.), (False, 1781.)],
      dtype=[('e.tdm', '?'), ('t.tdm', '<f8')]))
fn = 'predict_cumulative_hazard_function', normalize_options = False

    @pytest.mark.parametrize("fn", ["predict_survival_function", "predict_cumulative_hazard_function"])
    def test_baseline_predict(self, breast_cancer, fn, normalize_options):
        X, y = breast_cancer
    
        coxnet_1, coxnet_2, X_test, X_test_t = self._fit(X, y, normalize_options)
    
        time_points = np.unique(y["t.tdm"])
    
        for k, (a_1, a_2) in enumerate(zip(coxnet_1.alphas_, coxnet_2.alphas_)):
            pred_1 = getattr(coxnet_1, fn)(X_test, alpha=a_1)
            pred_2 = getattr(coxnet_2, fn)(X_test_t, alpha=a_2)
    
            for i, (f1, f2) in enumerate(zip(pred_1, pred_2)):
>               assert_array_almost_equal(f1.a, f2.a, 5, err_msg=f"alphas[{k}] [{i}].a mismatch")

tests/test_coxnet.py:1327: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/nix/store/ak3zf631ws2rwsl5qq0x3v7j18h0c2jj-python3-3.10.13/lib/python3.10/contextlib.py:79: in inner
    return func(*args, **kwds)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = (<function assert_array_almost_equal.<locals>.compare at 0x16996dd80>, 27079905.88052468, 27079905.880496684)
kwds = {'err_msg': 'alphas[22] [0].a mismatch', 'header': 'Arrays are not almost equal to 5 decimals', 'precision': 5, 'verbose': True}

    @wraps(func)
    def inner(*args, **kwds):
        with self._recreate_cm():
>           return func(*args, **kwds)
E           AssertionError: 
E           Arrays are not almost equal to 5 decimals
E           alphas[22] [0].a mismatch
E           Mismatched elements: 1 / 1 (100%)
E           Max absolute difference: 2.79955566e-05
E           Max relative difference: 1.03381292e-12
E            x: array(27079905.88052)
E            y: array(27079905.8805)

/nix/store/ak3zf631ws2rwsl5qq0x3v7j18h0c2jj-python3-3.10.13/lib/python3.10/contextlib.py:79: AssertionError
```
</details>

**Review by wamserma — APPROVED** [review]

**Comment by robert-manchester** [comment]
> I don't think this is a significant error. We just need to add this test to disabledTests as a flaky one.

ok. i disabled it for darwin && aarch64 -- assuming it is deterministic and platform dependent as it passes aarch64 linux. waiting to see results from x64 darwin though after 7 hours build was still in the queue before last update.

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 266019` at 20e41e0a run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python310Packages.scikit-survival</li>
    <li>python311Packages.scikit-survival</li>
  </ul>
</details>

**Review by natsukium — APPROVED** [review]

**Pull request merged**
