### PR TITLE
vector: 0.22.3 -> 0.23.0

### PR DESCRIPTION
**Pull request by happysalada**
###### Description of changes

this adds a couple of breaking changes, amongst which is a new way to pass in secrets.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
This also includes a small change in the feature set.
I'm going to merge as this is unlikely to attract any attention.
Happy to take care of anything later if need be.

**Comment by dhess** [comment]
I'm getting an odd config validation failure at build time since this change:

```
 '/nix/store/1bd74jllwzd7c34jakkyq6p2d82yxmax-validate-vector-conf.drv' failed with exit code 78;
       last 4 log lines:
       > Failed to load ["/nix/store/nq6bmwzy8yyl1wzdlxlqg1nx0wmrzbs8-vector.toml"]
       > --------------------------------------------------------------------------
       > x unknown variant `http`, expected `unit_test` for key `sinks.logtail`
```

My `services.vector.settings` is unchanged, and the `.toml` file that it generates is identical to previous versions' generated configuration. I don't see anything in the Vector 0.23 release notes that seems relevant.

FYI, the full config is:

```nix
        services.vector = {
          enable = true;
          journaldAccess = true;
          settings = {
            sources = {
              journald = {
                type = "journald";
                since_now = true;
              };
            };
            transforms = {
              logtail_transform = {
                type = "remap";
                inputs = [
                  "*"
                ];
                source = ''
                  .dt = del(.timestamp)
                '';
              };
            };
            sinks = {
              logtail = {
                type = "http";
                inputs = [
                  "logtail_transform"
                ];
                uri = "https://in.logtail.com/";
                encoding.codec = "json";
                auth = {
                  strategy = "bearer";
                  token = "\${LOGTAIL_VECTOR_AUTH_TOKEN}";
                };
              };
            };
          };
        };
```

**Comment by happysalada** [comment]
I briefly looked at the released notes and couldn't find anything related either.
Did you try to open an issue on the repo ?
My experience with opening issues is that they are very responsive. They broke things a couple of times and usually respond to issues within a couple of days.

**Comment by happysalada** [comment]
I'm downgrading to latest stable version until the error is figured out
https://github.com/NixOS/nixpkgs/pull/182020

**Comment by happysalada** [comment]
hey, I figured out the cause, but I can't get through to the root cause.
Somehow having a feature with a question mark in it, breaks the build in nix (it ends up not passing in any features at all).
I really don't know why.
I'm going to leave it at version 0.22.3 for now and I will disable kafka completely (by default) on the next version upgrade.
(unless someone figures out the problem, unfortunately I don't really have time).

**Pull request merged**
