### PR TITLE
lowPrio removed from rustBeta and rustUnstable

### PR DESCRIPTION
**Pull request by sjmackenzie**
###### Motivation for this change

If I have to wait through another rustUnstable and rust Beta build cycle I might just commit suicide.
###### Things done

Not committed suicide

### CODE REVIEW

**Comment by globin** [comment]
That would make rust update to rustUnstable with nix-env.

**Comment by sjmackenzie** [comment]
`nix-env -i rust` -> `rust`
`nix-env -i rustUnstable` -> `rustUnstable`
`nix-env -i rustBeta` -> `rustBeta`

How do you see rust being updated to rustUnstable?

**Comment by sjmackenzie** [comment]
@globin please explain ^

**Comment by sjmackenzie** [comment]
@7c6f434c @the-kenny @peti please review.

**Comment by sjmackenzie** [comment]
I wish we had C4.

**Comment by globin** [comment]
`nix-env -u` would update rust to rustUnstable

**Comment by sjmackenzie** [comment]
Show me *exactly* in the code where this is supposed to happen, I'm testing it out now with `nix-env -u` after installing `nix-env -i rustc`, takes time on my shitty village internet connection. I hope I'm not wasting my time cause I haven't slept and it 7am.

**Comment by sjmackenzie** [comment]
```
[stewart@rivergod:~/dev/fractalide/nixpkgs]$ nix-env -i rustc
replacing old ‘rustc-1.11.0’
installing ‘rustc-1.11.0’
 
[stewart@rivergod:~/dev/fractalide/nixpkgs]$ nix-env -u rustc
 
[stewart@rivergod:~/dev/fractalide/nixpkgs]$ 
```
@globin now do you want to explain why you voted against C4?

@the-kenny @7c6f434c @peti please review.

**Comment by sjmackenzie** [comment]
@edolstra please may we try out C4.

**Comment by globin** [comment]
If you calm down I might be interested in putting my time into trying to understand why this isn't affected but I'm quite sure you misinterpret the meaning of lowprio

**Comment by sjmackenzie** [comment]
I understand `lowprio` to mean: `Hydra don't compile this, if a user wants it then they compile it themselves.`

**Comment by fpletz** [comment]
`lowPrio` sets the `meta.priority` attribute to a low value. This means if you install both `rust` with `rustBeta` or `rustUnstable` in one environment, the binaries from rust will take precendence and are symlinked. This has nothing to do with hydra.

As the three different rust versions have different derivation names, they shouldn't be updated with `nix-env -u`.

The rust expressions mentioned above only refer to an attribute set containing `rustc` and `cargo`. Hydra won't recurse into attribute sets by default. Only the `rustc` and `cargo` from the stable rust expression are exposed a few lines below of your diff.

Apart from that, the commit does not follow our style guidelines (C4 2.3.3), its description does not indicate the desired effect (that the packages should be built by hydra, C4 2.3.7) and furthermore does not what it's supposed to do (C4 2.3.2). So even if we had C4, your patch would have no chance of being accepted in this state because it's wrong.

**Comment by the-kenny** [comment]
Ah, this is about making Hydra build the rustc-variants? We can discuss this. `lowPrio` isn't the right strategy for this though.

**Comment by sjmackenzie** [comment]
I'm working on this right now, but, need to go to a place with a better
internet connection.

What is your suggestion? I'll force update this PR.

The idea was quite nice to have Beta and Unstable not built by Hydra, I
initially supported it but I just can't do it anymore.
So this is a really painful issue for me atm.

**Comment by sjmackenzie** [comment]
The reason? All the experimental features that were in Beta have
recently moved to Nightly, which is annoying, cause now we have to
deal with Nightly churn.

**Comment by the-kenny** [comment]
Note that I opened an issue to discuss inlcuding `rustc{Beta,Unstable}` in hydra: https://github.com/NixOS/nixpkgs/issues/18111

**Comment by edolstra** [comment]
Note that Nixpkgs generally should not include beta/prerelease versions of packages anyway. But if they are included, they should be marked `lowPrio`.

**Comment by sjmackenzie** [comment]
Okay fair, as said earlier, I'll update the PR retaining the `lowPrio`.

**Pull request closed without merging**
