### PR TITLE
displaylink: 5.8.0-63.33 -> 6.0.0-24

### PR DESCRIPTION
**Pull request by GeoffreyFrogeye**
## Description of changes

Changelog from the archive:

#### C.9  Changes in 6.0 release

- DL-7xxx: Support for DP++ (HDMI) video
- DL-7xxx: Added Unigraf UCD-400/500 for DisplayPort compliance testing
- DL-6xxx series: incorrect image at 2560x1440@60 on some DisplayPort monitors
- Added preliminary support for kernel 6.9
- General stability updates and bug fixes

#### C.8  Changes in 5.9 release

- Drop support for Ubuntu 18.04

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Confirmed working with a `17e9:4318 DisplayLink Dell USB 3.0 Dock`.

This is a major release in the semver sense of the term, but I'm not sure whether it is worth adding an entry in the release notes.

I am not super familiar with the package, so I haven't looked deeply whether more needs updating, but I figured this would be a starting point.

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GeoffreyFrogeye** [comment]
If I'm not mistaken ofborg should have requested a review from the package maintainers, maybe it didn't do so because I force-pushed while it was still running? So, uh, ping @abbradar

**Review by toastal — APPROVED** [review]
This builds & runs for me, but we should be wary that `evdi` current isn’t compatible with `linux_testing` @ v6.10.0-rc* https://github.com/DisplayLink/evdi/issues/469

**Review by astratagem — APPROVED** [review]
This also builds and runs for me on `aarch64-linux`.  Thank you!

FWIW: after updating NixOS sometime in the past couple weeks, I encountered a severe (unusable) lag on my external monitor, which I can only use via a DisplayLink hub.  I am running GNOME Desktop via `nixos-unstable` on a MacBook Air M2 (https://github.com/tpwrules/nixos-apple-silicon/).  Unfortunately for me, updating to DisplayLink 6.0.0-24 did not resolve the issue, so it's probably related to my configuration.

**Comment by montchr** [comment]
> This builds & runs for me, but we should be wary that `evdi` current isn’t compatible with `linux_testing` @ v6.10.0-rc\* [https://github.com/DisplayLink/evdi/issues/469](https://github.com/DisplayLink/evdi/issues/469)

Looks like they released a fix in v1.14.5, though they did not actually close the issue.

https://github.com/DisplayLink/evdi/issues/469#issuecomment-2194215169

**Comment by karlskewes** [comment]
FWIW a separate PR https://github.com/NixOS/nixpkgs/pull/324121 updating to 6.0 has been merged.

**Pull request closed without merging**
