### PR TITLE
samtools: 1.13 -> 1.17

### PR DESCRIPTION
**Pull request by bzizou**
###### Description of changes

Our biologists need this upgrade. 
htslib, which is a library part of samtools, must also be upgraded to 1.17 for samtools 1.17 to be compiled 

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 225865` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>platypus</li>
  </ul>
</details>
<details>
  <summary>10 packages failed to build:</summary>
  <ul>
    <li>python310Packages.cnvkit</li>
    <li>python310Packages.cnvkit.dist</li>
    <li>python311Packages.cnvkit</li>
    <li>python311Packages.cnvkit.dist</li>
    <li>python311Packages.htseq</li>
    <li>python311Packages.htseq.dist</li>
    <li>python311Packages.pysam</li>
    <li>python311Packages.pysam.dist</li>
    <li>truvari</li>
    <li>truvari.dist</li>
  </ul>
</details>
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>angsd</li>
    <li>bcftools</li>
    <li>deeptools</li>
    <li>deeptools.dist</li>
    <li>delly</li>
    <li>htslib</li>
    <li>mosdepth</li>
    <li>nimPackages.hts-nim</li>
    <li>octopus-caller</li>
    <li>python310Packages.htseq</li>
    <li>python310Packages.htseq.dist</li>
    <li>python310Packages.pysam</li>
    <li>python310Packages.pysam.dist</li>
    <li>samtools</li>
    <li>tebreak</li>
    <li>tebreak.dist</li>
  </ul>
</details>

**Comment by mimame** [comment]
Hi @bzizou and @natsukium 
There is already one pull request for htslib 1.17 that has to be merged first
https://github.com/NixOS/nixpkgs/pull/219663

**Comment by natsukium** [comment]
The derivation of `truvari` is too old and already broken.
The failure of `python311Packages.pysam` and `python311Packages.htseq` is fixed in #222906.
The `python3Packages.cnvkit` that depends on `python3Packages.pomegranate` already failed in the test regardless of this change.

I think this PR change is good.

**Review by natsukium — APPROVED** [review]

**Review by risicle — APPROVED** [review]
`nixpkgs-review` reveals no new failures, macos 10.15 & nixos x86_64

**Comment by bzizou** [comment]
Thank you!

**Pull request merged**
