### PR TITLE
python3Packages.jsonschema: 4.19.0 -> 4.20.0, python3Packages.regress: init at 0.4.2, check-jsonschema: 0.25.0 -> 0.27.1

### PR DESCRIPTION
**Pull request by matthiasbeyer**
## Description of changes

This was done on work-time :laughing: because we need these updated for our CI. So this was sponsored. :laughing: 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by nikstur** [comment]
I'm surprised by the number of rebuilds. @mweinelt should this target staging?

**Comment by l0b0** [comment]
I'm running into a crash on nixos-unstable (check-jsonschema 0.25.0):

```
❯ check-jsonschema --builtin-schema=vendor.github-workflows .github/workflows/*.yml
Error: Unexpected Error building schema validator
TypeError: create.<locals>.Validator.__init__() got an unexpected keyword argument 'registry'
  in "/nix/store/asxk29a77cf1d7kf3pi2arsci81kfi9v-check-jsonschema-0.25.0/lib/python3.11/site-packages/check_jsonschema/checker.py", line 53
  >>> return self._schema_loader.get_validator(
```

I'm going to see if that's fixed by upgrading to 0.27.1. If so, I'll bump regress and check-jsonschema to their latest versions, rebase onto `staging`, and create a new PR.

**Comment by l0b0** [comment]
Can we close this since #273831 was merged?

**Comment by matthiasbeyer** [comment]
> I hope you don't mind I added myself as co-author on your commits

of course not, go ahead! :heart:

**Pull request closed without merging**
