### PR TITLE
Update packages maintained by Artturin

### PR DESCRIPTION
**Pull request by Artturin**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Infinidoge** [comment]
Is there a particular reason why [nwg-wrapper](https://github.com/NixOS/nixpkgs/pull/197602/commits/ae54952c4e2d8e3cdebd2947bc07afb9ace4fee6) is bumped in this PR?

**Comment by Artturin** [comment]
> Is there a particular reason why [nwg-wrapper](https://github.com/NixOS/nixpkgs/pull/197602/commits/ae54952c4e2d8e3cdebd2947bc07afb9ace4fee6) is bumped in this PR?

i was updating my maintained packages (checked with [repology](https://repology.org/projects/?search=&maintainer=artturin%40artturin.com&category=&inrepo=nix_unstable&notinrepo=&repos=&families=&repos_newest=&families_newest=))
and just happened to fix the update script

**Comment by Infinidoge** [comment]
Ah, fair enough.
Seemed odd to have them in a PR with a title referring specifically to Discord.

**Review by Infinidoge — APPROVED** [review]
Tested `discord-ptb` and it works properly.
The update script change also looks good.

Can't test `nwg-wrapper` properly since I am not running Wayland, but both it and `flashfocus`' binaries seem to be working properly, producing help text and their expected output given my setup.

**Review by Infinidoge — APPROVED** [review]
A sacrificial review for our ofborg overlord.

See review above, also poked at the varlink CLI which seems to be in working order.
All looks good to me.

**Pull request merged**
