### PR TITLE
glib: Add support for GNOME Console

### PR DESCRIPTION
**Pull request by jtojnar**
###### Description of changes

GNOME Console (aka King’s Cross) is the default terminal emulator in GNOME 42. Let’s make GLib aware of it so that apps relying on it (e.g. GNOME Shell) can launch terminal apps like htop.

This is a downstream patch since GLib does not want to add any more terminal emulators: https://gitlab.gnome.org/GNOME/glib/-/issues/2618

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
While at it, should we also add Pantheon Terminal @bobby285271?

**Comment by bobby285271** [comment]
> While at it, should we also add Pantheon Terminal

Personally, this sounds good to me. I think `-x` should be used when calling `io.elementary.terminal`.

---

I actually have a very wired question for gnome-console, if I have a `~/.local/share/applications/test.desktop` file as:

```
[Desktop Entry]
Type=Application
Version=1.0
Name=Test
GenericName=Test
Comment=Test
Icon=htop
Exec=/home/bobby285271/test.sh --help
Terminal=true
Categories=System;ConsoleOnly;
Keywords=system
```

And a `/home/bobby285271/test.sh` file as:

```bash
#!/usr/bin/env bash
echo "hello"
if [[ "${1}" == "--help" ]]
then
  echo "world"
fi
sleep 10
```

Can `kgx -e` handle that correctly? I expect a terminal window pop up and say hello world.

**Comment by jtojnar** [comment]
Not sure, still have not rebuilt my system with this patch. I can only say that GNOME Terminal does print both lines when the script is started through the desktop file in GNOME Shell.

----

`kgx -e "$PWD/test.sh --randomarg"` and `xterm -e "$PWD/test.sh --randomarg"` need to be invoked like this, while `gnome-terminal -- $PWD/test.sh --randomarg`. `io.elementary.terminal` seems to support both formats (`-x` is synonym to `--`). `kgx` and `io.elementary.terminal` do not seem to close the tab after the command finishes, xterm and gnome-terminal do.

**Comment by jtojnar** [comment]
Actually, testing using the following shows that the patch is not sufficient as is:

```
$ env PATH=$(nix-build -A gnome-console)/bin $(nix-build https://github.com/jtojnar/nixpkgs/archive/glib-gnome-console.tar.gz -A glib.bin)/bin/gio launch ~/.local/share/applications/test.desktop
Unknown option --randomarg
```

**Comment by bobby285271** [comment]
> Not sure, still have not rebuilt my system with this patch.

I am actually testing the change using the "workaround" mentioned in the [upstream issue](https://gitlab.gnome.org/GNOME/glib/-/issues/2618), that is enable `environment.localBinInPath`, run `ln -s /path/to/bin/kgx tilix` in `~/.local/bin`, create the above files, then `gtk-launch test.desktop` :rofl: And yeah I am also seeing `Unknown option --randomarg`.

**Comment by jtojnar** [comment]
Weirdly, having only `xterm` on `PATH` does not even seem to do anything. Not even when I remove the extra argument from the desktop file.

**Comment by jtojnar** [comment]
Interestingly, Tilix supports both `tilix -e test.sh --randomarg` and `tilix -e "test.sh --randomarg"` (I added `test.sh` on `PATH`).

**Comment by jtojnar** [comment]
The window closing immediately might have something to do with the `PATH`, it does the same when running `env PATH=(nix-build -A xfce.xfce4-terminal)/bin result/bin/xfce4-terminal -x ~/.local/bin/test.sh --randomarg` but not when passing it non-existent program, or running it without `PATH` modification `result/bin/xfce4-terminal -x ~/.local/bin/test.sh --randomarg`.

**Comment by jtojnar** [comment]
Testing with the following fish script and your [desktop file](https://github.com/NixOS/nixpkgs/pull/165975#issuecomment-1080124826), it seems all tested emulators support argument per argument, only KGX needs the whole command as a single argument.

```fish
for termpkg in gnome.gnome-terminal mate.mate-terminal xfce.xfce4-terminal gnome-console tilix libsForQt5.konsole xterm
echo Testing $termpkg
env PATH=(nix-build -A bash)/bin:(nix-build -A coreutils)/bin:(nix-build -A $termpkg)/bin (nix-build https://github.com/jtojnar/nixpkgs/archive/glib-gnome-console.tar.gz -A glib.bin)/bin/gio launch ~/.local/share/applications/test.desktop
read foo --prompt-str="Enter to continue"
end
```

**Comment by jtojnar** [comment]
Okay, this seems to work.

**Comment by jtojnar** [comment]
This can go to staging, since xterm is always available as a fallback.

**Pull request merged**
