### PR TITLE
apparmor: 2.13.3 -> 2.13.4

### PR DESCRIPTION
**Pull request by ajs124**
New upstream patch release. Addresses two issues, that we were patching, so now we can drop those patches.

[Release notes](https://gitlab.com/apparmor/apparmor/-/wikis/Release_Notes_2.13.4).

### CODE REVIEW

**Comment by alyssais** [comment]
> Addresses two issues, that we were patching, so now we can drop those patches.

I only see one dropped patch?

**Comment by ajs124** [comment]
One patch we carried in tree (which I forgot to delete, oops) and another one we fetched from upstream.

**Comment by alyssais** [comment]
Oh yes my mistake :)

**Comment by alyssais** [comment]
@GrahamcOfBorg build apparmor-parser systemd

**Pull request merged**
