### PR TITLE
chromedriver: 85.0.4183.87 -> 86.0.4240.22

### PR DESCRIPTION
**Pull request by nbr**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by marsam** [comment]
Would you mind changing the [commit message to](https://github.com/NixOS/nixpkgs/blob/b8e8c7d5b95b836c3b8dcbf098b1fd3008caa810/.github/CONTRIBUTING.md#submitting-changes): `chromedriver: 85.0.4183.87 -> 86.0.4240.22`?. Besides that, LGTM

**Comment by nbr** [comment]
> Would you mind changing the [commit message to](https://github.com/NixOS/nixpkgs/blob/b8e8c7d5b95b836c3b8dcbf098b1fd3008caa810/.github/CONTRIBUTING.md#submitting-changes): `chromedriver: 85.0.4183.87 -> 86.0.4240.22`?. Besides that, LGTM

@marsam Done, thanks.

**Comment by alexanderkranga** [comment]
Hi, can someone please let me know when this change is going to be merged? Currently, chromedriver of version 85 is incompatible with Google Chrome 87 and it causes incompatibility issues.

**Review by polynomial — APPROVED** [review]

**Comment by marsam** [comment]
Thank you! sorry for the delay

**Pull request merged**
