### PR TITLE
jmol init, pymol -> 2.1.0 and tidied up all-packages.nix

### PR DESCRIPTION
**Pull request by Mounium**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by matthewbauer — CHANGES_REQUESTED** [review]
Resolve merge conflicts.

**Comment by Mounium** [comment]
@matthewbauer 
```
bin/jmol: line 20: /bin/ls: No such file or directory
bin/jmol: line 21: /usr/bin/expr: No such file or directory
bin/jmol: line 22: /usr/bin/expr: No such file or directory
bin/jmol: line 25: /usr/bin/dirname: No such file or directory
```
I got this error while executing the jmol symlink, solved by using patched original initiation script.

I also rebased branch, so there won't be two jmol lines in all-packages.nix

**Comment by matthewbauer** [comment]
@GrahamcOfBorg build jmol pymol

**Comment by Mounium** [comment]
@matthewbauer Could you please merge it if you think it is useful, because I'm afraid the change to all-packages.nix will sooner or later will conflict with the base branch. 

Also, I don't know should anything be done about darwin or is it ok to let it fail?

**Pull request merged**
