### PR TITLE
masterpdfeditor: use autoPatchelfHook

### PR DESCRIPTION
**Pull request by Mic92**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
cc @flokli

**Comment by flokli** [comment]
Works here as well, great :-)

While you're at it, could you strip the `-v` from the `cp` command?

**Comment by CMCDragonkai** [comment]
Where are the docs for `autoPatchelfHook`?

**Comment by Mic92** [comment]
documentation: https://github.com/NixOS/nixpkgs/blob/c958516cb3e8b68433097c15f49eedcac781b93d/doc/stdenv.xml#L2409. @aszlig added it here: https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/setup-hooks/auto-patchelf.sh

It has a growing userbase in nixpkgs:
https://github.com/NixOS/nixpkgs/search?q=autoPatchelfHook&unscoped_q=autoPatchelfHook

**Pull request merged**
