### PR TITLE
nixos/privacyidea: use `sudo(8)` that's configured via the module

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

I have a `sudo` built with `--enable-static-sudoers` to keep `sudo` working in a user-namespaced `nspawn` container. With privacyidea using the "default" sudo, it didn't start properly, so I figured it makes sense to use the system's "actual" sudo.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aanderse** [comment]
tree wide?

**Comment by Ma27** [comment]
@aanderse WDYM? :)

**Comment by aanderse** [comment]
We reference `pkgs.sudo` in a number of modules. I think this change makes sense to apply tree wide, to all modules referencing `sudo`.

**Comment by Ma27** [comment]
Fair, but I don't have the capacity to go through all affected modules and check them, so I guess it's fine to merge it now as it still contains a valid fix.

**Comment by aanderse** [comment]
Can't blame a guy got trying! 😄 Thanks for this fix, though. It serves as a good example which someone else can pickup at some point.

**Pull request merged**
