### PR TITLE
amdgpu-pro-libs: init at 5.4.5

### LINKED ISSUE #204502: AMD AMF(AMD Media Framework)
**Project description**
encoders for amd gpu's. 

**Metadata**

* homepage URL: https://www.amd.com/en/support/kb/release-notes/rn-pro-lin-22-q4
* source URL: https://github.com/GPUOpen-LibrariesAndSDKs/AMF
* license: MIT, proprietary
* platforms: linux

### PR DESCRIPTION
**Pull request by materusPL**
###### Description of changes

Init packages with amdgpu-pro userspace drivers (opengl, vulkan, amf) and prefixes like in nobara or arch (gl_pro, vk_pro etc.)
Current amdgpu-pro package in nixpkgs is kernel module and seems outdated. This adds only userspace
Would close https://github.com/NixOS/nixpkgs/issues/204502

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by PedroHLC** [comment]
Is there an open issue for why can't we update the kernel module? Could we add the AMF stuff as an output, as we already do with the vulkan output?

**Comment by materusPL** [comment]
@PedroHLC I can't find any issue. It would be possible to add as output but current amdgpu-pro prackage require some work due to how amd distributes newer packages.

**Comment by PedroHLC** [comment]
Looking at this, it seems something interesting to have in repos.

My question seems to have scared the reviews, sorry.

**Comment by icodeforyou-dot-net** [comment]
Okay, I'm gonna ping you this time dear @materusPL :smile: 

What happened to this PR?

**Comment by materusPL** [comment]
As @PedroHLC said current `amdgpu-pro` seems to provide most of those libs from this PR but is a bit outdated. 
So looking at it, current amdgpu-pro should be updated  instead adding new libs but I'm not really willing to maintain/update dkms module with all related driver settings.

I have libs from this PR in my nur [repo](https://github.com/materusPL/Nixerus/tree/master/pkgs/libs/amdgpu-pro-libs)

**Comment by icodeforyou-dot-net** [comment]
Thanks for the reply @materusPL !

I somewhat disagree with your take though. For these reasons.

1) I failed getting the current `amdgpu-pro` to work from nixpkgs for now. No real idea why, didn't have time to debug it. But this gives me a sense that you might not wanna mess with it, if you don't really really badly have to.

2) Given that you might not wanna use `amdgpu-pro` if you can avoid it, you might still want to use AMF for something like gaming with OBS streaming. Not my main thing, but some people might. 

3) In Arch Linux you can get these fairly easily via the AUR which everybody uses anyways. I think I'd just prefer having them in `nixpkgs`, it makes things a lot easier for the end user, including me of course. Normally I don't even look for NUR repos on NixOS. And I have a feeling I am not the only one. 

So yeah, bottom line: These are the reasons. I'd really love to see these in nixpkgs. I thought your PR was a great step forward in this respect.

**Comment by PedroHLC** [comment]
Yeah, the point in (2) it's really worth to achieve.

**Pull request closed without merging**
