### PR TITLE
qt5.wrapQtAppsHook: wrap more than just ELF's

### PR DESCRIPTION
**Pull request by FRidh**
###### Motivation for this change
We should also be able to wrap Python scripts. Note that this also means
we can create nested wrappers. While unfortunate, until we have a way to
compose wrappers it's the only way.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by worldofpeace** [comment]
https://github.com/NixOS/nixpkgs/commit/7d6ab0ad7a5a5b1765a6d70b5df861d14e3c3482 didn't actually break this, It probably didn't work even before this since it used to be conditioned on `isQtApp`.

Initially I removed this like you've done here, but I had to restored a similar behavior because of issues I noticed in the plasma5 session
https://github.com/NixOS/nixpkgs/pull/64720#issuecomment-512083023.

Possibly something there shouldn't be wrapped, but since it's added unconditionally when using `qt5.mkDerivation` it may be difficult to figure out what.
And even then, It may be a good idea for these scripts to at least wrap `XDG_DATA_DIRS`.

**Comment by ttuegel** [comment]
> Possibly something there shouldn't be wrapped, but since it's added unconditionally when using `qt5.mkDerivation` it may be difficult to figure out what.

It's not added unconditionally; set `dontWrapQtApps = true;`.

**Comment by worldofpeace** [comment]
So I guess the step forward would be to identify in plasma5 what packages provide scripts that shouldn't be wrapped and to set that.

**Comment by ttuegel** [comment]
I expect that most scripts don't need to be wrapped, and I would prefer to use `isELF` + semi-manually wrap (using `wrapQtApp`) the minority of scripts that need to be wrapped.

**Review by Mic92 — APPROVED** [review]

**Comment by FRidh** [comment]
Pushed 92cb811455e9fecf9900eb9612592b4951d6a270 and 1190f69d3490b9b6b420d4109fcfb8cd59b9e770 using `wrapQtApp` directly instead.

**Pull request closed without merging**
