### PR TITLE
nixos/wireless: fix quotes in config path

### PR DESCRIPTION
**Pull request by buckley310**
## Description of changes
The string `finalConfig` already contains quotes, but has more quotes added to it in some of the places it is used.
Being quoted twice may cause problems if `$RUNTIME_DIRECTORY` ever contains spaces.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by buckley310** [comment]
I have not yet run a system with this config, however I have built a system with and without this fix.
```
$ diff /nix/store/ihyvds8kpz8bd7skkyrhcichharw35pw-unit-script-wpa_supplicant-wlan0-start/bin/wpa_supplicant-wlan0-start /nix/store/6al05s7rfx8nz77ydrfz37kk7mpa3av9-unit-script-wpa_supplicant-wlan0-start/bin/wpa_supplicant-wlan0-start
18c18
<   }' "/etc/wpa_supplicant.conf" > ""$RUNTIME_DIRECTORY"/wpa_supplicant.conf"
---
>   }' "/etc/wpa_supplicant.conf" > "$RUNTIME_DIRECTORY"/wpa_supplicant.conf
20c20
<   touch ""$RUNTIME_DIRECTORY"/wpa_supplicant.conf"
---
>   touch "$RUNTIME_DIRECTORY"/wpa_supplicant.conf
```

**Review by Aleksanaa — COMMENTED** [review]
What about the other references of `finalConfig`? Can we just edit `finalConfig` itself?

**Comment by buckley310** [comment]
Yeah, I could remove the quotes from the string stored in finalConfig, and add quotes around all uses of it. That's probably how i would have done it, personally, I just figured someone wanted the quotes in there.

**Comment by buckley310** [comment]
(I somehow accidentally closed this while commenting. Reopening.)

**Review by Aleksanaa — APPROVED** [review]

**Review by Aleksanaa — COMMENTED** [review]
Wait, I'm not sure, is `finalConfig` in line 97~98 also incorrect?

**Comment by rnhmjoj** [comment]
@GrahamcOfBorg test wpa_supplicant

**Comment by rnhmjoj** [comment]
> Wait, I'm not sure, is finalConfig in line 97~98 also incorrect?

Looks ok to me: it's not being quoted again.

**Review by rnhmjoj — APPROVED** [review]

**Pull request merged**
