### PR TITLE
optifine: 1.16.5_HD_U_G8 -> 1.18.1_HD_U_H4

### PR DESCRIPTION
**Pull request by PeterHindes**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

This time im targeting main branch.

### CODE REVIEW

**Comment by collares** [comment]
Sorry for being pedantic, but: To help with review, the commit message/PR title should be something like `optifine: 1.16.5_HD_U_G8 -> 1.18.1_HD_U_H4`, as described in `CONTRIBUTING.md`. Thanks for your contribution!

**Comment by PeterHindes** [comment]
My bad its my first comit and I was being lazy thanks for the heads up

**Comment by PeterHindes** [comment]
is there a way to automate this so that a pr is created every time a new version is released? All we need to is generate the hash and update the file name. Then someone can check it and merge it :)

**Comment by collares** [comment]
That's a good idea. There is a bot that does this (@r-ryantm) and it's very useful in general, but I would guess it doesn't handle non-free software such as `optifine`.

**Comment by legendofmiracles** [comment]
Another possibility is this: https://github.com/samuela/nixpkgs-upkeep

**Comment by bobby285271** [comment]
I guess the r-ryantm bot can handle non-free package updates (for example [vscode](https://github.com/NixOS/nixpkgs/pull/151161)), but you will need to add an updateScript for this package as https://repology.org/project/optifine/versions shows that only nixpkgs has this package so the bot cannot automatically figure out the latest version based on it.

**Comment by PeterHindes** [comment]
isnt vscode opensource though?

**Comment by bobby285271** [comment]
Visual Studio Code is released under a traditional [Microsoft product license](https://code.visualstudio.com/License/).

https://github.com/NixOS/nixpkgs/blob/959104e58cd30224a02bdd2ef3e8fbac7ac79b72/pkgs/applications/editors/vscode/vscode.nix#L59

See https://github.com/NixOS/nixpkgs/pull/86122 for Code - OSS.

**Comment by ryantm** [comment]
R-ryantm doesn't care about the license of things it updates.

**Comment by bobby285271** [comment]
@IvarWithoutBones Would you like to review the update as you are the maintainer of this package?

(Yeah this needs a squash merge)

**Review by IvarWithoutBones — APPROVED** [review]
Other than the commit name this LGTM :+1: 

Since people still want to play on older versions of the game, and this isn't backwards compatible, we should expose all the major versions in the future. This works for now though.

**Comment by PeterHindes** [comment]
How do you do multiple versions? I'm new to nixpkgs.

**Comment by IvarWithoutBones** [comment]
> How do you do multiple versions? I'm new to nixpkgs.

You can use a generic builder, much like [discord](https://github.com/NixOS/nixpkgs/blob/8ac7f8d217b564953ae081c6343422ca048abacb/pkgs/applications/networking/instant-messengers/discord/default.nix), or [yuzu](https://github.com/NixOS/nixpkgs/blob/8ac7f8d217b564953ae081c6343422ca048abacb/pkgs/misc/emulators/yuzu/default.nix). See their entries in `pkgs/top-level/all-packages.nix`, they're called differently from other packages. 

I think this would deserve it's own `optifinePackages` set containting all its versions, as to not pollute `pkgs`. (See `lib.attrsets.recurseIntoAttrs` from [the nixpkgs manual](https://nixos.org/manual/nixpkgs/stable/#sec-functions-library-attrset)). The existing `optifine` attribute could just point to the latest version.

**Pull request merged**
