### PR TITLE
Tree-wide link fix on patchelf's documentation

### PR DESCRIPTION
**Pull request by ppom0**
Tree-wide link fix on patchelf's documentation
README became README.md

### CODE REVIEW

**Comment by prusnak** [comment]
I think it would be better to use just this link: https://github.com/NixOS/patchelf

The contents of README.md are shown below anyway.

**Review by prusnak — CHANGES_REQUESTED** [review]
Please squash the commits into a single one and use the following commit message: `patchelf: fix homepage`

**Comment by aopom** [comment]
Ok, I think I successfully passed the git test :)

**Comment by rnhmjoj** [comment]
Thank you!

**Pull request merged**
