### PR TITLE
rust-bindgen: use a better drv name for fakeRustup

### PR DESCRIPTION
**Pull request by alyssais**
###### Motivation for this change

I saw a derivation called "rustup" building and was concerned why
rust-bindgen would depend on rustup.  If it had been called
"fake-rustup", I wouldn't have had to check the package source to see
what was going on. :)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ralith** [comment]
Won't that change the name of the binary and defeat the point?

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 132545` at d1b639a9 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/d7f6134d8d47ded1c46809aada2d6381">rust-bindgen</a></li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`configurePhase` should probably contain `runHook preConfigure` and `runHook postConfigure`.

Near pkgs/build-support/rust/default.nix:141:3:
```
    |
141 |   configurePhase = args.configurePhase or ''
    |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/duplicate-check-inputs.md">duplicate-check-inputs</a>

Dependencies listed in `propagatedBuildInputs` should not be repeated in `checkInputs`.

Detected duplicates:

- clang-wrapper-7.1.0

Near pkgs/development/tools/rust/bindgen/default.nix:40:3:
```
   |
40 |   checkInputs =
   |   ^
```

Near pkgs/development/tools/rust/bindgen/default.nix:27:3:
```
   |
27 |   propagatedBuildInputs = [ clang ]; # to populate NIX_CXXSTDLIB_COMPILE
   |   ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by alyssais** [comment]
Benjamin Saunders ***@***.***> writes:

> Won't that change the name of the binary and defeat the point?

Sorry, you're absolutely right.  I forgot how writeScriptBin works.

I've pushed a new version that sets the drv name to fake-rustup, while
keeping the executable name as rustup.  Please take another look.

**Comment by alyssais** [comment]
@Ralith would you mind taking another look at this please?

**Review by Ralith — APPROVED** [review]
Seems fine, though I haven't tested it myself.

**Pull request merged**
