### PR TITLE
nixos manual: segment into pages

### PR DESCRIPTION
**Pull request by Mic92**
At the moment we have one unnavigable large page.
This pull request puts each chapter into a separate file.
The idea solution would be to have a navigation side-bar were only
first-level chapters are shown (or even a page search like sphinx).
However docbook seems to be too inflexible to do that.

Is there a way to get nicer looking templates like the guix manual has?
https://www.gnu.org/software/guix/manual/guix.html

**Update** the template used on the website would be already enough.

---

### CODE REVIEW

**Comment by makefu** [comment]
Splitting into separate pages will also help the google indexation as large pages get ranked down

**Comment by FRidh** [comment]
There was a discussion about this earlier when the switch was made to a single page https://github.com/NixOS/nixpkgs/issues/7607.

**Comment by 0xABAB** [comment]
Most projects offer single page and multi page for good reason as well as multiple formats (PDF/HTML)

**Comment by dezgeg** [comment]
I'd definitely prefer both single-page and multi-page versions being available (as was mentioned above), as an arbitrary example: https://www.gnu.org/software/bison/manual/

**Comment by Mic92** [comment]
Having two version would increase the build time twice. I would like avoid that, because I have to build the manual, whenever service options are changed.

**Pull request closed without merging**
