### PR TITLE
nixos/modules/services/backup/borgbackup.nix: Add retry on fail

### PR DESCRIPTION
**Pull request by StillerHarpo**
###### Motivation for this change

This service always fails for me.  I think this is because network isn't up when it gets executed.

I added an option to make it retry the service.  

Another fix would be depending on `network-online.target`.  But this can impact boot time (https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/)

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aanderse** [comment]
Does this software always fail for other people too? These options don't do anything, just add discoverability. I would be inclined to suggest just modifying the `systemd` service in your own configuration unless there is evidence to suggest many people a) have this problem, and b) don't know if the `systemd` options.

**Comment by pennae** [comment]
doesn't fail here, but there is another PR about this exact thing: #99196

**Comment by StillerHarpo** [comment]
Sorry I should have used the searched fist.

**Comment by pennae** [comment]
wasn't meaning to imply that, just that there's at least one other person with that problem. :)

**Comment by aanderse** [comment]
@toonn sounds good :+1: I didn't mean to this is invalid - it was a legitimate question because I'm not familiar with the software. I think it is good to ask questions like this and if the answer is "yes, this is valid" then I'm happy.

**Comment by toonn** [comment]
Np, I was just giving my rationale for why my changes are warranted. I'm hoping this'll cause some movement on that PR of mine or an alternative, I've been overlaying with my patch for over a year now and I think it'd be useful to others.

**Pull request closed without merging**
