### PR TITLE
nixos: fix fallout from #46193

### PR DESCRIPTION
**Pull request by oxij**
###### Motivation for this change

Fixes an issue reported in https://github.com/NixOS/nixpkgs/pull/46193#issuecomment-424106727.

Enabling `minimal` and `installation-device` profiles at the same time (like `netboot` profile does) started failing after #46193.

###### Things done

- [X] Installers in `./nixos/release.nix` evaluate.

### CODE REVIEW

**Review by samueldr — APPROVED** [review]
```
~/tmp/nixpkgs/nixpkgs $ git checkout master

~/tmp/nixpkgs/nixpkgs $ nix-build nixos/release.nix -A netboot
error: attribute 'manual' missing, at /Users/samuel/tmp/nixpkgs/nixpkgs/nixos/modules/services/misc/nixos-manual.nix:57:39

~/tmp/nixpkgs/nixpkgs-PR47298 $ git show | head -n1
commit 1a6ce11518af319e6029863a7f220c071ce5b467

~/tmp/nixpkgs/nixpkgs-PR47298 $ nix-build nixos/release.nix -A netboot
these derivations will be built:
[...]
```

:+1:  sorry for not catching that in the initial merge.

**Comment by oxij** [comment]
Nah, if we are to blame someone then that clearly is my fault.

I would've liked OfBorg to catch it, though.

**Comment by 7c6f434c** [comment]
Hm, it looks like just using `nix-instantiate` on `nixos/release.nixos` only instantiates derivations, but not auto-callable functions. Then again, there are tests in a non-trivial Nix data structure. Is there something like eval-release.nix in Nixpkgs for checking that things evaluate?

**Comment by oxij** [comment]
That needs to be investigated. But the question of how to prevent this in the future and a fix to broken master are separate issues IMHO.

Can we merge this and then discuss what OfBorg should evaluate to prevent future issues like this?

**Comment by 7c6f434c** [comment]
Yes, a separate question and the change looks OK.

**Comment by oxij** [comment]
Thanks! Added investigation to the TODO list.

**Pull request merged**
