### PR TITLE
python310Packages.dash: 2.10.2 -> 2.13.0

### PR DESCRIPTION
**Pull request by TomaSajt**
###### Description of changes

This PR bumps the `dash` python package version.

One of the bigger changes in this version is the merging of the `JupyterDash` module into the main repo. Sadly, the jupyter extension was not pushed to the repo already build (the Pypi source does have it though, but I tried to stay with the GitHub source)

To build the Jupyter extension I had to use yarn and prefetch the deps.

I grouped the used python packages by usage area and ordered them by how they appear in the requirements.txt list.

I put `flask-compress` into `optional-dependencies.compress` which fixed the broken test.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TomaSajt** [comment]
Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>das</li>
    <li>das.dist</li>
    <li>picosnitch</li>
    <li>picosnitch.dist</li>
    <li>python310Packages.dash</li>
    <li>python310Packages.dash.dist</li>
    <li>python311Packages.dash</li>
    <li>python311Packages.dash.dist</li>
  </ul>
</details>

**Comment by wegank** [comment]
Already on master.

**Comment by elesiuta** [comment]
This PR should be reopened and updated because it also contains changes other than the version bump. As it is now (with the version bump, minus the other changes here, on nixos-23.11pre544052.85f1ba3e5167-x86_64-linux.ova), `das`, `picosnitch`, and `python311Packages.dash` all fail to build with

```
error: builder for '/nix/store/fkdmjl37p60nkgil8xl27kiw6nj61h8x-python3.11-dash-2.13.0.drv' failed with exit code 1;
       last 10 log lines:
       > copying dash/nbextension/main.js -> build/bdist.linux-x86_64/wheel/dash-2.13.0.data/data/share/jupyter/nbextensions/dash
       > creating build/bdist.linux-x86_64/wheel/dash-2.13.0.data/data/etc
       > creating build/bdist.linux-x86_64/wheel/dash-2.13.0.data/data/etc/jupyter
       > creating build/bdist.linux-x86_64/wheel/dash-2.13.0.data/data/etc/jupyter/nbconfig
       > creating build/bdist.linux-x86_64/wheel/dash-2.13.0.data/data/etc/jupyter/nbconfig/notebook.d
       > copying dash/nbextension/dash.json -> build/bdist.linux-x86_64/wheel/dash-2.13.0.data/data/etc/jupyter/nbconfig/notebook.d
       > creating build/bdist.linux-x86_64/wheel/dash-2.13.0.data/data/share/jupyter/lab
       > creating build/bdist.linux-x86_64/wheel/dash-2.13.0.data/data/share/jupyter/lab/extensions
       > error: can't copy 'dash/labextension/dist/dash-jupyterlab.tgz': doesn't exist or not a regular file
       > /nix/store/bbxdw4rgwwl3gnajri82yidr1nlsfskf-stdenv-linux/setup: line 1596: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix-store -l /nix/store/fkdmjl37p60nkgil8xl27kiw6nj61h8x-python3.11-dash-2.13.0.drv'.
error: 1 dependencies of derivation '/nix/store/n4gjaw5v4rcnqgv3nldpq2d7yklcyhrv-das-0.3.8.drv' failed to build
```

**Comment by wegank** [comment]
@elesiuta Would you like to open a PR containing the changes? This PR is likely to have merge conflicts if the previous update was done differently.

**Comment by TomaSajt** [comment]
I'll open another PR soon

**Pull request closed without merging**
