### PR TITLE
protonvpn-gui: 4.1.10 -> 4.3.0

### PR DESCRIPTION
**Pull request by WolfangAukang**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by raspher** [comment]
@WolfangAukang seems latest nixos-stable (23.11) cannot run `protonvpn-app` as it crashes with `ModuleNotFoundError: No module named 'bcrypt._bcrypt'`. 

I'm not a Python developer, but I've noticed that Python versions vary between packages: `protonvpn-gui` uses Python 3.11, while others are built using Python 3.12

Details: https://gist.github.com/raspher/11a684f4979269ed306595d563ef7096

**Comment by WolfangAukang** [comment]
@raspher `protonvpn-gui` relies on `buildPythonApplication` to get built. I am not sure how you can determine the Python version to run against. `bcrypt` is already added to `proton-core`, and the logs you sent are pointing to a `bcrypt` issue:
```
  File "/nix/store/3k05g5pp4gykk5lbx7i06i5nh5gfma4p-python3.12-proton-core-0.1.16/lib/python3.12/site-packages/proton/session/srp/_pysrp.py", line 34, in <module>
    from .util import (PM_VERSION, SRP_LEN_BYTES, SALT_LEN_BYTES, bytes_to_long, custom_hash,
  File "/nix/store/3k05g5pp4gykk5lbx7i06i5nh5gfma4p-python3.12-proton-core-0.1.16/lib/python3.12/site-packages/proton/session/srp/util.py", line 20, in <module>
    import bcrypt
-->  File "/nix/store/d7dgkybk90jm33gnrrcg62026800ms52-python3.12-bcrypt-4.1.2/lib/python3.12/site-packages/bcrypt/__init__.py", line 13, in <module>
    from ._bcrypt import (
ModuleNotFoundError: No module named 'bcrypt._bcrypt'
```

**Comment by Andreas02-dev** [comment]
Hi @WolfangAukang ,

Unfortunately I am currently unable to fully test as I am running 23.11 Tapir which doesn't seem to have the required NM version for the latest ProtonVPN versions:

`gi.repository.GLib.GError: nm-connection-error-quark: connection.autoconnect-ports: unknown property (7)`

[1.44.4 - The current version in 23.11 Tapir](https://networkmanager.dev/docs/api/1.44.4/settings-connection.html)
[1.46.0 - The latest stable version, can be found in NixOS Unstable](https://networkmanager.dev/docs/api/1.46/settings-connection.html)

I have taken a stab at upgrading to the newest 4.3.0 version by incorporating your changes and looking at the unofficial Flatpak build for ProtonVPN, and this version has the same issue.

My branch with the 4.3.0 version can be found here: https://github.com/Andreas02-dev/nixpkgs/tree/upgrade/protonvpn-gui_to_4-3-0

If you are able to run the 1.46.0 NetworkManager, could you maybe test if the 4.3.0 version works for you?

**Comment by JohnRTitor** [comment]
Note: there is already a [4.3 release](https://github.com/ProtonVPN/proton-vpn-gtk-app/releases/tag/v4.3.0), you might want to update this PR. Relevant issue: https://github.com/NixOS/nixpkgs/issues/304819

**Comment by Andreas02-dev** [comment]
> Note: there is already a [4.3 release](https://github.com/ProtonVPN/proton-vpn-gtk-app/releases/tag/v4.3.0), you might want to update this PR. Relevant issue: #304819

@WolfangAukang I'm sorry for the quick second ping, however I've had the opportunity to test both this PR and my 4.3.0 branch with NetworkManager 1.46.0 from NixOS Unstable. This PR errors with `AttributeError: 'ProtonVPNAPI' object has no attribute 'settings'`, however my 4.3.0 branch works correctly and allows me to connect to a VPN server.

Could you incorporate my changes to update the version to 4.3.0 so users with NetworkManager 1.46.0 from Unstable can use their VPN again, or is it better for me to open a PR from my [branch](https://github.com/Andreas02-dev/nixpkgs/tree/upgrade/protonvpn-gui_to_4-3-0)?

Looking forward to hearing from you and with kind regards,
Andreas

**Comment by WolfangAukang** [comment]
I have updated the PR to the newest version. But now I cannot get a connection:
```
2024-04-19T17:42:13.840848 | proton.vpn.app.gtk.widgets.main.exception_handler:164 | ERROR | APP:ERROR | Reconnection not possible due to authentication error.
Traceback (most recent call last):
  File "/nix/store/jii93xw34lkdvqgwpzj1yrhz9mxqxrp6-protonvpn-gui-4.3.0/lib/python3.11/site-packages/proton/vpn/app/gtk/services/reconnector/reconnector.py", line 148, in _on_reconnection_error
    raise AuthenticationError("Reconnection not possible due to authentication error.")
proton.vpn.connection.exceptions.AuthenticationError: Reconnection not possible due to authentication error.
```
I would assume this might be related to my account, but wanted to see if you are having the same issue

**Comment by Andreas02-dev** [comment]
> I have updated the PR to the newest version. But now I cannot get a connection:
> 
> ```
> 2024-04-19T17:42:13.840848 | proton.vpn.app.gtk.widgets.main.exception_handler:164 | ERROR | APP:ERROR | Reconnection not possible due to authentication error.
> Traceback (most recent call last):
>   File "/nix/store/jii93xw34lkdvqgwpzj1yrhz9mxqxrp6-protonvpn-gui-4.3.0/lib/python3.11/site-packages/proton/vpn/app/gtk/services/reconnector/reconnector.py", line 148, in _on_reconnection_error
>     raise AuthenticationError("Reconnection not possible due to authentication error.")
> proton.vpn.connection.exceptions.AuthenticationError: Reconnection not possible due to authentication error.
> ```
> 
> I would assume this might be related to my account, but wanted to see if you are having the same issue. This also happens to me with your branch @Andreas02-dev .

Just to be on the safe side, I've removed `~/.cache/Proton` and `~/.config/Proton` and removed all Proton entries from Gnome Keyring before testing the PR again, and everything works correctly for me, so it seems your account is having an issue.

At least we know that this build works now, so we should be able to merge this, right?

**Comment by WolfangAukang** [comment]
> At least we know that this build works now, so we should be able to merge this, right?

As long it is approved, then yes.

**Review by Andreas02-dev — APPROVED** [review]
Tested to work with NetworkManager 1.46.0, which will be included in Gnome 46.

**Review by JohnRTitor — APPROVED** [review]

**Comment by pbsds** [comment]
Result of `nixpkgs-review pr 302011` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>46 packages built:</summary>
  <ul>
    <li>protonvpn-gui</li>
    <li>protonvpn-gui.dist</li>
    <li>python311Packages.proton-core</li>
    <li>python311Packages.proton-core.dist</li>
    <li>python311Packages.proton-keyring-linux</li>
    <li>python311Packages.proton-keyring-linux-secretservice</li>
    <li>python311Packages.proton-keyring-linux-secretservice.dist</li>
    <li>python311Packages.proton-keyring-linux.dist</li>
    <li>python311Packages.proton-vpn-api-core</li>
    <li>python311Packages.proton-vpn-api-core.dist</li>
    <li>python311Packages.proton-vpn-connection</li>
    <li>python311Packages.proton-vpn-connection.dist</li>
    <li>python311Packages.proton-vpn-killswitch</li>
    <li>python311Packages.proton-vpn-killswitch-network-manager</li>
    <li>python311Packages.proton-vpn-killswitch-network-manager.dist</li>
    <li>python311Packages.proton-vpn-killswitch.dist</li>
    <li>python311Packages.proton-vpn-logger</li>
    <li>python311Packages.proton-vpn-logger.dist</li>
    <li>python311Packages.proton-vpn-network-manager</li>
    <li>python311Packages.proton-vpn-network-manager-openvpn</li>
    <li>python311Packages.proton-vpn-network-manager-openvpn.dist</li>
    <li>python311Packages.proton-vpn-network-manager.dist</li>
    <li>python311Packages.proton-vpn-session</li>
    <li>python311Packages.proton-vpn-session.dist</li>
    <li>python312Packages.proton-core</li>
    <li>python312Packages.proton-core.dist</li>
    <li>python312Packages.proton-keyring-linux</li>
    <li>python312Packages.proton-keyring-linux-secretservice</li>
    <li>python312Packages.proton-keyring-linux-secretservice.dist</li>
    <li>python312Packages.proton-keyring-linux.dist</li>
    <li>python312Packages.proton-vpn-api-core</li>
    <li>python312Packages.proton-vpn-api-core.dist</li>
    <li>python312Packages.proton-vpn-connection</li>
    <li>python312Packages.proton-vpn-connection.dist</li>
    <li>python312Packages.proton-vpn-killswitch</li>
    <li>python312Packages.proton-vpn-killswitch-network-manager</li>
    <li>python312Packages.proton-vpn-killswitch-network-manager.dist</li>
    <li>python312Packages.proton-vpn-killswitch.dist</li>
    <li>python312Packages.proton-vpn-logger</li>
    <li>python312Packages.proton-vpn-logger.dist</li>
    <li>python312Packages.proton-vpn-network-manager</li>
    <li>python312Packages.proton-vpn-network-manager-openvpn</li>
    <li>python312Packages.proton-vpn-network-manager-openvpn.dist</li>
    <li>python312Packages.proton-vpn-network-manager.dist</li>
    <li>python312Packages.proton-vpn-session</li>
    <li>python312Packages.proton-vpn-session.dist</li>
  </ul>
</details>

**Pull request merged**
