### PR TITLE
haskellPackages: add myself as maintainer for a few pkgs

### PR DESCRIPTION
**Pull request by sternenseemann**
Some packages I maintain already and additionally some packages I have
experience with, so I should be able to help fixing stuff related to
them.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by blitz — COMMENTED** [review]
Looks uncontroversial.

**Review by blitz — APPROVED** [review]

**Comment by iblech** [comment]
Thank you for offering to chip in :-)

**Comment by SuperSandro2000** [comment]
Please do not merge the target branch into the PR.

**Comment by cdepillabout** [comment]
Sorry, there was a merge conflict from https://github.com/NixOS/nixpkgs/pull/113320.  I tried to fix it up with the GitHub UI so that @sternenseemann wouldn't have to do it, but that appears to have caused the merge commit.

I then couldn't force push to @sternenseemann's branch to fix the situation.

I ended up just directly committing this PR to the `haskell-updates` branch:

- 935d5df1c10f7840 (this change)
- d34725d7f70bc9 (merge commit)

**Comment by cdepillabout** [comment]
@sternenseemann Please try to keep the packages in this PR building.

I didn't check all the packages here, but I did notice that `haskellPackages.yarn2nix` is currently marked broken.

**Comment by sternenseemann** [comment]
@cdepillabout I'll take a look, but yarn2nix is in a bit of an awkward state between releases, so broken is kind of an accurate description actually.

**Pull request closed without merging**
