### PR TITLE
Reverting the Chromium version bump as pepper fails to build for me :…

### PR DESCRIPTION
**Pull request by heydojo**
… ninja: build stopped: subcommand failed.

Chromium does not build for me with this new version. The build errors out when trying to build pepper.

### CODE REVIEW

**Comment by lethalman** [comment]
cc @wkennington

**Comment by edolstra** [comment]
It does build on Hydra: http://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.chromium.x86_64-linux

@heydojo Is the build failure repeatable for you?

**Comment by heydojo** [comment]
@edolstra the build failed twice here for me.
I have nixpkgs.config.chromium.enablePepperFlash = true; in configuration.nix and the default is false.
If hydra is using the default then it won't be building pepper and of course should not fail.
I will try again to build the new version but it takes quite a long time to build.

**Comment by heydojo** [comment]
Taken the build from hydra. No need for this request. I have learned that I need a staging tree if I want to push using github.

**Pull request closed without merging**
