### PR TITLE
[20.03] brave: 1.1.23 -> 1.3.118

### PR DESCRIPTION
**Pull request by samueldr**
#### Motivation for this change

Backport of #80592 to 20.03 (next stable).

Once this is successfully eval'd by ofborg this is good to be merged. I prefer going for a full eval since I squashed two commits together, and cherry-picked a maintainer file changed.

###### Things done

- [ x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by samueldr** [comment]
Sorry y'all pinged people, forgot to change the branch when opening the PR.

**Comment by worldofpeace** [comment]
@samueldr You also need https://github.com/NixOS/nixpkgs/commit/2f0614bdcb4c962440b9107f9e4c6d2f396b768f#diff-498fa90aaf17420b9719f0b04e1c3d08

**Comment by JeffLabonte** [comment]
@samueldr Thank you for opening this PR!

**Comment by samueldr** [comment]
good catch @worldofpeace, that's why I opened it as a PR, I knew it was likely I forgot one of these bits when doing the quick backport.

**Pull request merged**
