### PR TITLE
Revert "bottles: cleanup"

### PR DESCRIPTION
**Pull request by psydvl**
Reverts NixOS/nixpkgs#169136
We need automatic updates via passthru.UpdateScript

### CODE REVIEW

**Comment by psydvl** [comment]
Related links:
nixpkgs manual: 6.4.3.2. passthru.updateScript https://nixos.org/manual/nixpkgs/stable/#special-variables
Automatic update bot https://github.com/r-ryantm
https://github.com/ryantm/nixpkgs-update

**Review by mohe2015 — CHANGES_REQUESTED** [review]
To my knowledge
`nix-shell maintainers/scripts/update.nix --argstr package bottles` is not intended to work for packages with fetchFromGithub. Instead you should use e.g. https://github.com/Mic92/nix-update


I don't know though why fetchFromGithub doesn't do "magic" to make this work.

**Comment by OPNA2608** [comment]
`gitUpdater` could be used. (examples [1](https://github.com/NixOS/nixpkgs/blob/634141959076a8ab69ca2cca0f266852256d79ee/pkgs/tools/backup/stenc/default.nix#L21), [2](https://github.com/NixOS/nixpkgs/blob/1ffba9f2f683063c2b14c9f4d12c55ad5f4ed887/pkgs/applications/audio/furnace/default.nix#L82-L85))

```nix
passthru.updateScript = gitUpdater {
  inherit pname version;
  url = "https://github.com/bottlesdevs/bottles.git";
};
```

(Explicit url is required because `fetchFromGitHub` by default fetches a tarball instead of via git)

**Comment by psydvl** [comment]
@mohe2015 that's why I add `pasthru.UpdateScript`
However, you can manually check it's worked before:
``` console
$ git checkout 939acfebcd0bdec7f5fbcbc31dbe14e8af39910e # commit before "cleanup"
$ nix-shell maintainers/scripts/update.nix --argstr package bottles
Going to be running update for following packages:

 - bottles-2022.4.14-trento-1

Press Enter key to continue...

Running update for:
 - bottles-2022.4.14-trento-1: UPDATING ...
 - bottles-2022.4.14-trento-1: DONE.

Packages updated!

```
``` diff
$ git diff pkgs/applications/misc/bottles/default.nix
diff --git a/pkgs/applications/misc/bottles/default.nix b/pkgs/applications/misc/bottles/default.nix
index f4e1e50347a..b008638ac38 100644
--- a/pkgs/applications/misc/bottles/default.nix
+++ b/pkgs/applications/misc/bottles/default.nix
@@ -20,8 +20,8 @@ let
 in
 python3Packages.buildPythonApplication rec {
   pname = "bottles";
-  version = "2022.4.14-trento-1";
-  sha256 = "16cb01fhxa64f8fadwpr0mawfmchig6xlbx20mz4q9yh5fnagywj";
+  version = "2022.4.14-trento-2";
+  sha256 = "0w1dc8f7pxvfriy552a1s9hxk32zxgsni6d9zid0zy0f105vyfpb";
   # Note: Update via pkgs/applications/misc/bottles/update.py
   # mostly copypasted from pkgs/applications/networking/instant-messengers/telegram/tdesktop/update.py

```
``` console
$ git checkout . # for reset all chenges made by update before
$ git checkout a08498a0cd8751e4427a2f4729c76eb1cf152e14 # "cleanup" commit
$ nix-shell maintainers/scripts/update.nix --argstr package bottles
Going to be running update for following packages:

 - bottles-2022.4.14-trento-1

Press Enter key to continue...

Running update for:
 - bottles-2022.4.14-trento-1: UPDATING ...
 - bottles-2022.4.14-trento-1: DONE.

Packages updated!

$ git diff pkgs/applications/misc/bottles/default.nix
```
Yes, after "cleanup" commit update does nothing

**Comment by psydvl** [comment]
Will use `gitUpdater` instead, thanks @OPNA2608 
https://github.com/NixOS/nixpkgs/pull/169493

**Pull request closed without merging**
