### PR TITLE
haskell: preserve overrideScope on override

### LINKED ISSUE #7953: Haskell packages lose theire "overrideScope" attribute after a normal "override"
The following override works fine:

```
hsemail = super.hsemail.overrideScope (self: super: { parsec = super.parsec; });
```

But if a "normal" override is added before the Haskell-specific-one

```
hsemail = (super.hsemail.override {}).overrideScope (self: super: { parsec = super.parsec; });
```

..., then evaluation fails:

> error: attribute ‘overrideScope’ missing, at "/home/simons/.nix-defexpr/pkgs/development/haskell-modules/configuration-common.nix":846:13

The reason is that the `overrideScope` attribute is added by our special `mkDerivation` function from Haskell NG, but `override` is a normal Nixpkgs mechanism that is unaware of this particular feature, i.e. the overridden version of the attribute returned by `override` no longer has `overrideScope`.

### PR DESCRIPTION
**Pull request by bennofs**
We want code such as `(pkg.override {}).overrideScope (self: super: {})` to
work. This didn't work before, since `override` will call the original package
again, and the attribute `overideScope`, which `callPackageWithScope` added,
wasn't added again. The fix for this is to modify the package function itself
to include the `callPackageWithScope` attribute, so it'll be re-added whenever
the function is overriden for with arguments.

There is a small problem here though: since callPackage uses some magic
(`builtins.functionArgs`) to determine the auto-arguments of a function, we
can't just write `callPackageWith scope drvScope`, since
`builtins.functionArgs drvScope` will be `{}`. To fix this, we implement our own
`callPackageWith`.

fixes NixOS/nixpkgs#7953

@peti can you test that this doesn't lead to unexpected side effects, I'm unsure about the performance implications of the change.

### CODE REVIEW

**Comment by rasendubi** [comment]
(triage) As far as I can tell, it's still relevant.

@peti would you like to review this?

**Comment by peti** [comment]
I'm not sure what to do with this patch. It does a problem we have (albeit not an urgent one), so we want to merge, I suppose. On the other hand, the patch duplicates code that we probably don't want to duplicate. Instead, the proper implementation of `callPackageWith` should be refactord/extended. Doing that is a bit of an effort, though, and I don't see anyone who's willing to dedicate that effort right now. So it seems like we're stuck.

**Comment by bennofs** [comment]
I don't think that the duplicated code should be of much concern: it is only 3 lines that are duplicated (the `drv` and `auto` let bindings). Anyway, I rebased the branch to be compatible with master.

**Comment by domenkozar** [comment]
@bennofs can you verify that master still needs this fix?

**Comment by bennofs** [comment]
@domenkozar yes still necessary:

```
d-cube:/c/nixpkgs (master=) nix-build -E 'with (import ./. {}); (haskellPackages.acme-realworld.override {}).overrideScope (self: super: {})'
error: attribute ‘overrideScope’ missing, at (string):1:23
```

**Comment by peti** [comment]
@bennofs, your example was not fixed by https://github.com/NixOS/nixpkgs/pull/22613?

**Comment by bennofs** [comment]
@peti yes stil:

```
 $ git pull; nix-build -E 'with (import ./. {}); (haskellPackages.acme-realworld.override {}).overrideScope (self: super: {})'
Already up-to-date.
error: attribute ‘overrideScope’ missing, at (string):1:23
```

How should that patch fix this? The issue is that `overrideScope` ìs not added "under" `callPackage`, but instead is added directly to the *result* of `callPackage`. So `callPackage` doesn't know about the extra attribute, and the `override` function will no re-add it after re-calling the package with new arguments,

**Comment by peti** [comment]
Okay, thank you for the clarification. We currently have patches for 3
different issues that sound similar but are in fact different and it
seems like I've lost track of which is which.

**Comment by bennofs** [comment]
@peti so any idea how we progress with this? it's currently one of the oldest PRs on the nixpkgs repo, and I don't think that more time will change the situation. So it seems we have three options:

1. leave the code as is. I'm not sure how common it is to want to call `overrideScope` after `override`, but it is probably bad if you want to `overrideScope` a pkg that has overrides defined by some of the standard `-configuration` overrides.
2. copy 3 lines from `customization.nix` and adapt them
3. change `customization.nix` to support this, which might break other parts of nixpkgs in unforseen ways (will need lots of reviews for sure)

**Comment by peti** [comment]
@bennofs, I think option (2) is the best solution. The code duplication is unfortunate, but I don't see any reasonable way around it. Would you mind pushing an updated version of this patch that fixes the merge conflicts? I'll be happy to merge the PR then.

**Comment by peti** [comment]
Merged to `haskell-updates` for test-building in b39964cec5d505c00196ff0983b9fe008aac8401.

**Comment by bennofs** [comment]
@peti I rebased to `master` and force-pushed.

**Comment by peti** [comment]
Something isn't right: http://hydra.nixos.org/jobset/nixpkgs/haskell-updates. After b39964cec5d505c00196ff0983b9fe008aac8401 was added to the branch, `stack` is broken, apparently because the override

~~~
  stack = super.stack.overrideScope (self: super: {
    store-core = self.store-core_0_3;
    store = self.store_0_3_1;
  });
~~~

no longer works as before.

**Comment by bennofs** [comment]
@peti that is... weird. I will investigate.

**Comment by bennofs** [comment]
@peti fixed. stack compiles now. I added some docs that explain the the trickiness here.

**Pull request closed without merging**
