### PR TITLE
Add path to openSUSE certificate store

### PR DESCRIPTION
**Pull request by alternateved**
###### Description of changes

It seems that openSUSE suffers from [similar issue](https://discourse.nixos.org/t/certificate-validation-broken-in-all-electron-chromium-apps-and-browsers/15962) as Fedora/RHEL which was fixed with https://github.com/NixOS/nixpkgs/pull/146545. As could be seen from [openSUSE repository of ca-certificates](https://github.com/openSUSE/ca-certificates), openSUSE has certificate store in `/var/lib/ca-certificates` which then gets symlinked to all other places where applications would expect certificate store.

This fixes issue with `ERR_CERT_AUTHORITY_INVALID` error while trying to use Electron apps such as Discord or Slack.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rnhmjoj** [comment]
Looks good to me. You have to change the target branch to staging, though: this will cause a massive number of rebuilds.

**Comment by alternateved** [comment]
Of course, thanks.

**Comment by rnhmjoj** [comment]
Ah, one last thing: can you [prefix](https://nixos.org/manual/nixpkgs/stable/#chap-submitting-changes) the commit message with the name of the package? 
Like `p11-kit: add path ...`

**Comment by alternateved** [comment]
Is there anything else that I should correct?

**Comment by alternateved** [comment]
Great! Thank you for your help and suggestions.

**Pull request merged**
