### PR TITLE
pylint: 3.0.3 -> 3.1.0

### PR DESCRIPTION
**Pull request by funkeleinhorn**
## Description of changes

updated pylint from 3.0.3 to 3.1.0
changelog: https://github.com/pylint-dev/pylint/releases/tag/v3.1.0

updated astroid from 3.0.2 to 3.1.0 as pylint 3.1.0 depends on it
changelog: https://github.com/pylint-dev/astroid/releases/tag/v3.1.0

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [X] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by funkeleinhorn** [comment]
@GaetanLepage please review

**Comment by GaetanLepage** [comment]
Diff LGTM, but as updating `pylint` causes a massive number of rebuilds, you will have to target the `staging branch`.
Hence, please put this PR in draft mode and rebase it to `staging`. Finally, set the "target branch" to `staging`.

**Comment by funkeleinhorn** [comment]
Changed and rebased to staging. Should I reopen the PR or leave it as a draft for now?

**Comment by GaetanLepage** [comment]
> Changed and rebased to staging. Should I reopen the PR or leave it as a draft for now?

Good ! No, you can just re-mark this as "ready".

**Comment by funkeleinhorn** [comment]
Pipeline failed as the runner ran out of space while bulding the nixos manual. Could this job be restarted?

**Comment by iFreilicht** [comment]
This upgrade broke the build on aarch64-darwin: https://hydra.nixos.org/build/253881018

```
=================================== FAILURES ===================================
______________________ test_package[file_names1-<lambda>] ______________________
[gw0] darwin -- Python 3.11.8 /nix/store/c05vbvkjxarxkws9zkwrcwrzlsx9nd68-python3-3.11.8/bin/python3.11

finalize_linter = Checker 'main' (responsible for 'F0001', 'F0002', 'F0010', 'F0011', 'I0001', 'I0010', 'I0011', 'I0013', 'I0020', 'I0021', 'I0022', 'E0001', 'E0011', 'W0012', 'R0022', 'E0013', 'E0014', 'E0015')
file_names = ['precedence_test']
check = <function Equals.<locals>.<lambda> at 0x106c54360>

    @pytest.mark.parametrize(
        "file_names, check",
        [
            (["package.__init__"], Equals("")),
            (["precedence_test"], Equals("")),
            (["import_package_subpackage_module"], Equals("")),
            (["pylint.checkers.__init__"], lambda x: "__path__" not in x),
            ([join(REGR_DATA, "classdoc_usage.py")], Equals("")),
            ([join(REGR_DATA, "module_global.py")], Equals("")),
            ([join(REGR_DATA, "decimal_inference.py")], Equals("")),
            ([join(REGR_DATA, "absimp", "string.py")], Equals("")),
            ([join(REGR_DATA, "bad_package")], lambda x: "Unused import missing" in x),
        ],
    )
    def test_package(
        finalize_linter: PyLinter, file_names: list[str], check: Callable[[str], bool]
    ) -> None:
        finalize_linter.check(file_names)
        finalize_linter.reporter = cast(  # Due to fixture
            testutils.GenericTestReporter, finalize_linter.reporter
        )
        got = finalize_linter.reporter.finalize().strip()
>       assert check(got)
E       assert False
E        +  where False = <function Equals.<locals>.<lambda> at 0x106c54360>("E: 21: Module 'package.AudioTime' has no 'DECIMAL' member")

tests/test_regr.py:77: AssertionError
=========================== short test summary info ============================
FAILED tests/test_regr.py::test_package[file_names1-<lambda>] - assert False
============ 1 failed, 954 passed, 251 skipped, 5 xfailed in 23.70s ============
```

**Pull request merged**
