### PR TITLE
Properly fix nixos-version --hash when building from Git

### PR DESCRIPTION
**Pull request by aszlig**
First of all sorry for not reviewing #17218 in the first place.

The changes here IMHO follow a better approach by using the .git directory directly for fetching the hash rather than placing an additional `.git-revision` file beneath it containing the same redundant information.

@bennofs: Can you test whether these changes work for you as well?

Cc: @Profpatsch

### CODE REVIEW

**Comment by bennofs** [comment]
The reason I'm using `.git-revision` is that it also works with the nixpkgs channels, see `nixos/lib/make-channel.nix`, which don't contain the `.git` directory. What is your problem with the `.git-revision` file in the root directory? We already have had `.version-suffix` following the same principle.

**Comment by aszlig** [comment]
@bennofs: This doesn't affect channels at all, because they (usually) don't contain .git directories. Even if they do it doesn't make any difference either. Of course we could find a way to get rid of `.version-suffix` as well.

Of course with "getting rid" I mean not entirely but just avoid creating them when they aren't needed. If we have a channel tarball, this information is missing, so we need `.git-revision` and `.version-suffix` because Git information isn't available. But creating redundant information in an already existing Git working tree is unnecessary and will just confuse users about why those files suddenly are there, especially because they're really not needed at all and we _already_ check the `.git` dir as well.

**Comment by bennofs** [comment]
Oh I see, I'm on board with that. I thought that you removed the support for `.git-revision` entirely, but you just don't create it when `nixos-rebuild`ing, but still support it for channels. That makes sense! But in that case, I think you can remove the code for `.version-suffix` as well?

**Comment by aszlig** [comment]
@bennofs: Working on it...

**Comment by aszlig** [comment]
@bennofs: Okay, this one is a lot more complicated, because it appends an `M` if the working dir is dirty (uses `git describe` for that). So leaving `.version-suffix` as-is for now.

**Comment by bennofs** [comment]
Works for me! :+1:

**Pull request merged**
