### PR TITLE
staging-next 2024-03-01

### PR DESCRIPTION
**Pull request by vcunat**
##### Helpful links

- workflow docs: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#staging
- important jobs:
  https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
  https://hydra.nixos.org/job/nixos/staging-next-small/tested
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next
  https://hydra.nixos.org/jobset/nixos/staging-next-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/289734
- - - 
##### Mass breakages
- [x] libbacktrace is failing since [xz: 5.4.6 -> 5.6.0](https://github.com/NixOS/nixpkgs/pull/291205#issuecomment-1974838835); https://github.com/ianlancetaylor/libbacktrace/issues/118;

(will be edited based on progress)

### CODE REVIEW

**Comment by infinisil** [comment]
There's an inconsequential `pkgs/by-name` check failure with this PR, here's a PR to fix it though: https://github.com/NixOS/nixpkgs/pull/292674

**Review by 999eagle — COMMENTED** [review]
I was just about to open a PR for the `libheif` as well. Wouldn't this be easier:

```
  cmakeFlags = [
    "-DCMAKE_INSTALL_PREFIX=${placeholder "dev"}"
  ];
```

**Comment by vcunat** [comment]
I suspect that would say to install **everything** into $dev, which wouldn't be what we want.

**Comment by vcunat** [comment]
- [ ] `python3Packages.debugpy` tests hang
  https://hydra.nixos.org/build/252462132
  Looks like a reproducible regression against nixpkgs master, for both linuxes and both pythons
  maintainer: @kira-bruneau

**Comment by mweinelt** [comment]
A regularly complaint about debugpy tests: https://github.com/NixOS/nixpkgs/issues/262000

**Comment by vcunat** [comment]
Oh OK, let me disable them for now: e0008b48c915

**Comment by vcunat** [comment]
Overall I don't expect large improvements within days, so let's merge.

**Pull request merged**
