### PR TITLE
hedgedoc: fix executing any of the management clis

### LINKED ISSUE #189213: hedgedoc manage_users looks for a git repository, fails to start
### Describe the bug
```
$ manage_users 
fatal: not a git repository (or any of the parent directories): .git
```

### Steps To Reproduce
1. nix-shell -p hedgedoc
2. manage_users

### Expected behavior
manage_user runs.

### PR DESCRIPTION
**Pull request by SuperSandro2000**
## Description of changes

Before it failed with ```
$ manage_users 
fatal: not a git repository (or any of the parent directories): .git
```

when you now execute manage_users it fails like the following which means it couldn't find the config.

```
 ▶ ./result/bin/manage_users
2024-01-24T12:36:11.492Z warn:  Neither 'domain' nor 'CMD_DOMAIN' is configured. This can cause issues with various components.
Hint: Make sure 'protocolUseSSL' and 'urlAddPort' or 'CMD_PROTOCOL_USESSL' and 'CMD_URL_ADDPORT' are configured properly.
2024-01-24T12:36:11.493Z warn:  Session secret not set. Using random generated one. Please set `sessionSecret` in your config.json file. All users will be logged out.
2024-01-24T12:36:11.498Z error:         uncaughtException: Dialect needs to be explicitly supplied as of v4.0.0
Error: Dialect needs to be explicitly supplied as of v4.0.0
    at new Sequelize (/nix/store/0l5xmb5lycfqfp7mm4kfwv6l2lx10wik-hedgedoc-1.9.9/node_modules/sequelize/lib/sequelize.js:275:13)
    at Object.<anonymous> (/nix/store/0l5xmb5lycfqfp7mm4kfwv6l2lx10wik-hedgedoc-1.9.9/lib/models/index.js:27:15)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/nix/store/0l5xmb5lycfqfp7mm4kfwv6l2lx10wik-hedgedoc-1.9.9/app.js:27:16)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
```

Closes #189213

This likely needs some integration in the nixos module to be really useful but I leave that up to someone else.

## Things done

<!-- Please check what applies. Note that these are not hard requirements but merely serve as information for reviewers. -->

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

<!--
To help with the large amounts of pull requests, we would appreciate your
reviews of other pull requests, especially simple package updates. Just leave a
comment describing what you have tested in the relevant package/service.
Reviewing helps to reduce the average time-to-merge for everyone.
Thanks a lot if you do!

List of open PRs: https://github.com/NixOS/nixpkgs/pulls
Reviewing guidelines: https://nixos.org/manual/nixpkgs/unstable/#chap-reviewing-contributions
-->

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by MangoIV** [comment]
I cannot reproduce the failure you got locally (wrt the git repository), it just did nothing.

**Comment by MangoIV** [comment]
I will apply your patch and look at whether it solve smy issues anyway

**Comment by nabcos** [comment]
I had no output from manage_users as well. I did not try this patch, but I think you need to provide the config file as env variable for the scripts, as the systemd service sets `Environment=CMD_CONFIG_FILE=/run/hedgedoc/config.json`, and that variable also needs to be present for the CLI.

For now, I worked around the issue by creating a wrapper script (needs root to execute to be able to read the config file):
```
    environment.systemPackages = [
      (
      pkgs.writeShellScriptBin "hedgedoc-manage_users" ''
        CMD_CONFIG_FILE=/run/hedgedoc/config.json NODE_ENV=production ${pkgs.nodejs_21}/bin/node ${pkgs.hedgedoc}/bin/manage_users
      ''
      )
    ];
```

With that wrapper script, I get output and was able to add users.

**Comment by SuperSandro2000** [comment]
We only know about `CMD_CONFIG_FILE` at https://github.com/NixOS/nixpkgs/blob/721901cf20e147ebba7873e399f1b3f9f87a4dee/nixos/modules/services/web-apps/hedgedoc.nix#L275 so I ma not sure how to fix that yet but I would like to delay that to at least be able to run the clis with the env set.

**Comment by SuperSandro2000** [comment]
@ofborg test hedgedoc

**Pull request merged**
