### PR TITLE
Remove nodejs-6_x which is about to enter EOL

### LINKED ISSUE #58953: Node 6 is due to go EOL on 2019-04-30
## Issue description
Node 6 is due to go End-of-Life on 2019-04-30 https://github.com/nodejs/Release

In d956f2279b8ac02bd9e48cf2a09dcb66383ab6be there are still references to nodejs-6_x
```
$ git grep nodejs-6_x
pkgs/development/node-packages/composition-v6.nix:  }, system ? builtins.currentSystem, nodejs ? pkgs."nodejs-6_x"}:
pkgs/development/web/remarkjs/nodepkgs.nix:  }, system ? builtins.currentSystem, nodejs ? pkgs."nodejs-6_x"}:
pkgs/misc/base16-builder/default.nix:  #            --pkg-name nodejs-6_x
pkgs/misc/base16-builder/node-packages.nix:  }, system ? builtins.currentSystem, nodejs ? pkgs."nodejs-6_x"}:
pkgs/servers/web-apps/codimd/CodeMirror/default.nix:{ stdenv, pkgs, buildEnv, fetchFromGitHub, nodejs-6_x, phantomjs2, which }:
pkgs/servers/web-apps/codimd/CodeMirror/default.nix:  buildInputs = [ nodejs-6_x phantomjs-prebuilt ] ++ (stdenv.lib.attrVals [
pkgs/servers/web-apps/codimd/CodeMirror/node.nix:  }, system ? builtins.currentSystem, nodejs ? pkgs."nodejs-6_x"}:
pkgs/servers/web-apps/codimd/default.nix:, fetchpatch, nodejs-6_x, phantomjs2, runtimeShell }:
pkgs/servers/web-apps/codimd/default.nix:  buildInputs = [ nodejs-6_x ];
pkgs/servers/web-apps/codimd/default.nix:      ${nodejs-6_x}/bin/node $out/app.js
pkgs/servers/web-apps/codimd/node.nix:  }, system ? builtins.currentSystem, nodejs ? pkgs."nodejs-6_x"}:
pkgs/tools/networking/airfield/node.nix:  }, system ? builtins.currentSystem, nodejs ? pkgs."nodejs-6_x"}:
pkgs/tools/package-management/nixui/nixui.nix:  }, system ? builtins.currentSystem, nodejs ? pkgs."nodejs-6_x"}:
pkgs/tools/security/bitwarden-cli/node-packages.nix:  }, system ? builtins.currentSystem, nodejs ? pkgs."nodejs-6_x"}:
pkgs/top-level/all-packages.nix:  nodejs-6_x = callPackage ../development/web/nodejs/v6.nix {};
pkgs/top-level/all-packages.nix:    nodejs = pkgs.nodejs-6_x;
```

### PR DESCRIPTION
**Pull request by gilligan**
###### Motivation for this change

nodejs 6.x is entering EOL soon, so we should get rid of it - Fixes #58953

###### Things done

- Remove nodejs-6_x
- Set nodejs / nodejs-slim to nodejs-8_x / nodejs-slim-8_x
- Re-generate node2nix generated files using nodejs-8_x instead

### CODE REVIEW

**Comment by adisbladis** [comment]
I had to repair a few packages:
- `bitwarden-cli`
- `airfield`
- `base16-builder`

Still broken:
- `codimd`

**Comment by gilligan** [comment]
```
building '/nix/store/bgvg4dvnh5iqb4j8yxs1x8zvc0jcfq8r-node-babel-plugin-transform-runtime-6.23.0.drv'...
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to http://www.example.com/lodash failed, reason: getaddrinfo ENOTFOUND www.example.com www.example.com:80
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/.npm/_logs/2019-04-04T18_09_12_784Z-debug.log
```

Hm yeah so node2nix failed to resolve all dependencies which leads to npm trying to fetch/install whatever is missing ;/ 

Oh dear, looking at the `default.nix` of `codimd` there is a lot of patching/hacking going on around npm dependencies which i really do not want to fiddle with. I hope @WilliButz is around.

**Comment by WilliButz** [comment]
@gilligan @adisbladis Quite some time ago (according to my stash it was in the end of october) I abandoned the node2nix approach and repackaged it successfully using yarn2nix (and nodejs 8) because I also think that right now it's way too hacky.
Unfortunately I currently have two impediments regarding the upstreaming of it, for one I depend on (the not yet merged) git support for yarn2nix introduced in https://github.com/moretea/yarn2nix/pull/85 and I am also a little short of time for at least the next two weeks.

**Comment by Ma27** [comment]
As I'm fairly interested in keeping `codimd` in nixpkgs, here are some of my thoughts:

* I'm currently not sure if it's such a good idea to use `yarn2nix` in `nixpkgs` as it's been removed recently (#58424). But if we pull the needed `yarn2nix` sources to build `codimd`, I guess it should be fine for this use case to simply use a git rev which includes `git` support.
* We could simply try to regenerate the `node2nix` package set and modify the expression accordingly. We currently use Codimd 1.2.0 which should work with NodeJS 8 as well (https://github.com/codimd/server/blob/1.2.0/package.json#L136-L138), the latest version (1.3.x supports NodeJS 10 as well).

Unless anybody else wants to take over, I can attempt to do an update of `codimd` tomorrow to ensure that it's working until we have a simpler solution based on `yarn2nix`.

**Comment by Ma27** [comment]
Unfortunately it seems as it's not possible to regenerate the `codimd` package set in its current state as `node2nix` fails to resolve some dependencies. I hope that I can fix that this weekend, however `codimd` is certainly not a blocker for 19.03, so I'd suggest that we mark `codimd` as broken here and backport the fix for `codimd` as soon as it's ready :)

**Comment by Ma27** [comment]
#59118 for `codimd`.

**Comment by samueldr** [comment]
Just checking, @gilligan / @adisbladis that with #59118 now open, everything is fine?

This PR can be merged? The other one looks ready to me.

**Review by Ma27 — APPROVED** [review]

**Comment by samueldr** [comment]
Shouldn't we remove `remarkjs`, marked broken since 2016-06-11? I think we should.

**Comment by samueldr** [comment]
Backported
[release-19.03 763e65fe78f] Remove nodejs-6_x which is about to enter EOL
 Date: Thu Apr 4 19:10:06 2019 +0200
 23 files changed, 3520 insertions(+), 720 deletions(-)

**Pull request merged**
