### PR TITLE
grub2: switch to release tarball  & fix cross shebang

### LINKED ISSUE #125491: grub-install: locale directory doesn't exist
After upgrading to 21.05, when running `nixos-rebuild switch --upgrade`, I get the following warning:

```
/nix/store/475gqf8jmkgsnzqr3zspvwj20xdbl0xr-grub-2.06-rc1/sbin/grub-install: warning: cannot open directory `/nix/store/475gqf8jmkgsnzqr3zspvwj20xdbl0xr-grub-2.06-rc1/share/locale': No such file or directory.
```

Everything else seems to work fine, but it's unclear what has gone wrong here, or if I should be worried.

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.78, NixOS, 21.05.650.eaba7870ffc (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - channels(root): `"nixos-21.05.650.eaba7870ffc"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by Artturin**
works-around /nix/store/d283v972wlp4fplvdn7v8nr5xx5si60k-grub-2.06/sbin/grub-install: warning: cannot open directory `/nix/store/d283v972wlp4fplvdn7v8nr5xx5si60k-grub-2.06/share/locale': No such file or directory.

if we want to enable them we will need to fetch them from https://translationproject.org/latest/grub/
i did not find a versioned url or a tarball

###### Motivation for this change
Closes https://github.com/NixOS/nixpkgs/issues/125491

###### Things done
tested building the virtualbox image before and after and now there is no error.

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mkg20001** [comment]
You could use archive.org URLs. The current version on archive.org is https://web.archive.org/web/20190925210108/http://translationproject.org/latest/grub/

It's the best stopgap I can think of, the alternative would be asking upstream whether a translation zip can be provided or checking where debian pulls it from and seeing if they already have something similar

**Comment by samueldr** [comment]
Debian, fedora, gentoo, archlinux, all options to look at for "best practices".

**Comment by mkg20001** [comment]
This is from ubuntu https://git.launchpad.net/~ubuntu-core-dev/grub/+git/ubuntu/tree/debian/po?h=debian/2.04-1ubuntu48

Seems like they just put the files into their own version control, repo is https://git.launchpad.net/~ubuntu-core-dev/grub/+git/ubuntu  the tags can be found on that page

**Comment by samueldr** [comment]
# Arch Linux

No locales downloaded AFAICT

 - https://github.com/archlinux/svntogit-packages/blob/8e56f8a1898d6da50b0e341af1b8e2378136a893/trunk/PKGBUILD#L84
 - https://github.com/archlinux/svntogit-packages/blob/8e56f8a1898d6da50b0e341af1b8e2378136a893/trunk/PKGBUILD#L141-L142

Confused about that statement.

¯\\\_(ツ)\_/¯

# Debian

Unsure about how to check what it downloads, if anything.

 - https://salsa.debian.org/grub-team/grub/-/blob/4144b27ff6c1e89c276693f086c2663f367e27f1/debian/rules#L349

¯\\\_(ツ)\_/¯

# Gentoo

Enabled too. Can't seem to find obvious traces of 

 - https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-boot/grub/grub-2.06-r1.ebuild?h=abe655fe66964de0a45e8d0c158bdf3958cdfd1c#n218

There is a big distinction here: it uses the tarball AFAICT:

 - https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-boot/grub/grub-2.06-r1.ebuild?h=abe655fe66964de0a45e8d0c158bdf3958cdfd1c#n44

Maybe the translations were captured in the release. We probably should move the the release tarball in that case; it is the policy to use released tarballs when projects make them.

# Fedora

Situation seems similar:

 - https://src.fedoraproject.org/rpms/grub2/blob/rawhide/f/grub2.spec#_22

Using the release tarball, but can't figure out whether it compiles with or without nls.

**Comment by samueldr** [comment]
Release tarballs include translations:

```
~/tmp/tmp/grub-2.06 $ pwd
/Users/samuel/tmp/tmp/grub-2.06

~/tmp/tmp/grub-2.06 $ find po/ | head -n10
po/
po/de@hebrew.gmo
po/nl.gmo
po/cyrillic.sed
po/pa.gmo
po/ast.gmo
po/sl.gmo
po/eo.gmo
po/ro.po
po/boldquot.sed
```

Compare to the git repo:

 - https://git.savannah.gnu.org/cgit/grub.git/tree/po

**Comment by Artturin** [comment]
grub was switched to the vcs source in 2014, should probably be safe to switch it back now. 1f460e00efb99a1450f5b5806d68ff6633641ad8

**Comment by Artturin** [comment]
diffoscope https://gist.github.com/Artturin/4edc5d6bc3f2f2afbf0d4edffa2d45e1

**Comment by Artturin** [comment]
```
nix-store --query --references $(chase result)
/nix/store/fgy0y973qix6k1byywd5za0qhkrpanih-glibc-aarch64-unknown-linux-gnu-2.33-56
/nix/store/4s84mvbfv0if6v4xg3i3d5shnpnclvfd-fuse-aarch64-unknown-linux-gnu-2.9.9
/nix/store/ahsls4h434g2kkbi36f6s37ah7q5kbic-lvm2-aarch64-unknown-linux-gnu-2.03.12-lib
/nix/store/cqgic24marclwwsaaxk0jka95dy63qxr-bash-5.1-p8-aarch64-unknown-linux-gnu
/nix/store/l0wlqpbsvh1pgvhcdhw7qkka3d31si7k-bash-5.1-p8
/nix/store/ywfrrgl7ww7sfp9ma5if0iigz6gvbckp-freetype-aarch64-unknown-linux-gnu-2.11.0
/nix/store/9djhjws5h2ykmw102p8y7ga51x6jq2gf-grub-aarch64-unknown-linux-gnu-2.06
 nix why-depends ./result ".#bash"
/nix/store/9djhjws5h2ykmw102p8y7ga51x6jq2gf-grub-aarch64-unknown-linux-gnu-2.06
└───lib/grub/arm64-efi/modinfo.sh: …#!/nix/store/l0wlqpbsvh1pgvhcdhw7qkka3d31si7k-bash-5.1-p8/bin/bash..# User-co…
    → /nix/store/l0wlqpbsvh1pgvhcdhw7qkka3d31si7k-bash-5.1-p8
```
will fix this too

**Comment by samueldr** [comment]
Don't forget to update the PR title to something more correctlier.

**Review by mkg20001 — APPROVED** [review]

**Comment by Artturin** [comment]
built my system with this change and it booted

**Comment by ajs124** [comment]
This probably broke `nixos.tests.installer.separateBoot.x86_64-linux`, therefore blocking unstable-small.

Did you run the installer tests before merging this?

**Comment by ajs124** [comment]
git bisect says yes. Log output is this:
```
machine # building '/nix/store/3s5r35dr4i39148wycdi878n7jbrxznv-stage-1-init.sh.drv'...
machine # checking syntax
machine # building '/nix/store/48abbgal241s714fpgldngbbk2hg7x6w-initrd-linux-5.10.81.drv'...
machine # 121297 blocks
machine # building '/nix/store/1fizlmy99ik6pwjyyzrdsb3z2zcgwq3z-nixos-system-nixos-22.05pre-git.drv'...
machine # /nix/store/h2hwn3kas58vlsqhbjf7ndyqzjx92vhq-nixos-system-nixos-22.05pre-git
machine # copying channel...
machine # installing the boot loader...
machine # setting up /etc...
machine # /etc/tmpfiles.d/journal-nocow.conf:26: Failed to resolve specifier: uninitialized /etc detected, skipping
machine # All rules containing unresolvable specifiers will be skipped.
machine # updating GRUB 2 menu...
machine # installing the GRUB 2 boot loader on /dev/vda...
machine # Installing for i386-pc platform.
machine # Installation finished. No error reported.
machine # installation finished!
(302.08 seconds)
(302.08 seconds)
Do it again to make sure it's idempotent
machine: must succeed: nixos-install < /dev/null >&2
machine # building the configuration in /mnt/etc/nixos/configuration.nix...
machine # /nix/store/h2hwn3kas58vlsqhbjf7ndyqzjx92vhq-nixos-system-nixos-22.05pre-git
machine # copying channel...
machine # installing the boot loader...
machine # setting up /etc...
machine # /etc/tmpfiles.d/journal-nocow.conf:26: Failed to resolve specifier: uninitialized /etc detected, skipping
machine # All rules containing unresolvable specifiers will be skipped.
machine # updating GRUB 2 menu...
machine # installing the GRUB 2 boot loader on /dev/vda...
machine # Installing for i386-pc platform.
machine # /nix/store/4ppwb83yj9jgn8yds811142bblm0cadk-grub-2.06/sbin/grub-install: error: cannot copy `/nix/store/4ppwb83yj9jgn8yds811142bblm0cadk-grub-2.06/share/locale/en@piglatin/LC_MESSAGES/grub.mo' to `/boot/grub/locale/en@piglatin.mo': No space left on device.
machine # /nix/store/5fpw2zwv6a03l9ydmh797jhd5ivk93fy-install-grub.pl: installation of GRUB on /dev/vda failed: No such file or directory
machine: output:
Test "Do it again to make sure it's idempotent" failed with error: "command `nixos-install < /dev/null >&2` failed (exit code 1)"
cleanup
kill machine (pid 8)
machine # qemu-system-x86_64: terminating on signal 15 from pid 6 (/nix/store/5bh6rpya1ar6l49vrhx1rg58dsa42906-python3-3.9.6/bin/python3)
(0.19 seconds)
builder for '/nix/store/xayylcc8j5xs4bkcrfj60083nmsy0m06-vm-test-run-installer-separateBoot.drv' failed with exit code 1
```

Looks like the fix would just be increasing the size of this volume. I converted #147949 to a draft, so it doesn't get merged and also blocks 21.11.

**Comment by Artturin** [comment]
built a vm and the /boot used size went from 35M -> 39M

i'll make a pr increasin

**Pull request merged**
