### PR TITLE
srcOnly: fix invocation and document

### PR DESCRIPTION
**Pull request by zimbatm**
###### Motivation for this change

Previously, callPackage would try and fill the arguments such as `name`
and `src` which would cause problems if those existed as top-level
attributes. This also makes it clearer what part is the function
signature.

Then document the derivation inline in the code to explain the ellipsis
and various use-cases.

This is a follow-up on #80903

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zimbatm** [comment]
The `buildInputs` argument really should be `nativeBuildInputs` if the goal is to provide some extra unpackers.

**Review by edef1c — APPROVED** [review]
LGTM.

> The `buildInputs` argument really should be `nativeBuildInputs` if the goal is to provide some extra unpackers.

This seems reasonable, and probably deserves a followup commit. I suspect it'll break some usage, but the ripple effect there causes nixpkgs improvement if anything.

**Comment by zimbatm** [comment]
@edef1c: pushed the nativeBuildInputs change.

Inside of nixpkgs, `srcOnly` is used in one place and doesn't use the buildInputs.

**Review by cdepillabout — APPROVED** [review]
This looks good to me.

Thanks for adding documentation!

**Comment by zimbatm** [comment]
fixed the evaluation and made the last commit backward-compatible

**Pull request merged**
