### PR TITLE
kernelPackages.nct6687d: init at unstable-2023-09-22

### PR DESCRIPTION
**Pull request by Atemu**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Atemu** [comment]
If nobody has objections, I'm inclined to just self-merge this.

**Review by bjornfor — APPROVED** [review]
I'd prefer it if was merged upstream instead, but I'm not going to object to merging. And this might enable sensors on a machine of mine :-)

**Comment by Atemu** [comment]
@bjornfor yeah me too. See https://github.com/Fred78290/nct6687d/issues/52

Could you test whether it works on that machine? Just build the package for your kernelPackages and then `sudo insmod result/lib/modules/*/updates/nct6687.ko.xz`. It'll just magically show up in `sensors`.

**Comment by bjornfor** [comment]
> @bjornfor yeah me too. See [Fred78290/nct6687d#52](https://github.com/Fred78290/nct6687d/issues/52)
> 
> Could you test whether it works on that machine? Just build the package for your kernelPackages and then `sudo insmod result/lib/modules/*/updates/nct6687.ko.xz`. It'll just magically show up in `sensors`.

```
$ sudo insmod /nix/store/hdx4vm6vm11p79ja8k54xvq4hd4yij8i-nct6687d-unstable-2023-09-22/lib/modules/6.1.57/extra/nct6687.ko.xz 
insmod: ERROR: could not insert module /nix/store/hdx4vm6vm11p79ja8k54xvq4hd4yij8i-nct6687d-unstable-2023-09-22/lib/modules/6.1.57/extra/nct6687.ko.xz: No such device
```

I apparently misremembered the chip: I have _another_ machine with a working nct6776 (close but not close enough), but the machine I was thinking of has a different chip. This is the issue I have: https://github.com/lm-sensors/lm-sensors/issues/154

**Pull request merged**
