### PR TITLE
muzika: init at unstable-2023-06-07

### PR DESCRIPTION
**Pull request by onny**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fleaz** [comment]
Just build this locally and music playback is not working. Clicking on any song on the startpage produces
```
Gjs-Console-Message: 15:49:40.576: Error:  {} ../gst/playback/gsturidecodebin.c(1487): gen_source_element (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin1
Gjs-Console-Message: 15:49:40.596: Error:  {} ../gst/playback/gsturidecodebin.c(1487): gen_source_element (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin2
```
and then clicking the play button again results in 
```
(com.vixalien.muzika:466746): Gjs-CRITICAL **: 15:49:48.575: JS ERROR: Error: Failed to play
play@resource:///com/vixalien/muzika/js/main.js:18828:13
play_pause@resource:///com/vixalien/muzika/js/main.js:18853:12
activate@resource:///com/vixalien/muzika/js/main.js:18775:16
main@resource:///com/vixalien/muzika/js/main.js:19264:14
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
@file:///nix/store/qrmvzpaklrnilnx1x6mc4cjyy6h6mc3j-muzika-unstable-2023-06-07/bin/.com.vixalien.muzika-wrapped:23:40
@file:///nix/store/qrmvzpaklrnilnx1x6mc4cjyy6h6mc3j-muzika-unstable-2023-06-07/bin/.com.vixalien.muzika-wrapped:29:6
```

Also `Preferences` in the burger menu is grayed out for me.

**Comment by onny** [comment]
> Just build this locally and music playback is not working. Clicking on any song on the startpage produces
> 
> ```
> Gjs-Console-Message: 15:49:40.576: Error:  {} ../gst/playback/gsturidecodebin.c(1487): gen_source_element (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin1
> Gjs-Console-Message: 15:49:40.596: Error:  {} ../gst/playback/gsturidecodebin.c(1487): gen_source_element (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin2
> ```
> 
> and then clicking the play button again results in
> 
> ```
> (com.vixalien.muzika:466746): Gjs-CRITICAL **: 15:49:48.575: JS ERROR: Error: Failed to play
> play@resource:///com/vixalien/muzika/js/main.js:18828:13
> play_pause@resource:///com/vixalien/muzika/js/main.js:18853:12
> activate@resource:///com/vixalien/muzika/js/main.js:18775:16
> main@resource:///com/vixalien/muzika/js/main.js:19264:14
> run@resource:///org/gnome/gjs/modules/script/package.js:206:19
> @file:///nix/store/qrmvzpaklrnilnx1x6mc4cjyy6h6mc3j-muzika-unstable-2023-06-07/bin/.com.vixalien.muzika-wrapped:23:40
> @file:///nix/store/qrmvzpaklrnilnx1x6mc4cjyy6h6mc3j-muzika-unstable-2023-06-07/bin/.com.vixalien.muzika-wrapped:29:6
> ```
> 
> Also `Preferences` in the burger menu is grayed out for me.

also had issues with playback and changed buildInputs to

```
  buildInputs = [
    gjs
    glib-networking
    gst_all_1.gst-plugins-base
    gst_all_1.gstreamer
    gst_all_1.gst-plugins-base
    gst_all_1.gst-plugins-good
    gst_all_1.gst-plugins-bad
    gtk4
    libadwaita
    libsoup_3
  ];
```

Not sure which codecs are required but with this it is working for me. This app is in early development so I guess it is fine that some things are not implemented yet.

**Comment by fleaz** [comment]
Confirmed, basic playback is working now :)

**Comment by onny** [comment]
Thank you for testing :)

**Pull request merged**
