### PR TITLE
python3Packages.runway-python: fix build, enable tests

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

- Fetch source from GitHub and enable tests
- Add missing dependencies cryptography and pyOpenSSL

https://hydra.nixos.org/build/142599298

ZHF: #122042 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by prusnak** [comment]
@GrahamcOfBorg build python3Packages.runway-python

**Review by jonringer — COMMENTED** [review]
I get some python39 errors, but they look like upstream issues:

```
    def deserialize(self, value):
        try:
            image = value[value.find(",")+1:]
>           image = base64.decodestring(image.encode('utf8'))
E           AttributeError: module 'base64' has no attribute 'decodestring'
```

**Comment by prusnak** [comment]
> I get some python39 errors, but they look like upstream issues:

Reported in https://github.com/runwayml/model-sdk/issues/99

**Comment by mweinelt** [comment]
Disabled the failing tests for python>=3.9.

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 122076 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>2 packages built:</summary>  <ul>    <li>python38Packages.runway-python</li>    <li>python39Packages.runway-python</li>  </ul></details>

**Pull request merged**
