### PR TITLE
Revert "irrd: init at 4.2.6"

### PR DESCRIPTION
**Pull request by dotlambda**
Reverts NixOS/nixpkgs#210565

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Since this was merged a while ago we probably should add an alias. Also if the maintainer reacts in a few days to redo the package proper we can avoid the removal.

**Comment by yu-re-ka** [comment]
I'm somewhat surprised because we use upstream lockfiles in all kinds of places (Npm/Yarn, Ruby, Go, Rust), so they seem to be generally accepted. Lines of code added to nixpkgs can be solved by an FOD fetcher.

This has also landed in the 23.05 release and is running in production setups.

Can you please also adjust the documentation to make this more clear? The documentation currently mentions poetry2nix in this section:

> Packages inside nixpkgs are written by hand. However many tools exist in
> community to help save time. No tool is preferred at the moment. 

Maybe make this a "**We prefer that poetry2nix is not used inside nixpkgs**", since the current phrasing could be interpreted as "any of the listed tools can be used".

**Comment by yu-re-ka** [comment]
BTW there are reasons we did it like this:
upstream pins on exact versions for all of its dependencies, since they expect to be installed in its own venv. a.k.a. not sharing installed dependencies with other applications.
https://github.com/irrdnet/irrd/blob/main/pyproject.toml#L18
The poetry2nix implementation of the packaging reflects this upstream wish to fully determine the dependencies they are running with.

**Comment by dotlambda** [comment]
@yu-re-ka The PR you merged had many problems besides using poetry2nix.

**Comment by yu-re-ka** [comment]
@NetaliDev is working on rewriting the package using buildPythonPackage/pythonRelaxDepsHook/poetry-core.

**Comment by yu-re-ka** [comment]
Prefer this over the "mark as insecure" since it will result in less merge/rebase conflicts with our the new packaging

**Comment by dotlambda** [comment]
What will we do about 23.05?

**Comment by yu-re-ka** [comment]
> What will we do about 23.05?

I am for the solution that presents the least breaking change to the user.
Either we just update the lockfile from time to time for the rest of the release cycle (I could take care of that), or we can backport the new packaging once it is done.

**Pull request merged**
