### PR TITLE
python3Packages.datasette: 0.54.1 -> 0.57.1

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 0.57.1

Change log: https://github.com/simonw/datasette/releases/tag/0.57.1

Advisory: https://github.com/simonw/datasette/security/advisories/GHSA-xw7c-jx9m-xh5g

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 126242` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>datasette (python38Packages.datasette)</li>
    <li>python39Packages.datasette</li>
  </ul>
</details>

**Comment by risicle** [comment]
Patch should be easy enough to yank https://github.com/simonw/datasette/commit/26fc539312bca2551b6f048b6bcf4ffbb491289f

**Review by risicle — APPROVED** [review]
LGTM, `nixpkgs-review` happy for me, nixos x86_64, macos 10.15.

**Review by jonringer — APPROVED** [review]
LGTM

```
https://github.com/NixOS/nixpkgs/pull/126242

2 packages built:
datasette python39Packages.datasette
```

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 126242` at 052e0227 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>datasette (python38Packages.datasette)</li>
    <li>python39Packages.datasette</li>
  </ul>
</details>

**Pull request merged**
