### PR TITLE
Docker 20.10 fixes

### PR DESCRIPTION
**Pull request by mikroskeem**
###### Motivation for this change

- https://github.com/NixOS/nixpkgs/pull/108960#pullrequestreview-569152521
- https://github.com/NixOS/nixpkgs/pull/109418#issuecomment-760935552

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mikroskeem** [comment]
`nix build -Lf . nixosTests.docker` ran successfully.

**Comment by petabyteboy** [comment]
Can I push a fix for the mkRemovedOptionModule message as well?

**Comment by mikroskeem** [comment]
Sure.

**Review by ghost — APPROVED** [review]

**Review by roberth — APPROVED** [review]
Looks good. Thanks for the quick response!

**Comment by exFalso** [comment]
This does *not* work, I'm experiencing the socket issue (`failed to load listeners: no sockets found via socket activation`).
If I change `fd://` to `unix://` it works

**Pull request merged**
