### PR TITLE
torbrowser: 4.5.2 -> 4.5.3

### PR DESCRIPTION
**Pull request by christianlask**

### CODE REVIEW

**Comment by jagajaga** [comment]
Please rename commit's name following our guide from `CONTRIBUTING.md`.

**Comment by hiberno** [comment]
Done, I hope. :)

**Comment by joachifm** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/pull/8953

**Comment by hiberno** [comment]
I'll close it, then. Didn't see that PR beforehand.

**Pull request closed without merging**
