### PR TITLE
treewide: fix hard-coded `sourceRoot` prefix for `fetchgit`-based `src`

### PR DESCRIPTION
**Pull request by ShamrockLee**
## Description of changes

According to [Nixpkgs manual](https://nixos.org/manual/nixpkgs/unstable/#var-stdenv-sourceRoot) and [NixOS 23.11 Release Note](https://nixos.org/manual/nixos/stable/release-notes#sec-release-23.11), the `sourceRoot` attribute passed to `stdenv.mkDerivation` should be specified as `"${src.name}"` or `"${src.name}/subdir"` when `src` is produced using `fetchgit`-based fetchers.

`sourceRoot = "source"` or `sourceRoot = "source/subdir"` is based on the assumption that the `name` attribute of these pre-unpacked fetchers are always `"source"`, which is not the case. Expecting constant `name` also makes the source FODs prone to irrelevent hashes during version bumps.

This PR should cause no rebuild. As the issue occurs also on the stable branch, we could also backport this fix to the stable branch.

This is a continuation of #245388 and an initial effort for #294068.

## Things done

- Built on platform(s)
  - [X] x86_64-linux (no rebuild)
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ShamrockLee** [comment]
Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Review by AndersonTorres — APPROVED** [review]

**Review by drupol — CHANGES_REQUESTED** [review]
Hi!

Just to stay on the safe side, could you please call `@ofborg build` with all the derivations that were updated?

Thx

**Comment by ShamrockLee** [comment]
> Just to stay on the safe side, could you please call `@ofborg build` with all the derivations that were updated?

Is there a way to programmatically get the list of packages? The `nixpkgs-review` output goes too large to copy and paste from the terminal.

If not, I'll just log the output of nixpkgs-review and select them out manually.

**Comment by drupol** [comment]
I don't know any way of automatizing this, I guess manually doing it is the only way, there not that much.

**Comment by ShamrockLee** [comment]
@drupol I have confused this PR with #294068 in my previous reply. `nixpkgs-review` reports no rebuild in this PR, and great chance are that the build command will just download existing packages from Hydra. Anyway, I'll tag them by hand.

@ofborg build vimPlugins awesomebump geph localsend autodock-vina openrefine anilibria-winmaclinux c2fmzq frankenphp intiface-central lanzaboote-tool liana linien-gui mercure monophony rustdesk-flutter snippetexpanderx svix-server syn2mas torrentstream flutter coqPackages_8_16.vcfloat coqPackages_8_17.vcfloat mpfi opentelemetry-collector opentelemetry-collector-contrib opentelemetry-cpp python3Packages.bootstrap.flit-core python3Packages.daqp python3Packages.flit-core python3Packages.kanidm python3Packages.linien-client python3Packages.linien-common python3Packages.openllm-client python3Packages.openllm-core python3Packages.openllm python3Packages.pendulum_3 python3Packages.prophet sudachidict-core sudachidict-full sudachidict-small electron-source electron-bin gendef opensnitch tailor-gui openobserve SP800-90B_EntropyAssessment mpremote

**Comment by ShamrockLee** [comment]
As for the *affected* packages, #294068 has shown more than 5000+ rebuild on Linux and `stdenv` rebuild on Darwin. `nixpkgs-review` shows 55040 packages on my `x86_64-linux` NixOS laptop. I can paste them here if need be.

**Comment by ShamrockLee** [comment]
It seems that OfBorg actually rebuilds the packages I specify, which is great  for testing purpose.

**Review by SuperSandro2000 — APPROVED** [review]

**Review by drupol — APPROVED** [review]

**Pull request merged**
