### PR TITLE
deltachat-desktop: 1.41.1 -> 1.41.2

### PR DESCRIPTION
**Pull request by totoroot**
## Description of changes

- Update package `deltachat-desktop` from version 1.41.1 to 1.41.2.

Ping @dotlambda  

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by dotlambda — CHANGES_REQUESTED** [review]
Update libdeltachat to the appropriate version.

**Comment by totoroot** [comment]
> Update libdeltachat to the appropriate version.

Done!

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 267870` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages failed to build:</summary>
  <ul>
    <li>deltachat-cursed</li>
    <li>deltachat-cursed.dist</li>
    <li>kdeltachat</li>
    <li>python310Packages.deltachat</li>
    <li>python310Packages.deltachat.dist</li>
    <li>python311Packages.deltachat</li>
    <li>python311Packages.deltachat.dist</li>
  </ul>
</details>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>deltachat-desktop</li>
    <li>deltachat-repl</li>
    <li>libdeltachat</li>
  </ul>
</details>

**Review by dotlambda — CHANGES_REQUESTED** [review]
`python3.pkgs.deltachat` fails to build and a new version of deltachat-desktop is available.

**Comment by dotlambda** [comment]
I investigated the build failure of the Python bindings:
```
FileNotFoundError: [Errno 2] No such file or directory: b'/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-libdeltachat-1.121.0/include/deltachat.h'
```
This path is returned by https://github.com/deltachat/deltachat-core-rust/blob/40dea771cc4d97d48949a6ececd7ef2be238b3cf/deltachat-ffi/deltachat.h#L7291.
Since the same happens on master I'll try to bisect the failure.

**Pull request closed without merging**
