### PR TITLE
Refactor icu and init 74.2

### PR DESCRIPTION
**Pull request by afh**
ℹ️ This draft PR is my understanding of how the icu package could be improved in a similar vein as #289690.

### TODO
If this PR is headed in the right direction and people see value in pursuing this approach close the following PRs
- [x] #289782
- [x] #289783

## Description of changes

* Add `icu/default.nix` containing the icu version specific packages
* Remove `icu/[0-9]*.nix` 
* Use `hash` instead of `sha256` in `icu/base.nix`
* ❗Includes changes proposed in #289782 **icu73: use buildPackages.icu73 for nativeBuildRoot**
* Update `all-packages.nix` accordingly using `callPackages`

I'm uncertain whether the changes proposed here properly affect `buildPackages.icu[0-9]{2}` or whether more work is needed.
I'd appreciated if someone could chime in on this.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by 7c6f434c** [comment]
OK, speaking about checking for rebuilds: `nix-instantiate` producing the same derivation before and after means that there is no need to rebuild the derivation, or any of its dependants (also known as reverse-dependencies or rev-deps). Which is quite a bit cheaper to check than doing a rebuild.

Actual icu-originating rebuild would definitely go to staging, you are absolutely correct here. But expression refactoring should typically target zero rebuilds as a goal, and then have some kind of an answer why this goal is not achievable (if it is not achievable). Often any reasonable answer is good enough, though!

(Adding a not-yet-used version of ICU very similar to the previous ones counts separately, and it has low impact )

**Comment by afh** [comment]
Thanks for elaborating in this, @7c6f434c, seems I have a bit more reading to do 😅

Do you see value in switching the icu package to icu74 for 24.05?

**Comment by afh** [comment]
Also thanks for merging! 😃

**Comment by 7c6f434c** [comment]
In general, I ended up maintainer of ICU because too much stuff needs it… so I don't have strong opinions to be honest. 

Trying to switch to icu74 and pinning only what needs to be pinned sounds reasonable (also based on CVE track record and on the changelog, we don't want to stay behind and the upgrade has a chance of being smooth). That's obviously a staging-scale thing, and I am not sure how long it would take to test so much stuff…

**Comment by afh** [comment]
That sounds reasonable, @7c6f434c. Here goes nothin' #290509 🤞

**Comment by 7c6f434c** [comment]
… and conveniently it looks like calling the relevant people is happening even before we got around to it ourselves!

**Comment by kirillrdy** [comment]
I had to deal with some icu firefox issues myself before :-)

**Pull request merged**
