### PR TITLE
texmacs: update to 1.99.2

### PR DESCRIPTION
**Pull request by Profpatsch**

### CODE REVIEW

**Comment by jagajaga** [comment]
Please rename commit's name following our guide from `CONTRIBUTING.md`

**Comment by Profpatsch** [comment]
@jagajaga Done.

**Comment by jagajaga** [comment]
Please rebase against current master (due to Travis error).

**Comment by Profpatsch** [comment]
@jagajaga Done, I hope (if `git rebase --onto remote/master` works as I think).

**Pull request merged**
