### PR TITLE
xfce: 4.10 -> 4.12

### PR DESCRIPTION
**Pull request by domenkozar**
Tested in VM, it boots up :)

### CODE REVIEW

**Comment by iElectric** [comment]
cc @vcunat

**Comment by edolstra** [comment]
Does it use only GTK 2 or 3 (rather than both)? I see references to both `gtk` and `gtk3`...

**Comment by iElectric** [comment]
Only in `libxfce4ui`, but we can remove that

**Comment by vcunat** [comment]
From reading the announcement and other reports, some apps do support gtk3 (e.g. task manager, parole, mousepad). For simplicity, we might try to stick to a gtk2-only solution.

I guess parole might be the only part that can no longer work with gtk2, so it could have a separately-built version of libxfce4ui or something like that...

**Comment by iElectric** [comment]
Yeah, they've also dropped `xfce-mixer` because of gstreamer 1.0 api.

**Comment by iElectric** [comment]
Removed `gtk3` support, did anyone test this PR?

**Comment by vcunat** [comment]
I'm just now running on it (without the second commit), and I see no problems, although I don't use complete Xfce (not the window-manager, mixer, etc.).

**Comment by vcunat** [comment]
Perhaps this could be fixed:
```
(xfce4-session:942): xfce4-session-WARNING **: Failed to running discard command "/bin/true": Failed to execute child process "/bin/true" (No such file or directory)
```

Heh, "Failed to running" sounds wrong by itself :-)

**Comment by vcunat** [comment]
Pushed to master with a few changes of my own 208d1f2.

**Pull request closed without merging**
