### PR TITLE
Fix weasyprint on darwin (x86_64 and aarch64)

### PR DESCRIPTION
**Pull request by janvogt**
- add FONTCONFIG_FILE also for executable
- deactivate http_test due to permission denied in sandbox
- remove unused dependencies that caused build problems
- fix responses dependency by allowing local networking for tests

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by janvogt** [comment]
Hi @elohmeier and @fabaff, is there anything I can do to get this merged?

It was multiple days of work for me, since I am neither a nix nor a python expert. But I really needed weasyprint to work on mac. I made sure the changes fit the style present as good as I could. But I am happy to improve... I'd really like to stop using my own nixpkgs fork.

**Review by McSinyx — APPROVED** [review]
Can't speak for Darwin, but doesn't seem to cause any regression on GNU/Linux.  Please rebase on top of master and reword the first line of the commit message to something like `python3Packages.weasyprint: fix build on Darwin` for a better chance of being merged soon.

**Comment by smancill** [comment]
@janvogt please rebase master so I can run nixpkgs-review in Darwin.

**Comment by Mindavi** [comment]
Closed by https://github.com/NixOS/nixpkgs/pull/207348

**Pull request closed without merging**
