### PR TITLE
Fix isabelle on darwin

### PR DESCRIPTION
**Pull request by shlevy**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by veprbl** [comment]
Does this fix `gcc49`? On x86_64-darwin I get:
```
error: builder for '/nix/store/dnlpjry9kag02ypb4pbp05r3xdqh4ar5-gcc-4.9.4.drv' failed with exit code 2;
       last 10 log lines:
       > checking whether ln -s works... yes
       > checking for x86_64-apple-darwin-gcc... /private/tmp/nix-build-gcc-4.9.4.drv-1/build/./gcc/xgcc -B/private/tmp/nix-build-gcc-4.9.4.drv-1/build/./gcc/ -O2 -I/nix/store/lggc04r544prygg2grxkxn0lvk4n3p39-Libsystem-1238.60.2/include -B/nix/store/lggc04r544prygg2grxkxn0lvk4n3p39-Libsystem-1238.60.2/lib/ -idirafter /nix/store/lggc04r544prygg2grxkxn0lvk4n3p39-Libsystem-1238.60.2/include -idirafter /nix/store/sdn87rkfbw2lgbrlbdcps4napx41bsh4-gcc-11.2.0/lib/gcc/x86_64-apple-darwin/11.2.0/include-fixed -Wl,-rpath,/nix/store/rrbknqy201sja4llh2h96bx0k2ym1fc5-gcc-4.9.4/lib -Wl,-L/nix/store/lggc04r544prygg2grxkxn0lvk4n3p39-Libsystem-1238.60.2/lib -Wl,-rpath -Wl,/nix/store/lggc04r544prygg2grxkxn0lvk4n3p39-Libsystem-1238.60.2/lib -Wl,-L/nix/store/lggc04r544prygg2grxkxn0lvk4n3p39-Libsystem-1238.60.2/lib -Wl,-arch -Wl,x86_64
       > checking for suffix of object files... configure: error: in `/private/tmp/nix-build-gcc-4.9.4.drv-1/build/x86_64-apple-darwin/libgcc':
       > configure: error: cannot compute suffix of object files: cannot compile
       > See `config.log' for more details.
       > make[2]: *** [Makefile:13363: configure-stage1-target-libgcc] Error 1
       > make[2]: Leaving directory '/private/tmp/nix-build-gcc-4.9.4.drv-1/build'
       > make[1]: *** [Makefile:17844: stage1-bubble] Error 2
       > make[1]: Leaving directory '/private/tmp/nix-build-gcc-4.9.4.drv-1/build'
       > make: *** [Makefile:18149: bootstrap] Error 2
       For full logs, run 'nix log /nix/store/dnlpjry9kag02ypb4pbp05r3xdqh4ar5-gcc-4.9.4.drv'
```

**Comment by shlevy** [comment]
Hmm it worked on my test branch but I admit I didn't re-build it on top of master. Will check again.

**Comment by shlevy** [comment]
Works on top of 21321a6381fd8d3660fe1cdc0485fbb5978112ce. Will try to see if I can bisect the failure.

**Comment by shlevy** [comment]
Build works on master for me (2e80f552f5f5c0e9727e35304dbf498600f29412)

**Comment by veprbl** [comment]
On master I also get the same error and:
```
# nix-instantiate . -A gcc49.cc
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
/nix/store/dnlpjry9kag02ypb4pbp05r3xdqh4ar5-gcc-4.9.4.drv
```

**Comment by shlevy** [comment]
```
$ nix-store -r /nix/store/dnlpjry9kag02ypb4pbp05r3xdqh4ar5-gcc-4.9.4.drv
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
/nix/store/cfylkxnli0dk84kpndgxf40vqc8ya12a-gcc-4.9.4-info
/nix/store/m2vi2zbn4n4asy1xj2g1x9r1r0h05ayg-gcc-4.9.4-man
/nix/store/rrbknqy201sja4llh2h96bx0k2ym1fc5-gcc-4.9.4
```

**Comment by shlevy** [comment]
I'm running on an M1 via rosetta and `--system x86_64-darwin`, I hope not but possibly this is a factor?

**Comment by veprbl** [comment]
Turns out, it works without the sandbox. My guess is that it tries to run sw_vers.

**Pull request merged**
