### PR TITLE
obs-studio-plugins.obs-hyperion: fix build

### PR DESCRIPTION
**Pull request by Algram**
###### Description of changes

Missed the qtbase call during packaging. This fixes the plugin.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 190721` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>obs-studio-plugins.obs-hyperion</li>
  </ul>
</details>

**Comment by Algram** [comment]
Hm I don't really know how to fix it the, could you maybe try and have a look?  Locally it works like this:
image

I don't know how to properly make it work in the repo though.

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 190721` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>obs-studio-plugins.obs-hyperion</li>
  </ul>
</details>

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 190721` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>obs-studio-plugins.obs-hyperion</li>
  </ul>
</details>

**Comment by superherointj** [comment]
Try:
>     rev = version;

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 190721` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>obs-studio-plugins.obs-hyperion</li>
  </ul>
</details>

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 190721` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>obs-studio-plugins.obs-hyperion</li>
  </ul>
</details>

**Comment by Algram** [comment]
I think it will start working now once flatbuffers gets released with the fix here:
https://github.com/google/flatbuffers/issues/7499

It is fixed on master but not on their latest version.

**Comment by superherointj** [comment]
If necessary, add a patch.

**Comment by superherointj** [comment]
You can set the package to use master.

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 190721` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>obs-studio-plugins.obs-hyperion</li>
  </ul>
</details>

**Comment by Algram** [comment]
@superherointj  Any pointers on how to test that locally? I can test flatbuffers to master, but how to make my package use that then?

**Comment by superherointj** [comment]
Notice: I am lacking context on this.

You could bump flatbuffers (in general). No?

**Comment by Algram** [comment]
@superherointj  I could, but I would need to set it to master and not a specific version. Is that accepted in general? If yes, I can commit that. But even if I commit. How can I test it before merging?

**Comment by superherointj** [comment]
> @superherointj I could, but I would need to set it to master and not a specific version. Is that accepted in general? If yes, I can commit that. But even if I commit. How can I test it before merging?

Yes, just use version `unstable-YYYY-MM-DD` (commit date)

**Comment by superherointj** [comment]
Use `nixpkgs-review` to validate downstream breakage. Always use `nixpkgs-review` to test all your PRs and after every build. You should have been using it already.

**Comment by Algram** [comment]
Alright I will split it up into a separate PR.

**Comment by Algram** [comment]
Depends on: https://github.com/NixOS/nixpkgs/pull/190727

**Comment by superherointj** [comment]
Feel free to integrate and squash my changes here.

**Comment by Algram** [comment]
Will be fixed in this PR: https://github.com/NixOS/nixpkgs/pull/198198

**Pull request closed without merging**
