### PR TITLE
zabbix: 3.0.31 -> 3.0.32, 4.0.26 -> 4.0.29, 5.0.5 -> 5.0.9

### PR DESCRIPTION
**Pull request by aanderse**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 117304` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
7 packages built:
</summary>
<ul>
<li>zabbix.agent (zabbix50.agent)</li>
<li>zabbix.proxy-mysql (zabbix50.proxy-mysql)</li>
<li>zabbix.proxy-pgsql (zabbix50.proxy-pgsql)</li>
<li>zabbix.proxy-sqlite (zabbix50.proxy-sqlite)</li>
<li>zabbix.server (zabbix.server-pgsql ,zabbix50.server ,zabbix50.server-pgsql)</li>
<li>zabbix.server-mysql (zabbix50.server-mysql)</li>
<li>zabbix.web (zabbix50.web)</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
zabbix.agent:
<details>


warning: unclear-gpl
`gpl2` is a deprecated license, check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/servers/monitoring/zabbix/agent.nix:34:7:

```
   |
34 |       license = licenses.gpl2;
   |       ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 117304` at f1ce8b59 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built successfully:</summary>
  <ul>
    <li>zabbix.agent (zabbix50.agent)</li>
    <li>zabbix.proxy-mysql (zabbix50.proxy-mysql)</li>
    <li>zabbix.proxy-pgsql (zabbix50.proxy-pgsql)</li>
    <li>zabbix.proxy-sqlite (zabbix50.proxy-sqlite)</li>
    <li>zabbix.server (zabbix.server-pgsql ,zabbix50.server ,zabbix50.server-pgsql)</li>
    <li>zabbix.server-mysql (zabbix50.server-mysql)</li>
    <li>zabbix.web (zabbix50.web)</li>
  </ul>
</details>

**Comment by aanderse** [comment]
@GrahamcOfBorg build zabbix.agent2

**Comment by aanderse** [comment]
@GrahamcOfBorg eval

**Pull request merged**
