### PR TITLE
ghcHEAD: 8.11.20200505 -> 8.11.20200731

### PR DESCRIPTION
**Pull request by utdemir**
###### Motivation for this change

This PR updates ghcHEAD to the latest revision as of today (2020-07-31).

There is one major change, now instead of `integer-simple` and `integer-gmp`, we have a `ghc-bignum` package with different backends. So I added a new compiler set like `haskell.packages.native-bignum.ghcHEAD`.

Also, the next version will be called GHC 9.0, so instead of calling this `8.11` we might call it something like `9.0-dev`.

Let me know what you think.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cdepillabout** [comment]
@utdemir Could you rebase this on the `haskell-updates` branch?

Also, after rebasing, could you try to get ofborg to build some of these packages for you?  I'd like to see that it actually is building successfully.

Oh, and it looks like the `grahamcofborg-eval` check is failing.  It appears to be related to this PR?

**Comment by utdemir** [comment]
> @utdemir Could you rebase this on the `haskell-updates` branch?
> 
> Oh, and it looks like the `grahamcofborg-eval` check is failing. It appears to be related to this PR?

Done, and yes, it was related to this PR, I just fixed it; thanks!
 
> Also, after rebasing, could you try to get ofborg to build some of these packages for you? I'd like to see that it actually is building successfully.

I do not think ofborg trusts me enough to do that, and even so I am hesitating if I should make it compile two GHC's, might be a bit heavy. If you are happy to do that, you can use:

@grahamcofborg build haskell.compiler.ghcHEAD haskell.compiler.native-bignum.ghcHEAD

**Comment by utdemir** [comment]
It looks like ofborgs `aarch64-linux` build has failed `x86_64-linux` build has timed out. Even though I built both on my NixOS x86_64 system. I do not have an ARM system, so if anyone else can debug it, here's the error:

```
rts/Libdw.c:363:6: error: #error "Please implement set_initial_registers() for your arch"
  363 | #    error "Please implement set_initial_registers() for your arch"
      |      ^~~~~
rts/ghc.mk:585: rts/dist/build/.depend-v-p-dyn-l-debug-thr-thr_debug-thr_l-thr_p-debug_dyn-thr_dyn-thr_debug_dyn-l_dyn-thr_l_dyn-thr_debug_p-debug_p.c_asm: No such file or directory
```

**Review by cdepillabout — APPROVED** [review]
This looks good to me.  Thanks for fixing this up @utdemir.

It would be great if @ggreif could do a quick review of this, since he is often responsible for updating these GHC derivations here in nixpkgs.

If he signs off on this, I'm happy to merge it in.

@utdemir If he doesn't respond in a few days, feel free to ping me and I will merge it in anyway.

--------------------------------------

As for the arm build, it is unfortunate they don't "just work", but without an arm machine it is hard to debug it.  I don't think too many people actually use this ghcHEAD package set, so I'm fine with just going ahead and merging this in.

**Comment by ggreif** [comment]
Just for comparison

@GrahamcOfBorg build haskell.compiler.integer-simple.ghc884 haskell.compiler.integer-simple.ghc8101

**Comment by ggreif** [comment]
@cdepillabout this looks totally reasonable to me.

It appears that the non-imp build are wonky on aarch64 too:
```
configuring
/nix/store/iccnwksp0hfffsv3x7qcf73f043b4znq-stdenv-linux/setup: line 106: GhcLibWays: command not found
error: --- Error --- nix-daemon
```
Maybe @domenkozar can comment.

**Comment by domenkozar** [comment]
@ggreif assuming you tried 8.8.4 or 8.10.1 I've just pushed a fix 1353355a636d6bb2cff5d554a0c6e40861751182

Thanks for the report!

**Pull request merged**
