### PR TITLE
avidemux: fix evaluation

### PR DESCRIPTION
**Pull request by jagajaga**

### CODE REVIEW

**Comment by exi** [comment]
this branch failes for some weird nox issues, ill check it out and test it and report back in a few minutes.

**Comment by exi** [comment]
@jagajaga i get a lot of these when starting the compiled binary:
```
[ADM_mx_plugin] Scanning directory /nix/store/zdwsih66r2pcid1kfqkrgcj6x4ysask7-avidemux-2.6.9/lib64/ADM_plugins6/muxers/
[ADM_av_plugin] Cannot parse plugin
[ADM_ad_plugin] Scanning directory /nix/store/zdwsih66r2pcid1kfqkrgcj6x4ysask7-avidemux-2.6.9/lib64/ADM_plugins6/audioDecoder/
[ADM_ad_plugin] Cannot parse plugin
[ADM_av_plugin] Scanning directory /nix/store/zdwsih66r2pcid1kfqkrgcj6x4ysask7-avidemux-2.6.9/lib64/ADM_plugins6/audioDevices/
[ADM_av_plugin] Cannot parse plugin
[ADM_ae_plugin] Scanning directory /nix/store/zdwsih66r2pcid1kfqkrgcj6x4ysask7-avidemux-2.6.9/lib64/ADM_plugins6/audioEncoders/
[ADM_ae_plugin] Cannot parse plugin
[ADM_dm_plugin] Scanning directory /nix/store/zdwsih66r2pcid1kfqkrgcj6x4ysask7-avidemux-2.6.9/lib64/ADM_plugins6/demuxers/
[ADM_av_plugin] Cannot parse plugin
Unable to load [copyADM]: copyADM: cannot open shared object file: No such file or directory
[videoEncoder6]Symbol loading failed for copyADM
[ADM_ve6_plugin] Scanning directory /nix/store/zdwsih66r2pcid1kfqkrgcj6x4ysask7-avidemux-2.6.9/lib64/ADM_plugins6/videoEncoders/
[ADM_ve6_plugin] Cannot parse plugin
[ADM_ve6_plugin] Scanning directory /nix/store/zdwsih66r2pcid1kfqkrgcj6x4ysask7-avidemux-2.6.9/lib64/ADM_plugins6/videoEncoders//qt4
[ADM_ve6_plugin] Cannot parse plugin
[ADM_vf_plugin] Scanning directory /nix/store/zdwsih66r2pcid1kfqkrgcj6x4ysask7-avidemux-2.6.9/lib64/ADM_plugins6/videoFilters/
[ADM_vf_plugin] Cannot parse plugin
[ADM_vf_plugin] Cannot parse plugin
[ADM_vd6_plugin] Scanning directory /nix/store/zdwsih66r2pcid1kfqkrgcj6x4ysask7-avidemux-2.6.9/lib64/ADM_plugins6/videoDecoders/
[ADM_vd6_plugin] Cannot parse plugin
[ADM_ad_plugin] Scanning directory /home/exi/.avidemux6/plugins6/audioDecoder/
[ADM_ad_plugin] Cannot parse plugin
[ADM_vf_plugin] Scanning directory /home/exi/.avidemux6/plugins6/videoFilter/
[ADM_vf_plugin] Cannot parse plugin
[ADM_vf_plugin] Cannot parse plugin
```

I cannot open any video files with the compiled avidemux, it just says "Cannot find an demuxer for <filename>"

**Comment by exi** [comment]
After looking at it again, i think this build would be much easier if we split it into 4-5 separate builds (for qt/gtk/core/cli/plugins) with defined dependencies on each other like the avidemux modularization suggests.
We could use the "bootstrap.bash" as a template and recreate it as a nix expression.
That would give the user more choices and hopefully would support a kind of "genericBuild" support.

**Comment by jagajaga** [comment]
Indeed I don't have enough time to fix that. So I revert https://github.com/NixOS/nixpkgs/commit/a40b413b04287e3556c5007a42cf80b3761ab556 and close this PR.

**Pull request closed without merging**
