### PR TITLE
locate: extend module

### PR DESCRIPTION
**Pull request by gkleen**
###### Motivation for this change
Support for `mlocate` looked significantly more complete than it turned out to be

###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

I couldn't find a way to properly handle `includeStore` in `rename.nix` so I´m just echoing a warning for now. I think a reasonable approach would be to remove `/nix/store` from `prunePaths` when `includeStore` is set (and print a warning). I could not, however, find a way to do so without running into infinite recursion – any ideas?

### CODE REVIEW

**Comment by pngwjpgh** [comment]
_Bump_

@copumpkin, @edolstra, @andjscott Care to comment?

**Comment by Mic92** [comment]
@pngwjpgh tested and works for me. Can you rebase your changes against master again?
`

**Comment by pngwjpgh** [comment]
@Mic92 done

**Comment by Mic92** [comment]
Thanks!

**Pull request merged**
