### PR TITLE
ocamlPackages.ocsigen_server: 2.11.0 → 2.15.0; ocamlPackages.ssl: 0.5.5 → 0.5.9

### PR DESCRIPTION
**Pull request by vbgl**
###### Motivation for this change

Compatibility with OCaml 4.08.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @maggesi (ssl) @FlorentBecker (ocsigen_server)

### CODE REVIEW

**Comment by vbgl** [comment]
@GrahamcOfBorg build trv opa

**Comment by vbgl** [comment]
The `trv` failure on darwin seems to be a regression.

**Comment by vbgl** [comment]
@GrahamcOfBorg build ocamlPackages.cohttp-lwt-unix

**Comment by risicle** [comment]
Yes, on macos 10.13 I get a failure:

```
builder for '/nix/store/qp0k5ncjm3gy1f0cggw2iwk4x2yra6h9-ocaml-cohttp-0.19.3.drv' failed with exit code 2; last 10 log lines:
    "_X509_get_subject_name", referenced from:
        _client_verify_callback in libssl_stubs.a(ssl_stubs.o)
        _ocaml_ssl_get_subject in libssl_stubs.a(ssl_stubs.o)
  ld: symbol(s) not found for architecture x86_64
  clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
  File "caml_startup", line 1:
  Error: Error during linking
  Command exited with code 2.
  E: Failure("Command ''/nix/store/sqr051rii5hmjsqwakqcfs6msyn30297-ocaml-4.02.3/bin/ocamlbuild' lib/cohttp.cma lib/cohttp.cmxa lib/cohttp.a lib/cohttp.cmxs top/cohttp_top.cma top/cohttp_top.cmxa top/cohttp_top.a top/cohttp_top.cmxs lwt-core/cohttp_lwt.cma lwt-core/cohttp_lwt.cmxa lwt-core/cohttp_lwt.a lwt-core/cohttp_lwt.cmxs lwt/cohttp_lwt_unix.cma lwt/cohttp_lwt_unix.cmxa lwt/cohttp_lwt_unix.a lwt/cohttp_lwt_unix.cmxs async/cohttp_async.cma async/cohttp_async.cmxa async/cohttp_async.a async/cohttp_async.cmxs bin/cohttp_server_async.native bin/cohttp_curl_async.native bin/cohttp_server_lwt.native bin/cohttp_proxy_lwt.native bin/cohttp_curl_lwt.native examples/async/hello_world.native examples/async/receive_post.native examples/doc/client_lwt.native examples/doc/server_lwt.native -tag debug -classic-display' terminated with error code 10")
  make: *** [Makefile:20: build] Error 1
```

**Comment by vbgl** [comment]
Thanks for testing. Would you have a hint on how to fix such linking issue?

**Comment by vbgl** [comment]
@GrahamcOfBorg build ocamlPackages.cohttp-lwt-unix trv opa

**Review by maggesi — APPROVED** [review]
Builds on macOS.
Diff looks good.

**Pull request merged**
