### PR TITLE
openjdk8: swtich darwin to adoptopenjdk8 at jdk8u212-b04

### PR DESCRIPTION
**Pull request by gleber**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by risicle** [comment]
Build of `adoptopenjdk-openj9-bin-8` fails for me on macos 10.13:

```
building '/nix/store/56a2zn6v30vyknpp4f6afnrv921309dn-OpenJDK8U-jdk_x64_mac_openj9_8u212b04_openj9-0.14.2.tar.gz.drv'...

trying https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u212-b04_openj9-0.14.2/OpenJDK8U-jdk_x64_mac_openj9_8u212b04_openj9-0.14.2.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   649    0   649    0     0   1690      0 --:--:-- --:--:-- --:--:--  1694
100  108M  100  108M    0     0   582k      0  0:03:10  0:03:10 --:--:-- 1161k
building '/nix/store/pfh4bljwpjq08wiy7cc90db04wsw9mmz-adoptopenjdk-openj9-bin-8.0.212.drv'...
unpacking sources
unpacking source archive /nix/store/6hjjbvw9lyh8b8s6vbk82q94nds03ywf-OpenJDK8U-jdk_x64_mac_openj9_8u212b04_openj9-0.14.2.tar.gz
source root is jdk8u212-b04
setting SOURCE_DATE_EPOCH to timestamp 1558507151 of file jdk8u212-b04/Contents/Home/jre/lib/server/libjvm.dylib
patching sources
configuring
no configure script, doing nothing
building
no Makefile, doing nothing
installing
ln: failed to create symbolic link '/nix/store/1dicsm5jvgwsvjyw6j337ldhckkgnwzp-adoptopenjdk-openj9-bin-8.0.212/jre': File exists
builder for '/nix/store/pfh4bljwpjq08wiy7cc90db04wsw9mmz-adoptopenjdk-openj9-bin-8.0.212.drv' failed with exit code 1
```

**Comment by risicle** [comment]
In fact more or less the same thing happens for `adoptopenjdk-bin-8`, along with a lot of downstream broken packages.

**Comment by denisgarci** [comment]
@risicle I'm having the same issue. Did you manage to fix it?

**Comment by risicle** [comment]
Sorry, no - I don't have access to a darwin machine full-time.

**Comment by Ekleog** [comment]
@gleber Do you still plan on working on this some day, or should this PR be closed? :)

**Comment by gleber** [comment]
Ah, not really. Closing.

**Pull request closed without merging**
