### PR TITLE
trezord: 2.0.24 -> 2.0.25

### PR DESCRIPTION
**Pull request by 1000101**
###### Motivation for this change
Upgrade of the package.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by c0bw3b** [comment]
Changelog:
https://github.com/trezor/trezord-go/blob/master/CHANGELOG.md#2025---unreleased

**Comment by 1000101** [comment]
> Changelog:
> https://github.com/trezor/trezord-go/blob/master/CHANGELOG.md#2025---unreleased

Sorry, the repo maintainer made a mistake, you can check the 2.0.25 is the latest available version for download here: http://wallet.trezor.io/

**Comment by c0bw3b** [comment]
But is the changelog accurate, still?
It gives context as to what the update brings, if it brings some kind of security-related fix (not the case here) etc...
I was looking for it to get more context and justify the backport (your other PR)

**Comment by c0bw3b** [comment]
Ok, thanks for explaining.

**Comment by worldofpeace** [comment]
@GrahamcOfBorg build trezord

**Pull request merged**
