### PR TITLE
upgrade msbuild and fix omnisharp-roslyn

### LINKED ISSUE #126477: omnisharp-roslyn cannot find Microsoft.Common.props
**Describe the bug**
When running `omnisharp` I get an error that project loading failed due to a missing file:
```
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.MSBuild.ProjectManager","Message":"Loading project: /home/felschr/dev/work/project/Api/Api.csproj"},"Seq":147,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"WARNING","Name":"OmniSharp.MSBuild.ProjectManager","Message":"Failed to load project file '/home/felschr/dev/work/project/Api/Api.csproj'."},"Seq":148,"Type":"event"}
{"Event":"Error","Body":{"Text":"Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project \"/nix/store/pw1ic8h00a9k2c5j1786ivq7zqrc59cb-omnisharp-roslyn-1.37.8/src/.msbuild/Current/Microsoft.Common.props\" was not found. Confirm that the expression in the Import declaration \"/nix/store/pw1ic8h00a9k2c5j1786ivq7zqrc59cb-omnisharp-roslyn-1.37.8/src/.msbuild/Current/Microsoft.Common.props\" is correct, and that the file exists on disk.  /nix/store/ycw6rph7kyff988mqk56qyf5q7qwidqc-dotnet-core-combined/sdk/5.0.202/Sdks/Microsoft.NET.Sdk/Sdk/Sdk.props\n  at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject (System.String errorSubCategoryResourceName, Microsoft.Build.Shared.IElementLocation elementLocation, System.String resourceName, System.Object[] args) [0x00040] in <9be4d26643704d2e91efa63e9f29e6b0>:0 \n  at Microsoft.Build.Shared.ProjectErrorUtilities.VerifyThrowInvalidProject[T1,T2] (System.Boolean condition, System.String errorSubCategoryResourceName, Microsoft.Build.Shared.IElementLocation elementLocation, System.String resourceName, T1 arg0, T2 arg1) [0x00003] in <9be4d26643704d2e91efa63e9f29e6b0>:0
```

The path `/nix/store/pw1ic8h00a9k2c5j1786ivq7zqrc59cb-omnisharp-roslyn-1.37.8/src/.msbuild/Current/Microsoft.Common.props` does not seem to exist on my system.
There is only one folder in `/nix/store/pw1ic8h00a9k2c5j1786ivq7zqrc59cb-omnisharp-roslyn-1.37.8/src/.msbuild/Current`, which is called `Bin`.

**Expected behavior**
`omnisharp` should not throw an error and work as expected.

**Additional context**
`omnisharp.json`:
```json
{
  "MsBuild": {
    "UseLegacySdkResolver": true,
    "EnablePackageAutoRestore": true
  },
  "FormattingOptions": {
    "EnableEditorConfigSupport": true
  },
  "RoslynExtensionsOptions": {
    "EnableAnalyzersSupport": true
  }
}
```

Additionally, I've set the environment variables `DOTNET_ROOT`, `MSBuildSdksPath` & `MSBUILD_EXE_PATH` to the respective paths of my dotnet installation.

**Notify maintainers**
@tesq0 @ericdallo @corngood

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.7, NixOS, 21.11.20210606.fbfb794 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - channels(root): `"nixos-21.11pre291991.ea7d4aa9b82"`
 - channels(felschr): `"nixpkgs-unstable-21.11pre291991.ea7d4aa9b82"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: omnisharp-roslyn
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by corngood**
Should fix #126477

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 132165` at 415bef17 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/5199ffee7ea2f55f5d1f09604b2fc4c9">msbuild</a></li>
    <li><a href="https://gist.github.com/0b03c1538b2f0fe7f851e324da425623">omnisharp-roslyn</a></li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/development/tools/omnisharp-roslyn/default.nix:94:3:
```
   |
94 |   installPhase = ''
   |   ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by felschr** [comment]
I've updated my test project to use the changes of this PR: https://github.com/felschr/omnisharp-nix-issue
I was also able to remove quite a bit of omnisharp & dotnet configuration that was apparently unnecessary.
omnisharp is finally working for me, at least on this project. I'm gonna try using it on a more complex project next week and report back.

**Comment by hpfr** [comment]
Thanks, this also fixed an issue I had using omnisharp for emacs-lsp where omnisharp would find the embedded msbuild 16.8 but then claim it needed at least msbuild 16.8, which was strange. Looking forward to the merge!

**Comment by hpfr** [comment]
I guess @jirkadanek for msbuild, although they don't look active. Maybe msbuild needs another maintainer as well?

**Comment by corngood** [comment]
I thought about adding myself as maintainer.  I'm still working on some cleanup of the nuget dependencies.  I'd love it if all of that was dealt with in a consistent manner across nixpkgs, but `msbuild` has so many quirks around bootstrapping that it's quite a pain in the ass.  I'd like to at least make `create-deps.sh` easier to use.

**Comment by jiridanek** [comment]
I'm now known as @jiridanek (was @jirkadanek), but yes, I haven't touched nixpkgs in a long while now. And msbuild is quite difficult build to get back up to speed for me on. For personal use, I've given up on nixpkgs-packaged dotnet (and IntelliJ IDEs) and I am instead running the binary downloads...

I had big plans around msbuild nixpkgs, but I somehow moved to other things; It would be still interesting to get back, but... so would be 100+1 other possible things...

**Review by Artturin — APPROVED** [review]
not tested (other than running the binary) but they built and its better than the status quo

**Pull request merged**
