### PR TITLE
nixos/onlyoffice: don't drop database on start

### PR DESCRIPTION
**Pull request by lheckemann**
If nextcloud is down, or the changes can otherwise not be saved back to nextcloud (e.g. because of [1]), the onlyoffice database contains _all the user data_ and should absolutely not be dropped on startup!

[1]: https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/931

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
I think I copied that from the docker container script. I am not sure why and never questioned this.

Also would you be interested in helping to maintain this? I think you where also in the thread recently together with @codingmarcel and I am really needing some help here.

**Comment by MarcelCoding** [comment]
As far as I can tell. It should be absolutely safe to keep the database. I've restored the database already multiple times because of data loss and it worked without issues all the time.

**Comment by SuperSandro2000** [comment]
I want to follow upstream here because sadly everything else is a lost cause for onlyoffice and since their source code is not great to work with, we can't work around this. At this point we can't even compile the software from source...

**Comment by MarcelCoding** [comment]
I've created an upstream issue: https://github.com/ONLYOFFICE/DocumentServer/issues/2787

**Comment by MarcelCoding** [comment]
I've just talked with other people about onlyoffice and data recovery. Normally you can just recover documents from the file cache, therefore the database is always deleted and onlyoffice does not need to do database migrations. The issue I had was that x2t not worked correctly, so the documents could not be written to the file cache.

**Pull request closed without merging**
