### PR TITLE
nodePackages: update to latest

### PR DESCRIPTION
**Pull request by aqrln**
###### Description of changes

```
$ pkgs/development/node-packages/generate.sh
```

I needed a newer version of pnpm, so decided to update all Node.js packages.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aqrln** [comment]
Result of `nixpkgs-review pr 244007` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>41 packages marked as broken and skipped:</summary>
  <ul>
    <li>code-server</li>
    <li>coder</li>
    <li>discourse</li>
    <li>discourseAllPlugins</li>
    <li>mx-puppet-discord</li>
    <li>odoo</li>
    <li>odoo.dist</li>
    <li>python310Packages.batchspawner</li>
    <li>python310Packages.batchspawner.dist</li>
    <li>python310Packages.dockerspawner</li>
    <li>python310Packages.dockerspawner.dist</li>
    <li>python310Packages.jupyterhub</li>
    <li>python310Packages.jupyterhub-ldapauthenticator</li>
    <li>python310Packages.jupyterhub-ldapauthenticator.dist</li>
    <li>python310Packages.jupyterhub-systemdspawner</li>
    <li>python310Packages.jupyterhub-systemdspawner.dist</li>
    <li>python310Packages.jupyterhub-tmpauthenticator</li>
    <li>python310Packages.jupyterhub-tmpauthenticator.dist</li>
    <li>python310Packages.jupyterhub.dist</li>
    <li>python310Packages.nbdev</li>
    <li>python310Packages.nbdev.dist</li>
    <li>python310Packages.oauthenticator</li>
    <li>python310Packages.oauthenticator.dist</li>
    <li>python311Packages.batchspawner</li>
    <li>python311Packages.batchspawner.dist</li>
    <li>python311Packages.dockerspawner</li>
    <li>python311Packages.dockerspawner.dist</li>
    <li>python311Packages.jupyterhub</li>
    <li>python311Packages.jupyterhub-ldapauthenticator</li>
    <li>python311Packages.jupyterhub-ldapauthenticator.dist</li>
    <li>python311Packages.jupyterhub-systemdspawner</li>
    <li>python311Packages.jupyterhub-systemdspawner.dist</li>
    <li>python311Packages.jupyterhub-tmpauthenticator</li>
    <li>python311Packages.jupyterhub-tmpauthenticator.dist</li>
    <li>python311Packages.jupyterhub.dist</li>
    <li>python311Packages.nbdev</li>
    <li>python311Packages.nbdev.dist</li>
    <li>python311Packages.oauthenticator</li>
    <li>python311Packages.oauthenticator.dist</li>
    <li>teleprompter</li>
    <li>whalebird</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>graphite-cli</li>
  </ul>
</details>
<details>
  <summary>61 packages built:</summary>
  <ul>
    <li>balanceofsatoshis</li>
    <li>bitwarden-cli</li>
    <li>castnow</li>
    <li>commitlint</li>
    <li>create-cycle-app</li>
    <li>emacsPackages.lsp-bridge</li>
    <li>emanote</li>
    <li>emanote.data</li>
    <li>fast-cli</li>
    <li>flood</li>
    <li>gtop</li>
    <li>haskellPackages.emanote</li>
    <li>haskellPackages.emanote.data</li>
    <li>haskellPackages.emanote.doc</li>
    <li>haskellPackages.tailwind</li>
    <li>haskellPackages.tailwind.doc</li>
    <li>jellyseerr</li>
    <li>joplin</li>
    <li>lessc</li>
    <li>lighthouse</li>
    <li>lv_img_conv</li>
    <li>n8n</li>
    <li>node2nix</li>
    <li>nodehun</li>
    <li>openmoji-black</li>
    <li>openmoji-color</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>pot</li>
    <li>pscid</li>
    <li>pulsar</li>
    <li>pyright</li>
    <li>redoc-cli</li>
    <li>reveal-md</li>
    <li>styx</li>
    <li>styx.lib</li>
    <li>styx.themes</li>
    <li>theLoungePlugins.plugins.closepms</li>
    <li>theLoungePlugins.plugins.giphy</li>
    <li>theLoungePlugins.themes.flat-blue</li>
    <li>theLoungePlugins.themes.flat-dark</li>
    <li>uppy-companion</li>
    <li>vimPlugins.coc-clangd</li>
    <li>vimPlugins.coc-markdownlint</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-sh</li>
    <li>vimPlugins.coc-spell-checker</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-tslint</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vimPlugins.markdown-preview-nvim</li>
    <li>vscode</li>
    <li>vscode-extensions.rust-lang.rust-analyzer</li>
    <li>vscode-fhs</li>
    <li>vscode-langservers-extracted</li>
    <li>vscode-with-extensions</li>
    <li>vscodium</li>
    <li>vscodium-fhs</li>
    <li>wasm-text-gen</li>
    <li>wrangler</li>
  </ul>
</details>

**Comment by aqrln** [comment]
Testing with `nixpkgs-review`, building `graphite-cli` fails on aarch64-linux because there are no pre-built binaries for the native addon in `node-canvas` and building it from sources fails with
```
nix/store/7i6cwyqk037k95xa2c1cvd1dx1zchkkx-bash-5.2-p15/bin/sh: line 1: pkg-config: command not found
```

Result of `nixpkgs-review pr 244007` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>41 packages marked as broken and skipped:</summary>
  <ul>
    <li>code-server</li>
    <li>coder</li>
    <li>discourse</li>
    <li>discourseAllPlugins</li>
    <li>mx-puppet-discord</li>
    <li>odoo</li>
    <li>odoo.dist</li>
    <li>python310Packages.batchspawner</li>
    <li>python310Packages.batchspawner.dist</li>
    <li>python310Packages.dockerspawner</li>
    <li>python310Packages.dockerspawner.dist</li>
    <li>python310Packages.jupyterhub</li>
    <li>python310Packages.jupyterhub-ldapauthenticator</li>
    <li>python310Packages.jupyterhub-ldapauthenticator.dist</li>
    <li>python310Packages.jupyterhub-systemdspawner</li>
    <li>python310Packages.jupyterhub-systemdspawner.dist</li>
    <li>python310Packages.jupyterhub-tmpauthenticator</li>
    <li>python310Packages.jupyterhub-tmpauthenticator.dist</li>
    <li>python310Packages.jupyterhub.dist</li>
    <li>python310Packages.nbdev</li>
    <li>python310Packages.nbdev.dist</li>
    <li>python310Packages.oauthenticator</li>
    <li>python310Packages.oauthenticator.dist</li>
    <li>python311Packages.batchspawner</li>
    <li>python311Packages.batchspawner.dist</li>
    <li>python311Packages.dockerspawner</li>
    <li>python311Packages.dockerspawner.dist</li>
    <li>python311Packages.jupyterhub</li>
    <li>python311Packages.jupyterhub-ldapauthenticator</li>
    <li>python311Packages.jupyterhub-ldapauthenticator.dist</li>
    <li>python311Packages.jupyterhub-systemdspawner</li>
    <li>python311Packages.jupyterhub-systemdspawner.dist</li>
    <li>python311Packages.jupyterhub-tmpauthenticator</li>
    <li>python311Packages.jupyterhub-tmpauthenticator.dist</li>
    <li>python311Packages.jupyterhub.dist</li>
    <li>python311Packages.nbdev</li>
    <li>python311Packages.nbdev.dist</li>
    <li>python311Packages.oauthenticator</li>
    <li>python311Packages.oauthenticator.dist</li>
    <li>teleprompter</li>
    <li>whalebird</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>graphite-cli</li>
  </ul>
</details>
<details>
  <summary>61 packages built:</summary>
  <ul>
    <li>balanceofsatoshis</li>
    <li>bitwarden-cli</li>
    <li>castnow</li>
    <li>commitlint</li>
    <li>create-cycle-app</li>
    <li>emacsPackages.lsp-bridge</li>
    <li>emanote</li>
    <li>emanote.data</li>
    <li>fast-cli</li>
    <li>flood</li>
    <li>gtop</li>
    <li>haskellPackages.emanote</li>
    <li>haskellPackages.emanote.data</li>
    <li>haskellPackages.emanote.doc</li>
    <li>haskellPackages.tailwind</li>
    <li>haskellPackages.tailwind.doc</li>
    <li>jellyseerr</li>
    <li>joplin</li>
    <li>lessc</li>
    <li>lighthouse</li>
    <li>lv_img_conv</li>
    <li>n8n</li>
    <li>node2nix</li>
    <li>nodehun</li>
    <li>openmoji-black</li>
    <li>openmoji-color</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>pot</li>
    <li>pscid</li>
    <li>pulsar</li>
    <li>pyright</li>
    <li>redoc-cli</li>
    <li>reveal-md</li>
    <li>styx</li>
    <li>styx.lib</li>
    <li>styx.themes</li>
    <li>theLoungePlugins.plugins.closepms</li>
    <li>theLoungePlugins.plugins.giphy</li>
    <li>theLoungePlugins.themes.flat-blue</li>
    <li>theLoungePlugins.themes.flat-dark</li>
    <li>uppy-companion</li>
    <li>vimPlugins.coc-clangd</li>
    <li>vimPlugins.coc-markdownlint</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-sh</li>
    <li>vimPlugins.coc-spell-checker</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-tslint</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vimPlugins.markdown-preview-nvim</li>
    <li>vscode</li>
    <li>vscode-extensions.rust-lang.rust-analyzer</li>
    <li>vscode-fhs</li>
    <li>vscode-langservers-extracted</li>
    <li>vscode-with-extensions</li>
    <li>vscodium</li>
    <li>vscodium-fhs</li>
    <li>wasm-text-gen</li>
    <li>wrangler</li>
  </ul>
</details>

**Comment by aqrln** [comment]
Result of `nixpkgs-review pr 244007` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>37 packages marked as broken and skipped:</summary>
  <ul>
    <li>code-server</li>
    <li>coder</li>
    <li>discourse</li>
    <li>discourseAllPlugins</li>
    <li>mx-puppet-discord</li>
    <li>odoo</li>
    <li>odoo.dist</li>
    <li>python310Packages.batchspawner</li>
    <li>python310Packages.batchspawner.dist</li>
    <li>python310Packages.dockerspawner</li>
    <li>python310Packages.dockerspawner.dist</li>
    <li>python310Packages.jupyterhub</li>
    <li>python310Packages.jupyterhub-ldapauthenticator</li>
    <li>python310Packages.jupyterhub-ldapauthenticator.dist</li>
    <li>python310Packages.jupyterhub-systemdspawner</li>
    <li>python310Packages.jupyterhub-systemdspawner.dist</li>
    <li>python310Packages.jupyterhub-tmpauthenticator</li>
    <li>python310Packages.jupyterhub-tmpauthenticator.dist</li>
    <li>python310Packages.jupyterhub.dist</li>
    <li>python310Packages.oauthenticator</li>
    <li>python310Packages.oauthenticator.dist</li>
    <li>python311Packages.batchspawner</li>
    <li>python311Packages.batchspawner.dist</li>
    <li>python311Packages.dockerspawner</li>
    <li>python311Packages.dockerspawner.dist</li>
    <li>python311Packages.jupyterhub</li>
    <li>python311Packages.jupyterhub-ldapauthenticator</li>
    <li>python311Packages.jupyterhub-ldapauthenticator.dist</li>
    <li>python311Packages.jupyterhub-systemdspawner</li>
    <li>python311Packages.jupyterhub-systemdspawner.dist</li>
    <li>python311Packages.jupyterhub-tmpauthenticator</li>
    <li>python311Packages.jupyterhub-tmpauthenticator.dist</li>
    <li>python311Packages.jupyterhub.dist</li>
    <li>python311Packages.oauthenticator</li>
    <li>python311Packages.oauthenticator.dist</li>
    <li>teleprompter</li>
    <li>whalebird</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>graphite-cli</li>
  </ul>
</details>
<details>
  <summary>73 packages built:</summary>
  <ul>
    <li>balanceofsatoshis</li>
    <li>bitwarden-cli</li>
    <li>breitbandmessung</li>
    <li>castnow</li>
    <li>commitlint</li>
    <li>create-cycle-app</li>
    <li>emacsPackages.lsp-bridge</li>
    <li>emanote</li>
    <li>emanote.data</li>
    <li>fast-cli</li>
    <li>flexoptix-app</li>
    <li>flood</li>
    <li>gtop</li>
    <li>haskellPackages.emanote</li>
    <li>haskellPackages.emanote.data</li>
    <li>haskellPackages.emanote.doc</li>
    <li>haskellPackages.tailwind</li>
    <li>haskellPackages.tailwind.doc</li>
    <li>jellyseerr</li>
    <li>joplin</li>
    <li>lessc</li>
    <li>lighthouse</li>
    <li>lv_img_conv</li>
    <li>morgen</li>
    <li>n8n</li>
    <li>node2nix</li>
    <li>nodehun</li>
    <li>openmoji-black</li>
    <li>openmoji-color</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>pot</li>
    <li>pscid</li>
    <li>pulsar</li>
    <li>pyright</li>
    <li>python310Packages.nbdev</li>
    <li>python310Packages.nbdev.dist</li>
    <li>python311Packages.nbdev</li>
    <li>python311Packages.nbdev.dist</li>
    <li>quarto</li>
    <li>quartoMinimal</li>
    <li>redoc-cli</li>
    <li>reveal-md</li>
    <li>slack</li>
    <li>styx</li>
    <li>styx.lib</li>
    <li>styx.themes</li>
    <li>teams</li>
    <li>theLoungePlugins.plugins.closepms</li>
    <li>theLoungePlugins.plugins.giphy</li>
    <li>theLoungePlugins.themes.flat-blue</li>
    <li>theLoungePlugins.themes.flat-dark</li>
    <li>uppy-companion</li>
    <li>vimPlugins.coc-clangd</li>
    <li>vimPlugins.coc-markdownlint</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-sh</li>
    <li>vimPlugins.coc-spell-checker</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-tslint</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vimPlugins.markdown-preview-nvim</li>
    <li>vscode</li>
    <li>vscode-extensions.ms-python.vscode-pylance</li>
    <li>vscode-extensions.rust-lang.rust-analyzer</li>
    <li>vscode-fhs</li>
    <li>vscode-langservers-extracted</li>
    <li>vscode-with-extensions</li>
    <li>vscodium</li>
    <li>vscodium-fhs</li>
    <li>wasm-text-gen</li>
    <li>wrangler</li>
  </ul>
</details>

**Comment by aqrln** [comment]
Result of `nixpkgs-review pr 244007` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>37 packages marked as broken and skipped:</summary>
  <ul>
    <li>code-server</li>
    <li>coder</li>
    <li>discourse</li>
    <li>discourseAllPlugins</li>
    <li>mx-puppet-discord</li>
    <li>odoo</li>
    <li>odoo.dist</li>
    <li>python310Packages.batchspawner</li>
    <li>python310Packages.batchspawner.dist</li>
    <li>python310Packages.dockerspawner</li>
    <li>python310Packages.dockerspawner.dist</li>
    <li>python310Packages.jupyterhub</li>
    <li>python310Packages.jupyterhub-ldapauthenticator</li>
    <li>python310Packages.jupyterhub-ldapauthenticator.dist</li>
    <li>python310Packages.jupyterhub-systemdspawner</li>
    <li>python310Packages.jupyterhub-systemdspawner.dist</li>
    <li>python310Packages.jupyterhub-tmpauthenticator</li>
    <li>python310Packages.jupyterhub-tmpauthenticator.dist</li>
    <li>python310Packages.jupyterhub.dist</li>
    <li>python310Packages.oauthenticator</li>
    <li>python310Packages.oauthenticator.dist</li>
    <li>python311Packages.batchspawner</li>
    <li>python311Packages.batchspawner.dist</li>
    <li>python311Packages.dockerspawner</li>
    <li>python311Packages.dockerspawner.dist</li>
    <li>python311Packages.jupyterhub</li>
    <li>python311Packages.jupyterhub-ldapauthenticator</li>
    <li>python311Packages.jupyterhub-ldapauthenticator.dist</li>
    <li>python311Packages.jupyterhub-systemdspawner</li>
    <li>python311Packages.jupyterhub-systemdspawner.dist</li>
    <li>python311Packages.jupyterhub-tmpauthenticator</li>
    <li>python311Packages.jupyterhub-tmpauthenticator.dist</li>
    <li>python311Packages.jupyterhub.dist</li>
    <li>python311Packages.oauthenticator</li>
    <li>python311Packages.oauthenticator.dist</li>
    <li>teleprompter</li>
    <li>whalebird</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>graphite-cli</li>
  </ul>
</details>
<details>
  <summary>73 packages built:</summary>
  <ul>
    <li>balanceofsatoshis</li>
    <li>bitwarden-cli</li>
    <li>breitbandmessung</li>
    <li>castnow</li>
    <li>commitlint</li>
    <li>create-cycle-app</li>
    <li>emacsPackages.lsp-bridge</li>
    <li>emanote</li>
    <li>emanote.data</li>
    <li>fast-cli</li>
    <li>flexoptix-app</li>
    <li>flood</li>
    <li>gtop</li>
    <li>haskellPackages.emanote</li>
    <li>haskellPackages.emanote.data</li>
    <li>haskellPackages.emanote.doc</li>
    <li>haskellPackages.tailwind</li>
    <li>haskellPackages.tailwind.doc</li>
    <li>jellyseerr</li>
    <li>joplin</li>
    <li>lessc</li>
    <li>lighthouse</li>
    <li>lv_img_conv</li>
    <li>morgen</li>
    <li>n8n</li>
    <li>node2nix</li>
    <li>nodehun</li>
    <li>openmoji-black</li>
    <li>openmoji-color</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>pot</li>
    <li>pscid</li>
    <li>pulsar</li>
    <li>pyright</li>
    <li>python310Packages.nbdev</li>
    <li>python310Packages.nbdev.dist</li>
    <li>python311Packages.nbdev</li>
    <li>python311Packages.nbdev.dist</li>
    <li>quarto</li>
    <li>quartoMinimal</li>
    <li>redoc-cli</li>
    <li>reveal-md</li>
    <li>slack</li>
    <li>styx</li>
    <li>styx.lib</li>
    <li>styx.themes</li>
    <li>teams</li>
    <li>theLoungePlugins.plugins.closepms</li>
    <li>theLoungePlugins.plugins.giphy</li>
    <li>theLoungePlugins.themes.flat-blue</li>
    <li>theLoungePlugins.themes.flat-dark</li>
    <li>uppy-companion</li>
    <li>vimPlugins.coc-clangd</li>
    <li>vimPlugins.coc-markdownlint</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-sh</li>
    <li>vimPlugins.coc-spell-checker</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-tslint</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vimPlugins.markdown-preview-nvim</li>
    <li>vscode</li>
    <li>vscode-extensions.ms-python.vscode-pylance</li>
    <li>vscode-extensions.rust-lang.rust-analyzer</li>
    <li>vscode-fhs</li>
    <li>vscode-langservers-extracted</li>
    <li>vscode-with-extensions</li>
    <li>vscodium</li>
    <li>vscodium-fhs</li>
    <li>wasm-text-gen</li>
    <li>wrangler</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
If you need an update of any cli or package like thing in nodePackages consider moving it out and convert it to use buildNpmPackage

**Comment by aqrln** [comment]
Understood, will do that next time. Thanks for the tip!

**Comment by SuperSandro2000** [comment]
fixing graphite-cli in #244153

**Pull request merged**
