### PR TITLE
texlivePackages: add homepage

### PR DESCRIPTION
**Pull request by yVieta**
## Description of changes
add homepage to TexlivePackages

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by xworld21** [comment]
Good idea! Are you sure `pname` is safe to use this way, though? I'd rather extract the info from texlive.tlpdb.

**Comment by yVieta** [comment]
> Good idea! Are you sure `pname` is safe to use this way, though? I'd rather extract the info from texlive.tlpdb.

All Texlive packages are on  https://ctan.org. Each package has their own url. Forinstance tex-math has https://ctan.org/pkg/tex-math. They also include all information about the package. This can also help packagers to find the correct license.

**Comment by xworld21** [comment]
> All Texlive packages are on https://ctan.org. Each package has their own url.

I mean to say, TeX Live packages do not match CTAN packages 1-1, for instance there is no 'latex-bin'.

I'd be happy to add the relevant info to `tlpdb.nix`, though. In fact, there is lots of metadata we do not currently include – it didn't really matter until we surfaced `texlivePackages`.

**Review by xworld21 — CHANGES_REQUESTED** [review]
I have looked into this a bit more carefully. This will set an invalid homepage for quite a few packages, for instance cjkutils and latex-bin.

To add the home pages correctly, you need to modify `tl2nix.sed` in order to preserve the following info from `texlive.tlpdb`: the `catalogue` attribute if present (for when `pname` differs from the CTAN name, such as cjkutils), and if there are any `catalogue-` attributes at all, say with `hasCatalogue = true;` (to recognise non-CTAN packages such as latex-bin). Then set the homepage to either `https://ctan.org/pkg/${catalogue}`, `https://ctan.org/pkg/${pname}` according to those values.

@yVieta please let me know if you want to give it a try! However be warned that adding `hasCatalogue = true;` will be quite tricky – you'll need to do a sed loop, like for formats and hyphenation patterns, because you need to print `hasCatalogue = true;` only once, while you also need to parse `catalogue-license` and `catalogue-version` as we do now. Otherwise I'll find a moment to do it myself in a new PR.

**Comment by xworld21** [comment]
Superseded by #321744.

**Pull request closed without merging**
