### PR TITLE
php: replace substituteInPlace to patch

### PR DESCRIPTION
**Pull request by Izorkin**
###### Motivation for this change
Remove In the build log lot of warning mesages:
```
...
substituteStream(): WARNING: pattern '@CONFIGURE_OPTIONS@' doesn't match anything in file 'main/build-defs.h.in'
substituteStream(): WARNING: pattern '@PHP_LDFLAGS@' doesn't match anything in file 'main/build-defs.h.in'
substituteStream(): WARNING: pattern '@CONFIGURE_COMMAND@' doesn't match anything in file 'scripts/php-config.in'
substituteStream(): WARNING: pattern 'test -x "$PKG_CONFIG"' doesn't match anything in file './Zend/acinclude.m4'
substituteStream(): WARNING: pattern 'test -x "$PKG_CONFIG"' doesn't match anything in file './Zend/Zend.m4'
substituteStream(): WARNING: pattern 'test -x "$PKG_CONFIG"' doesn't match anything in file './ext/libxml/config0.m4'
substituteStream(): WARNING: pattern 'test -x "$PKG_CONFIG"' doesn't match anything in file './ext/dba/config.m4'
substituteStream(): WARNING: pattern 'test -x "$PKG_CONFIG"' doesn't match anything in file './ext/xml/config.m4'
substituteStream(): WARNING: pattern 'test -x "$PKG_CONFIG"' doesn't match anything in file './ext/tidy/config.m4'
substituteStream(): WARNING: pattern 'test -x "$PKG_CONFIG"' doesn't match anything in file './ext/date/config0.m4'
substituteStream(): WARNING: pattern 'test -x "$PKG_CONFIG"' doesn't match anything in file './ext/json/config.m4'
substituteStream(): WARNING: pattern 'test -x "$PKG_CONFIG"' doesn't match anything in file './ext/pdo_sqlite/config.m4'
substituteStream(): WARNING: pattern 'test -x "$PKG_CONFIG"' doesn't match anything in file './ext/xmlrpc/libxmlrpc/acinclude.m4'
substituteStream(): WARNING: pattern 'test -x "$PKG_CONFIG"' doesn't match anything in file './ext/xmlrpc/libxmlrpc/xmlrpc.m4'
...
```
and cleanup preConfigure phase.

cc @NixOS/php 
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Izorkin** [comment]
cc @NixOS/php

**Comment by aanderse** [comment]
One issue I have with this change is that your patch could potentially miss something if the patched files change in the future, though maybe `php` simply wouldn't compile in that case?

Currently there is no error, just warning. I think the current heavy handed substitute approach is better as it requires no manual maintaining... does anyone else have an opinion on that?

**Comment by etu** [comment]
I agree with you @aanderse. 

If the code change in the future one has to update the patch etc. Then it would become harder to do overrides to get other versions where the current substitutes just works.

I find these warnings to be harmless and as long as it builds it's fine with these warnings. So doing this is just asking for more issues than it's worth.

**Comment by Izorkin** [comment]
I don't think that there are going to be any big changes in build process in versions 7.2.x, 7.3.x and 7.4.x.
In php-8.x we also only need to change `#define CONFIGURE_COMMAND` in `main/build-defs.h.in`, and `ldflags` and `configure_options` in `scripts/php-config.in`. We don't need to patch pkgconfig in php-8.x at all.
To sum it up, it's not necessary to change anything in the patches in the future, or it might be needed very seldom.

**Comment by etu** [comment]
I'm thinking that we won't merge this, if someone disagree, make a comment here.

**Pull request closed without merging**
