### PR TITLE
maintainers: Fix github account names

### PR DESCRIPTION
**Pull request by mweinelt**
```
PlayerNameHere is now known on github as dixslyf. Editing maintainer-list.nix…
Borlaag likely deleted their github account
bhootjb is now known on github as jyssh. Editing maintainer-list.nix…
IvanMalison is now known on github as colonelpanic8. Editing maintainer-list.nix…
jonnybolton is now known on github as jonnynightingale. Editing maintainer-list.nix…
ee2500 likely deleted their github account
lethalman is now known on github as lucabrunox. Editing maintainer-list.nix…
theHedgehog0 is now known on github as pyrox0. Editing maintainer-list.nix…
maddiethecafebabe likely deleted their github account
nebulka1 likely deleted their github account
christianharke is now known on github as rake5k. Editing maintainer-list.nix…
razvan-flavius-panda is now known on github as freeman42x. Editing maintainer-list.nix…
joscha has no github handle
RichterOliver is now known on github as ORichterSec. Editing maintainer-list.nix…
DomesticMoth is now known on github as asciimoth. Editing maintainer-list.nix…
pjbarnoy is now known on github as waaamb. Editing maintainer-list.nix…
```

None of the deleted maintainers hold any package maintainership.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by delroth** [comment]
> None of the deleted maintainers hold any package maintainership.

That doesn't seem to match my greps:

```
pkgs/development/tools/extism-cli/default.nix:    maintainers = with maintainers; [ borlaag ];
pkgs/development/libraries/yas/default.nix:    maintainers = with maintainers; [ ee2500 ];
pkgs/tools/virtualization/uefi-run/default.nix:    maintainers = [ maintainers.maddiethecafebabe ];
pkgs/applications/virtualization/rvvm/default.nix:    maintainers = with maintainers; [ nebulka ];
```

**Comment by mweinelt** [comment]
Must've grepped from a subdirectory, my bad. I think we can remove these maintainers still, if they can't contribute through GitHub any longer.

**Review by delroth — APPROVED** [review]
LGTM, let's just make sure ofborg-eval completes successfully.

**Comment by eclairevoyant** [comment]
Not sure why @jooooscha was removed, as they clearly have a gh acc and are a maintainer of a module (#241088). This PR therefore breaks config eval.

**Comment by delroth** [comment]
That looks like a bug in the fix-maintainers script (it doesn't update a missing github account name, even when a githubId is present). Of course we should have avoided having that broken maintainers list entry in the first place...

**Pull request merged**
