### PR TITLE
rust-analyzer: 2020-04-06 -> 2020-04-20

### PR DESCRIPTION
**Pull request by oxalica**
###### Motivation for this change
Bump rust-analyzer.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — COMMENTED** [review]
the changes to ` pkgs/development/node-packages/node-packages-v12.nix` are not really needed

**Comment by HugoReeves** [comment]
Thanks for packaging rust-analyzer!
Was able to build and execute on NixOS and MacOS Catalina.

I'm not involved with any of these packages, but, I believe removing quotes around the URLs in nodePackages is probably not a good idea. I think I read somewhere that future versions of the Nix language might look to remove the special syntax for URLs, so keeping the URLs in quotes is probably a good idea.

You're also changing a package which isn't really associated with rust-analyzer, so if you want to make the edits to nodePackages they should probably get their own PR.
Just my thoughts, thanks again.

**Comment by oxalica** [comment]
@jonringer 
Actually yes, but the generator updates all of them. Only `node-packages-v10.nix` is used by `vscode-extensions.rust-analyzer` and should be updated.
So should I only update v10 packages here?

**Comment by oxalica** [comment]
2020-04-20 is released, but blocked by #85618.

**Comment by oxalica** [comment]
@jonringer Bumped to 2020-04-20 and upgrade only `node-packages-v10.nix` now.

**Pull request merged**
