### PR TITLE
pythonPackages.fasttext: 0.2.0 -> 0.9.1

### PR DESCRIPTION
**Pull request by danieldk**
###### Motivation for this change

Changes:

- Refactoring of internal classes.
- Better unicode handling.
- New Python API: https://fasttext.cc/docs/en/python-module.html

https://github.com/facebookresearch/fastText/releases/tag/v0.9.1

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by danieldk** [comment]
@GrahamcOfBorg build pythonPackages.fasttext python3Packages.fasttext

**Review by jonringer — APPROVED** [review]
`$ nix-review pr 64640` passes on NixOS
diff LGTM

```
[4 built, 8 copied (80.1 MiB), 11.6 MiB DL]
https://github.com/NixOS/nixpkgs/pull/64640
2 package were build:
python27Packages.fasttext python37Packages.fasttext
```

**Comment by costrouc** [comment]
Nix review passed

Result of `nix-review pr 64640` [1](https://github.com/Mic92/nix-review)
<details>
  <summary>2 package were build:</summary>

  - python27Packages.fasttext
  - python37Packages.fasttext
</details>

**Comment by teto** [comment]
Thanks for the package and the reviews.

**Pull request merged**
