### PR TITLE
jetbrains.* 2019.2.* -> 2019.3

### PR DESCRIPTION
**Pull request by kolaente**
###### Motivation for this change

Bugfix releases of jetbrains Ideas.

For me, Goland is broken in 2019.2.4. so I updated it to 2019.3. (I'm not sure if it is broken for everyone, it could be my specific combination of plugins). It works with 2019.3.

I've tested the execution of Goland, Phpstorm and clion.

IMHO, as Goland is broken, it should be backported to stable.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by liff** [comment]
There’s 2019.3 release available for these (per running `update.pl`):
 - CLion
 - GoLand
 - Intellij IDEA
 - PhpStorm
 - RubyMine
 - WebStorm

**Comment by liff** [comment]
If updating to 2019.3, perhaps update jetbrains-jdk as well? The JDK version bundled with idea-community for Linux looks to be 520.11.

**Comment by kolaente** [comment]
@liff I've updated the IDE's to 2019.3

I'm not sure how to find the latest version of the jdk, simply putting `520.11` as version in https://github.com/NixOS/nixpkgs/blob/dae3575cee5b88de966d06b11861c602975cb23a/pkgs/development/compilers/jetbrains-jdk/default.nix#L10 does not seem to work. Do you have an idea?

**Comment by liff** [comment]
I found the [jetbrains-jdk release files](https://bintray.com/jetbrains/intellij-jbr/) by stripping `download_file` from the bintray URLs in `fetchurl`. The files for the 520.11 release can be found under
 - [jbrsdk11-linux-x64](https://bintray.com/jetbrains/intellij-jbr/jbrsdk11-linux-x64/520.11#files) and
 - [jbrsdk11-osx-x64](https://bintray.com/jetbrains/intellij-jbr/jbrsdk11-osx-x64/520.11#files).

For macOS the OpenJDK version has changed from 11.0.2 to 11.0.4 so the download URL for `x86_64-darwin` should be changed to:

    https://bintray.com/jetbrains/intellij-jdk/download_file?file_path=jbrsdk-11_0_4-osx-x64-b${version}.tar.gz

You can get the [`sha256` values](https://github.com/NixOS/nixpkgs/blob/492be34fc98b5a119ccb014df2cf0848838a9ad6/pkgs/development/compilers/jetbrains-jdk/default.nix#L15) by running:

```bash
# Linux
nix-prefetch-url 'https://bintray.com/jetbrains/intellij-jbr/download_file?file_path=jbrsdk-11_0_4-linux-x64-b520.11.tar.gz'
# macOS
nix-prefetch-url 'https://bintray.com/jetbrains/intellij-jbr/download_file?file_path=jbrsdk-11_0_4-osx-x64-b520.11.tar.gz'
```

**Comment by liff** [comment]
Noticed that the macOS bintray repository for JetBrains Runtime is currently [`intellij-jdk`](https://github.com/NixOS/nixpkgs/blob/492be34fc98b5a119ccb014df2cf0848838a9ad6/pkgs/development/compilers/jetbrains-jdk/default.nix#L19) and not `intellij-jbr` as it should be.

See also: #75171

**Comment by pmiddend** [comment]
Is there anything blocking this PR from being merged?

**Comment by sjfloat** [comment]
A review, apparently.

**Comment by kolaente** [comment]
A new update was available for 2019.3.1, I updated.

**Comment by kolaente** [comment]
@liff I would propose to move updating the jdk into a seperate PR, to get this one merged as fast as possible.

**Comment by liff** [comment]
Sounds good to me. 2013.3.1 seems to ship with 520.17.

**Review by Lassulus — APPROVED** [review]
tested with nix-review, sorry for the delay

**Comment by kolaente** [comment]
@Lassulus Thanks!

**Comment by jonringer** [comment]
this commit history should have been cleaned up. Each package was bumped 3x

**Pull request merged**
