### PR TITLE
nixos/test-driver: more context when step finishes, give more functions nested labels

### PR DESCRIPTION
**Pull request by cole-h**
###### Motivation for this change

By adding context about the step that finished in the elapsed time, it becomes easier to read (or grep) through the test output.

Additionally, every step that is waiting for something to happen or finish happening should document itself via the `nested` function so there are fewer steps that are difficult to search for in the logs.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Example snippet:

```
Machine state will be reset. To keep it, pass --keep-vm-state
start all VLans
start vlan
running vlan (pid 7)
(finished: start all VLans, in 0.00 seconds)
run the VM test script
additionally exposed symbols:
    machine,
    vlan1,
    start_all, test_script, machines, vlans, driver, log, os, create_machine, subtest, run_tests, join_all, retry, serial_stdout_off, serial_stdout_on, Machine
machine: starting vm
machine # Formatting '/build/vm-state-machine/machine.qcow2', fmt=qcow2 cluster_size=65536 extended_l2=off compression_type=zlib size=1073741824 lazy_refcounts=off refcount_bits=16
machine: waiting for monitor prompt
(finished: waiting for monitor prompt, in 0.00 seconds)
machine: QEMU running (pid 8)
machine: waiting for unit test.service
machine: waiting for the VM to finish booting
[... snip ...]
machine: connected to guest root shell
machine: (connecting took 4.85 seconds)
(finished: waiting for the VM to finish booting, in 4.86 seconds)
[... snip ...]
(finished: waiting for unit test.service, in 10.05 seconds)
machine: must succeed: systemd-cat echo 'doing some things'; sleep 5
machine # [    9.766839] echo[906]: doing some things
(finished: must succeed: systemd-cat echo 'doing some things'; sleep 5, in 5.04 seconds)
machine: must succeed: systemd-cat echo 'some more stuff'; sleep 5
machine # [   14.802560] echo[911]: some more stuff
(finished: must succeed: systemd-cat echo 'some more stuff'; sleep 5, in 5.03 seconds)
machine: must succeed: systemd-cat echo 'wow, done'; sleep 5
machine # [   19.843773] echo[917]: wow, done
(finished: must succeed: systemd-cat echo 'wow, done'; sleep 5, in 5.04 seconds)
(finished: run the VM test script, in 25.19 seconds)
test script finished in 25.21s
cleanup
kill machine (pid 8)
machine # qemu-system-x86_64: terminating on signal 15 from pid 6 (/nix/store/8dxxjbiyxwkvh53q5kh6nydla2anacgi-python3-3.9.6/bin/python3)
(finished: cleanup, in 0.01 seconds)
```

Imagine those `snip`s were filled with tons more log lines (they were) -- it's much easier to figure out e.g. when "waiting for unit test.service" actually finished (if ever).

### CODE REVIEW

**Comment by cole-h** [comment]
@tfc Is there anything I can do to get this in, or do you just need to find some time for review?

**Comment by tfc** [comment]
hey @cole-h this looks generally good, but i am not completely sure if everyone wants all this output all the time, as it has slight debugging-info-character.

**Comment by cole-h** [comment]
IMHO, I think it's fair to add "debugging-info" to our test suite. I might even argue that all the "must succeed:" stuff is also debugging-related... If someone comes across an issue with some test, it will make tracking it down easier. Better to have it now than to need it later.

**Comment by cole-h** [comment]
Ping @tfc -- I think this is really a net-positive (especially for long-running / output-spewing tests).

**Comment by tfc** [comment]
@ofborg test installer.simple installer.zfsroot doas sudo hydra nginx wireguard deluge cage

**Pull request merged**
