### PR TITLE
qt515.qtwebkit: unbreak

### LINKED ISSUE #105467: qtwebkit marked as broken
**Describe the bug**
qtwebkit has been marked as broken for serveral weeks/months now.

**To Reproduce**
1. Try to build qtwebkit on nixos-unstable

```
error: Package ‘qtwebkit-5.212.0-alpha4’ in /nix/store/dkknbjkiilpxbqysnnf8pyvdrcjb7hhm-nixos-21.03pre255513.8ee7c2505f9/nixos/pkgs/development/libraries/qt-5/qtModule.nix:54 is marked as broken, refusing to evaluate.

a) To temporarily allow broken packages, you can use an environment variable
   for a single invocation of the nix tools.

     $ export NIXPKGS_ALLOW_BROKEN=1

b) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.config/nixpkgs/config.nix.

(use '--show-trace' to show detailed location information)
```

**Expected behavior**
qtwebkit should build.

**Notify maintainers**
@abbradar 
@periklis 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.62, NixOS, 20.09.git.61525137fd1 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(hyper): `"nixos-20.09pre242769.61525137fd1"`
 - channels(root): `"nixos-21.03pre255513.8ee7c2505f9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by doronbehar**
###### Motivation for this change

More qt515 fixes (like https://github.com/NixOS/nixpkgs/pull/102840) with unbroken qt515.qtwebkit.

Here's a `git grep` list of packages that use qt514 in `all-packages.nix`. Ideally each of them needs to have at least a comment explaining why it uses qt514 and not qt515. Usually they are pinned to qt514 since qt515.qtwebkit is broken on master, but not on this branch - hence every package listed here likely _can_ use qt515.

- [x] digitalbitbox - has a comment regarding qt514 (segfaults with qt515).
- [ ] apitrace
- [ ] brewtarget (@mmahut)
- [ ] calamares (@manveru)
- [ ] clementine - has a comment regarding qt514 (for the next update)
- [ ] mellowplayer (@kalbasit)
- [ ] dsview (@bachp)
- [ ] fontmatrix
- [x] hal-hardware-analyzer (@risicle)
- [x] heaptrack (@gebner) - already fixed in #104442
- [ ] i-score (@magnetophon)
- [ ] iannix (@freezeboy)
- [ ] partition-manager (@peterhoeg)
- [ ] ksmoothdock (@SCOTT-HAMILTON)
- [ ] kstars (@TimPut)
- [ ] nixnote2 (@htr)
- [ ] nmapsi4 (@peterhoeg)
- [ ] olive-editor (@balsoft)
- [ ] owncloud-client (@qknight)
- [ ] qownnotes (@dtzWill)
- [x] qtikz
- [ ] rosegarden (@lebastr)
- [ ] subsurface (@mguentner)
- [ ] teamviewer (@jagajaga)
- [x] texworks (@dotlambda)
- [ ] wkhtmltopdf (@jb55)
- [ ] colmap (@lebastr)
- [ ] nextpnr (@thoughtpolice @emilazy)
- [ ] supercollider (@MrMebelMan)
- [ ] phantomjs2 (@aflatter)
- [ ] qtcreator (@akaWolf)
- [ ] herqq 
- [ ] qolibri
- [ ] qgnomeplatform - should be handled in https://github.com/NixOS/nixpkgs/pull/102594 .
- [ ] vtk_9 (@tfmoraes)
- [ ] qmc2
- [ ] zeal (@svenkeidel @peterhoeg)
- [ ] antimony (@rnhmjoj)
- [ ] in
- [ ] bibletime
- [ ] calligra (@phreedom @ebzzry @zraexy)
- [ ] cb2bib (@edwtjo)
- [ ] copyq (@willtim)
- [ ] dfilemanager
- [ ] drawpile (@fgaz)
- [ ] drawpile-server-headless
- [ ] evilpixie (@fgaz)
- [x] ghostwriter (@dotlambda)
- [x] goldendict (@gebner @astsmtl @sikmir) - fixed in #106774 
- [x] gqrx - should be handled in https://github.com/NixOS/nixpkgs/pull/99685 .
- [ ] mindforger
- [ ] multibootusb
- [x] gpsbabel (@rycee)
- [x] gpsbabel-gui (@sikmir)
- [x] inspectrum - should be handled in https://github.com/NixOS/nixpkgs/pull/99685 .
- [ ] ipe (@ttuegel)
- [ ] kdevelop-pg-qt
- [ ] kdevelop-unwrapped (@ambrop72)
- [ ] kdev-php (@aanderse)
- [ ] kdev-python
- [ ] kexi (@zraexy)
- [ ] kotatogram-desktop (@ilya-fedin)
- [ ] krusader (@sander @turion)
- [ ] kvirc (@suhr)
- [ ] librecad (@kiwi @viric)
- [ ] libreoffice (@7c6f434c)
- [ ] lsd2dsl (@sikmir)
- [x] mapmap (@erictapen)
- [ ] mendeley (@dtzWill)
- [ ] merkaartor
- [ ] p4v (@nathyong @nioncode)
- [ ] polyphone (@Maxdamantus)
- [ ] shotcut (@cillianderoiste @woffs @peti)
- [ ] smtube (@vbgl)
- [ ] mythtv (@titanous)
- [ ] notepadqq (@rszibele)
- [ ] obs-ndi (@peti @jshcmbll)
- [ ] pulseview (@bjornfor)
- [ ] in
- [ ] qlandkartegt (@sikmir)
- [x] qmapshack (@dotlambda @sikmir)
- [x] qsyncthingtray
- [ ] quiterss (@primeos)
- [ ] falkon (@peterhoeg)
- [ ] rapcad (@7c6f434c)
- [x] rclone-browser (@dotlambda)
- [ ] rpcs3 (@abbradar @nocent)
- [ ] rstudio (@ehmry @changlinli @ciil)
- [ ] sayonara (@deepfire)
- [ ] scantailor-advanced (@jfrankenau)
- [x] scribusUnstable (@erictapen @kiwi)
- [x] seafile-client
- [ ] swift-im (@orivej)
- [ ] toggldesktop (@yegortimoshenko)
- [ ] tony (@orivej)
- [ ] trojita (@ehmry)
- [ ] valentina (@jfrankenau)
- [ ] qpdfview (@7c6f434c)
- [ ] virtualbox (@svanderburg)
- [x] vlc
- [ ] wpsoffice (@Ninlives @Th0rgal)
- [ ] xygrib (@SuperSandro2000 @johannesloetzsch)
- [ ] zanshin (@zraexy)
- [ ] zombietrackergps (@Sohalt)
- [ ] bitcoin-unlimited (@DmitryTsygankov)
- [ ] bitcoin-classic (@jefdaj)
- [ ] bitcoin-gold (@mmahut)
- [ ] digibyte (@mmahut)
- [ ] litecoin (@offlinehacker)
- [ ] vertcoin (@mmahut)
- [x] digikam
- [ ] hedgewars (@kragniz @fpletz)
- [ ] solarus
- [ ] solarus-quest-editor
- [ ] apmplanner2 (@wucke13)
- [ ] mame (@gnidorah)
- [ ] wacomtablet (@Thra11)
- [ ] golden-cheetah (@ocharles)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix-useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by doronbehar** [comment]
cc @freezeboy for review.

**Comment by freezeboy** [comment]
Looks good for me

**Comment by FRidh** [comment]
> konversation: 1.7.5 -> 1.7.5

Should be 1.7.7.

**Comment by doronbehar** [comment]
> Should be 1.7.7.

Fixed.

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by ctheune** [comment]
Note that wkhtmltopdf should not be using the general qtwebkit as it maintains its own set of patches. PR #96379 fixes this.

**Review by ttuegel — APPROVED** [review]

**Comment by ttuegel** [comment]
As I remarked [elsewhere](https://github.com/NixOS/nixpkgs/pull/106118#issuecomment-743145753),

> I think we should go ahead and merge the qtwebkit changes to master. There are many packages which can probably be upgraded from Qt 5.14 to Qt 5.15 now, so it would be good if those package maintainers could start testing as soon as possible.

**Comment by ttuegel** [comment]
I updated the top comment to ping the relevant maintainers.

Please test your packages with Qt 5.15, and un-pin them from Qt 5.14 if everything is working. (Note: this will probably not be possible for proprietary applications.)

**Comment by turion** [comment]
Does that mean we should use `libsForQt5` or `libsForQt515`? Probably `libsForQt5` is better?

**Comment by freezeboy** [comment]
Yes better to use the generic version to avoid the same problem with many programs pinned to 5.15 when the default qt5 will be updated

**Comment by fgaz** [comment]
`evilpixie` waiting on upstream: https://github.com/bcampbell/evilpixie/issues/14

**Comment by dotlambda** [comment]
There seems to be a limit to the number of people you can ping in a message. We should remove the maintainer ping for the packages that have already been fixed.

**Pull request merged**
