### PR TITLE
unzip: fix symlink unpacking issues on larger zips

### PR DESCRIPTION
**Pull request by shyim**
###### Description of changes

Some files are unpacked in bigger zips as symlinks. See https://gitlab.alpinelinux.org/alpine/aports/-/issues/11986
and patch https://sources.debian.org/patches/unzip/6.0-26/06-initialize-the-symlink-flag.patch/ from Debian

###### Things done

#181572 

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [X] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by trofi — CHANGES_REQUESTED** [review]
The change looks good but please rebase it against `staging` branch.

I usually rebase a single patch locally against merge-base of `staging` and `master` and then force-push. I can do it for you if you are not comfortable with that.

**Review by Mindavi — APPROVED** [review]
Looked a bit into the history and this seems like the go-to patch for this issue.

**Comment by shyim** [comment]
@trofi I have currently no time. It would be nice if you could do it for me ❤️

**Review by trofi — APPROVED** [review]
Rebased against `staging` and squashed in Sandro's suggestion. Should be ready.

**Pull request merged**
