### PR TITLE
flyctl: 0.2.52 -> 0.2.55

### PR DESCRIPTION
**Pull request by RaghavSood**
## Description of changes

Update `flyctl` to 0.2.55

This also reworks the check phases. Upstream introduced some tests in [flyctl#3430](https://github.com/superfly/flyctl/pull/3430) that require network access - we can skip all of them by ignoring `TestToTestMachineConfig`.

For some reason, we were running tests in postCheck. We can instead override checkPhase (replicating the base construct) to run checks against `./...`. Under current `buildGoModule` structure, it is not possible to use `subPackages` (which we want in this case since we only want to build the root package, and not the various internal and audit ones), and also run tests against `./...`. 

By reusing the plumbing of `checkPhase`, we can also avoid duplicating the `ldflags` as they are already included.

See #284568 for an ongoing, potential fix to test problem.

An updateScript has been added as well - upstream tags any PR merge as its own release tag like `v2024.5.20-pr3545.4` - by ignoring tags with `-`, we can skip those and stick to the normal release tags.

I have also added myself as a maintainer.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by RaghavSood** [comment]
Result of `nixpkgs-review pr 313157` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>flyctl</li>
  </ul>
</details>

**Comment by RaghavSood** [comment]
Result of `nixpkgs-review pr 313157` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>flyctl</li>
  </ul>
</details>

**Review by techknowlogick — APPROVED** [review]
Thanks!!

**Comment by billyb2** [comment]
hi, i'm upstream :). why would `TestToTestMachineConfig` require network access? We're reading from a toml file and making sure it's producing a specific output.

**Comment by RaghavSood** [comment]
Hey upstream - thanks for chiming in.

You're right, the actual failure doesn't appear to be a network issue:

```
--- FAIL: TestToTestMachineConfig (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0xa8 pc=0x1058e6b9c]

goroutine 66 [running]:
testing.tRunner.func1.2({0x105ca0b40, 0x1065ca000})
        /nix/store/i04a1a6qgxhjw6c0ld2b3x1v815sbxjc-go-1.22.3/share/go/src/testing/testing.go:1631 +0x1c4
testing.tRunner.func1()
        /nix/store/i04a1a6qgxhjw6c0ld2b3x1v815sbxjc-go-1.22.3/share/go/src/testing/testing.go:1634 +0x33c
panic({0x105ca0b40?, 0x1065ca000?})
        /nix/store/i04a1a6qgxhjw6c0ld2b3x1v815sbxjc-go-1.22.3/share/go/src/runtime/panic.go:770 +0x124
github.com/superfly/flyctl/internal/appconfig.(*Config).ToTestMachineConfig(0x140004b5980, 0x1400042d1d0, 0x0)
        /private/tmp/nix-build-flyctl-0.2.55.drv-1/source/internal/appconfig/machines.go:153 +0x59c
github.com/superfly/flyctl/internal/appconfig.TestToTestMachineConfig(0x14000490d00)
        /private/tmp/nix-build-flyctl-0.2.55.drv-1/source/internal/appconfig/machines_test.go:210 +0x51c
testing.tRunner(0x14000490d00, 0x105dd9ac0)
        /nix/store/i04a1a6qgxhjw6c0ld2b3x1v815sbxjc-go-1.22.3/share/go/src/testing/testing.go:1689 +0xec
created by testing.(*T).Run in goroutine 1
        /nix/store/i04a1a6qgxhjw6c0ld2b3x1v815sbxjc-go-1.22.3/share/go/src/testing/testing.go:1742 +0x318
```

This is tailing at `mConfig.Env["FLY_TEST_MACHINE_IP"] = lo.Ternary(origMachine == nil, "", origMachine.PrivateIP)` on [internal/appconfig/machines.go#L153](https://github.com/superfly/flyctl/blob/v0.2.55/internal/appconfig/machines.go#L153).

Looks like `origMachine` is passed in as `nil`

**Comment by RaghavSood** [comment]
@billyb2 Looks like the issue was resolved in [flyctl#3561](https://github.com/superfly/flyctl/pull/3561) - my version bump to `0.2.58` in #314437 drops the test skip flag as it is no longer necessary.

**Pull request merged**
