### PR TITLE
prometheus-lnd-exporter: unstable-2020-12-04 -> unstable-2021-03-26, fix test

### PR DESCRIPTION
**Pull request by mmilata**
###### Motivation for this change

Bunch of new metrics have been added since the last version. Also test was broken.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by drewrisinger — CHANGES_REQUESTED** [review]
* [x] Diff LGTM
* [x] Commits LGTM
* [x] Builds via ``nix-review`` on x86-64-linux:

```
1 package built:
prometheus-lnd-exporter
```
* [ ] Nixos tests fail:
```
running the VM test script
apcupsd: starting vm
apcupsd: starting vm
apcupsd # Formatting '/build/vm-state-apcupsd/apcupsd.qcow2', fmt=qcow2 cluster_size=65536 extended_l2=off compression_type=zlib size=536870912 lazy_refcounts=off refcount_bits=16
apcupsd # Formatting '/build/vm-state-apcupsd/apcupsd.qcow2', fmt=qcow2 cluster_size=65536 extended_l2=off compression_type=zlib size=536870912 lazy_refcounts=off refcount_bits=16
apcupsd # Could not access KVM kernel module: Permission denied
apcupsd # Could not access KVM kernel module: Permission denied
apcupsd # qemu-system-x86_64: failed to initialize kvm: Permission denied
apcupsd # qemu-system-x86_64: failed to initialize kvm: Permission denied
apcupsd: QEMU running (pid 7)
apcupsd: QEMU running (pid 7)
apcupsd: waiting for the VM to finish booting
apcupsd: waiting for the VM to finish booting
apcupsd: connected to guest root shell
apcupsd: connected to guest root shell
apcupsd: (connecting took 0.00 seconds)
apcupsd: (connecting took 0.00 seconds)
(0.00 seconds)
(0.00 seconds)
error:
error: 
Traceback (most recent call last):
Traceback (most recent call last):
  File "/nix/store/kywf23qy7r8857ba5m0z1shjswrf2qd1-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 897, in run_tests
  File "/nix/store/kywf23qy7r8857ba5m0z1shjswrf2qd1-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 897, in run_tests
    exec(tests, globals())
    exec(tests, globals())
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 2, in <module>
  File "<string>", line 2, in <module>
  File "/nix/store/kywf23qy7r8857ba5m0z1shjswrf2qd1-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 348, in wait_for_unit
  File "/nix/store/kywf23qy7r8857ba5m0z1shjswrf2qd1-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 348, in wait_for_unit
    retry(check_active)
    retry(check_active)
  File "/nix/store/kywf23qy7r8857ba5m0z1shjswrf2qd1-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 136, in retry
  File "/nix/store/kywf23qy7r8857ba5m0z1shjswrf2qd1-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 136, in retry
    if fn(False):
    if fn(False):
  File "/nix/store/kywf23qy7r8857ba5m0z1shjswrf2qd1-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 330, in check_active
  File "/nix/store/kywf23qy7r8857ba5m0z1shjswrf2qd1-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 330, in check_active
    info = self.get_unit_info(unit, user)
    info = self.get_unit_info(unit, user)
  File "/nix/store/kywf23qy7r8857ba5m0z1shjswrf2qd1-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 351, in get_unit_info
  File "/nix/store/kywf23qy7r8857ba5m0z1shjswrf2qd1-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 351, in get_unit_info
    status, lines = self.systemctl('--no-pager show "{}"'.format(unit), user)
    status, lines = self.systemctl('--no-pager show "{}"'.format(unit), user)
  File "/nix/store/kywf23qy7r8857ba5m0z1shjswrf2qd1-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 382, in systemctl
  File "/nix/store/kywf23qy7r8857ba5m0z1shjswrf2qd1-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 382, in systemctl
    return self.execute("systemctl {}".format(q))
    return self.execute("systemctl {}".format(q))
  File "/nix/store/kywf23qy7r8857ba5m0z1shjswrf2qd1-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 400, in execute
  File "/nix/store/kywf23qy7r8857ba5m0z1shjswrf2qd1-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 400, in execute
    self.shell.send(out_command.encode())
    self.shell.send(out_command.encode())
BrokenPipeError: [Errno 32] Broken pipe
BrokenPipeError: [Errno 32] Broken pipe
cleaning up
cleaning up
killing apcupsd (pid 7)
killing apcupsd (pid 7)
(0.00 seconds)
(0.00 seconds)
builder for '/nix/store/ciqfgbblkhb5iv96y4qjx1id8jg1bvpv-vm-test-run-prometheus-apcupsd-exporter.drv' failed with exit code 1
```

**Comment by mmilata** [comment]
@drewrisinger thanks for reviewing this! The failure looks unrelated to the PR, the failing test is for apcupsd exporter. Also the problem doesn't seem to be the exporter itself but rather the (execution of?) the testing infrastructure:

```
apcupsd # Could not access KVM kernel module: Permission denied
apcupsd # qemu-system-x86_64: failed to initialize kvm: Permission denied
```

If other NixOS tests work fine for you, could this be caused by the exporters test creating huge amount of virtual machines at once? It should be possible to run just the `prometheus-lnd-exporter` test by `nix-build -A lnd prometheus-exporters.nix` or `nix-build -A nixosTests.prometheus-exporters.lnd`.

**Comment by drewrisinger** [comment]
> It should be possible to run just the `prometheus-lnd-exporter` test by `nix-build -A lnd prometheus-exporters.nix` or `nix-build -A nixosTests.prometheus-exporters.lnd`.

Here's what I just tried re-running now (via ``nix-review``):
```
[nix-shell:~/.cache/nixpkgs-review/pr-118630-1]$ nix-build -A lnd ./nixpkgs/nixos/tests/prometheus-exporters.nix 
this derivation will be built:
  /nix/store/mhfwvz0cza8gpqli1wqh78jmkvk50100-vm-test-run-prometheus-lnd-exporter.drv
building '/nix/store/mhfwvz0cza8gpqli1wqh78jmkvk50100-vm-test-run-prometheus-lnd-exporter.drv'...
starting VDE switch for network 1
starting VDE switch for network 1
running the VM test script
running the VM test script
lnd: starting vm
lnd: starting vm
lnd # Formatting '/build/vm-state-lnd/lnd.qcow2', fmt=qcow2 cluster_size=65536 extended_l2=off compression_type=zlib size=536870912 lazy_refcounts=off refcount_bits=16
lnd # Formatting '/build/vm-state-lnd/lnd.qcow2', fmt=qcow2 cluster_size=65536 extended_l2=off compression_type=zlib size=536870912 lazy_refcounts=off refcount_bits=16
lnd # Could not access KVM kernel module: Permission denied
lnd # Could not access KVM kernel module: Permission denied
lnd # qemu-system-x86_64: failed to initialize kvm: Permission denied
lnd # qemu-system-x86_64: failed to initialize kvm: Permission denied
lnd: QEMU running (pid 7)
lnd: QEMU running (pid 7)
lnd: waiting for the VM to finish booting
lnd: waiting for the VM to finish booting
lnd: connected to guest root shell
lnd: connected to guest root shell
lnd: (connecting took 0.00 seconds)
lnd: (connecting took 0.00 seconds)
(0.00 seconds)
(0.00 seconds)
error:
error: 
Traceback (most recent call last):
Traceback (most recent call last):
  File "/nix/store/kywf23qy7r8857ba5m0z1shjswrf2qd1-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 897, in run_tests
  File "/nix/store/kywf23qy7r8857ba5m0z1shjswrf2qd1-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 897, in run_tests
    exec(tests, globals())
    exec(tests, globals())
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 2, in <module>
  File "<string>", line 2, in <module>
  File "/nix/store/kywf23qy7r8857ba5m0z1shjswrf2qd1-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 348, in wait_for_unit
  File "/nix/store/kywf23qy7r8857ba5m0z1shjswrf2qd1-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 348, in wait_for_unit
    retry(check_active)
    retry(check_active)
  File "/nix/store/kywf23qy7r8857ba5m0z1shjswrf2qd1-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 136, in retry
  File "/nix/store/kywf23qy7r8857ba5m0z1shjswrf2qd1-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 136, in retry
    if fn(False):
    if fn(False):
  File "/nix/store/kywf23qy7r8857ba5m0z1shjswrf2qd1-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 330, in check_active
  File "/nix/store/kywf23qy7r8857ba5m0z1shjswrf2qd1-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 330, in check_active
    info = self.get_unit_info(unit, user)
    info = self.get_unit_info(unit, user)
  File "/nix/store/kywf23qy7r8857ba5m0z1shjswrf2qd1-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 351, in get_unit_info
  File "/nix/store/kywf23qy7r8857ba5m0z1shjswrf2qd1-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 351, in get_unit_info
    status, lines = self.systemctl('--no-pager show "{}"'.format(unit), user)
    status, lines = self.systemctl('--no-pager show "{}"'.format(unit), user)
  File "/nix/store/kywf23qy7r8857ba5m0z1shjswrf2qd1-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 382, in systemctl
  File "/nix/store/kywf23qy7r8857ba5m0z1shjswrf2qd1-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 382, in systemctl
    return self.execute("systemctl {}".format(q))
    return self.execute("systemctl {}".format(q))
  File "/nix/store/kywf23qy7r8857ba5m0z1shjswrf2qd1-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 400, in execute
  File "/nix/store/kywf23qy7r8857ba5m0z1shjswrf2qd1-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 400, in execute
    self.shell.send(out_command.encode())
    self.shell.send(out_command.encode())
BrokenPipeError: [Errno 32] Broken pipe
BrokenPipeError: [Errno 32] Broken pipe
cleaning up
cleaning up
killing lnd (pid 7)
killing lnd (pid 7)
(0.00 seconds)
(0.00 seconds)
builder for '/nix/store/mhfwvz0cza8gpqli1wqh78jmkvk50100-vm-test-run-prometheus-lnd-exporter.drv' failed with exit code 1
error: --- Error ----------------------------------------------------- nix-build
build of '/nix/store/mhfwvz0cza8gpqli1wqh78jmkvk50100-vm-test-run-prometheus-lnd-exporter.drv' failed
```

I don't run nixos tests much, so there could be some problem with my machine/setup.

**Comment by mmilata** [comment]
Rebased to fix conflicts. Test still passes for me.

cc @prusnak

**Comment by prusnak** [comment]
@GrahamcOfBorg test prometheus-lnd-exporter

**Comment by prusnak** [comment]
@GrahamcOfBorg build prometheus-lnd-exporter

**Comment by mmilata** [comment]
Thanks! I think the test attribute was actually prometheus-exporters.lnd.

**Pull request merged**
