### PR TITLE
sponsorblock-minimal: replace sha256sum with nix store path

### PR DESCRIPTION
**Pull request by onemoresuza**
## Description of changes
Also format the file with nixfmt and replace `--replace` option with
`--replace-fail`.

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by arthsmn — APPROVED** [review]
LGTM.

**Comment by arthsmn** [comment]
Would you like to add yourself as a maintainer? You don't need to do so, just if you want it.

**Comment by onemoresuza** [comment]
> Would you like to add yourself as a maintainer? You don't need to do so, just if you want it.

I'd rather not: I'm not familiar with mpv's lua API to be able to maintain this plugin.

**Comment by arthsmn** [comment]
> > Would you like to add yourself as a maintainer? You don't need to do so, just if you want it.
> 
> I'd rather not: I'm not familiar with mpv's lua API to be able to maintain this plugin.
> 
> 

I was talking about just the package, but it's OK, thanks for the contribution!

**Comment by wegank** [comment]
The formatting doesn't comply with [RFC 166](https://github.com/NixOS/rfcs/blob/master/rfcs/0166-nix-formatting.md), however. Would you please reformat the file using `nixfmt-rfc-style`?

**Comment by Mic92** [comment]
> The formatting doesn't comply with [RFC 166](https://github.com/NixOS/rfcs/blob/master/rfcs/0166-nix-formatting.md), however. Would you please reformat the file using `nixfmt-rfc-style`?

Ah, sorry missed that comment. Do we now reformat packages in each pull request? I would have expect this to be rather a big PR where we reformat larger parts of nixpkgs, followed by some CI check.

**Comment by wegank** [comment]
> Do we now reformat packages in each pull request?

No, in fact I'd be happy to approve this PR if it's a one-line change. But since the reformatting was done in addition, I would expect it to follow RFC 166.

**Comment by onemoresuza** [comment]
> The formatting doesn't comply with [RFC 166](https://github.com/NixOS/rfcs/blob/master/rfcs/0166-nix-formatting.md), however. Would you please reformat the file using `nixfmt-rfc-style`?

My mistake, @wegank. I thought that now `nixfmt` was `nixfmt-rfc-style`, but after running the latter on the file, I can see that they are not.

**Pull request merged**
