### PR TITLE
postgresqlPackages.pgvecto-rs: 0.2.1 -> 0.3.0

### PR DESCRIPTION
**Pull request by diogotcorreia**
## Description of changes

https://github.com/tensorchord/pgvecto.rs/releases/tag/v0.3.0

~~However, this needs rustc 1.79, so it's failing to build.~~
~~Waiting for https://github.com/NixOS/nixpkgs/pull/320250~~

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by happysalada** [comment]
This looks good, feel free to ping me again when 1.79 lands on master

**Comment by happysalada** [comment]
Now that 1.79 is in, this should be good to go.
Do you have time to do a quick nixpkgs-review or local test by any chance ?

**Comment by diogotcorreia** [comment]
@happysalada I was waiting for it to be available in master, but I can rebase it on staging if you prefer

**Comment by happysalada** [comment]
You are completely right here, lets wait for it to land on master its just easier.

**Comment by diogotcorreia** [comment]
Rust 1.79 seems to already be in master, but perhaps we should only merge this after Immich supports 0.3.0?
See https://github.com/immich-app/immich/discussions/11091

Especially relevant since https://github.com/NixOS/nixpkgs/pull/324127 requires this package.

**Comment by diogotcorreia** [comment]
I've rebased this on master and it builds now. I had to do a small change to `buildPgrxExtension` since upstream removed the `pg_test` feature from their crate.

**Comment by happysalada** [comment]
The PR looks good but youre right we should probably wait for immich support before merging.

Small thing, it looks like there are merge conflicts with master. Youll need to rebase at some point.

**Comment by diogotcorreia** [comment]
Immich will support pgvecto-rs 0.3.0 in the next release: https://github.com/immich-app/immich/pull/11624

**Comment by diogotcorreia** [comment]
https://github.com/immich-app/immich/releases/tag/v1.112.0
Immich 1.112.0 released with support for this. Marking as ready

**Comment by happysalada** [comment]
Should we wait until the updated of immich gets merged ?

**Comment by esclear** [comment]
> Should we wait until the updated of immich gets merged ?

That seems reasonable to me.

**Pull request merged**
