### PR TITLE
libsForQt5.mauiPackages: 3.0.0 -> 3.0.1

### PR DESCRIPTION
**Pull request by wegank**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 252528` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>18 packages built:</summary>
  <ul>
    <li>libsForQt5.booth (plasma5Packages.booth)</li>
    <li>libsForQt5.buho (plasma5Packages.buho)</li>
    <li>libsForQt5.clip (plasma5Packages.clip)</li>
    <li>libsForQt5.communicator (plasma5Packages.communicator)</li>
    <li>libsForQt5.index (plasma5Packages.index)</li>
    <li>libsForQt5.mauikit (plasma5Packages.mauikit)</li>
    <li>libsForQt5.mauikit-accounts (plasma5Packages.mauikit-accounts)</li>
    <li>libsForQt5.mauikit-calendar (plasma5Packages.mauikit-calendar)</li>
    <li>libsForQt5.mauikit-filebrowsing (plasma5Packages.mauikit-filebrowsing)</li>
    <li>libsForQt5.mauikit-imagetools (plasma5Packages.mauikit-imagetools)</li>
    <li>libsForQt5.mauikit-terminal (plasma5Packages.mauikit-terminal)</li>
    <li>libsForQt5.mauikit-texteditor (plasma5Packages.mauikit-texteditor)</li>
    <li>libsForQt5.mauiman (plasma5Packages.mauiman)</li>
    <li>libsForQt5.nota (plasma5Packages.nota)</li>
    <li>libsForQt5.pix (plasma5Packages.pix)</li>
    <li>libsForQt5.shelf (plasma5Packages.shelf)</li>
    <li>libsForQt5.station (plasma5Packages.station)</li>
    <li>libsForQt5.vvave (plasma5Packages.vvave)</li>
  </ul>
</details>

**Comment by wegank** [comment]
Blocked by Nitrux/maui-shell#56.

**Comment by dotlambda** [comment]
@wegank How did you generate the update? I wonder why https://github.com/NixOS/nixpkgs/pull/255572 has a bigger diff but I guess some projects were only removed after you made this PR.

**Comment by wegank** [comment]
From what I remember, I fixed and ran the update script, then manually adjusted the generated file.

**Comment by dotlambda** [comment]
I think we should simply mark maui-shell broken.

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 252528` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>maui-shell</li>
  </ul>
</details>
<details>
  <summary>18 packages built:</summary>
  <ul>
    <li>libsForQt5.booth (plasma5Packages.booth)</li>
    <li>libsForQt5.buho (plasma5Packages.buho)</li>
    <li>libsForQt5.clip (plasma5Packages.clip)</li>
    <li>libsForQt5.communicator (plasma5Packages.communicator)</li>
    <li>libsForQt5.index (plasma5Packages.index)</li>
    <li>libsForQt5.mauikit (plasma5Packages.mauikit)</li>
    <li>libsForQt5.mauikit-accounts (plasma5Packages.mauikit-accounts)</li>
    <li>libsForQt5.mauikit-calendar (plasma5Packages.mauikit-calendar)</li>
    <li>libsForQt5.mauikit-filebrowsing (plasma5Packages.mauikit-filebrowsing)</li>
    <li>libsForQt5.mauikit-imagetools (plasma5Packages.mauikit-imagetools)</li>
    <li>libsForQt5.mauikit-terminal (plasma5Packages.mauikit-terminal)</li>
    <li>libsForQt5.mauikit-texteditor (plasma5Packages.mauikit-texteditor)</li>
    <li>libsForQt5.mauiman (plasma5Packages.mauiman)</li>
    <li>libsForQt5.nota (plasma5Packages.nota)</li>
    <li>libsForQt5.pix (plasma5Packages.pix)</li>
    <li>libsForQt5.shelf (plasma5Packages.shelf)</li>
    <li>libsForQt5.station (plasma5Packages.station)</li>
    <li>libsForQt5.vvave (plasma5Packages.vvave)</li>
  </ul>
</details>

**Review by dotlambda — CHANGES_REQUESTED** [review]
Booth fails with
```
qrc:/views/CameraPage.qml:15:1: module "org.kde.prison.scanner" is not installed
```
Shelf fails with
```
qrc:/views/Viewer/Viewer.qml:8:1: module "org.mauikit.documents" is not installed
```

**Comment by wegank** [comment]
These are not regressions caused by this PR, I think?

**Comment by dotlambda** [comment]
> These are not regressions caused by this PR, I think?

True, but they aren't hard to fix.

**Review by dotlambda — APPROVED** [review]

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 252528` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>maui-shell</li>
  </ul>
</details>
<details>
  <summary>19 packages built:</summary>
  <ul>
    <li>libsForQt5.booth (plasma5Packages.booth)</li>
    <li>libsForQt5.buho (plasma5Packages.buho)</li>
    <li>libsForQt5.clip (plasma5Packages.clip)</li>
    <li>libsForQt5.communicator (plasma5Packages.communicator)</li>
    <li>libsForQt5.index (plasma5Packages.index)</li>
    <li>libsForQt5.mauikit (plasma5Packages.mauikit)</li>
    <li>libsForQt5.mauikit-accounts (plasma5Packages.mauikit-accounts)</li>
    <li>libsForQt5.mauikit-calendar (plasma5Packages.mauikit-calendar)</li>
    <li>libsForQt5.mauikit-documents (plasma5Packages.mauikit-documents)</li>
    <li>libsForQt5.mauikit-filebrowsing (plasma5Packages.mauikit-filebrowsing)</li>
    <li>libsForQt5.mauikit-imagetools (plasma5Packages.mauikit-imagetools)</li>
    <li>libsForQt5.mauikit-terminal (plasma5Packages.mauikit-terminal)</li>
    <li>libsForQt5.mauikit-texteditor (plasma5Packages.mauikit-texteditor)</li>
    <li>libsForQt5.mauiman (plasma5Packages.mauiman)</li>
    <li>libsForQt5.nota (plasma5Packages.nota)</li>
    <li>libsForQt5.pix (plasma5Packages.pix)</li>
    <li>libsForQt5.shelf (plasma5Packages.shelf)</li>
    <li>libsForQt5.station (plasma5Packages.station)</li>
    <li>libsForQt5.vvave (plasma5Packages.vvave)</li>
  </ul>
</details>

**Pull request merged**
