### PR TITLE
linux: FB_SIMPLE

### PR DESCRIPTION
**Pull request by ethorsoe**
###### Motivation for this change
linux-5.14.12 compile fails

```
GOT: Symbol: FB_SIMPLE [=n]
GOT: Type  : tristate
GOT: Defined at drivers/video/fbdev/Kconfig:2193
GOT:   Prompt: Simple framebuffer support
GOT:   Depends on: HAS_IOMEM [=y] && FB [=y] && !DRM_SIMPLEDRM [=m]
GOT:   Location:
GOT:     -> Device Drivers
GOT:       -> Graphics support
GOT:         -> Frame buffer Devices
GOT:           -> Support for frame buffer devices (FB [=y])
GOT: Selects: FB_CFB_FILLRECT [=y] && FB_CFB_COPYAREA [=y] && FB_CFB_IMAGEBLIT [=y]
GOT: 
GOT: 
GOT: 
QUESTION:   Simple framebuffer support, NAME: FB_SIMPLE, ALTS: N/m/?, ANSWER: y
repeated question:   Simple framebuffer support at /nix/store/hsqv1hp0c7vi7hdknanhk0b5rq16r7zn-generate-config.pl line 88.
```

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by samueldr** [comment]
We had a chat on Matrix.

This change alone is inadequate since this conflict represents a **huge** change with how upstream Linux wants to handle framebuffers.

Context:

 - https://lore.kernel.org/all/20210430105840.30515-1-tzimmermann@suse.de/
 - https://github.com/torvalds/linux/blame/d999ade1cc86cd2951d41c11ea769cb4452c8811/drivers/gpu/drm/tiny/Kconfig#L54-L68
 - https://github.com/torvalds/linux/blob/master/drivers/firmware/Kconfig#L224-L249

With 5.14 alone, `simplefb` is the only driver being left behind with this change.

Starting with 5.15, `efifb` and `vesafb` will share this common implementation.

We have two way forwards:

 - Being conservative and not using `DRM_SIMPLEDRM` at all, or at least until judged correct.
 - Jump feet first into the future and start using `DRM_SIMPLEDRM=y` as a replacement ASAP, and use `SYSFB_SIMPLEFB` with 5.15+.

I would advocate with following what upstream does here. Though note that we'd need to unconditionally enable those options with `=y` on all platforms (when the option is available). Reading from the cover letter of the change it's likely to be a desirable change all the way.

**Comment by samueldr** [comment]
This might be an issue:

 - https://github.com/NixOS/nixpkgs/blob/e90bc337f0151c52c14a0f8d7c25e8c95d35bd9e/nixos/modules/profiles/all-hardware.nix#L62-L63

We'll need to apply this only for older than 5.14 kernels.

**Comment by samueldr** [comment]
And relatedly... `DRM_SIMPLEDRM` can't be `=y` (I think it's because `DRM` is `=m`)...

So we **must** rely on modules in stage-1, but modules in stage-1 are now "unreliable" to refer to as they break the build too easily as you can't trivially say "add this module if possible" or "fail when this other module is not available"... It's always all or nothing.

**Comment by flokli** [comment]
It's `CONFIG_DRM_SIMPLEDRM` being `M` enforcing `FB_SIMPLE` to be `M`.

This was introduced in ec7cc3f74b4236860ce612656aa5be7936d1c594:

```
   Configurations with both CONFIG_FB_SIMPLE=y and CONFIG_DRM_SIMPLEDRM=m
    are allowed by Kconfig because the 'depends on !DRM_SIMPLEDRM' dependency
    does not disallow FB_SIMPLE as long as SIMPLEDRM is not built-in. This
    can however result in a build failure when cfb_fillrect() etc are then
    also in loadable modules:
    […]
```

**Comment by samueldr** [comment]
This is what I think the fix should be:

 - https://github.com/samueldr/nixpkgs/commit/92d9068052260ef30ac08b89af453cce02b1c24f

Using this branch:

 - https://github.com/samueldr/nixpkgs/commits/wip/simplefb-testing

I verified that the upcoming changes around the area with 5.15 don't cause undesirable changes on AArch64 and x86_64 using (for AArch64):

```
 $ nix-build -A pkgsCross.aarch64-multiplatform.linux_testing.configfile
```

And equivalent other linux variants.

**Comment by jkarlson** [comment]
How about releasing 21.11 with FB_SIMPLE=y only and working out migration with 22.05/unstable?

**Comment by samueldr** [comment]
@jkarlson that's kind of what I'm suggesting here.

Whatever change is going to happen to support `DRM_SIMPLEDRM` can happen whenever.

The change I proposed in my last comment is to use `FB_SIMPLE=y` to keep the current status quo behaviour.

**Review by samueldr — APPROVED** [review]

**Comment by Ma27** [comment]
I'm quite embarrassed, but I realized quite late that we're also having these issues on 21.05 (i.e. LInux 5.14/5.15 are not compiling there).

Since I'm lacking a bit of context in here, is this worth backporting (or does it even make sense to do so)? :)

**Comment by samueldr** [comment]
Probably a good idea to backport. Makes sense even if it's soon EOL, but just barely (in time).

**Pull request merged**
