### PR TITLE
python3.pkgs.setuptools-git-versioning: init at 1.13.5

### PR DESCRIPTION
**Pull request by tjni**
## Description of changes

This is used by several projects as a build-time dependency, and I would like to package it to give us options about how we should handle those cases. I did see https://github.com/dolfinus/setuptools-git-versioning/issues/77, and I'm not sure what the best way is yet.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by natsukium** [comment]
@ofborg build python310Packages.setuptools-git-versioning

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 248019` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python311Packages.setuptools-git-versioning</li>
    <li>python311Packages.setuptools-git-versioning.dist</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python310Packages.setuptools-git-versioning</li>
    <li>python310Packages.setuptools-git-versioning.dist</li>
  </ul>
</details>

**Comment by natsukium** [comment]
```
error: builder for '/nix/store/kwriig3zcm1jq3x4qkfx2dg20yblzkk8-python3.11-setuptools-git-versioning-1.13.5.drv' failed with exit code 4;
       last 10 log lines:
       > Check whether the following modules can be imported: setuptools_git_versioning
       > pytestCheckPhase
       > Executing pytestCheckPhase
       > ImportError while loading conftest '/build/source/tests/conftest.py'.
       > tests/conftest.py:7: in <module>
       >     from tests.lib.util import create_file, execute, rand_str
       > tests/lib/util.py:13: in <module>
       >     import toml
       > E   ModuleNotFoundError: No module named 'toml'
```

**Comment by tjni** [comment]
Good catch, I didn't test it on Python 3.11. I can fix this upstream.

**Comment by tjni** [comment]
Oh, it uses `toml` in tests to write, which is not in the Python 3.11 standard library. So we've got to add the dependency in our derivation.

**Comment by natsukium** [comment]
> I'm building the whole bootstrap right now from staging.

Sounds like hard work. 😵

**Comment by tjni** [comment]
> Sounds like hard work. 😵

For my computer 🥲

**Comment by tjni** [comment]
I verified that the tests pass on Python 3.11 now after adding `toml` to `nativeCheckInputs`. Let's kick it off again:

@ofborg build python310Packages.setuptools-git-versioning python311Packages.setuptools-git-versioning

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 248019` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python310Packages.setuptools-git-versioning</li>
    <li>python310Packages.setuptools-git-versioning.dist</li>
    <li>python311Packages.setuptools-git-versioning</li>
    <li>python311Packages.setuptools-git-versioning.dist</li>
  </ul>
</details>

**Review by natsukium — APPROVED** [review]

**Pull request merged**
