### PR TITLE
gegl_0_4: 0.4.26 → 0.4.28

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
﻿NEWS: https://gitlab.gnome.org/GNOME/gegl/-/commit/91ace253930a83874f30a1d13e0ea5bbc2e5174c
Changes: https://gitlab.gnome.org/GNOME/gegl/-/compare/GEGL_0_4_26...GEGL_0_4_28

- New dependency maxflow.
- dot path has been briefly hardcoded added (https://gitlab.gnome.org/GNOME/gegl/-/commit/5ac40e3c3f9ab25b1208a96a8fdcae6fd72958ef) but then it was switched back to finding it on PATH (https://gitlab.gnome.org/GNOME/gegl/-/commit/1f50456de59c686941a861d299a63bfcd4126ee5). Given that it is optional dependency only needed for debugging and graphviz is big, I have decided not to hardcode it in a patch.

cc @tadfisher

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 116478` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
4 packages marked as broken and skipped:
</summary>
<ul>
<li>gimpPlugins.exposureBlend</li>
<li>gimpPlugins.texturize</li>
<li>glimpsePlugins.exposureBlend</li>
<li>glimpsePlugins.texturize</li>
</ul>
</details>
<details>
<summary>
23 packages built:
</summary>
<ul>
<li>gegl_0_4 (gnome3.gegl_0_4)</li>
<li>gimp (gimpPlugins.gimp)</li>
<li>gimp-with-plugins</li>
<li>gimpPlugins.farbfeld</li>
<li>gimpPlugins.fourier</li>
<li>gimpPlugins.gap</li>
<li>gimpPlugins.gimplensfun</li>
<li>gimpPlugins.gmic (glimpsePlugins.gmic)</li>
<li>gimpPlugins.lightning</li>
<li>gimpPlugins.lqrPlugin</li>
<li>gimpPlugins.resynthesizer</li>
<li>gimpPlugins.waveletSharpen</li>
<li>glimpse (glimpsePlugins.gimp)</li>
<li>glimpse-with-plugins</li>
<li>glimpsePlugins.farbfeld</li>
<li>glimpsePlugins.fourier</li>
<li>glimpsePlugins.gap</li>
<li>glimpsePlugins.gimplensfun</li>
<li>glimpsePlugins.lightning</li>
<li>glimpsePlugins.lqrPlugin</li>
<li>glimpsePlugins.resynthesizer</li>
<li>glimpsePlugins.waveletSharpen</li>
<li>gnome-photos (gnome3.gnome-photos)</li>
</ul>
</details>

**Comment by rmcgibbo** [comment]
You beat r-rmcgibbo by 15 minutes. LGTM too (built fine on both aarch64 and x86-64 for me).

**Comment by emmanuelrosa** [comment]
This change is causing a runtime issue with GIMP A dialog box appears with the following message:

```
GEGL operation missing!

GIMP requires the GEGL operation "gegl:introspect".
This operation cannot be found. Check your
GEGL install and ensure it has been compiled
with any dependencies required for GIMP.
```

I used `git bisect` to locate the commit and `nix run nixpkgs.gimp --command gimp` to test:

```
git bisect start
# good: [7fcc4a8a84d6a6a1b07c0e375d55e991749e786d] Merge pull request #115990 from r-ryantm/auto-update/helm
git bisect good 7fcc4a8a84d6a6a1b07c0e375d55e991749e786d
# bad: [623851e197da048a7130969cf6cdc5ab134419ed] Merge pull request #115669 from r-ryantm/auto-update/turbovnc
git bisect bad 623851e197da048a7130969cf6cdc5ab134419ed
# good: [54fe2547f92aa6f40d1bbd9ba89752a8e3a93f9b] Merge pull request #116194 from r-ryantm/auto-update/shipyard
git bisect good 54fe2547f92aa6f40d1bbd9ba89752a8e3a93f9b
# good: [7d804ec1692d96c3810710098849531d8ca81d4d] k6: 0.30.0 -> 0.31.0
git bisect good 7d804ec1692d96c3810710098849531d8ca81d4d
# good: [4d56318fcaf4046e62eb1b1177e584db994f2ade] Merge pull request #116389 from r-ryantm/auto-update/MIDIVisualizer
git bisect good 4d56318fcaf4046e62eb1b1177e584db994f2ade
# good: [2926759b15bfd2c8805915a016ca0351c422c81c] Merge pull request #116309 from primeos/ungoogled-chromium
git bisect good 2926759b15bfd2c8805915a016ca0351c422c81c
# bad: [cbd71a8732f4f635a4742876cfccbf5b7b3f9544] Merge pull request #116343 from nh2/onlyoffice-bin
git bisect bad cbd71a8732f4f635a4742876cfccbf5b7b3f9544
# bad: [0bda4788f0f1694e8f4b8a075cdb63f59d442bb5] Merge pull request #116478 from jtojnar/gegl-0.4.28
git bisect bad 0bda4788f0f1694e8f4b8a075cdb63f59d442bb5
# good: [8989d8f457875bbf62c12cdbde8a8658c1e26a4b] Merge pull request #116137 from AndersonTorres/new-xa
git bisect good 8989d8f457875bbf62c12cdbde8a8658c1e26a4b
# good: [84b4bd544e8ef024a834f62a51529a5ef8860a6f] Merge pull request #116470 from davidak/jbidwatcher
git bisect good 84b4bd544e8ef024a834f62a51529a5ef8860a6f
# bad: [f63098a9c52fe7e93dba3af880e8fe714d86935c] gegl_0_4: 0.4.26 → 0.4.28
git bisect bad f63098a9c52fe7e93dba3af880e8fe714d86935c
# first bad commit: [f63098a9c52fe7e93dba3af880e8fe714d86935c] gegl_0_4: 0.4.26 → 0.4.28
```

**Comment by jtojnar** [comment]
Are you doing any specific actions? The introspect action should only appear in unstable releases and I cannot reproduce it on de4012ac80d.

**Comment by Synthetica9** [comment]
I also bisected it and came to this same PR. I don't think I'm doing anything specific?

**Comment by jtojnar** [comment]
Sorry, I had dot in the environment. https://github.com/NixOS/nixpkgs/pull/116787 should fix that.

**Pull request merged**
