### PR TITLE
google-cloud-sdk: 268.0.0 -> 281.0.0

### PR DESCRIPTION
**Pull request by leigh-perry**
###### Motivation for this change

Bring in GCP fix for python error in bq tool.

### CODE REVIEW

**Comment by artemist** [comment]
Thanks for contributing! This currently breaks building on macOS, since it's trying to fetch an updated version but expecting the old hash. Can you change the hash to `0hg4823dlnf9ahqh9dr05wsi6cdxn9mbwhg65jng3d2aws3ski6r` on line 24?

**Comment by leigh-perry** [comment]
@artemist I have made the requested change. Thanks for your help and patience

**Review by jonringer — COMMENTED** [review]
please squash commits

**Comment by leigh-perry** [comment]
PR closed to recreate with single commit

**Pull request closed without merging**
