### PR TITLE
freetube: use current Electron

### PR DESCRIPTION
**Pull request by dscottboggs**
## Description of changes
I'm not really sure what changed, I just started getting an error when trying to build my system that says that Electron 22 is EOL.

## Things done
Bump Electron version to 27

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kirillrdy** [comment]
@dscottboggs  greetings !
can you please update commit message and PR title to match contribution guidelines https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md

also, is it possible not pining electron and just use latest ? I am not that across breakages in electron land

**Comment by dscottboggs** [comment]
Thanks for the advice, @kirillrdy, is this better?

**Comment by dscottboggs** [comment]
CC: @ryneeverett @alyaeanyx as maintainers of this package

**Comment by alyaeanyx** [comment]
The pin to _22 was intentional, see https://github.com/NixOS/nixpkgs/pull/252061. Can you pin this to _27 instead? (Upstream is on 27.0.2 rn)

**Comment by dscottboggs** [comment]
That was what I originally was trying to do. Not sure if the `-bin` is a problem.

Also that means that since 27 is not in 23.05 that this will not be able to be backported.

Since the bug seems to have to do with Wayland I feel that I should note that I only tested it (so far) on X11

**Comment by kirillrdy** [comment]
duplicate of https://github.com/NixOS/nixpkgs/pull/264084 sorry I didn't spot it.  @dscottboggs feel free to continue with your PR

**Comment by kirillrdy** [comment]
@dscottboggs appologies, looks like we will  continue in https://github.com/NixOS/nixpkgs/pull/264084 after all

**Comment by dscottboggs** [comment]
That's fine with me. Thanks.

**Pull request closed without merging**
