### PR TITLE
vaultwarden: Add update script to keep web vault in sync

### PR DESCRIPTION
**Pull request by mweinelt**
- Adds an update script to fetch the compatible web vault version
- Removes `vaultwarden-vault` from top-level to prevent independent
  updates through e.g. r-ryantm. Istead the vault is now accessible
  at `vaultwarden.vault`.
- Downgrade `vaultwarden.vault` to 2022.10.0, see https://github.com/dani-garcia/vaultwarden/releases/tag/1.26.0
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
@ofborg test vaultwarden

**Comment by Mic92** [comment]
Did we had this vaultwarden in the old release already?

**Comment by mweinelt** [comment]
We have 1.26.0 in release-22.11, paired with webvault 2022.6.2. The update was stuck because it failed the nixos tests.

https://github.com/NixOS/nixpkgs/pull/206098

**Comment by dotlambda** [comment]
> * Downgrade `vaultwarden.vault` to 2022.10.0, see https://github.com/dani-garcia/vaultwarden/releases/tag/1.26.0

Can a newer frontend actually cause incompatibilities? I'd think it's just another client that sends JSON to the server and Vaultwarden is definitely compatible with multiple versions of the desktop client.

**Comment by mweinelt** [comment]
Whether new frontend versions break gracefully or not I don't know.

**Pull request merged**
