### PR TITLE
nixos/paperless: use toShellVars for paperless-manage

### PR DESCRIPTION
**Pull request by Atemu**
The homebrewed snippet didn't escape vars properly which is an issue because PAPERLESS_OCR_USER_ARGS requires a JSON string. This also meant a discrepancy between the services' env vars and paperless-manage's.

Just use the correctly functioning library function for this instead.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by leona-ya** [comment]
In #242084 is some discussion about the same issue. We have to decide which approach we want to use.
I like the approach here more, but I think we should include the added docs from the PR (not strong opinion)

**Comment by erikarvstedt** [comment]
> should include the added docs from 

The env of the `manage` script must equal the env of the services. This is the default, expected case and thus needs no extra comment.

**Comment by Atemu** [comment]
The doc from the other PR is only necessary because it still doesn't quote shell vars correctly. toShellVars does.

The hint about using toJSON would be a handy addition though.

**Comment by erikarvstedt** [comment]
> The hint about using toJSON would be a handy addition though.

Ah, sorry, that's what @leona-ya probably meant. Yes, this should be included. Here's the [version from my fixup](https://github.com/erikarvstedt/nixpkgs/commit/7ada032f667bc0e99045a7f51e37513b89ab3ff4).

**Comment by leona-ya** [comment]
Oh yes, that's what I meant. I'm sorry that was imprecise

**Comment by Atemu** [comment]
Any further objections?

**Comment by erikarvstedt** [comment]
@Atemu, tbh, I'd prefer to avoid the pessimized loop over `env`, given Nix' performance issues.
Alternative:
```nix
manage = pkgs.writeShellScript "manage" ''
   ${lib.concatStringsSep "\n" (mapAttrsToList (name: val: "export ${name}=${escapeShellArg val}") env)}
   exec ${pkg}/bin/paperless-ngx "$@"
'';
```
This avoids:
- The `isValidPosixName` regex check. All var names that paperless accepts are POSIX compatible.
- The value type checks. These are always strings. (We should change `extraConfig.type` to `attrsOf str`).

Weak preference, so I'm fine with ACKing this PR as it is.

**Review by erikarvstedt — APPROVED** [review]
Let's get this merged.

**Comment by mweinelt** [comment]
> We need the verdict of a senior Nixer. @mweinelt, can you help us out?

Slight preference for easier to read code in this case.

**Comment by Atemu** [comment]
Thanks!

**Pull request merged**
