### PR TITLE
appimageTools: remove python2 from FHS env

### PR DESCRIPTION
**Pull request by dotlambda**
Motivated by https://github.com/NixOS/nixpkgs/pull/201859. 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Atemu — CHANGES_REQUESTED** [review]
Why was python2 in here and why can we now remove it without breaking packages?

Please add that info to the commit message.

**Comment by dotlambda** [comment]
> Why was python2 in here and why can we now remove it without breaking packages?

I don't know why it was there or whether this breaks anything.

**Comment by Atemu** [comment]
They were copied out of the Steam FHS by @tilpner in the initial implementation.

I'd say we just drop python2 from the closure entirely and see if anyone complains. They can then add it to their specific package only.

**Comment by SuperSandro2000** [comment]
currently running a nixpkgs-review

**Comment by Artturin** [comment]
nixpkgs-review probably won't reveal anything because there's barely any tests in packages that use fhs env

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 202767` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>appimage-run-tests</li>
  </ul>
</details>
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>flexoptix-app</li>
    <li>polypane</li>
    <li>remnote</li>
  </ul>
</details>
<details>
  <summary>69 packages built:</summary>
  <ul>
    <li>Sylk</li>
    <li>altair</li>
    <li>anytype</li>
    <li>appimage-run</li>
    <li>beekeeper-studio</li>
    <li>betterdiscord-installer</li>
    <li>bloomrpc</li>
    <li>bootstrap-studio</li>
    <li>buttercup-desktop</li>
    <li>caprine-bin</li>
    <li>chrysalis</li>
    <li>cider</li>
    <li>cozy-drive</li>
    <li>crypto-org-wallet</li>
    <li>davinci-resolve</li>
    <li>devdocs-desktop</li>
    <li>electron-mail</li>
    <li>electronplayer</li>
    <li>firefly-desktop</li>
    <li>fluent-reader</li>
    <li>framesh</li>
    <li>fspy</li>
    <li>irccloud</li>
    <li>joplin-desktop</li>
    <li>keeweb</li>
    <li>lbry</li>
    <li>ldtk</li>
    <li>ledger-live-desktop</li>
    <li>lens</li>
    <li>losslesscut-bin</li>
    <li>lunar-client</li>
    <li>marktext</li>
    <li>mathpix-snipping-tool</li>
    <li>mobilecoin-wallet</li>
    <li>molotov</li>
    <li>museeks</li>
    <li>mycrypto</li>
    <li>neo4j-desktop</li>
    <li>notable</li>
    <li>notion-app-enhanced</li>
    <li>nuclear</li>
    <li>octant-desktop</li>
    <li>p3x-onenote</li>
    <li>passky-desktop</li>
    <li>plexamp</li>
    <li>radicle-upstream</li>
    <li>rambox-pro</li>
    <li>raven-reader</li>
    <li>saleae-logic-2</li>
    <li>session-desktop</li>
    <li>sonixd</li>
    <li>ssb-patchwork</li>
    <li>standardnotes</li>
    <li>station</li>
    <li>steam-rom-manager</li>
    <li>timeular</li>
    <li>trezor-suite</li>
    <li>tusk</li>
    <li>uhk-agent</li>
    <li>uhk-udev-rules</li>
    <li>unityhub</li>
    <li>via</li>
    <li>vial</li>
    <li>wootility</li>
    <li>youtube-music</li>
    <li>ytmdesktop</li>
    <li>zecwallet-lite</li>
    <li>zettlr</li>
    <li>zulip</li>
  </ul>
</details>

**Review by SuperSandro2000 — APPROVED** [review]

**Pull request merged**
