### PR TITLE
libimagequant: init at 2.12.1

### PR DESCRIPTION
**Pull request by sphaugh**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by srhb** [comment]
Are you interested in taking up maintainership of this addition?

**Comment by ma9e** [comment]
@srhb done :)

**Comment by srhb** [comment]
@GrahamcOfBorg build libimagequant

**Comment by srhb** [comment]
Looks like the configure script needs some fixing up (patchShebangs at least) in order to work with sandboxing on.

**Comment by ma9e** [comment]
@GrahamcOfBorg build libimagequant

**Comment by srhb** [comment]
Thanks!

**Pull request merged**
