### PR TITLE
uwsm: 0.17.0 -> 0.17.2, fix paths and deps by wrapping the binaries

### PR DESCRIPTION
**Pull request by JohnRTitor**
## Description of changes

- uwsm: 0.17.0 -> 0.17.2 (https://github.com/Vladimir-csp/uwsm/compare/v0.17.0...v0.17.2)
- Add essential dependencies
- Add sway and hyprland support (disabled by default). This is first step towards a NixOS module

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by kai-tub** [comment]
Hey @JohnRTitor.
I am happy to see that you have followed my discussions over at the [uwsm](https://github.com/Vladimir-csp/uwsm/pull/34) repo and have taken it as an inspiration to make the PR.

But I would've liked it if you could've waited maybe a bit longer before opening this PR, as my main goal was to first create a solid flake and shake all of the bugs out before pushing it into nixpkgs. Ideally, while discussing possible upstream changes and learning from other Nixpkgs Wayland modules. :/

Second, if you copy my patches and request a review from me, it has a bitter taste since you only add yourself as the maintainer & do not add me as a co-author to the init commit.

But moving on. Please have a look at my `draft` branch on [uwsm-nix](https://github.com/kai-tub/uwsm-nix/tree/draft).
I have added NixOS module tests in `flake.nix` that check if hyprland, sway & wayfire correctly boot.

In `module.nix` I have created the module implementation with quite a bit of comments about my reasoning (+ quite some out-dated and messy information but I wasn't really planning on sharing it yet, sorry for that).

The TL;DR is: I would like to avoid _injecting_ the different Wayland packages into `uwsm` wrapper. Apart from the additional derivations (for each activated compositor one), the big issue is that it might point to the _wrong_ package. If you have a look at the `wayfire` or `sway` module, you will see that the actual package isn't `pkgs.sway` but rather a module with custom overlays applied to it https://github.com/NixOS/nixpkgs/blob/5ad6a14c6bf098e98800b091668718c336effc95/nixos/modules/programs/wayland/sway.nix#L17-L38

To get access to the _real_ packages, you need to access [services.displayManager.sessionPackages](https://github.com/NixOS/nixpkgs/blob/0c53b6b8c2a3e46c68e04417e247bba660689c9d/nixos/modules/services/display-managers/default.nix#L188C5-L188C40) (if I understand it correctly).

In my most recent iteration, I have avoided this issue by simply injecting all of the `sessionPackages` (including my newly build uwsm-based ones) into the `systemd.user.extraConfig` 

https://github.com/kai-tub/uwsm-nix/blob/cea3b709c4dfdddaaec9d66a8f0f6d5c20edf16b/nix/module.nix#L130-L134

as it was done in #320737. Ahhh. But I see that you are working on an alternative solution in #322000, nice!

But yeah, simply calling the full path would be easiest, but _is not_ supported by `uswm`.
If https://github.com/Vladimir-csp/uwsm/issues/35 does get resolved, there might be a way to simply use the "default" desktop entry files.

I have changed it locally to calling the `.desktop` files instead without the systemd modification and it _seems_ to work. But as I couldn't fully grasp the `uwsm` code and wasn't sure if it would break in the future, I asked the question in https://github.com/Vladimir-csp/uwsm/issues/35 ;)

**Comment by JohnRTitor** [comment]
> But I would've liked it if you could've waited maybe a bit longer before opening this PR, as my main goal was to first create a solid flake and shake all of the bugs out before pushing it into nixpkgs. Ideally, while discussing possible upstream changes and learning from other Nixpkgs Wayland modules. :/

I'll mark it as draft then, thanks.

> Second, if you copy my patches and request a review from me, it has a bitter taste since you only add yourself as the maintainer & do not add me as a co-author to the init commit.

Sorry, I did not know about your patches and your work when "`init`ing" `uwsm` package. I'll add you as a co-maintainer here (was waiting for bit of a response on your side).

> But moving on. Please have a look at my `draft` branch on [uwsm-nix](https://github.com/kai-tub/uwsm-nix/tree/draft). I have added NixOS module tests in `flake.nix` that check if hyprland, sway & wayfire correctly boot.

Sure.

**Comment by JohnRTitor** [comment]
> The TL;DR is: I would like to avoid _injecting_ the different Wayland packages into `uwsm` wrapper. Apart from the additional derivations (for each activated compositor one), the big issue is that it might point to the _wrong_ package. If you have a look at the `wayfire` or `sway` module, you will see that the actual package isn't `pkgs.sway` but rather a package with custom overlays applied to it

I have thought about this before and I was thinking of using `config.programs.hyprland.package` (as people like to override the options, like using from a flake) as the inputs but as you pointed out that is not enough and might still point to "different" package.

> as it was done in #320737. Ahhh. But I see that you are working on an alternative solution in #322000, nice!

#322000 does not apply on wayland sessions at all. It only affects xsession wrapper that NixOS uses. I am not working on it anymore, if anyone wants to pick that up, they have my approval.

---

My setup in https://github.com/JohnRTitor/nix-conf/tree/d7ddbdc3753369d8ec69587ae2de4f5d04ded899/modules-overlays/uwsm (based on your work), works for me as of now (for those who have been following the discussion so far). But obviously this is not ready yet to be upstreamed to nixpkgs.

I will wait for you to make the PR.

**Comment by kai-tub** [comment]
Hey, thank you very much for the changes!

> I have thought about this before and I was thinking of using config.programs.hyprland.package (as people like to override the options, like using from a flake) as the inputs but as you pointed out that is not enough and might still point to "different" package.

Yeah, that's sadly not the way to go :/ 

> I will wait for you to make the PR.

If we exclude the "package" injection in this PR, I believe that it could/should still be merged. :+1:

Depending on the final solution in the module, we might be able to drop the patch in the future, but it definitely doesn't hurt.

But by PR you are referring to a PR for the NixOS module?

> Sorry, I did not know about your patches and your work when "initing" uwsm package. I'll add you as a co-maintainer here (was waiting for bit of a response on your side).

Sorry about the maintainer comment, there was no way of knowing if I wanted to be added or not. Thanks for adding me :+1:

**Comment by JohnRTitor** [comment]
@kai-tub I have removed `hyprland` and `sway` injection, should be fine now. I'll merge once you approve.

**Comment by JohnRTitor** [comment]
> But by PR you are referring to a PR for the NixOS module?

Yes.

**Comment by JohnRTitor** [comment]
I have added back `sway` and `hyprland` PATH injection back as the package still won't work without them, even if I do something like

```
uwsm start -S /run/booted-system/sw/bin/Hyprland
```

Perhaps we will find a solution in future, but for now I am inclined to keep it as a fallback.

**Pull request merged**
