### PR TITLE
libreoffice: still 7.6 -> 24.2, fresh 24.2 -> 24.8, more cleanups, more system deps

### PR DESCRIPTION
**Pull request by K900**
## Description of changes

Much flake. Very oof. Why am I doing this again.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by K900** [comment]
Result of `nixpkgs-review pr 336839` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.sunpy</li>
    <li>python311Packages.sunpy.dist</li>
  </ul>
</details>
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>odoo</li>
    <li>odoo.dist</li>
    <li>odoo16</li>
    <li>odoo16.dist</li>
    <li>powerdns-admin</li>
  </ul>
</details>
<details>
  <summary>140 packages built:</summary>
  <ul>
    <li>apacheHttpdPackages.mod_auth_mellon</li>
    <li>aqbanking</li>
    <li>authentik</li>
    <li>certbot-full</li>
    <li>frigate</li>
    <li>gnucash</li>
    <li>home-assistant-component-tests.onvif</li>
    <li>home-assistant-component-tests.totalconnect</li>
    <li>jasp-desktop</li>
    <li>kmymoney</li>
    <li>lasso</li>
    <li>lexicon (python312Packages.dns-lexicon)</li>
    <li>lexicon.dist (python312Packages.dns-lexicon.dist)</li>
    <li>libreoffice (libreoffice-still)</li>
    <li>libreoffice-collabora</li>
    <li>libreoffice-fresh</li>
    <li>libreoffice-fresh-unwrapped</li>
    <li>libreoffice-qt (libreoffice-qt-still)</li>
    <li>libreoffice-qt-fresh</li>
    <li>libreoffice-qt-fresh-unwrapped</li>
    <li>libreoffice-qt-still-unwrapped</li>
    <li>libreoffice-qt6 (libreoffice-qt6-still)</li>
    <li>libreoffice-qt6-fresh</li>
    <li>libreoffice-qt6-fresh-unwrapped</li>
    <li>libreoffice-qt6-unwrapped</li>
    <li>libreoffice-still-unwrapped</li>
    <li>mailman-web</li>
    <li>mailman-web.dist</li>
    <li>matrix-synapse</li>
    <li>matrix-synapse-plugins.matrix-synapse-ldap3</li>
    <li>matrix-synapse-plugins.matrix-synapse-ldap3.dist</li>
    <li>matrix-synapse-plugins.matrix-synapse-mjolnir-antispam</li>
    <li>matrix-synapse-plugins.matrix-synapse-mjolnir-antispam.dist</li>
    <li>matrix-synapse-plugins.matrix-synapse-s3-storage-provider</li>
    <li>matrix-synapse-plugins.matrix-synapse-s3-storage-provider.dist</li>
    <li>matrix-synapse-plugins.matrix-synapse-shared-secret-auth</li>
    <li>matrix-synapse-plugins.matrix-synapse-shared-secret-auth.dist</li>
    <li>matrix-synapse-unwrapped</li>
    <li>matrix-synapse-unwrapped.dist</li>
    <li>netbox (netbox_3_7)</li>
    <li>open-vm-tools</li>
    <li>open-vm-tools-headless</li>
    <li>open-vm-tools-headless.dev</li>
    <li>open-vm-tools.dev</li>
    <li>openscap</li>
    <li>paperless-ngx</li>
    <li>paperwork</li>
    <li>paperwork.dist</li>
    <li>peering-manager</li>
    <li>pretix</li>
    <li>pretix.dist</li>
    <li>python311Packages.certbot-dns-ovh</li>
    <li>python311Packages.certbot-dns-ovh.dist</li>
    <li>python311Packages.dj-rest-auth</li>
    <li>python311Packages.dj-rest-auth.dist</li>
    <li>python311Packages.django-allauth</li>
    <li>python311Packages.django-allauth-2fa</li>
    <li>python311Packages.django-allauth-2fa.dist</li>
    <li>python311Packages.django-allauth.dist</li>
    <li>python311Packages.django-mailman3</li>
    <li>python311Packages.django-mailman3.dist</li>
    <li>python311Packages.dns-lexicon</li>
    <li>python311Packages.dns-lexicon.dist</li>
    <li>python311Packages.drf-spectacular</li>
    <li>python311Packages.drf-spectacular.dist</li>
    <li>python311Packages.netbox-reorder-rack</li>
    <li>python311Packages.netbox-reorder-rack.dist</li>
    <li>python311Packages.onvif-zeep</li>
    <li>python311Packages.onvif-zeep-async</li>
    <li>python311Packages.onvif-zeep-async.dist</li>
    <li>python311Packages.onvif-zeep.dist</li>
    <li>python311Packages.paperwork-backend</li>
    <li>python311Packages.paperwork-backend.dist</li>
    <li>python311Packages.paperwork-shell</li>
    <li>python311Packages.paperwork-shell.dist</li>
    <li>python311Packages.pysaml2</li>
    <li>python311Packages.pysaml2.dist</li>
    <li>python311Packages.python3-saml</li>
    <li>python311Packages.python3-saml.dist</li>
    <li>python311Packages.simple-salesforce</li>
    <li>python311Packages.simple-salesforce.dist</li>
    <li>python311Packages.social-auth-app-django</li>
    <li>python311Packages.social-auth-app-django.dist</li>
    <li>python311Packages.social-auth-core</li>
    <li>python311Packages.social-auth-core.dist</li>
    <li>python311Packages.softlayer</li>
    <li>python311Packages.softlayer.dist</li>
    <li>python311Packages.total-connect-client</li>
    <li>python311Packages.total-connect-client.dist</li>
    <li>python311Packages.xmlsec</li>
    <li>python311Packages.xmlsec.dist</li>
    <li>python311Packages.zeep</li>
    <li>python311Packages.zeep.dist</li>
    <li>python312Packages.certbot-dns-ovh</li>
    <li>python312Packages.certbot-dns-ovh.dist</li>
    <li>python312Packages.dj-rest-auth</li>
    <li>python312Packages.dj-rest-auth.dist</li>
    <li>python312Packages.django-allauth</li>
    <li>python312Packages.django-allauth-2fa</li>
    <li>python312Packages.django-allauth-2fa.dist</li>
    <li>python312Packages.django-allauth.dist</li>
    <li>python312Packages.django-mailman3</li>
    <li>python312Packages.django-mailman3.dist</li>
    <li>python312Packages.drf-spectacular</li>
    <li>python312Packages.drf-spectacular.dist</li>
    <li>python312Packages.netbox-reorder-rack</li>
    <li>python312Packages.netbox-reorder-rack.dist</li>
    <li>python312Packages.onvif-zeep</li>
    <li>python312Packages.onvif-zeep-async</li>
    <li>python312Packages.onvif-zeep-async.dist</li>
    <li>python312Packages.onvif-zeep.dist</li>
    <li>python312Packages.paperwork-backend</li>
    <li>python312Packages.paperwork-backend.dist</li>
    <li>python312Packages.paperwork-shell</li>
    <li>python312Packages.paperwork-shell.dist</li>
    <li>python312Packages.pysaml2</li>
    <li>python312Packages.pysaml2.dist</li>
    <li>python312Packages.python3-saml</li>
    <li>python312Packages.python3-saml.dist</li>
    <li>python312Packages.simple-salesforce</li>
    <li>python312Packages.simple-salesforce.dist</li>
    <li>python312Packages.social-auth-app-django</li>
    <li>python312Packages.social-auth-app-django.dist</li>
    <li>python312Packages.social-auth-core</li>
    <li>python312Packages.social-auth-core.dist</li>
    <li>python312Packages.softlayer</li>
    <li>python312Packages.softlayer.dist</li>
    <li>python312Packages.total-connect-client</li>
    <li>python312Packages.total-connect-client.dist</li>
    <li>python312Packages.xmlsec</li>
    <li>python312Packages.xmlsec.dist</li>
    <li>python312Packages.zeep</li>
    <li>python312Packages.zeep.dist</li>
    <li>tandoor-recipes</li>
    <li>unoconv</li>
    <li>weblate</li>
    <li>weblate.dist</li>
    <li>weblate.static</li>
    <li>xmlsec</li>
    <li>xmlsec.dev</li>
  </ul>
</details>

**Comment by K900** [comment]
The oodos are also broken on master by some aiohttp Python 3.10 thing that I don't want to investigate. powerdns-admin is broken by distutils removal. Skipped gotenberg because that would require me to build a Chromium and I was more worried about xmlsec than Libreoffice anyway.

**Comment by 7c6f434c** [comment]
Does xmlsec update break a macOS-only patch?

**Comment by K900** [comment]
It did. I've made the patch unconditional so we catch this earlier if it breaks.

**Comment by K900** [comment]
Result of `nixpkgs-review pr 336839` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>frigate</li>
    <li>powerdns-admin</li>
  </ul>
</details>
<details>
  <summary>79 packages built:</summary>
  <ul>
    <li>certbot-full</li>
    <li>lexicon (python312Packages.dns-lexicon)</li>
    <li>lexicon.dist (python312Packages.dns-lexicon.dist)</li>
    <li>netbox (netbox_3_7)</li>
    <li>oath-toolkit</li>
    <li>paperless-ngx</li>
    <li>passExtensions.pass-otp</li>
    <li>python311Packages.certbot-dns-ovh</li>
    <li>python311Packages.certbot-dns-ovh.dist</li>
    <li>python311Packages.dj-rest-auth</li>
    <li>python311Packages.dj-rest-auth.dist</li>
    <li>python311Packages.django-allauth</li>
    <li>python311Packages.django-allauth-2fa</li>
    <li>python311Packages.django-allauth-2fa.dist</li>
    <li>python311Packages.django-allauth.dist</li>
    <li>python311Packages.dns-lexicon</li>
    <li>python311Packages.dns-lexicon.dist</li>
    <li>python311Packages.drf-spectacular</li>
    <li>python311Packages.drf-spectacular.dist</li>
    <li>python311Packages.netbox-reorder-rack</li>
    <li>python311Packages.netbox-reorder-rack.dist</li>
    <li>python311Packages.onvif-zeep</li>
    <li>python311Packages.onvif-zeep-async</li>
    <li>python311Packages.onvif-zeep-async.dist</li>
    <li>python311Packages.onvif-zeep.dist</li>
    <li>python311Packages.pysaml2</li>
    <li>python311Packages.pysaml2.dist</li>
    <li>python311Packages.python3-saml</li>
    <li>python311Packages.python3-saml.dist</li>
    <li>python311Packages.simple-salesforce</li>
    <li>python311Packages.simple-salesforce.dist</li>
    <li>python311Packages.social-auth-app-django</li>
    <li>python311Packages.social-auth-app-django.dist</li>
    <li>python311Packages.social-auth-core</li>
    <li>python311Packages.social-auth-core.dist</li>
    <li>python311Packages.softlayer</li>
    <li>python311Packages.softlayer.dist</li>
    <li>python311Packages.total-connect-client</li>
    <li>python311Packages.total-connect-client.dist</li>
    <li>python311Packages.xmlsec</li>
    <li>python311Packages.xmlsec.dist</li>
    <li>python311Packages.zeep</li>
    <li>python311Packages.zeep.dist</li>
    <li>python312Packages.certbot-dns-ovh</li>
    <li>python312Packages.certbot-dns-ovh.dist</li>
    <li>python312Packages.dj-rest-auth</li>
    <li>python312Packages.dj-rest-auth.dist</li>
    <li>python312Packages.django-allauth</li>
    <li>python312Packages.django-allauth-2fa</li>
    <li>python312Packages.django-allauth-2fa.dist</li>
    <li>python312Packages.django-allauth.dist</li>
    <li>python312Packages.drf-spectacular</li>
    <li>python312Packages.drf-spectacular.dist</li>
    <li>python312Packages.netbox-reorder-rack</li>
    <li>python312Packages.netbox-reorder-rack.dist</li>
    <li>python312Packages.onvif-zeep</li>
    <li>python312Packages.onvif-zeep-async</li>
    <li>python312Packages.onvif-zeep-async.dist</li>
    <li>python312Packages.onvif-zeep.dist</li>
    <li>python312Packages.pysaml2</li>
    <li>python312Packages.pysaml2.dist</li>
    <li>python312Packages.python3-saml</li>
    <li>python312Packages.python3-saml.dist</li>
    <li>python312Packages.simple-salesforce</li>
    <li>python312Packages.simple-salesforce.dist</li>
    <li>python312Packages.social-auth-app-django</li>
    <li>python312Packages.social-auth-app-django.dist</li>
    <li>python312Packages.social-auth-core</li>
    <li>python312Packages.social-auth-core.dist</li>
    <li>python312Packages.softlayer</li>
    <li>python312Packages.softlayer.dist</li>
    <li>python312Packages.total-connect-client</li>
    <li>python312Packages.total-connect-client.dist</li>
    <li>python312Packages.xmlsec</li>
    <li>python312Packages.xmlsec.dist</li>
    <li>python312Packages.zeep</li>
    <li>python312Packages.zeep.dist</li>
    <li>xmlsec</li>
    <li>xmlsec.dev</li>
  </ul>
</details>

**Comment by 7c6f434c** [comment]
Thank you!

**Pull request merged**
