### PR TITLE
openvpn: 2.5.8 -> 2.6.8

### PR DESCRIPTION
**Pull request by nevivurn**
## Description of changes

- [Changelog](https://github.com/OpenVPN/openvpn/blob/v2.6.8/Changes.rst)
- Added new dependencies for DCO on linux, lz4 compression

Result of `nixpkgs-review pr 268146` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>maui-shell</li>
  </ul>
</details>
<details>
  <summary>19 packages built:</summary>
  <ul>
    <li>CuboCore.coretoppings</li>
    <li>calyx-vpn</li>
    <li>connman</li>
    <li>connman-gtk</li>
    <li>connman-ncurses</li>
    <li>connmanFull</li>
    <li>connman_dmenu</li>
    <li>crowbar</li>
    <li>crowbar.dist</li>
    <li>networkmanager-openvpn (gnome.networkmanager-openvpn)</li>
    <li>ivpn-service</li>
    <li>libsForQt5.plasma-nm</li>
    <li>mullvad</li>
    <li>openvpn</li>
    <li>openvpn-auth-ldap</li>
    <li>pritunl-client</li>
    <li>protonvpn-cli_2</li>
    <li>protonvpn-cli_2.dist</li>
    <li>riseup-vpn</li>
  </ul>
</details>

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by quinn-dougherty** [comment]
Curious if this will help me with [`ivpn` and `networkmanager`](https://discourse.nixos.org/t/ivpn-disconnect-not-playing-well-with-networkmanager/36230)

**Comment by ajs124** [comment]
`nixosTests.systemd-initrd-networkd-openvpn` does not seem to evaluate right now.

Can you add some relevant nixos tests to `passthru.tests` and maybe look into fixing that test?

**Comment by nevivurn** [comment]
> `nixosTests.systemd-initrd-networkd-openvpn` does not seem to evaluate right now.
> 
> Can you add some relevant nixos tests to `passthru.tests` and maybe look into fixing that test?

Sure thing. I'll give it a try this weekend.

**Comment by nevivurn** [comment]
`nixosTests.initrd-network-openvpn` on aarch64-linux was [already failing](https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.initrd-network-openvpn.aarch64-linux) with timeout before this, so it seems unrelated with this change. Same for [`systemd-initrd-networkd-openvpn`](https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.systemd-initrd-networkd-openvpn.aarch64-linux)  In fact, it seems to have never worked at all. I can't test on those platforms, so I have disabled those platforms for now.

**Pull request merged**
