### PR TITLE
Python package updates

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

https://hydra.nixos.org/jobset/nixpkgs/python-unstable

### CODE REVIEW

**Comment by dotlambda** [comment]
Please add https://github.com/dotlambda/nixpkgs/commit/130542eb860c274d6402bfb2279853f5df7d905c

**Comment by dotlambda** [comment]
I also updated typing: dotlambda/nixpkgs@fd753e1f107a58ce18c8827124417f2317482b41
I however had to disable tests for Python 3.6. I must say I can't really follow https://github.com/python/typing/pull/280 but typing should have any effect for Python 3.5 or later anyway.
Is there a way to add typing to `buildInputs` only for Python 3.4 and below? For example by making it `null` otherwise? This could however lead to unsatisfied requirements.

**Review by dotlambda — COMMENTED** [review]
Wouldn't it make sense to remove all `name`s in the updated derivations?

**Comment by FRidh** [comment]
> Is there a way to add typing to `buildInputs` only for Python 3.4 and below? For example by making it `null` otherwise? This could however lead to unsatisfied requirements. 

```
buildInputs = [ ] ++ optionals pythonOlder "3.5" [ typing ];
```
Other solution we use mostly for backports:
```
typing = if pythonAtLeast "3.5" then null else buildPythonPackage rec { ... };
```

> Wouldn't it make sense to remove all `name`s in the updated derivations?

Feel free to create a commit that removes all of them. These updates are generated automatically.

**Comment by dotlambda** [comment]
I had already tried the second solution but that would cause packages requiring typing in their `setup.py` to fail to build. So I guess it is best left as is.

**Comment by dotlambda** [comment]
Don't you want to include the typing update?

**Comment by grahamc** [comment]
@GrahamcOfBorg eval

**Comment by FRidh** [comment]
(@grahamc vs @GrahamcOfBorg :laughing:  )

**Pull request merged**
