### PR TITLE
typora: 0.9.72 -> 0.9.73

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
Determined it uses `electron_5` by looking at the `version` file in the archive.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by ysndr** [comment]
Would not open files if not given as command line argument. This has been an issue before so this might not be a consequence of this update, sadly updating to the newer electron didn't help here.

Also the program shows errors regarding mismatching node versions hindering it from auto reloading files.

image

**Comment by worldofpeace** [comment]
I've tested this with https://github.com/NixOS/nixpkgs/pull/65916 and that issue was gone.
Can you try that @ysndr?

**Comment by ysndr** [comment]
Yes that seems to work. Fixes both the error message and opening/navigating of files and folders.
maybe other issues with typora will be fixed due to this as well but that needs more usage than I can currently afford.
Anyway I found no more obvious issues with this PR.
seems good to go @worldofpeace

**Comment by worldofpeace** [comment]
Thanks @ysndr , merging.

**Pull request merged**
