### PR TITLE
vscode-extensions: bumps

### LINKED ISSUE #246416: Update request: vscode-extensions.tamasfe.even-better-toml 0.19.0 → 0.19.2
- Package name: vscode-extensions.tamasfe.even-better-toml
- Latest released version: 0.19.2
- Current version on the unstable channel:  0.19.0
- Current version on the stable/release channel:  0.19.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@Garmelon 

-----

Note for maintainers: Please tag this issue in your PR.

### LINKED ISSUE #246418: Update request: vscode-extensions.bmalehorn.vscode-fish 1.0.33 → 1.0.35
- Package name: 1.0.35
- Latest released version: 1.0.33
- Current version on the unstable channel: 1.0.33
- Current version on the stable/release channel: 1.0.33

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@Garmelon

-----

Note for maintainers: Please tag this issue in your PR.

### LINKED ISSUE #246420: Update request: vscode-extensions.github.vscode-pull-request-github 0.66.0 → 0.69.2023072716
- Package name: vscode-extensions.github.vscode-pull-request-github
- Latest released version:
- Current version on the unstable channel:  0.66.0
- Current version on the stable/release channel:  0.64.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@Garmelon 

-----

Note for maintainers: Please tag this issue in your PR.

### LINKED ISSUE #246421: Update request: vscode-extensions.pkief.material-icon-theme 4.25.0 → 4.29.0
- Package name: vscode-extensions.pkief.material-icon-theme
- Latest released version: 4.29.0
- Current version on the unstable channel: 4.25.0
- Current version on the stable/release channel: 4.25.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@Garmelon 

-----

Note for maintainers: Please tag this issue in your PR.

### LINKED ISSUE #246422: Update request: vscode-extensions.jnoortheen.nix-ide 0.2.1 → 0.2.2
- Package name: vscode-extensions.jnoortheen.nix-ide
- Latest released version:  0.2.2
- Current version on the unstable channel: 0.2.1
- Current version on the stable/release channel: 0.2.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@Garmelon 

-----

Note for maintainers: Please tag this issue in your PR.

### LINKED ISSUE #246424: Update request: vscode-extensions.esbenp.prettier-vscode 9.19.0 → 10.1.0
- Package name: vscode-extensions.esbenp.prettier-vscode
- Latest released version: 10.1.0
- Current version on the unstable channel: 9.19.0
- Current version on the stable/release channel: 9.19.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@datafoo

-----

Note for maintainers: Please tag this issue in your PR.

### LINKED ISSUE #246427: Update request: vscode-extensions.rust-lang.rust-analyzer OLDVERSION → NEWVERSION
- Package name: vscode-extensions.rust-lang.rust-analyzer
- Latest released version: 0.4.1606
- Current version on the unstable channel: 0.3.1426
- Current version on the stable/release channel: 0.3.1426

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@malob 

-----

Note for maintainers: Please tag this issue in your PR.

### LINKED ISSUE #246428: Update request: vscode-extensions.tyriar.sort-lines 1.9.1 → 1.10.2
- Package name: vscode-extensions.tyriar.sort-lines
- Latest released version: 1.10.2
- Current version on the unstable channel: 1.9.1
- Current version on the stable/release channel: 1.9.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

### LINKED ISSUE #246430: Update request: vscode-extensions.gruntfuggly.todo-tree  0.0.224 → 0.0.226
- Package name: vscode-extensions.gruntfuggly.todo-tree
- Latest released version: 0.0.226
- Current version on the unstable channel: 0.0.224
- Current version on the stable/release channel: 0.0.224

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@rhoriguchi 

-----

Note for maintainers: Please tag this issue in your PR.

### LINKED ISSUE #246432: Update request: vscode-extensions.eamodio.gitlens 13.4.0 → 2023.7.2905
- Package name: vscode-extensions.eamodio.gitlens
- Latest released version: 2023.7.2905
- Current version on the unstable channel: 13.4.0
- Current version on the stable/release channel: 13.4.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@ratsclub

-----

Note for maintainers: Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by yoav-lavi**
## Description of changes

- vscode-extensions.eamodio.gitlens: 13.4.0 -> 14.1.1
- vscode-extensions.gruntfuggly.todo-tree: 0.0.224 -> 0.0.226
- vscode-extensions.tyriar.sort-lines: 1.9.1 -> 1.10.2
- vscode-extensions.rust-lang.rust-analyzer: 0.3.1426 -> 0.3.1607
- vscode-extensions.esbenp.prettier-vscode: 9.19.0 -> 10.1.0
- vscode-extensions.jnoortheen.nix-ide: 0.2.1 -> 0.2.2
- vscode-extensions.pkief.material-icon-theme: 4.25.0 -> 4.29.0
- vscode-extensions.github.vscode-pull-request-github: 0.66.0 -> 0.68.1
- vscode-extensions.bmalehorn.vscode-fish: 1.0.33 -> 1.0.35
- vscode-extensions.tamasfe.even-better-toml: 0.19.0 -> 0.19.2

Closes: #246432 
Closes: #246430 
Closes: #246428 
Closes: #246427 
Closes: #246424
Closes: #246422
Closes: #246421 
Closes: #246420 
Closes: #246418 
Closes: #246416

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by yoav-lavi** [comment]
@drupol perhaps you're free for a review? Thanks!

**Comment by yoav-lavi** [comment]
cc @Janik-Haag

**Review by drupol — APPROVED** [review]

**Comment by yoav-lavi** [comment]
@drupol accidentally formatted a file, fixing

**Review by drupol — APPROVED** [review]

**Comment by yoav-lavi** [comment]
@drupol in a few of the commits there's a space missing between the arrow and the version number, let me know if it should be changed. Thanks!

**Comment by yoav-lavi** [comment]
Also, not sure if any labels are missing for the PR

**Review by drupol — CHANGES_REQUESTED** [review]
Oh good catch !

Indeed, each commit message needs to be perfectly formatted.

**Comment by yoav-lavi** [comment]
@drupol fixed

**Comment by drupol** [comment]
Let's wait for the ci to verify the hashes.

**Pull request merged**
