### PR TITLE
[22.05] backport python39Packages.numba-scipy: update stale substituteInPlace

### PR DESCRIPTION
**Pull request by risicle**
###### Description of changes

~#174152 - needed to include a commit from #174720 to get arviz patch to apply.~

Backport of #174152 & #174720

This fixes several packages.

ZHF: #172160

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
```
error: builder for '/nix/store/k5j9k8lx8z19jj6h93fcjn4cqbrbw0r1-python3.10-graspologic-1.0.0.drv' failed with exit code 1;
       last 10 log lines:
       > removing build/bdist.linux-x86_64/wheel
       > Finished executing setuptoolsBuildPhase
       > installing
       > Executing pipInstallPhase
       > /build/source/dist /build/source
       > Processing ./graspologic-1.0.0-py3-none-any.whl
       > ERROR: Could not find a version that satisfies the requirement beartype>=0.10.0 (from graspologic) (from versions: none)
       > ERROR: No matching distribution found for beartype>=0.10.0
       >
       > builder for '/nix/store/k5j9k8lx8z19jj6h93fcjn4cqbrbw0r1-python3.10-graspologic-1.0.0.drv' failed with exit code 1
       For full logs, run 'nix log /nix/store/k5j9k8lx8z19jj6h93fcjn4cqbrbw0r1-python3.10-graspologic-1.0.0.drv'.
```

```
error: builder for '/nix/store/dd59iz763as2404swdaq96bnilmzq1xg-python3.9-graspologic-1.0.0.drv' failed with exit code 1;
       last 10 log lines:
       > removing build/bdist.linux-x86_64/wheel
       > Finished executing setuptoolsBuildPhase
       > installing
       > Executing pipInstallPhase
       > /build/source/dist /build/source
       > Processing ./graspologic-1.0.0-py3-none-any.whl
       > ERROR: Could not find a version that satisfies the requirement graspologic-native>=1.1.1 (from graspologic) (from versions: none)
       > ERROR: No matching distribution found for graspologic-native>=1.1.1
       >
       > builder for '/nix/store/dd59iz763as2404swdaq96bnilmzq1xg-python3.9-graspologic-1.0.0.drv' failed with exit code 1
       For full logs, run 'nix log /nix/store/dd59iz763as2404swdaq96bnilmzq1xg-python3.9-graspologic-1.0.0.drv'.
```

Has been marked broken due to missing `graspologic-native` dependency on master, but not on release-22.05

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 175286` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.pygbm</li>
    <li>python310Packages.shap</li>
    <li>python39Packages.pygbm</li>
    <li>python39Packages.shap</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python310Packages.graspologic</li>
    <li>python39Packages.graspologic</li>
  </ul>
</details>
<details>
  <summary>73 packages built:</summary>
  <ul>
    <li>python310Packages.aeppl</li>
    <li>python310Packages.aesara</li>
    <li>python310Packages.awkward</li>
    <li>python310Packages.clifford</li>
    <li>python310Packages.cppe</li>
    <li>python310Packages.dask-ml</li>
    <li>python310Packages.datashader</li>
    <li>python310Packages.fastparquet</li>
    <li>python310Packages.ffcv</li>
    <li>python310Packages.gumath</li>
    <li>python310Packages.hyppo</li>
    <li>python310Packages.intake</li>
    <li>python310Packages.intake-parquet</li>
    <li>python310Packages.librosa</li>
    <li>python310Packages.numba</li>
    <li>python310Packages.numba-scipy</li>
    <li>python310Packages.numbaWithCuda</li>
    <li>python310Packages.numdifftools</li>
    <li>python310Packages.persim</li>
    <li>python310Packages.phik</li>
    <li>python310Packages.pygmo</li>
    <li>python310Packages.pynndescent</li>
    <li>python310Packages.pyscf</li>
    <li>python310Packages.qiskit</li>
    <li>python310Packages.qiskit-machine-learning</li>
    <li>python310Packages.resampy</li>
    <li>python310Packages.ripser</li>
    <li>python310Packages.scikit-tda</li>
    <li>python310Packages.sparse</li>
    <li>python310Packages.stumpy</li>
    <li>python310Packages.stytra</li>
    <li>python310Packages.tensorly</li>
    <li>python310Packages.timezonefinder</li>
    <li>python310Packages.trackpy</li>
    <li>python310Packages.umap-learn</li>
    <li>python310Packages.uproot</li>
    <li>python39Packages.aeppl</li>
    <li>python39Packages.aesara</li>
    <li>python39Packages.awkward</li>
    <li>python39Packages.clifford</li>
    <li>python39Packages.cppe</li>
    <li>python39Packages.dask-ml</li>
    <li>python39Packages.datashader</li>
    <li>python39Packages.fastparquet</li>
    <li>python39Packages.ffcv</li>
    <li>python39Packages.gumath</li>
    <li>python39Packages.hyppo</li>
    <li>python39Packages.intake</li>
    <li>python39Packages.intake-parquet</li>
    <li>python39Packages.librosa</li>
    <li>python39Packages.numba</li>
    <li>python39Packages.numba-scipy</li>
    <li>python39Packages.numbaWithCuda</li>
    <li>python39Packages.numdifftools</li>
    <li>python39Packages.persim</li>
    <li>python39Packages.phik</li>
    <li>python39Packages.pygmo</li>
    <li>python39Packages.pynndescent</li>
    <li>python39Packages.pyscf</li>
    <li>python39Packages.qiskit</li>
    <li>python39Packages.qiskit-machine-learning</li>
    <li>python39Packages.resampy</li>
    <li>python39Packages.ripser</li>
    <li>python39Packages.scikit-tda</li>
    <li>python39Packages.sparse</li>
    <li>python39Packages.stumpy</li>
    <li>python39Packages.stytra</li>
    <li>python39Packages.tensorly</li>
    <li>python39Packages.timezonefinder</li>
    <li>python39Packages.trackpy</li>
    <li>python39Packages.umap-learn</li>
    <li>python39Packages.uproot</li>
    <li>tts</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
#### python310.pkgs.arviz

##### Before

> error: numba-0.55.1 not supported for interpreter python3.10

##### Now

```
error: builder for '/nix/store/dpfsyawij8gxysjjcg7h2c1lckprbqpd-python3.10-arviz-0.12.1.drv' failed with exit code 1;
       last 10 log lines:
       > running install tests
       > no Makefile or custom installCheckPhase, doing nothing
       > pythonCatchConflictsPhase
       > pythonRemoveBinBytecodePhase
       > pythonImportsCheckPhase
       > Executing pythonImportsCheckPhase
       > Check whether the following modules can be imported: arviz
       > Matplotlib created a temporary config/cache directory at /build/matplotlib-dr1pk2zu because the default path (/homeless-shelter/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
       > /nix/store/acjcrvqk7cz8690jh0chz6jbi2znlyx9-python-imports-check-hook.sh/nix-support/setup-hook: line 9:   422 Illegal instruction     (core dumped) /nix/store/40n9pd613v8fc3x39yjrgs1i7d4q8yl0-python3-3.10.4/bin/python3.10 -c 'import os; import importlib; list(map(lambda mod: importlib.import_module(mod), os.environ["pythonImportsCheck"].split()))'
       > builder for '/nix/store/dpfsyawij8gxysjjcg7h2c1lckprbqpd-python3.10-arviz-0.12.1.drv' failed with exit code 132
       For full logs, run 'nix log /nix/store/dpfsyawij8gxysjjcg7h2c1lckprbqpd-python3.10-arviz-0.12.1.drv'.
``

**Comment by mweinelt** [comment]
Pick 9102b1cc65c05edb0ada9b1391c942bb3862dfd4 to mark graspologic as broken.

**Comment by risicle** [comment]
Should already be #175318

**Comment by risicle** [comment]
Do you get the arviz SIGILL on master?

**Comment by mweinelt** [comment]
It just gets SIGILL on older x86_64 models, nothing we can do about that. Works on my desktop.

**Pull request merged**
