### PR TITLE
httpie: 2.6.0 -> 3.0.1

### PR DESCRIPTION
**Pull request by JesusMtnez**
###### Motivation for this change

Upgrade httpie to latest release 3.0.1

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NotGordias** [comment]
Result of `nixpkgs-review pr 156466` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>http-prompt</li>
    <li>httpie</li>
  </ul>
</details>

**Comment by NotGordias** [comment]
Posting logs from the failures:

```
error: builder for '/nix/store/sgg1s2xr356i78r344qcqk4namwqcqvj-httpie-3.0.1.drv' failed with exit code 1;
       last 10 log lines:
       > =============================== warnings summary ===============================
       > tests/test_encoding.py: 12 warnings
       > tests/test_stream.py: 8 warnings
       >   /nix/store/zvn7pcxxhxpyd3394qjc5l7l2di9gprx-python3.9-responses-0.16.0/lib/python3.9/site-packages/responses/__init__.py:396: DeprecationWarning: stream argument is deprecated. Use stream parameter in request directly
       >     warn(
       >
       > -- Docs: https://docs.pytest.org/en/stable/warnings.html
       > =========================== short test summary info ============================
       > FAILED tests/test_plugins_cli.py::test_plugins_upgrade - AssertionError: asse...
       > = 1 failed, 865 passed, 4 skipped, 9 deselected, 1 xfailed, 20 warnings in 64.05s (0:01:04) =
       For full logs, run 'nix log /nix/store/sgg1s2xr356i78r344qcqk4namwqcqvj-httpie-3.0.1.drv'.
error: 1 dependencies of derivation '/nix/store/6ydl6shcxdh83l3cyhdiv1f2x52ib59b-http-prompt-1.0.0.drv' failed to build
error: 2 dependencies of derivation '/nix/store/nyn5mxlz91pzvfr8h9j9sinpgq82sw5b-review-shell.drv' failed to build

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/156466

2 packages failed to build:
http-prompt httpie

error: build log of '/nix/store/6ydl6shcxdh83l3cyhdiv1f2x52ib59b-http-prompt-1.0.0.drv' is not available
error: build log of '/nix/store/ihb3bf0rsnk737q2c38xnjxw2za48mgw-http-prompt-1.0.0' is not available
```

**Comment by NotGordias** [comment]
Result of `nixpkgs-review pr 156466` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>http-prompt</li>
    <li>httpie</li>
  </ul>
</details>

**Review by ghost — APPROVED** [review]
Looks like a flaky test upstream, which is why the first build failed for me. A re-run fixed it. I'm not sure if/how to mark a package as "possibly has flaky test" but that seems like a useful signal for packages that depend on a test-suite that could have flaky tests.

^ Possibly out of scope for this PR? LGTM otherwise 🙂

**Comment by SuperSandro2000** [comment]
> Looks like a flaky test upstream, which is why the first build failed for me. A re-run fixed it. I'm not sure if/how to mark a package as "possibly has flaky test" but that seems like a useful signal for packages that depend on a test-suite that could have flaky tests.

Just disable/ignore the test.

---


Also there is 3.0.2 out.

**Comment by JesusMtnez** [comment]
I will open a new PR to go to 3.0.2

**Pull request closed without merging**
