### PR TITLE
[RDY] neovim: init wrapper

### PR DESCRIPTION
**Pull request by teto**
I accidentally deleted the branch on https://github.com/NixOS/nixpkgs/pull/32657 so I reopen the PR.

###### Motivation for this change
Adding a python/ruby package to the neovim environment should not trigger a neovim recompilation.
This adds a wrapper to prevent that.

###### Things done
This moves the neovim configuration (python packages/ ruby etc) to a wrapper.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by teto** [comment]
@garbas any comment ? I hack a bit on neovim and between nixops/home-manager/nixos-rebuild, I ended up rebuilding quite often.

**Comment by Nadrieril** [comment]
I would love to have this, since it also solves the problem of patching neovim when it is wrapped, which is currently impossible.

**Review by garbas — APPROVED** [review]
👍 thank you @teto

**Comment by mnacamura** [comment]
It fails on darwin because [`share/applications/nvim.desktop` is not created on darwin](https://github.com/neovim/neovim/blob/c06995b34d604a37f80ee1174fcb3530dbd59206/runtime/CMakeLists.txt#L118):
```
post-installation fixup
gzipping man pages under /nix/store/1pyacq3ac3kgxrq8ad1zj2r1sp76qqfm-neovim-unwrapped-0.2.1/share/man/
strip is /nix/store/bhfkh37smh9lc5bngdha6zx98k6w6cgd-cctools-binutils-darwin/bin/strip
stripping (with command strip and flags -S) in /nix/store/1pyacq3ac3kgxrq8ad1zj2r1sp76qqfm-neovim-unwrapped-0.2.1/bin
patching script interpreter paths in /nix/store/1pyacq3ac3kgxrq8ad1zj2r1sp76qqfm-neovim-unwrapped-0.2.1
/nix/store/1pyacq3ac3kgxrq8ad1zj2r1sp76qqfm-neovim-unwrapped-0.2.1/share/nvim/runtime/macros/less.sh: interpreter directive changed from "/bin/sh" to "/nix/store/hgsbnqhg7zr5vbjazb250ac4wnj3cfhy-bash-4.4-p12/bin/sh"
building path(s) ‘/nix/store/yx3c7cvdllakxci8pn9dxhrm328rqi8r-neovim’
substitute(): ERROR: file '/nix/store/1pyacq3ac3kgxrq8ad1zj2r1sp76qqfm-neovim-unwrapped-0.2.1/share/applications/nvim.desktop' does not exist
builder for ‘/nix/store/2p9jsn7qrxhnlp35avbqdavdm0v3wg94-neovim.drv’ failed with exit code 1
error: build of ‘/nix/store/2p9jsn7qrxhnlp35avbqdavdm0v3wg94-neovim.drv’ failed
```
@teto Could you fix this?

**Comment by teto** [comment]
Thnaks for merging. 

@mnacamura my apologies for  the inconvenience, does 
https://github.com/NixOS/nixpkgs/pull/33925 work for you ?

**Comment by mnacamura** [comment]
@teto It works fine. Thanks!

**Pull request merged**
