### PR TITLE
pkgs.path: Avoid copying when used via flake

### PR DESCRIPTION
**Pull request by roberth**
###### Motivation for this change

 - Avoid unnecessary copies of the nixpkgs sources via `pkgs.path`
 - Fix https://github.com/NixOS/nixpkgs/pull/153592 disk space regression.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by pennae** [comment]
we tried pretty much exactly this before giving up and copying subdirectories explicitly, since it doesn't seem to work:

```
locking path '/nix/store/0n8zdf8sn8hk1pdqczgczz09gf8rcx97-mf2c1hpfds2fv501d1jc6pxc07qym974-nixpkgs'
lock acquired on '/nix/store/0n8zdf8sn8hk1pdqczgczz09gf8rcx97-mf2c1hpfds2fv501d1jc6pxc07qym974-nixpkgs.lock'
'/nix/store/0n8zdf8sn8hk1pdqczgczz09gf8rcx97-mf2c1hpfds2fv501d1jc6pxc07qym974-nixpkgs/.editorconfig' has hash 'sha256:1wkj2wfy26ylp3dbrhbiw71y9fci11mbi8pj7zsdw8i1xncll2g3'
linking '/nix/store/0n8zdf8sn8hk1pdqczgczz09gf8rcx97-mf2c1hpfds2fv501d1jc6pxc07qym974-nixpkgs/.editorconfig' to '/nix/store/.links/1wkj2wfy26ylp3dbrhbiw71y9fci11mbi8pj7zsdw8i1xncll2g3'
'/nix/store/0n8zdf8sn8hk1pdqczgczz09gf8rcx97-mf2c1hpfds2fv501d1jc6pxc07qym974-nixpkgs/.git/HEAD' has hash 'sha256:0fq06xi94yqqr4snhcgax31da3rmyzd0wm6804xgks8psjgrr4wf'
[ repeat for all of nixpkgs ]
```

the only way to avoid having a redundant copy is to force the name of the resulting store path to be the same as the source store path (eg, `path { name = "source"; path = pkgs.path; }`), but that only avoid the duplication, not the copy.

**Comment by roberth** [comment]
Was that without the flake?

With the flake, it should use `outPath`, which is a string with context, so that should be efficient.
Without the flake, it defaults to a `path` is a "path value" such that `isStorePath path == false`, at least when using a local checkout. I think this is where it went wrong? Or maybe I was holding it wrong again.

I've pushed a commit. It's really kind of a flake-only optimization now, unless someone cares to set `config.path`.

**Comment by pennae** [comment]
yes, that was without flakes, we ran `nix-instantiate -vvvvv /nix/store/mf2c1hpfds2fv501d1jc6pxc07qym974-nixpkgs/nixos -A config.system.build.manual`, where the store path in there was a freshly added checkout of your branch. hadn't even checked the flake case because we remembered the non-flake case would suffer.

checked the flake case with your additional commit now though, and we still see a lot of copying happening:
```❯ nix show-derivation /nix/store/6gjsp6s79qggw0sz9lnbl2bin8lhd6pq-lazy-options.json.drv
{
  "/nix/store/6gjsp6s79qggw0sz9lnbl2bin8lhd6pq-lazy-options.json.drv": {
    "outputs": {
      "out": {
        "path": "/nix/store/za8h4fvkrnvyyrsf4936scfwq6afmad0-lazy-options.json"
      }
    },
    "inputSrcs": [
      "/nix/store/6b1v21x04fxr6w84nl8424xd2x6r304g-lib",
      "/nix/store/9krlzvny65gdc8s7kpb6lkx8cd02c25b-default-builder.sh",
      "/nix/store/an5jjcrjay229b0kfckyza3dnfif0kzh-nixos",
      "/nix/store/ns935b2vvx5i7hwmlz8c8bdxz1frhhxm-pkgs-lib"
    ],
```

not sure there's a good way to solve this if `builtins.storePath` isn't available from pure evaluations. the best we can think of right now is to inject a differentiator from the flake: if it's not present use `storePath`, if it is present pull `lazy-options.json` from a nixpkgs flake output that contains exactly the derivation required to build lazy-options

**Comment by roberth** [comment]
> ```
> "inputSrcs": [
>       "/nix/store/6b1v21x04fxr6w84nl8424xd2x6r304g-lib",
>       "/nix/store/9krlzvny65gdc8s7kpb6lkx8cd02c25b-default-builder.sh",
>       "/nix/store/an5jjcrjay229b0kfckyza3dnfif0kzh-nixos",
>       "/nix/store/ns935b2vvx5i7hwmlz8c8bdxz1frhhxm-pkgs-lib"
>     ],
> ```

This looks as expected for a non-flake eval. Without `builtins.storePath` we can't do better.

> the best we can think of right now is to inject a differentiator from the flake

That's kind of what's happening after my last commit here, except it errs on the safe side, rather than assuming pure eval is off for non-flake usage.

It's not as good as we hoped, but at least it doesn't break and is more efficient for flake users.

**Comment by pennae** [comment]
> This looks as expected for a non-flake eval.

that was a flake eval though :slightly_frowning_face:

**Comment by pennae** [comment]
test operations done to get to that conclusion:

```
nix show-derivation $(nix eval --raw .\#nixosConfigurations.$(hostname).config.system.build.manual.optionsJSON --override-input nixpkgs github:hercules-ci/nixpkgs/flake-avoid-copying-nixpkgs-path)
# find the layz-options.json drv
nix show-derivation $that_drv # here: /nix/store/zga6r1jkxbrklp25s90x8iz1nyxb96qw-lazy-options.json.drv
```

we've confirmed that the eval did use your repo, our current flake lock for the test system does not include the docs split yet

**Comment by roberth** [comment]
`pkgs` isn't a `legacyPackages`. The latest commit sets `config.path` in NixOS-initialized Nixpkgs.

**Review by pennae — COMMENTED** [review]
works as intended now :smile_cat: flakes use the existing store path, non-flakes filter parts over.

we've tried a bit whether we can `tryEval (storePath ...)`, but that's not possible. what we *can* do though is `getEnv "_" != ""` and use `storePath` if so, because `getEnv` will not fail in pure or restricted mode but simply return an empty string. we couldn't falsely detect that `storePath` is available, only that it isn't. do you think it's worth going for that too?

**Comment by pennae** [comment]
we finally got around to checking whether `getEnv` really is viable for this, and it is! :slightly_smiling_face: since `PATH` should always be set to *something* `getEnv "PATH" != ""` is a pretty good approximation of a hypothetical `isImpureEval`, so we can use `storePath` to avoid copies as well. here's a patch, we would've added it to the branch (and attempted to rebase) but that seems to be disallowed for this PR.

```patch
diff --git a/nixos/modules/misc/documentation.nix b/nixos/modules/misc/documentation.nix
index 2ecdf68293e..b850d5f9ab5 100644
--- a/nixos/modules/misc/documentation.nix
+++ b/nixos/modules/misc/documentation.nix
@@ -74,13 +74,18 @@ let
         #
         # We can only avoid copying when pkgs.path is already a string. A path
         # value can not be converted to a store path without rehashing it.
-        # builtins.storePath would be a solution but is currently off-limits
-        # because of https://github.com/NixOS/nix/issues/1888
-        #        and https://github.com/NixOS/nix/issues/5868
-        pull = dir:
-          if builtins.typeOf pkgs.path == "string" && isStorePath pkgs.path
-          then "${pkgs.path}/${dir}"
-          else filter "${toString pkgs.path}/${dir}";
+        # builtins.storePath can only be used to avoid this when impure eval is
+        # allowed, which we approximate by getEnv returning something for a
+        # variable that should always be set.
+        # see https://github.com/NixOS/nix/issues/1888
+        # and https://github.com/NixOS/nix/issues/5868
+        pull =
+          if builtins.typeOf pkgs.path == "string" && isStorePath pkgs.path then
+            dir: "${pkgs.path}/${dir}"
+          else if builtins.getEnv "PATH" != "" && isStorePath pkgs.path then
+            dir: "${builtins.storePath pkgs.path}/${dir}"
+          else
+            dir: filter "${toString pkgs.path}/${dir}";
       in
         pkgs.runCommand "lazy-options.json" {
           libPath = pull "lib";
```

**Comment by pennae** [comment]
we like this a lot. thanks for caring and for writing the extremely comprehensive comments, they're *superb* :)

**Comment by pennae** [comment]
tested it again, the copy elision seems to work fine, resulting json also looks good.

**Comment by edolstra** [comment]
Note that this makes nix-env produce a different evaluation result for a `nixpkgs` tree inside the Nix store compared to one outside of the Nix store, because the `nixos-install-tools` attribute will be different. That's an undesirable property IMHO (see https://github.com/NixOS/nixpkgs/pull/156527 and https://github.com/NixOS/nixpkgs/pull/156587). 

In general we should avoid the use of `isStorePath` on sources since they cause divergent evaluation results. Perhaps we should ensure that `builtins.isStorePath` is false for inputs to the evaluator, even when the inputs happen to be in the store.

**Comment by roberth** [comment]
I agree that this is still not a great solution. Indeed this will produce one of two different derivations depending on how the NixOS/Nixpkgs invocation was made. Perhaps the `filterSource` based invocation shouldn't be automatic? That will make the drvs reproducible again.

**Comment by roberth** [comment]
I've [reverted](#156992) this PR, as it makes already fragile code like the installer tests even more fragile.

**Pull request merged**
