### PR TITLE
geant4: 10.6.3 -> 10.7.0

### PR DESCRIPTION
**Pull request by OmnipotentEntity**
###### Motivation for this change

Updating to the latest version.  Updated datafiles as well.

Python packages don't build.  Error with Boost, and I cannot figure it out.

```
-- Found PythonLibs: /nix/store/zq4mf44s4hwvbmhkqd3bi70g2bx0q3zz-python3-3.7.9/lib/libpython3.7m.so (found version "3.7.9") 
CMake Error at /nix/store/ksfn34l2hzc6j3i0l2xialqbs7lbwzfy-cmake-3.18.4/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find Boost (missing: python) (found suitable version "1.69.0",
  minimum required is "1.65")
Call Stack (most recent call first):
  /nix/store/ksfn34l2hzc6j3i0l2xialqbs7lbwzfy-cmake-3.18.4/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /nix/store/ksfn34l2hzc6j3i0l2xialqbs7lbwzfy-cmake-3.18.4/share/cmake-3.18/Modules/FindBoost.cmake:2177 (find_package_handle_standard_args)
  environments/g4py/CMakeLists.txt:11 (find_package)
```

Assistance on that is appreciated.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by OmnipotentEntity** [comment]
@veprbl Any ideas on the python boost problem?

**Comment by veprbl** [comment]
Try:
```diff
diff --git a/pkgs/development/libraries/physics/geant4/default.nix b/pkgs/development/libraries/physics/geant4/default.nix
--- a/pkgs/development/libraries/physics/geant4/default.nix
+++ b/pkgs/development/libraries/physics/geant4/default.nix
@@ -60,8 +60,8 @@ stdenv.mkDerivation rec {
   postPatch = ''
     # Fix for boost 1.67+
     substituteInPlace environments/g4py/CMakeLists.txt \
-      --replace "find_package(Boost REQUIRED python)" \
-                "find_package(Boost REQUIRED COMPONENTS $boost_python_lib)"
+      --replace "REQUIRED python)" \
+                "REQUIRED COMPONENTS $boost_python_lib)"
     substituteInPlace environments/g4py/G4PythonHelpers.cmake \
       --replace "Boost::python" "Boost::$boost_python_lib"
   '';
```

**Comment by OmnipotentEntity** [comment]
I apologize, I've had a rather tumultuous few days.  I've given your patch a shot, and it seems to work!  Thanks so much.  I feel rather ashamed that I didn't notice that the replacement here wasn't taking place despite looking directly at this and the CMakeLists.txt in question.

**Comment by veprbl** [comment]
Thanks!

**Pull request merged**
