### PR TITLE
jdk11_webkit: init

### PR DESCRIPTION
**Pull request by nazarewk**
###### Description of changes

1. adds webkit-enabled openjfx11 option

loosely inspired by https://github.com/NixOS/nixpkgs/pull/205059

###### Things done

**This is still work-in-progress as I failed to build it.**

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nazarewk** [comment]
Currently stuck at:

```
openjfx-modular-sdk> Build file '/build/source/build.gradle' line: 4031
openjfx-modular-sdk> * What went wrong:
openjfx-modular-sdk> A problem occurred evaluating root project 'source'.
openjfx-modular-sdk> > Could not resolve all files for configuration ':web:icu'.
openjfx-modular-sdk>    > Could not resolve :icu4c-71_1-data-bin-l.
openjfx-modular-sdk>      Required by:
openjfx-modular-sdk>          project :web
openjfx-modular-sdk>       > Could not resolve :icu4c-71_1-data-bin-l.
openjfx-modular-sdk>          > Could not get resource 'https://download.eclipse.org/eclipse/updates/4.6/R-4.6.3-201703010400/plugins/icu4c-71_1-data-bin-l.zip'.
openjfx-modular-sdk>             > Could not HEAD 'https://download.eclipse.org/eclipse/updates/4.6/R-4.6.3-201703010400/plugins/icu4c-71_1-data-bin-l.zip'.
openjfx-modular-sdk>                > download.eclipse.org: Temporary failure in name resolution
openjfx-modular-sdk>       > Could not resolve :icu4c-71_1-data-bin-l.
openjfx-modular-sdk>          > Could not get resource 'https://github.com/unicode-org/icu/releases/download/release-71-1/icu4c-71_1-data-bin-l.zip'.
openjfx-modular-sdk>             > Could not HEAD 'https://github.com/unicode-org/icu/releases/download/release-71-1/icu4c-71_1-data-bin-l.zip'.
openjfx-modular-sdk>                > github.com: Temporary failure in name resolution
```

The file is available for download at https://github.com/unicode-org/icu/releases/tag/release-71-1 , not sure how to make Gradle accept it?

**Comment by nazarewk** [comment]
Somebody on Element suggested using `fetchurl` to get the ZIP and replace it's usage with `file://${icu4c-src}`.

Sadly I don't know Gradle (or any other Java packaging) to know how to replace the lines responsible https://github.com/openjdk/jfx11u/blob/11.0.19%2B0/build.gradle#L3949-L3950

**Comment by nazarewk** [comment]
Note: I've run the Xiaomi Unlock tool on another system VM and [it doesn't work anymore](https://github.com/francescotescari/XiaoMiToolV2/pull/98) so I won't be pushing forward with enabling the Webkit in JavaFX so feel free to take over.

**Comment by t-gebauer** [comment]
Related issue: [libjfxwebkit.so missing in jdk #162064](https://github.com/NixOS/nixpkgs/issues/162064)

This should probably target `staging`: https://github.com/NixOS/nixpkgs/pull/206643 has already made some of the same changes there.

Personally, I am not sure about adding a separate `jdk11_webkit` package, but we should definitely fix `openjfx.override { withWebKit = true; }`

**Comment by t-gebauer** [comment]
I got it to build further (20 minutes and still building...)

1. Local file dependency ([Grade - File dependencies](https://docs.gradle.org/current/userguide/declaring_dependencies.html#sub:file_dependencies))

```
--replace 'icu name: "icu4c-''${icuFileVersion}-data-bin-l", ext: "zip"' 'icu files("${icuBinLZip}")'
```

2. But it is not enough, we also need to preserve the original file name (well, at least part of it ), because of [a glob in a make file](https://github.com/openjdk/jfx11u/blob/11.0.19%2B0/modules/javafx.web/src/main/native/Source/ThirdParty/icu/CMakeLists.txt#L584): `icu4c-*.zip`.

```
<=====--------> 41% EXECUTING [5m 58s]> :web:compileNativeLinux[ 29%] Built target data_as_asm
[ 29%] Generating ../../../icu/data/icudt71l.dat
java.io.FileNotFoundException:  (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
        at jdk.jartool/sun.tools.jar.Main.run(Main.java:388)
        at jdk.jartool/sun.tools.jar.Main.main(Main.java:1683)
make[2]: *** [Source/ThirdParty/icu/CMakeFiles/icudata.dir/build.make:78: icu/data/icudt71l.dat] Error 1
make[1]: *** [CMakeFiles/Makefile2:1227: Source/ThirdParty/icu/CMakeFiles/icudata.dir/all] Error 2
make: *** [Makefile:111: all] Error 2
```

**Comment by linsui** [comment]
Replaced by https://github.com/NixOS/nixpkgs/pull/300573.

**Pull request closed without merging**
