### PR TITLE
polybar: 3.3.1 -> 3.4.0

### PR DESCRIPTION
**Pull request by eadwu**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xrelkd** [comment]
@GrahamcOfBorg build polybar

**Comment by xrelkd** [comment]
LGTM!
Built and tested locally on NixOS.
Hi @marsam, could you merge this PR? Thank you very much!

**Comment by worldofpeace** [comment]
Can we add a `homepage` attribute to `meta` while we're at it?
* https://polybar.github.io/

**Review by jonringer — APPROVED** [review]
`nix-review` passes on NixOS
diff LGTM
binary works (just did --help)
leaf package

**Pull request merged**
