### PR TITLE
fishPlugins.tide: init at 5.5.1

### PR DESCRIPTION
**Pull request by jocelynthode**
###### Description of changes

This fish plugin provides a nice native fish prompt

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by pacien** [comment]
Doesn't seem to be working for me when trying as follows:

```
~/src/nixpkgs add-tide ≡
❯ nix build --impure --expr 'with import ./. {}; wrapFish {
    pluginPkgs = [ fishPlugins.tide ];
  }'
~/src/nixpkgs add-tide ≡
❯ ./result/bin/fish
fish: Unknown command: _tide_1_line_prompt
fish:
_tide_1_line_prompt
^
in command substitution
fish: Unknown command
PATH=/home/kea/bin:/run/wrappers/bin:/home/kea/.nix-profile/bin:/etc/profiles/per-user/kea/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin CMD_DURATION=0 fish_bind_mode=default set _tide_prompt_2586425 (_tide_1_line_prompt)
                                                                                                                                                                                                                           ^
```

**Comment by jocelynthode** [comment]
You need to run `tide configure` this guides you through a quick wizard to setup the prompt and then stores the variables in your fish config.

**Comment by jocelynthode** [comment]
Mmh strange indeed when specifying an empty fish config via 
```
XDG_CONFIG_HOME=/tmp/.config ./result/bin/fish
```
I get the same error as you. I do not understand why. I'm using the package overlayed in my own config but a bit differently and via home-manager as follow: https://github.com/jocelynthode/nixos-config/blob/dcd510c7071677ceefcca793d821c367bd0a7bd9/modules/base/fish/default.nix#L35 and never had this issue. I need to investigate more

**Comment by jocelynthode** [comment]
Ok I'm getting a bit further. When playing with the `wrapFish` generated command which by default is:
```
/nix/store/q8f2zk07qi7hmvgppdsfa1pwiihyrnji-fish-3.5.1/bin/fish --init-command "
    set --prepend fish_complete_path '/nix/store/10sigwkk4nlsm2vxyb2aybsrsg0z9dfd-fishplugin-tide-5.5.1/share/fish/vendor_completions.d'
    set --prepend fish_function_path '/nix/store/10sigwkk4nlsm2vxyb2aybsrsg0z9dfd-fishplugin-tide-5.5.1/share/fish/vendor_functions.d'
    set --local fish_conf_source_path '/nix/store/10sigwkk4nlsm2vxyb2aybsrsg0z9dfd-fishplugin-tide-5.5.1/share/fish/vendor_conf.d'
    for c in \$fish_conf_source_path/*; source \$c; end
  "
```

but switching the `--prepend` with `--append` the first error disappears. I'm not sure why

**Comment by jocelynthode** [comment]
Good idea, I have added a comment pointing to this issue and the specific comment with the workaround.

**Review by pacien — APPROVED** [review]

**Pull request merged**
