### PR TITLE
vimPlugins.ncm2: init at 2018-09-03 

### PR DESCRIPTION
**Pull request by Mic92**
###### Motivation for this change

This is the new version of nvim-completion-manager. Should we remove the old plugin?

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
Nice, I always wanted to try that. 

> Should we remove the old plugin?

Upstream repo https://github.com/roxma/nvim-completion-manager is archived and deprecated, but I guess it still works, and removing it may break existing configs. But then we need to remove it someday...  Hope we get a standard deprecation mechanism soon.

**Comment by Mic92** [comment]
Something like `deprecated; we will remove this in the next release` would be nice.

**Comment by Mic92** [comment]
this is what they recommend as settings: https://github.com/Mic92/dotfiles/commit/dc5e389a916c1f19ad035026c6a90b24754aff27

**Comment by xeji** [comment]
Thanks!

**Pull request merged**
