### PR TITLE
toplevel: stdenv.lib -> lib

### PR DESCRIPTION
**Pull request by Profpatsch**
The library does not depend on stdenv, that `stdenv` exposes `lib` is
an artifact of the ancient origins of nixpkgs.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by alyssais — APPROVED** [review]
LGTM as long as OfBorg identifies it as rebuild-0.

**Review by siraben — APPROVED** [review]
LGTM

**Comment by Atemu** [comment]
Should such a change be done treewide whenever you get the chance to?

**Comment by FRidh** [comment]
Are we in any way fixing anything by this or will this just cause work for people that have expressions relying on this?

**Review by ghost — APPROVED** [review]

**Comment by Profpatsch** [comment]
> or will this just cause work for people that have expressions relying on this?

How do you mean expressions relying on this?

**Comment by FRidh** [comment]
> How do you mean expressions relying on this?

Nevermind, I thought the change in `stdenv` was included here. This here in Nixpkgs is good.

**Comment by Atemu** [comment]
Doesn't eval. Fix: https://github.com/Profpatsch/nixpkgs/pull/3

With that patch, nixpkgs-review says it doesn't change anything.

**Comment by siraben** [comment]
> Should such a change be done treewide whenever you get the chance to?

The end goal is to completely remove `stdenv.lib`. When we perform it treewide it would make sense to split it into several smaller PRs.

**Comment by alyssais** [comment]
> The end goal is to completely remove `stdenv.lib`. When we perform it treewide it would make sense to split it into several smaller PRs.

I’m not sure we necessarily want to completely remove it, because there’ll be lots of external code that uses it. But we don’t want to be using it within Nixpkgs.

**Comment by Profpatsch** [comment]
yeah, just not use it, maybe add a warning eventually, but that’s far out.

If we give people less examples, they won’t copy it around so much.

**Comment by Profpatsch** [comment]
@GrahamcOfBorg build dotnetPackages emscriptenPackages haxePackages luaPackages pythonPackages

**Pull request merged**
