### PR TITLE
ciscoPacketTracer8: fix script modules

### LINKED ISSUE #291445: Cisco Packet Tracer 8 install broken
### Describe the bug
When I install packet tracer 8.2.1 and run it, it launches, but gives a pop up error Titled, "Cisco Packet Tracer - Missing Script Module" with a description, "Required Script Modules do not appear to be running. Please reinstall Cisco Packet Tracer."

### Steps To Reproduce
1. Download CiscoPacketTracer_821_Ubuntu_64bit.deb from cisco netacad and verify its checksum.
2. Add it to your nix cache with $nix-prefetch-url --type sha256 file:///path/to/CiscoPacketTracer_821_Ubuntu_64bit.deb
3. In /etc/configuration.nix
4. Add pkgs.ciscoPacketTracer8 to package list
5. nixos-rebuild switch
6. Launch packet tracer 8

### Expected behavior
Ideally, packet tracer should launch with no issues, and the scripts (including pre-installed and necessary scripts) would work.

### Screenshots
image
image

### Additional context
Not only is it unable to load the scripts, but it cannot see them. I have verified that the .pts files exist in the correct location on install, but trying to add them yields no results.

### Notify maintainers
@lucasew 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.3, NixOS, 23.11 (Tapir), 23.11.20240201.25e3d4c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by gepbird**
Closes https://github.com/NixOS/nixpkgs/issues/291445

As the bug got introduced with a refactor that moved away from `buildFHSEnv`, the only fix I found is moving back to it.

This PR is mostly a revert of https://github.com/NixOS/nixpkgs/commit/2920b6fc16a9ed5d51429e94238b28306ceda79e with additional refactors and the addition of `wayland` for newer versions of packet tracer.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by gepbird** [comment]
cc @griffi-gh @cooparo @ob7 @NemoSomnium @Guccel @Anifyuli @doolphin @sjcp7 for being involved in https://github.com/NixOS/nixpkgs/issues/291445.

You can test this PR with this command, as usual you may need to download the packet tracer deb file and rename it to what you see in the error message:
```
NIXPKGS_EXPORT_ALLOW_UNFREE=1 nix run github:gepbird/nixpkgs/packet-tracer-fix-script-modules#ciscoPacketTracer8 --impure --extra-experimental-features nix-command --extra-experimental-features flakes
```

The "Required Script Modules do not appear to be running. Please reinstall Cisco Packet Tracer." and the "Unable to deserialize." message boxes should be gone, and you should be able to see the script modules loaded. IoT devices also seem to work.

**Comment by griffi-gh** [comment]
Minor complaint but the way the `-unwrapped` package is currently defined makes it kinda hard to override the source; 
what if i do not want to use the stateful/non-reproducible `prefetch-url`?

the only thing i was able to come up with is
- copy the file in my repo
- call `callPackage` on it and override `requireFile` with `fetchurl` (hacky~)
```nix
ciscoPacketTracer8' = (callPackage ./ciscoPacketTracer8.nix {
  requireFile = _: fetchurl {
    url = "https://files-cf.beeg.pp.ua/cisco/Packet_Tracer822_amd64_signed.deb";
    sha256 = "6cd2b8891df92d2cad8b6fdc47480fc089de085c4f3fe95eb80d5450a2a7f72d";
  };
});
```

**Comment by griffi-gh** [comment]
Another thing:
my cursor looks weird whenever i hover over the Packet tracer window

image

**Comment by gepbird** [comment]
> Minor complaint but the way the `-unwrapped` package is currently defined makes it kinda hard to override the source; what if i do not want to use the stateful/non-reproducible `prefetch-url`?
> 
> the only thing i was able to come up with is
> 
>     * copy the `ciscoPacketTracer8` derivation into my repo
> 
>     * call `callPackage` on it and override `requireFile` with `fetchurl` (hacky~)
> 
> 
> ```nix
> ciscoPacketTracer8' = (callPackage ./ciscoPacketTracer8.nix {
>   requireFile = _: fetchurl {
>     url = "https://.../cisco/Packet_Tracer822_amd64_signed.deb";
>     sha256 = "6cd2b8891df92d2cad8b6fdc47480fc089de085c4f3fe95eb80d5450a2a7f72d";
>   };
> });
> ```

Thanks for feedback! I'm not sure what's the best way to allow overriding, making the `unwrapped` and `fhs-env` a function should do the job but its a bit ugly, what do you think? (I intentionally didn't format the file to make the diff easier to read)

**Comment by gepbird** [comment]
> Another thing: my cursor looks weird whenever i hover over the Packet tracer window
> 
> image
> 
> Actually the same weird cursor as i see in Steam.. huh
> 
> and under KDE Plasma (aka the Qt GUI), it runs under x11 instead of Wayland, even without any env vars

That looks normal to me as I see that cursor everywhere on my own system. I haven't looked into cursor themes, but could be that packet tracer is trying to use some other cursor icon that is not in your cursor theme. Do you also experience it with PT on master?

**Comment by ob7** [comment]
tested this out.  seems to work well.  also seems to fix some issues with certain pka files causing PT to crash.  ( haven't tested extensively, just surface level )

**Comment by gepbird** [comment]
I'm not sure why ofborg-eval is failing, maybe rebasing to master will help.

**Comment by griffi-gh** [comment]
(another common pattern for packages using FHSenv is moving `-unwrapped` into a separate package, should this be applied here? idk i don't have much experience with this)

**Review by griffi-gh — APPROVED** [review]

**Comment by gepbird** [comment]
> Hey there. I'm new to nixos and is currently facing an error in ciscoPacketTracer8 - "Required Script Modules do not appear to be running. Please reinstall Cisco Packet Tracer." - at startup. May I know how i should address it? I am running NixOS in qemu. I really want to install it on my main machine, but then I need packettracer for my classes.

Hi, are you using the stable channel (nixos-24.11)? This PR only applies to unstable channel (nixos-unstable) currently but we can backport it.

Also you still should be able to use most of packet tracer's functionality even with that message appearing

**Comment by Emman-pip** [comment]
> Hi @Emman-pip, are you using the stable channel (nixos-24.11)? This PR only applies to unstable channel (nixos-unstable) currently but we can backport it stable.
> 
> Also you still should be able to use most of packet tracer's functionality even with that message appearing

Yes, I am currently at the stable channel. Unfortunately, I think the missing scripts are causing some of the browser functionality in packettracer a segfault. Is there any way I can fix that?

**Comment by gepbird** [comment]
> Yes, I am currently at the stable channel. Unfortunately, I think the missing scripts are causing some of the browser functionality in packettracer a segfault. Is there any way I can fix that? 

Unfortunane that it probably causes runtime issues, in that case try packet tracer from unstable.

Quick one liner to imperatively run it from unstable (doesn't affect the system-wide installation of packet tracer):
`NIXPKGS_ALLOW_UNFREE=1 nix run github:NixOS/nixpkgs/nixos-unstable#ciscoPacketTracer8 --impure --extra-experimental-features 'flakes nix-command'`

If that works, you can decleratively define packet tracer to be installed on your system from unstable, if you're unsure how to do that google it (include "channels" or "flakes" in the query, if you're unsure, by default NixOS is used with channels)

**Comment by Emman-pip** [comment]
> Unfortunane that it probably causes runtime issues, in that case try packet tracer from unstable.
> 
> Quick one liner to imperatively run it from unstable (doesn't affect the system-wide installation of packet tracer):
> `NIXPKGS_ALLOW_UNFREE=1 nix run github:NixOS/nixpkgs/nixos-unstable#ciscoPacketTracer8 --impure --extra-experimental-features 'flakes nix-command'`
> 
> If that works, you can decleratively define packet tracer to be installed on your system from unstable, if you're unsure how to do that google it (include "channels" or "flakes" in the query, if you're unsure, by default NixOS is used with channels)
> 
> I believe in a week this will be backported to stable when you update your system

Thanks! That actually fixed it. This was actually my first time contacting a package maintainer like you. I'm glad I did. Thank you!

**Comment by Emman-pip** [comment]
> Unfortunane that it probably causes runtime issues, in that case try packet tracer from unstable.
> 
> Quick one liner to imperatively run it from unstable (doesn't affect the system-wide installation of packet tracer):
> `NIXPKGS_ALLOW_UNFREE=1 nix run github:NixOS/nixpkgs/nixos-unstable#ciscoPacketTracer8 --impure --extra-experimental-features 'flakes nix-command'`
> 
> If that works, you can decleratively define packet tracer to be installed on your system from unstable, if you're unsure how to do that google it (include "channels" or "flakes" in the query, if you're unsure, by default NixOS is used with channels)
> 
> I believe in a week this will be backported to stable when you update your system

Thanks! That actually fixed it. This was actually my first time contacting a package maintainer like you. I'm glad I did. Thank you!

**Pull request merged**
