### PR TITLE
Add openjdk8

### PR DESCRIPTION
**Pull request by cocreature**
First of all this is my first attempt at nix packaging so there are probably a lot of thing to improve :)
I tried staying somewhat close to the way openjdk7 is built in nix. For this reason I also tried leaving the patches in (after all they are probably useful for something :)). However two of them can't be applied at all as the files they are referring to don't exist anymore, so I removed them. The configure and buildphase look quite different. I sticked very close to the official build guide there. The symlinks in the prePatch phase are so that I can reuse some of the patches from openjdk7.
It might be a good idea to unify the derivations for openjdk7 and openjdk8 a bit more but currently this is over my head :)
Any feedback is appreciated.

### CODE REVIEW

**Comment by cocreature** [comment]
I think the travis failure is caused by an oom or a timeout.

**Comment by lethalman** [comment]
So I'm trying to build it locally. However I have a question: why does the build depend on openjdk-7u65b32 ?

**Comment by cocreature** [comment]
You need a bootstrap sdk to compile it.

**Comment by cocreature** [comment]
openjdk7 seems to manually download this (probably because it can't depend on itself), if you think this is a better solution I could try to use this here aswell.

**Comment by lethalman** [comment]
@cocreature the problem is that the day we drop openjdk7, then openjdk8 needs to be rewritten. So yes, it's better if openjdk8 doesn't depend on openjdk7 in my opinion.

**Comment by cocreature** [comment]
Ok, I'll change this later.

**Comment by lethalman** [comment]
Also think that there's an input "openjdk", what if this openjdk8 becomes the default openjdk? Or if one overrides his own packages to make openjdk8 the default? That's an infinite recursion. Not sure what's the best way to handle this anyway.

**Comment by lethalman** [comment]
Btw build fails:
```
source root is jdk8u-jdk8u25-b18
patching sources
applying patch /nix/store/2x6v46j158y86yhpzwhywjc0x7wgn84p-fix-java-home.patch
patching file hotspot/src/os/linux/vm/os_linux.cpp
Hunk #1 succeeded at 2300 with fuzz 2 (offset -58 lines).
applying patch /nix/store/b0vwvn37nmjdhlbr7zwv27vfjzwnh28q-read-truststore-from-env-jdk8.patch
patching file jdk/src/share/classes/sun/security/ssl/TrustManagerFactoryImpl.java
applying patch /nix/store/6k8nwds7ycliaq0yf242gnrrb199p980-currency-date-range-jdk8.patch
patching file jdk/make/src/classes/build/tools/generatecurrencydata/GenerateCurrencyData.java
configuring
configure flags: --prefix=/nix/store/p2d4l3ga1alph3v0m80bmzrhmx9rz2xa-openjdk-8u25b18 --with-freetype=/nix/store/74lfjnmp1iighl17d44pyqnvk2d0nrw0-freetype-2.5.4 --with-override-langtools=../langtools-jdk8u25-b18 --with-override-hotspot=../hotspot-jdk8u25-b18 --with-override-corba=../corba-jdk8u25-b18 --with-override-jdk=../jdk-jdk8u25-b18 --with-override-jaxws=../jaxws-jdk8u25-b18 --with-override-jaxp=../jaxp-jdk8u25-b18 --with-override-nashorn=../nashorn-jdk8u25-b18 --with-boot-jdk=/nix/store/30fq1x2h11qjdyjh4r9z6ckbsgdds8xf-openjdk-7u65b32/lib/openjdk/ --with-update-version=25 --with-build-number=b18 --with-milestone=fcs 
/nix/store/frmyf8fdq5xhm035mr87wn6kj0c278g7-stdenv/setup: ./configure: /bin/bash: bad interpreter: No such file or directory
builder for ‘/nix/store/7mzgw3g2vz497rfgpkwcrjc9aw8mk3jh-openjdk-8u25b18.drv’ failed with exit code 126
error: build of ‘/nix/store/7mzgw3g2vz497rfgpkwcrjc9aw8mk3jh-openjdk-8u25b18.drv’ failed
```

You should enable chroot builds :)

**Comment by cocreature** [comment]
I need to create new bootstrap tarballs because the 3 year old ones don't work with jdk8, so it might take a bit longer to fix this.

**Comment by lethalman** [comment]
Ah I see, that's harder than what it seems :(

**Comment by cocreature** [comment]
Sorry, I fail at creating a bootstrap package that contains native2ascii (which seems to be necessary with jdk8). Pinging @shlevy and @edolstra as they seem to be maintaining jdk7. I can't even reproduce the build of the old jdk using openjdk7 as an input to make-bootstrap.nix.

**Comment by shlevy** [comment]
@cocreature Haven't looked at this in a long time, sorry. Do we currently have jdk8 building with jdk7 as the compiler?

**Comment by shlevy** [comment]
Ah never mind misread the above. If at all possible, bootstrapping should be a second step, please try to get jdk8 building first and then we can make it independent of jdk7. If jdk8 requires jdk8 to compile, let me know and I'll see about bootstrapping our way up.

**Comment by shlevy** [comment]
(to clarify, try to build openjdk8 with openjdk7, *not* with the openjdk7 bootstrap)

**Comment by cocreature** [comment]
Seems to build in a chroot now with openjdk7.

**Comment by shlevy** [comment]
OK, starting a build overnight, will merge if all is well.

**Comment by lethalman** [comment]
Great work, thanks :)

**Comment by shlevy** [comment]
@cocreature Can you add yourself as maintainer? Also, if you're planning on getting it bootstrapped feel free to open an issue and I'll try to help as best I can.

**Comment by cocreature** [comment]
@shlevy I didn't do this because at this point I'm not really sure if I know enough to be a good maintainer. But if you think it's a good idea I will do so, should I create a separate PR for this?

**Comment by shlevy** [comment]
In practical terms, "maintainer" just means you will get emails from hydra about build results and people will email/ping you if they're uncertain about a change or have a question about the package. You certainly don't have to do it, but if you plan to do further work on jdk8 it would be nice (yes, in a separate PR)

**Pull request merged**
