### PR TITLE
imagemagick: 7.1.0-57 -> 7.1.0-60

### PR DESCRIPTION
**Pull request by dotlambda**
`perlPackages.ImageMagick` fails to build, even without the bump to 7.0.11-3.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dotlambda** [comment]
I guess we don't care about the Perl package?

**Comment by xworld21** [comment]
@dotlambda have you tried checking with the ImageMagick project? I have checked your PR, and I see that one image is not generated correctly (the TGA one, at least on my macOS Monterey). But I struggled to debug the issue. At the moment I wouldn't necessarily blame nixpkgs for this.

(There is also a fontconfig error that is actually due to packaging, but it is not important and does not cause the tests to fail anyway.)

**Comment by dotlambda** [comment]
> have you tried checking with the ImageMagick project?

I would prefer if someone's who's familiar with Perl did that?

**Comment by xworld21** [comment]
PS: I'd rather remove the `write.t` test temporarily and make sure the failure is reported here on nixpkgs, hoping that somebody can fix that, rather than breaking `Image::Magick` altogether. One thing to know: if you add `makeFlags = "TEST_VERBOSE=1"`, you'll get more detailed output from the tests.

> I would prefer if someone's who's familiar with Perl did that?

I can give it a try but I can't promise too much time at the moment! @erictapen would you be able to help with this?

**Comment by dotlambda** [comment]
Turns out this was fixed upstream in https://github.com/ImageMagick/ImageMagick/commit/6192ed29eb8db563a09093b0529933f2b09645f2. I think we should build `perPackages.ImageMagick` from the same source as `imagemagick`, e.g. using the configure flag `--with-perl`. I've pushed a commit but it fails with
```
ERROR: Can't create '/nix/store/4r62651pfraj819rpyvmbq8pg2bq6k71-perl-5.36.0/lib/perl5/site_perl/5.36.0/x86_64-linux-thread-multi/Image'
mkdir /nix/store/4r62651pfraj819rpyvmbq8pg2bq6k71-perl-5.36.0/lib/perl5/site_perl/5.36.0/x86_64-linux-thread-multi/Image: Permission denied at /nix/store/4r62651pfraj819rpyvmbq8pg2bq6k71-perl-5.36.0/lib/perl5/5.36.0/ExtUtils/Install.pm line 470.
```
Can someone help me?

**Comment by xworld21** [comment]
@dotlambda good catch! For now, I recommend you simply add something like
```nix
patches = [ fetchPatch {
  name = "update-tga-test-hash.patch";
  url = "https://github.com/ImageMagick/ImageMagick/commit/6192ed29eb8db563a09093b0529933f2b09645f2.patch";
}];
```
to `perl-packages.nix`, best if accompanied by a comment and/or a link to a bug report, or this PR, so that we have a working build.

Creating the Perl package out of ImageMagick itself sounds like a tricky change. But maybe not, of course, so if you can make that fit the way `perlPackages` work (and e.g. produce variants for all perl versions), you can submit a different PR. I would check with @stigtsp, who I gather is in charge of `perl-packages.nix`.

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 212205` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>imagemagick</li>
    <li>imagemagickBig</li>
    <li>imagemagick_light</li>
    <li>perlPackages.ImageMagick</li>
    <li>python310.pkgs.wand</li>
    <li>python311.pkgs.wand</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 212205` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>imagemagick</li>
    <li>imagemagickBig</li>
    <li>imagemagick_light</li>
    <li>perlPackages.ImageMagick</li>
    <li>python310.pkgs.wand</li>
    <li>python311.pkgs.wand</li>
  </ul>
</details>

**Pull request merged**
