### PR TITLE
nodePackages.lumo-cljs: init at 1.5.0

### PR DESCRIPTION
**Pull request by m3tti**
###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by pSub** [comment]
You're sure you need all those changes (+4,435 −3,436) to add that package? I tried to view those large diffs on github but they failed to load due to their size.

**Comment by m3tti** [comment]
I've just followed the README.md file in the nodePackages section. Primarily i've just added lumo-cljs into the node-packages.json file and run generate.sh which than created the other files (updated them v4 and v6).

**Comment by pSub** [comment]
Ok, then someone with more knowledge about node in nixpkgs should look into this.

**Comment by svanderburg** [comment]
The churn of node package updates is always quite big. This is unfortunate side effect comes from node2nix trying to remain as compatible with npm. node2nix, for example, deploys an entire package + dependencies as a single derivation.

Also, the package set is always updated as a whole, meaning that also dependencies of other packages will be updated.

Although I know this is not desirable, this is something we have to "live" with" at the moment.

I noticed that the travis CI job is failing, but seems to be caused by a Haskell package.

From my perspective, since the tool is end-user software and the expressions are properly regenerated, this update can go in.

**Comment by Mic92** [comment]
Is there still interest in this package? I could add it in https://github.com/NixOS/nixpkgs/pull/50003

**Comment by Mic92** [comment]
If there is still an interest, just open a new pull request.

**Pull request closed without merging**
