### PR TITLE
cemu: fix build

### LINKED ISSUE #114509: CEmu is broken
**Describe the bug**
CEmu doesn't build on master. When that's fixed, it segfaults.

**To Reproduce**
1. Create `pkgs/applications/science/math/cemu/fix-includes.patch`:

<details>

```
From fd72766acfdde9e71ed70ae4c5441cf8cdff7b69 Mon Sep 17 00:00:00 2001
From: Adrien Bertrand <bertrand.adrien@gmail.com>
Date: Sat, 16 May 2020 19:17:09 -0400
Subject: [PATCH] cleanup and fix header inclusion on some toolchains.

---
 src/BinaryFile.cpp                       | 2 ++
 src/TIModel.cpp                          | 2 ++
 src/TIVarFile.cpp                        | 2 ++
 src/TIVarType.cpp                        | 2 ++
 src/TIVarTypes.cpp                       | 1 -
 src/TypeHandlers/DummyHandler.cpp        | 2 ++
 src/TypeHandlers/STH_DataAppVar.cpp      | 2 ++
 src/TypeHandlers/STH_ExactFraction.cpp   | 3 ++-
 src/TypeHandlers/STH_ExactFractionPi.cpp | 3 ++-
 src/TypeHandlers/STH_ExactPi.cpp         | 3 ++-
 src/TypeHandlers/STH_ExactRadical.cpp    | 2 ++
 src/TypeHandlers/STH_FP.cpp              | 4 ++--
 src/TypeHandlers/STH_PythonAppVar.cpp    | 2 +-
 src/TypeHandlers/TH_GenericAppVar.cpp    | 2 +-
 src/TypeHandlers/TH_GenericComplex.cpp   | 2 +-
 src/TypeHandlers/TH_GenericList.cpp      | 2 ++
 src/TypeHandlers/TH_GenericReal.cpp      | 2 +-
 src/TypeHandlers/TH_Matrix.cpp           | 2 ++
 src/TypeHandlers/TH_TempEqu.cpp          | 2 ++
 src/TypeHandlers/TH_Tokenized.cpp        | 1 +
 20 files changed, 33 insertions(+), 10 deletions(-)

diff --git a/src/BinaryFile.cpp b/src/BinaryFile.cpp
index 64b5144..1d6037e 100644
--- a/src/BinaryFile.cpp
+++ b/gui/qt/tivarslib/BinaryFile.cpp
@@ -8,6 +8,8 @@
 #include "BinaryFile.h"
 #include "tivarslib_utils.h"
 
+#include <stdexcept>
+
 namespace tivars
 {
 
diff --git a/src/TIModel.cpp b/src/TIModel.cpp
index ab0890e..8d90f45 100644
--- a/src/TIModel.cpp
+++ b/gui/qt/tivarslib/TIModel.cpp
@@ -8,6 +8,8 @@
 #include "TIModel.h"
 #include "TIModels.h"
 
+#include <stdexcept>
+
 namespace tivars
 {
     
diff --git a/src/TIVarFile.cpp b/src/TIVarFile.cpp
index bd4c606..4ca8bcc 100644
--- a/src/TIVarFile.cpp
+++ b/gui/qt/tivarslib/TIVarFile.cpp
@@ -8,6 +8,8 @@
 #include "TIVarFile.h"
 #include "tivarslib_utils.h"
 #include "TIModels.h"
+
+#include <stdexcept>
 #include <numeric>
 #include <regex>
 
diff --git a/src/TIVarType.cpp b/src/TIVarType.cpp
index 441c030..76e501b 100644
--- a/src/TIVarType.cpp
+++ b/gui/qt/tivarslib/TIVarType.cpp
@@ -8,6 +8,8 @@
 #include "TIVarType.h"
 #include "TIVarTypes.h"
 
+#include <stdexcept>
+
 namespace tivars
 {
     /*** "Constructors" ***/
diff --git a/src/TypeHandlers/DummyHandler.cpp b/src/TypeHandlers/DummyHandler.cpp
index 91bca1a..f12a044 100644
--- a/src/TypeHandlers/DummyHandler.cpp
+++ b/gui/qt/tivarslib/TypeHandlers/DummyHandler.cpp
@@ -8,6 +8,8 @@
 #include "../CommonTypes.h"
 #include "TypeHandlers.h"
 
+#include <stdexcept>
+
 namespace tivars
 {
 
diff --git a/src/TypeHandlers/STH_DataAppVar.cpp b/src/TypeHandlers/STH_DataAppVar.cpp
index 47d2dcc..4df8984 100644
--- a/src/TypeHandlers/STH_DataAppVar.cpp
+++ b/gui/qt/tivarslib/TypeHandlers/STH_DataAppVar.cpp
@@ -7,6 +7,8 @@
 
 #include "TypeHandlers.h"
 #include "../tivarslib_utils.h"
+
+#include <stdexcept>
 #include <regex>
 
 namespace tivars
diff --git a/src/TypeHandlers/STH_ExactFraction.cpp b/src/TypeHandlers/STH_ExactFraction.cpp
index 544da88..5d96db3 100644
--- a/src/TypeHandlers/STH_ExactFraction.cpp
+++ b/gui/qt/tivarslib/TypeHandlers/STH_ExactFraction.cpp
@@ -7,7 +7,8 @@
 
 #include "TypeHandlers.h"
 #include "../tivarslib_utils.h"
-#include <regex>
+
+#include <stdexcept>
 
 namespace tivars
 {
diff --git a/src/TypeHandlers/STH_ExactFractionPi.cpp b/src/TypeHandlers/STH_ExactFractionPi.cpp
index f4f090a..788d19f 100644
--- a/src/TypeHandlers/STH_ExactFractionPi.cpp
+++ b/gui/qt/tivarslib/TypeHandlers/STH_ExactFractionPi.cpp
@@ -7,7 +7,8 @@
 
 #include "TypeHandlers.h"
 #include "../tivarslib_utils.h"
-#include <regex>
+
+#include <stdexcept>
 
 namespace tivars
 {
diff --git a/src/TypeHandlers/STH_ExactPi.cpp b/src/TypeHandlers/STH_ExactPi.cpp
index b0fb2f4..410b281 100644
--- a/src/TypeHandlers/STH_ExactPi.cpp
+++ b/gui/qt/tivarslib/TypeHandlers/STH_ExactPi.cpp
@@ -7,7 +7,8 @@
 
 #include "TypeHandlers.h"
 #include "../tivarslib_utils.h"
-#include <regex>
+
+#include <stdexcept>
 
 namespace tivars
 {
diff --git a/src/TypeHandlers/STH_ExactRadical.cpp b/src/TypeHandlers/STH_ExactRadical.cpp
index ab7abd4..825b62a 100644
--- a/src/TypeHandlers/STH_ExactRadical.cpp
+++ b/gui/qt/tivarslib/TypeHandlers/STH_ExactRadical.cpp
@@ -8,5 +8,7 @@
 #include "TypeHandlers.h"
 #include "../tivarslib_utils.h"
+
+#include <stdexcept>
 #include <regex>
 
 namespace tivars
diff --git a/src/TypeHandlers/STH_FP.cpp b/src/TypeHandlers/STH_FP.cpp
index c6b5edb..77cbf8d 100644
--- a/src/TypeHandlers/STH_FP.cpp
+++ b/gui/qt/tivarslib/TypeHandlers/STH_FP.cpp
@@ -8,8 +8,8 @@
 // TODO : check if the models have different exponent offsets
 
 #include "TypeHandlers.h"
-#include "../tivarslib_utils.h"
-#include <regex>
+
+#include <stdexcept>
 
 static bool parseSign(std::string::const_iterator &i, const std::string::const_iterator &e) {
     bool sign = false;
diff --git a/src/TypeHandlers/STH_PythonAppVar.cpp b/src/TypeHandlers/STH_PythonAppVar.cpp
index 494671f..4f48661 100644
--- a/src/TypeHandlers/STH_PythonAppVar.cpp
+++ b/gui/qt/tivarslib/TypeHandlers/STH_PythonAppVar.cpp
@@ -6,8 +6,8 @@
  */
 
 #include "TypeHandlers.h"
-#include "../tivarslib_utils.h"
 
+#include <stdexcept>
 #include <cstring>
 
 // TODO: handle filename stuff
diff --git a/src/TypeHandlers/TH_GenericAppVar.cpp b/src/TypeHandlers/TH_GenericAppVar.cpp
index 5610672..26585ec 100644
--- a/src/TypeHandlers/TH_GenericAppVar.cpp
+++ b/gui/qt/tivarslib/TypeHandlers/TH_GenericAppVar.cpp
@@ -6,8 +6,8 @@
  */
 
 #include "TypeHandlers.h"
-#include "../tivarslib_utils.h"
 
+#include <stdexcept>
 #include <cstring>
 
 namespace tivars
diff --git a/src/TypeHandlers/TH_GenericComplex.cpp b/src/TypeHandlers/TH_GenericComplex.cpp
index d7accd3..19adbaa 100644
--- a/src/TypeHandlers/TH_GenericComplex.cpp
+++ b/gui/qt/tivarslib/TypeHandlers/TH_GenericComplex.cpp
@@ -6,8 +6,8 @@
  */
 
 #include "TypeHandlers.h"
-#include "../tivarslib_utils.h"
 
+#include <stdexcept>
 #include <regex>
 #include <unordered_map>
 
diff --git a/src/TypeHandlers/TH_GenericList.cpp b/src/TypeHandlers/TH_GenericList.cpp
index 23fa048..eb518ec 100644
--- a/src/TypeHandlers/TH_GenericList.cpp
+++ b/gui/qt/tivarslib/TypeHandlers/TH_GenericList.cpp
@@ -9,6 +9,8 @@
 #include "../tivarslib_utils.h"
 #include "../TIVarTypes.h"
 
+#include <stdexcept>
+
 namespace tivars
 {
     // TODO: also make it detect the type correctly...
diff --git a/src/TypeHandlers/TH_GenericReal.cpp b/src/TypeHandlers/TH_GenericReal.cpp
index 5502500..418b91c 100644
--- a/src/TypeHandlers/TH_GenericReal.cpp
+++ b/gui/qt/tivarslib/TypeHandlers/TH_GenericReal.cpp
@@ -6,8 +6,8 @@
  */
 
 #include "TypeHandlers.h"
-#include "../tivarslib_utils.h"
 
+#include <stdexcept>
 #include <unordered_map>
 
 namespace tivars
diff --git a/src/TypeHandlers/TH_Matrix.cpp b/src/TypeHandlers/TH_Matrix.cpp
index e06cf03..d98ccf8 100644
--- a/src/TypeHandlers/TH_Matrix.cpp
+++ b/gui/qt/tivarslib/TypeHandlers/TH_Matrix.cpp
@@ -8,6 +8,8 @@
 #include "TypeHandlers.h"
 #include "../tivarslib_utils.h"
 
+#include <stdexcept>
+
 namespace tivars
 {
 
diff --git a/src/TypeHandlers/TH_TempEqu.cpp b/src/TypeHandlers/TH_TempEqu.cpp
index 8c47dcb..d0b300a 100644
--- a/src/TypeHandlers/TH_TempEqu.cpp
+++ b/gui/qt/tivarslib/TypeHandlers/TH_TempEqu.cpp
@@ -6,6 +6,8 @@
  */
 
 #include "TypeHandlers.h"
+
+#include <stdexcept>
 #include <cstring>
 
 namespace tivars
diff --git a/src/TypeHandlers/TH_Tokenized.cpp b/src/TypeHandlers/TH_Tokenized.cpp
index 20d58f5..bcaf549 100644
--- a/src/TypeHandlers/TH_Tokenized.cpp
+++ b/gui/qt/tivarslib/TypeHandlers/TH_Tokenized.cpp
@@ -13,5 +13,6 @@
 #include <QtCore/QFile>
 
+#include <stdexcept>
 #include <unordered_map>
 #include <iostream>
 #include <regex>
```

</details>

2. Add the following lines to `pkgs/applications/science/math/cemu/default.nix`:

```
  patches = [
    ./fix-includes.patch
  ];
```

3. `nix-build -A cemu`
4. `result/bin/CEmu`
5. Segmentation fault (core dumped)

**Notify maintainers**
@luc65r 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.92, NixOS, 21.05pre270709.6b1057b452c (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(kuba): `"nixpkgs-21.03pre267490.65211f5afcc"`
 - channels(root): `"nixos-21.05pre270709.6b1057b452c"`
 - nixpkgs: `/home/kuba/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: cemu
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by luc65r**
###### Motivation for this change

Fixes https://github.com/NixOS/nixpkgs/issues/114509

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 114577` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>cemu</li>
  </ul>
</details>

**Comment by siraben** [comment]
```ShellSession
builder for '/nix/store/4b29pw928jgm43pn33apf3fnnyakwvsm-CEmu-1.3.drv' failed with exit code 3; last 10 log lines:
       /nix/store/n63cxjv3wylh1094x52gyk4flsnh0n2b-libarchive-3.5.1-lib/lib
   /nix/store/84p32pj92xdji1rzcx3m78qcg5zknjmp-libusb-compat-0.1.7/lib
    /nix/store/3wwfb12b0d6rvnrybxx5r667kl56z62c-clang-7.1.0/lib
    /nix/store/hc44758rqfmm08m4fl79ycvicf1wz52y-clang-7.1.0-lib/lib
        /nix/store/v5vd9k28hsmj826nr0sx48ajyh7wfqf1-Libsystem-1238.60.2/lib
  Framework search paths:
  ld: library not found for -lc++
  clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
  ===================
  Maybe you forgot to setup the environment?
```

**Comment by siraben** [comment]
Full log: http://ix.io/2Sfl , looks like it wants to use `clang++` on darwin.

**Comment by risicle** [comment]
Same failure, macos 10.14

**Comment by luc65r** [comment]
merged in #144889

**Pull request closed without merging**
