### PR TITLE
safeeyes: init at 2.0.2

### PR DESCRIPTION
**Pull request by srghma**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

##### Known issues
1. 
```
ERROR:root:Error in loading the plugin: notification
```
 
2. 

```
(safeeyes:2448): Gtk-WARNING **: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/check-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.
```

adding `"--prefix XDG_DATA_DIRS : \"${gnome3.defaultIconTheme}/share:$GSETTINGS_SCHEMAS_PATH\""` to `makeWrapperArgs` didnt help

### CODE REVIEW

**Comment by srghma** [comment]
@mattbillenstein added, tested

**Comment by srghma** [comment]
@matthewbauer can you help me fix Known issues above?

1. with what I should substitute APPINDICATOR_ID?
2. how to make it find Adwaita theme?

**Comment by matthewbauer** [comment]
1. For the plugin thing, most likely you need to override "BIN_DIRECTORY" in safeeyes (or at least make sure that those plugins are installed correctly) :

https://github.com/slgobinath/SafeEyes/blob/992b091cf768afaa8718056adccc47893ae11962/safeeyes/Utility.py#L53

2. I think for this you need to wrap with "GDK_PIXBUF_MODULE_FILE" se https://github.com/NixOS/nixpkgs/blob/6632fd23a73745c4b6a4d93cb7bec92c14e83f36/pkgs/applications/office/tryton/default.nix#L19


Also I think there is still a merge conflict (fix by running ```git fetch nixpkgs master``` and ```git rebase nixpkgs/master``` then resolve merge conflicts).

**Comment by srghma** [comment]
@matthewbauer 

1. other plugins are working, I think its because of  gir1.2-notify-0.7 https://github.com/slgobinath/SafeEyes/blob/57418866befa1aff64d91c4de365b8aad009e18c/safeeyes/plugins/notification/plugin.py#L24 , I dont have it in deps, just noticied)
2. I'm already using it https://github.com/NixOS/nixpkgs/pull/37737/files#diff-1a7442bd61f809d72baeb21b15f0fa47R45

2018-04-10-21 35 48-screenshot

**Comment by srghma** [comment]
@mattbillenstein fixed notify plugin)

**Comment by matthewbauer** [comment]
For 2, definitely make sure the wrapper is setting valid values for GDK_PIXBUF_MODULE_FILE. You may need pull in "gdk-pixbuf" to get it. See this too:

https://github.com/NixOS/nixpkgs/blob/0fadb81af44fe7f43581a276d2ca863bdb64dd67/pkgs/applications/misc/pdfshuffler/default.nix#L29

**Comment by matthewbauer** [comment]
@GrahamcOfBorg build safeeyes

**Comment by matthewbauer** [comment]
Well looks good to me. I can merge today if there are no object. One last thing to try is just adding "gnome3.adwaita-icon-theme" as a build inpunt.

**Comment by matthewbauer** [comment]
I'll merge this for now because it looks good enough. I think your icon issue may be something weird with GTK on Nix. Maybe try running it in GNOME to see if that finds the right themes. See also #5053.

**Comment by srghma** [comment]
@matthewbauer already) 
https://github.com/NixOS/nixpkgs/pull/37737/commits/344c142cda39a467f6d8f398ae9c47d68a426936#diff-1a7442bd61f809d72baeb21b15f0fa47R21

Thanks for merge)

P.S.
thats how it looks on elementary
I dunno, maybe images are right

screenshot_from_2018-04-10_22-38-13

**Comment by srghma** [comment]
Dont want to run gnome, whatever, tnx)

**Pull request merged**
