### PR TITLE
nixos/btrfs: make autoScrub not prevent shutdown or suspend

### LINKED ISSUE #79086: services.btrfs.autoScrub: running scrub prevents system suspend
**Describe the bug**

When the filesystem scrubbing service configured via `services.btrfs.autoScrub` is running, the system cannot suspend until the scrubbing is completed.

**To Reproduce**
1. enable the autoscrub service on some Btrfs file system, e.g. by
  ```nix
  services.btrfs.autoScrub = {enable = true; fileSystems = [ "/" ];};
  ```
2. start the resulting service, e.g. `systemctl start btrfs-scrub-.service`
3. suspend-to-ram the system: `systemctl suspend`
4. the system fails to suspend and a trace appropriating this failure tu btrfs can be found in the [system journal](https://github.com/NixOS/nixpkgs/files/4144117/btrfs-scrub-suspend_partial.log)

**Expected behavior**

The scrub should be paused properly when the system suspends.

**More context**

It's likely that this is an upstream bug. I'll ask around on the btrfs mailing list and will update this issue accordingly.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.98, NixOS, 19.09.1970.6d9a4a615ee (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"home-manager-19.09, nixos-19.09.1970.6d9a4a615ee, nixos-unstable-20.03pre210639.e59dcf8ccec"`
 - channels(user): `"home-manager-19.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
- tasks/filesystems/btrfs.nix
```

### PR DESCRIPTION
**Pull request by symphorien**
Fixes: #79086 #79017

can you test this @schmittlauch ?

###### Things done
Tested on my system, only that scrub is cancelled by suspend.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by schmittlauch** [comment]
I backported this onto the release-19.09 branch, there it works fine both with shutdown and suspend.

It would be nice if the scrubbing was resumed/ started again after resuming from suspension. But if this was not trivial to achieve, I'd be in favour of merging this without resumption support. Maybe we can still sneak this into 20.03, @worldofpeace? It'd be a shame if this small bugfix only reached stable in September.

**Comment by schmittlauch** [comment]
*bump* @symphorien:

Do you see a straight-forward way for resumption or do you prefer to merge this as-is for the time being?

**Comment by symphorien** [comment]
`man btrfs scrub` mentions no cancel or resume operation. So I think there is no straightforward way to improve. Let's merge as is.

**Comment by Ekleog** [comment]
Merged and backported to 20.03 as 99a3d7a86fce9e9c9f23b3e304d7d2b1270a12b8, seeing the absence of opposition

**Pull request merged**
