### PR TITLE
vimPlugins: updates

### PR DESCRIPTION
**Pull request by teto**
###### Motivation for this change

packer.nvim is getting increasingly popular in neovim, especially because it can deal with plugin dependency via luarocks.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AndersonTorres** [comment]
Was it autogenerated?

**Comment by teto** [comment]
yes it was, I've just added sqlite as a buildInput of sql.nvim

**Review by SuperSandro2000 — COMMENTED** [review]
Next time please update before doing any changes then do your changes and update again. This makes reviewing the changes way easier.

**Comment by teto** [comment]
@SuperSandro2000 I dont get your comment, this is all generated as recommended by:
`pkgs/misc/vim-plugins/update.py  --add tami5/sql.nvim --add nvim-telescope/telescope-frecency.nvim --add wbthomason/packer.nvim`
Checking out changes commit by commit is quite straightforward.

**Comment by SuperSandro2000** [comment]
> @SuperSandro2000 I dont get your comment, this is all generated as recommended by:
> `pkgs/misc/vim-plugins/update.py --add tami5/sql.nvim --add nvim-telescope/telescope-frecency.nvim --add wbthomason/packer.nvim`
> Checking out changes commit by commit is quite straightforward.

Next time just run ``./pkgs/misc/vim-plugins/update.py`` before adding the plugins.

**Comment by teto** [comment]
but there is an "update commit" before all of them, that's what the script does...

**Pull request merged**
