### PR TITLE
lowdown: Split out "bin" and "man" outputs

### PR DESCRIPTION
**Pull request by Ericson2314**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
We [discussed this originally](https://github.com/NixOS/nixpkgs/pull/94225#discussion_r462955750).

The decision was in the end to keep the man pages in the `bin` and `dev`/`lib` outputs respectively, since the man pages don't take up a lot of space and it's more convenient this way. Also a package with 5 outputs which lowdown would become then would be kinda confusing I suppose…

**Comment by Ericson2314** [comment]
I don't really care about man pages, but it's very nice to separate bin and libraries. I use this with Nix itself, in fact, which needs the executables at build time, but libraries at run time.

**Comment by sternenseemann** [comment]
The library is installed to `dev`, `out` only contains the binary and man pages.

**Comment by Ericson2314** [comment]
@sternenseemann you are saying `.so` are in `dev`? or just `.a`?

**Comment by sternenseemann** [comment]
@Ericson2314 There's no `liblowdown.so`, see the [Makefile](https://github.com/kristapsdz/lowdown/blob/1705b4a26fbf065d9574dce47a94e8c7c79e052f/Makefile#L104-L120).

**Review by sternenseemann — COMMENTED** [review]
Why patch in a shared object? As long as nothing depends on `lowdown` providing a shared object (which isn't the case in `nixpkgs` yet and I generally doubt, since It isn't the case for upstream), I don't see a reason to patch one in and to maintain the patch etc.

**Comment by Ericson2314** [comment]
By default, we install libraries as shared objects. I don't see why this library should be different?

**Comment by Ericson2314** [comment]
I think we should do this:

- We don't do static libs in `dev` elsewhere
- We try to do shared libs by defalut
- I did this for Nix itself to help make cross compilation more robust: https://github.com/NixOS/nix/blob/8a2ce0f455da32bc20978e68c0aad9efb4560abc/flake.nix#L214

**Comment by sternenseemann** [comment]
* Are there any advantages in making `lib` the default output? I feel like the default output should be `bin`.
* Can you submit the Makefile patch [upstream](https://github.com/kristapsdz/lowdown) as well?
* Out of curiosity: How does the additional output help? Also: Wouldn't it be empty in the linked flake?

**Comment by Ericson2314** [comment]
Discussing in https://github.com/kristapsdz/lowdown/issues/45.

**Comment by Ericson2314** [comment]
https://github.com/kristapsdz/lowdown/issues/45#issuecomment-756654013 upstream author doesn't want to add better support at this time.

**Comment by sternenseemann** [comment]
Alright, if it helps for packaging and cross compiling `nix`, I think it's definitely worth it patching this in for us. Having to override `lowdown` in the nix flake shouldn't be necessary, really.

I'll see if I find the time and motivation to maybe patch this in upstream, we'll see.

I think the question that remains is the question of the default output.

**Comment by Ericson2314** [comment]
Based on what you said, and upstream confirmed, I made bin the default output. :)

**Pull request merged**
