### PR TITLE
nixos/spiped: remove broken chmod's from preStart

### LINKED ISSUE #306789: spiped module: error in default configuration
### Describe the bug

The module `services/networking/spiped.nix` does not work in the default configuration, because the `preStart` script is broken.

### Steps To Reproduce
1. Use spiped, e.g.

```
  services.spiped = {
    enable = true;
    config = {
      myservice = {
        keyfile = "/run/secrets/myservice.key";
        encrypt = true;
        source = "[127.0.0.1]:4445";
        target = "[169.254.42.42]:5445";
      };
    };
  };

```

2. The service fails to start, the `preStart` script fails because the directory `/var/lib/spiped` is empty, and thus the command `chown spiped:spiped *` fails because `*` doesn't expand in an empty directory.

### Expected behavior

The service should start successfully as the configuration is complete.

### Additional context

It is not clear to me what the `/var/lib/spiped` directory is good for: spiped doesn't create any files by default (except the pidfile, which NixOS doesn't use).

Furthermore, the directory could be created with correct permissions in the tmpfile rule already?

A simple fix would be to use `.` instead of `*` here, if one wants to keep around the same semantics.

### Notify maintainers

@thoughtpolice 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.77, NixOS, 23.11 (Tapir), 23.11.20240211.809cca7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-22.05.3300.82379884b2e"`
 - nixpkgs: `/nix/store/684dgr65n8li4pnfirls96jigyhvb9rq-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by tomfitzhenry**
Forked from https://github.com/NixOS/nixpkgs/pull/209368, which might be stale. Attribution to original author kept. Fixes https://github.com/NixOS/nixpkgs/issues/306789.

Remove `chmod`s which were (1) broken and (2) no longer considered good Nix practice.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by aanderse** [comment]
`PermissionsStartOnly` is long deprecated but this module still uses it 

maybe this PR is a good opportunity for cleaning that up

**Comment by MazeChaZer** [comment]
@aanderse good idea, as the preStart script is gone now, this is also no longer needed.

**Comment by aanderse** [comment]
@tomfitzhenry i'll also mention [LoadCredential](https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#LoadCredential=ID:PATH) as another _option_ here... i think it would work quite well - are you familiar with that?

to be clear - what you currently have is fine, i'm just offering another idea :smile:

**Review by aanderse — APPROVED** [review]
> I've never used it, but have been meaning to. For now, it'd be nice to just fix this broken module.

sounds good, i hope to see such an improvement in the future

---

@SuperSandro2000 are you good with a merge here? you were involved with the previous PR attempt on the module

**Pull request merged**
