### PR TITLE
nano-wallet: 18.0 -> 19.0

### PR DESCRIPTION
**Pull request by jluttine**
###### Motivation for this change

Update Nano cryptocurrency wallet.

~~**NOTE: This is still work in progress! Any help appreciated.**~~ **EDIT: Works now.**

~~I'm getting the following error when running `nano_wallet`:~~

```
$ nano_wallet
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-org.kde.kwin.qpa.
```

~~Any ideas how to solve this?~~

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jluttine** [comment]
Hmm.. I think I found all relevant help from here: https://github.com/NixOS/nixpkgs/pull/68309

Let's see if it works now..

**Review by jb55 — COMMENTED** [review]
Looks like these commits are signed with an expired key, just a heads up.

**Comment by jluttine** [comment]
Works now!

**Comment by jluttine** [comment]
Oh, thanks for the heads up! Have to fix my key at some point then.

**Comment by mmahut** [comment]
@GrahamcOfBorg build nano-wallet

**Comment by worldofpeace** [comment]
If this is a qt application entirely, it should use `mkDerivation` which is from qt and it automatically adds `wrapQtAppsHook`. The aforementioned PR #68309 actually has changes to reflect that which I requested there also.

**Pull request merged**
