### PR TITLE
python3Packages.ase: 3.21.1 -> 3.22.0

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 3.22.0

Change log: https://wiki.fysik.dtu.dk/ase/releasenotes.html#releasenotes

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 129047` at 638c0dfa run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/80ef5015589a3f54d1338f65d6ebc8ab">python38Packages.dftfit</a></li>
    <li><a href="https://gist.github.com/bca301a570194fb308e1319d0e33dbc7">python38Packages.lammps-cython</a></li>
    <li><a href="https://gist.github.com/8f4a6989e18112b617f0b6eae6bf8a63">python39Packages.lammps-cython</a></li>
  </ul>
</details>
<details>
  <summary>4 packages built successfully:</summary>
  <ul>
    <li>python38Packages.ase</li>
    <li>python38Packages.boltztrap2</li>
    <li>python39Packages.ase</li>
    <li>python39Packages.boltztrap2</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/python-include-tests.md">python-include-tests</a>

Consider adding a `checkPhase` for tests, or if not feasible, `pythonImportsCheck`.

Near pkgs/development/python-modules/ase/default.nix:33:0:
```
   |
33 |     description = "Atomic Simulation Environment";
   | ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 129047` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>python38Packages.dftfit</li>
    <li>python38Packages.lammps-cython</li>
    <li>python39Packages.lammps-cython</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python38Packages.ase</li>
    <li>python38Packages.boltztrap2</li>
    <li>python39Packages.ase</li>
    <li>python39Packages.boltztrap2</li>
  </ul>
</details>

**Comment by fabaff** [comment]
`lammps-cython` will be removed in #129085.

**Review by risicle — APPROVED** [review]
`nixpkgs-review` reveals no new breakage, macos 10.15 & nixos x86_64

**Pull request merged**
