### PR TITLE
Use `hostPlatform.system` in `nixos-generate-config`

### PR DESCRIPTION
**Pull request by name-snrl**
###### Description of changes

Make `nixos-generate-config` respect `nix.package` option

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by name-snrl** [comment]
@roberth @mweinelt @dasJ @Ma27 Could you review, please?

**Review by roberth — COMMENTED** [review]
Looks ok.

I wonder if we should just put the value of `stdenv.hostPlatform.system` as a hardcoded value into the script instead. Asking nix itself seemed like the right thing, but I can't think of a realistic use case that needs to query nix at runtime.

**Comment by name-snrl** [comment]
@roberth I'm not sure about new commit, but it's work for me.

**Review by roberth — APPROVED** [review]

**Comment by roberth** [comment]
Passes installer test.

**Comment by roberth** [comment]
Thanks!

**Comment by tpwrules** [comment]
This breaks things for cross-compiled installer images.

**Comment by roberth** [comment]
@tpwrules what things? If you want the problem to be solved, you'll have to be more specific.

**Comment by tpwrules** [comment]
My apologies. This causes `nixpkgs.hostSystem` to be set to the system type where the installer image was built instead of the system type where `nixos-generate-config` was run. Therefore, on a fresh install, nixpkgs is evaluated for the wrong system and the install fails.

**Comment by roberth** [comment]
@tpwrules The file containing the `nixpkgs.hostPlatform` definition is documented as follows

> /etc/nixos/hardware-configuration.nix
>           This module sets NixOS configuration options based on your current hardware configuration.

My reasoning for using `hostPlatform` directly, is that `nixos-generate-config` is meant to run on the host* hardware.
So far so good, but how does `nixos-generate-config` even run on the final hardware? I've assumed that you would cross compile `nixos-generate-config`, because otherwise it can't run on the final hardware.

The previous behavior was to pull from `builtins.currentSystem` aka the `system` option in `nix.conf` or whatever Nix itself was built with. I would expect that value to coincide with `hostPlatform` as well. So I'm skeptical that reverting this PR would fix your problem.

> if there's a better source to fill in this field in a hard-coded manner.

I'm not aware of a better source than eval-time `hostPlatform` which is generally equal to the runtime nix `system` on the host, including on a cross compiled installer image (I would surely expect).

You mention an installer image. Where did that image come from? Maybe something is wrong about the image?

Or maybe it should be made a bit more clear that you're not supposed to use a `hardware-configuration.nix` generated on one machine for the configuration of a different machine. It kind of seems like that's what you're doing, and it wouldn't work well for other reasons, like wrong file system labels and driver modules.


\* (perhaps superfluously) _host_ from the GNU terminology: _build_ is where the build is performed, _host_ is where the output of the build runs, _target_ is irrelevant because a NixOS configuration is not a compiler we're compiling.

**Comment by tpwrules** [comment]
I publish my own cross-compiled installer images [here](https://github.com/tpwrules/nixos-apple-silicon/tree/6b08b1821c45601c6833c9e5e391c0ab777631a5). They are designed to be cross-compiled from `x86_64-linux` to `aarch64-linux` (or built natively on `aarch64-linux`). When the cross-compiled image is booted on the `aarch64-linux` device and `nixos-generate-config` is run from that image on that device, it puts `nixpkgs.hostPlatform = "x86_64-linux";` into `hardware-configuration.nix` and the system does not build. It is absolutely not the case that `hardware-configuration.nix` is being moved between systems.

Using the linked commit on an `x86_64-linux` system:
```
$ nix eval .#installer-bootstrap.config.system.build.nixos-generate-config.stdenv.hostPlatform.system
"aarch64-linux"

$ nix eval .#installer-bootstrap.config.system.build.nixos-generate-config.system
"x86_64-linux"

$ nix build .#installer-bootstrap.config.system.build.nixos-generate-config

$ cat result/bin/nixos-generate-config | grep hostPlatform
push @attrs, "nixpkgs.hostPlatform = lib.mkDefault \"x86_64-linux\";";
```

You are right that `hostPlatform` is the right attribute and I did have a misconception about the terminology. But there is something wrong and the wrong `hostPlatform` is clearly being substituted even though the cross-compiled system builds and boots successfully and has for many months. It's not immediately clear to me what the issue is. Do you have any ideas?

**Comment by roberth** [comment]
https://github.com/NixOS/nixpkgs/pull/237218 should fix it. Could you give it a try?

**Pull request merged**
