### PR TITLE
mate: update stable packages

### PR DESCRIPTION
**Pull request by romildo**
###### Motivation for this change

There are some new patch level updates for the Mate Desktop Environment.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by worldofpeace** [comment]
@romildo Could this also go into 20.09?

**Comment by romildo** [comment]
> @romildo Could this also go into 20.09?

Sure.

**Comment by romildo** [comment]
Links to upstream changes:

https://github.com/mate-desktop/caja-extensions/releases/tag/v1.24.1
https://github.com/mate-desktop/engrampa/releases/tag/v1.24.1
https://github.com/mate-desktop/eom/releases/tag/v1.24.1
https://github.com/mate-desktop/libmatekbd/releases/tag/v1.24.1
https://github.com/mate-desktop/libmatemixer/releases/tag/v1.24.1
https://github.com/mate-desktop/libmateweather/releases/tag/v1.24.1
https://github.com/mate-desktop/mate-applets/releases/tag/v1.24.1
https://github.com/mate-desktop/mate-backgrounds/releases/tag/v1.24.2
https://github.com/mate-desktop/mate-calc/releases/tag/v1.24.1
https://github.com/mate-desktop/mate-common/releases/tag/v1.24.2
https://github.com/mate-desktop/mate-control-center/releases/tag/v1.24.1
https://github.com/mate-desktop/mate-desktop/releases/tag/v1.24.1
https://github.com/mate-desktop/mate-media/releases/tag/v1.24.1
https://github.com/mate-desktop/mate-menus/releases/tag/v1.24.1
https://github.com/mate-desktop/mate-notification-daemon/releases/tag/v1.24.1
https://github.com/mate-desktop/mate-panel/releases/tag/v1.24.1
https://github.com/mate-desktop/mate-power-manager/releases/tag/v1.24.2
https://github.com/mate-desktop/mate-screensaver/releases/tag/v1.24.1
https://github.com/mate-desktop/mate-sensors-applet/releases/tag/v1.24.1
https://github.com/mate-desktop/mate-session-manager/releases/tag/v1.24.1
https://github.com/mate-desktop/mate-settings-daemon/releases/tag/v1.24.1
https://github.com/mate-desktop/mate-system-monitor/releases/tag/v1.24.1
https://github.com/mate-desktop/mate-terminal/releases/tag/v1.24.1
https://github.com/mate-desktop/pluma/releases/tag/v1.24.1

**Comment by worldofpeace** [comment]
- engrampa:
We could enable libmagic to mime-type for zstd files https://github.com/mate-desktop/engrampa/blob/6b2b3b41ac74254d0dcd3a22d8e6fec2be499a90/configure.ac#L145

Everything else seemed fine, thanks for the links :+1:

**Pull request merged**
