### PR TITLE
warzone2100: fixup build after vulkan update

### PR DESCRIPTION
**Pull request by vcunat**
* #250795 
* https://github.com/Warzone2100/warzone2100/pull/3353

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
@fgaz this doesn't pull the PR.

**Comment by fgaz** [comment]
Huh, I guess I saw the URL and my brain went "ah yes, fetchpatch".

Anyway, the PR got merged, so there _is_ a patch we can fetch now.

**Comment by vcunat** [comment]
I'm not up to resolving that
```
       > patching file lib/ivis_opengl/gfx_api_vk.cpp
       > Hunk #2 succeeded at 527 (offset -28 lines).
       > Hunk #3 succeeded at 1546 (offset -220 lines).
       > Hunk #4 succeeded at 1610 with fuzz 1 (offset -220 lines).
       > Hunk #5 succeeded at 1743 (offset -229 lines).
       > Hunk #6 FAILED at 2026.
       > Hunk #7 FAILED at 2245.
       > Hunk #8 FAILED at 2362.
       > 3 out of 8 hunks FAILED -- saving rejects to file lib/ivis_opengl/gfx_api_vk.cpp.rej
       For full logs, run 'nix log /nix/store/v4qikgp2cznrlrsg242agq1wrgzh3zcx-warzone2100-4.3.5.drv'.
```

**Comment by fgaz** [comment]
Ow. Yeah, let's just replace the string then. I'll try to remember to remove it on the next update.

**Review by fgaz — APPROVED** [review]

**Pull request merged**
