### PR TITLE
perl: fix cross compiling

### LINKED ISSUE #348662: Build failure: pkgsLLVM.perl540
### Steps To Reproduce

1. build pkgsLLVM.perl540

### Build log

```
Don't worry if any of the following aren't found...
I don't see ar out there, offhand.
I don't see bison out there, either.
I don't see byacc out there, either.
cpp is in /nix/store/1n6bqr2y3s54115ppx3b3pw1lzxlqf71-clang-18.1.8/bin/cpp.
I don't see csh out there, either.
date is in /nix/store/cqnb5spmpzvc32h16568s028frzvz8hs-coreutils-9.5/bin/date.
egrep is in /nix/store/hz0n7bgpmnkvd83kz7ahgd899yiwrvsa-gnugrep-3.11/bin/egrep.
I don't see gmake out there, either.
gzip is in /nix/store/zf7spazb812ddrhkw07b7d245rhpsc1d-gzip-1.13/bin/gzip.
I don't see less out there, either.
ln is in /nix/store/cqnb5spmpzvc32h16568s028frzvz8hs-coreutils-9.5/bin/ln.
make is in /nix/store/77mvb93h7g9479lq4myxz9zvvhcj2ckh-gnumake-4.4.1/bin/make.
I don't see more out there, either.
I don't see nm out there, either.
I don't see nroff out there, either.
I don't see perl out there, either.
I don't see pg out there, either.
test is in /nix/store/cqnb5spmpzvc32h16568s028frzvz8hs-coreutils-9.5/bin/test.
uname is in /nix/store/cqnb5spmpzvc32h16568s028frzvz8hs-coreutils-9.5/bin/uname.
I don't see zip out there, either.
Using the test built into your sh.

Checking compatibility between /nix/store/cqnb5spmpzvc32h16568s028frzvz8hs-coreutils-9.5/bin/echo and builtin echo (if any)...
They are compatible.  In fact, they may be identical.
The following message is sponsored by

  Dresden.pm<--The stars should be here.

Dear Perl user, system administrator or package
maintainer, the Perl community sends greetings to
you. Do you (emblematical) greet back [Y/n]? n


Symbolic links are supported.

Checking how to test for symbolic links...
You can test for symbolic links with 'test -h'.
Checking for cross-compile
No targethost for running compiler tests against defined, running locally

Good, your tr supports [:lower:] and [:upper:] to convert case.
Using [:upper:] and [:lower:] to convert case.
./UU/checkcc: line 10: cc: command not found
You need to find a working C compiler.
Either (purchase and) install the C compiler supplied by your OS vendor,
or for a free C compiler try http://gcc.gnu.org/
I cannot continue any further, aborting.
```

### Notify maintainers

@marcusramberg bumped perl which led me to finding this problem

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by RossComputerGuy**
## Things done

Fixes #348662

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Artturin — APPROVED** [review]
✅️ if 0 rebuilds (or no mass rebuild)

**Comment by RossComputerGuy** [comment]
Result of `nixpkgs-review` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by RossComputerGuy** [comment]
Merging now that rebuilds are 0

**Comment by stigtsp** [comment]
Hi @RossComputerGuy

That's quite a short turnaround time.

Although it looks OK afaik - and it only affects static/cross, I think it would be great to have more than a two hour review window for changes to `perl`.

**Pull request merged**
