### PR TITLE
[Backport release-24.11] dotnet: migrate nuget lockfiles to JSON

### PR DESCRIPTION
**Pull request by corngood**
Backport of #362278

I've removed all conflicting packages from the treewide commit.

Cc: @NixOS/dotnet 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by corngood** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 366269`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 1 package blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 3 packages built:</summary>
  <ul>
    <li>nixpkgs-manual</li>
    <li>nuget-to-json</li>
    <li>nuget-to-nix</li>
  </ul>
</details>

**Comment by MattSturgeon** [comment]
> I've removed all conflicting packages from the treewide commit.

Would it be reasonable to re-generate json lockfiles for those packages too, and amend the treewide commit?

> ✅ 3 packages built:

Had me worried there was an eval difference, but of course it is the infrastructure packages that are actually _supposed_ to be different.

**Comment by corngood** [comment]
> Would it be reasonable to re-generate json lockfiles for those packages too, and amend the treewide commit?

I sort of don't think it's worth the effort, because it's mostly due to packages that have already made changes that weren't backported.  If someone wants to do it though, I have no problem with that.

**Comment by MattSturgeon** [comment]
> > Would it be reasonable to re-generate json lockfiles for those packages too, and amend the treewide commit?
> 
> I sort of don't think it's worth the effort, because it's mostly due to packages that have already made changes that weren't backported.

That's fair.

> If someone wants to do it though, I have no problem with that.

If so, probably best to use @GGG-KILLER's script: https://gist.github.com/GGG-KILLER/3a52e6244bbd14dd38e27f115e0ad2d6

**Comment by GGG-KILLER** [comment]
If possible I think it'd be better to migrate all lockfiles to JSON to make it easier on people who want to backport changes after our treewide on master.

If you'd like I could do that on another PR since I don't have write perms to your branch.

**Comment by GGG-KILLER** [comment]
@corngood I've pushed my changes to https://github.com/GGG-KILLER/nixpkgs/tree/backport-362278-to-release-24.11

**Comment by corngood** [comment]
@GGG-KILLER I grabbed your branch, plus those two fixes.  Let me know what you think.  Thanks for doing the rest of the conversions.

**Comment by MattSturgeon** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 366269`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 1 package blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 3 packages built:</summary>
  <ul>
    <li>nixpkgs-manual</li>
    <li>nuget-to-json</li>
    <li>nuget-to-nix</li>
  </ul>
</details>

**Review by MattSturgeon — APPROVED** [review]

**Review by GGG-KILLER — APPROVED** [review]
Looks good to me!

**Pull request merged**
