### PR TITLE
stdenv: aarch64-linux: gcc9 -> gcc11

### PR DESCRIPTION
**Pull request by wegank**
###### Description of changes

Here we go!

```bash
$ nix-build -A stdenv
/nix/store/x0vcrqypn803in7i7hdd3ll8r9fqhbks-stdenv-linux
```

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tpwrules** [comment]
I was unaware that a PR got merged to make this happen? Testing now...

**Comment by wegank** [comment]
@tpwrules The fix came from #209055.

**Comment by wegank** [comment]
@ofborg build stdenv

**Comment by wegank** [comment]
And it goes well on Hydra too.

**Comment by tpwrules** [comment]
`icu` fails to build still, with a different error granted, but it's about the same symbol:

```
g++ -O2 -W -Wall -pedantic -Wpointer-arith -Wwrite-strings -Wno-long-long -std=c++11     -o ../../bin/makeconv gencnvex.o genmbcs.o makeconv.o ucnvstat.o -L../../lib -licutu -L../../lib -licui18n -L../../lib -licuuc -L../../stubdata -licudata -lpthread -lm  
/nix/store/dgbbnlsmwx9vbk43adypvc4dqylfag9n-binutils-2.39/bin/ld: ../../bin/makeconv: hidden symbol `__aarch64_ldadd4_acq_rel' in /nix/store/ihjgrb8nbdi885sm042bfpvh269vd6m3-gcc-11.3.0/lib/gcc/aarch64-unknown-linux-gnu/11.3.0/libgcc.a(ldadd_4_4.o) is referenced by DSO
/nix/store/dgbbnlsmwx9vbk43adypvc4dqylfag9n-binutils-2.39/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
```

`dejagnu` is fine though

**Comment by tpwrules** [comment]
Confirmed that `icu` and `dejagnu` both build at the commit before this one so upgrading to 11 definitely still breaks things.

**Comment by trofi** [comment]
> The fix came from #209055.

Unfortunately it's a no-op change as long as we we use `bootstrap -> binutils -> glibc -> binutils` bootstrap sequence (here `glibc` still embeds `libgcc_s.so.1` from `bootstrap`).

It will have an effect only after https://github.com/NixOS/nixpkgs/pull/209063 gets merged. There `bootstrap -> gcc -> binutils -> glibc -> binutils` will have a chance to embed newer `libgcc_s.so.1`.

**Pull request closed without merging**
