### PR TITLE
python3Packages.pyjwt: 2.1.0 -> 2.3.0

### PR DESCRIPTION
**Pull request by bryanasdev000**
###### Motivation for this change

Update to the latest release.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [X] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by thiagokokada — COMMENTED** [review]
This rebuild number seems to be much more scary than I initially thought, calling the Python folks.

CC @jonringer @SuperSandro2000 @fabaff .

**Comment by fabaff** [comment]
The update to 2.1 required a bunch of fixes as there are modules which are pinning `PyJWT`.

Rebuilds around 90 or so for 2.1

**Comment by SuperSandro2000** [comment]
> This rebuild number seems to be much more scary than I initially thought, calling the Python folks.
> 
> CC @jonringer @SuperSandro2000 @fabaff .

Yeah, please target staging. Maybe this should be part of an python-unstable run?

**Review by jonringer — COMMENTED** [review]
```
# finding the common merge base will avoid pinging all CODEOWNERs
common=$(git merge-base origin/master origin/staging)
git rebase --onto=$common HEAD~1 # or however many commits you want to pull
git push .. ... --force
```
then change the base branch in the github PR from `master` -> `staging`

See https://nixos.org/nixpkgs/manual/#submitting-changes-staging-branch for more details on staging branch

**Comment by bryanasdev000** [comment]
Changed target branch to `staging`.

**Review by thiagokokada — APPROVED** [review]
LGTM.

Wait until the checks finishes running.

**Pull request merged**
