### PR TITLE
Shake+

### PR DESCRIPTION
**Pull request by deepfire**
This was tested against a roughly two-month-old master.

Unable test it on fresh master, due to unrelated problems (extra-utils failures), so submitting it anyway, for it to be checked against the CI.

### CODE REVIEW

**Comment by peti** [comment]
Do you realize that `shake 0.15` is already available in Nixpkgs under the attribute `haskellngPackages.shake`?

**Comment by jagajaga** [comment]
@peti when we are going to drop `haskellPackages`?

**Comment by peti** [comment]
When we switch to GHC 7.10.1. Certainly before forking off the next release branch.

**Comment by jagajaga** [comment]
@peti thank you. So maybe close this PR?

**Comment by peti** [comment]
@deepfire, please re-open this PR if the other version of shake turns out to be unsatisfactory to you for some reason!

**Pull request closed without merging**
