### PR TITLE
dotnet: expose stage0 vmr derivations

### PR DESCRIPTION
**Pull request by corngood**
This is only meant to be a helper for testing, so recursion is disabled.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by corngood** [comment]
FYI @NixOS/dotnet

I couldn't find anything exactly like this in nixpkgs, but it's useful for testing the state0 derivations.  For example `dotnetCorePackages.dotnet_8.stage0.sdk.tests`.

**Comment by GGG-KILLER** [comment]
> I couldn't find anything exactly like this in nixpkgs, but it's useful for testing the stage0 derivations.  For example `dotnetCorePackages.dotnet_8.stage0.sdk.tests`.

Maybe a dumb question, but what's the point of testing stage0? Wouldn't this be covered by testing the final package?

**Comment by corngood** [comment]
> Maybe a dumb question, but what's the point of testing stage0? Wouldn't this be covered by testing the final package?

Since it takes so long to build, it's nice to be able to check things on stage0 first.  In the past I've just hacked the source to point to stage0, but this makes it a bit easier.

**Comment by GGG-KILLER** [comment]
> Since it takes so long to build, it's nice to be able to check things on stage0 first.  In the past I've just hacked the source to point to stage0, but this makes it a bit easier.

Wouldn't it be better to add stuff to `checkPhase` then instead?
That way if stage0 failed it wouldn't continue building the rest

**Comment by corngood** [comment]
> Wouldn't it be better to add stuff to checkPhase then instead?

`checkPhase` runs in the build environment for vmr, and the tests I'm thinking about are in other derivations like `.sdk.tests`.

**Comment by GGG-KILLER** [comment]
> `checkPhase` runs in the build environment for vmr, and the tests I'm thinking about are in other derivations like `.sdk.tests`.

I see, fair enough then, I don't really see any problem with exposing stage0 as long as it doesn't show up in `search.nixos.org`.

**Review by GGG-KILLER — APPROVED** [review]
LGTM

**Comment by corngood** [comment]
> as long as it doesn't show up in search.nixos.org.

Yeah, that's the sort of thing I was worried about, but I think I'm doing it the right way.  I just couldn't find anything in nixpkgs that had a similar intention (i.e. something meant to be used only for nixpkg development).

**Pull request merged**
