### PR TITLE
pypi2nix: 1.6.0 -> 1.8.0

### PR DESCRIPTION
**Pull request by garbas**
###### Motivation for this change

update to flake8 and its deps is also needed

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by taku0** [comment]
Should the `firefox-bin` commit be a separate PR?

**Comment by garbas** [comment]
@taku0 right. well if the Travis will succeed I'm going to push it to master anyway.

**Comment by garbas** [comment]
ah travis reaches 10k limit ... I will build this on my hydra and if successful I will push to master

**Comment by FRidh** [comment]
mccabe and flake8 are typically tricky to upgrade. Often packages require an older version which is why we're still stuck on these versions.

**Comment by garbas** [comment]
@FRidh flake8 fails for me on python35, when running it not when building it

**Comment by garbas** [comment]
well i'll just push pypi2nix with checkPhase disabled

**Pull request closed without merging**
