### PR TITLE
Added cwm to window managers

### PR DESCRIPTION
**Pull request by paspanag**
Hi guys, I incorporated the comments from pSub into this pull request.

### CODE REVIEW

**Comment by jagajaga** [comment]
Please properly name commit following our `CONTRIBUTING.md`.

**Comment by paspanag** [comment]
Hmmm. It automatically closed. I moved the changes to a branch as describe in the contributing.md. Sorry about this, new to contributing (and following the guide in nixos.org/wiki/Contributing_to_nixpkgs).

Should I open a third pull request? Or re-add the change into my master branch?

**Comment by jagajaga** [comment]
You have to rebase and force push to your branch. Do not create new PR.

**Comment by paspanag** [comment]
OK. I've added the changes to my master. Re-opening.

**Comment by jagajaga** [comment]
There are extra commits now :)

**Comment by garbas** [comment]
@paspanag tnx! i've cherry-picked that one commit from your PR. i know you'll submit perfect PR next time and made @jagajaga and everybody happy :)

**Comment by paspanag** [comment]
Sorry I just got this now. Thanks! I'll make sure to follow the guidelines and readme's closer next time.

**Pull request closed without merging**
