### PR TITLE
aws-iam-authenticator: 0.4.0 -> 0.5.2

### PR DESCRIPTION
**Pull request by ivankovnatsky**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ivankovnatsky** [comment]
did not invest much time into this for now:

```console
builder for '/nix/store/d8haqdf4av9dg4wjpz0lzapz9zs61yn1-aws-iam-authenticator-0.5.2.drv' failed with exit code 1; last 10 log lines:
          /nix/store/v76kr0rbcghcc6vx70k6xdd2ifqid98c-go-1.15.6/share/go/src/sigs.k8s.io/aws-iam-authenticator/pkg/mapper (from $GOROOT)
         /build/go/src/sigs.k8s.io/aws-iam-authenticator/pkg/mapper (from $GOPATH)
  go/src/github.com/kubernetes-sigs/aws-iam-authenticator/cmd/aws-iam-authenticator/server.go:26:2: cannot find package "sigs.k8s.io/aws-iam-authenticator/pkg/server" in any of:
    /build/go/src/github.com/kubernetes-sigs/aws-iam-authenticator/vendor/sigs.k8s.io/aws-iam-authenticator/pkg/server (vendor tree)
       /nix/store/v76kr0rbcghcc6vx70k6xdd2ifqid98c-go-1.15.6/share/go/src/sigs.k8s.io/aws-iam-authenticator/pkg/server (from $GOROOT)
         /build/go/src/sigs.k8s.io/aws-iam-authenticator/pkg/server (from $GOPATH)
  go/src/github.com/kubernetes-sigs/aws-iam-authenticator/cmd/aws-iam-authenticator/token.go:23:2: cannot find package "sigs.k8s.io/aws-iam-authenticator/pkg/token" in any of:
      /build/go/src/github.com/kubernetes-sigs/aws-iam-authenticator/vendor/sigs.k8s.io/aws-iam-authenticator/pkg/token (vendor tree)
        /nix/store/v76kr0rbcghcc6vx70k6xdd2ifqid98c-go-1.15.6/share/go/src/sigs.k8s.io/aws-iam-authenticator/pkg/token (from $GOROOT)
          /build/go/src/sigs.k8s.io/aws-iam-authenticator/pkg/token (from $GOPATH)
cannot build derivation '/nix/store/2a4h1nhn2baf4qijrmsy644qc159gw3g-env.drv': 1 dependencies couldn't be built
```

will get back.

**Comment by NelsonJeppesen** [comment]
I started work on this before I saw this PR - I did get a build working if you want to steal my code https://github.com/NelsonJeppesen/nixpkgs/commit/edc923a40caff11d1291098d59bf3422857a59c4

I'm brand new to Nix, but it was recomened to me to switch to `buildGoModule`

**Comment by ivankovnatsky** [comment]
Hey @NelsonJeppesen, as you say, if you didn't raise a pr we probably could do it here, to minimize actions.

**Comment by kalbasit** [comment]
@GrahamcOfBorg build aws-iam-authenticator

**Review by kalbasit — COMMENTED** [review]
Please set ldflags to `-s -w` at the minimum to shrink the size of the binary (look for examples in nixpkgs). I recommend also looking upstream if they support embedding a version in the binary.

**Comment by kalbasit** [comment]
@ivankovnatsky I'm afk, could please double check that the version is reported correctly by the binary? 

Also, your last commit is removing stdenv that you added in the first commit, please squash those two commits so you end up with two commits one for the update and the other for ldflags.

**Review by kalbasit — APPROVED** [review]

**Comment by ivankovnatsky** [comment]
@kalbasit good catch, thanks. i'm not a big expert in go software packaging, so i took it from here: https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/master/.goreleaser.yaml#L16.

but i still could not get the version running the cli (sorry i didn't respond earlier, will create new pr no problem):

```console
tools/security/aws-iam-authenticator on  patch-10 ❯ nix-build -E 'with import <nixpkgs> {} ; callPackage ./default.nix {}';
/nix/store/b6q5pb3wdxvl21n5vzwhy9prf929m9a7-aws-iam-authenticator-0.5.2
tools/security/aws-iam-authenticator on  patch-10 ❯ ./result/bin/aws-iam-authenticator version
{"Version":"unversioned"}
tools/security/aws-iam-authenticator on  patch-10 ❯
```

am i doing it wrong?

**Comment by kalbasit** [comment]
@ivankovnatsky no worries I pushed https://github.com/NixOS/nixpkgs/commit/ab987e26d5d5cfc860ba576fd66e47f30acb8314 to fix it. The version variable used to be called differently in version 0.5.2 as you can see [here](https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/292b9b82df69b87af962b92485b254d9f4b10f00/.goreleaser.yaml#L16).

**Comment by ivankovnatsky** [comment]
@kalbasit, good catch, thanks.

**Pull request merged**
