### PR TITLE
GIMP 2.10

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
https://www.gimp.org/release-notes/gimp-2.10.html

Depends on https://github.com/NixOS/nixpkgs/pull/36371

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jtojnar** [comment]
```
Missing fast-path babl conversion detected, Implementing missing babl fast paths
accelerates GEGL, GIMP and other software using babl, warnings are printed on
first occurance of formats used where a conversion has to be synthesized
programmatically by babl based on format description

*WARNING* missing babl fast path(s): "R'G'B' double" to "CIE Lab double"
Traceback (most recent call last):
  File "/nix/store/7zw5c9kdry6mqb2b7l860yk870fsdzcb-gimp-2.10.0-RC2/lib/gimp/2.0/plug-ins/python-console/.python-console.py-wrapped", line 20, in <module>
    from gimpfu import *
  File "/nix/store/7zw5c9kdry6mqb2b7l860yk870fsdzcb-gimp-2.10.0-RC2/lib/gimp/2.0/python/gimpfu.py", line 76, in <module>
    import gimp
ImportError: libgegl-0.3.so.0: cannot open shared object file: No such file or directory
result/bin/gimp: LibGimpBase-WARNING: gimp: gimp_wire_read(): error
```

**Comment by jtojnar** [comment]
I fixed the rpath bug ([upstream issue](https://bugzilla.gnome.org/show_bug.cgi?id=795620)), the warning is not an issue according to GIMP maintainers.

**Comment by Ma27** [comment]
@jtojnar any change to get this backported? GIMP 2.10 is a real game changer and I'm quite sure that some more folks building from stable would love to use this as well %)

**Comment by jtojnar** [comment]
@Ma27 I do not think so, it depends on recent freetype or fontconfig.

**Comment by jtojnar** [comment]
Sure, the repo is MIT licensed after all.

**Comment by Ma27** [comment]
@jtojnar I know I was just unsure if you don't want to do the backport (which is absolutely fine) or if there are further technical reasons I'm missing %)

**Comment by jtojnar** [comment]
I just do not really care about release branches. One thing to consider is whether we want to have GIMP 2.10 replace 2.8 since three plug-ins will no longer work with 2.10 (see above) – taking the [policy](https://groups.google.com/forum/#!topic/nix-devel/3KxPNwxDV9E) literally, that would not be allowed.

**Comment by Ma27** [comment]
just talked to @fpletz about this issue, he says (as well) that there are way too much dependencies to backport so this might not be such a good idea :-)

**Pull request merged**
