### PR TITLE
nixos/pam: add fingerprint auth ordering

### PR DESCRIPTION
**Pull request by bd-g**
###### Description of changes

Add option to allow use of a password if you cannot `Ctrl+C` fingerprint authentication (due to a lack of a shell). Described in [Arch Wiki](https://wiki.archlinux.org/title/Fprint#Login_configuration) and [one potential discussion thread](https://discourse.nixos.org/t/strange-lock-screen-behaviour-with-fprintd-enabled/10248/2)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bd-g** [comment]
@RaitoBezarius I saw you reviewed another Pam PR, could you take a look at this?

I noticed you wanted a test included on the  other PR - I'm not sure how to form an independent test for this PR that wouldn't be fluff, since it seems to be just an ordering thing. But I can write one up if you'd like.

**Comment by RaitoBezarius** [comment]
> @RaitoBezarius I saw you reviewed another Pam PR, could you take a look at this?
> 
> I noticed you wanted a test included on the other PR - I'm not sure how to form an independent test for this PR that wouldn't be fluff, since it seems to be just an ordering thing. But I can write one up if you'd like.

I still need a test for any PAM PRs that I judge having the potential of breaking things (almost all of them), that's my policy.

If you can provide a test, we can proceed.

**Comment by bd-g** [comment]
@RaitoBezarius I added a test as requested, and also added the other existing tests to the pam passthru.tests attribute for automatic testing in the future.

**Review by RaitoBezarius — CHANGES_REQUESTED** [review]
Thank you a lot for the very interesting test, but it's only testing the contents of the document, it's not testing whether you can still login with password or fingerprint in the right order, take a look to the other PAM tests like the ZFS key one, which goes ahead and tries to login, etc. Do you think it's possible to have such a test?
This test does not test the functionality "can I still login into my system" beyond poking around PAM impl details, I believe?

**Comment by RaitoBezarius** [comment]
Also please cleanup the commit history according to the CONTRIBUTING guide

**Comment by bd-g** [comment]
Closing this, as the refactor of the main Pam module to allow explicit ordering of contents is a more generalized solution that addresses the original concern of this PR!

**Pull request closed without merging**
