### PR TITLE
hcloud: 1.11.0 -> 1.13.0

### PR DESCRIPTION
**Pull request by elmarx**
###### Motivation for this change

Update hcloud v1.11.0 to v1.13.0

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

@petabyteboy already created a PR for 1.11.0 -> 1.12.0 which did not yet get merged, but is somehow superseeded by the update to 1.13.0

### CODE REVIEW

**Comment by petabyteboy** [comment]
Built and ran resulting binary :+1: 
Closure size increased from 38.9M to 39.3M, which seems fine for this update

**Comment by petabyteboy** [comment]
If you like you can add quotes to the homepage (https://github.com/NixOS/rfcs/pull/45) and change `name = "hcloud-${version}";` to `pname = "hcloud";`.

**Comment by zauberpony** [comment]
Ah great, I didn't know about these, thanks for the info! I implemented the changes you proposed :)

**Review by angristan — APPROVED** [review]
Successful build and run:

```sh
[nix-shell:~/.cache/nix-review/pr-65599]$ hcloud version
hcloud 1.13.0
```

**Pull request merged**
