### PR TITLE
nixos/portunus: fix portunus not only listening on localhost

### LINKED ISSUE #221678: Portunus doesn't just listen on localhost in NixOS
The option ```services.portunus.port``` is described as:

```
Description: Port where the Portunus webserver should listen on. This must be put behind a
  TLS-capable reverse proxy because Portunus only listens on localhost.
```
Declared in: [nixos/modules/services/misc/portunus.nix](https://github.com/NixOS/nixpkgs/blob/nixos-22.11/nixos/modules/services/misc/portunus.nix)

But this is inaccurate, it listens on *:8080, which is a potential security issue.

```
$ sudo ss --listening  -t --processes
State    Recv-Q   Send-Q       Local Address:Port              Peer Address:Port   Process
LISTEN   0        2048               0.0.0.0:ldap                   0.0.0.0:*       users:(("slapd",pid=621556,fd=7))
LISTEN   0        4096                     *:http-alt                     *:*       users:(("portunus-server",pid=621554,fd=11))
LISTEN   0        2048                  [::]:ldap                      [::]:*       users:(("slapd",pid=621556,fd=8))
```

NOTE: I haven't looked at the ldap sockets in this issue, but there they are too.

I've patched the module to try ```[::]:8080```, ```[::1]:8080```, ```localhost:8080```, and ```127.0.0.1:8080``` for the value of ```PORTUNUS_SERVER_HTTP_LISTEN```. Here are the results tested with an http client and with ss:

| PORTUNUS_SERVER_HTTP_LISTEN | [::]:8080                 | [::1]:8080         | localhost:8080      | 127.0.0.1:8080     |
|-----------------------------|---------------------------|--------------------|---------------------|--------------------|
| http://127.0.0.1:8080/      | Portunus                  | connection refused | malformed env. var. | Portunus           |
| http://localhost:8080/      | Portunus                  | Portunus           |                     | Portunus           |
| http://192.168.1.27:8080    | Portunus                  | connection refused |                     | connection refused |
| http://[::1]:8080           | Portunus                  | Portunus           |                     | connection refused |
| ipv6 link local address     | not supported by browsers |                    |                     |                    |
| ss --listening -t --numeric | *:8080                    | [::1]:8080        |                     | 127.0.0.1:8080     |

My /etc/hosts maps both127.0.0.1 and ::1 to localhost, so the documented behavior seems impossible. Unless there is a valid notation which captures both loopbacks (please advise), I'll use ```::1``` in the PR, which is the unique IPv6 loopback, and change the documentation to suit.

### Notify maintainers

@majewsky, @SuperSandro2000,  take a look. I'll close the issue on the Portunus site, since the problem is here in nixpkgs.

### PR DESCRIPTION
**Pull request by SuperSandro2000**
Closes #221678

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by acarrico** [comment]
Is there some reason you opened this in favor of #221678?

**Comment by acarrico** [comment]
I think we should close this in favor of #221685 since the existing documentation implies that you could proxy ```http://127.0.0.1:8080/``` and have a working system, but that is not the case, and #221685 makes that clear.

**Review by SuperSandro2000 — COMMENTED** [review]
tested on a deployment and still works

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by SuperSandro2000** [comment]
> Is there some reason you opened this in favor of #221678? (EDIT) Err, I meant #221685, I guess my PR hadn't come through yet.

The documentation update would be wrong now.

**Pull request merged**
