### PR TITLE
elmPackages: update node-packages.nix

### PR DESCRIPTION
**Pull request by qbit**
## Description of changes

Generate a new node-packages.nix. I was explicitly trying to update `elm-language-server` but I couldn't find a clean way to just update the one package.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by qbit** [comment]
Result of `nixpkgs-review pr 279022` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>elmPackages.elm-land</li>
  </ul>
</details>
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>elmPackages.create-elm-app</li>
    <li>elmPackages.elm-coverage</li>
    <li>elmPackages.elm-doc-preview</li>
    <li>elmPackages.elm-git-install</li>
    <li>elmPackages.elm-language-server</li>
    <li>elmPackages.elm-live</li>
    <li>elmPackages.elm-pages</li>
    <li>elmPackages.elm-review</li>
    <li>elmPackages.elm-spa</li>
    <li>elmPackages.elm-upgrade</li>
    <li>elmPackages.elm-verify-examples</li>
  </ul>
</details>

**Comment by qbit** [comment]
hrm.. not sure about elm-land..

**Comment by turboMaCk** [comment]
thanks for the PR but first we will probably need to address the regression in elm compiler itself which is WIP in https://github.com/NixOS/nixpkgs/pull/277326

**Comment by qbit** [comment]
@GrahamcOfBorg build elmPackages

**Comment by turboMaCk** [comment]
It looks like there might be regression in elm-land:

```
warning: Ignoring setting 'auto-allocate-uids' because experimental feature 'auto-allocate-uids' is not enabled
warning: Ignoring setting 'impure-env' because experimental feature 'configurable-impure-env' is not enabled
error: builder for '/nix/store/541a1x8svs27xsa81r72zc86j8axnzj7-elm-land-0.19.5.drv' failed with exit code 1;
       last 10 log lines:
       > npm ERR!
       > npm ERR!
       > npm ERR! NOTE: You can avoid npm entirely by downloading directly from:
       > npm ERR! https://github.com/elm/compiler/releases/tag/0.19.1
       > npm ERR! All this package does is distribute a file from there.
       > npm ERR!
       > npm ERR! --------------------------------------------------------------------------------
       > 
       > npm ERR! A complete log of this run can be found in: /build/.npm/_logs/2024-01-06T20_10_09_494Z-debug-0.log
       > 
       For full logs, run 'nix log /nix/store/541a1x8svs27xsa81r72zc86j8axnzj7-elm-land-0.19.5.drv'.
error: 1 dependencies of derivation '/nix/store/l1ldnr4rvjij8wq6d0g0pwp9i95im9rh-review-shell.drv' failed to build

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/279022

1 package failed to build:
elmPackages.elm-land

```

**Comment by qbit** [comment]
Result of `nixpkgs-review pr 279022` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>elmPackages.create-elm-app</li>
    <li>elmPackages.elm-coverage</li>
    <li>elmPackages.elm-doc-preview</li>
    <li>elmPackages.elm-git-install</li>
    <li>elmPackages.elm-land</li>
    <li>elmPackages.elm-language-server</li>
    <li>elmPackages.elm-live</li>
    <li>elmPackages.elm-pages</li>
    <li>elmPackages.elm-review</li>
    <li>elmPackages.elm-spa</li>
    <li>elmPackages.elm-upgrade</li>
    <li>elmPackages.elm-verify-examples</li>
  </ul>
</details>

**Comment by qbit** [comment]
@turboMaCk thanks! that did it!

**Review by turboMaCk — APPROVED** [review]
LGTM

**Pull request merged**
