### PR TITLE
displaylink: 5.6.1-59.184 -> 5.7.0-61.129

### PR DESCRIPTION
**Pull request by jensbin**
###### Description of changes

* Pull request to update evdi to 1.13.1 and displaymanager to 5.7.
* Needed to use with Linux kernel >= 6.2
* Added TearFree to X config to improve stability

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by archer-65** [comment]
LGTM!

**Review by Janik-Haag — CHANGES_REQUESTED** [review]
This mostly looks good, but please change the commit message to follow our guidelines:
`pname: $old_version -> $new_version`

and spilt it out into two independent commits, one for each package.

**Comment by jensbin** [comment]
Split of the merge requests: evdi -> https://github.com/NixOS/nixpkgs/pull/239883

**Review by Janik-Haag — COMMENTED** [review]
Looks good to me but it says I have to agree some eula before downloading, how can I fix this to test the package? 
```
***
In order to install the DisplayLink drivers, you must first
comply with DisplayLink's EULA and download the binaries and
sources from here:

https://www.synaptics.com/products/displaylink-graphics/downloads/ubuntu-5.7

Once you have downloaded the file, please use the following
commands and re-run the installation:

mv $PWD/"DisplayLink USB Graphics Software for Ubuntu5.7-EXE.zip" $PWD/displaylink-570.zip
nix-prefetch-url file://$PWD/displaylink-570.zip

***
```

**Comment by jensbin** [comment]
Hi, I don't understand the question. The displaylink graphics software needs a manual acceptance before downloading, similar to the citrix_workspace package. This is done on the webpage, as mentioned in the description. I am not aware of how to fix the manual eula acceptance.

**Comment by Janik-Haag** [comment]
I'm sorry I missed that. When I download the file and put it into $PWD which is in my case my local nixpkgs clone and run `nix-build -A displaylink` it still fails with the same error, what am I doing wrong?

**Comment by jensbin** [comment]
Can you paste the error message? Loading of the binary into nix store was successful? 
`nix-prefetch-url file://$PWD/displaylink-570.zip`

**Comment by Janik-Haag** [comment]
Uff i'm just really stupid sorry I some how missed that line....

**Review by Janik-Haag — APPROVED** [review]

**Comment by Janik-Haag** [comment]
Yes I know I was just stupid or too tired or something when I tried this initially.

**Comment by jensbin** [comment]
Verified with:

- HP G5 Universal Dock
- HP Thunderbolt Dock G4

@drupol (https://github.com/NixOS/nixpkgs/pull/239883)

**Review by drupol — APPROVED** [review]

**Comment by Janik-Haag** [comment]
Sorry for the trouble :see_no_evil: 
Btw @jensbin next time you don't have to split it in to two PRs, just one commit per updated package, it is fine if they are in the same PR.

**Pull request merged**
