### PR TITLE
nixos/test/prometheus-exporters/bird: fix race condition

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

https://hydra.nixos.org/build/141423969

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
@mweinelt did the test pass for you? Locally it's hanging with:

```
bird # [  152.440867] bird_exporter[753]: time="2021-04-19T20:06:34Z" level=error msg="dial unix /var/run/bird.ctl: connect: connection refused" source="metric_collector.go:84"
bird # [  153.456306] bird_exporter[753]: time="2021-04-19T20:06:35Z" level=error msg="dial unix /var/run/bird.ctl: connect: connection refused" source="metric_collector.go:84"
bird # [  154.471430] bird_exporter[753]: time="2021-04-19T20:06:36Z" level=error msg="dial unix /var/run/bird.ctl: connect: connection refused" source="metric_collector.go:84"
bird # [  155.487275] bird_exporter[753]: time="2021-04-19T20:06:37Z" level=error msg="dial unix /var/run/bird.ctl: connect: connection refused" source="metric_collector.go:84"
bird # [  156.502348] bird_exporter[753]: time="2021-04-19T20:06:38Z" level=error msg="dial unix /var/run/bird.ctl: connect: connection refused" source="metric_collector.go:84"
```

Though I probably wasn't patient enough :)

**Comment by mweinelt** [comment]
Odd, for me it works. It was racy because the bird socket wouldn't be there yet sometimes.

**Comment by Ma27** [comment]
@mweinelt how long did the test take for you? As I said, maybe I wasn't patient enough :)

**Comment by mweinelt** [comment]
> nix-build -A nixosTests.prometheus-exporters.bird  1.95s user 0.58s system 11% cpu 21.827 total

**Comment by Ma27** [comment]
Hmm so way faster than it was the case locally. Let's see what ofborg has to say :) 

@ofborg test prometheus-exporters.bird

**Comment by mweinelt** [comment]
> bird # [    6.428950] bird[682]: Cannot determine router ID, please configure it manually

**Comment by mweinelt** [comment]
@ofborg test prometheus-exporters.bird

**Pull request merged**
