### PR TITLE
wezterm: 20230408-112425-69ae8472 -> 20230712-072601-f4abf8fd

### PR DESCRIPTION
**Pull request by belak**
###### Description of changes

This updates wezterm to the latest version. I was able to build and run it locally - I'm not sure what else needs to be done to merge this update.

Cargo.toml was copied from https://github.com/wez/wezterm/blob/20230712-072601-f4abf8fd/Cargo.lock

I also wasn't sure if I should add myself to maintainers, or just leave it as-is, but I assume that would be better as a separate PR.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by marcusramberg — APPROVED** [review]
Nice!

**Comment by SuperSandro2000** [comment]
> This updates wezterm to the latest version. I was able to build and run it locally - I'm not sure what else needs to be done to merge this update.

Wait for someone, like me, to merge it.

> I also wasn't sure if I should add myself to maintainers, or just leave it as-is, but I assume that would be better as a separate PR.

That's not required, I can manage things on my own except for special case darwin.

**Comment by marcusramberg** [comment]
> That's not required, I can manage things on my own except for special case darwin.
Looks like the darwin passthrough timed out, I'm running `nixpkgs-review pr 243212` on my mac now.

**Comment by marcusramberg** [comment]
```
1 package built:
wezterm

warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/m0c4cls11gcyhfm1d0k02zh8ndqgs9bp-wezterm-20230712-072601-f4abf8fd.drv^*'
$ /nix/store/bf6vm3ndlrqrv41mswkfyz4agl5q7ahc-nix-2.15.1/bin/nix-shell /Users/marcus/.cache/nixpkgs-review/pr-243212/shell.nix

[nix-shell:~/.cache/nixpkgs-review/pr-243212]$ wezterm --version
wezterm 20230712-072601-f4abf8fd
```

**Comment by SuperSandro2000** [comment]
> Looks like the darwin passthrough timed out

Kinda normal, aarch64-darwin at least worked.

**Comment by gabyx** [comment]
@SuperSandro2000 :What would make it easier for wezterm to be updated here directly?

Could wezterm have a flake.nix or something, or does it need a special CI setp to produce here a PullRequest?
Is therre any automation for this already?
Just curious if we could help here.

**Comment by SuperSandro2000** [comment]
I don't really have an idea right now other than not using git cargo dependencies but we have that mostly solved at this point.

There is already automation through @r-ryantm

**Pull request merged**
