### PR TITLE
skytemple: 1.2.5 -> 1.3.0

### PR DESCRIPTION
**Pull request by sugar700**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by xfix** [comment]
cc @marius851000

**Comment by marius851000** [comment]
That was fast ! I'll test it.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 137310` at 966eadef run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package skipped due to time constraints:</summary>
  <ul>
    <li>skytemple</li>
  </ul>
</details>
<details>
  <summary>8 packages built successfully:</summary>
  <ul>
    <li>python38Packages.dungeon-eos</li>
    <li>python38Packages.skytemple-dtef</li>
    <li>python38Packages.skytemple-files</li>
    <li>python38Packages.skytemple-ssb-debugger</li>
    <li>python39Packages.dungeon-eos</li>
    <li>python39Packages.skytemple-dtef</li>
    <li>python39Packages.skytemple-files</li>
    <li>python39Packages.skytemple-ssb-debugger</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: unused-argument

Unused argument: `fetchpatch`.
Near pkgs/development/python-modules/skytemple-files/default.nix:2:65:
```
  |
2 | , ndspy, pillow, setuptools, skytemple-rust, tilequant, armips, fetchpatch
  |                                                                 ^
```
</li>
  </ul>
</details>

**Comment by marius851000** [comment]
Finished testing, (after spending some time waiting for webkitgtk to compile). Assembly patch work well, and dungeon preview too. Tested on a european rom. Didn't tested applying patch for special process, as they are known to not work with EU rom.

**Pull request merged**
