### PR TITLE
bind: 9.18.17 -> 9.18.18

### PR DESCRIPTION
**Pull request by trofi**
While at it added trivial updater.

Changes: https://bind9.readthedocs.io/en/v9.18.18/notes.html#notes-for-bind-9-18-18

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by trofi** [comment]
Result of `nixpkgs-review pr 250135` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>53 packages built:</summary>
  <ul>
    <li>acme-sh</li>
    <li>asn</li>
    <li>autofs5</li>
    <li>bashSnippets</li>
    <li>bind</li>
    <li>bind.dev</li>
    <li>dig (bind.dnsutils ,dig.dev ,dig.dnsutils ,dig.host ,dig.lib ,dig.man)</li>
    <li>host (bind.host ,host.dev ,host.dnsutils ,host.host ,host.lib ,host.man)</li>
    <li>bind.lib</li>
    <li>bind.man</li>
    <li>blueberry</li>
    <li>check-wmiplus</li>
    <li>checkSSLCert</li>
    <li>cinnamon.cinnamon-common</li>
    <li>cinnamon.cinnamon-gsettings-overrides</li>
    <li>cinnamon.cinnamon-screensaver</li>
    <li>cinnamon.cinnamon-session</li>
    <li>cinnamon.nemo</li>
    <li>cinnamon.nemo-fileroller</li>
    <li>cinnamon.nemo-python</li>
    <li>cinnamon.nemo-with-extensions</li>
    <li>cinnamon.nemo.dev</li>
    <li>cinnamon.pix</li>
    <li>cinnamon.warpinator</li>
    <li>cinnamon.xapp</li>
    <li>cinnamon.xapp.dev</li>
    <li>cinnamon.xreader</li>
    <li>cinnamon.xviewer</li>
    <li>dwm-status</li>
    <li>freeipa</li>
    <li>gnome.gnome-nettool</li>
    <li>hw-probe</li>
    <li>hypnotix</li>
    <li>inxi</li>
    <li>lightdm-slick-greeter</li>
    <li>monitoring-plugins</li>
    <li>nmapsi4</li>
    <li>python310Packages.django-scim2</li>
    <li>python310Packages.django-scim2.dist</li>
    <li>python310Packages.xapp</li>
    <li>python311Packages.django-scim2</li>
    <li>python311Packages.django-scim2.dist</li>
    <li>python311Packages.xapp</li>
    <li>sssd</li>
    <li>sticky</li>
    <li>testssl</li>
    <li>timeshift</li>
    <li>timeshift-minimal</li>
    <li>timeshift-unwrapped</li>
    <li>twa</li>
    <li>wsl-vpnkit</li>
    <li>xed-editor</li>
    <li>xplayer</li>
  </ul>
</details>

**Review by risicle — APPROVED** [review]
`nixpkgs-review` reveals no new failures, macos 10.15 & nixos x86_64. `passthru.tests` pass.

**Comment by vcunat** [comment]
Channel blocked.  I checked that reverting this would fix it but I'd rather drop i686 tests: https://github.com/NixOS/nixpkgs/pull/250563

**Comment by trofi** [comment]
Having spent some time bisecting `bind9` down to https://github.com/isc-projects/bind9/commit/a2c5503bba8ded457efed0cd0dfb376e828d8128 I see you already filed https://gitlab.isc.org/isc-projects/bind9/-/issues/4269.

**Pull request merged**
