### PR TITLE
nixos/haproxy: Implement hitless reloads

### PR DESCRIPTION
**Pull request by talyz**
###### Motivation for this change
Since 1.8 HAProxy has had support for hitless reloads. Implement support for this and prefer reloading over restarting the service.

For this to work properly, we need to switch the service type back to `forking`, since `notify` sadly doesn't allow new processes to be spawned and take over in `ExecReload`.

###### Things done

I've stress tested the configuration by using `hey` and reloading the `haproxy` service in a loop, yielding good results.

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by peterhoeg** [comment]
Based on my reading of https://www.haproxy.com/blog/hitless-reloads-with-haproxy-howto/, `forking` isn't necessary. Did you try it out without?

**Comment by talyz** [comment]
Yeah, I tried to get it working with `notify` first, but ran into trouble since systemd only expects the process started by `ExecReload` to send a message or signal to the main process and exit, not actually replace the main process. The upstream unit file implements reloads by sending the `SIGUSR2` signal to the main process, which should work fine on FHS, but since we don't replace either the binary or configuration, reexecing isn't good enough - we need to replace the process by starting the new binary in `ExecReload`. This behavior is only possible with `forking`, it seems, since systemd checks the `PIDFile` to learn the main process PID even after a reload.

**Comment by aanderse** [comment]
Oops.

What I meant to say: https://github.com/NixOS/nixpkgs/pull/88434

**Comment by peterhoeg** [comment]
Thanks for doing this @talyz  - the referenced PR covers quite a bit more (and has tests), so I suggest to continue the work over there.

**Pull request closed without merging**
