### PR TITLE
podman: ensure paths exist for the wrapper

### LINKED ISSUE #162694: Unable to update system with home-manager and `podman`
### Describe the bug

With `podman` installed to `home.packages`, running `home-manager switch` results in:

```
building '/nix/store/8rir90i2sgmyyqcsazm8vmac5wxgrp52-home-manager-path.drv'...
error: not a directory: `/nix/store/yyqyc86np5bisl5a1g25wvdvvamrxc1v-podman-wrapper-4.0.2/etc'
builder for '/nix/store/8rir90i2sgmyyqcsazm8vmac5wxgrp52-home-manager-path.drv' failed with exit code 2
```

### Steps To Reproduce

1. Add `podman` to `home.packages`
2. `home-manager switch`

### Expected behavior

Switch continues without error.

### Additional context

Strangely, building in `nixpkgs` seems to work fine: `nix-build -A podman`. If I pin podman to 4ee1f9eafc15a291bbb838f80a47bf2f4c97ce80 there is no problem. So it seems related to https://github.com/NixOS/nixpkgs/pull/161130.

### Notify maintainers

@marsam @zowoq 

### Metadata

```yaml
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.3.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.6`
 - channels(abutler): `"home-manager, nixpkgs-22.05pre358575.ad267cc9cf3"`
 - nixpkgs: `/Users/abutler/.nix-defexpr/channels/nixpkgs`
```

### PR DESCRIPTION
**Pull request by zowoq**
###### Motivation for this change

Easier than doing platform specific wrapping. 

Fixes #162694

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by austinbutler** [comment]
Result of `nixpkgs-review pr 162695` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>podman</li>
    <li>podman-unwrapped</li>
  </ul>
</details>

**Review by austinbutler — APPROVED** [review]

**Comment by zowoq** [comment]
> Result of nixpkgs-review ...

`nixpkgs-review` isn't helpful for this, can you confirm that the `home-manager` issue is resolved?

**Comment by austinbutler** [comment]
I approved it because yes it does resolve it.

**Review by saschagrunert — APPROVED** [review]
LGTM

**Pull request merged**
