### PR TITLE
netbsd: 9.1 -> 9.2

### PR DESCRIPTION
**Pull request by alyssais**
Note: 9.2 has been tagged, but not announced yet.

###### Things done

- [x] Update all versions and hashes
- [x] Everything that cross-compiled for NetBSD before the update still does
- [x] Static binaries run on NetBSD
- [x] Everything used on Darwin still works

### CODE REVIEW

**Comment by alyssais** [comment]
@ofborg build bash-my-aws microscheme

**Comment by sternenseemann** [comment]
@ofborg eval

**Comment by alyssais** [comment]
@ofborg build bash-my-aws microscheme

**Comment by Ericson2314** [comment]
I wonder if we should just let-bind the version to inherit everywhere.

**Comment by alyssais** [comment]
> I wonder if we should just let-bind the version to inherit everywhere.

I've been thinking about switching us over to building from the release tarballs rather than CVS, which would take care of that issue.  (Not in this PR, though.)

**Comment by alyssais** [comment]
@sternenseemann could you try building those packages on Darwin again please?  OfBorg timed out. :(

**Comment by sternenseemann** [comment]
Everything used in unixtools still builds on darwin:

```console
$ nix-build -A netbsd.getent -A netbsd.column -A netbsd.getconf -A netbsd.locale --keep-going
/nix/store/wa6lwkxzr3fifnrlnqj2bny4kcv20g24-getent-netbsd-9.2
/nix/store/sfvgg9979jxvsml68dapdiphadknz703-column-netbsd-9.2
/nix/store/aalcbss14c83vj90chly65dcal0pyixv-getconf-netbsd-9.2
/nix/store/x87sryn46dwyyl9ay2sv2z9bffp8h6bb-locale-netbsd-9.2
```

**Pull request merged**
