### PR TITLE
colord: 1.4.6 -> 1.4.7

### PR DESCRIPTION
**Pull request by trofi**
Changes: https://github.com/hughsie/colord/blob/1.4.7/NEWS

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by risicle** [comment]
@ofborg eval

**Comment by amaxine** [comment]
@ofborg eval

**Review by jtojnar — APPROVED** [review]
Changes look okay https://github.com/hughsie/colord/compare/1.4.6...1.4.7
There might be some downfall from systemd service hardening but [upstream YOLO’d it](https://github.com/hughsie/colord/pull/153) so we might as well.

**Comment by trofi** [comment]
Thank you for the report! Given that the service was specifying that directory for quite a while in https://github.com/NixOS/nixpkgs/blob/3f8ecdfda510112379f79f222d17e8f54a361a61/nixos/modules/services/x11/colord.nix#L33 I suspect the change is in generic systemd unit generation or systemd update itself.

Probably related to private home directory.

I'll try to reproduce and bisect.

**Comment by trofi** [comment]
Oh, it might be the `colord` itself after all. The suspect: https://github.com/hughsie/colord/commit/d7352455075f6a6eb32e7d256dadb436cbd15ae8

**Comment by trofi** [comment]
`strace` said `colord` failed to write to a read-only filesystem. I think it's a bug in `NixOS` `colord` module.

Proposed the possible fix as:
- https://github.com/NixOS/nixpkgs/pull/288142

As it's a module change we can quickly get it to `master`.

**Pull request merged**
