### PR TITLE
zigbee2mqtt: 1.16.2 -> 1.18.2

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

Regular upstream update.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
We cannot update zigbee2mqtt at this time, because the resulting derivation exceeds 5 MB.

https://github.com/NixOS/nixpkgs/pull/114896
https://github.com/svanderburg/node2nix/issues/46

**Comment by peterhoeg** [comment]
Huh, I've got it running here.

**Comment by SuperSandro2000** [comment]
> Huh, I've got it running here.

Please run ``nixpkgs-review pr --eval local 118147``.

**Comment by mweinelt** [comment]
https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.18.2 is out.

**Comment by peterhoeg** [comment]
Updated with the `update.sh` script, deployed and working fine here.

**Comment by mweinelt** [comment]
Do we want to give this a shot? I have no idea why it works now.

Result of `nixpkgs-review pr 118147` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>zigbee2mqtt</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
> Do we want to give this a shot?

Here we go, geronimo!

**Comment by mweinelt** [comment]
https://hydra.nixos.org/jobset/nixos/trunk-combined#tabs-errors

I wonder if this caused the unexpected EOF, again.

**Comment by thefloweringash** [comment]
I've created a PR to npm2nix reduce the derivation size of generated packages: https://github.com/svanderburg/node2nix/pull/255. Posting it here to bring it to the attention of people interesting in zigbee2mqtt.

**Comment by peterhoeg** [comment]
That's a win and a half! Nice.

**Pull request merged**
