### PR TITLE
Fix buildbot

### PR DESCRIPTION
**Pull request by lsix**
###### Motivation for this change

See https://github.com/NixOS/nixpkgs/pull/25243#pullrequestreview-35849958

###### Things done

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by copumpkin** [comment]
Not sure I really understand what's going on here. Are you downgrading it back to the previous setup that worked? The WIP is confusing me 😄

**Comment by jammerful** [comment]
@lsix Have you confirmed that this fixes the buildbot python 2.7 package?

**Comment by lsix** [comment]
This fixes the `autobahn` related issue, but a new problem follows for `buildbot`. `buildbot` was using during tests internal API from `autobahn`  that changed for the last release (see https://github.com/buildbot/buildbot/commit/e7fc8c8eba903c2aa6d7e6393499e5b9bffc2334).

I am considering the following approaches:

- disable that unique test
- backport that unique commit
- revert the autobahn update (and all other associated updates)

I’ll probably go for the first approach

**Comment by copumpkin** [comment]
Cool. Is this still WIP?

**Comment by lsix** [comment]
Here is the fixed version, but only for buildbot… As mentionned by @FRidh in 52b1995250c5dd7443c69818d469ef7db0299ffd this update of `os-testr` required for `buildbot` (considering the version of `pbr`) impacts a huge amount of other packages.

I’ll leave the WIP for the moment, I am on it, but it might take time…

**Comment by FRidh** [comment]
You could leave out upgrading the openstack packages because they're broken anyway. I suppose that should make it easier at least.

**Comment by lsix** [comment]
@FRidh I am mainly marking the necessary packages as broken (`cliff`, `glanceclient`), but the amount of packages to rebuild remains high. Takes me time to download / rebuild everything to see if something broke.

If anyone has a way to set-up a hydra job to give me the list of newly broken ackages, this would help me.

**Comment by lsix** [comment]
actually, I got to reduce the number of rebuilds (and I think I was doing a `nox-review wip --against master` with a non up to date master), I should get results sooner than what I initially thought.

**Comment by FRidh** [comment]
@lsix great. Otherwise, you can push to `nixpkgs/python-wip` and check https://headcounter.org/hydra/jobset/iElectric/python-wip. Nobody is using it right now (I was yesterday).

**Comment by FRidh** [comment]
although it might not include buildbot

**Comment by lsix** [comment]
WIP tag removed, I can run `nox-review pr 25460` properly on a sandboxed box. It is now ready for review.

I have not tested buildbot more than with a `buildbot --help`, but it builds fine now.

**Comment by FRidh** [comment]
Thanks a lot @lsix. This looks good to me so let's merge it. If issues do pop up we'll fix them then.

**Comment by copumpkin** [comment]
Thank you!

**Pull request merged**
