### PR TITLE
Add mind mapping tool XMind.

### PR DESCRIPTION
**Pull request by vandenoever**
This is a FOSS project, but this expression is using the binary build.

### CODE REVIEW

**Comment by wmertens** [comment]
@vandenoever so... did you get a reply?

**Comment by vandenoever** [comment]
No i did not.

**Comment by wmertens** [comment]
so... we sadly close this?

**Comment by 7c6f434c** [comment]
@vandenoever Do I understand correctly that you never received any reply about XMind license?

**Comment by vandenoever** [comment]
On Saturday 04 April 2015 03:32:58 Michael Raskin wrote:
> @vandenoever Do I understand correctly that you never received any reply
> about XMind license?

yes, there was no reply.

**Comment by 7c6f434c** [comment]
Pity. I guess we have to close the request then; as-is it seems to be too optimistic about the license, and I am not sure it is not a formal infringement to distribute instructions on altering their proprietary binaries (I mean patchelf in the expressions)

**Pull request closed without merging**
