### PR TITLE
zed-editor: 0.137.6 -> 0.141.2

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Changelog: https://github.com/zed-industries/zed/releases/tag/v0.141.2

cc @jansol @niklaskorz 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 317564` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

**Comment by jansol** [comment]
Build fails because they got around to setting up a linux "packaging" workflow for themselves that e.g. generates the desktop file from a template and packages everything up into a "we have AppImage at home" bundle that mimics the macOS app bundle and assumes you are running ubuntu 22.04 or something with hopefully most of the 2nd order dependencies installed.

**Comment by jansol** [comment]
Also [the bundling script](https://github.com/zed-industries/zed/blob/main/script/bundle-linux) requires at least gettext. And is currently broken, apparently.

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 317564` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
> Build fails because they got around to setting up a linux "packaging" workflow for themselves that e.g. generates the desktop file from a template and packages everything up into a "we have AppImage at home" bundle that mimics the macOS app bundle and assumes you are running ubuntu 22.04 or something with hopefully most of the 2nd order dependencies installed. (they copy direct dependency libraries into the bundle)

Thank you for pointing this out.
What does it imply for us then ? We have to change the derivation ?

**Comment by GaetanLepage** [comment]
So maybe we should fall back to creating the desktop file ourselves then.

**Comment by jansol** [comment]
We definitely need to change the derivation. Ideally we'd just run `script/bundle-linux` and then move the artifacts we want into `$out`. But that script also invokes cargo to actually perform the build, which I'm guessing won't work with the dependency vendoring nix does. We'll have to make some changes to the derivation for sure, maybe even to `buildRustPackage` (in order to build multiple top-level crates from the `source` workspace for the same nix package - zed and cli).

As for the .desktop file, we could use the .desktop.in file from the repo and just substitute the variables ourselves in the derivation.

**Comment by Mic92** [comment]
My PR addresses installing the desktop file: https://github.com/NixOS/nixpkgs/pull/319336

**Comment by GaetanLepage** [comment]
Unfortunately, I currently don't have the bandwidth to work on the required changes to this update.
@jansol, would you be able to make a patch on top of this branch ?

**Comment by matteo-pacini** [comment]
@GaetanLepage @jansol I would also  like to offer some help re packaging for Darwin once this is finalised.

Universal app bundles are distributed directly via Github - https://github.com/zed-industries/zed/releases - and I'd rather have "some" Zed, than have no Zed at all for `x86_64-darwin` and `aarch64-darwin` 🙇🏻 

The closer I got it to compile was with this patch on the `0.137.6` derivation:

```diff
diff --git a/pkgs/by-name/ze/zed-editor/package.nix b/pkgs/by-name/ze/zed-editor/package.nix
index 71482e5540f2..7e2cfd8be149 100644
--- a/pkgs/by-name/ze/zed-editor/package.nix
+++ b/pkgs/by-name/ze/zed-editor/package.nix
@@ -23,8 +23,43 @@
   darwin,
   makeFontsConf,
   vulkan-loader,
+  swift,
+  swiftpm,
 }:
-
+let
+  swiftDeps = {
+    client-sdk-swift = fetchFromGitHub {
+      owner = "livekit";
+      repo = "client-sdk-swift";
+      rev = "1.0.12";
+      hash = "sha256-lMj5zfI2cRh08rdPssAKcJrdzxkpJyoTc4oWvXKEIkI=";
+    };
+    promises = fetchFromGitHub {
+      owner = "google";
+      repo = "promises";
+      rev = "2.2.0";
+      hash = "sha256-YGvRInUdtbxePXuY6I2sv/iOSeN93n9rQwUnHo0qTAY=";
+    };
+    Specs = fetchFromGitHub {
+      owner = "webrtc-sdk";
+      repo = "Specs";
+      rev = "104.5112.17";
+      hash = "sha256-GX7AdcuDlH8IN3JxfOvk2BpXx0AymhrLDMT1OXSkJyk=";
+    };
+    swift-log = fetchFromGitHub {
+      owner = "apple";
+      repo = "swift-log";
+      rev = "1.5.2";
+      hash = "sha256-V6qp7O2IVCO+0hHMTUvhzWFiK8TT4oPGKpG+k9F003Q=";
+    };
+    swift-protobuf = fetchFromGitHub {
+      owner = "apple";
+      repo = "swift-protobuf";
+      rev = "1.22.1";
+      hash = "sha256-nn1XMM76Mv0pIDWS37+13BtsRm6YEwfoMElqWrGiLAM=";
+    };
+  };
+in
 rustPlatform.buildRustPackage rec {
   pname = "zed";
   version = "0.137.6";
@@ -37,6 +72,17 @@ rustPlatform.buildRustPackage rec {
     fetchSubmodules = true;
   };
 
+  postUnpack = lib.optionalString stdenv.isDarwin ''
+    pushd source
+    mkdir -p crates/live_kit_client/LiveKitClient/.build/checkouts
+    cp -r ${swiftDeps.client-sdk-swift} crates/live_kit_client/LiveKitClient/.build/checkouts/client-sdk-swift
+    cp -r ${swiftDeps.promises} crates/live_kit_client/LiveKitClient/.build/checkouts/promises
+    cp -r ${swiftDeps.Specs} crates/live_kit_client/LiveKitClient/.build/checkouts/Specs
+    cp -r ${swiftDeps.swift-log} crates/live_kit_client/LiveKitClient/.build/checkouts/swift-log
+    cp -r ${swiftDeps.swift-protobuf} crates/live_kit_client/LiveKitClient/.build/checkouts/swift-protobuf
+    popd
+  '';
+
   cargoLock = {
     lockFile = ./Cargo.lock;
     outputHashes = {
@@ -66,14 +112,23 @@ rustPlatform.buildRustPackage rec {
     };
   };
 
-  nativeBuildInputs = [
-    copyDesktopItems
-    curl
-    perl
-    pkg-config
-    protobuf
-    rustPlatform.bindgenHook
-  ] ++ lib.optionals stdenv.isDarwin [ xcbuild.xcrun ];
+  nativeBuildInputs =
+    [
+      copyDesktopItems
+      curl
+      perl
+      pkg-config
+      protobuf
+      rustPlatform.bindgenHook
+    ]
+    ++ lib.optionals stdenv.isDarwin [
+      xcbuild.xcrun
+      swift
+      swiftpm
+    ];
+
+  dontUseSwiftpmBuild = true;
+  dontUseSwiftpmCheck = true;
 
   buildInputs =
     [
@@ -111,6 +166,12 @@ rustPlatform.buildRustPackage rec {
       ]
     );
 
+  NIX_CFLAGS_COMPILE = lib.optionals stdenv.isDarwin [
+    # disable modules, otherwise we get redeclaration errors between
+    # Libsystem and xpc lib
+    "-fno-modules"
+  ];
+
   buildFeatures = [ "gpui/runtime_shaders" ];
 
   env = {
@@ -151,7 +212,5 @@ rustPlatform.buildRustPackage rec {
     ];
     mainProgram = "zed";
     platforms = platforms.all;
-    # Currently broken on darwin: https://github.com/NixOS/nixpkgs/pull/303233#issuecomment-2048650618
-    broken = stdenv.isDarwin;
   };
 }
```

...but compiling fails as Swift can't find the `SwiftShims` library, and that's where I ran out of ideas.

**Comment by jansol** [comment]
Ah, right. Upstream changed the cargo config for linux to use the `mold` linker recently. I guess that has already made its way to the 0.140.5 release that this PR refers to now?

**Comment by lukaslihotzki** [comment]
I have made this related PR to add the withGLES flag: https://github.com/NixOS/nixpkgs/pull/321516

Should we merge this update or withGLES first? Or, add the flag to this PR?

**Comment by GaetanLepage** [comment]
> Should we merge this update or withGLES first? Or, add the flag to this PR?

It's fine for me if we merge it first.

**Comment by GaetanLepage** [comment]
> Ah, right. Upstream changed the cargo config for linux to use the `mold` linker recently. I guess that has already made its way to the 0.140.5 release that this PR refers to now?

Should I then add `ld` to `nativeBuildInputs` ?

**Comment by GaetanLepage** [comment]
Success !!!

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 317564` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 317564` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 317564` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
It would be great if some current zed users could test this.

**Review by niklaskorz — APPROVED** [review]
Works great here on Plasma 6.1! :)

Next release will likely bring us collaboration support, I'm currently preparing the necessary changes to get https://github.com/zed-industries/zed/pull/13343 to build in nixpkgs. Also this theoretically finally makes zed-editor build on darwin too, but unfortunately that'll be blocked until we get newer macOS SDKs in nixpkgs because of the dependency on ScreenCaptureKit (also see https://github.com/NixOS/nixpkgs/pull/229210#issuecomment-2191312353).

**Review by niklaskorz — APPROVED** [review]

**Comment by PedroHLC** [comment]
Is the `Exec=` empty in `zed.desktop` right?

**Comment by GaetanLepage** [comment]
> Is the `Exec=` empty in `zed.desktop` right?

Indeed it is...

**Comment by GaetanLepage** [comment]
All good now @PedroHLC !

```
gaetan in 🌐 cuda in nixpkgs on  zed took 19m20s 
❯ nix-build -A zed-editor
/nix/store/0cd70ddjympqkp9d3l12n7mzl89rnyc9-zed-0.141.2

gaetan in 🌐 cuda in nixpkgs on  zed 
❯ cat result/share/applications/zed.desktop 
[Desktop Entry]
Version=1.0
Type=Application
Name=Zed
GenericName=Text Editor
Comment=A high-performance, multiplayer code editor.
TryExec=zed
StartupNotify=true
Exec=zed 
Icon=zed
Categories=Utility;TextEditor;Development;IDE;
Keywords=zed;
MimeType=text/plain;inode/directory;

**Pull request merged**
