### PR TITLE
openjdk8: use lndir instead of single symlink to JRE

### PR DESCRIPTION
**Pull request by lopsided98**
###### Motivation for this change

Fixes gradle based packages (and others) that were broken by #68382, by reverting to the prior symlinking strategy using `lndir`.

I also think this will supersede #68382, as it fixes jogl and hadoop.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @fgaz @d-goldin

### CODE REVIEW

**Comment by d-goldin** [comment]
I'm going to build 1-2 of the hadoop versions affected with this fix and will report back.

**Comment by d-goldin** [comment]
Tried hadoop 2.7 and 3.1 and they compile fine on NixOS-x86_64. :+1:

**Comment by FRidh** [comment]
I've pushed this to master as 72f76fe856077becf4135acaf6cab385067ddf2e. When it's OK this needs to be backported. Keeping open so we keep track of it.

**Comment by fgaz** [comment]
I can also confirm, this fixes my gradle builds. Thank you!

**Comment by d-goldin** [comment]
Seems like its doing fine on master.

**Comment by lheckemann** [comment]
Will cherry-pick and build on 19.09 now.

**Comment by lheckemann** [comment]
35751608badabf8d88f4f72bb91ceaac993181a2

**Comment by volth** [comment]
@GrahamcOfBorg build mucommander

**Pull request closed without merging**
