### PR TITLE
znc: add configure options

### PR DESCRIPTION
**Pull request by Izorkin**
###### Motivation for this change
Add options to build znc without IPv6 and enable debugging

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ivan** [comment]
What motivated disabling IPv6? If the machine can't connect to any IPv6, maybe it makes sense to disable IPv6 in the networking stack instead of in individual programs?

If the option is really necessary (because of some ZNC defect?), I suggest `withIPv6 ? true` instead of `withOutIPv6 ? false`.

**Review by c0bw3b — CHANGES_REQUESTED** [review]
Right now it's failing if _withZlib = true_ because zlib is not in the build inputs
```shell
Building "backlog.so" for ZNC 1.7.1... /nix/store/vcc4svb8gy29g4pam2zja6llkbcwsyiq-binutils-2.30/bin/ld: cannot find -lz
```

**Comment by Izorkin** [comment]
Sorry, fixed config.

**Comment by c0bw3b** [comment]
@GrahamcOfBorg build znc zncModules

**Comment by c0bw3b** [comment]
Hum actually the build failure is with `zncModules` :confused:

**Comment by Izorkin** [comment]
Remove commit 7c1d2a0? Don`t known to fix build.

**Comment by c0bw3b** [comment]
Let's see if modules maintainers have some insights on this first
@schneefux @offlinehacker @hrdinka @Infinisil

**Comment by c0bw3b** [comment]
So what's happening is: if built with zlib then `znc-buildmod` will pass `-lz` but zlib is not in the include path. It fails with zlib but could have been another lib.
Conclusion is we need `zncModules` build inputs to match `znc`'s to match znc-buildmod expectations.

I'll retry a bot build once the checks are green.

**Comment by c0bw3b** [comment]
@GrahamcOfBorg build znc zncModules

**Review by c0bw3b — APPROVED** [review]

**Pull request merged**
