### PR TITLE
systemd.tmpfiles.rules: Add upstream docs ref

### PR DESCRIPTION
**Pull request by Kreyren**
###### Motivation for this change
Being less flustrated with this hell of a lang docs

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
As discussed on Matrix, the information is already there, only search.nixos.org displays it incorrectly: https://github.com/NixOS/nixos-search/issues/303. https://github.com/jgm/pandoc/pull/7433 will fix that.

**Comment by Mic92** [comment]
> As discussed on Matrix, the information is already there, only search.nixos.org displays it incorrectly: [NixOS/nixos-search#303](https://github.com/NixOS/nixos-search/issues/303). [jgm/pandoc#7433](https://github.com/jgm/pandoc/pull/7433) will fix that.

What does this mean for this PR so? Having a web url sounds find to me.

**Comment by jtojnar** [comment]
If we want to merge this as a temporary sort of fix, it would be better if it were formatted as `<link xlink:href="https://www.freedesktop.org/software/systemd/man/tmpfiles.d.html"><citerefentry><refentrytitle>tmpfiles.d</refentrytitle><manvolnum>5</manvolnum></citerefentry></link>`.

But, hopefully, it will not take too long for the pandoc patch to get merged and we would then have a proper fix with nice formating that would allow us to link to man pages automatically.

**Comment by Kreyren** [comment]
Closing in favor of https://github.com/NixOS/nixos-search/issues/303 then

**Pull request closed without merging**
