### PR TITLE
pre-commit: fix import bug for built-in hooks

### PR DESCRIPTION
**Pull request by l0b0**
## Description of changes

Pre-commit's "system" language is a sort of escape hach from the encapsulation which pre-commit typically provides.  It just runs commands without thinking too hard about setting up or tearing down environments.

But it is used for two things: user-provided hooks which reference things in calling environment, and pre-commit-provided hooks which live in the pre-commit package (I'm calling these "meta" hooks).

The challenge becomes: which PATH and PYTHONPATH variables do we expose to pre-commit?  If it's the calling environment, the meta hooks break, and if it's the packaged environment, the external-facing system hooks break.

In order to make both of these work at the same time, this commit separates 'system' into two languages: 'system', and 'meta'. System hooks get access to the calling environment, and meta hooks get access to the packaged environment.

## Things done

Rebase #251418 with https://github.com/MatrixManAtYrService/nixpkgs/pull/1 on top of current master, which seems to fix the [broken builds](https://github.com/NixOS/nixpkgs/pull/251418/#issuecomment-2085337473):

```console
❯ nix-build --attr pre-commit --attr python311Packages.asteroid-filterbanks --attr python311Packages.pyannote-audio
/nix/store/9gj7wz6nvs66cxhbaxynyx3hynn4ch48-pre-commit-3.7.1
/nix/store/6fy6mkv761aynq1sbxbn3ms99q4ix3qs-python3.11-asteroid-filterbanks-0.4.0
/nix/store/mz50n7jy8zvcqvy5yy2dkp4676rdd74j-python3.11-pyannote-audio-3.3.0
```

Verify that this fixes the issue with the `check-useless-excludes` meta-hook:

```console
❯ cd [other project]
❯ ~/my\ projects/nixpkgs/result/bin/pre-commit run --all-files
Check for useless excludes...............................................Passed
```

Format the Nix files using `nixfmt-rfc-style`.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by l0b0** [comment]
Result of `nixpkgs-review pr 342436` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>pre-commit</li>
    <li>pre-commit.dist</li>
    <li>python311Packages.asteroid-filterbanks</li>
    <li>python311Packages.asteroid-filterbanks.dist</li>
    <li>python311Packages.pyannote-audio</li>
    <li>python311Packages.pyannote-audio.dist</li>
    <li>python312Packages.asteroid-filterbanks</li>
    <li>python312Packages.asteroid-filterbanks.dist</li>
    <li>python312Packages.pyannote-audio</li>
    <li>python312Packages.pyannote-audio.dist</li>
    <li>whisper-ctranslate2</li>
    <li>whisper-ctranslate2.dist</li>
  </ul>
</details>

**Review by Artturin — CHANGES_REQUESTED** [review]
Formatting should be in a separate commit

Not familiar with pre-commit but I suppose the changes are fine.

**Comment by l0b0** [comment]
> Formatting should be in a separate commit

Oops, fixed!

**Review by phaer — COMMENTED** [review]
I think https://github.com/NixOS/nixpkgs/issues/272178 and more specifically https://github.com/NixOS/nixpkgs/pull/272179 might be relevant here.

In my understanding we are patching an extra feature in upstream software to work around long-standing quirks of nixpkgs python handling.
This isn't pretty, but fine with me as it seems to solve actual problems for which I don't have quick & easier solution.

But might be worth documenting it a bit further or put out a warning? From reading the code, I think a user running into broken system hooks might have to read this nix code to learn that there are meta builds as well?

**Comment by l0b0** [comment]
> But might be worth documenting it a bit further or put out a warning? From reading the code, I think a user running into broken system hooks might have to read this nix code to learn that there are meta builds as well?

This fixes the *meta* hooks, I'm not aware of it fixing any system hooks. I've not observed broken system hooks in relation to this fix.

@MatrixManAtYrService, would you be OK to field the other questions, as the original author of the fix? (I just wrote the tests to verify the fix.)

**Comment by MatrixManAtYrService** [comment]
I think that at a casual glance, most would classify pre-commit as an application and not a library.  I did, which is why in https://github.com/NixOS/nixpkgs/pull/235123 I prevented it from propagating its build inputs since I had no reason to import them and they were interfering with other python libraries in the same environment.

@phaer I believe the PR's you linked are trying to do for python applications *in general* what I did in that PR.

But pre-commit is a bit strange in that there are a few cases where it tries to import parts of itself in a subprocess.  These cases are listed as [meta hooks](https://github.com/pre-commit/pre-commit/tree/main/pre_commit/meta_hooks), but they're configured to run via the `system` language.   https://github.com/NixOS/nixpkgs/pull/235123 cleaned up the environment known to `system` such that pre-commit could not find itself, which broke the meta hooks (shame on me for not noticing, I wasn't using them).

With this patch I am indeed
> patching an extra feature in upstream software to work around long-standing quirks of nixpkgs python handling

and I agree that it isn't pretty.  Specifically, it creates a `meta` language which corresponds with the meta hooks so that they can be run without the cleanup done by https://github.com/NixOS/nixpkgs/pull/235123, while the system hooks continue to be run in the cleaned-up environment.

On the bright side, I think it's fairly robust because any new meta hooks that are later added to pre-commit are likely show up [here](https://github.com/pre-commit/pre-commit/blob/de8590064e181c0ad45d318a0c80db605bf62a60/pre_commit/clientlib.py#L239) which means that they'll get the patched language type automatically.

As for system hooks... they end up with `PATH` and `PYTHONPATH` as they're collected via the `pre-commit` wrapper script.  I think that's pretty authentic to the meaning of `system`.  It's everything that was lying around when the command was invoked. I don't think this is likely to break them.  It would've broken them if they were relying on pre-commit's python dependencies, but https://github.com/NixOS/nixpkgs/pull/235123 already removed those (oops).

I'm happy to add a document or a warning somewhere if we think it's warranted, but I would need a bit of guidance about where to put it.

**Comment by l0b0** [comment]
Fixed in 306444.

**Pull request closed without merging**
