### PR TITLE
peertube: 6.0.4 -> 6.3.3

### PR DESCRIPTION
**Pull request by liberodark**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by liberodark** [comment]
Cleanup PR without formating

**Review by Izorkin — APPROVED** [review]

**Review by Izorkin — APPROVED** [review]

**Comment by synq** [comment]
It looks like this PR will only build if this PR from the Peertube project has been fixed: https://github.com/Chocobozzz/PeerTube/pull/6548

I have put a remark about this in that PR.

**Comment by synq** [comment]
So the problem is that the test fails on this:
```
server # [  235.543401] peertube[877]: node:internal/errors:496
server # [  235.563965] peertube[877]:     ErrorCaptureStackTrace(err);
server # [  235.567887] peertube[877]:     ^
server # [  235.574601] peertube[877]: Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@peertube/peer>
server # [  235.579849] peertube[877]:     at new NodeError (node:internal/errors:405:5)
server # [  235.584877] peertube[877]:     at packageResolve (node:internal/modules/esm/resolve:916:9)
server # [  235.590518] peertube[877]:     at moduleResolve (node:internal/modules/esm/resolve:973:20)
server # [  235.594392] peertube[877]:     at defaultResolve (node:internal/modules/esm/resolve:1206:11)
server # [  235.598478] peertube[877]:     at ModuleLoader.defaultResolve (node:internal/modules/esm/loa>
server # [  235.601779] peertube[877]:     at ModuleLoader.resolve (node:internal/modules/esm/loader:373>
server # [  235.604889] peertube[877]:     at ModuleLoader.getModuleJob (node:internal/modules/esm/loade>
server # [  235.609638] peertube[877]:     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_j>
server # [  235.612933] peertube[877]:     at link (node:internal/modules/esm/module_job:75:36) {
server # [  235.615966] peertube[877]:   code: 'ERR_MODULE_NOT_FOUND'
server # [  235.621379] peertube[877]: }
server # [  235.625732] peertube[877]: Node.js v18.20.5
```

**Comment by roberth** [comment]
It does look like the NixOS test is failing.
You're right that the package is buildable, producing outputs and all, but those outputs seem to contain a peertube that's broken when you run it.
The NixOS test and NixOS module don't seem to do anything outlandish, and they don't seem to configure anything related to transcription. It's the test that protects users from a broken package, and while tests are technically internal, that does not diminish their importance.
Did you perhaps run peertube in a different way? Then it would be good to look at any differences between your configuration and that which is provided by the NixOS peertube module and the test.

**Comment by OPNA2608** [comment]
> It looks like this PR will only build if this PR from the Peertube project has been fixed: [Chocobozzz/PeerTube#6548](https://github.com/Chocobozzz/PeerTube/pull/6548)

Not really relevant, as that is about managing external plugins. Your log is cut off on the side, but it's complaining about `peertube/peertube-transcription`, which is a new in-tree package that needs to be installed together with the rest.

**Comment by Izorkin** [comment]
> And a new storage location was added `storage.original_video_files`, which needs to be added to the module. I've re-ordered the storage entries here to match [the order from upstream's code](https://github.com/Chocobozzz/PeerTube/blob/2ebfe772ed10af34f48fbd012f0d85aa3e4fee59/server/core/initializers/config.ts#L110-L129), for an easier overview.

Maybe keep the current sort order? At the very least, can see the history of file changes in upstream.

**Comment by fricklerhandwerk** [comment]
`x86_64-darwin` builds are failing and `aarch64-darwin` is stuck, but not sure this is a blocker for merging. Hard to imagine anyone would host peertube on macOS. If someone is, please open PRs with fixes.

**Comment by natsukagami** [comment]
Will this be backported to 24.11?

**Comment by fricklerhandwerk** [comment]
I'd have nothing against it personally, but it would be against the general policy of only backporting security fixes. @wegank @RossComputerGuy is that a firm rule?

**Comment by natsukagami** [comment]
One point to argue for backporting is that 6.1 (which we don't have yet) fixes two important security bugs: https://joinpeertube.org/news/release-6.1

**Pull request merged**
