### PR TITLE
NodeJS: 10.5.0 -> 10.6.0

### PR DESCRIPTION
**Pull request by wmertens**
[Release notes](https://nodejs.org/en/blog/release/v10.6.0/)

### CODE REVIEW

**Comment by wmertens** [comment]
@GrahamcOfBorg build nodejs-10_x

**Comment by wmertens** [comment]
@GrahamcOfBorg build nodejs-10_x

**Comment by adisbladis** [comment]
This is already on `staging` in 63e0e4d899a06791f48a81de4129ae86a53687e8

**Comment by wmertens** [comment]
> This is already on staging in 63e0e4d

d'oh :)

**Comment by adisbladis** [comment]
> d'oh :)

No worries :)
It's on staging because nodejs `10.6.0` required a `libuv` upgrade and `libuv` causes lots of rebuilding.
That's what caused your aarch64 build failure btw.

**Pull request closed without merging**
