### PR TITLE
topiary: 0.3.0 -> 0.5.1

### PR DESCRIPTION
**Pull request by nartsisss**
- Upgrade to [v0.5.1](https://github.com/tweag/topiary/releases/tag/v0.5.1) ([Changes](https://github.com/tweag/topiary/blob/main/CHANGELOG.md#v051---fragrant-frangipani---2024-10-22))
- Use `tag` instead of `rev = "refs/tags/..."` in `fetchFromGitHub`
- Use new cargo fetcher (`useFetchCargoVendor`)
- Shell completions
- Skip broken tests
- Add versionCheckHook
- Refactor meta (remove `with lib;`)

## Things done
- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by nartsisss** [comment]
Idk why hashes on my machine and Ofborg's are different. Maybe related to `useFetchCargoVendor`?

```
...
Fetching https://crates.io/api/v1/crates/zerocopy-derive/0.7.35/download -> tarballs/zerocopy-derive-0.7.35.tar.gz
buildPhase completed in 50 seconds
error: hash mismatch in fixed-output derivation '/nix/store/ys95sazfz0f9l938xdp6n8cv3xd5aanc-topiary-0.5.1-vendor-staging.drv':
         specified: sha256-o3Y37W6d2kVI6zsyrOZ8UJXehhDVeFYE+BZPiMq3ArY=
            got:    sha256-bk5993v0wn/emzJKvxaPBYjqCmP0BpOuFMga7ZOyqXg=
error: 1 dependencies of derivation '/nix/store/gg0484pq66kx8lxrh8gn36wwl621n3h1-topiary-0.5.1-vendor.drv' failed to build
error: 1 dependencies of derivation '/nix/store/6xiw5ib3sz4jryz4pkprlkv0g69jpwgv-topiary-0.5.1.drv' failed to build
```

**Comment by Niols** [comment]
It might be coming from case-insensivity of the underlying file systems. I am not sure that it would be a problem to do
```
  cargoHash =
    if stdenv.system == "x86_64-linux" then
      "sha256-bk5993v0wn/emzJKvxaPBYjqCmP0BpOuFMga7ZOyqXg="
    else
      "sha256-o3Y37W6d2kVI6zsyrOZ8UJXehhDVeFYE+BZPiMq3ArY=";
```
(probably by testing on more platforms than that).

**Comment by YorikSar** [comment]
For me, `topiary-0.5.1-vendor` builds fine on both `aarch64-darwin` (case-insensitive APFS) and `x86_64-linux` (case-sensitive ZFS) with current hash `sha256-o3Y37W6d2kVI6zsyrOZ8UJXehhDVeFYE+BZPiMq3ArY=`.

**Comment by Niols** [comment]
I'm curious then, what exactly did you run and at which commit of nixpkgs?

**Comment by YorikSar** [comment]
I ran:
* `git fetch https://github.com/nartsisss/nixpkgs update-topiary`
* `git co FETCH_HEAD`
* got to a commit `deb0e6a0a8473105677ea6a038b114ebf56727a5`
* `nom build --system aarch64-darwin -f . topiary`
* `nom build --system x86_64-linux -f . topiary`

`aarch64-darwin` build was local, `x86_64-linux` one used a remote build server. I didn't wait for the topiary itself to finish building though.

**Comment by Niols** [comment]
Running on another machine, that same commit builds normally. Both machines are `x86_64-linux` and both are building locally. There are many differences between the two machines, but maybe the most significant one here is that one machine has an ext4 partition holding the Nix store while the other uses ZFS.

**Comment by Niols** [comment]
I vendored all the dependencies and looked for non-normalised UTF-8 file names and that does not seem to be the problem. I also didn't find any pair of files whose names are equal up to case.

**Comment by Niols** [comment]
Found the culprit. Two vendored files:

```
git/036226e5edb410aec004cc7ac0f4b2014dd04a0e/examples/dune/ci/setup-dkml/pc/setup-dkml-windows_x86.ps1
git/036226e5edb410aec004cc7ac0f4b2014dd04a0e/examples/dune/ci/setup-dkml/pc/setup-dkml-windows_x86_64.ps1
```

get different hashes depending on which machine downloads them. Everything else is the same. I think the problem is that they are UTF-16 files, and somehow their endianness changes (big-endian for `bk599...qXg=`, small-endian for `o3Y37...ArY=`).

It is a bit sad because these files are only here for `tree-sitter-ocaml`, and specifically only in a submodule `examples/dune` and specifically only needed for CI of that example. The files have also actually been removed from Dune in July (https://github.com/ocaml/dune/pull/10749).

For this one PR, a hacky solution consists in converting those files to eg. little-endian systematically (since that's what most architectures work with anyway nowadays), with something like:
```nix
depsExtraArgs.postBuild = ''
  for file in \
    $out/git/036226e5edb410aec004cc7ac0f4b2014dd04a0e/examples/dune/ci/setup-dkml/pc/setup-dkml-windows_x86*.ps1
  do
    ${iconv}/bin/iconv -f UTF-16BE -t UTF16LE "$file" > tmp && mv tmp "$file"
  done
'';
```

However, this feels like a very wrong solution, for two major reasons:

- We seem to be cloning a loooot of things for nothing (all the examples of tree-sitter-ocaml), so probably we could in fact not clone subdirectories of tree-sitter-ocaml in Topiary, and update `fetch-cargo-vendor-util.py` so that it follows these instructions. I have been complaining regularly that entering the Topiary Nix shell was taking forever because of much fetching, so that would actually help, and it might improve build time of some other Rust projects.

- `fetch-cargo-vendor-util.py` does not seem to do much magic, and mostly it calls `nix-prefetch-git` to clone git repositories and their submodules. So.... is there a bug in there to be found? Sadly, I haven't managed to get two calls of `nix-prefetch-git` on https://github.com/ocaml/dune.git that would return different hashes, but I will keep trying. Also, there is something to understand about what causes `nix-prefetch-git` to behave differently? Network stuff? Weird temporary filesystems? Maybe in some cases we normalise to the current architecture while in others we keep the original file?

To be continued.

**Comment by YorikSar** [comment]
I think this could be the reason: https://github.com/ocaml/dune/blob/main/.gitattributes#L6 - Git has to process these files after checking them out.
I’m not sure why it would produce different results on different file systems though. Does Git mix up settings for file names with the ones for the content?..

**Comment by Niols** [comment]
Good catch, it definitely looks related. I still don't see what circumstances change that make some machines end up encoding those files in BE, though.

14 Dec 2024 06:10:39 Yuriy Taraday ***@***.***>:

**Comment by Niols** [comment]
For the approach to convert them to LE in the `postBuild`, one should be careful that `iconv` doesn't do any sort of checking, so `iconv -f UTF-16BE -t UTF-16LE` will convert UTF-16BE files to UTF-16LE, but also UTF-16LE files to UTF16-BE. One could imagine something like:
```sh
find $out -name '*.ps1' -print | while read -r file; do
  case $(file --brief --mime-encoding "$file") in
    utf-16be) ${iconv}/bin/iconv -f UTF-16BE -t UTF16LE "$file" > tmp && mv tmp "$file" ;;
    *) ;;
  esac
done
```

**Comment by Niols** [comment]
@nartsisss> Would you mind giving more details about the architecture on which you developed this patch? I know it is Darwin, but would you mind sharing the model of the computer, or at least processor chip?

**Comment by nartsisss** [comment]
@Niols aarch64, M3 Pro chip

**Comment by Niols** [comment]
OK, apparently this architecture is configurable, but most probably it is little-endian. Would you mind checking, with eg.
```
python -c 'import sys; print(sys.byteorder)'
```

**Comment by Niols** [comment]
After some discussions with some other Nix people at Tweag (in particular @infinisil), the conclusion is:

- This endianness change behaviour should probably not count as an issue in Nix but more as one of the peculiar differences between Linux and Darwin at the same level as the case sensivity stuff.

- The best way to move forward for the current PR is with explicit conversion of the two files in question, because this is what shows best the source of differences, where two different hashes for Darwin and Linux would just be saying “somehow they're different”.

@nartsisss> Are you happy to proceed with something in the lines of https://github.com/NixOS/nixpkgs/pull/359145#issuecomment-2545017512? I am otherwise happy to write it down, if you prefer.

@infinisil> Should we try to write anywhere about this UTF-16 endianness peculiarity that differentiate Linux and Darwin? I'm just hoping to maybe save another poor engineer some time in the future.

**Comment by nartsisss** [comment]
@Niols 
Sorry for the wait.

> OK, apparently this architecture is configurable, but most probably it is little-endian. 

You're right
```
[nix-shell:~]$ python -c 'import sys; print(sys.byteorder)'
little
```

> @nartsisss> Are you happy to proceed with something in the lines of https://github.com/NixOS/nixpkgs/pull/359145#issuecomment-2545017512? I am otherwise happy to write it down, if you prefer.

It seems that `$out` can't be accessed in  `postBuild`?
```
find: '/nix/store/zp7arv77mym2rh8g66zrwqkhsa7qy0b5-topiary-0.5.1': No such file or directory
```
Also, I tried `$cargoDeps`:
```
mv: inter-device move failed: 'tmp' to '/nix/store/0x1q9clrbxsxbnf8pjx64nvyy76c393c-topiary-0.5.1-vendor/tree-sitter-ocaml-0.22.0/examples/dune/ci/setup-dkml/pc/setup-dkml-windows_x86_64.ps1'; unable to remove target: Permission denied
```

**Comment by Niols** [comment]
No worries, we all have our own timelines. For me, the following commit on top of your work seems to work fine: https://github.com/Niols/nixpkgs/commit/72c620ff6b1de0e02be4340a0398ff7a7204ee3f. Do you also have the issue with this one?

**Comment by infinisil** [comment]
> @infinisil> Should we try to write anywhere about this UTF-16 endianness peculiarity that differentiate Linux and Darwin? I'm just hoping to maybe save another poor engineer some time in the future.

Definitely, easiest would be in a comment in the code

**Comment by nartsisss** [comment]
> Niols@72c620f

Forgot about `depsExtraArgs`, works fine now.

**Comment by Niols** [comment]
It's a bit worrying that it works for you with Cargo hash `sha256-o3Y37W6d2kVI6zsyrOZ8UJXehhDVeFYE+BZPiMq3ArY=`, because I think that was the hash with the big endian files; but I could be mistaken, I got so confused by this thing -- Let's just see what CI says.

**Comment by nartsisss** [comment]
> It's a bit worrying that it works for you with Cargo hash `sha256-o3Y37W6d2kVI6zsyrOZ8UJXehhDVeFYE+BZPiMq3ArY=`, because I think that was the hash with the big endian files; but I could be mistaken, I got so confused by this thing -- Let's just see what CI says. (Hopefully, if it is the wrong hash, it should be the wrong hash **everywhere**!)

It's weird, I'll try to rebuild with --repair flag

**Comment by Niols** [comment]
Makes sense. Actually, we could also enforce big-endian everywhere considering that's what seems to be the default in the Git repo in question; it chose little-endian because it's closer to our architectures, but it really doesn't matter at all.

**Comment by nartsisss** [comment]
CI passed. Thanks, @Niols @YorikSar

**Comment by Niols** [comment]
Amazing! Topiary v0.5.1 in nixpkgs in 2024 maybe?!

20 Dec 2024 14:31:21 Daniil Nartsissov ***@***.***>:

**Review by GaetanLepage — CHANGES_REQUESTED** [review]

**Review by GaetanLepage — APPROVED** [review]

**Pull request merged**
