### PR TITLE
buildNpmPackage: symlink manpages to the correct output directory

### PR DESCRIPTION
**Pull request by delroth**
## Description of changes

I noticed this was a regression from node2nix when reviewing #249879. Not completely sure if that's doing it right, and I'm happy to take your suggestions, but it seems to work in the few cases I've tested.

nixpkgs-review OOMs on my 48GB RAM machine when trying to rebuild all dependents, so I couldn't do a full check run, but the few packages I tried building all built fine.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by dotlambda — CHANGES_REQUESTED** [review]
This shouldn't use the man directory by default. Instead we have to respect the `"man"` key in `package.json`: https://github.com/mapbox/carto/blob/v1.2.0/package.json#L30
Also see https://docs.npmjs.com/cli/v6/configuring-npm/package-json/#man

**Review by dotlambda — APPROVED** [review]

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 249932` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>magnetophonDSP.ConstantDetuneChorus</li>
  </ul>
</details>
<details>
  <summary>136 packages failed to build:</summary>
  <ul>
    <li>activitywatch</li>
    <li>ariang</li>
    <li>audiobookshelf</li>
    <li>authelia</li>
    <li>aw-server-rust</li>
    <li>balanceofsatoshis</li>
    <li>bitwarden-cli</li>
    <li>cdxgen</li>
    <li>cz-cli</li>
    <li>deltachat-desktop</li>
    <li>djot-js</li>
    <li>emscripten</li>
    <li>emscriptenPackages.json_c</li>
    <li>emscriptenPackages.json_c.dev</li>
    <li>emscriptenPackages.libxml2</li>
    <li>emscriptenPackages.libxml2.bin</li>
    <li>emscriptenPackages.libxml2.dev</li>
    <li>emscriptenPackages.libxml2.doc</li>
    <li>emscriptenPackages.xmlmirror</li>
    <li>emscriptenPackages.xmlmirror.doc</li>
    <li>emscriptenPackages.zlib</li>
    <li>epgstation</li>
    <li>eslint_d</li>
    <li>faust</li>
    <li>faust2alqt</li>
    <li>faust2alsa</li>
    <li>faust2csound</li>
    <li>faust2firefox</li>
    <li>faust2jack</li>
    <li>faust2jackrust</li>
    <li>faust2jaqt</li>
    <li>faust2ladspa</li>
    <li>faust2lv2</li>
    <li>faust2sc</li>
    <li>faustPhysicalModeling</li>
    <li>faustlive</li>
    <li>flood</li>
    <li>forgejo</li>
    <li>forgejo.data</li>
    <li>fx-cast-bridge</li>
    <li>geph.gui</li>
    <li>github-copilot-cli</li>
    <li>gnomeExtensions.pop-shell</li>
    <li>google-clasp</li>
    <li>guitarix</li>
    <li>homepage-dashboard</li>
    <li>hred</li>
    <li>husky</li>
    <li>imgbrd-grabber</li>
    <li>iosevka</li>
    <li>iosevka-comfy.comfy</li>
    <li>iosevka-comfy.comfy-duo</li>
    <li>iosevka-comfy.comfy-fixed</li>
    <li>iosevka-comfy.comfy-motion</li>
    <li>iosevka-comfy.comfy-motion-duo</li>
    <li>iosevka-comfy.comfy-motion-fixed</li>
    <li>iosevka-comfy.comfy-wide</li>
    <li>iosevka-comfy.comfy-wide-duo</li>
    <li>iosevka-comfy.comfy-wide-fixed</li>
    <li>iosevka-comfy.comfy-wide-motion</li>
    <li>iosevka-comfy.comfy-wide-motion-duo</li>
    <li>iosevka-comfy.comfy-wide-motion-fixed</li>
    <li>jellyfin</li>
    <li>jellyfin-media-player</li>
    <li>jellyfin-web</li>
    <li>kapitonov-plugins-pack</li>
    <li>kavita</li>
    <li>lineselect</li>
    <li>lv_img_conv</li>
    <li>magnetophonDSP.CharacterCompressor</li>
    <li>magnetophonDSP.CompBus</li>
    <li>magnetophonDSP.LazyLimiter</li>
    <li>magnetophonDSP.MBdistortion</li>
    <li>magnetophonDSP.RhythmDelay</li>
    <li>magnetophonDSP.VoiceOfFaust</li>
    <li>magnetophonDSP.faustCompressors</li>
    <li>magnetophonDSP.pluginUtils</li>
    <li>magnetophonDSP.shelfMultiBand</li>
    <li>matrix-alertmanager</li>
    <li>memos</li>
    <li>mermaid-filter</li>
    <li>mirakurun</li>
    <li>mongosh</li>
    <li>mooSpace</li>
    <li>moonfire-nvr</li>
    <li>mpvScripts.webtorrent-mpv-hook</li>
    <li>mw</li>
    <li>nest-cli</li>
    <li>newman</li>
    <li>npm-check</li>
    <li>ntfy-sh</li>
    <li>open-music-kontrollers.mephisto</li>
    <li>open-stage-control</li>
    <li>osmtogeojson</li>
    <li>pairdrop</li>
    <li>paperless-ngx</li>
    <li>photofield</li>
    <li>photoprism</li>
    <li>pnpm-lock-export</li>
    <li>polaris</li>
    <li>pufferpanel</li>
    <li>pyCA</li>
    <li>pyCA.dist</li>
    <li>readability-cli</li>
    <li>resumed</li>
    <li>semantic-release</li>
    <li>sitespeed-io</li>
    <li>slskd</li>
    <li>sunshine</li>
    <li>swagger-cli</li>
    <li>tambura</li>
    <li>terminal-stocks</li>
    <li>thelounge</li>
    <li>torq</li>
    <li>triton</li>
    <li>twspace-crawler</li>
    <li>typescript</li>
    <li>uivonim</li>
    <li>uptime-kuma</li>
    <li>vencord</li>
    <li>vencord-web-extension</li>
    <li>vieb</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vsce</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
    <li>vscode-langservers-extracted</li>
    <li>webcord</li>
    <li>webcord-vencord</li>
    <li>webtorrent_desktop</li>
    <li>weylus</li>
    <li>windmill</li>
    <li>yarn-lock-converter</li>
    <li>ycmd</li>
    <li>zigbee2mqtt</li>
    <li>zincsearch</li>
    <li>zrythm</li>
  </ul>
</details>
<details>
  <summary>25 packages built:</summary>
  <ul>
    <li>ansible-language-server</li>
    <li>antennas</li>
    <li>antora</li>
    <li>assemblyscript</li>
    <li>bibtex-tidy</li>
    <li>bitwarden</li>
    <li>castnow</li>
    <li>docker-compose-language-service</li>
    <li>documenso</li>
    <li>dot-language-server</li>
    <li>eask</li>
    <li>filebrowser</li>
    <li>gtop</li>
    <li>hueadm</li>
    <li>karma-runner</li>
    <li>kaufkauflist</li>
    <li>maizzle</li>
    <li>markdownlint-cli</li>
    <li>node-manta</li>
    <li>nodehun</li>
    <li>polaris-web</li>
    <li>psitransfer</li>
    <li>reveal-md</li>
    <li>sharing</li>
    <li>zx</li>
  </ul>
</details>

**Comment by delroth** [comment]
Uh, some of the derivations in your "failed" list are ones that I did test locally and that worked fine. Let me have another look...

**Comment by delroth** [comment]
@dotlambda do you have build failure logs for e.g. `github-copilot-cli`, `forgejo`, `mongosh` or `ntfy-sh`? I just spot checked all 4 of them locally and all 4 built successfully.

**Comment by delroth** [comment]
@ofborg build github-copilot-cli forgejo mongosh ntfy-sh

**Comment by dotlambda** [comment]
That was some issue with my network or nixpkgs-review. I'll try to run it again.

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 249932` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>magnetophonDSP.ConstantDetuneChorus</li>
  </ul>
</details>
<details>
  <summary>10 packages failed to build:</summary>
  <ul>
    <li>geph.gui</li>
    <li>imgbrd-grabber</li>
    <li>iosevka</li>
    <li>iosevka-comfy.comfy</li>
    <li>iosevka-comfy.comfy-duo</li>
    <li>iosevka-comfy.comfy-motion</li>
    <li>iosevka-comfy.comfy-motion-duo</li>
    <li>iosevka-comfy.comfy-motion-fixed</li>
    <li>iosevka-comfy.comfy-wide</li>
    <li>sitespeed-io</li>
  </ul>
</details>
<details>
  <summary>144 packages built:</summary>
  <ul>
    <li>activitywatch</li>
    <li>ansible-language-server</li>
    <li>antennas</li>
    <li>antora</li>
    <li>ariang</li>
    <li>assemblyscript</li>
    <li>audiobookshelf</li>
    <li>authelia</li>
    <li>aw-server-rust</li>
    <li>balanceofsatoshis</li>
    <li>bibtex-tidy</li>
    <li>bitwarden</li>
    <li>bitwarden-cli</li>
    <li>castnow</li>
    <li>cdxgen</li>
    <li>cz-cli</li>
    <li>deltachat-desktop</li>
    <li>djot-js</li>
    <li>docker-compose-language-service</li>
    <li>documenso</li>
    <li>dot-language-server</li>
    <li>eask</li>
    <li>emscripten</li>
    <li>epgstation</li>
    <li>eslint_d</li>
    <li>faust (faust2)</li>
    <li>faust2alqt</li>
    <li>faust2alsa</li>
    <li>faust2csound</li>
    <li>faust2firefox</li>
    <li>faust2jack</li>
    <li>faust2jackrust</li>
    <li>faust2jaqt</li>
    <li>faust2ladspa</li>
    <li>faust2lv2</li>
    <li>faust2sc</li>
    <li>faustPhysicalModeling</li>
    <li>faustlive</li>
    <li>filebrowser</li>
    <li>flood</li>
    <li>forgejo</li>
    <li>forgejo.data</li>
    <li>fx-cast-bridge</li>
    <li>github-copilot-cli</li>
    <li>gnomeExtensions.pop-shell</li>
    <li>google-clasp</li>
    <li>gtop</li>
    <li>guitarix</li>
    <li>haskellPackages.aeson-typescript</li>
    <li>haskellPackages.aeson-typescript.doc</li>
    <li>homepage-dashboard</li>
    <li>hred</li>
    <li>hueadm</li>
    <li>husky</li>
    <li>iosevka-comfy.comfy-fixed</li>
    <li>iosevka-comfy.comfy-wide-duo</li>
    <li>iosevka-comfy.comfy-wide-fixed</li>
    <li>iosevka-comfy.comfy-wide-motion</li>
    <li>iosevka-comfy.comfy-wide-motion-duo</li>
    <li>iosevka-comfy.comfy-wide-motion-fixed</li>
    <li>jellyfin</li>
    <li>jellyfin-media-player</li>
    <li>jellyfin-web</li>
    <li>kapitonov-plugins-pack</li>
    <li>karma-runner</li>
    <li>kaufkauflist</li>
    <li>kavita</li>
    <li>lineselect</li>
    <li>lv_img_conv</li>
    <li>magnetophonDSP.CharacterCompressor</li>
    <li>magnetophonDSP.CompBus</li>
    <li>magnetophonDSP.LazyLimiter</li>
    <li>magnetophonDSP.MBdistortion</li>
    <li>magnetophonDSP.RhythmDelay</li>
    <li>magnetophonDSP.VoiceOfFaust</li>
    <li>magnetophonDSP.faustCompressors</li>
    <li>magnetophonDSP.pluginUtils</li>
    <li>magnetophonDSP.shelfMultiBand</li>
    <li>maizzle</li>
    <li>markdownlint-cli</li>
    <li>matrix-alertmanager</li>
    <li>memos</li>
    <li>mermaid-filter</li>
    <li>mirakurun</li>
    <li>mongosh</li>
    <li>mooSpace</li>
    <li>moonfire-nvr</li>
    <li>mpvScripts.webtorrent-mpv-hook</li>
    <li>mw</li>
    <li>nest-cli</li>
    <li>newman</li>
    <li>node-manta</li>
    <li>nodehun</li>
    <li>npm-check</li>
    <li>ntfy-sh</li>
    <li>open-music-kontrollers.mephisto</li>
    <li>open-stage-control</li>
    <li>osmtogeojson</li>
    <li>pairdrop</li>
    <li>paperless-ngx</li>
    <li>photofield</li>
    <li>photoprism</li>
    <li>pnpm-lock-export</li>
    <li>polaris</li>
    <li>polaris-web</li>
    <li>psitransfer</li>
    <li>pufferpanel</li>
    <li>pyCA</li>
    <li>pyCA.dist</li>
    <li>readability-cli</li>
    <li>resumed</li>
    <li>reveal-md</li>
    <li>semantic-release</li>
    <li>sharing</li>
    <li>slskd</li>
    <li>sunshine</li>
    <li>swagger-cli</li>
    <li>tambura</li>
    <li>terminal-stocks</li>
    <li>thelounge</li>
    <li>torq</li>
    <li>triton</li>
    <li>twspace-crawler</li>
    <li>typescript</li>
    <li>uivonim</li>
    <li>uptime-kuma</li>
    <li>vencord</li>
    <li>vencord-web-extension</li>
    <li>vieb</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vsce</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
    <li>vscode-langservers-extracted</li>
    <li>webcord</li>
    <li>webcord-vencord</li>
    <li>webtorrent_desktop</li>
    <li>weylus</li>
    <li>windmill</li>
    <li>yarn-lock-converter</li>
    <li>ycmd</li>
    <li>zigbee2mqtt</li>
    <li>zincsearch</li>
    <li>zrythm</li>
    <li>zx</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
Oops, I shouldn't have merged. This isn't quite enough because we need directories like `$out/share/man/man1`. I pushed a fix to https://github.com/NixOS/nixpkgs/pull/249879

**Pull request merged**
