### PR TITLE
busybox: Fix 404 error

### PR DESCRIPTION
**Pull request by HaoZeke**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TethysSvensson** [comment]
This looks good to me. As far as I can tell, `default.script` is identical in the new package, and that is the only file currently used.

**Review by jonringer — COMMENTED** [review]
I think having the version bump would be more appropriate:
```
busybox: 1.30.1-5 -> 1.30.1-6, fix 404
```

otherwise LGTM

**Comment by TethysSvensson** [comment]
> I think having the version bump would be more appropriate:
> 
> ```
> busybox: 1.30.1-5 -> 1.30.1-6, fix 404
> ```
> 
> otherwise LGTM

It's not a version bump for the entire busybox package, just for the debian package we are using to get a single script for udhcpc.

The current version for busybox itself is 1.31.1.

**Comment by pbogdan** [comment]
It could also be fetched from https://salsa.debian.org/installer-team/busybox/ where it should be possible to pin it to a specific git revision so it doesn't disappear in the future (it doesn't seem the file is being updated frequently / with each release).

**Review by worldofpeace — CHANGES_REQUESTED** [review]
See https://github.com/NixOS/nixpkgs/pull/97286#issuecomment-687820393. That would be much better.

**Comment by TethysSvensson** [comment]
This can be closed now, as it was superseded by #97894.

**Pull request closed without merging**
