### PR TITLE
matrix-appservice-slack: 1.2.0 -> 1.3.1

### PR DESCRIPTION
**Pull request by kampka**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kampka** [comment]
@GrahamcOfBorg build matrix-appservice-slack

**Comment by kampka** [comment]
@GrahamcOfBorg build matrix-appservice-slack

**Review by mmilata — APPROVED** [review]
Changes look good and the package builds and runs fine! Haven't done any testing of functionality yet.

**Comment by mmilata** [comment]
Confirming that this version works :+1: 

Off-topic: have you seen this error before?
<details>
  <summary>Error: ENOENT: no such file or directory, open 'config/slack-config-schema.yaml'</summary>

```
fs.js:114
    throw err;
    ^
Error: ENOENT: no such file or directory, open 'config/slack-config-schema.yaml'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at ConfigValidator._loadFromFile (/nix/store/kv4w6rqv49jimq961wq3l7mx10cwzbr9-node_matrix-appservice-slack-1.3.1/lib/node_modules/matrix-appservice-slack/node_modules/matrix-appservice-bridge/lib/components/config-validator.js:63:29)
    at new ConfigValidator (/nix/store/kv4w6rqv49jimq961wq3l7mx10cwzbr9-node_matrix-appservice-slack-1.3.1/lib/node_modules/matrix-appservice-slack/node_modules/matrix-appservice-bridge/lib/components/config-validator.js:29:28)
    at Cli._loadConfig (/nix/store/kv4w6rqv49jimq961wq3l7mx10cwzbr9-node_matrix-appservice-slack-1.3.1/lib/node_modules/matrix-appservice-slack/node_modules/matrix-appservice-bridge/lib/components/cli.js:159:21)
    at Cli._assignConfigFile (/nix/store/kv4w6rqv49jimq961wq3l7mx10cwzbr9-node_matrix-appservice-slack-1.3.1/lib/node_modules/matrix-appservice-slack/node_modules/matrix-appservice-bridge/lib/components/cli.js:144:23)
    at Cli.run (/nix/store/kv4w6rqv49jimq961wq3l7mx10cwzbr9-node_matrix-appservice-slack-1.3.1/lib/node_modules/matrix-appservice-slack/node_modules/matrix-appservice-bridge/lib/components/cli.js:139:10)
    at Object.<anonymous> (/nix/store/kv4w6rqv49jimq961wq3l7mx10cwzbr9-node_matrix-appservice-slack-1.3.1/lib/node_modules/matrix-appservice-slack/lib/app.js:57:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```
</details>

Do you have to change the current working directory to `${pkg}/lib/node_modules/matrix-appservice-slack` before running `matrix-appservice-slack` or am I missing something?

**Comment by kampka** [comment]
> Do you have to change the current working directory to `${pkg}/lib/node_modules/matrix-appservice-slack` before running `matrix-appservice-slack` or am I missing something?

Yes, pretty much. I have a service configuration for it that looks like this:
https://gist.github.com/kampka/a3d05fde767aabea612a040129ffa259

**Comment by mmilata** [comment]
That's very similar to service what I ended up with:) If matrix-org/matrix-appservice-slack#415 is merged it won't be needed in next release.

**Pull request merged**
