### PR TITLE
egl-wayland: 1.1.7 -> 1.1.9

### PR DESCRIPTION
**Pull request by abdelq**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
It is okay to target this to `master` I think.

**Comment by abdelq** [comment]
Just remembered why I put it in staging. It depends on version 1.3.4 of libglvnd to build properly.

**Comment by abdelq** [comment]
Now that https://github.com/NixOS/nixpkgs/pull/143028 is merged, could we get this one merged too please?

**Review by fabianhjr — APPROVED** [review]
LGTM, built on NixOS-x86_64

```
33 packages marked as broken and skipped
94 packages built:
adapta-gtk-theme cage cagebreak chrome-gnome-shell dwl egl-wayland fnott gnome.gdm gnome.gnome-applets gnome.gnome-control-center gnome.gnome-flashback gnome.gnome-initial-setup gnome.gnome-panel gnome.gnome-session gnome.gnome-shell gnome.gnome-terminal gnome.gnome-tweaks gnome.gpaste gnome.mutter gnome.mutter338 gnome.pomodoro gnomeExtensions.easyScreenCast gnomeExtensions.gsconnect gnomeExtensions.night-theme-switcher gnomeExtensions.system-monitor hikari kdev-php kdev-python kdevelop kdevelop-unwrapped labwc libsForQt5.kde-cli-tools libsForQt5.kdeplasma-addons libsForQt5.khotkeys libsForQt5.kinfocenter libsForQt5.kmenuedit libsForQt5.krohnkite libsForQt5.kwin libsForQt5.kwin-dynamic-workspaces libsForQt5.kwin-tiling libsForQt5.parachute libsForQt5.plasma-browser-integration libsForQt5.plasma-desktop libsForQt5.plasma-disks libsForQt5.plasma-workspace libsForQt5.powerdevil libsForQt5.systemsettings monitor nwg-panel pantheon.elementary-greeter pantheon.elementary-gsettings-schemas pantheon.elementary-session-settings pantheon.gala pantheon.switchboard-plug-a11y pantheon.switchboard-plug-mouse-touchpad pantheon.switchboard-plug-pantheon-shell pantheon.switchboard-plug-power pantheon.switchboard-plug-security-privacy pantheon.switchboard-with-plugs pantheon.wingpanel pantheon.wingpanel-applications-menu pantheon.wingpanel-indicator-a11y pantheon.wingpanel-indicator-bluetooth pantheon.wingpanel-indicator-datetime pantheon.wingpanel-indicator-keyboard pantheon.wingpanel-indicator-network pantheon.wingpanel-indicator-nightlight pantheon.wingpanel-indicator-notifications pantheon.wingpanel-indicator-power pantheon.wingpanel-indicator-session pantheon.wingpanel-indicator-sound pantheon.wingpanel-with-indicators phoc phosh qt-video-wlr river sway sway-contrib.grimshot sway-unwrapped tinywl vimix-gtk-themes wacomtablet waybar waybox wayfire wayfirePlugins.wayfire wayfirePlugins.wf-shell wayfireApplications-unwrapped.wcm wcm weston whitesur-gtk-theme wio wlroots xwayland
```

**Review by mvnetbiz — APPROVED** [review]
Firefox now recognizes nvidia gpu.

**Comment by colemickens** [comment]
This is on my radar, but what of the regressions that @vcunat pointed out? Are we sure they're resolved and that there aren't further regressions?

As part of the work I'm doing on this nvidia stuff, I'm considering adding a level somewhere to make the egl-wayland configuration flexible so the user could override nvidia with a different version of upstream egl-wayland. That might upgrades easier, we could keep a few versions side-by-side even and pick a default, let users opt-in, etc.

**Comment by fabianhjr** [comment]
Can't test; seems to be mostly hydrid/prime related and I am not on an APU.

**Comment by mvnetbiz** [comment]
Cheese opens but the camera view glitches out, no problems with any other applications mentioned. I don't have hybrid graphics though.

**Comment by fabianhjr** [comment]
@colemickens, I have been using the version bump for a whole day without issues on NixOS Linux 5.15 (/w nvidia dirivers version 495.44); those issues reported could have been caused by any other factors like nvidia driver versions or toolchain used to compile.

Also, Wayland /w Nvidia is experimental and disabled by default. To use wayland on gdm /w nvidia for example one must set this config:

```
      displayManager.gdm = {
        enable = true;
        nvidiaWayland = true;
      };
```

I think this can be safely merged and would be a net gain on experience.

**Review by fabianhjr — APPROVED** [review]
Makes steam and webgl usable under wayland and nvidia on NixOS.

Tested alongside #145319 and #145439

**Review by Artturin — APPROVED** [review]
fabian has been using it for 10 days

**Comment by nrdxp** [comment]
due to the nature of NVIDIA/egl-wayland#40, it is import somebody test this on plasma if you really want to merge before release

**Comment by nrdxp** [comment]
Result of `nixpkgs-review pr 138180` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>33 packages marked as broken and skipped:</summary>
  <ul>
    <li>libsForQt512.kde-cli-tools</li>
    <li>libsForQt512.kdeplasma-addons</li>
    <li>libsForQt512.khotkeys</li>
    <li>libsForQt512.kinfocenter</li>
    <li>libsForQt512.kmenuedit</li>
    <li>libsForQt512.krohnkite</li>
    <li>libsForQt512.kwin</li>
    <li>libsForQt512.kwin-dynamic-workspaces</li>
    <li>libsForQt512.kwin-tiling</li>
    <li>libsForQt512.parachute</li>
    <li>libsForQt512.plasma-browser-integration</li>
    <li>libsForQt512.plasma-desktop</li>
    <li>libsForQt512.plasma-disks</li>
    <li>libsForQt512.plasma-workspace</li>
    <li>libsForQt512.powerdevil</li>
    <li>libsForQt512.systemsettings</li>
    <li>libsForQt514.kde-cli-tools</li>
    <li>libsForQt514.kdeplasma-addons</li>
    <li>libsForQt514.khotkeys</li>
    <li>libsForQt514.kinfocenter</li>
    <li>libsForQt514.kmenuedit</li>
    <li>libsForQt514.krohnkite</li>
    <li>libsForQt514.kwin</li>
    <li>libsForQt514.kwin-dynamic-workspaces</li>
    <li>libsForQt514.kwin-tiling</li>
    <li>libsForQt514.parachute</li>
    <li>libsForQt514.plasma-browser-integration</li>
    <li>libsForQt514.plasma-desktop</li>
    <li>libsForQt514.plasma-disks</li>
    <li>libsForQt514.plasma-workspace</li>
    <li>libsForQt514.powerdevil</li>
    <li>libsForQt514.systemsettings</li>
    <li>xmonad_log_applet</li>
  </ul>
</details>
<details>
  <summary>94 packages built:</summary>
  <ul>
    <li>adapta-gtk-theme</li>
    <li>cage</li>
    <li>cagebreak</li>
    <li>chrome-gnome-shell</li>
    <li>dwl</li>
    <li>egl-wayland</li>
    <li>fnott</li>
    <li>gnome.gdm</li>
    <li>gnome.gnome-applets</li>
    <li>gnome.gnome-control-center (gnome.gnome_control_center)</li>
    <li>gnome.gnome-flashback</li>
    <li>gnome.gnome-initial-setup</li>
    <li>gnome.gnome-panel</li>
    <li>gnome.gnome-session (gnome.gnome_session)</li>
    <li>gnome.gnome-shell (gnome.gnome_shell)</li>
    <li>gnome.gnome-terminal (gnome.gnome_terminal)</li>
    <li>gnome.gnome-tweaks (gnome.gnome-tweak-tool)</li>
    <li>gnome.gpaste</li>
    <li>gnome.mutter</li>
    <li>gnome.mutter338 (pantheon.mutter)</li>
    <li>gnome.pomodoro</li>
    <li>gnomeExtensions.easyScreenCast</li>
    <li>gnomeExtensions.gsconnect</li>
    <li>gnomeExtensions.night-theme-switcher</li>
    <li>gnomeExtensions.system-monitor</li>
    <li>hikari</li>
    <li>kdev-php</li>
    <li>kdev-python</li>
    <li>kdevelop</li>
    <li>kdevelop-unwrapped</li>
    <li>labwc</li>
    <li>libsForQt5.kde-cli-tools (libsForQt515.kde-cli-tools ,plasma5Packages.kde-cli-tools)</li>
    <li>libsForQt5.kdeplasma-addons (libsForQt515.kdeplasma-addons ,plasma5Packages.kdeplasma-addons)</li>
    <li>libsForQt5.khotkeys (libsForQt515.khotkeys ,plasma5Packages.khotkeys)</li>
    <li>libsForQt5.kinfocenter (libsForQt515.kinfocenter ,plasma5Packages.kinfocenter)</li>
    <li>libsForQt5.kmenuedit (libsForQt515.kmenuedit ,plasma5Packages.kmenuedit)</li>
    <li>libsForQt5.krohnkite (libsForQt515.krohnkite ,plasma5Packages.krohnkite)</li>
    <li>libsForQt5.kwin (libsForQt515.kwin ,plasma5Packages.kwin)</li>
    <li>libsForQt5.kwin-dynamic-workspaces (libsForQt515.kwin-dynamic-workspaces ,plasma5Packages.kwin-dynamic-workspaces)</li>
    <li>libsForQt5.kwin-tiling (libsForQt515.kwin-tiling ,plasma5Packages.kwin-tiling)</li>
    <li>libsForQt5.parachute (libsForQt515.parachute ,plasma5Packages.parachute)</li>
    <li>libsForQt5.plasma-browser-integration (libsForQt515.plasma-browser-integration ,plasma5Packages.plasma-browser-integration)</li>
    <li>libsForQt5.plasma-desktop (libsForQt515.plasma-desktop ,plasma5Packages.plasma-desktop)</li>
    <li>libsForQt5.plasma-disks (libsForQt515.plasma-disks ,plasma5Packages.plasma-disks)</li>
    <li>libsForQt5.plasma-workspace (libsForQt515.plasma-workspace ,plasma5Packages.plasma-workspace)</li>
    <li>libsForQt5.powerdevil (libsForQt515.powerdevil ,plasma5Packages.powerdevil)</li>
    <li>libsForQt5.systemsettings (libsForQt515.systemsettings ,plasma5Packages.systemsettings)</li>
    <li>monitor</li>
    <li>nwg-panel</li>
    <li>pantheon.elementary-greeter</li>
    <li>pantheon.elementary-gsettings-schemas</li>
    <li>pantheon.elementary-session-settings</li>
    <li>pantheon.gala</li>
    <li>pantheon.switchboard-plug-a11y</li>
    <li>pantheon.switchboard-plug-mouse-touchpad</li>
    <li>pantheon.switchboard-plug-pantheon-shell</li>
    <li>pantheon.switchboard-plug-power</li>
    <li>pantheon.switchboard-plug-security-privacy</li>
    <li>pantheon.switchboard-with-plugs</li>
    <li>pantheon.wingpanel</li>
    <li>pantheon.wingpanel-applications-menu</li>
    <li>pantheon.wingpanel-indicator-a11y</li>
    <li>pantheon.wingpanel-indicator-bluetooth</li>
    <li>pantheon.wingpanel-indicator-datetime</li>
    <li>pantheon.wingpanel-indicator-keyboard</li>
    <li>pantheon.wingpanel-indicator-network</li>
    <li>pantheon.wingpanel-indicator-nightlight</li>
    <li>pantheon.wingpanel-indicator-notifications</li>
    <li>pantheon.wingpanel-indicator-power</li>
    <li>pantheon.wingpanel-indicator-session</li>
    <li>pantheon.wingpanel-indicator-sound</li>
    <li>pantheon.wingpanel-with-indicators</li>
    <li>phoc</li>
    <li>phosh</li>
    <li>qt-video-wlr</li>
    <li>river</li>
    <li>sway</li>
    <li>sway-contrib.grimshot</li>
    <li>sway-unwrapped</li>
    <li>tinywl</li>
    <li>vimix-gtk-themes</li>
    <li>wacomtablet</li>
    <li>waybar</li>
    <li>waybox</li>
    <li>wayfire</li>
    <li>wayfirePlugins.wayfire (wayfireApplications-unwrapped.wayfire)</li>
    <li>wayfirePlugins.wf-shell (wayfireApplications-unwrapped.wayfirePlugins.wf-shell)</li>
    <li>wayfireApplications-unwrapped.wcm</li>
    <li>wcm</li>
    <li>weston</li>
    <li>whitesur-gtk-theme</li>
    <li>wio</li>
    <li>wlroots</li>
    <li>xwayland</li>
  </ul>
</details>

**Comment by fabianhjr** [comment]
Haven't tested plasma, will do so this afternoon thanks for the pointer.

Tested with GNOME 40/41

**Comment by fabianhjr** [comment]
image

I don't use KDE Plasma but it starts alright and I was able to loging via gdm to KDE Plasma Wayland, take a screenshot, and post this comment.

**Comment by fabianhjr** [comment]
Please note there is a worrisome comment regarding post 1.1.7 versions:

> > This will be fixed in upcoming 495 driver. Until then, downgrading to 1.1.7 is the best option.

> So you are saying future versions of egl-wayland will need driver version 495 or newer? Where does this leave users of Kepler? It was reported that 470 would be the last version to support that generation of GPU. Will a future version of egl-wayland be fixed to work with the 470 version, or will the driver fix be backported?

https://github.com/NVIDIA/egl-wayland/issues/40#issuecomment-930286036

Seems like 1.1.9 require nvidia 495 or later drivers.

**Comment by Baughn** [comment]
I want to chime in and say that this PR is a huge upgrade. With it, 3D rendering via XWayland -- at least on Gnome -- appears to just work; Steam / Proton included.

Since others may want to follow along at home, here's how to test it. Simply put this in your configuration.nix. It may or may not work with other compositors than Gnome's; I haven't tested that.

```
 # https://github.com/NixOS/nixpkgs/pull/138180
  environment.variables.GBM_BACKENDS_PATH = "/run/opengl-driver/lib/gbm";
  nixpkgs.overlays = let
    nixpkgs-tars = "https://github.com/NixOS/nixpkgs/archive";
    pr138180 = import (fetchTarball {
      url = "${nixpkgs-tars}/49a2d9ba22d78fc60917fed918c8ebc97ed458ea.tar.gz";
      sha256 = "06frgm7a1j5d4hdxqqcjwr0dcr8a3c38pzb572smmhwfb7k07sxd";
    }) {
      config = config.nixpkgs.config; 
      system = config.nixpkgs.system;
    };
  in [(self: super: {
    egl-wayland = pr138180.egl-wayland;
  })];
```

**Comment by nrdxp** [comment]
Well we've already missed the window to include this in the next release, so there is no rush on this. But once it does get merged, and everything appears to work properly, I don't see any problem with backporting it to 21.11. The only outstanding concern is @fabianhjr's comment above about the 495 series now being required, and so not working for older nvidia hardware.

Perhaps we'll have to add some logic to detect if a user is using the legacy driver and stick with 1.1.7 in that case. We may have to maintain more than one version after all.

**Comment by vcunat** [comment]
This doesn't seem to be a big rebuild, so I believe that strictly speaking you have NOT missed the 21.11 window yet.

**Comment by fabianhjr** [comment]
> The only outstanding concern is @fabianhjr's comment above about the 495 series now being required, and so not working for older nvidia hardware.

That was posted as a question and quoted and it is unclear if more recent patch releases of 470 for example can work with egl-wayland. In particular it would be great if someone could test: 

- 470.86 | November 10, 2021
- 460.91.03 | July 20, 2021

**Comment by Baughn** [comment]
> That was posted as a question and quoted and it is unclear if more recent patch releases of 470 for example can work with egl-wayland-1.1.9; In particular it would be great if someone could test:

I don't see a package for 460 in nixpkgs-unstable. However, I tested 470 by setting `hardware.nvidia.package = pkgs.linuxPackages.nvidiaPackages.legacy_470`.

```
saya :: ~ » glxinfo
name of display: :0
display: :0  screen: 0
direct rendering: Yes
server glx vendor string: SGI
server glx version string: 1.4
server glx extensions:
  (snip)
client glx vendor string: NVIDIA Corporation
client glx version string: 1.4
client glx extensions:
  (snip)
GLX version: 1.4
GLX extensions:
  (snip)
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 24576 MB
    Total available memory: 24576 MB
    Currently available dedicated video memory: 22932 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce RTX 3090/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 470.86
OpenGL core profile shading language version string: 4.60 NVIDIA
```
eglinfo reports similar results. Steam still works; so do games such as Satisfactory (Vulkan, via Proton), Carrier Command 2 (DirectX, ditto) and Oxygen Not Included (native). Firefox rendering performance is noticably inferior, mostly on Github (d'oh), but you can't have everything. Also, I was able to bring Firefox up to par by force-enabling Webrender.

(That being par for the 490 driver, which is still vastly inferior to Firefox on Windows. Different discussion.)

**Comment by Baughn** [comment]
The GBM_BACKENDS_PATH environment setting from my earlier snippet does not appear to be needed anymore. That was left over from an earlier attempt at getting this working.

**Comment by fabianhjr** [comment]
Ok, so 1.1.9 does work with legacy drivers (at least as how it is distributed and used in NixOS), works on gnome and plasma, and I think there are no more blockers left. :3

**Comment by Baughn** [comment]
Things that don't work with this patch: Discord stops functioning at all, rendering a black window.

This can be worked around by running it as `discord --disable-gpu`. I'm unsure if we'd want to do anything about it; it's also supposed to run natively on Wayland now, which would be superior, but I figure out how to test it.

**Comment by Baughn** [comment]
> The GBM_BACKENDS_PATH environment setting from my earlier snippet does not appear to be needed anymore. That was left over from an earlier attempt at getting this working.

This is false. It is needed; the setting simply has no effect _on applications_. It's probably affecting Xwayland.

Without it, GLX doesn't work. So while this PR is still a step in the right direction, it's incomplete on its own.

**Comment by fabianhjr** [comment]
Regarding that, https://github.com/NixOS/nixpkgs/pull/145319 is on `staging-next` and could be merge in the following days.

As mentioned, that was used during testing on my end.

**Comment by colemickens** [comment]
I actually using a commit or two beyond 1.1.9 just for fun, and as far as I can tell, Plasma and Gnome are working (and seemingly well after bumping up my refresh rates in their respective settings), but this is just further confirmation of what @fabianhjr has reported. That and we have a test report with the 470 series driver, so I also agree that blockers are resolved.

If there's no objections, I'll merge this in the next day or two, I'd love to have this and #145319 be in `nixos-unstable` soon to test all end-to-end.

**Comment by nrdxp** [comment]
if #145319 is a dependancy for certain applications, we might want to wait on the merge until that hits master

**Comment by colemickens** [comment]
While related, that PR is not a dependency to this one, they're fairly orthogonal changes. It's more just the case that NVidia users really need both for sway to work out-of-box. This PR is still beneficial to non-nvidia users, doesn't rely on mesa's gbm loading, etc.

**Comment by fabianhjr** [comment]
> If there's no objections, I'll merge this in the next day or two, I'd love to have this and #145319 be in nixos-unstable soon to test all end-to-end.

> if #145319 is a dependancy for certain applications, we might want to wait on the merge until that hits master

Since the mentioned PR is on staging-next it would currently merge into master just before branch off of `21.11` (which was scheduled for today), wouldn't it be better to merge now to either master or staging-next to ensure both are on 21.11? (This is relatively on the non world-rebuilding side and staging next still has a long queue before merging and the time window for branch off after that merge might be very small)

**Comment by colemickens** [comment]
I was being shy, given the newness of my commit bit, but I agree with your analysis and think we have enough consensus from involved/testing folks. I'll merge it.

**Comment by fabianhjr** [comment]
Thanks for the PR @abdelq and everyone else that tested and helped along the way. :3

**Pull request merged**
