### PR TITLE
staging-next 2023-08-30

### PR DESCRIPTION
**Pull request by vcunat**
##### Helpful links

- workflow docs: https://nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy
- important jobs:
  https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
  https://hydra.nixos.org/job/nixos/staging-next-small/tested
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next
  https://hydra.nixos.org/jobset/nixos/staging-next-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/250778
- - - 
##### Mass breakages
(will be edited based on progress)

### CODE REVIEW

**Comment by vcunat** [comment]
Huge amount of x86_64-darwin failures were apparently just a broken machine on the farm.  I'll restart them later (for now all machines have plenty other work to do).

**Comment by vcunat** [comment]
https://hydra.nixos.org/eval/1798974?compare=1798972
Basically all *-linux is rebuilt, and regressions look OK to me.  Mostly various fallout from rustc update I think, as usual.

**Comment by vcunat** [comment]
So, the regressions due to rustc update #251174 (apparently) &ndash; they don't seem like anything to block for, but let me /cc the maintainers anyway:
- [ ] `edge-runtime` @happysalada
  https://hydra.nixos.org/build/233594310/nixlog/2/tail
- [ ] `eww*` @figsoda @legendofmiracles
  https://hydra.nixos.org/build/233537438/nixlog/3/tail
- [ ] `gitoxide` @syberant
  https://hydra.nixos.org/build/233481358/nixlog/3/tail
- [ ] `influxdb2` (libflux) @abbradar @danderson
  https://hydra.nixos.org/build/233405572/nixlog/3/tail
- [ ] `rome` @dit7ya @felschr
  https://hydra.nixos.org/build/233453580/nixlog/3/tail
- [ ] `srvc` @john-shaffer
  https://hydra.nixos.org/build/233561869/nixlog/3/tail
- [ ] `turbo` @dlip
  https://hydra.nixos.org/build/233545788/nixlog/5/tail
- [ ] `wasmtime` @ereslibre
  https://hydra.nixos.org/build/233586502/nixlog/2/tail
- [ ] `windmill` @dit7ya
  https://hydra.nixos.org/build/233468310/nixlog/119/tail
- [x] `aardvark-dns` 8490868860c9

**Comment by figsoda** [comment]
eww: #253145

**Comment by happysalada** [comment]
regarding edge-runtime, it appears the update is not as easy as just updating to the latest version. Not a blocker, I'm checking with upstream.

**Comment by happysalada** [comment]
Actually, all is good 
edge-runtime: https://github.com/NixOS/nixpkgs/pull/253180

**Comment by ereslibre** [comment]
wasmtime: I created https://github.com/NixOS/nixpkgs/pull/253265

This is an issue due to a limitation of `cargo-auditable`, used by the rust build-support infra. I am not familiar with the rust build-support, but I suspect bumping cargo_metadata to 0.17.0 at the [cargo-auditable](https://github.com/rust-secure-code/cargo-auditable/blob/master/cargo-auditable/Cargo.toml#L25) project will fix this issue, given this crate is using some new functionality on how to refer to dependencies and features with the `opt:` keyword.

The PR I for wasmtime fixes the issue temporarily until cargo-auditable is fixed/bumped. I can look into that more in detail, and when the issue is fixed, we can get rid of the workaround I submitted at https://github.com/NixOS/nixpkgs/pull/253265

**Comment by dlip** [comment]
I created a fix for turbo #253339

**Pull request merged**
