### PR TITLE
firefox: 78.0.2 -> 79.0, 68.10.0esr -> 68.11.0esr, 78.1.0esr [High security fixes]

### PR DESCRIPTION
**Pull request by taku0**
###### Motivation for this change

- High security fixes
- Other updates and fixes.

https://www.mozilla.org/en-US/firefox/79.0/releasenotes/
https://www.mozilla.org/en-US/security/advisories/mfsa2020-30/

https://www.mozilla.org/en-US/firefox/78.1.0/releasenotes/
https://www.mozilla.org/en-US/security/advisories/mfsa2020-32/

https://www.mozilla.org/en-US/firefox/68.11.0/releasenotes/
https://www.mozilla.org/en-US/security/advisories/mfsa2020-31/

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ajs124** [comment]
Have you tested if all of these compile and work? I did these bumps a few days ago as well, but haven't gotten around to posting a PR because someone thought it would be a good idea to manipulate my build infrastructure for no good reason.

**Comment by taku0** [comment]
Yes. All of 79.0, 78.1.0esr, and 68.11.0esr played YouTube video fine. https://www.youtube.com/user/firefoxchannel

**Review by vcunat — APPROVED** [review]
I've been doing some testing; no issues so far.

**Comment by vcunat** [comment]
Backporting to release-20.03: I gave up on FF 79 (feel free to try), so for now I made it default to ESR 78 in ea0b3dd.  In particular I noticed that ESR 68 is planned to end support a bit earlier than NixOS 20.03, so perhaps 78 will become the only compiled FF that we support in there in September.

**Pull request merged**
