### PR TITLE
staging-next 2024-02-03

### PR DESCRIPTION
**Pull request by vcunat**
##### Helpful links

- workflow docs: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#staging
- important jobs:
  https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
  https://hydra.nixos.org/job/nixos/staging-next-small/tested
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next
  https://hydra.nixos.org/jobset/nixos/staging-next-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/281828
- - - 
##### Mass breakages
(will be edited based on progress)

### CODE REVIEW

**Comment by vcunat** [comment]
[`pkgsi686Linux.coreutils`](https://hydra.nixos.org/build/248417723):
```
-du: cannot access: Too many levels of symbolic links
+du: cannot read directory: Too many levels of symbolic links
FAIL tests/du/long-sloop.sh (exit status: 1)
```
I fail to reproduce that.  Could that be an impurity based on host's kernel version?

**Comment by vcunat** [comment]
- [ ] `python312` broken on aarch64-darwin (but OK on x86_64-linux)
  https://hydra.nixos.org/build/248410479/nixlog/2/tail

**Comment by infinisil** [comment]
You can ignore the `pkgs/by-name` check failure, it's the same as in in the original PR: https://github.com/NixOS/nixpkgs/pull/284964#discussion_r1471974549

**Comment by fabianhjr** [comment]
Have been unable to debug a build hang of samba for i686: https://github.com/NixOS/nixpkgs/issues/287339

UnU

**Pull request merged**
