### PR TITLE
python.pkgs.{gitdb,GitPython}: update

### PR DESCRIPTION
**Pull request by timokau**
###### Motivation for this change

I had issues with the outdated `GitPython` and the `gitdb` update is a dependency.

@FRidh do you think dropping `gitdb2` is the right thing to do, given the merge and that gitdb is the canonical version?

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
From the linked issue:

> In 2015 ...

Yes, let's make this change.

**Comment by timokau** [comment]
To be precise, the split happened in 2015 but the merge back only happened recently. So it may very well be that people are using `gitdb2` somewhere. That would break.

It wouldn't be difficult to fix though, so I don't see much point in backwards compatibility here.

I noticed that `smmap2` was in a similar situation (from the same devs), so I applied the same change there. `nix-review` revealed taht `gitdb2` is no longer py2 compatible, so I dropped that. I think this is ready now.

**Review by jonringer — APPROVED** [review]
LGTM

```
[31 built (2 failed), 778 copied (2732.6 MiB), 505.1 MiB DL]
error: build of '/nix/store/mqs5ws3sb5akiigcpaklxxdw8rrqjhzj-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/82589
2 package failed to build:
dvc-with-remotes python38Packages.apache-airflow

27 package built:
apache-airflow dvc fdroidserver fluidasserts git-repo-updater git-up mlflow-server opentimestamps-client python37Packages.GitPython python37Packages.bandit python37Packages.cccolutils python37Packages.git-sweep python37Packages.gitdb python37Packages.mlflow python37Packages.nbdime python37Packages.opentimestamps python37Packages.stytra python38Packages.GitPython python38Packages.bandit python38Packages.cccolutils python38Packages.git-sweep python38Packages.gitdb python38Packages.mlflow python38Packages.nbdime python38Packages.opentimestamps python38Packages.stytra snakemake
```

slightly concerned about the removals. Might be nice to do a 
```
  gitdb2 = throw "gitdb2 has been deprecated, use gitdb instead."; # added 2020-MM-DD
```

**Comment by timokau** [comment]
Yeah, that might be helpful. How about this?

**Review by jonringer — APPROVED** [review]

**Pull request merged**
