### PR TITLE
Python package set: mostly patch updates

### PR DESCRIPTION
**Pull request by FRidh**
###### Motivation for this change

https://hydra.nixos.org/jobset/nixpkgs/python-unstable

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dotlambda** [comment]
Do you think we can update requests to 2.21.0? Do requests bumps usually yield a lot of failures?

**Comment by dotlambda** [comment]
The last few fixes are all due to 05232abbbc6574b31a714bc34d9639676b83c1a8.

**Comment by FRidh** [comment]
Thanks @dotlambda. I am removing a bunch of the pkgconfig changes because those were already correct.

**Comment by vcunat** [comment]
I noticed many new `google-cloud-*` failures on staging-next Hydra:
```
Collecting google-cloud-core<0.30dev,>=0.29.0 (from google-cloud-dns==0.29.2)
  Could not find a version that satisfies the requirement google-cloud-core<0.30dev,>=0.29.0 (from google-cloud-dns==0.29.2) (from versions: )
No matching distribution found for google-cloud-core<0.30dev,>=0.29.0 (from google-cloud-dns==0.29.2)
```
... so you just forgot commit with `google-cloud-core` update somewhere?  (I don't know your workflow.)

**Comment by dotlambda** [comment]
I have pushed appropriate updates to staging-next.

**Pull request merged**
