### PR TITLE
build-support/release: deprecate phases

### PR DESCRIPTION
**Pull request by Stunkymonkey**
###### Description of changes

#28910

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mindavi** [comment]
How do you build this?

**Comment by Stunkymonkey** [comment]
> How do you build this?

thats a very good question... I wanted to bring the issue a bit closer to completion and hoped someone will come and tell us here.

**Comment by ralismark** [comment]
I don't think I'm the right person to review this, but I'm not really sure who is.

This seems to have been added by @ericsagnes in this PR, and not really touched since:

- https://github.com/NixOS/nixpkgs/pull/17681

There's also [only around 32 usages on github](https://github.com/search?q=releaseTools.channel&type=code).

**Comment by piegamesde** [comment]
The PR title confused me for a bit here. Instead of "deprecate phases", maybe something like "stop declaring phases because it is deprecated"?

**Comment by Stunkymonkey** [comment]
maybe:
- @markuskowa (https://github.com/Nix-QChem/NixOS-QChem/blob/813b42461681186d483fd74f9973e20c1080017d/release.nix#L121)
- @dpausp (https://github.com/flyingcircusio/fc-nixos/blob/ef4aadcbd375e085881d4f1a55e318d92a9e7010/release/default.nix#L273)

can help here? Both of you used it recently.

**Comment by markuskowa** [comment]
@Stunkymonkey I am not sure I have set opinion on this change. Maybe just a few thoughts:
* Removing  "phases" here has no big benefit. It will now run all phases and just take longer.
* The channel build is no typical build that fits the schema of `mkDerivation` with all its phases. So the arguments made in https://github.com/NixOS/nixpkgs/issues/28910 about keeping the build clean do not really apply here.
* Could `mkDerivation`  be replaced with `runCommand` here?

**Comment by Stunkymonkey** [comment]
first of all thanks for responding @markuskowa . Is the latest commit the right direction?

I still do not know how to test this. Can you give an example? I am also fine if you can test it yourself.

**Comment by markuskowa** [comment]
@Stunkymonkey It seems that run command ignore the `src` input. I.e. the channel is empty now.
You can test this like this `nix-build -A releaseTools.channel --arg src ./. --argstr name test`.

Maybe it is better to revert to `mkDerivation` and disable the unneeded phases with `dontConfigure` and `dontBuild` instead.

**Review by markuskowa — APPROVED** [review]
It looks good to me, and seems to still work as intended.
However, since this is probably also used to generate the oficial nixos channels, it would be good if someone familiar with the nixos.org infrastructure has a look at it also.

CC @vcunat ?

**Comment by vcunat** [comment]
I anticipate no infra issues, if it still builds.

**Pull request merged**
