### PR TITLE
Add ocaml-cow & update needed ocaml-packages (especially async_ssl related stuff)

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### State of this PR

I expect to break a few packages with this PR, but I wanted to open this for discussion as soon as possible.

Known breakages are currently:

* `  ocamlPackages_4_02.trv`  

I am eager to hear your opinions! Especially if you know a good method for testing for breakages inside `  ocamlPackages`  .

### CODE REVIEW

**Comment by vbgl** [comment]
I’ve merged the `ezjsonm` update in 44820907afab52221ac7db20bf6e115ee42a927a and the init of `logs` in 4f0feb4f5f2f4662a075f015d9675b25865b3ae9, as they are independent of this issue.

**Comment by sternenseemann** [comment]
@vbgl seems resonable, will rebase those commits out of this branch!

**Comment by vbgl** [comment]
I took care of the `uri` update in d2a4a84f00019596006cf218df9f8b143c7d624d, and cherry-picked the init of `cow` in a452714799b36fae4c34e7167122d2b26ff07747 (after fixing the propagated inputs).

How did you end up touching `ipaddr` and `async_ssl`?

All this `_p4` stuff is an ugly mess; we need to find a proper way to deal with several incompatible versions of the set of `core` libraries…

**Comment by FlorentBecker** [comment]
I have a pr coming for the core stuff.

**Comment by sternenseemann** [comment]
@vbgl because `  cow`   depends on the most current version of `  uri`  , that update then caused all the other changes.

**Comment by sternenseemann** [comment]
I don't think these changes are not too important at the moment, maybe, we better wait with the updates of `  cohttp`   and `  async_ssl`   since the `  core`  -stuff has been resolved by @FlorentBecker?

**Comment by FlorentBecker** [comment]
Sorry, I misunderstood what the problem with core was, I haven't fixed it. I think we should drop packages which only compile with caml 4.01 (here, it seems trv is the one causing trouble).

**Comment by sternenseemann** [comment]
This seems like a reasonable idea in the long term, many of the current dependencies to `  _p4`   packages can be resolved by updating the packages.

**Comment by vbgl** [comment]
I think this kind of reasoning is flowed. In the long term, every single package that is currently in nixpkgs will be removed or completely rewritten. Each package is a temporary hack to accommodate for the current state of the world. We cannot just wait that everything eventually gets fixed.

`trv` in nixpkgs is available on 4.02 only. It builds and seems to work. It has been recently added with — I guess — some user need in mind. And I don’t see how removing it will help solving actual issues (like, say, having `ocamlPackages_latest.sexplib` build).

**Comment by FlorentBecker** [comment]
My mistake, I thought trv was old and unmaintained, it isn't.

**Comment by FlorentBecker** [comment]
@ericbmerritt : is trv supposed to be in nixpkgs? Its homepage says it isn't.

**Comment by vbgl** [comment]
Cherry-picked the `ipaddr` update in 8352e0b38c65a736219619d8821ad50f787e58d1

**Pull request closed without merging**
