### PR TITLE
python3Packages.rasterio: 1.3.5 -> 1.3.6

### PR DESCRIPTION
**Pull request by imincik**
###### Description of changes

Update to latest bug fix release.

List of changes: https://github.com/rasterio/rasterio/releases/tag/1.3.6

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by imincik** [comment]
Manual testing:

```
./result/bin/rio --show-versions
rasterio info:
  rasterio: 1.3.6
      GDAL: 3.6.3
      PROJ: 9.2.0
      GEOS: 3.11.1
 PROJ DATA: /home/imincik/.local/share/proj:/nix/store/xv3lvdxb29s9n2mqf1nc1lrn4sa62h8h-proj-9.2.0/share/proj:/nix/store/xv3lvdxb29s9n2mqf1nc1lrn4sa62h8h-proj-9.2.0/share/proj
 GDAL DATA: None

System:
    python: 3.10.10 (main, Feb  7 2023, 12:19:31) [GCC 12.2.0]
executable: /nix/store/0n4y44dnaxafqs7cg625aldrb152x7bx-python3-3.10.10/bin/python3.10
   machine: Linux-5.15.102-x86_64-with-glibc2.35

Python deps:
    affine: 2.4.0
     attrs: 22.2.0
   certifi: 2022.12.07
     click: 8.1.3
     cligj: 0.7.2
    cython: None
     numpy: 1.24.2
    snuggs: 1.4.7
click-plugins: None
setuptools: 67.4.0.post0
```

**Review by mredaelli — APPROVED** [review]
Sorry for the delay.

I have to say I haven't used this package for a while. This works for me. If you also want to change the maintainer to yourself, it would probably be best :P

**Comment by imincik** [comment]
> If you also want to change the maintainer to yourself, it would probably be best :P

Thank you very much @mredaelli . I am trying to convince people that it is better to manage geospatial packages as a team, rather than do it as individuals. Is it ok for you to change maintainer to @NixOS/geospatial [team](https://github.com/NixOS/nixpkgs/blob/master/maintainers/team-list.nix#L280) as our first package ?

**Comment by mredaelli** [comment]
> Is it ok for you to change maintainer to @NixOS/geospatial [team](https://github.com/NixOS/nixpkgs/blob/master/maintainers/team-list.nix#L280) as our first package ?

That sounds like a terrific idea!

**Comment by imincik** [comment]
@sikmir , thanks for running nixpkgs-review. Do you have error messages from darwin build of osmnx ?

**Pull request merged**
