### PR TITLE
lldb: fix python lldb library

### LINKED ISSUE #125183: Cannot `import lldb` in lldb anymore
**Describe the bug**
After #111487, `import lldb` in lldb results in a ModuleNotFoundError.

`vscode-extensions.vadimcn.vscode-lldb` is affected by this issue (#119945)

**To Reproduce**
1. On current master, `nix-shell -p lldb_12` (Seems all versions of `lldb` are affected, but I only checked 11 and 12.)
2. `lldb`
3. `script import lldb`, see the error.

**Expected behavior**
Module successfully imported.

**Additional context**
Note that in `lldb_12.out`, `lib/python3.8/site-packages/lldb` DOES exist. Not sure why it failed to import.

**Notify maintainers**

@Ericson2314 @lovek323 @7c6f434c @dtzWill @primeos 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.37, NixOS, 21.11.20210528.540dccb (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210503_6d2553a`
 - channels(root): `"nixos-21.03pre257339.83cbad92d73"`
 - channels(oxa): `"home-manager"`
 - nixpkgs: `/nix/store/49d2fsjglqa57cca9cwqy1rzgxcanjjl-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- lldb_12
- lldb_11
- vscode-extensions.vadimcn.vscode-lldb
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by tcmal**
###### Motivation for this change

Fixes #125183, and should also fix CodeLLDB. Propagated back to LLDB5.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
Patch does not apply to some versions:

```

$ nix --experimental-features nix-command build --no-link --keep-going --option build-use-sandbox relaxed -f /home/s1691654/.cache/nixpkgs-review/pr-126091/build.nix
error: builder for '/nix/store/j4padbci087jrbzrqmsbkhr5ax2nywy3-lldb-7.1.0.drv' failed with exit code 1;
       last 10 log lines:
       > patching sources
       > applying patch /nix/store/7gxywkbcspm0816zjy2dsg2rx4j4i41k-gnu-install-dirs.patch
       > patching file CMakeLists.txt
       > patching file cmake/modules/AddLLDB.cmake
       > patching file cmake/modules/LLDBConfig.cmake
       > patching file tools/intel-features/CMakeLists.txt
       > patching file cmake/modules/LLDBStandalone.cmake
       > patch unexpectedly ends in middle of line
       > Hunk #1 FAILED at 62.
       > 1 out of 1 hunk FAILED -- saving rejects to file cmake/modules/LLDBStandalone.cmake.rej
       For full logs, run 'nix log /nix/store/j4padbci087jrbzrqmsbkhr5ax2nywy3-lldb-7.1.0.drv'.
error: 1 dependencies of derivation '/nix/store/z6bw043nqb93957nryw5p8j6vkm0q2b4-coreclr-2.0.7.drv' failed to build
error: builder for '/nix/store/a9gwp3q51f4lxgss3ayzn88dz1c06hp5-lldb-8.0.1.drv' failed with exit code 1;
       last 10 log lines:
       > patching sources
       > applying patch /nix/store/9aay8im1hw7xmgyvnbpaf3la04rvxznc-gnu-install-dirs.patch
       > patching file CMakeLists.txt
       > patching file cmake/modules/AddLLDB.cmake
       > patching file cmake/modules/LLDBConfig.cmake
       > patching file tools/intel-features/CMakeLists.txt
       > patching file cmake/modules/LLDBStandalone.cmake
       > patch unexpectedly ends in middle of line
       > Hunk #1 FAILED at 62.
       > 1 out of 1 hunk FAILED -- saving rejects to file cmake/modules/LLDBStandalone.cmake.rej
       For full logs, run 'nix log /nix/store/a9gwp3q51f4lxgss3ayzn88dz1c06hp5-lldb-8.0.1.drv'.
error: builder for '/nix/store/9ycf1danp60i2rp2s47gxib0hjrz8aj2-lldb-5.0.2.drv' failed with exit code 1;
       last 10 log lines:
       > Hunk #1 succeeded at 404 (offset 5 lines).
       > applying patch /nix/store/wmd15yk0fwd5r9bfx3xilz22vianlvi4-gnu-install-dirs.patch
       > patching file CMakeLists.txt
       > patching file cmake/modules/AddLLDB.cmake
       > patching file cmake/modules/LLDBConfig.cmake
       > patching file tools/intel-mpx/CMakeLists.txt
       > patching file cmake/modules/LLDBStandalone.cmake
       > patch unexpectedly ends in middle of line
       > Hunk #1 FAILED at 62.
       > 1 out of 1 hunk FAILED -- saving rejects to file cmake/modules/LLDBStandalone.cmake.rej
       For full logs, run 'nix log /nix/store/9ycf1danp60i2rp2s47gxib0hjrz8aj2-lldb-5.0.2.drv'.
error: builder for '/nix/store/hv040wxn4jk5idnrikwal24b084xi7zq-lldb-6.0.1.drv' failed with exit code 1;
       last 10 log lines:
       > Hunk #1 succeeded at 404 (offset 5 lines).
       > applying patch /nix/store/40yhaj6mc3xgsa2vbmszj02i4k6sijbl-gnu-install-dirs.patch
       > patching file CMakeLists.txt
       > patching file cmake/modules/AddLLDB.cmake
       > patching file cmake/modules/LLDBConfig.cmake
       > patching file tools/intel-features/CMakeLists.txt
       > patching file cmake/modules/LLDBStandalone.cmake
       > patch unexpectedly ends in middle of line
       > Hunk #1 FAILED at 62.
       > 1 out of 1 hunk FAILED -- saving rejects to file cmake/modules/LLDBStandalone.cmake.rej
       For full logs, run 'nix log /nix/store/hv040wxn4jk5idnrikwal24b084xi7zq-lldb-6.0.1.drv'.
error: 5 dependencies of derivation '/nix/store/vvsqdajd0r28hygq1fy3m59vaypfxad4-review-shell.drv' failed to build

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/126091

1 package marked as broken and skipped:
jucipp

5 packages failed to build:
coreclr lldb_5 lldb_6 lldb_7 lldb_8
```

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 126091` at fa865a6b run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/8f2d045a04ab0a28bf8440a75e0a8661">jucipp</a></li>
    <li><a href="https://gist.github.com/9d4570680db48b8e6a32f4571df194e6">lldb_5</a> (llvmPackages_5.lldb)</li>
    <li><a href="https://gist.github.com/2e98fae1231e125a52b46320ef926caf">lldb_7</a> (llvmPackages.lldb ,llvmPackages_7.lldb)</li>
  </ul>
</details>
<details>
  <summary>7 packages skipped due to time constraints:</summary>
  <ul>
    <li>lldb (lldb_11 ,llvmPackages_11.lldb ,llvmPackages_latest.lldb)</li>
    <li>lldb_10 (llvmPackages_10.lldb)</li>
    <li>lldb_12 (llvmPackages_12.lldb)</li>
    <li>lldb_6 (llvmPackages_6.lldb)</li>
    <li>lldb_8 (llvmPackages_8.lldb ,vscode-extensions.llvm-org.lldb-vscode)</li>
    <li>lldb_9 (llvmPackages_9.lldb)</li>
    <li>vscode-extensions.vadimcn.vscode-lldb</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by risicle** [comment]
If you want to ensure this continues working I'd consider adding a very basic test for it. Perhaps through `installCheckPhase` or `passthru.tests`?

**Comment by risicle** [comment]
Also, I wonder if the thing to do would be to wrap the `lldb` executable (pre)fixing the correct `PYTHONPATH`, so a user doesn't have to fully inject the package into their environment to be able to use it properly.

**Comment by tcmal** [comment]
I left the python module in the normal output and just linked to the lib crate, since that seems more in line with what the developers intend, so there's no change to PYTHONPATH.

**Comment by risicle** [comment]
I'm not sure the developers had anything like nix in mind - most developers just assume that all python packages are just going to be thrown together into one big global dumping ground and everything will "just work".

**Comment by oxalica** [comment]
> I left the python module in the normal output and just linked to the lib crate, since that seems more in line with what the developers intend, so there's no change to PYTHONPATH.

I'd expect lldb can at least import its own python module without any configuration, since they are packaged together.

**Comment by Mic92** [comment]
It builds now. How can I test it?

**Comment by Mic92** [comment]
```
$ /nix/store/lbqzyhwdp09vicl8dyj170bi48w01s2r-lldb-11.1.0/bin/lldb
(lldb) script
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'lldb'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_python_interpreter' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'lldb' is not defined
(lldb)
```

**Comment by Mic92** [comment]
This kind of works than: 

```
╭─[~/.cache/nixpkgs-review/pr-126091-1]─s1691654@lairg
╰─ ╰─ % export PYTHONPATH=/nix/store/lbqzyhwdp09vicl8dyj170bi48w01s2r-lldb-11.1.0/lib/python3.8/site-packages/
╭─[~/.cache/nixpkgs-review/pr-126091-1]─s1691654@lairg
╰─ ╰─ % /nix/store/lbqzyhwdp09vicl8dyj170bi48w01s2r-lldb-11.1.0/bin/lldb
(lldb) script
Python Interactive Interpreter. To exit, type 'quit()', 'exit()' or Ctrl-D.
>>>
```

This is what sys.prefix looks like:

```
>>> sys.path
['/nix/store/597kkxgc8xzfh0vxmlvdqg93wj9jvwjc-lldb-11.1.0-lib/lib', '/nix/store/597kkxgc8xzfh0vxmlvdqg93wj9jvwjc-lldb-11.1.0-lib/lib/python3.8/site-packages', '/nix/store/lbqzyhwdp09vicl8dyj170bi48w01s2r-lldb-11.1.0/lib/python3.8/site-packages', '/nix/store/h53s9qb9qw1w6jz7w0xayy9f4824bjpk-python3-3.8.9-env/lib/python38.zip', '/nix/store/h53s9qb9qw1w6jz7w0xayy9f4824bjpk-python3-3.8.9-env/lib/python3.8', '/nix/store/h53s9qb9qw1w6jz7w0xayy9f4824bjpk-python3-3.8.9-env/lib/python3.8/lib-dynload', '/nix/store/h53s9qb9qw1w6jz7w0xayy9f4824bjpk-python3-3.8.9-env/lib/python3.8/site-packages', '.']
```

I think a symlink in the right directory like in `./lib` would help with importing it.

**Review by 7c6f434c — APPROVED** [review]
Looks good

**Comment by 7c6f434c** [comment]
Checking all the versions build would be nice indeed…

**Comment by 7c6f434c** [comment]
@ofborg eval

**Comment by Ericson2314** [comment]
Thanks!

**Pull request merged**
