### PR TITLE
nest-cli: 9.4.2 -> 10.1.17

### PR DESCRIPTION
**Pull request by dotlambda**
## Description of changes
Diff: https://github.com/nestjs/nest-cli/compare/9.4.2...10.1.17

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ehllie** [comment]
This package does not build on `aarch64-darwin` with your PR. Here are the [build logs](https://gist.github.com/ehllie/4190be13da46199ba39c93846935a62a). It's basically the same errors I encountered when originally trying to repackage it. I discussed how it could be fixed with @lilyinstarlight on the unofficial discord server. This is the [start of the discussion](https://discord.com/channels/568306982717751326/797348145805393940/1102999509216264193) if you feel like looking into what we were discussing there. Otherwise the package can be left as failing on that system.

**Comment by dotlambda** [comment]
> This package does not build on `aarch64-darwin` with your PR.

I know. But that's better than vendoring thousands of lines.
Also, you didn't ask upstream to do something about it.

> This is the [start of the discussion](https://discord.com/channels/568306982717751326/797348145805393940/1102999509216264193) if you feel like looking into what we were discussing there.

I won't sign up for Discord just to read a conversation.

**Comment by ehllie** [comment]
> I know. But that's better than vendoring thousands of lines. Also, you didn't ask upstream to do something about it.
It is probably better to not vendor a lockable. I have ended up being a little busy the past couple months and it slipped my mind to request that to get updated upstream.

> I won't sign up for Discord just to read a conversation.
Fair enough. Just left it there in case anyone was interested.

**Comment by dotlambda** [comment]
> just bug upstream

https://github.com/nestjs/nest-cli/pull/2281

**Comment by ehllie** [comment]
The package does build on darwin with your upstream PR merged. We can just update this PR once it gets merged, or make a new one when that happens. I'm fine with either.

**Review by ehllie — APPROVED** [review]

**Review by marsam — APPROVED** [review]

**Pull request merged**
