### PR TITLE
vimPlugins.vim-jsonpath: init at 2020-06-16

### PR DESCRIPTION
**Pull request by austinbutler**
###### Description of changes

- Adds https://github.com/mogelbrod/vim-jsonpath
- Updates vimPlugins
- Fixes `vimPlugins.vim-clap` which is broken on master because of course it is (see https://github.com/NixOS/nixpkgs/pull/162815)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by austinbutler** [comment]
Result of `nixpkgs-review pr 171582` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>vimPlugins.vim-markdown-composer</li>
  </ul>
</details>
<details>
  <summary>58 packages built:</summary>
  <ul>
    <li>spacevim</li>
    <li>vimPlugins.SpaceVim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.auto-session</li>
    <li>vimPlugins.awesome-vim-colorschemes</li>
    <li>vimPlugins.bufexplorer</li>
    <li>vimPlugins.chad</li>
    <li>vimPlugins.coc-nvim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.copilot-vim</li>
    <li>vimPlugins.coq_nvim</li>
    <li>vimPlugins.deol-nvim</li>
    <li>vimPlugins.edge</li>
    <li>vimPlugins.everforest</li>
    <li>vimPlugins.fzf-lsp-nvim</li>
    <li>vimPlugins.gruvbox-material</li>
    <li>vimPlugins.kanagawa-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.lightspeed-nvim</li>
    <li>vimPlugins.lua-dev-nvim</li>
    <li>vimPlugins.luasnip</li>
    <li>vimPlugins.mini-nvim</li>
    <li>vimPlugins.minimap-vim</li>
    <li>vimPlugins.nightfox-nvim</li>
    <li>vimPlugins.null-ls-nvim</li>
    <li>vimPlugins.nvim-autopairs</li>
    <li>vimPlugins.nvim-cmp</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-notify</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-ts-rainbow</li>
    <li>vimPlugins.nvimdev-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.sonokai</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.telescope-zoxide</li>
    <li>vimPlugins.toggleterm-nvim</li>
    <li>vimPlugins.unicode-vim</li>
    <li>vimPlugins.vifm-vim</li>
    <li>vimPlugins.vim-eunuch</li>
    <li>vimPlugins.vim-gitgutter</li>
    <li>vimPlugins.vim-highlightedyank</li>
    <li>vimPlugins.vim-jsonpath</li>
    <li>vimPlugins.vim-matchup</li>
    <li>vimPlugins.vim-plug</li>
    <li>vimPlugins.vim-rails</li>
    <li>vimPlugins.vim-smoothie</li>
    <li>vimPlugins.which-key-nvim</li>
  </ul>
</details>

**Comment by austinbutler** [comment]
Result of `nixpkgs-review pr 171582` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>59 packages built:</summary>
  <ul>
    <li>spacevim</li>
    <li>vimPlugins.SpaceVim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.auto-session</li>
    <li>vimPlugins.awesome-vim-colorschemes</li>
    <li>vimPlugins.bufexplorer</li>
    <li>vimPlugins.chad</li>
    <li>vimPlugins.coc-nvim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.copilot-vim</li>
    <li>vimPlugins.coq_nvim</li>
    <li>vimPlugins.deol-nvim</li>
    <li>vimPlugins.edge</li>
    <li>vimPlugins.everforest</li>
    <li>vimPlugins.fzf-lsp-nvim</li>
    <li>vimPlugins.gruvbox-material</li>
    <li>vimPlugins.kanagawa-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.lightspeed-nvim</li>
    <li>vimPlugins.lua-dev-nvim</li>
    <li>vimPlugins.luasnip</li>
    <li>vimPlugins.mini-nvim</li>
    <li>vimPlugins.minimap-vim</li>
    <li>vimPlugins.nightfox-nvim</li>
    <li>vimPlugins.null-ls-nvim</li>
    <li>vimPlugins.nvim-autopairs</li>
    <li>vimPlugins.nvim-cmp</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-notify</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-ts-rainbow</li>
    <li>vimPlugins.nvimdev-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.sonokai</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.telescope-zoxide</li>
    <li>vimPlugins.toggleterm-nvim</li>
    <li>vimPlugins.unicode-vim</li>
    <li>vimPlugins.vifm-vim</li>
    <li>vimPlugins.vim-eunuch</li>
    <li>vimPlugins.vim-gitgutter</li>
    <li>vimPlugins.vim-highlightedyank</li>
    <li>vimPlugins.vim-jsonpath</li>
    <li>vimPlugins.vim-markdown-composer</li>
    <li>vimPlugins.vim-matchup</li>
    <li>vimPlugins.vim-plug</li>
    <li>vimPlugins.vim-rails</li>
    <li>vimPlugins.vim-smoothie</li>
    <li>vimPlugins.which-key-nvim</li>
  </ul>
</details>

**Comment by austinbutler** [comment]
Ah but of course... vim-clap is broken. Used my other PR to determine that as it's not caught by the update script as-is nor nixpkgs-review: https://github.com/NixOS/nixpkgs/pull/162815.

**Comment by austinbutler** [comment]
Just to be clear all is good now if someone wants to review.

**Comment by AndersonTorres** [comment]
I am not a vimmer. This code does not matter so much to me in practical terms.
I just reorganized it.

**Comment by teto** [comment]
any reason why you pinned the version to v0.5.2 ?

if you drop the general update plugin I can merge.

**Comment by SuperSandro2000** [comment]
> any reason why you pinned the version to v0.5.2 ?
> 
> if you drop the general update commit I can merge.

same question from me, other than that LGTM

**Comment by austinbutler** [comment]
Well most vim plugins don't seem to bother to create/tag releases, but this one does and the update script has the option for a version so that seemed... possibly correct/more in line with how most packaging is done in nixpkgs? Sounds like that's not the case though so I've reverted that.

Also @teto I got some errors relating to `stylish-nvim`, found that `vim-plugin-names` was not updated in https://github.com/NixOS/nixpkgs/pull/172532. Was that intentional?

**Comment by austinbutler** [comment]
Result of `nixpkgs-review pr 171582` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>vimPlugins.markdown-preview-nvim</li>
  </ul>
</details>
<details>
  <summary>155 packages built:</summary>
  <ul>
    <li>spacevim</li>
    <li>vimPlugins.Coqtail</li>
    <li>vimPlugins.LeaderF</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.SpaceVim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.aurora</li>
    <li>vimPlugins.auto-session</li>
    <li>vimPlugins.awesome-vim-colorschemes</li>
    <li>vimPlugins.barbar-nvim</li>
    <li>vimPlugins.bufdelete-nvim</li>
    <li>vimPlugins.bufexplorer</li>
    <li>vimPlugins.bufferline-nvim</li>
    <li>vimPlugins.chad</li>
    <li>vimPlugins.cmp-buffer</li>
    <li>vimPlugins.cmp-tabnine</li>
    <li>vimPlugins.coc-nvim</li>
    <li>vimPlugins.codi-vim</li>
    <li>vimPlugins.comment-nvim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.copilot-vim</li>
    <li>vimPlugins.coq_nvim</li>
    <li>vimPlugins.crates-nvim</li>
    <li>vimPlugins.dart-vim-plugin</li>
    <li>vimPlugins.dashboard-nvim</li>
    <li>vimPlugins.deol-nvim</li>
    <li>vimPlugins.diffview-nvim</li>
    <li>vimPlugins.dressing-nvim</li>
    <li>vimPlugins.edge</li>
    <li>vimPlugins.everforest</li>
    <li>vimPlugins.feline-nvim</li>
    <li>vimPlugins.fidget-nvim</li>
    <li>vimPlugins.formatter-nvim</li>
    <li>vimPlugins.friendly-snippets</li>
    <li>vimPlugins.fzf-lsp-nvim</li>
    <li>vimPlugins.fzf-lua</li>
    <li>vimPlugins.git-blame-nvim</li>
    <li>vimPlugins.gitsigns-nvim</li>
    <li>vimPlugins.glow-nvim</li>
    <li>vimPlugins.gruvbox-material</li>
    <li>vimPlugins.gruvbox-nvim</li>
    <li>vimPlugins.harpoon</li>
    <li>vimPlugins.incsearch-vim</li>
    <li>vimPlugins.indent-blankline-nvim</li>
    <li>vimPlugins.julia-vim</li>
    <li>vimPlugins.kanagawa-nvim</li>
    <li>vimPlugins.lazygit-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.lf-vim</li>
    <li>vimPlugins.lightline-vim</li>
    <li>vimPlugins.lightspeed-nvim</li>
    <li>vimPlugins.lir-nvim</li>
    <li>vimPlugins.litee-filetree-nvim</li>
    <li>vimPlugins.litee-nvim</li>
    <li>vimPlugins.lsp_signature-nvim</li>
    <li>vimPlugins.lspsaga-nvim</li>
    <li>vimPlugins.lua-dev-nvim</li>
    <li>vimPlugins.lualine-nvim</li>
    <li>vimPlugins.luasnip</li>
    <li>vimPlugins.lush-nvim</li>
    <li>vimPlugins.marks-nvim</li>
    <li>vimPlugins.material-nvim</li>
    <li>vimPlugins.mini-nvim</li>
    <li>vimPlugins.minimap-vim</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neorg</li>
    <li>vimPlugins.neovim-ayu</li>
    <li>vimPlugins.nightfox-nvim</li>
    <li>vimPlugins.nord-nvim</li>
    <li>vimPlugins.nterm-nvim</li>
    <li>vimPlugins.nui-nvim</li>
    <li>vimPlugins.null-ls-nvim</li>
    <li>vimPlugins.nvim-autopairs</li>
    <li>vimPlugins.nvim-cmp</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-dap-ui</li>
    <li>vimPlugins.nvim-gdb</li>
    <li>vimPlugins.nvim-highlite</li>
    <li>vimPlugins.nvim-jdtls</li>
    <li>vimPlugins.nvim-lint</li>
    <li>vimPlugins.nvim-lsp-ts-utils</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-metals</li>
    <li>vimPlugins.nvim-neoclip-lua</li>
    <li>vimPlugins.nvim-notify</li>
    <li>vimPlugins.nvim-scrollview</li>
    <li>vimPlugins.nvim-solarized-lua</li>
    <li>vimPlugins.nvim-spectre</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-context</li>
    <li>vimPlugins.nvim-ts-rainbow</li>
    <li>vimPlugins.nvimdev-nvim</li>
    <li>vimPlugins.octo-nvim</li>
    <li>vimPlugins.onedarkpro-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.plenary-nvim</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.rest-nvim</li>
    <li>vimPlugins.rnvimr</li>
    <li>vimPlugins.rose-pine</li>
    <li>vimPlugins.rust-tools-nvim</li>
    <li>vimPlugins.slimv</li>
    <li>vimPlugins.sonokai</li>
    <li>vimPlugins.space-vim</li>
    <li>vimPlugins.splitjoin-vim</li>
    <li>vimPlugins.stabilize-nvim</li>
    <li>vimPlugins.stylish-nvim</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-file-browser-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.telescope-zoxide</li>
    <li>vimPlugins.toggleterm-nvim</li>
    <li>vimPlugins.trouble-nvim</li>
    <li>vimPlugins.unicode-vim</li>
    <li>vimPlugins.urlview-nvim</li>
    <li>vimPlugins.vifm-vim</li>
    <li>vimPlugins.vim-airline</li>
    <li>vimPlugins.vim-autoformat</li>
    <li>vimPlugins.vim-clap</li>
    <li>vimPlugins.vim-eunuch</li>
    <li>vimPlugins.vim-floaterm</li>
    <li>vimPlugins.vim-fugitive</li>
    <li>vimPlugins.vim-gitgutter</li>
    <li>vimPlugins.vim-glsl</li>
    <li>vimPlugins.vim-gutentags</li>
    <li>vimPlugins.vim-hardtime</li>
    <li>vimPlugins.vim-highlightedyank</li>
    <li>vimPlugins.vim-jsonpath</li>
    <li>vimPlugins.vim-localvimrc</li>
    <li>vimPlugins.vim-markdown</li>
    <li>vimPlugins.vim-markdown-composer</li>
    <li>vimPlugins.vim-matchup</li>
    <li>vimPlugins.vim-plug</li>
    <li>vimPlugins.vim-projectionist</li>
    <li>vimPlugins.vim-quickrun</li>
    <li>vimPlugins.vim-rails</li>
    <li>vimPlugins.vim-rhubarb</li>
    <li>vimPlugins.vim-slime</li>
    <li>vimPlugins.vim-smoothie</li>
    <li>vimPlugins.vim-snippets</li>
    <li>vimPlugins.vim-tpipeline</li>
    <li>vimPlugins.vim-ultest</li>
    <li>vimPlugins.vim-visual-multi</li>
    <li>vimPlugins.vimtex</li>
    <li>vimPlugins.which-key-nvim</li>
    <li>vimPlugins.wildfire-vim</li>
    <li>vimPlugins.zoxide-vim</li>
  </ul>
</details>

**Comment by austinbutler** [comment]
Result of `nixpkgs-review pr 171582` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>155 packages built:</summary>
  <ul>
    <li>spacevim</li>
    <li>vimPlugins.Coqtail</li>
    <li>vimPlugins.LeaderF</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.SpaceVim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.aurora</li>
    <li>vimPlugins.auto-session</li>
    <li>vimPlugins.awesome-vim-colorschemes</li>
    <li>vimPlugins.barbar-nvim</li>
    <li>vimPlugins.bufdelete-nvim</li>
    <li>vimPlugins.bufexplorer</li>
    <li>vimPlugins.bufferline-nvim</li>
    <li>vimPlugins.chad</li>
    <li>vimPlugins.cmp-buffer</li>
    <li>vimPlugins.cmp-tabnine</li>
    <li>vimPlugins.coc-nvim</li>
    <li>vimPlugins.codi-vim</li>
    <li>vimPlugins.comment-nvim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.copilot-vim</li>
    <li>vimPlugins.coq_nvim</li>
    <li>vimPlugins.crates-nvim</li>
    <li>vimPlugins.dart-vim-plugin</li>
    <li>vimPlugins.dashboard-nvim</li>
    <li>vimPlugins.deol-nvim</li>
    <li>vimPlugins.diffview-nvim</li>
    <li>vimPlugins.dressing-nvim</li>
    <li>vimPlugins.edge</li>
    <li>vimPlugins.everforest</li>
    <li>vimPlugins.feline-nvim</li>
    <li>vimPlugins.fidget-nvim</li>
    <li>vimPlugins.formatter-nvim</li>
    <li>vimPlugins.friendly-snippets</li>
    <li>vimPlugins.fzf-lsp-nvim</li>
    <li>vimPlugins.fzf-lua</li>
    <li>vimPlugins.git-blame-nvim</li>
    <li>vimPlugins.gitsigns-nvim</li>
    <li>vimPlugins.glow-nvim</li>
    <li>vimPlugins.gruvbox-material</li>
    <li>vimPlugins.gruvbox-nvim</li>
    <li>vimPlugins.harpoon</li>
    <li>vimPlugins.incsearch-vim</li>
    <li>vimPlugins.indent-blankline-nvim</li>
    <li>vimPlugins.julia-vim</li>
    <li>vimPlugins.kanagawa-nvim</li>
    <li>vimPlugins.lazygit-nvim</li>
    <li>vimPlugins.lean-nvim</li>
    <li>vimPlugins.lf-vim</li>
    <li>vimPlugins.lightline-vim</li>
    <li>vimPlugins.lightspeed-nvim</li>
    <li>vimPlugins.lir-nvim</li>
    <li>vimPlugins.litee-filetree-nvim</li>
    <li>vimPlugins.litee-nvim</li>
    <li>vimPlugins.lsp_signature-nvim</li>
    <li>vimPlugins.lspsaga-nvim</li>
    <li>vimPlugins.lua-dev-nvim</li>
    <li>vimPlugins.lualine-nvim</li>
    <li>vimPlugins.luasnip</li>
    <li>vimPlugins.lush-nvim</li>
    <li>vimPlugins.marks-nvim</li>
    <li>vimPlugins.material-nvim</li>
    <li>vimPlugins.mini-nvim</li>
    <li>vimPlugins.minimap-vim</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neorg</li>
    <li>vimPlugins.neovim-ayu</li>
    <li>vimPlugins.nightfox-nvim</li>
    <li>vimPlugins.nord-nvim</li>
    <li>vimPlugins.nterm-nvim</li>
    <li>vimPlugins.nui-nvim</li>
    <li>vimPlugins.null-ls-nvim</li>
    <li>vimPlugins.nvim-autopairs</li>
    <li>vimPlugins.nvim-cmp</li>
    <li>vimPlugins.nvim-dap</li>
    <li>vimPlugins.nvim-dap-ui</li>
    <li>vimPlugins.nvim-gdb</li>
    <li>vimPlugins.nvim-highlite</li>
    <li>vimPlugins.nvim-jdtls</li>
    <li>vimPlugins.nvim-lint</li>
    <li>vimPlugins.nvim-lsp-ts-utils</li>
    <li>vimPlugins.nvim-lspconfig</li>
    <li>vimPlugins.nvim-metals</li>
    <li>vimPlugins.nvim-neoclip-lua</li>
    <li>vimPlugins.nvim-notify</li>
    <li>vimPlugins.nvim-scrollview</li>
    <li>vimPlugins.nvim-solarized-lua</li>
    <li>vimPlugins.nvim-spectre</li>
    <li>vimPlugins.nvim-tree-lua</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.nvim-treesitter-context</li>
    <li>vimPlugins.nvim-ts-rainbow</li>
    <li>vimPlugins.nvimdev-nvim</li>
    <li>vimPlugins.octo-nvim</li>
    <li>vimPlugins.onedarkpro-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.plenary-nvim</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.rest-nvim</li>
    <li>vimPlugins.rnvimr</li>
    <li>vimPlugins.rose-pine</li>
    <li>vimPlugins.rust-tools-nvim</li>
    <li>vimPlugins.slimv</li>
    <li>vimPlugins.sonokai</li>
    <li>vimPlugins.space-vim</li>
    <li>vimPlugins.splitjoin-vim</li>
    <li>vimPlugins.stabilize-nvim</li>
    <li>vimPlugins.stylish-nvim</li>
    <li>vimPlugins.telescope-cheat-nvim</li>
    <li>vimPlugins.telescope-file-browser-nvim</li>
    <li>vimPlugins.telescope-frecency-nvim</li>
    <li>vimPlugins.telescope-fzf-native-nvim</li>
    <li>vimPlugins.telescope-fzf-writer-nvim</li>
    <li>vimPlugins.telescope-fzy-native-nvim</li>
    <li>vimPlugins.telescope-nvim</li>
    <li>vimPlugins.telescope-symbols-nvim</li>
    <li>vimPlugins.telescope-z-nvim</li>
    <li>vimPlugins.telescope-zoxide</li>
    <li>vimPlugins.toggleterm-nvim</li>
    <li>vimPlugins.trouble-nvim</li>
    <li>vimPlugins.unicode-vim</li>
    <li>vimPlugins.urlview-nvim</li>
    <li>vimPlugins.vifm-vim</li>
    <li>vimPlugins.vim-airline</li>
    <li>vimPlugins.vim-autoformat</li>
    <li>vimPlugins.vim-clap</li>
    <li>vimPlugins.vim-eunuch</li>
    <li>vimPlugins.vim-floaterm</li>
    <li>vimPlugins.vim-fugitive</li>
    <li>vimPlugins.vim-gitgutter</li>
    <li>vimPlugins.vim-glsl</li>
    <li>vimPlugins.vim-gutentags</li>
    <li>vimPlugins.vim-hardtime</li>
    <li>vimPlugins.vim-highlightedyank</li>
    <li>vimPlugins.vim-jsonpath</li>
    <li>vimPlugins.vim-localvimrc</li>
    <li>vimPlugins.vim-markdown</li>
    <li>vimPlugins.vim-markdown-composer</li>
    <li>vimPlugins.vim-matchup</li>
    <li>vimPlugins.vim-plug</li>
    <li>vimPlugins.vim-projectionist</li>
    <li>vimPlugins.vim-quickrun</li>
    <li>vimPlugins.vim-rails</li>
    <li>vimPlugins.vim-rhubarb</li>
    <li>vimPlugins.vim-slime</li>
    <li>vimPlugins.vim-smoothie</li>
    <li>vimPlugins.vim-snippets</li>
    <li>vimPlugins.vim-tpipeline</li>
    <li>vimPlugins.vim-ultest</li>
    <li>vimPlugins.vim-visual-multi</li>
    <li>vimPlugins.vimtex</li>
    <li>vimPlugins.which-key-nvim</li>
    <li>vimPlugins.wildfire-vim</li>
    <li>vimPlugins.zoxide-vim</li>
  </ul>
</details>

**Comment by austinbutler** [comment]
Reverted updated of `markdown-preview-nvim` as that's a whole can of NPM worms...

**Comment by teto** [comment]
thanks for fixing stylish and vim-clap

**Pull request merged**
