### PR TITLE
openimagedenoise: fix cmake tbb discovery

### LINKED ISSUE #216580: Build failure: `openimagedenoise`
### Steps To Reproduce

1. build `openimagedenoise`

### Build log

```console
$ nix-channel --list
nixos https://nixos.org/channels/nixos-unstable

$ nix log /nix/store/2ay0ynwd7639msidi0f8xjbx518l7k4m-openimagedenoise-1.4.3.drv
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/gjqcn7495q4sqd9cm6lg3fyy936dbsa7-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
fixing cmake files...
cmake flags: -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DCMAKE_INSTALL_LOCALEDIR=/nix/store/4p56q>
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /nix/store/l0fvy72hpfdpjjs3dk4112f57x7r3dlm-gcc-wrapper-12.2.0/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /nix/store/l0fvy72hpfdpjjs3dk4112f57x7r3dlm-gcc-wrapper-12.2.0/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /nix/store/0pyymzxf7n0fzpaqnvwv92ab72v3jq8d-python3-3.10.9/bin/python (found version "3.10.9")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Looking for TBB components tbb; ()
-- Found TBB version 2020.3 at /nix/store/6y5ms2chn50ksw6fbsig8jm62fimqspr-tbb-2020.3-dev
CMake Error at cmake/FindTBB.cmake:80 (message):
  Cannot find required components: ;tbb
Call Stack (most recent call first):
  cmake/FindTBB.cmake:487 (rk_tbb_error)
  CMakeLists.txt:73 (find_package)


-- Configuring incomplete, errors occurred!
See also "/build/source/build/CMakeFiles/CMakeOutput.log".
```

### Additional context

Breaks `blender` since it depends on `openimagedenoise`

### Notify maintainers

@LeshaInc (`openimagedenoise`); @thoughtpolice, @dizfer (`tbb`)

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.90, NixOS, 23.05 (Stoat), 23.05pre454549.545c7a31e5d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(USERNAME): `"home-manager"`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by davidak**
###### Description of changes

Fixes https://github.com/NixOS/nixpkgs/issues/216580

Alternative: https://github.com/NixOS/nixpkgs/pull/216842, https://github.com/NixOS/nixpkgs/pull/216844

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 216853` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>blender</li>
    <li>blender-hip</li>
    <li>openimagedenoise</li>
    <li>openimagedenoise_1_2_x</li>
    <li>python310Packages.bpycv</li>
  </ul>
</details>

**Comment by davidak** [comment]
@MultisampledNight what am i doing wrong?

**Comment by MultisampledNight** [comment]
I'm not sure, tbh. Are you running the 22.11 or the unstable channel?

**Comment by davidak** [comment]
My system runs NixOS 22.11.2568.c43f676c938 with Nix 2.11.1.

**Comment by davidak** [comment]
For some reason i used `TBB_ROOT_DIR` instead of `DTBB_ROOT`.

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 216853` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>blender</li>
    <li>blender-hip</li>
    <li>openimagedenoise_1_2_x</li>
    <li>python310Packages.bpycv</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>openimagedenoise</li>
  </ul>
</details>

**Comment by davidak** [comment]
Closing in favor of https://github.com/NixOS/nixpkgs/pull/216844.

**Pull request closed without merging**
