### PR TITLE
Kernels 2021-06-28

### PR DESCRIPTION
**Pull request by ymatsiuk**
###### Motivation for this change
recent kernels versions

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ymatsiuk** [comment]
@ofborg test kernel-latest kernel-lts latestKernel.login latestKernel.hardened

**Comment by fabianhjr** [comment]
Can't build, investigating:

```
builder for '/nix/store/r9ymc8js0k4789qz2f4km2jc2n4qi6r9-linux-config-5.12.13.drv' failed with exit code 1
```

**Comment by fabianhjr** [comment]
Seems like a patch became redundant:

```
applying patch /nix/store/p3pvbsyh6bh318jynsaxk95d3bas7af3-rtnetlink_fix_regression_in_bridge_vlan_configuration.patch
patching file net/core/rtnetlink.c
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file net/core/rtnetlink.c.rej
```

**Comment by fabianhjr** [comment]
Can build with the following change:

```
diff --git a/pkgs/os-specific/linux/kernel/patches.nix b/pkgs/os-specific/linux/kernel/patches.nix
index 48dd9b38d9b..f41cedca0f6 100644
--- a/pkgs/os-specific/linux/kernel/patches.nix
+++ b/pkgs/os-specific/linux/kernel/patches.nix
@@ -102,13 +102,4 @@
     name = "mac_nvme_t2";
     patch = ./mac-nvme-t2.patch;
   };
-
-  rtnetlink_fix_regression_in_bridge_vlan_configuration = rec {
-    name = "rtnetlink_fix_regression_in_bridge_vlan_configuration";
-    patch = fetchpatch {
-      name = name + ".patch";
-      url = "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/patch/?id=d2e381c4963663bca6f30c3b996fa4dbafe8fcb5";
-      sha256 = "0ragdi13yh5ypp9x49vrdjqx8ddh7sq7i1qjp8fyrbk3n0jdaac3";
-    };
-  };
 }
```

**Review by fabianhjr — CHANGES_REQUESTED** [review]
Patch `rtnetlink_fix_regression_in_bridge_vlan_configuration` should be removed

**Comment by fabianhjr** [comment]
Have to check the changelog of 5.4, 5.10 for the rtnetlink revert.

```
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -20739,11 +20739,10 @@ in
   linux_5_4 = callPackage ../os-specific/linux/kernel/linux-5.4.nix {
     kernelPatches = [
       kernelPatches.bridge_stp_helper
       kernelPatches.request_key_helper
       kernelPatches.rtl8761b_support
-      kernelPatches.rtnetlink_fix_regression_in_bridge_vlan_configuration
     ];
   };
 
   linux-rt_5_4 = callPackage ../os-specific/linux/kernel/linux-rt-5.4.nix {
     kernelPatches = [
@@ -20754,19 +20753,17 @@ in
 
   linux_5_10 = callPackage ../os-specific/linux/kernel/linux-5.10.nix {
     kernelPatches = [
       kernelPatches.bridge_stp_helper
       kernelPatches.request_key_helper
-      kernelPatches.rtnetlink_fix_regression_in_bridge_vlan_configuration
     ];
   };
 
   linux_5_12 = callPackage ../os-specific/linux/kernel/linux-5.12.nix {
     kernelPatches = [
       kernelPatches.bridge_stp_helper
       kernelPatches.request_key_helper
-      kernelPatches.rtnetlink_fix_regression_in_bridge_vlan_configuration
     ];
   };
```

**Comment by fabianhjr** [comment]
Present on 5.4 and 5.10 as commits commit 23f3d2779dd685db6189eca303543f56ff5e3c68 and c8f1437c0145e2750fb9543c552ccc5a47636491 respectively, patch can be completely removed.

**Comment by TredwellGit** [comment]
It was fixed upstream. Use `git revert 24a08441d52480cf3332a100e24fdf9b83a8351a`.

@fortuneteller2k: https://github.com/NixOS/nixpkgs/pull/128006 needs to be merged before this.

**Comment by TredwellGit** [comment]
The title of the pull request is using a backwards date format.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 128538` at a7343b09 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>78 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/1cc700c5c6fbcf2bd04c7f3472d010f1">bumblebee</a></li>
    <li><a href="https://gist.github.com/d70f1f4ee7d2ac29b2dfffef9dc22c70">crosvm</a></li>
    <li><a href="https://gist.github.com/72a64a3f8f5b84a1356f24349d9c88c3">geekbench</a></li>
    <li><a href="https://gist.github.com/d92b2a77b3578c026050d4cfb631b336">linux</a> (linuxPackages.kernel ,linuxPackages_5_10.kernel ,linux_5_10)</li>
    <li><a href="https://gist.github.com/0477cf6e96130de8188d58a62213c6f9">linuxPackages.acpi_call</a> (linuxPackages_5_10.acpi_call)</li>
    <li><a href="https://gist.github.com/d8cf5c9c14f91b4a81f1183c979c4294">linuxPackages.akvcam</a> (linuxPackages_5_10.akvcam)</li>
    <li><a href="https://gist.github.com/4c80d0898fbdc8959d16fe81e4686eb5">linuxPackages.amdgpu-pro</a> (linuxPackages_5_10.amdgpu-pro)</li>
    <li><a href="https://gist.github.com/b18e8f99e277ceaa426725b65228c7b5">linuxPackages.anbox</a> (linuxPackages_5_10.anbox)</li>
    <li><a href="https://gist.github.com/a9b4f8f30f1184550d9d095116bc38ea">linuxPackages.apfs</a> (linuxPackages_5_10.apfs)</li>
    <li><a href="https://gist.github.com/e3198cb7217de6c7ec9dbc357b1b4ae5">linuxPackages.asus-wmi-sensors</a> (linuxPackages_5_10.asus-wmi-sensors)</li>
    <li><a href="https://gist.github.com/fa07901c91f0d6527550cff1ec35a693">linuxPackages.batman_adv</a> (linuxPackages_5_10.batman_adv)</li>
    <li><a href="https://gist.github.com/089e9b102d1f4536e60228c4b177c248">linuxPackages.bbswitch</a> (linuxPackages_5_10.bbswitch)</li>
    <li><a href="https://gist.github.com/60972263762d64f73b9305749d82fcba">linuxPackages.bcc</a> (linuxPackages_5_10.bcc)</li>
    <li><a href="https://gist.github.com/4b66ff1d314cbff71a49cfd1cfddd9a0">linuxPackages.bpftrace</a> (linuxPackages_5_10.bpftrace)</li>
    <li><a href="https://gist.github.com/b8c2406ce3095d5866a406af6a025f9c">linuxPackages.broadcom_sta</a> (linuxPackages_5_10.broadcom_sta)</li>
    <li><a href="https://gist.github.com/e6097dda15fa994495df9db192aadf23">linuxPackages.can-isotp</a> (linuxPackages_5_10.can-isotp)</li>
    <li><a href="https://gist.github.com/1ded8fca3c3f4650e6c982d4d5e27d6b">linuxPackages.chipsec</a> (linuxPackages_5_10.chipsec)</li>
    <li><a href="https://gist.github.com/18ff6ea179f8a1d9481eb59b12de2500">linuxPackages.cryptodev</a> (linuxPackages_5_10.cryptodev)</li>
    <li><a href="https://gist.github.com/e91b26c4d0ee87bceae46a6593549e1d">linuxPackages.ddcci-driver</a> (linuxPackages_5_10.ddcci-driver)</li>
    <li><a href="https://gist.github.com/1427496053001f32fbfd1686bbc083a8">linuxPackages.digimend</a> (linuxPackages_5_10.digimend)</li>
    <li><a href="https://gist.github.com/2cac296983edf59ed37145ea7504f948">linuxPackages.ena</a> (linuxPackages_5_10.ena)</li>
    <li><a href="https://gist.github.com/8bd1f1396938d95ae36ffe7af4a982b3">linuxPackages.evdi</a> (linuxPackages_5_10.evdi)</li>
    <li><a href="https://gist.github.com/4f3b0fc1d6274b78c8ae18da94cb457c">linuxPackages.facetimehd</a> (linuxPackages_5_10.facetimehd)</li>
    <li><a href="https://gist.github.com/9427960e7a681a84a8416d3271940feb">linuxPackages.fwts-efi-runtime</a> (linuxPackages_5_10.fwts-efi-runtime)</li>
    <li><a href="https://gist.github.com/9b2c4f2b71e6251c5f02ec2e75562156">linuxPackages.gcadapter-oc-kmod</a> (linuxPackages_5_10.gcadapter-oc-kmod)</li>
    <li><a href="https://gist.github.com/5ad38a7e2d2229d8437f3bda495485be">linuxPackages.hid-nintendo</a> (linuxPackages_5_10.hid-nintendo)</li>
    <li><a href="https://gist.github.com/ff09b3611f40b56df68e7800dc6f9535">linuxPackages.isgx</a> (linuxPackages_5_10.isgx)</li>
    <li><a href="https://gist.github.com/c05375893b19e1c9374d2b0e173f8705">linuxPackages.it87</a> (linuxPackages_5_10.it87)</li>
    <li><a href="https://gist.github.com/da2db427ac9af43d2ace7ac9ce421a5e">linuxPackages.ixgbevf</a> (linuxPackages_5_10.ixgbevf)</li>
    <li><a href="https://gist.github.com/6bd3c4ec8b70681a1cd26b88e77f402e">linuxPackages.jool</a> (linuxPackages_5_10.jool)</li>
    <li><a href="https://gist.github.com/d4b2bc3d4790d1363df6d83f83376193">linuxPackages.lttng-modules</a> (linuxPackages_5_10.lttng-modules)</li>
    <li><a href="https://gist.github.com/794966aeb4e39e83b16b4834fb13f6c3">linuxPackages.mba6x_bl</a> (linuxPackages_5_10.mba6x_bl)</li>
    <li><a href="https://gist.github.com/ede00b42b318d4dc68b6cfcd54e98b1e">linuxPackages.mbp2018-bridge-drv</a> (linuxPackages_5_10.mbp2018-bridge-drv)</li>
    <li><a href="https://gist.github.com/b6232d811106da5b607534798b3661d2">linuxPackages.mwprocapture</a> (linuxPackages_5_10.mwprocapture)</li>
    <li><a href="https://gist.github.com/6868d1ca53f7b206c4197bb9c3adf0cd">linuxPackages.mxu11x0</a> (linuxPackages_5_10.mxu11x0)</li>
    <li><a href="https://gist.github.com/075caecacd3924d9bd802258b24a62e6">linuxPackages.ndiswrapper</a> (linuxPackages_5_10.ndiswrapper)</li>
    <li><a href="https://gist.github.com/d16dc4a6ae5b96dfd130c544d20d6348">linuxPackages.netatop</a> (linuxPackages_5_10.netatop)</li>
    <li><a href="https://gist.github.com/1df94e7e77d65d7733a992288c1f9452">linuxPackages.nvidia_x11</a> (linuxPackages_5_10.nvidia_x11)</li>
    <li><a href="https://gist.github.com/7b11074d72516adcb565796e6af11683">linuxPackages.nvidia_x11_beta</a> (linuxPackages_5_10.nvidia_x11_beta)</li>
    <li><a href="https://gist.github.com/998ffd0843ab409bc432ec474f313259">linuxPackages.nvidia_x11_legacy340</a> (linuxPackages_5_10.nvidia_x11_legacy340)</li>
    <li><a href="https://gist.github.com/09468ca09c49802f0630a7e3d5b78db4">linuxPackages.nvidia_x11_legacy390</a> (linuxPackages_5_10.nvidia_x11_legacy390)</li>
    <li><a href="https://gist.github.com/7b6ec44e5611092c71d6bb9f3822ee44">linuxPackages.nvidia_x11_vulkan_beta</a> (linuxPackages_5_10.nvidia_x11_vulkan_beta)</li>
    <li><a href="https://gist.github.com/4aa507fa203d48a38e16ee911436fd91">linuxPackages.nvidiabl</a> (linuxPackages_5_10.nvidiabl)</li>
    <li><a href="https://gist.github.com/ffc01d6540c75b3a4b045bd0c0f9c2b1">linuxPackages.oci-seccomp-bpf-hook</a> (linuxPackages_5_10.oci-seccomp-bpf-hook)</li>
    <li><a href="https://gist.github.com/963dcee61ab4fbd16f3b8a085e3674c5">linuxPackages.openrazer</a> (linuxPackages_5_10.openrazer)</li>
    <li><a href="https://gist.github.com/9ae40735e94a39ed479cde7afaf4e8da">linuxPackages.phc-intel</a> (linuxPackages_5_10.phc-intel)</li>
    <li><a href="https://gist.github.com/676183e7af6c6c2be74114e5179c7963">linuxPackages.r8125</a> (linuxPackages_5_10.r8125)</li>
    <li><a href="https://gist.github.com/7a9236ec87a266dcfdfe5dfab96b1305">linuxPackages.r8168</a> (linuxPackages_5_10.r8168)</li>
    <li><a href="https://gist.github.com/70413f44bf894a2df2994438a1b8d7fa">linuxPackages.rtl8188eus-aircrack</a> (linuxPackages_5_10.rtl8188eus-aircrack)</li>
    <li><a href="https://gist.github.com/f17ad864293081ecb19a292d62c85d0d">linuxPackages.rtl8192eu</a> (linuxPackages_5_10.rtl8192eu)</li>
    <li><a href="https://gist.github.com/c5b88aa637a7de299eb2d41e56d5cbd0">linuxPackages.rtl8723bs</a> (linuxPackages_5_10.rtl8723bs)</li>
    <li><a href="https://gist.github.com/8e4b4c3fc1972e966d4f793aedb2f49a">linuxPackages.rtl8812au</a> (linuxPackages_5_10.rtl8812au)</li>
    <li><a href="https://gist.github.com/23851431ebea2f5cda109de58fefdcdd">linuxPackages.rtl8814au</a> (linuxPackages_5_10.rtl8814au)</li>
    <li><a href="https://gist.github.com/3f7b362e913c7ba1216120caecea9057">linuxPackages.rtl8821au</a> (linuxPackages_5_10.rtl8821au)</li>
    <li><a href="https://gist.github.com/e5dda89412b9e04dbc227173c071d43b">linuxPackages.rtl8821ce</a> (linuxPackages_5_10.rtl8821ce)</li>
    <li><a href="https://gist.github.com/dfdd666b972049133c30065e539b8c3b">linuxPackages.rtl8821cu</a> (linuxPackages_5_10.rtl8821cu)</li>
    <li><a href="https://gist.github.com/bafe7a52b440d58490a06248f9777ada">linuxPackages.rtl88xxau-aircrack</a> (linuxPackages_5_10.rtl88xxau-aircrack)</li>
    <li><a href="https://gist.github.com/2a330616d712764b980c21865f6503b6">linuxPackages.rtw88</a> (linuxPackages.rtlwifi_new ,linuxPackages_5_10.rtlwifi_new ,linuxPackages_5_10.rtw88)</li>
    <li><a href="https://gist.github.com/e210c4bf189202f476c1035756c2d62a">linuxPackages.sch_cake</a> (linuxPackages_5_10.sch_cake)</li>
    <li><a href="https://gist.github.com/5a6430c01fe7ccefd8eebfcf1761f627">linuxPackages.sysdig</a> (linuxPackages_5_10.sysdig)</li>
    <li><a href="https://gist.github.com/3574ca09f99830aa612f4a09ba1e36e2">linuxPackages.system76</a> (linuxPackages_5_10.system76)</li>
    <li><a href="https://gist.github.com/cc66b309b09cf1e6eeaa7f3baa793d63">linuxPackages.system76-acpi</a> (linuxPackages_5_10.system76-acpi)</li>
    <li><a href="https://gist.github.com/be1416cc19adfc5475044f4b7c508fa2">linuxPackages.system76-io</a> (linuxPackages_5_10.system76-io)</li>
    <li><a href="https://gist.github.com/98f2edc600dd1d83eb3eb817e37a967e">linuxPackages.systemtap</a> (linuxPackages_5_10.systemtap)</li>
    <li><a href="https://gist.github.com/1b750fce14cebd3bf0010f66b1b111ce">linuxPackages.tbs</a> (linuxPackages_5_10.tbs)</li>
    <li><a href="https://gist.github.com/253c5359e28d22f88979a41afccad308">linuxPackages.tp_smapi</a> (linuxPackages_5_10.tp_smapi)</li>
    <li><a href="https://gist.github.com/b0d21e1119b01eee9e5122a05ca16ef6">linuxPackages.tuxedo-keyboard</a> (linuxPackages_5_10.tuxedo-keyboard)</li>
    <li><a href="https://gist.github.com/10fbab2035b4439dc5241c413b365123">linuxPackages.v4l2loopback</a> (linuxPackages_5_10.v4l2loopback)</li>
    <li><a href="https://gist.github.com/3fe2043d367b7fec121613b4d472718a">linuxPackages.v86d</a> (linuxPackages_5_10.v86d)</li>
    <li><a href="https://gist.github.com/8234f8e8874c5b5e2eb9d05053c90460">linuxPackages.veikk-linux-driver</a> (linuxPackages_5_10.veikk-linux-driver)</li>
    <li><a href="https://gist.github.com/63863855f18c33135f76b61af152e7bb">linuxPackages.vendor-reset</a> (linuxPackages_5_10.vendor-reset)</li>
    <li><a href="https://gist.github.com/6c0b7d8d8beebfeae83ee8106fb4ef52">linuxPackages.vhba</a> (linuxPackages_5_10.vhba)</li>
    <li><a href="https://gist.github.com/6019a25a44f08aee8ae3bc44d058c2d3">linuxPackages.virtualbox</a> (linuxPackages_5_10.virtualbox)</li>
    <li><a href="https://gist.github.com/3eb99abc043565c7548700e3f7a76d47">linuxPackages.virtualboxGuestAdditions</a> (linuxPackages_5_10.virtualboxGuestAdditions)</li>
    <li><a href="https://gist.github.com/b014174bd80138c14e33ca355cf16607">linuxPackages.xpadneo</a> (linuxPackages_5_10.xpadneo)</li>
    <li><a href="https://gist.github.com/5e39e963973ab81b36c7b383eb1e9815">linuxPackages.zenpower</a> (linuxPackages_5_10.zenpower)</li>
    <li><a href="https://gist.github.com/9c41e068542b9d69db18d1eaaa28da5b">linuxPackages.zfs</a> (linuxPackages.zfsStable ,linuxPackages_5_10.zfs ,linuxPackages_5_10.zfsStable)</li>
    <li><a href="https://gist.github.com/5ed1473a761c06ea5150a07313f69493">linuxPackages.zfsUnstable</a> (linuxPackages_5_10.zfsUnstable)</li>
  </ul>
</details>
<details>
  <summary>537 packages skipped due to time constraints:</summary>
  <ul>
    <li>bpftools</li>
    <li>cargo-flamegraph</li>
    <li>displaylink</li>
    <li>freefall</li>
    <li>gnome.gnome-applets</li>
    <li>gpio-utils</li>
    <li>gwe</li>
    <li>linux-libre (linuxPackages-libre.kernel)</li>
    <li>linuxPackages-libre.acpi_call</li>
    <li>linuxPackages-libre.akvcam</li>
    <li>...</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by ymatsiuk** [comment]
@ofborg test kernel-latest kernel-lts latestKernel.login latestKernel.hardened

**Review by TredwellGit — APPROVED** [review]

**Review by fabianhjr — APPROVED** [review]
LGTM

**Review by TredwellGit — CHANGES_REQUESTED** [review]
There is a major AMD GPU power usage issue in 5.12.13: https://bugzilla.kernel.org/show_bug.cgi?id=213561

**Comment by ymatsiuk** [comment]
@TredwellGit not sure what to do there, shall I add this patch? This is not an approved patch or am I missing something?

**Comment by TredwellGit** [comment]
5.12.14, which was released today, includes the fix.

**Comment by fabianhjr** [comment]
@ymatsiuk, I think there are three options:

1. get the revert commits from v5.12.14 and apply them as patches:

```
commit 07553a027bf9b166877b9b700749d092b8f7e0e0
Author: Yifan Zhang <yifan1.zhang@amd.com>
Date:   Sat Jun 19 11:39:43 2021 +0800

    Revert "drm/amdgpu/gfx10: enlarge CP_MEC_DOORBELL_RANGE_UPPER to cover full doorbell."
    
    commit baacf52a473b24e10322b67757ddb92ab8d86717 upstream.
    
    This reverts commit 1c0b0efd148d5b24c4932ddb3fa03c8edd6097b3.
    
    Reason for revert: Side effect of enlarging CP_MEC_DOORBELL_RANGE may
    cause some APUs fail to enter gfxoff in certain user cases.
    
    Signed-off-by: Yifan Zhang <yifan1.zhang@amd.com>
    Acked-by: Alex Deucher <alexander.deucher@amd.com>
    Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
    Cc: stable@vger.kernel.org
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

commit c798a995cb39fe11fb71681306e4c74c348ff7a7
Author: Yifan Zhang <yifan1.zhang@amd.com>
Date:   Sat Jun 19 11:40:54 2021 +0800

    Revert "drm/amdgpu/gfx9: fix the doorbell missing when in CGPG issue."
    
    commit ee5468b9f1d3bf48082eed351dace14598e8ca39 upstream.
    
    This reverts commit 4cbbe34807938e6e494e535a68d5ff64edac3f20.
    
    Reason for revert: side effect of enlarging CP_MEC_DOORBELL_RANGE may
    cause some APUs fail to enter gfxoff in certain user cases.
    
    Signed-off-by: Yifan Zhang <yifan1.zhang@amd.com>
    Acked-by: Alex Deucher <alexander.deucher@amd.com>
    Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
    Cc: stable@vger.kernel.org
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
    ```
    
    2. Wait for 5.12.14
    
    2b. Remove 5.12.13 changes and commit the other version updates

**Comment by TredwellGit** [comment]
We really need to separate the hardened patches. Ironically, they block security updates making everything less secure.

**Comment by ymatsiuk** [comment]
Hardened patches are always a week or even more late. I like the idea of separating those, this way we can keep at least upstream kernel up to date and minimize delays. It doesn't look good to me to cherry-pick patches from different releases and mix those, as it creates confusion for the next person who is going to submit a PR with update. Ideally I'd love to have a strategy that allows fast version updates to keep up at least with upstream.

**Comment by fabianhjr** [comment]
> It doesn't look good to me to cherry-pick patches from different releases and mix those, as it creates confusion for the next person who is going to submit a PR with update

It would only be applied to the same series (5.12) and is an immediate revert of a regression introduced on 5.12.13; something helpful would be to leave a note regarding that but is the same thing that happened with the `rtnetlink_fix_regression_in_bridge_vlan_configuration` patch (revert of a regression introduced on 5.12.12 and fixed in 5.12.13)

**Comment by TredwellGit** [comment]
Also needs to be reverted for 5.10 and 5.4.

**Comment by ymatsiuk** [comment]
Leaked a bit of formatting if you don't mind 😉 I didn't build the kernel fully just tested the path phase passes, so please review carefully.

**Comment by fabianhjr** [comment]
Reviewed the changes, going to build. Thanks for working on this @ymatsiuk <3

**Comment by ymatsiuk** [comment]
@ofborg test kernel-latest kernel-lts latestKernel.login latestKernel.hardened

**Comment by TredwellGit** [comment]
- 5.13 does not need patching.
- linux_xanmod needs patching.

**Comment by fabianhjr** [comment]
Could build and boot to 5.12.13 succesfully

**Comment by fabianhjr** [comment]
Can confirm 5.13 doesn't need the patch:

```
applying patch /nix/store/m382nbxyabd66hmn5av0cfc94p9yfss4-revert_enlarge_CP_MEC_DOORBELL_RANGE_UPPER_drm_amdgpu_gfx10.patch
patching file drivers/gpu/drm/amd/amdgpu/gfx_v10_0.c
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file drivers/gpu/drm/amd/amdgpu/gfx_v10_0.c.rej
```

**Comment by ymatsiuk** [comment]
rephrased and fixed

**Review by fabianhjr — APPROVED** [review]
LGTM

**Comment by TredwellGit** [comment]
4.19, 4.14, 4.9, and 4.4 need update.

**Comment by TredwellGit** [comment]
Correction, 4.9 and 4.4 need update. 4.19 and 4.14 are blocked by hardened.

**Comment by fortuneteller2k** [comment]
> * linux_xanmod needs patching.

After #128842 it shouldn't need it.

**Comment by ymatsiuk** [comment]
@ofborg test kernel-latest kernel-lts latestKernel.login latestKernel.hardened

**Review by Ma27 — APPROVED** [review]

**Comment by TredwellGit** [comment]
Only commits updating to the latest version should be included. For example, `5.12.12 -> 5.12.14` not `5.12.12 -> 5.12.13` then `5.12.13 -> 5.12.14`.

**Comment by ymatsiuk** [comment]
@ofborg test kernel-latest kernel-lts latestKernel.login latestKernel.hardened

**Review by fabianhjr — APPROVED** [review]
LGTM

**Comment by ymatsiuk** [comment]
Is there anything else I can do here?

**Comment by fabianhjr** [comment]
Don't think so, maybe ping someone for merge?

**Comment by mweinelt** [comment]
@GrahamcOfBorg eval
@GrahamcOfBorg test kernel-latest kernel-lts latestKernel.login latestKernel.hardened

**Pull request merged**
