### PR TITLE
[new] emacs24Packages org-trello & new deps derivations

### PR DESCRIPTION
**Pull request by ardumont**
Pre-requisites:
- Add derivation request
- Add derivation request-deferred
- Add derivation deferred

Goal:
- Add org-trello derivation

### CODE REVIEW

**Comment by jagajaga** [comment]
Haven't you seen this https://github.com/NixOS/nixpkgs/pull/6641?

**Comment by ardumont** [comment]
Hello,

no I did not see it.

Thanks for pointing this out!

tony / @ardumont

**Comment by jagajaga** [comment]
So maybe add your pkgs to `emacs24PakagesNG`?

**Comment by ardumont** [comment]
Yes, it's my intention to do so!


tony / @ardumont

**Comment by ardumont** [comment]
Work in progress.
I'll force push on this branch when ready.

**Comment by jagajaga** [comment]
Have you built it locally?

**Comment by ardumont** [comment]
Yes and it's ok.
I've build it on another box just now and it's ok.


tony / @ardumont

**Comment by ardumont** [comment]
Here it is:

```sh
# tony at lenovo in ~/repo/perso/nixpkgs on git:add-org-trello-and-dependencies-derivation o [13:37:08]
$ nix-build -A emacs24PackagesNg.request-deferred -A emacs24PackagesNg.deferred -A emacs24PackagesNg.request -A emacs24PackagesNg.org-trello
these derivations will be built:
/nix/store/386q78fmjqkl6gry66cbd59pjlc6q338-package-build.el.drv
/nix/store/7fwvra9v8zjvnk6wh24r604kcr2kw6pq-dash.el-2.9.0-src.drv
/nix/store/9db3431fwz8ghzi038mygf3vas8yv8l2-emacs-dash-2.9.0.drv
/nix/store/yblaaxrwc22g3m1ppimmkdf34q8i1bs3-emacs-request-adf7de452f9914406bfb693541f1d280093c4efd-src.drv
/nix/store/h8k79bpc8yi7k6bj7z6p6hczd5djnf4j-emacs-request-0.2.0.drv
/nix/store/ljg3a2p8f4c9ify01q9cdwbakmng0xa9-emacs-deferred-896d4b53210289afe489e1ee7db4e12cb9248109-src.drv
/nix/store/wpa65xs2mi60fh9379smz2wk09n0hgqa-emacs-deferred-0.3.2.drv
/nix/store/hz7ycg7rbhh5wpp5b1yb1jcg8j3rvanz-emacs-request-deferred-0.2.0.drv
/nix/store/j0fgni3z2s4nabij4klkh9dvc34h6s70-org-trello-5656f32d3624b3c82014658aef88ffa47c0fca7b-src.drv
/nix/store/cvfxps05wib30vq6yv67acady4c60cr8-s.el-1f85b5112f3f68169ddaa2911fcfa030f979eb4d-src.drv
/nix/store/nl2zmz47z3a7wx6ari0s4cbmyl00lglv-emacs-s-20140910.drv
/nix/store/70n9gbrjmnjbfflni09qvj72vf59di6q-emacs-org-trello-0.6.9.2.drv
these paths will be fetched (36.17 MiB download, 102.04 MiB unpacked):
/nix/store/6km7fqcx85dwpxfsqp1jav3y4x84d163-libXpm-3.5.11
/nix/store/7ajid5i7qs79y237gl4q5cg4pzmd328n-emacs-24.4
/nix/store/dnssw6bnj4mk85jqm4gxgdm4wads7qnr-libungif-4.1.4
/nix/store/i3a50p23l245xxiiwyd6avkqsw11b8rc-libcroco-0.6.8
/nix/store/wynjz05709gv0zm5ivz6zxdypn5xibdk-librsvg-2.36.4
building path (s) ‘/nix/store/lzj8yf45hmhahbvljnjcwnz8pgkb3k9n-emacs-deferred-896d4b53210289afe489e1ee7db4e12cb9248109-src’
building path (s) ‘/nix/store/zv571lzzmvbjsjw9p6rck14fw225mdbp-emacs-request-adf7de452f9914406bfb693541f1d280093c4efd-src’
building path (s) ‘/nix/store/g0qijhqkk4db7pq07v8m3smvxis04m7m-org-trello-5656f32d3624b3c82014658aef88ffa47c0fca7b-src’
building path (s) ‘/nix/store/r7m3gd8d0ji8vc4hwjjhmmf4c2r05ija-package-build.el’

trying https://raw.githubusercontent.com/milkypostman/melpa/12a862e5c5c62ce627dab83d7cf2cca6e8b56c47/package-build.el
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
trying https://github.com/org-trello/org-trello/archive/5656f32d3624b3c82014658aef88ffa47c0fca7b.tar.gz

trying https://github.com/kiwanami/emacs-deferred/archive/896d4b53210289afe489e1ee7db4e12cb9248109.tar.gz
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
trying https://github.com/tkf/emacs-request/archive/adf7de452f9914406bfb693541f1d280093c4efd.tar.gz
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 59453  100 59453    0     0   107k      0 --:--:-- --:--:-- --:--:--  108k
fetching path ‘/nix/store/6km7fqcx85dwpxfsqp1jav3y4x84d163-libXpm-3.5.11’...
...
Generating autoloads for org-trello-buffer.el...
Generating autoloads for org-trello-buffer.el...done
Generating autoloads for org-trello-cbx.el...
Generating autoloads for org-trello-cbx.el...done
Generating autoloads for org-trello-controller.el...
Generating autoloads for org-trello-controller.el...done
Generating autoloads for org-trello-data.el...
Generating autoloads for org-trello-data.el...done
Generating autoloads for org-trello-entity.el...
Generating autoloads for org-trello-entity.el...done
Generating autoloads for org-trello-hash.el...
Generating autoloads for org-trello-hash.el...done
Generating autoloads for org-trello-input.el...
Generating autoloads for org-trello-input.el...done
Generating autoloads for org-trello-log.el...
Generating autoloads for org-trello-log.el...done
Generating autoloads for org-trello-pkg.el...
Generating autoloads for org-trello-pkg.el...done
Generating autoloads for org-trello-proxy.el...
Generating autoloads for org-trello-proxy.el...done
Generating autoloads for org-trello-query.el...
Generating autoloads for org-trello-query.el...done
Generating autoloads for org-trello-setup.el...
Generating autoloads for org-trello-setup.el...done
Generating autoloads for org-trello-utils.el...
Generating autoloads for org-trello-utils.el...done
Saving file /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-autoloads.el...
Wrote /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-autoloads.el
Checking /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2...
Compiling /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-action.el...
Wrote /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-action.elc
Compiling /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-api.el...
Wrote /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-api.elc
Compiling /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-autoloads.el...
Compiling /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-backend.el...
Wrote /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-backend.elc
Compiling /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-buffer.el...
Wrote /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-buffer.elc
Compiling /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-cbx.el...
Wrote /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-cbx.elc
Compiling /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-controller.el...
Wrote /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-controller.elc
Compiling /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-data.el...
Wrote /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-data.elc
Compiling /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-entity.el...
Wrote /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-entity.elc
Compiling /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-hash.el...
Wrote /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-hash.elc
Compiling /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-input.el...
Wrote /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-input.elc
Compiling /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-log.el...
Wrote /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-log.elc
Compiling /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-pkg.el...
Compiling /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-proxy.el...
Wrote /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-proxy.elc
Compiling /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-query.el...
Wrote /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-query.elc
Compiling /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-setup.el...
Wrote /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-setup.elc
Compiling /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-utils.el...
Wrote /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2/share/emacs/site-lisp/elpa/org-trello-0.6.9.2/org-trello-utils.elc
Done (Total of 15 files compiled, 2 skipped)
Parsing tar file...
Parsing tar file...done
post-installation fixup
patching ELF executables and libraries in /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2
gzipping man pages in /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2
patching script interpreter paths in /nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2
/nix/store/5nlyfmk5nblninsf7l6jq5pbmzdyfp0q-emacs-request-deferred-0.2.0
/nix/store/6n7ir4cnikfflmmxgkd3fghav67j8wgk-emacs-deferred-0.3.2
/nix/store/18clbsvw9armllpbi6gs5p7z3zj0841c-emacs-request-0.2.0
/nix/store/rndbf24g0h4yq85kqrarfnl7vkl5sj9d-emacs-org-trello-0.6.9.2
```

**Pull request merged**
