### PR TITLE
glibc: 2.32-40 -> 2.32-46

### PR DESCRIPTION
**Pull request by TredwellGit**
###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
No, just breaking changes. I would block bumping this to `2.33`, but a patch bump on `2.32` is fine :)

**Comment by Ma27** [comment]
Thanks for elaborating! The package itself is working fine. Will take a look at the changelog and currently building a stdenv on a buildserver. If both seems fine, I'd merge then :)

**Comment by jonringer** [comment]
sounds good to me :)

**Review by Ma27 — APPROVED** [review]
Diff & Upstream Diff LGTM, Build (+stdenv build) working fine on x86_64-linux and aarch64-linux.

**Pull request merged**
