### PR TITLE
python-packages: mps-youtube init version 0.2.5

### PR DESCRIPTION
**Pull request by odi**
new python package; https://github.com/mps-youtube/mps-youtube
Terminal based YouTube player and downloader

### CODE REVIEW

**Comment by lethalman** [comment]
```
output path ‘/nix/store/g9h0dh5kzpnxfjr38l671sd1dbhz1c7l-v0.2.5.tar.gz’ should have md5 hash ‘d
131d01908c3c9758140152d97832110’, instead has ‘99016b53b7dfb440080d8429443aea9b’
```

**Comment by lethalman** [comment]
Use `fetchFromGitHub` please.

**Comment by jagajaga** [comment]
Please avoid the word `version` in the commit's name.

**Comment by odi** [comment]
out of memory again
The build failed due to running out of memory: ...

**Pull request merged**
