### PR TITLE
bitwarden: 1.28.1 -> 1.29.1

### LINKED ISSUE #144497: Bitwarden package out-of-date
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: bitwarden

current version: 1.28
desired version: 1.29

###### Notify maintainers

maintainers: @Kiwi 

###### Note for maintainers

Maybe add support to use system electron via an override, as Bitwarden currently ships with Electron 11, which is severly outdated.

Edit: bitwarden not bitwarden-cli.

### PR DESCRIPTION
**Pull request by prusnak**
###### Motivation for this change

- version update
- fixes https://github.com/NixOS/nixpkgs/issues/144497

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by prusnak** [comment]
@Schmensch can you please test whether this change works for you?

**Review by jyooru — APPROVED** [review]

**Comment by jyooru** [comment]
Result of `nixpkgs-review pr 144524` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>bitwarden</li>
  </ul>
</details>

**Comment by prusnak** [comment]
@jyooru have you tried running the app?

**Comment by jyooru** [comment]
Yes, it ran fine. 
2021-11-04-194252_344x325_scrot

I'm quite new to reviewing on nixpkgs, should I make a note that it worked?

**Comment by prusnak** [comment]
> I'm quite new to reviewing on nixpkgs, should I make a note that it worked?

Nothing that is always nice :-)

**Pull request merged**
