### PR TITLE
onlyoffice: typo fixes, remove top level `with lib;`

### PR DESCRIPTION
**Pull request by britter**
## Description of changes

Non functional changes:
- typo fixes in option descriptions.
- Replaced top-level `with lib;` with prepending affected components with `lib.`

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by JohnRTitor — COMMENTED** [review]
Since you have touched this module already, could you remove the `with lib;` at the top level and prepend the affected components with `lib.` in a separate commit?

**Comment by britter** [comment]
@JohnRTitor sure! PTAL at [57ea5be](https://github.com/NixOS/nixpkgs/pull/326047/commits/57ea5be9292ed4957c4a44f2fad6fd666a005a3a)

Would be curious to understand why you asked for this change. Is this a general design principle in nixpkgs to not have `with` statements? Do you have a reference where I can read up on the reasoning? Thanks!

**Comment by emilazy** [comment]
See https://github.com/NixOS/nixpkgs/issues/208242. `with` has some surprising behaviour, and makes static scope‐checking impossible; `let var = 123; in vra` gives an error, but `let var = 123; in with …; vra` can’t.

**Review by JohnRTitor — APPROVED** [review]
Built NixOS manual and checked.
```bash
nix build github:NixOS/nixpkgs/refs/pull/326047/merge#htmlDocs.nixosManual.x86_64-linux --print-build-logs --print-out-paths;
```

**Pull request merged**
