### PR TITLE
zed-editor: 0.145.1 -> 0.146.3

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Changelog: https://github.com/zed-industries/zed/releases/tag/v0.146.3

cc @jansol @niklaskorz 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 331354` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
image

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 331354` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

**Comment by jansol** [comment]
```
error: builder for '/nix/store/96hi983c9qp54svjba3lkx9wbdbwszls-zed-0.146.3.drv' failed with exit code 101;
       last 10 log lines:
       > assertion failed: window_is_edited(window, cx)
       > note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
       >
       >
       > failures:
       >     zed::tests::test_window_edit_state_restoring_enabled
       >
       > test result: FAILED. 21 passed; 1 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.72s
       >
       > error: test failed, to rerun pass `--bin zed`
       For full logs, run 'nix log /nix/store/96hi983c9qp54svjba3lkx9wbdbwszls-zed-0.146.3.drv'
```

```
---- zed::tests::test_window_edit_state_restoring_enabled stdout ----
[2024-07-31T20:52:37Z ERROR client] Custom { kind: NotFound, error: PathError { path: "/homeless-shelter/.local/share/zed/logs/.tmpsgVt2m", err: Os { code: 2, kind: NotFound, message: "No such file or directory" } } }
[2024-07-31T20:52:37Z ERROR theme] theme not found: One Light
[2024-07-31T20:52:37Z ERROR theme] theme not found: One Light
[2024-07-31T20:52:37Z ERROR workspace] No path or contents found for buffer
[2024-07-31T20:52:37Z ERROR gpui] window not found
thread 'zed::tests::test_window_edit_state_restoring_enabled' panicked at crates/zed/src/zed.rs:1534:9:
assertion failed: window_is_edited(window, cx)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by GaetanLepage** [comment]
> `error: builder for '/nix/store/96hi983c9qp54svjba3lkx9wbdbwszls-zed-0.146.3.drv' failed with exit code 101;`

You got this at compile time ?

**Comment by jansol** [comment]
> You got this at compile time ?

Yep, from `nix build github:GaetanLepage/nixpkgs/zed#zed-editor`

**Comment by unitythemaker** [comment]
I think it builds successfully on me:
```
unitythemaker@blazingfast ~> nix build github:GaetanLepage/nixpkgs/zed#zed-editor
unitythemaker@blazingfast ~> 
```

Also able to launch it:
image
```
unitythemaker@blazingfast ~> cd result/
unitythemaker@blazingfast ~/result> ls
bin  libexec  share
unitythemaker@blazingfast ~/result> bin/zed
```

**Comment by GaetanLepage** [comment]
> > failures:
>        >     zed::tests::test_window_edit_state_restoring_enabled

This seemingly flaky test also fails on Hydra. I have disabled it.

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 331354` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 331354` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

**Pull request merged**
