### PR TITLE
deltachat-desktop: 1.30.1 -> 1.32.0

### PR DESCRIPTION
**Pull request by dotlambda**
###### Description of changes
https://github.com/deltachat/deltachat-desktop/blob/v1.32.0/CHANGELOG.md

I can't use the correct version of libdeltachat because of https://github.com/deltachat/deltachat-core-rust/issues/3548.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rapenne-s** [comment]
with this change on top, latest version 1.32.1 builds and runs fine

```
diff --git a/pkgs/applications/networking/instant-messengers/deltachat-desktop/default.nix b/pkgs/applications/networking/instant-messengers/deltachat-desktop/default.nix
index 7266ebde10f..391455b4b9b 100644
--- a/pkgs/applications/networking/instant-messengers/deltachat-desktop/default.nix
+++ b/pkgs/applications/networking/instant-messengers/deltachat-desktop/default.nix
@@ -50,13 +50,13 @@ let
   };
 in nodePackages.deltachat-desktop.override rec {
   pname = "deltachat-desktop";
-  version = "1.32.0";
+  version = "1.32.1";
 
   src = fetchFromGitHub {
     owner = "deltachat";
     repo = "deltachat-desktop";
     rev = "v${version}";
-    hash = "sha256-5eau6CLgze13rc1+fhNgdy/NEbEHBKf5/xd5K+zb4Co=";
+    hash = "sha256-DklrTMnubVSkD1wfJzPRqWsVZy65kG7EuvRVRYcCUAI=";
   };
 
   nativeBuildInputs = [
```

I tried to port it without the fix, and can't get it to work...

**Comment by dotlambda** [comment]
@rapenne-s But libdeltachat 1.91.0 still doesn't build.

**Comment by dotlambda** [comment]
@winterqt Do you still have the code that uses the recently merged https://github.com/NixOS/nixpkgs/pull/189539 for this update?

**Comment by dotlambda** [comment]
superseded by #200981

**Pull request closed without merging**
