### PR TITLE
python310Packages.censys: 2.2.0 -> 2.2.2, python310Packages.argcomplete: 2.1.1 -> 3.1.1

### PR DESCRIPTION
**Pull request by fabaff**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by hacker1024** [comment]
argcomplete is now at 3.1.0.

**Comment by fabaff** [comment]
> argcomplete is now at 3.1.1 upstream.

Thanks for the tip.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 230911` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>54 packages failed to build:</summary>
  <ul>
    <li>apache-airflow</li>
    <li>apache-airflow.dist</li>
    <li>cmake-language-server</li>
    <li>cmake-language-server.dist</li>
    <li>commitizen</li>
    <li>commitizen.dist</li>
    <li>dart-sass</li>
    <li>nuget-to-nix</li>
    <li>pipx (python310Packages.pipx)</li>
    <li>pipx.dist (python310Packages.pipx.dist)</li>
    <li>protoc-gen-dart</li>
    <li>python310Packages.censys</li>
    <li>python310Packages.censys.dist</li>
    <li>python310Packages.jedi-language-server</li>
    <li>python310Packages.jedi-language-server.dist</li>
    <li>python310Packages.lsprotocol</li>
    <li>python310Packages.lsprotocol.dist</li>
    <li>python310Packages.nox</li>
    <li>python310Packages.nox.dist</li>
    <li>python310Packages.pygls</li>
    <li>python310Packages.pygls.dist</li>
    <li>python310Packages.python-lsp-ruff</li>
    <li>python310Packages.python-lsp-ruff.dist</li>
    <li>yq (python310Packages.yq)</li>
    <li>yq.dist (python310Packages.yq.dist)</li>
    <li>python311Packages.censys</li>
    <li>python311Packages.censys.dist</li>
    <li>python311Packages.jedi-language-server</li>
    <li>python311Packages.jedi-language-server.dist</li>
    <li>python311Packages.lsprotocol</li>
    <li>python311Packages.lsprotocol.dist</li>
    <li>python311Packages.nox</li>
    <li>python311Packages.nox.dist</li>
    <li>python311Packages.pipx</li>
    <li>python311Packages.pipx.dist</li>
    <li>python311Packages.pygls</li>
    <li>python311Packages.pygls.dist</li>
    <li>python311Packages.python-lsp-ruff</li>
    <li>python311Packages.python-lsp-ruff.dist</li>
    <li>python311Packages.yq</li>
    <li>python311Packages.yq.dist</li>
    <li>ruff-lsp</li>
    <li>ruff-lsp.dist</li>
    <li>shopware-cli</li>
    <li>stubby</li>
    <li>stubby.man</li>
    <li>stubby.stubbyExampleJson</li>
    <li>theharvester</li>
    <li>theharvester.dist</li>
    <li>tockloader</li>
    <li>tockloader.dist</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vscode-extensions.ms-python.python</li>
    <li>ycmd</li>
  </ul>
</details>
<details>
  <summary>73 packages built:</summary>
  <ul>
    <li>barman</li>
    <li>barman.dist</li>
    <li>checkov</li>
    <li>checkov.dist</li>
    <li>clickable</li>
    <li>clickable.dist</li>
    <li>cloud-custodian</li>
    <li>cloud-custodian.dist</li>
    <li>cwltool</li>
    <li>cwltool.dist</li>
    <li>datalad</li>
    <li>datalad.dist</li>
    <li>diffoscope</li>
    <li>diffoscope.dist</li>
    <li>diffoscope.man</li>
    <li>diffoscopeMinimal</li>
    <li>diffoscopeMinimal.dist</li>
    <li>diffoscopeMinimal.man</li>
    <li>dvc-with-remotes</li>
    <li>dvc-with-remotes.dist</li>
    <li>gallia</li>
    <li>gallia.dist</li>
    <li>git-aggregator</li>
    <li>git-aggregator.dist</li>
    <li>lenovo-legion</li>
    <li>lenovo-legion.dist</li>
    <li>linkchecker</li>
    <li>linkchecker.dist</li>
    <li>meraki-cli</li>
    <li>meraki-cli.dist</li>
    <li>pubs</li>
    <li>pubs.dist</li>
    <li>python310Packages.amcrest</li>
    <li>python310Packages.amcrest.dist</li>
    <li>python310Packages.argcomplete</li>
    <li>python310Packages.argcomplete.dist</li>
    <li>python310Packages.dvc-azure</li>
    <li>python310Packages.dvc-azure.dist</li>
    <li>python310Packages.enhancements</li>
    <li>python310Packages.enhancements.dist</li>
    <li>python310Packages.heudiconv</li>
    <li>python310Packages.heudiconv.dist</li>
    <li>python310Packages.knack</li>
    <li>python310Packages.knack.dist</li>
    <li>python310Packages.milc</li>
    <li>python310Packages.milc.dist</li>
    <li>sdkmanager (python310Packages.sdkmanager)</li>
    <li>sdkmanager.dist (python310Packages.sdkmanager.dist)</li>
    <li>python311Packages.amcrest</li>
    <li>python311Packages.amcrest.dist</li>
    <li>python311Packages.argcomplete</li>
    <li>python311Packages.argcomplete.dist</li>
    <li>python311Packages.dvc-azure</li>
    <li>python311Packages.dvc-azure.dist</li>
    <li>python311Packages.enhancements</li>
    <li>python311Packages.enhancements.dist</li>
    <li>python311Packages.heudiconv</li>
    <li>python311Packages.heudiconv.dist</li>
    <li>python311Packages.knack</li>
    <li>python311Packages.knack.dist</li>
    <li>python311Packages.milc</li>
    <li>python311Packages.milc.dist</li>
    <li>python311Packages.sdkmanager</li>
    <li>python311Packages.sdkmanager.dist</li>
    <li>qmk</li>
    <li>qmk.dist</li>
    <li>ssh-mitm</li>
    <li>ssh-mitm.dist</li>
    <li>styx</li>
    <li>styx.lib</li>
    <li>styx.themes</li>
    <li>wlc</li>
    <li>wlc.dist</li>
  </ul>
</details>

**Comment by fabaff** [comment]
@ofborg build python311Packages.censys commitizen tockloader ruff-lsp yq

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 230911` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>cwltool</li>
    <li>cwltool.dist</li>
  </ul>
</details>
<details>
  <summary>115 packages built:</summary>
  <ul>
    <li>apache-airflow</li>
    <li>apache-airflow.dist</li>
    <li>azure-cli</li>
    <li>azure-cli.dist</li>
    <li>barman</li>
    <li>barman.dist</li>
    <li>checkov</li>
    <li>checkov.dist</li>
    <li>clickable</li>
    <li>clickable.dist</li>
    <li>cloud-custodian</li>
    <li>cloud-custodian.dist</li>
    <li>commitizen</li>
    <li>commitizen.dist</li>
    <li>dart-sass</li>
    <li>datalad</li>
    <li>datalad.dist</li>
    <li>diffoscopeMinimal</li>
    <li>diffoscopeMinimal.dist</li>
    <li>diffoscopeMinimal.man</li>
    <li>dvc-with-remotes</li>
    <li>dvc-with-remotes.dist</li>
    <li>gallia</li>
    <li>gallia.dist</li>
    <li>git-aggregator</li>
    <li>git-aggregator.dist</li>
    <li>lenovo-legion</li>
    <li>lenovo-legion.dist</li>
    <li>linkchecker</li>
    <li>linkchecker.dist</li>
    <li>meraki-cli</li>
    <li>meraki-cli.dist</li>
    <li>nuget-to-nix</li>
    <li>protoc-gen-dart</li>
    <li>pubs</li>
    <li>pubs.dist</li>
    <li>python310Packages.amcrest</li>
    <li>python310Packages.amcrest.dist</li>
    <li>python310Packages.argcomplete</li>
    <li>python310Packages.argcomplete.dist</li>
    <li>python310Packages.censys</li>
    <li>python310Packages.censys.dist</li>
    <li>python310Packages.dvc-azure</li>
    <li>python310Packages.dvc-azure.dist</li>
    <li>python310Packages.enhancements</li>
    <li>python310Packages.enhancements.dist</li>
    <li>python310Packages.heudiconv</li>
    <li>python310Packages.heudiconv.dist</li>
    <li>python310Packages.jedi-language-server</li>
    <li>python310Packages.jedi-language-server.dist</li>
    <li>python310Packages.knack</li>
    <li>python310Packages.knack.dist</li>
    <li>python310Packages.lsprotocol</li>
    <li>python310Packages.lsprotocol.dist</li>
    <li>python310Packages.milc</li>
    <li>python310Packages.milc.dist</li>
    <li>python310Packages.nox</li>
    <li>python310Packages.nox.dist</li>
    <li>python310Packages.pipx</li>
    <li>python310Packages.pipx.dist</li>
    <li>python310Packages.pygls</li>
    <li>python310Packages.pygls.dist</li>
    <li>python310Packages.python-lsp-ruff</li>
    <li>python310Packages.python-lsp-ruff.dist</li>
    <li>sdkmanager (python310Packages.sdkmanager)</li>
    <li>sdkmanager.dist (python310Packages.sdkmanager.dist)</li>
    <li>yq (python310Packages.yq)</li>
    <li>yq.dist (python310Packages.yq.dist)</li>
    <li>python311Packages.argcomplete</li>
    <li>python311Packages.argcomplete.dist</li>
    <li>python311Packages.censys</li>
    <li>python311Packages.censys.dist</li>
    <li>python311Packages.dvc-azure</li>
    <li>python311Packages.dvc-azure.dist</li>
    <li>python311Packages.enhancements</li>
    <li>python311Packages.enhancements.dist</li>
    <li>python311Packages.heudiconv</li>
    <li>python311Packages.heudiconv.dist</li>
    <li>python311Packages.knack</li>
    <li>python311Packages.knack.dist</li>
    <li>python311Packages.lsprotocol</li>
    <li>python311Packages.lsprotocol.dist</li>
    <li>python311Packages.milc</li>
    <li>python311Packages.milc.dist</li>
    <li>python311Packages.nox</li>
    <li>python311Packages.nox.dist</li>
    <li>python311Packages.pipx</li>
    <li>python311Packages.pipx.dist</li>
    <li>python311Packages.pygls</li>
    <li>python311Packages.pygls.dist</li>
    <li>python311Packages.python-lsp-ruff</li>
    <li>python311Packages.python-lsp-ruff.dist</li>
    <li>python311Packages.sdkmanager</li>
    <li>python311Packages.sdkmanager.dist</li>
    <li>python311Packages.yq</li>
    <li>python311Packages.yq.dist</li>
    <li>qmk</li>
    <li>qmk.dist</li>
    <li>ruff-lsp</li>
    <li>ruff-lsp.dist</li>
    <li>shopware-cli</li>
    <li>ssh-mitm</li>
    <li>ssh-mitm.dist</li>
    <li>styx</li>
    <li>styx.lib</li>
    <li>styx.themes</li>
    <li>theharvester</li>
    <li>theharvester.dist</li>
    <li>tockloader</li>
    <li>tockloader.dist</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vscode-extensions.ms-python.python</li>
    <li>wlc</li>
    <li>wlc.dist</li>
    <li>ycmd</li>
  </ul>
</details>

**Comment by fabaff** [comment]
`cwltool` already fails.

**Pull request merged**
