### PR TITLE
poetry: don't use poetry2nix

### PR DESCRIPTION
**Pull request by dotlambda**
The use of poetry2nix within Nixpkgs is discouraged since we have a well-tested Python package set.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
We should probably move `poetry` out of `python-modules` and patch everything to use `poetry-core`. That way we can use `packageOverrides` to be more agile with poetrys dependencies.

**Comment by dotlambda** [comment]
@mweinelt beancount-ing-diba was the only remaining package using poetry instead of poetry-core

**Review by SuperSandro2000 — APPROVED** [review]
Thanks for cleaning this up!

**Comment by adisbladis** [comment]
If you want to to this (I'm totally 100% in disagreement with this PR) also remove me as a maintainer from the package as I want nothing to do with the python package sets.

**Comment by adisbladis** [comment]
Also, this begs the question: What is even the purpose of having maintainers listed if you're going to continuously go against their wishes anyway? I've been clearly saying no to efforts like this in the past and @dotlambda is well aware of this.
But if you're going to keep steamrolling despite maintainer wishes I'm not gong to keep fighting this.
I'm sick and tired of this crap and quite frankly on a personal level it's extremely demotivating.

IMHO this is the exact opposite direction to what nixpkgs should go towards as I see the current Python maintenance model in nixpkgs as unsustainable, and for the lack of a better word to express it, insane.

Additionally, as I have express before this results in leaking all of the dependencies of poetry via `$PYTHONPATH`, making this package extremely broken in a nix-shell environment.
You would need to adopt a similar "vendoring" as the existing poetry package does not to have spectacularly broken imports.

**Comment by adisbladis** [comment]
> The use of poetry2nix within Nixpkgs is discouraged 

By who exactly? By what decree?

**Comment by adisbladis** [comment]
I'm willing to concede on this even though I don't agree, I'm not especially interested in having this discussion time and time again.. 
I don't agree, but whatever.

Regardless the usability issue with `$PYTHONPATH` needs to be fixed before this is mergeable.

**Comment by dotlambda** [comment]
I tested poetry after removing `$out/nix-support/propagated-build-inputs` and it seems like symlinking poetry-core, as was done previously, isn't necessary. Can you check?

**Comment by adisbladis** [comment]
> I tested poetry after removing `$out/nix-support/propagated-build-inputs` and it seems like symlinking poetry-core, as was done previously, isn't necessary. Can you check?

That works.
Additionally a new version of Poetry was released yesterday. You might want to squeeze in the version bump in this PR too.

**Comment by SuperSandro2000** [comment]
> IMHO this is the exact opposite direction to what nixpkgs should go towards as I see the current Python maintenance model in nixpkgs as unsustainable, and for the lack of a better word to express it, insane.

We cannot rely on upstreams lock files especially in the python world. The ``cryptography`` package is a perfect example why: Some upstreams pin it to before it was build with rust for various reasons but some of the more popular ones are that they either need to install rust, it takes to long to compile or because some cross platform issue. All those reasons do not apply to nixpkgs and are completely unacceptable to alone pin a 1.5 years old security relevant library for us.
``cryptography`` is a direct dependency of hundreds of packages and a indirect one of thousands. Patching hundreds of lock files is unsustainable work.



Fully relying on upsteams lock files create security and maintainer nightmares like https://github.com/NixOS/nixpkgs/issues/141368

**Pull request merged**
