### PR TITLE
meli: Remove

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Uses openssl_1_1, which will be removed before the 23.05 branchoff, so remove this.

---

See #210452

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
CC @0x4A6F

**Comment by figsoda** [comment]
this should be removed from `all-packages.nix` as well

**Comment by matthiasbeyer** [comment]
Meh, missed it when `git-add`ing. Fixed.

**Comment by figsoda** [comment]
Can you also add an alias that `throw`s?

**Comment by matthiasbeyer** [comment]
Like this?

**Comment by matthiasbeyer** [comment]
No worries. If this looks good I can squash this!

**Comment by 0x4A6F** [comment]
LGTM

**Comment by ajs124** [comment]
if you are (or anyone else that stumbles over this is) still interested in using `meli`, it can probably be fixed by updating the cargo deps

**Review by figsoda — APPROVED** [review]
lgtm for a squash merge

**Pull request merged**
