### PR TITLE
ruby: 2.2.3 -> 2.2.5 and 2.1.7 -> 2.1.10

### PR DESCRIPTION
**Pull request by vrthra**
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vrthra** [comment]
Error on travis was ` No space left on device`

**Comment by joachifm** [comment]
Needs a rebase

**Comment by vrthra** [comment]
I will update with a rebase soon. I am currently in a location with very sporadic internet access with limited bandwidth budget.

**Comment by vrthra** [comment]
@joachifm I have updated the PR

**Comment by vrthra** [comment]
@joachifm Ruby 1.x and 2.0.0 is [EOLed](https://www.ruby-lang.org/en/downloads/) Can they be removed from the `pkgs/development/interpreters/ruby/default.nix`? What are the guidelines for Nix packaging on removing old versions packages?

**Comment by fpletz** [comment]
We usually remove software versions that are not maintained upstream anymore. One exception would be when there are still packages in nixpkgs depending on old versions that can't be fixed. As you're stepping up as maintainer (thanks btw!) I'll guess it's your decision now. ;)

Either way, this should be merged. :+1:

**Pull request merged**
