### PR TITLE
moesocks service: init at 1.0.0.40

### PR DESCRIPTION
**Pull request by ghost**
[moesocks](http://hackage.haskell.org/package/moesocks) SOCKS5 proxy server.

Tested on the unstable channel: 421989f.

### CODE REVIEW

**Comment by jgeerds** [comment]
@nfjinjing You could also use [mkEnableOption](https://github.com/NixOS/nixpkgs/blob/master/lib/options.nix)

**Comment by nfjinjing** [comment]
Thanks! Updated and also fixed the coding convention for function calls.

What does "needs changelog" mean?

**Comment by jgeerds** [comment]
That we should mention this new service [in the changelog](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-unstable.xml) for the upcoming NixOS release. There is a `The following new services were added since the last release:` section. Would be great if you add moesocks to the list :smile:

**Comment by nfjinjing** [comment]
Thanks @jgeerds, it's been added.

**Comment by fpletz** [comment]
@jgeerds Do you have any other issues with this PR? LGTM

**Pull request closed without merging**
