### PR TITLE
mailpit: init at 1.7.1

### PR DESCRIPTION
**Pull request by stephank**
###### Description of changes

Packages [mailpit](https://github.com/axllent/mailpit)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by drupol — COMMENTED** [review]
Is this a duplicate of #242719 ?

**Review by shyim — APPROVED** [review]
Wow. Now I know how to get libtool working on darwin 😅

**Review by drupol — APPROVED** [review]

**Review by drupol — CHANGES_REQUESTED** [review]
I just noticed a bit too late,  that the CI is not able to build the derivation.

**Comment by stephank** [comment]
> Is this a duplicate of #242719 ?

Oh! I must've searched the issue tracker before it was open. :)

> Wow. Now I know how to get libtool working on darwin 😅

It seems to expect the Darwin native libtool, which has different parameters. Normally, including `cctools` as a build input breaks stuff, because wrapped versions are already part of stdenv, and including it again puts unwrapped versions in PATH. So I'm also a little confused why it works fine in this case, but maybe that has to do with the recent switch to `cctools-llvm`.

> I just noticed a bit too late, that the CI is not able to build the derivation.

Hmm, I don't understand the ofborg failures. I just did build on the `x86_64-linux` community builder, and it's fine here.

**Comment by stephank** [comment]
Oh! It appears the go modules derivation inherits nativeBuildInputs and preBuild, so it's trying to run the hook there. I didn't notice because I had a build cached before I added the npm stuff, and that cache was also copied to the community builder. D'oh!

I'll make a follow-up PR shortly.

**Pull request merged**
