### PR TITLE
tlsh: 3.4.5 -> 4.5.0

### PR DESCRIPTION
**Pull request by armijnhemel**
###### Motivation for this change

tlsh hasn't been updated in a long time, while there have been a few releases. Unfortunately the TLSH developers decided to not use tags for their new releases.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Please change the commit message and PR title to ``tlsh: 4.5.0 -> 3.4.5`` to fit the contributing guide.

**Comment by armijnhemel** [comment]
> Please change the commit message and PR title to `tlsh: 4.5.0 -> 3.4.5` to fit the contributing guide.

Since I don't want to downgrade I did it the other way around ;-)

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 111949` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>diffoscope: log was empty</li>
  </ul>
</details>
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>python37Packages.tlsh</li>
<li>python38Packages.tlsh</li>
<li>python39Packages.tlsh</li>
</ul>
</details>

```
error: --- Error ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
nixbuilder for '/nix/store/mikmbqjj49ppfjzfk3sgb7zxmlqldg0j-e2fsprogs-1.45.6.drv' failed with exit code 2; last 10 log lines:
/nix/store/2c9kjj14qhns6cd28cmm51jvy74yk4c4-Libsystem-osx-10.12.6/include/sys/_types/_off_t.h:30:25: note: 'off_t' declared here
typedef __darwin_off_t          off_t;
^
1 error generated.
make[2]: *** [Makefile:611: imager.o] Error 1 
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/private/tmp/nix-build-e2fsprogs-1.45.6.drv-0/e2fsprogs-1.45.6/lib/ext2fs'
make[1]: *** [Makefile:445: all-libs-recursive] Error 1
make[1]: Leaving directory '/private/tmp/nix-build-e2fsprogs-1.45.6.drv-0/e2fsprogs-1.45.6'
make: *** [Makefile:366: all] Error 2
error: --- Error -----------------------------------------------------------------------------------------------------------------------------------------------------------------------
nix1 dependencies of derivation '/nix/store/291ricwi43wxd34adg4ypqirx8b3wy30-diffoscope-163.drv' failed to build
error: --- Error -----------------------------------------------------------------------------------------------------------------------------------------------------------------------
nix1 dependencies of derivation '/nix/store/wcr9780gc1z6dy5y2kwfc2nm86bjxjw7-env.drv' failed to build
```

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 111949` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
4 packages built:
</summary>
<ul>
<li>diffoscope</li>
<li>python37Packages.tlsh</li>
<li>python38Packages.tlsh</li>
<li>python39Packages.tlsh</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 111949` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
4 packages built:
</summary>
<ul>
<li>diffoscope</li>
<li>python37Packages.tlsh</li>
<li>python38Packages.tlsh</li>
<li>python39Packages.tlsh</li>
</ul>
</details>

**Pull request merged**
