### PR TITLE
qemu_xen: sync with xen meta attributes

### PR DESCRIPTION
**Pull request by SigmaSquadron**
## Description of changes
Adds the `xen` maintainers as co-maintainers of the `qemu_xen` package.

## Things done

- Built on platform(s)
  - This PR does not rebuild any packages.
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by CertainLach** [comment]
I wonder if we need to keep EOL versions of Xen in nixpkgs?
Ok, got it, misunderstood the original intent.

Perhaps, this will show the intention better?
```nix
maintainers = let
  qemuMaintainers =  with maintainers; [ eelco qyliss ];
  xenMaintainers = xen.meta.maintainers;
  unmaintained = xenMaintainers == [];
  maintainers = qemuMaintainers ++ optionals enableXen xenMaintainers
in optionals !unmaintained maintainers;
```

**Comment by SigmaSquadron** [comment]
> I wonder if we need to keep EOL versions of Xen in nixpkgs? 

We keep outdated versions in knownVulnerabilitites for one release cycle before deleting them. This prevents users from suddenly updating to a non-existent Xen version.

> Perhaps, this will show the intention better?

This looks good, and I was trying to do something similar with a `let` statement in the `meta` set, but this is a better solution.

**Comment by emilazy** [comment]
> The issue with just adding the maintainers is that the package still appears maintained if Xen is unmaintained. This will be the case for EOL versions of Xen, such as 4.16 in December. For those versions, the usual maintainer list needs to be removed.

Perhaps the QEMU maintainer list should be overwritten entirely, then? Either the QEMU maintainers can meaningfully maintain the package without being heavily involved in Xen, in which case they don’t need removing, or the Xen maintainer team should have complete responsibility over the Xen variant.

Given that the actual Xen package will show as unmaintained, though, I don’t see much benefit in worrying about what `qemu_xen` lists. To be honest I don’t think users pay much attention to maintainer lists in general anyway; all it means is fewer ofborg pings, and frankly the Xen maintainers seem best placed to inform those users that the packages are unsupported anyway; `knownVulnerabilities` is a way bigger hammer than `maintainers`.

Anyway, I guess I’m really saying that it doesn’t matter and you can do whatever you want :)

**Comment by SigmaSquadron** [comment]
There. Instead of doing a check, we just update the set with the contents of the Xen package.

**Review by emilazy — APPROVED** [review]
Seems good to me. QEMU maintainers should still get a look at any QEMU change that could affect the non‐Xen build, but I trust you to loop them in :)

cc @alyssais for sign‐off on this

**Review by CertainLach — APPROVED** [review]

**Comment by alyssais** [comment]
> The issue with just adding the maintainers is that the package still appears maintained if Xen is unmaintained.

IMO this is fine?  This is how every package in Nixpkgs works — it might be maintained, but it's likely to have a dependency that isn't.

**Comment by SigmaSquadron** [comment]
Well, my reasoning is that `qemu_xen` isn't exactly a normal package dependency or a dependent package. It's the QEMU part of Xen, and useless if you aren't using Xen. It's also not exactly a realistic overview of maintainership, as the QEMU maintainers don't maintain Xen, despite your names being present in `qemu_xen`. If there's ever a bug report for `qemu_xen` specifically, the report would mention two maintainers that don't exactly have any way to fix the package, as any issues would most likely be with Xen itself.

**Comment by alyssais** [comment]
But Xen is just a feature of QEMU, unless I'm misunderstanding.  If there are bugs with QEMU Xen, upstream is QEMU, not the Xen project, right?

(BTW: I'm the only actual maintainer for QEMU in Nixpkgs — Eelco hasn't touched the package in years.)

**Comment by SigmaSquadron** [comment]
> But Xen is just a feature of QEMU, unless I'm misunderstanding. If there are bugs with QEMU Xen, upstream is QEMU, not the Xen project, right?

Many years ago, upstream QEMU didn't have a feature flag for Xen, and you could only get `qemu_xen` by compiling it alongside Xen. Eventually, Xen's modified fork of QEMU was upstreamed and could be enabled with the feature flag we have today. This `qemu_xen` is a part of a normally-functioning Xen, and is therefore maintained by the upstream Xen developers, not the QEMU developers. If there's a `qemu_xen` specific bug, the vendor that fixes it is usually Xen, not QEMU. This PR simply reflects this upstream situation.

**Comment by alyssais** [comment]
There's no reason to think that only Xen-specific bugs will be reported against the qemu_xen package.  I'd expect that a lot of the time they might be general QEMU bugs, that happened to manifest for somebody using Xen.

> If there's a `qemu_xen` specific bug, the vendor that fixes it is usually Xen, not QEMU.

I don't think this is a distinction that makes sense to draw.  What does it mean for "QEMU" to be a vendor, if the people regularly developing QEMU (which includes Xen developers) don't count as part of "QEMU"?

Essentially, I'm volunteering to help look after this package as the existing QEMU maintainer, to the extent that I can, which can include updating the package, being a bridge between Nixpkgs users and upstream, etc.  It's normal for packages with multiple maintainers that maintenance work is split between the maintainers, and they focus on different things.  This is the first time I've ever seen an offer to co-maintain a package pushed back on in Nixpkgs...

**Comment by SigmaSquadron** [comment]
> This is the first time I've ever seen an offer to co-maintain a package pushed back on in Nixpkgs...

I'm very sorry; this wasn't my intention at all! The original PR used to just add the maintainers to QEMU, but the conditional check to add maintainers was a bit too over-engineered. May we return to the first version of this PR and just add the `meta.maintainers` from Xen as co-maintainers? I was somewhat convinced that all `qemu_xen`-specific bugs would be related to Xen, but your view does make a lot of sense.

**Comment by alyssais** [comment]
SGTM.  I think perhaps you had higher expectations of the lengths our users will go to to debug problems before reporting them than I do. :P

**Comment by SigmaSquadron** [comment]
I hate github so much -_-

**Pull request merged**
