### PR TITLE
nodePackages.gtop: init at 1.0.0

### PR DESCRIPTION
**Pull request by tfc**
##### Motivation for this change

This PR adds `gtop` to the nodePackages list. It is a system monitoring dashboard for the terminal.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by tfc** [comment]
I need to (and will) rebase this, but is there anything that keeps this from being merged? I would like to avoid rebasing this every few weeks.

**Comment by tfc** [comment]
rebased

**Comment by tfc** [comment]
@globin @Ma27 @domenkozar @adisbladis any chance of merging this?

**Review by ivan — CHANGES_REQUESTED** [review]
Because this is a program for end users: can you also add `inherit (nodePackages) gtop;` to all-packages.nix?

**Comment by ivan** [comment]
Built and tested locally on x86_64 NixOS, appears to work fine.

**Review by globin — APPROVED** [review]

**Comment by tfc** [comment]
@ivan thx for the suggestion! done.

**Comment by ivan** [comment]
@GrahamcOfBorg build gtop

**Review by ivan — APPROVED** [review]

**Pull request merged**
