### PR TITLE
rich-cli: fix dependency versions

### LINKED ISSUE #211987: rich-cli: --pager does not work
### Describe the bug
```
Traceback (most recent call last):
  File "/nix/store/a3a7lldql51bm2cb57173mv9q0z12dh1-rich-cli-1.8.0/bin/.rich-wrapped", line 9, in <module>
    sys.exit(run())
  File "/nix/store/a3a7lldql51bm2cb57173mv9q0z12dh1-rich-cli-1.8.0/lib/python3.10/site-packages/rich_cli/__main__.py", line 935, in run
    main()
  File "/nix/store/whih1qwwfq8a4zyzx2kdnpjvwdr9b83k-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/whih1qwwfq8a4zyzx2kdnpjvwdr9b83k-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/nix/store/whih1qwwfq8a4zyzx2kdnpjvwdr9b83k-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/whih1qwwfq8a4zyzx2kdnpjvwdr9b83k-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/nix/store/a3a7lldql51bm2cb57173mv9q0z12dh1-rich-cli-1.8.0/lib/python3.10/site-packages/rich_cli/__main__.py", line 704, in main
    from .pager import PagerApp, PagerRenderable
  File "/nix/store/a3a7lldql51bm2cb57173mv9q0z12dh1-rich-cli-1.8.0/lib/python3.10/site-packages/rich_cli/pager.py", line 10, in <module>
    from textual.widgets import ScrollView
  File "/nix/store/4qmbz4wlx2x8xqmylansqyy5fi5m2c3w-python3.10-textual-0.9.1/lib/python3.10/site-packages/textual/widgets/__init__.py", line 62, in __getattr__
    raise ImportError(f"Package 'textual.widgets' has no class '{widget_class}'")
ImportError: Package 'textual.widgets' has no class 'ScrollView'
```

### Steps To Reproduce
1. `nix shell nixpkgs#rich-cli`
2. `rich --pager README.md`

### Expected behavior
Rich starts its pager

### Notify maintainers
@joelkoen

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.3, NixOS, 23.05 (Stoat), 23.05.20230119.d7705c0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixos, nixpkgs"`
 - channels(anselmschueler): `""`
 - nixpkgs: `/nix/store/ci0324339l5i3x7q68vigpfcf1jicsgs-source`

### PR DESCRIPTION
**Pull request by joelkoen**
###### Description of changes

Fixes #211987

 

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
You could try to override `textual` to 0.1.18. Something like that should work:

```bash
let
  python = python3.override {
    packageOverrides = self: super: {
      textual = super.textual.overrideAttrs (oldAttrs: rec {
        version = "0.1.18";
        src = oldAttrs.src.override {
          inherit version;
          sha256 = "sha256-XVmbt8r5HL8r64ISdJozmM+9HuyvqbpdejWICzFnfiw=";
        };
      });
    };
  };
in
```

**Comment by joelkoen** [comment]
Thank you, that's a much better solution. I couldn't find `src.override` in your example and have used `fetchFromGitHub` instead.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 217762` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>rich-cli</li>
  </ul>
</details>

**Review by fabaff — APPROVED** [review]
Looks good to me.

```bash
ew/pr-217762]$ ./results/rich-cli/bin/rich 
Usage: rich [OPTIONS] <PATH,TEXT,URL, or '-'>
See rich --help for options
[...]
```

**Pull request merged**
