### PR TITLE
kicad: 5.1.2 -> 5.1.4 [WIP]

### PR DESCRIPTION
**Pull request by tokudan**
###### Motivation for this change

Update kicad to current version.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tokudan** [comment]
@GrahamcOfBorg build kicad

**Comment by bjornfor** [comment]
I think it's more natural for kicad updates to land on master and not staging(-next).

**Comment by tokudan** [comment]
@bjornfor I agree, but staging-next has some pending updates for kicad and I intend to add at least one more commit, probably tomorrow to fix some issues with the spice simulation.
I have made some progress there, but the spice simulation still causes a segmentation fault.

**Comment by veprbl** [comment]
@GrahamcOfBorg eval

**Comment by tokudan** [comment]
going to reopen against master, as staging-next is currently broken.

**Pull request closed without merging**
