### PR TITLE
sudo: 1.8.25 -> 1.8.25p1 (bugfix for systems w/o ppoll)

### PR DESCRIPTION
**Pull request by dtzWill**
- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
Does this really need staging?

**Comment by xeji** [comment]
Master is still on 1.8.24, the update to 1.8.25 is in staging for whatever reason (not even staging-next yet). We could revert it on staging and do 1.8.24 -> 1.8.25p1 on master instead.

**Comment by dtzWill** [comment]
Oh I expected more to depend on this, sorry.  Please proceed as seems best! I'm good with either approach.

**Comment by xeji** [comment]
- reverted the previous bump (#46057) on staging in 5a9c9162228bc0e3d13b316ecf1578bee2cd32e1
- applied it to master in b026786e77ac4752aee44da47f0597917049dee6
- applied this to master in 2608649de70a77f13306d155a1d96a0763a09d9d

**Pull request closed without merging**
