### PR TITLE
python3Packages.imageio: 2.22.1 -> 2.22.4

### PR DESCRIPTION
**Pull request by Luflosi**
###### Description of changes
https://github.com/imageio/imageio/releases/tag/v2.22.4

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Luflosi** [comment]
Updated to the latest version.

**Comment by Luflosi** [comment]
Updated again.

**Comment by deejayem** [comment]
Result of `nixpkgs-review pr 198731` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>30 packages marked as broken and skipped:</summary>
  <ul>
    <li>intensity-normalization</li>
    <li>napari</li>
    <li>python310Packages.boxx</li>
    <li>python310Packages.bpycv</li>
    <li>python310Packages.bsuite</li>
    <li>python310Packages.caffe</li>
    <li>python310Packages.caffeWithCuda</li>
    <li>python310Packages.dm-sonnet</li>
    <li>python310Packages.intensity-normalization</li>
    <li>python310Packages.mask-rcnn</li>
    <li>python310Packages.napari</li>
    <li>python310Packages.rl-coach</li>
    <li>python310Packages.rlax</li>
    <li>python310Packages.tensorflow-datasets</li>
    <li>python310Packages.test-tube</li>
    <li>python310Packages.zcs</li>
    <li>python39Packages.boxx</li>
    <li>python39Packages.bpycv</li>
    <li>python39Packages.bsuite</li>
    <li>python39Packages.caffe</li>
    <li>python39Packages.caffeWithCuda</li>
    <li>python39Packages.dm-sonnet</li>
    <li>python39Packages.intensity-normalization</li>
    <li>python39Packages.mask-rcnn</li>
    <li>python39Packages.napari</li>
    <li>python39Packages.rl-coach</li>
    <li>python39Packages.rlax</li>
    <li>python39Packages.tensorflow-datasets</li>
    <li>python39Packages.test-tube</li>
    <li>python39Packages.zcs</li>
  </ul>
</details>
<details>
  <summary>40 packages built:</summary>
  <ul>
    <li>python310Packages.aplpy</li>
    <li>python310Packages.batchgenerators</li>
    <li>python310Packages.dask-image</li>
    <li>python310Packages.dremel3dpy</li>
    <li>python310Packages.env-canada</li>
    <li>python310Packages.glymur</li>
    <li>python310Packages.handout</li>
    <li>python310Packages.image-match</li>
    <li>python310Packages.imagecorruptions</li>
    <li>python310Packages.imageio</li>
    <li>python310Packages.moviepy</li>
    <li>python310Packages.napari-console</li>
    <li>python310Packages.napari-svg</li>
    <li>python310Packages.pims</li>
    <li>python310Packages.psd-tools</li>
    <li>python310Packages.runway-python</li>
    <li>python310Packages.scikitimage</li>
    <li>python310Packages.slicedimage</li>
    <li>python310Packages.spectral-cube</li>
    <li>python310Packages.stytra</li>
    <li>python39Packages.aplpy</li>
    <li>python39Packages.batchgenerators</li>
    <li>python39Packages.dask-image</li>
    <li>python39Packages.dremel3dpy</li>
    <li>python39Packages.env-canada</li>
    <li>python39Packages.glymur</li>
    <li>python39Packages.handout</li>
    <li>python39Packages.image-match</li>
    <li>python39Packages.imagecorruptions</li>
    <li>python39Packages.imageio</li>
    <li>python39Packages.moviepy</li>
    <li>python39Packages.napari-console</li>
    <li>python39Packages.napari-svg</li>
    <li>python39Packages.pims</li>
    <li>python39Packages.psd-tools</li>
    <li>python39Packages.runway-python</li>
    <li>python39Packages.scikitimage</li>
    <li>python39Packages.slicedimage</li>
    <li>python39Packages.spectral-cube</li>
    <li>python39Packages.stytra</li>
  </ul>
</details>

**Review by deejayem — APPROVED** [review]
Built and tested (using example from https://github.com/imageio/imageio) on x86_64-darwin

**Pull request merged**
