### PR TITLE
buckets: init at 0.71.1

### PR DESCRIPTION
**Pull request by kmogged**
## Description of changes

This adds the buckets budgeting application, which is derived from an AppImage.
https://www.budgetwithbuckets.com/changelog/

This closes issue #178623

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by bachp** [comment]
I can build but I can't run the resulting application on a x86_64 manjaro.

Also I saw that they also provide a .deb package. Is there a reason you prefered the AppImage variant?

**Comment by kmogged** [comment]
> I can build but I can't run the resulting application on a x86_64 manjaro.
> Also I saw that they also provide a .deb package. Is there a reason you prefered the AppImage variant?

Great observations @bachp 
What kind of error message was displayed for Manjaro or was there none? When I get a chance I will also spin up Manjaro and test for myself.

As far as using AppImage to build from I believe it was easier at the time. I've been running previous and this version without too many issues for some time now. The way Nix handles AppImage is that the source of the AppImage archive is unpacked. Not terribly different than .deb except for the dependencies also being shipped with the AppImage.

That being said, I'm building and running the newly released Buckets from the AppImage and noticing a strange behavior with the application not opening the first time it's started. Opening the application a second time finally starts the app, so I am considering taking the .deb file and creating a build from that, but that would be the newer version and not this one.

**Comment by kmogged** [comment]
@bachp I also forgot to ask what desktop you are running on Manjaro. Just to make sure I have equal test environment.

**Comment by bachp** [comment]
@kmogged I'm using GNOME.

**Comment by kmogged** [comment]
@bachp When I attempted running the nixpkg of buckets on fresh install of Manjaro Gnome I noticed that the fontconfig and this version were not compatible. It's attempting to use the installed version of fontconfig on Manjaro. I'm able to run the AppImage downloaded from the site with no issues, so that could be a workaround if you need the application today (chmod +x *.AppImage).

I also attempted to package up the debian version, but that introduces a lot of complexities. This is a proprietary app with no source code available, but it's an Electron app. I might be able to get this working with some time. Wrapping the AppImage is the quickest method on NixOS. I have been using the latest version, but I'm not satisfied with how I have to start the application twice to get it running.

**Comment by kmogged** [comment]
I'm closing this pull request for 4 reasons.
1. The upcoming v0.73.3 version is not backwards compatible with previous versions of the application. Once opened by v0.73.3 the budget files can no longer be opened by older versions. I'd prefer to introduce buckets to nixpkgs without a breaking change.
2. An update to NixOS broke the v0.72.2 version I'm currently using and results in blank windows. Again, I'd prefer to release with v0.73.3, which appears to resolve this issue.
3. v0.72.2 introduced a bug, which resulted in the application not opening half the time. I worked with upstream to resolve this bug, which is patched in the beta. That is why I'd prefer to wait for the v0.73.3 beta to be released as stable. Again, opting for the more stable version as first release.
4. I would also like to test and include the ARM64 version, which just released with v0.72.2

I'm hoping with all the improvements, newer electron the v0.73.3 overall works better for everyone regardless of platform.

**Pull request closed without merging**
