### PR TITLE
pythonPackages.optuna: init at 0.13.0

### PR DESCRIPTION
**Pull request by costrouc**
###### Motivation for this change

Listened to an awesome optuna talk at SciPy! So I wanted to contribute the package to nixpkgs

This closes PR #31954

###### Things done

 - pythonPackages.scikit-optimize: init at 0.6 
 - pythonPackages.optuna: init at 0.13.0 
 - pythonPackages.lightgbm: init at 2.2.3 
 - pythonPackages.cliff: init at 2.15.0 

cc: @wd15 @g-votte thanks to the awesome nix and optuna talks :smile: 

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by costrouc** [comment]
Nix review passed

Result of `nix-review pr 64642` [1](https://github.com/Mic92/nix-review)
<details>
  <summary>6 package were build:</summary>

  - python27Packages.lightgbm
  - python27Packages.scikit-optimize
  - python37Packages.cliff
  - python37Packages.lightgbm
  - python37Packages.optuna
  - python37Packages.scikit-optimize
</details>

**Comment by risicle** [comment]
For me, `python27Packages.cliff` fails to build simply because of its dependency `cmd2` being apparently broken on py27 at the moment (deja vu?).

**Comment by costrouc** [comment]
Didn't you just remove python 2.7 support for cmd2? https://github.com/NixOS/nixpkgs/pull/62998 so I don't think this is an issue

**Comment by risicle** [comment]
_That's_ what the deja vu was!

Not sure why my machine was attempting to build it - possible some stale files somewhere...

**Comment by risicle** [comment]
p.s. `lightgbm` _does_ fail to build for me on macos 10.13 - I'll see what I can do about it.

**Comment by costrouc** [comment]
Ahh gotcha. Thanks I would definitely appreciate osx support for the binary.

**Comment by risicle** [comment]
https://github.com/NixOS/nixpkgs/pull/64711

**Pull request merged**
