### PR TITLE
tree-sitter: 0.22.6 -> 0.23.0

### PR DESCRIPTION
**Pull request by ribru17**
Also updates all of the grammars, and adds some new repos to the script ignore list.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ribru17** [comment]
@Profpatsch friendly ping :) Does this look alright to you?

**Comment by DamienCassou** [comment]
@ofborg build

**Comment by DamienCassou** [comment]
nixpkgs found out that:

```
3 packages failed to build:
emacsPackages.clingo-mode emacsPackages.phpinspect supercollider_scel
```

Could you please double-check what is the status of these packages on the master branch?

**Comment by ribru17** [comment]
I believe this is unrelated; the phpinspect package now fails due to 404 in the download link (https://elpa.gnu.org/devel/phpinspect-0.0.20240819.94625.tar) which I guess was moved or something. So I think those failures are unrelated (probably depend on this package)? Just in case I will regenerate the grammars, even though I think that those failures are not affected by this bump

**Comment by DamienCassou** [comment]
I confirm the 3 packages mentioned above all fail in `master`. Let's merge this PR. Thank you @ribru17 for the work!

**Comment by ribru17** [comment]
Thank you for the quick reply, and for checking in master! Apologies for not doing the same not sure how it slipped my mind- I appreciate it!!

**Comment by vcunat** [comment]
Isn't this a too big rebuild to merge directly to master?

I believe this is the main reason why over 33k jobs are missing binaries right now.

**Comment by DamienCassou** [comment]
I'm sorry about that @vcunat, I totally forgot. I will read the contribution manual again.

**Comment by vcunat** [comment]
Moved to the `staging` branch in 565a94174fb0eb25f13830e2163bc72dbd7e9251.

**Pull request merged**
