### PR TITLE
fixup awsebcli: update botocore to match nixpkgs

### PR DESCRIPTION
**Pull request by kirillrdy**
###### Description of changes

fix build of awsebcli on master after recent version bump of python3.pkgs.botocore

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kirillrdy** [comment]
cc @mweinelt 

this is a quick fix for master

**Comment by mweinelt** [comment]
We will have to repeat this dance more often if you pin versions so strict.

**Comment by kirillrdy** [comment]
> We will have to repeat this dance more often if you pin versions so strict.
> 
> Also the commit message does not match the contributing guidelines.

@mweinelt thank you looking at this, I know you are overwhelmed  with PRs

- fixing version requirements this strict was deliberate choice done by me, so that I test each version bump, I've mentioned this in PR https://github.com/NixOS/nixpkgs/pull/181906 that you cherry-picked into python-updates
- apologies, i have never read contributing guidelines, i just roughly followed what I saw from other PRs I will adjust accordingly once I read the guidelines

Also if you can suggest better workflow for me to keep awsebcli uptodate and working, i am happy to hear any suggestions. So far I am just following master/staging/python-updates.

otherwise, thank you and good time of day to you

**Comment by kirillrdy** [comment]
@mweinelt I have adjusted version requirement to match upcoming release from upstream
https://github.com/aws/aws-elastic-beanstalk-cli/blob/master/requirements.txt

I've also adjusted the commit message to ( what i think ) is following contribution guidelines

github is showing @mweinelt  status as "busy", I am not sure what it means, but just in case I can ask @happysalada to have a look at this MR as well

thank you both in advance

**Pull request merged**
