### PR TITLE
nixos/dokuwiki: add missing option enable

### LINKED ISSUE #139853: The interface of the Dokuwiki module has been updated without providing any migration hints
### Describe the bug

https://github.com/NixOS/nixpkgs/pull/132551 heavily changes the interface of the Dokuwiki NixOS module without providing any hints about which actions should be taken to properly migrate.

All you get after bumping your nixpkgs pin is

```
error: The option `services.dokuwiki.REDACTED.enable' does not exist. Definition values:
       - In `<unknown-file>': true
(use '--show-trace' to show detailed location information)
```

This is not a helpful error message.

We should provide some indication about how to migrate from the 21.05-compliant conf to this new webserever-independent interface through a eval-time warning message. Worst case scenario, we should at least point to the release notes. See https://nixos.org/manual/nixos/stable/index.html#sec-assertions for more information about how to emit such a warning. We should list all the deleted/moved options and trigger a helpful warning for each of them.

We should address this before the ~21.09~ 21.11 branchoff.

Edit: I indeed meant 21.11 branchoff here.

cc @happysalada @onny @1000101.

### PR DESCRIPTION
**Pull request by onny**
###### Motivation for this change
This small addition fixes a migration issue for the Dokuwiki module. Fixes https://github.com/NixOS/nixpkgs/issues/139853

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NinjaTrappeur** [comment]
Still not good.

```
error: The option `services.dokuwiki.REDACTED-HOSTNAME.hostName' does not exist. Definition values:
       - In `<unknown-file>': "REDACTED-HOSTNAME"
```

With this conf:

```
    dokuwiki = {
      "REDACTED-HOSTNAME" = {
        enable = true;
        hostName = "REDACTED-HOSTNAME";
        # Permissions cheat sheet
        #
        # 0: no permission
        # 1: read
        # 2: edit
        # 3: create
        # 4: upload
        # 5: delete
        # 6: admin
        #
        # Special groups:
        # @ALL: unregistered users
        # @users: registered users
        acl = ''
          * @ALL 0
          * @users 4
          * @admin 6
          wiki:* @ALL 1
          wiki:* @admin 6
          public:* @ALL 1
          public:* @users 4
          public:* @admin 6
        '';
        usersFile = "/var/lib/dokuwiki/users";
        extraConfig = ''
          $conf['title'] = "REDACTED Wiki";
          $conf['hidepages'] = '^:(public*)';
          $conf['disableactions'] = 'register';
        '';
        # Let's generate that with our own webroot.
        nginx = {
         addSSL = true;
         sslCertificate = "/var/lib/acme/REDACTED-HOSTNAME/fullchain.pem";
         sslCertificateKey = "/var/lib/acme/REDACTED-HOSTNAME/key.pem";
         locations = {
           "/.well-known/acme-challenge" = {
             root = "/var/www/REDACTED-HOSTNAME/";
           };
          };
        };
      };
    };
```

**Comment by NinjaTrappeur** [comment]
Right, I had a quick scan through the module.

Another issue we'll have is that we removed the Nginx-specific configuration from this module.

In my use case, the generic Nginx conf won't be good enough, I need to redirect the acme endpoint (`.well-known/acme-challenge`) to the appropriate acme dir. The previous API was allowing me to do that directly through the `dokuwiki` config. The extra config was injected when the new virtual host was created.

I injected that through my generic nginx config, but to do that, I had to:

1. Read through the module.
2. Understand how the nginx virtualhost was created.
3. Predict the virtualhost name and override the generic definition.

**Comment by NinjaTrappeur** [comment]
Hhhm, I can't come with a immediate fix for these two issues. I'll let that rest for a bit.

**Comment by happysalada** [comment]
Thinking some more about it, the ideal situation I think for things that can be exposed would be to have an attribute for each proxy. a bit like https://github.com/NixOS/nixpkgs/blob/nixos-21.05/nixos/modules/services/web-apps/jitsi-meet.nix#L132
so something like
```
options.nginx = {
   enable ...
   nginx_specific options...
}
options.caddy = {
  enable ...
  caddy specific
}
```
trying to have a common interface does not seem straightforward nor intuitive.
I think it's still valuable to have some default configurations that are usable, to give an idea of what is needed for the service. Whoever doesn't like the default config can take the things they like from the default and copy them. 

The one problem I didn't realise before is that what if people want to disable the reverse proxy and use their own settings. I didn't see reading the module a way to do that easily.

**Comment by happysalada** [comment]
@onny let me know if you are short on time (no worries at all), I can make the follow up PR. We wouldn't want to miss the 21.11 release.

**Comment by onny** [comment]
> @onny let me know if you are short on time (no worries at all), I can make the follow up PR. We wouldn't want to miss the 21.11 release.

Yeah sorry I'm short on time, would be really glad if you could fix this!

**Comment by happysalada** [comment]
follow up PR https://github.com/NixOS/nixpkgs/pull/144168

**Pull request merged**
