### PR TITLE
qadwaitadecorations: init at 0.1.3

### LINKED ISSUE #257869: Package request: QAdwaitaDecorations
**Project description**
 Qt decoration plugin implementing Adwaita-like client-side decorations  (Replacement for [QGnomePlatform](https://github.com/FedoraQt/QGnomePlatform#qgnomeplatform))

**Metadata**

* homepage URL: https://github.com/FedoraQt/QAdwaitaDecorations
* source URL: https://github.com/FedoraQt/QAdwaitaDecorations
* license: LGPL2.1
* platforms: linux

### PR DESCRIPTION
**Pull request by SamLukeYes**
## Description of changes

Fixes https://github.com/NixOS/nixpkgs/issues/257869

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SamLukeYes** [comment]
Tested with Shotcut (Qt5) and OBS Studio (Qt6):
```nix
{
  qt = {
    enable = true;
    waylandDecoration = "adwaita";
  };
}
```
截图 2023-11-01 21-16-13
截图 2023-11-01 21-16-36

With Qt5 shadows support:
```nix
{
  nixpkgs.overlays = [
    (final: prev: {
      qadwaitadecorations = prev.qadwaitadecorations.override {
        qtwayland = final.qtwayland-patched;
        qt5ShadowsSupport = true;
      };
      qtwayland-patched = final.qt5.qtwayland.overrideAttrs (old: {
        patches = old.patches ++ [
          (final.fetchpatch {
            url = "https://src.fedoraproject.org/rpms/qt5-qtwayland/raw/rawhide/f/qtwayland-decoration-support-backports-from-qt6.patch";
            hash = "sha256-BmSVhQSJ1IRZujAUbdi9lIM7f59OOQPXctig+w7dri8=";
          })
        ];
      });
    })
  ];
  system.replaceRuntimeDependencies = [({
    original = pkgs.qt5.qtwayland;
    replacement = pkgs.qtwayland-patched;
  })];
}
```
截图 2023-11-01 21-12-03
截图 2023-11-01 21-11-21

**Comment by SamLukeYes** [comment]
图片
Seems to be a bit buggy on Qt5. The minimize and maximize buttons don't render :confused:

**Comment by SamLukeYes** [comment]
Giving up the modules for now, because using `qgnomeplatform` for Qt5 and `qadwaitadecorations-qt6` for Qt6 seems ideal for me. Adding `qadwaitadecorations-qt6` and `qt6.qtsvg` to `environment.systemPackages` and setting the environmental variable `QT_WAYLAND_DECORATION=adwaita` should work.

**Comment by pbsds** [comment]
Result of `nixpkgs-review pr 264774` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>qadwaitadecorations</li>
    <li>qadwaitadecorations-qt6</li>
  </ul>
</details>



- [ ] package path fits guidelines
  * `by-name` + an entry in `all-packages.nix` doesn't strike me as sound, please move it out of `by-name`
- [x] package name fits guidelines
- [x] package version fits guidelines
- [x] package builds on x86_64-linux
- [x] executables tested on x86_64-linux
- [x] `meta.description` is set and fits guidelines
- [x] `meta.license` fits upstream license
- [x] `meta.platforms` is set
- [x] `meta.maintainers` is set
- [x] build time only dependencies are declared in `nativeBuildInputs`
- [x] source is fetched using the appropriate function
- [x] the list of `phases` is not overridden
- [x] when a phase (like `installPhase`) is overridden it starts with `runHook preInstall` and ends with `runHook postInstall`.
- [x] patches have a comment describing either the upstream URL or a reason why the patch wasn't upstreamed
- [x] patches that are remotely available are fetched rather than vendored

---

Seems to run fine. With:
image

Without:
image

**Comment by sund3RRR** [comment]
Is it possible to make this work on KDE plasma?

**Comment by dukzcry2** [comment]
> Is it possible to make this work on KDE plasma?

Probably #324525 Most likely plugin is just not loaded for some uncertain reason

**Pull request merged**
