### PR TITLE
 nixos/chromium: add enablePlasmaBrowserIntegration option 

### LINKED ISSUE #85342: Chromium extension that uses native messaging does not work
**Describe the bug**
[Plasma Integration](https://chrome.google.com/webstore/detail/plasma-integration/cimiefiiaegbelhefglklhhakcgmhkai) addon in chromium does not work.

After install addon show errors: "**Failed to connect to the main process.**"

"_Verify the installation of the plasma-browser-integration package. The running environment of the Plasma desktop environment must be at least version 5.13._"

"**Specified native messaging host not found.**"

Manually run `plasma-browser-integration-host` from console not help.

**To Reproduce**
1.  Add to `configuration.nix`:
```
{ config, pkgs, lib, ... }:

with lib;

{
environment.systemPackages = (with pkgs; [
    chromium
  ]);
  programs.chromium = {
    enable = true;
    extensions = [
      "cimiefiiaegbelhefglklhhakcgmhkai" # Plasma integration
    ];
  };
}
```
2. `nix-channel --update nixos; nixos-rebuild switch`
3. run `chromium`

**Expected behavior**
No errors.

**Additional context**
I found issue #47340 Everything looks like the same problem but in chromium

**Notify maintainers**

**Metadata**
Please run nix-shell -p nix-info --run "nix-info -m" and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.31, NixOS, 20.09pre-git (Nightingale)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Description of changes

Closes #85342

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
@K900 can you have look?

**Comment by NovaViper** [comment]
Hey could you also add support for Vivaldi? It too is based on Chromium and has a specific path for the native host messaging host like how Brave does

**Comment by SuperSandro2000** [comment]
I don't use vivaldi and don't have the time to verify them. Please create a separate PR.

---

@K900 so what do we do about this?

**Comment by SuperSandro2000** [comment]
Updated to work with Plasma 6 from #286522

**Comment by yisraeldov** [comment]
It would probably be better if the formatting was done in a spearate PR, makes it hard to see what was changed.

**Review by pbsds — APPROVED** [review]
had to review commit-by-commit, but the diff LGTM

**Comment by SuperSandro2000** [comment]
> It would probably be better if the formatting was done in a spearate PR, makes it hard to see what was changed.

I can move it to an extra commit but doing in  a separate PR is way to much hassle.

**Comment by pbsds** [comment]
@ofborg test chromium

**Comment by pbsds** [comment]
aarch64-linux failed (timeout?) building chromium, LGTM

**Pull request merged**
