### PR TITLE
edk2: fix build on x86_64-darwin

### PR DESCRIPTION
**Pull request by reckenrode**
ZHF #199919

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by RaitoBezarius — APPROVED** [review]
LGTM as we were already hardcoding LLVM toolchain.

**Comment by reckenrode** [comment]
I ended up adding OVMF and edk2-uefi-shell to the PR since they depend on edk2. I can split them out, but the separate PRs wouldn’t be buildable until this one landed.

**Comment by RaitoBezarius** [comment]
Seems fair to me.

**Comment by mweinelt** [comment]
Can someone check why ofBorg is unhappy?

**Comment by RaitoBezarius** [comment]
> Can someone check why ofBorg is unhappy?

For Darwin:
```
xcode-select: error: no developer tools were found at '/Applications/Xcode.app', and no install could be requested (perhaps no UI is present), please install manually from 'developer.apple.com'.
```
It seems unrelated to the PR and more an ofborg issue itself.

For aarch64-linux, just after VM boot, the command pipe is broken, I do not have aarch64 to reproduce, but it could be some regression due to this PR building a corrupted OVMF firmware, we should investigate.

**Comment by reckenrode** [comment]
Looking at the [full log][1], there’s a message about running out of space. Is that expected?

```
[Errno 28] No space left on device: '/nix/store/dg7z7wnyy2wv1w97vqm946z9fr2y6n0l-initrd-linux-5.15.77/initrd' -> '/boot/efi/nixos/dg7z7wnyy2wv1w97vqm946z9fr2y6n0l-initrd-linux-5.15.77-initrd.efi'
```

[1]: https://logs.nix.ci/?key=nixos/nixpkgs.199940&attempt_id=914a5950-f49f-4e7d-8c78-b2c556198761

**Comment by RaitoBezarius** [comment]
> Looking at the [full log](https://logs.nix.ci/?key=nixos/nixpkgs.199940&attempt_id=914a5950-f49f-4e7d-8c78-b2c556198761), there’s a message about running out of space. Is that expected?
> 
> ```
> [Errno 28] No space left on device: '/nix/store/dg7z7wnyy2wv1w97vqm946z9fr2y6n0l-initrd-linux-5.15.77/initrd' -> '/boot/efi/nixos/dg7z7wnyy2wv1w97vqm946z9fr2y6n0l-initrd-linux-5.15.77-initrd.efi'
> ```

This is a classical issue with these macOS builders I think, cc @grahamc

**Comment by LunNova** [comment]
@reckenrode edk2-uefi-shell still seems to be failing on hydra for aarch64-darwin. I don't have a darwin machine, are you able to look into it?

**Comment by reckenrode** [comment]
@LunNova I’ll take a look at it. The other edk2 packages don’t support aarch64-darwin, so the fix may be to limit edk2-uefi-shell similarly.

**Comment by reckenrode** [comment]
I checked the [job report][1] for nixpkgs-22.05-darwin, but I don’t see any failures for edk2-uefi-shell. It also won’t build locally due to being an unsupported platform, which is what I should expect. Can you help point me in the right direction to where you’re seeing the failure on Hydra?

[1]: https://malob.github.io/nix-review-tools-reports/

**Comment by LunNova** [comment]
Sorry that should've been x86_64-darwin not arrch64-darwin.

<https://hydra.nixos.org/build/198166720>

**Comment by RaitoBezarius** [comment]
> Sorry that should've been x86_64-darwin not arrch64-darwin.
> 
> https://hydra.nixos.org/build/198166720

It really seems to be an orthogonal issue due to the Apple environment, I think.

**Comment by reckenrode** [comment]
I was able to reproduce the problem by disabling sandboxing. `edksetup.sh` uses `whereis` to locate Python, which picks up `/usr/bin/python3` when sandboxing is disabled on Darwin. I opened https://github.com/NixOS/nixpkgs/pull/201095 with a fix.

**Pull request merged**
