### PR TITLE
strelka: init 2.9.5

### PR DESCRIPTION
**Pull request by jbedo**
###### Motivation for this change

Strelka init at version 2.9.5.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jtojnar** [comment]
It would be preferable to package the dependncies in `redist` and use them instead of awkwardly patching them in `postFixup`.

**Comment by jbedo** [comment]
I agree in general, however in this case the awkward patch would still remain (albeit applied at a different time) as it is hardcoded into pyflow. It would obviate the need to recompile the file after the patch, though.

As for splitting out the packages in redist, some of them already do exist in nixpkgs. However, in the interest of reproducible science I'm hesitant to use this over the bundled code: when we write in a paper that strelka 2.9.5 was used to call variants, it should be as close to the release of Illumina as possible.

Is it preferable to split out the compilation of the redist packages as separate expressions in a let binding for the strelka package and then hack the cmake system to use these instead? I'm not sure this improves anything, it's just making nix build them instead of cmake.

**Comment by joachifm** [comment]
@GrahamcOfBorg build strelka

**Comment by jbedo** [comment]
I have changed platforms to only x86_64-linux.

**Pull request merged**
