### PR TITLE
elmPackages: Updates Elm node packages to latest versions.

### PR DESCRIPTION
**Pull request by akoppela**
###### Motivation for this change

Updated Elm node packages to the latest versions. This operation is automatic and done with existing script. No manual changes were done.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by turboMaCk** [comment]
@GrahamcOfBorg build elmPackages

**Comment by turboMaCk** [comment]
It seems will require some manual work:

```
error: build of '/nix/store/xgs51zcl385jpgl0gjax43kmapcpxvdl-node_elm-review-2.4.0.drv' failed
```

There is also this PR in progress https://github.com/NixOS/nixpkgs/pull/110813#pullrequestreview-575830796 which will allow us to reuse node-env.nix. I don't think this upgrade is necessarily blocked by that.

a. You can fix the build of elm-review
b. If you don't want to spend time on this you can close the PR and I'll open new one myself once #110813 is in

**Comment by turboMaCk** [comment]
I had a brief looks and to me it seems

1. elm-review removed npm dependecy on binwrap.
2. elm-json is still a dependecy but it's not downloaded on installation but rather when elm-review starts.

The simplest way to solve this is to remove `patchBinwrap` call for elm review. The downside is that that way we would let elm-review to fetch it's own elm-json binary and not the one we build as a part of package set.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110845` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>elmPackages.elm-review: log <a href="https://termbin.com/pbyl">https://termbin.com/pbyl</a></li>
  </ul>
</details>
<details>
<summary>
10 packages built:
</summary>
<ul>
<li>elmPackages.create-elm-app</li>
<li>elmPackages.elm-analyse</li>
<li>elmPackages.elm-coverage</li>
<li>elmPackages.elm-doc-preview</li>
<li>elmPackages.elm-language-server</li>
<li>elmPackages.elm-live</li>
<li>elmPackages.elm-optimize-level-2</li>
<li>elmPackages.elm-test</li>
<li>elmPackages.elm-upgrade</li>
<li>elmPackages.elm-verify-examples</li>
</ul>
</details>

**Comment by akoppela** [comment]
Thank you sirs!

**Pull request closed without merging**
