### PR TITLE
ente-auth: 4.0.2 -> 4.1.6

### PR DESCRIPTION
**Pull request by niklaskorz**
Changelogs (4.1.1-4.1.4 were either pre-releases or not released at all):

- https://github.com/ente-io/ente/releases/tag/auth-v4.1.0
- https://github.com/ente-io/ente/releases/tag/auth-v4.1.5
- https://github.com/ente-io/ente/releases/tag/auth-v4.1.6

~~Note that due to a rename of the binary in upstream, this update is not backwards compatible. A security fix from 4.1.0 has been backported to NixOS 24.11 here: https://github.com/NixOS/nixpkgs/pull/363985~~

The old binary name has been symlinked for backwards compatibility.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by niklaskorz** [comment]
> sqflite

Yup that's where I am stuck, any idea what might cause the mismatch?

**Comment by gepbird** [comment]
> > Currently in draft mode as it does not build yet.
> 
> ```
> error: hash mismatch in fixed-output derivation '/nix/store/ihbvpyw1ammkfxj1jzwyx1vm0vb5z5jb-pub-sqflite-2.3.3+2.drv':
>          specified: sha256-TdvCtEO7KL1R2oOSwGWllmS5kGCIU5CkvvUqUJf3tUc=
>             got:    sha256-+XTVtkFJ94VifwnutvUuAqqiyWwrcEiZ3Uz0H4D9zWA=
> error: hash mismatch in fixed-output derivation '/nix/store/qx291zbh1gvkgbjv5gkkm0507fhb2987-source.drv':
>          specified: sha256-6fJ0OAZ9p8+zanPl39p3VX9xUMGV47klcwfEnwyRX98=
>             got:    sha256-ytKGRsBhKD/GfaWiFvhT0g+UzG7mZI100Ws1GBibsxI=
> ```

I got these hashes too, not sure why they changed, last update to the auth-v4.1.0 branch was 2 weeks ago.

**Comment by niklaskorz** [comment]
Updated to 4.1.6, fixed build issues and also added a release not for 25.05.

**Comment by niklaskorz** [comment]
I'm not sure how I originally came to the conclusion the data directory was renamed, but after testing 4.1.6, the data directory is `$XDG_DATA_HOME/io.ente.auth` before _and_ after update, so downgrading is possible from 4.1.0+ to 4.0.2 after all.

**Review by gepbird — APPROVED** [review]
Changes LGTM, tested on x86_64-linux. Switching between versions works well, and thanks a lot for patching out the annoying update popup!

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 357503`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 1 package blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 3 packages built:</summary>
  <ul>
    <li>ente-auth</li>
    <li>ente-auth.debug</li>
    <li>ente-auth.pubcache</li>
  </ul>
</details>

**Comment by niklaskorz** [comment]
One last change as I just realized the desktop name does not match the app id that Ente Auth uses for its XDG surface, thus failing to assign the taskbar icon when the app is running. I assume this has something to do with how `buildFlutterApplication` works and is also the reason the data directory has the same name as before (which is a good thing imho).

**Review by gepbird — APPROVED** [review]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 357503`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 3 packages built:</summary>
  <ul>
    <li>ente-auth</li>
    <li>ente-auth.debug</li>
    <li>ente-auth.pubcache</li>
  </ul>
</details>

**Review by schnow265 — APPROVED** [review]

**Pull request merged**
