### PR TITLE
python310Packages.scikit-build-core: 0.2.0 -> 0.4.8

### PR DESCRIPTION
**Pull request by natsukium**
## Description of changes

Changelog: https://github.com/scikit-build/scikit-build-core/releases/tag/v0.4.8

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by natsukium** [comment]
Result of `nixpkgs-review` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages failed to build:</summary>
  <ul>
    <li>python310Packages.coffea</li>
    <li>python310Packages.coffea.dist</li>
    <li>python310Packages.laspy</li>
    <li>python310Packages.laspy.dist</li>
    <li>python310Packages.laszip</li>
    <li>python310Packages.laszip.dist</li>
    <li>python311Packages.laspy</li>
    <li>python311Packages.laspy.dist</li>
    <li>python311Packages.laszip</li>
    <li>python311Packages.laszip.dist</li>
  </ul>
</details>
<details>
  <summary>18 packages built:</summary>
  <ul>
    <li>python310Packages.awkward</li>
    <li>python310Packages.awkward-cpp</li>
    <li>python310Packages.awkward-cpp.dist</li>
    <li>python310Packages.awkward.dist</li>
    <li>python310Packages.dask-awkward</li>
    <li>python310Packages.dask-awkward.dist</li>
    <li>python310Packages.mplhep</li>
    <li>python310Packages.mplhep.dist</li>
    <li>python310Packages.scikit-build-core</li>
    <li>python310Packages.scikit-build-core.dist</li>
    <li>python310Packages.uproot</li>
    <li>python310Packages.uproot.dist</li>
    <li>python310Packages.vector</li>
    <li>python310Packages.vector.dist</li>
    <li>python311Packages.awkward-cpp</li>
    <li>python311Packages.awkward-cpp.dist</li>
    <li>python311Packages.scikit-build-core</li>
    <li>python311Packages.scikit-build-core.dist</li>
  </ul>
</details>

**Comment by veprbl** [comment]
```
      ERROR: Could not find a version that satisfies the requirement hatchling (from versions: none)
      ERROR: No matching distribution found for hatchling
```
(From ofborg failures)

**Comment by risicle** [comment]
I see the same failure on linux x86_64.

**Comment by natsukium** [comment]
Thanks, I'll fix it later.

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 246143` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python310Packages.coffea</li>
    <li>python310Packages.coffea.dist</li>
  </ul>
</details>
<details>
  <summary>26 packages built:</summary>
  <ul>
    <li>python310Packages.awkward</li>
    <li>python310Packages.awkward-cpp</li>
    <li>python310Packages.awkward-cpp.dist</li>
    <li>python310Packages.awkward.dist</li>
    <li>python310Packages.dask-awkward</li>
    <li>python310Packages.dask-awkward.dist</li>
    <li>python310Packages.laspy</li>
    <li>python310Packages.laspy.dist</li>
    <li>python310Packages.laszip</li>
    <li>python310Packages.laszip.dist</li>
    <li>python310Packages.mplhep</li>
    <li>python310Packages.mplhep.dist</li>
    <li>python310Packages.scikit-build-core</li>
    <li>python310Packages.scikit-build-core.dist</li>
    <li>python310Packages.uproot</li>
    <li>python310Packages.uproot.dist</li>
    <li>python310Packages.vector</li>
    <li>python310Packages.vector.dist</li>
    <li>python311Packages.awkward-cpp</li>
    <li>python311Packages.awkward-cpp.dist</li>
    <li>python311Packages.laspy</li>
    <li>python311Packages.laspy.dist</li>
    <li>python311Packages.laszip</li>
    <li>python311Packages.laszip.dist</li>
    <li>python311Packages.scikit-build-core</li>
    <li>python311Packages.scikit-build-core.dist</li>
  </ul>
</details>

**Comment by natsukium** [comment]
I disabled some tests because the build failure on linux was caused by network access using pip.

coffea, laszip and laspy seem to be broken regardless of this update.
https://hydra.nixos.org/eval/1798015?filter=coffea&compare=1798007&full=#tabs-still-fail
https://hydra.nixos.org/eval/1798015?filter=laszip&compare=1798007&full=#tabs-still-fail
https://hydra.nixos.org/eval/1798015?filter=laspy&compare=1798007&full=#tabs-still-fail

**Comment by veprbl** [comment]
@GrahamcOfBorg build python3Packages.coffea

**Review by tjni — APPROVED** [review]
Thank you for keeping this package current.

**Review by veprbl — APPROVED** [review]

**Pull request merged**
