### PR TITLE
[20.09] Switch latest kernel to 5.10

### PR DESCRIPTION
**Pull request by NeQuissimus**
###### Motivation for this change
The 5.8 and 5.9 kernels have been EOL'd.
5.10 has been on master for a while now (I have been using it daily since 5.10.1)

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [X] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NeQuissimus** [comment]
@ofborg test kernel-latest kernel-lts latestKernel.login

**Comment by NeQuissimus** [comment]
@ofborg test kernel-latest kernel-lts latestKernel.login

**Comment by NeQuissimus** [comment]
@ofborg test kernel-latest kernel-lts latestKernel.login latestKernel.hardened

**Comment by NeQuissimus** [comment]
I cannot figure out why ofborg fails building 5.10.5.a for the test on x64... I am posting this from 5.10.5.a on an x64 :)

**Comment by lheckemann** [comment]
```
chmod: missing operand after 'u-w'
Try 'chmod --help' for more information.
```
Maybe you didn't backport the fix from 3088dcb148e8110aa6102e8c3a2c7ee5af1348f1 correctly?

**Comment by jonringer** [comment]
IIRC there was a lot of kernel modules which aren't support in 5.10.

However, people should be using an LTS kernel if they want LTS behavior

**Comment by NeQuissimus** [comment]
@lheckemann Ah, that might be it

**Comment by NeQuissimus** [comment]
@ofborg test kernel-latest kernel-lts latestKernel.login latestKernel.hardened

**Comment by NeQuissimus** [comment]
@ofborg test kernel-latest kernel-lts latestKernel.login latestKernel.hardened

**Review by jonringer — APPROVED** [review]
diff and intention LGTM

but this should target staging-20.09, as it does 1000+ rebuilds (I'm assuming most of these are kernel modules), but then we can stabilize failing modules as well.

**Review by Atemu — CHANGES_REQUESTED** [review]
20.09's ZFSs are not compatible with 5.10.

We should at least backport https://github.com/NixOS/nixpkgs/pull/108646 to zfsUnstable before we bump _latest.

**Comment by NeQuissimus** [comment]
Rebased onto `staging-20.09`

**Comment by lheckemann** [comment]
Backported 2.0.1 bump as well: c0216833f23c756615995e6d3b1af40bfae05904

**Pull request merged**
