### PR TITLE
zfs: 0.7.12 -> 0.7.13

### PR DESCRIPTION
**Pull request by Mic92**
(cherry picked from commit b57080d34136fd8dcc49632696ceb5ed1ff73326)

###### Motivation for this change

cc @clefru regarding your question, personally I found rebasing a patch with
git easier then having a patch file in nixpkgs itself.
However we could also move the zfs fork to a more official place, what do you think?

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg test zfs

**Comment by Mic92** [comment]
Mhm. now that I run the tests I get a build error.

**Comment by Mic92** [comment]
Ah, spl also needs an upgrade.

**Comment by markuskowa** [comment]
duplicate https://github.com/NixOS/nixpkgs/pull/56882?

**Comment by Mic92** [comment]
Yeah. Also I still prefer git because it is easier to update.

**Comment by Mic92** [comment]
Tests run on my machine.

**Review by markuskowa — APPROVED** [review]
I can confirm that the test runs successfully.

**Pull request merged**
