### PR TITLE
[WIP] ngspice: Update to version 27

### PR DESCRIPTION
**Pull request by bgamari**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by c0bw3b** [comment]
The licensing situation is quite a mess but according to [COPYING](https://sourceforge.net/p/ngspice/ngspice/ci/master/tree/COPYING) the `meta.license` list should include `bsd3` + `lgpl21` + `publicDomain` + `gpl2`

**Comment by c0bw3b** [comment]
It does build successfully with `nox-review pr` but it looks like some things are missing:

```shell
/nix/store/zay1xfzva3mhmwii8x8w6hkkq8356zzh-ngspice-27
├── [4.0K]  bin
│   └── [ 93K]  cmpp
├── [4.0K]  include
```

Where current v26 contains:
```shell
/nix/store/59vc3jd4fii2c1s79q6y2rcc6qj72pnc-ngspice-26/
├── [4.0K]  bin
│   ├── [ 97K]  cmpp
│   ├── [ 12K]  ngmakeidx
│   ├── [ 47K]  ngmultidec
│   ├── [722K]  ngnutmeg
│   ├── [ 21K]  ngproc2mod
│   ├── [ 86K]  ngsconvert
│   └── [5.7M]  ngspice
├── [4.0K]  lib
│   └── [4.0K]  ngspice
```

**Comment by bgamari** [comment]
Indeed; moreover KiCad `master` segfaults when linked against it. Things are clearly not alright.

**Comment by bgamari** [comment]
The `ngspice` derivation is now at 27 due to 9e3690e87ca2eb39f0fb8960a08d27583192aae3. `libngspice` still need to be updated, however, before this can happen we'll need to sort out the segfaults I noted above.

**Pull request closed without merging**
