### PR TITLE
Update wine{stable,unstable,staging,mono}

### PR DESCRIPTION
**Pull request by tadeokondrak**
###### Motivation for this change

Wine 4 was released.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by worldofpeace** [comment]
@GrahamcOfBorg build wine

**Comment by avnik** [comment]
@worldofpeace ping!

**Comment by worldofpeace** [comment]
Testing this today :+1:

**Comment by ikervagyok** [comment]
just found this as i wanted to create a pr myself ;)
can you update to wine staging and unstable to 4.1? (https://github.com/ikervagyok/nixpkgs/commit/34fc22004f7aac8bd97694a0fb4fa183efd1be5e)

**Comment by ikervagyok** [comment]
wine is at 4.2 now, as is staging

**Review by lheckemann — APPROVED** [review]
Tested by running GNU hello (`pkgsCross.mingw32.hello`) with each wine version.

**Pull request merged**
