### PR TITLE
nixos/matomo: option for geolocation support

### PR DESCRIPTION
**Pull request by mmilata**
Adds option that:

 * enables `services.geoip-updater.enable`
 * checks that the city database is among the updated databases
 * symlinks the database to matomo dataDir

###### Motivation for this change
Main motivation is to automate the symlink creation. Also #64759.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @florianjacob @aanderse @dasJ

### CODE REVIEW

**Comment by dasJ** [comment]
Doesn't this conflict with #55867?

**Comment by mmilata** [comment]
@dasJ thanks, I had no idea that the downloaded databases are outdated. Closing this.

[For future reference: this may not even need an option, we create the symlink unconditionally (Matomo treats broken symlink as no database) and add to the manual that the geoip updater needs to be enabled for geolocation.]

**Comment by aanderse** [comment]
@dasJ your PR we merged for that php library... does that do the same thing? What is needed to get that working? Is that another avenue we could pursue?

**Comment by mmilata** [comment]
Ah, I misunderstood, the GeoLite2 databases (which Matomo uses) are *not* outdated. However starting next year the current download mechanism will not work and registration will be required in order to download it: https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

**Comment by dasJ** [comment]
@aanderse The library is used to accelerate access to the GeoIP databases. Without the module, pure PHP code is used which is slower.

**Comment by aanderse** [comment]
@dasJ ok so it is just another (faster) method to access the data... but you still need the data. Thanks for clarifying.

**Pull request closed without merging**
