### PR TITLE
oxidized: 0.26.3 -> 0.29.1

### PR DESCRIPTION
**Pull request by NetaliDev**
###### Description of changes

<del>This PR updates oxidized to version 0.29.1 and splits it into multiple packages. This is necessary, because `oxidized` and `oxidized-script` now require a different version of a dependency.</del>

This PR updates `oxidized`, fixes the `oxidized-script` executable and removes the non existing `oxidized-web` executable (`oxidized-web` is just a library for `oxidized` and does not provide a executable).

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by nicknovitski — APPROVED** [review]
This seems fine. Maybe modify the descriptions of the new packages to explain their purposes more clearly? I can't tell what I would do with the "oxidized" binary and what i would do with "oxidized-cli".

**Comment by NetaliDev** [comment]
Now each package has its own description

**Comment by yu-re-ka** [comment]
Some notes:

- as it is this is a breaking change and can not be backported

- it would be possible to create a `buildEnv` to continue providing all binaries under the `oxidized` attribute

**Comment by NetaliDev** [comment]
I just recognized that the `oxidized-script` and `oxidized-web` executables are broken at the moment (also on current unstable and release-22.11). This has the following reasons:

- The name of the `oxidized-script` executable is `oxs` and because of that, it currently is a broken symlink.
- `oxidized-web` does not provide a executable at all, it is just a library used by `oxidized` itself.

I try to figure out a solution. Until then, this PR is a draft.

**Comment by NetaliDev** [comment]
Oookay, I found out that the rubygems-version of `oxidized-script` was not up2date and so now we use the latest source version and it seems to work fine. So no splitting is necessary. I have now also fixed the executable names.

**Pull request merged**
