### PR TITLE
dirvish: init at 1.2.1 

### PR DESCRIPTION
**Pull request by winpat**
###### Motivation for this change
Dirvish is a battle proof wrapper around rsync.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by thefloweringash** [comment]
I packaged this for my backup server, but never got around to upstreaming it. Now that I re-read it, I find some bugs, but maybe it would still be useful to compare? https://gist.github.com/thefloweringash/1f44500cc22116558382efb1555d7dff

**Comment by winpat** [comment]
@thefloweringash Cool! I will have a look at your gist tomorrow in detail.

**Comment by winpat** [comment]
@thefloweringash This is my first time working with Nix and I'm learning quite a bit from your solution. Thanks for that!

1. Is it ok with you if I reuse large parts of your dirvish.nix and module.nix?
2. If so, since you already did the heavy lifting would you like to be mentioned in the `meta.maintainers` attribute?
3. You also mentioned, that you've seen some bugs while re-reading it.  Would you mind to elaborate on that (I would be more than happy to fix them)?

**Comment by thefloweringash** [comment]
@winpat 

1. Absolutely! Thank you for up-streaming this.
2. I don't mind much either way. I contribute where I can but haven't taken maintainership of anything yet.
3. Things I noticed wrong with my version:
   - `executables` and `manpages` include strings with spaces and rely on shell word splitting. Should be `[ "a" "b" ]`, not `[ "a b" ]`.
   - `rsync` is an unused buildInput. It's runtime only, and added via an explicit wrapper.
   - `cat a` followed by `cat b` might as well just be `cat a b`
   - `buildPhase` creates `$out/bin`, which it doesn't use, then `installPhase` also creates it.

**Comment by winpat** [comment]
I've fixed and tested the mentioned points. I will submit the dirvish service options in a separate PR due to time constraints.

**Pull request merged**
