### PR TITLE
ruby: 2.7.5 -> 2.7.6, 3.0.3 -> 3.0.4, 3.1.1 -> 3.1.2

### PR DESCRIPTION
**Pull request by jboyens**
###### Description of changes
Bump patch versions for CVEs

https://www.ruby-lang.org/en/news/2022/04/12/ruby-2-7-6-released/
https://www.ruby-lang.org/en/news/2022/04/12/ruby-3-0-4-released/
https://www.ruby-lang.org/en/news/2022/04/12/ruby-3-1-2-released/

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jboyens** [comment]
This likely needs to be re-pointed to `staging`.

Happy for any and all feedback.

**Comment by marsam** [comment]
>This likely needs to be re-pointed to staging.

Indeed, please point it to `staging`. Besides that, LGTM.

**Comment by mweinelt** [comment]
Please check out https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging for how to correctly do a rebase without inadvertently pinging a bunch of people.

**Comment by jboyens** [comment]
So so so sorry.

**Comment by jboyens** [comment]
Okay. After that fiasco of chaos, I've re-pointed it at staging and verified the builds again.

As well, I hereby swear that I shall never be so cavalier again and will read CONTRIBUTING.md as though my life depends on it.

**Comment by jboyens** [comment]
GitHub was still showing a merge issue, I've resolved that so hopefully all clean.

**Comment by mweinelt** [comment]
Please make this three commits, one for each attribute. We need to backport the bumps for 2_7 and 3_0 into staging-21.11.

**Comment by mweinelt** [comment]
Took the liberty to split them up so we have them in the next evaluation.

**Pull request merged**
