### PR TITLE
axoloti: 1.0.12-1 -> 1.0.12-2

### PR DESCRIPTION
**Pull request by TealG**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by srhb** [comment]
@GrahamcOfBorg build axoloti

**Comment by srhb** [comment]
It might be better to split this into two commits, if you don't want maintainership anymore. Just in case the bump ever gets reverted. :-)

**Comment by Mic92** [comment]
Do we want to remove this package?

**Comment by srhb** [comment]
@Mic92 I don't know, do we? Maintainerless packages are certainly non-ideal, but it's not a unique situation, and since we don't have a proper queue of volunteers for maintainership on arbitrary packages, it seems a little extreme to me. Your call.

**Pull request merged**
