### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
systemd fails to build cc @flokli

**Comment by flokli** [comment]
@FRidh looking at the hydra log, this seems to be some incompatibility with `libmicrohttpd`:
```
../src/journal-remote/journal-remote-main.c: In function ‘setup_microhttpd_server’:
../src/journal-remote/journal-remote-main.c:431:38: error: passing argument 5 of ‘MHD_start_daemon’ from incompatible pointer type [-Werror=incompatible-pointer-types]
```

We can probably just disable that whole feature for now - we don't install the unit files anyways.

**Comment by flokli** [comment]
@FRidh I opened a PR, directed towards `staging-next` at https://github.com/NixOS/nixpkgs/pull/94356 which fixes the build for me.

**Comment by FRidh** [comment]
libreoffice fails to build https://hydra.nixos.org/build/124674530

**Comment by kristoff3r** [comment]
> libreoffice fails to build https://hydra.nixos.org/build/124674530

I spent a couple of minutes debugging this, and it looks like the breakage comes from the `icu` default being upgraded. Apparently they changed their macros to require semi-colons after them, and at least one is present in the pinned libreoffice version. I guess libreoffice needs to still get `icu64` or be upgraded.

**Comment by FRidh** [comment]
qtwebkit fails https://hydra.nixos.org/build/124672735
I thought that was deprecated and that applications such as kmail would not depend on it any longer. It seems it's used via messagelib, which I think not necessarily needs qtwebkit.

**Comment by gebner** [comment]
@FRidh qtwebkit is not deprecated, it's just community maintained now.

**Comment by FRidh** [comment]
I should have referred to https://github.com/NixOS/nixpkgs/issues/53079

**Pull request merged**
