### PR TITLE
prosody: added optional dependency on zlib

### PR DESCRIPTION
**Pull request by k0ral**
Required for [mod_compression](https://prosody.im/doc/modules/mod_compression).

### CODE REVIEW

**Comment by vcunat** [comment]
Is there a reason not to have the zlib dependency by default. I would think zlib already is in the runtime closure of the output anyway.

**Comment by k0ral** [comment]
Though the derivation assumes no zlib dependency (`withZlib ? false`), the `prosody` package explicitly enables it, so from the user's point of view, installing prosody will *by default* use zlib.
I could implement the zlib dependency as an opt-out feature instead if you wish, but that's really just a matter of convention if you ask me.

**Comment by vcunat** [comment]
Oh, I didn't realize you set it true by default. I'd prefer ``withZlib ? true`` then to be "consistent" about the default then, but that's just a nitpick I can do during the merge.

I forgot to /cc maintainer @flosse.

**Comment by k0ral** [comment]
Any reason this PR is still pending validation ?

**Comment by vcunat** [comment]
No, I was just very slow to get back to it.

**Pull request closed without merging**
