### PR TITLE
nixosTests.docker-preloader: Port to Python

### PR DESCRIPTION
**Pull request by tfc**
###### Motivation for this change

#72828

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tfc** [comment]
@grahamcofborg test docker-preloader

**Comment by flokli** [comment]
@tfc Did this succeed on your machine? Seems to fail on ofborg:

```
open /var/lib/docker/overlay2/e15685a6d503df5e91f284dccf1fe62a2fddbe3db41c4386b883edad8ff1eb13/committed: read-only file system"
```

**Comment by tfc** [comment]
@flokli weird. Yes, it works on both my machines.

**Comment by worldofpeace** [comment]
@GrahamcOfBorg test docker-preloader

**Comment by worldofpeace** [comment]
Fails on my machine
```
ocker # [   14.307652] dockerd[856]: time="2020-02-14T19:17:53.392910714Z" level=error msg="Handler for POST /v1.40/containers/create returned error: open /var/lib/docker/overlay2/7efbea82c8cbd126c34d5e5fa5111fd4349c2034dc7a320627fb9c80f0e31dfd/committed: read-only file system"
docker # /nix/store/6sfqhlii23k5fhpwpzv2gwrzfpdwsawi-docker-19.03.5/libexec/docker/docker: Error response from daemon: open /var/lib/docker/overlay2/7efbea82c8cbd126c34d5e5fa5111fd4349c2034dc7a320627fb9c80f0e31dfd/committed: read-only file system.
docker # See '/nix/store/6sfqhlii23k5fhpwpzv2gwrzfpdwsawi-docker-19.03.5/libexec/docker/docker run --help'.
docker: output:
error: command `docker run nix nix-store --version` failed (exit code 125)
cleaning up
killing docker (pid 9)
(0.00 seconds)
```

**Comment by flokli** [comment]
@tfc this also failed for me, when running `nix-build -A nixosTests.docker-preloader` from a checkout of this branch:

```
docker # [   12.618288] dockerd[841]: time="2020-02-18T16:57:15.186850000Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
docker # [   12.626016] systemd-udevd[532]: Using default interface naming scheme 'v243'.
docker # [   12.647880] systemd-udevd[532]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
docker # [   12.890340] dockerd[841]: time="2020-02-18T16:57:15.458796574Z" level=info msg="Loading containers: done."
docker # [   13.089265] systemd[1]: var-lib-docker-overlay2-opaque\x2dbug\x2dcheck242620588-merged.mount: Succeeded.
docker # [   13.096296] dockerd[841]: time="2020-02-18T16:57:15.664879191Z" level=info msg="Docker daemon" commit=633a0ea838f10e000b7c6d6eed1623e6e988b5bc graphdriver(s)=overlay2 version=19.03.5
docker # [   13.100627] dockerd[841]: time="2020-02-18T16:57:15.669026366Z" level=info msg="Daemon has completed initialization"
docker # [   13.182081] systemd[1]: Started Docker Application Container Engine.
docker # [   13.186243] systemd[1]: Reached target Multi-User System.
docker # [   13.188691] systemd[1]: Startup finished in 3.386s (kernel) + 9.794s (userspace) = 13.181s.
docker # [   13.198959] dockerd[841]: time="2020-02-18T16:57:15.756404510Z" level=info msg="API listen on /run/docker.sock"
docker # [   13.216920] dockerd[841]: time="2020-02-18T16:57:15.785408476Z" level=error msg="Handler for POST /v1.40/containers/create returned error: open /var/lib/docker/overlay2/dad7ff32c10de4660ec848025acfcd2c2fdf7534d215603acb01f0275e551849/committed: read-only file system"
docker # /nix/store/6sfqhlii23k5fhpwpzv2gwrzfpdwsawi-docker-19.03.5/libexec/docker/docker: Error response from daemon: open /var/lib/docker/overlay2/dad7ff32c10de4660ec848025acfcd2c2fdf7534d215603acb01f0275e551849/committed: read-only file system.
docker # See '/nix/store/6sfqhlii23k5fhpwpzv2gwrzfpdwsawi-docker-19.03.5/libexec/docker/docker run --help'.
docker: output:
error: command `docker run nix nix-store --version` failed (exit code 125)
cleaning up
killing docker (pid 9)
(0.00 seconds)
builder for '/nix/store/wip3apvpmxykhdyk28mf84vszb1n5w57-vm-test-run-docker-preloader.drv' failed with exit code 1
error: build of '/nix/store/wip3apvpmxykhdyk28mf84vszb1n5w57-vm-test-run-docker-preloader.drv' failed
```

**Comment by tfc** [comment]
It finally fails on my systems, too. I wonder how/why it ever worked, as the commit that introduces this module maps the images RO: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/docker-preloader.nix#L92

However, i have no idea how to fix this without modifying the module (possible to the worse). @nlewo any idea?

**Pull request merged**
