### PR TITLE
itch: 25.5.1 -> 25.6.2

### PR DESCRIPTION
**Pull request by SuperSamus**
###### Description of changes

Updates to the latest version of Itch, which... doesn't change very much.
Can't upgrade the old and insecure Electron 11.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by pasqui23** [comment]
Compiles and run. LGTM

**Comment by Mic92** [comment]
Get 404 when building (probably the icons?) 

```
error: builder for '/nix/store/5f10byxw2v9bvb5qqk40f87zp6bbwxvd-source.drv' failed with exit code 1;
       last 13 log lines:
       > exporting https://github.com/itchio/itch.git (rev v25.6.2) into /nix/store/na4nj8r1bzfalhq1j99pxz66r4aq9jpf-source
       > Initialized empty Git repository in /nix/store/na4nj8r1bzfalhq1j99pxz66r4aq9jpf-source/.git/
       > fatal: couldn't find remote ref refs/tags/v25.6.2
       > remote: Enumerating objects: 110, done.
       > remote: Counting objects: 100% (110/110), done.
       > remote: Compressing objects: 100% (92/92), done.
       > remote: Total 110 (delta 0), reused 77 (delta 0), pack-reused 0
       > Receiving objects: 100% (110/110), 23.58 KiB | 23.58 MiB/s, done.
       > From https://github.com/itchio/itch
       >  * branch            HEAD       -> FETCH_HEAD
       > fatal: Not a valid object name
       > Unrecognized git object type:
       > Unable to checkout refs/tags/v25.6.2 from https://github.com/itchio/itch.git.
       For full logs, run 'nix log /nix/store/5f10byxw2v9bvb5qqk40f87zp6bbwxvd-source.drv'.
error: 1 dependencies of derivation '/nix/store/1wdifp3fvgaxqpcl8f22sh2zam6k5dqs-itch-25.6.2.drv' failed to build

```

**Comment by pasqui23** [comment]
> Get 404 when building (probably the icons?)
> 
> ```
> error: builder for '/nix/store/5f10byxw2v9bvb5qqk40f87zp6bbwxvd-source.drv' failed with exit code 1;
>        last 13 log lines:
>        > exporting https://github.com/itchio/itch.git (rev v25.6.2) into /nix/store/na4nj8r1bzfalhq1j99pxz66r4aq9jpf-source
>        > Initialized empty Git repository in /nix/store/na4nj8r1bzfalhq1j99pxz66r4aq9jpf-source/.git/
>        > fatal: couldn't find remote ref refs/tags/v25.6.2
>        > remote: Enumerating objects: 110, done.
>        > remote: Counting objects: 100% (110/110), done.
>        > remote: Compressing objects: 100% (92/92), done.
>        > remote: Total 110 (delta 0), reused 77 (delta 0), pack-reused 0
>        > Receiving objects: 100% (110/110), 23.58 KiB | 23.58 MiB/s, done.
>        > From https://github.com/itchio/itch
>        >  * branch            HEAD       -> FETCH_HEAD
>        > fatal: Not a valid object name
>        > Unrecognized git object type:
>        > Unable to checkout refs/tags/v25.6.2 from https://github.com/itchio/itch.git.
>        For full logs, run 'nix log /nix/store/5f10byxw2v9bvb5qqk40f87zp6bbwxvd-source.drv'.
> error: 1 dependencies of derivation '/nix/store/1wdifp3fvgaxqpcl8f22sh2zam6k5dqs-itch-25.6.2.drv' failed to build
> ```

Could not reproduce, even after deleting the gc root and `nix-collect-garbage`

**Comment by SuperSamus** [comment]
I solved it with the last force push.

**Pull request merged**
