### PR TITLE
dotnet-sdk_7: mark as insecure due to support ending

### PR DESCRIPTION
**Pull request by corngood**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by corngood** [comment]
> .NET 7 went EOL on 14th May[1](#user-content-fn-1-ef5507b2026dd4aebea1e9c27aa47088). It should probably be marked as deprecated.
> ## Footnotes
> 
>     1. https://endoflife.date/dotnet [↩](#user-content-fnref-1-ef5507b2026dd4aebea1e9c27aa47088)

@JamieMagee what do you think of this?  It looks like a dozen or so packages would be impacted by this.

**Comment by corngood** [comment]
Result of `nixpkgs-review pr 326218` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by JamieMagee** [comment]
@corngood I expect we will handle this the same as the .NET Core 3.1 deprecation:

1. Some packages will build fine with a newer SDK regardless of what is declared
2. Some will have updates upstream we'll need to package
3. Some will require patching either upstream or in nixpkgs

I think it took us about 6 months to fully resolve the .NET Core 3.1 list of dependent packages.

**Comment by corngood** [comment]
@JamieMagee do you think we should mark it insecure immediately, wait until the dependencies are removed, or do neither and just remove it like 3.1?

I was thinking I could make a tracking issue for the dependencies by replacing all uses with .net 8.  That should show what's actually broken, and ping the relevant people.  Do you think that's a good idea?

**Comment by gepbird** [comment]
Superseded by https://github.com/NixOS/nixpkgs/pull/358533

**Pull request closed without merging**
