### PR TITLE
nnn: 4.3 → 4.4

### PR DESCRIPTION
**Pull request by sikmir**
###### Motivation for this change
[Changelog](https://github.com/jarun/nnn/releases/tag/v4.4)

###### Things done
- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux (cross)
  - [x] x86_64-darwin
  - [x] aarch64-darwin (cross)
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by thiagokokada — COMMENTED** [review]
Please fix the commit message:

```
nnn: 4.3 -> 4.4
```

**Comment by sikmir** [comment]
> Please fix the commit message:
> 
> ```
> nnn: 4.3 -> 4.4
> ```

Why? Unicode arrow symbol is widely used and even prefered as discussed here https://discourse.nixos.org/t/vs-in-a-commit-message/11180

**Comment by thiagokokada** [comment]
> > Please fix the commit message:
> > ```
> > nnn: 4.3 -> 4.4
> > ```
> 
> Why? Unicode arrow symbol is widely used and even prefered as discussed here https://discourse.nixos.org/t/vs-in-a-commit-message/11180

https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#submitting-changes

Unless there is a consensus (e.g.: update `CONTRIBUTING.md`) I would much prefer to follow the document. So please update your commit message.

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 147139` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>nnn</li>
  </ul>
</details>

**Review by thiagokokada — APPROVED** [review]
Works fine for me.

**Pull request merged**
