### PR TITLE
kapow: init at 1.5.10

### PR DESCRIPTION
**Pull request by infinitisno**
###### Motivation for this change
For add a new package

###### Things done
Added a new package :)

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by eonpatapon** [comment]
Builded it locally, but execution doesn't work for me:

```
/nix/store/sl5r2n3zxv9d0qmx65arh5y9rzv8lrzz-kapow-1.5.9/bin/kapow

(process:13658): GLib-GIO-ERROR **: 21:50:48.873: No GSettings schemas are installed on the system
Trace/breakpoint trap (core dumped)
```

Also you make two commits, one for the package, one for adding yourself in maintainers.

The commit message for adding the package would be: `kapow: init at 1.5.9`

**Comment by AndersonTorres** [comment]
Split the maintainers file commit.

**Comment by orivej** [comment]
I have set myself as the maintainer because the change to maintainers list seemed invalid: azimov.rocks email domain is not registered and 0x769C79DA5C9B038A PGP key is [not published](http://keys.gnupg.net/pks/lookup?search=0x769C79DA5C9B038A&fingerprint=on&op=index). @0x450x6c, please add yourself to maintainers if you still wish to maintain this package (and be notified of its issues and pull requests that edit its definition).

**Comment by AndersonTorres** [comment]
What about merge it and include @0x450x6c in a future commit?

**Comment by orivej** [comment]
OK.

**Pull request merged**
