### PR TITLE
xandikos: backport systemd socket activation

### PR DESCRIPTION
**Pull request by schnusch**
###### Motivation for this change

Backported <https://github.com/jelmer/xandikos/pull/155> to add support for systemd socket activation. This also enables UNIX sockets with proper owner/permissions, because systemd creates them for us.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 0x4A6F** [comment]
I'm a little bit baffled about your PR description and the actual changes.

**Comment by 0x4A6F** [comment]
I'm a little bit baffled about your PR description and the actual changes.

**Comment by schnusch** [comment]
Yeah, you're right. Xandikos was always able to do that, this PR just adds that to the nginx configuration.

**Comment by 0x4A6F** [comment]
Topic and changes fit together.

But I mean the mismatching description:
```
Remove prometheus-client, it is replaced by aiohttp-openmetrics which is not
yet packaged.
```

**Comment by schnusch** [comment]
Yeah, I think you are right, when I made this I still had xandikos-0.2.6 and was about to create a pull request for that too but noticed this and probably mixed up the pull requests.

**Review by 0x4A6F — CHANGES_REQUESTED** [review]
LGTM, could you also expand `nixos/tests/xandikos.nix` to include a subtest for sockets usecase?

**Comment by schnusch** [comment]
While writing a test I noticed that the permission of the socket are too strict to be useful. Changing the services UMask does not seem appropriate. We should probably put this off until systemd's socket activation makes it into xandikos, see <https://github.com/jelmer/xandikos/pull/155>.

**Comment by schnusch** [comment]
Rebased to fix merge conflict.

**Comment by schnusch** [comment]
Close in favor of <https://github.com/NixOS/nixpkgs/pull/253523>.

**Pull request closed without merging**
