### PR TITLE
hunspell-dict-de-any-igerman98: init at 20160407

### PR DESCRIPTION
**Pull request by seschwar**
###### Things done
- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [X] NixOS
  - [ ] OS X
  - [ ] Linux
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

The derivation's buildPhase requires `ispell` for which we reuse pull request #3320 by @bennofs.

### CODE REVIEW

**Comment by bjornfor** [comment]
Isn't ispell deprecated? This page (https://www.gnu.org/software/ispell/) suggests to use aspell instead. (I had to look it up, because of all the ispell patches that are included in this PR.)

Hm, Archlinux has ispell, and it's smaller (almost no patching):
https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/ispell

Seems a lot of those patches belong to upstream. Are they dead?

**Comment by seschwar** [comment]
Yes, ispell is deprecated. However this hunspell dictionary requires the `buildhash` executable which is included with ispell to build. That is the only reason for adding ispell to nixpkgs.

I had trouble to get a more minimal ispell to build. Therefore I just reused @bennofs' earlier pull request. Maybe we can slim down the ispell derivation.

**Comment by bjornfor** [comment]
@seschwar: So you plan to work more on this PR? (I'm OK with merging as is, if you want.)

**Comment by seschwar** [comment]
No, I'd rather not spend more time on ispell than required as it's only a build dependency.

**Comment by bjornfor** [comment]
After having a closer look, some comments:

* Those commented out stuff in the Nix file ("XXX" and "sed"). Keep or discard?
* ispell is missing "meta" attributes.

**Comment by Mic92** [comment]
Needed to solve this issue: https://github.com/NixOS/nixpkgs/issues/14430

**Comment by Mic92** [comment]
How about the following solution: 
* Make a derivation called ispell-buildhash: 
* Build only buildhash by doing `make buildhash`
* skip all patches because they do not affect buildhash

**Comment by FRidh** [comment]
Closing because there is no progress.

**Pull request closed without merging**
