### PR TITLE
nodePackages:update to latest

### PR DESCRIPTION
**Pull request by happysalada**
###### Description of changes

Just an update of nodePackages

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 237035` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>29 packages failed to build:</summary>
  <ul>
    <li>balanceofsatoshis</li>
    <li>bitwarden-cli</li>
    <li>castnow</li>
    <li>commitlint</li>
    <li>concurrently</li>
    <li>create-cycle-app</li>
    <li>emacsPackages.lsp-bridge</li>
    <li>gtop</li>
    <li>joplin</li>
    <li>lighthouse</li>
    <li>lv_img_conv</li>
    <li>openmoji-black</li>
    <li>openmoji-color</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>pscid</li>
    <li>redoc-cli</li>
    <li>theLoungePlugins.plugins.closepms</li>
    <li>theLoungePlugins.themes.flat-blue</li>
    <li>theLoungePlugins.themes.flat-dark</li>
    <li>uppy-companion</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-tslint</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vimPlugins.markdown-preview-nvim</li>
    <li>vscode-extensions.rust-lang.rust-analyzer</li>
    <li>wrangler</li>
    <li>zx</li>
  </ul>
</details>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>pyright</li>
    <li>vscode-extensions.ms-python.vscode-pylance</li>
    <li>wasm-text-gen</li>
  </ul>
</details>

**Comment by tjni** [comment]
Result of `nixpkgs-review pr 237035` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages marked as broken and skipped:</summary>
  <ul>
    <li>fast-cli</li>
    <li>python310Packages.nbdev</li>
    <li>python310Packages.nbdev.dist</li>
    <li>python311Packages.nbdev</li>
    <li>python311Packages.nbdev.dist</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>joplin</li>
  </ul>
</details>
<details>
  <summary>37 packages built:</summary>
  <ul>
    <li>balanceofsatoshis</li>
    <li>bitwarden-cli</li>
    <li>castnow</li>
    <li>commitlint</li>
    <li>concurrently</li>
    <li>create-cycle-app</li>
    <li>emacsPackages.lsp-bridge</li>
    <li>emanote</li>
    <li>emanote.data</li>
    <li>gtop</li>
    <li>haskellPackages.emanote</li>
    <li>haskellPackages.emanote.data</li>
    <li>haskellPackages.emanote.doc</li>
    <li>haskellPackages.tailwind</li>
    <li>haskellPackages.tailwind.doc</li>
    <li>lighthouse</li>
    <li>lv_img_conv</li>
    <li>openmoji-black</li>
    <li>openmoji-color</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>pscid</li>
    <li>pyright</li>
    <li>redoc-cli</li>
    <li>theLoungePlugins.plugins.closepms</li>
    <li>theLoungePlugins.themes.flat-blue</li>
    <li>theLoungePlugins.themes.flat-dark</li>
    <li>uppy-companion</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-tslint</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vimPlugins.markdown-preview-nvim</li>
    <li>vscode-extensions.rust-lang.rust-analyzer</li>
    <li>wasm-text-gen</li>
    <li>wrangler</li>
    <li>zx</li>
  </ul>
</details>

**Comment by tjni** [comment]
On aarch64-darwin, `joplin` is the only package that started to fail, with the following error:

```
npm ERR! In file included from ../src/CanvasPattern.cc:6:
npm ERR! ../src/Image.h:18:10: fatal error: 'gif_lib.h' file not found
npm ERR! #include <gif_lib.h>
npm ERR!          ^~~~~~~~~~~
npm ERR! 1 error generated.
npm ERR! make: *** [canvas.target.mk:164: Release/obj.target/canvas/src/CanvasPattern.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
```

**Comment by happysalada** [comment]
Thanks for the review, I did this on a computer where I ran out of space before the end.

I'm going to merge now in order not to get conflicts

**Pull request merged**
