### PR TITLE
nixos/networkd: add missing IPv6 options

### PR DESCRIPTION
**Pull request by veehaitch**
###### Motivation for this change

Adds various missing/renamed configuration sections/options for systemd-networkd related to IPv6.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by veehaitch** [comment]
@GrahamcOfBorg test systemd-networkd-ipv6-prefix-delegation

**Comment by veehaitch** [comment]
@GrahamcOfBorg test systemd-networkd-ipv6-prefix-delegation

**Comment by veehaitch** [comment]
If there's anything I can do to advance this PR, feel free to reach out. Happy to help :)

**Comment by andir** [comment]
This is missing changelog entries. Would be nice to point users towards this before they run into crypto eval errors (that do not point out the right lines :/)

**Pull request merged**
