### PR TITLE
[20.09 backport] tor-browser-bundle-bin: mark as broken

### PR DESCRIPTION
**Pull request by xaverdh**
###### Motivation for this change

see https://github.com/NixOS/nixpkgs/pull/102540

### CODE REVIEW

**Comment by wamserma** [comment]
Backports are commonly done using `git cherry-pick -x` to keep a reference to the commit on master. Also, please add the word backport to the PR title.

**Comment by jonringer** [comment]
When backporting changes, please follow https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#backporting-changes.

Namely, you should be doing `git cherry-pick -x <rev>` from a commit that has already landed in master. If the branches have diverged, you may alter the commit or add another commit to ensure that the package is able to still evaluate and build

**Comment by xaverdh** [comment]
> Backports are commonly done using `git cherry-pick -x` to keep a reference to the commit on master. Also, please add the word backport to the PR title.

Ok, hope I did that right, since its a merge commit.
I will happily add "backport" to the title, but maybe we should update the [docs](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md) on this then, if it is desired?
(currently it says:

> The pull request title should be the commit title with the release version as prefix, e.g. [20.09]."

)

**Comment by wamserma** [comment]
> > Backports are commonly done using `git cherry-pick -x` to keep a reference to the commit on master. Also, please add the word backport to the PR title.
> 
> Ok, hope I did that right, since its a merge commit.
> I will happily add "backport" to the title, but maybe we should update the [docs](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md) on this then, if it is desired?
> (currently it says:
> 
> > The pull request title should be the commit title with the release version as prefix, e.g. [20.09]."
> 
> )

Contribution guidelines are mandatory, having backport in the title is just a matter of personal taste.

**Comment by jonringer** [comment]
> Ok, hope I did that right, since its a merge commit.

no, it should just be the commit itself
```
git cherry-pick -x 968348bd188315597c94e40b19442b45b2da4ec5
```

I found this by going to the original PR, going down to the "merge" comment from github, it has a commit hash listed of the merge commit. Click on it. It will show that it has two parents, click on either one to see if it's the correct commit, generally it's the second one in github.

**Comment by xaverdh** [comment]
I tried `git cherry-pick -x 968348bd188315597c94e40b19442b45b2da4ec5` and force pushing to this pr branch, it said "Everything up-to-date" ..
This means I should open a new pr maybe?

Either way, feel free to open your own & merge if that's quicker, this is somewhat time critical and I don't want to delay it by messing things up..

**Review by wamserma — APPROVED** [review]
LGTM.

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 102628 [1](https://github.com/Mic92/nixpkgs-review)

**Pull request merged**
