### PR TITLE
vimPlugins.neuron-vim: 2020-10-29 -> 2020-11-11

### PR DESCRIPTION
**Pull request by wbadart**
###### Motivation for this change

There have been a couple important bug fixes pushed to
fiatjaf/neuron.vim in the last few days; just want to make sure they're
available via nixpkgs.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
for vim plugins, please follow https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/vim.section.md#updating-plugins-in-nixpkgs

Namely, there should be a single `vimPlugins: update` commit which will update all of the vim plugins to their latest

**Comment by wbadart** [comment]
Thanks for the feedback @jonringer. I'd been asked to touch up the commits created by `update.py` for #101385 so I thought I might have to do the same here. I've replaced my original commit with the untouched result of running `update.py`. You mentioned that there should be one commit, `vimPlugins: update` but the script also created 6e9408f; please let me know if I should delete that second commit.

**Comment by jonringer** [comment]
no, this is great!

**Comment by jonringer** [comment]
> but the script also created [6e9408f](https://github.com/NixOS/nixpkgs/commit/6e9408f7e08140cbe71c3ad8da833cfe3972ba22); please let me know if I should delete that second commit.

In most cases, will just make one. But it looks like someone redirected, and that should also be captured.

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 103645 [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>62 packages built:</summary>  <ul>    <li>vimPlugins.Coqtail</li>    <li>vimPlugins.YouCompleteMe</li>    <li>vimPlugins.barbar-nvim</li>    <li>vimPlugins.coc-explorer</li>    <li>vimPlugins.coc-markdownlint</li>    <li>vimPlugins.coc-nvim</li>    <li>vimPlugins.ctrlp-vim</li>    <li>vimPlugins.dart-vim-plugin</li>    <li>vimPlugins.deoplete-fish</li>    <li>vimPlugins.deoplete-jedi</li>    <li>vimPlugins.deoplete-khard</li>    <li>vimPlugins.deoplete-nvim</li>    <li>vimPlugins.diagnostic-nvim</li>    <li>vimPlugins.dracula-vim</li>    <li>vimPlugins.fzf-vim</li>    <li>vimPlugins.hoon-vim</li>    <li>vimPlugins.indentLine</li>    <li>vimPlugins.lh-vim-lib</li>    <li>vimPlugins.lightline-vim</li>    <li>vimPlugins.ncm2-ultisnips</li>    <li>vimPlugins.neco-vim</li>    <li>vimPlugins.neoformat</li>    <li>vimPlugins.neomake</li>    <li>vimPlugins.neosnippet-snippets</li>    <li>vimPlugins.neoterm</li>    <li>vimPlugins.nerdtree-git-plugin</li>    <li>vimPlugins.neuron-vim</li>    <li>vimPlugins.nvim-treesitter</li>    <li>vimPlugins.oceanic-next</li>    <li>vimPlugins.open-browser-github-vim</li>    <li>vimPlugins.papercolor-theme</li>    <li>vimPlugins.skim-vim</li>    <li>vimPlugins.syntastic</li>    <li>vimPlugins.tagbar</li>    <li>vimPlugins.telescope-nvim</li>    <li>vimPlugins.ultisnips</li>    <li>vimPlugins.undotree</li>    <li>vimPlugins.vim-airline</li>    <li>vimPlugins.vim-airline-themes</li>    <li>vimPlugins.vim-bsv</li>    <li>vimPlugins.vim-clap</li>    <li>vimPlugins.vim-codefmt</li>    <li>vimPlugins.vim-exchange</li>    <li>vimPlugins.vim-floaterm</li>    <li>vimPlugins.vim-gitgutter</li>    <li>vimPlugins.vim-go</li>    <li>vimPlugins.vim-graphql</li>    <li>vimPlugins.vim-jsx-pretty</li>    <li>vimPlugins.vim-lsc</li>    <li>vimPlugins.vim-mundo</li>    <li>vimPlugins.vim-pandoc</li>    <li>vimPlugins.vim-projectionist</li>    <li>vimPlugins.vim-snippets</li>    <li>vimPlugins.vim-tmux-navigator</li>    <li>vimPlugins.vim-trailing-whitespace</li>    <li>vimPlugins.vim-vsnip</li>    <li>vimPlugins.vim-vsnip-integ</li>    <li>vimPlugins.vimspector</li>    <li>vimPlugins.vimtex</li>    <li>vimPlugins.vista-vim</li>    <li>vimPlugins.wal-vim</li>    <li>vimPlugins.yats-vim</li>  </ul></details>

**Pull request merged**
