### PR TITLE
bat-extras: 20200515-dev -> 2021.04.06

### PR DESCRIPTION
**Pull request by bbigras**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 119689` at 2a441ee4 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built successfully:</summary>
  <ul>
    <li>bat-extras.batdiff</li>
    <li>bat-extras.batgrep</li>
    <li>bat-extras.batman</li>
    <li>bat-extras.batwatch</li>
    <li>bat-extras.prettybat</li>
  </ul>
</details>

**Comment by dywedir** [comment]
Thanks!

**Comment by bbigras** [comment]
Thank you too :)

**Comment by lilyball** [comment]
I can't build `bat-extras` now. It builds, then prints the line "running tests", then fails with exit code 127 (which I believe indicates that it's trying to run a command that doesn't exist). This is on darwin.

**Comment by lilyball** [comment]
It looks like it's failing to find `getconf`. This appears to be in stdenv on Linux, but not on macOS.

**Comment by lilyball** [comment]
Adding `getconf` to the `checkInputs` on both `core` and `script` fixes this. I'd submit a PR but I can't do that for the time being.

**Comment by lilyball** [comment]
I filed this as #119987.

**Pull request merged**
