### PR TITLE
kdeApplications.ktnef: init at 17.04.0

### PR DESCRIPTION
**Pull request by peterhoeg**
###### Motivation for this change

I actually needed the KDE tnef VIEWER while this is the tnef LIBRARY which was pretty stupid of me...

ktnef (the viewer) is part if kdepim it seems.

@ttuegel: is this the proper way to package kdeApplication components?

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ttuegel** [comment]
The viewer is part of KMail, which I have packaged in [this branch](https://github.com/ttuegel/nixpkgs/tree/kde-applications).

**Comment by orivej** [comment]
That's great! Would you also package akregator, or should I add it myself and send you a pull request (if kde-applications branch is not merged here yet)?

**Comment by ttuegel** [comment]
@orivej I am just adding some source patches to complete the work @vandenoever started in #20576, so Akregator and the rest of the KDE PIM suite will be packaged after I cherry-pick the rest of those patches. I plan to merge that branch rather soon because it contains some important changes to the way Qt/KDE applications are packaged.

**Comment by peterhoeg** [comment]
Got it, closing this in favour of your work.

**Pull request closed without merging**
