### PR TITLE
duckdb: 1.0.0 -> 1.1.1

### PR DESCRIPTION
**Pull request by cpcloud**
## Description of changes

Bump duckdb 1.0.0 -> 1.1.0.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cpcloud** [comment]
I'm going to include updates to ibis-framework as well as sqlglot here.

**Comment by cpcloud** [comment]
cc @fabaff, would you mind reviewing this?

**Comment by paparodeo** [comment]
Result of `nixpkgs-review pr 341169` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>18 packages failed to build:</summary>
  <ul>
    <li>python311Packages.duckdb-engine</li>
    <li>python311Packages.duckdb-engine.dist</li>
    <li>python311Packages.graphrag</li>
    <li>python311Packages.graphrag.dist</li>
    <li>python311Packages.jupysql</li>
    <li>python311Packages.jupysql.dist</li>
    <li>python311Packages.lancedb</li>
    <li>python311Packages.lancedb.dist</li>
    <li>python311Packages.pylance</li>
    <li>python311Packages.pylance.dist</li>
    <li>python312Packages.duckdb-engine</li>
    <li>python312Packages.duckdb-engine.dist</li>
    <li>python312Packages.graphrag</li>
    <li>python312Packages.graphrag.dist</li>
    <li>python312Packages.lancedb</li>
    <li>python312Packages.lancedb.dist</li>
    <li>python312Packages.pylance</li>
    <li>python312Packages.pylance.dist</li>
  </ul>
</details>
<details>
  <summary>25 packages built:</summary>
  <ul>
    <li>azure-cli-extensions.rdbms-connect</li>
    <li>azure-cli-extensions.rdbms-connect.dist</li>
    <li>duckdb</li>
    <li>duckdb.dev</li>
    <li>duckdb.lib</li>
    <li>mycli</li>
    <li>mycli.dist</li>
    <li>python311Packages.datafusion</li>
    <li>python311Packages.datafusion.dist</li>
    <li>python311Packages.duckdb</li>
    <li>python311Packages.duckdb.dist</li>
    <li>python311Packages.ibis-framework</li>
    <li>python311Packages.ibis-framework.dist</li>
    <li>python311Packages.sqlglot</li>
    <li>python311Packages.sqlglot.dist</li>
    <li>python312Packages.datafusion</li>
    <li>python312Packages.datafusion.dist</li>
    <li>python312Packages.duckdb</li>
    <li>python312Packages.duckdb.dist</li>
    <li>python312Packages.ibis-framework</li>
    <li>python312Packages.ibis-framework.dist</li>
    <li>python312Packages.sqlglot</li>
    <li>python312Packages.sqlglot.dist</li>
    <li>sbclPackages.duckdb</li>
    <li>vimPlugins.nvim-dbee</li>
  </ul>
</details>

**Comment by paparodeo** [comment]
Result of `nixpkgs-review pr 341169` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>18 packages failed to build:</summary>
  <ul>
    <li>python311Packages.duckdb-engine</li>
    <li>python311Packages.duckdb-engine.dist</li>
    <li>python311Packages.graphrag</li>
    <li>python311Packages.graphrag.dist</li>
    <li>python311Packages.jupysql</li>
    <li>python311Packages.jupysql.dist</li>
    <li>python311Packages.lancedb</li>
    <li>python311Packages.lancedb.dist</li>
    <li>python311Packages.pylance</li>
    <li>python311Packages.pylance.dist</li>
    <li>python312Packages.duckdb-engine</li>
    <li>python312Packages.duckdb-engine.dist</li>
    <li>python312Packages.graphrag</li>
    <li>python312Packages.graphrag.dist</li>
    <li>python312Packages.lancedb</li>
    <li>python312Packages.lancedb.dist</li>
    <li>python312Packages.pylance</li>
    <li>python312Packages.pylance.dist</li>
  </ul>
</details>
<details>
  <summary>23 packages built:</summary>
  <ul>
    <li>azure-cli-extensions.rdbms-connect</li>
    <li>azure-cli-extensions.rdbms-connect.dist</li>
    <li>duckdb</li>
    <li>duckdb.dev</li>
    <li>duckdb.lib</li>
    <li>mycli</li>
    <li>mycli.dist</li>
    <li>python311Packages.datafusion</li>
    <li>python311Packages.datafusion.dist</li>
    <li>python311Packages.duckdb</li>
    <li>python311Packages.duckdb.dist</li>
    <li>python311Packages.ibis-framework</li>
    <li>python311Packages.ibis-framework.dist</li>
    <li>python311Packages.sqlglot</li>
    <li>python311Packages.sqlglot.dist</li>
    <li>python312Packages.datafusion</li>
    <li>python312Packages.datafusion.dist</li>
    <li>python312Packages.duckdb</li>
    <li>python312Packages.duckdb.dist</li>
    <li>python312Packages.ibis-framework</li>
    <li>python312Packages.ibis-framework.dist</li>
    <li>python312Packages.sqlglot</li>
    <li>python312Packages.sqlglot.dist</li>
  </ul>
</details>

**Comment by turboMaCk** [comment]
I did not finish running nixpkgs-review because builds are bit too spicy for my hardware. But even for the bits I managed to execute I've encountered some test failures:

```
error: builder for '/nix/store/dijhzl7r7rvygs87y8vr2vd95kkhqi0r-python3.12-duckdb-engine-0.13.2.drv' failed with exit code 1;
       last 10 log lines:
       >     - 1 passing examples, 0 failing examples, 0 invalid examples
       >     - Tried 1 shrinks of which 2 were successful
       >
       >   - Stopped because test was flaky
       >
       >
       > =========================== short test summary info ============================
       > FAILED duckdb_engine/tests/test_basic.py::test_simple_string - hypothesis.errors.FlakyFailure: Hypothesis test_simple_string(s='\x11$Ù') p...
       > FAILED duckdb_engine/tests/test_basic.py::test_with_cache - sqlalchemy.exc.OperationalError: (duckdb.duckdb.ConnectionException) Connec...
       > = 2 failed, 35 passed, 35 skipped, 2 deselected, 105 warnings in 62.52s (0:01:02) =
       For full logs, run 'nix log /nix/store/dijhzl7r7rvygs87y8vr2vd95kkhqi0r-python3.12-duckdb-engine-0.13.2.drv'.
error: builder for '/nix/store/1xm6cjdns1n90mvgi1zjws3bd5pqa9qm-python3.11-duckdb-engine-0.13.2.drv' failed with exit code 1;
       last 10 log lines:
       >
       >   - Stopped because nothing left to do
       >
       >
       > =========================== short test summary info ============================
       > FAILED duckdb_engine/tests/test_basic.py::test_simple_string - hypothesis.errors.FlakyFailure: Hypothesis test_simple_string(s='^-') produ...
       > FAILED duckdb_engine/tests/test_basic.py::test_with_cache - sqlalchemy.exc.OperationalError: (duckdb.duckdb.ConnectionException) Connec...
       > FAILED duckdb_engine/tests/test_datatypes.py::test_all_types_reflection - AssertionError: varint
       > FAILED duckdb_engine/tests/test_datatypes.py::test_nested_types - KeyError: 'key'
       > = 4 failed, 50 passed, 35 skipped, 4 deselected, 42 warnings in 125.98s (0:02:05) =
       For full logs, run 'nix log /nix/store/1xm6cjdns1n90mvgi1zjws3bd5pqa9qm-python3.11-duckdb-engine-0.13.2.drv'.
error: 1 dependencies of derivation '/nix/store/s1bzgi6n82njnzkb15nfxr4qxvs7hanc-python3.11-jupysql-0.10.13.drv' failed to build
```

Other than that diff looks good to me. I think the main question really is about the potential regressions (reported 18 failing builds).

**Comment by cpcloud** [comment]
@turboMaCk Updated to duckdb 1.1.1

**Comment by turboMaCk** [comment]
@cpcloud I tried to run nixpkgs review here again but this amount of C++ rebuilds is making it freez and then power off. I wonder if you have any idea about the impact of regressions this could cause. Personally I would be for accepting this but I'm not usually working with python package set which seems to be impacted by the bump.

**Comment by cpcloud** [comment]
@turboMaCk If you run `nixpkgs-review` with `--build-args='--max-jobs=1'` then you should avoid running of memory (and avoid the process dying).

I can also adjust the `ibis-framework` tests to not run in parallel, which when coupled with its engines executing queries in parallel **and** other derivations being built in parallel is likely responsible for running out of memory 😅

**Comment by cpcloud** [comment]
Result of `nixpkgs-review pr 341169` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>22 packages failed to build:</summary>
  <ul>
    <li>python311Packages.duckdb-engine</li>
    <li>python311Packages.duckdb-engine.dist</li>
    <li>python311Packages.graphrag</li>
    <li>python311Packages.graphrag.dist</li>
    <li>python311Packages.ibis-framework</li>
    <li>python311Packages.ibis-framework.dist</li>
    <li>python311Packages.jupysql</li>
    <li>python311Packages.jupysql.dist</li>
    <li>python311Packages.lancedb</li>
    <li>python311Packages.lancedb.dist</li>
    <li>python311Packages.pylance</li>
    <li>python311Packages.pylance.dist</li>
    <li>python312Packages.duckdb-engine</li>
    <li>python312Packages.duckdb-engine.dist</li>
    <li>python312Packages.graphrag</li>
    <li>python312Packages.graphrag.dist</li>
    <li>python312Packages.ibis-framework</li>
    <li>python312Packages.ibis-framework.dist</li>
    <li>python312Packages.lancedb</li>
    <li>python312Packages.lancedb.dist</li>
    <li>python312Packages.pylance</li>
    <li>python312Packages.pylance.dist</li>
  </ul>
</details>
<details>
  <summary>21 packages built:</summary>
  <ul>
    <li>azure-cli-extensions.rdbms-connect</li>
    <li>azure-cli-extensions.rdbms-connect.dist</li>
    <li>duckdb</li>
    <li>duckdb.dev</li>
    <li>duckdb.lib</li>
    <li>mycli</li>
    <li>mycli.dist</li>
    <li>python311Packages.datafusion</li>
    <li>python311Packages.datafusion.dist</li>
    <li>python311Packages.duckdb</li>
    <li>python311Packages.duckdb.dist</li>
    <li>python311Packages.sqlglot</li>
    <li>python311Packages.sqlglot.dist</li>
    <li>python312Packages.datafusion</li>
    <li>python312Packages.datafusion.dist</li>
    <li>python312Packages.duckdb</li>
    <li>python312Packages.duckdb.dist</li>
    <li>python312Packages.sqlglot</li>
    <li>python312Packages.sqlglot.dist</li>
    <li>sbclPackages.duckdb</li>
    <li>vimPlugins.nvim-dbee</li>
  </ul>
</details>

**Comment by cpcloud** [comment]
Changed the `ibis-framework` tests to run serially.

**Comment by cpcloud** [comment]
Result of `nixpkgs-review pr 341169` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>python311Packages.jupysql</li>
    <li>python311Packages.jupysql.dist</li>
  </ul>
</details>
<details>
  <summary>41 packages built:</summary>
  <ul>
    <li>azure-cli-extensions.rdbms-connect</li>
    <li>azure-cli-extensions.rdbms-connect.dist</li>
    <li>duckdb</li>
    <li>duckdb.dev</li>
    <li>duckdb.lib</li>
    <li>mycli</li>
    <li>mycli.dist</li>
    <li>python311Packages.datafusion</li>
    <li>python311Packages.datafusion.dist</li>
    <li>python311Packages.duckdb</li>
    <li>python311Packages.duckdb-engine</li>
    <li>python311Packages.duckdb-engine.dist</li>
    <li>python311Packages.duckdb.dist</li>
    <li>python311Packages.graphrag</li>
    <li>python311Packages.graphrag.dist</li>
    <li>python311Packages.ibis-framework</li>
    <li>python311Packages.ibis-framework.dist</li>
    <li>python311Packages.lancedb</li>
    <li>python311Packages.lancedb.dist</li>
    <li>python311Packages.pylance</li>
    <li>python311Packages.pylance.dist</li>
    <li>python311Packages.sqlglot</li>
    <li>python311Packages.sqlglot.dist</li>
    <li>python312Packages.datafusion</li>
    <li>python312Packages.datafusion.dist</li>
    <li>python312Packages.duckdb</li>
    <li>python312Packages.duckdb-engine</li>
    <li>python312Packages.duckdb-engine.dist</li>
    <li>python312Packages.duckdb.dist</li>
    <li>python312Packages.graphrag</li>
    <li>python312Packages.graphrag.dist</li>
    <li>python312Packages.ibis-framework</li>
    <li>python312Packages.ibis-framework.dist</li>
    <li>python312Packages.lancedb</li>
    <li>python312Packages.lancedb.dist</li>
    <li>python312Packages.pylance</li>
    <li>python312Packages.pylance.dist</li>
    <li>python312Packages.sqlglot</li>
    <li>python312Packages.sqlglot.dist</li>
    <li>sbclPackages.duckdb</li>
    <li>vimPlugins.nvim-dbee</li>
  </ul>
</details>

**Comment by cpcloud** [comment]
@turboMaCk I was able to get the failures down to just one package (`jupysql`) by disabling the tests that don't work with duckdb 1.1.1. The failing packages haven't been updated to work with duckdb 1.1.1, and I think upgrade duckdb is high value enough that it's an acceptable tradeoff to disable those packages' tests.

**Comment by turboMaCk** [comment]
I agree. I think the only thing left is resolution of conflict. After that I we should do just final review and hopefully merge this.

**Review by natsukium — APPROVED** [review]

**Comment by cpcloud** [comment]
@turboMaCk @natsukium I fixed the merge conflict.

**Comment by turboMaCk** [comment]
remaining failures

```
25 packages failed to build:
harlequin harlequin.dist python311Packages.duckdb-engine python311Packages.duckdb-engine.dist python311Packages.graphrag python311Packages.graphrag.dist python311Packages.ibis-framework python311Packages.ibis-framework.dist python311Packages.jupysql python311Packages.jupysql.dist python311Packages.lancedb python311Packages.lancedb.dist python311Packages.pylance python311Packages.pylance.dist python312Packages.duckdb-engine python312Packages.duckdb-engine.dist python312Packages.graphrag python312Packages.graphrag.dist python312Packages.ibis-framework python312Packages.ibis-framework.dist python312Packages.lancedb python312Packages.lancedb.dist python312Packages.pylance python312Packages.pylance.dist sbclPackages.duckdb

20 packages built:
azure-cli-extensions.rdbms-connect azure-cli-extensions.rdbms-connect.dist duckdb duckdb.dev duckdb.lib mycli mycli.dist python311Packages.datafusion python311Packages.datafusion.dist python311Packages.duckdb python311Packages.duckdb.dist python311Packages.sqlglot python311Packages.sqlglot.dist python312Packages.datafusion python312Packages.datafusion.dist python312Packages.duckdb python312Packages.duckdb.dist python312Packages.sqlglot python312Packages.sqlglot.dist vimPlugins.nvim-dbee
```

Diff LGTM.

Anyone objects the merge?

**Pull request merged**
