### PR TITLE
gmt: init at 6.1.0

### PR DESCRIPTION
**Pull request by tviti**
###### Motivation for this change

Adds v6.0.0 of the Generic Mapping Tools (GMT) and support coastline/basemap datasets.

Build is restricted to LGPL licensed code (although GPL and non-free are also possible).

Users interested in movie making functionality will need to also install FFmpeg (for webm and mp4 support) and/or graphicsmagick (for gif support).

ghostscript is included as a runtime dep, since I suspect most users would want this functionality out-of-the-box (w/o ghostscript, postscript is the only available output format). Not sure if it is preferable to make a wrapper v.s. using `propagatedBuildInputs`?

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tviti** [comment]
Just wondering if there's anything I can do to help this along.

**Comment by tviti** [comment]
I think this is a case of:
>   2. You used a modern mode module name while running in GMT classic mode.

In v6.0.0, GMT introduced a so called "modern-mode" that turns it into a sort of plotting mini-language, where modern-mode command invocations are supposed to be wrapped into a gmt begin/end block, i.e.:

 gmt begin <options>
     ...
 gmt end

The legacy commands, which can be called outside of a gmt begin/end block, are generally preceded with ps (since they dump postscript to stdout, which you can append to a postscript plot/map w/ a redirection operator), so I think coast is basically not supposed to be used on its own like that (the associated classic-mode command is pscoast).

Lassulus writes:

**Comment by Lassulus** [comment]
whupps, missed some name/pname issues. fixed it on master in https://github.com/NixOS/nixpkgs/commit/cedef0c6c7604a387e2eae1e04dd89b7ff320ef1

**Comment by tviti** [comment]
Thanks for catching those. Suppose I'm not 100% on when to use one vs the
other.

Is it always preferable to define the pname attr in a derivation, instead
of name?

**Comment by Lassulus** [comment]
name gets auto generated usually out of pname and version.

**Pull request merged**
