### PR TITLE
doc: markdown transition fixes

### PR DESCRIPTION
**Pull request by pennae**
###### Description of changes

https://github.com/NixOS/nixpkgs/issues/175586#issuecomment-1368012288 reported problem for downstream users of the docs infra. changes to the option factories shouldn't be controversial, but the change to `_module.args` is different. not sure whether this is a good way to solve the problem, very much open to other ideas.

should probably be backported to 22.11 in the end

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ncfavier** [comment]
A possible alternative to adding more `*MD` variants would be to treat `mdDoc` as a generic Markdown marker:
- `mkPackageOption pkgs (mdDoc "foobar")`
- `mkAliasOptionModule [ "old" ] (mdDoc [ "new" ])` or something (this is probably terrible)

Independently from this PR, we probably want to make `_module.*`'s visibility opt-in anyway: see https://github.com/NixOS/nixos-search/pull/528. Standalone NixOS module docs like https://nix-community.github.io/home-manager/nixos-options.html don't really need to include `_module.args`. In fact I think ideally `_module.*` options should be documented somewhere in the main NixOS manual rather than in the "configuration options" annex. But for now, maybe we can just use `specialArgs._moduleVisible` and set `_module.*.visible` based on that?

**Comment by roberth** [comment]
I think we should try to keep it simple for two reasons
 - the markdown transition is a temporary state of affairs
 - `_module` is added to _every_ module, including _all_ submodules, so doing anything extra there will have a sizable performance impact

Also simple is good.
I'd be ok with hiding `_module.args` docs unconditionally for now, and enable it later. (Sorry @infinisil)

**Comment by ncfavier** [comment]
We should probably mention `mkAliasOptionModuleMD` and `mkPackageOptionMD` in the error message in `mergeJSON.py`

**Review by ncfavier — APPROVED** [review]
Half-hearted approval because the transitional period is taking way too long :/

**Comment by zowoq** [comment]
https://github.com/NixOS/nixpkgs/actions/runs/3843384881/jobs/6545596726

Manual checks are failing since this was merged.

**Pull request merged**
