### PR TITLE
pods: 1.2.1 -> 1.2.2

### PR DESCRIPTION
**Pull request by figsoda**
Diff: https://github.com/marhkb/pods/compare/v1.2.1...v1.2.2

Changelog: https://github.com/marhkb/pods/releases/tag/v1.2.2

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by NickCao — APPROVED** [review]

**Comment by meppu** [comment]
I just wanted to notify that it fails to build this package from source. The issue is [here](https://github.com/marhkb/pods/issues/691). But basically looks like this package can't be compiled from source with rust `1.70.0` now.

**Comment by figsoda** [comment]
We can either pull in https://github.com/rust-lang/rust/pull/112266 or wait for rust 1.71 which will be released on july 13. @nixos/rust @vcunat what do you think?

**Comment by meppu** [comment]
Since stable channel is not affected, i think just waiting for a week can be ideal 😅

**Comment by vcunat** [comment]
(pinged) I don't know rust stuff really.  If you're asking about `staging-next`, one iteration will be starting now but another one probably roughly in a week as well.

**Pull request merged**
