### PR TITLE
tomahawk: 0.8.3 -> 0.8.4

### PR DESCRIPTION
**Pull request by devhell**
From the Changelog:
- Fixed drag & drop issues on sidebar.
- Fixed starting Tomahawk with a filename as parameter.
- Update column view when collection changes.
- (Linux) Don't crash on environments with invalid locales.

/cc @aszlig

### CODE REVIEW

**Comment by devhell** [comment]
Built and run successfully, not sure why the travis build failed.

**Comment by FRidh** [comment]
> The invocation of "nix-build -A tomahawk /home/travis/.nox/nixpkgs" failed
> The build failed due to running out of memory:
This is not uncommon on Travis.

I ran `nox-review pr 9858` but after a long time of compiling the building unfortunately failed while attempting to retrieve `quazip-0.7.1.tar.gz`, but that's of course unrelated to the version bump.

**Comment by davidak** [comment]
built successfully on NixOS 15.09 64-bit, playback from a source in the network works also :+1:

**Comment by aszlig** [comment]
Merged, pushing soon, thanks :-)

**Pull request closed without merging**
