### PR TITLE
crabz: fix darwin build

### PR DESCRIPTION
**Pull request by figsoda**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-burns** [comment]
Hmm, this is still failing for me with the same error:

```
   Compiling crabz v0.7.2 (/private/tmp/nix-build-crabz-0.7.2.drv-0/source)
error: linking with `/nix/store/s5yid9p7xgdn2bnh6yys2817y1a71jpr-clang-wrapper-7.1.0/bin/cc` fa
  |
  = note: "/nix/store/s5yid9p7xgdn2bnh6yys2817y1a71jpr-clang-wrapper-7.1.0/bin/cc" "-m64" "-arc
  = note: ld: framework not found System
          clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: could not compile `crabz` due to previous error
```

**Comment by figsoda** [comment]
hmm... How do I get the `System` framework then

**Comment by r-burns** [comment]
Weird, couldn't find it anywhere in nixpkgs. There's an entry here: https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/OSX_Technology_Overview/SystemFrameworks/SystemFrameworks.html

System.framework first available 10.0, "do not use"

**Comment by figsoda** [comment]
added an ugly patch to make it compile, can you confirm that it works?

**Comment by r-burns** [comment]
lol. surely there should be an easier way to do this? I feel like patching the cargo vendor tarball should not be this difficult. Is there a rust maintainer team we can ping?

**Comment by figsoda** [comment]
I don't think there is a rust maintainer team, I hope there is a easier way to patch vendored sources but I couldn't find any

**Comment by happysalada** [comment]
I checked a bit, that https://github.com/Elzair/core_affinity_rs crate is 4 years old, with very little updates, that is why it is relying on an outdated framework.
Regarding patching the vendored source, I only know about `cargoPatches` but it's for a different purpose (patching the cargo file). I checked as well if there was no way to influence compilation with a feature flag, but it doesn't seem so.
Sorry I couldn't be of more help.

**Comment by r-burns** [comment]
No worries, really appreciate you taking a look.

In that case, this looks good to me as a stopgap. It might be a good idea to pester upstream to remove this outdated crate from their dependency graph.

**Comment by happysalada** [comment]
Agreed about talking to upstream if possible.

**Comment by figsoda** [comment]
I opened an issue upstream to remove the dependency on core_affinity

**Pull request merged**
