### PR TITLE
clockify: 2.0.3 -> 2.1.6

### PR DESCRIPTION
**Pull request by WolfangAukang**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by teto** [comment]
no hope they fix it ? the website look alive

**Comment by pbsds** [comment]
If upstream is still alive, then i'd rather mark it insecure

**Comment by WolfangAukang** [comment]
The problem I have found is that after updating the package to the upstream, I wasn't able to get it working. If someone could get it working, then we could manage it as a version upgrade.

**Review by pbsds — COMMENTED** [review]
LGTM, just a minor nit:

It seems the desktop entry has an explicit store reference.
```
$ cat result/share/applications/clockify.desktop | grep Exec
Exec=/nix/store/v6i7pqrx98vwkp8y7mg20w09ssr0s2w0-clockify-2.1.6/bin/clockify %U
```

The store path could be garbage collected. 
This is a problem in desktop environments like Gnome, where startup application desktop entries are copied into a separate directory.
Please change this into `Exec=clockify %U`

**Pull request merged**
