### PR TITLE
onnxruntime: 1.12.1 -> 1.13.1

### PR DESCRIPTION
**Pull request by nagy**
###### Description of changes

Changelog: https://github.com/microsoft/onnxruntime/releases/tag/v1.13.1

cc @FRidh @SebTM @ck3d 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ck3d** [comment]
Result of `nixpkgs-review pr 207845` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>obs-studio-plugins.obs-backgroundremoval</li>
  </ul>
</details>
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>aitrack</li>
    <li>onnxruntime</li>
    <li>python310Packages.invisible-watermark</li>
    <li>python310Packages.onnxruntime</li>
    <li>python39Packages.invisible-watermark</li>
    <li>python39Packages.onnxruntime</li>
  </ul>
</details>

**Comment by nagy** [comment]
The `obs-studio-plugins.obs-backgroundremoval` build failure is reported upstream here:
*  https://github.com/royshil/obs-backgroundremoval/issues/118

**Comment by SebTM** [comment]
> The `obs-studio-plugins.obs-backgroundremoval` build failure is reported upstream here:
> 
>     * [Build fail with onnxruntime 1.13 (git) royshil/obs-backgroundremoval#118](https://github.com/royshil/obs-backgroundremoval/issues/118)

Sadly project seems to be not maintained (at least currently since May), no release since 11/2021 also no response to contact-request like https://github.com/royshil/obs-backgroundremoval/issues/124. How do we proceed with it? Use the latest commit (as unstable-version and add the patch to nixpkgs?

**Comment by nagy** [comment]
I have added a patch to `obs-backgroundremoval` that has been posted here https://github.com/royshil/obs-backgroundremoval/issues/118#issuecomment-1367034595 .

**Review by ck3d — APPROVED** [review]
Thanks for your work, LGTM

**Comment by SebTM** [comment]
I've built and tested the obs-plugin and it builds but different from before it has issues with de-terminating the input source/video source (same-configuration just rebuild of my system with the two commits cherry-picked). So either we mark it as broken/abandon it as unmaintained (described above) or we dig further into the issue?

```
error: [obs-backgroundremoval] Invalid Feed Input Name: �
```
(full log: https://gist.github.com/SebTM/944996f9b2d4d31ede820d5b9e597c29)

**Comment by FRidh** [comment]
Since the project is no longer maintained I am of the opinion we should remove the package. People that do want to use it can a) use an older nixpkgs or b) get it back in Nixpkgs and maintain it.

**Comment by nagy** [comment]
I have removed the package. If somebody in the future comes across this, with a bit of luck this might be a workaround:

```nix
{
  environment.systemPackages = [
    # ...
  ] ++ (with import (fetchFromGitHub {
    owner = "NixOS";
    repo = "nixpkgs";
    rev = "refs/tags/22.11";
    hash = "sha256-/HEZNyGbnQecrgJnfE8d0WC5c1xuPSD2LUpB6YXlg4c=";
  }) { }; [
    obs-studio
    obs-studio-plugins.obs-backgroundremoval
  ]);
}
```

**Review by ck3d — APPROVED** [review]

**Review by SebTM — APPROVED** [review]

**Pull request merged**
