### PR TITLE
linux_xanmod: 6.1.30 -> 6.1.31, 6.3.3 -> 6.3.5

### PR DESCRIPTION
**Pull request by brenix**
###### Description of changes

Updates xanmod kernels to the latest releases

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Atemu — CHANGES_REQUESTED** [review]
6.3.4 broke my audio and I'm not sure 6.3.5 has fixed it. I don't think that should ship to users. Soonest I could re-test would be this weekend.

**Comment by Atemu** [comment]
You need to be running a CPU-intensive task for a bit. It usually takes >10min to repro which makes it really annoying.

**Comment by Shawn8901** [comment]
do you mean shuttering on output or input? i possibly got a similar thing on lts, after some cpu intense task noisetorch (mic filtering) gone into a crazy shuttering.
After switching the input source (non filtered) it was fine again.

**Comment by Atemu** [comment]
@Shawn8901 no such weird setups on my end. See https://github.com/xanmod/linux/issues/373

**Comment by Atemu** [comment]
Could you split the commits @brenix?

**Pull request merged**
