### PR TITLE
anki: 2.0.47 -> 2.0.48

### PR DESCRIPTION
**Pull request by ryantm**
Semi-automatic update
- [x] built on NixOS
- [x] checked binary runs and version 2.0.48 on NixOS

### CODE REVIEW

**Comment by dotlambda** [comment]
There's even a 2.0.49.

**Comment by dotlambda** [comment]
@ryantm Why did you close?

**Comment by ryantm** [comment]
@dotlambda I was going to try to do 2.0.49, but that doesn't seem to work. I'll restore this.

**Comment by adisbladis** [comment]
Quote from upstream:
https://apps.ankiweb.net/docs/changes.html#changes-in-2.0.48

`Built with an updated Python version, which fixes some issues add-ons were having accessing secure sites. Due to regressions with the Linux build, this version is only available for Windows and Mac.`

I say we skip this version.

**Pull request closed without merging**
