### PR TITLE
llvmPackages_{15,16,git}.libcxxabi: fix build on Darwin

### LINKED ISSUE #251091: Build failure: libcxxabi on Darwin
### Steps To Reproduce

1. build libcxxabi on Darwin

### Build log

```
building '/nix/store/ac8awd5c8fj8n0ya3bh5adkcz6mljijz-libcxxabi-15.0.7.drv'...
unpacking sources
unpacking source archive /nix/store/fgdzkqv6f72axj9zgkv94lm9f9wqmns3-libcxxabi-src-15.0.7
source root is libcxxabi-src-15.0.7/runtimes
patching sources
applying patch /nix/store/4hxmswl71hy1dc037qxj2nb6g3hph25b-gnu-install-dirs.patch
patching file CMakeLists.txt
applying patch /nix/store/wjqqjq7dcfr4yslnd21zwsm60rs822xz-e6a0800532bb409f6d1c62f3698bdd6994a877dc.patch
patching file CMakeLists.txt
patching file test/CMakeLists.txt
configuring
fixing cmake files...
cmake flags: -GNinja -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DCMAKE_INSTALL_LOCALEDIR=/nix/store/nrsifj0zdqzv4pvv8mmssq9cphfjlf2z-libcxxabi-15.0.7/share/locale -DCMAKE_INSTALL_LIBEXECDIR=/nix/store/nrsifj0zdqzv4pvv8mmssq9cphfjlf2z-libcxxabi-15.0.7/libexec -DCMAKE_INSTALL_LIBDIR=/nix/store/nrsifj0zdqzv4pvv8mmssq9cphfjlf2z-libcxxabi-15.0.7/lib -DCMAKE_INSTALL_DOCDIR=/nix/store/nrsifj0zdqzv4pvv8mmssq9cphfjlf2z-libcxxabi-15.0.7/share/doc/Runtimes -DCMAKE_INSTALL_INFODIR=/nix/store/nrsifj0zdqzv4pvv8mmssq9cphfjlf2z-libcxxabi-15.0.7/share/info -DCMAKE_INSTALL_MANDIR=/nix/store/nrsifj0zdqzv4pvv8mmssq9cphfjlf2z-libcxxabi-15.0.7/share/man -DCMAKE_INSTALL_OLDINCLUDEDIR=/nix/store/xvsi8zixbqcvh4ypw69dzy9w5a2ikldc-libcxxabi-15.0.7-dev/include -DCMAKE_INSTALL_INCLUDEDIR=/nix/store/xvsi8zixbqcvh4ypw69dzy9w5a2ikldc-libcxxabi-15.0.7-dev/include -DCMAKE_INSTALL_SBINDIR=/nix/store/nrsifj0zdqzv4pvv8mmssq9cphfjlf2z-libcxxabi-15.0.7/sbin -DCMAKE_INSTALL_BINDIR=/nix/store/nrsifj0zdqzv4pvv8mmssq9cphfjlf2z-libcxxabi-15.0.7/bin -DCMAKE_INSTALL_NAME_DIR=/nix/store/nrsifj0zdqzv4pvv8mmssq9cphfjlf2z-libcxxabi-15.0.7/lib -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_OSX_SYSROOT= -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_STRIP=/nix/store/rwb88nwzbrsk2k0ldf1b5scd5yyrfgl9-cctools-binutils-darwin-11.1.0-973.0.1/bin/strip -DCMAKE_RANLIB=/nix/store/dan3imi2bd0nv5vq10i53a3wqsfc5ya7-clang-wrapper-15.0.7/bin/ranlib -DCMAKE_AR=/nix/store/dan3imi2bd0nv5vq10i53a3wqsfc5ya7-clang-wrapper-15.0.7/bin/ar -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX=/nix/store/nrsifj0zdqzv4pvv8mmssq9cphfjlf2z-libcxxabi-15.0.7 -DLLVM_ENABLE_RUNTIMES=libcxxabi -DLIBCXXABI_LIBCXX_INCLUDES=/nix/store/kd08z58zhhpvrww8a2f74dx1dr3frggb-libcxx-headers-15.0.7/include/c++/v1 -DCMAKE_CXX_COMPILER_WORKS=ON -DCMAKE_EXE_LINKER_FLAGS=-nostdlib -DCMAKE_SHARED_LINKER_FLAGS=-nostdlib
-- The C compiler identification is Clang 15.0.7
-- The CXX compiler identification is Clang 15.0.7
-- The ASM compiler identification is Clang with GNU-like command-line
-- Found assembler: /nix/store/dan3imi2bd0nv5vq10i53a3wqsfc5ya7-clang-wrapper-15.0.7/bin/clang
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /nix/store/dan3imi2bd0nv5vq10i53a3wqsfc5ya7-clang-wrapper-15.0.7/bin/clang
-- Check for working C compiler: /nix/store/dan3imi2bd0nv5vq10i53a3wqsfc5ya7-clang-wrapper-15.0.7/bin/clang - broken
CMake Error at /nix/store/inh6dp2sykgdnh6g4sblmng1s89vz08c-cmake-3.26.4/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:67 (message):
  The C compiler

    "/nix/store/dan3imi2bd0nv5vq10i53a3wqsfc5ya7-clang-wrapper-15.0.7/bin/clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /tmp/nix-build-libcxxabi-15.0.7.drv-0/libcxxabi-src-15.0.7/runtimes/build/CMakeFiles/CMakeScratch/TryCompile-t6lOIn

    Run Build Command(s):/nix/store/mqyp4gwyppmcykj3vk3ig9z1lgnvrrji-ninja-1.11.1/bin/ninja -v cmTC_72306 && [1/2] /nix/store/dan3imi2bd0nv5vq10i53a3wqsfc5ya7-clang-wrapper-15.0.7/bin/clang    -MD -MT CMakeFiles/cmTC_72306.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_72306.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_72306.dir/testCCompiler.c.o -c /tmp/nix-build-libcxxabi-15.0.7.drv-0/libcxxabi-src-15.0.7/runtimes/build/CMakeFiles/CMakeScratch/TryCompile-t6lOIn/testCCompiler.c
    [2/2] : && /nix/store/dan3imi2bd0nv5vq10i53a3wqsfc5ya7-clang-wrapper-15.0.7/bin/clang  -Wl,-search_paths_first -Wl,-headerpad_max_install_names -nostdlib CMakeFiles/cmTC_72306.dir/testCCompiler.c.o -o cmTC_72306   && :
    FAILED: cmTC_72306
    : && /nix/store/dan3imi2bd0nv5vq10i53a3wqsfc5ya7-clang-wrapper-15.0.7/bin/clang  -Wl,-search_paths_first -Wl,-headerpad_max_install_names -nostdlib CMakeFiles/cmTC_72306.dir/testCCompiler.c.o -o cmTC_72306   && :
    ld: dynamic main executables must link with libSystem.dylib for architecture x86_64
    clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.


  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)


-- Configuring incomplete, errors occurred!
error: builder for '/nix/store/ac8awd5c8fj8n0ya3bh5adkcz6mljijz-libcxxabi-15.0.7.drv' failed with exit code 1
```

### Additional context

Could this be caused by https://github.com/NixOS/nixpkgs/pull/246577 ? (@pwaller)

### Notify maintainers
@vlstill 

### Metadata

```
- system: `"x86_64-darwin"`
 - host os: `Darwin 22.5.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(djm): `"home-manager, nixpkgs, unstable"`
 - nixpkgs: `/Users/djm/.nix-defexpr/channels/nixpkgs`
 ```

### PR DESCRIPTION
**Pull request by reckenrode**
## Description of changes

Fixes #251091 by excluding Darwin from the libc++abi build changes in #246577. I was able to build mpv.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by RaitoBezarius — APPROVED** [review]
Do not have Darwin machine but I have seen people saying this fixed their issue, diff LGTM.

**Comment by vcunat** [comment]
I suggest you watch ofBorg.  You'd know in advance that this breaks build on `*-linux`.  On Hydra now: https://hydra.nixos.org/eval/1798783#tabs-now-fail

**Comment by RaitoBezarius** [comment]
Ugh, you are right, I misread the CI checks, my sincere apologies. I will revert this and revert the original PR that seems to create issues on Darwin.

**Comment by RaitoBezarius** [comment]
Follow-up fix in https://github.com/NixOS/nixpkgs/pull/251566 as, with enough rest, I can determine the cause quite fast.

**Pull request merged**
