### PR TITLE
ipv6calc: 2.2.0 -> 3.2.0

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 3.2.0

Change log: 
- https://github.com/pbiering/ipv6calc/releases/tag/3.2.0
- https://github.com/pbiering/ipv6calc/releases/tag/3.1.1
- https://github.com/pbiering/ipv6calc/releases/tag/3.1.0
- https://github.com/pbiering/ipv6calc/releases/tag/3.0.2
- https://github.com/pbiering/ipv6calc/releases/tag/3.0.1
- https://github.com/pbiering/ipv6calc/releases/tag/3.0.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 136168` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>ip2location-c</li>
    <li>ipv6calc</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
```
$ ./bin/ip2location 
Datafile is absent

$ fd
bin
bin/ip2location
include
include/IP2Location.h
lib
lib/libIP2Location.la
lib/libIP2Location.so
lib/libIP2Location.so.3
lib/libIP2Location.so.3.0.0
share
share/man
share/man/man1
share/man/man1/ip2location.1.gz
```

That looks somewhat incomplete.

**Comment by fabaff** [comment]
For some databases a license is [required](https://www.ip2location.com/database/ip2location). They provide free databases called  "IP2Location™ LITE". Those are licensed under CC-BY-SA, require a specific acknowledgment and have lower data accuracy than the licensed DBs. E.g., 

```bash
]$ ./bin/ip2location -d /home/fab/geo-location/IP2LOCATION-LITE-DB1.BIN -p 80.219.53.100 -e country_name
"country_name"
"Switzerland"
```

I don't think that we should ship those DBs and leave it up to the user to decide which one to use. From a `ipv6calc` point of view this is somehow an inconvenience as lookups are only backed by built-in data.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 136168` at ed7e5ab3 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>ip2location-c</li>
    <li>ipv6calc</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/libraries/ip2location-c/default.nix:38:5:
```
   |
38 |     maintainers = with maintainers; [ ];
   |     ^
```
</li>
  </ul>
</details>

**Pull request merged**
