### PR TITLE
lz4: patch cmake to generate unified target

### LINKED ISSUE #322003: Build failure: arrow-cpp (staging branch)
### Steps To Reproduce

At **staging** (not `master`):
1. nix build .#arrow-cpp

### Build log

```
--   Outputting build configuration summary to /build/apache-arrow-16.0.0/cpp/build/cmake_summary.json
-- Configuring done (13.8s)
CMake Error at src/arrow/CMakeLists.txt:592 (target_link_libraries):
  Target "arrow_util" links to:

    LZ4::lz4

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```
Full log: https://termbin.com/i0tg

### Additional context

(I've opened this to log or look after a solution for this.)

* For debug purposes, reverting #318512 fixes `arrow-cpp` build.

### Notify maintainers

CC @tobim @veprbl @cpcloud

### PR DESCRIPTION
**Pull request by tobim**
Fixes #322003.

## Description of changes

Integrated changes from:
* https://github.com/lz4/lz4/pull/1372
* https://github.com/lz4/lz4/pull/1413

Dropped a patch for the `make` based build that is not used any more.

Added myself as a maintainer of the package.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by superherointj — APPROVED** [review]
LGTM. `lz4` and `arrow-cpp` are building fine.

**Review by superherointj — APPROVED** [review]

**Review by Scrumplex — APPROVED** [review]

**Comment by mweinelt** [comment]
Needs to target staging-next.

**Review by SuperSandro2000 — APPROVED** [review]
didn't test but LGTM

**Review by makuru-org — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
@ofborg build lz4

**Pull request merged**
