### PR TITLE
mxu11x0: 1.3 -> 1.4

### PR DESCRIPTION
**Pull request by uralbash**
###### Motivation for this change

The new version fixes a bug with the latest versions of linux kernel

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by matthiasbeyer — APPROVED** [review]
Patch looks good to me.

**Review by matthiasbeyer — CHANGES_REQUESTED** [review]
"Update default.nix" is not a good commit message. "Remove unnecessary imports" is better.

**Comment by uralbash** [comment]
@matthiasbeyer fixed

**Review by matthiasbeyer — APPROVED** [review]

**Comment by c0bw3b** [comment]
@GrahamcOfBorg build linuxPackages_4_9.mxu11x0 linuxPackages_5_0.mxu11x0

**Pull request merged**
