### PR TITLE
Fixed output deps

### PR DESCRIPTION
**Pull request by Ericson2314**
###### Motivation for this change

Fixed output derivations should (almost) never have run-time dependencies.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

CC @dtzWill

### CODE REVIEW

**Comment by Ericson2314** [comment]
The darwin stdenv label is a red herring: it's still cached from fixed output. Not sure what the deal is with the 11-100 Linux packages. @GrahamcOfBorg you know how to get the list?

**Comment by vcunat** [comment]
@Ericson2314: one could modify the script `<nixpkgs/maintainers/scripts/rebuild-amount.sh>` not to delete the temporary files.

**Comment by vcunat** [comment]
Oh, it's actually easier to remove the last couple of lines that just counts the number of packages :-)
<details><pre>
Estimating rebuild amount by counting changed Hydra jobs.
boogie.x86_64-darwin                                                       /nix/store/8w4s7qyh0fkm4wqbmvnz2lmbqc478bvq-Boogie-unstable-2017-01-03
boogie.x86_64-linux                                                        /nix/store/5rb1wnsp6r6cjyhgcwa4dkfmiis6fjp6-Boogie-unstable-2017-01-03
dafny.x86_64-darwin                                                        /nix/store/kdp9xkgs2837vmpx68vb1a9a9lb1n8xq-Dafny-1.9.8
dafny.x86_64-linux                                                         /nix/store/8bnmrxgphnv0nmrmxhfakqacp2rk5d2l-Dafny-1.9.8
dotnetPackages.Autofac.x86_64-linux                                        /nix/store/hcfv6m75a105rnvnz6pgyg1nl8sqli7n-Autofac-3.5.2
dotnetPackages.Boogie.x86_64-darwin                                        /nix/store/8w4s7qyh0fkm4wqbmvnz2lmbqc478bvq-Boogie-unstable-2017-01-03
dotnetPackages.Boogie.x86_64-linux                                         /nix/store/5rb1wnsp6r6cjyhgcwa4dkfmiis6fjp6-Boogie-unstable-2017-01-03
dotnetPackages.Dafny.x86_64-darwin                                         /nix/store/kdp9xkgs2837vmpx68vb1a9a9lb1n8xq-Dafny-1.9.8
dotnetPackages.Dafny.x86_64-linux                                          /nix/store/8bnmrxgphnv0nmrmxhfakqacp2rk5d2l-Dafny-1.9.8
dotnetPackages.Deedle.x86_64-linux                                         /nix/store/52y685ibcb7w6s4j957fdjcqc5w6f772-Deedle-1.2.0
dotnetPackages.ExtCore.x86_64-linux                                        /nix/store/akrdyaixhwjy0vhssgd8pjx9wwm4439h-ExtCore-0.8.46
dotnetPackages.Fake.x86_64-linux                                           /nix/store/86kmw7rgi5br4dwyqdpc8dks6847srb4-FAKE-3.33.0
dotnetPackages.Fantomas.x86_64-linux                                       /nix/store/f97cny6ywrl9idb5yhv47dda6mrflxx2-Fantomas-1.6.0
dotnetPackages.FsCheck262.x86_64-linux                                     /nix/store/rhk3052vnh1whjddm4skvsxs7vgqp25m-FsCheck-2.6.2
dotnetPackages.FsCheckNunit.x86_64-linux                                   /nix/store/0n7zraaa7sj62llqgp043kz3gl6zkx13-FsCheck.Nunit-1.0.4
dotnetPackages.FsCheck.x86_64-linux                                        /nix/store/7vgfc081z7h34nryw5wfgg7p4qhjh06a-FsCheck-1.0.4
dotnetPackages.FSharpAutoComplete.x86_64-linux                             /nix/store/layz1x0gs3340ka35hbwydg25qnvibs2-FSharp.AutoComplete-0.18.2
dotnetPackages.FSharpCompilerCodeDom.x86_64-linux                          /nix/store/qx7vr8adn15v0pz0slbllvwlp0wi7kmd-FSharp.Compiler.CodeDom-0.9.2
dotnetPackages.FSharpCompilerService.x86_64-linux                          /nix/store/75kaszk9vcsn64is3r7iplssjhjxd3nv-FSharp.Compiler.Service-0.0.90
dotnetPackages.FSharpCompilerTools.x86_64-linux                            /nix/store/32d9gpjrhj7h1rlgmcfvivdpfxa3kkjz-FSharp.Compiler.Tools-4.1.4
dotnetPackages.FSharpCore.x86_64-linux                                     /nix/store/1nyac8fk3l2mdj99k0wf0cly2qjlhmfk-FSharp.Core-4.0.0.1
dotnetPackages.FSharpData225.x86_64-linux                                  /nix/store/104qxpc8n8x49vypmzpahj5ldn6nq8pf-FSharp.Data-2.2.5
dotnetPackages.FSharpDataSQLProvider.x86_64-linux                          /nix/store/wpb1pw0h9x0g7ykvfd8j1vlczj1ncn6p-SQLProvider-0.0.9-alpha
dotnetPackages.FSharpFormatting.x86_64-linux                               /nix/store/pc4ap2khyvk0sfc8wx3qaxyv1a87qwr5-FSharp.Formatting-2.9.8
dotnetPackages.FsLexYacc704.x86_64-linux                                   /nix/store/gd1rpq847wc4770myy6qzbhargsgsykc-FsLexYacc-7.0.4
dotnetPackages.FsLexYacc.x86_64-linux                                      /nix/store/pgdn8qzdns6yddfjvihcm5l6b82ahbnp-FsLexYacc-6.1.0
dotnetPackages.FsPickler.x86_64-linux                                      /nix/store/1s2cdwrvfnmsk76xqyvz4cnhqpbd01k7-FsPickler-1.2.9
dotnetPackages.FsUnit.x86_64-linux                                         /nix/store/1cmbg2g983hp57l2sjx08zrapj9bc44d-FsUnit-1.3.0.1
dotnetPackages.FuzzyLogicLibrary.x86_64-linux                              /nix/store/akl2q4ln3wsnhsc3qiai2li25z7vw5b7-FuzzyLogicLibrary-1.2.0
dotnetPackages.MaxMindDb.x86_64-linux                                      /nix/store/yr97mzan22giby9k7c35vvcrijkp8912-MaxMind.Db-1.1.0.0
dotnetPackages.MaxMindGeoIP2.x86_64-linux                                  /nix/store/030mlm7l40lfa944gw7bz8g4qbfxigi6-MaxMind.GeoIP2-2.3.1
dotnetPackages.MicrosoftDiaSymReaderPortablePdb.x86_64-linux               /nix/store/9051wp9ayby5nafvyhd4251k3djwz1gn-Microsoft.DiaSymReader.PortablePdb-1.2.0
dotnetPackages.MicrosoftDiaSymReader.x86_64-linux                          /nix/store/1snqhf16c2wx8yjvh0wfvnhgdgwhqq7n-Microsoft.DiaSymReader-1.1.0
dotnetPackages.MonoNat.x86_64-linux                                        /nix/store/928pzjynciqrbslrchbl68619mdnym3m-Mono.Nat-1.2.24
dotnetPackages.NewtonsoftJson.x86_64-linux                                 /nix/store/n14z4ha1i5hg3q10hrcvn2lf70xkjwvd-Newtonsoft.Json-6.0.8
dotnetPackages.NUnit2.x86_64-linux                                         /nix/store/dvzpk5y3sw6habz60wl27gkphzcf3hrg-NUnit-2.6.4
dotnetPackages.NUnit350.x86_64-linux                                       /nix/store/i1x166dbscdsm160r6hbmvf7qknzglgx-NUnit-3.5.0
dotnetPackages.NUnit3.x86_64-linux                                         /nix/store/qnhms356825h9rdzg67p69g457hhxakd-NUnit-3.0.1
dotnetPackages.NUnitConsole.x86_64-linux                                   /nix/store/dv354sa9vnzjblaxcnph360ry4k2s4ck-NUnit.Console-3.0.1
dotnetPackages.NUnitRunners.x86_64-linux                                   /nix/store/c0ycm62nr1il2g1n5sil5vk7aasqfk6p-NUnit.Runners-2.6.4
dotnetPackages.NUnit.x86_64-linux                                          /nix/store/dvzpk5y3sw6habz60wl27gkphzcf3hrg-NUnit-2.6.4
dotnetPackages.OpenNAT.x86_64-linux                                        /nix/store/551zxnqvvz3ng4f32jhc2y6nrv49as5k-Open.NAT-2.1.0
dotnetPackages.Paket.x86_64-linux                                          /nix/store/0scwq8dssvia3p9pw9z7bml2m37zfk2j-Paket-1.18.2
dotnetPackages.Projekt.x86_64-linux                                        /nix/store/49giwirdl4g2b9d2w3vq0fpgikalq4jc-projekt-git-715a21e5cd
dotnetPackages.RestSharp.x86_64-linux                                      /nix/store/36j5jxhbqkh1jvvdvhny8sr9zgx8n3mj-RestSharp-105.2.3
dotnetPackages.SharpFont.x86_64-linux                                      /nix/store/6ak3h8mzz727a2c2fyqzz1ap5i3f1xqd-SharpFont-3.1.0
dotnetPackages.SharpZipLib.x86_64-linux                                    /nix/store/qmbjxsfzi06f2flnrkp74md9b5n020dx-SharpZipLib-0.86.0
dotnetPackages.SmartIrc4net.x86_64-linux                                   /nix/store/lz0m04lcsjkqnzjmhrq14pqairhhfgif-SmartIrc4net-0.4.5.1
dotnetPackages.StyleCopMSBuild.x86_64-linux                                /nix/store/zh61vh19bywxpig8y31iixvwi8l4y8w2-StyleCop.MSBuild-4.7.49.0
dotnetPackages.StyleCopPlusMSBuild.x86_64-linux                            /nix/store/k5xfps9rq5wi1wx4p8amqn20ay05pv19-StyleCopPlus.MSBuild-4.7.49.5
dotnetPackages.Suave.x86_64-linux                                          /nix/store/c9604wxvmq7ahnzpxppr870mipprlg41-Suave-0.29.0
dotnetPackages.SystemCollectionsImmutable131.x86_64-linux                  /nix/store/44mblqg78j1bkb3z5bqw42lh3y9wqasn-System.Collections.Immutable-1.3.1
dotnetPackages.SystemCollectionsImmutable.x86_64-linux                     /nix/store/abvsxp0b0czvs55ahxsqjamngvy87pra-System.Collections.Immutable-1.1.36
dotnetPackages.SystemReflectionMetadata.x86_64-linux                       /nix/store/gs7906j3d14fgkzvm9rjp74gc9akqhcb-System.Reflection.Metadata-1.4.2
dotnetPackages.SystemValueTuple.x86_64-linux                               /nix/store/xwbp394gpg019dsxrwvklj39i5xk789c-System.ValueTuple-4.3.0
dotnetPackages.UnionArgParser.x86_64-linux                                 /nix/store/7sdxnns70rvqr46i8vnhfx9rk1ndjhvi-UnionArgParser-0.8.7
fsharp41.x86_64-darwin                                                     /nix/store/d9dkwp0qd3zmwxkmm6bm9raxnggwrvdj-fsharp-4.1.7
fsharp41.x86_64-linux                                                      /nix/store/5m06dq0zygr9ilv45y3nb5xa9gwxj9ly-fsharp-4.1.7
gdata-sharp.x86_64-linux                                                   /nix/store/fzqcpm1p7mk5mnrkd5d1isyq5cjby368-gdata-sharp-2.2.0.0
monodevelop.x86_64-linux                                                   /nix/store/3b1k4a0ymab44r690kk1p6zsdfjfyqgw-monodevelop-5.9.4.5
openra.x86_64-linux                                                        /nix/store/b1d3q4g596l25sci2nzgc3m316vrxyy4-openra-20171014
uni-vga.x86_64-linux                                                       /nix/store/fa6j7v6drxij1vpa7hpvwk39lkmm28i7-uni-vga
</pre>
</details>

**Comment by vcunat** [comment]
Inspired to https://github.com/NixOS/nixpkgs/pull/33693

**Comment by Ericson2314** [comment]
OK the one "rebuild" here seems to be in error. it's just a fixed output derivation.

**Pull request merged**
