### PR TITLE
ccache: 4.2 -> 4.2.1

### PR DESCRIPTION
**Pull request by kira-bruneau**
###### Motivation for this change
Update to the latest version: https://github.com/ccache/ccache/releases/tag/v4.2.1

###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

@r-burns @veprbl

### CODE REVIEW

**Comment by MetaDark** [comment]
I've created an upstream pull request for `env-instead-of-compgen.patch`: https://github.com/ccache/ccache/pull/835/files.

**Comment by MetaDark** [comment]
Also, `test.basedir` usually passes on Darwin, but it occasionally fails, so I've disabled it.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 119176` at dbeee740 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>ccache</li>
    <li>ccacheStdenv</li>
  </ul>
</details>

**Review by r-burns — APPROVED** [review]
Thanks!

Result of `nixpkgs-review pr 119176` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>ccache</li>
    <li>ccacheStdenv</li>
  </ul>
</details>

**Comment by Kha** [comment]
@kira-bruneau It looks like test.modules started failing again on Hydra some while ago: https://hydra.nixos.org/build/144701939/nixlog/1
Do you know if it's the same error message as before?

**Comment by r-burns** [comment]
Hmm, so this broke between the 4.2.1 bump and the 4.3 bump. Git bisect tells me that something in the #122068 staging-next cycle was the cause. @kira-bruneau, I think our macOS testing setups must differ in some way if https://github.com/NixOS/nixpkgs/pull/122492#issuecomment-837413608 succeeded for you. I'm on 10.15 with a sandboxed multi-user Nix install and getting the same errors as hydra.

**Comment by Kha** [comment]
Ah, I suppose sandbox on/off might explain it!
(I don't use macOS myself, just on CI)

**Comment by kira-bruneau** [comment]
Oh right, yeah sorry I had the sandbox disabled because there were some problems with it on Big Sur: https://github.com/NixOS/nix/issues/4658. I think the fix should be available in `nixUnstable`, so I will try it out.

**Comment by r-burns** [comment]
I bisected the issue to 96bbe339d47d4bc78cc9eaf0845734f80fe2d56b but don't see why that would have caused this regression.

Maybe the `isCxx` flag in the cc-wrapper is not being set (so c++ includes are not available) because clang is not being invoked like a typical c++ compiler? The command line in the module test looks like this:
`/tmp/nix-build-ccache-4.2.1.drv-0/source/build/ccache clang -fmodules -fcxx-modules -c test1.cpp -MD`

The progname is simply `clang` and there is no `-x c++` option, so maybe we should add another case to the cc-wrapper so that `-fcxx-modules` enables `isCxx`:
https://github.com/NixOS/nixpkgs/blob/961cae37edeb34b5dec8060e49e5abbde3af9c00/pkgs/build-support/cc-wrapper/cc-wrapper.sh#L54-L55

Or maybe c++ includes should always be enabled, since clang is able to automatically detect that this .cpp file is c++.

**Comment by r-burns** [comment]
Ok, now that I've looked at this a bit, it's much more clear to me. https://github.com/NixOS/nixpkgs/commit/96bbe339d47d4bc78cc9eaf0845734f80fe2d56b broke this because after that revert, including C++ standard library headers requires `isCxx` to be set, in addition to the more lenient `cxxInclude`.

https://github.com/NixOS/nixpkgs/commit/54c7a0f42287f63c2db8086a8ad46ac981364378 must have fixed the ccache module test, which is why we were were able to originally un-disable it. My kneejerk reaction is to want to un-revert the commit, but clearly there are bigger-picture issues with making the C++ standard library includes always available, so I'll leave that to people more versed in stdenv.

In the meantime, I see two potential fixes for this:
- tell ccache to use `-x c++` when using ordinary `clang` to compile C++ code, as our toolchain otherwise won't enable C++ standard library includes
- have `-fcxx-modules` enable `isCxx`

**Pull request merged**
