### PR TITLE
Regroup all themes under data/themes

### PR DESCRIPTION
**Pull request by c0bw3b**
###### Motivation for this change

Top-level `misc` folder is really not a good place to put things away so :
\+ move remaining mislocated themes under `data/themes`
\+ updated 3 KDE themes
\+ locate GTK theming libraries ("engines") under `development/libraries`

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @romildo @gnidorah

### CODE REVIEW

**Comment by romildo** [comment]
I think that the GTK theming libraries (_engines_) should not be at `pkgs/desktops`. In my understanding this directory is for desktop environments, and not for single libraries.

Maybe they should go to `pks/development/libraries`, like the `qvantum` package. But I am not sure.

**Comment by c0bw3b** [comment]
My reasoning was these engines are used for the theming of GTK-based desktop envs.
But I initially thought about about `dev/libraries` too :) because well... it is libs. :)
I'll change that.

**Review by worldofpeace — APPROVED** [review]

**Review by romildo — APPROVED** [review]

**Comment by worldofpeace** [comment]
I think we need to update https://nixos.org/nixpkgs/manual/#sec-hierarchy to include themes.
If follow it's instructions currently, I think most people are assuming it'll go under some place in misc.

**Comment by c0bw3b** [comment]
Indeed, I'll try and prepare a PR for the manual

**Pull request merged**
