### PR TITLE
cmake: Setup default macOS flags

### PR DESCRIPTION
**Pull request by matthewbauer**
###### Motivation for this change

This is a collection of new defaults to setup for CMake related to macOS. Many packages are already setting these, but this will just make them the default. If I have time, I can make a treewide commit that removes references to these flags.

This could potentially break many packages, so it should be extensively tested. If someone could setup a Hydra jobset for this, that would be great!

Also related to #36834

### CODE REVIEW

**Comment by matthewbauer** [comment]
Does anyone have issues with this? Will merge soon if no issues.

**Review by LnL7 — APPROVED** [review]
Looks good to me, I can push this to my wip job if this should be tested more extensively before merging to staging.

**Review by matthewbauer — COMMENTED** [review]
Yes a Hydra job would be helpful.

**Comment by LnL7** [comment]
@matthewbauer Any thoughts on a list of packages to test for this, building all of nixpkgs on the official hydra is maybe not the best idea given the limited build capacity.

**Comment by matthewbauer** [comment]
Okay I'll just merge to staging and watch what happens. It shouldn't break anything that wasn't already broken.

**Comment by LnL7** [comment]
I would be surprised if this causes any major issues, if everything looks ok we should probably backport this to 18.03. I've seen a number of build failures that look related to this.

**Pull request merged**
