### PR TITLE
elmPackages.elm-format: build using hspec-tasty 1.1.6, hspec-golden 0.1.0.3

### LINKED ISSUE #167533: `elm-format` fails to build
### Describe the bug
`elm-format` fails to build on latest `master`

### Steps To Reproduce
1. Attempt to build `elm-format` on latest `master`

### Expected behavior
Successful build

### Additional context
```
builder for '/nix/store/chv2sni9b6mmz5x82kqyvi4ihh0vsv28-elm-format-test-lib-0.0.0.1.drv' failed with exit code 1; last 10 log lines:
    $, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:1024:20 in Cabal-3.2.1.0:Distribution.Simple.Configure
    configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:477:12 in Cabal-3.2.1.0:Distribution.Simple.Configure
    configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:625:20 in Cabal-3.2.1.0:Distribution.Simple
    confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:65:5 in Cabal-3.2.1.0:Distribution.Simple.UserHooks
    configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:180:19 in Cabal-3.2.1.0:Distribution.Simple
    defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:116:27 in Cabal-3.2.1.0:Distribution.Simple
    defaultMain, called at /nix/store/4mdp8nhyfddh7bllbi7xszz7k9955n79-Setup.hs:2:8 in main:Main
  Setup: Encountered missing or private dependencies:
  hspec-golden >=0.1.0.3 && <0.2, tasty-hspec >=1.1.5.1 && <1.2
cannot build derivation '/nix/store/kg1k8zfq2m8wmai06qd1zyq1wklal5hf-elm-format-0.8.5.drv': 1 dependencies couldn't be built
```

See upstream dependency definitions https://github.com/avh4/elm-format/blob/fd1d240f0574879e46b5909377ff6d8a54cbe6be/elm-format-test-lib/elm-format-test-lib.cabal#L41-L45

Interestingly, dependant packages were last updated a long time ago 7d89be36a863 991041b33a18

### Notify maintainers

Not sure who to notify:
```
$ rg 'maintainers' pkgs/development/compilers/elm/packages
pkgs/development/compilers/elm/packages/elm-test-rs.nix
29:    maintainers = [ maintainers.jpagex ];

pkgs/development/compilers/elm/packages/elm-json.nix
37:    maintainers = [ maintainers.turbomack ];
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.8-zen1, NixOS, 21.11 (Porcupine), 21.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - nixpkgs: `/home/rvolosatovs/src/github.com/rvolosatovs/infrastructure/vendor/nixpkgs/nixos-unstable`
```

### PR DESCRIPTION
**Pull request by aforemny**
###### Description of changes

elm-format depends on elm-format-lib which failed to build with
hspec-tasty 1.1.7 and hspec-golden 0.2.0.0.

hspec-tasty 1.1.6 and hspec-golden 0.1.0.3 had been removed in
cd67b4fcbb81d07477746a138d6dbb9d01a81450.

hspec-tasty 1.1.6 in turn pulls in older dependencies for hspec,
hspec-core and hspec-discover.

Fixes #167533.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aforemny** [comment]
Converting to draft as it seems there is still some work to do:

<details>
<summary>

```
nix-shell -p nixpkgs-review --run 'nixpkgs-review rev HEAD'

3 packages failed to build:
elmPackages.elm-coverage elmPackages.elm-verify-examples elmPackages.elmi-to-json

4 packages built:
elmPackages.create-elm-app elmPackages.elm elmPackages.elm-format elmPackages.elm-instrument
```

</summary>

```
error: builder for '/nix/store/fl3xxqz9gxjybdnzf3414xy0jxav7j5n-aeson-2.0.3.0.drv' failed with exit code 1;
       last 10 log lines:
       >   $, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:1024:20 in Cabal-3.2.1.0:Distribution.Simple.Configure
       >   configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:477:12 in Cabal-3.2.1.0:Distribution.Simple.Configure
       >   configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:625:20 in Cabal-3.2.1.0:Distribution.Simple
       >   confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:65:5 in Cabal-3.2.1.0:Distribution.Simple.UserHooks
       >   configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:180:19 in Cabal-3.2.1.0:Distribution.Simple
       >   defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:116:27 in Cabal-3.2.1.0:Distribution.Simple
       >   defaultMain, called at Setup.lhs:3:10 in main:Main
       > Setup: Encountered missing or private dependencies:
       > attoparsec >=0.14.2 && <0.15
       >
       For full logs, run 'nix log /nix/store/fl3xxqz9gxjybdnzf3414xy0jxav7j5n-aeson-2.0.3.0.drv'.
error: 1 dependencies of derivation '/nix/store/jsdx1fcpj6hv118fhm5p6jnb9wh7f3j4-yaml-0.11.8.0.drv' failed to build
error: 2 dependencies of derivation '/nix/store/51c9pd8kggpqyfnyky4vgsf45l1ifhiv-hpack-0.34.6.drv' failed to build
error: 2 dependencies of derivation '/nix/store/nlwymngfppmg88ki3h38pxn1lb7i00m4-elmi-to-json-1.3.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ri2fv81fwkbli5mqq41z9z5q8vxs6rc9-elm-verify-examples-5.2.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/gxlvcf6x0rgyj3hrxks8vbyz5mkryddz-elm-coverage-0.4.1.drv' failed to build
error: 3 dependencies of derivation '/nix/store/4xvsg4n2r3pg6f1cjrkbyyrjk475pjr6-review-shell.drv' failed to build
```
</details>

**Comment by aforemny** [comment]
```
nix-shell -p nixpkgs-review --run 'nixpkgs-review rev HEAD'
7 packages built:
elmPackages.create-elm-app elmPackages.elm elmPackages.elm-coverage elmPackages.elm-format elmPackages.elm-instrument elmPackages.elm-verify-examples elmPackages.elmi-to-json
```

**Comment by turboMaCk** [comment]
Thanks @aforemny.

@maralorn are you ok with us adding these extra versions o flibs to Haskell package set or should we do these only in our override?

**Comment by sternenseemann** [comment]
> One issue here is that we only test elmPackages.elm on the haskell-updates branch. None of the other mentioned packages here. So we will not notice if we break any of them.

I want to add them. From what I gathered so far, these are the Haskell based derivations in `elmPackages`:

* `elm`
* `elm-format`
* `elm-instrument`
* `elmi-to-json`

Any others?

**Comment by turboMaCk** [comment]
@maralorn I don't think we should put more burden on haskell maintainers. We can take care of breakages if they occur.

It also seems changes in this PR are related to fixes to 4 packages in total. Commit message will need to change. Anyway more important question for me is if we should be putting elm specific overrides into Haskell set in first place. We can do all of this in `elmPackages` scope.

**Comment by turboMaCk** [comment]
@sternenseemann that is indeed complete list. But I also don't expect these to move together with rest of the haskell ecosystem. Most likely they will move together with elm (compiler) releases so they might be a bit annoying to maintain for you during reoccurring work on haskellPackages.

**Comment by sternenseemann** [comment]
> @sternenseemann that is indeed complete list. But I also don't expect these to move together with rest of the haskell ecosystem. Most likely they will move together with elm (compiler) releases so they might be a bit annoying to maintain for you during reoccurring work on haskellPackages.

I think it makes sense, we can still choose to ignore regressions, but it's useful to know they exist, so we can coordinate with you for a workaround. I imagine it's much more annoying for you to find out that elm-related things broke all of a sudden on `master`.

**Pull request merged**
