### PR TITLE
vapoursynth: 65 → 69

### PR DESCRIPTION
**Pull request by illdefined**
## Description of changes

- Updated `src` to latest upstream version,
- adapted and simplified Nix plugin loader, and
- reformatted and moved files to fit new contributing guidelines.

Upstream change log: <https://github.com/vapoursynth/vapoursynth/blob/R69/ChangeLog>

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by rnhmjoj** [comment]
Did you test it? I have been postponing updates intentionally because 66 was broken: https://github.com/NixOS/nixpkgs/pull/294451

**Comment by illdefined** [comment]
> Did you test it? I have been postponing updates intentionally because 66 was broken: #294451

I tested `vspipe` and `vsedit` both without any plugins and with the `pkgs.ffms` plugin. I shall test mpv, too.

**Comment by illdefined** [comment]
mpv works fine as well when wrapped.

**Comment by illdefined** [comment]
Result of `nixpkgs-review pr 332199` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li>av1an</li>
    <li>av1an-unwrapped</li>
    <li>python311Packages.vapoursynth</li>
    <li>python311Packages.vapoursynth.dist</li>
    <li>python312Packages.vapoursynth</li>
    <li>python312Packages.vapoursynth.dist</li>
    <li>svp</li>
    <li>vapoursynth</li>
    <li>vapoursynth-editor</li>
    <li>vapoursynth-mvtools</li>
  </ul>
</details>

**Comment by illdefined** [comment]
av1an appears to work as well.

svp builds and starts, but I have not performed any more extensive tests.

**Review by rnhmjoj — APPROVED** [review]
I tested my script in mpv with `vapoursynthSupport` and `vapoursynth.withPlugins`: looks all good. It would be interesting to know how/when the problem was fixed, but I don't have time to run a bisection.

**Pull request merged**
