### PR TITLE
ollama: 0.1.48 -> 0.2.1

### LINKED ISSUE #326038: Update request: Ollama 0.1.48 → 0.2.1
- Package name: Ollama
- Latest released version: 0.2.1

- Current version on the unstable channel: 0.1.48
- Current version on the stable/release channel: 0.1.38

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@abysssol

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by redyf**
## Description of changes

changelog: [release 0.2.0](https://github.com/ollama/ollama/releases/tag/v0.2.0)
changelog: [release 0.2.1](https://github.com/ollama/ollama/releases/tag/v0.2.1)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [x] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by abysssol — COMMENTED** [review]
Diff looks good except for the `vendorHash`, did it not need to be updated?

However, I happened to choose today to update ollama as well, so I just recently created #326867 before seeing that you had created this. Since my pr updates to 0.2.3 which is more recent, should this pr be closed?

**Comment by redyf** [comment]
> Diff looks good except for the `vendorHash`, did it not need to be updated?
> 
> However, I happened to choose today to update ollama as well, so I just recently created #326867 before seeing that you had created this. Since my pr updates to 0.2.3 which is more recent, should this pr be closed?

Initially I made the PR for 0.2.3 but wasn't sure if I should've used that version or 0.2.1 as it was the latest release according to ollama's repo. I just went back to 0.2.3 again so I think it's best to keep this one.

**Review by abysssol — APPROVED** [review]

**Review by drupol — APPROVED** [review]

**Review by abysssol — CHANGES_REQUESTED** [review]
I just checked ollama's releases page again, and 0.2.1 is now marked as the latest even though 0.2.3 was marked as latest just a couple hours ago. I think you may have been right in only updating to 0.2.1; perhaps 0.2.2 introduced multiple issues that are just now surfacing.

It's probably best to only update to 0.2.1 for now.

**Comment by redyf** [comment]
> I just checked ollama's releases page again, and 0.2.1 is now marked as the latest even though 0.2.3 was marked as latest just a couple hours ago. I think you may have been right in only updating to 0.2.1; perhaps 0.2.2 introduced multiple issues that are just now surfacing.
> 
> It's probably best to only update to 0.2.1 for now.

I see, that makes sense. I'll revert to 0.2.1

**Comment by redyf** [comment]
Ollama just declared 0.2.4 as latest version, here we go again xD

**Comment by abysssol** [comment]
Do you want to (in order of personal preference):
1. leave this pr open to wait and see if 0.2.4 is relatively stable
2. merge 0.2.1 for now and wait and see if 0.2.4 is relatively stable
3. merge 0.2.4 and hope for the best

I may prefer option 1, but I'm not against any of them.

**Review by abysssol — APPROVED** [review]

**Review by abysssol — APPROVED** [review]

**Comment by redyf** [comment]
> Do you want to (in order of personal preference):
> 
>     1. leave this pr open to wait and see if 0.2.4 is relatively stable
> 
>     2. merge 0.2.1 for now and wait and see if 0.2.4 is relatively stable
> 
>     3. merge 0.2.4 and hope for the best
> 
> 
> I may prefer option 1, but I'm not against any of them.

I vote for merging 0.2.1 for now, as it's already pretty stable. We can bump the next versions later.

**Comment by abysssol** [comment]
Alright, I'll merge once ofborg is done. Though it would really be best if someone could test that rocm and cuda still work correctly and detect the gpu. I can't test rocm at the moment due to a hardware fault in both the cpu and motherboard rendering my pc unusable; I'm currently on a weak laptop.

**Comment by redyf** [comment]
Ollama v0.2.5 is already available, so I think it was actually a good idea not merging 0.2.4 hahaha :laughing:  https://github.com/ollama/ollama/releases/tag/v0.2.5

**Comment by drupol** [comment]
Would you like to merge 0.2.5 within this PR ?

**Comment by abysssol** [comment]
Ollama's releases seem too unstable and bug filled for now; I think we should hold off on updating ollama for 2 to 5 more days. Unless it turns out 0.2.1 also has all the bugs, and updating is the only way to fix them besides reverting back to 0.1.48.

**Pull request merged**
