### PR TITLE
Improve cross referencing in NixOS Manual

### PR DESCRIPTION
**Pull request by rdnetto**
###### Motivation for this change
Discoverability of Appendix A, which documents the options, is poor. This results in issues like #20548, where users copy isolated snippets without understanding them.

###### Things done
This PR modifies all references to options in manual to be links or cross-references to their section in the appendix. This means that the generated HTML will render them as hyperlinks, and that the manual will fail to build if someone removes/renames an option without updating it.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jtojnar** [comment]
Do you have a script for adding the links? I think it would be best if the links were added during the build, otherwise the files will be quite messy or people will keep forgetting to add the links.

**Comment by rdnetto** [comment]
> Do you have a script for adding the links? I think it would be best if the links were added during the build, otherwise the files will be quite messy or people will keep forgetting to add the links.

Unfortunately no - they were added by hand.

Automating the process is non-trivial, for the following reasons:
* the tool would need to differentiate between terms which are options and terms which are package names. e.g. `services.postgresql.package` and `pkgs.postgresql96` are defined in different places (and I don't know if the latter always has documentation)
* the tool would need to be capable of parsing Nix, so that it could understand that `foo.bar = { baz = null }` means that the link should reference `foo.bar.baz`
* the tool would need to understand wildcards like `systemd.services._name_.serviceConfig`
* we'd probably need to extend the docbook syntax somehow so that the tool would know which sections to replace, since not all `<programlisting>`s contain Nix, and not all Nix is in `<programlisting>`s
* what dependencies do we consider acceptable for building the manual? Haskell is a good fit for this kind of problem and already has libraries for parsing Nix, but I don't know how maintainable the community would find it

It's not unfeasible, but it's a decent chunk of work. My suggestion is that we start by manually maintaining the links, and figure out how/if we want to automate it.

**Review by lheckemann — CHANGES_REQUESTED** [review]
I love it!

Just one issue: you've modified the indentation in various places, which is mostly fine, except in some cases where the elements actually preserve whitespace, particularly `<screen>` sections. In these cases it results in worse rendering, since the leading whitespace is preserved. However, I see you've also fixed the same issue in some other places, which is also nice.

Thanks for this!

**Comment by rdnetto** [comment]
This should be ready to merge now, unless I've missed anything.

**Comment by grahamc** [comment]
> what dependencies do we consider acceptable for building the manual? Haskell is a good fit for this kind of problem and already has libraries for parsing Nix, but I don't know how maintainable the community would find it

Haskell is much too big. NixOS docs's build closure should remain fairly small.

**Pull request merged**
