### PR TITLE
python3.pkgs.dropbox: use source from git, since it contains documentation

### PR DESCRIPTION
**Pull request by KAction**
###### Motivation for this change

While there is discussion (#136100) about building Sphinx documentation
in nixpkgs proper, this change makes life easier for those who build
documentation out-of-tree, in personal overlays, since it allows inheriting
"src" attribute instead of matching git and pypi themself.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 136291` at 69473d24 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built successfully:</summary>
  <ul>
    <li>git-annex-remote-dbx</li>
    <li>maestral (python39Packages.maestral)</li>
    <li>maestral-gui</li>
    <li>python38Packages.dropbox</li>
    <li>python38Packages.maestral</li>
    <li>python39Packages.dropbox</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/dropbox/default.nix:31:5:
```
   |
31 |     maintainers = with maintainers; [ ];
   |     ^
```
</li>
  </ul>
</details>

**Comment by KAction** [comment]
Resolved merge conflict.

**Comment by KAction** [comment]
@SuperSandro2000

**Comment by SuperSandro2000** [comment]
@KAction Please fix the merge conflict. Otherwise LGTM.

**Comment by KAction** [comment]
@SuperSandro2000 Resolved merge conflict again.

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 136291 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>6 packages built:</summary>  <ul>    <li>git-annex-remote-dbx</li>    <li>maestral (python39Packages.maestral)</li>    <li>maestral-gui</li>    <li>python38Packages.dropbox</li>    <li>python38Packages.maestral</li>    <li>python39Packages.dropbox</li>  </ul></details>

**Pull request merged**
