### PR TITLE
LLVM 3.8.1

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

Bump LLVM from 3.8.0 to 3.8.1.

First commit is needed to fix LLDB after hardening changes (even on 3.8.0), second bumps to 3.8.1.

Resulting tools seem to work, more testing probably required.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
(Failure is apparently due to lack of disk space?)

**Comment by dtzWill** [comment]
Not at all to be impatient but since I'm new to this process of submitting package update requests to nixpkgs: is this blocking on me (perhaps trying to do the things outlined in the template-provided checklist), or maybe things I could do to help make it easier to accept this change? Please let me know if that's the case, otherwise carry on and thanks for all your work :).

**Review by acowley — APPROVED** [review]
Built successfully in a darwin sandbox.

**Comment by acowley** [comment]
@dtzWill Thanks for the ping to remind everyone. Sorry it's sat this long!

**Comment by vcunat** [comment]
Thank you! There's too much happening in nixpkgs these days.

**Pull request merged**
