### PR TITLE
nixos/nimdow: module updates

### PR DESCRIPTION
**Pull request by marcusramberg**
## Description of changes

- Make nimdow package configurable
- Ensure nimdow can start a terminal in it's default configuration
- Add a simple module test

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by stigtsp — CHANGES_REQUESTED** [review]
Looks good!

Could you add a `passthru.tests` reference to `nixosTests.nimdow` in the `nimdow` derivation? In that way, ofborg and other tools would run these tests for new updates.

Should be something like:
```diff
diff --git a/pkgs/by-name/ni/nimdow/package.nix b/pkgs/by-name/ni/nimdow/package.nix
index a77fb05298b7..b4c2842f573f 100644
--- a/pkgs/by-name/ni/nimdow/package.nix
+++ b/pkgs/by-name/ni/nimdow/package.nix
@@ -1,4 +1,4 @@
-{ lib, buildNimPackage, fetchFromGitHub, testers }:
+{ lib, buildNimPackage, fetchFromGitHub, testers, nixosTests }:

 buildNimPackage (finalAttrs: {
   pname = "nimdow";
@@ -30,6 +30,8 @@ buildNimPackage (finalAttrs: {
     version = "v${finalAttrs.version}";
   };

+  passthru.tests.nimdow = nixosTests.nimdow;
+
   meta = with lib;
     finalAttrs.src.meta // {
       description = "Nim based tiling window manager";
```

**Comment by marcusramberg** [comment]
> Looks good!
> 
> Could you add a `passthru.tests` reference to `nixosTests.nimdow` in the `nimdow` derivation? In that way, ofborg and other tools would run these tests for new updates.

Yeah, I already had that in progress, just wasn't sure if I should add it to this PR or separately. Added it here now.

**Comment by stigtsp** [comment]
Version test fails on darwin x86: https://github.com/NixOS/nixpkgs/pull/296479/checks?check_run_id=22757547826

```
building '/nix/store/5sn0iihbw09lc7yy95rklpg6dbmbj3qq-nimdow-0.7.37-test-version.drv'...
nimdow --version returned a non-zero exit code.
could not load: libXft.so
(compile with -d:nimDebugDlOpen for more information)
error: builder for '/nix/store/5sn0iihbw09lc7yy95rklpg6dbmbj3qq-nimdow-0.7.37-test-version.drv' failed with exit code 1;
       last 3 log lines:
       > nimdow --version returned a non-zero exit code.
       > could not load: libXft.so
       > (compile with -d:nimDebugDlOpen for more information)
       For full logs, run 'nix log /nix/store/5sn0iihbw09lc7yy95rklpg6dbmbj3qq-nimdow-0.7.37-test-version.drv'.
```

**Review by stigtsp — DISMISSED** [review]

**Comment by marcusramberg** [comment]
Uh it's a x11 window manager, it cannot work on Darwin. The version check isn't new tho?

**Comment by marcusramberg** [comment]
Doesn't link correctly on macos so set platforms to linux.

**Review by stigtsp — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
