### PR TITLE
pythonPackages.closure-linter: init at 2.3.19

### PR DESCRIPTION
**Pull request by chris-martin**
###### Things done:
- [ ] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
appears to be a Python 2.x only package judging from the build log

**Comment by FRidh** [comment]
ping

**Comment by chris-martin** [comment]
https://github.com/google/closure-linter/issues/81 confirms that Python 3 is not supported.

**Comment by chris-martin** [comment]
Updated to flag the package as disabled for python 3.x.

**Pull request merged**
