### PR TITLE
nextcloudPackages.recognize: init at 6.1.1

### PR DESCRIPTION
**Pull request by mibmo**
## Description of changes

Add the [recognize](https://github.com/nextcloud/recognize) nextcloud app.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by mibmo** [comment]
oh, woops. just noticed the version is different for each nextcloud version. will update commit.

**Comment by mibmo** [comment]
not sure what's preferred, but decided to name commit/PR after the app's version for the latest nextcloud and provide extra details in the commit description. If there's a better way to go about it, please do tell! :)

**Comment by dotlambda** [comment]
How do you configure the nodejs path?

**Comment by mibmo** [comment]
> How do you configure the nodejs path? See #211631

Same trick as [here](https://github.com/NixOS/nixpkgs/pull/211631#issuecomment-1623717615), but it was too hacky so I've decided to remove it again. Would love to join in on an effort to improve the UX for these apps (especially memories and recognize; they seem to be the most hacky), but unless anyone else steps up I'm not sure that'll happen.

We can close this for now, especially given there's already an open issue, but FWIW it does "work" (just not in the usual nix _it just works™_ way ;))

**Comment by mibmo** [comment]
Closing as I don't see this getting fixed anytime soon.

**Pull request closed without merging**
