### PR TITLE
agdaPackages.standard-library: 1.3 -> 1.4

### PR DESCRIPTION
**Pull request by turion**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

CC: @alexarice @jwiegley

### CODE REVIEW

**Comment by turion** [comment]
@alexarice Do we have all agda libraries on CI? Or could it be that I accidentally break one this way?

**Comment by turion** [comment]
Indeed this broke the `generic` package. I'll try and update the agda test in a way that it would have caught this.

**Comment by turion** [comment]
This test now shows that generic doesn't build.

**Comment by turion** [comment]
I don't understand why there is no CI failure. When I do `nix-build nixos/tests/agda.nix`, it fails with the error message described here:

https://github.com/effectfully/Generic/issues/5

**Comment by alexarice** [comment]
CI doesn't run the tests by default. I'm also not sure building every agda package in the tests is a good idea.

**Review by alexarice — CHANGES_REQUESTED** [review]
I'd prefer not to modify the test here, and likely not in this way. I don't think anything else checks that all their packages build.

I think the three options here are:
+ Update standard library and mark everything broken
+ Don't update yet and wait for some things to catch up
+ Add a `standard-library_1.3` package

**Comment by alexarice** [comment]
Given that my understanding is that it only breaks the one library, we could just go ahead

**Comment by turion** [comment]
> I'd prefer not to modify the test here, and likely not in this way. I don't think anything else checks that all their packages build.

But we should add some test somewhere that builds all packages, do you agree? Where could such a test reside?

> Don't update yet and wait for some things to catch up

I guess that's fine as well. As far as I could see, `generic` is the only package that failed, and it's probably fairly easy to fix.
 
> Add a standard-library_1.3 package

I think that's a great option as well. I can make the standard library builder generic and call it twice, with both versions.

I'd go for first waiting a bit until all packages work with 1.4. It's an interesting experiment to see whether there is enough motivation in the community to stay coherent. If it works out fine, then great. If not, we can wonder about the other options.

**Comment by alexarice** [comment]
> > I'd prefer not to modify the test here, and likely not in this way. I don't think anything else checks that all their packages build.
> 
> But we should add some test somewhere that builds all packages, do you agree? Where could such a test reside?

I'm not sure it's usual to have a test like this, but if we did perhaps it should be a standard library test rather than an agda test

**Comment by turion** [comment]
I fixed `generic` here: https://github.com/effectfully/Generic/pull/6

Maybe it gets released soon.

> I'm not sure it's usual to have a test like this, but if we did perhaps it should be a standard library test rather than an agda test

I'm also not sure, but it doesn't seem wasteful to me. The packages need to be built anyways for the cache, and it would be nice to have some signal if something breaks. In Haskell, this is done by stackage. I'm imagining that nixpkgs could step in for the corresponding task in the Agda world. Given that it's just a handful curated packages, it seems feasible.

Anyways, I guess it's a separate issue. I opened one: https://github.com/NixOS/nixpkgs/issues/98209

**Comment by turion** [comment]
Indeed a pleasantly fast response, on `generic`. But `agda-categories` fails as well.

**Comment by alexarice** [comment]
This is unsurprising, and it took a bit of work to get a release last time

**Comment by turion** [comment]
Yes, they seem to have released it several times until they got it right. I think nixpkgs can help there because we can build one consistent package set.

**Comment by turion** [comment]
@alexarice Is it ok if the updated other packages (`generic` and `agda-categories`) don't have a release tag? Or should we only update them when they release a new version?

**Comment by turion** [comment]
agda-categories is also fixed. See latest commit. There is also an upcoming release: https://github.com/agda/agda-categories/issues/208

**Review by alexarice — CHANGES_REQUESTED** [review]
I reckon update the other libraries to the latest commit, then we can fix them to a release when they make one

**Comment by turion** [comment]
Which other libraries? Even those that do not depend on the standard library, or weren't broken by the change?

**Comment by alexarice** [comment]
Just those that depend on stdlib

**Comment by alexarice** [comment]
We should perhaps go ahead with this, even if it breaks some other packages?

**Comment by ryanorendorff** [comment]
It seems that for the next version, the standard library will use a versioning number scheme (see https://github.com/agda/agda-stdlib/commit/7ad6e06f697d9e0513b2b39502a8d8c033446a67). So instead of `standard-library`, the package name will be `standard-library-1.5`.

Should we make this `standard-library-1.4` to prevent some confusion over whether the `standard-library` link is the most recent one?

**Comment by alexarice** [comment]
That's a good spot, is this change post 1.4?

**Comment by ryanorendorff** [comment]
> That's a good spot, is this change post 1.4?

Yes, it seems that starting at 1.5 and going forward they will have versioning in the package name.

**Comment by turion** [comment]
I think the name of the agda package here should not have a version number, i.e. it should be `agdaPackages.agda-stdlib` and not `agdaPackages.agda-stdlib-1.4`. The convention for the latter is that sometimes, old legacy versions or new preview versions are added. But the released, up-to-date version should not have a version number.

**Comment by alexarice** [comment]
We'll have to add `libraryName = "${pname}-${version}"` from next release onwards but I think this one is unaffected

**Comment by turion** [comment]
Let me re-evaluate which packages are broken, and mark them broken. Both agda-categories and Generic have released compatible versions, I'll update.

**Comment by turion** [comment]
No other packages are broken. I updated `agda-stdlib`, `agda-categories`, `generic` to latest released versions.

I believe we should merge this as-is, and not bump the other packages. That should be a separate MR, if at all necessary.

**Comment by alexarice** [comment]
I think this could all just be one commit really

**Comment by turion** [comment]
I always thought that separate package updates should be separate commits. Otherwise we can't follow the commit message format in https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md.

**Comment by alexarice** [comment]
I think there is a precedent for package sets that mutually break eachother being updated in one commit. See haskellPackages, emacsPackages etc. I don't mind too much either way though

**Comment by turion** [comment]
Ah I didn't know. I prefer committing each update separately, tbh.

**Comment by alexarice** [comment]
Sure, can we rebase out the fix whitespace commit in any case

**Comment by turion** [comment]
> Sure, can we rebase out the fix whitespace commit in any case

Done.

**Review by alexarice — APPROVED** [review]
Diff looks good, though my laptop is playing funny with `nix-review` so I can't really test it atm

**Review by alexarice — APPROVED** [review]

**Pull request merged**
