### PR TITLE
fluxcd: 0.24.1 -> 0.25.3

### PR DESCRIPTION
**Pull request by superherointj**
fluxcd: 0.24.1 -> 0.25.3

### CODE REVIEW

**Review by bryanasdev000 — APPROVED** [review]
Can't test now but LGTM.

Thanks :)

**Comment by bobby285271** [comment]
https://github.com/NixOS/nixpkgs/pull/156627/checks?check_run_id=4929503653 shows that this fails to build... 🤔
@ofborg build fluxcd

**Comment by superherointj** [comment]
@bobby285271 Thanks for noticing this. I should have noticed it. Bumping this package had been straight forward until now.

Error in logs did not clarify problem much to me.

Would be nice if someone more experienced w/ Go would provide feedback. Suggestions?

**Comment by bryanasdev000** [comment]
This is probably because of the recent bump from fluxcd to Go 1.17: https://github.com/fluxcd/flux2/releases/tag/v0.25.0

I am in an impure environment, but this diff should help:

```
diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
index 92118559..f9a6b294 100644
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -26708,7 +26708,9 @@ with pkgs;
 
   fluxctl = callPackage ../applications/networking/cluster/fluxctl { };
 
-  fluxcd = callPackage ../applications/networking/cluster/fluxcd { };
+  fluxcd = callPackage ../applications/networking/cluster/fluxcd {
+    buildGoModule = buildGo117Module;
+  };
 
   linkerd = callPackage ../applications/networking/cluster/linkerd { };
   linkerd_edge = callPackage ../applications/networking/cluster/linkerd/edge.nix { };
```

Until https://github.com/NixOS/nixpkgs/pull/154059 is merged we probably need to work like this in some packages (like linkerd-edge  @superherointj per https://github.com/linkerd/linkerd2/releases/tag/edge-21.12.1).

**Comment by superherointj** [comment]
Thanks @bryanasdev000 for the directions. I have built it successfully and it runs for me.
I'm sorry for the trouble here.

**Pull request merged**
