### PR TITLE
vortex: init at 1.6.14

### LINKED ISSUE #147228: Vortex mod manager
**Project description**

From the [home page](https://www.nexusmods.com/site/mods/1):

> Vortex is the new, modern mod manager from Nexus Mods. It is designed to make modding your game as simple as possible for new users, while still providing enough control for more experienced veterans of the modding scene. Lead by Tannin, the creator of Mod Organizer, Vortex takes the lessons learnt during the development of MO and Nexus Mod Manager to provide the most powerful and intuitive modding experience available.
> 
> Our approach with Vortex aims to take complex tasks such as sorting your load order or managing your mod files and automates as much of the process as possible with the goal of having you achieve a stable modded game with minimal effort. We want to help you spend less time modding and more time playing your games.

**Metadata**

* homepage URL: https://www.nexusmods.com/site/mods/1
* source URL: https://github.com/Nexus-Mods/Vortex
* license: GPLv3
* platforms: Mainly Windows. [Builds & runs on Linux](https://github.com/Nexus-Mods/Vortex/issues/2862#issuecomment-625742078), but currently unsupported. Nix's reproducible builds makes it the perfect platform to showcase this advanced gaming software on Linux.

Update: I'm not sure HEAD builds on Linux. I used the following shell.nix:

```
{ pkgs ? import
    (
      fetchTarball
        {
          name = "21.05";
          url = "https://github.com/NixOS/nixpkgs/archive/7e9b0dff974c89e070da1ad85713ff3c20b0ca97.tar.gz";
          sha256 = "1ckzhh24mgz6jd1xhfgx0i9mijk6xjqxwsshnvq789xsavrmsc36";
        })
    { }
}:
pkgs.mkShell {
  buildInputs = [
    pkgs.mono
    pkgs.nodejs
    pkgs.python3
    pkgs.yarn
  ];
}
```

The build result:

```console
$ yarn install
yarn install v1.22.10
$ git submodule update --init --recursive
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.1: The platform "linux" is incompatible with this module.
info "fsevents@2.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > modmeta-db@0.7.0" has incorrect peer dependency "commander@^6.1.0".
warning " > modmeta-db@0.7.0" has unmet peer dependency "express@^4.14.0".
warning "react-sortable-tree > frontend-collective-react-dnd-scrollzone@1.0.2" has incorrect peer dependency "react-dnd@^7.3.0".
[4/4] Building fresh packages...
[7/17] ⠄ icon-extract
[14/17] ⠄ @bitdisaster/exe-icon-extractor
[3/17] ⠄ drivelist
[9/17] ⠄ libxmljs
error /home/user/Vortex/node_modules/icon-extract: Command failed.
Exit code: 1
Command: npm run autogypi && node-gyp configure build
Arguments: 
Directory: /home/user/Vortex/node_modules/icon-extract
Output:
npm WARN lifecycle The node binary used for scripts is /run/user/1000/yarn--1637737991396-0.008285407273942225/node but npm is using /nix/store/cdalbhzm3z4gz07wyg89maprdbjc4yah-nodejs-14.17.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> icon-extract@1.1.0 autogypi /home/user/Vortex/node_modules/icon-extract
> autogypi

gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@14.17.0 | linux | x64
gyp info find Python using Python version 3.8.9 found at "/nix/store/4s0h5aawbap3xhldxhcijvl26751qrjr-python3-3.8.9/bin/python3"
gyp info spawn /nix/store/4s0h5aawbap3xhldxhcijvl26751qrjr-python3-3.8.9/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/user/Vortex/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/Vortex/node_modules/icon-extract/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/Vortex/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/.cache/node-gyp/13.1.6/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/user/.cache/node-gyp/13.1.6',
gyp info spawn args   '-Dnode_gyp_dir=/home/user/Vortex/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/user/.cache/node-gyp/13.1.6/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/user/Vortex/node_modules/icon-extract',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/user/Vortex/node_modules/icon-extract/build'
  CC(target) Release/obj.target/nothing/node_modules/node-addon-api/nothing.o
  AR(target) Release/obj.target/node_modules/node-addon-api/nothing.a
  COPY Release/nothing.a
  CXX(target) Release/obj.target/IconExtractor/src/IconExtractor.o
make: Leaving directory '/home/user/Vortex/node_modules/icon-extract/build'
In file included from ../src/IconExtractor.cpp:1:
../node_modules/node-addon-api/napi.h:32:6: error: #error Exception support not detected. Define either NAPI_CPP_EXCEPTIONS or NAPI_DISABLE_CPP_EXCEPTIONS.
   32 |     #error Exception support not detected. \
      |      ^~~~~
../src/IconExtractor.cpp:9:10: fatal error: IconExtractorLinux.h: No such file or directory
    9 | #include "IconExtractorLinux.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [IconExtractor.target.mk:118: Release/obj.target/IconExtractor/src/IconExtractor.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/Vortex/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.10.79
gyp ERR! command "/nix/store/cdalbhzm3z4gz07wyg89maprdbjc4yah-nodejs-14.17.0/bin/node" "/home/user/Vortex/node_modules/icon-extract/node_modules/.bin/node-gyp" "configure" "build"
gyp ERR! cwd /home/user/Vortex/node_modules/icon-extract
```

### PR DESCRIPTION
**Pull request by l0b0**
###### Description of changes

GPLv3 [Mod manager by Nexus Mods](https://www.nexusmods.com/site/mods/1).

Closes #147228. Depends on [upstream issue](https://github.com/Nexus-Mods/Vortex/issues/2862).

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by l0b0** [comment]
[This doesn't build on my machine](https://gist.github.com/l0b0/f1aeb61f4526b085354ccaba80bc2cf1), but seems to build just fine here. Does anyone know enough about node-gyp/yarn to tell whether it's just an issue with my setup?

**Comment by natto1784** [comment]
the build is not triggered here because you did not add it to the all-packages.nix. As i said in the issue thread, it would not build even after that. Besides, there are issues with the code styling as well.

**Comment by l0b0** [comment]
Cancelling this since there's now [NexusMods.App](https://github.com/NixOS/nixpkgs/issues/270358), [which already supports Linux](https://github.com/Nexus-Mods/NexusMods.App/issues/148).

**Comment by ardishko** [comment]
Can we reopen this? Vortex is the only supported one for now. NexusMods.App only supports around 4 games... The NexusMods native app won't be ready for another good few years...

**Comment by kinzokudev** [comment]
> Can we reopen this? Vortex is the only supported one for now. NexusMods.App only supports around 4 games... The NexusMods native app won't be ready for another good few years...

I 100% second this

**Pull request closed without merging**
