### PR TITLE
znapzend: 0.18.0 -> 0.20.0

### PR DESCRIPTION
**Pull request by rail**
###### Motivation for this change
* update to latest znapzend version which supports `sendRaw` features (encrypted backups)

###### Things done
I tested this on "my laptop" :tm: :) I use native ZFS encryption and with `sendRaw` feature enabled I get properly generated backups that I can mount only by specifying the encryption passphrase. 

Is there any other scenario that I should use to test this?

This is my `configuration.nix` snippet:
```nix
  services.znapzend = {
    enable = true;
    autoCreation = true;
    pure = true;
    features.sendRaw = true;
    zetup = {
      "rpool/HOME" = {
        plan = "4hour=>15min,2day=>1hour,7day=>1day,3week=>1week";
        enable = true;
        destinations = {
          local = {
            dataset = "backup/HOME";
            plan = "4hour=>15min,4day=>1hour,1week=>1day,1year=>1week,10year=>1month";
          };
        };
      };
      "rpool/NIXOS" = {
        plan = "1day=>1hour,7day=>1day,3week=>1week";
        enable = true;
        destinations = {
          local = {
            dataset = "backup/NIXOS";
            plan = "4days=>1hour,1week=>1day,1year=>1week,10year=>1month";
          };
        };
      };
    };
  };

```

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rail** [comment]
@Infinisil, I see you added the futures option recently. You may be also interested in this change. ;)

**Comment by rail** [comment]
Let's try the next person in the commit log, @fpletz :) Maybe you have some time to review this.

**Comment by Mic92** [comment]
Thanks!

**Comment by rail** [comment]
Thank you!

**Pull request merged**
