### PR TITLE
Add port type

### PR DESCRIPTION
**Pull request by danielrutz**
###### Motivation for this change
Many port values in nixos modules use types.int as a type. This allows invalid port numbers to be set. In theory, you could use types.ints.u16 instead, but types.port is more idiomatic. This change might lead to a wider usage of this type.

As an example, the sshd module has been changed to use the new type for the port.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by Ma27 — CHANGES_REQUESTED** [review]
I like that change and can imagine several places where this can be fairly useful.

But it would be great to have this properly documented as well, in `nixos/doc/manual/development/option-types.xml` you can add `types.port`. :)

**Comment by danielrutz** [comment]
I have just added documentation for the type. Is it enough or should I write more about it?

**Review by Ma27 — APPROVED** [review]
LGTM :+1: 
But I'd prefer to wait for at least another maintainer for confirmation :)

**Comment by Infinisil** [comment]
I'd like it to have this type be used on all options that use integer ports, can you do that?

**Comment by bobvanderlinden** [comment]
:+1:

Have come across services that incorrectly set their port type to `int`. Using this type for all services will be harder to merge. I'd rather have this merged and have a separate PR (or PRs) to fix the types in the different services.

**Pull request merged**
