### PR TITLE
nixos/nix-channel: don't set `nix-path`

### PR DESCRIPTION
**Pull request by nicoonoclaste**
## Description of changes

Do not set an empty `nix-path` (in `nix.conf`) when `! nix.channel.enable`.

Otherwise, `nix` will ignore the `NIX_PATH` environment variable, and by extension the `nix.nixPath` NixOS option.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) : `activation-nix-channel` ;
- [x] Tested compilation of all packages that depend on this change using `nixpkgs-review`
  Only `nixos-install-tools` would be rebuilt, but it is blacklisted in `nixpkgs-review`.
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [x] (Module updates) Added a release notes entry if the change is significant
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by mkg20001 — APPROVED** [review]
Looks good, ~~im just unsure if there was any reason for that default~~ edit: seen commit message

**Comment by r-vdp** [comment]
There was work ongoing regarding this also in #323613, @CyberShadow, @roberth.

That being said, I had this patch added to my nixpkgs for a long time now.

**Comment by CyberShadow** [comment]
@mkg20001 @nbraud I believe @roberth objected to making this change by itself: https://github.com/NixOS/nixpkgs/pull/273170#pullrequestreview-1780197755

So, it may make sense to revert this pull request.

**Comment by roberth** [comment]
I've merged #323613 which implements the first mitigation

> print a clear warning in the activation script if the channel data still exists in /nix/var/... and can therefore still be found by Nix

**Pull request merged**
