### PR TITLE
bun: 0.6.14 -> 0.7.0

### PR DESCRIPTION
**Pull request by cdmistman**
###### Description of changes

- added myself to maintainers
- updated bun from 0.6.14 to 0.7.0
- changed changelog url to use the one from the bun blog eg https://bun.sh/blog/bun-v0.7.0

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by GiggleSquid** [comment]
Result of `nixpkgs-review pr 244746` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>bun</li>
  </ul>
</details>

**Review by GiggleSquid — COMMENTED** [review]
Good job, lgtm!

I know you've only updated the package and swapped out the changelog. But is there any reason this package uses fetchurl and builds with unzip, rather than just using fetchzip?

Is it for the update script to work?

**Comment by cdmistman** [comment]
> I know you've only updated the package and swapped out the changelog. But is there any reason this package uses fetchurl and builds with unzip, rather than just using fetchzip?
>
> Is it for the update script to work?

@DAlperin wrote the initial package in #180299 with `fetchurl`, but the update script was added #192265. I think it's probably just what Dov was familiar with at the time. Nonetheless, the way the package is written is known to work, so I don't think it's worth rewriting it using `fetchzip`

**Comment by GiggleSquid** [comment]
That makes sense. And fair enough, if it ain't broke!

**Review by GiggleSquid — APPROVED** [review]

**Pull request merged**
