### PR TITLE
fix secp256k1 broken package

### PR DESCRIPTION
**Pull request by a-t-richard**
The way setup_version is checked generated errors. I fixed it via postPatch by using string comparison (don't know if it's optimal).

### CODE REVIEW

**Comment by Avzgui** [comment]
After reflection, I think it's more relevant to add something like:
```
substituteInPlace setup.py --replace "int(i)" "int(i) if i.isdigit() else 0"
```

Instead of:

```
substituteInPlace setup.py --replace "[int(i) for i in setuptools_version.split('.')] < [3, 3]" "setuptools_version < '3.3'"
```

**Comment by FRidh** [comment]
Please just patch that nonsense out entirely. Setuptools 3.3 is 6 years old.

**Comment by Avzgui** [comment]
Well, I can't disagree with that.

**Review by chris-martin — APPROVED** [review]
The sed patch seems fragile, but seems harmless enough since the python package hasn't been updated since 2016.

**Comment by jonringer** [comment]
I squashed the commits for you, but please adhere to CONTRIBUTING.md guidelines about git history.

Also, thanks for opening your first PR against nixpkgs.

**Pull request merged**
