### PR TITLE
looking-glass-client: a12 -> B1

### PR DESCRIPTION
**Pull request by alexbakker**
###### Motivation for this change

There was a new upstream release.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @pneumaticat

### CODE REVIEW

**Comment by mmahut** [comment]
@GrahamcOfBorg build looking-glass-client

**Comment by Pneumaticat** [comment]
@alexbakker I no longer use VFIO & this package, but the diff looks fine to me. May want to remove me from the maintainers list, since I can no longer test it.

**Comment by alexbakker** [comment]
@Pneumaticat I can do that, but can a package have 0 maintainers? I don't feel comfortable maintaining a package myself (yet) as I started using NixOS only recently.

**Comment by Pneumaticat** [comment]
@alexbakker Looks like there is [at least one other currently unmaintained package](https://github.com/NixOS/nixpkgs/blob/d73cca7808b007b2a8d37b8befd0210ac086f691/pkgs/applications/editors/sigil/default.nix#L40).

However, I'd encourage you to add yourself as a maintainer if you are willing - there are no [formal requirements](https://nixos.wiki/wiki/Nixpkgs#Becoming_a_Nixpkgs_maintainer) - you just get alerted when the package fails to build or potentially mentioned if someone else makes a change.

**Comment by alexbakker** [comment]
@Pneumaticat Alright. I've replaced your username with mine.

**Comment by Pneumaticat** [comment]
@alexbakker Thanks - @mmahut are you able to review? [I don't have merge permissions, so I can't merge the update.]

**Comment by mmahut** [comment]
@GrahamcOfBorg build looking-glass-client

**Pull request merged**
