### PR TITLE
gettext: 0.19.8.1 -> 0.20.1

### PR DESCRIPTION
**Pull request by lsix**
###### Motivation for this change

- 0.20 release information: https://lists.gnu.org/archive/html/info-gnu/2019-05/msg00006.html
- 0.20.1 release information: https://lists.gnu.org/archive/html/info-gnu/2019-05/msg00011.html

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @vrthra @zimbatm

### CODE REVIEW

**Comment by jtojnar** [comment]
Interestingly, upstream actually [recommends](https://git.savannah.gnu.org/gitweb/?p=gettext.git;a=blob;f=PACKAGING;h=f4bae4561ec70a9de2532502b5c2358bb976036c;hb=55b8fe9a2f12b22eb3ee6baf973e03e60b3a9915) packaging gettext-runtime, libtextstyle (newly introduced) and gettext-tools separately. And they seem to have the projects properly divided each in its own directory.

**Comment by lsix** [comment]
Yes, you are right.

I’ll have a look into dividing this into different packages.

Do you think we should postpone the update until we have the package split up, or this can be done in 2 steps ?

**Comment by jtojnar** [comment]
Two steps will be fine, as long we do not forget to do the second one.

**Comment by jtojnar** [comment]
Opened https://github.com/NixOS/nixpkgs/issues/73288 so we do not forget about it.

**Comment by FRidh** [comment]
It fails to build on Darwin
https://nix-cache.s3.amazonaws.com/log/k7aphmvb1ng1z7nps59xn95xvzk9ac79-gettext-0.20.1.drv

**Comment by jtojnar** [comment]
cc @NixOS/darwin-maintainers

**Comment by worldofpeace** [comment]
Is `libintl` missing?

**Pull request merged**
