### PR TITLE
super-slicer: 2.2.54.2 -> 2.3.55.2

### PR DESCRIPTION
**Pull request by lovesegfault**
###### Motivation for this change
Noticed there's a new release

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cab404** [comment]
Thanks)

**Comment by cab404** [comment]
Just checked — it segfaults for some reason. Is it working for you?

**Comment by lovesegfault** [comment]
> Just checked — it segfaults for some reason. Is it working for you?

I've been using it daily with no issues, maybe report the backtrace upstream?

**Comment by lovesegfault** [comment]
@cab404 updated to 2.3.55.1 now, see how this version works for you?

**Comment by cab404** [comment]
> @cab404 updated to 2.3.55.1 now, see how this version works for you?

Still crashes.

**Comment by cab404** [comment]
I am on NixOS 20.09, gitlab.com/cab404/nixos-config

**Comment by lovesegfault** [comment]
@cab404 Can you use `coredumpctl debug` and `bt full` to try and get a backtrace?

**Comment by cab404** [comment]
I strace-d it and it looks like it fails to load some svgs
```
[pid 24336] stat("/nix/store/c441azxfam0hn5nis0nf4bfh4icvmsrk-super-slicer-2.3.55.1/share/SuperSlicer/icons/white/notification_close.svg", 0x7ffefcbeb600) = -1 ENOENT (No such file or directory)
[pid 24336] stat("/nix/store/c441azxfam0hn5nis0nf4bfh4icvmsrk-super-slicer-2.3.55.1/share/SuperSlicer/icons/white/notification_close_hover.svg", 0x7ffefcbeb600) = -1 ENOENT (No such file or directory)
[pid 24336] stat("/nix/store/c441azxfam0hn5nis0nf4bfh4icvmsrk-super-slicer-2.3.55.1/share/SuperSlicer/icons/white/notification_minimalize.svg", 0x7ffefcbeb600) = -1 ENOENT (No such file or directory)
[pid 24336] stat("/nix/store/c441azxfam0hn5nis0nf4bfh4icvmsrk-super-slicer-2.3.55.1/share/SuperSlicer/icons/white/notification_minimalize_hover.svg", 0x7ffefcbeb600) = -1 ENOENT (No such file or directory)
[pid 24336] stat("/nix/store/c441azxfam0hn5nis0nf4bfh4icvmsrk-super-slicer-2.3.55.1/share/SuperSlicer/icons/white/notification_warning.svg", 0x7ffefcbeb600) = -1 ENOENT (No such file or directory)
[pid 24336] stat("/nix/store/c441azxfam0hn5nis0nf4bfh4icvmsrk-super-slicer-2.3.55.1/share/SuperSlicer/icons/white/notification_error.svg", 0x7ffefcbeb600) = -1 ENOENT (No such file or directory)
[pid 24336] stat("/nix/store/c441azxfam0hn5nis0nf4bfh4icvmsrk-super-slicer-2.3.55.1/share/SuperSlicer/icons/white/notification_eject_sd.svg", 0x7ffefcbeb600) = -1 ENOENT (No such file or directory)
[pid 24336] stat("/nix/store/c441azxfam0hn5nis0nf4bfh4icvmsrk-super-slicer-2.3.55.1/share/SuperSlicer/icons/white/notification_eject_sd_hover.svg", 0x7ffefcbeb600) = -1 ENOENT (No such file or directory)
```

coredump kinda shows the same 
```
#0  0x0000000000f02e78 in Slic3r::GUI::GLTexture::load_from_svg_files_as_sprites_array(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::pair<int, bool>, std::allocator<std::pair<int, bool> > > const&, unsigned int, bool) ()
```

**Comment by cab404** [comment]
I've asked merill if he changed something in cmakefile

**Comment by lovesegfault** [comment]
It's really interesting that I can't repro this :P

**Comment by cab404** [comment]
> It's really interesting that I can't repro this :P

yup. are you using nixos?

can you use strace to see, where ss finds those svgs?

**Comment by lovesegfault** [comment]
Yeah, but I'm on nixos-unstable-small.


Here's the strace of me slicing something. Somehow, I now too get a segmentation fault, but only when I attempt to slice.
[Uploading superslicer-strace.txt…]()

```
Core was generated by `./result/bin/superslicer'.
Program terminated with signal SIGSEGV, Segmentation fault.
b#0  0x00007f2c8ee519a2 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /nix/store/fgd3xl7mzzijj3klgxciz2wrrv3q2pg2-gcc-9.3.0-lib/lib/libstdc++.so.6
[Current thread is 1 (Thread 0x7f2c165fc640 (LWP 1339))]
(gdb) bt full
#0  0x00007f2c8ee519a2 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /nix/store/fgd3xl7mzzijj3klgxciz2wrrv3q2pg2-gcc-9.3.0-lib/lib/libstdc++.so.6
No symbol table info available.
#1  0x000000000096ed3f in Slic3r::GCodeProcessor::apply_config(Slic3r::PrintConfig const&) ()
No symbol table info available.
#2  0x00000000009a57ed in Slic3r::GCode::_do_export(Slic3r::Print&, _IO_FILE*, std::function<void (std::vector<Slic3r::ThumbnailData, std::allocator<Slic3r::ThumbnailData> >&, std::vector<Eigen::Matrix<double, 2, 1, 2, 2, 1>, std::allocator<Eigen::Matrix<double, 2, 1, 2, 2, 1> > > const&, bool, bool, bool, bool)>) ()
No symbol table info available.
#3  0x00000000009ad4a0 in Slic3r::GCode::do_export(Slic3r::Print*, char const*, Slic3r::GCodeProcessor::Result*, std::function<void (std::vector<Slic3r::ThumbnailData, std::allocator<Slic3r::ThumbnailData> >&, std::vector<Eigen::Matrix<double, 2, 1, 2, 2, 1>, std::allocator<Eigen::Matrix<double, 2, 1, 2, 2, 1> > > const&, bool, bool, bool, bool)>) ()
No symbol table info available.
#4  0x0000000000727424 in Slic3r::Print::export_gcode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Slic3r::GCodeProcessor::Result*, std::function<void (std::vector<Slic3r::ThumbnailData, std::allocator<Slic3r::ThumbnailData> >&, std::vector<Eigen::Matrix<double, 2, 1, 2, 2, 1>, std::allocator<Eigen::Matrix<double, 2, 1, 2, 2, 1> > > const&, bool, bool, bool, bool)>) ()
No symbol table info available.
#5  0x0000000000dfba66 in Slic3r::BackgroundSlicingProcess::process_fff() ()
No symbol table info available.
#6  0x0000000000dfc940 in Slic3r::BackgroundSlicingProcess::thread_proc() ()
No symbol table info available.
#7  0x0000000000dfcae6 in Slic3r::BackgroundSlicingProcess::thread_proc_safe() ()
No symbol table info available.
#8  0x00007f2c8eb43a12 in thread_proxy () from /nix/store/29y41wrw78msvcphmx6shi926gf0y67p-boost-1.69.0/lib/libboost_thread.so.1.69.0
No symbol table info available.
#9  0x00007f2c8cc64e9e in start_thread (arg=0x7f2c165fc640) at pthread_create.c:463
        ret = <optimized out>
        pd = 0x7f2c165fc640
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139827330664000, 5879860613782677379, 140731641470174, 140731641470175, 0, 46053648, -5782240751264749693, -5782499189338691709}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0,
              0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#10 0x00007f2c8cb9366f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.
```

**Comment by lovesegfault** [comment]
@cab404 Updated again, give it a go

**Comment by cab404** [comment]
> @cab404 Updated again, give it a go

It actually works now!

**Review by cab404 — APPROVED** [review]

**Review by cab404 — APPROVED** [review]

**Comment by cab404** [comment]
Result of `nixpkgs-review pr 103769` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>super-slicer</li>
  </ul>
</details>

**Comment by cab404** [comment]
But actually fails to slice too :|

**Comment by cab404** [comment]
But actually fails to slice too :|

**Comment by lovesegfault** [comment]
Yeah, there are some fixes in master that solve issues with gyroid infill. Waiting on those to update this again :D

**Comment by cab404** [comment]
> Yeah, there are some fixes in master that solve issues with gyroid infill. Waiting on those to update this again :D

but it fails with any type of infill :/

**Comment by cab404** [comment]
@lovesegfault what happened?

**Comment by lovesegfault** [comment]
@cab404 They never released a new version and I got tired of waiting and having this PR open. I ended up just moving to PrusaSlicer.

**Comment by baracoder** [comment]
They have done a lot of beta releases with interesting changes. Would it be an option to add a beta version of the package?

**Comment by cab404** [comment]
> They have done a lot of beta releases with interesting changes. Would it be an option to add a beta version of the package?

I am working with Merill on packaging 2.3.56.1 ­-- there are some runtime bugs as of now.

**Comment by cab404** [comment]
@baracoder @lovesegfault rejoice! https://github.com/NixOS/nixpkgs/pull/126671/files

**Pull request closed without merging**
