### PR TITLE
docker: 1.10.0 -> 1.10.3

### PR DESCRIPTION
**Pull request by pdalpra**
###### Things done:
- Built on platform(s)
  - [x] NixOS

### CODE REVIEW

**Comment by joachifm** [comment]
Looks like this bump brings quite a few fixes, probably should be picked into the upcoming release as well, if merged.

**Comment by pdalpra** [comment]
@joachifm That would be awesome, there were a bunch on regressions in Docker 1.10 and Docker 1.10.3 seems to fix them all (battle tested in the company I'm working for :) )

**Comment by colemickens** [comment]
LGTM. Not even sure if 1.10.3 fixes /all/ of the regressions, but I'd be happy to see it merged sooner rather than later.

**Comment by joachifm** [comment]
Let's do it

**Pull request merged**
