### PR TITLE
[staging] cpan2nix: update perl packages

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

newer ```cpan2nix``` run
supersede https://github.com/NixOS/nixpkgs/pull/40441

### CODE REVIEW

**Comment by xeji** [comment]
Thanks. Let's wait until current `staging` is stabilized and merged to master, which hopefully will not  too long. Then we merge this in the next round of staging (fyi, we're discussing an improved workflow in https://github.com/NixOS/rfcs/pull/26) . 
/cc @vcunat

**Comment by vcunat** [comment]
That staging iteration is in master now, since 448d7d648.

**Comment by orivej** [comment]
@volth Please take a look why did 5750a94f90e377339988f9e7e6b51c6fb0eee4bb remove CPANPLUS `propagatedBuildInputs` and why did 6044e21fefde999cfea6f7e1de59b8e5accd5e31 not restore them. This broke `nix-generate-from-cpan`; fixed in 5b96694e2d85e3c4bd3324719b630a0d2a6b2423 (misattributing to this PR instead of #36147).

**Comment by volth** [comment]
> why did https://github.com/NixOS/nixpkgs/commit/5750a94 remove CPANPLUS propagatedBuildInputs and why did https://github.com/NixOS/nixpkgs/commit/6044e21 not restore them

@orivej Those packages are not dependencies of CPANPLUS: https://cpan.metacpan.org/authors/id/B/BI/BINGOS/CPANPLUS-0.9174.meta

> This broke ```nix-generate-from-cpan```; fixed in https://github.com/NixOS/nixpkgs/commit/5b96694

That means they are dependencies of ```nix-generate-from-cpan```, not ```CPANPLUS``` and it is better to add them there

**Comment by orivej** [comment]
CPANPLUS probably does not list them as dependencies because they are included in the `inc/bundle/` directory of its archive [1], but this bundle is not installed with `perlPackages.CPANPLUS` and yet e.g. `CPANPLUS/Configure.pm` does `use Log::Message;`.

[1] https://cpan.metacpan.org/authors/id/B/BI/BINGOS/CPANPLUS-0.9174.tar.gz

**Comment by volth** [comment]
>  but this bundle is not installed with perlPackages.CPANPLUS

That means ```CPANPLUS``` does not propagate them

**Comment by orivej** [comment]
Those dependencies are necessary to use CPANPLUS (for example its `cpanp` binary, fixed just now in e5dedc5f3b5a4b3473f635c946d2f241ea53c79a), but in this PR they are neither installed with `perlPackages.CPANPLUS` nor propagated.

**Comment by volth** [comment]
ok, added to exception list to preserve them in the next ```cpan2nix``` runs

**Comment by orivej** [comment]
Thanks!

**Comment by volth** [comment]
@orivej it removed ```LogMessage``` on the next run (https://github.com/NixOS/nixpkgs/pull/41447/commits/ee090eb92e5789af83b650173023167d9dd80d28)only because it is already propagated here via other dependency.

**Pull request merged**
