### PR TITLE
langchain{-community,core,text-splitters}: update

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

- **python3Packages.langchain-core: 0.2.37 -> 0.2.38**
    https://github.com/langchain-ai/langchain/releases/tag/v0.2.38
- **python312Packages.langchain-text-splitters: 0.2.2 -> 0.2.4**
    https://github.com/langchain-ai/langchain/releases/tag/langchain-text-splitters==0.2.4
- **python312Packages.langchain: 0.2.15 -> 0.2.16**
    https://github.com/langchain-ai/langchain/releases/tag/v0.2.16
- **python312Packages.langchain-community: 0.2.15 -> 0.2.16**
    https://github.com/langchain-ai/langchain/releases/tag/langchain-community==0.2.16

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 340049` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>khoj</li>
    <li>khoj.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python311Packages.langgraph</li>
    <li>python311Packages.langgraph.dist</li>
    <li>python312Packages.langgraph</li>
    <li>python312Packages.langgraph.dist</li>
  </ul>
</details>
<details>
  <summary>60 packages built:</summary>
  <ul>
    <li>open-webui</li>
    <li>open-webui.dist</li>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python311Packages.langchain</li>
    <li>python311Packages.langchain-aws</li>
    <li>python311Packages.langchain-aws.dist</li>
    <li>python311Packages.langchain-azure-dynamic-sessions</li>
    <li>python311Packages.langchain-azure-dynamic-sessions.dist</li>
    <li>python311Packages.langchain-chroma</li>
    <li>python311Packages.langchain-chroma.dist</li>
    <li>python311Packages.langchain-community</li>
    <li>python311Packages.langchain-community.dist</li>
    <li>python311Packages.langchain-core</li>
    <li>python311Packages.langchain-core.dist</li>
    <li>python311Packages.langchain-huggingface</li>
    <li>python311Packages.langchain-huggingface.dist</li>
    <li>python311Packages.langchain-mongodb</li>
    <li>python311Packages.langchain-mongodb.dist</li>
    <li>python311Packages.langchain-openai</li>
    <li>python311Packages.langchain-openai.dist</li>
    <li>python311Packages.langchain-standard-tests</li>
    <li>python311Packages.langchain-standard-tests.dist</li>
    <li>python311Packages.langchain-text-splitters</li>
    <li>python311Packages.langchain-text-splitters.dist</li>
    <li>python311Packages.langchain.dist</li>
    <li>python311Packages.langgraph-checkpoint</li>
    <li>python311Packages.langgraph-checkpoint-postgres</li>
    <li>python311Packages.langgraph-checkpoint-postgres.dist</li>
    <li>python311Packages.langgraph-checkpoint-sqlite</li>
    <li>python311Packages.langgraph-checkpoint-sqlite.dist</li>
    <li>python311Packages.langgraph-checkpoint.dist</li>
    <li>python312Packages.langchain</li>
    <li>python312Packages.langchain-aws</li>
    <li>python312Packages.langchain-aws.dist</li>
    <li>python312Packages.langchain-azure-dynamic-sessions</li>
    <li>python312Packages.langchain-azure-dynamic-sessions.dist</li>
    <li>python312Packages.langchain-chroma</li>
    <li>python312Packages.langchain-chroma.dist</li>
    <li>python312Packages.langchain-community</li>
    <li>python312Packages.langchain-community.dist</li>
    <li>python312Packages.langchain-core</li>
    <li>python312Packages.langchain-core.dist</li>
    <li>python312Packages.langchain-huggingface</li>
    <li>python312Packages.langchain-huggingface.dist</li>
    <li>python312Packages.langchain-mongodb</li>
    <li>python312Packages.langchain-mongodb.dist</li>
    <li>python312Packages.langchain-openai</li>
    <li>python312Packages.langchain-openai.dist</li>
    <li>python312Packages.langchain-standard-tests</li>
    <li>python312Packages.langchain-standard-tests.dist</li>
    <li>python312Packages.langchain-text-splitters</li>
    <li>python312Packages.langchain-text-splitters.dist</li>
    <li>python312Packages.langchain.dist</li>
    <li>python312Packages.langgraph-checkpoint</li>
    <li>python312Packages.langgraph-checkpoint-postgres</li>
    <li>python312Packages.langgraph-checkpoint-postgres.dist</li>
    <li>python312Packages.langgraph-checkpoint-sqlite</li>
    <li>python312Packages.langgraph-checkpoint-sqlite.dist</li>
    <li>python312Packages.langgraph-checkpoint.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
`python3Packages.langgraph` is broken, but this is not a regression and I plan to fix it in #340036 after this is merged.

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 340049` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>khoj</li>
    <li>khoj.dist</li>
  </ul>
</details>
<details>
  <summary>8 packages failed to build:</summary>
  <ul>
    <li>python311Packages.langgraph</li>
    <li>python311Packages.langgraph-checkpoint-postgres</li>
    <li>python311Packages.langgraph-checkpoint-postgres.dist</li>
    <li>python311Packages.langgraph.dist</li>
    <li>python312Packages.langgraph</li>
    <li>python312Packages.langgraph-checkpoint-postgres</li>
    <li>python312Packages.langgraph-checkpoint-postgres.dist</li>
    <li>python312Packages.langgraph.dist</li>
  </ul>
</details>
<details>
  <summary>56 packages built:</summary>
  <ul>
    <li>open-webui</li>
    <li>open-webui.dist</li>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python311Packages.langchain</li>
    <li>python311Packages.langchain-aws</li>
    <li>python311Packages.langchain-aws.dist</li>
    <li>python311Packages.langchain-azure-dynamic-sessions</li>
    <li>python311Packages.langchain-azure-dynamic-sessions.dist</li>
    <li>python311Packages.langchain-chroma</li>
    <li>python311Packages.langchain-chroma.dist</li>
    <li>python311Packages.langchain-community</li>
    <li>python311Packages.langchain-community.dist</li>
    <li>python311Packages.langchain-core</li>
    <li>python311Packages.langchain-core.dist</li>
    <li>python311Packages.langchain-huggingface</li>
    <li>python311Packages.langchain-huggingface.dist</li>
    <li>python311Packages.langchain-mongodb</li>
    <li>python311Packages.langchain-mongodb.dist</li>
    <li>python311Packages.langchain-openai</li>
    <li>python311Packages.langchain-openai.dist</li>
    <li>python311Packages.langchain-standard-tests</li>
    <li>python311Packages.langchain-standard-tests.dist</li>
    <li>python311Packages.langchain-text-splitters</li>
    <li>python311Packages.langchain-text-splitters.dist</li>
    <li>python311Packages.langchain.dist</li>
    <li>python311Packages.langgraph-checkpoint</li>
    <li>python311Packages.langgraph-checkpoint-sqlite</li>
    <li>python311Packages.langgraph-checkpoint-sqlite.dist</li>
    <li>python311Packages.langgraph-checkpoint.dist</li>
    <li>python312Packages.langchain</li>
    <li>python312Packages.langchain-aws</li>
    <li>python312Packages.langchain-aws.dist</li>
    <li>python312Packages.langchain-azure-dynamic-sessions</li>
    <li>python312Packages.langchain-azure-dynamic-sessions.dist</li>
    <li>python312Packages.langchain-chroma</li>
    <li>python312Packages.langchain-chroma.dist</li>
    <li>python312Packages.langchain-community</li>
    <li>python312Packages.langchain-community.dist</li>
    <li>python312Packages.langchain-core</li>
    <li>python312Packages.langchain-core.dist</li>
    <li>python312Packages.langchain-huggingface</li>
    <li>python312Packages.langchain-huggingface.dist</li>
    <li>python312Packages.langchain-mongodb</li>
    <li>python312Packages.langchain-mongodb.dist</li>
    <li>python312Packages.langchain-openai</li>
    <li>python312Packages.langchain-openai.dist</li>
    <li>python312Packages.langchain-standard-tests</li>
    <li>python312Packages.langchain-standard-tests.dist</li>
    <li>python312Packages.langchain-text-splitters</li>
    <li>python312Packages.langchain-text-splitters.dist</li>
    <li>python312Packages.langchain.dist</li>
    <li>python312Packages.langgraph-checkpoint</li>
    <li>python312Packages.langgraph-checkpoint-sqlite</li>
    <li>python312Packages.langgraph-checkpoint-sqlite.dist</li>
    <li>python312Packages.langgraph-checkpoint.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 340049` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages marked as broken and skipped:</summary>
  <ul>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>open-webui</li>
    <li>open-webui.dist</li>
    <li>python311Packages.langchain-chroma</li>
    <li>python311Packages.langchain-chroma.dist</li>
    <li>python312Packages.langchain-chroma</li>
    <li>python312Packages.langchain-chroma.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python311Packages.langgraph</li>
    <li>python311Packages.langgraph.dist</li>
    <li>python312Packages.langgraph</li>
    <li>python312Packages.langgraph.dist</li>
  </ul>
</details>
<details>
  <summary>54 packages built:</summary>
  <ul>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python311Packages.langchain</li>
    <li>python311Packages.langchain-aws</li>
    <li>python311Packages.langchain-aws.dist</li>
    <li>python311Packages.langchain-azure-dynamic-sessions</li>
    <li>python311Packages.langchain-azure-dynamic-sessions.dist</li>
    <li>python311Packages.langchain-community</li>
    <li>python311Packages.langchain-community.dist</li>
    <li>python311Packages.langchain-core</li>
    <li>python311Packages.langchain-core.dist</li>
    <li>python311Packages.langchain-huggingface</li>
    <li>python311Packages.langchain-huggingface.dist</li>
    <li>python311Packages.langchain-mongodb</li>
    <li>python311Packages.langchain-mongodb.dist</li>
    <li>python311Packages.langchain-openai</li>
    <li>python311Packages.langchain-openai.dist</li>
    <li>python311Packages.langchain-standard-tests</li>
    <li>python311Packages.langchain-standard-tests.dist</li>
    <li>python311Packages.langchain-text-splitters</li>
    <li>python311Packages.langchain-text-splitters.dist</li>
    <li>python311Packages.langchain.dist</li>
    <li>python311Packages.langgraph-checkpoint</li>
    <li>python311Packages.langgraph-checkpoint-postgres</li>
    <li>python311Packages.langgraph-checkpoint-postgres.dist</li>
    <li>python311Packages.langgraph-checkpoint-sqlite</li>
    <li>python311Packages.langgraph-checkpoint-sqlite.dist</li>
    <li>python311Packages.langgraph-checkpoint.dist</li>
    <li>python312Packages.langchain</li>
    <li>python312Packages.langchain-aws</li>
    <li>python312Packages.langchain-aws.dist</li>
    <li>python312Packages.langchain-azure-dynamic-sessions</li>
    <li>python312Packages.langchain-azure-dynamic-sessions.dist</li>
    <li>python312Packages.langchain-community</li>
    <li>python312Packages.langchain-community.dist</li>
    <li>python312Packages.langchain-core</li>
    <li>python312Packages.langchain-core.dist</li>
    <li>python312Packages.langchain-huggingface</li>
    <li>python312Packages.langchain-huggingface.dist</li>
    <li>python312Packages.langchain-mongodb</li>
    <li>python312Packages.langchain-mongodb.dist</li>
    <li>python312Packages.langchain-openai</li>
    <li>python312Packages.langchain-openai.dist</li>
    <li>python312Packages.langchain-standard-tests</li>
    <li>python312Packages.langchain-standard-tests.dist</li>
    <li>python312Packages.langchain-text-splitters</li>
    <li>python312Packages.langchain-text-splitters.dist</li>
    <li>python312Packages.langchain.dist</li>
    <li>python312Packages.langgraph-checkpoint</li>
    <li>python312Packages.langgraph-checkpoint-postgres</li>
    <li>python312Packages.langgraph-checkpoint-postgres.dist</li>
    <li>python312Packages.langgraph-checkpoint-sqlite</li>
    <li>python312Packages.langgraph-checkpoint-sqlite.dist</li>
    <li>python312Packages.langgraph-checkpoint.dist</li>
  </ul>
</details>

**Comment by sarahec** [comment]
You have test failures:
```sh
       > FAILED tests/test_pregel.py::test_repeat_condition - AssertionError: assert [+ received] == [- snapshot]
       > FAILED tests/test_pregel.py::test_nested_graph_xray - AssertionError: assert [+ received] == [- snapshot]
```

These look like implementation tests instead of true unit tests, so I would suggest disabling them. Possibly also file a bug on the source repos.

I also suggest merging #940036 into this and adding `langchain-core` to the update script. I'll go look at the langchain and langsmith release logs and see if we should add additional packages to the update script.

**Comment by GaetanLepage** [comment]
Ok, I merged both PRs into this one and bumped `langgraph` to 2.19.
However, it complained about not being able to import `psycopg_pool`, so I added `psycopg.pool` to the dependencies.
However, now many tests fail with:
```
psycopg.errors.InsufficientPrivilege: permission denied to create database
```

**Comment by GaetanLepage** [comment]
In https://github.com/NixOS/nixpkgs/pull/340036#issuecomment-2334597102, were you suggesting to add `langchain-core` to the update script of `langgraph` ?
`langchain-core` [already has a custom update script](https://github.com/NixOS/nixpkgs/blob/5f4c0543d2e76a091465335bad84d8702a593124/pkgs/development/python-modules/langchain-core/default.nix#L84-L87)

**Comment by sarahec** [comment]
> Ok, I merged both PRs into this one and bumped `langgraph` to 2.19. However, it complained about not being able to import `psycopg_pool`, so I added `psycopg.pool` to the dependencies. However, now many tests fail with:
> 
> ```
> psycopg.errors.InsufficientPrivilege: permission denied to create database
> ```

As far as I can tell, that would have to be reworked into a passthrough test. Personally, I'd disable those tests for now.

**Comment by GaetanLepage** [comment]
> Personally, I'd disable those tests for now.

Good for me, done.

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 340049` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>khoj</li>
    <li>khoj.dist</li>
  </ul>
</details>
<details>
  <summary>8 packages failed to build:</summary>
  <ul>
    <li>python311Packages.langgraph</li>
    <li>python311Packages.langgraph-checkpoint-postgres</li>
    <li>python311Packages.langgraph-checkpoint-postgres.dist</li>
    <li>python311Packages.langgraph.dist</li>
    <li>python312Packages.langgraph</li>
    <li>python312Packages.langgraph-checkpoint-postgres</li>
    <li>python312Packages.langgraph-checkpoint-postgres.dist</li>
    <li>python312Packages.langgraph.dist</li>
  </ul>
</details>
<details>
  <summary>60 packages built:</summary>
  <ul>
    <li>open-webui</li>
    <li>open-webui.dist</li>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python311Packages.langchain</li>
    <li>python311Packages.langchain-aws</li>
    <li>python311Packages.langchain-aws.dist</li>
    <li>python311Packages.langchain-azure-dynamic-sessions</li>
    <li>python311Packages.langchain-azure-dynamic-sessions.dist</li>
    <li>python311Packages.langchain-chroma</li>
    <li>python311Packages.langchain-chroma.dist</li>
    <li>python311Packages.langchain-community</li>
    <li>python311Packages.langchain-community.dist</li>
    <li>python311Packages.langchain-core</li>
    <li>python311Packages.langchain-core.dist</li>
    <li>python311Packages.langchain-huggingface</li>
    <li>python311Packages.langchain-huggingface.dist</li>
    <li>python311Packages.langchain-mongodb</li>
    <li>python311Packages.langchain-mongodb.dist</li>
    <li>python311Packages.langchain-openai</li>
    <li>python311Packages.langchain-openai.dist</li>
    <li>python311Packages.langchain-standard-tests</li>
    <li>python311Packages.langchain-standard-tests.dist</li>
    <li>python311Packages.langchain-text-splitters</li>
    <li>python311Packages.langchain-text-splitters.dist</li>
    <li>python311Packages.langchain.dist</li>
    <li>python311Packages.langgraph-checkpoint</li>
    <li>python311Packages.langgraph-checkpoint-sqlite</li>
    <li>python311Packages.langgraph-checkpoint-sqlite.dist</li>
    <li>python311Packages.langgraph-checkpoint.dist</li>
    <li>python311Packages.langgraph-sdk</li>
    <li>python311Packages.langgraph-sdk.dist</li>
    <li>python312Packages.langchain</li>
    <li>python312Packages.langchain-aws</li>
    <li>python312Packages.langchain-aws.dist</li>
    <li>python312Packages.langchain-azure-dynamic-sessions</li>
    <li>python312Packages.langchain-azure-dynamic-sessions.dist</li>
    <li>python312Packages.langchain-chroma</li>
    <li>python312Packages.langchain-chroma.dist</li>
    <li>python312Packages.langchain-community</li>
    <li>python312Packages.langchain-community.dist</li>
    <li>python312Packages.langchain-core</li>
    <li>python312Packages.langchain-core.dist</li>
    <li>python312Packages.langchain-huggingface</li>
    <li>python312Packages.langchain-huggingface.dist</li>
    <li>python312Packages.langchain-mongodb</li>
    <li>python312Packages.langchain-mongodb.dist</li>
    <li>python312Packages.langchain-openai</li>
    <li>python312Packages.langchain-openai.dist</li>
    <li>python312Packages.langchain-standard-tests</li>
    <li>python312Packages.langchain-standard-tests.dist</li>
    <li>python312Packages.langchain-text-splitters</li>
    <li>python312Packages.langchain-text-splitters.dist</li>
    <li>python312Packages.langchain.dist</li>
    <li>python312Packages.langgraph-checkpoint</li>
    <li>python312Packages.langgraph-checkpoint-sqlite</li>
    <li>python312Packages.langgraph-checkpoint-sqlite.dist</li>
    <li>python312Packages.langgraph-checkpoint.dist</li>
    <li>python312Packages.langgraph-sdk</li>
    <li>python312Packages.langgraph-sdk.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 340049` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages marked as broken and skipped:</summary>
  <ul>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>open-webui</li>
    <li>open-webui.dist</li>
    <li>python311Packages.langchain-chroma</li>
    <li>python311Packages.langchain-chroma.dist</li>
    <li>python312Packages.langchain-chroma</li>
    <li>python312Packages.langchain-chroma.dist</li>
  </ul>
</details>
<details>
  <summary>62 packages built:</summary>
  <ul>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python311Packages.langchain</li>
    <li>python311Packages.langchain-aws</li>
    <li>python311Packages.langchain-aws.dist</li>
    <li>python311Packages.langchain-azure-dynamic-sessions</li>
    <li>python311Packages.langchain-azure-dynamic-sessions.dist</li>
    <li>python311Packages.langchain-community</li>
    <li>python311Packages.langchain-community.dist</li>
    <li>python311Packages.langchain-core</li>
    <li>python311Packages.langchain-core.dist</li>
    <li>python311Packages.langchain-huggingface</li>
    <li>python311Packages.langchain-huggingface.dist</li>
    <li>python311Packages.langchain-mongodb</li>
    <li>python311Packages.langchain-mongodb.dist</li>
    <li>python311Packages.langchain-openai</li>
    <li>python311Packages.langchain-openai.dist</li>
    <li>python311Packages.langchain-standard-tests</li>
    <li>python311Packages.langchain-standard-tests.dist</li>
    <li>python311Packages.langchain-text-splitters</li>
    <li>python311Packages.langchain-text-splitters.dist</li>
    <li>python311Packages.langchain.dist</li>
    <li>python311Packages.langgraph</li>
    <li>python311Packages.langgraph-checkpoint</li>
    <li>python311Packages.langgraph-checkpoint-postgres</li>
    <li>python311Packages.langgraph-checkpoint-postgres.dist</li>
    <li>python311Packages.langgraph-checkpoint-sqlite</li>
    <li>python311Packages.langgraph-checkpoint-sqlite.dist</li>
    <li>python311Packages.langgraph-checkpoint.dist</li>
    <li>python311Packages.langgraph-sdk</li>
    <li>python311Packages.langgraph-sdk.dist</li>
    <li>python311Packages.langgraph.dist</li>
    <li>python312Packages.langchain</li>
    <li>python312Packages.langchain-aws</li>
    <li>python312Packages.langchain-aws.dist</li>
    <li>python312Packages.langchain-azure-dynamic-sessions</li>
    <li>python312Packages.langchain-azure-dynamic-sessions.dist</li>
    <li>python312Packages.langchain-community</li>
    <li>python312Packages.langchain-community.dist</li>
    <li>python312Packages.langchain-core</li>
    <li>python312Packages.langchain-core.dist</li>
    <li>python312Packages.langchain-huggingface</li>
    <li>python312Packages.langchain-huggingface.dist</li>
    <li>python312Packages.langchain-mongodb</li>
    <li>python312Packages.langchain-mongodb.dist</li>
    <li>python312Packages.langchain-openai</li>
    <li>python312Packages.langchain-openai.dist</li>
    <li>python312Packages.langchain-standard-tests</li>
    <li>python312Packages.langchain-standard-tests.dist</li>
    <li>python312Packages.langchain-text-splitters</li>
    <li>python312Packages.langchain-text-splitters.dist</li>
    <li>python312Packages.langchain.dist</li>
    <li>python312Packages.langgraph</li>
    <li>python312Packages.langgraph-checkpoint</li>
    <li>python312Packages.langgraph-checkpoint-postgres</li>
    <li>python312Packages.langgraph-checkpoint-postgres.dist</li>
    <li>python312Packages.langgraph-checkpoint-sqlite</li>
    <li>python312Packages.langgraph-checkpoint-sqlite.dist</li>
    <li>python312Packages.langgraph-checkpoint.dist</li>
    <li>python312Packages.langgraph-sdk</li>
    <li>python312Packages.langgraph-sdk.dist</li>
    <li>python312Packages.langgraph.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 340049` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>khoj</li>
    <li>khoj.dist</li>
  </ul>
</details>
<details>
  <summary>68 packages built:</summary>
  <ul>
    <li>open-webui</li>
    <li>open-webui.dist</li>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python311Packages.langchain</li>
    <li>python311Packages.langchain-aws</li>
    <li>python311Packages.langchain-aws.dist</li>
    <li>python311Packages.langchain-azure-dynamic-sessions</li>
    <li>python311Packages.langchain-azure-dynamic-sessions.dist</li>
    <li>python311Packages.langchain-chroma</li>
    <li>python311Packages.langchain-chroma.dist</li>
    <li>python311Packages.langchain-community</li>
    <li>python311Packages.langchain-community.dist</li>
    <li>python311Packages.langchain-core</li>
    <li>python311Packages.langchain-core.dist</li>
    <li>python311Packages.langchain-huggingface</li>
    <li>python311Packages.langchain-huggingface.dist</li>
    <li>python311Packages.langchain-mongodb</li>
    <li>python311Packages.langchain-mongodb.dist</li>
    <li>python311Packages.langchain-openai</li>
    <li>python311Packages.langchain-openai.dist</li>
    <li>python311Packages.langchain-standard-tests</li>
    <li>python311Packages.langchain-standard-tests.dist</li>
    <li>python311Packages.langchain-text-splitters</li>
    <li>python311Packages.langchain-text-splitters.dist</li>
    <li>python311Packages.langchain.dist</li>
    <li>python311Packages.langgraph</li>
    <li>python311Packages.langgraph-checkpoint</li>
    <li>python311Packages.langgraph-checkpoint-postgres</li>
    <li>python311Packages.langgraph-checkpoint-postgres.dist</li>
    <li>python311Packages.langgraph-checkpoint-sqlite</li>
    <li>python311Packages.langgraph-checkpoint-sqlite.dist</li>
    <li>python311Packages.langgraph-checkpoint.dist</li>
    <li>python311Packages.langgraph-sdk</li>
    <li>python311Packages.langgraph-sdk.dist</li>
    <li>python311Packages.langgraph.dist</li>
    <li>python312Packages.langchain</li>
    <li>python312Packages.langchain-aws</li>
    <li>python312Packages.langchain-aws.dist</li>
    <li>python312Packages.langchain-azure-dynamic-sessions</li>
    <li>python312Packages.langchain-azure-dynamic-sessions.dist</li>
    <li>python312Packages.langchain-chroma</li>
    <li>python312Packages.langchain-chroma.dist</li>
    <li>python312Packages.langchain-community</li>
    <li>python312Packages.langchain-community.dist</li>
    <li>python312Packages.langchain-core</li>
    <li>python312Packages.langchain-core.dist</li>
    <li>python312Packages.langchain-huggingface</li>
    <li>python312Packages.langchain-huggingface.dist</li>
    <li>python312Packages.langchain-mongodb</li>
    <li>python312Packages.langchain-mongodb.dist</li>
    <li>python312Packages.langchain-openai</li>
    <li>python312Packages.langchain-openai.dist</li>
    <li>python312Packages.langchain-standard-tests</li>
    <li>python312Packages.langchain-standard-tests.dist</li>
    <li>python312Packages.langchain-text-splitters</li>
    <li>python312Packages.langchain-text-splitters.dist</li>
    <li>python312Packages.langchain.dist</li>
    <li>python312Packages.langgraph</li>
    <li>python312Packages.langgraph-checkpoint</li>
    <li>python312Packages.langgraph-checkpoint-postgres</li>
    <li>python312Packages.langgraph-checkpoint-postgres.dist</li>
    <li>python312Packages.langgraph-checkpoint-sqlite</li>
    <li>python312Packages.langgraph-checkpoint-sqlite.dist</li>
    <li>python312Packages.langgraph-checkpoint.dist</li>
    <li>python312Packages.langgraph-sdk</li>
    <li>python312Packages.langgraph-sdk.dist</li>
    <li>python312Packages.langgraph.dist</li>
  </ul>
</details>

**Comment by sarahec** [comment]
Note: Build failures on Darwin are coming from a database test problem in `python312Packages.langchain-checkpoint-postgres`. Filed #340224 to fix.

**Review by sarahec — APPROVED** [review]
LGTM

**Review by natsukium — APPROVED** [review]

**Comment by drupol** [comment]
Got some issues with langchain:

```
        >
┃        > tests/unit_tests/test_imports.py::test_import_all
┃        >   /build/source/libs/langchain/tests/unit_tests/test_imports.py:24: LangChainPendingDeprecationWarning: langchain.indexes.prompts will be removed in the future.If you're relying on these prompts, please open an issue on GitHub to explain your use case.
┃        >     mod = importlib.import_module(module_name)
┃        >
┃        > tests/unit_tests/utils/test_openai_functions.py::test_convert_pydantic_to_openai_function
┃        >   /build/source/libs/langchain/tests/unit_tests/utils/test_openai_functions.py:12: LangChainDeprecationWarning: The function `convert_pydantic_to_openai_function` was deprecated in LangChain 0.1.16 and will be removed in 1.0. Use langchain_core.utils.functi…
┃        >     actual = convert_pydantic_to_openai_function(Data)
┃        >
┃        > -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
┃        > --------------------------- snapshot report summary ----------------------------
┃        > 1 snapshot passed.
┃        > ============================= slowest 5 durations ==============================
┃        > 1.81s call     tests/unit_tests/test_imports.py::test_import_all
┃        > 0.44s call     tests/unit_tests/indexes/test_indexing.py::test_cleanup_with_different_batchsize
┃        > 0.18s call     tests/unit_tests/agents/test_agent.py::test_runnable_with_multi_action_per_step
┃        > 0.12s call     tests/unit_tests/smith/evaluation/test_runner_utils.py::test_arun_on_dataset
┃        > 0.12s call     tests/unit_tests/test_imports.py::test_import_all_using_dir
┃        > =========================== short test summary info ============================
┃        > FAILED tests/unit_tests/retrievers/document_compressors/test_chain_filter.py::test_llm_chain_filter - AssertionError: assert [Document(metadata={'a': 1}, page_content='Candlepin bowling is popular in New England.'), Document(metadata={'c': 3}, page_content=…
┃        >
┃        >   At index 1 diff: Document(metadata={'c': 3}, page_content='The moon is round.') != Document(metadata={'b': 2}, page_content='Candlepin bowling balls are smaller.')
┃        >
┃        >   Full diff:
┃        >     [
┃        >         Document(metadata={'a': 1}, page_content='Candlepin bowling is popular in New England.'),
┃        >   -     Document(metadata={'b': 2}, page_content='Candlepin bowling balls are smaller.'),
┃        >   +     Document(metadata={'c': 3}, page_content='The moon is round.'),
┃        >     ]
┃        > ==== 1 failed, 593 passed, 96 skipped, 12 deselected, 32 warnings in 8.31s =====
┃        For full logs, run 'nix log /nix/store/c83xklb3z7l0jqwrikrrwfaqq2q2py1z-python3.12-langchain-0.2.16.drv'.
┣━ Dependency Graph:
┃
```

**Comment by drupol** [comment]
False alarm, I updated master branch again and it worked.

**Pull request merged**
