### PR TITLE
soapui: 5.5.0 -> 5.6.0 

### LINKED ISSUE #117477: soapui: 5.5.0 does not work with jdk15
**Describe the bug**
The version of SoapUI provided by nixpkgs unstable (5.5.0) does not run against jdk15, the new default.

**To Reproduce**
1. `nix-shell -p soapui --run soapui` 

**Expected behavior**
SoapUI runs.

**Actual behavior**
SoapUI hangs on the splash screen.

**Screenshots**
image

**Additional context**
Changing the derivation to use JDK8 would be trivial, but it might be preferable to finish and merge #93433 instead.

Upstream bug: https://github.com/SmartBear/soapui/issues/487

**Notify maintainers**

@Gerschtli 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.24, NixOS, 21.05.20210319.f5e8bdd (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210317_8a5203d`
 - channels(root): `"nixos-21.05pre275232.29b0d4d0b60"`
 - channels(user): `"nixos-21.05pre276515.1f77a4c8c74"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [ soapui ]
# a list of nixos modules affected by the problem
module: []
```

### PR DESCRIPTION
**Pull request by asbachb**
Closes #93433
Closes #117477

###### Motivation for this change
In the current state `soapui` is broken. see #117477 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Gerschtli — APPROVED** [review]
Diff LGTM, Thanks!

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 131307` at fe763ec5 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>soapui</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/applications/networking/soapui/default.nix:15:3:
```
   |
15 |   installPhase = ''
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/applications/networking/soapui/default.nix:23:5:
```
   |
23 |     (writeText "soapui-${version}.patch" ''
   |     ^
```
</li>
  </ul>
</details>

**Comment by asbachb** [comment]
after merge we can close https://github.com/NixOS/nixpkgs/pull/93433 as well

**Review by Gerschtli — APPROVED** [review]

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 131307` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>soapui</li>
  </ul>
</details>

**Comment by siraben** [comment]
```
[nix-shell:~/.cache/nixpkgs-review/pr-131307]$ soapui                                                                                                                                
================================                                                                                                                                                     
=                                                                                                                                                                                    
= SOAPUI_HOME = /nix/store/x9kllr4f7vxnrsvqh5774vg7hfwk342s-soapui-5.6.0/share/java                                                                                                  
=                                                                                         
================================                                                          
Configuring log4j from [/nix/store/x9kllr4f7vxnrsvqh5774vg7hfwk342s-soapui-5.6.0/share/java/bin/soapui-log4j.xml]                                                                    
log4j:ERROR setFile(null,true) call failed.                                                                                                                                          
java.io.FileNotFoundException: global-groovy.log (Permission denied)                                                                                                                 
        at java.base/java.io.FileOutputStream.open0(Native Method)                                                                                                                   
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)             
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)           
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:158)           
        at org.apache.log4j.FileAppender.setFile(FileAppender.java:289)                                                                                                              
        at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:163)                                                                                                      
        at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:256)                                                                                                  
        at org.apache.log4j.xml.DOMConfigurator.parseAppender(DOMConfigurator.java:220)                                                                                              
        at org.apache.log4j.xml.DOMConfigurator.findAppenderByName(DOMConfigurator.java:150)                                                                                         
        at org.apache.log4j.xml.DOMConfigurator.findAppenderByReference(DOMConfigurator.java:163)                                                                                    
        at org.apache.log4j.xml.DOMConfigurator.parseChildrenOfLoggerElement(DOMConfigurator.java:425)                                                                               
        at org.apache.log4j.xml.DOMConfigurator.parseCategory(DOMConfigurator.java:345)                                                                                              
        at org.apache.log4j.xml.DOMConfigurator.parse(DOMConfigurator.java:827)                                                                                                      
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:712)                                                                                                
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:604)                                                                                                
        at org.apache.log4j.xml.XMLWatchdog.doOnChange(DOMConfigurator.java:861)                                                                                                     
        at org.apache.log4j.helpers.FileWatchdog.checkAndConfigure(FileWatchdog.java:88)                                                                                             
        at org.apache.log4j.helpers.FileWatchdog.<init>(FileWatchdog.java:57)     
        at org.apache.log4j.xml.XMLWatchdog.<init>(DOMConfigurator.java:853)                                                                                                         
        at org.apache.log4j.xml.DOMConfigurator.configureAndWatch(DOMConfigurator.java:584)                                                                                          
        at com.eviware.soapui.DefaultSoapUICore.initLog(DefaultSoapUICore.java:493)                                                                                                  
        at com.eviware.soapui.DefaultSoapUICore.init(DefaultSoapUICore.java:136)                                                                                                     
        at com.eviware.soapui.StandaloneSoapUICore.<init>(StandaloneSoapUICore.java:38)                                                                                              
        at com.eviware.soapui.SoapUI$SoapUIRunner.run(SoapUI.java:791)                                                                                                               
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)                                                                                            
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)                                                                                                   
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)                                                                                                               
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)                                                                                                               
        at java.base/java.security.AccessController.doPrivileged(Native Method)        
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)                                                         
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)         
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)                                                           
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)                                                                               
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)                                                                            
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)                                                                                        
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)                                                                                        
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)  
```

**Comment by asbachb** [comment]
@siraben Actually that `Exception` existed already before as the application tries to write a log to a non writable location. Startup takes some time can you double check the app does not start?

**Comment by siraben** [comment]
Does it launch a GUI? I'm running this on a server.

**Comment by asbachb** [comment]
> Does it launch a GUI? I'm running this on a server.

Yeah. It's soap**UI** ;)

**Pull request merged**
