### PR TITLE
pkgsCross.wasi32.llvmPackages_{13,14}.libcxxabi: drop unappliable patch

### PR DESCRIPTION
**Pull request by trofi**
Without the change build fails as:

       > unpacking source archive /nix/store/xhc43z7x1wmx50j4a43i27vkyfp9fzf7-source
       > source root is source/libcxxabi
       > patch: **** Can't change to directory llvm : No such file or directory

Notices when tried to use llvm13 locally for everything.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dtzWill** [comment]
(cc @matthewbauer who introduced these for LLVM 8 in a4cfd500044617059d0cfbe804c6814151f7c7e4)

Thanks for fixing this!  Boo for copying forward patches without checking they at the very least apply.  I say this without being brave enough to check that I am not partially responsible :wink:.

Before removing them, do we know what they were for?

Fixing their application is easy, they still apply it's just we need to change the paths (something like 3fa78816b647f66e18da4a07b100f598386cd3e2).  So we can fix the build either way, making the question whether this patch is still useful (and perhaps: how far back did it stop being useful? -- removing it from 12 doesn't break the build, for example).

Looking at the patch, it seems its purpose is to stop LLVM from refusing to build on WASI since it's not recognized/blessed, builds succeeding without it make me doubt its utility... 

The changed file doesn't seem to propagate or end up in the outputs, AFAICT.  Maybe if I go back to when it was introduced that'll be clearer.  Testing llvm 8 (where this was first introduced) on master (`nix-build -A pkgsCross.wasi32.llvmPackages_8.libcxxabi.all`) errors out early complaining about compiler not being able `to compile a simple test program`.

(There aren't other WASI build configurations we use/support that this might need these patches, right?)
---

Mostly LGTM although I'm curious about the patch, but removing it where it it's not needed would be nice but not necessary.
(if this unbreaks things for you we can clean house in a separate issue :))

**Comment by dtzWill** [comment]
* Testing llvm 8 (where this was first introduced) on master (`nix-build -A pkgsCross.wasi32.llvmPackages_8.libcxxabi.all`) errors out early complaining about compiler not being able `to compile a simple test program`.  Curious.
* Testing 9-14 all build successfully without this patch
* Probably should remove from `git` variant as well (regardless of other versions, if we're unsure), since it's 13+.

**Comment by mweinelt** [comment]
When that is fixed we can surely move wasi32 to llvm 13. I think firefox is its only consumer within nixpkgs and I already tested wasm sandboxing still works with llvm 13 and the patch dropped.

**Comment by trofi** [comment]
Dropping in favour of https://github.com/NixOS/nixpkgs/commit/f924715b26761385b200116ad590ccfaa537fea3

**Pull request closed without merging**
