### PR TITLE
nixos/dovecot: make ssl_dh optional

### PR DESCRIPTION
**Pull request by ajs124**
###### Motivation for this change
this is basically a revert of 851d5d72a3c87d06d26dd78f8b3a421537fc8a52

this hasn't been needed since 2.3.3, in fact it is encouraged not to use such cipher suites anymore

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by symphorien** [comment]
> , in fact it is encouraged not to use such cipher suites anymore

do you have a link to an authoritative source?

**Comment by ajs124** [comment]
Sure: https://doc.dovecot.org/configuration_manual/dovecot_ssl_configuration/#ssl-security-settings
> Since v2.3.3+ Diffie-Hellman parameters have been made optional, and you are encouraged to disable non-ECC DH algorithms completely.

**Comment by symphorien** [comment]
If I understand correctly:
* dh parameters increase security for prime field- but not elliptic curve based algorithms
* default dovecot configuration still allows prime field-based algorithms
* by default dovecot will generate dh parameters anyway, but smaller ones: according to your link
> When Dovecot starts up for the first time, it generates new 512bit and 1024bit Diffie Hellman parameters and saves them into <prefix>/var/lib/dovecot/ssl-parameters.dat. 

(on my systemd nixos provided ones are 2048 bits)

So I'm not sure this change is warranted. But granted it probably does not make much of a difference as modern clients probably use elliptic curves.

**Comment by ajs124** [comment]
The problem with the module right now is that dh suites cannot be disabled. Right now, if you set `ssl_cipher_list` to something not containing a dh ciphersuite, the config generated by the nixos module does not work.

The reason I want to disable these suites is because DH is not really state of the art anymore and looking at our statistics, out of 100k connections, <30 try to use them, of which probably none are legitimate connections.

I see your point though. If you'd prefer that, we can add an option, say `enableDH`, which defaults to true that controls if this enabled.

**Comment by symphorien** [comment]
> The problem with the module right now is that dh suites cannot be disabled. Right now, if you set ssl_cipher_list to something not containing a dh ciphersuite, the config generated by the nixos module does not work.

I think this is a good enough motivation for this change.

**Review by symphorien — APPROVED** [review]
passes nixos-mailserver tests.

Do you think this deserves a mention in release notes?

**Comment by ajs124** [comment]
Probably, especially if we merge it like this. Maybe it's easier to just go the new option (e.g. `enableDH`) route, tbh.

On one hand, DHE is old and shouldn't be used, on the other hand, just merging this, assuming people ignore the (yet to be written) release notes entry and don't adapt their config, will lead to them having worse security.

**Comment by symphorien** [comment]
@GrahamcOfBorg test dovecot

**Pull request merged**
