### PR TITLE
PHP: Added SSH2 and msgpack extensions.

### PR DESCRIPTION
**Pull request by akoppela**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by etu** [comment]
Hi, do you want to maintain these packages as well as the PHP team? If so you need to make a separate commit to the [maintainer list](https://github.com/NixOS/nixpkgs/blob/master/maintainers/maintainer-list.nix), instructions are in the top of the file.

Also, you cleared out the PR template that contains things like checkboxes describing what's been done. That's never a good practice until your request really doesn't match the template, which it does in this case.

For instance the commit messages doesn't follow the [CONTRIBUTING](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md) guidelines.

They should be formatted for example:
`phpExtensions.ssh2: init at 1.2` and `phpExtensions.msgpack: init at 2.1.2`

Is it built on Linux? Is it built on Darwin? Just to know where to start testing this.

@ofborg build php73Extensions.ssh2 php73Extensions.msgpack php74Extensions.ssh2 php74Extensions.msgpack php80Extensions.ssh2 php80Extensions.msgpack

**Comment by etu** [comment]
I've done some local builds.

The following builds on x86_64-linux:
- php73Extensions.ssh2
- php73Extensions.msgpack
- php74Extensions.ssh2
- php74Extensions.msgpack
- php80Extensions.msgpack

The following doesn't build on x86_64-linux:
- php80Extensions.ssh2

Maybe there's some newer version or patch that make it work with PHP 8.0? If not it should be marked as broken on PHP 8.0.

**Comment by etu** [comment]
@ofborg build php73Extensions.ssh2 php73Extensions.msgpack php74Extensions.ssh2 php74Extensions.msgpack  php80Extensions.msgpack

**Comment by akoppela** [comment]
Hi. Thanks for quick response. That's my first PR here. Actually I didn't clear the template. What happened is that for some reason PR when I submitted the PR I got an error that PR already exist. And when I reload the page I saw that PR actually was created. I didn't notice that template was gone. My bad. I'll return the template.

**Comment by akoppela** [comment]
I'm not a PHP developer myself and added support for the missing extensions we use at work. I'm in frontend team. So I don't see myself maintaining it unless there is a need for me. Hope that's ok.

**Comment by akoppela** [comment]
I'll do more testing and comeback with new commits. @etu would you like me to rename commits and force push them with correct names?

**Comment by etu** [comment]
> I'll do more testing and comeback with new commits. @etu would you like me to rename commits and force push them with correct names?

That would be great! Thank you in advance :)

**Comment by drupol** [comment]
what's the status of this ?

**Comment by etu** [comment]
> what's the status of this ?

Merge conflict and rebase with an update of commit messages to confirm to the https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md guidelines for how the commit messages should be formatted.

**Comment by drupol** [comment]
@akoppela Are you going to take care of this?

**Comment by etu** [comment]
This was superseeded by #220814

**Pull request closed without merging**
