### PR TITLE
trilium: 0.43.4 -> 0.45.10

### PR DESCRIPTION
**Pull request by FliegendeWurst**
###### Motivation for this change

Multiple new versions have been released.  
I added myself as a maintainer and removed the other maintainers from this package since they have not updated the package for months.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 114844` at 63b1af7a run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/eb6cb791063fe23d49b912afadac671e">trilium-desktop</a></li></li>
    <li><a href="https://gist.github.com/9fe4db4e7a093d5b3d75dc3a8f0429e4">trilium-server</a></li></li>
  </ul>
</details>
<details>
  <summary>4 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Please add a comment on the line above, explaining the purpose of this patch.
Near pkgs/applications/office/trilium/default.nix:98:17:
```
   |
98 |     patches = [ ./0001-Use-console-logger-instead-of-rolling-files.patch ] ;
   |                 ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/applications/office/trilium/default.nix:60:5:
```
   |
60 |     installPhase = ''
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/applications/office/trilium/default.nix:99:5:
```
   |
99 |     installPhase = ''
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`agpl3` is a deprecated license, check if project uses `agpl3Plus` or `agpl3Only` and change `meta.license` accordingly.

Near pkgs/applications/office/trilium/default.nix:17:5:
```
   |
17 |     license = licenses.agpl3;
   |     ^
```
</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 114844` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages built:
</summary>
<ul>
<li>trilium-desktop</li>
<li>trilium-server</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
trilium-desktop:
<details>


warning: unclear-gpl
`agpl3` is a deprecated license, check if project uses `agpl3Plus` or `agpl3Only` and change `meta.license` accordingly.

Near pkgs/applications/office/trilium/default.nix:17:5:

```
   |
17 |     license = licenses.agpl3;
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
</details>

**Review by SuperSandro2000 — APPROVED** [review]
diff LGTM, waiting a few days for the other maintainers.

**Comment by FliegendeWurst** [comment]
>  agpl3 is a deprecated license, check if project uses agpl3Plus or agpl3Only and change meta.license accordingly.

was fixed by the last force push.

**Review by emmanuelrosa — APPROVED** [review]
The diff looks good to me. 
I Ran trilium for a bit and it worked fine.

**Comment by FliegendeWurst** [comment]
@SuperSandro2000:
> diff LGTM, waiting a few days for the other maintainers.

ping, one maintainer approved the PR

**Pull request merged**
