### PR TITLE
[Staging] xorg: updates and cleanup

### PR DESCRIPTION
**Pull request by ikervagyok**
###### Motivation for this change
followup from https://github.com/NixOS/nixpkgs/pull/48549

###### Things done
waiting for my machine to compile everything ;)

@worldofpeace should apply cleanly to staging now
@MP2E looking into `libXp` now

### CODE REVIEW

**Comment by dtzWill** [comment]
> @MP2E looking into `libXp` now

05a334ee637a1c1706163d12c14278ad73dda0e0 IIRC gets things like that?

**Comment by dtzWill** [comment]
This seems to add a bunch of dup inputs in the xpra expression, FWIW.  (still reviewing/resolving/merging, sorry)

**Comment by volth** [comment]
Fixes https://github.com/NixOS/nixpkgs/issues/44492

**Comment by ikervagyok** [comment]
I have less time now, but would still like to see this get merged soon - otherwise there will be a lot of ugliness in merging the `*proto -> xorgproto` part. Anything I can help with? It should be fairly stable, since i used the https://github.com/NixOS/nixpkgs/pull/48549 as my daily driver for a while and there are only little deviations in this patchset.

@FRidh @matthewbauer any comments?
@dtzWill could work, but i had no time testing it. If you would link your more interesting patches from your xorg branch(es), i'd try to incorporate them here.

**Review by FRidh — APPROVED** [review]

**Comment by FRidh** [comment]
Rebase and I'll merge it.

**Comment by ikervagyok** [comment]
Thanks @globin @FRidh

**Comment by hedning** [comment]
There's a few new failures, most likely due to this bump: 
- `xorg.xcursorthemes`
- `xorg.xf86videos3virge`
- `xorg.xf86videosavage`
- `xorg.xf86videosis`

https://hydra.nixos.org/eval/1499603?filter=xorg&compare=1499579&full=

**Comment by worldofpeace** [comment]
I'd think this would fix `xorg.xcursorthemes`

```diff
diff --git a/pkgs/servers/x11/xorg/default.nix b/pkgs/servers/x11/xorg/default.nix
index 2f881d7f8f8..88561056989 100644
--- a/pkgs/servers/x11/xorg/default.nix
+++ b/pkgs/servers/x11/xorg/default.nix
@@ -1586,7 +1586,7 @@ lib.makeScope newScope (self: with self; {
     meta.platforms = stdenv.lib.platforms.unix;
   }) {};
 
-  xcursorthemes = callPackage ({ stdenv, pkgconfig, fetchurl, libXcursor }: stdenv.mkDerivation {
+  xcursorthemes = callPackage ({ stdenv, pkgconfig, utilmacros, xcursorgen, fetchurl, libXcursor, xorgproto }: stdenv.mkDerivation {
     name = "xcursor-themes-1.0.5";
     builder = ./builder.sh;
     src = fetchurl {
@@ -1594,8 +1594,8 @@ lib.makeScope newScope (self: with self; {
       sha256 = "0whjiq6d5z4z75zh37pji6llfcyrg6q3mg9zx5zqyncnj39q30xf";
     };
     hardeningDisable = [ "bindnow" "relro" ];
-    nativeBuildInputs = [ pkgconfig ];
-    buildInputs = [ libXcursor ];
+    nativeBuildInputs = [ pkgconfig utilmacros xcursorgen ];
+    buildInputs = [ libXcursor xorgproto ];
     meta.platforms = stdenv.lib.platforms.unix;
   }) {};
```

**Comment by vcunat** [comment]
Perhaps, but
> # THIS IS A GENERATED FILE.  DO NOT EDIT!

**Comment by vcunat** [comment]
The only remaining regressions AFAIK are three ancient xf86-video drivers, which seems a fine state to me.  Feel free to try fixing them;  I see some very recent git commits (at least) for one of them (but no release yet), so perhaps that would be enough...

**Comment by vcunat** [comment]
BTW, some of newly added packages also fail:
- [ ] editres
- [ ] oclock
- [ ] xload
- [ ] xtrap

**Comment by obadz** [comment]
Sadly, citrix_receiver aka wfica is broken by `xorg/xorgserver: 1.19.6 -> 1.20.3` (b981b8e0fef) as documented https://discussions.citrix.com/topic/395450-unusable-after-upgrade-to-xorg-v120/

Not suggesting we revert, just posting this here for those who might care.

Cc @Ma27 @a1russell @volth @FRidh @jensbin @7c6f434c @neilmayhew @veprbl

(Were these commits rebased btw? Looks like their hashes in master are ≠ from here)

**Comment by vcunat** [comment]
I hope `config.xorg.abiCompat` still works somehow; I'm not sure how much we use it nowadays.

**Comment by Infinisil** [comment]
What do we do about these broken packages @vcunat mentioned? Can we just remove them again or should we mark as broken?

**Comment by worldofpeace** [comment]
I can see that the following have already been fixed
* [xorg.oclock](https://github.com/NixOS/nixpkgs/commit/22160302cf43c917de736275bdf904968cc588b4)
* [xorg.editres](https://github.com/NixOS/nixpkgs/commit/680e9f1d9128e5a36fed8517c0664a9e2ecb1416)

**Comment by obadz** [comment]
Using Citrix Workspace instead of Citrix Receiver seems to fix the slowness issue even with Xorg 1.20.5.

**Pull request merged**
