### PR TITLE
gopls: fix privacy breach

### PR DESCRIPTION
**Pull request by KAction**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 119861` at 2796cfa5 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>gopls</li>
    <li>vimPlugins.vim-go</li>
  </ul>
</details>

**Review by lukegb — CHANGES_REQUESTED** [review]
Do you have an upstream commit for this change?

**Comment by SuperSandro2000** [comment]
> Do you have an upstream commit for this change?

https://github.com/golang/tools/commit/9712d02be394497cca363d5276a3cb7236d39984

**Comment by lukegb** [comment]
> > Do you have an upstream commit for this change?
> 
> [golang/tools@9712d02](https://github.com/golang/tools/commit/9712d02be394497cca363d5276a3cb7236d39984)

That... does the opposite of this though? It's not really clear to me if we want to diverge from upstream in this way for non-packaging reasons - this can be done by end-users in their system configs, for example.

**Comment by Mic92** [comment]
I also don't see the privacy breach here. This is the same level of information one would expose when having a http useragent set. There is no other private information leaked.

**Comment by zimbatm** [comment]
Agreed. We do disable telemetry when we can but here it just exposes what tool is being used, and not even the version. When putting the maintenance of the patch in balance, it doesn't seem worth it to me.

**Pull request closed without merging**
