### PR TITLE
lib.types.anything: remove custom logic for lists

### PR DESCRIPTION
**Pull request by krostar**
## Description of changes

Previously, in the lib.types.anything option type, for values of type list, the merge function would only retain the value if the number of option definitions was less than or equal to 1, and would throw an error for conflicting definitions to avoid potentially unwanted list merges.

This change removes that logic, defaulting to the 'mergeEqualOption' function for values of type list. This approach maintains the same safeguard against merging different lists while allowing lists with identical values to be merged.

You can find some more context [here](https://discourse.nixos.org/t/lib-types-anythings-merge-function-behavior-regarding-lists/51708).

## Things done

Removed the special handling of lists in lib.types.anything.

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by infinisil** [comment]
Please also extend/adjust the test suite [here](https://github.com/NixOS/nixpkgs/blob/45ac614560df39fbd0cf580544dac2764f30484f/lib/tests/modules.sh#L429-L430). In particular one test to make sure the error still happens for different lists, but one test to ensure the error doesn't happen for the same list :)

**Review by infinisil — APPROVED** [review]
LGTM, thanks! I'd like to also summon a @roberth here, since he reviewed the original PR adding `types.anything`.

**Comment by roberth** [comment]
> while allowing lists with identical values to be merged.

How do we know that's the user intent, and what if the list is not interpreted as a set by the configuration system this is used for?

I must have learned since then, because I don't think `anything` should be used for anything at all, and that makes me somewhat indifferent about changes to it.
Maybe this causes the breakage that people need to convince them to switch to accurate types? Or is that too cynical and chaotic?

What if we keep failing in cases where no semantics has been specified for lists, and add `anythingWith { lists = "set-like"; }` for making that explicit? That way we can also support the current implementation, and an alternative `lists = "sequence";` that appends in `mkOrder` order.
We could also use that function for other parameters, like for a lazier `anythingWith { lazyAttrs = true; }` or something, to use `lazyAttrsOf` (or vice versa if I'm mistaken; new parameter regardless).

Of course that's not all for this PR, but I think it'd be good for this PR to create `anythingWith`.

**Comment by krostar** [comment]
Hi,

Thank you for your comments.

I don’t have the same level of expertise as you both do, so I’m not in a position to weigh in on whether users should or shouldn’t use types.anything in its current implementation, nor on how to rework it to better serve all users. I’m interested in following the discussion and can share my opinion and personal use cases if you’re interested. However, I think that broader discussion might be better suited for another venue or PR.

The intent of this PR is not to break existing behavior or to overhaul the way types.anything works. The goal is to remove the potentially unwanted specific behavior regarding lists, which—except for sets, which are recursively merged—differs from other types handled by types.anything (only merging equal values), as [discussed here](https://discourse.nixos.org/t/lib-types-anythings-merge-function-behavior-regarding-lists/51708/2?u=krostar).

That said, this PR does change existing behavior by allowing multiple lists with identical values to be accepted, whereas they were not before. I don’t see this as a breaking change since code that evaluated successfully before will still evaluate successfully with the same result after. The original code was intended (based on the comments) to prevent unsafe behavior, and I don’t see this change introducing any new risks.

>How do we know that's the user intent?

The only scenario where this might cause an issue is if the user intends for types.anything to fail when multiple lists with the same values are evaluated.

>What if the list is not interpreted as a set by the configuration system this is used for?

I apologize, but I’m not entirely sure what you mean here. Could you please clarify?

I’m not looking to delve into the anythingWith idea at this time, as I believe that’s a larger discussion that might be better suited for a separate initiative with contributors who have more historical knowledge.

How would you suggest we proceed with this PR to move forward?

**Comment by infinisil** [comment]
>  Maybe this causes the breakage that people need to convince them to switch to accurate types? Or is that too cynical and chaotic?

`types.anything` is perfectly fine to use when somebody would've chosen `types.unspecified` instead, especially for personal use and in the future as a default type for `mkOption`. Yes more specific types are nice, but we don't need to be _that_ pragmatic, Nix is messy.

> I don’t see this as a breaking change since code that evaluated successfully before will still evaluate successfully with the same result after.

Yeah this. Yes the behavior changes, but I cannot imagine it actually _breaking_ anything. This is a small improvement to some, a breakage to none, my preference is really to just merge this and move on.

**Comment by roberth** [comment]
@krostar 

> However, I think that broader discussion might be better suited for another venue or PR.

I appreciate the thought, but I believe that would be impractical.
I hope you don't mind that some discussion about the design values of the module system takes place in this thread.

-----

@infinisil

> Yes the behavior changes, but I cannot imagine it actually _breaking_ anything.

When ignoring second order effects, this is probably true.
Specifically, a more permissive / presumptuous type allows module authors to not specify types for longer.
Also consider that a "successful" but wrong behavior tends to be harder for users to fix than an error message, so this will affect the user experience _when making a mistake_, which matters a lot.


> [`types.anything`] as a default type for `mkOption`.

For the reasons above, this would be bad.

> Nix is messy

Only if we make it messy. Do you want an ecosystem that improves, or an ecosystem that deteriorates?

------

I don't like the change in this PR, but I already have to advise against `types.anything` anyway, so not much changes for me.
If you feel strongly about this PR, I'll step aside.
Please just don't make the default type make more assumptions about how its arbitrary contents are allowed to merge (ie in future changes - not this).

**Comment by krostar** [comment]
Thank you for your response.

I want to make sure I fully understand your position, so I’d like to separate a couple of aspects of this discussion:

- The anything type itself: I understand that types.anything can be misleading and that you generally advise against using it. I can see how this type might not align with the design values you envision for the module system.

- Improving anything type: Despite its issues, types.anything currently exists and is used in the ecosystem. My intent with this PR is to improve how it handles list merging with a small iteration, addressing what I perceive as an inconsistency, without a complete redesign.
 
The goal is not to promote types.anything, nor to redesign it, but to make its existing behavior more consistent and less surprising.

I understand you don't like the change in this PR, but are you primarily against the specific change I’m proposing, or is your concern more about the existence, use, and development of types.anything in general?

I want to make sure we’re addressing the right issues here and not conflating concerns about the type itself with concerns about the proposed change.

**Comment by krostar** [comment]
I hope you don’t mind the ping, @roberth @infinisil.

It's been a week since the last reaction—how should we proceed with this PR?

I don’t want to force anything (pun intended ;)), so if you feel this PR shouldn’t be merged, I’m okay with closing it.

However, if the concerns are more about the usage or rework of types.anything, I believe that’s outside the scope of this PR.
Ideally, I’d like to get feedback on the specific changes proposed here.

**Comment by roberth** [comment]
`types.anything` isn't for me, but clearly this change is beneficial to you, so I'll trust @infinisil's judgement as the original author of the type.

I was expecting a discussion with @infinisil, but this is taking too long.
Sorry for the delay

**Pull request merged**
