### PR TITLE
vimPlugins: fix advanced-git-search-nvim override

### PR DESCRIPTION
**Pull request by andrevmatos**
## Description of changes

advanced-git-search-nvim was being overriden with autosave-nvim, probably a copy-paste issue.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by teto** [comment]
indeed. can you add a test to prevent future regression ? 
```
    doInstallCheck = true;
    vimCommandCheck = "MinimapToggle"; # replace with a command name created by the plugin
    # nvimRequireCheck = 'lua-module'; # if it's a lua plugin
```

**Comment by teto** [comment]
thanks for adding the check. `nixpkgs-review pr 339742` fails though. Probably because the plugin needs to call those freaking `setup` function or because it cant find a dependency. Depending on your motivation let's fix (maybe nvimRequireCheck is easier to run) or get rid of the check.

**Comment by andrevmatos** [comment]
@teto I think we'll need to remove; this is a telescope extension, and therefore loaded like this:
```lua
require("telescope").load_extension("advanced_git_search")
```
and I didn't find an easy way to trigger this with *Check statements, nor similar pattern for other loadable/oot telescope extensions; please, let me know if this is fine

**Review by GaetanLepage — APPROVED** [review]
I am ok merging this as is.
@teto, you make the final call.

**Pull request merged**
