### PR TITLE
WIP: haskellPackages.tensorflow: 2020-05-22 -> 2020-11-14

### PR DESCRIPTION
**Pull request by expipiplus1**
Fixes build, adds support for TF 2.3

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by cdepillabout — CHANGES_REQUESTED** [review]
It appears that everything other than `tensorflow-proto` is marked broken.

Could you mark these as unbroken as well?

**Comment by expipiplus1** [comment]
Ah yeah.

Also although `tensorflow` works now some other necessary packages such as `tensorflow-core-ops` are broken pending the haskell package being made compatible with tf 2.4: https://github.com/tensorflow/haskell/pull/271

I'll mark this as WIP until that's resolved.

**Comment by cdepillabout** [comment]
@expipiplus1 I turned this to a Draft since we're waiting on upstream here, but feel free to flip it back to non-Draft when it is ready to be reviewed again.

**Comment by mikesperber** [comment]
> @expipiplus1 I turned this to a Draft since we're waiting on upstream here, but feel free to flip it back to "Ready for review" when it is ready to be reviewed again.

The upstream pull request got merged - could you update this one?

**Comment by mikesperber** [comment]
@expipiplus1 @cdepillabout What's needed to move this one forward? Would it help if I submitted an up-to-date pull request?

**Comment by cdepillabout** [comment]
@mikesperber Yes, that would be great!

**Comment by expipiplus1** [comment]
Yeah, might be easier to do that. Thanks!

**Comment by mikesperber** [comment]
> Yeah, might be easier to do that. Thanks!

@cdepillabout @expipiplus1 Done:

https://github.com/NixOS/nixpkgs/pull/119411

**Pull request closed without merging**
