### PR TITLE
Backport firefox 50.0.1

### PR DESCRIPTION
**Pull request by grahamc**
###### Motivation for this change

There are critical fixes in 50.0.1: https://www.mozilla.org/en-US/security/advisories/mfsa2016-91/

@edolstra reverted the update to 50.0 due to breaking video, but we pretty well need to ship this update. I'm hoping to get some testing on this, get it fixed, and released.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
(If all is quiet on this, I'll go ahead and merge it at in 7 hours)

**Comment by FRidh** [comment]
@grahamc it would be nice if your revert revert commit would describe why it is again reverted.

**Comment by grahamc** [comment]
Great idea. Will amend that shortly.

**Comment by grahamc** [comment]
I amended the revert, @FRidh, to include a note about why.

**Pull request merged**
