### PR TITLE
Tomcat cleanup && update

### PR DESCRIPTION
**Pull request by danbst**
###### Motivation for this change

Update tomcats, add more versions and remove one error in service logs.

Also, webapps folder takes ~40% of package, so I decided to move it to separate output (it isn't a hard requirement for tomcat)
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [X] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sfultong** [comment]
ACK, looks good :+1: 

I'm surprised mention-bot mentioned me. I think I made one PR for tomcat ages ago.

**Comment by danbst** [comment]
Removed WIP, ping @svanderburg

**Comment by danbst** [comment]
Bump default to tomcat85, upstream default. Added changelogs to commit description, TLDR backwards compatible for most of users, but requires java 7

**Comment by bjornfor** [comment]
Reviewed, looks good!

**Comment by bjornfor** [comment]
+1 for merge to master and backport to release-16.09.

**Comment by danbst** [comment]
should I squash commits?

**Comment by bjornfor** [comment]
@danbst: Nope, they look nice and clean as is :-)

**Comment by bjornfor** [comment]
Pushed to master (63f9ef9f1951dc45e4aac900d9ad592be3a014eb with parents). Maybe wait a couple of days before backporting to release-16.09?

**Pull request closed without merging**
