### PR TITLE
vesktop: add webrtc support on wayland

### PR DESCRIPTION
**Pull request by Mikilio**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by JohnRTitor** [comment]
Result of `nixpkgs-review pr 321710` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>vesktop</li>
  </ul>
</details>

**Comment by JohnRTitor** [comment]
Perhaps `WebRtcPipeWireCamera`  too?

Additionally I think a `commandLineArgs` override could be provided like we do for [google-chrome](https://github.com/NixOS/nixpkgs/blob/d603719ec6e294f034936c0d0dc06f689d91b6c3/pkgs/by-name/go/google-chrome/package.nix#L135)

**Comment by Mikilio** [comment]
Is this to "screen share" that recently introduced pipewire camera output? Because if it has something to do with camera selection, I'm not sure if this will work on any discord client. See issues like [this](https://github.com/Vencord/Vesktop/issues/574)

**Comment by JohnRTitor** [comment]
This will help when video calling via Vesktop I believe.

image

I wonder if it is available on the electron version Vesktop uses.

**Comment by Mikilio** [comment]
I don't think this is on by default as most of my programs still use the v4l2l backend. I'd love that feature to be easily addable by the override to mention, but with something like vesktop I believe the defaults should work for the most naive user. I will test if this work without having to enable anything and let you know.

**Comment by Mikilio** [comment]
Related: [feature request](https://github.com/Vencord/Vesktop/issues/302)

**Comment by Mikilio** [comment]
It seems that feature is not implemented yet and Vesktop itself only uses these [flags](https://github.com/Vencord/Vesktop/blob/0e49e5e8f6bf3727a7d4bc0a4dfe12cf05fcfd5a/.env.example#L8) which is equivalent to my PR. I suggest not adding anything extra until the Vesktop devs add it.

**Review by getchoo — CHANGES_REQUESTED** [review]
i'm a bit confused here. what exactly does this flag solve? from my testing, both audio and video sharing work perfectly fine without this - as intended through venmic. is this not the case for you?

in any case, the commit message should also be changed. this does not "add webrtc support". webrtc is already enabled by default for this build of electron, and this flag doesn't enable it

**Comment by Mikilio** [comment]
On wayland this is necessary or screen share will not work. As mentioned above the vesktop flatpak also enables this on ozone. I have changed the commit message to better explain this.

**Review by JohnRTitor — APPROVED** [review]
Screensharing now properly works on Wayland with Pipewire, approved.

**Comment by pluiedev** [comment]
I've been streaming things with Vesktop on Plasma 6 Wayland and it's always worked fine. Can you share more info on what you mean by WebRTC & screensharing not working?

**Comment by pyrox0** [comment]
I've been using Vesktop for several months now without this flag on SwayWM, and I've had no issues screensharing and using WebRTC. What problem is this PR solving?

**Review by getchoo — CHANGES_REQUESTED** [review]
> On wayland this is necessary or screen share will not work

as reported by others here and through my own testing, this doesn't seem to be the case. this should be handled by venmic - not electron directly - and it has been supported for months. this PR doesn't seem to be actually fixing anything

> as mentioned above the vesktop flatpak also enables this on ozone.

could you send a link to this? reading your previous comments, you don't actually mention this anywhere. the closest is a link you provided to the .env.example in the upstream repo [here](https://github.com/Vencord/Vesktop/blob/0e49e5e8f6bf3727a7d4bc0a4dfe12cf05fcfd5a/.env.example#L8), but the `--enable-webrtc-pipewire-capturer` flag from there doesn't seem to be used in the flatpak (you can search for it [here](https://github.com/search?q=repo%3Aflathub%2Fdev.vencord.Vesktop%20%22--enable-webrtc-pipewire-capturer%22&type=code)) and the `WebRTCPipeWireCapturer` flag you're adding here isn't either ([search results](https://github.com/search?q=repo%3Aflathub%2Fdev.vencord.Vesktop+%22WebRTCPipeWireCapturer%22&type=code))

> I have changed the commit message to better explain this

the commit message still doesn't explain this at all. the only change you made is adding "on wayland", but once again webrtc has always worked. this is enabling the webrtc *pipewire capturer*

**Comment by Mikilio** [comment]
Well it doesn't work for me and this PR solves it, I apologize for making assumptions about the Flatpak.
While I can definitely confirm that this PR solves my issue (as I wouldn't make a PR for any other reason) it seems true that the issue may not be what it seems, and I may need help figuring it out.
Here some information:
- I use hyprland which comes with its own xdg portal
- When I click the screen share button on vesktop it opens the source picker from the  xdg portal as expected.
- When I chose a source nothing happens (vesktop doesn't start screen share as if I never pressed the button)
- The button becomes unresponsive until I restart vesktop

To me, this all seems like venmic may be crashing.

All this does not happen when enabling the Flag in my PR.
 
Should I make an issue instead? I can do with an overlay for now.

**Comment by Mikilio** [comment]
Also it seems like [here](https://github.com/Vencord/Vesktop/blob/0e49e5e8f6bf3727a7d4bc0a4dfe12cf05fcfd5a/scripts/start.ts#L11) vesktop uses the environment variable `ELECTRON_LAUNCH_FLAGS` to start modules. This variable it not defined on my system nor in this package. So it really does look to me like the issue is caused by a missing flag in the package.

**Comment by Mikilio** [comment]
Can you maybe reproduce the issue on wayland if you unset `ELECTRON_LAUNCH_FLAGS`?

@getchoo @pyrox0 @pluiedev

**Comment by Mikilio** [comment]
Scratch this. I can not reproduce the error anymore. Vesktop works without setting the flag now and I think I get what you meant with electron not being involved in screen sharing. Unfortunately, we will never find out why I had that issue, and now I don't.

I will close this PR and reopen if I can reproduce this again. I apologize for the commotion.

**Pull request closed without merging**
