### PR TITLE
agdaPackages.standard-library: 1.5 -> 1.6

### PR DESCRIPTION
**Pull request by turion**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

CC @alexarice

### CODE REVIEW

**Comment by turion** [comment]
The test still fails, but I'm not sure whether that's related to this MR.

**Comment by alexarice** [comment]
Did my test fix ever get merged?

**Comment by turion** [comment]
In https://github.com/NixOS/nixpkgs/pull/98214 I'm running the test whether reverse dependencies are broken. (Spoiler: Yes they are)

**Comment by turion** [comment]
The only straggler is `agda-categories` I believe: https://github.com/agda/agda-categories/pull/266

**Comment by turion** [comment]
> Did my test fix ever get merged?

In conclusion, yes it did, and it works.

**Comment by alexarice** [comment]
I ran 
```
nix-build -E "with import ./. {}; agda.withPackages (p: builtins.filter (x: x ? isAgdaDerivation && ! x.meta.broken) (lib.attrValues p))" --keep-going
```
and agree that only `agda-categories` seems broken

**Comment by turion** [comment]
`agda-categories` should now be fixed as well. Ready to merge.

**Comment by kevincox** [comment]
cc: @ryanorendorff 

Looks fine to me but as it touches @ryanorendorff's package I will give him at least a day to review as well. If they don't respond or approve you can ping me for a merge.

**Review by SuperSandro2000 — APPROVED** [review]
diff LGTM

**Comment by iblech** [comment]
I also confirm that everything works. Thank you @turion for your work!

I really liked how we approached this release: Already with the advent of the rc1 of the new stdlib, we opened issues/pull requests at the libraries we are providing, so that when the release happened, the libraries were already ready and we could simply bump the version numbers.

**Comment by turion** [comment]
> cc: @ryanorendorff
> 
> Looks fine to me but as it touches @ryanorendorff's package I will give him at least a day to review as well. If they don't respond or approve you can ping me for a merge.
> 
> (if this is particularly urgent please explain why)

@kevincox I think you can merge this. All I did is version bump to v0.3 which was released by @ryanorendorff (https://github.com/ryanorendorff/functional-linear-algebra/releases/tag/v0.3).

Agda libraries often need to be updated in sync to be compatible.

**Comment by ryanorendorff** [comment]
Hi everyone,

V0.3 of functional-linear-algebra is ready for 1.6 and the diff looks good! Thanks for keeping the agda standard library up to date!

**Pull request merged**
