### PR TITLE
buildFHSUserEnv: fix for when libc doesn't have lib64 folder

### PR DESCRIPTION
**Pull request by garbas**
@vcunat this made it possible for me to build VidyoDesktop

### CODE REVIEW

**Comment by abbradar** [comment]
https://github.com/NixOS/nixpkgs/issues/15033 has been closed; is this still relevant?

**Comment by garbas** [comment]
@abbradar yes! it is a fix for #15033

**Comment by abbradar** [comment]
@garbas Hm, isn't https://github.com/NixOS/nixpkgs/commit/70cecb9cbdc7684885e348e2e82308f8da373953 the proper fix?

**Comment by abbradar** [comment]
I did a more thorough fix in https://github.com/NixOS/nixpkgs/commit/1b2139b3e2cda13c6816bafd22871ac60ddf83ac -- we can now cleanup things somewhat. Thanks for the original fix though and sorry for not getting the problem initially!

**Comment by garbas** [comment]
+1 ... VidyoDesktop works now

**Pull request closed without merging**
