### PR TITLE
nixos/gitlab-runner: reload on config change

### PR DESCRIPTION
**Pull request by bachp**
The current module on master is broken with gitlab-runner 12.5.0 as it tries to create a `Config.toml` lock next to it's config file, which is located in the nix store and thus not writable.

This fixes this issue.

Also with this change it is no longer required to restart the runner on every
change. Instead it can just reload it's config while running.

This is an alternative to https://github.com/NixOS/nixpkgs/pull/53048 with the additional advantage that the config is located in the usual location under `/etc`.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @max-wittig @zimbatm @globin @makefu @fpletz @flokli @bgamari

### CODE REVIEW

**Review by max-wittig — APPROVED** [review]

**Comment by max-wittig** [comment]
@zimbatm @globin @makefu @fpletz @flokli @bgamari The runner is currently broken. Any chance you could take a look?

**Comment by zimbatm** [comment]
Is it possible to specify to the gitlab-runner where to put the lockfile? `/etc` is not really meant to be writable on NixOS.

**Comment by flokli** [comment]
Yeah, writing to `/etc` will probably not work.

We could do some `libredirect` hackery to point the lock file elsewhere, but this really should be fixed properly upstream - `gitlab-runner` doesn't really play nice with CasC in general…

I left feedback upstream at https://gitlab.com/gitlab-org/gitlab-runner/issues/4876#note_253544148.

If somebody would be up to do a MR implementing https://gitlab.com/gitlab-org/gitlab-runner/issues/5024, we could fetchpatch and apply to gitlab-runner until it's merged…

**Comment by bachp** [comment]
We could also put the config file to `/var/lib` as proposed in https://github.com/NixOS/nixpkgs/pull/53048 or even put it into `/run`.

**Comment by flokli** [comment]
Yes, but if we do that, it can't be updated from nix, because how do you diff state changed by gitlab-runner from intended config changes done via nix?

**Comment by max-wittig** [comment]
@flokli I've started to work on this: https://gitlab.com/gitlab-org/gitlab-runner/merge_requests/1700

**Comment by max-wittig** [comment]
Do we want to just patch this? https://gitlab.com/gitlab-org/gitlab-runner/merge_requests/1700/diffs?commit_id=5be5ab6eeaad6c10ef3b692df662547e60a99e88

It does seem like nobody is reacting on GitLab side.

**Comment by flokli** [comment]
yes, I think we should.

Can you add a PR `fetchpatch`ing it?

**Comment by bachp** [comment]
Seems like upstream decided to remove the lock file again https://gitlab.com/gitlab-org/gitlab-runner/issues/4876#note_257319457

@flokli Do you know what state changes gitlab-runner does? The only one I know of is if you run `gitlab-runner register` which is not usable with the current nixos module.

**Comment by flokli** [comment]
@bachp 

`gitlab-runner register` asks the user a lot of things (https://gitlab.com/gitlab-org/gitlab-runner/blob/master/commands/register.go#L72), but I assume all that can be pre-populated from the config file.

The registration token is passed down to the `RegisterRunner` command. For now, only `Token` is stored back to the config struct (and the private boolean `registered`, which doesn't end up in config):
https://gitlab.com/gitlab-org/gitlab-runner/blob/master/commands/register.go#L254

**Comment by zimbatm** [comment]
gitlab-runner has been updated: https://github.com/NixOS/nixpkgs/pull/76190

> This release does no longer contain the lock file that broke the NixOS
module in 12.5.0

**Comment by bachp** [comment]
Does anybody still want dynamic config reload?

**Comment by flokli** [comment]
Yes please :-)

I assume we can merge this even with https://gitlab.com/gitlab-org/gitlab-runner/issues/5024#note_273315256 being stuck.

**Pull request merged**
