### PR TITLE
imlib2: 1.8.1 -> 1.9.1

### PR DESCRIPTION
**Pull request by kilianar**
###### Description of changes
Update to latest upstream release.

I cherry-picked the commit to master, `feh` and `ffmpeg-full` build and work on x86_64-linux.
###### Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
This causes `feh` to fail its tests on macos 10.15:

```
test/feh.t ..... 62/73 # Looks like you failed 10 tests of 73.
test/feh.t ..... Dubious, test returned 10 (wstat 2560, 0xa00)
Failed 10/73 subtests 
test/mandoc.t .. # mandoc not installed, test skipped. This is NOT fatal.
test/mandoc.t .. ok

Test Summary Report
-------------------
test/feh.t   (Wstat: 2560 Tests: 73 Failed: 10)
  Failed tests:  23, 26, 29, 32, 35, 38, 41, 44, 47, 53
  Non-zero exit status: 10
Files=2, Tests=74,  1 wallclock secs ( 0.04 usr  0.01 sys +  0.41 cusr  0.43 csys =  0.89 CPU)
Result: FAIL
```

**Comment by risicle** [comment]
The above is happening for me on nixos x86_64 too.

**Comment by kilianar** [comment]
Building feh 3.8 worked fine, but in the meanwhile the version on master was bumped to 3.9 (https://github.com/NixOS/nixpkgs/commit/7d69cd5908e92862e449b53509e0d3b9bd07b3b8) and now the tests are failing for me too.

As you have guessed, the failing tests try to load empty images and the returned error message should match a given one.

Changing the [hard coded warning](https://github.com/derf/feh/blob/master/test/feh.t#L50) in `postPatch` would solve this issue.

**Comment by risicle** [comment]
The update in master should get auto-backmerged to staging, so it's probably the responsibility of this PR to make that fix now.

**Comment by risicle** [comment]
WFM now building applicable `passthru.tests` on macos 10.15 & nixos x86_64

**Review by risicle — APPROVED** [review]

**Pull request merged**
