### PR TITLE
ghc94x: apply the Cabal cycle patch on aarch64-darwin

### LINKED ISSUE #220647: Port patch fixing cabal Paths_* module caused reference cycle on aarch64-darwin to GHC 9.4
The problem described in #140774 also affects GHC 9.4 (and will also affect GHC 9.6 etc.), so we need to rebase the relevant `Cabal-3.6-paths-fix-cycle-aarch64-darwin.patch` for Cabal 3.8 (and 3.10). The issue is not pressing, but should be taken care of before we switch to GHC 9.4 as the default compiler.

### PR DESCRIPTION
**Pull request by SamirTalwar**
## Description of changes

Fixes #220647.

This was already applied to GHC 9.2.x, but was not copied to GHC 9.4.x. I have had issues with this locally.

The same patch works for both Cabal 3.6 and 3.8, so we can just reuse it.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SamirTalwar** [comment]
Tested here: https://github.com/hasura/graphql-engine/blob/master/nix/overlays/ghc.nix

**Comment by sternenseemann** [comment]
Cherry-picked as f6f780f129f50df536fb301b9dac554f9744ab4b. Thanks!

**Comment by sternenseemann** [comment]
@SamirTalwar Notably, this breaks

* [GHC 9.4.2](https://hydra.nixos.org/build/230943178/nixlog/1) on aarch64-darwin
* [GHC 9.4.3](https://hydra.nixos.org/build/230935095/nixlog/1) on aarch64-darwin

It could be interesting to investigate why this is, alternatively we can drop the patch there, we'd probably not miss it.

**Comment by SamirTalwar** [comment]
@sternenseemann: I find this very surprising. I checked the release branches for GHC [9.4.1](https://gitlab.haskell.org/ghc/ghc/-/tree/ghc-9.4.1-release/libraries) to [9.4.5](https://gitlab.haskell.org/ghc/ghc/-/tree/ghc-9.4.5-release/libraries) and they all reference the same Cabal commit (the 3.8.1.0 release) via submodule.

I downloaded the source tarballs that nixpkgs references, but `git diff --no-index` seems to think that the Cabal packages are identical from v9.4.2 to v9.4.5.

So… I tried applying the patch, and I get that error on all versions. I don't know why it magically works for GHC 9.4.4 and 9.4.5 in the derivation.

I think I will need to recreate the patch for Cabal 3.8 properly, and open a new PR.

**Comment by SamirTalwar** [comment]
Ah, here's the difference: the following patch is only added to GHC 9.4.4 and 9.4.5: https://github.com/NixOS/nixpkgs/blob/195975b1387b69ac5566338819298d7abc595ac3/pkgs/development/compilers/ghc/9.4.5.nix#L193-L200

Any objection to adding it to all 9.4.x versions?

I will also generate a new patch file that patches perfectly, but I'd prefer not to make two, especially as that patch above seems prudent regardless of GHC version.

**Comment by sternenseemann** [comment]
No objections, that sounds good!

**Comment by SamirTalwar** [comment]
Here we go: https://github.com/NixOS/nixpkgs/pull/248209

With that, the patch merges cleanly again. (At least when I tested locally.)

**Pull request closed without merging**
