### PR TITLE
vscode, vscodium: 1.62.3 -> 1.63.0

### PR DESCRIPTION
**Pull request by bobby285271**
###### Motivation for this change

It builds and launches but please just consider me as samuela's nixpkgs-upkeep bot.

https://code.visualstudio.com/updates/v1_63

Closes #149842
Closes #149843

###### Things done

- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).
- [x] Runs the updateScript.
- [x] Makes it builds on x86_64-linux:

```diff
- substituteInPlace $unpacked/sudo-prompt/index.js \
+ substituteInPlace $unpacked/@vscode/sudo-prompt/index.js \
```

### CODE REVIEW

**Comment by bobby285271** [comment]
@ofborg build vscodium
@ofborg test vscodium

**Comment by jyooru** [comment]
Result of `nixpkgs-review pr 149829` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>vscode</li>
    <li>vscode-fhs</li>
    <li>vscode-with-extensions</li>
    <li>vscodium</li>
    <li>vscodium-fhs</li>
  </ul>
</details>

**Comment by jyooru** [comment]
Executable tested and works

**Comment by Synthetica9** [comment]
I prefer this over #149842 & #149843 because this actually seems to work ;)

**Comment by Synthetica9** [comment]
@ofborg test vscodium

**Comment by samuela** [comment]
Thanks for this @bobby285271 !

**Pull request merged**
