### PR TITLE
ruby.dev

### PR DESCRIPTION
**Pull request by zimbatm**
###### Things done:
- [x] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- [x] Built on platform(s): NixOS
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

The idea is to bundle ruby, rubygems, bundler and bundix together. I was
having issues where bundler was installed with ruby 2.3.0 and I wanted to use
ruby 2.0.0. I also think that bundix's behaviour might change depending on the bundler version (?).

With this change all the developer has to do is install `ruby_2_0_0.dev`
either in his environment or in a nix-shell to get the proper tooling.

This needs testing, especially in regards to rubygems, I think the one shipped with ruby is picked-up and we might want to install it directly into the ruby derivation (?).

It also means that bundix needs to work with all the ruby version that we ship, is this a bad idea ?

cc @cstrahan , @manveru

### CODE REVIEW

**Comment by cstrahan** [comment]
This looks good to me.

> This needs testing, especially in regards to rubygems, I think the one shipped with ruby is picked-up and we might want to install it directly into the ruby derivation (?).

Don't have time at the moment to confirm/look into this. Not sure what to do here.

**Comment by cstrahan** [comment]
You might want to confirm that the `$GEM_PATH` is being set such that the given `rubygems` is included therein. I suppose the Rubygems included with Ruby should do some sort of bootstraping so that the newer version on `$GEM_PATH`... but that's just speculation on my part. I don't actually know Rubygems is supposed to work in this scenario.

**Comment by zimbatm** [comment]
Maybe that's the issue. I don't really know how the /nix-support works but it doesn't seem to get added to the environment (even if I add it to the env paths), even restarting the shell doesn't add `$GEM_PATH`.

If I run `irb` and then `p $LOADED_FEATURES` is shows the rubygems that's bundled with ruby.

I'm going to try to install rubygems directly into the ruby derivation to make the environment variable redundant. I don't think that most people want to switch rubygems versions, just get the latest-one.

**Comment by zimbatm** [comment]
Now I can run `ruby -e "puts Gem::VERSION"` and get the latest version :)

**Comment by zimbatm** [comment]
I have been running nox-review quite a bit on this and as a result have produced fixes that are now in master. There are still some failing tests but I think they are all unrelated to the proposed changes (see below).

A last issue is that the dev version gets "upgraded" to the regular version. Eg: ruby-2.3.0-dev -> ruby-2.3.0. Do you have any ideas on how to avoid that ?

```
# Xen issue https://github.com/NixOS/nixpkgs/issues/13590
 ‘/nix/store/1kbkvv6w44s60sh9p00dbskmk4amfnyh-libvirt-1.3.0.drv’
 ‘/nix/store/8480d54wfnlgkb5r0hrb5jgw5fnv6j6s-libvirt-glib-0.2.3.drv’
 ‘/nix/store/xifqihaygpqv500v10pfnshh45a047yy-libvirt-python-1.3.0.drv’
 ‘/nix/store/y5g0blijwzj9cvw5q649mpcjrfcck6xq-libvirt-python-1.3.0.drv’
 ‘/nix/store/vgqxpfy88pnmdg0rh6pyk241hx43l9bw-libguestfs-1.29.5.drv’
 ‘/nix/store/wviaqk1pmv7nbxn1yz912fad6yc7aci9-xen-4.5.2.drv’
 ‘/nix/store/3dmijq0nx5m8g7kapviwcmjvgrkbp47z-xen-4.5.0.drv’
 ‘/nix/store/psbsl8j4pckqljkm2lkm5yzdz7qzbh1b-xen-4.5.0.drv’
 ‘/nix/store/mb8ycmgnn5ar29cr7a82k60n1fnrkghs-virt-manager-1.3.1.drv’
 ‘/nix/store/zp14kjrav57nynzrgab8njcly0ixdhz0-virt-viewer-2.0.drv’ failed
 ‘/nix/store/4swcjkqijbx3cdlhwgy99b0r05hvg711-virtinst-0.600.4.drv’
 ‘/nix/store/6f6hidphi9pjkmcn7cpkaxzmprs9rnv5-collectd-5.5.0.drv’
 ‘/nix/store/nyv8yl69isbgqz9vmw708czh1wkwbx3p-gnome-boxes-3.18.1.drv’
 # Darwin only
 ‘/nix/store/7n86nlyc2x52m4yp3lg99mkcwffxjn9r-macvim-7.4.909.drv’
 # TODO: Really broken packaging, doesn't work with sandboxing
 ‘/nix/store/h54sk48d6g6zfrksci0dlv4qchhvccy6-openbr-0.5.drv’
 ‘/nix/store/f4bx84lmhhxfby1fvcbjm37lsl72dix2-openbr-0.5.drv’
 # Broken because of QT?
 ‘/nix/store/5f06p868qxgrsx0js112ljxb4j1ir3dr-antimony-0.8.0b.drv’
 # Luarocks compilation issue. module 'std.debug_init' not found:
 ‘/nix/store/7b72p2alrvchk3ajdphfgq24wfx93mxz-mudlet-3.0.0-delta.drv’
 # qt cmath 32:5: note:   'std::isnan'
 ‘/nix/store/97dn2i782nscksm45970i60c40v52rrh-mgba-0.3.1.drv’
 # scripts/cl_gobject.c:488:5: error: non-floating-point argument in call to function `'__builtin_isnan'`
 ‘/nix/store/55wik09nmyg1j65c23g8cjix8lw6dkps-dwb-2015-07-07.drv’
 ‘/nix/store/cxy620918cihsrm6g6700kf6iizwpv8x-dwb-2015-07-07.drv’
 # Project ERROR: Unknown module(s) in QT: qml quick webkitwidgets x11extras
 ‘/nix/store/kwyki5b76iwxpjc2h9gmkmf17xcww0md-shotcut-14.09.drv’
 # source is broken / down
 ‘/nix/store/dknff5gshprnabk1hqy7jh60vmkhnkjf-rq-3.4.0.drv’
 # /usr/bin/env sandbox issue
 ‘/nix/store/cvm7d5rs00l84bsdbngr1dic4vqi3g97-sage-6.8.drv’
 # cp: missing destination file operand after '/nix/store/c0hsw6dyzx23dl4bfyby2lw85vs431rf-lp_solve-5.5.2.0/lib'
 ‘/nix/store/g0z6ic4mdc27zqjqiq4rvjn5wlk5fz2b-openmodelica.drv’
 # gcc: error: /tmp/nix-build-jsaddle-0.3.0.1.drv-0/ghc7223_0/ghc_31.o: No such file or directory
 ‘/nix/store/qpgw3sqiqmq6rvipx9pw3ia2axbjdprl-leksah.drv’
 # ? seems to work
 ‘/nix/store/85avf6an77lck8fpi65qgm1cpzrpdmf4-vlc-2.2.2.drv’
 ‘/nix/store/v0ifkhy05fbzpiwss8q234ws2986d37n-signon-8.57.drv’
 # TODO: not directly reachable
 ‘/nix/store/486mqnyqhpzmsfrpcfdd89xcrwnxpz5f-phonon-backend-vlc-0.8.2.drv’
 ‘/nix/store/am2zhavbk7fjqlc30hw3vwvkgikcmap9-calamares-1.0.drv’
 ‘/nix/store/g66rfa9jcighcaq5vpdypdwryn4c76b8-xapian-bindings-1.2.8.drv’
 ‘/nix/store/vq8aalvg11mh5jw7makas6dj6f20yxjr-xapian-bindings-1.0.23.drv’
 ‘/nix/store/s2swpa6r6xdr3h46ngvx6bs34marnh48-perl-Sys-Virt-1.2.19.drv’
 ‘/nix/store/y9m34gfi6mdv80shvk0sgw3ss8dg5r5i-kde-l10n-sr-qt5-15.12.1.drv’
```

**Comment by cstrahan** [comment]
Nix parses the `2.3.0-dev` part as the version, which is considered newer than `2.3.0`.

Two ways around this:

1. Do something like `name = let parsed = builtins.parseDrvName ruby.name; in  "${parsed.name}-dev-${parsed.version}";`
2. Or alternatively (and _ideally_, IMO): `name = "${ruby.baseName}-dev-${ruby.version}";`

No. 2 would require adding a `baseName` passthru to the Ruby packages. I chose `baseName` as the attr name, because (I think) that's the name of the config entry that should correspond to the Ruby name (e.g. ruby/jruby/mruby/etc):

    λ ruby -e 'puts RbConfig::CONFIG["RUBY_BASE_NAME"]'
    ruby

**Comment by zimbatm** [comment]
Thanks for the inspiration. How about like this ^ 0135df8adb4e365cafc629d3c812870ff6da8a65

I think the rubyEngine passthrough covers the name already. On jruby's irb I get:
```
irb(main):001:0> RUBY_ENGINE
=> "jruby"
irb(main):002:0> RUBY_ENGINE_VERSION
=> "9.0.5.0"
irb(main):003:0> RUBY_VERSION
=> "2.2.3"
```

I also had a brief look to produce a jruby.dev version and if gems could be installed by swapping ruby = jruby but it's a bit too much effort for now. Do you know what all the passtrough are for ? It seems to me that we should just be exporting the ruby.engine ruby.engineVersion and ruby.version and infer the libPath and gemPath ? I'm happy do discuss all of this on IRC if you want.

**Comment by cstrahan** [comment]
Yeah, that looks great. I forgot about the `rubyEngine` passthru (and, IIRC, I wrote that - ha).

**Comment by zimbatm** [comment]
Alright, I've tested the changes with a couple of things like building gitlab and everything seems to be working as expected.

**Comment by zimbatm** [comment]
New failure list, all seem unrelated to the ruby changes:
```
error: build of ‘/nix/store/1791djrnr68isn58qbrf4qga7yidby4h-openbr-0.5.drv’,
‘/nix/store/1h1v599h1qrai62cqaw0xxz39cyq11aa-leksah.drv’,
‘/nix/store/29224sjxlkv7v79r7091lgv3zcfvnmh6-synfigstudio-1.0.2.drv’,
‘/nix/store/356ay64xm1a3l2f5zxf2aiqz6kylycqi-vlc-2.2.2.drv’,
‘/nix/store/3qsfvjkwpv9gkfkf45h3kazij07y1n8c-openbr-0.5.drv’,
‘/nix/store/5mmcv4xx12f4q6ch1gq89zy1fpm46hqz-virtinst-0.600.4.drv’,
‘/nix/store/5sqrad2jkxfy78b7kff50dq7wj9w167i-shotcut-14.09.drv’,
‘/nix/store/99sy30724fpigvd0wqxkcspvk57rd7p0-signon-8.57.drv’,
‘/nix/store/cr918qwrrwcisrvmb6badyz3b0vriihq-virt-manager-1.3.1.drv’,
‘/nix/store/fbvq1n8yhy1zalhmnxxlkv59k649ah72-phonon-backend-vlc-0.8.2.drv’,
‘/nix/store/fidqagn9np1f68yb42i1mnxvj7nhi29m-xapian-bindings-1.0.23.drv’,
‘/nix/store/ggz9dw6p8p2bjwq1ad15hgjg3qm9456l-calamares-1.0.drv’,
‘/nix/store/h2k1jxr9b09g97szfsdwkpffzb4k06n7-dwb-2015-07-07.drv’,
‘/nix/store/m42bvgpgrjr2gdnbdg6nd8j38qijidp5-kde-l10n-sr-qt5-15.12.1.drv’,
‘/nix/store/ma1c8x7cbv5bq9az5k7p7pbwhxqzrszz-vim-with-plugins.drv’,
‘/nix/store/rgrg6njbwhlkpzvlynn8r677waci3vd0-xapian-bindings-1.2.8.drv’,
‘/nix/store/rxnhr5yn2707x9pnf1blrw12hgvxpqa4-sage-6.8.drv’,
‘/nix/store/s29q5w6nf2z9w78zmvd9axmmbf300p2l-mgba-0.3.1.drv’,
‘/nix/store/x9w8ffc18c12dlr130nrlgny75inbjmq-mudlet-3.0.0-delta.drv’,
‘/nix/store/ydmi9ibqajz64qprrkn913mblkf89r9i-macvim-7.4.909.drv’,
‘/nix/store/z4vpq0dimxh0p64sbz3l2zchg6ylk86f-openmodelica.drv’,
‘/nix/store/zvvb1h1zb2n9h05w97bw40rr1-dwb-2015-07-07.drv',
failed
```

**Comment by zimbatm** [comment]
Going ahead. Let me know if I broke anything.

**Comment by matthiasbeyer** [comment]
I really like this, though I'd even more like this if there was some documentation added. Can you please add an addendum?

**Pull request merged**
