### PR TITLE
mullvad-vpn: 2024.1 -> 2024.2

### PR DESCRIPTION
**Pull request by DogeRam1500**
https://github.com/mullvad/mullvadvpn-app/releases/tag/2024.2

## Description of changes
Updated Mullvad VPN from 2024.1 to 2024.2

### CODE REVIEW

**Comment by getchoo** [comment]
Result of `nixpkgs-review pr 310441` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>mullvad-vpn</li>
  </ul>
</details>

**Review by getchoo — APPROVED** [review]

**Comment by ajs124** [comment]
Please don't merge master into your branch, but rebase instead.

**Comment by DogeRam1500** [comment]
> Please don't merge master into your branch, but rebase instead.
> 
> Edit: Also, 2024.3 is already out now.

This is my first time using git, I'll be sure to learn how to do that for future pull requests.

**Comment by ajs124** [comment]
I understand, but I don't think we can/should merge this, as is.

Can you rebase this branch and force push it?

**Comment by DogeRam1500** [comment]
I think it's best if I just close this pull request and let someone with more experience with using Git and nixpkgs take care of this, I clearly have a lot of learning to do with git

**Comment by ajs124** [comment]
done  #312499

**Pull request closed without merging**
