### PR TITLE
Python unstable

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jonringer** [comment]
So, for python updates and bumps that would cause large rebuilds, should we make PR's against python-unstable?

**Comment by FRidh** [comment]
It's a branch I use to check the effect of changes, however, I force push often and at times it contains also a stable (e.g. 19.03) branch instead. Therefore, making a PR against that branch is probably not a good idea.

**Comment by jonringer** [comment]
Okay, so this is just a mechanism for you to verify a series of large changes. Sounds good.

**Comment by FRidh** [comment]
Right, there's is a dedicated Hydra job for this branch
https://hydra.nixos.org/jobset/nixpkgs/python-unstable

**Pull request merged**
