### PR TITLE
flameshot: Add nix-update-script support

### PR DESCRIPTION
**Pull request by otavio**
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
nix-update does not need this entry in each package and also works flawlessly on staging. IMO we should remove all occurrences of this.

**Comment by otavio** [comment]
It doesn't work if I use the `update.nix` script. I often use:

```sh
nix-shell maintainers/scripts/update.nix --argstr package flameshot
```
or 
```sh
nix-shell maintainers/scripts/update.nix --argstr maintainer otavio
```

So how can I use this workflow without it?

**Comment by SuperSandro2000** [comment]
> ``nix-shell maintainers/scripts/update.nix --argstr package flameshot``

``nix-update flameshot``

It can't do by maintainer.

**Comment by otavio** [comment]
@SuperSandro2000 my Nix'fu level is too low yet to adapt it. I am glad to test a PR with it.

**Pull request merged**
