### PR TITLE
WIP: add ruby-3.2

### PR DESCRIPTION
**Pull request by emptyflask**
###### Description of changes

Ruby 3.2 is now the current release (as of 25 Dec 2022)

###### Things done

Added ruby 3.2 source, created a new patch for `common.mk`, etc. Currently running into a problem:
```
shrinking /nix/store/gsz2b7gqamhxvf30w6hxa2ian5p5g69f-ruby-3.2.0/lib/ruby/3.2.0/x86_64-linux/ripper.so
gzipping man pages under /nix/store/gsz2b7gqamhxvf30w6hxa2ian5p5g69f-ruby-3.2.0/share/man/
strip is /nix/store/wn31i3dzwahz6ccws8bs1nwyqrpgsvj7-gcc-wrapper-11.3.0/bin/strip
stripping (with command strip and flags -S) in  /nix/store/gsz2b7gqamhxvf30w6hxa2ian5p5g69f-ruby-3.2.0/lib /nix/store/gsz2b7gqamhxvf30w6hxa2ian5p5g69f-ruby-3.2.0/bin
patching script interpreter paths in /nix/store/gsz2b7gqamhxvf30w6hxa2ian5p5g69f-ruby-3.2.0
checking for references to /build/ in /nix/store/gsz2b7gqamhxvf30w6hxa2ian5p5g69f-ruby-3.2.0...
RPATH of binary /nix/store/gsz2b7gqamhxvf30w6hxa2ian5p5g69f-ruby-3.2.0/lib/ruby/3.2.0/x86_64-linux/enc/cp949.so contains a forbidden reference to /build/
error: builder for '/nix/store/34qljbikyl8qlz9cbjlc8fi35z2fnhmk-ruby-3.2.0.drv' failed with exit code 1;
       last 10 log lines:
       > shrinking /nix/store/gsz2b7gqamhxvf30w6hxa2ian5p5g69f-ruby-3.2.0/lib/ruby/3.2.0/x86_64-linux/enc/euc_tw.so
       > shrinking /nix/store/gsz2b7gqamhxvf30w6hxa2ian5p5g69f-ruby-3.2.0/lib/ruby/3.2.0/x86_64-linux/enc/cesu_8.so
       > shrinking /nix/store/gsz2b7gqamhxvf30w6hxa2ian5p5g69f-ruby-3.2.0/lib/ruby/3.2.0/x86_64-linux/syslog.so
       > shrinking /nix/store/gsz2b7gqamhxvf30w6hxa2ian5p5g69f-ruby-3.2.0/lib/ruby/3.2.0/x86_64-linux/ripper.so
       > gzipping man pages under /nix/store/gsz2b7gqamhxvf30w6hxa2ian5p5g69f-ruby-3.2.0/share/man/
       > strip is /nix/store/wn31i3dzwahz6ccws8bs1nwyqrpgsvj7-gcc-wrapper-11.3.0/bin/strip
       > stripping (with command strip and flags -S) in  /nix/store/gsz2b7gqamhxvf30w6hxa2ian5p5g69f-ruby-3.2.0/lib /nix/store/gsz2b7gqamhxvf30w6hxa2ian5p5g69f-ruby-3.2.0/bin
       > patching script interpreter paths in /nix/store/gsz2b7gqamhxvf30w6hxa2ian5p5g69f-ruby-3.2.0
       > checking for references to /build/ in /nix/store/gsz2b7gqamhxvf30w6hxa2ian5p5g69f-ruby-3.2.0...
       > RPATH of binary /nix/store/gsz2b7gqamhxvf30w6hxa2ian5p5g69f-ruby-3.2.0/lib/ruby/3.2.0/x86_64-linux/enc/cp949.so contains a forbidden reference to /build/
```
- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by emptyflask** [comment]
> I just stumpled over [Add support for Ruby 3.2 YJIT](https://github.com/bobvanderlinden/nixpkgs-ruby/commit/6d63f96bed170a2e24918dd5e4d0ba159b03b153)
> where  [bobvanderlinden](https://github.com/bobvanderlinden/nixpkgs-ruby/commits?author=bobvanderlinden) seems to have solved porting ruby to 3.2.0. Also to enable YJIT one needs rustc.
> Thanks for your guys bringing ruby 3.2 to nixos!

That's great news, thanks for the heads up. I tested out his derivation and it works perfectly, so whenever I have some time I'll pull the relevant parts over to nixpkgs. Though maybe nixpkgs-ruby is a better source for actual projects...

**Comment by thefloweringash** [comment]
I also started on this but haven't found the time to finish it, and you can see my efforts on my [ruby-3.2 branch](https://github.com/thefloweringash/nixpkgs/commits/ruby-3.2).

As for the reference to `/build/`, it looks like it's intentionally putting a setting the libdir to the build dir, which is going into the rpath of the encoding modules. This isn't a new change (https://github.com/ruby/ruby/commit/42c6ef00afc0164a2ac11fc344a0b379e14fddf5), so I don't know why it's a problem now. It only seems to be a problem when providing a `BASERUBY`, which IIUC, is only required for cross compilation. Nixpkgs also enables `useBaseRuby` when `useRailsExpress` is on, maybe we can try disabling that and seeing if anything breaks?

**Comment by anna328p** [comment]
has there been any further work on this PR?

**Comment by emptyflask** [comment]
Sadly no, I haven't had the time for it yet.

I was able to use @bobvanderlinden's flake config for some quick ruby 3.2 work, but it's a little less ergonomic than I'm used to, since unless I'm doing something wrong, updating gems with it requires commenting out `gems` from flake.nix temporarily.

**Pull request closed without merging**
