### PR TITLE
libvirt: 7.0.0 -> 7.2.0

### PR DESCRIPTION
**Pull request by wedens**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 120819` at fe455b15 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>libvmi</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/31560d36debb770700e63e4e8a33599f">nixopsUnstable</a></li>
  </ul>
</details>
<details>
  <summary>24 packages built successfully:</summary>
  <ul>
    <li>collectd</li>
    <li>collectd-data</li>
    <li>docker-machine-kvm</li>
    <li>docker-machine-kvm2</li>
    <li>gnome3.gnome-boxes</li>
    <li>haskellPackages.libvirt-hs</li>
    <li>libguestfs</li>
    <li>libvirt</li>
    <li>libvirt-glib</li>
    <li>minikube</li>
    <li>minishift</li>
    <li>perl530Packages.SysVirt</li>
    <li>perl532Packages.SysVirt</li>
    <li>python38Packages.guestfs</li>
    <li>python38Packages.libvirt</li>
    <li>python39Packages.guestfs</li>
    <li>python39Packages.libvirt</li>
    <li>terraform-full</li>
    <li>terraform-providers.libvirt</li>
    <li>vagrant</li>
    <li>virt-manager</li>
    <li>virt-manager-qt</li>
    <li>virt-top</li>
    <li>virt-viewer</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`lgpl2` is a deprecated license, please check if project uses `lgpl2Plus` or `lgpl2Only` and change `meta.license` accordingly.

Near pkgs/development/python-modules/libvirt/default.nix:25:5:
```
   |
25 |     license = licenses.lgpl2;
   |     ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement.

**Comment by jonringer** [comment]
didn't see anything alarming in https://libvirt.org/news.html#v7-2-0-2021-04-01

**Review by jonringer — COMMENTED** [review]
do you splitting these up into three commits?

```
libvirt: 7.0.0 -> 7.2.0
python3Packages.libvirt: 7.0.0 -> 7.2.0
perlPackages.libvirt: 7.0.0 -> 7.2.0
```
although related, they target different ecosystems.

**Comment by wedens** [comment]
> do you splitting these up into three commits?
> 
> ```
> libvirt: 7.0.0 -> 7.2.0
> python3Packages.libvirt: 7.0.0 -> 7.2.0
> perlPackages.libvirt: 7.0.0 -> 7.2.0
> ```
> 
> although related, they target different ecosystems.

I could do that, but the commits won't even evaluate/build individually due to version checks. If that's not an issue and splitting commits by ecosystem is a good practice, sure, I'll do it.

**Comment by wedens** [comment]
Closed in favor of #121965

**Pull request closed without merging**
