### PR TITLE
activitywatch: 0.12.2 -> 0.13.2

### LINKED ISSUE #348950: Update request: ActivityWatch 0.12.2 → 0.13.2
- Package name: ActivityWatch
- Latest released version: 0.13.2

- Current version on the unstable channel: 0.12.2
- Current version on the stable/release channel: 0.12.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

There is a Pull request for **0.13.1** https://github.com/NixOS/nixpkgs/pull/319121 by @huantianad

**No maintainers**

### PR DESCRIPTION
**Pull request by huantianad**
## Description of changes
Closes #348950

This update includes a few code changes that should be quite self explanatory to work with the new version.

I have yet to test the new binary `aw-notify` and the x11 based watchers as well. If anyone could help with that, it'd be great.

One big thing I would like to fix is the `aw-qt` finding the bundled tools like `aw-server` or the bundled watchers, when inside of the `activitywatch` `symlinkJoin`. Right now it fails to find any of the bundled tools, as it searches for them with `os.path.dirname(os.path.realpath(__file__))`, which points to inside of `aw-qt` instead of the `symlinkJoin`. This means that the program only works if it's installed to PATH...

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by huantianad** [comment]
Can't actually test rn because of pyqt build failure, I'll figure something out later.

**Comment by huantianad** [comment]
@NickCao hope you don't mind me bringing you in here, but wanted to ask rq if I'm doing `buildPythonApplication` correctly.

**Comment by NickCao** [comment]
> @NickCao hope you don't mind me bringing you in here, but wanted to ask rq if I'm doing `buildPythonApplication` correctly.

I don't see obvious problems. A nitpick is we do prefer `python3Packages` over `python3.pkgs` due to issues with splicing/cross-compilation.

**Comment by huantianad** [comment]
Thanks, I'll just include that here since im at it already.

**Pull request merged**
