### PR TITLE
xpra: 2.3.4 -> 2.5, unbreak?

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

It builds and bits seem to almost work,
would be nice to try it in a VM with the xpra module enabled or
something?

May want to fix default paths for things like sockets
in order to get usage other than via NixOS module working.

Thoughts/comments/testing appreciated :).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
Previously: #51877 (and others linked from there)

**Comment by aanderse** [comment]
I'm going to guess that https://github.com/NixOS/nixpkgs/pull/58589 has fixed the broken build on aarch64-linux.

@GrahamcOfBorg build xpra

**Comment by aanderse** [comment]
Results of nix-review:
```
1 package failed to build:
winswitch

2 package were build:
run-scaled xpra
```

**Comment by c0bw3b** [comment]
I think we can just mark winswitch as broken..
Its last commit was in Nov. 2016 for compat with Xpra **1.0**

**Review by Ekleog — APPROVED** [review]
LGTM! @dtzWill, any reason not to merge (potentially after having marked `winswitch` as broken)? :)

**Comment by dtzWill** [comment]
On Tue, 04 Jun 2019 12:26:45 -0700, Léo Gaspard <notifications@github.com> wrote:
> Ekleog approved this pull request.
> 
> LGTM! @dtzWill, any reason not to merge (potentially after having marked `winswitch` as broken)? :)
> 
> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/NixOS/nixpkgs/pull/58151#pullrequestreview-245653985Non-text part: text/html

Sounds good! I just was unable (not in the right position/context) to
check it worked in any capacity, but if it looks to work then ship it!
:)

(modulo marking winswitch as broken--which it effectively already is due
to its dep on xpra, right?)

**Comment by Ekleog** [comment]
Right, AFAIU if a dep is broken then the package can't be built without having allowed the dep, so marking it as broken should not make anything additional broken.

**Pull request merged**
