### PR TITLE
[21.05] mediatomb: use ffmpeg instead of ffmpeg_3

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
backport https://github.com/NixOS/nixpkgs/pull/123487

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by schmittlauch** [comment]
LGTM

what was tested:
- mediatomb builds successfully
- mediatomb NixOS test continues to fail, but this is due to gerbera
- mediatomb NixOS test succeeds when removing all gerbera-specific tests

what was **not** tested:
- actual real-world usage of mediatomb

Having a mediatomb that builds and passes tests in 21.05 is preferrable over a situation where mediatomb is insecure and the alternative gerbera *might* be broken as it does not pass tests.

**Review by schmittlauch — APPROVED** [review]
LGTM

what was tested:
- mediatomb builds successfully
- mediatomb NixOS test continues to fail, but this is due to gerbera
- mediatomb NixOS test succeeds when removing all gerbera-specific tests

what was **not** tested:
- actual real-world usage of mediatomb

Having a mediatomb that builds and passes tests in 21.05 is preferrable over a situation where mediatomb is insecure and the alternative gerbera *might* be broken as it does not pass tests.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 124757` at 989c0342 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>mediatomb</li>
  </ul>
</details>
<details>
  <summary>3 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

pkg-config is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/servers/mediatomb/default.nix:15:3:
```
   |
15 |   buildInputs = [ sqlite expat spidermonkey_68 taglib libexif curl ffmpeg file mp4v2 flac
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl2` is a deprecated license, please check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/servers/mediatomb/default.nix:22:5:
```
   |
22 |     license = licenses.gpl2;
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

autoreconfHook is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/servers/mediatomb/default.nix:15:3:
```
   |
15 |   buildInputs = [ sqlite expat spidermonkey_68 taglib libexif curl ffmpeg file mp4v2 flac
   |   ^
```
</li>
  </ul>
</details>

**Comment by schmittlauch** [comment]
Robot is right with its suggestions, but as the goal should be to drop this package in the next release anyways I'm okay to move forward with this.

**Pull request merged**
