### PR TITLE
sage: disable intermittent test and fix threejs breakage

### PR DESCRIPTION
**Pull request by collares**
This PR contains two changes:

1) Following the suggestion in https://github.com/NixOS/nixpkgs/pull/107663#issuecomment-755433414, I have disabled a test which occasionally causes a segfault. The segfault happens upstream too, see https://trac.sagemath.org/ticket/30945.

2) Starting with Three.js r125, the minified file does not contain the string `REVISION="125"` directly (it contains `n="125",...,REVISION=n`), breaking Sage's fragile way of obtaining revision data. I did not import a patch from upstream because Sage has since migrated to [its own fork of Three.js](https://github.com/sagemath/threejs-sage) in https://trac.sagemath.org/ticket/30915.

Sage migrated to a Three.js fork because they needed to add some extra exports, see https://trac.sagemath.org/ticket/30620 or the fork's README. This probably means that Sage 9.2 already has some incompatibilities with upstream Three.js >= r121, which does not export `OrbitControls`, `Line2`, `LineGeometry`, `LineMaterial`, `LineSegments2` and `LineSegmentsGeometry` (the `examples` folder does not end up in the final `three.js`/`three.min.js` files now). Three.js r121 is in nixpkgs since September (c1834f41029950b41e2e87ad3abb2819deaaee83), so I think unbreaking Sage first makes sense. (Edit: Looking at the relevant Three.js PRs, I see that this was deprecated in r124, not r121. Sorry for the inaccuracy.)

In the future, we have to decide if we want to use Sage's fork or if we want to patch upstream to include the extra exports. I prefer the second option to be honest. It should be easy, but I won't have time to do it until next week. If we do decide to use Sage's fork instead, perhaps we should wait for https://github.com/sagemath/threejs-sage/pull/1 which will upload the library to PyPI.

cc @omasanori @timokau

### CODE REVIEW

**Comment by collares** [comment]
@ofborg build sage

**Comment by omasanori** [comment]
Personally I also prefer the second one, though the first one is surely viable if upstream disagrees.
No rush, please take your time.

**Review by Lassulus — APPROVED** [review]

**Comment by collares** [comment]
Just noticed I was using underscores instead of hyphens in the patch file names. Fixed.

**Review by omasanori — APPROVED** [review]
I had run the test suite and found no new failure related to this changes. Thanks!

**Review by timokau — APPROVED** [review]
Thanks. Are you aware of any relevant upstream (three.js) discussions regarding the fork?

**Comment by collares** [comment]
@timokau I didn't find any relevant upstream discussion mentioning the fork, unfortunately. The only thing I know is that https://github.com/mrdoob/three.js/pull/18749 is the PR that motivated the fork. The three.js maintainers are determined to use ES6 modules and I guess Sage hasn't moved to (or doesn't plan to) using modules yet.

**Comment by timokau** [comment]
I see. Maybe it would be a good idea to ask upstream what they think about applying the patch in nixpkgs. I think the more conservative option would be to use the fork.

**Pull request merged**
