### PR TITLE
ghostscript: 9.22 -> 9.24 (security)

### PR DESCRIPTION
**Pull request by vcunat**
The $doc stuff needed changes, probably because of ghostscript newly
reacting to some configure flags that stdenv passes.
 - share/ghostscript/9.22/doc was an ugly location for documentation,
   and I didn't like their new share/ghostscript/9.24 either,
   so that got changed to share/doc/ghostscript/9.24
 - their process no longer installs examples, apparently,
   but I don't expect that would be any problem for us

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vcunat** [comment]
Uh, don't merge yet, there's a slight closure mess here.

**Comment by jb55** [comment]
> Uh, don't merge yet, there's a slight closure mess here.

it would be neat if the bot showed closure sizes or size deltas...

**Comment by vcunat** [comment]
Upstream claims there are no incompatible changes
- https://www.ghostscript.com/doc/9.23/News.htm
- https://www.ghostscript.com/doc/9.24/News.htm

so I guess we'll chance it.  I see [ABI changes](https://abi-laboratory.pro/index.php?view=timeline&l=ghostscript) but perhaps those were considered internal symbols or something.

**Comment by 7c6f434c** [comment]
@jb55 Of course, even in principle closure sizes can be reported only for things that were built

**Comment by vcunat** [comment]
`has: documentation`?   How did Borg determine that?

**Pull request merged**
