### PR TITLE
mpv: Add openal support

### PR DESCRIPTION
**Pull request by Baughn**
###### Motivation for this change

mpv no longer has HRTF support, which means it can't collapse positional (e.g. 5.1) audio to stereo (for headphones) while maintaining the surround effect. The recommended workaround is to use `-ao openal`, which does know how to do this.

(Assuming you put `hrtf = true` in ~/.alsoftrc.)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build mpv

**Comment by Mic92** [comment]
Can you disable openal on macOS?

**Comment by knedlsepp** [comment]
This fixes the darwin build for me:
```
     ++ optionals stdenv.isDarwin (with darwin.apple_sdk.frameworks; [
-      libiconv Cocoa CoreAudio
+      libiconv Cocoa CoreAudio OpenAL
     ]);
```

**Comment by Baughn** [comment]
@GrahamcOfBorg build mpv

**Comment by Mic92** [comment]
@GrahamcOfBorg build mpv

**Pull request merged**
