### PR TITLE
treewide: handle `*Phases` variables `__structuredAttrs`-agnostically

### PR DESCRIPTION
**Pull request by ShamrockLee**
## Description of changes

Always specify the preDistPhases attribute as a list instead of a string.

Append elements to the preDistPhases Bash variable using appendToVar instead of string or Bash array concatenation.

Handle element insertion before a specific element using string substitution as before, but handle both structured and unstructured attributes.

State explicitly in the Nixpkgs Manual, "*Phases attributes are lists" and "elements of *Phases variables contain no spaces."

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by corngood — APPROVED** [review]
+1 for dotnet stuff.  I promise to keep an eye out for this in the future. :)

**Comment by ShamrockLee** [comment]
Test `buildVimPlugin`:
@ofborg build spacevim

Test `autoreconfHook`:
@ofborg build voms
@ofborg build dasher

Test `gimpPlugins`:
@ofborg build gimpPlugins

I'm unsure how to test the `pkgs/build-support/coq/default.nix` changes. Ping @CohenCyril

I'm unsure how to test the `makeDarwinBundle` changes. Ping @hexagonal-sun

I'm unsure how to test `releaseTools`. Ping @edolstra

Test `hareHook`:
@ofborg build bonsai
@ofborg build haredo

I'm unsure how to test the setup hook of `gnustep-make`. Ping @ashalkhakov @matthewbauer @2xsaiko

Test `xfce4.setupHook`
@ofborg build xfce.xfce4-i3-workspaces-plugin

Test `dotnet-sdk-setup-hook.sh`:
@ofborg build nbxplorer

Test `writeRequiredOctavePackagesHooks`:
@ofborg build octavePackages.audio

Test `pytestCheckHook`:
@ofborg build python3Packages.six

Test `pytest-forked`'s setup hook:
@ofborg build python3Packages.httplib2

Test `pytest-xdist`'s setup hook:
@ofborg build python3Packages.quodlibet

Test `pytest_7`'s setup hook:
@ofborg build python3Packages.graphviz

Test the setup hook of pytest for Python 2 (PyPy is still supporting Python2, and will continue to support it):
@ofborg build pypy2Packages.six

Test `glib`'s setup hook.
@ofborg build image-roll

Test `liquidfun`:
@ofborg build liquidfun

I'm unsure how to test the changes in `qtbase-setup-hook.sh` `qmake-hook.sh` for Qt 5 and 6. Ping @ttuegel

I'm unsure how to test the changes in `pkgs/servers/home-assistant/build-custom-component/manifest-requirements-check-hook.sh`. Ping @graham33

**Comment by emilazy** [comment]
> Test the setup hook of pytest for Python 2 (PyPy is still supporting Python2, and will continue to support it): @ofborg build pypy2Packages.six

(FWIW although PyPy2 will of course continue to be packaged, I’m quite sure `python2-modules` will go away as soon as the new GIMP comes out and I figure out how to get resholve onto the C++ OSH. resholve would be a more relevant test here.)

**Review by philiptaron — APPROVED** [review]
One two things in here look scary at all to me.

I did a "quick" staging build on those two and everything came up roses. 🌹🌹🦌🌹🌹 

Result of `nixpkgs-review pr 339117 -p python3Packages.pytest-forked -p python3Packages.pytest-xdist` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python3Packages.pytest-forked</li>
    <li>python3Packages.pytest-forked.dist (python3Packages.pytest-forked.dist.dist)</li>
    <li>python3Packages.pytest-xdist</li>
    <li>python3Packages.pytest-xdist.dist (python3Packages.pytest-xdist.dist.dist)</li>
  </ul>
</details>

**Comment by philiptaron** [comment]
I intend to merge this within the next day.

**Comment by ShamrockLee** [comment]
> One two things in here look scary at all to me.
> 
> I did a "quick" staging build on those two and everything came up roses. 🌹🌹🦌🌹🌹 
> 
> Result of `nixpkgs-review pr 339117 -p python3Packages.pytest-forked -p python3Packages.pytest-xdist` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
> <details>
>   <summary>4 packages built:</summary>
>   <ul>
>     <li>python3Packages.pytest-forked</li>
>     <li>python3Packages.pytest-forked.dist (python3Packages.pytest-forked.dist.dist)</li>
>     <li>python3Packages.pytest-xdist</li>
>     <li>python3Packages.pytest-xdist.dist (python3Packages.pytest-xdist.dist.dist)</li>
>   </ul>
> </details>

It would be great if they could be handled more gracefully (e.g. without string substitutions or if-blocks). Still, I wonder if it worths it to craft a generic global Bash helper function (like `appendToVar`) for such a specific use case.

**Comment by philiptaron** [comment]
> It would be great if they could be handled more gracefully (e.g. without string substitutions or if-blocks). Still, I wonder if it worth it to craft a generic global Bash helper function (like `appendToVar`) for such a specific use case.

Yeah, I see no need to do so at the present juncture; it's likely that these two derivations could get golfed into something neater, in fact I'm certain of it, but no need to make the perfect be the enemy of this quite good PR.

**Comment by Artturin** [comment]
This might have caused https://github.com/NixOS/nixpkgs/pull/351010 `"${mingw-patch}/*.patch"` to break

**Comment by ShamrockLee** [comment]
> This might have caused #351010 `"${mingw-patch}/*.patch"` to break

This PR changed the semantics of the `__structuredAttrs = false` packages only when changing from `fooPhases+=(myPhase)` to `appendToVar fooPhases myPhase`.

The breakage of `patches = [ "${mingw-patch}/*patch" ]` seems like an issue of the globbing handling of `patches`, but the diff of this PR hasn't touched the code processing `patches`.

**Comment by greg-hellings** [comment]
> > This might have caused #351010 `"${mingw-patch}/*.patch"` to break
> 
> This PR changed the semantics of the `__structuredAttrs = false` packages only when changing from `fooPhases+=(myPhase)` to `appendToVar fooPhases myPhase`.
> 
> The breakage of `patches = [ "${mingw-patch}/*patch" ]` seems like an issue of the globbing handling of `patches`, but the diff of this PR hasn't touched the code processing `patches`.
> 
> Does `patches = [ "${mingw-patch}/*patch" ]` work before the merging commit of this PR but break afterward?

Doing a bisect on the problematic branches, it appears that the breakage appeared [here](https://github.com/NixOS/nixpkgs/commit/bc0395ee6f9964065665adf3d365a2f93c3b4ca5) which doesn't seem to be part of this branch.

**Comment by emilazy** [comment]
cc @wolfgangwalther

**Pull request merged**
