### PR TITLE
opentelemetry-collector-contrib: 0.78.0 -> 0.87.0

### PR DESCRIPTION
**Pull request by spacekitteh**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by spacekitteh** [comment]
argh how do i get the channel check to re-run

**Comment by spacekitteh** [comment]
Okay, this is ready I believe.

**Comment by spacekitteh** [comment]
!ofborg check

**Comment by mweinelt** [comment]
> !ofborg check

https://github.com/NixOS/ofborg#commands

**Comment by spacekitteh** [comment]
I was going from memory :D

**Comment by spacekitteh** [comment]
@ofborg test

**Review by 06kellyjac — CHANGES_REQUESTED** [review]
Thanks for the update.

Can you update your PR title and commit to match contributing
`update opentelemetry-collector-contrib: v0.78.0 -> v0.85.0` -> `opentelemetry-collector-contrib: 0.78.0 -> 0.85.0`

Also why are you removing `CGO_ENABLED = 0;`?
We've had issues in the past when we've not had this set and that README item still requires it to be disabled AKA what we have so I don't think that position has changed

CC: @uri-canva

**Comment by spacekitteh** [comment]
> Also why are you removing `CGO_ENABLED = 0;`? We've had issues in the past when we've not had this set and that README item still requires it to be disabled AKA what we have so I don't think that position has changed
> 
> CC: @uri-canva

`nixpkgs-review` didn't pass the inbuilt tests with that set, due to the gosqlite3 (I think?) package dependency requiring it.

**Review by uri-canva — CHANGES_REQUESTED** [review]
`CGO_ENABLED`

**Comment by spacekitteh** [comment]
>If it's required for the tests, we can set it only for the build, and leave it unset for the check.

How?

**Comment by 06kellyjac** [comment]
preCheck export CGO_ENABLE=1 or skip the related tests

**Review by uri-canva — APPROVED** [review]

**Comment by spacekitteh** [comment]
Yep, fixed. Is there any way to get it other than to build it and wait for the error?

**Comment by spacekitteh** [comment]
ofberg internal error? O.o

**Comment by 06kellyjac** [comment]
For future reference, this shouldn't have been merged with 3 commits as it's against the commit conventions outlined in CONTRIBUTING.md

https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions

They should have been squashed into the original and become `opentelemetry-collector-contrib: 0.78.0 -> 0.87.0`

**Pull request merged**
