### PR TITLE
pulumi: 1.12.0 -> 2.1.0

### PR DESCRIPTION
**Pull request by MarcoPolo**
###### Motivation for this change
Update pulumi to latest version. Was lagging behind

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @jlesquembre

I updated the plugins, but I'm not sure how they are used. Doesn't pulumi fetch the resources when you need them from a predefined template?

### CODE REVIEW

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 86815` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
<br>- pulumi-bin
</details>

**Comment by ludovicc** [comment]
Version 2.2.1 of Pulumi is already out

**Comment by mudrii** [comment]
Pull request raised for 2.2.1 https://github.com/NixOS/nixpkgs/pull/88013

**Comment by veprbl** [comment]
@GrahamcOfBorg build pulumi-bin

**Pull request merged**
