### PR TITLE
cc-wrapper, bintools-wrapper: simply symlink man and info outputs 

### PR DESCRIPTION
**Pull request by oxij**
###### Motivation for this change

See commit messages. See discussion in #43547.

###### Things done

- [X] It evaluates.
- [X] It worked before these changes were reverted.
- [X] It still works.

### CODE REVIEW

**Comment by Ericson2314** [comment]
Can we do the first commit for `master` and `release-18.09`? I think no one disagrees with that.

**Comment by oxij** [comment]
Well, ok, the first patch is split into #46119 and this is now rebased on top of that.

**Comment by oxij** [comment]
@FRidh sorry for the code owner noise today.

**Comment by oxij** [comment]
Ah, #46119 is a mass-rebuild too. I reset this back to the original.

**Comment by Ericson2314** [comment]
Hmm. Know why it is a mass rebuild?

**Comment by oxij** [comment]
Intermediate stages didn't propagateDoc before, now they do. Since symlinking outputs costs nothing (actual nothing, nix will just refer to the original outPath if you produce a symlink as an output) it makes no difference, and this way stdenv bootstrapping logic becomes a bit simpler.

**Comment by oxij** [comment]
Though, I guess, nothing really prevents me from removing that part from #46119 (and from here). Pushed an edited version there, should not cause a mass rebuild anymore. Will update this later.

**Comment by oxij** [comment]
Pinned the old values of `propagateDoc` in #46119 and rebased this on top again.

The strangeness of the reverted state became apparent.

**Comment by oxij** [comment]
Anyway, I put the split version (lets call it "demo", of which #46119 is a piece) into `stdenv/bintools-cc-symlink-split` branch.

Note that those pinned `propagateDoc` mean that wrappers on master currently produce a bunch of empty outputs.

Hence, I think, there's no real point reverting those reverts in pieces, let's merge in a single hunk and bite the mass rebuild bullet.

I reset this branch back to the original version and simplified it a tiny bit more.

**Comment by oxij** [comment]
The explanation of the whole issue: https://github.com/NixOS/nixpkgs/pull/46119#issuecomment-419091869.

**Comment by FRidh** [comment]
The commits themselves lack motivation.

**Comment by oxij** [comment]
Fair enough, copy-pasted everything related from issue comments into commit messages.

**Review by 7c6f434c — APPROVED** [review]
I am not sure about the current nomenclature; shouldn't this target `staging`?

**Comment by 7c6f434c** [comment]
Thank you.

**Comment by oxij** [comment]
Yay! Thanks! I really hope this won't get reverted...

**Pull request merged**
