### PR TITLE
nixpkgs-21.05-darwin upgrade python 3.9.4 -> 3.9.6

### PR DESCRIPTION
**Pull request by yaitskov**

### CODE REVIEW

**Review by mweinelt — CHANGES_REQUESTED** [review]
Thanks for your interest.

This is not how upgrades to the stable branch are working. Multiple issues:

- Please don't delete the PR template and give a motivation
- Updates/Backports need to be cherry-picked from master
- The reason for the backport needs to be explained
- Backports to the stable branch would need to go into `release-21.05`

See https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#criteria-for-backporting-changes.

I don't think there is currently a precedent for upgrading cpython in a stable release cycle. But it is worth a discussion if we should. And if we do we should upgrade all python versions, not just python39.

CC @jonringer @FRidh

**Comment by yaitskov** [comment]
@mweinelt, python update is needed, because jupyter is not working with current version on MacOS BigSur and you cannot change python as an "application developer" though overrides, because you end up with duplicated package error.

Python 3.10 is not supported by jupyter or its dependencies yet, so current state is pretty bad for python.

**Comment by yaitskov** [comment]
I am not a nix expert, but it might be a problem with binary cache.
It seems to me that 3.9.4 just need to be rebuild for MacOS from scratch, but it is loaded from cache.
`nix-shell --check` is not working on MacOS so it is hard to prove my assumption.

**Comment by mweinelt** [comment]
Superseded by https://github.com/NixOS/nixpkgs/pull/133252.

**Pull request closed without merging**
