### PR TITLE
fortran tight-binding ecosystem: enable static/dynamic builds depending on hostPlatform

### PR DESCRIPTION
**Pull request by sheepforce**
## Description of changes

For some reasons the packages of Fortran's ecosystem for tight-binding calculations and computational chemistry default to always static linking, irrespective of the host platform. This PR enables dynamic builds on `!stdenv.hostPlatform.isStatic` platforms.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by markuskowa** [comment]
@GrahamcOfBorg build pkgsStatic.dftd4 pkgsStatic.tblite

**Review by markuskowa — COMMENTED** [review]
Maybe not fully on topic for this PR: you could also consider to convert the packages to split output. This would save some space in the run time closure (and make caching more efficient).
e.g. add `outputs = [ "out" "dev" ];`

**Comment by sheepforce** [comment]
Alright, split output has been added to all packages :)

**Comment by markuskowa** [comment]
Unfortunately the pkg-config files are now broken (double include paths, /nix/store/...//nix/store).
Either you revert back to single output or patch all pkg-config template files (e.g. https://github.com/NixOS/nixpkgs/pull/259737/files)

**Comment by sheepforce** [comment]
pkg-config files should be fixed now.

**Comment by markuskowa** [comment]
Unfortunately not:
```
Broken paths found in a .pc file! /nix/store/7x4n3mawqzv9jrc41dql4mf9ax7l2bsq-tblite-0.3.0-dev/lib/pkgconfig/tblite.pc
The following lines have issues (specifically '//' in paths).
2:libdir=${prefix}//nix/store/328ws9xcli0hyn76074h699yfchz26gq-tblite-0.3.0/lib
```

**Comment by sheepforce** [comment]
Argh, overlooked tblite. :grimacing:   But now ...

**Pull request merged**
