### PR TITLE
treewide: Remove fetchurl of SourceForge snapshots

### PR DESCRIPTION
**Pull request by endgame**
###### Description of changes

I have a machine which builds everything without substituters, to test that `nixpkgs` actually works. I discovered that `sox` failed to build because snapshots from https://sourceforge.net/code-snapshots are generated by interaction with the web UI and they go away after a while. This PR changes every `fetchzip` against `https://sourceforge.net/code-snapshots/...` to fetch from the upstream source repo. I have confirmed that the source hashes did not change.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
- [X] Confirmed that source hashes did not change.

### CODE REVIEW

**Comment by endgame** [comment]
These are niche packages and the hash of their source did not change. Can someone explain OfBorg's high rebuild counts to me?

**Comment by endgame** [comment]
This is a dupe of #240766 and someone else fixed `enblend-enfuse`, so I'll close this PR.

**Comment by doronbehar** [comment]
What a coincidence!

**Comment by emilylange** [comment]
> These are niche packages and the hash of their source did not change. Can someone explain OfBorg's high rebuild counts to me?

@endgame, since you asked:
While the hash did not change, the store path did.
`fetchzip`: `/nix/store/06d2xkrl3h1pbyg3m1whz1mvhafqgsqq-source`
`fetchgit`: `/nix/store/82jj7c66cwwp6pf6vi4p97j9isl7a2mq-code-42b3557`

Which is what changes the build graph and thus triggers the rebuild of `sox`.
And a lot of packages directly or indirectly depend on that, thus resulting in a huge amount of rebuilds.

This can be prevented by making this a no-op, by telling `fetchgit` to use `source` instead of `code-42b3557` in the store path.
See https://github.com/NixOS/nixpkgs/pull/240766#discussion_r1248976876 and the follow-up #241106 :)

Thank you for your contribution nonetheless!

**Comment by endgame** [comment]
@emilylange Thank you for the explanation.

**Pull request closed without merging**
