### PR TITLE
shufflecake: 0.4.4 -> 0.5.1

### PR DESCRIPTION
**Pull request by oluceps**
## Description of changes
https://codeberg.org/shufflecake/shufflecake-c/pulls/99

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by oluceps** [comment]
Result of `nixpkgs-review pr 343906` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>18 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.linux_5_10.shufflecake</li>
    <li>linuxKernel.packages.linux_5_10.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_5_10_hardened.shufflecake</li>
    <li>linuxKernel.packages.linux_5_10_hardened.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_5_15.shufflecake</li>
    <li>linuxKernel.packages.linux_5_15.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_5_15_hardened.shufflecake</li>
    <li>linuxKernel.packages.linux_5_15_hardened.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_5_4.shufflecake</li>
    <li>linuxKernel.packages.linux_5_4.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_5_4_hardened.shufflecake</li>
    <li>linuxKernel.packages.linux_5_4_hardened.shufflecake.bin</li>
    <li>linuxPackages_5_10_hardened.shufflecake</li>
    <li>linuxPackages_5_10_hardened.shufflecake.bin</li>
    <li>linuxPackages_5_15_hardened.shufflecake</li>
    <li>linuxPackages_5_15_hardened.shufflecake.bin</li>
    <li>linuxPackages_5_4_hardened.shufflecake</li>
    <li>linuxPackages_5_4_hardened.shufflecake.bin</li>
  </ul>
</details>
<details>
  <summary>24 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_6_1.shufflecake</li>
    <li>linuxKernel.packages.linux_6_1.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_6_10.shufflecake</li>
    <li>linuxKernel.packages.linux_6_10.shufflecake.bin</li>
    <li>linuxPackages_latest.shufflecake (linuxKernel.packages.linux_6_11.shufflecake)</li>
    <li>linuxPackages_latest.shufflecake.bin (linuxKernel.packages.linux_6_11.shufflecake.bin)</li>
    <li>linuxPackages_6_1_hardened.shufflecake (linuxKernel.packages.linux_6_1_hardened.shufflecake)</li>
    <li>linuxPackages_6_1_hardened.shufflecake.bin (linuxKernel.packages.linux_6_1_hardened.shufflecake.bin)</li>
    <li>linuxPackages.shufflecake (linuxKernel.packages.linux_6_6.shufflecake)</li>
    <li>linuxPackages.shufflecake.bin (linuxKernel.packages.linux_6_6.shufflecake.bin)</li>
    <li>linuxPackages_hardened.shufflecake (linuxPackages_6_6_hardened.shufflecake)</li>
    <li>linuxPackages_hardened.shufflecake.bin (linuxPackages_6_6_hardened.shufflecake.bin)</li>
    <li>linuxPackages_latest-libre.shufflecake (linuxKernel.packages.linux_latest_libre.shufflecake)</li>
    <li>linuxPackages_latest-libre.shufflecake.bin (linuxKernel.packages.linux_latest_libre.shufflecake.bin)</li>
    <li>linuxPackages-libre.shufflecake (linuxKernel.packages.linux_libre.shufflecake)</li>
    <li>linuxPackages-libre.shufflecake.bin (linuxKernel.packages.linux_libre.shufflecake.bin)</li>
    <li>linuxPackages_lqx.shufflecake (linuxKernel.packages.linux_lqx.shufflecake)</li>
    <li>linuxPackages_lqx.shufflecake.bin (linuxKernel.packages.linux_lqx.shufflecake.bin)</li>
    <li>linuxPackages_xanmod.shufflecake (linuxKernel.packages.linux_xanmod.shufflecake)</li>
    <li>linuxPackages_xanmod.shufflecake.bin (linuxKernel.packages.linux_xanmod.shufflecake.bin)</li>
    <li>linuxPackages_xanmod_latest.shufflecake (linuxKernel.packages.linux_xanmod_latest.shufflecake ,linuxPackages_xanmod_stable.shufflecake)</li>
    <li>linuxPackages_xanmod_latest.shufflecake.bin (linuxKernel.packages.linux_xanmod_latest.shufflecake.bin ,linuxPackages_xanmod_stable.shufflecake.bin)</li>
    <li>linuxPackages_zen.shufflecake (linuxKernel.packages.linux_zen.shufflecake)</li>
    <li>linuxPackages_zen.shufflecake.bin (linuxKernel.packages.linux_zen.shufflecake.bin)</li>
  </ul>
</details>

**Review by FliegendeWurst — APPROVED** [review]

**Comment by blitz** [comment]
@oluceps Do you want to bump this to 0.5.1? This was released in October.

**Review by blitz — APPROVED** [review]

**Comment by oluceps** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 343906`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 12 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.linux_5_10.shufflecake</li>
    <li>linuxKernel.packages.linux_5_10.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_5_10_hardened.shufflecake</li>
    <li>linuxKernel.packages.linux_5_10_hardened.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_5_15.shufflecake</li>
    <li>linuxKernel.packages.linux_5_15.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_5_15_hardened.shufflecake</li>
    <li>linuxKernel.packages.linux_5_15_hardened.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_5_4.shufflecake</li>
    <li>linuxKernel.packages.linux_5_4.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_5_4_hardened.shufflecake</li>
    <li>linuxKernel.packages.linux_5_4_hardened.shufflecake.bin</li>
  </ul>
</details>
<details>
  <summary>:x: 2 packages failed to build:</summary>
  <ul>
    <li>linuxKernel.packages.linux_lqx.shufflecake</li>
    <li>linuxKernel.packages.linux_lqx.shufflecake.bin</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 24 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_6_1.shufflecake</li>
    <li>linuxKernel.packages.linux_6_1.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_6_11.shufflecake</li>
    <li>linuxKernel.packages.linux_6_11.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_6_11_hardened.shufflecake</li>
    <li>linuxKernel.packages.linux_6_11_hardened.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_6_12.shufflecake</li>
    <li>linuxKernel.packages.linux_6_12.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_6_1_hardened.shufflecake</li>
    <li>linuxKernel.packages.linux_6_1_hardened.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_6_6.shufflecake</li>
    <li>linuxKernel.packages.linux_6_6.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_hardened.shufflecake (linuxKernel.packages.linux_6_6_hardened.shufflecake)</li>
    <li>linuxKernel.packages.linux_hardened.shufflecake.bin (linuxKernel.packages.linux_6_6_hardened.shufflecake.bin)</li>
    <li>linuxKernel.packages.linux_latest_libre.shufflecake</li>
    <li>linuxKernel.packages.linux_latest_libre.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_libre.shufflecake</li>
    <li>linuxKernel.packages.linux_libre.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_xanmod.shufflecake</li>
    <li>linuxKernel.packages.linux_xanmod.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_xanmod_latest.shufflecake (linuxKernel.packages.linux_xanmod_stable.shufflecake)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.shufflecake.bin (linuxKernel.packages.linux_xanmod_stable.shufflecake.bin)</li>
    <li>linuxKernel.packages.linux_zen.shufflecake</li>
    <li>linuxKernel.packages.linux_zen.shufflecake.bin</li>
  </ul>
</details>

**Comment by oluceps** [comment]
```
GOT: 
GOT: #
GOT: # configuration written to .config
GOT: #
GOT: make[1]: Leaving directory '/build/source/build'
GOT: make: Leaving directory '/build/source'
warning: unused option: NUMA_BALANCING
warning: unused option: POWER_RESET_GPIO
warning: unused option: POWER_RESET_GPIO_RESTART
warning: unused option: PSI
warning: unused option: RCU_BOOST_DELAY
warning: unused option: SCHED_AUTOGROUP
error: unused option: SCHED_CLASS_EXT
warning: unused option: SCHED_CORE
warning: unused option: UCLAMP_TASK_GROUP
```

**Comment by oluceps** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 343906`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 14 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.linux_5_10.shufflecake</li>
    <li>linuxKernel.packages.linux_5_10.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_5_10_hardened.shufflecake</li>
    <li>linuxKernel.packages.linux_5_10_hardened.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_5_15.shufflecake</li>
    <li>linuxKernel.packages.linux_5_15.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_5_15_hardened.shufflecake</li>
    <li>linuxKernel.packages.linux_5_15_hardened.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_5_4.shufflecake</li>
    <li>linuxKernel.packages.linux_5_4.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_5_4_hardened.shufflecake</li>
    <li>linuxKernel.packages.linux_5_4_hardened.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_lqx.shufflecake</li>
    <li>linuxKernel.packages.linux_lqx.shufflecake.bin</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 24 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_6_1.shufflecake</li>
    <li>linuxKernel.packages.linux_6_1.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_6_11.shufflecake</li>
    <li>linuxKernel.packages.linux_6_11.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_6_11_hardened.shufflecake</li>
    <li>linuxKernel.packages.linux_6_11_hardened.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_6_12.shufflecake</li>
    <li>linuxKernel.packages.linux_6_12.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_6_1_hardened.shufflecake</li>
    <li>linuxKernel.packages.linux_6_1_hardened.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_6_6.shufflecake</li>
    <li>linuxKernel.packages.linux_6_6.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_hardened.shufflecake (linuxKernel.packages.linux_6_6_hardened.shufflecake)</li>
    <li>linuxKernel.packages.linux_hardened.shufflecake.bin (linuxKernel.packages.linux_6_6_hardened.shufflecake.bin)</li>
    <li>linuxKernel.packages.linux_latest_libre.shufflecake</li>
    <li>linuxKernel.packages.linux_latest_libre.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_libre.shufflecake</li>
    <li>linuxKernel.packages.linux_libre.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_xanmod.shufflecake</li>
    <li>linuxKernel.packages.linux_xanmod.shufflecake.bin</li>
    <li>linuxKernel.packages.linux_xanmod_latest.shufflecake (linuxKernel.packages.linux_xanmod_stable.shufflecake)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.shufflecake.bin (linuxKernel.packages.linux_xanmod_stable.shufflecake.bin)</li>
    <li>linuxKernel.packages.linux_zen.shufflecake</li>
    <li>linuxKernel.packages.linux_zen.shufflecake.bin</li>
  </ul>
</details>

**Review by blitz — APPROVED** [review]

**Comment by FliegendeWurst** [comment]
@ofborg build linuxPackages.shufflecake

(for aarch64)

**Pull request merged**
