### PR TITLE
gitRepo: Add import to ssl module to avoid runtime error

### PR DESCRIPTION
**Pull request by otavio**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by wizeman — APPROVED** [review]

**Comment by wizeman** [comment]
I'm now running into this issue:

```
Downloading Repo source from https://gerrit.googlesource.com/git-repo
repo: Updating release signing keys to keyset ver 2.3
Downloading manifest from https://github.com/GPUOpen-Drivers/AMDVLK.git
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 17 (delta 3), reused 9 (delta 0), pack-reused 0

repo has been initialized in /nix/store/q6l15n954w49z8dpvc48cia9fim6n3xm-amdvlk-src
Traceback (most recent call last):
  File "/nix/store/q6l15n954w49z8dpvc48cia9fim6n3xm-amdvlk-src/.repo/repo/main.py", line 627, in <module>
    _Main(sys.argv[1:])
  File "/nix/store/q6l15n954w49z8dpvc48cia9fim6n3xm-amdvlk-src/.repo/repo/main.py", line 603, in _Main
    result = run()
  File "/nix/store/q6l15n954w49z8dpvc48cia9fim6n3xm-amdvlk-src/.repo/repo/main.py", line 596, in <lambda>
    run = lambda: repo._Run(name, gopts, argv) or 0
  File "/nix/store/q6l15n954w49z8dpvc48cia9fim6n3xm-amdvlk-src/.repo/repo/main.py", line 262, in _Run
    result = cmd.Execute(copts, cargs)
  File "/nix/store/q6l15n954w49z8dpvc48cia9fim6n3xm-amdvlk-src/.repo/repo/subcmds/sync.py", line 1008, in Execute
    ssh_proxy.sock()
  File "/nix/store/q6l15n954w49z8dpvc48cia9fim6n3xm-amdvlk-src/.repo/repo/ssh.py", line 270, in sock
    if version() < (6, 7):
  File "/nix/store/q6l15n954w49z8dpvc48cia9fim6n3xm-amdvlk-src/.repo/repo/ssh.py", line 54, in version
    return _parse_ssh_version()
  File "/nix/store/q6l15n954w49z8dpvc48cia9fim6n3xm-amdvlk-src/.repo/repo/ssh.py", line 42, in _parse_ssh_version
    ver_str = _run_ssh_version()
  File "/nix/store/q6l15n954w49z8dpvc48cia9fim6n3xm-amdvlk-src/.repo/repo/ssh.py", line 36, in _run_ssh_version
    return subprocess.check_output(['ssh', '-V'], stderr=subprocess.STDOUT).decode()
  File "/nix/store/n8fzm8kyvxkczma71sir15v9n2jas39w-python3-3.8.9/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/nix/store/n8fzm8kyvxkczma71sir15v9n2jas39w-python3-3.8.9/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/nix/store/n8fzm8kyvxkczma71sir15v9n2jas39w-python3-3.8.9/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/n8fzm8kyvxkczma71sir15v9n2jas39w-python3-3.8.9/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ssh'
builder for '/nix/store/0zp7r9v8y173rh40s6zgvzlqi6d5nvg7-amdvlk-src.drv' failed with exit code 1
```

Any ideas?

**Comment by wizeman** [comment]
Ok, it seems I've fixed (or at least worked around) the issue in my previous comment with this commit: https://github.com/wizeman/nixpkgs/commit/e0db4913f67d4a5b19cce795780f77b4e5b428c5

**Comment by otavio** [comment]
@wizeman I added your commit here but it seems like it is fixing the issue at wrong place no? Shouldn't it to be included on the gitRepo wrapper?

**Comment by wizeman** [comment]
@otavio You are totally correct. I've fixed it in commit https://github.com/wizeman/nixpkgs/commit/90dfe330d4a6ef4c46fc64fb4cc31c1566f05126 and verified it to work correctly. Thanks!

**Comment by otavio** [comment]
@wizeman, thx for the team work 👍🏼 I think it is good to go now.

**Review by wizeman — APPROVED** [review]
Looks good to me. Thanks!

**Comment by SuperSandro2000** [comment]
Does this need a backport?

**Comment by wizeman** [comment]
@SuperSandro2000 Yes, to 21.05 at least.

**Comment by wizeman** [comment]
Backport PR is at #125528.

**Pull request merged**
