### PR TITLE
Kubernetes : upgrade to 1.3 and various adaptations

### PR DESCRIPTION
**Pull request by mikefaille**
- As Kubernetes 1.3.6 DNS is a built-in service
- Use go 1.7

### CODE REVIEW

**Comment by groxxda** [comment]
I think the comment about dns should be commitmsg because without the removed lines it's not clear why it is even there :wink:

**Comment by offlinehacker** [comment]
Thanks for pull request, but it does not update nixos module which we have. It's true that this module was broken with previous update to kubernetes, but i have more complete pull request basically ready, so sorry i will not accept this pull request. I will make a pull request with nixos module and you can test it later.

**Comment by mikefaille** [comment]
@offlinehacker @groxxda  Wow, you are fast !

I just update my DNS commit. And, I accept my refused pull request for more complete one. ;-)

**Comment by offlinehacker** [comment]
@mikefaille it will be ready in max two weeks, since we need kubernetes updated in our company from 1.0 version :)

**Comment by mikefaille** [comment]
@offlinehacker  Allright ! Actually, I must use Kubernetes 1.3 for my own skillz. I'll use my package until you complete official one.

**Comment by bachp** [comment]
@offlinehacker Any update on you PR? I'm looking forward to see the new kubernetes in NixOS 😉

**Comment by mikefaille** [comment]
I could help if needed. It will be a pleasure.

**Comment by offlinehacker** [comment]
Here's WIP pull request, if someone would help me with testing it, or
writing more complete nixos tests it would be nice :)
https://github.com/NixOS/nixpkgs/pull/19023

**Pull request closed without merging**
