### PR TITLE
linux_4_9: remove

### LINKED ISSUE #199933: Remove Linux 4.9
The Linux 4.9 LTS release will be EOL after 2023/01 and I hope we can remove it before the 22.11 release, so we don't carry it around until then.

via https://endoflife.date/linux

cc kernel maintainer team

@TredwellGit @Ma27 @NeQuissimus @alyssais

### PR DESCRIPTION
**Pull request by Ma27**
###### Description of changes

Closes #199933.
Also remove tombstone-attributes for dropped Linux kernels from before 22.05.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Atemu — APPROVED** [review]

**Comment by ajs124** [comment]
Assuming we don't support out of tree users of random unsupported kernel versions, we can drop everything up to 4.14, e.g. https://github.com/NixOS/nixpkgs/blob/636051e353461f073ac55d5d42c1ed062a345046/pkgs/os-specific/linux/kernel/common-config.nix#L56

**Comment by Ma27** [comment]
@dasj @mweinelt wdyt regarding the kernel config thing?

**Comment by mweinelt** [comment]
We can drop them after the branch-off if we are worried about downstream usage. I think that would be a reasonable trade-off.

**Comment by Atemu** [comment]
If it's going to be EOL soon and we won't have it in the stable release, I don't see why we should carry it in unstable.

These older kernels are around in case someone needs them for some fringe use-case and because their maintenance burden for us is basically 0. We don't *need* to keep them.  

We could drop everything except the latest release and maybe the latest LTS kernel and it'd be a perfectly acceptable thing to do for a distro. Fedora and Arch do that respectively. It's just more likely that we break someone's fringe use-case by removing more recent kernels which is why I don't like that idea but we totally could.

I like the simplicity of keeping the same set of kernels in all maintained releases.

**Comment by mweinelt** [comment]
The idea is to remove kernel 4.9 now for unstable and the upcoming release, but keep the config bits around until after the branch-off, so if someone uses a downstream kernel that requires these options they can use that throughout 22.05, but we can get rid of them and get peace of mind in ~10 days.

**Review by trofi — APPROVED** [review]

**Review by lovesegfault — APPROVED** [review]

**Pull request merged**
