### PR TITLE
google-cloud-sdk: 404.0.0 -> 405.0.0

### PR DESCRIPTION
**Pull request by iAmMrinal0**
###### Description of changes

Package update: [Changelog v405.0.0](https://cloud.google.com/sdk/docs/release-notes#40500_2022-10-04)

@pborzenkov would appreciate a check to see if `gcloud sql connect` works as expected as a patch was added in #114488. Running the command works, however, I'm not sure if there's more that's required. The SDK has code to check the path and from what I can see the patch is no more required. relevant code from the SDK:

```python
def _GetCloudSqlProxyPath():
  """Determines the path to the cloud_sql_proxy binary."""
  sdk_bin_path = config.Paths().sdk_bin_path

  if sdk_bin_path:
    # Validate if the cloud_sql_proxy binary present in Cloud SDK bin repository
    # and it has access for invoking user,
    # otherwise look for it in PATH
    cloud_sql_proxy_path = os.path.join(sdk_bin_path, 'cloud_sql_proxy')
    if _IsCloudSqlProxyPresentInSdkBin(cloud_sql_proxy_path):
      return cloud_sql_proxy_path

  # Check if cloud_sql_proxy is located on the PATH.
  proxy_path = file_utils.FindExecutableOnPath('cloud_sql_proxy')
  if proxy_path:
    log.debug('Using cloud_sql_proxy found at [{path}]'.format(path=proxy_path))
    return proxy_path
  else:
    raise sql_exceptions.SqlProxyNotFound(
        'A Cloud SQL Proxy SDK root could not be found, or access is denied.'
        'Please check your installation.')

```

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by pborzenkov** [comment]
@iAmMrinal0 Sorry, I no longer have access to a CloudSQL instance, so can't check if the new version works or not.

**Comment by iAmMrinal0** [comment]
No problem. I am assuming that if this worked then it should be fine:
image

**Comment by pborzenkov** [comment]
@iAmMrinal0 It might not. `cloud_sql_proxy` is started by this command in order to connect to an instance. If you don't provide the instance name it won't even attempt to start it.

**Comment by iAmMrinal0** [comment]
@pborzenkov spun up a test instance to verify. it seems to work

```
$ results/google-cloud-sdk/bin/gcloud sql connect test-google-cloud-sdk
Allowlisting your IP for incoming connection for 5 minutes...done.
Connecting to database with SQL user [postgres].Password:
psql (12.12 (Ubuntu 12.12-0ubuntu0.20.04.1), server 14.4)
WARNING: psql major version 12, server major version 14.
         Some psql features might not work.
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.
```

**Pull request merged**
