### PR TITLE
docopts: 0.6.3 -> 0.6.4

### PR DESCRIPTION
**Pull request by endorama**
###### Motivation for this change

Version 0.6.3 was affected by a bug (https://github.com/docopt/docopts/issues/47) that has been resolved in 0.6.4.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
Please target `master` first then backport to `release-21.05`.

**Comment by endorama** [comment]
Sorry everyone for the noise this created. I tried changing the base branch to `master` as asked in the comment but seems something went wrong (I got a 500 error).
Working on rebasing this.

**Comment by endorama** [comment]
Closing this as I'm not sure what is going on.

@bobby285271 I'm very sorry for the mess :( 

I'll open a different PR targeting `master` as requested.

**Comment by bobby285271** [comment]
As mentioned in [GitHub docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#about-code-owners):

> Code owners are automatically requested for review when someone opens a pull request that modifies code that they own. Code owners are not automatically requested to review draft pull requests.

Though I haven't opened a PR that targeted a wrong branch myself, I guess it will be a good idea to draft and maybe close the PR before changing the target branch. Also the `release-*` branch may contain commits that are not in `master` so you will need to do some rebases and force pushes when changing the target branch.

**Pull request closed without merging**
