### PR TITLE
pythonPackages.av: init at 0.2.4

### PR DESCRIPTION
**Pull request by mkovaxx**
Tested on NixOS.

### CODE REVIEW

**Comment by joachifm** [comment]
By tested, do you mean built or have you also used the library?

**Comment by mkovacs** [comment]
I mean built, then ran the tests. The only failures were due to missing test assets, so I temporarily turned off the tests in the Nix package, and filed https://github.com/mikeboers/PyAV/issues/152.

**Comment by mkovacs** [comment]
Why does the dependency `python3.5-Pillow-2.9.0` fail to build on TravisCI?

**Comment by joachifm** [comment]
```
_imagingcms.c:29:19: fatal error: lcms2.h: No such file or directory
 #include "lcms2.h"
                   ^
compilation terminated.
Building using 2 processes
```

**Comment by mkovacs** [comment]
Do you think that's an issue with `pythonPackages.pillow`, or a configuration problem?

**Comment by joachifm** [comment]
I'm stumped. Everything builds fine for me. Anyway, I doubt that your PR is to blame for any breakage in its dependencies.

I do think you need to move `buildInputs` that are not strictly build-time dependencies into `propagatedBuildInputs`, otherwise packages that pull in python-av will fail with run-time import errors. Besides that, I think this can be merged, regardless of travis.

**Comment by FRidh** [comment]
if the package builds and can be imported with any supported Python version, then it is fine.

**Comment by lethalman** [comment]
Built locally, thanks.

**Pull request merged**
