### PR TITLE
llvm_39: fix on darwin

### PR DESCRIPTION
**Pull request by acowley**
###### Motivation for this change

Build and use `llvm_39` on darwin.
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [x] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by copumpkin** [comment]
Thanks! Curious if you know why it needs libxpc. Just thinking forward to if we wanted to use this for a stdenv bootstrap since using unfree stuff like `libxpc` in the stdenv makes things a lot messier.

**Comment by acowley** [comment]
@copumpkin I didn't realize it was significant so did write a note about it, but without it there is a build failure when something tries to include `xpc.h`. I think the failure is towards the start of the build, so removing that input and building should reveal the problem within about 5-10 minutes.

**Comment by copumpkin** [comment]
Ah, was just wondering what `llvm` actually did with it. I'll poke around later to try to understand why they need it.

**Comment by copumpkin** [comment]
Aha, https://github.com/llvm-mirror/compiler-rt/search?utf8=%E2%9C%93&q=xpc

**Comment by copumpkin** [comment]
So it seems like it's all part of the TSAN stuff, which doesn't seem essential or needed for bootstrap. So when/if we get to 3.9, I might make that optional and not use it during bootstrap.

**Comment by acowley** [comment]
Thanks for tracking it down! Disabling during bootstrap makes sense.

**Pull request merged**
