### PR TITLE
qutebrowser: use upstream make install

### PR DESCRIPTION
**Pull request by nrdxp**
###### Description of changes

Use the upsteam Makefile to avoid reinventing the install logic.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by magnetophon** [comment]
This doesn't buid for me, I get:
```
nixpkgs-review pr 195744
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/195744/head:refs/nixpkgs-review/1
remote: Enumerating objects: 24944, done.
remote: Counting objects: 100% (9608/9608), done.
remote: Compressing objects: 100% (381/381), done.
remote: Total 24944 (delta 9373), reused 9364 (delta 9198), pack-reused 15336
Receiving objects: 100% (24944/24944), 20.20 MiB | 8.78 MiB/s, done.
Resolving deltas: 100% (17750/17750), completed with 2510 local objects.
From https://github.com/NixOS/nixpkgs
   f71b215225d..652d76837ac  master                -> refs/nixpkgs-review/0
 + 7f85186f617...23ecb722e4b refs/pull/195744/head -> refs/nixpkgs-review/1  (forced update)
$ git worktree add /home/bart/.cache/nixpkgs-review/pr-195744/nixpkgs 652d76837acff4bb2951fbe2bdfae4bc86075f8a
Preparing worktree (detached HEAD 652d76837ac)
Updating files: 100% (32265/32265), done.
HEAD is now at 652d76837ac Merge pull request #195776 from bobby285271/pantheon-patch-update
$ git merge --no-commit --no-ff 23ecb722e4bd8cd67db5452b9b379f1dc254debc
Automatic merge went well; stopped before committing as requested
$ nix --experimental-features nix-command build --no-link --keep-going --option build-use-sandbox relaxed -f /home/bart/.cache/nixpkgs-review/pr-195744/build.nix
error: builder for '/nix/store/n1cg9zx2acv6w784xfd4jik8yx8qm77b-review-shell.drv' failed with exit code 1;
       last 3 log lines:
       > Error: detected mismatched Qt dependencies:
       >     /nix/store/rzh41hv0w6vglydmx36ad22kqdd6fska-qtbase-6.4.0-dev
       >     /nix/store/nlviw38mbi7hjwgxxs0nv844qpak78b1-qtbase-5.15.6-dev
       For full logs, run 'nix log /nix/store/n1cg9zx2acv6w784xfd4jik8yx8qm77b-review-shell.drv'.

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/195744

2 packages built:
qutebrowser qutebrowser-qt6

$ /nix/store/27fmjjffj4qi2rs2kamizq51qj44s5fb-nix-2.11.0/bin/nix-shell /home/bart/.cache/nixpkgs-review/pr-195744/shell.nix
Error: detected mismatched Qt dependencies:
    /nix/store/rzh41hv0w6vglydmx36ad22kqdd6fska-qtbase-6.4.0-dev
    /nix/store/nlviw38mbi7hjwgxxs0nv844qpak78b1-qtbase-5.15.6-dev
$ git worktree prune
```

**Comment by nrdxp** [comment]
> This doesn't buid for me

strange, I have no such eval error. I can build 2.5.2 with qt5 just fine, as far as the qt6 version, I don't get an eval error but I haven't had a chance to build it fully yet, since it seems webengine wants to build from scratch again even though I built it for another PR last week :facepalm:

**Comment by LunNova** [comment]
If you run then individually with nix run on the PR branch does it work? Think it's something to do with having both in the same env with the different QT versions.

**Comment by magnetophon** [comment]
> If you run them individually with nix run on the PR branch does it work?

How do I do that?

**Comment by nrdxp** [comment]
Result of `nixpkgs-review pr 195744` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>qutebrowser</li>
    <li>qutebrowser-qt6</li>
  </ul>
</details>

**Comment by nrdxp** [comment]
> If you run them individually with nix run on the PR branch does it work?

They both build and run fine.

**Comment by nrdxp** [comment]
@dotlambda or @rnhmjoj any comment on here? I don't really see a downside to this, and it should make the package easier to maintain going forward. I understand the qt6 version makes things kinda messy, but ideally the qt6 work will soon be a part of an official release and we can remove it soon, and then we'll have a much simpler package to deal with.

**Comment by rnhmjoj** [comment]
This is likely unrelated to this change (I've never tried the Qt 6 branch before) but It seems there is an issue with xkbcommon, in particular is not respecting $XKB_CONFIG_ROOT and qutebrowser hard crashes if you have set a layout with the `xserver.extraLayouts` option.

**Comment by LunNova** [comment]
Should that substitute be `/etc/X11/xkb/` instead?

**Comment by nrdxp** [comment]
> Should that substitute be `/etc/X11/xkb/` instead?

I don't have that directory on my NixOS system (I don't have any `xserver.extraLayouts` set).

**Comment by rnhmjoj** [comment]
> Should that substitute be /etc/X11/xkb/ instead?

No, it's supposed to use the $XKB_CONFIG_ROOT variable, which is set by a NixOS module. /etc/X11/xkb is not expected to exist, in general. I'm not sure why it's being ignored.

**Comment by LunNova** [comment]
In that case I'd test patching out that code that sets a custom path and removing `XKB_CONTEXT_NO_DEFAULT_INCLUDES` and seeing if it starts doing the right thing.

**Comment by nrdxp** [comment]
> In that case I'd test patching out that code that sets a custom path and removing `XKB_CONTEXT_NO_DEFAULT_INCLUDES` and seeing if it starts doing the right thing.

sounds reasonable, but also out of scope for this PR, so I think we can still merge this and try to fix this issue in a follow up.

**Comment by rnhmjoj** [comment]
I `diff`ed the output before and after this change. Besides the bunch of unreproducible .pyc, here's what I noticed:

1. The {dist,egg}-info of qutebrowserchanged somewhat: the GPL license disappeared, a SOURCES.txt and requires.txt files appeared
2. The qutebrowser wrapped now has compatibility with [easy_install](https://xkcd.com/1987/) (yay, I guess)
3. A bunch of files in /share/qutebrowser/scripts disappeared:
    - link_pyqt.py
    - setupcommon.py
    - testbrowser_webengine.py
    - testbrowser_webkit.py
  This looks like testing stuff and doesn't seem to have ever been working.

So, I don't see any practical downside.

**Review by rnhmjoj — APPROVED** [review]

**Pull request merged**
