### PR TITLE
ttyrec: 1.0.8 -> ovh-ttyrec 1.1.6.6

### PR DESCRIPTION
**Pull request by charles-dyfis-net**
###### Motivation for this change

The upstream ttyrec package has been marked broken since January 2020, as it depends on a deprecated POSIX API that Linux has never fully supported, and for which such support as did exist has been withdrawn from glibc.

This PR replaces the broken ttyrec derivation with one packaging an actively-maintained fork by @ovh.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by charles-dyfis-net** [comment]
Items where feedback is requested:

- [ ] Is it okay to take over the `ttyrec` name when switching source trees, or should this have a new top-level entry?
- [ ] Is @zimbatm okay with remaining on the maintainers list with this change?

**Comment by SuperSandro2000** [comment]
> * [ ]  Is it okay to take over the `ttyrec` name when switching source trees, or should this have a new top-level entry?

The old one had its last release 14 years ago and if it is a drop in replacement I think it is finish.

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 108182` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ttyrec</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review. If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108182` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>ttyrec</li>
</ul>
</details>

**Review by lukegb — APPROVED** [review]

**Comment by zimbatm** [comment]
Since the pname has changed, can you please update all-packages.nix to rename the attibute as well? Update ttyrec to ovh-ttyrec and then add an alias back from ttyrec to ovh-ttyrec in pkgs/top-level/aliases.nix

Ideally we want pname and attribute names to match, to simplify reverse-lookup from a store path to attribute. ttyrec can then be kept as

**Comment by charles-dyfis-net** [comment]
@zimbatm -- I've updated this to also have the directory name match the pname. LGTY, or have I overstepped?

**Comment by charles-dyfis-net** [comment]
(Argh, missed the `top-level/aliases.nix` specification; apologies, going back and modifying that...)

**Comment by charles-dyfis-net** [comment]
@zimbatm -- updated per request; `ttyrec` is now in `pkgs/top-level/aliases.nix`, whereas `pkgs/top-level/all-packages.nix` uses the `ovh-ttyrec` name. I also updated the directory name to match.

**Review by zimbatm — APPROVED** [review]
thanks!

**Comment by zimbatm** [comment]
Result of `nixpkgs-review pr 108182` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ovh-ttyrec</li>
  </ul>
</details>

**Pull request merged**
