### PR TITLE
Mesa updates

### PR DESCRIPTION
**Pull request by eduarrrd**
Tested both. Keeping 1.5.7 to be able to revert to stable if 1.6.0 has unexpected issues.

### CODE REVIEW

**Comment by lethalman** [comment]
Can't be merged as the current version is 10.5.6. cc @vcunat @wkennington

**Comment by vcunat** [comment]
Personally, I don't think we should default to mesa versions that aren't considered stable by upstream.

**Comment by wkennington** [comment]
How is this not "stable"? None of their releases have ever been marked as
stable as far as I am aware.

**Comment by vcunat** [comment]
Mesa calls .0 versions "development release". They call the others bug-fix or something.
> People who are concerned with stability and reliability should stick with a previous release or wait for .1

**Comment by wkennington** [comment]
Ah okay

**Comment by garbas** [comment]
waiting for mesa 1.6.1 then we bump it

**Comment by vcunat** [comment]
I picked the minor bump to staging.

**Pull request closed without merging**
