### PR TITLE
nixos/tests/k3s: add multi-node test, test basic flannel networking

### PR DESCRIPTION
**Pull request by euank**
###### Description of changes

This updates the k3s tests to be in a directory (since I'm adding a second test), and then adds a 2-node test.

Most importantly, this verifies network connectivity between two pods, one running on each node, which lets us test that flannel is working correctly.

I think this gives us a nice increase in coverage for k3s, even if I'm not actually confident this would have caught the recent issue in #181790.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) -- Verified both tests work via `nix-build -A nixosTests.k3s.single-node` and `nix-build -A nixosTests.k3s.multi-node`
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by bryanasdev000 — APPROVED** [review]
Tested and diff/ofborg LGTM.

**Comment by superherointj** [comment]
Hi @euank 

Thanks for contributing an improved test.

Forgive my ignorance, I was not able to run the tests the usual way I do.

image

Unless I manually link to the specific files. (Which I did and worked.)

Any suggestion? Could it be a problem? Let me know.

**Comment by euank** [comment]
I've named the passthrough tests as just "single-node" and "multi-node", i.e.

```
$ nix-build -A k3s.passthru.tests.single-node
$ nix-build -A k3s.passthru.tests.multi-node
```

I think calling it like that should work!

Including `k3s` in the name again seems redundant for the passthrough tests, so it seems fine to me to leave it out in this little bit of restructuring.

**Comment by superherointj** [comment]
> I've named the passthrough tests as just "single-node" and "multi-node", i.e.
> 
> ```
> $ nix-build -A k3s.passthru.tests.single-node
> $ nix-build -A k3s.passthru.tests.multi-node
> ```
> I think calling it like that should work!

I did try...

image
 
But does not seem to work. I'm using flakes.

> Including `k3s` in the name again seems redundant for the passthrough tests, so it seems fine to me to leave it out in this little bit of restructuring.

Yes, it is fine leaving k3s out.

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 182445` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by superherointj** [comment]
At "nixos/tests/k3s/default.nix", by replacing `import` with `handleTest` I was able to build the test. So it is not a matter of how I'm starting the tests, but the actual code is not being interpreted the same way by our different testing method.

I've noticed that another package with many tests (./installed-tests) use a `pkgs.newScope` technique and `pkgs.recurseIntoAttrs`. I don't know which method is more correct. We could, to keep things simple, add two lines to `all-tests.nix` and keep k3s files inside `k3s` folder. Until we can better figure out this.

**Comment by bryanasdev000** [comment]
> > I've named the passthrough tests as just "single-node" and "multi-node", i.e.
> > 
> > ```
> > $ nix-build -A k3s.passthru.tests.single-node
> > $ nix-build -A k3s.passthru.tests.multi-node
> > ```
> > I think calling it like that should work!
> 
> I did try...
> 
> image
>  
> But does not seem to work. I'm using flakes.
> 
> > Including `k3s` in the name again seems redundant for the passthrough tests, so it seems fine to me to leave it out in this little bit of restructuring.
> 
> Yes, it is fine leaving k3s out.
> 
> Btw, `nb` is an alias such as `nix build .#`. Result does not change using `nix build .#` in the full form. (tested it)
> 
> @bryanasdev000 How did you test the tests here?


nix-build /path/to/test

**Comment by euank** [comment]
Thanks for catching that @superherointj!

It looks like I had an extra layer of function calls because I didn't have an `import` in `tests/k3s/default.nix`; actually `import`ing there makes the attributes be actual test derivations rather than functions that `nix build` doesn't evaluate.

I've verified with what I've got now both:

```
$ nix-build -A k3s.passthru.tests.single-node
$ nix build '.#k3s.passthru.tests.multi-node'
```

work as I'd expect.

Want to double check this works like you'd expect now?

**Review by superherointj — APPROVED** [review]
Tests run for me. Thanks!

**Pull request merged**
