### PR TITLE
python3Packages.qiling: 1.3.0 -> 1.4.0, unicorn: 1.0.3 -> 2.0.0-rc4

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 1.4.0

Change log: https://github.com/qilingframework/qiling/releases/tag/1.4.0

Fix build (https://hydra.nixos.org/build/157285293)

ZHF: #144627

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
On macos 10.15:

```
builder for '/nix/store/gf6gk53b9yjyk4s724nkg0zqsfy8ds7m-unicorn-2.0.0-rc4.drv' failed with exit code 2; last 10 log lines:
  [  0%] Building C object CMakeFiles/unicorn-common.dir/glib_compat/gslice.c.o
  [  0%] Building C object CMakeFiles/unicorn-common.dir/qemu/util/bitmap.c.o
  In file included from /tmp/nix-build-unicorn-2.0.0-rc4.drv-0/source/qemu/util/bitmap.c:12:
  /tmp/nix-build-unicorn-2.0.0-rc4.drv-0/source/qemu/include/qemu/osdep.h:30:10: fatal error: 'config-host.h' file not found
  #include "config-host.h"
           ^~~~~~~~~~~~~~~
  1 error generated.
  make[2]: *** [CMakeFiles/unicorn-common.dir/build.make:216: CMakeFiles/unicorn-common.dir/qemu/util/bitmap.c.o] Error 1
  make[1]: *** [CMakeFiles/Makefile2:699: CMakeFiles/unicorn-common.dir/all] Error 2
  make: *** [Makefile:146: all] Error 2
```

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 145273` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>30 packages built:</summary>
  <ul>
    <li>pwndbg</li>
    <li>pwntools (python39Packages.pwntools)</li>
    <li>python38Packages.angr</li>
    <li>python38Packages.angrcli</li>
    <li>python38Packages.angrop</li>
    <li>python38Packages.datasets</li>
    <li>python38Packages.manticore</li>
    <li>python38Packages.multiprocess</li>
    <li>python38Packages.pathos</li>
    <li>python38Packages.pwntools</li>
    <li>python38Packages.qiling</li>
    <li>python38Packages.sagemaker</li>
    <li>python38Packages.spacy-transformers</li>
    <li>python38Packages.tokenizers</li>
    <li>python38Packages.transformers</li>
    <li>python38Packages.unicorn</li>
    <li>python39Packages.angr</li>
    <li>python39Packages.angrcli</li>
    <li>python39Packages.angrop</li>
    <li>python39Packages.datasets</li>
    <li>python39Packages.manticore</li>
    <li>python39Packages.multiprocess</li>
    <li>python39Packages.pathos</li>
    <li>python39Packages.qiling</li>
    <li>python39Packages.sagemaker</li>
    <li>python39Packages.spacy-transformers</li>
    <li>python39Packages.tokenizers</li>
    <li>python39Packages.transformers</li>
    <li>python39Packages.unicorn</li>
    <li>unicorn (unicorn-emu)</li>
  </ul>
</details>

**Comment by risicle** [comment]
Other than this breaking darwin, I'm a bit nervous about:
 - shipping a `x.0.0-rc` version for a stable release
 - disabling tests that are broken by the new unicorn

**Comment by tomberek** [comment]
Result of `nixpkgs-review pr 145273` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>30 packages built:</summary>
  <ul>
    <li>pwndbg</li>
    <li>pwntools (python39Packages.pwntools)</li>
    <li>python38Packages.angr</li>
    <li>python38Packages.angrcli</li>
    <li>python38Packages.angrop</li>
    <li>python38Packages.datasets</li>
    <li>python38Packages.manticore</li>
    <li>python38Packages.multiprocess</li>
    <li>python38Packages.pathos</li>
    <li>python38Packages.pwntools</li>
    <li>python38Packages.qiling</li>
    <li>python38Packages.sagemaker</li>
    <li>python38Packages.spacy-transformers</li>
    <li>python38Packages.tokenizers</li>
    <li>python38Packages.transformers</li>
    <li>python38Packages.unicorn</li>
    <li>python39Packages.angr</li>
    <li>python39Packages.angrcli</li>
    <li>python39Packages.angrop</li>
    <li>python39Packages.datasets</li>
    <li>python39Packages.manticore</li>
    <li>python39Packages.multiprocess</li>
    <li>python39Packages.pathos</li>
    <li>python39Packages.qiling</li>
    <li>python39Packages.sagemaker</li>
    <li>python39Packages.spacy-transformers</li>
    <li>python39Packages.tokenizers</li>
    <li>python39Packages.transformers</li>
    <li>python39Packages.unicorn</li>
    <li>unicorn</li>
  </ul>
</details>

**Comment by fabaff** [comment]
> shipping a x.0.0-rc version for a stable release

Staying with the stable unicorn release would lead to the same hack for `qiling` as we do for `angr`. `angr` has an override for the `unicorn` release. Python module should not do this but it was accepted as an option of last resort. Going with `rc` may not be optional for `manticore` but for `qiling` wouldn't introduce more hacks.

> disabling tests that are broken by the new unicorn

`manticore-0.3.5` is broken (https://hydra.nixos.org/build/157321677) already. At the moment there seems to be no way around disabling tests even if we stick to the older `unicorn` release.

**Comment by nrdxp** [comment]
> * shipping a `x.0.0-rc` version for a stable release

At least to this point, I don't think it's so aweful, since we can always upgrade to the stable release and backport when it's available.

**Comment by risicle** [comment]
Wait stop - you've just broken unicorn on darwin, after I told you as much and right in front of my face.

**Pull request merged**
