### PR TITLE
wasmtime: 0.21.0 -> 0.35.2

### PR DESCRIPTION
**Pull request by ereslibre**
###### Description of changes

Supersedes https://github.com/NixOS/nixpkgs/pull/109571

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
Just tested and this won't build for darwin. (The ci shows the failure if you are interested, but I'm afraid those are quite cryptic)
```
FAILED: obj/libv8_libbase.a
rm -f obj/libv8_libbase.a && "../../../../../../nix/store/cvz17hkb0wpbsyx58l4zcaamqs2bhlmz-clang-wrapper-11.1.0/bin/llvm-ar"  -r -c -s -D obj/libv8_libbase.a "@obj/libv8_libbase.a.rsp"
/bin/sh: ../../../../../../nix/store/cvz17hkb0wpbsyx58l4zcaamqs2bhlmz-clang-wrapper-11.1.0/bin/llvm-ar: No such file or directory
```

Could you change the platform to only linux ?

Also the ci fails on linux with the following 
```
failures:
    commands::compile::test::test_successful_compile
    commands::compile::test::test_x64_flags_compile
    commands::compile::test::test_x64_presets_compile

test result: FAILED. 16 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.05s
```
Could you mark those tests to be skipped ?
something like
```
  checkFlags = [
    # tries to make a network access
    "--skip=sinks::loki::tests::healthcheck_grafana_cloud"
  ];
```
(I just copied and pasted the relevant part from another test to give you an example in case you hadn't seen it. (more can be found in pkgs/tools/misc/vector/default.nix

**Comment by ereslibre** [comment]
> Could you change the platform to only linux ?

Done, although I will check what's wrong, I'd like to have the derivation for Mac OS as well. I would not block this PR because of that though.

> Could you mark those tests to be skipped ?

Done, and I have done the same with the patch that I had removing a test, and removed the patch that was removing the test itself.

> Also the ci fails on linux with the following

I cannot reproduce this and I wonder why. Do you know how can I reproduce this locally, or get more information from the CI run? I would like to go further into this.

> oh and last but not least, thanks a lot for the PR!

:)

**Comment by happysalada** [comment]
oh small detail regarding the first commit. It should probably be `wasmtime: fix build`
Some people like to have the commit message start by the package name to make it easier to search through commits.
Just something for next time.

**Comment by nomeata** [comment]
Oh, did we just lose wasmtime on Darwin? That's be very unfortunate. I hope it's only temporary. (Pinging @ggreif)

**Comment by ereslibre** [comment]
> Oh, did we just lose wasmtime on Darwin?

I want to check why it's failing and my plan is to restore it as soon as possible. It was also nice to have a more recent version of wasmtime.

**Comment by nomeata** [comment]
Ok, thanks :-)

**Comment by ereslibre** [comment]
@nomeata I will keep looking into it. `v8` was being problematic so the first approach I wanted was to disable checks but only on darwin. Now, I'm getting a linker error. I will open a PR when I have something that works :)

WIP: https://github.com/NixOS/nixpkgs/compare/master...ereslibre:wasmtime-build-darwin

The error, in case is meaningful:

```
error: could not compile `wasmtime-cli` due to previous error
error: builder for '/nix/store/rjx90jsczzn5v4y74qd79v4yivgl8255-wasmtime-0.35.2.drv' failed with exit code 101;
       last 10 log lines:
       >   = note: Undefined symbols for architecture x86_64:
       >             "_futimens", referenced from:
       >                 rustix::imp::fs::syscalls::futimens::h8cff26252e668e9b in librustix-960c26ac3e1fab35.rlib(rustix-960c26ac3e1fab35.rustix.00f71eac-cgu.4.rcgu.o)
       >             "_utimensat", referenced from:
       >                 rustix::imp::fs::syscalls::utimensat::h92f324ed16adf14b in librustix-960c26ac3e1fab35.rlib(rustix-960c26ac3e1fab35.rustix.00f71eac-cgu.4.rcgu.o)
       >           ld: symbol(s) not found for architecture x86_64
       >           clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
       >
       >
       > error: could not compile `wasmtime-cli` due to previous error
       For full logs, run 'nix log /nix/store/rjx90jsczzn5v4y74qd79v4yivgl8255-wasmtime-0.35.2.drv'.
```

/cc @nomeata

**Comment by sunfishcode** [comment]
@ereslibre https://github.com/bytecodealliance/wasmtime/pull/4022 is a PR which addresses those linker errors.

**Comment by ereslibre** [comment]
Thank you @sunfishcode!

I just did a smoke test and it builds and runs correctly.

I will submit a new PR to nixpkgs as soon a new wasmtime version is tagged.

cc/ @nomeata

**Comment by ereslibre** [comment]
wasmtime 0.36.0 was released. I opened https://github.com/NixOS/nixpkgs/pull/169544.

It builds and links in darwin under aarch64, but fails to link under x86_64 (when running with rosetta).

We can follow up over there.

**Comment by ereslibre** [comment]
@nomeata https://github.com/NixOS/nixpkgs/pull/173870 is up and brings `wasmtime` to darwin back again :)

**Pull request merged**
