### PR TITLE
Systemd coredump zstd, enable elfutils support for stack traces in coredump 

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Motivation for this change
I wanted to have stack traces in coredumpctl. Also enabled zstd support which was missing.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
zstd compression reduces the size of the stack traces for my test form 3.0M to 1.4M.

**Comment by trofi** [comment]
Until very recently systemd was frequently crashing at stack trace generation time. Worth checking if nixos has a form of https://github.com/systemd/systemd/pull/20354 backported.

**Comment by flokli** [comment]
@trofi did this end up in `systemd-stable`, and if not, could you poke upstream to cherry-pick it there?

We usually don't add non-NixOS-specific patches, but wait for patches to trickle into `systemd-stable`.

**Comment by trofi** [comment]
> @trofi did this end up in `systemd-stable`, and if not, could you poke upstream to cherry-pick it there?
> 
> We usually don't add non-NixOS-specific patches, but wait for patches to trickle into `systemd-stable`.

Aha! Yeah, two patches I was concerned about are already in `nixpkgs/master`:
- https://github.com/systemd/systemd-stable/commit/765c366274db3ff841da237769f2b20a4ec3a045 (since 249.3)
- https://github.com/systemd/systemd-stable/commit/60630b5e812ce103e9625bcc87778165374a455e (since 249.5)

**Comment by dasJ** [comment]
I like this change a lot. Is this also backportworthy to staging-21.11?

**Comment by flokli** [comment]
@trofi I didn't build this yet, as it's quite a large rebuild. Is there a chance you could cherry-pick this into a local checkout and give it a spin?

**Comment by trofi** [comment]
> @trofi I didn't build this yet, as it's quite a large rebuild. Is there a chance you could cherry-pick this into a local checkout and give it a spin?

Sure! Works here just fine:

```
$ cat a.c
void t(){ __builtin_trap(); }
void r(){ t(); }
void a(){ r(); }
void p(){ a(); }
int main() { p(); }
$ sudo gcc a.c -o /a -ggdb3
$ /a
Illegal instruction
$ journalctl -r | head -n 30
-- Journal begins at Mon 2021-08-30 17:56:01 BST, ends at Sun 2021-11-28 21:00:22 GMT. --
ноя 28 21:00:22 nz systemd[1]: systemd-coredump@34855-3968797-0.service: Deactivated successfully.
ноя 28 21:00:22 nz systemd-coredump[3968807]: Process 3968795 (a) of user 1000 dumped core.

                                                 Found module linux-vdso.so.1 with build-id: e1fae3fd1e8fbc9a72b8ae8d16fdc9c059c8da47
                                                 Found module ld-linux-x86-64.so.2 with build-id: b60b89b6921053c086d6640f5ecc02035efc1570
                                                 Found module libc.so.6 with build-id: 30f69e92c5e710c15fcda2dec8c5316b040db347
                                                 Found module a without build-id.
                                                 Stack trace of thread 3968795:
                                                 #0  0x000000000040110a t (a + 0x110a)
                                                 #1  0x000000000040111a r (a + 0x111a)
                                                 #2  0x000000000040112b a (a + 0x112b)
                                                 #3  0x000000000040113c p (a + 0x113c)
                                                 #4  0x000000000040114d main (a + 0x114d)
                                                 #5  0x00007f79e16bc780 __libc_start_main (libc.so.6 + 0x27780)
                                                 #6  0x000000000040104a _start (a + 0x104a)
```

**Review by trofi — APPROVED** [review]

**Pull request merged**
