### PR TITLE
cargo-audit: 0.20.0 -> 0.20.1

### PR DESCRIPTION
**Pull request by ipetkov**
## Description of changes

https://github.com/rustsec/rustsec/releases/tag/cargo-audit%2Fv0.20.1

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ipetkov** [comment]
Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>cargo-audit</li>
  </ul>
</details>

**Comment by newAM** [comment]
Result of `nixpkgs-review pr 335192` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>cargo-audit</li>
  </ul>
</details>

**Review by newAM — APPROVED** [review]

**Review by pinage404 — APPROVED** [review]
Thanks for this !

I found this PR important because without this `cargo-audit` can't compile

1 package built:
cargo-audit

Result of `nixpkgs-review pr 335192` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>1 package built:</summary>
<ul>
<li>cargo-audit</li>
</ul>
</details>

I tested the built binary, it works for me

**Review by a-kenji — APPROVED** [review]

**Comment by jonhoo** [comment]
Worth pointing out that this mitigates https://github.com/NixOS/nixpkgs/issues/332957 for cargo-audit (which is also affected), as confirmed upstream in https://github.com/rustsec/rustsec/issues/1240.

**Comment by jonhoo** [comment]
Am I right that https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.cargo-audit.x86_64-linux is the page to watch for whether the next attempted build into nixpkgs-unstable will succeed?

**Comment by gauravjuvekar** [comment]
Yep. I've verified it builds for x86_64-linux locally just now with https://github.com/gauravjuvekar/homemanager_common/commit/7fb8e1f96a8799d94054b119ea5388fc69dd7868

```
$ nix build github:NixOS/nixpkgs/6cb5757dce96718ad47108f0a5a3ff1b2b9b96c2#cargo-audit
$ readlink -f result
/nix/store/vvg8axqpc3aci5qh3k2vbnwvdccmdnqy-cargo-audit-0.20.1
```

**Comment by a-kenji** [comment]
You can also check at what point it will be in the channels:

https://nixpk.gs/pr-tracker.html?pr=335192

**Pull request merged**
