### PR TITLE
pyicu: 2.6 -> 2.7.3

### PR DESCRIPTION
**Pull request by edude03**
###### Motivation for this change
ZHF: #122042, ping @NixOS/nixos-release-managers

Looks like it was broken by b8b108166697cd0a5e68a78216c07a26c252e1f7, since 2.6 requires icu68. We could upgrade pyicu or if that doesn't work / breaks more packages we can use the `icu68` derivation in here instead.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 123428` at f128f87b run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/5348ba439d13c8b2fc4a62f02e826806">python38Packages.fingerprints</a></li>
    <li><a href="https://gist.github.com/bd72a2eb749c74259f3e4963c415bc15">python38Packages.normality</a></li>
    <li><a href="https://gist.github.com/cea981d262e18384cf4aba4cd63afdc1">python38Packages.scancode-toolkit</a></li>
    <li><a href="https://gist.github.com/5391fa5fedfadbcca31cc354bbec0314">python39Packages.fingerprints</a></li>
    <li><a href="https://gist.github.com/4ed1828437db78372212520a72701b2b">python39Packages.normality</a></li>
    <li><a href="https://gist.github.com/cbdc741175356514702f43da29b8f386">python39Packages.scancode-toolkit</a></li>
  </ul>
</details>
<details>
  <summary>7 packages built successfully:</summary>
  <ul>
    <li>gramps</li>
    <li>python38Packages.PyICU</li>
    <li>python38Packages.slob</li>
    <li>python39Packages.PyICU</li>
    <li>python39Packages.slob</li>
    <li>tests.trivial</li>
    <li>xdxf2slob</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/pyicu/default.nix:22:3:
```
   |
22 |   meta = with lib; {
   |   ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by Mindavi** [comment]
Doesn't icu69 work? According to the changelog it should work.

**Comment by edude03** [comment]
It doesn’t, it builds but the tests fail.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Mindavi** [comment]
Nothing to do about that then :(. Might be good to make a bugreport upstream if you'd like.

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 123428 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>13 packages built:</summary>  <ul>    <li>gramps</li>    <li>python38Packages.PyICU</li>    <li>python38Packages.fingerprints</li>    <li>python38Packages.normality</li>    <li>python38Packages.scancode-toolkit</li>    <li>python38Packages.slob</li>    <li>python39Packages.PyICU</li>    <li>python39Packages.fingerprints</li>    <li>python39Packages.normality</li>    <li>python39Packages.scancode-toolkit</li>    <li>python39Packages.slob</li>    <li>tests.trivial</li>    <li>xdxf2slob</li>  </ul></details>

**Pull request merged**
