### PR TITLE
Fix evaluation of package sets

### PR DESCRIPTION
**Pull request by ncfavier**
Extracted from https://github.com/NixOS/nixpkgs/pull/156870, makes the following command succeed

```
nix-env -f '<nixpkgs>' --arg config 'import <nixpkgs/pkgs/top-level/packages-config.nix>' -qa --drv-path
```

### CODE REVIEW

**Comment by sternenseemann** [comment]
I'll clean up the haskell packages thing separately, it needs a package set regeneration.

**Comment by sternenseemann** [comment]
Okay, actually I'd prefer not to make that change, actually. It would basically eliminate the nice error message users will get when trying to use this attribute from haskellPackages. I'll propose an alternative solution.

**Comment by sternenseemann** [comment]
#158656

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 158623 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Pull request merged**
