### PR TITLE
sanjuuni: fix build with FFmpeg 7 

### LINKED ISSUE #348724: Build failure: sanjuuni
### Steps To Reproduce

1. Build `sanjuuni`

### Build log

```
this derivation will be built:
  /nix/store/mcky5q58k3l04hq3wm817g4k2jrnpq6c-sanjuuni-0.5.drv
building '/nix/store/mcky5q58k3l04hq3wm817g4k2jrnpq6c-sanjuuni-0.5.drv'...
Running phase: unpackPhase
unpacking source archive /nix/store/vcpmdaa2r5lvrjza2y8zij2xadjnkicp-source
source root is source
Running phase: patchPhase
Running phase: updateAutotoolsGnuConfigScriptsPhase
Running phase: configurePhase
patching script interpreter paths in ./configure
./configure: interpreter directive changed from "#! /bin/sh" to "/nix/store/717iy55ncqs0wmhdkwc5fg2vci5wbmq8-bash-5.2p32/bin/sh"
configure flags: --prefix=/nix/store/2158fgamx7nlzmad7k9zdnqhnk3i3gqs-sanjuuni-0.5
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking whether C++ compiler accepts -std=c++17... yes
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for libavformat/avformat.h... yes
checking for libavcodec/avcodec.h... yes
checking for libavdevice/avdevice.h... yes
checking for libavfilter/avfilter.h... yes
checking for libswscale/swscale.h... yes
checking for libswresample/swresample.h... yes
checking for zlib.h... yes
checking for Poco/Base64Encoder.h... yes
checking for Poco/Util/OptionProcessor.h... yes
checking for Poco/Net/HTTPServer.h... yes
checking for Poco/Net/HTTPSClientSession.h... yes
checking for Poco/Crypto/X509Certificate.h... yes
checking for CL/opencl.hpp... yes
checking for library containing pthread_create... none required
checking for library containing avcodec_find_decoder... -lavcodec
checking for library containing avdevice_register_all... -lavdevice
checking for library containing avfilter_version... -lavfilter
checking for library containing avformat_open_input... -lavformat
checking for library containing av_frame_alloc... -lavutil
checking for library containing sws_getContext... -lswscale
checking for library containing swr_alloc_set_opts... no
configure: error: Could not find libswresample library.
```

### Additional context

libswresample is part of ffmpeg.

### Notify maintainers

Just me @tomodachi94.

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.0-1025-azure, Ubuntu, 20.04.6 LTS (Focal Fossa), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - nixpkgs: `/nix/store/mln6wr5z539qgldmsm4j1k8k0dm19yvz-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by tomodachi94**
Sanjuuni fails with FFmpeg 7:
```
configure: error: Could not find
libswresample library.
```
(per https://hydra.nixos.org/build/274775547)

libswresample is part of FFmpeg.

Upstream recommends this fix (we
apply a similar one):
https://github.com/MCJack123/sanjuuni/issues/22#issuecomment-2198454686

Breakage introduced in:
https://github.com/NixOS/nixpkgs/pull/337855
ZHF: #352882

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by tomodachi94** [comment]
Upstream issue: https://github.com/MCJack123/sanjuuni/issues/30

**Comment by tomodachi94** [comment]
Upstream recommended this fix in https://github.com/MCJack123/sanjuuni/issues/22:
```console
sed -i 's/swr_alloc_set_opts/swr_alloc_set_opts2/' configure
```

**Comment by emilazy** [comment]
If that’s the only FFmpeg 7 issue then we should just do a `substituteInPlace` for it.

**Comment by tomodachi94** [comment]
Yes, that was my plan :) marked it as a draft until I had a moment to amend this PR to do so.

**Review by emilazy — APPROVED** [review]
LGTM. (No 24.05 backport; we use FFmpeg 6 there.)

**Comment by emilazy** [comment]
Result of `nixpkgs-review pr 354089` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)                                                          
<details>                                                                       
  <summary>1 package built:</summary>                                           
  <ul>                                                                          
    <li>sanjuuni</li>                                                           
  </ul>                                                                         
</details>

**Pull request merged**
