### PR TITLE
weechat: 4.0.5 -> 4.1.0

### PR DESCRIPTION
**Pull request by ncfavier**
https://github.com/weechat/weechat/releases/tag/v4.1.0

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ncfavier** [comment]
Darwin build failure [reported](https://github.com/weechat/weechat/issues/2031) upstream.

**Comment by ncfavier** [comment]
@NixOS/darwin-maintainers could you look into this? Why is [this cmake file](https://github.com/weechat/weechat/blob/c156fee0e1f07d2854d8ccff182eda464a101a4b/cmake/FindGettext.cmake) not finding `libintl.h` on darwin, despite it being present at `${gettext}/include/libintl.h`?

**Comment by ncfavier** [comment]
Thanks, that seems to work.

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 261174` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>weechat</li>
    <li>weechat-unwrapped</li>
    <li>weechat-unwrapped.guile</li>
    <li>weechat-unwrapped.lua</li>
    <li>weechat-unwrapped.man</li>
    <li>weechat-unwrapped.perl</li>
    <li>weechat-unwrapped.python</li>
    <li>weechat-unwrapped.ruby</li>
    <li>weechat-unwrapped.tcl</li>
  </ul>
</details>

**Comment by sikmir** [comment]
Result of `nixpkgs-review pr 261174` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>weechat</li>
    <li>weechat-unwrapped</li>
    <li>weechat-unwrapped.guile</li>
    <li>weechat-unwrapped.lua</li>
    <li>weechat-unwrapped.man</li>
    <li>weechat-unwrapped.perl</li>
    <li>weechat-unwrapped.python</li>
    <li>weechat-unwrapped.ruby</li>
    <li>weechat-unwrapped.tcl</li>
  </ul>
</details>

**Pull request merged**
