### PR TITLE
gotosocial: 0.16.0 -> 0.17.0

### PR DESCRIPTION
**Pull request by jugendhacker**
New [version](https://github.com/superseriousbusiness/gotosocial/releases/tag/v0.17.0) and ran nixfmt

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by jugendhacker** [comment]
Not sure if it would need a release notes entry, as the changes are kind of breaking and according to the upstream release notes migrations could take quite some time running.

**Review by blakesmith — APPROVED** [review]
Thanks!

**Review by surfaceflinger — APPROVED** [review]

**Comment by blakesmith** [comment]
@jugendhacker My only hesitation with closing #348416 is that upstream gotosocial is still built explicitly with golang 1.22 here: https://github.com/superseriousbusiness/gotosocial/blob/main/go.mod#L3. I'm not sure what the NixOS policy / stance is on whether we should try to match upstream project versions, or accept minor potential incompatibilities with whatever is latest in nixpkgs. Thoughts?

**Comment by jugendhacker** [comment]
Not sure about it either

**Comment by asymmetric** [comment]
IMO, we should actually try to match upstream's toolchain version, otherwise we end up introducing bugs, as seen in the original issue.

It doesn't look like we do that nixpkgs-wide, so I'm not sure what to do in this case. cc @zowoq as someone who's worked on the Go infrastructure a lot.

**Comment by asymmetric** [comment]
In any case, this PR should not be blocked by the discussion. We can continue in https://github.com/NixOS/nixpkgs/pull/348416

**Comment by zowoq** [comment]
> upstream gotosocial is still built explicitly with golang 1.22 here: https://github.com/superseriousbusiness/gotosocial/blob/main/go.mod#L3.

That is the minimum go version, not the version that is explicitly required.

**Comment by asymmetric** [comment]
@zowoq true but IIUC it's also used to choose the toolchain version, and the default of `GOTOOLCHAIN` being `auto`, it means `go build` outside nixpkgs will in fact build with `1.22`. So semantically it's also the actually used version? Please correct me if I'm wrong.

**Comment by zowoq** [comment]
> the default of `GOTOOLCHAIN` being `auto`, it means `go build` outside nixpkgs will in fact build with `1.22`.

> https://go.dev/doc/toolchain
> In the standard configuration, the go command uses its own bundled toolchain when that toolchain is at least as new as the go or toolchain lines in the main module or workspace. For example, when using the go command bundled with Go 1.21.3 in a main module that says go 1.21.0, the go command uses Go 1.21.3. When the go or toolchain line is newer than the bundled toolchain, the go command runs the newer toolchain instead. For example, when using the go command bundled with Go 1.21.3 in a main module that says go 1.21.9, the go command finds and runs Go 1.21.9 instead.

**Comment by blakesmith** [comment]
@zowoq Thanks for clarifying! Appreciate it.

**Pull request merged**
