### PR TITLE
geant4: 10.7.1 -> 11.0.0

### PR DESCRIPTION
**Pull request by OmnipotentEntity**
###### Motivation for this change

Updating to the latest version.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by veprbl** [comment]
@GrahamcOfBorg build python38Packages.geant4 python39Packages.geant4

**Comment by OmnipotentEntity** [comment]
Thanks!  I always forget that.

**Comment by veprbl** [comment]
Probably need to remove something here
https://github.com/NixOS/nixpkgs/blob/c9efb0765caed3d0e8da9088f49d93e64f34a59c/pkgs/development/libraries/physics/geant4/default.nix#L60-L68

**Comment by OmnipotentEntity** [comment]
The sha256 of the main tar file seems to have changed out from under me.  So I've updated that.

> Probably need to remove something here

Investigating this, it seems like these files changed from:

```
  target_include_directories(${target_name} PRIVATE ${PYTHON_INCLUDE_DIRS})
  target_link_libraries(${target_name} PRIVATE Boost::python "$<$<PLATFORM_ID:Darwin>:-undefined dynamic_lookup>")

```

to

```
  target_include_directories(${target_name} PRIVATE ${PYTHON_INCLUDE_DIRS})
  target_link_libraries(${target_name} PRIVATE Boost::python${PYTHON_VERSION_MAJOR}${PYTHON_VERSION_MINOR} "$<$<PLATFORM_ID:Darwin>:-undefined dynamic_lookup>")
```

In other words, it is now attempting to use variables to set the particular version of python.  I tried to just remove this:

```
  postPatch = ''
    # Fix for boost 1.67+
    substituteInPlace environments/g4py/CMakeLists.txt \
      --replace "REQUIRED python''${PYTHON_VERSION_MAJOR}''${PYTHON_VERSION_MINOR}" \
                "REQUIRED COMPONENTS $boost_python_lib"
    substituteInPlace environments/g4py/G4PythonHelpers.cmake \
      --replace "Boost::python''${PYTHON_VERSION_MAJOR}''${PYTHON_VERSION_MINOR}" "Boost::$boost_python_lib"
  '';
```

However, I get the same error on build.

```
und PythonLibs: /nix/store/dgmp76d54xxb3bka1fph17yz7n8rfkai-python3-3.8.12/lib/libpython3.8.so (found version "3.8.12") 
CMake Warning at /nix/store/q2lj6pxd6sn75fa9pjx9x3jpgxnr6zld-cmake-3.21.2/share/cmake-3.21/Modules/FindBoost.cmake:2186 (message):
  No header defined for python3838; skipping header check (note: header-only
  libraries have no designated component)
Call Stack (most recent call first):
  environments/g4py/CMakeLists.txt:11 (find_package)


CMake Error at /nix/store/q2lj6pxd6sn75fa9pjx9x3jpgxnr6zld-cmake-3.21.2/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: python3838) (found suitable version
  "1.69.0", minimum required is "1.65")
Call Stack (most recent call first):
  /nix/store/q2lj6pxd6sn75fa9pjx9x3jpgxnr6zld-cmake-3.21.2/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /nix/store/q2lj6pxd6sn75fa9pjx9x3jpgxnr6zld-cmake-3.21.2/share/cmake-3.21/Modules/FindBoost.cmake:2345 (find_package_handle_standard_args)
  environments/g4py/CMakeLists.txt:11 (find_package)


-- Configuring incomplete, errors occurred!
```

Any hints?

**Comment by veprbl** [comment]
@GrahamcOfBorg build python38Packages.geant4 python39Packages.geant4

**Comment by veprbl** [comment]
@OmnipotentEntity Your `PYTHON_VERSION_*` were expanded inside double quotes to empty strings, which is what bash does silently by default.

**Comment by tmplt** [comment]
Mind removing me from the list of maintainers while your at it? I haven't used geant4 for quite a while.

**Pull request merged**
