### PR TITLE
ghcjs-dom bump

### PR DESCRIPTION
**Pull request by k0001**
It built just fine in my computer.

Note 01f5c466ab6fbf3e9d34950d3684e8213ee83897 is introduced by #10011. In other words, this pull-request depends on #10011.

Thanks to @mayhewluke for his suggestions on how to package this.

### CODE REVIEW

**Comment by peti** [comment]
This patch does not apply cleanly on top of https://github.com/NixOS/nixpkgs/pull/10011:

~~~~
$ curl https://patch-diff.githubusercontent.com/raw/NixOS/nixpkgs/pull/10012.patch | git am
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3481    0  3481    0     0   6820      0 --:--:-- --:--:-- --:--:--  6812
Applying: bump ghcjs, ghcjs-boot, ghcjs-shims
error: patch failed: pkgs/development/compilers/ghcjs/default.nix:29
error: pkgs/development/compilers/ghcjs/default.nix: patch does not apply
Patch failed at 0001 bump ghcjs, ghcjs-boot, ghcjs-shims
The copy of the patch that failed is found in:
   /home/simons/.nix-defexpr/.git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
~~~~

**Comment by k0001** [comment]
@peti I rebased this against `master`. It should apply cleanly now. Thanks.

**Comment by peti** [comment]
Merged in 5b4f774ba8ffe415b661e85d00bdd54ea60a7917. Will go to `master` in the next couple of hours.

**Comment by k0001** [comment]
@peti sorry to bother, but I would like to know what's going on so as to better understand what happens whenever a pull-request like this gets accepted, in which the code doesn't go directly to `master`. Is there a process in place where commits go somewhere before going to `master`?

Thank you :)

**Comment by peti** [comment]
@k0001, the commit is in https://github.com/peti/nixpkgs/commits/haskell-updates, where all updates go for test building. http://lists.science.uu.nl/pipermail/nix-dev/2015-April/016912.html has a brief description of the process.

**Pull request closed without merging**
