### PR TITLE
clojure: 1.8.0 -> 1.9.0

### PR DESCRIPTION
**Pull request by jlesquembre**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by orivej** [comment]
Could you keep building Clojure from source?

**Comment by jlesquembre** [comment]
@orivej I tried, but I don't know how to do it.
For 1.9 looks like maven is needed. I know nothing about maven, and I'm getting errors when I call maven in the build phase

**Comment by grahamc** [comment]
@GrahamcOfBorg eval

**Comment by yegortimoshenko** [comment]
This has been merged in in #32700. I'm not closing #32695 because it builds from source.

**Pull request closed without merging**
