### PR TITLE
icr: 0.5.0 -> 0.6.0

### PR DESCRIPTION
**Pull request by c0bw3b**
###### Motivation for this change
None other than fixing a failing build on Hydra
Changelog: https://github.com/crystal-community/icr/releases/tag/v0.6.0
cc @peterhoeg 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by risicle** [comment]
`nox-review` builds for me, non-nixos linux x86_64, but executing `icr` complains:

```
Can not find `crystal` command. Make sure you have crystal installed.
```

Surely this should be `makeWrapper`ed into the `PATH` rather than relying on the execution environment's `crystal`?

**Comment by c0bw3b** [comment]
Only @peterhoeg could confirm but I guess it was done on purpose, to allow using `icr` with different crystal version, not just a fixed one.

**Comment by peterhoeg** [comment]
Sorry about the late reply guys. 

> but I guess it was done on purpose, to allow using icr with different crystal version, not just a fixed one.

Indeed. Although an argument can of course also be made for having it work out of the box. I'll open a PR to remove the wrapper.

**Comment by c0bw3b** [comment]
Ah ok, no problem.
I saw your +1 on @risicle comment so I then assumed I was wrong.
But do cc me on your PR

**Pull request merged**
