### PR TITLE
gdm: 3.34.1 -> 3.36.3

### PR DESCRIPTION
**Pull request by dasj19**
###### Motivation for this change

Version bump.
Changelog:
```
==============
Version 3.36.2
==============
- Fixes for when GDM isn't started on its configured initial VT
- Don't hardcode path to plymouth
- keyutils has a .pc file so use it
- Chrome remote desktop fix
- Always use separate session bus for greeter sessions
  This runs dbus-run-session, so the binary needs to be available
- Translation updates
==============
Version 3.36.3
==============
- User switching fix
- Translation updates


```

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

CC: @worldofpeace @jtojnar

### CODE REVIEW

**Comment by jtojnar** [comment]
Do we actually have `plymouth` on `PATH`? If yes, we should stop passing it to `substituteAll` in the GDM expression.

**Comment by jtojnar** [comment]
From the [other changes](https://gitlab.gnome.org/GNOME/gdm/-/compare/3.34.1...3.36.3), it might be nice to add `keyutils` dependency if it enables to [reuse the LUKS password](https://gitlab.gnome.org/Dudemanguy/gdm/-/commit/31ed6f2b3f1ab45ae07aad41c13a51ba91fd159d). @hedning might know better if the VT changes affect us.

**Comment by hedning** [comment]
> Do we actually have plymouth on PATH?

Yeah, it should be available when `boot.plymouth.enable` is true: 
https://github.com/NixOS/nixpkgs/blob/3bc1b7bf6fae7677b096fa8128e8cc4280ef7164/nixos/modules/system/boot/plymouth.nix#L87

So sort of an accident, but means we don't need to keep plymouth in the closure I guess.

> might know better if the VT changes affect us.

Looks like they simply make sure user sessions aren't launched on GDM's designated VT (7 in our case). Don't think that should affect us at all tbh as it's already fairly unlikely for GDM to launch a session on VT7 in the first place.

**Comment by worldofpeace** [comment]
Just want to mention we had an issue in lightdm where plymouth had to be hardcoded https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/display-managers/lightdm/default.nix#L95. Not sure if that will spark the same issue here though, but I think it's possible to be likely.

**Comment by worldofpeace** [comment]
I just tried this on my machine and it locks up with plymouth. So I think it needs to be hardcoded.

**Comment by dasj19** [comment]
@worldofpeace I have hardcoded the path to plymouth binary within the `fix-paths.patch`
@jtojnar I am adding keyutils to the dependencies right now.

**Comment by jtojnar** [comment]
@GrahamcOfBorg test gnome3 gnome3-xorg

**Comment by doronbehar** [comment]
gdm is updated now.

**Pull request closed without merging**
