### PR TITLE
mesa: restructure driver selection to be more architecture-neutral

### PR DESCRIPTION
**Pull request by CrystalGamma**
###### Motivation for this change
Allows Mesa to build on non-x86, non-ARM platforms like ppc64(le).
Part of [my roadmap](https://crystalgamma.github.io/nixpkgs-prs.html) to bring NixOS to OpenPower platforms.

The new logic should be logically equivalent for x86 and ARM platforms (but might cause rebuilds due to reordered list elements).

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dezgeg** [comment]
I don't see this very readable.

What you could do is just a separate case for x86 and then an else case which just adds the safest option (which is presumably only `virgl`).

**Comment by CrystalGamma** [comment]
The point was that "generic" architectures (like Power) that have PCIe support but no integrated GPUs get all drivers for GPUs widely available as PCIe cards by default, while drivers for integrated GPUs are only built for their platforms (ARM ⇒ freedreno, etnaviv, x86 ⇒ Intel drivers), so when following your suggestion I would need to add a specific path for ppc64(le) for each variable …

**Comment by dezgeg** [comment]
Makes sense. Maybe have the `else` case then just list all the drivers for the PCI(-E) cards.

**Comment by edolstra** [comment]
Note that adding support for a new platform is something that should go through the RFC process (since it may introduce a non-trivial maintenance burden for other contributors).

**Comment by CrystalGamma** [comment]
New design that more clearly shows the reasoning.

**Comment by CrystalGamma** [comment]
@edolstra Where can I access that process? FWIW, the initial platform enablement PR was marked as [RFC] …

**Comment by edolstra** [comment]
@CrystalGamma https://github.com/NixOS/rfcs

**Review by matthewbauer — APPROVED** [review]

**Review by benley — APPROVED** [review]

**Comment by CrystalGamma** [comment]
I see discussion on NixOS/rfcs#31 has largely concluded without major unaddressed objections …
Maybe we should just (squash &) merge this (even though the RFC hasn't been merged)?

**Comment by matthewbauer** [comment]
I still think this is helpful - the old way basically just had static lists for each system. We should think more in capabilities - what driver works and doesn't work with each system.

**Comment by matthewbauer** [comment]
@grahamcofborg build mesa

**Pull request merged**
