### PR TITLE
nextcloud22: 22.2.0 -> 22.2.1

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

ChangeLog: https://nextcloud.com/changelog/#22-2-1

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by turion** [comment]
Note https://github.com/nextcloud/server/issues/29678, it's probably a bad idea to update to 22.2.1 :(

**Comment by turion** [comment]
Not sure whether we should maybe temporarily revert?

**Comment by Ma27** [comment]
The backport shouldn't be merged, of course now. Let's wait a moment and see if they publish a hotfix release (though I didn't have notable performance issues, otherwise I wouldn't have merged in the first place).

Also, if it's known what the problem is, we probably want to just apply a fix?

**Comment by turion** [comment]
The fix is probably coming from https://github.com/nextcloud/server/pull/29682, and it's not clear yet whether there is a hotfix release.

**Comment by beardhatcode** [comment]
There is a version 22.2.2, which should have fixed the issue. See: https://github.com/nextcloud/server/pull/29682 and https://github.com/NixOS/nixpkgs/pull/145700

**Pull request merged**
