### PR TITLE
hplip: remove enum-compat

### PR DESCRIPTION
**Pull request by fabaff**
Not needed on newer Python releases

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 350778` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>electrum-grs</li>
    <li>electrum-grs.dist</li>
  </ul>
</details>
<details>
  <summary>63 packages built:</summary>
  <ul>
    <li>electrum</li>
    <li>electrum.dist</li>
    <li>hplip</li>
    <li>hplipWithPlugin</li>
    <li>hwi (python312Packages.hwi)</li>
    <li>hwi.dist (python312Packages.hwi.dist)</li>
    <li>iocsearcher (python312Packages.iocsearcher)</li>
    <li>iocsearcher.dist (python312Packages.iocsearcher.dist)</li>
    <li>python311Packages.base58</li>
    <li>python311Packages.base58.dist</li>
    <li>python311Packages.bases</li>
    <li>python311Packages.bases.dist</li>
    <li>python311Packages.bip32</li>
    <li>python311Packages.bip32.dist</li>
    <li>python311Packages.bitbox02</li>
    <li>python311Packages.bitbox02.dist</li>
    <li>python311Packages.bitcoin-utils-fork-minimal</li>
    <li>python311Packages.bitcoin-utils-fork-minimal.dist</li>
    <li>python311Packages.block-io</li>
    <li>python311Packages.block-io.dist</li>
    <li>python311Packages.hwi</li>
    <li>python311Packages.hwi.dist</li>
    <li>python311Packages.iocsearcher</li>
    <li>python311Packages.iocsearcher.dist</li>
    <li>python311Packages.ipfshttpclient</li>
    <li>python311Packages.ipfshttpclient.dist</li>
    <li>python311Packages.ledger-bitcoin</li>
    <li>python311Packages.ledger-bitcoin.dist</li>
    <li>python311Packages.py-cid</li>
    <li>python311Packages.py-cid.dist</li>
    <li>python311Packages.py-multiaddr</li>
    <li>python311Packages.py-multiaddr.dist</li>
    <li>python311Packages.py-multihash</li>
    <li>python311Packages.py-multihash.dist</li>
    <li>python311Packages.pytest-cid</li>
    <li>python311Packages.pytest-cid.dist</li>
    <li>python312Packages.base58</li>
    <li>python312Packages.base58.dist</li>
    <li>python312Packages.bases</li>
    <li>python312Packages.bases.dist</li>
    <li>python312Packages.bip32</li>
    <li>python312Packages.bip32.dist</li>
    <li>python312Packages.bitbox02</li>
    <li>python312Packages.bitbox02.dist</li>
    <li>python312Packages.bitcoin-utils-fork-minimal</li>
    <li>python312Packages.bitcoin-utils-fork-minimal.dist</li>
    <li>python312Packages.block-io</li>
    <li>python312Packages.block-io.dist</li>
    <li>python312Packages.ipfshttpclient</li>
    <li>python312Packages.ipfshttpclient.dist</li>
    <li>python312Packages.ledger-bitcoin</li>
    <li>python312Packages.ledger-bitcoin.dist</li>
    <li>python312Packages.py-cid</li>
    <li>python312Packages.py-cid.dist</li>
    <li>python312Packages.py-multiaddr</li>
    <li>python312Packages.py-multiaddr.dist</li>
    <li>python312Packages.py-multihash</li>
    <li>python312Packages.py-multihash.dist</li>
    <li>python312Packages.pytest-cid</li>
    <li>python312Packages.pytest-cid.dist</li>
    <li>sparrow</li>
    <li>sparrow-unwrapped</li>
    <li>zeronet-conservancy</li>
  </ul>
</details>

**Comment by Pandapip1** [comment]
Blocked by https://github.com/NixOS/nixpkgs/pull/349608

**Comment by fabaff** [comment]
`electrum-grs` is already broken on `master`.

@Pandapip1, why is this blocked by https://github.com/NixOS/nixpkgs/pull/349608?

**Comment by Yarny0** [comment]
Tested on x86-64 with an HP LaserJet 1000, after cherry-picking the commit on top of [current `nixos-unstable`](https://github.com/NixOS/nixpkgs/tree/2768c7d042a37de65bb1b5b3268fc987e534c49d): loads firmware into printer as soon as printer is connected via USB, prints beautiful test page.  I approve!

**Comment by Pandapip1** [comment]
> Why is this blocked by https://github.com/NixOS/nixpkgs/pull/349608?

Borgy was failing due to fs not being able to find enum34, but it looks like it fixed itself.

**Review by Aleksanaa — APPROVED** [review]

**Review by Pandapip1 — APPROVED** [review]

**Pull request merged**
