### PR TITLE
lvm2: systemd fixes and update

### PR DESCRIPTION
**Pull request by ajs124**
###### Motivation for this change
We're deploying `lvmthin` and they recommend running `dmeventd`, and while there is an option on the lvm2 package, it sort of didn't work.

The update is in there, because our current version is from October of 2018.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

This probably needs a changelog entry and some documentation updates, because:

1. it's probably worth noting that we support lvm2 services now. You can run dmeventd simply by setting `systemd.packages = with pkgs; [ lvm2 ];` and `systemd.sockets."dm-event".wantedBy = [ "sockets.target" ];`. And mabye you also need a `lvm.conf`. (And also `lvm2.override { enable_dmeventd = true; }`).
2. `blk_availability_systemd_red_hat.service` and `lvm2_activation_generator_systemd_red_hat` are currently manually installed with these names. Using the upstream install they're simply called `blk-availability.service` and `lvm2-activation-generator`.

I haven't looked through the commit history that much, but I'm wondering why dmeventd is optional in the first place. Is the difference in closure size really that big?

There's also at least two other lvm daemons (lvmetad and lvmpoold), which we're not shipping right now.

Point 1. above might also warrant the introduction of a small module to configure dmeventd and the other daemons, if anyone is interested in those.

### CODE REVIEW

**Comment by 7c6f434c** [comment]
I would guess that nobody wanted to check if `dmeventd` is fully ignorable if enabled (although the man page seems to suggest so). The dependency set does not seem to differ, so I guess making it on by default should be safe. Same with the other daemons, hopefully.

As for modules — well, I guess this is a necessary step to eventually having a NixOS test for all that…

No idea whether addition of more things should be mentioned in release notes (but I am not a user of stable), renaming installed files probably is a good thing to mention. (I wonder if it breaks some rev-deps…)

**Comment by ajs124** [comment]
I looked a bit more into this. Turns out `lvmetad` isn't part of `lvm2` anymore. `lvmpolld` still exists, though.

For turning them off there is `global/use_lvmpolld` and `activation/monitoring`.

The other daemons include some python d-bus stuff and cluster stuff (`lvmlockd`, `cmirrord`), but I'd not add them right now, as we don't use them and I don't really know how to test them.

As for tests, there is `nixos.tests.installer.lvm`, but it's pretty basic.

The main hold-up for extending `nixos/modules/tasks/lvm.nix` with thin support is that #46541 never got merged, for valid reasons, but with #72401 still in progress, not much has changed on that front.

**Comment by 7c6f434c** [comment]
Well, maybe it is enough for the first step just not to break the basic operation… 

So, for this PR what is needed is a release note entry that we rename installed files back to upstream names?

**Comment by ajs124** [comment]
Enabling dmeventd doesn't actually work right now, because of 
```
cycle detected in the references of '/nix/store/9x3ny30dvb8i2lrc5pybgjvrjci4hb3x-lvm2-2.03.09-lib' from '/nix/store/nhrji14hh4nq3grg1jzgkrzbp04qymg1-lvm2-2.03.09-bin'
```

Not sure how to fix that while keeping the split outputs.

**Comment by flokli** [comment]
@ajs124 I propose checking the outputs, and /why/ there are these circular references.

**Comment by ajs124** [comment]
It's not that much of a "why", but:
```
find /nix/store/9x3ny30dvb8i2lrc5pybgjvrjci4hb3x-lvm2-2.03.09-lib -type f -exec strings -f {} + | grep /nix/store/nhrji14hh4nq3grg1jzgkrzbp04qymg1-lvm2-2.03.09-bin                                                                                                                              

/nix/store/9x3ny30dvb8i2lrc5pybgjvrjci4hb3x-lvm2-2.03.09-lib/lib/libdevmapper-event.so.1.02: /nix/store/nhrji14hh4nq3grg1jzgkrzbp04qymg1-lvm2-2.03.09-bin/bin
/nix/store/9x3ny30dvb8i2lrc5pybgjvrjci4hb3x-lvm2-2.03.09-lib/lib/liblvm2cmd.so.2.03: /nix/store/nhrji14hh4nq3grg1jzgkrzbp04qymg1-lvm2-2.03.09-bin/bin/fsadm
/nix/store/9x3ny30dvb8i2lrc5pybgjvrjci4hb3x-lvm2-2.03.09-lib/lib/liblvm2cmd.so.2.03: /nix/store/nhrji14hh4nq3grg1jzgkrzbp04qymg1-lvm2-2.03.09-bin/bin/dmeventd
/nix/store/9x3ny30dvb8i2lrc5pybgjvrjci4hb3x-lvm2-2.03.09-lib/lib/liblvm2cmd.so.2.03: /nix/store/nhrji14hh4nq3grg1jzgkrzbp04qymg1-lvm2-2.03.09-bin/bin/lvm
```

**Comment by flokli** [comment]
Yeah, I dropped `liblvm2cmd`from the expresssion - it's ["a library aiming to simplify typical LV management tasks from a web interface"](https://www.redhat.com/archives/linux-lvm/2008-September/msg00029.html) - see https://github.com/NixOS/nixpkgs/pull/88565/commits/3b7d76bff76f1b0d2312a0528a97ed0615a4dfd7.

If `dmeventd` now depends on it as well, that'll make things more complicated. How do other distros handle this? It seems it's not installed in Gentoo [as well](https://gitweb.gentoo.org/repo/gentoo.git/diff/sys-fs/lvm2/lvm2-2.02.187-r2.ebuild?id=171bc0144212041972ae2e877078cf073b8252a5).

**Comment by ajs124** [comment]
The problem isn't only `liblvm2cmd` though. The problem is also that `libdevmapper-event.so` depends on `bin` when `dmeventd` is enabled and `dmeventd`, `lvm` and `dmsetup` depend on `libdevmapper-event.so`.

**Comment by flokli** [comment]
I'm not entirely sure which of the components are needed for lvm operation these days - I mostly introduced the multiple outputs to get the closure size down, as systemd only uses the devmapper components shipped inside lvm.

**Comment by ajs124** [comment]
> I'm not entirely sure which of the components are needed for lvm operation these days

I'm not sure what either, to be honest.

> I mostly introduced the multiple outputs to get the closure size down, as systemd only uses the devmapper components shipped inside lvm.

That's what I assumed. Reducing closure size for something like systemd is always a good idea.

The question is where we go from here. I can spend some time to figure out which parts of LVM are relevant for what, which is probably relevant to us in any case.
However, that might lead to the conclusion that features like dmeventd or lockd are incompatible with multiple outputs. It's probably _technically possible_ to disable the multiple outputs in case such a feature is activated, but that's sounds ugly.

**Comment by flokli** [comment]
I'm all fine with reducing some of the multiple-output stuff. Does your PR currently build, and does the new test succeed?

In that case, I could merge this into https://github.com/NixOS/nixpkgs/pull/66856, possibly squashing some of the changes for readability.

Did you check the closure size of the minimal iso before and after this change?

**Comment by ajs124** [comment]
It doesn't build as is, but _probably_ builds and runs fine without multiple outputs.

I haven't checked the closure size yet. Not sure when I'll get around to put some time into this, might not happen before next week, sorry.

**Comment by flokli** [comment]
@7c6f434c I incorporated this into https://github.com/NixOS/nixpkgs/pull/66856#issuecomment-657209616, feel free to take a look :-)

**Pull request closed without merging**
