### PR TITLE
add ocsigen_start

### PR DESCRIPTION
**Pull request by FlorentBecker**
###### Motivation for this change

This updates to the latest versions of the ocsigen project. This allows nix users to follow their "recommended workflow".

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vbgl** [comment]
The two attributes `ocsigen_server` and `ocsigen_server_pgocaml` have the same value (in the second, you explicitly set the `pgocaml` parameter to its default value). If you really want a version of `ocsigenserver` build without PostgreSQL support, then you may add a call with `{ pgocaml = null; }`. An other possibility is to add a boolean argument, say `pgSupport`, that defaults to `false`, and that is set to `true` in the `ocsigen_server_pgocaml` attribute.

Please do not introduce arbitrary mismatches between package name, attribute name, directory name, etc. For instance, you should use `ocsigen-toolkit` everywhere (with a dash).

Is `ocsigen-i18n` an OCaml library? If not, then `createFindlibDestdir` should be `false`. Otherwise, something is wrong in the build since nothing is installed in that directory.

`buildOCaml` sets the `meta.platforms` for you: no need to override it.

**Comment by vbgl** [comment]
Cherry-picked the first commits as e3a77dd49ab72150c8cf23e9603ed4f6a7fb2457, 9fd4966429e188711844651360ffbb1e3042d93b, and bc26feb1d6edfce6b43d0d82e418e0a7c4551c78.

I think the packages for `ocsigen-start` and `ocsigen-i18n` are not yet ready.

**Comment by FlorentBecker** [comment]
Do you mean the software or the packaging?

**Comment by vbgl** [comment]
I’m talking about the packaging.

About `ocsigen-start`, there should be a convenient way to tell `eliom-distillery` where the template is.

```
$ eliom-distillery -template os.pgocaml
eliom-distillery: Not a known template name: "os.pgocaml".
```

About `ocsigen-i18n`, is it a library? does it belong to `ocaml-packages.nix`?

**Comment by vbgl** [comment]
Merged in ac87d9ba8bb2a6602bd267c90ddcf25cfe29498f, 091073819a8e1cf98b7bb02f4a8d2e3af97b67e4, and e4d39749f288680c44152cdef7d438fe06534479. Thanks.

**Pull request closed without merging**
