### PR TITLE
rivet: 3.1.2 -> 3.1.3

### PR DESCRIPTION
**Pull request by veprbl**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by veprbl** [comment]
@GrahamcOfBorg build rivet

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105363` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>python27Packages.yoda</li>
  </ul>
</details>
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>fastnlo</li>
    <li>herwig</li>
    <li>python37Packages.rivet</li>
    <li>python37Packages.yoda</li>
    <li>rivet (python38Packages.rivet)</li>
    <li>yoda (python38Packages.yoda)</li>
    <li>sherpa</li>
    <li>thepeg</li>
    <li>yoda-with-root</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105363` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>python27Packages.yoda</li>
  </ul>
</details>
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>fastnlo</li>
    <li>herwig</li>
    <li>python37Packages.rivet</li>
    <li>python37Packages.yoda</li>
    <li>rivet (python38Packages.rivet)</li>
    <li>yoda (python38Packages.yoda)</li>
    <li>sherpa</li>
    <li>thepeg</li>
    <li>yoda-with-root</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105363` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>python27Packages.yoda</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>sherpa</li>
    <li>yoda-with-root</li>
  </ul>
</details>
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>fastnlo</li>
    <li>herwig</li>
    <li>python37Packages.rivet</li>
    <li>python37Packages.yoda</li>
    <li>rivet (python38Packages.rivet)</li>
    <li>yoda (python38Packages.yoda)</li>
    <li>thepeg</li>
  </ul>
</details>

sherpa
```
  CXX      libToolsOrg_la-Getter_Function.lo                                                                                                                                      [40/45777]  CXX      libToolsOrg_la-My_MPI.lo                                                                                                                                                           CXX      libToolsOrg_la-Exception.lo                                                                                                                                                        CXX      libToolsOrg_la-Exception_Handler.lo                                                                                                                                                CXX      libToolsOrg_la-My_File.lo                                                                                                                                                          CXX      libToolsOrg_la-File_IO_Base.lo                                                                                                                                                     CXX      libToolsOrg_la-Read_Write_Base.lo                                                                                                                                                  CXX      libToolsOrg_la-Run_Parameter.lo                                                                                                                                                  Run_Parameter.C:37:15: error: use of undeclared identifier 'CTL_HW'                                                                                                                           int mib[2]={CTL_HW,HW_PHYSMEM};                                                                                                                                                                         ^                                                                                                                                                                             Run_Parameter.C:37:22: error: use of undeclared identifier 'HW_PHYSMEM'                                                                                                                       int mib[2]={CTL_HW,HW_PHYSMEM};                                                                                                                                                                                ^                                                                                                                                                                      Run_Parameter.C:40:7: error: use of undeclared identifier 'sysctl'                                                                                                                            if (sysctl(mib,miblen,&pmem,&len,NULL,0)!=0) {                                                                                                                                                  ^                                                                                                                                                                                     Run_Parameter.C:56:15: error: use of undeclared identifier 'CTL_HW'                                                                                                                           int mib[2]={CTL_HW,HW_AVAILCPU};                                                                                                                                                                        ^
Run_Parameter.C:56:22: error: use of undeclared identifier 'HW_AVAILCPU'
  int mib[2]={CTL_HW,HW_AVAILCPU};
                     ^
Run_Parameter.C:59:7: error: use of undeclared identifier 'sysctl'
  if (sysctl(mib,miblen,&ncpu,&len,NULL,0)!=0) {
      ^
Run_Parameter.C:60:12: error: use of undeclared identifier 'HW_NCPU'
    mib[1]=HW_NCPU;
           ^
Run_Parameter.C:61:9: error: use of undeclared identifier 'sysctl'
    if (sysctl(mib,miblen,&ncpu,&len,NULL,0)!=0) {
        ^
8 errors generated.
make[4]: *** [Makefile:854: libToolsOrg_la-Run_Parameter.lo] Error 1
make[4]: Leaving directory '/private/tmp/nix-build-sherpa-2.2.10.drv-0/SHERPA-MC-2.2.10/ATOOLS/Org'
make[3]: *** [Makefile:594: all] Error 2
make[3]: Leaving directory '/private/tmp/nix-build-sherpa-2.2.10.drv-0/SHERPA-MC-2.2.10/ATOOLS/Org'
make[2]: *** [Makefile:493: all-recursive] Error 1
make[2]: Leaving directory '/private/tmp/nix-build-sherpa-2.2.10.drv-0/SHERPA-MC-2.2.10/ATOOLS'
make[1]: *** [Makefile:572: all-recursive] Error 1
make[1]: Leaving directory '/private/tmp/nix-build-sherpa-2.2.10.drv-0/SHERPA-MC-2.2.10'
make: *** [Makefile:498: all] Error 2
```

**Comment by veprbl** [comment]
Failing build for `sherpa` is failing on x86_64-darwin with current master: https://hydra.nixos.org/job/nixpkgs/trunk/sherpa.x86_64-darwin/all

**Pull request merged**
