### PR TITLE
helix: 22.12 -> 23.03

### PR DESCRIPTION
**Pull request by isti115**
###### Description of changes

https://github.com/helix-editor/helix/blob/master/CHANGELOG.md#2303-2023-03-31

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Isti115** [comment]
@ilian I see that you've requested this in #224054, could you please test this pr and verify that it's working? (You can use `nixpkgs-review pr 224062`.)

**Review by ilian — CHANGES_REQUESTED** [review]
Thanks for creating a PR.
The build is failing with `ERROR: The Cargo.lock contains git dependencies`.
You can find more info [on the CI log of ofborg here](https://logs.nix.ci/?key=nixos/nixpkgs.224062&attempt_id=2421f93c-f1b9-4d22-b520-1abe6bdd3ab1).

**Comment by cigrainger** [comment]
> Thanks for creating a PR.
> The build is failing with `ERROR: The Cargo.lock contains git dependencies`.
> You can find more info [on the CI log of ofborg here](https://logs.nix.ci/?key=nixos/nixpkgs.224062&attempt_id=2421f93c-f1b9-4d22-b520-1abe6bdd3ab1).

Yep, same here.

**Comment by the-mikedavis** [comment]
See https://github.com/helix-editor/helix/pull/6218, we pinned our dependency on tree-sitter to master. Ignoring the git patch and using the latest publish version on crates.io should be fine though, it shouldn't cause any compilation errors (just some slightly slower runtime behavior)

**Comment by james-atkins** [comment]
I've added the hash of the tree-sitter master branch to the `cargoLock.outputHashes` attribute and it works okay. See here: https://github.com/james-atkins/dotfiles/blob/3b4eb9a3851894e7023cede799170762ff9bf1f9/pkgs/helix/default.nix#L15

**Comment by Isti115** [comment]
@charles-dyfis-net Thanks for the ping, I have somehow missed the latest comment.
@james-atkins I've adapted your commit for this branch, thanks for the correction!

**Comment by charles-dyfis-net** [comment]
As amended, I'm now able to build and run this successfully on aarch64-darwin.

One thing that's a little odd is that running `hx --health` complains `Runtime directory does not exist: /nix/store/...-helix-23.03/bin/runtime` -- but since the wrapper setting `HELIX_RUNTIME` is pointing at the right place (and _does_ get found/used), I assume that's built-in behavior to support running from a source tree and harmless.

**Review by charles-dyfis-net — APPROVED** [review]

**Comment by happysalada** [comment]
@GrahamcOfBorg eval

**Comment by happysalada** [comment]
somehow ci is still failing, trying to restart it.

**Comment by leona-ya** [comment]
We should probably use Cargo.lock as in #224397, as mentioned here https://nixos.org/manual/nixpkgs/unstable/#compiling-rust-applications-with-cargo. We could either use the mentioned PR I made yesterday or add the changes here.

**Comment by happysalada** [comment]
Oh right this one is not going to work because of IFD, your PR js probably best then

**Comment by happysalada** [comment]
I've merged the other one as we went through the same process there (in the interest of speed of release and for additional testing)
Feel free to check, there is an explanation as to why the current approach doesn't work.

**Pull request closed without merging**
