### PR TITLE
rav1e: remove build-time dependency on libgit2

### PR DESCRIPTION
**Pull request by tjni**
It has a dependency on an old, vendored version of libgit2, which was causing some pain for work updating to clang 19. When investigating, we noticed that it only seems to use libgit2 at build-time to encode and later print out the commit hash [as part of the version string](https://github.com/xiph/rav1e/blob/0b743163beb4a981fc8855f6e44ef0662025bd4e/src/lib.rs#L239). This can be disabled from the list of default features.

The main difference from what I can see is that the current version is printed out as:

```
❯ result/bin/rav1e --version
rav1e 0.7.1 () (release)
rustc 1.82.0 (f6e511eec 2024-10-15) (built from a source tarball) aarch64-apple-darwin
Compiled CPU Features: aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh
Runtime Assembly Support: Enabled
Runtime Assembly Level: NEON
Threading: Enabled
Unstable Features: Disabled
Compiler Flags: -Ctarget-feature=-crt-static
```

while afterward we have:

```
❯ result/bin/rav1e --version
rav1e 0.7.1 (UNKNOWN) (release)
rustc 1.82.0 (f6e511eec 2024-10-15) (built from a source tarball) aarch64-apple-darwin
Compiled CPU Features: aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh
Runtime Assembly Support: Enabled
Runtime Assembly Level: NEON
Threading: Enabled
Unstable Features: Disabled
Compiler Flags: -Ctarget-feature=-crt-static
```

Note that we don't even currently get the git revision, probably because we fetch from crate.io instead of from GitHub while keeping the .git directory intact.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by paparodeo — APPROVED** [review]
LGTM -- maybe target llvm-19 branch

**Review by emilazy — APPROVED** [review]
Will handle the merge myself.

**Comment by paparodeo** [comment]
> Will handle the merge myself.

this triggers 1001 -> 2500 rebuilds. https://github.com/NixOS/nixpkgs/pull/355124 so shouldn't be in master.

**Comment by emilazy** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/355456, sorry. Will reapply on `llvm-19`. I didn’t see any big red labels but it turns out that ofborg took over 10 hours to even get to the eval :/

**Comment by paparodeo** [comment]
> Fixed in #355456, sorry. Will reapply on `llvm-19`. I didn’t see any big red labels but it turns out that ofborg took over 10 hours to even get to the eval :/

yeah, I could've mentioned it it my approval message

**Comment by tjni** [comment]
Sorry about that! I didn’t anticipate so many dependencies but this library is popular!

**Comment by emilazy** [comment]
I think it’s via FFmpeg, great aggregator of mass rebuilds :)

**Pull request merged**
