### PR TITLE
pythonPackages.mccabe fixup, hypothesis: 3.1.0 -> 3.5.2, flake8: 2.5.4 -> 2.6.2

### PR DESCRIPTION
**Pull request by groxxda**
###### Motivation for this change

mccabe was reverted in https://github.com/NixOS/nixpkgs/commit/25dcdc58d05a3e9421116a8bedd3a47815faf1f4 and the old version inited in https://github.com/NixOS/nixpkgs/commit/8eae96d70c18f2a1015796e8aa0ff84463f4711c
so we have the old version twice.

I also updated flake8 2.x to the latest released version to get rid of pep8
And while at it updated hypothesis.
We can split the hypothesis update I you prefer, but I built everything yesteday (3x webkit24x ...)

follow up to #19132 
cc @FRidh @7c6f434c 
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by 7c6f434c** [comment]
Oops, reacted to Hydra and missed the commit in-between. Looks reasonable.

**Comment by mdorman** [comment]
It's a shame that the travis failure was ignored, since it pointed out the issue with this merge.

**Comment by 7c6f434c** [comment]
Hm, the status seemed to be «pending»… is there yet another way Travis misinforms?

**Comment by mdorman** [comment]
Maybe Nix hits travis hard enough that stuff doesn't get run immediately? https://travis-ci.org/NixOS/nixpkgs/builds/164410021 suggests that the three actual checks all ran in < 3 minutes, but that the "total time" was 7+---so maybe that 4 minute discrepancy is the "pending" time?

**Comment by 7c6f434c** [comment]
>Maybe Nix hits travis hard enough that stuff doesn't get run immediately? https://travis-ci.org/NixOS/nixpkgs/builds/164410021 suggests that the three actual checks all ran in < 3 minutes, but that the "total time" was 7+---so maybe that 4 minute discrepancy is the "pending" time?

That's totally possible and I consider that normal.

I just wonder if  ignored the existing Travis faiure or just didn't wait
for the failure to happen.

**Pull request merged**
