### PR TITLE
fix accelerate, updating to git versions

### PR DESCRIPTION
**Pull request by NickHu**
This pull request depends on https://github.com/NixOS/nixpkgs/pull/27615.

`haskellPackages.accelerate` and its related packages are broken - somehow we've
ended up with a split with `accelerate` (0.15.x) and `accelerate_1_0_0_0`. I don't really see
any reason to keep the old one around, but it's there at the moment.

These changes add functionality to pull the latest git versions of the
accelerate packages, which seems unfortunately necessary because the current
versions on hackage don't build against what we have packaged in NixOS.

Another change made is the addition of `callCabal2nixWithOpts`, which takes
a set of options --- currently, the only one is to pass the `--subpath` flag to
`cabal2nix` (the main accelerate repo contains multiple cabal packages each in
a different directory).

I also had to update `cuda`, and also reapply the same patches in
`configuration-nix` --- this is ugly, I'm sure there's a better way, but I don't
know it.

Open to suggestions, but this is what I concluded as the 'path of least effort'
to getting accelerate working again.

Packages that are broken without this pr are things like `accelerate-examples`, `accelerate-io` etc.

Please check what applies. Note that these are not hard requirements but mereley serve as information for reviewers.

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by domenkozar** [comment]
I'd suggest to upload new (renamed?) packages to hackage since we have this all automated. Pinning down versions in Nix itself is manual and requires too much work (that's what we want to avoid with automation).

Best to make a separate PR for cabal2nix changes, I think those can be merged.

**Comment by NickHu** [comment]
I think the real solution is to get upstream to update the Hackage modules and see if that somehow manages to fix everything. But I think the `llvm-hs` fix should be applied.

**Comment by NickHu** [comment]
cc @tmcdonell

**Comment by tmcdonell** [comment]
I guess this is because the versions of `accelerate-llvm*` don't build against `llvm-hs >= 4.0`. I was planning to make a new release of accelerate and friends soon to address this (just a couple bugs remaining). Note that git HEAD currently constitutes a major version bump, so if this goes ahead I'd suggest versioning this as 1.1.0.0-rc1 or similar, if you can.

I expect you'll need to also update `accelerate-examples` if you are pulling the git versions, but `accelerate-io-1.0.0.0` is probably okay.

What is the issue with the `cuda` package? Can this be fixed there, or is this just something specific to nix configuration?

**Comment by NickHu** [comment]
There's a nix specific hack for `cuda` which is a duplicate of this which is already in master. I needed to update `cuda` here solely because these newer package versions also required newer `cuda` too - should be unnecessary after everything gets bumped.

**Comment by c0bw3b** [comment]
@NickHu I'm closing this old PR since `accelerate` v1.2.0.0 is part of <nixpkgs> by now

**Pull request closed without merging**
