### PR TITLE
[Backport release-21.11] bcachefs and related

### PR DESCRIPTION
**Pull request by Madouura**
###### Description of changes
Some fixes and catchup from master.
Namely, you can use encrypted bcachefs now without it bugging out.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Madouura** [comment]
cc @davidak

**Comment by Madouura** [comment]
On-disk format change seems to be automatic so shouldn't be an issue too, but we could remove the most recent patch if anyone things we should.

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 165790` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>36 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.linux_testing_bcachefs.anbox</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.ena</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.evdi</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.ixgbevf</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.kvmfr</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.mxu11x0</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.ndiswrapper</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.openafs_1_9</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.phc-intel</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.r8125</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.rtl8188eus-aircrack</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.rtl8723bs</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.rtl8812au</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.rtlwifi_new</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.rtw88</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.sch_cake</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.tbs</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.xmm7360-pci</li>
    <li>linuxPackages_testing_bcachefs.anbox</li>
    <li>linuxPackages_testing_bcachefs.ena</li>
    <li>linuxPackages_testing_bcachefs.evdi</li>
    <li>linuxPackages_testing_bcachefs.ixgbevf</li>
    <li>linuxPackages_testing_bcachefs.kvmfr</li>
    <li>linuxPackages_testing_bcachefs.mxu11x0</li>
    <li>linuxPackages_testing_bcachefs.ndiswrapper</li>
    <li>linuxPackages_testing_bcachefs.openafs_1_9</li>
    <li>linuxPackages_testing_bcachefs.phc-intel</li>
    <li>linuxPackages_testing_bcachefs.r8125</li>
    <li>linuxPackages_testing_bcachefs.rtl8188eus-aircrack</li>
    <li>linuxPackages_testing_bcachefs.rtl8723bs</li>
    <li>linuxPackages_testing_bcachefs.rtl8812au</li>
    <li>linuxPackages_testing_bcachefs.rtlwifi_new</li>
    <li>linuxPackages_testing_bcachefs.rtw88</li>
    <li>linuxPackages_testing_bcachefs.sch_cake</li>
    <li>linuxPackages_testing_bcachefs.tbs</li>
    <li>linuxPackages_testing_bcachefs.xmm7360-pci</li>
  </ul>
</details>
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>linuxPackages_testing_bcachefs.amdgpu-pro (linuxKernel.packages.linux_testing_bcachefs.amdgpu-pro)</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11_legacy340 (linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_legacy340)</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11_legacy390 (linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_legacy390)</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11_vulkan_beta (linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_vulkan_beta)</li>
    <li>linuxPackages_testing_bcachefs.openafs (linuxKernel.packages.linux_testing_bcachefs.openafs ,linuxPackages_testing_bcachefs.openafs_1_8)</li>
  </ul>
</details>
<details>
  <summary>71 packages built:</summary>
  <ul>
    <li>bcachefs-tools</li>
    <li>linux_testing_bcachefs (linuxPackages_testing_bcachefs.kernel)</li>
    <li>linuxPackages_testing_bcachefs.acpi_call (linuxKernel.packages.linux_testing_bcachefs.acpi_call)</li>
    <li>linuxPackages_testing_bcachefs.akvcam (linuxKernel.packages.linux_testing_bcachefs.akvcam)</li>
    <li>linuxPackages_testing_bcachefs.apfs (linuxKernel.packages.linux_testing_bcachefs.apfs)</li>
    <li>linuxPackages_testing_bcachefs.asus-wmi-sensors (linuxKernel.packages.linux_testing_bcachefs.asus-wmi-sensors)</li>
    <li>linuxPackages_testing_bcachefs.batman_adv (linuxKernel.packages.linux_testing_bcachefs.batman_adv)</li>
    <li>linuxPackages_testing_bcachefs.bbswitch (linuxKernel.packages.linux_testing_bcachefs.bbswitch)</li>
    <li>linuxPackages_testing_bcachefs.bcc (linuxKernel.packages.linux_testing_bcachefs.bcc)</li>
    <li>linuxPackages_testing_bcachefs.bpftrace (linuxKernel.packages.linux_testing_bcachefs.bpftrace)</li>
    <li>linuxPackages_testing_bcachefs.broadcom_sta (linuxKernel.packages.linux_testing_bcachefs.broadcom_sta)</li>
    <li>linuxPackages_testing_bcachefs.can-isotp (linuxKernel.packages.linux_testing_bcachefs.can-isotp)</li>
    <li>linuxPackages_testing_bcachefs.chipsec (linuxKernel.packages.linux_testing_bcachefs.chipsec)</li>
    <li>linuxPackages_testing_bcachefs.cpupower (linuxKernel.packages.linux_testing_bcachefs.cpupower)</li>
    <li>linuxPackages_testing_bcachefs.cryptodev (linuxKernel.packages.linux_testing_bcachefs.cryptodev)</li>
    <li>linuxPackages_testing_bcachefs.ddcci-driver (linuxKernel.packages.linux_testing_bcachefs.ddcci-driver)</li>
    <li>linuxPackages_testing_bcachefs.digimend (linuxKernel.packages.linux_testing_bcachefs.digimend)</li>
    <li>linuxPackages_testing_bcachefs.dpdk-kmods (linuxKernel.packages.linux_testing_bcachefs.dpdk-kmods)</li>
    <li>linuxPackages_testing_bcachefs.facetimehd (linuxKernel.packages.linux_testing_bcachefs.facetimehd)</li>
    <li>linuxPackages_testing_bcachefs.fwts-efi-runtime (linuxKernel.packages.linux_testing_bcachefs.fwts-efi-runtime)</li>
    <li>linuxPackages_testing_bcachefs.gcadapter-oc-kmod (linuxKernel.packages.linux_testing_bcachefs.gcadapter-oc-kmod)</li>
    <li>linuxPackages_testing_bcachefs.hid-nintendo (linuxKernel.packages.linux_testing_bcachefs.hid-nintendo)</li>
    <li>linuxPackages_testing_bcachefs.hyperv-daemons (linuxKernel.packages.linux_testing_bcachefs.hyperv-daemons)</li>
    <li>linuxPackages_testing_bcachefs.intel-speed-select (linuxKernel.packages.linux_testing_bcachefs.intel-speed-select)</li>
    <li>linuxPackages_testing_bcachefs.isgx (linuxKernel.packages.linux_testing_bcachefs.isgx)</li>
    <li>linuxPackages_testing_bcachefs.it87 (linuxKernel.packages.linux_testing_bcachefs.it87)</li>
    <li>linuxPackages_testing_bcachefs.jool (linuxKernel.packages.linux_testing_bcachefs.jool)</li>
    <li>linuxPackages_testing_bcachefs.lttng-modules (linuxKernel.packages.linux_testing_bcachefs.lttng-modules)</li>
    <li>linuxPackages_testing_bcachefs.mba6x_bl (linuxKernel.packages.linux_testing_bcachefs.mba6x_bl)</li>
    <li>linuxPackages_testing_bcachefs.mbp2018-bridge-drv (linuxKernel.packages.linux_testing_bcachefs.mbp2018-bridge-drv)</li>
    <li>linuxPackages_testing_bcachefs.mwprocapture (linuxKernel.packages.linux_testing_bcachefs.mwprocapture)</li>
    <li>linuxPackages_testing_bcachefs.netatop (linuxKernel.packages.linux_testing_bcachefs.netatop)</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11 (linuxKernel.packages.linux_testing_bcachefs.nvidia_x11)</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11_beta (linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_beta)</li>
    <li>linuxPackages_testing_bcachefs.nvidia_x11_legacy470 (linuxKernel.packages.linux_testing_bcachefs.nvidia_x11_legacy470)</li>
    <li>linuxPackages_testing_bcachefs.nvidiabl (linuxKernel.packages.linux_testing_bcachefs.nvidiabl)</li>
    <li>linuxPackages_testing_bcachefs.oci-seccomp-bpf-hook (linuxKernel.packages.linux_testing_bcachefs.oci-seccomp-bpf-hook)</li>
    <li>linuxPackages_testing_bcachefs.openrazer (linuxKernel.packages.linux_testing_bcachefs.openrazer)</li>
    <li>linuxPackages_testing_bcachefs.perf (linuxKernel.packages.linux_testing_bcachefs.perf)</li>
    <li>linuxPackages_testing_bcachefs.ply (linuxKernel.packages.linux_testing_bcachefs.ply)</li>
    <li>linuxPackages_testing_bcachefs.r8168 (linuxKernel.packages.linux_testing_bcachefs.r8168)</li>
    <li>linuxPackages_testing_bcachefs.rr-zen_workaround (linuxKernel.packages.linux_testing_bcachefs.rr-zen_workaround)</li>
    <li>linuxPackages_testing_bcachefs.rtl8192eu (linuxKernel.packages.linux_testing_bcachefs.rtl8192eu)</li>
    <li>linuxPackages_testing_bcachefs.rtl8814au (linuxKernel.packages.linux_testing_bcachefs.rtl8814au)</li>
    <li>linuxPackages_testing_bcachefs.rtl8821au (linuxKernel.packages.linux_testing_bcachefs.rtl8821au)</li>
    <li>linuxPackages_testing_bcachefs.rtl8821ce (linuxKernel.packages.linux_testing_bcachefs.rtl8821ce)</li>
    <li>linuxPackages_testing_bcachefs.rtl8821cu (linuxKernel.packages.linux_testing_bcachefs.rtl8821cu)</li>
    <li>linuxPackages_testing_bcachefs.rtl88x2bu (linuxKernel.packages.linux_testing_bcachefs.rtl88x2bu)</li>
    <li>linuxPackages_testing_bcachefs.rtl88xxau-aircrack (linuxKernel.packages.linux_testing_bcachefs.rtl88xxau-aircrack)</li>
    <li>linuxPackages_testing_bcachefs.rtw89 (linuxKernel.packages.linux_testing_bcachefs.rtw89)</li>
    <li>linuxPackages_testing_bcachefs.sysdig (linuxKernel.packages.linux_testing_bcachefs.sysdig)</li>
    <li>linuxPackages_testing_bcachefs.system76 (linuxKernel.packages.linux_testing_bcachefs.system76)</li>
    <li>linuxPackages_testing_bcachefs.system76-acpi (linuxKernel.packages.linux_testing_bcachefs.system76-acpi)</li>
    <li>linuxPackages_testing_bcachefs.system76-io (linuxKernel.packages.linux_testing_bcachefs.system76-io)</li>
    <li>linuxPackages_testing_bcachefs.systemtap (linuxKernel.packages.linux_testing_bcachefs.systemtap)</li>
    <li>linuxPackages_testing_bcachefs.tmon (linuxKernel.packages.linux_testing_bcachefs.tmon)</li>
    <li>linuxPackages_testing_bcachefs.tp_smapi (linuxKernel.packages.linux_testing_bcachefs.tp_smapi)</li>
    <li>linuxPackages_testing_bcachefs.turbostat (linuxKernel.packages.linux_testing_bcachefs.turbostat)</li>
    <li>linuxPackages_testing_bcachefs.tuxedo-keyboard (linuxKernel.packages.linux_testing_bcachefs.tuxedo-keyboard)</li>
    <li>linuxPackages_testing_bcachefs.usbip (linuxKernel.packages.linux_testing_bcachefs.usbip)</li>
    <li>linuxPackages_testing_bcachefs.v4l2loopback (linuxKernel.packages.linux_testing_bcachefs.v4l2loopback)</li>
    <li>linuxPackages_testing_bcachefs.v86d (linuxKernel.packages.linux_testing_bcachefs.v86d)</li>
    <li>linuxPackages_testing_bcachefs.veikk-linux-driver (linuxKernel.packages.linux_testing_bcachefs.veikk-linux-driver)</li>
    <li>linuxPackages_testing_bcachefs.vendor-reset (linuxKernel.packages.linux_testing_bcachefs.vendor-reset)</li>
    <li>linuxPackages_testing_bcachefs.vhba (linuxKernel.packages.linux_testing_bcachefs.vhba)</li>
    <li>linuxPackages_testing_bcachefs.virtualbox (linuxKernel.packages.linux_testing_bcachefs.virtualbox)</li>
    <li>linuxPackages_testing_bcachefs.virtualboxGuestAdditions (linuxKernel.packages.linux_testing_bcachefs.virtualboxGuestAdditions)</li>
    <li>linuxPackages_testing_bcachefs.x86_energy_perf_policy (linuxKernel.packages.linux_testing_bcachefs.x86_energy_perf_policy)</li>
    <li>linuxPackages_testing_bcachefs.xpadneo (linuxKernel.packages.linux_testing_bcachefs.xpadneo)</li>
    <li>linuxPackages_testing_bcachefs.zenpower (linuxKernel.packages.linux_testing_bcachefs.zenpower)</li>
    <li>linuxPackages_testing_bcachefs.zfs (linuxKernel.packages.linux_testing_bcachefs.zfs ,linuxPackages_testing_bcachefs.zfsStable ,linuxPackages_testing_bcachefs.zfsUnstable)</li>
  </ul>
</details>

**Review by davidak — APPROVED** [review]
Changes look good

Builds, tests successful

Thank you! :sparkles:

**Pull request merged**
