### PR TITLE
mimalloc: 1.1.0 -> 1.6.1

### PR DESCRIPTION
**Pull request by ajs124**
###### Motivation for this change
upstream release(s)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @thoughtpolice

### CODE REVIEW

**Review by jonringer — APPROVED** [review]
diff LGTM

```
[3 built, 0.0 MiB DL]
https://github.com/NixOS/nixpkgs/pull/80403
1 package built:
mimalloc
```
outputs look right:
```
[23:25:02] jon@jon-desktop /home/jon/projects/nixpkgs (master)
$ tree ./result
./result
└── lib
    ├── libmimalloc.a
    ├── libmimalloc.so -> libmimalloc.so.1.0
    ├── libmimalloc.so.1.0
    └── mimalloc.o

1 directory, 4 files
```
```
[nix-shell:/home/jon/.cache/nixpkgs-review/pr-80403]$ tree ./results/mimalloc
./results/mimalloc
└── lib
    ├── libmimalloc.a
    ├── libmimalloc.so -> libmimalloc.so.1.6
    ├── libmimalloc.so.1.6
    └── mimalloc.o

1 directory, 4 files
```

**Comment by jonringer** [comment]
@GrahamcOfBorg build mimalloc

**Comment by jonringer** [comment]
darwin failure:
```
/nix/store/h7i49dl44vcsb0mls05xmwjfyzj42p3z-mimalloc-1.6.1/lib/mimalloc-1.6/libmimalloc.1.6.dylib
/nix/store/h7i49dl44vcsb0mls05xmwjfyzj42p3z-mimalloc-1.6.1/lib/mimalloc-1.6/libmimalloc.a
/nix/store/h7i49dl44vcsb0mls05xmwjfyzj42p3z-mimalloc-1.6.1/lib/mimalloc-1.6/libmimalloc.dylib
/nix/store/h7i49dl44vcsb0mls05xmwjfyzj42p3z-mimalloc-1.6.1/lib/mimalloc-1.6/mimalloc.o
mv: cannot stat '/nix/store/h7i49dl44vcsb0mls05xmwjfyzj42p3z-mimalloc-1.6.1/lib/mimalloc-1.6/libmimalloc.dylib.1.6': No such file or directory
```

**Comment by ajs124** [comment]
I'm not sure this ever worked. It definitely doesn't work [right now](https://hydra.nixos.org/build/112973074/nixlog/2).

**Comment by jonringer** [comment]
mind adding ` badPlatforms = lib.platforms.darwin;` to the meta, so hydra isn't constantly reevaluating it.

**Review by thoughtpolice — APPROVED** [review]

**Pull request merged**
