### PR TITLE
zed-editor: downgrade nodejs

### PR DESCRIPTION
**Pull request by niklaskorz**
See #356257 and #355919.
Downgrades nodejs from latest to 22, as 23 (latest) currently fails to build.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilazy** [comment]
Seems good to me; I’ll give Zed users a chance to respond.

We could pick Node 22 instead, as it’s about to become the main LTS and the default for 25.05, if it’s likely that some things might use functionality not available in 20.

cc @jansol @GaetanLepage

**Comment by niklaskorz** [comment]
> Seems good to me; I’ll give Zed users a chance to respond.
> 
> We could pick Node 22 instead, as it’s about to become the main LTS and the default for 25.05, if it’s likely that some things might use functionality not available in 20.
> 
> cc @jansol @GaetanLepage

22 also is what [Zed itself downloads](https://github.com/zed-industries/zed/blob/d664f56fac161cec8b14d9093dc553c07936fe34/crates/node_runtime/src/node_runtime.rs#L268) if no Node installation is found, so that seems fair enough.

**Comment by emilazy** [comment]
We could leave it as `nodejs_22` for 24.11 but unpin to `nodejs` once it becomes the default on unstable.

I’m agnostic about `all-packages.nix` – I personally prefer to keep version overrides with the definition for legibility but other people prefer to do it differently to make the override API more sensible.

**Comment by niklaskorz** [comment]
> We could leave it as `nodejs_22` for 24.11 but unpin to `nodejs` once it becomes the default on unstable.
> 
> I’m agnostic about `all-packages.nix` – I personally prefer to keep version overrides with the definition for legibility but other people prefer to do it differently to make the override API more sensible.

Alright, for consistency sake (i.e., we already have `apple-sdk_15`), I won't override nodejs in all-packages and instead directly use `nodejs_22` in the package.

**Comment by aduh95** [comment]
> I won't override nodejs in all-packages and instead directly use `nodejs_22` in the package.



FWIW it's already done on `staging`: https://github.com/NixOS/nixpkgs/blob/0b3eef7441c4c8becc61d67004bd8d05c33922a1/pkgs/top-level/all-packages.nix#L4299

**Review by emilazy — APPROVED** [review]

**Review by GaetanLepage — APPROVED** [review]

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 356459`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

---
### `x86_64-darwin`

---
### `aarch64-darwin`

**Comment by emilazy** [comment]
Feel free to cc me on a `staging` PR to unpin the version after the automatic merge goes through.

**Pull request merged**
