### PR TITLE
patchutils: fix and 0.3.3 -> 0.3.4

### PR DESCRIPTION
**Pull request by plesiv**
###### Motivation for this change

- `patchutils` binaries using perl (e.g. `splitdiff`) were broken before this change
- according to [repology](https://repology.org/metapackage/patchutils/packages) `patchutils` version is lagging behind the versions in other distros

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`) **NOTE** `fixcvsdiff` hangs, but that's that's broken in upstreamn in upstream
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
Please re-open this pull request against the staging github branch, since it causes stdenv rebuilds on macOS.

**Comment by samueldr** [comment]
Any updates here? #25154 was closed without (imo) proper resolution.

**Comment by dezgeg** [comment]
Nope, the choices are still:
- Keep a `patchutils_0_3_3` for `fetchpatch`
- Rewrite `fetchpatch` to not use `patchutils`

**Comment by vcunat** [comment]
The first bullet merged: #59422

**Pull request closed without merging**
