### PR TITLE
invidious: 0.20.1-unstable-2024-02-18 -> 0.20.1-unstable-2024-03-08

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

cc @infinisil @sbruder @999eagle 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 296371` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>invidious</li>
  </ul>
</details>

**Review by 999eagle — APPROVED** [review]
Tested on my instance, LGTM

**Comment by a-n-n-a-l-e-e** [comment]
the auto-update script looks like it is failing.
https://r.ryantm.com/log/invidious/2024-03-15.log
```console
o auto update branch exists
Successfully finished processing
cachix "/nix/store/217j2bf0fjal95p8mfglwkyr22f5f6dq-invidious-0.20.1-unstable-2024-03-08"
Received ExitFailure 1 when running
Raw command: /nix/store/fmx804pc0bs1966xq5bb67kark2mww9r-git-2.43.2/bin/git commit -am "invidious: 0.20.1-unstable-2024-02-18 -> 0.20.1-unstable-2024-03-08"
Standard output:

On branch auto-update/invidious
nothing to commit, working tree clean
```

**Comment by GaetanLepage** [comment]
> unrelated to the changes in this commit, but the auto-update script looks like it is failing.

What I do personally regarding invidious is:
```
./pkgs/servers/invidious/update.sh
```

**Comment by 999eagle** [comment]
```
Raw command: /nix/store/fmx804pc0bs1966xq5bb67kark2mww9r-git-2.43.2/bin/git commit -am "invidious: 0.20.1-unstable-2024-02-18 -> 0.20.1-unstable-2024-03-08"
Standard output:

On branch auto-update/invidious
nothing to commit, working tree clean
```

This is probably because the update script itself already commits its changes. We might want to remove that from the update script.

**Comment by a-n-n-a-l-e-e** [comment]
looks like the darwin build is failing.

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 296371` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>invidious</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
> looks like the darwin build is failing.

I am not sure `invidious` is expected to build on darwin...

**Comment by a-n-n-a-l-e-e** [comment]
> > looks like the darwin build is failing.
> 
> I am not sure `invidious` is expected to build on darwin...
https://hydra.nixos.org/job/nixpkgs/trunk/invidious.x86_64-darwin
it is listed https://docs.invidious.io/installation/#macos on the web page.

**Comment by wegank** [comment]
@ofborg build invidious

**Comment by a-n-n-a-l-e-e** [comment]
i see -- so it is the passthru.tests which are failing on darwin.

**Comment by 999eagle** [comment]
Looking at the test logs it seems like for some reason a derivation requires `x86_64-linux` despite testing `x86_64-darwin`. I don't think this is actually related to invidious at all? The tests don't specify anything linux-specific either as far as I can tell. I don't have a darwin machine available to test what exactly is going wrong here.

@GaetanLepage maybe try rebasing onto a current `nixpkgs-unstable` in case this issue has been fixed somewhere in nixpkgs?

**Comment by 999eagle** [comment]
Hmm tests still fail with this. No idea why cross-compilation seems to be involved here, especially for something like `builder.pl`.

```
error: a 'x86_64-linux' with features {} is required to build '/nix/store/jb9c39a65i2s6paj6inwjx7crjywgky9-builder.pl.drv', but I am a 'aarch64-darwin' with features {benchmark, big-parallel, nixos-test}
```

**Comment by wegank** [comment]
> Hmm tests still fail with this. No idea why cross-compilation seems to be involved here, especially for something like `builder.pl`.
> 
> ```
> error: a 'x86_64-linux' with features {} is required to build '/nix/store/jb9c39a65i2s6paj6inwjx7crjywgky9-builder.pl.drv', but I am a 'aarch64-darwin' with features {benchmark, big-parallel, nixos-test}
> ```

Known issue: #294725

**Pull request merged**
