### PR TITLE
borgbackup: 1.1.16 -> 1.1.17

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

https://github.com/borgbackup/borg/blob/1.1.17/docs/changes.rst#version-1117-2021-07-12
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 130051` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>borgbackup</li>
  </ul>
</details>

**Comment by happysalada** [comment]
I couldn't figure out why nixpkgs-review said that borgbackup was broken for darwin.

On another note, it doesn't need to be part of this PR, but how about using `installShellCompletion` instead of the explicit manipulation.

Also it looks like the formatting commit is together with the commit about the tests. Not a big deal, but would have been better if they were separated.

**Comment by mweinelt** [comment]
> I couldn't figure out why nixpkgs-review said that borgbackup was broken for darwin.

Can you build it with `nix-build` and provide a normal log?

> On another note, it doesn't need to be part of this PR, but how about using installShellCompletion instead of the explicit manipulation.

I'd rather leave that for someone else. I changed what I'm comfortable with.

> Also it looks like the formatting commit is together with the commit about the tests. Not a big deal, but would have been better if they were separated.

Can still separate them if you see a reasonable value in it.

**Comment by mweinelt** [comment]
The discussion was still going, not exactly sure why you would just merge when there is an indication about breakage on any platform, when the changes are so extensive.

**Comment by SuperSandro2000** [comment]
What breakage? There was no breakage mentioned.

darwin is not being build by ofborg because some dependency does not support it.

The other two points are nits.

**Comment by mweinelt** [comment]
I was waiting for feedback from @happysalada what the issue with darwin on his end was.

**Comment by happysalada** [comment]
I'm guessing it was a dependency issue. I'm a little bit concerned since at present I definetly have and use borgbackup on darwin. When this is release, I'll have a look at why this breaks. I'll mention in the PR when I have a look (if you don't mind of course)

Don't worry about the formatting thing. It really is a tiny thing, just if you have time next time.

Thank you for doing the PR!

**Comment by happysalada** [comment]
Here is the stacktrace
```
error: Package ‘fuse-3.10.4’ in /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/pkgs/os-specific/linux/fuse/common.nix:86 is not supported on ‘x86_64-darwin’, refusing to evaluate.

       a) To temporarily allow packages that are unsupported for this system, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnsupportedSystem = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnsupportedSystem = true; }
       to ~/.config/nixpkgs/config.nix.


       … while evaluating 'handleEvalIssue'

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/pkgs/stdenv/generic/check-meta.nix:188:38:

          187|
          188|   handleEvalIssue = { meta, attrs }: { reason , errormsg ? "" }:
             |                                      ^
          189|     let

       … from call site

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/pkgs/stdenv/generic/check-meta.nix:302:14:

          301|       handled = if !validity.valid
          302|         then handleEvalIssue { inherit meta attrs; } { inherit (validity) reason errormsg; }
             |              ^
          303|         else true;

       … while evaluating the attribute 'handled'

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/pkgs/stdenv/generic/check-meta.nix:301:7:

          300|       # Throw an error if trying to evaluate an non-valid derivation
          301|       handled = if !validity.valid
             |       ^
          302|         then handleEvalIssue { inherit meta attrs; } { inherit (validity) reason errormsg; }

       … while evaluating the attribute 'buildInputs' of the derivation 'python3.8-pyfuse3-3.2.0'

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/pkgs/stdenv/generic/make-derivation.nix:203:11:

          202|         // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          203|           name =
             |           ^
          204|             let

       … while evaluating the attribute 'out.outPath'

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/lib/customisation.nix:156:13:

          155|             drvPath = assert condition; drv.${outputName}.drvPath;
          156|             outPath = assert condition; drv.${outputName}.outPath;
             |             ^
          157|           };

       … while evaluating the attribute 'propagatedBuildInputs' of the derivation 'borgbackup-1.1.17'

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/pkgs/stdenv/generic/make-derivation.nix:203:11:

          202|         // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          203|           name =
             |           ^
          204|             let

       … while evaluating the attribute 'out.outPath'

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/lib/customisation.nix:156:13:

          155|             drvPath = assert condition; drv.${outputName}.drvPath;
          156|             outPath = assert condition; drv.${outputName}.outPath;
             |             ^
          157|           };

       … while evaluating the attribute 'passAsFile'

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/pkgs/build-support/buildenv/default.nix:77:5:

           76|     # XXX: The size is somewhat arbitrary
           77|     passAsFile = if builtins.stringLength pkgs >= 128*1024 then [ "pkgs" ] else [ ];
             |     ^
           78|   }

       … while evaluating the attribute 'passAsFile' of the derivation 'system-applications'

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/pkgs/stdenv/generic/make-derivation.nix:203:11:

          202|         // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          203|           name =
             |           ^
          204|             let

       … while evaluating the attribute 'value'

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/lib/modules.nix:392:44:

          391|       defnsByName' = byName "config" (module: value:
          392|           [{ inherit (module) file; inherit value; }]
             |                                            ^
          393|         ) configs;

       … while evaluating 'dischargeProperties'

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/lib/modules.nix:609:25:

          608|   */
          609|   dischargeProperties = def:
             |                         ^
          610|     if def._type or "" == "merge" then

       … from call site

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/lib/modules.nix:538:137:

          537|         defs' = concatMap (m:
          538|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          539|         ) defs;

       … while evaluating definitions from `/nix/store/nb2kapr1yf12ra2x3jmdbm2lwfh9c1pr-source/modules/system/applications.nix':

       … while evaluating anonymous lambda

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/lib/modules.nix:537:28:

          536|         # Process mkMerge and mkIf properties.
          537|         defs' = concatMap (m:
             |                            ^
          538|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … from call site

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/lib/modules.nix:537:17:

          536|         # Process mkMerge and mkIf properties.
          537|         defs' = concatMap (m:
             |                 ^
          538|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating the attribute 'values'

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/lib/modules.nix:650:7:

          649|     in {
          650|       values = concatMap (def: if getPrio def == highestPrio then [(strip def)] else []) defs;
             |       ^
          651|       inherit highestPrio;

       … while evaluating the attribute 'values'

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/lib/modules.nix:551:9:

          550|       in {
          551|         values = defs''';
             |         ^
          552|         inherit (defs'') highestPrio;

       … while evaluating the attribute 'mergedValue'

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/lib/modules.nix:557:5:

          556|     # Type-check the remaining definitions, and merge them. Or throw if no definitions.
          557|     mergedValue =
             |     ^
          558|       if isDefined then

       … while evaluating the option `system.activationScripts.applications.text':

       … while evaluating the attribute 'value'

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/lib/modules.nix:525:9:

          524|     in warnDeprecation opt //
          525|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          526|         inherit (res.defsFinal') highestPrio;

       … while evaluating anonymous lambda

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/lib/modules.nix:140:72:

          139|           # For definitions that have an associated option
          140|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          141|

       … from call site

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/lib/attrsets.nix:301:20:

          300|               then recurse (path ++ [name]) value
          301|               else f (path ++ [name]) value;
             |                    ^
          302|         in mapAttrs g set;

       … while evaluating 'g'

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/lib/attrsets.nix:298:19:

          297|           g =
          298|             name: value:
             |                   ^
          299|             if isAttrs value && cond value

       … from call site

       … while evaluating the attribute 'activationScripts.applications.text'

       … while evaluating the attribute 'value'

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/lib/modules.nix:392:44:

          391|       defnsByName' = byName "config" (module: value:
          392|           [{ inherit (module) file; inherit value; }]
             |                                            ^
          393|         ) configs;

       … while evaluating 'dischargeProperties'

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/lib/modules.nix:609:25:

          608|   */
          609|   dischargeProperties = def:
             |                         ^
          610|     if def._type or "" == "merge" then

       … from call site

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/lib/modules.nix:538:137:

          537|         defs' = concatMap (m:
          538|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          539|         ) defs;

       … while evaluating definitions from `/nix/store/nb2kapr1yf12ra2x3jmdbm2lwfh9c1pr-source/modules/system/activation-scripts.nix':

       … while evaluating anonymous lambda

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/lib/modules.nix:537:28:

          536|         # Process mkMerge and mkIf properties.
          537|         defs' = concatMap (m:
             |                            ^
          538|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … from call site

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/lib/modules.nix:537:17:

          536|         # Process mkMerge and mkIf properties.
          537|         defs' = concatMap (m:
             |                 ^
          538|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating the attribute 'values'

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/lib/modules.nix:650:7:

          649|     in {
          650|       values = concatMap (def: if getPrio def == highestPrio then [(strip def)] else []) defs;
             |       ^
          651|       inherit highestPrio;

       … while evaluating the attribute 'values'

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/lib/modules.nix:551:9:

          550|       in {
          551|         values = defs''';
             |         ^
          552|         inherit (defs'') highestPrio;

       … while evaluating the attribute 'mergedValue'

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/lib/modules.nix:557:5:

          556|     # Type-check the remaining definitions, and merge them. Or throw if no definitions.
          557|     mergedValue =
             |     ^
          558|       if isDefined then

       … while evaluating the option `system.activationScripts.script.text':

       … while evaluating the attribute 'value'

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/lib/modules.nix:525:9:

          524|     in warnDeprecation opt //
          525|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          526|         inherit (res.defsFinal') highestPrio;

       … while evaluating anonymous lambda

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/lib/modules.nix:140:72:

          139|           # For definitions that have an associated option
          140|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          141|

       … from call site

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/lib/attrsets.nix:301:20:

          300|               then recurse (path ++ [name]) value
          301|               else f (path ++ [name]) value;
             |                    ^
          302|         in mapAttrs g set;

       … while evaluating 'g'

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/lib/attrsets.nix:298:19:

          297|           g =
          298|             name: value:
             |                   ^
          299|             if isAttrs value && cond value

       … from call site

       … while evaluating the attribute 'activationScripts.script.text'

       … while evaluating the attribute 'activationScript' of the derivation 'darwin-system-21.11.20210713.dac74fe+darwin4.007d700'

       at /nix/store/xni1qpy1nsrpmjfhjz71j1gg4chspasg-source/pkgs/stdenv/generic/make-derivation.nix:203:11:

          202|         // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          203|           name =
             |           ^
          204|             let
```

It seems to be the llfuse dependency.
I am checking what has changed. It doesn't seem to be a borg PR.

**Comment by mweinelt** [comment]
Actually `pyfuse3` is introduced in this pr. We can make it conditional I guess.

**Comment by happysalada** [comment]
Trying to rebuild, it needs to rebuild a bunch of things.
The build is starting. I'll update when it finishes.

**Comment by mweinelt** [comment]
I already made the change in #130171 and ofBorg said it was fine.

**Comment by happysalada** [comment]
Cool, thank you!
I'm confirming by running nixpkgs-review, I'm sure it will run fine.

**Pull request merged**
