### PR TITLE
oauth2_proxy: 20180325 -> 3.2.0

### PR DESCRIPTION
**Pull request by nyanloutre**
###### Motivation for this change
after bitly repo was frozen pusher is now the official hard fork
https://github.com/bitly/oauth2_proxy/issues/628

the module will need more testing to see if anything is broken

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by marsam — CHANGES_REQUESTED** [review]
looks like it uses dep to manage its dependencies, can you update deps.nix with https://github.com/nixcloud/dep2nix. Besides that, LGTM

**Comment by nyanloutre** [comment]
@marsam done

**Review by marsam — APPROVED** [review]

**Comment by marsam** [comment]
@GrahamcOfBorg build oauth2_proxy

**Comment by marsam** [comment]
@nyanloutre thanks!

**Pull request merged**
