### PR TITLE
mesa_drivers_glvnd: init

### PR DESCRIPTION
**Pull request by ghost**
###### Motivation for this change

See also https://github.com/NixOS/nixpkgs/pull/34461

This allows nothing more that co-existing of mesa and proprietary drivers in same /run/opengl-driver/ prefix e.g. for Nvidia Optimus setups. Then correct GL drivers are picked dynamically depending on what X/DRI drivers are used.

cc maintainers @eduarrrd @vcunat 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by avnik** [comment]
I feel, better to have `libglvnd` as "default" `libGL` provider, used to build all software (it have fewer dependencies, than `mesa-nonglu`, so will be build faster and earlier, so more packages would be built on CI).  

Real backend can still be dispatched via `/run/opengl-driver` symlink. (Backend can be `buildEnv` of libglvnd enabled mesa and other libglvnd capable implementations. In worst cases user can force real `libGL` from any non-glvnd compatible package, including old-style mesa builds).

**Comment by gnidorah** [comment]
@avnik 
> I feel, better to have libglvnd as "default" libGL provider, used to build all software (it have fewer dependencies, than mesa-nonglu, so will be build faster and earlier, so more packages would be built on CI).

We discussed this on IRC already:
> vcunat: ... but it's difficult to find time for larger changes (or more risky ones).
> gchristensen: it still requires holistic thinking about how it interacts with the rest of the systems

So not now, sorry. The next step is also drop that `LD_LIBRARY_PATH=/run/opengl-driver/lib` hack, once all drivers are ready to by picked by libglvnd.

**Comment by avnik** [comment]
On Mon, Jan 29, 2018 at 06:45:40AM +0000, gnidorah wrote:

@gnidorah
> We discussed this on IRC already:
> > vcunat: ... but it's difficult to find time for larger changes (or more risky ones).
> > gchristensen: it still requires holistic thinking about how it interacts with the rest of the systems
> 
> So not now, sorry. The next step is also drop that `LD_LIBRARY_PATH=/run/opengl-driver/lib` hack, once all drivers are ready to by picked by libglvnd.
>

I seen discussion, but decide answer here, because I seen it few hours
after it happens.

I would like to drop `LD_LIBRARY_PATH=/run/opengl-driver/lib` hack as
well, but libglvnd still need something like this, to found their
`libGL_$VENDOR.so.0`. But it would be nice, to move this hack to
dedicated variable like LIBGL_VENDOR_PATH.

Anyway, I like to support move into this direction, so I would like to
join efffort, and working on small steps.

One of following steps should be make default aliases `libGL` and
`libGLU` (for mesa-nonglu and mesa respectively), and replace direct
references on mesa everywhere with `libGL`/`libGLU` (this shouldn't
cause any hash changes).

Then we can one time replace `libGL` with `libglvnd` as default libGL
provider. (One reason, why I not tried it yet -- it take 2-3 days to full
rebuild).

**Comment by coreyoconnor** [comment]
I'm definitely interested in replacing direct mesa references everywhere. With that in mind I started testing this. 

I've applied this patch and done the full rebuild of a Plasma 5 desktop:

* (merge) https://github.com/coreyoconnor/nixpkgs/commit/1971460cebeaf99727182d727c656b52badc9dd3
* (xserver and gl config for desktop) https://github.com/coreyoconnor/nix_configs/blob/master/computers/grr/configuration.nix#L100

xserver starts, and reports the expected GLX, but Plasma 5 does not:

~~~
Jan 29 09:39:09 grr xsession[29061]: Could not initialize GLX
Jan 29 09:39:09 grr xsession[29061]: CreateNotify: 12582915
Jan 29 09:39:09 grr xsession[29061]: libGL error: unable to load driver: swrast_dri.so
Jan 29 09:39:09 grr xsession[29061]: libGL error: failed to load driver: swrast
~~~

I think I've seen that error before but can't recall what the fix was. That said, the Plasma 5 desktop was working (with HW opengl) prior to this patch and enable of GLVND.

Note this config does not use primus.

Checking the `/var/run/opengl-driver/lib` directory: NVidia libs are present but no libGL.so.

**Comment by coreyoconnor** [comment]
I think the issue with NVidia with glvnd but no optimus is related to this logic here:

* https://github.com/NixOS/nixpkgs/pull/34282/commits/71ede8a7c1458ccf267f06c0c5876a2f89eaf328#diff-eba4fea93f8708e0012684b9c398b1e3R74

I was able to restore OpenGL by applying this hack of a patch:

* https://github.com/coreyoconnor/nixpkgs/commit/07b037ee9b0024df9285bc582b6aa95de91c7e64

**Comment by gnidorah** [comment]
@avnik Unfortunately I'm not in position to implement that, but I would like to be a tester :smiley: And we need someone from NixOS team with interest to support and approve that change.

@coreyoconnor Fixed, thank you!

**Comment by coreyoconnor** [comment]
@gnidorah Thanks! No issues with current commits.

**Pull request closed without merging**
