### PR TITLE
ocamlPackages.dune: rename as dune_1 and disable for OCaml ≥ 4.12

### LINKED ISSUE #114421: ocamlPackages_4_12.dune is broken
**Describe the bug**

`ocamlPackages_4_12.dune` (dune-1.11.4 with ocaml-4.12.0) is broken due to [this bug](https://github.com/ocaml/dune/issues/3583).
This has been [fixed](https://github.com/ocaml/dune/pull/3585/files) in dune2 but not dune1.

Should either update all packages to use dune2,
and/or try patching dune1 with the above fix.

**To Reproduce**

```
> nix build 'nixpkgs#ocaml-ng.ocamlPackages_4_12.dune'
warning: ignoring the user-specified setting 'experimental-features', because it is a restricted setting and you are not a trusted user
[1/2/5 built, 21.2 MiB DL] building ocaml-4.12.0 (buildPhase): ./boot/ocamlrun ./ocamlopt -g -nostdlib -I stdlib -I otherlibs/dynlink -strict-sequence -principal -absname -w +a-4-9-40-41-42-44-45-48-66 -warn-error A -bin-annot -safe-string -strict-formats -I utils -I parsing -I typing -I bytecomp -I file_formats -I la[1/2/5 built, 21.2 MiB DL] building ocaml-4.12.0 (buildPhase): ./boot/ocamlrun ./ocamlopt -g -nostdlib -I stdlib -I otherlibs/dynlink -strict-sequence -principal -absname -w +a-4-9-40-41-42-44-45-48-66 -warn-error A -bin-annot -safe-string -strict-formats -I utils -I parsing -I typing -I bytecomp -I file_formats -I labuilder for '/nix/store/w0kqyczdkghfvi51cyfn5gqfinr8d4if-dune-1.11.4.drv' failed with exit code 2; last 10 log lines:
  29 |   }
  Error: Some record fields are undefined: forced_major_collections
  -> required by src/catapult/.catapult.objs/native/catapult.cmx
  -> required by src/.dune.objs/native/dune__Action.cmx
  -> required by bin/.main.objs/native/main.cmx
  -> required by bin/main.a
  -> required by bin/main/main_dune.exe
  -> required by install bin/dune
  -> required by dune.install
  make: *** [Makefile:12: release] Error 1
error: --- Error 
build of '/nix/store/w0kqyczdkghfvi51cyfn5gqfinr8d4if-dune-1.11.4.drv' failed
```

**Notify maintainers**

@vbgl @Zimmi48 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by vbgl**
###### Motivation for this change

Fixes #114421.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 114478` at f9441389 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li><a href="https://gist.github.com/93857d1c8f59316cae06b55ab1e676a1">dune_1</a></li></li>
  </ul>
</details>

**Comment by Zimmi48** [comment]
What would be the impact of making `dune_2` the default in `dunePackage`?

**Comment by anmonteiro** [comment]
FWIW I've been running dune_2 exclusively in my overlays and, apart from packages that still have `jbuild` files, most failing packages can be fixed by adding `dune-configurator` to `buildInputs`.

**Comment by tg-x** [comment]
dune_2 would have to be the default at least for 4.12, otherwise many packages wouldn't build anymore that support dune2 but don't have useDune2=true set

**Pull request merged**
