### PR TITLE
Use symlinkJoin for wrappers

### PR DESCRIPTION
**Pull request by abbradar**
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

This extends `symlinkJoin` function to accept a set with several additional arguments, and uses that to refactor many buildEnv-and-wrap-style wrappers in the tree. Also fixes `dwarf-therapist`.

cc @magnetophon @avnik @ericsagnes

### CODE REVIEW

**Comment by abbradar** [comment]
I've tested manually all the wrappers and checked our their contents -- they seem to behave the same. As this also fixes a package and seems a good cleanup, let's merge. Full disclosure: this is the last package I need to fix before all packages in my configuration finally build ^_^.

**Comment by cstrahan** [comment]
Ooh, this should be useful in the Haskell packaging, where we currently use `buildEnv`; thanks!

**Comment by edolstra** [comment]
Why is `symlinkJoin` better than `buildEnv`?

**Comment by abbradar** [comment]
Because of a long-standing issue https://github.com/NixOS/nixpkgs/issues/4621 -- `symlinkJoin` happens to use `lndir` which does create all the directories, and is sufficient for needs of such wrappers. The `dwarf-therapist` package fix is just a side effect (see #14937).

**Comment by cstrahan** [comment]
@edolstra My understanding is that `symlinkJoin` will always create the sub directories, rather than (selectively) symlinking. Symlinking the entire directories causes problems where we want to create the symlink forest, and then add a file to the tree -- which wouldn't be possible (without nasty workarounds) due to the symlinked folders pointing into the immutable nix store.

**Comment by vcunat** [comment]
> Symlinking the entire directories causes problems where we want to create the symlink forest, and then add a file to the tree [...]

You don't need nasty work-arounds: you just create the files to be added in a separate derivation (e.g. `runCommand`) and add it to the paths.

**Comment by abbradar** [comment]
Hm, this won't work because those wrappers often need to refer to `$out` of `buildEnv`, but I'm not sure if this can't be solved somehow...

**Comment by vcunat** [comment]
Ah, I see. You can always hack around it, e.g. only create empty dirs in that `runCommand`, but `symlinkJoin` is probably a nicer way for such cases.

A couple months ago I also needed to convert symlinks to directories for a service that was locating configuration relative to detected executable location.

**Pull request merged**
