### PR TITLE
kernel: fix tpm_crb failed

### LINKED ISSUE #250166: tpm_crb: probe of MSFT0101:00 failed with error 378
### Describe the bug
I use tpm + luks, but recently when the kernel updating to 6.4.11, the `tpm_crb` can't find `tpm` devices. 
And, if I switch to old kernel like 6.1, it can't work too.

### Steps To Reproduce
1. Use the latest unstable
2.
```nix
  boot = {
    kernelPackages = pkgs.linuxPackages_latest;
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "ahci"
        "nvme"
        "usbhid"
        "usb_storage"
        "sd_mod"
        "tpm"
        "tpm_tis"
        "tpm_crb"
      ];
      systemd.enable = true;
    };

    tmp.useTmpfs = true;
  };
```

### Expected behavior
`tpm` work correctly.

### Screenshots
图片
图片

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.11, NixOS, 23.11 (Tapir), 23.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(yufei): `""`
 - nixpkgs: `/nix/store/5mj1vfslaf052b8s9nnbz31fb2l1qwdi-source`
```

### PR DESCRIPTION
**Pull request by Cryolitia**
## Description of changes

bugzilla: https://bugzilla.kernel.org/show_bug.cgi?id=217804
fix https://github.com/NixOS/nixpkgs/issues/250166

It works on my machine with i7-9750H, otherwaise I couldn't sign the commit. ^_^

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by panda2134** [comment]
I can confirm this works on my i9-13900k setup with NixOS unstable.

**Comment by alyssais** [comment]
[v2](https://lore.kernel.org/stable/20230821140230.1168-1-mario.limonciello@amd.com/) of this patch was posted today.

**Comment by Cryolitia** [comment]
Update to patch [v2](https://lore.kernel.org/stable/20230821140230.1168-1-mario.limonciello@amd.com/)

Works on my machine with i7-9750H, not tests for AMD because of no device.

thx for telling me that ^_^

**Comment by alyssais** [comment]
I think we need to wait until a patch is actually accepted, because since then there have been another three versions of a different [patch](https://lore.kernel.org/lkml/20230822231510.2263255-1-jarkko@kernel.org/). It seems like there's a risk of breaking other setups by applying a patch that fixes this particular issue but hasn't been checked for what it does on other platforms.

**Comment by Cryolitia** [comment]
patch was accepted by Linus

https://github.com/torvalds/linux/commit/8f7f35e5aa6f2182eabcfa3abef4d898a48e9aa8

**Pull request closed without merging**
