### PR TITLE
Cinnamon 6.4

### PR DESCRIPTION
**Pull request by bobby285271**
https://github.com/bobby285271/what-changed/blob/master/003-cinnamon.md

## Things done

- Built on platform(s)
  - [x] x86_64-linux
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

cc @mkg20001

### CODE REVIEW

**Comment by bobby285271** [comment]
@ofborg test cinnamon cinnamon-wayland

**Comment by mkg20001** [comment]
I have tested this on my machine, Login works, seems to work so far. Anything in particular I should test or is this enough?

**Comment by bobby285271** [comment]
I think this upgrade is mostly related to:

1. The new Cinnamon built-in theme (though Mint still defaults to Mint-Y):



2. Mass dialog migration (from GTK dialog to Clutter dialog):




3. Night light (https://github.com/linuxmint/cinnamon-desktop/commit/913198430f27852544f9443a250421168d3d4466 & https://github.com/linuxmint/cinnamon-settings-daemon/commit/8c5b745c65bfd30f2aabe00e040df2905b1ba979):



For packaging changes, other than https://github.com/linuxmint/cinnamon-screensaver/pull/456/commits/a3926237f1826ef78b68b3cbede55fda380d34ff I don't aware of major changes.

**Comment by mkg20001** [comment]
night light works, new dialogs work but the run command dialog looks weird under acr-dark theme. But I think that's a theme issue.

image

**Comment by bobby285271** [comment]
Yeah this will be a theme issue. I assume the `padding-top` is not good here?

Since Arc does not have explicit support for Cinnamon >= 5.6, per [`meson.build`](https://github.com/jnsh/arc-theme/blob/3fd4786f45ce18f06eb8c2efeee6510bb45fabe8/common/cinnamon/meson.build#L25) you can temporarily workaround the issue by editing `common/cinnamon/5.4/sass/_common.scss`:

```diff
diff --git a/common/cinnamon/5.4/sass/_common.scss b/common/cinnamon/5.4/sass/_common.scss
index 65468a4a..7ed4414e 100644
--- a/common/cinnamon/5.4/sass/_common.scss
+++ b/common/cinnamon/5.4/sass/_common.scss
@@ -1141,7 +1141,7 @@ StScrollBar {
 // Run dialog
 //
 .run-dialog {
-  padding: 0px 15px 10px 15px;
+  padding: 10px 15px 10px 15px;
   border-image: url("common-assets/misc/bg.svg") 9 9 9 9;
 
   > * { padding: 0; }
```

(I have no idea what a proper value will be, you can try adjust the numbers and find a good value). After updating the theme restart Cinnamon.

**Review by getchoo — APPROVED** [review]
I'll test on an actual machine and comment again if I have the time, but everything builds and diff LGTM. Great work!

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 359855`

---
### `aarch64-linux`
<details>
  <summary>:fast_forward: 2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 26 packages built:</summary>
  <ul>
    <li>arc-theme</li>
    <li>cinnamon-common</li>
    <li>cinnamon-control-center</li>
    <li>cinnamon-desktop</li>
    <li>cinnamon-desktop.dev</li>
    <li>cinnamon-gsettings-overrides</li>
    <li>cinnamon-menus</li>
    <li>cinnamon-screensaver</li>
    <li>cinnamon-session</li>
    <li>cinnamon-settings-daemon</li>
    <li>cinnamon-settings-daemon.dev</li>
    <li>cinnamon-translations</li>
    <li>cjs</li>
    <li>cjs.dev</li>
    <li>muffin</li>
    <li>muffin.dev</li>
    <li>muffin.man</li>
    <li>nemo</li>
    <li>nemo-emblems</li>
    <li>nemo-emblems.dist</li>
    <li>nemo-fileroller</li>
    <li>nemo-python</li>
    <li>nemo-with-extensions</li>
    <li>nemo.dev</li>
    <li>xdg-desktop-portal-xapp</li>
    <li>xviewer</li>
  </ul>
</details>

**Comment by bobby285271** [comment]
> I'll test on an actual machine

No rush but I will wait for your testing :-)

**Review by getchoo — APPROVED** [review]
Played around with some XApps and themes. All seems well :)

**Comment by getchoo** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 359855`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 1 package blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 26 packages built:</summary>
  <ul>
    <li>arc-theme</li>
    <li>cinnamon-common</li>
    <li>cinnamon-control-center</li>
    <li>cinnamon-desktop</li>
    <li>cinnamon-desktop.dev</li>
    <li>cinnamon-gsettings-overrides</li>
    <li>cinnamon-menus</li>
    <li>cinnamon-screensaver</li>
    <li>cinnamon-session</li>
    <li>cinnamon-settings-daemon</li>
    <li>cinnamon-settings-daemon.dev</li>
    <li>cinnamon-translations</li>
    <li>cjs</li>
    <li>cjs.dev</li>
    <li>muffin</li>
    <li>muffin.dev</li>
    <li>muffin.man</li>
    <li>nemo</li>
    <li>nemo-emblems</li>
    <li>nemo-emblems.dist</li>
    <li>nemo-fileroller</li>
    <li>nemo-python</li>
    <li>nemo-with-extensions</li>
    <li>nemo.dev</li>
    <li>xdg-desktop-portal-xapp</li>
    <li>xviewer</li>
  </ul>
</details>

**Review by mkg20001 — APPROVED** [review]

**Comment by bobby285271** [comment]
Thanks for testing, let's merge then.

**Pull request merged**
