### PR TITLE
staging-next 2023-06-02

### PR DESCRIPTION
**Pull request by vcunat**
##### Helpful links

- workflow docs: https://nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy
- important jobs:
  https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
  https://hydra.nixos.org/job/nixos/staging-next-small/tested
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next
  https://hydra.nixos.org/jobset/nixos/staging-next-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/233944
- - - 
##### Mass breakages
(will be edited based on progress)
- [x] `python3Packages.apsw`  [below](#issuecomment-1575591828)

### CODE REVIEW

**Comment by willcohen** [comment]
#235624 should unbreak emscripten rebuilds on `staging-next`.

**Comment by vcunat** [comment]
- [ ] `python3Packages.apsw` fails tests, probably after sqlite update (all python versions, all platforms)
  example log: https://hydra.nixos.org/build/222675808/nixlog/3/tail
  /cc maintainer @gador
  Report says that a couple hundred builds depend on this.

**Comment by gador** [comment]
> - [ ] `python3Packages.apsw` fails tests, probably after sqlite update (all python versions, all platforms)
>   example log: https://hydra.nixos.org/build/222675808/nixlog/3/tail
>   /cc maintainer @gador
>   Report says that a couple hundred builds depend on this.

Hi, yes I already have a PR ready #233027

**Comment by vcunat** [comment]
Thanks.  I should've searched github before asking.

**Comment by vcunat** [comment]
Notable but not really a mass failure:
- [ ] `po4a` regressed in some tests on *-darwin: https://hydra.nixos.org/build/222552892
  (a few retries, also locally)
  I tried to update it, but then it wouldn't pass tests on x86_64-linux.  Review estimates 81 builds depending on this.  (no `meta.maintainers`)

**Comment by spikespaz** [comment]
Where should I be reporting build failures? It seems that the following are broken:
```
/nix/store/dmqqm6x6g1nj58cw5sl63qkdhjmisspw-glew-x86_64-unknown-linux-gnu-1.10.0.drv
/nix/store/r4pnyfmy1qf0lnqk7k54rdnwfrz7sf4q-SDL_ttf-x86_64-unknown-linux-gnu-2.0.11.drv
/nix/store/m0wz8dn1145l8cgds2fl78z5ymqsq9bi-libIDL-x86_64-unknown-linux-gnu-0.8.14.drv
/nix/store/qc5mjr2i0lmzd6rbl0sk85gfkrx59x2q-libgdiplus-x86_64-unknown-linux-gnu-6.0.5.drv
/nix/store/sz7a6fi9lbvnrhczs5m5x39vh9f7mchf-timidity-x86_64-unknown-linux-gnu-2.15.0.drv
/nix/store/nkjs8jjdf4iw42immjq23sz1bdf21yyf-rustfmt-nightly-x86_64-unknown-linux-gnu-1.69.0.drv
```
I would also like to see if the above derivations (exact same hashes) also fail on Hydra.

**Comment by vcunat** [comment]
I don't know; cross-compilations aren't top-tier targets for us, especially packages that aren't very significant (basic build toolchain).  Some stuff gets built on https://hydra.nixos.org/jobset/nixpkgs/cross-trunk but it's only catching up to this merge now and I don't think your packages are there.

Generally, if you find particular pull request that broke something, it's good to at least mention on it or link.  (I mean, almost all commits in `staging-next*` PRs were originally merged in some small PR.)  Otherwise... opening issues is an option, a cross-compilation label exists, also [chat](https://matrix.to/#/#cross-compiling:nixos.org), but I don't deal with cross stuff normally so perhaps someone else can advise better.

For reading hydra logs for particular derivations, be it failing or succeeding, I'd recommend `nix log -f. bash` (example).

**Comment by vcunat** [comment]
The `x86_64-unknown-linux-gnu` suffixes are certainly suspicious.  Normal non-cross builds do not have them.

**Comment by spikespaz** [comment]
Indeed, it is suspicious. Is it possible that whatever mechanism bypasses `impure.nix` also specifies `null` for `crossPlatform`, causing [whatever this is](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/top-level/default.nix#L64) (what is that?) to do a thing?

I haven't bothered to investigate further because it was my understanding that cross-compiling for the same `hostPlatform` and `buildPlatform` should be identical to not cross-compiling at all. I was under the impression that this is important to Nixpkgs. Am I mistaken?

**Comment by spikespaz** [comment]
Who would I ping to help me investigate this?

**Comment by vcunat** [comment]
Say, the chat I linked above: https://matrix.to/#/#cross-compiling:nixos.org

**Pull request merged**
