### PR TITLE
llvmPackages_4: 4.0.0 -> 4.0.1

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

Minor update.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dtzWill** [comment]
Running nox-review presently :).

**Comment by copumpkin** [comment]
Given that this is a mass darwin rebuild, I'd probably send it to staging. Otherwise looks good.

**Comment by vcunat** [comment]
Uh, I see no announcement on ML or mention on llvm.org yet :-)  If `llvmPackages` themselves build OK after this, merging to staging should be a no-brainer.  (better have a look at official NEWS as well before merging to master, though)

**Comment by dtzWill** [comment]
Hmm, don't currently have the resources to complete the nox-review myself in a timely manner, sorry :).

And the release is finalized but indeed no official announcement yet.

The release docs are here: http://releases.llvm.org/4.0.1/docs/ReleaseNotes.html
although it doesn't mention anything about what's fixed in the point release (indeed it refers to itself as "4.0.0"), but release management is hard.

As for determining what's changed I think the best to be done is bouncing through the commits on the release branches, for example [LLVM 4.0 commits](https://github.com/llvm-mirror/llvm/commits/release_40), but we'll see once the release is mentioned on the ML/website :).

**Comment by dtzWill** [comment]
@vcunat If you look through llvm-commits@ ([this week's threads](http://lists.llvm.org/pipermail/llvm-commits/Week-of-Mon-20170626/thread.html), you'll see it's not as premature is it might seem :).

Anyway, hopefully no big deal just need to rebuild all the things :grin:

**Comment by vcunat** [comment]
That doc seems just for 3.9.x -> 4.0.0 update.  No need to finish nox-review; it would be thousands of packages just on `x86_64-linux`.  Trying to build Darwin stdenv would actually give some confidence bump, but I'll chance a merge if noone volunteers for that soon.  (Hydra's rebuilding staging heavily ATM and I'd prefer to wait until the next iteration anyway.)

**Review by 0xABAB — APPROVED** [review]

**Comment by LnL7** [comment]
I'll do a build of the stdenv and some basic packages.

**Review by LnL7 — APPROVED** [review]

**Comment by LnL7** [comment]
Forgot to report back, everything looks ok on darwin.

**Review by vcunat — APPROVED** [review]
Seems OK.

**Comment by vcunat** [comment]
Staged.

**Comment by dtzWill** [comment]
It's officially mentioned on the website now, haha: http://llvm.org/

[Bugged'em](http://lists.llvm.org/pipermail/llvm-commits/Week-of-Mon-20170703/467592.html) after it was pointed out that it didn't /look/ officially released yet :innocent:.  No hard feelings-- it's a volunteer job and I'm sure we can sympathize with how challenging release management can be!

**Comment by vcunat** [comment]
Even the announcement mail was about a week after this PR was submitted...

**Pull request merged**
