### PR TITLE
thunderbirdPackages.thunderbird-102: set knownVulnerabilities

### PR DESCRIPTION
**Pull request by vcunat**
_Usual checklist doesn't apply here._

### CODE REVIEW

**Comment by alyssais** [comment]
Any reason we don't just drop it?

**Comment by vcunat** [comment]
I'm not aware.  I guess we just do it now?

**Comment by alyssais** [comment]
Does that count as a breaking change?

**Comment by vcunat** [comment]
Anyway, I opened PR  #308820

**Pull request merged**
