### PR TITLE
conmon: 2.0.22 -> 2.0.23

### PR DESCRIPTION
**Pull request by saschagrunert**
###### Motivation for this change
Update conmon to the latest version.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by saschagrunert** [comment]
cc @NixOS/podman

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109367` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
4 packages built:
</summary>
<ul>
<li>buildah</li>
<li>conmon</li>
<li>cri-o</li>
<li>podman</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
Tests are failing.

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 109367 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>4 packages built:</summary>  <ul>    <li>buildah</li>    <li>conmon</li>    <li>cri-o</li>    <li>podman</li>  </ul></details>

**Comment by zowoq** [comment]
> Tests are failing.

I don't understand why this was merged with a broken test when the test isn't broken on master @jonringer?

**Comment by zowoq** [comment]
https://github.com/containers/conmon/releases/tag/v2.0.23



Don't know what upstream is doing but `2.0.24` doesn't exist so I'll revert this for now.

**Comment by zowoq** [comment]
Reverted in https://github.com/NixOS/nixpkgs/commit/8a4b39330f80143b313bde8d88b6cc1264b31d18.

**Comment by jonringer** [comment]
sounds good, but the podman test was failing before this PR

**Comment by zowoq** [comment]
> the podman test was failing before this PR

It doesn't seem to be broken, it passes for me.

**Comment by jonringer** [comment]
I checked out the wrong commit, you're right it is a new failure.

Really need enable `nixpkgs-review` to run tests on affected packages

**Comment by jonringer** [comment]
Yes, this should not have been merged. I apologize

**Comment by saschagrunert** [comment]
Ah, …alright so let’s wait for the next release. 🤭

**Comment by zowoq** [comment]
PR for `2.0.24`: https://github.com/NixOS/nixpkgs/pull/109400

**Pull request merged**
