### PR TITLE
aerc: 0.1.4 -> 0.2.1; add ncurses to PATH

### PR DESCRIPTION
**Pull request by AluisioASG**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

aerc needs infocmp when running in terminals not in its database, hence the ncurses dependency.

### CODE REVIEW

**Comment by kalbasit** [comment]
@GrahamcOfBorg build aerc

**Review by mmahut — APPROVED** [review]
- [X] reviewed the diff and commit messages
- [X] made sure ofBorg build succeeded for all applicable platforms
- [X] run nix-review without any failures
- [X] run and tested the binaries

**Comment by aanderse** [comment]
What binary from `ncurses.dev` is this program using?

**Comment by AluisioASG** [comment]
@aanderse `infocmp`, which aerc's TUI library [uses](https://github.com/gdamore/tcell/blob/ca8fb5bcc94b37b52eb8508d3ed8753e4762e83f/terminfo/dynamic/dynamic.go#L15-L20) to convert terminfo files to its own format.

**Comment by aanderse** [comment]
Thanks @AluisioASG!

Looks straight forward enough to me. Merging based on the good word of @mmahut.

**Pull request merged**
