### PR TITLE
[staging] python3Packages.virtualenv: 20.2.1 -> 20.3.1

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 20.3.1

Change log: https://virtualenv.pypa.io/en/latest/changelog.html#bugfixes-20-3-1

This PR also enables the tests.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
@GrahamcOfBorg build python3Packages.tox

**Review by jonringer — APPROVED** [review]
diff LGTM

**Comment by dotlambda** [comment]
Why was this merged into master?
`python37Packages.virtualenv` fails to build now.
We should revert.

**Comment by dotlambda** [comment]
The problem on python 3.7 is that xonsh is not packaged as a module (`pythonPackages.xonsh`) does not exist and is therefore not picked up by the interpreter. I'm not sure if xonsh is supposed to be packaged as a module too.

**Comment by jonringer** [comment]
-_-... I saw that `[staging]` title and didnt' even check the target branch

**Comment by jonringer** [comment]
reverted in https://github.com/NixOS/nixpkgs/commit/c98d6ce51f1ec9bcb2ce49d8210f3ce51dd7b29a https://github.com/NixOS/nixpkgs/commit/135a14fa45de3de39dc97336ab7f15fc442451dc

**Comment by jonringer** [comment]
the python37 fix is easy enough, as that's not built by hydra, just need to pin the version for python<3.8

**Comment by fabaff** [comment]
I'm too slow...in #109994 I got the error:

```bash
error: --- Error ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix
builder for '/nix/store/3han1yi5k9xlnpggxmikdfksn6bjncdw-python3.7-virtualenv-20.3.1.drv' failed with exit code 1; last 10 log lines:
  SKIPPED [1] tests/unit/activation/conftest.py:249: PowerShell(
  version=FileNotFoundError(2, "No such file or directory: 'pwsh'"),
  creator=CPython3Posix(dest=/build/pytest-of-nixbld/pytest-0/activation-tester-env3/e-$ èрт🚒♞中片-j, clear=False, no_vcs_ignore=False, global=False),
  interpreter=PythonInfo(spec=CPython3.7.9.final.0-64, exe=/nix/store/q5hdqw6bcp3mfzg8l9m2qhra3y892xwm-python3-3.7.9/bin/python3.7, platform=linux, version='3.7.9 (default, Aug 15 2020, 06:36:35) \n[GCC 10.2.0]', encoding_fs_io=utf-8-UTF-8)) is not available due [Errno 2] No such file or directory: 'pwsh': 'pwsh'
  SKIPPED [1] tests/integration/test_run_int.py: need --int option to run
  SKIPPED [1] tests/integration/test_zipapp.py: need --int option to run
  SKIPPED [2] tests/integration/test_zipapp.py:95: need --int option to run
  FAILED tests/unit/activation/test_xonsh.py::test_xonsh[with_prompt] - IndexEr...
  FAILED tests/unit/activation/test_xonsh.py::test_xonsh[no_prompt] - IndexErro...
  ===== 2 failed, 209 passed, 15 skipped, 2 deselected, 1 warning in 17.42s ======
```

**Comment by dotlambda** [comment]
> the python37 fix is easy enough, as that's not built by hydra, just need to pin the version for python<3.8

If we use `xonsh.override { python3Packages = python.pkgs }` in `virtualenv`, that would only work for Python versions for which we can build xonsh, which excludes Python 2.7.
Hence I suggest simply adding `disabledTests = [ "test_xonsh" ];` and removing `xonsh` from `checkInputs`.

**Pull request merged**
