### PR TITLE
nordic: make sddm a separate output

### PR DESCRIPTION
**Pull request by romildo**
## Description of changes

It brings some kde stuff into the environment, and that may not be desirable when one does not need it.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lucasew** [comment]
The idea is very good, but I think it needs some kind of standarization. That way all SDDM themes can be exported to the sddm output and if sddm is enabled it can add this output to `environment.extraOutputsToInstall`. This same approach could also be done in icon packs.

I think `theme_sddm` is a better name tho, it's a little less ambiguous.

**Comment by lucasew** [comment]
Result of `nixpkgs-review pr 263855` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>nordic</li>
    <li>nordic.sddm</li>
  </ul>
</details>

**Comment by romildo** [comment]
> The idea is very good, but I think it needs some kind of standarization. That way all SDDM themes can be exported to the sddm output and if sddm is enabled it can add this output to `environment.extraOutputsToInstall`. This same approach could also be done in icon packs and other theming stuff.

I have not thought about the idea of automatically installing the sddm theme provided at the `sddm` output for every installed package which have them, when the `sddm` module is enabled. At least that is not the goal of this PR. But it may be a good idea for another PR later.

> I think `theme_sddm` is a better name tho, it's a little less ambiguous.

I think that the output name `sddm` may be good enough, because it is already part of a theme package.

What you are proposing is something in the lines of having several other outputs, like the following?

``` nix
nordic.aurorae
nordic.cinnamon
nordic.color-schemes
nordic.gnome-shell
nordic.gtk2
nordic.gtk3
nordic.gtk4
nordic.icons
nordic.konsole
nordic.kvantum
nordic.metacity
nordic.plasma
nordic.sddm
nordic.wallpapers
nordic.xfwm4
```
I am not sure if prefixing all those outputs with `theme_` would be necessary.

Outputs like those in a theme package would allow a streamlined installation, as one could choose exactly which parts of a theme is really needed.

In this example, I do not know what to do with the `index.theme` and `assets` entries of the GTK based themes.

**Comment by lucasew** [comment]
> What you are proposing is something in the lines of having several other outputs, like the following?
> 
> ```nix
> nordic.aurorae
> nordic.cinnamon
> nordic.color-schemes
> nordic.gnome-shell
> nordic.gtk2
> nordic.gtk3
> nordic.gtk4
> nordic.icons
> nordic.konsole
> nordic.kvantum
> nordic.metacity
> nordic.plasma
> nordic.sddm
> nordic.wallpapers
> nordic.xfwm4
> ```

Not necessarily. Just that if one is using SDDM then it would additionally fetch that special output too. Otherwise it only fetches `out`. It's more like a usability thing, people shouldn't have issues about enabling the module and having also to add that specific output to `environment.systemPackages`.

**Comment by romildo** [comment]
> It's more like a usability thing, people shouldn't have issues about enabling the module and having also to add that specific output to environment.systemPackages

One sets the sddm theme with a configuration option: `[services.xserver.displayManager.sddm.theme](https://nixos.org/manual/nixos/stable/options#opt-services.xserver.displayManager.sddm.theme)`

It may be more interesting to have an aditional option `services.xserver.displayManager.sddm.themePackage` to install the package containing the desired theme.

Usually there is no need to install several sddm themes, because only one is used in the module configuration.

That way both the theme and theme package to be used for sddm could be set in the same portion of the configuration that enables the sddm module.

Like it is already done for many modules. Some examples are greeters for lightdm.

**Review by Cryolitia — APPROVED** [review]
LGTM

**Pull request merged**
