### PR TITLE
davinci-resolve: remove host header restrictions for blob download

### PR DESCRIPTION
**Pull request by tnichols217**
## Description of changes
Remove header: host restriction for download of binaries from blackmagic as their download domain has changed multiple times in the past few days.

## Things done

Remove header: host restriction from cURL command

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tnichols217** [comment]
@jshcmpbll heres the pull

**Review by jshcmpbll — APPROVED** [review]
LGTM

**Comment by LiGoldragon** [comment]
This worked! :+1:

**Comment by NickCao** [comment]
The missing commits on release-23.05 are
```
9bca13980fae davinci-resolve: remove host header restrictions for blob download
384a9eeee4dd davinci-resolve: update payload request and URL of download
e0d25a052885 davinci-resolve: add missing dependencies to 18.1.4
c4319ac59e90 davinci-resolve: 17.4.3 -> 18.1.4
```
Which includes a major version update that might not be eligible for backport.

**Comment by davidak** [comment]
>Backport failed

I try to do the backport manually.

**Pull request merged**
