### PR TITLE
graph-tool: enable drawing and openmp for algorithms

### PR DESCRIPTION
**Pull request by joelmo**
I also replaced lots of arguments using with pkgs;

### CODE REVIEW

**Comment by peti** [comment]
>  replaced lots of arguments using with pkgs

Please don't do that. We want to pass lots of arguments, not `pkgs`.

**Comment by joelmo** [comment]
Ok I will change it, but what is the reason for doing that? To me it looks better this way, otherwise I need to specify the requirements both in arguments and then the inputs.

**Comment by peti** [comment]
For people reading the expression it's nice to see where the various symbols come from. Having `with pkgs;` at the top defeats that. Also, users of the expressions might want to override a single dependency, say, to pass a different version than the one used by default. This is much harder to do if the function doesn't take it's dependencies individually.

**Comment by joelmo** [comment]
Ok I changed this, but is overriding really harder, I could call with `pkgs // pkgsWithOverridings`, it maybe would be hard to see where symbols come from if there were multiple `withs` but i'm not even sure if it would be much harder, say if I read this `with pkgs; { .... with pythonPackages; { ... }  }` I would start looking at pythonPackages for that symbol foremost, I think having `withs` may be easier to read.

**Pull request merged**
