### PR TITLE
yubikey-manager: 2.1.1 -> 3.1.0

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

https://developers.yubico.com/yubikey-manager/Release_Notes.html

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by benley — APPROVED** [review]

**Comment by mmahut** [comment]
Fails on ``darwin`` with.

```In file included from smartcard/scard/winscarddll.c:26:
smartcard/scard/winscarddll.h:280:13: error: unknown type name 'LPTSTR'
    OUT     LPTSTR mszReaders,
            ^
smartcard/scard/winscarddll.h:286:13: error: unknown type name 'LPTSTR'
    OUT     LPTSTR mszGroups,
            ^
smartcard/scard/winscarddll.h:304:9: error: unknown type name 'LPTSTR'
    OUT LPTSTR szReaderName,
        ^
smartcard/scard/winscarddll.c:529:13: error: unknown type name 'LPTSTR'
    OUT     LPTSTR mszReaders,
            ^
smartcard/scard/winscarddll.c:543:13: error: unknown type name 'LPTSTR'
    OUT     LPTSTR mszGroups,
            ^
smartcard/scard/winscarddll.c:582:9: error: unknown type name 'LPTSTR'
    OUT LPTSTR szReaderName,
        ^
6 errors generated.
error: command 'clang' failed with exit status 1```

**Comment by dtzWill** [comment]
> Fails on `darwin` with.

Those files don't exist in `yubikey-manager`, but they do in `pyscard` -- is that where you're seeing the failure?

1) I should send the update to 1.9.9 (242f916d2ee638b606640974c7eb95cfb6536177 and follow-up 844420ec4c10c1504df35ffb1492fa1894714757), maybe that helps?
2) pyscard patches the path to pcsclite's ".so" library-- does Darwin work without a similar substitution? Just curious :).

**Comment by mmahut** [comment]
@dtzWill yes, it's failing on ofborg as well.

**Review by marsam — APPROVED** [review]

**Comment by marsam** [comment]
@mmahut pyscard on darwin is fixed by https://github.com/NixOS/nixpkgs/pull/65163

**Comment by mmahut** [comment]
@GrahamcOfBorg build yubikey-manager

**Pull request merged**
