### PR TITLE
php: 7.4.26 -> 7.4.27, 8.0.13 -> 8.0.14

### PR DESCRIPTION
**Pull request by drupol**
This PR:

- [x] Upgrade PHP to version 7.4.27
- [x] Upgrade PHP to version 8.0.14

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by drupol** [comment]
@ofborg build php74

**Comment by drupol** [comment]
@ofborg build php74

**Review by dasj19 — COMMENTED** [review]
The version update and maintainers update should be in different commits

The commit message would be: `php: add drupal as maintainer`

PS: nice github handle

**Comment by drupol** [comment]
@ofborg build php74

**Comment by risicle** [comment]
@ofborg test php

**Comment by risicle** [comment]
`nixpkgs-review` reveals no new failures, macos 10.15 & nixos x86_64.

Many packages also built happily on nixos aarch64

**Review by jtojnar — APPROVED** [review]
Changelog looks okay as well: https://github.com/php/php-src/blob/php-7.4.27/NEWS#L3-L26

**Comment by ajs124** [comment]
`php80` also had a release, do you mind taking care of that as well @drupol? If not, I (or somebody else) can just take care of that in another PR.

**Comment by drupol** [comment]
Sure, will do it.

**Comment by drupol** [comment]
@ofborg build php74 php80

**Comment by etu** [comment]
This should also be two separate commits where they actually refer to the affected attribute, which is `php74: 7.4.26 -> 7.4.27` and `php80: 8.0.13 -> 8.0.14` :)

**Comment by drupol** [comment]
Ok will do.

**Comment by drupol** [comment]
@ofborg build php74 php80

**Comment by etu** [comment]
@ofborg test php74 php80

**Pull request merged**
