### PR TITLE
vimPlugins.nvim-scrollbar: init at 2020-12-13

### PR DESCRIPTION
**Pull request by pinpox**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by pinpox** [comment]
I'm not able to run ./update.py, it outputs a lot of errors like these:
```
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
HTTP Error 429: too many requests, Retrying in 3 seconds...
```

**Review by jonringer — COMMENTED** [review]
please create a github api token, and run the script as detailed here: https://github.com/NixOS/nixpkgs/blob/855574d4d70710462181876590a9ca9318e358b1/doc/languages-frameworks/vim.section.md#updating-plugins-in-nixpkgs

**Comment by teto** [comment]
or run it with `--proc 1`

**Comment by pinpox** [comment]
@jonringer @teto I tried both, but still get an error:
```bash
GITHUB_API_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ./update.py --add "dstein64/nvim-scrollview"
warning: unknown setting 'experimental-features'
656 plugins were checked
updated generated.nix
committing to nixpkgs "vimPlugins: update"
HTTP Error 404: Not Found, Retrying in 3 seconds...
HTTP Error 404: Not Found, Retrying in 6 seconds...
HTTP Error 404: Not Found, Retrying in 12 seconds...
656 plugins were checked, 1 plugin(s) could not be downloaded:

nvim-scrollview: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "./update.py", line 381, in prefetch
    plugin, redirect = prefetch_plugin(owner, repo, branch, alias, cache)
  File "./update.py", line 235, in prefetch_plugin
    commit, date = repo.latest_commit()
  File "./update.py", line 67, in f_retry
    return f(*args, **kwargs)
  File "./update.py", line 112, in latest_commit
    with urllib.request.urlopen(commit_req, timeout=10) as req:
  File "/nix/store/i9lzacdfrwlj1ayw551c016s0fq71p7j-python3-3.8.6/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/nix/store/i9lzacdfrwlj1ayw551c016s0fq71p7j-python3-3.8.6/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/nix/store/i9lzacdfrwlj1ayw551c016s0fq71p7j-python3-3.8.6/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/nix/store/i9lzacdfrwlj1ayw551c016s0fq71p7j-python3-3.8.6/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/nix/store/i9lzacdfrwlj1ayw551c016s0fq71p7j-python3-3.8.6/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/nix/store/i9lzacdfrwlj1ayw551c016s0fq71p7j-python3-3.8.6/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by SuperSandro2000** [comment]
This is already in master as ``dstein64/nvim-scrollview@main``.

**Pull request closed without merging**
