### PR TITLE
buck: use jdk8

### LINKED ISSUE #120557: Buck built with wrong JDK version
Buck build system is packaged with the wrong JDK it seems

```
% buck
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.Error: java.lang.NullPointerException
	at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder.getDefaultProvider(FileSystems.java:133)
	< snip >
	... 34 more
You're using Java 11, but Buck requires Java 8.
```

# Additional context

PR #119247 introduced a bump in JDK version, see (https://github.com/NixOS/nixpkgs/pull/119247#pullrequestreview-642420243).

@jonringer @marsam @jgertm 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
closes #120557

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
cc @HolgerPeters

**Comment by asbachb** [comment]
I wonder if this PR is still needed for the most recent version: https://github.com/facebook/buck/issues/2037

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 120559` at ad521d00 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>buck</li>
  </ul>
</details>
<details>
  <summary>3 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`buildPhase` should probably contain `runHook preBuild` and `runHook postBuild`.

Near pkgs/development/tools/build-managers/buck/default.nix:22:3:
```
   |
22 |   buildPhase = ''
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Please add a comment on the line above, explaining the purpose of this patch.
Near pkgs/development/tools/build-managers/buck/default.nix:14:15:
```
   |
14 |   patches = [ ./pex-mtime.patch ];
   |               ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/development/tools/build-managers/buck/default.nix:31:3:
```
   |
31 |   installPhase = ''
   |   ^
```
</li>
  </ul>
</details>

**Comment by jonringer** [comment]
> I wonder if this PR is still needed for the most recent version: [facebook/buck#2037](https://github.com/facebook/buck/issues/2037)

last stable release was from January,  those changes are from feburary.

https://github.com/NixOS/nixpkgs/issues/120557#issuecomment-826135485
> Until they make a stable release with those changes included, we will just use jdk8

**Review by lukegb — APPROVED** [review]

**Review by marsam — APPROVED** [review]

**Pull request merged**
