### PR TITLE
kakoune: add philiptaron as maintainer to most kakoune-related things

### PR DESCRIPTION
**Pull request by philiptaron**
## Description of changes

I'd like to step up and help maintain the [Kakoune editor](https://kakoune.org) and its plugins and related tools.

## Things done

- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Aleksanaa — APPROVED** [review]

**Comment by Aleksanaa** [comment]
Would be good to add yourself to the [codeowner](https://github.com/NixOS/nixpkgs/blob/master/.github/CODEOWNERS) of `pkgs/applications/editors/kakoune`, but it's up to you

**Comment by philiptaron** [comment]
My understanding is that I can't add to codeowner until I'm a committer, which as of today I'm not. Someday!

**Comment by Aleksanaa** [comment]
Oh didn't know that!

**Comment by philiptaron** [comment]
> Would be good to add yourself to the [codeowner](https://github.com/NixOS/nixpkgs/blob/master/.github/CODEOWNERS) of `pkgs/applications/editors/kakoune`, but it's up to you

In the interim, I ascended. Added.

**Pull request merged**
