### PR TITLE
mosml: init at 2.10.1

### PR DESCRIPTION
**Pull request by vaibhavsagar**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by srhb** [comment]
@GrahamcOfBorg build mosml

**Comment by srhb** [comment]
@vaibhavsagar Did you manage to build it on Darwin?

**Comment by vaibhavsagar** [comment]
I didn't try on macOS, but I assumed it would work :frowning_face:

**Comment by srhb** [comment]
Yeah, strange. People of the future, it has been mentioned at least here: https://github.com/kfl/mosml/issues/47#issuecomment-297646961

**Comment by srhb** [comment]
And thanks!

**Comment by vaibhavsagar** [comment]
My pleasure 😄!

**Pull request merged**
