### PR TITLE
swaylock-fancy: unstable-2021-10-11 -> unstable-2023-11-21

### PR DESCRIPTION
**Pull request by frogamic**
## Description of changes

* Update to latest commit of swaylock-fancy
* Update nix package formatting
* Add myself as maintainer (previously unmaintained)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by frogamic** [comment]
1 package built:
swaylock-fancy

Result of `nixpkgs-review pr 268845` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>swaylock-fancy</li>
  </ul>
</details>

**Review by nevivurn — APPROVED** [review]
Works for me. Also, why did you add then remove meta.mainProgram?

**Comment by frogamic** [comment]
> Works for me. Also, why did you add then remove meta.mainProgram?

I removed it because it matches `pname` which is the default if mainProgram is not supplied

**Comment by nevivurn** [comment]
> I removed it because it matches `pname` which is the default if mainProgram is not supplied

I believe setting mainProgram even if it matches pname is useful, eg. it removes warnings in eg. `lib.getExe`.

see
```
$ nix eval --impure --expr 'with import ./. {}; lib.getExe swaylock'
"/nix/store/0fw7sir0fhbjbidw3rsx8in4m879q7ca-swaylock-1.7.2/bin/swaylock"

$ nix eval --impure --expr 'with import ./. {}; lib.getExe swaylock-fancy'
trace: warning: getExe: Package swaylock-fancy-unstable-2021-10-11 does not have the meta.mainProgram attribute. We'll assume that the main program has the same name for now, but this behavior is deprecated, because it leads to surprising errors when the assumption does not hold. If the package has a main program, please set `meta.mainProgram` in its definition to make this warning go away. Otherwise, if the package does not have a main program, or if you don't control its definition, use getExe' to specify the name to the program, such as lib.getExe' foo "bar".
"/nix/store/8fnxjqrvqjx0j0q0agsgz7k13ci5ax9z-swaylock-fancy-unstable-2021-10-11/bin/swaylock-fancy-unstable"
```

**Comment by frogamic** [comment]
Thanks for pointing that out, reverted to include the mainProgram

**Comment by Janik-Haag** [comment]
You can do:
```patch
From cf848307db37cbf65ba6c6de9ebc15eb92d95145 Mon Sep 17 00:00:00 2001
From: "Janik H." <janik@aq0.de>
Date: Thu, 23 Nov 2023 12:03:09 +0100
Subject: [PATCH] swaylock-fancy remove rec

---
 pkgs/applications/window-managers/sway/lock-fancy.nix | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/pkgs/applications/window-managers/sway/lock-fancy.nix b/pkgs/applications/window-managers/sway/lock-fancy.nix
index 9ffef2259af1..72d92d2fd339 100644
--- a/pkgs/applications/window-managers/sway/lock-fancy.nix
+++ b/pkgs/applications/window-managers/sway/lock-fancy.nix
@@ -26,13 +26,13 @@ let
     fontconfig
     wmctrl
   ];
-in stdenv.mkDerivation rec {
+in stdenv.mkDerivation {
   pname = "swaylock-fancy";
   version = "unstable-2023-11-21";
 
   src = fetchFromGitHub {
     owner = "Big-B";
-    repo = pname;
+    repo = "swaylock-fancy";
     rev = "ff37ae3c6d0f100f81ff64fdb9d422c37de2f4f6";
     hash = "sha256-oS4YCbZOIrMP4QSM5eHWzTn18k3w2OnJ2k+64x/DnuM=";
   };
-- 
2.42.0
```
so we don't have the rec argument before the attribute set.

**Comment by frogamic** [comment]
Removed the `rec` expression and fixed formatting.

**Review by Janik-Haag — APPROVED** [review]

**Pull request merged**
