### PR TITLE
python: enable optimizations

### PR DESCRIPTION
**Pull request by LnL7**
###### Motivation for this change

I didn't perform any tests yet, but I assume it's pretty safe and hopefully makes some stuff a bit faster.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
     - [x] python27
     - [ ] python34
     - [ ] python35
     - [x] python36
     - [ ] python37
   - [x] macOS
     - [ ] python27
     - [ ] python34
     - [ ] python35
     - [x] python36
     - [ ] python37
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by orivej** [comment]
This should go to staging.

**Comment by FRidh** [comment]
We would have to test against the package set to see if it does not have any unwanted side-effects.

**Comment by FRidh** [comment]
How much more time does it take to build the different Python versions?

**Comment by LnL7** [comment]
@FRidh I tested this with the dependency tree of a project as a sanity check and didn't notice any problems.
The build time does indeed increase significantly because of the tests, but it's not like it was long already. Shouldn't we be running some of the tests anyway?

```diff
-nix-build -A python27 --check  0.17s user 0.08s system 0% cpu 1:39.95 total
-nix-build -A python36 --check  0.19s user 0.10s system 0% cpu 1:34.19 total
+nix-build -A python27 --check  0.19s user 0.09s system 0% cpu 15:40.69 total
+nix-build -A python36 --check  0.23s user 0.12s system 0% cpu 28:26.26 total
```

**Review by matthewbauer — APPROVED** [review]

**Comment by vcunat** [comment]
I wonder... do you care for this for 18.09?  (I can't really afford to review it myself.)

**Comment by LnL7** [comment]
I reread the description of the flag and I'm not actually sure anymore if it's useful. I mainly tried this out because the build log recommends it for a release build.

```
If you want a release build with all optimizations active (LTO, PGO, etc),
please run ./configure --enable-optimizations
```

**Comment by FRidh** [comment]
@LnL7 https://bugs.python.org/msg281332

**Review by lukateras — APPROVED** [review]

**Comment by yegortimoshenko** [comment]
> https://bugs.python.org/msg281332

It seems we're good on that since `--with-lto` is not passed and `--enable-optimizations` doesn't imply the former flag since 2016-09.

Will merge in a few days if there's no disagreement.

**Comment by FRidh** [comment]
At least when building the interpreter we also build optimized bytecode. We could do that as well in a hook for all Python packages.

I don't think we should bother with these optimizations. If you indeed have something critical running, then likely you know about the option and enable it.

**Comment by sbourdeauducq** [comment]
> If you indeed have something critical running, then likely you know about the option and enable it.

This is a rather difficult proposal since it means rebuilding a lot of packages that depend on Python.
What about enabling ``--enable-optimizations`` and ``--with-lto`` only on certain platforms, like ``x86_64-linux``, where toolchains are better tested, and CPU power to build Python is relatively plentiful and low-cost?

FWIW I've just ran ``nix-build -A python27 -A python35 -A python36 -A python37 -A python38 -A python39`` on ``x86_64-linux`` with nixpkgs master and those flags; the build finished without issue and the resulting ``python`` binaries ran fine.

**Pull request closed without merging**
