### PR TITLE
Darwin ffmpeg

### PR DESCRIPTION
**Pull request by acowley**
###### Things done:
- Built on platform(s)
  - [ ] OS X
###### More

The three commits here are a journey I went through to get camera input working with ffmpeg on darwin.
- ffmpeg's build system does some checking of available include files that revealed the problem with AVFoundation. This is not an issue with the headers on my 10.11 system, so it is a temporary fix.
- I may have misunderstood the `cf-private/setup-hook.sh` as it didn't make sense to me as it was
- The `install_name_tool` idea implemented in `ffmpeg-full/default.nix` is thanks to @pikajude . I spent two days trying alternatives, none of which worked, before catching him on IRC. It's ugly, but I do not know how to avoid it.

### CODE REVIEW

**Comment by pikajude** [comment]
@acowley as far as your third point goes, the `install_name_tool` mangling is only avoidable if we manage to reverse-engineer all of Apple's frameworks. Any volunteers? :)

:+1:

**Comment by acowley** [comment]
Let's punt on that for now 😬

@pikajude what about the change to cf-private's setup-hook? Was the previous form as intended, or did it get mangled at some point?

**Comment by pikajude** [comment]
@acowley I don'

**Comment by acowley** [comment]
Is there anything I can do to help move this along? I appreciate it's rather gnarly, but I think it's all necessary to get ffmpeg to work with AVFoundation.

**Comment by acowley** [comment]
Pinging again to see if there is any more feedback. I have a few PRs that seem to have stalled, but I'm not sure what the next steps might be.

**Comment by joachifm** [comment]
Hm, reading over this patch, it looks like it will only affect darwin builds; am I reading that right?
Looks like there's an evaluation error, though. Fix that and I'll merge this.

Btw., I think the reason darwin PRs tend to stall is lack of darwin people with commit access; perhaps you ought to ask for it?

**Comment by wmertens** [comment]
[LGTM](http://lgtm.in/i/omBlhc2Vp)

**Pull request merged**
