### PR TITLE
nextcloud-notify_push: 0.5.0 -> 0.6.0

### PR DESCRIPTION
**Pull request by SuperSandro2000**
Diff: https://github.com/nextcloud/notify_push/compare/v0.5.0...v0.6.0

- [ ] deploy on nextcloud server

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ajs124** [comment]
I think the patch to the test_client will fail to apply like this

**Comment by ajs124** [comment]
Seems like I didn't add the actual test to `passthru` in #201780. Maybe we should do that. Either here or in a separate PR. Because if that were there, then ofborg would tell us if it succeeded and I wouldn't need to build that manually locally.

**Review by Shawn8901 — COMMENTED** [review]
The companion plugin also should be updated (the companion is in the nextclouds plugins thing see here as example for 24.X https://github.com/NixOS/nixpkgs/blob/7d530fdb9957f83882a0d1a78b76fd5be70199df/pkgs/servers/nextcloud/packages/24.json#L132)  
If someone would use the declarative way to install the plugin (like the test is doing, if active), it will fail to activate with the following error:

`nextcloud-notify_push-post-start[1533457]: 🗴 push server (version 0.6.0) is not the same version as the app (version 0.5.2).`

As my system is still on an older channel, i am testing that with manual patches and have the plugin installed via the nextcloud way, after patching the said plugin to 0.6.0, it works fine.

**Comment by SuperSandro2000** [comment]
Not using declarative plugins, so I didn't notice it. Added an update to all nextcloud packages.

**Review by Shawn8901 — APPROVED** [review]

**Pull request merged**
