### PR TITLE
uutils-coreutils: install symlinks again by converting to stdenv.mkDe…

### PR DESCRIPTION
**Pull request by SuperSandro2000**
…rivation which executes make,

add enableMulticallBinary option to generate small binaries and last add
me as a maintainer because I have bigger plans for this package.

This got most likely broken when @danieldk changed the rust build system but it would be broken anyway.

###### Motivation for this change
I need a working uutils-coreutils package.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 116269` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>uutils-coreutils</li>
  </ul>
</details>

**Review by siraben — APPROVED** [review]
LGTM. Tested binaries.

**Comment by 06kellyjac** [comment]
What are your big plans @SuperSandro2000 :slightly_smiling_face:

**Comment by SuperSandro2000** [comment]
That you can replace coreutils with it. #116274

**Comment by 06kellyjac** [comment]
Thanks

**Pull request merged**
