### PR TITLE
redmine: Use proper Gemfile and unbreak package

### PR DESCRIPTION
**Pull request by felixsinger**
###### Description of changes

The Gemfile that was added/used in commit 6201512ce2 originates from the master branch of Redmine instead of its 5.0.5 release tag, which breaks the Redmine package and makes it unable to start.

For whatever reason the issue wasn't detected during review and also the tests worked.

Use the Gemfile from the 5.0.5 release tag and do the following changes:
  * Add webrick gem, since it is not included anymore
  * To fix the ffi dependency, add the :mri platform to it
  * Only use the gems for PostgreSQL and MySQL

Also, add a patch that is applied to the Redmine tree to make it complaint with above changes.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by felixsinger** [comment]
@megheaiulian Please be more careful next time when you copy the Gemfile.

**Comment by felixsinger** [comment]
@GrahamcOfBorg test redmine

**Comment by felixsinger** [comment]
Tests fail. Though, that's what I have done on my production instance. Will have a look tomorrow.

**Comment by megheaiulian** [comment]
It is a bit weird that the service fails to start with the current Gemfile because I am using this and it works for me. 
What kind of error do you get when starting Redmine?

**Comment by megheaiulian** [comment]
We also shouldn't need to patch the Gemfile inside the sources ...

**Comment by megheaiulian** [comment]
Fixed this in #239518. I've used the Gemfile from redmine 5.0.5 and made sure that `rexml` gem is always included.

**Pull request closed without merging**
