### PR TITLE
godot: 2.1.4 -> 3.0.2

### PR DESCRIPTION
**Pull request by augu5te**
###### Motivation for this change
Make available the version 3, version 2 is considered as legacy.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
similar: #34971 , #34421

**Comment by Twey** [comment]
Be careful — there is a sneaky impurity here: see my PR for details.

**Comment by Ekleog** [comment]
Thanks! However, now that https://github.com/NixOS/nixpkgs/pull/34971 is merged I guess this is no longer needed :) (well, on the next unstable bump at least)

**Comment by augu5te** [comment]
Issue addressed by #34971

**Pull request closed without merging**
