### PR TITLE
bundler: 1.14.6 -> 1.16.1

### PR DESCRIPTION
**Pull request by Mic92**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build vagrant

**Comment by xeji** [comment]
Tried this locally, looks like the hash for `vagrant` has changed although it's pinned to a git revision.

**Comment by Mic92** [comment]
@GrahamcOfBorg build vagrant

**Comment by Mic92** [comment]
I changed the way I import the source from the gemset.

**Comment by Mic92** [comment]
Does not ofborg performs a merge automatically before building. How a local rebase would help here?

**Comment by xeji** [comment]
Right, my mistake. Maybe something broke git again or the ofborg builder isn't up to date (has happened to me before).

**Comment by timor** [comment]
Will this be merged into 18.03?

**Pull request merged**
