### PR TITLE
melange: init at 0.4.0

### PR DESCRIPTION
**Pull request by developer-guy**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by developer-guy** [comment]
hi @emilylange, I think we just need to disable the tests since the tests (I guess?) need a shell which we don't have in the nix build environment (I guess), this is why I added `dontCheck = true`, but it didn't seem to work, could you please help me on this? Thanks in advance

**Comment by emilylange** [comment]
Your `src` fails, not `melange` itself.

Which you probably can't reproduce locally on your machine, since that's a fixed-output-derivation, already in your `/nix/store`.
You can force a rebuild of it by setting the `src.hash` to `lib.fakeHash` (or `""`), or by running `nix-build -A melange.src --check`.

Build error logs (`-A melange` should yield the same):
```
❯ nix-build -A melange.src
this derivation will be built:
  /nix/store/k6i2nhcqxp0j6hd99vvd2jkd364b8dq8-source.drv
building '/nix/store/k6i2nhcqxp0j6hd99vvd2jkd364b8dq8-source.drv'...
exporting https://github.com/chainguard-dev/melange.git (rev v0.4.0) into /nix/store/bqfq4db6nwycmkdrql9igsbrayqsw3g2-source
Initialized empty Git repository in /nix/store/bqfq4db6nwycmkdrql9igsbrayqsw3g2-source/.git/
remote: Enumerating objects: 245, done.
remote: Counting objects: 100% (245/245), done.
remote: Compressing objects: 100% (214/214), done.
remote: Total 245 (delta 28), reused 135 (delta 15), pack-reused 0
Receiving objects: 100% (245/245), 712.40 KiB | 2.34 MiB/s, done.
Resolving deltas: 100% (28/28), done.
From https://github.com/chainguard-dev/melange
 * tag               v0.4.0     -> FETCH_HEAD
Switched to a new branch 'fetchgit'
Enumerating objects: 244, done.
Counting objects: 100% (244/244), done.
Compressing objects: 100% (228/228), done.
Writing objects: 100% (244/244), done.
Total 244 (delta 26), reused 215 (delta 0), pack-reused 0
Enumerating objects: 244, done.
Nothing new to pack.
/nix/store/32ihbg0l1v9v4bs9x0shmp4kdjsym3qq-stdenv-linux/setup: line 132: shell: command not found
/nix/store/32ihbg0l1v9v4bs9x0shmp4kdjsym3qq-stdenv-linux/setup: line 144: pop_var_context: head of shell_variables not a function context
```

The issue is the `shell` in `SOURCE_DATE_EPOCH=$(shell git log -1 --pretty=%ct)` you copied from the upstream Makefile

https://github.com/chainguard-dev/melange/blob/0488212980b85f22ce901a960b6febdd1733a31e/Makefile#L24-L30

Dropping `shell` from that lines seems to fix it.

But you don't necessarily need to resolve/lookup the underlying `version.gitCommit` and `version.buildDate` values.
It's very common to just set whatever build date variable a program might take as input as `1970-01-01` and `gitCommit` set to `src.rev`.

Up to you, if you want to keep your `src.postFetch` phase, for slightly more correct values.
But if so, it needs some more polishing :)

**Comment by developer-guy** [comment]
thank you so much @emilylange, I forgot the remove the `shell` that I copied from Makefile, yeah.

**Review by emilylange — CHANGES_REQUESTED** [review]
```patch
diff --git a/pkgs/development/tools/melange/default.nix b/pkgs/development/tools/melange/default.nix
index 492c3e249f5..709198ed589 100644
--- a/pkgs/development/tools/melange/default.nix
+++ b/pkgs/development/tools/melange/default.nix
@@ -19,22 +19,16 @@ buildGoModule rec {
     postFetch = ''
       cd "$out"
       git rev-parse HEAD > $out/COMMIT
-      # '0000-00-00T00:00:00Z'
-
-      DATE_FMT='+%Y-%m-%dT%H:%M:%SZ'
-      SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)
-      if [ -n "$SOURCE_DATE_EPOCH" ]; then
-          BUILD_DATE=$(date -u -d "@$SOURCE_DATE_EPOCH" "$DATE_FMT" 2>/dev/null || date -u -r "$SOURCE_DATE_EPOCH" "$DATE_FMT" 2>/dev/null || date -u "$DATE_FMT")
-      else
-          BUILD_DATE=$(date "$DATE_FMT")
-      fi
-      echo "$BUILD_DATE" > $out/SOURCE_DATE_EPOCH
+      # in format of 0000-00-00T00:00:00Z
+      date -u -d "@$(git log -1 --pretty=%ct)" "+%Y-%m-%dT%H:%M:%SZ" > $out/SOURCE_DATE_EPOCH
       find "$out" -name .git -print0 | xargs -0 rm -rf
     '';
   };
 
   vendorHash = "sha256-IkbXZu6iHRXjWFsLtRBDxwJio5sVVZvHylk1al0S+/c=";
 
+  subPackages = [ "." ];
+
   nativeBuildInputs = [ installShellFiles ];
 
   ldflags = [
@@ -57,7 +51,9 @@ buildGoModule rec {
       --zsh <($out/bin/melange completion zsh)
   '';
 
+  doInstallCheck = true;
   installCheckPhase = ''
+    runHook preInstallCheck
 
     $out/bin/melange --help
     $out/bin/melange version 2>&1 | grep "v${version}"
@@ -67,7 +63,7 @@ buildGoModule rec {
 
   meta = with lib; {
     homepage = "https://github.com/chainguard-dev/melange";
-    changelog = "https://github.com/chainguard-dev/melange/blob/main/NEWS.md";
+    changelog = "https://github.com/chainguard-dev/melange/blob/${src.rev}/NEWS.md";
     description = "Build APKs from source code";
     license = licenses.asl20;
     maintainers = with maintainers; [ developer-guy ];
```

**Review by emilylange — APPROVED** [review]

**Pull request merged**
