### PR TITLE
coqPackages.equations: enable for Coq 8.8

### PR DESCRIPTION
**Pull request by vbgl**
cc @jwiegley 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vbgl** [comment]
@GrahamcOfBorg build coqPackages_8_8.equations

**Comment by jwiegley** [comment]
I already pushed a change for this to master: 1459b2dffa8336872f5b1f10cfcb1f1f36d8e490

**Comment by jwiegley** [comment]
Never mind.

**Comment by vbgl** [comment]
Thanks.

**Pull request merged**
