### PR TITLE
python3Packages.ecdsa: 0.15 -> 0.16.0

### PR DESCRIPTION
**Pull request by yorickvP**
###### Motivation for this change

Required for esptool update

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by prusnak** [comment]
@GrahamcOfBorg build electrum python3Packages.trezor

**Comment by prusnak** [comment]
This should probably go to staging branch instead of master as it is causing massive rebuilds.

**Comment by yorickvP** [comment]
Looks like not all the past bumps went via staging. @FRidh?

**Comment by FRidh** [comment]
Reverse deps need to be tested first, and then this should go via staging.

**Comment by SuperSandro2000** [comment]
@yorickvP Can you please rebase it on staging?

**Comment by FRidh** [comment]
0.16.1 ea4de56619aba7f4701e27382cc2222e9a46e8f3 is in staging-next

**Pull request closed without merging**
