### PR TITLE
keyspersecond: init at 8.9

### LINKED ISSUE #281453: Package request: KeysPerSecond
**Project description**
KeysPerSecond is a program that counts how many times certain keys and mouse buttons are pressed.

**Metadata**
* homepage URL: https://osu.ppy.sh/forum/t/552405/
* source URL: https://github.com/RoanH/KeysPerSecond
* license: GPL-3.0
* platforms: unix

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by TomaSajt**
## Description of changes

Closes https://github.com/NixOS/nixpkgs/issues/281453

This PR adds 1 package: `keyspersecond`
This is a java app, using Gradle as the build system.
Luckily, there were less gradle shenanigans than with other packages.

I used `stripJavaArchivesHook` to fix the timestamps in the jar file

I do not know if darwin also needs extra runtime libraries, sadly I cannot test it.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by UlyssesZh** [comment]
Thank you for your work! Some suggestions:

- KeysPerSecond v8.9 has been released.
- Add the flag `-Dsun.java2d.opengl=true` in the command wrapper; otherwise, the background color cannot be translucent.
- Could you please also add a desktop entry?

**Comment by TomaSajt** [comment]
I did a big restructuring of the whole derivation, hopefully this way its in a more "override"-able state.

I also dropped the usage of `canonicalize-jars-jook` in place of a better built-in solution (added by a patch file)

**Comment by TomaSajt** [comment]
I can't seem to be able to use the colors set in the color selector (bug?), so I don't know if the transparency fix works or not.

**Comment by UlyssesZh** [comment]
> I can't seem to be able to use the colors set in the color selector (bug?), so I don't know if the transparency fix works or not.

In the color config interface, there is a checkbox saying "enable custom colors". You need check that on.

Upon second thought, I think enabling this flag in the command wrapper may cause some problems when OpenGL is not supported? I do not have an environment to test that, though.

**Comment by TomaSajt** [comment]
> In the color config interface, there is a checkbox saying "enable custom colors". You need check that on.

I'm using a dark theme, so most of the UI is pretty unintelligible, because of this that toggle button wasn't even visible to me.

I tried it out, and it wasn't working properly yet. However after debugging with `J2D_TRACE_LEVEL=4` I figured out that `libGL` just wasn't able to be found, so I added it to `libPath`. It now seems to work OK

**Comment by bjornfor** [comment]
> ~I used canonicalize-jars-hook to fix the timestamps in the jar file.~
> I used a built-in build flag inside gradle to have a deterministic timestamp in the jar file.

Cool! Do you think this can be generalized and used across nixpkgs?

**Comment by TomaSajt** [comment]
> > ~I used canonicalize-jars-hook to fix the timestamps in the jar file.~
> > I used a built-in build flag inside gradle to have a deterministic timestamp in the jar file.
> 
> Cool! Do you think this can be generalized and used across nixpkgs?

I think we can, but mostly with manual patches.
See [this comment](https://github.com/NixOS/nixpkgs/issues/278518#issuecomment-1934535129) for every solution I could find to not have to use canonicalize-jars-hook.

**Comment by chayleaf** [comment]
https://github.com/NixOS/nixpkgs/pull/272380 got merged, so you should adjust the code accordingly (it should be greatly simplified). See https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/gradle.section.md

**Comment by TomaSajt** [comment]
> #272380 got merged, so you should adjust the code accordingly (it should be greatly simplified). See https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/gradle.section.md

That's really great to hear, I've been excited to finally try it out.

**Review by Aleksanaa — APPROVED** [review]

**Pull request merged**
