### PR TITLE
streamlink: 0.12.1 -> 0.13.0

### PR DESCRIPTION
**Pull request by jfrankenau**
###### Motivation for this change

Update

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @dezgeg @zraexy

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg  build streamlink

**Review by xeji — CHANGES_REQUESTED** [review]
Please fix test failure.

**Review by xeji — APPROVED** [review]

**Comment by jfrankenau** [comment]
I have sandboxing enabled. I mereley managed to somehow let this commit slip away …

**Comment by xeji** [comment]
Thanks. Why does this cause a mass rebuild of pretty much all haskell things now? If this is necessary, you will need to rebase this PR on the `staging` branch.

**Comment by jfrankenau** [comment]
Haskell? With nox-review I am seeing primarily Python packages. This is probably caused by the update of freezegun which is a test dependency and thus indirectly used by those packages.

**Comment by xeji** [comment]
Can you get the streamlink update to work without updating freezegun?

**Comment by jfrankenau** [comment]
Yes! I have applied a patch from upstream which was commited twelve days ago specifically to make it work with older versions of freezegun.

**Comment by xeji** [comment]
Thank you!

**Pull request merged**
