### PR TITLE
scala_3: 3.3.0 -> 3.3.1, scala_2_13: 2.13.11 -> 2.13.12

### PR DESCRIPTION
**Pull request by kashw2**
## Description of changes

change logs:
- [Scala 3.3.1](https://github.com/lampepfl/dotty/releases/tag/3.3.1)
- [Scala 2.13.12](https://github.com/scala/scala/releases/tag/v2.13.12)

diffs:
- https://github.com/scala/scala/compare/v2.13.11...v2.13.12
- https://github.com/lampepfl/dotty/compare/3.3.0...3.3.1

tested scalac for both scala 3 and scala 2
tested the scala repl 

added myself as a maintainer of scala_3
added myself as a maintainer of scala_2_13

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kashw2** [comment]
Result of `nixpkgs-review pr 254688` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>isabelle</li>
    <li>isabelle-components.isabelle-linter</li>
    <li>scala</li>
    <li>scala_3</li>
    <li>tlaps</li>
  </ul>
</details>

**Comment by fabianhjr** [comment]
Result of `nixpkgs-review pr 254688` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>isabelle</li>
    <li>isabelle-components.isabelle-linter</li>
    <li>scala (scala_2_13)</li>
    <li>scala_3</li>
    <li>tlaps</li>
  </ul>
</details>

**Review by fabianhjr — APPROVED** [review]

**Review by virusdave — COMMENTED** [review]
Approved!  Thanks for doing this.

**Comment by karolchmist** [comment]
Result of `nixpkgs-review pr 254688` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>isabelle</li>
    <li>isabelle-components.isabelle-linter</li>
    <li>scala (scala_2_13)</li>
    <li>scala_3</li>
    <li>tlaps</li>
  </ul>
</details>

**Review by karolchmist — APPROVED** [review]

**Pull request merged**
