### PR TITLE
marp-cli: init at 2.3.0

### PR DESCRIPTION
**Pull request by blaggacao**

### CODE REVIEW

**Comment by blaggacao** [comment]
Result of `nixpkgs-review pr 216443` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>dat</li>
    <li>slack-dark</li>
  </ul>
</details>
<details>
  <summary>80 packages built:</summary>
  <ul>
    <li>antora</li>
    <li>balanceofsatoshis</li>
    <li>bat-extras.prettybat</li>
    <li>bitwarden-cli</li>
    <li>castnow</li>
    <li>code-server</li>
    <li>commitlint</li>
    <li>create-cycle-app</li>
    <li>emanote</li>
    <li>epgstation</li>
    <li>fast-cli</li>
    <li>flexoptix-app</li>
    <li>flood</li>
    <li>google-clasp</li>
    <li>grafana-image-renderer</li>
    <li>gtop</li>
    <li>imapnotify</li>
    <li>joplin</li>
    <li>lighthouse</li>
    <li>mastodon-bot</li>
    <li>morgen</li>
    <li>mx-puppet-discord</li>
    <li>n8n</li>
    <li>node2nix</li>
    <li>pm2</li>
    <li>postcss-cli</li>
    <li>pulp</li>
    <li>pyright</li>
    <li>python310Packages.batchspawner</li>
    <li>python310Packages.dockerspawner</li>
    <li>python310Packages.jupyterhub</li>
    <li>python310Packages.jupyterhub-ldapauthenticator</li>
    <li>python310Packages.jupyterhub-systemdspawner</li>
    <li>python310Packages.jupyterhub-tmpauthenticator</li>
    <li>python310Packages.oauthenticator</li>
    <li>python311Packages.batchspawner</li>
    <li>python311Packages.dockerspawner</li>
    <li>python311Packages.jupyterhub</li>
    <li>python311Packages.jupyterhub-ldapauthenticator</li>
    <li>python311Packages.jupyterhub-systemdspawner</li>
    <li>python311Packages.jupyterhub-tmpauthenticator</li>
    <li>python311Packages.oauthenticator</li>
    <li>quarto</li>
    <li>redoc-cli</li>
    <li>reveal-md</li>
    <li>shepherd</li>
    <li>shout</li>
    <li>slack</li>
    <li>teams</li>
    <li>theLoungePlugins.plugins.closepms</li>
    <li>theLoungePlugins.plugins.giphy</li>
    <li>theLoungePlugins.themes.chord</li>
    <li>theLoungePlugins.themes.flat-blue</li>
    <li>theLoungePlugins.themes.flat-dark</li>
    <li>thelounge</li>
    <li>uppy-companion</li>
    <li>vimPlugins.coc-docker</li>
    <li>vimPlugins.coc-emmet</li>
    <li>vimPlugins.coc-explorer</li>
    <li>vimPlugins.coc-metals</li>
    <li>vimPlugins.coc-prettier</li>
    <li>vimPlugins.coc-pyright</li>
    <li>vimPlugins.coc-r-lsp</li>
    <li>vimPlugins.coc-rust-analyzer</li>
    <li>vimPlugins.coc-sh</li>
    <li>vimPlugins.coc-stylelint</li>
    <li>vimPlugins.coc-sumneko-lua</li>
    <li>vimPlugins.coc-tslint</li>
    <li>vimPlugins.coc-vetur</li>
    <li>vimPlugins.markdown-preview-nvim</li>
    <li>vscode</li>
    <li>vscode-extensions.matklad.rust-analyzer</li>
    <li>vscode-extensions.ms-python.vscode-pylance</li>
    <li>vscode-fhs</li>
    <li>vscode-with-extensions</li>
    <li>vscodium</li>
    <li>vscodium-fhs</li>
    <li>wrangler</li>
    <li>yaml-language-server</li>
    <li>zx</li>
  </ul>
</details>

**Comment by NickCao** [comment]
@winterqt suggested that the preferred method to package nodejs packages now might be `buildNpmPackage`, which is easier to use and does not rely on codegen. Ref: https://github.com/NixOS/nixpkgs/pull/213590#issuecomment-1419018577

**Comment by GuillaumeDesforges** [comment]
I have pushed a PR for the latest release of marp: https://github.com/NixOS/nixpkgs/pull/244504

**Comment by blaggacao** [comment]
Superseded by https://github.com/NixOS/nixpkgs/pull/244504 thanks @GuillaumeDesforges

**Pull request closed without merging**
