### PR TITLE
Update freetype, fontconfig

### PR DESCRIPTION
**Pull request by nckx**
Testing this even partially (but properly) is so far outside my hardware's abilities it hurts. Help wanted.

### CODE REVIEW

**Comment by nckx** [comment]
Although I guess I should try to bump `fontconfig` as well.

**Comment by abbradar** [comment]
I left this to build in the background; the numbers are many so don't expect a result soon!

**Comment by abbradar** [comment]
I've managed to build my whole system with it (including LibreOffice) -- works good for me.

**Comment by vcunat** [comment]
@abbradar: did the appearance of fonts change significantly? It seems there have been quite significant changes around that.

BTW, after reading the news on freetype.org I'm surprised how bad the state is in general:
> there is still no rendering system on Unix-like operating systems that does linear alpha blending and gamma correction by default to render glyphs correctly.

**Comment by abbradar** [comment]
They feel _better_ but I can't say exactly why -- sharper, maybe. You can [judge by yourself](https://i.imgur.com/w8m2SNp.png) (this is on 120 DPI screen).

I have also seen this note -- a shame!

**Comment by vcunat** [comment]
It certainly appears good enough. If I understand the matter correctly, greatest visual deficiencies are/were with light-on-dark fonts rendered small.

**Comment by abbradar** [comment]
Thank you, @nckx!

**Comment by nckx** [comment]
Thank you for testing!

**Pull request merged**
