### PR TITLE
fluentd: 0.14.11 -> 1.2.3

### PR DESCRIPTION
**Pull request by kiloreux**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Infinisil** [comment]
@GrahamcOfBorg build fluentd

Can you check that the nixos module still works?

**Comment by ryantm** [comment]
@GrahamcOfBorg build fluentd

**Comment by ryantm** [comment]
I used mic92's nixos-shell to test that systemd starts fluentd without error with this PR applied onto master.

**Comment by ryantm** [comment]
fluentd was already failing on darwin

**Comment by ryantm** [comment]
@kiloreux thanks; please consider adding yourself as a maintainer.

**Pull request merged**
