### PR TITLE
protonup-ng: init at 0.2.1

### LINKED ISSUE #186974: [Packaging Request] protonup-ng
**Project description**
protonup is currently borked, protonup-ng is a fork fixing all the problems present in protonup

**Metadata**

* homepage/source URL: https://github.com/cloudishBenne/protonup-ng
* license: GPL-3.0
* platforms: linux

### PR DESCRIPTION
**Pull request by Madouura**
###### Description of changes
close #193062
close #186974

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [x] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Madouura** [comment]
cc @flexagoon

**Review by Atemu — APPROVED** [review]
This is pretty much a 1:1 copy of the regular protonup, perhaps we should unify the packages.

TBH, you could probably just override the regular one with a new source and metadata.

OR or we just remove the old one and alias it. Upstream has clearly given up on protonup: https://github.com/AUNaseef/protonup/issues/25

**Comment by Atemu** [comment]
Result of `nixpkgs-review pr 196957` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>protonup-ng (python310Packages.protonup-ng)</li>
    <li>python39Packages.protonup-ng</li>
  </ul>
</details>

Sucessfully updated proton-ge.

**Comment by Madouura** [comment]
I think it would be best to remove the old one and alias it. It's been long enough that we can safely assume that the original protonup is dead.

**Review by Atemu — APPROVED** [review]
Result of `nixpkgs-review pr 196957` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>protonup-ng (python310Packages.protonup-ng)</li>
    <li>python39Packages.protonup-ng</li>
  </ul>
</details>

Sucessfully updated.

**Comment by Atemu** [comment]
Might want to leave a minor release note on this to be transparent.

**Comment by Madouura** [comment]
Done.

**Review by Atemu — APPROVED** [review]

**Pull request merged**
