### PR TITLE
tzdata: revert to fat format

### PR DESCRIPTION
**Pull request by roberth**
###### Motivation for this change

The tzdata default format has changed, breaking some packages. We'll want to stick to the old format until the libraries and applications actually support the new format.

cc @zowoq, @jtojnar 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zowoq** [comment]
As the `go_bootstrap` timezone tests already require disabling/patching , I'd rather don't revert that commit so we don't need to bother with them in the future.

**Comment by roberth** [comment]
> As the `go_bootstrap` timezone tests already require disabling/patching, I'd rather don't revert that commit so we don't need to bother with them in the future.

It was valuable because it helped change my mind, letting me find the root cause and a better solution. That doesn't necessarily mean it will be valuable in the future though.
I'm leaning towards keeping the test, but I don't feel strongly about it.

**Comment by zowoq** [comment]
We already disable lots of tests for the `go` packages, I really don't see the benefit in keeping this one.

**Comment by roberth** [comment]
Sure enough. You're the go maintainer, not me :)

**Comment by jtojnar** [comment]
How wide are the breakages? Can we do it on staging-next?

**Comment by roberth** [comment]
I don't know how wide. It only shows when you miss an appointment. I don't know which time zones and time ranges are affected. `libical` apps seem to be affected, possibly more. It'd take considerable effort to figure that out, because test suites may or may not detect the problem.

**Comment by FRidh** [comment]
> How wide are the breakages? Can we do it on staging-next?

Channel blocking.

If reverting to the old format while keeping the latest version of tzdata is enough, then let's do that. Wel'll need to undo the disabling of the tests as well then and this needs to target staging-next.

**Comment by roberth** [comment]
> this needs to target staging-next.

I've changed base, hesitantly, because I think this should be applied asap. A bug like this seems to be much worse than a bunch of build failures. The risk here is that some number of programs is returning wrong times to unsuspecting users.

**Comment by roberth** [comment]
Changed it back. Will make a second PR.

**Comment by FRidh** [comment]
No need.

**Comment by FRidh** [comment]
@GrahamcOfBorg build libical

**Comment by doronbehar** [comment]
Is it possible there are other regressions for the latest tzdata update?

Screenshot from 2020-11-09 11-12-56

**Comment by roberth** [comment]
@doronbehar is that `master`?

I don't know the exact details of the format change, but a certain section of data is missing in the "slim" format. It's supposedly redundant, but some programs clearly still depend on it. The wrong `UTC+00` is probably caused by that missing data?

**Comment by doronbehar** [comment]
@roberth that's from the current latest `nixos-unstable` channel, which doesn't include the change. I'd have tested this change on my fork, but I didn't merge it since it seems it'd cause tons of rebuilds :/.

I also noticed that manually setting a certain time or using a different time zone, keeps reverting me back to the old time zone.

**Comment by jtojnar** [comment]
You can use `staging-next` branch which contains the fix and is mostly built.

**Comment by jtojnar** [comment]
I can reproduce this in `gnome-control-center` in `staging-next` too. Weirdly, when I click on some location on map, it briefly shows the correct timezone before changing to UTC. And if I click the map second time without moving cursor, it reverts to the correct timezone.

**Comment by jtojnar** [comment]
Possibly https://gitlab.gnome.org/GNOME/glib/-/issues/2215

**Comment by doronbehar** [comment]
Then maybe we should patch glib with https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1705 ?

**Comment by jtojnar** [comment]
There has been a new glib release since, currently testing

```patch
diff --git a/pkgs/desktops/gnome-3/core/gnome-control-center/default.nix b/pkgs/desktops/gnome-3/core/gnome-control-center/default.nix
index 1300f7a7503..0695aeb2cb8 100644
--- a/pkgs/desktops/gnome-3/core/gnome-control-center/default.nix
+++ b/pkgs/desktops/gnome-3/core/gnome-control-center/default.nix
@@ -94,6 +94,14 @@ stdenv.mkDerivation rec {
   ];
 
   buildInputs = [
+    (glib.overrideAttrs (attrs: rec {
+      inherit (attrs) pname;
+      version = "2.66.2";
+      src = fetchurl {
+        url = "mirror://gnome/sources/glib/${stdenv.lib.versions.majorMinor version}/${pname}-${version}.tar.xz";
+        sha256 = "1i0pd8y6xz64qlzfj73wxyqp0x7x9j6mwf4gj6ggil4d9vnhnfgc";
+      };
+    }))
     accountsservice
     adwaita-icon-theme
     cheese
@@ -103,7 +111,6 @@ stdenv.mkDerivation rec {
     colord-gtk
     fontconfig
     gdk-pixbuf
-    glib
     glib-networking
     gnome-bluetooth
     gnome-desktop
diff --git a/pkgs/desktops/gnome-3/core/gnome-settings-daemon/default.nix b/pkgs/desktops/gnome-3/core/gnome-settings-daemon/default.nix
index 3c039bc6310..cc21910d3d6 100644
--- a/pkgs/desktops/gnome-3/core/gnome-settings-daemon/default.nix
+++ b/pkgs/desktops/gnome-3/core/gnome-settings-daemon/default.nix
@@ -76,8 +76,15 @@ stdenv.mkDerivation rec {
   ];
 
   buildInputs = [
+    (glib.overrideAttrs (attrs: rec {
+      inherit (attrs) pname;
+      version = "2.66.2";
+      src = fetchurl {
+        url = "mirror://gnome/sources/glib/${stdenv.lib.versions.majorMinor version}/${pname}-${version}.tar.xz";
+        sha256 = "1i0pd8y6xz64qlzfj73wxyqp0x7x9j6mwf4gj6ggil4d9vnhnfgc";
+      };
+    }))
     gtk3
-    glib
     gsettings-desktop-schemas
     modemmanager
     networkmanager
```

**Comment by jtojnar** [comment]
Yes, that seems to fix it.

**Comment by andersk** [comment]
`configuration.nix` workaround for those who don’t want to wait for their entire system to rebuild:

```nix
{
  environment.etc.zoneinfo.source = lib.mkForce "${
      pkgs.tzdata.overrideAttrs (old: {
        makeFlags = old.makeFlags
          ++ [ ''CFLAGS+=-DZIC_BLOAT_DEFAULT=\"fat\"'' ];
      })
    }/share/zoneinfo";
}
```

**Comment by doronbehar** [comment]
> `configuration.nix` workaround for those who don’t want to wait for their entire system to rebuild:
> 
> ```nix
> {
>   environment.etc.zoneinfo.source = lib.mkForce "${
>       pkgs.tzdata.overrideAttrs (old: {
>         makeFlags = old.makeFlags
>           ++ [ ''CFLAGS+=-DZIC_BLOAT_DEFAULT=\"fat\"'' ];
>       })
>     }/share/zoneinfo";
> }
> ```

That fixed it for me, Thanks!

**Pull request merged**
