### PR TITLE
hhvm: fix build

### PR DESCRIPTION
**Pull request by pbogdan**
###### Motivation for this change

HHVM doesn't build:

- https://hydra.nixos.org/build/59511735
- https://github.com/NixOS/nixpkgs/issues/28643

/cc package maintainer @thoughtpolice 

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by fpletz** [comment]
Did you try updating HHVM?

**Comment by pbogdan** [comment]
3.15.8 - most recent release in 3.15 release series suffers from the same error, it may require adjusting the patch. I haven't tried updating to the most recent upstream release.

**Comment by pbogdan** [comment]
Even on 3.21 - most recent upstream LTS release - patching for gcc6 is still required for the bundled re2 library. Only tested briefly with a simple CLI PHP script and a simple WordPress site.

**Comment by globin** [comment]
Is it possible to use the nixpkgs re2?

**Comment by pbogdan** [comment]
@globin I haven't looked into substituting nixpkgs libraries in place of the bundled ones. In the specific case of re2 ours appears to be ~ 2 years behind the version bundled with hhvm:

- https://github.com/NixOS/nixpkgs/blob/56904d7c423f2b13b37fbd29f39bbb4b52bc7824/pkgs/development/libraries/re2/default.nix#L5
- https://github.com/google/re2/tree/718df09610fee584c9038d8d519697e507e09c9b

I haven't tried but I suspect it would require some more work beyond convincing the build system to use nipxkgs re2.

**Comment by globin** [comment]
I guess this is fine for now

**Pull request merged**
