### PR TITLE
pythonPackages.setuptools-rust: cleanup, add pythonImportsCheck

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 115009` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>python3Packages.setuptools-rust</li>
</ul>
</details>

**Comment by petabyteboy** [comment]
This broke the build of multiple dependencies of pandoc:

```
[...]
  setupCompilerEnvironmentPhase
  Build with /nix/store/fbffvqdwgprgfjrp6yfwqihpgp2dqf16-ghc-8.10.4.
  ghc-pkg: "the input" (line 1, column 1):
  unexpected character in input '\NUL'
  expecting field or section name

  builder for '/nix/store/plxrcb901d9c5nsi89zsd9pg4zp9xdn0-tree-diff-0.1.drv' failed with exit code 1
```

```
[...]
          depends bytestring-0.10.12.0
          depends optparse-applicative-0.15.1.0-1NlWv7wr2aM4qnx27SYgil
  CallStack (from HasCallStack):
    dieNoWrap, called at libraries/Cabal/Cabal/Distribution/Utils/LogProgress.hs:61:9 in Cabal-3.2.1.0:Distribution.Utils.LogProgress
  Error:
      The following packages are broken because other packages they depend on are missing. These broken packages must be rebuilt before they can be used.
  installed package aeson-1.5.6.0 is broken due to missing package time-compat-1.9.5-I1tHGrNfoIT6zPhkHvFW8y
  installed package quickcheck-instances-0.3.25.2 is broken due to missing package time-compat-1.9.5-I1tHGrNfoIT6zPhkHvFW8y

  builder for '/nix/store/f7msjndps86nxisa9llp1dhqx7g27hdb-aeson-diff-1.1.0.9.drv' failed with exit code 1
```

```
[...]
  setupCompilerEnvironmentPhase
  Build with /nix/store/fbffvqdwgprgfjrp6yfwqihpgp2dqf16-ghc-8.10.4.
  ghc-pkg: "the input" (line 1, column 1):
  unexpected character in input '\NUL'
  expecting field or section name

  builder for '/nix/store/c3xwaw1sl9hwg4sqpv5saj814qs2xr10-microlens-aeson-2.3.1.drv' failed with exit code 1
```

I'm not sure if they are exposed in the top-level attribute set.

**Comment by SuperSandro2000** [comment]
This should have gone into staging...

**Comment by danieldk** [comment]
The `nixpkgs-review` output also seems wrong? At least the `tokenizers` Python package is dependent on `setuptools-rust`.

**Comment by danieldk** [comment]
> This broke the build of multiple dependencies of pandoc:

How? Does any part of the Haskell or pandoc ecosystems rely indirectly on setuptools-rust?

**Comment by petabyteboy** [comment]
> > This broke the build of multiple dependencies of pandoc:
> 
> How? Does any part of the Haskell or pandoc ecosystems rely indirectly on setuptools-rust?

Yes. This change caused a reboot of GHC and thus all haskellPackages.

**Comment by SuperSandro2000** [comment]
Can we somehow make ghc not depend on swtuptools-rust?

**Comment by danieldk** [comment]
> Can we somehow make ghc not depend on swtuptools-rust?

It seems that `ghc` depends on `sphinx` for documentation generation, `sphinx` depends on `requests`, which in turn has `cryptography` as a transitive dependency. `cryptography` is now built with `setuptools-rust`.

**Comment by danieldk** [comment]
> It seems that `ghc` depends on `sphinx` for documentation generation, `sphinx` depends on `requests`, which in turn has `cryptography` as a transitive dependency. `cryptography` is now built with `setuptools-rust`.

It seems like this is a good example where an intensional/content-addressed store would help. Changes to `setuptools-rust` typically do not have any bearing on the compiled Python modules. So, a change to `setuptools-rust` wouldn't trigger a rebuild of `ghc` + all packages that use `ghc`.

**Pull request merged**
