### PR TITLE
Switch the default Haskell package set to GHC 7.10.1.

### PR DESCRIPTION
**Pull request by peti**
Hydra builds for this branch are running at http://hydra.cryp.to/jobset/nixpkgs/haskell-updates-ghc7101.

### CODE REVIEW

**Comment by jagajaga** [comment]
:beers:

**Comment by aszlig** [comment]
:+1: I'm on 7.10.1 for quite a while and improves the problem with non-deterministic package IDs a lot! Thanks a lot for the work on Haskell (NG) packaging.

**Comment by abbradar** [comment]
:+1: I've fixed/workarounded some things to prepare for this PR applied. There is also a strange issue -- I can't build `ghc784.transformers-compat` from your tree:
```
 nixpkgs git:(haskell-updates-ghc7101) ✗ nix-build -A haskell-ng.packages.ghc784.transformers-compat ~/nixpkgs
these derivations will be built:
  /nix/store/lcfvxq9q79g34slfd91jg0mywjhckkvy-haskell-transformers-compat-0.4.0.4.drv
building path(s) ‘/nix/store/1rfg2gadxvhwzwl8xsvdxsiwz2pn31ff-haskell-transformers-compat-0.4.0.4’
setupCompilerEnvironmentPhase
Build with /nix/store/rnxk1a1bz4rgy1rw4973blbfp9f0ic89-ghc-7.8.4.
unpacking sources
unpacking source archive /nix/store/hxwh9akki7spiccyya7m5fsxv5bz416d-transformers-compat-0.4.0.4.tar.gz
source root is transformers-compat-0.4.0.4
patching sources
compileBuildDriverPhase
setupCompileFlags: -package-db=/tmp/nix-build-haskell-transformers-compat-0.4.0.4.drv-0/package.conf.d -j4
[1 of 1] Compiling Main             ( Setup.lhs, /tmp/nix-build-haskell-transformers-compat-0.4.0.4.drv-0/Main.o )
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/1rfg2gadxvhwzwl8xsvdxsiwz2pn31ff-haskell-transformers-compat-0.4.0.4 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --with-gcc=gcc --package-db=/tmp/nix-build-haskell-transformers-compat-0.4.0.4.drv-0/package.conf.d --ghc-option=-optl=-Wl,-rpath=/nix/store/1rfg2gadxvhwzwl8xsvdxsiwz2pn31ff-haskell-transformers-compat-0.4.0.4/lib/ghc-7.8.4/transformers-compat-0.4.0.4 --enable-split-objs --disable-library-profiling --enable-shared --enable-library-vanilla --enable-executable-dynamic --enable-tests -fthree
Configuring transformers-compat-0.4.0.4...
Setup: At least the following dependencies are missing:
mtl ==2.1.*
builder for ‘/nix/store/lcfvxq9q79g34slfd91jg0mywjhckkvy-haskell-transformers-compat-0.4.0.4.drv’ failed with exit code 1
error: build of ‘/nix/store/lcfvxq9q79g34slfd91jg0mywjhckkvy-haskell-transformers-compat-0.4.0.4.drv’ failed
```

**Comment by peti** [comment]
@abbradar, the `transformers-compat` library needs `mtl` as an additional build input when built in "three" mode. 0a0d97f71db3881c95c93e8dbe08bb87e397dc7e fixes that. Thanks for the bug report!

**Comment by abbradar** [comment]
Ah, I've checked `mtl` version in `configuration-ghc-7.8.x.nix` but haven't thought to check if `transformers-compat` actually lists it as a dependency! Thanks for the fix.

**Pull request merged**
