### PR TITLE
libreoffice-fresh: 7.4.2.3 -> 7.5.2.2

### LINKED ISSUE #221008: Update request: various libreoffice packages
I'm not using the regular form as libreoffice-(fresh|still|qt) are all affected.

 - fresh is v7.4.2.3 in unstable but should be 7.5.2.1
 - still is v7.3.7.2 but should be 7.4.6.2

I will not have time to look at this in the next 2 weeks or so, so just putting out there for others.

Cc: @doronbehar @7c6f434c

### PR DESCRIPTION
**Pull request by doronbehar**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by peterhoeg** [comment]
@GrahamcOfBorg build libreoffice-qt

**Comment by doronbehar** [comment]
I needed to also update the other srcs that a Python script grabs their hashes.. I also removed the patches for the `still` variant. Some more changes and now the `configurePhase` is successful. Haven't tested the full build yet.

**Comment by doronbehar** [comment]
@GrahamcOfBorg build libreoffice-fresh

**Comment by doronbehar** [comment]
Oh It's `sdext_pdfimport` cppunit test failling. I only found this link to a bug report which was not attended:

https://bugs.documentfoundation.org/show_bug.cgi?id=117014

**Comment by 7c6f434c** [comment]
Yeah, can't find a matching post in the mailing list. I guess it is fine to add it to our long (but pretty negligible as a fraction of the total test suite) list of excluded tests…

**Comment by doronbehar** [comment]
Let's see if this works..

**Comment by doronbehar** [comment]
@GrahamcOfBorg build libreoffice-qt

**Review by 7c6f434c — APPROVED** [review]
Code changes look good, hopefully not too many more tests will need to be dropped…

**Comment by doronbehar** [comment]
Had a small typo, here's another attempt.

**Comment by doronbehar** [comment]
Disabled yet another test (lucky me for not building this locally :sweat_smile: ).

**Comment by 7c6f434c** [comment]
Is the error in the main expression or in the wrapper?

**Comment by doronbehar** [comment]
I'm afraid it seems to be a problem with the unwrapped derivation. The wrapped derivation doesn't have split outputs..

**Comment by 7c6f434c** [comment]
And this is a difference between OfBorg build and local sandboxed build?? Hm, maybe Nix version is different (still wouldn't explain it, but… where even to look…)

**Comment by doronbehar** [comment]
I haven't tested the build locally at all. I don't think it'd be different then ofborg's build.

**Comment by doronbehar** [comment]
It seems that no package is using this `$dev` output - all dependents of libreoffice just use it as a program. Hence I removed it. If ofborg will build it successfully now, I'll test it locally and merge this PR.

**Comment by nashamri** [comment]
The build failed locally on my machine. This link is down:
https://download.documentfoundation.org/libreoffice/src/7.5.2/libreoffice-7.5.2.1.tar.xz

It seems that a new tweak version was released `7.5.2.2`.

**Comment by nashamri** [comment]
It builds and works fine now :+1:

**Comment by ajs124** [comment]
I think this broke the libreoffice-still build. Still investigating though.

**Comment by doronbehar** [comment]
> It builds and works fine now +1

It seems only libreoffice-fresh builds and works fine. Sorry for not mentioning `libreoffice-still` in the PR title, this could have helped this PR not get merged as is. Indeed `libreoffice-still` fails to build, as ofborg predicted as well.

**Comment by doronbehar** [comment]
Fix attempt: https://github.com/NixOS/nixpkgs/pull/225116

**Pull request merged**
