### PR TITLE
jujutsu: 0.13.0 -> 0.14.0

### PR DESCRIPTION
**Pull request by mfrw**
Signed-off-by: Muhammad Falak R Wani <falakreyaz@gmail.com>

## Description of changes
Diff: https://github.com/martinvonz/jj/compare/v0.13.0...v0.14.0
Changelog: https://github.com/martinvonz/jj/blob/v0.14.0/CHANGELOG.md

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by ambroisie — CHANGES_REQUESTED** [review]
GitHub isn't letting me comment this on the `postInstall` phase for some reason.

Quoting from the release notes:

> `jj util completion` now takes the shell as a positional argument, not a flag. the previous behavior is deprecated, but supported for now. it will be removed in the future.

We should therefore migrate our package to use that.

**Comment by mfrw** [comment]
> GitHub isn't letting me comment this on the `postInstall` phase for some reason.
> 
> Quoting from the release notes:
> 
> > `jj util completion` now takes the shell as a positional argument, not a flag. the previous behavior is deprecated, but supported for now. it will be removed in the future.
> 
> We should therefore migrate our package to use that.

Ack. Let me learn how to do that.
Thank you :)

**Review by thoughtpolice — APPROVED** [review]

**Comment by thoughtpolice** [comment]
We can wait to merge this after you'd change the `jj util completion` usage, if you'd like. But I'm also fine with merging it as-is; eventually it will be a hard error and fail but the fix is easy anyway.

**Comment by mfrw** [comment]
> We can wait to merge this after you'd change the `jj util completion` usage, if you'd like. But I'm also fine with merging it as-is; eventually it will be a hard error and fail but the fix is easy anyway.

@thoughtpolice I did an attempt at it. PTAL whenever you get a chance :)

**Review by ambroisie — APPROVED** [review]

**Review by thoughtpolice — APPROVED** [review]

**Pull request merged**
