### PR TITLE
discord-openasar: init at e087078

### PR DESCRIPTION
**Pull request by GenericNerdyUsername**
###### Description of changes

Add openasar versions to `all-packages.nix`, so build fails get picked up by ofborg/nixpkgs-review

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kranzes** [comment]
I actually think it makes more sense to make `openasar` itself a package instead of exposing 3 extra discord package variants.

**Comment by GenericNerdyUsername** [comment]
so `openasar.{stable,ptb,canary}`?

**Comment by Kranzes** [comment]
> so `openasar.{stable,ptb,canary}`?

No, openasar on its own is useless anyway just do `pkgs.discord-canary.override { withOpenASAR = true; };`.

**Comment by GenericNerdyUsername** [comment]
That isn't as searchable and changes that break the openasar version but not the vanilla version don't get picked up by nixpkgs-review or ofborg

**Comment by Kranzes** [comment]
Alright then make openasar its own package, without ptb/stable/canary, it shouldn't be part of discord.

**Comment by GenericNerdyUsername** [comment]
Wdym "it shouldn't be part of discord"? thats the only way it can work?

**Comment by Kranzes** [comment]
We shouldn't make more discord variants just for openAsar

**Comment by GenericNerdyUsername** [comment]
Why not `openasar.{stable,ptb,canary}`?

**Comment by Kranzes** [comment]
Because we don't want more discord variants than we already have, and all that OpenASAR variant does is run a single shell command in the `postInstall` phase.

**Comment by GenericNerdyUsername** [comment]
So should I just close the pull?

**Comment by Kranzes** [comment]
I think so at least...

**Pull request closed without merging**
