### PR TITLE
Wine update

### PR DESCRIPTION
**Pull request by avnik**
###### Motivation for this change

Regular wine unstable+staging update.
combined win64+win32 build (wow) tested -- my usual set of games works.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ikervagyok** [comment]
Since wine updates take forever on NixOS to land, can you update this PR to 5.5? And of course thanks for the update to 5.4.
https://www.winehq.org/pipermail/wine-devel/2020-March/163220.html

**Comment by avnik** [comment]
@ikervagyok will be 5.5 soon. I just built it, and will update PR after some testing

**Comment by avnik** [comment]
@ikervagyok for first glance 5.5 is brownbag, so stay with 5.4 if you need update fast

**Comment by avnik** [comment]
Well 5.5 is here
@ikervagyok  I withdraw my notice about brownbag

Existing prefixes may need  to invoke `wine64 wineboot.exe -u` to upgrade properly.

**Comment by ikervagyok** [comment]
@avnik thank you

**Review by veprbl — APPROVED** [review]
nixpkgs-review report on NixOS (x86_64-linux):
```
9 package built:
lutris lutris-free lutris-unwrapped pipelight wine-staging winePackages.staging winePackages.unstable wineWowPackages.staging wineWowPackages.unstable
```

**Pull request merged**
