### PR TITLE
vimPlugins: Added vim-racket and vim-lsp-cxx-highlight

### PR DESCRIPTION
**Pull request by Mazurel**
###### Motivation for this change
Plugins for using racket language https://github.com/wlangstroth/vim-racket and proper syntax highlighting for c++ for vim https://github.com/jackguo380/vim-lsp-cxx-highlight

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102947` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>21 packages built:</summary>
  <ul>
    <li>vimPlugins.ale</li>
    <li>vimPlugins.asyncomplete-vim</li>
    <li>vimPlugins.caw-vim</li>
    <li>vimPlugins.coc-nvim</li>
    <li>vimPlugins.deoplete-fish</li>
    <li>vimPlugins.deoplete-khard</li>
    <li>vimPlugins.deoplete-nvim</li>
    <li>vimPlugins.dracula-vim</li>
    <li>vimPlugins.lightline-vim</li>
    <li>vimPlugins.lsp_extensions-nvim</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.syntastic</li>
    <li>vimPlugins.vim-airline</li>
    <li>vimPlugins.vim-airline-themes</li>
    <li>vimPlugins.vim-android</li>
    <li>vimPlugins.vim-clap</li>
    <li>vimPlugins.vim-devicons</li>
    <li>vimPlugins.vim-lsp</li>
    <li>vimPlugins.vim-lsp-cxx-highlight</li>
    <li>vimPlugins.vim-polyglot</li>
    <li>vimPlugins.vim-racket</li>
  </ul>
</details>

**Comment by jonringer** [comment]
sorry, looks like I missed this, do you mind cleaning up the git history? should be 3 commits
```
update
add
add
```

Please follow [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md) and [manual#submitting-changes-making-patches ](https://nixos.org/nixpkgs/manual/#submitting-changes-making-patches) and squash the fix-up commits.

`git rebase -i` works well for this I created a small video demonstrating it's use [here](https://www.youtube.com/watch?v=OR8Q-4PLalc). A more indepth text tutorial can be found [here](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase)

**Comment by Mazurel** [comment]
I have squashed unnecessary commits. Sorry for the problem, I was using the `update.py --add` tool and it has added those empty commits, I am not really sure why.

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 102947 [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>21 packages built:</summary>  <ul>    <li>vimPlugins.ale</li>    <li>vimPlugins.asyncomplete-vim</li>    <li>vimPlugins.caw-vim</li>    <li>vimPlugins.coc-nvim</li>    <li>vimPlugins.deoplete-fish</li>    <li>vimPlugins.deoplete-khard</li>    <li>vimPlugins.deoplete-nvim</li>    <li>vimPlugins.dracula-vim</li>    <li>vimPlugins.lightline-vim</li>    <li>vimPlugins.lsp_extensions-nvim</li>    <li>vimPlugins.nvim-treesitter</li>    <li>vimPlugins.syntastic</li>    <li>vimPlugins.vim-airline</li>    <li>vimPlugins.vim-airline-themes</li>    <li>vimPlugins.vim-android</li>    <li>vimPlugins.vim-clap</li>    <li>vimPlugins.vim-devicons</li>    <li>vimPlugins.vim-lsp</li>    <li>vimPlugins.vim-lsp-cxx-highlight</li>    <li>vimPlugins.vim-polyglot</li>    <li>vimPlugins.vim-racket</li>  </ul></details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 102947` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>vimPlugins.vim-clap</li>
  </ul>
</details>

**Pull request merged**
