### PR TITLE
Revert NetworkManager to 1.42.8

### PR DESCRIPTION
**Pull request by SuperSandro2000**
## Description of changes

NetworkManager 1.44.0 does not work with the current Plasma after a restart of the NetworkManager service. It can be sometimes worked around by unloading and loading the iwlwifi kernel module but things like wpa_supplicant continue to behave buggy.

Tested this on my plasma system and after this revert things worked again.
I am open for alternatives and testing things but I couldn't figure out a better way yesterday.

see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1053707

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by amaxine** [comment]
Was this reported upstream at all? I don't see anything linked in the debian report, and I can't find anything in the nm gitlab, and I've not been able to reproduce this issue on GNOME 45.

Unfortunate timing, but i guess saves doing backports of 1.44 for the rest of 23.11 :sweat_smile:

**Review by amaxine — APPROVED** [review]

**Comment by K900** [comment]
Restarting Plasma (e.g. with `plasmashell --replace`) fixes it. I'd rather look for a fix in plasma-nm here.

**Review by K900 — CHANGES_REQUESTED** [review]
-1 on the revert, let me run it by the Plasma people first.

**Comment by SuperSandro2000** [comment]
> Was this reported upstream at all?

I couldn't find anything yet but I was also not sure what to search for exactly until now because I didn't have an error log.

> Restarting Plasma (e.g. with `plasmashell --replace`) fixes it. I'd rather look for a fix in plasma-nm here.

That is a good observation! I'd also rather fix this but if we can't fix it until the end of November the current situation is not great.

**Comment by K900** [comment]
Filed upstream: https://bugs.kde.org/show_bug.cgi?id=476323

**Comment by amaxine** [comment]
I think the revert is the only acceptable choice for 23.11, but I don't love the idea of having to hold nm back after branch off in that situation.

There's a comment on the issue mentioning Plasma 6 has this resolved - I don't follow KDE at all, so I'd appreciate if someone could weigh in as to what the timeline is for it landing in nix? The comments indicate that this is a Qt 6 fix, rather than anything in plasma-nm, and I'm not sure how Qt and plasma versions are related, if at all.

**Comment by K900** [comment]
Plasma 6 is pre-alpha, and requires Qt 6. What do you think about just not restarting NM on activation? That would be an easy workaround we can then always remove.

**Comment by vcunat** [comment]
At a superficial glance (these comments) I'd choose older NM for 23.11 and then perhaps immediately try newer one on unstable/master after fork-off.

**Comment by amaxine** [comment]
I cannot say I love the idea of potentially breaking the module as a workaround for this, and would much rather we ship 1.42.x for 23.11 - I'm not sure what all the consequences would be, but this seems like a lot to find out so close to release. The revert is safer.

I assume going back to 1.44.x asap after branch off is going to be quite irritating for KDE users on Nix though, with there being 4 more months before Plasma 6 releases. I'm not sure what the right call is there, since it's not a bug in NM but in Plasma/Qt, but that's gonna matter more a month from now and not today.

**Comment by K900** [comment]
"Revert" or "leave broken" are not our only options. I am still looking into what's causing the bug on my end.

**Comment by amaxine** [comment]
Right, I'm not hitting merge here - branch off is not for another 2.5 weeks, but if it comes to it I would rather revert than remove restarting NM on activation.

**Comment by vcunat** [comment]
1.42 vs 1.44 is a difference better not left as late as branch-off date.  There may be other packages where it matters, too.

**Comment by K900** [comment]
I think I have it.

**Comment by K900** [comment]
Please test: https://github.com/NixOS/nixpkgs/pull/264997

**Comment by SuperSandro2000** [comment]
Reopening so this is not being forgotten and because the linked PR doesn't fully fix the problem and we are really to late to have such breaking changes for the stable branch off.

**Pull request closed without merging**
