### PR TITLE
python3Packages.sqlalchemy_1: bring back 1.x for .databases

### PR DESCRIPTION
**Pull request by vcunat**
Upstream doesn't have a patch to support 2.x yet.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
I checked building `ansible_2_12 ansible_2_13 ansible_2_14` (i.e. all our versions).

**Comment by vcunat** [comment]
An alternative would be reverting the `.sqlalchemy` upgrade (commit de884ab68f1ddaa).

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 220680` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.pytest-ansible</li>
    <li>python311Packages.pytest-ansible</li>
  </ul>
</details>
<details>
  <summary>11 packages failed to build:</summary>
  <ul>
    <li>ntfy</li>
    <li>parsedmarc (python310Packages.parsedmarc)</li>
    <li>python310Packages.ormar</li>
    <li>python310Packages.slack-sdk</li>
    <li>python310Packages.slowapi</li>
    <li>python311Packages.ormar</li>
    <li>python311Packages.parsedmarc</li>
    <li>python311Packages.slack-sdk</li>
    <li>python311Packages.slowapi</li>
    <li>python311Packages.sopel</li>
    <li>theharvester</li>
  </ul>
</details>
<details>
  <summary>43 packages built:</summary>
  <ul>
    <li>ansible (python310Packages.ansible-core)</li>
    <li>ansible-later (python310Packages.ansible-later)</li>
    <li>ansible-lint (python310Packages.ansible-lint)</li>
    <li>ansible_2_12</li>
    <li>ansible_2_13</li>
    <li>etebase-server (python310Packages.etebase-server)</li>
    <li>kargo</li>
    <li>khoj</li>
    <li>python310Packages.ansible</li>
    <li>python310Packages.ansible-compat</li>
    <li>python310Packages.ansible-kernel</li>
    <li>python310Packages.ansible-runner</li>
    <li>python310Packages.aria2p</li>
    <li>python310Packages.databases</li>
    <li>python310Packages.dependency-injector</li>
    <li>python310Packages.fastapi</li>
    <li>python310Packages.fastapi-mail</li>
    <li>python310Packages.geoip2</li>
    <li>python310Packages.mocket</li>
    <li>python310Packages.orm</li>
    <li>python310Packages.sopel</li>
    <li>python310Packages.sqlalchemy_1</li>
    <li>ttp (python310Packages.ttp)</li>
    <li>python311Packages.ansible</li>
    <li>python311Packages.ansible-compat</li>
    <li>python311Packages.ansible-core</li>
    <li>python311Packages.ansible-kernel</li>
    <li>python311Packages.ansible-later</li>
    <li>python311Packages.ansible-lint</li>
    <li>python311Packages.ansible-runner</li>
    <li>python311Packages.aria2p</li>
    <li>python311Packages.databases</li>
    <li>python311Packages.dependency-injector</li>
    <li>python311Packages.etebase-server</li>
    <li>python311Packages.fastapi</li>
    <li>python311Packages.fastapi-mail</li>
    <li>python311Packages.geoip2</li>
    <li>python311Packages.mocket</li>
    <li>python311Packages.orm</li>
    <li>python311Packages.sqlalchemy_1</li>
    <li>python311Packages.ttp</li>
    <li>soco-cli</li>
    <li>spotdl</li>
  </ul>
</details>

**Review by dotlambda — CHANGES_REQUESTED** [review]
Only acceptable if we spin out ansible into its own package set. Lots of packages that aren't ansible use fastapi and might depend on sqlalchemy through some other path as well.

**Comment by mweinelt** [comment]
`ormar` and `slack-sdk` indicate a conflict.

```
       > Found duplicated packages in closure for dependency 'SQLAlchemy':
       >   SQLAlchemy 1.4.46 (/nix/store/9bd7a5xrj8jb5q1b70qx5xahgidrdw36-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages)
       >   SQLAlchemy 2.0.4 (/nix/store/i8316ag8a8bqcqb14c9pj7a02wss56ak-python3.10-SQLAlchemy-2.0.4/lib/python3.10/site-packages)
       >
       > Package duplicates found in closure, see above. Usually this happens if two packages depend on different version of the same dependency.
       For full logs, run 'nix log /nix/store/pwxj0s7l4819drnzii9ysa2ppzaiib8v-python3.10-ormar-0.12.1.drv'.
```

```
       > Found duplicated packages in closure for dependency 'SQLAlchemy':
       >   SQLAlchemy 1.4.46 (/nix/store/9bd7a5xrj8jb5q1b70qx5xahgidrdw36-python3.10-SQLAlchemy-1.4.46/lib/python3.10/site-packages)
       >   SQLAlchemy 2.0.4 (/nix/store/i8316ag8a8bqcqb14c9pj7a02wss56ak-python3.10-SQLAlchemy-2.0.4/lib/python3.10/site-packages)
       >
       > Package duplicates found in closure, see above. Usually this happens if two packages depend on different version of the same dependency.
       For full logs, run 'nix log /nix/store/qadww9advysb7kzihwlmgm2hbf8niaph-python3.10-slack-sdk-3.20.1.drv'.
```

**Comment by dotlambda** [comment]
> Only `ormar` and `slack-sdk` indicate a conflict.

In that case this is a no go for sure.

**Comment by vcunat** [comment]
I don't think this is about ansible really.  It's databases that's incompatible with sqlalchemy update.  And fastapi (and others) depend on databases.

**Pull request closed without merging**
