### PR TITLE
nodejs: 14.21.2 -> 14.21.3, 16.19.0 -> 16.19.1, 18.14.0 -> 18.14.1, 19.6.0 -> 19.6.1 

### PR DESCRIPTION
**Pull request by marsam**
###### Description of changes

https://nodejs.org/en/blog/vulnerability/february-2023-security-releases/
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by winterqt** [comment]
@marsam Do we usually send Node updates to master? I did my last change to Node on staging, maybe I shouldn't have? 🙃

**Comment by numinit** [comment]
Thanks for taking care of these CVEs. :-)

I looked at this in preparation for their release; seems that 22.11 won't just be able to do a point release, as it is on 16.18.1, 18.12.1, and 19.1.0

**Comment by winterqt** [comment]
> I looked at this in preparation for their release; seems that 22.11 won't just be able to do a point release, as it is on 16.18.1, 18.12.1, and 19.1.0

We can always (try to) backport the patches. It's a bit late for me to look at this now, but I can try to at some point tomorrow.

**Comment by numinit** [comment]
That would be helpful, I think.

**Comment by winterqt** [comment]
Might be best to just backport the minor releases though, as Node is good with their semver policy usually.

**Comment by numinit** [comment]
That is probably a better idea.

**Comment by marsam** [comment]
>Do we usually send Node updates to master? I did my last change to Node on staging, maybe I shouldn't have? 

Sorry for the delay. I think it's safe to send node updates to `master` since it's _just_ <1000 rebuilds and in some cases it just updates the shebang. 
However, if you want to check whether a change doesn't cause a major breakage or you feel it's not urgent enough, you can send it to staging.

**Comment by lilyinstarlight** [comment]
> Sorry for the delay. I think it's safe to send node updates to `master` since it's _just_ <1000 rebuilds and in some cases it just updates the shebang. However, if you want to check whether a change doesn't cause a major breakage or you feel it's not urgent enough, you can send it to staging.

While I think they are safe to send to `master` from a rebuild count standpoint (and CVE fixes should definitely go to `master`), it would be nice to send non-security-fixes to `staging` since Node.js takes forever to build locally

I've known several people (including myself) to pull from `master` when preparing a PR or fixing merge conflicts, but end up having to wait an hour or two rebuilding Node.js if it went straight to `master` and Hydra hadn't built/cached it yet

Thoughts?

**Comment by alyssais** [comment]
> I've known several people (including myself) to pull from `master` when preparing a PR or fixing merge conflicts, but end up having to wait an hour or two rebuilding Node.js if it went straight to `master` and Hydra hadn't built/cached it yet

It's hopefully pretty rare that you _need_ master to make a PR.  Usually nixos-unstable or `git merge-base origin/master origin/staging` (which is nice because then you can change the PR base without all hell breaking loose) is enough.  Are you often finding that you want to make or fix merge conflicts in node-related PRs that need a more recent commit than unstable?

**Comment by lilyinstarlight** [comment]
> It's hopefully pretty rare that you _need_ master to make a PR. Usually nixos-unstable or `git merge-base origin/master origin/staging` (which is nice because then you can change the PR base without all hell breaking loose) is enough. Are you often finding that you want to make or fix merge conflicts in node-related PRs that need a more recent commit than unstable?

It is not often, no, but has occured (and I've experienced it with other "big" packages that get merged directly to `master` and aren't leaves in the dependency tree). It's not the biggest bother for me personally, but I do notice people in Matrix and Discord and such end up rebuilding Node.js to test their PR so I brought it up

Also nixpkgs-review defaults to building from `master` so I do have to manually get it to retarget against another branch sometimes because of that (but obviously that can also be worked around)

**Comment by alyssais** [comment]
> It's not the biggest bother for me personally, but I do notice people in Matrix and Discord and such end up rebuilding Node.js to test their PR so I brought it up

I think it's probably best to spread awareness that master is not the best PR base — putting every big package through staging would mean that lots more updates took several weeks earlier to reach users, which I think would cause more annoyance overall.  (Plus, more packages coming through staging means more work for us to do when trying to stabilize a new staging-next, which is already a scarily big job.)

> Also nixpkgs-review defaults to building from `master` so I do have to manually get it to retarget against another branch sometimes because of that (but obviously that can also be worked around)

Or changed, if upstream is open to it!

**Comment by lilyinstarlight** [comment]
> I think it's probably best to spread awareness that master is not the best PR base — putting every big package through staging would mean that lots more updates take several weeks longer to reach users, which I think would cause more annoyance overall.

This is just one additional package that touches a ton of stuff (I really would *not* like to try to do that for every big package)

But it was more an idle thought either way rather than an actual argument, so if that's undesired then it's fine enough with me

**Pull request merged**
