### PR TITLE
freerdp: 2.0.0 -> 2.1.0

### PR DESCRIPTION
**Pull request by lheckemann**
###### Motivation for this change
New upstream release

###### Things done

- [x] Build on NixOS
- [x] Tested bin/wlfreerdp
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
* ANN: https://www.freerdp.com/2020/05/08/2_1_0-released
* Changes: https://github.com/FreeRDP/FreeRDP/blob/2.1.0/ChangeLog
* Contains CVE fixes

**Comment by mweinelt** [comment]
NixOS 20.03 has 2.0.0-rc4, which additionally suffers from security issues fixed in 2.0.0. We can apply 10+ patches on top of 2.0.0-rc4 or upgrade to 2.1.0. Upgrading to 2.1.0 feels more straightforward and less complex to me.

**Comment by FRidh** [comment]
> Upgrading to 2.1.0 feels more straightforward and less complex to me.

If there are no regressions we can consider it.

**Comment by lheckemann** [comment]
#87392

**Pull request merged**
