### PR TITLE
elmPackages.elm-{language-server,tooling,review}: Update versions

### PR DESCRIPTION
**Pull request by andys8**
###### Motivation for this change

Smaller updates for elm tooling versions

```
elm-language-server: 2.0.2 -> 2.0.3
elm-tooling: 1.1.0 -> 1.2.0
elm-review: 2.4.1 -> 2.4.2
```

###### Things done

Ran the script to update package version from npm

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 113018` at c4a3e021 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/6ea6f905aedfb661d2d84999891802c0">elmPackages.create-elm-app</a></li></li>
    <li><a href="https://gist.github.com/3532030cc05a0a26326e01a60cebb47e">elmPackages.elm-analyse</a></li></li>
    <li><a href="https://gist.github.com/222850e3898c45be34ed099504170a84">elmPackages.elm-coverage</a></li></li>
    <li><a href="https://gist.github.com/3593826c86f40fa04efd30444b7862c4">elmPackages.elm-language-server</a></li></li>
    <li><a href="https://gist.github.com/f37f492a3e27b1d884d307fd36d806d1">elmPackages.elm-optimize-level-2</a></li></li>
    <li><a href="https://gist.github.com/e904b6fd49330233b12f17fccf735f64">elmPackages.elm-review</a></li></li>
    <li><a href="https://gist.github.com/c4aee43d9025a82d9286d29aab23ef55">elmPackages.elm-test</a></li></li>
    <li><a href="https://gist.github.com/c6e3a6aee1d1762d0dcc887b6662b23d">elmPackages.elm-upgrade</a></li></li>
    <li><a href="https://gist.github.com/362d73f92fdb7145af035ee18c3eb3d9">elmPackages.elm-verify-examples</a></li></li>
    <li><a href="https://gist.github.com/3b1b0d18388be12b45e3c265c99e23c3">elmPackages.elm-xref</a></li></li>
  </ul>
</details>
<details>
  <summary>13 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/compilers/elm/packages/node-packages.nix:12248:5:
```
      |
12248 |     meta = {
      |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/compilers/elm/packages/node-packages.nix:12756:5:
```
      |
12756 |     meta = {
      |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/compilers/elm/packages/node-packages.nix:12938:5:
```
      |
12938 |     meta = {
      |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/compilers/elm/packages/node-packages.nix:13019:5:
```
      |
13019 |     meta = {
      |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/compilers/elm/packages/node-packages.nix:13214:5:
```
      |
13214 |     meta = {
      |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/compilers/elm/packages/node-packages.nix:13258:5:
```
      |
13258 |     meta = {
      |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/compilers/elm/packages/node-packages.nix:15040:5:
```
      |
15040 |     meta = {
      |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/compilers/elm/packages/node-packages.nix:15096:5:
```
      |
15096 |     meta = {
      |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/compilers/elm/packages/node-packages.nix:15250:5:
```
      |
15250 |     meta = {
      |     ^
```
</li>
    <li>warning: unused-argument

Unused argument: `fetchgit`.
Near pkgs/development/compilers/elm/packages/node-packages.nix:3:21:
```
  |
3 | {nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:
  |                     ^
```
</li>
    <li>warning: unused-argument

Unused argument: `lib`.
Near pkgs/development/compilers/elm/packages/node-packages.nix:3:54:
```
  |
3 | {nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:
  |                                                      ^
```
</li>
    <li>warning: unused-argument

Unused argument: `nix-gitignore`.
Near pkgs/development/compilers/elm/packages/node-packages.nix:3:31:
```
  |
3 | {nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:
  |                               ^
```
</li>
    <li>warning: unused-argument

Unused argument: `stdenv`.
Near pkgs/development/compilers/elm/packages/node-packages.nix:3:46:
```
  |
3 | {nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:
  |                                              ^
```
</li>
  </ul>
</details>

**Comment by turboMaCk** [comment]
@GrahamcOfBorg build elmPackages

**Comment by turboMaCk** [comment]
Tested on NixOS & MacOS works just fine. Thanks @andys8 :hand: 

@domenkozar good to be merged. Thanks.

**Comment by turboMaCk** [comment]
hmm this one is getting old. I'm making not to check dependencies again and make sure it gets in.

**Comment by turboMaCk** [comment]
@andys8 Seems there were some updates since this PR was opened. Could you please rerun the generator script again? I would pefer if we could just update this PR rather than close it and open another - I don't want to steal this from you. If you don't have time no worries. I can open a new one.

**Comment by andys8** [comment]
@turboMaCk Updated. Feel free to update or create a new PR for future updates. It's not stealing 🙂

**Comment by turboMaCk** [comment]
thanks :+1: I want to get your PR merged for my own sake. I don't want to be the only one maintaining this part of nixpkgs :D

**Comment by andys8** [comment]
I'm working with Haskell and PureScript nowadays. So currently, I'd only run the script and see what changed.

Are there more Elm-Nix people you could think of involving? Maybe Brian Hicks?

**Comment by turboMaCk** [comment]
@andys8 At the moment it's fairly manageable for me to maintain this so I did not proactively looked for help but thanks. Brian did contacted me about few things on elm Slack. I'm not actively looking for help but I would be more than happy to see more people getting involved for sake of both elm and nixos projects.

**Comment by turboMaCk** [comment]
@GrahamcOfBorg build elmPackages

**Comment by domenkozar** [comment]
Hey, sorry I missed this (not really sure what happens). Just ping me again if it happens.

**Comment by turboMaCk** [comment]
no worries. I would ping you earlier but I kind of forgot about this myself. I also don't want to be too pushy because I know you already have a lot of things to take care of. I guess we will need to find a right balance in both frequency of these updates and pings to you as a committer. Anyway thanks a lot for a merge - appreciated.

**Pull request merged**
