### PR TITLE
staging-next-23.05 iteration 9 - 2023-10-10

### PR DESCRIPTION
**Pull request by vcunat**
- workflow docs: https://nixos.org/manual/nixpkgs/stable/#submitting-changes-stable-release-branches
- important job: https://hydra.nixos.org/job/nixpkgs/staging-next-23.05/unstable#tabs-constituents
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next-23.05
  https://hydra.nixos.org/jobset/nixos/staging-next-23.05-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next-23.05 PR: https://github.com/NixOS/nixpkgs/pull/254997
- - - 
##### Significant breakages
(will be edited based on progress)

### CODE REVIEW

**Comment by vcunat** [comment]
I hope that the python bumps won't cause trouble.

Still waiting for tomorrow's fixes for `curl`.  Everything that won't be rebuilt due to that is being prepared in https://hydra.nixos.org/eval/1800270

**Comment by vcunat** [comment]
I believe we're good enough now, for linux at least.  With darwins there are at least 30k builds still missing, but likelihood of something really major seems low and some of the security fixes seem... relatively important.

**Comment by ajs124** [comment]
This seems to have broken cross compilation of (some) things that depend on libcurl somehow, e.g.:
```
tpm2-tss> checking for strndup... yes
tpm2-tss> checking for reallocarray... yes
tpm2-tss> checking for libcrypto >= 1.1.0... yes
tpm2-tss> checking for EVP_sm3 in -lcrypto... yes
tpm2-tss> checking for json-c... yes
tpm2-tss> checking for libcurl... no
tpm2-tss> configure: error: Package requirements (libcurl) were not met:
tpm2-tss> 
tpm2-tss> Package 'libcurl' has no Name: field
tpm2-tss> 
tpm2-tss> Consider adjusting the PKG_CONFIG_PATH environment variable if you
tpm2-tss> installed software in a non-standard prefix.
tpm2-tss> 
tpm2-tss> Alternatively, you may set the environment variables CURL_CFLAGS
tpm2-tss> and CURL_LIBS to avoid the need to call pkg-config.
tpm2-tss> See the pkg-config man page for more details.
```

**Comment by vcunat** [comment]
That's really weird.  I see no change in `libcurl.pc` (except hashes and versions of dependencies).  It would also be surprising given the curl diff on nix level, only 87ef095bdd15612e839c03b5de0332b7636807a5

I wonder if it's another instance of /nix/store hashes matching a hacky regex, or something similar.

**Comment by ajs124** [comment]
bisect points to 87ef095bdd15612e839c03b5de0332b7636807a5, but I agree, that shouldn't break like that.

I'll see what else I can find.

**Comment by vcunat** [comment]
I suggest building with `--keep-failed` and looking at `config.log` (or how it's called).

**Comment by vcunat** [comment]
I actually only looked at `libcurl.pc` in normal non-cross builds, so maybe...

**Comment by ajs124** [comment]
`lib/pkgconfig/libcurl.pc` is just null bytes for me, in the cross build.

Maybe it's just my build environment after all :thinking: 
If so, sorry for the noise.

**Comment by vcunat** [comment]
Some filesystem issues were causing similar things IIRC.

**Comment by ajs124** [comment]
Yup. Seems to have been something like that. Oops.

**Pull request merged**
