### PR TITLE
pipewire: 0.3.32 -> 0.3.33

### PR DESCRIPTION
**Pull request by Kranzes**
###### Motivation for this change
Updated Pipewire to the latest version at the time of making this PR.
Note: In order for Pipewire 0.3.33 to build i had to package libfreeaptx, since pipewire now uses libfreeaptx instead of libopenaptx.

Also added myself as a second maintainer to the Pipewire package.
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kranzes** [comment]
This change requires packaging libfreeaptx.

**Comment by jansol** [comment]
Are there any default config changes that require updating the JSON files in the nixos module?

**Comment by Kranzes** [comment]
No there shouldn't be any difference this is just a hotfix release.
Also read this:

```
libfreeaptx is based on version 0.2.0 of libopenaptx with the intent of continuing
under a free license without the additional license restriction added to 0.2.1. The
initial version of libfreeaptx was reset to 0.1.0 to prevent confusion between the
two projects.

**Comment by jansol** [comment]
Looks like there *are* indeed some config changes. Please build `pipewire` and `pipewire.mediaSession` and copy the .conf.json files from the nix-support directories in the result symlinks (result and result-mediaSession on my nix version) to `nixos/modules/services/desktop/pipewire`. If you get a permission error, just chmod+w the problematic files and try again. The files in the symlink are read-only and copying them to the module keeps that restriction so it's possible the files in the module can't be overwritten directly if the previous updater has been careless.

**Comment by Kranzes** [comment]
Done.

**Review by jansol — APPROVED** [review]
Diff looks good, rebuilt my system with this PR applied and everything is working so far. Note that port names in Pro Audio profile have changed once more. (playback_n to playback_AUXn etc)

**Pull request merged**
