### PR TITLE
vimPlugins.vim-emacs-bindings: init at 2016-10-07

### PR DESCRIPTION
**Pull request by taranarmo**
Add vim plugin adding emacs bindings to insert mode
https://github.com/kentarosasaki/vim-emacs-bindings

Locally updated vim plugins with `nix run .\#vimPluginsUpdater` and tested the package functionality inside
```
nix-shell -p 'vim-full.customize{
  vimrcConfig.packages.myVimPackage = with pkgs.vimPlugins; {
     start = [ vim-emacs-bindings ];
  };
}' -I nixpkgs=`pwd`
```

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by PerchunPak** [comment]
Hi @taranarmo,

Would you mind rebasing this PR when you have a moment? Also, could you please add an entry to `generated.nix`? Just run `nix-shell -p vimPluginsUpdater --run 'vim-plugins-updater -n'
` and make sure to include only the changes related to this plugin. Thanks!

If it's not something you're concerned about anymore, feel free to close the PR—no worries at all. I totally understand if too much time has passed.

**Comment by PerchunPak** [comment]
Please, use rebase instead of merge

```sh
git reset --hard HEAD~1 # deletes your merge commit
git rebase upstream/master

**Comment by taranarmo** [comment]
@PerchunPak, sorry for disturbance, I though Github will do the rebase but instead it created a merge commit. Let me fetch the upstream and rebase onto it as well as update the `generated.nix`.

**Comment by taranarmo** [comment]
`vimPluginsUpdater` is failing as https://github.com/andsild/peskcolor.vim returns 404. Is it possible to bypass this?

**Comment by PerchunPak** [comment]
Yes, here I filled data manually. I will also create a PR for that 404

```nix
  vim-emacs-bindings = buildVimPlugin {
    pname = "vim-emacs-bindings";
    version = "2016-10-07";
    src = fetchFromGitHub {
      owner = "kentarosasaki";
      repo = "vim-emacs-bindings";
      rev = "a8037ef1b0cc0eca9aca15d4e2cab6d462aa57ee";
      sha256 = "18bhcvs5vnrr394waz9mg2fdnrycsc2ng589s2jw892pap9zxq36";
    };
    meta.homepage = "https://github.com/kentarosasaki/vim-emacs-bindings/";
  };
```

**Comment by taranarmo** [comment]
Done, insert into `generated.nix` in alphabetic order and amend the previous commit

**Review by PerchunPak — APPROVED** [review]
LGTM! Thanks!

[CC](https://github.com/NixOS/nixpkgs/pull/333817#issuecomment-2294798601) @GaetanLepage

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 267414` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>vimPlugins.vim-emacs-bindings</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Review by GaetanLepage — APPROVED** [review]

**Pull request merged**
