### PR TITLE
python3Packages: fix vulnerabilities or mark insecure

### PR DESCRIPTION
**Pull request by dotlambda**
###### Description of changes
I used [PyPI's JSON API](https://warehouse.pypa.io/api-reference/json.html#project) to list all of our Python packages with known CVEs.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
but we need to target staging

**Comment by mweinelt** [comment]
I honestly don't get the 500 packages metric. You apply it to a package changing a single package. Now here we modify 13 packages and we still may only target 500 packages?

**Comment by dotlambda** [comment]
I can file a separate PR for the ones that cause e.g. more than 1000 rebuilds. But I won't have time for that today.

**Comment by dotlambda** [comment]
The [bottle upgrade](https://github.com/NixOS/nixpkgs/pull/178394/commits/fe2c69a71f5c1774df96cbd0e74fcb221c6433ae) was the only one causing a lot of rebuilds, e.g. because urllib3 transitively depends on it.

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 178394` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages marked as broken and skipped:</summary>
  <ul>
    <li>apache-airflow</li>
    <li>gnome.gnome-documents</li>
    <li>python310Packages.apache-airflow</li>
    <li>python310Packages.beaker</li>
    <li>python310Packages.mapbox</li>
    <li>python310Packages.pyramid_beaker</li>
    <li>python39Packages.apache-airflow</li>
    <li>python39Packages.beaker</li>
    <li>python39Packages.mapbox</li>
    <li>python39Packages.pyramid_beaker</li>
    <li>zerobin</li>
    <li>zeronet</li>
  </ul>
</details>
<details>
  <summary>37 packages failed to build:</summary>
  <ul>
    <li>aws-sam-cli</li>
    <li>etesync-dav</li>
    <li>ib-controller</li>
    <li>ioccheck</li>
    <li>maigret</li>
    <li>manim</li>
    <li>python310Packages.arviz</li>
    <li>python310Packages.batchspawner</li>
    <li>python310Packages.dockerspawner</li>
    <li>python310Packages.graphite_api</li>
    <li>python310Packages.influxgraph</li>
    <li>python310Packages.jupyterhub</li>
    <li>python310Packages.jupyterhub-ldapauthenticator</li>
    <li>python310Packages.jupyterhub-systemdspawner</li>
    <li>python310Packages.jupyterhub-tmpauthenticator</li>
    <li>python310Packages.jupyterlab</li>
    <li>python310Packages.jupyterlab-git</li>
    <li>python310Packages.jupyterlab-lsp</li>
    <li>python310Packages.jupyterlab_server</li>
    <li>python310Packages.jupytext</li>
    <li>python310Packages.oauthenticator</li>
    <li>python310Packages.pymc</li>
    <li>python310Packages.pyramid_hawkauth</li>
    <li>python39Packages.elegy</li>
    <li>python39Packages.graphite_api</li>
    <li>python39Packages.influxgraph</li>
    <li>python39Packages.jupyterlab</li>
    <li>python39Packages.jupyterlab-git</li>
    <li>python39Packages.jupyterlab-lsp</li>
    <li>python39Packages.jupyterlab_server</li>
    <li>python39Packages.jupytext</li>
    <li>python39Packages.pymc</li>
    <li>python39Packages.pyramid_hawkauth</li>
    <li>python39Packages.treex</li>
    <li>spring</li>
    <li>springLobby</li>
    <li>wolfram-notebook</li>
  </ul>
</details>
<details>
  <summary>288 packages built:</summary>
  <ul>
    <li>adapta-gtk-theme</li>
    <li>ankisyncd</li>
    <li>arc-theme</li>
    <li>arx-libertatis</li>
    <li>asciidoc-full</li>
    <li>asciidoc-full-with-plugins</li>
    <li>awslimitchecker</li>
    <li>ayu-theme-gtk</li>
    <li>buildbot (python310Packages.buildbot)</li>
    <li>buildbot-full (python310Packages.buildbot-full)</li>
    <li>buildbot-ui (python310Packages.buildbot-ui)</li>
    <li>capitaine-cursors</li>
    <li>ceph (ceph-dev)</li>
    <li>ceph-client</li>
    <li>ceph-csi</li>
    <li>cinnamon.cinnamon-screensaver</li>
    <li>cinnamon.iso-flags-png-320x420</li>
    <li>cinnamon.iso-flags-svg</li>
    <li>clevis</li>
    <li>cloudflare-dyndns (python310Packages.cloudflare-dyndns)</li>
    <li>cmake-language-server</li>
    <li>commitizen</li>
    <li>cookiecutter (python310Packages.cookiecutter)</li>
    <li>cwltool</li>
    <li>dblatexFull</li>
    <li>deluge (deluge-2_x)</li>
    <li>devpi-client</li>
    <li>devpi-server</li>
    <li>diffoscope</li>
    <li>diffoscopeMinimal</li>
    <li>disorderfs</li>
    <li>emojione</li>
    <li>errbot</li>
    <li>fava</li>
    <li>fim</li>
    <li>flexget</li>
    <li>grass</li>
    <li>home-assistant-component-tests.airnow</li>
    <li>home-assistant-component-tests.eafm</li>
    <li>home-assistant-component-tests.geocaching</li>
    <li>home-assistant-component-tests.github</li>
    <li>home-assistant-component-tests.iqvia</li>
    <li>home-assistant-component-tests.meteo_france</li>
    <li>home-assistant-component-tests.modern_forms</li>
    <li>home-assistant-component-tests.onboarding</li>
    <li>home-assistant-component-tests.openuv</li>
    <li>home-assistant-component-tests.overkiz</li>
    <li>home-assistant-component-tests.prosegur</li>
    <li>home-assistant-component-tests.radio_browser</li>
    <li>home-assistant-component-tests.roku</li>
    <li>home-assistant-component-tests.simplisafe</li>
    <li>home-assistant-component-tests.tesla_wall_connector</li>
    <li>home-assistant-component-tests.toon</li>
    <li>home-assistant-component-tests.velbus</li>
    <li>home-assistant-component-tests.wled</li>
    <li>home-assistant-component-tests.yale_smart_alarm</li>
    <li>ihaskell</li>
    <li>inkscape</li>
    <li>inkscape-extensions.applytransforms</li>
    <li>inkscape-with-extensions</li>
    <li>iso-flags</li>
    <li>isso</li>
    <li>jupyter</li>
    <li>k40-whisperer</li>
    <li>kabeljau</li>
    <li>rep (kakounePlugins.rep)</li>
    <li>kicad-small</li>
    <li>kicad-unstable-small</li>
    <li>krop</li>
    <li>libceph</li>
    <li>luksmeta</li>
    <li>mate.mate-utils</li>
    <li>metamorphose2</li>
    <li>mnemosyne</li>
    <li>mojave-gtk-theme</li>
    <li>numix-cursor-theme</li>
    <li>numix-solarized-gtk-theme</li>
    <li>odoo</li>
    <li>pdf-quench</li>
    <li>pip-audit</li>
    <li>plata-theme</li>
    <li>playonlinux</li>
    <li>poetry2conda (python310Packages.poetry2conda)</li>
    <li>pop-gtk-theme</li>
    <li>pypiserver (python310Packages.pypiserver)</li>
    <li>python310Packages.Nikola</li>
    <li>python310Packages.aioeafm</li>
    <li>python310Packages.aiogithubapi</li>
    <li>python310Packages.aiohttp-apispec</li>
    <li>python310Packages.aiomodernforms</li>
    <li>python310Packages.ansible-kernel</li>
    <li>python310Packages.aria2p</li>
    <li>python310Packages.augmax</li>
    <li>python310Packages.backoff</li>
    <li>python310Packages.cachecontrol</li>
    <li>python310Packages.censys</li>
    <li>python310Packages.cheroot</li>
    <li>python310Packages.cherrypy</li>
    <li>python310Packages.cornice</li>
    <li>python310Packages.cypherpunkpay</li>
    <li>python310Packages.deform</li>
    <li>python310Packages.diagrams</li>
    <li>python310Packages.einops</li>
    <li>python310Packages.expecttest</li>
    <li>python310Packages.flask-caching</li>
    <li>python310Packages.flask-common</li>
    <li>python310Packages.functorch</li>
    <li>python310Packages.geocachingapi</li>
    <li>python310Packages.hypothesis-auto</li>
    <li>python310Packages.inkex</li>
    <li>python310Packages.jedi-language-server</li>
    <li>python310Packages.jupyter</li>
    <li>python310Packages.jupyter-lsp</li>
    <li>python310Packages.jupyter-server-mathjax</li>
    <li>python310Packages.jupyter_server</li>
    <li>python310Packages.jupyterlab_launcher</li>
    <li>python310Packages.kicad</li>
    <li>python310Packages.mesa</li>
    <li>python310Packages.meteofrance-api</li>
    <li>python310Packages.nbclassic</li>
    <li>python310Packages.nbdime</li>
    <li>python310Packages.nix-kernel</li>
    <li>python310Packages.notebook</li>
    <li>python310Packages.notedown</li>
    <li>python310Packages.nplusone</li>
    <li>python310Packages.pdfposter</li>
    <li>python310Packages.pecan</li>
    <li>python310Packages.phik</li>
    <li>python310Packages.pipenv-poetry-migrate</li>
    <li>python310Packages.poetry</li>
    <li>python310Packages.pyairnow</li>
    <li>python310Packages.pyalgotrade</li>
    <li>python310Packages.pyiqvia</li>
    <li>python310Packages.pylxd</li>
    <li>python310Packages.pyopenuv</li>
    <li>python310Packages.pyoverkiz</li>
    <li>python310Packages.pypdf2</li>
    <li>python310Packages.pyprosegur</li>
    <li>python310Packages.pypugjs</li>
    <li>python310Packages.pyramid</li>
    <li>python310Packages.pyramid_chameleon</li>
    <li>python310Packages.pyramid_exclog</li>
    <li>python310Packages.pyramid_jinja2</li>
    <li>python310Packages.pyramid_mako</li>
    <li>python310Packages.pyramid_multiauth</li>
    <li>python310Packages.radios</li>
    <li>python310Packages.rencode</li>
    <li>python310Packages.requests-unixsocket</li>
    <li>python310Packages.rokuecp</li>
    <li>python310Packages.schema-salad</li>
    <li>python310Packages.scikit-bio</li>
    <li>python310Packages.simplisafe-python</li>
    <li>spyder (python310Packages.spyder)</li>
    <li>python310Packages.tesla-wall-connector</li>
    <li>python310Packages.teslajsonpy</li>
    <li>python310Packages.toonapi</li>
    <li>python310Packages.vega</li>
    <li>python310Packages.velbus-aio</li>
    <li>python310Packages.versionfinder</li>
    <li>python310Packages.waitress</li>
    <li>python310Packages.waitress-django</li>
    <li>python310Packages.web</li>
    <li>python310Packages.webargs</li>
    <li>python310Packages.webtest</li>
    <li>python310Packages.webtest-aiohttp</li>
    <li>python310Packages.wled</li>
    <li>python310Packages.ws4py</li>
    <li>python310Packages.wxPython_4_1</li>
    <li>python310Packages.xarray-einstats</li>
    <li>xml2rfc (python310Packages.xml2rfc)</li>
    <li>python310Packages.yalesmartalarmclient</li>
    <li>python39Packages.Nikola</li>
    <li>python39Packages.aioeafm</li>
    <li>python39Packages.aiogithubapi</li>
    <li>python39Packages.aiohttp-apispec</li>
    <li>python39Packages.aiomodernforms</li>
    <li>python39Packages.ansible-kernel</li>
    <li>python39Packages.aria2p</li>
    <li>python39Packages.arviz</li>
    <li>python39Packages.augmax</li>
    <li>python39Packages.backoff</li>
    <li>python39Packages.batchspawner</li>
    <li>python39Packages.buildbot</li>
    <li>python39Packages.buildbot-full</li>
    <li>python39Packages.buildbot-ui</li>
    <li>python39Packages.cachecontrol</li>
    <li>python39Packages.censys</li>
    <li>python39Packages.cheroot</li>
    <li>python39Packages.cherrypy</li>
    <li>python39Packages.cloudflare-dyndns</li>
    <li>python39Packages.cookiecutter</li>
    <li>python39Packages.cornice</li>
    <li>python39Packages.cypherpunkpay</li>
    <li>python39Packages.dalle-mini</li>
    <li>python39Packages.deform</li>
    <li>python39Packages.diagrams</li>
    <li>python39Packages.dockerspawner</li>
    <li>python39Packages.einops</li>
    <li>python39Packages.expecttest</li>
    <li>python39Packages.flask-caching</li>
    <li>python39Packages.flask-common</li>
    <li>python39Packages.functorch</li>
    <li>python39Packages.geocachingapi</li>
    <li>python39Packages.hypothesis-auto</li>
    <li>python39Packages.inkex</li>
    <li>python39Packages.jedi-language-server</li>
    <li>python39Packages.jupyter</li>
    <li>python39Packages.jupyter-lsp</li>
    <li>python39Packages.jupyter-server-mathjax</li>
    <li>python39Packages.jupyter_server</li>
    <li>python39Packages.jupyterhub</li>
    <li>python39Packages.jupyterhub-ldapauthenticator</li>
    <li>python39Packages.jupyterhub-systemdspawner</li>
    <li>python39Packages.jupyterhub-tmpauthenticator</li>
    <li>python39Packages.jupyterlab_launcher</li>
    <li>python39Packages.kicad</li>
    <li>python39Packages.mesa</li>
    <li>python39Packages.meteofrance-api</li>
    <li>python39Packages.nbclassic</li>
    <li>python39Packages.nbdime</li>
    <li>python39Packages.nix-kernel</li>
    <li>python39Packages.notebook</li>
    <li>python39Packages.notedown</li>
    <li>python39Packages.nplusone</li>
    <li>python39Packages.oauthenticator</li>
    <li>python39Packages.pdfposter</li>
    <li>python39Packages.pecan</li>
    <li>python39Packages.phik</li>
    <li>python39Packages.pipenv-poetry-migrate</li>
    <li>python39Packages.poetry</li>
    <li>python39Packages.poetry2conda</li>
    <li>python39Packages.pyairnow</li>
    <li>python39Packages.pyalgotrade</li>
    <li>python39Packages.pyiqvia</li>
    <li>python39Packages.pylxd</li>
    <li>python39Packages.pyopenuv</li>
    <li>python39Packages.pyoverkiz</li>
    <li>python39Packages.pypdf2</li>
    <li>python39Packages.pypiserver</li>
    <li>python39Packages.pyprosegur</li>
    <li>python39Packages.pypugjs</li>
    <li>python39Packages.pyramid</li>
    <li>python39Packages.pyramid_chameleon</li>
    <li>python39Packages.pyramid_exclog</li>
    <li>python39Packages.pyramid_jinja2</li>
    <li>python39Packages.pyramid_mako</li>
    <li>python39Packages.pyramid_multiauth</li>
    <li>python39Packages.radios</li>
    <li>python39Packages.rencode</li>
    <li>python39Packages.requests-unixsocket</li>
    <li>python39Packages.rokuecp</li>
    <li>python39Packages.schema-salad</li>
    <li>python39Packages.scikit-bio</li>
    <li>python39Packages.simplisafe-python</li>
    <li>python39Packages.spyder</li>
    <li>python39Packages.tesla-wall-connector</li>
    <li>python39Packages.teslajsonpy</li>
    <li>python39Packages.toonapi</li>
    <li>python39Packages.vega</li>
    <li>python39Packages.velbus-aio</li>
    <li>python39Packages.versionfinder</li>
    <li>python39Packages.waitress</li>
    <li>python39Packages.waitress-django</li>
    <li>python39Packages.web</li>
    <li>python39Packages.webargs</li>
    <li>python39Packages.webtest</li>
    <li>python39Packages.webtest-aiohttp</li>
    <li>python39Packages.wled</li>
    <li>python39Packages.ws4py</li>
    <li>python39Packages.wxPython_4_1</li>
    <li>python39Packages.xarray-einstats</li>
    <li>python39Packages.xml2rfc</li>
    <li>python39Packages.yalesmartalarmclient</li>
    <li>qemu_full</li>
    <li>qgis</li>
    <li>qgis-ltr</li>
    <li>radicale (radicale3)</li>
    <li>run-scaled</li>
    <li>sabnzbd</li>
    <li>sambaFull (samba4Full)</li>
    <li>tang</li>
    <li>tebreak</li>
    <li>theharvester</li>
    <li>tribler</li>
    <li>wpa_supplicant_gui</li>
    <li>xpra</li>
    <li>xpraWithNvenc</li>
    <li>zeronet-conservancy</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
Failures are on target branch. Some failures (eg arviz) were caused by SIGILL on one of my older remote builders.

**Comment by dotlambda** [comment]
@ju1m This breaks zerobin.

**Pull request merged**
