### PR TITLE
 electron-source.electron_33: init at 33.0.0, electron: 32 -> 33

### LINKED ISSUE #350029: Update request: electron 32 → 33
- Package name: electron
- Latest released version: 33

- Current version on the unstable channel: 32
- Current version on the stable/release channel: -

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@yayayayaka @teutat3s 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by dotlambda**
fixes https://github.com/NixOS/nixpkgs/issues/350029

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by dotlambda** [comment]
Result of `nixpkgs-review pr 350348` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>yandex-music</li>
  </ul>
</details>
<details>
  <summary>60 packages built:</summary>
  <ul>
    <li>affine</li>
    <li>antimatter-dimensions</li>
    <li>bitwarden-directory-connector</li>
    <li>blockbench</li>
    <li>bruno</li>
    <li>camunda-modeler</li>
    <li>caprine</li>
    <li>chatd</li>
    <li>drawio</li>
    <li>drawio-headless</li>
    <li>electron (electron_33)</li>
    <li>electron-bin</li>
    <li>electron-chromedriver</li>
    <li>equibop</li>
    <li>fcast-receiver</li>
    <li>follow</li>
    <li>freetube</li>
    <li>goofcord</li>
    <li>headset</li>
    <li>httptoolkit</li>
    <li>itch</li>
    <li>jitsi-meet-electron</li>
    <li>koodo-reader</li>
    <li>mattermost-desktop</li>
    <li>mqtt-explorer</li>
    <li>nix-tour</li>
    <li>obsidian</li>
    <li>open-stage-control</li>
    <li>pandoc-drawio-filter</li>
    <li>pandoc-drawio-filter.dist</li>
    <li>podman-desktop</li>
    <li>pritunl-client</li>
    <li>proton-pass</li>
    <li>protonmail-desktop</li>
    <li>python311Packages.mkdocs-drawio-exporter</li>
    <li>python311Packages.mkdocs-drawio-exporter.dist</li>
    <li>python312Packages.mkdocs-drawio-exporter</li>
    <li>python312Packages.mkdocs-drawio-exporter.dist</li>
    <li>r2modman</li>
    <li>redisinsight</li>
    <li>revolt-desktop</li>
    <li>ride</li>
    <li>sharedown</li>
    <li>sieve-editor-gui</li>
    <li>siyuan</li>
    <li>standardnotes</li>
    <li>stretchly</li>
    <li>super-productivity</li>
    <li>terra-station</li>
    <li>tetrio-desktop</li>
    <li>thedesk</li>
    <li>threema-desktop</li>
    <li>uhk-agent</li>
    <li>uhk-udev-rules</li>
    <li>uivonim</li>
    <li>vesktop</li>
    <li>vieb</li>
    <li>webtorrent_desktop</li>
    <li>youtube-music</li>
    <li>ytdownloader</li>
  </ul>
</details>

**Review by teutat3s — COMMENTED** [review]
Thank you for taking care of this. Could you bump the version to 33.0.2?

**Comment by dotlambda** [comment]
> Thank you for taking care of this. Could you bump the version to 33.0.2?

It might be a week before I have time to work on that. Feel free to take on the work or just merge this for now.

**Comment by teutat3s** [comment]
I'll run a build over night and approve tomorrow if everything's fine.

**Comment by teutat3s** [comment]
Result of `nixpkgs-review pr 350348` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>yandex-music</li>
  </ul>
</details>
<details>
  <summary>60 packages built:</summary>
  <ul>
    <li>affine</li>
    <li>antimatter-dimensions</li>
    <li>bitwarden-directory-connector</li>
    <li>blockbench</li>
    <li>bruno</li>
    <li>camunda-modeler</li>
    <li>caprine</li>
    <li>chatd</li>
    <li>drawio</li>
    <li>drawio-headless</li>
    <li>electron (electron_33)</li>
    <li>electron-bin</li>
    <li>electron-chromedriver</li>
    <li>equibop</li>
    <li>fcast-receiver</li>
    <li>follow</li>
    <li>freetube</li>
    <li>goofcord</li>
    <li>headset</li>
    <li>httptoolkit</li>
    <li>itch</li>
    <li>jitsi-meet-electron</li>
    <li>koodo-reader</li>
    <li>mattermost-desktop</li>
    <li>mqtt-explorer</li>
    <li>nix-tour</li>
    <li>obsidian</li>
    <li>open-stage-control</li>
    <li>pandoc-drawio-filter</li>
    <li>pandoc-drawio-filter.dist</li>
    <li>podman-desktop</li>
    <li>pritunl-client</li>
    <li>proton-pass</li>
    <li>protonmail-desktop</li>
    <li>python311Packages.mkdocs-drawio-exporter</li>
    <li>python311Packages.mkdocs-drawio-exporter.dist</li>
    <li>python312Packages.mkdocs-drawio-exporter</li>
    <li>python312Packages.mkdocs-drawio-exporter.dist</li>
    <li>r2modman</li>
    <li>redisinsight</li>
    <li>revolt-desktop</li>
    <li>ride</li>
    <li>sharedown</li>
    <li>sieve-editor-gui</li>
    <li>siyuan</li>
    <li>standardnotes</li>
    <li>stretchly</li>
    <li>super-productivity</li>
    <li>terra-station</li>
    <li>tetrio-desktop</li>
    <li>thedesk</li>
    <li>threema-desktop</li>
    <li>uhk-agent</li>
    <li>uhk-udev-rules</li>
    <li>uivonim</li>
    <li>vesktop</li>
    <li>vieb</li>
    <li>webtorrent_desktop</li>
    <li>youtube-music</li>
    <li>ytdownloader</li>
  </ul>
</details>

**Review by teutat3s — APPROVED** [review]

**Pull request merged**
