### PR TITLE
python311Packages.urwid: 2.4.3 -> 2.5.3

### PR DESCRIPTION
**Pull request by fabaff**
Changelog: https://github.com/urwid/urwid/releases/tag/2.5.3

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 288996` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>34 packages marked as broken and skipped:</summary>
  <ul>
    <li>python312Packages.bpython</li>
    <li>python312Packages.bpython.dist</li>
    <li>python312Packages.configshell</li>
    <li>python312Packages.configshell.dist</li>
    <li>python312Packages.hachoir</li>
    <li>python312Packages.hachoir.dist</li>
    <li>python312Packages.netapp-ontap</li>
    <li>python312Packages.netapp-ontap.dist</li>
    <li>python312Packages.nomadnet</li>
    <li>python312Packages.nomadnet.dist</li>
    <li>python312Packages.pijuice</li>
    <li>python312Packages.pijuice.dist</li>
    <li>python312Packages.pudb</li>
    <li>python312Packages.pudb.dist</li>
    <li>python312Packages.pytest-pudb</li>
    <li>python312Packages.pytest-pudb.dist</li>
    <li>python312Packages.python-fx</li>
    <li>python312Packages.python-fx.dist</li>
    <li>python312Packages.python-openzwave</li>
    <li>python312Packages.python-openzwave.dist</li>
    <li>python312Packages.qiling</li>
    <li>python312Packages.qiling.dist</li>
    <li>python312Packages.recline</li>
    <li>python312Packages.recline.dist</li>
    <li>python312Packages.upass</li>
    <li>python312Packages.upass.dist</li>
    <li>python312Packages.urwid</li>
    <li>python312Packages.urwid-readline</li>
    <li>python312Packages.urwid-readline.dist</li>
    <li>python312Packages.urwid.dist</li>
    <li>python312Packages.urwidgets</li>
    <li>python312Packages.urwidgets.dist</li>
    <li>python312Packages.urwidtrees</li>
    <li>python312Packages.urwidtrees.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>alot</li>
    <li>alot.dist</li>
    <li>stig</li>
    <li>stig.dist</li>
  </ul>
</details>
<details>
  <summary>70 packages built:</summary>
  <ul>
    <li>deltachat-cursed</li>
    <li>deltachat-cursed.dist</li>
    <li>hachoir (python311Packages.hachoir)</li>
    <li>hachoir.dist (python311Packages.hachoir.dist)</li>
    <li>khal</li>
    <li>khal.dist</li>
    <li>mongoaudit</li>
    <li>mongoaudit.dist</li>
    <li>nvmet-cli</li>
    <li>nvmet-cli.dist</li>
    <li>pijuice (python311Packages.pijuice)</li>
    <li>pijuice.dist (python311Packages.pijuice.dist)</li>
    <li>python311Packages.bpython</li>
    <li>python311Packages.bpython.dist</li>
    <li>python311Packages.configshell</li>
    <li>python311Packages.configshell.dist</li>
    <li>python311Packages.netapp-ontap</li>
    <li>python311Packages.netapp-ontap.dist</li>
    <li>python311Packages.nomadnet</li>
    <li>python311Packages.nomadnet.dist</li>
    <li>python311Packages.pudb</li>
    <li>python311Packages.pudb.dist</li>
    <li>python311Packages.pytest-pudb</li>
    <li>python311Packages.pytest-pudb.dist</li>
    <li>python311Packages.python-fx</li>
    <li>python311Packages.python-fx.dist</li>
    <li>python311Packages.python-openzwave</li>
    <li>python311Packages.python-openzwave.dist</li>
    <li>python311Packages.qiling</li>
    <li>python311Packages.qiling.dist</li>
    <li>python311Packages.recline</li>
    <li>python311Packages.recline.dist</li>
    <li>python311Packages.upass</li>
    <li>python311Packages.upass.dist</li>
    <li>python311Packages.urwid</li>
    <li>python311Packages.urwid-readline</li>
    <li>python311Packages.urwid-readline.dist</li>
    <li>python311Packages.urwid.dist</li>
    <li>python311Packages.urwidgets</li>
    <li>python311Packages.urwidgets.dist</li>
    <li>python311Packages.urwidtrees</li>
    <li>python311Packages.urwidtrees.dist</li>
    <li>qemu-python-utils</li>
    <li>qemu-python-utils.dist</li>
    <li>s-tui</li>
    <li>s-tui.dist</li>
    <li>scli</li>
    <li>scriv</li>
    <li>scriv.dist</li>
    <li>targetcli</li>
    <li>targetcli.dist</li>
    <li>todoman</li>
    <li>todoman.dist</li>
    <li>toot</li>
    <li>toot.dist</li>
    <li>topydo</li>
    <li>topydo.dist</li>
    <li>trackma-curses</li>
    <li>trackma-curses.dist</li>
    <li>turses</li>
    <li>turses.dist</li>
    <li>urlscan</li>
    <li>urlscan.dist</li>
    <li>vit</li>
    <li>vit.dist</li>
    <li>wikicurses</li>
    <li>wikicurses.dist</li>
    <li>wikicurses.man</li>
    <li>zulip-term</li>
    <li>zulip-term.dist</li>
  </ul>
</details>

**Comment by emhamm** [comment]
I support this update, but there is a even newer version available, v2.6.0:

https://github.com/urwid/urwid/releases/tag/2.6.0

**Comment by Erethon** [comment]
> I support this update, but there is a even newer version available, v2.6.0:
> 
> https://github.com/urwid/urwid/releases/tag/2.6.0

And an even newer one now https://github.com/urwid/urwid/releases/tag/2.6.1

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 288996` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python312Packages.qiling</li>
    <li>python312Packages.qiling.dist</li>
    <li>stig</li>
    <li>stig.dist</li>
  </ul>
</details>
<details>
  <summary>104 packages built:</summary>
  <ul>
    <li>alot</li>
    <li>alot.dist</li>
    <li>deltachat-cursed</li>
    <li>deltachat-cursed.dist</li>
    <li>hachoir (python311Packages.hachoir)</li>
    <li>hachoir.dist (python311Packages.hachoir.dist)</li>
    <li>khal</li>
    <li>khal.dist</li>
    <li>mongoaudit</li>
    <li>mongoaudit.dist</li>
    <li>nvmet-cli</li>
    <li>nvmet-cli.dist</li>
    <li>pijuice (python311Packages.pijuice)</li>
    <li>pijuice.dist (python311Packages.pijuice.dist)</li>
    <li>python311Packages.bpython</li>
    <li>python311Packages.bpython.dist</li>
    <li>python311Packages.configshell</li>
    <li>python311Packages.configshell.dist</li>
    <li>python311Packages.netapp-ontap</li>
    <li>python311Packages.netapp-ontap.dist</li>
    <li>python311Packages.nomadnet</li>
    <li>python311Packages.nomadnet.dist</li>
    <li>python311Packages.pudb</li>
    <li>python311Packages.pudb.dist</li>
    <li>python311Packages.pytest-pudb</li>
    <li>python311Packages.pytest-pudb.dist</li>
    <li>python311Packages.python-fx</li>
    <li>python311Packages.python-fx.dist</li>
    <li>python311Packages.python-openzwave</li>
    <li>python311Packages.python-openzwave.dist</li>
    <li>python311Packages.qiling</li>
    <li>python311Packages.qiling.dist</li>
    <li>python311Packages.recline</li>
    <li>python311Packages.recline.dist</li>
    <li>python311Packages.upass</li>
    <li>python311Packages.upass.dist</li>
    <li>python311Packages.urwid</li>
    <li>python311Packages.urwid-readline</li>
    <li>python311Packages.urwid-readline.dist</li>
    <li>python311Packages.urwid.dist</li>
    <li>python311Packages.urwidgets</li>
    <li>python311Packages.urwidgets.dist</li>
    <li>python311Packages.urwidtrees</li>
    <li>python311Packages.urwidtrees.dist</li>
    <li>python312Packages.bpython</li>
    <li>python312Packages.bpython.dist</li>
    <li>python312Packages.configshell</li>
    <li>python312Packages.configshell.dist</li>
    <li>python312Packages.hachoir</li>
    <li>python312Packages.hachoir.dist</li>
    <li>python312Packages.netapp-ontap</li>
    <li>python312Packages.netapp-ontap.dist</li>
    <li>python312Packages.nomadnet</li>
    <li>python312Packages.nomadnet.dist</li>
    <li>python312Packages.pijuice</li>
    <li>python312Packages.pijuice.dist</li>
    <li>python312Packages.pudb</li>
    <li>python312Packages.pudb.dist</li>
    <li>python312Packages.pytest-pudb</li>
    <li>python312Packages.pytest-pudb.dist</li>
    <li>python312Packages.python-fx</li>
    <li>python312Packages.python-fx.dist</li>
    <li>python312Packages.python-openzwave</li>
    <li>python312Packages.python-openzwave.dist</li>
    <li>python312Packages.recline</li>
    <li>python312Packages.recline.dist</li>
    <li>python312Packages.upass</li>
    <li>python312Packages.upass.dist</li>
    <li>python312Packages.urwid</li>
    <li>python312Packages.urwid-readline</li>
    <li>python312Packages.urwid-readline.dist</li>
    <li>python312Packages.urwid.dist</li>
    <li>python312Packages.urwidgets</li>
    <li>python312Packages.urwidgets.dist</li>
    <li>python312Packages.urwidtrees</li>
    <li>python312Packages.urwidtrees.dist</li>
    <li>qemu-python-utils</li>
    <li>qemu-python-utils.dist</li>
    <li>s-tui</li>
    <li>s-tui.dist</li>
    <li>scli</li>
    <li>scriv</li>
    <li>scriv.dist</li>
    <li>targetcli</li>
    <li>targetcli.dist</li>
    <li>todoman</li>
    <li>todoman.dist</li>
    <li>toot</li>
    <li>toot.dist</li>
    <li>topydo</li>
    <li>topydo.dist</li>
    <li>trackma-curses</li>
    <li>trackma-curses.dist</li>
    <li>turses</li>
    <li>turses.dist</li>
    <li>urlscan</li>
    <li>urlscan.dist</li>
    <li>vit</li>
    <li>vit.dist</li>
    <li>wikicurses</li>
    <li>wikicurses.dist</li>
    <li>wikicurses.man</li>
    <li>zulip-term</li>
    <li>zulip-term.dist</li>
  </ul>
</details>

**Comment by fabaff** [comment]
`qiling` fails as `capstone` and `unicorn` are still using `distutils`. `stig` is broken for a while already.

**Pull request merged**
