### PR TITLE
openh264: fix hash mismatch

### PR DESCRIPTION
**Pull request by ophestra**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by drupol** [comment]
@ofborg build openh264

**Comment by Scrumplex** [comment]
This was introduced in #337037

It's very odd that its hash has changed :thinking: 

CC @NickCao

**Review by NickCao — APPROVED** [review]
I'm able to reproduce this, hope this is a fluke not something wrong with fetchpatch2.

**Comment by Scrumplex** [comment]
I think this might be a case of #257446, as the hashes in the patch are 8 characters long (instead of the usual 7). @ophestra could you add `?full_index=1` and regenerate the hash to avoid this in the future?

**Comment by ophestra** [comment]
> I think this might be a case of #257446, as the hashes in the patch are 8 characters long (instead of the usual 7). @ophestra could you add `?full_index=1` and regenerate the hash to avoid this in the future?

Done.

**Review by NickCao — CHANGES_REQUESTED** [review]
Oh and this should target staging.

**Comment by NickCao** [comment]
Turns out openh264 is updated on staging, and this patch was dropped, so this PR is no longer needed.

**Comment by ophestra** [comment]
> Turns out openh264 is updated on staging, and this patch was dropped, so this PR is no longer needed.

Yeah, just noticed that as well.

**Pull request closed without merging**
