### PR TITLE
conduwuit: init at 0.4.6

### PR DESCRIPTION
**Pull request by niklaskorz**
## Description of changes

I've been a happy conduwuit user for a while now. The [most recent release](https://github.com/girlbossceo/conduwuit/releases/tag/v0.4.6) brings along features like authenticated media and Element X (sliding sync) compatibility, which make it a well-suited alternative to conduit.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by niklaskorz** [comment]
Currently getting the following on aarch64-darwin if `enableJemalloc` is true:

```
       > error: test failed, to rerun pass `-p conduit --bin conduit`
       >
       > Caused by:
       >   process didn't exit successfully: `/private/tmp/nix-build-conduwuit-0.4.6.drv-0/source/target/aarch64-apple-darwin/release/deps/conduit-c8303cb4f61487aa --test-threads=12` (signal: 11, SIGSEGV: invalid memory reference)
```

**Comment by niklaskorz** [comment]
Tested on my own homeserver with an existing rocksdb, runs fine

**Review by Aleksanaa — APPROVED** [review]

**Comment by nyabinary** [comment]
Shouldn't a module be provided too with options? :P

**Comment by niklaskorz** [comment]
> Shouldn't a module be provided too with options? :P

Right now conduwuit is compatible with the already existing conduit module. The conduwuit docs also currently recommend using the conduit module and just changing `services.conduit.package` to conduwuit.

**Comment by girlbossceo** [comment]
Personally I would love to see us having our own module so we can detach further from Conduit. I only mention using Conduit's module in the docs because no one's made our own dedicated module. I would be more than eager to remove usage of the Conduit module from the docs if we have our own module.

Hope that clarifies my stance on a conduwuit module.

**Comment by niklaskorz** [comment]
> Personally I would love to see us having our own module so we can detach further from Conduit. I only mention using Conduit's module in the docs because no one's made our own dedicated module. I would be more than eager to remove usage of the Conduit module from the docs if we have our own module.
> 
> Hope that clarifies my stance on a conduwuit module.

I see, thanks for chiming in! I'll look into it when I return home again next week, if no one else did until then.

**Comment by nyabinary** [comment]
> > Personally I would love to see us having our own module so we can detach further from Conduit. I only mention using Conduit's module in the docs because no one's made our own dedicated module. I would be more than eager to remove usage of the Conduit module from the docs if we have our own module.
> > Hope that clarifies my stance on a conduwuit module.
> 
> I see, thanks for chiming in! I'll look into it when I return home again next week, if no one else did until then.

Any updates? :3

**Comment by niklaskorz** [comment]
> > > Personally I would love to see us having our own module so we can detach further from Conduit. I only mention using Conduit's module in the docs because no one's made our own dedicated module. I would be more than eager to remove usage of the Conduit module from the docs if we have our own module.
> > > Hope that clarifies my stance on a conduwuit module.
> > 
> > 
> > I see, thanks for chiming in! I'll look into it when I return home again next week, if no one else did until then.
> 
> Any updates? :3

Sorry, not yet! I was occupied fixing zed-editor on darwin but now have some room to look into a conduwuit module.

**Pull request merged**
