### PR TITLE
gen-oath-safe: add dependency on file command

### PR DESCRIPTION
**Pull request by wamserma**
###### Motivation for this change

`file` was not listed as a dependency, causing the program to throw an error.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wamserma** [comment]
@grahamc OfBorg seems stuck on "Fetching PR" - is this caused by GitHub being a bit wobbly yesterday or simply high load on OfBorg?

**Comment by wamserma** [comment]
ping @makefu (maintainer)

**Review by makefu — APPROVED** [review]
LGTM

**Comment by wamserma** [comment]
@FRidh merge?

**Comment by timokau** [comment]
You have a little typo, the status is called `needs_merger` (and you need to set to `needs_reviewer` first anyway).

Diff looks good to me. Would be nice if the tool had a little sanity-check test script, but at least this fixes it for now. ofBorg failure is indeed weird, lets see if we can fix it by turning it off and on again.

@GrahamcOfBorg eval
@GrahamcOfBorg build gen-oath-safe

**Comment by timokau** [comment]
On IRC by cole-h:
> Notice: ofborg evaluators and x86_64-linux builders are down. Buildkite seems to be having trouble, so I can't try to redeploy, either. Sory for the inconvenience.

Though it is weird that this PR already got stuck in May. Anyway, `nix-review` passes and this looks safe enough.

**Review by timokau — APPROVED** [review]

**Comment by timokau** [comment]
Just for testing
/status needs_merger

**Pull request merged**
