### PR TITLE
[Backport release-24.05] nixVersions: backport 2.24.3 as nixVersions.latest

### PR DESCRIPTION
**Pull request by philiptaron**
## Description of changes

With #335342 incoming on master, it's really awkward to have the stable version on master not be available on the latest release branch.

See for instance https://github.com/zhaofengli/attic/pull/159.

This PR cherry-picks commits from #331720, #333183, #333986, #336076, and #332724 so that `nixVersions.latest` is 2.24.3.

I _think_ this is the minimal set to backport.

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>nil</li>
    <li>nixVersions.git</li>
    <li>nixVersions.git.debug</li>
    <li>nixVersions.git.dev</li>
    <li>nixVersions.git.doc</li>
    <li>nixVersions.git.man</li>
    <li>nixVersions.latest</li>
    <li>nixVersions.latest.debug</li>
    <li>nixVersions.latest.dev</li>
    <li>nixVersions.latest.doc</li>
    <li>nixVersions.latest.man</li>
    <li>nixVersions.nix_2_22</li>
    <li>nixVersions.nix_2_22.debug</li>
    <li>nixVersions.nix_2_22.dev</li>
    <li>nixVersions.nix_2_22.doc</li>
    <li>nixVersions.nix_2_22.man</li>
  </ul>
</details>

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by philiptaron** [comment]
Apologies for the overlap, @Mic92!

**Comment by Mic92** [comment]
This one is more up-to-date.

**Comment by Mic92** [comment]
Result of `nixpkgs-review pr 336108` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>nil</li>
    <li>nixVersions.git</li>
    <li>nixVersions.git.debug</li>
    <li>nixVersions.git.dev</li>
    <li>nixVersions.git.doc</li>
    <li>nixVersions.git.man</li>
    <li>nixVersions.latest</li>
    <li>nixVersions.latest.debug</li>
    <li>nixVersions.latest.dev</li>
    <li>nixVersions.latest.doc</li>
    <li>nixVersions.latest.man</li>
    <li>nixVersions.nix_2_22</li>
    <li>nixVersions.nix_2_22.debug</li>
    <li>nixVersions.nix_2_22.dev</li>
    <li>nixVersions.nix_2_22.doc</li>
    <li>nixVersions.nix_2_22.man</li>
  </ul>
</details>

**Comment by Mic92** [comment]
Result of `nixpkgs-review pr 336108` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>nil</li>
    <li>nixVersions.git</li>
    <li>nixVersions.git.debug</li>
    <li>nixVersions.git.dev</li>
    <li>nixVersions.git.doc</li>
    <li>nixVersions.git.man</li>
    <li>nixVersions.latest</li>
    <li>nixVersions.latest.debug</li>
    <li>nixVersions.latest.dev</li>
    <li>nixVersions.latest.doc</li>
    <li>nixVersions.latest.man</li>
    <li>nixVersions.nix_2_22</li>
    <li>nixVersions.nix_2_22.debug</li>
    <li>nixVersions.nix_2_22.dev</li>
    <li>nixVersions.nix_2_22.doc</li>
    <li>nixVersions.nix_2_22.man</li>
  </ul>
</details>

**Comment by Mic92** [comment]
Thanks!

**Pull request merged**
