### PR TITLE
buildbot: move out of python3.pkgs

### PR DESCRIPTION
**Pull request by Mic92**
###### Description of changes

By moving it out we can start apply overrides to python dependendencies
starting with sqlalchemy.

This fixes the build with the current version.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
ofborg test buildbot

**Review by bjornfor — COMMENTED** [review]
Can you add the motivation for this change in the commit message?

**Comment by Mic92** [comment]
Done

**Review by bjornfor — APPROVED** [review]

**Comment by Mic92** [comment]
Setup works in prod and given the current broken state it cannot get worse really. Merging.

**Comment by lopsided98** [comment]
I can't figure out how to make the `updateScript` work again with these changes. Since `buildbot-pkg` is no longer externally visible, I can't tell `nix-update` to update it.

**Comment by Mic92** [comment]
@lopsided98 fixed in https://github.com/NixOS/nixpkgs/pull/229521

**Pull request merged**
