### PR TITLE
stm32cubemx: 6.8.1 -> 6.9.1

### PR DESCRIPTION
**Pull request by angaz**
Release notes: https://www.st.com/resource/en/release_note/rn0094-stm32cubemx-release-691-stmicroelectronics.pdf

In the release notes, it mentions that it's bundled with Java 17, so
this is the same version which is pinned in this package.

## Description of changes

- Add maintainer angaz
- Update stm32cubemx to the latest version, use JDK 17 for the runtime.

I chose JDK 17 because this is what is mentioned in the release notes as the version which is bundled with the application, so I suppose this is the version which was used for their internal testing. I tried JDK 19 and 20. It worked, but there could be unexpected bugs, so I think it's safest to stay with the version suggested by the release notes.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by angaz** [comment]
Hi @AndersonTorres can you please be more specific? I believe I followed the instructions and I ran the two commands suggested to make sure the rules were followed.

**Comment by angaz** [comment]
Are you talking about the `maintainers` key in the `mkDerivation`? I see the order is not sorted. I will fix that now.

**Comment by angaz** [comment]
Decided to sort the `nativeBuildInputs` and dependencies as well.

**Comment by AndersonTorres** [comment]
If you are updating the `maintainers` file, this update must be done first, in a separate **commit** (no need for a pull request).

Google "how to split a git commit into multiple ones".

**Comment by AndersonTorres** [comment]
> Can you please show me where it says this has to be committed separately? 

In the section of manual about `meta.maintainers`:

> . . . There is no restriction to becoming a maintainer, just add yourself to that list in a separate commit titled "maintainers: add alice” in the same pull request . . .

Source: https://nixos.org/manual/nixpkgs/stable/#var-meta-maintainers

> Because I don't see it mentioned

Solved, I believe.

> and I see a lot of recent commits to the maintainers file with other files changed in the same commit. 

Can you precisely point me such commits? Because this is a very known and old policy of Nixpkgs - from the times the documentation was written in Docbook.

**Comment by angaz** [comment]
A lot of commits was a bit of an overstatement.
Here's a few commits I found quickly:
f68619b5f3ff2d77fa152e8e18e0472d91b19f13
231f561d78adc9a0e9223255acc7b240aaf419ee
183e7ca1b7dc0d165923614226fa0b4373203980

> Source: https://nixos.org/manual/nixpkgs/stable/#var-meta-maintainers

I didn't know this existed. I read the markdown files found in the repo linked in the PR template. I would never have looked anywhere else because there is the [maintainers/README.md](https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md) file and I'd expect to find everything I need there, or linked there.

**Comment by AndersonTorres** [comment]
> Here's a few commits I found quickly

Based on this sample, I think they were small slips. Usually people look at the code more

> I didn't know this existed.

No problem. The [Contributing Guidelines](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md) file was rewritten very recently, and some sections were reworked. Maybe the section linking to `meta` attrs was removed.

I will take care of this.

**Comment by angaz** [comment]
Cool. Thanks for the review and guidance.

**Pull request merged**
