### PR TITLE
6.4.22 --> 6.4.25

### PR DESCRIPTION
**Pull request by alexnils**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Scrumplex** [comment]
Could you amend your commit message to follow [Commit conventions](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions)? In this case, the commit should look like this: `praat: 6.4.22 -> 6.4.25`.

Additionally, your PR currently targets the branch `nixos-24.11`. For changes like these you should first target `master` and then someone can add the `backport release-24.11` label to bring this change to 24.11.

You can change the base branch of your PR using a rebase, but make sure to mark this PR as a draft before you push your rebased changes, as it might cause mass-pings to other people. If you need more help, feel free to ask here or in any of our community channels.

**Comment by alexnils** [comment]
Hi! Thanks for helping me out. I've managed to do the things you've asked of me, but I'm stuck on rebasing. When I do `git rebase origin/master` I get this:

```
hint: use --reapply-cherry-picks to include skipped commits
hint: Disable this message with "git config advice.skippedCherryPicks false"
Auto-merging pkgs/applications/version-management/gitlab/data.json
CONFLICT (content): Merge conflict in pkgs/applications/version-management/gitlab/data.json
Auto-merging pkgs/applications/version-management/gitlab/gitlab-workhorse/default.nix
CONFLICT (content): Merge conflict in pkgs/applications/version-management/gitlab/gitlab-workhorse/default.nix
Auto-merging pkgs/by-name/gi/gitaly/package.nix
CONFLICT (content): Merge conflict in pkgs/by-name/gi/gitaly/package.nix
Auto-merging pkgs/by-name/gi/gitlab-container-registry/package.nix
CONFLICT (content): Merge conflict in pkgs/by-name/gi/gitlab-container-registry/package.nix
Auto-merging pkgs/by-name/gi/gitlab-pages/package.nix
CONFLICT (content): Merge conflict in pkgs/by-name/gi/gitlab-pages/package.nix
error: could not apply 9855e57e3688... gitlab: 17.3.6 -> 17.3.7
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
hint: Disable this message with "git config advice.mergeConflict false"
Could not apply 9855e57e3688... gitlab: 17.3.6 -> 17.3.7
```

**Comment by Scrumplex** [comment]
You can try the following:

1. Abort the current rebase operation (`git rebase --abort`). This should take you back to the state before you started your rebasee
2. Rebase only your changes onto master. In your case you only have a single commit that you want to rebase onto master. To do so, you can run `git rebase --onto origin/master HEAD~1` to rebase the latest commit

I think you might run into a conflict on master is already slightly ahead of your current branch.

**Comment by alexnils** [comment]
Thank you, that solved it. But now some tests are failing.

**Comment by Scrumplex** [comment]
It seems like your changes were discarded during rebase, as your `patch-1` branch does not have any new commits over master.

There are no new commits between base branch 'master' and head branch 'patch-1'

**Comment by alexnils** [comment]
Yeah, that's odd, but it explains why I got this message when doing `git rebase --onto origin/master HEAD~1`:

```
dropping 3ecb13ed99c920fb0f01699f2505bf1bb5b53197 praat: 6.4.22 -> 6.4.25 -- patch contents already upstream
Successfully rebased and updated refs/heads/patch-1.
```

Do you have any idea on what I should do?

**Comment by Scrumplex** [comment]
Seems like these changes are already present in master: https://github.com/NixOS/nixpkgs/commit/89b96743cb6f7d50f3accf6b63d3a85c78542390 https://github.com/NixOS/nixpkgs/commit/43a8b6b9322ee8f285b7401d1132c7d51576c4fb

**Comment by alexnils** [comment]
I see. Well, this PR can be closed now. Thank you so much for helping me out! I've learned a lot. Hopefully next PR will go smoother, now that I know how it works.

**Pull request closed without merging**
