### PR TITLE
home-assistant: 2021.5.3 -> 2021.5.4

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

https://github.com/home-assistant/core/releases/tag/2021.5.4

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 123056` at d4a64aa2 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>home-assistant</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 123056` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Comment by happysalada** [comment]
How weird, it says nothing to be built for me.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 123056` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>home-assistant</li>
  </ul>
</details>

**Review by fabaff — APPROVED** [review]

**Comment by happysalada** [comment]
There seems to have been a failure on aarch64
```
 >
       > tests/components/hyperion/test_config_flow.py::test_auth_create_token_approval_declined_task_canceled[pyloop]
       >   /nix/store/l8hhssp3l42h05nxh7f8avd05jxs8lwm-python3.8-aiohttp-3.7.4.post0/lib/python3.8/site-packages/aiohttp/test_utils.py:536: RuntimeWarning: coroutine 'ServiceRegistry.async_call' was never awaited
       >     gc.collect()
       >
       > -- Docs: https://docs.pytest.org/en/stable/warnings.html
       > =========================== short test summary info ============================
       > FAILED tests/components/prometheus/test_init.py::test_view[pyloop] - assert '...
       > ===== 1 failed, 8959 passed, 5 skipped, 7005 warnings in 798.98s (0:13:18) =====
       For full logs, run 'nix log /nix/store/ip9law6xvsbb34vrmm4326a86ddffvpq-homeassistant-2021.5.4.drv'.
```

Can somebody confirm it's a transient failure?

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 123056` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>home-assistant</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
Let's see if we can get some more details on those flaky tests using `--showlocals`.

**Comment by mweinelt** [comment]
@GrahamcOfBorg test home-assistant

**Comment by mweinelt** [comment]
@fabaff @happysalada I need someone to reproduce the issue with [`bdabf32` (#123056)](https://github.com/NixOS/nixpkgs/pull/123056/commits/bdabf32fdd0e9f8102d9c22fa20dde45054a6081)

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 123056` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>home-assistant</li>
  </ul>
</details>

**Comment by mweinelt** [comment]
The mobile app issue reproduced on my RPi4 (aarch64-linux).

```python
____________________ test_webhook_handle_get_config[pyloop] ____________________
[gw1] linux -- Python 3.8.9 /nix/store/7i305r9i4rsb1hmqwkdmphjf430niq3l-python3-3.8.9/bin/python3.8

hass = <homeassistant.core.HomeAssistant object at 0xffffc9ec6fa0>
create_registrations = ({'cloudhook_url': None, 'remote_ui_url': None, 'secret': '00c930ab9c1c724ab514ac14ac40a410ad7bf089b6f23cef4e6e9b27833...emote_ui_url': None, 'secret': None, 'webhook_id': 'd62002d044f9307156434143a8ee16587c591093f500721ef3fe0e3c823b82ba'})
webhook_client = <aiohttp.test_utils.TestClient object at 0xffffc9c874f0>

    async def test_webhook_handle_get_config(hass, create_registrations, webhook_client):
        """Test that we can get config properly."""
        resp = await webhook_client.post(
            "/api/webhook/{}".format(create_registrations[1]["webhook_id"]),
            json={"type": "get_config"},
        )
    
        assert resp.status == 200
    
        json = await resp.json()
        if "components" in json:
            json["components"] = set(json["components"])
        if "allowlist_external_dirs" in json:
            json["allowlist_external_dirs"] = set(json["allowlist_external_dirs"])
    
        hass_config = hass.config.as_dict()
    
        expected_dict = {
            "latitude": hass_config["latitude"],
            "longitude": hass_config["longitude"],
            "elevation": hass_config["elevation"],
            "unit_system": hass_config["unit_system"],
            "location_name": hass_config["location_name"],
            "time_zone": hass_config["time_zone"],
            "components": hass_config["components"],
            "version": hass_config["version"],
            "theme_color": "#03A9F4",  # Default frontend theme color
        }
    
>       assert expected_dict == json
E       AssertionError: assert {'components'...st home', ...} == {'components'...st home', ...}
E         Omitting 8 identical items, use -vv to show
E         Differing items:
E         {'theme_color': '#03A9F4'} != {'theme_color': 'blue'}
E         Use -v to get the full diff
```

**Comment by fabaff** [comment]
Same for me with aarch64-linux (Raspberry Pi 4). I guess that I would see the same output if I could scroll back more...

```bash
[...]
=========================== short test summary info ============================
FAILED tests/components/mobile_app/test_webhook.py::test_webhook_handle_get_config[pyloop]
===== 1 failed, 8959 passed, 5 skipped, 465 warnings in 5707.48s (1:35:07) =====
builder for '/nix/store/g2vmjkhjsrzj0dzp2586vldfhdvgidwy-homeassistant-2021.5.4.drv' failed with exit code 1
error: build of '/nix/store/g2vmjkhjsrzj0dzp2586vldfhdvgidwy-homeassistant-2021.5.4.drv' failed
```

**Comment by mweinelt** [comment]
You could scroll back more, if you didn't use nixpkgs-review to build, but instead just used `nix-build -A home-assistant`. You can even check out pull requests using a simple git alias:

```
[alias]
	cpr="!f() { git fetch origin refs/pull/$1/head && git checkout FETCH_HEAD; }; f"
```

```
❯ git cpr 123056
From https://github.com/NixOS/nixpkgs
 * branch                    refs/pull/123056/head -> FETCH_HEAD
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
warning: The last gc run reported the following. Please correct the root cause
and remove /home/hexa/git/nixos/master/.git/worktrees/release-20.09/gc.log.
Automatic cleanup will not be performed until the file is removed.

warning: There are too many unreachable loose objects; run 'git prune' to remove them.

Updating files: 100% (21113/21113), done.
Note: switching to 'FETCH_HEAD'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at bdabf32fdd0 home-assistant: print full variables on test error
```

**Comment by fabaff** [comment]
I was playing around with the terminals in VScodium. Their implementation is somehow limited in the amount of lines you can scroll back by default (unlike gnome-terminal which is set to 10 k lines in NixOS).

After a reboot I can't reproduce the failure (around `mobile_app/test_webhook.py`) on a Raspberry Pi 4.

**Pull request merged**
