### PR TITLE
Burpsuite: 2024.8.5 -> 2024.10.1

### PR DESCRIPTION
**Pull request by yechielw**
burpsuite: 2024.8.5 -> 2024.10.1

Changelog: https://portswigger.net/burp/releases/professional-community-2024-10-1

### CODE REVIEW

**Comment by yechielw** [comment]
Burpsuite was updated 7 times since august while the nix package is stuck at 2024.8.4

**Review by BonusPlay — APPROVED** [review]
Built and ran community version on `x86_64-linux`, seems to be working.

**Comment by fabaff** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 357898`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>burpsuite</li>
  </ul>
</details>

**Comment by fabaff** [comment]
> Burpsuite was updated 7 times since august while the nix package is stuck at 2024.8.4

#355638 was not merged

**Comment by yechielw** [comment]
I Know, what do i need to do to get a PR merged? this is not a complex pacakge or a breaking change.
It is a simple version bump that should be updated with each release.

**Review by fabaff — COMMENTED** [review]
Could you please update the commit message? 

```text
burpsuite: 2024.8.5 -> 2024.10.1

Changelog: https://portswigger.net/burp/releases/professional-community-2024-10-1
```

Thanks

**Comment by yechielw** [comment]
Done

**Comment by yechielw** [comment]
@fabaff what do i need to do to get this merged?

**Comment by fabaff** [comment]
The commit message [ca4a0c7](https://github.com/NixOS/nixpkgs/pull/357898/commits/ca4a0c7aa0754573f9808c5244b1208be60e870f) needs to be adjusted as mentioned in my previous comment.

**Comment by yechielw** [comment]
@fabaff  I had some truble rebasing the commit but I think I managed.

**Review by fabaff — APPROVED** [review]

**Review by BonusPlay — APPROVED** [review]

**Pull request merged**
