### PR TITLE
dotnet-sdk_7.0: 7.0.100 -> 7.0.101

### PR DESCRIPTION
**Pull request by JamieMagee**
###### Description of changes

Version update via `update.sh`

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by mdarocha — APPROVED** [review]

**Comment by jcdickinson** [comment]
This remediates a vulnerability. It's pretty frightening that this has gone without review for 2 weeks.

**Comment by mdarocha** [comment]
> This remediates a vulnerability. It's pretty frightening that this has gone without review for 2 weeks.
> 
This PR is good to merge, unfortunately .NET contributors with merge access weren't active much for the past couple weeks :/

**Review by IvarWithoutBones — APPROVED** [review]
Apologies for taking a while to reply, I am currently on vacation and unable to merge this. It does LGTM on paper though 👍

**Comment by risicle** [comment]
`BeatSaberModManager` fails to builds for me on x86_64 linux and aarch64-linux, but this sounds too important to let that stop us.

```
Executing dotnetConfigureHook
  Determining projects to restore...
/build/source/BSIPA-Linux/IPA-lib/IPA-lib.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Ref with version (= 6.0.12) [/build/source/BeatSaberModManager.sln]
/build/source/BSIPA-Linux/IPA-lib/IPA-lib.csproj : error NU1102:   - Found 2 version(s) in /nix/store/wlpaq8i4q4wqh4j2lhp0c1md7grpfrxk-BeatSaberModManager-0.0.4-nuget-source/lib [ Nearest version: 7.0.1 ] [/build/source/BeatSaberModManager.sln]
/build/source/BSIPA-Linux/IPA-lib/IPA-lib.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Runtime.linux-x64 with version (= 6.0.12) [/build/source/BeatSaberModManager.sln]
/build/source/BSIPA-Linux/IPA-lib/IPA-lib.csproj : error NU1102:   - Found 2 version(s) in /nix/store/wlpaq8i4q4wqh4j2lhp0c1md7grpfrxk-BeatSaberModManager-0.0.4-nuget-source/lib [ Nearest version: 7.0.1 ] [/build/source/BeatSaberModManager.sln]
/build/source/BSIPA-Linux/IPA-lib/IPA-lib.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.App.Ref with version (= 6.0.12) [/build/source/BeatSaberModManager.sln]
/build/source/BSIPA-Linux/IPA-lib/IPA-lib.csproj : error NU1102:   - Found 2 version(s) in /nix/store/wlpaq8i4q4wqh4j2lhp0c1md7grpfrxk-BeatSaberModManager-0.0.4-nuget-source/lib [ Nearest version: 7.0.1 ] [/build/source/BeatSaberModManager.sln]
/build/source/BSIPA-Linux/IPA-lib/IPA-lib.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.App.Runtime.linux-x64 with version (= 6.0.12) [/build/source/BeatSaberModManager.sln]
/build/source/BSIPA-Linux/IPA-lib/IPA-lib.csproj : error NU1102:   - Found 2 version(s) in /nix/store/wlpaq8i4q4wqh4j2lhp0c1md7grpfrxk-BeatSaberModManager-0.0.4-nuget-source/lib [ Nearest version: 7.0.1 ] [/build/source/BeatSaberModManager.sln]
/build/source/BSIPA-Linux/IPA-lib/IPA-lib.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Host.linux-x64 with version (= 6.0.12) [/build/source/BeatSaberModManager.sln]
/build/source/BSIPA-Linux/IPA-lib/IPA-lib.csproj : error NU1102:   - Found 2 version(s) in /nix/store/wlpaq8i4q4wqh4j2lhp0c1md7grpfrxk-BeatSaberModManager-0.0.4-nuget-source/lib [ Nearest version: 7.0.1 ] [/build/source/BeatSaberModManager.sln]
  Failed to restore /build/source/BSIPA-Linux/IPA-lib/IPA-lib.csproj (in 199 ms).
  Restored /build/source/BeatSaberModManager/BeatSaberModManager.csproj (in 10.54 sec).
```

**Comment by mdarocha** [comment]
> `BeatSaberModManager` fails to builds for me on x86_64 linux and aarch64-linux, but this sounds too important to let that stop us.
> 
> 
> 
> ```
> 
> Executing dotnetConfigureHook
> 
>   Determining projects to restore...
> 
> /build/source/BSIPA-Linux/IPA-lib/IPA-lib.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Ref with version (= 6.0.12) [/build/source/BeatSaberModManager.sln]
> 
> /build/source/BSIPA-Linux/IPA-lib/IPA-lib.csproj : error NU1102:   - Found 2 version(s) in /nix/store/wlpaq8i4q4wqh4j2lhp0c1md7grpfrxk-BeatSaberModManager-0.0.4-nuget-source/lib [ Nearest version: 7.0.1 ] [/build/source/BeatSaberModManager.sln]
> 
> /build/source/BSIPA-Linux/IPA-lib/IPA-lib.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Runtime.linux-x64 with version (= 6.0.12) [/build/source/BeatSaberModManager.sln]
> 
> /build/source/BSIPA-Linux/IPA-lib/IPA-lib.csproj : error NU1102:   - Found 2 version(s) in /nix/store/wlpaq8i4q4wqh4j2lhp0c1md7grpfrxk-BeatSaberModManager-0.0.4-nuget-source/lib [ Nearest version: 7.0.1 ] [/build/source/BeatSaberModManager.sln]
> 
> /build/source/BSIPA-Linux/IPA-lib/IPA-lib.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.App.Ref with version (= 6.0.12) [/build/source/BeatSaberModManager.sln]
> 
> /build/source/BSIPA-Linux/IPA-lib/IPA-lib.csproj : error NU1102:   - Found 2 version(s) in /nix/store/wlpaq8i4q4wqh4j2lhp0c1md7grpfrxk-BeatSaberModManager-0.0.4-nuget-source/lib [ Nearest version: 7.0.1 ] [/build/source/BeatSaberModManager.sln]
> 
> /build/source/BSIPA-Linux/IPA-lib/IPA-lib.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.App.Runtime.linux-x64 with version (= 6.0.12) [/build/source/BeatSaberModManager.sln]
> 
> /build/source/BSIPA-Linux/IPA-lib/IPA-lib.csproj : error NU1102:   - Found 2 version(s) in /nix/store/wlpaq8i4q4wqh4j2lhp0c1md7grpfrxk-BeatSaberModManager-0.0.4-nuget-source/lib [ Nearest version: 7.0.1 ] [/build/source/BeatSaberModManager.sln]
> 
> /build/source/BSIPA-Linux/IPA-lib/IPA-lib.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Host.linux-x64 with version (= 6.0.12) [/build/source/BeatSaberModManager.sln]
> 
> /build/source/BSIPA-Linux/IPA-lib/IPA-lib.csproj : error NU1102:   - Found 2 version(s) in /nix/store/wlpaq8i4q4wqh4j2lhp0c1md7grpfrxk-BeatSaberModManager-0.0.4-nuget-source/lib [ Nearest version: 7.0.1 ] [/build/source/BeatSaberModManager.sln]
> 
>   Failed to restore /build/source/BSIPA-Linux/IPA-lib/IPA-lib.csproj (in 199 ms).
> 
>   Restored /build/source/BeatSaberModManager/BeatSaberModManager.csproj (in 10.54 sec).
> 
> ```

This looks like an error in the package definition - it probably does not define net6, but uses the default value. Most probably unrelated to this change and must have been failing for a while. Make an issue maybe.

**Comment by JamieMagee** [comment]
BeatsaberModManager defines .NET 7.0:

https://github.com/NixOS/nixpkgs/blob/3ad7b8a7e8c2da367d661df6c3742168c53913fa/pkgs/games/BeatSaberModManager/default.nix#L41-L42

And this matches upstream:

https://github.com/affederaffe/BeatSaberModManager/blob/755bf9d3a0ff8c19965a92f216f711a2a52e1c4d/BeatSaberModManager/BeatSaberModManager.csproj#L4

But upstream also vendors a dependencies `BSIPA-Linux` which specifies .NET 6.0

https://github.com/geefr/BSIPA-Linux/blob/81788f58b75f0510a2c534ebe34f11827e167e07/IPA-bin/IPA-bin.csproj#L5

I think it's an issue with the package, not with this change.

**Comment by risicle** [comment]
It was previously building on hydra though: https://hydra.nixos.org/eval/1788869?filter=beatsaber&compare=1788850&full=#tabs-still-succeed

Will have to watch to see if new builds succeed https://hydra.nixos.org/eval/1788908?filter=beatsaber&compare=1788887&full=

**Pull request merged**
