### PR TITLE
linuxPackages.nvidiaPackages.beta: 560.31.02 -> 565.57.01

### PR DESCRIPTION
**Pull request by Kiskae**
- Fixed a bug that could cause suspend/resume to fail when using the NVreg_PreserveVideoMemoryAllocations option: https://github.com/NVIDIA/open-gpu-kernel-modules/issues/472
- Fixed a bug that caused the cursor image to be truncated on Gamescope: https://github.com/ValveSoftware/gamescope/issues/1099
- Re-enabled GLX_EXT_buffer_age on Xwayland. This extension had been previously disabled on Xwayland due to a bug which is now fixed.
- Added support for mmap of exported DMA-BUF objects.
- Reduced some cases of stutter with OpenGL syncing to vblank while using GSP firmware.
- Fixed a regression that could cause some applications to exit due to resource exhaustion on some GPUs while using GSP firmware.
- Added several new per-plane and per-CRTC vendor-specific properties to nvidia-drm. These properties may be used by Wayland compositors to program the GPU's color pipeline for HDR hardware acceleration.
- Introduced a driver optimization to mitigate the performance loss from the 'd3d9.floatEmulation' option in DXVK.
- Fixed a bug that caused FarCry 5 running through DXVK to display a black screen.
- Updated the framelock settings page of the nvidia-settings control panel to use the GTK3 theme text color rather than defaulting to white for the text color, improving legibility with some themes.
- Fixed some performance regressions that were observed with Vkd3d 2.9.
- Fixed a bug that could cause flickering in some applications when using Unified Back Buffer (UBB).
- Fixed a bug which could cause incorrect and/or washed out colors to be displayed with HDR scanout: https://bugs.kde.org/show_bug.cgi?id=482780
- Implemented support for VK_EXT_depth_clamp_control.
- Fixed a bug which could cause applications using GBM to crash when running with nvidia-drm.modeset=0.
- Fixed a bug that could cause kernel crashes upon attempting KMS operations through DRM when nvidia_drm was loaded with modeset=0.
- https://github.com/NVIDIA/open-gpu-kernel-modules/compare/560.35.03...565.57.01
- ~Draft pending auxiliary programs~

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Kiskae** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 350530 --checkout commit`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 6 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11_beta</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11_beta.bin</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11_beta.firmware</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11_beta.lib32</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_5_4_hardened.nvidia_x11_stable_open</li>
  </ul>
</details>
<details>
  <summary>:x: 3 packages failed to build:</summary>
  <ul>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_stable_open</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11_stable_open</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_stable_open</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 99 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_beta</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_beta.bin</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_beta.firmware</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_beta.lib32</li>
    <li>linuxKernel.packages.linux_5_10.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11_beta</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11_beta.bin</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11_beta.firmware</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11_beta.lib32</li>
    <li>linuxKernel.packages.linux_5_10_hardened.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11_beta</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11_beta.bin</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11_beta.firmware</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11_beta.lib32</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_5_15.nvidia_x11_stable_open</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11_beta</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11_beta.bin</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11_beta.firmware</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11_beta.lib32</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_5_15_hardened.nvidia_x11_stable_open</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_beta</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_beta.bin</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_beta.firmware</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_beta.lib32</li>
    <li>linuxKernel.packages.linux_5_4.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11_beta</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11_beta.bin</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11_beta.firmware</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11_beta.lib32</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_6_1.nvidia_x11_stable_open</li>
    <li>linuxKernel.packages.linux_6_10.nvidia_x11_beta</li>
    <li>linuxKernel.packages.linux_6_10.nvidia_x11_beta.bin</li>
    <li>linuxKernel.packages.linux_6_10.nvidia_x11_beta.firmware</li>
    <li>linuxKernel.packages.linux_6_10.nvidia_x11_beta.lib32</li>
    <li>linuxKernel.packages.linux_6_10.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_6_10.nvidia_x11_stable_open</li>
    <li>linuxKernel.packages.linux_6_11.nvidia_x11_beta</li>
    <li>linuxKernel.packages.linux_6_11.nvidia_x11_beta.bin</li>
    <li>linuxKernel.packages.linux_6_11.nvidia_x11_beta.firmware</li>
    <li>linuxKernel.packages.linux_6_11.nvidia_x11_beta.lib32</li>
    <li>linuxKernel.packages.linux_6_11.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_6_11.nvidia_x11_stable_open</li>
    <li>linuxKernel.packages.linux_6_1_hardened.nvidia_x11_beta</li>
    <li>linuxKernel.packages.linux_6_1_hardened.nvidia_x11_beta.bin</li>
    <li>linuxKernel.packages.linux_6_1_hardened.nvidia_x11_beta.firmware</li>
    <li>linuxKernel.packages.linux_6_1_hardened.nvidia_x11_beta.lib32</li>
    <li>linuxKernel.packages.linux_6_1_hardened.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_6_1_hardened.nvidia_x11_stable_open</li>
    <li>linuxKernel.packages.linux_6_6.nvidia_x11_beta</li>
    <li>linuxKernel.packages.linux_6_6.nvidia_x11_beta.bin</li>
    <li>linuxKernel.packages.linux_6_6.nvidia_x11_beta.firmware</li>
    <li>linuxKernel.packages.linux_6_6.nvidia_x11_beta.lib32</li>
    <li>linuxKernel.packages.linux_6_6.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_6_6.nvidia_x11_stable_open</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11_beta (linuxKernel.packages.linux_6_6_hardened.nvidia_x11_beta)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11_beta.bin (linuxKernel.packages.linux_6_6_hardened.nvidia_x11_beta.bin)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11_beta.firmware (linuxKernel.packages.linux_6_6_hardened.nvidia_x11_beta.firmware)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11_beta.lib32 (linuxKernel.packages.linux_6_6_hardened.nvidia_x11_beta.lib32)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11_beta_open (linuxKernel.packages.linux_6_6_hardened.nvidia_x11_beta_open)</li>
    <li>linuxKernel.packages.linux_hardened.nvidia_x11_stable_open (linuxKernel.packages.linux_6_6_hardened.nvidia_x11_stable_open)</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_beta</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_beta.bin</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_beta.firmware</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_beta.lib32</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_latest_libre.nvidia_x11_stable_open</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11_beta</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11_beta.bin</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11_beta.firmware</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11_beta.lib32</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_libre.nvidia_x11_stable_open</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_beta</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_beta.bin</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_beta.firmware</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_beta.lib32</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_lqx.nvidia_x11_stable_open</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11_beta</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11_beta.bin</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11_beta.firmware</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11_beta.lib32</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_xanmod.nvidia_x11_stable_open</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_beta (linuxKernel.packages.linux_xanmod_stable.nvidia_x11_beta)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_beta.bin (linuxKernel.packages.linux_xanmod_stable.nvidia_x11_beta.bin)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_beta.firmware (linuxKernel.packages.linux_xanmod_stable.nvidia_x11_beta.firmware)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_beta.lib32 (linuxKernel.packages.linux_xanmod_stable.nvidia_x11_beta.lib32)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_beta_open (linuxKernel.packages.linux_xanmod_stable.nvidia_x11_beta_open)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.nvidia_x11_stable_open (linuxKernel.packages.linux_xanmod_stable.nvidia_x11_stable_open)</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_beta</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_beta.bin</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_beta.firmware</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_beta.lib32</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_beta_open</li>
    <li>linuxKernel.packages.linux_zen.nvidia_x11_stable_open</li>
  </ul>
</details>

**Comment by diniamo** [comment]
Works well.

Do you happen to know anything about why Firefox crashes on wakeups?

**Comment by Kiskae** [comment]
> Works well.
> 
> Do you happen to know anything about why Firefox crashes on wakeups?

The only immediate thing I would check is `hardware.nvidia.powerManagement.enable`, since that enables `NVreg_PreserveVideoMemoryAllocations`.

But there are so many moving parts involved in suspend/resume when it comes to firefox and the nvidia driver that its impossible to be more specific without an actual error.

**Comment by diniamo** [comment]
I do have that enabled. And it's more so a freeze than a crash, but I'll see if there is an error.

**Comment by diniamo** [comment]
It is in fact just a freeze, so there isn't anything useful in the logs. Here are the logs with WAYLAND_DEBUG=1 though:

[firefox.log](https://github.com/user-attachments/files/17497119/firefox.log)


1. Opened Firefox
2. Suspended
3. Turned my PC back on
4. Killed Firefox

**Comment by Kiskae** [comment]
> It is in fact just a freeze, so there isn't anything useful in the logs. Here are the logs with WAYLAND_DEBUG=1 though:

You might need to look in either your wayland server or kernel log. The mention of a channel error makes me think something on the wayland server side is going wrong.

I've also been running this version for a day and so far haven't run into any new issues, so its probably fine to merge as this is a beta release.

**Comment by ilya-epifanov** [comment]
I'm running it for about a day now. I've only encountered problems when VRAM was under quite a pressure but it's more or less as expected I guess.

**Review by NickCao — APPROVED** [review]

**Pull request merged**
