### PR TITLE
nixos/tests/boot: fix after aa0f27abb06ca66a1dc99493ada65e2bbd6000c9

### PR DESCRIPTION
**Pull request by ajs124**
###### Description of changes
was mistakenly changed in #165035

cc @roberth @erictapen 

###### Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lukegb** [comment]
@ofborg test boot

**Comment by lukegb** [comment]
well, that showed me.

@ofborg test boot.biosCdrom boot.uefiCdrom boot.uefiUsb boot.biosUsb

**Comment by ajs124** [comment]
The test is still broken for unrelated reasons, sadly. @dasJ is working on a fix for those and will hopefully push it to this branch.

**Comment by dasJ** [comment]
Fixed my regressions by pushing onto the PR branch

**Comment by lukegb** [comment]
Hmm, the boot tests are still failing for me at the moment with:

```
Check whether the channel got installed correctly
machine: must succeed: nix-instantiate --dry-run '<nixpkgs>' -A hello
machine # warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
machine # warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
machine # error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)
machine: output:
Test "Check whether the channel got installed correctly" failed with error: "command `nix-instantiate --dry-run '<nixpkgs>' -A hello` failed (exit code 1)"
cleanup
```

**Comment by dasJ** [comment]
Might have broken that as well, currently checking it out

**Comment by lukegb** [comment]
For the record: discussed (on Matrix) running systemd-tmpfiles in stage2-init with dasJ. It's technically doable via an incantation like

```$systemConfig/sw/bin/systemd-tmpfiles --create --boot $systemConfig/etc/tmpfiles.d/*```

and does fix the test, but causes [errors](https://gist.github.com/lukegb/9a8de42ffd74b9f0b3c3c5b060081bb6) to be spammed into the log which don't look _great_.

Introducing the notion of "stage2-init tmpfiles" so we can select only the rules we absolutely need is probably bad too, and maybe only marginally better than having some mkdir here, so... eh.

**Comment by lukegb** [comment]
Works locally for me.

@ofborg test boot.biosCdrom boot.uefiCdrom boot.uefiUsb boot.biosUsb

**Review by lukegb — APPROVED** [review]

**Pull request merged**
