### PR TITLE
gh: 2.39.2 -> 2.40.0

### PR DESCRIPTION
**Pull request by msfjarvis**
Diff: https://github.com/cli/cli/compare/v2.39.2...v2.40.0

Changelog: https://github.com/cli/cli/releases/tag/v2.40.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by williammartin** [comment]
Just want to call out this issue I created over here https://github.com/nix-community/home-manager/issues/4744 as related.

**Comment by msfjarvis** [comment]
> Just want to call out this issue I created over here [nix-community/home-manager#4744](https://github.com/nix-community/home-manager/issues/4744) as related.

Yep, saw it mentioned in your docs, thank you! I'll create a PR for the home-manager module for the migration.

**Comment by williammartin** [comment]
Thank you. If you need more help understanding what's happening exactly what's going on and where the sharp edges are feel free to ask over on that issue. It's not ideal but we expect this kind of thing to be _extremely_ rare. Like, the last time the schema changed was at least more than a year ago as far as I know. 🙏

**Comment by RaitoBezarius** [comment]
Why was this merged given that Home-Manager is not ready @zowoq ? This breaks `gh` for any declarative setup…

**Comment by drupol** [comment]
Yep totally broken here as well.

**Comment by Janik-Haag** [comment]
I think we might want to revert this depending on how long it takes to write a home-manager fix.

**Comment by zowoq** [comment]
I don't think it should be reverted but not interested in debating it.

**Comment by drupol** [comment]
Bravo.

**Comment by Janik-Haag** [comment]
GH apparently does auto migrations on the first run after an update so reverting isn't really an option. :/

**Pull request merged**
