### PR TITLE
pulseview: fix build error

### PR DESCRIPTION
**Pull request by sophrosyne97**
###### Motivation for this change
ZHF: #122042
cc @NixOS/nixos-release-managers

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 123170` at b4052211 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>pulseview</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/applications/science/electronics/pulseview/default.nix:23:15:
```
   |
23 |   patches = [ ./fix-broken-build-due-to-C++-template-behind-C-linkage.patch ];
   |               ^
```
</li>
  </ul>
</details>

**Review by bjornfor — APPROVED** [review]

**Comment by bjornfor** [comment]
Thanks!

**Comment by bjornfor** [comment]
I got a build error locally, the patch has a different hash. Fixed in 3d18eddae244c9a88fc5d8dfe2e90a29d412bb0f.

**Comment by grahamc** [comment]
Note the hash mismatch was reported in ofborg:

https://github.com/NixOS/nixpkgs/runs/2592650314

https://logs.nix.ci/?key=nixos/nixpkgs.123170&attempt_id=fbb98a43-85ac-4d7e-9213-0661c83ec32b

```
hash mismatch in fixed-output derivation '/nix/store/7ld542sh9jmpw5iqsgdcvryhwx4x80ck-fb89dd11f2a4a08b73c498869789e38677181a8d.patch':
  wanted: sha256:153lrvbj0qf8qxx3l01v3ln8g5qjmlapwp8h1k1iir3xx3lyy37k
  got:    sha256:07ifsis9jlc0jjp2d11f7hvw9kaxcbk0a57h2m4xsv1d7vzl9yfh
```

**Comment by grahamc** [comment]
Also note that in the future ofborg will have red X's if the hash doesn't match.

**Pull request merged**
