### PR TITLE
helm: fix #79177 on linux

### LINKED ISSUE #79177: Helm synthesizer does NOT allow saving or loading
**Describe the bug**
Using the Helm Synthesizer, the saving and loading of patches does not work. 

**To Reproduce**
1. `nix-env -iA nixos.helm` (in my case `nix-env -if "<nix-master>" -A helm` to get the version in master)
2. `helm`
3. Attempt to save a patch

**Expected behavior**
Saving patches works, as well as loading patches as per the helm documentation. [page 26](https://tytel.org/static/docs/helm_manual.pdf)

**Screenshots**
- Clicking save has no effect
- Clicking the `+` button under "bank" clears the input
- Clicking the `+` button under "folder" has no effect
2020-02-03-124146_1198x533_scrot

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.98, NixOS, 19.09.1957.57c35c63004 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"musnix, nixos-19.09.1957.57c35c63004"`
 - channels(isaac): `"nixos-18.03-18.03.133402.cb0e20d6db9, nixos-19.03-19.03.173684.c8db7a8a16e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### PR DESCRIPTION
**Pull request by pennae**
###### Motivation for this change

fix #79177 on linux. can't test on a macos machine for lack of having one. also fix the build process a little (`installPhase` would build the vst portion since `buildPhase` didn't).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

cc @magnetophon

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 137146` at ae58f874 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>helm</li>
  </ul>
</details>
<details>
  <summary>3 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/applications/audio/helm/default.nix:48:3:
```
   |
48 |   installPhase = ''
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl3` is a deprecated license, please check if project uses `gpl3Plus` or `gpl3Only` and change `meta.license` accordingly.

Near pkgs/applications/audio/helm/default.nix:72:5:
```
   |
72 |     license = lib.licenses.gpl3;
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

pkg-config is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/applications/audio/helm/default.nix:26:3:
```
   |
26 |   buildInputs = [
   |   ^
```
</li>
  </ul>
</details>

**Comment by yurrriq** [comment]
Can someone test on Darwin?

**Comment by pennae** [comment]
don't think anything would change for darwin, at least considering that the sed script changes the value of a define called `LINUX_FACTORY_PATCH_DIRECTORY` that is only used on linux systems.

**Comment by tomberek** [comment]
Result of `nixpkgs-review pr 137146` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>helm</li>
  </ul>
</details>

**Pull request merged**
