### PR TITLE
python3Packages.transmissionrpc: re-init at 0.11

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
This partially reverts #112237. It re-introduces `transmissionrpc-0.11`.

`transmission-rpc` is not a drop-in replacement for `transmissionrpc`. Home Assistant still depends on `transmissionrpc`.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 115186` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>python37Packages.transmissionrpc</li>
    <li>python38Packages.transmissionrpc</li>
    <li>python39Packages.transmissionrpc</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 115186` at bceef381 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/485d1d47df71a7d76fff330667534bbd">python37Packages.transmissionrpc</a></li></li>
    <li><a href="https://gist.github.com/ea87e63184a543b5a16c2dfc2336d2df">python38Packages.transmissionrpc</a></li></li>
    <li><a href="https://gist.github.com/f80e8ecefa73cfe9da7d8f132534a8cf">python39Packages.transmissionrpc</a></li></li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 115186` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>python37Packages.transmissionrpc</li>
<li>python38Packages.transmissionrpc</li>
<li>python39Packages.transmissionrpc</li>
</ul>
</details>

**Comment by eyJhb** [comment]
@fabaff has it actually been tested and confirmed not to work with Home Assistant ?

**Comment by mweinelt** [comment]
@eyJhb https://github.com/NixOS/nixpkgs/pull/115016#discussion_r587241660

**Pull request merged**
