### PR TITLE
firefox-beta-bin: 80.0b8 -> 81.0b4

### PR DESCRIPTION
**Pull request by cole-h**
###### Motivation for this change

While I try to sort out making `nixpkgs-mozilla` pure enough to be used from a flake (utilizing https://github.com/colemickens/flake-firefox-nightly), I'd like to be mostly up-to-date. (I use Firefox Beta because sometimes Nightly breaks some interactions with Reddit + RES, whereas this breakage doesn't appear to make it into the beta.)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Closes https://github.com/NixOS/nixpkgs/pull/96284.

### CODE REVIEW

**Review by Atemu — APPROVED** [review]
Result of `nixpkgs-review pr 96447` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
<br>- firefox-beta-bin-unwrapped
</details>

WOMM.

**Comment by cole-h** [comment]
Updated to 81.0b3.

**Review by Atemu — APPROVED** [review]
Result of `nixpkgs-review pr 96447` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
<br>- firefox-beta-bin-unwrapped
</details>

Still works.

**Comment by cole-h** [comment]
Updated to 81.0b4.

**Review by vcunat — APPROVED** [review]

**Comment by cole-h** [comment]
Thanks, @vcunat!

**Pull request merged**
