### PR TITLE
KDE / Plasma updates

### PR DESCRIPTION
**Pull request by vandenoever**
###### Motivation for this change

KDE software in NixOS is not at the latest version. This patch `release-19.03` updates to
 - KDE frameworks 5.57
 - Plasma 5.15
 - KDE applications 19.04

I've been running my desktop on a nix channel with this patch for a few weeks. So far I've observed only one bug (https://bugs.kde.org/show_bug.cgi?id=406829). I have not been able to look into the details of the bug because:
 - I cannot get Qt 5.12.3 to compile to see if that fixes it (https://github.com/NixOS/nixpkgs/pull/60119)
 - I do not know how to install Qt package and up with debug symbols enabled.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [~] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by matthewbauer** [comment]
This should be based off of master. Once it's merged and no significant breakages occur, we may be able to backport it to release-19.03.

**Comment by vandenoever** [comment]
Ok, I'll port it to master after the Qt 5.12.3 is working on master (https://github.com/NixOS/nixpkgs/pull/60119)

**Review by FRidh — CHANGES_REQUESTED** [review]
Needs to target master instead.

**Comment by FRidh** [comment]
See also https://github.com/NixOS/nixpkgs/pull/60035

**Comment by nyanloutre** [comment]
Hello, I think this PR should be closed

**Pull request closed without merging**
