### PR TITLE
pythonPackages.libmr: init at 0.1.9

### PR DESCRIPTION
**Pull request by PsyanticY**
###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by lheckemann** [comment]
@GrahamcOfBorg build pythonPackages.libmr python3Packages.libmr

**Comment by worldofpeace** [comment]
Hmm maybe try again?

@GrahamcOfBorg build pythonPackages.libmr python3Packages.libmr

**Comment by Assassinkin** [comment]
@worldofpeace would you please invoke GrahamcOfBorg to re-build for Darwin

**Comment by lheckemann** [comment]
@GrahamcOfBorg build pythonPackages.libmr python3Packages.libmr

**Comment by worldofpeace** [comment]
@Assassinkin I'm not a trusted user with GrahamcOfBorg so It won't build anything on Darwin.

@lheckemann Any comments on this? I think it's fine.

**Review by worldofpeace — APPROVED** [review]

**Pull request merged**
