### PR TITLE
python310Packages.openai: 0.27.9 -> 0.28.0

### PR DESCRIPTION
**Pull request by rounakdatta**
## Description of changes

Update to latest version of the `openai` Python package. The latest version contains the APIs for using gpt-3.5 finetuning.

Diff: https://github.com/openai/openai-python/compare/v0.27.9...v0.28.0

Changelog: https://github.com/openai/openai-python/releases/tag/v0.28.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by natsukium — CHANGES_REQUESTED** [review]
Thanks for your contribution!

Could you please read the [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md) again and change the PR title and the commit message?

**Review by nagy — CHANGES_REQUESTED** [review]
Can you follow the guidelines for the commit message at https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions ?

**Comment by rounakdatta** [comment]
Sorry for the obvious miss, I've now fixed the commit and the PR title.

**Review by nagy — APPROVED** [review]

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 253110` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages marked as broken and skipped:</summary>
  <ul>
    <li>chatgpt-retrieval-plugin</li>
    <li>chatgpt-retrieval-plugin.dist</li>
    <li>openai-full</li>
    <li>openai-full.dist</li>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python310Packages.langchain</li>
    <li>python310Packages.langchain.dist</li>
  </ul>
</details>
<details>
  <summary>20 packages built:</summary>
  <ul>
    <li>chatblade</li>
    <li>chatblade.dist</li>
    <li>checkov</li>
    <li>checkov.dist</li>
    <li>home-assistant-component-tests.openai_conversation</li>
    <li>imaginer</li>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>openai (python310Packages.openai)</li>
    <li>openai.dist (python310Packages.openai.dist)</li>
    <li>python310Packages.guidance</li>
    <li>python310Packages.guidance.dist</li>
    <li>python310Packages.minichain</li>
    <li>python310Packages.minichain.dist</li>
    <li>python311Packages.guidance</li>
    <li>python311Packages.guidance.dist</li>
    <li>python311Packages.openai</li>
    <li>python311Packages.openai.dist</li>
    <li>shell-genie</li>
    <li>shell-genie.dist</li>
  </ul>
</details>

**Review by natsukium — APPROVED** [review]
LGTM, thanks!

**Comment by malob** [comment]
FWIW, I already had a PR open for this #252420. (I'll close it since this was merged.)

**Comment by natsukium** [comment]
Sorry, I looked at most of the PRs for the  python packages, but I missed it.

**Pull request merged**
