### PR TITLE
pantheon.elementary-files: 6.0.4 -> 6.1.0

### PR DESCRIPTION
**Pull request by bobby285271**
###### Motivation for this change

Part of Pantheon 6.0.4 updates (previous one at #147445).

- For upcoming Pantheon 7, check [OS 7 project board](https://github.com/orgs/elementary/projects/94)  for more details.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
<sub>The following content is machine generated and may contain invalid information.</sub>

---

#### pantheon.elementary-files: 6.0.4 -> 6.1.0
- [Release on GitHub](https://github.com/elementary/files/releases/tag/6.1.0)
- [Compare changes on GitHub](https://github.com/elementary/files/compare/6.0.4...6.1.0)

###### Comment



###### To inspect upstream changes
- [ ] [`Re-Adding "Send by Email" (#1822)`](https://github.com/elementary/files/commit/a3779bd303e2d7b39bdf224ae280d0a3e70d580e)
- [ ] [`Add next release appdata for Send Mail portal; bump to v6.1 (#1883)`](https://github.com/elementary/files/commit/7ac08649629dab7790003eaa17854d344f01aee8)
- [ ] [`Focus more results (#1882)`](https://github.com/elementary/files/commit/b38b40ac8b205fa3591f23915ae7818ea20d6f3e)
- [ ] [`Fix empty trash context menu item when already empty (#1742)`](https://github.com/elementary/files/commit/6b9893645ece934cb8519cdb92992bab48bbe381)
- [ ] [`filechooser-portal: Check for flatpak-builder before providing a build target (#1895)`](https://github.com/elementary/files/commit/6d0a77d3f07143997af4c171abc494b7a54219bd)
- [ ] [`Do not lose pathbar entry text if another window is focused (#1847)`](https://github.com/elementary/files/commit/9382bcdfb74d065c16f97160c3497fb2ec2c8ef8)
- [ ] [`Allow blank password attempt when connecting with a user name (#1832)`](https://github.com/elementary/files/commit/830e78ae3584b2cbb84ab55cb80c42826302db46)
- [ ] [`Allow inserting bookmark after Recent (#1848)`](https://github.com/elementary/files/commit/e71ec1b44f00cd4a46af4d76afe844243c6264e3)
- [ ] [`Use the elementary platforma and sdk for portal tester (#1900)`](https://github.com/elementary/files/commit/0a46c63d7dcc2c1e65d7cad2e3d65d018b77d419)
- [ ] [`Inactivate browser button if dragged. (#1902)`](https://github.com/elementary/files/commit/498ad9a867642d640b570f4af84938710c8455d2)
- [ ] [`filechooser-portal: Rewrite Dialog over Gtk.FileChooserWidget (#1899)`](https://github.com/elementary/files/commit/bd9d39a7ac78d0250b0432d76f9b7ec159494f6d)
- [ ] [`FileChooserDialog: use Gtk.CheckButton.with_label (#1912)`](https://github.com/elementary/files/commit/52e2c231570650948c39489d9e226cabd6bb20cb)
- [ ] [`Update next release appdata after filechooser update (#1913)`](https://github.com/elementary/files/commit/dcb48ab540292ffcca7dc90031e648cf3b0e4192)
- [ ] [`Added revealer to remember checkbutton in connect server dialog (#1911)`](https://github.com/elementary/files/commit/d05fb818555ab4f28cb1952029909c476e7f1920)
- [ ] [`Fix multiselect with rubberband (#1907)`](https://github.com/elementary/files/commit/17fd16ac74c91653f4f43942781e2b72b7dfd324)
- [ ] [`Release 6.1.0 (#1897)`](https://github.com/elementary/files/commit/328a5a30206714c607bced6d655e2ea7cda9241d)

**Comment by bobby285271** [comment]
@ofborg test pantheon

**Comment by bobby285271** [comment]
Result of `nixpkgs-review pr 147963` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>pantheon-tweaks</li>
    <li>pantheon.elementary-files</li>
  </ul>
</details>

**Comment by bobby285271** [comment]
@ofborg test pantheon

**Comment by jtojnar** [comment]
The patch was there for the GTK module replacing the file chooser since modules are libraries that was loaded and could not be wrapped. The portal is an executable so wrappers should be enough.

**Review by davidak — COMMENTED** [review]
Quick review looks good. Thank you!

**Pull request merged**
