### PR TITLE
vimPlugins: update

### PR DESCRIPTION
**Pull request by dotlambda**
The previous update broke some hashes: https://github.com/NixOS/nixpkgs/pull/199042

Closes #199541

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by leona-ya — APPROVED** [review]

**Comment by figsoda** [comment]
please run `pkgs/applications/editors/vim/plugins/nvim-treesitter/update.py` as well and commit it as `vimPlugins.nvim-treesitter: update grammars`

note: there were some changes to the update script that was just merged into master so you might want to rebase first

**Comment by figsoda** [comment]
@supersandro2000 I am working on it, but I am not familiar with pluginupdate and I'm not sure how to approach this

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 199466` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>52 packages built:</summary>
  <ul>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.SpaceVim</li>
    <li>vimPlugins.SudoEdit-vim</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.asyncrun-vim</li>
    <li>vimPlugins.bufdelete-nvim</li>
    <li>vimPlugins.catppuccin-nvim</li>
    <li>vimPlugins.chad</li>
    <li>vimPlugins.coc-nvim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.coq-artifacts</li>
    <li>vimPlugins.coq-thirdparty</li>
    <li>vimPlugins.coq_nvim</li>
    <li>vimPlugins.dracula-nvim</li>
    <li>vimPlugins.editorconfig-vim</li>
    <li>vimPlugins.flake8-vim</li>
    <li>vimPlugins.haskell-tools-nvim</li>
    <li>vimPlugins.lazy-lsp-nvim</li>
    <li>vimPlugins.lazygit-nvim</li>
    <li>vimPlugins.leap-ast-nvim</li>
    <li>vimPlugins.lf-vim</li>
    <li>vimPlugins.mini-nvim</li>
    <li>vimPlugins.neodev-nvim</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neotest</li>
    <li>vimPlugins.neotest-haskell</li>
    <li>vimPlugins.null-ls-nvim</li>
    <li>vimPlugins.nvim-base16</li>
    <li>vimPlugins.nvim-dap-ui</li>
    <li>vimPlugins.nvim-lint</li>
    <li>vimPlugins.nvim-navic</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.onedarkpro-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.python-mode</li>
    <li>vimPlugins.pywal-nvim</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.registers-nvim</li>
    <li>vimPlugins.rest-nvim</li>
    <li>vimPlugins.srcery-vim</li>
    <li>vimPlugins.tabby-nvim</li>
    <li>vimPlugins.tabnine-vim</li>
    <li>vimPlugins.telescope-manix</li>
    <li>vimPlugins.toggleterm-nvim</li>
    <li>vimPlugins.vim-airline-themes</li>
    <li>vimPlugins.vim-bazel</li>
    <li>vimPlugins.vim-codefmt</li>
    <li>vimPlugins.vim-floaterm</li>
    <li>vimPlugins.vim-illuminate</li>
    <li>vimPlugins.vim-maktaba</li>
    <li>vimPlugins.vimtex</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
@figsoda I think you you want to add a boolean thats by default false, a check [here](https://github.com/dotlambda/nixpkgs/blob/vimplugins-update/pkgs/applications/editors/vim/plugins/update.py#L92-L93) that sets it to true and then run the nvim-treesitter update script [here](https://github.com/dotlambda/nixpkgs/blob/vimplugins-update/pkgs/applications/editors/vim/plugins/update.py#L125) if the boolean is true. 

---

Currently generating the other bump and appending it when its done.

**Comment by dotlambda** [comment]
> please run `pkgs/applications/editors/vim/plugins/nvim-treesitter/update.py` as well and commit it as `vimPlugins.nvim-treesitter: update grammars`
> 
> note: there were some changes to the update script that was just merged into master so you might want to rebase first

I don't have time for that. Let's revert the other PR instead: https://github.com/NixOS/nixpkgs/pull/199541

**Comment by SuperSandro2000** [comment]
> I don't have time for that.

It takes like 3 minutes and I got time for that.

---

Result of `nixpkgs-review pr 199466` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>vimPlugins.maktaba</li>
  </ul>
</details>
<details>
  <summary>52 packages built:</summary>
  <ul>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.SpaceVim</li>
    <li>vimPlugins.SudoEdit-vim</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vimPlugins.asyncrun-vim</li>
    <li>vimPlugins.bufdelete-nvim</li>
    <li>vimPlugins.catppuccin-nvim</li>
    <li>vimPlugins.chad</li>
    <li>vimPlugins.coc-nvim</li>
    <li>vimPlugins.completion-treesitter</li>
    <li>vimPlugins.coq-artifacts</li>
    <li>vimPlugins.coq-thirdparty</li>
    <li>vimPlugins.coq_nvim</li>
    <li>vimPlugins.dracula-nvim</li>
    <li>vimPlugins.editorconfig-vim</li>
    <li>vimPlugins.flake8-vim</li>
    <li>vimPlugins.haskell-tools-nvim</li>
    <li>vimPlugins.lazy-lsp-nvim</li>
    <li>vimPlugins.lazygit-nvim</li>
    <li>vimPlugins.leap-ast-nvim</li>
    <li>vimPlugins.lf-vim</li>
    <li>vimPlugins.mini-nvim</li>
    <li>vimPlugins.neodev-nvim</li>
    <li>vimPlugins.neogit</li>
    <li>vimPlugins.neotest</li>
    <li>vimPlugins.neotest-haskell</li>
    <li>vimPlugins.null-ls-nvim</li>
    <li>vimPlugins.nvim-base16</li>
    <li>vimPlugins.nvim-dap-ui</li>
    <li>vimPlugins.nvim-lint</li>
    <li>vimPlugins.nvim-navic</li>
    <li>vimPlugins.nvim-treesitter</li>
    <li>vimPlugins.onedarkpro-nvim</li>
    <li>vimPlugins.orgmode</li>
    <li>vimPlugins.python-mode</li>
    <li>vimPlugins.pywal-nvim</li>
    <li>vimPlugins.refactoring-nvim</li>
    <li>vimPlugins.registers-nvim</li>
    <li>vimPlugins.rest-nvim</li>
    <li>vimPlugins.srcery-vim</li>
    <li>vimPlugins.tabby-nvim</li>
    <li>vimPlugins.tabnine-vim</li>
    <li>vimPlugins.telescope-manix</li>
    <li>vimPlugins.toggleterm-nvim</li>
    <li>vimPlugins.vim-airline-themes</li>
    <li>vimPlugins.vim-bazel</li>
    <li>vimPlugins.vim-codefmt</li>
    <li>vimPlugins.vim-floaterm</li>
    <li>vimPlugins.vim-illuminate</li>
    <li>vimPlugins.vim-maktaba</li>
    <li>vimPlugins.vimtex</li>
  </ul>
</details>

---

So, the hashes are now verified by two people. If they are broken by tomorrow again this is definitely a bug in the fetcher and not the fault of a person.

Going to merge this when ofborg is done.

**Review by SuperSandro2000 — APPROVED** [review]

**Pull request merged**
