### PR TITLE
nixos/ldap: remove redundant configuration options

### PR DESCRIPTION
**Pull request by aanderse**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aanderse** [comment]
@GrahamcOfBorg test ldap

**Comment by aanderse** [comment]
I guess the `ldap` test wasn't a good choice because apparently it is broken in `master` right now :disappointed:
I tested this change and it eliminates error messages on `nslcd.service` restart.

**Comment by flokli** [comment]
Uff, it used to work…

Did you verify things still work with a local setup? I'd rather see this being tested somehow, if we can't get the tests to work right now…

**Comment by aanderse** [comment]
I deployed this change to a nixops machine and was able to access the machine via `ssh` with a password. I ran `journalctl -f -u nslcd.service` both while I deployed and while I logged in - there were no errors.

I'll run some more tests, including running a command via `sudo` as well as a local login and then report back :+1:

**Comment by flokli** [comment]
Thanks!

**Comment by aanderse** [comment]
With this change I have confirmed that for an account authenticated via `ldap`:
- remote ssh logins work with a password
- remote ssh logins work with a key
- local logins work with a password
- sudo rules work
- `getent passwd username` yields the expected results
- `getent.ldap passwd username` yields the expected results
- **there are no more errors in `journalctl`**

After reading through source code to better understand where these errors might be coming from, combined with the mentioned testing I believe this PR is ready for a merge.

**Comment by flokli** [comment]
Alright. Thanks :-)

**Pull request merged**
