### PR TITLE
vscode-extensions: move underscore-prefixed extension identifiers to quoted ones

### PR DESCRIPTION
**Pull request by schuelermine**
###### Description of changes

Successor to #191229

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by superherointj** [comment]
Please fix your git signature. It is `Your Name`.

**Comment by schuelermine** [comment]
Done

**Comment by superherointj** [comment]
> home-manager didn’t set my git config correctly when I reinstalled my system.

Home-manager or you (as in your nix configuration)?

**Comment by schuelermine** [comment]
> > home-manager didn’t set my git config correctly when I reinstalled my system.
> 
> Home-manager or you (as in your nix configuration)?

No, I have it in my home-manager configuration. Home manager didn’t warn about an existing .gitconfig from when I messed around with /etc/nixos before I installed home-manager, I think :/
image

**Review by superherointj — APPROVED** [review]

**Comment by superherointj** [comment]
@schuelermine Why do you have to use `gitFull` package there?

**Comment by wegank** [comment]
Looks like this PR breaks eval?  https://github.com/NixOS/nixpkgs/pulls

**Comment by superherointj** [comment]
> Looks like this PR breaks eval? https://github.com/NixOS/nixpkgs/pulls

Will see / fix.

**Comment by superherointj** [comment]
@schuelermine You'll have to file a new PR. Use `throw` instead.

**Comment by schuelermine** [comment]
For backwards compatibility I will just leave an alias in there w/o warning

**Comment by superherointj** [comment]
> For backwards compatibility I will just leave an alias in there w/o warning

Use throw.

**Comment by schuelermine** [comment]
OK

**Pull request merged**
