### PR TITLE
Ngrok update + update script

### PR DESCRIPTION
**Pull request by roberth**
###### Motivation for this change

 - Uses immutable URL instead of mutable to prevent future breakage
 - Update script should make maintenance easier

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bobvanderlinden** [comment]
The update script is very much appreciated!

**Comment by bobvanderlinden** [comment]
You could already bump the version to `.18` from what I gathered in my pr. Though that'll happen automatically anyway. Will give this a go tomorrow (currently on phone).

**Comment by roberth** [comment]
Thanks! Updated.

It's not fully automatic, unless someone runs a generic script that tries every `update` script. Afaik, r-ryantm only checks repology.

**Comment by bobvanderlinden** [comment]
Works for me!:

```
nix build ngrok-2 -f .
result/bin/ngrok http 80
```

The update script also works. It resulted in the same `versions.json` when I first removed `versions.json`.

**Review by bobvanderlinden — APPROVED** [review]

**Comment by bobvanderlinden** [comment]
It might be possible to use the more standardized(?) update script that some other packages are also using. See for instance Firefox https://github.com/nixos/nixpkgs/blob/136126ceaeb8cc21166a0f76c05aaaeb4ff1755a/pkgs/applications/networking/browsers/firefox-bin/default.nix#L194-L200

I can have a look at this later this week.

**Comment by roberth** [comment]
I've split that task off into an issue https://github.com/NixOS/nixpkgs/issues/57898

**Pull request merged**
