### PR TITLE
atlauncher: add discord integration

### PR DESCRIPTION
**Pull request by eljamm**
## Description of changes

Solves [this issue](https://discourse.nixos.org/t/atlauncher-executables-not-found/45450/8?u=eljamm).

Pinging maintainer @GetPsyched 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GetPsyched** [comment]
Is this necessary? It seems as though the JAR already includes the RPC stuff as it's included in the upstream repo's gradle deps and I can see the rich presence on Discord without this as well.

https://github.com/ATLauncher/ATLauncher/blob/d0f20021cc755e464ea527a569ff78f6acf42554/gradle/libs.versions.toml#L10

**Comment by GetPsyched** [comment]
I'm guessing this fixes this specific issue?
https://discourse.nixos.org/t/atlauncher-executables-not-found/45450/8?u=getpsyched

I cannot reproduce this error though.

**Comment by eljamm** [comment]
How odd... it used to happen before this fix, but now I can't reproduce it either, even without the fix.

Perhaps we should wait for a bit and understand what's causing it in the first place, but feel free to close this since you've confirmed that the integration works without this.

**Comment by eljamm** [comment]
I tried to reproduce this again lately, but I couldn't.

It's probably better to close this since nobody seems to have this problem, else we can always re-open this PR or make a new one in the future.

**Pull request closed without merging**
