### PR TITLE
treewide: Dont use obsolete platform aliases

### PR DESCRIPTION
**Pull request by Ericson2314**
###### Motivation for this change

Should be the less controversial part of https://github.com/NixOS/nixpkgs/pull/45717. Doesn't formally deprecate anything, but rewrites usages of platform-related things I'd like to deprecate, analogous for https://github.com/NixOS/nixpkgs/pull/44423 for `configureFlags`.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by FRidh — APPROVED** [review]
It's a pity always having to add something like `hostPlatform` when you don't know/use/care about cross-compilation, but I think it is a small cost for having such feature.

**Comment by Ericson2314** [comment]
@FRidh yeah I'm going to try to make most of these ones be `stdemv.is*` over time.

**Comment by Ericson2314** [comment]
I'd counter that inspecting `system` at all is a pretty low-level operation, so full explicitness is warranted.

**Comment by dezgeg** [comment]
No, sometimes you really need an specific platform to choose from (for instance, when downloading for some prebuilt binaries for different architectures).

**Comment by vcunat** [comment]
Yes, this breaks stuff.  Have you noticed the windows builds on Hydra?  Before:
```
$ nix eval -f pkgs/top-level/release-cross.nix crossMingw32.boehmgc.x86_64-linux.system
"x86_64-linux"
```
After:
```
$ nix eval -f pkgs/top-level/release-cross.nix crossMingw32.boehmgc.x86_64-linux.system
"i686-windows"
```

**Comment by vcunat** [comment]
I also wonder why Borg detected some [aarch64 rebuilds](https://gist.github.com/GrahamcOfBorg/c0fd27c6c0df3c3d9519385548436099).

**Pull request merged**
