### PR TITLE
imagemagick: 6.9.9-21 -> 6.9.9-23

### LINKED ISSUE #31943: ImageMagick-6.9.9-21.tar.xz not available anymore
## Issue description

Upstream has updated and ImageMagick-6.9.9-21.tar.xz isn't available anymore;

example mirror status now:

http://ftp.vim.org/ftp/pub/pub/ImageMagick/

### Steps to reproduce

I was trying to install NixOS from Debian, using the 17.09 channel, but I doubt that's relevant here.

## Technical details

```
building path(s) ‘/nix/store/6fqrgpp4n11h79nvm0dgbf5pmrsl4gfz-ImageMagick-6.9.9-21.tar.xz’

trying https://www.imagemagick.org/download/releases/ImageMagick-6.9.9-21.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found

trying https://mirror.checkdomain.de/imagemagick/releases/ImageMagick-6.9.9-21.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found

trying https://ftp.nluug.nl/ImageMagick/releases/ImageMagick-6.9.9-21.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found

trying ftp://ftp.sunet.se/pub/multimedia/graphics/ImageMagick/releases/ImageMagick-6.9.9-21.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (9) Server denied you to change to the given directory

trying http://ftp.sunet.se/pub/multimedia/graphics/ImageMagick/releases/ImageMagick-6.9.9-21.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found

trying ftp://ftp.imagemagick.org/pub/ImageMagick/releases/ImageMagick-6.9.9-21.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (78) RETR response: 550

trying http://ftp.fifi.org/ImageMagick/releases/ImageMagick-6.9.9-21.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found

trying ftp://ftp.fifi.org/ImageMagick/releases/ImageMagick-6.9.9-21.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (78) RETR response: 550

trying http://imagemagick.mirrorcatalogs.com/releases/ImageMagick-6.9.9-21.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to imagemagick.mirrorcatalogs.com port 80: No route to host

trying ftp://imagemagick.mirrorcatalogs.com/imagemagickreleases/ImageMagick-6.9.9-21.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to imagemagick.mirrorcatalogs.com port 21: No route to host

trying http://distfiles.macports.org/ImageMagick/ImageMagick-6.9.9-21.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found

trying https://bintray.com/homebrew/mirror/download_file?file_path=imagemagick-6.9.9-21.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
error: cannot download ImageMagick-6.9.9-21.tar.xz from any mirror
builder for ‘/nix/store/810wpc327kj3jxgjy00rlg24n8kydvvd-ImageMagick-6.9.9-21.tar.xz.drv’ failed with exit code 1
```

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.0-4-amd64, Debian GNU/Linux, 9 (stretch)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2138.48bf1f43cd"`
 - channels(snajpa): `"nixos-17.03.1947.d77e0969a7"`
 - nixpkgs: `/root/.nix-defexpr/channels/nixos`
```

### PR DESCRIPTION
**Pull request by srhb**
###### Motivation for this change
Fixes #31943

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by srhb** [comment]
@GrahamcOfBorg build imagemagickBig

**Comment by srhb** [comment]
@GrahamcOfBorg build imagemagickBig

**Comment by grahamc** [comment]
@srhb should this be backported?

**Comment by srhb** [comment]
I'm not sure. The upstream source for the older version is gone, but the nar is on cache.nixos.org, so it would only affects stable users that override imagemagick somehow.

**Comment by grahamc** [comment]
Is the version in 17.09 missing, and 6.9.9-x too?

**Comment by srhb** [comment]
The source for 17.09 is missing, since it is also 6.9.9-21

**Comment by grahamc** [comment]
Great, let's backport. Can you open that PR? `git cherry-pick -x <thecommitinthisPR>`

**Pull request merged**
