### PR TITLE
signal-desktop: 1.27.4 -> 1.28.0

### PR DESCRIPTION
**Pull request by equirosa**
###### Motivation for this change
Version 1.28.0 of the signal-desktop app has been released.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by mmahut** [comment]
@GrahamcOfBorg build signal-desktop

**Comment by mmahut** [comment]
Thank you. Welcome to nixpkgs :)

**Comment by mmahut** [comment]
Backported already in dd00d0f2ca6195bd5eee5e1b0b1c2a57fa860e5f.

**Comment by equirosa** [comment]
> Thank you. Welcome to nixpkgs :)
Happy to help! :)

**Comment by primeos** [comment]
Just noticed this, why wasn't I notified as the maintainer (`@GrahamcOfBorg` probably skipped it as there was no actual change)?

This update was already in `master` (7b77666eb1e4ba5731c84551f50a7e55c3d8095f) and this package is actively maintained.
So there was actually no need for this PR (no-op merge). But of course this doesn't really hurt, it's just confusing.

@equirosa thanks for your PR and welcome to nixpkgs. But if possible please focus on unmaintained packages that actually need a maintainer. Unfortunately we have quite a few of those and could need some help :)

**Comment by mmahut** [comment]
@primeos I am a little bit confused, was the commit 7b77666eb1e4ba5731c84551f50a7e55c3d8095f merged without a pull request?

**Comment by equirosa** [comment]
> @equirosa thanks for your PR and welcome to nixpkgs. But if possible please focus on unmaintained packages that actually need a maintainer. Unfortunately we have quite a few of those and could need some help :)

Understood! Will attempt to help where I can! :smile:

**Comment by primeos** [comment]
> @primeos I am a little bit confused, was the commit 7b77666 merged without a pull request?

Yes, I pushed it directly.

> Will attempt to help where I can!

Awesome, thanks :)

**Comment by rht** [comment]
There is a nasty bug for Signal <=1.29.5 https://github.com/signalapp/Signal-Desktop/issues/3879 that is fixed in the latest version 1.29.6. @equirosa do you have the time to bump the version up once again?

**Comment by rht** [comment]
Nvm, I have made #77924.

**Pull request merged**
