### PR TITLE
wpa_supplicant: copy sample config into output

### PR DESCRIPTION
**Pull request by lheckemann**
###### Motivation for this change
The manpage is useless.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by davidak** [comment]
I'm not sure if the information is really accessible there. Maybe it should be part of some kind of documentation?

**Comment by Ma27** [comment]
I just skimmed through the exemplary `wpa_supplicant.conf` and I'm not sure if we really want the entire configuration as default as it defines several `example` networks to show how to configure Wifi networks.

In case there's a use-case when you need some of the defaults I'd vote for patching this file and commenting out everything except the most sensitive values you may want to have as default :)

**Comment by lheckemann** [comment]
>not really sure if we really want the entire configuration as default

Yes, this wouldn't actually make it default. But that is indeed a bit incongruous with the path, so I'll move it to share/doc.

**Comment by lheckemann** [comment]
@davidak
>Maybe it should be part of some kind of documentation?

It's mentioned in the manpage for wpa_supplicant.conf:

>See the example configuration file, probably in /usr/share/doc/wpa_supplicant/, for detailed information about the configuration format and supported fields.

I suppose maybe we should patch this to have the store path.

**Comment by lheckemann** [comment]
When do we get nixos tests for wpa_supplicant with a physics simulation? :D

**Pull request merged**
