### PR TITLE
auto-multiple-choice: use absolute paths instead of "portable" strategy

### PR DESCRIPTION
**Pull request by wentasah**
Currently, auto-multiple-choice from nixpkgs doesn't work on systems with /lib directory. Running auto-multiple-choice there fails with:

    Unknown action gui at /nix/store/n3cyw5ngp0v52rny9gr6z35vslh5d4vx-auto-multiple-choice-1.6.0/bin/.auto-multiple-choice-wrapped line 94.

This happens on non-NixOS systems as well as on NixOS with e.g. nix-ld [1] enabled.

The reason is documented in the Nix expression and the problem is reported upstream at https://project.auto-multiple-choice.net/issues/872. However, the problem can be worked around without requiring upstream changes, as shown in this commit. We stop using the "portable distribution", which tries to detect the base directory at run time, and instead hardcode all paths as absolute at build time.

[1] https://github.com/Mic92/nix-ld

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by wentasah** [comment]
BTW. I've just finished a full exam with AMC from this PR and everything worked as I'm used to. I used NixOS for that.

I also did more testing on non-NixOS systems. Without this change, AMC does not run at all. With this PR, it runs (shows GUI). Unfortunately, some operations such as generation of PDFs with questions require AMC to be in $PATH. So running AMC via e.g. `nix run github:wentasah/nixpkgs/amc-fix-lib#auto-multiple-choice` is not sufficient. One needs to install AMC with `nix profile install` or similar. And then, there is still risk of mixing AMC from Nix with native distro's AMC. Another "problem" is that AMC from Nix still uses many things from outside of Nix (LaTeX, fonts) so determinism is not fully guaranteed.

Anyway, even thought the PR is not perfect, it makes AMC work definitely better than it was before.

**Review by thblt — APPROVED** [review]
lgtm

**Review by thblt — APPROVED** [review]
lgtm

**Comment by thblt** [comment]
sorry for the delay

**Comment by wentasah** [comment]
Result of `nixpkgs-review pr 281217` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>auto-multiple-choice</li>
  </ul>
</details>

**Comment by wentasah** [comment]
I've just tested that the PR still works and can be merged.

**Pull request merged**
