### PR TITLE
atomicwrites: 0.1.0 -> 0.1.9

### PR DESCRIPTION
**Pull request by DamienCassou**
###### Things done:
- [x] Tested using sandboxing
- [x] Built on platform(s): NixOS
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
It seems that `vdirsyncer`, `khard` and `khal` want `atomicwrites` - did you test them? If yes, I can ACK this.

**Comment by DamienCassou** [comment]
@matthiasbeyer I tried khard and vdirsyncer manually (running the binaries). Nox-review managed to build everything. So I think it's safe.

**Comment by matthiasbeyer** [comment]
@DamienCassou Good job.

**Pull request merged**
