### PR TITLE
luaPackages.mimetypes: init at 1.0.0-3

### LINKED ISSUE #297143: Package request: lua*Packages.mimetypes
**Project description**

This is a simple library for guessing a file's MIME type. It includes a (hopefully) comprehensive database of MIME types, but it allows you to create your own should you have specific requirements. It can guess types both by extension and by the complete filename.

used by https://github.com/rest-nvim/rest.nvim

**Metadata**

* homepage URL:https://luarocks.org/modules/lunarmodules/mimetypes
* source URL:https://github.com/lunarmodules/lua-mimetypes
* license: mit
* platforms: linux, darwin, windows

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by teto**
## Description of changes

Fix https://github.com/NixOS/nixpkgs/issues/297143

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by teto** [comment]
Result of `nixpkgs-review pr 297258` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>lua51Packages.mimetypes</li>
    <li>lua52Packages.mimetypes</li>
    <li>lua53Packages.mimetypes</li>
    <li>lua54Packages.mimetypes</li>
    <li>luajitPackages.mimetypes</li>
  </ul>
</details>

**Comment by lolbinarycat** [comment]
`generated-packages.nix` comment says it is generated from `pkgs/development/lua-modules/overrides.nix`, but i don't see any changes to that file.

is something wrong or is the comment just wrong?

**Comment by teto** [comment]
where do you see that ? I read 
```
/* pkgs/development/lua-modules/generated-packages.nix is an auto-generated file -- DO NOT EDIT!
Regenerate it with: nix run nixpkgs#update-luarocks-packages
You can customize the generated packages in pkgs/development/lua-modules/overrides.nix
*/
```

**Comment by lolbinarycat** [comment]
yes, that is the comment i was referring to, although it seems i just misread it.

**Comment by wenjinnn** [comment]
Hi there. I did the building step on my computer follow your comment at #297143, It success with no error output.

**Pull request merged**
