### PR TITLE
New linuxPackages_custom helper function

### PR DESCRIPTION
**Pull request by ts468**
Add linuxPackages_custom helper function for installing a Linux kernel with a custom config file.

### CODE REVIEW

**Comment by ts468** [comment]
PR #5994 should be merged first.

**Comment by ts468** [comment]
As an example, I use linuxPackages_custom in my /etc/nixos/configuration.nix as in the example below. Is there another configuration option that achieves the same and is already included in NixOS?

  
boot.kernelPackages = pkgs.linuxPackages_custom {
    version = "3.18.1-xen";
    src = pkgs.fetchurl {
      url = "mirror://kernel/linux/kernel/v3.x/linux-3.18.1.tar.xz";
      sha256 = "13m0s2m0zg304w86yvcmxgbjl41c4kc420044avi8rnr1xwcscsq";
    };
    configfile = /etc/nixos/customKernel.config;
  };

**Comment by jagajaga** [comment]
:+1:

**Comment by ts468** [comment]
@jagajaga, glad you like it ;), could you maybe merge it?

**Comment by jagajaga** [comment]
Can you show `/etc/nixos/customKernel.config`?

**Comment by ts468** [comment]
It is just a standard kernel config file; what is it that you're looking for?

**Comment by jagajaga** [comment]
Hm. The problem is that I think that we have to document it somewhere.
May be for now you can just write some information in comments above your new code?

**Comment by jagajaga** [comment]
Some updates? :)

**Comment by ts468** [comment]
I think it would be best to put some note into https://nixos.org/wiki/How_to_tweak_Linux_kernel_config_options

**Comment by jagajaga** [comment]
Can you do it? Then I'll merge.

**Comment by ts468** [comment]
@jagajaga: So, I've updated the wiki. Could you please merge the PR?

**Comment by jagajaga** [comment]
Nice! Thank you.

**Pull request merged**
