### PR TITLE
libchewing: 0.5.1-unstable-2020-06-27 -> 0.6.0

### PR DESCRIPTION
**Pull request by ShamrockLee**
## Description of changes

Update libchewing from an untagged revision `0.5.1-unstable-2020-06-27` to the nearest official release `0.6.0`.
- If merged and backported, users should enjoy an officially released version of `libchewing,` making it easier to get upstream support.
- 0.7.0 or 0.8.0 changed the user dictionary format and rewrote the whole codebase with Rust, making the update and backport more challenging.

The changes in this PR aim to be backportable and to make future backporting easier. I hope to backport it if it works without additional issues.

Cc: @ericsagnes

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`) (Tested fcitx5-chewing by invoking Fcitx5 input method framework through Home Manager module `i18n.inputMethod`.)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ShamrockLee** [comment]
Result of `nixpkgs-review pr 314538` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>chewing-editor</li>
    <li>fcitx5-chewing</li>
    <li>hime</li>
    <li>libchewing</li>
    <li>libsForQt5.plasma-mobile (plasma5Packages.plasma-mobile)</li>
    <li>lomiri.lomiri</li>
    <li>lomiri.lomiri-session</li>
    <li>lomiri.lomiri-system-settings</li>
    <li>lomiri.lomiri-system-settings-security-privacy</li>
    <li>lomiri.lomiri-system-settings-unwrapped</li>
    <li>lomiri.lomiri-system-settings-unwrapped.dev</li>
    <li>maliit-keyboard</li>
  </ul>
</details>

**Comment by ShamrockLee** [comment]
I was just tested `fcitx5-chewing` locally. It works as well as before. `chewing-editor` (the user phrase editor of the Chewing input method) also works.

**Comment by ShamrockLee** [comment]
@ericsagnes, thank you for your patience while waiting for this PR to get ready for review.

How should we adjust/rewrite the `libchewing` for the upstream rewrite in Rust in versions 0.7 and 0.8?

**Comment by ShamrockLee** [comment]
Cc: @ryantm

**Review by tjni — APPROVED** [review]

**Pull request merged**
