### PR TITLE
rustc: 1.63.0 -> 1.64.0

### PR DESCRIPTION
**Pull request by zowoq**
https://github.com/rust-lang/rust/releases/tag/1.64.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Built:
- [x] `fd.x86_64-darwin`
- [x] `fd.x86_64-linux`
- [ ] `firefox.x86_64-linux`
- [x] `thunderbird.x86_64-linux`

### CODE REVIEW

**Comment by alyssais** [comment]
Firefox builds for me (x86_64-linux)

**Comment by zowoq** [comment]
Thanks, my original firefox build failed and I forgot to restart it.

**Comment by trofi** [comment]
Bisect says 8f7b25344084335aaa55bda890559ab3a139c4a8 `rustc: 1.63.0 -> 1.64.0` broke `alacritty` build in tests phase in `satging`:

```
$ nix build --no-link -f. -L alacritty
...
alacritty> failures:
alacritty> ---- input::tests::multi_click_separate_buttons stdout ----
alacritty> thread 'input::tests::multi_click_separate_buttons' panicked at 'cannot transmute_copy if U is larger than T', /build/rustc-1.64.0-src/library/core/src/mem/mod.rs:1057:5
alacritty> ---- input::tests::double_click stdout ----
alacritty> thread 'input::tests::double_click' panicked at 'cannot transmute_copy if U is larger than T', /build/rustc-1.64.0-src/library/core/src/mem/mod.rs:1057:5
alacritty> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
alacritty> ---- input::tests::single_middle_click stdout ----
alacritty> thread 'input::tests::single_middle_click' panicked at 'cannot transmute_copy if U is larger than T', /build/rustc-1.64.0-src/library/core/src/mem/mod.rs:1057:5
alacritty> ---- input::tests::triple_click stdout ----
alacritty> thread 'input::tests::triple_click' panicked at 'cannot transmute_copy if U is larger than T', /build/rustc-1.64.0-src/library/core/src/mem/mod.rs:1057:5
alacritty> ---- input::tests::single_click stdout ----
alacritty> thread 'input::tests::single_click' panicked at 'cannot transmute_copy if U is larger than T', /build/rustc-1.64.0-src/library/core/src/mem/mod.rs:1057:5
alacritty> ---- input::tests::single_right_click stdout ----
alacritty> thread 'input::tests::single_right_click' panicked at 'cannot transmute_copy if U is larger than T', /build/rustc-1.64.0-src/library/core/src/mem/mod.rs:1057:5
alacritty> failures:
alacritty>     input::tests::double_click
alacritty>     input::tests::multi_click_separate_buttons
alacritty>     input::tests::single_click
alacritty>     input::tests::single_middle_click
alacritty>     input::tests::single_right_click
alacritty>     input::tests::triple_click
alacritty> test result: FAILED. 56 passed; 6 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

**Comment by trofi** [comment]
Looks like fresh `alacritty` release candidates happen to work on `rustc-1.64.0`. Proposed an update as https://github.com/NixOS/nixpkgs/pull/192780

**Comment by vcunat** [comment]
Just FYI: https://github.com/NixOS/nixpkgs/pull/193494#issuecomment-1265703414

**Pull request merged**
