### PR TITLE
noisetorch: remove

### PR DESCRIPTION
**Pull request by DieracDelta**
###### Description of changes

Noisetorch is compromised and deprecated. Remove it from nixpkgs. https://github.com/lawl/NoiseTorch/releases/tag/0.11.6 https://github.com/lawl/NoiseTorch/issues/256

###### Things done

Deleted nixos noisetorch module and noisetorch package.

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by legendofmiracles** [comment]
The release doesn't state that noisetorch is deprecated. And the keys only affect the official releases.

I think it's better to leave it. If we really want to be sure, we could set `meta.insure` to true, that way we leave the decision to the user.

**Comment by DieracDelta** [comment]
I asked specifically about the source: https://github.com/lawl/NoiseTorch/issues/256#issuecomment-1130760229, and [the author says he doesn't know when the compromise happened or which commits might be affected](https://github.com/lawl/NoiseTorch/issues/254#issuecomment-1130904396). I think it is better to drop the package than risk introducing some sort of vulnerability. And perhaps reintroduce when volunteers have finished auditing...

**Comment by MagicRB** [comment]
Id suggest disabling it with a broken flag and a trace, not removing. The situation is being handled

**Comment by legendofmiracles** [comment]
As a maintainer of noisetorch, I've gone ahead and merged my own proposal: https://github.com/NixOS/nixpkgs/pull/173611
We can still go ahead and merge this if that's what the consensus is.

**Comment by Mindavi** [comment]
Marking insecure should be enough, in my opinion. Also, chances are very unlikely source was actually compromised, AFAICT?

**Pull request closed without merging**
