### PR TITLE
Kicad: 5.1.8 -> 5.1.9

### PR DESCRIPTION
**Pull request by evils**
###### Motivation for this change
new stable version tagged

###### Things done
fixed update.sh to handle multiple responses from `git ls-remote --heads --tags` (taking the last rather than the first response)
run update.sh to update stable and unstable

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
 - `8 packages updated:
kicad-with-packages3d (5.1.8 → 5.1.9) kicad (5.1.8 → 5.1.9) python39Packages.kicad (5.1.8 → 5.1.9) python38Packages.kicad (5.1.8 → 5.1.9) python37Packages.kicad (5.1.8 → 5.1.9) kicad-small (5.1.8 → 5.1.9) kicad-unstable (2020-12-01 → 2020-12-23) kicad-unstable-small (2020-12-01 → 2020-12-23)`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
  - stable: `6347308864 -> 6764336248`
  - unstable: `6925383008 -> 6926087408`
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 107467` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages marked as broken and skipped:</summary>
  <ul>
    <li>kicad-small</li>
    <li>kicad-unstable-small</li>
    <li>python37Packages.kicad</li>
    <li>python38Packages.kicad</li>
    <li>python39Packages.kicad</li>
  </ul>
</details>

**Comment by evils** [comment]
> on x86_64-darwin

i believe until #98538 is merged, our kicad can't work on darwin

there's still a comment in default.nix calling out libngspice as linux only, but that has been fixed
i don't have a way of confirming that issue is actually resolved though

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 107467` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>kicad-small</li>
    <li>kicad-unstable-small</li>
    <li>python37Packages.kicad</li>
    <li>python38Packages.kicad</li>
    <li>python39Packages.kicad</li>
  </ul>
</details>

**Comment by evils** [comment]
ah yes, the traditional PR merge as i find an issue and start working on it :D

3D models in kicad-unstable don't work (this issue is not introduced in this PR)
there's a new variable, `KICAD6_3DMODEL_DIR` that's supposed to contain the path to the 3D models
currently we're not setting that, the old `KISYS3DMOD` variable is still used, but does not take its value from the env var in the wrapper anymore...

current workaround if you need 3D models in kicad-unstable is to copy the 3D models path in the wrapper (`cat $(which kicad) | grep "KISYS3DMOD"`) into kicad under preferences -> configure paths -> `KISYS3DMOD`

**Pull request merged**
