### PR TITLE
staging-next 2024-07-20

### PR DESCRIPTION
**Pull request by vcunat**
##### Helpful links

- workflow docs: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#staging
- important jobs:
  https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
  https://hydra.nixos.org/job/nixos/staging-next-small/tested
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next
  https://hydra.nixos.org/jobset/nixos/staging-next-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/322145
##### Mass breakages
_nothing notable so far_

### CODE REVIEW

**Comment by NickCao** [comment]
fakeroot: https://github.com/NixOS/nixpkgs/pull/328928

**Comment by Mrmaxmeier** [comment]
raptor2: https://github.com/NixOS/nixpkgs/pull/328243

**Comment by Aleksanaa** [comment]
Sorry for the noise, you can just skip nixf-tidy and nixfmt check by adding `[skip treewide]` to PR title

**Comment by vcunat** [comment]
Thanks for your fixes ❤️   The rest is for master.

**Comment by vcunat** [comment]
Noticed quite late, but `nixpkgs-unstable` is blocked by darwin bootstrap tools:
https://hydra.nixos.org/build/267920930/nixlog/1/tail
Hopefully @reckenrode knows easily?

**Comment by reckenrode** [comment]
> Noticed quite late, but `nixpkgs-unstable` is blocked by darwin bootstrap tools: https://hydra.nixos.org/build/267920930/nixlog/1/tail Hopefully @reckenrode knows easily?

Fixed by https://github.com/NixOS/nixpkgs/pull/331145.

**Pull request merged**
