### PR TITLE
all-packages.nix: reorder git-and-tools expressions

### PR DESCRIPTION
**Pull request by AndersonTorres**
This commit serves as first step for refactor them in the next set of commits.

###### Description of changes

A scary reordering of lines.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AndersonTorres** [comment]
For the log: next I will group all those expressions inside a typical `recurseIntoAttrs` thing.

**Comment by zowoq** [comment]
> For the log: next I will group all those expressions inside a typical `recurseIntoAttrs` thing.

So you're basically reverting https://github.com/NixOS/nixpkgs/pull/109396?

**Comment by AndersonTorres** [comment]
> So you're basically reverting https://github.com/NixOS/nixpkgs/pull/109396?

Partially, I would say.

They will all stay in the top-level, but transparently, using `inherit (recurseIntoAttrs <path to git and tools>) <the git tools>`.
Hopefully no one will notice...

**Comment by zowoq** [comment]
> They will all stay in the top-level - but transparently, using inherit (recurseIntoAttrs <path to git and tools>) <the git tools>.

Frankly I think this is a waste of time and effort, strong no from me.

**Comment by AndersonTorres** [comment]
Maybe not. This already happens within Nixpkgs, especially

- coherent sets of packages like desktop managers
- plugins to shells and other utilities

I will give this a shot.

**Comment by zowoq** [comment]
> * coherent sets of packages like desktop managers
> 
> * plugins to shells and other utilities

This is very different from these.

cc @alyssais  @cole-h @Mic92 from https://github.com/NixOS/nixpkgs/pull/109396

**Comment by AndersonTorres** [comment]
For now this is OK. I will leave the "next shot" to another future PR.

**Comment by zowoq** [comment]
> I will leave the "next shot" to another future PR.

If this means `recurseIntoAttrs` then consider this a very strong pre-emptive objection to that.

**Comment by vcunat** [comment]
Uh, this didn't just reorder the lines, probably just due to "conflicts" accumulated over time.  Example:
```diff
-  subsurface = libsForQt5.callPackage ../applications/misc/subsurface { };
+  subsurface = libsForQt514.callPackage ../applications/misc/subsurface { };
```

**Comment by zowoq** [comment]
https://github.com/NixOS/nixpkgs/pull/204250

**Pull request merged**
