### PR TITLE
Fix the syntax error on tt-rss config file

### PR DESCRIPTION
**Pull request by MasseR**
I have used these changes in my server for a few days now, although I have only tested the passwordFile option.

###### Motivation for this change

A fix for https://github.com/NixOS/nixpkgs/issues/148694 fixing the syntax error in the PHP config file.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by symphorien — CHANGES_REQUESTED** [review]
When using unix authentication this generates invalid php:
```
putenv('TTRSS_DB_PASS=' . );                                                                                                                                                            
```

**Comment by MasseR** [comment]
> When using unix authentication this generates invalid php:
> 
> ```
> putenv('TTRSS_DB_PASS=' . );                                                                                                                                                            
> ```

How are you configuring tt-rss to get that output? Omitting the password entirely?

**Comment by symphorien** [comment]
Indeed no password. A password is not required as postgresql allows acess to the tt-rss database to the unix user of the same name.

**Comment by MasseR** [comment]
Should the config.php omit the entire password setting or should it be set empty?

In effect, would this do the trick?

``` php
putenv('TTRSS_DB_PASS=' . ''); 
```

**Comment by symphorien** [comment]
I think so as my current config file contains:
```
 putenv('TTRSS_DB_PASS=');
```

**Comment by MasseR** [comment]
Added handling for unix password:

- No password at all: `putenv('TTRSS_DB_PASS=' );`
- Password explicitly set in nix: `putenv('TTRSS_DB_PASS=' . 'foo');`
- Using a password file: `putenv('TTRSS_DB_PASS=' . file_get_contents('/etc/nixos/system/services/ttrss/db'));`

**Review by symphorien — APPROVED** [review]

**Pull request merged**
