### PR TITLE
nix-daemon: Sanity check maxJobs vs nrBuildUsers

### LINKED ISSUE #6341: error: all build users are currently in use; consider creating additional users and adding them to the ‘nixbld’ group
This error message is very bad. 
```error: all build users are currently in use; consider creating additional users and adding them to the ‘nixbld’ group```

It should list which configured build users exist (with a count too) it then should display what those are doing, and finally it should output the code required to add a nixbld group. 

In this particular case, I think it's a bug... because no builds are in progress in the first place. But really such error messages ... an "error path" of a program should still generate proof that it cannot do something and as such it cannot just create existential output. Computation is constructive, so ... output that. 

So, I now have a broken version of Nix on my laptop (with some wrong instructions on a wiki), and a broken version of NixOS on my server (no idea on what can possibly have caused that). Good going guys! 

This even happens after a reboot and running `nixos-rebuild switch` as the first command. WAT. 

Ok, so we here even have a counter-example that whatever `nixos-rebuild switch` is saying is complete bullshit.  
```
for u in {1..10}; do ps -U  nixbld$u; done
  PID TTY          TIME CMD
  PID TTY          TIME CMD
  PID TTY          TIME CMD
  PID TTY          TIME CMD
  PID TTY          TIME CMD
  PID TTY          TIME CMD
  PID TTY          TIME CMD
  PID TTY          TIME CMD
  PID TTY          TIME CMD
  PID TTY          TIME CMD
```

So, can you please fix what you release?

### PR DESCRIPTION
**Pull request by wmertens**
Fixes #6341

### CODE REVIEW

**Comment by wwat** [comment]
This is better than what is currently in NixOS, but I think the semantics I suggested would eliminate the failure condition. This code still contains a failure condition. I think it would be better to make a warning out of it and use code like 

nrJobs = min number_of_configured_jobs number_of_builders and additionally show a warning when number_of_configured_jobs is greater than number_of_builders.

**Comment by wmertens** [comment]
The thing is, nixpkgs doesn't have many warnings at the moment, and this is a pretty limited use case. If you specify more build jobs than users, it will abort and tell you to adjust. Immediate feedback on a just-changed value and therefore no warning needed.

**Comment by iElectric** [comment]
Would be nice if such changes hang around as PRs at least a few days - just to give everyone a chance to review :)

**Comment by edolstra** [comment]
Rather than checking, why don't we just create the necessary number of users?

**Comment by edolstra** [comment]
I've done just that in 5d7000d.

**Comment by wmertens** [comment]
@edolstra that works too :smile:

**Pull request merged**
