### PR TITLE
tortoisehg: added smoke test for thg

### PR DESCRIPTION
**Pull request by gbtb**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/pull/155636#issuecomment-1017015028
cc @pacien 

###### Things done

Added smoke test for thg, based on an output of thg -h command. Main purpose of this test is to detect breakage of thg in case of out-of-sync mercurial update. In that case any thg subcommand just opens up an gui dialog with a description of version mismatch.
Also in order for thg to work in a checkPhase environment I have to add QT_QPA_PLATFORM=offscreen, otherwise the infamous xcb plugin error does show up. 
Also I've run nixpkgs-fmt on file.

Right now the test should fail because of version mismatch, so https://github.com/NixOS/nixpkgs/pull/155636 should be merged first in order for a test to pass.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by pacien — CHANGES_REQUESTED** [review]
Could you split the reformatting into a separate commit?

**Comment by gbtb** [comment]
> Could you split the reformatting into a separate commit?

Done. 

Just in case, there is a settings in github diff viewer to ignore whitespace changes, which will simplify review.

**Review by pacien — APPROVED** [review]
Looks good to me.
As expected, the check phase fails with mercurial 5.9 and passes with 6.0.

https://github.com/NixOS/nixpkgs/pull/155636 should be merged first.

CC @lukegb

**Comment by lukegb** [comment]
Manually merged in 0f3df5402378323b02068a19a5ed87809778a7f8.

**Pull request closed without merging**
