### PR TITLE
nixos/mysql: fix mysql test after #63862

### PR DESCRIPTION
**Pull request by thorstenweber83**
@aanderse @flokli 

I took another look at the mysql test and noticed the initialScript printing a syntax error.

###### Motivation for this change
Fix mysql test after #63862 introduced non-functional initialScript.
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by aanderse** [comment]
@thorstenweber83 Congratulations! You have demonstrated that the `mysql` test is useless as it reports success on failure :disappointed: Thanks for catching this.

@GrahamcOfBorg test mysql

**Comment by aanderse** [comment]
Alright tracked down the larger problem. I made the incorrect assumption that `writeShellScript` would pass the `-e` flag to `sh`, but it does not.

@deliciouslytyped I assume it is on purpose that the `-e` flag is not passed, right?
@thorstenweber83 Do you mind applying this to your PR as a second commit:
```
~/nixpkgs> git diff
diff --git a/nixos/modules/services/databases/mysql.nix b/nixos/modules/services/databases/mysql.nix
index 177e742d65e..3b5950c02e7 100644
--- a/nixos/modules/services/databases/mysql.nix
+++ b/nixos/modules/services/databases/mysql.nix
@@ -319,7 +319,9 @@ in
           ExecStart = "${mysql}/bin/mysqld --defaults-file=/etc/my.cnf ${mysqldOptions} $_WSREP_NEW_CLUSTER $_WSREP_START_POSITION";
           ExecStartPost =
             let
-              setupScript = pkgs.writeShellScript "mysql-setup" ''
+              setupScript = pkgs.writeText "mysql-setup" ''
+                #!${pkgs.runtimeShell} -e
+
                 ${optionalString (!hasNotify) ''
                   # Wait until the MySQL server is available for use
                   count=0
```

**Comment by deliciouslytyped** [comment]
@aanderse I just copied writeShellScriptBin. I'm no bash guru, and though maybe nice, `-e` sounds like it would be pretty hardcore for an arbitrary script?

**Comment by aanderse** [comment]
@deliciouslytyped All generated `preStart` and `postStart` scripts in our `systemd` modules run with `-e` and this is where I went wrong. The way `writeShellScript` works currently is more general purpose and probably should remain that way I guess... Thanks!

**Comment by thorstenweber83** [comment]
@aanderse I had to use writeScript for the executable bit.
Now the test fails when i put a syntax error into initialScript :+1:

**Comment by aanderse** [comment]
Thanks again @thornstenweber83!

**Pull request merged**
