### PR TITLE
stale bot: TL;DR

### PR DESCRIPTION
**Pull request by blaggacao**
The current text is an imposition on the reader, reformulate to make it short, concise and useful.

###### Motivation for this change

image

### CODE REVIEW

**Comment by nh2** [comment]
I have nothing against making long text shorter where possible, or improving formatting, but this PR currently also makes some changes I consider regressions:

* It removes some actionable advice (what to do when a maintainer approved your change, how to use `git blame` to find somebody relevant). That info seems very useful for newcomers; the new text appears to assume that you know all of that already.
* It changes the criterion of when to close issues, from a

    > checking if the issue is still valid. If it isn't, please close it.

  clear determination that the issue is invalid, to `If this might still be an issue, but you [one of many people pinged by the bot] don't have a vested interest in promoting it's resolution, please consider closing it while encouraging others to take over and reopen an issue if they care enough`.

  First, this weakens the condition on closure; with this new text, it suggests that any of the pinged people can determine that they themselves don't have a vested interest promoting the resolution, and thus close it. This is bad, because if the issue is, "XYZ is isn't working", then the issue should _not_ be closed when somebody loses interest in making it work, but only when XYZ is working again, or if software XYZ became obsolete.

  Second, it encourages a new mode of "well just close the issue for now even though it's still an issue, and suggests others can reopen it if they feel like it". This is a strong change from what the bot suggested so far.

**Comment by blaggacao** [comment]
> First, this weakens the condition on closure; with this new text, it suggests that any of the pinged people can determine that they themselves don't have a vested interest promoting the resolution, and thus close it. This is bad, because if the issue is, "XYZ is isn't working", then the issue should not be closed when somebody loses interest in making it work, but only when XYZ is working again, or if software XYZ became obsolete.

Good catch, wasn't not intended!

> Second, it encourages a new mode of "well just close the issue for now even though it's still an issue, and suggests others can reopen it if they feel like it". This is a strong change from what the bot suggested so far.

Indeed, but better be honest. Opening an issue or PR comes with great responsibility. Else, the real spammer is the proponent. So if the proponent doesn't have the capacity, motivation or intention to move things forward, they should step down. But since only authors have this implicit "ownership" / responsibility, and nobody has already stepped up and said" |I'm taking this over", then they should be fair and give way for others by closing. This is not true for any long standing issues submitted by the veterans of the project, but the stalebot probably is not for the veterans anyway. AFAIK, there veterans could tell the stale but to shut up perpetuously by adding a new label which the stalebot disregards. I'm adding this into this PR, to completely address this concern.

**Comment by blaggacao** [comment]
@nh2 Thanks for your comment! Can you revise (and eventually hide it as resolved) under the light of:
- https://github.com/NixOS/nixpkgs/pull/100462/commits/f7d1146fd33302096a00e09d63bc7fe52255fd06
- https://github.com/NixOS/nixpkgs/pull/100462/commits/1ed7a23e4c23a4eeded909efa565e97bcbb0d075

Or give any additional feedback with the goal to resolve your feedback as quick as possible.

**Comment by blaggacao** [comment]
### Renderd PR


Hello, I'm a bot and I thank you in the name of the community for your contributions.

Nixpkgs is a busy repository, and _very_ unfortunately sometimes PRs get left behind for too long.

So my role is to be explicit about it:

- There was no activity on this PR for 180 days.
- So I marked it as `2:status: stale`.

Let me remind you, that I'm a kind bot:

- I'll never close any Pull Request. Promised.

#### A few suggestions (for authors)

1. If you bother this being marked as stale, just leave a comment. No questions asked.
2. If this is unfinished work and you plan on finishing it some time in the future, please mark it as a draft PR.
3. If you want to abandon this work for whatever reason, please consider closing this PR with a short comment. Maybe somebody else wants to pick this up?
4. If you want to get things rolling again, first make sure to rebase the PR and have all valid comments addressed.
5. Then, if you need a review to push things forward, [try this thread](https://discourse.nixos.org/t/prs-in-distress/3604).
6. Though, if all you need is a merger, check out the git history to find and [request reviews](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/requesting-a-pull-request-review) from people who usually merge things in adjacent code. 
    
***How to find the right people to ping?*** &rarr; [`git blame`](https://git-scm.com/docs/git-blame) to the rescue or GitHub's history button!

_Note: As a regular subscriber, you are invited to take initiative within due reason. Just make sure to duly coordinate with the author._

Lastly, you can always ask for help at [our Discourse Forum](https://discourse.nixos.org/) or at [#nixos' IRC channel](https://webchat.freenode.net/#nixos).


### Rendered Issue


Hello, I'm a bot and I thank you in the name of the community for opening this issue.
    
Nixpkgs is a busy repository, and _very_ unfortunately sometimes issues get left behind for too long.
    
So my role is to be explicit about it:
    
- There was no activity on this issue for 180 days.
- So I marked it as `2:status: stale`.
    
Let me remind you, that I'm a kind bot:
    
- I'll never close any issue. Promised.
    
#### A few suggestions (for authors)
    
1. If you bother this being marked as stale, just leave a comment. No questions asked.
2. If this issue is no longer one (either for you, personally, or in general), please consider closing it.
3. If this might still be an issue, but you don't have a vested interest in promoting it's resolution, please consider closing it while encouraging others to take over and reopen an issue if they care enough.
4. If you still have interest in pushing this issue, try to ping somebody who you believe might have an interest in the topic. Consider exposing the problem in [our Discourse Forum](https://discourse.nixos.org/).
5. As in all open source projects, though, by far your best option is to submit a Pull Request that adresses this issue.
    
***How to find the right people to ping?*** &rarr; [`git blame`](https://git-scm.com/docs/git-blame) to the rescue or GitHub's history button!
    
_Note: Closed issues are still around, and people actually _do_ occasionally search closed issues, so nothing at all is lost.
They also can be reopened at any time, for example, once you've gained renewed interest in the issue.
So, when in doubt, closing mostly helps real human beings to deal with the sheer complexity of the amount of open issues on this project._
    
_Note: As a regular subscriber, you are invited to also take initiative within due reason. Just make sure to duly coordinate with the author._

Lastly, you can always ask for help at [our Discourse Forum](https://discourse.nixos.org/) or at [#nixos' IRC channel](https://webchat.freenode.net/#nixos).

**Comment by edolstra** [comment]
> The current text is an imposition on the reader, reformulate to make it short, concise and useful.

Doesn't this PR make the message left on issues *longer*? According to the diff it replaces ~164 words by ~313. In the interest of brevity it's probably best to leave out lines like "So it is my most undesired pleasure to be explicit about it:". Or advice like "5. As in all open source projects, though, by far your best option is to submit a Pull Request that addresses this issue" which is true but not super useful, since if the submitter had the ability to fix the issue, they probably would have done so already.

I'm not sure a "never-stale" label is a good idea. It just means that eventually we're going to need a bot to clean up the never-stale issues...

**Comment by blaggacao** [comment]
@edolstra Thanks for your comment. I'm also in favor of brevity. It is a kind of balancing act when coming from a clearly policially motivated formulayion (see RFC51) while still keeping everybody happy. That is my crux when really wanting to be short. I have an idea: I'm not only going to shorten as per yous suggestion, but allso put the suggestions behind a `<details>` block.

@nh2 had convincing arguments for the "never-stale" label. Furthermore, only maintainers can put it. I think, it should not be documented further, but it's tacit existence is a (hypothetical) escape vent for frustrated community members which have a hard time seeing their issues going stale or are at risk of being unduly bothered by "irrelevent" notifications. Example uses are meta-issues and the like.

**Comment by edolstra** [comment]
Another possibility is to put that information somewhere else (e.g. in the manual) and link to it from the comment. That way we don't have to duplicate a large body of text (which could get outdated) across hundreds of issues.

Regarding "never-stale": yeah, it sounds fine if only maintainers can add that label.

**Comment by blaggacao** [comment]
@edolstra 
> Another possibility is to put that information somewhere else (e.g. in the manual) and link to it from the comment. That way we don't have to duplicate a large body of text (which could get outdated) across hundreds of issues.

I've done the shortening, but will be leaving the linking for another PR. I want to see once again to RFC 75 for that after the Homepage is completely refurbished.

**Comment by ryantm** [comment]
I think we should move it into the manual as edolstra suggests. Then the bot message can be much more minimal.

**Comment by blaggacao** [comment]
> I think we should move it into the manual as edolstra suggests. Then the bot message can be much more minimal.

I have a problem with this in that I cannot remember once having had an experience where I would have found what I have been looking for quickly in the current manual. Hence, I think the manual is not the right place. Something akin to a top level `CONTRIBUTING.md` would be a thing which people coming from other ecosystems would expect to find.

Anyway, since this change is small and incremental and fulfills its immediate purpose, let's not overload it.

So sorting out the manual/contributing.md question should be approached in a follow up PR.

**Comment by ryantm** [comment]
The only time you need to find it is when the bot mentions it, and there will be a link to it. I'd also be fine with putting it in a file like `nixpkgs/.github/stale.md`, then it would live next to the stale configuration.

I think it is a waste to put effort into this rewording when we are so close to having a place where a longer form message is okay.

**Comment by blaggacao** [comment]
`.github/STALE-BOT-HELP.md` was an excellent idea! Thank you @ryantm Done

**Comment by blaggacao** [comment]
Is something still holding this back?

**Comment by ryantm** [comment]
@blaggacao Please review https://github.com/NixOS/nixpkgs/pull/101320 I made the stale bot message even shorter, renamed the markdown file and edited your text.

**Comment by blaggacao** [comment]
#101320 ❤️

**Pull request closed without merging**
