### PR TITLE
solaar: 1.1.8 -> 1.1.9

### PR DESCRIPTION
**Pull request by Kranzes**
Diff: https://github.com/pwr-Solaar/Solaar/compare/refs/tags/1.1.8...1.1.9

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kranzes** [comment]
Result of `nixpkgs-review pr 243807` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>solaar.udev (logitech-udev-rules)</li>
    <li>solaar</li>
    <li>solaar.dist</li>
  </ul>
</details>

**Comment by oxalica** [comment]
Break for me.

It shows no devices and the tray icon is missing for 1.1.9, while everything works perfectly for 1.1.8 on master.

**Comment by Kranzes** [comment]
Interesting, it worked just fine for me with the Logitech G Pro Wireless.

**Comment by oxalica** [comment]
I have a Logitech G102 wired mouse. The `--debug` log complains about `hid-parser` dependency. [It is optional](https://github.com/pwr-Solaar/Solaar/blob/bee1b1dd39bbda376e6da2bd68adfe898505cce9/docs/installation.md?plain=1#L64) for a while. Maybe some internal changes made it required for my mouse somehow?

```
2023-07-16 23:41:27,035,035  WARNING [MainThread] logitech_receiver.diversion: rules cannot access active process or modifier keys in Wayland
2023-07-16 23:41:27,147,147  WARNING [MainThread] solaar.upower: failed to register suspend/resume callbacks
2023-07-16 23:41:27,199,199  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 000005AC PID 0000024F: No module named 'hid_parser'
2023-07-16 23:41:27,200,200  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 000005AC PID 0000024F: No module named 'hid_parser'
2023-07-16 23:41:27,200,200  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 0000046D PID 0000C092: No module named 'hid_parser'
2023-07-16 23:41:27,201,201  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 0000046D PID 0000C092: No module named 'hid_parser'
2023-07-16 23:41:27,258,258    ERROR [MainThread] logitech_receiver.base: (13) device 255 error on feature request {0D2D}: 2 = invalid argument
2023-07-16 23:41:27,258,258  WARNING [MainThread] logitech_receiver.settings: report_rate: error applying value 1 so ignore it (<Device(255,C092,G102 Lightsync Mouse,)>)
2023-07-16 23:41:27,263,263  WARNING [MainThread] hidapi.udev: Report Descriptor not processed for BID 0003 VID 00000424 PID 0000274C: No module named 'hid_parser'
^Csolaar: exit due to keyboard interrupt
```

**Comment by Kranzes** [comment]
@oxalica Could you try adding it to the expression on your machine and test it?

**Comment by oxalica** [comment]
Okay, I confirmed it's caused by the missing hid-parser dependency. With it added, the mouse is detected and configurations also work. Here's the patch:

```diff
diff --git a/pkgs/applications/misc/solaar/default.nix b/pkgs/applications/misc/solaar/default.nix
index 2596b5d673c..be0d29ee507 100644
--- a/pkgs/applications/misc/solaar/default.nix
+++ b/pkgs/applications/misc/solaar/default.nix
@@ -44,6 +44,7 @@ python3Packages.buildPythonApplication rec {
     pyudev
     pyyaml
     xlib
+    hid-parser
   ];
 
   # the -cli symlink is just to maintain compabilility with older versions where
diff --git a/pkgs/development/python-modules/hid-parser/default.nix b/pkgs/development/python-modules/hid-parser/default.nix
new file mode 100644
index 00000000000..907d92ba369
--- /dev/null
+++ b/pkgs/development/python-modules/hid-parser/default.nix
@@ -0,0 +1,20 @@
+{ lib
+, buildPythonPackage
+, fetchPypi
+}:
+
+buildPythonPackage rec {
+  pname = "hid-parser";
+  version = "0.0.3";
+
+  src = fetchPypi {
+    inherit pname version;
+    hash = "sha256-zbm+h+ieDmd1K0uH+9B8EWtYScxqYJXVpY9bXdBivA4=";
+  };
+
+  meta = with lib; {
+    description = "Typed pure Python library to parse HID report descriptors";
+    homepage = "https://github.com/usb-tools/python-hid-parser";
+    license = with licenses; [ mit ];
+  };
+}
diff --git a/pkgs/top-level/python-packages.nix b/pkgs/top-level/python-packages.nix
index 828108c74c8..99d86fcc7b0 100644
--- a/pkgs/top-level/python-packages.nix
+++ b/pkgs/top-level/python-packages.nix
@@ -4692,6 +4692,8 @@ self: super: with self; {
     inherit (pkgs) udev libusb1;
   };
 
+  hid-parser = callPackage ../development/python-modules/hid-parser { };
+
   hieroglyph = callPackage ../development/python-modules/hieroglyph { };
 
   hijri-converter = callPackage ../development/python-modules/hijri-converter { };
```

**Comment by Kranzes** [comment]
Result of `nixpkgs-review pr 243807` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>solaar.udev (logitech-udev-rules)</li>
    <li>python310Packages.hid-parser</li>
    <li>python310Packages.hid-parser.dist</li>
    <li>python311Packages.hid-parser</li>
    <li>python311Packages.hid-parser.dist</li>
    <li>solaar</li>
    <li>solaar.dist</li>
  </ul>
</details>

**Review by oxalica — APPROVED** [review]
LGTM. Works for me.

Result of `nixpkgs-review pr 243807` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>solaar.udev (logitech-udev-rules)</li>
    <li>python310Packages.hid-parser</li>
    <li>python310Packages.hid-parser.dist</li>
    <li>python311Packages.hid-parser</li>
    <li>python311Packages.hid-parser.dist</li>
    <li>solaar</li>
    <li>solaar.dist</li>
  </ul>
</details>

**Pull request merged**
