### PR TITLE
Updated vim packages

### PR DESCRIPTION
**Pull request by softinio**
###### Motivation for this change
Updated vim packages

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by softinio** [comment]
Gave up waiting for review and merge especially now it requires a rebase. Will submit again some other day.

**Comment by jonringer** [comment]
sorry about my response, been busy with personal life stuff, and a lot of stuff got dropped :(

**Comment by softinio** [comment]
@jonringer no problem at all I get OSS as I contribute regularly. 

How do I become a codeowner/merger so I can help you and nix? This way load isn't just on you :-) 

FYI areas I am happy to help in are all things vim, python and scala related.

**Comment by jonringer** [comment]
to get commit access, I don't think there's a set requirements, more or less this is done organically by how often people feel that your reviews are aligned with good practices and maintaining code quality. Since nixpkgs is a mono-repo, commit access does kind of give you keys to the castle, so there's not a lot of desire to give it out freely. See https://github.com/NixOS/nixpkgs/issues/50105 for more info.

**Pull request closed without merging**
