### PR TITLE
libreoffice, hyphen: Load hyphen dicts in LibreOffice, modularize hyphen dicts, add german hyphen dict

### LINKED ISSUE #14430: Spellchecking - Hyphenation - Thesaurus
## Spelling - Hyphenation - Thesaurus

Make spellchecking work properly in all languages. I think the focus should be on hunspell.
FF, Libreoffice, KDE (sonnet) all use hunspell.

#### spellchecking

* Hunspell (supersedes MySpell, probably most common, lots of languages)
* Aspell (supersedes ISpell, probably second most common, lots of languages)
* HSpell (spell checking for Hebrew)
* voikko (spell checking for Finnish)
* Enchant (meta: can use Hunspell/Aspell/HSpell)
* Sonnet (KDE: can use Hunspell, voikko, HSpell)
* Firefox (uses Hunspell)
* LibreOffice (uses Hunspell)
* ... various others

#### Spellchecking

* *hunspell*: has some languages but not all available / files are found by some programs and not by others
* *aspell*: (TODO)

### Sources for hunspell

*hunspell*: Libreoffice has a nice collection https://github.com/LibreOffice/dictionaries. This also contains Thesaurus and Hyphenation

...

### Paths

*Aspell*: probably works with the variable $ASPELL_CONF

*Hunspell*: is more problematic because the callee decides on where it searches for the files.

Hunspell files go in (as is the case currently):
/run/current-system/sw/share/myspell/dict && /run/current-system/sw/share/hunspell/
~/.nix-profile/share/myspell/dict && ~/.nix-profile/share/hunspell

enchant and firefox (maybe throught enchant) are smart enough to find them there because of $XDG_DATA_DIRS

sonnet (KDEs spellchecker) and LibreOffice are not smart enough.

...

#### Spellchecking
hunspell-dict-en-us (exist in NixOS)
aspell-dict-en (exist in NixOS)

#### Thesaurus
mythes-en (name in Debian)

#### Hyphenation
hyphen-en (name in Debian)

#### Meta packages
Should there be meta packages for languages? Or for all languages?

#### Tasks

- [ ] make hunspell, hyphen and mythes packages from LibreOffice/dictionaries
- [ ] ensure files are found for hyphen and mythes
- [ ] fix sonnet: complain upsteam about them not obeying XDG Standard?
- [ ] fix libreoffice: (TODO)
- [ ] package: voikko

### PR DESCRIPTION
**Pull request by theCapypara**
## Description of changes
Fixes parts of #14430

Let me know if I should split this PR! I needed all these things so I added and tested them together.

1. Makes sure that all hyphen dictionaries are loaded for LibreOffice (1st commit)
2. Adds a new package group `hyphenDicts` that follows the same principle as `hunspellDicts` (2nd commit)
3. Removes the `en_US` dict from `hyphen` and moves it to `hyphenDicts.en_US` (2nd commit)
4. Adds the hyphen dictionaries `de_DE`, `de_CH`, `de_AT`

NOTE: This is a breaking change, as `hyphen` now no longer contains the `en_US` dictionary.

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by theCapypara** [comment]
@Br1ght0ne for hyphen
I'm not really sure who to tag for libreoffice, there is no GitHub user named "raskin"... @7c6f434c is that you? Sorry if not!

**Comment by 7c6f434c** [comment]
Yes, as described in maintainer-list.nix, but maybe I should just make everything uniform… it's not like any plausible future hosting platform is likely to have a name collision for 7c6f434c.

**Review by 7c6f434c — APPROVED** [review]
Looks good to me, but I want to see ofBorg builds and also if there are unexpected rev-deps for hyphen

**Comment by 7c6f434c** [comment]
Oh right, to add yourself as a maintainer you should also add yourself to the maintainer-list.nix

**Comment by theCapypara** [comment]
Oh, alright! Didn't know that existed, first time contributor and all. Will have a look!

**Comment by 7c6f434c** [comment]
Typo revealed by ofBorg eval error

**Comment by theCapypara** [comment]
Oh wow, whoops.

**Pull request merged**
