### PR TITLE
ycmd: 2016-01-12 -> 2017-02-03

### LINKED ISSUE #14349: ycmd fails to work with Atom you-complete-me plugin due to wrapper script
## Basic info

To make sure that we are on the same page:
- Kernel: `Linux szamito 3.18.24 #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970 x86_64 GNU/Linux`
- System: `15.09.git.45128deM (Dingo)`
- Nix version: `nix-env (Nix) 1.10`
- Nixpkgs version: `"15.09.1177.f8a795e"`
## Describe your issue here

I installed atom and ycmd, and the you-complete-me plugin for Atom, but none of the YCM functionality in Atom seems to work.
### Expected result

It works.
### Actual result

It doesn't.
### Steps to reproduce

`nix-env -i ycmd atom`
Install you-complete-me from Atom's package manager.
Set the ycmd path in the plugin's settings appropriately (`/home/glaebhoerl/.nix-profile/lib/ycmd` in my case)
Open a C/C++ source file, right click on something, try (e.g.) "GoToDeclaration" from the "YouCompleteMe" submenu
(nothing happens)

---

Boilerplate out of the way!

The above commands all say 15.09, but I installed ycmd and atom from the 16.03 beta channel. `atom-1.5.3`, `ycmd-2016-01-12`, you-complete-me plugin is 0.7.4.

Running Atom in Dev Mode, if we try anything from the YouCompleteMe submenu, we see this in the debug console:

you-complete-me-python

Looking at that `__main__.py` file, we see that it contains:

``` bash
#! /nix/store/w6rc026a5kw9zyvvapqq6li157ckvwq7-bash-4.3-p42/bin/bash -e
export PYTHONPATH=/nix/store/9jlki3pyyxxlldsdj2zr2d5y637lfr8r-python2.7-waitress-0.8.9/lib/python2.7/site-packages:/nix/store/jzq8nbp1z182kxz3vyj51p2qki2s1vdq-python2.7-frozendict-0.5/lib/python2.7/site-packages:/nix/store/7h43ls1ixp0s1vhbdjjm44dvdkaggmlk-python2.7-bottle-0.12.8/lib/python2.7/site-packages${PYTHONPATH:+:}$PYTHONPATH
exec -a "$0" /nix/store/f91xrlqmby1sb0c3jsqbycmf19sk4nja-ycmd-2016-01-12/lib/ycmd/ycmd/.__main__.py-wrapped "${extraFlagsArray[@]}" "$@"
```

It's actually a bash script! Which Nix created to setup `PYTHONPATH` before invoking the _real_ `__main__.py` from `ycmd`. And the syntax error is presumably because Atom/YCM are trying to execute it as a python script.

We can verify this by looking at the [source for the you-complete-me plugin](https://github.com/Qusic/atom-youcompleteme/blob/9c856557ff7acc16777bdf782f547777cf7d6b4d/lib/handler.coffee#L60-L64):

``` coffee
  startServer = (optionsFile) -> new Promise (fulfill, reject) ->
    ycmdProcess = new BufferedProcess
      command: atom.config.get 'you-complete-me.pythonExecutable'
      args: [
        path.resolve atom.config.get('you-complete-me.ycmdPath'), 'ycmd'
```

But I'm not sure where or how this should be fixed.

### PR DESCRIPTION
**Pull request by d-xo**
###### Motivation for this change
Updates to latest version. Fixes #14349

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by LnL7** [comment]
I didn't know we have this, I feel like should `vimPlugins.youcompleteme` use it.

**Comment by rasendubi** [comment]
This PR makes ycmd copy all its third party dependencies to the output. This includes a couple of python packages as well as _source code_ for racerd, gocode, godef, and OmniSharp. (This adds additional 42M to the package size.) Is there any good reason for doing so?

I'm also not sure how this fixes https://github.com/NixOS/nixpkgs/issues/14349, because python scripts are still wrapped in bash scripts.

**Comment by cstrahan** [comment]
The majority of the third_party disk util is OmniSharpServer:

```
   26.2 MiB [##########] /OmniSharpServer
    3.9 MiB [#         ] /JediHTTP
    3.8 MiB [#         ] /python-future
    1.9 MiB [          ] /requests
    1.0 MiB [          ] /bottle
  844.0 KiB [          ] /gocode
  564.0 KiB [          ] /godef
  564.0 KiB [          ] /waitress
  380.0 KiB [          ] /argparse
  184.0 KiB [          ] /racerd
   28.0 KiB [          ] /frozendict
    4.0 KiB [          ] /tern_runtime
```

I almost wouldn't be opposed to vendoring some of the other deps though. In the PR I opened above, I think I'll probably just vendor JediHTTP, since it's not a legitimate python package (doesn't have a `setup.py`, and they're not likely to keep up to date with breaking changes in their deps, since they too vendor stuff...). With all that said, might make sense to use ycmd's vendored python deps too, but I've decided to stick with using our packaged versions for now.

**Comment by xwvvvvwx** [comment]
Yeah this was rushed. Apologies. 

Declining in favor of the PR from @cstrahan.

As a side note, @rasendubi the `__main__.py` output from this expression is definitely not wrapped in bash script (or at least the one installed into my `~/.nix-profile/bin`), but the path is also no longer modified.

**Pull request closed without merging**
