### PR TITLE
vulkan-validation-layers: fix bug related to XDG_DATA_DIRS

### PR DESCRIPTION
**Pull request by loewenheim**
###### Motivation for this change
Fix issue #89816 as suggested there.

###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
The whole setup hook might not be needed after: https://github.com/NixOS/nixpkgs/pull/103501

You will just need `vulkan-validation-layers` listed as a `nativeBuildInput`

**Comment by loewenheim** [comment]
All the better. Is that change going to be available on `20.09`?

**Review by Ralith — APPROVED** [review]

**Comment by jonringer** [comment]
> All the better. Is that change going to be available on `20.09`?

probably, I wanted some time for it to "bake" in master to ensure that it's working as intended.

**Comment by tcmal** [comment]
Can this be merged? Am currently encountering target/lorri#262 which seems to be blocked by this.

**Review by kanashimia — CHANGES_REQUESTED** [review]
Removing `setupHook` all together does indeed work now, so should probably do that.

**Review by Ralith — APPROVED** [review]

**Comment by loewenheim** [comment]
Someone else will have to merge it, I don't have rights :)

**Review by kanashimia — APPROVED** [review]

**Review by Ralith — APPROVED** [review]

**Pull request merged**
