### PR TITLE
[WIP] nixos/systemd-boot: boot counting and automatic fallback

### PR DESCRIPTION
**Pull request by danielfullmer**
###### Motivation for this change
This draft PR adds support for `systemd-boot` "automatic boot assessment".
For background information, please first read the following document: https://systemd.io/AUTOMATIC_BOOT_ASSESSMENT/

Setting `boot.loader.systemd-boot.counters.enable = true` enables this optional functionality.
Since what a "successful boot" exactly means is somewhat context dependent, systemd provides `boot-complete.target` which serves as a synchronization point that an end user could order necessary services before. The boot entry will be marked as successfully booting only if this target succeeds.
For unattended boots, there are some other potentially useful options such as adding `panic=1` to `boot.kernelParams` or setting `FailureAction=reboot` for certain necessary services. However, these are end-user concerns that are somewhat orthogonal to boot counting and automatic fallback, and they probably do not belong in this PR.

This is a draft PR, as there are a few issues that still need to be resolved:
 - [x] The menu entries appear to be ordered incorrectly upstream: https://github.com/systemd/systemd/issues/15256 _(fixed upstream, should be in v246)_
 - [ ] The `systemd-boot` test needs a writable boot disk (since boot counters are state included in the entry filenames). I have a hack enabling this, which should be cleaned up somehow.
 - [ ] Documentation is needed

---

_(edit: the issue below has been resolved to my satisfaction)_

Perhaps the biggest current issue which could use some feedback on is how we set the "default" for `systemd-boot`. Normally, `systemd-boot-builder.py` sets the `default` entry in `loader.conf`. The logic in `systemd-boot` means that this entry would always be selected--overriding anything having to do with boot counters. I've disabled setting `default` in this draft PR, and so `systemd-boot` should select the latest generation which does not have 0 tries left. However, this would break the ability for the user to switch back to a previous generation, which is clearly undesirable. Perhaps we need to further patch `systemd-boot` to use `default` only if it has remaining tries left, and otherwise select the latest generation with remaining tries left.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by grahamc** [comment]
cc @adisbladis for interest

**Comment by flokli** [comment]
@danielfullmer with 245.3 merged into master, can you rebase this PR and see if it's still broken upstream?

**Comment by danielfullmer** [comment]
@flokli Sure, just rebased. There haven't been any relavent changes to `systemd-boot` in the meantime.

Since I haven't received any response about the menu ordering here systemd/systemd#15256, I'll send a patch upstream to see if that sparks any discussion.

I also recently patched `systemd-boot` to ignore default entries which have no tries left. That allows me to remove the hack where I commented out the default setting in `systemd-boot-builder.py`. I'll see if I can get any upstream feedback on whether the original behavior was intended or not.

Just to be clear, the logic is now this: We select the default entry specified in `loader.conf` (which should be the current generation), unless this entry has zero tries left. In that case, we select the entry with the highest `version` string (basically, generation number) which has a nonzero number of tries left.

**Comment by flokli** [comment]
I just [prepared the bump to `245.6`](https://github.com/NixOS/nixpkgs/pull/90333), which doesn't seem to include https://github.com/systemd/systemd/pull/15577 - do we need to wait for 9eaac58683788ae1870760ad61d594c8ce7a43a8 to have landed in our systemd package?

We also might need to address https://github.com/NixOS/nixpkgs/issues/86422#issuecomment-622272598, so actual sd-boot fixes manifest on existing installations.

**Comment by danielfullmer** [comment]
@flokli Yeah, it's probably best to wait for the next major systemd release before merging.

I actually have a little more free time now. So I'll see if I can take a look at https://github.com/NixOS/nixpkgs/issues/86422 again either today or tomorrow.

**Comment by danielfullmer** [comment]
I've resolved the earlier issue with the `default` selection to my satisfaction.  To review, the problem is that systemd will always select an entry matching `default` set in `loader.conf`, even if that entry didn't have any tries left.  Since we currently set `default` to only match a single entry, it would never fallback to any other entry.

My fix was this: instead of setting (for example) `default nixos-generation-15`, we now set `default nixos-generation-*`, and rely on the systemd-boot's lexicographic ordering of the entry filenames to ensure we actually default to the proper entry.  This way, if the default boot entry has no tries left, there could still be another entry matching `nixos-generation-*` which systemd-boot could try instead.

Since the proper default generation might not be the highest numbered generation, I've renamed the default entry to (for example) `nixos-generation-default-15`.  This would be compared against other entries named (for example)`nixos-generation-20`. Since `'d'` is lexicographically greater than `'1'` (or any other digit), `nixos-generation-default-15` is ordered last, which is the one that systemd-boot chooses as the default selection.  This does seem a little hackish, but I think this is the best approach. I will add comments to the source explaining this.

This approach has the additional benefit that non-default system profiles would be respected.  If the user has run `nixos-rebuild boot --profile-name test`, and the latest `test` generation is not booting correctly, `systemd-boot` should only choose other `test` generations, not any other profile's generations.

**Comment by minijackson** [comment]
Hey!

I was trying to implement boot assessment independently, completely oblivious to this PR, and amazingly, we arrived at much of the same developments on many points!

They are a few things which I have/would have done differently though:

- I intended on creating a `boot.assessment` option, independently from `systemd-boot`, since other bootloaders have a similar support (like the `fallback` option of grub)
- For the `default` issue, my first intuition was that the `systemd-bless-boot.service` would change the content of `loader.conf` and set the `default`. This has the advantage that people can still rollback to a previous profile, and if this profile is "bad", it would rollback a generation further, and so on.
- Another possibility, is to upstream a change to systemd-boot that filters out or reorder every entry that do not have any tries left.
- I would like to implement a `boot.assessment.requiredUnits` that automatically blesses the boot as "bad" when they fail, or reboot the system (still WIP on my end)

In any case, I'm willing to participate in this PR in any way I can! (I'm available in Matrix/IRC)

**Comment by minijackson** [comment]
Also, I've found in that in the nixos test, we need to setup the profile links manually, instead of using `nix-env --profile ... --set ...` because the `regInfo` is not passed in the kernel parameters when `useEFIboot` is set to `true` in `qemu-vm.nix`, but I fail to see how to fix that without introducing a cyclic dependency. :confused:

**Comment by danielfullmer** [comment]
@minijackson Thanks for the interest! I'll give a few comments on your proposals:

> They are a few things which I have/would have done differently though:
> 
> * I intended on creating a `boot.assessment` option, independently from `systemd-boot`, since other bootloaders have a similar support (like the `fallback` option of grub)

I'm certainly open to something like this. One thing to watch out for is that different boot systems have slightly different fallback behavior.  For instance, once a boot entry is successful on `systemd-boot`, it will then be marked as successfully booting, disabling the counters and then always booting that entry by default--even if it starts failing later. (I believe android's A/B boot system acts similarly). IIRC grub and u-boot always keep the functionality active, falling back to some other entry whenever a boot entry fails a certain number of times.

Certainly something like systemd's `boot-complete.target` would be useful to share across bootloaders, however.

> * For the `default` issue, my first intuition was that the `systemd-bless-boot.service` would change the content of `loader.conf` and set the `default`. This has the advantage that people can still rollback to a previous profile, and if this profile is "bad", it would rollback a generation further, and so on.

Would your proposal be to modify `systemd-bless-boot.service` to do this?  I'm not exactly sure how this would work. When we switch generations, we want `default` to point to the new generation so that a reboot will try the new generation without any user interaction.  But then if it's failing I don't see how `systemd-boot` would select an earlier generation.

> * Another possibility, is to upstream a change to systemd-boot that filters out or reorder every entry that do not have any tries left.

This was my initial change that I made, before I found the new approach for `default`.  It would require convincing upstream that this is proper behavior, which I'm not sure it is: one issue with this is that if all nixos entries are marked as failing, it would then boot some other entry (including potentially something like memtest86).

> * I would like to implement a `boot.assessment.requiredUnits` that automatically blesses the boot as "bad" when they fail, or reboot the system (still WIP on my end)

:+1: Yeah, I'd like to have some easy to set option(s) that guarantee (as much as we can) that an improperly booting system will eventually return to an earlier generation without any further user-interaction.  Like I said earlier, this could involve setting `panic=1` to `boot.kernelParams`, setting `FailureAction=reboot` on necessary services, and ordering necessary services before `boot-complete.target`. We don't want to end up with a "partially booted" system that (for instance) doesn't provide SSH/network access, but also doesn't reboot to try an earlier generation automatically.

> In any case, I'm willing to participate in this PR in any way I can! (I'm available in Matrix/IRC)

Cool! I'll reach out to you.

**Comment by cole-h** [comment]
Hi @danielfullmer,

I just wanted to swing by and say: thank you for your work on this! I tested this on my machine just now and it works flawlessly.

Is there anything I can do to help move this into a mergeable state?

**Review by cole-h — COMMENTED** [review]
Something I just noticed (after having switched off of using this PR) -- I still have boot entries with counters attached, but I *also* have the same profiles without counters. e.g.:

```
$ ls /boot/loader/entries
[...]
.rwxr-xr-x 690 root 22 Mar 11:49 nixos-generation-70+0-1.conf
.rwxr-xr-x 580 root 23 Mar 13:29 nixos-generation-70.conf
.rwxr-xr-x 690 root 22 Mar 11:49 nixos-generation-71+0-1.conf
.rwxr-xr-x 580 root 23 Mar 13:29 nixos-generation-71.conf
.rwxr-xr-x 690 root 22 Mar 11:49 nixos-generation-72+0-1.conf
.rwxr-xr-x 580 root 23 Mar 13:29 nixos-generation-72.conf
.rwxr-xr-x 690 root 22 Mar 11:49 nixos-generation-73+0-3.conf
.rwxr-xr-x 580 root 23 Mar 13:29 nixos-generation-73.conf
.rwxr-xr-x 580 root 23 Mar 13:29 nixos-generation-74.conf
.rwxr-xr-x 580 root 23 Mar 13:29 nixos-generation-76.conf
.rwxr-xr-x 690 root 22 Mar 11:49 nixos-generation-default-74+3.conf
```

If boot counters are ever disabled and we see that there are profiles with a counter attached, what should be done? Nothing (and continue to regenerate the counted profiles on `nixos-rebuild switch`)? Skip it (e.g. don't regenerate that profile)?

**Comment by RaitoBezarius** [comment]
This still looks interesting, can we do something to help?

**Comment by RaitoBezarius** [comment]
Still interested, can we help you @danielfullmer ?

**Comment by danielfullmer** [comment]
Man this has been on my TODO list for so long, apologies for not taking it the last 20% and trying to get it merged.  I now have a concrete need for this feature so I intend to work on this soon (on the order of weeks).  If anyone gets to it before I do: I know we'll at least need to (1) Resolve any conflicts and ensure the feature still works (2) Figure out a solution to @cole-h 's issue of how to handle boot entries if we turn the feature off and on, and (3) Write some documentation/release notes for the feature.  This is very likely too late to make it into 22.05, but it'd be nice to get it merged into master for the release after that.

**Comment by lovesegfault** [comment]
@danielfullmer Gentlest of pings :)

**Comment by dasJ** [comment]
Partly related, I have a half-baked implementation of this for grub at home. Main issue is that it's shitty to implement when we want proper counting and that I cannot get the test runner to do what I want

**Comment by domenkozar** [comment]
As part of [Cachix Deploy](https://blog.cachix.org/posts/2022-07-29-cachix-deploy-public-beta/), I'd very much like to sponsor this work to get it fixed for everyone in NixOS itself. Let me know if someone is willing to get it done :)

**Comment by danielfullmer** [comment]
@domenkozar I'm actually currently working on bringing this PR up-to-date with master right now. I know I've been meaning to work on this for a while now, and I don't want to prevent you from sponsoring someone else to work on this if needed. But if I don't have something within ~2 weeks, then take that as a sign that I might not get to it for a while longer.

**Comment by samueldr** [comment]
> @domenkozar I'm actually currently working on bringing this PR up-to-date with master right now. I know I've been meaning to work on this for a while now, and I don't want to prevent you from sponsoring someone else to work on this if needed. But if I don't have something within ~2 weeks, then take that as a sign that I might not get to it for a while longer.

Are **you** unable to get sponsored for this? Not sure if that's what @domenkozar could have had in mind.

**Comment by danielfullmer** [comment]
> Are **you** unable to get sponsored for this? Not sure if that's what @domenkozar could have had in mind.

It might be complicated for some unrelated reasons--but I'll reach out directly.

**Comment by RaitoBezarius** [comment]
> As part of [Cachix Deploy](https://blog.cachix.org/posts/2022-07-29-cachix-deploy-public-beta/), I'd very much like to sponsor this work to get it fixed for everyone in NixOS itself. Let me know if someone is willing to get it done :)

I'm interested into taking over for this and bringing this to completion if @danielfullmer cannot really anymore.

**Comment by n8henrie** [comment]
@dasJ Could you share more about your grub implementation?

Would love to see this PR go forward!

**Comment by RaitoBezarius** [comment]
Closing in favor of #273062 which is close to completion.

**Pull request closed without merging**
