### PR TITLE
Add ringcentral meetings

### PR DESCRIPTION
**Pull request by djmaze**
###### Motivation for this change

As a customer of Ringcentral, wanting / needing to use their video-conferencing solution included in the product portfolio.

Under the hood, this is essentially just a whitelabel clone of Zoom. As this is my first nix package, I just copied the `zoom-us` package definition and adjusted it. So please advice if something is awkward.

The package version is taken from the value shown in the running application. The [download page](https://support.ringcentral.com/s/download?language=en_US) shows a totally different version 7.0.1 for the Linux version. Not sure if that makes sense.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 101100** [comment]
Any way this could be updated and merged?  I am in need of RingCentral, too.

**Comment by djmaze** [comment]
Not using Ringcentral anymore, so I am not really motivated to work on this any further. Happy to handover to someone who is.

**Comment by 101100** [comment]
It turns out RingCentral is not the client I was looking for, so I'm not going to be picking this up.

**Comment by SuperSandro2000** [comment]
Closing because the creator does not plan to maintain it and it is to complex for me. If anyone wants to pick this up feel free to do so.

**Pull request closed without merging**
