### PR TITLE
make `nix-env -qa` include unfree packages

### PR DESCRIPTION
**Pull request by vcunat**
I leave to discussion whether this would promote unfree packages too much or not.

This makes `nix-env -qa` always include unfree packages. The error is still thrown on package derivation instantiation.

I had to move the check to an ugly place, as even the innermost attrmap was evaluated by `nix-env -qa`.

### CODE REVIEW

**Comment by rbvermaa** [comment]
I don't think we should show the unfree packages by default, even on -qa. We should keep nixpkgs as 'free' as possible. I do think however, that we should add a small statement or section to the nixpkgs/nixos manual describing this, and an explanation that if the user wants to use non-free software, how he can accomplish this. 

There will still be people who think that nixpkgs isn't free when such a reference is in the manual, and the sources contains references to unfree software, however, this way we are at least working in the spirit of keeping nixos/nixpkgs as free as possible.

**Comment by vcunat** [comment]
- We're less strict than Debian, and GNU still won't consider *them* free enough.
- Newcomers typically won't know they have to enable anything. They will try to find packages they need and  report missing them or rather abandon nixpkgs straightaway.

Personally, I believe without this we'll be losing people that e.g. avoid unfree SW but others force them to use skypes and similars. They still need to **explicitly** enable an option, so they won't be just getting them without a warning.

**Comment by rbvermaa** [comment]
As long as it is clearly documented in the manual, users will find what they need, in my opinion. Do we have any evidence that we have been losing many users due to this?

I agree it is a (small) pain, and personally I do not have a very big problem with unfree software, however in my opinion NixOS/Nixpkgs will be as free as possible if we create a situation that enables the biggest possible set of both worlds, which is in my opinion disabling by default and clearly documenting our policy regarding this and instruction for people who choose to use non-free software.

**Comment by puffnfresh** [comment]
It could help with problems like I've had:

https://github.com/NixOS/nixpkgs/issues/4766

**Comment by vcunat** [comment]
@puffnfresh: no, this PR hasn't changed anything when instantiating/installing stuff. Only listing is changed. However, your suggests the error message should be improved.

**Comment by vcunat** [comment]
Added a commit changing the error message to better explain what to do, hopefully avoiding issues like #4766.

**Comment by puffnfresh** [comment]
@vcunat ah, even better. Thank you! :heart:

**Comment by eduarrrd** [comment]
How about issuing a warning (which can be disabled) on nix-env -qa that unfree (and broken) are not shown by default?

**Comment by Havvy** [comment]
Where would that warning be that it wouldn't be annoying to have to set the configuration option for that?

**Comment by eduarrrd** [comment]
Scenario: User just installed nix(os) and ran some `nix-env -q`.

Three part warning at the bottom of output:

1. Either:
  1. "unfree packages are not queried."
  2.  "unfree packages matched your query but are omitted."
2. "Set `nix.warnOnUnfreeInQuery` to false to silence this warning."
3. "Set `config.allowUnfree` in blabla to include unfree packages"

Obviously details need to be figured out but the general idea is hopefully clear.

**Comment by vcunat** [comment]
The two non-controversial commits were picked to master (I rebased this).

**Comment by vcunat** [comment]
Showing unfree stuff clearly doesn't seem wanted.

**Comment by iElectric** [comment]
FTR, I'm for unfree to be listed as installable software.

**Comment by geerds** [comment]
I think this behavior would be annoying, because even with explicitly disabled `allowUnfree` the user would see a lot of unfree packages. If he tries to install one of those packages (because he doesn't know whether it's free or not), that installation will fail. I think this will push the user to enable `allowUnfree`

What do you think about my idea:

- `nixos-generate-config --root /mnt` should generate a template including `allowUnfree = false;`
- The first use of `nix-env` should generate a basic `~/.nixpkgs/config.nix` including `allowUnfree = false;`  and inform the user about this option (just the first time). Or maybe even better: ask the user whether it should be enabled or not, before generating the initial config.
- Our Nix **and** NixOS docs should point out this option multiple times. I think a good place would be the install and package management section. Not just a simple text like `Allow installing of packages that are distributed under[...]` but also list 1-2 well-known example packages like Skype and inform the user that this option could be harmful (with a reference to a FSF article or anything like that)

bonus:
- `nix-env` could inherit NixOS's `allowUnfree` setting. This would be comfortable for NixOS users who have system wide enabled `allowUnfree`
- an easy to remember option for `nix-env` to temporary allow unfree packages. Maybe something like `nix-env -qAU`? (uppercase `U` for `[U]nfree`)

but of course:

- with *enabled* `allowUnfree`, `nix-env -qa` should show **all** packages
- with *disabled* `allowUnfree`, `nix-env -qa` should only show free packages

**Pull request closed without merging**
