### PR TITLE
tk-8_6: fix hash after tcl-8_6 update

### PR DESCRIPTION
**Pull request by wizeman**
###### Motivation for this change

tcl-8_6 was updated in 4fb92ae60d68344254b2bb753c03fd72f3ffb35c from 8.6.9 -> 8.6.11 but tk's hash wasn't updated at the same time, which means the current hash was still from tk 8.6.9 rather than 8.6.11.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wizeman** [comment]
This should be backported to 21.05.

**Comment by wizeman** [comment]
Added comments so people don't forget to update tk's hashes.

**Comment by wizeman** [comment]
cc @siraben @FRidh

**Comment by wizeman** [comment]
Should this be rebased to staging? What is the criteria for that, exactly?

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 125307` at b0c69a09 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>50 packages marked as broken and skipped:</summary>
  <ul>
    <li>OVMF-CSM</li>
    <li>cassandra_2_1</li>
    <li>cassandra_2_2</li>
    <li>deeptools</li>
    <li>gtmess</li>
    <li>hydrus</li>
    <li>impressive</li>
    <li>ocropus</li>
    <li>odpdown</li>
    <li>opentsdb</li>
    <li>pig</li>
    <li>polymake</li>
    <li>processing</li>
    <li>python38Packages.HTSeq</li>
    <li>python38Packages.caffe</li>
    <li>python38Packages.cnvkit</li>
    <li>python38Packages.dask-xgboost</li>
    <li>python38Packages.datashader</li>
    <li>python38Packages.fipy</li>
    <li>python38Packages.foundationdb51</li>
    <li>python38Packages.foundationdb52</li>
    <li>python38Packages.foundationdb60</li>
    <li>python38Packages.foundationdb61</li>
    <li>python38Packages.foxdot</li>
    <li>python38Packages.ignite</li>
    <li>python38Packages.python-csxcad</li>
    <li>python38Packages.python-openems</li>
    <li>python38Packages.spacy</li>
    <li>python38Packages.spacy-transformers</li>
    <li>python38Packages.textacy</li>
    <li>python38Packages.thinc</li>
    <li>python39Packages.HTSeq</li>
    <li>python39Packages.caffe</li>
    <li>python39Packages.cnvkit</li>
    <li>python39Packages.dask-xgboost</li>
    <li>python39Packages.fipy</li>
    <li>python39Packages.foundationdb51</li>
    <li>python39Packages.foundationdb52</li>
    <li>python39Packages.foundationdb60</li>
    <li>python39Packages.foundationdb61</li>
    <li>python39Packages.foxdot</li>
    <li>python39Packages.ignite</li>
    <li>python39Packages.python-csxcad</li>
    <li>python39Packages.python-openems</li>
    <li>python39Packages.thinc</li>
    <li>scribus</li>
    <li>spark</li>
    <li>spring</li>
    <li>springLobby</li>
    <li>yosys-bluespec</li>
  </ul>
</details>
<details>
  <summary>14 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/c5f74580e027f183e6cd1588e077668a">asciidoc-full-with-plugins</a></li>
    <li><a href="https://gist.github.com/fd276b5e9394d897072a44a22c2157a5">fop</a></li>
    <li><a href="https://gist.github.com/a864d272cc550ebfce6faefec0f43e43">helmholtz</a></li>
    <li><a href="https://gist.github.com/a449d950015390d58dc571d3cf4c9deb">igraph</a></li>
    <li><a href="https://gist.github.com/22c2c7f58cb8e2dcd2660726617e29d3">python38Packages.descartes</a></li>
    <li><a href="https://gist.github.com/7520678ee639be17c7ac687f0588768d">python38Packages.kmapper</a></li>
    <li><a href="https://gist.github.com/df0862ce912abf91521467c26633ba77">python38Packages.mlxtend</a></li>
    <li><a href="https://gist.github.com/cc1369cc4fa6e8e3a20a05078233dab4">python38Packages.python-igraph</a></li>
    <li><a href="https://gist.github.com/9ffff76bd1ab2a3eea98cdbf808cd94c">python38Packages.spyder-kernels_0_5</a></li>
    <li><a href="https://gist.github.com/fa442cbe328ed77c5332802b7ef605cb">python38Packages.trackpy</a></li>
    <li><a href="https://gist.github.com/f39107636337a68c5c06a37130154031">python39Packages.basemap</a></li>
    <li><a href="https://gist.github.com/c4805461ffd4e4c1bae59a67e6209c1d">python39Packages.descartes</a></li>
    <li><a href="https://gist.github.com/1ae8b4e1486b5d21829082a2e21d390e">python39Packages.python-igraph</a></li>
    <li><a href="https://gist.github.com/be0d648d7e9c72664c75f4bf75ef19ac">python39Packages.trackpy</a></li>
  </ul>
</details>
<details>
  <summary>595 packages skipped due to time constraints:</summary>
  <ul>
    <li>DisnixWebService</li>
    <li>OVMF</li>
    <li>OVMF-secureBoot</li>
    <li>R</li>
    <li>abcl</li>
    <li>adapta-gtk-theme</li>
    <li>adoptopenjdk-icedtea-web</li>
    <li>aiodnsbrute</li>
    <li>alloy (alloy5)</li>
    <li>alloy4</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>121 packages built successfully:</summary>
  <ul>
    <li>anki</li>
    <li>cbrowser</li>
    <li>corrscope</li>
    <li>flatcam</li>
    <li>graph-cli</li>
    <li>image-analyzer</li>
    <li>itktcl</li>
    <li>jre8 (jre8_headless)</li>
    <li>mnemosyne</li>
    <li>mrpeach</li>
    <li>puredata</li>
    <li>puremapping</li>
    <li>pyspread</li>
    <li>python38Packages.Pmw</li>
    <li>python38Packages.Pweave</li>
    <li>python38Packages.androguard</li>
    <li>python38Packages.ase</li>
    <li>python38Packages.castepxbin</li>
    <li>python38Packages.colorcet</li>
    <li>python38Packages.deap</li>
    <li>python38Packages.dufte</li>
    <li>python38Packages.flametree</li>
    <li>python38Packages.fonttools</li>
    <li>python38Packages.genome-collector</li>
    <li>python38Packages.glymur</li>
    <li>python38Packages.gtts</li>
    <li>python38Packages.holoviews</li>
    <li>python38Packages.imagecorruptions</li>
    <li>python38Packages.ipympl</li>
    <li>python38Packages.librosa</li>
    <li>python38Packages.lightning</li>
    <li>python38Packages.matplotlib</li>
    <li>python38Packages.memory_profiler</li>
    <li>python38Packages.monty</li>
    <li>python38Packages.moviepy</li>
    <li>python38Packages.mplfinance</li>
    <li>python38Packages.nbval</li>
    <li>python38Packages.osmpythontools</li>
    <li>python38Packages.panel</li>
    <li>python38Packages.parfive</li>
    <li>python38Packages.persim</li>
    <li>python38Packages.phik</li>
    <li>python38Packages.pims</li>
    <li>python38Packages.pint</li>
    <li>python38Packages.proglog</li>
    <li>python38Packages.pyalgotrade</li>
    <li>python38Packages.pycm</li>
    <li>python38Packages.pymatgen</li>
    <li>python38Packages.pyregion</li>
    <li>python38Packages.pyspice</li>
    <li>python38Packages.pytest-astropy</li>
    <li>python38Packages.pytest-astropy-header</li>
    <li>python38Packages.pytest-mpl</li>
    <li>python38Packages.pytest-regressions</li>
    <li>python38Packages.pytomlpp</li>
    <li>python38Packages.regional</li>
    <li>python38Packages.ripser</li>
    <li>python38Packages.scapy</li>
    <li>python38Packages.scikitimage</li>
    <li>python38Packages.seaborn</li>
    <li>python38Packages.showit</li>
    <li>python38Packages.tadasets</li>
    <li>python38Packages.tkinter</li>
    <li>python38Packages.tqdm</li>
    <li>twine (python38Packages.twine)</li>
    <li>python38Packages.vidstab</li>
    <li>python39Packages.Pweave</li>
    <li>python39Packages.androguard</li>
    <li>python39Packages.ase</li>
    <li>python39Packages.castepxbin</li>
    <li>python39Packages.colorcet</li>
    <li>python39Packages.deap</li>
    <li>python39Packages.dufte</li>
    <li>python39Packages.flametree</li>
    <li>python39Packages.fonttools</li>
    <li>python39Packages.genome-collector</li>
    <li>python39Packages.glymur</li>
    <li>python39Packages.holoviews</li>
    <li>python39Packages.imagecorruptions</li>
    <li>python39Packages.ipympl</li>
    <li>python39Packages.lightning</li>
    <li>python39Packages.matplotlib</li>
    <li>python39Packages.memory_profiler</li>
    <li>python39Packages.monty</li>
    <li>python39Packages.mplfinance</li>
    <li>python39Packages.nbval</li>
    <li>python39Packages.osmpythontools</li>
    <li>python39Packages.panel</li>
    <li>python39Packages.parfive</li>
    <li>python39Packages.persim</li>
    <li>python39Packages.proglog</li>
    <li>python39Packages.pyalgotrade</li>
    <li>python39Packages.pycm</li>
    <li>python39Packages.pycocotools</li>
    <li>python39Packages.pymatgen</li>
    <li>python39Packages.pyregion</li>
    <li>python39Packages.pyspice</li>
    <li>python39Packages.pytest-astropy</li>
    <li>python39Packages.pytest-astropy-header</li>
    <li>python39Packages.pytest-mpl</li>
    <li>python39Packages.pytest-regressions</li>
    <li>python39Packages.pytomlpp</li>
    <li>python39Packages.regional</li>
    <li>python39Packages.scapy</li>
    <li>python39Packages.scikitimage</li>
    <li>python39Packages.seaborn</li>
    <li>python39Packages.showit</li>
    <li>python39Packages.spyder-kernels_0_5</li>
    <li>python39Packages.tadasets</li>
    <li>python39Packages.tkinter</li>
    <li>python39Packages.tqdm</li>
    <li>python39Packages.vidstab</li>
    <li>remind</li>
    <li>tartube</li>
    <li>tclreadline</li>
    <li>tix</li>
    <li>tk (tk-8_6)</li>
    <li>tkcvs</li>
    <li>uudeview</li>
    <li>vkeybd</li>
    <li>wordnet</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by SuperSandro2000** [comment]
> Should this be rebased to staging? What is the criteria for that, exactly?

500+ rebuilds is a pretty good indicator. Also tk takes a while to build.

**Comment by wizeman** [comment]
Changed target branch to `staging`, thanks!

**Review by SuperSandro2000 — APPROVED** [review]

**Review by davidak — APPROVED** [review]
Change looks good

**Pull request merged**
