### PR TITLE
pantheon.elementary-code: 6.1.0 -> 6.2.0

### PR DESCRIPTION
**Pull request by bobby285271**
###### Description of changes
https://github.com/elementary/code/releases/tag/6.2.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bobby285271** [comment]
### [pantheon.elementary-code](https://github.com/elementary/code): [6.1.0 → 6.2.0](https://github.com/elementary/code/compare/6.1.0...6.2.0)



- [ ] [<code>863: Set window title to title of currently focused document. (#1139)</code>](https://github.com/elementary/code/commit/c56b9fb467ea38884d77e7666bdf628a4edbecb6)
- [ ] [<code>Show hidden folders by default (#1154)</code>](https://github.com/elementary/code/commit/83877c09a299c594af4b4200a459f85ca0eef131)
- [ ] [<code>1092 - Add location and count functionality  to Search and Replace (#1118)</code>](https://github.com/elementary/code/commit/fdebb1f2a7f31eb7106a417b995bad8f61f64378)
- [ ] [<code>Rewrite word completion to play nice with other completion providers. (#1125)</code>](https://github.com/elementary/code/commit/3f2e7052cca176bf3e12081ff4519cd820c4f2a5)
- [ ] [<code>MonitoredRepository: allow changing branch with untracked files (#1161)</code>](https://github.com/elementary/code/commit/a376b9bc81af48b1bed89e2cf1d95516ffb9347d)
- [ ] [<code>Use tilde (#1153)</code>](https://github.com/elementary/code/commit/446a52cf67ed3dc4dd82e6327bbd4898f4d593da)
- [ ] [<code>Meson: remove positional arguments from i18n.merge_file (#1165)</code>](https://github.com/elementary/code/commit/a2607cce3a6b1bb62d02456456d3cbc3c6530bb0)
- [ ] [<code>Search-bar enhancements (Regex Support) (#1170)</code>](https://github.com/elementary/code/commit/02f40c50a3beee935432a9be91b188c8dff1e027)
- [ ] [<code>Fix occasional crash in SearchBar (#1174)</code>](https://github.com/elementary/code/commit/4d6767ff9601a910404f5715d05e364853f21579)
- [ ] [<code>Only focus the current document on open (#1177)</code>](https://github.com/elementary/code/commit/a4685230e577b0537b3998af2c0f3a1498ec7022)
- [ ] [<code>Update appdata with recent changes (#1178)</code>](https://github.com/elementary/code/commit/9d840655c5c131809e9d2e5912121358c27c5944)
- [ ] [<code>Check fully for null doc in document change handler (#1146)</code>](https://github.com/elementary/code/commit/9db961ac3ebf32ab85837426540be2e964fc9791)
- [ ] [<code>Fix logic for duplicating unselected line. (#1137)</code>](https://github.com/elementary/code/commit/e2990f709dbd46c5f50c63a0f95d8ff55ff572ff)
- [ ] [<code>replace_home_with_tilde: use `substring()` to remove home directory (#1180)</code>](https://github.com/elementary/code/commit/e95da83ac9d336d9a74255aab8dea8d0825b4dfa)
- [ ] [<code>Include hyphen and underscore in word to match (#1160)</code>](https://github.com/elementary/code/commit/1e321b4153d8e9746f97600a70c854d25c46b23c)
- [ ] [<code>Check commandline files, do not allow docs with null file (#1129)</code>](https://github.com/elementary/code/commit/ae3e081e38bd055f50f48e52761b106466e5a1ab)
- [ ] [<code>SearchBar: Make the search count translatable (#1182)</code>](https://github.com/elementary/code/commit/ae319e69b59fd578e17493a02384e5892f828e24)
- [ ] [<code>Release 6.2.0 (#1181)</code>](https://github.com/elementary/code/commit/a580f6b6b0c7963333dd472f6ee9da2a7c602449) <sub>Tagged: <code>6.2.0</code></sub>

**Comment by bobby285271** [comment]
@ofborg test pantheon

**Comment by davidak** [comment]
Result of `nixpkgs-review pr 167265` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>pantheon.elementary-code</li>
  </ul>
</details>

**Review by davidak — APPROVED** [review]
Change looks good

Builds, works

**Pull request merged**
