### PR TITLE
rustc: 1.36.0 -> 1.37.0

### PR DESCRIPTION
**Pull request by edolstra**
###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
I get the following build when building rustc on x86_64-linux:

https://gist.github.com/Mic92/be9139d06dfd446996bd74ceb52bdce0

Note that I also rebased to latest staging before.

**Comment by edolstra** [comment]
@Mic92 Ah thanks, I made this PR on master which doesn't have the profiler changes yet.

**Comment by edolstra** [comment]
@Mic92 Should work now.

**Comment by edolstra** [comment]
Merging since the ofborg failures are timeouts or unrelated.

**Pull request merged**
