### PR TITLE
python3Packages.skorch: 0.11.0 -> 0.12.1; unbreak

### PR DESCRIPTION
**Pull request by bcdarwin**
###### Description of changes

Update and unbreak package.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mattmelling** [comment]
Result of `nixpkgs-review pr 205724` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python310Packages.skorch</li>
    <li>python39Packages.skorch</li>
  </ul>
</details>

**Comment by mattmelling** [comment]
Builds fine (see above), but fails when I try to import the package:

```
~/.cache/nixpkgs-review/pr-205724-1/results/python310Packages.skorch/lib/python3.10/site-packages$ python -m skorch
Traceback (most recent call last):
  File "/nix/store/kph267nv0zvbgsgsvkz2a4ic5mgzc4cw-python3.9-numpy-1.23.3/lib/python3.9/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/nix/store/kph267nv0zvbgsgsvkz2a4ic5mgzc4cw-python3.9-numpy-1.23.3/lib/python3.9/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/nix/store/kph267nv0zvbgsgsvkz2a4ic5mgzc4cw-python3.9-numpy-1.23.3/lib/python3.9/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/nzgqxw4d875pgl1lji8n3q82x3bf7ldi-python3-3.10.8/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/nix/store/nzgqxw4d875pgl1lji8n3q82x3bf7ldi-python3-3.10.8/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/nix/store/nzgqxw4d875pgl1lji8n3q82x3bf7ldi-python3-3.10.8/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/nix/store/932p8zd4sw2m0k2lb49z953wgps77aqn-python3.10-skorch-0.12.1/lib/python3.10/site-packages/skorch/__init__.py", line 9, in <module>
    from .history import History
  File "/nix/store/932p8zd4sw2m0k2lb49z953wgps77aqn-python3.10-skorch-0.12.1/lib/python3.10/site-packages/skorch/history.py", line 5, in <module>
    from skorch.utils import open_file_like
  File "/nix/store/932p8zd4sw2m0k2lb49z953wgps77aqn-python3.10-skorch-0.12.1/lib/python3.10/site-packages/skorch/utils.py", line 16, in <module>
    import numpy as np
  File "/nix/store/kph267nv0zvbgsgsvkz2a4ic5mgzc4cw-python3.9-numpy-1.23.3/lib/python3.9/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/nix/store/kph267nv0zvbgsgsvkz2a4ic5mgzc4cw-python3.9-numpy-1.23.3/lib/python3.9/site-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/nix/store/nzgqxw4d875pgl1lji8n3q82x3bf7ldi-python3-3.10.8/bin/python"
  * The NumPy version is: "1.23.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
```

**Comment by bcdarwin** [comment]
This is a known issue importing Python packages inside the nixpkgs-review
shell which has built both Python 3.9 and 3.10 packages.

**Comment by bcdarwin** [comment]
Anyway, I've added the appropriate `pythonImportsCheck`.

**Review by mattmelling — APPROVED** [review]

**Pull request merged**
