### PR TITLE
cogl: 1.22.0 -> 1.22.2, enable wayland support

### PR DESCRIPTION
**Pull request by groxxda**
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @lovek323

### CODE REVIEW

**Comment by lethalman** [comment]
I would be more comfortable if we had a `config.wayland` flag in nixpkgs. You can look for `config.pulseaudio` as an example.

**Comment by groxxda** [comment]
@lethalman what should be the default for that flag?


having independent paths for wayland and x would be awesome though... (i. e. if you choose wayland, you get for example mesa without x, etc)

**Comment by lethalman** [comment]
@groxxda yeah but let's start with wayland first :) We can use true as default just fine for me.

**Comment by groxxda** [comment]
Okay I'll look into that, should be relatively straight forward.

**Comment by groxxda** [comment]
Merged into master with gnome3.22 in https://github.com/NixOS/nixpkgs/commit/e56832d7301f2be7c18abf12d151db00be88f6fa

**Pull request closed without merging**
