### PR TITLE
vim-plugins: add 13 plugins

### PR DESCRIPTION
**Pull request by ndarwincorn**
###### Motivation for this change

Migrated my init.nvim to nix/home-manager and realized how many of the plugins I use are missing.

###### Things done

Ran the following command: `update.py --add "dmix/elvish.vim" ... --add "yuki-ycino/ncm2-dictionary"`

Added overrides for dependencies for `ncm2-neoinclude`, `ncm2-neosnippet`, `ncm2-syntax`.

Built/installed them by sourcing my local nixpkgs repo.

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by typetetris — COMMENTED** [review]
[x] versions in commit messages match generated file
[x] all new plugins have MIT license except `vim-packer` and `vim-vagrant` which have ISC License

**Comment by typetetris** [comment]
Result of `nixpkgs-review pr 93449` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
<br>- vimPlugins.YouCompleteMe
</details>
<details>
  <summary>71 packages built:</summary>
<br>- vimPlugins.ale
<br>- vimPlugins.ansible-vim
<br>- vimPlugins.calendar-vim
<br>- vimPlugins.coc-go
<br>- vimPlugins.coc-nvim
<br>- vimPlugins.completion-nvim
<br>- vimPlugins.conjure
<br>- vimPlugins.csv-vim
<br>- vimPlugins.defx-nvim
<br>- vimPlugins.denite-nvim
<br>- vimPlugins.deol-nvim
<br>- vimPlugins.deoplete-fish
<br>- vimPlugins.deoplete-khard
<br>- vimPlugins.deoplete-lsp
<br>- vimPlugins.deoplete-nvim
<br>- vimPlugins.dhall-vim
<br>- vimPlugins.elvish-vim
<br>- vimPlugins.iceberg-vim
<br>- vimPlugins.jedi-vim
<br>- vimPlugins.kotlin-vim
<br>- vimPlugins.lh-vim-lib
<br>- vimPlugins.lightline-vim
<br>- vimPlugins.ncm2-cssomni
<br>- vimPlugins.ncm2-dictionary
<br>- vimPlugins.ncm2-github
<br>- vimPlugins.ncm2-html-subscope
<br>- vimPlugins.ncm2-markdown-subscope
<br>- vimPlugins.ncm2-neoinclude
<br>- vimPlugins.ncm2-neosnippet
<br>- vimPlugins.ncm2-syntax
<br>- vimPlugins.ncm2-tagprefix
<br>- vimPlugins.ncm2-vim
<br>- vimPlugins.neoformat
<br>- vimPlugins.neomake
<br>- vimPlugins.neosnippet-vim
<br>- vimPlugins.nerdtree
<br>- vimPlugins.neuron-vim
<br>- vimPlugins.nvim-lsp
<br>- vimPlugins.nvim-treesitter
<br>- vimPlugins.onedark-vim
<br>- vimPlugins.open-browser-github-vim
<br>- vimPlugins.splitjoin-vim
<br>- vimPlugins.traces-vim
<br>- vimPlugins.vim
<br>- vimPlugins.vim-airline
<br>- vimPlugins.vim-dasht
<br>- vimPlugins.vim-flutter
<br>- vimPlugins.vim-go
<br>- vimPlugins.vim-grepper
<br>- vimPlugins.vim-isort
<br>- vimPlugins.vim-jsx-typescript
<br>- vimPlugins.vim-lion
<br>- vimPlugins.vim-lsc
<br>- vimPlugins.vim-markdown
<br>- vimPlugins.vim-move
<br>- vimPlugins.vim-orgmode
<br>- vimPlugins.vim-packer
<br>- vimPlugins.vim-pandoc
<br>- vimPlugins.vim-ruby
<br>- vimPlugins.vim-sandwich
<br>- vimPlugins.vim-snippets
<br>- vimPlugins.vim-terraform
<br>- vimPlugins.vim-terraform-completion
<br>- vimPlugins.vim-test
<br>- vimPlugins.vim-vagrant
<br>- vimPlugins.vim-which-key
<br>- vimPlugins.vimfiler-vim
<br>- vimPlugins.vimtex
<br>- vimPlugins.vista-vim
<br>- vimPlugins.yats-vim
<br>- vimPlugins.zig-vim
</details>

**Comment by typetetris** [comment]
Doesn't seem to be this pull requests fault:
```
builder for '/nix/store/6rb7gicz0chyxw26q3w7r6ff6bkvy8ya-racerd-unstable-2019-09-02.drv' failed with exit code 101; last 10 log lines:
     |                                                           ^^

  error: aborting due to 3 previous errors

  For more information about this error, try `rustc --explain E0061`.
  error: could not compile `rustc-ap-rustc_data_structures`.

  To learn more, run the command again with --verbose.
  warning: build failed, waiting for other jobs to finish...
  error: build failed
cannot build derivation '/nix/store/0mp6w4xh9c22bj5xp7q688m5vgwc24bc-ycmd-2020-02-22.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/dhymwgknb0iwyw5533a53hwjp4a2a6gy-vimplugin-YouCompleteMe-2020-07-15.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/fydi7fk9gzmf5q314d58g5rmmkx43bsk-env.drv': 1 dependencies couldn't be built
[0 built (1 failed)]
```

**Comment by ndarwincorn** [comment]
@typetetris - confirmed, this is the version of YCM in `generated.nix` prior to my update:

```
warning: ignoring the user-specified setting 'sandbox', because it is a restricted setting and you are not a trusted user
builder for '/nix/store/6rb7gicz0chyxw26q3w7r6ff6bkvy8ya-racerd-unstable-2019-09-02.drv' failed with exit code 101; last 10 log lines:
     |                                                           ^^
  
  error: aborting due to 3 previous errors
  
  For more information about this error, try `rustc --explain E0061`.
  error: could not compile `rustc-ap-rustc_data_structures`.
  
  To learn more, run the command again with --verbose.
  warning: build failed, waiting for other jobs to finish...
  error: build failed
cannot build derivation '/nix/store/0mp6w4xh9c22bj5xp7q688m5vgwc24bc-ycmd-2020-02-22.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/h3wryjpdjaza7jvah581qy8s0yifsxqg-vimplugin-YouCompleteMe-2020-07-07.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/nqssandmm5fw4rscf58d5k0x4ayrjqmk-env.drv': 1 dependencies couldn't be built
```

**Pull request merged**
