### PR TITLE
qtdeclarative: revert "Patch for scrollbar regression"

### LINKED ISSUE #96159: qtquickcontrols is blocking channels
qtquickcontrols failure is blocking KDE https://hydra.nixos.org/build/125404486. cc @petabyteboy @ttuegel

### PR DESCRIPTION
**Pull request by peti**
This reverts commit 5530043208f0bef7. The change breaks the build of
qtquickcontrols. Fixes https://github.com/NixOS/nixpkgs/issues/96159.

### CODE REVIEW

**Comment by peti** [comment]
@GrahamcOfBorg build qt5.qtquickcontrols

**Review by ghost — APPROVED** [review]

**Comment by petabyteboy** [comment]
Thanks for discovering that this patch broke the build! But did you maybe push the picard update to the same branch on accident?

**Review by ghost — APPROVED** [review]

**Review by vcunat — APPROVED** [review]
Builds for me.  A visual fix doesn't seem worth the regression, though perhaps someone would be able to resolve it (later) in a better way than dropping the patch.

EDIT: the `picard` change seems non-controversial, so it shouldn't block merging.

**Comment by peti** [comment]
Oops, yes, I pushed that Picard update here by mistake. Will fix that in a second... The patch is in master already anyway.

**Comment by peti** [comment]
Ah, you were faster. Thanks a lot for merging. I'm glad `master` builds for me again.

**Pull request merged**
