### PR TITLE
minecraft: update launcher - WIP

### PR DESCRIPTION
**Pull request by cpages**
The minecraft launcher is about to be updated, as advertised [here](https://www.reddit.com/r/Minecraft/comments/5opl31/help_us_test_the_new_minecraft_launcher_now_with).

I cannot fully test this since I'm getting an 'Illegal instruction' error (time to get a new machine I guess :)

The icon is missing again for now, since we don't have the jar.

### CODE REVIEW

**Comment by ryantm** [comment]
Cool. I'll try to take a look at this this weekend. Let's get the icon working before merging this!

**Comment by ryantm** [comment]
I also get the "Illegal Instruction" error. Also, they've updated Minecraft_staging.tar.gz in-place and the new has is currently: 06yx7rcq4yl5ds2ccav8rqg6kv6dfy4zbgifzvgpf8cqn1rk3a0a

Error:

```
ryantm@laptop1 ~/p/nixpkgs (minecraft)$ minecraft
/nix/store/42yhvsr19z9rx3cgflja25gyjzk6syf6-minecraft-2.0.759/share/minecraft/.launcher-wrapped: unrecognized option '--type=zygote'
/nix/store/42yhvsr19z9rx3cgflja25gyjzk6syf6-minecraft-2.0.759/share/minecraft/.launcher-wrapped: unrecognized option '--no-sandbox'
/nix/store/42yhvsr19z9rx3cgflja25gyjzk6syf6-minecraft-2.0.759/share/minecraft/.launcher-wrapped: unrecognized option '--lang=en-US'
Illegal instruction
ryantm@laptop1 ~/p/nixpkgs (minecraft)$ /proc/self/exe: unrecognized option '--type=gpu-process'
/proc/self/exe: unrecognized option '--no-sandbox'
/proc/self/exe: unrecognized option '--window-depth=24'
```

**Comment by ryantm** [comment]
Here is the AUR package for inspiration: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=minecraft-launcher

**Comment by c0bw3b** [comment]
(triage) Is this still a being looked after?

**Comment by cpages** [comment]
The current installer still works, so let's just close it and I'll try to retake this if needed

**Comment by nathantalewis** [comment]
@cpages, I tried these changes with the latest version of the new launcher (with a few tweaks since there is no `.sh` file anymore) and I think I'm getting the same illegal instruction error.

The workaround of using the old launcher doesn't work with forge to get mods. Any chance you could open this PR again so we can start using the new launcher?

**Comment by cpages** [comment]
@nathantalewis it's been a while that I don't even play it, so it's low on my priority list, but I'll reopen in case I manage some progress

**Comment by nathantalewis** [comment]
@cpages, I was able to find a workaround that allowed me to use the old launcher with forge. It turns out there was an empty string in a url field of the forge version json file. I just added the correct url for the version I was using at everything was happy.

**Pull request closed without merging**
