### PR TITLE
nixos/localtimed: hopefully fix geoclue

### PR DESCRIPTION
**Pull request by lovesegfault**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
The module rename shouldn't have been done without adding a `mkRenamedOptionModule`, as things stand this creates a lot of unnecessary breakage for users that requires them to dig through the options list just to find out that they need to add one measly ‘d’.

**Comment by lovesegfault** [comment]
> The module rename shouldn't have been done without adding a `mkRenamedOptionModule`, as things stand this creates a lot of unnecessary breakage for users that requires them to dig through the options list just to find out that they need to add one measly ‘d’.

You're right, sorry for missing that!

**Comment by dschrempf** [comment]
Not sure if this is related, but after updating, and adding the bespoken `d` :-), the localtime service fails to start with
```
Jun 08 15:25:15 schwarzbaer systemd[1]: Started Timezone Updater Daemon.
Jun 08 15:25:20 schwarzbaer localtimed[991]: 2022/06/08 15:25:20 Failed to start GeoClue2 Client: 'localtimed' disallowed, no agent for UID 62714
Jun 08 15:25:20 schwarzbaer systemd[1]: localtime.service: Main process exited, code=exited, status=1/FAILURE
Jun 08 15:25:20 schwarzbaer systemd[1]: localtime.service: Failed with result 'exit-code
```

The reason may be that I am using
```
  services.geoclue2.enable = true;
```
in my system configuration, and
```
  services.redshift.enable = true;
  services.redshift.provider = "geoclue2";
```
in my user configuration with Home Manager.

**Comment by lovesegfault** [comment]
@dschrempf They removed the agent because it was buggy.

We have to either:
1. Figure out how to disable agents for geoclue, which would mean any application can query your location.

or

2. Figure out how to run a geoclue agent for the `localtime` user.

**Comment by dschrempf** [comment]
Hm OK, I do understand. Does this mean that both services, `geoclue2` and `localtimed` are not expected to work together, or that they only do not work in conjunction with Home Manager? In the former case, we should open an issue here at Nixpkgs, in the latter, we may want to report the issue to the Home Manager developers.

**Pull request merged**
