### PR TITLE
restinio: init at 0.6.8.1

### PR DESCRIPTION
**Pull request by doronbehar**
##### Motivation for this change

In my quest to package [Jami](https://jami.net/), also requested at #83411 I learned that this is a dependency of several components of the project.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by dasj19 — COMMENTED** [review]
Builds well with `nix-shell -p nixpkgs-review --run "nixpkgs-review pr 94460"`. I don't know how to make use of this library though...

**Comment by doronbehar** [comment]
Thanks for testing, but now I noticed I forgot to commit the all-packages.nix line addition, which means nixpkgs-review probably hasn't built anything for you :/.

**Comment by doronbehar** [comment]
The last push is an attempt to make the build succeed on Darwin, not like the latest: https://github.com/NixOS/nixpkgs/pull/94460/checks?check_run_id=937777778

**Comment by doronbehar** [comment]
Can't fix the Darwin build, marking it as broken for Darwin.

**Comment by bqv** [comment]
Maybe opt in marvin?

**Comment by doronbehar** [comment]
> Maybe opt in marvin?

TBH I'm not prioritizing this, as I didn't manage to eventually get jami working with this package, it may be worth testing again now.

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 94460` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>restinio</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 94460` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>restinio</li>
  </ul>
</details>

**Comment by doronbehar** [comment]
I will not attempt to package jami in the near future, so this PR has no use. Of course anyone is free to pick up the work I did here and / or in https://github.com/doronbehar/nixpkgs/blob/package-jami-dirty/pkgs/applications/networking/instant-messengers/jami/default.nix (branch `package-jami-dirty`).

**Comment by bqv** [comment]
I have been using guix for jami instead, quite successfully.

**Pull request closed without merging**
