### PR TITLE
homeassistant: 0.113.0 -> 0.113.3

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

https://github.com/home-assistant/core/releases/tag/0.113.1
https://github.com/home-assistant/core/releases/tag/0.113.2
https://github.com/home-assistant/core/releases/tag/0.113.3

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

@GrahamcOfBorg test home-assistant

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build homeassistant

**Comment by Mic92** [comment]
I am currently seeing this test error:

**Comment by Mic92** [comment]
[log.txt](https://github.com/NixOS/nixpkgs/files/5011683/log.txt)

**Comment by Mic92** [comment]
@GrahamcOfBorg build home-assistant

**Comment by Mic92** [comment]
I also tried to rebase this on upstream/master but it seems to be still a problem. Not sure why this is not triggered here.

**Comment by Mic92** [comment]
Mhm. Now it seems to work for me as well? Maybe its a flacky test?

**Comment by mweinelt** [comment]
Indeed is flaky, I didn't run into this issue when I first ran the test, now I do.

The test was introduced in 0.113.2: https://github.com/home-assistant/core/pull/38311

**Comment by mweinelt** [comment]
The timeout given here is a bit too tight:

```patch
diff --git a/tests/test_core.py b/tests/test_core.py
index 12ed00fde2..877eac226a 100644
--- a/tests/test_core.py
+++ b/tests/test_core.py
@@ -1447,7 +1447,7 @@ async def test_chained_logging_hits_log_timeout(hass, caplog):
             return
         hass.async_create_task(_task_chain_1())
 
-    with patch.object(ha, "BLOCK_LOG_TIMEOUT", 0.0001):
+    with patch.object(ha, "BLOCK_LOG_TIMEOUT", 0.001):
         hass.async_create_task(_task_chain_1())
         await hass.async_block_till_done()
 ```

I'll raise this issue upstream.

**Comment by Mic92** [comment]
Ok. We can apply the pull request patch.

**Comment by mweinelt** [comment]
Spoke too quick, that doesn't fix it for me.

**Comment by mweinelt** [comment]
Upstream issue https://github.com/home-assistant/core/issues/38476

**Comment by mweinelt** [comment]
> Ok. We can apply the pull request patch.

Done.

**Pull request merged**
