### PR TITLE
cypthon: moduralize so it can be called with other versions

### PR DESCRIPTION
**Pull request by domenkozar**
This allows passing in `hash` and `url` of any Python to build it, while not changing the output hashes.

### CODE REVIEW

**Comment by FRidh** [comment]
Any specific use case you have in mind? What not override `src`?

**Comment by domenkozar** [comment]
This PR doesn't change the interface, because you still need to set `sourceVersion` regardless.

I'm working on nixpkgs-python that will build all versions of Python.

**Comment by domenkozar** [comment]
@FRidh I've used the `src` override approach, but moved the dynamicly-produced patch as an input.

**Comment by domenkozar** [comment]
I've released https://github.com/cachix/nixpkgs-python that relies on this PR.

**Pull request merged**
