### PR TITLE
ungoogled-chromium: 113.0.5672.126 -> 114.0.5735.90

### PR DESCRIPTION
**Pull request by networkException**
###### Description of changes

Fixes incorrect warnings when using chromiumVersionAtLeast.

Same underlying changes as #235169

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by michaeladler — COMMENTED** [review]
I'm not sure I fully understood the issue with warn obsolete, but fwiw, I can confirm that ungoogled-chromium 114.0.5735.90 works.

**Comment by networkException** [comment]
It took me a while to understand what that code does but essentially its supposed to warn when there's an optional patch defined for a version that no package is affected by anymore

The same warning was wrongly used for releases newer than a certain version, there it's not really possible to have that warning

**Comment by networkException** [comment]
Should this also be backported to 22.11?

**Comment by michaeladler** [comment]
> The same warning was wrongly used for releases newer than a certain version, there it's not really possible to have that warning

Gotcha, that was the piece of information I was looking for (might be worth putting it into the commit message). Thanks!

> Should this also be backported to 22.11?

Yeah I guess since https://github.com/NixOS/nixpkgs/pull/235169 was backported to 22.11 this should as well.

**Comment by michaeladler** [comment]
Now I experienced the warning myself:

> trace: warning: chromium: ungoogled version 114.0.5735.90 is newer than a conditional bounded at 114. You can safely delete it.

This got me thinking... with your change, the warning will just be gone, right? The proper solution is to remove the version checks from the nix expressions though, e.g.

```
lib.optionals (chromiumVersionAtLeast "114") [
      libevdev
 ]
```

can be simplified to `[ libevdev ]` (and even moved up into the previous list). ungoogled-chromium is (almost) always the last chromium derivate which receives an update, so I think the check makes sense to make us aware of such bounds.

**Comment by networkException** [comment]
hm I only really though about chromiumVersionAtLeast as a versionRange with no upper bound that would eventually be converted to a versionRange, in which case we would probably want to keep some indiciation of the lower bound.

But you're right, I'll see if I can improve the warning message and comments and remove the conditionals

**Comment by primeos** [comment]
> The proper solution is to remove the version checks from the nix expressions though, e.g.

Yes, the purpose of those warnings is for us to know when to remove old conditionals that aren't required anymore. The warning basically means to remove the conditional but keep the code (i.e., make it unconditional), e.g.:
```
trace: warning: chromium: ungoogled version 114.0.5735.90 is newer than a conditional bounded at 114. You can safely delete it.
```

I've taken the liberty to update your PR accordingly since we should merge this ASAP due to the security fixes.

> But you're right, I'll see if I can improve the warning message and comments and remove the conditionals

Feel free to open a dedicated PR for this. Version bumps should have no other changes to make reviewing, merging, backporting, etc. faster/easier. Thanks :)

**Pull request merged**
