### PR TITLE
openssl: cherry-pick upstream fix for for mips64*-linux-*abin32

### PR DESCRIPTION
**Pull request by ghost**
###### Description of changes

This cherry-picks a fix for mips64*-linux-*abin32 which is [merged upstream](https://github.com/openssl/openssl/pull/19320#issuecomment-1264776731) as:

- https://github.com/openssl/openssl/commit/01b533540a555fc3a9eee4957c3feec1168cd709 in openssl-1.1.1
- https://github.com/openssl/openssl/commit/9f0867da4cbf77ed642717b5e703e09ab2c087a0 in openssl-3.0

###### Things done

- Built on platform(s)
  - [x] mips64-linux-gnuabin32
- [x] Tested compilation of a package that depends on this change: `curl`
- [x] Tested basic functionality of `curl`
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by amjoseph-nixpkgs** [comment]
Can anybody explain why ofborg says this?

>  added the 10.rebuild-darwin-stdenv label

It's been five or six years since I owned any Darwin hardware.

**Comment by ajs124** [comment]
This will probably be part of OpenSSL 3.0.7 due next Tuesday (https://www.openwall.com/lists/oss-security/2022/10/25/4), right?

Idk if they'll also do a 1.1.1 release then.

**Comment by amjoseph-nixpkgs** [comment]
> This will probably be part of OpenSSL 3.0.7 due next Tuesday (https://www.openwall.com/lists/oss-security/2022/10/25/4), right?

Unfortunately my time machine is in the shop for repairs, so I am unable to answer your question ;)

**Comment by vcunat** [comment]
Yes, current `staging` has this line fixed in both openssl versions.

**Pull request closed without merging**
