### PR TITLE
staging-next 2024-05-31

### PR DESCRIPTION
**Pull request by vcunat**
This is the first staging-next iteration that will **not** reach 24.05.  (But there are `staging*-24.05`, as usual.)

##### Helpful links

- workflow docs: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#staging
- important jobs:
  https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents
  https://hydra.nixos.org/job/nixos/staging-next-small/tested
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next
  https://hydra.nixos.org/jobset/nixos/staging-next-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/312133
##### Mass breakages
- [x] chromium [see below](#issuecomment-2156324180)

### CODE REVIEW

**Comment by vcunat** [comment]
- [ ] python3Packages.pydantic fails to build
  - both pythons, probably all platforms
  - blocks thousands of reverse dependencies
  - https://hydra.nixos.org/build/261955766

**Comment by vcunat** [comment]
- [ ] electron on *-linux [fails](https://hydra.nixos.org/build/262441504) with
  ```
  ld.lld: error: Invalid record (Producer: 'LLVM18.1.7' Reader: 'LLVM 17.0.6')
  ```
- [ ] chromium on *-linux [fails](https://hydra.nixos.org/build/262492726) with
  ```
  FAILED: obj/chrome/browser/devtools/devtools/devtools_window.o
  In file included from ../../chrome/browser/devtools/devtools_window.cc:32:
  ../../chrome/browser/file_select_helper.h:16:10: fatal error: 'components/enterprise/buildflags/buildflags.h' file not found
   16 | #include "components/enterprise/buildflags/buildflags.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ```

**Comment by doronbehar** [comment]
@vcunat would it be OK to push to `staging-next` a `python3.pkgs.matplotlib` version bump? It will trigger ~6700 rebuilds according to the ofborg evaluation at https://github.com/NixOS/nixpkgs/pull/316041 .

**Comment by vcunat** [comment]
@doronbehar: unless it's focused on fixing breakages, I wouldn't add it.

**Comment by vcunat** [comment]
The [broken chromium](#issuecomment-2156324180) is quite a problem, I think.  /cc maintainers: @networkException, @emilylange.

**Comment by vcunat** [comment]
- [ ] `swift` is broken on *-darwin, probably due to LLVM upgrade
  https://hydra.nixos.org/build/262150427
  Maintainers: @dtzWill, @trepetti, @dduan, @Trundle, @stephank

**Pull request merged**
