### PR TITLE
libgit2: 1.4.3 -> 1.5.0

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Description of changes

https://github.com/libgit2/libgit2/releases/tag/v1.4.4
https://github.com/libgit2/libgit2/releases/tag/v1.5.0
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
`nixpkgs-review` happy, macos 10.15

**Comment by SuperSandro2000** [comment]
TODO:
- [ ] pin python310Packages.pygit2 to libgit2 1.4.X

**Comment by SuperSandro2000** [comment]
Result of nixpkgs-review pr 181358 run on x86_64-linux 1

<details>
<summary>
102 packages marked as broken and skipped:
</summary>
<ul>
<li>akregator</li>
<li>dolphin</li>
<li>dragon</li>
<li>jucipp</li>
<li>julia</li>
<li>kate</li>
<li>kde-cli-tools</li>
<li>kdeplasma-addons</li>
<li>kdev-php</li>
<li>kdev-python</li>
<li>kdevelop</li>
<li>kdevelop-unwrapped</li>
<li>kexi</li>
<li>kig</li>
<li>kinfocenter</li>
<li>kmail</li>
<li>kmenuedit</li>
<li>kompare</li>
<li>krohnkite</li>
<li>ktouch</li>
<li>kwin-dynamic-workspaces</li>
<li>kwin-tiling</li>
<li>libsForQt512.akregator</li>
<li>libsForQt512.bismuth</li>
<li>libsForQt512.dolphin</li>
<li>libsForQt512.dolphin-plugins</li>
<li>libsForQt512.dragon</li>
<li>libsForQt512.kate</li>
<li>libsForQt512.kde-cli-tools</li>
<li>libsForQt512.kdepim-addons</li>
<li>libsForQt512.kdeplasma-addons</li>
<li>libsForQt512.kdev-php</li>
<li>libsForQt512.kdev-python</li>
<li>libsForQt512.kdevelop</li>
<li>libsForQt512.kdevelop-unwrapped</li>
<li>libsForQt512.khotkeys</li>
<li>libsForQt512.kig</li>
<li>libsForQt512.kinfocenter</li>
<li>libsForQt512.kmail</li>
<li>libsForQt512.kmail-account-wizard</li>
<li>libsForQt512.kmenuedit</li>
<li>libsForQt512.kompare</li>
<li>libsForQt512.krohnkite</li>
<li>libsForQt512.ktexteditor</li>
<li>libsForQt512.ktouch</li>
<li>libsForQt512.kwin-dynamic-workspaces</li>
<li>libsForQt512.kwin-tiling</li>
<li>libsForQt512.parachute</li>
<li>libsForQt512.pim-data-exporter</li>
<li>libsForQt512.plasma-browser-integration</li>
<li>libsForQt512.plasma-desktop</li>
<li>libsForQt512.plasma-disks</li>
<li>libsForQt512.plasma-mobile</li>
<li>libsForQt512.plasma-sdk</li>
<li>libsForQt512.plasma-workspace</li>
<li>libsForQt512.powerdevil</li>
<li>libsForQt512.rocs</li>
<li>libsForQt512.systemsettings</li>
<li>libsForQt514.akregator</li>
<li>libsForQt514.bismuth</li>
<li>libsForQt514.dolphin</li>
<li>libsForQt514.dolphin-plugins</li>
<li>libsForQt514.dragon</li>
<li>libsForQt514.kate</li>
<li>libsForQt514.kde-cli-tools</li>
<li>libsForQt514.kdepim-addons</li>
<li>libsForQt514.kdeplasma-addons</li>
<li>libsForQt514.kdev-php</li>
<li>libsForQt514.kdev-python</li>
<li>libsForQt514.kdevelop</li>
<li>libsForQt514.kdevelop-unwrapped</li>
<li>libsForQt514.khotkeys</li>
<li>libsForQt514.kig</li>
<li>libsForQt514.kinfocenter</li>
<li>libsForQt514.kmail</li>
<li>libsForQt514.kmail-account-wizard</li>
<li>libsForQt514.kmenuedit</li>
<li>libsForQt514.kompare</li>
<li>libsForQt514.krohnkite</li>
<li>libsForQt514.ktexteditor</li>
<li>libsForQt514.ktouch</li>
<li>libsForQt514.kwin-dynamic-workspaces</li>
<li>libsForQt514.kwin-tiling</li>
<li>libsForQt514.parachute</li>
<li>libsForQt514.pim-data-exporter</li>
<li>libsForQt514.plasma-browser-integration</li>
<li>libsForQt514.plasma-desktop</li>
<li>libsForQt514.plasma-disks</li>
<li>libsForQt514.plasma-mobile</li>
<li>libsForQt514.plasma-sdk</li>
<li>libsForQt514.plasma-workspace</li>
<li>libsForQt514.powerdevil</li>
<li>libsForQt514.rocs</li>
<li>libsForQt514.systemsettings</li>
<li>plasma-browser-integration</li>
<li>plasma-desktop</li>
<li>plasma-mobile</li>
<li>plasma-workspace</li>
<li>powerdevil</li>
<li>ring-daemon</li>
<li>swift</li>
<li>systemsettings</li>
</ul>
</details>
<details>
<summary>
93 packages built:
</summary>
<ul>
<li>amarok</li>
<li>amp</li>
<li>broot</li>
<li>calligra</li>
<li>cargo-raze</li>
<li>cargo-update</li>
<li>dvc</li>
<li>dvc-with-remotes</li>
<li>fritzing</li>
<li>git-annex-metadata-gui</li>
<li>git-series</li>
<li>gitfs</li>
<li>gitg</li>
<li>gitless</li>
<li>gitstatus</li>
<li>gnome-builder</li>
<li>gnuastro</li>
<li>guile-git</li>
<li>horizon-eda</li>
<li>jami-client-qt</li>
<li>jami-daemon</li>
<li>jami-libclient</li>
<li>kbibtex</li>
<li>kile</li>
<li>kup</li>
<li>l2md</li>
<li>libgit2</li>
<li>libgit2-glib</li>
<li>libsForQt5.akregator</li>
<li>libsForQt5.bismuth</li>
<li>libsForQt5.dolphin</li>
<li>libsForQt5.dolphin-plugins</li>
<li>libsForQt5.dragon</li>
<li>libsForQt5.kate</li>
<li>libsForQt5.kde-cli-tools</li>
<li>libsForQt5.kdepim-addons</li>
<li>libsForQt5.kdeplasma-addons</li>
<li>libsForQt5.kdev-php</li>
<li>libsForQt5.kdev-python</li>
<li>libsForQt5.kdevelop</li>
<li>libsForQt5.kdevelop-unwrapped</li>
<li>libsForQt5.khotkeys</li>
<li>libsForQt5.kig</li>
<li>libsForQt5.kinfocenter</li>
<li>libsForQt5.kmail</li>
<li>libsForQt5.kmail-account-wizard</li>
<li>libsForQt5.kmenuedit</li>
<li>libsForQt5.kompare</li>
<li>libsForQt5.krohnkite</li>
<li>libsForQt5.ktexteditor</li>
<li>libsForQt5.ktouch</li>
<li>libsForQt5.kwin-dynamic-workspaces</li>
<li>libsForQt5.kwin-tiling</li>
<li>libsForQt5.parachute</li>
<li>libsForQt5.pim-data-exporter</li>
<li>libsForQt5.plasma-browser-integration</li>
<li>libsForQt5.plasma-desktop</li>
<li>libsForQt5.plasma-disks</li>
<li>libsForQt5.plasma-mobile</li>
<li>libsForQt5.plasma-sdk</li>
<li>libsForQt5.plasma-workspace</li>
<li>libsForQt5.powerdevil</li>
<li>libsForQt5.rocs</li>
<li>libsForQt5.systemsettings</li>
<li>lightly-qt</li>
<li>mercurialFull</li>
<li>pantheon-tweaks</li>
<li>pantheon.elementary-code</li>
<li>pantheon.elementary-files</li>
<li>pharo</li>
<li>pharo-launcher</li>
<li>pharo-spur32</li>
<li>pharo-spur64</li>
<li>pijul</li>
<li>powerline (python310Packages.powerline)</li>
<li>powerline-rs</li>
<li>public-inbox</li>
<li>python310Packages.git-annex-adapter</li>
<li>python310Packages.pygit2</li>
<li>python310Packages.scmrepo</li>
<li>python39Packages.git-annex-adapter</li>
<li>python39Packages.powerline</li>
<li>python39Packages.pygit2</li>
<li>python39Packages.scmrepo</li>
<li>sourcehut.gitsrht</li>
<li>sourcehut.listssrht</li>
<li>sourcehut.mansrht</li>
<li>stagit</li>
<li>starship</li>
<li>subsurface</li>
<li>vala-language-server</li>
<li>wacomtablet</li>
<li>zsh-powerlevel10k</li>
</ul>
</details>

**Comment by risicle** [comment]
`nixpkgs-review` happy, macos 10.15

**Pull request merged**
