### PR TITLE
linux: enable LIRC

### PR DESCRIPTION
**Pull request by misuzu**
###### Motivation for this change
Right now you have to [recompile the kernel](https://nixos.wiki/wiki/LIRC) to use infrared remote control.
Enabled on [Arch Linux](https://git.archlinux.org/svntogit/packages.git/tree/trunk/config?h=packages/linux#n5345).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by symphorien** [comment]
@GrahamcOfBorg build linux

**Comment by symphorien** [comment]
@GrahamcOfBorg build linux_4_4 linux_latest

**Comment by symphorien** [comment]
Apparently this breaks linux_4_4:

```
GOT: CONFIG_LIRC:
GOT:
GOT: Enable this option to build the Linux Infrared Remote
GOT: Control (LIRC) core device interface driver. The LIRC
GOT: interface passes raw IR to and from userspace, where the
GOT: LIRC daemon handles protocol decoding for IR reception and
GOT: encoding for IR transmitting (aka "blasting").
GOT:
GOT: Symbol: LIRC [=n]
GOT: Type  : tristate
GOT: Prompt: LIRC interface driver
GOT:   Location:
GOT:     -> Device Drivers
GOT:       -> Multimedia support (MEDIA_SUPPORT [=m])
GOT:         -> Remote controller decoders (RC_DECODERS [=y])
GOT:   Defined at drivers/media/rc/Kconfig:15
GOT:   Depends on: MEDIA_SUPPORT [=m] && RC_DECODERS [=y] && RC_CORE [=m]
GOT:
GOT:
GOT:
QUESTION:     LIRC interface driver, NAME: LIRC, ALTS: N/m/?, ANSWER: y
repeated question:     LIRC interface driver at /nix/store/i08cwnb49a77dzcimwxm8lhynvq6qm9r-generate-config.pl line 87.

Error in reading or end of file.
```

**Comment by misuzu** [comment]
Should be fixed now. LIRC is broken on 4.16: https://forums.gentoo.org/viewtopic-t-1079866-start-0.html

@GrahamcOfBorg build linux_4_4 linux_latest

**Pull request merged**
