### PR TITLE
gpu-burn: unstable-2023-11-10 -> unstable-2024-04-09; update CUDA packaging

### PR DESCRIPTION
**Pull request by ConnorBaker**
## Description of changes

- rewrite the expression and move to `by-name`
- format with `nixfmt`
- update from unstable-2023-11-10 to unstable-2024-04-09
- switch to CUDA redist
- switch to `autoAddDriverRunpath`
- add myself as a maintainer

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ConnorBaker** [comment]
Gotta make sure `ofborg-eval` succeeds with this one...

**Comment by ConnorBaker** [comment]
Runs on my `x86_64-linux` machine:

```console
[connorbaker@nixos-desktop:~/nixpkgs]$ nix run --impure -L -v .#gpu-burn -- -l
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
ID 0: NVIDIA GeForce RTX 4090, 25289MB

[connorbaker@nixos-desktop:~/nixpkgs]$ nix run --impure -L -v .#gpu-burn -- -m 2048
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
Run length not specified in the command line. Using compare file: /nix/store/ish3nyshdbisvdawnxn4ym6r7050m7aw-gpu-burn-unstable-2024-04-09/share/compare.ptx
Burning for 10 seconds.
GPU 0: NVIDIA GeForce RTX 4090 (UUID: GPU-ca874d65-71c7-ddce-a6e4-2f9f1079af48)
Initialized device 0 with 24118 MB of memory (23713 MB available, using 2048 MB of it), using FLOATS
Results are 268435456 bytes each, thus performing 6 iterations
20.0%  proc'd: 72 (58535 Gflop/s)   errors: 0   temps: 34 C 
	Summary at:   Thu Sep  5 09:42:58 PM UTC 2024

30.0%  proc'd: 126 (59094 Gflop/s)   errors: 0   temps: 34 C 
	Summary at:   Thu Sep  5 09:42:59 PM UTC 2024

50.0%  proc'd: 234 (58531 Gflop/s)   errors: 0   temps: 34 C 
	Summary at:   Thu Sep  5 09:43:01 PM UTC 2024

60.0%  proc'd: 288 (59082 Gflop/s)   errors: 0   temps: 61 C 
	Summary at:   Thu Sep  5 09:43:02 PM UTC 2024

80.0%  proc'd: 402 (60244 Gflop/s)   errors: 0   temps: 61 C 
	Summary at:   Thu Sep  5 09:43:04 PM UTC 2024

100.0%  proc'd: 510 (59605 Gflop/s)   errors: 0   temps: 61 C 
	Summary at:   Thu Sep  5 09:43:06 PM UTC 2024

100.0%  proc'd: 564 (59581 Gflop/s)   errors: 0   temps: 63 C 
Killing processes with SIGTERM (soft kill)
Freed memory for dev 0
Uninitted cublas
done

Tested 1 GPUs:
	GPU 0: OK
```

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 339911` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 339911` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)

**Review by GaetanLepage — APPROVED** [review]
LGTM, thanks Connor !

**Pull request merged**
