### PR TITLE
projectm: adopt, Qt{4->5}, {2->3}1.0, patch rpath, clean-up closure

### PR DESCRIPTION
**Pull request by Anton-Latukha**
###### Motivation for this change

The package was abandoned in `nixpkgs` for some time, but upstream is very active.

Now it is in a good state.

Also patching upstream, waiting on issue resolved or not - patch would roll on versions:
Upstream inserts the `src` path reference during build into ELF `rpath`, so we must delete it out.
upstream report: https://github.com/projectM-visualizer/projectm/issues/245

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mmilata** [comment]
Thanks for updating this fine piece of software! Unfortunately it doesn't seem to work for me:
```
$ cd nixpkgs
$ git checkout adopt-projectm
$ nix-build . -A projectm
...
$ ./result-bin/bin/projectM-pulseaudio
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

zsh: abort      ./result-bin/bin/projectM-pulseaudio
```
Issue #68615 seems similar.

**Comment by Anton-Latukha** [comment]
@mmilata This needed `wrapQtAppsHook`, I still not accustomed to bother with Nix runtime dependencies. On your system, it now must work.

**Comment by mmilata** [comment]
@Anton-Latukha also had to add f7245ab2cd353ac0688c81ca79f6cadab353b948 then it works

**Comment by Anton-Latukha** [comment]
@ajs124

I see that you want to take over this.

I hope you took from this thread everything useful here is.

I do not think I would use `projectm` much, but I see you probably would, so I close this in favor of you.

**Pull request closed without merging**
