### PR TITLE
python311Packages.sqlalchemy: 2.0.21 -> 2.0.22

### PR DESCRIPTION
**Pull request by mweinelt**
https://github.com/sqlalchemy/sqlalchemy/releases/tag/rel_2_0_22

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alyssais** [comment]
sqlalchemy-utils (indirect dependency of nix-prefetch-scripts) is broken with 2.0.22: https://github.com/kvesteri/sqlalchemy-utils/issues/719

**Comment by mweinelt** [comment]
Wondering how quick we can expect the sqlalchemy-utils maintainers to react.

**Comment by mweinelt** [comment]
Reverted in 1d1bb5f1cd98ede100955caaa66a5a466697d451

**Comment by mweinelt** [comment]
Last commit on sqlalchemy-utils was 7 months ago. The dependency runs via factory-boy, but is an extra just used for tests, so I'm killing that dependency chain, so we can move on.

**Comment by alyssais** [comment]
Apparently now fixed upstream https://github.com/kvesteri/sqlalchemy-utils/commit/00d800063d2f8d2dcee714a3314311d79f8d4040

**Pull request merged**
