### PR TITLE
staging-next 2022-05-04

### PR DESCRIPTION
**Pull request by vcunat**
- workflow docs: [nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy](https://nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy)
- constitutents: [hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents](https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents)
- jobset: [hydra.nixos.org/jobset/nixpkgs/staging-next](https://hydra.nixos.org/jobset/nixpkgs/staging-next)
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next: https://github.com/NixOS/nixpkgs/pull/169965

### CODE REVIEW

**Comment by tpwrules** [comment]
It looks like this broke `gfortran` (and probably `gcc`) on aarch64-darwin. My guess is that this patch needs to be updated or removed after #170121: https://github.com/NixOS/nixpkgs/blob/3c36acf988e6f7e104adea166124fa8451e9abfe/pkgs/development/compilers/gcc/11/default.nix#L72

@bobrik initially introduced it, maybe they know how to update it? Otherwise I will try tonight. Is it acceptable to send a PR directly to `staging-next` to fix this?

**Comment by vcunat** [comment]
Yes, regressions introduced in `master..staging-next` are sent directly to `staging-next`.

**Comment by bobrik** [comment]
> @bobrik initially introduced it, maybe they know how to update it?

Previously I waited for @fxcoudert to update his fork and created a patch from the tags diff there. Looks like there's no update for 11.3 thought. Homebrew puts 11.2 as 11.3:

* https://github.com/Homebrew/homebrew-core/commit/5849ebff85a5684a4f67459cd2ab771aa3663143

**Comment by fxcoudert** [comment]
> Homebrew puts 11.2 as 11.3

The release of gcc 12.1.0 will happen on Friday, so I deemed the effort of rebasing a 11.3 port for two weeks not worth it. You can have a look at this branch by the darwin GCC maintainer, if you want: https://github.com/iains/gcc-11-branch/tree/gcc-11-3-apple-si

It contains the diff you can apply on top of 11.3

**Comment by delroth** [comment]
Regression fix from 22f5d327101dbf13c072761417f460ed413725e8: #171832

**Comment by ncfavier** [comment]
More https://github.com/NixOS/nixpkgs/pull/164163 -related fixes:

- [ ] https://github.com/NixOS/nixpkgs/pull/171836

**Comment by fabianhjr** [comment]
There is an issue with firefox on staging-next. Crashes instantly with exit status 255.

**Comment by ncfavier** [comment]
No surprise, this is related to https://github.com/NixOS/nixpkgs/pull/164163.

The culprit seems to be this part of the firefox wrapper:
https://github.com/NixOS/nixpkgs/blob/384d446910801ac29070cac4765761caba15fcd0/pkgs/applications/networking/browsers/firefox/wrapper.nix#L216-L219

It rewrites the target of the gapps wrapper from
```
/nix/store/1qg729mv21pk0i7hylx4qczirdfybv8d-firefox-release-bin-unwrapped-100.0/bin/.firefox-wrapped
```
to
```
/nix/store/gyybbi7d2jwr23f673ascrmq6c5wh2yy-firefox-bin-100.0in-unwrapped-100.0/bin/.firefox-wrapped
```

**Comment by vcunat** [comment]
- [ ] @rszibele: `curlcpp` [broke down](https://hydra.nixos.org/build/175469502), maybe due to curl update.  (you're in `meta.maintainers`)

**Comment by ncfavier** [comment]
- [ ] https://github.com/NixOS/nixpkgs/pull/171985

**Pull request merged**
