### PR TITLE
docker-machine: 0.10.0 -> 0.12.0

### PR DESCRIPTION
**Pull request by 1755**
###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
cc @tailhook @offlinehacker

**Comment by joachifm** [comment]
I take it this received no testing?

**Comment by 1755** [comment]
@joachifm Unfortunately no. I just​ update the version and sha256 hash. It was needed for my task. I just decided to share this quickfix

**Comment by grahamc** [comment]
Thank you, @1755!

**Comment by grahamc** [comment]
Thank you, @1755! Can you update your commit message to say "docker-machine: 0.10.0 -> 0.12.0"? If not, I can  do it for you. Otherwise, it looks  good to merge.

**Comment by 1755** [comment]
@grahamc I have not cloned repo. Can you do it please?

**Comment by Mic92** [comment]
@grahamc you can also do that, when using squasing instead of merging.

**Comment by grahamc** [comment]
Thank you! I'm sorry this took so long :/

**Pull request closed without merging**
