### PR TITLE
signal-desktop: move to pkgs/by-name; signal-desktop{x86_64-linux, aarch64-linux, darwin}: 7.33.0 -> 7.34.0; add myself to maintainers

### PR DESCRIPTION
**Pull request by Gliczy**
Changelog: https://github.com/signalapp/Signal-Desktop/releases/tag/v7.34.0
Diff: https://github.com/signalapp/Signal-Desktop/compare/v7.33.0...v7.34.0

Manually tested the `x86_64-linux` build.
I tried to run the `aarch64-linux` build, but it fails with:
```
The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /nix/store/sbn0dqvimalvwsc2kkv3i48lf30s5sbz-signal-desktop-7.34.0/lib/Signal/chrome-sandbox is owned by root and has mode 4755.
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
```
Note that I ran it from a `x86_64` machine with `aarch64` emulation.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by teutat3s — COMMENTED** [review]
Please update the darwin package to version 7.34, too. One can get the hash with:

```
nix hash to-sri --type sha256 $(nix-prefetch-url https://updates.signal.org/desktop/signal-desktop-mac-universal-7.34.0.dmg)
```

**Comment by Gliczy** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 358187`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>signal-desktop</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>signal-desktop</li>
  </ul>
</details>

**Comment by Gliczy** [comment]
Sorry I'm not the most familiar with `all-packages.nix`, and I'm not sure I understand what is the problem with `nixpkgs-vet`.

**Comment by teutat3s** [comment]
I think we're good to just delete that line from `all-packages.nix`.

**Comment by Gliczy** [comment]
Removing the line or using the one suggested by `nixpkgs-vet` both work fine with `nix-build -A signal-desktop`. However, it fails when running `nix build .#signal-desktop`, which works with the current line that is falling the `nixpkgs-vet` check.

**Comment by emilazy** [comment]
You need to remove `{ signal-desktop = …; }` from `package.nix`.

**Comment by Gliczy** [comment]
@emilazy So should the different calls for each systems/arch be moved into `all-packages.nix` instead? And in that case, what should happen to `package.nix` (as it's whole content would be moved)?

**Comment by emilazy** [comment]
No; just replace `{ signal-desktop = …; }` with `…`. `{ … }: if … then … else …`.

**Comment by teutat3s** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 358187`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>signal-desktop</li>
  </ul>
</details>

**Review by teutat3s — APPROVED** [review]

**Comment by emilazy** [comment]
I guess it’s just an `all-packages.nix` conflict. Can you do the manual backport steps?

**Pull request merged**
