### PR TITLE
[20.09] Staging

### PR DESCRIPTION
**Pull request by roberth**
###### Motivation for this change

Gather and deliver staging changes.

###### Things done

  - [x] [base: staging](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+is%3Aopen+base%3Astaging-20.09)
  - [x] [base: release](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+is%3Aopen+base%3Arelease-20.09) (if mass-rebuild)
  - [x] [base: wrong branch](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+is%3Aopen+base%3Anixos-20.09)
  - [ ] let it build on hydra

https://hydra.nixos.org/jobset/nixpkgs/staging-20.09

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 117191` at 5ce64bf7 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>906 packages marked as broken and skipped:</summary>
  <ul>
    <li>Literate</li>
    <li>OVMF-CSM</li>
    <li>agdaPackages.iowa-stdlib</li>
    <li>aldor</li>
    <li>alliance</li>
    <li>ams-lv2</li>
    <li>amsn</li>
    <li>anki</li>
    <li>ankisyncd</li>
    <li>apfelgrid</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>8875 packages skipped due to time constraints:</summary>
  <ul>
    <li>AusweisApp2</li>
    <li>DisnixWebService</li>
    <li>EmptyEpsilon</li>
    <li>MMA</li>
    <li>OVMF</li>
    <li>OVMF-secureBoot</li>
    <li>R</li>
    <li>SDL</li>
    <li>SDL2</li>
    <li>SDL2_gfx</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>29 packages built successfully:</summary>
  <ul>
    <li>asciidoctor</li>
    <li>epoxy</li>
    <li>fontconfig</li>
    <li>glib (gnome2.glib ,gnome3.glib)</li>
    <li>harfbuzz</li>
    <li>json-glib</li>
    <li>libass</li>
    <li>libnotify</li>
    <li>libtiff</li>
    <li>libva</li>
    <li>libva-minimal</li>
    <li>mesa_glu</li>
    <li>nettle</li>
    <li>newt</li>
    <li>openjdk8-bootstrap</li>
    <li>pango</li>
    <li>popt</li>
    <li>python37Packages.django (python37Packages.django_2_2 ,python37Packages.django_lts)</li>
    <li>python37Packages.tkinter</li>
    <li>python38Packages.django (python38Packages.django_2_2 ,python38Packages.django_lts)</li>
    <li>python38Packages.pycairo</li>
    <li>python38Packages.pygobject3</li>
    <li>python38Packages.tkinter</li>
    <li>shared-mime-info</li>
    <li>tesseract (tesseract3)</li>
    <li>unbound</li>
    <li>vala (vala_0_48)</li>
    <li>wayland-protocols</li>
    <li>xlibsWrapper (xorg.xlibsWrapper)</li>
  </ul>
</details>
<details>
  <summary>7 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/libraries/libtiff/default.nix:57:3:
```
   |
57 |   meta = with stdenv.lib; {
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/libraries/nettle/generic.nix:28:3:
```
   |
28 |   meta = with stdenv.lib; {
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/libraries/popt/default.nix:19:3:
```
   |
19 |   meta = with stdenv.lib; {
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Please add a comment on the line above, explaining the purpose of this patch.
Near pkgs/development/libraries/popt/default.nix:13:5:
```
   |
13 |     ./1.16-cygwin.patch
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Please add a comment on the line above, explaining the purpose of this patch.
Near pkgs/development/libraries/popt/default.nix:14:5:
```
   |
14 |     ./1.16-vpath.patch
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/python-include-tests.md">python-include-tests</a>

Consider adding a `checkPhase` for tests, or if not feasible, `pythonImportsCheck`.

Near pkgs/development/python-modules/django/2_2.nix:33:0:
```
   |
33 |     description = "A high-level Python Web framework";
   | ^
```
</li>
    <li>warning: EvalError

Cannot evaluate attribute ‘glib’ in ‘/nix/store/6a3bn97y8ch8rzqx49wb7mcj6bahdspr-nixpkgs’.</li>
  </ul>
</details>

**Comment by FRidh** [comment]
```
[18:10] <FRidh> staging-20.09 is almost finished, just in time for another round tomorrow with those fixes...
[18:10] <gchristensen> please don't merge staging until after openssl is released in to channels
```

**Comment by SuperSandro2000** [comment]
@vcunat did the openssl release already drop?

**Comment by vcunat** [comment]
No, I can't see it on their web, nor the expected download URL for the tarball.

**Comment by FRidh** [comment]
eval error
```
$ nix-build -A adoptopenjdk-hotspot-bin-14 
```

**Comment by roberth** [comment]
> eval error
> 
> ```
> $ nix-build -A adoptopenjdk-hotspot-bin-14 
> ```

I don't think this attribute was ever part of 20.09.
It is certainly not part of this staging iteration.

**Comment by FRidh** [comment]
Right, it was cherry-picked onto release-20.09 directly, https://github.com/NixOS/nixpkgs/pull/117586.

**Pull request merged**
