### PR TITLE
libinput: refactor & add optional dependencies

### PR DESCRIPTION
**Pull request by codyopel**

### CODE REVIEW

**Comment by vcunat** [comment]
CC @wkennington (I know little about libinput).

**Comment by vcunat** [comment]
Just out of curiosity: would there be some demand to have ``xf86-input-libinput``` soon? We don't have it yet, but it should be easy for me to add.

**Comment by codyopel** [comment]
I suppose it would be fine to add, I am looking into cleaning up X11 a bit in the future since we are missing other libraries (don't know if what is missing is of use to us) since we no longer generate the expression, partially due to X11 mirror layout changes.

**Comment by vcunat** [comment]
We do generate the xorg expression (or at least I do re-generate it), only the tarball list is updated by hand, as they no longer make whole-xorg releases (named X11R7.x). I just follow their release announcement list...

**Comment by codyopel** [comment]
Ok, I wasn't sure if updated it was by hand completely or not.

I was originally looking in to rewriting the scripts since xorg changed their mirror's directory layout, (everything now being in /individual/<category>/) breaking the functionality of the tarball script.  I am looking at combining the tarball and expression generation into a single script and add a way to easily white list or black list packages (and versions) so that it doesn't unintentionally add unneeded/old/random packages like compiz that still exist on the xorg mirrors.  I also want to have it store things such as the hash of the file, filename, version, etc... in a json file (or something similar)  so that updating the expression doesn't require re-downloading tarballs that are up-to-date.  The intent is to hopefully make updating xorg much simpler and prevent out of date packages since I was finding some random packages here and there that haven't been updated in a while, and unfortunately due to the amount of packages in xorg it is a lot of work to keep track of.  When I do get around to this I'll let you know to get feedback or help.

If you have any thoughts or ideas let me know.

**Comment by vcunat** [comment]
There's no script for generating the tarball list, but generating from that list seems fine (except that it's rather slow due to re-downloading and re-generating *everything*).

**Comment by codyopel** [comment]
Sorry, I wasn't looking at it at the time, I meant the one liner in the comments at the top of the expression script.  I forgot it wasn't actually a separate script.

**Pull request merged**
