### PR TITLE
[20.09] Staging next

### PR DESCRIPTION
**Pull request by roberth**
###### Motivation for this change

Deliver staging changes.

###### Things done

Latest hydra (as of description update time)

https://hydra.nixos.org/eval/1646124

### CODE REVIEW

**Comment by blitz** [comment]
@roberth Awesome!

I have one problem so far:

```
building the system configuration...
error: Linux v5.10.11 is not yet supported by zfsonlinux v0.8.6.
Try zfsUnstable or set the NixOS option boot.zfs.enableUnstable.
```

This is weird, because I'm not even using ZFS in my configuration. Setting `boot.zfs.enableUnstable` doesn't work to go past this. I've commented out the check and am currently building my system configuration. Will report back whether I see any issues.

**Comment by roberth** [comment]
@blitz I don't think it's caused by the zfs update commit. Does it also happen on release-20.09?

**Comment by blitz** [comment]
> @blitz I don't think it's caused by the zfs update commit. Does it also happen on release-20.09?

No, there it's fine because the included ZFS version is still compatible with linuxPackages_latest (5.9.16).

**Comment by roberth** [comment]
@lheckemann @NeQuissimus it seems that the linux/zfs update doesn't build cleanly. Could you try fix it?

> > @blitz I don't think it's caused by the zfs update commit. Does it also happen on release-20.09?
> 
> No, there it's fine because the included ZFS version is still compatible with linuxPackages_latest (5.9.16).

**Comment by blitz** [comment]
I also noticed a stale `linux_5_9` attribute:

```sh
% nix-build -A pkgs.linux_5_9
error: getting status of '/home/julian/src/own/nixpkgs/pkgs/os-specific/linux/kernel/linux-5.9.nix': No such file or directory
```

This might cause `grahamcofborg-eval` to fail, because it says:

```
getting status of '/var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/ofborg-evaluator-0/pkgs/os-specific/linux/kernel/linux-5.9.nix': No such file or directory
```

**Comment by blitz** [comment]
Besides the ZFS evaluation issues, it looks good. I'm writing this from a system running these changes after patching out the ZFS version check.

**Comment by blitz** [comment]
@roberth #109029 had a solution for the ZFS issue. You can cherry-pick the last two commits from my branch, if you want:

https://github.com/blitz/nixpkgs/commits/staging-20.09

**Comment by NeQuissimus** [comment]
OpenZFS 2.0.1 is the first release with compatibility for Linux 5.10. We'll have to update to that.

I just pushed 326d8f4f5ad.

**Comment by NeQuissimus** [comment]
Stale attribute gone as well.

**Review by blitz — APPROVED** [review]

**Comment by mweinelt** [comment]
ZFS does not yet work.

```
$ nix-build -A linuxPackages.zfs
[...]
substitute(): ERROR: file './module/zfs/zfs_ctldir.c' does not exist
builder for '/nix/store/5wsjzfkyrqz7r3lmmq0ywwvybnfyzh2k-zfs-kernel-2.0.1-5.4.93.drv' failed with exit code 1
```

**Comment by NeQuissimus** [comment]
@mweinelt I am just picking the necessary ZFS changes onto `staging-20.09` and building them. Give me an hour

**Comment by NeQuissimus** [comment]
Verified with `nix-build -A linuxPackages.zfs -A linuxPackages.zfsUnstable -A linuxPackages_latest.zfs -A linuxPackages_latest.zfsUnstable` and `nix-build ./nixos/tests/zfs.nix`.

**Comment by jonringer** [comment]
I believe there's also a patch that should be included as there was a regression with people using legacy mounts

**Comment by NeQuissimus** [comment]
Oh, which patch is this?

**Comment by roberth** [comment]
@NeQuissimus @jonringer I think this is the zfs legacy mount issue you're talking about https://github.com/NixOS/nixpkgs/issues/110376.

@NeQuissimus What's the reason to remove Linux 5.9? Seems wrong to do so on the stable branch.

I'd like to merge `staging-20.09` asap, before it gets delayed any further due to scope creep.

**Comment by mweinelt** [comment]
> @NeQuissimus What's the reason to remove Linux 5.9? Seems wrong to do so on the stable branch.

Because 5.9 is EOL and the next LTS release cycle is 5.10.

**Comment by jonringer** [comment]
> Oh, which patch is this?

this one https://github.com/NixOS/nixpkgs/pull/111375

**Pull request merged**
