### PR TITLE
python310Packages.ansible: 7.2.0 -> 8.0.0

### PR DESCRIPTION
**Pull request by mokrinsky**
###### Description of changes

8.0.0 changelog: https://github.com/ansible-community/ansible-build-data/blob/main/8/CHANGELOG-v8.rst
7.x.0 changelog (since there were several releases since 7.2.0): https://github.com/ansible-community/ansible-build-data/blob/main/7/CHANGELOG-v7.rst

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mokrinsky** [comment]
Result of `nixpkgs-review` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages failed to build:</summary>
  <ul>
    <li>python310Packages.ansible-kernel</li>
    <li>python310Packages.ansible-kernel.dist</li>
    <li>python310Packages.ansible-runner</li>
    <li>python310Packages.ansible-runner.dist</li>
    <li>python310Packages.pytest-ansible</li>
    <li>python310Packages.pytest-ansible.dist</li>
    <li>python311Packages.ansible-kernel</li>
    <li>python311Packages.ansible-kernel.dist</li>
    <li>python311Packages.ansible-runner</li>
    <li>python311Packages.ansible-runner.dist</li>
    <li>python311Packages.pytest-ansible</li>
    <li>python311Packages.pytest-ansible.dist</li>
  </ul>
</details>
<details>
  <summary>22 packages built:</summary>
  <ul>
    <li>ansible (python310Packages.ansible-core)</li>
    <li>ansible-later</li>
    <li>ansible-later.dist</li>
    <li>ansible-lint</li>
    <li>ansible-lint.dist</li>
    <li>ansible.dist (python310Packages.ansible-core.dist)</li>
    <li>ansible_2_13</li>
    <li>ansible_2_13.dist</li>
    <li>ansible_2_14</li>
    <li>ansible_2_14.dist</li>
    <li>kargo</li>
    <li>kargo.dist</li>
    <li>python310Packages.ansible</li>
    <li>python310Packages.ansible-compat</li>
    <li>python310Packages.ansible-compat.dist</li>
    <li>python310Packages.ansible.dist</li>
    <li>python311Packages.ansible</li>
    <li>python311Packages.ansible-compat</li>
    <li>python311Packages.ansible-compat.dist</li>
    <li>python311Packages.ansible-core</li>
    <li>python311Packages.ansible-core.dist</li>
    <li>python311Packages.ansible.dist</li>
  </ul>
</details>

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 235220` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages failed to build:</summary>
  <ul>
    <li>python310Packages.ansible-kernel</li>
    <li>python310Packages.ansible-kernel.dist</li>
    <li>python310Packages.ansible-runner</li>
    <li>python310Packages.ansible-runner.dist</li>
    <li>python310Packages.pytest-ansible</li>
    <li>python310Packages.pytest-ansible.dist</li>
    <li>python311Packages.ansible-kernel</li>
    <li>python311Packages.ansible-kernel.dist</li>
    <li>python311Packages.ansible-runner</li>
    <li>python311Packages.ansible-runner.dist</li>
    <li>python311Packages.pytest-ansible</li>
    <li>python311Packages.pytest-ansible.dist</li>
  </ul>
</details>
<details>
  <summary>22 packages built:</summary>
  <ul>
    <li>ansible (ansible_2_15 ,python310Packages.ansible-core)</li>
    <li>ansible-later</li>
    <li>ansible-later.dist</li>
    <li>ansible-lint</li>
    <li>ansible-lint.dist</li>
    <li>ansible.dist (ansible_2_15.dist ,python310Packages.ansible-core.dist)</li>
    <li>ansible_2_13</li>
    <li>ansible_2_13.dist</li>
    <li>ansible_2_14</li>
    <li>ansible_2_14.dist</li>
    <li>kargo</li>
    <li>kargo.dist</li>
    <li>python310Packages.ansible</li>
    <li>python310Packages.ansible-compat</li>
    <li>python310Packages.ansible-compat.dist</li>
    <li>python310Packages.ansible.dist</li>
    <li>python311Packages.ansible</li>
    <li>python311Packages.ansible-compat</li>
    <li>python311Packages.ansible-compat.dist</li>
    <li>python311Packages.ansible-core</li>
    <li>python311Packages.ansible-core.dist</li>
    <li>python311Packages.ansible.dist</li>
  </ul>
</details>

**Comment by Et7f3** [comment]
34 packages built:
ansible ansible-later ansible-later.dist ansible-lint ansible-lint.dist ansible.dist ansible_2_13 ansible_2_13.dist ansible_2_14 ansible_2_14.dist kargo kargo.dist python310Packages.ansible python310Packages.ansible-compat python310Packages.ansible-compat.dist python310Packages.ansible-kernel python310Packages.ansible-kernel.dist python310Packages.ansible-runner python310Packages.ansible-runner.dist python310Packages.ansible.dist python310Packages.pytest-ansible python310Packages.pytest-ansible.dist python311Packages.ansible python311Packages.ansible-compat python311Packages.ansible-compat.dist python311Packages.ansible-core python311Packages.ansible-core.dist python311Packages.ansible-kernel python311Packages.ansible-kernel.dist python311Packages.ansible-runner python311Packages.ansible-runner.dist python311Packages.ansible.dist python311Packages.pytest-ansible python311Packages.pytest-ansible.dist


on x86_64-linux Can you show one kind of error ?

**Review by Et7f3 — APPROVED** [review]

**Comment by wegank** [comment]
Indeed, there is no new regression.

**Review by wegank — APPROVED** [review]

**Comment by mokrinsky** [comment]
for `ansible-runner`:
```
test/unit/config/test_doc.py:120: AssertionError
1m=========================== short test summary info ============================
FAILED test/unit/config/test_ansible_cfg.py::test_prepare_config_command_with_containerization[docker] - AssertionError: assert ['docker', 'r...project', ...] == ['docker', 'r...pr...
FAILED test/unit/config/test_ansible_cfg.py::test_prepare_config_command_with_containerization[podman] - AssertionError: assert ['podman', 'r...project', ...] == ['podman', 'r...pr...
FAILED test/unit/config/test_command.py::test_prepare_run_command_with_containerization[docker] - AssertionError: assert ['docker', 'r...workdir', ...] == ['docker', 'r...wo...
FAILED test/unit/config/test_command.py::test_prepare_run_command_with_containerization[podman] - AssertionError: assert ['podman', 'r...workdir', ...] == ['podman', 'r...wo...
FAILED test/unit/config/test_doc.py::test_prepare_plugin_docs_command_with_containerization[docker] - AssertionError: assert ['docker', 'r...project', ...] == ['docker', 'r...pr...
FAILED test/unit/config/test_doc.py::test_prepare_plugin_list_command_with_containerization[podman] - AssertionError: assert ['podman', 'r...project', ...] == ['podman', 'r...pr...
FAILED test/unit/config/test_doc.py::test_prepare_plugin_list_command_with_containerization[docker] - AssertionError: assert ['docker', 'r...project', ...] == ['docker', 'r...pr...
FAILED test/unit/config/test_inventory.py::test_prepare_inventory_command_with_containerization[podman] - AssertionError: assert ['podman', 'r...project', ...] == ['podman', 'r...pr...
FAILED test/unit/config/test_inventory.py::test_prepare_inventory_command_with_containerization[docker] - AssertionError: assert ['docker', 'r...project', ...] == ['docker', 'r...pr...
FAILED test/unit/config/test_doc.py::test_prepare_plugin_docs_command_with_containerization[podman] - AssertionError: assert ['podman', 'r...project', ...] == ['podman', 'r...pr...
31m======================= 10 failed, 1880 passed in 14.34s =======================
```
I checked source code of these tests and it looks like docker for darwin doesn't have CLI options that are used in tests, hence it fails to run docker/podman. `ansible-kernel` depends on `ansible-runner` so i didn't even start building after dependency failure.

Speaking about `pytest-ansible`, I didn't dig it cause python is not my strongest language so far, but it feels like pytest connects to localhost and runs some ansible tasks, and since darwin has no sshd enabled by default, it fails these tests.
```
1m=========================== short test summary info ============================
FAILED tests/test_adhoc.py::test_contacted_with_params - assert <ExitCode.TESTS_FAILED: 1> == <ExitCode.OK: 0>
FAILED tests/test_adhoc.py::test_contacted_with_params_and_inventory_marker - assert <ExitCode.TESTS_FAILED: 1> == <ExitCode.OK: 0>
FAILED tests/test_adhoc.py::test_contacted_with_params_and_host_pattern_marker - assert <ExitCode.TESTS_FAILED: 1> == <ExitCode.OK: 0>
FAILED tests/test_adhoc.py::test_contacted_with_params_and_inventory_host_pattern_marker - assert <ExitCode.TESTS_FAILED: 1> == <ExitCode.OK: 0>
FAILED tests/test_fixtures.py::test_ansible_facts - assert <ExitCode.TESTS_FAILED: 1> == <ExitCode.OK: 0>
FAILED tests/test_params.py::test_param_override_with_marker - assert <ExitCode.TESTS_FAILED: 1> == <ExitCode.OK: 0>
ERROR tests/test_adhoc_result.py::test_len - pytest_ansible.errors.AnsibleConnectionFailure: Host unreachable in the inv...
ERROR tests/test_adhoc_result.py::test_keys - pytest_ansible.errors.AnsibleConnectionFailure: Host unreachable in the inv...
ERROR tests/test_adhoc_result.py::test_items - pytest_ansible.errors.AnsibleConnectionFailure: Host unreachable in the inv...
ERROR tests/test_adhoc_result.py::test_values - pytest_ansible.errors.AnsibleConnectionFailure: Host unreachable in the inv...
ERROR tests/test_adhoc_result.py::test_contains[another_host] - pytest_ansible.errors.AnsibleConnectionFailure: Host unreachable in the inv...
ERROR tests/test_adhoc_result.py::test_contains[localhost] - pytest_ansible.errors.AnsibleConnectionFailure: Host unreachable in the inv...
ERROR tests/test_adhoc_result.py::test_contains[yet_another_host] - pytest_ansible.errors.AnsibleConnectionFailure: Host unreachable in the inv...
ERROR tests/test_adhoc_result.py::test_not_contains[none] - pytest_ansible.errors.AnsibleConnectionFailure: Host unreachable in the inv...
ERROR tests/test_adhoc_result.py::test_not_contains[all] - pytest_ansible.errors.AnsibleConnectionFailure: Host unreachable in the inv...
ERROR tests/test_adhoc_result.py::test_not_contains[*] - pytest_ansible.errors.AnsibleConnectionFailure: Host unreachable in the inv...
ERROR tests/test_adhoc_result.py::test_not_contains[local*] - pytest_ansible.errors.AnsibleConnectionFailure: Host unreachable in the inv...
ERROR tests/test_adhoc_result.py::test_getitem[another_host] - pytest_ansible.errors.AnsibleConnectionFailure: Host unreachable in the inv...
ERROR tests/test_adhoc_result.py::test_getitem[localhost] - pytest_ansible.errors.AnsibleConnectionFailure: Host unreachable in the inv...
ERROR tests/test_adhoc_result.py::test_getitem[yet_another_host] - pytest_ansible.errors.AnsibleConnectionFailure: Host unreachable in the inv...
ERROR tests/test_adhoc_result.py::test_not_getitem[none] - pytest_ansible.errors.AnsibleConnectionFailure: Host unreachable in the inv...
ERROR tests/test_adhoc_result.py::test_not_getitem[all] - pytest_ansible.errors.AnsibleConnectionFailure: Host unreachable in the inv...
ERROR tests/test_adhoc_result.py::test_not_getitem[*] - pytest_ansible.errors.AnsibleConnectionFailure: Host unreachable in the inv...
ERROR tests/test_adhoc_result.py::test_not_getitem[local*] - pytest_ansible.errors.AnsibleConnectionFailure: Host unreachable in the inv...
ERROR tests/test_adhoc_result.py::test_getattr[another_host] - pytest_ansible.errors.AnsibleConnectionFailure: Host unreachable in the inv...
ERROR tests/test_adhoc_result.py::test_getattr[localhost] - pytest_ansible.errors.AnsibleConnectionFailure: Host unreachable in the inv...
ERROR tests/test_adhoc_result.py::test_getattr[yet_another_host] - pytest_ansible.errors.AnsibleConnectionFailure: Host unreachable in the inv...
ERROR tests/test_adhoc_result.py::test_not_getattr[none] - pytest_ansible.errors.AnsibleConnectionFailure: Host unreachable in the inv...
ERROR tests/test_adhoc_result.py::test_not_getattr[all] - pytest_ansible.errors.AnsibleConnectionFailure: Host unreachable in the inv...
ERROR tests/test_adhoc_result.py::test_not_getattr[*] - pytest_ansible.errors.AnsibleConnectionFailure: Host unreachable in the inv...
ERROR tests/test_adhoc_result.py::test_not_getattr[local*] - pytest_ansible.errors.AnsibleConnectionFailure: Host unreachable in the inv...
31m= 6 failed, 117 passed, 15 skipped, 3 deselected, 44 warnings, 25 errors in 34.36s =
```

I checked history and it looks like these three packages were broken for darwin for a while and there were no issues opened about it, so i decided to PR regardless of these failures.

**Pull request merged**
