### PR TITLE
signal-desktop: 7.22.0 -> 7.22.2, -aarch64: 7.19.0 -> 7.20.0

### PR DESCRIPTION
**Pull request by equirosa**
## Description of changes

Updates:
- amd64:
  - https://github.com/signalapp/Signal-Desktop/releases/tag/v7.22.1
  - https://github.com/signalapp/Signal-Desktop/releases/tag/v7.22.2
  - https://github.com/signalapp/Signal-Desktop/releases/tag/v7.23.0
- amd64-beta: https://github.com/signalapp/Signal-Desktop/releases/tag/v7.24.0-beta.1
- aarch64: 
  - https://github.com/0mniteck/Signal-Desktop-Mobian/releases/tag/7.20.0
  - https://github.com/0mniteck/Signal-Desktop-Mobian/releases/tag/7.23.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilazy** [comment]
Not sure why ofborg didn’t ping me for this. The hash is wrong for AArch64 (unfortunately due to the emoji stripping you can’t just use `nix-prefetch-url`, it actually requires an AArch64 machine… we really need to build this from source already).

**Comment by equirosa** [comment]
> Not sure why ofborg didn’t ping me for this. The hash is wrong for AArch64 (unfortunately due to the emoji stripping you can’t just use `nix-prefetch-url`, it actually requires an AArch64 machine… we really need to build this from source already).
> 
> Thankfully ofborg has given the correct hash in the error.

Is there a way to try building it through some sort of emulation? I don't have any aarch64 machines. Side note, I just saw this and didn't notice when making a new PR, so I'll move those changes to here and close that one :sweat_smile: after we get the error again I'll fix the hash :grin:

**Comment by emilazy** [comment]
If you’re on NixOS, you can just set `boot.binfmt.emulatedSystems = [ "aarch64-linux" ];`, or I think you could also do `pkgsCross.aarch64-multiplatform.signal-desktop.src` since it’s a FOD, but it might have to build a lot, not sure.

**Comment by emilazy** [comment]
FWIW, the hash is `sha256-fQb2nYE1+q6DNcMF0z5NadGlffYaCFNgcu8IIGVUtf8=` :)

**Comment by emilazy** [comment]
@equirosa Any update on this? (Looks like there’s been a new release again.)

**Pull request closed without merging**
