### PR TITLE
eclipses.eclipse-dsl: Init at 2023-09

### PR DESCRIPTION
**Pull request by GlancingMind**
###### Description of changes

Add [Eclipse IDE for Java and DSL Developers](https://www.eclipse.org/downloads/packages/release/2023-03/r/eclipse-ide-java-and-dsl-developers) to eclipses package set.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by OPNA2608** [comment]
Eclipse package set was bumped to 2023-06 in #246202, and will (hopefully soon) be bumped to 2023-09 in #258421. Could you bump this to 2023-06 & keep an eye out for the further 2023-09 update being merged?

**Comment by GlancingMind** [comment]
@OPNA2608 Bumped version to 2023-09 and changed the PRs name accordingly.

**Review by OPNA2608 — CHANGES_REQUESTED** [review]
Hmm. I can confirm that it builds & tries to launch on x86_64 & aarch64, but it fails on both. On one it just errors out, on the other it messes with my night mode before crashing the entire desktop session. But, `eclipses.eclipse-java` from the same tree fails in the same manner on both systems… Some incompatibility with system vs master? Maybe @jerith666 could check if this works for them.

- Please squash the commits and just init it as version 2023-09, the first commit wouldn't work on its own due to how the version-related attributes are handled in the `eclipses` attrset.

- Please retitle commit & PR to the correct attribute for the package: `eclipses.eclipse-dsl`.

- At the top of the file is a comment to help with testing & updating all of the `eclipses.eclipse-` variants, please add `dsl` there:
https://github.com/NixOS/nixpkgs/blob/21fbcce7a85b4280bd22ecd5a3d260774b8dc010/pkgs/applications/editors/eclipse/default.nix#L9-L12

**Comment by jerith666** [comment]
I tried at 21fbcce7a85b, on `x86_64`, and and all four of `eclipse-platform`, `eclipse-java`, `eclipse-jee`, and `eclipse-dsl` launched to the welcome screen cleanly for me.  Not sure what might be different for you, @OPNA2608.  :-/

**Comment by OPNA2608** [comment]
Hmm well that's definitely weird, but I have my hands full with other things right now so I'll leave it at "currently cursed for me". Thanks for checking! :smile:

Then I think this would be fine in terms of functionality. Just the points from earlier need to be addressed, then this LGTM.

**Comment by GlancingMind** [comment]
Done. Let me know if there are any other concerns. :-)

PS: For me the eclipse instance launches. No errors on my side.

**Review by OPNA2608 — APPROVED** [review]
Cursed systems it is then 🙂. LGTM.

**Comment by emilytrau** [comment]
Result of `nixpkgs-review pr 236094` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>eclipses.eclipse-dsl</li>
  </ul>
</details>

**Review by emilytrau — APPROVED** [review]

**Comment by emilytrau** [comment]
Welcome and thanks for your contribution!

**Pull request merged**
