### PR TITLE
buildGraalvm: move files in $out to $out/share

### LINKED ISSUE #345907: File collision: $out/LICENSE.txt of graalvm-ce and visualvm
### Describe the bug

System configuration fails to build when both packages are being installed

### Steps To Reproduce

1. Have `graalvm-ce` and `visualvm` installed
2. Rebuild

### Expected behavior

No Errors

### Screenshots

n/a

### Additional context

```
       last 1 log lines:
       > error: collision between `/nix/store/jcgwhvzay6j52r8gy2jv7in0v8vcf1ms-graalvm-ce-23.0.0/LICENSE.txt' and `/nix/store/kx6qx8jj3z929gqwbplw1j3iw40lqyx9-visualvm-2.1.10/LICENSE.txt'
       For full logs, run 'nix log /nix/store/zbnnzhh1jis34zv07j11p68vzn4jf5zg-home-manager-path.drv'.
```

### Notify maintainers

GraalVM-CE: @bennyandresen @hlolli @glittershark @babariviere @ericdallo @thiagokokada 

VisualVM: @michalrus @moaxcp 

### Metadata

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.1-cachyos, NixOS, 24.11 (Vicuna), 24.11.20240929.06cf0e1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.8`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/r2hk87rfvc5fpfbl2bj64a3x7mcq9f6c-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by thiagokokada**
Like `$out/LICENSE.txt` since this is generally a bad idea and can cause conflicts with other packages.

Fixes #345907.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by thiagokokada** [comment]
@ofborg build babashka clojure-lsp

**Comment by thiagokokada** [comment]
CC @ninelore since you're the author of #345907.

**Comment by ninelore** [comment]
Result of `nixpkgs-review pr 346174` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>17 packages built:</summary>
  <ul>
    <li>babashka</li>
    <li>babashka-unwrapped</li>
    <li>bbin</li>
    <li>certificate-ripper</li>
    <li>clj-kondo</li>
    <li>cljfmt</li>
    <li>clojure-lsp</li>
    <li>cq</li>
    <li>dapl-native</li>
    <li>dbqn-native</li>
    <li>graalvm-ce</li>
    <li>jet</li>
    <li>neil</li>
    <li>scala-update</li>
    <li>vscode-extensions.betterthantomorrow.calva</li>
    <li>yamlscript</li>
    <li>zprint</li>
  </ul>
</details>

**Comment by thiagokokada** [comment]
@ofborg build Babashka graalvm-ce

**Comment by thiagokokada** [comment]
@ofborg build babashka clojure-lsp

**Comment by ninelore** [comment]
LGTM

**Pull request merged**
