### PR TITLE
linuxHeaders: 5.16 -> 5.17

### PR DESCRIPTION
**Pull request by trofi**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by trofi** [comment]
At leas `audit` will need a fix:

```
audit_wrap.c: In function '_wrap_audit_rule_data_buf_set':
audit_wrap.c:5001:17: error: cast specifies array type
 5001 |     arg1->buf = (char [])(char *)memcpy(malloc((size)*sizeof(char)), (const char *)(arg2), sizeof(char)*(size));
      |                 ^
```

[ ] audit: TODO

**Comment by trofi** [comment]
Both known breakages are fixed in `nixpkgs/staging`. Ready for review.

**Review by fabianhjr — APPROVED** [review]
Diff LGTM

EDIT: Doing a whole system rebuild

**Comment by vcunat** [comment]
@fabianhjr: any issues during the rebuild?

**Comment by fabianhjr** [comment]
Ah, never finished, had to switch to other builds and never restarted it.

I think I built student successfully and about 500 of the 2500ish needed for my gnome nix config.

**Comment by vcunat** [comment]
If I understood `@trofi` right (on some chat), this has got quite a lot of rebuild validation already, so I'll hope it will be fine.

**Comment by trofi** [comment]
Yeah, I tested the build on my system (~3k packages) and against all the top-level attributes that mention linuxHeaders explicily. 

There is still a change that there are non-toplevel attributes, like `python3Packages.<foo>`. But I hope it will be a vanishing minority.

**Comment by vcunat** [comment]
I think some risk remains due to the headers being propagated by glibc, but I guess we'll see and in the worst case revert.

**Pull request merged**
