### PR TITLE
[Backport 18.09] nextcloud module: init

### PR DESCRIPTION
**Pull request by flokli**
###### Motivation for this change
This backports #47159 to 18.09. Filed a separate PR to run tests as suggested by @Mic92 in https://github.com/NixOS/nixpkgs/pull/47159#issuecomment-426828811 . 

I decided to keep the bump to 14.0.1 around, due to that release supporting 2FA and having a "Data Protection Confirmation app and separate audit log file" application.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @eqyiel @fpletz @globin @Ekleog

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg  test nextcloud.basic nextcloud.with-mysql-and-memcached nextcloud.with-postgresql-and-redis

**Comment by samueldr** [comment]
*Haven't looked at the PR in details yet.*

Nextcloud *probably* goes into the security sensitive category for backports; it's often exposed to the whole wild web. Unless it gets an LTS version, or another distro has security patches handy, it will probably always need to be updated in the stable release, so it's easier to apply security updates as needed.

**Comment by flokli** [comment]
@samueldr according to https://nextcloud.com/release-channels/, nextcloud does have a concept of release channels, although they don't explicitly show on the website which version is currently on which channel.

According to the URL above, the latest stable version can be found on the installation page, which is currently pointing to 14.0.1, so we should be good.

**Comment by flokli** [comment]
I did dig a bit deeper into it. Nextclouds updater logic polls some updater server, it's configuration can be found here:
https://github.com/nextcloud/updater_server/blob/master/config/config.php#L106

So basically nextcloud 14.0.1 is also delivered on both "production" and "stable" channels.

**Comment by Ekleog** [comment]
@samueldr Could you confirm whether this is wanted or not?

From my reading of the diff, the risky changes are:
 * Addition of the `nextcloud.nix`: no risk of
   backwards-incompatibility, everything is gated on the `enable` option
 * [Changes to nginx](https://github.com/NixOS/nixpkgs/pull/47859/files#diff-795fa65a7c41a479084de826e4e2e65c),
   likely the part with the highest risk of avoidable
   backwards-incompatibility, it appears to reorder the `location {}`
   blocks in the nginx config
 * Addition of tests… things I think we do want :)
 * Bump of the nextcloud package: this part will certainly be
   backwards-incompatible, but you mentioned that we'd want to bump it
   anyway at the next security update, and so might as well do it
   now. Now, nextcloud 13 appears to still receive updates even now that
   nextcloud 14 is out (cf. the dates in the
   [changelog](https://nextcloud.com/changelog/)), so this part may
   potentially be replaced by a bump to 13.0.7.

**Comment by globin** [comment]
@GrahamcOfBorg test nextcloud.basic nextcloud.with-mysql-and-memcached nextcloud.with-postgresql-and-redis

**Pull request merged**
