### PR TITLE
elementary-cmake-modules: add version

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
Part of #43717

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jtojnar** [comment]
Where does the version number come from? I cannot see it in the repo.

**Comment by worldofpeace** [comment]
[Here](https://github.com/elementary/junk/blob/cmake-modules/debian/changelog), It's retired software and not used centrally anymore. I would remove it from nixpkgs if some applications weren't depending on it.

**Comment by jtojnar** [comment]
The only depending package is regextester. Maybe we should ask them to port to meson.

**Comment by worldofpeace** [comment]
I believe the author of regextester has been unavailable for several months. But an issue wouldn't hurt in case someone wanted to contribute it. :wink:

**Pull request merged**
