### PR TITLE
nixos/security/misc: init

### PR DESCRIPTION
**Pull request by joachifm**
A module for security options that are too small to warrant their own module.

###### Motivation for this change

The impetus for adding this module is to make it more convenient to override
the behavior of the hardened profile wrt user namespaces.
Without a dedicated option for user namespaces, the user needs to
1) know which sysctl knob controls userns
2) know how large a value the sysctl knob needs to allow e.g.,
   Nix sandbox builds to work
Because Nix sandbox support is a likely incompatibility for hardened profile
users, it makes sense to create a dedicated option.

Supercedes https://github.com/NixOS/nixpkgs/pull/48207, resolving the
immediate issue addressed by that PR.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peterhoeg** [comment]
This is nice! Nitpick comment - don't we normally "enable" stuff instead of "disable" like it's done here?

**Comment by joachifm** [comment]
In this case, "disable" sounds better to me because the module doesn't provide user namespaces, it only takes them away.

**Comment by joachifm** [comment]
If disable is too unclear, maybe "remove" or some other wording could be used. I don't want to say `enableUserNamespaces = false` in my config, however, as long as the default is to enable them, if that makes sense.

**Comment by lheckemann** [comment]
I don't like "disable" options, as they result in more layers of negation, which can get pretty confusing. I think an "enable" or maybe better "allow" (since it's less suggestive that the default is not to) option would be better.

**Comment by joachifm** [comment]
Okay, I'll change it to `allowUserNamespaces`

Apart from that, any thoughts on having a module for this compared to just adding the assert to the profile? I'm not sure at present what else could go into this module, but I'm thinking some of the other hardened profile things could be reified as options here, to aid discovery and overriding for users of the profile. But unless that happens, I'm not sure the module is justifiable?

**Comment by DIzFer** [comment]
Ha! I was too slow. I was stuck trying to find the assertions magic. WIll test tomorrow probably :)

While I'm here, have I been living a lie, or is  [ENOSPEC](https://github.com/NixOS/nixpkgs/pull/48439/files#diff-0dda962f1c0c1359f13f9b0c19d68587R21) a typo?

**Comment by joachifm** [comment]
@DIzFer It is a typo, indeed :)

**Review by globin — APPROVED** [review]

**Pull request merged**
