### PR TITLE
openjdk: add infinality patch to improve font-rendering

### PR DESCRIPTION
**Pull request by joelmo**

### CODE REVIEW

**Comment by joelmo** [comment]
@edwtjo

**Comment by edwtjo** [comment]
I'm for it, however, are you the author of the patch?

**Comment by joelmo** [comment]
No, I got it from archs AUR, I forgot maybe I need to attribute the author or do some license thing?

**Comment by edwtjo** [comment]
Yeah, either you fetch the patch or add some source information to it, given that you're not the author.

**Comment by joelmo** [comment]
I added some source information to the patches, do you think this is good enough? I can't find mention of license to this anywhere. Original author appears to be https://github.com/trustin

**Comment by vcunat** [comment]
That seems a good-enough attribution to me.

**Comment by edwtjo** [comment]
Tjusighet fastställd lokalt :) Tackar!

**Comment by joelmo** [comment]
Nicey nicey, tack :)

**Pull request merged**
