### PR TITLE
qutebrowser: patch scripts

### LINKED ISSUE #37307: qutebrowser spellcheck doesn't work
## Issue description
When I run:
```
/nix/store/h8j3b3la9pd0j2a4z5cx1w8k24371jkh-qutebrowser-1.2.0/share/qutebrowser/scripts/dictcli.py install en-US
```
I get:
```
Traceback (most recent call last):
  File "/nix/store/h8j3b3la9pd0j2a4z5cx1w8k24371jkh-qutebrowser-1.2.0/share/qutebrowser/scripts/dictcli.py", line 34, in <module>
    import attr
ModuleNotFoundError: No module named 'attr'
```

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.27-rt21, NixOS, 18.03.git.a619890 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0`
 - channels(bart): `""`
 - channels(root): `"nixos-18.03pre130932.cc4677c36ee"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Motivation for this change
Fix #37307 

###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change (none)
- [x] Tested execution of all scripts
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by magnetophon** [comment]
@rnhmjoj 
Thanks for doing this.

I tried to run
```
/nix/store/h7x5r5rsciscgwp86lnjyh3cyg77h42g-qutebrowser-1.2.0/share/qutebrowser/scripts/dictcli.py install en-US
```
but I got:
```
Installing en-US: English (United States)
/nix/store/cv836804w0lcbmpan1aljzlzq6v3f66z-qtbase-5.10.1/qtwebengine_dictionaries does not exist, creating the directory
Traceback (most recent call last):
  File "/nix/store/h7x5r5rsciscgwp86lnjyh3cyg77h42g-qutebrowser-1.2.0/share/qutebrowser/scripts/dictcli.py", line 281, in <module>
    main()
  File "/nix/store/h7x5r5rsciscgwp86lnjyh3cyg77h42g-qutebrowser-1.2.0/share/qutebrowser/scripts/dictcli.py", line 275, in main
    install(filter_languages(languages, args.language))
  File "/nix/store/h7x5r5rsciscgwp86lnjyh3cyg77h42g-qutebrowser-1.2.0/share/qutebrowser/scripts/dictcli.py", line 232, in install
    install_lang(lang)
  File "/nix/store/h7x5r5rsciscgwp86lnjyh3cyg77h42g-qutebrowser-1.2.0/share/qutebrowser/scripts/dictcli.py", line 220, in install_lang
    os.makedirs(spell.dictionary_dir())
  File "/nix/store/p1bp0kpmxi7nzrla7n7c4waqic0a2myk-python3-3.6.4/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/nix/store/cv836804w0lcbmpan1aljzlzq6v3f66z-qtbase-5.10.1/qtwebengine_dictionaries'
```

Did I run it correctly?
I manually copy-pasted your patch, and might have messed that up.

**Comment by rnhmjoj** [comment]
No, you did nothing wrong. I patched the scripts and they now run but this one is trying to write into the nix store. I'm not sure how to deal with this.

**Comment by rnhmjoj** [comment]
The path it tries to write to is `QLibraryInfo::DataPath`. I'm trying to patch this to use $XDG_DATA_HOME instead.

**Comment by magnetophon** [comment]
@rnhmjoj When I run
``/nix/store/5bd16z932m2x2ndksifsxk7gna600rzv-qutebrowser-1.2.0/share/qutebrowser/scripts/dictcli.py install en-US``

I get
```
Traceback (most recent call last):
  File "/nix/store/5bd16z932m2x2ndksifsxk7gna600rzv-qutebrowser-1.2.0/lib/python3.6/site-packages/qutebrowser/browser/webengine/spell.py", line 43, in dictionary_dir
    path = standarddir.data()
  File "/nix/store/5bd16z932m2x2ndksifsxk7gna600rzv-qutebrowser-1.2.0/lib/python3.6/site-packages/qutebrowser/utils/standarddir.py", line 139, in data
    return _locations[Location.data]
KeyError: <Location.data: 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/5bd16z932m2x2ndksifsxk7gna600rzv-qutebrowser-1.2.0/share/qutebrowser/scripts/dictcli.py", line 281, in <module>
    main()
  File "/nix/store/5bd16z932m2x2ndksifsxk7gna600rzv-qutebrowser-1.2.0/share/qutebrowser/scripts/dictcli.py", line 264, in main
    languages = available_languages()
  File "/nix/store/5bd16z932m2x2ndksifsxk7gna600rzv-qutebrowser-1.2.0/share/qutebrowser/scripts/dictcli.py", line 184, in available_languages
    for code, name in lang_map.items()
  File "/nix/store/5bd16z932m2x2ndksifsxk7gna600rzv-qutebrowser-1.2.0/share/qutebrowser/scripts/dictcli.py", line 185, in <listcomp>
    if code in code2file
  File "<attrs generated init efad0138208ca86f2b346d11f55e255af25a51d5>", line 7, in __init__
  File "/nix/store/5bd16z932m2x2ndksifsxk7gna600rzv-qutebrowser-1.2.0/share/qutebrowser/scripts/dictcli.py", line 67, in __attrs_post_init__
    self.local_filename = spell.local_filename(self.code)
  File "/nix/store/5bd16z932m2x2ndksifsxk7gna600rzv-qutebrowser-1.2.0/lib/python3.6/site-packages/qutebrowser/browser/webengine/spell.py", line 69, in local_filename
    all_installed = local_files(code)
  File "/nix/store/5bd16z932m2x2ndksifsxk7gna600rzv-qutebrowser-1.2.0/lib/python3.6/site-packages/qutebrowser/browser/webengine/spell.py", line 53, in local_files
    pathname = os.path.join(dictionary_dir(), '{}*.bdic'.format(code))
  File "/nix/store/5bd16z932m2x2ndksifsxk7gna600rzv-qutebrowser-1.2.0/lib/python3.6/site-packages/qutebrowser/browser/webengine/spell.py", line 46, in dictionary_dir
    data = os.getenv('XDG_DATA_HOME', default)
NameError: name 'default' is not defined

```

**Comment by rnhmjoj** [comment]
Sorry, I didn't have time to test it yesterday. It should work now.

**Comment by rnhmjoj** [comment]
No, I don't know how it's supposed to work. Maybe the path is hardcoded in qtwebengine...

**Comment by The-Compiler** [comment]
It indeed used to be hardcoded in QtWebEngine - however, [I added a patch to Qt 5.10](https://codereview.qt-project.org/#/c/201422/) to add a `QTWEBENGINE_DICTIONARIES_PATH` environment variable. I haven't had the time to update qutebrowser accordingly yet, though.

So, as soon as NixOS updates to Qt >= 5.10, you should be able to set that to a custom path - until then, I don't think there's anything you can do.

**Comment by rnhmjoj** [comment]
@The-Compiler We actually have Qt 5.10! I tried it and seems to work, thank you.
I will wrap the binary with that variable as soon as I have some time.
I think qutebrowser should set it by default to somewhere in the user directory.

**Comment by The-Compiler** [comment]
Huh, so is https://nixos.org/nixos/packages.html#qtwebengine outdated somehow?

> I think qutebrowser should set it by default to somewhere in the user directory.

I agree, it's currently tracked as part of https://github.com/qutebrowser/qutebrowser/issues/2939 - at that point, it should also be possible to install dictionaries from inside qutebrowser instead of having a separate script. But like I said above, I haven't had time to look at that yet :wink:

**Comment by magnetophon** [comment]
@The-Compiler That link tracks the stable version, not the dev version.
[here](https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/libraries/qt-5/5.10) we have 5.10.

**Comment by rnhmjoj** [comment]
Ok, it should be all set.

**Comment by magnetophon** [comment]
@rnhmjoj Yes, that works!
Thank you!

**Comment by The-Compiler** [comment]
Upstream here - there isn't. I'd be happy to merge a fix, but it'd need to work on older Qt versions as well.

**Comment by rnhmjoj** [comment]
@jtojnar I have split the changes: if you are not sure about the patch at least the python scripts can be fixed by cherry-picking the first commit.

**Comment by jtojnar** [comment]
I think the patch is fine to include into nixpkgs but a PR should be opened upstream and a comment linking to the PR should be added next to the patch. This will make work for maintainers easier in the future.

**Comment by rnhmjoj** [comment]
Yeah sure, I'm planning to do it soon.

**Comment by The-Compiler** [comment]
upstream issue: https://github.com/qutebrowser/qutebrowser/issues/3759

**Comment by magnetophon** [comment]
Any news on this?

**Comment by magnetophon** [comment]
Any news on this?

**Comment by magnetophon** [comment]
To make this work on 1.3.0:
```
--from qutebrowser.utils import log
-+from qutebrowser.utils import log, standarddir
+-from qutebrowser.utils import log, message
++from qutebrowser.utils import log, message, standarddir
```

**Comment by vcanadi** [comment]
@magnetophon Thanks. Finally, a spell checker in qutebrowser on nixos.

**Comment by laMudri** [comment]
[This commit](https://github.com/qutebrowser/qutebrowser/commit/663d1a4d2f2f9d1797a8bb3c745e954f9f3ab4ab#diff-0b7d4d4714522a83b0344aa4c23bd5c8) has changed `dictionary_dir`, and I'm no longer sure what the desired behaviour is.

**Comment by The-Compiler** [comment]
Upstream here - with that commit, at least setting `QTWEBENGINE_DICTIONARIES_PATH` and `dictionaries-path.patch` shouldn't be needed anymore. With Qt >= 5.10, qutebrowser will automatically load dictionaries from `~/.local/share/qutebrowser`, and `dictcli.py` will store them there.

**Comment by rnhmjoj** [comment]
Ok, I removed the last commit.

**Comment by magnetophon** [comment]
@vcanadi Thank you, but I hardly did anything.
This is @rnhmjoj's work!
Thanks @rnhmjoj!

**Review by xeji — APPROVED** [review]

**Comment by magnetophon** [comment]
Great, it's working!
Thanks @rnhmjoj and @xeji !

**Comment by teto** [comment]
I am running qutebrowser with this patch. I was trying to use qute-pass but got this:
 ```
Process stderr:
unable to cache TLDs in file /nix/store/1wm58703hg8y59dfw70lp5abdiq08h0j-python3.6-tldextract-2.2.0/lib/python3.6/site-packages/tldextract/.tld_set: [Errno 30] Read-only file system: '/nix/store/1wm58703hg8y59dfw70lp5abdiq08h0j-python3.6-tldextract-2.2.0/lib/python3.6/site-packages/tldextract/.tld_set'
No pass candidates for URL 'https://www.amazon.com/ap/signin' found!
```
I am not sure if it's an error or warning (not being able to cache tlds should not be an error), in the end I have to rework my pass store to make it work with qute-pass so I am unsure how to proceed.

**Comment by The-Compiler** [comment]
That's not coming from one of qutebrowser's scripts, it's coming from [tldextract](https://pypi.org/project/tldextract/) - see e.g. 
https://github.com/john-kurkowski/tldextract/issues/149. It's just a warning though.

**Pull request merged**
