### PR TITLE
discourse: 2.8.0.beta9 -> 2.8.0.beta10; update plugins

### PR DESCRIPTION
**Pull request by ryantm**
###### Motivation for this change

New version released  https://meta.discourse.org/t/2-8-0-beta10-api-improvements-domain-restricted-invite-links-tab-to-indent-and-more/212780

###### Things done

I deployed this my instances, and checked some plugins work: data-explorer, checklist, LDAP, and calendar.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by talyz — APPROVED** [review]
Looks good to me! I noticed that the build failed on `aarch64-linux`, so I added two updates. One to fix the build and the other to make the tests work when running on a remote builder of a different architecture.

**Comment by ryantm** [comment]
Recently, there was some news about Discourse on the Raspberry Pi https://meta.discourse.org/t/discourse-on-a-raspberry-pi-blog/211357 . Maybe related to why that started failing. Thanks for fixing it!

**Comment by talyz** [comment]
Yeah, that sounds like the cause. It's a bit interesting that we had aarch64 support before upstream, and a bit ironic that we they introduced it, it broke for us :)

**Review by dpausp — APPROVED** [review]
Thanks! Code changes look good to me, upgraded my test system from 2.8.0.beta9 and NixOS Discourse staging is running it, both NixOS 21.11. Tested basic posting functionality, backups and the following plugins: discourse-assign, discourse-canned-replies, discourse-docs, discourse-spoiler-alert, discourse-voting.

**Pull request merged**
