### PR TITLE
aflplusplus: 2.64c -> 2.65c

### PR DESCRIPTION
**Pull request by risicle**
###### Motivation for this change
New release. Fixes some annoying bugs.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @Mindavi

### CODE REVIEW

**Comment by Mindavi** [comment]
Out of curiosity; why remove the cmocka tests?

**Comment by risicle** [comment]
See the commit comment

> i don't think running the unit tests really adds anything given that we have proper integration tests working, and it just introduces another build dependency and possibility for spurious breakage.

**Comment by Mindavi** [comment]
FYI: I did test this as mentioned in my previous comment, so LGTM.

**Comment by risicle** [comment]
Oh cool thanks - my robot brain was just waiting for an "approved" message.

**Pull request merged**
