### PR TITLE
rstudio: fix build

### PR DESCRIPTION
**Pull request by averelld**
###### Motivation for this change
Aliases for hunspell dicts from #65349 in ed060975 make this derivation fail, so we just use unique values. ~~No rebuild, as the old cached result remains valid.~~

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @matthewbauer

### CODE REVIEW

**Review by jonringer — COMMENTED** [review]
`nix-review` passes on NixOS
diff LGTM

Not really related to the goal of the PR but, I don't like the implications of the rstudioWrapper for this package. If someone wants to install RStudio (gui), AND use some of the other binaries, they can't without having package conflicts. 
```
$ nix-env -f ./nixpkgs/ -iA rstudio -iA rstudioWrapper
installing 'RStudio-1.2.1335'
installing 'RStudio-1.2.1335-wrapper'
building '/nix/store/fwnv4i16qngwxw75w4qb3d3ggjxpwp4g-user-environment.drv'...
error: packages '/nix/store/v5avxdcq94ar8m5m93x13zjni5xriqqw-RStudio-1.2.1335-wrapper/bin/rstudio' and '/nix/store/0vsrmdk0x8b9q51bqw0imn18mp2v90hd-RStudio-1.2.1335/bin/rstudio' have the same priority 5; use 'nix-env --set-flag priority NUMBER INSTALLED_PKGNAME' to change the priority of one of the conflicting packages (0 being the highest priority)
builder for '/nix/store/fwnv4i16qngwxw75w4qb3d3ggjxpwp4g-user-environment.drv' failed with exit code 1
error: build of '/nix/store/fwnv4i16qngwxw75w4qb3d3ggjxpwp4g-user-environment.drv' failed
```

I feel like the Wrapped version (at the very least) should be re-exporting the binaries, so that you can do either one or the other, but don't need both

**Comment by averelld** [comment]
The wrapper installs rstudio. I only have `(rstudioWrapper.override { packages = [...]; });` in my config. It also takes an optional rstudio parameter.

**Comment by jonringer** [comment]
I'm referencing the fact that the base rstudio package has an rstudio executable, which can't be ran:

```
$ realpath ./result
/nix/store/0vsrmdk0x8b9q51bqw0imn18mp2v90hd-RStudio-1.2.1335
[01:06:46] jon@jon-desktop /home/jon/projects/nixpkgs (master)
$ ls ./result/bin/
diagnostics  postback  r-ldpath  rpostback  rsession  rstudio  rstudio-backtrace.sh
[01:06:55] jon@jon-desktop /home/jon/projects/nixpkgs (master)
$ ./result/bin/rstudio
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted
```

**Comment by averelld** [comment]
I think it's just not meant to be run that way, you don't have any packages. The plugin wrapping was done in the wrapper even before the recent #65399 stuff too, although I guess that could be moved if there was an actual use-case.

**Comment by eadwu** [comment]
Getting a conflict again, 
```
builder for '/nix/store/3nf2kyld9csrjz8p6l0ik28gz23y6rcy-RStudio-1.2.1335.drv' failed with exit code 1; last 10 log lines:
    inflating: gwt-2.8.1/samples/Showcase/build.xml
  'dependencies/common/dictionaries/de_AT.aff' -> '/nix/store/zkp731a7a3v7rvgkgc373wkdbh842nzj-hunspell-dict-de-at-j3e-20161207/share/hunspell/de_AT.aff'
  'dependencies/common/dictionaries/de_AT.dic' -> '/nix/store/zkp731a7a3v7rvgkgc373wkdbh842nzj-hunspell-dict-de-at-j3e-20161207/share/hunspell/de_AT.dic'
  'dependencies/common/dictionaries/de_CH.aff' -> '/nix/store/nxla8247xk5xrax2hlacqszhw73gjizr-hunspell-dict-de-ch-j3e-20161207/share/hunspell/de_CH.aff'
  'dependencies/common/dictionaries/de_CH.dic' -> '/nix/store/nxla8247xk5xrax2hlacqszhw73gjizr-hunspell-dict-de-ch-j3e-20161207/share/hunspell/de_CH.dic'
  'dependencies/common/dictionaries/de_DE.aff' -> '/nix/store/sycjm22igxvkdhzp0w5ikcrzsx79pra7-hunspell-dict-de-de-j3e-20161207/share/hunspell/de_DE.aff'
  'dependencies/common/dictionaries/de_DE.dic' -> '/nix/store/sycjm22igxvkdhzp0w5ikcrzsx79pra7-hunspell-dict-de-de-j3e-20161207/share/hunspell/de_DE.dic'
  'dependencies/common/dictionaries/en_AU.aff' -> '/nix/store/xqzdp449ypl2s8mwnkhi60abcx8h8rsc-hunspell-dict-en-au-wordlist-2018.04.16/share/hunspell/en_AU.aff'
  'dependencies/common/dictionaries/en_AU.dic' -> '/nix/store/xqzdp449ypl2s8mwnkhi60abcx8h8rsc-hunspell-dict-en-au-wordlist-2018.04.16/share/hunspell/en_AU.dic'
  ln: failed to create symbolic link 'dependencies/common/dictionaries/en_AU.aff': File exists
cannot build derivation '/nix/store/syra6vhk1z8yyrvx6gvr50qlxzchpmx0-RStudio-1.2.1335-wrapper.drv': 1 dependencies couldn't be built
```

**Pull request merged**
