### PR TITLE
pulumi: 2.10.2 -> 2.16.2

### PR DESCRIPTION
**Pull request by mudrii**
###### Motivation for this change
Update pulumi to lates stable  version and update all plugins to the latest version

###### Things done
Update and run the script with new pulumi version and plugins. Add new plugins to pulumi Azure, Kafka and TLS and add myself as maintener.

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

/marvin opt-in
/status needs_merger

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
I fixed your checkboxes.

**Comment by SuperSandro2000** [comment]
Can you please cherry-pick the commit from #105008 over into here? Thanks! This fixes the ofborg error.

**Comment by prusnak** [comment]
https://github.com/NixOS/nixpkgs/pull/105008 has been merged.

Please drop the latter commit and keep only the first one.

**Comment by mudrii** [comment]
> #105008 has been merged.
> 
> Please drop the latter commit and keep only the first one.

commit reset to previouse change

**Comment by mudrii** [comment]
@jlesquembre  @ghuntley @peterromfeldhk Please can you review PR

**Comment by jlesquembre** [comment]
Result of `nixpkgs-review pr 105010` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>pulumi-bin</li>
  </ul>
</details>

**Comment by jlesquembre** [comment]
I tested the executable, looks ok
@mudrii Can you please remove me from the maintainers list? I switched to terraform, I don't use pulumi any longer

**Review by jlesquembre — APPROVED** [review]

**Comment by mudrii** [comment]
@cpcloud Please can you review and merge as I could see a few days back you updated pulumi to the latest version

**Comment by SuperSandro2000** [comment]
@mudrii Please fix the merge conflict.

**Comment by cpcloud** [comment]
Is this PR meaningfully different from #105908?

**Comment by cpcloud** [comment]
Ah I see this is going to 2.15.1!

**Comment by SuperSandro2000** [comment]
@mudrii Please fix the merge conflicts.

**Comment by mudrii** [comment]
> Ah I see this is going to 2.15.1!

@cpcloud I updates to the latest pulumi fix 2.15.4 and update most of the plugins
post rebase conflicts should be fixed

**Review by cpcloud — APPROVED** [review]
LGTM.

**Comment by mudrii** [comment]
can somebody please merge into the master?

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105010` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>pulumi-bin</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105010` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>pulumi-bin</li>
  </ul>
</details>

**Comment by cpcloud** [comment]
This is already out of date now, we should merge it ASAP and get a PR up for the next version.

**Comment by mudrii** [comment]
> This is already out of date now, we should merge it ASAP and get a PR up for the next version.

I will update to a new version

**Comment by cpcloud** [comment]
Thanks @mudrii! @SuperSandro2000 Can we get this merged?

**Comment by mudrii** [comment]
@SuperSandro2000 please can you review and merge?

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 105010` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>pulumi-bin</li>
</ul>
</details>

**Comment by cpcloud** [comment]
@mudrii this can be closed in light of https://github.com/NixOS/nixpkgs/pull/108814

**Pull request closed without merging**
