### PR TITLE
nix: fix  macOS sandbox escape via builtin builders

### PR DESCRIPTION
**Pull request by Mic92**
fixes
https://github.com/NixOS/nix/security/advisories/GHSA-wf4c-57rh-9pjg

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Mic92** [comment]
We will switch this back to released versions of nix as soon as the release process is finished.

**Comment by Mic92** [comment]
https://github.com/NixOS/nix/commit/736298718224de6935af2656eac183593b6afb6a

**Comment by emilazy** [comment]
Building on `aarch64-linux`.

**Comment by emilazy** [comment]
I believe the fallback paths need updating.

**Comment by Mic92** [comment]
> I believe the fallback paths need updating.

We can't update those yet without a release. We can update them after the release. However fallback paths shouldn't be used for a normal system anyway apart from upgrades. and where this issue applies.

**Comment by emilazy** [comment]
I’m confused – the fallback paths just contain Nix store paths that are present in `cache.nixos.org`, right? We can set them to the resulting derivation hashes here (and then set them again when there is a proper release).

**Comment by emilazy** [comment]
Will kick off evals.

**Comment by Mic92** [comment]
We shouldn't point fallback paths to non-existing store paths. That would break things.

**Comment by emilazy** [comment]
Since the advisory is not yet public: no risk at all for Linux?

**Comment by emilazy** [comment]
I’ve queued evaluations for `nixpkgs:trunk` and `nixpkgs:nixpkgs-24.05-darwin`. Won’t do the NixOS jobsets in the absence of indications that this matters on Linux at all (though since those jobsets still build for Linux we can still update the fallback paths when they build).

**Comment by Mic92** [comment]
> Since the advisory is not yet public: no risk at all for Linux?

No.

**Comment by Mic92** [comment]
New nix versions got released. That also means we have fallback paths again.

**Comment by Mic92** [comment]
nix 2.18 is still missing.

**Comment by emilazy** [comment]
Looks like 2.18.9 just got released, so we should be able to bump everything on both release branches. Do you know when we can expect an official advisory and public announcement?

**Comment by emilazy** [comment]
@Mic92 do you plan to open PRs for the release versions / fallback paths?

**Comment by Mic92** [comment]
@emilazy I would appreciate help on bumping the nix versions. The advisory is out, but we have to still write a discourse post for it.

**Comment by Mic92** [comment]
@emilazy https://github.com/NixOS/nixpkgs/pull/352834

**Pull request merged**
