### PR TITLE
pkgs/stdenv/linux: bootstrap-files for third (and final) mips ABI: n32

### PR DESCRIPTION
**Pull request by ghost**
###### Description of changes

This PR provides the Hydra-generated bootstrap tarballs for mips64el-linux-gnuabin32.

With this PR we now have the bootstrap-files for all three little endian ABIs on mips: n64, n32, and o32.  I do not currently plan to do big endian mips unless some motivation arises; all mips chips are bi-endian and Debian has dropped big endian support due to lack of interest.

I'll be following the script used in #151399, #168199, and #183487.

Files came from [this](https://hydra.nixos.org/build/188389586#tabs-summary) Hydra build, which used nixpkgs revision 97d9c84e1df4397b43ecb39359f1bd003cd44585 to instantiate:

```
/nix/store/hakn8s85s9011v61r6svp5qy8x1y64fv-stdenv-bootstrap-tools-mips64el-unknown-linux-gnuabin32.drv
```

and then built:

```
/nix/store/rjgybpnf3yiqyhvl2n2lx31jf800fii2-stdenv-bootstrap-tools-mips64el-unknown-linux-gnuabin32
```

I downloaded these files from Hydra and prefetched them into the nix store with the following commands:

```
STOREPATH=rjgybpnf3yiqyhvl2n2lx31jf800fii2-stdenv-bootstrap-tools-mips64el-unknown-linux-gnuabin32
OPTIONS="--option binary-caches https://cache.nixos.org --option trusted-public-keys cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
nix store prefetch-file \
  file://$(nix store add-file --name bootstrap-tools.tar.xz  $(nix-store ${OPTIONS} -r /nix/store/${STOREPATH})/on-server/bootstrap-tools.tar.xz)
nix store prefetch-file --executable \
  file://$(nix store add-path --name busybox $(nix-store ${OPTIONS} -r /nix/store/${STOREPATH})/on-server/busybox)
```

These commands produced the following output:

```
Downloaded 'file:///nix/store/w6zzd2fx2vhmjfcf5h5zc01m0swldpbw-bootstrap-tools.tar.xz' to '/nix/store/6w0f0mqblrghvh6yjwcb4xdqq9x50lbl-w6zzd2fx2vhmjfcf5h5zc01m0swldpbw-bootstrap-tools.tar.xz' (hash 'sha256-LWrpN6su2yNVurUyhZP34OiZyzgh7MfN13fIIbou8KI=').
Downloaded 'file:///nix/store/nqagw1kgdz1zlmqi00qfjrmwqk3g3bgd-busybox' to '/nix/store/i361xhbdhhnvg7zd637xpm63vbl80s0s-nqagw1kgdz1zlmqi00qfjrmwqk3g3bgd-busybox' (hash 'sha256-4N3G1qYA7vitjhsIW17pR6UixIuzrq4vZXa8F0/X4iI=').
```

I used the hashes from the output above to create the `fetchurl` invocation which is part of this commit.

I then started the bootstrap with the following command:

```
nix build -L -f . --arg localSystem '(import ./lib).systems.examples.mips64el-linux-gnuabin32' hello
```

As @lovesegfault requested, here are the the `sha256sum`s of all the `on-server` components for extra verification:

```
sha256sum /nix/store/${STOREPATH}/on-server/*
```

which produced the following output:

```
2d6ae937ab2edb2355bab5328593f7e0e899cb3821ecc7cdd777c821ba2ef0a2  /nix/store/rjgybpnf3yiqyhvl2n2lx31jf800fii2-stdenv-bootstrap-tools-mips64el-unknown-linux-gnuabin32/on-server/bootstrap-tools.tar.xz
01633f71135cb9ab1b5ce3ebb67e80cbf288739729bffc1350c1552f6f8df34b  /nix/store/rjgybpnf3yiqyhvl2n2lx31jf800fii2-stdenv-bootstrap-tools-mips64el-unknown-linux-gnuabin32/on-server/busybox
```

###### Things done

- Built on platform(s)
  - [x] mips64el-linux-gnuabin32 (`nix build -L hello`)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by amjoseph-nixpkgs** [comment]
@lovesegfault, would you mind uploading these when you get a chance?

**Comment by amjoseph-nixpkgs** [comment]
Ping @lovesegfault

**Comment by lovesegfault** [comment]
I finally recovered my identities to upload this!

One question, you have this going in:

```
nixpkgs-tarballs/stdenv-linux/mips64el/97d9c84e1df4397b43ecb39359f1bd003cd44585
```

But shouldn't it go in `mips64el-n32`?

**Comment by amjoseph-nixpkgs** [comment]
> But shouldn't it go in `mips64el-n32`?

Good point!

Would it be possible to put it in `/n32` like this?

```
nixpkgs-tarballs/stdenv-linux/mips64el/n32/97d9c84e1df4397b43ecb39359f1bd003cd44585
```

that way nobody will think that `n32` is an operating system and `mips64el-n32` is a nix-double (like `aarch64-linux`).

If we aren't supposed to have subdirectories below the `/${cpu}/` level I'll change the PR to use `/mips64el-n32/`.

**Comment by lovesegfault** [comment]
So, looking at the tarballs we currently have there are none with another level of subdir like that, so I'm going to upload this into `mips64el-n32`.

I agree with you that it's confusing, but IMO the entire naming scheme for these is bad, and we should probably just be using the target triple.

**Comment by lovesegfault** [comment]
Alright, they should be there!

```
❯ aws s3 ls --recursive s3://nixpkgs-tarballs/stdenv-linux/mips64el-n32/97d9c84e1df4397b43ecb39359f1bd003cd44585
2023-02-26 13:08:36   16338804 stdenv-linux/mips64el-n32/97d9c84e1df4397b43ecb39359f1bd003cd44585/bootstrap-tools.tar.xz
2023-02-26 13:08:36     246080 stdenv-linux/mips64el-n32/97d9c84e1df4397b43ecb39359f1bd003cd44585/busybox
```

Hashes are correct:

```
❯ aws s3 cp --recursive s3://nixpkgs-tarballs/stdenv-linux/mips64el-n32/97d9c84e1df4397b43ecb39359f1bd003cd44585 ./
download: s3://nixpkgs-tarballs/stdenv-linux/mips64el-n32/97d9c84e1df4397b43ecb39359f1bd003cd44585/busybox to ./busybox
download: s3://nixpkgs-tarballs/stdenv-linux/mips64el-n32/97d9c84e1df4397b43ecb39359f1bd003cd44585/bootstrap-tools.tar.xz to ./bootstrap-tools.tar.xz

❯ sha256sum /nix/store/rjgybpnf3yiqyhvl2n2lx31jf800fii2-stdenv-bootstrap-tools-mips64el-unknown-linux-gnuabin32/on-server/*
2d6ae937ab2edb2355bab5328593f7e0e899cb3821ecc7cdd777c821ba2ef0a2  /nix/store/rjgybpnf3yiqyhvl2n2lx31jf800fii2-stdenv-bootstrap-tools-mips64el-unknown-linux-gnuabin32/on-server/bootstrap-tools.tar.xz
01633f71135cb9ab1b5ce3ebb67e80cbf288739729bffc1350c1552f6f8df34b  /nix/store/rjgybpnf3yiqyhvl2n2lx31jf800fii2-stdenv-bootstrap-tools-mips64el-unknown-linux-gnuabin32/on-server/busybox

❯ sha256sum bootstrap-tools.tar.xz busybox 
2d6ae937ab2edb2355bab5328593f7e0e899cb3821ecc7cdd777c821ba2ef0a2  bootstrap-tools.tar.xz
01633f71135cb9ab1b5ce3ebb67e80cbf288739729bffc1350c1552f6f8df34b  busybox
```

Update the PR with the correct URL and this should be good to go :)

**Comment by lovesegfault** [comment]
@amjoseph-nixpkgs ping :)

**Comment by amjoseph-nixpkgs** [comment]
Reverifying the build to be sure...

**Comment by amjoseph-nixpkgs** [comment]
@ofborg eval

**Comment by amjoseph-nixpkgs** [comment]
This is ready to merge.

**Pull request merged**
