### PR TITLE
xbps: init at 0.52

### PR DESCRIPTION
**Pull request by dtzWill**
- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
Darwin build seems to require a `-Wno-error=...`

**Comment by dtzWill** [comment]
> Darwin build seems to require a -Wno-error=...

Hmm, googling around turned up various things suggesting that `fdatasync` is not actually supported (which is why it's not declared) but it does exist as a symbol in `libSystem`?

* https://bugs.freedesktop.org/show_bug.cgi?id=74873
* https://cmake.org/Bug/print_bug_page.php?bug_id=10044

So my idea was to avoid it on Darwin regardless of what the configure check reports (perhaps the check needs `-Werror` or something?)....

Does that sound good to you?

**Comment by xeji** [comment]
I found similar comments - but of course nothing official by Apple.
Your fix looks good - better not use `fdatasync` at all.

**Comment by xeji** [comment]
Google sez `utimensat`  doesn't exist on Darwin either...

**Comment by dtzWill** [comment]
Okay, great.

Unfortunately maybe disabling `-Werror` is needed regardless?

FWIW others seem to do this, but I was inclined to wait until we had problems to do so ourselves...
* https://git.alpinelinux.org/cgit/aports/tree/community/xbps/disable-Werror.patch
* https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=xbps#n24

I have no idea if xbps is "supposed" to work on Darwin at all anyway, hmm...

**Comment by xeji** [comment]
Well, if `-Werror` gets it to build , why no let people try it. Should crash pretty soon if there's a missing system call.

**Pull request merged**
