### PR TITLE
Update vscode

### PR DESCRIPTION
**Pull request by d-xo**
###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xwvvvvwx** [comment]
Every time I update this package, I have to do the exact same steps every single time. So I wrote a script to automate most of this (it just prints out the various bits of the derivation that need to change), and checked it in as part of this PR. 

Is this OK?

**Comment by jansuchomel** [comment]
The license should remain unfree as the binary version is distributed under [EULA](https://code.visualstudio.com/license).

**Comment by xwvvvvwx** [comment]
Hey, I don't know much about licenses, so more than happy to back out the change, but would really appreciate some more detail.

When I go to the GitHub page it says MIT, what exactly makes this package unfree?

**Comment by fpletz** [comment]
The source is MIT licensed but the pre-built binary from Microsoft that we are using falls under the "MICROSOFT SOFTWARE LICENSE TERMS". It specifically states that "You may not [..] share, publish, or lend the software [..] to any third party", thus making it unfree.

We would have to compile it from source ourselves to create a binary we can distribute freely.

**Comment by 3noch** [comment]
VS Code is currently at 1.10.2 so this PR would be downgrading. Can it be closed?

**Pull request closed without merging**
