### PR TITLE
[WIP] 1password: check binary code signature during build

### PR DESCRIPTION
**Pull request by xeji**
###### Motivation for this change

Check binary code signatures during `checkPhase` using upstream code signing key.
I don't use 1password myself (it's an unfree, commercial service) but the discussion in #42539 prompted me to try this because code signing is a topic that needs more attention in nixpkgs anyway.

cc @jb55 @marsam for testing.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jb55** [comment]
> Check binary code signatures during `checkPhase` using upstream code signing key.

Tested ACK, seems to work. nice!

**Review by jb55 — APPROVED** [review]
👍

**Comment by marsam** [comment]
LGTM 👍

**Comment by matthewbauer** [comment]
:-1: I don't like ad-hoc uses like this. Maybe a setup hook would be better?

**Comment by xeji** [comment]
A setup hook might be a good idea for signed tarballs. In this case, the tarball itself isn't signed but contains a binary and a signature file. I don't see a good generic solution for this.

**Review by puffnfresh — APPROVED** [review]

**Comment by garbas** [comment]
Not in this case, but in case of signed tarbals it would make sense to extend `fetchurl` to also allow checking for signatures, eg:

```nix
fetchurl {
  url = "....";
  sha256 = "....";
  public_key = ./1password.pub.key;
}
```

**Comment by jb55** [comment]
Another question: should we be committing keys to the repo or fetching them? A large number of public keys may take up a decent amount of space over time?

**Comment by xeji** [comment]
In the long run it would be better to fetch and cache them like we do with sources or patches.
But that requires a stable download URL plus an additional step of verifying the key's fingerprint.
Probably  leads to an abstraction like `fetchpubkey` ...

**Comment by matthewbauer** [comment]
> Another question: should we be committing keys to the repo or fetching them? A large number of public keys may take up a decent amount of space over time?

Yes this is definitely a good concern. Also what security does the signature add that the sha256 doesn't have? For both we have to trust that the signature in Nixpkgs is valid & not been tampered with. We should just tell people to verify the signature before updating the sha256 hash outside of Nxpkgs.

**Comment by xeji** [comment]
These things always come down to "you gotta trust something in the beginning". 
 Still better than trusting a sha256 on a TOFU basis because the public keys, as opposed to sha256 hashes, are typically long-term and rarely change. Makes it more likely that attacks will be spotted.

**Comment by jb55** [comment]
Another thing that would be nice:

I'm currently in the process of upgrading the trezor bridge: the release
tagged commit is signed but the hash I'm getting from fetchFromGitHub is
not. I'm trying to re-create the hash with nix-hash without any luck.

It would be cool if there was a way to provide a public key to fetchgit,
which would verify the commit with git-verify-commit after checkout.

**Comment by xeji** [comment]
Using this as an example to create helpers for verifying signed code. I plan to implement a setup hook with some functions for signature verification next.

**Comment by jb55** [comment]
> Using this as an example to create helpers for verifying signed code.
> I plan to implement a setup hook with some functions for signature
> verification next.

awesome!

**Pull request closed without merging**
