### PR TITLE
pdm: 2.19.3 -> 2.22.1

### LINKED ISSUE #352669: Update request: pdm 2.19.3 -> 2.20.1
- Package name: pdm
- Latest released version: 2.20.0.post1

- Current version on the unstable channel: 2.19.3
- Current version on the stable/release channel: 2.15.3

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

---

@cpcloud @natsukium

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by natsukium**
pdm: 2.19.3 -> 2.22.1
- Diff: https://github.com/pdm-project/pdm/compare/refs/tags/2.19.3...2.22.1
- Changelog: https://github.com/pdm-project/pdm/releases/tag/2.22.1

closes https://github.com/NixOS/nixpkgs/issues/352669

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [x] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 353056` at 24245101 run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>:fast_forward: 1 package marked as broken and skipped:</summary>
  <ul>
    <li>ansible-later</li>
  </ul>
</details>
<details>
  <summary>:x: 8 packages failed to build:</summary>
  <ul>
    <li>ansible-lint</li>
    <li>ansible-navigator</li>
    <li>molecule (python312Packages.molecule)</li>
    <li><a href="https://gist.github.com/natsukium/bdf62c9e4fecfd784811e5c9dec30f79">python311Packages.ansible-compat</a></li>
    <li>python311Packages.molecule</li>
    <li>python311Packages.pytest-ansible</li>
    <li><a href="https://gist.github.com/natsukium/937dafc3e390591039b3165e9785f27e">python312Packages.ansible-compat</a></li>
    <li>python312Packages.pytest-ansible</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 16 packages built:</summary>
  <ul>
    <li>ansible (python312Packages.ansible-core)</li>
    <li>ansible_2_15</li>
    <li>ansible_2_16</li>
    <li>mcdreforged</li>
    <li>pdm</li>
    <li>python311Packages.ansible-core</li>
    <li>python311Packages.ansible-kernel</li>
    <li>python311Packages.ansible-runner</li>
    <li>python311Packages.ansible-vault-rw</li>
    <li>python311Packages.pytest-testinfra</li>
    <li>python311Packages.resolvelib</li>
    <li>python312Packages.ansible-kernel</li>
    <li>python312Packages.ansible-runner</li>
    <li>python312Packages.ansible-vault-rw</li>
    <li>python312Packages.pytest-testinfra</li>
    <li>python312Packages.resolvelib</li>
  </ul>
</details>

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 353056` at 24245101 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>:x: 10 packages failed to build:</summary>
  <ul>
    <li>ansible-lint</li>
    <li>ansible-navigator</li>
    <li>molecule (python312Packages.molecule)</li>
    <li><a href="https://gist.github.com/natsukium/33edd0db3b3c5685fd8623a272e87b08">python311Packages.ansible-compat</a></li>
    <li>python311Packages.molecule</li>
    <li>python311Packages.pytest-ansible</li>
    <li><a href="https://gist.github.com/natsukium/e2ca17d7996949cae1110757d1f11a9d">python312Packages.ansible-compat</a></li>
    <li>python312Packages.ansible-kernel</li>
    <li><a href="https://gist.github.com/natsukium/61ab9857c7692475f59e3f5b90261488">python312Packages.ansible-runner</a></li>
    <li>python312Packages.pytest-ansible</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 15 packages built:</summary>
  <ul>
    <li>ansible (python312Packages.ansible-core)</li>
    <li>ansible-later</li>
    <li>ansible_2_15</li>
    <li>ansible_2_16</li>
    <li>mcdreforged</li>
    <li>pdm</li>
    <li>python311Packages.ansible-core</li>
    <li>python311Packages.ansible-kernel</li>
    <li>python311Packages.ansible-runner</li>
    <li>python311Packages.ansible-vault-rw</li>
    <li>python311Packages.pytest-testinfra</li>
    <li>python311Packages.resolvelib</li>
    <li>python312Packages.ansible-vault-rw</li>
    <li>python312Packages.pytest-testinfra</li>
    <li>python312Packages.resolvelib</li>
  </ul>
</details>

**Comment by MisileLab** [comment]
[2.20.1](https://github.com/pdm-project/pdm/releases/tag/2.20.1) out, can you upgrade to it?

**Comment by purepani** [comment]
@natsukium could you bump this to 2.22.1 now?

**Comment by natsukium** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 353056`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>pdm</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>pdm</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>pdm</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>pdm</li>
  </ul>
</details>

**Comment by natsukium** [comment]
closing in favor of #368557

**Pull request closed without merging**
