### PR TITLE
adoptopenjdk: update to latest &  add 14 & 15

### LINKED ISSUE #98784: Request: OpenJDK 15
I am missing version 15 of the `openjdk` package, see https://jdk.java.net/15/

### PR DESCRIPTION
**Pull request by andreoss**
should fix https://github.com/NixOS/nixpkgs/issues/98784

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Can you please follow the commit style described in the contribution guide?

**Comment by andreoss** [comment]
@SuperSandro2000 Done.

**Comment by SuperSandro2000** [comment]
The commit style is ``package: change`` without your ``()``.

**Comment by andreoss** [comment]
@SuperSandro2000 Sorry, misread the requirements. Now it should be fine.

**Comment by gytis-ivaskevicius** [comment]
@SuperSandro2000 ping

**Comment by taku0** [comment]
`adoptopenjdk: 8.0.252 -> 8.0.272, 11.0.7 -> 11.0.9, add 15.0.1, add 14.0.2` would be helpful for later `git log`.

**Comment by andreoss** [comment]
@taku0 Fixed commit message.

**Comment by taku0** [comment]
Please add `stdenv.cc.cc.lib` to `buildInputs` to build 14 and 15.

**Review by taku0 — APPROVED** [review]

**Comment by taku0** [comment]
This requires mass-rebuilds, so please rebase on `staging` branch instead of `master`.

**Review by taku0 — APPROVED** [review]

**Comment by taku0** [comment]
Merged. Thank you!

**Pull request merged**
