### PR TITLE
Don't kill kthreads during bootup

### PR DESCRIPTION
**Pull request by aszlig**
This addresses #15226 and fixes killing of processes before switching from the initrd to the real root.

Right now, the `pkill` that is issued not only kills user space processes but also sends a `SIGKILL` to kernel threads as well. Usually these threads ignore signals, but some of these processes do handle signals, like for example the `md` module, which happened in #15226.

It also adds a small check for the `swraid` installer test and a standalone test which checks on just that problem, so in the future this shouldn't happen again.

Cc: @edolstra, @viric, @dezgeg, @grahamc, @7c6f434c

### CODE REVIEW

**Comment by viric** [comment]
In stage 1 we don't have to avoid killing ourselves, because it is PID 1, init, that cannot be killed.

One typical process that would remain, for example, if not killed is the "tee" process that prefixes every log line with "stage-1-init:" string. That completely deluded me, because adding cmdline "boot.trace" gave me the "set -x" sh with lots of stage-1-init lines which I thought to be COMPLETE until switch_to_root, but they were not. They were there until the kill.

If we could get a COMPLETE log of stage1 with "boot.trace" (not only until kill) it would be great, but maybe topic of another issue.

**Comment by edolstra** [comment]
Wow, I didn't know you could kill kernel processes from user space.

An alternative solution woulf be to only kill known processes that we need to get rid of, e.g. udev. (Are there any others?)

**Comment by edolstra** [comment]
The alternative solution would have the advantage of not requiring a special kernel module in the test, which seems painful to maintain.

**Comment by aszlig** [comment]
@viric: I've added an exempt of the init process just to be absolutely sure, as detailed in 67223ee205364afb203361b134f16b890c4d726c. The kill is shortly before switching to stage 2, so I don't think we need to exempt `tee` from the killing.

@edolstra: Well, there could be plenty of others, anything that goes into the hooks prior to the killing spree. As for the kernel module: The implementation is quite simple and it's not exclusively useful for just stage 1 but for other things during the boot process. I'd keep it to make sure that regardless of this bug we don't kill kernel threads. If the maintenance burden gets too high, we can still drop it.

**Comment by aszlig** [comment]
@edolstra: Btw. if we switch our `initrd` to `systemd` some day, it also kills all of the processes the same way as we have now in this PR (aka: kill everything except kthreads and @-prefixed processes).

**Comment by viric** [comment]
well, you say "killing kthreads", but it's not that they die and disappear. As for the RAID thread case, it's about signaling them.

At some point in history, RAIDs had to be deactivated before poweroff to be properly later activated, but as people started to use rootfs, it was not always possible to deactivate the array, and they thought of the slow safe mode. As most shutdown sequences do a killall, that would hit the kthreads of raid that would put the RAIDs in safemode not requiring the deactivation.

**Comment by viric** [comment]
@aszlig couldn't the tee die just by closing an fd, maybe in stage 2, and we would get the whole log? As for the issue that raised all this, I thought that what put RAID in safe mode was the udev control exit, because that was the last line in the stage1 "set -x" log. I didn't expect that stage1 went further in silence.

**Comment by aszlig** [comment]
@viric: The "killing threads" is not about `md` only, there are other kthreads which do shut down on kill, for example there is `jffs2_gcd_mtd`, which is stopped at `SIGKILL`.

**Comment by viric** [comment]
Ah I didn't know. Good that you mentioned it!

**Comment by aszlig** [comment]
As for `tee`, there is https://github.com/NixOS/nixpkgs/blob/5ac997b8750b2dac56b7ef280870332d761138d9/nixos/modules/system/boot/stage-1-init.sh#L435-L438, which should close the file descriptors.

**Comment by viric** [comment]
right, why not close the descriptors in stage2, for example? Then we have the full stage1 log

**Comment by aszlig** [comment]
@viric: This would involve a lot more work, because we'd need to pause the tee (plus relocate the pipes) when moving the mountpoints to the new root filesystem. I don't think it's worth the effort, because you only gain a few little log lines (if any) which are only for switching to the new root filesystem, and even if we do pause we need to implement buffering while doing that. As this PR is also meant to be backported to stable, it's out of its scope because if we would do that we'll need more extensive testing plus we risk breaking existing systems that run on stable.

**Comment by viric** [comment]
@aszlig Don't worry then. Probably I don't understand all the consequences of that, and it's not the topic of this PR. Let others review this and get it into master and 16.03 (and 15.09? :)

**Comment by cstrahan** [comment]
Interesting. I wonder if that had anything to do with my occasionally broken LUKS bootup: https://github.com/NixOS/nixpkgs/issues/14199

**Pull request merged**
