### PR TITLE
procdump: init at 1.0.1

### LINKED ISSUE #49771: package request 'ProcDump-for-Linux'
https://github.com/Microsoft/ProcDump-for-Linux

I'll try to do this one soon as well

### PR DESCRIPTION
**Pull request by c0bw3b**
###### Motivation for this change

Resolves #49771
/cc @colemickens 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
```
$ sudo procdump -s 1 -M 1 -p4322

ProcDump v1.0.1 - Sysinternals process dump utility
Copyright (C) 2017 Microsoft Corporation. All rights reserved. Licensed under the MIT license.
Mark Russinovich, Mario Hewardt, John Salem, Javid Habibi
Monitors a process and writes a dump file when the process exceeds the
specified criteria.

Process:                firefox (4322)
CPU Threshold:          n/a
Commit Threshold:       >=1
Threshold Seconds:      1
Number of Dumps:        1

Press Ctrl-C to end monitoring without terminating the process.

[23:18:06 - INFO]: Commit: 299 MB
```

where are those stored?

**Comment by dtzWill** [comment]
LGTM! :tada:

**Comment by Mic92** [comment]
yes. upstream should merge this quickly.

**Comment by c0bw3b** [comment]
> where are those stored?

In the current working dir (now that it really works)

```shell
$ sudo procdump -s 1 -M 1 -p 721

ProcDump v1.0.1 - Sysinternals process dump utility
Copyright (C) 2017 Microsoft Corporation. All rights reserved. Licensed under the MIT license.
Mark Russinovich, Mario Hewardt, John Salem, Javid Habibi
Monitors a process and writes a dump file when the process exceeds the
specified criteria.

Process:                nscd (721)
CPU Threshold:          n/a
Commit Threshold:       >=1
Threshold Seconds:      1
Number of Dumps:        1

Press Ctrl-C to end monitoring without terminating the process.

[12:47:26 - INFO]: Commit: 2 MB
[12:47:28 - INFO]: Core dump 1 generated: nscd_commit_2018-11-16_12:47:26.721

$ ll nscd_commit_2018-11-16_12\:47\:26.721 
-rw-r--r-- 1 root root 453609880 16 nov.  12:47 nscd_commit_2018-11-16_12:47:26.721
```

**Comment by dtzWill** [comment]
Submitted sigset fix upstream: https://github.com/Microsoft/ProcDump-for-Linux/pull/50 if you don't mind including :).

**Pull request merged**
