### PR TITLE
monkeys-audio: Fix compilation using an older version of gcc

### PR DESCRIPTION
**Pull request by doronbehar**
Fixes this issue:

> /nix/store/...-gcc-11.2.0/include/c++/11.2.0/cmath:1930:1: error: expected declaration before '}' token
>  1930 | } // extern "C++"
>       | ^

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by RamKromberg** [comment]
1. The tarball seems to have been moved from https://deb-multimedia.org/pool/main/m/monkeys-audio/ to https://deb-multimedia.org/pool/main/m/monkeys-audio-old/ so you're probably pulling an old store copy you had on your machine.
2. Unless I'm mixing things up, it should be ``lib.licenses.unfree``: https://en.wikipedia.org/wiki/Monkey%27s_Audio https://monkeysaudio.com/license.html

**Comment by doronbehar** [comment]
1. Thanks for finding that link. I probably got the tarball from the old link using Hydra's cache.
2. Perhaps the modern version of this software has changed the license. The text of the license file in the downloaded tarball is:

```
                 Monkey's Audio Source Code License Agreement

License Agreement

1. The Monkey's Audio SDK and source code can be freely used to add APE format
playback, encoding, or tagging support to any product, free or commercial.  Use
of the code for proprietary efforts that don't support the official APE format
require written consent of the author.

2. Monkey's Audio source can be included in GPL and open-source software,
although Monkey's Audio itself will not be subjected to external licensing
requirements or other viral source restrictions.

3. Code changes and improvements must be contributed back to the Monkey's Audio
project free from restrictions or royalties for the sake of the common good,
unless exempted by express written consent of the author.

4. Any source code, ideas, or libraries used must be plainly acknowledged in
the software using the code.

5. Although the software has been tested thoroughly, the author is in no way
responsible for damages due to bugs or misuse. 

6. If you do not completely agree with all of the previous stipulations, you
must cease using this source code and remove it from your storage device.

                                        

   All rights not expressly granted here are reserved by Matthew T. Ashland.

                                        

 - All materials and programs copyrighted Â©2000-2006 by Matthew T. Ashland -

                           - All rights reserved. -

```

Sounds sort of free to me, but not LGPL.

**Comment by RamKromberg** [comment]
I'm not a lawyer or a reviewer, but, the limit on "playback, encoding, or tagging support" doesn't cover redistribution (as in, Nix servers catching the sources and/or binaries) or academic research while "although Monkey's Audio itself will not be subjected to external licensing requirements or other viral source restrictions" breaks compatibility with copyleft licenses. So, it's not "free software" or even "open source" for that matter.

Mind you, it's not to say it can't be packaged in nixpkgs. The purpose of the ``unfree`` flag is to tell the Nix servers not to catch the binaries or sources and instead let the users download the sources and compile them on their own per the license terms.

Anyhow, again, I'm not a reviewer or a lawyer so I'm just voicing my personal opinion here.

https://opensource.org/osd
https://en.wikipedia.org/wiki/Copyleft

**Comment by doronbehar** [comment]
> I'm not a lawyer or a reviewer, but, the limit on "playback, encoding, or tagging support" doesn't cover redistribution

Quoting from the 2nd item in the license:

> Monkey's Audio source can be included in GPL and open-source software

And that's exactly what we are doing here in Nixpkgs, so it seems to me.

I think I'll merge it as is. If anyone else feels in the future thinks my decision is incorrect feel free to change the Nix expression, while asking me for a review. Thanks @RamKromberg for voicing your opinion, and most importantly finding the links and suggesting that the license of this software is not trivial.

**Comment by RamKromberg** [comment]
> And that's exactly what we are doing here in Nixpkgs, so it seems to me.

``included in GPL and open-source software`` doesn't mean you're explicitly allowed to redistribute the source. It could mean as little as including it yourself for your own use, per clause 1. As in, download the tarball, unpack it and ``#include`` the headers in your own software, that you yourself run and use, for playback, encoding, or tagging. Which is what ``unfree`` does.

Regardless, the part about ``will not be subjected to external licensing requirements or other viral source restrictions`` breaks the GPL: [clause 2.b. of the GPLv2](https://tldrlegal.com/license/gnu-general-public-license-v2#fulltext) states that ``You must cause any work that you distribute or publish, that in whole or in part contains or is derived from the Program or any part thereof, to be licensed as a whole at no charge to all third parties under the terms of this License.``. So, even if Monkey's Audio own license isn't being violated here, by explicitly rejecting being ``subjected to external licensing requirements``, it has the user violate the GPL license of the software that includes Monkey's Audio.

IMHO, all this legalese headache is why Monkey's Audio isn't being binary redistributed by Gentoo, Debian, Arch and/or Ubuntu and is being source cached externally via [deb-multimedia.org](http://deb-multimedia.org): When a license takes lawyers to make sense of and didn't go through the FSF or the OSI, even if it might be free and you trust the developer, the safe thing to do is just to assume it's not free and let downstream pull in the tarballs and build it on their own.

Anyhow, I doubt any of this matters after all these years of nothing happening... Still, just my 2-cents.

**Comment by RamKromberg** [comment]
> I don't know what to do :tipping_hand_man:. At least now the package compiles

Yup. At least it's working.

> there's the port available at https://github.com/fernandotcl/monkeys-audio

Well, from the author's own lips: ``This port is based on Monkey's Audio Codec version 3.99 and integrates patches for [shntool](http://www.etree.org/shnutils/shntool/) compatibility. Silly licensing restrictions have hampered the development of a healthy ecosystem around this codec. Using it for anything other than decoding existing files is thus discouraged.``.

So, pretty sketchy.

Incidentally, if you want to split an ape by cue, you can just losslessly covert it to wav first using ``ffmpeg -i input.ape input.wav`` before invoking ``shnsplit -f input.cue input.wav``. Bonus points for tossing ``mktemp -d`` in there to avoid the disk thrashing.

> We should also consider packaging the latest version

[freac](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/audio/freac) could use Monkey's Audio. But, you'll need to do as an optional nix override since hydra won't build it. Btw, freac doesn't directly includes Monkey's Audio and other similar codecs in their sources either:
https://github.com/enzo1982/freac/blob/master/tools/build-codecs#L177
https://github.com/enzo1982/freac/blob/master/tools/build-codecs#L540

All in all, none of this is a big deal really. Nixpkgs has plenty of ``unfree`` codecs for video, audio and images and many of them require local builds and/or non-catch sourcing via overrides.

**Pull request merged**
