### PR TITLE
nmap: 7.80 -> 7.91

### PR DESCRIPTION
**Pull request by fpletz**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
FYI `nmap-unfree` is at 7.91 because of some licensing stuff. Not sure about the current state though. If we want to update `pkgs.nmap` we should get rid of the `nmap-unfree` expression IMHO.

**Comment by fpletz** [comment]
Sigh, okay. Then let's close.

**Comment by fpletz** [comment]
Ok, we cam do it after all. Let's reopen.

https://nmap.org/npsl/ states:
> Note that some releases of Nmap may fall under a previous version of this license, or a different license entirely. The exact terms for a given version of Nmap can be found in the included LICENSE or COPYING file. To ease the transition to the NPSL, the first two Nmap releases made under that license (Nmap 7.90 and 7.91) may also be used under the previous Nmap license terms by anyone who prefers those. 

So we could remove nmap-unfree for now. :)

**Comment by Ma27** [comment]
@fpletz ahh nice, just wanted to point out that `nmap` used to be on 7.80 for a reason, but didn't look into the current state :) 

I guess it makes sense then to add an alias from `nmap-unfree` to `nmap` in `aliases.nix`, correct?

**Comment by fpletz** [comment]
And closing again. Merged this instead: https://github.com/NixOS/nixpkgs/pull/118158

**Pull request closed without merging**
