### PR TITLE
libvirt: darwin/linux fix dlopen("libjansson.so.4")

### PR DESCRIPTION
**Pull request by teto**
###### Motivation for this change

Commit 59027e28800dd5c2cd1c9d434c1a71d39be19266 broke libvirt
 Revert "libvirt: fix dlopen("libjansson.so.4")" 

broke libvirt/nixops on linux :/ I am not sure what's the proper fix but meanwhile could we wrap the change in an if darwin ?

cf
https://github.com/NixOS/nixpkgs/pull/44900

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by teto** [comment]
@pikajude what do you think ? I don't have darwin either and it's a runtime issue so ofborg won't help.

**Comment by LnL7** [comment]
https://github.com/NixOS/nixpkgs/pull/44900#issuecomment-413314095

**Comment by teto** [comment]
@LnL7 Does that mean replace `.so` with `targetPlatform.extensions.sharedLibrary` ?

**Comment by teto** [comment]
The commit #44900 was purely reverted so I assumed libjansson was not mandatory for darwin else I don't see the point in the revert it just broke libvirt on both platforms. Also don't assume everyone is familiar with every bit of nixpkgs it's the first time I come across ${targetPlatform.extensions.sharedLibrary} hence my question, I am just trying to help here (as you are).

**Comment by teto** [comment]
I pushed your fix, it is fine on linux. Hope some macos user can test it too

**Comment by flokli** [comment]
@teto was able to build it on darwin, start libvirtd, and it kept running.
I was also able to connect via virsh to a remote system, and could instruct libvirt commands there - so nixopsing should work too after this is merged.

Note: I could connect to the locally started libvirtd as well, but wasn't able to define any domains - libvirt kept complaining it couldn't find capabilities for domaintype=qemu - unsure if running qemu with darwin as host ever worked, so this should be fine for now.

**Comment by LnL7** [comment]
@teto I wasn't talking about the sharedLibrary helper specifically, `if ... then "dylib" else "so"`, while not as nice will do the same thing. I'm just a bit confused why there's so much discussion about something that almost looks easier to fix then revert.

Just disabling the fix on darwin wouldn't break nixops anymore, but I assume (since it builds on darwin) you could run into the same problem there.

**Comment by LnL7** [comment]
@GrahamcOfBorg build libvirt

**Review by LnL7 — APPROVED** [review]

**Pull request merged**
