### PR TITLE
incus: 6.6.0 -> 6.7.0

### PR DESCRIPTION
**Pull request by bbigras**
https://github.com/lxc/incus/releases/tag/v6.7.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by adamcstephens** [comment]
I'm moving this to draft just so nobody else merges it. The virtual-machine test is working on master so this upgrade may in fact be problematic. 

There is at least one change in the TPM support in the release notes. If you could do some troubleshooting it'd be appreciated, as I'm short on capacity right now. If not, please be patient.

I'll also note that upstream doesn't normally release point patches for the non-lts line, so if there is a problem we may have to accept it or wait for the next release.

**Review by adamcstephens — APPROVED** [review]
x86
```
❯ nom-build -A incus.passthru.tests -A incus-lts.passthru.tests
/nix/store/9x2pkp9izvrgzlxjnw0way51hgbkzpah-vm-test-run-container-legacy-init
/nix/store/7x5sqdm3xk8c9sw0x41wql57p5dprr0w-vm-test-run-container-systemd-init
/nix/store/mfv9ziqf6bkbk837qgxx7zidrac9f9am-vm-test-run-incusd-options
/nix/store/9ry3qzqxsr96l488ikviax0hs0lwbfpr-vm-test-run-lxd-to-incus
/nix/store/9mlxv8c3lpyclxz27zbki9assxfj7nwz-vm-test-run-incus-openvswitch
/nix/store/arqy253i9z9j5vchp58mfzfswx9h3ccg-vm-test-run-incus-socket-activated
/nix/store/qkgk1va7m1lqfqkxxi032by8xrw4m4hk-vm-test-run-incus-storage
/nix/store/chnkn4a349xqkmlnq0rrmff94gql27af-vm-test-run-incus-ui
/nix/store/njskd2wnl92n72r7f4ncrcc7r5yg3b9d-vm-test-run-incus-virtual-machine
/nix/store/52q0zsyl0jph3n2n7j4lsf4sjhq5jb8f-vm-test-run-container-legacy-init
/nix/store/r448id3ij89pvybaybxy3x95qjv0gn54-vm-test-run-container-systemd-init
/nix/store/20ywj84ilf8w5w3hg29x2gp6s5c0lqs0-vm-test-run-incusd-options
/nix/store/5qdah7bqlg6nlmnx1l6k8fi8j2vwl4gi-vm-test-run-lxd-to-incus
/nix/store/299bdcwv2sj2qwvqi8k9l4ncrpg4kww6-vm-test-run-incus-openvswitch
/nix/store/d3jv75a9pva548gy85h3md01ihvjgzcn-vm-test-run-incus-socket-activated
/nix/store/vajpm7zahsqavyh9yd41vr53lhvdgsf6-vm-test-run-incus-storage
/nix/store/2241aypkybjm6x712idik9wh1ccdqbh0-vm-test-run-incus-ui
/nix/store/h0dilbaykhynmhh39ffrcqn80q735d2d-vm-test-run-incus-virtual-machine
```

aarch64
```
❯ nom-build -A incus.passthru.tests -A incus-lts.passthru.tests --argstr system aarch64-linux
/nix/store/8d96r8ksklr3sm7sx9pqk04s1a4bgbba-vm-test-run-container-legacy-init
/nix/store/ifxfnxa66bn658c9bhgx0rqg629f5xi6-vm-test-run-container-systemd-init
/nix/store/fz6rv4w8gg9g8bili90l3smhwyjv3xav-vm-test-run-incusd-options
/nix/store/qhlydfyrgizzkqicdd3px2xyg5jdmga2-vm-test-run-lxd-to-incus
/nix/store/q6miqd50cb0dbz4z7mciqc1jxsa8mxd9-vm-test-run-incus-openvswitch
/nix/store/apm5a453ygrij6h8679f18zh5az58124-vm-test-run-incus-socket-activated
/nix/store/f5pijb2903hyjjxqwddihdkglpaxmfqa-vm-test-run-incus-storage
/nix/store/1nr0ylplg4lsagxjamhnlas01cqh3inf-vm-test-run-incus-ui
/nix/store/vfwi47p7mbb4zg9bwvh3w0grcsbjb63p-vm-test-run-container-legacy-init
/nix/store/rblyrsg5arhfcqnaw7kk2yw6yy35prbr-vm-test-run-container-systemd-init
/nix/store/xr1dgvxfqmfr0m40fy83227jzfsybjj8-vm-test-run-incusd-options
/nix/store/cranqdr0cyyznzykz3r1x8rhghqcw189-vm-test-run-lxd-to-incus
/nix/store/2h2gsnjv2sj67vrcq6j204h92hc213fv-vm-test-run-incus-openvswitch
/nix/store/v2lqgkcakg2wzmc8r5xlmfl9044cgb3c-vm-test-run-incus-socket-activated
/nix/store/w7df0fx6znnlhmlhnxzcv1yai3rl9w9j-vm-test-run-incus-storage
/nix/store/0s1pz15njjwfd5dyzqhlcpfbxzzvi78l-vm-test-run-incus-ui
```

**Comment by bbigras** [comment]
Thank you very much.

**Comment by adamcstephens** [comment]
I’ll need to report the issue upstream, but reverting that PR fixed the issue.

**Pull request merged**
