### PR TITLE
factorio-experimental, factorio-headless-experimental: 1.1.2 -> 1.1.3

### PR DESCRIPTION
**Pull request by lukegb**
###### Motivation for this change

https://forums.factorio.com/92314

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lukegb** [comment]
Note that this includes #105296, since having written an update script I'm obviously going to use it :P

**Comment by SuperSandro2000** [comment]
> Note that this includes #105296, since having written an update script I'm obviously going to use it :P

Just merged that. Can you do a rebase?

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105471` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>factorio-experimental</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>factorio-headless-experimental</li>
  </ul>
</details>

**Comment by lukegb** [comment]
Rebased.

**Review by erictapen — APPROVED** [review]
Builds for me.

**Pull request merged**
