### PR TITLE
dbeaver: 7.3.2 -> 7.3.5, build from source and add darwin build

### PR DESCRIPTION
**Pull request by jojosch**
###### Motivation for this change

I finally got around to building dbeaver from source (resolving #34182). Here one problem occurred: maven needs JDK 11 as the jdk dependency to fix:

```
error: org/eclipse/tycho/core/p2/P2ArtifactRepositoryLayout has been compiled 
by a more recent version of the Java Runtime (class file version 55.0), this version 
of the Java Runtime only recognizes class file versions up to 52.0
```

Using JDK < 15 also fixes the build because `AlgorithmId.md5WithRSAEncryption_oid` was removed with JDK 15 and #107547 did update the default JDK to version 15:

```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:2.0.0:compile (default-compile) on project org.jkiss.dbeaver.model: Compilation failure: Compilation failure:
[ERROR] /build/source/plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/app/CertificateGenHelper.java:[69]
[ERROR] 	AlgorithmId algo = new AlgorithmId(AlgorithmId.md5WithRSAEncryption_oid);
[ERROR] 	                                               ^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] md5WithRSAEncryption_oid cannot be resolved or is not a field
```

-------------------

In addition, I've included some modifications for a macOS build (resolving #98631), since I have access to a Mac for a short time.

Could someone more familiar with the macOS side of things check my changes?

-------------------

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS (nix-build and run the .../MacOS/dbeaver Mach-O exe) - idk how to add the resulting Application to "Applications"
   - [x] other Linux distributions (Ubuntu 20.10)
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
```
/nix/store/7r66lj6a84c94m9rp1wmcnd562gg0f0f-dbeaver-ce-7.3.2	 1461069608 (from source)
/nix/store/y1gihgszwbn7g4mgs6lcz8rjgnkhsq0i-dbeaver-ce-7.3.2	 1463280536 (from tarball)
/nix/store/vcdjp7ihjl5928s6q9c82lf17aky5m56-dbeaver-ce-7.3.3	 1318132560 (from source)
/nix/store/yxgbd9nzibm5cc2ra8158az8dv0iq36l-dbeaver-ce-7.3.2	 403813864 (macOS)
```
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by samueldr** [comment]
Nice!

I did not test *in depth*, but ran it on the machine I used it previously, it picked up the old profile and worked just as expected.

Good work on figuring out a scheme to make the maven calls reproducible.

For fun I tried to run it on aarch64-linux, the maven artifacts were verified to fetch reproducibly, but a dependency isn't yet available for aarch64, so that didn't work for the time being. (https://github.com/dbeaver/dbeaver/issues/7606)

I haven't taken the time to look at the changes in depth either, but as far as the end-product working, it seems to work just fine.

**Comment by jojosch** [comment]
Updated to latest release https://dbeaver.io/2021/01/31/dbeaver-7-3-4/

**Comment by jojosch** [comment]
Updated to latest release https://dbeaver.io/2021/02/14/dbeaver-7-3-5/

**Comment by aanderse** [comment]
Any reason to wait on merging this? @samueldr want to press merge?

**Comment by samueldr** [comment]
I was hoping that someone else who knew more about the Java ecosystem would chime in, or to have other approvals along the way... And I forgot about it after the initial look.

**Comment by jojosch** [comment]
@samueldr thanks for merging :)

The two linked issues (#34182, #98631) do not appear to have been automatically closed. Maybe because i used "resolving XX" instead of "resolves/fixes XX" in the PR description?

**Comment by samueldr** [comment]
I'm not sure, but that's likely. Github tells you somewhere in the UI which issues will be closed, when the messages are formatted "correctly". I generally end-up making a list like what follows, otherwise Github sometimes doesn't do the right thing.

```markdown
 - Fixes #xxx
 - Fixes #xxy
```

**Pull request merged**
