### PR TITLE
python311Packages.cvxopt: use LP64 blas on darwin; fix build

### PR DESCRIPTION
**Pull request by ghost**
darwin builds were using the ILP64 openblas library which causes the build to segufault in the unittests, which might be why the unit tests were disabled on darwin.

ILP64 is [unsupported](https://github.com/cvxopt/cvxopt/issues/169#issuecomment-647091432) so it was a bug for darwin to use it in the first place.

this change aligns darwin to the linux build to use LP64 blas / lapack libraries. this also aligns with the assert at the top of the file which asserts blas and lapack are LP64. [nixpkgs blas & lapack point to openblasCompat which is the openblas LP64](https://nixos.org/manual/nixpkgs/unstable/index.html#sec-overlays-alternatives-blas-lapack), the opeblas package is ILP64. numpy and most (all) other math python packages require LP64.

the darwin unit test is enabled and now passes after this change as do the consumers of this package which were segfaulting in their unit tests.

Fixes: https://github.com/NixOS/nixpkgs/issues/271105
ZHF: #265948
https://hydra.nixos.org/build/241904734
note: the hydra failure is for python311Packages.cvxpy but that is just because it's unit tests run and were segfaulting in cvxopt

Result of `nixpkgs-review pr 270016` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>33 packages marked as broken and skipped:</summary>
  <ul>
    <li>labplot</li>
    <li>python310Packages.pot</li>
    <li>python310Packages.pot.dist</li>
    <li>python310Packages.qiskit</li>
    <li>python310Packages.qiskit-aer</li>
    <li>python310Packages.qiskit-aer.dist</li>
    <li>python310Packages.qiskit-finance</li>
    <li>python310Packages.qiskit-finance.dist</li>
    <li>python310Packages.qiskit-ibmq-provider</li>
    <li>python310Packages.qiskit-ibmq-provider.dist</li>
    <li>python310Packages.qiskit-ignis</li>
    <li>python310Packages.qiskit-ignis.dist</li>
    <li>python310Packages.qiskit-nature</li>
    <li>python310Packages.qiskit-nature.dist</li>
    <li>python310Packages.qiskit-optimization</li>
    <li>python310Packages.qiskit-optimization.dist</li>
    <li>python310Packages.qiskit.dist</li>
    <li>python311Packages.pot</li>
    <li>python311Packages.pot.dist</li>
    <li>python311Packages.qiskit</li>
    <li>python311Packages.qiskit-aer</li>
    <li>python311Packages.qiskit-aer.dist</li>
    <li>python311Packages.qiskit-finance</li>
    <li>python311Packages.qiskit-finance.dist</li>
    <li>python311Packages.qiskit-ibmq-provider</li>
    <li>python311Packages.qiskit-ibmq-provider.dist</li>
    <li>python311Packages.qiskit-ignis</li>
    <li>python311Packages.qiskit-ignis.dist</li>
    <li>python311Packages.qiskit-nature</li>
    <li>python311Packages.qiskit-nature.dist</li>
    <li>python311Packages.qiskit-optimization</li>
    <li>python311Packages.qiskit-optimization.dist</li>
    <li>python311Packages.qiskit.dist</li>
  </ul>
</details>
<details>
  <summary>28 packages built:</summary>
  <ul>
    <li>python310Packages.cvxopt</li>
    <li>python310Packages.cvxopt.dist</li>
    <li>python310Packages.cvxpy</li>
    <li>python310Packages.cvxpy.dist</li>
    <li>python310Packages.osqp</li>
    <li>python310Packages.osqp.dist</li>
    <li>python310Packages.picos</li>
    <li>python310Packages.picos.dist</li>
    <li>python310Packages.qpsolvers</li>
    <li>python310Packages.qpsolvers.dist</li>
    <li>python310Packages.qutip</li>
    <li>python310Packages.qutip.dist</li>
    <li>python310Packages.scikit-survival</li>
    <li>python310Packages.scikit-survival.dist</li>
    <li>python311Packages.cvxopt</li>
    <li>python311Packages.cvxopt.dist</li>
    <li>python311Packages.cvxpy</li>
    <li>python311Packages.cvxpy.dist</li>
    <li>python311Packages.osqp</li>
    <li>python311Packages.osqp.dist</li>
    <li>python311Packages.picos</li>
    <li>python311Packages.picos.dist</li>
    <li>python311Packages.qpsolvers</li>
    <li>python311Packages.qpsolvers.dist</li>
    <li>python311Packages.qutip</li>
    <li>python311Packages.qutip.dist</li>
    <li>python311Packages.scikit-survival</li>
    <li>python311Packages.scikit-survival.dist</li>
  </ul>
</details>

<hr>

Result of `nixpkgs-review pr 270016` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>28 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.qiskit</li>
    <li>python310Packages.qiskit-aer</li>
    <li>python310Packages.qiskit-aer.dist</li>
    <li>python310Packages.qiskit-finance</li>
    <li>python310Packages.qiskit-finance.dist</li>
    <li>python310Packages.qiskit-ibmq-provider</li>
    <li>python310Packages.qiskit-ibmq-provider.dist</li>
    <li>python310Packages.qiskit-ignis</li>
    <li>python310Packages.qiskit-ignis.dist</li>
    <li>python310Packages.qiskit-nature</li>
    <li>python310Packages.qiskit-nature.dist</li>
    <li>python310Packages.qiskit-optimization</li>
    <li>python310Packages.qiskit-optimization.dist</li>
    <li>python310Packages.qiskit.dist</li>
    <li>python311Packages.qiskit</li>
    <li>python311Packages.qiskit-aer</li>
    <li>python311Packages.qiskit-aer.dist</li>
    <li>python311Packages.qiskit-finance</li>
    <li>python311Packages.qiskit-finance.dist</li>
    <li>python311Packages.qiskit-ibmq-provider</li>
    <li>python311Packages.qiskit-ibmq-provider.dist</li>
    <li>python311Packages.qiskit-ignis</li>
    <li>python311Packages.qiskit-ignis.dist</li>
    <li>python311Packages.qiskit-nature</li>
    <li>python311Packages.qiskit-nature.dist</li>
    <li>python311Packages.qiskit-optimization</li>
    <li>python311Packages.qiskit-optimization.dist</li>
    <li>python311Packages.qiskit.dist</li>
  </ul>
</details>
<details>
  <summary>48 packages built:</summary>
  <ul>
    <li>cantor (libsForQt5.cantor ,plasma5Packages.cantor)</li>
    <li>labplot</li>
    <li>python310Packages.bambi</li>
    <li>python310Packages.bambi.dist</li>
    <li>python310Packages.blackjax</li>
    <li>python310Packages.blackjax.dist</li>
    <li>python310Packages.cvxopt</li>
    <li>python310Packages.cvxopt.dist</li>
    <li>python310Packages.cvxpy</li>
    <li>python310Packages.cvxpy.dist</li>
    <li>python310Packages.jaxopt</li>
    <li>python310Packages.jaxopt.dist</li>
    <li>python310Packages.osqp</li>
    <li>python310Packages.osqp.dist</li>
    <li>python310Packages.picos</li>
    <li>python310Packages.picos.dist</li>
    <li>python310Packages.pot</li>
    <li>python310Packages.pot.dist</li>
    <li>python310Packages.qpsolvers</li>
    <li>python310Packages.qpsolvers.dist</li>
    <li>python310Packages.qutip</li>
    <li>python310Packages.qutip.dist</li>
    <li>python310Packages.scikit-survival</li>
    <li>python310Packages.scikit-survival.dist</li>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
    <li>python311Packages.blackjax</li>
    <li>python311Packages.blackjax.dist</li>
    <li>python311Packages.cvxopt</li>
    <li>python311Packages.cvxopt.dist</li>
    <li>python311Packages.cvxpy</li>
    <li>python311Packages.cvxpy.dist</li>
    <li>python311Packages.jaxopt</li>
    <li>python311Packages.jaxopt.dist</li>
    <li>python311Packages.osqp</li>
    <li>python311Packages.osqp.dist</li>
    <li>python311Packages.picos</li>
    <li>python311Packages.picos.dist</li>
    <li>python311Packages.pot</li>
    <li>python311Packages.pot.dist</li>
    <li>python311Packages.qpsolvers</li>
    <li>python311Packages.qpsolvers.dist</li>
    <li>python311Packages.qutip</li>
    <li>python311Packages.qutip.dist</li>
    <li>python311Packages.scikit-survival</li>
    <li>python311Packages.scikit-survival.dist</li>
    <li>sage</li>
    <li>sageWithDoc</li>
  </ul>
</details>

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by a-n-n-a-l-e-e** [comment]
@NixOS/nixos-release-managers

**Review by pbsds — APPROVED** [review]
Diff LGTM, don't have a mac to test on

**Comment by a-n-n-a-l-e-e** [comment]
@emilytrau if you have a chance to look at this, i'm trying to get this package in as it silently (and not so silently) breaks a bunch of consumers on darwin. thx!

**Comment by emilytrau** [comment]
Result of `nixpkgs-review pr 270016` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>32 packages marked as broken and skipped:</summary>
  <ul>
    <li>python310Packages.pot</li>
    <li>python310Packages.pot.dist</li>
    <li>python310Packages.qiskit</li>
    <li>python310Packages.qiskit-aer</li>
    <li>python310Packages.qiskit-aer.dist</li>
    <li>python310Packages.qiskit-finance</li>
    <li>python310Packages.qiskit-finance.dist</li>
    <li>python310Packages.qiskit-ibmq-provider</li>
    <li>python310Packages.qiskit-ibmq-provider.dist</li>
    <li>python310Packages.qiskit-ignis</li>
    <li>python310Packages.qiskit-ignis.dist</li>
    <li>python310Packages.qiskit-nature</li>
    <li>python310Packages.qiskit-nature.dist</li>
    <li>python310Packages.qiskit-optimization</li>
    <li>python310Packages.qiskit-optimization.dist</li>
    <li>python310Packages.qiskit.dist</li>
    <li>python311Packages.pot</li>
    <li>python311Packages.pot.dist</li>
    <li>python311Packages.qiskit</li>
    <li>python311Packages.qiskit-aer</li>
    <li>python311Packages.qiskit-aer.dist</li>
    <li>python311Packages.qiskit-finance</li>
    <li>python311Packages.qiskit-finance.dist</li>
    <li>python311Packages.qiskit-ibmq-provider</li>
    <li>python311Packages.qiskit-ibmq-provider.dist</li>
    <li>python311Packages.qiskit-ignis</li>
    <li>python311Packages.qiskit-ignis.dist</li>
    <li>python311Packages.qiskit-nature</li>
    <li>python311Packages.qiskit-nature.dist</li>
    <li>python311Packages.qiskit-optimization</li>
    <li>python311Packages.qiskit-optimization.dist</li>
    <li>python311Packages.qiskit.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python310Packages.qutip</li>
    <li>python310Packages.qutip.dist</li>
    <li>python311Packages.qutip</li>
    <li>python311Packages.qutip.dist</li>
  </ul>
</details>
<details>
  <summary>24 packages built:</summary>
  <ul>
    <li>python310Packages.cvxopt</li>
    <li>python310Packages.cvxopt.dist</li>
    <li>python310Packages.cvxpy</li>
    <li>python310Packages.cvxpy.dist</li>
    <li>python310Packages.osqp</li>
    <li>python310Packages.osqp.dist</li>
    <li>python310Packages.picos</li>
    <li>python310Packages.picos.dist</li>
    <li>python310Packages.qpsolvers</li>
    <li>python310Packages.qpsolvers.dist</li>
    <li>python310Packages.scikit-survival</li>
    <li>python310Packages.scikit-survival.dist</li>
    <li>python311Packages.cvxopt</li>
    <li>python311Packages.cvxopt.dist</li>
    <li>python311Packages.cvxpy</li>
    <li>python311Packages.cvxpy.dist</li>
    <li>python311Packages.osqp</li>
    <li>python311Packages.osqp.dist</li>
    <li>python311Packages.picos</li>
    <li>python311Packages.picos.dist</li>
    <li>python311Packages.qpsolvers</li>
    <li>python311Packages.qpsolvers.dist</li>
    <li>python311Packages.scikit-survival</li>
    <li>python311Packages.scikit-survival.dist</li>
  </ul>
</details>

**Review by emilytrau — APPROVED** [review]
Nice work!

**Comment by a-n-n-a-l-e-e** [comment]
woot! thanks!

**Pull request merged**
