### PR TITLE
podman, etc packages: fix/update inputs/tags

### PR DESCRIPTION
**Pull request by zowoq**
~~Draft as I want to go over this again before it gets merged.~~

This adds/fixes/updates inputs and (inferred) build tags.

`libassuan` and `libgpgerror` are propagated by `gpgme`.

Add `libapparmor` and `libselinux` to most things.

Since `ostree` has been removed from `skopeo`, `libselinux` can be removed.

### CODE REVIEW

**Comment by zowoq** [comment]
@ofborg test podman docker-tools

**Review by saschagrunert — APPROVED** [review]
LGTM

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Comment by zowoq** [comment]
This is already conflicted so I'll wait until #86378 is merged and then rebase.

**Pull request merged**
