### PR TITLE
notmuch-bower: init at 2017-09-27

### PR DESCRIPTION
**Pull request by erictapen**
###### Motivation for this change

This adds the `bower` MUA, which I may use in the future.

The reason why I didn't use the latest version `0.8` but the most recent commit wangp/bower@ff95a1eb709ba998913a78b6bf7c50ef4ed480af is, that this commit introduces man pages. Therefore, the package version `2017-08-05` is the date of that commit.

###### Things done

Added `bower` package and added `erictapen` as maintainer.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by erictapen** [comment]
Now it looks good...

**Comment by orivej** [comment]
I've improved your package in https://github.com/NixOS/nixpkgs/pull/29856/commits/61bb2d44ef7c0bad1dc039fad7fced516128f7bc

I have one reservation: it seems that adding this under the name of `bower` will confuse a lot of people who will want to install JS bower. May we rename it to `bower-mail` or `notmuch-bower`?

**Comment by erictapen** [comment]
@orivej Thanks for the fixup. I learned quite a few things in it. Also a good idea to include the latest commit in order to prevent that `patchShebang` workaround.

This builds and works for me.

**Comment by orivej** [comment]
@erictapen And what do you think about the name of the package?

**Comment by erictapen** [comment]
@orivej Ah right, forgot about that. I'd rather see it as `bower`, since the other `notmuch` MUAs `alot`and `astroid` also have just their names as package names. 

But I'm not familiar with the popularity of JS bower. If you feel like people will confuse it easily, I'd say it's `notmuch-bower` (since the use case is bound tight to the `notmuch` system).

Would you mind taking the choice? I can do the change, based on your decision.

**Comment by Mic92** [comment]
`notmuch-bower`

**Comment by erictapen** [comment]
I didn't adapt the first commit, as I can't apply @orivej's fixup after that.

**Pull request merged**
