### PR TITLE
glibc: 2.32-25 -> 2.32-35

### PR DESCRIPTION
**Pull request by TredwellGit**
###### Motivation for this change
https://sourceware.org/git/?p=glibc.git;a=log;h=refs/heads/release/2.32/master

###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
@GrahamcOfBorg python3Packages.requests

**Review by jonringer — APPROVED** [review]
diff LGTM assuming ofborg passes

**Comment by TredwellGit** [comment]
If someone merges this, then merge https://github.com/NixOS/nixpkgs/pull/109261 as well since they both require rebuilding stdenv.

**Comment by TredwellGit** [comment]
@GrahamcOfBorg python3Packages.requests

**Comment by TredwellGit** [comment]
@GrahamcOfBorg build python3Packages.requests

**Comment by TredwellGit** [comment]
@GrahamcOfBorg build python3Packages.requests

**Comment by TredwellGit** [comment]
@GrahamcOfBorg build python3Packages.requests

**Pull request merged**
