### PR TITLE
rustc: 1.41.0 -> 1.42.0

### PR DESCRIPTION
**Pull request by alyssais**
The patch is included in rust master[1], but neither that, nor the
QuiltOS version we were using previously, apply to 1.42.0, so I've
included the fixed version here.

[1]: https://github.com/rust-lang/rust/commit/4f15867faf2797257cbeb9e4a38ae8dc87dcf2e9

@GrahamcOfBorg build thunderbird firefox
@GrahamcOfBorg build fd

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alyssais** [comment]
I've successfully built thunderbird, firefox and fd.

Could somebody please attempt fd on Darwin?

**Review by lblasc — APPROVED** [review]

**Comment by Mic92** [comment]
I am going to have a look... https://github.com/kholia/OSX-KVM

**Comment by Mic92** [comment]
The test on aarch64 only seems to fail sometimes? Weird.

**Comment by Mic92** [comment]
`fd` builds on aarch64-linux

**Comment by marsam** [comment]
I can confirm `fd` build on darwin

**Comment by Ericson2314** [comment]
@alyssais thanks for backporting!

**Pull request merged**
