### PR TITLE
besu: Use jemalloc & add tests

### PR DESCRIPTION
**Pull request by rolfschr**
## Description of changes

This PR adds `jemalloc` to `besu`. The [docs](https://besu.hyperledger.org/private-networks/get-started/install/binary-distribution#prerequisites-1)  recommend to do this in order to decrease the memory footprint.

Furthermore, a test on the installed version (`besu --version`) is added.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by cole-h** [comment]
@ofborg eval

**Comment by rolfschr** [comment]
There have been issues with the Darwin-based test for jemalloc. Unfortunately, I don't have access to a Mac computer. I have added some debug output to the test and will check later on, what the ofBorg evaluation yields.

**Comment by rolfschr** [comment]
Okay, I checked the output from `ofBorg` for the darwin-build and also checked besu's [source code](https://github.com/hyperledger/besu/blob/main/besu/src/main/java/org/hyperledger/besu/cli/ConfigurationOverviewBuilder.java#L366). Actually, usage of `jemalloc` is only recommended for Linux. I adapted the the code accordingly.

**Comment by rolfschr** [comment]
@cole-h What do you think, could this stay as is and get merged or do you have any further suggestions?

**Comment by rolfschr** [comment]
@cole-h Can we merge this?

**Comment by rolfschr** [comment]
@zimbatm I've seen you've been active at https://github.com/nix-community/ethereum.nix so maybe you could also approve & merge this PR here? Related PR is https://github.com/nix-community/ethereum.nix/pull/511.

**Pull request merged**
