### PR TITLE
parted: 3.2 -> 3.3

### PR DESCRIPTION
**Pull request by malbarbo**
###### Motivation for this change
Patches are not need anymore and builds with musl (without lvm).

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by malbarbo** [comment]
@nh2 you may be interested in this PR as this allow a static build of parted.

**Comment by nh2** [comment]
> @nh2 you may be interested in this PR as this allow a static build of parted.

Nice!

**Comment by nh2** [comment]
@GrahamcOfBorg build

**Comment by nh2** [comment]
@malbarbo I think this PR would better be changed to be PR'd against the `staging` branch, because it triggers rebuilds of a lot of big packages (e.g. apparently all of gnome3 and xfce) (see [this](https://nixos.org/nixpkgs/manual/#submitting-changes-master-branch) for details).

**Comment by malbarbo** [comment]
I changed to target `staging` branch.

**Comment by nh2** [comment]
@GrahamcOfBorg build

**Comment by nh2** [comment]
I succeeded building this commit with musl using

```
nix-build -E '(import <nixpkgs> {}).pkgsMusl.parted.override { lvm2 = null; }'
```

(With the `lvm2` dep, `lvm2 -> systemd -> libmicrohttpd -> gnutls` fails to build.)

I also succeded building it non-musl on top of `staging`.

**Comment by nh2** [comment]
I've tested simple execution. There are some NixOS tests that use `parted`. Merging.

**Comment by nh2** [comment]
@GrahamcOfBorg test bcachefs os-prober zfs

**Pull request merged**
