### PR TITLE
librsvg: 2.40.9 -> 2.40.16 (WIP)

### LINKED ISSUE #16474: librsvg is behind release
## Issue description

Trying to debug why enlightenment isn't showing audacious's .desktop svg icon, I noticed librsvg is somewhat behind release. Specifically, master has it at 2.40.9 which dates back to 2015-03-27 while the latest release is 2.40.16. 2016-06-09.

Unfortunately, the dependency tree is quite extensive so I haven't been able to build and verify if that's the cause of the bug.

Edit: Other packages that use librsvg to render SVGs (nautilus) work fine. Additionally there been a dozen EFL commits regarding svg support in the last couple of weeks ( https://git.enlightenment.org/core/efl.git/log/?id=3ce7aee940ac3dc0c1c38bd99efd08f5ab045da0&qt=grep&q=svg ) so my original concern was almost certainly upstream.

Regardless, the package is due for an update.

### Steps to reproduce

Compare https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/librsvg/default.nix to http://ftp.gnome.org/pub/GNOME/sources/librsvg/2.40/ .

### Note

Originally I filled this issue erroneously thinking the version was 2.9, dating back to 2009...

### PR DESCRIPTION
**Pull request by vrthra**
###### Motivation for this change

Closes #16474
###### Things done
- [x] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by RamKromberg** [comment]
```
In file included from /run/user/1001/nix-build-ffmpegthumbs-4.14.3.drv-0/ffmpegthumbs-4.14.3/ffmpegthumbnailer/moviedecoder.cpp:17:0:
/run/user/1001/nix-build-ffmpegthumbs-4.14.3.drv-0/ffmpegthumbs-4.14.3/ffmpegthumbnailer/moviedecoder.h:55:31: error: 'PixelFormat' has not been declared
     void convertAndScaleFrame(PixelFormat format, int scaledSize, bool maintainAspectRatio, int& scaledWidth, int& scaledHeight);

```
ffmpegthumbs also had an issue with ffmpeg 3 the other day: https://github.com/NixOS/nixpkgs/commit/994c81c391be37b7e2cad693dd0b54e2f9b17a30

I suspect just about every DEs, image viewer and file manager depends on it so these new APIs will cause some havoc :D

**Comment by vrthra** [comment]
@RamKromberg would it be better to provide this as a new package? and leave the old  2.40.9 as default?

**Comment by RamKromberg** [comment]
> would it be better to provide this as a new package?

I think it's unavoidable if kde4 is to be kept. It's why ffmpeg_2 is kept around after all. 

Though, like ffmpeg_2, the new version should take the default librsvg namespace. Of course, that would mean trial and error of over 50 packages with the new version... I guess poor travis is going to earn it's keep :D

**Comment by RamKromberg** [comment]
I closed the issue.

Since you defaulted on the older version, I guess people will just have to depend on the new version as breakage occurs.

**Comment by vrthra** [comment]
@RamKromberg I was actually moving in the direction you suggested, with defaulting on the newer version. I pushed the two commits early so that I could pull from a different system where I was running the `nox review`. But if this gets merged, I plan to move each dependents to the new version one at a time -- there are some 168 .nix files that contain a reference to librsvg.

**Comment by RamKromberg** [comment]
@vrthra I was afraid of that. I simply don't own the compute for all of that so I ended up raising an issue and moved along to other problems.

The steps I would have taken if I could skip travis checking and force merging is this:
1. Refactor to reserve the librsvg namespace to the newest version of librsvg.
2. Change all the current packages to explicitly depend on the old 2.40.9 version.
3. Let maintainers upgrade each package as the need arises.

This will save up on a lot of time and compute and will be the "right thing" to in the long term.

**Comment by vrthra** [comment]
@RamKromberg I will fix this bug the way you describe. But I think I will have to come back to this again later.

**Comment by RamKromberg** [comment]
Sure thing.  I opened and closed the issue expecting this to be a slow and gradual process from the start.

Thanks :)

**Comment by vcunat** [comment]
Debian is using 2.40.16 [in testing](https://packages.debian.org/source/stretch/librsvg) and unstable, so there should be (soon) patches for most packages to use the new version. But of course, even with that it can take quite some work to find and apply them in nixpkgs.

Note that travis is no (hard) requirement for merging at all; there are far too many false negatives.

**Comment by RamKromberg** [comment]
> so there should be (soon) patches for most packages to use the new version.

That's good news.  Might I suggest you throw in libpng 1.6.23 in there as well? The old 1.2.56 branch you've already noticed being upgraded due to a security concern wasn't the only thing I wanted to PR but I didn't want to burden a system-wide recompile over just a couple of bug-fixes.
However, since all the same packages are going to go through recompilation and libpng only had a few bug fixes between 1.6.21 and 1.6.23, maybe it's better to get both pulled in together?
Just a thought :D

**Comment by vcunat** [comment]
Right, I might've forgotten to through my feed of package updates, including libpng-1.6.23.

**Comment by RamKromberg** [comment]
@vrthra you can close this now that @fpletz pushed .16 as part of https://github.com/NixOS/nixpkgs/issues/18856

**Comment by vrthra** [comment]
Thanks, closing.

**Pull request closed without merging**
