### PR TITLE
WIP: ghcjs: Build core libraries with nix

### LINKED ISSUE #10147: Provide the package versions in `ghcjs-boot` to GHC as well
`ghcjs-boot` uses its own versions of [several packages](https://github.com/ghcjs/ghcjs-boot/tree/master/boot). When working on a project using both GHC and GHCJS it would be good to be able to use the exact same versions of these packages across both halves of the project. This is currently not possible because `nixpkgs` just [hands off](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/configuration-ghcjs.nix#L16) responsibility for those packages to `ghcjs`, so there is no way to access their derivations.

I don't think it's as simple as going through and adding the derivations to [configuration-ghcjs.nix](pkgs/development/haskell-modules/configuration-ghcjs.nix), though - changing the derivations from `null` to an actual derivation seems like it would cause problems on the GHCJS side of things. I'm not sure how this could be solved, but it would be great if we could get something going!

### PR DESCRIPTION
**Pull request by Ericson2314**
Currently ghcjs-boot installs these libraries, but picks versions we cannot control and may not like. This puts nixpkgs in charge making it easy to select versions (e.g. booting ghcjs for different LTS package sets). Additionally, I tweaked the haskell infrastructure to better support cross-compilers, with ghcjs the guinea pig. Hashes for ghc package sets should be unchanged.

This is unfinished because currently I can only build libraries. Even once I get all the requisite files in place for building executables, the duplication between my wrapper script and ghcjs-boot and the divergence between my fork and upstream are less than ideal. I hope to work with luite to see what here can be upstreamed.

fixes #10147 #10215

cc @k0001 @cstrahan

### CODE REVIEW

**Comment by Ericson2314** [comment]
Ok I built an executable with trivial `return []` TH. So this is getting closer / might be ready for others to test.

**Comment by k0001** [comment]
Thanks for such a piece of work. I haven't paid attention to the implementation details, but I wanted to say that I find this very convenient, at least as a way to reduce compile times for `ghcjs-boot` (since it would be picking its dependencies from the nix store if available).

**Comment by peti** [comment]
This appears to be stalled.

**Comment by Ericson2314** [comment]
Yes this stuff is mostly waiting on upstream—ehich might as well be waiting on GHC

**Pull request closed without merging**
