### PR TITLE
 blackmagic: v1.6.1-317-gc9c8b08 -> v1.6.1-409-g7a595ea (add new targets)

### PR DESCRIPTION
**Pull request by sorki**
###### Motivation for this change

Update to more recent version. Also exposes hosted targets which can be run on host system instead of microcontroller (requires libusb and pkg-config).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by emilazy — APPROVED** [review]
LGTM. Sorry for not getting around to this myself; I was hoping there'd be a tagged upstream release sooner.

@GrahamcOfBorg build blackmagic

**Comment by mmahut** [comment]
@GrahamcOfBorg build blackmagic

**Comment by emilazy** [comment]
Looks like stdenv is passing down CFLAGS it shouldn't to arm-embedded-gcc on Darwin. If you're not sure how to fix that, probably best just to mark it as only building on Linux for now?

**Comment by mmilata** [comment]
fyi ZHF: #80379

**Comment by emilazy** [comment]
Hopefully the bump will fix the error, but whoever merges should make sure to switch platforms to Linux-only so they don't introduce a new one in the process ^^;

**Comment by sorki** [comment]
I'll take a look and update to more recent version as well.

**Comment by sorki** [comment]
Bumped version, now uses `platforms.linux` instead of `platforms.unix`. I've also added myself to maintainers.

**Review by emilazy — APPROVED** [review]

**Comment by mmahut** [comment]
@GrahamcOfBorg build blackmagic

**Review by vcunat — APPROVED** [review]

**Pull request merged**
