### PR TITLE
[21.05] mc: 4.8.26 -> 4.8.27

### PR DESCRIPTION
**Pull request by wamserma**
###### Motivation for this change

https://github.com/NixOS/nixpkgs/pull/135690
has a bunch of security updates

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review pr 136504"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wamserma** [comment]
@GrahamcOfBorg build mc

**Comment by ShamrockLee** [comment]
LGTM

1 package built:
mc

nix-info output:
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.48, NixOS, 21.05.20210717.b2f87e0 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by wamserma** [comment]
ping @SuperSandro2000  - you merged the PR where this was cherry-picked from

**Review by risicle — APPROVED** [review]
Builds & runs, macos 10.15 & nixos x86_64

**Pull request merged**
