### PR TITLE
Update transitive-broken.yaml

### PR DESCRIPTION
**Pull request by thielema**
remove several packages depending on comfort-array, comfort-fftw

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by thielema** [comment]
The disabled packages are missing in the current release 22.11 and I wanted to reactivate them.

**Comment by cdepillabout** [comment]
> The disabled packages are missing in the current release 22.11 and I wanted to reactivate them.

I'm not quite sure I understand.  It sounds like you want these packages fixed in 22.11, but why is this PR targeting `master`?

**Comment by thielema** [comment]
> > The disabled packages are missing in the current release 22.11 and I wanted to reactivate them.
> 
> I'm not quite sure I understand. It sounds like you want these packages fixed in 22.11, but why is this PR targeting `master`?

They are disabled in 22.11 and in master, so I suspect that they will be disabled in upcoming 23.05, too.

Sorry, I am not familiar with the release process. What can I do to make those packages ship with the next release?

**Comment by sternenseemann** [comment]
These packages all depend on packages marked as broken. Removing them from the list won't make them ship. You need to fix the underlying build failure and remove the broken flag of those packages.

**Comment by maralorn** [comment]
@thielema It‘s actually great that you are wishing to fix packages you care for. And we will gladly support you with that. Would be cool if we can fix them until branch-off. We never know which packages users care about so getting that feedback is valuable.

To give you a bit more actionable feedback: From a look at the transative-broken.yaml, we can’t tell why these packages are broken, concretely which of their dependencies is. To figure that out you need try to build them and look at the evaluation error which will tell you about some broken package. Then you will need to fix that package.  Step one would be to remove the packages from the broken.yaml and then run maintainers/scripts/haskell/regenerate-hackage-packages.sh, then you try to ubild again and see what the problem is. Sadly we currently don’t have great docs about how to do that, but https://nixos.org/manual/nixpkgs/unstable/#haskell-overriding-haskell-packages might be helpful.

**Comment by thielema** [comment]
On Thu, 20 Apr 2023, maralorn wrote:

> @thielema It‘s actually great that you are wishing to fix packages you 
> care for. And we will gladly support you with that. Would be cool if we 
> can fix them until branch-off. We never know which packages users care 
> about so getting that feedback is valuable.

The problem seems to be that packages rely on storable-record_0_0_6, which 
is no longer present. They should simply depend on storable-record (which 
is currently 0.0.7). I find storable-record_0_0_6 in hackage-packages.nix, 
but this file is autogenerated, too. What I can I do make the packages 
depend on storable-record instead of storable-record_0_0_6?

How can I be notified about compilation failures of packages I am 
interested in?

**Comment by maralorn** [comment]
I have trouble reproducing what you are talking about. Are you on the master branch?
I can’t find any mentions of storable-record 0.0.6. We currently ship storable-record 0.0.7 which is the version in stackage lts.

Instead, I looked at a random of those packages, lapack and noticed it fails because the tests of storablevector is broken by a restrictive upper bound on bytestring. I fixed that and that fixed at least lapack, hyper, comfort-array and comfort-array-shape. I haven’t looked at all packages you listed.

You can be notified about compilation failures by entering yourself into the maintainer list here:

https://github.com/NixOS/nixpkgs/blob/98dc2474f769426e1c331d17b73a729458bfd862/pkgs/development/haskell-modules/configuration-hackage2nix/main.yaml#L139

You will then be pinged by us when we post a report like e.g. this: https://github.com/cdepillabout/nix-haskell-updates-status

**Comment by thielema** [comment]
On Thu, 20 Apr 2023, maralorn wrote:

> I have trouble reproducing what you are talking about. Are you on the master branch?
> I can’t find any mentions of storable-record 0.0.6.

Sorry, my mistake. I had some old lines from former versions of 
hackage-packages.nix lying around. With haskell-updates/HEAD I can now 
build storablevector. The version bound on bytestring is also relaxed at 
Hackage, now.


> You can be notified about compilation failures by entering yourself into the maintainer list here:
> 
> https://github.com/NixOS/nixpkgs/blob/98dc2474f769426e1c331d17b73a729458bfd862/pkgs/development/has
> kell-modules/configuration-hackage2nix/main.yaml#L139
> 
> You will then be pinged by us when we post a report like e.g. this:
> https://github.com/cdepillabout/nix-haskell-updates-status

perfect

**Pull request closed without merging**
