### PR TITLE
starship: 1.18.0 -> 1.18.1

### PR DESCRIPTION
**Pull request by acuteenvy**
## Description of changes

starship: 1.18.0 -> 1.18.1
https://github.com/starship/starship/releases/tag/v1.18.1

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by drupol — APPROVED** [review]

**Review by drupol — CHANGES_REQUESTED** [review]
I see that build and tests are failing, I think it's trivial to fix (because of a failing test).
Do you think you could exclude this test so tests would be green?

```
failures:
    modules::aws::tests::expiration_date_set_from_file
test result: FAILED. 1041 passed; 1 failed; 32 ignored; 0 measured; 0 filtered out; finished in 155.11s
error: test failed, to rerun pass `--lib`
error: builder for '/nix/store/sc9cd7wxyypx0ib188f5l54vlpdm8kks-starship-1.18.1.drv' failed with exit code 101;
       last 10 log lines:
       > time is not in range: Some("on \u{1b}[1;33m☁\u{fe0f}  astronauts (ap-northeast-2) [29m51s] \u{1b}[0m")
       > note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
       >
       >
       > failures:
       >     modules::aws::tests::expiration_date_set_from_file
       >
       > test result: FAILED. 1041 passed; 1 failed; 32 ignored; 0 measured; 0 filtered out; finished in 155.11s
       >
       > error: test failed, to rerun pass `--lib`
```

**Comment by kilianar** [comment]
At least for me, `starship` builds without any issues:

Result of `nixpkgs-review pr 298608` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>starship</li>
  </ul>
</details>


However, `nixosTests.starship` encounters the following error:
```
Traceback (most recent call last):
  File "/nix/store/k6yj2za3m4zg5mmviq23h0ir7y604fp6-nixos-test-driver-1.1/bin/.nixos-test-driver-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/k6yj2za3m4zg5mmviq23h0ir7y604fp6-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/__init__.py", line 126, in main
    driver.run_tests()
  File "/nix/store/k6yj2za3m4zg5mmviq23h0ir7y604fp6-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/driver.py", line 163, in run_tests
    self.test_script()
  File "/nix/store/k6yj2za3m4zg5mmviq23h0ir7y604fp6-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/driver.py", line 155, in test_script
    exec(self.tests, symbols, None)
  File "<string>", line 6, in <module>
  File "/nix/store/k6yj2za3m4zg5mmviq23h0ir7y604fp6-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/machine.py", line 611, in succeed
    raise Exception(f"command `{command}` failed (exit code {status})")
Exception: command `expect-zsh` failed (exit code 1)
```

**Comment by acuteenvy** [comment]
It builds correctly for me too.

**Review by drupol — APPROVED** [review]

**Comment by drupol** [comment]
OK, I merged it since apparently you succeeded to build it.

**Pull request merged**
