### PR TITLE
PySolFC: 2.0 -> 2.6.4

### PR DESCRIPTION
**Pull request by bignaux**
###### Motivation for this change

2.0 was released in  2010-06-09 . It seems like an unmaintained derivation.
CC @kierdavis 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bignaux** [comment]
@GrahamcOfBorg build pysol

**Comment by xeji** [comment]
@GrahamcOfBorg build pysolfc

**Review by xeji — CHANGES_REQUESTED** [review]
Fix hash mismatches

**Comment by bignaux** [comment]
the hash are good, sf is always a nightmare. i spent so many hours on such SF download issue, and have no good feedback from nixos maintainer, when i skip mirror:// syntax or others tricks.

**Comment by xeji** [comment]
This doesn't build on my local machine either - looks like I get a different hash every time I try.

**Comment by bignaux** [comment]
yes it's ALwAYS the same known bug, lot of mirrors just give you an htlm error page. mirror:// syntax is a bad idea for SF, but i never sucess to convinct anyone. I can put a known working mirror  but another maintainer would complain i'm too silly to not have using mirror:// syntax, it happens ...

**Comment by kierdavis** [comment]
Thanks for doing this. I'll try and find some time to test and review this
PR soon.

Don't feel you have to stick to sourceforge and/or mirror:// if you think
there's a better way. More generally, feel free to propose any other
changes that would make this derivation easier to work with in future.

For what it's worth, I don't actively track this software for new releases,
or any of the other packages that I'm listed as maintainer on. I do aim to
keep on top of nixpkgs issues and PRs however, so if you want to see the
package updated and/or changed feel free to just open an issue (and tag me
in it so I get an email), rather than feeling that you're forced to do the
legwork yourself.

**Comment by bignaux** [comment]
you can simply replace mirror by https://versaweb.dl.sourceforge.net . You can also restore a  wrapProgram mecanism to avoid .py suffix as i'd temporary removed that.

**Comment by bignaux** [comment]
This derivation fix non-working desktop file, python 3 and so ...

**Pull request merged**
