### PR TITLE
modemmanager: 1.18.12 → 1.20.4

### PR DESCRIPTION
**Pull request by jtojnar**
###### Things done

- [x] pkg-config files look okay
- [x] output diffs look okay
- [x] news look okay
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alyssais** [comment]
Hmm, 233dac2934f685e87e3f9a6480c3b66027c069b2 doesn't build for me on x86_64-linux.  I wonder how OfBorg managed it…

```
modemmanager> Installation failed due to insufficient permissions.
modemmanager> Attempting to use polkit to gain elevated privileges...
modemmanager> pkexec must be setuid root
modemmanager> FAILED: meson-internal__install
modemmanager> /nix/store/754p0izaawcr1v28i0k3xbbj2r3m27n2-meson-0.64.1/bin/meson install --no-rebuild
modemmanager> ninja: build stopped: subcommand failed.
error: build of '/nix/store/3yzwywmxb3hkcsqpsc1s58lrq63lfnlk-modemmanager-1.20.4.drv' failed
```

**Comment by alyssais** [comment]
Works for me on another system with a more recent Nix so probably a Nix bug that got fixed along the way.

**Comment by alyssais** [comment]
Okay, as it turns out this package _should_ have failed to build, and only worked due to a [regression in Nix](https://github.com/NixOS/nix/issues/7813).

From the OfBorg log:

```
Installing /build/source/build/data/org.freedesktop.ModemManager1.conf to /etc/dbus-1/system.d
```

This should not have worked.

**Comment by alyssais** [comment]
We can set `-Ddbus_policy_dir` to fix D-Bus file installation, but the new example files can't be disabled.  I've opened an [upstream MR](https://gitlab.freedesktop.org/mobile-broadband/ModemManager/-/merge_requests/966) to add an option to disable installing those.

**Comment by jtojnar** [comment]
Ugh I assumed the option is not necessary anymore due to the path being [properly interpolated now](https://gitlab.freedesktop.org/mobile-broadband/ModemManager/-/blob/02d730604dd3c99770d04d9ba79e7ba4eeed1854/meson.build#L168) but did not notice that it is interpolating `sysconfdir`. Must have been using Nix 2.12 as well.

But that line does not really make sense – it is getting `sysconfdir` from the pkg-config file and then replacing it wholesale with sysconfdir of the package. And the `/etc` path is [deprecated for packages anyway](https://archlinux.org/todo/d-bus-policy-in-usrsharedbus-1systemd-instead-of-etcdbus-1systemd/).

**Comment by jtojnar** [comment]
As for the examples, it might be useful install them, maybe with something like https://github.com/NixOS/nixpkgs/blob/532f202b6490c646817796ba09e88c8b7bea74c1/pkgs/os-specific/linux/firmware/fwupd/add-option-for-installation-sysconfdir.patch

**Comment by alyssais** [comment]
> As for the examples, it might be useful install them, maybe with something like https://github.com/NixOS/nixpkgs/blob/532f202b6490c646817796ba09e88c8b7bea74c1/pkgs/os-specific/linux/firmware/fwupd/add-option-for-installation-sysconfdir.patch

Useful for what? I don't mind installing stuff like that when it doesn't cause problems, but I'm fairly doubtful that people are going to go poking around in their Nix store to find examples.

**Comment by jtojnar** [comment]
When I want to edit fwupd settings on my NixOS system, I find running `nix build .#fwupd` in my config flake and looking at the commented config files in the output more convenient than looking at the fwupd version in the nixpkgs input of my flake, going to the repo and looking up the source file for the config with appropriate tag. But it’s just a nice to have, not something critical.

**Pull request merged**
