### PR TITLE
prusa-slicer: 2.0.0 -> 2.1.0 

### PR DESCRIPTION
**Pull request by Moredread**
###### Motivation for this change

Preparing for update to 2.1.0.

There is a new dependency needed, cereal. This PR adds a package for that as well.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by Moredread** [comment]
cc @mweinelt @ArdaXi @baracoder @thorstenweber83 as you were interested in the previous PR. :)

**Comment by mweinelt** [comment]
Unrelated, but FYI: There has also been a new firmware release https://github.com/prusa3d/Prusa-Firmware/releases/tag/v3.8.0.

Build is running, will report back asap.

**Comment by mweinelt** [comment]
2.1.0-rc2 is out and is supposed to fix https://github.com/prusa3d/PrusaSlicer/issues/2619#issuecomment-530522565.

**Comment by mweinelt** [comment]
Yup, still looking good.

**Comment by Mic92** [comment]
@GrahamcOfBorg build prusa-slicer

**Comment by flokli** [comment]
`cereal` itself seems quite useful, and it'd be a pity if it'd be inacessible just because there's not maintainer for it.

The derivation also looks quite trivial, let's keep it like it is currently.

**Pull request merged**
