### PR TITLE
bcachefs: update 10

### PR DESCRIPTION
**Pull request by eadwu**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by davidak** [comment]
@eadwu can you specify the "Motivation for this change"? The last update is 4 days ago. Why is this needed? (i currently don't follow the development)

I opened a general discussion about how frequent unstable packages should be updated: https://discourse.nixos.org/t/how-frequent-to-update-unstable-packages/4458

Could you also build the changes and run the tests?

**Review by davidak — APPROVED** [review]
LGTM

(not tested)

**Comment by eadwu** [comment]
There's no actual "motivation" to say, I namely just check the bcachefs-tool repository for updates before manually generating a patch for the kernel I wish to use it on (upstream uses 5.0) and since it's along the way, I just update the nix expressions as well. So for building, at least for the current revision, I've built it upon `linux_latest` and `linux_testing`. `bcachefs-tools` is rebuilt as I have it as a package in `environment.systemPackages` but since I don't explicitly build `linux_testing_bcachefs` I don't check the boxes.

**Review by ghost — APPROVED** [review]
Tested. Works.

**Pull request merged**
