### PR TITLE
hplip: 3.16.11 -> 3.17.9

### PR DESCRIPTION
**Pull request by ttuegel**
### Motivation

- Remove hplip-3.15.9 (broken)
- Update hplip-3.16.11 (kept as `hplip_3_16_11`) to hplip-3.17.9
- Remove @nckx from HPLIP maintainers per conversation on #29616

I have tested the binary plugin driver and the Postscript driver.

### Testing

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jgeerds** [comment]
@ttuegel: Your changes looks good to me. Unfortunately I don't have the time to test your changes.

Could someone else help out? @nckx?

**Comment by nckx** [comment]
I'm certainly willing to test this, but since
- that'll be in exactly 48 hours,
- will be only on x86* anyway, and
- I trust @ttuegel to do good work,

I don't expect anyone to actually wait for me.

**Comment by ttuegel** [comment]
> I don't expect anyone to actually wait for me.

I will go ahead with merging into master. I think this should eventually be ported to NixOS 17.09 because it adds support for new printer models. I will wait on that until we are sure it's stable.

**Comment by eqyiel** [comment]
I gave this a go and Gnome was able to see my printer.  Thanks!

**Comment by stefano-m** [comment]
@ttuegel any idea when this will be ported to NixOS 17.09? It would be a life-saver for me as at the moment I cannot use my printer.

Thanks!

**Pull request merged**
