### PR TITLE
ruby_3_4: 3.4.0.preview2 -> 3.4.1

### PR DESCRIPTION
**Pull request by masoo**
https://www.ruby-lang.org/en/news/2024/12/25/ruby-3-4-0-released/
https://www.ruby-lang.org/en/news/2024/12/25/ruby-3-4-1-released/

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

The result of  `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"` is as follows
```
error: build log of '/nix/store/yljdg1g7kcwrdfib1z9c3nn25f841nhg-ruby3.4-gdk3-4.2.1.drv^*' is not available
error: build log of '/nix/store/20yvpbd83slj75b5ksmx125zfddlk0dq-ruby3.4-gdk3-4.2.1' is not available
error: build log of '/nix/store/0h9i84bkdf3kc3rhz2vfslgd7zrbxf20-ruby3.4-gtk3-4.2.1.drv^*' is not available
error: build log of '/nix/store/fx3xnx13q4mg951hwilfw83mm24vqbw5-ruby3.4-gtk3-4.2.1' is not available
error: build log of '/nix/store/2x1shwr9lf51gm7q14fahmfj9jds6cmv-ruby3.4-ruby-libvirt-0.8.2.drv^*' is not available
error: build log of '/nix/store/vc8qrs15li74bfp5ghvzlv6ksgia4pw3-ruby3.4-ruby-libvirt-0.8.2' is not available
error: build log of '/nix/store/8zh7r81zqikgrpw8cpdmwgfcavfpx02r-ruby3.4-ruby-lsp-0.15.0.drv^*' is not available
error: build log of '/nix/store/arcspn7f574da405cnj2qnqck5gj2dw5-ruby3.4-ruby-lsp-0.15.0' is not available
```

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by kachick** [comment]
>[NixOS:staging](https://github.com/NixOS/nixpkgs/tree/staging)

As I understand, Ruby 3.4.0 is not yet used in another package. So sending to master branch will be better?

previous PR for similar purpose: https://github.com/NixOS/nixpkgs/pull/276648

**Comment by SigmaSquadron** [comment]
> The result of nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD" is as follows

As a rule of thumb, if you can `nixpkgs-review` a PR, and you do not own a supercomputer, it shouldn't target `staging`.

**Comment by MidAutumnMoon** [comment]
Thanks, this is fast! However, I'd agree that this should target master instead.

**Comment by masoo** [comment]
Ruby 3.4.1 has been released.
https://www.ruby-lang.org/en/news/2024/12/25/ruby-3-4-1-released/

> This fixes the version description.

Commit added.

**Comment by SigmaSquadron** [comment]
> As I understand, ruby_3_4 is not yet used in another package.

A `nixpkgs-review` runs shows me that's not true. This is well over 1300 rebuilds. I guess @masoo has a spare supercomputer lying around.

**Comment by masoo** [comment]
> supercomputer, it shouldn't target staging. staging is for changes which cause a massive amount of rebuilds.

nixpkgs-review was done on the master branch

Should I rework the pull request for the master branch?

**Comment by SigmaSquadron** [comment]
No, leave it on `staging`, and do not `nixpkgs-review` it. There are way too many rebuilds and it'll just use your computer's resources for no good reason.

**Comment by MidAutumnMoon** [comment]
Open another PR targeting master would be the easiest solution.

**Comment by masoo** [comment]
There was a broken package, and I wanted to provide an explanation.
I applied `nixpkgs-review` to it.
If I misunderstood or overlooked any rules, I sincerely apologize.

**Comment by SigmaSquadron** [comment]
It's not a rule, you can certainly review staging PRs if you have the computational resources, but most people don't because you're simply stressing your computer for the same result Hydra will eventually give you.

**Comment by MidAutumnMoon** [comment]
The problem here is not that one should or shouldn't nixpkgs-review staging. The commits are based on the wrong (staging) branch, and the proper solution would be cherry-pick the commits onto a branch based off master.

**Comment by MidAutumnMoon** [comment]
On the other side, this is a really good first time contrib. Congrats!

**Comment by masoo** [comment]
Thank you for providing the solution.
I will close this pull request and create a new one targeting the master branch.

**Pull request closed without merging**
