### PR TITLE
icu: 73.2 -> 74.1

### PR DESCRIPTION
**Pull request by marsam**
## Description of changes

Changelog: https://github.com/unicode-org/icu/releases/tag/release-74-1

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — COMMENTED** [review]
Did you test some if the usual breakage candidates like nodjs?

**Comment by nyabinary** [comment]
icu 74.2 is out.

**Review by l0b0 — APPROVED** [review]
LGTM, thanks!

**Review by AndersonTorres — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
> Did you test some if the usual breakage candidates like nodjs?

@ofborg build nodejs

**Comment by nyabinary** [comment]
> > Did you test some if the usual breakage candidates like nodjs?
> 
> @ofborg build nodejs

did this ever get built?

**Comment by wegank** [comment]
Fun fact: this PR can fail the pkgs/by-name check...

**Comment by infinisil** [comment]
Yeah this is an intended failure. This is a case where it makes sense to refactor into `icuVersions.*` (like `nixVersions.*`), instead of exposing each version individually in the top-level packages (though you'll want backwards compatibility aliases).

**Comment by infinisil** [comment]
Oh and note that this is a partial duplicate with https://github.com/NixOS/nixpkgs/pull/283359, which puts icu74 into `pkgs/by-name`, which wouldn't be necessary with the refactoring suggested above.

**Comment by AndersonTorres** [comment]
But nixVersions does not look "by-name"-able.

**Comment by infinisil** [comment]
Right, should've been clearer, you indeed wouldn't use `pkgs/by-name` with `nixVersions.*` or `icuVersions.*`. It's not something that can be done with `pkgs/by-name` yet.

**Comment by wegank** [comment]
Oh, I screwed up the rebase, sorry...

**Pull request closed without merging**
