### PR TITLE
python3Packages.trackpy: remove due to prolonged breakage

### PR DESCRIPTION
**Pull request by jonringer**
###### Motivation for this change
according to git history, this has been broken since feburary/march 2020, and I fixed the build for a period in oct 2019.

cc @costrouc 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
#95265

**Comment by jonringer** [comment]
cc @costrouc this package has been broken for more than a year

```
commit 9fbeaa4cfce629a8f414a8553bcd03d6e2358c25
Author: Jonathan Ringer <jonringer117@gmail.com>
Date:   Wed Mar 18 13:27:33 2020 -0700

    python3Packages.trackpy: 0.4.1 -> 0.4.2, mark broken
    ```

**Comment by Artturin** [comment]
this isn't broken anymore 

the tests pass

**Comment by Artturin** [comment]
#133052

**Pull request closed without merging**
