### PR TITLE
Add Python2 compatible version of chardet

### PR DESCRIPTION
**Pull request by efirestone**
Version 2.3.0 of the chardet Python module was the last one that was compatible with Python 2.X (specifically 2.6+). This adds a package for that version within python2-modules.
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by liff — CHANGES_REQUESTED** [review]
There should be an entry for this package in [`pkgs/top-level/python2-packages.nix`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/python2-packages.nix). Otherwise it won’t be actually available in the `python2Packages` set.

You can test that this package builds with:

```shell
NIXPKGS_ALLOW_INSECURE=1 nix-build -A python2Packages.chardet
```

The commit messages should follow [the conventions](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions). That is, they should be:

```
maintainers: add efirestone
python2Packages.chardet: init at 2.3.0
```

**Comment by SuperSandro2000** [comment]
What's the reason to even include this now?

**Comment by mweinelt** [comment]
Was removed in 5eb43616fece393fd7cf80cbbd20b1ce41dae9b6, because we don't support the python2 package set any longer. We're not going to restart adding packages there.

**Comment by efirestone** [comment]
> There should be an entry for this package in [`pkgs/top-level/python2-packages.nix`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/python2-packages.nix). Otherwise it won’t be actually available in the `python2Packages` set.
> 
> You can test that this package builds with:
> 
> ```shell
> NIXPKGS_ALLOW_INSECURE=1 nix-build -A python2Packages.chardet
> ```
> 
> The commit messages should follow [the conventions](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions). That is, they should be:
> 
> ```
> maintainers: add efirestone
> python2Packages.chardet: init at 2.3.0
> ```

Thank you for all of these comments! I've updated the commits. I left a more thorough commit message for the chardet commit, but did make the summary line match your suggestion and the conventions. I believe this is in line with what CONTRIBUTING.md recommends, but let me know if not.

**Comment by efirestone** [comment]
> Was removed in [5eb4361](https://github.com/NixOS/nixpkgs/commit/5eb43616fece393fd7cf80cbbd20b1ce41dae9b6), because we don't support the python2 package set any longer. We're not going to restart adding packages there.

Ah! I didn't think to look for a removal.

I'm working up to adding [gmvault](http://gmvault.org) as an application/service, but it's unfortunately pretty ancient and all based on Python 2. What would be the recommended way to include it? Should I include all of the necessary packages directly alongside the application package?

**Comment by mweinelt** [comment]
The time for Introducing new packages based on python 2 has passed. Feel free to keep the package in your own repository.

**Comment by efirestone** [comment]
Appreciate all the background. That sounds good to me. Thanks!

**Comment by efirestone** [comment]
I added a README to the python2 modules directory to hopefully help point others in the same direction in the future: https://github.com/NixOS/nixpkgs/pull/348583

**Pull request closed without merging**
