### PR TITLE
mates: fix hash

### PR DESCRIPTION
**Pull request by globin**

### CODE REVIEW

**Comment by globin** [comment]
cc @wizeman the hash seems to be changing either due to a cargo or registry update

**Comment by DamienCassou** [comment]
This issue might be related https://github.com/untitaker/mates.rs/issues/14

**Comment by globin** [comment]
Possible, haven't seen this on the other rust packages either.

**Comment by globin** [comment]
ping @cillianderoiste

**Comment by vcunat** [comment]
What causes these hash changes? When I pick this PR atop master, the hashes won't match (again):
`output path ‘/nix/store/b7f82cgqaqv0h61lpn58gm043mkz7js6-mates-0.1.0-fetch’ should have r:sha256 hash ‘0h8i4y7fr57k31s0m4c5dyzwim6y9f01rljvh2kjpnff97fc25xx’, instead has ‘0p899zx0ffn1grzxfgvdfid19mxzbax5ll5wc5xq75594dl81avb’
`

**Comment by wizeman** [comment]
A while back I added code to debug this kind of hash mismatches for Cargo build. It should be part of the output of the build process (at the end).

It would be great if these build outputs which got different `depsSha256` hashes would be posted, so that we could compare and see exactly what has changed.

**Comment by vcunat** [comment]
Log of the failing mates build on current master: http://sprunge.us/Hbfi.

**Comment by DamienCassou** [comment]
Can we just deactivate this derivation? I'm the maintainer, but I don't use it anymore.

**Comment by vcunat** [comment]
It seems @globin is interested in it.

**Comment by globin** [comment]
I actually only added all rust packages to our hydra as I was upgrading rust and playing around with a musl version of rust and found this being broken. Personally I'm happy to remove this if nobody uses it.

**Comment by globin** [comment]
I've removed the package, btw I haven't seen this behaviour for other rust packages, so I'm not sure what caused this here, let's see if this happens with others in future.

**Comment by DamienCassou** [comment]
Thanks. You could have just disabled it in case someone else wants to fix it. But I case it does not matter so much.

**Comment by globin** [comment]
It still can be found via the git history and this PR amongst others (at least the first one packaging it) and we do have a lot of abandoned packages lying around.

**Pull request closed without merging**
