### PR TITLE
nixos/openssh: add support for authorized principals

### PR DESCRIPTION
**Pull request by aanderse**
## Description of changes

i've been using ssh certificates lately and it would be super convenient if i could add principals via `users.users.foo.authorizedPrincipals = [ "value" ];` instead of `environment.etc."sshd/authorized_principals.d/foo".text = "value";` as the former is type checked and not susceptible to path typos

---

on an unrelated note: @teto do you know if openssh accepts a `,` as a separator for `AuthorizedKeysFile`? if not what is our plan to migrate `services.openssh.authorizedKeysFiles` to `services.openssh.settings.AuthorizedKeysFile`? i would like us to proceed with this and am willing to do the work

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by teto** [comment]
sry I dont know, I know that for instance https://github.com/NixOS/nixpkgs/pull/215397 broke my ssh config. The ssh config is an uttermess with no consistency. For a security program, I think it's crazy and you dont need to hack the software, the amount of silent misconfigured servers out there must be huge.

**Comment by con-f-use** [comment]
Maybe the documentation could mention, that this is meant to be used with `services.openssh.extraConfig = "TrustedUserCAKeys <some_cert_file>";` and how to sign an SSH public key and use that signed key or at least link the documentation that explains it. @aanderse

**Comment by aanderse** [comment]
@con-f-use ah i see that you also were looking for this feature... great! i like your idea for improved documentation - would you like to draft up a PR and we can iterate from there?

:heart:

**Comment by con-f-use** [comment]
I think this from my linked issue, would be enough to get people started:

```nix
    options.openssh.authorizedPrincipals = mkOption {
      type = with types; listOf types.singleLineStr;
      default = [];
      description = mdDoc ''
        A list of authorized principals that may login as this user.

        By signing any ssh public key and including one of these principals
        in the signature, the signing authority can authorize the key holder
        to login as that user, without needing to change anything on the sshd
        host. Only the sining certificate needs to be configures, e.g. using
        `rvices.openssh.extraConfig = "TrustedUserCAKeys ${path_to_signing_certificate}";`

        See: [SSH Certificate Authentication](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/sec-using_openssh_certificate_authentication)
      '';
      example = [
        "example@host"
        "foo@bar"
      ];
    };
```
Would you agree?

**Comment by aanderse** [comment]
that is great, far better than what we currently have! let's ship it :rocket:

**Pull request merged**
