### PR TITLE
transmission: 3.00 → 4.0.2

### PR DESCRIPTION
**Pull request by artemist**
###### Description of changes

Transmission 4.0.2 is a major change from 3.00. Several components, including the web interface, have been rewritten. The libtransmission API now requires C++, breaking compatibility with some old programs. The RPC clients now also use different APIs, but I believe they are backwards and forwards compatible.

This is a draft because some packages cannot use Transmission 4.0 due to the changes so I had to create new transmission_3 packages. I'm not sure about how to name those.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NickCao** [comment]
See https://github.com/NixOS/nixpkgs/pull/215316

**Comment by artemist** [comment]
Weird, I didn't see that when I searched.

**Comment by winterqt** [comment]
This is a dupe of the other PR, except the 4.0.2 bump. Can I close this out?

**Comment by linsui** [comment]
Obviously this can be closed since https://github.com/NixOS/nixpkgs/pull/241146 has been merged.

**Pull request closed without merging**
