### PR TITLE
mopidy-iris: 3.32.5 -> 3.33.0

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
Fixes https://github.com/NixOS/nixpkgs/issues/56940

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @Tomahna @worldofpeace

### CODE REVIEW

**Review by worldofpeace — COMMENTED** [review]
Yeah they just removed the problematic dependencies.

Can you reference these commits in the commit msg for Iris?
https://github.com/jaedb/Iris/commit/c9861bc79cc65eb7a775fe35eda48d0c8115e9cb
https://github.com/jaedb/Iris/commit/4d649809007ab3ac9078af9c5e3022f6fd87eac6
https://github.com/jaedb/Iris/commit/0c134459ea46799f535a56fb5908629856f2f6e5
https://github.com/jaedb/Iris/commit/28b5f69333f5769e5959df550f04ba6350e3ef9f

Didn't see them keeping much of a change log.

Other than that this should be fine

**Comment by dotlambda** [comment]
> Other than that this should be fine

Unless you actually tried running it, I'd like to wait for feedback by a user.

**Comment by worldofpeace** [comment]
> > Other than that this should be fine
> 
> Unless you actually tried running it, I'd like to wait for feedback by a user.

Note an explicit approval wouldn't have been in the format of a comment.

**Comment by Tomahna** [comment]
As far as I can tell it works fine. I'm not a user of lastFM though.

**Pull request merged**
