### PR TITLE
cinny: 3.1.0 -> 3.2.0

### PR DESCRIPTION
**Pull request by fufexan**
## Description of changes

Update `cinny` and `cinny-desktop` to 3.2.0.
[Changelog](https://github.com/cinnyapp/cinny/releases/tag/v3.2.0)

Couldn't build it as npm kept timing out. Perhaps OfBorg or others can.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by teutat3s** [comment]
```

error: hash mismatch in fixed-output derivation '/nix/store/0100v7s1zi09pnk839cfan2ziqx6xmj5-cinny-3.2.0-npm-deps.drv':
         specified: sha256-4R+To2LhcnEM9x1noo6MhCckyBKgPWiAi7zgDqAmaN0=
            got:    sha256-dVdylvclUIHvF5syVumdxkXR4bG1FA4LOYg3GmnNzXE=
```

**Comment by fufexan** [comment]
Oops, forgot about that. However, now I'm getting this error:
```
cinny> Executing npmBuildHook
cinny> > cinny@3.2.0 build
cinny> > vite build
cinny> vite v4.3.9 building for production...
cinny> [plugin:vite:resolve] Module "crypto" has been externalized for browser compatibility, imported by "/build/source/node_modules/@matrix-org/olm/olm.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
cinny> [plugin:vite:resolve] Module "path" has been externalized for browser compatibility, imported by "/build/source/node_modules/@matrix-org/olm/olm.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
cinny> [plugin:vite:resolve] Module "fs" has been externalized for browser compatibility, imported by "/build/source/node_modules/@matrix-org/olm/olm.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
cinny> [plugin:vite:resolve] Module "crypto" has been externalized for browser compatibility, imported by "/build/source/node_modules/matrix-js-sdk/lib/crypto/crypto.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
cinny> [plugin:vite:resolve] Module "util" has been externalized for browser compatibility, imported by "/build/source/node_modules/matrix-js-sdk/lib/crypto/crypto.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
cinny> node_modules/react-error-boundary/dist/react-error-boundary.esm.js (1:0) Module level directives cause errors when bundled, "use client" in "node_modules/react-error-boundary/dist/react-error-boundary.esm.js" was ignored.
cinny> node_modules/pdfjs-dist/build/pdf.js (1980:23) Use of eval in "node_modules/pdfjs-dist/build/pdf.js" is strongly discouraged as it poses security risks and may cause issues with minification.
cinny> ✓ 1832 modules transformed.
cinny> <--- Last few GCs --->
cinny> [1142:0x2e4c800]    21407 ms: Mark-sweep 2031.4 (2090.1) -> 2031.1 (2090.1) MB, 483.1 / 0.0 ms  (average mu = 0.286, current mu = 0.161) allocation failure; scavenge might not succeed
cinny> [1142:0x2e4c800]    22481 ms: Mark-sweep 2038.9 (2090.1) -> 2038.6 (2122.1) MB, 1024.0 / 0.0 ms  (average mu = 0.166, current mu = 0.046) allocation failure; scavenge might not succeed
cinny> <--- JS stacktrace --->
cinny> FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
cinny>  1: 0xab4728 node::Abort() [/nix/store/5l687mklyr9rhhbvvpvi93zv0zbbi4vg-nodejs-18.18.2/bin/node]
cinny>  2: 0x9a4839  [/nix/store/5l687mklyr9rhhbvvpvi93zv0zbbi4vg-nodejs-18.18.2/bin/node]
cinny>  3: 0xcc23e0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/nix/store/5l687mklyr9rhhbvvpvi93zv0zbbi4vg-nodejs-18.18.2/bin/node]
cinny>  4: 0xcc27ab v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/nix/store/5l687mklyr9rhhbvvpvi93zv0zbbi4vg-nodejs-18.18.2/bin/node]
cinny>  5: 0xea6cc5  [/nix/store/5l687mklyr9rhhbvvpvi93zv0zbbi4vg-nodejs-18.18.2/bin/node]
cinny>  6: 0xebb109 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/nix/store/5l687mklyr9rhhbvvpvi93zv0zbbi4vg-nodejs-18.18.2/bin/node]
cinny>  7: 0xe9789a v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/nix/store/5l687mklyr9rhhbvvpvi93zv0zbbi4vg-nodejs-18.18.2/bin/node]
cinny>  8: 0xe98c44 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/nix/store/5l687mklyr9rhhbvvpvi93zv0zbbi4vg-nodejs-18.18.2/bin/node]
cinny>  9: 0xe7855b v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/nix/store/5l687mklyr9rhhbvvpvi93zv0zbbi4vg-nodejs-18.18.2/bin/node]
cinny> 10: 0xe70f54 v8::internal::FactoryBase<v8::internal::Factory>::NewRawOneByteString(int, v8::internal::AllocationType) [/nix/store/5l687mklyr9rhhbvvpvi93zv0zbbi4vg-nodejs-18.18.2/bin/node]
cinny> 11: 0xe7b70d v8::internal::Factory::NewStringFromUtf8(v8::base::Vector<char const> const&, v8::internal::AllocationType) [/nix/store/5l687mklyr9rhhbvvpvi93zv0zbbi4vg-nodejs-18.18.2/bin/node]
cinny> 12: 0xcd4132 v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::NewStringType, int) [/nix/store/5l687mklyr9rhhbvvpvi93zv0zbbi4vg-nodejs-18.18.2/bin/node]
cinny> 13: 0xbbef2f node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding, v8::Local<v8::Value>*) [/nix/store/5l687mklyr9rhhbvvpvi93zv0zbbi4vg-nodejs-18.18.2/bin/node]
cinny> 14: 0xa85d6f  [/nix/store/5l687mklyr9rhhbvvpvi93zv0zbbi4vg-nodejs-18.18.2/bin/node]
cinny> 15: 0x163166f  [/nix/store/5l687mklyr9rhhbvvpvi93zv0zbbi4vg-nodejs-18.18.2/bin/node]
cinny> /nix/store/mz369dli2v5pnrqwvcx48iw0axsv973x-npm-build-hook/nix-support/setup-hook: line 3:  1127 Aborted                 (core dumped) npm run ${npmWorkspace+--workspace=$npmWorkspace} "$npmBuildScript" $npmBuildFlags "${npmBuildFlagsArray[@]}" $npmFlags "${npmFlagsArray[@]}"
cinny> ERROR: `npm build` failed
cinny> Here are a few things you can try, depending on the error:
cinny> 1. Make sure your build script (build) exists
cinny>   If there is none, set `dontNpmBuild = true`.
cinny> 2. If the error being thrown is something similar to "error:0308010C:digital envelope routines::unsupported", add `NODE_OPTIONS = "--openssl-legacy-provider"` to your derivation
cinny>   See https://github.com/webpack/webpack/issues/14532 for more information.
error: builder for '/nix/store/p2290aqrzlxrxl72f7gpn7d0p8h23k41-cinny-3.2.0.drv' failed with exit code 1;
```

**Comment by pbsds** [comment]
I seem to get the same issue with cinny on master when i override with my config, but it passed in nixpkgs-review for this PR. However there i got the following error:

Result of `nixpkgs-review pr 267754` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>cinny-desktop</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>cinny</li>
  </ul>
</details>



```
cinny-desktop> building '/nix/store/qnsx4aza03chyps1r59a5g73jjvphffy-cinny-desktop-3.2.0.drv'
cinny-desktop> unpacking sources
cinny-desktop> unpacking source archive /nix/store/40yvrkp0q4vm6xxq05s08w3bvb30dzz5-source
cinny-desktop> source root is source/src-tauri
cinny-desktop> Executing cargoSetupPostUnpackHook
cinny-desktop> Finished cargoSetupPostUnpackHook
cinny-desktop> patching sources
cinny-desktop> Executing cargoSetupPostPatchHook
cinny-desktop> Validating consistency between /build/source/src-tauri/Cargo.lock and /build/cargo-vendor-dir/Cargo.lock
cinny-desktop> 427c427
cinny-desktop> < version = "3.2.0"
cinny-desktop> ---
cinny-desktop> > version = "3.2.1"
cinny-desktop> 2936c2936
cinny-desktop> < version = "1.0.107"
cinny-desktop> ---
cinny-desktop> > version = "1.0.108"
cinny-desktop> 2938c2938
cinny-desktop> < checksum = "6b420ce6e3d8bd882e9b243c6eed35dbc9a6110c9769e74b584e0d68d1f20c65"
cinny-desktop> ---
cinny-desktop> > checksum = "3d1c7e3eac408d115102c4c24ad393e0821bb3a5df4d506a80f85f7a742a526b"
cinny-desktop> 
cinny-desktop> ERROR: cargoHash or cargoSha256 is out of date
cinny-desktop> 
cinny-desktop> Cargo.lock is not the same in /build/cargo-vendor-dir
cinny-desktop> 
cinny-desktop> To fix the issue:
cinny-desktop> 1. Set cargoHash/cargoSha256 to an empty string: `cargoHash = "";`
cinny-desktop> 2. Build the derivation and wait for it to fail with a hash mismatch
cinny-desktop> 3. Copy the "got: sha256-..." value back into the cargoHash field
cinny-desktop>    You should have: cargoHash = "sha256-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=";
cinny-desktop> 
```

**Comment by pbsds** [comment]
It seems RAM is the deciding factor in triggering https://github.com/NixOS/nixpkgs/pull/267754#issuecomment-1814829936.
I tried adding `env.NODE_OPTIONS = "--max_old_space_size=4096";` to the derivation but it doesn't help.

When i move the build to a remote with more RAM and it seems to succeed.

**Comment by JohnRTitor** [comment]
@fufexan Could you rebase this?

**Comment by fufexan** [comment]
> @fufexan Could you rebase this?

Done.

**Comment by JohnRTitor** [comment]
@ofborg build cinny cinny-desktop

**Comment by JohnRTitor** [comment]
Result of `nixpkgs-review pr 267754` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>cinny</li>
    <li>cinny-desktop</li>
  </ul>
</details>

**Comment by JohnRTitor** [comment]
Looks like `cinny` can be [built just fine](https://github.com/NixOS/nixpkgs/pull/267754/checks?check_run_id=26510185987) by Ofborg, but `cinny-desktop` [errors out](https://logs.ofborg.org/?key=nixos/nixpkgs.267754&attempt_id=cc30ac58-fbdb-40e7-babb-ecb7485c2093) due to cargo.lock not matching, it is fetching 3.2.1's cargo.lock for some reason.

Can we update cinny-desktop to 3.2.1 here?

**Comment by fufexan** [comment]
@JohnRTitor we can't, as the `cinny` and `cinny-desktop` versions have to match. Best I can do is downgrade the Cargo.lock file. I'm running out of memory so I can't build it, maybe ofborg can.

**Comment by JohnRTitor** [comment]
@ofborg build cinny-desktop
@ofborg build cinny

**Comment by Qyriad** [comment]
cinny-desktop [tagged a version](https://github.com/cinnyapp/cinny-desktop/tree/v3.2.1) with no matching cinny version, so the idea that the versions have to match may actually be wrong

**Pull request merged**
