### PR TITLE
pythonPackages: removes Python2 broken packages

### PR DESCRIPTION
**Pull request by superherointj**
PR is ready for review.

--

Removes all **broken** Python 2 packages.
114 of 265. 43% of packages broken.

If something important breaks, we can always restore it. :-)

List of [broken](https://gist.github.com/superherointj/e479e2b3333273b629217444969f6da8) packages

```
appleseed
arrow
ase
bitbucket_api
bitbucket-cli
blivet
browsermob-proxy
cairocffi
cairosvg
cherrypi
cliapp
cmdtest
coilmq
construct
django_evolution
docker-py
dulwich
flask
flask_ldap_login
flit
flit-core
fontforge
gdcm
geant4
google-api-python-client
gdrivefs
hg-git
hgsvn
imagecodecs-lite
imbalanced-learn
ipykernel
ipython
jsonrpclib
jupyter_client
jupyter_console
koji
kicad
larch
Lasagne
ldaptor
libcloud
libgpiod
libvirt 
lirc
lpod
lsi
mapsplotlib
marionette-harness
marionette_driver
matplotlib
mercurial
meson
mlt
moinmoin
monosat
mozprofile
mozrunner
mozsvc
mwlib
mwlib-rl
nbformat
nevow
nixpart0
nixpart
notebook
nxt-python
openwrt-luci-rpc
pandas
#pillow <- Delayed removal
postorius
praw
privacyidea-ldap-proxy
pycangjie
pycarddav
pyexiv2
pykickstart
python-otr
pythonIRClib
pythonmagick
pyutil
qserve
remotecv
rivet
robotframework-ride
runsnakerun
rpm
rpkg
scikit-learn
scipy
seaborn
serversyncstorage
sequoia
sipsimple
smartdc
snug
sphinx
squaremap
subliminal
suds
tarman
thumbor
tokenizers
tokenize-rt
tokenserver
ttystatus
wptserve
werkzeug
wxPython
wxPython30 <- Removal delayed
vcrpy
xenomapper
yt
zeek
zbase32
zfec
```

### CODE REVIEW

**Comment by superherointj** [comment]
> Please put all the commits that move packages to python3 into extra PRs.

Hello @SuperSandro2000 

I have only fixed package `plover` for Python3 and it's already a separate commit.
This PR is mostly about removing packages or marking as broken packages.
First commit (`pythonPackages: remove python2 broken packages`) is a compilation of the removal of all Python 2 broken packages. All other commits were packages that depended on any of these packages. And were also broken by extension.

I consider the PR ready for review.

**Review by doronbehar — APPROVED** [review]
LGTM to me overall, but it'd be nice to get a second :+1: from someone else.

**Review by peti — CHANGES_REQUESTED** [review]
Please don't remove displaycal. It works fine and I need it to color calibrate my display.

**Review by davidak — CHANGES_REQUESTED** [review]
displaycal should not be removed, since people depend on it for their professional work

it's the only tool available to calibrate the display (except gnome color management)

**Comment by superherointj** [comment]
I have changed my mind on this PR. There is opposition for it. And it needs further improvements that I'm not willing to take. So I'm closing. I'm sorry people that contributed for it.

**Pull request closed without merging**
