### PR TITLE
Alphabetize

### PR DESCRIPTION
**Pull request by zimbatm**
###### Things done:
- [ ] Tested via `nix.useChroot`.
- [ ] Built on platform(s): .
- [ ] Tested compilation of all pkgs that depend on this change.
- [ ] Tested execution of binary products.
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Keeping long lists in alphabetical order in general helps find stuff more quickly with the eyes.

Do we agree that it's a good thing overall ?

In vim it's fairly easy: Shift-V, select the lines and `:sort`. Emacs probably has an equally-easy way to do it as well.

### CODE REVIEW

**Comment by dezgeg** [comment]
:+1: from me.

**Comment by jagajaga** [comment]
;+1:

**Comment by edolstra** [comment]
@zimbatm Would you mind setting your real name in Git commits (`git config user.name`)?

**Comment by zimbatm** [comment]
@edolstra I prefer to use my nickname on the Internet in general if I can.

**Comment by edolstra** [comment]
@zimbatm Hm, I'm uncomfortable with pseudonymous contributors with direct commit access. For reasons of accountability, I'd prefer to know who has commit access. Is there a reason why you can't use your real name?

**Comment by zimbatm** [comment]
@edolstra it's the first time I've had this issue in the last 15 years so I don't know what to respond. It took me quite a bit of effort to dissociate my online and official identities as I prefer to stay anonymous on the web.

I understand that you want to protect your project and I don't mind sharing my personal information with you. Would it be okay if I sent you a copy of my ID card or some other references of your liking instead ? I also met with a couple of people at NixConf and FOSDEM that can vouch for my real existence.

**Pull request merged**
