### PR TITLE
Upgrade duplicity to 0.8.09.

### PR DESCRIPTION
**Pull request by sdier**
###### Motivation for this change
Upgrade duplicity to 0.8.09 from 0.7.19.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sdier** [comment]
Bah I wanted to just save what I has written so far but forget this triggers all the automation.  Will mark this as ready when its ready.

**Comment by sdier** [comment]
Waiting on https://github.com/NixOS/nixpkgs/pull/78116 first...

**Comment by jtojnar** [comment]
Duplicate of #76988

**Comment by FRidh** [comment]
We're at 0.8.10 so closing.

**Pull request closed without merging**
