### PR TITLE
chromium: use llvm 17

### PR DESCRIPTION
**Pull request by yu-re-ka**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by yu-re-ka** [comment]
Built chromium, electron_26 on x86_64-linux

**Comment by emilylange** [comment]
Is it okay for you, @yu-re-ka, if we wait with this until `23.05` is EOL, so things don't diverge even further between the currently maintained releases (`23.05`, `23.11`, `unstable`)?

LGTM otherwise and that updated patch makes sense and is needed.
Thanks :)

**Comment by yu-re-ka** [comment]
@emilylange NixOS 23.05 is now deprecated, so would you mind having another look?

**Review by emilylange — APPROVED** [review]
Result of `nixpkgs-review pr 274863` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>redisinsight</li>
    <li>sharedown</li>
    <li>sitespeed-io</li>
  </ul>
</details>
<details>
  <summary>64 packages built:</summary>
  <ul>
    <li>authy</li>
    <li>bilibili</li>
    <li>bitwarden</li>
    <li>camunda-modeler</li>
    <li>chromium</li>
    <li>chromium.sandbox</li>
    <li>deltachat-desktop</li>
    <li>drawio</li>
    <li>drawio-headless</li>
    <li>electron (electron_28)</li>
    <li>electron_26</li>
    <li>electron_27</li>
    <li>element-desktop</li>
    <li>element-desktop-wayland</li>
    <li>fast-cli</li>
    <li>freetube</li>
    <li>headset</li>
    <li>heroic</li>
    <li>heroic-unwrapped</li>
    <li>itch</li>
    <li>jitsi-meet-electron</li>
    <li>mattermost-desktop</li>
    <li>mermaid-cli</li>
    <li>mermaid-filter</li>
    <li>micropad</li>
    <li>nix-tour</li>
    <li>open-stage-control</li>
    <li>pandoc-drawio-filter</li>
    <li>pandoc-drawio-filter.dist</li>
    <li>percollate</li>
    <li>playwright-test</li>
    <li>pocket-casts</li>
    <li>podman-desktop</li>
    <li>pritunl-client</li>
    <li>puppeteer-cli</li>
    <li>python310Packages.mkdocs-drawio-exporter</li>
    <li>python310Packages.mkdocs-drawio-exporter.dist</li>
    <li>python310Packages.pytest-playwright</li>
    <li>python310Packages.pytest-playwright.dist</li>
    <li>python311Packages.mkdocs-drawio-exporter</li>
    <li>python311Packages.mkdocs-drawio-exporter.dist</li>
    <li>python311Packages.pytest-playwright</li>
    <li>python311Packages.pytest-playwright.dist</li>
    <li>revolt-desktop</li>
    <li>standardnotes</li>
    <li>stretchly</li>
    <li>super-productivity</li>
    <li>teams-for-linux</li>
    <li>terra-station</li>
    <li>thedesk</li>
    <li>threema-desktop</li>
    <li>tutanota-desktop</li>
    <li>uhk-agent</li>
    <li>uhk-udev-rules</li>
    <li>uivonim</li>
    <li>ungoogled-chromium</li>
    <li>ungoogled-chromium.sandbox</li>
    <li>vesktop</li>
    <li>vhs</li>
    <li>vieb</li>
    <li>wayback</li>
    <li>webcord</li>
    <li>webcord-vencord</li>
    <li>webtorrent_desktop</li>
  </ul>
</details>

---

```bash
# git describe --abbrev=40
24.05-pre-13723-g3349a3d56d594dfe809040279af58168d7b3147e
# nix-build nixos/tests/chromium.nix -A ungoogled -A stable
/nix/store/9a82laaa07q1qkzx8vq1h1986vs9l7c0-vm-test-run-chromium-ungoogled
/nix/store/2s3yvmfrycz4ia89dnfqd3fvkqchhgqp-vm-test-run-chromium-stable
```

**Pull request merged**
