### PR TITLE
[21.11] element{-desktop,}: 1.10.7 -> 1.10.8

### PR DESCRIPTION
**Pull request by sumnerevans**
(cherry picked from commit 1c223b63439ce7ddb5ac36138c03ba306794a9e1)

###### Description of changes

Closes #164548

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
@ofborg eval

**Comment by genofire** [comment]
@Ma27 but necessary, if you see that nothing happen with: https://github.com/NixOS/nixpkgs/pull/164548 (no reaction, comment or merge)

**Comment by Ma27** [comment]
No idea what's wrong here, opened #167178 as replacement.

@genofire  not sure what you mean. Also, why did you open a new issue if there are already pending PRs for the problem?
@cole-h any idea why I don't get CCed for element-{web,desktop} updates from ofborg anymore?

**Comment by Ma27** [comment]
Will try to do that soonish - no guarantees though :)

**Comment by Ma27** [comment]
@cole-h this is apparently because updating these packages only changes a JSON file and thus the `builtins.unsafeGetAttrPos`-check in `ofborg/src/maintainers.nix` doesn't work. I don't have the time to think of a good fix though, sorry!

@sumnerevans until this is fixed, please piing me directly when updating element, then I'll be able to respond quicker and take care of the backports more actively, thanks :)

**Pull request closed without merging**
