### PR TITLE
[WIP] gitlab: 11.10.4 -> 11.11.3

### PR DESCRIPTION
**Pull request by mmahut**
###### Motivation for this change

Major gitlab upgrade 11.10.4 -> 11.11.3.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by mmahut** [comment]
The builds appears to fail which seems possibly an usage of a different ``ar`` command?

```
ar  /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/libs/opt/libares.a /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares__close_sockets.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares__get_hostent.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares__read_line.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares__timeval.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_cancel.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_create_query.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_data.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_destroy.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_expand_name.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_expand_string.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_fds.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_free_hostent.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_free_string.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_getenv.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_gethostbyaddr.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_gethostbyname.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_getnameinfo.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_getopt.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_getsock.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_init.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_library_init.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_llist.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_mkquery.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_nowarn.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_options.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_parse_a_reply.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_parse_aaaa_reply.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_parse_mx_reply.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_parse_naptr_reply.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_parse_ns_reply.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_parse_ptr_reply.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_parse_soa_reply.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_parse_srv_reply.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_parse_txt_reply.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_platform.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_process.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_query.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_search.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_send.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_strcasecmp.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_strdup.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_strerror.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_timeout.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_version.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_writev.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/bitncmp.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/inet_net_pton.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/inet_ntop.o /nix/store/fa2iz4jdcmjhcqqn63kv5mhv1djabby6-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/windows_port.o
ar: invalid option -- '/'
```

ping @flokli for assistance

**Comment by flokli** [comment]
Here, it fails in the grpc gem too, but for me while building boringssl, which seems to be vendored inside the grpc gem :laughing:

I looked into https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/ruby-modules/gem-config/default.nix#L200, so we seem to be able to build a grpc gem successfully, but I'm not sure how to build it properly with bundix.

@alyssais @zimbatm @manveru, any pointers?

**Comment by flokli** [comment]
I was mistaken - had a remote builder, which swallowed some of the output. For me, it fails in the `ar` step, too.

It looks like the `rcs` part from `ar rcs` in grpc's Makefile is being thrown away.

**Comment by mmahut** [comment]
@alyssais @zimbatm @manveru @flokli any help is welcome :)

**Comment by flokli** [comment]
My wild guess would be that the `ar` line became too long - we could eventually tweak grpc's Makefile to pass relative paths to `ar` - but as I said, that's just a wild guess.

**Comment by bgamari** [comment]
The `ar` command line looks just plain wrong:
```
ar  /nix/store/lyack7rns5h345aikzck59l9hsxfxdmn-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/libs/opt/libz.a /nix/store/lyack7rns5h345aikzck59l9hsxfxdmn-ruby2.5.5-grpc-1.19.0/lib/ruby/gems/2.5.0/gems/grpc-1.19.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/adler32.o  ...
```
It is missing a command character.

It looks to me like the grpc build system [expects](https://github.com/grpc/grpc/blob/9ed8734efb9b1b2cd892942c2c6dd57e903ce719/src/ruby/ext/grpc/extconf.rb) the `AR` environment variable to contain not just the path of the `ar` executable, but also the flags `rcs`.

**Comment by bgamari** [comment]
I have fixed this and opened #64550 bumping gitlab to 12.0.3.

**Comment by mmahut** [comment]
Thank you, moving this party to #64550.

**Pull request closed without merging**
