### PR TITLE
Cargo has incorrect hash

### PR DESCRIPTION
**Pull request by sjmackenzie**
###### Motivation for this change

Cargo has incorrect hash
###### Things done

Corrected hash

### CODE REVIEW

**Comment by joachifm** [comment]
So it was never correct or is this a blind hash change?

**Comment by sjmackenzie** [comment]
I don't think it was correct, reason being, I've seen these sorts of things on fractalide whereby the cargo deps don't change and thus the system still compiles correctly. The correct procedure is to `nix-collect-garbage` (after deleting the `result`) and then you'll know.

**Comment by sjmackenzie** [comment]
What is a blind hash change? Something I'll randomly choose? If so, no it wasn't that... I wouldn't submit that kinda nonsense to upstream.

**Comment by joachifm** [comment]
A blind hash change is to update the hash to fix a mismatch without looking into why the mismatch occurred. That's why I ask whether it was wrong all along.

**Comment by sjmackenzie** [comment]
@joachifm "All checks have passed" Does that satisfy you?

**Comment by the-kenny** [comment]
@sjmackenzie Please calm done. Everyone here tries to do it's best. We're all working in our free time on this.

We'll have to investigate this hash-change some more. The original hash definitely worked, so we have to check if there's an impurity that caused the hash to change on your machine. We saw this with other packages before.

**Comment by sjmackenzie** [comment]
my machine and travis' machine you surely mean?

**Comment by the-kenny** [comment]
That just means that the new hash is correct *right now*. Usually it's caused by an impurity. There's no use in changing the hash every other day, we have to fix this impurity.

**Comment by sjmackenzie** [comment]
Ah! I see now, christ, how do you track down such a vile thing?

**Comment by the-kenny** [comment]
I don't see an obvious impurity in the `Cargo.toml` of `cargo` right now - the only candidate I can find is the `rust-installer` submodule in `src/`. Last commit was 7 days ago. The `fetch-cargo-deps` script contains a `TODO: Test with git submodules`, so it might be related. I'll try to investigate into this some more.

**Comment by lethalman** [comment]
It usually may be if deps use fetchgit and such. Travis says that nothing has changed somit's not very helpful. Any ody can build it locally to confirm the sha change?

**Comment by the-kenny** [comment]
@lethalman I can confirm: 

```
 % nix-build . -A rustBeta.cargo  --check --option use-binary-caches false
output path ‘/nix/store/m4i9jf6f5nav8wzg1fsns4gl2n9378jv-cargo-beta-2016-07-25-fetch’ has r:sha256 hash ‘1p1ygabg9k9b0azm0mrx8asjzdi35c5zw53iysba198lli6bhdl4’ when ‘055ky0lkrcsi976kmvc4lqyv0sjdpcj3jv36kz9hkqq0gip3crjc’ was expected
```

`fetch-cargo-deps` seems to mirror what `nix-prefetch-git` does to make clones reproducible. I wonder if we could just remove `.git` entirely and be done with it.

**Comment by lethalman** [comment]
So merging for now until someone has a better solution. Thanks.

**Comment by edolstra** [comment]
This PR doesn't fix the real problem: that `cargo.nix` uses `fetchgit`, which should never be used because it's not deterministic. (Thus, the hash will probably change randomly in the future.) Instead, it should use `fetchFromGitHub` which does provide a predictable result.

**Comment by edolstra** [comment]
Oh sorry, the `depsSha256` is passed to `fetchCargo`, which suggests *that* function is not deterministic and the whole Rust build infrastructure in Nixpkgs is broken.

**Comment by sjmackenzie** [comment]
That's correct! How does one fix this system?

**Comment by the-kenny** [comment]
@edolstra `fetchCargo` uses `git` internally and replicates some steps used by `nix-prefetch-git`. I agree that we should get rid of the git usage there. I hope I can find some time to get in touch with the cargo-registry guys to work on this. Most crates are on Github - there we can just fetch the necessary ref via http.

**Pull request merged**
