### PR TITLE
open-vm-tools: Fix rebooting on NixOS

### LINKED ISSUE #30717: open-vm-tools: vmtoolsd uses wrong path to `shutdown`
The VMWare guest service uses `open-vm-tools`, and when doing a guest restart, `vmtoolsd` will run the command `/sbin/shutdown`, which of course doesn't exist.

I believe the only way to fix this is to patch https://github.com/vmware/open-vm-tools/blob/e0a7b4e98bd6d6af06d31212dfdc82610d37e4d3/open-vm-tools/lib/system/systemLinux.c#L366 - it is the only call to `system()` I could find easily so I assume that's the only thing that needs fixing.

I think the easiest patch is to remove the `/sbin/` before `shutdown`, it will then get the correct `shutdown` from the system path.

/cc @joamaki

### PR DESCRIPTION
**Pull request by wmertens**
Fixes #30717 - hopefully… untested ;)

### CODE REVIEW

**Comment by wmertens** [comment]
the package itself builds fine but the first travis build fails on an unrelated issue with `cargo`. I think it will work, and it will not work less than it does now…

**Comment by Mic92** [comment]
Can you test, if that works?

**Comment by peterhoeg** [comment]
I've just tried here using ESX 6.5 and it works!

**Comment by wmertens** [comment]
\o/

**Comment by wmertens** [comment]
Ok I'll merge and then in a few days I'll backport it to stable

**Comment by peterhoeg** [comment]
I only tested it on stable... Should probably have mentioned that.

**Comment by wmertens** [comment]
:) Well I'm only in the position to test it once it hits Hydra. It's a very
low-risk change - it's not working right now and at worst the patch has no
effect.

**Pull request merged**
