### PR TITLE
xcbuild: various improvements

### PR DESCRIPTION
**Pull request by stephank**
###### Description of changes

These tweaks specifically target LLVM compiler-rt, which I need to modify for Darwin.

The LLVM build tries to call `xcrun` but we currently don't make it available and ignore the errors. That's disabling critical functionality however. A change in this PR makes `xcrun` available separately, which is just a bunch of files and shell scripts. That makes it much easier to put it in the closure of stdenv on Darwin.

The other change is to actually check the `-sdk` flag if passed. The LLVM build calls `xcrun` multiple times to detect different SDKs, but it should only succeed for the target platform.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by matthewbauer — APPROVED** [review]
Looks good to me. Haven't tested it or anything, but I think the tests are somewhat comprehensive.

**Comment by stephank** [comment]
Hmm, should I target staging for this? It doesn't touch stdenv, but I didn't realize it'd be 5001+. 🙃

**Comment by matthewbauer** [comment]
> Hmm, should I target staging for this? It doesn't touch stdenv, but I didn't realize it'd be 5001+. 🙃

I think it's fine to go to master. IIRC it's not a lot more than 5000.

**Comment by zowoq** [comment]
Almost 17000 rebuilds across both darwin platforms, this should go to staging.

**Comment by stephank** [comment]
I updated the base branch to staging.

**Pull request merged**
