### PR TITLE
nix-prefetch-github: 2.2 -> 2.3

### PR DESCRIPTION
**Pull request by seppeljordan**
###### Motivation for this change
The software had a new release upstream.  This PR updates the nix-prefetch-github in nixpkgs.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by mmahut — APPROVED** [review]
- [X] reviewed the diff and commit messages
- [X] made sure ofBorg evals
- [X] run nix-review without any failures
- [X] run and tested the binaries

**Review by worldofpeace — CHANGES_REQUESTED** [review]
Doesn't look like you need requests anymore https://github.com/seppeljordan/nix-prefetch-github/commit/199e981b245dd7a4c7e58f0160af1159c3f24fb9

**Comment by seppeljordan** [comment]
@worldofpeace Thanks for catching that.  I made a new commit explaining the change and I also tested the resulting executables on my machine.  If you want me to squash those commits and force push, let me know.

**Review by worldofpeace — APPROVED** [review]
Looks good from my side.

**Comment by worldofpeace** [comment]
Thanks you @seppeljordan

**Pull request merged**
