### PR TITLE
Revert "phpfpm service: restructured pool configuration"

### PR DESCRIPTION
**Pull request by bjornfor**
###### Motivation for this change

This reverts commit 6b3f5b5a421fe3422e9ef63a3fd690178c36163e because it
introduced a non-backwards compatible change in the phpfpm interface,
without explaining why it's needed and/or better than what we have. I
feel reworking the interface needs more discussion, so in the mean time
let's keep the old interface.

Commit 98e419c0e27dd21e9dee0b915876ea60 ("tt-rss service: init at 16.3")
depends on the new interface, so this commit updates the tt-rss service
to work with the services.phpfpm.poolConfigs interface.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bjornfor** [comment]
CC @zohl, @rickynils.

**Comment by zohl** [comment]
@bjornfor, hello!

I really haven't explained why I changed the service, so let me amend it here.

The only motivation I had is a convenient way to refer to `listen` option (see https://github.com/NixOS/nixpkgs/pull/16132/commits/98e419c0e27dd21e9dee0b915876ea603b833057#diff-7d6c11d6cd8a6fa7d48ba345715508f5R486) and to setup a virtual host, that will work with that phpfpm pool.

Of course the option can be extracted somehow from `extraConfig` but I don't think this is a good way. Moreover this option is mandatory, so it makes a sense to have a separate variable for it.

The next problem: `poolConfigs` is of `attrsOf lines` type, whereas `{listen = ...; extraConfig = ...; }` is of different type. So I took [this PR](https://github.com/NixOS/nixpkgs/pull/15862) as an example and rewrite the service in the way it was merged.

I did check that no service relies on phpfpm, so It won't break things in the repo.
I did check that `tt-rss` works fine with the new service.
I did not give a warning that it will break users' configurations and I'm afraid this caused all the back-and-forth changes.

So, I would like to check the following:
1) closing eyes on breaking changes, is the new structure of `phpfpm` service acceptable?
2) if yes, what is the right way to introduce the changes?

**Comment by bjornfor** [comment]
Hi @zohl!

Thanks for the feedback.

I don't want to extract "listen" option from text strings either. If you look at this PR you see that I created a separate variable for the php socket, and use this variable when generating the poolConfigs text.

> So, I would like to check the following:
> 1) closing eyes on breaking changes, is the new structure of phpfpm service acceptable?

I'm not familiar with all the phpfpm options, but my first reaction to the new interface was something like "allright, the listen option is important, but it's not the _only_ thing I might want to have structured access to". I think this change is only the beginning of a series of patches adding more and more structured options to the phpfpm interface. In the end, why not have structured options for everything? The problem is the amount of work to keep the interface working and matching various php versions etc. It might be a maintenance nightmare.

So instead of enforcing _some_ structure on phpfpm, why not add the structure that is needed[1] outside of the phpfpm interface, and generate the text when needed (like this PR does)?

Another alternative is possibly to change the option type to untyped "attrset", to keep ourself from spending too much time on the phpfpm interface.

> 2) if yes, what is the right way to introduce the changes?

IMHO, the best way would be to introduce the new interface alongside the old one. Throw a warning in release N+1 when the old interface is used and remove the old interface in release N+2. A less good alternative is the current situation, where the interface is completely changed in a single commit.

[1] The needed structure varies from use case to use case.

**Comment by bjornfor** [comment]
@zohl: Does merging this PR break anything for you?

**Comment by globin** [comment]
I'd personally prefer the implementation @zohl added, as it is heading towards a more declarative config. Obviously more options should/could be added in the future, I was actually going to look at the whole PHP config stuff after #15862 and #12895 are finished because we have to migrate some PHP sites to NixOS and it's easier to work with specific configuration options especially when mapping over pools and merging defaults etc. instead of working with strings.

**Comment by bjornfor** [comment]
@globin: My reaction to this is more about the non-backwards compatible part, not the new interface itself. I don't mind more structured options, but I'd prefer to have the timespan of a NixOS release to do the migration.

Well, thinking about it, I think there may be a lot of churn in the phpfpm interface going forward if we're going to introduce structured options one by one, so keeping the "text" interface might be a way out for those who like stability (like me). (That's also why I suggested looking into making the interface a untyped "attrset", so we don't impose restrictions on what to generate and hopefully eliminate some churn in the NixOS module.)

Merging this PR does not mean "no structured phpfpm ever", it just means letting poolConfigs live on (for at least a NixOS release more). Structured options can be used side by side with the old interface.

**Comment by globin** [comment]
I understand that and I could imagine an implementation with both the old config available and the new structured, too? Do you have the time to implement this in this PR or do you prefer merging and having someone else (possibly me soon) work on that in a new PR?

**Comment by bjornfor** [comment]
> I understand that and I could imagine an implementation with both the old config available and the new structured, too?

Yes, exactly.

> Do you have the time to implement this in this PR or do you prefer merging and having someone else (possibly me soon) work on that in a new PR?

I don't plan working on structured options. I have other issues that are more important to me. (For instance, I'd like to use NixOS at work, but for that I need Evolution EWS (https://github.com/NixOS/nixpkgs/issues/12847) and better printing support. Ubuntu manages to print, NixOS does not.)

**Comment by zohl** [comment]
@bjornfor, sorry for rolling in a little while after the main part of discussion, I'll just add my two cents.

First of all,
>Does merging this PR break anything for you?

No, `tt-rss` should work normally unless the one will try to specify a non-standard phpfpm pool. But this is an exotic case, so let's ignore it for now.

>In the end, why not have structured options for everything?

I guess it becomes a common pattern in nixpkgs, when the core parameters of a service are declared as options and the rest ones are specified in `extraConfig` or similar text variable. I followed this idea, but `listen` was the only parameter I needed.

In the new version of the service, the one who wanted another option to be a separate variable, could make a simple patch that would also keep backwards compatibility. This approach would allow us to distribute a workload between developers and avoid maintenance hell as a tricky/rare option can be left in `extraConfig`.

Anyway, this breaks compatibility with the current version of `phpfpm`. If I get a free minute by any chance, I'll try to think about the solution too.

**Comment by bjornfor** [comment]
@zohl:

> No, tt-rss should work normally unless the one will try to specify a non-standard phpfpm pool. But this is an exotic case, so let's ignore it for now.

To be nitpicky, you don't _have_ to change the phpfpm interface for that use case either (as shown in this PR), but I can understand its appeal. :-)

> I guess it becomes a common pattern in nixpkgs, when the core parameters of a service are declared as options and the rest ones are specified in extraConfig or similar text variable.

True. But several services also have the ```configText``` option which overrides the generated config from the other NixOS options. I like having both interfaces, because sometimes the structured options are incomplete.

Anyway, I'll merge this then.

**Pull request merged**
