### PR TITLE
gnutls: 3.8.0 -> 3.8.1

### PR DESCRIPTION
**Pull request by vcunat**
https://lists.gnupg.org/pipermail/gnutls-help/2023-August/004834.html

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
@ofborg eval

**Comment by risicle** [comment]
Built `passthru.tests` on macos 10.15 & nixos x86_64. `pkgsStatic` & `pkgsMusl` variants build happily x86_64.

**Review by risicle — APPROVED** [review]

**Comment by trofi** [comment]
Looks like this release renamed `GNUTLS_NO_EXTENSIONS` enum:

> ** libgnutls: %GNUTLS_NO_EXTENSIONS has been renamed to %GNUTLS_NO_DEFAULT_EXTENSIONS.

 and broke `openconnect` in `staging`:

```
error: builder for '/nix/store/iypwb7495y37zn0g50cbkx1p6rch6jrp-openconnect-9.12.drv' failed with exit code 2;
       last 10 log lines:
       > gnutls-dtls.c: In function 'start_dtls_handshake':
       > gnutls-dtls.c:413:84: error: 'GNUTLS_NO_EXTENSIONS' undeclared (first use in this function); did you mean 'GNUTLS_EXT_NONE'?
       >   413 |         err = gnutls_init(&dtls_ssl, GNUTLS_CLIENT|GNUTLS_DATAGRAM|GNUTLS_NONBLOCK|GNUTLS_NO_EXTENSIONS);
       >       |                                                                                    ^~~~~~~~~~~~~~~~~~~~
       >       |                                                                                    GNUTLS_EXT_NONE
       > gnutls-dtls.c:413:84: note: each undeclared identifier is reported only once for each function it appears in
       > make[1]: *** [Makefile:1442: libopenconnect_la-gnutls-dtls.lo] Error 1 shuffle=3602025659
       > make[1]: *** Waiting for unfinished jobs....
       > make[1]: Leaving directory '/build/openconnect-9.12'
       > make: *** [Makefile:922: all] Error 2 shuffle=3602025659
       For full logs, run 'nix log /nix/store/iypwb7495y37zn0g50cbkx1p6rch6jrp-openconnect-9.12.drv'.
```

**Comment by vcunat** [comment]
Let's bring that upstream:
https://gitlab.com/gnutls/gnutls/-/merge_requests/1734#note_1507426647

**Comment by risicle** [comment]
#248400 gnutls: add openconnect and samba to passthru.tests

**Pull request merged**
