### PR TITLE
Fix device wait in containers

### PR DESCRIPTION
**Pull request by kampfschlaefer**
###### Motivation for this change

It irks me that configuring the network inside the containers works different then outside of the containers. And all because inside the container there is no udev to tell systemd that a network device is already present. The most specific case where the problem bit me is when moving physical interface into the container. With this patch there is finally a way this can work without writing ip-commands by hand.

Based upon the idea from @bosu in #9836 I wrote tests and added code to make network configuration inside containers work the same as outside. There are also new tests for using physical interfaces inside the container, put the physical interface in a bridge, in a bond and in a bond which is put in a bridge.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [x] Linux
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by fpletz — APPROVED** [review]

**Comment by fpletz** [comment]
LGTM, but needs a rebase to resolve the conflicts. Maybe you could squash a few of the commits?

**Comment by kampfschlaefer** [comment]
@fpletz thanks for the review. rebased and a bit of squashing. Also ordered the tests in subtests, was on my todo for this.

**Comment by Mic92** [comment]
Does the container tests are working all properly for you?

**Comment by kampfschlaefer** [comment]
@Mic92 Thanks for the catch! the extraVeth test is failing in this PR, but also on last nixos-unstable-small. so there is #19391.

Apart from that, the container tests work here.

**Comment by Mic92** [comment]
Thanks!

**Comment by vcunat** [comment]
This breaks evaluation of nixos tests; I verified by reverting the merge locally. Test case:
```
$ nix-build nixos/release.nix -A tests.networking.scripted.sit.x86_64-linux --dry-run
```

**Comment by kampfschlaefer** [comment]
@vcunat not within this feature branch (on ubuntu14). But on master. interesting…

see #19464 for a fix.

Gotta set up my own hydra and have it run all release tests on my feature branches…

**Comment by Mic92** [comment]
I currently sit in a train, where I cannot download the test dependencies,
but does the current patch fix the problem?

```
diff --git a/nixos/modules/tasks/network-interfaces-scripted.nix b/nixos/modules/tasks/network-interfaces-scripted.nix
index 89ee13d..a44a73b 100644
--- a/nixos/modules/tasks/network-interfaces-scripted.nix
+++ b/nixos/modules/tasks/network-interfaces-scripted.nix
@@ -333,7 +333,7 @@ in

         createSitDevice = n: v: nameValuePair "${n}-netdev"
           (let
-            deps = optional (v.dev != null) (deviceDependency v.dev);
+            deps = (optionals (v.dev != null) (deviceDependency v.dev));
           in
           { description = "6-to-4 Tunnel Interface ${n}";
             wantedBy = [ "network-setup.service" (subsystemDevice n) ];
```

**Comment by Mic92** [comment]
The new systemd-nspawn module still uses the deprecated `optionSet` function, but this is a different issue.

**Comment by groxxda** [comment]
@Mic92 Yes, I'm afraid that code was written before the deprecation. I can look into it, but I won't have time for it too soon :wink:

**Comment by vcunat** [comment]
The patch certainly fixes evaluation of that particular test.

**Pull request merged**
