### PR TITLE
melpa-packages: 2020-05-11

### PR DESCRIPTION
**Pull request by rasendubi**
###### Things done

- [x] Manually reviewed generated file to ensure no new errors are introduced
- [x] Tested with my emacs setup
- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by adisbladis** [comment]
@rasendubi Are you aware of the script `update-from-overlay` that doesn't just update melpa packages but also updates elpa?
It pulls from https://github.com/nix-community/emacs-overlay, so it's pretty much instant and formats commit messages nicely for you.

**Comment by rasendubi** [comment]
No, I didn't!

I've updated my PR using it and also mentioned it in melpa/elpa-packages.nix so the next soul could find it.

**Comment by rasendubi** [comment]
ping @adisbladis

**Comment by adisbladis** [comment]
> I've updated my PR using it and also mentioned it in melpa/elpa-packages.nix so the next soul could find it.

Cool, thanks!

**Comment by timor** [comment]
Is there a policy about backporting melpa into current NixOS releases?
E.g. at the time of writing this, 20.03 contains a version of magit which has some issues that have been fixed in the version present in this commit.  Is there some kind of process to verify that the melpa/elpa set is sane, or ist just being updated every now and then?

**Comment by adisbladis** [comment]
@timor There is no policy around this, no. Typically backporting Emacs packages is not done but there is nothing stopping anyone from doing so.

**Pull request merged**
