### PR TITLE
{emojione, hackneyed}: Disable on Darwin

### LINKED ISSUE #343351: Build failure: {emojione, hackneyed} builds hang on Darwin
### Steps To Reproduce

1. Build any of the above on Darwin
2. Watch the build hang after a few minutes

### Build log

Similar issues across all three when they try to run Inkscape on the desktop during the build phase. Additional failures come from Fontconfig. Always ends in a builder hang.

Typical errors (from emojione).

```
Fontconfig error: No writable cache directories
File path /dev/shm/0036-20e3.png includes directory that doesn't exist. Skipping.
File path /dev/shm/0038-20e3.png includes directory that doesn't exist. Skipping.
File path /dev/shm/0037-20e3.png includes directory that doesn't exist. Skipping.
File path /dev/shm/0039-20e3.png includes directory that doesn't exist. Skipping.
File path /dev/shm/1f004.png includes directory that doesn't exist. Skipping.
File path /dev/shm/1f0cf.png includes directory that doesn't exist. Skipping.
2024-09-20 20:48:12.728 .inkscape-wrapped[996:2589192] +[NSXPCSharedListener endpointForReply:withListenerName:replyErrorCode:]: an error occurred while attempting to obtain endpoint for listener 'ClientCallsAuxiliary': Connection interrupted
2024-09-20 20:48:12.728 .inkscape-wrapped[995:2589188] +[NSXPCSharedListener endpointForReply:withListenerName:replyErrorCode:]: an error occurred while attempting to obtain endpoint for listener 'ClientCallsAuxiliary': Connection interrupted
2024-09-20 20:48:12.729 .inkscape-wrapped[994:2589181] +[NSXPCSharedListener endpointForReply:withListenerName:replyErrorCode:]: an error occurred while attempting to obtain endpoint for listener 'ClientCallsAuxiliary': Connection interrupted
2024-09-20 20:48:12.730 .inkscape-wrapped[997:2589200] +[NSXPCSharedListener endpointForReply:withListenerName:replyErrorCode:]: an error occurred while attempting to obtain endpoint for listener 'ClientCallsAuxiliary': Connection interrupted
2024-09-20 20:48:12.731 .inkscape-wrapped[998:2589198] +[NSXPCSharedListener endpointForReply:withListenerName:replyErrorCode:]: an error occurred while attempting to obtain endpoint for listener 'ClientCallsAuxiliary': Connection interrupted
2024-09-20 20:48:12.731 .inkscape-wrapped[999:2589199] +[NSXPCSharedListener endpointForReply:withListenerName:replyErrorCode:]: an error occurred while attempting to obtain endpoint for listener 'ClientCallsAuxiliary': Connection interrupted
make: *** [Makefile:117: build/svg-bw/0039-20e3.svg] Trace/BPT trap: 5
make: *** [Makefile:117: build/svg-bw/0037-20e3.svg] Trace/BPT trap: 5
make: *** [Makefile:117: build/svg-bw/0038-20e3.svg] Trace/BPT trap: 5
make: *** [Makefile:117: build/svg-bw/0036-20e3.svg] Trace/BPT trap: 5
make: *** [Makefile:117: build/svg-bw/1f004.svg] Trace/BPT trap: 5
make: *** [Makefile:117: build/svg-bw/1f0cf.svg] Trace/BPT trap: 5```

### Notify maintainers

@abbradar 
@somasis 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by sarahec**
## Description of changes

These fail to build on Darwin due to running a desktop app as part of the build and breaking the sandbox. Disabled on Darwin only.

Fixes #343351

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by sarahec** [comment]
@emilazy This needs to land before the desktop hook. These build errors hang nixpkgs-review if unpatched.

**Comment by sarahec** [comment]
Result of `nixpkgs-review pr 343353` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)

**Comment by viraptor** [comment]
Same as the other PR - does setting the Inkscape profile directory and HOME (for fontconfig's .cache usage) fix the issue instead?

**Comment by sarahec** [comment]
No, due to requiring access to the system UI. Also, the use of `xcursorgen` in `hackneyed` renders it incompatible with darwin. (`xcursorgen` isn't supported there.)

**Comment by sarahec** [comment]
@viraptor if you can do me a favor, look `/etc/nix.conf` and see if sandboxing is indeed enabled. I've discovered that the `--options sandbox {true,false}` flag does nothing for nix on Darwin.

**Comment by sarahec** [comment]
For reference, #343629 is the other PR. Since the icons were simple PNG we could convert using cairosvg. (The author was willing to work with me so we could make the change.)

**Comment by sarahec** [comment]
Huh, they build now on the mac. The other problems must have been a glitch.

Closing.

**Pull request closed without merging**
