### PR TITLE
ddnet: 16.8 -> 16.9

### PR DESCRIPTION
**Pull request by atemp**
###### Description of changes

https://ddnet.org/downloads/#16.9

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ncfavier** [comment]
Thanks! Please link to the changelog (https://ddnet.org/downloads/#16.9) in the commit description.

**Review by ncfavier — APPROVED** [review]

**Comment by atemp** [comment]
> Thanks! Please link to the changelog (https://ddnet.org/downloads/#16.9) in the commit description.

is the top post in this conversation okay, or shall i redo the commit somehow?

**Comment by ncfavier** [comment]
You can edit the commit message with `git commit --amend` and then force-push your branch with `git push --force`.

**Comment by atemp** [comment]
> You can edit the commit message with `git commit --amend` and then force-push your branch with `git push --force`.

ah, okay, thought u mean a comment like that: https://github.com/atemp/nixpkgs/commit/a7ff41dedb92c16061f0bee624c1ee577606a7c0

anyway, i changed the commit message, hope its good now

**Pull request merged**
