### PR TITLE
python3Packages.fontparts: 0.9.7 -> 0.9.9

### PR DESCRIPTION
**Pull request by sternenseemann**
###### Motivation for this change

<https://github.com/robotools/fontParts/releases/tag/0.9.8>

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
Result of `nixpkgs-review pr 112992` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>14 packages built:</summary>
  <ul>
    <li>noto-fonts-emoji</li>
    <li>python37Packages.afdko</li>
    <li>python37Packages.fontparts</li>
    <li>python37Packages.nototools</li>
    <li>python37Packages.ufoprocessor</li>
    <li>python38Packages.afdko</li>
    <li>python38Packages.fontparts</li>
    <li>python38Packages.nototools</li>
    <li>python38Packages.ufoprocessor</li>
    <li>python39Packages.afdko</li>
    <li>python39Packages.fontparts</li>
    <li>python39Packages.nototools</li>
    <li>python39Packages.ufoprocessor</li>
    <li>twitter-color-emoji</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 112992` at f097a520 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/1c212ce19e033aff7601b20e84cd0a21">noto-fonts-emoji</a></li></li>
  </ul>
</details>
<details>
  <summary>13 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/5928835b43fe0c924b52d852bd8b7d70">python37Packages.afdko</a></li></li>
    <li><a href="https://gist.github.com/252081a0cfb93da035851072693cc1d4">python37Packages.fontparts</a></li></li>
    <li><a href="https://gist.github.com/c2d335b45b671a89ef894dc40380d004">python37Packages.nototools</a></li></li>
    <li><a href="https://gist.github.com/f671252076981911ab181dacc9070110">python37Packages.ufoprocessor</a></li></li>
    <li><a href="https://gist.github.com/472ce6dcb6a8a3c73be787b54d935f0b">python38Packages.afdko</a></li></li>
    <li><a href="https://gist.github.com/acd7597d85c2545b13604f0576261ba6">python38Packages.fontparts</a></li></li>
    <li><a href="https://gist.github.com/852e65a18b4aa00f46ff3e978c76d81b">python38Packages.nototools</a></li></li>
    <li><a href="https://gist.github.com/022b45ceebde64072ae846c7843cc041">python38Packages.ufoprocessor</a></li></li>
    <li><a href="https://gist.github.com/779efca70a1bc7b6769d578599c3b75b">python39Packages.afdko</a></li></li>
    <li><a href="https://gist.github.com/3cbd53bfddb77566f075e4983017e0d4">python39Packages.fontparts</a></li></li>
    <li><a href="https://gist.github.com/b36b18f2a854e2806207753a5db7536d">python39Packages.nototools</a></li></li>
    <li><a href="https://gist.github.com/80c1f9fdfe3ab9c679c9fa15d62f8ee0">python39Packages.ufoprocessor</a></li></li>
    <li><a href="https://gist.github.com/ebe81dee1367450e7bb0142092995fd3">twitter-color-emoji</a></li></li>
  </ul>
</details>

**Comment by sternenseemann** [comment]
> 1 package failed to build:

Looks like a timeout to me, ping @rmcgibbo

**Comment by rmcgibbo** [comment]
Ack. Working on that today.

**Pull request merged**
