### PR TITLE
nasm: run checkPhase

### PR DESCRIPTION
**Pull request by WilliButz**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by WilliButz** [comment]
@orivej excuse me changing it back to master, looked like something was wrong.
Why does this need to be merged into staging? :)

**Comment by orivej** [comment]
Because it rebuilds 4000 packages on Linux.

**Comment by orivej** [comment]
Could you rebase this on top of staging?

**Comment by WilliButz** [comment]
@orivej could you remove review requests? :)
(I guess they where made in the short time between me pushing the rebased branch with a lot of changes compared to master and me switching the target branch staging)

**Comment by orivej** [comment]
Merged into staging. Thank you!

**Pull request merged**
