### PR TITLE
crashplan: 4.8.2 -> 4.8.3

### PR DESCRIPTION
**Pull request by forficate**
Refs #26666

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @sztupi @domenkozar @jerith666

### CODE REVIEW

**Comment by jerith666** [comment]
This works fine for me.  (The Travis CI builds failed with what appears to be an unrelated error, `No module named 'dogpile.cache'`.)

**Comment by Mic92** [comment]
How do I test this. I get an error on startup:

```
$ CrashPlanDesktop
/nix/store/hisapihmnadyfap13n9pd6q74q6s4qv3-crashplan-4.8.3-r1/bin/.CrashPlanDesktop-wrapped: line 9: /var/lib/crashplan/bin/run.conf: No such file or directory
Error: Could not find or load main class com.backup42.desktop.CPDesktop
```

**Comment by jerith666** [comment]
`CrashPlanDesktop` is just a front-end for https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/backup/crashplan.nix, so you have to set `services.crashplan.enable = true` in `configuration.nix` before it'll do anything useful.  (The service creates and populates `/var/lib/crashplan`.)

**Comment by Mic92** [comment]
Ok. Got tested until I reached the sign-up page.

**Pull request merged**
