### PR TITLE
linux_6_7: fix Rust support with current rustc

### PR DESCRIPTION
**Pull request by alyssais**
## Description of changes

The 1.75 patch can't be fetched, because it doesn't apply.  But git can apply it cleanly, so it must just need to do a three-way merge or something.  Regardless, we need to include a version that patch(1) can apply in Nixpkgs.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Ma27 — COMMENTED** [review]
LGTM.

One thing though: the `kernel-rust` test fails to build. I'm wondering if we want to hardcode it to use linux_6_7 instead, also apply the rust 1.75 patch to linux_testing or both + make a test-matrix with 6.7 and testing similar to what we do in kernel-generic (cc maintainer @blitz)

**Comment by alyssais** [comment]
Ah yes this should also have been applied to linux_testing, and I forgot that.  I'll update the PR to do that.

**Comment by alyssais** [comment]
I've added the appropriate patch to linux_testing.  It won't build though, because it needs https://github.com/NixOS/nixpkgs/pull/284307, which has to go through staging.

**Review by RaitoBezarius — APPROVED** [review]
LGTM, feel free to proceed as you see fit based on staging cycles, etc.

**Comment by alyssais** [comment]
It's only linux_testing that needs the fix in staging.  No reason to hold back on fixing linux_6_7 for that.

**Pull request merged**
