### PR TITLE
oraclejdk8: 8u181 -> 8u191

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

old files are not available on the upstream website

### CODE REVIEW

**Comment by xeji** [comment]
build checked locally on x86_64-linux

**Comment by xeji** [comment]
@volth did you check the build on aarch64?

**Comment by volth** [comment]
yes

**Comment by xeji** [comment]
should this be backported to 18.09?

**Comment by xeji** [comment]
I don't know how this was done before. But if the upstream tarball for 8u181 is gone we'll have to backport the upgrade, or users won't be able to build it on 18.09 unless they still have it in their nix store.

**Comment by volth** [comment]
It is not completely gone, all old versions are available but one have to creare an account at oracle.com and log in to have access to the archive.
I just meant it is gone from the place where it could be athomatically downloaded (with ```'Cookie: oraclelicense=accept-securebackup-cookie'```) but anyway this mode is not supported in the mainline ```nixpkgs``` because of some license issues

**Comment by xeji** [comment]
I see. So it is still possible to get the tarball, but the instructions given by require-file are wrong and will confuse users:

```
Unfortunately, we cannot download file jdk-8u181-linux-x64.tar.gz automatically.
Please go to http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html to download it yourself, and add it to the Nix store
...
``

**Comment by xeji** [comment]
Backported  to 18.09 in 971b5bea49d

**Pull request merged**
