### PR TITLE
blesh: 2022-07-29 -> 0.3.4

### LINKED ISSUE #224537: Update request: blesh unstable-2022-07-29 → 0.3.4
- Package name: blesh
- Latest released version: unstable-2022-07-29

- Current version on the unstable channel: unstable-2022-07-29
- Current version on the stable/release channel: unstable-2022-07-29

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@marsam 

-----

Note for maintainers: Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by marsam**
###### Description of changes

https://github.com/akinomyoga/ble.sh/releases/tag/v0.3.4

Closes https://github.com/NixOS/nixpkgs/issues/224537  cc: @Aleksanaa

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by aiotter — APPROVED** [review]
LGTM

**Comment by marsam** [comment]
>Please check if typing [ -z aaa ] make "[ command not found" output suddenly.

I tested it on Darwin and seems to work, it doesn't throw the `[ command not found`

**Comment by Aleksanaa** [comment]
> I tested it on Darwin and seems to work, it doesn't throw the `[ command not found`

Then it should be okay. This happened on last version.

**Comment by aiotter** [comment]
@Aleksanaa I've already got a review request and added a review. Please specify the kind of review if you need more.

**Comment by akinomyoga** [comment]
Oh, so is the `blesh` package switched from 0.4 (devel) to 0.3 ("stable")?

If it works fine, I have nothing to say, but ble-0.3 doesn't explicitly support NixOS. ble-0.4 is still in the devel state, but it includes many fixes for the nix-shell envrionment including https://github.com/akinomyoga/ble.sh/issues/169, https://github.com/akinomyoga/ble.sh/issues/171, https://github.com/akinomyoga/ble.sh/issues/179, https://github.com/akinomyoga/ble.sh/issues/300 (https://github.com/akinomyoga/ble.sh/issues/235 was backported to ble-0.3). But, as far as one doesn't use it inside the nix-shell, maybe there is not so much difference.

**Pull request merged**
