### PR TITLE
f3d: 2.2.1 -> 2.3.0, unbreak

### LINKED ISSUE #262328: f3d unstabe broken
### Describe the bug
When i try to launch, i get this error:

`f3d: error while loading shared libraries: libvtkInteractionWidgets.so.1: cannot open shared object file: No such file or directory`

### Steps To Reproduce
1. install f3d unstable
2. try to launch the program

### Expected behavior
Program launches

### Additional context
I dont konw if this matters, but i use nixos 23.05 but have f3d installed from unstable pkgs via my configuration.nix

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.57, NixOS, 23.05 (Stoat), 23.05.4407.80c1aab72515`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(ford): `"nixos-23.05, nixos-unstable"`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.57, NixOS, 23.05 (Stoat), 23.05.4407.80c1aab72515`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(ford): `"nixos-23.05, nixos-unstable"`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

### PR DESCRIPTION
**Pull request by pbsds**
## Description of changes

Diff: https://github.com/f3d-app/f3d/compare/refs/tags/v2.2.1...v2.3.0

Changelog: https://github.com/f3d-app/f3d/releases/tag/v2.3.0

unbreak by ~~partially reverting https://github.com/f3d-app/f3d/commit/a8fdf79e6e7b4006e71ae8a5db0592796a0a1477, tracked in https://github.com/f3d-app/f3d/pull/1217.~~ using `autoPatchelfHook`.

fixes https://github.com/NixOS/nixpkgs/issues/262328

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by pbsds** [comment]
@defini-tiv @bcdarwin please test

```
nix run github:NixOS/nixpkgs/refs/pull/283052/merge#f3d
```

**Comment by pbsds** [comment]
Result of `nixpkgs-review pr 283052` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>f3d</li>
    <li>f3d.man</li>
  </ul>
</details>

**Comment by pca006132** [comment]
Using `autoPatchelfHook` can also fix the rpath issue.

**Comment by bcdarwin** [comment]
@pbsds - do you think we should switch this PR to use `autopatchelfhook` as suggested by @pca006132? It seems like the patch will not be merged since upstream may do some slightly better refactoring to avoid breaking the Python API which we might also want to add in future.

**Review by bcdarwin — CHANGES_REQUESTED** [review]
Diff looks good - would you squash the `fetchpatch` and `autopatchelf` commit into one?

**Review by bcdarwin — APPROVED** [review]
LGTM, thanks.

**Comment by pca006132** [comment]
can we backport to 23.11?

**Pull request merged**
