### PR TITLE
ardour: 6.5 -> 6.6

### PR DESCRIPTION
**Pull request by hjones2199**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]
diff LGTM

**Review by magnetophon — COMMENTED** [review]
Ardour 6.6 is notorious for it's bad stability and many bugs.
I strongly suggest we wait for 6.7, which is right around the corner.

**Comment by Mathnerd314** [comment]
Regarding [ZHF](https://github.com/NixOS/nixpkgs/issues/122042), the [build failure](https://hydra.nixos.org/build/141571958/nixlog/4) with Glib 2.68 is not fixed in 6.6 AFAICT. https://github.com/Ardour/ardour/commit/cc7b8b1bc5fb19e0ec5e476741c55627d4b62ba9 is from March, while 6.6 was released in February.

https://discourse.ardour.org/t/last-call-for-ardour-6-7/105763/4 dated April 10 says 6.7 will be released "in 2-6 weeks", which works out to ending at the branch date.

If it's not released by then we'll have to backport the patch or use glib 2.66 or something.

**Comment by nixinator** [comment]
gentoo patch it at https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=4e848e1a42b49ba606f7e7bcf45ab97d09f1e57c

maybe 6.7 will be release before the end of ZFH, if not i'll patch it 6.6 for glibc2.68

writing this here to keep track of it.

**Comment by dotlambda** [comment]
Please also make sure to address https://github.com/NixOS/nixpkgs/issues/120705.

**Comment by SuperSandro2000** [comment]
> Should we just plan to backport 6.7 if it happens after NixOS 21.05 releases? Not 100% sure what the NixOS policy is about backporting releases because of non-security related bugs/breakage etc

The update is justified so just backport it.

**Comment by magnetophon** [comment]
Superseded by the above PR.

**Pull request closed without merging**
