### PR TITLE
HaskellPackages.PortMidi: fix ALSA plugins load path

### LINKED ISSUE #273407: ensuring correct environment variables for Haskell packages
### Describe the bug

Shell environment settings required for correct operation of Haskell packages don't seem to be ensured. This report discusses the impact on ALSA sound access. It may be platform dependent to some extent.

### Steps To Reproduce
1. Run `ghci` inside `pkgs.haskellPackages.ghcWithPackages { hpkgs: with hpkgs; [ Euterpea ])`
2. Try to play a sound through MIDI (MIDI must be set up):
```
import Euterpea
playDev 2 $ c 4 qn
```
3. MIDI access fails:
```
ALSA lib conf.c:4005:(snd_config_hooks_call) Cannot open shared library libasound_module_conf_pulse.so (/nix/store/isx80s2ph5i03in98r1hyy2zsyw6yin9-alsa-lib-1.2.9/lib/alsa-lib/libasound_module_conf_pulse.so: cannot open shared object file: No such file or directory)
ALSA lib seq.c:935:(snd_seq_open_noupdate) Unknown SEQ default
Unable to open output device in midiOutRealTime': PortMidi: `Invalid device ID'
Unable to open output device in midiOutRealTime': PortMidi: `Invalid device ID'
Unable to open output device in midiOutRealTime': PortMidi: `Invalid device ID'
Unable to open output device in midiOutRealTime': PortMidi: `Invalid device ID'
Unable to open output device in midiOutRealTime': PortMidi: `Invalid device ID'
```

### Expected behavior
No error message. Instead, you hear a sound.

### Additional context
It works when setting `ALSA_PLUGIN_DIR` `${alsa-plugins}/lib/alsa-lib`

For `$out/bin` executables, this would be solved by setting the environment using `wrapProgram` (e.g. https://github.com/NixOS/nixpkgs/pull/273326, https://github.com/NixOS/nixpkgs/pull/273181 or https://github.com/NixOS/nixpkgs/pull/267069). AFAIK, there is nothing similar for shared objects, and `ghci` would have to be wrapped instead.

Would there be any mechanism that allows collecting the required environment variables and wrap them from `ghcWithPackages`?

### Notify maintainers

Pinging the Haskell team since I don't see specific maintainers in the relevant packages:
@cdepillabout @expipiplus1 @maralorn @ncfavier @sternenseemann

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-88-generic, Ubuntu, 22.04.3 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.6.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/root/.nix-defexpr/channels/nixpkgs`
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by zeuner**
## Description of changes

Implements a mechanism that allows Haskell packages to define the process environment variables they require, having the existing wrapper mechanism from `ghcWithPackages` add it to processes like `ghci`. This is done also for transitive dependencies of the `ghc` environment.

This mechanism is used to fix ALSA plugin loading in `PortMidi`.

Fixes https://github.com/NixOS/nixpkgs/issues/273407

This is the first readily usable implementation. I'm happy about comments/criticism/suggestions. I also consider to switch from a list to an attrset for collecting the process environment variables, as this might avoid duplications when transitive dependencies get pulled into the environment multiple times.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by sternenseemann** [comment]
This mechanism is kind of unusual and not too useful, since it only works for `ghcWithPackages`.

My suggestion would be to patch `PortMidi`, so that it falls back to a hardcoded `alsa-plugins`-based path if `ALSA_PLUGINS_PATH`. This has the additional benefit that the user can still override the variable to whatever they like.

**Comment by zeuner** [comment]
Thanks for the feedback. It may be a bit more complex, though:

> This mechanism is kind of unusual and not too useful, since it only works for `ghcWithPackages`.
>

I thought `ghcWithPackages` would be the standard way to consume Haskell packages in a reproducible way, so I solved the issue for it. What other ways of consuming Haskall packages from `nixpkgs` did you have in mind? They can probably also be supported because you can get the environment variables for a given Haskell package by looking at its `passthru.processEnv`.

> My suggestion would be to patch `PortMidi`, so that it falls back to a hardcoded `alsa-plugins`-based path if `ALSA_PLUGINS_PATH`.

`PortMidi` does not control the ALSA plugin load paths as this is done by `alsa-lib`. And `alsa-lib` can't be just patched to point to `alsa-plugins` since it's a dependency of `alsa-plugins`.

Please see https://github.com/NixOS/nixpkgs/issues/6860 for more information on this (known for a long time but still not really fixed) ALSA issue. As can be seen there, the options people currently use rely on either setting shell environment variables (as I did), or adapting the ALSA configuration accordingly.

> This has the additional benefit that the user can still override the variable to whatever they like.

You're right. This should have been overridable as it is in other packages fixed for ALSA. Changed that.

**Comment by maralorn** [comment]
I feel like doing something like this has to be a solved problem in nixpkgs and we shouldn’t introduce yet another approach in mkDerivation. Normally environment variables are set by wrappers around binaries if they are required.

I think we really want a solution that works when someone installs a binary via environment.systemPackages = [ pkgs.haskellPackages.foo ]; because our infrastructure is first and foremost for providing working haskell binaries to nixos users.

Maybe we can patch PortMidi to simply inspect its environment and set it correctly if the variable is not set?

**Comment by zeuner** [comment]
> I feel like doing something like this has to be a solved problem in nixpkgs and we shouldn’t introduce yet another approach in mkDerivation. Normally environment variables are set by wrappers around binaries if they are required.
> 
> I think we really want a solution that works when someone installs a binary via environment.systemPackages = [ pkgs.haskellPackages.foo ]; because our infrastructure is first and foremost for providing working haskell binaries to nixos users.
>

I didn't see the source code for `environment.systemPackages`, but I guess there should be a way to also inspect `pkgs.haskellPackages.foo.passthru` in order to find necessary environment variables.

> Maybe we can patch PortMidi to simply inspect its environment and set it correctly if the variable is not set?

It seems kind of hacky to me to have the running process modify its environment in order to affect a library's behaviour, but is probably worth trying.

**Comment by FliegendeWurst** [comment]
Done in #273955

**Pull request closed without merging**
