### PR TITLE
dt-schema: init at v2019.11

### PR DESCRIPTION
**Pull request by sorki**
###### Motivation for this change

DeviceTree schema validation. Upstream issue https://github.com/devicetree-org/dt-schema/issues/35

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by prusnak** [comment]
Please put URL in the `homepage` field into quotes (RFC45).

**Comment by sorki** [comment]
Oh, for some reason I've thought it's the other way despite taking the template from docs and removed them, thanks :)

**Comment by Thra11** [comment]
Looks like the upstream issue is resolved, and dt-schema is now on PyPI: https://pypi.org/project/dtschema/. That should allow you to simplify this a bit.

**Comment by sorki** [comment]
Thanks for the poke, updated.

**Pull request merged**
