### PR TITLE
jenkins-job-builder: fix build

### LINKED ISSUE #362054: Build failure: python312Packages.jenkins-job-builder
## Steps To Reproduce

1. build `python312Packages.jenkins-job-builder`

## Build log

<details>

<summary>Build Log</summary>

```
error:
       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:34:12:
           33|
           34|   strict = derivationStrict drvAttrs;
             |            ^
           35|

       … while evaluating derivation 'shell'
         whose name attribute is located at /nix/store/sh0v21n9zc03b94qjj4jkkg5mbsjkpzr-source/pkgs/stdenv/generic/make-derivation.nix:336:7

       … while evaluating attribute 'buildInputs' of derivation 'shell'
         at /nix/store/sh0v21n9zc03b94qjj4jkkg5mbsjkpzr-source/pkgs/stdenv/generic/make-derivation.nix:383:7:
          382|       depsHostHost                = elemAt (elemAt dependencies 1) 0;
          383|       buildInputs                 = elemAt (elemAt dependencies 1) 1;
             |       ^
          384|       depsTargetTarget            = elemAt (elemAt dependencies 2) 0;

       … while evaluating the attribute 'out.outPath'
         at /nix/store/sh0v21n9zc03b94qjj4jkkg5mbsjkpzr-source/lib/customisation.nix:352:13:
          351|             drvPath = assert condition; drv.${outputName}.drvPath;
          352|             outPath = assert condition; drv.${outputName}.outPath;
             |             ^
          353|           } //

       … while evaluating the attribute 'out.outPath'
         at /nix/store/sh0v21n9zc03b94qjj4jkkg5mbsjkpzr-source/lib/customisation.nix:352:13:
          351|             drvPath = assert condition; drv.${outputName}.drvPath;
          352|             outPath = assert condition; drv.${outputName}.outPath;
             |             ^
          353|           } //

       … while calling the 'getAttr' builtin
         at <nix/derivation-internal.nix>:44:19:
           43|       value = commonAttrs // {
           44|         outPath = builtins.getAttr outputName strict;
             |                   ^
           45|         drvPath = strict.drvPath;

       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:34:12:
           33|
           34|   strict = derivationStrict drvAttrs;
             |            ^
           35|

       … while evaluating derivation 'python3.12-jenkins-job-builder-6.4.1'
         whose name attribute is located at /nix/store/sh0v21n9zc03b94qjj4jkkg5mbsjkpzr-source/pkgs/stdenv/generic/make-derivation.nix:336:7

       … while evaluating attribute 'propagatedBuildInputs' of derivation 'python3.12-jenkins-job-builder-6.4.1'
         at /nix/store/sh0v21n9zc03b94qjj4jkkg5mbsjkpzr-source/pkgs/stdenv/generic/make-derivation.nix:390:7:
          389|       depsHostHostPropagated      = elemAt (elemAt propagatedDependencies 1) 0;
          390|       propagatedBuildInputs       = elemAt (elemAt propagatedDependencies 1) 1;
             |       ^
          391|       depsTargetTargetPropagated  = elemAt (elemAt propagatedDependencies 2) 0;

       … while evaluating the attribute 'out.outPath'
         at /nix/store/sh0v21n9zc03b94qjj4jkkg5mbsjkpzr-source/lib/customisation.nix:352:13:
          351|             drvPath = assert condition; drv.${outputName}.drvPath;
          352|             outPath = assert condition; drv.${outputName}.outPath;
             |             ^
          353|           } //

       … while calling the 'getAttr' builtin
         at <nix/derivation-internal.nix>:44:19:
           43|       value = commonAttrs // {
           44|         outPath = builtins.getAttr outputName strict;
             |                   ^
           45|         drvPath = strict.drvPath;

       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:34:12:
           33|
           34|   strict = derivationStrict drvAttrs;
             |            ^
           35|

       … while evaluating derivation 'python3.12-python-jenkins-1.8.2'
         whose name attribute is located at /nix/store/sh0v21n9zc03b94qjj4jkkg5mbsjkpzr-source/pkgs/stdenv/generic/make-derivation.nix:336:7

       … while evaluating attribute 'nativeBuildInputs' of derivation 'python3.12-python-jenkins-1.8.2'
         at /nix/store/sh0v21n9zc03b94qjj4jkkg5mbsjkpzr-source/pkgs/stdenv/generic/make-derivation.nix:380:7:
          379|       depsBuildBuild              = elemAt (elemAt dependencies 0) 0;
          380|       nativeBuildInputs           = elemAt (elemAt dependencies 0) 1;
             |       ^
          381|       depsBuildTarget             = elemAt (elemAt dependencies 0) 2;

       … while evaluating the attribute 'out.outPath'
         at /nix/store/sh0v21n9zc03b94qjj4jkkg5mbsjkpzr-source/lib/customisation.nix:352:13:
          351|             drvPath = assert condition; drv.${outputName}.drvPath;
          352|             outPath = assert condition; drv.${outputName}.outPath;
             |             ^
          353|           } //

       … while calling the 'getAttr' builtin
         at <nix/derivation-internal.nix>:44:19:
           43|       value = commonAttrs // {
           44|         outPath = builtins.getAttr outputName strict;
             |                   ^
           45|         drvPath = strict.drvPath;

       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:34:12:
           33|
           34|   strict = derivationStrict drvAttrs;
             |            ^
           35|

       … while evaluating derivation 'python3.12-stestr-4.1.0'
         whose name attribute is located at /nix/store/sh0v21n9zc03b94qjj4jkkg5mbsjkpzr-source/pkgs/stdenv/generic/make-derivation.nix:336:7

       … while evaluating attribute 'propagatedBuildInputs' of derivation 'python3.12-stestr-4.1.0'
         at /nix/store/sh0v21n9zc03b94qjj4jkkg5mbsjkpzr-source/pkgs/stdenv/generic/make-derivation.nix:390:7:
          389|       depsHostHostPropagated      = elemAt (elemAt propagatedDependencies 1) 0;
          390|       propagatedBuildInputs       = elemAt (elemAt propagatedDependencies 1) 1;
             |       ^
          391|       depsTargetTargetPropagated  = elemAt (elemAt propagatedDependencies 2) 0;

       … while evaluating the attribute 'out.outPath'
         at /nix/store/sh0v21n9zc03b94qjj4jkkg5mbsjkpzr-source/lib/customisation.nix:352:13:
          351|             drvPath = assert condition; drv.${outputName}.drvPath;
          352|             outPath = assert condition; drv.${outputName}.outPath;
             |             ^
          353|           } //

       … while calling the 'getAttr' builtin
         at <nix/derivation-internal.nix>:44:19:
           43|       value = commonAttrs // {
           44|         outPath = builtins.getAttr outputName strict;
             |                   ^
           45|         drvPath = strict.drvPath;

       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:34:12:
           33|
           34|   strict = derivationStrict drvAttrs;
             |            ^
           35|

       … while evaluating derivation 'python3.12-cliff-4.7.0'
         whose name attribute is located at /nix/store/sh0v21n9zc03b94qjj4jkkg5mbsjkpzr-source/pkgs/stdenv/generic/make-derivation.nix:336:7

       … while evaluating attribute 'nativeBuildInputs' of derivation 'python3.12-cliff-4.7.0'
         at /nix/store/sh0v21n9zc03b94qjj4jkkg5mbsjkpzr-source/pkgs/stdenv/generic/make-derivation.nix:380:7:
          379|       depsBuildBuild              = elemAt (elemAt dependencies 0) 0;
          380|       nativeBuildInputs           = elemAt (elemAt dependencies 0) 1;
             |       ^
          381|       depsBuildTarget             = elemAt (elemAt dependencies 0) 2;

       … in the condition of the assert statement
         at /nix/store/sh0v21n9zc03b94qjj4jkkg5mbsjkpzr-source/lib/customisation.nix:352:23:
          351|             drvPath = assert condition; drv.${outputName}.drvPath;
          352|             outPath = assert condition; drv.${outputName}.outPath;
             |                       ^
          353|           } //

       … in the right operand of the IMPL (->) operator
         at /nix/store/sh0v21n9zc03b94qjj4jkkg5mbsjkpzr-source/pkgs/development/interpreters/python/mk-python-derivation.nix:350:13:
          349| in extendDerivation
          350|   (disabled -> throw "${name} not supported for interpreter ${python.executable}")
             |             ^
          351|   { }

       … while calling the 'throw' builtin
         at /nix/store/sh0v21n9zc03b94qjj4jkkg5mbsjkpzr-source/pkgs/development/interpreters/python/mk-python-derivation.nix:350:16:
          349| in extendDerivation
          350|   (disabled -> throw "${name} not supported for interpreter ${python.executable}")
             |                ^
          351|   { }

       error: openstackdocstheme-3.4.0 not supported for interpreter python3.12
```

</details>

## Additional context

Breaks options `services.jenkins.jobBuilder.*`

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.14, NixOS, 25.05 (Warbler), 25.05.20241203.55d15ad`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.25.2`
 - nixpkgs: `/nix/store/sh0v21n9zc03b94qjj4jkkg5mbsjkpzr-source`

## Notify maintainers

@bot-wxt1221

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by bjornfor**
## Things done

Fix building/running jenkins-job-builder and make nixosTests.jenkins pass.

Commits:
- **python3Packages.openstackdocstheme: add missing 'distutils' dependency**
- **nixos/tests/jenkins: increase disk size to 2 GiB**
- **python3Packages.jenkins-job-builder: add missing runtime dependency 'packaging'**
- **python3Packages.jenkins-job-builder: add passthru.tests**

Fixes https://github.com/NixOS/nixpkgs/issues/362054.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by bjornfor** [comment]
Result of `nixpkgs-review pr 363535` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.subunit2sql</li>
    <li>python311Packages.subunit2sql.dist</li>
    <li>python312Packages.subunit2sql</li>
    <li>python312Packages.subunit2sql.dist</li>
  </ul>
</details>
<details>
  <summary>14 packages failed to build:</summary>
  <ul>
    <li>python312Packages.python-cinderclient</li>
    <li>python312Packages.python-cinderclient.dist</li>
    <li>python312Packages.python-magnumclient</li>
    <li>python312Packages.python-magnumclient.dist</li>
    <li>python312Packages.python-neutronclient</li>
    <li>python312Packages.python-neutronclient.dist</li>
    <li>python312Packages.python-octaviaclient</li>
    <li>python312Packages.python-octaviaclient.dist</li>
    <li>python312Packages.python-openstackclient</li>
    <li>python312Packages.python-openstackclient.dist</li>
    <li>python312Packages.python-troveclient</li>
    <li>python312Packages.python-troveclient.dist</li>
    <li>python312Packages.swift</li>
    <li>python312Packages.swift.dist</li>
  </ul>
</details>
<details>
  <summary>170 packages built:</summary>
  <ul>
    <li>barbicanclient (python311Packages.python-barbicanclient)</li>
    <li>barbicanclient.dist (python311Packages.python-barbicanclient.dist)</li>
    <li>bashate</li>
    <li>bashate.dist</li>
    <li>glanceclient (python311Packages.python-glanceclient)</li>
    <li>glanceclient.dist (python311Packages.python-glanceclient.dist)</li>
    <li>heatclient (python311Packages.python-heatclient)</li>
    <li>heatclient.dist (python311Packages.python-heatclient.dist)</li>
    <li>html5validator</li>
    <li>html5validator.dist</li>
    <li>ironicclient (python311Packages.python-ironicclient)</li>
    <li>ironicclient.dist (python311Packages.python-ironicclient.dist)</li>
    <li>jenkins-job-builder (python312Packages.jenkins-job-builder)</li>
    <li>jenkins-job-builder.dist (python312Packages.jenkins-job-builder.dist)</li>
    <li>kolla</li>
    <li>kolla.dist</li>
    <li>magnumclient (python311Packages.python-magnumclient)</li>
    <li>magnumclient.dist (python311Packages.python-magnumclient.dist)</li>
    <li>manilaclient (python311Packages.python-manilaclient)</li>
    <li>manilaclient.dist (python311Packages.python-manilaclient.dist)</li>
    <li>mistralclient (python311Packages.python-mistralclient)</li>
    <li>mistralclient.dist (python311Packages.python-mistralclient.dist)</li>
    <li>openstackclient (python311Packages.python-openstackclient)</li>
    <li>openstackclient-full</li>
    <li>openstackclient-full.dist</li>
    <li>openstackclient.dist (python311Packages.python-openstackclient.dist)</li>
    <li>python311Packages.cliff</li>
    <li>python311Packages.cliff.dist</li>
    <li>python311Packages.debtcollector</li>
    <li>python311Packages.debtcollector.dist</li>
    <li>python311Packages.hacking</li>
    <li>python311Packages.hacking.dist</li>
    <li>python311Packages.jenkins-job-builder</li>
    <li>python311Packages.jenkins-job-builder.dist</li>
    <li>python311Packages.keystoneauth1</li>
    <li>python311Packages.keystoneauth1.dist</li>
    <li>python311Packages.openstackdocstheme</li>
    <li>python311Packages.openstackdocstheme.dist</li>
    <li>python311Packages.openstacksdk</li>
    <li>python311Packages.openstacksdk.dist</li>
    <li>python311Packages.openstacksdk.man</li>
    <li>python311Packages.os-client-config</li>
    <li>python311Packages.os-client-config.dist</li>
    <li>python311Packages.osc-lib</li>
    <li>python311Packages.osc-lib.dist</li>
    <li>python311Packages.osc-placement</li>
    <li>python311Packages.osc-placement.dist</li>
    <li>python311Packages.oslo-concurrency</li>
    <li>python311Packages.oslo-concurrency.dist</li>
    <li>python311Packages.oslo-config</li>
    <li>python311Packages.oslo-config.dist</li>
    <li>python311Packages.oslo-context</li>
    <li>python311Packages.oslo-context.dist</li>
    <li>python311Packages.oslo-db</li>
    <li>python311Packages.oslo-db.dist</li>
    <li>python311Packages.oslo-i18n</li>
    <li>python311Packages.oslo-i18n.dist</li>
    <li>python311Packages.oslo-log</li>
    <li>python311Packages.oslo-log.dist</li>
    <li>python311Packages.oslo-serialization</li>
    <li>python311Packages.oslo-serialization.dist</li>
    <li>python311Packages.oslo-utils</li>
    <li>python311Packages.oslo-utils.dist</li>
    <li>python311Packages.osprofiler</li>
    <li>python311Packages.osprofiler.dist</li>
    <li>python311Packages.python-aodhclient</li>
    <li>python311Packages.python-aodhclient.dist</li>
    <li>python311Packages.python-cinderclient</li>
    <li>python311Packages.python-cinderclient.dist</li>
    <li>python311Packages.python-designateclient</li>
    <li>python311Packages.python-designateclient.dist</li>
    <li>python311Packages.python-jenkins</li>
    <li>python311Packages.python-jenkins.dist</li>
    <li>python311Packages.python-keystoneclient</li>
    <li>python311Packages.python-keystoneclient.dist</li>
    <li>python311Packages.python-neutronclient</li>
    <li>python311Packages.python-neutronclient.dist</li>
    <li>python311Packages.python-novaclient</li>
    <li>python311Packages.python-novaclient.dist</li>
    <li>python311Packages.python-octaviaclient</li>
    <li>python311Packages.python-octaviaclient.dist</li>
    <li>swiftclient (python311Packages.python-swiftclient)</li>
    <li>swiftclient.dist (python311Packages.python-swiftclient.dist)</li>
    <li>troveclient (python311Packages.python-troveclient)</li>
    <li>troveclient.dist (python311Packages.python-troveclient.dist)</li>
    <li>watcherclient (python311Packages.python-watcherclient)</li>
    <li>watcherclient.dist (python311Packages.python-watcherclient.dist)</li>
    <li>python311Packages.python-zaqarclient</li>
    <li>python311Packages.python-zaqarclient.dist</li>
    <li>zunclient (python311Packages.python-zunclient)</li>
    <li>zunclient.dist (python311Packages.python-zunclient.dist)</li>
    <li>python311Packages.stestr</li>
    <li>python311Packages.stestr.dist</li>
    <li>python311Packages.swift</li>
    <li>python311Packages.swift.dist</li>
    <li>python311Packages.tempest</li>
    <li>python311Packages.tempest.dist</li>
    <li>python312Packages.cliff</li>
    <li>python312Packages.cliff.dist</li>
    <li>python312Packages.debtcollector</li>
    <li>python312Packages.debtcollector.dist</li>
    <li>python312Packages.hacking</li>
    <li>python312Packages.hacking.dist</li>
    <li>python312Packages.keystoneauth1</li>
    <li>python312Packages.keystoneauth1.dist</li>
    <li>python312Packages.openstackdocstheme</li>
    <li>python312Packages.openstackdocstheme.dist</li>
    <li>python312Packages.openstacksdk</li>
    <li>python312Packages.openstacksdk.dist</li>
    <li>python312Packages.openstacksdk.man</li>
    <li>python312Packages.os-client-config</li>
    <li>python312Packages.os-client-config.dist</li>
    <li>python312Packages.osc-lib</li>
    <li>python312Packages.osc-lib.dist</li>
    <li>python312Packages.osc-placement</li>
    <li>python312Packages.osc-placement.dist</li>
    <li>python312Packages.oslo-concurrency</li>
    <li>python312Packages.oslo-concurrency.dist</li>
    <li>python312Packages.oslo-config</li>
    <li>python312Packages.oslo-config.dist</li>
    <li>python312Packages.oslo-context</li>
    <li>python312Packages.oslo-context.dist</li>
    <li>python312Packages.oslo-db</li>
    <li>python312Packages.oslo-db.dist</li>
    <li>python312Packages.oslo-i18n</li>
    <li>python312Packages.oslo-i18n.dist</li>
    <li>python312Packages.oslo-log</li>
    <li>python312Packages.oslo-log.dist</li>
    <li>python312Packages.oslo-serialization</li>
    <li>python312Packages.oslo-serialization.dist</li>
    <li>python312Packages.oslo-utils</li>
    <li>python312Packages.oslo-utils.dist</li>
    <li>python312Packages.osprofiler</li>
    <li>python312Packages.osprofiler.dist</li>
    <li>python312Packages.python-aodhclient</li>
    <li>python312Packages.python-aodhclient.dist</li>
    <li>python312Packages.python-barbicanclient</li>
    <li>python312Packages.python-barbicanclient.dist</li>
    <li>python312Packages.python-designateclient</li>
    <li>python312Packages.python-designateclient.dist</li>
    <li>python312Packages.python-glanceclient</li>
    <li>python312Packages.python-glanceclient.dist</li>
    <li>python312Packages.python-heatclient</li>
    <li>python312Packages.python-heatclient.dist</li>
    <li>python312Packages.python-ironicclient</li>
    <li>python312Packages.python-ironicclient.dist</li>
    <li>python312Packages.python-jenkins</li>
    <li>python312Packages.python-jenkins.dist</li>
    <li>python312Packages.python-keystoneclient</li>
    <li>python312Packages.python-keystoneclient.dist</li>
    <li>python312Packages.python-manilaclient</li>
    <li>python312Packages.python-manilaclient.dist</li>
    <li>python312Packages.python-mistralclient</li>
    <li>python312Packages.python-mistralclient.dist</li>
    <li>python312Packages.python-novaclient</li>
    <li>python312Packages.python-novaclient.dist</li>
    <li>python312Packages.python-swiftclient</li>
    <li>python312Packages.python-swiftclient.dist</li>
    <li>python312Packages.python-watcherclient</li>
    <li>python312Packages.python-watcherclient.dist</li>
    <li>python312Packages.python-zaqarclient</li>
    <li>python312Packages.python-zaqarclient.dist</li>
    <li>python312Packages.python-zunclient</li>
    <li>python312Packages.python-zunclient.dist</li>
    <li>python312Packages.stestr</li>
    <li>python312Packages.stestr.dist</li>
    <li>python312Packages.tempest</li>
    <li>python312Packages.tempest.dist</li>
    <li>reno</li>
    <li>reno.dist</li>
  </ul>
</details>

**Comment by bjornfor** [comment]
> 14 packages failed to build:

No regressions; they fail also on the base branch.

**Comment by bjornfor** [comment]
> PR title doesn't fit CONTRIBUTION.md

Correct. I wasn't sure what to put there, because the individual commits touch various parts of the tree. So whatever pattern I chose for the PR title I felt it was "wrong". But OK, I can update it to match the guidelines.

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]

**Comment by bjornfor** [comment]
Due to the merge of https://github.com/NixOS/nixpkgs/pull/362467 I reworked this patch set onto staging in these two PRs: https://github.com/NixOS/nixpkgs/pull/364883 https://github.com/NixOS/nixpkgs/pull/364884

**Pull request closed without merging**
