### PR TITLE
patroni: 1.6.5 -> 2.0.1

### LINKED ISSUE #107425: patroni tests fail and hang up on master
**Describe the bug**

patroni tests on master currently fail and hang up forever. 

**To Reproduce**
```
nix-build -A patroni /path/to/nixpkgs/clone
[…]
============================= test session starts ==============================
platform linux -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /build/source
plugins: cov-2.10.1
collected 377 items                                                            

tests/test_api.py ....................                                   [  5%]
tests/test_async_executor.py ....                                        [  6%]
tests/test_aws.py ....                                                   [  7%]
tests/test_bootstrap.py .........                                        [  9%]
tests/test_callback_executor.py .                                        [ 10%]
tests/test_cancellable.py ...                                            [ 10%]
tests/test_config.py ....                                                [ 11%]
tests/test_consul.py ......................                              [ 17%]
tests/test_ctl.py ...................................                    [ 27%]
tests/test_etcd.py ..........................                            [ 33%]
tests/test_exhibitor.py ...                                              [ 34%]
tests/test_ha.py ....................................................... [ 49%]
............................                                             [ 56%]
tests/test_kubernetes.py ...................                             [ 61%]
tests/test_log.py F                                                      [ 62%]
tests/test_patroni.py ...............                                    [ 66%]
tests/test_postgresql.py ............................................... [ 78%]
...                                                                      [ 79%]
tests/test_postmaster.py .........                                       [ 81%]
tests/test_rewind.py .......                                             [ 83%]
tests/test_utils.py ..........                                           [ 86%]
tests/test_validator.py ........                                         [ 88%]
tests/test_wale_restore.py ......                                        [ 89%]
tests/test_watchdog.py ................                                  [ 94%]
tests/test_zookeeper.py ......................                           [100%]

=================================== FAILURES ===================================
____________________ TestPatroniLogger.test_patroni_logger _____________________

self = <tests.test_log.TestPatroniLogger testMethod=test_patroni_logger>

    @patch('logging.FileHandler._open', Mock())
    def test_patroni_logger(self):
        config = {
            'log': {
                'traceback_level': 'DEBUG',
                'max_queue_size': 5,
                'dir': 'foo',
                'file_size': 4096,
                'file_num': 5,
                'loggers': {
                    'foo.bar': 'INFO'
                }
            },
            'restapi': {}, 'postgresql': {'data_dir': 'foo'}
        }
        sys.argv = ['patroni.py']
        os.environ[Config.PATRONI_CONFIG_VARIABLE] = yaml.dump(config, default_flow_style=False)
        logger = PatroniLogger()
        patroni_config = Config(None)
        logger.reload_config(patroni_config['log'])
        _LOG.exception('test')
        logger.start()

        with patch.object(logging.Handler, 'format', Mock(side_effect=Exception)):
>           logging.error('test')

tests/test_log.py:47:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/nix/store/jdp800qwb3v330ggl6iq722ww96q2444-python3-3.8.6/lib/python3.8/logging/__init__.py:2037: in error
    root.error(msg, *args, **kwargs)
/nix/store/jdp800qwb3v330ggl6iq722ww96q2444-python3-3.8.6/lib/python3.8/logging/__init__.py:1463: in error
    self._log(ERROR, msg, args, **kwargs)
/nix/store/jdp800qwb3v330ggl6iq722ww96q2444-python3-3.8.6/lib/python3.8/logging/__init__.py:1577: in _log
    self.handle(record)
/nix/store/jdp800qwb3v330ggl6iq722ww96q2444-python3-3.8.6/lib/python3.8/logging/__init__.py:1587: in handle
    self.callHandlers(record)
/nix/store/jdp800qwb3v330ggl6iq722ww96q2444-python3-3.8.6/lib/python3.8/logging/__init__.py:1649: in callHandlers
    hdlr.handle(record)
/nix/store/jdp800qwb3v330ggl6iq722ww96q2444-python3-3.8.6/lib/python3.8/logging/__init__.py:950: in handle
    self.emit(record)
/nix/store/b7m9y5mxvi54bxhl8j75rxhmfrnj2m07-python3.8-pytest-6.1.2/lib/python3.8/site-packages/_pytest/logging.py:328: in emit
    super().emit(record)
/nix/store/jdp800qwb3v330ggl6iq722ww96q2444-python3-3.8.6/lib/python3.8/logging/__init__.py:1089: in emit
    self.handleError(record)
/nix/store/jdp800qwb3v330ggl6iq722ww96q2444-python3-3.8.6/lib/python3.8/logging/__init__.py:1081: in emit
    msg = self.format(record)
/nix/store/pzidjzswskij3cb0a6p70mryl5qrx9ss-python3.8-mock-4.0.2/lib/python3.8/site-packages/mock/mock.py:1100: in __call__
    return _mock_self._mock_call(*args, **kwargs)
/nix/store/pzidjzswskij3cb0a6p70mryl5qrx9ss-python3.8-mock-4.0.2/lib/python3.8/site-packages/mock/mock.py:1104: in _mock_call
    return _mock_self._execute_mock_call(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

_mock_self = <Mock id='140737266183136'>
args = (<LogRecord: root, 40, /build/source/tests/test_log.py, 47, "test">,)
kwargs = {}, self = <Mock id='140737266183136'>, effect = <class 'Exception'>

    def _execute_mock_call(_mock_self, *args, **kwargs):
        self = _mock_self
        # separate from _increment_mock_call so that awaited functions are
        # executed separately from their call, also AsyncMock overrides this method

        effect = self.side_effect
        if effect is not None:
            if _is_exception(effect):
>               raise effect
E               Exception

/nix/store/pzidjzswskij3cb0a6p70mryl5qrx9ss-python3.8-mock-4.0.2/lib/python3.8/site-packages/mock/mock.py:1161: Exception
----------------------------- Captured stderr call -----------------------------
--- Logging error ---
Traceback (most recent call last):
  File "/nix/store/jdp800qwb3v330ggl6iq722ww96q2444-python3-3.8.6/lib/python3.8/logging/handlers.py", line 69, in emit
    if self.shouldRollover(record):
  File "/nix/store/jdp800qwb3v330ggl6iq722ww96q2444-python3-3.8.6/lib/python3.8/logging/handlers.py", line 187, in shouldRollover
    if self.stream.tell() + len(msg) >= self.maxBytes:
TypeError: unsupported operand type(s) for +: 'Mock' and 'int'
Call stack:
  File "/nix/store/jdp800qwb3v330ggl6iq722ww96q2444-python3-3.8.6/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/nix/store/jdp800qwb3v330ggl6iq722ww96q2444-python3-3.8.6/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/nix/store/b7m9y5mxvi54bxhl8j75rxhmfrnj2m07-python3.8-pytest-6.1.2/lib/python3.8/site-packages/pytest/__main__.py", line 5, in <module>
    raise SystemExit(pytest.console_main())
  File "/nix/store/b7m9y5mxvi54bxhl8j75rxhmfrnj2m07-python3.8-pytest-6.1.2/lib/python3.8/site-packages/_pytest/config/__init__.py", line 187, in console_main
    code = main()
  File "/nix/store/b7m9y5mxvi54bxhl8j75rxhmfrnj2m07-python3.8-pytest-6.1.2/lib/python3.8/site-packages/_pytest/config/__init__.py", line 164, in main
    ret = config.hook.pytest_cmdline_main(
  File "/nix/store/1rh4pvy72q9zkbzc5h6f25c4g8cyrhx3-python3.8-pluggy-0.13.1/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/nix/store/1rh4pvy72q9zkbzc5h6f25c4g8cyrhx3-python3.8-pluggy-0.13.1/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/nix/store/1rh4pvy72q9zkbzc5h6f25c4g8cyrhx3-python3.8-pluggy-0.13.1/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/nix/store/1rh4pvy72q9zkbzc5h6f25c4g8cyrhx3-python3.8-pluggy-0.13.1/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/nix/store/b7m9y5mxvi54bxhl8j75rxhmfrnj2m07-python3.8-pytest-6.1.2/lib/python3.8/site-packages/_pytest/main.py", line 306, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/nix/store/b7m9y5mxvi54bxhl8j75rxhmfrnj2m07-python3.8-pytest-6.1.2/lib/python3.8/site-packages/_pytest/main.py", line 257, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "/nix/store/b7m9y5mxvi54bxhl8j75rxhmfrnj2m07-python3.8-pytest-6.1.2/lib/python3.8/site-packages/_pytest/main.py", line 313, in _main
    config.hook.pytest_runtestloop(session=session)
  File "/nix/store/1rh4pvy72q9zkbzc5h6f25c4g8cyrhx3-python3.8-pluggy-0.13.1/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/nix/store/1rh4pvy72q9zkbzc5h6f25c4g8cyrhx3-python3.8-pluggy-0.13.1/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/nix/store/1rh4pvy72q9zkbzc5h6f25c4g8cyrhx3-python3.8-pluggy-0.13.1/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/nix/store/1rh4pvy72q9zkbzc5h6f25c4g8cyrhx3-python3.8-pluggy-0.13.1/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/nix/store/b7m9y5mxvi54bxhl8j75rxhmfrnj2m07-python3.8-pytest-6.1.2/lib/python3.8/site-packages/_pytest/main.py", line 338, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "/nix/store/1rh4pvy72q9zkbzc5h6f25c4g8cyrhx3-python3.8-pluggy-0.13.1/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/nix/store/1rh4pvy72q9zkbzc5h6f25c4g8cyrhx3-python3.8-pluggy-0.13.1/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/nix/store/1rh4pvy72q9zkbzc5h6f25c4g8cyrhx3-python3.8-pluggy-0.13.1/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/nix/store/1rh4pvy72q9zkbzc5h6f25c4g8cyrhx3-python3.8-pluggy-0.13.1/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/nix/store/b7m9y5mxvi54bxhl8j75rxhmfrnj2m07-python3.8-pytest-6.1.2/lib/python3.8/site-packages/_pytest/runner.py", line 110, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "/nix/store/b7m9y5mxvi54bxhl8j75rxhmfrnj2m07-python3.8-pytest-6.1.2/lib/python3.8/site-packages/_pytest/runner.py", line 127, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "/nix/store/b7m9y5mxvi54bxhl8j75rxhmfrnj2m07-python3.8-pytest-6.1.2/lib/python3.8/site-packages/_pytest/runner.py", line 216, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "/nix/store/b7m9y5mxvi54bxhl8j75rxhmfrnj2m07-python3.8-pytest-6.1.2/lib/python3.8/site-packages/_pytest/runner.py", line 255, in call_runtest_hook
    return CallInfo.from_call(
  File "/nix/store/b7m9y5mxvi54bxhl8j75rxhmfrnj2m07-python3.8-pytest-6.1.2/lib/python3.8/site-packages/_pytest/runner.py", line 310, in from_call
    result = func()  # type: Optional[TResult]
  File "/nix/store/b7m9y5mxvi54bxhl8j75rxhmfrnj2m07-python3.8-pytest-6.1.2/lib/python3.8/site-packages/_pytest/runner.py", line 256, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/nix/store/1rh4pvy72q9zkbzc5h6f25c4g8cyrhx3-python3.8-pluggy-0.13.1/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/nix/store/1rh4pvy72q9zkbzc5h6f25c4g8cyrhx3-python3.8-pluggy-0.13.1/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/nix/store/1rh4pvy72q9zkbzc5h6f25c4g8cyrhx3-python3.8-pluggy-0.13.1/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/nix/store/1rh4pvy72q9zkbzc5h6f25c4g8cyrhx3-python3.8-pluggy-0.13.1/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/nix/store/b7m9y5mxvi54bxhl8j75rxhmfrnj2m07-python3.8-pytest-6.1.2/lib/python3.8/site-packages/_pytest/runner.py", line 163, in pytest_runtest_call
    item.runtest()
  File "/nix/store/b7m9y5mxvi54bxhl8j75rxhmfrnj2m07-python3.8-pytest-6.1.2/lib/python3.8/site-packages/_pytest/unittest.py", line 278, in runtest
    self._testcase(result=self)  # type: ignore[arg-type]
  File "/nix/store/jdp800qwb3v330ggl6iq722ww96q2444-python3-3.8.6/lib/python3.8/unittest/case.py", line 736, in __call__
    return self.run(*args, **kwds)
  File "/nix/store/jdp800qwb3v330ggl6iq722ww96q2444-python3-3.8.6/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/nix/store/jdp800qwb3v330ggl6iq722ww96q2444-python3-3.8.6/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/nix/store/pzidjzswskij3cb0a6p70mryl5qrx9ss-python3.8-mock-4.0.2/lib/python3.8/site-packages/mock/mock.py", line 1369, in patched
    return func(*newargs, **newkeywargs)
  File "/build/source/tests/test_log.py", line 43, in test_patroni_logger
    _LOG.exception('test')
  File "/build/source/patroni/log.py", line 20, in debug_exception
    logger_obj.error(msg, *args, exc_info=False, **kwargs)
  File "/nix/store/jdp800qwb3v330ggl6iq722ww96q2444-python3-3.8.6/lib/python3.8/logging/__init__.py", line 1463, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/nix/store/jdp800qwb3v330ggl6iq722ww96q2444-python3-3.8.6/lib/python3.8/logging/__init__.py", line 1577, in _log
    self.handle(record)
  File "/nix/store/jdp800qwb3v330ggl6iq722ww96q2444-python3-3.8.6/lib/python3.8/logging/__init__.py", line 1587, in handle
    self.callHandlers(record)
  File "/nix/store/jdp800qwb3v330ggl6iq722ww96q2444-python3-3.8.6/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
    hdlr.handle(record)
  File "/nix/store/jdp800qwb3v330ggl6iq722ww96q2444-python3-3.8.6/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/build/source/patroni/log.py", line 72, in emit
    self.patroni_logger.log_handler.handle(record)
Message: "test, DETAIL: 'None'"
Arguments: ()
------------------------------ Captured log call -------------------------------
ERROR    tests.test_log:log.py:20 test, DETAIL: 'None'
=============================== warnings summary ===============================
../../nix/store/wx7iajll6kj6cj5x17bsn2bv1xbiv8bb-python3.8-boto-2.49.0/lib/python3.8/site-packages/boto/plugin.py:40
  /nix/store/wx7iajll6kj6cj5x17bsn2bv1xbiv8bb-python3.8-boto-2.49.0/lib/python3.8/site-packages/boto/plugin.py:40: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
FAILED tests/test_log.py::TestPatroniLogger::test_patroni_logger - Exception
=================== 1 failed, 376 passed, 1 warning in 7.78s ===================
```

**Notify maintainers**

@limeytexan

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.84, NixOS, 21.03pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.03pre257780.e9158eca70a"`
 - channels(lukas): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: patroni
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by rmcgibbo**
###### Motivation for this change
Fix https://github.com/NixOS/nixpkgs/issues/107425 (patroni tests timing out) by upgrading package.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rmcgibbo** [comment]
Result of `nixpkgs-review pr 108019` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>patroni</li>
    <li>python37Packages.pysyncobj</li>
    <li>python38Packages.pysyncobj</li>
    <li>python39Packages.pysyncobj</li>
  </ul>
</details>

**Review by prusnak — APPROVED** [review]

**Review by jonringer — COMMENTED** [review]
otherwise diff lgtm

**Review by limeytexan — APPROVED** [review]
Tested changes and looks good to me - many thanks!

**Comment by arianvp** [comment]
Could rebase this to solve the conflict?

**Comment by rmcgibbo** [comment]
It looks like this was done in https://github.com/NixOS/nixpkgs/pull/111720 anyways.

**Pull request closed without merging**
