### PR TITLE
nixUnstable: 2.4pre20210707_02dd6bb -> 2.4pre20210802_47e96bb 

### PR DESCRIPTION
**Pull request by happysalada**
###### Motivation for this change

The [manual](https://nixos.org/manual/nix/unstable/command-ref/new-cli/nix3-build.html) mentions a `--eval-store` 
trying it with the latest version gives
```
error: unrecognised flag '--eval-store'
Try 'nix --help' for more information.
```

On another note, I was trying that option because I wonder how to evaluate a derivation on a remote machine.

So my question is:
- Does the `--eval-store` flag evaluate on another store ? Will it try to build on local first? 
- Related question is suppose you get a drv file with `nix eval` how can you build that on another machine ?

Finally I understand that you are very busy, so if you don't have time to answer, no worries!

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]
please revert the formatting.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 132739` at 4a45a905 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/ef9e01f9161f743bcefa4610de38c490">hydra-unstable</a></li>
  </ul>
</details>
<details>
  <summary>3 packages built successfully:</summary>
  <ul>
    <li>nix-update</li>
    <li>nixUnstable</li>
    <li>nixpkgs-review</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by happysalada** [comment]
@SuperSandro2000 reverted.

**Comment by nrdxp** [comment]
So this is causing hydra to fail, perhaps we will need to update hydra-unstable as well?

**Comment by happysalada** [comment]
@nrdxp thank you for the review, I've never updated nix before. I'll take a look at hydraunstable.

**Comment by happysalada** [comment]
I've checked, hydra-unstable has not been updated since may so I'm not sure if this release breaks it specifically.

Are you on linux by any chance ?
I'm on darwin and so I can't build hydra. If anybody had the hydra logs, I would be happy to take a look at the failure.
(the two bots report an empty log).

**Comment by Mic92** [comment]
cc @grahamc

**Comment by Ma27** [comment]
> I've checked, hydra-unstable has not been updated since may so I'm not sure if this release breaks it specifically.

I'm pretty sure it does because some internal C++ APIs that Hydra uses were changed (at least that was the case for all the other build problems in the past).

Triggering an ofborg build for hydra-unstable to get you some logs:

@ofborg build hydra-unstable

**Comment by nrdxp** [comment]
So I took the liberty of attempting an update on hydra like so:
```diff
   {
     hydra-unstable = callPackage ./common.nix {
  -    version = "2021-05-03";
  +    version = "2021-07-29";
       src = fetchFromGitHub {
         owner = "NixOS";
         repo = "hydra";
  -      rev = "886e6f85e45a1f757e9b77d2a9e4539fbde29468";
  -      sha256 = "t7Qb57Xjc0Ou+VDGC1N5u9AmeODW6MVOwKSrYRJq5f0=";
  +      rev = "4e9455160270b9b933582501a47430690d66e5b4";
  +      sha256 = "sha256-Uj0N7fbypQtn8m26cdR2UYK1xTB1QMXZ0lfzz1y+Bgw=";
       };
       nix = nixUnstable;
```
Unfortunately this still failed with the attached log
[hydra.log](https://github.com/NixOS/nixpkgs/files/6947161/hydra.log)

**Comment by SuperSandro2000** [comment]
Please bump hydra and then we can merge this.

**Comment by happysalada** [comment]
I had to enable nixpkgs unfree, since I didn't have nixos machine at hand. I hope it didn't influence the hash.

**Comment by nrdxp** [comment]
Result of `nixpkgs-review pr 132739` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>hydra-unstable</li>
    <li>nix-update</li>
    <li>nixUnstable</li>
    <li>nixpkgs-review</li>
  </ul>
</details>

**Review by nrdxp — APPROVED** [review]
Packages now build fine. Thanks! I'll just wait for CI to finish and then merge.

**Comment by nrdxp** [comment]
I'll wait for checks to finish, and then merge :+1:

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 132739` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>nix-update</li>
    <li>nixUnstable</li>
    <li>nixpkgs-review</li>
  </ul>
</details>

**Comment by happysalada** [comment]
Hmm, it might just be my machine. but this is the output I had
```
  deleting '/private/tmp/nix-build-nix-2.4pre20210802_47e96bb.drv-0/nix-test/tests/user-envs/store/trash
    deleting unused links...
    note: currently hard linking saves 0.00 MiB
    29 store paths deleted, 0.02 MiB freed
    + test -e /private/tmp/nix-build-nix-2.4pre20210802_47e96bb.drv-0/nix-test/tests/user-envs/store/xxfy9
    + '[' -e /private/tmp/nix-build-nix-2.4pre20210802_47e96bb.drv-0/nix-test/tests/user-envs/store/mqixx4
    + nix-env -e '*'
    uninstalling 'foo-1.0'
    uninstalling 'bar-0.1'
    error: unexpected EOF reading a line
```

**Comment by happysalada** [comment]
Result of `nixpkgs-review pr 132739` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>nix-update</li>
    <li>nixUnstable</li>
    <li>nixpkgs-review</li>
  </ul>
</details>

**Comment by happysalada** [comment]
It seems it was just a transitive failure. Weird.

**Comment by happysalada** [comment]
Got confirmation that this builds fine on Aarch64
@nrdxp  @SuperSandro2000 Thank you again for the help!

**Comment by SuperSandro2000** [comment]
The test for hydra-unstable fails.

**Comment by SuperSandro2000** [comment]
I had this PR open in nixpkgs-review and the test times out waiting for an port to be opened.

**Comment by Ma27** [comment]
Seems as if some perl dependencies are missing. I can file a PR later today.

**Comment by Ma27** [comment]
Fix is in https://github.com/NixOS/nixpkgs/pull/133482. Would be great if we could backport both #133482 and this PR later.

**Pull request merged**
