### PR TITLE
python3Packages.aiotractive: init at 0.5.1

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Python client for the Tractive REST API

https://github.com/zhulik/aiotractive

- Related Home Assistant change: https://github.com/home-assistant/core/pull/51002
- Target Home Assistant release: 2021.7.0

ToDo:

- [ ] Update `component-packages` 
- [ ] Enable tests in Home Assistant

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 126328` at a87aa4a2 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python38Packages.aiotractive</li>
    <li>python39Packages.aiotractive</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
> Hass will automatically install the module in the deps subdirectory only when the user adds the corresponding integration

That most likely will not work on nixos.

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by zhulik** [comment]
Sorry, I'm not familiar with nixos internals, but does it really install all possible hass dependencies? Sound like a huge overhead

**Comment by SuperSandro2000** [comment]
> Hey there, the author of the module and the integration here. I don't think you need to create a package for it because it's an optional dependency for hass and is not required for installing it. Hass will automatically install the module in the deps subdirectory only when the user adds the corresponding integration

That does not work on NixOS and yes we require this package.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 126328` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages built:
</summary>
<ul>
<li>python38Packages.aiotractive</li>
<li>python39Packages.aiotractive</li>
</ul>
</details>

**Comment by dotlambda** [comment]
> Sorry, I'm not familiar with nixos internals, but does it really install all possible hass dependencies? Sound like a huge overhead

NixOS's Home Assistant module only installs those packages required for the components used in the configuration. Still, the "recipes" for all those packages need to be added to Nixpkgs.

**Pull request merged**
