### PR TITLE
rustscan: fix build on darwin, set meta.platforms for maintainer Supersandro2000 

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Motivation for this change

I want Hydra builds for my maintained packages.

Tested using ``nix-build maintainers/scripts/build.nix --argstr maintainer SuperSandro2000`` on NixOS, Nix and Darwin.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zowoq** [comment]
> I want Hydra builds for my maintained packages.

I can't see any of these not being built on hydra.

Most of these look to be go or rust and inherit their platforms from the respective builder, setting `meta.platforms` is redundant.

**Comment by r-burns** [comment]
Ah! Thank you, that makes sense. So you only need the explicit platforms.all when it's a toplevel package?

**Comment by SuperSandro2000** [comment]
> Most of these look to be go or rust and inherit their platforms from the respective builder, setting meta.platforms is redundant.

I want a linter for such stuff which tells me yay or nay...

**Review by zowoq — APPROVED** [review]
Built `rustscan` on darwin.

**Comment by zowoq** [comment]
> So you only need the explicit platforms.all when it's a toplevel package?

Depends, some other package sets or builders will cover things like `meta.platforms` but others don't.

> I want a linter for such stuff

A couple of people have written linters for checking various things but I don't think they would cover these packages. I might come up with something just to cover go and rust.

**Pull request merged**
