### PR TITLE
odo: init at 0.3.3

### PR DESCRIPTION
**Pull request by FRidh**
Requires #8763 and #8737, so travis will obviously fail.

Tested with nox-review wip

### CODE REVIEW

**Comment by lethalman** [comment]
Built locally thanks.

**Comment by nckx** [comment]
How? `licenses.bsd4` doesn't even exist.

**Comment by lethalman** [comment]
@nckx building doesn't check for the meta, forgot to evaluate it. Thanks for the fix.

**Comment by nckx** [comment]
True.

(Which is why I test with `nix-env -i` and completely pollute my local profile nowadays :disappointed: )

**Comment by FRidh** [comment]
ah good point, thanks. Intuitively I just went for the `bsd4`. Any interest in an alias? :-)

**Pull request merged**
