### PR TITLE
enpass: 6.0.1.239 -> 6.5.1.723

### PR DESCRIPTION
**Pull request by ewok-old**
###### Motivation for this change
Enpass has not been updating for 2 years.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ewok** [comment]
I forgot to add a reviewer. 😞 

@guillaumekoenig could you please have a look on this? I added you as a maintainer in meta, because 'git blame' showed you as a a last committer here.

**Comment by guillaumekoenig** [comment]
> I forgot to add a reviewer. 😞
> 
> @guillaumekoenig could you please have a look on this? I added you as a maintainer in meta, because 'git blame' showed you as a a last committer here.

Haven't used NixOS in a year. Don't add me, add _you_ as maintainer.

**Comment by WolfangAukang** [comment]
Result of `nixpkgs-review pr 107020` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>enpass</li>
  </ul>
</details>

**Review by WolfangAukang — APPROVED** [review]

**Comment by thiagokokada** [comment]
Result of `nixpkgs-review pr 107020` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>enpass</li>
  </ul>
</details>

**Review by thiagokokada — APPROVED** [review]

**Pull request merged**
