### PR TITLE
nixos-rebuild, nixos-install: add support for --file and --attr flags

### PR DESCRIPTION
**Pull request by amozeo**
## Description of changes

Allows building NixOS and using nixos-rebuild commands with a NixOS configuration located in plain nix file. This is useful for using nixos-rebuild command with a NixOS system configuration located in a nix file that is not a flake or a NixOS configuration module.

if you want to test this feature with your own configuration (if not using flakes), you can use this

```nix
{ nixosEval ? import <nixpkgs/nixos/lib/eval-config.nix> }:

nixosEval {
  modules = [( import <path/to/nixosConfiguration.nix> )];
}
```

NixOS configuration in plain nix file can be created using `nixos` function in nixpkgs, or importing and calling `nixos/lib/eval-config.nix`.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - nixos/tests/installer.nix simple
  - nixos/tests/installer.nix switchToFlake
  - nixos/tests/installer.nix switchToByAttr (new test)
  - nixos/tests/installer.nix switchFromByAttrToFlake (new test)
  - [x] made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

maintainer mention: @Profpatsch

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by AndersonTorres — APPROVED** [review]
Looks very nice!

**Comment by tomberek** [comment]
Result of `nixpkgs-review pr 320462` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>nixos-rebuild</li>
    <li>tests.testers.lycheeLinkCheck.network</li>
    <li>tests.testers.nixosTest-example</li>
    <li>tests.testers.runNixOSTest-example</li>
    <li>tests.trivial-builders.references</li>
  </ul>
</details>

**Review by tomberek — APPROVED** [review]
Builds, runs, tests as expected.

**Comment by infinisil** [comment]
This is awesome! I just opened https://github.com/NixOS/nixpkgs/pull/333788 to take this to the next step, but unfortunately I don't have the time to pull it through, so I'd appreciate if you could help out with that @amozeo :pray:

**Pull request merged**
