### PR TITLE
nixos/starship: Allow using presets

### PR DESCRIPTION
**Pull request by jtojnar**
###### Description of changes

Until there is a [native method](https://github.com/starship/starship/issues/3039), we need to merge it manually.

Also introduce `runPythonScript` trivial builder.

cc @lilyball @danth 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jtojnar** [comment]
Maybe rather than presets we should allow merging multiple files. Or just allow passing `settingsFile` in addition to settings and allow user to merge whatever they want.

**Comment by jacekszymanski** [comment]
FWIW, I [approached](https://github.com/jacekszymanski/nur-packages/tree/master/pkgs/starship) this problem by exposing preset TOML files in the Nix store and then simply reading them into Nix with `fromTOML` and then merging them in the config, along with possible user overrides in the config.

**Comment by lilyball** [comment]
I did something similar in my local config, I have a simple shell script that just dumps all the presets into local TOML files, and then I have a module that declares all the presets as options, and for any enabled prefix it loads the TOML file and maps `mkDefault` onto every value (with `lib.mapAttrsRecursive`). With this approach I just have to occasionally run the update script, and then add a new preset name to the presets list if any new TOML files show up.

The approach in this PR has the downside of only allowing one preset at a time. Meanwhile in my local config I enable both `nerd-font-symbols` and `bracketed-segments`.

**Comment by jtojnar** [comment]
I decided not using startship since I do not like how the config does not compose.

**Pull request closed without merging**
