### PR TITLE
zrythm: 1.0.0-beta.4.9.1 -> 1.0.0-beta.6.4.1

### LINKED ISSUE #252561: Update request: zrythm 1.0.0-beta.4.9.1 → 1.0.0-beta.4.12.34
- Package name: zrythm
- Latest released version: v1.0.0-beta.4.12.34

- Current version on the unstable channel:  1.0.0-beta.4.9.1
- Current version on the stable/release channel: 1.0.0-beta.4.6.3

- [ X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@yuuyins 
@magnetophon 
@tshaynik 

-----

Note for maintainers: Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by PowerUser64**
## Description of changes

Update zrythm to [`v1.0.0-beta.6.4.1`](https://gitlab.zrythm.org/zrythm/zrythm/-/tags/v1.0.0-beta.6.4.1). Please note that I am using `overrideAttrs` in two places because nixpkgs' gtk and rtaudio are not on new enough versions for zrythm to compile. I was told that using `overrideAttrs` in buildInputs *should* be allowed [here](https://github.com/NixOS/nixpkgs/pull/253765#issuecomment-1889355182), but please let me know if this is not true.

Closes https://github.com/NixOS/nixpkgs/issues/252561
Closes #253765

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by contini-aron** [comment]
@PowerUser64 i was trying to build from source in the meantime this PR is reviewed and got an hash error mismatch

### steps to reproduce
```bash
 nix build github:PowerUser64/nixpkgs/zrythm-6.3-b#zrythm
```
### error

```bash
error: hash mismatch in fixed-output derivation '/nix/store/hckfhayyh20p35qhb772dmgsb854bwqz-source.drv':
         specified: sha256-OjUZzU5mqsM+8HkUvSD7E3WPiO+X9uzDwQA4rheJXTg=
            got:    sha256-veRzcxLGP8jkm0qWK98aSfEMv/UFPkgPOT/yRI8jfdc=
```
the specified hash seems to be the one for gitlab zrythm in this code block
```nix
  src = fetchFromGitLab {
    domain = "gitlab.zrythm.org";
    owner = "zrythm";
    repo = "zrythm";
    rev = "v${finalAttrs.version}";
    hash = "sha256-OjUZzU5mqsM+8HkUvSD7E3WPiO+X9uzDwQA4rheJXTg=";
  };
```

**Comment by Aleksanaa** [comment]
Don't override it. Just wait for https://github.com/NixOS/nixpkgs/pull/291339

**Comment by eclairevoyant** [comment]
FYI zrythm seems to be a troublesome program that always uses unreleased gtk/libadwaita versions, so we can never upgrade immediately without overriding

**Comment by Aleksanaa** [comment]
> FYI zrythm seems to be a troublesome program that always uses unreleased gtk/libadwaita versions, so we can never upgrade immediately without overriding

The flatpak guys, yeah

**Comment by PowerUser64** [comment]
Zrythm is still in beta, so I'm thinking it might be easier to maintain a package once it gets its first stable release. I could be wrong though.

**Comment by eclairevoyant** [comment]
It's been in alpha for a year and in beta for 2 years more, I'm not sure when a stable release would materialise.

**Comment by PowerUser64** [comment]
The release should be soon, hopefully in the next few months. There are only 9 issues left on the v1.rc milestone according to the [zrythm gitlab](https://gitlab.zrythm.org/zrythm/zrythm/-/issues/?sort=created_date&state=opened&milestone_title=v1.rc&first_page_size=100). Developing a DAW solo takes a lot of time I guess.

cc @alex-tee

**Comment by alex-tee** [comment]
Yes v1 RC should be out soon. I don't plan to use any unreleased libadwaita/gtk API anymore for v1 so the latest stable releases should be OK.

Just a nitpick: can you please fetch the source tarball from https://www.zrythm.org/releases/ instead of gitlab? Our Gitlab instance is really only meant to be used for development, not distribution. I want to avoid unnecessary traffic to it.

Also FYI json-glib and libaudec are no longer used so they can be removed from the dependencies.

**Comment by PowerUser64** [comment]
Thanks for the response and feedback @alex-tee! I'll adjust the source to retrieve from zrythm.org, and remove the old deps!

**Comment by PowerUser64** [comment]
Superseded by #306959 (Merged)

**Pull request closed without merging**
