### PR TITLE
pypy{27,39}: 7.3.11 -> 7.3.12; pypy310: init at 7.3.12

### PR DESCRIPTION
**Pull request by thiagokokada**
## Description of changes

https://www.pypy.org/posts/2023/06/pypy-v7312-release.html

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by thiagokokada** [comment]
@ofborg build pythonInterpreters.pypy27_prebuilt pythonInterpreters.pypy39_prebuilt

**Comment by thiagokokada** [comment]
@ofborg build pythonInterpreters.pypy27_prebuilt pythonInterpreters.pypy39_prebuilt pypy27 pypy39 pypy310

**Comment by thiagokokada** [comment]
For reviewers: `pypy27.passthru.tests` is expected to fail since it tries to import a few modules (like `requests`) that doesn't work in Python 2.7 anymore.

**Comment by AndersonTorres** [comment]
> For reviewers: `pypy27.passthru.tests` is expected to fail since it tries to import a few modules (like `requests`) that doesn't work in Python 2.7 anymore.

It's possible to update this test? (Not now.)

**Comment by thiagokokada** [comment]
> > For reviewers: `pypy27.passthru.tests` is expected to fail since it tries to import a few modules (like `requests`) that doesn't work in Python 2.7 anymore.
> 
> It's possible to update this test in the future?

I think it is probably better to disable it.

**Comment by thiagokokada** [comment]
> It's possible to update this test in the future?

Fixed those issues by disabling the affected tests.

**Review by AndersonTorres — APPROVED** [review]

**Pull request merged**
