### PR TITLE
[Backport release-24.05] forgejo: 7.0.9 -> 7.0.10

### PR DESCRIPTION
**Pull request by NyCodeGHG**
Release Notes: https://codeberg.org/forgejo/forgejo/milestone/8286

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by NyCodeGHG** [comment]
Looks like upstream bumped the required go version, but I cannot get it to build somehow

**Comment by emilylange** [comment]
Needs something like:

```diff
diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
index 86fc821111e2..7784ea70e472 100644
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -30693,6 +30693,10 @@ with pkgs;
 
   fontpreview = callPackage ../applications/misc/fontpreview { };
 
+  forgejo = callPackage ../by-name/fo/forgejo/package.nix {
+    # buildGoModule = buildGo123Module;
+  };
+
   fossil = callPackage ../applications/version-management/fossil {
     sqlite = sqlite.override { enableDeserialize = true; };
   };
```

Just as a fyi:
Even with by-name packages, we override stuff like that in `all-packages.nix` to keep our override pattern.
See https://github.com/NixOS/nixpkgs/pull/348925#issuecomment-2418187539

---

Also, please fix the commit message.
The package is called `forgejo` in `24.05`, not `forgejo-lts`.

But take your time. This isn't urgent.

Yes, this is a security release, but its severity isn't that high and it will take a fair time until this reaches our `nixos-24.05` `nixos-24.05-small` channels anyway.

**Comment by adamcstephens** [comment]
This should be a cherry-pick -x of the relevant commit from master. Doing so gives a link back to the original commit.

**Comment by NyCodeGHG** [comment]
> This should be a cherry-pick -x of the relevant commit from master. Doing so gives a link back to the original commit.

Should this still be done when the commit differs quite a bit from the original?
I mean this commit has the go bump which is required to build in 24.05, which has nothing to do with the original one

**Comment by adamcstephens** [comment]
> Should this still be done when the commit differs quite a bit from the original?

Yeah, it's a bit more work to do since it requires a rebase, but in the end shouldn't be that bad.

**Review by emilylange — APPROVED** [review]
The commit message is technically missing the

> Release Notes: https://codeberg.org/forgejo/forgejo/milestone/8286

bit, but that's okay.
No need to fix and force push that now.
Just something I wanted to point out, for the sake of acknowledging part of the failing backport CI check.

Builds on `x86_64-linux`:
```bash
# nix-build -A forgejo.tests
/nix/store/zapcwj2ylg18kdkmy3br3md4qkzv1h3j-vm-test-run-forgejo-mysql
/nix/store/jd2lmv7pan59vyxr56cnh9r2h0jv02wh-vm-test-run-forgejo-postgres
/nix/store/jm0y4nkr95n3kf7drfb12dim98dkwdy8-vm-test-run-forgejo-sqlite3
```

thanks :)

**Comment by adamcstephens** [comment]
`aarch64-linux`
/nix/store/mkd8a2cji8l6lviv1s48v3b1pwlmdx57-vm-test-run-forgejo-mysql
/nix/store/1flfzbd1pldrzvkgkvws8wjr5g9ay1dn-vm-test-run-forgejo-postgres
/nix/store/3944nqxhnns19a20sk6irhncxh62bgiv-vm-test-run-forgejo-sqlite3

**Pull request merged**
