### PR TITLE
z88dk: install in correct place, make tests run

### PR DESCRIPTION
**Pull request by hzeller**
## Description of changes

The z88dk package was not really working anymore after recent updates, so this is fixing that.

  * The final installation was not at the correct place; looks like
     the DESTDIR that worked previously needs to be PREFIX now (the location where the binaries ended
     up where in  `$out/usr/local/bin` instead of `$out/bin`. Similar with the bunch of `share/`.

  * In general fix up some things that apparently used to be needed in the past but no longer are.
 
   * Make tests work. These also didn't run anymore even though it looked they might've in the past, though that is unclear, as there were no Perl dependencies yet.  The `make testsuite` was not enough, `make test` is also needed ....
 
   * The tests need a bunch of Perl packages, not all of which were available in nixpkgs yet. For that, add these as local Perl packages for now (with the plan to actually move them to perl-packages.nix after this is submitted; for now have them in this in this file to have everything self-contained and don't complicate things with additional files to be added to this PR).

   * Also: run `nixfmt` and apply `finalAttrs` pattern (separate commit).
  
Tested by creating a mini-binary and inspect the disassembly:

```bash
echo "int main() { return 42; }" > foo.c
zcc +m100 -subtype=default -create-app foo.c -o foo.bin
z88dk-dis foo.bin
```
Tested on `x86_64-linux` and `aarch64-linux`.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by hzeller** [comment]
Maybe this PR went under the radar ?

**Comment by hzeller** [comment]
@siraben Are you still maintaining this package or should I widen the set of reviewers ?

**Comment by siraben** [comment]
@hzeller please widen the set of reviewers. I haven't been maintaining this package recently.

**Comment by hzeller** [comment]
Addning @emilytrau as she is interested in small devices.

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 329782` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>z88dk</li>
  </ul>
</details>

**Review by siraben — APPROVED** [review]
This looks good for me and runs and creates the binaries. Pending approval by at least another person.

**Pull request merged**
