### PR TITLE
singularity: 4.1.1 -> 4.1.2

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Changelog: https://github.com/sylabs/singularity/releases/tag/v4.1.2

cc @ShamrockLee @jbedo 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 293787` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>singularity</li>
    <li>singularity-overriden-nixos</li>
    <li>udocker</li>
    <li>udocker.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 293787` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>singularity</li>
    <li>singularity-overriden-nixos</li>
    <li>udocker</li>
    <li>udocker.dist</li>
  </ul>
</details>

**Comment by drupol** [comment]
> `singularity.tests` builds fine on `x86_64-linux` and fails on `aarch64-linux` with:
> 
> ```
> copying path '/nix/store/hs7qmvrbc3ss24n72iff88lks0m8hhaw-singularity-ce-4.1.1' from 'https://cache.nixos.org'...
> Formatting '/nix/store/h7drmdg3xi4ghi8fb59nfkwcvlsrfksd-singularity-image-hello-cowsay.img/disk-image.qcow2', fmt=qcow2 cluster_size=65536 extended_l2=off compression_type=zlib size>
> loading kernel modules...
> cat: can't open '/nix/store/fa19n6l32ig6bfpbawkjifpavhx8qlbx-linux-6.6.19-shrunk/insmod-list': No such file or directory
> mounting Nix store...
> mounting host's temporary directory...
> starting stage 2 (/nix/store/m3rysrzam7kj4ayr47d2p5wvm3w50746-vm-run-stage2)
> mke2fs 1.47.0 (5-Feb-2023)
> Discarding device blocks: done                            
> Creating filesystem with 262144 4k blocks and 65536 inodes
> Filesystem UUID: 18de6b07-a2ec-4e5b-a076-cbc4a2b15717
> Superblock backups stored on blocks: 
>         32768, 98304, 163840, 229376
> 
> Allocating group tables: done                            
> Writing inode tables: done                            
> Creating journal (8192 blocks): done
> Writing superblocks and filesystem accounting information: done
> 
> cp: cannot access '/nix/store/hr97rbiw87wl5ya46p3h5p1s5rx712bv-gcc-13.2.0-lib/share': Cannot allocate memory
> [    5.081342] reboot: Power down
> ```
> 
> It is not a regression as the same behavior happens on `master`.

Can we mark it as broken for that arch?

**Comment by ShamrockLee** [comment]
> Can we mark it as broken for that arch?

The breakage seems to be caused by `vmTools`, which is only used to build images for `passthru.tests`.

The breakage of a `passthru.tests` test case doesn't sound sufficient to mark a package as broken.

**Comment by drupol** [comment]
> > Can we mark it as broken for that arch?
> 
> The breakage seems to be caused by `vmTools`, which is only used to build images for `passthru.tests`.
> 
> The breakage of a `passthru.tests` test case doesn't sound sufficient to mark a package as broken.

Is there an open issue for that?

**Comment by ShamrockLee** [comment]
> > > Can we mark it as broken for that arch?
> > 
> > 
> > The breakage seems to be caused by `vmTools`, which is only used to build images for `passthru.tests`.
> > The breakage of a `passthru.tests` test case doesn't sound sufficient to mark a package as broken.
> 
> Is there an open issue for that?

I haven't found any.

My current understanding toward the breakage only comes from the piece of build log pasted by @GaetanLepage. I'll need to test it on NixOnDroid and/or Raspberry Pi to see what is actually broken. (virtualization-related build failure on NixOnDroid could also be caused by PRoot, and RPi seems to be the best bet.)

**Comment by ShamrockLee** [comment]
At least `singularity` for aarch64-linux builds alright on Hydra.

https://hydra.nixos.org/build/252186106

**Comment by GaetanLepage** [comment]
> At least `singularity` for aarch64-linux builds alright on Hydra.

Yes, `singularity` itself does build fine on `aarch64-linux`. `singularity.tests` fails.

**Comment by GaetanLepage** [comment]
Should we merge then @ShamrockLee ?

**Comment by ShamrockLee** [comment]
I failed to run the image built by `singularity.tests.image-hello-cowsay` on my laptop.

**Comment by ShamrockLee** [comment]
This image-running failure happens to SingularityCE 4.1.1 as well, which means that `singularity` on Nixpkgs `master` is already broken. We could say in this context that this update causes no regression :upside_down_face:.

**Comment by ShamrockLee** [comment]
Just created an issue #295809 to track the image-running failure.

**Pull request merged**
