### PR TITLE
carla: do not double-wrap

### PR DESCRIPTION
**Pull request by Artturin**
###### Motivation for this change
Supersedes #117880

###### Things done
the main program launches but i did not test further

i know a another solution would be to use buildPythonApplication

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tobiasBora** [comment]
Thanks for your work, however the result is not really the expected one and is a regression compared to https://github.com/NixOS/nixpkgs/pull/117880. In fact the problem is not that it's doubled wrapped (the second wrapper was in fact a wrapper coming directly from carla, not nix), but that it's just wrapped. And the package is still wrapped, as before (it may be "better wrapped", no idea, but the number of wrappers is the same at least):
```
[nix-shell:~/.cache/nixpkgs-review/pr-140117]$ cat $(which carla)
...
exec -a "$0" "/nix/store/mxfaf7l10w8390y5x4vyn8dafxqi8wzw-carla-2.4.0/bin/.carla-wrapped"  "$@"
[nix-shell:~/.cache/nixpkgs-review/pr-140117]$ cat /nix/store/mxfaf7l10w8390y5x4vyn8dafxqi8wzw-carla-2.4.0/bin/.carla-wrapped
...
exec $PYTHON "$INSTALL_PREFIX"/share/carla/carla --with-appname="$0" --with-libprefix="$INSTALL_PREFIX" "$@"
```
See the `--with-appname="$0"`: it's being replaced by `.carla-wrapped` at run time, like the old version, so the issue is still there when I follow this procedure https://github.com/jackaudio/new-session-manager/issues/73:

image
 
As you can see many "carla" instances are spawned, to be precise a new one appears everytime . That said, this time the result is a bit different compared to before: the first instance does save the instance, no idea why (maybe new-session-manager improved something recently?) but I'm not sure what is means to have multiple carla launched in parallel with different configurations. However the fact that it spawns many instances is anyway a problem.

I tried again https://github.com/NixOS/nixpkgs/pull/117880 and the problem does not appear. The only problem there is that it does not patch all carla executable. I guess one should grep and replace appropriately all `--with-appname="$0"` with ``--with-appname="NAMEOFTHEEXECUTABLEBEFOREWRAPPER"`` in the patch phase.

**Comment by tobiasBora** [comment]
Also any reason you removed mark aarch64-linux as bad? Is it just to do like the previous PR? Because if I trust https://github.com/NixOS/nixpkgs/issues/108273 it should build now.

**Comment by tobiasBora** [comment]
Just proposed here a proper fix for the bad `--app-name`, the compatibility with NSM has been tested: https://github.com/NixOS/nixpkgs/pull/140129 (I was not sure if I should use your method to patch as I'm not a patching expert. and as your method has the same number of wrappers (I think)... so I choose the existing solution to have minimal changes, let me know if you think your method provides a significant improvement)

**Comment by Artturin** [comment]
> Also any reason you mark aarch64-linux as bad? Is it just to do like the previous PR? Because if I trust #108273 it should build now.

i didn't remember that i closed that issue 😅

**Comment by Artturin** [comment]
also yep seems like there's almost the same number of files in bin/ though there's `.carla-single-wrapped_` but that should be inconsequential

guess my eyes played tricks on me

**Pull request closed without merging**
