### PR TITLE
coreuniverse: init at 4.2.0

### PR DESCRIPTION
**Pull request by dan4ik605743**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
@dan4ik605743 please resolve the merge conflict

**Comment by dan4ik605743** [comment]
ok

**Comment by dan4ik605743** [comment]
@SuperSandro2000 I will say honestly. I do not understand how to solve the conflict. I easier to re-create PR and Branch. You can tell please. I will blogger

**Comment by dan4ik605743** [comment]
nice

**Comment by dan4ik605743** [comment]
@SuperSandro2000 I want to make SCOOP from these packages. It will be easier for me now closed all PR and remove measured packages. And make PR immediately with SCOOP.

**Comment by SuperSandro2000** [comment]
> @SuperSandro2000 I want to make SCOOP from these packages. It will be easier for me now closed all PR and remove measured packages. And make PR immediately with SCOOP.

I think so, too.

**Comment by dan4ik605743** [comment]
> I think so, too.

Only I need your help

**Comment by dan4ik605743** [comment]
> > @SuperSandro2000 I want to make SCOOP from these packages. It will be easier for me now closed all PR and remove measured packages. And make PR immediately with SCOOP.
> 
> I think so, too.

@SuperSandro2000 I'm just the first time dealing with SCOOP. Let me write to Gmail?

**Comment by dan4ik605743** [comment]
@SuperSandro2000 I'm just the first time dealing with SCOOP. Let me write to Gmail?

**Comment by dan4ik605743** [comment]
@SuperSandro2000 check gmail

**Comment by dan4ik605743** [comment]
@SuperSandro2000  Now I woined everything. When I do SCOOP. Delete packages that are already in the branches. I sent you to Gmail what I want to do. I just need to patch holes and that's it. What I am and ask you to help me.

**Pull request closed without merging**
