### PR TITLE
haskellPackages.vulkan: Fix dependency for vulkan

### PR DESCRIPTION
**Pull request by expipiplus1**
Note that the version of this package in nixpkgs currently (1.7.0.0) doesn't
compile. However the newest version (2.0.0.0) does, hopefully this gets bumped
soon :)

### CODE REVIEW

**Comment by peti** [comment]
Considering that this update is already in `haskell-updates` @ 69ede59f3d0a6de6dbd6771f522144944960d746, I think we can just wait a day or two until the branch gets merged into master. OK?

**Comment by expipiplus1** [comment]
Sounds good to me, thanks!

**Comment by peti** [comment]
I don't understand what you mean???

**Comment by expipiplus1** [comment]
I realize that my PR message is a little misleading, this PR changes configuration-common to allow the `vulkan` package to compile. A change which isn't in nixpkgs master at the moment.

**Comment by peti** [comment]
Ah, now I see.

**Comment by peti** [comment]
@GrahamcOfBorg build haskellPackages.vulkan

**Comment by expipiplus1** [comment]
Thanks!

**Pull request merged**
