### PR TITLE
gnomeExtensions: auto-update

### PR DESCRIPTION
**Pull request by rhoriguchi**
###### Things done

Had to use a temporary patch to get this to work. I've also excluded the update of that extension from the PR. #168981

```patch
diff --git a/pkgs/desktops/gnome/extensions/update-extensions.py b/pkgs/desktops/gnome/extensions/update-extensions.py
index 581781fb11a..6363c6479eb 100755
--- a/pkgs/desktops/gnome/extensions/update-extensions.py
+++ b/pkgs/desktops/gnome/extensions/update-extensions.py
@@ -48,6 +48,9 @@ def fetch_extension_data(uuid: str, version: str) -> Tuple[str, str]:
     uuid = uuid.replace("@", "")
     url: str = f"https://extensions.gnome.org/extension-data/{uuid}.v{version}.shell-extension.zip"
 
+    if url == 'https://extensions.gnome.org/extension-data/VitalsCoreCoding.com.v53.shell-extension.zip':
+        url = 'https://extensions.gnome.org/extension-data/VitalsCoreCoding.com.v53.shell-extension_v1BI2FB.zip'
+
     # Yes, we download that file three times:
 
     # The first time is for the maintainter, so they may have a personal backup to fix potential issues
```

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

**cc:** @zendo this will update <https://gitlab.com/rmnvgr/nightthemeswitcher-gnome-shell-extension> to version `63`

### CODE REVIEW

**Comment by piegamesde** [comment]
What does that temporary patch exactly do, and why is it needed?

**Comment by rhoriguchi** [comment]
> What does that temporary patch exactly do, and why is it needed?

Please take a look at the issue #168981 description, after the default nixpkgs part.

**Comment by zendo** [comment]
Updating in unstable-small channel, but night-theme-switcher still is version 53, maybe the old one needs to delete? `pkgs/desktops/gnome/extensions/night-theme-switcher/default.nix`

**Comment by piegamesde** [comment]
@zendo This is mostly correct. We have a manual packaging of the extension that overrides the automatic one. That one would require a separate manual update.

If you want though, you can try to remove it and see whether the automatically generated package for that extension works or can be made working with a few patches.

**Pull request merged**
