### PR TITLE
lxd: 5.20 -> 5.21.0

### PR DESCRIPTION
**Pull request by marsam**
Changelog: https://github.com/canonical/lxd/releases/tag/lxd-5.21.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by adamcstephens** [comment]
@marsam how extensively do you use lxd? What would you think of deprecating lxd for 24.05 in favor of incus?

**Comment by jnsgruk** [comment]
I mean selfishly I'd rather not because i use the crap out of it for work 😅

**Comment by marsam** [comment]
tbh I'm not using lxd nowadays, for different reasons. 
I just saw the new release in my feed, and I thought that I may well update it 😅 

imho lxd is working rn and there may be people depending on it, so I'm a bit reluctant to deprecate it without a strong reason.  However, I won't object if you prefer to depreciate it.

**Comment by adamcstephens** [comment]
Yeah I realize it could be disruptive but it also feels duplicative to have both lxd and incus. I’ve also continued (and will continue) to progress the support for incus but am not updating lxd. If enough people are fine with lxd as is and don’t care about the improvements maybe we can just leave it. I do find that incus fits nixos a bit better given their focus on being distro-agnostic, while lxd is really only focused on supporting snap environments. That said lxd has worked well enough for other distributions.

**Comment by adamcstephens** [comment]
@ofborg build lxd lxd.passthru.tests

**Review by megheaiulian — APPROVED** [review]

**Comment by adamcstephens** [comment]
This version is an LTS. If we're planning to keep lxd in tree, I'd suggest we stick with LTS moving forward.

Note that this is currently failing the lxd-to-incus test, since 5.21 is not currently supported for migrations. Users who make this upgrade will currently not be able to migrate to incus if they so choose. Incus may add this as a supported migration, at the cost of an `auth` table.

**Comment by adamcstephens** [comment]
https://github.com/lxc/incus/pull/639 lxd-to-incus PR for updating to support migrations.

**Pull request merged**
