### PR TITLE
compiler-rt: fix build on armv7l

### LINKED ISSUE #87266: llvmPackages_7.compiler-rt fails to produce output path on armv7l
**Describe the bug**

Same issue as #66693 or #85622, but on armv7l

**Additional context**

On @thefloweringash's hydra, the clang build first started failing with this error after going from 84cf00f98031e93f389f1eb93c4a7374a33cc0a9 to 7e07846d99bed4bd7272b1626038e77a78aa36f6.  
I diffed the range and found 74f3b25896129f20f7af62fd7ccbb9fd1046761b to be the most likely culprit.

It enabled some cmakeFlags globally which used to only be enabled on darwin and useLLVM systems.  
I don't know what exactly these do but, I was able to build `llvmPackages_7.compiler-rt` on my rpi2 by disabling them on aarch32:

```diff
diff --git a/pkgs/development/compilers/llvm/7/compiler-rt.nix b/pkgs/development/compilers/llvm/7/compiler-rt.nix
index 055fb01215f..e30a5171008 100644
--- a/pkgs/development/compilers/llvm/7/compiler-rt.nix
+++ b/pkgs/development/compilers/llvm/7/compiler-rt.nix
@@ -20,7 +20,7 @@ stdenv.mkDerivation {
     "-DSCUDO_DEFAULT_OPTIONS=DeleteSizeMismatch=0:DeallocationTypeMismatch=0"
   ];
 
-  cmakeFlags = [
+  cmakeFlags = stdenv.lib.optionals (!stdenv.isAarch32) [
     "-DCOMPILER_RT_DEFAULT_TARGET_ONLY=ON"
     "-DCMAKE_C_COMPILER_TARGET=${stdenv.hostPlatform.config}"
     "-DCMAKE_ASM_COMPILER_TARGET=${stdenv.hostPlatform.config}"
```

Since I have no idea why this works and what would be affected, I'd rather have someone look over this.

**Notify maintainers**

@TravisWhitaker @matthewbauer

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"armv7l-linux"`
 - host os: `Linux 5.4.25, NixOS, 20.09pre-git (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-unstable2, nixos-20.09pre223023.fce7562cf46, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: llvmPackages
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by thefloweringash**
###### Motivation for this change

Fixes #87266 - llvmPackages_7.compiler-rt fails to produce output path on armv7l

Still testing the builds, so opening as draft.

See also same change for x86 https://github.com/NixOS/nixpkgs/pull/85945

cc @matthewbauer @Atemu @TravisWhitaker 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by matthewbauer** [comment]
Nice work! We probably should consolidate this with `set(X86 i386 i486 i586 i686)` and try to get it accepted upstream.

**Comment by thefloweringash** [comment]
Successfully built for `llvmPackages_{5,6,7,8,9,10}.compiler-rt`. For `llvmPackages_{8,10}` I had to set `doCheck = false` in `llvm` due to test failures.


> We probably should consolidate this with `set(X86 i386 i486 i586 i686)` and try to get it accepted upstream.

I'm following the pattern in #85945 with enough changes to make it work. I didn't look deeply into why this is an appropriate fix. Someone else would need to write the cover letter for upstreaming.

Incidentally, has this been tested in the i486 and i586 cases? I only see a definition of `i386_sources` and `i686_sources` in the [CMakeLists.txt](https://github.com/llvm/llvm-project/blob/d32170dbd5b0d54436537b6b75beaf44324e0c28/compiler-rt/lib/builtins/CMakeLists.txt#L313-L314). I wouldn't be surprised if it fails with the same error as in https://github.com/NixOS/nixpkgs/issues/87266#issuecomment-626139605 for i486 and i586

**Comment by Atemu** [comment]
Hm, is it actually still causing a rebuild on Darwin or is ofBorg bugged?

**Comment by doronbehar** [comment]
Related: #87528

**Pull request merged**
