### PR TITLE
sqlx-cli: 0.7.0 -> 0.7.1

### PR DESCRIPTION
**Pull request by fd**
###### Description of changes

* Updated sqlx-cli to version [`v0.7.1`](https://github.com/launchbadge/sqlx/blob/c70cfaf035b3ffcb1d6f244f6070e92646e83515/CHANGELOG.md#071---2023-07-14)
* Added myself as a maintainer

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tjni** [comment]
Result of `nixpkgs-review pr 243935` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>sqlx-cli</li>
  </ul>
</details>

**Comment by tjni** [comment]
Result of `nixpkgs-review pr 243935` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>sqlx-cli</li>
  </ul>
</details>

**Review by tjni — APPROVED** [review]
Would you mind updating the second commit message to be:
```
maintainers: adding fd
```
You're a super early adopter of GitHub 😮

**Comment by fd** [comment]
@tjni, thanks. I updated the commit message.

IIRC I join GH in the first week of the private beta. Pretty new to Nix though 😂

**Comment by xrelkd** [comment]
Result of `nixpkgs-review pr 243935` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>sqlx-cli</li>
  </ul>
</details>

**Review by vittsjo — APPROVED** [review]
LGTM

**Review by greizgh — APPROVED** [review]

**Comment by fd** [comment]
@tjni All checks have passed. Can this be merged now? Or is there a bot that will do that?

**Comment by tjni** [comment]
It can! It just can take a few days to a week before someone with merge permissions takes a look at it. If it looks like it's slipping through the cracks, you can post in https://discourse.nixos.org/t/prs-ready-for-review/3032/2429, and that usually works in my experience. Thank you for your patience.

**Review by xrelkd — APPROVED** [review]
Hi @NickCao, @marsam, please help us review and merge this PR. Thank you so much!

**Review by NickCao — APPROVED** [review]
Reviewed upstream changes, diff LGTM, commit messages good. Ideally there should be a third commit `sqlx-cli: add fd to maintainers`, but not a blocker here.

**Pull request merged**
