### PR TITLE
python310Packages.openai: 0.27.4 -> 0.27.5, python310Packages.openaiauth: 0.3.2 -> 0.3.6 

### PR DESCRIPTION
**Pull request by fabaff**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 228698` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>chatgpt-retrieval-plugin</li>
    <li>chatgpt-retrieval-plugin.dist</li>
  </ul>
</details>
<details>
  <summary>19 packages built:</summary>
  <ul>
    <li>chatblade</li>
    <li>chatblade.dist</li>
    <li>checkov</li>
    <li>checkov.dist</li>
    <li>home-assistant-component-tests.openai_conversation</li>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>openai (python310Packages.openai)</li>
    <li>openai-full</li>
    <li>openai-full.dist</li>
    <li>openai.dist (python310Packages.openai.dist)</li>
    <li>python310Packages.openaiauth</li>
    <li>python310Packages.openaiauth.dist</li>
    <li>python311Packages.openai</li>
    <li>python311Packages.openai.dist</li>
    <li>python311Packages.openaiauth</li>
    <li>python311Packages.openaiauth.dist</li>
    <li>shell-genie</li>
    <li>shell-genie.dist</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Depends on #228807

**Comment by malob** [comment]
Result of `nixpkgs-review pr 228698` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>checkov</li>
    <li>checkov.dist</li>
  </ul>
</details>
<details>
  <summary>18 packages built:</summary>
  <ul>
    <li>chatblade</li>
    <li>chatblade.dist</li>
    <li>chatgpt-retrieval-plugin</li>
    <li>chatgpt-retrieval-plugin.dist</li>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>openai (python310Packages.openai)</li>
    <li>openai-full</li>
    <li>openai-full.dist</li>
    <li>openai.dist (python310Packages.openai.dist)</li>
    <li>python310Packages.openaiauth</li>
    <li>python310Packages.openaiauth.dist</li>
    <li>python311Packages.openai</li>
    <li>python311Packages.openai.dist</li>
    <li>python311Packages.openaiauth</li>
    <li>python311Packages.openaiauth.dist</li>
    <li>shell-genie</li>
    <li>shell-genie.dist</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 228698` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>21 packages built:</summary>
  <ul>
    <li>chatblade</li>
    <li>chatblade.dist</li>
    <li>chatgpt-retrieval-plugin</li>
    <li>chatgpt-retrieval-plugin.dist</li>
    <li>checkov</li>
    <li>checkov.dist</li>
    <li>home-assistant-component-tests.openai_conversation</li>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>openai (python310Packages.openai)</li>
    <li>openai-full</li>
    <li>openai-full.dist</li>
    <li>openai.dist (python310Packages.openai.dist)</li>
    <li>python310Packages.openaiauth</li>
    <li>python310Packages.openaiauth.dist</li>
    <li>python311Packages.openai</li>
    <li>python311Packages.openai.dist</li>
    <li>python311Packages.openaiauth</li>
    <li>python311Packages.openaiauth.dist</li>
    <li>shell-genie</li>
    <li>shell-genie.dist</li>
  </ul>
</details>

**Comment by malob** [comment]
Result of `nixpkgs-review pr 228698` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>openai-full</li>
    <li>openai-full.dist</li>
  </ul>
</details>
<details>
  <summary>18 packages built:</summary>
  <ul>
    <li>chatblade</li>
    <li>chatblade.dist</li>
    <li>chatgpt-retrieval-plugin</li>
    <li>chatgpt-retrieval-plugin.dist</li>
    <li>checkov</li>
    <li>checkov.dist</li>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>openai (python310Packages.openai)</li>
    <li>openai.dist (python310Packages.openai.dist)</li>
    <li>python310Packages.openaiauth</li>
    <li>python310Packages.openaiauth.dist</li>
    <li>python311Packages.openai</li>
    <li>python311Packages.openai.dist</li>
    <li>python311Packages.openaiauth</li>
    <li>python311Packages.openaiauth.dist</li>
    <li>shell-genie</li>
    <li>shell-genie.dist</li>
  </ul>
</details>

**Comment by malob** [comment]
@ofborg build openai-full

**Pull request merged**
