### PR TITLE
Trinity on nixos

### PR DESCRIPTION
**Pull request by AndersonTorres**
###### Motivation for this change

Introduce the first steps to run Trinity Desktop Environment (TDE) on NixOS.
TDE is a fork of KDE 3.5 series, intended to be its logical continuation.

Initially, some "macros" and the TQt libs are described here.
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
Just as some background info. Trinity (TDE) is a fork of KDE 3.5. The last release of Trinity was on 2016.02.28. There is still some activity in the repo.

**Comment by AndersonTorres** [comment]
Here is the official git of TDE project:
http://mirror.git.trinitydesktop.org/cgit/tde/

**Comment by AndersonTorres** [comment]
It's a good idea to create a new branch on upstream nixpkgs?

**Comment by FRidh** [comment]
@AndersonTorres I don't see any reason for creating a branch.

**Comment by AndersonTorres** [comment]
@FRidh so far, so good. I will add the packages as far as I can.

**Comment by Mic92** [comment]
Is there anything left to do on this pull request?

**Comment by AndersonTorres** [comment]
A lot :/
There is at least tdelibs to compile - they are failing here.

**Comment by ocharles** [comment]
@AndersonTorres it sounds like this is still a work in progress. If so, I think it might be best to close this pull request and re-open it when the work is ready to be merged. What do you think about that?

**Comment by AndersonTorres** [comment]
My apologies about the delay responding, @ocharles .

Yes, I think it is better to close and re-open when I have something a bit more, eh, tangible to show. At least an Yakuake! 
Doing that one-man-show will consume more energy I initially supposed, and it's better not to soil the master branch with it.
Many thanks, anyway.

**Pull request closed without merging**
