### PR TITLE
twisted: 18.9.0 -> 19.7.0

### PR DESCRIPTION
**Pull request by exarkun**
###### Motivation for this change

https://github.com/twisted/twisted/blob/d07033a21c7d9146d14ded9d9f94fb4fafb0a4a8/NEWS.rst

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
since this causes 100+ rebuilds, do you mind rebasing this on top of staging and changing the branch to staging? :)

**Comment by exarkun** [comment]
Seems like a lot of tags.  Not sure I understand the workflow for the `staging` branch.

**Comment by jonringer** [comment]
@GrahamcOfBorg eval

**Comment by jonringer** [comment]
it's because rebasing will make it "seem" that you included all of what diverge in master a little bit until you change the base branch... :(

**Comment by jonringer** [comment]
@GrahamcOfBorg eval

**Comment by FRidh** [comment]
19.10 is in master

**Pull request closed without merging**
