### PR TITLE
pencil: v2.0.10 -> v2.0.11

### PR DESCRIPTION
**Pull request by prikhi**

### CODE REVIEW

**Comment by garbas** [comment]
@prikhi does this package builds for you? travis has some problems building it https://travis-ci.org/NixOS/nixpkgs/builds/64539672#L4560

**Comment by prikhi** [comment]
On Fri, May 29, 2015 at 01:58:37AM -0700, Rok Garbas wrote:
> @prikhi does this package builds for you? travis has some problems
> building it https://travis-ci.org/NixOS/nixpkgs/builds/64539672#L4560
Yup, both xulrunner 38.0.1 and pencil build fine for me...

**Comment by prikhi** [comment]
rebased & pushed. Still working fine for me locally

**Comment by garbas** [comment]
builds for me locally as well ... merged [here](http://git.io/vkiBp)

**Pull request closed without merging**
