### PR TITLE
qt5: 5.12.5 -> 5.12.6

### PR DESCRIPTION
**Pull request by dtzWill**
###### Motivation for this change

https://www.qt.io/blog/qt-5.12.6-released

Intended to be fixes only (safe), from language in the post.

Still building and testing, particularly the qtweb* beasts :).

So far so good...

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

(folks recently committing to these files, anyway..)

cc @ericson2314
cc @vcunat
cc @adisbladis
cc @ttuegel

### CODE REVIEW

**Comment by dtzWill** [comment]
Using this presently on my machines, FWIW! :)

**Review by Ericson2314 — APPROVED** [review]
Oh, I've only been fixing `set -u` errors with Qt lately, nothing creative, so ignore me :)

**Comment by dtzWill** [comment]
> Oh, I've only been fixing `set -u` errors with Qt lately, nothing creative, so ignore me :)

:heart_eyes_cat: for the `set -u` improvements! And oops I suppose i could have read the commit messages ;innocent:.

**Comment by petabyteboy** [comment]
This should probably make at least one patch unnecessary.

**Pull request merged**
