### PR TITLE
qt6.qtdeclarative: reduce closure size by removing reference to qtbase.dev

### PR DESCRIPTION
**Pull request by NickCao**
before: /nix/store/g7k03425nzhlwcldc85fyw4bly7bwk9a-qtdeclarative-6.3.2    1.7G
after:  /nix/store/x08j7c378j6a8i1vam4iqgk4lk6sqzm0-qtdeclarative-6.3.2  566.7M

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NickCao** [comment]
Result of `nixpkgs-review pr 192778` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>32 packages built:</summary>
  <ul>
    <li>beamerpresenter</li>
    <li>beamerpresenter-poppler</li>
    <li>cutemaze</li>
    <li>jami-client-qt</li>
    <li>mozillavpn</li>
    <li>qt6.qt3d</li>
    <li>qt6.qt5compat</li>
    <li>qt6.qtcharts</li>
    <li>qt6.qtconnectivity</li>
    <li>qt6.qtdatavis3d</li>
    <li>qt6.qtdeclarative</li>
    <li>qt6.qtdoc</li>
    <li>qt6.qtlottie</li>
    <li>qt6.qtmultimedia</li>
    <li>qt6.qtpositioning</li>
    <li>qt6.qtquick3d</li>
    <li>qt6.qtquicktimeline</li>
    <li>qt6.qtremoteobjects</li>
    <li>qt6.qtscxml</li>
    <li>qt6.qtsensors</li>
    <li>qt6.qttools</li>
    <li>qt6.qttranslations</li>
    <li>qt6.qtvirtualkeyboard</li>
    <li>qt6.qtwayland</li>
    <li>qt6.qtwebchannel</li>
    <li>qt6.qtwebengine</li>
    <li>qt6.qtwebsockets</li>
    <li>qt6.qtwebview</li>
    <li>qt6Packages.kcoreaddons</li>
    <li>qt6Packages.quazip</li>
    <li>tdesktop</li>
    <li>zint</li>
  </ul>
</details>

**Comment by NickCao** [comment]
An alternative fix would be:
```diff
diff --git a/pkgs/development/libraries/qt-6/hooks/qtbase-setup-hook.sh b/pkgs/development/libraries/qt-6/hooks/qtbase-setup-hook.sh
index 0ae969e8f8f..e03c80e230b 100644
--- a/pkgs/development/libraries/qt-6/hooks/qtbase-setup-hook.sh
+++ b/pkgs/development/libraries/qt-6/hooks/qtbase-setup-hook.sh
@@ -18,6 +18,9 @@ if [ -z "@debug@" ]; then
     NIX_CFLAGS_COMPILE="${NIX_CFLAGS_COMPILE-}${NIX_CFLAGS_COMPILE:+ }-DQT_NO_DEBUG"
 fi

+# remove references to qtbase.dev in __FILE__ macros
+NIX_CFLAGS_COMPILE="${NIX_CFLAGS_COMPILE-}${NIX_CFLAGS_COMPILE:+ }-fmacro-prefix-map=@dev@=qtbase.dev"
+
 # Integration with CMake:
 # Set the CMake build type corresponding to how qtbase was built.
 if [ -n "@debug@" ]; then
```
But I'm worried about the blast radius.

**Comment by NickCao** [comment]
For all the packages built in the nixpkgs-review session
```
mozillavpn
qt6.qtdoc
qt6.qtvirtualkeyboard
qt6Packages.quazip
```
Still have references to `qtbase.dev` from their `$out`

**Review by nrdxp — APPROVED** [review]
Looks fine to me :+1:

**Pull request merged**
