### PR TITLE
monero-gui: 2018-03-31 -> 0.12.0.0

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Motivation for this change
Use official release

###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build monero-gui

**Comment by Mic92** [comment]
@GrahamcOfBorg build monero-gui

**Comment by Mic92** [comment]
@GrahamcOfBorg build monero-gui

**Comment by Mic92** [comment]
@LnL7 which attribute contains the PCSC framework?

**Comment by Mic92** [comment]
OK. So monero seems to be fixed.

**Comment by LnL7** [comment]
@Mic92 ^ it's in darwin.frameworks

**Review by LnL7 — APPROVED** [review]

**Comment by rnhmjoj** [comment]
Thank you both for the help!

**Pull request merged**
