### PR TITLE
luajit_2_0, luajit_2_1: 2.1.0-2020-03-20 -> 2.1.0-2020-08-05

### PR DESCRIPTION
**Pull request by lblasc**
###### Motivation for this change

2.0 changes: https://github.com/LuaJIT/LuaJIT/compare/e613105..2211f6f
Mostly bugfixes.

2.1 changes: https://github.com/LuaJIT/LuaJIT/compare/9143e86..10ddae7
Lot of bugfixes, optimizations and modernization. For me the most interesting commits:
*  https://github.com/LuaJIT/LuaJIT/commit/1a4ff1311740aa6c85f7a9101b6aa9bfaafa3f8e (Optimize table length computation with hinting.)
* https://github.com/LuaJIT/LuaJIT/commit/a44f53acf53603e7d9b88352de035b1804be4e88 (Use a securely seeded global PRNG for the VM.)
* https://github.com/LuaJIT/LuaJIT/commit/ff34b48ddd6f2b3bdd26d6088662a214ba6b0288 (Redesign and harden string interning.)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by teto — APPROVED** [review]

**Comment by teto** [comment]
@GrahamcOfBorg build neovim luajitPackages.lpeg

**Comment by teto** [comment]
also a partial nixpkgs-review gives
```
error: --- Error --- nix-daemon
builder for '/nix/store/6d9svxq7fdh008g25ly3gxhksqv6q1k3-luajit-2.1.0-2020-08-05-ltermbox-0.2-1.drv' failed with exit code 1; last 10 log lines:
    106 | static const struct luaL_reg lt_buffer_metatable[] = {
        |                              ^~~~~~~~~~~~~~~~~~~
  lua/ltermbox.c:195:30: error: array type has incomplete element type 'struct luaL_reg'
    195 | static const struct luaL_reg ltermbox[] = {
        |                              ^~~~~~~~
  lua/ltermbox.c:213:12: warning: return type defaults to 'int' [-Wimplicit-int]
    213 | LUALIB_API luaopen_ltermbox(lua_State *L) {
        |            ^~~~~~~~~~~~~~~~
  
  Error: Build error: Failed compiling object lua/ltermbox.o
note: keeping build directory '/tmp/nix-build-luajit-2.1.0-2020-08-05-luaexpat-1.3.0-1.drv-0'
error: --- Error --- nix-daemon
builder for '/nix/store/fbidsmb2sp9vsh3xlgq7q32p14warijr-luajit-2.1.0-2020-08-05-luaexpat-1.3.0-1.drv' failed with exit code 1; last 10 log lines:
  gcc -O2 -fPIC -I/nix/store/wbr4wh47z6vscz2d6a6yii9x9vnls8d4-luajit-2.1.0-2020-08-05/include/luajit-2.1 -c src/lxplib.c -o src/lxplib.o -I/nix/store/kqhd4kk5cgaj37xcswdmmfygpvww65ms-expat-2.2.8-dev/include -Isrc/
  src/lxplib.c:593:13: error: static declaration of 'luaL_setfuncs' follows non-static declaration
    593 | static void luaL_setfuncs (lua_State *L, const luaL_Reg *l, int nup) {
        |             ^~~~~~~~~~~~~
  In file included from src/lxplib.c:15:
  /nix/store/wbr4wh47z6vscz2d6a6yii9x9vnls8d4-luajit-2.1.0-2020-08-05/include/luajit-2.1/lauxlib.h:88:18: note: previous declaration of 'luaL_setfuncs' was here
     88 | LUALIB_API void (luaL_setfuncs) (lua_State *L, const luaL_Reg *l, int nup);
        |                  ^~~~~~~~~~~~~
  
  Error: Build error: Failed compiling object src/lxplib.o
note: keeping build directory '/tmp/nix-build-luajit-2.1.0-2020-08-05-luaffi-scm-1.drv-0'
error: --- Error --- nix-daemon
builder for '/nix/store/zsp5znkj605ib6dyr5r8qn0izbshx9pl-luajit-2.1.0-2020-08-05-luaffi-scm-1.drv' failed with exit code 1; last 10 log lines:
  ffi.h:88:13: error: static declaration of 'luaL_setfuncs' follows non-static declaration
     88 | static void luaL_setfuncs (lua_State *L, const luaL_Reg *l, int nup) {
        |             ^~~~~~~~~~~~~
  In file included from ffi.h:31,
                   from call.c:9:
  /nix/store/wbr4wh47z6vscz2d6a6yii9x9vnls8d4-luajit-2.1.0-2020-08-05/include/luajit-2.1/lauxlib.h:88:18: note: previous declaration of 'luaL_setfuncs' was here
     88 | LUALIB_API void (luaL_setfuncs) (lua_State *L, const luaL_Reg *l, int nup);
        |                  ^~~~~~~~~~~~~
  
  Error: Build error: Failed compiling object call.o
note: keeping build directory '/tmp/nix-build-luajit-2.1.0-2020-08-05-digestif-0.2-1.drv-0'
error: --- Error --- nix-daemon
builder for '/nix/store/44g3f848il1r8kks2vl70s2dfd8wkcs8-luajit-2.1.0-2020-08-05-digestif-0.2-1.drv' failed with exit code 1; last 10 log lines:
  patching sources
  configuring
  building
  installing
  Missing dependencies for digestif 0.2-1:
     lua >= 5.3 (5.1-1 provided by VM)
  
  digestif 0.2-1 depends on lua >= 5.3 (5.1-1 provided by VM)
```

**Comment by lblasc** [comment]
nixpkgs-review gives:
```
9 packages failed to build:
gimpPlugins.focusblur gimpPlugins.texturize hawkthorne love_0_9 luajitPackages.digestif luajitPackages.ltermbox luajitPackages.luaexpat luajitPackages.luaffi obs-ndi
```

Most of them are marked broken (I'm not sure why nixpkgs-review is trying to build them) and some failures are not related to this update, except `luajitPackages.luaexpat` which was failing before this update (I've patched it and opened the pull request https://github.com/silverwind/luaexpat/pull/1).

**Comment by teto** [comment]
digestif should not be tried either as it requires lua >= 5.3 . weird. May look into it later. Feel free to merge.

**Comment by lblasc** [comment]
@teto thx for looking into this, I don't gave merge right. pinging @vcunat

**Comment by teto** [comment]
@GrahamcOfBorg build neovim luajitPackages.lpeg

**Review by vcunat — APPROVED** [review]
Seems OK.

I now switched my dev-env to this `2.1.0-2020-08-05`.  I'd probably still wait with merging a couple more days, so other people have a chance to react.

**Pull request merged**
