### PR TITLE
staging-next-23.11 iteration 3 - 2024-01-26

### PR DESCRIPTION
**Pull request by vcunat**
- workflow docs: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#staging
- important job: https://hydra.nixos.org/job/nixpkgs/staging-next-23.11/unstable#tabs-constituents
- jobsets:
  https://hydra.nixos.org/jobset/nixpkgs/staging-next-23.11
  https://hydra.nixos.org/jobset/nixos/staging-next-23.11-small
- nix-review reports: https://malob.github.io/nix-review-tools-reports/
- previous staging-next-23.11 PR: https://github.com/NixOS/nixpkgs/pull/279139
- - - 
##### Significant breakages
(will be edited based on progress)

### CODE REVIEW

**Comment by veprbl** [comment]
This fixes an important regression on darwin (#278945), would be nice to get this in asap.

**Comment by vcunat** [comment]
Hydra's been busy about this.  I expect the rebuilding will take a couple more days, and then we'll see if we avoided any significant regressions.

**Comment by veprbl** [comment]
Looks good?

**Comment by vcunat** [comment]
13k builds not finished yet, but so far I've seen no blocker.

**Comment by bjornfor** [comment]
> 13k builds not finished yet, but so far I've seen no blocker.

Yesterday it was only 1500 builds. Do we graph the remaining builds over time somewhere? :smile:

**Comment by vcunat** [comment]
I'm not aware of such graphs.  At some point it might've been around that low, but there were many thousands of transitive failures due to some transient issues.

**Comment by vcunat** [comment]
I think it should be OK now.

**Comment by bjornfor** [comment]
Yay! Now just waiting for it to hit the channel: https://nixpk.gs/pr-tracker.html?pr=284049

**Pull request merged**
