### PR TITLE
llvm: add 3.8.0 release

### PR DESCRIPTION
**Pull request by andrewrk**
###### Things done:
- [x] Built on platform(s): NixOS / Linux
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
- [x] Update [zig compiler](https://github.com/andrewrk/zig) to llvm 3.8.0 and build it with clang 3.8.0 and all tests pass.
###### More

See also #12759 

cc @lovek323 @viric @7c6f434c

### CODE REVIEW

**Comment by andrewrk** [comment]
cc @vcunat

**Comment by joachifm** [comment]
Am I reading this correctly that you're changing the default llvm version? Won't that cause a lot of rebuilds? If so, this should probably be filed against `staging`.

**Comment by andrewrk** [comment]
Hmm I think you're right. I incorrectly assumed that packages would specify which version of llvm they depended on explicitly.

**Comment by joachifm** [comment]
Some do pin the version. I could be overestimating the number of revdeps, just something to keep in mind.

**Comment by globin** [comment]
I'd reckon this is a mass-rebuild

**Comment by andrewrk** [comment]
Alright closing this PR, I (or someone else) needs to reopen against staging, and probably run some regression tests.

**Comment by joachifm** [comment]
@andrewrk Please do re-open against staging. Surely, this PR must be a good place to start.

**Comment by andrewrk** [comment]
Rebased against staging here: #13801

**Pull request closed without merging**
