### PR TITLE
zed-editor: 0.130.7 -> 0.131.6

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Changelog: https://github.com/zed-industries/zed/releases/tag/v0.131.6

cc @jansol @niklaskorz 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 304907` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 304907` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

**Review by jansol — COMMENTED** [review]
Works but is *extremely* sluggish for me on Plasma 6 / Wayland

**Comment by PoSayDone** [comment]
how about binaries downloaded by zed itself? should they not work for now? I have an error about nix-ld not being configured, but it is configured and manually running the binaries works.

error:
```
stderr: "cannot execute /home/posaydone/.config/zed/node/node-v18.15.0-linux-x64/bin/node: You are trying to run an unpatched binary on nixos, but you have not configured NIX_LD or NIX_LD_x86_64-linux. See https://github.com/Mic92/nix-ld for more details\n"
```

**Comment by jansol** [comment]
> how about binaries downloaded by zed itself? should they not work for now? I have an error about nix-ld not being configured, but it is configured and manually running the binaries works.

I don't think anyone has really looked into those. I have overridden all language servers with paths to manually installed ones in my config. But yes, they mostly do not work (a few standalone static binaries happen to work, such as taplo).

**Comment by PoSayDone** [comment]
> I don't think anyone has really looked into those. I have overridden all language servers with paths to manually installed ones in my config. But yes, they mostly do not work (a few standalone static binaries happen to work, such as taplo).

can you please share how you did it?

**Comment by jansol** [comment]
```json
 "lsp": {
    "bash-language-server": {
      "binary": { // The lazy version - simply copy the output of `which bash-language-server` + necessary arguments
        "path": "/etc/profiles/per-user/myself/bin/bash-language-server",
        "arguments": ["start"]
      }
    "clangd": {
      "binary": { // This way external dependencies get resolved correctly in projects with a flake.nix
        "path": "/run/current-system/sw/bin/nix",
        "arguments": ["develop", "--command", "clangd"]
      }
    },
    ...
  }
```
(note that bash-language-server is sadly not actually supported by any extension yet)

**Review by jansol — APPROVED** [review]
Hm, I can see the same slowdowns on the previous stable release so it seems that is not a regression after all. Let's just move forward with this.

**Review by niklaskorz — APPROVED** [review]

**Pull request merged**
