### PR TITLE
cctools: bump to latest commit

### PR DESCRIPTION
**Pull request by matthewbauer**
Lots of our patches are no longer needed. This simplifies things a
bunch. In addition, it now includes man pages.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by LnL7** [comment]
Nice, I was also thinking about doing this. Do you know if this fixes nm on 10.14?

```
$ nm /usr/lib/libSystem.B.dylib
nm: for architecture x86_64 object: /usr/lib/libSystem.B.dylib malformed object (unknown load command 8)
```

**Comment by matthewbauer** [comment]
No, we'll need to apple to release the new tools for that.

https://github.com/tpoechtrager/cctools-port/issues/60

**Comment by Ericson2314** [comment]
For iOS we sadly need the old version until either https://lists.llvm.org/pipermail/llvm-dev/2017-September/117264.html is done or we package Apple's LLVM fork. CC @kmicklas. There are some more recent responses to this post in August.

**Comment by matthewbauer** [comment]
Oops! I thought we fixed that one. Have you seen this:

https://github.com/tpoechtrager/apple-libtapi

?

**Comment by Ericson2314** [comment]
Doesn't that still contain much vendored LLVM?

**Pull request merged**
