### PR TITLE
backport borgbackup 1.1.4 for release-17.09

### PR DESCRIPTION
**Pull request by flokli**
###### Motivation for this change
See #33053

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
@GrahamcOfBorg build borgbackup

**Comment by fpletz** [comment]
Please use `git cherry-pick -x` to retain a reference to the commit you cherry-picked.

**Comment by flokli** [comment]
Good point, thanks!

Re-cherry-picked the `openblas` and the `guzzle_sphinx_theme` commits.

The borgbackup commits are a bit trickier, as the changes are a combination from multiple commits (borgbackup itself), or the referenced commit did more (remove nckx from more than borgbackup). What do you want me to do there?

Additionally, I tried building borgbackup on the aarch64 machine, but this fails at [`python3.6-cffi`](https://clbin.com/YtufH). Most likely this was already broken, but maybe someone could take a look?

**Comment by Mic92** [comment]
I have now also a nixos test for it: https://github.com/NixOS/nixpkgs/pull/33315

**Comment by flokli** [comment]
@Mic92 right, thanks! Cherry-picked and tested your test, feel free to merge :-)

**Pull request merged**
