### PR TITLE
cpputest: 3.7.2 -> 3.8

### PR DESCRIPTION
**Pull request by rasendubi**
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [x] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
cc maintainer @juliendehos

**Comment by rasendubi** [comment]
Travis failure is really strange. I've retested the package on Linux, tested on NixOS and ran nox-review -- everything builds fine.

**Comment by joachifm** [comment]
@rasendubi travis is a bit useless at the moment

**Comment by juliendehos** [comment]
I don't understand the Travis failure either. This update is ok on my machine (nixos).

**Comment by rasendubi** [comment]
@joachifm, @juliendehos, can this be merged then?

**Pull request merged**
