### PR TITLE
WIP: calcure: init at 1.7

### PR DESCRIPTION
**Pull request by tgharib**
###### Motivation for this change

Add `calcure` software package. The reason this PR is WIP is because I'm waiting for the next tagged release (v1.7). v1.6 and earlier do not have `setup.py` which are necessary to properly build the package.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by max-niederman** [comment]
Result of `nixpkgs-review pr 156003` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>calcure</li>
  </ul>
</details>

**Comment by max-niederman** [comment]
The executable is functional for me at least. LGTM so far.

**Comment by tgharib** [comment]
@max-niederman This PR is ready since the 1.7 tag has been released.

**Review by max-niederman — APPROVED** [review]
Functions perfectly and the package looks good.
My only suggestion is that you may want to put the `with python3.pkgs` right before the list of build inputs or remove it entirely since it's easy to be confused where `holidays` is coming from.

**Comment by tgharib** [comment]
@max-niederman Fixed

**Comment by max-niederman** [comment]
> @max-niederman Fixed

Just in case you don't know, I don't have commit permissions so you will have to get approval from a Nixpkgs commiter.

**Pull request closed without merging**
