### PR TITLE
 thunderbird, thunderbird-bin: 68.4.1 -> 68.4.2

### PR DESCRIPTION
**Pull request by taku0**
###### Motivation for this change

- Various security fixes
- Other fixes and changes.

https://www.thunderbird.net/en-US/thunderbird/68.4.2/releasenotes/

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
The security part is weird.  It's linked but there's nothing listed for this release.

**Review by vcunat — APPROVED** [review]
Both seem to work OK for me.

**Comment by vcunat** [comment]
I had backported it to stable but later [it turned out](https://github.com/thundernest/thunderbird-website/issues/163#issuecomment-578401041) that no security fixes were present in this bump.

**Comment by taku0** [comment]
The early version of the release notes mentioned “Various security fixes”, but corresponding Security Advisories did not exist.

**Pull request merged**
