### PR TITLE
yubikey-agent: fix on darwin

### PR DESCRIPTION
**Pull request by philandstuff**
Mea culpa: in #92936, I did originally test on macOS but I forgot to
retest after adding the piv-go patch.  Unfortunately, the piv-go patch
is broken on macOS (but fortunately it is unnecessary).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by rawkode — APPROVED** [review]

**Comment by flokli** [comment]
Could you instead replace go-piv with https://github.com/go-piv/piv-go/commit/80327675dc86ebe3c494f9cd6fe5dee3eec5bf4c (latest iteration of the PR? That should remove all sort of darwin-conditional code.

**Comment by philandstuff** [comment]
I tried writing `postPatch = "go mod edit -replace=github.com/go-piv/piv-go=github.com/rawkode/piv-go@80327675dc86ebe3c494f9cd6fe5dee3eec5bf4c"`, which should work, but the go binary gets confused about where to put cache stuff, and the go-modules derivation didn't inherit the patch.  There really ought to be a nicer way of inserting `replace` directives in `buildGoModule` than writing a patch file for go.mod 😞

**Comment by philandstuff** [comment]
@flokli @rawkode unfortunately the conditional is still needed.  I tried compiling latest go-piv/piv-go#75 unconditionally on darwin and got:

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/slyckbirmqymy0yj4cy27r21j8v2lmg8-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
applying patch /nix/store/ggq7300zpz3js06xyfq5hkfppq8zg9xd-use-piv-go-75.patch
patching file go.mod
patching file go.sum
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
@nix { "action": "setPhase", "phase": "buildPhase" }
building
Building subPackage ./.
github.com/go-piv/piv-go/piv
# pkg-config --cflags  -- libpcsclite
Package libpcsclite was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpcsclite.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libpcsclite' found
pkg-config: exit status 1
```

it looks like the `pkg-config` lines are *not* harmless on distros that don't support pkg-config 😞

**Comment by philandstuff** [comment]
@flokli @rawkode I've updated this PR to pull in the latest go-piv/piv-go#75, now that that has been fixed.  This allowed me to remove the conditional.  I've tested locally on NixOS and macOS and both compile successfully.

Please re-review.

**Comment by philandstuff** [comment]
urgh, my git fu is broken here :( seems I pushed a weird commit somehow which broke everything.  Apologies for the mass notification :disappointed: 

I'll open a new PR once I've worked out what I'm doing again.

**Pull request closed without merging**
