### PR TITLE
profanity: 0.5.1 -> 0.6.0

### PR DESCRIPTION
**Pull request by eri451**
###### Motivation for this change

I noticed the [announcement of the profanity.im release version 0.6.0](https://github.com/boothj5/profanity/releases/tag/0.6.0)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by c0bw3b** [comment]
@GrahamcOfBorg build profanity

**Comment by c0bw3b** [comment]
Build failure on Darwin. I guess the `packages-osx` patch is still needed?

**Comment by eri451** [comment]
I am also unsure about the osx-patch. I asked on the irc what to do since I cannot build the package with the patch. I was told to leave it out.
Do I need a Mac to test this?

**Comment by c0bw3b** [comment]
@GrahamcOfBorg build profanity

**Comment by c0bw3b** [comment]
@eri451 ideally yes, or ask around on IRC if a Darwin user is willing to do the test

I refreshed the Darwin patch for v0.6.0 sources so it is no longer a blocker.
The bot Darwin build wasn't complete only because it took to much time building gpgme

**Comment by eri451** [comment]
thank you

**Pull request merged**
