### PR TITLE
quarto: added platforms.all

### PR DESCRIPTION
**Pull request by b-rodrigues**
## Description of changes

quarto: added platforms.all

Second attempt at this. I mistakenly erased the branch on which I was working for https://github.com/NixOS/nixpkgs/pull/258043 which closed the PR. 

## Things done

I've added more platforms so that quarto now builds for x86_64-linux, x86_64-darwin, aarch64-linux and aarch64-darwin. 
The same tarball gets used for all platforms, so there was no need to change that. 

I built the package on x86_64-linux, x86_64-darwin and aarch64-linux and was able to run the checks using `quarto check`. I did not personally test it on aarch64-darwin, but  @sagikazarmark has been running it successfully for quite some time now on his own fork. 

I tried to follow contributing.md as much as possible, hope I didn't miss anything this time!

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kupac** [comment]
there are two `runhook preInstall`-s, the 2nd one should be `runhook postInstall`

**Comment by Kupac** [comment]
the nested `with` statements are discouraged. in the meta section, the `with lib;` can be removed, and  the later `with`-s can be extended, like `with lib.maintainers`, etc

**Review by minijackson — APPROVED** [review]
Sorry for the delay, I think this is good, thanks!

For the nested `with`, I think this can be done in another PR, no need to block this one.

**Comment by minijackson** [comment]
@wegank out of curiosity, why was `sysctl` needed for `quarto check` on darwin?

**Comment by wegank** [comment]
@minijackson see https://github.com/quarto-dev/quarto-cli/blob/a7460069020770d3c9e94a34e7600febdf089e1d/package/scripts/common/quarto#L126-L129.

**Pull request merged**
