### PR TITLE
code-server: 4.16.1 -> 4.18.0

### PR DESCRIPTION
**Pull request by henkery**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by henkery** [comment]
@code-asher hi, for some reason no matter how hard I try the `yarn release` command at the end wants to download a package from the outside world breaking the build.
do you know how I could suppress that behaviour?

**Comment by code-asher** [comment]
Sorry for the delayed response, I have been out for a few weeks and am just now catching up.

Is that log from `yarn release`?  It seems to be running the post-install script which I think is only supposed to happen from a `yarn install`.  Unless...`yarn release` does run `npm shrinkwrap`, maybe that triggers the post-install script?

The post-install script runs `yarn install` so maybe we need to pass through the `--offline` flag to those invocations.  VS Code itself also runs a bunch of `yarn install` commands so those might need to be patched as well?

Or, if it is from the `npm shrinkwrap`, that whole thing can probably be omitted.  We only need it for publishing the NPM package.

**Comment by code-asher** [comment]
`@microsoft/1ds-core-js` is supposedly already specified in the package.json by the way, or at least I do see it in `lib/vscode/remote/package.json` which is the one we use.

**Comment by henkery** [comment]
This is indeed caused by running `yarn release` 
passing `--offline` to that doesn't seem to change much so I will check if in any post-install scripts there are any `yarn install`'s that need patching

**Comment by wegank** [comment]
Closed by #275429.

**Pull request closed without merging**
