### PR TITLE
jbig2dec: update & security patch

### PR DESCRIPTION
**Pull request by joachifm**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/issues/22342

I've yet to do any testing beyond building the library itself.

### CODE REVIEW

**Comment by joachifm** [comment]
Successfully built these revdeps
- ghostscript
- llp
- mupdf
- k2pdfopt

**Comment by grahamc** [comment]
I accidentally committed these changes to master, then undid them. Running a nox-review to see what it looks like.

**Comment by joachifm** [comment]
jfbview was already broken: https://hydra.nixos.org/build/47713584

**Comment by grahamc** [comment]
Impacted:

`python27Packages.basemap texlive.combined.scheme-full samsung-unified-linux-driver ipe frescobaldi gimpPlugins.resynthesizer2 python35Packages.scikitimage ocamlPackages.camlimages gimpPlugins.waveletSharpen python27Packages.nipy python35Packages.tqdm darktable enlightenment.efl python35Packages.librosa gv python27Packages.qutip python35Packages.qutip gimp-with-plugins gimpPlugins.gimplensfun gimpPlugins.gmic kde4.cantor python35Packages.pythonefl python27Packages.tqdm jbig2dec python27Packages.seaborn python27Packages.acoustics recoll python35Packages.tqdm4 yoda pdf2odt sherpa djvu2pdf pytrainer kde4.calligra ghostscriptX gnuradio photoqt srecord evince texmacs xpdf fastnlo gimpPlugins.fourier gimpPlugins.ufraw python27Packages.moviepy anki winswitch python35Packages.acoustics python27Packages.rootpy gnuradio-with-packages python27Packages.udiskie enlightenment.econnman texlive.combined.scheme-medium qpdfview canon-cups-ufr2 pumpio gnuradio-gsm gnome3.gnome-documents python27Packages.librosa octaveFull gimpPlugins.focusblur gimpPlugins.resynthesizer ne imagemagickBig graphicsmagick gajim kde4.kdegraphics python35Packages.matplotlib graphicsmagick_q16 solfege python35Packages.udiskie freecad python35Packages.nipy python27Packages.spyder enlightenment.terminology mfcj470dw-cupswrapper rivet python27Packages.graph-tool kde5.okular udiskie python35Packages.magic-wormhole k2pdfopt kde4.okular kde4.kdeedu python27Packages.neuronpy mupdf python27Packages.joblib casperjs python35Packages.moviepy mcgrid python27Packages.lightning python35Packages.numpydoc i3-gaps python35Packages.seaborn thepeg xpra python27Packages.magic-wormhole gnuradio-ais python35Packages.py3status mfcj6510dw-cupswrapper ocamlPackages.camlimages_4_0 foo2zjs pitivi ib-controller asymptote brgenml1cupswrapper libspectre ikiwiki teensyduino zbar mfcj6510dwlpr xournal i3 pdfdiff auctex lilypond xpraGtk3 gqrx xvfb_run vimiv asciidoc-full-with-plugins backblaze-b2 gimpPlugins.gap kde4.kdegraphics_mobipocket photivo gnuradio-nacl python27Packages.oger python35Packages.Pweave flpsed gimpPlugins.lqrPlugin disorderfs mnemosyne python27Packages.tqdm4 impressive wt herwig jfbview python27Packages.nilearn python27Packages.statsmodels python35Packages.oger zathura python27Packages.matplotlib python35Packages.joblib python35Packages.statsmodels gnuradio-osmosdr python27Packages.Pweave gimpPlugins.texturize jfbpdf ocropus brgenml1lpr python27Packages.pythonefl python27Packages.py3status python27Packages.numpydoc enlightenment.enlightenment asciidoc-full python27Packages.scikitimage lout gnuradio-rds gnome3.sushi pdfread gimp mfcj470dwlpr python35Packages.basemap inspectrum enlightenment.rage ghostscript imagemagick7Big dblatexFull paperwork pstoedit llpp`

**Comment by joachifm** [comment]
It doesn't seem likely that indirect revdeps will be affected, at least not in terms of API incompatibilities (if there are any), given the nature of the library, but let's see what happens.

**Comment by joachifm** [comment]
I've amended the commit message; the Red Hat link didn't provide much additional info, I think.

**Comment by grahamc** [comment]
I'm heading to bed, and will leave the build running overnight. If you feel confident, feel free to merge & backport :) if not, I'll report in ~8hrs.

**Comment by grahamc** [comment]
ok, well, it ran all night and still didn't finish. I say we merge, and if it breaks a bunch of stuff we can revert.

**Pull request merged**
