### PR TITLE
vscode-extensions.ms-python.python: 2019.6.22090 -> 2019.6.24221

### PR DESCRIPTION
**Pull request by eadwu**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by teto** [comment]
just wondering ? do you use this with coc.nvim ? or with vscode only ?

**Review by worldofpeace — CHANGES_REQUESTED** [review]
I think you need to update the language server also, as the following expression fails to build for me
```nix
with import ./. {};

let

  test-vscode = (pkgs.vscode-with-extensions.override {
    vscodeExtensions = with pkgs.vscode-extensions; [
      ms-python.python
    ];
  });

in test-vscode
```

```
curl: (22) The requested URL returned error: 404
error: cannot download Python-Language-Server-linux-x64.0.2.82.nupkg from any mirror
```

**Comment by eadwu** [comment]
There goes `The languageServerVersion in our package.json always specifies the latest stable release version` [1].

[1] https://github.com/Microsoft/vscode-python/issues/3977

**Review by worldofpeace — APPROVED** [review]
LGTM, builds, doesn't explode when I view a python project.

**Pull request merged**
