### PR TITLE
nixos/nextcloud: Init

### PR DESCRIPTION
**Pull request by dasJ**
###### Motivation for this change

I'm using NextCloud and I'd prefer to have it packaged as a module and located in the nix store.

I hope this PR isn't too bad, it's the largest PR that I have done in this repo.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by dasJ** [comment]
Oh, before anyone asks: I put some location blocks into `extraConfig`. I did that because their order matters and I didn't see another way to enforce their order.

**Comment by flokli** [comment]
@dasJ Can you please also have a look at #44994, and on how much functionality is shared?

**Comment by globin** [comment]
Most of the functionality is similar, #44994 is a bit cleaner in a few ways:
 * adds nginx location priority in order not have to specify locations in extraConfig
 * adds an autoconfig.php for initial setup

This PR OTOH adds a few more options for caching, I'll try to add them to #44994. Sorry for not seeing this earlier and causing duplicate work.

**Comment by globin** [comment]
Improvements of this PR have been added to #44994

**Comment by flokli** [comment]
@Mic92 this can be closed, as it was incorporated into #44839, which was continued in #47159.

**Pull request closed without merging**
