### PR TITLE
Added dependency to gnome-music. Can't start without gnome3.tracker

### PR DESCRIPTION
**Pull request by l-margiela**

### CODE REVIEW

**Comment by jagajaga** [comment]
Please rename commit's name following our guide from `CONTRIBUTING.md`.

**Comment by domenkozar** [comment]
cc @lethalman

**Comment by lethalman** [comment]
Sorry? It's already in build inputs, it's `tracker` and you added next to it `gnome3.tracker`. What's the difference?

**Comment by geerds** [comment]
`tracker` should be enabled if you not explicitly disabled it: `services.gnome3.tracker.enable = mkDefault true;`

**Comment by lethalman** [comment]
Is this still a problem for you? Does adding that `gnome3.tracker` to buildInputs really solves your problem? Would you please provide some more information... like logs or errors of any kind.

**Comment by lethalman** [comment]
This cannot be merged. Also is the issue still current?

**Comment by NicolasPetton** [comment]
@lethalman gnome-music works fine here without this commit. Should this issue be closed?

**Comment by bjornfor** [comment]
Closing due to @NicolasPetton saying it works now (previous comment). (Also, no response from OP/@xaxes in months.)

**Pull request closed without merging**
