### PR TITLE
caddy: 2.6.4 -> 2.7.2

### PR DESCRIPTION
**Pull request by techknowlogick**
Diff: https://github.com/caddyserver/caddy/compare/v2.6.4...v2.7.0

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by emilylange** [comment]
I'll mark this as draft until https://github.com/caddyserver/caddy/issues/5671 is resolved and the fix released.
Thank you

**Comment by techknowlogick** [comment]
Thanks @emilylange :) I've just pushed the patched release of caddy.

**Comment by happysalada** [comment]
ofborg seems to be failing with
```
 > (finished: must succeed: curl --fail -v 'http://localhost/example.html' 2>&1 | sed -n -e "s/^< [Ee][Tt][Aa][Gg]: *//p", in 0.05 seconds)
       > webserver: must succeed: curl --fail --silent --show-error -o /dev/null -w "%{http_code}" --head -H 'If-None-Match: ' http://localhost/example.html
       > (finished: must succeed: curl --fail --silent --show-error -o /dev/null -w "%{http_code}" --head -H 'If-None-Match: ' http://localhost/example.html, in 0.02 seconds)
       > Test "check ETag if serving Nix store paths" failed with error: "HTTP code is 200, expected 304"
       > cleanup
       > kill machine (pid 8)
       > webserver # qemu-kvm: terminating on signal 15 from pid 6 (/nix/store/jhflvwr40xbb0xr6jx4311icp9cym1fp-python3-3.10.12/bin/python3.10)
       > (finished: cleanup, in 0.02 seconds)
       > kill vlan (pid 7)
       For full logs, run 'nix log /nix/store/j2p46rvjq0xyx4cnid13qbggsvrv0smc-vm-test-run-caddy.drv'.
```

I'm not the one who wrote that test, I just saw this and thought outlining it might help.

**Comment by fin444** [comment]
Caddy 2.7.2 has been released ([diff](https://github.com/caddyserver/caddy/compare/v2.7.1...v2.7.2))

Seems like 2.7 is having a bit of a rocky launch, may be best to hold off updating for a bit until it stabilizes.

**Comment by emilylange** [comment]
The VM test fails because Caddy no longer emits an `etag` for files with unix time `0` or `1`, specifically implemented for nix environments.

See https://github.com/caddyserver/caddy/pull/5550, https://github.com/caddyserver/caddy/pull/5547 and https://github.com/NixOS/nixpkgs/pull/222354

I'd argue in favor of removing our `etag` subtest for now, and I'll try (no promises though) to reimplement it, including a test for the new `etag` override, some time in the future.

**Comment by happysalada** [comment]
Happy to remove it for now.

**Comment by fin444** [comment]
Caddy 2.7.3 has been released ([diff](https://github.com/caddyserver/caddy/compare/v2.7.2...v2.7.3))

**Comment by techknowlogick** [comment]
Closing in favour of @emilylange's updated PR

**Pull request closed without merging**
