### PR TITLE
far2l: 2017-10-08 -> 2018-02-27

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

minor bug fixes

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build far2l

**Comment by Mic92** [comment]
Maybe this does not like clang or libc++ on darwin. If it did not work before, it should be disabled there.

**Comment by volth** [comment]
It worked on darwin few months ago

**Comment by volth** [comment]
Maybe it needs an older clang, I do not know.

**Comment by volth** [comment]
```aarch64-linux``` worked too

**Comment by Mic92** [comment]
aarch64 is currently broken on master.

**Comment by volth** [comment]
darwin should be fixed in https://github.com/NixOS/nixpkgs/commit/879f144d7fb4d49cf2afacbc4e84e045d519c792

**Pull request merged**
