### PR TITLE
maintainers: remove delroth

### PR DESCRIPTION
**Pull request by delroth**
## Description of changes

It's been fun, until the lack of proper, decisive moderation finally became a problem. Maybe if the right people had been banned a month ago I'd be sending a different PR today...

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Mindavi** [comment]
Thanks for your services.

**Review by Mindavi — APPROVED** [review]

**Comment by adingbatponder** [comment]
Cheers. So long and thanks for all the bash!

**Comment by hraban** [comment]
!! Thanks for all your work on infra and your insightful posts on discourse, @delroth! You will be missed.

**Comment by delroth** [comment]
> !! Thanks for all your work on infra and your insightful posts on discourse, @delroth! You will be missed.

Thank me by going and telling the srid/jonringer brigade to fuck off from this project instead.

**Pull request merged**
