### PR TITLE
tarball: backport nixos-search's subsets for JSON generation

### PR DESCRIPTION
**Pull request by Atemu**
###### Motivation for this change

Progress towards https://github.com/NixOS/nixpkgs/issues/102508

More limited scope than https://github.com/NixOS/nixpkgs/pull/102509

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Is this going to influence the speed of the bash-completion script when doing nix-build -A <kbd>Tab</kbd>?

**Comment by edolstra** [comment]
@SuperSandro2000 The evaluation cache in Nix master speeds up tab completion, e.g. `nix build nixpkgs#firef<tab>`.

**Comment by Atemu** [comment]
I don't think this would affect bash completion for `nix-build -A` at all as that simply evaluates the specified Nix file itself.

AFAICT, this file is only used in the build script of `pkgs/top-level/make-tarball.nix` and the only user of this expression's output I know of is Repology.  

`nix search` might be using it but it's pretty fast and the amount of packages in the JSON "only" increased by ~13%; if something were to use it, the slowdown would not be all that significant.

**Comment by lukegb** [comment]
A few questions:

* How was the list generated - I'm assuming by just looking for dontRecurseIntoAttrs in top-level/all-packages.nix - and can we add a comment indicating how to regenerate it if need be? (I guess that new packagesets like this aren't added particularly frequently)
* Does it matter if e.g. nodePackages and nodePackages_latest are both present (and emacs{26,27}Packages)? Do we need both (I assume yes because some packages might be disabled under older/newer versions of their respective runtime)?

**Comment by Atemu** [comment]
> How was the list generated

I don't think it was generated. It looks like it was picked out manually.

If we add another larger subset of packages, we should just manually update the list. That's a rare enough of an occurance to not cause too much trouble I think.

> Does it matter if e.g. nodePackages and nodePackages_latest are both present

For Repology, it doesn't matter. They take care of duplicates etc.

I don't know whether there are other users but I'm pretty sure there aren't. I the only thing I can think of that could possibly be using it is `nix search` but I'd have to check.

If there are users who can't deal with duplicates we could either just export the latest versions or export the longer list as a separate JSON (maybe even the [nearly complete list](https://github.com/NixOS/nixpkgs/pull/102509)).

> I assume yes because some packages might be disabled under older/newer versions of their respective runtime

Yeah that's what I was thinking too. Although, the set of packages not in both sets probably isn't too large in most cases.

**Review by lukegb — APPROVED** [review]

**Comment by timokau** [comment]
@veprbl, you added a :confused: reaction to #102509. Is there a reason for that?

**Comment by garbas** [comment]
I'm a bit -0 on this one, since it does not addresses the real problem. Somebody will have to keep this list manually up to date. It would be nicer if this list would not be even needed. But I understand that this solved the problem currently, therefore I'm not against it, but would like to challenge that the problem to be addressed at the root.

**Comment by timokau** [comment]
Since this discussion has stalled a bit and it seems like nobody is working on a better solution, I think something is better than nothing for now. So I'm calling "FCP with predisposition to merge" now. Unless somebody disagrees, I'll merge on Wednesday.

**Comment by Atemu** [comment]
The only thing I was worried about being affected would be `nix search` but it seems like that generates its own json.

**Review by timokau — APPROVED** [review]
Thank you for working on this @Atemu!

**Comment by Atemu** [comment]
:o

image

**Comment by Atemu** [comment]
Issue on fixing this properly: https://github.com/NixOS/nixpkgs/issues/107539

**Pull request merged**
