### PR TITLE
nixos/apparmor: fix error on nixos-rebuild if no profiles are present

### PR DESCRIPTION
**Pull request by presto8**
Restarting the apparmor service after a nixos-rebuild results in an error on systems where no apparmor profiles are installed. This is because the aa-remove-unknown program, which is called when the service is reloaded, returns a non-zero return code if no profiles are present.

This changeset adds a guard to run aa-remove-unknown only if there are profiles located in the /etc/apparmor.d directory, which resolves the issue.

Resolves issue #273164.

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by herrwiese** [comment]
Many thanks for your suggested fix!  This bugs me for some time now.  I had a closer look and just uploaded #285915 which tries to fix the problem at its root (broken check in `aa-remove-unknown`).  Maybe you want to have a look. :)

**Comment by presto8** [comment]
Closed in favor of #285915 which is a better way to fix the issue.

**Comment by ajs124** [comment]
We'll have to do the rebuild for https://github.com/NixOS/nixpkgs/pull/287441 anyways, so if we get https://github.com/NixOS/nixpkgs/pull/285915 into the same staging run, the rebuild amount is the same.

**Comment by presto8** [comment]
Closing since better approach was merged already :)

**Pull request closed without merging**
