### PR TITLE
Change kernel config: improve squashfs support of kernel

### PR DESCRIPTION
**Pull request by ts468**
Please check if that changes break anything, but things seem to build fine locally on my machine.

### CODE REVIEW

**Comment by ts468** [comment]
Maybe that PR should go into staging first?

**Comment by ts468** [comment]
@edolstra, what do you think about the changes?

**Comment by edolstra** [comment]
I'm not so sure about `SQUASHFS_4K_DEVBLK_SIZE`. The description suggests it's mostly good for sequential workloads, which is probably not the case for the live CD use case.

The others seem fine.

**Comment by ts468** [comment]
My intended use case was to store squashfs images on a filesystem like, e.g., btrfs, and then use the images from VMs. Do you think the value for SQUASHFS_4K_DEVBLK_SIZE makes a difference for that? I thought/hoped a 4K block size would align better with the block size of the underlying filesystem? But here I'm really just guessing...

**Comment by ts468** [comment]
@edolstra, I've updated the squashfs related changes to the kernel config, removing the previously suggested SQUASHFS_4K_DEVBLK_SIZE and leaving only non-controversial changes. Many thanks for merging the PR :)

**Pull request merged**
