### PR TITLE
update home-assistant-frontend to correct version for home-assistant 0.99.2

### PR DESCRIPTION
**Pull request by sweber83**
###### Motivation for this change
Currently the version of home-assistant-frontend is out of sync with the main home-assistant package.
Because of this some functionality (like the developer tools) of home assistant is broken.

###### Things done
To fix things bump home-assistant-frontend to 20190919.0
Here one can see that this is the correct version: https://github.com/home-assistant/home-assistant/blob/0.99.2/homeassistant/components/frontend/manifest.json

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @fleaz @dotlambda @globin

### CODE REVIEW

**Comment by risicle** [comment]
`nix-review` is happy for me on macos 10.13.

**Comment by etu** [comment]
@sweber83 Thanks! :)

**Comment by globin** [comment]
Fixed similarly on 19.09 in 97fc74fd349

**Comment by sweber83** [comment]
@etu
You're welcome!

**Pull request merged**
