### PR TITLE
mgba: cleanup derivation

### PR DESCRIPTION
**Pull request by SuperSamus**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by ocfox — APPROVED** [review]

**Comment by AndersonTorres** [comment]
Why?

**Comment by SuperSamus** [comment]
Every other similar derivation I've seen uses `libsForQt5.callPackage`, prefers using `rec` rather than `finalAttrs`, and I don't see any reason to use `let` just for renaming the dependencies.
Also, I'm removing `imagemagick` (which does nothing), and replacing `ffmpeg_4` with normal `ffmpeg`, which in my testing doesn't cause any problem.
And finally, alphabetical order.

**Comment by AndersonTorres** [comment]
> Every other similar derivation I've seen uses `libsForQt5.callPackage`

And no one explains why those derivations use it, besides "cultural circularity" - aka "because every other similar derivation uses libsForQt5.mkDerivation".

Further, "similar" is a dangerously loaded word here. Before #178206, cmake employed `libsForQt5.mkDerivation`.
I can't conceive two more different things that a cute console emulator and a big build system (besides incidentally using Qt to show fancy buttons in an overloaded DE).

> prefers using `rec` rather than `finalAttrs`

Let's go revert #119942 and everything related, then?

>, and I don't see any reason to use `let` just for renaming the dependencies.

The magic word was splicing.

#208264
#204303

> Also, I'm removing `imagemagick` (which does nothing),

This should be in a separate commit, since it changes the expression (besides cosmetic).

> and replacing `ffmpeg_4` with normal `ffmpeg`, which in my testing doesn't cause any problem.

This should be in a separate commit too (same reason as the previous point).

> And finally, alphabetical order.

It was already in alphabetical order - or, more accurate, ascii-betical order, as default of [Emacs commands](https://www.gnu.org/software/emacs/manual/html_node/emacs/Sorting.html).

**Review by AndersonTorres — CHANGES_REQUESTED** [review]
Please, include in the body of commit message an explicit mention about the removal. Something like:

```
mgba: cleanup

- Remove unused imagemagick dependency
- Use default ffmpeg
```

Besides, LGTM.

**Pull request merged**
