### PR TITLE
SDL2_image: 2.8.2 -> 2.8.3

### PR DESCRIPTION
**Pull request by trofi**
Changes: https://github.com/libsdl-org/SDL_image/releases/tag/release-2.8.3

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by trofi** [comment]
Moving to draft as it breaks `SDL2_image_2_0` with `SDL2_image` which for some reason shares the expression:

```
      > autoreconf: error: automake failed with exit status: 1
       For full logs, run 'nix log /nix/store/dcfzmq79hz9wi6ppi2kcnrp0r4iiyzrr-SDL2_image-2.0.5.drv'.
```

**Comment by trofi** [comment]
> Moving to draft as it breaks `SDL2_image_2_0` with `SDL2_image` which for some reason shares the expression:
> 
> ```
>       > autoreconf: error: automake failed with exit status: 1
>        For full logs, run 'nix log /nix/store/dcfzmq79hz9wi6ppi2kcnrp0r4iiyzrr-SDL2_image-2.0.5.drv'.
> ```

Tweaked the patch phase to provide enough files to allow `autoreconf`. Ready for review.

**Review by philiptaron — APPROVED** [review]
Read the release notes, built the packages, build a few dependent games in the tree, LGTM. ✅

**Comment by philiptaron** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 366222`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python312Packages.pettingzoo</li>
    <li>python312Packages.pettingzoo.dist</li>
    <li>python312Packages.shimmy</li>
    <li>python312Packages.shimmy.dist</li>
  </ul>
</details>
<details>
  <summary>:fast_forward: 1 package blacklisted:</summary>
  <ul>
    <li>appimage-run-tests</li>
  </ul>
</details>
<details>
  <summary>:x: 18 packages failed to build:</summary>
  <ul>
    <li>alephone-apotheosis-x</li>
    <li>cider-2</li>
    <li>d1x-rebirth-full</li>
    <li>d2x-rebirth-full</li>
    <li>koboredux</li>
    <li>manaplus</li>
    <li>python311Packages.stable-baselines3</li>
    <li>python311Packages.stable-baselines3.dist</li>
    <li>python312Packages.stable-baselines3</li>
    <li>python312Packages.stable-baselines3.dist</li>
    <li>quickgui</li>
    <li>quickgui.debug</li>
    <li>quickgui.pubcache</li>
    <li>rocksndiamonds</li>
    <li>sbclPackages.easing-demo</li>
    <li>sbclPackages.sketch</li>
    <li>sbclPackages.sketch-examples</li>
    <li>toppler</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 406 packages built:</summary>
  <ul>
    <li>OVMFFull</li>
    <li>OVMFFull.fd</li>
    <li>SDL2_image</li>
    <li>SDL2_image_2_0</li>
    <li>SDL2_image_2_6</li>
    <li>_20kly</li>
    <li>abbaye-des-morts</li>
    <li>alephone</li>
    <li>alephone-durandal</li>
    <li>alephone-eternal</li>
    <li>alephone-evil</li>
    <li>alephone-infinity</li>
    <li>alephone-marathon</li>
    <li>alephone-pathways-into-darkness</li>
    <li>alephone-pheonix</li>
    <li>alephone-red</li>
    <li>alephone-rubicon-x</li>
    <li>alephone-yuge</li>
    <li>alephone.icons</li>
    <li>altair</li>
    <li>amiberry</li>
    <li>anbox</li>
    <li>ankama-launcher</li>
    <li>anki-bin</li>
    <li>anytype</li>
    <li>appimage-run</li>
    <li>archipelago</li>
    <li>archipelago-minecraft</li>
    <li>arduino-ide</li>
    <li>assaultcube</li>
    <li>badlion-client</li>
    <li>bazecor</li>
    <li>beekeeper-studio</li>
    <li>beeper</li>
    <li>betterdiscord-installer</li>
    <li>bitcomet</li>
    <li>blobby</li>
    <li>blobwars</li>
    <li>blockattack</li>
    <li>blockattack.man</li>
    <li>bloomrpc</li>
    <li>bootstrap-studio</li>
    <li>brogue-ce</li>
    <li>brutalmaze</li>
    <li>brutalmaze.dist</li>
    <li>budgie-control-center</li>
    <li>budgie-control-center.debug</li>
    <li>buttercup-desktop</li>
    <li>cables</li>
    <li>caido</li>
    <li>caprine-bin</li>
    <li>cataclysm-dda</li>
    <li>cataclysm-dda-git</li>
    <li>cdogs-sdl</li>
    <li>chatzone-desktop</li>
    <li>chickenPackages_5.chickenEggs.sdl2-image</li>
    <li>chromium-bsu</li>
    <li>chrysalis</li>
    <li>cider</li>
    <li>clash-nyanpasu</li>
    <li>clickup</li>
    <li>clockify</li>
    <li>code-cursor</li>
    <li>codux</li>
    <li>colima</li>
    <li>colobot</li>
    <li>commandergenius</li>
    <li>cot (python312Packages.cot)</li>
    <li>cot.dist (python312Packages.cot.dist)</li>
    <li>cozy-drive</li>
    <li>crawlTiles</li>
    <li>crypto-org-wallet</li>
    <li>davinci-resolve</li>
    <li>davinci-resolve-studio</li>
    <li>dbgate</li>
    <li>decker</li>
    <li>deskreen</li>
    <li>devdocs-desktop</li>
    <li>devilutionx</li>
    <li>diffoscope</li>
    <li>diffoscope.dist</li>
    <li>diffoscope.man</li>
    <li>doomretro</li>
    <li>dopamine</li>
    <li>dosbox-staging</li>
    <li>dosbox-staging.man</li>
    <li>dreamchess</li>
    <li>dsda-doom</li>
    <li>dwarf-fortress</li>
    <li>dwarf-fortress-packages.dwarf-fortress-full</li>
    <li>dwarf-fortress-packages.dwarf-fortress-original</li>
    <li>dwarf-fortress-packages.dwarf-fortress_50_10</li>
    <li>dwarf-fortress-packages.dwarf-fortress_50_11</li>
    <li>dwarf-fortress-packages.dwarf-fortress_50_12</li>
    <li>dwarf-fortress-packages.dwarf-therapist</li>
    <li>dxx-rebirth</li>
    <li>electron-mail</li>
    <li>electronplayer</li>
    <li>endgame-singularity</li>
    <li>endgame-singularity.dist</li>
    <li>enigma</li>
    <li>everdo</li>
    <li>fflogs</li>
    <li>fheroes2</li>
    <li>firefly-desktop</li>
    <li>flare</li>
    <li>flexoptix-app</li>
    <li>fluent-reader</li>
    <li>framesh</li>
    <li>freeciv</li>
    <li>freeciv_qt</li>
    <li>freeciv_sdl2</li>
    <li>freenukum</li>
    <li>freerdp3</li>
    <li>frescobaldi</li>
    <li>frescobaldi.dist</li>
    <li>frogatto</li>
    <li>garble</li>
    <li>gearlever</li>
    <li>gnome-connections</li>
    <li>gnome-control-center</li>
    <li>gnome-control-center.debug</li>
    <li>gnome-remote-desktop</li>
    <li>golden-cheetah-bin</li>
    <li>gource</li>
    <li>gtk-frdp</li>
    <li>guestfs-tools</li>
    <li>guile-chickadee</li>
    <li>guile-sdl2</li>
    <li>hamrs</li>
    <li>hamsket</li>
    <li>handheld-daemon-ui</li>
    <li>hedgewars</li>
    <li>heptabase</li>
    <li>hifile</li>
    <li>hikounomizu</li>
    <li>hoppscotch</li>
    <li>httpie-desktop</li>
    <li>immersed</li>
    <li>infra-arcana</li>
    <li>insomnia</li>
    <li>instead</li>
    <li>irccloud</li>
    <li>jan</li>
    <li>jbrowse</li>
    <li>jet-pilot</li>
    <li>jetbrains-toolbox</li>
    <li>joplin-desktop</li>
    <li>kata-runtime</li>
    <li>katawa-shoujo-re-engineered</li>
    <li>kchat</li>
    <li>keeperrl</li>
    <li>keet</li>
    <li>klystrack</li>
    <li>kmeet</li>
    <li>koboredux-free</li>
    <li>lbreakouthd</li>
    <li>lbry</li>
    <li>ldtk</li>
    <li>ledger-live-desktop</li>
    <li>lens</li>
    <li>libguestfs</li>
    <li>libguestfs-with-appliance</li>
    <li>libguestfs-with-appliance.guestfsd</li>
    <li>libguestfs.guestfsd</li>
    <li>libresprite</li>
    <li>librewolf-bin</li>
    <li>libwtk-sdl2</li>
    <li>libwtk-sdl2.dev</li>
    <li>libwtk-sdl2.lib</li>
    <li>lima</li>
    <li>lima-bin</li>
    <li>lincity_ng</li>
    <li>linthesia</li>
    <li>liquidsoap</li>
    <li>listen1</li>
    <li>lmstudio</li>
    <li>logstalgia</li>
    <li>losslesscut-bin</li>
    <li>lpairs2</li>
    <li>lunar-client</li>
    <li>lunatask</li>
    <li>lxd-lts</li>
    <li>mathpix-snipping-tool</li>
    <li>mendeley</li>
    <li>mepo</li>
    <li>methane</li>
    <li>minari (python312Packages.minari)</li>
    <li>minari.dist (python312Packages.minari.dist)</li>
    <li>miru</li>
    <li>mobilecoin-wallet</li>
    <li>mockoon</li>
    <li>molotov</li>
    <li>motrix</li>
    <li>mpd-touch-screen-gui</li>
    <li>mqttx</li>
    <li>muffon</li>
    <li>multipass</li>
    <li>museeks</li>
    <li>mycrypto</li>
    <li>naev</li>
    <li>narsil</li>
    <li>navicat-premium</li>
    <li>nemu</li>
    <li>neo4j-desktop</li>
    <li>nosql-workbench</li>
    <li>notable</li>
    <li>notesnook</li>
    <li>notion-app-enhanced</li>
    <li>nsz (python312Packages.nsz)</li>
    <li>nsz.dist (python312Packages.nsz.dist)</li>
    <li>nuclear</li>
    <li>ocamlPackages.tsdl-image</li>
    <li>open-watcom-bin</li>
    <li>open-watcom-bin-unwrapped</li>
    <li>opendune</li>
    <li>openmsx</li>
    <li>openspades</li>
    <li>osu-lazer-bin</li>
    <li>out-of-tree</li>
    <li>p3x-onenote</li>
    <li>paperlib</li>
    <li>parsify</li>
    <li>phosh</li>
    <li>phosh-mobile-settings</li>
    <li>picoloop</li>
    <li>pingus</li>
    <li>pinokio</li>
    <li>pioneer</li>
    <li>plexamp</li>
    <li>polypane</li>
    <li>poptracker</li>
    <li>prboom-plus</li>
    <li>principia</li>
    <li>protonup-qt</li>
    <li>pureref</li>
    <li>pysolfc</li>
    <li>pysolfc.dist</li>
    <li>python311Packages.ale-py</li>
    <li>python311Packages.ale-py.dist</li>
    <li>python311Packages.cot</li>
    <li>python311Packages.cot.dist</li>
    <li>python311Packages.guestfs</li>
    <li>python311Packages.guestfs.dist</li>
    <li>python311Packages.gymnasium</li>
    <li>python311Packages.gymnasium.dist</li>
    <li>python311Packages.kivy</li>
    <li>python311Packages.kivy.dist</li>
    <li>python311Packages.minari</li>
    <li>python311Packages.minari.dist</li>
    <li>python311Packages.nsz</li>
    <li>python311Packages.nsz.dist</li>
    <li>python311Packages.pettingzoo</li>
    <li>python311Packages.pettingzoo.dist</li>
    <li>python311Packages.pyautogui</li>
    <li>python311Packages.pyautogui.dist</li>
    <li>python311Packages.pygame</li>
    <li>python311Packages.pygame-ce</li>
    <li>python311Packages.pygame-ce.dist</li>
    <li>python311Packages.pygame-gui</li>
    <li>python311Packages.pygame-gui.dist</li>
    <li>python311Packages.pygame-sdl2</li>
    <li>python311Packages.pygame-sdl2.dist</li>
    <li>python311Packages.pygame.dist</li>
    <li>python311Packages.pygetwindow</li>
    <li>python311Packages.pygetwindow.dist</li>
    <li>python311Packages.pyrect</li>
    <li>python311Packages.pyrect.dist</li>
    <li>python311Packages.pysdl2</li>
    <li>python311Packages.pysdl2.dist</li>
    <li>python311Packages.pytmx</li>
    <li>python311Packages.pytmx.dist</li>
    <li>python311Packages.shimmy</li>
    <li>python311Packages.shimmy.dist</li>
    <li>python311Packages.skrl</li>
    <li>python311Packages.skrl.dist</li>
    <li>python311Packages.torchrl</li>
    <li>python311Packages.torchrl.dist</li>
    <li>python311Packages.vulkan</li>
    <li>python311Packages.vulkan.dist</li>
    <li>python312Packages.ale-py</li>
    <li>python312Packages.ale-py.dist</li>
    <li>python312Packages.guestfs</li>
    <li>python312Packages.guestfs.dist</li>
    <li>python312Packages.gymnasium</li>
    <li>python312Packages.gymnasium.dist</li>
    <li>python312Packages.kivy</li>
    <li>python312Packages.kivy.dist</li>
    <li>python312Packages.pyautogui</li>
    <li>python312Packages.pyautogui.dist</li>
    <li>python312Packages.pygame</li>
    <li>python312Packages.pygame-ce</li>
    <li>python312Packages.pygame-ce.dist</li>
    <li>python312Packages.pygame-gui</li>
    <li>python312Packages.pygame-gui.dist</li>
    <li>python312Packages.pygame-sdl2</li>
    <li>python312Packages.pygame-sdl2.dist</li>
    <li>python312Packages.pygame.dist</li>
    <li>python312Packages.pygetwindow</li>
    <li>python312Packages.pygetwindow.dist</li>
    <li>python312Packages.pyrect</li>
    <li>python312Packages.pyrect.dist</li>
    <li>python312Packages.pysdl2</li>
    <li>python312Packages.pysdl2.dist</li>
    <li>python312Packages.pytmx</li>
    <li>python312Packages.pytmx.dist</li>
    <li>python312Packages.skrl</li>
    <li>python312Packages.skrl.dist</li>
    <li>python312Packages.torchrl</li>
    <li>python312Packages.torchrl.dist</li>
    <li>python312Packages.vulkan</li>
    <li>python312Packages.vulkan.dist</li>
    <li>qemu</li>
    <li>qemu.debug</li>
    <li>qemu.doc</li>
    <li>qemu.ga</li>
    <li>qemu_full</li>
    <li>qemu_full.debug</li>
    <li>qemu_full.doc</li>
    <li>qemu_full.ga</li>
    <li>qemu_kvm</li>
    <li>qemu_kvm.debug</li>
    <li>qemu_kvm.doc</li>
    <li>qemu_kvm.ga</li>
    <li>qemu_xen</li>
    <li>qemu_xen.debug</li>
    <li>qemu_xen.doc</li>
    <li>qemu_xen.ga</li>
    <li>qidi-slicer-bin</li>
    <li>qtemu</li>
    <li>quba</li>
    <li>quickemu</li>
    <li>quiet</li>
    <li>railway-wallet</li>
    <li>rambox</li>
    <li>raven-reader</li>
    <li>redact</li>
    <li>redeclipse</li>
    <li>remmina</li>
    <li>remnote</li>
    <li>renpy</li>
    <li>requestly</li>
    <li>responsively-app</li>
    <li>retrofe</li>
    <li>rquickshare</li>
    <li>saleae-logic-2</li>
    <li>sauerbraten</li>
    <li>sbclPackages.calm</li>
    <li>sbclPackages.cepl_dot_sdl2-image</li>
    <li>sbclPackages.sdl2-image</li>
    <li>sdlpop</li>
    <li>session-desktop</li>
    <li>simplex-chat-desktop</li>
    <li>sleek-todo</li>
    <li>snipaste</li>
    <li>solarus</li>
    <li>solarus-quest-editor</li>
    <li>solarus.dev</li>
    <li>solarus.lib</li>
    <li>sonixd</li>
    <li>sozi</li>
    <li>ssb-patchwork</li>
    <li>station</li>
    <li>status-im</li>
    <li>steam-rom-manager</li>
    <li>steamos-devkit</li>
    <li>steamos-devkit.dist</li>
    <li>superTux</li>
    <li>supermariowar</li>
    <li>sylk</li>
    <li>tamatool</li>
    <li>tauon</li>
    <li>the-legend-of-edgar</li>
    <li>theforceengine</li>
    <li>timeular</li>
    <li>todoist-electron</li>
    <li>tome4</li>
    <li>trackballs</li>
    <li>trezor-suite</li>
    <li>trigger</li>
    <li>tusk</li>
    <li>tutanota-desktop</li>
    <li>tuxpaint</li>
    <li>ultrastardx</li>
    <li>upscaler</li>
    <li>upscayl</li>
    <li>vagrant</li>
    <li>vcmi</li>
    <li>vdrift</li>
    <li>vdrift-bin</li>
    <li>via</li>
    <li>vial</li>
    <li>video2midi</li>
    <li>virt-v2v</li>
    <li>vmctl</li>
    <li>wargus</li>
    <li>wesnoth</li>
    <li>widelands</li>
    <li>wootility</li>
    <li>wowup-cf</li>
    <li>xemu</li>
    <li>xemu.debug</li>
    <li>xlights</li>
    <li>yafc-ce</li>
    <li>zecwallet-lite</li>
    <li>zettlr</li>
  </ul>
</details>

**Pull request merged**
