### PR TITLE
python311Packages.construct: 2.10.68 -> 2.10.69

### PR DESCRIPTION
**Pull request by fabaff**
Diff: https://github.com/construct/construct/compare/refs/tags/v2.10.69...v2.10.69

Changelog: https://github.com/construct/construct/releases/tag/v2.10.69

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 267848` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages marked as broken and skipped:</summary>
  <ul>
    <li>home-assistant-component-tests.matter</li>
    <li>python-matter-server</li>
    <li>python-matter-server.dist</li>
    <li>python310Packages.home-assistant-chip-core</li>
    <li>python310Packages.home-assistant-chip-core.dist</li>
    <li>python310Packages.python-matter-server</li>
    <li>python310Packages.python-matter-server.dist</li>
    <li>python311Packages.home-assistant-chip-core</li>
    <li>python311Packages.home-assistant-chip-core.dist</li>
    <li>python311Packages.python-matter-server</li>
    <li>python311Packages.python-matter-server.dist</li>
  </ul>
</details>
<details>
  <summary>111 packages built:</summary>
  <ul>
    <li>cve-bin-tool</li>
    <li>cve-bin-tool.dist</li>
    <li>deltachat-desktop</li>
    <li>electron-cash</li>
    <li>electron-cash.dist</li>
    <li>electrum</li>
    <li>electrum-grs</li>
    <li>electrum-grs.dist</li>
    <li>electrum-ltc</li>
    <li>electrum-ltc.dist</li>
    <li>electrum.dist</li>
    <li>gallia</li>
    <li>gallia.dist</li>
    <li>gnome-secrets</li>
    <li>home-assistant-component-tests.nibe_heatpump</li>
    <li>home-assistant-component-tests.roborock</li>
    <li>home-assistant-component-tests.snapcast</li>
    <li>home-assistant-component-tests.surepetcare</li>
    <li>home-assistant-component-tests.vallox</li>
    <li>home-assistant-component-tests.xiaomi_miio</li>
    <li>keepmenu</li>
    <li>keepmenu.dist</li>
    <li>qt5.qutebrowser (libsForQt5.qutebrowser)</li>
    <li>qt5.qutebrowser.dist (libsForQt5.qutebrowser.dist)</li>
    <li>noto-fonts-color-emoji</li>
    <li>passExtensions.pass-import</li>
    <li>passExtensions.pass-import.dist</li>
    <li>pgadmin4</li>
    <li>pgadmin4-desktopmode</li>
    <li>pgadmin4-desktopmode.dist</li>
    <li>pgadmin4.dist</li>
    <li>python310Packages.afdko</li>
    <li>python310Packages.afdko.dist</li>
    <li>python310Packages.brotli-asgi</li>
    <li>python310Packages.brotli-asgi.dist</li>
    <li>python310Packages.brotlipy</li>
    <li>python310Packages.brotlipy.dist</li>
    <li>python310Packages.construct</li>
    <li>python310Packages.construct-classes</li>
    <li>python310Packages.construct-classes.dist</li>
    <li>python310Packages.construct.dist</li>
    <li>python310Packages.garminconnect-aio</li>
    <li>python310Packages.garminconnect-aio.dist</li>
    <li>python310Packages.ledgerwallet</li>
    <li>python310Packages.ledgerwallet.dist</li>
    <li>python310Packages.nibe</li>
    <li>python310Packages.nibe.dist</li>
    <li>python310Packages.nototools</li>
    <li>python310Packages.nototools.dist</li>
    <li>python310Packages.procmon-parser</li>
    <li>python310Packages.procmon-parser.dist</li>
    <li>python310Packages.pykeepass</li>
    <li>python310Packages.pykeepass.dist</li>
    <li>python310Packages.pysim</li>
    <li>python310Packages.pysim.dist</li>
    <li>python310Packages.python-miio</li>
    <li>python310Packages.python-miio.dist</li>
    <li>python310Packages.python-roborock</li>
    <li>python310Packages.python-roborock.dist</li>
    <li>python310Packages.snapcast</li>
    <li>python310Packages.snapcast.dist</li>
    <li>python310Packages.surepy</li>
    <li>python310Packages.surepy.dist</li>
    <li>python310Packages.trezor</li>
    <li>python310Packages.trezor.dist</li>
    <li>python310Packages.trezor_agent</li>
    <li>python310Packages.trezor_agent.dist</li>
    <li>python310Packages.vallox-websocket-api</li>
    <li>python310Packages.vallox-websocket-api.dist</li>
    <li>python311Packages.afdko</li>
    <li>python311Packages.afdko.dist</li>
    <li>python311Packages.brotli-asgi</li>
    <li>python311Packages.brotli-asgi.dist</li>
    <li>python311Packages.brotlipy</li>
    <li>python311Packages.brotlipy.dist</li>
    <li>python311Packages.construct</li>
    <li>python311Packages.construct-classes</li>
    <li>python311Packages.construct-classes.dist</li>
    <li>python311Packages.construct.dist</li>
    <li>python311Packages.garminconnect-aio</li>
    <li>python311Packages.garminconnect-aio.dist</li>
    <li>python311Packages.ledgerwallet</li>
    <li>python311Packages.ledgerwallet.dist</li>
    <li>python311Packages.nibe</li>
    <li>python311Packages.nibe.dist</li>
    <li>python311Packages.nototools</li>
    <li>python311Packages.nototools.dist</li>
    <li>python311Packages.procmon-parser</li>
    <li>python311Packages.procmon-parser.dist</li>
    <li>python311Packages.pykeepass</li>
    <li>python311Packages.pykeepass.dist</li>
    <li>python311Packages.pysim</li>
    <li>python311Packages.pysim.dist</li>
    <li>python311Packages.python-miio</li>
    <li>python311Packages.python-miio.dist</li>
    <li>python311Packages.python-roborock</li>
    <li>python311Packages.python-roborock.dist</li>
    <li>python311Packages.snapcast</li>
    <li>python311Packages.snapcast.dist</li>
    <li>python311Packages.surepy</li>
    <li>python311Packages.surepy.dist</li>
    <li>trezorctl (python311Packages.trezor)</li>
    <li>trezorctl.dist (python311Packages.trezor.dist)</li>
    <li>trezor_agent (python311Packages.trezor_agent)</li>
    <li>trezor_agent.dist (python311Packages.trezor_agent.dist)</li>
    <li>python311Packages.vallox-websocket-api</li>
    <li>python311Packages.vallox-websocket-api.dist</li>
    <li>qutebrowser</li>
    <li>qutebrowser.dist</li>
    <li>twitter-color-emoji</li>
    <li>whatsapp-emoji-font</li>
  </ul>
</details>

**Review by bjornfor — DISMISSED** [review]
Commit message references old version as .69 but should be .68 (more than once).

**Review by bjornfor — COMMENTED** [review]
Please split version bumps and expression rewrites in separate commits.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 267848` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>111 packages built:</summary>
  <ul>
    <li>cve-bin-tool</li>
    <li>cve-bin-tool.dist</li>
    <li>deltachat-desktop</li>
    <li>electron-cash</li>
    <li>electron-cash.dist</li>
    <li>electrum</li>
    <li>electrum-grs</li>
    <li>electrum-grs.dist</li>
    <li>electrum-ltc</li>
    <li>electrum-ltc.dist</li>
    <li>electrum.dist</li>
    <li>gallia</li>
    <li>gallia.dist</li>
    <li>gnome-secrets</li>
    <li>home-assistant-component-tests.nibe_heatpump</li>
    <li>home-assistant-component-tests.roborock</li>
    <li>home-assistant-component-tests.snapcast</li>
    <li>home-assistant-component-tests.surepetcare</li>
    <li>home-assistant-component-tests.vallox</li>
    <li>home-assistant-component-tests.xiaomi_miio</li>
    <li>keepmenu</li>
    <li>keepmenu.dist</li>
    <li>noto-fonts-color-emoji</li>
    <li>passExtensions.pass-import</li>
    <li>passExtensions.pass-import.dist</li>
    <li>pgadmin4</li>
    <li>pgadmin4-desktopmode</li>
    <li>pgadmin4-desktopmode.dist</li>
    <li>pgadmin4.dist</li>
    <li>python310Packages.afdko</li>
    <li>python310Packages.afdko.dist</li>
    <li>python310Packages.brotli-asgi</li>
    <li>python310Packages.brotli-asgi.dist</li>
    <li>python310Packages.brotlipy</li>
    <li>python310Packages.brotlipy.dist</li>
    <li>python310Packages.construct</li>
    <li>python310Packages.construct-classes</li>
    <li>python310Packages.construct-classes.dist</li>
    <li>python310Packages.construct.dist</li>
    <li>python310Packages.garminconnect-aio</li>
    <li>python310Packages.garminconnect-aio.dist</li>
    <li>python310Packages.ledgerwallet</li>
    <li>python310Packages.ledgerwallet.dist</li>
    <li>python310Packages.nibe</li>
    <li>python310Packages.nibe.dist</li>
    <li>python310Packages.nototools</li>
    <li>python310Packages.nototools.dist</li>
    <li>python310Packages.procmon-parser</li>
    <li>python310Packages.procmon-parser.dist</li>
    <li>python310Packages.pykeepass</li>
    <li>python310Packages.pykeepass.dist</li>
    <li>python310Packages.pysim</li>
    <li>python310Packages.pysim.dist</li>
    <li>python310Packages.python-miio</li>
    <li>python310Packages.python-miio.dist</li>
    <li>python310Packages.python-roborock</li>
    <li>python310Packages.python-roborock.dist</li>
    <li>python310Packages.snapcast</li>
    <li>python310Packages.snapcast.dist</li>
    <li>python310Packages.surepy</li>
    <li>python310Packages.surepy.dist</li>
    <li>python310Packages.trezor</li>
    <li>python310Packages.trezor.dist</li>
    <li>python310Packages.trezor_agent</li>
    <li>python310Packages.trezor_agent.dist</li>
    <li>python310Packages.vallox-websocket-api</li>
    <li>python310Packages.vallox-websocket-api.dist</li>
    <li>python311Packages.afdko</li>
    <li>python311Packages.afdko.dist</li>
    <li>python311Packages.brotli-asgi</li>
    <li>python311Packages.brotli-asgi.dist</li>
    <li>python311Packages.brotlipy</li>
    <li>python311Packages.brotlipy.dist</li>
    <li>python311Packages.construct</li>
    <li>python311Packages.construct-classes</li>
    <li>python311Packages.construct-classes.dist</li>
    <li>python311Packages.construct.dist</li>
    <li>python311Packages.garminconnect-aio</li>
    <li>python311Packages.garminconnect-aio.dist</li>
    <li>python311Packages.ledgerwallet</li>
    <li>python311Packages.ledgerwallet.dist</li>
    <li>python311Packages.nibe</li>
    <li>python311Packages.nibe.dist</li>
    <li>python311Packages.nototools</li>
    <li>python311Packages.nototools.dist</li>
    <li>python311Packages.procmon-parser</li>
    <li>python311Packages.procmon-parser.dist</li>
    <li>python311Packages.pykeepass</li>
    <li>python311Packages.pykeepass.dist</li>
    <li>python311Packages.pysim</li>
    <li>python311Packages.pysim.dist</li>
    <li>python311Packages.python-miio</li>
    <li>python311Packages.python-miio.dist</li>
    <li>python311Packages.python-roborock</li>
    <li>python311Packages.python-roborock.dist</li>
    <li>python311Packages.snapcast</li>
    <li>python311Packages.snapcast.dist</li>
    <li>python311Packages.surepy</li>
    <li>python311Packages.surepy.dist</li>
    <li>trezorctl (python311Packages.trezor)</li>
    <li>trezorctl.dist (python311Packages.trezor.dist)</li>
    <li>trezor_agent (python311Packages.trezor_agent)</li>
    <li>trezor_agent.dist (python311Packages.trezor_agent.dist)</li>
    <li>python311Packages.vallox-websocket-api</li>
    <li>python311Packages.vallox-websocket-api.dist</li>
    <li>qutebrowser</li>
    <li>qutebrowser-qt5</li>
    <li>qutebrowser-qt5.dist</li>
    <li>qutebrowser.dist</li>
    <li>twitter-color-emoji</li>
    <li>whatsapp-emoji-font</li>
  </ul>
</details>

**Review by bjornfor — APPROVED** [review]

**Comment by bjornfor** [comment]
> Please split version bumps and expression rewrites in separate commits.

I see this became a number of commits: 1 version bump, 1 refactor and 4 additional misc commits. What I meant was just 1 version bump and 1 "update expression" (with bullet list of changes). I can see how my wording was unclear. I don't personally mind these fine grained commits (in fact I like it), but I just wanted to clarify my intention.

**Comment by bjornfor** [comment]
Thanks!

**Pull request merged**
