### PR TITLE
python3Packages.httpcore: 0.12.3 -> 0.13.0

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 0.13.0

Change log: https://github.com/encode/httpcore/blob/master/CHANGELOG.md#0130-april-21st-2021

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
`httpx` update is in progress: https://github.com/encode/httpx/pull/1576

**Comment by fabaff** [comment]
`pytest-httpx` needs to updated: https://github.com/Colin-b/pytest_httpx/issues/40

**Comment by teh** [comment]
aiobotocore change looks good, thanks!

**Comment by mweinelt** [comment]
Breaks the PyRMVTransport tests. I've reported this in the already open issue for `httpx==0.18.0` support.

https://github.com/Colin-b/pytest_httpx/issues/40

**Comment by mweinelt** [comment]
Rebasing on top of latest master and checking out the breakage. I need this change for home-assistant v2021.5.0.

**Comment by mweinelt** [comment]
Sanic was the only build failure due to the httpx or httpcore update, most other are unrelated or flaky.

**Pull request merged**
