### PR TITLE
.github/PULL_REQUEST_TEMPLATE.md: add extra referfence to pkgs/README.md

### PR DESCRIPTION
**Pull request by AndersonTorres**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by infinisil** [comment]
What's the motivation for this? I don't see why this would be necessary

**Comment by infinisil** [comment]
Well, yes all these documents do have important information, but they should all be linked from CONTRIBUTING.md, I'd rather not have such links duplicated.

Also the PR template is already big enough, and it seems the bigger it becomes, the less people actually go through it. Or alternatively, the bigger it becomes, the less of it is actually relevant for a specific PR. Prime example is this very PR, for which none of the points apply :)

**Comment by AndersonTorres** [comment]
> What's the motivation for this? I don't see why this would be necessary 

\- Do this not that
\- Why?
\- It is in the pkgs/README.md
\- I haven't seen it

> Well, yes all these documents do have important information, but they should all be linked from CONTRIBUTING.md, I'd rather not have such links duplicated.

A link into CONTRIBUTING.md? LGTM

> Prime example is this very PR, for which none of the points apply :)

Because, ehr, this PR does not require software compilation or installation...

**Comment by infinisil** [comment]
> Because, ehr, this PR does not require software compilation or installation...

Even for that a lot of points don't apply! Nixpkgs is just so varied. I think the PR template might work better something like this:

> - [ ] The change is tested [link to document showing how to test different parts]
> - [ ] The change is documented (if necessary) [link to document explaining what changes need to be documented and how]

Where the linked documents go to into the specifics. That's for a future PR though.

> A link into CONTRIBUTING.md? LGTM

This is already the case fwiw, the [overview section](https://github.com/NixOS/nixpkgs/blob/9ef8374074b8a00f01547a09cd8bac4d0519e5d9/CONTRIBUTING.md#overview) links to `pkgs/README.md`, and its [overview section](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#overview) links to `pkgs/by-name/README.md`.

Oh and also I don't think it should be necessary because `pkgs/by-name` will become enforced (when applicable) in the future, and for now it's still in the early stages.

**Pull request closed without merging**
