### PR TITLE
tlaplusToolbox: 1.5.7 -> 1.6.0

### PR DESCRIPTION
**Pull request by badmutex**
Bumps to new release of TLA+ Toolbox. Addresses #65760

Main change:
- toolbox now includes JRE so those external dependencies are no
longer needed.

Testing:
- nix-build -A tlaplusToolbox
- ./result/bin/tla-toolbox
- pdf generation
- validation of a simple pluscal model

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @vcunat

### CODE REVIEW

**Comment by srhb** [comment]
I don't think it's preferable to use a bundled jre if at all avoidable. It makes it more difficult to override its behaviour etc. with regular nix approaches. Has it become more difficult to use our own?

**Comment by badi** [comment]
> I don't think it's preferable to use a bundled jre if at all avoidable. It makes it more difficult to override its behaviour etc. with regular nix approaches
Yeah I agree.

> Has it become more difficult to use our own?
Yep. The toolbox binary now looks for the packaged jre directly instead of whatever java is in PATH.


I suppose we could try to override the lookup to get the old behavior back but I haven't tried that yet.

**Review by vcunat — APPROVED** [review]
I don't feel related to this in any way, but I can't see why block the merge.

**Comment by lemmy** [comment]
FWIW: We the upstream developers decided to bundle the JRE for a reason and now consider the JRE part of our distribution, ie. might patch it in the future.  We would thus recommend not to alter the lookup mechanism to use the JRE on the PATH.

**Pull request merged**
