### PR TITLE
nixos/roundcube: more options

### PR DESCRIPTION
**Pull request by Vskilet**
###### Motivation for this change
Add some options that allow to not known the PHP configuration of Roundcube. Default options are more secure than before.

I can see that @Ma27 worked too on the module. How can I merge our work without break the master ? :)

PS : I'm searching how to use a passwordFile option also and don't stock password on store.
###### Things done
- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Ma27** [comment]
> I can see that @Ma27 worked too on the module. How can I merge our work without break the master ? :)

You should go back to your first commit (4c4f068c1496ba50d516402aca27486fde43dd2c) and then run something like `git rebase master`.

I didn't go through the changes (yet) so I don't know if there will be any conflicts. If you need assistance with resolving those, feelf ree to ping me.

> PS : I'm searching how to use a passwordFile option also and don't stock password on store.

You could read it with [`file_get_contents`](https://secure.php.net/manual/de/function.file-get-contents.php):

```nix
{
  environment.etc."roundcube/config.inc.php".text = ''
    <?php
    $config['smtp_pass'] = file_get_contents('${cfg.smtpPasswordFile}');
  '';
}
```

Please keep in mind that `file_get_contents` returns false and only yields a warning and this needs some better error handling.

**Comment by Ma27** [comment]
Admittedly I'm not sure anymore if we actually want to merge this. The [NixOS RFC 42](https://github.com/NixOS/rfcs/pull/42) which proposes to simplify the complexity of modules by using a simple `config` attribute rather than multiple options and add several library helpers to render the config attr set in any given configuration language (or PHP in this case).

**Comment by Vskilet** [comment]
OK. So I can close this and do another pull request for password stuff

**Comment by Ma27** [comment]
I'd wait for now. I'd recommend to use `extraConfig` for this kind of stuff for now and wait how the RFC develops :)

**Comment by Ma27** [comment]
Ah and I've just seen that you force-pushed after my comment. IIRC I didn't get a notification for this (not sure how GitHub handles this), so feel free to ping the reviewer the next time (or at least leave a comment under the review when fixing stuff).

**Comment by Vskilet** [comment]
Not really relevant now I think

**Pull request closed without merging**
