### PR TITLE
pypy3Packages.bootstrapped-pip: fix build

### PR DESCRIPTION
**Pull request by wamserma**
###### Description of changes

PyPy3 ignores the local wheel package when `pyproject.toml` is present, so this file is removed before building, similar to the build of `setuptools`.

Fixes https://github.com/NixOS/nixpkgs/issues/150818

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
There should be no reason this is different between pypy and cpython. Has this issue been investigated further and reported on the pip tracker?

**Comment by wamserma** [comment]
> There should be no reason this is different between pypy and cpython. Has this issue been investigated further and reported on the pip tracker?

Not yet. What was the reason for `rm pyproject.toml` in https://github.com/NixOS/nixpkgs/commit/252ae444165fe4be8c8b3e3fc42a1c4eb857d609 ?

**Comment by FRidh** [comment]
> > There should be no reason this is different between pypy and cpython. Has this issue been investigated further and reported on the pip tracker?
> 
> Not yet. What was the reason for `rm pyproject.toml` in [252ae44](https://github.com/NixOS/nixpkgs/commit/252ae444165fe4be8c8b3e3fc42a1c4eb857d609) ?

We could not do a PEP517/518/pyproject/toml installation yet at that point. This is going to be the new default.

**Comment by wamserma** [comment]
> We could not do a PEP517/518/pyproject/toml installation at least not during bootstrapping. This is going to be the new default.

Switching to the new installation model will hopefully also resolve this issue.

Until then this workaround seems reasonable to me. Maybe just include it it the next round of python-bumps.

**Comment by FRidh** [comment]
Closing this because of https://github.com/NixOS/nixpkgs/issues/150818#issuecomment-1150863671.

**Comment by exarkun** [comment]
@FRidh is this meant to be open or closed?

**Comment by exarkun** [comment]
Ah sorry - I see that it was re-opened because of the confusion between pypy and pypy3 - sorry about the noise.

**Comment by exarkun** [comment]
> Until then this workaround seems reasonable to me. Maybe just include it in the next round of python-bumps.

Should this happen, then?

@wamserma

**Comment by wamserma** [comment]
@exarkun I guess it doesn't hurt. Feel free to pick it up.

**Pull request merged**
