### PR TITLE
invidious: 2.20240427 -> 2.20240825.2

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

- **invidious: switch to github repo**
  Actually, gitea is only a mirror. The main repo is the GitHub one.
- **invidious: 2.20240427 -> 2.20240825.2**

Changelog: https://github.com/iv-org/invidious/releases/tag/v2.20240825.2

The update script was not working for me and I had to tweak it manually for the correct version to be correctly picked up.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Okay, I really can't manage to get the script running.
It doesn't pick the right tag (see output with additional logging):
```
❮ ./pkgs/servers/invidious/update.sh
fetching https://github.com/iv-org/invidious.git...
From https://github.com/iv-org/invidious
 * branch              master     -> FETCH_HEAD
ALL TAGS:
b98152928c5e067cfe1e7430ed0149a0c4ac3e34	refs/tags/v2.20240427
3da53bc48498ad57ad6289763eecadf13cb38bba	refs/tags/v2.20240825
e75636b999abeef423b844c9775eaaaa6be926b0	refs/tags/v2.20240825.1
3cdaceccd0088aaafb68e26c73c4c84d0732ef68	refs/tags/0.1.0
76d3abb5f90dc513e30c996f0d11ba0f8c963bb8	refs/tags/0.2.0
45fa14838059d72e8a6eb2820a7bb6390a64055d	refs/tags/0.3.0
044a57ef344dc60f0511cbda080d4166f2a4220f	refs/tags/0.4.0
89bda1d3db9ff87799d1bf0a32cf8edbfd362b41	refs/tags/0.5.0
35bee987f60a12d3c246789e79c6012756577034	refs/tags/0.6.0
e122d68accebc448e08f02e4f9cc6872214c05e0	refs/tags/0.7.0
f8eb5ab4162a90b1bf4d3245d664c29dc80099f8	refs/tags/0.8.0
022427e20e5db73063f668ac78fad8987d3c94fb	refs/tags/0.9.0
57d88ffcc8e68aa3f057a37b94bbe5cef6c895cf	refs/tags/0.10.0
81ea2bf799742a2b93de3d75cc132c1290015e63	refs/tags/0.11.0
89439e1775039eb823ddc4a9acf01a996a05cc80	refs/tags/0.12.0
a16f967085415d7ddc2173be012fee783b4da6d9	refs/tags/0.13.0
138a6b11362257efc770f3d533c894ecf46802b3	refs/tags/0.13.1
699f85e773c7e69ac081c2361be3de89541accf5	refs/tags/0.14.0
09d0972ab45227be66e3e3a29934c3378dc6dc1f	refs/tags/0.14.1
a65998274fffd1334cf4d3d0f79a58e78b1b450e	refs/tags/0.15.0
8d5f9418297ac8b43540c571b466da82dd9fac0f	refs/tags/0.16.0
5e2889e776ca76263d0cad8fcf67d32d16e2317e	refs/tags/0.17.0
89725df3dc7e285adc5d3a80956f22265a858f6c	refs/tags/0.18.0
9e2a65a5ced2d2b79f4c3d01092013df1c1eb511	refs/tags/0.19.0
ff5d79e3ee1d295e97e589e39ca09bd0a880c99f	refs/tags/0.19.1
e56129111a5d182ddfcc75935c1222cc11e46234	refs/tags/0.20.0
05988c1c49851b7d0094fca16aeaf6382a7f64ab	refs/tags/0.20.1
eda7444ca46dbc3941205316baba8030fe0b2989	refs/tags/v2.20240427^{}
ffc70a5298bb4f954b2a8c607280d87882b7d6c7	refs/tags/v2.20240825^{}
3e17d04875570448edf42641175d297ec2ba2aa1	refs/tags/v2.20240825.1^{}

new_tag=v2.20240427
invidious is up-to-date.
```

We clearly see that the `v2.20240825.1` tag is indeed here, but the order is wrong.
Even if I force it, it doesn't work.

**Comment by 999eagle** [comment]
ah good catch! found the reason why the update script was broken and fixed it here: https://github.com/999eagle/nixpkgs/commit/d007ff800776ad8a9105c92843b50eb935592693

feel free to pull in that commit and run the script for this pr (this will also update the shards.nix file to match what is expected by invidious)

**Comment by GaetanLepage** [comment]
Thanks a lot @999eagle it seems to work great now !

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 337338` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>invidious</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 337338` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>invidious</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
@999eagle have you tried running it on your server ?

**Review by 999eagle — APPROVED** [review]
lgtm! maybe update the pr description to say `2.20240825.2` instead of `0.20240825.2` but apart from that it's fine

**Comment by GaetanLepage** [comment]
> lgtm! maybe update the pr description to say `2.20240825.2` instead of `0.20240825.2` but apart from that it's fine

Good catch, done.
I'll wait for ofborg and merge afterwards.

**Comment by GaetanLepage** [comment]
Would it actually be possible to backport this update to 24.05 ?

**Pull request merged**
