### PR TITLE
iosevka: 15.6.3 → 17.1.0

### PR DESCRIPTION
**Pull request by lunik1**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
We have three iosevka variants already. What does the one in `nodePackages` do?

```
27112:  iosevka = callPackage ../data/fonts/iosevka {};
27113:  iosevka-bin = callPackage ../data/fonts/iosevka/bin.nix {};
27114:  iosevka-comfy = recurseIntoAttrs (callPackages ../data/fonts/iosevka/comfy.nix {});
```

**Comment by mweinelt** [comment]
Also, if we do need the node package, can we build it using `buildNpmPackage` and drop it from `nodePackages` instead?

https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/javascript.section.md#buildnpmpackage-javascript-buildnpmpackage

**Comment by lunik1** [comment]
This package can be customised by overriding [`privateBuildPlan`](https://github.com/NixOS/nixpkgs/blob/nixos-22.11/pkgs/data/fonts/iosevka/default.nix#L7). I am not sure why it doesn't use `buildNpmPackage`, one for the maintainers?

**Comment by winterqt** [comment]
> I am not sure why it doesn't use `buildNpmPackage`, one for the maintainers?

It's just because nobody's converted it yet. Feel free to take a stab at it, and let me know if anything comes up.

**Pull request merged**
