### PR TITLE
python3Packages.django_silk: 4.1.0 -> 5.0.1

### PR DESCRIPTION
**Pull request by risicle**
###### Description of changes

Standard bumpage. Made the `checkPhase` a bit more correct.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by smancill** [comment]
The latest version is https://github.com/jazzband/django-silk/releases/tag/5.0.1

**Comment by risicle** [comment]
@ofborg build python39Packages.django_silk python310Packages.django_silk

@smancill congratulations, you've just volunteered to review this PR.

**Comment by smancill** [comment]
It fails for me on Darwin with sandbox enabled:

```
python3.10-django-silk> running install tests
python3.10-django-silk> /private/tmp/nix-build-python3.10-django-silk-5.0.1.drv-0/source/project /private/tmp/nix-build-python3.10-django-silk-5.0.1.drv-0/source
python3.10-django-silk> Traceback (most recent call last):
python3.10-django-silk>   File "/private/tmp/nix-build-python3.10-django-silk-5.0.1.drv-0/source/project/manage.py", line 11, in <module>
python3.10-django-silk>     execute_from_command_line(sys.argv)
python3.10-django-silk>   File "/nix/store/x93dmvasq9h27qn4mcijmm50lgvcpm9a-python3.10-django-3.2.14/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
python3.10-django-silk>     utility.execute()
python3.10-django-silk>   File "/nix/store/x93dmvasq9h27qn4mcijmm50lgvcpm9a-python3.10-django-3.2.14/lib/python3.10/site-packages/django/core/management/__init__.py", line 363, in execute
python3.10-django-silk>     settings.INSTALLED_APPS
python3.10-django-silk>   File "/nix/store/x93dmvasq9h27qn4mcijmm50lgvcpm9a-python3.10-django-3.2.14/lib/python3.10/site-packages/django/conf/__init__.py", line 82, in __getattr__
python3.10-django-silk>     self._setup(name)
python3.10-django-silk>   File "/nix/store/x93dmvasq9h27qn4mcijmm50lgvcpm9a-python3.10-django-3.2.14/lib/python3.10/site-packages/django/conf/__init__.py", line 69, in _setup
python3.10-django-silk>     self._wrapped = Settings(settings_module)
python3.10-django-silk>   File "/nix/store/x93dmvasq9h27qn4mcijmm50lgvcpm9a-python3.10-django-3.2.14/lib/python3.10/site-packages/django/conf/__init__.py", line 205, in __init__
python3.10-django-silk>     if zoneinfo_root.exists() and not zone_info_file.exists():
python3.10-django-silk>   File "/nix/store/76b5vjb1wkl7b38g8pazwv0p6pxmi53f-python3-3.10.5/lib/python3.10/pathlib.py", line 1290, in exists
python3.10-django-silk>     self.stat()
python3.10-django-silk>   File "/nix/store/76b5vjb1wkl7b38g8pazwv0p6pxmi53f-python3-3.10.5/lib/python3.10/pathlib.py", line 1097, in stat
python3.10-django-silk>     return self._accessor.stat(self, follow_symlinks=follow_symlinks)
python3.10-django-silk> PermissionError: [Errno 1] Operation not permitted: '/usr/share/zoneinfo'
```

It works when the sandbox is disabled.

**Comment by risicle** [comment]
Did it previously build for you with the darwin sandbox enabled?

**Comment by smancill** [comment]
I honestly was just browsing old, "forgotten" PRs to see what could be brought up to date, this looked like one.

The version 4.1.0 in master fails for a similar reason (sandbox enabled):

```
running install tests
Traceback (most recent call last):
  File "/private/tmp/nix-build-python3.10-django-silk-4.1.0.drv-0/source/project/manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/nix/store/x93dmvasq9h27qn4mcijmm50lgvcpm9a-python3.10-django-3.2.14/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/nix/store/x93dmvasq9h27qn4mcijmm50lgvcpm9a-python3.10-django-3.2.14/lib/python3.10/site-packages/django/core/management/__init__.py", line 363, in execute
    settings.INSTALLED_APPS
  File "/nix/store/x93dmvasq9h27qn4mcijmm50lgvcpm9a-python3.10-django-3.2.14/lib/python3.10/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/nix/store/x93dmvasq9h27qn4mcijmm50lgvcpm9a-python3.10-django-3.2.14/lib/python3.10/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/nix/store/x93dmvasq9h27qn4mcijmm50lgvcpm9a-python3.10-django-3.2.14/lib/python3.10/site-packages/django/conf/__init__.py", line 205, in __init__
    if zoneinfo_root.exists() and not zone_info_file.exists():
  File "/nix/store/76b5vjb1wkl7b38g8pazwv0p6pxmi53f-python3-3.10.5/lib/python3.10/pathlib.py", line 1290, in exists
    self.stat()
  File "/nix/store/76b5vjb1wkl7b38g8pazwv0p6pxmi53f-python3-3.10.5/lib/python3.10/pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
PermissionError: [Errno 1] Operation not permitted: '/usr/share/zoneinfo'
```

But it builds on Hydra: https://hydra.nixos.org/job/nixpkgs/trunk/python39Packages.django_silk.x86_64-darwin

**Comment by risicle** [comment]
The darwin sandbox is disabled on hydra.

**Comment by smancill** [comment]
I guess this is OK then and it will build on Hydra as it builds on my Macbook with sandbox disabled.

**Pull request merged**
