### PR TITLE
python312Packages.trx-python: init at 0.3; python312Packages.dipy: 1.7.0 -> 1.9.0

### PR DESCRIPTION
**Pull request by natsukium**
https://github.com/tee-ar-ex/trx-python

Diff: https://github.com/dipy/dipy/compare/refs/tags/1.7.0...1.9.0
Changelog: https://github.com/dipy/dipy/blob/1.9.0/Changelog

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [x] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 353282` at 747a8679 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/natsukium/3e74f6c7b39338259022a2f2cd4c8a03">python311Packages.dipy</a></li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 3 packages built:</summary>
  <ul>
    <li>python311Packages.trx-python</li>
    <li>python312Packages.dipy</li>
    <li>python312Packages.trx-python</li>
  </ul>
</details>

**Comment by natsukium** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 353282`

---
### `x86_64-linux`
<details>
  <summary>:x: 2 packages failed to build:</summary>
  <ul>
    <li>python311Packages.dipy</li>
    <li>python311Packages.dipy.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 6 packages built:</summary>
  <ul>
    <li>python311Packages.trx-python</li>
    <li>python311Packages.trx-python.dist</li>
    <li>python312Packages.dipy</li>
    <li>python312Packages.dipy.dist</li>
    <li>python312Packages.trx-python</li>
    <li>python312Packages.trx-python.dist</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:x: 2 packages failed to build:</summary>
  <ul>
    <li>python311Packages.dipy</li>
    <li>python311Packages.dipy.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 6 packages built:</summary>
  <ul>
    <li>python311Packages.trx-python</li>
    <li>python311Packages.trx-python.dist</li>
    <li>python312Packages.dipy</li>
    <li>python312Packages.dipy.dist</li>
    <li>python312Packages.trx-python</li>
    <li>python312Packages.trx-python.dist</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:x: 2 packages failed to build:</summary>
  <ul>
    <li>python311Packages.dipy</li>
    <li>python311Packages.dipy.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 6 packages built:</summary>
  <ul>
    <li>python311Packages.trx-python</li>
    <li>python311Packages.trx-python.dist</li>
    <li>python312Packages.dipy</li>
    <li>python312Packages.dipy.dist</li>
    <li>python312Packages.trx-python</li>
    <li>python312Packages.trx-python.dist</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:x: 2 packages failed to build:</summary>
  <ul>
    <li>python311Packages.dipy</li>
    <li>python311Packages.dipy.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 6 packages built:</summary>
  <ul>
    <li>python311Packages.trx-python</li>
    <li>python311Packages.trx-python.dist</li>
    <li>python312Packages.dipy</li>
    <li>python312Packages.dipy.dist</li>
    <li>python312Packages.trx-python</li>
    <li>python312Packages.trx-python.dist</li>
  </ul>
</details>

**Comment by bcdarwin** [comment]
Looks like `numpy` version just needs to be relaxed:

```
ERROR Missing dependencies:
	numpy==1.23.3; python_version == "3.11" and platform_python_implementation != "PyPy"
```

**Comment by natsukium** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 353282`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>python311Packages.dipy</li>
    <li>python311Packages.trx-python</li>
    <li>python312Packages.dipy</li>
    <li>python312Packages.trx-python</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>python311Packages.dipy</li>
    <li>python311Packages.trx-python</li>
    <li>python312Packages.dipy</li>
    <li>python312Packages.trx-python</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>python311Packages.dipy</li>
    <li>python311Packages.trx-python</li>
    <li>python312Packages.dipy</li>
    <li>python312Packages.trx-python</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>python311Packages.dipy</li>
    <li>python311Packages.trx-python</li>
    <li>python312Packages.dipy</li>
    <li>python312Packages.trx-python</li>
  </ul>
</details>

**Review by bcdarwin — APPROVED** [review]
LGTM.

**Pull request merged**
