### PR TITLE
xidlehook: 0.4.6 -> 0.4.8

### PR DESCRIPTION
**Pull request by jD91mZM2**
**This does not build yet.**
Blocked by #40356.

### CODE REVIEW

**Comment by xeji** [comment]
marking this as WIP, see above.

**Comment by jD91mZM2** [comment]
Should be possible now since we merged rustc 1.26.2

**Comment by xeji** [comment]
@GrahamcOfBorg  build xidlehook

**Comment by xeji** [comment]
@jD91mZM2 please have a look at the darwin failure.

**Comment by jD91mZM2** [comment]
Thank you, I will. Sorry for the delay.

**Comment by xeji** [comment]
Actually there's the `xquartz` X11 server for MacOS.

**Comment by xeji** [comment]
@GrahamcOfBorg build xidlehook

**Comment by jD91mZM2** [comment]
Hmm, how do you pass the cargoBuildFlags to testing?

**Comment by xeji** [comment]
According to https://github.com/NixOS/nixpkgs/blob/951d3cc4b90406ed760e9645c33a65b0577b3a78/pkgs/build-support/rust/default.nix#L82  `cargoBuildFlags` are ignored in `checkPhase`. Don't know if that's a bug or a feature. 
Anyway, you would probably have to override `checkPhase` and try to pass the flags to `cargo test` directly. Not idea if that would work though. Can't find anything similar in nixpkgs.

**Comment by jD91mZM2** [comment]
Sorry for being so late once again, had to head off to bed. Timezones suck. Disabled tests since I don't have any anyway

**Comment by xeji** [comment]
@GrahamcOfBorg build xidlehook

**Pull request merged**
