### PR TITLE
nixos/alacritty: init

### PR DESCRIPTION
**Pull request by figsoda**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
  - [x] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jansol** [comment]
I have nothing against an alacritty module but I'm curious, what is the motivation behind it?

**Comment by figsoda** [comment]
so It is easier to configure alacritty using nix

**Comment by SuperSandro2000** [comment]
> so It is easier to configure alacritty using nix

It is only adding alacrity to systemPackages and overcomplicating the following plain text setting. 

```
etc."xdg/alacritty/alacritty.yml".text = ''
'';
```

Right now the value of this is not very high and if we add more and more modules like this we run into the same trap home-manager is, that managing before simply things that were literally plain text become very complicated.

**Comment by figsoda** [comment]
I understand that this is very simple and wouldn't really hurt to configure without a module. But I don't see why this would be a problem, considering there are already so many modules that are even simpler than this:
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/bcc.nix
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/bash-my-aws.nix
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/file-roller.nix
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/haguichi.nix
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/xfconf.nix
and more

**Comment by jansol** [comment]
Arguably we should work to *remove* trivial modules like those.

What I could see being useful, however, is making it easier to manually write configs with the mechanism suggested by Sandro and highlight the method more in the docs.

Maybe a `.globalConfigFile` attribute could be introduced to package derivations where only a single simple configuration file is needed? Then it would be possible to do something like:
```nix
etc.${pkgs.alacritty.globalConfigFile}.text = generators.toYaml {
  font = {
    normal = {
      family = $preferredFontFamily;
      style = "Regular";
    };
    size = $preferredFontSize;
  };
};
```

Maybe even add a `.configGenerator` so the package can also ensure the right format gets generated.

**Comment by AndersonTorres** [comment]
I would argue that it looks more appropriate to Home Manager, since alacritty is a user program (I.E. needs no superuser privileges).

However, HM is not (yet) an official submodule of Nixpkgs monorepo.

**Comment by SuperSandro2000** [comment]
I think we can close this one because of the simplistic module it adds.

**Pull request closed without merging**
