### PR TITLE
pharo-vm: Refactor to introduce new VMs

### PR DESCRIPTION
**Pull request by DamienCassou**
The Pharo community now has a Spur VM: this VM is the only one to open Pharo50 images.

### CODE REVIEW

**Comment by vcunat** [comment]
It looks fine on a quick skim. I know nothing about the project, but you seem the only one really interested in it around here :-)

**Comment by DamienCassou** [comment]
@vcunat indeed. Thanks for your review anyway. My only problem right now is that both `pharo-vm` and `pharo-vm5` have `.so` files with the same name in `./lib`. So, they can't be installed in parallel and this is very important they can.

**Comment by vcunat** [comment]
They can be, if you set priorities. There should normally be no need to install `$out/lib` into the environments anyway...

**Comment by DamienCassou** [comment]
@vcunat how do I prevent libraries to get installed into the environments ?

**Comment by vcunat** [comment]
I think `nix-env` always installs whole output paths. Maybe splitting into multiple outputs would help this; I'm not certain. NixOS's `systemPackages` do not link `lib` by default.

**Comment by DamienCassou** [comment]
What about putting .so files in `$out/lib/<derivation-name>/`

**Comment by vcunat** [comment]
You could do that, for this particular package.

**Comment by DamienCassou** [comment]
@vcunat By the way, what happened with my commit? Why is the PR in an "unmerged" state?

**Comment by vcunat** [comment]
I cherry-picked the commit. I find it superfluous to generate one extra merge commit just to include a single commit. Github then shows the PR as closed/unmerged.

**Pull request closed without merging**
