### PR TITLE
intel-gmmlib: 21.3.3 -> 22.0.1, intel-media-driver: 21.4.3 -> 22.1.0

### PR DESCRIPTION
**Pull request by primeos**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by primeos** [comment]
Oops, nixpkgs-review isn't successful:
```
error: builder for '/nix/store/ivf1ypflh4hlljk857gjm033hcgb9v3c-intel-media-driver-21.4.3.drv' failed with exit code 2;
       last 10 log lines:
       > [ 70%] Building CXX object media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/linux/common/ddi/media_libva_common.cpp.o
       > /build/source/media_driver/linux/common/ddi/media_libva.cpp: In function 'VAStatus DdiMedia_InitMediaContext(VADriverContextP, int32_t, int32_t*, int32_t*, bool)':
       > /build/source/media_driver/linux/common/ddi/media_libva.cpp:1884:32: error: 'OpenGmm' was not declared in this scope
       >  1884 |         GMM_STATUS gmmStatus = OpenGmm(&mediaCtx->GmmFuncs);
       >       |                                ^~~~~~~
       > [ 70%] Building CXX object media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/linux/common/ddi/media_libva_util.cpp.o
       > make[2]: *** [media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/build.make:8112: media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/linux/common/ddi/media_libva.cpp.o] Error 1
       > make[2]: *** Waiting for unfinished jobs....
       > make[1]: *** [CMakeFiles/Makefile2:247: media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/all] Error 2
       > make: *** [Makefile:156: all] Error 2
       For full logs, run 'nix log /nix/store/ivf1ypflh4hlljk857gjm033hcgb9v3c-intel-media-driver-21.4.3.drv'.
error: 1 dependencies of derivation '/nix/store/dirvjghx0sbsh3kc4diwd4kwvlpydf73-review-shell.drv' failed to build
1 package failed to build:
intel-media-driver
```

**Comment by primeos** [comment]
I've notified upstream, let's see what happens:
- https://github.com/intel/gmmlib/issues/93
- https://github.com/intel/media-driver/issues/1311

**Comment by SuperSandro2000** [comment]
Will be fixed by https://github.com/intel/media-driver/commit/42ffd7983a32b75cf8403c235d8d0f727191390c in the next media-driver release.

**Comment by primeos** [comment]
```
3 packages updated:
intel-compute-runtime intel-gmmlib (21.3.3 → 22.0.1) intel-media-driver (21.4.3 → 22.1.0)

$ nix --experimental-features nix-command build --no-link --keep-going --option build-use-sandbox relaxed -f /home/michael/.cache/nixpkgs-review/rev-0fae01ba176c58c5f85a5693c04aa99951540a2b/build.nix
3 packages built:
intel-compute-runtime intel-gmmlib intel-media-driver
```

**Pull request merged**
