### PR TITLE
wpa_supplicant: use unique IDs for networks and credentials

### PR DESCRIPTION
**Pull request by ncfavier**
Fixes the bug described at https://github.com/NixOS/nixpkgs/pull/155266#issuecomment-1031711094

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ncfavier** [comment]
Sent the patch [upstream](http://lists.infradead.org/pipermail/hostap/2022-February/040210.html)

**Comment by ncfavier** [comment]
@ofborg test wpa_supplicant

**Comment by ncfavier** [comment]
friendly ping @Ma27

**Comment by Ma27** [comment]
Trying to take a look this weekend :)

**Review by Ma27 — COMMENTED** [review]
Applied this to my tracking branch and rebuilt my system with this. While everything seems to work fine, `wpa_cli list_networks` (and also `wpa_gui`) list each declaratively configured SSID twice when using `allowAuxiliaryImperativeNetworks = true;`.

also cc @rnhmjoj

**Comment by ncfavier** [comment]
That seems to be caused by `networking.wireless.fallbackToWPA2`. Shouldn't be a problem but you can set that to `false` if you don't need it.

**Comment by ncfavier** [comment]
Wait, did you not observe that before applying this change?

**Comment by Ma27** [comment]
> Wait, did you not observe that before applying this change?

Oh damn you're absolutely right :facepalm: 

And yes, I have to admit I didn't take a close look at the list *before* testing your patch, so sorry for the noise!

**Review by Ma27 — APPROVED** [review]
:+1: from me, I'd still like to wait for a moment to give @rnhmjoj a chance to review, but I'd merge next week %)

**Comment by rnhmjoj** [comment]
> That seems to be caused by networking.wireless.fallbackToWPA2. 

Yes, that's it: that options generates multiple `network` blocks for the same network, so the networks will appear duplicated.

I took a look at the commit @ncfavier mentioned and I think I see the problem.
I'm not very keen on patching software before upstream accepts it, but this seem critical and the fix simple enough.

**Review by rnhmjoj — APPROVED** [review]

**Comment by Ma27** [comment]
Two approvals and my wpa_supplicant works perfectly fine with this change -> merging!

Thanks @ncfavier !

**Pull request merged**
