### PR TITLE
tarsnap module: add options for controlling bandwidth

### PR DESCRIPTION
**Pull request by joachifm**
@thoughtpolice

### CODE REVIEW

**Comment by lethalman** [comment]
Wasn't an extraConfig enough?

**Comment by joachifm** [comment]
It's a matter of discoverability, IMO. You can do everything with extraConfig, after all, seeing as all the options are trivial mappings. Bandwidth options are special, though, because you're charged by the byte.

**Comment by thoughtpolice** [comment]
lgtm!

**Comment by thoughtpolice** [comment]
Also, tarsnap is simple enough we could conceivably give it all the options. It's not like there's a huge amount of flexibility with how it works...

**Pull request merged**
