### PR TITLE
dosbox: Replace patch from bugzilla with local analog

### PR DESCRIPTION
**Pull request by avnik**
I am not sure it it exactly same one, due patch link to bugzilla
are dead. I take this one from gentoo.

### CODE REVIEW

**Comment by globin** [comment]
I'm not sure which we prefer but AFAIR external persistent patches are preferred, but nonetheless you forget to add the patch :wink:

**Comment by avnik** [comment]
@globin fixed ;)
Old bugzilla link was too unstable.
I am just not so familiar with gentoo to refer patch in their tree

**Comment by avnik** [comment]
Looked again on source link, just something changed inside gentoo ;)
But if this change permanent -- it can affect other packages which refer gentoo viewcvs

**Comment by vcunat** [comment]
It's not bugzilla, it's directly from gentoo sources, and the URL works (again). I expect it was only a temporary blackout.

**Comment by avnik** [comment]
On Mon, Feb 08, 2016 at 01:14:39PM -0800, Vladimír Čunát wrote:
> It's not bugzilla, it's directly from gentoo sources, and the URL works (again). I expect it was only a temporary blackout.
> 

You can close PR if so.

btw have we more reliable mirror of gentoo source tree
(for example on github?)

**Comment by vcunat** [comment]
Maybe https://gitweb.gentoo.org/repo/gentoo.git/tree/ is a better source. It *looks* better and newer at least.

**Comment by vcunat** [comment]
Ah, yes, right. The files in CVS won't be updated anymore, so we should use git or gitweb now. https://gentoo.org/news/2015/08/12/git-migration.html

**Comment by vcunat** [comment]
Hmm, maybe we should wait a bit:

> Options to fetch the package tree via Git are to be announced later.

**Comment by vcunat** [comment]
... but that gitweb link should be safe to switch and we prefer to avoid git for fetches anyway.

**Comment by zimbatm** [comment]
Closing until it becomes an issue again

**Pull request closed without merging**
