### PR TITLE
xp-pen-deco-01-v2-driver: 3.2.3.230215-1 -> 3.4.9-231023

### LINKED ISSUE #266416: `libsForQt5.xp-pen-deco-01-v2-driver` src url wrong
### Describe the bug
Attempting to install libsForQt5.xp-pen-deco-01-v2-driver gives error:

curl: (22) The requested URL returned error: 404
error: cannot download xp-pen-deco-01-v2-driver-3.2.3.230215-1.tar.gz from any mirror

### Steps To Reproduce
1. either modify /etc/nixos/configuration.nix to add the named package or do "nix-shell -p libsForQt5.xp-pen-deco-01-v2-driver" in terminal

### Expected behavior
Package installs sucessfully.

### Screenshots
Screenshot_20231109_155706

### Additional context
I could be wrong, but it seems that the download link for the xp pen tablet driver was changed by xp pen upstream, and the link used here is now invalid.

### Notify maintainers

 @virchau13 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

``
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.61, NixOS, 23.11 (Tapir), 23.11pre544052.85f1ba3e5167`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

### PR DESCRIPTION
**Pull request by AlephNought0**
## Description of changes

I have noticed that the xp pen driver package for deco 01 v2 drawing tablets had an incorrect link. I also found out that the executable name was changed in the newest package too and so I have made these changes that can be visible in the commit. This is actually my first pull request and I am not 100% sure if I am doing everything correctly. I'd appreciate some feedback!

Fixes #266416

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by MikaelFangel** [comment]
Thank you for your contribution. A quick note (:

Your commit should have the message:
```
xp-pen-deco-01-v2-driver: 3.2.3.230215-1 -> 3.4.9-231023
```

and you should target the master branch not nixos-unstable (:

**Comment by MikaelFangel** [comment]
Fixes: #266416

**Comment by RadovanSk** [comment]
> Thank you for your contribution. A quick note (:
> 
> Your commit should have the message:
> 
> ```
> xp-pen-deco-01-v2-driver: 3.2.3.230215-1 -> 3.4.9-231023
> ```
> 
> and you should target the master branch not nixos-unstable (:

Oh I see. Is there a way for me to change this or do I need to make a new pull request in the master branch?

**Comment by MikaelFangel** [comment]
Use `git rebase -i HEAD~n` where n is the commits you'll rebase and then force push the result.

**Comment by RadovanSk** [comment]
> Use `git rebase -i HEAD~n` where n is the commits you'll rebase and then force push the result.

Alright, I managed to do it.

**Comment by MikaelFangel** [comment]
Okay and now you need to change the target branch of the PR to master (:

**Comment by RadovanSk** [comment]
> Okay and now you need to change the target branch of the PR to master (:

Oh wow, that was simpler than I thought! Thank you a lot for explaining to me how to do pull requests more properly!

**Review by virchau13 — APPROVED** [review]
LGTM. Hopefully XP Pen doesn't change their install format again.

**Comment by altsalt** [comment]
It is probably worth noting that there is another effort to combine the XP-Pen drivers going on in #213263

**Comment by MeshVoid** [comment]
Is this fixed? I'm still getting errors trying to build the package... ((

**Comment by RadovanSk** [comment]
> Is this fixed? I'm still getting errors trying to build the package... ((

The pull request has not been merged yet. So unless you use overlays or overrideAttrs you still can't use xp pen drivers unfortunately.

**Comment by Atemu** [comment]
@virchau13 did you test this to be working with the hardware?

**Comment by MeshVoid** [comment]
Hi there! I just built a separate boot profile to test the drivers by running **nixos-rebuild boot --profile test-pentablet -I nixpkgs=https://github.com/RadovanSk/nixpkgs-updates/archive/refs/heads/nixos-unstable.zip**. And they work perfectly, everything works as I remember, all the options are there, pen sensitivity, tilt functions hotkeying of buttons on both pen and tablet are working as intended!

Screenshot from 2024-03-12 03-18-37

Screenshot from 2024-03-12 03-19-02

**Pull request merged**
