### PR TITLE
astroid: 0.11.1 -> 0.13

### PR DESCRIPTION
**Pull request by yrashk**
Couple of things were updated to make this work.

1. webkitgtk24x-gtk3 that is marked unsafe has been replaced with
   webkitgtk (2.20.*) as astroid has recently indicated that [>= 2.20
   is
   acceptable](https://github.com/astroidmail/astroid/commit/48ce7e3010d2ee99ccba18798b4f5333867bd1a2)
2. protobuf built input was added to satisfy requirements
3. astroid was not functional at all without proper icons so gnome3.defaultIconTheme
   were added to buildInputs
4. By default, astroid will use `gvim` as a setting for the embedded
   editor, however that didn't work well with nixpkgs. vim is now
   bundled with astroid by default. This setting can be overridden
   by the user in astroid's config file.

###### Motivation for this change

Astroid 0.11.1 is outdated

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg  build astroid

**Comment by yrashk** [comment]
Turns out there's still a problem with email composition, it loses the body of the message. Trying to figure out if this is Nixpkgs-related or not.

**Comment by teto** [comment]
Really happy to see a PR but can't we make the vim dependency optional ? astroid can be used with any editor last time I tried.

**Comment by yrashk** [comment]
@teto it can be, indeed -- I just wanted to include it because without it, by default, astroid won't be functional. Should I make it optional but enabled by default?

**Comment by yrashk** [comment]
I've updated this PR to make `vim` optional at a build time (enabled by default).

Also, the issue with composition feature is only happening in certain configurations, and is not Nixpkgs-specific. It's been acknowledged and is being worked on https://github.com/astroidmail/astroid/issues/532. It only affects some users.

**Comment by teto** [comment]
I could build it locally but it crashed on startup
```
[2018-08-09 11:44:09.865693] [0x00007ffb98896a00] [info]    cf: loading: "/home/teto/.config/astroid/config"
[2018-08-09 11:44:09.865723] [0x00007ffb98896a00] [warning] cf: making runtime dir..
[2018-08-09 11:44:09.866115] [0x00007ffb98896a00] [info]    cf: version: 11
[2018-08-09 11:44:09.866211] [0x00007ffb98896a00] [debug]   cf: check config..
[2018-08-09 11:44:09.866225] [0x00007ffb98896a00] [error]   cf: the config file is an old version (9), the current version is: 11
[2018-08-09 11:44:09.866229] [0x00007ffb98896a00] [warning] cf: missing values in config have been updated with defaults (old version: 9, new: 11)
[11:44:09] [0x00007ffb98896a00] [M] [info] welcome to astroid! - 0.13.0
[11:44:09] [0x00007ffb98896a00] [M] [info] date: init.
[11:44:09] [0x00007ffb98896a00] [M] [info] db path: /home/teto/Maildir
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::property_tree::ptree_bad_data> >'
  what():  conversion of data to type "b" failed
zsh: abort      result/bin/astroid

```
anyway, I am still reluctant in having vim as a default dependency. Can't astroid use the value of EDITOR instead ? in worst case, it won't launch the editor and print a warning. If you insist in having nix manage the configuration, I recommand to look at the new home-manager infrastructure for mails, some cool stuff is happening https://github.com/rycee/home-manager/pull/318
If https://github.com/rycee/home-manager/pull/318

**Comment by yrashk** [comment]
Not sure about the crash, I think this one is worth reporting in the astroid repo. 

As for EDITOR, we can make a patch for that, but it won't help with all the arguments it is passing to gvim. If we just switch this to EDITOR, I believe, often times, the end-user will be getting a mail client that can't compose e-mails at all. 

What are the main concerns about using vim by default to support astroid's default configuration? It can be turned off or replaced with a different dependency if the user wishes so.

**Comment by yrashk** [comment]
Nix doesn't manage the configuration per se in this case, but just sets *working* defaults for astroid to produce when the few configuration file is produced.

If this concern is a roadblock, I can, of course, remove this dependency altogether (or disable it by default), but I think it'll make it for a much more confusing initial experience ("why does e-mail composition not work?")

**Comment by tkerber** [comment]
I don't see that much of an issue with vim being a default dependency, and I do think there is value in having functional default behaviour. One thing I'm not sure about is the specific version of vim? I'd also note that EDITOR is often set to a terminal-only editor, in which case it's non-trivial to have sensible behaviour, as it would have to a) decide if EDITOR is graphical or not, and b) if not, decide which terminal emulator to launch it in.

If this continues to be a concern, then maybe split the PR into a version update and adding vim as a dependency, so that at least the security-critical update can be used?

**Comment by teto** [comment]
I am no nixpkgs maintainer so feel free to ignore my comments :) My
experience with nixpkgs is that maintainers do pay attention to closure
size and while vim isn't huge it's not light either (also depends which
one, if you pull gvim then ouch)

I don't use vim but if changing the astroid package would imply recompiling
it and it's something I would rather avoid for this kind of medium-sized
application.

For people using vim, vim would be in PATH most likely so it should work
out of the box, for the others they would change the setting anyway.
Astroid needs a fair bit of configuration anyway (notmuch, poll mechanisms
etc) so I am not too concerned about the out of the box experience. It
would be realy improved with home-manager integration.

I've said too much, let's hope a nixos member chimes in.

2018-08-09 19:52 GMT+09:00 Thomas Kerber <notifications@github.com>:

**Comment by yrashk** [comment]
what is the best way to reach a resolution on this issue?

**Comment by yrashk** [comment]
What should I do with this PR?

**Pull request merged**
