### PR TITLE
Add Apache Pulsar

### PR DESCRIPTION
**Pull request by samdroid-apps**
###### Motivation for this change

This PR adds support for the Apache Pulsar message bus in NixOS.  Running Pulsar involves 3 components - the Zookeeper, the Bookkeeper Bookie and the Pulsar Broker.  All component are distributed by Apache Pulsar together.

This PR:

* Adding the `pulsar` package (containing the official distribution of zookeeper, bookie and broker)
* Adds the `services.pulsar` module, made up of a zookeeper, bookie and broker systemd service
* Adds 2 nixos tests for common configurations:
  * A single-node setup, where zookeeper, bookie and broker run on the same machine
  * A more complex multi-node setup, with two bookkeepers (for data integrity) and all services on components machines

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aahmed-se** [comment]
will close since you are picking up the task https://github.com/NixOS/nixpkgs/pull/65324

**Comment by jlesquembre** [comment]
Is there a reason for this PR to be staled? It seems ready. Other than fixing the merge conflicts, and bumping the version, is there anything to be done? 

It'd be nice to have Pulsar on nixpkgs. I see more people are interested in that, there were other PRs to add Pulsar: 
https://github.com/NixOS/nixpkgs/pull/92393
https://github.com/NixOS/nixpkgs/pull/65324

@samdroid-apps @lucperkins @aahmed-se Are you still interested in getting this merged? If not, I could try to finish the work and get it merged.

**Comment by aahmed-se** [comment]
Please update and finish it , overall it looks fine to me.

**Comment by AndersonTorres** [comment]
Closing as abandoned

**Pull request closed without merging**
