### PR TITLE
virtualbox: 7.0.6 -> 7.0.8; fix kernel 6.3 module

### PR DESCRIPTION
**Pull request by erdnaxe**
###### Description of changes

Update virtualbox to 7.0.8.

Fixes compatibility with kernel 6.3.

Virtualbox now requires SDL2, but there is some issues with `configure` that still searchs for SDL1 (hence `fix-sdl.patch`).

ZHF: https://github.com/NixOS/nixpkgs/issues/230712

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by erdnaxe** [comment]
Result of `nixpkgs-review pr 232770` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>linuxKernel.packages.linux_5_4_hardened.virtualbox</li>
    <li>linuxKernel.packages.linux_5_4_hardened.virtualboxGuestAdditions</li>
  </ul>
</details>
<details>
  <summary>49 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_4_14.virtualbox</li>
    <li>linuxKernel.packages.linux_4_14.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_4_14_hardened.virtualbox</li>
    <li>linuxKernel.packages.linux_4_14_hardened.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_4_19.virtualbox</li>
    <li>linuxKernel.packages.linux_4_19.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_4_19_hardened.virtualbox</li>
    <li>linuxKernel.packages.linux_4_19_hardened.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_5_10.virtualbox</li>
    <li>linuxKernel.packages.linux_5_10.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_5_10_hardened.virtualbox</li>
    <li>linuxKernel.packages.linux_5_10_hardened.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_5_15.virtualbox</li>
    <li>linuxKernel.packages.linux_5_15.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_5_15_hardened.virtualbox</li>
    <li>linuxKernel.packages.linux_5_15_hardened.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_5_4.virtualbox</li>
    <li>linuxKernel.packages.linux_5_4.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_6_1.virtualbox</li>
    <li>linuxKernel.packages.linux_6_1.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_hardened.virtualbox (linuxKernel.packages.linux_6_1_hardened.virtualbox)</li>
    <li>linuxKernel.packages.linux_hardened.virtualboxGuestAdditions (linuxKernel.packages.linux_6_1_hardened.virtualboxGuestAdditions)</li>
    <li>linuxKernel.packages.linux_6_2.virtualbox</li>
    <li>linuxKernel.packages.linux_6_2.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_6_3.virtualbox</li>
    <li>linuxKernel.packages.linux_6_3.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_latest_libre.virtualbox</li>
    <li>linuxKernel.packages.linux_latest_libre.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_libre.virtualbox</li>
    <li>linuxKernel.packages.linux_libre.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_lqx.virtualbox</li>
    <li>linuxKernel.packages.linux_lqx.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.virtualbox</li>
    <li>linuxKernel.packages.linux_testing_bcachefs.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_xanmod.virtualbox</li>
    <li>linuxKernel.packages.linux_xanmod.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_xanmod_latest.virtualbox (linuxKernel.packages.linux_xanmod_stable.virtualbox)</li>
    <li>linuxKernel.packages.linux_xanmod_latest.virtualboxGuestAdditions (linuxKernel.packages.linux_xanmod_stable.virtualboxGuestAdditions)</li>
    <li>linuxKernel.packages.linux_zen.virtualbox</li>
    <li>linuxKernel.packages.linux_zen.virtualboxGuestAdditions</li>
    <li>virtualbox</li>
    <li>virtualbox.modsrc</li>
    <li>virtualboxExtpack</li>
    <li>virtualboxHardened</li>
    <li>virtualboxHardened.modsrc</li>
    <li>virtualboxHeadless</li>
    <li>virtualboxHeadless.modsrc</li>
    <li>virtualboxWithExtpack</li>
    <li>virtualboxWithExtpack.modsrc</li>
  </ul>
</details>

**Comment by erdnaxe** [comment]
nixosTests.virtualbox works fine

**Comment by RaitoBezarius** [comment]
This is failing eval for me.

**Comment by RaitoBezarius** [comment]
We will grab this during beta.

**Comment by aviallon** [comment]
@erdnaxe I was just writing the same patch. Thanks ;)

**Comment by aviallon** [comment]
@svanderburg @cdepillabout is there anything blocking it from being merged?

**Comment by RaitoBezarius** [comment]
> @svanderburg @cdepillabout is there anything blocking it from being merged?

I am working on it.

**Comment by RaitoBezarius** [comment]
Result of `nixpkgs-review pr 232770` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>18 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.hardkernel_4_14.virtualbox</li>
    <li>linuxKernel.packages.hardkernel_4_14.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_4_14_hardened.virtualbox</li>
    <li>linuxKernel.packages.linux_4_14_hardened.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_4_19_hardened.virtualbox</li>
    <li>linuxKernel.packages.linux_4_19_hardened.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_5_4_hardened.virtualbox</li>
    <li>linuxKernel.packages.linux_5_4_hardened.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_6_2.virtualbox</li>
    <li>linuxKernel.packages.linux_6_2.virtualboxGuestAdditions</li>
    <li>linuxPackages_4_14_hardened.virtualbox</li>
    <li>linuxPackages_4_14_hardened.virtualboxGuestAdditions</li>
    <li>linuxPackages_4_19_hardened.virtualbox</li>
    <li>linuxPackages_4_19_hardened.virtualboxGuestAdditions</li>
    <li>linuxPackages_5_4_hardened.virtualbox</li>
    <li>linuxPackages_5_4_hardened.virtualboxGuestAdditions</li>
    <li>linuxPackages_hardkernel_latest.virtualbox</li>
    <li>linuxPackages_hardkernel_latest.virtualboxGuestAdditions</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>virtualboxWithExtpack</li>
    <li>virtualboxWithExtpack.modsrc</li>
  </ul>
</details>
<details>
  <summary>41 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_4_14.virtualbox</li>
    <li>linuxKernel.packages.linux_4_14.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_4_19.virtualbox</li>
    <li>linuxKernel.packages.linux_4_19.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_5_10.virtualbox</li>
    <li>linuxKernel.packages.linux_5_10.virtualboxGuestAdditions</li>
    <li>linuxPackages_5_10_hardened.virtualbox (linuxKernel.packages.linux_5_10_hardened.virtualbox)</li>
    <li>linuxPackages_5_10_hardened.virtualboxGuestAdditions (linuxKernel.packages.linux_5_10_hardened.virtualboxGuestAdditions)</li>
    <li>linuxKernel.packages.linux_5_15.virtualbox</li>
    <li>linuxKernel.packages.linux_5_15.virtualboxGuestAdditions</li>
    <li>linuxPackages_5_15_hardened.virtualbox (linuxKernel.packages.linux_5_15_hardened.virtualbox)</li>
    <li>linuxPackages_5_15_hardened.virtualboxGuestAdditions (linuxKernel.packages.linux_5_15_hardened.virtualboxGuestAdditions)</li>
    <li>linuxKernel.packages.linux_5_4.virtualbox</li>
    <li>linuxKernel.packages.linux_5_4.virtualboxGuestAdditions</li>
    <li>linuxPackages.virtualbox (linuxKernel.packages.linux_6_1.virtualbox)</li>
    <li>linuxPackages.virtualboxGuestAdditions (linuxKernel.packages.linux_6_1.virtualboxGuestAdditions)</li>
    <li>linuxPackages_hardened.virtualbox (linuxPackages_6_1_hardened.virtualbox)</li>
    <li>linuxPackages_hardened.virtualboxGuestAdditions (linuxPackages_6_1_hardened.virtualboxGuestAdditions)</li>
    <li>linuxPackages_latest.virtualbox (linuxKernel.packages.linux_6_3.virtualbox)</li>
    <li>linuxPackages_latest.virtualboxGuestAdditions (linuxKernel.packages.linux_6_3.virtualboxGuestAdditions)</li>
    <li>linuxPackages_latest-libre.virtualbox (linuxKernel.packages.linux_latest_libre.virtualbox)</li>
    <li>linuxPackages_latest-libre.virtualboxGuestAdditions (linuxKernel.packages.linux_latest_libre.virtualboxGuestAdditions)</li>
    <li>linuxPackages-libre.virtualbox (linuxKernel.packages.linux_libre.virtualbox)</li>
    <li>linuxPackages-libre.virtualboxGuestAdditions (linuxKernel.packages.linux_libre.virtualboxGuestAdditions)</li>
    <li>linuxPackages_lqx.virtualbox (linuxKernel.packages.linux_lqx.virtualbox)</li>
    <li>linuxPackages_lqx.virtualboxGuestAdditions (linuxKernel.packages.linux_lqx.virtualboxGuestAdditions)</li>
    <li>linuxPackages_testing_bcachefs.virtualbox (linuxKernel.packages.linux_testing_bcachefs.virtualbox)</li>
    <li>linuxPackages_testing_bcachefs.virtualboxGuestAdditions (linuxKernel.packages.linux_testing_bcachefs.virtualboxGuestAdditions)</li>
    <li>linuxPackages_xanmod.virtualbox (linuxKernel.packages.linux_xanmod.virtualbox)</li>
    <li>linuxPackages_xanmod.virtualboxGuestAdditions (linuxKernel.packages.linux_xanmod.virtualboxGuestAdditions)</li>
    <li>linuxPackages_xanmod_latest.virtualbox (linuxKernel.packages.linux_xanmod_latest.virtualbox ,linuxPackages_xanmod_stable.virtualbox)</li>
    <li>linuxPackages_xanmod_latest.virtualboxGuestAdditions (linuxKernel.packages.linux_xanmod_latest.virtualboxGuestAdditions ,linuxPackages_xanmod_stable.virtualboxGuestAdditions)</li>
    <li>linuxPackages_zen.virtualbox (linuxKernel.packages.linux_zen.virtualbox)</li>
    <li>linuxPackages_zen.virtualboxGuestAdditions (linuxKernel.packages.linux_zen.virtualboxGuestAdditions)</li>
    <li>virtualbox</li>
    <li>virtualbox.modsrc</li>
    <li>virtualboxExtpack</li>
    <li>virtualboxHardened</li>
    <li>virtualboxHardened.modsrc</li>
    <li>virtualboxHeadless</li>
    <li>virtualboxHeadless.modsrc</li>
  </ul>
</details>

**Comment by RaitoBezarius** [comment]
Result of `nixpkgs-review pr 232770` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>18 packages marked as broken and skipped:</summary>
  <ul>
    <li>linuxKernel.packages.hardkernel_4_14.virtualbox</li>
    <li>linuxKernel.packages.hardkernel_4_14.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_4_14_hardened.virtualbox</li>
    <li>linuxKernel.packages.linux_4_14_hardened.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_4_19_hardened.virtualbox</li>
    <li>linuxKernel.packages.linux_4_19_hardened.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_5_4_hardened.virtualbox</li>
    <li>linuxKernel.packages.linux_5_4_hardened.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_6_2.virtualbox</li>
    <li>linuxKernel.packages.linux_6_2.virtualboxGuestAdditions</li>
    <li>linuxPackages_4_14_hardened.virtualbox</li>
    <li>linuxPackages_4_14_hardened.virtualboxGuestAdditions</li>
    <li>linuxPackages_4_19_hardened.virtualbox</li>
    <li>linuxPackages_4_19_hardened.virtualboxGuestAdditions</li>
    <li>linuxPackages_5_4_hardened.virtualbox</li>
    <li>linuxPackages_5_4_hardened.virtualboxGuestAdditions</li>
    <li>linuxPackages_hardkernel_latest.virtualbox</li>
    <li>linuxPackages_hardkernel_latest.virtualboxGuestAdditions</li>
  </ul>
</details>
<details>
  <summary>43 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_4_14.virtualbox</li>
    <li>linuxKernel.packages.linux_4_14.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_4_19.virtualbox</li>
    <li>linuxKernel.packages.linux_4_19.virtualboxGuestAdditions</li>
    <li>linuxKernel.packages.linux_5_10.virtualbox</li>
    <li>linuxKernel.packages.linux_5_10.virtualboxGuestAdditions</li>
    <li>linuxPackages_5_10_hardened.virtualbox (linuxKernel.packages.linux_5_10_hardened.virtualbox)</li>
    <li>linuxPackages_5_10_hardened.virtualboxGuestAdditions (linuxKernel.packages.linux_5_10_hardened.virtualboxGuestAdditions)</li>
    <li>linuxKernel.packages.linux_5_15.virtualbox</li>
    <li>linuxKernel.packages.linux_5_15.virtualboxGuestAdditions</li>
    <li>linuxPackages_5_15_hardened.virtualbox (linuxKernel.packages.linux_5_15_hardened.virtualbox)</li>
    <li>linuxPackages_5_15_hardened.virtualboxGuestAdditions (linuxKernel.packages.linux_5_15_hardened.virtualboxGuestAdditions)</li>
    <li>linuxKernel.packages.linux_5_4.virtualbox</li>
    <li>linuxKernel.packages.linux_5_4.virtualboxGuestAdditions</li>
    <li>linuxPackages.virtualbox (linuxKernel.packages.linux_6_1.virtualbox)</li>
    <li>linuxPackages.virtualboxGuestAdditions (linuxKernel.packages.linux_6_1.virtualboxGuestAdditions)</li>
    <li>linuxPackages_hardened.virtualbox (linuxPackages_6_1_hardened.virtualbox)</li>
    <li>linuxPackages_hardened.virtualboxGuestAdditions (linuxPackages_6_1_hardened.virtualboxGuestAdditions)</li>
    <li>linuxPackages_latest.virtualbox (linuxKernel.packages.linux_6_3.virtualbox)</li>
    <li>linuxPackages_latest.virtualboxGuestAdditions (linuxKernel.packages.linux_6_3.virtualboxGuestAdditions)</li>
    <li>linuxPackages_latest-libre.virtualbox (linuxKernel.packages.linux_latest_libre.virtualbox)</li>
    <li>linuxPackages_latest-libre.virtualboxGuestAdditions (linuxKernel.packages.linux_latest_libre.virtualboxGuestAdditions)</li>
    <li>linuxPackages-libre.virtualbox (linuxKernel.packages.linux_libre.virtualbox)</li>
    <li>linuxPackages-libre.virtualboxGuestAdditions (linuxKernel.packages.linux_libre.virtualboxGuestAdditions)</li>
    <li>linuxPackages_lqx.virtualbox (linuxKernel.packages.linux_lqx.virtualbox)</li>
    <li>linuxPackages_lqx.virtualboxGuestAdditions (linuxKernel.packages.linux_lqx.virtualboxGuestAdditions)</li>
    <li>linuxPackages_testing_bcachefs.virtualbox (linuxKernel.packages.linux_testing_bcachefs.virtualbox)</li>
    <li>linuxPackages_testing_bcachefs.virtualboxGuestAdditions (linuxKernel.packages.linux_testing_bcachefs.virtualboxGuestAdditions)</li>
    <li>linuxPackages_xanmod.virtualbox (linuxKernel.packages.linux_xanmod.virtualbox)</li>
    <li>linuxPackages_xanmod.virtualboxGuestAdditions (linuxKernel.packages.linux_xanmod.virtualboxGuestAdditions)</li>
    <li>linuxPackages_xanmod_latest.virtualbox (linuxKernel.packages.linux_xanmod_latest.virtualbox ,linuxPackages_xanmod_stable.virtualbox)</li>
    <li>linuxPackages_xanmod_latest.virtualboxGuestAdditions (linuxKernel.packages.linux_xanmod_latest.virtualboxGuestAdditions ,linuxPackages_xanmod_stable.virtualboxGuestAdditions)</li>
    <li>linuxPackages_zen.virtualbox (linuxKernel.packages.linux_zen.virtualbox)</li>
    <li>linuxPackages_zen.virtualboxGuestAdditions (linuxKernel.packages.linux_zen.virtualboxGuestAdditions)</li>
    <li>virtualbox</li>
    <li>virtualbox.modsrc</li>
    <li>virtualboxExtpack</li>
    <li>virtualboxHardened</li>
    <li>virtualboxHardened.modsrc</li>
    <li>virtualboxHeadless</li>
    <li>virtualboxHeadless.modsrc</li>
    <li>virtualboxWithExtpack</li>
    <li>virtualboxWithExtpack.modsrc</li>
  </ul>
</details>

**Review by RaitoBezarius — APPROVED** [review]

**Pull request merged**
