### PR TITLE
dockerTools: Support files directly under /nix/store

### PR DESCRIPTION
**Pull request by utdemir**
###### Motivation for this change

See: https://github.com/NixOS/nixpkgs/pull/91084#issuecomment-653496223

Previosly, stream_layered_iamge.py was assuming that all the paths under
/nix/store were directories, which is clearly wrong. This PR adds a test
for that and fixes the issue.

Also makes sure that the files inside a layer added in a sorted order
to make the results more deterministic.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by misuzu — APPROVED** [review]
This fixes my issue, thank you!

**Comment by roberth** [comment]
Looks alright. `rglob` appears to include dotfiles as well, so that's good.
For the test you could run `nix-store --verify --check-contents` (with `buildLayeredImageWithNixDb`). That should catch all tarball issues.

**Comment by utdemir** [comment]
> For the test you could run `nix-store --verify --check-contents` (with `buildLayeredImageWithNixDb`).

Thank you @roberth , this was a great idea. It already uncovered one more issue regarding the handling of the hardlinks, so this PR now also fixes that.

**Comment by roberth** [comment]
Great job fixing both issues. Thank you @utdemir!

**Pull request merged**
