### PR TITLE
go_1_18: 1.18.4 -> 1.18.5 

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zowoq** [comment]
1.17 can go to master so I've cherry picked it to https://github.com/NixOS/nixpkgs/pull/184636

**Comment by zowoq** [comment]
Needed to revert 4d1e04c00fe2ab1dd485ae198be56f97b7fff41f as well .... guess I'll open another PR.

**Comment by SuperSandro2000** [comment]
that isn't in master yet so I didn't notice

**Comment by zowoq** [comment]
https://github.com/NixOS/nixpkgs/runs/7620927914

would have seen it fail on ofborg if you had waited for the builds to finish first rather than merging it prematurely

**Comment by SuperSandro2000** [comment]
that was and is green.... Not much I can do if GitHub trolls me.
image

**Comment by zowoq** [comment]
the screenshot you posted is the builds from the previous build master before ofborg started building it on staging.

if you had waited for ofborg to catch up:

go

**Comment by flokli** [comment]
@SuperSandro2000 really, please test your builds locally, against the branch it's targeting. This should have shown up quite early, as the patch removed in https://github.com/NixOS/nixpkgs/pull/184644 failed to apply in this version of the PR.

Also, it wouldn't have hurt to leave this PR up for review for more than 3 hours, to actually give more people time to look at it.

The nix code also had a comment stating this should be dropped with the next bump containing the patch.

**Comment by SuperSandro2000** [comment]
I tested that locally then zowoq retargeted the branch and I didn't retest that because I already tested the change and that was confirmed by ofborg being green.

Normally GitHub also discards the CI status of old commits almost immediately and if ofborg is not that busy it can be done after 30 minutes. I don't know how they where still green at that point. They shouldn't even if ofborg is not done yet.

> The nix code also had a comment stating this should be dropped with the next bump containing the patch.

Not on my branch https://github.com/NixOS/nixpkgs/pull/184617/files#diff-f251c3ef2dce7eb702c35d8698843d7fa89577a9dc660dbda6df7a8e8a1f5202R176-R184 even though that I rebased my branch yesterday. Also technically there wasn't a comment in the nix code that that patch should be dropped when 1.18.5 hits https://github.com/NixOS/nixpkgs/commit/4d1e04c00fe2ab1dd485ae198be56f97b7fff41f#diff-f251c3ef2dce7eb702c35d8698843d7fa89577a9dc660dbda6df7a8e8a1f5202R191-R196 .

**Comment by zowoq** [comment]
Could you please just stop merging PR so quickly? IIRC I've asked this of you a few times now and yet it keeps happening.

**Comment by SuperSandro2000** [comment]
Yeah, sure but normally go patch updates are a complete no brainer.

**Comment by flokli** [comment]
> Yeah, sure but normally go patch updates are a complete no brainer.

That's no reason to just not test stuff before sending the PR, and certainly not to self-merge after 5h…

**Comment by zimbatm** [comment]
This is not the first time @SuperSandro2000. Please adjust your decision-making process. Do not merge PRs unless they pass the following criteria: approved by a maintainer or approved by more than 3 people or waited for more than a week.

**Comment by SuperSandro2000** [comment]
> That's no reason to just not test stuff before sending the PR

That is not what happened. I tested this before sending the PR but the retargeting and multiple simultaneous moving branches at different points across forks make things a tiny bit more difficult and more likely to do mistakes. 

---

@zimbatm noted

**Pull request merged**
