### PR TITLE
ci/eval: add rebuildsByPlatform to the comparison result

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Things done

Follow-up of #362844

This adds a new key to the JSON generated by the `compare` function.
It lists the rebuilds for each platform.
This will make https://github.com/Mic92/nixpkgs-review/issues/433 way easier.

cc @infinisil @Mic92 

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Mic92** [comment]
Test run: https://github.com/Mic92/nixpkgs/pull/40

**Comment by Mic92** [comment]
> > Test run: [Mic92#40](https://github.com/Mic92/nixpkgs/pull/40)
> 
> It seems like the comparison step does not run.

@infinisil how can we test this in our own forks?

**Comment by infinisil** [comment]
@Mic92 Need to also push something on the master branch to get the eval there going

**Comment by Mic92** [comment]
Ah maybe the issue is that my base branch is called main and not master?

**Comment by GaetanLepage** [comment]
I was able to test in my fork:
- mock changes: https://github.com/GaetanLepage/nixpkgs/pull/4/files
- Result: https://github.com/GaetanLepage/nixpkgs/actions/runs/12279483898?pr=4

**Comment by GaetanLepage** [comment]
```
{
  "attrdiff": {
    "added": [
      "gh-cal-bis"
    ],
    "changed": [
      "python311Packages.equinox",
      "python311Packages.flowmc",
      "python311Packages.lineax",
      "python311Packages.optimistix",
      "python312Packages.equinox",
      "python312Packages.flowmc",
      "python312Packages.lineax",
      "python312Packages.optimistix"
    ],
    "removed": [
      "materialize",
      "quake3demo"
    ]
  },
  "labels": [
    "10.rebuild-darwin: 1-10",
    "10.rebuild-linux: 1-10"
  ],
  "rebuildCountByKernel": {
    "darwin": 9,
    "linux": 9
  },
  "rebuildsByKernel": {
    "darwin": [
      "gh-cal-bis",
      "python311Packages.equinox",
      "python311Packages.flowmc",
      "python311Packages.lineax",
      "python311Packages.optimistix",
      "python312Packages.equinox",
      "python312Packages.flowmc",
      "python312Packages.lineax",
      "python312Packages.optimistix"
    ],
    "linux": [
      "gh-cal-bis",
      "python311Packages.equinox",
      "python311Packages.flowmc",
      "python311Packages.lineax",
      "python311Packages.optimistix",
      "python312Packages.equinox",
      "python312Packages.flowmc",
      "python312Packages.lineax",
      "python312Packages.optimistix"
    ]
  },
  "rebuildsByPlatform": {
    "aarch64-darwin": [
      "gh-cal-bis",
      "python311Packages.equinox",
      "python311Packages.flowmc",
      "python311Packages.lineax",
      "python311Packages.optimistix",
      "python312Packages.equinox",
      "python312Packages.flowmc",
      "python312Packages.lineax",
      "python312Packages.optimistix"
    ],
    "aarch64-linux": [
      "gh-cal-bis",
      "python311Packages.equinox",
      "python311Packages.flowmc",
      "python311Packages.lineax",
      "python311Packages.optimistix",
      "python312Packages.equinox",
      "python312Packages.flowmc",
      "python312Packages.lineax",
      "python312Packages.optimistix"
    ],
    "x86_64-darwin": [
      "gh-cal-bis",
      "python311Packages.equinox",
      "python311Packages.lineax",
      "python311Packages.optimistix",
      "python312Packages.equinox",
      "python312Packages.lineax",
      "python312Packages.optimistix"
    ],
    "x86_64-linux": [
      "gh-cal-bis",
      "python311Packages.equinox",
      "python311Packages.flowmc",
      "python311Packages.lineax",
      "python311Packages.optimistix",
      "python312Packages.equinox",
      "python312Packages.flowmc",
      "python312Packages.lineax",
      "python312Packages.optimistix"
    ]
  }
}

**Pull request merged**
