### PR TITLE
nixos/redmine: add an extraEnv option, enable automatic log rotation

### PR DESCRIPTION
**Pull request by aanderse**
###### Motivation for this change
Some additional configuration for Redmine needs to be written to an additional_environment.rb file for Redmine. This PR creates that file and allows the user to append whatever they need to it. As an added  bonus log rotation is now configured by default so users won't have an ever expanding log file.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by aanderse** [comment]
@GrahamcOfBorg test redmine

**Comment by aanderse** [comment]
@7c6f434c just in case you're willing and able :)

**Comment by aanderse** [comment]
@7c6f434c that makes sense. I hope you don't mind me bugging you for relatively simple merges, because as mentioned previously you do have the most context on this...

Thanks for the merge!

**Comment by 7c6f434c** [comment]
Sure, no problem.

**Pull request merged**
