### PR TITLE
dgraph: 0.8.2 -> 1.0.11

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

update version

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc maintainer @sigma

### CODE REVIEW

**Comment by volth** [comment]
@GrahamcOfBorg build dgraph-ratel

**Comment by volth** [comment]
@GrahamcOfBorg build dgraph-ratel

**Comment by volth** [comment]
@GrahamcOfBorg build dgraph-ratel

**Comment by volth** [comment]
@GrahamcOfBorg build dgraph-ratel

**Comment by volth** [comment]
@GrahamcOfBorg build dgraph-ratel

**Comment by pingiun** [comment]
This PR can be closed as https://github.com/NixOS/nixpkgs/pull/67863 already updated dgraph

**Pull request closed without merging**
