### PR TITLE
ffmpeg_7: init at 7.0

### PR DESCRIPTION
**Pull request by Atemu**
## Description of changes

~~Currently fails with:~~

```
TEST    filter-hls-append
GEN     tests/data/vsynth_lena.yuv
GEN     tests/data/vsynth2.yuv
/lena.pnm: No such file or directory
make: *** [tests/Makefile:45: tests/data/vsynth_lena.yuv] Error 1
make: *** Waiting for unfinished jobs....
```

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Atemu** [comment]
Created upstream ticket: https://trac.ffmpeg.org/ticket/10947#ticket

**Comment by aviallon** [comment]
Fixed upstream: https://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=7b7b7819bd21cc92ac07f6696b0e7f26fa8f9834

**Comment by Atemu** [comment]
Result of `nixpkgs-review pr 301855` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>21 packages built:</summary>
  <ul>
    <li>ffmpeg_7</li>
    <li>ffmpeg_7-full</li>
    <li>ffmpeg_7-full.bin</li>
    <li>ffmpeg_7-full.data</li>
    <li>ffmpeg_7-full.dev</li>
    <li>ffmpeg_7-full.doc</li>
    <li>ffmpeg_7-full.lib</li>
    <li>ffmpeg_7-full.man</li>
    <li>ffmpeg_7-headless</li>
    <li>ffmpeg_7-headless.bin</li>
    <li>ffmpeg_7-headless.data</li>
    <li>ffmpeg_7-headless.dev</li>
    <li>ffmpeg_7-headless.doc</li>
    <li>ffmpeg_7-headless.lib</li>
    <li>ffmpeg_7-headless.man</li>
    <li>ffmpeg_7.bin</li>
    <li>ffmpeg_7.data</li>
    <li>ffmpeg_7.dev</li>
    <li>ffmpeg_7.doc</li>
    <li>ffmpeg_7.lib</li>
    <li>ffmpeg_7.man</li>
  </ul>
</details>

**Review by arthsmn — APPROVED** [review]

**Comment by aviallon** [comment]
@Atemu when trying to build your branch, I get a hash mismatch for the patch:
```console
[user@system] $ nix shell -L -v github:Atemu/nixpkgs/update/ffmpeg#ffmpeg_7
...
fate_avoid_dependency_on_samples> trying https://git.videolan.org/?p=ffmpeg.git;a=patch;h=7b7b7819bd21cc92ac07f6696b0e7f26fa8f9834
fate_avoid_dependency_on_samples>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
fate_avoid_dependency_on_samples>                                  Dload  Upload   Total   Spent    Left  Speed
fate_avoid_dependency_on_samples> 100 31379    0 31379    0     0  73275      0 --:--:-- --:--:-- --:--:-- 73144
error: hash mismatch in fixed-output derivation '/nix/store/kbg9gqv2cmf00h4r0sr5jlg90nx8c8p6-fate_avoid_dependency_on_samples.drv':
         specified: sha256-jS0UAysM1DoWVLoGAgGqBLSvxa6Ah/z2wmA6CvX/iuk=
            got:    sha256-TKI289XqtG86Sj9s7mVYvmkjAuRXeK+2cYYEDkg6u6I=
error: 1 dependencies of derivation '/nix/store/1kzxzyygrmzyy0h5kh3nim5a6jc9rip2-ffmpeg-7.0.drv' failed to build
```

**Comment by risicle** [comment]
Same, macos 12 x86_64:

```
error: hash mismatch in fixed-output derivation '/nix/store/bawwqgi9paimi3mrrkprsgz4dwckybny-fate_avoid_dependency_on_samples.drv':
         specified: sha256-jS0UAysM1DoWVLoGAgGqBLSvxa6Ah/z2wmA6CvX/iuk=
            got:    sha256-TKI289XqtG86Sj9s7mVYvmkjAuRXeK+2cYYEDkg6u6I=
```

**Comment by Atemu** [comment]
Yeah, I can repro aswell but wanted to take a look what actually changed first. Shouldn't that link be stable?

**Comment by lovesegfault** [comment]
Sometimes tarballs have different hashes on Darwin, IME; I think because of case-sensitivity?

**Comment by Atemu** [comment]
We're talking about fetchpatch here ;)

**Comment by Atemu** [comment]
Updated the patch.

Here are the previous and current versions if you want to check for backdoors ;) https://drive.proton.me/urls/G6XX4C3K9C#sBk9yvXWuhjb

**Review by SuperSandro2000 — APPROVED** [review]

**Review by jopejoe1 — APPROVED** [review]
Builds and runs

**Review by arthsmn — APPROVED** [review]

**Comment by risicle** [comment]
On macos 12 x86_64:

```
libavdevice/avfoundation.m:765:41: error: must use 'enum' tag to refer to type 'AVMediaType'
static NSArray* getDevicesWithMediaType(AVMediaType mediaType) {
                                        ^
                                        enum 

```

**Comment by Atemu** [comment]
@risicle I currently do not have access to a macOS machine. This smells a bit like requiring a newer SDK though?

**Pull request merged**
