### PR TITLE
mfc465cn[lpr,cupswrapper]: init at 1.0.1-1

### PR DESCRIPTION
**Pull request by phrogg**
###### Description of changes

This package consists of the driver as well as the cupswrapper for the MFC-465CN printer by brother: https://support.brother.com/g/b/downloadlist.aspx?c=us&lang=en&prod=mfc5460cn_all&os=128

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Hey, welcome to nixpkgs!

We need references to those two packages in `pkgs/top-level/all-packages.nix`, then others can `nix-build -A <attribute>` to build them.

We also require individual commits per attribute you are touching, so that would be one for adding yourself as a maintainer, then one for each package.

Thanks!

**Comment by phrogg** [comment]
> Hey, welcome to nixpkgs!
> 
> We need references to those two packages in `pkgs/top-level/all-packages.nix`, then others can `nix-build -A <attribute>` to build them.
> 
> We also require individual commits per attribute you are touching, so that would be one for adding yourself as a maintainer, then one for each package.
> 
> Thanks!

Thanks for the heads-up. I did as told :)

**Comment by phrogg** [comment]
Sorry for the mess, it should be fine now.

**Comment by quasigod-io** [comment]
The commits adding the files to `pkgs/top-level/all-packages.nix` will have to be squashed into the commits for adding the files. In the end, there should be one commit for each package, with each commit adding the new file for the package and adding the line in `all-packages.nix`.

**Comment by phrogg** [comment]
> The commits adding the files to `pkgs/top-level/all-packages.nix` will have to be squashed into the commits for adding the files. In the end, there should be one commit for each package, with each commit adding the new file for the package and adding the line in `all-packages.nix`.

Ahh thanks.



> Hey, welcome to nixpkgs!
> 
> We need references to those two packages in `pkgs/top-level/all-packages.nix`, then others can `nix-build -A <attribute>` to build them.
> 
> We also require individual commits per attribute you are touching, so that would be one for adding yourself as a maintainer, then one for each package.
> 
> Thanks!

Then I did not understand this correctly, I thought I need a commit for each file that has changed.

Nevertheless it should be correct now.

**Pull request merged**
