### PR TITLE
iio-sensor-proxy: new service

### PR DESCRIPTION
**Pull request by tomfitzhenry**
###### Motivation for this change

Make it easy to setup iio-sensor-proxy.

https://gitlab.freedesktop.org/hadess/iio-sensor-proxy/
https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/os-specific/linux/iio-sensor-proxy/default.nix

Tested to work on a Pinephone: Phosh uses the ambient light sensor to control auto brightness, and applications can use the compass.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by samueldr** [comment]
Uuuuuuh... [we already have the service setup here](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/hardware/sensor/iio.nix)

**Review by samueldr — CHANGES_REQUESTED** [review]
(Marking as request changes to make sure other contributors don't merge.)

**Comment by Pacman99** [comment]
I remember the the iio module being hard to discover for me because searching for "iio-sensor-proxy" in the configuration.nix manpage doesn't lead to anything. I guess that could be part of the reason as to why this PR was made.

I suggest updating the existing iio module option description to contain the keyword "iio-sensor-proxy".

**Comment by tomfitzhenry** [comment]
> Thought, uuuuuuh... we already have the service setup here

Perfect! :)

Somehow I missed this.

**Comment by tomfitzhenry** [comment]
> I suggest updating the existing iio module option description to contain the keyword "iio-sensor-proxy".

Good idea, I'll do that.

**Pull request closed without merging**
