### PR TITLE
nextcloud: 20.0.6 -> 20.0.7

### PR DESCRIPTION
**Pull request by nlewo**
###### Motivation for this change

Fix several bugs. The changelog: https://nextcloud.com/changelog/#latest20

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nlewo** [comment]
@GrahamcOfBorg test nextcloud

**Comment by nlewo** [comment]
This will also be backported to `nixos-20.09`.

**Review by Ma27 — APPROVED** [review]

**Comment by Ma27** [comment]
Ported to stable as 19d0ed03ef89dc659117e9e5789a54cf4ddc2745.

**Comment by nlewo** [comment]
Thanks!

**Pull request merged**
