### PR TITLE
atom: 1.42.0 -> 1.45.0; atom-beta: 1.43.0 -> 1.46.0

### PR DESCRIPTION
**Pull request by dasj19**
###### Motivation for this change
Version bump for atom and atom-beta.

###### Things done
Changed version numbers and hashes.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dasj19** [comment]
I did a regular update of the atom packages... but wouldn't it be better if we based them on source instead of compiled .deb?
@offlinehacker  @NeQuissimus  @ysndr

**Comment by chkno** [comment]
> I did a regular update of the atom packages... but wouldn't it be better if we based them on source instead of compiled .deb?

Yes, that would definitely be better, but we shouldn't stop atom version updates in the mean time.

**Review by chkno — APPROVED** [review]
I confirm that this builds and atom launches.

**Comment by chkno** [comment]
Atom 1.48 is out now, and is a significant update for python2 deprecation.  I opened a separate PR #90565 to go to 1.48.  Sorry if this was the wrong thing to do.  If this gets merged first I'll rebase on top of it.

**Review by NeQuissimus — APPROVED** [review]

**Comment by chkno** [comment]
This has been taken care of in #90565 atom: 1.42.0 -> 1.48.0, atom-beta: 1.43.0-beta0 -> 1.49.0-beta0

**Pull request closed without merging**
