### PR TITLE
python.nbxmpp: 0.6.10 → 1.0.2; gajim: 1.1.3 → 1.2.2

### PR DESCRIPTION
**Pull request by vbgl**
###### Motivation for this change

Major release.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vbgl** [comment]
@GrahamcOfBorg build python37Packages.nbxmpp gajim

**Review by jonringer — COMMENTED** [review]
otherwise diff LGTM, but i don't feel super strongly about it.

```
https://github.com/NixOS/nixpkgs/pull/95785
3 packages built:
gajim python37Packages.nbxmpp python38Packages.nbxmpp
```

**Comment by jonringer** [comment]
Please follow [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md) and [manual#submitting-changes-making-patches ](https://nixos.org/nixpkgs/manual/#submitting-changes-making-patches) and squash the fix-up commits.

This can be done with:
```
git reset HEAD~1                    # move fix-up commits into unstaged
git add -- pkgs/                    # move changes into staged
git commit --amend --no-edit        # add changes to previous commit
git push ... ... --force            # modify current PR branch
```

**Comment by vbgl** [comment]
Squashed using `git rebase -i`. This can also be achieved when choosing “squash and merge” on the web interface.

**Comment by jonringer** [comment]
in this case, yes, I could squash all of them to one commit. But, there's a CONTRIBUTING.md item in the template to ensure that the process is easier on those who are reviewing

**Review by jonringer — APPROVED** [review]
diff LGTM
shows usage

```
https://github.com/NixOS/nixpkgs/pull/95785
3 packages built:
gajim python37Packages.nbxmpp python38Packages.nbxmpp
```

**Comment by vbgl** [comment]
Thanks for reviewing & merging.

The contributing guide does not tell what to do when the reviewer suggests changes through the web interface: is it ok to just push the button “apply suggestion” (in which case it produces a new commit that does not comply with the contributing guide)?

IMHO, leaving the suggested changes in a separate commit — during the reviewing time only — makes the life of the reviewer easier: they know that their suggestion have been applied as-is. If I instead squash at once, they have to review all the changes again: this might be better regarding the quality of the review, but slightly more time-consuming.

**Pull request merged**
