### PR TITLE
blastem: init at 0.5.1

### PR DESCRIPTION
**Pull request by puffnfresh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ryantm** [comment]
@GrahamcOfBorg build blastem

**Review by ryantm — CHANGES_REQUESTED** [review]
Please fix the build

**Comment by puffnfresh** [comment]
Does ofborg not have /usr/bin/env? I can't reproduce the failure on my NixOS systems.

**Comment by ryantm** [comment]
I can reproduce with ` nix-build --option sandbox true -A blastem`

```
...
true ./blastem
gcc -O2 -flto -I/nix/store/cbcbqfpjkxpidsqv3r7w7slgik7fwx93-SDL2-2.0.8-dev/include/SDL2 -I/nix/store/4x4l8q7qisjg1gabvpq99cypr646sfgb-mesa-noglu-18.1.5-dev/\
include -I/nix/store/2yabd23z60jjgw1bvbnmmjlcp58xx2nw-glew-2.1.0-dev/include -I/nix/store/bil4p8ry2haarf1yhcz5vy9m0jwxnzcs-glu-9.0.0-dev/include -std=gnu99 \
-Wreturn-type -Werror=return-type -Werror=implicit-function-declaration -Wno-unused-value  -DX86_64 -m64  -O2 -flto -lm -L/nix/store/b028c6ax8622375lp2gjc3q\
6xznpkdbr-SDL2-2.0.8/lib -L/nix/store/3v1rcfkyzrf07vhij95cy9j72qx63y5j-libglvnd-1.0.0/lib -L/nix/store/v50b6limw49rcg686akm4aidxrawmymf-glew-2.1.0/lib -L/ni\
x/store/h2ipbyqfg712x16qsagpanybpxs3249r-glu-9.0.0/lib -Wl,-rpath,/nix/store/b028c6ax8622375lp2gjc3q6xznpkdbr-SDL2-2.0.8/lib -Wl,--enable-new-dtags -lSDL2 -\
lGLEW -lGLU -lGL -m64  termhelper.c   -o termhelper
/bin/sh: /bin/echo: not found
xcf2png font_interlace_variable.xcf > font_interlace_variable.png
./img2tiles.py -s font_interlace_variable.spec font_interlace_variable.tiles
make: ./img2tiles.py: Command not found
make: *** [Makefile:236: font_interlace_variable.tiles] Error 127
builder for '/nix/store/h8cnfldwg9v8g41l565biy08ln95damh-blastem-0.5.1.drv' failed with exit code 2
error: build of '/nix/store/h8cnfldwg9v8g41l565biy08ln95damh-blastem-0.5.1.drv' failed
```

**Comment by puffnfresh** [comment]
@ryantm thanks. I didn't realise the sandbox doesn't have `/usr`!

Fixed the problem.

**Comment by ryantm** [comment]
@GrahamcOfBorg build blastem

**Review by ryantm — APPROVED** [review]

**Pull request merged**
