### PR TITLE
qemu: 2.12.1 -> 3.0.0

### PR DESCRIPTION
**Pull request by volth**
do not merge, it is just to test the build on different platforms

I am not sure if it is a good idea to merge ```qemu-3.0.0-rc1```, but ```qemu-3.0.0``` may be ready by the time of ```nixos-18.09``` so the testing of ```3.0.0-rc1``` on ```nixos-unstable``` may have sense.

### CODE REVIEW

**Comment by thoughtpolice** [comment]
@volth I mentioned this in IRC a few days ago, but since you're here, would you mind doing a favor, if you are going to do the QEMU upgrade?

Can you change the `qemu` expression to include a `version` attribute and set `name = "qemu-${version}";`, as most packages do? QEMU's expression was originally quite old, so it wasn't written this way, but this makes it slightly more annoying to perform consistent overrides (e.g. in your own overlay, like the one I have), since `version` doesn't exist. (It's also occasionally nice to query `pkg.version` to get that information).

Unfortunately, adding that attribute will cause a rebuild which might percolate a bit, but doing it then would be nice.

**Comment by volth** [comment]
This version with ```3.0.0-rc1``` in the tarball name actually reports that it is ```2.12.91```, so it might be confusing specify it as ```3.0.0-rc1```

**Comment by volth** [comment]
A breaking [change](https://wiki.qemu.org/ChangeLog/3.0) is:

 ```
The "vlan" parameter of the "-net" option has been removed.
Use "-netdev" with IDs or the "hubport" netdev instead.
```

https://github.com/NixOS/nixpkgs/blob/7ffed91faf7ae50573e08690d3f1963d827575a5/nixos/tests/ec2.nix#L71
https://github.com/NixOS/nixpkgs/blob/7ffed91faf7ae50573e08690d3f1963d827575a5/nixos/lib/qemu-flags.nix#L7-L8

@dezgeg ?

**Comment by dezgeg** [comment]
I think it's something like this: https://github.com/NixOS/nixpkgs/compare/master...dezgeg:qemu-non-legacy-net-syntax?expand=1

**Comment by volth** [comment]
> I think it's something like this: https://github.com/NixOS/nixpkgs/compare/master...dezgeg:qemu-non-legacy-net-syntax?expand=1

Yes, it works in my fork of test-driver, so I added your commit to this PR and made similar changes in ec2.nix (but I have not tested the stock test-driver nor ec2).
Thank you!

**Comment by volth** [comment]
@GrahamcOfBorg build qemu

**Comment by volth** [comment]
meanwhile ```qemu-2.12.1``` released in [```stable-2.12```](https://git.qemu.org/?p=qemu.git;a=shortlog;h=refs/heads/stable-2.12) branch

**Comment by volth** [comment]
@dtzWill could you check musl patches?

**Comment by volth** [comment]
I think it is safe to merge, I'm using it since ```3.0.0-rc1```

**Pull request merged**
