### PR TITLE
nixos/earlyoom: bring the module up to date

### LINKED ISSUE #83504: earlyoom service: Cannot configure second part of -m/-s parameters
## Issue description

The `earlyoom` module requires `type = int`:

https://github.com/NixOS/nixpkgs/blob/7401afc428799acb19f72028d0914092a978c909/nixos/modules/services/system/earlyoom.nix#L20-L29

but in fact it can be given [docs](https://github.com/rfjakob/earlyoom/tree/137a6e43ac80b57b46426346b79a0dffee173c82#command-line-options)

```
  -m PERCENT[,KILL_PERCENT] set available memory minimum to PERCENT of total
                            (default 10 %).
                            earlyoom sends SIGTERM once below PERCENT, then
                            SIGKILL once below KILL_PERCENT (default PERCENT/2).
  -s PERCENT[,KILL_PERCENT] set free swap minimum to PERCENT of total (default
                            10 %).
                            Note: both memory and swap must be below minimum for
                            earlyoom to act.
```

so e.g. `-m 10,5` to configure `KILL_PERCENT`.

That means the `KILL_PERCENT` setting is currently not configurable in NixOS.

It is very important to configure it, because as written:

> both memory and swap must be below minimum for earlyoom to act.

That means earlyoom will only start terminating processes after a large amount of swap is full, which can take forever to happen, thus defeating a major point of earlyoom. (You can work around that by completely disabling swap, but then you can't suspend-to-disk either.)

Even if you set `freeSwapThreshold = 100`, that will translate to to `-s 100,50` by default, so that's 50% of swap filled!

This is why we need to allow the user to configure `KILL_PERCENT`, so that they can set it to an impactful value like `-s 100,100`.

We will have to change away from `type = int`, probably to accept both `int` and `string` for backwards compatibility.

### Steps to reproduce

Set up `earlyoom` with swap, run out of memory, see your system freeze.

## Technical details

19.09 (same for current `master`).

---

CC @wedens @ljli as past contributors.

### LINKED ISSUE #132783: Update earlyoom and undeprecate notification option / update the module to handle the re-added feature
See https://github.com/rfjakob/earlyoom/issues/254#issuecomment-878448415 for diagnosis and background , upstream appears to have re-added the script-like notification feature, we should update our earlyoom module to be consistent with the new state of things when earlyoom makes a release, or as appropriate.

I've discussed with @Profpatsch that he is willing to do this.

### PR DESCRIPTION
**Pull request by ncfavier**
Removes deprecated option `ignoreOOMScoreAdjust`, introduces `killHook` as a replacement for `notificationsCommand`, and adds an `extraArgs` option for things not covered by the module.

Fixes #132783
Fixes #83504

Untested.

My example `killHook` script sucks, suggestions welcome.

### CODE REVIEW

**Comment by ncfavier** [comment]
cc @deliciouslytyped as I can't add you to reviewers for some reason

**Review by Profpatsch — APPROVED** [review]
Tried on my very simple configuration

```
    services.earlyoom = {
      enable = true;
      freeMemThreshold = 5; # <5% free
    };
```

and it still seems to work.

**Comment by ncfavier** [comment]
Rebased after https://github.com/NixOS/nixpkgs/pull/130003, cc @peterhoeg

**Comment by peterhoeg** [comment]
Haven't tested it, but the changes look good to me. `killHook` sample is fine. How about a *super* simple nixos test that simply verifies that it launches?

**Comment by ncfavier** [comment]
Sounds like a good opportunity to write my first NixOS test

**Comment by ncfavier** [comment]
@ofborg build earlyoom

**Comment by ncfavier** [comment]
@ofborg build earlyoom.passthru.tests

**Comment by ncfavier** [comment]
Relaxed the type of `free{Mem,Swap}Threshold` to fix https://github.com/NixOS/nixpkgs/issues/83504, and added `reportInterval` to avoid log flooding (the interval default to one second...).

Tested locally, works fine.
@ofborg test earlyoom

**Comment by peterhoeg** [comment]
I don't like the string bit at all as we have no way of verifying that we're passing a sane value through.

Instead add 2 new integer options for the corresponding kill values and use those to generate the proper string.

**Comment by peterhoeg** [comment]
@GrahamcOfBorg build earlyoom.passthru.tests

**Pull request merged**
