### PR TITLE
upgrade leiningen to latest (2.9.0)

### PR DESCRIPTION
**Pull request by mpisanko**
###### Motivation for this change
Upgrade leiningen to latest (2.9.0)

###### Things done

- Built on platform(s)
- [x] NixOS
- [x] Tested execution of all binary files (usually in `./result/bin/`)

---

### CODE REVIEW

**Comment by ryantm** [comment]
@tobim please fix your commit message to match https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md

**Comment by ryantm** [comment]
@mpisanko  please fix your commit message to match https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md

**Comment by ryantm** [comment]
@GrahamcOfBorg build leiningen

**Comment by mpisanko** [comment]
@ryantm done

**Comment by ryantm** [comment]
@GrahamcOfBorg build

**Comment by ryantm** [comment]
@GrahamcOfBorg build leiningen

**Review by ryantm — APPROVED** [review]

**Pull request merged**
