### PR TITLE
write_stylus: fix loading libGL.so with libglvnd

### PR DESCRIPTION
**Pull request by oyren**
###### Motivation for this change
./Write: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
Is a backport required?

**Comment by oyren** [comment]
> Is a backport required?

Sry, what exactly do you mean by that?
Does it means that the package will be added to 18.09?

**Comment by oyren** [comment]
Oh of course.
Yes the package was in 18.09, also was affect by the bug, so a backport would be nice.

**Comment by Mic92** [comment]
backport: 533c5bcdeb8

**Pull request merged**
