### PR TITLE
nixos/nextcloud: add overwriteWebroot option

### PR DESCRIPTION
**Pull request by pnmadelaine**
###### Motivation for this change

The `overwritewebroot` option of Nextcloud is currently not exposed by the NixOS module.
It can be used to serve Nextcloud at a subdir of the webroot.

###### Things done

- create a new option, `config.overwriteWebroot`
- refactor the nginx config according to https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html#nextcloud-in-a-subdir-of-the-nginx-webroot

###### Checklist

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
A few notes:

* Please split this into two commits. These are two technical changes and this makes it a bit easier to review :) 
* Have you actually checked whether the latest nginx config is fine with all Nextcloud versions we support? I had to revert some changes in here in the past because older, still supported versions broke with that.

**Comment by pnmadelaine** [comment]
> A few notes:
> 
>     * Please split this into two commits. These are two technical changes and this makes it a bit easier to review :)
noted

> 
>     * Have you actually checked whether the latest nginx config is fine with all Nextcloud versions we support? I had to revert some changes in here in the past because older, still supported versions broke with that.
That's a good point. It works with nextcloud22 on my server but I didn't try older versions.

**Comment by pnmadelaine** [comment]
I've been running this on my server for a few days without any major issue, and I realize only now that it actually broke some apps.
I'm leaving the PR as a draft until I fix this.

**Comment by pnmadelaine** [comment]
From the tests in `nixos/tests/nextcloud` only `basic` is successful on `nixos-unstable`.
I've run it on my branch for all versions of Nextcloud avalaible and it seems to work.

**Pull request closed without merging**
