### PR TITLE
Fix hivex for darwin

### PR DESCRIPTION
**Pull request by Amar1729**
###### Motivation for this change

Hivex library updated to work on macOS:
- added `libiconv` dependency
- added proper `PERL5LIB` to wrapper for `hivexregedit`

Mostly added this because it's a dependency for `libguestfs` which I'm still trying to get working on darwin. Haven't been able to find a lot of test cases for it though.

Had some help from rycee on the nixos irc for the perl stuff too.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg build hivex

**Comment by Amar1729** [comment]
Current build failure due to #59450 

rip darwin :/

**Comment by Amar1729** [comment]
am i allowed to ask grahamc to build things? also is there a way to specify building on darwin only?

**Comment by xeji** [comment]
> am i allowed to ask grahamc to build things?

Unfortunately not (yet). Authorization is usually given to frequent contributors.

> also is there a way to specify building on darwin only?

Such a feature has been discussed but (at least to my knowledge) not yet implemented.

**Comment by xeji** [comment]
So let's try again
@GrahamcOfBorg build hivex

**Review by LnL7 — APPROVED** [review]

**Pull request merged**
