### PR TITLE
haskell-updates: add documentation for onboarding new member

### PR DESCRIPTION
**Pull request by cdepillabout**
###### Motivation for this change

This adds documentation about what packages on Hackage a new member of NixOS/haskell needs to be added to.

This is inspired from https://github.com/NixOS/nixpkgs/issues/125980.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by expipiplus1** [comment]
Would it also make sense to make new members be mods in the nix/haskell matrix room? (I notice that only maralorn is at the moment)

**Review by expipiplus1 — APPROVED** [review]

**Comment by cdepillabout** [comment]
Thanks for the review.  I'm going to go ahead and merge this.

> Would it also make sense to make new members be mods in the nix/haskell matrix room? (I notice that only maralorn is at the moment)

I don't really know anything about Matrix.  Maybe @maralorn has an opinion here?

**Comment by maralorn** [comment]
I agree that more people should have rights in the matrix room. I am a mod because graham gave me those rights. But a mod can‘t anoint other mods so we need to go through him who is the only admin of that room right now.

I have not really an opinion on the question if this is important enough to document.

**Comment by expipiplus1** [comment]
Sure, no biggie at all, I'm happy either way.

**Pull request merged**
