### PR TITLE
vale: init at 0.10.1

### PR DESCRIPTION
**Pull request by marsam**
###### Motivation for this change

Add [Vale](https://valelint.github.io/docs/) package

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ryantm** [comment]
Are you willing to add yourself as the maintainer of this package?

**Comment by grahamc** [comment]
@GrahamcOfBorg build vale

**Comment by marsam** [comment]
@ryantm sure, do I add myself to maintainer-list.nix?

**Comment by ryantm** [comment]
Yes, please!

**Comment by marsam** [comment]
done :)

**Pull request merged**
