### PR TITLE
[nixos] agetty: Add autologinUser config option

### PR DESCRIPTION
**Pull request by dezgeg**
This option causes the specified user to be automatically logged in at
the virtual console. Tested on x86_64 in virtualbox.

It might be useful to set `autologinUser = "root"` for the installation CDs as well.

### CODE REVIEW

**Comment by lethalman** [comment]
:+1: also for the installation cd

**Comment by edolstra** [comment]
:+1:

**Comment by dezgeg** [comment]
Added the installer change to this PR, please let me know if a separate PR would be preferrable. I left the comment about empty root password in in case something (su?) explicitly asks for it.

**Comment by lethalman** [comment]
I've tested the installation cd, worked fine. Thanks.

**Pull request merged**
