### PR TITLE
amd-blis: init at 2.2

### PR DESCRIPTION
**Pull request by danieldk**
###### Motivation for this change

Add the AMD fork of BLIS. This provides a BLAS-compatible library that is optimized for AMD CPUs. A counterpart to MKL, but open source :).

Tested by recompiling `numpy` with AMD BLIS through the new BLAS overlay mechanism.

After this PR, I'll also do a PR for AMD's libflame, so that we have a full AMD BLAS/LAPACK as an alternative.

**Changed to Draft until I figure out why ofborg VMs execute an illegal instruction.**

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by doronbehar** [comment]
CI builds fail.

**Comment by danieldk** [comment]
> CI builds fail.

Hmpf. SIGILL (Illegal instruction) on x86_64. Either it's misdetecting the features of the VM's CPU, or the features supported by CPUID are not permitted by the VM. Unfortunately, blis does not offer the possibility to override the architecture with e.g. an environment variable. I'll think a bit about the fix. Perhaps something along the lines of:

https://github.com/flame/blis/pull/345/commits/e22ab9dd0057dfd3d7b7590f41e41bce6ffbeb14

**Comment by danieldk** [comment]
@ofborg build amd-blis

**Comment by danieldk** [comment]
@ofborg build amd-blis

**Comment by danieldk** [comment]
@ofborg build amd-blis

**Comment by danieldk** [comment]
I figured it out. There is an error in the selection of `CFLAGS` that causes the `zen` kernels (which are also used on some Intel CPUs) to be compiled with Skylake X optimizations when the `x86_64` configuration is chosen. This introduces some AVX-512 instructions in the kernel (`vextractf64x2`), interestingly, this does not fail on my Zen 2 machine.

The reason that the kernel selection fails is that `x86_64` does not actually contain `zen`, so the kernel cannot be compiled with `-march=zen`. Adding `zen` (and `zen2`) to the `amd64`/`x86_64` kernel leads to another error. I'll try to see if this is easily fixable.

**Pull request closed without merging**
