### PR TITLE
volk: 2.4.1 -> 2.5.0

### PR DESCRIPTION
**Pull request by eduardosm**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by eduardosm** [comment]
Result of `nixpkgs-review pr 128494` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>gnss-sdr</li>
    <li>gnuradio</li>
    <li>gnuradio3_7Minimal</li>
    <li>gnuradio3_8</li>
    <li>gnuradio3_8Minimal</li>
    <li>gnuradio3_8Packages.ais</li>
    <li>gnuradio3_8Packages.gnuradio</li>
    <li>gnuradio3_8Packages.limesdr</li>
    <li>gnuradio3_8Packages.osmosdr</li>
    <li>gnuradio3_8Packages.rds</li>
    <li>gnuradioMinimal</li>
    <li>gnuradioPackages.gnuradio</li>
    <li>gqrx</li>
    <li>inspectrum</li>
    <li>qradiolink</li>
    <li>volk</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 128494` at 2b41f19f run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>15 packages skipped due to time constraints:</summary>
  <ul>
    <li>gnss-sdr</li>
    <li>gnuradio</li>
    <li>gnuradio3_7Minimal</li>
    <li>gnuradio3_8</li>
    <li>gnuradio3_8Minimal</li>
    <li>gnuradio3_8Packages.ais</li>
    <li>gnuradio3_8Packages.gnuradio</li>
    <li>gnuradio3_8Packages.limesdr</li>
    <li>gnuradio3_8Packages.osmosdr</li>
    <li>gnuradio3_8Packages.rds</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>volk</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: unused-argument

Unused argument: `cppunit`.
Near pkgs/development/libraries/volk/default.nix:5:3:
```
  |
5 | , cppunit
  |   ^
```
</li>
  </ul>
</details>

**Comment by doronbehar** [comment]
Not related to the update, but the Darwin build should succeed I think with:

```diff
diff --git i/pkgs/development/libraries/volk/default.nix w/pkgs/development/libraries/volk/default.nix
index 574a90d2272..6a6cccdd47d 100644
--- i/pkgs/development/libraries/volk/default.nix
+++ w/pkgs/development/libraries/volk/default.nix
@@ -29,7 +29,7 @@ stdenv.mkDerivation rec {
     })
   ];
   cmakeFlags = lib.optionals (!enableModTool) [ "-DENABLE_MODTOOL=OFF" ];
-  postInstall = ''
+  postInstall = lib.optionalString stdenv.isDarwin ''
     ${removeReferencesTo}/bin/remove-references-to -t ${stdenv.cc} $(readlink -f $out/lib/libvolk.so)
   '';
 
```

**Comment by eduardosm** [comment]
> Not related to the update, but the Darwin build should succeed I think with:
> 
> ```diff
> diff --git i/pkgs/development/libraries/volk/default.nix w/pkgs/development/libraries/volk/default.nix
> index 574a90d2272..6a6cccdd47d 100644
> --- i/pkgs/development/libraries/volk/default.nix
> +++ w/pkgs/development/libraries/volk/default.nix
> @@ -29,7 +29,7 @@ stdenv.mkDerivation rec {
>      })
>    ];
>    cmakeFlags = lib.optionals (!enableModTool) [ "-DENABLE_MODTOOL=OFF" ];
> -  postInstall = ''
> +  postInstall = lib.optionalString stdenv.isDarwin ''
>      ${removeReferencesTo}/bin/remove-references-to -t ${stdenv.cc} $(readlink -f $out/lib/libvolk.so)
>    '';
>  
> ```

`stdenv.isDarwin` or `!stdenv.isDarwin`? Using `stdenv.isDarwin` won't cause any effect on darwin (but it will on linux)

**Comment by eduardosm** [comment]
>     * Unused argument: `cppunit`.

Fixed

**Comment by doronbehar** [comment]
> `stdenv.isDarwin` or `!stdenv.isDarwin`? Using `stdenv.isDarwin` won't cause any effect on darwin (but it will on linux)

Yes, it should be `!stdenv.isDarwin` :) I was mistaken.

**Comment by eduardosm** [comment]
> Yes, it should be `!stdenv.isDarwin` :) I was mistaken.

Done, but I cannot test it.

**Comment by risicle** [comment]
Confirmed, `volk` builds, macos 10.15.

None of is reverse dependencies do of course though.

**Review by risicle — APPROVED** [review]
`nixpkgs-review` happy, nixos x86_64

**Pull request merged**
