### PR TITLE
shutdown: Protect system from make-initrd-ng

### PR DESCRIPTION
**Pull request by ElvishJerricco**
###### Description of changes

We had been talking a while ago on matrix about the potential for `make-initrd-ng` to run rampant and destroy things if it ever got buggy. At the time we considered pre-running it in a nix build, where it would be sandboxed, and copying its output from the store at shutdown. In my view, this has two problems.

1. It adds the shutdown ramfs to the store, which takes up unnecessary space.
2. We have to copy anyway. Whether it's `rsync` or `make-initrd-ng`, something has the potential to go break things.

Instead, I figure we should just enable `ProtectSystem=strict` on the systemd service. That way it *can't* screw anything up, short of malicious code. Plus, with #185036, `make-initrd-ng` is even faster now, so the noticeable second-long delay is virtually gone now.

In order to ensure the existence of `/run/initramfs`, I added a `systemd.mounts = ...` definition for it. I suppose this could have been a definition in `fileSystems` with `noauto`, but NixOS doesn't have any other implicit `fileSystems` definitions, so that seemed odd to me. I dunno if this is weirder or not.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ElvishJerricco** [comment]
@ofborg test systemd-shutdown

**Comment by winterqt** [comment]
> In order to ensure the existence of `/run/initramfs`, I added a `systemd.mounts = ...` definition for it. I suppose this could have been a definition in `fileSystems` with `noauto`, but NixOS doesn't have any other implicit `fileSystems` definitions, so that seemed odd to me. I dunno if this is weirder or not.

I personally think this is cleaner since we let systemd handle mounting it along with the service.

**Comment by ElvishJerricco** [comment]
@winterqt `fstab` is just a file that `systemd-fstab-generator` uses to make mount units just like this one. We'd get an identical unit out of having

```
  fileSystems."/run/initramfs" = {
    device = "tmpfs"
    fsType = "tmpfs"
    options = ["noauto"];
  };
```

`noauto` just tells it not to add a `Requires` relationship from `local-fs.target`, so that it doesn't become part of the boot chain. We get the same effect with a manual unit by just leaving out any such dependencies.

**Comment by arianvp** [comment]
I'd use `fileSystems` here

**Comment by ElvishJerricco** [comment]
In principle it's kind of more akin to the `specialMount`s in `system.build.earlyMountScript`. Maybe it ought to go there...

**Comment by ElvishJerricco** [comment]
@arianvp Oh, uh, using `fileSystems` gets *tricky* because things like `qemu-vm.nix` override the entirety of `fileSystems`. Any module that does anything like that would have to be modified to retain this FS. So I think it *must* be in `systemd.mounts`.

**Review by pennae — APPROVED** [review]
looks good in principle, but keeping a mount unit around for shutdown feels like it could (in rare circumstances) turn into a bit of a footgun. could we do this by *always* mounting a tmpfs over (the possibly pre-existing) `/run/initrams` in pre-start script instead?

admittedly this turning into a problem is probably unlikely enough to not care.

**Comment by ElvishJerricco** [comment]
@pennae systemd [does not add default dependencies](https://github.com/systemd/systemd/blob/abd6faae80fa87ecc24a000447b86fc32499809d/src/core/mount.c#L529-L532) to `/run/initramfs`, so there's no `Conflicts=umount.target shutdown.target` like there normally is for mount units. There's even an [extra assurance in `nonunmountable_path`](https://github.com/systemd/systemd/blob/abd6faae80fa87ecc24a000447b86fc32499809d/src/shutdown/umount.c#L523-L529), just to be very sure `/run/initramfs` is safe.

**Comment by winterqt** [comment]
@pennae What issues do you foresee (even if unlikely)? Since systemd handles everything, I don't see what could be an issue.

**Comment by pennae** [comment]
we were mostly thinking about other people using the path for anything at all, possibly defining their own mount unit for it. that would of course clash with the definitions provided here, but these being systemd special cases as they are (we didn't know that!) that'll be even less likely than we thought to begin with. doesn't seem unreasonable to just ignore that possibility altogether.

**Comment by oxalica** [comment]
Got here since it turns out I need to cross-compile `rustc` just for a shutdown script targeting Raspberry Pi. I think we should try to reuse the startup initramfs for `boot.initrd.systemd.enable = true` users and generated a new one at build-time rather than run-time. The two points you listed against pre-running `make-initrd-ng` don't really convince me.

> 1. It adds the shutdown ramfs to the store, which takes up unnecessary space.

In my laptop setup, the generated `/run/initramfs` takes about 21MB without compression, or 6.4MB with `xz`, 8.5M with `zstd`/`gzip`. It's pretty acceptable. Note that for extreme embedded devices, this initramfs could be disabled anyway if needed.

> 2. We have to copy anyway. Whether it's `rsync` or `make-initrd-ng`, something has the potential to go break things.

IMO, `make-initrd-ng` is less reliable than a simple `cp` or `rsync`. It does more complicated logic and is only used by NixOS -- unlike the latter ones.

**Comment by ElvishJerricco** [comment]
@oxalica Point of clarification: You're not cross-compiling `rustc`, you're building a cross-capable `rustc`. Realistically, nixpkgs needs to figure out how to use the same rustc build for every target, because it's very much designed to be able to do that.

Are there any other distros making use of `/run/initramfs/shutdown`? It'd be good to know how and when others generate the shutdown ramfs.

**Comment by ElvishJerricco** [comment]
Looks like fedora includes everything necessary for shutdown within initrd. In stage 2, they have `sysinit.target.wants/dracut-shutdown.service`, which starts a script that unpacks the initrd cpio archive into `/run/initramfs`. It's plausible that this is the correct way to do it, since the shutdown process probably needs to mirror the stage 1 process, which some random new NixOS generation the user has switched to may not properly do.

**Comment by lilyinstarlight** [comment]
> Are there any other distros making use of `/run/initramfs/shutdown`? It'd be good to know how and when others generate the shutdown ramfs.

As of right now, Dracut-based (e.g. Fedora) and mkinitcpio-based (e.g. Arch) distros use a shutdown initramfs. initramfs-tools (e.g. Debian) does not currently have support for this

Dracut seems to use the initramfs it was booted with: https://github.com/dracutdevs/dracut/blob/10cf8e46f43a7a2094e4d861c1296db6af0e0fa1/dracut-initramfs-restore.sh#L30-L50
mkinitcpio generates one on the fly at shutdown time (like we currently do): https://github.com/archlinux/mkinitcpio/blob/f2aa2bd69216e99a792b9acc68824e4cdacb216b/systemd/mkinitcpio-generate-shutdown-ramfs.service#L14

**Comment by oxalica** [comment]
@ElvishJerricco
> @oxalica Point of clarification: You're not cross-compiling `rustc`, you're building a cross-capable `rustc`. Realistically, nixpkgs needs to figure out how to use the same rustc build for every target, because it's very much designed to be able to do that.

Sorry for the wording. You're right, it's `rustc` with build=x86_64, host=x86_64, target=armv6l. The compilation is necessary since it needs armv6l `std`, which is currently compiled together with `rustc` IIRC.

> Are there any other distros making use of `/run/initramfs/shutdown`? It'd be good to know how and when others generate the shutdown ramfs.

I checked Arch Linux and it similarly runs `mkinitcpio` right before shutdown. :disappointed: 

I'm also thinking if it's possible to just assume (right before shutdown) the memory is larger enough so that we can `cp` the whole closure of `systemd.shutdownRamfs.contents` into `/run/initramfs` without `make-initramfs-ng`'s shrinking. If so, all issues will be gone.

```
$ nix path-info -Sh nixpkgs#systemd
/nix/store/9rjdvhq7hnzwwhib8na2gmllsrh671xg-systemd-252.1        169.3M
/nix/store/lasqzg72w5mpgam6pkdslqjyj9x3c5g7-systemd-252.1-man      1.4M
```

**Comment by lilyinstarlight** [comment]
I feel like we should probably pre-generate a shutdownramfs with `make-initrd-ng` and keep it in the store, since the size really is pretty small when compressed and avoids the need to have `make-initrd-ng` on the built system, which is larger than the shutdownramfs itself would be (`make-initrd-ng` is 31.66 MiB on my system but like @oxalica my shutdownramfs is 21 MiB uncompressed)

For whether we should combine the initramfs and shutdownramfs and use the same one like dracut, we would need to make sure systemd-shutdown gets copied to `/shutdown` in both the old stage-1 initramfs and the experimental systemd-based initramfs (but that doesn't seem like it would be much trouble and there should be no other requirements)

My initramfs (systemd-based) is 59 MiB uncompressed and my shutdownramfs is 21 MiB uncompressed, so separating them would mean less copying at shutdown since that ramfs is much smaller alone. So I would lean slightly towards separating them (at the cost of taking up more store space), but I doubt I'll notice the difference much either way

**Comment by oxalica** [comment]
@lilyinstarlight
> For whether we should combine the initramfs and shutdownramfs and use the same one like dracut, we would need to make sure systemd-shutdown gets copied to `/shutdown` in both the old stage-1 initramfs and the experimental systemd-based initramfs (but that doesn't seem like it would be much trouble and there should be no other requirements)

This sounds good and adding a `shutdown` symlink is almost always free.
- Old stage-1 initramfs [comes with `udevd` aka. `systemd`](https://github.com/NixOS/nixpkgs/blob/e182da8622a354d44c39b3d7a542dc12cd7baa5f/nixos/modules/system/boot/stage-1.nix#L12). `udevadm` pulls in almost all `systemd` dependencies.
- Systemd-based initrd, of course, has systemd.

The only difficulty is that `initrd` is non-trivial to unpack. It may have arbitrary `boot.initrd.prepend`s and a custom `boot.initrd.compressor`.

> ..., so separating them would mean less copying at shutdown since that ramfs is much smaller alone. So I would lean slightly towards separating them (at the cost of taking up more store space), but I doubt I'll notice the difference much either way.

Note that here we are copying to tmpfs, which is effectively (cached) file reads. The time cost is negligible, if it succeeds.

**Comment by lilyinstarlight** [comment]
I've implemented pre-building the shutdownramfs with the system closure at #216866

**Pull request merged**
