### PR TITLE
pythonPackages.tkinter: fix darwin build

### LINKED ISSUE #10667: Tkinter problem on darwin
i get this problem on OS X 10.9.5 but not on NixOS.

code of guitest.py

```
#! /usr/bin/env nix-shell
#! nix-shell -i python -p python python27Packages.tkinter

import Tkinter

class simpleapp_tk(Tkinter.Tk):
    def __init__(self,parent):
        Tkinter.Tk.__init__(self,parent)
        self.parent = parent
        self.initialize()

    def initialize(self):
        pass

if __name__ == "__main__":
    app = simpleapp_tk(None)
    app.title('my application')
    app.mainloop()
```

```
Traceback (most recent call last):
  File "./guitest.py", line 16, in <module>
    app = simpleapp_tk(None)
  File "./guitest.py", line 8, in __init__
    Tkinter.Tk.__init__(self,parent)
  File "/nix/store/qp0d2fi7bqsb3vl1qpknc294klq4g9zp-python-2.7.10/lib/python2.7/lib-tk/Tkinter.py", line 1816, in __init__
    self._loadtk()
  File "/nix/store/qp0d2fi7bqsb3vl1qpknc294klq4g9zp-python-2.7.10/lib/python2.7/lib-tk/Tkinter.py", line 1832, in _loadtk
    % (_tkinter.TK_VERSION, tk_version)
RuntimeError: tk.h version (8.6) doesn't match libtk.a version (8.5)
```

same error with `#! nix-shell -i python3 -p python3`

### PR DESCRIPTION
**Pull request by knedlsepp**
###### Motivation for this change
18.03 ZHF darwin edition: #36454 (Please backport to 18.03!)
I looked over to homebrew for how they build their python and took the lovely patch:
https://github.com/Homebrew/homebrew-core/blob/8d530a70f8fcf02129d924090d73efbe12ff438d/Formula/python.rb#L378-L425
Fixes #10667

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by LnL7** [comment]
@GrahamcOfBorg build stabber profanity

**Comment by LnL7** [comment]
@GrahamcOfBorg build pythonPackages.tkinter

**Comment by knedlsepp** [comment]
@LnL7 did I miss anything? Why doesn't the darwin build evaluate?

**Comment by LnL7** [comment]
You can't reproduce it? It's either meta.platforms or an evaluation error that ofborg somehow didn't catch.

**Comment by FRidh** [comment]
I've seen this before with Borg. Does this build work for both of you?

**Review by FRidh — APPROVED** [review]

**Comment by LnL7** [comment]
This happened before because of an issue with @grahamc's builder, I'm not aware of any other case that would cause false negatives.

**Review by LnL7 — COMMENTED** [review]
```
unpacking sources
unpacking source archive /nix/store/fm0d4jibbgsi3dpr0s685m5h254pdhsq-python-2.7.14
source root is python-2.7.14
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file python-2.7.14/share/man/man1/python2.7.1.gz
patching sources
configuring
no configure script, doing nothing
building
no Makefile, doing nothing
installing
/nix/store/0igxxngigjgfkgg3cw547n92b8bpg6b1-stdenv-darwin/setup: line 1233: patchelf: command not found
builder for '/nix/store/6agv8zz900y5v6kah1nhllrx9pgjy10z-python2.7-tkinter-2.7.14.drv' failed with exit code 127
error: build of '/nix/store/6agv8zz900y5v6kah1nhllrx9pgjy10z-python2.7-tkinter-2.7.14.drv' on 'ssh://mac1' failed: builder for '/nix/store/6agv8zz900y5v6kah1nhllrx9pgjy10z-python2.7-tkinter-2.7.14.drv' failed with exit code 127
builder for '/nix/store/6agv8zz900y5v6kah1nhllrx9pgjy10z-python2.7-tkinter-2.7.14.drv' failed with exit code 1
error: build of '/nix/store/6agv8zz900y5v6kah1nhllrx9pgjy10z-python2.7-tkinter-2.7.14.drv' failed
```

**Comment by knedlsepp** [comment]
Hm. That's odd. I'll try to figure out why it's not working. I didn't have that issue when creating the PR.

**Comment by LnL7** [comment]
Ofborg tests the merge, maybe something else broke it.

**Comment by Mic92** [comment]
if someone else broke a rebase should help.

**Comment by grahamc** [comment]
It doesn't evaluate on Darwin because it is not supported on Darwin:

```
grahamc@Morbo> HOME=/homeless-shelter NIX_PATH=nixpkgs=$(pwd) nix-instantiate ./default.nix -A pythonPackages.tkinter --option restrict-eval true --option build-timeout 1800 --argstr system x86_64-darwin --show-trace
error: while evaluating the attribute ‘handled’ at /home/grahamc/projects/nixpkgs/pkgs/stdenv/generic/check-meta.nix:203:3:
while evaluating ‘handleEvalIssue’ at /home/grahamc/projects/nixpkgs/pkgs/stdenv/generic/check-meta.nix:126:21, called from /home/grahamc/projects/nixpkgs/pkgs/stdenv/generic/check-meta.nix:204:10:
Package ‘python2.7-tkinter-2.7.14’ in /home/grahamc/projects/nixpkgs/pkgs/development/interpreters/python/cpython/2.7/default.nix:245 is not supported on ‘x86_64-darwin’, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.config/nixpkgs/config.nix.
```

**Comment by grahamc** [comment]
For more clarity:

```
  # Tkinter/tkinter is part of the Python standard library.
  # The Python interpreters in Nixpkgs come without tkinter by default.
  # To make the module available, we make it available as any other
  # Python package.
  tkinter = let
    py = python.override{x11Support=true;};
  in buildPythonPackage rec {
    name = "tkinter-${python.version}";
    src = py;
    format = "other";

    disabled = isPy26 || isPyPy;

    installPhase = ''
      # Move the tkinter module
      mkdir -p $out/${py.sitePackages}
      mv lib/${py.libPrefix}/lib-dynload/_tkinter* $out/${py.sitePackages}/
      # Update the rpath to point to python without x11Support
      old_rpath=$(patchelf --print-rpath $out/${py.sitePackages}/_tkinter*)
      new_rpath=$(sed "s#${py}#${python}#g" <<< "$old_rpath" )
      patchelf --set-rpath $new_rpath $out/${py.sitePackages}/_tkinter*
    '';

    meta = py.meta // {
      platforms = platforms.linux;
    };
  };
```

**Comment by FRidh** [comment]
Ah, right, in `python-packages.nix` we have for `tkinter`

```
    meta = py.meta // {
      platforms = platforms.linux;
    };
```
In any case, one could test here the derivation `pythonFull`

**Comment by grahamc** [comment]
I'm working to add evaluation outputs to these messages, but it is a bit complicated. For now, if the evaluator gives you confusing results, you might try testing yourself via the same command, also documented here: https://github.com/nixos/ofborg#how-does-ofborg-call-nix-instantiate

**Comment by LnL7** [comment]
@GrahamcOfBorg eval

**Comment by knedlsepp** [comment]
Oh. My bad. I must have mixed something up when building this on my machine.

**Comment by knedlsepp** [comment]
This should fix it now. When I tested this originally, I just built `python.override{x11Support=true;}` instead of `python.withPackages(ps: [ps.tkinter])`. The solitaire game `nix-build -A pysolfc && ./result/bin/pysol`, which depends on tkinter also runs fine now.

**Comment by LnL7** [comment]
@GrahamcOfBorg build pythonPackages.tkinter

**Comment by LnL7** [comment]
There we go 😄

**Review by LnL7 — APPROVED** [review]

**Comment by csawyerYumaed** [comment]
For nix morons like me, that get here and don't have tkinter and use nix-darwin:

environment.systemPackages =
[
pkgs.python36Full
pkgs.python36Packages.tkinter
]

worked for me:

/run/current-system/sw/bin/python3
Python 3.6.4 (default, Mar 21 2018, 14:15:32)
[GCC 4.2.1 Compatible Clang 5.0.1 (tags/RELEASE_501/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tkinter
>>>

**Pull request merged**
