### PR TITLE
gdal: fix standalone python programs

### PR DESCRIPTION
**Pull request by vbgl**
This addresses issue #9386.

@michelk: would you like to test? thanks.

### CODE REVIEW

**Comment by michelk** [comment]
Thanks a lot. Just tested locally and this does solve the issue.

**Comment by michelk** [comment]
I guess `QGIS` could be fixed in a similar way. Currently, when starting `QGIS`, I get

    Traceback (most recent call last):
      File "/nix/store/8hg8mmi8lb05a673jmv4dfs24hmfrwcs-gdal-2.0.0/lib/python2.7/site-packages/site.py", line 75, in <module>
        __boot()
      File "/nix/store/8hg8mmi8lb05a673jmv4dfs24hmfrwcs-gdal-2.0.0/lib/python2.7/site-packages/site.py", line 35, in __boot
        imp.load_module('site',stream,path,descr)
      File "/usr/lib/python2.7/site.py", line 563, in <module>
        main()
      File "/usr/lib/python2.7/site.py", line 545, in main
        known_paths = addusersitepackages(known_paths)
      File "/usr/lib/python2.7/site.py", line 272, in addusersitepackages
        user_site = getusersitepackages()
      File "/usr/lib/python2.7/site.py", line 247, in getusersitepackages
        user_base = getuserbase() # this will also set USER_BASE
      File "/usr/lib/python2.7/site.py", line 237, in getuserbase
        USER_BASE = get_config_var('userbase')
      File "/usr/lib/python2.7/sysconfig.py", line 582, in get_config_var
        return get_config_vars().get(name)
      File "/usr/lib/python2.7/sysconfig.py", line 528, in get_config_vars
        _init_posix(_CONFIG_VARS)
      File "/usr/lib/python2.7/sysconfig.py", line 412, in _init_posix
        from _sysconfigdata import build_time_vars
      File "/usr/lib/python2.7/_sysconfigdata.py", line 6, in <module>
        from _sysconfigdata_nd import *
    ImportError: No module named _sysconfigdata_nd

With the `nix-shell`-[trick](#9386), it works.

**Comment by vbgl** [comment]
@michelk could you be clearer about how you get this `QGIS` error, please? I cannot reproduce it.

**Comment by michelk** [comment]
I'm using `nixpkgs` on a debian system. 

With

```bash
nix-env -iA nixpkgs.qgis 
qgis
```

I'm getting the [error](https://github.com/NixOS/nixpkgs/pull/9423#issuecomment-134506156) listed above. 

Though
```bash
nix-shell -p python qgis
 qgis
```
works.

**Comment by vbgl** [comment]
Strange… Are you using any particular plug-in? Is this behaviour new or have you always got such an error?

**Comment by domenkozar** [comment]
If you fix qgis, I'll also push to release-15.09

**Comment by michelk** [comment]
I'm using some plug-ins, but when they were failing (eg. missing python-dependency), I got an error and the plugin was automatically disabled, but QGIS was running correctly. 

I never used nixpkgs-QGIS in production, since previously there was a [mismatch between compiled and running libpng](http://article.gmane.org/gmane.linux.distributions.nixos/14819/match=qgis); therefor I always used the debian-QGIS.

**Comment by vbgl** [comment]
I suggest to merge this PR, as it fixes an issue with `gdal`. I don’t understand what breaks `qgis`, so I can’t fix it.

**Pull request merged**
