### PR TITLE
linuxPackages_latest: update to linuxPackages_5_9

### PR DESCRIPTION
**Pull request by mweinelt**
The linux 5.9 package set was introduced in
0a614d2fb559115a63cd8ad66ed916f9d6c14ec7 but the linuxPackages_latest
packageset alias wasn't updated.

###### Motivation for this change

The update of the package set alias is missing. And I want the bluetooth stack updates. :smile: 

http://www.intel.com/content/www/us/en/security-center/advisory/intel-sa-00435.html
https://github.com/google/security-research/security/advisories/GHSA-h637-c88j-47wq

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by Emantor — APPROVED** [review]

**Comment by NeQuissimus** [comment]
@ofborg test latestKernel.login

**Review by NeQuissimus — APPROVED** [review]

**Comment by NeQuissimus** [comment]
Thanks, I had meant to do this yesterday but didn't have the time to make a PR or run the tests locally. So let's see what ofborg says :)

**Comment by NeQuissimus** [comment]
I am sure we will find something that's broken but that's the nature of the unstable/master :)

**Comment by mweinelt** [comment]
Thanks for mentioning the tests you use with ofborg. You probably meant @GrahamcOfBorg :)

**Comment by NeQuissimus** [comment]
No, the tests did run! Click "View details" on my merge commit. Ignore the failures for the hardened kernels, 5.8 hardened is currently broken.

**Pull request merged**
