### PR TITLE
Mark long-failing packages broken for 18.09 (2)

### PR DESCRIPTION
**Pull request by xeji**
###### Motivation for this change

ZHF #45960 . Continuation of #46385.  I'll keep adding broken packages as I find them.

### CODE REVIEW

**Comment by xeji** [comment]
cc respective maintainers:

- acl2: @7c6f434c @kini
- enlightenment.rage: @romildo @matejc @ftrvxmtrx 
- libretro.mame: @edwtjo @hrdinka @MP2E

**Comment by xeji** [comment]
eztrace: cc maintainer @Fuuzetsu

**Comment by 7c6f434c** [comment]
`acl2`: I guess no point in waiting for release, and the patch that solves the immediate problem is not applicable directly to 8.0, and it doesn't look like they have many regressions, so a pre-release bump: de764e65f0d655c6cdd9fca23abd101290a2a6b6

**Comment by 7c6f434c** [comment]
`acl2`: I guess no point in waiting for release, and the patch that solves the immediate problem is not applicable directly to 8.0, and it doesn't look like they have many regressions, so a pre-release bump: de764e65f0d655c6cdd9fca23abd101290a2a6b6

**Comment by xeji** [comment]
@7c6f434c : thanks! Can I backport the fix to 18.09?

**Comment by 7c6f434c** [comment]
Sure, we probably won't have anything better anyway.

**Comment by xeji** [comment]
`acl2`: backported in d10c5b88de7

**Comment by hrdinka** [comment]
`libretro.mame`: I'm on it. It's currently compiling since hours, I'll commit a patch once it's finished.

**Comment by kini** [comment]
`acl2`: ACL2 devs just cut an 8.1 release a couple days ago, and @7c6f434c the commit you've designated as "8.0.post.2018.09.20" is actually after the 8.1 release. Why not just bump to 8.1? I haven't been following the build failures (sorry) but I imagine that whatever fix you needed from 531089336bb1734ff82c7b3b3fc05917451db770 is present in 8.1 as well.

**Comment by 7c6f434c** [comment]
Yes, the fix is quite old. I looked at the list of the GitHub releases/tags and saw only 8.0. Rolling back to 8.1 is probably a good idea.

**Comment by xeji** [comment]
`monodevelop`: cc @obadz

**Comment by xeji** [comment]
Thank you @romildo for fixing `enlightenment.rage`!

**Comment by 7c6f434c** [comment]
OK, switched `acl2` to 8.1 in 60b6d5f8a8c5c2f2e50e446dbe0e07575b535e82

**Comment by xeji** [comment]
`acl2:` picked 8.1 to 18.09 in fd6930685c1

**Comment by xeji** [comment]
(I'm just reverting these to keep track. Will cleanup before merge.)

**Comment by Fuuzetsu** [comment]
>eztrace: cc maintainer @Fuuzetsu

unable to do maintenance, feel free to do anything (disable)

**Comment by xeji** [comment]
`eztrace` was just fixed in #47282. 
Out of the 7 packages added to this list, 4 have already been fixed. Awesome!

**Comment by xeji** [comment]
backported in  294060d1630..69514d78a6b

**Pull request merged**
