### PR TITLE
sublime3: make sublime text work with pkexec and gksudo

### PR DESCRIPTION
**Pull request by demin-dmitriy**
When sublime doesn't have rights to write a file, it asks for root rights by calling either
`/usr/bin/gksudo /bin/cp TMP_FILE FILE`
or
`/usr/bin/pkexec /bin/cp TMP_FILE FILE`
whichever it finds first.
Paths `/usr/bin/pkexec`, `/usr/bin/gksudo` and `/bin/cp` are all hardcoded in sublime_text binary. `/bin/cp` can be simply replaced by `cp` in binary itself (and padded with necessary amount of zero bytes), but to deal with `/usr/bin/pkexec` and `/usr/bin/gksudo` we have to use LD_PRELOAD trick to intercept glibc calls.

Tested it locally with system="i686-linux" and system="x86_64-linux".

cc @wmertens.

### CODE REVIEW

**Comment by wmertens** [comment]
LGTM, but why not rewrite the paths in binary like cp?

Note that I use Atom now, so if you would like to set yourself as
maintainer that would be great…

On Wed, Oct 21, 2015, 18:43 Demin Dmitriy <notifications@github.com> wrote:

> When sublime doesn't have rights to write a file, it asks for root rights
> by calling
> /usr/bin/pkexec /bin/cp TMP_FILE FILE.
> (it also attempts to call gksudo, but we don't have gksudo in nixpkgs)
> Paths /usr/bin/pkexec and /bin/cp are hardcoded in sublime_text binary.
> /bin/cp can be simply replaced by cp in binary itself (and padded with
> necessary amount of zero bytes), but to deal with /usr/bin/pkexec we have
> to use LD_PRELOAD trick to intercept glibc calls.
>
> Tested it locally with system="i686-linux" and system="x86_64-linux".
>
> cc @wmertens <https://github.com/wmertens>.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/NixOS/nixpkgs/pull/10517
> Commit Summary
>
>    - sublime3: fixed pkexec paths
>
> File Changes
>
>    - *M* pkgs/applications/editors/sublime3/default.nix
>    <https://github.com/NixOS/nixpkgs/pull/10517/files#diff-0> (10)
>    - *M* pkgs/build-support/libredirect/libredirect.c
>    <https://github.com/NixOS/nixpkgs/pull/10517/files#diff-1> (21)
>
> Patch Links:
>
>    - https://github.com/NixOS/nixpkgs/pull/10517.patch
>    - https://github.com/NixOS/nixpkgs/pull/10517.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/pull/10517>.
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by demin-dmitriy** [comment]
The reason why we can't just rewrite strings in binary is that if you change the length of the string then you'll essentially shift all bytes after that point. I believe most, if not all executable formats including ELF are very sensitive to this kind of change and it will corrupt file (most likely you'll get SIGSEGV).

But usually strings in binary are C-strings, so we can shorten them by replacing unnecessary bytes with \0. So I changed `/bin/cp` to `cp` and leave pkexec/gksudo to figure out actual file path by searching in  PATH.

We can't do the same with gksudo/pkexec because sublime_text tries to make `stat` syscal before calling them and stat requires full path. But we can't rewrite `/usr/bin/gksudo` to full path (`/nix/store/.../bin/gksudo`) because it's too long.

I know, it's all dirty tricks, but there is not so much that you can do with compiled binary.

**Comment by demin-dmitriy** [comment]
Alright, I added myself as a maintainer.

**Comment by wmertens** [comment]
Indeed, that all makes sense. One more request: could you convert this PR into two commits, one for the libredirect change and one for using it with sublime? Then I'll merge. We like pretty commits in nixpkgs :)

**Comment by demin-dmitriy** [comment]
Done.

**Comment by wmertens** [comment]
:beers:

**Pull request merged**
