### PR TITLE
nixos/redis Add connection wait script to ensure connections can be made to redis

### PR DESCRIPTION
**Pull request by jappeace**
###### Motivation for this change

We had an issue where our application would
start to early and crashed because redis connections
weren't available yet.

Adding this should ensure connections can be made to
redis. (and we can safely requires= ["redis.service"])

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by alyssais** [comment]
Redis appears to support systemd readiness notification, which would be more more efficient than polling. Can you see if adding `--supervised systemd` and setting Type=notify solves the problem for you?

**Comment by jappeace** [comment]
So this is the error we got:

image

It's configured properly though:

image

Note that postgres does this as well:

https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/databases/postgresql.nix#L319

I'd call this a bug yes, but same for postgres. Why is it giving the ready signal while it's still loading?

**Comment by jappeace** [comment]
I'm not sure if this works at all, we still have the issue.

**Comment by aanderse** [comment]
Did anyone ever dig deeper on this and find a cause?

**Comment by jappeace** [comment]
No I kindoff forgot about it.

**Comment by jappeace** [comment]
github for some reason thought this was related to my melpa changes so I just closed it :shrug:

**Pull request closed without merging**
