### PR TITLE
wayland-logout: init at 1.4

### PR DESCRIPTION
**Pull request by quantenzitrone**
## Description of changes

A simple package that logs you out of any Wayland compositor.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Quantenzitrone** [comment]
as far as i see, this is the first pr using the new `pkgs/by-name` structure introduced in #237439 :tada:

**Comment by Quantenzitrone** [comment]
@wegank why  homepage -> website? [Website is not a documented meta attribute](https://nixos.org/manual/nixpkgs/unstable/#sec-standard-meta-attributes).
Also, wouldn't it be easier to just wait until RFC 101 gets merged, and the whole codebase gets autoformatted before we try to enforce rules like spaces in lists.

**Comment by wegank** [comment]
> @wegank why homepage -> website? [Website is not a documented meta attribute](https://nixos.org/manual/nixpkgs/unstable/#sec-standard-meta-attributes).

What I've done is website -> homepage. The PR also had `meta.licenses`, which is not a valid attribute.

> Also, wouldn't it be easier to just wait until RFC 101 gets merged, and the whole codebase gets autoformatted before we try to enforce rules like spaces in lists.

This is what a formatter expects to produce, but the change is indeed not necessary here.

**Comment by Quantenzitrone** [comment]
oh bruh sorry im dumb
i'm going to have to be more careful for these attributes

**Comment by Quantenzitrone** [comment]
another thing: why remove the trailing comma for ninja?

now ninja always has to be the last argument, because any argument added after ninja would need to change 2 lines
```diff
- ninja
+ ninja,
+ anotherdependency
```
as far as i know, nix has no problem with trailing commas in function arguments, 
so even if you remove the `...`, the trailing comma could've stayed

**Pull request merged**
