### PR TITLE
clash-meta: init at 1.12.0

### PR DESCRIPTION
**Pull request by oluceps**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by contrun** [comment]
Why is this PR closed?

**Comment by oluceps** [comment]
> Why is this PR closed?

clash.meta is a fork of clash, I tried simply made an overlay for [clash](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/networking/clash/default.nix) and works well. So i think it's not necessary for packaging a new one.

**Comment by contrun** [comment]
I find clash-meta more feature-rich (e.g. having tun/tap support), so I was to try out it. I found your pr. I think clash-meta may be of some use any way.

**Comment by oluceps** [comment]
> I find clash-meta more feature-rich (e.g. having tun/tap support), so I was to try out it. I found your pr. I think clash-meta may be of some use any way.

I think so. I opened a new pr #191365

**Comment by oluceps** [comment]
> > I find clash-meta more feature-rich (e.g. having tun/tap support), so I was to try out it. I found your pr. I think clash-meta may be of some use any way.
> 
> I think so. I opened a new pr #191365

And now I found it not works with simply overriding clash package. So packaging it might be a great decision

**Pull request closed without merging**
