### PR TITLE
Luarocks pyupdater followup

### PR DESCRIPTION
**Pull request by teto**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by teto** [comment]
I've checked all updaters keep working. The lua updater is much much faster with the proc mechanism (the old bash script relied on parallel but it never worked for me). The luarocks update doesn't rewrite_input as vim does but I hope it can some day.

**Comment by lovesegfault** [comment]
This broke the script for me:

```
❯ ./maintainers/scripts/update-luarocks-packages 
Traceback (most recent call last):
  File "/home/bemeurer/src/nixpkgs/./maintainers/scripts/update-luarocks-packages", line 193, in <module>
    main()
  File "/home/bemeurer/src/nixpkgs/./maintainers/scripts/update-luarocks-packages", line 188, in main
    update_plugins(editor, args)
  File "/home/bemeurer/src/nixpkgs/maintainers/scripts/pluginupdate.py", line 553, in update_plugins
    update = editor.get_update(args.input_file, args.outfile, args.proc)
  File "/home/bemeurer/src/nixpkgs/./maintainers/scripts/update-luarocks-packages", line 113, in get_update
    cache: Cache = Cache(self.cache_file)
TypeError: __init__() missing 1 required positional argument: 'cache_file_name'
```

If I revert this change it works again (`git revert -m 1 4de33380ef1`)

**Comment by teto** [comment]
arf thanks for catching it https://github.com/NixOS/nixpkgs/pull/133685

**Comment by figsoda** [comment]
pretty sure this broke `pkgs/misc/vim-plugins/update.py` for me
```
❯ GITHUB_API_TOKEN=~/gh ./update.py --add allendang/nvim-expand-expr@main
warning: unknown setting 'experimental-features'
847 plugins were checked
updated /home/figsoda/.nixpkgs/pkgs/misc/vim-plugins/generated.nix
committing to nixpkgs "vimPlugins: update"
848 plugins were checked
updated /home/figsoda/.nixpkgs/pkgs/misc/vim-plugins/generated.nix
Traceback (most recent call last):
  File "/home/figsoda/.nixpkgs/pkgs/misc/vim-plugins/./update.py", line 94, in <module>
    main()
  File "/home/figsoda/.nixpkgs/pkgs/misc/vim-plugins/./update.py", line 90, in main
    pluginupdate.update_plugins(editor, args)
  File "/home/figsoda/.nixpkgs/maintainers/scripts/pluginupdate.py", line 575, in update_plugins
    plugin = fetch_plugin_from_pluginline(plugin_line)
  File "/home/figsoda/.nixpkgs/maintainers/scripts/pluginupdate.py", line 350, in fetch_plugin_from_pluginline
    plugin, _ = prefetch_plugin(*parse_plugin_line(plugin_line))
TypeError: pluginupdate.prefetch_plugin() argument after * must be an iterable, not PluginDesc
```

**Comment by teto** [comment]
Indeed, I had not tested `--add`, here https://github.com/NixOS/nixpkgs/pull/133832 is a fix (hopefully)

**Comment by figsoda** [comment]
I think there is still a regression that inserts a bunch of spaces in the generated file

https://github.com/NixOS/nixpkgs/pull/133844

**Comment by teto** [comment]
thanks for taking care of this.

**Pull request merged**
