### PR TITLE
prisma-engines: 3.14.0 -> 3.15.1

### PR DESCRIPTION
**Pull request by pimeys**
###### Description of changes

Changes since 3.14.0:

- https://github.com/prisma/prisma/releases/tag/3.15.0
- https://github.com/prisma/prisma/releases/tag/3.15.1

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by tomhoule — COMMENTED** [review]
lgtm

**Review by superherointj — APPROVED** [review]
LGTM

**Comment by superherointj** [comment]
@pimeys As there are tests now it is possible to automate the upgrade process (so you don't have to manually do it yourself). An update script is necessary to update the two packages at once and keep version in sync. But should be simple. It's just a suggestion.

**Comment by pimeys** [comment]
I'm doing the engines with `nix-update` and it works superb. With the node package it just crashes, even if we set the version statically in the overrides.

That would be great so we could automate everything, no matter how much I enjoy doing these PRs :)

**Comment by superherointj** [comment]
> With the node package it just crashes, even if we set the version statically in the overrides.

On reading [the manual on JS packages](https://nixos.org/manual/nixpkgs/unstable/#javascript-packages-nixpkgs):
```
A JS package (manually packaged in nixpkgs) should only provide end user software packages, such as CLIs. Libraries should only be added to the package set if there is a `non-NPM package` that requires it.

When it is desired to use NPM libraries in a development project, use the `node2nix` generator directly on the `package.json` configuration file of the *project*.
```

Is the package `nodePackages.prisma` used by the `prisma-engines` package or the other way around?
If not, maybe `nodePackages.prisma` package could be removed from nixpkgs so it is downloaded directly by the JS/npm project fetcher instead from nixpkgs. And prisma JS package would be kept at sync at `package.json` at JS side instead of from Nix side?

**Comment by pimeys** [comment]
The engines must be there though and the flake/shell definition must have the env vars for the CLI to work, but yes that sounds feasible.

The only thing what I'm thinking is there might be people who want the CLI to their system.

**Comment by superherointj** [comment]
This PR is ready to be merged.

**Comment by superherointj** [comment]
@bobby285271 Beyond me, @tomhoule has also approved it. He left a message saying `lgtm`. Isn't that good enough?

**Comment by bobby285271** [comment]
The labels are semi-automatic updated by https://github.com/nix-community/label-approved

**Comment by tomhoule** [comment]
I didn't click approve but just signaled that I read the PR because I'm just someone who works at Prisma and uses nix, I don't consider myself a qualified nixpkgs reviewer :)

**Pull request merged**
