### PR TITLE
pkgconfig: 0.29 -> 0.29.1

### PR DESCRIPTION
**Pull request by ndowens**
###### Motivation for this change

Update
###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by globin** [comment]
Please base mass-rebuilds on staging, and why didn't you just rebase the other PR?

**Comment by ndowens** [comment]
I panicked a little. I was playing with git one two repos that doesn't even use the repo I use for pkging and it messed it up and didn't want someone to accidentally merge it

**Comment by ndowens** [comment]
I'll rebase as soon as I can

**Comment by ndowens** [comment]
@globin It has been rebased for staging

**Pull request merged**
