### PR TITLE
unbound: Add mingw32 support

### PR DESCRIPTION
**Pull request by seanybaggins**
## Description of changes
Added mingw32 hostPlatfrom build support.

## Things done

Needed for https://github.com/NixOS/nixpkgs/issues/274274

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by ajs124 — COMMENTED** [review]
can't this use `lib.meta.availableOn`? iirc that's the preferred pattern.

**Comment by seanybaggins** [comment]
> can't this use `lib.meta.availableOn`? iirc that's the preferred pattern.

Can you link to an example?

**Comment by seanybaggins** [comment]
> can't this use `lib.meta.availableOn`? iirc that's the preferred pattern.

Okay found an example. If you are asking about the withMakeWrapper option, I think the answer is no. 
```
nix-repl> lib.meta.availableOn pkgsCross.mingw32.stdenv.hostPlatform pkgsCross.mingw32.makeWrapper
true
```
I think this response should be false. makeWrapper does not work when you try to target mingw. This is because bash is not a supported target for mingw32.

**Comment by seanybaggins** [comment]
If I have addressed the comments in the PR, can this get merged? If not what else needs to be done for this to be accepted?

**Comment by seanybaggins** [comment]
Did this get pushed to staging? Should I close this PR?

**Comment by wegank** [comment]
No, this isn't in staging.

**Comment by seanybaggins** [comment]
I got confused. I wasn't aware that you were able to do a force push of a branch that existed in my fork. Thanks for setting me straight.

**Review by wegank — APPROVED** [review]

**Comment by Ericson2314** [comment]
This can be a separate PR to avoid `staging`, but someone should clean up this file using `lib.{with,enable}Feature{,As}`.

**Pull request merged**
