### PR TITLE
python310Packages.argcomplete: 2.0.0 -> 2.1.1

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
@ofborg build commitizen

Breaks for me, nixos x86_64

**Comment by risicle** [comment]
@ofborg build gallia

Fails for me, nixos x86_64

**Comment by SuperSandro2000** [comment]
> @ofborg build gallia
> 
> Fails for me, nixos x86_64

> ERROR: Could not find a version that satisfies the requirement setuptools (from python-can) (from versions: none)
> ERROR: No matching distribution found for setuptools

The maintainer needs to maintain their package.

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 220237` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>apache-airflow</li>
    <li>python310Packages.apache-airflow</li>
    <li>python311Packages.apache-airflow</li>
  </ul>
</details>
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>checkov</li>
    <li>commitizen</li>
    <li>datalad</li>
    <li>diffoscope</li>
    <li>dvc-with-remotes</li>
    <li>vscode-extensions.ms-python.python</li>
  </ul>
</details>
<details>
  <summary>50 packages built:</summary>
  <ul>
    <li>azure-cli</li>
    <li>barman</li>
    <li>clickable</li>
    <li>cloud-custodian</li>
    <li>cmake-language-server</li>
    <li>cwltool</li>
    <li>diffoscopeMinimal</li>
    <li>expliot</li>
    <li>gallia</li>
    <li>git-aggregator</li>
    <li>linkchecker</li>
    <li>nuget-to-nix</li>
    <li>pipx (python310Packages.pipx)</li>
    <li>pubs</li>
    <li>python310Packages.amcrest</li>
    <li>python310Packages.argcomplete</li>
    <li>python310Packages.can</li>
    <li>python310Packages.canopen</li>
    <li>python310Packages.enhancements</li>
    <li>python310Packages.jedi-language-server</li>
    <li>python310Packages.knack</li>
    <li>python310Packages.lsprotocol</li>
    <li>python310Packages.milc</li>
    <li>python310Packages.msgspec</li>
    <li>python310Packages.nox</li>
    <li>python310Packages.pygls</li>
    <li>ssh-mitm (python310Packages.ssh-mitm)</li>
    <li>yq (python310Packages.yq)</li>
    <li>python311Packages.amcrest</li>
    <li>python311Packages.argcomplete</li>
    <li>python311Packages.can</li>
    <li>python311Packages.canopen</li>
    <li>python311Packages.enhancements</li>
    <li>python311Packages.jedi-language-server</li>
    <li>python311Packages.knack</li>
    <li>python311Packages.lsprotocol</li>
    <li>python311Packages.milc</li>
    <li>python311Packages.msgspec</li>
    <li>python311Packages.nox</li>
    <li>python311Packages.pipx</li>
    <li>python311Packages.pygls</li>
    <li>python311Packages.ssh-mitm</li>
    <li>python311Packages.yq</li>
    <li>qmk</li>
    <li>stubby</li>
    <li>styx</li>
    <li>tockloader</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>wlc</li>
    <li>ycmd</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 220237` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>apache-airflow</li>
    <li>python310Packages.apache-airflow</li>
    <li>python311Packages.apache-airflow</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>checkov</li>
    <li>dvc-with-remotes</li>
  </ul>
</details>
<details>
  <summary>53 packages built:</summary>
  <ul>
    <li>azure-cli</li>
    <li>barman</li>
    <li>clickable</li>
    <li>cloud-custodian</li>
    <li>commitizen</li>
    <li>cwltool</li>
    <li>datalad</li>
    <li>diffoscope</li>
    <li>diffoscopeMinimal</li>
    <li>expliot</li>
    <li>gallia</li>
    <li>git-aggregator</li>
    <li>linkchecker</li>
    <li>nuget-to-nix</li>
    <li>pipx (python310Packages.pipx)</li>
    <li>pubs</li>
    <li>python310Packages.amcrest</li>
    <li>python310Packages.argcomplete</li>
    <li>python310Packages.can</li>
    <li>python310Packages.canopen</li>
    <li>python310Packages.enhancements</li>
    <li>python310Packages.jedi-language-server</li>
    <li>python310Packages.knack</li>
    <li>python310Packages.lsprotocol</li>
    <li>python310Packages.milc</li>
    <li>python310Packages.msgspec</li>
    <li>python310Packages.nox</li>
    <li>python310Packages.pygls</li>
    <li>ssh-mitm (python310Packages.ssh-mitm)</li>
    <li>yq (python310Packages.yq)</li>
    <li>python311Packages.amcrest</li>
    <li>python311Packages.argcomplete</li>
    <li>python311Packages.can</li>
    <li>python311Packages.canopen</li>
    <li>python311Packages.enhancements</li>
    <li>python311Packages.jedi-language-server</li>
    <li>python311Packages.knack</li>
    <li>python311Packages.lsprotocol</li>
    <li>python311Packages.milc</li>
    <li>python311Packages.msgspec</li>
    <li>python311Packages.nox</li>
    <li>python311Packages.pipx</li>
    <li>python311Packages.pygls</li>
    <li>python311Packages.ssh-mitm</li>
    <li>python311Packages.yq</li>
    <li>qmk</li>
    <li>stubby</li>
    <li>styx</li>
    <li>tockloader</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vscode-extensions.ms-python.python</li>
    <li>wlc</li>
    <li>ycmd</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 220237` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>apache-airflow</li>
    <li>python310Packages.apache-airflow</li>
    <li>python311Packages.apache-airflow</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>checkov</li>
    <li>dvc-with-remotes</li>
  </ul>
</details>
<details>
  <summary>53 packages built:</summary>
  <ul>
    <li>azure-cli</li>
    <li>barman</li>
    <li>clickable</li>
    <li>cloud-custodian</li>
    <li>commitizen</li>
    <li>cwltool</li>
    <li>datalad</li>
    <li>diffoscope</li>
    <li>diffoscopeMinimal</li>
    <li>expliot</li>
    <li>gallia</li>
    <li>git-aggregator</li>
    <li>linkchecker</li>
    <li>nuget-to-nix</li>
    <li>pipx (python310Packages.pipx)</li>
    <li>pubs</li>
    <li>python310Packages.amcrest</li>
    <li>python310Packages.argcomplete</li>
    <li>python310Packages.can</li>
    <li>python310Packages.canopen</li>
    <li>python310Packages.enhancements</li>
    <li>python310Packages.jedi-language-server</li>
    <li>python310Packages.knack</li>
    <li>python310Packages.lsprotocol</li>
    <li>python310Packages.milc</li>
    <li>python310Packages.msgspec</li>
    <li>python310Packages.nox</li>
    <li>python310Packages.pygls</li>
    <li>ssh-mitm (python310Packages.ssh-mitm)</li>
    <li>yq (python310Packages.yq)</li>
    <li>python311Packages.amcrest</li>
    <li>python311Packages.argcomplete</li>
    <li>python311Packages.can</li>
    <li>python311Packages.canopen</li>
    <li>python311Packages.enhancements</li>
    <li>python311Packages.jedi-language-server</li>
    <li>python311Packages.knack</li>
    <li>python311Packages.lsprotocol</li>
    <li>python311Packages.milc</li>
    <li>python311Packages.msgspec</li>
    <li>python311Packages.nox</li>
    <li>python311Packages.pipx</li>
    <li>python311Packages.pygls</li>
    <li>python311Packages.ssh-mitm</li>
    <li>python311Packages.yq</li>
    <li>qmk</li>
    <li>stubby</li>
    <li>styx</li>
    <li>tockloader</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vscode-extensions.ms-python.python</li>
    <li>wlc</li>
    <li>ycmd</li>
  </ul>
</details>

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 220237` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>apache-airflow</li>
    <li>python310Packages.apache-airflow</li>
    <li>python311Packages.apache-airflow</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>dvc-with-remotes</li>
  </ul>
</details>
<details>
  <summary>54 packages built:</summary>
  <ul>
    <li>azure-cli</li>
    <li>barman</li>
    <li>checkov</li>
    <li>clickable</li>
    <li>cloud-custodian</li>
    <li>commitizen</li>
    <li>cwltool</li>
    <li>datalad</li>
    <li>diffoscope</li>
    <li>diffoscopeMinimal</li>
    <li>expliot</li>
    <li>gallia</li>
    <li>git-aggregator</li>
    <li>linkchecker</li>
    <li>nuget-to-nix</li>
    <li>pipx (python310Packages.pipx)</li>
    <li>pubs</li>
    <li>python310Packages.amcrest</li>
    <li>python310Packages.argcomplete</li>
    <li>python310Packages.can</li>
    <li>python310Packages.canopen</li>
    <li>python310Packages.enhancements</li>
    <li>python310Packages.jedi-language-server</li>
    <li>python310Packages.knack</li>
    <li>python310Packages.lsprotocol</li>
    <li>python310Packages.milc</li>
    <li>python310Packages.msgspec</li>
    <li>python310Packages.nox</li>
    <li>python310Packages.pygls</li>
    <li>ssh-mitm (python310Packages.ssh-mitm)</li>
    <li>yq (python310Packages.yq)</li>
    <li>python311Packages.amcrest</li>
    <li>python311Packages.argcomplete</li>
    <li>python311Packages.can</li>
    <li>python311Packages.canopen</li>
    <li>python311Packages.enhancements</li>
    <li>python311Packages.jedi-language-server</li>
    <li>python311Packages.knack</li>
    <li>python311Packages.lsprotocol</li>
    <li>python311Packages.milc</li>
    <li>python311Packages.msgspec</li>
    <li>python311Packages.nox</li>
    <li>python311Packages.pipx</li>
    <li>python311Packages.pygls</li>
    <li>python311Packages.ssh-mitm</li>
    <li>python311Packages.yq</li>
    <li>qmk</li>
    <li>stubby</li>
    <li>styx</li>
    <li>tockloader</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vscode-extensions.ms-python.python</li>
    <li>wlc</li>
    <li>ycmd</li>
  </ul>
</details>

**Review by fabaff — APPROVED** [review]
Change looks good to me.

**Pull request merged**
