### PR TITLE
go: buildGoPackage: 1.8 -> 1.9

### PR DESCRIPTION
**Pull request by orivej**
###### Motivation for this change

- gcsfuse 0.23.0 has become compatible with go1.9
- syncthing012: go1.9 requires that `-tags` are space separated
- envoy was broken before this change
- #29489

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by orivej** [comment]
CC @cstrahan, @wkennington.

**Comment by orivej** [comment]
I've finished testing with `nox-review wip` on Linux. Now I'd wait for https://github.com/golang/go/issues/21825.

**Comment by orivej** [comment]
@globin This rebuilds 245 derivations with Go 1.9. I think that this is not too much and may be merged to `master`. Is that OK?
<sub><sup>acbuild altcoins.go-ethereum altcoins.go-ethereum-classic aptly assh awless azure-vhd-utils boringssl bosun browserpass c14 caddy cadvisor camlistore cayley certstrap cfssl cide cloud-print-connector cni cockroachdb codesearch compile-daemon confd consul consul-alerts consul-template container-linux-config-transpiler containerd convoy coredns coyim ctop curl_unix_socket deis deisctl delve dex-oidc dgraph direnv docker docker-distribution docker-gc docker-machine docker-machine-kvm docker-proxy docker_17_06 doctl drive drone ecs-agent elvish envconsul etcd exercism filebeat filegive flannel fleet fscrypt-experimental fsql fzf gawp gcsfuse gdrive ghq git-lfs git-lfs1 gitAndTools.git-annex-remote-b2 gitAndTools.git-annex-remote-rclone gitAndTools.hub gitaly gitlab-runner gitlab-runner_1_11 gitlab-shell gitlab-workhorse glide glock go go-bindata go-bindata-assetfs go-dependency-manager go-md2man go-mtpfs go-pup go-repo-root go-sct go-upower-notify go2nix goa gocode gocryptfs godef godep gogs goimports golint gopherclient gosu gotags gotools gotty govers gox grafana gx gx-go heapster heartbeat hecate hologram hound httplab hugo i3cat influxdb interlock ipfs jd jid jmespath journalbeat jp kapacitor kbfs keybase keybase-go kops kt kube-aws kubernetes kubernetes-helm leaps lf linuxkit loccount logstash-forwarder lxd madonctl mailhog manul marathonctl matterbridge matterircd mesos-dns metricbeat minify minikube minio minio-client mirrorbits mm mmake moby mongodb-tools mop mqtt-bench mynewt-newt ngrok-1 nomad nsq oauth2_proxy oh openshift pachyderm packer packet packetbeat panamax_api peco phraseapp-client pipework platinum-searcher pond pprof prom2json prometheus prometheus-alertmanager prometheus-bind-exporter prometheus-blackbox-exporter prometheus-collectd-exporter prometheus-consul-exporter prometheus-fritzbox-exporter prometheus-haproxy-exporter prometheus-json-exporter prometheus-mesos-exporter prometheus-mysqld-exporter prometheus-nginx-exporter prometheus-node-exporter prometheus-openvpn-exporter prometheus-pushgateway prometheus-snmp-exporter prometheus-statsd-bridge prometheus-statsd-exporter prometheus-unifi-exporter prometheus-varnish-exporter python27Packages.syncthing-gtk qsyncthingtray rancher-compose rancher-compose_0_10 rclone restic rkt runc s3gof3r scaleway-cli serfdom shfmt sift skopeo skydns sops ssm-agent styx syncthing syncthing-inotify syncthing-tray syncthing012 syncthing013 systemd-journal2gelf telegraf terminal-parrot terraform terraform-inventory terraform_0_10 terraform_0_10-full terraform_0_8 terraform_0_8_5 terragrunt terragrunt_0_11_1 terragrunt_0_9_8 textql tmsu traefik ua uchiwa vault vimPlugins.YouCompleteMe vndr vultr wego wuzz xmpp-client xurls ycmd</sup></sub>

**Comment by globin** [comment]
Master is fine for me anyway, but please don't cherry-pick to the release branch.

**Comment by copumpkin** [comment]
It seems a little odd to me (to the point of causing me to second guess myself for the past 15 minutes) that the release branch has `go = go_1_9`, but `buildGoPackage = buildGo18Package`.

**Comment by orivej** [comment]
Do you have a preference about what to have in release, `go = go_1_8` or `buildGoPackage = buildGo19Package`? I don't expect that one option is more difficult to maintain than another.

**Comment by copumpkin** [comment]
Slight preference towards 1.9 because Terraform wants 1.9 and we reverted the commit that upgraded to the latest Terraform because `buildGoPackage` was on 1.8. But if we go with 1.8 I'd think it should probably be consistent across the two. In general it probably makes sense for the two attributes to automatically sync up (so `buildGoPackage` would be expressed in terms of `go` and thus automatically follow the same version)

**Comment by orivej** [comment]
Released in 87bfe2c74724e1a3a50ef773565fae9edc1523f9.

**Comment by copumpkin** [comment]
Thanks!

**Pull request merged**
