### PR TITLE
mdbook: init at 0.1.3

### PR DESCRIPTION
**Pull request by Havvy**
###### Motivation for this change

I want to install mdbook for work on the Rust reference using nixpkgs instead of via `cargo install`.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build mdbook

**Comment by Havvy** [comment]
I don't have a MacOS system nor know anything about it. How would I fix the failure?

**Comment by Mic92** [comment]
@GrahamcOfBorg build mdbook

**Comment by Mic92** [comment]
@LnL7 does rust also respect NIX_LDFLAGS on darwin?

**Comment by LnL7** [comment]
@GrahamcOfBorg build mdbook

**Comment by Havvy** [comment]
Marked as broken on Darwin. aarch64 is failing because it's trying to build LLVM and timing out.

**Pull request merged**
