### PR TITLE
meson/setup-hook.sh: make build directory configurable

### LINKED ISSUE #335818: Introduce `mesonBuildDir`
#170697 introduced `cmakeBuildDir`, we want the same thing for Meson for the same reasons.

Beyond the reasons given in that PR there is one additional one:

During local development is is very nice to have multiple dev shells building the project for different platform. For this to work, we need each dev shell / incremental build to by siloed in a separate build directory. If we can specify a separate `cmakeBuildDir` in each dev shell, this becomes more convenient.

### PR DESCRIPTION
**Pull request by fricklerhandwerk**
## Description of changes

closes https://github.com/NixOS/nixpkgs/issues/335818 @Ericson2314

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by Ericson2314 — APPROVED** [review]
Just needs to point to `staging` instead

**Review by winterqt — COMMENTED** [review]
Worth adding to the [docs](https://github.com/NixOS/nixpkgs/blob/master/doc/hooks/meson.section.md).

**Comment by Ericson2314** [comment]
https://github.com/NixOS/nixpkgs/blob/master/doc/hooks/cmake.section.md Boo the CMake equivalent doesn't document this either, so we can't just cut and paste.

**Review by Ericson2314 — APPROVED** [review]

**Comment by Ericson2314** [comment]
I tested this with 

```diff
diff --git a/pkgs/development/libraries/frozen/default.nix b/pkgs/development/libraries/frozen/default.nix
index 26c47617c1f6..2681c377977b 100644
--- a/pkgs/development/libraries/frozen/default.nix
+++ b/pkgs/development/libraries/frozen/default.nix
@@ -19,6 +19,10 @@ stdenv.mkDerivation rec {

   nativeBuildInputs = [ meson ninja ];

+  preHook = "set -x";
+
+  mesonBuildDir = "asdf";
+
   # frozen has a simple Makefile and a GN BUILD file as building scripts.
   # Since it has only two source files, the best course of action to support
   # cross compilation is to create a small meson.build file.
```

**Review by Ericson2314 — APPROVED** [review]

**Pull request merged**
