### PR TITLE
WIP: openssl: add ubuntu version symbols to openssl-steam

### PR DESCRIPTION
**Pull request by corngood**
###### Motivation for this change

This adds STEAM_1.0.0 etc symbols via the version-script.patch from ubuntu to the steam-specific build of openssl.

@FRidh could you see if this fixes the game you were having trouble with, and reference the issue once you've created it?

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by edolstra** [comment]
* This is a huge patch. Could it be fetched using fetchurl instead of keeping it in tree?

* How is this patch going to be maintained? We frequently need to do urgent OpenSSL upgrades so we don't want to have figure out how to update this patch first.

* Maybe this patch can be applied to the OpenSSL used by Steam only? It does not seem relevant anywhere else.

**Comment by corngood** [comment]
> This is a huge patch. Could it be fetched using fetchurl instead of keeping it in tree?

I pulled it out of the ubuntu src tarball.  I could probably find a way to automate that, but I'm not sure how reliable it would be (are there suitable permalinks?).  It's 100kb and 4k lines, and 25kb gzipped.  It's basically just a list of all public symbols grouped by the version where they were introduced.

I'll do a bit of investigating to see if it's machine-generated and who/what maintains it.

> How is this patch going to be maintained? We frequently need to do urgent OpenSSL upgrades so we don't want to have figure out how to update this patch first.

It shouldn't require any maintenance (for this purpose) unless you are trying to roll-back to pre-1.0.2, or if the steam runtime moves to a newer version, and even then it could only break things in steam-land that need the new symbols.

> Maybe this patch can be applied to the OpenSSL used by Steam only? It does not seem relevant anywhere else.

That's what's happening with this patch.  It should have zero impact outside of the steam chroot environment.

**Comment by corngood** [comment]
This is WIP because @FRidh reported a crash in a commercial game (Wargame: European Escalation) which I don't have access to.  So I'm just waiting for someone to confirm the fix.

**Comment by FRidh** [comment]
The PR causing trouble: https://github.com/NixOS/nixpkgs/pull/20269

**Comment by FRidh** [comment]
@corngood this does not fix the issue.

**Comment by corngood** [comment]
So no difference?

If you do:

```
nix-build -A steamPackages.steam-runtime
nm -D result/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 | grep OPENSSL_1
```

Do you see the version symbols?  I see:

```
0000000000000000 A OPENSSL_1.0.0
0000000000000000 A OPENSSL_1.0.1
```

Do  you know if the game is 32-bit?

**Comment by FRidh** [comment]
My machine just broke down so it might take a bit longer before I can test again and answer your questions.

**Comment by corngood** [comment]
Removing WIP.  I haven't had any problems with it, and I don't see what harm it could cause.

**Comment by FRidh** [comment]
> So no difference?

Indeed, there was no difference.

```
nix-build -A steamPackages.steam-runtime
nm -D result/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 | grep OPENSSL_1
```
results in the same symbols you showed.

> Do you know if the game is 32-bit?

```
Wargame: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=595f2525c683f3cd4d7f2a5b3336a4ba62121f3c, stripped
```
Note that other 32-bit games work fine.

**Comment by corngood** [comment]
Maybe it's the same problem we were discussing in https://github.com/NixOS/nixpkgs/issues/20726#issuecomment-280199924 ?

Have you tried removing "no-engine" from the steam openssl?

**Comment by FRidh** [comment]
I replied at https://github.com/NixOS/nixpkgs/issues/20726#issuecomment-280916817

**Comment by corngood** [comment]
I'm going to close this since it doesn't appear to be the solution to anything.  We can discuss other options on the issue.

**Pull request closed without merging**
