### PR TITLE
[20.03] libvirtd: polkit integration, security fixes (#87576)

### PR DESCRIPTION
**Pull request by jakobrs**
###### Motivation for this change
Backporting #87576 since it hadn't been done yet.

###### Things done
I've built and tested my system configuration with this change.

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by conferno** [comment]
There suppose to be one more commit (mentioned in https://github.com/NixOS/nixpkgs/pull/87576#issuecomment-628030370).
It might be hard to locate it :(

**Comment by jakobrs** [comment]
It seems that PR was never made.

**Comment by conferno** [comment]
Then this PR might destroy existing 20.03 installations

**Comment by jakobrs** [comment]
I think the reason the PR was never made might be that Polkit is already enabled by default. But I just opened #94926, which just adds an assertion.

**Comment by conferno** [comment]
nice, so the commit from #94926 could be added here to be backported

**Comment by SuperSandro2000** [comment]
Due to the number of PRs nixpkgs gets every month we didn't review and merge this on in time before 20.03 hit EOL. If you think this PR is still relevant please rebase it on master or 20.09 and leave a comment.

**Pull request closed without merging**
