### PR TITLE
glibc: 2.34-210 -> 2.35-163

### PR DESCRIPTION
**Pull request by lovesegfault**
###### Description of changes

The patches needed a little work, but other than that it was pretty smooth. I
built hello successfully, but we'll need Hydra to do further checking.

cc. @vcunat

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
See also #165979.

**Comment by lovesegfault** [comment]
Built up to python3 without issues.

**Comment by lovesegfault** [comment]
Built up to firefox without issues: /nix/store/zln8r9iyxpann0gv9wv8l65s3nchar6m-firefox-102.0.1/

**Comment by lovesegfault** [comment]
Built up to Chromium: /nix/store/6cmscp0wlssv6mr5zql6lnv5yx4ad6h5-chromium-103.0.5060.134/

**Comment by vcunat** [comment]
In the patches of `#!/bin/bash`, why don't we make that hunk to have no context, so that we don't have to update it every year?  The risk of applying it wrongly seems pretty non-existent here.

**Review by trofi — APPROVED** [review]
LGTM! In past few months I built my desktop system with `glibc-2.35` a few times and did not notice major API breakages. Should be an easy hydra run (famous last words).

**Comment by Ma27** [comment]
Yeah, the releases from February are IIRC the less impactful ones :) 
Anyways, I'm going to close #165979 now since this is more up-to-date and seems to be working fine.

@lovesegfault just one thing: it would be cool if we could coordinate who takes care of glibc updates in the future to make sure we don't duplicate work :)

**Comment by lovesegfault** [comment]
Alright, I built all of `iso_gnome` without issues. I think it's in a good state.

**Comment by lovesegfault** [comment]
> @lovesegfault just one thing: it would be cool if we could coordinate who takes care of glibc updates in the future to make sure we don't duplicate work :)

Definitely, I completely forgot that we had a branch for 2.35 up, so when I hit a need for it yesterday, I decided to just try bumping it.

**Comment by amjoseph-nixpkgs** [comment]
This bootstraps on `powerpc64le-linux` with a bootstrap-files rebuilt after #181943.  And it looks like it will let us use IEEE-standard `long double` like Fedora 36 does: #170215.

**Comment by vcunat** [comment]
Hydra jobset, as requested through matrix: https://hydra.nixos.org/jobset/nixpkgs/pr-182538-glibc-2.35

**Comment by lovesegfault** [comment]
Okay, the eval isn't fully done, but it's far enough along that I don't think we have any major noticeable issues with this PR.

@Ma27 Do you oppose merging it and letting it cook in staging? Don't want to hit the button without your OK.

**Review by Ma27 — APPROVED** [review]
SGTM, thanks!

**Pull request merged**
