### PR TITLE
python310: 3.10.9 -> 3.10.10; python311: 3.11.1 -> 3.11.2

### PR DESCRIPTION
**Pull request by mweinelt**
###### Description of changes
https://docs.python.org/release/3.11.2/whatsnew/changelog.html
https://docs.python.org/release/3.10.10/whatsnew/changelog.htm

Based on master for testing purpose, will rebase against staging once testing is complete.l

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Welp, building it on master went nowhere, due to libuv test flakiness, that was fixed in #211896, which is currently on staging-next.

**Comment by mweinelt** [comment]
##### x86_64-linux
- [x] python310.tests
- [x] python311.tests

##### aarch64-linux
- [x] python310.tests
- [x] python311.tests

##### aarch64-darwin
- [ ] python310.tests
- [ ] python311.tests

##### x86_64-darwin
- [ ] python310.tests
- [ ] python311.tests

**Comment by mweinelt** [comment]
x86_64-darwin failing in `darwin.apple_sdk_11_0.IOKit`

```
IOKit-x86_64-darwin> source root is .
IOKit-x86_64-darwin> setting SOURCE_DATE_EPOCH to timestamp 1633495632 of file ./IOUSBFamily-IOUSBFamily-630.4.5/USBProberV2/version.plist
IOKit-x86_64-darwin> patching sources
IOKit-x86_64-darwin> configuring
IOKit-x86_64-darwin> no configure script, doing nothing
IOKit-x86_64-darwin> building
IOKit-x86_64-darwin> no Makefile or custom buildPhase, doing nothing
IOKit-x86_64-darwin> installing
IOKit-x86_64-darwin> /nix/store/0lk5sy3ik47jz6wxyf1lbbmgkhk621g6-IOKit-/Library/Frameworks/IOKit.framework/Headers /private/tmp/nix-build-IOKit-.drv-0
IOKit-x86_64-darwin> /private/tmp/nix-build-IOKit-.drv-0
IOKit-x86_64-darwin> cp: cannot stat 'IOUSBFamily-630.4.5/IOUSBFamily/Headers/IOUSBLib.h': No such file or directory
```

**Comment by alyssais** [comment]
@mweinelt this has broken eval

```
error: Function called without required argument "sha256" at /home/qyliss/src/nixpkgs/pkgs/development/interpreters/python/cpython/2.7/default.nix:27
```

**Comment by alyssais** [comment]
https://github.com/NixOS/nixpkgs/pull/216189

**Pull request merged**
