### PR TITLE
[wip] Various GNOME 3.26 libraries: update

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
These libraries were updated as a part of the [GNOME 3.26 pull request](https://github.com/NixOS/nixpkgs/pull/29392) but they can actually be used independently. Since pull requests updating many of these packages started to pop up, I decided to submit those changes to prevent duplication of effort.

##### Updated libraries

* appstream-glib
* clutter_gtk
* colord
* fwup
* glib_networking
* glibmm
* gnome3.dconf
* gnome3.folks
* gnome3.gjs
* gnome3.grilo
* gnome3.grilo-plugins
* gnome3.libpeas
* gnome3.libgdata
* gnome3.libgepub
* gnome3.libgxps
* gnome3.libzapojit
* gnome3.mutter
* gnome3.nautilus-sendto
* gnome3.totem-pl-parser
* gnome3.vte
* gobjectIntrospection
* granite
* gstreamer
* gusb
* gvfs
* json_glib
* libchamplain
* libevdev
* libgtop
* libgudev
* libical
* libinput
* librsvg
* libwacom
* libxkbcommon
* networkmanagerapplet
* ostree
* packagekit
* spice_gtk
* spice_protocol
* spidermonkey_52
* telepathy_glib
* xf86_input_wacom
* zeitgeist

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
@jtojnar what is the status? Did you test these changes? Do you think we should run a Hydra job?

**Comment by jtojnar** [comment]
I only build tested them with GNOME 3.26. I will need to take a second pass. Hydra job might help.

**Comment by jtojnar** [comment]
@FRidh Finished review, could you please arrange the Hydra job?

**Comment by dezgeg** [comment]
I don't have Hydra creation permissions, but in the meantime here's some failures I noticed when build-testing this:
`colord`:
````
Compiler for C supports argument -Wl,-z,now: YES
Found pkg-config: /nix/store/pki9r32nbdvdrmxaxrkb7j8lbq3jfihi-pkg-config-0.29.2/bin/pkg-config (0.29.2)
Native dependency gio-2.0 found: YES 2.54.1
Native dependency glib-2.0 found: YES 2.54.1
Native dependency gmodule-2.0 found: YES 2.54.1
Native dependency gio-unix-2.0 found: YES 2.54.1
Native dependency lcms2 found: YES 2.8
Native dependency sqlite3 found: YES 3.21.0
Native dependency gusb found: YES 0.2.11
Native dependency gudev-1.0 found: YES 232
Library m found: YES
Native dependency udev found: YES 234
Native dependency libudev found: YES 234
Native dependency systemd found: YES 234
Native dependency libsystemd found: YES 234
Has header "pwd.h": YES
Has header "syslog.h": YES
Has header "unistd.h": YES
Checking for function "getuid": YES
Native dependency bash-completion found: YES 2.7
Native dependency sane-backends found: YES 1.0.27
Native dependency dbus-1 found: YES 1.10.24
Program spotread found: YES (/nix/store/fwzbk1l1lkil2ffxig946xhyn3m6aay3-argyllcms-1.8.3/bin/spotread)
Program vapigen found: NO

Meson encountered an error in file meson.build, line 170, column 2:
Program "vapigen" not found or not executable

A full log can be found at /tmp/nix-build-colord-1.4.1.drv-0/colord-1.4.1/build/meson-logs/meson-log.txt
builder for ‘/nix/store/frk7p89khfx3zqjjb4iybz0idj9hsqsy-colord-1.4.1.drv’ failed with exit code 1
````
Needs `vala` or `-Denable-vala=false`?

`mutter`:
````
  CC       backends/native/meta-idle-monitor-native.lo
In file included from /nix/store/d9s2m4fs3m8ifngnkzmpik6li1yqy0z9-glib-2.54.1/lib/glib-2.0/include/glibconfig.h:9:0,
                 from /nix/store/cf7hbajqjr93kc50mpi32cqjbcq53x6k-glib-2.54.1-dev/include/glib-2.0/glib/gtypes.h:32,
                 from /nix/store/cf7hbajqjr93kc50mpi32cqjbcq53x6k-glib-2.54.1-dev/include/glib-2.0/glib/galloca.h:32,
                 from /nix/store/cf7hbajqjr93kc50mpi32cqjbcq53x6k-glib-2.54.1-dev/include/glib-2.0/glib.h:30,
                 from /nix/store/cf7hbajqjr93kc50mpi32cqjbcq53x6k-glib-2.54.1-dev/include/glib-2.0/gobject/gbinding.h:28,
                 from /nix/store/cf7hbajqjr93kc50mpi32cqjbcq53x6k-glib-2.54.1-dev/include/glib-2.0/glib-object.h:23,
                 from backends/native/meta-launcher.h:23,
                 from backends/native/meta-launcher.c:22:
/nix/store/cf7hbajqjr93kc50mpi32cqjbcq53x6k-glib-2.54.1-dev/include/glib-2.0/glib/gmacros.h:430:43: error: redefinition of 'glib_autoptr_cleanup_GUdevDevice'
 #define _GLIB_AUTOPTR_FUNC_NAME(TypeName) glib_autoptr_cleanup_##TypeName
                                           ^
/nix/store/cf7hbajqjr93kc50mpi32cqjbcq53x6k-glib-2.54.1-dev/include/glib-2.0/glib/gmacros.h:444:22: note: in expansion of macro '_GLIB_AUTOPTR_FUNC_NAME'
   static inline void _GLIB_AUTOPTR_FUNC_NAME(TypeName) (TypeName **_ptr) { if (*_ptr) (func) (*_ptr); }         \
                      ^~~~~~~~~~~~~~~~~~~~~~~
backends/native/meta-launcher.c:52:1: note: in expansion of macro 'G_DEFINE_AUTOPTR_CLEANUP_FUNC'
 G_DEFINE_AUTOPTR_CLEANUP_FUNC(GUdevDevice, g_object_unref)
 ^
/nix/store/cf7hbajqjr93kc50mpi32cqjbcq53x6k-glib-2.54.1-dev/include/glib-2.0/glib/gmacros.h:430:43: note: previous definition of 'glib_autoptr_cleanup_GUdevDevice' was here
 #define _GLIB_AUTOPTR_FUNC_NAME(TypeName) glib_autoptr_cleanup_##TypeName
                                           ^
/nix/store/cf7hbajqjr93kc50mpi32cqjbcq53x6k-glib-2.54.1-dev/include/glib-2.0/glib/gmacros.h:444:22: note: in expansion of macro '_GLIB_AUTOPTR_FUNC_NAME'
   static inline void _GLIB_AUTOPTR_FUNC_NAME(TypeName) (TypeName **_ptr) { if (*_ptr) (func) (*_ptr); }         \
                      ^~~~~~~~~~~~~~~~~~~~~~~
/nix/store/hg3qjccvdqzxpwc8xzs3savnzhvkp430-libgudev-232/include/gudev-1.0/gudev/gudevdevice.h:39:1: note: in expansion of macro 'G_DEFINE_AUTOPTR_CLEANUP_FUNC'
 G_DEFINE_AUTOPTR_CLEANUP_FUNC (GUdevDevice, g_object_unref)
 ^
/nix/store/cf7hbajqjr93kc50mpi32cqjbcq53x6k-glib-2.54.1-dev/include/glib-2.0/glib/gmacros.h:430:43: error: redefinition of 'glib_autoptr_cleanup_GUdevClient'
 #define _GLIB_AUTOPTR_FUNC_NAME(TypeName) glib_autoptr_cleanup_##TypeName
                                           ^
/nix/store/cf7hbajqjr93kc50mpi32cqjbcq53x6k-glib-2.54.1-dev/include/glib-2.0/glib/gmacros.h:444:22: note: in expansion of macro '_GLIB_AUTOPTR_FUNC_NAME'
   static inline void _GLIB_AUTOPTR_FUNC_NAME(TypeName) (TypeName **_ptr) { if (*_ptr) (func) (*_ptr); }         \
                      ^~~~~~~~~~~~~~~~~~~~~~~
backends/native/meta-launcher.c:53:1: note: in expansion of macro 'G_DEFINE_AUTOPTR_CLEANUP_FUNC'
 G_DEFINE_AUTOPTR_CLEANUP_FUNC(GUdevClient, g_object_unref)
 ^
/nix/store/cf7hbajqjr93kc50mpi32cqjbcq53x6k-glib-2.54.1-dev/include/glib-2.0/glib/gmacros.h:430:43: note: previous definition of 'glib_autoptr_cleanup_GUdevClient' was here
 #define _GLIB_AUTOPTR_FUNC_NAME(TypeName) glib_autoptr_cleanup_##TypeName
                                           ^
/nix/store/cf7hbajqjr93kc50mpi32cqjbcq53x6k-glib-2.54.1-dev/include/glib-2.0/glib/gmacros.h:444:22: note: in expansion of macro '_GLIB_AUTOPTR_FUNC_NAME'
   static inline void _GLIB_AUTOPTR_FUNC_NAME(TypeName) (TypeName **_ptr) { if (*_ptr) (func) (*_ptr); }         \
                      ^~~~~~~~~~~~~~~~~~~~~~~
/nix/store/hg3qjccvdqzxpwc8xzs3savnzhvkp430-libgudev-232/include/gudev-1.0/gudev/gudevclient.h:39:1: note: in expansion of macro 'G_DEFINE_AUTOPTR_CLEANUP_FUNC'
 G_DEFINE_AUTOPTR_CLEANUP_FUNC (GUdevClient, g_object_unref)
 ^
/nix/store/cf7hbajqjr93kc50mpi32cqjbcq53x6k-glib-2.54.1-dev/include/glib-2.0/glib/gmacros.h:430:43: error: redefinition of 'glib_autoptr_cleanup_GUdevEnumerator'
 #define _GLIB_AUTOPTR_FUNC_NAME(TypeName) glib_autoptr_cleanup_##TypeName
                                           ^
/nix/store/cf7hbajqjr93kc50mpi32cqjbcq53x6k-glib-2.54.1-dev/include/glib-2.0/glib/gmacros.h:444:22: note: in expansion of macro '_GLIB_AUTOPTR_FUNC_NAME'
   static inline void _GLIB_AUTOPTR_FUNC_NAME(TypeName) (TypeName **_ptr) { if (*_ptr) (func) (*_ptr); }         \
                      ^~~~~~~~~~~~~~~~~~~~~~~
backends/native/meta-launcher.c:54:1: note: in expansion of macro 'G_DEFINE_AUTOPTR_CLEANUP_FUNC'
 G_DEFINE_AUTOPTR_CLEANUP_FUNC(GUdevEnumerator, g_object_unref)
 ^
/nix/store/cf7hbajqjr93kc50mpi32cqjbcq53x6k-glib-2.54.1-dev/include/glib-2.0/glib/gmacros.h:430:43: note: previous definition of 'glib_autoptr_cleanup_GUdevEnumerator' was here
 #define _GLIB_AUTOPTR_FUNC_NAME(TypeName) glib_autoptr_cleanup_##TypeName
                                           ^
/nix/store/cf7hbajqjr93kc50mpi32cqjbcq53x6k-glib-2.54.1-dev/include/glib-2.0/glib/gmacros.h:444:22: note: in expansion of macro '_GLIB_AUTOPTR_FUNC_NAME'
   static inline void _GLIB_AUTOPTR_FUNC_NAME(TypeName) (TypeName **_ptr) { if (*_ptr) (func) (*_ptr); }         \
                      ^~~~~~~~~~~~~~~~~~~~~~~
/nix/store/hg3qjccvdqzxpwc8xzs3savnzhvkp430-libgudev-232/include/gudev-1.0/gudev/gudevenumerator.h:39:1: note: in expansion of macro 'G_DEFINE_AUTOPTR_CLEANUP_FUNC'
 G_DEFINE_AUTOPTR_CLEANUP_FUNC (GUdevEnumerator, g_object_unref)
 ^
  CC       backends/native/meta-cursor-renderer-native.lo
  CC       backends/native/meta-clutter-backend-native.lo
make[4]: *** [Makefile:2162: backends/native/meta-launcher.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/tmp/nix-build-mutter-3.24.4.drv-0/mutter-3.24.4/src'
make[3]: *** [Makefile:2334: all-recursive] Error 1
make[3]: Leaving directory '/tmp/nix-build-mutter-3.24.4.drv-0/mutter-3.24.4/src'
make[2]: *** [Makefile:1336: all] Error 2
make[2]: Leaving directory '/tmp/nix-build-mutter-3.24.4.drv-0/mutter-3.24.4/src'
make[1]: *** [Makefile:484: all-recursive] Error 1
make[1]: Leaving directory '/tmp/nix-build-mutter-3.24.4.drv-0/mutter-3.24.4'
make: *** [Makefile:414: all] Error 2
builder for ‘/nix/store/fxb96yvr92zcn3bvvfm27cd9jvayzl5q-mutter-3.24.4.drv’ failed with exit code 2
````

`totem-pl-parser`:
````
unpacking sources
unpacking source archive /nix/store/594v76fxd4waiwz25xys9kwdhh2lyws5-totem-pl-parser-3.10.2.tar.xz
source root is totem-pl-parser-3.10.2
setting SOURCE_DATE_EPOCH to timestamp 1395667871 of file totem-pl-parser-3.10.2/docs/reference/totem-pl-parser.types
patching sources
configuring
meson flags: --buildtype=release --prefix=/nix/store/krbfsi9g7ilhqpz6kjq0p0grw8b98qi6-totem-pl-parser-3.10.2  
Warning: You are using 'ANSI_X3.4-1968' which is not a Unicode-compatible locale.
You might see errors if you use UTF-8 strings as filenames, as strings, or as file contents.
Please switch to a UTF-8 locale for your platform.
Error during basic setup:

Neither directory contains a build file meson.build.
builder for ‘/nix/store/3ldfqhhdzql0hcxdgv404i6ckbdrcgbi-totem-pl-parser-3.10.2.drv’ failed with exit code 1
````

**Comment by jtojnar** [comment]
@orivej Looks like a cherry-picking failure. Should be fixed now.

**Comment by orivej** [comment]
> @orivej Looks like a cherry-picking failure. Should be fixed now.

You meant @dezgeg.

BTW updating libgit2 is more involved than that, I'm doing it in #31119

**Comment by jtojnar** [comment]
@orivej Sorry, I misremembered.

Anyway, thanks for letting me know, I dropped the git related commits.

**Comment by dezgeg** [comment]
Next up is `gnome-documents` which just needs an updated version of `libgepub`, I think:
````
checking for version 0.4 of Gepub... no
configure: error: You do not have API version 0.4 of the GObject
Introspection bindings for the Gepub library.
Build a version from source, or find out what package to
install with one of these commands, depending on your system:
  apt-file search Gepub-0.4.typelib
  dnf provides \*/Gepub-0.4.typelib

builder for ‘/nix/store/220ld3qlzd9jsjbris0g5v3aaps8ps27-gnome-documents-3.24.3.drv’ failed with exit code 1
````
(That's the last failing dependency of `tests.gnome3`, AFAICT)

**Comment by jtojnar** [comment]
@dezgeg Hmm. I diffed the file trees again and the `libgepub` is the only one that stands out. Since it is not possible to update `gnome-documents` without also updating the GNOME platform and it is the only derivation depending on `Gepub`, I left the commit for #29392.

**Comment by dezgeg** [comment]
Next up seems to be that `libinput` needs the equivalent of the old `udev-absolute-path.patch` implemented in meson:
````
Checking that all programs called by relative paths in udev rules exist in /nix/store/zcrp3321v2kfk8p4hlmlwr3h91baj9wy-systemd-234/lib/udev... FAIL
libinput-model-quirks is called in udev rules but not installed by udev
builder for ‘/nix/store/k3l4f1apjdpyn9ccira61nmminfrg4dm-udev-rules.drv’ failed with exit code 1
````

i.e. previously it did:
````
result/lib/udev/rules.d/90-libinput-model-quirks.rules:  IMPORT{program}="/nix/store/qlswcixrd45fqzilgjyb3vh4qxkmij26-libinput-1.7.3/lib/udev/libinput-model-quirks %S%p"
````

but now:
````
result/lib/udev/rules.d/90-libinput-model-quirks.rules:  IMPORT{program}="libinput-model-quirks %S%p"
````

**Comment by jtojnar** [comment]
@dezgeg Fixed, thanks.

**Comment by vcunat** [comment]
Merged master and re-purposed the old gnome jobset on Hydra: https://hydra.nixos.org/eval/1407799?compare=1407776

**Comment by dezgeg** [comment]
Now things build but unfortunately gnome-shell crashes in the test: https://gist.github.com/dezgeg/4e78fb79c0e039ece97f8b3ca7d04e91

````
machine# [   52.259337] .gnome-shell-wr[1091]: Some code accessed the property 'LIBMUTTER_API_VERSION' on the module 'config'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
machine# [   56.075550] .gnome-shell-wr[1091]: Some code accessed the property 'PopupMenu' on the module 'popupMenu'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
machine# [   56.100632] .gnome-shell-wr[1091]: Some code accessed the property 'ModalDialog' on the module 'modalDialog'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
machine# [   56.113590] .gnome-shell-wr[1091]: Some code accessed the property 'SwitcherPopup' on the module 'switcherPopup'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
machine# [   56.127609] .gnome-shell-wr[1091]: Some code accessed the property 'SwitcherList' on the module 'switcherPopup'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
machine# [   58.914991] .gnome-shell-wr[1091]: Some code accessed the property 'PopupBaseMenuItem' on the module 'popupMenu'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
machine# [   58.965660] .gnome-shell-wr[1091]: Some code accessed the property 'Button' on the module 'panelMenu'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
machine# [   59.020636] .gnome-shell-wr[1091]: JS ERROR: SyntaxError: missing ] after element list @ resource:///org/gnome/shell/ui/messageTray.js:1045
machine# [   59.050886] .gnome-shell-wr[1091]: Execution of main.js threw exception: JS_EvaluateScript() failed
machine# [   59.232939] gnome-session[1009]: gnome-session-binary[1009]: WARNING: App 'org.gnome.Shell.desktop' exited with code 1
machine# [   59.237680] gnome-session-binary[1009]: WARNING: App 'org.gnome.Shell.desktop' exited with code 1
machine# [   66.582111] .gnome-shell-wr[1153]: Some code accessed the property 'LIBMUTTER_API_VERSION' on the module 'config'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
machine# [   71.575259] .gnome-shell-wr[1153]: Some code accessed the property 'PopupMenu' on the module 'popupMenu'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
machine# [   71.758305] .gnome-shell-wr[1153]: Some code accessed the property 'ModalDialog' on the module 'modalDialog'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
machine# [   71.835319] .gnome-shell-wr[1153]: Some code accessed the property 'SwitcherPopup' on the module 'switcherPopup'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
machine# [   71.841823] .gnome-shell-wr[1153]: Some code accessed the property 'SwitcherList' on the module 'switcherPopup'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
machine# [   73.988601] .gnome-shell-wr[1153]: Some code accessed the property 'PopupBaseMenuItem' on the module 'popupMenu'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
machine# [   74.093240] .gnome-shell-wr[1153]: Some code accessed the property 'Button' on the module 'panelMenu'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
machine# [   74.177824] .gnome-shell-wr[1153]: JS ERROR: SyntaxError: missing ] after element list @ resource:///org/gnome/shell/ui/messageTray.js:1045
machine# [   74.257902] .gnome-shell-wr[1153]: Execution of main.js threw exception: JS_EvaluateScript() failed
machine# [   74.324157] gnome-session[1009]: gnome-session-binary[1009]: WARNING: App 'org.gnome.Shell.desktop' exited with code 1
machine# [   74.342512] gnome-session[1009]: gnome-session-binary[1009]: WARNING: App 'org.gnome.Shell.desktop' respawning too quickly
machine# [   74.351724] gnome-session-binary[1009]: Unrecoverable failure in required component org.gnome.Shell.desktop
machine# [   74.382590] gnome-session-binary[1009]: WARNING: App 'org.gnome.Shell.desktop' exited with code 1
machine# [   74.409590] gnome-session-binary[1009]: WARNING: App 'org.gnome.Shell.desktop' respawning too quickly

````

**Comment by jtojnar** [comment]
@dezgeg Looks like an issue with gjs update.

**Comment by dezgeg** [comment]
The gnome3 test passed for me now.

**Comment by dezgeg** [comment]
json-glib seems to fail on i686 (which is a dependency of `wine`): https://hydra.nixos.org/build/63528827. The upstream issue https://gitlab.gnome.org/GNOME/json-glib/issues/27 looks like a test bug so I would just set `doCheck = !stdenv.isi686;` with a note to re-enable on upgrade.

**Comment by jtojnar** [comment]
@dezgeg Applied a patch for that.

**Comment by vcunat** [comment]
If some of you have a gnome3 setup, it would be good to verify that this PR doesn't cause some large breakage (like the DE not starting).

**Comment by jtojnar** [comment]
I will but am still rebuilding webkitgtk

**Comment by vcunat** [comment]
@jtojnar: at current PR's commit I get it from the binary cache ;-)

**Comment by jtojnar** [comment]
@vcunat No idea what was up with it. I rebuilt it and GNOME and the apps work just fine with the libraries.

**Comment by vcunat** [comment]
I probably just tried at the right moment.  There's also a short-time negative local cache for the binary cache lookups.

**Comment by globin** [comment]
So this should be ready to be merged now?

**Comment by vcunat** [comment]
Yes, I've been just waiting for the remaining builds to finish on Hydra.

**Comment by jtojnar** [comment]
Looks like `fwupd` build is broken after `libgudev` update. #30252 attempts to fix it.

**Comment by dezgeg** [comment]
It was actually broken previously since September (https://hydra.nixos.org/build/59954108) but fixes are still welcome :)

**Comment by orivej** [comment]
This broke `fwup`: https://hydra.nixos.org/job/nixpkgs/trunk/fwup.x86_64-linux

**Comment by jtojnar** [comment]
@orivej This does not seem to be the problem. The same tests fail even if I downgrade `fwup`. And it does not look like it depends on any other package changed in this PR.

**Comment by orivej** [comment]
Thank you! Fixed in 3954032ac5f38a6b3c693874497cb55e6c0aadb7.

**Pull request merged**
