### PR TITLE
python311Packages.pysequoia: 0.1.14 -> 0.1.20

### PR DESCRIPTION
**Pull request by puzzlewolf**
## Description of changes

The source has moved away from gitlab but keeps releasing on pypi, so use that source for the updated version. No packaging changes otherwise.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

 Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python310Packages.pysequoia</li>
    <li>python310Packages.pysequoia.dist</li>
    <li>python311Packages.pysequoia</li>
    <li>python311Packages.pysequoia.dist</li>
  </ul>
</details>

### CODE REVIEW

**Comment by natsukium** [comment]
The source seems to have moved to codeberg.
https://codeberg.org/wiktor/pysequoia

**Comment by natsukium** [comment]
It seems that `libiconv` is required for darwin's buildInputs.
```
       >   = note: ld: library not found for -liconv
       >           clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
       >           
       >
       > error: could not compile `nettle-sys` (build script) due to previous error
       > 💥 maturin failed
       >   Caused by: Failed to build a native library through cargo
       >   Caused by: Cargo build finished with "exit status: 101": `CARGO_ENCODED_RUSTFLAGS="-C\u{1f}target-feature=-crt-static" PYO3_ENVIRONMENT_SIGNATURE="cpython-3.11-64bit" PYO3_PYTHON="/nix/store/yqs2zxkxn61xzimdaz1pbgawk2lnm0d8-python3-3.11.4/bin/python3" PYTHON_SYS_EXECUTABLE="/nix/store/yqs2zxkxn61xzimdaz1pbgawk2lnm0d8-python3-3.11.4/bin/python3" "cargo" "rustc" "--jobs" "1" "--target" "x86_64-apple-darwin" "--message-format" "json-render-diagnostics" "--frozen" "--manifest-path" "/private/tmp/nix-build-python3.11-pysequoia-0.1.20.drv-0/pysequoia-0.1.20/Cargo.toml" "--release" "--lib" "--" "-C" "link-arg=-undefined" "-C" "link-arg=dynamic_lookup" "-C" "link-args=-Wl,-install_name,@rpath/pysequoia.cpython-311-darwin.so" "-C" "link-arg=-s"`
       For full logs, run 'nix log /nix/store/158n4c1pw77hs5f5k59lxfsnaz6lhx3c-python3.11-pysequoia-0.1.20.drv'.
```

**Comment by doronbehar** [comment]
> It seems that `libiconv` is required for darwin's buildInputs.

Pushed that fix. Let's wait for CI.

**Comment by doronbehar** [comment]
Couldn't find a way to fix the darwin build, so I marked it as broken on darwin.

**Pull request merged**
