### PR TITLE
containerd: 1.5.2 -> 1.5.3

### PR DESCRIPTION
**Pull request by amaxine**
###### Motivation for this change
https://github.com/containerd/containerd/releases/tag/v1.5.3

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by maxeaubrey** [comment]
Result of `nixpkgs-review pr 130311` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>charliecloud</li>
    <li>containerd</li>
    <li>docker</li>
    <li>docker-gc</li>
    <li>fn-cli</li>
    <li>grype</li>
    <li>ignite</li>
    <li>nvidia-docker</li>
    <li>out-of-tree</li>
    <li>pipework</li>
    <li>python38Packages.jupyter-repo2docker</li>
    <li>python39Packages.jupyter-repo2docker</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 130311` at 78932034 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/b023123d024331d8a365bbcfa09025ce">ignite</a></li>
  </ul>
</details>
<details>
  <summary>10 packages built successfully:</summary>
  <ul>
    <li>charliecloud</li>
    <li>containerd</li>
    <li>docker (docker-edge ,docker_20_10)</li>
    <li>docker-gc</li>
    <li>fn-cli</li>
    <li>grype</li>
    <li>out-of-tree</li>
    <li>pipework</li>
    <li>python38Packages.jupyter-repo2docker</li>
    <li>python39Packages.jupyter-repo2docker</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by maxeaubrey** [comment]
`firecracker` is broken right now, the hash wasn't updated with the last bump. Fixed in #130320, but not relevant here.

**Comment by maxeaubrey** [comment]
Apparently superseded by by #130681 :/

**Pull request closed without merging**
