### PR TITLE
nettle: 3.4.1 -> 3.5.1

### PR DESCRIPTION
**Pull request by aanderse**
###### Motivation for this change
~~https://github.com/NixOS/nixpkgs/issues/68361~~ :thinking: 

So I got confused while fixing `viking` and somehow ended up thinking `nettle` was broken too (hint: it is not). See https://github.com/NixOS/nixpkgs/pull/68595) for *actual* ZHF PR :man_shrugging: 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by globin** [comment]
Please switch this to staging

**Comment by aanderse** [comment]
Thanks @globin!

**Comment by jonringer** [comment]
@GrahamcOfBorg eval

**Comment by jonringer** [comment]
... why does this cause so many rebuilds...

**Comment by vcunat** [comment]
I think most will be through `gnutls`, as that's one of the more popular crypto-libraries.

**Review by vcunat — CHANGES_REQUESTED** [review]
`unbound` build is broken by this, which results into a mass breakage (through a DANE library in gnutls).  We'll need to resolve that before merging.

**Review by vcunat — APPROVED** [review]
NEWS seems nice (speedups!), and I don't expect any other significant breakages.

**Comment by vcunat** [comment]
Lemme cross-link the tickets: https://github.com/NLnetLabs/unbound/pull/90.

**Pull request merged**
