### PR TITLE
Merge ungoogled-chromium back into the chromium expressions

### LINKED ISSUE #102965: Merge ungoogled-chromium back into the chromium expressions?
**Note: This issue is still WIP, please add feedback, your opinion, advantages/disadvantages, etc. Thanks!**

## Issue description

In short: To ensure timely security updates (for a web browser, which is a very security critical component) and to avoid an unnecessary duplication of the Nix expressions for building `ungoogled-chromium` we should integrate it into `chromium` by using conditionals for the `ungoogled-chromium` specific parts. IIRC this was also the initial approach in #76082.

Advantages:
- More timely security updates (since we update Chromium much more timely)
- Less work for the `ungoogled-chromium` maintainer? (I assume since this requires regularly copying the Chromium expressions)
- Security updates will be backported to the stable NixOS release (though we'll probably do so without any additional testing for `ungoogled-chromium`; normally it should be fine if `chromium` is fine and if not users could also use it from the unstable channel).
- Reviewing `ungoogled-chromium` PRs would become easier (currently the diff will also contain changes from Chromium).

Drawbacks:
- Requires twice the amount of build time to test changes. Maybe @danielfullmer could help testing Chromium PRs (apart from the regular updates, which @squalus can likely test, there should be few PRs that change/improve our build expressions) for `ungoogled-chromium` by building it and running a test (we could reuse `nixosTests.chromium`)?
- ~~Could delay Chromium updates in case the `ungoogled-chromium` build fails.~~ I propose adding a new entry for `ungoogled-chromium` to `upstream-info.json` so that we can update them separately if required (e.g. if the `ungoogled-chromium` build fails after major updates or if the ungoogled patches aren't available yet).
- ~~The Nix expressions will become more complex.~~ I don't think that it'll make a huge difference and at least we avoid the code duplication.

cc:
- ungoogled-chromium maintainer @squalus 
- Chromium maintainer @primeos @thefloweringash @bendlas

### PR DESCRIPTION
**Pull request by primeos**
###### Motivation for this change

Resolve #102965.
cc @squalus

My additional changes for this merge:
https://github.com/primeos/nixpkgs/compare/ungoogled-chromium-merge-no-changes..primeos:ungoogled-chromium-merge
~~`git diff primeos/ungoogled-chromium-merge-no-changes primeos/ungoogled-chromium-merge` (unfortunately it seems like the GitHub UI can only diff `primeos/ungoogled-chromium-merge-no-changes...primeos/ungoogled-chromium-merge`)~~

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by primeos** [comment]
Btw this is the `nix-diff` output (explains the rebuild that the second commit causes, s. commit message):
```
$ nix-diff /nix/store/nl4b0hwiaaahpfr910qhamr6r70j70cv-ungoogled-chromium-87.0.4280.88.drv /nix/store/z2br0hkbvrgbqdmwyzr5a5ignn5rhs43-ungoogled-chromium-87.0.4280.88.drv
- /nix/store/nl4b0hwiaaahpfr910qhamr6r70j70cv-ungoogled-chromium-87.0.4280.88.drv:{out}
+ /nix/store/z2br0hkbvrgbqdmwyzr5a5ignn5rhs43-ungoogled-chromium-87.0.4280.88.drv:{out}
• The input named `chromium-unwrapped-87.0.4280.88` differs
  - /nix/store/iddxb9yrhc6anvz3c3blbrcfvr8hmkn7-chromium-unwrapped-87.0.4280.88.drv:{out,sandbox}
  + /nix/store/jx2dbhdgwkhn10q77wlyj4bfhjjh01fl-chromium-unwrapped-87.0.4280.88.drv:{out,sandbox}
  • The environments do not match:
      channel=stabungoogled-chromium
• Skipping environment comparison
```

The color is missing but it's basically `channel=stable` vs. `channel=ungoogled-chromium` in `/nix/store/iddxb9yrhc6anvz3c3blbrcfvr8hmkn7-chromium-unwrapped-87.0.4280.88.drv`. AFAIK `channel` shouldn't even be set as environment variable but that seems outside the scope of this PR. Anyway, the two outputs/realizations of the derivation should remain unchanged.

**Comment by primeos** [comment]
Let's give it a try :)

**Comment by squalus** [comment]
Looks great! Thanks for doing this.

**Comment by ajs124** [comment]
I think this broke [unstable-small](https://hydra.nixos.org/job/nixos/unstable-small/tested), see https://hydra.nixos.org/build/133143744 or rather https://nix-cache.s3.amazonaws.com/log/74kfh3pc10y5iin2r6crplabd0ky6vq4-nixpkgs-tarball-21.03pre258838.85298db412b.drv

**Comment by primeos** [comment]
@ajs124 thanks for notifying me! be94a4cf235ca11e05a549a1128bc2ae19ab4293 should hopefully fix it (not completely sure if there was a second problem - I was actually aware of this one but didn't expect that Hydra would try to evaluate `ungoogled-chromium.chromeSrc` but it seems like it will eagerly evaluate all attributes, even if they're not required/used anywhere).

**Comment by primeos** [comment]
Yay, the fix worked: https://hydra.nixos.org/build/133146064

@squalus and I just pushed 94bee1090426c1aaee8e20cc5bbb1e30da86c792 so you should now be able to update `ungoogled-chromium` by simply running `pkgs/applications/networking/browsers/chromium/update.py` ;)

**Comment by r3v2d0g** [comment]
Hey @primeos! It seems your last commit is now making my configuration throw an error at me (`Google Chrome is not supported for the ungoogled-chromium channel.`) when trying to install the `ungoogled-chromium` package :/.

**Comment by primeos** [comment]
@r3v2d0g oh, that"s a bit unexpected. I didn't think anyone would like to combine ungoogled-chromium with Google's proprietary DRM technology but I guess why not. I'll change the update script then to include the Google Chrome sources for the ungoogled-chromium channel as well.

**Comment by primeos** [comment]
@r3v2d0g could you please test if 86ff1e45cece6f001cf0971559cdec6d25bb9db7 works as expected (I only verified that it builds)?

**Comment by r3v2d0g** [comment]
@primeos Yes, this is now works as expected! Thank you for taking the time to fix this :)

**Pull request merged**
