### PR TITLE
nixos/bluetooth: don't install obex tools by default

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Motivation for this change
Currently setting `hardware.bluetooth.enable = true` install the OpenOBEX tools along with bluez.
Since sharing files over bluetooth seems pretty uncommon and the packages are more than 200MB I propose we don't install them by default.

---

### CODE REVIEW

**Comment by worldofpeace** [comment]
Only problem I see here could be like applications relying on `obexftp` being in the global environment and removing them would break them. (IIRC some plasma related utilities).

**Comment by worldofpeace** [comment]
BlueZ still has `obexd` so this is more accurately removing the `OpenOBEX` related things.

**Comment by jtojnar** [comment]
If we accept this, it needs to be mentioned in release notes.

**Comment by rnhmjoj** [comment]
> If we accept this, it needs to be mentioned in release notes.

Done.

**Comment by rnhmjoj** [comment]
worldofpeace: do you know more about the plasma situation? If needed this could be installed behind a guard like `plasma5.enable`.

**Comment by worldofpeace** [comment]
@rnhmjoj I'm not sure.

Perhaps some maintainers/contributors of plasma5 will know

@bkchr @ttuegel

**Comment by rnhmjoj** [comment]
I rebased and moved the note to 20.03. Any update?

**Comment by ttuegel** [comment]
> If needed this could be installed behind a guard like `plasma5.enable`.

As far as I know this is still required by Plasma. Could you please put it behind a guard?

**Comment by rnhmjoj** [comment]
Thank you @ttuegel. Is this ok?

**Review by worldofpeace — APPROVED** [review]

**Review by ttuegel — COMMENTED** [review]
Perfect. Thanks! :smiley:

**Comment by rnhmjoj** [comment]
> Since sharing files over bluetooth seems pretty uncommon and the packages are more than 200MB I propose we don't install them by default.

@bjornfor are you aware of other desktop environments that need these tools?

**Comment by bjornfor** [comment]
No, I'm not aware of other DEs that need this. I was just worried there were, seeing that commit.

> Since sharing files over bluetooth seems pretty uncommon

Personally, sharing files over bluetooth is something I _would like to do_, if it worked reliably. But I've never good enough experience with bluetooth on linux to rely on it :-/

**Comment by worldofpeace** [comment]
I checked and it appears it's likely dolphin needed this for that functionality. So it probably won't be that a desktop environment needs, more that a program that uses this functionality will need the packages installed.

**Pull request merged**
