### PR TITLE
clj-kondo: 2020.03.20 -> 2020.04.05

### PR DESCRIPTION
**Pull request by bennyandresen**
###### Motivation for this change
Version bump

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

@worldofpeace @AndersonTorres

### CODE REVIEW

**Comment by FRidh** [comment]
@grahamcofborg build clj-kondo

**Comment by jlesquembre** [comment]
It looks good to me. Unfortunately, graalvm8 is broken on master:
https://hydra.nixos.org/job/nixpkgs/trunk/graalvm8.x86_64-linux
I was able to build it with `graalvm11-ee`, I think it should work with `graalvm8` once it is fixed.

**Review by jlesquembre — APPROVED** [review]

**Comment by bandresen** [comment]
graalvm8 builds for me, but it consumes 24GB and takes 70 Minutes on my 8-thread Intel. Maybe that's a bit outside the hydra normality.

**Comment by bandresen** [comment]
for the next reviewer:

according to @hlolli in #83080 the package can't be built because it gets OOM-killed in grahamofborg's build.
I measured the peak memory resource consumption at 25GB when I built it myself.

It builds fine on my system and could be included, as the situation is the same for 0.0.78 or 0.0.71 before it.

**Pull request merged**
