### PR TITLE
pythonPackages.nibabel: unbreak tests/package

### PR DESCRIPTION
**Pull request by bcdarwin**
###### Motivation for this change

Build is broken due to an unimportant test failing and a few tests erroring due to missing `pytest`.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
nilearn is still broken for unrelated reasons
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
@GrahamcOfBorg build pythonPackages.nibabel
@GrahamcOfBorg build pythonPackages.nibabel

**Comment by jonringer** [comment]
@GrahamcOfBorg build python3Packages.nibabel
@GrahamcOfBorg build python38Packages.nibabel

**Comment by bcdarwin** [comment]
A couple tests fail on aarch64.  I've PR'ed one of them but can't reproduce the other on x64, so I've disabled them in the expression.

@ashgillman @jonringer

**Comment by jonringer** [comment]
@GrahamcOfBorg build pythonPackages.nibabel
@GrahamcOfBorg build python3Packages.nibabel
@GrahamcOfBorg build python38Packages.nibabel

**Comment by jonringer** [comment]
my main concern is: Under normal usage of this library, is it still actually broken for arm?

just because we disable a test, doesn't mean that everyone is okay; those tests might be revealing that the package makes some assumptions which are broken on arm.

at the very least, please comment why those tests are disabled :)

**Comment by bcdarwin** [comment]
Sure, updated to disable non-x64 builds for now.

**Comment by bcdarwin** [comment]
Added another commit to remove some spurious Python 2-related stuff from an earlier version.

**Pull request closed without merging**
