### PR TITLE
mailcatcher: fix libxml2.12 breaking change

### PR DESCRIPTION
**Pull request by szucsitg**
## Description of changes

Changes nokogiri package's version from 1.15.3 to 1.16.0, which fixed the libxml2.12 breaking changes. without the package upgrade mail catcher is currently broken.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by szucsitg** [comment]
@zarelit and @nicknovitski could you check this PR? thanks in advance

**Comment by zarelit** [comment]
not saying that it's wrong to update the lockfile resolution but I am missing something, why do you say it's broken?

the nixos test runs fine and so are my manual tests, what are you experiencing @szucsitg ?

**Comment by szucsitg** [comment]
it's broken on macOS, log is here: https://gist.github.com/szucsitg/79906f72e6e07cb48079b82cc0e12e63

vendored libxml2 was updated to 2.12, I'm pretty sure one of the reason was this: https://github.com/sparklemotion/nokogiri/releases/tag/v1.16.0

**Review by zarelit — APPROVED** [review]
LGTM

**Comment by szucsitg** [comment]
What would be the next step to get this merged?

**Review by cole-h — APPROVED** [review]
Builds for me on my aarch64-darwin machine (and, maybe obviously, doesn't before this).

Thanks!

**Pull request merged**
