### PR TITLE
yesod-bin: fix to work with GHC 8.0.1

### PR DESCRIPTION
**Pull request by vandenoever**
###### Motivation for this change

yesod devel does not work with GHC 8.0.1
https://github.com/yesodweb/yesod/issues/1284
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by sternenseemann** [comment]
I guess you have to use the correct [commit style for update commits](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes).

e. g. `yesod-bin: 1.4.18.5 -> 1.4.18.7`

**Comment by vandenoever** [comment]
done

**Comment by joachifm** [comment]
The Hackage package set is automatically generated from upstream at regular intervals, so this will be fixed by itself the next time that happens.

**Comment by joachifm** [comment]
The various `haskell-modules/configuration-*.nix` files is the right place for manual overrides.

**Pull request closed without merging**
