### PR TITLE
Fix docker tools nix symlinks

### PR DESCRIPTION
**Pull request by roberth**
###### Motivation for this change

`tar` transforms were breaking the symlink targets in the `nix` package when packaged as a layered image.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nlewo** [comment]
@GrahamcOfBorg test docker-tools

**Review by nlewo — APPROVED** [review]

**Comment by tfc** [comment]
lgtm, but there is a strange fail in the borg test in the python stuff that somehow does not look like it's really from your changes...

**Comment by roberth** [comment]
The same test does succeed on `aarch64-linux` and I had no issues running it locally multiple times while working on this. I'll assume it's unrelated to this change.

**Comment by roberth** [comment]
To provide some context, this was caused by https://github.com/hercules-ci/nixpkgs/commit/886c92332c8c9ecf62de9ab12789a6c4ee5207fc which seems to be a port of the idea of https://github.com/NixOS/nixpkgs/pull/58431/files.
Ultimately this is a fix for a fix https://github.com/NixOS/nixpkgs/pull/75911/files

**Pull request merged**
