### PR TITLE
[WIP] RFC #33

### PR DESCRIPTION
**Pull request by oxij**
See NixOS/rfcs#33, ignore the first two patches.

### CODE REVIEW

**Comment by Profpatsch** [comment]
Tangential: I’d leave the stuff in `debug.nix` and make `debug.nix` depend on `logging.nix`. Debug statements should usually not stay in the code once it’s commited.

**Comment by mmahut** [comment]
Are there any updates on this pull request, please?

**Comment by Profpatsch** [comment]
@oxij Do you intend to finish this WIP?

**Comment by oxij** [comment]
Yes, I plan to return to semi-fulltime nixpkgs hacking in a couple of months and this is near the top of the TODO list.

**Comment by Profpatsch** [comment]
@oxij still the case?

**Comment by oxij** [comment]
Yes (except for the timeline). This is not forgotten.

**Pull request closed without merging**
