### PR TITLE
shaderc: 2021.0 -> 2022.4

### PR DESCRIPTION
**Pull request by Ralith**
###### Description of changes

2021.0 is really old, missing critical features like SPIR-V intrinsics.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by PedroHLC** [comment]
libplacebo seems to fail to build here:
```console
error: builder for '/nix/store/9zfpczw05l9r22vbqayyq43j1lghnhjn-libplacebo-4.208.0.drv' failed with exit code 1;
       last 10 log lines:
       > [48/52] Compiling C object src/libplacebo.so.208.p/opengl_utils.c.o
       > [49/52] Compiling C object src/libplacebo.so.208.p/opengl_gpu_tex.c.o
       > [50/52] Compiling C object src/libplacebo.so.208.p/opengl_gpu_pass.c.o
       > [51/52] Compiling C++ object src/libplacebo.so.208.p/glsl_glslang.cc.o
       > FAILED: src/libplacebo.so.208.p/glsl_glslang.cc.o
       > g++ -Isrc/libplacebo.so.208.p -Isrc -I../src -Isrc/include -I../src/include -I/nix/store/862ndg8ph789sqyszqkdw2ginylf285x-libunwind-1.6.2-dev/include -I/nix/store/52sbwxkfdiyr0dvv0nanz618p6vkk1f6-lcms2-2.13.1-dev/include -I/nix/store/ph180wkgklhfj5wazjna16s8hmc8y4ns-shaderc-2022.4-dev/include -I/nix/store/bszqaw7ycydvqffylvr0va0van0hi0is-vulkan-headers-1.3.231.0/include -I/nix/store/6hxd0x3d1nkkyara7w8aq5sv3pj5ra8a-libepoxy-1.5.10-dev/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++11 -Wundef -Wshadow -Wparentheses -Wpointer-arith -fvisibility=hidden -fPIC -pthread -MD -MQ src/libplacebo.so.208.p/glsl_glslang.cc.o -MF src/libplacebo.so.208.p/glsl_glslang.cc.o.d -o src/libplacebo.so.208.p/glsl_glslang.cc.o -c ../src/glsl/glslang.cc
       > ../src/glsl/glslang.cc:224:1: error: cannot convert '<brace-enclosed initializer list>' to 'int' in initialization
       >   224 | };
       >       | ^
       > ninja: build stopped: subcommand failed.
```

**Comment by PedroHLC** [comment]
Result of `nixpkgs-review pr 206756` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>obs-studio-plugins.obs-hyperion</li>
  </ul>
</details>
<details>
  <summary>67 packages failed to build:</summary>
  <ul>
    <li>adl</li>
    <li>ani-cli</li>
    <li>anime-downloader</li>
    <li>anki</li>
    <li>ankisyncd</li>
    <li>arcanPackages.all-wrapped</li>
    <li>arcanPackages.arcan</li>
    <li>arcanPackages.arcan-wrapped</li>
    <li>arcanPackages.cat9-wrapped</li>
    <li>arcanPackages.durden-wrapped</li>
    <li>arcanPackages.pipeworld-wrapped</li>
    <li>arcanPackages.prio-wrapped</li>
    <li>arcanPackages.xarcan</li>
    <li>celluloid</li>
    <li>cplay-ng</li>
    <li>curseradio</li>
    <li>dmlive</li>
    <li>ff2mpv</li>
    <li>haruna</li>
    <li>hydrus</li>
    <li>hypnotix</li>
    <li>jellyfin-media-player</li>
    <li>jellyfin-mpv-shim</li>
    <li>jftui</li>
    <li>kaffeine</li>
    <li>kphotoalbum</li>
    <li>libplacebo</li>
    <li>libsForQt5.elisa (plasma5Packages.elisa)</li>
    <li>libsForQt5.phonon-backend-vlc (plasma5Packages.phonon-backend-vlc)</li>
    <li>libvlc</li>
    <li>megaglest</li>
    <li>minitube</li>
    <li>mnemosyne</li>
    <li>mpc-qt</li>
    <li>mpv</li>
    <li>mpv-unwrapped</li>
    <li>mpvScripts.mpris</li>
    <li>mpvpaper</li>
    <li>obs-studio</li>
    <li>obs-studio-plugins.input-overlay</li>
    <li>obs-studio-plugins.looking-glass-obs</li>
    <li>obs-studio-plugins.obs-backgroundremoval</li>
    <li>obs-studio-plugins.obs-gstreamer</li>
    <li>obs-studio-plugins.obs-move-transition</li>
    <li>obs-studio-plugins.obs-multi-rtmp</li>
    <li>obs-studio-plugins.obs-nvfbc</li>
    <li>obs-studio-plugins.obs-pipewire-audio-capture</li>
    <li>obs-studio-plugins.obs-source-record</li>
    <li>obs-studio-plugins.obs-vkcapture</li>
    <li>obs-studio-plugins.wlrobs</li>
    <li>plex-media-player</li>
    <li>plex-mpv-shim</li>
    <li>pympress</li>
    <li>python310Packages.mpv</li>
    <li>python310Packages.python-vlc</li>
    <li>python39Packages.mpv</li>
    <li>python39Packages.python-vlc</li>
    <li>qimgv</li>
    <li>radioboat</li>
    <li>reaper</li>
    <li>somafm-cli</li>
    <li>strawberry</li>
    <li>stremio</li>
    <li>sublime-music</li>
    <li>vlc</li>
    <li>wtwitch</li>
    <li>ytfzf</li>
  </ul>
</details>
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>shaderc</li>
    <li>superTuxKart</li>
    <li>warzone2100</li>
  </ul>
</details>

**Comment by Ralith** [comment]
Good catch. This was due to the packaged libplacebo version being incomptaible with the glslang version bundled by shaderc, which shadows the nixpkgs glslang. Fixed by removing the redundant dependency on nixpkgs glslang.

**Comment by PedroHLC** [comment]
Result of `nixpkgs-review pr 206756` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>obs-studio-plugins.obs-hyperion</li>
  </ul>
</details>
<details>
  <summary>72 packages built:</summary>
  <ul>
    <li>adl</li>
    <li>ani-cli</li>
    <li>anime-downloader</li>
    <li>anki</li>
    <li>ankisyncd</li>
    <li>arcanPackages.all-wrapped</li>
    <li>arcanPackages.arcan</li>
    <li>arcanPackages.arcan-wrapped</li>
    <li>arcanPackages.cat9-wrapped</li>
    <li>arcanPackages.durden-wrapped</li>
    <li>arcanPackages.pipeworld-wrapped</li>
    <li>arcanPackages.prio-wrapped</li>
    <li>arcanPackages.xarcan</li>
    <li>celluloid</li>
    <li>cplay-ng</li>
    <li>curseradio</li>
    <li>dmlive</li>
    <li>eaglemode</li>
    <li>ff2mpv</li>
    <li>gonic</li>
    <li>haruna</li>
    <li>hydrus</li>
    <li>hypnotix</li>
    <li>jellyfin-media-player</li>
    <li>jellyfin-mpv-shim</li>
    <li>jftui</li>
    <li>kaffeine</li>
    <li>kphotoalbum</li>
    <li>libplacebo</li>
    <li>libsForQt5.elisa (plasma5Packages.elisa)</li>
    <li>libsForQt5.phonon-backend-vlc (plasma5Packages.phonon-backend-vlc)</li>
    <li>libvlc</li>
    <li>megaglest</li>
    <li>minitube</li>
    <li>mnemosyne</li>
    <li>mpc-qt</li>
    <li>mpv</li>
    <li>mpv-unwrapped</li>
    <li>mpvScripts.inhibit-gnome</li>
    <li>mpvScripts.mpris</li>
    <li>mpvpaper</li>
    <li>obs-studio</li>
    <li>obs-studio-plugins.input-overlay</li>
    <li>obs-studio-plugins.looking-glass-obs</li>
    <li>obs-studio-plugins.obs-gstreamer</li>
    <li>obs-studio-plugins.obs-move-transition</li>
    <li>obs-studio-plugins.obs-multi-rtmp</li>
    <li>obs-studio-plugins.obs-nvfbc</li>
    <li>obs-studio-plugins.obs-pipewire-audio-capture</li>
    <li>obs-studio-plugins.obs-source-record</li>
    <li>obs-studio-plugins.obs-vkcapture</li>
    <li>obs-studio-plugins.wlrobs</li>
    <li>plex-media-player</li>
    <li>plex-mpv-shim</li>
    <li>pympress</li>
    <li>python310Packages.mpv</li>
    <li>python310Packages.python-vlc</li>
    <li>python39Packages.mpv</li>
    <li>python39Packages.python-vlc</li>
    <li>qimgv</li>
    <li>radioboat</li>
    <li>reaper</li>
    <li>shaderc</li>
    <li>somafm-cli</li>
    <li>strawberry</li>
    <li>stremio</li>
    <li>sublime-music</li>
    <li>superTuxKart</li>
    <li>vlc</li>
    <li>warzone2100</li>
    <li>wtwitch</li>
    <li>ytfzf</li>
  </ul>
</details>

**Review by PedroHLC — APPROVED** [review]
Not only it built this time, but I checked that Anime4K's GLSL shaders still works in MPV.

**Review by thiagokokada — APPROVED** [review]

**Pull request merged**
