### PR TITLE
libxml2: 2.10.4 → 2.11.4

### PR DESCRIPTION
**Pull request by jtojnar**
###### Description of changes

Reviewed changelogs and autotools.
Many minor memory safety and performance improvements.

Fixes: https://github.com/NixOS/nixpkgs/pull/239285

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] Built
  - shadow (heavy itstool usage)
  - glib (gtk-doc)
  - systemd (without bpf, manual pages)
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by trofi** [comment]
Bisect says 7d9be8a366921ed8193a4b58a8e8bde5f94daa1d `libxml2: 2.10.4 → 2.11.4` broke `librdf_raptor2` in `staging` as:

```
src/raptor_libxml.c:257:10: error: 'xmlEntity' {aka 'struct _xmlEntity'} has no member named 'checked'
```

It is already fixed upstream. Proposed possible `nixpkgs` fix as: https://github.com/NixOS/nixpkgs/pull/242012

**Comment by trofi** [comment]
Bisect says https://github.com/NixOS/nixpkgs/commit/7d9be8a366921ed8193a4b58a8e8bde5f94daa1d `libxml2: 2.10.4 → 2.11.4` broke `gupnp` in `staging` as:

```
$ nix build --no-link -f. gupnp -L
...
gupnp> ../libgupnp/gupnp-control-point.c: In function 'got_description_url':
gupnp> ../libgupnp/gupnp-control-point.c:616:17: error: 'xmlRecoverMemory' is deprecated [-Werror=deprecated-declarations]
gupnp>   616 |                 xml_doc = xmlRecoverMemory (msg->response_body->data,
gupnp>       |                 ^~~~~~~
```

Probably fixed by https://github.com/GNOME/gupnp/commit/80e68995b745a5900eaaa1d0c424d3a9d354e42d (part of released `1.6.4` 1 week ago).

**Comment by jtojnar** [comment]
We have that in #241751

**Comment by trofi** [comment]
Looks like `gupnp` points to `1.4` branch. Might need a backport still.

**Comment by jtojnar** [comment]
Opened [backport MR upstream](https://gitlab.gnome.org/GNOME/gupnp/-/merge_requests/34) and cherry-picked it to https://github.com/NixOS/nixpkgs/pull/241751.

**Comment by amjoseph-nixpkgs** [comment]
Hello, this appears to have made `perl5.36.0-XML-LibXML` fail a few new tests:

https://github.com/NixOS/nixpkgs/issues/243214

I don't know much about XML (or Perl, really), but I would like to be able to run the nixos-vm tests again, and they depend on `perl5.36.0-XML-LibXML` via `grub`.

Can you suggest a course of action?  Does it look safe to disable/ignore the newly-failing tests in `perl5.36.0-XML-LibXML`?

Thanks,

**Comment by jtojnar** [comment]
Skipping the tests and reporting that [upstream](https://github.com/shlomif/perl-XML-LibXML) is probably the best approach for now.

**Comment by martinetd** [comment]
Opened https://github.com/shlomif/perl-XML-LibXML/issues/79

**Pull request merged**
