### PR TITLE
ipmicfg: update to 1.34.1

### PR DESCRIPTION
**Pull request by georgewhewell**
###### Description of changes
previous version has been moved, no longer builds. update to latest

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by sorki — APPROVED** [review]

**Review by Janik-Haag — COMMENTED** [review]
This seems like a easy merge but the build fails for me locally, can you look into this?
```
nix-build -A ipmicfg       
these 2 derivations will be built:
  /nix/store/pnp4cchhljjvp8c4xm96r1pvrmglvs54-source.drv
  /nix/store/xr7jx7f220zgndrn5433zvcdsj21zh3b-ipmicfg-1.34.1.drv
building '/nix/store/pnp4cchhljjvp8c4xm96r1pvrmglvs54-source.drv'...

trying https://www.supermicro.com/wftp/utility/IPMICFG/IPMICFG_1.34.1_build.221026.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   201  100   201    0     0    387      0 --:--:-- --:--:-- --:--:--   387
100   150  100   150    0     0    198      0 --:--:-- --:--:-- --:--:--   198
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  158k    0  158k    0     0   158k      0 --:--:-- --:--:-- --:--:--  158k
unpacking source archive /build/IPMICFG_1.34.1_build.221026.zip
[/build/IPMICFG_1.34.1_build.221026.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /build/IPMICFG_1.34.1_build.221026.zip or
        /build/IPMICFG_1.34.1_build.221026.zip.zip, and cannot find /build/IPMICFG_1.34.1_build.221026.zip.ZIP, period.
do not know how to unpack source archive /build/IPMICFG_1.34.1_build.221026.zip
error: builder for '/nix/store/pnp4cchhljjvp8c4xm96r1pvrmglvs54-source.drv' failed with exit code 1;
```

**Comment by Janik-Haag** [comment]
Oh and please also rename your commit to `$pnam: $old_version -> $new_version` to fit `contributing.md`

**Comment by georgewhewell** [comment]
@Janik-Haag thx for review. seems like the URL to latest release is removed each time version is updated, this derivation will constantly break- closing

**Comment by Janik-Haag** [comment]
oh well :(

**Pull request closed without merging**
