### PR TITLE
deltachat-desktop: remove noop override

### PR DESCRIPTION
**Pull request by figsoda**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by NickCao — APPROVED** [review]

**Comment by dotlambda** [comment]
deltachat-desktop has to be shipped with an exact version of libdeltachat

**Comment by dotlambda** [comment]
Why was my review not requested???

**Comment by figsoda** [comment]
> Why was my review not requested???

Sorry about that, I thought the change was trivial enough and there were 0 rebuilds.

However, I still don't think keeping the patch makes sense in this case, since `libdeltachat` is only consumed by `deltachat-desktop` and `kdeltachat`, and we are having to ship a very large Cargo.lock for this

**Comment by dotlambda** [comment]
> However, I still don't think keeping the patch makes sense in this case, since `libdeltachat` is only consumed by `deltachat-desktop` and `kdeltachat`, and we are having to ship a very large Cargo.lock for this

So you suggest shipping a broken deltachat-desktop?
 
> Also, the build failure could have been mitigated if anyone ran nixpkgs-review on #242425

There is no build failure. Its functionality might be slightly broken though.

**Comment by figsoda** [comment]
No, I suggest keeping libdeltachat on the same version that deltachat-desktop requires, if compatibility is a concern

**Comment by dotlambda** [comment]
> No, I suggest keeping libdeltachat on the same version as what deltachat-desktop requires, if compatibility is a concern

That would mean e.g. not having an up-to-date `python3.pkgs.deltachat`.

**Comment by figsoda** [comment]
> That's a non-issue for the git repo since that file is deduplicated and was previously used by `libdeltachat`.

It does have an impact on the archive tarball

**Pull request merged**
