### PR TITLE
go_1_21: fix cross-compiling other packages

### PR DESCRIPTION
**Pull request by tie**
## Description of changes

Switch to distpack missed the fact that GOOS/GOARCH was set to targetPlatform instead of hostPlatform so Go package used in buildGoModule was built for the wrong platform (in this case, build = host since we need to run Go on the build platform, but host ≠ target when cross-compiling).

This change refactors build process for go1.21 to expose GOOS/GOARCH via passhtru set to targetPlatform for compatiblity (since that’s what other Go versions do), and build for hostPlatform as expected.

In addition to that, Go is a cross-compiler, that is, targetPlatform is not relevant as it can build for any supported platform out-of-the-box, and release builds are statically linked and do not require Cgo or C/C++ toolchain in general. Before this change, Go builds embedded C toolchain reference for the targetPlatform (via {CC,CXX}_FOR_TARGET environment variable). Now we expect that dependent packages configure CC/CXX for their target platform (this should already be handled automatically when using stdenv.mkDerivation and therefore buildGoModule).

Addresses https://github.com/NixOS/nixpkgs/pull/254497#issuecomment-1727653073

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zowoq** [comment]
Thanks for working on this but these changes are more significant than I am comfortable merging as a quick fix.

I'm going to revert the original changes from https://github.com/NixOS/nixpkgs/pull/254497 in https://github.com/NixOS/nixpkgs/pull/256588 so we can take a bit more to make sure that either aren't any regressions.

**Comment by tie** [comment]
@zowoq, should I reopen the original PR with the these changes applied?

**Comment by zowoq** [comment]
> @zowoq, should I reopen the original PR with the these changes applied?

Including them in this PR is fine.

**Comment by tie** [comment]
I’m currently working on decoupling Go package and build infrastructure so that the latter does not depend on the former. That is, `*Platform`s will contain `goPlatform.{GOOS,GOARCH,etc}`. This should make reviewing this change easier since changing the package implementation details would not affect `buildGo{Package,Module}`.

**Pull request closed without merging**
