### PR TITLE
qt5: 5.15.0 -> 5.15.1

### PR DESCRIPTION
**Pull request by gebner**
###### Motivation for this change

New upstream version.

Closes #100041.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by gebner** [comment]
I didn't try to build everything that depends on qt, but I don't expect much breakage since this is just a point release.

**Comment by FRidh** [comment]
KDE frameworks package `purpose` fails and thereby the application `okular` as well.
```
builder for '/nix/store/v1k26dcl0wnpj571a7isx38sn694hrx0-purpose-5.73.0.drv' failed with exit code 2; last 10 log lines:
     96 |         const auto socketError = m_socket.socketError();
        |                                           ^~~~~~~~~~~
        |                                           LocalSocketError
  /build/purpose-5.73.0/src/externalprocess/purposeprocess_main.cpp: In function 'int main(int, char**)':
  /build/purpose-5.73.0/src/externalprocess/purposeprocess_main.cpp:136:76: note: #pragma message: warning: make QGuiApplication, consider QCoreApplication?
    136 | #pragma message("warning: make QGuiApplication, consider QCoreApplication?")
        |                                                                            ^
  make[2]: *** [src/CMakeFiles/purposeprocess.dir/build.make:95: src/CMakeFiles/purposeprocess.dir/externalprocess/purposeprocess_main.cpp.o] Error 1
  make[1]: *** [CMakeFiles/Makefile2:671: src/CMakeFiles/purposeprocess.dir/all] Error 2
  make: *** [Makefile:149: all] Error 2
```

**Comment by FRidh** [comment]
Rebuilding my system now with this update based on top of https://github.com/NixOS/nixpkgs/pull/101369.

**Comment by unclechu** [comment]
It probably closes #98009 too.

**Comment by doronbehar** [comment]
@gebner could you please add the patch I wanted to add in https://github.com/NixOS/nixpkgs/pull/100041 ?

See also: https://github.com/NixOS/nixpkgs/pull/99456#issuecomment-703523943 .

**Comment by gebner** [comment]
@doronbehar The patch is already included.

**Comment by FRidh** [comment]
https://github.com/NixOS/nixpkgs/commit/ffe65c35874e175abac6619f2563ff4db0291e1f is needed for kpurpose.

**Comment by unclechu** [comment]
It seems this one doesn’t #98009. Am I testing this correctly? It took a while before everything compiles.


``` sh
nix-shell -E 'let pkgs=import (fetchTarball {url="https://github.com/NixOS/nixpkgs/archive/5856b4c99356e63119daa14f01626891b03af539.tar.gz";}) {}; in pkgs.mkShell {buildInputs = [pkgs.vlc];}' --run vlc
```


``` sh
nix-shell -E 'let pkgs=import (fetchTarball {url="https://github.com/NixOS/nixpkgs/archive/5856b4c99356e63119daa14f01626891b03af539.tar.gz";}) {}; in pkgs.mkShell {buildInputs = [pkgs.audacious pkgs.vlc];}' --run audacious
```

**Comment by gnidorah** [comment]
@unclechu 
As I told you before, vlc is forcefully built with 5.14
`vlc = libsForQt514.callPackage ../applications/video/vlc {};`
This PR just bumps Qt 5.15, nothing more

**Comment by unclechu** [comment]
First I applied a patch made of #102594 on top of `nixos-unstable`, it fixed dark theme for `vlc` and `psi-plus` for me but not `audacous`. Then I applied also this PR:
```sh
(set -eo pipefail && curl --fail -Ls https://github.com/NixOS/nixpkgs/pull/102216.patch | git apply)
```
And this also fixed `audacious` for me.

I rebuilt the system by this command (while being in a directory of `nixpkgs` repository):
``` sh
sudo nixos-rebuild switch -I nixpkgs="$PWD"
```
I didn’t test this MR without #102594 yet.

**Comment by unclechu** [comment]
I tested this PR separately and it only fixed `audacious` for me, `vlc` and `psi-plus` were still having light theme. So both #102594 and #102216 to fix Adwaita Dark for Qt applications.

**Comment by doronbehar** [comment]
Thanks for your report @unclechu, very appreciated.

**Comment by poelzi** [comment]
This should go into nixos 20.09 or better #104448 since it got more bugfixes as well.

**Comment by ttuegel** [comment]
I'm going to close this in favor of #106118. We should consolidate our efforts there, as it is the most complete pull request in the Qt 5.15.2 series.

**Pull request closed without merging**
