### PR TITLE
nixos/tests/prowlarr: check for folder existence

### LINKED ISSUE #155475: prowlarr: not working correctly without user
### Describe the bug
when using:
```
services.prowlarr.enable = true;
```
the resulting service is having multiple errors and does not work like intended:
```
2022-01-18 14:21:35.8|Fatal|ProwlarrErrorPipeline|Request Failed. GET /api/v1/update

[v0.1.8.1231] System.Net.WebException: The SSL connection could not be established, see inner exception.: 'https://prowlarr.servarr.com/v1/update/develop/changes?version=0.1.8.1231&os=linux&arch=Arm64&runtime=netc
ore&runtimeVer=6.0.0&prevVersion=0.1.2.1060&active=false'
 ---> System.Net.WebException: The SSL connection could not be established, see inner exception.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.InvalidOperationException: The home directory of the current user could not be determined.
```

### Steps To Reproduce
1. `services.prowlarr.enable = true;`

### Expected behavior
No errors and the applications works

### Possible ugly fix:
adding:
```
users.users.prowlarr = {
  isSystemUser = true;
  home = "/var/lib/prowlarr";
  group = "prowlarr";
  uid = 61654;
};
users.groups.prowlarr.gid = 61654;
```

### Notify maintainers

@jdreaver

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.06 MiB download, 0.30 MiB unpacked):
  /nix/store/vs01795cwqz8mf3fxvhh85dhwh3w9h6d-bash-interactive-5.1-p8-dev
copying path '/nix/store/vs01795cwqz8mf3fxvhh85dhwh3w9h6d-bash-interactive-5.1-p8-dev' from 'https://cache.nixos.org'...
 - system: `"aarch64-linux"`
 - host os: `Linux 5.10.52, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.335288.3ddd960a3b5, nixos-unstable-22.05pre343321.78cd22c1b86"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by Stunkymonkey**
## Description of changes

improve #155475

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Stunkymonkey** [comment]
ping @jdreaver ?

**Comment by justinas** [comment]
I'm afraid I don't quite get how this could fix the linked issue. This improves the tests with further checks that prowlarr is functioning as expected, but does not change anything about the module itself?

If this test passes consistently, either the issue is gone, or it is not reproduced in the test. The issue is inconsistent even in real deployments, as noted in the comments in #155475 .

**Comment by Stunkymonkey** [comment]
I did 3 reinstalls in the last months and never experienced this again. Therefore I guess the issue is no longer there.

**Comment by Stunkymonkey** [comment]
@justinas can we then merge this and keep the issue open?

**Review by justinas — APPROVED** [review]
The test change itself LGTM. :+1:

**Pull request merged**
