### PR TITLE
python3Packages.grandalf: 0.6 -> 0.7, dvc: 0.24.3 -> 2.9.3

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 0.7

Switch to `pytestCheckHook`

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 155094` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>python310Packages.scmrepo</li>
  </ul>
</details>
<details>
  <summary>19 packages built:</summary>
  <ul>
    <li>dvc</li>
    <li>dvc-with-remotes</li>
    <li>python310Packages.aiohttp-retry</li>
    <li>python310Packages.dictdiffer</li>
    <li>python310Packages.flatten-dict</li>
    <li>python310Packages.grandalf</li>
    <li>python310Packages.mailchecker</li>
    <li>python310Packages.python-benedict</li>
    <li>python310Packages.python-fsutil</li>
    <li>python310Packages.shtab</li>
    <li>python39Packages.aiohttp-retry</li>
    <li>python39Packages.dictdiffer</li>
    <li>python39Packages.flatten-dict</li>
    <li>python39Packages.grandalf</li>
    <li>python39Packages.mailchecker</li>
    <li>python39Packages.python-benedict</li>
    <li>python39Packages.python-fsutil</li>
    <li>python39Packages.scmrepo</li>
    <li>python39Packages.shtab</li>
  </ul>
</details>

**Comment by fabaff** [comment]
`gevent` doesn't work with Python 3.10 at the moment.

**Comment by risicle** [comment]
`nixpkgs-review ... --package-regex="python39"` passes on macos 10.15 (everything python 3.10 seems broken on macos at the moment)

`nixpkgs-review` on nixos x86_64 and aarch64, only `python310Packages.scmrepo` fails

**Comment by fabaff** [comment]
@ofborg build dvc

**Pull request merged**
