### PR TITLE
oatpp: init at 1.2.0

### PR DESCRIPTION
**Pull request by IvarWithoutBones**
###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by RaghavSood** [comment]
Result of `nixpkgs-review pr 105419` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>oatpp</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
Fails on darwin:

```
 D |2020-11-30 14:38:21 1606747101058826| TEST[web::server::api::ApiControllerTest]:response:
---
HTTP/1.1 200 OK
Content-Length: 5

test3
---

 I |2020-11-30 14:38:21 1606747101059128| TEST[web::server::api::ApiControllerTest]:FINISHED - success!
 I |2020-11-30 14:38:21 1606747101059414| TEST[web::server::api::ApiControllerTest]:1090(micro), 68(objs)

 I |2020-11-30 14:38:21 1606747101059724| TEST[web::server::handler::AuthorizationHandlerTest]:START...
 V |2020-11-30 14:38:21 1606747101060020| TEST[web::server::handler::AuthorizationHandlerTest]:header="Basic Zm9vOmJhcg==" -> user="foo" password="bar"
 V |2020-11-30 14:38:21 1606747101060313| TEST[web::server::handler::AuthorizationHandlerTest]:header="Basic Zm9vOmJhcg==" -> user="foo" password="bar"
 I |2020-11-30 14:38:21 1606747101060599| TEST[web::server::handler::AuthorizationHandlerTest]:FINISHED - success!
 I |2020-11-30 14:38:21 1606747101060935| TEST[web::server::handler::AuthorizationHandlerTest]:593(micro), 15(objs)

 I |2020-11-30 14:38:21 1606747101061246| TEST[web::PipelineTest]:START...
 D |2020-11-30 14:38:21 1606747101061829| ClientServerTestRunner:Running server on port 0. Timeout 600000000(micro)
 D |2020-11-30 14:38:21 1606747101062393| TEST[web::PipelineTest]:want to Receive 294000 bytes
 D |2020-11-30 14:38:21 1606747101062623| TEST[web::PipelineTest]:Sending 183000 bytes
 D |2020-11-30 14:38:21 1606747101105735| ClientServerTestRunner:Finished with time 43903(micro). Stopping server...
 I |2020-11-30 14:38:22 1606747102116478| TEST[web::PipelineTest]:FINISHED - success!
 I |2020-11-30 14:38:22 1606747102116876| TEST[web::PipelineTest]:1054920(micro), 30307(objs)

 I |2020-11-30 14:38:22 1606747102117166| TEST[web::PipelineTest]:START...
 E |2020-11-30 14:38:22 1606747102119205| [oatpp::network::tcp::server::ConnectionProvider::instantiateServer()]:Error. Call to getaddrinfo() failed with result=8: Operation not permitted
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: [oatpp::network::tcp::server::ConnectionProvider::instantiateServer()]: Error. Call to getaddrinfo() failed.


0% tests passed, 1 tests failed out of 1

Total Test time (real) =  24.15 sec

The following tests FAILED:
          1 - oatppAllTests (Child aborted)
Errors while running CTest
make: *** [Makefile:149: test] Erro
```

**Comment by IvarWithoutBones** [comment]
> Fails on darwin

I've disabled tests on Darwin for now, would you mind testing again?

**Comment by doronbehar** [comment]
@GrahamcOfBorg build oatpp

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 105419` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>oatpp</li>
  </ul>
</details>

**Pull request merged**
