### PR TITLE
shotcut: use qt5's mkDerivation

### PR DESCRIPTION
**Pull request by rawkode**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @goibhniu @woffs

Related: #65399

### CODE REVIEW

**Comment by woffs** [comment]
@GrahamcOfBorg build shotcut

**Comment by worldofpeace** [comment]
cc https://github.com/NixOS/nixpkgs/issues/65399

**Review by worldofpeace — CHANGES_REQUESTED** [review]
This program is already using a wrapper in `postInstall`

```
wrapProgram $out/bin/shotcut --prefix FREI0R_PATH : ${frei0r}/lib/frei0r-1 --prefix LD_LIBRARY_PATH : ${stdenv.lib.makeLibraryPath [ jack1 SDL2 ]} --prefix PATH : ${mlt}/bin
```

That will produce multiple wrappers which isn't desirable.

We can fix this by using `qtWrapperArgs`.
See the qt manual on this 
* https://hydra.nixos.org/build/96804884/download/1/nixpkgs/manual.html#sec-language-qt

**Comment by rawkode** [comment]
@worldofpeace @grahamc Ready :+1:

**Review by worldofpeace — APPROVED** [review]
Builds and executes, verified that the binary was wrapped.

In the force push I removed an un-referenced `makeWrapper`.

**Pull request merged**
