### PR TITLE
1password-gui: add macOS builds and unify beta

### PR DESCRIPTION
**Pull request by Enzime**
###### Description of changes

Unifies `default.nix` and `beta.nix` into one derivation as they are the same and add macOS builds :)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SebTM** [comment]
```
error: anonymous function at /home/sebtm/Projects/Nix/Nixpkgs/nixos-unstable/pkgs/applications/misc/1password-gui/default.nix:1:1 called with unexpected argument 'polkitPolicyOwners'
at /home/sebtm/Projects/Nix/Nixpkgs/nixos-unstable/lib/customisation.nix:69:16:

68|     let
69|       result = f origArgs;
                |                ^
```

Didn't evaluate on my machine, had to add `polkitPolicyOwners` to `default.nix` and pass it through to `linux.nix`. 

```
diff --git a/pkgs/applications/misc/1password-gui/default.nix b/pkgs/applications/misc/1password-gui/default.nix
index f6607d7d932..6b00d524682 100644
--- a/pkgs/applications/misc/1password-gui/default.nix
+++ b/pkgs/applications/misc/1password-gui/default.nix
@@ -2,7 +2,12 @@
 , callPackage
 , channel ? "stable"
 , fetchurl
-, lib }:
+, lib
+
+# The 1Password polkit file requires a list of users for whom polkit
+# integrations should be enabled. This should be a list of strings that
+# correspond to usernames.
+, polkitPolicyOwners ? [] }:

 let

@@ -63,4 +68,4 @@ let

 in if stdenv.isDarwin
 then callPackage ./darwin.nix { inherit pname version src meta; }
-else callPackage ./linux.nix { inherit pname version src meta; }
+else callPackage ./linux.nix { inherit pname version src meta polkitPolicyOwners; }
diff --git a/pkgs/applications/misc/1password-gui/linux.nix b/pkgs/applications/misc/1password-gui/linux.nix
index 06a10dd973d..026597c513c 100644
--- a/pkgs/applications/misc/1password-gui/linux.nix
+++ b/pkgs/applications/misc/1password-gui/linux.nix
@@ -36,11 +36,7 @@
 , systemd
 , udev
 , xdg-utils
-
-  # The 1Password polkit file requires a list of users for whom polkit
-  # integrations should be enabled. This should be a list of strings that
-  # correspond to usernames.
-, polkitPolicyOwners ? []
+, polkitPolicyOwners
 }:
 let
   # Convert the polkitPolicyOwners variable to a polkit-compatible string for the polkit file.
```

or do I miss something?

**Comment by Enzime** [comment]
@SebTM good catch, fixed :+1:

**Review by SebTM — APPROVED** [review]

**Comment by maxeaubrey** [comment]
Does https://github.com/NixOS/nixpkgs/pull/181004#issuecomment-1190814236 no longer apply?

**Comment by Enzime** [comment]
@maxeaubrey somewhat, 1Password 8 refuses to launch as an application if the files aren’t in `/Applications`, but if you run `$out/Applications/1Password.app/Contents/MacOS/1Password` directly it will launch. Despite it not launching as an application, I think there is still value in packaging the application as a `nix-darwin` module could handle the logic of putting the application in `/Applications` (something I had to do for Karabiner-Elements as system extensions must reside in `/Applications`)

**Comment by maxeaubrey** [comment]
That seems subpar for Darwin users, especially as that workaround wouldn't be obviously surfaced. Are you planning on working on the macOS equivalent of the 1password module in a follow up PR?

Thank you for simplifying the Linux derivation.

**Comment by Enzime** [comment]
@maxeaubrey yes I am planning to write that module

**Review by SebTM — APPROVED** [review]

**Pull request merged**
