### PR TITLE
pythonPackages.pip: make package reproducible

### LINKED ISSUE #201146: python3Packages.pip: unreproducible vendored .exe files
Building this package twice does not produce the bit-by-bit identical result each time, making it harder to detect CI breaches. You can read more about this at https://reproducible-builds.org/ .

Fixing bit-by-bit reproducibility also has additional advantages, such as avoiding hard-to-reproduce bugs, making content-addressed storage more effective and reducing rebuilds in such systems.

### Steps To Reproduce

```
nix-build '<nixpkgs>' -A ... --check --keep-failed
```

You can use `diffoscope` to analyze the differences in the output of the two builds.

To view the build log of the build that produced the artifact in the binary cache:

```
nix-store --read-log $(nix-instantiate '<nixpkgs>' -A ...)
```

### Additional context

https://arnout.engelen.eu/nixos-iso-minimal-r13y/diff/ffa37e4adce50539c65c4062f803e2c6d34fda37c2061b039db029123d3942e9-a645067984e633a18d01c8de9eb2a0929ef47d6586e1b92e7cd878c24415aa0d.html

Also seen in https://github.com/NixOS/nixpkgs/issues/192728

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Description of changes

This fixes #201146 by removing the vendored Windows PE binaries.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested the package is reproducible and builds
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
Do these also exist in `bootstrapped-pip`? Otherwise, this change looks good to me.

**Comment by rnhmjoj** [comment]
> Do these also exist in bootstrapped-pip? Otherwise, this change looks good to me.

They do, I've reused the `postPatch` from pip in this one too.

**Comment by FRidh** [comment]
I see. Now it needs to target staging.

**Comment by rnhmjoj** [comment]
Done.

**Review by thiagokokada — APPROVED** [review]

**Comment by rnhmjoj** [comment]
Fixed a typo in the comment.

**Pull request merged**
