### PR TITLE
qt-gstreamer{,1}: drop

### PR DESCRIPTION
**Pull request by Anton-Latukha**
###### Motivation for this change
(Progresses Qt4 cleanup #33248, gstreamer cleanup #39975)

This was a GNOME-related projects to provide `gst` bindings to Qt folks, both legacy and latest officially stated as unmaintained.
Both has no dependencies.

It is derived from my https://github.com/NixOS/nixpkgs/issues/33248#issuecomment-532935353

### CODE REVIEW

**Review by jtojnar — APPROVED** [review]
Great. I would not mind dropping `qt-gstreamer1` as well.

**Review by teto — APPROVED** [review]

**Comment by Anton-Latukha** [comment]
Sorry distracting people, out of branch commits slipped in.

**Comment by Anton-Latukha** [comment]
@jtojnar
As you asked, now dropped both pakages {`qt-gstreamer` (legacy), `qt-gstreamer1`}.
```fish
> rg qt-gstreamer
---
(void)
```

**Comment by jtojnar** [comment]
Thanks.

**Pull request merged**
