### PR TITLE
Update vim_configurable to vim 8.0005

### LINKED ISSUE #18800: Update vim_configurable to vim 8.0005
## Issue description
Currently vim_configurable is version 7.4.826 where as vim is now 8.0005.

### Steps to reproduce
$ nix-env -f /path/to/nixpkgs -i vim_configurable
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  1 1970 00:00:01)
Included patches: 1-826
...

## Technical details
Updated version and sha256 in nixpkgs/**/vim/configurable.nix to be identical to
that in nixpkgs/**/vim/default.nix

* System: (NixOS: 16.09beta264.aadcffc (Flounder))
* Nix version: (nix-env (Nix) 1.11.4)
* Nixpkgs version: (17.03pre-git)

### PR DESCRIPTION
**Pull request by winksaville**
###### Motivation for this change

fix #18800 
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [x] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by groxxda** [comment]
Can't we just use the `src` from the regular vim expression? Otherwise this will diverge eventually

**Comment by LnL7** [comment]
I was wondering the same thing, this should probably use the vim drv as a starting point.

**Review by groxxda — APPROVED** [review]
Using `vim.src` is probably not worth the effort since vim needs refactoring anyway ( #18763 )

**Comment by winksaville** [comment]
I was wondering if vim should just be derived from vim_configurable as
vim_configurable is more general? But, I thought this was the simplest
thing for now as they've been using different versions for awhile.

**Comment by LnL7** [comment]
This breaks the darwin build, the python patch does not apply.

**Comment by winksaville** [comment]
@LnL7, when you say "the python patch doesn't apply", what python patch? How can I reproduce the problem? (Note: I'm a newbie so pardon my ignorance).

**Comment by LnL7** [comment]
@winksaville You can remove the `optional` call to always apply the patch, I can take a look if you can't figure it out but I'm not sure if I'll have time today.

https://github.com/winksaville/nixpkgs/blob/08d7cfa4203dd5adc8b98979ab085a8a100c3f34/pkgs/applications/editors/vim/configurable.nix#L76

**Comment by winksaville** [comment]
@LnL7 are you saying we never want to apply the patch or we always want to apply the patch? 
Is this a problem with vim 8.005 only or with other builds too? For instance I noticed that vim/configurable.nix was using 7.4.826 where as previously vim/default.nix was using 7.4.1585.

Also, note the odd logic in line 75 with the 'or true':
    (stdenv.isDarwin && (config.vim.darwin or true))

I currently don't have a darwin environment setup so I'm unable to test.

**Comment by LnL7** [comment]
@winksaville I suspect the `vim` package does not need that patch because it does not have python support

**Comment by groxxda** [comment]
@winksaville the `attr.path or true` is common. It is there because `config` might not have a `vim` attribute, or if it has, that `vim` attribute set might not have a `darwin` attribute. Accessing an invalid key will yield an error, but the `or true` will "catch" the error and return true instead:
```
nix-repl> config = { vim = { linux = true; }; }

nix-repl> config.vim.darwin
error: attribute ‘darwin’ missing, at (string):1:1

nix-repl> config.vim.darwin or true
true
```

@LnL7 was suggesting you remove the `optional` so when you build `vim` the patch gets applied.

Another option would be to get the source manually and apply the patch. Or with help of nix:
```
 ~/nixpkgs nix-shell . -A vim_configurable 

[nix-shell:~/nixpkgs]$ cd /tmp

[nix-shell:/tmp]$ unpackPhase
[3punpacking source archive /nix/store/yhz9549411wsyfp5anxlclgcb266xvva-vim-v7.4.826-src
[qsource root is vim-v7.4.826-src

[nix-shell:/tmp]$ cd vim-v7.4.826-src/

[nix-shell:/tmp/vim-v7.4.826-src]$ $prePatch 

[nix-shell:/tmp/vim-v7.4.826-src/src]$ patch < ~/nixpkgs/pkgs/applications/editors/vim/python_framework.patch
patching file configure
[...]
```
This will most probably fail and you can inspect further. Interestingly the patch did not apply for me with the old vim version either...

**Comment by winksaville** [comment]
@groxxda, but doen't `(config.vim.darwin or true)` always evaluate to true and would therefore appear to me to be unnecessary. And regarding removing `optional` that's trivial but doing much beyond that is going to get me into trouble with you guys.

@LnL7, python can support python as an interpreter although I've never used it, see [here](http://stackoverflow.com/questions/4104202/what-is-the-vim-feature-enable-pythoninterp) and [here](https://zerokspot.com/weblog/2009/02/21/getting-to-know-vims-python-interface/) for instance. So I'm guessing if you install vim using nix is that vim should use nix's version of python not some random version installed on the platform. But as I said, I'm just guessing.

**Comment by groxxda** [comment]
@winksaville i admit this is not intuitive because the `or` is quite different from the logic `||`:
```
nix-repl> { x = false; }.x or true
false

nix-repl> { x = false; }.x or false
false

nix-repl> { x = false; }.y or true
true

nix-repl> { x = false; }.y or false
false
```
while the logic `||` yields:
```
nix-repl> { x = false; }.y || true
error: attribute ‘y’ missing, at (string):1:1

nix-repl> { x = false; }.y || false
error: attribute ‘y’ missing, at (string):1:1
```

The proposal was only to remove it to test the patch locally and fix the patch. Of cource you should not commit the _removed_ `optional` :wink:

**Comment by winksaville** [comment]
@groxxda, I think I understand `or`, I see from [here](https://nixos.org/nix/manual/#idm140737318164656) its a set operator that defines a default if the Set on the LHS yields an "empty" result or an "error", please correct me if I'm wrong.

@LnL7 please test and let me know if you'd like me to do anything else or if it needs a more sophisticated change I can certainly close this pull request and a proper one can be supplied.

**Comment by LnL7** [comment]
@winksaville The patch is no longer needed for this version as far as I can tell, you can remove the `python_framework.patch` file and the `patches` attribute.

**Comment by winksaville** [comment]
OK

**Comment by winksaville** [comment]
@LnL7 I've updated the pull request to remove python_framework.patch.

If a user 'manually' changed `version` to 7.4.826 or some other earlier version, would vim no longer 'work' on darwin? If so should we instead conditionally apply python_framework.patch?

**Comment by LnL7** [comment]
While you indeed can override the version, this is not something we account for in nixpkgs.
In some cases we do keep multiple versions around, but only if there's a reason for that.

**Pull request merged**
