### PR TITLE
[backport release-20.09] ghcjs 8.10.7: init

### PR DESCRIPTION
**Pull request by dfordivam**
###### Motivation for this change
Backporting the changes added in https://github.com/NixOS/nixpkgs/pull/137066

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by Ericson2314 — CHANGES_REQUESTED** [review]
We discussed making this keep the old GHCJS completely in place.

**Comment by dfordivam** [comment]
On 20.09 the builds are completely broken, but I agree that changing the old behavior should not happen with the backport of the ghcjs 8.10.

```
src/GhcUtil.hs:15:1: error:
    Could not find module ‘MonadUtils’
    Use -v to see a list of the files searched for.
   |
15 | import           MonadUtils (liftIO)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
checking for ANSI C header files... yes

builder for '/nix/store/55i5cahi8h92zv6901bm05pgldhp9bf1-doctest-0.16.3.drv' failed with exit code 1
cannot build derivation '/nix/store/7jacjc0q237brm1qa4l918i5l9jaa088-comonad-5.0.6.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/43606h1fwcm1ghk0mz9acj4fvih55556-bifunctors-5.5.7.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/7byvdkgcg0qj7rid54d3m768j3305i6b-assoc-1.0.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/ygfhn4bdbhyynafz8f4ydiin1mmz4jsq-these-1.1.1.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/yzs6gnzibn9rb2b8f9nbfzcdy7d9blay-quickcheck-instances-0.3.23.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/nl6fwjlf0wpv2wk4m6x78x82grh5s8b0-aeson-1.4.7.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/58kxwwdij4hby0fhdbw7rzc051ffb6y8-ghcjs-base-0.2.0.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/58kxwwdij4hby0fhdbw7rzc051ffb6y8-ghcjs-base-0.2.0.0.drv' failed
```

**Comment by SuperSandro2000** [comment]
Isn't 20.09 EOL? There was nothing pushed to it in over 2 months except some ghc stuff.

**Comment by Ericson2314** [comment]
@SuperSandro2000 Upgrading Nixpkgs is never easy when one is doing a bunch of obscure haskell cross compilation. In fact, it's proved quite absurdly difficult. We therefore try to do very incremental updates. Of course, we want to share our work with others, too.

**Comment by SuperSandro2000** [comment]
> Of course, we want to share our work with others, too.

Yeah sure but 20.09 is pretty dead and we already do not have enough resources to backport all necessary backports to 21.05. We can't maintain two stable releases longer than the one month grace period after a new release. I don't want that the impression is created 20.09 is still supported and we accept PRs for it.

**Comment by Ericson2314** [comment]
Surely there is some way we can make clear this is a one-off itch-scratching backport and not any sort of systematic maintainence?

**Comment by SuperSandro2000** [comment]
Maybe it is already enough if we agree on this in this discussion and make this a one time thing for ghcjs.

**Comment by Ericson2314** [comment]
Sounds good. Thank you!

**Pull request merged**
