### PR TITLE
devpi-server: 4.3.1 -> 4.4.0

### PR DESCRIPTION
**Pull request by nlewo**
We also disable 3 tests because they are failing with pytest 3.4.0. 
I don't why they are failing since we switch to pytest 3.4.0 but if I rollback pytest to 3.3.2, tests are ok.

###### Motivation for this change
Fix the build failure 
https://hydra.nixos.org/build/68801588#tabs-summary

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by nlewo** [comment]
cc @makefu

**Comment by nlewo** [comment]
@GrahamcOfBorg build devpi-server

**Review by makefu — APPROVED** [review]
Tested executable, looks good!

**Comment by davidak** [comment]
Build fails on debian 9 and OS X 10.10.5: https://pastebin.com/W8PThrrv

**Comment by nlewo** [comment]
Thanks @davidak !
@GrahamcOfBorg build devpi-client

**Comment by Mic92** [comment]
@GrahamcOfBorg build devpi-server

**Comment by Mic92** [comment]
I think the tests fail because 404, the number, does not longer match `<Response [404]>`, the object.
These are minor bugs, I would disable those tests using `pytest -k` option (see nixpkgs for examples) and report those upstream.

**Comment by nlewo** [comment]
I've tryied to upgrade devpi-client but it fails on more tests. Since my initial objective was to fix devpi-server, I didn't try hard to upgrade the client...

@GrahamcOfBorg build devpi-client

**Comment by nlewo** [comment]
@GrahamcOfBorg build devpi-client devpi-server

**Pull request merged**
