### PR TITLE
mstflint: 4.17.0-1 -> 4.25.0-1

### PR DESCRIPTION
**Pull request by pinpox**
Diff: https://github.com/Mellanox/mstflint/compare/None...v4.25.0-1

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Result of `nixpkgs-review pr 250967` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>mstflint</li>
  </ul>
</details>

**Comment by pinpox** [comment]
> Result of `nixpkgs-review pr 250967` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
> 1 package failed to build:

This is the relevant part of the error as far as I can tell. I havevn't been able to figure out why the file is missing, it present in the source of the uptream here: https://github.com/Mellanox/mstflint/blob/f279c4ce5665a02d4410fa75c698b7c35d427617/tools_layouts/cibfw_layouts.h

Any ideas how to fix this?

```
mstflint> fs3_ops.h:38:10: fatal error: cibfw_layouts.h: No such file or directory
mstflint>    38 | #include <cibfw_layouts.h>
mstflint>       |          ^~~~~~~~~~~~~~~~~
mstflint> compilation terminated.
mstflint> make[3]: *** [Makefile:536: bluefiled_signature_manager.o] Error 1
mstflint> make[3]: Leaving directory '/build/source/mlxfwops/lib'
mstflint> make[2]: *** [Makefile:421: all-recursive] Error 1
mstflint> make[2]: Leaving directory '/build/source/mlxfwops'
mstflint> make[1]: *** [Makefile:558: all-recursive] Error 1
mstflint> make[1]: Leaving directory '/build/source'
mstflint> make: *** [Makefile:443: all] Error 2
error: builder for '/nix/store/b2vg88rsf265zm6c0vifnp8522fh2r6z-mstflint-4.25.0-1.drv' failed with exit code 2;
       last 10 log lines:
       >    38 | #include <cibfw_layouts.h>
       >       |          ^~~~~~~~~~~~~~~~~
       > compilation terminated.
       > make[3]: *** [Makefile:536: bluefiled_signature_manager.o] Error 1
       > make[3]: Leaving directory '/build/source/mlxfwops/lib'
       > make[2]: *** [Makefile:421: all-recursive] Error 1
       > make[2]: Leaving directory '/build/source/mlxfwops'
       > make[1]: *** [Makefile:558: all-recursive] Error 1
       > make[1]: Leaving directory '/build/source'
       > make: *** [Makefile:443: all] Error 2
       For full logs, run 'nix log /nix/store/b2vg88rsf265zm6c0vifnp8522fh2r6z-mstflint-4.25.0-1.drv'.
```

**Comment by thillux** [comment]
FYI: #263149 should fix your build issue.

**Comment by thillux** [comment]
You may close at your discretion.

**Comment by wegank** [comment]
Superseded by #263149.

**Pull request closed without merging**
