### PR TITLE
nixos/xfce: add environment.xfce.excludePackages option

### PR DESCRIPTION
**Pull request by pjstadig**
Packages in environment.xfce.excludePackages will be excluded from the default environment.

There are analogous options for gnome, cinnamon, lxqt, etc.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by pjstadig** [comment]
@bobby285271 @romildo @muscaln

**Comment by bobby285271** [comment]
I am fine for this, did not test. (in https://github.com/NixOS/nixpkgs/pull/175620#discussion_r886978461 I was suggested core packages shouldn't be removed but I am not really sure what should be "core" here since people use e.g. random WMs and panels to replace the Xfce's :upside_down_face:)

Specifically, do you think `xfce4-notifyd` can be excluded? If so, since it is in both `environment.systemPackages` and `systemd.packages` shall we exclude it in both places?

**Comment by pjstadig** [comment]
Good question!

XFCE is more modular than most desktops, which makes it good for use with a different window manager, which is I'm doing, but the line that is causing me problems is this https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/desktop-managers/xfce.nix#L117

I have `noDesktop` set to true, but I am also installing `xfce4-panel` and `xfce4-pulseaudio-plugin`, but the module is also installing `xfce4-volumed-pulse`. I was on the fence about adding a change to split `noDesktop` into `enablePanel` and `enableXfdesktop` or something, so I could turn off `xfdesktop` and keep `xfce4-panel`.

I'm happy to put up a PR for that. I'm also happy to add the exclusion to `systemd.packages` (which I think makes sense), or I could do both!

**Comment by bobby285271** [comment]
LGTM

> split noDesktop into enablePanel and enableXfdesktop

Personally I prefer not introducing new options when excludePackages can do the job :thinking:

**Pull request merged**
