### PR TITLE
[WIP] NixOS integration of nixpart

### PR DESCRIPTION
**Pull request by aszlig**
## WIP branch of upcoming `nixpart` integration into NixOS

Storage configuration is done like this:

https://github.com/aszlig/nixpart/wiki/Device-tree-representation

Todo list until the first merge to master:

 * [x] Fully package latest blivet release.
 * [x] Fix up NixOS tests of blivet.
 * [x] Rewrite [nixpart](https://github.com/aszlig/nixpart) with new blivet API.
 * [x] Support disk device matchers in nixpart.
 * [x] Support mounting in nixpart.
 * [ ] Refactor building the device tree.
 * [ ] (Re)write NixOS storage tests.
 * [ ] Mark `storage.*` options experimental.
 * [ ] Add an experimental NixOS installer CD with nixpart.
 * [ ] Write thorough documentation with examples on how to use this for installing NixOS.

This is part 1 of 2 of #2079 (`nixos-assimilate`).

Test jobset: https://headcounter.org/hydra/jobset/aszlig/nixpart

### CODE REVIEW

**Comment by grahamc** [comment]
These sorts of features being part of NixOS modules itself spook me, and they may or may not be well founded fears. I worry about turning a safe operation (nixos-rebuild build / switch) in to one which can cause data loss (can this cause data loss?). I wonder about how changes in the specification are applied, and what support is there for rolling back.

**Comment by aszlig** [comment]
@grahamc: This can't cause data loss, because it's not going to be part of `nixos-rebuild` - at least not in the first place. If we want to make it available later for `nixos-rebuild`, I'd really make sure it's only used if you do something like `nixos-rebuild --yes-i-want-to-change-partitioning ...` or something like that.

But as said, for now, this is only for `nixos-install`.

**Comment by grahamc** [comment]
> But as said, for now, this is only for `nixos-install`.

I see, sorry, I misunderstood. Are there other parts of the
configuration.nix that don't have an effect when rebuilding?

**Comment by aszlig** [comment]
That's only the `storage.*` options and the hooks to it (`fileSystems.*.storage` and `swapDevices.*.storage`), nothing more.

**Comment by aszlig** [comment]
Okay, I've hit a roadblock right now, getting the storage configuration deterministic.

Storage configuration currently looks like this:

```nix
{
  storage.disk.foo.match.physicalPos = 1;

  storage.partition.part1 = {
    size.mib = 500;
    targetDevice = "disk.foo";
  };
  storage.partition.part2 = {
    size = "fill";
    targetDevice = "disk.foo";
  };

  fileSystems."/boot" = {
    fsType = "vfat";
    storage = "partition.part2";
  };
  fileSystems."/" = {
    fsType = "ext4";
    storage = "partition.part2";
  };
}
```

This matches the first physical disk enumerated by the kernel during partitioning and creates two partitions, the first (`part1`) with 500 MiB and the second (`part2') fills up the rest of the disk. Note that the matcher here is the crux of this whole problem: Once we're done partitioning, the match on the first physical might no longer apply and might likely be a different disk.

The way to achieve determinism (config-wise) is that whenever we match a device we first check whether partitioning has already done (which is the tricky part here) and if not, we run the actual matcher (in this case it's `physicalPos`) and continue walking the device tree. Every storage option tuple (`disk.foo`, `partiton.part1`, ...) is a so-called `device specification` (or shortly `devspec`) which designates a particular node in the device tree. The tree is built by referencing devspecs in `targetDevice(s)` or `storage` (within `fileSystems` and `swapDevices`).

Result: Whether you use the above for partitioning a system or for booting a system shouldn't make a difference.

My initial take on this was to hash every devspec with SHA-1, truncate it to 128 bit UUID length and use it for every filesystem. The problem however is that file system UUIDs are not generally supported the same way by all file systems. Some do not seem to have a form of UUID at all and others use different identifier variant, like for example vfat (it's a 32bit volume identifier).

Even if we could force some kind of UUIDs to be used among all file systems, we still have to go great lengths to identify the root device of the underlying file system (for example if you have several nested containers such as LUKS or LVM) so that we go down the `storage.*` specification and recurse up towards the root device until we find a valid UUID.

Another idea that would solve this is to punch a hole into the root device (like for example at the end), fill it with the devspec info and leave it unpartitioned/unused. Unfortunately say if you want to use a full disk as one big file system without a disk label, we enter a dangerous area except if we use mappers. The dangerous area is that while most file systems have a pretty good understanding about their own boundaries, there might be file systems or other container types out there which either try to always use the full device boundaries, can't even created with specific boundaries or might even do something completely unexpected.

A way to circumvent this is to put the devspec info only the devices where it's easily possible to add holes.

Nevertheless, the biggest downside of this is that people might notice that fdisk & friends show unpartitioned areas which might be confusing, so *if* we go that route we need to not only note about this in the documentation but also show this notice during partitioning just to be sure :-)

Of course, there is another option, which is not making it deterministic *at all* and use `nixpart` as an intermediate state similar to `nixos-generate-config`. However, I'd like to avoid this, because it makes it difficult to detect changes and also complicates remote deployments (instead of just copy-closure, we'd need to issue nixpart, fetch new config and then rebuild). We already had this so far in nixpart 0.x and while it works reasonably well for the Hetzner backend, it complicates things a lot (we need to evaluate twice and keep the extra config for the physical spec in the machine's state db).

The last thing that comes to my mind would be to force the user to set labels everywhere. We could autogenerate them, but with fs labels we have the same issues as with the UUID approach and things look even more grim, because not only does the length limit differ, the file systems also have different rules about which characters are allowed.

So is the way I'm approaching this too complicated and am I missing something obvious? Ideas and comments greatly appreciated.

**Comment by Mic92** [comment]
Do we have prior art in automatic partitioning? Are all partition frameworks like ignition, kickstart, partman or cloud-init stateful (only run once)?

**Comment by aszlig** [comment]
They're using a dummy disk UUID _before_ partitioning. However this only works if we only have _one_ OS and we would also need to pre-seed the devices. So unfortunately ignition is not deterministic in the way I've described.

**Comment by offlinehacker** [comment]
> The way to achieve determinism (config-wise) is that whenever we match a device we first check whether partitioning has already happened (which is the tricky part here)

If we know what filesystem should be on particular partition, can't we actually check if it is(blkid -o value -s TYPE /dev/block/device), and format if no filesystem is found? While this requires for partitions to be formated, labes or uuids could be used in rare cases where no filesystem is on partition.

One other idea is to put devspec to some system path(/boot), so everytime devspec would be changed and applied old devspec partition information would be taken into account.

**Comment by aszlig** [comment]
@offlinehacker wrote:
> If we know what filesystem should be on particular partition, can't we actually check if it is(blkid -o value -s TYPE /dev/block/device), and format if no filesystem is found?

This is exactly the problem here: We *do* know that a particular file system should be on a particular partition, but we don't know whether the device is the one we really want.

Right now we have different matcher implementations to search for the right set of devices. These matchers however rely on the *initial* state.

So let's say the initial situation is like this with `/dev/sda` and `/dev/sdb` being internal disks and `/dev/sdc` being an USB drive:

partitions | /dev/sda | /dev/sdb | /dev/sdc
-------------|-------------|-------------|-------------
partition 1 | NTFS | unpartitioned | ext4
partition 2 | unpartitioned | unpartitioned | XFS

So we want to only partition `/dev/sda` and `/dev/sdb` with the following storage configuration:

```nix
{
  storage.disk.sda = {};
  storage.disk.sdb = {};
  storage.partition.root.size = "fill";
  storage.partition.root.targetDevice = "disk.sda";
  storage.partition.data.size = "fill";
  storage.partition.data.targetDevice = "disk.sdb";
  btrfs.data.devices = [ "partition.data" ];

  fileSystems."/" = { storage = "partition.root"; fsType = "xfs"; };
  fileSystems."/data" = { storage = "btrfs.data"; fsType = "btrfs"; };
}
```

The resulting partition layout will be:

partitions | /dev/sda | /dev/sdb | /dev/sdc
-------------|-------------|-------------|-------------
partition 1 | NTFS | btrfs (data) | ext4
partition 2 | XFS (root) | | XFS

So let's say after reboot the whole layout looks like this:

partitions | /dev/sda | /dev/sdb | /dev/sdc | /dev/sdd
-------------|-------------|-------------|-------------|-------------
partition 1 | unpartitioned | btrfs | NTFS | btrfs (data)
partition 2 | | | XFS | XFS (root) |

In this case `/dev/sdc` is the same as `/dev/sda` from before and `/dev/sdd` is `/dev/sdb` from before and we now have two more disks which are now enumerated before the disks we had earlier.

With the above storage config run again we now have:

partitions | /dev/sda | /dev/sdb | /dev/sdc | /dev/sdd
-------------|-------------|-------------|-------------|-------------
partition 1 | XFS (root) | btrfs (data) | NTFS | btrfs (data)
partition 2 | | | XFS | XFS (root) |

This is clearly something we do *not* want to end up with and it gets even more dangerous if we "autoformat" in case something is missing.

@offlinehacker wrote:
> While this requires for partitions to be formated, labes or uuids could be used in rare cases where no filesystem is on partition.

If there is no file system, you don't have a UUID or label on a DOS disklabel.

@offlinehacker wrote:
> One other idea is to put devspec to some system path(/boot), so everytime devspec would be changed and applied old devspec partition information would be taken into account.

That makes more sense, especially because we can shovel more than just a UUID into such a partition. We had a discussion about this in IRC a few days ago where one similar idea was to put the information into the pre-boot gap usually used by GRUB.

However, this assumes the common case where there actually *is* a boot partition or a pre-boot gap. Unfortunately this won't work If you want to write a file system on a device without partitioning at all.

**Comment by aszlig** [comment]
Btw.: Right now I'm heading for a hybrid approach using UUIDs to store devspec info hash and if it is possible using other means like the mentioned suggestions. We can still bail out with an error in nixpart if there is no way to put information anywhere and suggest the user to use labels or rearrange the storage layout.

**Comment by offlinehacker** [comment]
@aszlig thanks for the explanation, i understand problem better now and solution with infohash uuids seems really clever, and covers majority of use cases.

**Comment by copumpkin** [comment]
Watching 😄

**Comment by cleverca22** [comment]
and what about luks and lvm?, which can be nested in either order

for reference, here is how i automate most of my installs:
https://github.com/cleverca22/nix-tests/blob/master/kexec/justdoit.nix#L36
it either
* creates a boot, zfs, and swap partition
* or creates a boot, and luks partition, then uses lvm on the luks to create a zfs and swap LV
boot and swap are of a fixed size, and the zfs takes up the rest

ive also got an unfinished installer project with an older example at https://github.com/cleverca22/nixos-installer/blob/master/installer/gui/bootconfig.cpp#L155
the critical problem i ran into there, is that libparted didnt have any way to get the partition uuid of the partitions it just created, even though it was in full control of creating the uuid's, the api just didnt expose it, which lead to issues correctly identifying the device i need to format

**Comment by rvolosatovs** [comment]
What's the status of this PR?

**Comment by aszlig** [comment]
@rvolosatovs: I still intend to rebase and put this forward within the next two months if possible.

**Comment by bobvanderlinden** [comment]
I really like the idea of being able to define a partition table in Nix. However, this PR is quite huge and hard to get up-to-date. Overwhelming to for me (and probably others) to help out.

Could we somehow split this PR up?

Introducing packages can already be done. Would it make sense to have PRs for:

* `mpathconf`
* `pocketlint`
* `libbytesize`
* `volume_key`
* `libblockdev`

There are also quite a few patches in here. Would it make sense to propose those upstream already? In particular:

* `blivet`
* `libblockdevice`
* `parted`

We can then introduce `nixpart` as a separate package. Then introduce the NixOS options with tests.

If you think it's a good idea, defining which steps can be taken would be a good idea. After that it's easier to delegate where there is lack of time.

**Comment by aszlig** [comment]
@bobvanderlinden: I think most of the dependencies should already be in nixpkgs, so only the most direct dependencies should be left after a rebase. Also, most of the patches should already be applied upstream.

The main hurdles I had previously, were with `blivet` itself and while the upstream project has a comprehensive test suite, they apparently didn't run it and tests were failing even on release versions on their side. However, this should have changed and they should now actually run the test suite on their side, which makes it easier for us to distinguish whether a test failure is our fault.

Sorry for not getting to that earlier, I'll try to do a rebase and check whether things got better before May the 5th 2019. If not I'll report back here.

**Comment by aszlig** [comment]
@bobvanderlinden: Okay, after giving this a try in rebasing, I found out that a lot has changed for blivet and related packages, so doing the rebase properly needs a lot more time to do, which I currently do not have :-/

So from the packages that were added here which are not yet part of nixpkgs, only `mpathconf` and `pocketlint` are missing, so adding them in separate pull requests would probably be a good idea.

Also, speaking of separating these things, I also made VM tests of `blivet` and `libblockdev` (which in turn need a few package changes), which would also make sense to do in separate pull requests as well.

Particularly if we could get `nixos/tests/blivet.nix` separated (and also updated to version 3.1.3) from this pull request and possibly merged, this would already by a huge step and would help a lot in bringing `nixpart` forward. If someone has time to work on the latter, that would be great :-)

**Comment by aszlig** [comment]
still important to me

**Comment by Mic92** [comment]
systemd now also has a partition manager by the way.

**Comment by davidak** [comment]
@Mic92 do you have a link to it?

**Comment by Mic92** [comment]
There is https://www.freedesktop.org/software/systemd/man/repart.d.html and https://www.freedesktop.org/software/systemd/man/systemd-makefs@.service.html

**Comment by kisik21** [comment]
The systemd-repart feature seems to be more intended to repartition the disk containing a base image more than partition an empty disk from an installer.

**Comment by Mic92** [comment]
This looks like it is stalled to me. Please open a new PR.

**Pull request closed without merging**
