### PR TITLE
nixos/mysql: remove fixed timeout and use notify service type

### PR DESCRIPTION
**Pull request by Princemachiavelli**
## Description of changes
Removes the hard coded 30 second startup timeout in `postStart` since systemd's `TimeoutStartSec` is a suitable and more flexible alternative. The 30 second timeout also not long enough for large databases where innodb initialization can often take >1min.

The systemd service type itself is changed to "notify" for MySQL >= 8.0 [1]. This means none of the MySQL/MariaDB versions in nixpkgs use the "simple" service type and therefore don't even need the manual loop/polling for the socket. However, there may be other MySQL implementations added to nixpkgs in the future (MyRocks, etc.) that may be based on MySQL < 8.0 and require the "simple" service type.

[1] https://dev.mysql.com/doc/refman/8.0/en/using-systemd.html

## Things done
The `mysql` test for `mysql80` and `mariadb` both pass. I've confirmed that systemd's `TimeoutStartSec` setting applies to both the `ExecStart` and `ExecStartPost` scripts.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by ajs124 — APPROVED** [review]
diff LGTM. haven't tested though.

**Comment by aanderse** [comment]
does anyone here have a database that takes longer than a second to start up that can test this?

this looks fine but it would be really nice if we could practically test this

if not... i guess we merge and rely on logic

**Comment by Princemachiavelli** [comment]
@aanderse My synthetic testing method was to add a `sleep 30` to the beginning of the `ExecStart` script to test that the `ExecStartPost` script is also postponed an additional 30 seconds. Technically, this doesn't test that MySQL itself waits to send the systemd `READY=1` status until after the socket is available - just going by upstream docs and observed behavior.

Here's the log of the `mysql` test with the 30 second delay but without sub-second resolution it's hard to confirm:
```
Feb 15 08:19:23 mariadb80 mysql-pre-start[861]: 2024-02-15T08:19:23.122910Z 0 [System] [MY-013169] [Server] /nix/store/vwcld5bqs1dg7h2ffcgz8am4vdrxw176-mysql-8.0.36/bin/mysqld (mysqld 8.0.36) initializing of server in progress as process 861
Feb 15 08:19:23 mariadb80 mysql-pre-start[861]: 2024-02-15T08:19:23.155992Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
Feb 15 08:19:23 mariadb80 mysql-pre-start[861]: 2024-02-15T08:19:23.756727Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
Feb 15 08:19:24 mariadb80 mysql-pre-start[861]: 2024-02-15T08:19:24.149674Z 0 [Warning] [MY-013501] [Server] Ignoring --plugin-load[_add] list as the server is running with --initialize(-insecure).
Feb 15 08:19:25 mariadb80 mysql-pre-start[861]: 2024-02-15T08:19:25.123350Z 6 [Warning] [MY-010453] [Server] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
Feb 15 08:19:27 mariadb80 mysql-start[988]: MySQL delay start...
Feb 15 08:19:57 mariadb80 mysql-start[988]: MySQL delay end...
Feb 15 08:19:57 mariadb80 mysql-start[988]: 2024-02-15T08:19:57.716130Z 0 [System] [MY-010116] [Server] /nix/store/vwcld5bqs1dg7h2ffcgz8am4vdrxw176-mysql-8.0.36/bin/mysqld (mysqld 8.0.36) starting as process 988
Feb 15 08:19:57 mariadb80 mysql-start[988]: 2024-02-15T08:19:57.732427Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
Feb 15 08:19:58 mariadb80 mysql-start[988]: 2024-02-15T08:19:58.121585Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
Feb 15 08:19:58 mariadb80 mysql-start[988]: 2024-02-15T08:19:58.453086Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
Feb 15 08:19:58 mariadb80 mysql-start[988]: 2024-02-15T08:19:58.454453Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
Feb 15 08:19:58 mariadb80 mysql-start[988]: 2024-02-15T08:19:58.478320Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /run/mysqld/mysqlx.sock
Feb 15 08:19:58 mariadb80 mysql-start[988]: 2024-02-15T08:19:58.479943Z 0 [System] [MY-010931] [Server] /nix/store/vwcld5bqs1dg7h2ffcgz8am4vdrxw176-mysql-8.0.36/bin/mysqld: ready for connections. Version: '8.0.36'  socket: '/run/mysqld/mysqld.sock'  port: 3306  Source distribution.
Feb 15 08:19:58 mariadb80 mysql-post-start[1162]: Creating initial database: testdb3
```

**Comment by Nhasty** [comment]
This worked for me on a large database that was not starting before the post start script caused the service to restart.

**Review by aanderse — APPROVED** [review]
great! thanks team

let's go ahead and merge

**Pull request merged**
