### PR TITLE
flac: build with cmake, fixes cross compilation

### PR DESCRIPTION
**Pull request by NickCao**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NickCao** [comment]
Built `flac` and `gst_all_1.gst-plugins-good` on `x86_64-linux` and `riscv64-linux (cross)`, not feasible to run nixpkgs-review though.

**Review by ck3d — APPROVED** [review]
LGTM

**Review by ruuda — CHANGES_REQUESTED** [review]
The new binary performs noticeably worse. I suspect it ends up passing different optimization flags to the compiler in the end? Could you look into this?

```
Benchmark 1: result-bin-before/bin/flac -t album/*.flac
  Time (mean ± σ):      5.037 s ±  0.113 s    [User: 4.834 s, System: 0.120 s]
  Range (min … max):    4.955 s …  5.282 s    10 runs
 
Benchmark 2: result-bin-cmake/bin/flac -t album/*.flac
  Time (mean ± σ):      5.307 s ±  0.040 s    [User: 5.072 s, System: 0.136 s]
  Range (min … max):    5.257 s …  5.381 s    10 runs
 
Summary
  'result-bin-before/bin/flac -t album/*.flac' ran
    1.05 ± 0.03 times faster than 'result-bin-cmake/bin/flac -t album/*.flac'
```

**Comment by ck3d** [comment]
Good catch!

According to the project documentation, autotools and cmake should be equivalent:
https://github.com/xiph/flac/blob/master/README.md?plain=1#L87

The autotools used following configuration:
```
  Configuration summary :

    FLAC version : ............................ 1.4.1

    Host CPU : ................................ x86_64
    Host Vendor : ............................. pc
    Host OS : ................................. linux-gnu


    Compiler is GCC : ......................... yes
    GCC version : ............................. 11.3.0
    Compiler is Clang : ....................... no
    SSE optimizations : ....................... yes
    Neon optimizations : ...................... no
    Asm optimizations : ....................... yes
    Ogg/FLAC support : ........................ yes
    Stack protector  : ........................ yes
    Fuzzing support (Clang only) : ............ no
```

When building with cmake, no configuration summary is available.
It could be that some optimizations are not activated.

I think this is an upstream issue.

**Comment by NickCao** [comment]
https://github.com/xiph/flac/blob/2440e19a733f045e50cd7f3dbd706b9ed98fc5ef/configure.ac#L508 sets `-O3`, while it's missing from the cmake build system.

**Comment by ruuda** [comment]
Hmm, even with b8a03cec225e78bb112c66836fc85720801cb377, there is a significant difference ... the binary is about 3% larger, and when I measure a `perf stat` of `flac --test`, it executes about 8% more instructions. (Using instructions now instead of wall time because it is more stable, in wall time, the old version is 1.05 ± 0.02 times faster on my machine.)

Is there an easy way to trace the compiler invocations, so we can see which flags get passed?

**Comment by ruuda** [comment]
I am a fool, I was comparing the current PR to master, which still has flac 1.3.4..., the regression is an upstream one, unrelated to this PR. I now no longer find a difference between the two:

```
Benchmark 1: result-bin-cmake/bin/flac -t album/*.flac
  Time (mean ± σ):      4.854 s ±  0.140 s    [User: 4.753 s, System: 0.096 s]
  Range (min … max):    4.702 s …  5.111 s    10 runs
 
Benchmark 2: result-bin-before/bin/flac -t album/*.flac
  Time (mean ± σ):      4.912 s ±  0.078 s    [User: 4.815 s, System: 0.091 s]
  Range (min … max):    4.783 s …  4.991 s    10 runs
 
Summary
  'result-bin-cmake/bin/flac -t album/*.flac' ran
    1.01 ± 0.03 times faster than 'result-bin-before/bin/flac -t album/*.flac'
```

**Review by ruuda — APPROVED** [review]

**Comment by ck3d** [comment]
No problem :)

**Comment by Mindavi** [comment]
I was just preparing a PR and got a merge conflict, thanks for already fixing this! My solution was worse (using `configure` script patches that already landed upstream).

**Pull request merged**
