### PR TITLE
nixos/doc: convert 21.05 release notes to CommonMark

### PR DESCRIPTION
**Pull request by blaggacao**

### CODE REVIEW

**Comment by ryantm** [comment]
Since people are still editing the 21.05 release notes when doing backports, we should backport this conversion. Warning: this may mess up existing release note changes people have made but not merged yet. Our only other alternative is to wait until 2022 to convert this section of the manual, which I think is too long to wait.

**Review by ryantm — APPROVED** [review]

**Comment by ryantm** [comment]
@GrahamcOfBorg eval

**Review by ryantm — CHANGES_REQUESTED** [review]
There's an issue with the indentation of a few code blocks:

image

**Comment by blaggacao** [comment]
@ryantm fixed in [force-push](https://github.com/NixOS/nixpkgs/compare/017f0ff937ad18f356ab8bf4291dd92660e8d0c4..32c2dd304d5e1b2a48a0772f906d0cc86332992e). Thanks!

**Comment by blaggacao** [comment]
@GrahamcOfBorg eval

**Review by ryantm — APPROVED** [review]

**Pull request merged**
