### PR TITLE
qemu: 6.2.0 -> 7.0.0

### PR DESCRIPTION
**Pull request by alyssais**
###### Description of changes

- [ChangeLog](https://wiki.qemu.org/ChangeLog/7.0)
- [QEMU Planning Doc](https://wiki.qemu.org/Planning/7.0)

**7.0.0 is scheduled to be released on 2022-04-12 or 2022-04-19.**

Starting now, at the beginning of the release process, so we can identify any issues early.  The main one I see so far is that fixing the Darwin build is no longer as simple as reverting one patch that adds clipboard support, because loads of work has happened on clipboard stuff in QEMU in the meantime.  (The underlying problem here is that we're stuck on a ancient Darwin SDK, which isn't supported by upstream.)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
Am I right in thinking we could skip the patch on darwin-aarch64 to enable it there though?

**Comment by alyssais** [comment]
> Am I right in thinking we could skip the patch on darwin-aarch64 to enable it there though?

It's on a newer SDK, right?  I suppose so.

**Comment by willcohen** [comment]
I'm intel-only, so I defer to you all re M1 testing...

The `utimensat` patch shouldn't hurt anything, so I don't think there's a problem with leaving that in in general. Is the overall plan to just `fetchpatch, revert` all the new clipboard and incompatible macOS stuff until it builds?

**Comment by alyssais** [comment]
> The `utimensat` patch shouldn't hurt anything, so I don't think there's a problem with leaving that in

Agreed.

> Is the overall plan to just `fetchpatch, revert` all the new clipboard and incompatible macOS stuff until it builds?

I don't have a plan, which is why I've been trying to get attention to this PR.  i'd rather not revert that many commits because lots of them touch code that's shared with Linux, so we'd have to do it conditionally on platform, which makes my job as maintainer harder.  And there are _loads_ of them, so I don't think it's sustainable to revert 10 commits on macOS this release, 20 next release, and so on.

So I think what we need is for an x86_64-darwin user to come up with a patch that makes it build, either by using older APIs, deleting Darwin-specific clipboard code, or updating the macOS SDK.

**Comment by risicle** [comment]
This builds for me on darwin aarch64 if the guest agent related parts are disabled (`--enable-guest-agent` and the installation of `qemu-ga`)

**Comment by willcohen** [comment]
Got it. Looks like the simplest plan will be to just delete the clipboard support -- the commit doesn't seem to revert very cleanly once we hit 7.0-rc. I'll try to get a patch taking that out in the next few days.

**Comment by alyssais** [comment]
@risicle I've disabled building the guest agent on unsupported platforms. :)

**Comment by willcohen** [comment]
@alyssais I haven't yet finished the rebuild purely with`nix-build`, but manually building with `./configure` and `make` in the environment coming from `nix-build $NIXPKGS --run-env -A qemu` works with the following patches: https://github.com/willcohen/nixpkgs/commit/1e94307c0a4dc3034536a8eabb2e7dfd6fe1822d. Feel free to squash or adjust into this PR as needed (and I'll follow up with confirmation that nix-build fully works on that revision).

Summary: there's only two commits at issue. The clipboard one from before has been reworked into a `.patch` since it no longer cleanly reverts, but there's one more about the adjusted about panel that still reverts cleanly, so I figured it's okay to leave it in as `fetchpatch`. Let me know if you'd like that in a patch before, as discussed above when more reversions seemed to be at play.

**Comment by willcohen** [comment]
@alyssais while qemu builds using the commit shown above, trying to actually run a known working image with a `q35` machine results in the following error, so my changes should not yet be considered a complete fix for darwin:

```
$ ./start-nixos.sh            
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]
Assertion failed: (qemu_in_main_thread()), function blk_all_next, file ../block/block-backend.c, line 552.
```

**Comment by willcohen** [comment]
As followup — once the solution lands (https://lists.gnu.org/archive/html/qemu-devel/2022-03/msg06694.html) we can use that in this branch for testing until it gets incorporated into the next rc.

**Review by willcohen — APPROVED** [review]

**Comment by alyssais** [comment]
@willcohen thanks so much for all your work!

**Comment by alyssais** [comment]
> Of course! Also, just keeping you in the loop @alyssais, the followup bugfix for 9p is in a maintainer tree and looks like it should be getting merged before rc3

Ah yeah, I'd been following that on the list (thanks for CCing me :)).

**Comment by willcohen** [comment]
Can confirm that `rc3` works on mac. 

Slightly outside the scope of this @alyssais, I am extremely appreciative for all of your work keeping this derivation working so well. I was just able to get a reasonably-performant NixOS VM running on a Windows 11 work machine via QEMU sourced from a WSL installation of nix on debian (I know that's turtles all the way down, but doing it through WSL is somehow a lot more familiar for a mac/linux user than trying to install QEMU natively on Windows and deal with all the options that way). (The most complicated part was recompiling the WSL kernel to enable KVM: https://boxofcables.dev/kvm-optimized-custom-kernel-wsl2-2022/)

The ability to then mount volumes there and on an equivalent image on macOS through 9p provides a pretty good experience for having a clean path to NixOS on Windows/Mac without too many compromises.

**Comment by alyssais** [comment]
> I am extremely appreciative for all of your work keeping this derivation working so well.

@willcohen, I'm extremely appreciative of all your work keeping it working (and making it better!) on Darwin, which has always been the most frustrating part for me! :)

**Comment by alyssais** [comment]
@ofborg test simple cage cagebreak cloud-init os-prober sway virtualbox

**Comment by alyssais** [comment]
Tests look fine — I think os-prober failed because of that debian keyutils download failure we've seen elsewhere?  So assuming 7.0 is released later today with no/few changes I plan to update the PR to that and merge after a quick smoke test.

**Pull request merged**
