### PR TITLE
WIP: Fetch sources

### PR DESCRIPTION
**Pull request by zimbatm**
###### Motivation for this change

This is a revival of #19582 but simplified to try to simplify the package update scenario.

The PR also contains an example script adapted from @layus' idea to demonstrate why fetchSource could be nice.

The idea is that you would run `nix edit nixpkgs.hello`, update the version or whatever. Then `nix-update-src hello` to prefetch-url and replace the sha256 directly. This could be combined in a nix-edit, update, build loop further down the road.

At this point I am looking for feedback on the idea and naming.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
I like the idea. The script should probably be located in `maintainer/scripts`, and perhaps it would be good to put a comment in places that fetchSource is used to remind people the script is there / how to use it.

**Comment by Mic92** [comment]
There is a different package called: `common-updater` in nixpkgs. I think we should only have one of the two in our repo.

**Comment by layus** [comment]
Two questions:
1. why require `-f .` by default
2. Why do you use fetchSource in mplayer.nix when the codecs_src attribute cannot be accessed by the update script anyway ?

**Comment by zimbatm** [comment]
the updater script is only there to illustrate the possibility for now. It could be cannibalized or moved to a different repo. The important part is to have access to all the fetchurl instances regardless of the tool.

I think fetchSources should be tried of a few other things before being merged. I am also not quite sure of the naming yet.

**Comment by Mic92** [comment]
Just for related work, I also post this project here: https://github.com/makefu/nix-src-updater

**Comment by layus** [comment]
> There is a different package called: common-updater in nixpkgs. I think we should have only one of the two in our repo.

Indeed. We should update that one. The main advantage of this script is that it locates the file to edit without the need of a `.meta.position` field.

**Comment by zimbatm** [comment]
@layus I tried to mimic the UX of `nix edit`. The script doesn't work since I changed it because nix-prefetch-url doesn't understand this notation.

**Comment by layus** [comment]
> the updater script is only there to illustrate the possibility for now. It could be cannibalized or moved to a different repo. The important part is to have access to all the fetchurl instances regardless of the tool.

Okay, I was already going too far :-). fetchSources is a good name, and I like the concept.

Other idea: Why not automatically detect the right source, or provide a fetchSystemSource function ?

> I think fetchSources should be tried of a few other things before being merged. I am also not quite sure of the naming yet.

May I suggest factorio ?

**Comment by oxij** [comment]
I think `fetchSources` name is misleading. None of the examples seem to fetch _sources_ but instead fetch something binary.
May I suggest `fetchBinaries` or, even better, `selectArch` instead?
`selectArch` also suggests more generic usage anywhere where nixpkgs dispatches on `stdenv.system`.

The `.sources` thing is nice and also integrates well with a little related experiment we run at SLNOS, which looks like this:

```nix
src = selectSource {
  tarball = fetchurl {};
  vcs = fetchgit {};
}
```

(You can then specify which source `selectSource` would give by default with `nixpkgs.config`.)

The point of the experiment is to make it possible to (eventually) review _all_ changes to _all_ packages.

(We have a little system where we vote for and/or veto git commits to nixpkgs, this would (eventually) extend it to voting for all changes to the whole system.)

**Comment by zimbatm** [comment]
It looks like fetchSource could just be a lib function since it's not depending on stdenv. How about:
`lib.select attrs key` and `lib.selectSystem {}`. The only issue is that it assumes that the return value is an attrset and is okay to override the `selections` keys, not sure what to do about that.

**Comment by oxij** [comment]
See 37dedf64536f366df730584b5fb285b0469d2bea of #35075.

**Comment by oxij** [comment]
@zimbatm The problem with not depending on `stdenv` is that `select` then becomes so trivial that it only wastes space. I would do `attrs.${key}` instead.

Lets discuss the proper name here and then I will steal the fixed eb77c083f28494c1d8e2e0da4f6a4eed60042f2b to #35075 because I really need it there.

**Comment by 7c6f434c** [comment]
If I understand correctly, the point is to add the list of the alternative downloads as an attribute of the chosen one.

**Comment by oxij** [comment]
That too, but I don't care about that part, I care about the syntax. `fetchSources` from here is much prettier than expressions soiled with `optionalAttrs` hack from 37dedf64536f366df730584b5fb285b0469d2bea.

**Comment by oxij** [comment]
Ah, I have a better idea for both here and my PR: I will implement `attrByName`, which would be like `attrByPath` but without the path. This is what @zimbatm actually wants, and what I need to make my `src`s pretty. Gone hacking.

**Comment by zimbatm** [comment]
As long as the original attribute set is still accessible somehow it's fine by me

**Pull request closed without merging**
