### PR TITLE
Update Geary to 0.12.2 from master

### PR DESCRIPTION
**Pull request by alexeymuranov**
###### Motivation for this change

Geary 0.12.2 fixes an [annoying bug](https://bugzilla.gnome.org/show_bug.cgi?id=788637).

I've just copied the file from *master* branch.

I didn't test it because i do not know how.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by xeji — CHANGES_REQUESTED** [review]
Please use `git cherry-pick -x` to pick the original commit from `master`. This allows us to track the origin of the change.

**Comment by alexeymuranov** [comment]
I do not think that `cherry-pick` is applicable here...

**Comment by alexeymuranov** [comment]
@jtojnar, what would you recommend?

**Comment by jtojnar** [comment]
If you list the commits that went into the commit, like `cherry-pick -x` does it will probably be fine. But it is more of a question for someone invested in old NixOS, I would just remove GNOME from release branch and recommend people using it from unstable.

**Comment by alexeymuranov** [comment]
Is there an easy way to use some packages from unstable, but the rest from stable?  If i add the unstable channel, then whenever i update something, Nix updates to the version from unstable.

**Comment by jtojnar** [comment]
See https://nixos.wiki/wiki/FAQ#How_can_I_install_a_package_from_unstable_while_remaining_on_the_stable_channel.3F

**Comment by alexeymuranov** [comment]
Thanks, but if i do
```
sudo nix-channel --add https://nixos.org/channels/nixos-unstable nixos-unstable
```
i will not be able to update all the manually installed packages with
```
nix-env -u '*'
```
Will there be a way to update all installed packages from stable to the newer versions from stable?

**Comment by jtojnar** [comment]
I do not use `nix-env` but I would think it would remember which channel you used for installing which package. Maybe ask on irc.

**Pull request closed without merging**
