### PR TITLE
Update imapsync

### PR DESCRIPTION
**Pull request by robinbb**
Improvement upon PR https://github.com/NixOS/nixpkgs/pull/14209 as recommended by @lancelotsix and @joachifm.

### CODE REVIEW

**Comment by joachifm** [comment]
Thanks you. Please review the guidelines on commit naming at https://nixos.org/nixpkgs/manual/#idm140737318605648

**Comment by domenkozar** [comment]
It fails on master due to perl bump, would you care to fix it?

**Comment by domenkozar** [comment]
@robinbb are you going to open a new PR?

**Comment by robinbb** [comment]
@domenkozar No. I love Nix, but I do not have the time to commit to doing a good job of upgrading this package.

**Comment by domenkozar** [comment]
OK, I'll do that then.

**Comment by domenkozar** [comment]
@robinbb can you just rebase? It should work now.

**Comment by joachifm** [comment]
Integrated. Thank you.

**Pull request closed without merging**
