### PR TITLE
eventstore: 22.6.0 -> 22.10.0

### PR DESCRIPTION
**Pull request by mdarocha**
###### Description of changes

Update to latest version available.

This new version uses .NET 6.0 to build, so it helps with https://github.com/NixOS/nixpkgs/issues/173115

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — COMMENTED** [review]
Can you fix the tests that want to connect to the internet on darwin? Maybe we can just disable them. See ofborg logs for details.

**Comment by mdarocha** [comment]
> Can you fix the tests that want to connect to the internet on darwin? Maybe we can just disable them. See ofborg logs for details.

Yeah, I tried, but have some problems with disabling them. I'll try again when I have the time, meanwhile if someone figures it out, let me know :)

**Comment by mdarocha** [comment]
I added the skips and also during that improved the `disabledTests` argument a bit, this PR is now ready to merge

**Comment by farcaller** [comment]
Result of `nixpkgs-review pr 202571` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>msbuild</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>jellyfin</li>
    <li>netcoredbg</li>
  </ul>
</details>
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>boogie (dotnetPackages.Boogie)</li>
    <li>btcpayserver</li>
    <li>formula</li>
    <li>jackett</li>
    <li>nbxplorer</li>
    <li>omnisharp-roslyn</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
BeatSaberModManager already fails on master

**Pull request merged**
