### PR TITLE
vimPlugins.vim-agda: init at 2022-03-01

### PR DESCRIPTION
**Pull request by RasmusRendal**
###### Description of changes
Init the vim-agda package. With the whole  #232078 of it all, I just threw on `vimPlugins: update` to actually generate the plugin. We should probably wait for #232899 to get merged, and then rebase this onto master.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by figsoda** [comment]
merged #232899

**Comment by RasmusRendal** [comment]
> merged #232899

Thanks for letting me know, I've rebased onto master now and rerun the update script

**Comment by figsoda** [comment]
Looks like nvim-treesitter's tests are failing because we were on a commit when a language's queries were [added](https://github.com/nvim-treesitter/nvim-treesitter/commit/8e817bebf9184cab6c59205e1aed3fdce11c8c51) but the bot didn't [catch up](https://github.com/nvim-treesitter/nvim-treesitter/commit/18c393108eb61c2d5157815b9af0e8f5b75c5109) and add it to the lock file yet. This shouldn't be an issue any more once we rerun the udpate script

**Comment by RasmusRendal** [comment]
@ofborg eval (That failure for x86_64-darwin was definitely spurious, it seemed to build the wrong commit. Maybe the force-push did it in? Wonder if I can even call ofborg)

**Comment by RasmusRendal** [comment]
> Looks like nvim-treesitter's tests are failing because we were on a commit when a language's queries were [added](https://github.com/nvim-treesitter/nvim-treesitter/commit/8e817bebf9184cab6c59205e1aed3fdce11c8c51) but the bot didn't [catch up](https://github.com/nvim-treesitter/nvim-treesitter/commit/18c393108eb61c2d5157815b9af0e8f5b75c5109) and add it to the lock file yet. This shouldn't be an issue any more once we rerun the udpate script

Alright, I'm pretty sure that's fixed now. Ofborg did fail on `x86_64-darwin`, but I'm pretty sure that's spurious, and it's building the wrong commit. If you look in the [log](https://logs.ofborg.org/?key=nixos/nixpkgs.232992&attempt_id=97efcedd-d582-4c73-8904-df2d885c2ecd), you can see it building `c-grammar-0.0.0+rev=424d014`, which is the version that `c-grammar` has on master, even though this PR has upgraded to `c-grammar-0.0.0+rev=cac392a`. The other ofborg builds, which pass, are building the correct version of `c-grammar`.

I tried rerunning ofborg, but it didn't work. You probably need to be a nixpkgs commiter or something like that ¯\\\_(ツ)_/¯

**Review by figsoda — APPROVED** [review]

**Pull request merged**
