### PR TITLE
waybar: 0.9.4 -> 0.9.5

### PR DESCRIPTION
**Pull request by bbigras**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

/nix/store/aqgwqk9si8a5ncyyl4z422yz7r9wp0s7-waybar-0.9.4	 346.1M
/nix/store/dr3k59pc4hywr0y475q830m1mgvwxi2h-waybar-0.9.5	 348.5M

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110273` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>waybar</li>
</ul>
</details>

**Review by minijackson — APPROVED** [review]
Thanks for the PR! 

When I saw that Waybar had a new release I was confused about if I should update this in nixpkgs, because of the big "WIP" written in the release. But looking again, I can see that a lots of Linux distributions have updated it, so it should be fine?

---

Result of `nix-review pr 110273` [1](https://github.com/Mic92/nix-review)
<details>
  <summary>1 package were built:</summary>

  - waybar
</details>

Tested it, works great!

**Comment by bbigras** [comment]
> When I saw that Waybar had a new release I was confused about if I should update this in nixpkgs, because of the big "WIP" written in the release. But looking again, I can see that a lots of Linux distributions have updated it, so it should be fine?

I thought maybe the release note was a WIP... 

There's a bit of commits in this, so I'm guessing it's worth it to package it.

**Comment by bbigras** [comment]
Thanks!

**Pull request merged**
