### PR TITLE
python312Packages.pytensor: disable failing tests on darwin

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Things done

Until recently, this package was disabled on darwin as our tensorflow was broken on this platform.
Now, we are using `tensorflow-bin` as the default and it makes `pytensor` buildable.
Unfortunately, several tests fail with:

<details>

```
            # difficult to read.
            # compile_stderr = compile_stderr.replace("\n", ". ")
>           raise CompileError(
                f"Compilation failed (return status={status}):\n{' '.join(cmd)}\n{compile_stderr}"
E               pytensor.link.c.exceptions.CompileError: Compilation failed (return status=1):
E               /nix/store/v39c0h6xv6hvki2k1bsyp5n090q8y2bp-clang-wrapper-16.0.6/bin/clang++ -dynamiclib -g -O3 -fno-math-errno -Wno-unused-label -Wno-unused-variable -Wno-write-strings -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -fPIC -undefined dynamic_lookup -I/nix/store/hxy7883sqyc9nsy6lbnfnqpi6n2p8rif-python3.11-numpy-1.26.4/lib/python3.11/site-packages/numpy/core/include -I/nix/store/qw9bwqbwcai9iaqiyir18knz91sff9am-python3-3.11.10/include/python3.11 -I/nix/store/51l67x35qzm94dgvy00i3p1skq7m0pkm-python3.11-pytensor-2.26.3/lib/python3.11/site-packages/pytensor/link/c/c_code -L/nix/store/qw9bwqbwcai9iaqiyir18knz91sff9am-python3-3.11.10/lib -fvisibility=hidden -o /private/tmp/nix-build-python3.11-pytensor-2.26.3.drv-0/tmp.7gz20k28t5/.pytensor/compiledir_macOS-14.7.1-arm64-arm-64bit-arm-3.11.10-64/tmpz22hhl4t/m2e6727be0750601c202685d31bcecfdb5515e8d3613c6d398468a7b477caf5cb.so /private/tmp/nix-build-python3.11-pytensor-2.26.3.drv-0/tmp.7gz20k28t5/.pytensor/compiledir_macOS-14.7.1-arm64-arm-64bit-arm-3.11.10-64/tmpz22hhl4t/mod.cpp
E               /private/tmp/nix-build-python3.11-pytensor-2.26.3.drv-0/tmp.7gz20k28t5/.pytensor/compiledir_macOS-14.7.1-arm64-arm-64bit-arm-3.11.10-64/tmpz22hhl4t/mod.cpp:514:9: error: non-constant-expression cannot be narrowed from type 'ssize_t' (aka 'long') to 'int' in initializer list [-Wc++11-narrowing]
E                       V5_stride0, V5_stride1,
E                       ^~~~~~~~~~
E               /private/tmp/nix-build-python3.11-pytensor-2.26.3.drv-0/tmp.7gz20k28t5/.pytensor/compiledir_macOS-14.7.1-arm64-arm-64bit-arm-3.11.10-64/tmpz22hhl4t/mod.cpp:514:9: note: insert an explicit cast to silence this issue
E                       V5_stride0, V5_stride1,
E                       ^~~~~~~~~~
E                       static_cast<int>( )
E               /private/tmp/nix-build-python3.11-pytensor-2.26.3.drv-0/tmp.7gz20k28t5/.pytensor/compiledir_macOS-14.7.1-arm64-arm-64bit-arm-3.11.10-64/tmpz22hhl4t/mod.cpp:514:21: error: non-constant-expression cannot be narrowed from type 'ssize_t' (aka 'long') to 'int' in initializer list [-Wc++11-narrowing]
E                       V5_stride0, V5_stride1,
E                                   ^~~~~~~~~~
E               /private/tmp/nix-build-python3.11-pytensor-2.26.3.drv-0/tmp.7gz20k28t5/.pytensor/compiledir_macOS-14.7.1-arm64-arm-64bit-arm-3.11.10-64/tmpz22hhl4t/mod.cpp:514:21: note: insert an explicit cast to silence this issue
E                       V5_stride0, V5_stride1,
E                                   ^~~~~~~~~~
E                                   static_cast<int>( )
E               /private/tmp/nix-build-python3.11-pytensor-2.26.3.drv-0/tmp.7gz20k28t5/.pytensor/compiledir_macOS-14.7.1-arm64-arm-64bit-arm-3.11.10-64/tmpz22hhl4t/mod.cpp:515:1: error: non-constant-expression cannot be narrowed from type 'ssize_t' (aka 'long') to 'int' in initializer list [-Wc++11-narrowing]
E               V3_stride0, V3_stride1
E               ^~~~~~~~~~
E               /private/tmp/nix-build-python3.11-pytensor-2.26.3.drv-0/tmp.7gz20k28t5/.pytensor/compiledir_macOS-14.7.1-arm64-arm-64bit-arm-3.11.10-64/tmpz22hhl4t/mod.cpp:515:1: note: insert an explicit cast to silence this issue
E               V3_stride0, V3_stride1
E               ^~~~~~~~~~
E               static_cast<int>( )
E               /private/tmp/nix-build-python3.11-pytensor-2.26.3.drv-0/tmp.7gz20k28t5/.pytensor/compiledir_macOS-14.7.1-arm64-arm-64bit-arm-3.11.10-64/tmpz22hhl4t/mod.cpp:515:13: error: non-constant-expression cannot be narrowed from type 'ssize_t' (aka 'long') to 'int' in initializer list [-Wc++11-narrowing]
E               V3_stride0, V3_stride1
E                           ^~~~~~~~~~
E               /private/tmp/nix-build-python3.11-pytensor-2.26.3.drv-0/tmp.7gz20k28t5/.pytensor/compiledir_macOS-14.7.1-arm64-arm-64bit-arm-3.11.10-64/tmpz22hhl4t/mod.cpp:515:13: note: insert an explicit cast to silence this issue
E               V3_stride0, V3_stride1
E                           ^~~~~~~~~~
E                           static_cast<int>( )
E               4 errors generated.

/nix/store/51l67x35qzm94dgvy00i3p1skq7m0pkm-python3.11-pytensor-2.26.3/lib/python3.11/site-packages/pytensor/link/c/cmodule.py:2685: CompileError
```

</details>

I propose to simply disable those tests for now.
Unfortunately, the test names are fairly general so several successful tests are surely ignored too.
Overall, the coverage remains acceptable:
```
1480 passed, 96 skipped, 381 deselected, 17 xfailed, 106 warnings
```

**NOTE:** The package is still not buildable on `x86_64-darwin` because `jax` is not available there. Hence, this PR only really targets `aarch64-darwin`.

cc @bcdarwin @ferrine

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by ferrine — APPROVED** [review]
Yeah,  I agree those compilation issues are not relevant for using the package

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 360745`

---
### `x86_64-linux`

---
### `aarch64-linux`

---
### `x86_64-darwin`

---
### `aarch64-darwin`
<details>
  <summary>:x: 4 packages failed to build:</summary>
  <ul>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
    <li>python312Packages.bambi</li>
    <li>python312Packages.bambi.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 8 packages built:</summary>
  <ul>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymc.dist</li>
    <li>python311Packages.pytensor</li>
    <li>python311Packages.pytensor.dist</li>
    <li>python312Packages.pymc</li>
    <li>python312Packages.pymc.dist</li>
    <li>python312Packages.pytensor</li>
    <li>python312Packages.pytensor.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 360745`

---
### `x86_64-linux`

---
### `aarch64-linux`

---
### `x86_64-darwin`

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 12 packages built:</summary>
  <ul>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymc.dist</li>
    <li>python311Packages.pytensor</li>
    <li>python311Packages.pytensor.dist</li>
    <li>python312Packages.bambi</li>
    <li>python312Packages.bambi.dist</li>
    <li>python312Packages.pymc</li>
    <li>python312Packages.pymc.dist</li>
    <li>python312Packages.pytensor</li>
    <li>python312Packages.pytensor.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 360745`

---
### `x86_64-linux`

---
### `aarch64-linux`

---
### `x86_64-darwin`

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 12 packages built:</summary>
  <ul>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymc.dist</li>
    <li>python311Packages.pytensor</li>
    <li>python311Packages.pytensor.dist</li>
    <li>python312Packages.bambi</li>
    <li>python312Packages.bambi.dist</li>
    <li>python312Packages.pymc</li>
    <li>python312Packages.pymc.dist</li>
    <li>python312Packages.pytensor</li>
    <li>python312Packages.pytensor.dist</li>
  </ul>
</details>

**Pull request merged**
