### PR TITLE
sbcl.pkgs: update to Quicklisp dist from June 2023

### PR DESCRIPTION
**Pull request by Uthar**
###### Description of changes

Ran `ql-import.lisp`

Upstream announcement: http://blog.quicklisp.org/2023/06/june-2023-quicklisp-dist-update-now.html

Notably:

> I **removed Nyxt** because it uses its own style of build system (nasdf) that doesn't work very well with Quicklisp. I recommend getting it directly if you want to use it.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Uthar** [comment]
@ofborg build nyxt

**Comment by Vonfry** [comment]
#235095 updates some packages manually to build the new version nyxt. Should we revert these updates and apply the new quicklisp ones?

**Comment by 7c6f434c** [comment]
Re: Nyxt deps: I guess if Quicklisp has updated at least as far, we can try dropping the overrides (and see if Nyxt is happy). But this can be done separately.

**Comment by dariof4** [comment]
Result of `nixpkgs-review pr 238790` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>sbclPackages.cl-gtk4_dot_webkit2</li>
    <li>sbclPackages.cl-tar</li>
  </ul>
</details>
<details>
  <summary>301 packages built:</summary>
  <ul>
    <li>nyxt</li>
    <li>sbclPackages.access</li>
    <li>sbclPackages.acclimation</li>
    <li>sbclPackages.agutil</li>
    <li>sbclPackages.alexandria</li>
    <li>sbclPackages.arnesi</li>
    <li>sbclPackages.array-operations</li>
    <li>sbclPackages.array-utils</li>
    <li>sbclPackages.babel</li>
    <li>sbclPackages.binpack</li>
    <li>sbclPackages.bordeaux-threads</li>
    <li>sbclPackages.buildnode</li>
    <li>sbclPackages.buildnode-xhtml</li>
    <li>sbclPackages.calispel</li>
    <li>sbclPackages.cffi</li>
    <li>sbclPackages.cffi-grovel</li>
    <li>sbclPackages.cffi-libffi</li>
    <li>sbclPackages.cffi-toolchain</li>
    <li>sbclPackages.cffi-uffi-compat</li>
    <li>sbclPackages.chanl</li>
    <li>sbclPackages.check-it</li>
    <li>sbclPackages.chipz</li>
    <li>sbclPackages.circular-streams</li>
    <li>sbclPackages.cl-ana</li>
    <li>sbclPackages.cl-annot</li>
    <li>sbclPackages.cl-ansi-text</li>
    <li>sbclPackages.cl-async</li>
    <li>sbclPackages.cl-async-base</li>
    <li>sbclPackages.cl-async-repl</li>
    <li>sbclPackages.cl-async-ssl</li>
    <li>sbclPackages.cl-async-util</li>
    <li>sbclPackages.cl-avro</li>
    <li>sbclPackages.cl-cairo2</li>
    <li>sbclPackages.cl-cairo2-xlib</li>
    <li>sbclPackages.cl-cffi-gtk</li>
    <li>sbclPackages.cl-cffi-gtk-cairo</li>
    <li>sbclPackages.cl-cffi-gtk-gdk</li>
    <li>sbclPackages.cl-cffi-gtk-gdk-pixbuf</li>
    <li>sbclPackages.cl-cffi-gtk-gio</li>
    <li>sbclPackages.cl-cffi-gtk-glib</li>
    <li>sbclPackages.cl-cffi-gtk-gobject</li>
    <li>sbclPackages.cl-cffi-gtk-pango</li>
    <li>sbclPackages.cl-change-case</li>
    <li>sbclPackages.cl-colors</li>
    <li>sbclPackages.cl-colors2</li>
    <li>sbclPackages.cl-colors2_0_5_3</li>
    <li>sbclPackages.cl-containers</li>
    <li>sbclPackages.cl-cookie</li>
    <li>sbclPackages.cl-csv</li>
    <li>sbclPackages.cl-cuda</li>
    <li>sbclPackages.cl-dbi</li>
    <li>sbclPackages.cl-emb</li>
    <li>sbclPackages.cl-environments</li>
    <li>sbclPackages.cl-fad</li>
    <li>sbclPackages.cl-form-types</li>
    <li>sbclPackages.cl-freetype2</li>
    <li>sbclPackages.cl-fuse</li>
    <li>sbclPackages.cl-fuse-meta-fs</li>
    <li>sbclPackages.cl-fuzz</li>
    <li>sbclPackages.cl-glib</li>
    <li>sbclPackages.cl-glib_dot_gio</li>
    <li>sbclPackages.cl-gobject-introspection</li>
    <li>sbclPackages.cl-gtk2-gdk</li>
    <li>sbclPackages.cl-gtk2-glib</li>
    <li>sbclPackages.cl-gtk2-pango</li>
    <li>sbclPackages.cl-gtk4</li>
    <li>sbclPackages.cl-gtk4_dot_adw</li>
    <li>sbclPackages.cl-hooks</li>
    <li>sbclPackages.cl-html5-parser</li>
    <li>sbclPackages.cl-interpol</li>
    <li>sbclPackages.cl-l10n</li>
    <li>sbclPackages.cl-liballegro-nuklear</li>
    <li>sbclPackages.cl-libuv</li>
    <li>sbclPackages.cl-libxml2</li>
    <li>sbclPackages.cl-libyaml</li>
    <li>sbclPackages.cl-locale</li>
    <li>sbclPackages.cl-mysql</li>
    <li>sbclPackages.cl-notify</li>
    <li>sbclPackages.cl-pango</li>
    <li>sbclPackages.cl-paths-ttf</li>
    <li>sbclPackages.cl-pattern</li>
    <li>sbclPackages.cl-pdf</li>
    <li>sbclPackages.cl-postgres</li>
    <li>sbclPackages.cl-postgres_plus_local-time</li>
    <li>sbclPackages.cl-ppcre</li>
    <li>sbclPackages.cl-ppcre-template</li>
    <li>sbclPackages.cl-ppcre-unicode</li>
    <li>sbclPackages.cl-prevalence</li>
    <li>sbclPackages.cl-readline</li>
    <li>sbclPackages.cl-reexport</li>
    <li>sbclPackages.cl-rsvg2</li>
    <li>sbclPackages.cl-sat</li>
    <li>sbclPackages.cl-sat_dot_glucose</li>
    <li>sbclPackages.cl-sat_dot_minisat</li>
    <li>sbclPackages.cl-shellwords</li>
    <li>sbclPackages.cl-slice</li>
    <li>sbclPackages.cl-smt-lib</li>
    <li>sbclPackages.cl-smtp</li>
    <li>sbclPackages.cl-syntax</li>
    <li>sbclPackages.cl-syntax-annot</li>
    <li>sbclPackages.cl-syntax-anonfun</li>
    <li>sbclPackages.cl-syntax-markup</li>
    <li>sbclPackages.cl-syslog</li>
    <li>sbclPackages.cl-tar-file</li>
    <li>sbclPackages.cl-test-more</li>
    <li>sbclPackages.cl-typesetting</li>
    <li>sbclPackages.cl-unicode</li>
    <li>sbclPackages.cl-webkit2</li>
    <li>sbclPackages.cl-webkit2_3_5_8</li>
    <li>sbclPackages.cl-xmlspam</li>
    <li>sbclPackages.cl_plus_ssl</li>
    <li>sbclPackages.clack</li>
    <li>sbclPackages.clack-socket</li>
    <li>sbclPackages.classowary</li>
    <li>sbclPackages.clfswm</li>
    <li>sbclPackages.closer-mop</li>
    <li>sbclPackages.closure-common</li>
    <li>sbclPackages.closure-html</li>
    <li>sbclPackages.clss</li>
    <li>sbclPackages.cluffer</li>
    <li>sbclPackages.clump</li>
    <li>sbclPackages.clump-2-3-tree</li>
    <li>sbclPackages.clump-binary-tree</li>
    <li>sbclPackages.clx</li>
    <li>sbclPackages.clx-truetype</li>
    <li>sbclPackages.collectors</li>
    <li>sbclPackages.colorize</li>
    <li>sbclPackages.qtgui (sbclPackages.qtcore ,sbclPackages.qthelp ,sbclPackages.qtnetwork ,sbclPackages.qtopengl ,sbclPackages.qtscript ,sbclPackages.qtsql ,sbclPackages.qtsvg ,sbclPackages.qttest ,sbclPackages.qtuitools ,sbclPackages.qtxml ,sbclPackages.qtxmlpatterns ,sbclPackages.smokebase)</li>
    <li>sbclPackages.css-lite</li>
    <li>sbclPackages.css-selectors</li>
    <li>sbclPackages.css-selectors-simple-tree</li>
    <li>sbclPackages.css-selectors-stp</li>
    <li>sbclPackages.cxml</li>
    <li>sbclPackages.cxml-stp</li>
    <li>sbclPackages.data-table</li>
    <li>sbclPackages.dbd-mysql</li>
    <li>sbclPackages.dbd-postgres</li>
    <li>sbclPackages.dbd-sqlite3</li>
    <li>sbclPackages.dbi</li>
    <li>sbclPackages.dbi-test</li>
    <li>sbclPackages.dbus</li>
    <li>sbclPackages.defclass-std</li>
    <li>sbclPackages.dexador</li>
    <li>sbclPackages.djula</li>
    <li>sbclPackages.do-urlencode</li>
    <li>sbclPackages.documentation-utils</li>
    <li>sbclPackages.drakma</li>
    <li>sbclPackages.duckdb</li>
    <li>sbclPackages.eager-future2</li>
    <li>sbclPackages.enchant</li>
    <li>sbclPackages.esrap</li>
    <li>sbclPackages.esrap-peg</li>
    <li>sbclPackages.external-program</li>
    <li>sbclPackages.fare-mop</li>
    <li>sbclPackages.fare-quasiquote-extras</li>
    <li>sbclPackages.fare-quasiquote-optima</li>
    <li>sbclPackages.fare-quasiquote-readtable</li>
    <li>sbclPackages.fast-http</li>
    <li>sbclPackages.fast-io</li>
    <li>sbclPackages.fiasco</li>
    <li>sbclPackages.file-attributes</li>
    <li>sbclPackages.fiveam</li>
    <li>sbclPackages.float-features</li>
    <li>sbclPackages.flow</li>
    <li>sbclPackages.fn</li>
    <li>sbclPackages.form-fiddle</li>
    <li>sbclPackages.fset</li>
    <li>sbclPackages.generic-cl</li>
    <li>sbclPackages.gsll</li>
    <li>sbclPackages.history-tree</li>
    <li>sbclPackages.http-body</li>
    <li>sbclPackages.hu_dot_dwim_dot_common</li>
    <li>sbclPackages.hu_dot_dwim_dot_def</li>
    <li>sbclPackages.hu_dot_dwim_dot_def_plus_swank</li>
    <li>sbclPackages.hu_dot_dwim_dot_stefil</li>
    <li>sbclPackages.hu_dot_dwim_dot_stefil_plus_hu_dot_dwim_dot_def</li>
    <li>sbclPackages.hu_dot_dwim_dot_stefil_plus_hu_dot_dwim_dot_def_plus_swank</li>
    <li>sbclPackages.hu_dot_dwim_dot_stefil_plus_swank</li>
    <li>sbclPackages.hunchensocket</li>
    <li>sbclPackages.hunchentoot</li>
    <li>sbclPackages.inferior-shell</li>
    <li>sbclPackages.iolib</li>
    <li>sbclPackages.iolib_dot_asdf</li>
    <li>sbclPackages.iolib_dot_base</li>
    <li>sbclPackages.iolib_dot_common-lisp</li>
    <li>sbclPackages.iolib_dot_conf</li>
    <li>sbclPackages.ironclad</li>
    <li>sbclPackages.jonathan</li>
    <li>sbclPackages.jpl-queues</li>
    <li>sbclPackages.jzon</li>
    <li>sbclPackages.kons-9</li>
    <li>sbclPackages.lack</li>
    <li>sbclPackages.lack-component</li>
    <li>sbclPackages.lack-middleware-backtrace</li>
    <li>sbclPackages.lack-util</li>
    <li>sbclPackages.legit</li>
    <li>sbclPackages.let-plus</li>
    <li>sbclPackages.lev</li>
    <li>sbclPackages.lfarm-client</li>
    <li>sbclPackages.lfarm-common</li>
    <li>sbclPackages.lfarm-server</li>
    <li>sbclPackages.lfarm-ssl</li>
    <li>sbclPackages.lisp-binary</li>
    <li>sbclPackages.lisp-namespace</li>
    <li>sbclPackages.lisp-unit2</li>
    <li>sbclPackages.lla</li>
    <li>sbclPackages.log4cl</li>
    <li>sbclPackages.lparallel</li>
    <li>sbclPackages.lquery</li>
    <li>sbclPackages.magicl</li>
    <li>sbclPackages.mathkit</li>
    <li>sbclPackages.metabang-bind</li>
    <li>sbclPackages.mgl</li>
    <li>sbclPackages.mgl-mat</li>
    <li>sbclPackages.mgl-pax</li>
    <li>sbclPackages.mmap</li>
    <li>sbclPackages.moptilities</li>
    <li>sbclPackages.more-conditions</li>
    <li>sbclPackages.named-readtables</li>
    <li>sbclPackages.nbd</li>
    <li>sbclPackages.nclasses_0_5_0</li>
    <li>sbclPackages.nfiles_1_1_2</li>
    <li>sbclPackages.nhooks</li>
    <li>sbclPackages.nkeymaps</li>
    <li>sbclPackages.nsymbols_0_3_1</li>
    <li>sbclPackages.nyxt (sbclPackages.nyxt-gtk)</li>
    <li>sbclPackages.optima</li>
    <li>sbclPackages.osicat</li>
    <li>sbclPackages.parachute</li>
    <li>sbclPackages.parenscript</li>
    <li>sbclPackages.parse-float</li>
    <li>sbclPackages.parser-combinators</li>
    <li>sbclPackages.parser_dot_common-rules</li>
    <li>sbclPackages.pcall</li>
    <li>sbclPackages.pcall-queue</li>
    <li>sbclPackages.plump</li>
    <li>sbclPackages.polyclot</li>
    <li>sbclPackages.postmodern</li>
    <li>sbclPackages.proc-parse</li>
    <li>sbclPackages.prompter</li>
    <li>sbclPackages.prove</li>
    <li>sbclPackages.pythonic-string-reader</li>
    <li>sbclPackages.pzmq</li>
    <li>sbclPackages.pzmq-compat</li>
    <li>sbclPackages.pzmq-examples</li>
    <li>sbclPackages.pzmq-test</li>
    <li>sbclPackages.qt</li>
    <li>sbclPackages.qtools</li>
    <li>sbclPackages.query-fs</li>
    <li>sbclPackages.quri</li>
    <li>sbclPackages.quri_7_0</li>
    <li>sbclPackages.rove</li>
    <li>sbclPackages.s-sql</li>
    <li>sbclPackages.s-sysdeps</li>
    <li>sbclPackages.serapeum</li>
    <li>sbclPackages.simple-date-time</li>
    <li>sbclPackages.simple-inferiors</li>
    <li>sbclPackages.simple-tasks</li>
    <li>sbclPackages.slynk</li>
    <li>sbclPackages.spinneret</li>
    <li>sbclPackages.sqlite</li>
    <li>sbclPackages.static-dispatch</li>
    <li>sbclPackages.static-vectors</li>
    <li>sbclPackages.stefil</li>
    <li>sbclPackages.str</li>
    <li>stumpwm (sbclPackages.stumpwm)</li>
    <li>stumpwm-unwrapped (sbclPackages.stumpwm-unwrapped)</li>
    <li>sbclPackages.swap-bytes</li>
    <li>sbclPackages.sycamore</li>
    <li>sbclPackages.symbol-munger</li>
    <li>sbclPackages.trivia</li>
    <li>sbclPackages.trivia_dot_balland2006</li>
    <li>sbclPackages.trivia_dot_level0</li>
    <li>sbclPackages.trivia_dot_level1</li>
    <li>sbclPackages.trivia_dot_level2</li>
    <li>sbclPackages.trivia_dot_quasiquote</li>
    <li>sbclPackages.trivia_dot_trivial</li>
    <li>sbclPackages.trivial-arguments</li>
    <li>sbclPackages.trivial-clipboard</li>
    <li>sbclPackages.trivial-features</li>
    <li>sbclPackages.trivial-indent</li>
    <li>sbclPackages.trivial-main-thread</li>
    <li>sbclPackages.trivial-package-manager</li>
    <li>sbclPackages.trivial-with-current-source-form</li>
    <li>sbclPackages.type-i</li>
    <li>sbclPackages.uax-15</li>
    <li>sbclPackages.usocket</li>
    <li>sbclPackages.usocket-server</li>
    <li>sbclPackages.utilities_dot_print-items</li>
    <li>sbclPackages.utilities_dot_print-tree</li>
    <li>sbclPackages.uuid</li>
    <li>sbclPackages.varjo</li>
    <li>sbclPackages.vecto</li>
    <li>sbclPackages.woo</li>
    <li>sbclPackages.wookie</li>
    <li>sbclPackages.xembed</li>
    <li>sbclPackages.xkeyboard</li>
    <li>sbclPackages.xml_dot_location</li>
    <li>sbclPackages.xpath</li>
    <li>sbclPackages.yason</li>
    <li>sbclPackages.zpb-ttf</li>
  </ul>
</details>

Out of the package that failed `sbclPackages.cl-gtk4_dot_webkit2` was already failing (see: https://github.com/NixOS/nixpkgs/commit/7486a74d9f5c3581c2db0e186d4763ff3a4ae782) and `sbclPackage.cl-tar` is failing with these errors:
```
; caught WARNING:
;   Argument :PACKAGE-SYMBOL is deprecated in DEFSECTION macr. Use :PACKAGE instead.
; 
; caught ERROR:
;   (during macroexpansion of (40ANTS-DOC:DEFSECTION @MANUAL
;       ...))
;   (FIND-PACKAGE :TAR) fell through ETYPECASE expression.
;   Wanted one of (PACKAGE KEYWORD STRING SYMBOL).
```

I debugged around a bit and found the culprit, this commit here for `_40ants-doc` https://github.com/40ants/doc/commit/897d29f59b84f14e3bb351ac39d4231b28d85818 which deprecates `:package-symbol` and uses `:find-package` internally, with this patch applied to `cl-tar` it builds correctly, this seems like an upstream issue though, other than that LGTM.


```diff
diff --git a/src/docs.lisp b/src/docs.lisp
index 49046ae..3265cf3 100644
--- a/src/docs.lisp
+++ b/src/docs.lisp
@@ -14,7 +14,7 @@
 (40ants-doc:defsection @manual
     (:title "Tar"
      :export nil
-     :package-symbol (find-package :tar))
+     :package :tar)
   #.(uiop:read-file-string (asdf:system-relative-pathname :tar "README.md"))
   (@tar 40ants-doc/locatives:section)
   (@tar-simple-extract 40ants-doc/locatives:section)
@@ -24,7 +24,7 @@
 (40ants-doc:defsection @tar-simple-extract
     (:title "Simple Extraction"
      :export nil
-     :package-symbol (find-package :tar-simple-extract))
+     :package :tar-simple-extract)
   "This section describes the support for simple extraction to the filesystem."
   (simple-extract-archive 40ants-doc/locatives:function)
   (@tar-simple-extract-conditions 40ants-doc/locatives:section))
@@ -32,7 +32,7 @@
 (40ants-doc:defsection @tar-simple-extract-conditions
     (:title "Simple Extraction Conditions"
      :export nil
-     :package-symbol (find-package :tar-simple-extract))
+     :package :tar-simple-extract)
   "This section describes the conditions that can occur during
 SIMPLE-EXTRACT-ARCHIVE."
   (extraction-error 40ants-doc/locatives:class)
@@ -56,7 +56,7 @@ SIMPLE-EXTRACT-ARCHIVE."
 (40ants-doc:defsection @tar-extract
     (:title "Extraction"
      :export nil
-     :package-symbol (find-package :tar-extract))
+     :package :tar-extract)
   "This section describes the support for non-portable extraction to the
 filesystem."
   (extract-archive 40ants-doc/locatives:function)
@@ -65,7 +65,7 @@ filesystem."
 (40ants-doc:defsection @tar-extract-conditions
     (:title "Extraction Conditions"
      :export nil
-     :package-symbol (find-package :tar-extract))
+     :package :tar-extract)
   "This section describes the conditions that can occur during
 EXTRACT-ARCHIVE."
   (extraction-error 40ants-doc/locatives:class)
@@ -101,7 +101,7 @@ EXTRACT-ARCHIVE."
 (40ants-doc:defsection @tar-create
     (:title "Create"
      :export nil
-     :package-symbol (find-package :tar-create))
+     :package :tar-create)
   "This section describes the support for non-portable creation of archives
 from the filesystem."
   (create-archive 40ants-doc/locatives:function))
@@ -109,7 +109,7 @@ from the filesystem."
 (40ants-doc:defsection @tar
     (:title "Tar"
      :export nil
-     :package-symbol (find-package :tar))
+     :package :tar)
   "This section describes the high level tar archive support."
   (@tar-archives 40ants-doc/locatives:section)
   (@tar-entries 40ants-doc/locatives:section)
@@ -118,7 +118,7 @@ from the filesystem."
 (40ants-doc:defsection @tar-archives
     (:title "Tar Archives"
      :export nil
-     :package-symbol (find-package :tar))
+     :package :tar)
   (tar:archive 40ants-doc/locatives:class)
   (tar:gnu-archive 40ants-doc/locatives:class)
   (tar:pax-archive 40ants-doc/locatives:class)
@@ -132,7 +132,7 @@ from the filesystem."
 (40ants-doc:defsection @tar-entries
     (:title "Tar Entries"
      :export nil
-     :package-symbol (find-package :tar))
+     :package :tar)
   "This section describes the various entry types and how to read/write them
   from/to an archive."
 
@@ -168,7 +168,7 @@ from the filesystem."
 (40ants-doc:defsection @tar-conditions
     (:title "Tar Conditions"
      :export nil
-     :package-symbol (find-package :tar))
+     :package :tar)
   "This section describes the various conditions and restarts in the tar
 system."
   (tar:tar-condition 40ants-doc/locatives:class)
```

**Comment by Uthar** [comment]
@ofborg build sbcl.pkgs.tar

**Review by dariof4 — APPROVED** [review]

**Pull request merged**
