### PR TITLE
python3.pkgs.pygobject2: 2.28.6 -> 2.28.7

### PR DESCRIPTION
**Pull request by jtojnar**
https://download.gnome.org/sources/pygobject/2.28/pygobject-2.28.7.news

Throwback to 2017, noticed this in r-ryantm's logs.

### CODE REVIEW

**Comment by jonringer** [comment]
diff LGTM, ill run a `nix-review` when im back home

**Comment by jtojnar** [comment]
Uugh, bluez still depends on this on master, https://github.com/NixOS/nixpkgs/pull/74995 will make it non-mass rebuild.

**Comment by bkchr** [comment]
On master this fails to build:
```
/nix/store/xb062l4b76zyhq6grqf4iyfdikkpg8fl-bash-4.4-p23/bin/bash /build/pygobject-2.28.7/install-sh -d /nix/store/lgvyv8c87zj5slk54zsxw77dc6257j09-python3.7-pygobject-2.28.7/lib/python3.7/site-packages
echo "gtk-2.0" > /nix/store/lgvyv8c87zj5slk54zsxw77dc6257j09-python3.7-pygobject-2.28.7/lib/python3.7/site-packages/pygtk.pth
 /nix/store/d7hlkykjjqs3f200jnmjm1y2hzgvbqa8-coreutils-8.31/bin/mkdir -p '/nix/store/lgvyv8c87zj5slk54zsxw77dc6257j09-python3.7-pygobject-2.28.7/lib/pkgconfig'
 /nix/store/d7hlkykjjqs3f200jnmjm1y2hzgvbqa8-coreutils-8.31/bin/install -c -m 644 pygobject-2.0.pc '/nix/store/lgvyv8c87zj5slk54zsxw77dc6257j09-python3.7-pygobject-2.28.7/lib/pkgconfig'
make[2]: Leaving directory '/build/pygobject-2.28.7'
make[1]: Leaving directory '/build/pygobject-2.28.7'
chmod: missing operand after ‘a-x’
Try 'chmod --help' for more information.
```

**Comment by jtojnar** [comment]
Thanks, fixed in 136c83c977d.

**Pull request merged**
