### PR TITLE
searx: pin flask-babel to 2.0.0

### LINKED ISSUE #216695: `searx` : internal server error
### Describe the bug

I'm running a `searx` instance through the corresponding NixOS module. The system builds successfully and the `uwsgi` service manages to start, but when trying to connect to the instance I get an `Internal server error`. I believe the relevant part of the `uwsgi` log is the following:

```console
Traceback (most recent call last):
File "/nix/store/y6akp3d17rskpxgz769pmczlr5lh896y-python3-3.10.9-env/lib/python3.10/site-packages/searx/webapp.py", line 191, >
@babel.localeselector
AttributeError: 'Babel' object has no attribute 'localeselector'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
```

### Notify maintainers

@matejc @globin @danielfullmer

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.81, NixOS, 23.05 (Stoat), 23.05.20230215.6d33e5e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(qaristote): `"nixos-22.05pre333986.73369f8d086"`
 - channels(root): `"nixos-22.05pre369524.5181d5945ed"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Note that I'm building my configuration through a flake and thus use `nixpkgs-unstable`.

### PR DESCRIPTION
**Pull request by eryg-kai**
###### Description of changes

Pin flask-babel to 2.0.0 for the searx package.  Using 3.x was resulting in the error:

```
"'Babel' object has no attribute 'localeselector'"
```

Fixes https://github.com/NixOS/nixpkgs/issues/216695

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

When I ran the tests I confirmed the Babel error no longer appears but there seem to be unrelated errors in there as well.

### CODE REVIEW

**Comment by NickCao** [comment]
It can instead be an easy fix, see https://github.com/janeczku/calibre-web/commit/94a6931d48d347ae6c07e2b5f0301e8cf97cf53d for example.

**Comment by eryg-kai** [comment]
Thank you!  I opened a PR upstream: https://github.com/searx/searx/pull/3501

**Comment by SuperSandro2000** [comment]
> Thank you! I opened a PR upstream: [searx/searx#3501](https://github.com/searx/searx/pull/3501)

Can we fetch that patch instead?

**Comment by matejc** [comment]
Searx is officially no longer being maintained, I think we can close this PR

**Comment by SuperSandro2000** [comment]
I started this in #258813

**Pull request closed without merging**
