### PR TITLE
Revert "haskellPackages.{SC,sc}alendar: nullify to fix ofborg eval"

### PR DESCRIPTION
**Pull request by peti**
Reverts NixOS/nixpkgs#33077. Don't null out  packages! `meta.broken = true` is the API we've been using this for a long time and I didn't get any memo that said that this had been changed.

Cc: @grahamc

### CODE REVIEW

**Comment by vcunat** [comment]
Even broken packages shouldn't be breaking *evaluation*, I believe.

**Comment by grahamc** [comment]
> As far as I am concerned, the source of the problem is the fact that the bot evaluates explicitly broken packages!

I agree with @vcunat. This is the _only_ `broken` package which doesn't even evaluate. What do you think about @pbogdan's other workaround:

```
  scalendar = markBroken (super.scalendar.override { SCalendar = null; });
  SCalendar = markBroken (super.SCalendar.override { scalendar = null; });
```

**Comment by pbogdan** [comment]
@peti as mentioned I have revised that change in https://github.com/NixOS/nixpkgs/pull/33077#issuecomment-353993598. Would you consider that an acceptable solution? I believe that would address your concerns with regards to the usage of standard API's, and keeping our current PR checks working.

**Comment by peti** [comment]
> Even broken packages shouldn't be breaking **evaluation**, I believe.

@vcunat, the package is broken *because* it doesn't evaluate properly. That's the whole point of marking it broken. If it would evaluate, then I would not set `meta.broken = true` for it.

**Comment by peti** [comment]
> What do you think about @pbogdan's other workaround:
> 
> ```
>   scalendar = markBroken (super.scalendar.override { SCalendar = null; });
>   SCalendar = markBroken (super.SCalendar.override { scalendar = null; });
>  ```

@grahamc, yes, this is a much better; I'd be happy with that solution.

> If you think we shouldn't be checking even broken packages to properly eval, we could talk about it?

I do think it's odd to check the status of a package that's been explicitly marked as broken and I cannot easily think of a use-case for that. What kind of issue would the bot detect due to this check that would otherwise go unnoticed?

**Comment by vcunat** [comment]
I don't have a strong opinion on this.  Use case: I think it's not that unreasonable to put `allowBroken = true;` into your config and still expect `nix-env -qa` etc. to work.  To me it feels that "hard" evaluation errors (`abort`, infinite cycle, etc.) should not happen unless you do something *very* wrong.  Throws are "soft" in this sense &ndash; they can be caught, they're filtered from `nix-env -qa`, etc.

**Comment by vcunat** [comment]
> @vcunat, the package is broken *because* it doesn't evaluate properly. That's the whole point of marking it broken. If it would evaluate, then I would not set `meta.broken = true` for it.

There are other possible motivations, e.g. avoid rebuilds for Hydra (or users) that are very likely to fail anyway (think _Zero Hydra Failures_), and for documentation of the state.

**Pull request merged**
