### PR TITLE
srelay: init at 0.4.8b5

### PR DESCRIPTION
**Pull request by Jookia**
Adds srelay, a neat tool for proxying.

### CODE REVIEW

**Comment by fpletz** [comment]
LGTM, but any reason why you packaged 0.4.8b5 instead of the newer 0.4.8b6?

**Comment by Jookia** [comment]
I don't think so. I'll see if I can package 0.4.8b6.

**Comment by Jookia** [comment]
Updated to 0.4.8.b6

**Comment by fpletz** [comment]
Thanks! :beers:

**Pull request merged**
