### PR TITLE
python312Packages.hkdf: drop

### PR DESCRIPTION
**Pull request by pyrox0**
## Description of changes
Part of #326513

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by emilazy — COMMENTED** [review]
An HKDF implementation is probably one of the less concerning cryptography libraries to not be updated for a decade, but I still don’t feel great about this.

`autobahn` only requires it (and `spake2`) optionally for some dead cryptocurrency thing that we should probably drop, but `magic-wormhole` depends on this through `spake2`. It looks like `magic-wormhole` was [removed by Fedora](https://github.com/magic-wormhole/magic-wormhole/pull/468) along with `hkdf` and `spake2` in favour of the Rust version from the same upstream.

I’m going to ask around about this, but it might be better just to drop this if we find the Rust version of Magic Wormhole to be an acceptable replacement.

**Comment by pyrox0** [comment]
> I’m going to ask around about this, but it might be better just to drop this if we find the Rust version of Magic Wormhole to be an acceptable replacement.

Sounds like a plan, I'll make this into a draft till there's a conclusion on that front.

**Comment by emilazy** [comment]
After engaging with upstream, it looks like they’re actively maintaining `spake2` again; the current unstable version has moved off `hkdf` to `cryptography` and also dropped the `six` dependency. We should probably wait for an official release, but it should be possible to drop `hkdf` after that.

**Comment by emilazy** [comment]
The changes to `spake2` were merged, but there’s no release yet; I’ve opened https://github.com/warner/python-spake2/issues/20.

**Comment by emilazy** [comment]
There’s new releases of `spake2` and `magic-wormhole` 🎉

Did you want to handle the bumps and dropping `hkdf` in this PR, or would you prefer I do it? The `xbr` optional dependencies of `autobahn` should definitely be able to go.

**Comment by pyrox0** [comment]
Working on doing those bumps now.

**Comment by emilazy** [comment]
Any progress on this? I’m holding out hope that we can rush the last few packages in the few days before the 24.11 freeze 😅

**Comment by emilazy** [comment]
Actually I misread the release schedule and we have until the 25th to finish the job, so don’t feel unduly rushed!

**Comment by pyrox0** [comment]
Pushed an update, this doesn't evaluate nicely because there's tahoe-lafs build failures, but the exact same check error counts (`(skips=14, expectedFailures=1, failures=41, errors=4342, successes=724)`) appear by building from the master branch, so I know that this PR does not change that. Should probably investigate fixing or marking that package as broken.

**Comment by emilazy** [comment]
Thanks for updating this :) An existing build failure is fine and normal; it’ll be dealt with in Zero Hydra Failures before the 24.11 release soon. Is there anything else blocking this or did you want to undraft?

**Comment by pyrox0** [comment]
Nope, I'll undraft now, I don't see anything else that would be blocking.

**Review by emilazy — APPROVED** [review]
Result of `nixpkgs-review pr 330769` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python312Packages.magic-wormhole-mailbox-server</li>
    <li>python312Packages.magic-wormhole-mailbox-server.dist</li>
    <li>python312Packages.magic-wormhole-transit-relay</li>
    <li>python312Packages.magic-wormhole-transit-relay.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>tahoe-lafs</li>
    <li>tahoe-lafs.dist</li>
    <li>tahoe-lafs.doc</li>
    <li>tahoe-lafs.info</li>
  </ul>
</details>
<details>
  <summary>42 packages built:</summary>
  <ul>
    <li>authentik</li>
    <li>buildbot</li>
    <li>buildbot-full</li>
    <li>buildbot-ui</li>
    <li>buildbot-worker</li>
    <li>buildbot-worker.dist</li>
    <li>buildbot.dist</li>
    <li>gnome-keysign</li>
    <li>gnome-keysign.dist</li>
    <li>magic-wormhole (python312Packages.magic-wormhole)</li>
    <li>magic-wormhole.dist (python312Packages.magic-wormhole.dist)</li>
    <li>paperless-ngx</li>
    <li>python311Packages.autobahn</li>
    <li>python311Packages.autobahn.dist</li>
    <li>python311Packages.channels</li>
    <li>python311Packages.channels-redis</li>
    <li>python311Packages.channels-redis.dist</li>
    <li>python311Packages.channels.dist</li>
    <li>python311Packages.daphne</li>
    <li>python311Packages.daphne.dist</li>
    <li>python311Packages.labgrid</li>
    <li>python311Packages.labgrid.dist</li>
    <li>python311Packages.magic-wormhole</li>
    <li>python311Packages.magic-wormhole-mailbox-server</li>
    <li>python311Packages.magic-wormhole-mailbox-server.dist</li>
    <li>python311Packages.magic-wormhole-transit-relay</li>
    <li>python311Packages.magic-wormhole-transit-relay.dist</li>
    <li>python311Packages.magic-wormhole.dist</li>
    <li>python311Packages.strawberry-graphql</li>
    <li>python311Packages.strawberry-graphql.dist</li>
    <li>python312Packages.autobahn</li>
    <li>python312Packages.autobahn.dist</li>
    <li>python312Packages.channels</li>
    <li>python312Packages.channels-redis</li>
    <li>python312Packages.channels-redis.dist</li>
    <li>python312Packages.channels.dist</li>
    <li>python312Packages.daphne</li>
    <li>python312Packages.daphne.dist</li>
    <li>python312Packages.labgrid</li>
    <li>python312Packages.labgrid.dist</li>
    <li>python312Packages.strawberry-graphql</li>
    <li>python312Packages.strawberry-graphql.dist</li>
  </ul>
</details>

**Pull request merged**
