### PR TITLE
Add gnome shell extensions

### PR DESCRIPTION
**Pull request by aneeshusa**
- [ ] Tested using sandboxing (`nix-build --option build-use-chroot true` or [nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

I'm running Nix on Arch, where Gnome 3.20 has been released, but https://extensions.gnome.org/ is being slow to update these so I wanted to package these extensions via Nix. Right now, I have a shell script that uses nix-build to make links to these in my `~/.local/share/gnome-shell/extensions` folder; in the future, I'm guessing these could be used via nixuser. I wasn't sure about a few things that I want feedback on:
- Is this the right location in the file structure to put these? Most of them work with a bunch of different Gnome3 versions.
-  How should I add these `top-level/all-packages.nix` file? I wasn't sure if they should have a prefix or something.
- @timbertson do you want to be listed as a maintainer for the impatience extension since you wrote it?

### CODE REVIEW

**Comment by timbertson** [comment]
Thanks @aneeshusa,

I agree that we should keep these out of gnome3.x specific directory - most of them work fine on most shell versions.

I don't know about top-level/all-pacakges. Maybe put them all under a `gnome3.shellExtensions` object?

And yep, feel free to add me as an additional maintainer for `impatience`.

**Comment by joachifm** [comment]
cc @lethalman

**Comment by lethalman** [comment]
AFAIK gnome shell extensions hardcode the shell version on which they work right? So I'd put them in gnome3 specific version folder.

**Comment by aneeshusa** [comment]
They have a hardcoded list of versions they work with, but they support many versions at the same time. For example:  https://github.com/timbertson/gnome-shell-impatience/blob/master/impatience/metadata.json

All three of these support at least 3.16, 3.18 and 3.20.

**Comment by aneeshusa** [comment]
Also, there is already a `gnome3.gnome-shell-extensions`, which is a derivation for the built-in official extensions. In order to make the difference between that and `gnome3.shellExtensions` more clear, how about putting these under `gnome3.unofficialShellExtensions` or `gnome3.extraShellExtensions` or `gnome3.moreShellExtensions`?

**Comment by aneeshusa** [comment]
Rebased and updated. I also added another extension that I had forgotten before.

**Comment by aneeshusa** [comment]
Ping on this, I'd love to get these in-tree.

**Comment by zimbatm** [comment]
Thanks !

**Pull request merged**
