### PR TITLE
perl: add comment why enableParallelBuilding is disabled

### PR DESCRIPTION
**Pull request by Atemu**
## Description of changes

Only a partial explanation but it's better to have at least this much in code
such that people don't have to dig it out of old PR comments.

Also fixed a typo in the file name.

cc @magneticflux- 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by magneticflux- — APPROVED** [review]

**Comment by stigtsp** [comment]
To be honest, I feel this change should be reverted to enable parallel builds instead of adding a comment here.

**Comment by magneticflux-** [comment]
I've personally been building it in parallel (on Linux x86), but I haven't tested that in all environments.

**Comment by stigtsp** [comment]
> I've personally been building it in parallel (on Linux x86), but I haven't tested that in all environments.

If you can do a PR against staging reverting to the previous behaviour, I'd be happy to test.

**Comment by Atemu** [comment]
I'd be in favour of having the comment in place until that PR is tested and done because IME that can take a while and is likely to stall.

**Comment by stigtsp** [comment]
Don't think we need to wait more than one staging cycle for this to reach master.

I'm testing `enableParallelBuilding = !crossCompiling`, and will do a PR for it shortly.

**Comment by Gerg-L** [comment]
`perl.overrideAttrs { enableParallelBuild = true; }` works on x86_64-linux with 32 threads so it should definitely be re-enabled at least conditionally

**Comment by stigtsp** [comment]
PR changing the behavior added here:
- https://github.com/NixOS/nixpkgs/pull/292588

@Atemu @magneticflux- Thx for pointing this out.  :)

**Comment by stigtsp** [comment]
@Atemu Want me to add https://github.com/NixOS/nixpkgs/pull/292344/commits/b30d678647b18ea0570becf2428081f079323ae4 to https://github.com/NixOS/nixpkgs/pull/292588 to handle the intepreter->interpreter typo as well?

**Pull request closed without merging**
