### PR TITLE
Package ruby-debug-ide

### PR DESCRIPTION
**Pull request by mbarak**
###### Motivation for this change
Allow ruby devs using Nix to use their preferred IDE to debug their projects. `ruby-debug-ide` is used by VS Code and RubyMine for debugging.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mbarak** [comment]
This is the error I am getting when I try to build
```
mbarak@ruby-debug-ide-dev:~/nixpkgs$ nix-build -I . -A ruby-debug-ide --show-trace 
these derivations will be built:
  /nix/store/qz5d4ag3gxxcdyrk4n5488a2lx8i5zf3-ruby2.6.5-ruby-debug-ide-0.7.0.drv
  /nix/store/4jvldsnnknxshz3fwxwh49rhgw8pj3ij-ruby-debug-ide-0.7.0.drv
  /nix/store/ck76j91x4n0s0s7wv3xcw1414kji1nmn-ruby-debug-ide-0.7.0.drv
building '/nix/store/qz5d4ag3gxxcdyrk4n5488a2lx8i5zf3-ruby2.6.5-ruby-debug-ide-0.7.0.drv'...
unpacking sources
patching sources
configuring
no configure script, doing nothing
installing
buildFlags: 
WARNING:  You build with buildroot.
  Build root: /
  Bin dir: /nix/store/lbm5aw087kk9g05bv1fixj5020frc7rc-ruby2.6.5-ruby-debug-ide-0.7.0/lib/ruby/gems/2.6.0/bin
  Gem home: /nix/store/lbm5aw087kk9g05bv1fixj5020frc7rc-ruby2.6.5-ruby-debug-ide-0.7.0/lib/ruby/gems/2.6.0
Building native extensions. This could take a while...
ERROR:  Error installing /nix/store/xsayw8pjzjiycsfn7wiagrlj7pz62n8s-ruby-debug-ide-0.7.0.gem:
        ERROR: Failed to build gem native extension.

    current directory: /nix/store/lbm5aw087kk9g05bv1fixj5020frc7rc-ruby2.6.5-ruby-debug-ide-0.7.0/lib/ruby/gems/2.6.0/gems/ruby-debug-ide-0.7.0/ext
/nix/store/a3wafb77xrn5wcz21sxg8l40kdlm2wny-ruby-2.6.5/bin/ruby mkrf_conf.rb
NOTE: Gem::DependencyInstaller#find_gems_with_sources is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::DependencyInstaller#find_gems_with_sources called from mkrf_conf.rb:6.
NOTE: Gem::DependencyInstaller#find_gems_with_sources is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::DependencyInstaller#find_gems_with_sources called from mkrf_conf.rb:7.
Installing base gem
Unable to resolve dependency: user requested 'debase (> 0)'
/nix/store/a3wafb77xrn5wcz21sxg8l40kdlm2wny-ruby-2.6.5/lib/ruby/2.6.0/rubygems/resolver/installer_set.rb:72:in `add_always_install'
  /nix/store/a3wafb77xrn5wcz21sxg8l40kdlm2wny-ruby-2.6.5/lib/ruby/2.6.0/rubygems/dependency_installer.rb:394:in `resolve_dependencies'
  /nix/store/a3wafb77xrn5wcz21sxg8l40kdlm2wny-ruby-2.6.5/lib/ruby/2.6.0/rubygems/dependency_installer.rb:301:in `install'
  mkrf_conf.rb:36:in `rescue in <main>'
  mkrf_conf.rb:29:in `<main>'

rake failed, exit code 1

Gem files will remain installed in /nix/store/lbm5aw087kk9g05bv1fixj5020frc7rc-ruby2.6.5-ruby-debug-ide-0.7.0/lib/ruby/gems/2.6.0/gems/ruby-debug-ide-0.7.0 for inspection.
Results logged to /nix/store/lbm5aw087kk9g05bv1fixj5020frc7rc-ruby2.6.5-ruby-debug-ide-0.7.0/lib/ruby/gems/2.6.0/extensions/x86_64-linux/2.6.0/ruby-debug-ide-0.7.0/gem_make.out
builder for '/nix/store/qz5d4ag3gxxcdyrk4n5488a2lx8i5zf3-ruby2.6.5-ruby-debug-ide-0.7.0.drv' failed with exit code 1
cannot build derivation '/nix/store/4jvldsnnknxshz3fwxwh49rhgw8pj3ij-ruby-debug-ide-0.7.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/ck76j91x4n0s0s7wv3xcw1414kji1nmn-ruby-debug-ide-0.7.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/ck76j91x4n0s0s7wv3xcw1414kji1nmn-ruby-debug-ide-0.7.0.drv' failed
```

**Comment by deliciouslytyped** [comment]
Why does it fail to build the native extension? Is there an error message for that somehow?

**Comment by zimbatm** [comment]
The issue is that the `ruby-debug-ide` gem doesn't have an explicit dependency on `debase`, which means that it doesn't become available at build time. Try patching the dependency tree manually to see if it fixes the error.

**Comment by mbarak** [comment]
> Try patching the dependency tree manually to see if it fixes the error.
I tried using a local version of `ruby-debug-ide` where I explicitely set `debase` as a dependency in the `Gemfile`. That didn't work.
Do you have anything else I could try?

Also, it seems like `ruby-debug-ide` tries to install its dependency twice: once with a `Gemfile` and once in `mkrb_conf.rb` here:
https://github.com/ruby-debug/ruby-debug-ide/blob/master/ext/mkrf_conf.rb#L31

This might be part of the issue.

**Comment by zimbatm** [comment]
Indeed. `debase` probably needs to be added to the `ruby-debug-ide` buildInputs. This scenario is not super well supported. Basically you want package debase, then inject it back into the bundlerApp useing the gemConfig attribute.

```
{ bundlerApp, defaultGemConfig
, debase // Packaged separately.
}:
bundlerApp {
  gemConfig = defaultGemConfig // {
    ruby-debug-ide = attrs: {
      buildInputs = [ debase ];
    };
  };
}
```

**Comment by mbarak** [comment]
I added debase to the default set of gems by adding it to the gemfile in
with-packages. I managed to import it in a ruby repl.

Does that affect your suggestion?

**Comment by mbarak** [comment]
Since I added `debase` to the default set of gems I tried doing this in `pkgs/development/ruby-modules/gem-config/default.nix`

```nix
  ruby-debug-ide = attrs: {
    buildInputs = [ ruby.gems.debase ];
  };
```

That still didn't work...

**Comment by mbarak** [comment]
Another question, how do I set an environment variable before the build?

I tried doing this:
```
bundlerApp { <snipped> } // { NO_EXT=true }
```
I tried doing this
```
bundlerApp {
...

  preBuild = ''
    export NO_EXT=1
  '';
  postBuild = ''
    export NO_EXT=1
  '';
...
}
```
(i added a `preBuild` step locally just for this)

**Comment by deliciouslytyped** [comment]
The fastest way until someone replies might be to start digging down into the source of bundlerApp. If it's mkDerivation based, then any extra variables you set in the arguments of bundlerApp should be passed as environment variables. I guess this might be easier to test empirically than to dig in the source.

Furthermore, I think function application binds stronger than `//`, so you're actually merging in the "environment variable" to the result of the function application, which is not what you want.

You can play in `nix repl` to see whats going on:
```
nix-repl> let f = {...}@args: { inherit args; }; in f ({c = 1;} // { d = 2; }) 
{ args = { ... }; }

nix-repl> let f = {...}@args: { inherit args; }; in (f {c = 1;}) // { d = 2; }
{ args = { ... }; d = 2; }

nix-repl> let f = {...}@args: { inherit args; }; in f {c = 1;} // { d = 2; }   
{ args = { ... }; d = 2; }
```

**Comment by mbarak** [comment]
I've been reading a lot of the internal code to figure things out.
`bundlerApp` uses `runCommand` from `trivial-builders` which uses the `stdenv`.
Unfortunately, `bundlerApp` doesn't support passing arbitrary values down to `mkDerivation`. That's why I tried `//` on the results of the `bundlerApp` call.

Thanks for the hint re `nix repl`. I didn't know that existed!

**Comment by deliciouslytyped** [comment]
I'm not 100% sure about this but it looks like `passthru` is merged into cmdArgs? 
https://github.com/NixOS/nixpkgs/blob/ab2d5c286c57dd9d5c373db9fe910bb9bbddff53/pkgs/development/ruby-modules/bundler-app/default.nix#L48
So it looks like you should be able to pass it in there through to runCommand's arguments?

**Comment by deliciouslytyped** [comment]
Hmm, yeah, as far as I can tell it looks like you're right. I'm not sure why it's like that. Maybe there's another way, or its due for a fix :)

**Comment by deliciouslytyped** [comment]
Actually, can you `.overrideAttrs` it?

**Comment by mbarak** [comment]
I tried that, no luck.
Is there a way to confirm that the environment variable got applied?
I don't know if `NO_EXT` will work. I'm trying it because based on reading the code of `ruby-debug-ide` it might work.

**Comment by deliciouslytyped** [comment]
Well, you can inspect the resulting derivation with `nix show-derivation` or you can try printing it with a pre or a post phase or somesuch.

`show-derivation` will take an output path as an argument, you don't have to figure out the `.drv` (though you can just get it from nix repl)

- I think.

**Pull request closed without merging**
