### PR TITLE
cargo,clippy,rustc,rustfmt: 1.79.0 -> 1.80.0

### PR DESCRIPTION
**Pull request by theoparis**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by theoparis** [comment]
I attempted to build this on x86_64-linux to test it locally and ran into 
```
rustc> Caused by:
rustc>     0: failed to tar file '/build/rustc-1.80.0-src/build/tmp/tarball/rustc-dev/x86_64-unknown-linux-gnu/rustc-dev-1.80.0-x86_64-unknown-linux-gnu/rustc-dev/lib/rustlib/x86_64-unknown-linux-gnu/lib/libzerovec_derive-8b341a0bb2416fc9.so'
rustc>     1: No space left on device (os error 28)
```

**Comment by alyssais** [comment]
We need to be very careful here, because Rust 1.80.0 contains a major unfixable compilation [regression](https://github.com/rust-lang/rust/issues/127343) that affects all but recent versions of the widely-used "time" crate.  (Trying to assess the damage here is what's delayed me opening my own PR.)

So at the very least, this PR needs to cherry-pick the other commits from my rust-1.80.0 branch, which update some channel blockers to be able to compile with 1.80.0.  I think once we're confident that the channel blockers are taken care of, we can merge this into staging, because going by the fact it generally only takes a couple of weeks to start seeing packages blocked by it, people also rely on Nixpkgs having an up to date Rust, but there's going to be a very long tail of build regressions (potentially hundreds) that we'll have to be on the look out for.  Hopefully we can identify and fix a bunch of them in advance of this making it into master.

**Comment by alyssais** [comment]
Actually, it's probably easier if I just open a separate PR to fix the channel blockers, and we merge it before this one: https://github.com/NixOS/nixpkgs/pull/332176

**Comment by alyssais** [comment]
I've built Firefox and Thunderbird on both x86_64-linux and aarch64-linux previously with my own version of the upgrade, which should be identical.

Still need fd to be tested on both Darwins.

**Comment by zowoq** [comment]
> Still need fd to be tested on both Darwins.

Done.

**Review by alyssais — APPROVED** [review]

**Comment by theoparis** [comment]
> @theoparis anything keeping this as a draft?

I didn't realize your PR was merged already. I can't seem to resolve the conflicts.

**Comment by alyssais** [comment]
@theoparis check the box to allow me to push to your branch and I'll do it.

**Comment by alyssais** [comment]
Let's wait until nsncd is [fixed properly](https://github.com/NixOS/nixpkgs/pull/332176#issuecomment-2270810662) and then merge this.

**Comment by alyssais** [comment]
wezterm from passthru.tests is failing.  I don't think this is a blocker.  It's sadly just one of lots of packages that maintainers will have to get updated to build with 1.80.0, and we can't hold back indefinitely until they're all fixed, because in the meantime other packages will start requiring the new Rust version.  I will be putting together a list of packages I know are affected and pinging maintainers, so they'll have a chance to get their packages fixed.  (cc @SuperSandro2000 who added it to passthru.tests)

**Comment by SuperSandro2000** [comment]
That's just the all-terminfo test which is not directly related to wezterm alone.

**Pull request merged**
