### PR TITLE
gitlab: 15.4.2 -> 15.5.0

### PR DESCRIPTION
**Pull request by winterqt**
###### Description of changes

This is mainly here to collect my attempts at getting this to work.

This looks like it'll require some... cursed hacks, since `attr_encrypted` is a dependency of other gems, so bundix doesn't ignore it entirely even if we patch it out of both the `Gemset` and `Gemset.lock` files. For now, I've manually edited it out (which is enough to get it to eval), to see how CI goes.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by winterqt** [comment]
There seems to be two main issues after skimming the logs:

1. Gitaly now requires libgit2 v1.5.0, and we currently pin it to v1.3.0. Easy fix.
2. `Could not find omniauth-google-oauth2-1.1.1 in locally installed gems`: looks like the vendored gems list was changed more than I thought, I'll fix it.

Hopefully everything's green after these fixes, and we just have to deal with the Gemfile modification stuff I mentioned initially.

**Comment by winterqt** [comment]
Oops, forgot to test eval that time, and forgot an edit. Will fix later.

**Review by yayayayaka — COMMENTED** [review]
Thanks for trying to fix the `attr_encrypted` dependency issue. :heart: 

I think the `update-pg.patch` can be removed again since they have bumped that dependency to 1.4.3.

**Comment by winterqt** [comment]
> I think the `update-pg.patch` can be removed again since they have bumped that dependency to 1.4.3.

Correct -- guess I didn't notice the warning about it in my logs, somehow.

**Comment by winterqt** [comment]
Tests are green, so this is ready for testing, but I still need to fix the gemset thing properly so this manual edit doesn't need to be made every time...

**Pull request closed without merging**
