### PR TITLE
[20.09] Backport ZFS update in preparation for 5.10 bump

### PR DESCRIPTION
**Pull request by Atemu**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/pull/108609#pullrequestreview-564855240

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Atemu** [comment]
nixosTests.zfs.unstable is failing for some reason, it seems like boot.zfs.enableUnstable which the test uses has no effect? O.o

**Comment by NeQuissimus** [comment]
@ofborg test zfs.unstable

**Comment by NeQuissimus** [comment]
@Atemu The test passes for me locally:

```
nixpkgs on  pr-108944 λ nix-build ./nixos/release.nix -A tests.zfs.unstable.x86_64-linux
...
machine # [   19.117462] dhcpcd[990]: eth0: adding default route via fe80::2
machine # [   19.362872] zed[991]: eid=1 class=pool_create pool='rpool'
machine # [   20.059297] zed[1044]: eid=2 class=history_event pool='rpool'
machine # [   20.085840] zed[664]: Missed 1 events
(1.78 seconds)
machine: must succeed: zfs create -o mountpoint=legacy rpool/root
(0.26 seconds)
machine: must succeed: mount -t zfs rpool/root /tmp/mnt
(0.07 seconds)
machine: must succeed: udevadm settle
(0.08 seconds)
machine: must succeed: umount /tmp/mnt
machine # [   20.600575] systemd[1]: tmp-mnt.mount: Succeeded.
(0.08 seconds)
machine: must succeed: zpool destroy rpool
machine # [   20.726437] systemd[1]: tmp-mnt-rpool.mount: Succeeded.
(0.20 seconds)
machine: must succeed: udevadm settle
(0.07 seconds)
(23.30 seconds)
test script finished in 23.35s
cleaning up
killing machine (pid 6)
(0.00 seconds)
/nix/store/gysai8sqhlyx07wy0syd6va1y7a4jbbh-vm-test-run-zfs-unstable

nixpkgs on  pr-108944 took 16m 39s λ echo $?
0
```

**Review by NeQuissimus — APPROVED** [review]

**Comment by Atemu** [comment]
Did you merge your kernel bump locally too? The zfsStable it (erroneously) uses is still compatible with the current _latest = 5.9.

Does the test use 0.8.6 or 2.0.1 on your machine? (grep the log, ZFS prints its version)

**Comment by NeQuissimus** [comment]
@Atemu I misunderstood. I thought this PR alone would break the test. Let me see...

**Comment by NeQuissimus** [comment]
I see what you mean. It seems there is an issue with how the test is evaluated. Regardless of `enableUnstable`, Nix tries to pull in `zfsStable`

**Comment by hmenke** [comment]
@Atemu Can you post the error message?  I actually don't see why it should fail here.  The userspace tool in the system environment should be the one from unstable as well.

**Comment by NeQuissimus** [comment]
From what I can tell (I am running zfsUnstable for my root), the user space tools are indeed 2.0.x. However, part of the issue is that the stable tools are still evaluated, which causes errors from the assertions when `nixos-rebuild boot`.

**Review by jonringer — APPROVED** [review]
LGTM, as this is effectively just bumping the unstable version from 2.0.0 to 2.0.1

future facing, we may want to leverage my `kernelOlder` and `kernelAtLeast` function to determine the compatible range. The current logic of specifying only one version seems very limited.

**Comment by lheckemann** [comment]
Hm, now it's duplicated across release-20.09 (this PR) and staging-20.09 (c0216833f23c756615995e6d3b1af40bfae05904). But I guess that won't be a problem, since they're the same thing.

**Pull request merged**
