### PR TITLE
Linux kernels 2024-01-29

### PR DESCRIPTION
**Pull request by alyssais**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by alyssais** [comment]
@OfBorg test kernel-generic.linux_testing

**Comment by Ma27** [comment]
No plans from my side. Also, won't be able to test it for now I'm afraid since I'm still on zfs 2.1 and it seems as if I can't go beyond 6.5 for now.

**Comment by RaitoBezarius** [comment]
> No plans from my side. Also, won't be able to test it for now I'm afraid since I'm still on zfs 2.1 and it seems as if I can't go beyond 6.5 for now.

ZFS 2.1 can go beyond 6.5, but I didn't upstream the patches for that yet, upstream has them for 2.2 series but no one bothered backporting them to 2.1 series. My production is running on 6.7 just fine.

**Comment by vcunat** [comment]
Oh, I guess it makes sense to wait for ZFS to support it, at least if it happens within a couple months.

**Comment by RaitoBezarius** [comment]
No, there's no need to block on ZFS upstream.

**Comment by Ma27** [comment]
> Oh, I guess it makes sense to wait for ZFS to support it, at least if it happens within a couple months.

I only wanted to state that I likely won't be able to participate in testing before bumping the default (as it was the case on 5.15 -> 6.1 at least).

**Comment by RaitoBezarius** [comment]
> Next stable ZFS 2.1.x and 2.2.x will support it. ([openzfs/zfs#15761](https://github.com/openzfs/zfs/pull/15761), [openzfs/zfs#15748](https://github.com/openzfs/zfs/pull/15748)), so given that I'm inclined to wait a little bit.

This gives only the support for the aarch64 SIMD operations, there's a bunch of work to do for 6.7 because of various changes in the API: here's a public list of patches for it https://github.com/NixOS/nixpkgs/pull/271703.

**Comment by alyssais** [comment]
> This gives only the support for the aarch64 SIMD operations, there's a bunch of work to do for 6.7 because of various changes in the API: here's a public list of patches for it #271703.

But we're talking about 6.6, the LTS.

**Comment by RaitoBezarius** [comment]
> > This gives only the support for the aarch64 SIMD operations, there's a bunch of work to do for 6.7 because of various changes in the API: here's a public list of patches for it #271703.
> 
> But we're talking about 6.6, the LTS.

Apologies… I confused things.

**Pull request merged**
