### PR TITLE
ulauncher: patchShebangs and do not double wrap

### LINKED ISSUE #136784: ulauncher: ulauncher-toggle shebang broken
### Describe the bug
the ulauncher-toggle script fails with
```
/run/current-system/sw/bin/ulauncher-toggle: /nix/store/gzmwv093622ilx03l1q2dkhj07b2jzma-ulauncher-5.9.0/bin/.ulauncher-toggle-wrapped: /usr/bin/sh: bad interpreter: No such file or directory
```

The script just seems to be missing the fix shebang step.

ulauncher is installed globally.

### Steps To Reproduce
1. run ulauncher-toggle

### Expected behavior
The script should run.

### Notify maintainers

@aaronjanse 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.45, NixOS, 21.05.1268.21b696caf39 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.05.1268.21b696caf39"`
 - channels(clemens): `"nixos-20.09.3732.91b77fe6942, unstable-21.05pre279456.04a2b269d89"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by Artturin**
###### Motivation for this change
Closes #136784

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Nervengift** [comment]
could the double wrapping also be the problem in #135936?

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 137056` at 7df8ba40 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>ulauncher</li>
  </ul>
</details>
<details>
  <summary>3 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/applications/misc/ulauncher/default.nix:75:5:
```
   |
75 |     ./fix-extensions.patch
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/applications/misc/ulauncher/default.nix:73:5:
```
   |
73 |     ./fix-path.patch
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/applications/misc/ulauncher/default.nix:74:5:
```
   |
74 |     ./0001-Adjust-get_data_path-for-NixOS.patch
   |     ^
```
</li>
  </ul>
</details>

**Comment by Artturin** [comment]
> could the double wrapping also be the problem in #135936?

I can't reproduce it before this pr or after it
Merging this and closing that issue
Mention me in the issue if the issue still persists @feijoas

**Comment by Nervengift** [comment]
thanks so much!
Can confirm this fixes both ulauncher-toggle and #135936

**Pull request merged**
