### PR TITLE
Thunderbird: Fix default mail client detection

### PR DESCRIPTION
**Pull request by layus**
###### Motivation for this change

fix regression from https://github.com/NixOS/nixpkgs/commit/b023370f3757a76acb244e647f29e388e076cab0, and default mail reader detection (see also #23516)

###### Things done

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - macOS
   - Linux
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

/cc @abbradar

### CODE REVIEW

**Comment by layus** [comment]
Ooops, found a bug in the meantime. it would be simpler to enforce gtk3 to get only one build to test.

**Review by abbradar — COMMENTED** [review]
From the bird's view the fix seems hacky to me. However this may very well be the best way to do this and I have a very little time to confirm. So, unless I'll have some in several days I'm okay with this merged as is.

**Comment by layus** [comment]
It is hacky because 
1. we do not want to use wrapProgram (which wrapGAppsHook uses), because it would wrap a symlink, leading to one extra useless resolve step.
2. it allows to factorize the code for gtk3 & wrapGAppsHook and gtk2 (without the hook) into one execution flow.

**Comment by abbradar** [comment]
Tested; it works for me. Thanks for this and for restoring features which I accidentially removed!

**Comment by layus** [comment]
Thanks for reviewing :-).

**Pull request merged**
