### PR TITLE
R: update CRAN package set

### PR DESCRIPTION
**Pull request by jabranham**
###### Motivation for this change
Update CRAN snapshot

###### Things done

Following instructions in `doc/languages-frameworks/r.section.md`:

```
$ cd pkgs/development/r-modules
$ nix-shell generate-shell.nix
$ Rscript generate-r-packages.R cran  > cran-packages.nix.new
$ mv cran-packages.nix.new cran-packages.nix
$ nix-build test-evaluation.nix --dry-run
```

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peti** [comment]
Pushed de589cd1ce8185910c927034fa774ebf4c2dce75 to `r-updates`  for test building at https://hydra.nixos.org/jobset/nixpkgs/r-updates.

**Comment by jabranham** [comment]
Looks like hydra finished. Do I need to investigate those three failures more closely?

Also, since hydra is building the packages anyway, is there a way we can enable substitutions for R packages so users don't have to rebuild from source? If storage space is a concern, we could just do it for a small whitelist. Some popular packages (Rcpp, dplyr, etc) take a decent amount of time to build locally, especially on older laptops.

**Comment by Mic92** [comment]
The substitution should already happen when hydra is building the packages.

**Comment by jabranham** [comment]
@Mic92 I don't think I've ever had any R package substituted. And as far as I know I'm not doing anything that would require them to be rebuilt.

**Comment by peti** [comment]
> I don't think I've ever had any R package substituted.

R packages aren't usually built by Hydra.

**Comment by jabranham** [comment]
@peti Thanks. My question was though whether it's possible to enable that, at least for a subset of R packages. Some are very popular (Rcpp, dplyr, etc) and take a while to build locally. Other distros (e.g. Debian) do offer a subset of CRAN packages as binaries.

**Comment by peti** [comment]
I don't know. We used to build `rPackages` but had to disable that a while ago because the sheer number of packages overloaded Hydra's evaluator. It's possible that problem would still exist today, but I am not in a position to tell with any authority. We could probably build a subset without any problems ... but that poses the question of what that subset would be? Who defines that?

Personally, I don't feel stronly about any of this, to be honest. I compile my R packages locally and it seems to be no big deal. Maybe I'm just lucky with my choice of dependencies, though. Who knows.

**Comment by jabranham** [comment]
Sure, that makes sense. 

I don't think it would be very hard to come up with a reasonable whitelist. Perhaps the tidyverse + the X number of packages that have the highest number of reverse dependencies? Perhaps a few select others too based on the amount of compile time? `rstan` is one package (for me) that is annoying to compile locally because of the amount of time it takes.

**Pull request merged**
