### PR TITLE
binutils: 2.35.1 -> 2.38

### PR DESCRIPTION
**Pull request by lovesegfault**
###### Motivation for this change
Hello binutils, my old friend
I've come to bump you again
Because a version softly creeping
Left its bugs while I was sleeping
And the patches that were planted in my brain
Still remains
Within the source of binutils

See also: #134916
See also: #118945

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
Oh, I see that the 2.36.1 PR was kind of left behind.  So you want to try the relatively new 2.37 directly?  Some others [have adopted](https://repology.org/project/binutils/history) it already, so perhaps it might be safe enough.  I see nothing risky in the announcement: https://sourceware.org/pipermail/binutils/2021-July/117384.html

I reconfigured the previous jobset: https://hydra.nixos.org/jobset/nixpkgs/binutils-2.36

**Comment by Ma27** [comment]
FYI Fedora uses both bintuils 2.37 and glibc 2.34 (https://fedoraproject.org/wiki/Changes/GNUToolchainF35, https://github.com/NixOS/nixpkgs/pull/133431).

Since I had some very weird linker errors with glibc 2.34 (haven't taken a closer look yet due to time constraints), bintuils 2.37 **may** be  needed to make it work properly :)

**Comment by vcunat** [comment]
Yes, but e.g. that Fedora 35 will be released in October, so I can't see a guarantee that basically all (our) packages will work well now (or have patches available already).

**Comment by Ma27** [comment]
You're right, but I don't expect us to get ready with this (especially bintuils considering the last attempts) noticeably faster :)

**Comment by lovesegfault** [comment]
Most failures seem to be due to `libbfd` which has a broken patch. Investigating.

**Comment by lovesegfault** [comment]
The now-broken patch: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/misc/binutils/build-components-separately.patch

Looking at the source updating the patch is non-trivial, it'd be nice to have some help.

cc. @luc65r @Ericson2314

**Comment by lovesegfault** [comment]
Seems like there are more failures: 

https://hydra.nixos.org/build/150347265/nixlog/1/tail

Which is caused by:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=981072

It seems that will need manual patching to replace `ar clq` with `ar cl`.

**Comment by TredwellGit** [comment]
See https://github.com/NixOS/nixpkgs/pull/118945/files for some fixes.

**Comment by lovesegfault** [comment]
r

> See https://github.com/NixOS/nixpkgs/pull/118945/files for some fixes.

Awesome, incorporated those fixes.

Can you explain this patch? https://github.com/NixOS/nixpkgs/pull/134917/commits/8d0b634e0a0d5b6668b5bd447b3feffcd2da9399

I took it from the branch just in case, but not sure why it's needed

**Comment by lovesegfault** [comment]
Rebased on top of b5398f404ce3e5824ada9e1416be55e3f78b4385 / [eval 1698102](https://hydra.nixos.org/eval/1698102) and started [eval 1698198](https://hydra.nixos.org/eval/1698198).

Here's the comparison of both: https://hydra.nixos.org/eval/1698198?compare=1698102

**Comment by lovesegfault** [comment]
@GrahamcOfBorg eval

**Comment by lovesegfault** [comment]
Alright, some of the last remaining failures are due to `libopcodes` build being broken, something's wrong with the new patch. I'm investigating.

**Comment by lovesegfault** [comment]
> Alright, some of the last remaining failures are due to `libopcodes` build being broken, something's wrong with the new patch. I'm investigating.

And fixed!

Jobset: https://hydra.nixos.org/eval/1698252

Base Comparison: https://hydra.nixos.org/eval/1698252?compare=1698102

**Comment by lovesegfault** [comment]
`qtwebengine` is the next main culprit. I think we're affected by this: https://sourceware.org/bugzilla/show_bug.cgi?id=28138

**Comment by lovesegfault** [comment]
Let's see: https://hydra.nixos.org/eval/1698327

**Review by SuperSandro2000 — COMMENTED** [review]
We should use substituteInPlace instead of sed to get a warning if something no longer matches.

**Comment by lovesegfault** [comment]
Hydra is being slow as molasses, but I've verified locally the [patch in bugzilla][1] solves our problems with `qtwebengine`.

[1]: https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;h=1c611b40e6bfc8029bff7696814330b5bc0ee5c0

**Comment by lovesegfault** [comment]
> We should use substituteInPlace instead of sed to get a warning if something no longer matches.

Alright, made it use `substituteInPlace` everywhere.

**Comment by SuperSandro2000** [comment]
@lovesegfault do you have a rough idea how many more packages need the fix you applied now at multiple places already? Maybe we should think about a universal solution instead of fixing individual packages if there are many (100+?) more?

**Comment by misuzu** [comment]
This change breaks cross-compiling `gcc` from `aarch64` to `armv7l` (tried `nix-build -A pkgs.pkgsCross.armv7l-hf-multiplatform.stdenv` on `aarch64` host), see [gcc.log](https://github.com/NixOS/nixpkgs/files/7032247/gcc.log).
`x86_64` -> `armv7l` and `x86_64` -> `aarch64` is working fine.

**Comment by lovesegfault** [comment]
> This change breaks cross-compiling `gcc` from `aarch64` to `armv7l` (tried `nix-build -A pkgs.pkgsCross.armv7l-hf-multiplatform.stdenv` on `aarch64` host), see [gcc.log](https://github.com/NixOS/nixpkgs/files/7032247/gcc.log).
> `x86_64` -> `armv7l` and `x86_64` -> `aarch64` is working fine.

I can't reproduce, on commit `2ab7fa56b0afc689d122dea6c40f6fc53757ee71` I can successfully build `/nix/store/6iikrl8h2k84ig7lr1qz3s5qph4nmdgf-stdenv-linux`.

```
[lovesegfault@aarch64:~/nixpkgs]$ git rev-parse HEAD
2ab7fa56b0afc689d122dea6c40f6fc53757ee71

[lovesegfault@aarch64:~/nixpkgs]$ uname -a
Linux aarch64.nixos.community 5.10.57 #1-NixOS SMP Sun Aug 8 07:05:24 UTC 2021 aarch64 GNU/Linux

[lovesegfault@aarch64:~/nixpkgs]$ nix-build -A pkgsCross.armv7l-hf-multiplatform.stdenv
/nix/store/6iikrl8h2k84ig7lr1qz3s5qph4nmdgf-stdenv-linux
```

**Comment by misuzu** [comment]
> I can't reproduce, on commit `2ab7fa56b0afc689d122dea6c40f6fc53757ee71` I can successfully build `/nix/store/6iikrl8h2k84ig7lr1qz3s5qph4nmdgf-stdenv-linux`.

That's weird, it consistently fails on my machine. Maybe I'm doing something wrong.

```
$ nix-build -A pkgsCross.armv7l-hf-multiplatform.stdenv # after gc'ing the nix store
<...........................................................>
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
make[3]: *** [../../gcc-9.3.0/gcc/cp/Make-lang.in:120: cc1plus] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [../../gcc-9.3.0/gcc/c/Make-lang.in:85: cc1] Error 1
collect2: error: ld returned 1 exit status
make[3]: *** [../../gcc-9.3.0/gcc/lto/Make-lang.in:81: lto1] Error 1
rm gcc.pod
make[3]: Leaving directory '/build/build/gcc'
make[2]: *** [Makefile:4707: all-stage2-gcc] Error 2
make[2]: Leaving directory '/build/build'
make[1]: *** [Makefile:22242: stage2-bubble] Error 2
make[1]: Leaving directory '/build/build'
make: *** [Makefile:22446: bootstrap] Error 2
builder for '/nix/store/k6piyjw0ryh0wmfwrgc8r548phlvwdgm-gcc-9.3.0.drv' failed with exit code 2
cannot build derivation '/nix/store/chdwab7x1d1zlg9asf27k0174l15jgbw-bootstrap-stage4-gcc-wrapper-9.3.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/653y3zrg5xd67knp0xamffzyvwlr7q9b-gcc-wrapper-9.3.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/4j7as25f1rwpny8wkndbggqpdxc4rhia-perl-5.34.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/jms2wkkqvxv258adcxxw1jv4n32fkpy7-perl-5.34.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/vaza9mpcxbzd0m06s75h75v58sr029gx-stdenv-linux.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/yw8ls0zscvh8v6csl7h22h6rzf6v9c8n-stdenv-linux.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/nxy4vaww4zwvnw1h7zz1kim4mcfw2xjs-armv7l-unknown-linux-gnueabihf-stage-final-gcc-debug-wrapper-10.3.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/nyv9ayrqkkld1rabpx3hnnvm96b2zhbx-bash-4.4-p23.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/iracvcm410920qa09sxa9rxfil4yzymr-bootstrap-stage4-stdenv-linux.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/avlx417zgbbf713lfly6k0hrgrv1yxxk-help2man-1.48.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/d2il4s3jbg2l9nzdhq3id2bh31a27lnl-stdenv-linux.drv': 1 dependencies couldn't be built
error: build of '/nix/store/d2il4s3jbg2l9nzdhq3id2bh31a27lnl-stdenv-linux.drv' failed
$ git status
On branch binutils-2.37
Your branch is up to date with 'origin/binutils-2.37'.

nothing to commit, working tree clean
$ git rev-parse HEAD
2ab7fa56b0afc689d122dea6c40f6fc53757ee71
$ uname -a
Linux aarch64-builder 5.10.50 #1-NixOS SMP Wed Jul 14 14:56:55 UTC 2021 aarch64 GNU/Linux
$ nix-build --version
nix-build (Nix) 2.3.15
```

**Comment by vcunat** [comment]
Could you be e.g. running out of memory at that point?  (sometimes such errors aren't reported well)

**Comment by misuzu** [comment]
> Could you be e.g. running out of memory at that point? (sometimes such errors aren't reported well in the log)

It's 4 core/8G RAM VM, so it should be enough, but I'll try again with `-j1 --cores 1`, thanks!

**Comment by vcunat** [comment]
From my experience 8G with `--cores 4` will be risky for some big builds (e.g. Firefox and I suspect gcc as well), even though it's plenty for most cases.

**Comment by misuzu** [comment]
> From my experience 8G with `--cores 4` will be risky for some big builds (e.g. Firefox and I suspect gcc as well), even though it's plenty for most cases (e.g. `linux`).

`--cores 1` did the trick.

**Comment by lovesegfault** [comment]
> > From my experience 8G with `--cores 4` will be risky for some big builds (e.g. Firefox and I suspect gcc as well), even though it's plenty for most cases (e.g. `linux`).
> 
> 
> 
> `--cores 1` did the trick.

Thank the lord, if I had to debug a cross-cc breakage it'd push me over the edge of sanity!

**Comment by lovesegfault** [comment]
Rebased on top of 3bd130c09f844ddd7942ea177bc4f5af7566d244 / https://hydra.nixos.org/eval/1702999

**Comment by vcunat** [comment]
Right now the only other big consumer of x86_64-linux is the glibc-2.34 jobset, which is in a similar position I expect, so I don't know about their relative priorities... but aarch64-linux seems quite free.

**Comment by Ma27** [comment]
> Right now the only other big consumer of x86_64-linux is the glibc-2.34 jobset, which is in a similar position I expect, so I don't know about their relative priorities... but aarch64-linux seems quite free (and I expect most of the issues to be the same as on x86_64).

Feel free to prioritize binutils. Apart from me being busy I doubt that I'd finish this until freeze since some breaking changes have higher impact that affects quite a number of packages (most notably `SIGSTKSZ` not being const anymore).

**Comment by Ma27** [comment]
At least with glibc this is regularly the case. Not sure about binutils though.

**Comment by eddyb** [comment]
As an extra data-point, I just found this PR because I would need `binutils 2.36` or later to get [Rust (`v0`) demangling](https://github.com/rust-lang/rust/issues/60705) support in e.g. `perf`.

Seems like this could take a while, so I'll probably try to find a low-rebuild-overhead local workaround, instead, if I can.

**Comment by trofi** [comment]
I pushed a few fixes into master to shrink this branch size a bit:
- 1923c51c0ae cdesktopenv: fix build on upcoming binutils-2.36 (#146750)
- 1561c366ab9 libAfterImage: fix binutils-2.36 compatibility (#147617)
- d793cbc4aa4 nx-libs: fix build on upcoming binutils-2.36
- 5da59495a3a afterstep: fix build on upcoming binutils-2.36

One more PR is in flight:
- [ ] https://github.com/NixOS/nixpkgs/pull/146927

Worth rebasing this PR against some recent state? I could try to chip at a few more failures. They don't seem to be numerous.

**Comment by lovesegfault** [comment]
Kicked off a new eval: https://hydra.nixos.org/eval/1743271

If it looks good I might try bundling 2.38 in here, there are almost no changes from 2.37 to 2.38 AFAICT.

**Comment by lovesegfault** [comment]
Rebased on master, kicking off a final eval. This is looking good :)

**Comment by lovesegfault** [comment]
Alright, the eval looks great. I'm going to rebase this on staging and merge it.

**Comment by lovesegfault** [comment]
Seems like there are some lingering issues for Darwin. I cannot test those.

**Comment by lovesegfault** [comment]
Well, let's see what ofborg says now

**Comment by lovesegfault** [comment]
Yup, this is broken on Darwin, and therefore breaks the Darwin stdenv.

I do not own hardware to test it there, I'd be nice if someone stepped up to help :)

**Comment by r-burns** [comment]
cc @NixOS/darwin-maintainers

**Comment by thefloweringash** [comment]
From a quick investigation, it looks like the cause is in a [binutils local patch](https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;h=bef9ef8ca0f941d743c77cc55b5fe7985990b2a7) to nm detection in libtool.m4. Which incorrectly concludes that `nm` requires `-B`, which is not correct. This propagates through the configure phase until it causes `$global_symbpol_pipe` to be empty, which then lands up producing an invalid pipeline from `... | $global_symbol_pipe | ...`

The upstream patch attempts to determine if a flag is valid for a given nm by passing the flag and an arbitrary binary to nm, and if the result includes the name of the arbitrary binary as the first line of output, then nm succeeded. However, the patch choses nm itself as the arbitrary binary. So if nm were to print its own path as part of its error message, the check would incorrectly pass. This seems to be the case for binutils and cctools:

```
❯ /nix/store/h19zwlkrp6b0hp3ypbqdcggnyarn3af6-binutils-2.35.2/bin/nm -Z /nix/store/h19zwlkrp6b0hp3ypbqdcggnyarn3af6-binutils-2.35.2/bin/nm 2>&1 | grep -v '^ *$' | sed '1q'
/nix/store/h19zwlkrp6b0hp3ypbqdcggnyarn3af6-binutils-2.35.2/bin/nm: invalid option -- 'Z'

❯ /nix/store/3ibr5yy13sxl2vb5rig8fivj85sqcvf2-cctools-port-949.0.1/bin/nm -Z /nix/store/3ibr5yy13sxl2vb5rig8fivj85sqcvf2-cctools-port-949.0.1/bin/nm 2>&1 | grep -v '^ *$' | sed '1q'
error: /nix/store/3ibr5yy13sxl2vb5rig8fivj85sqcvf2-cctools-port-949.0.1/bin/nm: invalid argument -Z

```

I've pushed a branch which builds on aarch64-darwin and x86_64-darwin (via rosetta): https://github.com/thefloweringash/nixpkgs/commits/binutils-darwin-nm.

---

<details>

<summary>Actual error</summary>

```
./libtool: eval: line 1115: syntax error near unexpected token `|'
./libtool: eval: line 1115: `/nix/store/awr0wcmm1y1risbxjm6zcpihnr0413c0-bootstrap-stage0-clang/bin/nm -B  .libs/libctf_la-ctf-archive.o .libs/libctf_la-ctf-dump.o .libs/libctf_la-ctf-create.o .libs/libctf_la-ctf-decl.o .libs/libctf_la-ctf-error.o .libs/libctf_la-ctf-hash.o .libs/libctf_la-ctf-labels.o .libs/libctf_la-ctf-dedup.o .libs/libctf_la-ctf-link.o .libs/libctf_la-ctf-lookup.o .libs/libctf_la-ctf-open.o .libs/libctf_la-ctf-serialize.o .libs/libctf_la-ctf-sha1.o .libs/libctf_la-ctf-string.o .libs/libctf_la-ctf-subr.o .libs/libctf_la-ctf-types.o .libs/libctf_la-ctf-util.o .libs/libctf_la-ctf-open-bfd.o   |  | /nix/store/awr0wcmm1y1risbxjm6zcpihnr0413c0-bootstrap-stage0-clang/bin/sed 's/.* //' | sort | uniq > .libs/libctf.exp'
```

</details>

**Comment by Ma27** [comment]
Please note that the staging freeze is rather soonish IIRC (cc @NixOS/nixos-release-managers )

**Comment by lovesegfault** [comment]
I cannot work further on this until one of two things happen:

1. I get access to a Darwin system
2. Someone tackles the Darwin issue for me

@thefloweringash did some great debugging work above, someone just has to turn it into a patch and test it on macOS. If they are a committer they can even push to this branch.

I can't be paying out of pocket to set up macOS machines to work on a platform I don't use or have access to. I don't think it's fair.

**Comment by mikroskeem** [comment]
You can give a shot to this: https://github.com/kholia/OSX-KVM

**Comment by uri-canva** [comment]
The patch is https://github.com/thefloweringash/nixpkgs/commit/28ee39d171d52cc81a3fcfaa8f3c521d580b3bc6 right? I'll test it out.

**Comment by fabianhjr** [comment]
> You can give a shot to this: https://github.com/kholia/OSX-KVM

That is a legally grey area, even while QEMU/Support scripts/materials are completely fine it would still require agreeing to the Apple EULA/Terms which do not allow that usage. (Plus storage requirement would be a bit high for macOS + nix on macOS, my guess would be at least 256 GB if not more to build)

I would advise against going through that route.

**Comment by uri-canva** [comment]
https://github.com/thefloweringash/nixpkgs/commit/28ee39d171d52cc81a3fcfaa8f3c521d580b3bc6 works for me on `x86_64-darwin`, testing `aarch64-darwin` next.

**Comment by fabianhjr** [comment]
> I can't be paying out of pocket to set up macOS machines to work on a platform I don't use or have access to. I don't think it's fair.

Yeah, I agree the suggestion was more along leaving darwin on 2.35.1 and moving linux forward to 2.38; thanks for all the work you have put into this PR.

Been using it on staging-next this week or so.

**Comment by uri-canva** [comment]
Works on `aarch64-darwin` too. The change makes sense to me, but it would be good to have it reviewed in the context of the PR. @lovesegfault can you cherry pick the commit into this PR?

**Comment by lovesegfault** [comment]
> Works on `aarch64-darwin` too. The change makes sense to me, but it would be good to have it reviewed in the context of the PR. @lovesegfault can you cherry pick the commit into this PR?

Yup.

**Comment by lovesegfault** [comment]
> Works on `aarch64-darwin` too. The change makes sense to me, but it would be good to have it reviewed in the context of the PR. @lovesegfault can you cherry pick the commit into this PR?

Done :)

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 134917` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>binutils</li>
  </ul>
</details>

**Comment by lovesegfault** [comment]
Thanks everyone who helped along the way, it's cooking in staging now :)

**Comment by vcunat** [comment]
It seems that cross-compilation has suffered heavy losses due to the update: https://hydra.nixos.org/eval/1756232#tabs-now-fail

**Comment by trofi** [comment]
One more minor breakage on `binutils-unwrapped{allTargets=true}`. Proposed the fix as: https://github.com/NixOS/nixpkgs/pull/169907

**Pull request merged**
