### PR TITLE
teto/haskell tools nvim enable tests

### PR DESCRIPTION
**Pull request by teto**
- **luaPackages.nlua: disable patchShebangAuto**
- **luaPackages.haskell-tools-nvim: enable tests**

## Description of changes

cc @mrcjkb

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by mrcjkb — APPROVED** [review]

**Comment by teto** [comment]
I dont know if it's an ideal we should strive for as it's pretty hypthetical in the current state of the ecosystem but it should be nice if we could just run `luarocks test` for all lua packages.

Do you think it's something achievable with haskell-tools-nvim ? it might already be the case I haven't tested.
Adding a .busted file that sets lua=nlua might be enough ? https://lunarmodules.github.io/busted/#overview
`luarocks test` wil detect the file and run busted automatically ?

**Comment by mrcjkb** [comment]
> but it should be nice if we could just run luarocks test for all lua packages.

I think there will still be quite a few neovim plugins that use plenary or something else, but it should be possible to run it automatically if there's a `.busted` file.

> Adding a .busted file that sets lua=nlua might be enough?

That night work, if `nlua` is added to the rockspec's `test_dependencies`. I'll try it out in haskell-tools later.
On the Nix side, we would have to modify luarocks-nix to add `test_dependencies` to the `nativeCheckInputs`.

**Comment by teto** [comment]
great.  luarocks-nix should already  add test_dependencies to `checkInputs ` though on the nix side it may need some adjustements. If you do the change in a haskell-tools-nvim, I can try it out and make the required changes in nixpkgs

Anyway waiting for https://github.com/NixOS/nixpkgs/pull/301957 to get merged before merging this

**Comment by teto** [comment]
so this worked in a devShell but because I had https://github.com/NixOS/nixpkgs/pull/300905 in my local fork so we need to wait for that to reach master.
Getting it to work in sandbox was tricker than I thought because disabling patchShebang (which removes the `nvim` call and breaks nlua)  leaves /usr/bin/env untouched which is not available in sandbox. 
So I decided to hardcode the nlua shebang instead, which should work once https://github.com/NixOS/nixpkgs/pull/300905  is available.

**Review by mrcjkb — APPROVED** [review]

**Comment by teto** [comment]
Result of `nixpkgs-review pr 302147` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>lua51Packages.haskell-tools-nvim</li>
    <li>lua51Packages.nlua</li>
    <li>lua52Packages.haskell-tools-nvim</li>
    <li>lua52Packages.nlua</li>
    <li>lua53Packages.haskell-tools-nvim</li>
    <li>lua53Packages.nlua</li>
    <li>lua54Packages.haskell-tools-nvim</li>
    <li>lua54Packages.nlua</li>
    <li>luajitPackages.haskell-tools-nvim</li>
    <li>luajitPackages.nlua</li>
    <li>vimPlugins.haskell-tools-nvim</li>
  </ul>
</details>

**Comment by teto** [comment]
I had to enable the test only for lua5.1 else it would fail for missing dependencies. I haven't looked much into it, I suppose since lua is the interpreter, it might be looking in the wrong folders (eg with "5.1" in its paths) while the installed dependencies are named "5.3" and so on. Perfection being the enemy of good, let's improve this incrementally. Merging once darwin is confirmed to work

**Comment by mrcjkb** [comment]
> I had to enable the test only for lua5.1 else it would fail for missing dependencies. I haven't looked much into it, I suppose since lua is the interpreter, it might be looking in the wrong folders (eg with "5.1" in its paths) while the installed dependencies are named "5.3" and so on. Perfection being the enemy of good, let's improve this incrementally. Merging once darwin is confirmed to work

🤔 Maybe neovim plugins shouldn't have lua > 5.1 listed as supported?

**Comment by teto** [comment]
> Maybe neovim plugins shouldn't have lua > 5.1 listed as supported?

in the lua package set, we dont know it's a neovim plugin (we could look at the rockspec tags/labels "neovim" ?). We follow the plugin recommendation. We could have haskell-tools.nvim requires lua == 5.1 then ?

**Comment by mrcjkb** [comment]
> > Maybe neovim plugins shouldn't have lua > 5.1 listed as supported?
> 
> in the lua package set, we dont know it's a neovim plugin (we could look at the rockspec tags/labels "neovim" ?). We follow the plugin recommendation. We could have haskell-tools.nvim requires lua == 5.1 then ?

:thinking: Perhaps it would make sense for `luarocks-tag-release` to specify `lua == 5.1` if both the following conditions are true:

- No lua dependency has been explicitly specified
- One of the labels is `neovim` (indicating that it's a Neovim plugin).
  This is either set via an input or picked up from the GitHub repo metadata.

Is there any case in which we would want to be able to build a Neovim plugin for any other lua versions?

**Comment by teto** [comment]
> Is there any case in which we would want to be able to build a Neovim plugin for any other lua versions?

None I can think of. 

> One of the labels is neovim (indicating that it's a Neovim plugin).
> This is either set via an input or picked up from the GitHub repo metadata.

I think defining it by an input that then enables the label makes more sense. How do you set `copy_directories` (= plugin/after/doc...) today ? isn't there a `neovim` input already ?

**Comment by mrcjkb** [comment]
> How do you set copy_directories (= plugin/after/doc...) today ? 

It defaults to adding the rtp directories if they exist (if you leave the input empty).

> isn't there a neovim input already ?

No. I decided to cater to neovim plugins by default, making it possible to disable neovim specific behaviour by setting the inputs explicitly.

**Pull request merged**
