### PR TITLE
nixos-install: only mount if root

### PR DESCRIPTION
**Pull request by ncfavier**
Emergency fix for https://github.com/NixOS/nixpkgs/pull/210812#issuecomment-1385152889

### CODE REVIEW

**Comment by ncfavier** [comment]
@ofborg test installer.simple
@ofborg test ec2-config

**Comment by vcunat** [comment]
I confirm the image builds locally.

**Comment by K900** [comment]
Can also confirm it builds.

**Comment by rnhmjoj** [comment]
Uhm, if `nixos-install` is expected to work as non-root this needs to be done in an unshared namespace.
I just tried and it seems to work inside a `unshare -mr`.

**Comment by rnhmjoj** [comment]
I found a nicer solution: `nixos-enter` is already unsharing the mount namespace, so I'll just add these commands to its invocation with `-c`.

**Pull request merged**
