### PR TITLE
ponyc: 0.50.0 -> 0.54.0

### PR DESCRIPTION
**Pull request by superherointj**
ponyc: 0.50.0 -> 0.54.0
* Release: https://github.com/ponylang/ponyc/releases/tag/0.54.0

pony-corral: 0.6.1 -> unstable-2023-02-11
* upgrade to `unstable-2023-02-11` is required because pony `0.54.0` breaks it.

CC: @redvers

### CODE REVIEW

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 220073` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>pony-corral</li>
    <li>ponyc</li>
  </ul>
</details>

**Comment by GabrielDougherty** [comment]
Result of `nixpkgs-review pr 220073` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>pony-corral</li>
    <li>ponyc</li>
  </ul>
</details>

**Comment by superherointj** [comment]
@GabrielDougherty Feel free to review this.

**Review by GabrielDougherty — APPROVED** [review]
Diff lgtm

**Pull request merged**
