### PR TITLE
grpcurl: 1.0.0 -> 1.4.0

### PR DESCRIPTION
**Pull request by bbigras**
###### Motivation for this change
1.0.0 is over a year old.

###### Things done

I didn't build on darwin. I have no idea if the 2 distinct deps files are still required.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

/nix/store/7nk0jmh4s64vr333v6bgibh6g449wv24-grpcurl-1.0.0-bin	  61.1M
/nix/store/s7s1rx0vqvb76makhr39fcajddznb2sr-grpcurl-1.4.0-bin	  63.3M

### CODE REVIEW

**Comment by knl** [comment]
@GrahamcOfBorg build grpcurl

**Comment by knl** [comment]
I've built this on my macOS and can confirm it builds and works there.

**Review by knl — APPROVED** [review]
Looks good, thanks. I tested it on darwin as well.

**Comment by bbigras** [comment]
thanks!

**Pull request merged**
