### PR TITLE
pebble: 2.4.0 -> 2.6.0 and fix version info

### PR DESCRIPTION
**Pull request by afh**
## Description of changes

* update to 2.6.0
* remove `meta.broken` as 2.6.0 contains a fix for 32-bit system (see [letsencrypt/pebble#388](https://github.com/letsencrypt/pebble/pull/388))
* pass version to `ldflags` to have `pebble -version` show the correct version
* shorten `meta.description`
* add `meta.longDescription`
* add `meta.mainProgram`

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by emilazy — APPROVED** [review]

**Comment by afh** [comment]
ℹ️ This PR supercedes #295489

**Comment by arianvp** [comment]
@GrahamcOfBorg test acme

**Comment by afh** [comment]
@arianvp I'm unfamiliar with the acme nixosTests and it seems that they failed for all platforms. Do you have an idea what could be the cause?

**Comment by m1cr0man** [comment]
Something doesn't look right with the subject line assertions. It appears to be empty. I will try and look into it in the next free moment I get.

**Comment by m1cr0man** [comment]
Aha, I think this is why: https://github.com/letsencrypt/pebble/pull/420/files#diff-9033031dd64a1f3c17bc6f97c5e0c3a0375eafa6e81bbbbbaccedc6446d94c8dL299

Will need to change the test to use some other validation of the cert scope

**Comment by afh** [comment]
Thanks for looking into this, @m1cr0man, much appreciated! Not sure if I can be of much help, but feel free to ping me on related changes.

**Comment by afh** [comment]
Friendly ping to @m1cr0man on this one. Any action that need to taken? 🙂

**Comment by m1cr0man** [comment]
Yeah, test suite needs updated. Damn it's been two weeks? Time flies... but I'll try find a moment.

**Comment by afh** [comment]
All good, @m1cr0man, if it takes a while, that's alright with me, just want to make sure this PR doesn't get stale 🙂

**Comment by tomberek** [comment]
Result of `nixpkgs-review pr 322331` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>pebble</li>
  </ul>
</details>

**Comment by m1cr0man** [comment]
Wait, was there a fix implemented for the broken tests? I haven't gotten around to it 😞 (trying to buy a house)

**Comment by K900** [comment]
Blocks channels, reverting.

**Comment by m1cr0man** [comment]
Agh sorry about that

**Comment by emilazy** [comment]
Not your fault!

I’m sorry too though; I should have removed my drive‐by approval when the test problems showed up.

**Pull request merged**
