### PR TITLE
python3Packages.trezor: 0.12.1 -> 0.12.2

### PR DESCRIPTION
**Pull request by prusnak**
###### Motivation for this change

* version update
* add attrs, pillow to dependencies

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by 1000101** [comment]
@GrahamcOfBorg build python3Packages.trezor

**Review by 1000101 — APPROVED** [review]
* [x] reviewed the diff and commit messages
* [x] made sure ofBorg build succeeded for all applicable platforms
* [x] ran and tested the binaries
* [ ] ran nix-review without any failures

```
builder for '/nix/store/rsfz9s74znmjzm7fmpvj117s9j3vzj8d-electron-cash-4.0.14.drv' failed with exit code 1; last 10 log lines:
  /build/source/dist /build/source
  Processing ./Electron_Cash-4.0.14-py3-none-any.whl
  ...
  ERROR: Could not find a version that satisfies the requirement protobuf<3.9 (from Electron-Cash==4.0.14) (from versions: none)
  ERROR: No matching distribution found for protobuf<3.9 (from Electron-Cash==4.0.14)
builder for '/nix/store/fpi35mhypijbsb040rq05flwa0wn5jhn-electrum-4.0.2.drv' failed with exit code 1; last 10 log lines:
  ERROR: Could not find a version that satisfies the requirement dnspython<2.0 (from Electrum==4.0.2) (from versions: none)
  ERROR: No matching distribution found for dnspython<2.0 (from Electrum==4.0.2)
...
2 packages failed to build:
electron-cash electrum
```
Packages `electron-cash` and `electrum` seems to be failing but not due to this PR.

**Comment by 1000101** [comment]
@GrahamcOfBorg build python3Packages.trezor

**Comment by prusnak** [comment]
Reported the `electrum` issue here: https://github.com/NixOS/nixpkgs/issues/96477

**Comment by 1000101** [comment]
@GrahamcOfBorg build python3Packages.trezor

**Comment by 1000101** [comment]
@GrahamcOfBorg build python3Packages.trezor

**Review by 1000101 — APPROVED** [review]

**Pull request merged**
