### PR TITLE
lib/options: Warn about options without type

### LINKED ISSUE #76184: All options should have types
**Describe the bug**

To make the usage of options and errors more clear, every option should have a type.
Currently, ~~more than 300 199 151 117 27 20~~ 18 options don't have a type.

**To Reproduce**
<details>

```nix
let
  config = { };
  pkgs = import ./. {};
  lib = import ./lib;

  scrubDerivations = namePrefix: pkgSet: lib.mapAttrs
    (name: value:
      let wholeName = "${namePrefix}.${name}"; in
      if lib.isAttrs value then
        scrubDerivations wholeName value
        // (lib.optionalAttrs (lib.isDerivation value) { outPath = "\${${wholeName}}"; })
      else value
    )
    pkgSet;

  scrubbedEval = lib.evalModules {
    modules = import ./nixos/modules/module-list.nix;
    specialArgs = {
      pkgs = scrubDerivations "pkgs" pkgs;
    };
  };

  manual = import ./nixos/doc/manual {
    inherit config pkgs;
    inherit (scrubbedEval) options;
    version = "master";
    revision = "master";
  };
in manual.optionsJSON
```

```bash
jsonFile="$(NIX_PATH='' nix-build types.nix)/share/doc/nixos/options.json"
jq -r 'to_entries[] | select(.value.type == "unspecified") | [ "`" + .key + "`", "[" + .value.declarations[0] + "](../blob/master/" + .value.declarations[0] + ")" ] | join(" - ")' < "${jsonFile}" | sed 's/^\(.*\)$/- [ ] \1/g'
```
</details>

**Expected behavior**

All options should have a type.

**Additional context**

Options without types:

- [x] `dysnomia.components` - [nixos/modules/services/misc/dysnomia.nix](../blob/master/nixos/modules/services/misc/dysnomia.nix) → #149416
- [x] `dysnomia.containers` - [nixos/modules/services/misc/dysnomia.nix](../blob/master/nixos/modules/services/misc/dysnomia.nix) → #149416
- [x] `dysnomia.extraContainerPaths` - [nixos/modules/services/misc/dysnomia.nix](../blob/master/nixos/modules/services/misc/dysnomia.nix) → #149416
- [x] `dysnomia.extraContainerProperties` - [nixos/modules/services/misc/dysnomia.nix](../blob/master/nixos/modules/services/misc/dysnomia.nix) → #149416
- [x] `dysnomia.extraModulePaths` - [nixos/modules/services/misc/dysnomia.nix](../blob/master/nixos/modules/services/misc/dysnomia.nix) → #149416
- [x] `dysnomia.properties` - [nixos/modules/services/misc/dysnomia.nix](../blob/master/nixos/modules/services/misc/dysnomia.nix) → #149416
- [x] `hardware.pcmcia.config` - [nixos/modules/hardware/pcmcia.nix](../blob/master/nixos/modules/hardware/pcmcia.nix) → #149415
- [x] `security.pam.loginLimits` - [nixos/modules/security/pam.nix](../blob/master/nixos/modules/security/pam.nix) → #149412 
- [x] `security.pam.services.<name>.limits` - [nixos/modules/security/pam.nix](../blob/master/nixos/modules/security/pam.nix) → #149412 
- [x] `services.hoogle.haskellPackages` - [nixos/modules/services/development/hoogle.nix](../blob/master/nixos/modules/services/development/hoogle.nix) → #149415
- [ ] `services.nsd.zones.<name>.children` - [nixos/modules/services/networking/nsd.nix](../blob/master/nixos/modules/services/networking/nsd.nix) → #149415
- [ ] `services.unbound.stateDir` - [nixos/modules/services/networking/unbound.nix](../blob/master/nixos/modules/services/networking/unbound.nix) → #141730
- [ ] `services.vsftpd.userlist` - [nixos/modules/services/networking/vsftpd.nix](../blob/master/nixos/modules/services/networking/vsftpd.nix) → #111441
- [ ] `services.xserver.displayManager.session` - [nixos/modules/services/x11/display-managers/default.nix](../blob/master/nixos/modules/services/x11/display-managers/default.nix) → #141760
- [x] `services.xserver.windowManager.xmonad.haskellPackages` - [nixos/modules/services/x11/window-managers/xmonad.nix](../blob/master/nixos/modules/services/x11/window-managers/xmonad.nix) → #149415
- [x] `specialisation.<name>.configuration` - [nixos/modules/system/activation/top-level.nix](../blob/master/nixos/modules/system/activation/top-level.nix) → #143207

### PR DESCRIPTION
**Pull request by dasJ**
This is a follow-up to #76184

Closes #76184 
Closes #141730
Closes #141760

###### Motivation for this change

Should push people to actually add types to all options.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lourkeur** [comment]
The relevant documentation should be updated since it says that the option type may be omitted.

https://nixos.org/manual/nixos/unstable/index.html#sec-option-declarations

**Comment by Infinisil** [comment]
To prevent options without a type for all options, not just ones rendered in documentation, you should add the warning here instead: https://github.com/NixOS/nixpkgs/blob/a3274dca8852385469d0b89a1661a0e52ccbd0ff/lib/modules.nix#L685

**Comment by dasJ** [comment]
@Infinisil I tried that but there are actually a lot of internal options that have no type. Going for all options in the manual is a good start in my opinion without having to touch a lot of options.
Adding that second warning results in:
```
$ nix-build --check nixos/tests/simple.nix 2>&1 | grep -c 'has no type'
375
```

**Comment by Infinisil** [comment]
It turns out that this PR didn't work at all like this, I could never make it produce any warnings even with an option that obviously doesn't have a type.

I force pushed a fix based on my previous suggested, but making sure to only throw a warning for options that aren't internal and are visible.

This now gives a couple warnings:
```
$ nix-instantiate nixos --arg configuration nixos/modules/installer/cd-dvd/installation-cd-graphical-gnome.nix -A system
trace: warning: Option `isoImage.volumeID' defined in `/home/infinisil/src/nixpkgs/nixos/modules/installer/cd-dvd/iso-image.nix' has no type.
trace: warning: Option `isoImage.edition' defined in `/home/infinisil/src/nixpkgs/nixos/modules/installer/cd-dvd/iso-image.nix' has no type.
trace: warning: Option `dysnomia.components' defined in `/home/infinisil/src/nixpkgs/nixos/modules/services/misc/dysnomia.nix' has no type.
trace: warning: Option `dysnomia.containers' defined in `/home/infinisil/src/nixpkgs/nixos/modules/services/misc/dysnomia.nix' has no type.
trace: warning: Option `dysnomia.extraContainerPaths' defined in `/home/infinisil/src/nixpkgs/nixos/modules/services/misc/dysnomia.nix' has no type.
trace: warning: Option `dysnomia.extraContainerProperties' defined in `/home/infinisil/src/nixpkgs/nixos/modules/services/misc/dysnomia.nix' has no type.
trace: warning: Option `dysnomia.extraModulePaths' defined in `/home/infinisil/src/nixpkgs/nixos/modules/services/misc/dysnomia.nix' has no type.
trace: warning: Option `dysnomia.properties' defined in `/home/infinisil/src/nixpkgs/nixos/modules/services/misc/dysnomia.nix' has no type.
trace: warning: Option `hardware.pcmcia.config' defined in `/home/infinisil/src/nixpkgs/nixos/modules/hardware/pcmcia.nix' has no type.
trace: warning: Option `security.pam.loginLimits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `services.hoogle.haskellPackages' defined in `/home/infinisil/src/nixpkgs/nixos/modules/services/development/hoogle.nix' has no type.
trace: warning: Option `services.unbound.stateDir' defined in `/home/infinisil/src/nixpkgs/nixos/modules/services/networking/unbound.nix' has no type.
trace: warning: Option `services.vsftpd.userlist' defined in `/home/infinisil/src/nixpkgs/nixos/modules/services/networking/vsftpd.nix' has no type.
trace: warning: Option `services.xserver.displayManager.session' defined in `/home/infinisil/src/nixpkgs/nixos/modules/services/x11/display-managers/default.nix' has no type.
trace: warning: Option `services.xserver.windowManager.xmonad.haskellPackages' defined in `/home/infinisil/src/nixpkgs/nixos/modules/services/x11/window-managers/xmonad.nix' has no type.
trace: warning: Option `security.pam.services.<name>.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `services.nsd.zones.<name>.children' defined in `/home/infinisil/src/nixpkgs/nixos/modules/services/networking/nsd.nix' has no type.
trace: warning: Option `specialisation.<name>.configuration' defined in `/home/infinisil/src/nixpkgs/nixos/modules/system/activation/top-level.nix' has no type.
trace: warning: Option `security.pam.services.chfn.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.loginLimits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.chpasswd.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.chsh.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.groupadd.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.groupdel.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.groupmems.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.groupmod.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.i3lock.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.i3lock-color.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.login.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.passwd.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.polkit-1.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.runuser.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.runuser-l.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.sshd.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.su.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.sudo.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.systemd-user.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.useradd.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.userdel.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.usermod.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.vlock.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.xlock.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.xscreensaver.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `services.xserver.displayManager.session' defined in `/home/infinisil/src/nixpkgs/nixos/modules/services/x11/display-managers/default.nix' has no type.
trace: warning: Option `installer.cloneConfig' defined in `/home/infinisil/src/nixpkgs/nixos/modules/profiles/clone-config.nix' has no type.
trace: warning: Option `installer.cloneConfigIncludes' defined in `/home/infinisil/src/nixpkgs/nixos/modules/profiles/clone-config.nix' has no type.
trace: warning: Option `installer.cloneConfigExtra' defined in `/home/infinisil/src/nixpkgs/nixos/modules/profiles/clone-config.nix' has no type.
```

And some more depending on which modules are included:
```
$ nix-instantiate nixos/tests/simple.nix
trace: warning: Option `virtualisation.vlans' defined in `/home/infinisil/src/nixpkgs/nixos/modules/virtualisation/qemu-vm.nix' has no type.
trace: warning: Option `virtualisation.writableStore' defined in `/home/infinisil/src/nixpkgs/nixos/modules/virtualisation/qemu-vm.nix' has no type.
trace: warning: Option `virtualisation.writableStoreUseTmpfs' defined in `/home/infinisil/src/nixpkgs/nixos/modules/virtualisation/qemu-vm.nix' has no type.
trace: warning: Option `virtualisation.useBootLoader' defined in `/home/infinisil/src/nixpkgs/nixos/modules/virtualisation/qemu-vm.nix' has no type.
trace: warning: Option `security.pam.services.chfn.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.loginLimits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.chpasswd.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.chsh.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.groupadd.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.groupdel.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.groupmems.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.groupmod.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.i3lock.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.i3lock-color.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.login.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.passwd.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.polkit-1.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.runuser.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.runuser-l.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.su.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.sudo.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.systemd-user.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.useradd.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.userdel.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.usermod.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.vlock.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.xlock.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `security.pam.services.xscreensaver.limits' defined in `/home/infinisil/src/nixpkgs/nixos/modules/security/pam.nix' has no type.
trace: warning: Option `services.xserver.displayManager.session' defined in `/home/infinisil/src/nixpkgs/nixos/modules/services/x11/display-managers/default.nix' has no type.
trace: warning: Option `virtualisation.diskImage' defined in `/home/infinisil/src/nixpkgs/nixos/modules/virtualisation/qemu-vm.nix' has no type.
trace: warning: Option `virtualisation.diskSize' defined in `/home/infinisil/src/nixpkgs/nixos/modules/virtualisation/qemu-vm.nix' has no type.
trace: warning: Option `virtualisation.memorySize' defined in `/home/infinisil/src/nixpkgs/nixos/modules/virtualisation/qemu-vm.nix' has no type.
trace: warning: Option `virtualisation.useEFIBoot' defined in `/home/infinisil/src/nixpkgs/nixos/modules/virtualisation/qemu-vm.nix' has no type.
trace: warning: Option `virtualisation.graphics' defined in `/home/infinisil/src/nixpkgs/nixos/modules/virtualisation/qemu-vm.nix' has no type.
trace: warning: Option `virtualisation.pathsInNixDB' defined in `/home/infinisil/src/nixpkgs/nixos/modules/virtualisation/qemu-vm.nix' has no type.
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
/nix/store/gwd6dk720gw0spb1xvs1h4h5ab7l2mqp-vm-test-run-simple.drv
```

**Comment by Infinisil** [comment]
Oh wait, just realized that the force push didn't work, looks like I can't push to this branch.

Pushed it to my own branch: https://github.com/Infinisil/nixpkgs/tree/feat/warn-no-type

**Comment by dasJ** [comment]
@Infinisil Do you want to open a PR yourself or do you want me to pick the commit?

**Comment by Infinisil** [comment]
Feel free to pick the commit :)

**Comment by dasJ** [comment]
After talking to @domenkozar we replaced the error message with something that is actionable and more clear

**Comment by Infinisil** [comment]
Hmm, I'm having second thoughts. With this we're essentially telling people to always specify a type, but at least one of the main reasons we want to do this is that the fallback type of `types.unspecified` has bad behavior (similar to `types.attrs`).

An alternative to fix this problem is to change the default type to something that doesn't have bad behavior, like `types.anything` from https://github.com/NixOS/nixpkgs/pull/97119. Then it would not be a problem to specify no type.

**Comment by Infinisil** [comment]
I guess another reason for wanting good types is documentation and actual type checking (duh!). Though the cost of requiring every option definition having a type is significant. I suspect there to be many many instances of people declaring their own options without types, me including.

**Comment by dasJ** [comment]
It's the same logic (I think) as with the description which throws a warning as well without the dangers of changing the default type.
It shouldn't change anything for anyone with custom modules (us included) but fail ofborg evaluation because ofborg expects the eval to have no warnings. So this should in the end have no effect for no-nixpkgs projects apart from the warnings.
We could implement an option to disable these warnings (if it annoys enough people in the future) that could also disable the warnings about the descriptions.

**Comment by Infinisil** [comment]
The PR in its current state throws warnings for user-defined options without a type. E.g. with a `config.nix` like

```nix
{ lib, config, ... }: {
  options.foo = lib.mkOption {
    default = "test";
  };

  config = {
    fileSystems."/".device = "/nodev";
    boot.loader.grub.device = "nodev";

    environment.etc.foo.text = config.foo;
  };
}
```

Evaluating it:
```
$ nix-instantiate nixos --arg configuration ./config.nix -A system
trace: warning: Option `foo' defined in `/home/infinisil/src/nixpkgs/config.nix' has no type.
       Please specify a valid types from <nixpkgs/lib/types.nix> or use types.unspecified if there is no appropriate type.
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
/nix/store/iw5i9w8z1z0klb8k9ja5y4iqh4bcy7d0-nixos-system-nixos-22.05pre-git.drv
```

**Comment by dasJ** [comment]
Yeah I wasn't arguing that, but I think we could make the warning an opt-out when people get annoyed by it

**Comment by Infinisil** [comment]
My point was that not setting a `description` doesn't give any warnings for user-defined options, in contrast to an unset `type`.

I think if we just throw warnings for undeclared types in nixpkgs (or rather, for all modules that are rendered into the manual, which can include user modules if `documentation.nixos.includeAllModules` is enabled) should be good enough, which is also what happens for `description`. I don't think we should give warnings for other options, especially as we will have a better default type eventually with `types.anything`.

For the suggestion of only giving a warning for rendered options, here's a patch that makes it work, notably assuming that `types.unspecified` is an unspecified type, which honestly sounds like it's original intention:
```diff
diff --git a/lib/options.nix b/lib/options.nix
index 5d52f065af0..c7970d38e73 100644
--- a/lib/options.nix
+++ b/lib/options.nix
@@ -185,7 +185,13 @@ rec {
             then true
             else opt.visible or true;
           readOnly = opt.readOnly or false;
-          type = opt.type.description or null;
+          type =
+            if opt.type.name == "unspecified"
+            then lib.warn
+              ("Option `${showOption loc}' defined in ${showFiles opt.declarations} has no type.\n"
+              +"       Please specify a valid types from <nixpkgs/lib/types.nix> or use types.raw if there is no appropriate type.")
+              null
+            else opt.type.description or null;
         }
         // optionalAttrs (opt ? example) { example = scrubOptionValue opt.example; }
         // optionalAttrs (opt ? default) { default = scrubOptionValue opt.default; }
```

This notably does mention `types.raw` from https://github.com/NixOS/nixpkgs/pull/132448 as the type to use when no other type is appropriate, because `types.unspecified` wouldn't work of course. We could also mention `types.anything` here as an alternative. Differences are:
- `types.raw` doesn't recurse into the structure at all, also meaning it doesn't do any merging and only one definition is allowed. This should be used for things like package sets, e.g. `services.xserver.windowManager.xmonad.haskellPackages`
- `types.anything` fully recurses into the structure with a safe default merge function that doesn't discard anything, it supports nested `mkIf`'s and co. which get properly handled.

**Comment by Infinisil** [comment]
I created https://github.com/NixOS/nixpkgs/pull/162271 as an updated version of this, along with some improvements

**Pull request closed without merging**
