### PR TITLE
treewide: replace `--enable-wayland-ime` with `--enable-wayland-ime=true` for the arguments to properly work

### LINKED ISSUE #361330: `unstable.vscode` with `NIXOS_OZONE_WL=1` no longer accepts a file argument
## Describe the bug

The `code` command from the latest VSCode package, when used with `NIXOS_OZONE_WL=1`, can no longer be used to open a specifc file. This is because in https://github.com/NixOS/nixpkgs/commit/8ae2932d567cbe792ddfebd537be6fd66f594179, the `--enable-wayland-ime` is passed *before* the file argument in the wrapper. If the file argument is passed just before `--enable-wayland-ime` it works without problem.

## Steps To Reproduce

1. Install `vscode` from the unstable branch.
2. `export NIXOS_OZONE_WL=1`
3. `code /tmp/some-nonexistent-file`
4. VSCode just loads the previous session. The file argument has no effect.

## Expected behavior

A VSCode window should open, with a new tab called `/tmp/some-nonexistent-file`.

## Additional context

If the generated wrapper is like

```bash
exec -a "$0" "/nix/store/41ggnz98g8pikykphnf3fy06d0wp508q-vscode-1.95.3/bin/.code-wrapped"
${NIXOS_OZONE_WL:+${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations --enable-wayland-ime}}  "$@"
```

This works:

```bash
"/nix/store/41ggnz98g8pikykphnf3fy06d0wp508q-vscode-1.95.3/bin/.code-wrapped" --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations /tmp/bar --enable-wayland-ime
```

This doesn't:

```bash
"/nix/store/41ggnz98g8pikykphnf3fy06d0wp508q-vscode-1.95.3/bin/.code-wrapped" --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations --enable-wayland-ime /tmp/bar
```

It's unclear if other Electron software handles `--enable-wayland-ime` in this way. Since https://github.com/NixOS/nixpkgs/commit/8ae2932d567cbe792ddfebd537be6fd66f594179 is a treewide change maybe there are other packages that require a fix as well.

## Notify maintainers

@34j @eadwu @Synthetica9 @bobby285271 @JohnRTitor 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by 34j**
- Replaces `--enable-wayland-ime` with `--enable-wayland-ime=true` for the arguments to properly work
- Closes #361330 (which is for VSCode)
- Tested in VSCode that passing filepaths now works
- Tested in VSCode and Slack that passing `--enable-wayland-ime=true` has the same effect as passing `--enable-wayland-ime`
- I am not sure how Electron apps handle arguments, so I am not really sure if treewide changes should be made.

```python
import re

from collections import defaultdict
from pathlib import Path

# for each nix file in the pkgs directory
for path in Path('pkgs').rglob('*.nix'):
    txt = path.read_text()
    
    # find NIXOS_OZONE_WL
    # start_text = '''"\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+'''
    match = re.search(r'\${WAYLAND_DISPLAY\:\+(.+?)}}', txt)
    if match:
        if "--enable-wayland-ime" in match.group(1):
            print(path)
            txt = txt.replace(match.group(1), match.group(1).replace("--enable-wayland-ime", "--enable-wayland-ime=true"))
            path.write_text(txt)     
```

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by JohnRTitor** [comment]
I am not sure about the syntax here, every example online seems to be just `--enable-wayland-ime`, perhaps we should let the electron and chromium maintainers have a look?

**Comment by JohnRTitor** [comment]
Related https://github.com/NixOS/nixpkgs/issues/357956 , upstream issue for VSCode: https://github.com/microsoft/vscode/issues/234479

@stereomato Could you try with `code --disable-font-subpixel-positioning=true hello.txt`

**Review by JohnRTitor — APPROVED** [review]
LGTM otherwise, tested a few packages

**Comment by stereomato** [comment]
> Related #357956 , upstream issue for VSCode: [microsoft/vscode#234479](https://github.com/microsoft/vscode/issues/234479)
> 
> @stereomato Could you try with `code --disable-font-subpixel-positioning=true hello.txt`
> 
> EDIT: works for me

yup! works here!

**Review by JohnRTitor — APPROVED** [review]
Let's merge this instead of keeping this broken

Tested a few packages and looks good

**Comment by YooLc** [comment]
Thank you for the patch! Now VSCode can accept path arguments as before.

However, I feel there might be a better way to address this issue 🥹.

Specifically, it might be more appropriate to place `--enable-wayland-ime` and other additional arguments for Wayland after `$@` instead of before. This way, we wouldn't need to change it to `--enable-wayland-ime=true`, and it could also prevent future issues where new arguments might accidentally cause problems concatenating with $@.

To achieve this, we can simply change `--add-flags` to `--append-flags`:

https://github.com/NixOS/nixpkgs/blob/9c34193fcba3201797da211aae03bbe48789790d/pkgs/build-support/setup-hooks/make-wrapper.sh#L167-L174

Similarly, the Visual Studio Code package in AUR places `$@` before user-defined flags like `--enable-wayland-ime`:

https://aur.archlinux.org/cgit/aur.git/tree/visual-studio-code-bin.sh?h=visual-studio-code-bin

**Comment by 34j** [comment]
> Thank you for the patch! Now VSCode can accept path arguments as before.
> 
> However, I feel there might be a better way to address this issue 🥹.
> 
> Specifically, it might be more appropriate to place `--enable-wayland-ime` and other additional arguments for Wayland after `$@` instead of before. This way, we wouldn't need to change it to `--enable-wayland-ime=true`, and it could also prevent future issues where new arguments might accidentally cause problems concatenating with $@.
> 
> To achieve this, we can simply change `--add-flags` to `--append-flags`:
> 
> https://github.com/NixOS/nixpkgs/blob/9c34193fcba3201797da211aae03bbe48789790d/pkgs/build-support/setup-hooks/make-wrapper.sh#L167-L174
> 
> and these flags would be passed to `flagsAfter` when making a wrapper:
> 
> https://github.com/NixOS/nixpkgs/blob/d6c2d483f153e8c6a793e775be5968a6dc45760a/pkgs/build-support/setup-hooks/make-wrapper.sh#L189-L190
> 
> Similarly, the Visual Studio Code package in AUR places `$@` before user-defined flags like `--enable-wayland-ime`:
> 
> https://aur.archlinux.org/cgit/aur.git/tree/visual-studio-code-bin.sh?h=visual-studio-code-bin

As a newbie to Electron and nix, I had no idea that such a solution existed.😇 I would like to leave this to you or others in case yours is the best solution as I have no more energy to open another PR.

**Comment by JohnRTitor** [comment]
This is really a electron problem and ideally should be fixed upstream.

**Comment by YooLc** [comment]
> As a newbie to Electron and nix, I had no idea that such a solution existed.😇 I would like to leave this to you or others in case yours is the best solution as I have no more energy to open another PR. (Maybe my Python scripts in the description can be utilized.)

No worry, the current patch is good enough, because it could cover cases where the .nix script doesn't use makeWrapper 🤝

**Pull request merged**
