### PR TITLE
xgboost: add headers from dmlc-core and rabit

### PR DESCRIPTION
**Pull request by nviets**
Adding headers from dmlc-core and rabit.

### CODE REVIEW

**Comment by nviets** [comment]
@abbradar

**Review by bcdarwin — APPROVED** [review]
Looks fine to me.

**Comment by nviets** [comment]
@Mindavi - are you able to approve and merge? I'm a maintainer, but it seems I can't approve my own PR.

**Review by bcdarwin — APPROVED** [review]

**Comment by nviets** [comment]
Thanks @bcdarwin. Newby question - to whom should package maintainers escalate for approval? I am unable to approve my own commits it seems.

**Comment by SuperSandro2000** [comment]
You don't need to approve your own PRs neither do you just be a maintainer of a package to change something about it.

**Pull request merged**
