### PR TITLE
Update Idris

### PR DESCRIPTION
**Pull request by ttuegel**
### Motivation for this change

This fixes the build failure of idris-1.1.1 and updates `idrisPackages` to use that version.
The build system has changed slightly, so `build-idris-package` changes.
`build-builtin-package` is mainly affected.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vyp** [comment]
cc @srhb this has some similar changes to your #28479, so I don't know what you want to do but just pinging you for that. 🙂

**Comment by srhb** [comment]
Oh, we should definitely go with this one. Closing mine. :)

**Review by shlevy — APPROVED** [review]
Nice!

**Comment by ttuegel** [comment]
I accidentally left off the most important part: changing the Idris version used by `idrisPackages`! It is fixed now.

**Pull request merged**
