### PR TITLE
waitron: init at 2020-01-24

### PR DESCRIPTION
**Pull request by dguibert**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by Emantor — APPROVED** [review]
- [x] checked license
- [x] build package
```$ nix build --no-link --keep-going --option build-use-sandbox relaxed -f /home/phoenix/.cache/nixpkgs-review/pr-84572/build.nix
[7 built, 4 copied (3.6 MiB), 1.1 MiB DL]
https://github.com/NixOS/nixpkgs/pull/84572
1 package built:
waitron
```
- [x] binary works as far as outputting the help text

**Review by Emantor — CHANGES_REQUESTED** [review]
Please correctly format the commit `waitron: init at 2020-01-24`.

**Comment by dguibert** [comment]
> Please correctly format the commit `waitron: init at 2020-01-24`.

done

**Review by Emantor — APPROVED** [review]

**Comment by dguibert** [comment]
"still important to me"

**Pull request merged**
