### PR TITLE
graalvm-ce: 22.1.0 -> 22.2.0

### PR DESCRIPTION
**Pull request by jlesquembre**
###### Description of changes
Update graalvm

ping @thiagokokada 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by thiagokokada — COMMENTED** [review]
Don't you also need to update GraalVM 11?

**Comment by jlesquembre** [comment]
Right, I forgot it, updated the PR

**Comment by thiagokokada** [comment]
@ofborg build babashka clojure-lsp jet

**Comment by thiagokokada** [comment]
@ofborg build graalvm17-ce

**Comment by thiagokokada** [comment]
`babashka` is failing to build with the update.

**Comment by thiagokokada** [comment]
Probably we need to wait for a new babashka release for now: https://github.com/babashka/babashka/pull/1325

**Comment by jlesquembre** [comment]
Right, let's wait for a new babashka release, probably will be a short wait XD
If I'm not mistaken, we are building babashka with graalvm 17, should we change to 11, since it's the version used in the babashka build script?

**Comment by thiagokokada** [comment]
> Right, let's wait for a new babashka release, probably will be a short wait XD If I'm not mistaken, we are building babashka with graalvm 17, should we change to 11, since it's the version used in the babashka build script?

I don't think so. In all packages:

```nix
  buildGraalvmNativeImage = callPackage ../build-support/build-graalvm-native-image {
    graalvm = graalvm11-ce;
  };
```

And `babashka` doesn't override it: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/clojure/babashka.nix

**Comment by jlesquembre** [comment]
thanks for the info, I missed that in all-packages.nix

**Comment by thiagokokada** [comment]
@ofborg build babashka clojure-lsp jet graalvm17-ce

**Review by thiagokokada — APPROVED** [review]

**Pull request merged**
