### PR TITLE
pythonPackages3.gdtoolkit: fixup loose lark dependency

### LINKED ISSUE #216243: gdtoolkit: Replace lark080 override
As posted in #160040:

            
Overrides like that are no allowed when using `buildPythonPackage`.

See https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.section.md#using-pythonrelaxdepshook-using-pythonrelaxdepshook

_Originally posted by @mweinelt in https://github.com/NixOS/nixpkgs/pull/160040#discussion_r1027113889_

### PR DESCRIPTION
**Pull request by kirillrdy**
###### Description of changes

fixes https://github.com/NixOS/nixpkgs/issues/216243

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by hesiod** [comment]
Result of `nixpkgs-review pr 216280` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python310Packages.gdtoolkit</li>
    <li>python311Packages.gdtoolkit</li>
  </ul>
</details>

**Review by hesiod — CHANGES_REQUESTED** [review]
Have you checked that the gdtoolkit tools still work?
Upstream says they use an older version of lark since newer versions had incompatible changes in the past: https://github.com/Scony/godot-gdscript-toolkit/issues/199#issuecomment-1422948469

Perhaps you could add `pytestCheckHook` so the tests are run. There is a comment that the tests need to run pip, but I don't think that's the case: According to https://github.com/Scony/godot-gdscript-toolkit/blob/master/tox.ini they only need pytest and hypothesis. I actually tried adding `pytestCheckHook` and there are some failing tests, but I can't say whether those are new failures.

**Comment by hesiod** [comment]
OK, found the issue - `gdtoolkit` tries to write files in a cache directory:
* The cache file path: https://github.com/Scony/godot-gdscript-toolkit/blob/8251fa142ea86b63263b6e7f84af21875668340c/gdtoolkit/parser/parser.py#L83-L85
* ...which is based on the cache directory: https://github.com/Scony/godot-gdscript-toolkit/blob/8251fa142ea86b63263b6e7f84af21875668340c/gdtoolkit/parser/parser.py#L52 and https://github.com/Scony/godot-gdscript-toolkit/blob/8251fa142ea86b63263b6e7f84af21875668340c/gdtoolkit/parser/parser.py#L153-L162
* Saving the parse result: https://github.com/Scony/godot-gdscript-toolkit/blob/8251fa142ea86b63263b6e7f84af21875668340c/gdtoolkit/parser/parser.py#L104

Looking at the docs of [os.path.expanduser](https://docs.python.org/3/library/os.path.html#os.path.expanduser), it should be possible to override `HOME` for the tests (e.g. by setting it to `$TMP`) so that the tests run in the sandbox

**Comment by hesiod** [comment]
I got the tests to work mostly (can post the required changes later today), but I'm afraid that they turned out to reveal the problem I suspected: `gdtoolkit` really isn't compatible with our version of `lark`.

<details>
  <summary>Test results with lark 0.8.0 (before this PR):</summary>
```
=========================== short test summary info ============================
FAILED tests/test_nearley/test_nearley.py::TestNearley::test_css - FileNotFoundError: [Errno 2] No such file or directory: '/build/source/test...
FAILED tests/test_nearley/test_nearley.py::TestNearley::test_include - FileNotFoundError: [Errno 2] No such file or directory: '/build/source/test...
FAILED tests/test_nearley/test_nearley.py::TestNearley::test_multi_include - FileNotFoundError: [Errno 2] No such file or directory: '/build/source/test...
============ 3 failed, 572 passed, 60 skipped, 2 warnings in 15.89s ============
```
</details>

<details>
  <summary>Test results for this PR (lark 1.1.5):</summary>
```
=========================== short test summary info ============================
FAILED tests/formatter/test_basics.py::test_formatting[tool-tool\n] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_executable.py::test_valid_file_formatting - AssertionError: assert 1 == 0
FAILED tests/formatter/test_executable.py::test_valid_files_formatting - AssertionError: assert 1 == 0
FAILED tests/formatter/test_executable.py::test_valid_files_formatting_with_nonexistent_one_keepgoing - AssertionError: assert 0 == 3
FAILED tests/formatter/test_executable.py::test_valid_files_formatting_with_invalid_one_keepgoing - AssertionError: assert 0 == 3
FAILED tests/formatter/test_executable.py::test_valid_formatted_file_checking - AssertionError: assert 1 == 0
FAILED tests/formatter/test_executable.py::test_valid_unformatted_file_checking - assert 28 == 2
FAILED tests/formatter/test_executable.py::test_valid_unformatted_files_checking_with_invalid_one_keepgoing - assert 'Traceback' not in "Traceback (...ansformer'\n"
FAILED tests/formatter/test_executable.py::test_valid_formatted_files_checking_with_nonexistent_one_keepgoing - AssertionError: assert 0 == 1
FAILED tests/formatter/test_executable.py::test_valid_formatted_files_checking_with_invalid_one_keepgoing - AssertionError: assert 0 == 1
FAILED tests/formatter/test_executable.py::test_valid_unformatted_file_diff - assert '+++' in 'Traceback (most recent call last):\n  File "/nix/store/4zr...
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[enum-comments] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[compound-function-statements] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[or-xor-and-shift-bitwise-expressions] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[blank-line-squeezing] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[complex-export-statements] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[assignment-expressions] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[strings] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[short-dict-expressions] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[static-function-surroundings] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[subscription-expressions] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[enum-w-long-name] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[short-boolean-test-expressions] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[extra-function-definitions] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[enum-name-not-long-enough] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[negation-n-bitwise-not-expressions] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[puppet-var] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[standalone-comments-in-expressions] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[empty-enum] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[force-multiline-dict] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[call-expressions] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[comment-corner-case] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[class-name-statement] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[assert] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[regular-enum-force-multiline] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[array-n-dict-expression-comments] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[regular-long-enum] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[simple-function-statements] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[blockless-func-n-func-suite] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[enum-operations] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[simple-atom-expressions] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[complex-class-name-w-extends-statement] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[nested-classes] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[short-array-expressions] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[attribute-expressions] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[setget] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[simple-class-stmts] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[blank-line-adding] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[simple-function-definitions] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[type-test-expressions] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[long-boolean-test-expressions] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[blockless-class] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[simple-nested-class-stmts] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[complex-signal-statements] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[bug-127-hashtag-corner-case] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[complex-extends-statements] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[simple-classes-and-functions] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[simple-class-statements] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[long-array-expressions] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[level-0-comment-preservation] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[class-stmt-chain] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[force-multiline-array] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[turn-spaces-into-tabs] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[type-cast-expressions] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[multiline-string] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[long-dict-expressions] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[if-corner-case] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[underscored-numeric-literals] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[utf-8-characters] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[comment-corner-cases] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[bug-70-ternary-corner-case] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[parentheses-expressions-preservation] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[long-arithmetic-expression] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[class-name-w-extends-statement] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[multiplication-division-remainder-expressions] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[regular-enum] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[test-corner-cases] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[complex-trailing-comma-scenarios] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[multiline-preload-workaround] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[addition-n-subtraction-expressions] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[simple-match-statements] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[inline-comments-on-compound-stmts] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[if-elif-else-comments] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[parentheses-expressions-removal] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[bug-136-empty-comma-separated-list] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[leading-and-trailing-wss-w-comments] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[class-name-statement-w-string] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_input_output_pairs.py::test_input_output_pair[complex-function-definitions] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/formatter/test_real_world_scripts.py::test_real_world_script[MarkovianPCG.gd] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/linter/test_basic_checks.py::test_expression_not_assigned_nok[func foo():\n    1 + 1\n] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/linter/test_basic_checks.py::test_unnecessary_pass_nok[func foo():\n    pass\n    1 + 1\n] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/linter/test_basic_checks.py::test_unnecessary_pass_nok[func foo():\n    if x: pass; 1+1\n] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/linter/test_basic_checks.py::test_duplicated_load_nok[\nconst B = preload('b')\nvar A = load('a')\nfunc foo():\n    var X = load('a')\n] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/linter/test_basic_checks.py::test_duplicated_load_nok[\nconst B = preload('b')\nvar A = load('a')\nfunc foo():\n    var X = preload('a')\n] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/linter/test_basic_checks.py::test_comparison_with_itself_nok[func foo():\n    if 1 == 1:\n        return 1\n    return 0\n] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/linter/test_basic_checks.py::test_comparison_with_itself_nok[func foo(x):\n    if x == x:\n        return 1\n    return 0\n] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/linter/test_basic_checks.py::test_comparison_with_itself_nok[func foo():\n    if "a" == "a":\n        return 1\n    return 0\n] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/linter/test_basic_checks.py::test_comparison_with_itself_nok[func foo():\n    if (x + 1) == (x + 1):\n        return 1\n    return 0\n] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/linter/test_class_checks.py::test_class_definitions_order_nok[extends Node\ntool\n] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/linter/test_class_checks.py::test_class_definitions_order_nok[tool;extends Node\ntool\n] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/linter/test_class_checks.py::test_class_definitions_order_nok[\nclass X: extends Node;tool\n] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/linter/test_design_checks.py::test_max_public_methods_nok[\nfunc foo1():\n    pass\nfunc foo2():\n    pass\nfunc foo3():\n    pass\nfunc foo4():\n    pass\nfunc foo5():\n    pass\nfunc foo6():\n    pass\nfunc foo7():\n    pass\nfunc foo8():\n    pass\nfunc foo9():\n    pass\nfunc foo10():\n    pass\nfunc foo11():\n    pass\nfunc foo12():\n    pass\nfunc foo13():\n    pass\nfunc foo14():\n    pass\nfunc foo15():\n    pass\nfunc foo16():\n    pass\nfunc foo17():\n    pass\nfunc foo18():\n    pass\nfunc foo19():\n    pass\nfunc foo20():\n    pass\nfunc foo21():\n    pass\n] - AttributeError: 'Tree' object has no attribute 'line'
FAILED tests/linter/test_executable.py::test_valid_file_no_config - AssertionError: assert 1 == 0
FAILED tests/linter/test_executable.py::test_valid_file_w_config - AssertionError: assert 1 == 0
FAILED tests/linter/test_executable.py::test_pretty_printing_unexpected_token - assert 'Traceback' not in "Traceback (...ansformer'\n"
FAILED tests/parser/test_executable.py::test_parsing_valid_files_succeeds - AssertionError: assert 1 == 0
FAILED tests/parser/test_executable.py::test_pretty_printing_valid_files_succeeds - AssertionError: assert 1 == 0
FAILED tests/parser/test_executable.py::test_pretty_printing_unexpected_token - assert 'Traceback' not in "Traceback (...ansformer'\n"
================= 108 failed, 189 passed, 213 skipped in 9.74s =================
```
</details>

**Comment by hesiod** [comment]
Unfortunately the fix in this PR won't work because of the issues outlined above and in #216329.

@kirillrdy I hope you don't mind if I close this PR as PR #216329 pretty much supersedes this PR. Thanks for your initial work on fixing this!

**Comment by kirillrdy** [comment]
@hesiod no worries, as long as it works !

**Pull request closed without merging**
