### PR TITLE
uboot: allow bigger kernels to boot on raspberry pi

### LINKED ISSUE #97064: Raspberry Pi 3 B+ can't boot with latest kernel 5.7.19
**Describe the bug**
Since my last kernel upgrade on the Raspberry Pi 3B+, I can't boot anymore (I lost ssh access). I tried to burn a new image from scrach, update the channel, and create the most basic configuration, and the problem persists.

**To Reproduce**
1. Download the Aarch64 sdcard image [here](https://hydra.nixos.org/build/126325375) 
2. Unpack, and burn it with `dd` on a sdcard
3. Make sure that you have the following `config.txt` (`enable_uart` is useful to boot with uart, and `force_turbo` was required to have less noise in the characters read by uart):

```
kernel=u-boot-rpi3.bin

# Boot in 64-bit mode.
arm_control=0x200

# U-Boot used to need this to work, regardless of whether UART is actually used or not.
# TODO: check when/if this can be removed.
enable_uart=1

# Prevent the firmware from smashing the framebuffer setup done by the mainline kernel
# when attempting to show low-voltage or overtemperature warnings.
avoid_warnings=1
force_turbo=1
```
4. Boot on this sdcard, and I recommend to use UART + `screen` to boot with a serial console
5. Configure internet, put the following file in `/etc/nixos/configuration.nix`:

```
{ config, pkgs, lib, ... }:
{
  # NixOS wants to enable GRUB by default
  boot.loader.grub.enable = false;
  # Enables the generation of /boot/extlinux/extlinux.conf
  boot.loader.generic-extlinux-compatible.enable = true;
 
  # !!! Otherwise (even if you have a Raspberry Pi 2 or 3), pick this:
  boot.kernelPackages = pkgs.linuxPackages_latest;
  
  # !!! Needed for the virtual console to work on the RPi 3, as the default of 16M doesn't seem to be enough.
  # If X.org behaves weirdly (I only saw the cursor) then try increasing this to 256M.
  # On a Raspberry Pi 4 with 4 GB, you should either disable this parameter or increase to at least 64M if you want the USB ports to work.
  boot.kernelParams = ["cma=32M"];
    
  # File systems configuration for using the installer's partition layout
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-label/NIXOS_SD";
      fsType = "ext4";
    };
  };
    
  # !!! Adding a swap file is optional, but strongly recommended!
  swapDevices = [ { device = "/swapfile"; size = 1024; } ];
}
```

and then run:

```
sudo nix-channel --update
sudo nixos-rebuild switch
```

Reboot: the OS stops booting at `Starting kernel ...`, even if you add in the kernel parameters `console=ttyS1,115200n8` or `console=ttyS0,115200n8 console=ttyAMA0,115200n8 console=tty0 loglevel=7` (via `/boot/extlinux/extlinux.conf`):

```
------------------------------------------------------------
1:      NixOS - Default
2:      NixOS - Configuration 2 (2020-09-04 00:54 - 20.03.2873.10aede9bcfe)
3:      NixOS - Configuration 1 (1970-01-01 00:00 - 20.03.2869.0d60b0b10ea)
Enter choice: 1:        NixOS - Default
Retrieving file: /boot/extlinux/../nixos/jkjjy892iirdhns5mxqx063xn374ph80-initrd-linux-5.7.19-initrd
7726240 bytes read in 322 ms (22.9 MiB/s)
Retrieving file: /boot/extlinux/../nixos/hmwv1a4bnlshi1zlnzsk83sg41ybaf73-linux-5.7.19-Image
39021056 bytes read in 1614 ms (23.1 MiB/s)
append: systemConfig=/nix/store/jrmziij585fgr7n82dg3ff435s13gnhb-nixos-system-nixos-20.03.2873.10aede9bcfe init=/nix/store/jrmziij585fgr7n82dg3ff435s13gnhb-nixos-system-nixos-20.03.2873.10aede9bcfe/init cma=32M console=ttyS0,115200n8 console=ttyAMA0,115200n8 console=tty0 loglevel=7
Retrieving file: /boot/extlinux/../nixos/hmwv1a4bnlshi1zlnzsk83sg41ybaf73-linux-5.7.19-dtbs/broadcom/bcm2837-rpi-3-b-plus.dtb
14622 bytes read in 6 ms (2.3 MiB/s)
## Flattened Device Tree blob at 02600000
   Booting using the fdt blob at 0x2600000
   Using Device Tree in place at 0000000002600000, end 000000000260691d

Starting kernel ...
``` 

Moreover, I think it is not a problem with UART, because on my first system I couldn't ssh my system that was working fine during 2 years, and the green LED does not blink during the expected boot period.

**Expected behavior**
I would expect it to boot properly.

**Screenshots**

**Additional context**
I tried with the kernel 5.6 and it boots fine. I experienced issues with the kernel `5.7.18` and `5.7.19`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by ghost**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — COMMENTED** [review]
Can you change the title and commit message to something like ``uboot: allow bigger kernels to boot on raspberry pies``

**Comment by petabyteboy** [comment]
> Can you change the title and commit message to something like `uboot: allow bigger kernels to boot on raspberry pies`

sure!

**Comment by blaggacao** [comment]
Sorry for being at risk of abusing your care for the commons, but I'm trying to use this PR as an overlay, but I seem [unable to get it to work](https://github.com/nrdxp/nixflk/pull/73/files#diff-248955e8e79c9098356d0975a1f9249e2c12350643a1de6aa3ac172a075bcbaf)...

I tried setting it `buildUboot` and what not...

Is there an easy way I'm just not seeing?

**Comment by petabyteboy** [comment]
> Sorry for being at risk of abusing your care for the commons, but I'm trying to use this PR as an overlay and I seem [unable to get it to work](https://github.com/nrdxp/nixflk/pull/73/files#diff-248955e8e79c9098356d0975a1f9249e2c12350643a1de6aa3ac172a075bcbaf)...
> 
> I tried setting it `buildUboot` and what not...
> 
> Is there an easy way I'm just not seeing?

Try this:

```
final: prev: {
  ubootRaspberryPi3_64bit = prev.ubootRaspberryPi3_64bit.overrideAttrs (o: { patches = [ ../pkgs/misc/uboot/0001-configs-rpi-allow-for-bigger-kernels.patch ]; });
}
```

**Review by samueldr — APPROVED** [review]
I don't know how to judge if the values can be problematic, but at a glance it looks alright: they're all increased by `0x800000` (except the kernel), so they all moved up in unison.

**Comment by samueldr** [comment]
Hi!

Nice work, may I ask you to *also* send this upstream? We've had a good success story with @lopsided98 for rockchip boards in the past:

 - https://patchwork.ozlabs.org/project/uboot/patch/20191203054006.1822512-1-benwolsieffer@gmail.com/

(Though you'll also have to fix the comments if you send upstream.)

**Comment by petabyteboy** [comment]
I will try to send it upstream in the next few hours, although I'm not entirely sure if they'll accept it. After all where is the limit for kernel size? It will just keep getting bigger and bigger and the values will not be enough in a year.

**Comment by lopsided98** [comment]
I submitted a similar patch for the RockPro64 and they accepted it, although I don't remember how much I increased it by.

**Comment by samueldr** [comment]
They are understanding of "mainline defconfig Linux". They know it exists, and gets bigger.

Just to re-iterate, here is _the_ patch @lopsided98 contributed, if you want to see the reception:

 - https://patchwork.ozlabs.org/project/uboot/patch/20191203054006.1822512-1-benwolsieffer@gmail.com/

(Though it was reviewed by the Rockchip... maintainer? )

**Comment by petabyteboy** [comment]
Meh, all of us didni't actually test it and the patch I committed was for 2021.01 and doesn't apply to 2020.10. I will fix it later.

**Pull request merged**
