### PR TITLE
gtk-mac-integration: 2.1.3 -> 3.0.1

### PR DESCRIPTION
**Pull request by arkivm**
###### Motivation for this change

gtk-mac-integration: 2.1.3 -> 3.0.1

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by arkivm** [comment]
@veprbl

**Comment by prusnak** [comment]
@GrahamcOfBorg build gtk-mac-integration gtk-mac-integration-gtk2 gspell gimp inkscape darktable dia gtksourceview

**Comment by prusnak** [comment]
> Also, I don't see your name in the known users list here: https://github.com/grahamc/ofborg

This repo hasn't been updated since 2019. I believe the repo in use is now under nixos organization and here's my username: https://github.com/NixOS/ofborg/blob/released/config.public.json#L90

**Comment by jtojnar** [comment]
Same as https://github.com/NixOS/nixpkgs/pull/134860, changes look okay but there are some Mac-related BC breaks so it would be nice to test run at least a few apps depending on this.

**Pull request merged**
