### PR TITLE
bazel: 0.12.0 -> 0.13.0

### PR DESCRIPTION
**Pull request by rdnetto4**
###### Motivation for this change
This PR bumps the Bazel package to the recently released 0.13.0.

###### Things done
Built Nix package under Sabayon Linux and used it to compile a Bazel project.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by FRidh** [comment]
Thanks. This needs testing of dependents as version bumps of Bazel typically break things.

**Comment by rdnetto4** [comment]
Needed to bump tensorflow to get it to compile with the new Bazel version, still waiting to see if anything else fails.

**Comment by uri-canva** [comment]
I get this when I try to build this on NixOS:

```
ERROR: /tmp/nix-build-bazel-0.13.0.drv-0/third_party/grpc/BUILD:51:1: Creating runfiles tree bazel-out/host/bin/third_party/grpc/cpp_plugin.runfiles [for host] failed (Exit 127): build-runfiles failed: error executing command
  (cd /tmp/bazel_hLCMGkTp/out/execroot/io_bazel && \
  exec env - \
  _bin/build-runfiles bazel-out/host/bin/third_party/grpc/cpp_plugin.runfiles_manifest bazel-out/host/bin/third_party/grpc/cpp_plugin.runfiles)
[2 / 6] //third_party/grpc:cpp_plugin; 0s local
/tmp/bazel_hLCMGkTp/out/execroot/io_bazel/_bin/build-runfiles: line 2: mkdir: command not found
/tmp/bazel_hLCMGkTp/out/execroot/io_bazel/_bin/build-runfiles: line 3: cp: command not found
```

See my PR for a different approach to have Bazel find coreutils: #40424.

**Comment by rdnetto4** [comment]
It turns out that bumping Bazel requires us to bump Tensorflow (currently 1.5.0), since the new Bazel no longer tolerates certain warnings. There are two potential versions we could update to (1.7.1 and 1.8.0 - for some reason 1.7.1 was released after 1.8.0), both of which are currently failing to build for different reasons. I'm going to try and get 1.7.1 working as it looks like it might just be missing a dependency, but progress will be slow due to the one hour build time.

I suspect I'm not running into the coreutils problem in #40424 because I'm not under NixOS - will try and get it working for my setup first before trying to merge them.

**Comment by xeji** [comment]
closing this in favor of #40525

**Pull request closed without merging**
