### PR TITLE
openmw-tes3mp: fix working

### LINKED ISSUE #87967: tes3mp doesn't launch
tes3mp crashes on launch like described in https://github.com/TES3MP/openmw-tes3mp/issues/542

**To Reproduce**
1. Create a shell with tes3mp using `nix-shell -p tes3mp-openmw`
2. Launch server browser using `tes3mp-browser`
3. Connect to any server.
4. The game will crash.

**Expected behavior**
A game was expected to launch and run.

**Additional context**
tes3mp crash log:
```
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast (search paths /run/opengl-driver/lib/dri)
libGL error: failed to load driver: swrast
Got an X11ErrorHandling call display=0x2144000 event=0x7ffdebd0e6c0
GLXBadContext
Major opcode: 150
Minor opcode: 6
Error code: 156
Request serial: 101
Current serial: 100
  ResourceID: 71303171
Got an X11ErrorHandling call display=0x2144000 event=0x7ffdebd0e4f0
BadValue (integer parameter out of range for operation)
Major opcode: 150
Minor opcode: 3
Error code: 2
Request serial: 100
Current serial: 101
  Value: 0
Loading config file: /home/smakarov/.config/openmw/openmw.cfg... done.
Loading config file: /nix/store/9vcp5m8mzh472q7r9q8i3zjc1dy7zn2f-openmw-tes3mp-2019-11-19/etc/openmw/openmw.cfg... done.
TES3MP client 0.7.0-alpha (Linux 64-bit)
Protocol version: 7
Oldest compatible commit hash: 292536439e
------------------------------------------------------------
OpenMW version 0.44.0
Using Cyrillic font encoding.
[2020-05-16 20:34:15] [INFO]: tes3mp started
Loading settings file: /nix/store/9vcp5m8mzh472q7r9q8i3zjc1dy7zn2f-openmw-tes3mp-2019-11-19/etc/openmw/tes3mp-client-default.cfg
[2020-05-16 20:34:15] [WARN]: Received ID_CONNECTION_REQUESTED_ACCEPTED from 149.172.198.154|25570
idx: 0	checksum: 34282D67	file: /home/smakarov/.steam/steam/steamapps/common/Morrowind/Data Files/Morrowind.esm
idx: 1	checksum: 211329EF	file: /home/smakarov/.steam/steam/steamapps/common/Morrowind/Data Files/Tribunal.esm
idx: 2	checksum: 9EB62F26	file: /home/smakarov/.steam/steam/steamapps/common/Morrowind/Data Files/Bloodmoon.esm
OSG version: 3.4.1
Loading settings file: /nix/store/9vcp5m8mzh472q7r9q8i3zjc1dy7zn2f-openmw-tes3mp-2019-11-19/etc/openmw/settings-default.cfg
Loading settings file: /home/smakarov/.config/openmw/settings.cfg
Got an X11ErrorHandling call display=0x2144000 event=0x7ffdebd0e100
GLXBadContext
Major opcode: 150
Minor opcode: 6
Error code: 156
Request serial: 156
Current serial: 155
  ResourceID: 71303177
Got an X11ErrorHandling call display=0x2144000 event=0x7ffdebd0df30
BadValue (integer parameter out of range for operation)
Major opcode: 150
Minor opcode: 3
Error code: 2
Request serial: 155
Current serial: 156
  Value: 0
Error: Unable to create OpenGL graphics context: Could not create GL context: BadValue (integer parameter out of range for operation)
[2020-05-16 20:34:16] [INFO]: tes3mp stopped

ERROR: Failed to create GraphicsContext
```

**Possible workaround**
I tried to run tes3mp with libstdc++ from gcc9 using LD_PRELOAD and the game launched successfully.  Maybe building tes3mp using the same toolchain as for openmw would resolve issue, but I didn't manage to do it.

**Notify maintainers**

@gnidorah

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.39, NixOS, 20.09.20200513.8ba41a1 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20200501_941f952`
 - channels(root): `"nixos-20.09pre223023.fce7562cf46"`
 - channels(smakarov): `""`
 - nixpkgs: `/etc/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: openmw-tes3mp
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by ghost**
###### Motivation for this change

Closes #87967

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SeTSeR — APPROVED** [review]
LGTM. tes3mp seems to work, when started from server browser.

**Comment by gnidorah** [comment]
@SeTSeR Thanks. Though I think its too much of workarounds now. All that gcc8 and gcc9 mixing will likely make tes3mp break again soon. So i've added a quick code patch instead until that gcc bug will be fixed.

**Comment by gnidorah** [comment]
@GrahamcOfBorg build openmw-tes3mp

**Review by SeTSeR — APPROVED** [review]
tes3mp compiles and runs.

**Comment by gnidorah** [comment]
@veprbl @SeTSeR Thanks!

**Pull request merged**
