### PR TITLE
packages.json: more subsets

### PR DESCRIPTION
**Pull request by Atemu**
###### Motivation for this change

https://github.com/NixOS/nixpkgs/issues/102508

Nix expression used to generate the list:

https://gist.github.com/Atemu/283526e3e8c196107468209068562a7e

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by veprbl** [comment]
@timokau To answer to https://github.com/NixOS/nixpkgs/pull/105857#issuecomment-739259708: Yes, this adds a list that would need to be maintained. Even after the selections there are some items that are not sets of installable packages (e.g. `texFunctions`).

**Comment by Atemu** [comment]
>adds a list that would need to be maintained

True but I feel like we kind of need a list like this. There is no source for what's a set of packages under `pkgs` and what isn't. Not good for discoverability; neither automated nor manual.

As @garbas [mentioned](https://github.com/NixOS/nixpkgs/pull/105857#issuecomment-739838002) though, ideally this would be resolved at the root: Perhaps such a list should be the very place in which package subsets are defined.

What if we moved packages subsets out of `all-packages`, into a new "subsets.nix" and then combined back into the current `pkgs` structure for example? (+ perhaps a new `pkgs.subsets`)

> Even after the selections there are some items that are not sets of installable packages

It'd be better if it was 100% clean of course but having sets with things other than packages in them isn't actually an issue because non-derivations are simply skipped in the JSON generation.

**Comment by davidak** [comment]
What is the status here?

It would still be great to export every package to packages.json. That is an easy way to make nixpkgs more valuable for users. Packages that are not discoverable do not exist for users!

https://github.com/NixOS/nixpkgs/pull/105857 was merged because there is no better proposed solution to solve the issue and i think that applies here too. So, can we get it merged?

**Comment by Atemu** [comment]
The problem is not that this is a bad solution, the problem is that this is an unsustainable solution.

We need to enforce a single place where subsets *must* be declared and perhaps even apply `recurseIntoAttrs` to all of them.

**Pull request closed without merging**
