### PR TITLE
cln: 1.3.3 -> 1.3.4

### PR DESCRIPTION
**Pull request by vbgl**
Tested on NixOS and darwin.

### CODE REVIEW

**Comment by pSub** [comment]
I've restarted the build and will merge if it succeeds.

**Comment by pSub** [comment]
```
/nix/store/wha7xisi3irdxi1ki0nsgsfy58622lkx-gstreamer-1.6.1/include/gstreamer-1.0/gst/gstelement.h:55:27: fatal error: gst/gstconfig.h: No such file or directory

 #include <gst/gstconfig.h>
```

**Comment by vbgl** [comment]
That error is not related to this update. See eg, http://hydra.nixos.org/build/28845676 for a previous manifestation of that error.

**Comment by pSub** [comment]
Oh, thank you. I was in a hurry and just looked briefly at the error. The update seems fine on a second look.

**Pull request merged**
