### PR TITLE
hyperterm: init at 0.7.6

### PR DESCRIPTION
**Pull request by puffnfresh**
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by peterhoeg** [comment]
In order for the binary to be available, you need to place it (or a symlink or a wrapper) in $out/bin.

**Comment by puffnfresh** [comment]
@peterhoeg thanks, I forgot to do that.

**Comment by peterhoeg** [comment]
Is there any reason that we are not building from source?

**Comment by puffnfresh** [comment]
@peterhoeg my experience with Electron applications is that they're a pain to package. I'd love to build this from source.

**Comment by peterhoeg** [comment]
There's an example here:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/nix-tour/default.nix

**Pull request merged**
