### PR TITLE
Staging next with systemd privacy fix

### PR DESCRIPTION
**Pull request by FRidh**
###### Motivation for this change

Includes channel blocking fixes for systemd. Let's hope it won't break anything else.

https://hydra.nixos.org/job/nixpkgs/staging-next/unstable#tabs-constituents

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by ttuegel — APPROVED** [review]
I can't comment on the rest, but for my part: the Qt and KDE changes are fine.

**Comment by Atemu** [comment]
Tried to build my system config which depends on Lutris and `wineWowPackages.staging` now fails with:

```
configure flags: --prefix=/nix/store/j16xw0pz68mwjpvc2256xr40ckqgi20k-wine-wow-5.22-staging --enable-win64
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/build/wine64':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
```

Everything else builds fine and seems to work fine in a VM. 

Bisecting...

**Comment by FRidh** [comment]
26k darwin packages remaining

**Comment by vcunat** [comment]
@Atemu: I'd look into `config.log` (after building with `--keep-failed`).  Maybe some of the changes in toolchain wrappers.

**Comment by Atemu** [comment]
Nothing jumped to my eye initially but I found this:

```
/build/wine-5.22/configure: line 4907: ./conftest: Accessing a corrupted shared library
```

Any idea what that could mean?

**Comment by FRidh** [comment]
Mixing 32 and 64 bit? https://stackoverflow.com/questions/30419857/accessing-a-corrupted-shared-library

**Comment by Atemu** [comment]
That could be it, it is the 64bit build afterall.

Any idea which commits have the potential to cause this regression? That'd help speed up my bisecting efforts as wine has tons of dependencies and I'm not even through the first build yet.

**Comment by FRidh** [comment]
> Any idea which commits have the potential to cause this regression? That'd help speed up my bisecting efforts as wine has tons of dependencies and I'm not even through the first build yet.

Probably https://github.com/NixOS/nixpkgs/pull/107086/commits/11302dc1cff70c92793bc2c867e027d69e2c91ef or https://github.com/NixOS/nixpkgs/pull/107086/commits/ccfd26ef14ea213320f0b49db3fb347785b38f06 or https://github.com/NixOS/nixpkgs/pull/107086/commits/ccfd26ef14ea213320f0b49db3fb347785b38f06. `libwine.so*` is supposed to be static according to https://wiki.winehq.org/Packaging#WoW64_Workarounds.

Wine wow uses its own builder script, `builder-wow.sh`, to perform the two builds necessary. I wonder why we don't build them separate and then symlink together.

**Comment by Atemu** [comment]
Finished bisecting, it's indeed caused by ccfd26ef14ea213320f0b49db3fb347785b38f06. cc @Mic92 

It also affects all wineWowPackages, not just .staging.

**Comment by FRidh** [comment]
cc-wrapper tests are failing @Ericson2314 @Mic92

**Comment by Emantor** [comment]
Pretty sure #107253 will fix this, however this unfortunately triggers a mass rebuild for a lot of stuff...

**Comment by Emantor** [comment]
> Pretty sure #107253 will fix this, however this unfortunately triggers a mass rebuild for a lot of stuff...
> 
> Edit:
> 
> > cc-wrapper tests (all versions of tests.cc-wrapper-libcxx) are failing @Ericson2314 @Mic92
> 
> Nice, I'll test with the wrapper tests.

Unfortunately my PR does not fix the wrapper tests, however I still think my PR fixes compilation for 32-bit binaries.
The wrapper tests are failing because the linker is trying to include `crtbegin.o` and `-lgcc`, which both can't be found in the search paths.

**Comment by Emantor** [comment]
Compilation is still broken for darwin (e.g. https://hydra.nixos.org/build/133372669/nixlog/8):
```
checking whether the C compiler works... no
configure: error: in `/private/tmp/nix-build-libffi-3.3.drv-0/libffi-3.3/x86_64-apple-darwin17.7.0':
configure: error: C compiler cannot create executables
See `config.log' for more details
builder for '/nix/store/83ish70q5ghw48q5g3h9yr9dxjczvxfg-libffi-3.3.drv' failed with exit code 77
```

**Comment by thefloweringash** [comment]
The error seems to be:
```
ld: unknown option: -dynamic-linker=/usr/lib/dyld
```
(from https://hydra.nixos.org/build/133170060/nixlog/12/tail)

Which looks like it was added by https://github.com/NixOS/nixpkgs/pull/106908. Previously `-dynamic-linker` was only passed when `! stdenv.isDarwin`, but it was made unconditional. Looking at the [man page for ld](https://www.unix.com/man-page/osx/1/ld/) and the [source of ld64](https://github.com/tpoechtrager/cctools-port/blob/ae9675d50dae4e77d2b09f6d27daa356419de2de/cctools/ld64/src/ld/Options.cpp#L4501-L4503) we use, it looks like it can only be set by an environment variable and there's no equivalent command line flag. The wrappers should probably only pass this flag when the linker is known to be support it.

**Comment by Emantor** [comment]
The wrapper tests on NixOS are failing because of 11302dc1cff, this looks to be unrelated to the darwin issue.

> The error seems to be:
> 
> ```
> ld: unknown option: -dynamic-linker=/usr/lib/dyld
> ```
> 
> (from https://hydra.nixos.org/build/133170060/nixlog/12/tail)
> 
> Which looks like it was added by #106908. Previously `-dynamic-linker` was only passed when `! stdenv.isDarwin`, but it was made unconditional. Looking at the [man page for ld](https://www.unix.com/man-page/osx/1/ld/) and the [source of ld64](https://github.com/tpoechtrager/cctools-port/blob/ae9675d50dae4e77d2b09f6d27daa356419de2de/cctools/ld64/src/ld/Options.cpp#L4501-L4503) we use, it looks like it can only be set by an environment variable and there's no equivalent command line flag. The wrappers should probably only pass this flag when the linker is known to be support it.

Nice find!

**Comment by Emantor** [comment]
Tentative PR for the cc-wrapper problems: https://github.com/NixOS/nixpkgs/pull/107336, please review.

**Comment by vcunat** [comment]
🤔 when channel is broken and a fix is in staging, I suspect that just taking whole staging (into staging-next) isn't the best default strategy.  Sure, we got unlucky this time, but still.

**Comment by vcunat** [comment]
For the current particular situation... what about unleashing Hydra over a new branch containing just master and the systemd fixes?  That will need no darwin fixes (the currently slowest platform by far).

**Comment by FRidh** [comment]
I think we should revert the cc wrapper and bintools changes instead. Everything else looked fine. Stdenv changes need to be tested better before being merged into staging.

**Comment by Emantor** [comment]
> I think we should revert the cc wrapper and bintools changes instead. Everything else looked fine. Stdenv changes need to be tested better before being merged into staging.

TBH, that would also be my preference, the fix for the dynamicLinker for darwin feels more like a hack to me.

**Comment by vcunat** [comment]
Depends if that's the only cause for a large rebuild.  IIRC systemd by itself doesn't cause such a huge rebuild.

**Comment by vcunat** [comment]
> Stdenv changes need to be tested better before being merged into staging.

32-bit cases are easy to miss (and considered rather minor generally) and darwin is hard to test for most people 🤷🏽

**Comment by flokli** [comment]
> I think we should revert the cc wrapper and bintools changes instead. Everything else looked fine. Stdenv changes need to be tested better before being merged into staging.

I agree with @FRidh here. Let's revert the cc wrapper and bintools changes, run another hydra evaluation, and get channels unblocked.

The other changes can be re-introduced in a followup PR, and be more thoroughly tested.

**Comment by vcunat** [comment]
Done.
```
$ ./maintainers/scripts/rebuild-amount.sh 583470209f9d5
  25938 x86_64-darwin
  30435 x86_64-linux
```
^^ this amount of darwin rebuilds will surely take several days, but perhaps we can afford to merge before that finishes.

**Comment by Atemu** [comment]
I was going to ask why we'd need to wait for Darwin builds as the Darwin channel would just block for a few days until they're done which wouldn't be a huge issue but I just noticed that such channel does not exist.

Is there a specific reason why we don't have one for unstable? It'd sure be convenient for cases like these.

**Comment by vcunat** [comment]
I'm not aware of any reason.  I think I've already mentioned somewhere that it would be nice to remove this difference.  There's `nixpkgs-unstable` channel.

**Comment by archseer** [comment]
I think there should be a channel per architecture target, see https://github.com/NixOS/nixpkgs/issues/83049 for similar issues with aarch64

**Comment by FRidh** [comment]
This is not the place to discuss what channels we should have.

**Comment by flokli** [comment]
@FRidh considering there's less than [500 queued jobs](https://hydra.nixos.org/eval/1637068?filter=x86_64-linux&compare=1636988&full=#tabs-unfinished) left for `x86_64-linux`, I assume this is good to merge (and we can trigger a NixOS eval afterwards?)

**Comment by flokli** [comment]
Okay, there's no more builds left. Let's merge this :-)

**Comment by petrosagg** [comment]
Sorry if this is a basic question, I'm not fully familiar with the hydra pipeline. What's left for the `nixos-unstable` to get unblocked? Will it reuse the artifacts from this build run?

**Comment by flokli** [comment]
nixos-unstable runs builds from master - this was in `staging-next`.

I just triggered https://hydra.nixos.org/jobset/nixos/unstable-small and https://hydra.nixos.org/jobset/nixos/trunk-combined, which should update the corresponding channels (once succeeded).

**Comment by vcunat** [comment]
All hydra jobsets populate cache.nixos.org, and same /nix/store hashes get reused.

**Comment by jonringer** [comment]
unfortunately, `nixos.tests.installer.simpleUefiSystemdBoot` is failing https://hydra.nixos.org/build/133597924/nixlog/100.

I get the same failure locally.

**Comment by jakobrs** [comment]
#107275 is the PR that broke the test.

**Comment by Atemu** [comment]
Eval complete: https://hydra.nixos.org/eval/1637149?filter=tested&compare=1637089&full=#tabs-now-succeed

**Pull request merged**
