### PR TITLE
ryujinx: 1.1.223 -> 1.1.248

### PR DESCRIPTION
**Pull request by IvarWithoutBones**
###### Description of changes
Its now running unit tests, and the headless frontend is packaged as well. The latter is a bit inconsistent, on the OpenGL backend it will always fail to create an SDL+OpenGL instance, causing a crash.

The Vulkan backend mostly works fine, although it might need a few restarts before it decides to show graphics. Better than nothing though.

Did also look into if we use `testVersion` with the headless executable since it has a `--version` flag, but for some reason that needs access to an X11 socket.

cc @06kellyjac

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and “core” functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by zhaofengli — APPROVED** [review]
Tested to work, thanks!

**Review by 06kellyjac — APPROVED** [review]

**Comment by superherointj** [comment]
> Did also want to ask for opinions on symlinking the main executable to `ryujinx` (not capitalised). That's kind of the standard for programs on unix systems, i can definitely see people not being able to find the binary from a `nix-shell` without having to resort to looking in the nix store.

Please make the changes you deem reasonable.

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 187942` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ryujinx</li>
  </ul>
</details>

**Comment by superherointj** [comment]
@IvarWithoutBones ping

**Comment by IvarWithoutBones** [comment]
Apologies about the wait everyone, I just updated this to the latest version again and added the symlink.

**Comment by superherointj** [comment]
Result of `nixpkgs-review pr 187942` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ryujinx</li>
  </ul>
</details>

**Comment by superherointj** [comment]
@IvarWithoutBones I see you have moved some code. Would be nicer if you respected the phases order.

Unpack => Patch => Configure => Build => Check => Install

**Comment by IvarWithoutBones** [comment]
Not exactly sure what you mean. The only phases we override are `preInstall` and `postFixup`, which look to be ordered correctly?

**Comment by superherointj** [comment]
> Or do you mean attributes effecting those phases like `doCheck` and `patches`?

Yes

**Review by superherointj — APPROVED** [review]

**Comment by IvarWithoutBones** [comment]
> > Or do you mean attributes effecting those phases like `doCheck` and `patches`?
> 
> Yes

Ah right, it can be done in a future PR i suppose.

**Pull request merged**
