### PR TITLE
bash: 5.2p26 -> 5.2p32; add upstream fix for `pop_var_context` error

### LINKED ISSUE #214822: NOT A NIXPKGS BUG nor the cause of any failure stdenv: `pop_var_context: head of shell_variables not a function context`
Not a nixpkgs bug nor the cause of any failure
https://mail.gnu.org/archive/html/bug-bash/2022-10/msg00075.html

```
/nix/store/559pz0w6zlvw8yyxah9s10fhaz400vaj-stdenv-darwin/setup: line 138: pop_var_context: head of shell_variables not a function context
```

### PR DESCRIPTION
**Pull request by emilazy**
## Description of changes

Tested with the first‐built Bash in stdenv; it applies, builds, and runs. I haven’t tried injecting it into derivations to check that the error doesn’t appear any more because I don’t really know what the best way to do that without rebuilding all of stdenv is and I’m not entirely sure how to arrange the circumstances that cause the error.

Closes: #214822

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by emilazy** [comment]
It might be a good idea to backport just the https://github.com/NixOS/nixpkgs/issues/214822 fix back to 24.05 since it confuses people so often.

**Comment by K900** [comment]
Tested this on an intentionally broken package, and the error is in fact gone (and everything else works normally). Going to try building up to something more interesting now, like Mesa.

**Review by philiptaron — APPROVED** [review]
Built the packages below and ~150 more odd in the review shell.

Result of `nixpkgs-review pr 331540` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>bashInteractive</li>
    <li>bashInteractive.debug (bashInteractive.debug.debug ,bashInteractive.debug.dev ,bashInteractive.debug.doc ,bashInteractive.debug.info ,bashInteractive.debug.man)</li>
    <li>bashInteractive.dev (bashInteractive.dev.debug ,bashInteractive.dev.dev ,bashInteractive.dev.doc ,bashInteractive.dev.info ,bashInteractive.dev.man)</li>
    <li>bashInteractive.doc (bashInteractive.doc.debug ,bashInteractive.doc.dev ,bashInteractive.doc.doc ,bashInteractive.doc.info ,bashInteractive.doc.man)</li>
    <li>bashInteractive.info (bashInteractive.info.debug ,bashInteractive.info.dev ,bashInteractive.info.doc ,bashInteractive.info.info ,bashInteractive.info.man)</li>
    <li>bashInteractive.man (bashInteractive.man.debug ,bashInteractive.man.dev ,bashInteractive.man.doc ,bashInteractive.man.info ,bashInteractive.man.man)</li>
  </ul>
</details>

**Comment by K900** [comment]
Built up to Mesa on x86_64-linux, I think we can be reasonably confident this doesn't break bash too hard.

**Pull request merged**
