### PR TITLE
sparrow: 1.8.1 -> 1.8.4

### PR DESCRIPTION
**Pull request by emmanuelrosa**
## Description of changes

This is a version bump of sparrow (bitcoin wallet) from 1.8.1 to 1.8.4. See the release notes: 

- https://github.com/sparrowwallet/sparrow/releases/tag/1.8.2
- https://github.com/sparrowwallet/sparrow/releases/tag/1.8.3
- https://github.com/sparrowwallet/sparrow/releases/tag/1.8.4

A noteworthy change is that now upstream uses JDK21, which is now reflected in this package. I also updated the JVM runtime arguments as per upstream. There aren't that many changes, it's just that I copy-pasted from upstream, so the ordering is different.

It's also worth mentioning that the download verification feature added in 1.8.3 does not work on NixOS; A different process would be needed.

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by naturallaw777** [comment]
Thanks for this @emmanuelrosa !!

**Comment by emmanuelrosa** [comment]
I rebased the commit, to use a newer Nixpkgs.

**Comment by naturallaw777** [comment]
Hi @emmanuelrosa,

Sparrow just released 1.8.3: https://sparrowwallet.com/download/

Thanks so much!

Now all we need is to get the reviewers to merge this after sparrow is updated

**Comment by naturallaw777** [comment]
Whoah! Now Sparrow 1.8.4 is out!

**Comment by emmanuelrosa** [comment]
Geez! It looks like I'll be playing whack-a-mole with Craig.

OK, hold me beer...

**Comment by naturallaw777** [comment]
Haha! For real. Thanks @emmanuelrosa for all that you do for the Nix Bitcoin community! Your next several beers are on me!

**Comment by zikziko** [comment]
Thank you so much for your work @emmanuelrosa !

**Review by drupol — APPROVED** [review]

**Pull request merged**
