### PR TITLE
nodejs_14: drop

### PR DESCRIPTION
**Pull request by marsam**
## Description of changes

Node.js 14 has reached End-of-Life (EoL) on 2023-04-30

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — CHANGES_REQUESTED** [review]
Can we keep nodejs_14 behind some knownVulnerable or similar? There is still some software that requires it and undoing a removals is for most people none trivial.

**Comment by marsam** [comment]
>Can we keep nodejs_14 behind some knownVulnerable or similar? 

I think that is the current status, nodejs_14 _is_ marked as vulnerable due openssl-1.1.

I planned to drop Nodejs 14 and 16 for Release 23.11, and I believe the release managers also think so 
cc: @RaitoBezarius @figsoda 
https://github.com/NixOS/nixpkgs/blob/cb9e968437faec0c0b72804d32e360042e05442c/pkgs/top-level/release.nix#L32-L38

**Comment by RaitoBezarius** [comment]
> >Can we keep nodejs_14 behind some knownVulnerable or similar? 
> 
> I think that is the current status, nodejs_14 _is_ marked as vulnerable due openssl-1.1.
> 
> I planned to drop Nodejs 14 and 16 for Release 23.11, and I believe the release managers also think so 
> cc: @RaitoBezarius @figsoda 
> https://github.com/NixOS/nixpkgs/blob/cb9e968437faec0c0b72804d32e360042e05442c/pkgs/top-level/release.nix#L32-L38

Let me know when you feel like this is ready to merge.

**Comment by SuperSandro2000** [comment]
Closing because it's the other pr from raito

**Pull request closed without merging**
