### PR TITLE
knot-dns: doInstallCheck = true

### PR DESCRIPTION
**Pull request by vcunat**
This is trivial; I just need borg to check `darwin`.

### CODE REVIEW

**Comment by vcunat** [comment]
@GrahamcOfBorg build knot-dns

**Comment by vcunat** [comment]
Oh, bad luck!  Right now [ofbrorg seems](https://monitoring.nix.ci/d/000000002/ofborg?refresh=10s&orgId=1) to have no darwin builder and the queue is reaching to a thousand...

**Comment by ajs124** [comment]
@dasJ weren't you saying you have a mac to test things on, recently? How about running `nixpkgs-review` against this?

**Comment by dasJ** [comment]
Seems to hang here:
```
[1/0/3 built] building knot-dns-3.0.0 (checkPhase): knot/test_zonedb................ok
```

**Comment by vcunat** [comment]
Weird; `checkPhase` hasn't changed and seems to be fine on Hydra: https://nix-cache.s3.amazonaws.com/log/sl744gdlwdzkl32qdmxbsaiqjdlb2zph-knot-dns-3.0.0.drv

**Pull request merged**
