### PR TITLE
python311Packages.openai: 0.28.1 -> 1.3.4

### PR DESCRIPTION
**Pull request by malob**
## Description of changes

Update to latest version. 

This is basically a total rewrite, so likely lots of breaking changes for packages that depend on it. Not sure how best to handle that.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by malob** [comment]
Result of `nixpkgs-review pr 265946` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>chatgpt-retrieval-plugin</li>
    <li>chatgpt-retrieval-plugin.dist</li>
    <li>khoj</li>
    <li>khoj.dist</li>
  </ul>
</details>
<details>
  <summary>10 packages failed to build:</summary>
  <ul>
    <li>openai-full</li>
    <li>openai-full.dist</li>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python310Packages.langchain</li>
    <li>python310Packages.langchain.dist</li>
    <li>python310Packages.minichain</li>
    <li>python310Packages.minichain.dist</li>
    <li>python311Packages.langchain</li>
    <li>python311Packages.langchain.dist</li>
  </ul>
</details>
<details>
  <summary>21 packages built:</summary>
  <ul>
    <li>chatblade</li>
    <li>chatblade.dist</li>
    <li>checkov</li>
    <li>checkov.dist</li>
    <li>imaginer</li>
    <li>open-interpreter</li>
    <li>open-interpreter.dist</li>
    <li>openai (python311Packages.openai)</li>
    <li>openai.dist (python311Packages.openai.dist)</li>
    <li>python310Packages.guidance</li>
    <li>python310Packages.guidance.dist</li>
    <li>python310Packages.litellm</li>
    <li>python310Packages.litellm.dist</li>
    <li>python310Packages.openai</li>
    <li>python310Packages.openai.dist</li>
    <li>python311Packages.guidance</li>
    <li>python311Packages.guidance.dist</li>
    <li>python311Packages.litellm</li>
    <li>python311Packages.litellm.dist</li>
    <li>shell-genie</li>
    <li>shell-genie.dist</li>
  </ul>
</details>

**Comment by malob** [comment]
Result of `nixpkgs-review pr 265946` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>chatgpt-retrieval-plugin</li>
    <li>chatgpt-retrieval-plugin.dist</li>
  </ul>
</details>
<details>
  <summary>7 packages failed to build:</summary>
  <ul>
    <li>home-assistant-component-tests.openai_conversation</li>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python310Packages.langchain</li>
    <li>python310Packages.langchain.dist</li>
    <li>python311Packages.langchain</li>
    <li>python311Packages.langchain.dist</li>
  </ul>
</details>
<details>
  <summary>25 packages built:</summary>
  <ul>
    <li>chatblade</li>
    <li>chatblade.dist</li>
    <li>checkov</li>
    <li>checkov.dist</li>
    <li>imaginer</li>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>openai (python311Packages.openai)</li>
    <li>openai-full</li>
    <li>openai-full.dist</li>
    <li>openai.dist (python311Packages.openai.dist)</li>
    <li>python310Packages.guidance</li>
    <li>python310Packages.guidance.dist</li>
    <li>python310Packages.litellm</li>
    <li>python310Packages.litellm.dist</li>
    <li>python310Packages.minichain</li>
    <li>python310Packages.minichain.dist</li>
    <li>python310Packages.openai</li>
    <li>python310Packages.openai.dist</li>
    <li>python311Packages.guidance</li>
    <li>python311Packages.guidance.dist</li>
    <li>python311Packages.litellm</li>
    <li>python311Packages.litellm.dist</li>
    <li>shell-genie</li>
    <li>shell-genie.dist</li>
  </ul>
</details>

**Comment by malob** [comment]
Result of `nixpkgs-review pr 265946` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>chatgpt-retrieval-plugin</li>
    <li>chatgpt-retrieval-plugin.dist</li>
    <li>khoj</li>
    <li>khoj.dist</li>
  </ul>
</details>
<details>
  <summary>10 packages failed to build:</summary>
  <ul>
    <li>openai-full</li>
    <li>openai-full.dist</li>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python310Packages.langchain</li>
    <li>python310Packages.langchain.dist</li>
    <li>python310Packages.minichain</li>
    <li>python310Packages.minichain.dist</li>
    <li>python311Packages.langchain</li>
    <li>python311Packages.langchain.dist</li>
  </ul>
</details>
<details>
  <summary>21 packages built:</summary>
  <ul>
    <li>chatblade</li>
    <li>chatblade.dist</li>
    <li>checkov</li>
    <li>checkov.dist</li>
    <li>imaginer</li>
    <li>open-interpreter</li>
    <li>open-interpreter.dist</li>
    <li>openai (python311Packages.openai)</li>
    <li>openai.dist (python311Packages.openai.dist)</li>
    <li>python310Packages.guidance</li>
    <li>python310Packages.guidance.dist</li>
    <li>python310Packages.litellm</li>
    <li>python310Packages.litellm.dist</li>
    <li>python310Packages.openai</li>
    <li>python310Packages.openai.dist</li>
    <li>python311Packages.guidance</li>
    <li>python311Packages.guidance.dist</li>
    <li>python311Packages.litellm</li>
    <li>python311Packages.litellm.dist</li>
    <li>shell-genie</li>
    <li>shell-genie.dist</li>
  </ul>
</details>

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 265946` at 4544e9e9 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>chatgpt-retrieval-plugin</li>
  </ul>
</details>
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/natsukium/695685a191ab316af1797db27f807961">home-assistant-component-tests.openai_conversation</a></li>
    <li>pentestgpt</li>
    <li><a href="https://gist.github.com/natsukium/3c9a1552d75809522fc429ef224d059d">python310Packages.langchain</a></li>
    <li><a href="https://gist.github.com/natsukium/c89a219ce2648351ace952a9eb116e48">python311Packages.langchain</a></li>
  </ul>
</details>
<details>
  <summary>14 packages built successfully:</summary>
  <ul>
    <li>chatblade</li>
    <li>checkov</li>
    <li>imaginer</li>
    <li>khoj</li>
    <li>open-interpreter</li>
    <li>openai (python311Packages.openai)</li>
    <li>openai-full</li>
    <li>python310Packages.guidance</li>
    <li>python310Packages.litellm</li>
    <li>python310Packages.minichain</li>
    <li>python310Packages.openai</li>
    <li>python311Packages.guidance</li>
    <li>python311Packages.litellm</li>
    <li>shell-genie</li>
  </ul>
</details>

**Comment by natsukium** [comment]
It seems that langchain is currently working on supporting openai's new API. e.g. https://github.com/langchain-ai/langchain/pull/12969
Since the development is fast, I think it will be done within a few days.

**Comment by mweinelt** [comment]
Please don't merge before the branch-off.

**Comment by malob** [comment]
Result of `nixpkgs-review pr 265946` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>chatgpt-retrieval-plugin</li>
    <li>chatgpt-retrieval-plugin.dist</li>
  </ul>
</details>
<details>
  <summary>17 packages built:</summary>
  <ul>
    <li>chatblade</li>
    <li>chatblade.dist</li>
    <li>checkov</li>
    <li>checkov.dist</li>
    <li>imaginer</li>
    <li>open-interpreter</li>
    <li>open-interpreter.dist</li>
    <li>openai (python311Packages.openai)</li>
    <li>openai.dist (python311Packages.openai.dist)</li>
    <li>python310Packages.litellm</li>
    <li>python310Packages.litellm.dist</li>
    <li>python310Packages.openai</li>
    <li>python310Packages.openai.dist</li>
    <li>python311Packages.litellm</li>
    <li>python311Packages.litellm.dist</li>
    <li>shell-genie</li>
    <li>shell-genie.dist</li>
  </ul>
</details>

**Comment by malob** [comment]
Result of `nixpkgs-review pr 265946` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>18 packages marked as broken and skipped:</summary>
  <ul>
    <li>chatgpt-retrieval-plugin</li>
    <li>chatgpt-retrieval-plugin.dist</li>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>openai-full</li>
    <li>openai-full.dist</li>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>python310Packages.guidance</li>
    <li>python310Packages.guidance.dist</li>
    <li>python310Packages.langchain</li>
    <li>python310Packages.langchain.dist</li>
    <li>python310Packages.minichain</li>
    <li>python310Packages.minichain.dist</li>
    <li>python311Packages.guidance</li>
    <li>python311Packages.guidance.dist</li>
    <li>python311Packages.langchain</li>
    <li>python311Packages.langchain.dist</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>home-assistant-component-tests.openai_conversation</li>
  </ul>
</details>
<details>
  <summary>15 packages built:</summary>
  <ul>
    <li>chatblade</li>
    <li>chatblade.dist</li>
    <li>checkov</li>
    <li>checkov.dist</li>
    <li>imaginer</li>
    <li>openai (python311Packages.openai)</li>
    <li>openai.dist (python311Packages.openai.dist)</li>
    <li>python310Packages.litellm</li>
    <li>python310Packages.litellm.dist</li>
    <li>python310Packages.openai</li>
    <li>python310Packages.openai.dist</li>
    <li>python311Packages.litellm</li>
    <li>python311Packages.litellm.dist</li>
    <li>shell-genie</li>
    <li>shell-genie.dist</li>
  </ul>
</details>

**Comment by malob** [comment]
Result of `nixpkgs-review pr 265946` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>chatgpt-retrieval-plugin</li>
    <li>chatgpt-retrieval-plugin.dist</li>
  </ul>
</details>
<details>
  <summary>17 packages built:</summary>
  <ul>
    <li>chatblade</li>
    <li>chatblade.dist</li>
    <li>checkov</li>
    <li>checkov.dist</li>
    <li>imaginer</li>
    <li>open-interpreter</li>
    <li>open-interpreter.dist</li>
    <li>openai (python311Packages.openai)</li>
    <li>openai.dist (python311Packages.openai.dist)</li>
    <li>python310Packages.litellm</li>
    <li>python310Packages.litellm.dist</li>
    <li>python310Packages.openai</li>
    <li>python310Packages.openai.dist</li>
    <li>python311Packages.litellm</li>
    <li>python311Packages.litellm.dist</li>
    <li>shell-genie</li>
    <li>shell-genie.dist</li>
  </ul>
</details>

**Comment by Animeshz** [comment]
OpenAI Api docs now no longer show 0.x compatible examples, is there a quick way to upgrade to latest version, if this PR have a blocker?

**Pull request closed without merging**
