### PR TITLE
[Backport release-24.05] github-runner: 2.320.0 -> 2.321.0

### PR DESCRIPTION
**Pull request by YorikSar**
Manual backport of #356300 to `release-24.05`.

Automatic backport failed to rebase change, because the package was in a different place in the tree back then.

* [x]  Before merging, ensure that this backport is [acceptable for the release](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#changes-acceptable-for-releases).
  
  * Even as a non-commiter, if you find that it is not acceptable, leave a comment.

### CODE REVIEW

**Review by kfollesdal — APPROVED** [review]

**Review by kfollesdal — CHANGES_REQUESTED** [review]
Check cherry-picks fails

**Comment by YorikSar** [comment]
@kfollesdal cherrypick check fails because `deps.nix` is in a different place in this branch. The same reason why automatic cherrypick failed here.

**Comment by kfollesdal** [comment]
@YorikSar, apologies for my ignorance, but I'm not familiar with the automatic `cherry-picks check`. Are you saying it's expected to fail in this case?

**Comment by YorikSar** [comment]
@kfollesdal The logs end with:
> Note this should not necessarily be treated as a hard fail, but a reviewer's attention should be drawn to it and github actions have no way of doing that but to raise a 'failure'
This is because the check verifies diff between master commit and release branch commit. In this case, the same file is in different places in master and this release branch, so it's in different places in the commit patches. That's why the check fails.

**Review by kfollesdal — APPROVED** [review]

**Review by kfollesdal — APPROVED** [review]

**Review by leona-ya — APPROVED** [review]

**Pull request merged**
