### PR TITLE
zed-editor: 0.141.3 -> 0.144.4

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Changelog: https://github.com/zed-industries/zed/releases/tag/v0.144.4

We need to wait for Rust 1.79.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by bbigras** [comment]
Btw Rust 1.79 is in staging 83aaf6183611b2816a35d3d437eb99177d43378f

zed-editor [v0.143.6](https://github.com/zed-industries/zed/releases/tag/v0.143.6) with official Linux support is out too.

**Comment by bbigras** [comment]
for people who can't wait to try this version (but don't mind rebuilding the whole world and waiting for it), you can use:
```nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs?ref=83aaf6183611b2816a35d3d437eb99177d43378f";
    nixpkgs_zed_pr.url = "github:nixos/nixpkgs?ref=e1d78dd2615ea4ac7e5f95df96b1faeaccf652a9";
    utils.url = "github:numtide/flake-utils";
  };
  outputs = { self, nixpkgs, utils, nixpkgs_zed_pr }: utils.lib.eachDefaultSystem (system:
    let
      pkgs = nixpkgs.legacyPackages.${system};
      zed-editor = pkgs.callPackage "${nixpkgs_zed_pr}/pkgs/by-name/ze/zed-editor/package.nix" { };

      zed-fhs = pkgs.buildFHSUserEnv {
        name = "zed";
        targetPkgs = pkgs:
          [
            zed-editor
          ];
        runScript = "zed";
      };
    in
    {
      devShell = pkgs.mkShell {
        buildInputs = [
          zed-fhs
        ];
      };
    }
  );
}
```

**Comment by rayanamal** [comment]
Thank y'all so much, I'm so excited to finally try it out!

**Comment by istudyatuni** [comment]
Why is this PR draft? Mentioned PR with rust already merged

**Comment by bbigras** [comment]
> Why is this PR draft? Mentioned PR with rust already merged

It's only merged in staging, not master.

**Comment by domenkozar** [comment]
Why doesn't the PR target staging?

**Comment by bbigras** [comment]
> Why doesn't the PR target staging?

How does it work? Do you target 83aaf6183611b2816a35d3d437eb99177d43378f or the branch? and what happens when that commit ends up in master?

**Comment by bbigras** [comment]
v0.143.7 is out.

**Comment by OctoRocket** [comment]
[v0.144.3](https://github.com/zed-industries/zed/releases/tag/v0.144.3) is out now

**Comment by JohnRTitor** [comment]
https://github.com/NixOS/nixpkgs/pull/320250 has landed on `staging-next`. Retargeted and rebased accordingly.

**Comment by JohnRTitor** [comment]
@ofborg build zed-editor

**Review by JohnRTitor — APPROVED** [review]
Built locally.

**Comment by JohnRTitor** [comment]
Result of `nixpkgs-review pr 324549` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>zed-editor</li>
  </ul>
</details>

**Comment by OctoRocket** [comment]
Does this fix the LSP problem?

**Comment by JohnRTitor** [comment]
You can easily check by using 
`nix run github:nixos/nixpkgs/refs/pull/324549/merge#zed-editor`.

**Comment by arunoruto** [comment]
> You can easily check by using `nix run github:nixos/nixpkgs/refs/pull/324549/merge#zed-editor`.

Sorry for asking in a closed pull request, but I am also eager to try it out, and I am getting the following error:
```sh
error:
       … while fetching the input 'github:nixos/nixpkgs/refs/pull/324549/merge'

       error: unable to download 'https://api.github.com/repos/nixos/nixpkgs/commits/refs/pull/324549/merge': HTTP error 422

       response body:

       {
         "message": "No commit found for SHA: refs/pull/324549/merge",
         "documentation_url": "https://docs.github.com/rest/commits/commits#get-a-commit",
         "status": "422"
       }
```
Am I doing something wrong?

**Comment by jansol** [comment]
> Am I doing something wrong?

The original branch of this PR has been deleted. You'll have to fetch the staging-next branch instead. Or some other branch that has these changes.

**Comment by rayanamal** [comment]
Does anybody know when this will land on nixos-unstable?

**Comment by JohnRTitor** [comment]
This is mainly blocked on https://github.com/NixOS/nixpkgs/pull/328673

You can track when it lands in https://nixpk.gs/pr-tracker.html?pr=324549

**Comment by arunoruto** [comment]
The package is now on unstable!

**Pull request merged**
