### PR TITLE
Revert "python3.pkgs.cryptography: use openssl_1_1"

### PR DESCRIPTION
**Pull request by NickCao**
This reverts commit 8b1f16573cc6fa50facc3fe3154ba437e64a9220.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by NickCao** [comment]
@ajs for context why it was pinned to openssl_1_1.

**Comment by ajs124** [comment]
I seem to remember talking to @mweinelt about this, at the time. iirc the test suite didn't pass or something like that?

**Comment by mweinelt** [comment]
I think it broke pyopenssl?

**Comment by NickCao** [comment]
Shall I rebase this for python-update, or you just cherry-pick it?

**Comment by mweinelt** [comment]
It's too early, we have just landed the last python-updates this week. I'll pick the change when it's time.

**Comment by mweinelt** [comment]
> Please don't make any reverts without writing the explanation or reason in the commit message.

This request is still open.

**Comment by mweinelt** [comment]
85bd9a9caa2d6c0f339eb77f144001baf5d62988

**Pull request closed without merging**
