### PR TITLE
Fixed fatal error with libX11 and libGL while building playonlinux

### PR DESCRIPTION
**Pull request by schonfinkel**
This is my first attempt on fixing a package on NixOS, any advice is extremely welcome. 

###### Motivation for this change

I was experiencing the following errors while building playonlinux 4.3.4 on unstable [19.09pre171786.34aa254f9eb (Loris)]

```
fatal error: X11/Xlib.h: No such file or directory
fatal error: GL/gl.h: No such file or directory
```

###### Things done

I've changed some `buildInputs` and `makeLibraryPath` until `nix-build -A playonlinux` finally compiled.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Infinisil** [comment]
Nice, I'm still getting

```
/home/infinisil/.PlayOnLinux//tmp/check_dd_x86: error while loading shared libraries: libGL.so.1: wrong ELF class: ELFCLASS64
```

and a window pop up saying "PlayOnLinux is unable to find 32bits OpenGL libraries. You might encounter problem with your games".

On NixOS this can probably be fixed by telling it about /run/opengl-driver-32/lib, there's a bunch of examples of this in nixpkgs

**Comment by Infinisil** [comment]
And I actually think you should get the drivers from `/run/opengl-driver/lib` instead of adding `libGL`

**Comment by mtrsk** [comment]
Ok, this is really something with my config then. Will close this and the issue I've opened some days ago.

**Comment by Infinisil** [comment]
No, I mean, you should wrap the package definition with /run/opengl-driver/lib instead of adding it to the library paths. The fix for the build is still needed, it doesn't work on master

**Comment by mtrsk** [comment]
@Infinisil Oh I see, sorry. I'll take a better look then and submit once it works.

**Comment by jerith666** [comment]
The errors about OpenGL at runtime are not new, I wouldn't let them hold up merging this -- at least it gets it to build.

**Comment by mtrsk** [comment]
> The errors about OpenGL at runtime are not new, I wouldn't let them hold up merging this -- at least it gets it to build.

Indeed, but some problems persist. Now playonlinux can't create 64 bits volumes due to wine crashing, 32 bits are fine as far as I can see.

**Review by infinisil — APPROVED** [review]
I guess let's merge this then

**Comment by matthewbauer** [comment]
Make sure to backport and unmark as broken.

**Review by matthewbauer — APPROVED** [review]

**Comment by Infinisil** [comment]
Where is it marked as broken?

**Comment by matthewbauer** [comment]
> Where is it marked as broken?

171eb304c6cfa201ed8345de81cbcd82fdf398fa

**Comment by Infinisil** [comment]
I rebased on top of the commit that marked it as broken, then amended the fixing commit to remove the `broken = true` again.

**Comment by Infinisil** [comment]
Cherry-picked to 19.03 in 3d98c52b23a0e0fb79f0236e985b52a68dcfc46d (and parent)

Should I also backport to 18.09?

**Pull request merged**
