### PR TITLE
dmenu: allow config file argument

### PR DESCRIPTION
**Pull request by 0david0mp**
## Description of changes

Just allowing for a config file as arg (like in [slstatus](https://github.com/NixOS/nixpkgs/blob/88470d6246d6e6673f17961772f889fee3504e04/pkgs/applications/misc/slstatus/default.nix#L30) or [dwm](https://github.com/NixOS/nixpkgs/blob/88470d6246d6e6673f17961772f889fee3504e04/pkgs/applications/window-managers/dwm/default.nix#L27))

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by 0david0mp** [comment]
@IogaMaster just saw your [video](https://www.youtube.com/watch?v=1ED9b7ERTzI), i'm trying to learn nixos and distrohoping in a month or so.
i saw that there was this inconsistency and thought it is a good option for learning to contribute to nixpkgs!

it's a very small change, any advice is greeted. thanks in advance!

**Comment by 0david0mp** [comment]
also, i haven't been able to run `nixpkgs-review rev HEAD`, it states something about a bad revision (`d474941b8a95891e0bd79e37f3548038b35848ac`), dont really know what it means

**Comment by superherointj** [comment]
If you are to refactor `dmenu` move it to `by-name` directory structure.

**Comment by superherointj** [comment]
This change you are trying to make it weird. A package should not have a configFile. I don't get that.

**Comment by Qusic** [comment]
looks similar to what `dwm` does with `conf` and good to me. please format your code with `nixfmt`.

**Comment by 0david0mp** [comment]
should i just move the `dmenu` or is there something else to be done?

**Comment by Qusic** [comment]
> should i just move the dmenu directory

did you mean moving to pkgs/by-name? i think it'd be better to do that in a separate PR.


> is there something else to be done

please read this [section](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions)
basically you need to squash format change commit into the other one and use a meaningful commit message 
"dmenu: allow config file argument" instead of "refactor"
image

as for nixpkgs-review, please try it again using pr number after pushing your final changes, and that should be less error prone. [usage](https://github.com/Mic92/nixpkgs-review?tab=readme-ov-file#usage)

**Comment by 0david0mp** [comment]
This should be everything! I don't really care about moving the directory, I was answering another comment, I guess it was deleted.

Anyway, thanks for helping me learning how to contribute!
Any other thing needed you ask me.

**Comment by Qusic** [comment]
that's weird :/
anyway i ran it myself and everything is good, just as expected for such a small change.

Result of `nixpkgs-review pr 321234` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>38 packages built:</summary>
  <ul>
    <li>connman_dmenu</li>
    <li>dmensamenu</li>
    <li>dmensamenu.dist</li>
    <li>dmenu</li>
    <li>dmenu-bluetooth</li>
    <li>emojipick</li>
    <li>git-credential-manager</li>
    <li>j4-dmenu-desktop</li>
    <li>keepmenu</li>
    <li>keepmenu.dist</li>
    <li>krunner-pass</li>
    <li>pass</li>
    <li>pass-wayland</li>
    <li>passExtensions.pass-audit</li>
    <li>passExtensions.pass-audit.man</li>
    <li>passExtensions.pass-import</li>
    <li>passExtensions.pass-import.dist</li>
    <li>passff-host</li>
    <li>python311Packages.bundlewrap-pass</li>
    <li>python311Packages.bundlewrap-pass.dist</li>
    <li>python311Packages.dmenu-python</li>
    <li>python311Packages.dmenu-python.dist</li>
    <li>python311Packages.keyring-pass</li>
    <li>python311Packages.keyring-pass.dist</li>
    <li>python312Packages.bundlewrap-pass</li>
    <li>python312Packages.bundlewrap-pass.dist</li>
    <li>python312Packages.dmenu-python</li>
    <li>python312Packages.dmenu-python.dist</li>
    <li>python312Packages.keyring-pass</li>
    <li>python312Packages.keyring-pass.dist</li>
    <li>qtpass</li>
    <li>rofi-pass</li>
    <li>rofi-pass-wayland</li>
    <li>surf</li>
    <li>surf-display</li>
    <li>tessen</li>
    <li>wofi-pass</li>
    <li>ytfzf</li>
  </ul>
</details>

**Review by Qusic — APPROVED** [review]

**Comment by 0david0mp** [comment]
ok perfect, you have been a lot of help, thanks!

**Review by fpletz — APPROVED** [review]

**Pull request merged**
