### PR TITLE
python2Packages: remove superfluous overrides

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/issues/148779

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Trac also has a module and a tests that we should remove.

**Comment by mweinelt** [comment]
Result of `nixpkgs-review pr 152907` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>bareos</li>
    <li>python38Packages.hug</li>
    <li>python39Packages.hug</li>
  </ul>
</details>
<details>
  <summary>2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>gns3-server</li>
    <li>python38Packages.mailman</li>
  </ul>
</details>
<details>
  <summary>45 packages built:</summary>
  <ul>
    <li>alerta-server</li>
    <li>bitbucket-cli</li>
    <li>ceph (ceph-dev)</li>
    <li>ceph-client</li>
    <li>ceph-csi</li>
    <li>cura</li>
    <li>gns3-gui</li>
    <li>home-assistant</li>
    <li>libceph</li>
    <li>mailman</li>
    <li>moodle-dl</li>
    <li>moz-phab</li>
    <li>octavePackages.symbolic</li>
    <li>octoprint</li>
    <li>pylode</li>
    <li>python38Packages.WSME</li>
    <li>python38Packages.django-rq</li>
    <li>python38Packages.falcon</li>
    <li>python38Packages.jupyterlab</li>
    <li>python38Packages.jupyterlab-git</li>
    <li>python38Packages.jupyterlab_server</li>
    <li>python38Packages.jupytext</li>
    <li>python38Packages.openapi-core</li>
    <li>python38Packages.pecan</li>
    <li>python38Packages.sentry-sdk</li>
    <li>python38Packages.variants</li>
    <li>python38Packages.webargs</li>
    <li>python39Packages.django-rq</li>
    <li>python39Packages.falcon</li>
    <li>python39Packages.jupyterlab</li>
    <li>python39Packages.jupyterlab-git</li>
    <li>python39Packages.jupyterlab_server</li>
    <li>python39Packages.jupytext</li>
    <li>python39Packages.mailman</li>
    <li>python39Packages.mailman-hyperkitty</li>
    <li>python39Packages.openapi-core</li>
    <li>python39Packages.pecan</li>
    <li>python39Packages.sentry-sdk</li>
    <li>python39Packages.variants</li>
    <li>python39Packages.webargs</li>
    <li>qemu_full</li>
    <li>rainbowstream</li>
    <li>sambaFull (samba4Full)</li>
    <li>tribler</li>
    <li>xenomapper</li>
  </ul>
</details>

**Review by jonringer — APPROVED** [review]
diff LGTM

Thank you for doing this. Looks like it was a lot of work

**Comment by mweinelt** [comment]
Rebased after #153012.

**Pull request merged**
