### PR TITLE
python311Packages.aenum: 3.1.12 -> 3.1.15

### PR DESCRIPTION
**Pull request by fabaff**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 241853` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages failed to build:</summary>
  <ul>
    <li>home-assistant-component-tests.vulcan</li>
    <li>python310Packages.okta</li>
    <li>python310Packages.okta.dist</li>
    <li>python311Packages.okta</li>
    <li>python311Packages.okta.dist</li>
    <li>python311Packages.vulcan-api</li>
    <li>python311Packages.vulcan-api.dist</li>
  </ul>
</details>
<details>
  <summary>48 packages built:</summary>
  <ul>
    <li>csvkit</li>
    <li>csvkit.dist</li>
    <li>home-assistant-component-tests.homematicip_cloud</li>
    <li>home-assistant-component-tests.wallbox</li>
    <li>onlykey-agent</li>
    <li>onlykey-agent.dist</li>
    <li>onlykey-cli</li>
    <li>onlykey-cli.dist</li>
    <li>python310Packages.aenum</li>
    <li>python310Packages.aenum.dist</li>
    <li>python310Packages.agate-dbf</li>
    <li>python310Packages.agate-dbf.dist</li>
    <li>python310Packages.awswrangler</li>
    <li>python310Packages.awswrangler.dist</li>
    <li>python310Packages.cassandra-driver</li>
    <li>python310Packages.cassandra-driver.dist</li>
    <li>python310Packages.dbf</li>
    <li>python310Packages.dbf.dist</li>
    <li>python310Packages.gremlinpython</li>
    <li>python310Packages.gremlinpython.dist</li>
    <li>python310Packages.home-assistant-chip-clusters</li>
    <li>python310Packages.home-assistant-chip-clusters.dist</li>
    <li>python310Packages.homematicip</li>
    <li>python310Packages.homematicip.dist</li>
    <li>python310Packages.intellifire4py</li>
    <li>python310Packages.intellifire4py.dist</li>
    <li>python310Packages.vulcan-api</li>
    <li>python310Packages.vulcan-api.dist</li>
    <li>python310Packages.wallbox</li>
    <li>python310Packages.wallbox.dist</li>
    <li>python311Packages.aenum</li>
    <li>python311Packages.aenum.dist</li>
    <li>python311Packages.agate-dbf</li>
    <li>python311Packages.agate-dbf.dist</li>
    <li>python311Packages.awswrangler</li>
    <li>python311Packages.awswrangler.dist</li>
    <li>python311Packages.cassandra-driver</li>
    <li>python311Packages.cassandra-driver.dist</li>
    <li>python311Packages.dbf</li>
    <li>python311Packages.dbf.dist</li>
    <li>python311Packages.gremlinpython</li>
    <li>python311Packages.gremlinpython.dist</li>
    <li>python311Packages.home-assistant-chip-clusters</li>
    <li>python311Packages.home-assistant-chip-clusters.dist</li>
    <li>python311Packages.homematicip</li>
    <li>python311Packages.homematicip.dist</li>
    <li>python311Packages.wallbox</li>
    <li>python311Packages.wallbox.dist</li>
  </ul>
</details>

**Review by jbgosselin — APPROVED** [review]

**Review by jbgosselin — CHANGES_REQUESTED** [review]
I actually think there is a regression introduced with aenum and that's why the tests are not passing anymore. 

I think since a certain version, aenum seems to require `*.value` to be called in order to retrieve the underlying value instead of the type name.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 241853` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python310Packages.python-ndn</li>
    <li>python310Packages.python-ndn.dist</li>
    <li>python311Packages.awswrangler</li>
    <li>python311Packages.awswrangler.dist</li>
  </ul>
</details>
<details>
  <summary>55 packages built:</summary>
  <ul>
    <li>csvkit</li>
    <li>csvkit.dist</li>
    <li>home-assistant-component-tests.homematicip_cloud</li>
    <li>home-assistant-component-tests.vulcan</li>
    <li>home-assistant-component-tests.wallbox</li>
    <li>onlykey-agent</li>
    <li>onlykey-agent.dist</li>
    <li>onlykey-cli</li>
    <li>onlykey-cli.dist</li>
    <li>python310Packages.aenum</li>
    <li>python310Packages.aenum.dist</li>
    <li>python310Packages.agate-dbf</li>
    <li>python310Packages.agate-dbf.dist</li>
    <li>python310Packages.awswrangler</li>
    <li>python310Packages.awswrangler.dist</li>
    <li>python310Packages.cassandra-driver</li>
    <li>python310Packages.cassandra-driver.dist</li>
    <li>python310Packages.dbf</li>
    <li>python310Packages.dbf.dist</li>
    <li>python310Packages.gremlinpython</li>
    <li>python310Packages.gremlinpython.dist</li>
    <li>python310Packages.home-assistant-chip-clusters</li>
    <li>python310Packages.home-assistant-chip-clusters.dist</li>
    <li>python310Packages.homematicip</li>
    <li>python310Packages.homematicip.dist</li>
    <li>python310Packages.intellifire4py</li>
    <li>python310Packages.intellifire4py.dist</li>
    <li>python310Packages.okta</li>
    <li>python310Packages.okta.dist</li>
    <li>python310Packages.vulcan-api</li>
    <li>python310Packages.vulcan-api.dist</li>
    <li>python310Packages.wallbox</li>
    <li>python310Packages.wallbox.dist</li>
    <li>python311Packages.aenum</li>
    <li>python311Packages.aenum.dist</li>
    <li>python311Packages.agate-dbf</li>
    <li>python311Packages.agate-dbf.dist</li>
    <li>python311Packages.cassandra-driver</li>
    <li>python311Packages.cassandra-driver.dist</li>
    <li>python311Packages.dbf</li>
    <li>python311Packages.dbf.dist</li>
    <li>python311Packages.gremlinpython</li>
    <li>python311Packages.gremlinpython.dist</li>
    <li>python311Packages.home-assistant-chip-clusters</li>
    <li>python311Packages.home-assistant-chip-clusters.dist</li>
    <li>python311Packages.homematicip</li>
    <li>python311Packages.homematicip.dist</li>
    <li>python311Packages.okta</li>
    <li>python311Packages.okta.dist</li>
    <li>python311Packages.python-ndn</li>
    <li>python311Packages.python-ndn.dist</li>
    <li>python311Packages.vulcan-api</li>
    <li>python311Packages.vulcan-api.dist</li>
    <li>python311Packages.wallbox</li>
    <li>python311Packages.wallbox.dist</li>
  </ul>
</details>

**Review by jbgosselin — APPROVED** [review]

**Review by jbgosselin — CHANGES_REQUESTED** [review]
I really think we need to lock the aenum dependency on the okta python sdk.
Commenting the tests out make them pass but there is a reason they are not passing.
I see there is a PR on the okta repo that lock aenum dependency https://github.com/okta/okta-sdk-python/pull/366/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7 we should do the same here and keep the commented out tests.
If we merge this PR as is, it will break the okta python package and potentially its dependencies.

**Comment by fabaff** [comment]
Update was included in #251878.

**Pull request closed without merging**
