### PR TITLE
grafana: 8.0.5 -> 8.0.6

### PR DESCRIPTION
**Pull request by LeSuisse**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>grafana</li>
  </ul>
</details>

### CODE REVIEW

**Comment by Ma27** [comment]
How does this work when the tag was "last changed" two hours ago: https://github.com/grafana/grafana/releases/tag/v8.0.6 ?

**Comment by LeSuisse** [comment]
It cannot. The tag 8.0.6 was published yesterday and it seems it has been moved today :neutral_face:

**Comment by Ma27** [comment]
Please update to the tag which was release a few hours ago then.

**Comment by LeSuisse** [comment]
Hum there is something strange happening here.
The SHA-256 sets for `srcStatic` is the same that the one currently displayed on the Grafana download page `252a4d022f4dbd9a68d07cdd0e6762d62fa53462f294781cb53e8f3d61cd8649`

Screenshot Grafana download page

If I attempt to get the archive from another endpoint I get another archive with the SHA-256 `827656b523e9eed3e51cba2b8e547eaa79f7656ca8a8bf735591d1210b35627a`. And that does not match what's retrieved by OfBorg (`04b70a13d8e4f608bac5d59f8596646f2c764abb75b8b857914db81f67cd9cb2`).

I suspect something wrong happened with the release and there are some caches at play. I will try again in a few hours.

For reference I have a diffoscope HTML report of the two archives I have retrieved can be found here: https://gist.github.com/LeSuisse/4d0f7e4a0866b42499276ed1ae2f5c20

**Comment by Ma27** [comment]
@LeSuisse in case this didn't help, I'd suggest to notify Grafana's support. This could be the same problem as in https://github.com/NixOS/nixpkgs/pull/104794.

**Comment by LeSuisse** [comment]
Yeah I tried [to reach out to them on Twitter](https://twitter.com/el_suisse/status/1415930792816037890) without luck so far. I'm trying the contact form right now.

**Comment by LeSuisse** [comment]
Just to keep this ticket updated: at this time I have not heard back from Grafana Labs.

I have created a thread in their community forum so hopefully someone will notice it https://community.grafana.com/t/grafana-oss-8-0-6-tarball-checksum-does-not-always-match/50785

**Comment by LeSuisse** [comment]
I heard back from Grafana Labs, the issue should now be fixed.

> Thank you for your patience, yes you are right, we’ve noticed a few issues all related to this same thing. 
> We’re hopeful that this has been resolved as of this afternoon as it seems our CDN cache was a bit out of whack. 

I tested from different endpoints, I now get the expected tarball.
The PR has been rebased.

**Review by Ma27 — APPROVED** [review]

**Pull request merged**
