### PR TITLE
 pkgs/development: switch to fetchFromGitHub part 2

### PR DESCRIPTION
**Pull request by Stunkymonkey**
###### Motivation for this change
use `fetchFromGitHub`

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kranzes** [comment]
Please change `hash` to `sha256`.
`sed -i 's/hash/sha256/g' default.nix`

**Comment by Kranzes** [comment]
I have already told you why `hash` shouldn't be used in a previous PR like this.

**Comment by Stunkymonkey** [comment]
sorry forgot that again. should be fixed

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 143850 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>31 packages built:</summary>  <ul>    <li>haxe</li>    <li>haxePackages.hxcpp</li>    <li>haxePackages.hxcs</li>    <li>haxePackages.hxjava</li>    <li>haxePackages.hxnodejs_4</li>    <li>haxe_4_0</li>    <li>haxe_4_1</li>    <li>ocamlPackages.eliom</li>    <li>ocamlPackages.iri</li>    <li>ocamlPackages.ocsigen-start</li>    <li>ocamlPackages.ocsigen-toolkit</li>    <li>ocamlPackages.ocsigen_server</li>    <li>ocamlPackages.sedlex</li>    <li>ocamlPackages.twt</li>    <li>ocamlPackages.xml-light</li>    <li>python38Packages.audiotools</li>    <li>python38Packages.etcd</li>    <li>python38Packages.jsonwatch</li>    <li>python38Packages.livestreamer</li>    <li>python38Packages.livestreamer-curses</li>    <li>python38Packages.pep257</li>    <li>python38Packages.pytest-pep257</li>    <li>python39Packages.audiotools</li>    <li>python39Packages.etcd</li>    <li>python39Packages.jsonwatch</li>    <li>python39Packages.livestreamer</li>    <li>python39Packages.livestreamer-curses</li>    <li>python39Packages.pep257</li>    <li>python39Packages.pytest-pep257</li>    <li>stog</li>    <li>virt-top</li>  </ul></details>

**Pull request merged**
