### PR TITLE
viber: 16.1.0.37 -> 21.8.0.11 

### PR DESCRIPTION
**Pull request by pyrox0**
## Description of changes
Updates this package to the latest version, which also removes the dependency on openssl 1.1. There were a few more that needed to be added, but nothing major. There's no upstream changelog as far as I can see, so I can't link to one.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by onny** [comment]
Result of `nixpkgs-review pr 323215` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>viber</li>
  </ul>
</details>

**Comment by onny** [comment]
Thank you!

**Comment by sinh-x** [comment]
There is hash-mismatch with viber latest on unstable channel.

```
viber.deb> trying https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb
viber.deb>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
viber.deb>                                  Dload  Upload   Total   Spent    Left  Speed
viber.deb> 100  154M  100  154M    0     0  23.2M      0  0:00:06  0:00:06 --:--:-- 24.7M
error: hash mismatch in fixed-output derivation '/nix/store/v5zzfp2z0a6q4b4f4qrjfpbdqx9417vm-viber.deb.drv':
         specified: sha256-RrObmN21QOm5nk0R2avgCH0ulrfiUIo2PnyYWvQaGVw=
            got:    sha256-9WHiI2WlsgEhCPkrQoAunmF6lSb2n5RgQJ2+sdnSShM=
```

**Comment by raceordie690** [comment]
This seems to still be broken.  What's the work around?   I've tried creating the following override but it doesn't override anything.... 

```
  nixpkgs.overlays = [
    ( final: previous: {
      viber = final.unstable.viber.overrideAttrs (oldAttrs: {
        src = final.fetchurl {
          url = "https://web.archive.org/web/20240114085219/https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb";
          sha256 = "sha256-RrObmN21QOm5nk0R2avgCH0ulrfiUIo2PnyYWvQaGVw"; # same hash as original commit in this PR https://github.com/NixO
S/nixpkgs/pull/323215
        };
      });
    })
  ];
```

Robert

**Comment by onny** [comment]
@raceordie690 Please try https://github.com/NixOS/nixpkgs/pull/336969 should fix the issue

**Comment by sinh-x** [comment]
@raceordie690 Robert, the overlay should be depend on your nixos setup the code is base on my setup if you setup unstable to be your nixpkgs main inupt then ithe overlay could be a slightly different.

it you need some help regard the overlay config feel free to message me. Otherwise thank to @onny  for the fix. :)

**Pull request merged**
