### PR TITLE
ytmdl: improve expressions

### PR DESCRIPTION
**Pull request by dotlambda**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/pull/127000#pullrequestreview-699068576

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by j0hax** [comment]
Result of `nixpkgs-review pr 129381` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li>python38Packages.itunespy</li>
    <li>python38Packages.pydes</li>
    <li>python38Packages.youtube-search</li>
    <li>python39Packages.itunespy</li>
    <li>python39Packages.pydes</li>
    <li>python39Packages.youtube-search</li>
    <li>ytmdl</li>
  </ul>
</details>

**Comment by dotlambda** [comment]
@j0hax You should consider applying https://github.com/deepjyoti30/ytmdl/commit/37ba821d9692249c1fa563505cf60bd11b8e209e using `fetchpatch`.

**Review by j0hax — APPROVED** [review]
LGTM, thank you for getting around to these fixes before I did!

I'm aware of the bug, applying https://github.com/deepjyoti30/ytmdl/commit/37ba821d9692249c1fa563505cf60bd11b8e209e is something I will PR as soon as this one closes.

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 129381` at 3a5eb40f run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built successfully:</summary>
  <ul>
    <li>python38Packages.itunespy</li>
    <li>python38Packages.pydes</li>
    <li>python38Packages.youtube-search</li>
    <li>python39Packages.itunespy</li>
    <li>python39Packages.pydes</li>
    <li>python39Packages.youtube-search</li>
    <li>ytmdl</li>
  </ul>
</details>

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 129381 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>7 packages built:</summary>  <ul>    <li>python38Packages.itunespy</li>    <li>python38Packages.pydes</li>    <li>python38Packages.youtube-search</li>    <li>python39Packages.itunespy</li>    <li>python39Packages.pydes</li>    <li>python39Packages.youtube-search</li>    <li>ytmdl</li>  </ul></details>

**Pull request merged**
