### PR TITLE
kdepim: init at 16.04.2

### PR DESCRIPTION
**Pull request by vandenoever**
###### Motivation for this change

These are the dependencies that do not require qtwebengine or qtwebkit.
###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by vandenoever** [comment]
@ttuegel @FRidh Would you have a look at this PR?

**Comment by FRidh** [comment]
It looks good to me, but unless we have a working package that requires these additions, I don't think we should merge. It would only require extra maintenance but provide nothing extra and therefore I suggest to keep the branch, and merge it as soon as it does result in a working kontact.

**Comment by vandenoever** [comment]
I agree.

**Comment by vandenoever** [comment]
For kdepim v16.04 we need QtWebKit. This is no longer supported by Qt Company for Qt 5.6, but it's still available and still compiles.

https://marc.info/?l=kde-pim&m=146710943012618&w=2

**Comment by vandenoever** [comment]
Most distros still ship QtWebKit for Qt 5.6.1.

https://marc.info/?l=kde-pim&m=146712084316914&w=2

**Comment by ttuegel** [comment]
@vandenoever You can get QtWebkit 5.6 from the Git repository, even though it is not supported or released.

**Comment by vandenoever** [comment]
@ttuegel there are even still tarballs. The QtWebKit tarball is even listed in srcs.nix. So you're fine with restoring qtwebkit and kf5webkit? I'm asking because you removed them, probably hoping we could get by with only one browser implementation.

**Comment by ttuegel** [comment]
@vandenoever I removed them because there was no tarball for 5.6.0; I guess Qt upstream decided to release them again.

**Comment by vandenoever** [comment]
kdepim now compiles. but the runtime environment is not good yet. kmail is not in the path after installing kde5.kdepim

**Comment by garbas** [comment]
@vandenoever this is still work in progress, right?

**Comment by vandenoever** [comment]
Yes, it depend on #16561 which has not landed yet. But even so it's not done yet.

Getting all the paths right for runtime takes some doing.

**Comment by vandenoever** [comment]
replace by https://github.com/NixOS/nixpkgs/pull/20531

**Pull request closed without merging**
