### PR TITLE
i2p: 0.9.28 -> 0.9.30 (and build wrapper from source) (and for 32bit)

### PR DESCRIPTION
**Pull request by photm5**
###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS (only built on 32bit)
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by joachifm** [comment]
cc @edwtjo @joelmo

**Comment by joachifm** [comment]
Per travis, this PR seems to break x86_64 builds. Please investigate.

**Comment by shak-mar** [comment]
Oops, that's obviously because I use `build32.sh` in all situations.

**Comment by shak-mar** [comment]
Interesting, the testsuite is only built on 64bit linux.  From looking at the makefile, it is only built, not executed there, so I'll simply disable that.

**Review by 0xABAB — APPROVED** [review]

**Pull request merged**
