### PR TITLE
nixos/acme: Custom ACME endpoint

### PR DESCRIPTION
**Pull request by picnoir**
###### Motivation for this change

We currently do not allow users to setup a custom ACME endpoint in `config.security.acme` and hardcode the Let's Encrypt production/staging endpoints.

Let's encrypt is not the only entity issuing certificates using the ACME protocol anymore [[1]](https://en.wikipedia.org/wiki/Automated_Certificate_Management_Environment#CAs_&_PKIs_that_offer_ACME_certificates), this PR allow users to choose an alternative issuer both on a per-certificate and global scope.

This PR also has the nice side effect of allowing us to drop the `pebble` patch we use in the associated nixos test by using `pebble`'s custom directory endpoint instead of the boulder one.

PR idea was suggested by a [`pebble` maintainer](https://github.com/letsencrypt/pebble/issues/283#issuecomment-545123242).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @flokli @aszlig

### CODE REVIEW

**Comment by NinjaTrappeur** [comment]
Could somebody run `@GrahamcOfBorg test acme` to trigger the relevant nixos test?

I don't have the appropriate credentials to do that yet (https://github.com/NixOS/ofborg/pull/406).

**Comment by NinjaTrappeur** [comment]
Might be blocked by https://github.com/NixOS/nixpkgs/commit/501314c9e8b2dcecc76b5eb7a8fcae6b425efbe8#issuecomment-547338521

**Comment by flokli** [comment]
Can we refactor the `production` option to influence `server`, or maybe just deprecate it alltogether?

**Comment by rnhmjoj** [comment]
@GrahamcOfBorg test acme

**Comment by NinjaTrappeur** [comment]
@GrahamcOfBorg test acme

**Comment by NinjaTrappeur** [comment]
@GrahamcOfBorg test acme

**Review by flokli — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
> Can we refactor the `production` option to influence `server`, or maybe just deprecate it alltogether?

I don't think this was an improvement to the module. You can't remember the server URL and when testing you often want to switch to the staging server to not trigger the lets encrypt rate limit.

**Pull request merged**
