### PR TITLE
iris-cli: init at 0.1

### PR DESCRIPTION
**Pull request by cafkafk**
## Description of changes

Work in progress to add iris-cli and liblexbor.

See: https://github.com/NixOS/nixpkgs/issues/246442

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cafkafk** [comment]
Currently stuck at https://paste.debian.net/hidden/5d80735b/

**Comment by cafkafk** [comment]
I tried using the latest unstable version of lexbor instead and it still didn't work.

**Comment by cafkafk** [comment]
Got it working, will be cleaning this up now

**Comment by cafkafk** [comment]
> This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:
> 
> https://discourse.nixos.org/t/prs-ready-for-review/3032/2485

I pasted this url accidentaly, this is false (I'll mention it when CI passes)

**Comment by gp2112** [comment]
Already made a pr for lexbor in #246613

**Comment by cafkafk** [comment]
Also, there are some parts of my package definition I prefer, such as:
```nix
  cmakeFlags = [] ++ lib.optionals stdenv.hostPlatform.isStatic [
    "-DLEXBOR_BUILD_TESTS=ON"
    "-DLEXBOR_BUILD_EXAMPLES=ON"
  ];
```

Instead of:
```nix
  buildPhase = ''
    cmake . -DLEXBOR_BUILD_TESTS=ON -DLEXBOR_BUILD_EXAMPLES=ON
    make
  '';
```

**Comment by cafkafk** [comment]
@ofborg eval

**Comment by cafkafk** [comment]
This program isn't really functional, closing in favor of #246613.

**Pull request closed without merging**
