### PR TITLE
ssb-patchwork: 3.17.7 -> 3.18.0

### PR DESCRIPTION
**Pull request by cyplo**
- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by picnoir — APPROVED** [review]
LGTM

**Comment by cyplo** [comment]
@asymmetric @thedavidmeister - any thoughts on this one ? :)

**Comment by asymmetric** [comment]
The SSB DB is borked on my machine so can't really test this :(

**Comment by cyplo** [comment]
@asymmetric - would it make sense to test with a new db, just to see it booting up and getting synced ?

**Comment by asymmetric** [comment]
@cyplo if you provide me with instructions, yes :)

**Comment by thedavidmeister** [comment]
hey i dropped off sb, maybe take me off maintainer for this one :)

**Comment by cyplo** [comment]
Removed you and forced pushed the squashed change @thedavidmeister , thanks for all the help :)

**Pull request merged**
