### PR TITLE
numpy: set lapack,blas library names correctly

### PR DESCRIPTION
**Pull request by matthewbauer**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ericson2314** [comment]
Numpy indeed builds, now checking scipy.

**Comment by Ericson2314** [comment]
SciPy succeed on Linux too. Numpy still fails on darwin, during the install check when lapacke cannot be dlopened for some reason.

**Comment by Ericson2314** [comment]
Ah Ah per https://github.com/NixOS/nixpkgs/pull/83888#issuecomment-616803809 a lack of patchelf and other things is probably causing the dlopen problems. So this PR should be doing enough on the numpy side.

**Review by Ericson2314 — APPROVED** [review]
Strictly better than it was before.

**Comment by matthewbauer** [comment]
Closing in favor of https://github.com/NixOS/nixpkgs/pull/85636

**Pull request closed without merging**
