### PR TITLE
graphite: make systemd create /run directory for us

### PR DESCRIPTION
**Pull request by basvandijk**
###### Motivation for this change

Part of https://github.com/NixOS/nixpkgs/issues/41092.

@peterhoeg I tested your commit and it seems to work fine. If you approve the PR I'll merge it in.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by xeji** [comment]
@GrahamcOfBorg  eval

**Comment by jtojnar** [comment]
What about using `systemd.tmpfiles.rules` for more declarative approach?

**Comment by basvandijk** [comment]
@jtojnar you mean something like:

```
systemd.tmpfiles.rules = [ "d /run/carbon-cache 0700 graphite graphite -" ];
```

how is that more declarative than using `RuntimeDirectory = "carbon-cache"`? Isn't  [RuntimeDirectory](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#RuntimeDirectory=) exactly made for this purpose?

**Comment by Mic92** [comment]
`RuntimeDirectory` is better.

**Comment by Mic92** [comment]
@GrahamcOfBorg test graphite

**Comment by xeji** [comment]
@GrahamcOfBorg test graphite

**Comment by Mic92** [comment]
@GrahamcOfBorg test graphite

**Comment by Mic92** [comment]
The test throw:

```
IOError: [Errno 2] No such file or directory: '/var/db/graphite/log/webapp/info.log'
```

this looks like something else is incorrect in the module.

**Comment by basvandijk** [comment]
Strange, on my system the test completes successfully:

```
$ nix-build nixos/release.nix -A tests.graphite.x86_64-linux
/nix/store/pxc72magi4ym56w0m6cfdqkvgnilsg2d-vm-test-run-graphite
```

**Comment by xeji** [comment]
Test succeeds on my local machine as well (on this branch).

**Review by xeji — APPROVED** [review]

**Comment by Mic92** [comment]
@GrahamcOfBorg test graphite

**Comment by peterhoeg** [comment]
I'm late to the party (we just had kids!), but this is great. Thanks for pushing this past the goal line!

**Comment by xeji** [comment]
@peterhoeg congrats on the kids!

**Pull request merged**
