### PR TITLE
pdfpc, libgee_0_8: Add darwin support

### PR DESCRIPTION
**Pull request by jbaum98**
###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by LnL7** [comment]
I think the platforms for one of the dependencies should also be updated.
```
Package ‘libgee-0.18.0’ in ‘/nix/store/8fzb0a1y40fc61ar3585ajp1vxkb3x30-git-export/pkgs/desktops/gnome-3/3.22/core/libgee/default.nix:21’ is not supported on ‘x86_64-darwin’, refusing to evaluate.
```

**Comment by jbaum98** [comment]
Sorry about the many name changes. Autocorrect got me twice. Thanks @LnL7.

**Comment by LnL7** [comment]
It looks like it's actually [`gnome3.libgee-0.18.0`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/desktops/gnome-3/3.22/core/libgee/default.nix), not sure why that isn't defined top-level.

**Comment by jbaum98** [comment]
I found it in [`all-packages.nix`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/all-packages.nix#L8200) as `libgee_0_8`.

**Comment by LnL7** [comment]
Yes, but that's actually another file https://search.nix.gsc.io/?q=libgee-&i=nope&files=&repos=

**Comment by jbaum98** [comment]
Ohh my bad. I see that I've update the wrong file. I'll get rid of that commit.

**Review by LnL7 — APPROVED** [review]

**Pull request merged**
