### PR TITLE
smartgit: 19.1.1 -> 20.1.4

### PR DESCRIPTION
**Pull request by novafacing**
###### Motivation for this change

Smartgit has received updates and will not open in free mode if not kept at latest. I have simply updated the version and updated a requirement that was crashing the app on my system. Prior to replacing `jre` with `jdk11`, smartgit crashed with error "GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported". This is fixed by updating the java dependency.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tomberek** [comment]
```
anonymous function at /home/tom/.cache/nixpkgs-review/pr-96980/nixpkgs/pkgs/applications/version-management/smartgithg/default.nix:1:1 called with unexpected argument 'jre', at /home/tom/.cache/nixpkgs-review/pr-96980/nixpkgs/lib/customisation.nix:69:16
```

**Comment by SuperSandro2000** [comment]
@novafacing please fix the eval issue.

**Comment by novafacing** [comment]
@SuperSandro2000 I don't have time right this moment (end of semester) but I'll have a fix in in about a week hopefully.

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Pull request closed without merging**
