### PR TITLE
gap: install libgap, add packageSet option

### PR DESCRIPTION
**Pull request by timokau**
3 Commits:

###### add timokau as maintainer

So that I'll be notified on changes which likely impact sage.

###### install libgap

There are some starts of a `make install`, but nothing complete yet.
Upstream now ships a `libgap` as a replacement of the custom one used by
sagemath.

###### add packageSet option

Two reasons for this:

- more fine-grained space/functionality tradeoff

- preparation for the sage 8.6 update, which finally doesn't need a
  downgraded gap anymore but does break when unexpected (non-standard)
  packages are installed. Details: 0ttps://trac.sagemath.org/ticket/26983

The proper way to deal with gap packages would be to create a package
set, package each one individually and have something like gap
equivalent of `python.withPackages`. I am not willing to do that
however.

Previous discussion about package sets here: https://github.com/NixOS/nixpkgs/pull/38754

CC @7c6f434c @ChrisJefferson 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by timokau** [comment]
Notably, gap now defaults to keep only standard packages instead of all packages. That is way less radical than my approach in #38754 and still saves 1G of space.

**Comment by ChrisJefferson** [comment]
Just to say, I could never get NixOS to work properly, so I don't use it any more. I am a GAP developer so I can answer any GAP-specific questions, independant of NixOS.

**Comment by timokau** [comment]
Okay. The main question of this PR is: Is it reasonable to default to only keeping "standard" packages, that is:

- GAPDoc
- primgrp
- SmallGrp
- transgrp
- atlasrep
- autpgrp
- alnuth
- crisp
- ctbllib
- FactInt
- fga
- irredsol
- laguna
- polenta
- polycyclic
- resclasses
- sophus
- tomlib

While also offering the option to either keep all packages (current default behaviour but very large) or keep the absolute minimal package set:

- GAPDoc
- primgrp
- SmallGrp
- transgrp

**Comment by 7c6f434c** [comment]
@ChrisJefferson I guess you also don't use Nix outside NixOS now; do you want to be removed from the list of maintainers (given that maintainers get pinged for Nix-level-only changes)?

**Comment by timokau** [comment]
I have now
- fixed `gap-minimal` to actually point to the minimal version (`gap` points to standard)
- added `gap-full`
- fixed gap-libgap-compatible. Not pretty, but will soon be removed anyways (I plan to work on the sage update after this is merged)

**Comment by timokau** [comment]
If @ChrisJefferson doesn't mind getting pinged on potentially uninteresting changes every once in a while, I think its useful to have someone on board who is involved upstream.

**Comment by 7c6f434c** [comment]
By default, I would put a code comment above maintainer list:

«# We are also grateful to @ChrisJefferson for previous work on the package and the contiunuing help with GAP-related questions from the upstream point of view»

As we know, pinging maintainers is only likely to become more active with the increase in tooling…

**Comment by timokau** [comment]
Didn't properly fix gap-libgap-compatible after all, should work now. I still have to test that sage is also happy with it. I can't wait to remove it altogether.

I'm fine with either the maintainer list or a comment.

**Comment by timokau** [comment]
Yes, that is the case. With this PR there are 3 options:

##### gap-minimal

offers the bare necessities (->~400MB), i.e.

* GAPDoc
* primgrp
* SmallGrp
* transgrp

##### gap (the default)

additionally offers the autoloaded packages (->~700MB)

* atlasrep
* autpgrp
* alnuth
* crisp
* ctbllib
* FactInt
* fga
* irredsol
* laguna
* polenta
* polycyclic
* resclasses
* sophus
* tomlib

##### gap-full

Offers all the packages shipped with the gap distribution (->1.7G)



Does that look good?

**Comment by timokau** [comment]
> I would strongly recommend making the "default" be the set of autoloaded packages

I'll take this as a yes. Rushing this along a bit because the sage 8.5 build has a transient issue on hydra right now that I'm hoping 8.6 will fix. At least there is no point in debugging 8.5 issues anymore.

**Pull request merged**
