### PR TITLE
tree-sitter: add `buildGrammar` to `passthru`

### PR DESCRIPTION
**Pull request by erikarvstedt**
#### Copy of commit msg

`buildGrammar` is useful for building custom grammars.

Also, improve perf by moving `callPackage` out of the fn call.

Use more precise var name: `change` -> `build`.

#### Details

Check that this PR doesn't change build outputs:
```bash
nix-instantiate /path/to/nixpkgs -A tree-sitter.builtGrammars -A vimPlugins.nvim-treesitter.builtGrammars | sha256sum
```

### CODE REVIEW

**Review by oxalica — APPROVED** [review]
Diff LGTM.

**Comment by figsoda** [comment]
https://github.com/NixOS/nixpkgs/pull/198606#issuecomment-1304595012
> The tree-sitter packaging was not intended to be called from outside, especially build-grammar.nix does not have a stable interface.

I would want to hear from @Profpatsch

if we do end up exposing `buildGrammar`, I would also want to have `nvim-treesitter` use `tree-sitter.buildGrammar` instead (changing this line into `inherit (tree-sitter) buildGrammar;`):
https://github.com/NixOS/nixpkgs/blob/3cb1b521bfb52ca94e9c804e5f984c95483c2b36/pkgs/applications/editors/vim/plugins/nvim-treesitter/overrides.nix#L7

**Comment by erikarvstedt** [comment]
@figsoda: done, thanks!

I really think this should be exposed as there's no other practical way for nixpkgs users to build tree-sitter grammars.

**Comment by oxalica** [comment]
@figsoda
> > The tree-sitter packaging was not intended to be called from outside, especially build-grammar.nix does not have a stable interface.
> 
> I would want to hear from Profpatsch
> 
> if we do end up exposing `buildGrammar`, I would also want to have `nvim-treesitter` use `tree-sitter.buildGrammar` instead (changing this line into `inherit (tree-sitter) buildGrammar;`):

I really don't like the current packaging of `tree-sitter` parsers. They lean to `neovim`'s expected file structure and the only users are `neovim` and `emacs`. But since `tree-sitter` is a library, users can write custom parsers and programs using it. If the build function is not exposed, users need to re-implement it or `import` it via path anyway.

**Comment by erikarvstedt** [comment]
I think `tree-sitter.builtGrammars` is generally useful.
Want to access a parser? Grab any `tree-sitter` binding, load a parser from `builtGrammars` (or use `buildGrammar`), done.

**Review by figsoda — APPROVED** [review]
changes lgtm, I like the `source` -> `src` change

I would still wait for a response from profpatsch, but if we don't get one, I think we can merge this

**Comment by SuperSandro2000** [comment]
Please rebase otherwise LGTM

**Comment by erikarvstedt** [comment]
Rebased to master.

**Comment by gvolpe** [comment]
Hey folks, sorry to spoil this PR! I have a few grammar overrides using `extraGrammars` that have stopped working after these changes, and I can't figure out why. I would appreciate any help. 

```nix
{
  ts = prev.tree-sitter.override {
    extraGrammars = {
      tree-sitter-scala = final.tree-sitter-scala-master;
      tree-sitter-tsx = final.tree-sitter-tsx-master;
      tree-sitter-typescript = final.tree-sitter-tsx-master;
    };
  };

  treesitterGrammars = ts.withPlugins (p: [
    p.tree-sitter-scala
    p.tree-sitter-nix
    p.tree-sitter-elm
    p.tree-sitter-haskell
    p.tree-sitter-rust
    p.tree-sitter-markdown
    p.tree-sitter-tsx
    p.tree-sitter-typescript
    p.tree-sitter-smithy
  ]);
}
```

Where the grammar overrides are built in the following overlay.

```nix
{
  tsOverlay = f: p: {
    tree-sitter-scala-master = p.tree-sitter.buildGrammar {
      language = "scala";
      version = inputs.tree-sitter-scala.rev;
      src = inputs.tree-sitter-scala;
    };

    tree-sitter-tsx-master = p.tree-sitter.buildGrammar {
      language = "tsx";
      version = inputs.tree-sitter-typescript.rev;
      src = inputs.tree-sitter-typescript;
    };
  };
}
```

Attempting to build my [Neovim configuration](https://github.com/gvolpe/neovim-flake) results in the following error:

```console
$ nix build .#scala
error: attempt to call something which is not a function but a set

       at /nix/store/hsws025hvigmlqr1r4mfzwkhxnnry8wf-source/pkgs/development/tools/parsing/tree-sitter/default.nix:63:17:

           62|           inherit version;
           63|           src = grammar.src or fetchGrammar grammar;
             |                 ^
           64|           location = grammar.location or null;
(use '--show-trace' to show detailed location information)
```

Any ideas what I'm doing wrong with the new changes?

**Comment by gvolpe** [comment]
Reverting this change fixes the issue. Was that intentional @erikarvstedt ?

```diff
--- a/pkgs/development/tools/parsing/tree-sitter/default.nix
+++ b/pkgs/development/tools/parsing/tree-sitter/default.nix
@@ -60,7 +60,7 @@ let
         buildGrammar {
           language = grammar.language or name;
           inherit version;
-          src = grammar.src or fetchGrammar grammar;
+          src = if grammar ? src then grammar.src else fetchGrammar grammar;
           location = grammar.location or null;
         };
       grammars' = import ./grammars { inherit lib; } // extraGrammars;
```

**Comment by gvolpe** [comment]
Alright, that is definitely a bug, seems to need parens around. This fixes the issue too:

```diff
--- a/pkgs/development/tools/parsing/tree-sitter/default.nix
+++ b/pkgs/development/tools/parsing/tree-sitter/default.nix
@@ -60,7 +60,7 @@ let
         buildGrammar {
           language = grammar.language or name;
           inherit version;
-          src = grammar.src or fetchGrammar grammar;
+          src = grammar.src or (fetchGrammar grammar);
           location = grammar.location or null;
         };
       grammars' = import ./grammars { inherit lib; } // extraGrammars;
```

I'll make a PR shortly.

**Pull request merged**
