### PR TITLE
vimPlugins.arcanist-vim: init at 2016-05-27

### PR DESCRIPTION
**Pull request by lovesegfault**
###### Motivation for this change
I noticed it was missing, also noticed the list was out of ordered and added a commit sorting it again.

**Edit**
I also added https://github.com/jparise/vim-phabricator

@jonringer 
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lovesegfault** [comment]
```
[61 built, 105 copied (1017.4 MiB), 228.3 MiB DL]
https://github.com/NixOS/nixpkgs/pull/79312
30 package built:
vimPlugins.arcanist-vim vimPlugins.coc-git vimPlugins.coc-go vimPlugins.coc-yaml vimPlugins.csv vimPlugins.denite vimPlugins.deoplete-jedi vimPlugins.falcon vimPlugins.fastfold vimPlugins.fugitive vimPlugins.fzf-vim vimPlugins.jedi-vim vimPlugins.lh-brackets vimPlugins.lightline-vim vimPlugins.ncm2 vimPlugins.ncm2-jedi vimPlugins.neomake vimPlugins.neomru vimPlugins.nvim-lsp vimPlugins.quickrun vimPlugins.rust-vim vimPlugins.vim-asterisk vimPlugins.vim-autoformat vimPlugins.vim-devicons vimPlugins.vim-go vimPlugins.vim-gutentags vimPlugins.vim-parinfer vimPlugins.vim-sandwich vimPlugins.vim-snippets vimPlugins.vista-vim
```

**Comment by lovesegfault** [comment]
After rebasing and re-updating today
```
[70 built, 16 copied (2.6 MiB), 0.4 MiB DL]
https://github.com/NixOS/nixpkgs/pull/79312
62 package built:
vimPlugins.nerdtree vimPlugins.airline vimPlugins.ale vimPlugins.arcanist-vim vimPlugins.calendar vimPlugins.coc-eslint vimPlugins.coc-git vimPlugins.coc-go vimPlugins.coc-metals vimPlugins.coc-tsserver vimPlugins.coc-yaml vimPlugins.csv vimPlugins.ctrlp vimPlugins.denite vimPlugins.deoplete-jedi vimPlugins.easymotion vimPlugins.falcon vimPlugins.fastfold vimPlugins.fugitive vimPlugins.fzf-vim vimPlugins.jedi-vim vimPlugins.lh-brackets vimPlugins.lightline-vim vimPlugins.multiple-cursors vimPlugins.ncm2 vimPlugins.ncm2-jedi vimPlugins.neomake vimPlugins.neomru vimPlugins.neosnippet vimPlugins.nvim-lsp vimPlugins.open-browser vimPlugins.open-browser-github-vim vimPlugins.quickrun vimPlugins.rust-vim vimPlugins.snipmate vimPlugins.unicode-vim vimPlugins.vim-addon-actions vimPlugins.vim-addon-background-cmd vimPlugins.vim-addon-goto-thing-at-cursor vimPlugins.vim-addon-mru vimPlugins.vim-addon-mw-utils vimPlugins.vim-addon-nix vimPlugins.vim-addon-other vimPlugins.vim-addon-syntax-checker vimPlugins.vim-addon-toggle-buffer vimPlugins.vim-addon-xdebug vimPlugins.vim-airline-themes vimPlugins.vim-asterisk vimPlugins.vim-autoformat vimPlugins.vim-devicons vimPlugins.vim-go vimPlugins.vim-gutentags vimPlugins.vim-parinfer vimPlugins.vim-phabricator vimPlugins.vim-racer vimPlugins.vim-sandwich vimPlugins.vim-snippets vimPlugins.vim-terraform vimPlugins.vim-themis vimPlugins.vim-wakatime vimPlugins.vista-vim vimPlugins.xptemplate
```

**Comment by lovesegfault** [comment]
de-novo
```
[19 built, 69 copied (368.3 MiB), 78.8 MiB DL]
https://github.com/NixOS/nixpkgs/pull/79312
68 package built:
vimPlugins.nerdtree vimPlugins.YouCompleteMe vimPlugins.airline vimPlugins.ale vimPlugins.ansible-vim vimPlugins.arcanist-vim vimPlugins.calendar vimPlugins.coc-eslint vimPlugins.coc-git vimPlugins.coc-go vimPlugins.coc-metals vimPlugins.coc-tsserver vimPlugins.coc-yaml vimPlugins.csv vimPlugins.ctrlp vimPlugins.defx-nvim vimPlugins.denite vimPlugins.deoplete-jedi vimPlugins.easymotion vimPlugins.falcon vimPlugins.fastfold vimPlugins.ferret vimPlugins.fugitive vimPlugins.fzf-vim vimPlugins.jedi-vim vimPlugins.lh-brackets vimPlugins.lightline-vim vimPlugins.multiple-cursors vimPlugins.ncm2 vimPlugins.ncm2-jedi vimPlugins.neomake vimPlugins.neomru vimPlugins.neosnippet vimPlugins.nvim-gdb vimPlugins.nvim-lsp vimPlugins.open-browser vimPlugins.open-browser-github-vim vimPlugins.quickrun vimPlugins.rust-vim vimPlugins.snipmate vimPlugins.unicode-vim vimPlugins.vim-addon-actions vimPlugins.vim-addon-background-cmd vimPlugins.vim-addon-goto-thing-at-cursor vimPlugins.vim-addon-mru vimPlugins.vim-addon-mw-utils vimPlugins.vim-addon-nix vimPlugins.vim-addon-other vimPlugins.vim-addon-syntax-checker vimPlugins.vim-addon-toggle-buffer vimPlugins.vim-addon-xdebug vimPlugins.vim-airline-themes vimPlugins.vim-asterisk vimPlugins.vim-autoformat vimPlugins.vim-better-whitespace vimPlugins.vim-devicons vimPlugins.vim-go vimPlugins.vim-gutentags vimPlugins.vim-parinfer vimPlugins.vim-phabricator vimPlugins.vim-racer vimPlugins.vim-sandwich vimPlugins.vim-snippets vimPlugins.vim-terraform vimPlugins.vim-themis vimPlugins.vim-wakatime vimPlugins.vista-vim vimPlugins.xptemplate
```

**Comment by lovesegfault** [comment]
cc. @jonringer

**Comment by jonringer** [comment]
sorry, do you mind rebasing again.

Been caught up with moving then was traveling

**Comment by lovesegfault** [comment]
Done, @jonringer :)

Testing

**Comment by lovesegfault** [comment]
Getting a failure of an unrelated plugin:
```
$ nix build --no-link --keep-going --option build-use-sandbox relaxed -f /home/bemeurer/.cache/nixpkgs-review/pr-79312-4/build.nix
builder for '/nix/store/yn670mzi6xggidlfa95zimgmlhd190nj-vimplugin-far-vim-2020-02-12.drv' failed with exit code 1; last 10 log lines:
  unpacking sources
  unpacking source archive /nix/store/ngbhjj2raj3ikvv6py4dq3nq4j4x03iy-source
  source root is source
  patching sources
  configuring
  building
  installing
  Building help tags
  Error detected while processing command line:
  E154: Duplicate tag "g:far#mapping['stoggle_expand_all']" in file /nix/store/iy7s6nplwlw9kdign5xmyyr2b9cvc8zl-vimplugin-far-vim-2020-02-12/share/vim-plugins/far-vim/doc/far.txtFailed to build help tags!
cannot build derivation '/nix/store/4mv1566gnsm9k7v5ai23sf57nx8nlac2-env.drv': 1 dependencies couldn't be built
[0 built (1 failed)]
error: build of '/nix/store/4mv1566gnsm9k7v5ai23sf57nx8nlac2-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/79312
1 package failed to build:
vimPlugins.far-vim

2 package built:
vimPlugins.arcanist-vim vimPlugins.vim-phabricator
```

**Comment by lovesegfault** [comment]
This patch fixes the failure, should I apply it @jonringer ?

```
diff --git a/pkgs/misc/vim-plugins/vim-plugin-names b/pkgs/misc/vim-plugins/vim-plugin-names
index 0fc5edffe48..3081f2383f2 100644
--- a/pkgs/misc/vim-plugins/vim-plugin-names
+++ b/pkgs/misc/vim-plugins/vim-plugin-names
@@ -30,7 +30,6 @@ bogado/file-line
 bohlender/vim-smt2
 brennanfee/vim-gui-position
 bronson/vim-trailing-whitespace
-brooth/far.vim
 carlitux/deoplete-ternjs
 ccarpita/rtorrent-syntax-file
 cespare/vim-toml
```

**Comment by jonringer** [comment]
I posted the issue here: https://github.com/brooth/far.vim/issues/84 it's an upstream issue. If it lasts more than a day, I will mark it broken

**Review by jonringer — APPROVED** [review]
diff LGTM
commits LGTM

failure unrelated to PR, but upstreamed: https://github.com/brooth/far.vim/issues/84
```
[5 built (1 failed), 55 copied (274.7 MiB), 62.5 MiB DL]
error: build of '/nix/store/4mv1566gnsm9k7v5ai23sf57nx8nlac2-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/79312
1 package failed to build:
vimPlugins.far-vim

2 package built:
vimPlugins.arcanist-vim vimPlugins.vim-phabricator
```

**Pull request merged**
