### PR TITLE
maintainers: add presto8

### PR DESCRIPTION
**Pull request by presto8**

### CODE REVIEW

**Comment by h7x4** [comment]
Hello!

We usually don't merge PRs with commits that container only a maintainer entry, to avoid having lots of maintainers without packages. I see you've already made a PR for a package - could you add this commit as the first commit of that PR instead?

**Comment by presto8** [comment]
@h7x4: thanks! I understand and agree with that philosophy! Actually that is exactly what I did over in PR #278804 but I received two separate comments from reviewers to make a separate PR for adding myself as maintainer :) Not sure what to do....

**Comment by presto8** [comment]
For reference:

@[mweinelt](https://github.com/mweinelt) mweinelt [Feb 1, 2024](https://github.com/NixOS/nixpkgs/pull/278804#discussion_r1475374764)

Adding your maintainer handle should be its own commit: maintainers: add presto8.


and

dotlambda 

You need to add yourself to maintainers/maintainer-list.nix in a separate commit.

**Comment by h7x4** [comment]
Ah, I think there's been a misunderstanding. The comments were about adding yourself as a maintainer in a separate commit, not an entirely new PR 😅

**Comment by presto8** [comment]
Oh I see, two commits in the same PR?

**Pull request closed without merging**
