### PR TITLE
Revert "roc-toolkit: 0.3.0 -> 0.4.0"

### PR DESCRIPTION
**Pull request by superherointj**
Revert "roc-toolkit: 0.3.0 -> 0.4.0"

Reverts NixOS/nixpkgs#320870

Broke pipewire.

### CODE REVIEW

**Comment by superherointj** [comment]
ping @noblepayne

**Comment by K900** [comment]
No it didn't? How did it break?

**Comment by CyberShadow** [comment]
> No it didn't? How did it break?

Well, just the `roc-toolkit` support.

I get:

```
Jun 23 19:20:56 t580 pipewire[1290783]: 19:20:56.677 [1290783] [err] roc_api: bad configuration: failed to select packet_encoding matching frame_encoding, set roc_sender_config.packet_encoding manually
Jun 23 19:20:56 t580 pipewire[1290783]: 19:20:56.677 [1290783] [err] roc_api: roc_sender_open(): invalid arguments: bad config
Jun 23 19:20:56 t580 pipewire[1290783]: mod.roc-sink: failed to create roc sender: -1
Jun 23 19:20:56 t580 pipewire[1290783]: pw.conf: 0x557f48a800d0: could not load mandatory module "libpipewire-module-roc-sink": Invalid argument
Jun 23 19:20:56 t580 pipewire[1290783]: default: failed to create context: Invalid argument
```

Upstream bug report: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/4070

**Comment by K900** [comment]
In that case, I'd rather see the upstream fix cherry-picked into staging, instead of forcing yet another mass rebuild on master for a generally uncommon use case.

**Comment by superherointj** [comment]
> In that case, I'd rather see the upstream fix cherry-picked into staging, 

I just tested the proposed patch and `nixosTests.installed-tests.pipewire` still errors.
I don't have a solution at hand. And I'm out of time.

> instead of forcing yet another mass rebuild on master for a generally uncommon use case.

I get the problem.

I'm not sure what to do then.

Revert to staging? Do nothing?

**Comment by K900** [comment]
The tests don't even check that I'm pretty sure, and there's one test that just fails on a VM. So that's not a good indicator of anything.

**Pull request closed without merging**
