### PR TITLE
Sway: module

### PR DESCRIPTION
**Pull request by ndowens**
###### Motivation for this change
Add module for sway-wm

###### Things done

- [ x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ N/A] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [N/A ] Tested execution of all binary files (usually in `./result/bin/`)
- [x ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ndowens** [comment]
@fpletz ok Reopened, and I hope I indented it like you wanted. Tried to make it easy to read.

**Comment by Mic92** [comment]
We also have this pull request on going: https://github.com/NixOS/nixpkgs/pull/19663

**Comment by ndowens** [comment]
@Mic92 ah didnt know there was one pending, guess I should close it, it seems

**Comment by Mic92** [comment]
@ndowens if you can address the stuff mentioned in comments, I can also merge yours.

**Comment by ndowens** [comment]
@Mic92 afaik i got the issues fixed, it was mostly indentation problems. In which i think looks better than before.

**Comment by Mic92** [comment]
@ndowens Sorry I meant the last one from the other pull request regarding setcap wrapper: https://github.com/NixOS/nixpkgs/pull/19663#issuecomment-281516828

**Comment by offlinehacker** [comment]
isn't sway window manager for wayland, does it also run with x11?

**Comment by ndowens** [comment]
@Mic92 Done
@offlinehacker yea it is wayland, I DON'T think it uses x11. I know it uses weston and wayland IIRC

**Comment by offlinehacker** [comment]
@ndowens i don't get it, does it use x11 and if no, why is it exposed as x desktop manager?

**Comment by ndowens** [comment]
I don't know much about wayland and weston really. Just that it meant to replace xorg if I am not mistaken

**Comment by xwvvvvwx** [comment]
@ndowens I think the point is that this should maybe be under `services.wayland.windowManager`?

**Comment by ndowens** [comment]
Didn't notice there was one for wayland. Will look at it when I am off work

**Comment by Mic92** [comment]
There is no `services.wayland.windowManager` at the moment, but it should be probably also called compositor instead.

**Comment by ndowens** [comment]
@Mic92 changed it, which proposes a new category

**Pull request closed without merging**
