### PR TITLE
linuxPackages_5_3.openafs_1_8: fix build

### PR DESCRIPTION
**Pull request by artemist**
This update cherry-picks patches necessary to build the OpenAFS kernel
module from the OpenAFS master branch. This commit does not fix OpenAFS
1.6.

###### Motivation for this change

OpenAFS failed to build

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @spacefrogg @maggesi

### CODE REVIEW

**Comment by veprbl** [comment]
@GrahamcOfBorg build linuxPackages_5_3.openafs_1_8

**Comment by artemist** [comment]
We might as well check older versions of Linux (I haven't checked yet)
@GrahamcOfBorg build linuxPackages_4_4.openafs_1_8 linuxPackages.openafs_1_8

**Review by veprbl — APPROVED** [review]
Passes nix-review on x86_64-linux (non-NixOS without sandboxing)
```
3 package failed to build:
linuxPackages_hardened.openafs_1_8 linuxPackages_latest_hardened.openafs_1_8 linuxPackages_testing_hardened.openafs_1_8

11 package were build:
linuxPackages-libre.openafs_1_8 linuxPackages.openafs_1_8 linuxPackages_4_14.openafs_1_8 linuxPackages_4_4.openafs_1_8 linuxPackages_4_9.openafs_1_8 linuxPackages_5_2.openafs_1_8 linuxPackages_5_3.openafs_1_8 linuxPackages_latest-libre.openafs_1_8 linuxPackages_latest_xen_dom0.openafs_1_8 linuxPackages_testing_bcachefs.openafs_1_8 linuxPackages_xen_dom0.openafs_1_8
```

**Comment by spacefrogg** [comment]
@artemist @veprbl Thanks for taking care of this!

**Pull request merged**
