### PR TITLE
add Renoise to nixpkgs

### PR DESCRIPTION
**Pull request by krgn**

### CODE REVIEW

**Comment by lethalman** [comment]
cc @MagneticDuck cannot test this because I don't have the binaries

**Comment by krgn** [comment]
@lethalman you can test the derivation with `demo = true`, which should download the publicly available version from the Renoise site.

**Comment by lethalman** [comment]
Ok works for me thanks.

**Comment by MagneticDuck** [comment]
ahaha we made it finally ;)

**Comment by krgn** [comment]
to be honest, even though its mostly a past-time of mine, this program was one of the top-priorities when I switched back to NixOS recently :)

**Comment by krgn** [comment]
@MagneticDuck thanks for pinging me on IRC as well. didn't see it until only today tho

**Pull request merged**
