### PR TITLE
mesonEmulatorHook: don’t use `lib.escapeShellArg`

### PR DESCRIPTION
**Pull request by emilazy**
## Description of changes

This needs to be a single‐quoted string; #333744 broke this incorrect use. Hyrum’s law strikes again!

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by infinisil — APPROVED** [review]
I can't comment on whether this works or not (not even sure how to reproduce the reported error), but this definitely wasn't a correct use of that function, kudos for the quick fix!

**Comment by NickCao** [comment]
What if there happens to be a naughty ' within the emulator command? Which is actually the case for dummy emulator (when `stdenv.buildPlatform.canExecute stdenv.hostPlatform`.
```
nix-repl> stdenv.hostPlatform.emulator pkgs
"/nix/store/4bj2kxdm1462fzcc2i2s4dn33g2angcc-bash-5.2p32/bin/bash -c '\"$@\"' --"
```

**Comment by NickCao** [comment]
Maybe we should use `lib.escape` directly? Just to escape single quotes.

**Comment by emilazy** [comment]
Then it’ll break. I didn’t realize it could be a full command line; I was just thinking about the edge case of filenames with quotes in them. Let me look at our options here.

**Comment by infinisil** [comment]
Not sure if `'` is the only thing that should be escaped, because other characters have escape sequences: https://mesonbuild.com/Syntax.html#strings

**Comment by NickCao** [comment]
Guess we have to implement `pkgs.formats.meson` now!

**Comment by emilazy** [comment]
I think the current version should be correct in all cases. Probably. Maybe not if you put a newline in there or something.

And yes, clearly we generate these Meson `.conf` files enough that we should be doing it in a structured fashion. But this patch should make things strictly better than before.

**Review by infinisil — APPROVED** [review]

**Comment by NickCao** [comment]
Also ping meson maintainers: @alyssais and @AndersonTorres

**Comment by NickCao** [comment]
Glad we are not in a rush here since this also affects cross compilation, which is not cached anyway.

**Comment by emilazy** [comment]
I’m inclined just to merge, since it can’t get more broken than the current state of `staging-next` and this shouldn’t cause rebuilds. The whole Meson `.conf` generation could of course be further improved later as part of another staging cycle.

**Comment by NickCao** [comment]
Let's at least wait until hearing back from the maintainers.

**Review by AndersonTorres — APPROVED** [review]

**Comment by AndersonTorres** [comment]
> Guess we have to implement `pkgs.formats.meson` now!

+1 for this

**Review by NickCao — APPROVED** [review]
Tested building `pkgsCross.riscv64.glib`.

**Comment by vcunat** [comment]
> Merge pull request #336890 from emilazy/push-xmwppmokytwn

Uh, I hate GitHub's default merge messages.

**Comment by emilazy** [comment]
I wish the format was

```
Merge #123: PR title

…PR cover letter…
```

rather than

```
Merge pull request #123 from somebody/useless-branch-name

PR title
```

Maybe I should set up an alias to `jj git push` with a nicer branch name. OTOH, my experience is that other people’s manually‐written branch names are often not very useful or accurate either, and I’m kind of glad to still not be spending time thinking of both a branch name *and* a PR title… I guess I could make it synthesize a branch name from the PR title, though.

Here’s something disgusting you might like that I just cooked up to make the Nixpkgs log a lot more readable:

```bash
git log --oneline --first-parent --pretty='%h %s@@ %w(999,0,1)%b' | sed 's/ Merge pull request \(#[[:digit:]]*\).*@@ \(.\{1,\}\)/ \2 (\1)/; s/@@.*//; /^ /d; /^$/d'
```

**Comment by vcunat** [comment]
That's exactly how I do merges, e.g. 9edd5ddbd2453e22d4c4820992563c7ba0930f7a right now.

**Comment by vcunat** [comment]
BTW, in GitLab one can override the default merge PR template.  I'm not sure if it can be done here.

**Comment by emilazy** [comment]
> That's exactly how I do merges, e.g. [9edd5dd](https://github.com/NixOS/nixpkgs/commit/9edd5ddbd2453e22d4c4820992563c7ba0930f7a) right now. I don't see the need for a branch name here.

That’s a squash merge, right? I dislike those for other reasons since I tend to split my commits up pretty carefully, but they do have better messages.

> BTW, in GitLab one can override the default merge PR template. I'm not sure if it can be done here.

I thought no, but it looks like yes! https://github.blog/changelog/2022-08-23-new-options-for-controlling-the-default-commit-message-when-merging-a-pull-request/

We can set the merge commit default to “Pull request title and description”. I think that would be better. We’d need an org owner to do it, I suppose, and I don’t know how we’d get consensus for it. I’ll bring it up on Matrix.

**Comment by vcunat** [comment]
No, it's a normal merge.  I merge and sign PRs locally.

**Comment by emilazy** [comment]
@vcunat FWIW the setting was changed and `git log --first-parent --oneline` should be a lot more usable going forward :)

**Comment by mmlb** [comment]
> I wish the format was
> 
> ```
> Merge #123: PR title
> 
> …PR cover letter…
> ```
> 
> rather than
> 
> ```
> Merge pull request #123 from somebody/useless-branch-name
> 
> PR title
> ```

There is a GitHub setting for better merge commit messages, its "Pull request title and description", though it doesn't quite match exactly what you'd prefer it is a huge improvement over the default. Messages end up looking like:

```
PR title (#PRNUM)

PR description
```

image

**Comment by emilazy** [comment]
Yes, we already switched to the pull request title option after this discussion :) Which is better (IMO), but it does make merges a little harder to spot.

PR description would not be so good because our PR description template has a lot of HTML/Markdown cruft in it and PR descriptions aren’t really reliably updated for changes as the PRs evolve.

**Comment by mmlb** [comment]
> Yes, we already switched to the pull request title option after this discussion :) Which is better (IMO), but it does make merges a little harder to spot.

Nice! Its not too bad imo since they are always merge commits so can be seen/filtered okish.

> PR description would not be so good because our PR description template has a lot of HTML/Markdown cruft in it and PR descriptions aren’t really reliably updated for changes as the PRs evolve.

Yep that is a struggle indeed, its a balance. IMO the template has too much info that is better off verified by CI. Having the comments not be comments and have a "DELETE ME" string in them can also serve a bit like the Van Halen brown-m&ms test, we can see at a glance who did not read the PR template body :).

**Pull request merged**
