### PR TITLE
discourse: Fix plugin support

### LINKED ISSUE #127795: Plugins in Discourse not working even though they appear to be installed correctly
**Describe the bug**
I have tried to install two plugins, namely discourse-solved and discourse-canned-replies, none of them work, but they appear in the plugin list as installed and enabled.

**To Reproduce**
1. install plugins by setting services.discourse.plugins to:
[
        (pkgs.fetchFromGitHub {
          owner = "discourse";
          repo = "discourse-solved";
          rev = "ca0dbd6d4c99958b88a1c9ec0661728ddac468b1";
          sha256 = "02blzbiwkcqb7nfw0llj9m081w6iixldshmrf3s9z9315zlnxr31";
        })
        (pkgs.fetchFromGitHub {
          owner = "discourse";
          repo = "discourse-canned-replies";
          rev = "7ee748f18a276aca42185e2079c1d4cadeecdaf8";
          sha256 = "0j10kxfr6v2rdd58smg2i7iac46z74qnnjk8b91jd1svazhis1ph";
        })
   ];
2. after rebuilding, check the admin/plugins section of discourse and you see the plugins are there and enabled (see the screenshot bellow)
3. check to open a new reply and you should have the "canned replies" in the gear menu (provided by discourse-canned-replies plugin), but it doesn't
4. when you click "show more" bellow any reply in the topic, you should see the "solution" button (provided by discourse-solved plugin), but it's not there

**Expected behavior**
explained above

**Screenshots**
admin/plugins screen:

what it shows in the reply after installation:

what it should show in the reply after installation:

what it shows bellow a reply:

what it should show bellow a reply after installation:

**Additional context**
N/A

**Notify maintainers**

@talyz 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.43, NixOS, 21.11pre-git (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by talyz**
###### Motivation for this change
Fix #127795.

For Discourse plugins to work properly, their assets need to be precompiled along with the rest of Discourse's assets. This means we need to build new packages when the list of plugins change.

This moves the plugin file handling from the module over to the package, where the plugin files are put in place before the assets are built.

cc @Dehumanizer77

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by ryantm — APPROVED** [review]
Changes look good. Thank you for fixing this!

**Comment by talyz** [comment]
I've simplified the fix, but it should be equivalent to earlier - it evaluates to the same derivations as before the change, both with and without plugins.

**Comment by ryantm** [comment]
Wow, that is much simpler, nice. Still looks good to me.

**Comment by dpausp** [comment]
The PR builds with the following plugins:

- discourse-canned-replies
- discourse-solved
- discourse-chat-integration
- discourse-akismet
- discourse-rss-polling
- discourse-spoiler-alert

I can confirm that `discourse-solved` and `discourse-canned-replies` work as expected, haven't tested the others yet.

discourse-github breaks the build because it expects the `sawyer` and `octokit` gems which aren't included in Discourse. This plugin installs without the PR but I don't know if it actually works.

I don't have an idea yet how to package such plugins to make them easy to use. It's also hard to find out which plugin caused the problem because bundler just reports missing gems and you have to find the culprit by trial-and-error or by looking at their `plugin.rb`. 

discourse-yearly-review fails for a different reason, which also happens without the PR:

~~~
++++ bundle exec rake db:migrate
rake aborted!
LoadError: cannot load such file -- /build/source/plugins/discourse-yearly-review/app/jobs/yearly_review.rb
~~~

**Comment by talyz** [comment]
@dpausp Oh, right, Discourse installs Ruby dependencies automatically, but can't do so for us. I've extended the plugin support to include packages with Ruby dependencies now and packaged a few plugins. It needs more documentation and the plugin packages needs updating and metadata, but it should be enough to discuss the approach. I've tested and made sure the `discourse-github` plugin now works (at least it's able to permalink).

**Comment by talyz** [comment]
@dpausp I added `discourse-yearly-review` now and can't reproduce your issue - it looks like it works just fine, so not sure what's going on there :shrug:

**Review by dpausp — APPROVED** [review]

**Comment by dpausp** [comment]
Great work, will package some additional plugins soon!

> @dpausp I added `discourse-yearly-review` now and can't reproduce your issue - it looks like it works just fine, so not sure what's going on there 🤷

I still don't know either but it works with your code now :)

Built again with the other plugins I mentioned before and everything builds now. Tried out the `discourse-chat-integration` plugin with Matrix, `discourse-canned-replies`, `discourse-solved` and `discourse-spoiler-alert` which all work as expected.

**Pull request merged**
