### PR TITLE
Add allowedTCPPorts for opening firewall ports

### PR DESCRIPTION
**Pull request by polynomial**
Open firewall ports for consul so that all your consul configuration can be done as services.consul.*

### CODE REVIEW

**Comment by peti** [comment]
Why is this preferrable over specifying `networking.firewall.allowedTCPPorts` directly?

**Comment by polynomial** [comment]
If you are trying to enable multiple services on the same box having to manage the port openings via combined lists makes the code harder to read. We've found it preferable to follow this approach: https://github.com/NixOS/nixpkgs/blob/0761f81da71fc6a940c7f51129b6c7717db78e87/nixos/modules/services/games/minecraft-server.nix#L68-L71

**Comment by lethalman** [comment]
@polynomial yes, but what's the relationship with this PR? Why should consul have his own `allowedTCPPorts` instead of specifying them directly?

**Comment by polynomial** [comment]
Using this in nixops, the problem we run into is that if we have a node definition that pulls into two services and they both set firewall ports using 'networking.firewall.*' then when you merge them together you only get one set of ports (both services don't have their ports open). Here is a gist which I hope helps explain the problem: https://gist.github.com/polynomial/7f3ea09e27b422e9aea8
The merge at the 'module' level works so if you have services that do it like the minecraft-server and just 'enable' the firewall then all ports done that way are successfully added. I'll hop on IRC too.

**Comment by lethalman** [comment]
@polynomial I'm pretty sure the list of tcp ports are concatenated between multiple definitions. You are telling this is not happening?

**Comment by polynomial** [comment]
It doesn't appear to. The expected behavior would be that all the ports opened in any of the expressions would be open on the node. But what we see is that the last one is the only set open (along with 22). So if we put mysql last we get 3306, 22. If we put Consul last we get 8000, 8083, ..., 22.

**Comment by lethalman** [comment]
@polynomial that's because you are doing your nix `import` instead of using the nixos `imports`.

**Comment by polynomial** [comment]
For us the issue there was that passing arguments to the imported expressions wasn't possible. Although I may be missing the right way to do this. The hope would be that we could have several different service expressions and pass arguments to them given certain profiles. Sorry if this just adds to the confusion. (: ):

**Comment by peti** [comment]
> passing arguments to the imported expressions wasn't possible.

The proper mechanism to do that is `config`.

**Comment by polynomial** [comment]
I think I may have missed conveying the initial motivation. When looking through the packages and finding a couple other services that do it this way (like the minecraft example above: https://github.com/NixOS/nixpkgs/blob/0761f81da71fc6a940c7f51129b6c7717db78e87/nixos/modules/services/games/minecraft-server.nix#L68-L71 ). So instead of:

    services.minecraft-server.enable = true;
    networking.firewall.allowedTCPPorts = [ 26655 ];

You have:

    services.minecraft-server.enable = true;
    services.minecraft-server.openFirewall = true;

This seems like a desirable approach to use for all modules. Is there a reason we wouldn't want to keep all the logic for whats done to enable the module inside the modules configuration name space?

**Comment by peti** [comment]
> Is there a reason we wouldn't want to keep all the logic for whats done to enable the module inside the modules configuration name space?

I see no inherent value in duplicating the functionality of `networking.firewall.allowedTCPPorts` in another namespace. What is the point? The example you cite, `services.minecraft-server.openFirewall`, doesn't do that. It provides some extra functionality -- i.e. it gives users a high-level option to decide whether or not to open the firewall without having them worry about port numbers, etc. It's not strictly necessary to provide that extra option, but there *is* some added value in it. That added value seems to be missing from your proposal.

**Comment by offlinehacker** [comment]
I'm also against this pr. We have too much magic in nixos already.

**Comment by offlinehacker** [comment]
Btw it nothing stops you to define your nixos modules that abstract your use case. This is set of profiles we use in production. https://github.com/offlinehacker/x-truder.net/tree/master/profiles

**Comment by lethalman** [comment]
@polynomial the correct way to pass arguments to another module is not to pass them. That's functional approach. NixOS is declarative. So the correct way is to define your own options like any other module does.

**Comment by polynomial** [comment]
Ok, thank you very much for the feedback! Closing this and will try and take the suggested approach!

**Pull request closed without merging**
