### PR TITLE
zdoom: Fix typo from 1cc9d9ef2ce80dee5c8f2ef9f8ae20ae76337d73

### PR DESCRIPTION
**Pull request by Ericson2314**

### CODE REVIEW

**Comment by abbradar** [comment]
Ouch, thank you very much. It's strange that none of my tests caught this...

**Comment by Ericson2314** [comment]
Don't feel bad, I broke nixpkgs recently too! We really need better CI so these things aren't possible; it's stupid to put the onus on us humans.

I'm going to make a label or something collecting evidence.

**Comment by abbradar** [comment]
I think a good way may be to split tests. One tries to build everything (and is judged with a grain of salt like current Travis tests) and the other just does full evaluation of packages themselves and `meta`. I thought that we already do that since Travis has two tests, but I have often seen the first one (which I supposed to be evaluation) downloading and building things -- that's why I more or less stopped being attentive to it with time, too (and relied on me running them by hand).

Fixing this would be a good first step but I'm sure that has been thought of before. Whom can we ask about current Travis state?

**Comment by Ericson2314** [comment]
https://github.com/hercules-ci/hercules I hope will save the day. I see no solution build making sure everything in each (merge) commit builds before bumping the master ref.

**Pull request merged**
