### PR TITLE
envoy: update broken deps hashes

### PR DESCRIPTION
**Pull request by adamcstephens**
## Description of changes

I've built the x86_64-linux deps a couple dozen times, and these hashes are stable for me. I'm still not confident they are 100% reproducible, but comfortable enough to try and fix this package.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by yu-re-ka** [comment]
Sadly, this seems to be not reproducible:

```
[yuka@yuyu:~]$ nix build github:adamcstephens/nixpkgs/envoy/update-hashes#envoy.deps
error: hash mismatch in fixed-output derivation '/nix/store/ckvgbpvk61x1hbk7v3hy59l9693qrl31-envoy-1.26.4-deps.tar.gz.drv':
         specified: sha256-d8uj/uZP2bl5BqqzUwTigW61aYDUxeUh4XdWgKp0dcs=
            got:    sha256-nHfs4c7MnHuWeYQJW011CRWksDstsoI4iiYZNRA7DPM=

[yuka@yuyu:~]$ 
```
(x86_64-linux)

**Comment by adamcstephens** [comment]
and ofborg got yet another hash:

```
error: hash mismatch in fixed-output derivation '/nix/store/ckvgbpvk61x1hbk7v3hy59l9693qrl31-envoy-1.26.4-deps.tar.gz.drv':
         specified: sha256-d8uj/uZP2bl5BqqzUwTigW61aYDUxeUh4XdWgKp0dcs=
            got:    sha256-l4EKUsUvumNRylPpUDXkFsUPmxAglfnYbk5Qu4+VJvk=
```

**Comment by adamcstephens** [comment]
```
Binary files p0v/external/pypi__pip/pip/_vendor/pyparsing/__pycache__/core.cpython-310.pyc and saw/external/pypi__pip/pip/_vendor/pyparsing/__pycache__/core.cpython-310.pyc differ
```

**Comment by adamcstephens** [comment]
@ofborg test envoy

**Review by yu-re-ka — APPROVED** [review]
Can reproduce the hashes on x86_64-linux and aarch64-linux
Next question (but should not block this PR from being merged): would it be possible to eliminate the differences between platforms?

**Comment by adamcstephens** [comment]
> would it be possible to eliminate the differences between platforms?

I’ll need to look through the deps tarball to see what’s different between architectures. Could be a good thing to bundle with the next upgrade which is already available.

**Review by wegank — APPROVED** [review]

**Review by lukegb — APPROVED** [review]

**Pull request merged**
