### PR TITLE
nim: 2.0.8 -> 2.2.0; nim: init updatescript;

### LINKED ISSUE #346530: Update request: nim 2.0.8 -> 2.2.0 and 2.0.10
See new release blog post: https://nim-lang.org/blog/2024/10/02/nim-220-2010.html

- Package name: nim
- Latest released version: 2.2.0 and 2.0.10
- Current version on the unstable channel: 2.0.8
- Current version on the stable/release channel: 2.0.4
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@ehmry 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Eveeifyeve**
[changeLog v2.0.8...v2.2.0](https://github.com/nim-lang/Nim/compare/v2.0.8...v2.2.0)

Adds an update script to nim.

Fixes: #346530 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Eveeifyeve** [comment]
It fails on `aarch-64darwin` for some reason.

**Comment by Eveeifyeve** [comment]
@ofborg eval

**Comment by Eveeifyeve** [comment]
```
patching file compiler/msgs.nim
Hunk #1 FAILED at 659.
1 out of 1 hunk FAILED -- saving rejects to file compiler/msgs.nim.rej
error: builder for '/nix/store/lj7avzq64ivkzwyl6q68wwriw8l1gy9r-nim-unwrapped-2.2.0.drv' failed with exit code 1;
       last 10 log lines:
       > patching file lib/pure/dynlib.nim
       > Hunk #1 succeeded at 45 with fuzz 2 (offset -11 lines).
       > Hunk #2 succeeded at 87 with fuzz 1 (offset -11 lines).
       > applying patch /nix/store/vw1jfdamdy5gd2qm0kk41afjykj653h7-extra-mangling.patch
       > patching file compiler/modulepaths.nim
       > Hunk #1 succeeded at 79 (offset 9 lines).
       > Hunk #2 succeeded at 94 (offset 9 lines).
       > patching file compiler/msgs.nim
       > Hunk #1 FAILED at 659.
       > 1 out of 1 hunk FAILED -- saving rejects to file compiler/msgs.nim.rej
       For full logs, run 'nix-store -l /nix/store/lj7avzq64ivkzwyl6q68wwriw8l1gy9r-nim-unwrapped-2.2.0.drv'.
error: 1 dependencies of derivation '/nix/store/fzmdg1fg8sz33dhjzb7m1padxsjvlbfb-aarch64-apple-darwin-nim-wrapper-2.2.0.drv' failed to build
```

**Comment by ehmry** [comment]
I'll fix the path mangling patch and push it when I get a chance.

After that, squash the version and hash commits together and put the version update in the commit message.
https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions

**Comment by ehmry** [comment]
I pushed a new mangling patch.

**Comment by Eveeifyeve** [comment]
Works.

**Comment by Eveeifyeve** [comment]
Logs: 
```
error: 2 dependencies of derivation '/nix/store/207ndaa7jd4x2il8hiil2qbd6nbga8df-review-shell.drv' failed to build
┏━ 1 Errors:
┃ error: builder for '/nix/store/ls0mbvx6hdmzmzidp36z86f7ahkxrhvq-nim-unwrapped-1.6.20.drv' failed with exit code 1;
┃        last 10 log lines:
┃        > patching file lib/pure/dynlib.nim
┃        > Hunk #1 succeeded at 45 with fuzz 2 (offset -11 lines).
┃        > Hunk #2 succeeded at 87 with fuzz 1 (offset -11 lines).
┃        > applying patch /nix/store/lhkmiqgxabd2z00kbkh3nfgcf7fwd283-extra-mangling.patch
┃        > patching file compiler/modulepaths.nim
┃        > Hunk #1 succeeded at 73 (offset -6 lines).
┃        > Hunk #2 succeeded at 88 (offset -6 lines).
┃        > patching file compiler/modulegraphs.nim
┃        > Hunk #1 FAILED at 503.
┃        > 1 out of 1 hunk FAILED -- saving rejects to file compiler/modulegraphs.nim.rej
┃        For full logs, run 'nix-store -l /nix/store/ls0mbvx6hdmzmzidp36z86f7ahkxrhvq-nim-unwrapped-1.6.20.drv'.
```


Result of `nixpkgs-review pr 346578` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>chawan</li>
    <li>nrpl</li>
  </ul>
</details>
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>nim1</li>
    <li>vimPlugins.fruzzy</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>nim (nim2)</li>
    <li>nim_lk</li>
    <li>promexplorer</li>
    <li>tridactyl-native</li>
  </ul>
</details>

**Comment by Eveeifyeve** [comment]
> Might need to keep distinct versions of the extra-mangling.patch for nim 1.x and 2.2.x respectively.

I just made it seprate.

**Comment by Eveeifyeve** [comment]
Result of `nixpkgs-review pr 346578` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>chawan</li>
    <li>nrpl</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>nim (nim2)</li>
    <li>nim_lk</li>
    <li>promexplorer</li>
    <li>tridactyl-native</li>
  </ul>
</details>

**Comment by Eveeifyeve** [comment]
I can confirm `nim1` is working and `vimPlugins.fruzzy` in my local enviroment.

**Review by xTrayambak — APPROVED** [review]

**Pull request merged**
