### PR TITLE
leiningen: 2.9.1 -> 2.9.4

### PR DESCRIPTION
**Pull request by mpisanko**
- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

current version: 2.9.1
desired version: 2.9.4

###### Motivation for this change
Get latest version of leiningen

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by RaghavSood** [comment]
Result of `nixpkgs-review pr 104646` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>leiningen</li>
  </ul>
</details>

**Comment by mpisanko** [comment]
Sorry, didn't quite understand at first. Do you need something else?

[nix-shell:~/.cache/nixpkgs-review/pr-104646]$ cat report.md
Result of `nixpkgs-review pr 104646` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>leiningen</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
@mpisanko please resolve the merge conflict.

**Comment by mpisanko** [comment]
No point, as master is now 2.9.5 - newer than 2.9.4 (PR 2 months old now)

**Pull request closed without merging**
