### PR TITLE
shell_gpt: 0.7.3 -> 0.8.8

### PR DESCRIPTION
**Pull request by MGlolenstine**
###### Description of changes

Updated to a [newer release](https://github.com/TheR1D/shell_gpt/releases) of `shell_gpt`, requested [here](https://github.com/NixOS/nixpkgs/pull/222240#issuecomment-1504118495).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Magellol** [comment]
I'm trying to test this but I'm not sure what is the process. 

I've forked this repo and I'm trying to follow this section https://nixos.org/manual/nixpkgs/stable/#chap-submitting-changes:~:text=Test%20your%20changes.%20If%20you%20work%20with

```console
$ git clone ...
$ cd nixpkgs/pkgs/tools/misc/shell_gpt/default.nix
$ nix-build -A shell_gpt .
```

But I get the following error
→ nix-build -A shell_gpt .
error: cannot evaluate a function that has an argument without a value ('lib')

       Nix attempted to evaluate a function as a top level expression; in
       this case it must have its arguments supplied either by default
       values, or passed explicitly with '--arg' or '--argstr'. See
       https://nixos.org/manual/nix/stable/#ss-functions.

       at /Work/nixpkgs/pkgs/tools/misc/shell_gpt/default.nix:1:3:

            1| { lib
             |   ^
            2| , python3
```
I'm sure there is something I'm missing. Note I'm not running `nixos`.

**Comment by MGlolenstine** [comment]
@Magellol 
I think there's an issue with the period you're adding to the end of the `nix-build` command.

Something like this should work.
```
nixpkgs on  shellgpt
❯ nix-build -A shell_gpt
/nix/store/k8zbbfjc83xhrz5wsy06751x3jr7bvm7-shell_gpt-0.8.8

nixpkgs on  shellgpt
❯ ./result/bin/sgpt
```

(Note, I'm on NixOS, but the above should be the same.)

**Comment by MGlolenstine** [comment]
I added an auto-update hook as suggested [here](https://github.com/NixOS/nixpkgs/pull/222240#issuecomment-1487064351).

**Comment by Magellol** [comment]
@MGlolenstine I was adding the `.` to target the current directory. I thought to test I had to point to the local folder for `shell_gpt`. That's what they say in the docs

>nix-build -A pkg-attribute-name <path to your local nixpkgs folder> and check results in the folder result. It will appear in the same directory where you did nix-build.

If I run `nix-build -A shell_gpt` it builds the `0.7.3` version 🤔 

```
result -> /nix/store/yv6hvy5hid6vh9fychl12y5pzp4ch9y1-shell_gpt-0.7.3
```

**Comment by MGlolenstine** [comment]
Weird, does `nix-build -A shell_gpt -I nixpkgs=.` alleviate the issue?
(On my way from work, so no computer in sight to test.)

**Comment by MGlolenstine** [comment]
Ok, checking `man nix-build`, I noticed this line:
```
   Build the GNU Hello package from the latest revision of the master branch of Nixpkgs:

       $ nix-build https://github.com/NixOS/nixpkgs/archive/master.tar.gz -A hello
```
so I think `nix-build . -A shell_gpt` should work.

**Comment by Magellol** [comment]
@MGlolenstine I've got it to work now! Looks good to me

**Review by Magellol — APPROVED** [review]
⭐

**Comment by MGlolenstine** [comment]
Thank you for testing it!

**Comment by happysalada** [comment]
Thank you !

**Pull request merged**
