### PR TITLE
matrix-hookshot: 4.0.0 -> 4.1.0

### PR DESCRIPTION
**Pull request by chvp**
###### Description of changes

https://github.com/matrix-org/matrix-hookshot/releases/tag/4.1.0

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by chvp** [comment]
Deployed and tested on my server.

**Comment by SuperSandro2000** [comment]
Can we try adding iconv for darwin? Otherwise please mark it broken.

```
hookshot/target/release/build/markup5ever-fe48539dfa75bf64/build_script_build-fe48539dfa75bf64" "-Wl,-dead_strip" "-nodefaultlibs"
  = note: ld: library not found for -liconv
          clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
          
error: could not compile `markup5ever` due to previous error
warning: build failed, waiting for other jobs to finish...
Internal Error: Command failed: cargo build --release --target x86_64-apple-darwin
    at checkExecSyncError (node:child_process:885:11)
    at Object.execSync (node:child_process:957:15)
    at BuildCommand.<anonymous> (/nix/store/afndff0pcbiy12n5gdbp2a098s1a92wa-napi-rs-cli-2.12.0/lib/napi-rs-cli/index.js:27918:26)
    at Generator.next (<anonymous>)
    at /nix/store/afndff0pcbiy12n5gdbp2a098s1a92wa-napi-rs-cli-2.12.0/lib/napi-rs-cli/index.js:3467:71
    at new Promise (<anonymous>)
    at __awaiter$1 (/nix/store/afndff0pcbiy12n5gdbp2a098s1a92wa-napi-rs-cli-2.12.0/lib/napi-rs-cli/index.js:3463:12)
    at BuildCommand.execute (/nix/store/afndff0pcbiy12n5gdbp2a098s1a92wa-napi-rs-cli-2.12.0/lib/napi-rs-cli/index.js:27806:16)
    at BuildCommand.validateAndExecute (/nix/store/afndff0pcbiy12n5gdbp2a098s1a92wa-napi-rs-cli-2.12.0/lib/napi-rs-cli/index.js:1993:37)
error: builder for '/nix/store/ds29q3ahrhhakffzh0wimg4ssyg3ahr8-matrix-hookshot-4.1.0.drv' failed with exit code 1;
```

**Comment by chvp** [comment]
The build still seems to fail on ofborg, but maybe I'm doing something wrong? Unfortunately I don't have a mac to test it on.

**Comment by SuperSandro2000** [comment]
The change looks correct to me, so lets just mark it broken and let someone with a mac deal with this.

**Pull request merged**
