### PR TITLE
arduino: 1.8.9 -> 1.8.12

### PR DESCRIPTION
**Pull request by prusnak**
###### Motivation for this change

+ version update
+ added aarch64-linux support
+ reformatted via nixpkgs-fmt

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by prusnak** [comment]
@GrahamcOfBorg build arduino teensyduino

**Comment by dasj19** [comment]
@prusnak thanks a lot for picking up where I left off... I would not have made it that far as fast. I am testing at the moment your changes

**Comment by prusnak** [comment]
@GrahamcOfBorg build arduino teensyduino

**Comment by prusnak** [comment]
@GrahamcOfBorg build arduino teensyduino

**Pull request merged**
