### PR TITLE
llvmPackages_git.compiler-rt: fix build

### PR DESCRIPTION
**Pull request by alyssais**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sternenseemann** [comment]
@ofborg build llvmPackages_git.compiler-rt

**Review by rrbutani — APPROVED** [review]
I've been meaning to redo `llvmPackages_git` starting from `llvmPackages_15` once some of the remaining `llvmPackages_15` PRs go through (`llvmPackages_git` is missing a fair number of patches at this point I think) but merging this fix in the interim certainly doesn't hurt!

----

I'm a little unsure whether it makes sense to share the armv7l `compiler-rt` patch between `llvmPackages_15` and `_git` (it _seems_ like the two files it touches see a fair bit of churn and I imagine `_git` will end up needing it's own version of the patch again once we update it) but this doesn't hurt either; at worst 15's version of the patch just ends up living in `common`.

**Comment by alyssais** [comment]
> I'm a little unsure whether it makes sense to share the armv7l `compiler-rt` patch between `llvmPackages_15` and `_git` (it _seems_ like the two files it touches see a fair bit of churn and I imagine `_git` will end up needing it's own version of the patch again once we update it) but this doesn't hurt either; at worst 15's version of the patch just ends up living in `common`.

Yeah I wasn't sure either, but I decided it's best to avoid having two copies of the patch just in case one has to change later.

**Comment by alyssais** [comment]
> I've been meaning to redo `llvmPackages_git` starting from `llvmPackages_15` once some of the remaining `llvmPackages_15` PRs go through (`llvmPackages_git` is missing a fair number of patches at this point I think) but merging this fix in the interim certainly doesn't hurt!

I might beat you to it. :) I'm trying to copy all the changes that were made to llvmPackages_15 over to _git — I didn't want to end up with a single blob of changes that were difficult to understand.  In future, it would probably make things easier to always make sure changes are added to _git at the same time as the latest LLVM.  (And in the further future, to have a common builder function…)

**Comment by alyssais** [comment]
> Please let me know if I can help in any way! Between the changes in #194634 and all the other PRs listed there I think there's lots that `llvmPackages_git` is missing.

Thanks! Are you on Matrix? (I checked maintainer-list.nix and didn't see a Matrix ID for you.) It'd be great to have you in the [Compilers Team channel](https://matrix.to/#/#compilers:nixos.org), if you're not there already.

**Comment by rrbutani** [comment]
> It'd be great to have you in the [Compilers Team channel](https://matrix.to/#/#compilers:nixos.org), if you're not there already.

Thanks! I just joined the channel

**Pull request merged**
