### PR TITLE
sublime-merge: support aarch64-linux

### PR DESCRIPTION
**Pull request by povik**
Generalize the common derivation and add hashes for aarch64 binaries.
Everything seems to apply the same on the new platform.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zookatron** [comment]
I'm unable to test this because I don't have access to a aarch64 device.

**Comment by jtojnar** [comment]
It would be nice to use the same packaging style as Sublime Text does.

**Comment by povik** [comment]
> It would be nice to use the same packaging style as Sublime Text does.

Yeah, I peeked there, but in the end I decided passing in the hashes dict is nicer than the ad-hoc parameters in the sublime text derivation, if that's what you refer to.

**Comment by winterqt** [comment]
I agree with @povik.

@jtojnar Is there a specific reason you think the hash parameter per platform approach that Sublime Text takes is better than passing an attrset with keys based on the system? I personally don't see any advantages. (In fact, it may be better to switch Sublime Text to pass an attrset, IMO.)

**Comment by jtojnar** [comment]
I am not saying it is better, just that we should keep the both expressions in sync.

**Comment by winterqt** [comment]
So we should probably decide on one. As you're a maintainer of the ST4 package, what do you think, should the Sublime Text packages be switched over to pass an attrset?

**Comment by jtojnar** [comment]
Sorry, I forgot about this. I have added aarch64 support to https://github.com/NixOS/nixpkgs/pull/255623

**Pull request closed without merging**
