### PR TITLE
shotwell: 0.26.2 -> 0.27.0

### PR DESCRIPTION
**Pull request by mimame**
###### Motivation for this change

Update shotwell to the last version

> 
>   * Remove F-Spot import support
>   * Create a commandline utility to test image transformations
>   * Speed up color transformations a bit
>   * Bump GTK+ requirement to 3.18 and remove deprecated functions
>   * Clean-up histogram drawing code
>   * Run thumbnailer with nice 19
>   * Update VAAPI blacklisting for video thumbnailer and new plugin structure
>   * Add configurable image background
>   * Split several dialogs from shotwell.ui file
>   * Move Tumblr to default plugin set
>   * Remove some unnecessary memcpys on import
>   * Add Meson build support
>   * Some more ngettext for plurals
>   * Add --fullscreen/-f option for viewer
>   * Add option to install Ubuntu apport hook
>   * Fix issue when importing to NTFS-backed vboxfs
>   * Fix GSettings schema search path for running out-of-tree
>   * Work around "Camera locked: -53" error on GNOME
> * Fix issue with missing highlight on dnd actions

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by bjornfor** [comment]
AFAIK, 0.27.x is unstable, 0.26.x is stable. (Just FYI... I haven't looked into how (un)stable those variants are.)

**Comment by mkocha2** [comment]
Stable versions of Shotwell are a danger to your data too. I am not aware of any photo solution on Linux that doesn't have a history of data loss. I switched to Digikam, but it too has a history of data loss, just slightly less.

Perhaps we should include a warning message in the description that it's pointless to try to create tags in Shotwell manually without some elaborate non-existing backup in place.

I think it's rather anti-social behaviour to "give away" "Free software" that results in material loss of property for most users. NixOS contributes to this by packaging Shotwell. 

https://bugzilla.gnome.org/buglist.cgi?bug_status=__open__&content=shotwell&no_redirect=1&order=Importance&product=shotwell&query_format=specific seems to suggest that Shotwell is not maintained. 

Shotwell suffers from:

- index corruption
- meta-data deletion
-  crashes during mere browsing
- slow imports
- a broken data model

I am in favor of protecting users against themselves and I think it's disappointing that you do not seem to share that approach.

**Comment by domenkozar** [comment]
@grahamcofborg shotwell

**Comment by bjornfor** [comment]
From shotwell mailing list just now:

```0.27.0 is broken and will corrupt your data on camera import. 0.27.1 should be ok.``` (https://mail.gnome.org/archives/shotwell-list/2017-October/msg00016.html)

Also, earlier in the thread they recommend to stay with 0.26.x unless there is a specific feature you need from 0.27.x.

**Pull request merged**
