### PR TITLE
vagrant: 2.0.0 -> 2.0.1 (fixes vagrant with virtualbox 5.2)

### PR DESCRIPTION
**Pull request by andir**
###### Motivation for this change

With the recent virtualbox bump to 5.2 vagrant is no longer able to interface with virtualbox. Version 2.01 fixes that.

While doing that I figured that the custom rake gem doesn't seem to have any purpose anymore. Our standard `pkgs.rake` works just as well so that is the 2nd commit in this PR.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by andir** [comment]
@grahamc is there a way to get the output of @GrahamcOfBorg? The command that I can see in the tooltip of "grahamcofborg-eval-package-list" works on my machines (TM).

**Comment by grahamc** [comment]
Hey @andir, a couple things:

1. if you rebase this branch to master, it'll definitely fail. the piping of stderr to /dev/null isn't going to help people figure this out, so I'll remove that.
2. The failure is because master fails to evaluate packages: https://github.com/NixOS/nixpkgs/pull/31626 and yours is based on master. Orivej is sending a patch for this right now. When that happens, we'll rerun the checks for this branch.

**Comment by andir** [comment]
Thanks for the input. I used the latest unstable channel as base for my PR - as I do always.

So the checks succeeded now. Without anyone touching master and this PR.. So your theory sounds a bit strange to me. Maybe I am missing something.

**Comment by grahamc** [comment]
@GrahamcOfBorg vagrant

**Comment by grahamc** [comment]
LGTM should we backport this?

**Comment by andir** [comment]
It probably doesn't hurt since it is basically just bug fixing and adding support for ruby 2.4 (but previous versions are still support (we've 2.3 as "stable" currently)).
The relevant changelog is
```
## 2.0.1 (November 2, 2017)

FEATURES:

  - core: Introduce Ruby 2.4 to Vagrant [GH-9102]
  - providers/virtualbox: Virtualbox 5.2 support [GH-8955]

IMPROVEMENTS:

  - command/destroy: Introduce parallel destroy for certain providers [GH-9127]
  - communicators/winrm: Include APIPA check within ready check [GH-8997]
  - core: Clear POSIXLY_CORRECT when using optparse [GH-8685]
  - docs: Add auto_start_action and auto_stop_action to docs. [GH-9029]
  - docs: Fix typo in box format doc [GH-9100]
  - provisioners/chef: Handle chef provisioner reboot request [GH-8874]
  - providers/salt: Support Windows Salt Minions greater than 2016.x.x [GH-8926]
  - provisioners/salt: Add wget to bootstrap_salt options when fetching installer file [GH-9112]
  - provisioners/shell: Use ui.detail for displaying output [GH-8983]
  - util/downloader: Use CURL_CA_BUNDLE environment variable [GH-9135]

BUG FIXES:

  - communicators/ssh: Retry on Errno::EPIPE exceptions [GH-9065]
  - core: Rescue more exceptions when checking if port is open [GH-8517]
  - guests/solaris11: Inherit from Solaris guest and keep solaris11 specific methods [GH-9034]
  - guests/windows: Split out cygwin path helper for msys2/cygwin paths and ensure cygpath exists [GH-8972]
  - guests/windows: Specify expected shell when executing on guest (fixes winssh communicator usage) [GH-9012]
  - guests/windows: Include WinSSH Communicator when using insert_public_key [GH-9105]
  - hosts/windows: Check for vagrant.exe when validating versions within WSL [GH-9107, GH-8962]
  - providers/docker: Isolate windows check within executor to handle running through VM [GH-8921]
  - providers/hyper-v: Properly invoke Auto stop action [GH-9000]
  - provisioners/puppet: Fix winssh communicator support in puppet provisioner [GH-9014]
  - virtualbox/synced_folders: Allow synced folders to contain spaces in the guest path [GH-8995]
```
(https://github.com/hashicorp/vagrant/blob/v2.0.1/CHANGELOG.md#201-november-2-2017)

**Comment by grahamc** [comment]
This patch was applied to master: https://github.com/NixOS/nixpkgs/commit/d7aefea2ef4248a8138de15baad228ebce21e737 and I triggered the evaluation checks  to run again. That is why it started passing again :)

**Comment by andir** [comment]
Ahhh, okay.. Since I didn't know the exact error I didn't think of that fixing it... Totally makes sense now :-)

**Pull request merged**
