### PR TITLE
dovecot_fts_xapian: 1.3.1 -> 1.3.3

### PR DESCRIPTION
**Pull request by symphorien**
###### Motivation for this change

update

###### Things done

I tested with a nixos test I wrote for a module which is not upstream yet

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by symphorien** [comment]
cc @ju1m

**Comment by ju1m** [comment]
@symphorien, thanks for this update. This PR works for me.

**Comment by ajs124** [comment]
1.4.6 is out meanwhile. are either of you actively using this?

**Comment by symphorien** [comment]
Yes, I do, but I'm still using the version in nixpkgs. I'll try and update this.

**Comment by symphorien** [comment]
superseded by https://github.com/NixOS/nixpkgs/pull/111041

**Pull request closed without merging**
