### PR TITLE
haskell-modules: split off nix-specific overrides and common ones

### PR DESCRIPTION
**Pull request by bennofs**
This allows the nix-specific overrides to be reused for other purposes,
with different haskell package sets, etc.

To verify that I didn't mess anything up, I ran the following command both before and after
making the changes:

```
$ nix-instantiate -A haskellPackages --arg config '{allowBroken = true; allowUnfree = true; }'
```

This produced the following diff:

```
2000c2000
< /nix/store/6vgdp0z0x0bv8kl8d2ka98wnyd84f72v-black-jewel-0.0.0.1.drv
---
> /nix/store/31bfq8pwh42jrlrhhxpr3w253n9i67ka-black-jewel-0.0.0.1.drv
3351c3351
< /nix/store/51606q0gdnmhnzm6m3mihn6apvgcg59i-download-0.3.2.5.drv
---
> /nix/store/9cb00p6a2ghljwpng2qi8g2ch6wflvhf-download-0.3.2.5.drv
4180c4180
< /nix/store/i6kvbsv51m1wmcpnaaqswxprrvpxzxbq-ghcjs-hplay-0.3.4.2.drv
---
> /nix/store/jig283apjpphhcin8hs8j363pbfpq22a-ghcjs-hplay-0.3.4.2.drv
4754c4754
< /nix/store/h125bwab6idwsg546jxkwvn7jvmi5yi1-hackage-sparks-0.5.1.drv
---
> /nix/store/awpxsbdhk7bpc529s84xqib628754van-hackage-sparks-0.5.1.drv
4756c4756
< /nix/store/bigrl8c1q8g69gmn3w9bcn3ysd3gim9h-hackage2hwn-0.5.1.drv
---
> /nix/store/88j55rmbws3dlkmbqkyrniab9xk2gj8j-hackage2hwn-0.5.1.drv
```

The changes are due to the fact that I added `download` to the list of packages
whose test suite requires networking access. All listed derivations depend on
`download`. Before merging this, I should split that change into a separate commit.

/cc @peti

### CODE REVIEW

**Comment by peti** [comment]
This is really nice, great job cleaning up the overrides!

**Comment by bennofs** [comment]
I've split off the `dontCheck download` now

**Comment by bennofs** [comment]
I've moved the `dontCheck download` into a different commit now

**Comment by peti** [comment]
Merged to `haskell-updates`. Test builds are running at http://hydra.nixos.org/jobset/nixpkgs/haskell-updates.

**Comment by bennofs** [comment]
Whoops, I think I've messed up the idris override

**Comment by bennofs** [comment]
@peti idris failure should be fixed now. Seems like I did some changes between running my "check" (that the derivations are equal) and submitting the PR ...

**Comment by peti** [comment]
I've merged the current version of this PR into 6c290e4b989463d6090e93a14149af3847bc49b8 and 535b91842b6b84a726075254925488d0fe9c988d and re-based it on top of the current `master`. I hope I made no mistake, but IMHO things look good. I'll let http://hydra.nixos.org/jobset/nixpkgs/haskell-updates one more shot at this, and then I'll merge.

**Comment by domenkozar** [comment]
This is now in master.

**Pull request closed without merging**
