### PR TITLE
yq-go: 3.3.0 -> 3.3.1

### PR DESCRIPTION
**Pull request by zowoq**
https://github.com/mikefarah/yq/releases/tag/3.3.1

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by marsam** [comment]
looks like it added support for completions; Would you mind adding the following?
```nix
  postInstall = ''
    for shell in bash fish zsh; do
      $out/bin/yq shell-completion --variation $shell > yq.$shell
      installShellCompletion yq.$shell
    done
  '';
```

**Comment by zowoq** [comment]
> looks like it added support for completions

They don't seem to work, I had already added them and then force pushed to drop them.

**Comment by marsam** [comment]
oh, did you try with the `--variation` flag?

**Comment by zowoq** [comment]
> oh, did you try with the `--variation` flag?

Apparently not, I must have dropped it instead of squashing so I actually tested the same command twice. 🤦

**Comment by marsam** [comment]
Thank you

**Pull request merged**
