### PR TITLE
emacs-htmlize:  fix url -- see http://fly.srk.fer.hr/

### PR DESCRIPTION
**Pull request by deepfire**
###### Motivation for this change

The origin for the download was lost, for explanation see http://fly.srk.fer.hr/
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux

### CODE REVIEW

**Comment by mdorman** [comment]
melpa itself has chosen to draw from somewhere else, so this seems like a poor choice.  From [the updated recipe](https://github.com/melpa/melpa/blob/master/recipes/htmlize):

```
(htmlize
 :repo "dunn/htmlize-mirror"
:fetcher github)
```

**Comment by deepfire** [comment]
@mdorman, it doesn't make any difference, since the autogenerator for `melpa-packages.nix` will revert to whatever melpa provides.  For now the precise commit is available from a number of repositories.

It's appears to be of no importance what source for the exact same commit is chosen in the interim.

**Comment by joachifm** [comment]
cc @ttuegel

**Comment by ttuegel** [comment]
Please do not manually edit generated files; use [emacs2nix](https://github.com/ttuegel/emacs2nix) to update the package instead.

**Pull request closed without merging**
