### PR TITLE
Run elm update script

### PR DESCRIPTION
**Pull request by jaredramirez**
Ran the elm update script

elm-language-server 1.13.1
create-elm-app 5.9.0

Very similar to https://github.com/NixOS/nixpkgs/pull/99671

###### Motivation for this change
Upgrade elm-language-server, current nixpkg version elm-language-server had a bug that caused it to fail in vim

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

@turboMaCk - You were @'d in the [last elm pr](https://github.com/NixOS/nixpkgs/pull/99671), so I'm mentioning you here too!

### CODE REVIEW

**Review by jonringer — COMMENTED** [review]
commit should probably be:
```
elmPackages: update
```
please amend commit

**Comment by jaredramirez** [comment]
Renamed commit

**Review by jonringer — APPROVED** [review]
LGTM

```
https://github.com/NixOS/nixpkgs/pull/101085
10 packages built:
elmPackages.create-elm-app elmPackages.elm-analyse elmPackages.elm-coverage elmPackages.elm-doc-preview elmPackages.elm-language-server elmPackages.elm-live elmPackages.elm-optimize-level-2 elmPackages.elm-test elmPackages.elm-upgrade elmPackages.elm-verify-examples
```

**Comment by turboMaCk** [comment]
thanks @jaredramirez

**Pull request merged**
