### PR TITLE
nixos/acme: Add option to make certificates world readable

### PR DESCRIPTION
**Pull request by malte-v**
###### Motivation for this change
I generate wildcard certificates using a local BIND instance and use them for a lot of different services, and even in containers by mounting them. It is quite a pain to figure out the users of all the services I'm running so I can add them to the `acme` group. I'm willing to accept the security risk of making the certificates world readable (if someone manages to break into my system, I have bigger problems than comprimised SSL keys).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Why are you not using a reverse proxy that does TLS? If you are using nginx then you only need this line and you are done: ``users.users.nginx.extraGroups = [ "acme" ];``

**Comment by malte-v** [comment]
I *am* using nginx as a reverse proxy, it's just that I have more than a web server running. I don't think you can reverse proxy IMAPS/SMTPS with nginx.

**Comment by roberth** [comment]
Nobody should use this. We should encourage service module authors to add options for acme instead. That way, you won't have to deal with configuring file paths either.

Adding a service user to a group isn't a hard problem, so we shouldn't accept this as a workaround.

**Comment by malte-v** [comment]
I admit that this PR is stupid. I've added all the service users to the group and it isn't very hard to do.

**Pull request closed without merging**
