### PR TITLE
perlPackages.Mojolicious: 9.10 -> 9.17

### PR DESCRIPTION
**Pull request by zakame**
###### Motivation for this change

https://metacpan.org/release/SRI/Mojolicious-9.17

In particular, there is a *security* fix in https://metacpan.org/release/SRI/Mojolicious-9.11 which breaks some modules - these are also updated accordingly.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by stigtsp** [comment]
https://github.com/mojolicious/mojo/commit/a0c4576ffb11c235088550de9ba7ac4196e1953c

**Comment by stigtsp** [comment]
@GrahamcOfBorg build perlPackages.Mojolicious perlPackages.MojoliciousPluginStatus perlPackages.JSONValidator perlPackages.LinkEmbedder perlPackages.MojoliciousPluginOpenAPI perlPackages.MojoliciousPluginTextExceptions
@GrahamcOfBorg build convos.tests

**Comment by stigtsp** [comment]
Consider a port to 20.09 of the Mojolicious bump (this PR contains several bumps).

**Review by stigtsp — APPROVED** [review]
LGTM

**Comment by zakame** [comment]
Thanks @stigtsp	!  Will try that 20.09 port :muscle:

**Pull request merged**
