### PR TITLE
Poezio bump

### PR DESCRIPTION
**Pull request by lheckemann**
###### Motivation for this change
New upstream version. cc maintainer @lsix 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distrib utions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by lsix — CHANGES_REQUESTED** [review]
Hi,

Thanks for the PR,

Can the `slixmpp` declaration be moved outside of the `python-packages.nix` file while it is being updated? (it should go into `pkgs/development/python-modules/slixmpp/default.nix`).

On another subject, I guess (hope) we can depend on `gnupg` instead of `gnupg1`. This will require some investigation and tests, but it would be nice to rely on the main maintained branch instead of the old 1 branch.

I have built and launched your updated version of `poezio` and it works as expected! Thanks

**Comment by lheckemann** [comment]
I've tentatively switched the references to gnupg rather than gnupg1, but I don't use the gpg functionality myself so I haven't tested it.

**Comment by lsix** [comment]
I also do not use GPG with poesio on my side, but apparently, archlinux uses the main gnupg (no version requirement mentionned: https://aur.archlinux.org/packages/poezio/). I think we can do that on our side.

I did not realized on my first read, but could you also move the declaration of poezio outside of python-packages.nix as well?

**Comment by lheckemann** [comment]
>could you also move the declaration of poezio outside of python-packages.nix as well?

 :man_facepalming: of course

**Comment by FRidh** [comment]
please rebase onto staging due to the large changes in `python-packages.nix` in there

**Comment by lheckemann** [comment]
@FRidh only slixmpp and poezio are affected, and poezio is the only thing that depends on slixmpp. I've just moved them out, so this shouldn't cause much in the way of rebuilds, so I think master is still the appropriate target.

**Comment by FRidh** [comment]
It's not about rebuilds, but to prevent merge conflicts.

**Review by globin — APPROVED** [review]

**Review by lsix — APPROVED** [review]

**Pull request merged**
