### PR TITLE
nixos/caddy: set extraDomainNames for acme

### PR DESCRIPTION
**Pull request by jian-lin**
###### Description of changes

Doing so is reasonable and nginx module also does so.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by aanderse — COMMENTED** [review]
- does this merge properly if you have multiple virtual hosts using the same `useACMEHost` value?
- does this PR solve a specific problem you are having in your configuration?

**Comment by jian-lin** [comment]
> does this merge properly if you have multiple virtual hosts using the same useACMEHost value?

Good catch.  Currently, it does not.

> does this PR solve a specific problem you are having in your configuration?

This does solve a problem, which I do not have because I do not use `serverAliases`.

The problem occurs when the acme module (lego) uses caddy to complete http-01 challenges.

- The acme module is needed because the user service FOO of the certs needs to get notified when the certs are renewed.
- caddy is needed because it is used as a reverse proxy for some other services.
- http-01 challenge is used because dns-01 is not possible. tls-alpn-01 challenge is similar to http-01 challenge here.

An example for FOO is [NixOS Mailserver][1] with non-empty `mailserver.certificateDomains` and `mailserver.certificateScheme = "acme"`.

So one decides to *mimic the nginx config* of NixOS Mailserver for caddy.  In this case, it's easy to overlook `extraDomainNames`.
```nix
{ config, ... }:

let
  fqdn = "mail.example.com";
in
{
  mailserver = {
    ...
    fqdn = "mail.example.com";
    certificateDomains = [ "imap.example.com" ];
    certificateScheme = "acme";
  };
  services.caddy = {
    ...
    virtualHosts.${fqdn} = {
      useACMEHost = fqdn;
      serverAliases = config.mailserver.certificateDomains;
      extraConfig = ''
        file_server /.well-known/acme-challenge/* {
          root ${config.security.acme.certs.${fqdn}.webroot}
        }
      '';
    };
  };
  security.acme.certs.${fqdn} = {
    webroot = "...";
    # XXX he overlooks extraDomainNames
  };
}
```

IMHO, setting `extraDomainNames` in caddy module is a good idea.

[1]: https://nixos-mailserver.readthedocs.io/en/nixos-23.05/options.html#mailserver-certificate

**Comment by aanderse** [comment]
> The acme module is needed because the service FOO which uses those certs needs to get notified when the certs are renewed.

Wouldn't it make sense to just have `caddy` ping your mail server when new certificates are available? It looks like @emilylange already had some thoughts and comments on that in https://github.com/caddyserver/caddy/issues/3643.

Really the `useACMEHost` was added a workaround to avoid building `caddy` with plugins. I'm not sure if it is a good idea to expand it much or not 🤔

What do you think @emilylange?

**Comment by jian-lin** [comment]
> Wouldn't it make sense to just have caddy ping your mail server when new certificates are available? 

That would be great but I do not think caddy is able to do that.

> does this merge properly if you have multiple virtual hosts using the same useACMEHost value?
> Really the useACMEHost was added a workaround to avoid building caddy with plugins.

What is this use case? From the description you added for `useACMEHost` option and the above lines, it seems that you want to use a wildcard cert (dns-01 challenge) for multiple domains with caddy.  That is also a quite less common use case.  Since this PR is based on the nginx module, does the nginx module support that?

That said, it is possible to change this PR to properly merge domains.  However, I consider my implementation inelegant.

This is more complicate than I thought, and I do not have enough time for it. So I will close this PR.

Thanks for your review.

**Comment by aanderse** [comment]
I think `caddy` does support this with the additions of events.

**Comment by emilylange** [comment]
A bit late to the party, but yeah, Caddy does support a variant of this via events using e.g. https://github.com/mholt/caddy-events-exec

But that is still in a somewhat early stage, and building Caddy with plugins in nixpkgs is quite a hassle as of right now, unfortunately.
See #14671

**Comment by jian-lin** [comment]
Thanks for the info of caddy event handler, which did not exist last time I checked[1].

Using https://github.com/mholt/caddy-events-exec and giving the `caddy` user permissions to reload the needed service seems doable.

[1]: https://github.com/caddyserver/dist/pull/84

**Pull request closed without merging**
