### PR TITLE
python3Packages.uvloop: use system libuv

### LINKED ISSUE #62970: uvloop isn't using system libuv
## Issue description

uvloop should have a way to build with the system libuv. However, currently, it is trying to build libuv itself each time.

See https://github.com/MagicStack/uvloop/blob/master/setup.py#L72

https://hydra.nixos.org/build/94429522

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

### PR DESCRIPTION
**Pull request by FliegendeWurst**
Fixes #62970

## Things done

- Built on platform(s)
  - [x] x86_64-linux
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Yeeting the vendor dir makes the build fail, so I'm not sure the arguments are passed correctly.

**Comment by FliegendeWurst** [comment]
> Yeeting the vendor dir makes the build fail, so I'm not sure the arguments are passed correctly.

You can try removing `libuv` from `buildInputs`, the build will fail then. That makes me think it depends on the system library. Not sure about the vendored code.

**Comment by mweinelt** [comment]
I patched into the build_libuv function (see the canary line), and here it is building the vendored libuv.

```
uvloop> running build_ext
uvloop> canary build_libuv
uvloop> checking for a BSD-compatible install... /nix/store/k48bha2fjqzarg52picsdfwlqx75aqbb-coreutils-9.5/bin/install -c
uvloop> checking whether build environment is sane... yes
uvloop> checking for x86_64-unknown-linux-gnu-strip... strip
uvloop> checking for a race-free mkdir -p... /nix/store/k48bha2fjqzarg52picsdfwlqx75aqbb-coreutils-9.5/bin/mkdir -p
uvloop> checking for gawk... gawk
uvloop> checking whether make sets $(MAKE)... yes
uvloop> checking whether make supports nested variables... yes
uvloop> checking whether to enable maintainer-specific portions of Makefiles... yes
uvloop> checking build system type... x86_64-pc-linux-gnu
uvloop> checking host system type... x86_64-unknown-linux-gnu
uvloop> checking for x86_64-unknown-linux-gnu-gcc... gcc
uvloop> checking whether the C compiler works... yes
uvloop> checking for C compiler default output file name... a.out
uvloop> checking for suffix of executables... 
uvloop> checking whether we are cross compiling... no
uvloop> checking for suffix of object files... o
uvloop> checking whether the compiler supports GNU C... yes
uvloop> checking whether gcc accepts -g... yes
uvloop> checking for gcc option to enable C11 features... none needed
uvloop> checking whether gcc understands -c and -o together... yes
uvloop> checking whether make supports the include directive... yes (GNU style)
uvloop> checking dependency style of gcc... gcc3
uvloop> checking for gcc way to treat warnings as errors... -Werror
uvloop> checking if gcc supports __attribute__(( visibility("default") ))... yes
uvloop> checking if gcc supports -fvisibility=hidden... yes
uvloop> checking if gcc supports -fno-strict-aliasing flag... yes
uvloop> checking if gcc supports -fno-strict-aliasing flag... yes
uvloop> checking if gcc supports -g flag... yes
uvloop> checking if gcc supports -std=gnu89 flag... yes
uvloop> checking if gcc supports -Wall flag... yes
uvloop> checking if gcc supports -Wextra flag... yes
uvloop> checking if gcc supports -Wno-long-long flag... yes
uvloop> checking if gcc supports -Wno-unused-parameter flag... yes
uvloop> checking if gcc supports -Wstrict-prototypes flag... yes
uvloop> checking for x86_64-unknown-linux-gnu-ar... ar
uvloop> checking the archiver (ar) interface... ar
uvloop> checking how to print strings... printf
uvloop> checking for a sed that does not truncate output... /nix/store/gvivnz7rb2gz1vy7d9mdxgzj9didz7w2-gnused-4.9/bin/sed
uvloop> checking for grep that handles long lines and -e... /nix/store/14aswfz6pm8zvyyy927xzmi8x4rnvlc8-gnugrep-3.11/bin/grep
uvloop> checking for egrep... /nix/store/14aswfz6pm8zvyyy927xzmi8x4rnvlc8-gnugrep-3.11/bin/grep -E
uvloop> checking for fgrep... /nix/store/14aswfz6pm8zvyyy927xzmi8x4rnvlc8-gnugrep-3.11/bin/grep -F
uvloop> checking for ld used by gcc... ld
uvloop> checking if the linker (ld) is GNU ld... yes
uvloop> checking for BSD- or MS-compatible name lister (nm)... nm
uvloop> checking the name lister (nm) interface... BSD nm
uvloop> checking whether ln -s works... yes
uvloop> checking the maximum length of command line arguments... 1572864
uvloop> checking how to convert x86_64-pc-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
uvloop> checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
uvloop> checking for ld option to reload object files... -r
uvloop> checking for x86_64-unknown-linux-gnu-objdump... objdump
uvloop> checking how to recognize dependent libraries... (cached) pass_all
uvloop> checking for x86_64-unknown-linux-gnu-dlltool... no
uvloop> checking for dlltool... no
uvloop> checking how to associate runtime and link libraries... printf %s\n
uvloop> checking for x86_64-unknown-linux-gnu-ar... (cached) ar
uvloop> checking for archiver @FILE support... @
uvloop> checking for x86_64-unknown-linux-gnu-strip... (cached) strip
uvloop> checking for x86_64-unknown-linux-gnu-ranlib... ranlib
uvloop> checking command to parse nm output from gcc object... ok
uvloop> checking for sysroot... no
uvloop> checking for a working dd... /nix/store/k48bha2fjqzarg52picsdfwlqx75aqbb-coreutils-9.5/bin/dd
uvloop> checking how to truncate binary pipes... /nix/store/k48bha2fjqzarg52picsdfwlqx75aqbb-coreutils-9.5/bin/dd bs=4096 count=1
uvloop> checking for x86_64-unknown-linux-gnu-mt... no
uvloop> checking for mt... no
uvloop> checking if : is a manifest tool... no
uvloop> checking for stdio.h... yes
uvloop> checking for stdlib.h... yes
uvloop> checking for string.h... yes
uvloop> checking for inttypes.h... yes
uvloop> checking for stdint.h... yes
uvloop> checking for strings.h... yes
uvloop> checking for sys/stat.h... yes
uvloop> checking for sys/types.h... yes
uvloop> checking for unistd.h... yes
uvloop> checking for dlfcn.h... yes
uvloop> checking for objdir... .libs
uvloop> checking if gcc supports -fno-rtti -fno-exceptions... no
uvloop> checking for gcc option to produce PIC... -fPIC -DPIC
uvloop> checking if gcc PIC flag -fPIC -DPIC works... yes
uvloop> checking if gcc static flag -static works... no
uvloop> checking if gcc supports -c -o file.o... yes
uvloop> checking if gcc supports -c -o file.o... (cached) yes
uvloop> checking whether the gcc linker (ld -m elf_x86_64) supports shared libraries... yes
uvloop> checking whether -lc should be explicitly linked in... no
uvloop> checking dynamic linker characteristics... GNU/Linux ld.so
uvloop> checking how to hardcode library paths into programs... immediate
uvloop> checking whether stripping libraries is possible... yes
uvloop> checking if libtool supports shared libraries... yes
uvloop> checking whether to build shared libraries... yes
uvloop> checking whether to build static libraries... yes
uvloop> checking whether make supports nested variables... (cached) yes
uvloop> checking how to run the C preprocessor... gcc -E
uvloop> checking whether gcc is Clang... no
uvloop> checking whether pthreads work with -pthread... yes
uvloop> checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
uvloop> checking whether more special flags are required for pthreads... no
uvloop> checking for PTHREAD_PRIO_INHERIT... yes
uvloop> checking for library containing dlopen... none required
uvloop> checking for library containing kstat_lookup... no
uvloop> checking for library containing gethostbyname... none required
uvloop> checking for library containing perfstat_cpu... no
uvloop> checking for library containing clock_gettime... none required
uvloop> checking for library containing sendfile... none required
uvloop> checking for library containing socket... none required
uvloop> checking for special C compiler options needed for large files... no
uvloop> checking for _FILE_OFFSET_BITS value needed for large files... no
uvloop> checking for sys/ahafs_evProds.h... no
uvloop> checking that generated files are newer than configure... done
uvloop> configure: creating ./config.status
uvloop> config.status: creating Makefile
uvloop> config.status: creating libuv.pc
uvloop> config.status: executing depfiles commands
uvloop> config.status: executing libtool commands
uvloop>   CC       src/libuv_la-fs-poll.lo
uvloop>   CC       src/libuv_la-idna.lo
uvloop>   CC       src/libuv_la-inet.lo
uvloop>   CC       src/libuv_la-random.lo
uvloop>   CC       src/libuv_la-strscpy.lo
uvloop>   CC       src/libuv_la-thread-common.lo
uvloop>   CC       src/libuv_la-threadpool.lo
uvloop>   CC       src/libuv_la-timer.lo
uvloop>   CC       src/libuv_la-uv-data-getter-setters.lo
uvloop>   CC       src/libuv_la-uv-common.lo
uvloop>   CC       src/libuv_la-version.lo
uvloop>   CC       src/libuv_la-strtok.lo
uvloop>   CC       src/unix/libuv_la-async.lo
uvloop>   CC       src/unix/libuv_la-core.lo
uvloop>   CC       src/unix/libuv_la-getaddrinfo.lo
uvloop>   CC       src/unix/libuv_la-dl.lo
uvloop>   CC       src/unix/libuv_la-fs.lo
uvloop>   CC       src/unix/libuv_la-getnameinfo.lo
uvloop>   CC       src/unix/libuv_la-loop.lo
uvloop>   CC       src/unix/libuv_la-pipe.lo
uvloop>   CC       src/unix/libuv_la-loop-watcher.lo
uvloop>   CC       src/unix/libuv_la-poll.lo
uvloop>   CC       src/unix/libuv_la-process.lo
uvloop>   CC       src/unix/libuv_la-random-devurandom.lo
uvloop>   CC       src/unix/libuv_la-stream.lo
uvloop>   CC       src/unix/libuv_la-signal.lo
uvloop>   CC       src/unix/libuv_la-tcp.lo
uvloop>   CC       src/unix/libuv_la-linux.lo
uvloop>   CC       src/unix/libuv_la-tty.lo
uvloop>   CC       src/unix/libuv_la-thread.lo
uvloop>   CC       src/unix/libuv_la-procfs-exepath.lo
uvloop>   CC       src/unix/libuv_la-udp.lo
uvloop>   CC       src/unix/libuv_la-proctitle.lo
uvloop>   CC       src/unix/libuv_la-random-getrandom.lo
uvloop>   CC       src/unix/libuv_la-random-sysctl-linux.lo
uvloop>   CCLD     libuv.la
uvloop> installing to build/bdist.l
```

**Comment by mweinelt** [comment]
This is what works for me. PTAL.

**Comment by mweinelt** [comment]
AIUI: The call to `build_libuv` is in the else clause and only happens when use_system_libuv is `False`. This in turn means that if it gets built, the toggle didn't get propagated correctly.

https://github.com/MagicStack/uvloop/blob/7bb12a174884b2ec8b3162a08564e5fb8a5c6b39/setup.py#L193-L208

**Comment by FliegendeWurst** [comment]
Well, here is what `ldd` says:
```
> ldd /nix/store/viiqsdkziwnzpjj8bj98n3c2wplhs4ra-python3.11-uvloop-0.21.0/lib/python3.11/site-packages/uvloop/loop.cpython-311-x86_64-linux-gnu.so
        linux-vdso.so.1 (0x00007ffe599ba000)
        libuv.so.1 => /nix/store/if1558fw8f93v5h0fl5x8gbz17n6q682-libuv-1.48.0/lib/libuv.so.1 (0x00007fe6a2a22000)
        librt.so.1 => /nix/store/8kzsh7c6qj91kqc6dirylfl8vgd4sqwi-glibc-2.40-36/lib/librt.so.1 (0x00007fe6a2a1d000)
        libpthread.so.0 => /nix/store/8kzsh7c6qj91kqc6dirylfl8vgd4sqwi-glibc-2.40-36/lib/libpthread.so.0 (0x00007fe6a2a18000)
        libc.so.6 => /nix/store/8kzsh7c6qj91kqc6dirylfl8vgd4sqwi-glibc-2.40-36/lib/libc.so.6 (0x00007fe6a281f000)
        /nix/store/kpy2cyd05vdr6j1h200av81fnlxl1jw0-glibc-2.39-52/lib64/ld-linux-x86-64.so.2 (0x00007fe6a2c03000)
```
But I prefer your solution anyway, it is a lot cleaner.

**Comment by mweinelt** [comment]
The prior art also uses patching fwiw:
- Fedora: https://src.fedoraproject.org/rpms/python-uvloop/blob/rawhide/f/python-uvloop.spec#_39
- Gentoo: https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-python/uvloop/uvloop-0.21.0.ebuild#n42
- Arch: https://gitlab.archlinux.org/archlinux/packaging/packages/python-uvloop/-/blob/main/PKGBUILD?ref_type=heads#L34
- openSUSE: https://build.opensuse.org/projects/openSUSE:Factory/packages/python-uvloop/files/python-uvloop.spec?expand=1

**Pull request merged**
