### PR TITLE
Staging next

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
there should be 1 more staging-next cycle after this for branch off, which is currently projected to be  September 4th.

**Comment by jonringer** [comment]
@FRidh did you want to do a python package set update? I'm going to go to bed soon, but I'll have most of my sunday to do stabilization.

**Comment by FRidh** [comment]
@jonringer Yes I'd like to have one for the next cycle. I can make a start with it.

**Comment by FRidh** [comment]
qtquickcontrols failure is blocking KDE https://hydra.nixos.org/build/125404486. cc @petabyteboy @ttuegel

**Pull request merged**
