### PR TITLE
g2o: 20230223 -> 20230806

### PR DESCRIPTION
**Pull request by lopsided98**
## Description of changes

https://github.com/RainerKuemmerle/g2o/releases/tag/20230806_git

The only package in nixpkgs that depends on g2o is rtabmap, which requires a patch to be compatible with this update. There are ROS distro specific tags of rtabmap 0.21.1 (ie. [`0.21.1-rolling`](https://github.com/introlab/rtabmap/releases/tag/0.21.1-rolling), [`0.21.1-humble`](https://github.com/introlab/rtabmap/releases/tag/0.21.1-humble), etc.) that include this patch, but there is no plain `0.21.1` tag, so I decided not to update rtabmap and just backport the patch.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

cc @ckiee

### CODE REVIEW

**Comment by ckiee** [comment]
thank you! feel free to add yourself to rtabmap's maintainer list if you'd like that (:

---

Result of `nixpkgs-review pr 250016` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>g2o</li>
    <li>g2o.debug</li>
    <li>g2o.dev</li>
    <li>rtabmap</li>
  </ul>
</details>

---

rtabmap does run, but I will not be testing with hardware as there's significant setup with mine:

screenshot of an empty rtabmap session

**Comment by lopsided98** [comment]
I don't currently use rtabmap, so I don't think I should be a maintainer.

**Comment by lopsided98** [comment]
@ckiee Can this be merged?

**Comment by ckiee** [comment]
@lopsided98 no idea why i didn't merge! will rerun tests now (:

**Review by ckiee — APPROVED** [review]
4 packages built:
g2o g2o.debug g2o.dev rtabmap
 
Result of `nixpkgs-review pr 250016` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>g2o</li>
    <li>g2o.debug</li>
    <li>g2o.dev</li>
    <li>rtabmap</li>
  </ul>
</details>

**Pull request merged**
