### PR TITLE
pipewire: 0.3.71 -> 0.3.72

### PR DESCRIPTION
**Pull request by K900**
Diff: https://gitlab.freedesktop.org/pipewire/pipewire/-/compare/0.3.71...0.3.72

###### Description of changes

Now with 1394% more FireWire.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Janik-Haag** [comment]
What made you realize that firewire support was missing? Or did some one upstream add it in the new version?

**Comment by K900** [comment]
It was added in this release upstream.

**Review by Janik-Haag — COMMENTED** [review]
Please add a [change log entry](https://gitlab.freedesktop.org/pipewire/pipewire/-/releases/0.3.72) in the meta attributes, code looks good still waiting for the local build.

**Comment by K900** [comment]
Huh, I was sure we had that. Oh well.

**Comment by Janik-Haag** [comment]
hm build failed for me locally because of a timeout:
```
post-installation fixup
Moving /nix/store/v09hbczv5rs5zjrca0dmd0bny0gb9w22-libjxl-0.8.2/lib/pkgconfig to /nix/store/0582pv9k725jwy7pbmn4bbrbnl9hvp8d-libjxl-0.8.2-dev/lib/pkgconfig
[236/240] Linking target tests/websocket-test
Patching '/nix/store/0582pv9k725jwy7pbmn4bbrbnl9hvp8d-libjxl-0.8.2-dev/lib/pkgconfig/libjxl.pc' includedir to output /nix/store/0582pv9k725jwy7pbmn4bbrbnl9hvp8d-libjxl-0.8.2-dev
Patching '/nix/store/0582pv9k725jwy7pbmn4bbrbnl9hvp8d-libjxl-0.8.2-dev/lib/pkgconfig/libjxl_threads.pc' includedir to output /nix/store/0582pv9k725jwy7pbmn4bbrbnl9hvp8d-libjxl-0.8.2-dev
[205/321] Compiling C object libsoup/libsoup-3.0-static.a.p/soup-header-names.c.o
shrinking RPATHs of ELF executables and libraries in /nix/store/v09hbczv5rs5zjrca0dmd0bny0gb9w22-libjxl-0.8.2
shrinking /nix/store/v09hbczv5rs5zjrca0dmd0bny0gb9w22-libjxl-0.8.2/bin/djxl
shrinking /nix/store/v09hbczv5rs5zjrca0dmd0bny0gb9w22-libjxl-0.8.2/bin/jxlinfo
shrinking /nix/store/v09hbczv5rs5zjrca0dmd0bny0gb9w22-libjxl-0.8.2/bin/benchmark_xl
[206/321] Compiling C object libsoup/libsoup-3.0-static.a.p/soup-client-input-stream.c.o
[237/240] Generating libsoup/Soup-2.4.typelib with a custom command
shrinking /nix/store/v09hbczv5rs5zjrca0dmd0bny0gb9w22-libjxl-0.8.2/bin/cjxl
shrinking /nix/store/v09hbczv5rs5zjrca0dmd0bny0gb9w22-libjxl-0.8.2/bin/cjpeg_hdr
[ 48%] Building C object src/CMakeFiles/libcmark.dir/html.c.o
shrinking /nix/store/v09hbczv5rs5zjrca0dmd0bny0gb9w22-libjxl-0.8.2/lib/libjxl_threads.so.0.8.2
[207/321] Compiling C object libsoup/libsoup-3.0-static.a.p/websocket_soup-websocket-connection.c.o
shrinking /nix/store/v09hbczv5rs5zjrca0dmd0bny0gb9w22-libjxl-0.8.2/lib/libjxl.so.0.8.2
[208/321] Compiling C object libsoup/libsoup-3.0-static.a.p/soup-http2-utils.c.o
[209/321] Compiling C object libsoup/libsoup-3.0-static.a.p/soup-date-utils.c.o
checking for references to /build/ in /nix/store/v09hbczv5rs5zjrca0dmd0bny0gb9w22-libjxl-0.8.2...
patching script interpreter paths in /nix/store/v09hbczv5rs5zjrca0dmd0bny0gb9w22-libjxl-0.8.2
stripping (with command strip and flags -S -p) in  /nix/store/v09hbczv5rs5zjrca0dmd0bny0gb9w22-libjxl-0.8.2/lib /nix/store/v09hbczv5rs5zjrca0dmd0bny0gb9w22-libjxl-0.8.2/bin
[ 51%] Building C object src/CMakeFiles/libcmark.dir/commonmark.c.o
[210/321] Compiling C object libsoup/libsoup-3.0-static.a.p/soup-init.c.o
[211/321] Compiling C object libsoup/libsoup-3.0-static.a.p/soup-connection-manager.c.o
[212/321] Compiling C object libsoup/libsoup-3.0-static.a.p/soup-form.c.o
[56/154] Compiling C object src/libqmi-glib/libqmi-glib-compat.a.p/qmi-compat.c.o
[57/154] Linking static target src/libqmi-glib/libqmi-glib-compat.a
[58/301] Compiling C++ object src/libharfbuzz.so.0.60730.0.p/hb-ft.cc.o
[238/240] Generating libsoup/libsoup-2.4.vapi with a custom command
[213/321] Compiling C object libsoup/libsoup-3.0-static.a.p/soup-logger-input-stream.c.o
[214/321] Compiling C object libsoup/libsoup-3.0-static.a.p/soup-io-stream.c.o
[58/154] Compiling C object src/libqmi-glib/libqmi-glib.so.5.9.0.p/qmi-endpoint.c.o
[215/321] Compiling C object libsoup/libsoup-3.0-static.a.p/soup-connection.c.o
[ 55%] Building C object src/CMakeFiles/libcmark.dir/latex.c.o
shrinking RPATHs of ELF executables and libraries in /nix/store/0582pv9k725jwy7pbmn4bbrbnl9hvp8d-libjxl-0.8.2-dev
[217/321] Compiling C object libsoup/libsoup-3.0-static.a.p/soup-method.c.o
Summary of Failures:
checking for references to /build/ in /nix/store/0582pv9k725jwy7pbmn4bbrbnl9hvp8d-libjxl-0.8.2-dev...
[218/321] Compiling C object libsoup/libsoup-3.0-static.a.p/soup-headers.c.o
patching script interpreter paths in /nix/store/0582pv9k725jwy7pbmn4bbrbnl9hvp8d-libjxl-0.8.2-dev
stripping (with command strip and flags -S -p) in  /nix/store/0582pv9k725jwy7pbmn4bbrbnl9hvp8d-libjxl-0.8.2-dev/lib
[59/154] Compiling C object src/libqmi-glib/libqmi-glib.so.5.9.0.p/qmi-device.c.o
[219/321] Compiling C object libsoup/libsoup-3.0-static.a.p/soup-message-headers.c.o
[220/321] Compiling C object libsoup/libsoup-3.0-static.a.p/soup-logger.c.o
[60/154] Compiling C object src/libqmi-glib/libqmi-glib.so.5.9.0.p/qmi-enums-dms.c.o
building '/nix/store/ianq58bff18xbr40b87j1g12qx19dymg-python3.10-pygobject-3.44.1.drv'...
[59/301] Compiling C++ object src/libharfbuzz.so.0.60730.0.p/hb-static.cc.o
[221/321] Compiling C object libsoup/libsoup-3.0-static.a.p/soup-message-queue-item.c.o
[222/321] Compiling C object libsoup/libsoup-3.0-static.a.p/soup-misc.c.o
[223/321] Compiling C object libsoup/libsoup-3.0-static.a.p/soup-socket-properties.c.o
[224/321] Compiling C object libsoup/libsoup-3.0-static.a.p/soup-session-feature.c.o
[225/321] Compiling C object libsoup/libsoup-3.0-static.a.p/soup-multipart-input-stream.c.o
[226/321] Compiling C object libsoup/libsoup-3.0-static.a.p/content-decoder_soup-brotli-decompressor.c.o
[227/321] Compiling C object libsoup/libsoup-3.0-static.a.p/soup-uri-utils.c.o
[228/321] Compiling C object libsoup/libsoup-3.0-static.a.p/soup-version.c.o
[229/321] Compiling C object libsoup/libsoup-3.0-static.a.p/soup-status.c.o
[ 59%] Building C object src/CMakeFiles/libcmark.dir/houdini_href_e.c.o
[ 62%] Building C object src/CMakeFiles/libcmark.dir/houdini_html_e.c.o
[ 66%] Building C object src/CMakeFiles/libcmark.dir/houdini_html_u.c.o
[ 70%] Building C object src/CMakeFiles/libcmark.dir/cmark_ctype.c.o
[61/154] Compiling C object src/libqmi-glib/libqmi-glib.so.5.9.0.p/qmi-endpoint-qmux.c.o
[62/154] Compiling C object src/libqmi-glib/libqmi-glib.so.5.9.0.p/qmi-enums-nas.c.o
[63/154] Compiling C object src/libqmi-glib/libqmi-glib.so.5.9.0.p/qmi-enums-wds.c.o
[64/154] Compiling C object src/libqmi-glib/libqmi-glib.so.5.9.0.p/qmi-helpers.c.o
libwacom:all / pytest time out (After 30 seconds)                        29/30s
7/7 libwacom:all / pytest                               TIMEOUT        30.31s   killed by signal 15 SIGTERM
>>> MESON_SOURCE_ROOT=/build/source MALLOC_PERTURB_=53 /nix/store/hzv8xjxk35i72jrljvjhl9y5i00vnsqn-python3.10-pytest-7.2.1/bin/pytest /build/source
 ✀  
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.2.1, pluggy-1.0.0
rootdir: /build/source
collected 1869 items

../test/test_data_files.py ............................................. [  2%]
........................................................................ [  6%]
........................................................................ [ 10%]
........................................................................ [ 13%]
........................................................................ [ 17%]
........................................................................ [ 21%]
........................................................................ [ 25%]
........................................................................ [ 29%]
........................................................................ [ 33%]
........................................................................ [ 37%]
........................................................................ [ 40%]
........................................................................ [ 44%]
........................................................................ [ 48%]
........................................................................ [ 52%]
........................................................................ [ 56%]
........................................................................ [ 60%]
........................................................................ [ 64%]
.........................................



7/7 libwacom:all / pytest                        TIMEOUT        30.31s   killed by signal 15 SIGTERM

7/7 libwacom:all / pytest                        TIMEOUT        30.31s   killed by signal 15 SIGTERM

Ok:                 5   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            1   
Timeout:            1   

Full log written to /build/source/build/meson-logs/testlog.txt
FAILED: meson-internal__test 
/nix/store/2fyi668mbivk9syigxh40irfdf65lsnv-meson-1.1.1/bin/meson test --no-rebuild --print-errorlogs
ninja: build stopped: subcommand failed.
error: builder for '/nix/store/9nvjqzwf0fa1l41maisddi6fxsd82ddd-libwacom-2.7.0.drv' failed with exit code 1;
       last 10 log lines:
       > Expected Fail:      0
       > Fail:               0
       > Unexpected Pass:    0
       > Skipped:            1
       > Timeout:            1
       >
       > Full log written to /build/source/build/meson-logs/testlog.txt
       > FAILED: meson-internal__test
       > /nix/store/2fyi668mbivk9syigxh40irfdf65lsnv-meson-1.1.1/bin/meson test --no-rebuild --print-errorlogs
       > ninja: build stopped: subcommand failed.
       For full logs, run 'nix log /nix/store/9nvjqzwf0fa1l41maisddi6fxsd82ddd-libwacom-2.7.0.drv'.
error: 1 dependencies of derivation '/nix/store/gjvh399591iiw6sv28qq8yh9hassq6nz-libinput-1.23.0.drv' failed to build
building '/nix/store/mw4z7fhasq37jxas8lg5mch10jcpk2ma-libaom-3.6.1.drv'...
error: 1 dependencies of derivation '/nix/store/awcgnb0ng8slb80m0crrpz9lp55hzb2l-qtbase-5.15.9.drv' failed to build
error: 1 dependencies of derivation '/nix/store/mh0jk00cnvdz7rx3xzlfmlzvd7arjw27-python3.10-PyQt5-5.15.9.drv' failed to build
error: 1 dependencies of derivation '/nix/store/wqdwchnkfv7plky7rkn29rz0z044q9bw-ffado-2.4.7.drv' failed to build
error (ignored): error: cannot unlink '/tmp/nix-build-libaom-3.6.1.drv-0/source/aom_dsp/x86': Directory not empty
error: 1 dependencies of derivation '/nix/store/c04rjq5jkg6z7r6va2cxpi951xzxsrdr-pipewire-0.3.72.drv' failed to build
```

any ideas? Might also be my laptop being to slow (i7-8650U and 16gig ram)?

**Pull request merged**
