### PR TITLE
nixos/caddy: add tests

### PR DESCRIPTION
**Pull request by sugar700**
###### Motivation for this change

I wanted to make sure Caddy works before working on moving my server infrastructure to NixOS. The test is based on nginx's test.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @rushmorem @fpletz @zimbatm

### CODE REVIEW

**Comment by zimbatm** [comment]
@GrahamcOfBorg test caddy

**Comment by zimbatm** [comment]
```
undefined variable 'xfix' at /var/lib/gc-of-borg/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/globin-server/nixos/tests/caddy.nix:4:21
```

**Comment by xfix** [comment]
Hm, I guess I forgot to add myself to the maintainers list. I will fix this commit soon.

**Comment by xfix** [comment]
@GrahamcOfBorg test caddy

**Comment by xfix** [comment]
@GrahamcOfBorg test caddy

**Comment by xfix** [comment]
I guess I cannot run the test. Anyway highlighting maintainers again after a change.

cc @rushmorem @fpletz @zimbatm

**Comment by zimbatm** [comment]
@GrahamcOfBorg test caddy

**Comment by zimbatm** [comment]
thanks!

**Pull request merged**
