### PR TITLE
openvswitch: remove LTS variant

### PR DESCRIPTION
**Pull request by kmcopper**
### Motivation for this change 

old unused package.

### CODE REVIEW

**Comment by kmcopper** [comment]
If this can also be applied to 20.09 that would be great.

Thanks!

**Review by rnhmjoj — CHANGES_REQUESTED** [review]
Can you add an alias to `pkgs/top-level/aliases.nix` that says something like
```
openvswitch-lts = throw "openvswitch-tls has been removed from nixpkgs, as it was unmaintained."; # added 2021-08-15
```

**Comment by AdrianKoshka** [comment]
What's the state of this PR? I was updating the openvswitch package, and was going to update the LTS variant as well, so I want to know whether I should or not.

**Comment by SuperSandro2000** [comment]
> What's the state of this PR?

looks pretty stale.

> I was updating the openvswitch package, and was going to update the LTS variant as well, so I want to know whether I should or not.

If you want to. You can also drop it.

**Comment by ajs124** [comment]
This has a bunch of conflicts now and racoon was dropped in #156787

**Pull request closed without merging**
