### PR TITLE
guile-1.8: Fix and clean up `libtool` propagation fixes

### LINKED ISSUE #37548: lilypond: broken build
## Issue description

https://hydra.nixos.org/build/71492931

I attempted to bisect, but so many of the possible commits would have spent hours building that I wasn't able to narrow it down.

### PR DESCRIPTION
**Pull request by mdorman**
###### Motivation for this change

Fixes #37548

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build lilypond

**Comment by 7c6f434c** [comment]
Darwin failure: `poppler` fails on Darwin because `nullptr` is not defined (doesn't matter for this PR)

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build lilypong guile_2_2 guile_2_0 guile_1_8

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build lilypond

**Review by Ericson2314 — APPROVED** [review]

**Comment by Ericson2314** [comment]
OK think I got this into a state where I like it. Hopefully OfBorg agrees.

@vcunat we should cherry-pick this.

**Comment by 7c6f434c** [comment]
@GrahamcOfBorg build lilypond guile_2_2 guile_2_0 guile_1_8

**Comment by Ericson2314** [comment]
Thanks @7c6f434c

**Comment by 7c6f434c** [comment]
Erm. One of Guile versions is a GTK dependency which gives us a large rebuild…

**Comment by 7c6f434c** [comment]
I think it got worse than the first version…

**Comment by mdorman** [comment]
@Ericson2314 Perhaps at this point it would make more sense to merge the simple fix that works?

**Comment by 7c6f434c** [comment]
@Ericson2314 I support the plan that @mdorman force-pushes whatever allows `lilypond guile guile_1_8 guile_2_2 guile_2_0` builds to succeed and I merge it.

**Comment by teto** [comment]
Agreed, may packets include asciidoctor which breaks lots of builds, making  nox-review unusable.

**Comment by Ericson2314** [comment]
Sorry for that; I'm fine with that too. Since nobody did then I force-pushed a fix so the glob expands properly, but feel-free to force-push again back the way it was.

**Comment by Ericson2314** [comment]
@GrahamcOfBorg build lilypond guile_2_2 guile_2_0 guile_1_8

**Comment by 7c6f434c** [comment]
@Ericson2314 and now without syntax errors, please? I would prefer a fix that wouldn't trigger an almost-stdenv rebuild to get merged to master, though (and the more comprehensive fix will go to staging, I guess)

**Comment by Ericson2314** [comment]
Oh I didn't see the mass rebuild either.

**Comment by Ericson2314** [comment]
@GrahamcOfBorg build lilypond guile_1_8

**Comment by 7c6f434c** [comment]
Now that the circle of life is complete, I can merge what I didn't merge fast enough the first time…

**Comment by vcunat** [comment]
@Ericson2314: I don't immediately see what to do about this and 18.03.  Lilypond does build, and the guile expression has seen more changes since the fork than this PR.

**Comment by Ericson2314** [comment]
Oh I thought this was the one new thing post fork. No worries then.

**Pull request merged**
