### PR TITLE
imagemagick: 7.1.1-19 -> 7.1.1-21

### PR DESCRIPTION
**Pull request by dotlambda**
## Description of changes
Diff: https://github.com/ImageMagick/ImageMagick/compare/7.1.1-19...7.1.1-21

Changelog: https://github.com/ImageMagick/Website/blob/main/ChangeLog.md

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by stigtsp — APPROVED** [review]
LGTM

**Comment by stigtsp** [comment]
There seems to be an upstream issue with linux-i686:
- https://github.com/ImageMagick/ImageMagick/issues/6820

Maybe these commits will fix the problem:
- https://github.com/ImageMagick/ImageMagick/commit/3a7b915d9a810ce742987b37c935f6ae8b36df10
- https://github.com/ImageMagick/ImageMagick/commit/8f3c56fabc619c1672865257e5aafe33cbfaaf3e

See https://hydra.nixos.org/build/239665773/nixlog/1/tail

**Comment by misuzu** [comment]
Same issue on armv7l-linux: https://hydra.armv7l.xyz/build/20428/nixlog/74

```
<.................................>
convert -size 136x128 canvas:none -compose copy -gravity center "png/128/emoji_u0023.png" -composite "PNG32:build/emoji/emoji_u0023.png"
convert -size 136x128 canvas:none -compose copy -gravity center "png/128/emoji_u0023_20e3.png" -composite "PNG32:build/emoji/emoji_u0023_20e3.png"
convert -size 136x128 canvas:none -compose copy -gravity center "png/128/emoji_u002a.png" -composite "PNG32:build/emoji/emoji_u002a.png"
convert: time limit exceeded `none' @ fatal/cache.c/GetImagePixelCache/1702.
convert: time limit exceeded `none' @ fatal/cache.c/GetImagePixelCache/1702.
convert: time limit exceeded `none' @ fatal/cache.c/GetImagePixelCache/1702.
make: *** [Makefile:164: build/emoji/emoji_u0023.png] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:164: build/emoji/emoji_u0023_20e3.png] Error 1
make: *** [Makefile:164: build/emoji/emoji_u002a.png] Error 1
```

**Comment by vcunat** [comment]
Sure, the description seemed as universal 32-bit issue.

**Pull request merged**
