### PR TITLE
qc: 0.4.0 -> 0.5.0

### PR DESCRIPTION
**Pull request by pbek**
Semi-automatic update generated by [nixpkgs-update](https://github.com/ryantm/nixpkgs-update) tools. This update was made based on information from repology.org.

meta.description for qc is: QOwnNotes command-line snippet manager

meta.homepage for qc is: https://github.com/qownnotes/qc

###### Updates performed
- Golang update

###### To inspect upstream changes

- [Release on GitHub](https://github.com/qownnotes/qc/releases/tag/v0.5.0)

- [Compare changes on GitHub](https://github.com/qownnotes/qc/compare/v0.4.0...v0.5.0)

###### Impact

<details>
<summary>
<b>Checks done</b> (click to expand)
</summary>

---

- built on NixOS
- The tests defined in `passthru.tests`, if any, passed
- found 0.5.0 with grep in /nix/store/7hb2qsr717p39wkcra2pin2c3kc247r2-qc-0.5.0
- found 0.5.0 in filename of file in /nix/store/7hb2qsr717p39wkcra2pin2c3kc247r2-qc-0.5.0

---

</details>
<details>
<summary>
<b>Rebuild report</b> (if merged into master) (click to expand)
</summary>

```
1 total rebuild path(s)

1 package rebuild(s)

First fifty rebuilds by attrpath
qc
```

</details>

<details>
<summary>
<b>Instructions to test this update</b> (click to expand)
</summary>

---

Build yourself:
```
nix-build -A qc https://github.com/pbek/nixpkgs/archive/89305b837eef0974ec52e9d5cf7a22f773623d03.tar.gz
```

After you've downloaded or built it, look at the files and if there are any, run the binaries:
```
ls -la /nix/store/7hb2qsr717p39wkcra2pin2c3kc247r2-qc-0.5.0
ls -la /nix/store/7hb2qsr717p39wkcra2pin2c3kc247r2-qc-0.5.0/bin
```

---

</details>
<br/>

### Pre-merge build results

We have automatically built all packages that will get rebuilt due to
this change.

This gives evidence on whether the upgrade will break dependent packages.
Note sometimes packages show up as _failed to build_ independent of the
change, simply because they are already broken on the target branch.

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>qc</li>
  </ul>
</details>

---

###### Maintainer pings

cc @pbek @totoroot for [testing](https://github.com/ryantm/nixpkgs-update/blob/master/doc/nixpkgs-maintainer-faq.md#r-ryantm-opened-a-pr-for-my-package-what-do-i-do).

### CODE REVIEW

**Review by Janik-Haag — APPROVED** [review]
LGTM; but you might want to add sehll completions for the other one supported:
```
./result/bin/qc completion    

Generate the autocompletion script for qc for the specified shell.
See each sub-command's help for details on how to use the generated script.

Usage:
  qc completion [command]

Available Commands:
  bash        generate the autocompletion script for bash
  fish        generate the autocompletion script for fish
  powershell  generate the autocompletion script for powershell
  zsh         generate the autocompletion script for zsh
```

**Comment by totoroot** [comment]
Result of `nixpkgs-review pr 238773` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>qc</li>
  </ul>
</details>

**Review by totoroot — APPROVED** [review]

**Comment by pbek** [comment]
> LGTM; but you might want to add sehll completions for the other one supported:
> 
> ```
> ./result/bin/qc completion    
> 
> Generate the autocompletion script for qc for the specified shell.
> See each sub-command's help for details on how to use the generated script.
> 
> Usage:
>   qc completion [command]
> 
> Available Commands:
>   bash        generate the autocompletion script for bash
>   fish        generate the autocompletion script for fish
>   powershell  generate the autocompletion script for powershell
>   zsh         generate the autocompletion script for zsh
> ```

@Janik-Haag, thank you for your feedback!
Is that possible to feed the output of a command to `installShellCompletion` during `postInstall`?

Something like: `qc completion fish | installShellCompletion --cmd qc --fish -`?

**Comment by pbek** [comment]
Ah, more like:

https://github.com/NixOS/nixpkgs/blob/eafa1fd10d709fb2e5b85865cb475f1c074c33f8/doc/hooks/installShellFiles.section.md?plain=1#L20-L23

**Comment by pbek** [comment]
Result of `nixpkgs-review pr 238773` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>qc</li>
  </ul>
</details>

**Comment by pbek** [comment]
@totoroot?

**Comment by totoroot** [comment]
@pbek When I build the changes in this PR, the shell completion directories get created in `qc/share/` but the completion files seem to be empty.
@Janik-Haag Can you check whether that is how it's supposed to be? I've never worked on shell completion for nixpkgs

**Comment by pbek** [comment]
Strange, I saw it done in that way too in other places, like:

https://github.com/NixOS/nixpkgs/blob/838e1c1165a10ae034821cd0250719e409c5339f/pkgs/applications/networking/cluster/kubernetes/kubectl.nix#L20-L23

**Comment by totoroot** [comment]
Yeah, when you first wanted to add `qc` to nixpkgs I already tried to add shell completion but couldn't get it to work. Perhaps @Janik-Haag knows more about this.

**Comment by pbek** [comment]
I tried several ways (which wasn't easy, because nix didn't let me always write to temp files), but I always got empty shell completion files...

```nix
  preInstall = ''
    compdir=$(mktemp -d)

    for shell in bash zsh fish; do
      # gives me an nix error
#    $out/bin/qc completions $shell > $compdir/$shell

      # this writes the file
      cat <($out/bin/qc completion $shell) > $compdir/$shell
    done

    installShellCompletion --cmd qc \
      --bash $compdir/bash \
      --zsh $compdir/zsh \
      --fish $compdir/fish
  '';
```

**Comment by pbek** [comment]
Same when I only write a single completion with "installShellCompletion".

**Comment by pbek** [comment]
The only thing that DOES seem to work is writing a file that exists in the repository:

```nix
    installShellCompletion --cmd qc \
      --zsh ./misc/completions/zsh/_qc
```

**Comment by Janik-Haag** [comment]
To be honest I don't know what's causing this, 

I noticed that when building it with the completions nix throws an error:
```
this derivation will be built:
  /nix/store/w1lgavyxdjcpvkhnzfh9m4s2qyzaa03s-qc-0.5.0.drv
building '/nix/store/w1lgavyxdjcpvkhnzfh9m4s2qyzaa03s-qc-0.5.0.drv'...
unpacking sources
unpacking source archive /nix/store/7h1wklygpbki8h7m1zg6hra1j937an6z-source
source root is source
patching sources
configuring
building
Building subPackage ./.
installing
cannot create directory: mkdir /homeless-shelter: permission deniedcannot create directory: mkdir /homeless-shelter: permission deniedcannot create directory: mkdir /homeless-shelter: permission denied@nix { "action": "setPhase", "phase": "fixupPhase" }
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/ppxw54psqbrg6xiascsrv1bkhrwgb757-qc-0.5.0
shrinking /nix/store/ppxw54psqbrg6xiascsrv1bkhrwgb757-qc-0.5.0/bin/qc
checking for references to /build/ in /nix/store/ppxw54psqbrg6xiascsrv1bkhrwgb757-qc-0.5.0...
patching script interpreter paths in /nix/store/ppxw54psqbrg6xiascsrv1bkhrwgb757-qc-0.5.0
stripping (with command strip and flags -S -p) in  /nix/store/ppxw54psqbrg6xiascsrv1bkhrwgb757-qc-0.5.0/bin
/nix/store/ppxw54psqbrg6xiascsrv1bkhrwgb757-qc-0.5.0
```
> cannot create directory: mkdir /homeless-shelter: permission deniedcannot create directory: mkdir /homeless-shelter: permission deniedcannot create directory: mkdir /homeless-shelter: permission denied@nix { "action": "setPhase", "phase": "fixupPhase" }

that doesn't happen when I comment out these lines:
```nix
  postInstall = ''
    installShellCompletion --cmd qc \
      --bash <($out/bin/qc completion bash) \
      --fish <($out/bin/qc completion fish) \
      --zsh <($out/bin/qc completion zsh)
  '';
```

so I'm guessing it's some kind of permission error since running `cat <(./result/bin/qc completion bash)` after the build works as expected and the `<()` syntax generates a file in `/proc/self/fd/*` which it might not be able to write and that would explain the empyt files, I just don't really get why it works in other instances.

**Comment by pbek** [comment]
I'm removing the change from the PR then...

**Comment by Janik-Haag** [comment]
I pushed the solution for the problem which was kindly provided by @figsoda on matrix, works with my local build. The solution was to set this `export HOME=$(mktemp -d)` in the post install phase which fixes this error `cannot create directory: mkdir /homeless-shelter: permission deniedcannot create directory: mkdir /homeless-shelter: permission deniedcannot create directory: mkdir /homeless-shelter: permission denied@nix { "action": "setPhase", "phase": "fixupPhase" }` and now the completions get created correctly. I can merge the PR once you verify that completions work for you know as well and ci runs through.

**Comment by pbek** [comment]
Ah, great to know! I'll test tomorrow. Thank you very much!
Does every similar call need this or just go apps?

**Comment by Janik-Haag** [comment]
As far as I know you usually only need this with stuff like javascript that try's to create a cache in the user home.

**Comment by Janik-Haag** [comment]
@SuperSandro2000 can you please wait with merging next time until the pr author tested the change as discussed in the comment above :confused:

**Comment by SuperSandro2000** [comment]
Oh, sorry but you already tested the change so it should be fine.

**Comment by Janik-Haag** [comment]
I of course already tested the change but humans make mistakes, and since I pushed the change I would have liked some one else to test it as well but meh, probably going to be fine :shrug:

**Comment by pbek** [comment]
Works like a charm! Thanks a lot @Janik-Haag and @figsoda!

@SuperSandro2000, thank you for the merge and all the advice that you have given me in the past!
Since the shell completion was an "extra" anyway, no harm would have been done if it hadn't work! 😉

**Pull request merged**
