### PR TITLE
fileSystems: strip trailing slash of mountPoints

### LINKED ISSUE #78951: Mounting the nix store on /nix/ fails but /nix works
**Describe the bug**

I have a separate  /nix/ ZFS dataset whose mountpoint I declare in my NixOS config.

However when I try to boot that system, it mounts the root dataset, tries to read something out of the nix store (before it's mounted) and fails, prompting me to reboot or ignore.

```Nix
  fileSystems."/nix" = {
    device = "Rpool/R/nix";
    fsType = "zfs";
  };
```

works but

```Nix
  fileSystems."/nix/" = {
    device = "Rpool/R/nix";
    fsType = "zfs";
  };
```
doesn't.

**To Reproduce**
1. Have a separate ZFS dataset for /nix/
2. Try to mount it on /nix and /nix/ respectively
3. Observe that /nix gets mounted before anything is read from the nix store while /nix/ isn't

**Expected behavior**

It should behave the same, no matter the trailing slash.

**Screenshots**

**Additional context**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.98, NixOS, 19.09.1970.6d9a4a615ee (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-19.09.1970.6d9a4a615ee"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by Atemu**
###### Motivation for this change
Fixes #78951

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by aanderse — COMMENTED** [review]
Seems like a simple change that looks fine to me... but I'm going to defer to someone who might know better if there are any implications to this change.

:+1:

**Comment by Mic92** [comment]
What do you think about this solution: https://github.com/NixOS/nixpkgs/pull/95406
This avoids duplicate mountpoints and improves validation.

**Comment by Atemu** [comment]
Hm, I'd prefer if trivial things like these were just corrected automatically.

Preventing duplicates would be a desirable property though.

Would it perhaps be possible to strip the slash earlier, during the merge? I'm not too familiar how these submodules with custom names work and how they're merged unfortunately.

**Comment by Mic92** [comment]
I think there is an `apply` attribute that can be set.

**Comment by Atemu** [comment]
There is indeed and it's a cleaner solution to the problem.

I could not figure out how to make it work with submodule names though, so duplicates are still possible. The purpose of this PR isn't to sanitise bad user configs but rather work around a bug in our handling of essential mountPoints, so that's fine.

**Pull request closed without merging**
