### PR TITLE
virtualbox: use wrapQtAppsHook

### LINKED ISSUE #66200: virtualbox: fails to start, Qt error
**Describe the bug**

Cannot start Virtualbox:

```
août 06 13:41:06 nixpsla virtualbox.desktop[2469]: Qt WARNING: Could not find the Qt platform plugin "xcb" in ""
août 06 13:41:06 nixpsla virtualbox.desktop[2469]: Qt FATAL: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

**To Reproduce**
1. Open virtualbox

**Expected behavior**

Virtualbox should start

**Additional context**

I saw this mentioned here: https://github.com/NixOS/nixpkgs/issues/65448#issuecomment-515971498

But the related fixes have been pushed to master a week ago, I think?

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.1.21, NixOS, 19.09pre187507.525eaf407d4 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre187507.525eaf407d4, home-manager, nixos-hardware"`
 - channels(stanislas): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### PR DESCRIPTION
**Pull request by worldofpeace**
###### Motivation for this change
Fixes #66200

See: #65399

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by worldofpeace** [comment]
cc @angristan testing would be appreciated :+1:

**Review by jonringer — APPROVED** [review]
`nix-review` mostly passes on NixOS (I believe the packages are broken on master)
diff LGTM

```
[18 built (2 failed), 72 copied (2812.6 MiB), 1333.0 MiB DL]
error: build of '/nix/store/430zfb4rdb9qhlbhgbbhgsj4f5rcisk5-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/66222
2 package are marked as broken and were skipped:
linuxPackages_hardkernel_4_14.virtualbox linuxPackages_hardkernel_latest.virtualbox

2 package failed to build:
linuxPackages-libre.virtualbox linuxPackages_latest-libre.virtualbox

16 package were build:
linuxPackages.virtualbox linuxPackages_4_14.virtualbox linuxPackages_4_4.virtualbox linuxPackages_4_9.virtualbox linuxPackages_5_1.virtualbox linuxPackages_5_2.virtualbox linuxPackages_hardened.virtualbox linuxPackages_latest_hardened.virtualbox linuxPackages_latest_xen_dom0.virtualbox linuxPackages_testing_bcachefs.virtualbox linuxPackages_testing_hardened.virtualbox linuxPackages_xen_dom0.virtualbox virtualbox virtualboxHardened virtualboxHeadless virtualboxWithExtpack
```

**Review by angristan — APPROVED** [review]
Same results as @jonringer! `Virtualbox` launches correctly now.

**Comment by worldofpeace** [comment]
@angristan  How about `rdesktop-vrdp`? It's conditioned with `!headless` so I don't know if it uses qt.

**Comment by angristan** [comment]
I will try and let you know!

**Comment by angristan** [comment]
`rdesktop-vrdp` :heavy_check_mark:

**Comment by worldofpeace** [comment]
Thanks @angristan

**Pull request merged**
