### PR TITLE
haskellPackages.memfd: mark supported on linux only

### PR DESCRIPTION
**Pull request by viraptor**
###### Description of changes

memfd is linux-specific.

ZHF: https://github.com/NixOS/nixpkgs/issues/230712

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by viraptor** [comment]
I assume I need to regenerate the list for this change, but I get:
```
Running hackage2nix to regenerate pkgs/development/haskell-modules/hackage-packages.nix …
hackage2nix: constraint doctest >=0.18 && <0.19 cannot be resolved in Hackage
This could be due the package being missing in the hackage directory
or the file system not being case sensitive.
```
Could someone more familiar with the system double-check, plase?

**Review by sternenseemann — CHANGES_REQUESTED** [review]
If it is linux-specific, it's `supported-platforms` should be `platforms.linux` instead.

I am happy to regenerate the package set for you—I assume it is no longer possible to do this due to the clash between DocTest and doctest on macOS' case insensitive file system.

**Comment by viraptor** [comment]
Done. With the long list in the file, I didn't even spot that `supported` was a category available :)

**Comment by sternenseemann** [comment]
Done in 8607b80c85600c2ad439a8a198ff812b15d01c0c.

**Pull request closed without merging**
