### PR TITLE
[24.05] Revert "nixos/steam: add option fontPackages"

### PR DESCRIPTION
**Pull request by eclairevoyant**
## Description of changes

This reverts commit 7f86c8842a5d4686b86bded1c29e2ef22304eab3, which was a breaking change (see https://github.com/NixOS/nixpkgs/pull/312268#issuecomment-2133641945) and therefore not eligible for backporting.

Original PR #312268
Original backport #314970

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Cryolitia** [comment]
No need to revert, fixes coming soon, I'm working on it.

**Comment by Cryolitia** [comment]
https://github.com/NixOS/nixpkgs/pull/315149

**Comment by eclairevoyant** [comment]
> No need to revert, fixes coming soon, I'm working on it.

You're welcome to fix it on unstable, but it still needs to be reverted on 24.05. A breaking change is still a breaking change; we should not have such risky changes on a stable branch especially right before a release.

**Review by wegank — APPROVED** [review]

**Comment by Cryolitia** [comment]
It was supposed to be just a fix without breaking anything.

But fine...depends on you, maintainer.

**Comment by eclairevoyant** [comment]
The concern I had was that we aren't still confident on the type even on the new PR. And stable really should be stable.

If someone on 24.05 wants to put `config.fonts.packages` in the `extraPackages` option, nothing stops them, as I left that alone.

**Comment by Cryolitia** [comment]
clear enough, I agree

**Pull request merged**
