### PR TITLE
bioconductor: 3.4 -> 3.6

### PR DESCRIPTION
**Pull request by jbedo**
###### Motivation for this change

Bioconductor was quite out of date because the old expression fetched bioconductor with the same version as R. This is not appropriate as bioconductor versions are not synchronised with R versions. I have updated the expression to explicitly fetch the latest bioconductor (3.6).

I have also updated the R packages as many of the bioconductor packages require the latest CRAN versions.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
@GrahamcOfBorg eval

looks like the eval issue was handled.

**Comment by peti** [comment]
Test builds are running at https://hydra.nixos.org/jobset/nixpkgs/r-updates.

**Comment by peti** [comment]
Hmm, after applying this patch, https://hydra.nixos.org/jobset/nixpkgs/r-updates no longer evaluates and performs no builds. Something isn't right.

**Review by peti — CHANGES_REQUESTED** [review]
Please make sure the package set evaluates after your changes: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/r-modules/README.md#testing-if-the-nix-expression-could-be-evaluated

**Comment by jbedo** [comment]
Apologies for neglecting the last testing step. It now passes for me.

**Comment by peti** [comment]
OK, the new version looks good! It's compiling at https://hydra.nixos.org/jobset/nixpkgs/r-updates right now.

**Comment by peti** [comment]
The number of broken builds increased from 500 to 1400. A good chunk of those failures seem to be caused by this issue: https://hydra.nixos.org/build/69692858. Apparently, `GenomicRanges_1.30.1.tar.gz` is not available for download?

**Comment by jbedo** [comment]
Looks like GenomicRanges had a version bump since I made the original pull request. Turns out old packages are not available at the url we use for bioc packages, which makes bioc quite fragile.  I've addressed this by adding the archive url to the list of urls searched for packages, which should help prevent breakage whenever a bioc package is update. I've also re-updated all the packages that have changed since my original pull request.

**Comment by peti** [comment]
I'm restarting the test builds with the new version ...

**Review by peti — APPROVED** [review]

**Pull request merged**
