### PR TITLE
mdbook: 0.1.8 -> 0.2.0

### PR DESCRIPTION
**Pull request by dywedir**
https://github.com/rust-lang-nursery/mdBook/releases/tag/v0.2.0

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc @havvy

### CODE REVIEW

**Comment by Havvy** [comment]
You're gonna want to keep at least 0.1.8 until we can get all the links updated in the Rust books.

**Comment by Mic92** [comment]
Is there a way to find out, when this happen (like an issue?).

**Comment by Havvy** [comment]
I've a tracking issue at https://github.com/rust-docs/team/issues/23

**Comment by cw789** [comment]
v0.2.3 is the latest now ...

It's not good for the nix pkgs ecosystem, that updates are hold back by such circumstances.
Should be solved by pinning nix pkgs or some other solutions ...

**Comment by tazjin** [comment]
I opened #65890 to move this to 0.3.1 (which is the latest version).

Agree with @cw789 that external projects depending on an old version via Nix should look to pin that version separately.

**Pull request closed without merging**
