### PR TITLE
homepage-dashboard: 0.6.21 -> 0.6.23

### PR DESCRIPTION
**Pull request by jnsgruk**
###### Description of changes

Update to latest version and drop explicit fetch of a patch that is now upstream. It also has a driveby fix of an incorrect attribute in `passthru.tests` and fixes the package build for darwin.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by drupol — APPROVED** [review]

**Review by RaitoBezarius — APPROVED** [review]

**Comment by drupol** [comment]
It seems that there's an issue with `x86_64-darwin`... is it expected?

**Comment by jnsgruk** [comment]
Hmm, I've not tested on Darwin. I don't have access to such a machine. I thought I'd restricted this package to Linux only

**Comment by drupol** [comment]
We can try to ping @NixOS/darwin-maintainers and see what they say ?

**Comment by emilazy** [comment]
Builds successfully on `x86_64-darwin`; did not try running, untested on `aarch64-darwin`:

```diff
diff --git a/pkgs/servers/homepage-dashboard/default.nix b/pkgs/servers/homepage-dashboard/default.nix
index d2e4a07d331..4a74ff170fb 100644
--- a/pkgs/servers/homepage-dashboard/default.nix
+++ b/pkgs/servers/homepage-dashboard/default.nix
@@ -2,6 +2,9 @@
 , fetchFromGitHub
 , nodePackages
 , python3
+, stdenv
+, cctools
+, IOKit
 , lib
 , fetchpatch
 , makeBinaryWrapper
@@ -31,8 +34,14 @@ buildNpmPackage rec {
     patchShebangs .next/standalone/server.js
   '';
 
+  nativeBuildInputs = lib.optionals stdenv.isDarwin [
+    cctools
+  ];
+
   buildInputs = [
     nodePackages.node-gyp-build
+  ] ++ lib.optionals stdenv.isDarwin [
+    IOKit
   ];
 
   env.PYTHON = "${python3}/bin/python";
diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
index e3e6f6a5660..b3b3deddcfd 100644
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -5398,7 +5398,10 @@ with pkgs;
 
   home-manager = callPackage ../tools/package-management/home-manager { };
 
-  homepage-dashboard = callPackage ../servers/homepage-dashboard { };
+  homepage-dashboard = callPackage ../servers/homepage-dashboard {
+    inherit (darwin) cctools;
+    inherit (darwin.apple_sdk.frameworks) IOKit;
+  };
 
   hostsblock = callPackage ../tools/misc/hostsblock { };
 
```

**Comment by drupol** [comment]
Thank you so much !

**Comment by n8henrie** [comment]
With the patch from @emilazy it also builds on aarch64-darwin.

Tried running but when I open up localhost:3000 I get `Error: EACCES: permission denied, mkdir '/var/lib/homepage-dashboard'`.

**Comment by emilazy** [comment]
Probably just needs the directory configuring or creating externally? I don't know how to use the program but I think building successfully is a good start at least :)

**Comment by jnsgruk** [comment]
Great! Yeh the default dir can be overridden with `HOMEPAGE_CONFIG_DIR=. ./result/bin/homepage`.

I'm afk most of today but will apply that patch when I get a minute.

Thank you all! 🤩

**Comment by jnsgruk** [comment]
Hey @emilazy :) I applied your patch and indeed the package now builds, though for some reason the nixos tests fail on x86_64-darwin: [logs here](https://logs.ofborg.org/?attempt_id=01b47dbd-cf01-4199-89bc-9e3d69abaf08&key=nixos%2Fnixpkgs.244454).

Any experience with this sort of error? Thank you!

**Comment by drupol** [comment]
@jnsgruk It would be nice to investigate the failures on Darwin.

@NixOS/darwin-maintainers Do you have some resources/time to check on this one?

**Comment by jnsgruk** [comment]
> @jnsgruk It would be nice to investigate the failures on Darwin.

afaict they're now fixed :) ofborg still shows the historic runs from before I pushed the fixes, so they show as failed, but you should see successful runs now for darwin too :)

**Comment by RaitoBezarius** [comment]
> @jnsgruk It would be nice to investigate the failures on Darwin.
> 
> @NixOS/darwin-maintainers Do you have some resources/time to check on this one?

Merging because the OfBorg CI is completely broken for Darwin and Cole is away. Unfortunately, we don't have the means to support those CI checks for the time being.

**Comment by drupol** [comment]
fair enough!

**Pull request merged**
