### PR TITLE
Kernels 2021-07-25

### PR DESCRIPTION
**Pull request by TredwellGit**
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ma27** [comment]
Now that 5.12 is EOL, we should also remove it.

**Comment by TredwellGit** [comment]
I was going to do that it another pull request, but don't have time right now.

**Review by ymatsiuk — APPROVED** [review]

**Review by mohe2015 — APPROVED** [review]
`Linux nixos 5.13.5 #1-NixOS SMP Sun Jul 25 12:37:37 UTC 2021 x86_64 GNU/Linux`

**Comment by fabianhjr** [comment]
Diff LGTM, building 5.13.5

**Review by fabianhjr — APPROVED** [review]
Running 5.13.5 without issues

**Comment by alyssais** [comment]
@OfBorg test simple

**Pull request merged**
