### PR TITLE
pythonPackages.sympy: add antlr4 dep

### PR DESCRIPTION
**Pull request by matthuszagh**
antlr is necessary for sympy to be able to parse latex input (see the bottom of [this page](https://docs.sympy.org/latest/modules/parsing.html?highlight=latex)).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

**Comment by FRidh** [comment]
Is it a mandatory dependency (that is, it is in `install_requires`), or an optional dependency?

**Comment by matthuszagh** [comment]
Fair point, only necessary if you need latex parsing (not sure if it's used anywhere else). Shall I change it to an option defaulting to false?

**Comment by matthuszagh** [comment]
Happy to close this if you don't feel it's necessary since it's an optional dependency.

**Comment by jonringer** [comment]
unfortunately there's a mismatch in abstractions between nix and python packages, in which this scenario doesn't have a great solution.

The most proper course of action would be include the related antlr4 package in the environment in which you need it.

**Comment by matthuszagh** [comment]
Sounds good, thanks for the response @jonringer. Closing this.

**Pull request closed without merging**
