### PR TITLE
xkeyboard_config: 2.33 -> 2.39

### PR DESCRIPTION
**Pull request by kevinboulain**
###### Description of changes

The [release notes](https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/blob/master/NEWS) aren't really helpful and given it's a new build system, I did a [diff](https://gist.github.com/ether42/9862653105520fee4ec9c054ad7b83af) because I'm not too familiar with this package (ignoring `etc` and `lib` that are just symlinked in `overrides.nix`):
 - Javanese hasn't been removed, just [moved](https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/commit/3fa0dfde2637d9a0032c1395ff6a965d546ff08c).
 - A lot of updates, new translations and layouts (nearly two years worth of updates).

Explanation of changes:
 - `-Dxorg-rules-symlinks=true` replaces `--with-xkb-rules-symlink=xorg`, without that `share/X11/xkb/rules/xorg*` wouldn't be generated.
 - There's a new Perl script hence the dependency on Perl.
 - gettext is necessary to generate the translations.
 - I edited `overrides.nix` and did not special case `xkeyboardconfig` in `generate-expr-from-tarballs.pl` as that seems to be the way to go (I believe we could drop pkg-config in `default.nix`, but again, not sure we want to special case).

###### Things done

Apparently, there are more than 5k packages impacted (at least that's what `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"` tells me) so I followed https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging and couldn't really rebuild everything locally. I believe the CI will?

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by apfelkuchen6** [comment]
2.39 is out now.

The diff looks good to me and the tests in `nixosTests.keymap` build with it.

**Comment by ether42** [comment]
Pushed another commit for 2.39 and rebased. Whom should I notify (there's no maintainer)?

**Review by apfelkuchen6 — APPROVED** [review]

**Comment by nagy** [comment]
A good chunk of this has landed with https://github.com/NixOS/nixpkgs/pull/241220 . Can you rebase and see what is still missing? xkeyboard_config is currently broken for me, at least with a custom keyboard layout.

**Comment by ether42** [comment]
They appear to be equivalent, let's close this one.

**Pull request closed without merging**
