### PR TITLE
[ghc] fix dylib load command limits

### PR DESCRIPTION
**Pull request by angerman**
###### Motivation for this change

See https://phabricator.haskell.org/D4714 for the full details.
This will be part of ghc 8.6.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by angerman** [comment]
cc @Ericson2314 @matthewbauer 

We can probably just drop the linker hack with this, and reenable #37750 (e.g. revert 970f2b5063ba59aed2583a9741e79658a92d7656) as well.

I'm positive the patch is good for 8.0, and I think for 8.2 as well, for 8.4 we might need to drop the OSiOS. Also 8.4 has logic for `-dead_strip`, so we could potentially drop that line as well.

In general there is an issue though with using `-dead_strip` when using the LLVM backend. Should
we conditionalize it on the LLVM backend, or just drop OSiOS and `-dead_strip` outright?

**Comment by angerman** [comment]
Alright, after reconsidering what I just wrote, I did drop `OSiOS` and `-drop_dead`. The reasoning is the following, for iOS, you are very unlikely to use GHC prior to 8.4 with any substantial success anyway. Also the whole dynamic issue doesn't come up with stage1 compilers usually as they are built using the internal static linker and I don't think they even built dynamic libs by default.

Also `-dead_strip` can be bolted on as we used to do prior to the linker hack, so we might not need to force it in GHC.

**Comment by peti** [comment]
Merged to `haskell-updates` for testing in 0524d6b4020f2c19b83bbaa63bd1c88599f6d861. I'll merge to `master` ASAP.

**Review by peti — APPROVED** [review]
Just waiting for test builds ...

**Comment by angerman** [comment]
@Ericson2314 I guess we could try to fetchpatch it, not sure if necessary though?

**Comment by peti** [comment]
@angerman, if we can `fetchpatch` the file, then yes, please do that rather than checking the file into Nixpkgs.

**Pull request closed without merging**
