### PR TITLE
python3Packages.snitun: 0.21.0 -> 0.27.0

### PR DESCRIPTION
**Pull request by fabaff**
###### Motivation for this change
Update to latest upstream release 0.27.0

Change log: https://github.com/NabuCasa/snitun/releases/tag/0.27.0

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 126279` at a4e9f9f3 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/3b52063fde6a068fbee0aec4d9a353b4">home-assistant</a></li>
    <li><a href="https://gist.github.com/1aba3c332b4b6784ac3e43b81e77bdbb">python38Packages.hass-nabucasa</a></li>
    <li><a href="https://gist.github.com/aff775b9122ee8121deb49fe40f7cbb9">python39Packages.hass-nabucasa</a></li>
  </ul>
</details>
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python38Packages.snitun</li>
    <li>python39Packages.snitun</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: unused-argument

Unused argument: `python`.
Near pkgs/development/python-modules/snitun/default.nix:1:36:
```
  |
1 | { lib, stdenv, buildPythonPackage, python, fetchFromGitHub
  |                                    ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl3` is a deprecated license, please check if project uses `gpl3Plus` or `gpl3Only` and change `meta.license` accordingly.

Near pkgs/development/python-modules/snitun/default.nix:32:5:
```
   |
32 |     license = licenses.gpl3;
   |     ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 126279` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>home-assistant</li>
    <li>python38Packages.hass-nabucasa</li>
    <li>python38Packages.snitun</li>
    <li>python39Packages.hass-nabucasa</li>
    <li>python39Packages.snitun</li>
  </ul>
</details>

**Review by Scriptkiddi — APPROVED** [review]
lgtm

**Comment by risicle** [comment]
Many tests `snitun` tests fail for me on macos 10.15. Judging from https://github.com/NabuCasa/snitun/issues/61 it doesn't look like anyone's ever really tested this package on macos and it's not known whether it works. Perhaps we should disable it?

**Comment by fabaff** [comment]
> Perhaps we should disable it?

For macos I depend on Sandro and Martin. `hass-nabucasa` is the only module that I know and that is depending `snitun`. The issue would most likely be that if `hass-nabucasa` is disabled on Darwin then we no longer have Home Assistant for Darwin.

**Comment by mweinelt** [comment]
We disabled home-assistant on darwin, please just do the same with snitun.

**Comment by fabaff** [comment]
> We disabled home-assistant on darwin, please just do the same with snitun.

Ok

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 126279` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
5 packages built:
</summary>
<ul>
<li>home-assistant</li>
<li>python38Packages.hass-nabucasa</li>
<li>python38Packages.snitun</li>
<li>python39Packages.hass-nabucasa</li>
<li>python39Packages.snitun</li>
</ul>
</details>

**Comment by Randyblo7** [comment]
J

**Review by Randyblo7 — APPROVED** [review]
Nice

**Pull request merged**
