### PR TITLE
openjdk: bootstrap headless variant with headless openjdk

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Description of changes
This makes bootstrapping work when environment.noXlibs is set to true

###### Things done

- Built on platform(s)
  - [x] x86_64-linux ``openjdk-headless-19`` with nox enabled
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by roberth — COMMENTED** [review]
I think the bootstrap should be headless regardless of whether the end result is headless.
That way we may need only half the number of bootstrap jdks.

**Comment by SuperSandro2000** [comment]
Didn't test that yet but that would also be a an option.

Maybe someone more familiar with java could answer if that would work.

**Comment by jerith666** [comment]
I don't have any inside knowledge, but I would be pretty surprised if bootstrapping required anything but a headless JDK, regardless of whether the JDK being built is headless or not.  Definitely worth a try.

**Review by AndersonTorres — APPROVED** [review]
Nihil obstat.

**Comment by winterqt** [comment]
> Nihil obstat.

(Latin for "nothing hinders" or "nothing stands in the way")

**Comment by roberth** [comment]
@ofborg build openjdk              openjdk11-bootstrap  openjdk16-bootstrap  openjdk17-bootstrap  openjdk19            openjdk8             openjdk8_headless openjdk11            openjdk11_headless   openjdk17            openjdk17_headless   openjdk19_headless   openjdk8-bootstrap   openjdk_headless

**Comment by SuperSandro2000** [comment]
Can we merge this before the next conflict is created?

**Comment by AndersonTorres** [comment]
> Can we merge this before the next conflict is created?

_Thy will be done_

**Comment by Mic92** [comment]
This breaks evaluation in nix-index-database... https://github.com/Mic92/nix-index-database/issues/56
Where is gtkSupport defined?

```
error: anonymous function at /home/joerg/git/nixpkgs/pkgs/development/compilers/openjdk/bootstrap.nix:1:1 called with unexpected argument 'gtkSupport'

       at /home/joerg/git/nixpkgs/lib/customisation.nix:80:16:

           79|     let
           80|       result = f origArgs;
             |                ^
           81|
(use '--show-trace' to show detailed location information)

noglob nix shell --inputs-from .# nixpkgs#nix-index -c nix-index --db    2>&1  12.91s user 2.64s system 73% cpu 21.142 total
```

**Comment by Mic92** [comment]
see https://github.com/NixOS/nixpkgs/pull/232259

**Pull request merged**
