### PR TITLE
python3Packages.irc: fix build

### PR DESCRIPTION
**Pull request by wkral**
###### Motivation for this change
ZHF: #97479

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wkral** [comment]
Result of `nixpkgs-review pr 98232` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>errbot</li>
    <li>python37Packages.irc</li>
    <li>python38Packages.irc</li>
  </ul>
</details>

**Comment by risicle** [comment]
You wouldn't mind adding a `pythonImportsCheck = [ "irc" ]` to this one would you? Seeing as it has no tests...

**Comment by wkral** [comment]
@risicle No problem, added it and squashed. I'll try to keep that in mind if I hit that again in some future fixes.

**Comment by risicle** [comment]
Thanks. It's not really your job, it's just a useful drive-by improvement that can be made.

WFM macos 10.14, linux x86_64

**Pull request merged**
