### PR TITLE
nixos/nginx: use Mozilla Intermediate TLS configuration

### PR DESCRIPTION
**Pull request by emilazy**
###### Motivation for this change

The configuration at https://ssl-config.mozilla.org/#server=nginx&config=intermediate
is reliably kept up-to-date in terms of security and compatible with a
wide range of clients. They've probably had more care and thought put
into them than our defaults, and will be easier to keep updated in
the future.

The only removed (rather than changed) configuration option here is
ssl_ecdh_curve, per https://github.com/mozilla/server-side-tls/issues/189.

Resolves #80952.

cc @infinisil @fpletz

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by Mic92 — APPROVED** [review]
I also had a similar commit in the pipeline: https://github.com/Mic92/nixpkgs/commit/3b698d9c0b3d18bfd0f55ede5b24d7a1b08be732

Chosen options looks good to me.

**Comment by Mic92** [comment]
@GrahamcOfBorg test nginx

**Review by infinisil — APPROVED** [review]
Looking good!

**Comment by Mic92** [comment]
backport pr https://github.com/NixOS/nixpkgs/pull/81902

**Comment by emilazy** [comment]
thanks, forgot about the backport!

**Pull request merged**
