### PR TITLE
nixos/onlyoffice: allow ExecStartPre additions

### LINKED ISSUE #215405: Can't add a ExecStartPre to onlyoffice systemd service
I want to change a configuration variable to onlyoffice.
Currently, the NixOS module adapts on the fly in `ExecStartPre` the upstream configuration with a `jq` call.
I'd like to make my own adaptation.
For now it's not possible due to ExecStartPre being not declared as a list, but as a direct value.

### PR DESCRIPTION
**Pull request by ppom0**
###### Description of changes

Fixes https://github.com/NixOS/nixpkgs/issues/215405

cc @SuperSandro2000 who created this module (thanks!)

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by dotlambda — COMMENTED** [review]
I think adding an option like `services.onlyoffice.settings` that uses `pkgs.formats.json` to add things to `/run/onlyoffice/config/default.json` would make more sense.

**Comment by aopom** [comment]
It's true, I can't disagree. On an other hand, permitting to add `ExecStartPre` directives can't be a bad thing either. Adding a prestart hook is often useful, and not having this possibility can [make customising things hard](https://discourse.nixos.org/t/how-to-append-string-to-existing-value-from-a-module/24335/2). What do you think?

**Comment by dotlambda** [comment]
Does this guarantee that a user-specified `ExecStartPre` is inserted after the one coming from the NixOS module?

**Comment by aopom** [comment]
No! But all options set with the module's `jq` call are options configurable by the module, so overriding them after setting them indirectly shouldn't make sense. And to be clear about it, `ExecStartPre` can serve other purposes than overriding the conf.

Nevertheless, I'm in favor of implementing `services.onlyoffice.settings`, but I won't do this today :)

**Comment by NickCao** [comment]
> Does this guarantee that a user-specified `ExecStartPre` is inserted after the one coming from the NixOS module?

Users can use `lib.mkBefore` and `lib.mkAfter` to get the desired ordering.

**Comment by SuperSandro2000** [comment]
> I think adding an option like `services.onlyoffice.settings` that uses `pkgs.formats.json` to add things to `/run/onlyoffice/config/default.json` would make more sense.

Good idea for another PR.

---

As this should break nothing, we can merge it but with settings we need to be a bit careful.

**Pull request merged**
