### PR TITLE
Suitable clang stdenv for Darwin

### PR DESCRIPTION
**Pull request by pikajude**
Doesn't involve GCC at any point. This will be necessary once 10.10 comes around.

### CODE REVIEW

**Comment by tel** [comment]
What's remaining to do to push this along?

**Comment by jwiegley** [comment]
We've got the biggest merge through now.  Time to make the next one.

**Comment by tel** [comment]
Anything I can do to contribute?

**Comment by jwiegley** [comment]
Start using it and building more derivations, so that we can improve our coverage.  Also, see the `##nix-darwin` channel on IRC freenode.

**Comment by tel** [comment]
Is there any documentation on the general way to roll these improvements into more derivations? For instance, I think the mlton derivation is failing due to some change that hides `gcc` which I think is related.

**Pull request closed without merging**
