### PR TITLE
aws-nuke: 2.22.1 -> 2.23.0

### PR DESCRIPTION
**Pull request by aaronjheng**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by natsukium** [comment]
We can't build it well.
```
error: builder for '/nix/store/lm0bn1y5cw951gm6fmqi5098a5w2smws-aws-nuke-2.23.0-go-modules.drv' failed with exit code 1;
       last 10 log lines:
       > go: downloading github.com/gemnasium/logrus-graylog-hook/v3 v3.1.0
       > go: downloading github.com/davecgh/go-spew v1.1.1
       > go: downloading github.com/pmezard/go-difflib v1.0.0
       > go: downloading github.com/jmespath/go-jmespath v0.4.0
       > go: downloading github.com/inconshreveable/mousetrap v1.1.0
       > go: downloading github.com/spf13/pflag v1.0.5
       > github.com/rebuy-de/aws-nuke/v2/resources tested by
       >       github.com/rebuy-de/aws-nuke/v2/resources.test imports
       >         github.com/rebuy-de/aws-nuke/v2/mocks/mock_cloudformationiface: no required module provides package github.com/rebuy-de/aws-nuke/v2/mocks/mock_cloudformationiface; to add it:
       >         go get github.com/rebuy-de/aws-nuke/v2/mocks/mock_cloudformationiface
       For full logs, run 'nix-store -l /nix/store/lm0bn1y5cw951gm6fmqi5098a5w2smws-aws-nuke-2.23.0-go-modules.drv'.
error: 1 dependencies of derivation '/nix/store/qjhkwxrmwf0jywpg8k5cdp65nw13r33c-aws-nuke-2.23.0.drv' failed to build
```

**Comment by aaronjheng** [comment]
Done.

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 245814` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>aws-nuke</li>
  </ul>
</details>

**Comment by natsukium** [comment]
Result of `nixpkgs-review pr 245814` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>aws-nuke</li>
  </ul>
</details>

**Review by natsukium — APPROVED** [review]
Thanks!

**Pull request merged**
