### PR TITLE
corsix-th: darwin build, add maintainer

### PR DESCRIPTION
**Pull request by matteo-pacini**
## Description of changes

- Added darwin build to `corsix-th`.
- Added myself as second maintainer for Darwin.
- Added `nix-update-script` as `passthru.updateScript`

Tested on `aarch64-darwin`. Also rebuilt on `aarch64-linux` to ensure that my changes did not break stuff.

Screenshot 2024-06-09 at 15 15 14

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [X] aarch64-linux
  - [ ] x86_64-darwin
  - [X] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by paparodeo — COMMENTED** [review]
- i don't see a reason to remove the `finalAttrs` pattern
- can put lua.withPackages in the buildInputs. no need for luaEnv attribute
- i think `lua.withPackages` brings in `lua` so can remove `lua` from buildInputs

<details><summary>suggested changes</summary>

```diff
diff --git a/pkgs/games/corsix-th/default.nix b/pkgs/games/corsix-th/default.nix
index d50c55a0718d..885de2612361 100644
--- a/pkgs/games/corsix-th/default.nix
+++ b/pkgs/games/corsix-th/default.nix
@@ -18,14 +18,14 @@
 , nix-update-script
 }:
 
-stdenv.mkDerivation rec {
+stdenv.mkDerivation (finalAttrs: {
   pname = "corsix-th";
   version = "0.67";
 
   src = fetchFromGitHub {
     owner = "CorsixTH";
     repo = "CorsixTH";
-    rev = "v${version}";
+    rev = "v${finalAttrs.version}";
     hash = "sha256-WA/VJqHXzBfVUBNtxCVsGBRzSRQ0pvDvAy03ntc0KZE=";
   };
 
@@ -33,14 +33,12 @@ stdenv.mkDerivation rec {
     ./darwin-cmake-no-fixup-bundle.patch
   ];
 
-  luaEnv = lua.withPackages(p: with p; [ luafilesystem lpeg luasec luasocket ]);
   nativeBuildInputs = [ cmake doxygen makeWrapper ];
 
   buildInputs = [
     ffmpeg
     freetype
-    lua
-    luaEnv
+    (lua.withPackages(p: with p; [ luafilesystem lpeg luasec luasocket ]))
     SDL2
     SDL2_mixer
     timidity
@@ -74,4 +72,4 @@ stdenv.mkDerivation rec {
     maintainers = with maintainers; [ hughobrien matteopacini ];
     platforms = platforms.linux ++ platforms.darwin;
   };
-}
+})
```
</details>

alternatively if don't want to expand luaEnv can put it in a let.
```nix
buildInputs = let
  luaEnv = lua.withPackages(p: with p; [ luafilesystem lpeg luasec luasocket ]);
in
[
  ...
  luaEnv
  ...
];
```

**Comment by matteo-pacini** [comment]
@paparodeo removing `lua` yields an error during the game startup - not sure why, so I put it back in.

Screenshot 2024-06-11 at 08 39 01

**Review by paparodeo — APPROVED** [review]
Result of `nixpkgs-review pr 318535` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>corsix-th</li>
  </ul>
</details>

---

Result of `nixpkgs-review pr 318535` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>corsix-th</li>
  </ul>
</details>

**Review by hughobrien — APPROVED** [review]

**Comment by wegank** [comment]
Result of `nixpkgs-review pr 318535` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>corsix-th</li>
  </ul>
</details>

**Pull request merged**
