### PR TITLE
multimc: 0.4.9 -> 0.4.11

### PR DESCRIPTION
**Pull request by AveryLychee**
###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

The patch is no longer required, as upstream (appears to have) fixed their issues.

This update means that MultiMC can now work with the updated minecraft downloading api.

### CODE REVIEW

**Comment by pSub** [comment]
I haven't tried it, but it looks good so far. Could you resolve the conflicts so that one  can just try it?

**Comment by AveryGlitch** [comment]
Err, I can't, when I click on "Resolve conflicts", the page just loads forever...

**Comment by 7c6f434c** [comment]
@AveryGlitch is the current `master` version OK?

**Comment by AveryGlitch** [comment]
Yes

**Comment by 7c6f434c** [comment]
Closing as unlucky (the other update got into master first). Still, thanks for the contribution.

**Pull request closed without merging**
