### PR TITLE
python310Packages.aiohttp: 3.8.4 -> 3.8.5

### PR DESCRIPTION
**Pull request by dotlambda**
###### Description of changes
Changelog: https://github.com/aio-libs/aiohttp/blob/v3.8.5/CHANGES.rst

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
Shouldn't we try and unvendor llhttp?

**Comment by dotlambda** [comment]
> Shouldn't we try and unvendor llhttp?

https://github.com/NixOS/nixpkgs/pull/244541

**Comment by vcunat** [comment]
Backported to 23.05 manually.

**Comment by happysalada** [comment]
Just for information, not sure if it's relevant.
Upon testing a PR on staging, I kept getting failures for this package on linux-x86_64
I had to disable the file 
`    "test_web_sendfile_functional.py"`
that had 5 failures that were "ignored exception in ...".
Maybe that just happened on my local, but I'm leaving this for reference in case there are problems on staging later on.

**Comment by newAM** [comment]
I kept getting failures on x86_64-linux too, same test.
It's flakey, the package built on the 3rd try.

**Comment by happysalada** [comment]
Ah we should disabled it at some point then.

**Comment by mweinelt** [comment]
I did in afd84eebb94b5eafb7f3002ad50df7aac4f2c722.

**Comment by happysalada** [comment]
Thank you !

**Pull request merged**
