### PR TITLE
Add ibus-qt and ibus-anthy.

### PR DESCRIPTION
**Pull request by gebner**
This adds the anthy input method to the ibus input method framework, a programs.ibus.enable option that starts ibus with the specified plugins, and the ibus-qt plugin for ibus support in qt4.

```
programs.ibus.enable = true;
programs.ibus.plugins = [ pkgs.ibus-anthy ];
```

I'm not sure about the `programs.ibus.enable` option; I have done it in a similar way as the existing `uim.enable` option (and the plugin path handling similar to `qtPlugins`).  Maybe all ibus-related packages should be moved to the inputmethods directory as well?

### CODE REVIEW

**Comment by lethalman** [comment]
Yes maybe it's better to move those stuff to the inputmethods dir.

**Comment by lethalman** [comment]
When adding new commits to the PR, please leave a comment asking for review. We don't get notified otherwise.

**Comment by lethalman** [comment]
So during the rename of ibus you removed the GIO_EXTRA_MODULES and XDG_DATA_DIRS. Why. This is going to slow down this PR merging.

**Comment by gebner** [comment]
I can't see any changes in the ibus derivation, github says "File renamed without changes".  There is another wrapProgram call in ibus-anthy without GIO_EXTRA_MODULES and XDG_DATA_DIRS though.

**Comment by lethalman** [comment]
Ops sorry. Don't know why gtk wants to be rebuilt (regardless of this PR), when building ibus.

**Comment by lethalman** [comment]
Built locally, haven't tested the module. Thanks.

**Pull request merged**
