### PR TITLE
gitkraken: 8.9.1 -> 9.0.0

### LINKED ISSUE #206227: Out-of-date gitkraken
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: gitkraken

current version: 8.9.1
desired version: 9.0.0

###### Notify maintainers

maintainers: @rhoriguchi @xnwdd @evanjs @arkivm

###### Note for maintainers

Please tag this issue in your PR.

### PR DESCRIPTION
**Pull request by toelke**
closes #206227

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by deejayem** [comment]
Result of `nixpkgs-review pr 206240` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gitkraken</li>
  </ul>
</details>

**Review by deejayem — APPROVED** [review]
Built and tested successfully on `x86_64-darwin` (I was able to launch the application and create an account).

**Comment by yswtrue** [comment]
@evanjs please merge this pr.

**Review by evanjs — APPROVED** [review]

**Comment by toelke** [comment]
Thank you!

**Comment by rhoriguchi** [comment]
This seems to be broken.

```console
> gitkraken
[3342025:0101/193445.002900:FATAL:fork_and_spawn.cc(196)] posix_spawn: No such file or directory (2)
[3342019:0101/193445.015949:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.

> gitkraken --version
9.0.0

> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.81, NixOS, 23.05 (Stoat), 23.05.20221229.677ed08`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/1psqy3qnsxj0kzmfcf67hwiz7aa8kb9b-source`
```

**Comment by toelke** [comment]
I am very sorry about this.
It works for me.

image

I am not really an nix-expert, this was my first contribution and I hoped it was an easy one. How can I help debug/fix this?

**Comment by SuperSandro2000** [comment]
Can you start it with strace to see what file it tried to access and could not found?

**Comment by sheepforce** [comment]
Can confirm, I am getting the same error and additionally `Gtk-Message: Failed to load module "appmenu-gtk-module"`. Here is an strace. After the `fork_and_spawn` error even the strace hangs.
[strace.txt](https://github.com/NixOS/nixpkgs/files/10369545/strace.txt)

Some GTK modules seem to be accessed from `/run/current-system` and others are simply not found. But I am not sure if this is noise or part of the actual problem.

**Comment by hacker1024** [comment]
With the interpreter fixes, I still cannot start GitKraken on Wayland:

```
$ gitkraken
[96242:0121/164716.352396:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
```

**Comment by xRiot** [comment]
> With the interpreter fixes, I still cannot start GitKraken on Wayland (it worked before the update):
> 
> ```
> $ gitkraken
> [96242:0121/164716.352396:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
> ```

DId you find a fix?

**Comment by hacker1024** [comment]
> > With the interpreter fixes, I still cannot start GitKraken on Wayland (it worked before the update):
> > ```
> > $ gitkraken
> > [96242:0121/164716.352396:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
> > ```
> 
> DId you find a fix?

By the time this made it into`nixos-unstable`, this issue disappeared. I don't know why.

**Comment by xRiot** [comment]
> > > With the interpreter fixes, I still cannot start GitKraken on Wayland (it worked before the update):
> > > ```
> > > $ gitkraken
> > > [96242:0121/164716.352396:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
> > > ```
> > 
> > 
> > DId you find a fix?
> 
> By the time this made it into`nixos-unstable`, this issue disappeared. I don't know why.

Wait you're actually able to run GitKraken on Wayland? Mine fails on Hyprland with:
```
# gitkraken --enable-features=UseOzonePlatform --ozone-platform=wayland
[1455001:0220/201342.280249:ERROR:egl_util.cc(74)] Failed to load GLES library: libGLESv2.so.2: libGLESv2.so.2: cannot open shared object file: No such file or directory
[1455001:0220/201342.280862:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
LaunchProcess: failed to execvp:
xdg-settings
[1454964:0220/201342.355628:ERROR:cursor_loader.cc(116)] Failed to load a platform cursor of type kNull
```
With this configuration
```
services.xserver.videoDrivers = [ "nvidia" ]; # Wayland
hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.beta;

hardware.opengl = {
  enable = true;
  driSupport = true; # Vulkan
  
  extraPackages = with pkgs; [
    vaapiVdpau
    libvdpau-va-gl
  ];
};
```
(I'm not using XWayland)

**Comment by forgondolin** [comment]
I was using gitkraken normally last week (02/20) and on 02/23 it started to fail, I'll try the unstable and see what happens.

**Pull request merged**
