### PR TITLE
graalvm: remove derivation

### PR DESCRIPTION
**Pull request by thiagokokada**
###### Motivation for this change

This derivation was not updated since Jan 18, 2020. It doesn't build on Hydra because it needs too much memory (~30GB). And no other packages depend on it.

Also, this is a very complex package and really difficult to maintain. It is a blocker for https://github.com/NixOS/nixpkgs/pull/141794, since a recent bump of broke it.

`graalvm8-ce` is the replacement. It is much more up-to-date (`graalvm` is on version 19.2.1, `graalvm8-ce` is on version 21.2.0), it is much easier on Hydra (it uses the binary from Oracle).

I also deprecated `jvmci8` and `mx`. I am not sure if `graalvm8` supplies them, but if something is missing we can always add it later to `graalvm8-ce`.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by superherointj — APPROVED** [review]
LGTM. Thanks!

`nixpkgs-review pr 141812`:

2 packages built:
graalvm11 graalvm8

**Comment by thiagokokada** [comment]
@hlolli (@volth doesn't seem to exist anymore).

**Review by hlolli — APPROVED** [review]

**Comment by partisani** [comment]
I know this was opened 3 years ago, but i can't seem to find a way to download `graalvm8-ce`, as trying to build my config with it installed just says it doesn't exist, and 11+ versions give an error telling me to use `graalvm-ce` instead, which uses version 22 as of right now

**Comment by thiagokokada** [comment]
> I know this was opened 3 years ago, but i can't seem to find a way to download `graalvm8-ce`, as trying to build my config with it installed just says it doesn't exist, and 11+ versions give an error telling me to use `graalvm-ce` instead, which uses version 22 as of right now

Both `graalvm8-ce` and `graalvm11-ce` were deprecated a long time ago by upstream, so this is why they're removed.

**Pull request merged**
