### PR TITLE
tzdata: 2024a -> 2024b

### PR DESCRIPTION
**Pull request by trofi**
Changes: https://github.com/eggert/tz/blob/2024b/NEWS

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by ajs124 — APPROVED** [review]

**Review by fpletz — APPROVED** [review]

**Comment by emilazy** [comment]
Looks like the build is broken? https://github.com/NixOS/nixpkgs/pull/340523#issuecomment-2342927347

**Comment by emilazy** [comment]
Beautiful:

```
ccuurrlcl:u: r ((7777) err)o rle :rrosre tste titnign( g cert7ificate cfeirl7te) eirfriocr setti:ng certifi acate file: /n/no-certto--fcielret.cr-tf
ei file: /nloe.crt-
cert-file.crt
curl: (77) error setting certificate file: /no-cert-file.crt
clang -o date -DHAVE_LINK=0 -DZIC_BLOAT_DEFAULT=\"fat\"  date.o localtime.o strftime.o 
make: *** [Makefile:992: theory.ck] Error 1
make: *** Waiting for unfinished jobs....
```

(from https://github.com/NixOS/nixpkgs/pull/340523#issuecomment-2343524170)

**Comment by emilazy** [comment]
ccuurrlcl is experiencing an eirfriocr when setti:ng certifi acate file, what could be more clear?

**Comment by vcunat** [comment]
On Hydra: https://hydra.nixos.org/build/272249259/nixlog/164/tail

**Comment by emilazy** [comment]
I can’t immediately find a patch for one of the issues mentioned on the mailing list so perhaps we should roll back until the next release.

**Comment by mweinelt** [comment]
Was reverted on staging-next-24.05 already.

**Comment by trofi** [comment]
The reported failure looks darwin-specific (`curl` presence in the build closure?). I'll see how easy it is to trick darwin not to run network tests.

**Comment by trofi** [comment]
> The reported failure looks darwin-specific (`curl` presence in the build closure?). I'll see how easy it is to trick darwin not to run network tests.

Proposed the fix as:
- https://github.com/NixOS/nixpkgs/pull/341307

**Pull request merged**
