### PR TITLE
ferretdb: 0.9.2 -> 0.9.3

### PR DESCRIPTION
**Pull request by yu-re-ka**
###### Description of changes

https://github.com/FerretDB/FerretDB/discussions/2191

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by JulienMalka — COMMENTED** [review]
Looks like one test is failing, might investigate later.

**Comment by yu-re-ka** [comment]
The test is not finding the compiled binary, however even if it would find the binary it would still fail because it will be missing its corresponding git revision information.
Should we just skip/delete this particular test?

**Comment by noisersup** [comment]
Hi! The recent changes introduced some changes in binary building. 
I've tried to debug what nix is doing while building derivation, but honestly, I couldn't find any easy way to log what exact commands are generated by `buildGoModule`, however I believe that the test fails because it waits for development binary, which is not created here.

I would suggest to set `doCheck=false` and don't run tests at all, especially that `buildGoModule` here runs only tests from `./cmd/ferretdb` submodule, which doesn't implement production relevant tests at all.

**Review by noisersup — COMMENTED** [review]
Hi! The recent changes introduced some changes in binary building.
I've tried to debug what nix is doing while building derivation, but honestly, I couldn't find any easy way to log what exact commands are generated by `buildGoModule`, however I believe that the test fails because it waits for development binary, which is not created here.

I would suggest to set `doCheck=false` and don't run tests at all, especially that `buildGoModule` here runs only tests from `./cmd/ferretdb` submodule, which doesn't implement production relevant tests at all.

**Comment by yu-re-ka** [comment]
@noisersup thanks for the hint! Is there any way we can run production relevant tests in the Nixpkgs packaging (or in a NixOS test maybe)?

**Comment by noisersup** [comment]
@yu-re-ka Sorry, I guess I have misunderstood something :) What's the purpose of tests ran at nix build level? What do we want to check with them?

**Comment by yu-re-ka** [comment]
We try to have as many tests as possible to detect breakages when our toolchain changes, for example we might build FerretDB with a newer Golang version than what the upstream tests run with.
Simply disabling all tests is thus discouraged.

**Comment by AlekSi** [comment]
In that case, the best test could be something like `ferretdb --version | grep ${version}" (the binary panics if something required wasn't set during compilation).

Running "real" FerretDB tests requires a lot of things running the in the environment.

Other options could be to run `go test` with the `-short` flag, so the failing test is skipped, or for us to modify that test to try to locate the binary in other places (that's something that we don't really want to do).

**Comment by JulienMalka** [comment]
We can maybe disable that specific test via a patch ?

**Comment by AlekSi** [comment]
I would strongly oppose that :)

**Comment by yu-re-ka** [comment]
I have disabled the unit tests and instead implemented a installCheckPhase that does `ferretdb --version | grep ${version}` as suggested.

**Review by noisersup — APPROVED** [review]
Thank you!

**Pull request merged**
