### PR TITLE
python3Packages.sqlalchemy: 1.3.23 -> 1.4.13

### PR DESCRIPTION
**Pull request by mweinelt**
###### Motivation for this change

<s>Required for home-assistant v2021.5.0.</s> Will add an override for home-assistant. Probably too big before the release.

https://docs.sqlalchemy.org/en/14/changelog/changelog_14.html
https://docs.sqlalchemy.org/en/14/changelog/changelog_13.html

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mweinelt** [comment]
https://github.com/NixOS/nixpkgs/pull/111653 101-500 here, 1001-2500 now. Great.

/rebase staging

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 121854` at 86657e88 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>107 packages marked as broken and skipped:</summary>
  <ul>
    <li>bareos</li>
    <li>bonfire</li>
    <li>cassandra_2_1</li>
    <li>cassandra_2_2</li>
    <li>couchdb</li>
    <li>gnuradio3_7</li>
    <li>gnuradio3_7Packages.ais</li>
    <li>gnuradio3_7Packages.gnuradio</li>
    <li>gnuradio3_7Packages.gsm</li>
    <li>gnuradio3_7Packages.limesdr</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>19 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/f57b84bfddcfb1f74b84c2636907cc54">expliot</a></li>
    <li><a href="https://gist.github.com/3eb8b4abd3ae2ff5102ee2485f0612cb">mailman</a></li>
    <li><a href="https://gist.github.com/fdd9ee8f48d303a9ceb58b074d235e21">python38Packages.databases</a></li>
    <li><a href="https://gist.github.com/3f77c740472d82fe73bbadb69b442063">python38Packages.mailman</a></li>
    <li><a href="https://gist.github.com/791566b3495f5f038c16b2b936c96ae8">python38Packages.mailman-hyperkitty</a></li>
    <li><a href="https://gist.github.com/a399ce453b15fd28185ffb3c5066fd48">python38Packages.marshmallow-sqlalchemy</a></li>
    <li><a href="https://gist.github.com/8a3194f87fff30ae9b0abc43cb71f22c">python38Packages.orm</a></li>
    <li><a href="https://gist.github.com/8ef2de4c5062c84deb0eeefcc62e4cf4">python38Packages.pecan</a></li>
    <li><a href="https://gist.github.com/309361af174ce5b257187755b98cfacd">python38Packages.pynetdicom</a></li>
    <li><a href="https://gist.github.com/fa2e56db205f756babc64b250ad68a7d">python38Packages.snowflake-connector-python</a></li>
    <li><a href="https://gist.github.com/dbc0e70bc14390c0fd932756ea7877fa">python38Packages.snowflake-sqlalchemy</a></li>
    <li><a href="https://gist.github.com/f1ea7a8fc06c19c6a189339ee47bc5ce">python38Packages.sqlsoup</a></li>
    <li><a href="https://gist.github.com/dd5d4487dc1cc78c8f5b8cad403d8c87">python39Packages.databases</a></li>
    <li><a href="https://gist.github.com/6e92a095ccea8acfd8aaecbdaa5f49f3">python39Packages.marshmallow-sqlalchemy</a></li>
    <li><a href="https://gist.github.com/d8e175347b2b1afec62527d871999f73">python39Packages.orm</a></li>
    <li><a href="https://gist.github.com/37089787a7f8761e8f76ae566a72d5ee">python39Packages.snowflake-connector-python</a></li>
    <li><a href="https://gist.github.com/97ea91fc2e316562b2293851e2dc8d6b">python39Packages.snowflake-sqlalchemy</a></li>
    <li><a href="https://gist.github.com/2e0ffb93c53573fe3914ba3bb569a92b">python39Packages.sqlsoup</a></li>
    <li><a href="https://gist.github.com/718a6d05722c5fcd64152f01afc1d959">python39Packages.tablib</a></li>
  </ul>
</details>
<details>
  <summary>1118 packages skipped due to time constraints:</summary>
  <ul>
    <li>DisnixWebService</li>
    <li>R</li>
    <li>abcl</li>
    <li>adapta-gtk-theme</li>
    <li>adoptopenjdk-icedtea-web</li>
    <li>aiodnsbrute</li>
    <li>alloy (alloy5)</li>
    <li>alloy4</li>
    <li>ansible (ansible_2_10)</li>
    <li>ansible-lint (python38Packages.ansible-lint)</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>129 packages built successfully:</summary>
  <ul>
    <li>acd-cli</li>
    <li>anki</li>
    <li>ankisyncd</li>
    <li>cum</li>
    <li>jre8</li>
    <li>liberation_ttf (liberation_ttf_v2)</li>
    <li>mautrix-signal</li>
    <li>mautrix-telegram</li>
    <li>python38Packages.APScheduler</li>
    <li>python38Packages.ColanderAlchemy</li>
    <li>python38Packages.aiocontextvars</li>
    <li>python38Packages.alembic</li>
    <li>python38Packages.angr</li>
    <li>python38Packages.angrop</li>
    <li>python38Packages.azure-core</li>
    <li>python38Packages.azure-storage-blob</li>
    <li>python38Packages.backoff</li>
    <li>python38Packages.celery</li>
    <li>python38Packages.factory_boy</li>
    <li>python38Packages.flask_sqlalchemy</li>
    <li>python38Packages.fonttools</li>
    <li>python38Packages.geoalchemy2</li>
    <li>python38Packages.google-api-core</li>
    <li>python38Packages.google-api-python-client</li>
    <li>python38Packages.google-auth</li>
    <li>python38Packages.google-auth-httplib2</li>
    <li>python38Packages.google-auth-oauthlib</li>
    <li>python38Packages.google-cloud-core</li>
    <li>python38Packages.google-cloud-iam</li>
    <li>python38Packages.google-cloud-kms</li>
    <li>python38Packages.google-cloud-storage</li>
    <li>python38Packages.google-cloud-testutils</li>
    <li>python38Packages.google-resumable-media</li>
    <li>python38Packages.httplib2</li>
    <li>python38Packages.httpretty</li>
    <li>python38Packages.imdbpy</li>
    <li>python38Packages.kombu</li>
    <li>python38Packages.mautrix (python38Packages.mautrix-appservice)</li>
    <li>python38Packages.msrest</li>
    <li>python38Packages.oauth2client</li>
    <li>python38Packages.poetry</li>
    <li>python38Packages.pymodbus</li>
    <li>python38Packages.pymysqlsa</li>
    <li>python38Packages.pytest-factoryboy</li>
    <li>python38Packages.pytest-randomly</li>
    <li>python38Packages.python-telegram-bot</li>
    <li>python38Packages.rich</li>
    <li>python38Packages.sqlalchemy</li>
    <li>python38Packages.sqlalchemy-citext</li>
    <li>python38Packages.sqlalchemy-i18n</li>
    <li>python38Packages.sqlalchemy-utils</li>
    <li>python38Packages.telethon-session-sqlalchemy</li>
    <li>python38Packages.tld</li>
    <li>python38Packages.wled</li>
    <li>python39Packages.APScheduler</li>
    <li>python39Packages.ColanderAlchemy</li>
    <li>python39Packages.Quandl (python39Packages.quandl)</li>
    <li>python39Packages.aiocontextvars</li>
    <li>python39Packages.aioinflux</li>
    <li>python39Packages.alembic</li>
    <li>python39Packages.angr</li>
    <li>python39Packages.angrop</li>
    <li>python39Packages.apptools</li>
    <li>python39Packages.azure-core</li>
    <li>python39Packages.azure-storage-blob</li>
    <li>python39Packages.bkcharts</li>
    <li>python39Packages.clevercsv</li>
    <li>python39Packages.csvs-to-sqlite</li>
    <li>python39Packages.drms</li>
    <li>python39Packages.factory_boy</li>
    <li>python39Packages.flammkuchen</li>
    <li>python39Packages.flask_sqlalchemy</li>
    <li>python39Packages.geoalchemy2</li>
    <li>python39Packages.google-api-core</li>
    <li>python39Packages.google-api-python-client</li>
    <li>python39Packages.google-auth</li>
    <li>python39Packages.google-auth-httplib2</li>
    <li>python39Packages.google-auth-oauthlib</li>
    <li>python39Packages.holoviews</li>
    <li>python39Packages.httplib2</li>
    <li>python39Packages.httpretty</li>
    <li>python39Packages.huggingface-hub</li>
    <li>python39Packages.imdbpy</li>
    <li>python39Packages.influxdb</li>
    <li>python39Packages.kombu</li>
    <li>python39Packages.mautrix (python39Packages.mautrix-appservice)</li>
    <li>python39Packages.mplfinance</li>
    <li>python39Packages.msrest</li>
    <li>python39Packages.oauth2client</li>
    <li>python39Packages.pandas</li>
    <li>python39Packages.pandas-datareader</li>
    <li>python39Packages.panel</li>
    <li>python39Packages.parfive</li>
    <li>python39Packages.partd</li>
    <li>python39Packages.poetry</li>
    <li>python39Packages.pyezviz</li>
    <li>python39Packages.pymysqlsa</li>
    <li>python39Packages.pynetdicom</li>
    <li>python39Packages.pytest-factoryboy</li>
    <li>python39Packages.pytest-randomly</li>
    <li>python39Packages.python-telegram-bot</li>
    <li>python39Packages.pytrends</li>
    <li>python39Packages.rapidfuzz</li>
    <li>python39Packages.rich</li>
    <li>python39Packages.seaborn</li>
    <li>python39Packages.sqlalchemy</li>
    <li>python39Packages.sqlalchemy-citext</li>
    <li>python39Packages.sqlalchemy-i18n</li>
    <li>python39Packages.sqlalchemy-utils</li>
    <li>python39Packages.telethon-session-sqlalchemy</li>
    <li>python39Packages.tld</li>
    <li>python39Packages.tqdm</li>
    <li>python39Packages.vega_datasets</li>
    <li>python39Packages.vidstab</li>
    <li>python39Packages.yfinance</li>
    <li>semiphemeral</li>
    <li>sourcehut.buildsrht</li>
    <li>sourcehut.dispatchsrht</li>
    <li>sourcehut.gitsrht</li>
    <li>sourcehut.hgsrht</li>
    <li>sourcehut.hubsrht</li>
    <li>sourcehut.listssrht</li>
    <li>sourcehut.mansrht</li>
    <li>sourcehut.metasrht</li>
    <li>sourcehut.pastesrht</li>
    <li>sourcehut.todosrht</li>
    <li>vorta</li>
    <li>yokadi</li>
    <li>ytcc</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/sqlalchemy/default.nix:52:3:
```
   |
52 |   meta = with lib; {
   |   ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement.

**Comment by mweinelt** [comment]
Thanks, changes applied.

**Review by jonringer — APPROVED** [review]

**Review by jonringer — CHANGES_REQUESTED** [review]
actually, read the deprecations: https://docs.sqlalchemy.org/en/14/changelog/changelog_14.html#change-1.4.0b1

I would rather not have to deal with the potential of mass breakages. Please wait til the 14th (staging will no longer see changes in the release) to merge.

**Comment by mweinelt** [comment]
> Probably too big before the release.

see my top post :)

**Comment by jonringer** [comment]
> see my top post :)

Yea, I was just confirming that I feel the same way :)

**Review by jonringer — APPROVED** [review]
LGTM

```
https://github.com/NixOS/nixpkgs/pull/121854

1 package built:
python3Packages.pandas
```

**Pull request merged**
