### PR TITLE
git: enable some of broken tests

### PR DESCRIPTION
**Pull request by sugar700**
###### Motivation for this change

Enabled tests because they could be enabled. I think we may want to do some sort of change in git anyway because of https://github.com/NixOS/nixpkgs/issues/73806, so rebuild is non-issue.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @peti @the-kenny @wmertens @globin

### CODE REVIEW

**Review by wmertens — APPROVED** [review]

**Comment by FRidh** [comment]
needs rebase

**Comment by xfix** [comment]
Done.

**Comment by FRidh** [comment]
rebase, don't merge.

**Comment by xfix** [comment]
Rebased.

**Comment by xfix** [comment]
Hm, weird, build fails, but only on x86_64-linux. I guess there may be something non-deterministic then?

**Comment by xfix** [comment]
Rebased again due to another merge conflict.

**Comment by Mic92** [comment]
@GrahamcOfBorg build git

**Pull request merged**
