### PR TITLE
nixos/geoclue2: add network-online.target as wanted by geoclue2

### PR DESCRIPTION
**Pull request by matthewbauer**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by peterhoeg** [comment]
Please refer to #86273

**Comment by flokli** [comment]
> Please refer to #86273

I think @matthewbauer 's approach is correct here - see my reasoning in https://github.com/nixos/nixpkgs/pull/86273#issuecomment-622331318.

**Comment by flokli** [comment]
@matthewbauer does geoclue2 fail on startup if it doesn't have network access, or is it just a service binding on a socket?

**Comment by peterhoeg** [comment]
If geoclue fails on startup without a network, that's a bug in geoclue. I'm not saying we shouldn't work around that, but ideally we want this fixed upstream.

**Comment by matthewbauer** [comment]
Closing in favor of https://github.com/NixOS/nixpkgs/pull/86484

**Pull request closed without merging**
