### PR TITLE
projectm: 3.1.12 -> 4.1.3

### PR DESCRIPTION
**Pull request by pinpox**
Diff: https://github.com/projectM-visualizer/projectM/compare/v3.1.12...v4.0.0

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Result of `nixpkgs-review pr 250969` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>clementine</li>
    <li>kodiPackages.visualization-projectm</li>
    <li>projectm</li>
  </ul>
</details>

**Comment by pinpox** [comment]
I got it to build. With this release a lot of components (e.g. the binaries) have been moved to other external locations, see https://github.com/projectM-visualizer/projectm/commit/9e9f4ca1b2b767e7e35db60907b2868b096973b6 for more information.

As is, this now only includes the binaries and the binaries and frontends would have to be separate packages in nixpkgs I think. 
Let me know what you think or how to proceed.

**Comment by luzpaz** [comment]
Note: 4.1.0 released  
https://github.com/projectM-visualizer/projectm/releases/tag/v4.1.0

**Comment by pinpox** [comment]
> Note: 4.1.0 released https://github.com/projectM-visualizer/projectm/releases/tag/v4.1.0

Updated to newest release. Still don't know how to proceed on fixing the build though.

**Comment by pinpox** [comment]
Blocked by: https://github.com/NixOS/nixpkgs/pull/310821

**Comment by hervyqa** [comment]
Note: [libprojectM Release 4.1.3](https://github.com/projectM-visualizer/projectm/releases/tag/v4.1.3)

**Comment by pinpox** [comment]
I'm not using this any longer and wont find the time to finish the PR as it currently fails to build. If someone wants to continue on it feel free to reopen or open a new PR.

**Pull request closed without merging**
