### PR TITLE
python3.pkgs.drf-spectacular-sidecar: 2023.3.1 -> 2023.9.1

### PR DESCRIPTION
**Pull request by yu-re-ka**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by yu-re-ka** [comment]
Built nixosTests.peering-manager

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 257307` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package marked as broken and skipped:
</summary>
<ul>
<li>netbox_3_3</li>
</ul>
</details>
<details>
<summary>
12 packages built:
</summary>
<ul>
<li>baserow</li>
<li>baserow.dist</li>
<li>netbox</li>
<li>peering-manager</li>
<li>python310Packages.drf-spectacular</li>
<li>python310Packages.drf-spectacular-sidecar</li>
<li>python310Packages.drf-spectacular-sidecar.dist</li>
<li>python310Packages.drf-spectacular.dist</li>
<li>python311Packages.drf-spectacular</li>
<li>python311Packages.drf-spectacular-sidecar</li>
<li>python311Packages.drf-spectacular-sidecar.dist</li>
<li>python311Packages.drf-spectacular.dist</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
python310Packages.drf-spectacular.dist:
<details>

Package is missing maintainers.
If the package is using runCommand please make sure to inherit or list one or more maintainers.

got build log for '/nix/store/np9n264ibzi0zjw4ymfxf9nn148d4ka6-python3.10-drf-spectacular-0.26.5-dist' from 'daemon'
When evaluating attribute ‘python310Packages.drf-spectacular.dist’:
warning: maintainers-missing
Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/drf-spectacular/default.nix:81:5:

```
   |
81 |     maintainers = with maintainers; [ ];
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md
</details>
python310Packages.drf-spectacular:
<details>

Package is missing maintainers.
If the package is using runCommand please make sure to inherit or list one or more maintainers.

got build log for '/nix/store/amgm5i208kwajwa0dcm2dacq8rld1kq8-python3.10-drf-spectacular-0.26.5' from 'daemon'
When evaluating attribute ‘python310Packages.drf-spectacular’:
warning: maintainers-missing
Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/drf-spectacular/default.nix:81:5:

```
   |
81 |     maintainers = with maintainers; [ ];
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md
</details>
python310Packages.drf-spectacular-sidecar.dist:
<details>

Package is missing maintainers.
If the package is using runCommand please make sure to inherit or list one or more maintainers.

got build log for '/nix/store/c7msl7ln02igk92x1ca8d5pc9qbnsaph-python3.10-drf-spectacular-sidecar-2023.9.1-dist' from 'daemon'
When evaluating attribute ‘python310Packages.drf-spectacular-sidecar.dist’:
warning: maintainers-missing
Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/drf-spectacular-sidecar/default.nix:32:5:

```
   |
32 |     maintainers = with maintainers; [ ];
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md
</details>
python310Packages.drf-spectacular-sidecar:
<details>

Package is missing maintainers.
If the package is using runCommand please make sure to inherit or list one or more maintainers.

got build log for '/nix/store/zvddsj3fmnasrsc9zyh630fzjznx961y-python3.10-drf-spectacular-sidecar-2023.9.1' from 'daemon'
When evaluating attribute ‘python310Packages.drf-spectacular-sidecar’:
warning: maintainers-missing
Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/drf-spectacular-sidecar/default.nix:32:5:

```
   |
32 |     maintainers = with maintainers; [ ];
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md
</details>
python311Packages.drf-spectacular.dist:
<details>

Package is missing maintainers.
If the package is using runCommand please make sure to inherit or list one or more maintainers.

got build log for '/nix/store/qpcjwabc4glclaz6mz8v87q7ad6d9spi-python3.11-drf-spectacular-0.26.5-dist' from 'daemon'
When evaluating attribute ‘python311Packages.drf-spectacular.dist’:
warning: maintainers-missing
Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/drf-spectacular/default.nix:81:5:

```
   |
81 |     maintainers = with maintainers; [ ];
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md
</details>
python311Packages.drf-spectacular:
<details>

Package is missing maintainers.
If the package is using runCommand please make sure to inherit or list one or more maintainers.

got build log for '/nix/store/9clli2hg40l98wafb3jzw72l3yc67cx9-python3.11-drf-spectacular-0.26.5' from 'daemon'
When evaluating attribute ‘python311Packages.drf-spectacular’:
warning: maintainers-missing
Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/drf-spectacular/default.nix:81:5:

```
   |
81 |     maintainers = with maintainers; [ ];
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md
</details>
python311Packages.drf-spectacular-sidecar.dist:
<details>

Package is missing maintainers.
If the package is using runCommand please make sure to inherit or list one or more maintainers.

got build log for '/nix/store/cv3d9n2638mpwgz7wwqgs5ga0hg346rh-python3.11-drf-spectacular-sidecar-2023.9.1-dist' from 'daemon'
When evaluating attribute ‘python311Packages.drf-spectacular-sidecar.dist’:
warning: maintainers-missing
Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/drf-spectacular-sidecar/default.nix:32:5:

```
   |
32 |     maintainers = with maintainers; [ ];
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md
</details>
python311Packages.drf-spectacular-sidecar:
<details>

Package is missing maintainers.
If the package is using runCommand please make sure to inherit or list one or more maintainers.

got build log for '/nix/store/znl3ji0qpaczb7j6rcbixjfbnrv2lgcf-python3.11-drf-spectacular-sidecar-2023.9.1' from 'daemon'
When evaluating attribute ‘python311Packages.drf-spectacular-sidecar’:
warning: maintainers-missing
Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/python-modules/drf-spectacular-sidecar/default.nix:32:5:

```
   |
32 |     maintainers = with maintainers; [ ];
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md
</details>
</details>

**Comment by yu-re-ka** [comment]
@SuperSandro2000 do you approve this change?

**Review by SuperSandro2000 — APPROVED** [review]
Ups, forgot that 😅

**Pull request merged**
