### PR TITLE
jabref: 5.6 -> 5.7

### PR DESCRIPTION
**Pull request by linsui**
###### Description of changes

1. lockfile is removed. There is no dynamic version used so it's not needed.
2. Fix double wrapper.
3. Fix wm class.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by linsui** [comment]
@ofborg build jabref

**Comment by linsui** [comment]
@gebner Do you still maintain jabref?

**Comment by MrTarantoga** [comment]
You should also mark "Tested basic functionality of all binary files (usually in ./result/bin/)" in your PR. You said you tested it and verified the basic functionality?

**Comment by MrTarantoga** [comment]
Your commits https://github.com/NixOS/nixpkgs/commit/6ce2b1a950d97064546b119b76b71e039bec5c42 and https://github.com/NixOS/nixpkgs/commit/c9af52f43ccfe5d71da18d3c7b3d5abc5df8134c not relate to jabref

**Comment by linsui** [comment]
What do you mean?

**Comment by MrTarantoga** [comment]
Error on my side during working with your branch. Sorry, I'll delete the comment.

**Review by wamserma — APPROVED** [review]
Diff LGTM, running via `nix run github:NixOS/nixpkgs/pull/189720/merge#jabref`worked.

**Comment by wamserma** [comment]
@SuperSandro2000 ping 4 merge

**Pull request merged**
