### PR TITLE
xorgproto: 2021.3->2021.4 & xkeyboard_config: 2.31->2.32

### PR DESCRIPTION
**Pull request by Stunkymonkey**
###### Motivation for this change
new releases. if i should open seperate PRs please tell me to do so.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](./CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 125788` at ab0297c0 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>221 packages marked as broken and skipped:</summary>
  <ul>
    <li>OVMF-CSM</li>
    <li>adoptopenjdk-hotspot-bin-13</li>
    <li>adoptopenjdk-hotspot-bin-14</li>
    <li>adoptopenjdk-jre-hotspot-bin-13</li>
    <li>adoptopenjdk-jre-hotspot-bin-14</li>
    <li>airtame</li>
    <li>ams-lv2</li>
    <li>apfelgrid</li>
    <li>applgrid</li>
    <li>artyFX</li>
    <li>asymptote</li>
    <li>attract-mode</li>
    <li>autotrace</li>
    <li>beignet</li>
    <li>betaflight-configurator</li>
    <li>blastem</li>
    <li>bless</li>
    <li>cargo-rr</li>
    <li>cassandra_2_1</li>
    <li>cassandra_2_2</li>
    <li>chez</li>
    <li>colmapWithCuda</li>
    <li>cura_stable</li>
    <li>deeptools</li>
    <li>devede</li>
    <li>displaycal</li>
    <li>dvd-slideshow</li>
    <li>electron_3</li>
    <li>electron_4</li>
    <li>electron_5</li>
    <li>embree</li>
    <li>embree2</li>
    <li>eterm</li>
    <li>evilvte</li>
    <li>exodus</li>
    <li>ffmpeg_2</li>
    <li>ffmpeg_2_8</li>
    <li>ffmpeg_3</li>
    <li>ffmpeg_3_4</li>
    <li>firestarter</li>
    <li>forge</li>
    <li>gb-backup</li>
    <li>git-dit</li>
    <li>globalplatform</li>
    <li>globulation2</li>
    <li>gmtk</li>
    <li>gnome_mplayer</li>
    <li>gnuradio3_7</li>
    <li>gnuradio3_7Packages.ais</li>
    <li>gnuradio3_7Packages.gnuradio</li>
    <li>gnuradio3_7Packages.gsm</li>
    <li>gnuradio3_7Packages.limesdr</li>
    <li>gnuradio3_7Packages.nacl</li>
    <li>gnuradio3_7Packages.osmosdr</li>
    <li>gnuradio3_7Packages.rds</li>
    <li>gopro</li>
    <li>gppcscconnectionplugin</li>
    <li>gpshell</li>
    <li>grass</li>
    <li>green-pdfviewer</li>
    <li>gtkd</li>
    <li>gtmess</li>
    <li>hplipWithPlugin_3_16_11</li>
    <li>hplipWithPlugin_3_18_5</li>
    <li>hplip_3_16_11</li>
    <li>hplip_3_18_5</li>
    <li>idris2</li>
    <li>impressive</li>
    <li>intecture-cli</li>
    <li>intel-compute-runtime</li>
    <li>intel-media-driver</li>
    <li>invoice2data</li>
    <li>isabelle</li>
    <li>jboss</li>
    <li>jfbpdf</li>
    <li>jfbview</li>
    <li>k2pdfopt</li>
    <li>k3d</li>
    <li>keyfinder</li>
    <li>libav</li>
    <li>libav_0_8</li>
    <li>libav_11</li>
    <li>libav_12</li>
    <li>libgroove</li>
    <li>libvirt_5_9_0</li>
    <li>libvmi</li>
    <li>linuxPackages_hardkernel_4_14.akvcam</li>
    <li>linuxPackages_hardkernel_4_14.dpdk</li>
    <li>linuxPackages_hardkernel_4_14.xpadneo</li>
    <li>linuxPackages_hardkernel_latest.akvcam</li>
    <li>linuxPackages_hardkernel_latest.dpdk</li>
    <li>linuxPackages_hardkernel_latest.xpadneo</li>
    <li>linuxPackages_testing_bcachefs.akvcam</li>
    <li>linuxPackages_testing_bcachefs.dpdk</li>
    <li>linuxPackages_testing_bcachefs.xpadneo</li>
    <li>loxodo</li>
    <li>luxcorerender</li>
    <li>magma</li>
    <li>mame</li>
    <li>meo</li>
    <li>metamorphose2</li>
    <li>mrxvt</li>
    <li>mupdf_1_17</li>
    <li>natron</li>
    <li>nixui</li>
    <li>nvtop</li>
    <li>obs-ndi</li>
    <li>ocropus</li>
    <li>odpdown</li>
    <li>onedrive</li>
    <li>openems</li>
    <li>openrw</li>
    <li>opentsdb</li>
    <li>pcsxr</li>
    <li>pdfdiff</li>
    <li>pgadmin</li>
    <li>photoflow</li>
    <li>pig</li>
    <li>plover.stable</li>
    <li>poedit</li>
    <li>polymake</li>
    <li>processing</li>
    <li>pulseeffects-legacy</li>
    <li>pulseeffects-pw</li>
    <li>python38Packages.HTSeq</li>
    <li>python38Packages.caffe</li>
    <li>python38Packages.cnvkit</li>
    <li>python38Packages.dask-gateway</li>
    <li>python38Packages.dask-jobqueue</li>
    <li>python38Packages.dask-ml</li>
    <li>python38Packages.dask-mpi</li>
    <li>python38Packages.dask-xgboost</li>
    <li>python38Packages.datashader</li>
    <li>python38Packages.fipy</li>
    <li>python38Packages.foundationdb51</li>
    <li>python38Packages.foundationdb52</li>
    <li>python38Packages.foundationdb60</li>
    <li>python38Packages.foundationdb61</li>
    <li>python38Packages.foxdot</li>
    <li>python38Packages.ignite</li>
    <li>python38Packages.pycuda</li>
    <li>python38Packages.pygmt</li>
    <li>python38Packages.pynvml</li>
    <li>python38Packages.python-csxcad</li>
    <li>python38Packages.python-openems</li>
    <li>python38Packages.pythonnet</li>
    <li>python38Packages.pytorchWithCuda</li>
    <li>python38Packages.spacy</li>
    <li>python38Packages.spacy-transformers</li>
    <li>python38Packages.streamz</li>
    <li>python38Packages.stumpy</li>
    <li>python38Packages.tensorflowWithCuda</li>
    <li>python38Packages.textacy</li>
    <li>python38Packages.thinc</li>
    <li>python39Packages.HTSeq</li>
    <li>python39Packages.caffe</li>
    <li>python39Packages.cnvkit</li>
    <li>python39Packages.dask-gateway</li>
    <li>python39Packages.dask-jobqueue</li>
    <li>python39Packages.dask-mpi</li>
    <li>python39Packages.dask-xgboost</li>
    <li>python39Packages.fipy</li>
    <li>python39Packages.foundationdb51</li>
    <li>python39Packages.foundationdb52</li>
    <li>python39Packages.foundationdb60</li>
    <li>python39Packages.foundationdb61</li>
    <li>python39Packages.foxdot</li>
    <li>python39Packages.ignite</li>
    <li>python39Packages.pycuda</li>
    <li>python39Packages.pygmt</li>
    <li>python39Packages.pynvml</li>
    <li>python39Packages.python-csxcad</li>
    <li>python39Packages.python-openems</li>
    <li>python39Packages.pythonnet</li>
    <li>python39Packages.pytorchWithCuda</li>
    <li>python39Packages.streamz</li>
    <li>python39Packages.tensorflowWithCuda</li>
    <li>python39Packages.thinc</li>
    <li>qemu_xen</li>
    <li>qemu_xen-light</li>
    <li>qemu_xen_4_10</li>
    <li>qemu_xen_4_10-light</li>
    <li>qlandkartegt</li>
    <li>qubes-core-vchan-xen</li>
    <li>ring-daemon</li>
    <li>rocm-opencl-icd</li>
    <li>rocm-opencl-runtime</li>
    <li>root5</li>
    <li>rxvt</li>
    <li>scribus</li>
    <li>shotgun</li>
    <li>sonic-pi</li>
    <li>spark</li>
    <li>split2flac</li>
    <li>spotifywm</li>
    <li>spring</li>
    <li>springLobby</li>
    <li>stepmania</li>
    <li>swift</li>
    <li>termplay</li>
    <li>tilix</li>
    <li>tlaps</li>
    <li>torchat</li>
    <li>truvari</li>
    <li>tvheadend</li>
    <li>twinkle</li>
    <li>unetbootin</li>
    <li>unicap</li>
    <li>vbam</li>
    <li>vcs</li>
    <li>vp</li>
    <li>winpdb</li>
    <li>woeusb</li>
    <li>xfitter</li>
    <li>xorg.libAppleWM</li>
    <li>xpdf</li>
    <li>xsw</li>
    <li>yaxg</li>
    <li>yosys-bluespec</li>
    <li>zandronum</li>
    <li>zgv</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/dbf0db8496adde9e1d9bcf2b4ce58964">bitkeeper</a></li>
  </ul>
</details>
<details>
  <summary>15803 packages skipped due to time constraints:</summary>
  <ul>
    <li>AusweisApp2</li>
    <li>CHOWTapeModel</li>
    <li>DisnixWebService</li>
    <li>EBTKS</li>
    <li>EmptyEpsilon</li>
    <li>Fabric (python38Packages.Fabric)</li>
    <li>MIDIVisualizer</li>
    <li>MMA</li>
    <li>OVMF</li>
    <li>OVMF-secureBoot</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>64 packages built successfully:</summary>
  <ul>
    <li>asciidoctor</li>
    <li>at-spi2-atk</li>
    <li>at-spi2-core</li>
    <li>atk (gnome.atk ,gnome2.atk)</li>
    <li>avahi</li>
    <li>cairo (gnome2.cairo)</li>
    <li>cups</li>
    <li>dbus</li>
    <li>dconf (gnome.dconf ,xfce.dconf)</li>
    <li>epoxy</li>
    <li>gdk-pixbuf</li>
    <li>gobject-introspection (gnome.gobject-introspection)</li>
    <li>libgudev (gnome.libgudev)</li>
    <li>libsoup (gnome.libsoup)</li>
    <li>pango (gnome2.pango)</li>
    <li>harfbuzz</li>
    <li>json-glib</li>
    <li>lasem</li>
    <li>lib2geom</li>
    <li>libass</li>
    <li>libglvnd</li>
    <li>libinput</li>
    <li>libva</li>
    <li>libvdpau</li>
    <li>libwacom</li>
    <li>libxkbcommon (libxkbcommon_8)</li>
    <li>python38Packages.pycairo</li>
    <li>python38Packages.pygobject3</li>
    <li>tome2</li>
    <li>xkeyboard_config (xorg.xkeyboardconfig)</li>
    <li>xlibsWrapper (xorg.xlibsWrapper)</li>
    <li>xorg.libICE</li>
    <li>xorg.libSM</li>
    <li>xorg.libX11</li>
    <li>xorg.libXScrnSaver</li>
    <li>xorg.libXau</li>
    <li>xorg.libXcomposite</li>
    <li>xorg.libXcursor</li>
    <li>xorg.libXdamage</li>
    <li>xorg.libXdmcp</li>
    <li>xorg.libXext</li>
    <li>xorg.libXfixes</li>
    <li>xorg.libXft</li>
    <li>xorg.libXi</li>
    <li>xorg.libXinerama</li>
    <li>xorg.libXmu</li>
    <li>xorg.libXpm</li>
    <li>xorg.libXrandr</li>
    <li>xorg.libXrender</li>
    <li>xorg.libXres</li>
    <li>xorg.libXt</li>
    <li>xorg.libXtst</li>
    <li>xorg.libXv</li>
    <li>xorg.libXvMC</li>
    <li>xorg.libXxf86vm</li>
    <li>xorg.libfontenc</li>
    <li>xorg.libxcb</li>
    <li>xorg.libxshmfence</li>
    <li>xorg.xcbutil</li>
    <li>xorg.xcbutilimage</li>
    <li>xorg.xcbutilkeysyms</li>
    <li>xorg.xcbutilrenderutil</li>
    <li>xorg.xcbutilwm</li>
    <li>xorg.xorgproto</li>
  </ul>
</details>
<details>
  <summary>40 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/servers/x11/xorg/default.nix:377:5:
```
    |
377 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/servers/x11/xorg/default.nix:489:5:
```
    |
489 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/servers/x11/xorg/default.nix:419:5:
```
    |
419 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/servers/x11/xorg/default.nix:433:5:
```
    |
433 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/servers/x11/xorg/default.nix:349:5:
```
    |
349 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/servers/x11/xorg/default.nix:531:5:
```
    |
531 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/servers/x11/xorg/default.nix:503:5:
```
    |
503 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/servers/x11/xorg/default.nix:321:5:
```
    |
321 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/servers/x11/xorg/default.nix:571:5:
```
    |
571 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/servers/x11/xorg/default.nix:167:5:
```
    |
167 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/servers/x11/xorg/default.nix:517:5:
```
    |
517 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/servers/x11/xorg/default.nix:279:5:
```
    |
279 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/servers/x11/xorg/default.nix:419:5:
```
    |
419 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/servers/x11/xorg/default.nix:84:5:
```
   |
84 |     meta.platforms = lib.platforms.unix;
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/servers/x11/xorg/default.nix:98:5:
```
   |
98 |     meta.platforms = lib.platforms.unix;
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/servers/x11/xorg/default.nix:517:5:
```
    |
517 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/servers/x11/xorg/default.nix:405:5:
```
    |
405 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/servers/x11/xorg/default.nix:433:5:
```
    |
433 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/servers/x11/xorg/default.nix:377:5:
```
    |
377 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/servers/x11/xorg/default.nix:585:5:
```
    |
585 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/servers/x11/xorg/default.nix:475:5:
```
    |
475 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/servers/x11/xorg/default.nix:98:5:
```
   |
98 |     meta.platforms = lib.platforms.unix;
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/servers/x11/xorg/default.nix:349:5:
```
    |
349 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/servers/x11/xorg/default.nix:405:5:
```
    |
405 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/servers/x11/xorg/default.nix:503:5:
```
    |
503 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/servers/x11/xorg/default.nix:321:5:
```
    |
321 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/servers/x11/xorg/default.nix:307:5:
```
    |
307 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/servers/x11/xorg/default.nix:265:5:
```
    |
265 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/servers/x11/xorg/default.nix:279:5:
```
    |
279 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/servers/x11/xorg/default.nix:447:5:
```
    |
447 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/servers/x11/xorg/default.nix:84:5:
```
   |
84 |     meta.platforms = lib.platforms.unix;
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/servers/x11/xorg/default.nix:585:5:
```
    |
585 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/servers/x11/xorg/default.nix:489:5:
```
    |
489 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/servers/x11/xorg/default.nix:531:5:
```
    |
531 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/servers/x11/xorg/default.nix:447:5:
```
    |
447 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/servers/x11/xorg/default.nix:571:5:
```
    |
571 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/servers/x11/xorg/default.nix:265:5:
```
    |
265 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/servers/x11/xorg/default.nix:167:5:
```
    |
167 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/servers/x11/xorg/default.nix:475:5:
```
    |
475 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/license-missing.md">license-missing</a>

Package is missing a license.

Near pkgs/servers/x11/xorg/default.nix:307:5:
```
    |
307 |     meta.platforms = lib.platforms.unix;
    |     ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

**Comment by Stunkymonkey** [comment]
i rebased it to `staging`

**Review by bbjubjub2494 — CHANGES_REQUESTED** [review]
`default.nix` is generated by `generate-expr-from-tarballs.pl` and starts with a comment saying "DO NOT EDIT". Please use that script instead. (I learned this the hard way) If you have the time, making it pname-version I think would be awesome.

**Comment by TredwellGit** [comment]
https://github.com/NixOS/nixpkgs/pull/122792

**Comment by TredwellGit** [comment]
https://github.com/NixOS/nixpkgs/pull/126367

**Pull request closed without merging**
