### PR TITLE
live555: 2024.05.30 -> 2024.06.26

### PR DESCRIPTION
**Pull request by AndersonTorres**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by JeremiahSecrist** [comment]
Result of `nixpkgs-review pr 332628` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>castero</li>
    <li>castero.dist</li>
  </ul>
</details>
<details>
  <summary>87 packages built:</summary>
  <ul>
    <li>anilibria-winmaclinux</li>
    <li>arcan</li>
    <li>arcan-all-wrapped</li>
    <li>arcan-wrapped</li>
    <li>arcan.dev</li>
    <li>arcan.lib</li>
    <li>arcan.man</li>
    <li>cat9-wrapped</li>
    <li>deepin.deepin-music</li>
    <li>deepin.deepin-voice-note</li>
    <li>durden-wrapped</li>
    <li>eaglemode</li>
    <li>kaffeine</li>
    <li>kdePackages.elisa</li>
    <li>kdePackages.elisa.debug</li>
    <li>kdePackages.elisa.dev</li>
    <li>kdePackages.elisa.devtools</li>
    <li>kdePackages.kasts</li>
    <li>kdePackages.kasts.debug</li>
    <li>kdePackages.kasts.dev</li>
    <li>kdePackages.kasts.devtools</li>
    <li>kdePackages.phonon-vlc</li>
    <li>kdePackages.phonon-vlc.debug</li>
    <li>kdePackages.phonon-vlc.dev</li>
    <li>kdePackages.phonon-vlc.devtools</li>
    <li>kphotoalbum</li>
    <li>libsForQt5.elisa</li>
    <li>libsForQt5.elisa.dev</li>
    <li>libsForQt5.phonon-backend-vlc</li>
    <li>libvlc</li>
    <li>live555</li>
    <li>megaglest</li>
    <li>minitube</li>
    <li>obs-studio</li>
    <li>obs-studio-plugins.advanced-scene-switcher</li>
    <li>obs-studio-plugins.droidcam-obs</li>
    <li>obs-studio-plugins.input-overlay</li>
    <li>obs-studio-plugins.looking-glass-obs</li>
    <li>obs-studio-plugins.obs-3d-effect</li>
    <li>obs-studio-plugins.obs-backgroundremoval</li>
    <li>obs-studio-plugins.obs-command-source</li>
    <li>obs-studio-plugins.obs-composite-blur</li>
    <li>obs-studio-plugins.obs-freeze-filter</li>
    <li>obs-studio-plugins.obs-gradient-source</li>
    <li>obs-studio-plugins.obs-gstreamer</li>
    <li>obs-studio-plugins.obs-hyperion</li>
    <li>obs-studio-plugins.obs-livesplit-one</li>
    <li>obs-studio-plugins.obs-move-transition</li>
    <li>obs-studio-plugins.obs-multi-rtmp</li>
    <li>obs-studio-plugins.obs-mute-filter</li>
    <li>obs-studio-plugins.obs-ndi</li>
    <li>obs-studio-plugins.obs-nvfbc</li>
    <li>obs-studio-plugins.obs-pipewire-audio-capture</li>
    <li>obs-studio-plugins.obs-replay-source</li>
    <li>obs-studio-plugins.obs-rgb-levels-filter</li>
    <li>obs-studio-plugins.obs-scale-to-sound</li>
    <li>obs-studio-plugins.obs-shaderfilter</li>
    <li>obs-studio-plugins.obs-source-clone</li>
    <li>obs-studio-plugins.obs-source-record</li>
    <li>obs-studio-plugins.obs-source-switcher</li>
    <li>obs-studio-plugins.obs-teleport</li>
    <li>obs-studio-plugins.obs-text-pthread</li>
    <li>obs-studio-plugins.obs-transition-table</li>
    <li>obs-studio-plugins.obs-tuna</li>
    <li>obs-studio-plugins.obs-vaapi</li>
    <li>obs-studio-plugins.obs-vertical-canvas</li>
    <li>obs-studio-plugins.obs-vintage-filter</li>
    <li>obs-studio-plugins.obs-vkcapture</li>
    <li>obs-studio-plugins.obs-webkitgtk</li>
    <li>obs-studio-plugins.obs-websocket</li>
    <li>obs-studio-plugins.waveform</li>
    <li>obs-studio-plugins.wlrobs</li>
    <li>pipeworld-wrapped</li>
    <li>prio-wrapped</li>
    <li>pympress</li>
    <li>pympress.dist</li>
    <li>python311Packages.python-vlc</li>
    <li>python311Packages.python-vlc.dist</li>
    <li>python312Packages.python-vlc</li>
    <li>python312Packages.python-vlc.dist</li>
    <li>reaper</li>
    <li>strawberry</li>
    <li>strawberry-qt6</li>
    <li>vlc</li>
    <li>vlc-bittorrent</li>
    <li>wtwitch</li>
    <li>xarcan</li>
  </ul>
</details>

**Comment by JeremiahSecrist** [comment]
```
error: builder for '/nix/store/hcnjzb575xkg3bb5981yidf0sdddshzc-castero-0.9.5.drv' failed with exit code 139;
       last 10 log lines:
       >   File "/nix/store/hmx1fgrr96wkr5sjdjcx9sr4nary39f0-python3.12-pluggy-1.5.0/lib/python3.12/site-packages/pluggy/_hooks.py", line 513 in __call__
       >   File "/nix/store/fpyc2jjhp59fjd2vmks7kih8421zsmqc-python3.12-pytest-8.2.2/lib/python3.12/site-packages/_pytest/config/__init__.py", line 178 in main
       >   File "/nix/store/fpyc2jjhp59fjd2vmks7kih8421zsmqc-python3.12-pytest-8.2.2/lib/python3.12/site-packages/_pytest/config/__init__.py", line 206 in console_main
       >   File "/nix/store/fpyc2jjhp59fjd2vmks7kih8421zsmqc-python3.12-pytest-8.2.2/lib/python3.12/site-packages/pytest/__main__.py", line 7 in <module>
       >   File "<frozen runpy>", line 88 in _run_code
       >   File "<frozen runpy>", line 198 in _run_module_as_main
       >
       > Extension modules: greenlet._greenlet, zope.interface._zope_interface_coptimizations, gevent.libev.corecext, gevent._gevent_c_greenlet_primitives, gevent._gevent_c_hub_local, gevent._gevent_c_waiter, gevent._gevent_c_hub_primitives, gevent._gevent_c_ident, gevent._gevent_cgreenlet, gevent._gevent_c_abstract_linkable, gevent._gevent_cevent, gevent._gevent_cqueue, _cffi_backend, gevent._gevent_c_semaphore, gevent._gevent_c_imap, lxml._elementpath, lxml.etree (total: 17)
       > /nix/store/0mbl9d00sgnqcw6cli8lbn53nw4hlb0s-pytest-check-hook/nix-support/setup-hook: line 53:   281 Segmentation fault      (core dumped) /nix/store/l014xp1qxdl6gim3zc0jv3mpxhbp346s-python3-3.12.4/bin/python3.12 -m pytest -k "not test_datafile_download" tests
       > /nix/store/1r32fki5z5ivgaikgh8pq0r6vz3b0jpj-stdenv-linux/setup: line 1655: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/hcnjzb575xkg3bb5981yidf0sdddshzc-castero-0.9.5.drv'.

```

**Comment by AndersonTorres** [comment]
@JeremiahSecrist I have found the same error with the current Master branch.

**Comment by JeremiahSecrist** [comment]
@AndersonTorres  looks like ill check and see if this is a known issue or if i'll need to raise one.

**Comment by JeremiahSecrist** [comment]
I'm going to assume emulation station is not broken because of your change here. :laughing: 
Result of `nixpkgs-review pr 332628` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>emulationstation</li>
  </ul>
</details>
<details>
  <summary>88 packages built:</summary>
  <ul>
    <li>anilibria-winmaclinux</li>
    <li>arcan</li>
    <li>arcan-all-wrapped</li>
    <li>arcan-wrapped</li>
    <li>arcan.dev</li>
    <li>arcan.lib</li>
    <li>arcan.man</li>
    <li>castero</li>
    <li>castero.dist</li>
    <li>cat9-wrapped</li>
    <li>deepin.deepin-music</li>
    <li>deepin.deepin-voice-note</li>
    <li>durden-wrapped</li>
    <li>eaglemode</li>
    <li>kaffeine</li>
    <li>kdePackages.elisa</li>
    <li>kdePackages.elisa.debug</li>
    <li>kdePackages.elisa.dev</li>
    <li>kdePackages.elisa.devtools</li>
    <li>kdePackages.kasts</li>
    <li>kdePackages.kasts.debug</li>
    <li>kdePackages.kasts.dev</li>
    <li>kdePackages.kasts.devtools</li>
    <li>kdePackages.phonon-vlc</li>
    <li>kdePackages.phonon-vlc.debug</li>
    <li>kdePackages.phonon-vlc.dev</li>
    <li>kdePackages.phonon-vlc.devtools</li>
    <li>kphotoalbum</li>
    <li>libsForQt5.elisa (plasma5Packages.elisa)</li>
    <li>libsForQt5.elisa.dev (plasma5Packages.elisa.dev)</li>
    <li>libsForQt5.phonon-backend-vlc (plasma5Packages.phonon-backend-vlc)</li>
    <li>libvlc</li>
    <li>live555</li>
    <li>megaglest</li>
    <li>minitube</li>
    <li>obs-studio</li>
    <li>obs-studio-plugins.advanced-scene-switcher</li>
    <li>obs-studio-plugins.droidcam-obs</li>
    <li>obs-studio-plugins.input-overlay</li>
    <li>obs-studio-plugins.looking-glass-obs</li>
    <li>obs-studio-plugins.obs-3d-effect</li>
    <li>obs-studio-plugins.obs-backgroundremoval</li>
    <li>obs-studio-plugins.obs-command-source</li>
    <li>obs-studio-plugins.obs-composite-blur</li>
    <li>obs-studio-plugins.obs-freeze-filter</li>
    <li>obs-studio-plugins.obs-gradient-source</li>
    <li>obs-studio-plugins.obs-gstreamer</li>
    <li>obs-studio-plugins.obs-hyperion</li>
    <li>obs-studio-plugins.obs-livesplit-one</li>
    <li>obs-studio-plugins.obs-move-transition</li>
    <li>obs-studio-plugins.obs-multi-rtmp</li>
    <li>obs-studio-plugins.obs-mute-filter</li>
    <li>obs-studio-plugins.obs-nvfbc</li>
    <li>obs-studio-plugins.obs-pipewire-audio-capture</li>
    <li>obs-studio-plugins.obs-replay-source</li>
    <li>obs-studio-plugins.obs-rgb-levels-filter</li>
    <li>obs-studio-plugins.obs-scale-to-sound</li>
    <li>obs-studio-plugins.obs-shaderfilter</li>
    <li>obs-studio-plugins.obs-source-clone</li>
    <li>obs-studio-plugins.obs-source-record</li>
    <li>obs-studio-plugins.obs-source-switcher</li>
    <li>obs-studio-plugins.obs-teleport</li>
    <li>obs-studio-plugins.obs-text-pthread</li>
    <li>obs-studio-plugins.obs-transition-table</li>
    <li>obs-studio-plugins.obs-tuna</li>
    <li>obs-studio-plugins.obs-vaapi</li>
    <li>obs-studio-plugins.obs-vertical-canvas</li>
    <li>obs-studio-plugins.obs-vintage-filter</li>
    <li>obs-studio-plugins.obs-vkcapture</li>
    <li>obs-studio-plugins.obs-webkitgtk</li>
    <li>obs-studio-plugins.obs-websocket</li>
    <li>obs-studio-plugins.waveform</li>
    <li>obs-studio-plugins.wlrobs</li>
    <li>pipeworld-wrapped</li>
    <li>prio-wrapped</li>
    <li>pympress</li>
    <li>pympress.dist</li>
    <li>python311Packages.python-vlc</li>
    <li>python311Packages.python-vlc.dist</li>
    <li>python312Packages.python-vlc</li>
    <li>python312Packages.python-vlc.dist</li>
    <li>reaper</li>
    <li>strawberry (strawberry-qt5)</li>
    <li>strawberry-qt6</li>
    <li>vlc</li>
    <li>vlc-bittorrent</li>
    <li>wtwitch</li>
    <li>xarcan</li>
  </ul>
</details>

**Review by JeremiahSecrist — APPROVED** [review]
LGTM

**Comment by AndersonTorres** [comment]
Emulationstation is broken because it uses an outdated and insecure library.

**Review by thiagokokada — APPROVED** [review]

**Pull request merged**
