### PR TITLE
ollama: 0.1.7 -> 0.1.9

### PR DESCRIPTION
**Pull request by ktaf**
## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by elohmeier** [comment]
```
go: downloading github.com/go-playground/locales v0.14.1
go: downloading golang.org/x/arch v0.3.0
go: downloading github.com/chenzhuoyu/base64x v0.0.0-20221115062448-fe3a3abad311
go: downloading github.com/klauspost/cpuid/v2 v2.2.4
go: downloading github.com/twitchyliquid64/golang-asm v0.15.1
installing
error: hash mismatch in fixed-output derivation '/nix/store/5rzszc1llc1a8xlsqmlyrcdi9vlg6y5d-ollama-0.1.9-go-modules.drv':
         specified: sha256-Qt5QVqRkwK61BJPVhFWtox6b9E8BpAIseNB0yhh+/90=
            got:    sha256-NrRj+YmsNgehxgPL/fzG4sH1CCt42KMkhpNyifiyDWM=
error: 1 dependencies of derivation '/nix/store/jsbfy28bng85ljqcfia9kc04h297gq1p-ollama-0.1.9.drv' failed to build
```

Please update the modules hash.

**Comment by ktaf** [comment]
> ```
> go: downloading github.com/go-playground/locales v0.14.1
> go: downloading golang.org/x/arch v0.3.0
> go: downloading github.com/chenzhuoyu/base64x v0.0.0-20221115062448-fe3a3abad311
> go: downloading github.com/klauspost/cpuid/v2 v2.2.4
> go: downloading github.com/twitchyliquid64/golang-asm v0.15.1
> installing
> error: hash mismatch in fixed-output derivation '/nix/store/5rzszc1llc1a8xlsqmlyrcdi9vlg6y5d-ollama-0.1.9-go-modules.drv':
>          specified: sha256-Qt5QVqRkwK61BJPVhFWtox6b9E8BpAIseNB0yhh+/90=
>             got:    sha256-NrRj+YmsNgehxgPL/fzG4sH1CCt42KMkhpNyifiyDWM=
> error: 1 dependencies of derivation '/nix/store/jsbfy28bng85ljqcfia9kc04h297gq1p-ollama-0.1.9.drv' failed to build
> ```
> 
> Please update the modules hash.
Could you please guide me how?
Package hash I fetched it by this:
nix hash to-sri --type sha256 $(nix-prefetch-url --unpack https://github.com/jmorganca/ollama/archive/refs/tags/v0.1.9.tar.gz)
path is '/nix/store/az3knffzai5ldzkj1rqyn0wrrapra7p1-v0.1.9.tar.gz'
sha256-pc3lDBh3e49k9PKe8cEvjcHvDuTyhRjTulxReRqqu7s=

How should I check module hash?!

**Comment by ktaf** [comment]
> ```
> go: downloading github.com/go-playground/locales v0.14.1
> go: downloading golang.org/x/arch v0.3.0
> go: downloading github.com/chenzhuoyu/base64x v0.0.0-20221115062448-fe3a3abad311
> go: downloading github.com/klauspost/cpuid/v2 v2.2.4
> go: downloading github.com/twitchyliquid64/golang-asm v0.15.1
> installing
> error: hash mismatch in fixed-output derivation '/nix/store/5rzszc1llc1a8xlsqmlyrcdi9vlg6y5d-ollama-0.1.9-go-modules.drv':
>          specified: sha256-Qt5QVqRkwK61BJPVhFWtox6b9E8BpAIseNB0yhh+/90=
>             got:    sha256-NrRj+YmsNgehxgPL/fzG4sH1CCt42KMkhpNyifiyDWM=
> error: 1 dependencies of derivation '/nix/store/jsbfy28bng85ljqcfia9kc04h297gq1p-ollama-0.1.9.drv' failed to build
> ```
> 
> Please update the modules hash.

Done.

**Comment by marcusramberg** [comment]
> > ```
> > go: downloading github.com/go-playground/locales v0.14.1
> > go: downloading golang.org/x/arch v0.3.0
> > go: downloading github.com/chenzhuoyu/base64x v0.0.0-20221115062448-fe3a3abad311
> > go: downloading github.com/klauspost/cpuid/v2 v2.2.4
> > go: downloading github.com/twitchyliquid64/golang-asm v0.15.1
> > installing
> > error: hash mismatch in fixed-output derivation '/nix/store/5rzszc1llc1a8xlsqmlyrcdi9vlg6y5d-ollama-0.1.9-go-modules.drv':
> >          specified: sha256-Qt5QVqRkwK61BJPVhFWtox6b9E8BpAIseNB0yhh+/90=
> >             got:    sha256-NrRj+YmsNgehxgPL/fzG4sH1CCt42KMkhpNyifiyDWM=
> > error: 1 dependencies of derivation '/nix/store/jsbfy28bng85ljqcfia9kc04h297gq1p-ollama-0.1.9.drv' failed to build
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please update the modules hash.
> 
> Done.

I see your fix also added a merge commit. You should probably rebase against master instead.

**Comment by ktaf** [comment]
> > > ```
> > > go: downloading github.com/go-playground/locales v0.14.1
> > > go: downloading golang.org/x/arch v0.3.0
> > > go: downloading github.com/chenzhuoyu/base64x v0.0.0-20221115062448-fe3a3abad311
> > > go: downloading github.com/klauspost/cpuid/v2 v2.2.4
> > > go: downloading github.com/twitchyliquid64/golang-asm v0.15.1
> > > installing
> > > error: hash mismatch in fixed-output derivation '/nix/store/5rzszc1llc1a8xlsqmlyrcdi9vlg6y5d-ollama-0.1.9-go-modules.drv':
> > >          specified: sha256-Qt5QVqRkwK61BJPVhFWtox6b9E8BpAIseNB0yhh+/90=
> > >             got:    sha256-NrRj+YmsNgehxgPL/fzG4sH1CCt42KMkhpNyifiyDWM=
> > > error: 1 dependencies of derivation '/nix/store/jsbfy28bng85ljqcfia9kc04h297gq1p-ollama-0.1.9.drv' failed to build
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Please update the modules hash.
> > 
> > 
> > Done.
> 
> I see your fix also added a merge commit. You should probably rebase against master instead.

Rebased!

**Comment by ethanthoma** [comment]
Any thoughts on updating to [v0.1.10](https://github.com/jmorganca/ollama/releases/tag/v0.1.10) instead?

**Comment by ktaf** [comment]
Yes, but maybe after merging this?

**Comment by kirillrdy** [comment]
I get a build error when running nixpkgs-review

```
error: builder for '/nix/store/0sy8qxjyjh70lzip16gb27dmb7j0nilw-llama-cpp-1483.drv' failed with exit code 1;
       last 10 log lines:
       > -- Checking for module 'openblas'
       > --   No package 'openblas' found
       > CMake Error at /nix/store/vnhl4zdy7igx9gd3q1d548vwzz15a9ma-cmake-3.27.7/share/cmake-3.27/Modules/FindPkgConfig.cmake:607 (message):
       >   A required package was not found
       > Call Stack (most recent call first):
       >   /nix/store/vnhl4zdy7igx9gd3q1d548vwzz15a9ma-cmake-3.27.7/share/cmake-3.27/Modules/FindPkgConfig.cmake:829 (_pkg_check_modules_internal)
       >   CMakeLists.txt:193 (pkg_check_modules)
       >
       > 
       > -- Configuring incomplete, errors occurred!
       For full logs, run 'nix log /nix/store/0sy8qxjyjh70lzip16gb27dmb7j0nilw-llama-cpp-1483.drv'.
```

**Comment by pbsds** [comment]
Fixing [the build failure](https://hydra.nixos.org/build/241148122) would be gainful to the zero hydra fail campaign.

**Comment by pbsds** [comment]
Seems to be fixed in #268449. LGTM

**Comment by TanvirOnGH** [comment]
0.1.11 is out https://github.com/jmorganca/ollama/releases/tag/v0.1.11

**Pull request closed without merging**
