### PR TITLE
python3Packages.librosa: 0.10.1 -> 0.10.2-pre.1474631

### LINKED ISSUE #306859: Build failure: pitivi, python311Packages.librosa
### Steps To Reproduce

1. Be in nixos-unstable chanale
2. Run `nix-shell -p pitivi`

### Build log
https://paste.dismail.de/?6a40f862893c155b#F4P875mfQBHBDCaepTDseEU9CRmfNhy9gbfh55tyGaSC
``` python
Running phase: pytestCheckPhase
Executing pytestCheckPhase
============================= test session starts ==============================
platform linux -- Python 3.11.9, pytest-8.1.1, pluggy-1.4.0
Matplotlib: 3.8.3
Freetype: 2.13.2
rootdir: /build/source
configfile: setup.cfg
plugins: mpl-0.16.1
collected 12910 items / 1 error / 48 deselected / 12862 selected               

==================================== ERRORS ====================================
____________________ ERROR collecting tests/test_filters.py ____________________
tests/test_filters.py:486: in <module>
    "pre_win", [scipy.signal.hann(16), list(scipy.signal.hann(16)), [1, 1, 1]]
E   AttributeError: module 'scipy.signal' has no attribute 'hann'
=========================== short test summary info ============================
ERROR tests/test_filters.py - AttributeError: module 'scipy.signal' has no attribute 'hann'
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
================= 48 deselected, 4 warnings, 1 error in 16.00s =================
/nix/store/9wnvhjyxjykwn5y06xc9a2h8rs5fbfia-stdenv-linux/setup: line 1579: pop_var_context: head of shell_variables not a function context
error: builder for '/nix/store/1ps9paiq7ivs210lgmnzqnnkhaz92agp-python3.11-librosa-0.10.1.drv' failed with exit code 2;
       last 10 log lines:
       > ==================================== ERRORS ====================================
       > ____________________ ERROR collecting tests/test_filters.py ____________________
       > tests/test_filters.py:486: in <module>
       >     "pre_win", [scipy.signal.hann(16), list(scipy.signal.hann(16)), [1, 1, 1]]
       > E   AttributeError: module 'scipy.signal' has no attribute 'hann'
       > =========================== short test summary info ============================
       > ERROR tests/test_filters.py - AttributeError: module 'scipy.signal' has no attribute 'hann'
       > !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
       > ================= 48 deselected, 4 warnings, 1 error in 16.00s =================
       > /nix/store/9wnvhjyxjykwn5y06xc9a2h8rs5fbfia-stdenv-linux/setup: line 1579: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix-store -l /nix/store/1ps9paiq7ivs210lgmnzqnnkhaz92agp-python3.11-librosa-0.10.1.drv'.
error: 1 dependencies of derivation '/nix/store/8bcip9c0504qwnhvx86b8qpcgj4yywv7-pitivi-2023.03.drv' failed to build

```

### Notify maintainers

@GuillaumeDesforges
@AkechiShiro

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.28, NixOS, 24.05 (Uakari), 24.05pre615930.572af610f615`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - channels(suliman): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by GuillaumeDesforges**
Update `librosa` to 0.10.2-pre.1474631, fixes #306859

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Aleksanaa** [comment]
Sorry we don't name version in such a way. Use `0.10.1-unstable-2024-mm-dd`

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 308533` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>piper-train</li>
    <li>piper-train.dist</li>
    <li>tts</li>
    <li>tts.dist</li>
  </ul>
</details>
<details>
  <summary>4 packages failed to build:</summary>
  <ul>
    <li>python311Packages.pyannote-audio</li>
    <li>python311Packages.pyannote-audio.dist</li>
    <li>python311Packages.torch-audiomentations</li>
    <li>python311Packages.torch-audiomentations.dist</li>
  </ul>
</details>
<details>
  <summary>13 packages built:</summary>
  <ul>
    <li>pianotrans</li>
    <li>pianotrans.dist</li>
    <li>pitivi</li>
    <li>python311Packages.asteroid-filterbanks</li>
    <li>python311Packages.asteroid-filterbanks.dist</li>
    <li>python311Packages.librosa</li>
    <li>python311Packages.librosa.dist</li>
    <li>python311Packages.piano-transcription-inference</li>
    <li>python311Packages.piano-transcription-inference.dist</li>
    <li>python311Packages.tinygrad</li>
    <li>python311Packages.tinygrad.dist</li>
    <li>python311Packages.torchlibrosa</li>
    <li>python311Packages.torchlibrosa.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 308533` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>piper-train</li>
    <li>piper-train.dist</li>
  </ul>
</details>
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>python311Packages.pyannote-audio</li>
    <li>python311Packages.pyannote-audio.dist</li>
    <li>python311Packages.tinygrad</li>
    <li>python311Packages.tinygrad.dist</li>
    <li>python311Packages.torch-audiomentations</li>
    <li>python311Packages.torch-audiomentations.dist</li>
  </ul>
</details>
<details>
  <summary>11 packages built:</summary>
  <ul>
    <li>pianotrans</li>
    <li>pianotrans.dist</li>
    <li>pitivi</li>
    <li>python311Packages.asteroid-filterbanks</li>
    <li>python311Packages.asteroid-filterbanks.dist</li>
    <li>python311Packages.librosa</li>
    <li>python311Packages.librosa.dist</li>
    <li>python311Packages.piano-transcription-inference</li>
    <li>python311Packages.piano-transcription-inference.dist</li>
    <li>python311Packages.torchlibrosa</li>
    <li>python311Packages.torchlibrosa.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 308533` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>16 packages failed to build:</summary>
  <ul>
    <li>pianotrans</li>
    <li>pianotrans.dist</li>
    <li>python311Packages.asteroid-filterbanks</li>
    <li>python311Packages.asteroid-filterbanks.dist</li>
    <li>python311Packages.librosa</li>
    <li>python311Packages.librosa.dist</li>
    <li>python311Packages.piano-transcription-inference</li>
    <li>python311Packages.piano-transcription-inference.dist</li>
    <li>python311Packages.pyannote-audio</li>
    <li>python311Packages.pyannote-audio.dist</li>
    <li>python311Packages.tinygrad</li>
    <li>python311Packages.tinygrad.dist</li>
    <li>python311Packages.torch-audiomentations</li>
    <li>python311Packages.torch-audiomentations.dist</li>
    <li>python311Packages.torchlibrosa</li>
    <li>python311Packages.torchlibrosa.dist</li>
  </ul>
</details>

**Comment by GuillaumeDesforges** [comment]
Closing in favor of https://github.com/NixOS/nixpkgs/pull/308525

**Pull request closed without merging**
