### PR TITLE
musl-utils: init at 1.1.20

### PR DESCRIPTION
**Pull request by tathougies**
###### Motivation for this change

musl-utils: init at 1.1.20

Glibc provides several utilities that must exist to have a bootable system. Musl is an alternative C library ideal for embedded systems. However, it does not contain these utilities. Alpine Linux is a musl-based distribution that maintains versions of these utilities for Musl.

This is part of work I've started to get NixOS building with Musl for my ODROID-XU4 ARM device. I've confirmed these utilities work on the device, but you won't be able to build NixOS for this device with just this change. I hope this change is welcome, and I would like to bring mainline nixpkgs up to par with my branch.

I'm happy to maintain this as well!

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- ~~[ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`~~
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by symphorien** [comment]
It seems iconv is already included in nixpkgs's musl: https://github.com/NixOS/nixpkgs/pull/39486
cc @dtzWill

**Comment by matthewbauer** [comment]
The networking change looks good and can probably get merged right away.

But on "musl-utils" I think it makes sense to use ```pkgs.getent``` and ```pkgs.getconf``` instead in the default path. These should give you the right package based on what libc you are targeting:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/unix-tools.nix#L61-L70

I could be wrong, but I don't think there is any reason for iconv to be included in the default path. We probably need to also add a ```ldd``` package based on what libc you want (can use similar logic to libcChooser).

**Comment by tathougies** [comment]
So if we use pkgs.getent, pkgs.getconf, we wouldn't need to have any conditional in the system path?

I'll split out the networking change.

**Comment by tathougies** [comment]
Opening a new pull request to lessen the scope.

**Pull request closed without merging**
