### PR TITLE
php.packages.laravel-installer: init at 4.2.7

### PR DESCRIPTION
**Pull request by aanderse**
###### Motivation for this change
- package not currently included in `nixpkgs`
- as a sysadmin it would be helpful to me if i could provide my team this tool through `nixpkgs`

###### Questions
- are we accepting `composer2nix` packages in `nixpkgs` now? currently we have [bookstack](https://github.com/NixOS/nixpkgs/blob/nixos-21.05/pkgs/servers/web-apps/bookstack/default.nix#L28)
- how do i properly set the `name`, `pname`, and `version` for a `composer2nix` package?

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 128796` at 736f2b68 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>php74Packages.laravel</li>
    <li>php80Packages.laravel</li>
  </ul>
</details>

**Comment by talyz** [comment]
Nice! This could probably be useful to our web team as well :) Could we maybe call this package something more distinguishing, like `laravel-installer`, since laravel has so many parts?

For now I'd say doing things like they're done for `bookstack` is good enough, but we should provide infrastructure for `composer2nix` packages in the future to avoid all this duplication. I know both me and @etu have prototype branches for this; maybe we should organize a meeting to plan the future of `composer` packaging for `nixpkgs`?

**Comment by aanderse** [comment]
Package renamed :+1: 

I'm looking forward to see what @etu and you have cooked up for `composer2nix`! Count me in.

**Comment by aanderse** [comment]
@ofborg eval

**Comment by lukegb** [comment]
@ofborg build php.packages.laravel-installer

**Comment by aanderse** [comment]
@talyz good to merge?

**Comment by drupol** [comment]
What is the status of this ?

**Comment by aanderse** [comment]
I'm no longer working with `laravel` developers so I guess I don't want this anymore.

Anyone who wants this is free to take the code and run with it.

**Pull request closed without merging**
