### PR TITLE
emacs-packages: elpy init at 1.9.0 + deps (yasnippet, etc...)

### PR DESCRIPTION
**Pull request by ardumont**
Hello,
# Main package
- elpy: init at 1.9.0 
# Dependencies
- find-file-in-project: init at 3.5
- highlight-indentation: init at 0.7.0
- pyvenv: init at 1.7
- yasnippet: init at 0.8.1
# Builds ok:

``` sh
# tony at corellia in ~/repo/perso/nixpkgs on git:init-elpy+deps o [14:08:14]
$ nix-build -A emacs24PackagesNg.yasnippet -A emacs24PackagesNg.highlight-indentation -A emacs24PackagesNg.company -A emacs24PackagesNg.find-file-in-project -A emacs24PackagesNg.pyvenv -A emacs24PackagesNg.elpy
/nix/store/ngvlx7ki3x70pjfphr6x7i4p5zpgw275-emacs-yasnippet-0.8.1
/nix/store/s9gp9232r18cqr1q5ypry1i3yx9w92ia-emacs-highlight-indentation-0.7.0
/nix/store/2bki2d0102v2g4cdrf4d6ydp3x7yxv58-emacs-company-0.8.12
/nix/store/rdhq26ma66pgx07raxmpmmxl0lykwl33-emacs-find-file-in-project-3.5
/nix/store/y87rsa72km7mf1yi5xmigph8xj6l45c4-emacs-pyvenv-1.7
/nix/store/fpy7x6kmif5fypf2jcaaks83qxg7jw4r-emacs-elpy-1.9.0

# tony at corellia in ~/repo/perso/nixpkgs on git:init-elpy+deps o [14:29:54]
$ tree result*
result
├── nix-support
│   └── setup-hook
└── share
└── emacs
└── site-lisp
└── elpa
└── yasnippet-0.8.1
├── yasnippet-autoloads.el
├── yasnippet-autoloads.el~
├── yasnippet-debug.el
├── yasnippet-debug.elc
├── yasnippet.el
├── yasnippet.elc
├── yasnippet-pkg.el
├── yasnippet-tests.el
└── yasnippet-tests.elc

result-2
├── nix-support
│   └── setup-hook
└── share
└── emacs
└── site-lisp
└── elpa
└── highlight-indentation-0.7.0
├── highlight-indentation-autoloads.el
├── highlight-indentation-autoloads.el~
├── highlight-indentation.el
├── highlight-indentation.elc
├── highlight-indentation-pkg.el
└── highlight-indentation-pkg.elc

result-3... company is not needed for check as this already exists

result-4
├── nix-support
│   └── setup-hook
└── share
└── emacs
└── site-lisp
└── elpa
└── find-file-in-project-3.5
├── find-file-in-project-autoloads.el
├── find-file-in-project-autoloads.el~
├── find-file-in-project.el
├── find-file-in-project.elc
├── find-file-in-project-pkg.el
└── find-file-in-project-pkg.elc

result-5
├── nix-support
│   └── setup-hook
└── share
└── emacs
└── site-lisp
└── elpa
└── pyvenv-1.7
├── pyvenv-autoloads.el
├── pyvenv-autoloads.el~
├── pyvenv.el
├── pyvenv.elc
├── pyvenv-pkg.el
└── pyvenv-pkg.elc

result-6
├── nix-support
│   ├── propagated-native-build-inputs
│   ├── propagated-user-env-packages
│   └── setup-hook
└── share
└── emacs
└── site-lisp
└── elpa
└── elpy-1.9.0
├── elpy-autoloads.el
├── elpy-autoloads.el~
├── elpy.el
├── elpy.elc
├── elpy-pkg.el
├── elpy-refactor.el
└── elpy-refactor.elc

36 directories, 97 files
```

Once installed, the package is found in the user's store:

``` sh
# tony at corellia in ~ [14:31:37]
$ f ~/.nix-profile/ elpy | grep emacs
/home/tony/.nix-profile/share/emacs/site-lisp/elpa/elpy-1.9.0

# tony at corellia in ~ [14:31:50]
$ f ~/.nix-profile/ elpy | grep emacs
/home/tony/.nix-profile/share/emacs/site-lisp/elpa/elpy-1.9.0

# tony at corellia in ~ [14:31:53]
$ f ~/.nix-profile/ yasnippet | grep emacs
/home/tony/.nix-profile/share/emacs/site-lisp/elpa/yasnippet-0.8.1

# tony at corellia in ~ [14:32:01]
$ f ~/.nix-profile/ find-file-in-project | grep emacs
/home/tony/.nix-profile/share/emacs/site-lisp/elpa/find-file-in-project-3.5

# tony at corellia in ~ [14:32:08]
$ f ~/.nix-profile/ pyvenv | grep emacs
/home/tony/.nix-profile/share/emacs/site-lisp/elpa/pyvenv-1.7

# tony at corellia in ~ [14:32:19]
$ f ~/.nix-profile/ highlight-indentation | grep emacs
/home/tony/.nix-profile/share/emacs/site-lisp/elpa/highlight-indentation-0.7.0
```

Once emacs's started, the package is detected as installed by emacs' M-x package-list-packages.
Also, `M-x elpy-config` triggers itself.

So everything is ok.

Thanks @oxij for the troubleshoot help.

Cheers,

### CODE REVIEW

**Comment by oxij** [comment]
I would start by trying to patch `elpy` (checkout its repo to disk at
the required revision, edit the files there, do `git diff > elpy.patch`,
and add that `patches = [ /path/to/repo/elpy.patch ]`; with this you
won't need to fix sha256 hash after every single change) so that it
would ask for the newer versions of the required packages. Then I would
check that it actually works and, in case it it isn't, I would duplicate
the required packages in `emacs-packages.nix` with the required versions
one by one, starting with those whose versions are most different from
the required ones, until it starts working as expected. Then I would put
that `elpy.patch` into nixpkgs or rewrite it as a `patchPhase` directly
into the expression.

**Comment by ardumont** [comment]
@oxij Thanks for the hint! Will definitely try that.

Cheers,

**Comment by ardumont** [comment]
Acting on the suggestion, i've reworked the elpy derivation but hit yet again a new barrier.

```nix
  elpy = melpaBuild rec {
    pname   = "elpy";
    version = "1.9.0";
    src = fetchFromGitHub {
      owner  = "jorgenschaefer";
      repo   = pname;
      rev    = "39ea47c73f040ce8dcc1c2d2639ebc0eb57ab8c8";
      sha256 = "0q3av1qv4m6aj4bil608f688hjpr5px8zqnnrdqx784nz98rpjrs";
    };

    patchPhase = ''
      substituteInPlace elpy.el \
          --replace "company \"0.8.2\"" "company \"${company.version}\"" \
          --replace "find-file-in-project \"3.3\"" "find-file-in-project \"${find-file-in-project.version}\"" \
          --replace "highlight-indentation \"0.5.0\"" "highlight-indentation \"${highlight-indentation.version}\"" \
          --replace "pyvenv \"1.3\"" "pyvenv \"${pyvenv.version}\"" \
          --replace "yasnippet \"0.8.0\"" "yasnippet \"${yasnippet.version}\""
      substituteInPlace elpy-pkg.el \
          --replace "company \"0.8.2\"" "company \"${company.version}\"" \
          --replace "find-file-in-project \"3.3\"" "find-file-in-project \"${find-file-in-project.version}\"" \
          --replace "highlight-indentation \"0.5.0\"" "highlight-indentation \"${highlight-indentation.version}\"" \
          --replace "pyvenv \"1.3\"" "pyvenv \"${pyvenv.version}\"" \
          --replace "yasnippet \"0.8.0\"" "yasnippet \"${yasnippet.version}\""
    '';

    # debug purposes, do not commit
     packageRequires = [
       highlight-indentation company find-file-in-project pyvenv yasnippet
     ];

    meta = {
      description = "Emacs Python Development Environment";
      longDescription = ''
        Elpy is an Emacs package to bring powerful Python editing to Emacs.
        It combines a number of other packages, both written in Emacs Lisp as
        well as Python.
      '';
      license = gpl3Plus;
    };
  };

```

build output:
```sh
# tony at corellia in ~/repo/perso/nixpkgs on git:init-elpy+deps x [9:42:41]
$ nix-build -A emacs24PackagesNg.elpy
these derivations will be built:
/nix/store/lflzhzhmhp8wjdasirl6q2n4zrkcx0wz-emacs-elpy-1.9.0.drv
building path (s) ‘/nix/store/8hiyqp64ls8alnwrf9xvnvicawfpsr7i-emacs-elpy-1.9.0’
unpacking sources
unpacking source archive /nix/store/4d712m5ra20ky5j6dsgkdm0b37rdq8ml-elpy-39ea47c73f040ce8dcc1c2d2639ebc0eb57ab8c8-src
source root is elpy-39ea47c73f040ce8dcc1c2d2639ebc0eb57ab8c8-src
patching sources
configuring
no configure script, doing nothing
building

;;; elpy

Note: elpy :files spec is equivalent to the default.
/tmp/nix-build-emacs-elpy-1.9.0.drv-0/elpy-39ea47c73f040ce8dcc1c2d2639ebc0eb57ab8c8-src/elpy-pkg.el -> /tmp/nix-build-emacs-elpy-1.9.0.drv-0/elpy15347zrP/elpy-1.9.0/elpy-pkg.el
/tmp/nix-build-emacs-elpy-1.9.0.drv-0/elpy-39ea47c73f040ce8dcc1c2d2639ebc0eb57ab8c8-src/elpy-refactor.el -> /tmp/nix-build-emacs-elpy-1.9.0.drv-0/elpy15347zrP/elpy-1.9.0/elpy-refactor.el
/tmp/nix-build-emacs-elpy-1.9.0.drv-0/elpy-39ea47c73f040ce8dcc1c2d2639ebc0eb57ab8c8-src/elpy.el -> /tmp/nix-build-emacs-elpy-1.9.0.drv-0/elpy15347zrP/elpy-1.9.0/elpy.el
Wrote /tmp/nix-build-emacs-elpy-1.9.0.drv-0/elpy-39ea47c73f040ce8dcc1c2d2639ebc0eb57ab8c8-src/elpy-readme.txt
Built in 0.016s, finished at Fri Sep 25 07:42:43 2015
installing
Parsing tar file...
Parsing tar file...done
Package `highlight-indentation-0.7.0' is unavailable
builder for ‘/nix/store/lflzhzhmhp8wjdasirl6q2n4zrkcx0wz-emacs-elpy-1.9.0.drv’ failed with exit code 255
error: build of ‘/nix/store/lflzhzhmhp8wjdasirl6q2n4zrkcx0wz-emacs-elpy-1.9.0.drv’ failed
```

Somehow, the highlight-indentation required package to the right version, is not seen.
If I build highlight-indentation separately, it's ok though.

```sh
# tony at corellia in ~/repo/perso/nixpkgs on git:init-elpy+deps x [9:44:49]
$ nix-build -A emacs24PackagesNg.highlight-indentation
/nix/store/0pl51v3s7c0sdaki9j1ivwmv6xhqxm3r-emacs-Highlight-Indentation-for-Emacs-0.7.0

# tony at corellia in ~/repo/perso/nixpkgs on git:init-elpy+deps x [9:44:57]
$ grep Version result/share/emacs/site-lisp/highlight-indentation.el
;; Version: 0.7.0
```

Note: I use trivialBuild function for highlight-indentation derivation because melpaBuild rejects this package due to its repository name mismatching the mode name (a voluntary limitation in melpa's convention for the naming repository if I remember correctly). Could it be one reason?

What am I doing wrong or what did I possibly misunderstand?

Cheers,

**Comment by oxij** [comment]
1) In the future just push those changes into the branch, I had to copy-paste them by hand :(
2) I think this works: https://github.com/ardumont/nixpkgs/compare/init-elpy+deps...oxij:elpy-pull?expand=1

**Comment by ardumont** [comment]
@oxij Thanks!

> 1) In the future just push those changes into the branch, I had to copy-paste them by hand :(

Right!

2) I think this works: https://github.com/ardumont/nixpkgs/compare/init-elpy+deps...oxij:elpy-pull?expand=1

I confirm it works (still from build stand point).
The immediate difference i see between your tryouts and mine is that I used `melpaBuild` and `fetchFromGithub`... (here it's with `fetchurl`).
Still, many many thanks!

Off with testing runtime :D 

Cheers,

**Comment by oxij** [comment]
Nope, I renamed `highlight-indentation` and changed it to be built with
`melpa` builder. And dropped the copy-paste. As far as I could see I did
not change any `src`s.

**Comment by ardumont** [comment]
> Nope, I renamed `highlight-indentation` and changed it to be built with `melpa` builder. And dropped the copy-paste. 

Yes.

> As far as I could see I did not change any `src`s.

I did not say you changed anything in that regard.
I just explicited my assumption that my tryouts failed because of the use of `melpaBuild` and `fetchFromGithub` (which is not apparent on the commits because i squashed it), nothing else.

> I confirm it works (still from build stand point).

It worked locally but not from a fresh start. Which fortunately, travis-ci caught.
The highlight-indentation github url was not right. The highlight-indentation repository is https://github.com/antonj/Highlight-Indentation-for-Emacs...

Anyway, fixed it, rebased and forced push the code.

I still need to ensure the runtime is ok (which it is from the emacs' package standpoint but i don't know yet for the package's use per say).

Again, thanks oxij, great help!

Cheers,

**Comment by ardumont** [comment]
# will do better next time

I should have left a blank field when opening this PR 
and ask for help in a comment...
Sorry for the noise.

# Original comment to not lose history...

    Hello,
    
    It's WIP because i hit some issue with emacs package dependencies version.
    
    I don't see how to fix it. 
    If someone could help me by pointing me to the right direction, it'd be great :D (thanks in advance).
    
    # problem description
    
    I'm trying to add the emacs package elpy but i hit dependencies mismatch issue.
    
    The dependencies are ok by themselves (from a nix-build stand point for the moment, no runtime check yet). 
    I declared the missing dependencies and used the latest available as of today (on github).
    
    For elpy though, the dependencies needed are lesser versions.
    
    So, when trying to build elpy, i've got a `Package '<deps>' is unavailable`
    (for example with <deps> as `highlight-indentation-0.5.0`, indeed, only 0.9.0 is declared)
    
    Here is a detailed message with the error:
    ``` sh
    # tony at corellia in ~/repo/perso/nixpkgs on git:init-elpy+deps x [20:12:07]
    $ nix-build -A emacs24PackagesNg.elpy
    these derivations will be built:
    /nix/store/ssw6npwqgjm58pdcjw5c8x5kc0h65nnf-emacs-elpy-1.9.0.drv
    building path (s) ‘/nix/store/w9g9x38hf0szzmppfdv7awax7jz0w6h1-emacs-elpy-1.9.0’
    unpacking sources
    unpacking source archive /nix/store/4d712m5ra20ky5j6dsgkdm0b37rdq8ml-elpy-39ea47c73f040ce8dcc1c2d2639ebc0eb57ab8c8-src
    source root is elpy-39ea47c73f040ce8dcc1c2d2639ebc0eb57ab8c8-src
    patching sources
    configuring
    no configure script, doing nothing
    building
    
           ;;; elpy
    
    Note: elpy :files spec is equivalent to the default.
    /tmp/nix-build-emacs-elpy-1.9.0.drv-0/elpy-39ea47c73f040ce8dcc1c2d2639ebc0eb57ab8c8-src/elpy-pkg.el -> /tmp/nix-build-emacs-elpy-1.9.0.drv-0/elpy2088751D/elpy-1.9.0/elpy-pkg.el
    /tmp/nix-build-emacs-elpy-1.9.0.drv-0/elpy-39ea47c73f040ce8dcc1c2d2639ebc0eb57ab8c8-src/elpy-refactor.el -> /tmp/nix-build-emacs-elpy-1.9.0.drv-0/elpy2088751D/elpy-1.9.0/elpy-refactor.el
    /tmp/nix-build-emacs-elpy-1.9.0.drv-0/elpy-39ea47c73f040ce8dcc1c2d2639ebc0eb57ab8c8-src/elpy.el -> /tmp/nix-build-emacs-elpy-1.9.0.drv-0/elpy2088751D/elpy-1.9.0/elpy.el
    Wrote /tmp/nix-build-emacs-elpy-1.9.0.drv-0/elpy-39ea47c73f040ce8dcc1c2d2639ebc0eb57ab8c8-src/elpy-readme.txt
    Built in 0.016s, finished at Thu Sep 24 18:14:17 2015
    installing
    Parsing tar file...
    Parsing tar file...done
    Package `highlight-indentation-0.5.0' is unavailable
    builder for ‘/nix/store/ssw6npwqgjm58pdcjw5c8x5kc0h65nnf-emacs-elpy-1.9.0.drv’ failed with exit code 255
    error: build of ‘/nix/store/ssw6npwqgjm58pdcjw5c8x5kc0h65nnf-emacs-elpy-1.9.0.drv’ failed
    ```
    
    `highlight-indentation` is a new package (as of this PR), so I could install the 0.5.0 and not the latest.
    
    Still, `company`, which is also a dependency, already exists in nixpkgs with a superior version than the dependencies needed by elpy.
    (0.8.2 is the dependency version needed but 0.8.12 is the one in nixpkgs).
    
    Is it possible to either:
    - override the dependencies version to ask for a lesser one?
    - bypass the number version declared in emacs package (less clean i suppose)
    
    If not, what's the solution, go and make a pr on elpy's package to increase its deps version?
    
    Thanks for any help
    
    Cheers,

**Comment by oxij** [comment]
I'd prefer commit messages that start with 'emacs-packages: '. If you do
`git log pkgs/top-level/emacs-packages.nix` you should notice that most
of the commit messages there have that property.

**Comment by ardumont** [comment]
> I'd prefer commit messages that start with 'emacs-packages: '. If you do `git log pkgs/top-level/emacs-packages.nix` you should notice that most of the commit messages there have that property.

Ok.
Also, I forgot to sort the new packages alphabetically as the others are.

**Comment by ardumont** [comment]
Done, btw :D

So, from my point of view, it's ready.

Of course, I'll adapt if anything is still considered wrong.

Cheers,

**Comment by oxij** [comment]
I did not notice before, but if you look at the source of
`fetchFromGitHub` in `all-packages.nix` you'll notice that `src` in
`highlight-indentation` can be re written as `fetchFromGitHub` with
`rev = "v${version}";`.

**Comment by ardumont** [comment]
> I did not notice before, but if you look at the source of `fetchFromGitHub` in `all-packages.nix` you'll notice that `src` in `highlight-indentation` can be re written as `fetchFromGitHub` with `rev = "v${version}";`.

Not only rev but also:
```nix
repo = "Highlight-Indentation-for-Emacs";
```

Tryout running... I wonder if i will not hit my previous errors... will see :D 

Thanks for the heads up.

**Comment by ardumont** [comment]
> Tryout running... I wonder if i will not hit my previous errors... will see :D

It worked! Great!

**Comment by ardumont** [comment]
Will push one commit to check travis is ok.
Then will rebase... 
(but i've got a hellishly slowwww network... )

**Comment by oxij** [comment]
I think you've lost the `for` cycle when patching deps in `elpy`.
Copy-paste is not good.

**Comment by ardumont** [comment]
> I think you've lost the `for` cycle when patching deps in `elpy`. Copy-paste is not good.

You mean that, during the patchPhase, I could map substitution on elpy.el and elpy-pkg.el instead of copy/paste. Indeed. 
Thanks @oxij.

(I reformulated because I did not get it at first.)

**Comment by oxij** [comment]
Now it's perfect :+1:

**Comment by ardumont** [comment]
> Now it's perfect :+1:

:beer:

**Comment by ardumont** [comment]
Reworking this in a complete elpy related PR (including python-packages and emacs-packages as they need version compatibility)...

**Pull request closed without merging**
