### PR TITLE
 addic7ed-cli: init at 1.4.5 

### PR DESCRIPTION
**Pull request by eugenezastrogin**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by c0bw3b — CHANGES_REQUESTED** [review]
Homepage is not the GH repo of the Pypi pkg you are fetching

addic7ed -> https://github.com/adrian-maurin/addic7ed
addic7ed-cli -> https://github.com/BenoitZugmeyer/addic7ed-cli/

It seems you intend to package the first one.

**Comment by c0bw3b** [comment]
Does the tool works for you @aethelz ?
Asking because I see the last release is from 2017 and addic7ed APIs may have changed since.

**Comment by aethelz** [comment]
> Homepage is not the GH repo of the Pypi pkg you are fetching
> 
> addic7ed -> https://github.com/adrian-maurin/addic7ed
> addic7ed-cli -> https://github.com/BenoitZugmeyer/addic7ed-cli/
> 
> It seems you intend to package the first one.

Wow! Cannot believe I missed that. Sorry for the confusion.
I actually wanted to package the second one. It is newer and still works.
I made changes accordingly.

**Comment by c0bw3b** [comment]
@GrahamcOfBorg build python27Packages.addic7ed-cli python37Packages.addic7ed-cli

**Review by c0bw3b — APPROVED** [review]

**Pull request merged**
