### PR TITLE
mesa: 22.1.4 -> 22.1.5

### PR DESCRIPTION
**Pull request by PedroHLC**
###### Description of changes

1. Bump changes: https://docs.mesa3d.org/relnotes/22.1.5.html

2. Moved patches (that were already using SRI hashes), I've adopted [what the wiki calls the preferred way](https://nixos.wiki/wiki/Nix_Hash#Usage).

3. Added the fix for https://gitlab.freedesktop.org/mesa/mesa/-/issues/6519 as a patch (for darwin only).

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vcunat** [comment]
Are you sure that the darwin fixes have been included in 22.1.5?  I haven't noticed them in the release notes.

**Comment by PedroHLC** [comment]
> Are you sure that the darwin fixes have been included in 22.1.5? I haven't noticed them in the release notes.

I somehow looked the wrong tag, reverting this...

**Comment by vcunat** [comment]
SRI: I like to simply paste the hash published on https homepages ([example](https://docs.mesa3d.org/relnotes/22.1.5.html#sha256-checksum)), but I don't really mind.

**Comment by PedroHLC** [comment]
> SRI: I like to simply paste the hash published on https homepages ([example](https://docs.mesa3d.org/relnotes/22.1.5.html#sha256-checksum)), but I don't really mind.

Indeed, that's easier. Reverted...

Instead of keeping the darwin friends outdated, I pulled the fix as a patch, seems fine right? Will ask a colleague to build it...

**Comment by PedroHLC** [comment]
@ofborg build mesa

**Comment by vcunat** [comment]
That most likely won't work, because the staging rebuilds are normally very large.  (and ofborg tries to merge with newest version of the target branch)

**Comment by PedroHLC** [comment]
> That most likely won't work, because the staging rebuilds are normally very large. (and ofborg tries to merge with newest version of the target branch)

It already succeeded with `aarch64-darwin`, which is already a relief. :smile: 

But yeah, you're right, for `x86_64-darwin` I'll have to wait LLVM.

For reference, without the patch, this same version fails with:
```
Undefined symbols for architecture x86_64:
  "_dri_kms_driver_extensions", referenced from:
      _swkmsCreateNewScreen in libdri.a(dri_util.c.o)
  "_galliumdrm_driver_extensions", referenced from:
      _dri2CreateNewScreen in libdri.a(dri_util.c.o)
ld: symbol(s) not found for architecture x86_64
```

**Comment by vcunat** [comment]
I only see a failure on `aarch64-darwin`, though an unrelated one.

**Comment by PedroHLC** [comment]
@ofborg build mesa

**Comment by PedroHLC** [comment]
https://github.com/ofborg build mesa

**Comment by PedroHLC** [comment]
@ofborg build mesa

**Comment by PedroHLC** [comment]
Successful builds in both aarch64 and x86_64 for darwin, against unstable:
- x86_64: https://logs.nix.ci/?key=nixos/nixpkgs.185699&attempt_id=7629ae3a-b87f-4e86-9fc7-343028f035ba
- aarch64: https://logs.nix.ci/?key=nixos/nixpkgs.185699&attempt_id=deb5f7c8-fb0d-4a36-9db7-ae9cfb1678a2

I should have run the tests instead of package in ofborg...

**Comment by superherointj** [comment]
@GrahamcOfBorg eval

**Comment by superherointj** [comment]
@ofborg eval

**Comment by superherointj** [comment]
@NixOS/ofborg eval

**Comment by superherointj** [comment]
@ofborg eval

**Comment by PedroHLC** [comment]
@vcunat what do you recommend me to deal with this? Keep the darwin patch (which builds, but I can't test), or revert and just push the bump?

PS: Meanwhile, the "No channel PR" [won't re-trigger in the right target](https://github.com/NixOS/nixpkgs/blob/2f69e982ace00128c0641c368aee171cb56fb13e/.github/workflows/no-channel.yml#L3).

**Comment by vcunat** [comment]
It sounds good to me this way.  I think we've never tested mesa for `*-darwin` beyond building stuff.

**Review by superherointj — APPROVED** [review]
On linux-x86_64, `mesa` builds for me. I cannot test for downstream breakage as it's staging. Merging this would be good to let hydra test it fully. Seems good to me for this purpose. If someone else (@vcunat maybe?) approves this, I'd be fine merging this.

**Comment by vcunat** [comment]
Hydra doesn't test much relevant things, and `staging` branch normally isn't built (immediately).  But getting further, into the the next `staging-next` iteration will create binaries and allow easier testing by people.  Either way, patch bumps shouldn't be problematic.

**Comment by vcunat** [comment]
Let's skip to 22.1.6?
https://lists.freedesktop.org/archives/mesa-announce/2022-August/000683.html

**Comment by PedroHLC** [comment]
> 22.1.6

In another, less noised PR.

**Pull request closed without merging**
