### PR TITLE
fetchgit -> fetchFromGitHub where possible

### PR DESCRIPTION
**Pull request by volth**
###### Motivation for this change

```fetchFrom*``` functions support tags since https://github.com/NixOS/nixpkgs/pull/26877 so they could be used where ```fetchgit``` had to be used to workaround the issue with forbidden characters in tag names.

Rebased to staging

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
This should probably quickly get merged before we have to many merge conflicts.

**Comment by edolstra** [comment]
I'm against the use of `fetchSubmodules` with `fetchFromGitHub`, and this adds dozens of uses of that.  `fetchFromGitHub` was intended as a trivial wrapper around `fetchzip` (i.e. a fast HTTP download), not a complicated wrapper around `fetchgit`.  So we should not promote its use. (I have a commit laying around reverting the addition of `fetchSubmodules`, but I haven't pushed it yet.)

**Comment by volth** [comment]
Actually, it is ```fetchgit``` at first place with faster (and unreliable: https://github.com/NixOS/nixpkgs/issues/25647) cache accessible via ```fetchzip```

**Comment by edolstra** [comment]
Arguably, `fetchFromGitHub` should not have been introduced in the first place since it doesn't really provide any value over calling `fetchzip` directly. In fact, `fetchFromGitHub` calls are more verbose than the equivalent `fetchzip` calls. But at least it was simple:
```
  fetchGitHub = { owner, repo, rev, sha256 }: fetchzip {
    url = "https://github.com/${owner}/${repo}/archive/${rev}.zip";
    inherit sha256;
  };
```
Now it has turned into this monstrosity:
```
  fetchFromGitHub = {
    owner, repo, rev, name ? gitRepoToName repo rev,
    fetchSubmodules ? false, private ? false,
    githubBase ? "github.com", varPrefix ? null,
    ... # For hash agility
  }@args: assert private -> !fetchSubmodules;
  let
    baseUrl = "https://${githubBase}/${owner}/${repo}";
    passthruAttrs = removeAttrs args [ "owner" "repo" "rev" "fetchSubmodules" "private" "githubBase" "varPrefix" ];
    varBase = "NIX${if varPrefix == null then "" else "_${varPrefix}"}_GITHUB_PRIVATE_";
  in if fetchSubmodules then
    fetchgit ({
      inherit name rev fetchSubmodules;
      url = "${baseUrl}.git";
    } // passthruAttrs)
  else
    # We prefer fetchzip in cases we don't need submodules as the hash
    # is more stable in that case.
    fetchzip ({
      inherit name;
      url = "${baseUrl}/archive/${rev}.tar.gz";
      meta.homepage = "${baseUrl}/";
    } // lib.optionalAttrs private {
      netrcPhase = ''
        if [ -z "''$${varBase}USERNAME" -o -z "''$${varBase}PASSWORD" ]; then
          echo "Error: Private fetchFromGitHub requires the nix building process (nix-daemon in multi user mode) to have the ${varBase}USERNAME and ${varBase}PASSWORD env vars set." >&2
          exit 1
        fi
        cat > netrc <<EOF
        machine ${githubBase}
                login ''$${varBase}USERNAME
                password ''$${varBase}PASSWORD
        EOF
      '';
      netrcImpureEnvVars = [ "${varBase}USERNAME" "${varBase}PASSWORD" ];
    } // passthruAttrs) // { inherit rev; };
```
which either calls `fetchzip` or `fetchgit` (so its semantics are no longer obvious) and does some magic impure netrc stuff that doesn't belong in Nixpkgs since nothing in Nixpkgs fetches private git repos. So I no longer feel we should promote the use of `fetchFromGitHub`.

**Comment by volth** [comment]
another point against ```fetchFromGitHub``` is Nodejs and Go packages with their ```import githib.com/owner/repo``` statements, they use ```fetchgit``` and cannot use the fast path of downloading zips from "https://github.com/${owner}/${repo}/archive/${rev}.zip"

**Comment by Mic92** [comment]
I think `node.js` and `go` is a separate issue. `fetchzip` also needs a separate implementation, which would only work for `github` again. This needs to implemented in the wrapper.

**Comment by volth** [comment]
Flipping between ```fetchgit``` and ```fetchFromGitHub``` depending on whether the current version of upstream software requires ```fetchSubmodules``` is not nice either...
There are basically two ways:
1. Github is just a git hosting, one in a row, nothing special except of nice ```fetchzip```-caching, which is anyway not for all github repos, but only for those which do not require ```fetchSubmodules``` nor ```leaveDotGit``` nor private. Then ```fetchFromGitHub``` is needless and we should use ```fetchzip``` and ```fetchgit``` depending on if ```fetchzip```could help in a particular case (this is subject of change, Github may introduce support of zip-download with submodules)
2. Github is something special (which is probably true, there are much more Github repos then others), and pointer to repo is not a git://-url, but ```owner``` and ```repo```. Then ```fetchFromGitHub``` is a interface to Github hiding implementation details (```fetchzip``` or ```fetchgit```) under the hood. Although it might be a complex and scary code, it is the only place to change if interface to github would change or require special attention (something like "to use http/2 or not").

**Pull request closed without merging**
