### PR TITLE
dotnet: add SRI hash support to dotnet packages

### PR DESCRIPTION
**Pull request by Aleksanaa**
## Description of changes

This is a small step forward to support SRI `hash` attribute everywhere and deprecate `sha256` attribute.

This PR doesn't deprecate `sha256` attribute however. I think this change can be made after half a year, but would love to hear different opinions.

For `nuget-to-nix` part, I've tested with one of my packages `pablodraw`, and it works perfectly.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by GaetanLepage — APPROVED** [review]

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 324526` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>csharp-ls</li>
    <li>csharpier</li>
    <li>csharprepl</li>
    <li>fable</li>
    <li>fantomas</li>
    <li>gitversion</li>
    <li>nuget-to-nix</li>
    <li>pablodraw</li>
    <li>pbm</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 324526` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>pablodraw</li>
  </ul>
</details>
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>csharp-ls</li>
    <li>csharpier</li>
    <li>csharprepl</li>
    <li>fantomas</li>
    <li>gitversion</li>
    <li>nuget-to-nix</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 324526` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>pablodraw</li>
  </ul>
</details>
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>csharp-ls</li>
    <li>csharpier</li>
    <li>csharprepl</li>
    <li>fantomas</li>
    <li>gitversion</li>
    <li>nuget-to-nix</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 324526` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built:</summary>
  <ul>
    <li>csharp-ls</li>
    <li>csharpier</li>
    <li>csharprepl</li>
    <li>fable</li>
    <li>fantomas</li>
    <li>gitversion</li>
    <li>pablodraw</li>
    <li>pbm</li>
  </ul>
</details>

**Comment by Aleksanaa** [comment]
Thanks for testing!

**Review by GaetanLepage — APPROVED** [review]

**Review by corngood — APPROVED** [review]

**Comment by corngood** [comment]
There is `maintainers/scripts/update-dotnet-lockfiles.nix`, which could be helpful in removing sha256.  It will however update dependencies for a lot of things.

FYI @NixOS/dotnet

**Comment by Aleksanaa** [comment]
> There is `maintainers/scripts/update-dotnet-lockfiles.nix`, which could be helpful in removing sha256. It will however update dependencies for a lot of things.

We can update that but not running it?

**Comment by corngood** [comment]
> We can update that but not running it?

Sorry, I'm not sure what you mean.  The script simply runs `fetch-deps` on everything in nixpkgs.  I just thought that might be helpful.

It wouldn't fix the 'global tool' hashes.

**Comment by Aleksanaa** [comment]
Oh now I know what you mean. But let’s just wait until deprecation. Anyway, this `deps.nix` is not written by humans, and there is no problem of correcting habits.

**Review by GGG-KILLER — APPROVED** [review]

**Comment by melvyn2** [comment]
Since this seems like a purely additive change, could it be backported to 24.05?
It would help with backporting updates of other dotnet packages which switch to the SRI hash type.

**Comment by eclairevoyant** [comment]
I'd only backport the first 5 commits, probably.

**Comment by arianvp** [comment]
Is there still a plan to backport this? This is causing more backport churn here:

https://github.com/NixOS/nixpkgs/pull/333767

**Comment by GGG-KILLER** [comment]
@arianvp I've created #336197 to backport this to stable

**Pull request merged**
