### PR TITLE
kubectl-klock: init at 0.3.1

### PR DESCRIPTION
**Pull request by scm2342**
Add https://github.com/jilleJr/kubectl-klock kubectl plugin

###### Description of changes

kubectl [klock](https://github.com/jilleJr/kubectl-klock) is analog to `kubectl get -w` but instead of line based output, it keeps the table format.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by qjoly — APPROVED** [review]

**Comment by nagy** [comment]
`v0.3.1` has since been released. Can you update this and then squash the commits, so that we only have one init commit ?

**Comment by scm2342** [comment]
@nagy yes, sure, done.

**Comment by nagy** [comment]
Hello, apologies. I did not pay much attention, when I wrote my last comment. We need two commits. One for initializing your maintainership and one for the package itself. sorry.

**Comment by scm2342** [comment]
@nagy no worries at all and thanks for taking care. 
I think this should be it then.

Greetings from a german hacker camp (on the off chance you are also there as there is a nixos village that I have not visited).

**Comment by nagy** [comment]
Thank you. Indeed it looks good, but one last minor thing. Can you change the commit message to `maintainers: add scm2342` ?

> on the off chance you are also there

I am not, but maybe next time.

**Comment by scm2342** [comment]
@nagy done.

**Review by nagy — APPROVED** [review]

**Comment by nagy** [comment]
Thanks, could you also update the PR title itself ?

**Comment by scm2342** [comment]
@nagy sure. Thanks!

**Pull request merged**
