### PR TITLE
haskell generic-builder: Fix package conf handling

### PR DESCRIPTION
**Pull request by infinisil**
###### Motivation for this change
Previously the package conf files were handled without paying attention to the fact that it's pretty-printed output. One problem was discovered with GHC 8.8.1 on Darwin, where the dynamic-library-dirs first field seems to have increased in length, meaning while before it was

```
dynamic-library-dirs: some-small-directory-name
                      some-more-directories
```

Now it is

```
dynamic-library-dirs:
    some-larger-directory-name
    some-more-directories
```

Which breaks the code installed for https://github.com/NixOS/nixpkgs/pull/25537 because it assumed the former format, resulting in the reoccurence of the bug in https://github.com/NixOS/nixpkgs/issues/22810, see https://github.com/Infinisil/all-hies/issues/43

This commit fixes this by unprettifying the package conf files before
processing them. This also gets rid of a nasty sed expression previously used to do this conf format juggling

The only change of behavior is that whereas previously above line would be changed to

```
dynamic-library-dirs: $out/lib/links
                      some-more-directories
```

it now is changed to (`some-more-directories` isn't present anymore)
```
dynamic-library-dirs: $out/lib/links
```

But this isn't a problem because all `.dylib`'s in those directories will have been symlinked into `$out/lib/links` anyways.

Ping @peti @copumpkin @Ericson2314 @LnL7 @shlevy 

###### Things done

- [x] Confirmed that this fixes https://github.com/Infinisil/all-hies/issues/43 (currently compiling on my mac) (which is also a good confirmation that nothing broke, because this includes dozens of dependencies).

### CODE REVIEW

**Comment by Infinisil** [comment]
Such that people can find this issue, here is the error message this fixes on macOS using GHC 8.8.1 (can occur during building or running):
```
dyld: Library not loaded: @rpath/libHShaskell-ide-engine-1.0.0.0-5EcNvjBz4sl3yA1Hn7NQQN-ghc8.8.1.dylib
  Referenced from: /Users/malo/.nix-profile/bin/hie-8.8.1
  Reason: no suitable image found.  Did find:
        /nix/store/gvdg0v5c0n8h0yi75w6k8gzn17wdr4q0-haskell-ide-engine-ghc881-970637fa13/lib/ghc-8.8.1/x86_64-osx-ghc-8.8.1/libHShaskell-ide-engine-1.0.0.0-5EcNvjBz4sl3yA1Hn7NQQN-ghc8.8.1.dylib: malformed mach-o: load commands size (33984) > 32768
```

**Review by Ericson2314 — APPROVED** [review]
Nice work munging around with the stuff. We should raise the issue upstream that they ought to migrate to more standardized encodings.

**Comment by Infinisil** [comment]
Oh and another change of behavior is how now *all* directories in `dynamic-library-dirs` are being checked for dynamic libraries instead of just the first one. Because of this I just had to push a fix for when such a directory is empty

**Comment by Infinisil** [comment]
With this change I just pushed I can confirm that this fixes the issue

**Comment by Infinisil** [comment]
Anybody have any objections? Otherwise I'd like to have this merged soon

**Comment by peti** [comment]
Pushed in 55a8169316bf6e1e18e94055baa1b5e1d60c4c97. Test builds are running at https://hydra.nixos.org/eval/1567978.

**Comment by Infinisil** [comment]
Seems to be failing, but that very much seems unrelated:
```
make[1]: *** [compiler/ghc.mk:445: compiler/stage2/build/HsInstances.p_o] Segmentation fault (core dumped)
```

I hope that's just a transient failure, I'll restart the build

**Comment by Infinisil** [comment]
Nevermind, I can't restart that job, "Only the project members, administrators, and accounts with restart-jobs privileges can perform this operation."

**Comment by peti** [comment]
I have restarted the `ghc-8.8.1` build.

**Pull request closed without merging**
