### PR TITLE
python312Packages.tempita: drop nose dependency

### PR DESCRIPTION
**Pull request by Sigmanificient**
## Description of changes

part of:
- #326513

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by emilazy — CHANGES_REQUESTED** [review]
There’s a 2021 upstream release that seems to support Python 3, maybe we should switch to that rather than using this random fork if we want to keep this package?

However, the only reverse dependency in‐tree is `python3Packages.sqlalchemy-migrate`, which is marked broken because it doesn’t support newer SQLAlchemy versions. Perhaps we should simply drop instead.

**Comment by Sigmanificient** [comment]
The bit-bucket link in repo description seems to 404 on my side, which might be te reason the fork was chosen
Well, the fact has no maintainers is an argument in favor of dropping it?

**Comment by emilazy** [comment]
Ah, the thing from 2021 is just a wheel of a version from 2013. Weird.

I favour dropping this and `sqlalchemy-migrate`. I was going to cite the small list of reverse dependencies on Wheelodex that I remembered seeing when I left my last comment but it looks like I made the site fall over by using it too much.

However, `openlp` depends on `sqlalchemy-migrate`. It is on an outdated version, and the latest upstream release does not use the dependency any more. So we’d have to bump that, or drop the package, which would be unfortunate as it seems like an actively‐maintained end‐user application.

@jorsn Would you be willing to update `openlp` to help unblock this?

**Comment by Sigmanificient** [comment]
Doesn't `qtwebkit` have quite a few deps?

**Comment by Sigmanificient** [comment]
oh hum i was in the process of doing it

**Pull request closed without merging**
