### PR TITLE
zed: replace npm2nix with node2nix

### PR DESCRIPTION
**Pull request by Ma27**
###### Motivation for this change

Further effort on #31032

Unfortunately `zedapp` is not available in the NPM registry, so the old derivation had to be kept.
I retained the dependency-versions used by `zedapp` (which aren't the latest ones), see `deps.json` and https://github.com/zedapp/zed/blob/master/app/package.json for further reference

I cleaned up the meta section a bit and added myself as maintainer to make sure there are more people to ping if this breaks before one of the next releases.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Ma27** [comment]
(/cc @svanderburg)

**Comment by svanderburg** [comment]
Very cool @Ma27 that you fixed this!

Could you make a few subtle changes? I can't find the node2nix command line instruction that you used to generate the package set. Could you also include a shell script that describes how to regenerate the expressions? This would be useful to allow others to repeat the packaging process.

Another thing I noticed is that you include yet another copy of `node-env.nix` in the package directory. This is strictly not needed since such a copy already exists in the Nixpkgs repository. It would be more space efficient if we reuse it.

You can reuse the existing `node-env.nix` file from the NPM package set, by adding the following parameters to node2nix:

```bash
node2nix -e ../../../development/node-packages/node-env.nix --no-copy-node-env
```

The first parameter specifies the relative path to the existing `node-env.nix` from the NPM package set, the second parameter specifies that we should not copy this file from the `node2nix` toolset.

**Comment by Ma27** [comment]
1.: I added the used command in a coment above the 'import ./node.nix' expression, however a shell script might be way better...

2.: ah, didn't know about this option, so :+1: for deduplication!

**Comment by yegortimoshenko** [comment]
Consider checking out this fetcher and see if it works for you:
https://github.com/NixOS/nixpkgs/blob/1925b4c1a06c6c03431ab45f10ef369125d57f6f/pkgs/applications/networking/instant-messengers/rambox/fetchNodeModules.nix

**Comment by svanderburg** [comment]
@Ma27 I just noticed that a validation step in the Travis CI build is failing.

The fix is quite simple. Can you change the following line in `default.nix`:

```nix
nodePackages = import ./node.nix {};
```

into:

```nix
nodePackages = import ./node.nix { inherit pkgs; system = stdenv.system; };
```

Then it should work fine. The validation error is caused by the fact that there is a `<nixpkgs>` reference that should not be called in strict mode.

**Comment by Ma27** [comment]
@svanderburg just out of interest: what do you think of the fetcher @yegortimoshenko built?

The latest NPM versions are deterministic, they secure their sources with SHA hashes and (IIRC) the NPM registry is immutable (no re-push/delete for published tags) since the left-pad incident, so it should be possible  to use NPM without fearing side-effects as soon as NodeJS 4 and 6 are EOLed, right?

However I'm a bit hesitant to use this approach for `zed` as I think it's better to bring this to a consistent state (by dropping npm2nix) for now and discuss such things in a seperate issue (as @yegortimoshenko built this, you might want to open one?)

**Comment by svanderburg** [comment]
@Ma27 @yegortimoshenko I haven't studied this solution in detail yet. I think it's a practical/workable solution for some categories of NPM packages (most notably end-user packages without any complex dependencies), but I don't think it is a robust solution for every project -- I can already think of some projects where more is needed than just a drop-in replacement for the`node_modules/` folder.

However, since packaging support for NPM 5.x is still missing in `node2nix` (I'm still working on this, but this requires a very different kind of solution), this fetcher (so far) is the only solution we have for integrating the newest NPM with Nix to some extent.

So the fetcher is not a useless solution, but I also believe we need a more robust facility with features on par with what `node2nix` currently provides.

I will come back to this (hopefully) soon.

**Comment by yegortimoshenko** [comment]
While older Node.js versions don't come with a usable npm, all that it takes to use this fetcher with older NodeJS versions is a npm package (`npm install npm@latest`). Also, since it doesn't run scripts, I believe that `node_modules` fetched with `nodejs-8_x` package should be usable with any Node.js version.

This shouldn't be much of a problem, as 8.x is now the stable branch: https://nodejs.org/en/download/

**Comment by svanderburg** [comment]
@Ma27 I have integrated your changes. Thanks!

I think my former research colleague @zefhemel would like it!

**Comment by Ma27** [comment]
> While older Node.js versions don't come with a usable npm, all it would take to support this is a npm package (npm install npm@latest).

Right, this is why I said "as soon as NodeJS 4 and 6 are EOLed".

I didn't intend to replace node2nix immediately, I've just realized while reading through this code (and the linked issues) that NPM made a huge progress regarding deterministic builds (that actually work in comparison to all these weird npm-shrinkwrap issues I had in NPM 3.x :-D).

> I can already think of some projects where more is needed than just a drop-in replacement for thenode_modules/ folder.

you mean node packages where you need extra dependencies that need to be adjusted using the override-capabilities or are there any further issues?

The reason why I asked about this is because it seems to be an interesting approach, however I we should discuss any further details about this in a special ticket :-)

**Pull request merged**
