### PR TITLE
nixosTests.installer: fix non-zfs grub tests

### PR DESCRIPTION
**Pull request by r-burns**
Now that grub2 is built without zfs support when possible, this is a
separate store path which may need to be made available to the installer.

###### Motivation for this change

I bisected the currently failing `nixosTests.installer.simpleUefiGrub` to fe111fc67937c22ffc84e4466f494366583124b7. This fixes that test failure for me.
cc @symphorien re: https://github.com/NixOS/nixpkgs/pull/112857#issuecomment-778068295

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-burns** [comment]
@GrahamcOfBorg test installer.simpleUefiGrub installer.simpleUefiGrubSpecialisation zfs.installer

**Comment by r-burns** [comment]
arm64 tester ran out of space:
```
machine # /nix/store/sy446046vxwlk6ya5012rx3cvx12wmp8-grub-2.04/sbin/grub-install: error: cannot copy `/nix/store/sy446046vxwlk6ya5012rx3cvx12wmp8-grub-2.04/share/grub/unicode.pf2' to `/boot/grub/fonts/unicode.pf2': No space left on device.
machine # /nix/store/hz5q3qifivm19q4bqxi3qqf8vw43zrgj-install-grub.pl: installation of GRUB EFI into /boot failed: No such file or directory
```

**Comment by SuperSandro2000** [comment]
@ofborg eval

**Comment by tfc** [comment]
code looks good to me, but on ofborg it seems to be failing

**Comment by r-burns** [comment]
Yeah, the aarch64 builder runs out of space. Not sure what to do..

```
machine # updating GRUB 2 menu...
machine # installing the GRUB 2 EFI boot loader into /boot...
machine # Installing for arm64-efi platform.
machine # /nix/store/sy446046vxwlk6ya5012rx3cvx12wmp8-grub-2.04/sbin/grub-install: error: cannot copy `/nix/store/sy446046vxwlk6ya5012rx3cvx12wmp8-grub-2.04/share/grub/unicode.pf2' to `/boot/grub/fonts/unicode.pf2': No space left on device.
machine # /nix/store/hz5q3qifivm19q4bqxi3qqf8vw43zrgj-install-grub.pl: installation of GRUB EFI into /boot failed: No such file or directory
```

**Comment by tfc** [comment]
@GrahamcOfBorg test installer.simpleUefiGrub installer.simpleUefiGrubSpecialisation zfs.installer

**Comment by tfc** [comment]
@r-burns thank you!

**Pull request merged**
