### PR TITLE
gcc-arm-embedded: Update, add Mac support, drop old versions.

### PR DESCRIPTION
**Pull request by ambrop72**
Please someone test this on Mac.

### CODE REVIEW

**Comment by ambrop72** [comment]
Actually I would wait with this particular version, since I found a pretty serious regression (https://bugs.launchpad.net/gcc-arm-embedded/+bug/1516185). But please still someone try the Mac code, I've added support but don't have a Mac to test!

**Comment by zimbatm** [comment]
It looks like the 5.0 version has been released.

**Comment by ambrop72** [comment]
Hey,
I'm no longer interested in maintaining this because I maintain my own Nix expressions for a from-source toolchain - [link](https://github.com/ambrop72/aprinter/blob/master/nix/gcc-arm-embedded-fromsrc.nix).

Anyway the issue I mentioned has been [discussed](https://sourceware.org/ml/newlib/2016/threads.html#00000) on the newlib mailing list and it would not be fixed. In summary, there has been an upstream change in newlib related to the printf formats which breaks `PRI*8` formats when newlib is
configured either with `--enable-newlib-nano-formatted-io` or without
`--enable-newlib-io-c99-format` (the former being the case here). On my own toolchain I build with the latter only to avoid the issue.

**Comment by ambrop72** [comment]
I also have a clang-based toolchain (build on top of that one, i.e. still using gcc-built newlib), if anyone is interested (see its nix-expr in the same folder). I think the C++ stdlib isn't set up with it though (I don't need it myself).

**Comment by zimbatm** [comment]
I don't have much knowledge of the gcc and clang toolchain but it would be cool to get your work merged at some point.

Should I just close the issue for now ?

**Comment by ambrop72** [comment]
I am okay with this issue being closed. Please note I have no interest myself in merging this into nixpkgs, it is more practical for me to ship nix expressions along with my project, for versions tested and configured correctly for my software. But I can assist anyone wanting to add this to nixpkgs.

**Pull request closed without merging**
