### PR TITLE
gitlab: 14.0.5 -> 14.1.0

### PR DESCRIPTION
**Pull request by yu-re-ka**
###### Motivation for this change

https://about.gitlab.com/releases/2021/07/22/gitlab-14-1-released/

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
What's the reason for the backport label, @talyz ?

**Comment by talyz** [comment]
It triggers the automatic creation of a backport PR to stable when this is merged to master.

**Comment by risicle** [comment]
Sure - but I'm asking what qualifies this bump for the stable branch?

**Comment by yu-re-ka** [comment]
> Sure - but I'm asking what qualifies this bump for the stable branch?

GitLab updates are usually backported, because security patches and bugfixes are not backported for more than 3 months. If we don't backport this now, we will need to do a huge version jump in three months in order to deliver security updates and bugfixes.

**Comment by talyz** [comment]
Oh, we just want GitLab as up-to-date as possible in stable to always have the latest security patches and bugfixes in place. The only exception I see to this is when it would cause major and unavoidable breakage, which doesn't seem to be the case here.

**Comment by risicle** [comment]
You could make the same argument about almost any package and then it makes a farce of the idea of trying to have a stable distribution at all.

I guess what I'm asking is - what is the advantage of porting this back to stable over just running off `master`?

**Comment by talyz** [comment]
I don't think that's fair. The point is to prioritize keeping important packages that are likely to pose security risks up-to-date in stable. GitLab is one of those packages. We're not a big team keeping GitLab updated in NixOS, so yes, diverging branches can significantly impact our ability to keep it up-to-date. In case updating the package would cause major breakage, we wouldn't backport the update to stable.

As for why I'm not just running off of master on my production system - severely breaking changes get added to master, which can affect the stability and availability of packages for extended periods of time. Compiler updates, changes to how frameworks are handled, breaking major version upgrades of core dependencies, etc. I want to run a secure and up-to-date version of GitLab, a leaf package, on a stable base.

**Comment by risicle** [comment]
The problem is, what you might consider to be a leaf package might not be a leaf package to a user. And users who have needs for stability (i.e. you won't have things randomly break on monday morning) and don't get it from the "stable" branch will simply stop updating at completely. And then they don't even get security updates.

I'm not _even_ suggesting here that you maintain a security-backported branch for stable - I'm just suggesting that you don't bump stable _unless_ you actually have a declared vulnerability. And who knows, if you manage to make it 6 months without a security issue, users get that stability as a bonus.

**Comment by talyz** [comment]
What you're describing is _stale_, not _stable_. You're just locking in the bugs and issues that exist at a certain point, refusing to fix them. Stable should be usable in practice, not ignored. That might imply leaving many packages untouched, but GitLab should be kept up-to-date: firstly, the scenario you describe where no security issues arise in six months doesn't happen in practice and secondly, a slow trickle of updates is much easier to handle than jumping multiple versions all at once when the next version of NixOS comes around (if it's even possible to upgrade cleanly at that point).

As stated earlier, major breaking changes should not be backported.

If GitLab is not a leaf package in your setup, I'm not sure what you're doing, but it probably falls outside any usage we can reasonably account for.

**Comment by risicle** [comment]
> What you're describing is stale, not stable. You're just locking in the bugs and issues that exist at a certain point, refusing to fix them.

New releases not only fix bugs but also introduce them - especially when these releases introduce features.

And if 6-month old software is "stale", then frankly 90% of the internet is running on extremely stale software - and it's not accidental or due to laziness.

> a slow trickle of updates is much easier to handle than jumping multiple versions all at once when the next version of NixOS comes around

That is the whole *point* of the stable branch. A user who is using the stable branch already accepts that a "big" (not that big, it's only 6 months) upgrade is going to happen every 6 months. This is something that can be planned for and pre-tested. A continual trickle of updates means every time you think you're just updating to make sure you're security patched, oops, it could break everything - hope you were planning on staying late tonight...

Incidentally if it's not safe to skip versions in upgrades for GitLab, then that itself is something I would worry about a *lot*, as it implies that a user's system that gets neglected for a few months (perhaps an auto-update trigger got broken?) would be in for trouble the next time they do update. So really, if that's the case, then any user's system is *potentially* going to fall victim to this - which would make me want to pre-plan updates even moreso rather than have them quietly trickled out to me on a "stable" branch.

> If GitLab is not a leaf package in your setup, I'm not sure what you're doing, but it probably falls outside any usage we can reasonably account for.

GitLab is a package that exposes APIs left, right and centre. People build all sorts of integrations with GitLab that may be sensitive to all kinds of subtleties and corner cases.

**Comment by talyz** [comment]
> And if 6-month old software is "stale", then frankly 90% of the internet is running on extremely stale software

For most software it probably isn't - many packages only receive one or two updates per year, but GitLab is updated constantly.

> A continual trickle of updates means every time you think you're just updating to make sure you're security patched, oops, it could break everything - hope you were planning on staying late tonight...

This point really is secondary - the main point is that failing to backport will leave a vulnerable and obsolete version of GitLab that no one should be running in stable. The mindset of not backing up your production servers because you're running off of stable won't work in general, but especially not with GitLab.

GitLab issue bug fixes only for their latest stable release and security patches for the two previous monthly releases, leaving three months of unapplied security patches in the best case, if we don't backport. See the [release and maintenance policy](https://docs.gitlab.com/ee/policy/maintenance.html) for more info.

> Incidentally if it's not safe to skip versions in upgrades for GitLab, then that itself is something I would worry about a _lot_, as it implies that a user's system that gets neglected for a few months (perhaps an auto-update trigger got broken?) would be in for trouble the next time they do update.

The upgrade guidelines state that, when upgrading from one major version to the next, you have to go from the last minor of the previous major release to the first minor release of the next major release. Jumping between minor and patch releases within the same major release should be fine.

> GitLab is a package that exposes APIs left, right and centre. People build all sorts of integrations with GitLab that may be sensitive to all kinds of subtleties and corner cases.

True, but even outside NixOS, there's no way to run an instance of the same minor version of GitLab with security patches for six months, because such a release doesn't exist. If you're that sensitive to potential API changes and don't want to update your code, your only alternative is to not upgrade at all. The way you would normally would run GitLab on any other distro is to add their third-party repository, install and update it from there, always getting the latest stable release, so this is nothing unique to NixOS. If you've been running GitLab somewhere else, you should be used to this, especially if you're at the level where you're heavily utilizing the API.

Also, major revisions and deprecations to the APIs are only made in major releases. Depending on the timing, we may have to backport major releases to be able to stay up-to-date (they _should_ release on May 22 every year, which sadly collides with our release schedule). That's not really relevant to this PR, though, since this is a minor release update.

**Pull request merged**
