### PR TITLE
catppuccin-cursors: init at 0.2.0

### PR DESCRIPTION
**Pull request by NULLx76**
###### Description of changes
adds the catppuccin styled cursors. the gtk theme is already in nixpkgs and this adds the cursors as well.
[Here](https://github.com/catppuccin/cursors) is the home page. 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by eigengrau** [comment]
Looks good (tough a local build on 16-core i9 took 65 minutes for some reason :sweat_smile:). One possible improvement I see is that the derivation includes all 16×4 variants of the theme, each of which has a size of ~7M (16×4×4 variants if you count cursor size). The total size of the package is 500M, which you then need to install even if most people will effectively only use one of the variants. Maybe it would make sense to expose the variants individually instead of as one big derivation.

**Comment by eigengrau** [comment]
>Also when splitting it probably nice to namespace them like pkgs.catpuccin-cursors.frappe-blue or something like that right?

Sure, that should work. You could have one function with two parameters underlying those derivations. It looks like upstream’s Makefile isn’t readily modular like that, though. It just calls out to `build.sh` and builds everything in one go. However, it should still be possible to build all the variants in one go in one big derivation, but then copy parts of the output into separate derivations.

**Comment by PlayerNameHere** [comment]
Hey, just a friendly note, I had actually already made a pull request for catppuccin-cursors last month in #191058. It's my first contribution to nixpkgs, so I would be happy if it got merged. Our pull requests basically do the same thing just in slightly different ways, though we use different versioning. I believe `0.2.0` actually refers to the version of the catppuccin color scheme, and not catppuccin-cursors, which doesn't use any versioning itself. Hence, I used `unstable-YYYY-MM-DD` as suggested in the nixpkgs manual.

> > Also when splitting it probably nice to namespace them like pkgs.catpuccin-cursors.frappe-blue or something like that right?
> 
> Sure, that should work. You could have one function with two parameters underlying those derivations. It looks like upstream’s Makefile isn’t readily modular like that, though. It just calls out to `build.sh` and builds everything in one go. However, it should still be possible to build all the variants in one go in one big derivation, but then copy parts of the output into separate derivations.

This does indeed seem possible using [multiple-output packages](https://nixos.org/manual/nixpkgs/stable/#sec-multiple-outputs-). In fact, [comixcursors](https://github.com/NixOS/nixpkgs/blob/4a177de7f287d10dd889063b86bc9c54d3029606/pkgs/data/icons/comixcursors/default.nix) does this and can be used as a reference. I don't mind having a stab at this.

**Comment by NULLx76** [comment]
Ah sorry that's my bad, I'll close this in favor of your PR. A multiple-output does indeed seem like a good solution. Also happy to see more contributors :D

**Pull request closed without merging**
