### PR TITLE
Added Gillius LaTeX font

### PR DESCRIPTION
**Pull request by jgertm**
I quite like this fonts for my LaTeX-Documents. It wasn't available with the normal TeXLive packages, so I took it upon myself to integrate it.

### CODE REVIEW

**Comment by vcunat** [comment]
Note: the new `texlive` already contains it. Personally, I believe the old `texLive*` attributes will fade away. If you want to try it, user docs are in https://github.com/vcunat/nixpkgs/blob/p/tex-space-stdenv/pkgs/tools/typesetting/tex/texlive-new/default.nix#L1

**Comment by jgertm** [comment]
That's some great work! I was unaware of it however, and just added this font to fit my own needs.
Has this been upstreamed yet? If so, it would make this commit moot, unless people want to keep using ```texLive```.
Would you be kind enough to write a couple of paragraphs in the wiki to point people to it?

**Comment by vcunat** [comment]
I'm sorry for the misleading link; I meant to link the official master branch (edited now). It should be in the latest channels, both unstable and release-15.09.

**Comment by vcunat** [comment]
I didn't realize there was a wiki article, thanks for pointing out. Now I added a link from there. It was very easy to miss so far, and it's been only a few days in the official branches.

**Pull request closed without merging**
