### PR TITLE
luaPackages.mpack: 1.0.9 -> 1.0.10

### PR DESCRIPTION
**Pull request by reckenrode**
###### Description of changes

This update fixes compilation with clang 15+.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by reckenrode** [comment]
@ofborg eval

**Review by toonn — COMMENTED** [review]
I can't reproduce the failure on 9ae5c2de7fc82170d65296041b2f4822e5ec8459. Am I bungling the override?

```
nix-build --pure --no-out-link -E 'with import ./. {}; (lua.override { inherit (llvmPackages_16) stdenv; callPackage = newScope { inherit (llvmPackages_16) stdenv; }; }).pkgs.mpack'
```

**Comment by teto** [comment]
@toonn what do you mean ? if it doesnt change things for you I think we can merge, I've checked that neovim builds at least

**Comment by toonn** [comment]
@teto, I can't reproduce the failure with newer Clang. This means I can't rely on no failure after the bump occurring as a signal for whether or not this works. I don't expect any problems but I try to be diligent in testing.

**Pull request merged**
