### PR TITLE
[WIP] gxi: init at 0.5.5

### PR DESCRIPTION
**Pull request by jansol**
###### Motivation for this change

Package all the things!

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jansol** [comment]
Ugh, looks like `DESTDIR=$out` was not correct after all, fixing...

**Comment by dtzWill** [comment]
This seems to have a duplicate "prefix", `result/nix/store/xxx..../bin/gxi` vs `result/bin/gxi`? I'm trying a build w/o setting DESTDIR to see if that fixes things, not sure.

FWIW, previously: #48593 .
Which I was encouraged to make available elsewhere until xi was more "stable".
Accordingly, may want to check out my NUR repo: https://github.com/dtzWill/nur-packages/,
particularly: https://github.com/dtzWill/nur-packages/tree/master/pkgs/xi and especially https://github.com/dtzWill/nur-packages/blob/master/pkgs/xi/gxi/default.nix .

I would be happy to see this (and perhaps others) in nixpkgs proper, or otherwise improved and made available for folks to explore!

There might be better ways to approach this than what I did, but it does handle something I don't think is tackled here: rigging up the `xi-syntext` plugin so that syntax highlighting works out-of-the-box.
(You still need to select filetype from the drop-down, but it otherwise seems to work! Well, other than the unforgivable (:wink:) omission of highlight support for Nix files!

I haven't poked at this much recently (beyond automated updates), but offhand it might be better for gxi in particular to do something more like what you have done re:all-in-one to avoid mismatches between frontend and backend versions.  Although I forget if that's a concern :innocent:.

**Comment by dtzWill** [comment]
Oh the syntect plugin is handled here now too, great! That was the main technical point, glad it's handled automagically.

**Comment by jansol** [comment]
Yeah I noticed that problem. I'm setting DESTDIR precisely because the meson postinstall script was failing otherwise. Still no clue why, it wouldn't print out anything...

This was just a mostly clueless attempt at packaging gxi so I don't have to use atom. Anyway this does set up xi-syntect-plugin. Your setup seems to allow for much better sharing of derivations down the line though so I'd probably prefer that route. Would be nice to be able to use a shared LSP plugin installation for all xi frontends. Plugins and frontends AFAIK *should not* be tied to any specific core version, but until 1.0 there are of course no guarantees about that.

TIL about NUR. I guess I'll just close this until we figure out a proper clean setup...

**Comment by jansol** [comment]
Let's move discussion to [the xi-editor Zulip instance](https://xi.zulipchat.com/).

**Pull request closed without merging**
