### PR TITLE
stuntrally: 2.6.2 -> 2.7

### PR DESCRIPTION
**Pull request by ThibaultLemaire**
###### Description of changes

[StuntRally 2.7 Changelog](https://stuntrally.tuxfamily.org/wiki/doku.php?id=changelog)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ThibaultLemaire** [comment]
This fails to build with (excerpt):

```
/build/source/source/ogre/CarReflection.cpp:96:31: error: 'class Ogre::Camera' has no member named 'setPosition'; did you mean 'getRealPosition'?
   96 |                         mCam->setPosition(Vector3::ZERO);
      |                               ^~~~~~~~~~~
      |                               getRealPosition
```

The offending line in the upstream source has not been changed in 11 years. [The latest (13.5) OGRE doc](https://ogrecave.github.io/ogre/api/latest/class_ogre_1_1_camera.html#abb5bad7918a07b1e7408f183b177d1a0) says `Ogre::Camera::setPosition()` is deprecated now, but it seems to still be there... 

I'm building with OGRE 13 because [the StuntRally 2.7 documentation](https://stuntrally.tuxfamily.org/wiki/doku.php?id=compile) says it's what it's been tested with.

I'll keep investigating tomorrow

**Comment by ThibaultLemaire** [comment]
[Latest CI build](https://github.com/stuntrally/stuntrally/actions/runs/3448019539/jobs/5754638348) for 2.7 passed on Ubuntu 20.04.5 with OGRE 13.4.4 from Conan. I'll try rolling back to ogre 13.4.4, see if that changes anything.

**Comment by ThibaultLemaire** [comment]
So everything works now; This PR is ready for review :)

**Comment by wegank** [comment]
@ofborg build stuntrally stuntrally.passthru.tests

**Pull request merged**
