### PR TITLE
nvidiabl: 0.87 -> 2017-09-26

### LINKED ISSUE #36356: Please update nvidiabl package to use madsherlock/nvidiabl fork that adds support for Kernels >= 4.0.0
## Issue description

The [`nvidiabl`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/nvidiabl/default.nix) package points to guillaumezin/nvidiabl that is not maintained any more.

However there is a fork with an up-to-date driver that supports kernels >= 4.0.0 at https://github.com/madsherlock/nvidiabl

Would it be possible to update the nix package to use that repository?

Thanks!

### Steps to reproduce

N/A

## Technical details

```shell
$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.7, NixOS, 17.09.3109.48a76ca6f57 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.3109.48a76ca6f57"`
 - channels(user): `"unstable-18.03pre129189.c2fbd472a4e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

### PR DESCRIPTION
**Pull request by abbradar**
###### Motivation for this change

Fix build on newer kernels. Fixes #36356.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

@stefano-m can you test this works for you?

### CODE REVIEW

**Comment by stefano-m** [comment]
@abbradar I can give it a go, but I need some guidance about _how_ to do that.

**Comment by abbradar** [comment]
@stefano-m  Find out your current commit with `nixos-version` (look at the suffix), then clone nixpkgs repository (`git clone https://github.com/NixOS/nixpkgs`), checkout current commit (`git checkout commit_hash`), fetch my changes (`git fetch origin refs/pull/37100/head`) and cherry-pick my patch atop your current commit (`git cherry-pick 085be65ae14491551a0997801e0e802d3aef5510`). Then you can rebuild nixpkgs with `nixos-rebuild switch -I /path/to/repository`.

**Comment by yorickvP** [comment]
Add `nativeBuildInputs = kernel.moduleBuildDependencies;` and remove the libelf one. You can switch to my fork, it has a patch for that kernel warning.

**Comment by yorickvP** [comment]
You're also welcome to add me to the `meta.maintainers = [maintainers.yorickvp]` so I'll know if something breaks.

**Comment by abbradar** [comment]
@yorickvP Thanks, did just that! I didn't use your fork to not deviate from upstream more than needed to build a working module -- the warning is not that serious.

**Comment by abbradar** [comment]
Ah, wait, I took a look at your original PR. Yeah, a _kernel_ warning isn't good at all. I'll switch to your fork.

**Comment by yorickvP** [comment]
Nah, they result in a compiler warning that you can easily ignore. I think people use them for comments sometimes.

**Comment by abbradar** [comment]
@GrahamcOfBorg build linuxPackages.nvidiabl linuxPackages_latest.nvidiabl

**Pull request merged**
