### PR TITLE
hwinfo: 21.38 -> 21.50

### PR DESCRIPTION
**Pull request by c0bw3b**
###### Motivation for this change
Update `hwinfo` and its `libx86emu` dependency to latest stable releases 
Also fixed the pkgconfig .pc file of hwinfo (prefix was wrong)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by c0bw3b** [comment]
```shell
$ ./result/bin/hwinfo --version
21.50

$ ./result/bin/hwinfo --short
cpu:                                                            
                       Intel(R) Core(TM) i7-4790S CPU @ 3.20GHz, 3200 MHz
                       Intel(R) Core(TM) i7-4790S CPU @ 3.20GHz, 3200 MHz
                       Intel(R) Core(TM) i7-4790S CPU @ 3.20GHz, 3200 MHz
                       Intel(R) Core(TM) i7-4790S CPU @ 3.20GHz, 3200 MHz
keyboard:
[...]
```

**Review by orivej — APPROVED** [review]
Re. `DESTDIR=$(out)" "LIBDIR=/lib`: technically this is a lie — our DESTDIR is empty and LIBDIR is `${out}/lib` (this is usually achieved by setting `PREFIX=$(out)`) — but if the application works anyway, and since you did not write this, this is good to go.

**Comment by bjornfor** [comment]
Applied to master (7a32e683938dda07590da2ddf23dae211b8b0c1d, 076842028036fd4901779532a0fcdb2fdb1e86e9). Thanks!

**Comment by orivej** [comment]
@bjornfor Did you not merge this because you've added a comment `#enableParallelBuilding = true;`? Does this mean that `hwinfo` fails to build in parallel?

**Comment by c0bw3b** [comment]
I had that comment in the first place and then removed entirely it in a second push.
And it was commented because I did encountered failure to build hwinfo when trying to enable parallel building

**Comment by bjornfor** [comment]
I didn't change the PR, I rebased locally without doing any changes. I didn't notice to the commented line :-/

**Pull request closed without merging**
