### PR TITLE
linux: cleanup common-config after drop of 4.9

### PR DESCRIPTION
**Pull request by fabianhjr**
linux-4.9 was dropped on 8d9133c67d25c15348ec12720ee2ce90762d4d4c / #200218

next lowest version in nixpkgs is 4.14 so cleaning up options

###### Description of changes

whenOlder < 4.14 x  => remove option
whenAtLeast <= 4.14 => remove conditional

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabianhjr** [comment]
Please note the following comment: https://github.com/NixOS/nixpkgs/pull/200218#issuecomment-1310122845

> We can drop them after the branch-off if we are worried about downstream usage. I think that would be a reasonable trade-off.

**Comment by fabianhjr** [comment]
On 6.0.Z the following options are unused:

```
warning: unused option: ANDROID
warning: unused option: DEBUG_INFO_BTF
warning: unused option: DEBUG_STACKOVERFLOW
warning: unused option: EXT4_ENCRYPTION
warning: unused option: F2FS_FS_ENCRYPTION
warning: unused option: INET_DIAG_DESTROY
warning: unused option: INET_MPTCP_DIAG
warning: unused option: INET_RAW_DIAG
warning: unused option: INET_TCP_DIAG
warning: unused option: INET_UDP_DIAG
warning: unused option: IO_STRICT_DEVMEM
warning: unused option: MODULE_ALLOW_BTF_MISMATCH
warning: unused option: RCU_PERF_TEST
```

**Comment by lovesegfault** [comment]
> On 6.0.Z the following options are unused:
> 
> ```
> warning: unused option: ANDROID
> warning: unused option: DEBUG_INFO_BTF
> warning: unused option: DEBUG_STACKOVERFLOW
> warning: unused option: EXT4_ENCRYPTION
> warning: unused option: F2FS_FS_ENCRYPTION
> warning: unused option: INET_DIAG_DESTROY
> warning: unused option: INET_MPTCP_DIAG
> warning: unused option: INET_RAW_DIAG
> warning: unused option: INET_TCP_DIAG
> warning: unused option: INET_UDP_DIAG
> warning: unused option: IO_STRICT_DEVMEM
> warning: unused option: MODULE_ALLOW_BTF_MISMATCH
> warning: unused option: RCU_PERF_TEST
> ```

We can land this without it, but it'd be great to:
1. If the option just changed names, then update the name
2. If the option is gone (e.f. `CONFIG_ANDROID`) then gate it to not be applied to kernels >= `6.0`

**Comment by fabianhjr** [comment]
@lovesegfault it seems like there are 2 already open PRs related to those unused options.

https://github.com/NixOS/nixpkgs/pull/141505

https://github.com/NixOS/nixpkgs/pull/164906

**Comment by fabianhjr** [comment]
Now that the branchoff has happened this is ready

**Comment by lovesegfault** [comment]
@fabianhjr Could you cherry-pick them together with this one, that way we can land one large cleanup?

**Comment by fabianhjr** [comment]
Sure

**Comment by fabianhjr** [comment]
Cherry-picked #164906

**Comment by fabianhjr** [comment]
:| don't know how I feel about this @lovesegfault, I would rather this Merge Request be more on the 0 rebuilds side.

**Comment by fabianhjr** [comment]
@K900 it seems like for this particular case it does work as a 0 rebuild change. :3

**Comment by K900** [comment]
Oh, sorry, I thought you were removing unused options here too.

**Comment by lovesegfault** [comment]
> :| don't know how I feel about this @lovesegfault, I would rather this Merge Request be more on the 0 rebuilds side.

I'll make sure all the kernels build, give me a moment

**Pull request merged**
