### PR TITLE
Revert "deltachat-desktop: remove noop override"

### PR DESCRIPTION
**Pull request by dotlambda**
Reverts NixOS/nixpkgs#239666

### CODE REVIEW

**Comment by figsoda** [comment]
Wouldn't it make more sense to revert #242425 instead?

**Comment by dotlambda** [comment]
> Wouldn't it make more sense to revert #242425 instead, since it is what caused the build failure?

Again, there is no build failure. Deltachat-desktop relies on a specific version of libdeltachat because it needs to be compatible with the latter's jsonrpc API.

**Comment by figsoda** [comment]
> Again, there is no build failure.

Edited the comment

> Deltachat-desktop relies on a specific version of libdeltachat because it needs to be compatible with the latter's jsonrpc API.

And reverting #242425 does exactly what you want

**Comment by dotlambda** [comment]
> And reverting #242425 does exactly what you want

Not quite. I would like to keep `python3.pkgs.deltachat` up to date.

**Pull request closed without merging**
