### PR TITLE
[WIP] Fix rebar3 release

### PR DESCRIPTION
**Pull request by ankhers**
I'm not quite ready to have this merged yet. I'm just putting this up so that people are able to test my changes. I would appreciate any feedback.

###### Motivation for this change
I wrote a [rebar32nix](https://github.com/ankhers/rebar32nix) tool (Read: rebar3 to nix) in order to help with building Erlang applications. I needed to make some minor modifications to the builder in order for my tool to work.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
cc @astro

**Comment by aanderse** [comment]
ping (triage)

**Comment by ankhers** [comment]
Hey, I will still be working on this. I was waiting for feedback on the most recent linked issue. I will just be moving ahead with this myself.

**Comment by happysalada** [comment]
Hey I just noticed this. I think the rebar3 release is in a good state now, perhaps we can close this?

**Comment by NickCao** [comment]
rebar3 looks good now.

**Pull request closed without merging**
