### PR TITLE
Add vimPlugins.{nvzone-menu,nvzone-minty,nvzone-volt}

### PR DESCRIPTION
**Pull request by fmway**
### Description of changes
nvzone-menu: https://github.com/nvzone/menu
nvzone-minty: https://github.com/nvzone/minty
nvzone-volt: https://github.com/nvzone/volt

### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by mrcjkb — CHANGES_REQUESTED** [review]
Thanks 🙏 

question: why the `nvchad-` prefixes? 
I can't see anything in the repos indicating that the plugins are specific to nvchad, and they don't appear to have nvchad in their names.

**Comment by fmway** [comment]
> question: why the `nvchad-` prefixes? I can't see anything in the repos indicating that the plugins are specific to nvchad, and they don't appear to have nvchad in their names.

I'm also not sure if I should use the nvchad prefix or not. Is it better to delete it? 😅

**Comment by teto** [comment]
it's better to follow upstream convention, which doesn't use nvchad (or I cant find it).

**Comment by PerchunPak** [comment]
The plugins are indeed don't depend on nvchad, but they have so generic names, that I would keep nvchad prefix

BTW, you forgot to specify dependencies. Could you please do it, similar to [here](https://github.com/NixOS/nixpkgs/blob/bd4f00ac7fa6b641777b5a7fb08911c456b4ed01/pkgs/applications/editors/vim/plugins/overrides.nix#L197-L199)?

**Comment by fmway** [comment]
> BTW, you forgot to specify dependencies. Could you please do it, similar to [here](https://github.com/NixOS/nixpkgs/blob/bd4f00ac7fa6b641777b5a7fb08911c456b4ed01/pkgs/applications/editors/vim/plugins/overrides.nix#L197-L199)?
Okay, I'll try it. Sorry if it took long. This is my first time

**Comment by teto** [comment]
what's sad is that I've uploaded some of these packages to luarocks.org so we could have dependency detection for free. I wont ask you to nixify those lua dependencies because it's a bit complex at the moment but with something like 
 https://github.com/NixOS/nixpkgs/pull/344320 it could get easier. Hopefully someone can resume that work.

**Comment by PerchunPak** [comment]
You accidentally removed all your changes. Also, please rebase all commits into three (one for a plugin)

**Comment by fmway** [comment]
My Bad. On my way

**Comment by fmway** [comment]
How about this?

**Comment by mrcjkb** [comment]
> it's better to follow upstream convention, which doesn't use nvchad (or I cant find it).

In that case I would suggest `nvzone-` prefixes. `nvchad-` is misleading.

**Comment by fmway** [comment]
> In that case I would suggest `nvzone-` prefixes. `nvchad-` is misleading. @teto what did you name the luarocks packages?

I don't think it's misleading. Because they were originally in nvchad's org. nvzone was recently created 🥲

**Comment by fmway** [comment]
> @teto what did you name the luarocks packages?

I found it.
https://luarocks.org/modules/neorocks/menu
https://luarocks.org/modules/neorocks/volt

**Comment by fmway** [comment]
> Why it was created?

nah, maybe to separate between core and just a plugins 😅. So, it's better nvzone- prefix, than nvchad-?

**Comment by khaneliman** [comment]
> > Why it was created?
> 
> nah, maybe to separate between core plugins and just a plugins 😅. So, it's better `nvzone-` prefix, rather than `nvchad-`?

Would make more sense than using a name they chose to move away from :P

**Review by PerchunPak — APPROVED** [review]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 357120`

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>vimPlugins.nvzone-menu</li>
    <li>vimPlugins.nvzone-minty</li>
    <li>vimPlugins.nvzone-volt</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Review by mrcjkb — APPROVED** [review]

**Comment by GaetanLepage** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 357120`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>vimPlugins.nvzone-menu</li>
    <li>vimPlugins.nvzone-minty</li>
    <li>vimPlugins.nvzone-volt</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>vimPlugins.nvzone-menu</li>
    <li>vimPlugins.nvzone-minty</li>
    <li>vimPlugins.nvzone-volt</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>vimPlugins.nvzone-menu</li>
    <li>vimPlugins.nvzone-minty</li>
    <li>vimPlugins.nvzone-volt</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>vimPlugins.nvzone-menu</li>
    <li>vimPlugins.nvzone-minty</li>
    <li>vimPlugins.nvzone-volt</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

**Review by GaetanLepage — APPROVED** [review]

**Comment by fmway** [comment]
thanks

**Pull request merged**
