### PR TITLE
wireshark: wayland support

### PR DESCRIPTION
**Pull request by Janik-Haag**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bjornfor** [comment]
How much bigger does the closure become?

**Comment by Janik-Haag** [comment]
Ouput of ```du -hc``` in the result directory wihtout the patch
```
13M	./bin
20K	./share/man/man4
168K	./share/man/man1
192K	./share/man
8,0K	./share/metainfo
820K	./share/wireshark/diameter
100K	./share/wireshark/wimaxasncp
1,6M	./share/wireshark/radius
640K	./share/wireshark/tpncp
12K	./share/wireshark/profiles/Bluetooth
12K	./share/wireshark/profiles/No Reassembly
8,0K	./share/wireshark/profiles/Classic
36K	./share/wireshark/profiles
60K	./share/wireshark/dtds
7,9M	./share/wireshark
12K	./share/applications
16K	./share/mime/packages
20K	./share/mime
8,0K	./share/icons/hicolor/16x16/mimetypes
8,0K	./share/icons/hicolor/16x16/apps
20K	./share/icons/hicolor/16x16
8,0K	./share/icons/hicolor/24x24/mimetypes
8,0K	./share/icons/hicolor/24x24/apps
20K	./share/icons/hicolor/24x24
12K	./share/icons/hicolor/64x64/mimetypes
12K	./share/icons/hicolor/64x64/apps
28K	./share/icons/hicolor/64x64
8,0K	./share/icons/hicolor/48x48/mimetypes
8,0K	./share/icons/hicolor/48x48/apps
20K	./share/icons/hicolor/48x48
8,0K	./share/icons/hicolor/32x32/mimetypes
8,0K	./share/icons/hicolor/32x32/apps
20K	./share/icons/hicolor/32x32
20K	./share/icons/hicolor/128x128/mimetypes
20K	./share/icons/hicolor/128x128/apps
44K	./share/icons/hicolor/128x128
40K	./share/icons/hicolor/256x256/mimetypes
52K	./share/icons/hicolor/256x256/apps
96K	./share/icons/hicolor/256x256
12K	./share/icons/hicolor/scalable/apps
16K	./share/icons/hicolor/scalable
268K	./share/icons/hicolor
280K	./share/icons
8,4M	./share
3,1M	./lib/wireshark/plugins/4.0/epan
36K	./lib/wireshark/plugins/4.0/codecs
20K	./lib/wireshark/plugins/4.0/wiretap
3,1M	./lib/wireshark/plugins/4.0
3,1M	./lib/wireshark/plugins
424K	./lib/wireshark/extcap
3,6M	./lib/wireshark
134M	./lib
154M	.
154M	total
```
with patch:
```
13M	./bin
20K	./share/man/man4
168K	./share/man/man1
192K	./share/man
8,0K	./share/metainfo
820K	./share/wireshark/diameter
100K	./share/wireshark/wimaxasncp
1,6M	./share/wireshark/radius
640K	./share/wireshark/tpncp
12K	./share/wireshark/profiles/Bluetooth
12K	./share/wireshark/profiles/No Reassembly
8,0K	./share/wireshark/profiles/Classic
36K	./share/wireshark/profiles
60K	./share/wireshark/dtds
7,9M	./share/wireshark
12K	./share/applications
16K	./share/mime/packages
20K	./share/mime
8,0K	./share/icons/hicolor/16x16/mimetypes
8,0K	./share/icons/hicolor/16x16/apps
20K	./share/icons/hicolor/16x16
8,0K	./share/icons/hicolor/24x24/mimetypes
8,0K	./share/icons/hicolor/24x24/apps
20K	./share/icons/hicolor/24x24
12K	./share/icons/hicolor/64x64/mimetypes
12K	./share/icons/hicolor/64x64/apps
28K	./share/icons/hicolor/64x64
8,0K	./share/icons/hicolor/48x48/mimetypes
8,0K	./share/icons/hicolor/48x48/apps
20K	./share/icons/hicolor/48x48
8,0K	./share/icons/hicolor/32x32/mimetypes
8,0K	./share/icons/hicolor/32x32/apps
20K	./share/icons/hicolor/32x32
20K	./share/icons/hicolor/128x128/mimetypes
20K	./share/icons/hicolor/128x128/apps
44K	./share/icons/hicolor/128x128
40K	./share/icons/hicolor/256x256/mimetypes
52K	./share/icons/hicolor/256x256/apps
96K	./share/icons/hicolor/256x256
12K	./share/icons/hicolor/scalable/apps
16K	./share/icons/hicolor/scalable
268K	./share/icons/hicolor
280K	./share/icons
8,4M	./share
3,1M	./lib/wireshark/plugins/4.0/epan
36K	./lib/wireshark/plugins/4.0/codecs
20K	./lib/wireshark/plugins/4.0/wiretap
3,1M	./lib/wireshark/plugins/4.0
3,1M	./lib/wireshark/plugins
424K	./lib/wireshark/extcap
3,6M	./lib/wireshark
134M	./lib
154M	.
154M	total
```

**Comment by Janik-Haag** [comment]
The error it thorws without the patch is:
```
** (wireshark:31859) 10:38:21.859847 [GUI WARNING] -- Could not find the Qt platform plugin "wayland" in ""
 ** (wireshark:31859) 10:38:21.859926 [GUI ERROR] -- This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

[1]    31859 IOT instruction (core dumped)  ./bin/wireshark
```
And yes the size stays the same.

**Review by Tungsten842 — APPROVED** [review]

**Comment by Ma27** [comment]
With the change:
```
$ nix path-info -Sh ./result
/nix/store/axi79fd42lv3xwrilgg0ka5x96ird9hv-wireshark-qt-4.0.3	647.4M
```
Without the change:
```
$ nix path-info -Sh ./result
/nix/store/2v827qwv7s697w5i6x9a6wd7hn2zjqyy-wireshark-qt-4.0.3	637.6M
```

I think the increase is OK, especially considering that this is a dsktop application.

**Comment by QuantMint** [comment]
This [breaks the darwin build](https://logs.nix.ci/?key=nixos/nixpkgs.219242&attempt_id=734f8922-5ed4-48e9-b5a2-a09051b5aa5c), qtwayland doesn't work on darwin. Fixing it in https://github.com/NixOS/nixpkgs/pull/219480.

**Pull request merged**
