### PR TITLE
gnome3: only maintain single GNOME 3 package set

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
GNOME 3 was split into 3.10 and 3.12 in #2694. Unfortunately, we barely have the resources to update a single version of GNOME. Maintaining multiple versions just does not make sense. Additionally, it makes viewing history using most Git tools bothersome.

###### Things done
I renamed `pkgs/desktops/gnome-3/3.24` to `pkgs/desktops/gnome-3`, removed
the config variable for choosing packageset (`environment.gnome3.packageSet`), and removed the `gnome3_24` derivation from `all-packages.nix`. On top of that, I modified the maintainer script not to require the directory path.

Closes: #29329

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

##### Follow-ups
* Maintainer script can be updated to pick up any version of a package available on FTP.
---

cc @teh @vcunat @lethalman

### CODE REVIEW

**Comment by jtojnar** [comment]
It does not look like a mass rebuild so I will just pointed it back to master.

**Comment by jtojnar** [comment]
Can we move this forward?

**Comment by zimbatm** [comment]
should this be cherry-picked for 17.09? /cc @globin

**Comment by vcunat** [comment]
It would simplify further cherry-picking of gnome fixes to 17.09, though that might not be easy anyway due to expected update 3.24 -> 3.26.

**Comment by zimbatm** [comment]
Yeah we'll see. I pushed it to the 17.09 branch as well in the end.

**Pull request merged**
