### PR TITLE
bup: 0.32 -> 0.33.2

### PR DESCRIPTION
**Pull request by rnhmjoj**
###### Description of changes

Version bump with numerous bug fixes

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- Tested:
  - [x] `bup index`
  - [x] `bup save`, `bup restore`
  - [x] `bup web`
  - [x] `bup fuse`
  - [x] `bup fsck -g`   
- [x] Tested compilation of all packages that depend on this change
- [x] Tested basic functionality of all binary files
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by ck3d — COMMENTED** [review]
LGTM

**Review by ck3d — APPROVED** [review]

**Comment by Atemu** [comment]
This broke darwin support:

```
building
build flags: SHELL=/nix/store/mxvgjwzdvrl81plvgqnzbrqb14ccnji6-bash-5.2-p15/bin/bash MANDIR=\$\(out\)/share/man DOCDIR=\$\(out\)/share/doc/bup BINDIR=\$\(out\)/bin LIBDIR=\$\(out\)/lib/bup
fatal: not a git repository (or any of the parent directories): .git
clang -I/nix/store/2rrfpkq6cr8ppip9szl0z1qfdlskdinq-python3-3.10.12/include/python3.10 -I/nix/store/2rrfpkq6cr8ppip9szl0z1qfdlskdinq-python3-3.10.12/include/python3.10 -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/nix/store/vnn3dp5cyjlknkqxmi29vbg812ml5m7r-libxcrypt-4.4.35/include -Wno-unused-command-line-argument -D_FILE_OFFSET_BITS=64 -Wno-unknown-pragmas -Wsign-compare -O2 -Wall -Werror -Wformat=2 -MMD -MP -D BUP_DEV_BUP_EXEC=1 -I/private/tmp/nix-build-bup-0.33.2.drv-0/source/src -I src  -g lib/cmd/bup.c src/bup/compat.c src/bup/io.c -lpython3.10 -lcrypt -ldl -L/nix/store/vnn3dp5cyjlknkqxmi29vbg812ml5m7r-libxcrypt-4.4.35/lib -framework CoreFoundation  -g -fPIE -o dev/bup-exec
lib/cmd/bup.c:153:14: error: implicit declaration of function '_NSGetExecutablePath' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    int rc = _NSGetExecutablePath(spath, &size);
             ^
1 error generated.
make: *** [GNUmakefile:185: dev/bup-exec] Error 1
```

**Comment by Atemu** [comment]
https://github.com/NixOS/nixpkgs/pull/242634

**Comment by rnhmjoj** [comment]
The package was unmaintained and I can't test darwin. Add yourself to the list, if you can.

**Comment by Atemu** [comment]
As for maintainership: I don't have any direct connection to bup. I don't use it and don't have a setup to test it easily. I only care because git-annex depends on it and its build is therefore transitively broken on Darwin rn.

Best I could do is test the build and basic execution but I feel ofBorg is sufficient for a smoke check. It detected the build error btw, it just doesn't log that as a CI failure which means it wasn't red. Perhaps because it can't differentiate between intended eval failure and unintended build failure, I don't know.  
You really have to make sure to check ofBorg manually. I forget to do that all the time too.

**Comment by rnhmjoj** [comment]
> Best I could do is test the build and basic execution but I feel ofBorg is sufficient for a smoke check. 

You probably know how to fix common build error on darwin, I don't. So, it would be an improvement.

**Comment by Atemu** [comment]
Sure, when there's a new build failure on Darwin for something, feel free to ping me and/or the darwin-maintainers team.

**Pull request merged**
