### PR TITLE
heroku: Update to 4.27.6. Fixes #10298

### LINKED ISSUE #10298: Heroku toolbelt core plugins don't work
With `heroku-3.32.0` installed on NixOS 15.09, none of the core plugins (beside `heroku-apps`) appear to work:

```
$ nixos-version
15.09.587.dbf2827 (Dingo)

$ heroku fork --help
Installing core plugins heroku-cli-addons, heroku-apps, heroku-fork, heroku-git, heroku-local, heroku-run, heroku-status...
 ▸    
 !    fork is not a heroku command. See `heroku help`.
```

I think this might be a regression, because I don't remember seeing `Installing core plugins heroku-cli-addons, heroku-apps, heroku-fork, heroku-git, heroku-local, heroku-run, heroku-status...` on every invocation of the `heroku` command before nixos-15.09.

### PR DESCRIPTION
**Pull request by ocharles**

### CODE REVIEW

**Comment by ocharles** [comment]
Please don't merge just yet, want to make sure @rehno-lindeque can at least also use this.

**Comment by rehno-lindeque** [comment]
The existing heroku package is completely unusable for me at the moment (it randomly broke two or so days ago), so definitely :+1: on this. Works for me on my laptop.

Technically `heroku-cli` is a different package than the original `heroku` since this is a rewrite of the original toolchain and I do notice that some commands are missing, notably `heroku logs`. Might also be surprising for people since they will now have to call `heroku-cli` directly instead of using `heroku`.

**Comment by ocharles** [comment]
I don't think it's meant to be called `heroku-cli`, because the self-help documentation for the command mentions `heroku`, so I wonder if something built wrong. It is a problem that `logs` (and other commands are missing though)...

**Comment by rehno-lindeque** [comment]
I saw over [here](https://blog.heroku.com/archives/2015/3/19/making_cli_plugins_better_with_a_new_architecture#discovery-and-installation) that they mention papertrail as a logging plugin for the new cli. I wonder if that's intended to replace the `heroku logs` command.

**Comment by zimbatm** [comment]
This is nice but heroku-cli is far from complete yet. It might be best to install it as heroku-cli in the top-level instead.

**Comment by ocharles** [comment]
I've abandoned this.

**Pull request closed without merging**
