### PR TITLE
octoprint: fix build due to black

### PR DESCRIPTION
**Pull request by gador**
This is a quick fix for the build error described in #165323 

Signed-off-by: florian on nixos (Florian Brandes) <florian.brandes@posteo.de>

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 165389` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>octoprint</li>
  </ul>
</details>

**Review by fabaff — APPROVED** [review]
Change looks good to me.

**Comment by fabaff** [comment]
@ofborg eval

**Comment by siraben** [comment]
Result of `nixpkgs-review pr 165389` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>octoprint</li>
  </ul>
</details>

**Comment by SuperSandro2000** [comment]
It would be a much better idea to remove black from whatever it is using instead of using an older version.

**Comment by gador** [comment]
Hi @SuperSandro2000 
I figured out the dependency on black. The dependency graph looks like this:
```
  /nix/store/kjrycs7dg6rjpfm292l8067yfvkhqdxq-python3.9-black-22.1.0.drv
  /nix/store/w53810z4gpvzjql74v9vbccr7ax84pgm-python3.9-ipython-8.0.1.drv
  /nix/store/2hic8mycpw8mgym52r6v74vh7dha96bs-python3.9-python-dotenv-0.19.2.drv
  /nix/store/b3daf7cb9jljf16z8ivcrd3vjgjbz4qx-python3.9-Flask-1.1.4.drv
  /nix/store/0nzqh8x8mbnf2jmkx8qqa4h06x37vdlg-python3.9-flask-login-0.5.0.drv
  /nix/store/xypr2mx5ln80rw6svvxf5rk6czljiz23-python3.9-Flask-SQLAlchemy-2.5.1.drv
  /nix/store/zmrdgh08bw0d73f2jpddsxlf7yzz9q8y-python3.9-factory-boy-3.2.1.drv
  /nix/store/nhijyvv8v4xywmlrflhilsxad3mlynsx-python3.9-pytest-randomly-3.11.0.drv
  /nix/store/26dl4ijj969jj91cgsygkkg79g4y28fm-python3.9-httplib2-0.20.3.drv
  /nix/store/jskyy09y8wj4nxbp2f35dxyc0d243fv8-python3.9-Flask-RESTful-0.3.9.drv
  /nix/store/w7hl3n3qykk9sdh1hx4fnl1dlpc18sh4-python3.9-Flask-Limiter-1.4.drv
  /nix/store/w80ja2ls3xg0ghhh0yhc0w3m50is3xy4-python3.9-httpbin-0.7.0.drv
  /nix/store/2bi64wmc89jnc1h7cpqqzazv2ajvl7dd-python3.9-pytest-httpbin-1.0.1.drv
  /nix/store/ppxjx5j6rkyv0klg7n9lvjv808q05sn0-python3.9-uvicorn-0.16.0.drv
  /nix/store/wwbh01qzv1y8gdzm5db0z22c0qdgyhcr-python3.9-httpcore-0.14.4.drv
  /nix/store/z21jndk0anc6dmviq4d1255dfdy0wbz2-python3.9-httpx-0.21.3.drv
  /nix/store/plpsjr2hb8l215kgq7sp6rphsjll1bcc-python3.9-sanic-testing-0.8.2.drv
  /nix/store/h1v56fsx0gb7cj990kbdx0p9glxf7fwp-python3.9-sanic-21.12.1.drv
  /nix/store/2kdigbbkbihiv9ayrrbh4489mma9il3z-python3.9-sanic-testing-0.8.2.drv
  /nix/store/rz8npi2yp2y32f61hknv0bpwv2897d06-python3.9-Flask-Script-2.0.6.drv
  /nix/store/3wh7hnyl2lha8dd6xq69sjyz1wm5hgbd-python3.9-Flask-Assets-2.0.drv
  /nix/store/v4sh28fr316mmqd7yhw5cxvjp0cj6rmq-python3.9-httpretty-1.1.4.drv
  /nix/store/ir6yz3lzg2sw6m4w5cxk1al2cijgfv45-python3.9-adal-1.2.7.drv
  /nix/store/j11bagzr9dxfc2k4q16j6rcs58pd12fh-python3.9-msrest-0.6.21.drv
  /nix/store/j5q7vymfg75q4h8prfkq1c2f78qyxpr4-python3.9-msrestazure-0.6.4.drv
  /nix/store/akpp3k6iyzlkdg1yzv2f5isclg3inq97-python3.9-azure-servicebus-7.5.0.drv
  /nix/store/a82nlbcrk2dhy21h56hn8qkqr5jvjlqd-python3.9-kombu-5.2.4.drv
  /nix/store/nj91kq2m9gmvgwmpjrr0cwnr4y7cja3f-python3.9-Flask-Cors-3.0.10.drv
  /nix/store/l67jki7vm62r3hfrnss9lkvb2rchmfrr-python3.9-moto-3.0.2.drv
  /nix/store/n826jv3f2n8agm0rz1117d4cvlfga03k-python3.9-Flask-Babel-1.0.0.drv
  /nix/store/rn0xkx8ind6gds2864cx0daazb08kaas-python3.9-falcon-3.0.1.drv
  /nix/store/rrpm4cfx4vca6dc2n2cxa2pqgjliq3ii-python3.9-celery-5.2.3.drv
  /nix/store/pqkn1zfhmv9w45whyh6jhxwi9q7bgzlc-python3.9-sentry-sdk-1.5.8.drv
  /nix/store/mwfqc4531zr75ywj054q11xgkld1bwbh-python3.9-OctoPrint-1.7.3.drv
```
So `ipython` requires `black` as a build input. 

I think the way forward is to merge  #165328 in order to update octoprint and remove all those old version dependencies.

**Pull request merged**
