### PR TITLE
Rework grsecurity support

### PR DESCRIPTION
**Pull request by joachifm**
###### Motivation for this change

Make grsecurity easier to use on NixOS: reduce the number of options and tune for desktop use, with minimal configuration.
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

I'm at a point where I spend more time fixing merge conflicts than adding features, so probably a good time to propose it. See commits for details. I've tested this quite extensively, but it's a bit "opinionated", I guess, so may not be to everyone's tastes.

I've drafted a chapter on configuration & some release notes, but will tinker some more with them before integration.

### CODE REVIEW

**Comment by copumpkin** [comment]
I like the simplification in principle, so 👍, but I haven't looked carefully so can't say yet. What do you mean by "tune for desktop use" though? All my NixOS boxes are server (headless) boxes and that's a pretty common use case. Are you factoring in that use case?

Also cc @thoughtpolice who's given this some thought in the past.

**Comment by joachifm** [comment]
Tuning for desktop use means prioritizing casual desktop users, e.g., minimising re-compilation and favoring compatibility with applications such as firefox and chromium, preferably wine as well. For headless servers you probably want to compile your own kernel with everything hard-coded. If you're doing anything security sensitive, I don't know that using an off-the-shelf distro kernel is such a good idea.

My opinion is that even if you were to be able to boot this kernel with all sysctls disabled, you're still in pretty good shape, but it is possible to switch into a profile that, upon boot, will have certain chroot restrictions disabled, for example. But you still have mandatory PaX memory hardening, memory sanitization, and address space layout randomization, &c. 

If somebody wants a `_nixos_server` variant, I encourage them to step up and maintain it, I'm not going to. Given the severe usability bugs that have gone unnoticed for a long time, I'm quite certain that a proliferation of variants does nothing but give the illusion of choice.

**Comment by copumpkin** [comment]
Hmm, I've been actively using that (server) kernel build outside of NixOS (on a different distro). I don't expect you to maintain it, but can you not get rid of it? Or is that just going to force a bunch of old code to be lying around?

**Comment by joachifm** [comment]
Are there specific features you're concerned about related to the server deployment? The sysctl tuning or maybe the TCP simultaneous connect feature? It's not like the NixOS kernel *won't* work in a server deployment. 

Keeping the old code would retain quite a bit of cruft (i.e.., all of the old grsecurity builder). The replacement would be a `linux-grsecurity` base kernel with `kernelPatches.grsecurity` and something like the following `extraKernelConfig`:
```
GRKERNSEC y
PAX y # not strictly required, should be selected automatically ...
GRKERNSEC_CONFIG_AUTO y
GRKERNSEC_CONFIG_SERVER y
GRKERNSEC_CONFIG_PRIORITY_SECURITY y
GRKERNSEC_SYSCTL n # not sure if this is strictly necessary, but just to be sure.
```

I don't see why something like that couldn't be added for headless server deployments. Then you could also do away with the usermode helper patch, that weakens vanilla grsecurity (as you've pointed out before). Note that the old grsec kernel also included other nixos-only stuff that further weakens the grsec protections vs vanilla, so this could be considered strictly better than what is currently available (for use in a non-NixOS environment).

**Comment by copumpkin** [comment]
@joachifm I'll need to check. I'm mostly using it in a virtualized environment and assumed I needed the Xen guest stuff turned on, but that might only be necessary for paravirtualization (that would make sense to me at least). I haven't really done much testing and am about to go on vacation for two weeks, so I guess I'll figure out if anything breaks when I get back 😄 

Either way, thanks for putting so much effort into this. I'm hoping we can get more people on a nice hardened-by-default system and then there will be more people to help maintain improvements!

**Comment by joachifm** [comment]
@copumpkin ah, yes, Xen and friends may not work so well with the default NixOS kernel (UDEREF and some memory sanitization features are said to cause problems for Virtualbox/Xen, but I've never had cause to use anything but KVM). My goal is that building custom variants should be utterly trivial, so I'm sure we can figure something out, but I don't think there's anything in the new implementation that prevents iterating on that part of the interface (it's the part I'm least happy about btw).

**Comment by copumpkin** [comment]
Utterly trivial modulo a 2-hour kernel build :) but yeah in principle I
agree with you, and if it gets annoying I'll put some thought into a common
virtualization kernel to put into hydra again

**Comment by joachifm** [comment]
@copumpkin as a stop-gap solution, I'll probably add a kernel package (but not package set) corresponding to server+security+xen. It'll be untested but ought to alleviate some of the pain.

**Comment by thoughtpolice** [comment]
I think this is fine in principle, looking over the changes. Also, I agree that the proliferation of kernels really gives an illusion of choice, so minimizing the common cases is fine - the secure desktop variant is perfectly OK for 'normal' or 'production' usage. Personally I still think this needs more work[1] to make it more usable but this is all a step in the right direction, vs my shitty old version.

Making sure we can handle Xen, etc is all a separate task IMO, so I'd suggest just moving forward with this and discuss what we need as the next step.

As for server kernels, I'd suggest punting on them for now, but include them if you want. Server mode does enable some more important features but some of them really don't work for us yet (such as TPE, but things like the IO protections for `hwclock` etc are nice). So I wouldn't worry about that either, just yet.

However, the real benefit of a server kernel is that you build it yourself in a restricted environment, so you can enable features like RANDSTRUCT and HIDESYM to offer enhanced protections (self-built kernels are also important as you get features like Intel memory protection keys, because execute-only pages are worthless against code-reuse attacks if you can just download a copy of the kernel from your distribution and look at it).

[1] Obviously, my NixOS-related time these days is minimal since I have a million other open source commitments, but I'd be willing to find my notes on this and write them down somewhere fully, sometime.

**Comment by joachifm** [comment]
@copumpkin @thoughtpolice thank you for the feedback. There's still lots of room for improvement, but I'll go ahead with this for now.

**Comment by 8573** [comment]
Why is this incompatible with ZFS?

**Comment by joachifm** [comment]
@8573 originally due to boot failure. I do not test zfs with new releases of zfs-on-linux or grsecurity. If you are interested, please do test it and report back.

**Comment by 8573** [comment]
@joachifm I deleted the non-ZFS assertion in the grsecurity module and the `meta.broken` line set to true for grsecurity in the SPL (Solaris Porting Layer; a ZFS dependency) package definition, enabled grsecurity, and ran `nixos-rebuild`; SPL indeed failed to build. ([The build error][build-err], in case it's useful.)

[build-err]: <https://gist.github.com/8573/471be9e26052e20e9d216f5656227ea3>

**Comment by joachifm** [comment]
@8573 thanks for testing, feedback like this is crucial for getting grsec support into decent shape.

spl is broken on vanilla linux 4.7 as well, so I'm not sure if the build error is directly related to grsec. Probably needs revisiting once it builds against 4.7. 

My primary concern has been to lower the bar for using grsec, so I've probably been overly conservative in some cases wrt. disabling potentially problematic features/modules. A problem that manifests as a build error is fairly benign IMO, the more insidiuous ones cause problems at runtime (which was the problem with zfs, originally, iirc). In those cases I've generally opted to disable features just to be sure. With more testing, I hope this situation improves.

**Pull request merged**
