### PR TITLE
netsurf: 3.5 -> 3.8

### PR DESCRIPTION
**Pull request by samueldr**
###### Motivation for this change

Updates netsurf and related libraries.

The default config for netsurf (using sixel ui) wasn't tested, I can't get it to work, in the previous iteration either. The gtk ui, though works fine.

###### Things done

- ✔️ Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - ✔️ NixOS
   - 🔲 macOS
   - 🔲 other Linux distributions
- 🔲 Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- ✔️ Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- ✔️ Tested execution of all binary files (usually in `./result/bin/`)
- 🔲 Determined the impact on package closure size (by running `nix path-info -S` before and after)
- ✔️ Assured whether relevant documentation is up to date
- ✔️ Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Mic92** [comment]
@GrahamcOfBorg build netsurf

**Comment by mmahut** [comment]
@GrahamcOfBorg build netsurf

**Comment by fgaz** [comment]
Ping :)

**Comment by samueldr** [comment]
It has some issues, but fewer than the previous version:

Tried to load up GitHub:

image

I had some (4) with nixos.org, but see, it works...

image

This is an improvement to the current behaviour of not working after showing empty windows.

image

So... erm I'm not sure it was acting that way back in January. Not sure where to go from here.

**Comment by S-NA** [comment]
According to the Netsurf mailing list, the last call for fixes to land in 3.9 is happening now. The version is expected to fix a lot of issues. [Including incompatibilities with newer versions of cURL](https://bugs.netsurf-browser.org/mantis/view.php?id=2663) which I encounter when running Netsurf using this PR. 

I have an environment with nix-shell for developing Netsurf and the build it produces seems to work with no issues. Maybe merge this and make a note to update to the 3.9 release soon or perhaps wait, since the release is not too far off. That said [feedback is requested](https://listmaster.pepperfish.net/pipermail/netsurf-users-netsurf-browser.org/2019-July/014409.html) against their CI builds.

**Comment by fgaz** [comment]
+1 for merging this for now and seeing what happens with 3.9 once it's released

**Comment by samueldr** [comment]
Let's wait; no change here is worth it since it's likely close; 3.9 is likely to fix the issue if I understand it right.

**Comment by samueldr** [comment]
Turns out the update didn't fix the issue with the certificates being unknown, but I figured out a solution to the problem. See #65360.

**Pull request closed without merging**
