### PR TITLE
pythonPackages.flask-swagger-ui: init at 3.20.9

### PR DESCRIPTION
**Pull request by vanschelven**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by risicle** [comment]
Again, this isn't actually picking up any tests - but this time because it looks like upstream doesn't _have_ any.

**Comment by vanschelven** [comment]
> Again, this isn't actually picking up any tests - but this time because it looks like upstream doesn't _have_ any.

Updated accordingly

**Comment by vanschelven** [comment]
@risicle or others: anything I can do to move this forward? I'd like to think I've dealt with all comments.

**Review by risicle — APPROVED** [review]

**Review by doronbehar — APPROVED** [review]

**Comment by ryantm** [comment]
@GrahamcOfBorg  build pythonPackages.flask-swagger-ui

**Pull request merged**
