### PR TITLE
cc-wrapper: add support for `hardbackedgecfi` hardening flag on x86_64 & aarch64

### PR DESCRIPTION
**Pull request by risicle**
## Description of changes

(This sits on top of  #318256 ~(go review that!)~, because it takes advantage of a refactoring done there - the only "interesting" commit in this PR is the last one)

Some background: https://discourse.nixos.org/t/future-design-of-hardening-flags/38826

This experimentally implements the hardening flag `hardbackedgecfi` (**hard**ware-based **back**ward edge **C**ontrol **F**low **I**ntegrity) _in different ways_ on the x86_64 and aarch64 linux platforms. The flag is only enabled on the `pkgsExtraHardening` package set here.

Here's where I need some help - I don't have access to hardware that implements either of these features. So while I can do a large rebuild and ensure it doesn't break anything on older systems (for which the features are effectively a no-op), I'm unable to find out how many packages these flags break when the features are actually _active_.

On x86_64 this enables CET "shadow stack" features implemented in (a seemingly random selection of) new Intel processors and AMD Zen3+. It requires a 6.6+ kernel. Helpfully those VPS providers that _do_ have processors supporting this don't necessarily expose the feature to guests, so I'm probably appealing to people with bare metal here to be able to test this properly.

On aarch64 this uses "pac-ret" - pointer authentication of return addresses on the stack. This uses instructions added in ARM 8.3. Unfortunately most (all?) dev board SoCs don't implement anything further than 8.2, and the most widely used processor for cloud ARM instances, the Ampere Altra series, is also ARM 8.2. I do hear that the latest AWS Gravitons implement ARM 9.0, so that's a possibility (I have no personal AWS account though). So far I've managed to test packages (built on native ARM 8.2 hardware) on qemu's TCG aarch64 implementation - which luckily _does_ implement the pointer authentication instructions. Although it's obviously extremely slow and it took me a weekend to (re-)build a small selection of packages with good test suites on some fairly beefy x86_64 hardware. And there are some spurious test failures caused by running the tests on qemu in the first place which doesn't help..

What am I trying to discover? Whether there's significant overlap in the sets of packages broken by these two features. If there isn't, they probably shouldn't be covered by the same hardening flag and I should rethink this.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by numinit** [comment]
How exactly do I turn this on? I've compiled something like `.#pkgsExtraHardening.gqrx` but only see `x86_Thread_features:` in /proc/self/status. I see `user_shstk` in /proc/cpuinfo (I'm on zen4) and am running:

`Linux monomyth 6.8.11-xanmod1 #1-NixOS SMP PREEMPT_DYNAMIC Tue Jan  1 00:00:00 UTC 1980 x86_64 GNU/Linux`

**Comment by alois31** [comment]
https://sourceware.org/git/?p=glibc.git;a=commit;h=55d63e731253de82e96ed4ddca2e294076cd0bc5 looks relevant, as it disabled shadow stack by default.

**Comment by risicle** [comment]
Good find, my guess is that they needed to do that because certain unnamed distributions started blindly enabling the flag in their builds before it was possible to test for breakage.

I guess we could make `pkgsExtraHardening` revert that change.

**Comment by numinit** [comment]
I've actually tried that environment variable and still don't see it...

**Comment by numinit** [comment]
OK, I actually do see it now but not how I originally thought.

```
GLIBC_TUNABLES=glibc.cpu.hwcaps=SHSTK strace ./result/bin/gqrx 2>&1 | grep prctl
arch_prctl(ARCH_SET_FS, 0x7f849aa68740) = 0
arch_prctl(ARCH_SHSTK_ENABLE, 0x1)      = 0
arch_prctl(ARCH_SHSTK_STATUS, 0x7fffc5c5d400) = 0
arch_prctl(ARCH_SET_FS, 0x7f0cf80e2f40) = 0
```

```
strace ./result/bin/gqrx 2>&1 | grep prctl
arch_prctl(ARCH_SET_FS, 0x7fa38e6a8740) = 0
arch_prctl(ARCH_SET_FS, 0x7fe76625bf40) = 0
```

**Comment by numinit** [comment]
Update: success!

`GLIBC_TUNABLES=glibc.cpu.hwcaps=SHSTK:glibc.cpu.x86_shstk=on ./result/bin/gqrx`

```
x86_Thread_features:    shstk 
x86_Thread_features_locked:
```

**Comment by numinit** [comment]
From what I understand, there are a few considerations here:
- the ENDBR opcodes inserted by the compiler to mark valid branch targets on x64 are NOPs on old CPUs, so it should be safe to compile this on CPUs that don't support it
- maybe we should use `-fcf-protection=full`: https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html#index-fcf-protection
- those tunables need to be enabled by default somehow

**Comment by risicle** [comment]
>     * the ENDBR opcodes inserted by the compiler to mark valid branch targets on x64 are NOPs on old CPUs, so it should be safe to compile this on CPUs that don't support it
>     * maybe we should use `-fcf-protection=full`: https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html#index-fcf-protection though the backedge CFI flag would then mean more than pac-ret

TODO. I'm currently only looking at stack-protecting features as they appear to have fewer caveats. I expect we'll end up covering forward-edge CFI with a different flag.

>     * those tunables need to be enabled by default somehow

On it.

**Comment by numinit** [comment]
I'll spend about an hour bootstrapping everything again with those enabled :-)

**Comment by risicle** [comment]
Hopefully this doesn't cause a rebuild for non-x86.

It builds for me.

**Comment by numinit** [comment]
Alright, now we're cooking. PCRE hates this.

```
./test-driver: line 109:  3769 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: pcre_jit_test
FAIL: RunTest
PASS: RunGrepTest
=================================
   PCRE 8.45: ./test-suite.log
=================================

# TOTAL: 3
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: pcre_jit_test
===================

Running JIT regression tests
  target CPU of SLJIT compiler: x86 64bit (little endian + unaligned)
  in  8 bit mode with UTF-8  enabled and ucp enabled:
............................................................
............................................................
............................................................
............................................................
............................................................
............................................................
............................................................
............................................................
............................................................
.......................FAIL pcre_jit_test (exit status: 139)

FAIL: RunTest
=============


PCRE C library tests using test data from ./testdata
PCRE version 8.45 2021-06-15

---- Testing 8-bit library ----

Test 1: Main functionality (Compatible with Perl >= 5.10)
  OK
  OK with study
  OK with JIT study
Test 2: API, errors, internals, and non-Perl stuff (not UTF-8)
  OK
  OK with study
Segmentation fault (core dumped)
 
** Test 2 requires a lot of stack. If it has crashed with a
** segmentation fault, it may be that you do not have enough
** stack available by default. Please see the 'pcrestack' man
** page for a discussion of PCRE's stack usage.
 
FAIL RunTest (exit status: 1)

============================================================================
Testsuite summary for PCRE 8.45
============================================================================
# TOTAL: 3
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  2

```

**Comment by numinit** [comment]
:sweat_smile: What on earth

```
[441571.930599] ------------[ cut here ]------------                                                                                                                                                                         
[441571.930605] WARNING: CPU: 34 PID: 4144666 at ssp_get+0x77/0x90                                                                                                                                                           
[441571.930612] Modules linked in: tcp_diag inet_diag nhpoly1305_avx2 nhpoly1305_sse2 nhpoly1305 chacha_generic chacha_x86_64 libchacha adiantum libpoly1305 camellia_generic camellia_aesni_avx2 camellia_aesni_avx_x86_64 c
amellia_x86_64 cast5_avx_x86_64 cast5_generic cast_common des_generic des3_ede_x86_64 libdes blowfish_generic blowfish_x86_64 blowfish_common serpent_avx2 serpent_avx_x86_64 serpent_sse2_x86_64 serpent_generic xts twofish
_generic twofish_avx_x86_64 twofish_x86_64_3way twofish_x86_64 twofish_common lrw algif_skcipher af_alg snd_seq_dummy snd_hrtimer snd_seq vhost_net vhost vhost_iotlb xt_CHECKSUM ipt_REJECT nf_reject_ipv4 veth af_packet cf
g80211 rfkill msr 8021q dm_crypt nft_chain_nat xt_MASQUERADE xt_mark xt_conntrack xt_pkttype xt_LOG nf_log_syslog xt_tcpudp nft_compat cbc encrypted_keys trusted asn1_encoder tee tpm nf_tables sch_fq_codel uinput ipmi_ssi
f nvidia_drm(PO) nvidia_modeset(PO) nvidia_uvm(PO) snd_hda_codec_hdmi amd64_edac edac_mce_amd snd_hda_intel edac_core snd_usb_audio intel_rapl_msr                                                                           
[441571.930703]  snd_intel_dspcfg snd_intel_sdw_acpi intel_rapl_common uvcvideo crc32_pclmul snd_hda_codec polyval_clmulni polyval_generic snd_usbmidi_lib gf128mul videobuf2_vmalloc ghash_clmulni_intel snd_ump uvc sha512_
ssse3 snd_hda_core snd_rawmidi videobuf2_memops sha256_ssse3 snd_hwdep videobuf2_v4l2 snd_seq_device sha1_ssse3 snd_pcm videodev aesni_intel bnxt_en acpi_ipmi crypto_simd sp5100_tco snd_timer cryptd videobuf2_common watch
dog rndis_host video dax_hmem ipmi_si ast cdc_ether snd cxl_acpi mc usbnet ptp ipmi_devintf mousedev input_leds wmi evdev cxl_core rapl led_class mii corsair_psu i2c_algo_bit pps_core soundcore backlight i2c_piix4 ipmi_ms
ghandler k10temp joydev mac_hid nvidia(PO) nf_nat_ftp nf_conntrack_ftp nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 libcrc32c crc32c_generic atkbd libps2 serio vivaldi_fmap loop bonding tls tun tap macvlan bridge stp
 llc kvm_amd ccp rng_core kvm irqbypass fuse configfs efi_pstore nfnetlink efivarfs dmi_sysfs ip_tables x_tables autofs4 sr_mod cdrom hid_generic usbhid                                                                     
[441571.930819]  hid usb_storage sd_mod crc32c_intel ahci libahci xhci_pci libata xhci_pci_renesas nvme firmware_class nvme_core xhci_hcd scsi_mod nvme_auth t10_pi crc64_rocksoft crc64 crc_t10dif crct10dif_generic crct10d
if_pclmul crct10dif_common scsi_common rtc_cmos dm_mod dax nls_iso8859_1 nls_cp437 vfat fat zfs(PO) spl(O)                                                                                                                   
[441571.930855] CPU: 34 PID: 4144666 Comm: lt-run-tests Tainted: P        W  O       6.8.11-xanmod1 #1-NixOS                                                                                                                 
[441571.930858] Hardware name: Supermicro Super Server/H13SSL-NT, BIOS 1.6b 03/08/2024                                                                                                                                       
[441571.930860] RIP: 0010:ssp_get+0x77/0x90                                                                                                                                                                                  
[441571.930863] Code: 00 00 48 85 c0 74 22 48 8d 70 08 ba 08 00 00 00 48 89 e7 e8 ab f8 ff ff 48 83 c4 10 5b e9 3c 94 eb 00 e8 ec ed ff ff eb c4 90 <0f> 0b 90 b8 ed ff ff ff eb e4 66 66 2e 0f 1f 84 00 00 00 00 00 0f
[441571.930866] RSP: 0018:ff6fbe9d576939f8 EFLAGS: 00010246                                                                                                                                                                  
[441571.930869] RAX: 0000000000000000 RBX: ff368549957bb000 RCX: 0000000000000008                                                                                                                                            
[441571.930871] RDX: ff36854611ce5148 RSI: 000000000000000b RDI: ff368549957bbe40                                                                                                                                            
[441571.930873] RBP: ff6fbe9d57693a50 R08: ff368549957bb000 R09: ffffffffa744ac60                                                                                                                                            
[441571.930875] R10: ff6fbe9d57693a18 R11: ff368524e893c70c R12: ffffffffa89acae0                                                                                                                                            
[441571.930876] R13: ff36854611ce5148 R14: ff6fbe9d57693ad8 R15: ff36854611ce5148                                                                                                                                            
[441571.930878] FS:  00007ffff7d77080(0000) GS:ff36854bf7c00000(0000) knlGS:0000000000000000              
[441571.930881] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033                                          
[441571.930883] CR2: 0000000001456000 CR3: 0000002a0fbcc004 CR4: 0000000000f71ef0     
[441571.930885] PKRU: 55555554             
[441571.930886] Call Trace:                                                                                                                                                                                                  
[441571.930890]  <TASK>                                                                                       
[441571.930891]  ? ssp_get+0x77/0x90                                                                          
[441571.930894]  ? __warn+0x81/0x130                                                                          
[441571.930904]  ? ssp_get+0x77/0x90                                                                          
[441571.930907]  ? report_bug+0x125/0x160                                                                     
[441571.930914]  ? handle_bug+0x3d/0x80                                                                       
[441571.930918]  ? exc_invalid_op+0x17/0x70                                                                   
[441571.930921]  ? asm_exc_invalid_op+0x1a/0x20                                                               
[441571.930928]  ? __pfx_ssp_get+0x10/0x10                                                                    
[441571.930935]  ? ssp_get+0x77/0x90
[441571.930938]  ? ssp_get+0x4f/0x90
[441571.930941]  __regset_get+0xad/0xf0
[441571.930948]  elf_core_dump+0x583/0x1070
[441571.930953]  ? srso_alias_return_thunk+0x5/0xfbef5
[441571.930957]  ? finish_task_switch.isra.0+0x94/0x2f0
[441571.930963]  ? srso_alias_return_thunk+0x5/0xfbef5
[441571.930966]  ? mod_memcg_lruvec_state+0x15/0x30
[441571.930971]  ? srso_alias_return_thunk+0x5/0xfbef5
[441571.930974]  ? mod_objcg_state+0x245/0x2c0 
[441571.930987]  do_coredump+0x1278/0x1740
[441571.931000]  get_signal+0x91c/0xa30
[441571.931005]  ? srso_alias_return_thunk+0x5/0xfbef5
[441571.931010]  arch_do_signal_or_restart+0x3e/0x270
[441571.931017]  syscall_exit_to_user_mode+0x1da/0x240
[441571.931022]  do_syscall_64+0xce/0x210             
[441571.931026]  entry_SYSCALL_64_after_hwframe+0x79/0x81
[441571.931030] RIP: 0033:0x7ffff7e0db5c  
[441571.931076] Code: ff ff 0f 46 da e9 74 ff ff ff 0f 1f 40 00 b8 ba 00 00 00 0f 05 89 c3 e8 02 20 05 00 44 89 ea 89 de 89 c7 b8 ea 00 00 00 0f 05 <89> c3 f7 db 3d 00 f0 ff ff b8 00 00 00 00 0f 47 c3 e9 66 ff ff ff
[441571.931078] RSP: 002b:00007fffffff8970 EFLAGS: 00000246 ORIG_RAX: 00000000000000ea
[441571.931082] RAX: 0000000000000000 RBX: 00000000000017ff RCX: 00007ffff7e0db5c
[441571.931084] RDX: 0000000000000006 RSI: 00000000000017ff RDI: 00000000000017ff
[441571.931085] RBP: 00007ffff7f6fb50 R08: 0000000000000000 R09: 0000000000000000
[441571.931087] R10: 0000000000000008 R11: 0000000000000246 R12: 00007ffff7d77080
[441571.931089] R13: 0000000000000006 R14: 0000000000000000 R15: 00007fffffff97f0
[441571.931095]  </TASK>
[441571.931096] ---[ end trace 0000000000000000 ]---
```

**Comment by numinit** [comment]
python3.11 also seems to dislike this:

```
python3.11-execnet> testing/test_basics.py::test_io_message[gevent-sys.executable] PASSED    [ 52%]                                                                                                                          
python3.11-execnet> testing/test_basics.py::test_io_message[gevent-pypy3] SKIPPED (no pypy3                                                                                                                                  
python3.11-execnet> found)                                                                   [ 53%]                                                                                                                          
python3.11-execnet> testing/test_basics.py::test_exectask[gevent] PASSED                     [ 54%]                                                                                                                          
python3.11-execnet> testing/test_basics.py::TestPureChannel::test_factory_create[gevent] PASSED [ 54%]                                                                                                                       
python3.11-execnet> testing/test_basics.py::TestPureChannel::test_factory_getitem[gevent] PASSED [ 55%]                                                                                                                      
python3.11-execnet> testing/test_basics.py::TestPureChannel::test_channel_timeouterror[gevent] Fatal Python error: Segmentation fault       
```

**Comment by numinit** [comment]
LLVM (don't have a fix for this one...)

```
llvm> Failed Tests (19):
llvm>   LLVM :: ExecutionEngine/OrcLazy/anonymous_globals.ll
llvm>   LLVM :: ExecutionEngine/OrcLazy/basic-object-file-loading.ll
llvm>   LLVM :: ExecutionEngine/OrcLazy/basic-whole-module-partitions.ll
llvm>   LLVM :: ExecutionEngine/OrcLazy/common-symbols.ll
llvm>   LLVM :: ExecutionEngine/OrcLazy/emulated-tls.ll
llvm>   LLVM :: ExecutionEngine/OrcLazy/global-ctors-and-dtors.ll
llvm>   LLVM :: ExecutionEngine/OrcLazy/global_aliases.ll
llvm>   LLVM :: ExecutionEngine/OrcLazy/hidden-visibility.ll
llvm>   LLVM :: ExecutionEngine/OrcLazy/minimal.ll
llvm>   LLVM :: ExecutionEngine/OrcLazy/module-flags.ll
llvm>   LLVM :: ExecutionEngine/OrcLazy/multiple-compile-threads-basic.ll
llvm>   LLVM :: ExecutionEngine/OrcLazy/printargv.ll
llvm>   LLVM :: ExecutionEngine/OrcLazy/private_linkage.ll
llvm>   LLVM :: ExecutionEngine/OrcLazy/single-function-call.ll
llvm>   LLVM :: ExecutionEngine/OrcLazy/static-initializers-in-objectfiles.ll
llvm>   LLVM :: ExecutionEngine/OrcLazy/static-library-support.ll
llvm>   LLVM :: ExecutionEngine/OrcLazy/weak-function.ll
llvm>   LLVM :: ExecutionEngine/OrcLazy/weak-non-materialization.ll
llvm>   LLVM-Unit :: ExecutionEngine/Orc/./OrcJITTests/58/75
llvm> Testing Time: 121.32s
llvm>   Skipped          :    15
llvm>   Unsupported      :  1797
llvm>   Passed           : 54016
llvm>   Expectedly Failed:   174
llvm>   Failed           :    19
llvm> FAILED: CMakeFiles/check-all /build/llvm-src-17.0.6/llvm/build/CMakeFiles/check-all
llvm> cd /build/llvm-src-17.0.6/llvm/build && /nix/store/0j1101rd67wnxn1v2bm6prbydmi2zfl1-python3-3.11.9-env/bin/python3.11 /build/llvm-src-17.0.6/llvm/build/./bin/llvm-lit -svj48 --no-progress-bar --param polly_site_config=/build/llvm-src-17.0.6/llvm/build/tools/polly/test/lit.site.cfg --param polly_unit_site_config=/build/llvm-src-17.0.6/llvm/build/tools/polly/test/Unit/lit.site.cfg /build/llvm-src-17.0.6/llvm/build/tools/polly/test /build/llvm-src-17.0.6/llvm/build/utils/lit /build/llvm-src-17.0.6/llvm/build/test
```

**Comment by numinit** [comment]
So, as you may be able to tell, certain tools are pretty unhappy about backedge CFI existing. 🙃

**Comment by risicle** [comment]
Awesome! Do these packages behave themselves if you `hardeningDisable = [ "hardbackedgecfi" ];` ?

**Comment by numinit** [comment]
I'll give Python a shot, that looks like it may have been the issue for LLVM. PCRE behaved when I changed that.

**Comment by numinit** [comment]
So, it was actually LLVM that caused the problem. What would cause a process to not report `shstk` in its thread features? I can build `armagetronad.dedicated` and have it work, but `armagetronad` the desktop app doesn't support shadow stacks.

... Wait, as I was writing this, I answered my own question. My system isn't compiled with CFI, so it's graphics drivers!

**Comment by risicle** [comment]
I forget about things like that being mostly a server user.

**Comment by risicle** [comment]
Excellent thankyou. So far it's looking like there isn't much correspondence between broken packages for shadow stacks and for pac-ret, so this might need a rethink.

**Pull request closed without merging**
