### PR TITLE
linux_5_13: init at 5.13

### PR DESCRIPTION
**Pull request by ymatsiuk**
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by jonringer — APPROVED** [review]
diff LGTM

we can fix or mark the broken modules later 

```
https://github.com/NixOS/nixpkgs/pull/128502

12 packages marked as broken and skipped:
linuxPackages_5_13.anbox linuxPackages_5_13.ixgbevf linuxPackages_5_13.mxu11x0 linuxPackages_5_13.ndiswrapper linuxPackages_5_13.phc-intel linuxPackages_5_13.r8125 linuxPackages_5_13.rtl8723bs linuxPackages_5_13.sch_cake linuxPackages_5_13.tbs linuxPackages_5_13.zfs linuxPackages_5_13.zfsStable linuxPackages_5_13.zfsUnstable

10 packages failed to build:
linuxPackages_5_13.amdgpu-pro linuxPackages_5_13.evdi linuxPackages_5_13.nvidia_x11 linuxPackages_5_13.nvidia_x11_legacy340 linuxPackages_5_13.nvidia_x11_legacy390 linuxPackages_5_13.nvidia_x11_vulkan_beta linuxPackages_5_13.odp-dpdk linuxPackages_5_13.perf linuxPackages_5_13.tuxedo-keyboard linuxPackages_5_13.virtualboxGuestAdditions

71 packages built:
linuxPackages_5_13.acpi_call linuxPackages_5_13.akvcam linuxPackages_5_13.apfs linuxPackages_5_13.asus-wmi-sensors linuxPackages_5_13.batman_adv linuxPackages_5_13.bbswitch linuxPackages_5_13.bcc linuxPackages_5_13.bpftrace linuxPackages_5_13.broadcom_sta linuxPackages_5_13.can-isotp linuxPackages_5_13.chipsec linuxPackages_5_13.cpupower linuxPackages_5_13.cryptodev linuxPackages_5_13.ddcci-driver linuxPackages_5_13.digimend linuxPackages_5_13.dpdk-kmods linuxPackages_5_13.ena linuxPackages_5_13.facetimehd linuxPackages_5_13.fwts-efi-runtime linuxPackages_5_13.gcadapter-oc-kmod linuxPackages_5_13.hid-nintendo linuxPackages_5_13.hyperv-daemons linuxPackages_5_13.intel-speed-select linuxPackages_5_13.isgx linuxPackages_5_13.it87 linuxPackages_5_13.jool linux_5_13 linuxPackages_5_13.lttng-modules linuxPackages_5_13.mba6x_bl linuxPackages_5_13.mbp2018-bridge-drv linuxPackages_5_13.mwprocapture linuxPackages_5_13.netatop linuxPackages_5_13.nvidia_x11_beta linuxPackages_5_13.nvidiabl linuxPackages_5_13.oci-seccomp-bpf-hook linuxPackages_5_13.openafs linuxPackages_5_13.openafs_1_9 linuxPackages_5_13.openrazer linuxPackages_5_13.pktgen linuxPackages_5_13.ply linuxPackages_5_13.r8168 linuxPackages_5_13.rtl8188eus-aircrack linuxPackages_5_13.rtl8192eu linuxPackages_5_13.rtl8812au linuxPackages_5_13.rtl8814au linuxPackages_5_13.rtl8821au linuxPackages_5_13.rtl8821ce linuxPackages_5_13.rtl8821cu linuxPackages_5_13.rtl88x2bu linuxPackages_5_13.rtl88xxau-aircrack linuxPackages_5_13.rtw88 linuxPackages_5_13.stdenv linuxPackages_5_13.sysdig linuxPackages_5_13.system76 linuxPackages_5_13.system76-acpi linuxPackages_5_13.system76-io linuxPackages_5_13.system76-power linuxPackages_5_13.systemtap linuxPackages_5_13.tmon linuxPackages_5_13.tp_smapi linuxPackages_5_13.turbostat linuxPackages_5_13.usbip linuxPackages_5_13.v4l2loopback linuxPackages_5_13.v86d linuxPackages_5_13.veikk-linux-driver linuxPackages_5_13.vendor-reset linuxPackages_5_13.vhba linuxPackages_5_13.virtualbox linuxPackages_5_13.x86_energy_perf_policy linuxPackages_5_13.xpadneo linuxPackages_5_13.zenpower
```

**Comment by Atemu** [comment]
I'd prefer if the PR which introduces a new kernel marked the modules as broken too. Else I fear that we might end up having tons of unmarked broken modules again.

It's much easier to do it when the kernel has just been introduced using nixpkgs-review etc. than doing it after the fact.

**Comment by jonringer** [comment]
I started fixing one: https://github.com/NixOS/nixpkgs/pull/128537

Having the changes in master allows for people to iterate on them.

**Comment by alyssais** [comment]
You forgot to update `linuxPackages_latest` :)

I opened #128785 to do that.

**Pull request merged**
