### PR TITLE
flarum: init at 1.8.1, module

### PR DESCRIPTION
**Pull request by fsagbuya**
## Description of changes

Based from #96869, https://github.com/ngi-nix/ngipkgs/pull/47 and https://github.com/ngi-nix/ngipkgs/pull/56.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by drupol** [comment]
Hi!

Good idea to backport flarum from ngi-nix, did you used their repo as source for the code?
Context: https://github.com/ngi-nix/ngipkgs/pull/56

**Comment by fsagbuya** [comment]
> did you used their repo as source for the code? Context: [ngi-nix/ngipkgs#56](https://github.com/ngi-nix/ngipkgs/pull/56)

Yes, only changes I made was updating the version and hash, some cleanup,  and also [modifying this line](https://github.com/NixOS/nixpkgs/pull/311608/commits/3d7849c2a927c0e36116f6c47a447b3c700e98b0#diff-d694d99e5b93515b9aeb968b1335e30f9349a205780f0f558d131988c7913decR44) to avoid this error:
```
Cacheable portion of option doc build failed.
Usually this means that an option attribute that ends up in documentation (eg `default` or `description`) depends on the restricted module arguments `config` or `pkgs`.
```
I'm open to suggestions especially from someone at ngi-nix, and very willing to add them as maintainer. Just give me a ping.

**Comment by jasonodoom** [comment]
> > did you used their repo as source for the code? Context: [ngi-nix/ngipkgs#56](https://github.com/ngi-nix/ngipkgs/pull/56)
> 
> Yes, only changes I made were updating the version and hash, some cleanup, and [modifying this line](https://github.com/NixOS/nixpkgs/pull/311608/commits/3d7849c2a927c0e36116f6c47a447b3c700e98b0#diff-d694d99e5b93515b9aeb968b1335e30f9349a205780f0f558d131988c7913decR44) to avoid this error:
> 
> ```
> Cacheable portion of option doc build failed.
> Usually this means that an option attribute that ends up in documentation (eg `default` or `description`) depends on the restricted module arguments `config` or `pkgs`.
> ```
> 
> I'm open to suggestions especially from someone at ngi-nix, and very willing to add them as maintainer. Just give me a ping.

Thanks for doing this @fsagbuya! I was able to build this successfully. Feel free to add me as second maintainer if you want.

**Review by jasonodoom — APPROVED** [review]

**Comment by fsagbuya** [comment]
@jasonodoom added you. Thanks!

**Comment by albertchae** [comment]
@fsagbuya thanks for upstreaming this! last year one of the reasons we didn't upstream it was that no one wanted to be a maintainer in nixpkgs since we didn't use the software, but looks like @jasonodoom has changed his mind since 🎉 

@drupol thanks for linking the PRs to the ngipkgs repo. IIRC your recent comments in #foundation seemed to indicate you felt there were code quality issues with the flarum packaging work, so I was hoping you'd provide some more commentary on this upstreaming PR for our education

Now that this PR has been merged, it's a good candidate for whenever ngipkgs implements https://github.com/ngi-nix/ngipkgs/issues/76

**Comment by drupol** [comment]
> @drupol thanks for linking the PRs to the ngipkgs repo. IIRC your recent comments in #foundation seemed to indicate you felt there were code quality issues with the flarum packaging work, so I was hoping you'd provide some more commentary on this upstreaming PR for our education

Hello,

My main concern has been addressed already, but I'd like to reiterate it here. I don't see the value in merging stuff into a repository outside `nixpkgs`. Even if this is enforced by the NGI contractual agreement, it seems counterproductive. NGI should either ensure that once a PR is merged into their repository, it gets upstreamed into `nixpkgs`, or they should discontinue `ngi-nix/ngipkgs` and instead support users in contributing directly to `nixpkgs`, which maintains higher quality standards.

I refrained from interfering with this PR, even though I could have requested some changes. I didn't want to block the merge over the use of a top-level `with lib;`. While technically valid, this practice is no longer recommended.

I hope my message is clear. My goal is to consolidate nix recipes in their appropriate place and avoid fragmentation. Teaching contributors to work directly with `nixpkgs` is much more valuable than contributing to a standalone repository. It's important to learn technical skills, best practices, and the social interactions on GitHub.

**Pull request merged**
