### PR TITLE
Update default version of gnupg to 2.1.x 

### PR DESCRIPTION
**Pull request by peti**

### CODE REVIEW

**Comment by cstrahan** [comment]
@peti @ttuegel 

I snagged the following (plus some tweaks of my own) from @ttuegel's configuration; might it make sense to provide a similar service in NixOS?

```nix
# inspired by: https://github.com/ttuegel/nixos-config/blob/master/gpg-agent.nix
{ config, lib, pkgs, ... }:

with lib;

let

  cfg = config.programs.gpg-agent;

  startGpgAgent = pkgs.writeScript "start-gpg-agent"
    ''
        #!/bin/sh
        ${pkgs.gnupg21}/bin/gpg-agent \
            --enable-ssh-support \
            --pinentry-program ${pkgs.pinentry}/bin/pinentry-gtk-2 \
            --allow-loopback-pinentry \
            --daemon
    '';

in

{
  options = {

    programs.gpg-agent = {
      enable = mkEnableOption "gpg-agent";
    };

  };

  config = mkIf cfg.enable {

    programs.ssh.startAgent = mkDefault false;
    services.xserver.startGnuPGAgent = mkDefault false;

    systemd.user.services = {
      gpg-agent = {
        description = "Secret key management for GnuPG";
        enable = true;
        serviceConfig = {
          Type = "forking";
          ExecStart = "${startGpgAgent}";
          ExecStop = "${pkgs.procps}/bin/pkill -u %u gpg-agent";
          Restart = "always";
        };
        wantedBy = [ "default.target" ];
      };
    };

    environment.extraInit = ''
      if [ -n "$TTY" -o -n "$DISPLAY" ]; then
          ${pkgs.gnupg21}/bin/gpg-connect-agent updatestartuptty /bye >/dev/null 2>&1
      fi

      if [ -z "$SSH_AUTH_SOCK" ]; then
          export SSH_AUTH_SOCK="$HOME/.gnupg/S.gpg-agent.ssh"
      fi
    '';

    assertions =
      [ { assertion = !(config.programs.ssh.startAgent && cfg.enable);
          message =
            ''
              The OpenSSH agent and this custom GnuPG agent cannot be started both. Please
              choose between ‘programs.ssh.startAgent’ and ‘programs.gpg-agent.enable’.
            '';
        }
        { assertion = !(config.services.xserver.startGnuPGAgent && cfg.enable);
          message =
            ''
              The default GnuPG agent and this custom GnuPG agent cannot be started both. Please
              choose between ‘services.xserver.startGnuPGAgent’ and ‘programs.gpg-agent.enable’.
            '';
        }
      ];

  };
}
```

**Comment by peti** [comment]
Personally, I just added

~~~~
gpg-connect-agent /bye
GPG_TTY=$(tty)
export GPG_TTY
unset SSH_AGENT_PID
export SSH_AUTH_SOCK="${HOME}/.gnupg/S.gpg-agent.ssh"
~~~~

to my `~/.xsession` file, which has the advantage that it works fine on non-NixOS machines, too. I still think that that the systemd configuration can be very useful, though.

**Comment by ttuegel** [comment]
I am no longer using the systemd user service; instead I use [XDG autostart](https://github.com/ttuegel/nixos-config/blob/master/programs/gpg-agent.nix). I strongly recommend against using systemd user services. Most graphical applications behave very poorly if they are not started after the window manager or desktop manager, if present.

**Comment by domenkozar** [comment]
Upgrading to 16.09 now yields:

```
trace: warning: The option definition `services.xserver.startGnuPGAgent' in `/etc/nixos/configuration.nix' no longer has any effect; please remove it.
See the 16.03 release notes for more information.
```

**Comment by domenkozar** [comment]
Opened https://github.com/NixOS/nixpkgs/issues/18293 to address this

**Pull request merged**
