### PR TITLE
parity: 2.1.6 -> 2.1.9; parity-beta: 2.2.1 -> 2.2.4

### PR DESCRIPTION
**Pull request by akru**
###### Motivation for this change

* https://github.com/paritytech/parity-ethereum/releases/tag/v2.2.4
* https://github.com/paritytech/parity-ethereum/releases/tag/v2.1.9

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by worldofpeace** [comment]
@GrahamcOfBorg build parity

**Comment by worldofpeace** [comment]
Do the vendor patches need any changes since `daemonize` is now from crates.io?

**Comment by akru** [comment]
@worldofpeace You are right, fixed.

**Comment by akru** [comment]
@GrahamcOfBorg build parity parity-beta

**Review by worldofpeace — APPROVED** [review]
Built and executed with success. We're good for merge.

**Comment by worldofpeace** [comment]
@akru Can you split your commit `parity: 2.1.6 -> 2.1.9; parity-beta: 2.2.1 -> 2.2.4` into two?

**Comment by Mic92** [comment]
Are you cargo/config files still necessary with https://github.com/NixOS/nixpkgs/pull/46362 ?

**Comment by akru** [comment]
@Mic92 You are right, fixed.

**Comment by akru** [comment]
@GrahamcOfBorg build parity parity-beta

**Pull request merged**
