### PR TITLE
luaPackages, vimPlugins: update on 2024-09-30

### PR DESCRIPTION
**Pull request by khaneliman**
## Description of changes

~Not seeing the neotest-dotnet regression like in last PR bump, so that might have been due to something else going on.~

Nvm... it's just not a consistent bug. I can sometimes get it to work. But, neotest in general feels that way with all the bugs in it. 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by khaneliman** [comment]
We need to fix botan on x86 darwin, that's the rehex dependency failure. But, it does that on the master branch currently. 

```bash
-Wshorten-64-to-32 -Wcomma -Wdocumentation -DBOTAN_IS_BEING_BUILT  -I build/include/public -I build/include/internal  -isystem build/include/external -c src/cli/tls_client.cpp -o build/obj/cli/tls_client.o
       > src/cli/sandbox.cpp:18:13: error: 'sandbox.h' file not found with <angled> include; use "quotes" instead
       >    #include <sandbox.h>
       >             ^~~~~~~~~~~
       >             "sandbox.h"
       > src/cli/sandbox.cpp:104:9: error: no member named 'sandbox_init' in the global namespace
       >    if(::sandbox_init(kSBXProfileNoWriteExceptTemporary, SANDBOX_NAMED, nullptr) < 0) {
       >       ~~^
       > src/cli/sandbox.cpp:104:22: error: use of undeclared identifier 'kSBXProfileNoWriteExceptTemporary'
       >    if(::sandbox_init(kSBXProfileNoWriteExceptTemporary, SANDBOX_NAMED, nullptr) < 0) {
       >                      ^
       > src/cli/sandbox.cpp:104:57: error: use of undeclared identifier 'SANDBOX_NAMED'
       >    if(::sandbox_init(kSBXProfileNoWriteExceptTemporary, SANDBOX_NAMED, nullptr) < 0) {
       >                                                         ^
       > 4 errors generated.
       > make: *** [Makefile:1602: build/obj/cli/sandbox.o] Error 1
       > make: *** Waiting for unfinished jobs....
       For full logs, run 'nix log /nix/store/d4blqix0la0wjzxr11jiydnyyk1qvp83-botan-3.5.0.drv'.
```

**Review by GaetanLepage — APPROVED** [review]
LGTM, thanks

**Comment by GaetanLepage** [comment]
> We need to fix botan on x86 darwin, that's the rehex dependency failure. But, it does that on the master branch currently.

Sure, but as this is not a regression, I will go ahead and merge this PR.

**Comment by fpletz** [comment]
`dkjson` fails:
```
error: hash mismatch in fixed-output derivation '/nix/store/xldxkrh87vnxpdm3si720c49771jmrva-dkjson-2.8.tar.gz.drv':
        likely URL: http://dkolf.de/dkjson-lua/dkjson-2.8.tar.gz
         specified: sha256-CfpgoEECteMiqwa51Zt6oPKcChnHVCFfikHzoWT5SUs=
            got:    sha256-JOjNO+uRwchh63uz+8m9QYu/+a1KpdBHGBYlgjajFTI=
```

**Comment by khaneliman** [comment]
> `dkjson` fails:
> 
> ```
> error: hash mismatch in fixed-output derivation '/nix/store/xldxkrh87vnxpdm3si720c49771jmrva-dkjson-2.8.tar.gz.drv':
>         likely URL: http://dkolf.de/dkjson-lua/dkjson-2.8.tar.gz
>          specified: sha256-CfpgoEECteMiqwa51Zt6oPKcChnHVCFfikHzoWT5SUs=
>             got:    sha256-JOjNO+uRwchh63uz+8m9QYu/+a1KpdBHGBYlgjajFTI=
> ```

weird... I used to get that on previous updates but didn't get it this update so I assumed something changed.

**Pull request merged**
