### PR TITLE
nixos/nftables: add redirect for /etc/hosts to checkRuleset

### PR DESCRIPTION
**Pull request by 4z3**
###### Description of changes

Add a redirect for `/etc/hosts` when checking the ruleset. For easier extension, redirects can be modified using the new `networking.nftables.checkRulesetRedirects` option. The defaults have been chosen to redirect to `environment.etc` so the ruleset check can utilize the same names as the built system.

Without this addition, hostnames defined via `networking.hosts` cannot be used while checking the ruleset, causing errors like this:
```
building '/nix/store/j07299i21rjvzmz9njykadh0skci50jc-nftables-rules.drv'...
In file included from ruleset.conf:3:1-63:
/nix/store/ayppg24dsajr3mf9cd2gh6h52cvz9qi4-nftables:79:14-20: Error: Could not resolve hostname: Temporary failure in name resolution
    ip saddr zonk tcp dport couchdb counter accept
             ^^^^
error: builder for '/nix/store/j07299i21rjvzmz9njykadh0skci50jc-nftables-rules.drv' failed with exit code 1
```

An alternative to this PR is to (ab-) use `networking.nftables.preCheckRuleset` to implement a custom check, e.g. like follows (but that's nothing friends would allow friends to do):
```nix
{
  networking.nftables.preCheckRuleset = ''
    export NIX_REDIRECTS=${escapeShellArg (concatStringsSep ":" (mapAttrsToList (name: value: "${name}=${value}") {
      "/etc/hosts" = config.environment.etc.hosts.source;
      "/etc/protocols" = config.environment.etc.protocols.source;
      "/etc/services" = config.environment.etc.services.source;
    }))}
    export LD_PRELOAD=${escapeShellArgs (toString [
      "${pkgs.buildPackages.libredirect}/lib/libredirect.so"
      "${pkgs.buildPackages.lklWithFirewall.lib}/lib/liblkl-hijack.so"
    ])}
    exec ${pkgs.buildPackages.nftables}/bin/nft --check --file ruleset.conf
  '';
}
```

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jian-lin** [comment]
related https://github.com/NixOS/nixpkgs/pull/238846

**Comment by rnhmjoj** [comment]
This is nice, but I think another option just for it is a bit overkill: I can't think of more files one would possibly need to redirect.
In #238846 I'm proposing to make the declaration of NIX_REDIRECTS extensible, so if needed users can add more redirects using the existing option `networking.nftables.preCheckRuleset`.
What do you think?

**Comment by 4z3** [comment]
> What do you think?

I don't think it's overkill, but I'm fine with either solution. I wasn't aware / didn't bother checking whether there was already something related. I just needed something to allow my configuration to build.

That said, in https://github.com/NixOS/nixpkgs/pull/238846 at least /etc/services should redirect to `environment.etc.services.source` because that can also be overridden as e.g. done [here](https://cgit.krebsco.de/stockholm/tree/krebs/3modules/iana-etc.nix). And for consistency, /etc/protocols should probably also point to `environment.etc.protocols.source`.

**Comment by rnhmjoj** [comment]
> /etc/services should redirect to environment.etc.services.source because that can also be overridden 

Makes sense, but are those `environment.etc.*` always defined? Otherwise `pkgs.iana-etc` should be set as a default here.

**Comment by 4z3** [comment]
> are those `environment.etc.*` always defined?

[Yes](https://github.com/NixOS/nixpkgs/blob/9547123258f69efd92b54763051d6dc7f3bfcaca/nixos/modules/config/networking.nix#L192-L199).

**Comment by rnhmjoj** [comment]
> That said, in https://github.com/NixOS/nixpkgs/pull/238846 at least /etc/services should redirect to environment.etc.services.source 

Done. I would like to hear from one of the nftables maintainers about which approach is better, now.

**Review by mkg20001 — APPROVED** [review]
seems reasonable.
maybe a note in the description of when one would need to modify this option. (or maybe we don't need it to be an option)

is this the full set of files nftables reads from /etc? it seems so. we should have them all by default.

**Comment by rnhmjoj** [comment]
> or maybe we don't need it to be an option

The alternative is https://github.com/NixOS/nixpkgs/pull/238846: same thing, but no explicit option. You can still add more links if you need, though.

**Review by rnhmjoj — APPROVED** [review]

**Comment by rnhmjoj** [comment]
@GrahamcOfBorg test firewall-nftables

**Comment by rnhmjoj** [comment]
Thank you all!

**Comment by hgl** [comment]
I wonder if this option can be used for `include`s? I tried something like this

```nix
networking.nftables.tables.foo.content = ''
  include "/var/lib/foo/foo.nft"
'';


networking.nftables.checkRulesetRedirects = ''
  "/var/lib/foo/foo.nft" = ./foo.nft;
''
```
and build failed with

```
ruleset.conf:99:3-33: Error: File not found: /var/lib/foo/foo.nft
  include "/var/lib/foo/foo.nft"
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
I can't directly include the store file because this file needs to be updated periodically at runtime.

**Pull request merged**
