### PR TITLE
doc: enable code syntax highlighting

### PR DESCRIPTION
**Pull request by alexeymuranov**
Use "fenced" code blocks to enable syntax highlighting in Haskell documentation `haskell.md`.  Try to improve other markup and formatting.

### CODE REVIEW

**Comment by FRidh** [comment]
Note that this isn't Markdown anymore but GitHub Flavored Markdown.

I hoped we could get syntax highlighting in the eventual manual as well by indicating the source is `markdown_github`. After fixing some small issues I got it to build, but unfortunately the syntax isn't highlighted. Checking the xml it seems a language is passed to `programlisting` so I suppose we need to fix the stylesheet.

**Comment by peti** [comment]
That  Markdown documented is targeting `pandoc` for conversion into Docbook so that it can be included in the Nixpkgs manual. Displaying that document in Github would be a nice feature, of course, but only if the Docbook output doesn't suffer because of it.

**Comment by FRidh** [comment]
@peti Absolutely. Last I checked this PR (there's also one for Python) didn't affect the manual in any negative way.

**Comment by alexeymuranov** [comment]
No more merge conflicts.

**Pull request merged**
