### PR TITLE
wrapFirefox: fix default-browser update

### LINKED ISSUE #4370: Firefox and Chromium "set as default" not including wrapper
When "set as default browser" is clicked from within Firefox, it places a custom .desktop file in ~/.local/share/applications, and points to this from mimeapps.list in the same directory. This file launches Firefox without the wrapper when it's opened using xdg-open. The result is that if xdg-open is used when no Firefox window exists, it will be opened without environment variables set correctly, and without plugins.

### PR DESCRIPTION
**Pull request by layus**
Set MOZ_APP_LAUNCHER for firefox as per [1] (see [2] for detailed discussion).
Firefox will recognise itself across verions, skipping the 'not-the-default-browser' prompt.
Firefox will also write sane paths to the generated desktop file, should someone ever set it as default through the 'not-the-default-browser' prompt.
Also removed the unnecessary libtrick cruft.

This fixes #4370 for firefox.

- [X] tested with nox-review on NixOS

/cc @vcunat

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=611953
[2] https://bugzilla.mozilla.org/show_bug.cgi?id=593948

### CODE REVIEW

**Review by 7c6f434c — APPROVED** [review]

**Comment by 7c6f434c** [comment]
You did test execution of the wrapper too, right?

**Comment by layus** [comment]
I tested all the wrappers rebuilt by nox-review.

**Comment by RonnyPfannschmidt** [comment]
shouldn't this go o 17.03 as well? @globin

**Comment by globin** [comment]
cherry-picked

**Pull request merged**
