### PR TITLE
new-lg4ff: 0.4.0 -> 0-unstable-2024-11-25

### PR DESCRIPTION
**Pull request by mksafavi**
## Things done

The lg4ff build failed on kernel 6.12 and there's a patch for it upstream.
I updated the package.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by mksafavi** [comment]
I didn't have time to test this yet. I'll probably look into it on the weekend. 
Though it does compile the module `nix-build -A linuxPackages.new-lg4ff`.

**Comment by mksafavi** [comment]
> ## `nixpkgs-review` result
> 
> Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).
> 
> Command: `nixpkgs-review pr 360385`
> ### `x86_64-linux`
> ⏩ 2 packages marked as broken and skipped:
> 
>     * linuxKernel.packages.linux_5_4_hardened.new-lg4ff
> 
>     * linuxPackages_5_4_hardened.new-lg4ff
> 
> 
> ✅ 18 packages built:
> 
>     * linuxKernel.packages.linux_5_10.new-lg4ff
> 
>     * linuxPackages_5_10_hardened.new-lg4ff (linuxKernel.packages.linux_5_10_hardened.new-lg4ff)
> 
>     * linuxKernel.packages.linux_5_15.new-lg4ff
> 
>     * linuxPackages_5_15_hardened.new-lg4ff (linuxKernel.packages.linux_5_15_hardened.new-lg4ff)
> 
>     * linuxKernel.packages.linux_5_4.new-lg4ff
> 
>     * linuxKernel.packages.linux_6_1.new-lg4ff
> 
>     * linuxKernel.packages.linux_6_11.new-lg4ff
> 
>     * linuxPackages_6_11_hardened.new-lg4ff (linuxKernel.packages.linux_6_11_hardened.new-lg4ff)
> 
>     * linuxPackages_latest.new-lg4ff (linuxKernel.packages.linux_6_12.new-lg4ff)
> 
>     * linuxPackages_6_1_hardened.new-lg4ff (linuxKernel.packages.linux_6_1_hardened.new-lg4ff)
> 
>     * linuxPackages.new-lg4ff (linuxKernel.packages.linux_6_6.new-lg4ff)
> 
>     * linuxPackages_hardened.new-lg4ff (linuxPackages_6_6_hardened.new-lg4ff)
> 
>     * linuxPackages_latest-libre.new-lg4ff (linuxKernel.packages.linux_latest_libre.new-lg4ff)
> 
>     * linuxPackages-libre.new-lg4ff (linuxKernel.packages.linux_libre.new-lg4ff)
> 
>     * linuxPackages_lqx.new-lg4ff (linuxKernel.packages.linux_lqx.new-lg4ff)
> 
>     * linuxPackages_xanmod.new-lg4ff (linuxKernel.packages.linux_xanmod.new-lg4ff)
> 
>     * linuxPackages_xanmod_latest.new-lg4ff (linuxKernel.packages.linux_xanmod_latest.new-lg4ff ,linuxPackages_xanmod_stable.new-lg4ff)
> 
>     * linuxPackages_zen.new-lg4ff (linuxKernel.packages.linux_zen.new-lg4ff)

Hi.
Does it look good?

**Comment by keenanweaver** [comment]
> Hi. Does it look good?

I don't know how to properly test it on my system with the module, but it builds at least.

**Comment by mksafavi** [comment]
> > Hi. Does it look good?
> 
> I don't know how to properly test it on my system with the module, but it builds at least.

I don't know the Nix-y way to do it either. 
I upgraded my kernel to 6.12 and then manually added the module with `sudo insmod hid-logitech-new.ko`.
It worked with my Wheel.

**Review by Aleksanaa — APPROVED** [review]

**Pull request merged**
