### PR TITLE
temporal-cli: Fix Darwin builds with sandbox enabled

### PR DESCRIPTION
**Pull request by amarshall**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
What is the actual error that is printed in the logs?

**Comment by tjni** [comment]
The `tctl` derivation seems to only need:
```
__darwinAllowLocalNetworking = true;
```
but the `tctl-next` derivation fails because a test tries to access `/etc/protocols`:
```
running tests
ok      github.com/temporalio/tctl/cli  0.657s
ok      github.com/temporalio/tctl/cli/headers  0.012s
ok      github.com/temporalio/tctl/cli/stringify        0.016s
ok      github.com/temporalio/tctl/cli/trace    0.012s
panic: open /etc/protocols: operation not permitted

goroutine 1 [running]:
modernc.org/libc/honnef.co/go/netdb.init.0()
        /private/tmp/nix-build-tctl-next-0.9.0.drv-1/source/vendor/modernc.org/libc/honnef.co/go/netdb/netdb.go:700 +0x784
FAIL    github.com/temporalio/cli/app   0.043s
FAIL
```

**Comment by tjni** [comment]
> I cannot reproduce either succeeding with only `__darwinAllowLocalNetworking = true`, they both have the same dep that causes the `/etc/protocols` access failure.

You're right, I just checked again. Adding `__darwinAllowLocalNetworking` does remove this log message:
```
Upserted cluster localhost:7233
current-env: tctl-test-env
--- FAIL: Test_fetchCACertFromUrl (0.00s)
panic: httptest: failed to listen on a port: listen tcp6 [::1]:0: bind: operation not permitted [recovered]
        panic: httptest: failed to listen on a port: listen tcp6 [::1]:0: bind: operation not permitted
```
but still runs into the same error. I jumped the gun there, sorry for the noise!

**Comment by tjni** [comment]
Result of `nixpkgs-review pr 242721` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>temporal-cli</li>
  </ul>
</details>

**Review by tjni — APPROVED** [review]
LGTM!

**Pull request merged**
