### PR TITLE
tandoor-recipes: 1.4.9 -> 1.5.4

### PR DESCRIPTION
**Pull request by blargg**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [x] (N/A) (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ambroisie** [comment]
I'll have to investigate _why_ ofborg doesn't seem to update this package.

The changes look correct, I'll try building and testing the package in the evening.

**Comment by ambroisie** [comment]
@blargg 1.5.4 was just released.

Please also add a link to the changelog.

**Comment by blargg** [comment]
I tried the update, 1.5.4 gives a failure in testing. I didn't get that in 1.5.3 I'm going to poke around a bit more to see what's up.

`nix build .\#nixosTests.tandoor-recipes `

```
cookbook/tests/other/test_recipe_full_text_search.py::test_search_count[found_recipe1-timescooked]
  /nix/store/gy40p8nfs0dnjpbj6c01jk9rks2sc8i9-python3.10-Django-4.2.3/lib/python3.10/site-packages/django/db/models/fields/__init__.py:1535: RuntimeWarning: DateTimeField Recipe.created_at received a naive datetime (2018-09-09 00:00:00) while time zon>
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED cookbook/tests/other/test_recipe_full_text_search.py::test_search_date[found_recipe0-viewedon-result0] - assert 0 == 1
FAILED cookbook/tests/other/test_recipe_full_text_search.py::test_search_date[found_recipe1-cookedon-result1] - assert 0 == 1
FAILED cookbook/tests/other/test_recipe_full_text_search.py::test_search_date[found_recipe2-createdon-result2] - assert 11 == 12
FAILED cookbook/tests/other/test_recipe_full_text_search.py::test_search_date[found_recipe3-updatedon-result3] - assert 11 == 12
===== 4 failed, 738 passed, 24 skipped, 639 warnings in 181.12s (0:03:01) ======
```

**Comment by blargg** [comment]
Alright, we should be good. I think it was just something else on the particular nixpkgs commit that it was based on. Pulling the master branch an rebasing fixed it, and it works on older branches too.

Tests are passing again

**Comment by ambroisie** [comment]
Please change the title of the PR to reflect the updated code :-)

**Comment by blargg** [comment]
Ah, thanks for the catch. I must not have moved the change out to my branch and changed the name somehow. Fixed.

**Review by NickCao — APPROVED** [review]

**Pull request merged**
