### PR TITLE
WIP: nixos/ceph: port tests to python

### PR DESCRIPTION
**Pull request by flokli**
###### Motivation for this change
https://github.com/NixOS/nixpkgs/issues/72828

Contains commits from https://github.com/NixOS/nixpkgs/pull/72603 and https://github.com/NixOS/nixpkgs/pull/73189 and should be rebased on top of master once these are merged.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @tfc @worldofpeace

### CODE REVIEW

**Comment by flokli** [comment]
@Mic92 this contains #73189, but it seems the python test driver spends 100% of its cpu time with recvfrom syscalls when running the ceph-multi-node test… Any idea what's going on?

**Comment by flokli** [comment]
Turns out, it's wasting cpu cycles in the `wait_for_monitor_prompt` method, because for some reason, there's nothing received.

**Review by lejonet — APPROVED** [review]
From what I can see, it doesn't change any of the test cases, merely just changes the syntax of calling.

The only comment I have is that in the lines where there is more than one command in a row, and thus a comma-separated list is given to succeed() for example, there seems to be some extra whitespace that gets added. Is that intentionally or just your editor interprenting tabs as 4 spaces or something? I don't really care if its 2, 4, 8 or more spaces, the indentation is coherent and that is the important part. Just wanted to highlight it to see if it was an intended or unintended change.

**Comment by Mic92** [comment]
4 spaces is what the python community embraces for code, so I am fine with that.

**Comment by lejonet** [comment]
> 4 spaces is what the python community does for code, so I am fine with that.

Yeah, I'm completely fine with it too, just wanted to point it out, in case it wasn't intentional :)

**Comment by flokli** [comment]
@tfc @lejonet after some investigation, it turns out the python test driver doesn't properly handle `emptyDiskImages`. I opened https://github.com/NixOS/nixpkgs/issues/73559 to track this.

**Comment by flokli** [comment]
Got the test to work - they uncovered two issues in the python test driver, which didn't behave exactly like the perl one (passing of environment to the script executing qemu, handling in the `wait_for_monitor_prompt` method).

Thanks to @tfc, these are fixed now. Rebased on latest master and cherry-picked them in. PTAL.

**Comment by flokli** [comment]
@GrahamcOfBorg test ceph-single-node ceph-multi-node

**Review by tfc — APPROVED** [review]

**Comment by tfc** [comment]
@domenkozar @adisbladis

**Pull request merged**
