### PR TITLE
treewide: use runtimeShell instead of stdenv.shell whenever possible

### PR DESCRIPTION
**Pull request by Mic92**
Whenever we create scripts that are installed to $out, we must use runtimeShell
in order to get the shell that can be executed on the machine we create the
package for. This is relevant for cross-compiling. The only use case for
stdenv.shell are scripts that are executed as part of the build system.
Usages in checkPhase are borderline however to decrease the likelyhood
of people copying the wrong examples, I decided to use runtimeShell as well.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`

  Only vessel and worldofgoo cannot be tested since they require files that I do not have.
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by FRidh** [comment]
This is in line with a1a5ea59433257ab3a46bb67aaf05e9b7d8aa071 where `checkInputs` were made native.

**Comment by FRidh** [comment]
By the way, how come this is not an attribute of `stdenv`?

**Comment by tobim** [comment]
Could probably also be done for `ccls` and `cquery`.

**Comment by Mic92** [comment]
@FRidh from my understanding only packages needed for build are in `stdenv` like coreutils, the build shell and the compiler.

**Comment by Ericson2314** [comment]
Woo! Marked that this should definitely go to 19.03 too.

**Review by Ericson2314 — APPROVED** [review]

**Pull request merged**
