### PR TITLE
 thunderbird, thunderbird-bin: 68.3.0 -> 68.3.1 

### PR DESCRIPTION
**Pull request by taku0**
###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @nbp, @edolstra, @lovesegfault

### CODE REVIEW

**Comment by lovesegfault** [comment]
Looking good!
```
[2 built]
https://github.com/NixOS/nixpkgs/pull/76118
2 package were built:
thunderbird thunderbird-bin
```

**Comment by jtojnar** [comment]
Would it be possible to re-evaluate whether the following packages are still necessary:

- libIDL (https://github.com/NixOS/nixpkgs/issues/39976)
- GConf
- libgnome
- libgnomeui
- gst-plugins-base (#39975) 
- gstreamer
- gtk2

**Comment by lovesegfault** [comment]
@jtojnar Absolutely, let's do that in a separate PR though; I'm on it.

**Review by vcunat — APPROVED** [review]
Both work fine for me (x86_64 NixOS).

**Comment by vcunat** [comment]
Links for completeness:
 - [release notes](https://www.thunderbird.net/en-US/thunderbird/68.3.1/releasenotes/#changes)
 - [no security fixes](https://www.mozilla.org/en-US/security/known-vulnerabilities/thunderbird/#thunderbird68.3), apparently

**Pull request merged**
