### PR TITLE
Python package set updates

### PR DESCRIPTION
**Pull request by FRidh**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonringer** [comment]
Traveling right now, but if you need help stabilizing, i can help sunday

**Comment by FRidh** [comment]
In this case I am only selecting specific packages, so it should mostly be fine.

**Comment by jonringer** [comment]
sounds good

**Comment by FRidh** [comment]
Current botocore can't handle docutils 0.16. Need to check whether an upgrade fixes it. Maybe https://github.com/NixOS/nixpkgs/pull/77254

**Comment by jonringer** [comment]
the problem is moto, it will break >100 other packages

**Pull request merged**
