### PR TITLE
(legacy) gstreamer: fetch archive with httpS instead of http

### PR DESCRIPTION
**Pull request by jpierre03**
###### Things done
- Built on platform(s)
   - [x] NixOS
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`

---

### CODE REVIEW

**Comment by joachifm** [comment]
The subject does not match the content. It changes `meta.homepage` not the archive url.

**Comment by jpierre03** [comment]
@joachifm It's true but incomplete. ```meta.homepage``` is used as URL prefix.

```
urls =
      [ "${meta.homepage}/src/gstreamer/${name}.tar.xz"
        "mirror://gentoo/distfiles/${name}.tar.xz"
      ];
```

IMHO it seems more important to express this impact as PR title than homepage impact.

**Comment by joachifm** [comment]
Makes sense, it's just not clear from the delta that this would be the case.

**Comment by jpierre03** [comment]
Thanks.
Indeed diff is not helpfull in this case.

**Pull request merged**
