### PR TITLE
atk: clean up

### PR DESCRIPTION
**Pull request by jtojnar**
###### Motivation for this change
Closes: #32296

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by jtojnar** [comment]
Mikutter fails to build:

<details>
<summary>Build log</summary>

```
WARNING:  You build with buildroot.
  Build root: /
  Bin dir: /nix/store/84mhf8b2qfmqlvq2ahj9acjpjmr9mkkj-ruby2.3.5-gio2-3.1.9/lib/ruby/gems/2.3.0/bin
  Gem home: /nix/store/84mhf8b2qfmqlvq2ahj9acjpjmr9mkkj-ruby2.3.5-gio2-3.1.9/lib/ruby/gems/2.3.0
Building native extensions.  This could take a while...
WARNING:  You build with buildroot.
  Build root: /
  Bin dir: /nix/store/rlbz8x089s4yrgfrfw60nxwcnb7g33sd-ruby2.3.5-pango-3.1.9/lib/ruby/gems/2.3.0/bin
  Gem home: /nix/store/rlbz8x089s4yrgfrfw60nxwcnb7g33sd-ruby2.3.5-pango-3.1.9/lib/ruby/gems/2.3.0
Building native extensions.  This could take a while...
ERROR:  Error installing /nix/store/h3zk0ldid1acka8wd5abxxa3ppi24pys-gio2-3.1.9.gem:
	ERROR: Failed to build gem native extension.

    current directory: /nix/store/84mhf8b2qfmqlvq2ahj9acjpjmr9mkkj-ruby2.3.5-gio2-3.1.9/lib/ruby/gems/2.3.0/gems/gio2-3.1.9/ext/gio2
/nix/store/fh53an3sv5ra1kb9vp10fy01xjjfx00l-ruby-2.3.5/bin/ruby -r ./siteconf20171213-1104-1hqvzbo.rb extconf.rb
checking for --enable-debug-build option... no
checking for -Wall option to compiler... yes
checking for -Waggregate-return option to compiler... yes
checking for -Wcast-align option to compiler... yes
checking for -Wextra option to compiler... yes
checking for -Wformat=2 option to compiler... yes
checking for -Winit-self option to compiler... yes
checking for -Wlarger-than-65500 option to compiler... yes
checking for -Wmissing-declarations option to compiler... yes
checking for -Wmissing-format-attribute option to compiler... yes
checking for -Wmissing-include-dirs option to compiler... yes
checking for -Wmissing-noreturn option to compiler... yes
checking for -Wmissing-prototypes option to compiler... yes
checking for -Wnested-externs option to compiler... yes
checking for -Wold-style-definition option to compiler... yes
checking for -Wpacked option to compiler... yes
checking for -Wp,-D_FORTIFY_SOURCE=2 option to compiler... yes
checking for -Wpointer-arith option to compiler... yes
checking for -Wswitch-default option to compiler... yes
checking for -Wswitch-enum option to compiler... yes
checking for -Wundef option to compiler... yes
checking for -Wout-of-line-declaration option to compiler... no
checking for -Wunsafe-loop-optimizations option to compiler... yes
checking for -Wwrite-strings option to compiler... yes
checking for Windows... no
checking for gio-2.0... yes
checking for gobject-introspection-1.0... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/nix/store/fh53an3sv5ra1kb9vp10fy01xjjfx00l-ruby-2.3.5/bin/$(RUBY_BASE_NAME)
	--enable-debug-build
	--disable-debug-build
	--with-pkg-config
	--without-pkg-config
	--with-override-variables
	--without-override-variables

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /nix/store/84mhf8b2qfmqlvq2ahj9acjpjmr9mkkj-ruby2.3.5-gio2-3.1.9/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/gio2-3.1.9/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /nix/store/84mhf8b2qfmqlvq2ahj9acjpjmr9mkkj-ruby2.3.5-gio2-3.1.9/lib/ruby/gems/2.3.0/gems/gio2-3.1.9 for inspection.
Results logged to /nix/store/84mhf8b2qfmqlvq2ahj9acjpjmr9mkkj-ruby2.3.5-gio2-3.1.9/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/gio2-3.1.9/gem_make.out
builder for ‘/nix/store/633imb0w5kc82ls5rvrvvnbz6fwnzpsl-ruby2.3.5-gio2-3.1.9.drv’ failed with exit code 1
```

</details>

Adding `gobjectIntrospection` to `buildInputs` is not enough.

**Comment by jtojnar** [comment]
For some reason, totem fails to build on hydra, even though it builds fine on my computer.

https://hydra.nixos.org/build/65987618

**Comment by jtojnar** [comment]
cc @midchildan for mikutter faiilure https://hydra.nixos.org/build/65972646

**Comment by midchildan** [comment]
@jtojnar I'm going to check, but it might take a few days.

**Comment by jtojnar** [comment]
Okay, managed to fix mikutter.

**Review by orivej — COMMENTED** [review]
Are all cases of `gobjectIntrospection # For setup hook` for its `_multioutMoveGlibGir` and not for `make_gobject_introspection_find_gir_files`? What do you think about enabling it by default? https://github.com/NixOS/nixpkgs/blob/3366ce99df61132b82e385617c1744dc352a83c2/pkgs/stdenv/generic/default.nix#L45-L60

**Comment by orivej** [comment]
> What do you think about enabling it by default?

Here: https://github.com/NixOS/nixpkgs/blob/3366ce99df61132b82e385617c1744dc352a83c2/pkgs/build-support/setup-hooks/multiple-outputs.sh#L150-L159

**Comment by jtojnar** [comment]
They are actually for `make_gobject_introspection_find_gir_files`.

**Comment by grahamc** [comment]
@GrahamcOfBorg eval

**Pull request merged**
