### PR TITLE
cpython: Pull in the mime-types database

### LINKED ISSUE #113901: Python 3's mimetypes module is broken on NixOS
#### Bug description

Python 3 provides a `mimetypes` module to interact with the system's MIME types database.  This seems broken on NixOS, where it fails to recognise many common formats.

#### Reproduction instructions

1. Clone [mat2]'s git repository; the issue isn't confined to mat2, and it was convenient to use its test fixtures to reproduce the bug.
2. Run the following test script
```python3
import mimetypes
from pathlib import Path

for file in (Path.cwd() / 'mat2' / 'tests' / 'data').iterdir():
    ty, _ = mimetypes.guess_type(file)
    if ty is None:
        print(f"'{file}' not recognised")
```

[mat2]: https://0xacab.org/jvoisin/mat2/

#### Expected behavior

No output, as everything is recognised, like on other distributions (I tested on Debian bullseye).

#### Actual behaviour

```
'/tmp/tmp.eldqIS77YO/mat2/tests/data/weird_producer.odt' not recognised
'/tmp/tmp.eldqIS77YO/mat2/tests/data/revision.odt' not recognised
'/tmp/tmp.eldqIS77YO/mat2/tests/data/revision.docx' not recognised
'/tmp/tmp.eldqIS77YO/mat2/tests/data/office_revision_session_ids.docx' not recognised
'/tmp/tmp.eldqIS77YO/mat2/tests/data/no_content_types.docx' not recognised
'/tmp/tmp.eldqIS77YO/mat2/tests/data/narrated_powerpoint_presentation.pptx' not recognised
'/tmp/tmp.eldqIS77YO/mat2/tests/data/malformed_content_types.docx' not recognised
'/tmp/tmp.eldqIS77YO/mat2/tests/data/embedded_corrupted.odt' not recognised
'/tmp/tmp.eldqIS77YO/mat2/tests/data/embedded_corrupted.docx' not recognised
'/tmp/tmp.eldqIS77YO/mat2/tests/data/embedded.odt' not recognised
'/tmp/tmp.eldqIS77YO/mat2/tests/data/embedded.docx' not recognised
'/tmp/tmp.eldqIS77YO/mat2/tests/data/dirty_with_nsid.docx' not recognised
'/tmp/tmp.eldqIS77YO/mat2/tests/data/dirty.wmv' not recognised
'/tmp/tmp.eldqIS77YO/mat2/tests/data/dirty.torrent' not recognised
'/tmp/tmp.eldqIS77YO/mat2/tests/data/dirty.ogg' not recognised
'/tmp/tmp.eldqIS77YO/mat2/tests/data/dirty.odt' not recognised
'/tmp/tmp.eldqIS77YO/mat2/tests/data/dirty.odg' not recognised
'/tmp/tmp.eldqIS77YO/mat2/tests/data/dirty.odf' not recognised
'/tmp/tmp.eldqIS77YO/mat2/tests/data/dirty.flac' not recognised
'/tmp/tmp.eldqIS77YO/mat2/tests/data/dirty.epub' not recognised
'/tmp/tmp.eldqIS77YO/mat2/tests/data/dirty.docx' not recognised
'/tmp/tmp.eldqIS77YO/mat2/tests/data/broken_xml_content_types.docx' not recognised
```

#### Additional context

Ran into this issue while packaging `mat2`, see #112413.

#### Notify maintainers

@FRidh 

#### Metadata
```yaml
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.94, NixOS, 21.03pre267696.fab6fcdceb2 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(nicoo): `"home-manager"`
 - channels(root): `"nixos-21.03pre267696.fab6fcdceb2, nixpkgs-20.09pre239808.ddfa2216701"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- python27
- python36
- python37
- python38
- python39
- python310
```

### PR DESCRIPTION
**Pull request by nicoonoclaste**
###### Motivation for this change

Fix #113901

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nbraud** [comment]
@FRidh This is the patch I mentioned just earlier; I'm currently trying to do the required testing, but rebuilding everything involved is proving difficult.

**Comment by nbraud** [comment]
Ahah, `mime-types` seems to be broken currently

**Comment by FRidh** [comment]
Do we want to refer to mime-types purely, or impurely? To me this seems like something may want to load impurely, but not necessarily. https://wiki.debian.org/MIME/etc/mime.types

> I'm currently trying to do the required testing, but rebuilding everything involved is proving difficult.

Just building the interpreters is sufficient, this can't possibly break anything more.

> PS: There seems to be unrelated breakage, when I try to evaluate the updated derivations:

This eval error is because `python3` is needed for bootstrapping, and the bootstrapping closure can only use `builtins.fetchurl` for fetching. `mime-types` uses `fetchzip`, so this won't work. Maybe we do not need `fetchzip`.

**Comment by nbraud** [comment]
> Do we want to refer to mime-types purely, or impurely? To me this seems like something may want to load impurely, but not necessarily. https://wiki.debian.org/MIME/etc/mime.types

I think we should do it purely, given that unexpected changes (or entirely-missing files) can break applications, like it did for me with `mat2`.  This way, we know that Python applications use the same MIME types DB at runtime as when they were built and tested.

> > PS: There seems to be unrelated breakage, when I try to evaluate the updated derivations:
> 
> This eval error is because `python3` is needed for bootstrapping, and the bootstrapping closure can only use `builtins.fetchurl` for fetching. `mime-types` uses `fetchzip`, so this won't work. Maybe we do not need `fetchzip`.

Oooh, thanks.  The error message was rather cryptic.

**Comment by SuperSandro2000** [comment]
> but rebuilding everything involved is proving difficult.

Hit me up when it evals and I can build all python interpreters for you.

**Comment by SuperSandro2000** [comment]
@nbraud Are you still working on this PR? If not leave me a quick message and I would convert mime-types to work into bootstrap.

**Comment by FRidh** [comment]
In https://github.com/NixOS/nixpkgs/commit/b861209521aacada646a209e4c5370cc97cffe3c mimetypes was converted to a fixed-output derivation. `postFetch` is not available for builtins.fetchurl.

**Comment by FRidh** [comment]
(note to self: local commit 6e619eddbbb)

**Comment by FRidh** [comment]
By not having python3 override python3Minimal mime-types does not need to eval for python3Minimal, and so mime-types can stay as it is. Checking now whether nuke-refs removes too much. Do need a test for this.

**Comment by FRidh** [comment]
Pushed to staging as faf0f8a8a4134edbeec0a73de7f938453444186d as well as some other changes.

**Pull request closed without merging**
