### PR TITLE
nixos/icingaweb2: Fix php extensions package

### PR DESCRIPTION
**Pull request by dasJ**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dasJ** [comment]
@GrahamcOfBorg test icingaweb2

**Review by talyz — COMMENTED** [review]
Note that we now have functions to build a PHP with extensions - `php.withExtensions` or `php.buildEnv`. They're documented in `doc/languages-frameworks/php.section.md` if you want to know more. It's not strictly necessary to use them, of course - with the current functionality in the module, it shouldn't really matter; it mostly matters if you want to implement a way for people to specify the PHP package in use.

If you want to go with the current solution, I would recommend using `php.extensions` instead of `phpExtensions`, though. `phpExtensions` should probably be removed anyways to lessen confusion.

**Comment by dasJ** [comment]
@talyz Using php.extensions instead of phpExtensions is not really obvious. Wouldn't `lib.warn` help in that case?

**Comment by talyz** [comment]
It's not, no, which is why I think it should be removed. This isn't something that we've decided to do, though - just my personal opinion. I'll probably fix it in a future pr. :)

**Pull request closed without merging**
