### PR TITLE
python311Packages.cvxpy: 1.4.3 -> 1.5.2

### PR DESCRIPTION
**Pull request by GaetanLepage**
## Description of changes

Changelog: https://github.com/cvxpy/cvxpy/releases/tag/v1.5.2

cc @drewrisinger 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by GaetanLepage** [comment]
# Current issue (`scs` not building)

- The build phase of `scs` requires `numpy >=2`.
- At the same time, we cannot have `numpy_2` in `dependencies` as it would lead to many collisions with other python packages that propagate `numpy` (i.e. v1.xx)

However, naively adding `numpy_2` to `build-inputs` and `numpy` in `dependencies` leads to a failure of the `importsCheckPhase`:

<details>

```
Executing pythonImportsCheckPhase
Check whether the following modules can be imported: scs

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "/nix/store/hyppxdhgqx7nbg394j97yhmi6vizl074-python3-3.11.9/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/nix/store/5dsxqpwq55zp1q067938jnzifkv2amgq-python3.11-scs-3.2.6/lib/python3.11/site-packages/scs/__init__.py", line 3, in <module>
    from scipy import sparse
  File "/nix/store/5hm7542sdrcmny8ski2a3nckmspfcv78-python3.11-scipy-1.14.0/lib/python3.11/site-packages/scipy/__init__.py", line 134, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "/nix/store/hyppxdhgqx7nbg394j97yhmi6vizl074-python3-3.11.9/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/nix/store/5hm7542sdrcmny8ski2a3nckmspfcv78-python3.11-scipy-1.14.0/lib/python3.11/site-packages/scipy/sparse/__init__.py", line 294, in <module>
    from ._csr import *
  File "/nix/store/5hm7542sdrcmny8ski2a3nckmspfcv78-python3.11-scipy-1.14.0/lib/python3.11/site-packages/scipy/sparse/_csr.py", line 11, in <module>
    from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks,
Traceback (most recent call last):
  File "/nix/store/scmvsl83ff74vksp77k47wzyky77qmsz-python3.11-numpy-2.0.0/lib/python3.11/site-packages/numpy/core/_multiarray_umath.py", line 44, in __getattr__
    raise ImportError(msg)
ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.


Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "/nix/store/hyppxdhgqx7nbg394j97yhmi6vizl074-python3-3.11.9/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nix/store/5dsxqpwq55zp1q067938jnzifkv2amgq-python3.11-scs-3.2.6/lib/python3.11/site-packages/scs/__init__.py", line 3, in <module>
    from scipy import sparse
  File "/nix/store/5hm7542sdrcmny8ski2a3nckmspfcv78-python3.11-scipy-1.14.0/lib/python3.11/site-packages/scipy/__init__.py", line 134, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/hyppxdhgqx7nbg394j97yhmi6vizl074-python3-3.11.9/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/5hm7542sdrcmny8ski2a3nckmspfcv78-python3.11-scipy-1.14.0/lib/python3.11/site-packages/scipy/sparse/__init__.py", line 294, in <module>
    from ._csr import *
  File "/nix/store/5hm7542sdrcmny8ski2a3nckmspfcv78-python3.11-scipy-1.14.0/lib/python3.11/site-packages/scipy/sparse/_csr.py", line 11, in <module>
    from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks,
ImportError: numpy.core.multiarray failed to import
```

</details>

**Comment by paparodeo** [comment]
just use numpy and patch out the version requirement.

<details><summary>diff</summary>

```diff
diff --git a/pkgs/development/python-modules/scs/default.nix b/pkgs/development/python-modules/scs/default.nix
index 2ee30a421478..efa84c7e4f57 100644
--- a/pkgs/development/python-modules/scs/default.nix
+++ b/pkgs/development/python-modules/scs/default.nix
@@ -6,7 +6,6 @@
 
   # build-system
   meson-python,
-  numpy_2,
   pkg-config,
 
   # buildInputs
@@ -35,9 +34,13 @@ buildPythonPackage rec {
     fetchSubmodules = true;
   };
 
+  postPatch = ''
+    substituteInPlace pyproject.toml --replace-warn "numpy >= 2.0.0" "numpy"
+  '';
+
   build-system = [
     meson-python
-    numpy_2
+    numpy
     pkg-config
   ];
 
```
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 325493` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
    <li>python311Packages.blackjax</li>
    <li>python311Packages.blackjax.dist</li>
    <li>python311Packages.jaxopt</li>
    <li>python311Packages.jaxopt.dist</li>
    <li>python312Packages.blackjax</li>
    <li>python312Packages.blackjax.dist</li>
    <li>python312Packages.jaxopt</li>
    <li>python312Packages.jaxopt.dist</li>
  </ul>
</details>
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>python311Packages.cvxpy</li>
    <li>python311Packages.cvxpy.dist</li>
    <li>python311Packages.qpsolvers</li>
    <li>python311Packages.qpsolvers.dist</li>
    <li>python311Packages.qutip</li>
    <li>python311Packages.qutip.dist</li>
    <li>python311Packages.scs</li>
    <li>python311Packages.scs.dist</li>
    <li>python312Packages.cvxpy</li>
    <li>python312Packages.cvxpy.dist</li>
    <li>python312Packages.qpsolvers</li>
    <li>python312Packages.qpsolvers.dist</li>
    <li>python312Packages.qutip</li>
    <li>python312Packages.qutip.dist</li>
    <li>python312Packages.scs</li>
    <li>python312Packages.scs.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 325493` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
    <li>python311Packages.blackjax</li>
    <li>python311Packages.blackjax.dist</li>
    <li>python311Packages.jaxopt</li>
    <li>python311Packages.jaxopt.dist</li>
    <li>python312Packages.blackjax</li>
    <li>python312Packages.blackjax.dist</li>
    <li>python312Packages.jaxopt</li>
    <li>python312Packages.jaxopt.dist</li>
  </ul>
</details>
<details>
  <summary>16 packages built:</summary>
  <ul>
    <li>python311Packages.cvxpy</li>
    <li>python311Packages.cvxpy.dist</li>
    <li>python311Packages.qpsolvers</li>
    <li>python311Packages.qpsolvers.dist</li>
    <li>python311Packages.qutip</li>
    <li>python311Packages.qutip.dist</li>
    <li>python311Packages.scs</li>
    <li>python311Packages.scs.dist</li>
    <li>python312Packages.cvxpy</li>
    <li>python312Packages.cvxpy.dist</li>
    <li>python312Packages.qpsolvers</li>
    <li>python312Packages.qpsolvers.dist</li>
    <li>python312Packages.qutip</li>
    <li>python312Packages.qutip.dist</li>
    <li>python312Packages.scs</li>
    <li>python312Packages.scs.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 325493` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
  </ul>
</details>
<details>
  <summary>24 packages built:</summary>
  <ul>
    <li>python311Packages.blackjax</li>
    <li>python311Packages.blackjax.dist</li>
    <li>python311Packages.cvxpy</li>
    <li>python311Packages.cvxpy.dist</li>
    <li>python311Packages.jaxopt</li>
    <li>python311Packages.jaxopt.dist</li>
    <li>python311Packages.qpsolvers</li>
    <li>python311Packages.qpsolvers.dist</li>
    <li>python311Packages.qutip</li>
    <li>python311Packages.qutip.dist</li>
    <li>python311Packages.scs</li>
    <li>python311Packages.scs.dist</li>
    <li>python312Packages.blackjax</li>
    <li>python312Packages.blackjax.dist</li>
    <li>python312Packages.cvxpy</li>
    <li>python312Packages.cvxpy.dist</li>
    <li>python312Packages.jaxopt</li>
    <li>python312Packages.jaxopt.dist</li>
    <li>python312Packages.qpsolvers</li>
    <li>python312Packages.qpsolvers.dist</li>
    <li>python312Packages.qutip</li>
    <li>python312Packages.qutip.dist</li>
    <li>python312Packages.scs</li>
    <li>python312Packages.scs.dist</li>
  </ul>
</details>

**Comment by GaetanLepage** [comment]
Result of `nixpkgs-review pr 325493` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
  </ul>
</details>
<details>
  <summary>24 packages built:</summary>
  <ul>
    <li>python311Packages.blackjax</li>
    <li>python311Packages.blackjax.dist</li>
    <li>python311Packages.cvxpy</li>
    <li>python311Packages.cvxpy.dist</li>
    <li>python311Packages.jaxopt</li>
    <li>python311Packages.jaxopt.dist</li>
    <li>python311Packages.qpsolvers</li>
    <li>python311Packages.qpsolvers.dist</li>
    <li>python311Packages.qutip</li>
    <li>python311Packages.qutip.dist</li>
    <li>python311Packages.scs</li>
    <li>python311Packages.scs.dist</li>
    <li>python312Packages.blackjax</li>
    <li>python312Packages.blackjax.dist</li>
    <li>python312Packages.cvxpy</li>
    <li>python312Packages.cvxpy.dist</li>
    <li>python312Packages.jaxopt</li>
    <li>python312Packages.jaxopt.dist</li>
    <li>python312Packages.qpsolvers</li>
    <li>python312Packages.qpsolvers.dist</li>
    <li>python312Packages.qutip</li>
    <li>python312Packages.qutip.dist</li>
    <li>python312Packages.scs</li>
    <li>python312Packages.scs.dist</li>
  </ul>
</details>

**Pull request merged**
