### PR TITLE
treewide: remove unused variables

### PR DESCRIPTION
**Pull request by volth**
Rerun the bot which did https://github.com/NixOS/nixpkgs/pull/43857
It should have no effect besides the cleanup

### CODE REVIEW

**Comment by Profpatsch** [comment]
Is the source code to the bot available anywhere?

**Comment by volth** [comment]
@Profpatsch https://gist.github.com/volth/297b24d577f9868255210c31479fd56b

**Comment by LnL7** [comment]
@volth FYI https://github.com/NixOS/ofborg#running-meta-checks-locally

**Comment by volth** [comment]
OK, ofborg is happy.
Please do not hold it for long time, soon there will be merge conflicts

**Comment by alyssais** [comment]
> 10.rebuild-linux: 1-10

Is that correct? What's being rebuilt?

**Comment by volth** [comment]
>> 10.rebuild-linux: 1-10

> Is that correct? What's being rebuilt?

Maybe ```pkgs/applications/science/biology/sumatools/default.nix``` (there was ```let meta = ... in``` which I did not delete but added ```inherit meta``` below, apparently forgotten)

**Comment by 7c6f434c** [comment]
Just for information: «Show all checks» → eval — Details

There are `sup`, `sumatra`, `terraform` and some others.

**Comment by volth** [comment]
So, another group are derivations with ```gemdir = ./.;```
They will be rebuilt even on changes in comments or whitespacing.

**Comment by alyssais** [comment]
> So, another group are derivations with ```gemdir = ./.;```
> They will be rebuilt even on changes in comments or whitespacing.

I wonder if that might be a reason to consider deprecating gemdir... we
definitely shouldn't be copying the whole directory to the store.

**Comment by volth** [comment]
>> So, another group are derivations with ```gemdir = ./.;``` They will be rebuilt even on changes in comments or whitespacing.

> I wonder if that might be a reason to consider deprecating gemdir... we definitely shouldn't be copying the whole directory to the store.

It is not only `gemdir`, some python modules use `src = ./.`

**Comment by alyssais** [comment]
> It is not only `gemdir`, some python modules use `src = ./.`

Perhaps those should go too then. Feels like an antipattern.

**Comment by Mic92** [comment]
@zimbatm introduced that. I think it should be possible to only add the files we actually need to the nix store.

**Pull request merged**
