### PR TITLE
cudatoolkit_11, cudnn_cudatoolkit_11: 11.1 -> 11.2

### PR DESCRIPTION
**Pull request by danieldk**
###### Motivation for this change

This PR bundles a lot of updates and a fix:

- Add `cudatoolkit_11_2` (11.2.1)
- The cudatoolkit_11_1 top-level attribute was missing, add it.
- cudnn_cudatoolkit_11_0: 8.0.2 -> 8.1.0
- Add cudnn_cudatoolkit_11_1 and cudnn_cudatoolkit_11_1,
  which also use CDNN 8.1.0.
- Switch the cudatoolkit_11 and cudnn_cudatoolkit_11 aliases to 11_2 versions.

This PR and #112636 prepare for updating PyTorch to support the latest
GPUs.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 112648` at f1db117b run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>colmapWithCuda</li>
    <li>python37Packages.tensorflowWithCuda</li>
    <li>python38Packages.tensorflowWithCuda</li>
    <li>python39Packages.tensorflowWithCuda</li>
  </ul>
</details>

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 112648` at f1db117b run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>python39Packages.tensorflowWithCuda</li>
  </ul>
</details>
<details>
  <summary>9 packages failed to build:</summary>
  <ul>
    <li>colmapWithCuda</li>
    <li>cudatoolkit_11 (cudaPackages.cudatoolkit_11 ,cudatoolkit_11_2)</li>
    <li><a href="https://gist.github.com/2f91dc9d24cf32a7afea338d9ea1a74d">cudatoolkit_11_1</a></li></li>
    <li>cudnn_cudatoolkit_11 (cudnn_cudatoolkit_11_2)</li>
    <li>cudnn_cudatoolkit_11_0</li>
    <li>cudnn_cudatoolkit_11_1</li>
    <li>nccl_cudatoolkit_11</li>
    <li>python37Packages.tensorflowWithCuda</li>
    <li>python38Packages.tensorflowWithCuda</li>
  </ul>
</details>

**Comment by danieldk** [comment]
Unrelated errors in the build above:

```
/nix/store/h50ypqigilk8cv8a2gvwr2x2gl6pfq8v-stdenv-linux/setup: line 803: export: write error: No space left on device
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
/nix/store/h50ypqigilk8cv8a2gvwr2x2gl6pfq8v-stdenv-linux/setup: line 803: export: write error: No space left on device
Creating directory pkg
mkdir: cannot create directory 'pkg': No space left on device
Cannot create target directory pkg
You should try option --target OtherDirectory
```

**Comment by danieldk** [comment]
Cc previous reviewers: @bhipple @prusnak @lovesegfault @mdaiter

**Review by bhipple — APPROVED** [review]

**Comment by lovesegfault** [comment]
Result of `nixpkgs-review pr 112648` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>python39Packages.tensorflowWithCuda</li>
  </ul>
</details>
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>colmapWithCuda</li>
    <li>cudatoolkit_11 (cudaPackages.cudatoolkit_11 ,cudatoolkit_11_2)</li>
    <li>cudatoolkit_11_1</li>
    <li>cudnn_cudatoolkit_11 (cudnn_cudatoolkit_11_2)</li>
    <li>cudnn_cudatoolkit_11_0</li>
    <li>cudnn_cudatoolkit_11_1</li>
    <li>nccl_cudatoolkit_11</li>
    <li>python37Packages.tensorflowWithCuda</li>
    <li>python38Packages.tensorflowWithCuda</li>
  </ul>
</details>

**Pull request merged**
