### PR TITLE
fish: add module to support it as default shell

### LINKED ISSUE #5331: Make fish easily configurable as a default shell
This is a feature request. May you please make `fish` shell easily configurable as a default shell. With `zsh`, for example, I can simply enable it like so `programs.zsh.enable = true;` and set `users.defaultUserShell = "/run/current-system/sw/bin/zsh";`.

cc @ocharles

### PR DESCRIPTION
**Pull request by jgillich**
- Patched fish to load /etc/fish/config.fish if it exists (by default,
  it only loads config relative to itself)
- Added fish-foreign-env package to parse the system environment

closes #5331

### CODE REVIEW

**Comment by jgillich** [comment]
There is a `builtin` command, so I will look into using that instead of dropping the `status` alias. Also, I'm getting a `expr command not defined` when I log in via Linux ttyX, which is really weird. SSH works fine however.

**Comment by jagajaga** [comment]
:+1:

**Comment by gpyh** [comment]
This is awesome. I'll test this after the holidays.

**Comment by jgillich** [comment]
Ok I fixed all remaining issues and patched the status command. Should be good to merge after someone else confirmed it works.

**Comment by jgillich** [comment]
Seems like the `status` fixes won't be accepted upstream (https://github.com/fish-shell/fish-shell/pull/2636). It can understand their reasoning, but it still sucks from a NixOS perspective; updating fish is not going to be a trivial task.

**Comment by Profpatsch** [comment]
Seems to work splendidly. The code also looks sane. +1

**Comment by Profpatsch** [comment]
@jagajaga Merge?

**Comment by jagajaga** [comment]
@Profpatsch have you tested it? I don't have any opportunity to do that.

**Comment by Profpatsch** [comment]
@jagajaga Yes, I have applied the patch and fish works as user shell without throwing any kind of error. Looks good to me.

**Pull request merged**
