### PR TITLE
go: 1.14.3 -> 1.14.4

### PR DESCRIPTION
**Pull request by zowoq**
https://golang.org/doc/devel/release.html#go1.14.minor

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

~~8d41f9f281a8317faa45c4270e8d48bf657cc1a0~~

~~Targeting `staging-next` as the previous `go` version bump hasn't landed in master yet.~~

### CODE REVIEW

**Comment by drewrisinger** [comment]
Diff LGTM, but failing tests on OfBorg aarch64-linux.

**Comment by zowoq** [comment]
@ofborg build go

**Comment by c00w** [comment]
Failure message is
```
--- FAIL: TestDontCacheBrokenHTTP2Conn (0.05s)
    transport_test.go:6079: for iteration 5, doBreak=false; unexpected error Get "https://127.0.0.1:40267": some write error
    transport_test.go:6083: GotConn calls = 0; want 1
```

**Comment by zowoq** [comment]
Looks like it doesn't occur very often, I'll let the package maintainers decide if we want to disable that particular test or not.

**Comment by c00w** [comment]
If it's flaky, can we file a report with the go team and disable it? I think we have lots of other disabled go tests + they passed on upstream so I'm not super concerned about a single test failing.

**Comment by c00w** [comment]
I'm also not a maintainer and can't merge :D so this is just my personal opinion.

**Comment by mdlayher** [comment]
Possibly related? https://github.com/golang/go/issues/35113

**Comment by Mic92** [comment]
Does cherry-picking https://github.com/golang/go/commit/ea1437a8cdf6bb3c2d2447833a5d06dbd75f7ae4 works?

**Comment by zowoq** [comment]
> Does cherry-picking [golang/go@ea1437a](https://github.com/golang/go/commit/ea1437a8cdf6bb3c2d2447833a5d06dbd75f7ae4) fix the error?

> https://github.com/golang/go/commit/ea1437a8cdf6bb3c2d2447833a5d06dbd75f7ae4
> On my laptop, before this commit, TestDontCacheBrokenHTTP2Conn
failed 66 times out of 20,000. With this commit, I see 0 out of 20,000.

I've added the patch but it might be had to tell if it fixes it or not. 

The patch doesn't apply for `1.13`. As nothing depends on it, it will be EOL soon and we've already deleted it once I'm not going to bother trying to patch it.

**Comment by zowoq** [comment]
@ofborg build go

**Review by mdlayher — APPROVED** [review]
LGTM. I am still fairly new to NixOS and am slightly concerned by pulling in patches that aren't part of the upstream Go 1.14.4, but it seems that is the usual pattern here.

**Pull request merged**
