### PR TITLE
Enable Kerberos by default for OpenSSH

### PR DESCRIPTION
**Pull request by aneeshusa**
###### Motivation for this change
@grantwwu recently made a [mailing list post](https://groups.google.com/forum/#!topic/nix-devel/JdWuZaZ_Njw) about making using OpenSSH with Kerberos easier. As one of the openssh maintainers, I think the easiest thing to do here is to enable Kerberos by default.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aneeshusa** [comment]
I still need to run the NixOS tests and such, but wanted to post this for discussion.

**Comment by bjornfor** [comment]
-1 for the first commit, +2 for the second commit (PR topic).

**Comment by grahamc** [comment]
@GrahamcOfBorg test openssh

**Comment by grahamc** [comment]
re that test failure I left this comment on the PR I suspect is responsible: https://github.com/NixOS/nixpkgs/pull/34350#issuecomment-361094147

**Comment by fpletz** [comment]
@GrahamcOfBorg test openssh

**Comment by grahamc** [comment]
@GrahamcOfBorg test initrd-network-ssh

**Comment by grahamc** [comment]
@aneeshusa can you remove the first commit? Then I think this is good to merge.

**Comment by grahamc** [comment]
Ehh I'll just pick it :)

**Comment by aneeshusa** [comment]
I'd like to run the NixOS tests, test the hpn build, etc. before merging.

**Comment by grahamc** [comment]
Applied the second commit in a232dd66ee0b390dc4d82858af7e15713bd60327, thanks!

**Comment by grahamc** [comment]
Erm... sorry @aneeshusa, so I ran the initrd ssh test and the openssh test prior to merging (see: https://github.com/NixOS/nixpkgs/pull/34348#pullrequestreview-92065944, https://github.com/NixOS/nixpkgs/pull/34348#pullrequestreview-92065793) but what about hpn?

**Comment by aneeshusa** [comment]
No worries @grahamc. The two other things I wanted to check were that the top-level `openssh_hpn` package builds, and also to run the `openssh.nix` NixOS test. I ran those both just now with a fresh staging and they both succeeded. Since SSH is critical for remote connectivity, I prefer to be thorough before merging updates.

I think this could also merit a line or two in the release notes.

**Comment by grahamc** [comment]
Sounds good, @aneeshusa. Thanks for testing. Can you submit a patch for the release notes?

**Pull request closed without merging**
