### PR TITLE
Add Dr Robotnik'ss Ring Racers

### PR DESCRIPTION
**Pull request by TheHans255**
## Description of changes

This adds the game "Dr. Robotnik's Ring Racers", the sequel to Sonic Robo Blast 2 Kart (srb2kart).
The homepage for this project can be found here: https://www.kartkrew.org/,
and the developers have published a more in-depth description in their Flatpak: 
https://flathub.org/apps/org.kartkrew.RingRacers.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by TheHans255** [comment]
@viric @donovanglover Thought you might be interested in this review since you two are listed as maintainers of the SRB2Kart package.

**Comment by TheHans255** [comment]
General question: the code itself is licensed under GPL2, but a good chunk of the assets are made by SEGA and are used under fair-use doctrine (under the strict condition that the game should not be sold). Would this entail that the `assets` derivation be marked as unfree?

**Comment by donovanglover** [comment]
Already made a PR here: https://github.com/NixOS/nixpkgs/pull/306820

Can we continue discussion in the original PR? Let me know if you want me to add you as a maintainer!

**Comment by TheHans255** [comment]
> Already made a PR here: #306820
> 
> Can we continue discussion in the original PR? Let me know if you want me to add you as a maintainer!

Oh, cool! Apologies, I forgot to check if there was already an existing PR for this game - we can definitely continue there. 

Yes, I'd love to be added as a maintainer! We'll also need to add my credentials to the maintainers file.

**Pull request closed without merging**
