### PR TITLE
ponyc: update to 0.37.0

### PR DESCRIPTION
**Pull request by redvers**
###### Motivation for this change
ponyc had been stalled at v0.33.2 for a while for three reasons:

1. The buildsystem had been changed from make to cmake
2. A bug was discovered in LLVM 9.x which caused SIGSEGV in the test suite.  The fix has been applied to LLVM upstream but is in the 10.x and master branch.  Since ponyc currently uses 9.x, the build requires a patched+fixed llvm **for the build only**
3. The additional complexity of the (temporary) build-system in use was a real pain to integrate into a nix package.

I believe I have finally tamed this beast.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Note - I do not own a Mac so I'm going to be reliant on hydra to test against that platform.

Thanks!

### CODE REVIEW

**Comment by evanjs** [comment]
Is there any way we can use the already in-tree expressions for `gtest`/`gbenchmark`?
Not sure if optimal for this case, but I wonder if it would simplify these changes, any.

**Comment by redvers** [comment]
> Is there any way we can use the already in-tree expressions for `gtest`/`gbenchmark`?
> Not sure if optimal for this case, but I wonder if it would simplify these changes, any.

I actually tried that originally as I wanted to reduce the amount of work I had to do.  I was not successful in pulling it in successfully.  That very well may be due to my lack of knowledge of cmake, but I spent several hours in the attempt.

I consoled myself by reminding myself that it never exits the build process.

**Comment by redvers** [comment]
Reference https://github.com/NixOS/nixpkgs/issues/98376

**Comment by redvers** [comment]
While attempting to rebase I made a mess.  Will open a new PR.

**Pull request closed without merging**
