### PR TITLE
obfs4: 0.0.12 -> 0.0.14-tor2

### PR DESCRIPTION
**Pull request by ghost**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by amjoseph-nixpkgs** [comment]
CC @thoughtpolice

**Review by taku0 — APPROVED** [review]
It works on my machine.
`nyx` reports `ServerTransportPlugin obfs4 exec /nix/store/c43java7gyigh67fj5dvwz471cjxsb5h-obfs4-0.0.14-tor2/bin/obfs4proxy managed` and it establishes inbound and outbound connections.

**Comment by taku0** [comment]
The Tor Anti-Censoship Team sent the following mail to Tor Bridge operators:

> Hello,
> 
> I'm contacting you as you operate a Tor Bridge. First thank you for running the
> bridge and helping others with it.
> 
> There is a new version of obfs4proxy (0.0.14) that fixes some important
> obfuscation bugs, the details of will be published soon. Please upgrade as soon
> as possible, to keep users safe.
> 
> If you use debian you can find the Debian package in stable-backports:
>   https://packages.debian.org/stable-backports/obfs4proxy
> 
> If you use docker you'll find the latest version in docker hub:
>   https://hub.docker.com/r/thetorproject/obfs4-bridge/
> 
> We are providing a package for ubuntu jammy:
>   https://people.torproject.org/~meskio/jammy/obfs4proxy_0.0.14-1_amd64.deb
> 
> Or you can find the source code in the upstream repository:
>   https://gitlab.com/yawning/obfs4
> 
> If you need help upgrading your relay, please use the tor-relays mailing list:
>   https://lists.torproject.org/cgi-bin/mailman/listinfo/tor-relays
> Or the Tor Forum:
>   https://forum.torproject.net/c/support/relay-operator/17
> 
> We appreciate a lot your effort and time!
> Thank you
> 
> The Tor Anti-Censoship Team

**Comment by amjoseph-nixpkgs** [comment]
I think maybe ofborg got stuck.

@ofborg eval

**Review by Luflosi — APPROVED** [review]

**Comment by taku0** [comment]
#203929 is merged. Closing.

**Pull request closed without merging**
