### PR TITLE
rust-analyzer: use nix-update-script

### PR DESCRIPTION
**Pull request by figsoda**
###### Description of changes

found out about this from https://github.com/NixOS/nixpkgs/pull/215733#discussion_r1103260533, figured this will make things simpler

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by oxalica** [comment]
Update script returns 0 but `cargoHash` is not filled.

```shell
$ nix-shell maintainers/scripts/update.nix --argstr package rust-analyzer-unwrapped

Going to be running update for following packages:
 - rust-analyzer-unwrapped-2023-01-30

Press Enter key to continue...

Running update for:
 - rust-analyzer-unwrapped-2023-01-30: UPDATING ...
 - rust-analyzer-unwrapped-2023-01-30: DONE.

Packages updated!

$ git diff --no-ext-diff | cat
diff --git a/pkgs/development/tools/rust/rust-analyzer/default.nix b/pkgs/development/tools/rust/rust-analyzer/default.nix
index 47028160d17..bd6758bd912 100644
--- a/pkgs/development/tools/rust/rust-analyzer/default.nix
+++ b/pkgs/development/tools/rust/rust-analyzer/default.nix
@@ -13,14 +13,14 @@

 rustPlatform.buildRustPackage rec {
   pname = "rust-analyzer-unwrapped";
-  version = "2023-01-30";
-  cargoSha256 = "sha256-ONziMXbMPDoIb44mOJCg5O1QOo5o13kaGb+b6Qp3Ikk=";
+  version = "2023-02-06";
+  cargoSha256 = "";

   src = fetchFromGitHub {
     owner = "rust-lang";
     repo = "rust-analyzer";
     rev = version;
-    sha256 = "sha256-W8abw+8SuxSMMBH4ydfawdC6zwPHQwhHerFEXkB4oU4=";
+    sha256 = "sha256-apIUZwMwZkWqd7anSGcI1g+2rYfd5GoxIpFFabUFYBU=";
   };

   auditable = true; # TODO: remove when this is the default
```

**Comment by figsoda** [comment]
I can't reproduce the error, but I agree nix-update should exit with an error here

**Comment by figsoda** [comment]
opened https://github.com/Mic92/nix-update/pull/139 to fix this upstream, we can hold on to this until nix-update is updated

**Review by wegank — APPROVED** [review]

**Comment by figsoda** [comment]
@oxalica could you check now that nix-update is updated?

**Review by oxalica — APPROVED** [review]
Works for me.

**Pull request merged**
