### PR TITLE
chefdk: 2.4.17 -> 4.2.0

### PR DESCRIPTION
**Pull request by nicknovitski**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @offlinehacker

### CODE REVIEW

**Comment by mmahut** [comment]
@GrahamcOfBorg build chefdk

**Comment by mmahut** [comment]
Failure on ```aarch64-linux```.

```
unf/table.hh:13539:25: error: narrowing conversion of '-89' from 'int' to 'char' inside { } [-Wnarrowing]
unf/table.hh:13539:25: error: narrowing conversion of '-104' from 'int' to 'char' inside { } [-Wnarrowing]
unf/table.hh:13539:25: error: narrowing conversion of '-25' from 'int' to 'char' inside { } [-Wnarrowing]
unf/table.hh:13539:25: error: narrowing conversion of '-82' from 'int' to 'char' inside { } [-Wnarrowing]
```

**Comment by offlinehacker** [comment]
It seems like a dependant package for aarch64, I would still merge, and someone can fix later if needed. Optionally we can remove from supported systems.

**Review by offlinehacker — APPROVED** [review]

**Comment by mmahut** [comment]
Please either fix it or disable aarch64, we cannot merge changes that will produce build failures.

**Comment by nlewo** [comment]
Superseded by https://github.com/NixOS/nixpkgs/pull/80858

**Pull request closed without merging**
