### PR TITLE
python3Packages.sympy: 1.11.2 -> 1.12

### PR DESCRIPTION
**Pull request by ChrisPattison**
###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ChrisPattison** [comment]
The tests have been run

**Comment by collares** [comment]
Please wait a bit until I have merged the relevant Sage patches. I will do this later today. Thanks!

**Comment by collares** [comment]
Ah, apparently I did this before already :) Sage should be OK with this update, let's see.

@ofborg build sageWithDoc

**Review by collares — APPROVED** [review]
Sage is happy. I haven't run `nixpkgs-review` to ensure other dependents aren't broken, though.

**Comment by collares** [comment]
I have changed the target branch to `python-updates` because of the large number of rebuilds. It will take a bit for this PR to reach master, you can track it on https://nixpk.gs/pr-tracker.html?pr=244787.  Thanks for your contribution!

**Comment by SuperSandro2000** [comment]
Please rebase merge into python updates, thanks

**Comment by collares** [comment]
@SuperSandro2000 Noted!

**Pull request merged**
