### PR TITLE
fluxcd: 0.5.0 -> 0.5.9

### PR DESCRIPTION
**Pull request by ymatsiuk**
###### Motivation for this change
version bump, [changelog](https://github.com/fluxcd/flux2/releases/tag/v0.5.9)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ymatsiuk** [comment]
```$ nix-env -f /home/ymatsiuk/.cache/nixpkgs-review/pr-109260/nixpkgs -qaP --xml --out-path --show-trace --meta
1 package updated:
fluxcd (0.5.0 → 0.5.9)

$ nix --experimental-features nix-command build --no-link --keep-going --option build-use-sandbox relaxed -f /home/ymatsiuk/.cache/nixpkgs-review/pr-109260/build.nix

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/109260

1 package built:
fluxcd
```

**Comment by fabaff** [comment]
Result of `nixpkgs-review pr 109260` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>fluxcd</li>
  </ul>
</details>

**Review by fabaff — APPROVED** [review]
- [x] package build (see https://github.com/NixOS/nixpkgs/pull/109260#issuecomment-759361320)
- [ ] all depending packages build
- [x] executables tested on x86_64

```bash
...r-109260/results]$ ./fluxcd/bin/flux
Command line utility for assembling Kubernetes CD pipelines the GitOps way.

Usage:
  flux [command]

Examples:
  # Check prerequisites
[...]
```

Looks good to me.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109260` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>fluxcd</li>
</ul>
</details>

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109260` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>fluxcd</li>
</ul>
</details>

**Pull request merged**
