### PR TITLE
treewide: remove issue #56943 workarounds

### PR DESCRIPTION
**Pull request by Artturin**
checked with diffoscope+difflog and launching the programs

i have fixed that issue in my other gir PRs https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+author%3Aartturin+gobject-introspection+

Result of `nixpkgs-review pr 208268` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>69 packages built:</summary>
  <ul>
    <li>adl</li>
    <li>arandr</li>
    <li>bada-bib</li>
    <li>beets (beetsPackages.beets ,beetsPackages.beets-stable)</li>
    <li>beets-unstable (beetsPackages.beets-unstable)</li>
    <li>beetsPackages.alternatives</li>
    <li>beetsPackages.beets-minimal</li>
    <li>beetsPackages.copyartifacts</li>
    <li>beetsPackages.extrafiles</li>
    <li>blanket</li>
    <li>bubblemail</li>
    <li>cambalache</li>
    <li>cozy</li>
    <li>curtail</li>
    <li>devede</li>
    <li>dfeet</li>
    <li>gaphor</li>
    <li>giara</li>
    <li>gnome-feeds</li>
    <li>gnome-keysign</li>
    <li>gnome-photos</li>
    <li>gnome-secrets</li>
    <li>gnome.accerciser</li>
    <li>gnome.gnome-tweaks</li>
    <li>gpodder</li>
    <li>gtg</li>
    <li>guake</li>
    <li>hamster</li>
    <li>input-remapper</li>
    <li>kazam</li>
    <li>kupfer</li>
    <li>lutris</li>
    <li>lutris-free</li>
    <li>lutris-unwrapped</li>
    <li>mcomix</li>
    <li>meld</li>
    <li>minigalaxy</li>
    <li>mpdris2</li>
    <li>onboard</li>
    <li>pantheon.elementary-greeter</li>
    <li>pantheon.elementary-session-settings</li>
    <li>pantheon.switchboard-plug-a11y</li>
    <li>pantheon.switchboard-plug-keyboard</li>
    <li>pantheon.switchboard-with-plugs</li>
    <li>pantheon.wingpanel-applications-menu</li>
    <li>pantheon.wingpanel-with-indicators</li>
    <li>pick-colour-picker</li>
    <li>piper</li>
    <li>pitivi</li>
    <li>printrun</li>
    <li>protonvpn-gui</li>
    <li>python310Packages.dogtail</li>
    <li>python39Packages.dogtail</li>
    <li>rabbitvcs</li>
    <li>rednotebook</li>
    <li>sc-controller</li>
    <li>solfege</li>
    <li>sonata</li>
    <li>sublime-music</li>
    <li>terminator</li>
    <li>trackma</li>
    <li>trackma-curses</li>
    <li>trackma-gtk</li>
    <li>trackma-qt</li>
    <li>virt-manager</li>
    <li>wike</li>
    <li>xfce.catfish</li>
    <li>xsser</li>
    <li>zim</li>
  </ul>
</details>

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 208268` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>69 packages built:</summary>
  <ul>
    <li>adl</li>
    <li>arandr</li>
    <li>bada-bib</li>
    <li>beets (beetsPackages.beets ,beetsPackages.beets-stable)</li>
    <li>beets-unstable (beetsPackages.beets-unstable)</li>
    <li>beetsPackages.alternatives</li>
    <li>beetsPackages.beets-minimal</li>
    <li>beetsPackages.copyartifacts</li>
    <li>beetsPackages.extrafiles</li>
    <li>blanket</li>
    <li>bubblemail</li>
    <li>cambalache</li>
    <li>cozy</li>
    <li>curtail</li>
    <li>devede</li>
    <li>dfeet</li>
    <li>gaphor</li>
    <li>giara</li>
    <li>gnome-feeds</li>
    <li>gnome-keysign</li>
    <li>gnome-photos</li>
    <li>gnome-secrets</li>
    <li>gnome.accerciser</li>
    <li>gnome.gnome-tweaks</li>
    <li>gpodder</li>
    <li>gtg</li>
    <li>guake</li>
    <li>hamster</li>
    <li>input-remapper</li>
    <li>kazam</li>
    <li>kupfer</li>
    <li>lutris</li>
    <li>lutris-free</li>
    <li>lutris-unwrapped</li>
    <li>mcomix</li>
    <li>meld</li>
    <li>minigalaxy</li>
    <li>mpdris2</li>
    <li>onboard</li>
    <li>pantheon.elementary-greeter</li>
    <li>pantheon.elementary-session-settings</li>
    <li>pantheon.switchboard-plug-a11y</li>
    <li>pantheon.switchboard-plug-keyboard</li>
    <li>pantheon.switchboard-with-plugs</li>
    <li>pantheon.wingpanel-applications-menu</li>
    <li>pantheon.wingpanel-with-indicators</li>
    <li>pick-colour-picker</li>
    <li>piper</li>
    <li>pitivi</li>
    <li>printrun</li>
    <li>protonvpn-gui</li>
    <li>python310Packages.dogtail</li>
    <li>python39Packages.dogtail</li>
    <li>rabbitvcs</li>
    <li>rednotebook</li>
    <li>sc-controller</li>
    <li>solfege</li>
    <li>sonata</li>
    <li>sublime-music</li>
    <li>terminator</li>
    <li>trackma</li>
    <li>trackma-curses</li>
    <li>trackma-gtk</li>
    <li>trackma-qt</li>
    <li>virt-manager</li>
    <li>wike</li>
    <li>xfce.catfish</li>
    <li>xsser</li>
    <li>zim</li>
  </ul>
</details>

**Comment by jtojnar** [comment]
Note that some of the other setup hooks (¿was it gdk-pixbuf, or the maybe the removed `hicolor-icon-theme`?) may suffer from the same problem. But if you checked the wrappers with diffoscope and there were no differences then it is probably fine.

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/208537

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/215715

**Pull request closed without merging**
