### PR TITLE
obs-studio: fix script plugin path 

### PR DESCRIPTION
**Pull request by materusPL**
## Description of changes
Fix for https://github.com/NixOS/nixpkgs/issues/245235

After change, lua and python scripts seem to load without errors.

## Things done
Edited patch so it will also change OBS_SCRIPT_PLUGIN_PATH, both OBS_SCRIPT_PLUGIN_DESTINATION and CMAKE_INSTALL_PREFIX are absolute path while building with nix so merging them makes non existing path.

OBS_SCRIPT_PLUGIN_PATH is now  same as OBS_SCRIPT_PLUGIN_DESTINATION

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by woojiq** [comment]
Can it be merged? @materusPL, do you know any guy who can review and merge this pr?

**Comment by deviant** [comment]
Have tested this and can confirm it fixes script loading (tested with the `clock-source.lua` that comes with OBS). [`6380f7a`](https://github.com/NixOS/nixpkgs/pull/249337/commits/6380f7a45c776731c4117921ecddd594bf353538) appears to be spurious (presumably it was either included by mistake, or you were intending on adding yourself to `meta.maintainers`). If that gets fixed, I'm happy for this to get merged!

**Comment by materusPL** [comment]
I wanted to add myself to meta.maintainers but forgot to add it. 
Made commit to add myself.

**Review by deviant — APPROVED** [review]

**Comment by mindmeshlink** [comment]
Is there any reason this shouldn't be backported to 23.05 stable once it's merged?

**Comment by materusPL** [comment]
> Is there any reason this shouldn't be backported to 23.05 stable once it's merged?

On 23.05 obs-studio is in version  29.0.2. This version have a bit different cmake files than 29.1.3
So it would require backporting update to 29.1.3 or making other patch ( from quick look it seems just adding new line but still different patch)

**Pull request merged**
