### PR TITLE
nixos/network-interfaces-scripted: remove network-setup unit if unused

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by klemensn — APPROVED** [review]
While there, can you move the "# Set the default gateway" line into the `optionalString` block?

**Comment by SuperSandro2000** [comment]
Just leaving that there because I don't fully understand the code and just wanted to remove the empty script from my system.

**Comment by cmm** [comment]
This breaks deploy-rs for me (at least) because "network-local-commands.service" binds to "network-setup.service" and fails to start when the latter does not exist, this is the failure message:
```
Failed to start network-local-commands.service: Unit network-setup.service not found.
```

I also have no idea whether deploy-rs does anything funky wrt profile activation; I think it just runs the activation script?  So not sure why nobody's complained about this yet.

There are also multiple occurrences of `wantedBy`/`partOf`/`before` "network-setup.service" which do not seem to be related to the condition you formulated for "network-setup.service"'s existence.

**Comment by SuperSandro2000** [comment]
You are probably using one of these functions https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/tasks/network-interfaces-scripted.nix#L597-L604

Isn'T scripted networking required to use those?

**Comment by cmm** [comment]
I cannot really say, except to note that my network setup is totally pedestrian (`config.networking.interfaces` is an empty list, no bridges or vlans or whatever fancy).  I do use zerotierone, but its module just adds a link under `system.network.links` and I don't see it influencing anything under `config.networking`, but of course I could be missing something here.

But if I understand https://github.com/NixOS/nixpkgs/blob/68c94a2786f071f7671cf86668954cfb57123b60/nixos/modules/tasks/network-interfaces-scripted.nix#L623 correctly, the two problematic services ("network-setup" and "network-local-commands") are always defined if systemd-networkd is not enabled (which it isn't in my case, because totally pedestrian).

**Comment by SuperSandro2000** [comment]
Then we maybe need to add two more conditions if those features are used.

**Comment by cmm** [comment]
Which features and conditions do you mean?

To reiterate: this patch results in an invalid systemd service configuration when: 1. systemd-networkd is not used 2. resolvconf is not enabled 3. no default gateway is configured.  The systemd service configuration is invalid because an enabled service ("network-local-commands") bindsTo a non-existing service ("network-setup").

The simplest fix seems to be to `mkIf` both `networkSetup` and `networkLocalCommands` with the same condition?  What am I missing here?

**Comment by SuperSandro2000** [comment]
> The simplest fix seems to be to `mkIf` both `networkSetup` and `networkLocalCommands` with the same condition.

If that works please submit a PR.

**Comment by cmm** [comment]
#179163

**Pull request merged**
