### PR TITLE
Luarocks nix bump

### PR DESCRIPTION
**Pull request by teto**
###### Motivation for this change

less controversial changes I made while working on https://github.com/NixOS/nixpkgs/pull/131499
- normalize lua package names like vim plugins aka replace dot by a dash
- added plenary.nvim, an important package in the neovim ecosystem
-
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 132004` at a2a2bb32 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built successfully:</summary>
  <ul>
    <li>lua51Packages.luarocks-nix</li>
    <li>lua51Packages.plenary-nvim</li>
    <li>luarocks-nix (luaPackages.luarocks-nix)</li>
    <li>luaPackages.plenary-nvim (lua52Packages.plenary-nvim)</li>
    <li>lua53Packages.luarocks-nix</li>
    <li>lua53Packages.plenary-nvim</li>
    <li>luajitPackages.luarocks-nix</li>
    <li>luajitPackages.plenary-nvim</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/no-uri-literals.md">no-uri-literals</a>

URI literals are deprecated.
Near pkgs/development/lua-modules/generated-packages.nix:1534:14:
```
     |
1534 |     url    = mirror://luarocks/readline-2.6-0.src.rock;
     |              ^
```
</li>
    <li>warning: unused-argument

Unused argument: `pkgs`.
Near pkgs/development/lua-modules/generated-packages.nix:8:34:
```
  |
8 | { self, lib, fetchurl, fetchgit, pkgs, ... } @ args:
  |                                  ^
```
</li>
  </ul>
</details>

**Comment by toastal** [comment]
```console
building '/nix/store/axl3dqaqhwfc6gjqnh44rvwmpwj35j53-lua5.1-plenary.nvim-scm-1.drv'...
unpacking sources
unpacking source archive /nix/store/jbwlgm4fnb5kalgfhccqx60688lp86my-plenary.nvim-adf9d62
source root is plenary.nvim-adf9d62
patching sources
configuring
building
installing

cp: cannot stat 'lua/plenary/popup.lua': No such file or directory

Error: Build error: Failed installing lua/plenary/popup.lua in /nix/store/dqa8ip5nc0g7z2dxccqf0ksfx035w1yz-lua5.1-plenary.nvim-scm-1/plenary.nvim-scm-1-rocks/plenary.nvim/scm-1/lua/plenary/popup.lua: Failed copying lua/plenary/popup.lua to /nix/store/dqa8ip5nc0g7z2dxccqf0ksfx035w1yz-lua5.1-plenary.nvim-scm-1/plenary.nvim-scm-1-rocks/plenary.nvim/scm-1/lua/plenary/popup.lua
```

This related?

**Comment by teto** [comment]
I dont think so, check out https://github.com/NixOS/nixpkgs/pull/133785

**Comment by colemickens** [comment]
So is this unblocked yet, or not?

**Pull request merged**
