### PR TITLE
perl: fix errant references when cross-compiling

### PR DESCRIPTION
**Pull request by lopsided98**
###### Motivation for this change

Cross-compiled Perl ends up with references to its source tarball and build `coreutils`. 

###### Things done

The source tarball reference was a bit perplexing, but it turns out that Perl's build system uses the `src` environment variable, and writes its value into a header in the output. For native builds, some part of the config ends up of overwriting this variable, but this does not happen when cross-compiling.

The `coreutils` reference was simply an assumption that the correct binary would be in `PATH`.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @edolstra

### CODE REVIEW

**Comment by lopsided98** [comment]
I guess we need some special case for the Darwin bootstrap perl. I'm not sure what package provides `pwd` in that case.

**Comment by lopsided98** [comment]
Oh, I see https://github.com/NixOS/nixpkgs/pull/58979 ran into the same problem.

**Comment by lopsided98** [comment]
I applied the `coreutils` fix only to cross builds and added a comment explaining why this was done.

**Comment by lopsided98** [comment]
Sorry, I accidentally rebased on master...

**Review by Ericson2314 — COMMENTED** [review]
I would put the comments outside the `''...''` that way they don't affect the drv. Otherwise looks good!

**Comment by lopsided98** [comment]
I fixed the comments.

**Comment by Ericson2314** [comment]
Thank you!

**Pull request merged**
