### PR TITLE
ssm-agent: use the fixed lsb-release instead of workarounds

### PR DESCRIPTION
**Pull request by prusnak**
###### Motivation for this change

Partial fix for https://github.com/NixOS/nixpkgs/issues/66636

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by prusnak** [comment]
@GrahamcOfBorg build ssm-agent

**Comment by prusnak** [comment]
@GrahamcOfBorg test ssm-agent

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 120938` at 7432dcd0 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/1e1367c16e69e0957907244f6e31882c">ssm-agent</a></li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: unused-argument

Unused argument: `writeShellScriptBin`.
Near pkgs/applications/networking/cluster/ssm-agent/default.nix:2:3:
```
  |
2 | , writeShellScriptBin
  |   ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement.

**Comment by prusnak** [comment]
Changing to draft as this needs more testing.

**Comment by michojel** [comment]
FWIW so far the megasync looks to be failing with this change:
<details>

```
install flags: SHELL=/nix/store/68c5b0h2w2ab57sbas1b4m073ik8hlm5-bash-4.4-p23/bin/bash gsettingsschemadir=/nix/store/z1lsymqa84l03x1app45gvd93zn2xnd9-megasync-4.4.0.0/share/gsettings-schemas/megasync-4.4.0.0/glib-2.0/schemas/ gsettingsschemadir=/nix/store
/z1lsymqa84l03x1app45gvd93zn2xnd9-megasync-4.4.0.0/share/gsettings-schemas/megasync-4.4.0.0/glib-2.0/schemas/ install
cd MEGASync/ && ( test -e Makefile || /nix/store/ifmn4kf92fbmdigf7pyqd602gc99hznm-qtbase-5.15.2-dev/bin/qmake -o Makefile /build/source/src/MEGASync/MEGASync.pro CONFIG+=release ) && make -f Makefile install
make[1]: Entering directory '/build/source/src/MEGASync'
/nix/store/ifmn4kf92fbmdigf7pyqd602gc99hznm-qtbase-5.15.2-dev/bin/qmake -install qinstall -exe megasync /nix/store/z1lsymqa84l03x1app45gvd93zn2xnd9-megasync-4.4.0.0/bin/megasync
strip /nix/store/z1lsymqa84l03x1app45gvd93zn2xnd9-megasync-4.4.0.0/bin/megasync
lsb_release -ds > /build/source/src/MEGASync/platform/linux/data/distro
make[1]: *** [Makefile:9375: install_distro] Error 3
make[1]: Leaving directory '/build/source/src/MEGASync'
make: *** [Makefile:59: sub-MEGASync-install_subtargets] Error 2
```

</details>

Is there something I can help with?

**Comment by prusnak** [comment]
> Is there something I can help with?

Sure, you can investigate and fix the issue :-)

**Comment by prusnak** [comment]
I am closing this. It seems that both megasync and ssm-agent have issues when distribution lsb-release is being used.

**Pull request closed without merging**
