### PR TITLE
epkowa: support Epson Perfection V330 Photo

### PR DESCRIPTION
**Pull request by bebehei**
###### Motivation for this change

This adds the iscan plugin for Epson Perfection V330 Photo scanner. It's mostly just copy & paste of another module with some changes.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

This is my first PR. I've read CONTRIBUTING.md and I guess it should fit, but I'm not sure about the rest, which is listed in the PR template.

### CODE REVIEW

**Comment by veprbl** [comment]
cc @symphorien

**Comment by matthewbauer** [comment]
@grahamcofborg eval

**Comment by symphorien** [comment]
I can't test, but looks good to me :) Thanks!

**Comment by veprbl** [comment]
@bebehei @symphorien Thank you!

**Pull request merged**
