### PR TITLE
[20.09] python3Packages.alerta: add missing dependency

### PR DESCRIPTION
**Pull request by austinbutler**
###### Motivation for this change

Backport of: https://github.com/NixOS/nixpkgs/pull/98894

ZHF: https://github.com/NixOS/nixpkgs/issues/97479
https://hydra.nixos.org/build/127654289

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by risicle** [comment]
WFM macos 10.14, linux x86_64

**Comment by risicle** [comment]
@ofborg eval

:thinking:

**Review by rnhmjoj — APPROVED** [review]
I can confirm this fixes the build on 20.09. 
ofBorg seems pretty unresponsive today, I run the eval [command](https://github.com/NixOS/ofborg) manually and it passes.

**Review by jonringer — COMMENTED** [review]
also need to backport maintainer commit

```
error: while evaluating anonymous function at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/packet-spot-eval-1/.gc-of-borg-outpaths.nix:44:12, called from undefined position:
while evaluating anonymous function at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/packet-spot-eval-1/pkgs/top-level/release-lib.nix:121:6, called from /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/packet-spot-eval-1/lib/attrsets.nix:292:43:
while evaluating 'hydraJob' at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/packet-spot-eval-1/lib/customisation.nix:171:14, called from /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/packet-spot-eval-1/pkgs/top-level/release-lib.nix:121:14:
while evaluating the attribute 'meta' at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/packet-spot-eval-1/lib/customisation.nix:176:24:
while evaluating the attribute 'maintainers' at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/packet-spot-eval-1/pkgs/development/python-modules/requests-hawk/default.nix:18:5:
undefined variable 'austinbutler' at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/packet-spot-eval-1/pkgs/development/python-modules/requests-hawk/default.nix:18:39
```

**Comment by austinbutler** [comment]
Sorry about that, pushed with all four commits now.

**Review by jonringer — APPROVED** [review]
LGTM

```
https://github.com/NixOS/nixpkgs/pull/98920
8 packages built:
python27Packages.mohawk python27Packages.requests-hawk python37Packages.alerta python37Packages.mohawk python37Packages.requests-hawk python38Packages.alerta python38Packages.mohawk python38Packages.requests-hawk
```

**Pull request merged**
