### PR TITLE
gobject-introspection: fix cross-compilation

### PR DESCRIPTION
**Pull request by ghost**
Currently pkgsCross.aarch64-multiplatform.gobject-introspection does
not build due to breakage in (a) generating the docs and (b)
generating the introspection data.

There really isn't proper support in gobject-introspection for
cross-compiles with -Dintrospection=true, just a collection of hacks
in meson_options.txt that are rumored to be useful somehow.  I  ave
not been able to find any reports of people actually getting this to
work.

Let's disable the docs  nd introspection data for cross-compiles,
since a build without docs or introspection is still very useful, and
definitely more useful than no build at all.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux cross to aarch64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Currently pkgsCross.aarch64-multiplatform.gobject-introspection does
not build due to breakage in (a) generating the docs and (b)
generating the introspection data.

There really isn't proper support in gobject-introspection for
cross-compiles with -Dintrospection=true, just a collection of hacks
in meson_options.txt that are rumored to be useful somehow.  I have
not been able to find any reports of people actually getting this to
work.

Let's disable the docs and introspection data for cross-compiles,
since a build without docs or introspection is still very useful, and
definitely more useful than no build at all.

### CODE REVIEW

**Comment by NickCao** [comment]
And, gobject-introspection is not really designed to be used in cross compilations, in short, even if it build, we can not build packages that depends on it. Then what's the point of fixing it in the first place?

**Comment by a-m-joseph** [comment]
> even if it build, we can not build packages that depends on it.

We can.  I am about to submit the patch that makes gtk3 cross-compile.

Stay tuned.  It's worth it.

**Comment by NickCao** [comment]
> > even if it build, we can not build packages that depends on it.
> 
> We can. I am about to submit the patch that makes gtk3 cross-compile.
> 
> Stay tuned. It's worth it.

Some previous work on cross compiling gtk3 is at https://github.com/NixOS/nixpkgs/pull/148618, hope it helps.

**Comment by a-m-joseph** [comment]
> We can. I am about to submit the patch that makes gtk3 cross-compile.

https://github.com/NixOS/nixpkgs/pull/166219

**Comment by a-m-joseph** [comment]
> Some previous work on cross compiling gtk3 is at #148618, hope it helps.

Ah crap, I wish I had known about that before I spent a ton of time on this.

**Comment by Artturin** [comment]
See https://github.com/NixOS/nixpkgs/pull/88222 for prior art

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/176464

**Pull request closed without merging**
