### PR TITLE
jetbrains-jdk: add JCEF support

### LINKED ISSUE #160468: JetBrains JDK does not support JCEF
### Describe the bug
The JetBrains JDK seems to be built without JCEF support.

### Steps To Reproduce
1. Run something (e.g. Intellij) with the JetBrains JDK
2. Expect JCEF to work.
3. It doesn't.

### Expected behavior
JCEF should be supported.

### Additional context
This is probably the cause of #143122, #109347 and #150579.

### Notify maintainers

@edwtjo @petabyteboy

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.7, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.0`
 - channels(niko): `""`
 - channels(root): `"android, nix-ld, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by GenericNerdyUsername**
###### Description of changes

Update the jetbrains jdk, but also add JCEF support, allowing the markdown plugin in jetbrains IDEs to work correctly.
Closes #160468 and #143122. Also updates the IDEs.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Ifropc** [comment]
Thank you for the fix! 
Can confirm it fixes mardown rendering issues in IDEA.
Would be happy to see it merged @edwtjo

**Comment by Ifropc** [comment]
After upgrading to the latest version opening project containing kotlin files make idea to be stuck on "looking up kotlin script definition..." background task @GenericNerdyUsername can you take a look please? (as alternative, I'd just rollback the sdk)

**Comment by GenericNerdyUsername** [comment]
Can you diff the logs with/without the version bump and show me the result?

**Comment by GenericNerdyUsername** [comment]
@Ifropc

**Comment by l0b0** [comment]
Does this close #150579 as well?

**Comment by niknetniko** [comment]
If I run this (using the latest NixOS unstable), I get this error when running Intellij IDEA:

image

Do I need to change something else?

**Comment by GenericNerdyUsername** [comment]
> Does this close #150579 as well?

I can view markdown files in clion with this

**Comment by GenericNerdyUsername** [comment]
> If I run this (using the latest NixOS unstable), I get this error when running Intellij IDEA:
> 
> image
> 
> Do I need to change something else?

I fixed this in [my overlay](https://gitlab.com/genericnerdyusername/jetbrains-updater/), forgot to push changes here

**Comment by GenericNerdyUsername** [comment]
Should be working now

**Review by niknetniko — APPROVED** [review]
Tested with both Intellij and Clion, both work. Very nice work!

**Comment by Ifropc** [comment]
@GenericNerdyUsername sorry for the late response, for some reason I didn't received a notification on my mail.
I had the same issue with 4c5a2e44561f4991d568d7bb7dc68d56a73a5d6c version. The one from unstable works just fine. 6f0a18633d59a73c90d29446e1f85e4f1a233e86 also works just fine.
Very strange error. Tried to clean caches, didn't really help. I got the log from the unsuccessful run if you are curious: https://paste.apache.org/u6jua
ClassCastException is what causes this behavior is my guess. 
The last IllegalStateException can be ignored, it happens when I close IDE.

<details>
  <summary>Result of about section</summary>

4c5a2e44561f4991d568d7bb7dc68d56a73a5d6c:
```
IntelliJ IDEA 2022.2.3 (Community Edition)
Build #IC-222.4345.14, built on October 4, 2022
Runtime version: 17.0.5+8-nixos amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.0.11
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 20
Non-Bundled Plugins:
    wu.seal.tool.jsontokotlin (3.7.4)
    org.jetbrains.kotlin (222-1.7.21-release-272-IJ4167.29)
    com.facebook.ktfmt_idea_plugin (1.1.0.42)
    IdeaVIM (1.11.1)
    com.godwin.kdocer (1.6)

Kotlin: 222-1.7.21-release-272-IJ4167.29
Current Desktop: sway
```
And unstable:
```
IntelliJ IDEA 2022.2.3 (Community Edition)
Build #IC-222.4345.14, built on October 4, 2022
Runtime version: 17.0.5+8-nixos amd64
VM: OpenJDK 64-Bit Server VM by N/A
Linux 6.0.11
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 20
Non-Bundled Plugins:
    wu.seal.tool.jsontokotlin (3.7.4)
    org.jetbrains.kotlin (222-1.7.21-release-272-IJ4167.29)
    com.facebook.ktfmt_idea_plugin (1.1.0.42)
    IdeaVIM (1.11.1)
    com.godwin.kdocer (1.6)

Kotlin: 222-1.7.21-release-272-IJ4167.29
Current Desktop: sway
```

</details>

**Comment by GenericNerdyUsername** [comment]
@Ifropc what happens if you use the latest IntelliJ?

**Comment by Ifropc** [comment]
@GenericNerdyUsername Do you mean from unstable? It works just fine

**Comment by GenericNerdyUsername** [comment]
I mean using this jdk with intellij 2022.3.1

**Comment by Ifropc** [comment]
It will probably work, but version in master is 222, so if PR is merged as is, it will break things for somebody else too (potentially) 
I would say it's a good idea to either rollback SDK or upgrade IDEA in this PR to 223

**Comment by GenericNerdyUsername** [comment]
@Ifropc do things work now?

**Comment by Ifropc** [comment]
@GenericNerdyUsername yes, everything is working now, thank you very much for your patience!

**Comment by K900** [comment]
Can confirm PyCharm Professional builds and runs fine with this, including the web stuff. I'm inclined to merge this unless someone objects.

**Comment by tlipinski** [comment]
I've just fixed Gitlab Merge Request plugin with it - thanks!:)

**Comment by GenericNerdyUsername** [comment]
Done

**Comment by l0b0** [comment]
Fantastic work, all! Is anyone working on porting this to 22.11?

**Comment by GenericNerdyUsername** [comment]
Cherry picking this commit on top of the `22.11` branch lets it compile if you apply this patch
```diff
diff --git a/pkgs/development/compilers/jetbrains-jdk/default.nix b/pkgs/development/compilers/jetbrains-jdk/default.nix
index 3d1e8a30434..ebeb218c1b5 100644
--- a/pkgs/development/compilers/jetbrains-jdk/default.nix
+++ b/pkgs/development/compilers/jetbrains-jdk/default.nix
@@ -29,8 +29,8 @@
 
 openjdk17.overrideAttrs (oldAttrs: rec {
   pname = "jetbrains-jdk-jcef";
-  javaVersion = "17.0.5";
-  build = "653.14";
+  javaVersion = "17.0.3";
+  build = "653";
   # To get the new tag:
   # git clone https://github.com/jetbrains/jetbrainsruntime
   # cd jetbrainsruntime
@@ -88,7 +88,7 @@ openjdk17.overrideAttrs (oldAttrs: rec {
     runHook preInstall
 
     rm -rf build/linux-x86_64-server-${buildType}/images/jdk
-    mv build/linux-x86_64-server-${buildType}/images/jbrsdk${jcefSuffix}-${javaVersion}-linux-x64${debugSuffix}-b${build} build/linux-x86_64-server-${buildType}/images/jdk
+    mv build/linux-x86_64-server-${buildType}/images/jbrsdk${jcefSuffix}-${javaVersion}-x64${debugSuffix}-b${build} build/linux-x86_64-server-${buildType}/images/jdk
   '' + oldAttrs.installPhase + "runHook postInstall";
 
   postInstall = ''
```
All that should be needed is testing and making a pr.

**Pull request merged**
