### PR TITLE
ansible-lint: 4.2.0 -> 4.3.5

### PR DESCRIPTION
**Pull request by SuperSandro2000**
###### Motivation for this change

Update failed in https://r.ryantm.com/log/2020-10-17.log.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Result of `nixpkgs-review pr 101021` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 package built:</summary>

  - ansible-lint (python38Packages.ansible-lint)
  - python37Packages.ansible-lint
</details>

**Comment by sengaya** [comment]
Many thanks for the PR. Unfortunately a build on MacOS fails at the moment for me. For some reason the dependency `cairo` does not build. Seems unrelated to your PR though. I need to dig deeper.

For the record, this is the error:
```
./cairo-mutex-impl-private.h:262:3: error: "XXX: No mutex implementation found.  Cairo will not work with multiple threads.  Define CAIRO_NO_MUTEX to 1 to acknowledge and accept this limitation and compile cairo without thread-safety support."
```

**Comment by SuperSandro2000** [comment]
> No mutex implementation found

Maybe this helps you debugging this issue https://gitlab.freedesktop.org/cairo/cairo/-/issues/121

**Review by jonringer — APPROVED** [review]
LGTM

Result of nixpkgs-review pr 101021 [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>2 packages built:</summary>  <ul>    <li>ansible-lint (python38Packages.ansible-lint)</li>    <li>python37Packages.ansible-lint</li>  </ul></details>

**Pull request merged**
