### PR TITLE
pwvucontrol 0.3.1 -> 0.4.1

### PR DESCRIPTION
**Pull request by calebstewart**
## Description of changes
In certain cases, v0.3.1 would crash immediately upon opening. See [saivert/pwvucontrol#7](https://github.com/saivert/pwvucontrol/issues/7).

There doesn't appear to be a published changelog for this package, but I can link to the diff of `0.3.1` and `0.4.1` [here](https://github.com/saivert/pwvucontrol/compare/0.3.1...0.4.1).

This is my first PR to `nixpkgs`, and I'm pretty new to NixOS in general. I read through contributing guidelines, but I'm still not perfectly confident. Happy to make any adjustments necessary. :)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by calebstewart** [comment]
Oops, I forgot to mention the maintainer. @figsoda :wave:

**Comment by JohnRTitor** [comment]
Result of `nixpkgs-review pr 315809` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>pwvucontrol</li>
  </ul>
</details>

**Comment by Scrumplex** [comment]
Result of `nixpkgs-review pr 315809` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>pwvucontrol</li>
  </ul>
</details>

**Review by JohnRTitor — APPROVED** [review]
LGTM

**Review by Scrumplex — APPROVED** [review]
Previous version didn't work on my machine. This one does

**Review by JohnRTitor — COMMENTED** [review]
It successfully builds, but I see this in build log:
```log
pwvucontrol> Program desktop-file-validate found: YES (/nix/store/rmk31w7i6ijps82v2zdy6jp2hpqz65x4-desktop-file-utils-0.27/bin/desktop-file-validate)
pwvucontrol> Program appstream-util found: NO
```

So perhaps [add](https://github.com/search?q=repo%3ANixOS%2Fnixpkgs%20appstream-util&type=code) `appstream-glib` to native build inputs for appstream-util?

**Pull request merged**
