### PR TITLE
atom*: drop

### PR DESCRIPTION
**Pull request by SuperSandro2000**
## Description of changes

https://atom.io redirects to https://github.blog/2022-06-08-sunsetting-atom/ which explicitly states ``No more security updates`` and the repo is archived since last November. This means atom is probably vulnerable to the recent libwebp and libvpx CVEs and probably more.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by MikaelFangel** [comment]
Ref to: #254798

**Comment by delroth** [comment]
ofborg-eval is unhappy due to various dependencies on atomEnv in nixpkgs.

**Comment by SuperSandro2000** [comment]
I just checked a few atomEnv usages and it mostly seems like a legacy artifact before electron was really a thing and is in some cases not required at all.

**Comment by SuperSandro2000** [comment]
I started all touched applications and they started up properly but I never went past login screens.

**Comment by pbsds** [comment]
It would be nice to add a notice about Pulsar being the new Atom fork ;)

**Comment by SuperSandro2000** [comment]
We can write that into the error message but I don't think we can just alias it without any user action required.

**Comment by delroth** [comment]
Please re-order the commits to put the atomEnv removal at the end (after its usages were removed). Otherwise LGTM.

**Review by pbsds — APPROVED** [review]

**Review by delroth — APPROVED** [review]

**Pull request merged**
