### PR TITLE
jetbrains-clion/rider-eap: init at 2023.1-EAP7

### PR DESCRIPTION
**Pull request by raymens**
###### Description of changes

Init some of the jetbrains editors with their corresponding EAP (early access program) version.
For now I've added and run:
- Clion
- Rider

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by GabrielDougherty** [comment]
I think this should be split into two PRs - one for each package.

**Comment by GabrielDougherty** [comment]
Result of `nixpkgs-review pr 219902` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>jetbrains.clion-eap</li>
    <li>jetbrains.rider-eap</li>
  </ul>
</details>

**Comment by raymens** [comment]
> I think this should be split into two PRs - one for each package.
> 
> see https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#submitting-changes

Will do :)

**Comment by kouyk** [comment]
It is often difficult to keep the release channel updated, eap channel with its frequent update might be even more challenging, is it better for the user to create an overlay and override the `version.json`? My worry is that if one chooses to be using EAP they would want to stay on the bleeding edge, and it is likely better for them to maintain an overlay and keep the version updated. Since JetBrains IDEs are non-free, there's no build cache to utilise anyway.

I do imagine the original intention of abstracting out `version.json` is to make it possible to change all the channels entirely.

**Comment by raymens** [comment]
> It is often difficult to keep the release channel updated, eap channel with its frequent update might be even more challenging, is it better for the user to create an overlay and override the `version.json`? My worry is that if one chooses to be using EAP they would want to stay on the bleeding edge, and it is likely better for them to maintain an overlay and keep the version updated. Since JetBrains IDEs are non-free, there's no build cache to utilise anyway.
> 
> I do imagine the original intention of abstracting out `version.json` is to make it possible to change all the channels entirely.

Thanks for your input, keeping it up to date is a valid concern I share. I will await other input before continuing.

**Comment by raymens** [comment]
@edwtjo @mic92 any opinion/conclusion on this?

**Comment by AnatolyPopov** [comment]
> It is often difficult to keep the release channel updated, eap channel with its frequent update might be even more challenging, is it better for the user to create an overlay and override the version.json? My worry is that if one chooses to be using EAP they would want to stay on the bleeding edge, and it is likely better for them to maintain an overlay and keep the version updated. Since JetBrains IDEs are non-free, there's no build cache to utilise anyway.
>
>I do imagine the original intention of abstracting out `version.json` is to make it possible to change all the channels entirely.
This is exactly the reason why I was trying to package JetBrains Toolbox instead for a long time. Keeping EAP up to date will be a challenge and with Toolbox it's a lot easier than constantly updating `version.json`, so I would suggest using Toolbox if possible if you need bleeding edge version. However not all the IDEs working correctly with Toolbox also.

**Comment by wegank** [comment]
Merge conflict, please rebase.

**Pull request closed without merging**
