### PR TITLE
simp_le: 0.6.1 -> 0.8.0

### PR DESCRIPTION
**Pull request by makefu**
###### Motivation for this change

according to the changelog, the release 0.6.2 of simp_le will be future-proof by not hard-coding the TOS checksum.
To update simp_le, the latest version is required which is bumped by this PR. Additionally josepy is added which is required for simp_le and certbot.
related: #31944 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by makefu** [comment]
@GrahamcOfBorg build simp_le certbot

**Comment by makefu** [comment]
certbot fails on darwitn with
```
ERROR: test_no_persisted_empty (simp_le.ExternalIOPluginTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/5myi8sjqdhii0wsrcrjaw1pkzc14hmnj-simp_le-client-0.8.0/lib/python2.7/site-packages/simp_le.py", line 886, in test_no_persisted_empty
    self.assertEqual(IOPlugin.EMPTY_DATA, self.plugin.load())
  File "/nix/store/5myi8sjqdhii0wsrcrjaw1pkzc14hmnj-simp_le-client-0.8.0/lib/python2.7/site-packages/simp_le.py", line 654, in load
    pems = list(self.split_pems(self.get_output_or_fail('load')))
  File "/nix/store/5myi8sjqdhii0wsrcrjaw1pkzc14hmnj-simp_le-client-0.8.0/lib/python2.7/site-packages/simp_le.py", line 629, in get_output_or_fail
    raise Error('Failed to execute external script: {0}'.format(error))
Error: Failed to execute external script: [Errno 8] Exec format error
```
not sure how to fix it. should i disable this test for darwin? everything else looks fine

**Comment by dotlambda** [comment]
I noticed some `/bin/sh` stuff in `simp_le.py`. No idea if that's the reason but it should be fixed anyway.

**Comment by wmertens** [comment]
It would be nice to backport this to stable too

**Comment by Mic92** [comment]
Currently I a don't have time to do this, but maybe someone else.

**Comment by dotlambda** [comment]
This breaks the `acme` module:
@GrahamcOfBorg test acme

**Comment by wmertens** [comment]
The reason seems to be `simp_le: error: unrecognized arguments: --tos_sha256 cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b`

It doesn't use that argument any more, so the test needs to be adjusted.

**Comment by makefu** [comment]
@wmertens exactly, with 0.6.2 the TOS shasum will not be hardcoded anymore. See changelog 0.7.0 on https://pypi.python.org/pypi/simp-le-client . the client implicitly agrees with the TOS if one is is presented

**Pull request merged**
