### PR TITLE
canon-cups-ufr2: fix color printing issues

### LINKED ISSUE #310013: canon-cups-ufr2 5.70 prints blank pages for Canon MF743CDW
### Describe the bug
When trying to print using the canon-cups-ufr2 print driver version 5.70, no pages are output, and the printer job log (printer web UI, not CUPS) shows the job succeeding, but with zero pages.  I believe it's due to a segfault in cnrsdrvufr2, the binary which converts to the ufr2 language the printer understands

### Steps To Reproduce
1. Install canon-cups-ufr2
2. Add network printer to CUPS, using the manufacturer Canon, and model MF743CDW UFR II
3. Try to print anything

### Expected behavior
Print output

### Screenshots
N/A

### Additional context
As a workaround, I enabled IPP and Mopria on the printer web interface, and added the printer to CUPS at the url ipp://<my_printer_address>/ipp/print and selected the driver Canon->IPP Everywhere, which allows me to print with less functionality (the two-sided printing doesn't seem to be supported).

I also tried updating the driver to 5.90, but that version has the same problem.

### Notify maintainers
@lluchs 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run 'nix-info -m'
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.25, NixOS, 24.05 (Uakari), 24.05.20240406.ff0dbd9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/etc/nixpath/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by dan-smetana**
This commit resolves https://github.com/NixOS/nixpkgs/issues/310013 by adding the required `libjpeg` and `libgcrypt` libraries. It sets `dontPatchELF = true` to prevent `patchelf --shrink-rpath` from removing these libraries from the `RPATH`. The driver binaries use `dlopen` to load the libraries at runtime instead of specifying them in `DT_NEEDED`, which causes `dlopen` to be unable to find them when `patchelf --shrink-rpath` is called.

In addition, this commit also updates the driver to its latest version.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by lluchs — CHANGES_REQUESTED** [review]
Thanks for the PR! I can confirm that the driver still builds and works for my setup (aarch64, iR1022). A couple small things however:

- My PR updating to 5.90 was merged in the meantime, so you'll have to update your commit.
- Please don't ignore all the extra stuff in the PR template and fill out what you did.
- Your commit message doesn't match the required form (last checkbox in the PR template). Split your changes in two commits, one with the package update (canon-cups-ufr2: 5.90 -> 6.00) and another with the fix.

**Comment by lluchs** [comment]
Thanks for the update. Your commit messages still don't match the required format, see here: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions

The first commit should read "canon-cups-ufr2: 5.90 -> 6.00", and the second also need to start with "canon-cups-ufr2: ".

**Comment by feinerer** [comment]
I can confirm that this fixes printing PDFs on a Canon imageRUNNER ADVANCE DX C5840 (which was broken before).

**Comment by dan-smetana** [comment]
I renamed the commits as requested.

**Comment by lluchs** [comment]
All looking good now, except that the package was migrated to pkgs/by-name in the meantime: https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/ca/canon-cups-ufr2/package.nix

I'm sorry that this has been dragging on for so long, but you'll have to rebase one more time :(

**Review by lluchs — APPROVED** [review]

**Comment by dan-smetana** [comment]
rebased

**Review by lluchs — APPROVED** [review]

**Pull request merged**
