### PR TITLE
proggyfonts: dead link fixed

### PR DESCRIPTION
**Pull request by volth**
- [x] dead link fixed
- [x] make the font derivations fixed-output (https://github.com/NixOS/nixpkgs/issues/27754)

### CODE REVIEW

**Comment by fpletz** [comment]
Seems the hash is wrong here:

```output path ‘/nix/store/na81qxc4ss6zhklwqlm749wnkng22z3x-proggyfonts-0.1’ has r:sha256 hash ‘19m6h9hvdb2p99yrh3pk8gagb8y4w6sd6k4k0ycxz6wj4q8ccggs’ when ‘06jsf3rw6q4l1jrw1161h4vxa1xbvpry5x12d8sh5g7hjk88p77g’ was expected```

**Comment by volth** [comment]
@fpletz could you please send me your closure?

**Comment by volth** [comment]
```gzip``` might bring some non-determinism here. But it hardly can be a timestamp in the header.

**Comment by volth** [comment]
superseded with #28164

**Pull request closed without merging**
