### PR TITLE
calibre: bugfix: add markdown to inputs

### LINKED ISSUE #72724: calibre: will crash if markdown is configured in custom column
**Describe the bug**
calibre offers the ability to create custom columns and one of the options is:
`Interpret this column as: Plain text formatted using markdown`

If this option is used, the current version of calibre will crash as it lacks python-markdown in its environment.

```
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "/nix/store/wzyg72rsmxblk4wazrw6ryl3hng7p5kl-calibre-3.48.0/lib/calibre/calibre/gui2/book_details.py", line 896, in show_data
    self.book_info.show_data(data)
  File "/nix/store/wzyg72rsmxblk4wazrw6ryl3hng7p5kl-calibre-3.48.0/lib/calibre/calibre/gui2/book_details.py", line 638, in show_data
    html = render_html(mi, css(), self.vertical, self.parent())
  File "/nix/store/wzyg72rsmxblk4wazrw6ryl3hng7p5kl-calibre-3.48.0/lib/calibre/calibre/gui2/book_details.py", line 110, in render_html
    use_roman_numbers=config['use_roman_numerals_for_series_number'], pref_name=pref_name)
  File "/nix/store/wzyg72rsmxblk4wazrw6ryl3hng7p5kl-calibre-3.48.0/lib/calibre/calibre/gui2/book_details.py", line 192, in render_data
    rating_font=rating_font(), default_author_link=default_author_link())
  File "/nix/store/wzyg72rsmxblk4wazrw6ryl3hng7p5kl-calibre-3.48.0/lib/calibre/calibre/ebooks/metadata/book/render.py", line 126, in mi_to_html
    val = markdown(val)
  File "/nix/store/wzyg72rsmxblk4wazrw6ryl3hng7p5kl-calibre-3.48.0/lib/calibre/calibre/library/comments.py", line 138, in markdown
    from calibre.ebooks.markdown import Markdown
  File "/nix/store/wzyg72rsmxblk4wazrw6ryl3hng7p5kl-calibre-3.48.0/lib/calibre/calibre/startup.py", line 69, in load_module
    return import_module(fullname[len('calibre.ebooks.'):])
  File "/nix/store/bzf8x5kpv3x4qi09xq2grnvccakvy7gz-python-2.7.17/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named markdown
[1]    15851 abort (core dumped)  calibre
```

**To Reproduce**
1. Have custom formatted column configured in calibre
2. start calibre
3. crash, see above Traceback

**Expected behavior**
No crash, including working markdown formatting in the custom column

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.81, NixOS, 20.03pre199897.471869c9185 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(benny): `""`
 - channels(root): `"nixos-20.03pre199897.471869c9185"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
@domenkozar @pSub @AndersonTorres

### PR DESCRIPTION
**Pull request by bennyandresen**
fixes #72724

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @domenkozar @pSub @AndersonTorres

### CODE REVIEW

**Review by worldofpeace — APPROVED** [review]
LGTM, builds. Trace looks like it needs it.

**Comment by worldofpeace** [comment]
Not sure if this needs a backport on 19.09.

One could run the executable off of that channel like
```
nix run -f channel:nixos-19.09 calibre -c calibre
```

and see if markdown things are working.

**Comment by bandresen** [comment]
> Not sure if this needs a backport on 19.09.
> 
> One could run the executable off of that channel like
> 
> ```
> nix run -f channel:nixos-19.09 calibre -c calibre
> ```
> 
> and see if markdown things are working.

@worldofpeace a backport to 19.09 is needed.

this fails:
```
nix run -f channel:nixos-19.09 calibre -c calibre
```

this works:
```
nix run -I ~/Projects/NixOS/ nixpkgs.calibre -c calibre
```

**Comment by worldofpeace** [comment]
> > Not sure if this needs a backport on 19.09.
> > One could run the executable off of that channel like
> > ```
> > nix run -f channel:nixos-19.09 calibre -c calibre
> > ```
> > 
> > 
> > and see if markdown things are working.
> 
> @worldofpeace a backport to 19.09 is needed.
> 
> this fails:
> 
> ```
> nix run -f channel:nixos-19.09 calibre -c calibre
> ```
> 
> this works:
> 
> ```
> nix run -I ~/Projects/NixOS/ nixpkgs.calibre -c calibre
> ```

Thanks for checking. I've backported it in 6c2f097e92fc37fdb7a82564353658b45fc97945.

**Pull request merged**
