### PR TITLE
oh-my-zsh: 2021-03-01 → 2021-03-08

### PR DESCRIPTION
**Pull request by NeQuissimus**
###### Motivation for this change
Update

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by r-rmcgibbo** [comment]
Result of `nixpkgs-review pr 115429` at 711e0341 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li><a href="https://gist.github.com/528255f4a9f76203433636e5e4dbe2c2">oh-my-zsh</a></li></li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/shells/zsh/oh-my-zsh/default.nix:19:3:
```
   |
19 |   installPhase = ''
   |   ^
```
</li>
  </ul>
</details>

**Review by scolobb — APPROVED** [review]
Thank you @NeQuissimus !

**Comment by scolobb** [comment]
In fact, I don't use oh-my-zsh almost at all any more, so it's probably rather useless to have ofborg request my review and therefore prevent you from my modifying this package directly.

Feel free to remove me from the list of maintainers if it is helpful.

To make things very clear: I am not trying to eschew my maintainer duties and I will continue reviewing contributions to this package as long as necessary.

**Review by scolobb — APPROVED** [review]

**Comment by NeQuissimus** [comment]
@scolobb Feel free to make a separate PR for that. I'd like to keep the version update and the maintainer list separate PRs so I don't get all confused :)

**Pull request merged**
