### PR TITLE
 release-notes/18-09: add licenses marked as unfree 

### PR DESCRIPTION
**Pull request by Ekleog**
###### Motivation for this change

Adds missing backwards-incompatible change in the release notes. Needs backport to 18.09 for display on nixos.org.

Docs built locally and verified.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by samueldr** [comment]
Not sure if this is a dealbreaker, but I would like to see better descriptive names in the list, in addition to our identifiers. That is, "Microsoft Research License Agreement (`msrla`)" instead of the stand-alone identifiers.

**Comment by Ekleog** [comment]
Fixed by adding the full names taken from `lib/licenses.nix` :)

**Comment by grahamc** [comment]
@Ekleog can you open a backport PR? use `git cherry-pick -x`

**Comment by Ekleog** [comment]
@grahamc Done :) https://github.com/NixOS/nixpkgs/pull/48468

**Pull request merged**
