### PR TITLE
voms: init at 2021-05-04, xrootd: add voms support

### PR DESCRIPTION
**Pull request by ShamrockLee**
###### Motivation for this change
*   Package VOMS, the authentication framework of CERN GRID, into Nixpkgs.
*   Add VOMS support to XRootD, a network-based data storage/access framework
*   ~~Add XRootD support to ROOT, the data analysis framework commonly used in the field of High Energy Physics.
    This way, we can (finally) open URLs prefixed with `root://` using ROOT on LXPLUS and CERN GRID! (Not tested yet.)~~
    Due to #169677, the package `xrootd` is not functioning. It is unsuitable to add it to ROOT before the issue is solved or a workaround is found.

###### Status
*   All build successfully.
*   ~~Need to test on LXPLUS and HTCondor is needed to see if ROOT built by us can now accepts URLs with `root` schema.~~
*   ~~This PR will be ready to merge after these tests.~~
*   `gsoap`, a required dependency of `voms`, is currently set to build only on Linux. ~~I'm trying to loosen it and let it build by OfBorg, since MacPorts does have it packed.
*   ~~Should it fails to work on Mac, I'll modify the xrootd Nix expression to inject voms where gsoap are able to build.~~ Voms is now injected on Linux only.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`) (More tests need to be done on LXPLUS.)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ShamrockLee** [comment]
Try to loosen the platform limit of `gsoap` and let it build on Mac, since MacPorts have it packed in their repo.

https://github.com/macports/macports-ports/blob/master/security/voms/Portfile

**Comment by veprbl** [comment]
Result of `nixpkgs-review pr 161732` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>python310Packages.hepmc3</li>
  </ul>
</details>
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>hepmc3</li>
    <li>python39Packages.hepmc3</li>
    <li>root</li>
    <li>yoda-with-root</li>
  </ul>
</details>

**Comment by ShamrockLee** [comment]
The LXPLUS test result for `root://` input isn't positive.

```
Error in <TNetXNGFile::Open>: [FATAL] Auth failed: Could not load authentication handler.
terminate called after throwing an instance of 'std::runtime_error'
  what():  GetBranchNames: error in opening the tree tree/treeMaker
```

**Comment by ShamrockLee** [comment]
Update: The error comes from `xrootd`, and can be reproduced by running `xrdcp -vd 3` against a `root://` URL on LXPLUS.

It complains in the debug message that `libXrdSec-5.so` is missing, whereas the outpath of `xrootd.out` is already presented.

**Comment by veprbl** [comment]
@GrahamcOfBorg build root

**Review by veprbl — APPROVED** [review]

**Pull request merged**
