### PR TITLE
flow: 0.28.0 -> 0.30.0

### PR DESCRIPTION
**Pull request by Profpatsch**
- [x] builds

### CODE REVIEW

**Comment by FRidh** [comment]
Please use the template; it's there for a reason.

**Comment by FRidh** [comment]
cc maintainers @puffnfresh @globin

**Comment by Profpatsch** [comment]
@FRidh Well, I could leave it as is. What more is there to say. I updated the version number and tested if it builds. It does.

**Comment by despairblue** [comment]
Weird. Shouldn't github show a conflict since it is already updated? 

https://github.com/NixOS/nixpkgs/pull/17613

Or am I missing something. Maybe this PR does not go to master. The mobile interface is kind of weird. :confused:

**Comment by FRidh** [comment]
@despairblue you're right, strange.

**Pull request closed without merging**
