### PR TITLE
certificate-ripper: init at 2.2.0

### LINKED ISSUE #274263: Package request: certificate-ripper
## Project Description

A CLI tool to extract server certificates.

## Metadata

* Homepage: https://github.com/Hakky54/certificate-ripper
* Source: https://github.com/Hakky54/certificate-ripper
* License: Apache License 2.0
* Platforms: Linux, macOS, Windows

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by TomaSajt**
## Description of changes

Closes https://github.com/NixOS/nixpkgs/issues/274263

This PR adds 1 package: `certificate-ripper` with 1 executable: `crip`

I added a patch so that makes the final store hash is deterministic (the timestamp is fixed to the lowest accepted value now) and also locks the default maven plugin versions.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Hakky54** [comment]
@ofborg and @TomaSajt Certificate ripper has also binaries for arm Linux and also binaries for Mac. Should those be included?

**Comment by TomaSajt** [comment]
> @TomaSajt Certificate ripper has also binaries for arm Linux and also binaries for Mac. Should those be included?

I listed linux and darwin (Mac) as supported platforms in `meta.platforms`, I just haven't been able to test them, as I do not have access to anything other than x86_64-linux.

**Comment by Hakky54** [comment]
I have all those machines available locally and I am able to help with testing if needed/wanted.

**Comment by TomaSajt** [comment]
Though it looks like OfBorg (the auto build system) got an error on darwin
https://logs.ofborg.org/?key=nixos/nixpkgs.276299&attempt_id=f7a81de4-d2f5-45e2-a632-e57c6d265482

Some tests are maybe trying to create directories in places where they dont have permission

**Comment by TomaSajt** [comment]
I found that it puts the files into a directory inside the home directory, so maybe I can just create a new fake $HOME directory (I have done this before in other packages). I'll try that once I get home later today.

**Comment by TomaSajt** [comment]
@ofborg build certificate-ripper

**Comment by TomaSajt** [comment]
Okay, I added a patch for the temporary directory. It turns out you can't just override the `HOME` environment variable to trick `System.getProperty("user.home")`

**Comment by TomaSajt** [comment]
@ofborg build certificate-ripper

**Comment by TomaSajt** [comment]
It seems like the tests are running fine on darwin as well, and it also seems to compile fine.

@Hakky54 could you please check if the darwin build(s) also run fine?

**Comment by Hakky54** [comment]
All the builds look fine to me and nice to see you find a way to adjust the test path directory..

By the way I notcied in the package.nix file you are building the project, to create a jar file which you in return use to create a wrapper. However I am not able to understand why you are doing that, maybe I am just not yet that familar with the nix package build scripts. But why not just use the native executables which are available in the release section of the projects itself? See here: https://github.com/Hakky54/certificate-ripper/releases/tag/2.2.0

I am just curious and want to understand how the nix packages are being build 😄

**Comment by TomaSajt** [comment]
> By the way I notcied in the package.nix file you are building the project, to create a jar file which you in return use to create a wrapper. However I am not able to understand why you are doing that, maybe I am just not yet that familar with the nix package build scripts. But why not just use the native executables which are available in the release section of the projects itself? See here: https://github.com/Hakky54/certificate-ripper/releases/tag/2.2.0 In that way you don't need java, maven or the jar wrapper.

Packaging prebuilt binaries is a thing one should, if possible, avoid on nixpkgs. This allows us to more properly manage dependencies, run unit tests, and there might also be an issue of transparency when using prebuilt stuff.

How does your prebuilt executable not need java? Does it bundle the JRE inside the executable?

If that's the case that would mean that you'll have two times the used storage, if you already have another java application installed.

**Comment by Hakky54** [comment]
>Packaging prebuilt binaries is a thing one should, if possible, avoid on nixpkgs. This allows us to more properly manage dependencies, run unit tests, and there might also be an issue of transparency when using prebuilt stuff.

Ah, I see. Yes I understand it now.

> How does your prebuilt executable not need java? Does it bundle the JRE inside the executable?

I use GraalVM, which is an advanced JDK with Native Image compilation. So basically point my JAVA_HOME path to GraalVM  directory and run the command below. So it does not bundle the JRE. It populates all of the java statements and compiles it to machine code, so there is no need for a JRE. The startup time is faster, also execution time...

So I run the following command and it will generate the prebuilt executables.
```
mvn clean install -Pnative-image
```

See also this script which I use to create the prebuilt executables: https://github.com/Hakky54/certificate-ripper/blob/master/script/build-native-executable-for-linux-amd64.sh Do you think it would be usefull for you?

**Comment by TomaSajt** [comment]
Oh wow, looked up what the native image uses, it's actually native code, huh.
I might try to compile it into that instead.

**Comment by TomaSajt** [comment]
@ofborg build certificate-ripper

**Comment by TomaSajt** [comment]
I have managed to get graalvm working, though in a bit of a roundabout way. I first compile to a .jar file, then run the `buildGraalvmNativeImage` builder provided by Nixpkgs. There are not many packages that use `graalvm` and those that do actually use prebuilt `.jar` files for the job. This is probably why the builder only works with jar files. I could actually use the maven plugin, but `buildGraalvmNativeImage` has a lot of workarounds ([source](https://github.com/NixOS/nixpkgs/blob/62dbffc2d7afc8f92bdbd861ddeb39e19fe39b2f/pkgs/build-support/build-graalvm-native-image/default.nix)) which I didn't want to reimplement.

**Comment by Hakky54** [comment]
Awesome, it looks good to me. I think this is much better then using the jar wrapper as it will be really fast when being executed. However the only difference compared to my configuration is the missing native build arts, see below:
```
-H:Name=crip
```

Let's give it a shot. If it works you can share the executables with me so I can run it on every operating system if needed.

**Comment by TomaSajt** [comment]
> Awesome, it looks good to me. I think this is much better then using the jar wrapper as it will be really fast when being executed. However the only difference compared to my configuration is the missing native build arts, see below:
> 
> ```
> -H:Name=crip
> ```

`-H:Name=crip` is [done by the builder script](https://github.com/NixOS/nixpkgs/blob/62dbffc2d7afc8f92bdbd861ddeb39e19fe39b2f/pkgs/build-support/build-graalvm-native-image/default.nix#L16)

> Let's give it a shot. If it works you can share the executables with me so I can run it on every operating system if needed.

I don't think I can do that, actually, or if I did that, it wouldn't really work properly (though not 100% sure). This whole nix thing is about using and linking everything from `/nix/store`, so I don't really know what would happen if it was run on a non Nix-enabled system.
Also, only OfBorg can build for darwin, not me, and I don't think I can copy files generated by it.

Just the fact that it compiles properly is a pretty good sign it will work properly. For `x86_64-linux` it works fine.

If people encounter some issues with other platforms, they can probably just open an issue and I'll try to fix them.

**Comment by Hakky54** [comment]
Hi @adisbladis I saw you reviewed a different PR which was recently created https://github.com/NixOS/nixpkgs/pull/278201
Any idea who can review this PR?

**Comment by pbsds** [comment]
Result of `nixpkgs-review pr 276299` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>certificate-ripper</li>
  </ul>
</details>

Runs fine and LGTM, thanks!

**Comment by Hakky54** [comment]
Hi mate, sorry that I forgot you. Not quite sure how I missed it as we had a conversation here. I added you to the release note. Really nice to see you following the updates actively ♥️

**Comment by TomaSajt** [comment]
I'm periodically checking the Repology site to see if the packages which I'm maintaining recieved any new updates.

**Comment by Hakky54** [comment]
Amazing you already created a new pr to update the package to the latest version. You are fast. I will tag you in every release note then you will get notified, might be easier then checking periodically, WDYT?

**Comment by pbsds** [comment]
> I'm periodically checking the Repology site to see if the packages which I'm maintaining recieved any new updates.

Repology supports RSS ;)

**Comment by TomaSajt** [comment]
> I will tag you in every release note then you will get notified, might be easier then checking periodically, WDYT?

It would be easier for me to just click on the "Watch" button above the repo and choose the option to get notified upon a new release.

**Comment by TomaSajt** [comment]
> Repology supports RSS ;)

Never used it before, will look into it.

**Pull request merged**
