### PR TITLE
sqldeveloper: 4.1.1 -> 17.2.0

### PR DESCRIPTION
**Pull request by timokau**
###### Motivation for this change

When I installed sqldeveloper, I noticed that it is very much out of date.

What I'm unsure about: The website we point to for the manual download doesn't directly allow to download older versions. It is possible to manually replace the version of the file in the download link they give you though. Does anybody have experience with this? Would it be allowed to give a direkt download link, thereby probably bypassing the necessity to accept the license first? How else could this be solved?

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by orivej** [comment]
See the use of `requireFile` in nixpkgs.

**Comment by Eisfreak7** [comment]
What am I supposed to look for?

**Comment by orivej** [comment]
When we are not allowed to redistribute files or download them automatically, we use `requireFile` to ask the user to download the file from the original source.

**Comment by Eisfreak7** [comment]
Yes thats also used in sqldeveloper

What I meant to ask was, wether we could point the user to the direct download link in the message (isntead of the one listing the download options)

**Comment by Mic92** [comment]
you can create a message for users like this: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/oracle-instantclient/default.nix#L12

**Comment by Eisfreak7** [comment]
Yes but is it allowed to point directly to the file in that message? I'd guess probably not

**Comment by Mic92** [comment]
@Eisfreak7 what do you mean by pointing directly to the file? The website requires authentication so user interaction is required AFAIK.

**Comment by Eisfreak7** [comment]
Oh I assumed that you just need to login to see the link. But you're right, a simple curl without being logged in doesn't work.

Then maybe I'll just write a more specific message explaining what to do and which file to choose.

**Comment by Eisfreak7** [comment]
I added a detailed message explaining the process and updated to the newest version. This should be ready to merge now.

**Comment by Mic92** [comment]
Ok. I have no account there, but the code looks reasonable.

**Pull request merged**
