### PR TITLE
cmake: 3.29.3 -> 3.29.6

### PR DESCRIPTION
**Pull request by afh**
## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by AndersonTorres** [comment]
As always, we need Darwin testers, especially for the Darwin-specific patches.

**Comment by afh** [comment]
Happy to test on `aarch64-darwin`, @AndersonTorres, unfortunately a full build of this PR (`nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`) seems a bit too much for my workstation.
Could you list a few commands with which the most relevant Darwin-related packages and patches could be tested?

**Comment by AndersonTorres** [comment]
I just need to know if it builds and runs.

For now I can't think on a serious package. Try `castxml`.

**Comment by afh** [comment]
@AndersonTorres, happy to report that `castxml` built successfully from this PR branch on `aarch64-darwin`:

```sh
% ./result/bin/castxml --version
castxml version 0.6.6

CastXML project maintained and supported by Kitware (kitware.com).

clang version 16.0.6
Target: aarch64-apple-darwin23.5.0
Thread model: posix
InstalledDir:
```

💁 Please note that the following message appeared during the build:
```
bad JSON log message from builder: [json.exception.parse_error.101] parse error at line 1, column 3: syntax error while parsing object key - unexpected end of input; expected string literal
```

If there's any other package you'd like me to build on darwin or test to run with castxml do let me know.

**Review by AndersonTorres — APPROVED** [review]

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by trofi** [comment]
`3.29.5` is out: https://cmake.org/cmake/help/v3.29/release/3.29.html#id3

**Comment by afh** [comment]
Thanks, @trofi, I've updated this PR accordingly. I'll report back the results from `nix build .#castxml` on `aarch64-darwin`.

**Comment by AMS21** [comment]
cmake version `3.29.6` is out now https://cmake.org/cmake/help/v3.29/release/3.29.html#id3

**Comment by afh** [comment]
When building `castxml` (Using `nix build .#castxml`) on `aarch64-darwin` the build for boehm-gc failed the first time around (see [boehm-gc-8.2.6.drv.log](https://github.com/user-attachments/files/15899763/boehm-gc-8.2.6.drv.log) for details). Building `castxml` again succeeded. I'm uncertain wether that is good enough for folks to judge whether this PR is acceptable for approval also on darwin.

**Comment by AndersonTorres** [comment]
As always we need Darwin maintainers.
Or, since this is a minor version bump and hopefully without breaking changes, just wait a month (so that no one can complain about not having sufficient time) and merge.

**Comment by emilazy** [comment]
Looks like a nondeterministic test failure in a package that doesn't even build with CMake; I can’t imagine it has anything to do with this update. Please do ping the darwin-maintainers group if you need people to look at anything on macOS; we can’t know about issues or people needing help if nobody notifies us about them.

**Review by SuperSandro2000 — APPROVED** [review]

**Pull request merged**
